g4sim: EventAction Class Reference
EventAction Class Reference
#include <EventAction.hh>
Public Member Functions
EventAction ()
virtual ~EventAction ()
void BeginOfEventAction (const G4Event *)
void EndOfEventAction (const G4Event *)
Private Attributes
RunAction * runAct
EventActionMessenger * eventMessenger
Detailed Description
Definition at line 48 of file EventAction.hh.
Constructor & Destructor Documentation
EventAction::EventAction ()
Definition at line 59 of file EventAction.cc.
References eventMessenger, and runAct.
{
  runAct = (RunAction*)G4RunManager::GetRunManager()->GetUserRunAction();
  eventMessenger = new EventActionMessenger(this);
}
EventAction::~EventAction () [virtual]
Definition at line 67 of file EventAction.cc.
References eventMessenger.
{
  delete eventMessenger;
}
Member Function Documentation
void EventAction::BeginOfEventAction (const G4Event * evt)
Definition at line 74 of file EventAction.cc.
References MyAnalysisSvc::BeginOfEventAction(), and MyAnalysisSvc::GetMyAnalysisSvc().
{
        //deal with analysis
        MyAnalysisSvc::GetMyAnalysisSvc()->BeginOfEventAction();
}
void EventAction::EndOfEventAction (const G4Event * evt)
Definition at line 82 of file EventAction.cc.
References MyAnalysisSvc::EndOfEventAction(), and MyAnalysisSvc::GetMyAnalysisSvc().
{
        //deal with analysis
        MyAnalysisSvc::GetMyAnalysisSvc()->EndOfEventAction(evt);
}
Member Data Documentation
EventActionMessenger* EventAction::eventMessenger [private]
Definition at line 60 of file EventAction.hh.
Referenced by EventAction(), and ~EventAction().
RunAction* EventAction::runAct [private]
Definition at line 58 of file EventAction.hh.
Referenced by EventAction().
The documentation for this class was generated from the following files:
include/EventAction.hh
src/EventAction.cc