g4sim: FieldMapImpl Class Reference
FieldMapImpl Class Reference
Public Member Functions
FieldMapImpl ()
virtual ~FieldMapImpl ()
virtual void getFieldValue (const G4double local[4], G4double field[6]) const =0
virtual bool handleCommand (InputFile &in, MyBLArgumentVector &argv, MyBLArgumentMap &namedArgs)=0
virtual void getBoundingPoint (int i, G4double point[4])=0
virtual bool hasB ()=0
virtual bool hasE ()=0
bool readBlock (InputFile &in, float *values, int nRows, int nCols, G4double units)
virtual bool writeFile (FILE *f)=0
Detailed Description
class FieldMapImpl -- base class for a FieldMap implementation
Definition at line 87 of file MyBLFieldMap.cc.
Constructor & Destructor Documentation
FieldMapImpl::FieldMapImpl () [inline]
Definition at line 89 of file MyBLFieldMap.cc.
{ }
virtual FieldMapImpl::~FieldMapImpl () [inline, virtual]
Definition at line 90 of file MyBLFieldMap.cc.
{ }
Member Function Documentation
virtual void FieldMapImpl::getBoundingPoint (int i, G4double point[4]) [pure virtual]
Implemented in GridImpl, and CylinderImpl.
Referenced by MyBLFieldMap::getBoundingPoint().
virtual void FieldMapImpl::getFieldValue (const G4double local[4], G4double field[6]) const [pure virtual]
Implemented in GridImpl, and CylinderImpl.
Referenced by MyBLFieldMap::getFieldValue().
virtual bool FieldMapImpl::handleCommand (InputFile & in, MyBLArgumentVector & argv, MyBLArgumentMap & namedArgs) [pure virtual]
Implemented in GridImpl, and CylinderImpl.
Referenced by MyBLFieldMap::readFile().
virtual bool FieldMapImpl::hasB () [pure virtual]
Implemented in GridImpl, and CylinderImpl.
Referenced by MyBLFieldMap::hasB().
virtual bool FieldMapImpl::hasE () [pure virtual]
Implemented in GridImpl, and CylinderImpl.
Referenced by MyBLFieldMap::hasE().
bool FieldMapImpl::readBlock (InputFile & in, float * values, int nRows, int nCols, G4double units)
Definition at line 414 of file MyBLFieldMap.cc.
References InputFile::getline().
Referenced by CylinderImpl::handleCommand().
                {
    while(nRows-- > 0) {
        char *line = in.getline();
        if(!line) return false;
        char *p=line;
        for(int i=0; i<nCols; ++i) {
            while(isspace(*p)) ++p;
            if(*p == '\0') return false;
            *values++ = strtod(p,&p) * units;
            if(*p == ',') ++p;
        }
    }
    return true;
}
virtual bool FieldMapImpl::writeFile (FILE * f) [pure virtual]
Implemented in GridImpl, and CylinderImpl.
Referenced by MyBLFieldMap::writeFile().
The documentation for this class was generated from the following file:
src/MyBLFieldMap.cc