g4sim: MyFieldMap Class Reference
MyFieldMap Class Reference
#include <MyFieldMap.hh>
Public Member Functions
MyFieldMap (G4String fieldMapFile, G4double current, G4double gradient, G4double timeOffset, G4LogicalVolume *fieldVolume)
~MyFieldMap ()
void addFieldValue (const G4double point[4], G4double field[6]) const
void setRot (G4RotationMatrix *aRotMat)
virtual G4double getMaxLength ()
return the length used for the bounding box
virtual G4double getMaxWidth ()
return the width used for the bounding box
virtual G4double getMaxHeight ()
return the height used for the bounding box
void construct ()
the actual implementation constructs the MyElementField
G4ThreeVector getCenter ()
void setCenter (G4ThreeVector)
G4double const * getBoundingBox ()
void setMaxStep (G4double s)
setMaxStep(G4double) sets the max. step size
G4double getMaxStep ()
getMaxStep() returns the max. step size
void setColor (G4String c)
setColor(G4String) sets the color
G4String getColor ()
getColor() returns the color
void setGlobalPoint (const G4double point[4])
bool isInBoundingBox (const G4double point[4]) const
Static Public Member Functions
static G4VisAttributes * getVisAttribute (G4String color)
getVisAttribute() returns the appropriate G4VisAttributes.
Protected Attributes
G4LogicalVolume * lvolume
G4AffineTransform global2local
Private Attributes
G4RotationMatrix * fRotation
G4double fCurrent
G4double fGradient
G4double fTimeOffset
MyBLFieldMap * fMap
G4double fMaxLength
G4double fMaxWidth
G4double fMaxHeight
Detailed Description
Definition at line 13 of file MyFieldMap.hh.
Constructor & Destructor Documentation
MyFieldMap::MyFieldMap (G4String fieldMapFile, G4double current, G4double gradient, G4double timeOffset, G4LogicalVolume * fieldVolume)
Definition at line 17 of file MyFieldMap.cc.
References fCurrent, fGradient, fMap, fMaxHeight, fMaxLength, fMaxWidth, fRotation, fTimeOffset, and MyBLFieldMap::readFile().
: MyElementField(G4ThreeVector(0,0,0),fieldVolume) {
    // This constructor must be called after creating the logical
    // field volume and before defining any detectors in the field
    // volume.
    fMap = new MyBLFieldMap();
    fMap->readFile(mapFileName);
    fCurrent = current;
    fGradient = gradient;
    fRotation = NULL;
    // AK20110616: timeOffset doesn't appear to be used for anything
    fTimeOffset = timeOffset;
    // Set dimensions
    if (fieldVolume->GetSolid()->GetEntityType() == "G4Tubs") {
        fMaxLength = 2*((G4Tubs*)fieldVolume->GetSolid())->GetZHalfLength();
        fMaxWidth = 2*((G4Tubs*)fieldVolume->GetSolid())->GetOuterRadius();
        fMaxHeight = fMaxWidth;
    }
    else if (fieldVolume->GetSolid()->GetEntityType()== "G4Box") {
        fMaxLength = 2*((G4Box*)fieldVolume->GetSolid())->GetZHalfLength();
        fMaxWidth = 2*((G4Box*)fieldVolume->GetSolid())->GetXHalfLength();
        fMaxHeight = 2*((G4Box*)fieldVolume->GetSolid())->GetYHalfLength();
    }
}
MyFieldMap::~MyFieldMap ()
Definition at line 48 of file MyFieldMap.cc.
References fMap, and fRotation.
{
    delete fRotation;
    delete fMap;
}
Member Function Documentation
void MyFieldMap::addFieldValue (const G4double point[4], G4double field[6]) const [virtual]
addFieldValue() will add the field value for this element to field[]. Implementations must be sure to verify that point[] is within the field region, and do nothing if not. point[] is in global coordinates and geant4 units; x,y,z,t. field[] is in geant4 units; Bx,By,Bz,Ex,Ey,Ez. For efficiency, the caller may (but need not) call isInBoundingBox(point), and only call this function if that returns true.
Implements MyElementField.
Definition at line 54 of file MyFieldMap.cc.
References fCurrent, fGradient, fMap, fRotation, MyBLFieldMap::getFieldValue(), MyElementField::global2local, MyBLFieldMap::hasB(), and MyBLFieldMap::hasE().
{
    G4ThreeVector global(point[0],point[1],point[2]);
    G4ThreeVector local;
    local = global2local.TransformPoint(global);
    G4double relPoint[4]= {local[0],local[1],local[2],point[3]};
    G4double f[6];
    f[0] = f[1] = f[2] = f[3] = f[4] = f[5] = 0.0;
    fMap->getFieldValue(relPoint,f,fCurrent,fGradient);
    if(fRotation) {
        if (fMap->hasB()) {
            G4ThreeVector B(f[0],f[1],f[2]);
            B = *fRotation * B;
            field[0] += B[0];
            field[1] += B[1];
            field[2] += B[2];
        }
        if (fMap->hasE()) {
            G4ThreeVector E(f[3],f[4],f[5]);
            E = *fRotation * E;
            field[3] += E[0];
            field[4] += E[1];
            field[5] += E[2];
        }
    }
    else {
        if (fMap->hasB()) {
            field[0] += f[0];
            field[1] += f[1];
            field[2] += f[2];
        }
        if (fMap->hasE()) {
            field[3] += f[3];
            field[4] += f[4];
            field[5] += f[5];
        }
    }
}
void MyElementField::construct () [inherited]
the actual implementation constructs the MyElementField
Definition at line 74 of file MyElementField.cc.
References MyElementField::aNavigator, MyElementField::center, MyElementField::getMaxHeight(), MyElementField::getMaxLength(), MyElementField::getMaxWidth(), MyElementField::global2local, MyElementField::lvolume, and MyElementField::setGlobalPoint().
{
    G4Navigator* theNavigator =
        G4TransportationManager::GetTransportationManager()->
        GetNavigatorForTracking();
//    G4cout << "-AK- In MyElementField::construct, lvolume is "
//        << lvolume->GetName() << G4endl;
    if (!aNavigator) {
        aNavigator = new G4Navigator();
        if ( theNavigator->GetWorldVolume() )
            aNavigator->SetWorldVolume(theNavigator->GetWorldVolume());
    }
    G4GeometryManager* geomManager = G4GeometryManager::GetInstance();
    if (!geomManager->IsGeometryClosed()) {
        geomManager->OpenGeometry();
        geomManager->CloseGeometry(true);
    }
    aNavigator->LocateGlobalPointAndSetup(center,0,false);
//    G4cout << "-AK- MyElementField::construct, center is " << center << G4endl;
    G4TouchableHistoryHandle fTouchable = aNavigator->
        CreateTouchableHistoryHandle();
    G4int depth = fTouchable->GetHistoryDepth();
//    G4cout << "-AK- fTouchable->GetHistoryDepth is " << depth << G4endl;
    for (G4int i = 0; i<depth; ++i) {
//        G4cout << "-AK- In MyElementField::construct, volume is "
 //           << fTouchable->GetVolume()->GetLogicalVolume()->GetName() << G4endl;
        if(fTouchable->GetVolume()->GetLogicalVolume() == lvolume) {
//            G4cout << "-AK- In MyElementField::construct, found lvolume "
//                << lvolume->GetName() << G4endl;
            break;
        }
        fTouchable->MoveUpHistory();
    }
    // set global2local transform
    global2local = fTouchable->GetHistory()->GetTopTransform();
    // set global bounding box
    G4double local[4], global[4];
    G4ThreeVector globalPosition;
    local[3] = 0.0;
    for (int i=0; i<2; ++i) {
        local[0] = (i==0 ? -1.0 : 1.0) * getMaxWidth()/2.;
        for (int j=0; j<2; ++j) {
            local[1] = (j==0 ? -1.0 : 1.0) * getMaxHeight()/2.;
            for (int k=0; k<2; ++k) {
                local[2] = (k==0 ? -1.0 : 1.0) * getMaxLength()/2.;
                G4ThreeVector localPosition(local[0],local[1],local[2]);
                globalPosition =
                    global2local.Inverse().TransformPoint(localPosition);
                global[0] = globalPosition.x();
                global[1] = globalPosition.y();
                global[2] = globalPosition.z();
                setGlobalPoint(global);
                //G4cout << "-AK- MyElementField::construct, bounding box global pos is"
                //     << globalPosition << G4endl;
            }
        }
    }
}
G4double const * MyElementField::getBoundingBox () [inherited]
Definition at line 165 of file MyElementField.cc.
References MyElementField::boundingBox, MyElementField::maxX, MyElementField::maxY, MyElementField::maxZ, MyElementField::minX, MyElementField::minY, and MyElementField::minZ.
{
    if(boundingBox==NULL) {
        boundingBox= new G4double[6];
    }
    boundingBox[0] = minX;
    boundingBox[1] = maxX;
    boundingBox[2] = minY;
    boundingBox[3] = maxY;
    boundingBox[4] = minZ;
    boundingBox[5] = maxZ;
    return boundingBox;
}
G4ThreeVector MyElementField::getCenter () [inline, inherited]
Definition at line 75 of file MyElementField.hh.
References MyElementField::center.
{return center;}
G4String MyElementField::getColor () [inline, inherited]
getColor() returns the color
Definition at line 100 of file MyElementField.hh.
References MyElementField::color.
{ return color; }
virtual G4double MyFieldMap::getMaxHeight () [inline, virtual]
return the height used for the bounding box
Implements MyElementField.
Definition at line 36 of file MyFieldMap.hh.
References fMaxHeight.
{ return fMaxHeight; }
virtual G4double MyFieldMap::getMaxLength () [inline, virtual]
return the length used for the bounding box
Implements MyElementField.
Definition at line 30 of file MyFieldMap.hh.
References fMaxLength.
{ return fMaxLength; }
G4double MyElementField::getMaxStep () [inline, inherited]
getMaxStep() returns the max. step size
Definition at line 91 of file MyElementField.hh.
References MyElementField::maxStep.
{ return maxStep; }
virtual G4double MyFieldMap::getMaxWidth () [inline, virtual]
return the width used for the bounding box
Implements MyElementField.
Definition at line 33 of file MyFieldMap.hh.
References fMaxWidth.
{ return fMaxWidth; }
G4VisAttributes * MyElementField::getVisAttribute (G4String color) [static, inherited]
getVisAttribute() returns the appropriate G4VisAttributes.
Definition at line 145 of file MyElementField.cc.
Referenced by MyElementField::setColor().
{
    G4VisAttributes* p = NULL;
    if(color.size() > 0 &&
    (isdigit(color.c_str()[0]) || color.c_str()[0] == '.')) {
        G4double red=0.0, green=0.0, blue=0.0;
        if (sscanf(color.c_str(),"%lf,%lf,%lf",&red,&green,&blue) == 3) {
            p = new G4VisAttributes(true,G4Color(red,green,blue));
        }
        else {
            G4cout << " Invalid color " << color << G4endl;
        }
    }
    if (!p) p = new G4VisAttributes(G4VisAttributes::Invisible);
    p->SetDaughtersInvisible(false);
    return p;
}
bool MyElementField::isInBoundingBox (const G4double point[4]) const [inline, inherited]
isInBoundingBox() returns true if the point is within the global bounding box - global coordinates.
Definition at line 122 of file MyElementField.hh.
References MyElementField::maxX, MyElementField::maxY, MyElementField::maxZ, MyElementField::minX, MyElementField::minY, and MyElementField::minZ.
Referenced by MyGlobalField::GetFieldValue().
{
            if(point[2] < minZ || point[2] > maxZ) return false;
            if(point[0] < minX || point[0] > maxX) return false;
            if(point[1] < minY || point[1] > maxY) return false;
            return true;
        }
void MyElementField::setCenter (G4ThreeVector c) [inherited]
Definition at line 179 of file MyElementField.cc.
References MyElementField::center.
{
    center = c;
}
void MyElementField::setColor (G4String c) [inline, inherited]
setColor(G4String) sets the color
Definition at line 94 of file MyElementField.hh.
References MyElementField::color, MyElementField::getVisAttribute(), and MyElementField::lvolume.
{
            color = c;
            lvolume->SetVisAttributes(getVisAttribute(color));
        }
void MyElementField::setGlobalPoint (const G4double point[4]) [inline, inherited]
setGlobalPoint() ensures that the point is within the global bounding box of this ElementField's global coordinates. Normally called 8 times for the corners of the local bounding box, after a local->global coordinate transform. If never called, the global bounding box is infinite. BEWARE: if called only once, the bounding box is just a point.
Definition at line 111 of file MyElementField.hh.
References MyElementField::maxX, MyElementField::maxY, MyElementField::maxZ, MyElementField::minX, MyElementField::minY, and MyElementField::minZ.
Referenced by MyElementField::construct().
{
            if(minX == -DBL_MAX || minX > point[0]) minX = point[0];
            if(minY == -DBL_MAX || minY > point[1]) minY = point[1];
            if(minZ == -DBL_MAX || minZ > point[2]) minZ = point[2];
            if(maxX ==  DBL_MAX || maxX < point[0]) maxX = point[0];
            if(maxY ==  DBL_MAX || maxY < point[1]) maxY = point[1];
            if(maxZ ==  DBL_MAX || maxZ < point[2]) maxZ = point[2];
        }
void MyElementField::setMaxStep (G4double s) [inline, inherited]
setMaxStep(G4double) sets the max. step size
Definition at line 84 of file MyElementField.hh.
References MyElementField::lvolume, MyElementField::maxStep, and MyElementField::userLimits.
{
            maxStep = s;
            userLimits->SetMaxAllowedStep(maxStep);
            lvolume->SetUserLimits(userLimits);
        }
void MyFieldMap::setRot (G4RotationMatrix * aRotMat)
Definition at line 96 of file MyFieldMap.cc.
References fRotation.
{
    // aRotMat is the rotation matrix used when placing a physical object
    fRotation = new G4RotationMatrix(aRotMat->inverse());
}
Member Data Documentation
G4double MyFieldMap::fCurrent [private]
Definition at line 40 of file MyFieldMap.hh.
Referenced by addFieldValue(), and MyFieldMap().
G4double MyFieldMap::fGradient [private]
Definition at line 41 of file MyFieldMap.hh.
Referenced by addFieldValue(), and MyFieldMap().
MyBLFieldMap* MyFieldMap::fMap [private]
Definition at line 43 of file MyFieldMap.hh.
Referenced by addFieldValue(), MyFieldMap(), and ~MyFieldMap().
G4double MyFieldMap::fMaxHeight [private]
Definition at line 47 of file MyFieldMap.hh.
Referenced by getMaxHeight(), and MyFieldMap().
G4double MyFieldMap::fMaxLength [private]
Definition at line 45 of file MyFieldMap.hh.
Referenced by getMaxLength(), and MyFieldMap().
G4double MyFieldMap::fMaxWidth [private]
Definition at line 46 of file MyFieldMap.hh.
Referenced by getMaxWidth(), and MyFieldMap().
G4RotationMatrix* MyFieldMap::fRotation [private]
Definition at line 39 of file MyFieldMap.hh.
Referenced by addFieldValue(), MyFieldMap(), setRot(), and ~MyFieldMap().
G4double MyFieldMap::fTimeOffset [private]
Definition at line 42 of file MyFieldMap.hh.
Referenced by MyFieldMap().
G4AffineTransform MyElementField::global2local [protected, inherited]
Definition at line 149 of file MyElementField.hh.
Referenced by addFieldValue(), and MyElementField::construct().
G4LogicalVolume* MyElementField::lvolume [protected, inherited]
Definition at line 147 of file MyElementField.hh.
Referenced by MyElementField::construct(), MyElementField::MyElementField(), MyElementField::setColor(), and MyElementField::setMaxStep().
The documentation for this class was generated from the following files:
include/MyFieldMap.hh
src/MyFieldMap.cc