g4sim: InputFile Class Reference
InputFile Class Reference
Public Member Functions
InputFile (G4String filename, G4int _maxline=1024)
~InputFile ()
const char * filename ()
bool good ()
int linenumber ()
char * getline ()
void setMaxline (int _maxline)
void close ()
void repeatLine ()
Private Attributes
std::ifstream in
G4String name
char * line
int maxline
int lineno
bool repeatline
Detailed Description
class InputFile handles input file I/O
Definition at line 32 of file MyBLFieldMap.cc.
Constructor & Destructor Documentation
InputFile::InputFile (G4String filename, G4int _maxline = 1024) [inline]
Definition at line 40 of file MyBLFieldMap.cc.
References in, line, lineno, maxline, name, and repeatline.
                                                          : in(), name() {
            name = filename;
            in.open(name.c_str());
            maxline = _maxline;
            line = new char[maxline];
            assert(line != 0);
            lineno = 0;
            repeatline = false;
        }
InputFile::~InputFile () [inline]
Definition at line 49 of file MyBLFieldMap.cc.
References close().
{ close(); }
Member Function Documentation
void InputFile::close () [inline]
Definition at line 77 of file MyBLFieldMap.cc.
References in, and line.
Referenced by MyBLFieldMap::readFile(), and ~InputFile().
                     {
            if(line) {
                in.close(); delete line; line = 0;
            }
        }
const char* InputFile::filename () [inline]
Definition at line 50 of file MyBLFieldMap.cc.
References name.
Referenced by MyBLFieldMap::readFile().
{ return name.c_str(); }
char* InputFile::getline () [inline]
Definition at line 53 of file MyBLFieldMap.cc.
References in, line, lineno, maxline, and repeatline.
Referenced by CylinderImpl::handleCommand(), GridImpl::handleCommand(), FieldMapImpl::readBlock(), MyBLFieldMap::readFile(), and TimeImpl::readTime().
                        {                             // skips blank lines and comments
            if(repeatline) {
                repeatline = false;
                return line;
            }
            while(in.good()) {
                line[0] = '\0';
                in.getline(line,maxline);
                ++lineno;
                if(line[0] == '*')
                    printf("%s\n",line);
                if(line[0] == '\0' || line[0] == '#' || line[0] == '*')
                    continue;
                return line;
            }
            return 0;
        }
bool InputFile::good () [inline]
Definition at line 51 of file MyBLFieldMap.cc.
References in.
Referenced by MyBLFieldMap::readFile().
{ return in.good(); }
int InputFile::linenumber () [inline]
Definition at line 52 of file MyBLFieldMap.cc.
References lineno.
Referenced by CylinderImpl::handleCommand(), GridImpl::handleCommand(), and MyBLFieldMap::readFile().
{ return lineno; }
void InputFile::repeatLine () [inline]
Definition at line 82 of file MyBLFieldMap.cc.
References repeatline.
Referenced by CylinderImpl::handleCommand(), GridImpl::handleCommand(), and TimeImpl::readTime().
{ repeatline = true; }
void InputFile::setMaxline (int _maxline) [inline]
Definition at line 70 of file MyBLFieldMap.cc.
References line, and maxline.
Referenced by MyBLFieldMap::readFile().
{
            maxline = _maxline;
            assert(maxline >= 80);
            if(line) delete line;
            line = new char[maxline];
            assert(line != 0);
        }
Member Data Documentation
std::ifstream InputFile::in [private]
Definition at line 33 of file MyBLFieldMap.cc.
Referenced by close(), getline(), good(), and InputFile().
char* InputFile::line [private]
Definition at line 35 of file MyBLFieldMap.cc.
Referenced by close(), getline(), InputFile(), and setMaxline().
int InputFile::lineno [private]
Definition at line 37 of file MyBLFieldMap.cc.
Referenced by getline(), InputFile(), and linenumber().
int InputFile::maxline [private]
Definition at line 36 of file MyBLFieldMap.cc.
Referenced by getline(), InputFile(), and setMaxline().
G4String InputFile::name [private]
Definition at line 34 of file MyBLFieldMap.cc.
Referenced by filename(), and InputFile().
bool InputFile::repeatline [private]
Definition at line 38 of file MyBLFieldMap.cc.
Referenced by getline(), InputFile(), and repeatLine().
The documentation for this class was generated from the following file:
src/MyBLFieldMap.cc