g4sim: SimpleGeometryParameter Class Reference
SimpleGeometryParameter Class Reference
#include <SimpleGeometryParameter.hh>
Public Member Functions
SimpleGeometryParameter (G4String name, G4String opt="")
virtual ~SimpleGeometryParameter (void)
virtual void InitFromFile (G4String)
virtual void Calculate ()
virtual void Dump ()
int GetValue (G4String)
void Preset ()
bool CheckInfo ()
void DumpInfo (void)
G4int get_VolIndex (G4String name)
G4int get_VolNo ()
G4double get_PosX (G4int VolId, G4int j=0)
G4double get_PosY (G4int VolId, G4int j=0)
G4double get_PosZ (G4int VolId, G4int j=0)
G4String get_name (G4int VolId)
G4String get_SDName (G4int VolId)
G4String get_MotherName (G4int VolId)
G4String get_material (G4int VolId)
G4int get_SRepNo (G4int VolId)
G4int get_RepNo (G4int VolId)
G4String get_SolidType (G4int VolId)
G4int get_SolidIndex (G4int VolId)
G4double get_Ephi (G4int VolId, G4int j=0)
G4double get_Etheta (G4int VolId, G4int j=0)
G4double get_Epsi (G4int VolId, G4int j=0)
G4bool get_SolidBoolean (G4int VolId)
G4int get_BoxNo ()
G4double get_Box_X (G4int BoxId, G4int j=0)
G4double get_Box_Y (G4int BoxId, G4int j=0)
G4double get_Box_Z (G4int BoxId, G4int j=0)
G4int get_EllipticalTubeNo ()
G4double get_EllipticalTube_X (G4int EllipticalTubeId, G4int j=0)
G4double get_EllipticalTube_Y (G4int EllipticalTubeId, G4int j=0)
G4double get_EllipticalTube_Z (G4int EllipticalTubeId, G4int j=0)
G4int get_TubsNo ()
G4double get_Tubs_RMax (G4int TubsId, G4int j=0)
G4double get_Tubs_RMin (G4int TubsId, G4int j=0)
G4double get_Tubs_Length (G4int TubsId, G4int j=0)
G4double get_Tubs_StartAng (G4int TubsId, G4int j=0)
G4double get_Tubs_SpanAng (G4int TubsId, G4int j=0)
G4int get_TorusNo ()
G4double get_Torus_RMax (G4int TorusId, G4int j=0)
G4double get_Torus_RMin (G4int TorusId, G4int j=0)
G4double get_Torus_Rtor (G4int TorusId, G4int j=0)
G4double get_Torus_StartAng (G4int TorusId, G4int j=0)
G4double get_Torus_SpanAng (G4int TorusId, G4int j=0)
G4int get_SphereNo ()
G4double get_Sphere_RMax (G4int SphereId, G4int j=0)
G4double get_Sphere_RMin (G4int SphereId, G4int j=0)
G4double get_Sphere_StartPhi (G4int SphereId, G4int j=0)
G4double get_Sphere_SpanPhi (G4int SphereId, G4int j=0)
G4double get_Sphere_StartTheta (G4int SphereId, G4int j=0)
G4double get_Sphere_SpanTheta (G4int SphereId, G4int j=0)
G4int get_HypeNo ()
G4double get_Hype_innerRadius (G4int HypeId, G4int j=0)
G4double get_Hype_outerRadius (G4int HypeId, G4int j=0)
G4double get_Hype_innerStereo (G4int HypeId, G4int j=0)
G4double get_Hype_outerStereo (G4int HypeId, G4int j=0)
G4double get_Hype_Length (G4int HypeId, G4int j=0)
G4int get_TwistedTubsNo ()
G4double get_TwistedTubs_twistedangle (G4int TwistedTubsId, G4int j=0)
G4double get_TwistedTubs_endinnerrad (G4int TwistedTubsId, G4int j=0)
G4double get_TwistedTubs_endouterrad (G4int TwistedTubsId, G4int j=0)
G4double get_TwistedTubs_Length (G4int TwistedTubsId, G4int j=0)
G4double get_TwistedTubs_dphi (G4int TwistedTubsId, G4int j=0)
G4int get_ConsNo ()
G4double get_Cons_RMax1 (G4int ConsId, G4int j=0)
G4double get_Cons_RMin1 (G4int ConsId, G4int j=0)
G4double get_Cons_RMax2 (G4int ConsId, G4int j=0)
G4double get_Cons_RMin2 (G4int ConsId, G4int j=0)
G4double get_Cons_Length (G4int ConsId, G4int j=0)
G4double get_Cons_StartAng (G4int ConsId, G4int j=0)
G4double get_Cons_SpanAng (G4int ConsId, G4int j=0)
G4int get_PolyconeNo ()
G4int get_Polycone_numZ (G4int PolyconeId, G4int j=0)
G4double get_Polycone_RMax (G4int PolyconeId, G4int i, G4int j=0)
G4double get_Polycone_RMin (G4int PolyconeId, G4int i, G4int j=0)
G4double get_Polycone_Z (G4int PolyconeId, G4int i, G4int j=0)
G4double get_Polycone_StartAng (G4int PolyconeId, G4int j=0)
G4double get_Polycone_SpanAng (G4int PolyconeId, G4int j=0)
G4int get_ExtrudedSolidNo ()
G4int get_ExtrudedSolid_numZ (G4int ExtrudedSolidId, G4int j=0)
G4int get_ExtrudedSolid_numP (G4int ExtrudedSolidId, G4int j=0)
G4double get_ExtrudedSolid_X (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4double get_ExtrudedSolid_Y (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4double get_ExtrudedSolid_Z (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4double get_ExtrudedSolid_X0 (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4double get_ExtrudedSolid_Y0 (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4double get_ExtrudedSolid_Scale (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4String get_BooleanSolid_type (G4int BooleanSolidId)
G4String get_BooleanSolid_sol1 (G4int BooleanSolidId)
G4String get_BooleanSolid_sol2 (G4int BooleanSolidId)
G4double get_BooleanSolid_Ephi (G4int BooleanSolidId, G4int j=0)
G4double get_BooleanSolid_Etheta (G4int BooleanSolidId, G4int j=0)
G4double get_BooleanSolid_Epsi (G4int BooleanSolidId, G4int j=0)
G4double get_BooleanSolid_PosX (G4int BooleanSolidId, G4int j=0)
G4double get_BooleanSolid_PosY (G4int BooleanSolidId, G4int j=0)
G4double get_BooleanSolid_PosZ (G4int BooleanSolidId, G4int j=0)
bool get_vis (G4int VolId)
G4double get_r (G4int VolId)
G4double get_g (G4int VolId)
G4double get_b (G4int VolId)
G4double get_t (G4int VolId)
void set_PosX (G4String type, G4int i, G4double val, G4int j=0)
void set_PosY (G4String type, G4int i, G4double val, G4int j=0)
void set_PosZ (G4String type, G4int i, G4double val, G4int j=0)
void set_name (G4String type, G4int i, G4String val)
void set_SDName (G4String type, G4int i, G4String val)
void set_MotherName (G4String type, G4int i, G4String val)
void set_material (G4String type, G4int i, G4String val)
void set_SRepNo (G4String type, G4int i, G4int val)
void set_RepNo (G4String type, G4int i, G4int val)
void set_Ephi (G4String type, G4int i, G4double val, G4int j=0)
void set_Etheta (G4String type, G4int i, G4double val, G4int j=0)
void set_Epsi (G4String type, G4int i, G4double val, G4int j=0)
void set_SolidBoolean (G4String type, G4int i, G4int val)
void set_name (G4String name, G4String val)
void set_SDName (G4String name, G4String val)
void set_MotherName (G4String name, G4String val)
void set_material (G4String name, G4String val)
void set_SRepNo (G4String name, G4int val)
void set_RepNo (G4String name, G4int val)
void set_SolidBoolean (G4String name, G4int val)
void set_PosX (G4String name, G4double val, G4int j=0)
void set_PosY (G4String name, G4double val, G4int j=0)
void set_PosZ (G4String name, G4double val, G4int j=0)
void set_Ephi (G4String name, G4double val, G4int j=0)
void set_Etheta (G4String name, G4double val, G4int j=0)
void set_Epsi (G4String name, G4double val, G4int j=0)
void set_Box_X (G4int i, G4double val, G4int j=0)
void set_Box_Y (G4int i, G4double val, G4int j=0)
void set_Box_Z (G4int i, G4double val, G4int j=0)
void set_Box_X (G4String name, G4double val, G4int j=0)
void set_Box_Y (G4String name, G4double val, G4int j=0)
void set_Box_Z (G4String name, G4double val, G4int j=0)
void set_EllipticalTube_X (G4int i, G4double val, G4int j=0)
void set_EllipticalTube_Y (G4int i, G4double val, G4int j=0)
void set_EllipticalTube_Z (G4int i, G4double val, G4int j=0)
void set_EllipticalTube_X (G4String name, G4double val, G4int j=0)
void set_EllipticalTube_Y (G4String name, G4double val, G4int j=0)
void set_EllipticalTube_Z (G4String name, G4double val, G4int j=0)
void set_Tubs_RMax (G4int i, G4double val, G4int j=0)
void set_Tubs_RMin (G4int i, G4double val, G4int j=0)
void set_Tubs_Length (G4int i, G4double val, G4int j=0)
void set_Tubs_StartAng (G4int i, G4double val, G4int j=0)
void set_Tubs_SpanAng (G4int i, G4double val, G4int j=0)
void set_Tubs_RMax (G4String name, G4double val, G4int j=0)
void set_Tubs_RMin (G4String name, G4double val, G4int j=0)
void set_Tubs_Length (G4String name, G4double val, G4int j=0)
void set_Tubs_StartAng (G4String name, G4double val, G4int j=0)
void set_Tubs_SpanAng (G4String name, G4double val, G4int j=0)
void set_Torus_RMax (G4int i, G4double val, G4int j=0)
void set_Torus_RMin (G4int i, G4double val, G4int j=0)
void set_Torus_Rtor (G4int i, G4double val, G4int j=0)
void set_Torus_StartAng (G4int i, G4double val, G4int j=0)
void set_Torus_SpanAng (G4int i, G4double val, G4int j=0)
void set_Torus_RMax (G4String name, G4double val, G4int j=0)
void set_Torus_RMin (G4String name, G4double val, G4int j=0)
void set_Torus_Rtor (G4String name, G4double val, G4int j=0)
void set_Torus_StartAng (G4String name, G4double val, G4int j=0)
void set_Torus_SpanAng (G4String name, G4double val, G4int j=0)
void set_Sphere_RMax (G4int i, G4double val, G4int j=0)
void set_Sphere_RMin (G4int i, G4double val, G4int j=0)
void set_Sphere_StartPhi (G4int i, G4double val, G4int j=0)
void set_Sphere_SpanPhi (G4int i, G4double val, G4int j=0)
void set_Sphere_StartTheta (G4int i, G4double val, G4int j=0)
void set_Sphere_SpanTheta (G4int i, G4double val, G4int j=0)
void set_Sphere_RMax (G4String name, G4double val, G4int j=0)
void set_Sphere_RMin (G4String name, G4double val, G4int j=0)
void set_Sphere_StartPhi (G4String name, G4double val, G4int j=0)
void set_Sphere_SpanPhi (G4String name, G4double val, G4int j=0)
void set_Sphere_StartTheta (G4String name, G4double val, G4int j=0)
void set_Sphere_SpanTheta (G4String name, G4double val, G4int j=0)
void set_Hype_innerRadius (G4int i, G4double val, G4int j=0)
void set_Hype_outerRadius (G4int i, G4double val, G4int j=0)
void set_Hype_innerStereo (G4int i, G4double val, G4int j=0)
void set_Hype_outerStereo (G4int i, G4double val, G4int j=0)
void set_Hype_Length (G4int i, G4double val, G4int j=0)
void set_Hype_innerRadius (G4String name, G4double val, G4int j=0)
void set_Hype_outerRadius (G4String name, G4double val, G4int j=0)
void set_Hype_innerStereo (G4String name, G4double val, G4int j=0)
void set_Hype_outerStereo (G4String name, G4double val, G4int j=0)
void set_Hype_Length (G4String name, G4double val, G4int j=0)
void set_TwistedTubs_twistedangle (G4int i, G4double val, G4int j=0)
void set_TwistedTubs_endinnerrad (G4int i, G4double val, G4int j=0)
void set_TwistedTubs_endouterrad (G4int i, G4double val, G4int j=0)
void set_TwistedTubs_Length (G4int i, G4double val, G4int j=0)
void set_TwistedTubs_dphi (G4int i, G4double val, G4int j=0)
void set_TwistedTubs_twistedangle (G4String name, G4double val, G4int j=0)
void set_TwistedTubs_endinnerrad (G4String name, G4double val, G4int j=0)
void set_TwistedTubs_endouterrad (G4String name, G4double val, G4int j=0)
void set_TwistedTubs_Length (G4String name, G4double val, G4int j=0)
void set_TwistedTubs_dphi (G4String name, G4double val, G4int j=0)
void set_Cons_RMax1 (G4int i, G4double val, G4int j=0)
void set_Cons_RMin1 (G4int i, G4double val, G4int j=0)
void set_Cons_RMax2 (G4int i, G4double val, G4int j=0)
void set_Cons_RMin2 (G4int i, G4double val, G4int j=0)
void set_Cons_Length (G4int i, G4double val, G4int j=0)
void set_Cons_StartAng (G4int i, G4double val, G4int j=0)
void set_Cons_SpanAng (G4int i, G4double val, G4int j=0)
void set_Cons_RMax1 (G4String name, G4double val, G4int j=0)
void set_Cons_RMin1 (G4String name, G4double val, G4int j=0)
void set_Cons_RMax2 (G4String name, G4double val, G4int j=0)
void set_Cons_RMin2 (G4String name, G4double val, G4int j=0)
void set_Cons_Length (G4String name, G4double val, G4int j=0)
void set_Cons_StartAng (G4String name, G4double val, G4int j=0)
void set_Cons_SpanAng (G4String name, G4double val, G4int j=0)
void set_Polycone_numZ (G4int PolyconeId, G4int val, G4int j=0)
void set_Polycone_RMax (G4int PolyconeId, G4int i, G4double val, G4int j=0)
void set_Polycone_RMin (G4int PolyconeId, G4int i, G4double val, G4int j=0)
void set_Polycone_Z (G4int PolyconeId, G4int i, G4double val, G4int j=0)
void set_Polycone_StartAng (G4int PolyconeId, G4double val, G4int j=0)
void set_Polycone_SpanAng (G4int PolyconeId, G4double val, G4int j=0)
void set_Polycone_numZ (G4String name, G4int val, G4int j=0)
void set_Polycone_RMax (G4String name, G4int iCone, G4double val, G4int j=0)
void set_Polycone_RMin (G4String name, G4int iCone, G4double val, G4int j=0)
void set_Polycone_Z (G4String name, G4int iCone, G4double val, G4int j=0)
void set_Polycone_StartAng (G4String name, G4double val, G4int j=0)
void set_Polycone_SpanAng (G4String name, G4double val, G4int j=0)
void set_ExtrudedSolid_numZ (G4int ExtrudedSolidId, G4int val, G4int j=0)
void set_ExtrudedSolid_numP (G4int ExtrudedSolidId, G4int val, G4int j=0)
void set_ExtrudedSolid_X (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_Y (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_Z (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_X0 (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_Y0 (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_Scale (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_numZ (G4String name, G4int val, G4int j=0)
void set_ExtrudedSolid_numP (G4String name, G4int val, G4int j=0)
void set_ExtrudedSolid_X (G4String name, G4int iCone, G4double val, G4int j=0)
void set_ExtrudedSolid_Y (G4String name, G4int iCone, G4double val, G4int j=0)
void set_ExtrudedSolid_Z (G4String name, G4int iCone, G4double val, G4int j=0)
void set_ExtrudedSolid_X0 (G4String name, G4int iCone, G4double val, G4int j=0)
void set_ExtrudedSolid_Y0 (G4String name, G4int iCone, G4double val, G4int j=0)
void set_ExtrudedSolid_Scale (G4String name, G4int iCone, G4double val, G4int j=0)
void set_BooleanSolid_type (G4int BooleanSolidId, G4String val)
void set_BooleanSolid_sol1 (G4int BooleanSolidId, G4String val)
void set_BooleanSolid_sol2 (G4int BooleanSolidId, G4String val)
void set_BooleanSolid_Ephi (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_Etheta (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_Epsi (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_PosX (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_PosY (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_PosZ (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_type (G4String name, G4String val)
void set_BooleanSolid_sol1 (G4String name, G4String val)
void set_BooleanSolid_sol2 (G4String name, G4String val)
void set_BooleanSolid_Ephi (G4String name, G4double val, G4int j=0)
void set_BooleanSolid_Etheta (G4String name, G4double val, G4int j=0)
void set_BooleanSolid_Epsi (G4String name, G4double val, G4int j=0)
void set_BooleanSolid_PosX (G4String name, G4double val, G4int j=0)
void set_BooleanSolid_PosY (G4String name, G4double val, G4int j=0)
void set_BooleanSolid_PosZ (G4String name, G4double val, G4int j=0)
void set_vis (G4String type, G4int i, bool val)
void set_r (G4String type, G4int i, G4double val)
void set_g (G4String type, G4int i, G4double val)
void set_b (G4String type, G4int i, G4double val)
void set_t (G4String type, G4int i, G4double val)
void set_vis (G4int i, bool val)
void set_r (G4int i, G4double val)
void set_g (G4int i, G4double val)
void set_b (G4int i, G4double val)
void set_t (G4int i, G4double val)
void set_vis (G4String name, bool val)
void set_r (G4String name, G4double val)
void set_g (G4String name, G4double val)
void set_b (G4String name, G4double val)
void set_t (G4String name, G4double val)
void get_RepCont (G4String RepCont, G4int &SRepNo, G4int &RepNo)
bool ISEMPTY (G4String)
void DEBUG (G4String content, int level=1)
bool get_checkoverlap ()
int get_VerboseLevel ()
G4String get_Name ()
G4String get_filename ()
void set_checkoverlap (bool val)
void set_VerboseLevel (int val)
void set_GeometryParameterMessenger (MyVGeometryParameterMessenger *val)
void set_Name (G4String val)
void set_filename (G4String val)
std::vector< G4String > GetWords (G4String formula)
bool FindMacro (G4String word, G4String &value)
void Replace (G4String &formula, G4String word, G4String value)
double CalFormula (G4String formula, int iRep=0)
G4String ReplaceMacro (G4String formula)
Static Public Attributes
static std::vector< G4String > knownValueNames
static std::vector< G4String > knownValues
Private Member Functions
void ReSetVis ()
int get_index (G4String type, G4int i)
bool check_VolId (int VolId)
bool check_BoxId (int BoxId)
bool check_EllipticalTubeId (int EllipticalTubeId)
bool check_BoxNo (int No)
bool check_TubsId (int TubsId)
bool check_TubsNo (int No)
bool check_TorusId (int TorusId)
bool check_TorusNo (int No)
bool check_SphereId (int SphereId)
bool check_SphereNo (int No)
bool check_HypeId (int HypeId)
bool check_HypeNo (int No)
bool check_TwistedTubsId (int TwistedTubsId)
bool check_TwistedTubsNo (int No)
bool check_ConsId (int ConsId)
bool check_ConsNo (int No)
bool check_PolyconeId (int PolyconeId)
bool check_PolyconeNo (int No)
bool check_ExtrudedSolidId (int ExtrudedSolidId)
bool check_ExtrudedSolidNo (int No)
bool check_BooleanSolidId (int BooleanSolidId)
bool check_BooleanSolidNo (int No)
void dump_general_header ()
void dump_general_note ()
void dump_general_value (G4int index, G4int j=0)
Private Attributes
G4int VolNo
std::vector< G4String > fPosX
std::vector< G4String > fPosY
std::vector< G4String > fPosZ
std::vector< G4String > fPosR
std::vector< G4String > fPosPhi
std::vector< G4String > fPosTheta
std::vector< G4String > PosType
std::vector< std::vector
< G4ThreeVector > > Pos
std::vector< G4String > Name
std::vector< G4String > MotherName
std::vector< G4String > SDName
std::vector< G4String > Material
std::vector< G4int > SRepNo
std::vector< G4int > RepNo
std::vector< G4String > SolidType
std::vector< G4int > SolidIndex
std::vector< std::vector
< G4double > > Ephi
std::vector< std::vector
< G4double > > Etheta
std::vector< std::vector
< G4double > > Epsi
std::vector< G4String > fEphi
std::vector< G4String > fEtheta
std::vector< G4String > fEpsi
std::vector< G4bool > SolidBoolean
G4int BoxNo
std::vector< std::vector
< G4double > > Box_X
std::vector< std::vector
< G4double > > Box_Y
std::vector< std::vector
< G4double > > Box_Z
std::vector< G4String > fBox_X
std::vector< G4String > fBox_Y
std::vector< G4String > fBox_Z
std::vector< G4int > Box_GenIndex
G4int EllipticalTubeNo
std::vector< std::vector
< G4double > > EllipticalTube_X
std::vector< std::vector
< G4double > > EllipticalTube_Y
std::vector< std::vector
< G4double > > EllipticalTube_Z
std::vector< G4String > fEllipticalTube_X
std::vector< G4String > fEllipticalTube_Y
std::vector< G4String > fEllipticalTube_Z
std::vector< G4int > EllipticalTube_GenIndex
G4int TubsNo
std::vector< std::vector
< G4double > > Tubs_RMax
std::vector< std::vector
< G4double > > Tubs_RMin
std::vector< std::vector
< G4double > > Tubs_Length
std::vector< std::vector
< G4double > > Tubs_StartAng
std::vector< std::vector
< G4double > > Tubs_SpanAng
std::vector< G4String > fTubs_RMax
std::vector< G4String > fTubs_RMin
std::vector< G4String > fTubs_Length
std::vector< G4String > fTubs_StartAng
std::vector< G4String > fTubs_SpanAng
std::vector< G4int > Tubs_GenIndex
G4int TorusNo
std::vector< G4String > fTorus_RMax
std::vector< G4String > fTorus_RMin
std::vector< G4String > fTorus_Rtor
std::vector< G4String > fTorus_StartAng
std::vector< G4String > fTorus_SpanAng
std::vector< std::vector
< G4double > > Torus_RMax
std::vector< std::vector
< G4double > > Torus_RMin
std::vector< std::vector
< G4double > > Torus_Rtor
std::vector< std::vector
< G4double > > Torus_StartAng
std::vector< std::vector
< G4double > > Torus_SpanAng
std::vector< G4int > Torus_GenIndex
G4int SphereNo
std::vector< G4String > fSphere_RMax
std::vector< G4String > fSphere_RMin
std::vector< G4String > fSphere_StartPhi
std::vector< G4String > fSphere_SpanPhi
std::vector< G4String > fSphere_StartTheta
std::vector< G4String > fSphere_SpanTheta
std::vector< std::vector
< G4double > > Sphere_RMax
std::vector< std::vector
< G4double > > Sphere_RMin
std::vector< std::vector
< G4double > > Sphere_StartPhi
std::vector< std::vector
< G4double > > Sphere_SpanPhi
std::vector< std::vector
< G4double > > Sphere_StartTheta
std::vector< std::vector
< G4double > > Sphere_SpanTheta
std::vector< G4int > Sphere_GenIndex
G4int HypeNo
std::vector< G4String > fHype_innerRadius
std::vector< G4String > fHype_outerRadius
std::vector< G4String > fHype_innerStereo
std::vector< G4String > fHype_outerStereo
std::vector< G4String > fHype_Length
std::vector< std::vector
< G4double > > Hype_innerRadius
std::vector< std::vector
< G4double > > Hype_outerRadius
std::vector< std::vector
< G4double > > Hype_innerStereo
std::vector< std::vector
< G4double > > Hype_outerStereo
std::vector< std::vector
< G4double > > Hype_Length
std::vector< G4int > Hype_GenIndex
G4int TwistedTubsNo
std::vector< G4String > fTwistedTubs_twistedangle
std::vector< G4String > fTwistedTubs_endinnerrad
std::vector< G4String > fTwistedTubs_endouterrad
std::vector< G4String > fTwistedTubs_Length
std::vector< G4String > fTwistedTubs_dphi
std::vector< std::vector
< G4double > > TwistedTubs_twistedangle
std::vector< std::vector
< G4double > > TwistedTubs_endinnerrad
std::vector< std::vector
< G4double > > TwistedTubs_endouterrad
std::vector< std::vector
< G4double > > TwistedTubs_Length
std::vector< std::vector
< G4double > > TwistedTubs_dphi
std::vector< G4int > TwistedTubs_GenIndex
G4int ConsNo
std::vector< G4String > fCons_RMax1
std::vector< G4String > fCons_RMin1
std::vector< G4String > fCons_RMax2
std::vector< G4String > fCons_RMin2
std::vector< G4String > fCons_Length
std::vector< G4String > fCons_StartAng
std::vector< G4String > fCons_SpanAng
std::vector< std::vector
< G4double > > Cons_RMax1
std::vector< std::vector
< G4double > > Cons_RMin1
std::vector< std::vector
< G4double > > Cons_RMax2
std::vector< std::vector
< G4double > > Cons_RMin2
std::vector< std::vector
< G4double > > Cons_Length
std::vector< std::vector
< G4double > > Cons_StartAng
std::vector< std::vector
< G4double > > Cons_SpanAng
std::vector< G4int > Cons_GenIndex
G4int PolyconeNo
std::vector< G4int > Polycone_numZ
std::vector< std::vector
< G4String > > fPolycone_RMax
std::vector< std::vector
< G4String > > fPolycone_RMin
std::vector< std::vector
< G4String > > fPolycone_Z
std::vector< std::vector
< std::vector< G4double > > > Polycone_RMax
std::vector< std::vector
< std::vector< G4double > > > Polycone_RMin
std::vector< std::vector
< std::vector< G4double > > > Polycone_Z
std::vector< G4String > fPolycone_StartAng
std::vector< G4String > fPolycone_SpanAng
std::vector< std::vector
< G4double > > Polycone_StartAng
std::vector< std::vector
< G4double > > Polycone_SpanAng
std::vector< G4int > Polycone_GenIndex
G4int waited_Polycone_iVol
G4int achieved_componets_Polycone
G4int ExtrudedSolidNo
std::vector< G4int > ExtrudedSolid_numZ
std::vector< G4int > ExtrudedSolid_numP
std::vector< std::vector
< G4String > > fExtrudedSolid_X
std::vector< std::vector
< G4String > > fExtrudedSolid_Y
std::vector< std::vector
< G4String > > fExtrudedSolid_Z
std::vector< std::vector
< G4String > > fExtrudedSolid_X0
std::vector< std::vector
< G4String > > fExtrudedSolid_Y0
std::vector< std::vector
< G4String > > fExtrudedSolid_Scale
std::vector< std::vector
< std::vector< G4double > > > ExtrudedSolid_X
std::vector< std::vector
< std::vector< G4double > > > ExtrudedSolid_Y
std::vector< std::vector
< std::vector< G4double > > > ExtrudedSolid_Z
std::vector< std::vector
< std::vector< G4double > > > ExtrudedSolid_X0
std::vector< std::vector
< std::vector< G4double > > > ExtrudedSolid_Y0
std::vector< std::vector
< std::vector< G4double > > > ExtrudedSolid_Scale
std::vector< G4int > ExtrudedSolid_GenIndex
G4int waited_ExtrudedSolid_iVol
G4int achieved_P_ExtrudedSolid
G4int achieved_Z_ExtrudedSolid
G4int BooleanSolidNo
std::vector< G4String > BooleanSolid_type
std::vector< G4String > BooleanSolid_sol1
std::vector< G4String > BooleanSolid_sol2
std::vector< G4int > BooleanSolid_GenIndex
std::vector< std::vector
< G4double > > BooleanSolid_Ephi
std::vector< std::vector
< G4double > > BooleanSolid_Etheta
std::vector< std::vector
< G4double > > BooleanSolid_Epsi
std::vector< std::vector
< G4ThreeVector > > BooleanSolid_Pos
std::vector< G4String > fBooleanSolid_Ephi
std::vector< G4String > fBooleanSolid_Etheta
std::vector< G4String > fBooleanSolid_Epsi
std::vector< G4String > fBooleanSolid_PosX
std::vector< G4String > fBooleanSolid_PosY
std::vector< G4String > fBooleanSolid_PosZ
std::vector< G4String > fBooleanSolid_PosTheta
std::vector< G4String > fBooleanSolid_PosPhi
std::vector< G4String > fBooleanSolid_PosR
std::vector< G4String > BooleanSolid_PosType
std::vector< bool > vVis
std::vector< G4double > vR
std::vector< G4double > vG
std::vector< G4double > vB
std::vector< G4double > vT
bool notReSetVis
Detailed Description
Definition at line 24 of file SimpleGeometryParameter.hh.
Constructor & Destructor Documentation
SimpleGeometryParameter::SimpleGeometryParameter (G4String name, G4String opt = "")
Definition at line 23 of file SimpleGeometryParameter.cc.
References MyVGeometryParameter::set_GeometryParameterMessenger().
        : MyVGeometryParameter(name, "S") // Use a not-empty opt to stop inherited class from creating new GeometryParameterMessenger
{
        if ( opt == "" ){
                SimpleGeometryParameterMessenger *pointer = new SimpleGeometryParameterMessenger(this, name);
                //              std::cout<<"======>In SimpleGeometryParameter, new SimpleGeometryParameterMessenger at ("<<(void*)pointer<<")!"<<std::endl;
                set_GeometryParameterMessenger(pointer);
        }
}
SimpleGeometryParameter::~SimpleGeometryParameter (void) [virtual]
Definition at line 33 of file SimpleGeometryParameter.cc.
{
        printf("~SimpleGeometryParameter");
}
Member Function Documentation
void SimpleGeometryParameter::Calculate () [virtual]
Reimplemented from MyVGeometryParameter.
Definition at line 68 of file SimpleGeometryParameter.cc.
References BooleanSolid_Ephi, BooleanSolid_Epsi, BooleanSolid_Etheta, BooleanSolid_Pos, BooleanSolid_PosType, Box_X, Box_Y, Box_Z, MyConfigure::CalFormula(), Cons_Length, Cons_RMax1, Cons_RMax2, Cons_RMin1, Cons_RMin2, Cons_SpanAng, Cons_StartAng, EllipticalTube_X, EllipticalTube_Y, EllipticalTube_Z, Ephi, Epsi, Etheta, ExtrudedSolid_numP, ExtrudedSolid_numZ, ExtrudedSolid_Scale, ExtrudedSolid_X, ExtrudedSolid_X0, ExtrudedSolid_Y, ExtrudedSolid_Y0, ExtrudedSolid_Z, fBooleanSolid_Ephi, fBooleanSolid_Epsi, fBooleanSolid_Etheta, fBooleanSolid_PosPhi, fBooleanSolid_PosR, fBooleanSolid_PosTheta, fBooleanSolid_PosX, fBooleanSolid_PosY, fBooleanSolid_PosZ, fBox_X, fBox_Y, fBox_Z, fCons_Length, fCons_RMax1, fCons_RMax2, fCons_RMin1, fCons_RMin2, fCons_SpanAng, fCons_StartAng, fEllipticalTube_X, fEllipticalTube_Y, fEllipticalTube_Z, fEphi, fEpsi, fEtheta, fExtrudedSolid_Scale, fExtrudedSolid_X, fExtrudedSolid_X0, fExtrudedSolid_Y, fExtrudedSolid_Y0, fExtrudedSolid_Z, fHype_innerRadius, fHype_innerStereo, fHype_Length, fHype_outerRadius, fHype_outerStereo, fPolycone_RMax, fPolycone_RMin, fPolycone_SpanAng, fPolycone_StartAng, fPolycone_Z, fPosPhi, fPosR, fPosTheta, fPosX, fPosY, fPosZ, fSphere_RMax, fSphere_RMin, fSphere_SpanPhi, fSphere_SpanTheta, fSphere_StartPhi, fSphere_StartTheta, fTorus_RMax, fTorus_RMin, fTorus_Rtor, fTorus_SpanAng, fTorus_StartAng, fTubs_Length, fTubs_RMax, fTubs_RMin, fTubs_SpanAng, fTubs_StartAng, fTwistedTubs_dphi, fTwistedTubs_endinnerrad, fTwistedTubs_endouterrad, fTwistedTubs_Length, fTwistedTubs_twistedangle, Hype_innerRadius, Hype_innerStereo, Hype_Length, Hype_outerRadius, Hype_outerStereo, Polycone_numZ, Polycone_RMax, Polycone_RMin, Polycone_SpanAng, Polycone_StartAng, Polycone_Z, Pos, PosType, RepNo, SolidBoolean, SolidIndex, SolidType, Sphere_RMax, Sphere_RMin, Sphere_SpanPhi, Sphere_SpanTheta, Sphere_StartPhi, Sphere_StartTheta, Torus_RMax, Torus_RMin, Torus_Rtor, Torus_SpanAng, Torus_StartAng, Tubs_Length, Tubs_RMax, Tubs_RMin, Tubs_SpanAng, Tubs_StartAng, TwistedTubs_dphi, TwistedTubs_endinnerrad, TwistedTubs_endouterrad, TwistedTubs_Length, TwistedTubs_twistedangle, and VolNo.
Referenced by InitFromFile().
{
//      std::cout<<"In SimpleGeometryParameter::Calculate"<<std::endl; // to be deleted
        MyVGeometryParameter::Calculate();
        for ( int VolId = 0; VolId < VolNo; VolId++ ){
                std::vector<G4ThreeVector> tPos; tPos.clear();
                std::vector<G4double> tEphi; tEphi.clear();
                std::vector<G4double> tEtheta; tEtheta.clear();
                std::vector<G4double> tEpsi; tEpsi.clear();
                if (!SolidBoolean[VolId]){
                        for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                tEphi.push_back(CalFormula(fEphi[VolId],RepId)*deg);
                                tEtheta.push_back(CalFormula(fEtheta[VolId],RepId)*deg);
                                tEpsi.push_back(CalFormula(fEpsi[VolId],RepId)*deg);
                                G4ThreeVector vec3temp(1,1,1);
                                if (PosType[VolId]=="Cartesian"){
                                        vec3temp.setX(CalFormula(fPosX[VolId],RepId)*mm);
                                        vec3temp.setY(CalFormula(fPosY[VolId],RepId)*mm);
                                        vec3temp.setZ(CalFormula(fPosZ[VolId],RepId)*mm);
                                }
                                else if (PosType[VolId]=="Spherical"){
                                        vec3temp.setMag(CalFormula(fPosR[VolId],RepId)*mm);
                                        vec3temp.setTheta(CalFormula(fPosTheta[VolId],RepId)*deg);
                                        vec3temp.setPhi(CalFormula(fPosPhi[VolId],RepId)*deg);
                                }
                                else if (PosType[VolId]=="Polar"){
                                        vec3temp.setRho(CalFormula(fPosR[VolId],RepId)*mm);
                                        vec3temp.setZ(CalFormula(fPosZ[VolId],RepId)*mm);
                                        vec3temp.setPhi(CalFormula(fPosPhi[VolId],RepId)*deg);
                                }
                                tPos.push_back(vec3temp);
                        }
                }
                Pos.push_back(tPos);
                Ephi.push_back(tEphi);
                Etheta.push_back(tEtheta);
                Epsi.push_back(tEpsi);
                int SolId = SolidIndex[VolId];
                if ( SolidType[VolId] == "BooleanSolid" ){
                        std::vector<G4double> tBooleanSolid_Ephi;
                        std::vector<G4double> tBooleanSolid_Etheta;
                        std::vector<G4double> tBooleanSolid_Epsi;
                        std::vector<G4ThreeVector> tBooleanSolid_Pos;
                        for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                tBooleanSolid_Ephi.push_back(CalFormula(fBooleanSolid_Ephi[SolId],RepId)*deg);
                                tBooleanSolid_Etheta.push_back(CalFormula(fBooleanSolid_Etheta[SolId],RepId)*deg);
                                tBooleanSolid_Epsi.push_back(CalFormula(fBooleanSolid_Epsi[SolId],RepId)*deg);
                                G4ThreeVector vec3temp(1,1,1);
                                if (BooleanSolid_PosType[SolId]=="Cartesian"){
                                        vec3temp.setX(CalFormula(fBooleanSolid_PosX[SolId],RepId)*mm);
                                        vec3temp.setY(CalFormula(fBooleanSolid_PosY[SolId],RepId)*mm);
                                        vec3temp.setZ(CalFormula(fBooleanSolid_PosZ[SolId],RepId)*mm);
                                }
                                else if (BooleanSolid_PosType[SolId]=="Spherical"){
                                        vec3temp.setMag(CalFormula(fBooleanSolid_PosR[SolId],RepId)*mm);
                                        vec3temp.setTheta(CalFormula(fBooleanSolid_PosTheta[SolId],RepId)*deg);
                                        vec3temp.setPhi(CalFormula(fBooleanSolid_PosPhi[SolId],RepId)*deg);
                                }
                                else if (BooleanSolid_PosType[SolId]=="Polar"){
                                        vec3temp.setRho(CalFormula(fBooleanSolid_PosR[SolId],RepId)*mm);
                                        vec3temp.setZ(CalFormula(fBooleanSolid_PosZ[SolId],RepId)*mm);
                                        vec3temp.setPhi(CalFormula(fBooleanSolid_PosPhi[SolId],RepId)*deg);
                                }
                                tBooleanSolid_Pos.push_back(vec3temp);
                        }
                        BooleanSolid_Ephi.push_back(tBooleanSolid_Ephi);
                        BooleanSolid_Etheta.push_back(tBooleanSolid_Etheta);
                        BooleanSolid_Epsi.push_back(tBooleanSolid_Epsi);
                        BooleanSolid_Pos.push_back(tBooleanSolid_Pos);
                }
                else if ( SolidType[VolId] == "Box" ){
                        std::vector<G4double> tBox_X; tBox_X.clear();
                        std::vector<G4double> tBox_Y; tBox_Y.clear();
                        std::vector<G4double> tBox_Z; tBox_Z.clear();
                        for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                tBox_X.push_back(CalFormula(fBox_X[SolId],RepId)*mm);
                                tBox_Y.push_back(CalFormula(fBox_Y[SolId],RepId)*mm);
                                tBox_Z.push_back(CalFormula(fBox_Z[SolId],RepId)*mm);
                        }
                        Box_X.push_back(tBox_X);
                        Box_Y.push_back(tBox_Y);
                        Box_Z.push_back(tBox_Z);
                }
                else if ( SolidType[VolId] == "EllipticalTube" ){
                        std::vector<G4double> tEllipticalTube_X; tEllipticalTube_X.clear();
                        std::vector<G4double> tEllipticalTube_Y; tEllipticalTube_Y.clear();
                        std::vector<G4double> tEllipticalTube_Z; tEllipticalTube_Z.clear();
                        for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                tEllipticalTube_X.push_back(CalFormula(fEllipticalTube_X[SolId],RepId)*mm);
                                tEllipticalTube_Y.push_back(CalFormula(fEllipticalTube_Y[SolId],RepId)*mm);
                                tEllipticalTube_Z.push_back(CalFormula(fEllipticalTube_Z[SolId],RepId)*mm);
                        }
                        EllipticalTube_X.push_back(tEllipticalTube_X);
                        EllipticalTube_Y.push_back(tEllipticalTube_Y);
                        EllipticalTube_Z.push_back(tEllipticalTube_Z);
                }
                else if ( SolidType[VolId] == "Tubs" ){
                        std::vector<G4double> tTubs_RMax;
                        std::vector<G4double> tTubs_RMin;
                        std::vector<G4double> tTubs_Length;
                        std::vector<G4double> tTubs_StartAng;
                        std::vector<G4double> tTubs_SpanAng;
                        for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                tTubs_RMax.push_back(CalFormula(fTubs_RMax[SolId],RepId)*mm);
                                tTubs_RMin.push_back(CalFormula(fTubs_RMin[SolId],RepId)*mm);
                                tTubs_Length.push_back(CalFormula(fTubs_Length[SolId],RepId)*mm);
                                tTubs_StartAng.push_back(CalFormula(fTubs_StartAng[SolId],RepId)*deg);
                                tTubs_SpanAng.push_back(CalFormula(fTubs_SpanAng[SolId],RepId)*deg);
                        }
                        Tubs_RMax.push_back(tTubs_RMax);
                        Tubs_RMin.push_back(tTubs_RMin);
                        Tubs_Length.push_back(tTubs_Length);
                        Tubs_StartAng.push_back(tTubs_StartAng);
                        Tubs_SpanAng.push_back(tTubs_SpanAng);
                }
                else if( SolidType[VolId] == "Torus" ){
                        std::vector<G4double> tTorus_RMax;
                        std::vector<G4double> tTorus_RMin;
                        std::vector<G4double> tTorus_Rtor;
                        std::vector<G4double> tTorus_StartAng;
                        std::vector<G4double> tTorus_SpanAng;
                        for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                tTorus_RMax.push_back(CalFormula(fTorus_RMax[SolId],RepId)*mm);
                                tTorus_RMin.push_back(CalFormula(fTorus_RMin[SolId],RepId)*mm);
                                tTorus_Rtor.push_back(CalFormula(fTorus_Rtor[SolId],RepId)*mm);
                                tTorus_StartAng.push_back(CalFormula(fTorus_StartAng[SolId],RepId)*deg);
                                tTorus_SpanAng.push_back(CalFormula(fTorus_SpanAng[SolId],RepId)*deg);
                        }
                        Torus_RMax.push_back(tTorus_RMax);
                        Torus_RMin.push_back(tTorus_RMin);
                        Torus_Rtor.push_back(tTorus_Rtor);
                        Torus_StartAng.push_back(tTorus_StartAng);
                        Torus_SpanAng.push_back(tTorus_SpanAng);
                }
                else if( SolidType[VolId] == "Sphere" ){
                        std::vector<G4double> tSphere_RMax;
                        std::vector<G4double> tSphere_RMin;
                        std::vector<G4double> tSphere_StartPhi;
                        std::vector<G4double> tSphere_SpanPhi;
                        std::vector<G4double> tSphere_StartTheta;
                        std::vector<G4double> tSphere_SpanTheta;
                        for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                tSphere_RMax.push_back(CalFormula(fSphere_RMax[SolId],RepId)*mm);
                                tSphere_RMin.push_back(CalFormula(fSphere_RMin[SolId],RepId)*mm);
                                tSphere_StartPhi.push_back(CalFormula(fSphere_StartPhi[SolId],RepId)*deg);
                                tSphere_SpanPhi.push_back(CalFormula(fSphere_SpanPhi[SolId],RepId)*deg);
                                tSphere_StartTheta.push_back(CalFormula(fSphere_StartTheta[SolId],RepId)*deg);
                                tSphere_SpanTheta.push_back(CalFormula(fSphere_SpanTheta[SolId],RepId)*deg);
                        }
                        Sphere_RMax.push_back(tSphere_RMax);
                        Sphere_RMin.push_back(tSphere_RMin);
                        Sphere_StartPhi.push_back(tSphere_StartPhi);
                        Sphere_SpanPhi.push_back(tSphere_SpanPhi);
                        Sphere_StartTheta.push_back(tSphere_StartTheta);
                        Sphere_SpanTheta.push_back(tSphere_SpanTheta);
                }
                else if( SolidType[VolId] == "Hype" ){
                        std::vector<G4double> tHype_innerRadius;
                        std::vector<G4double> tHype_outerRadius;
                        std::vector<G4double> tHype_innerStereo;
                        std::vector<G4double> tHype_outerStereo;
                        std::vector<G4double> tHype_Length;
                        for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                tHype_innerRadius.push_back(CalFormula(fHype_innerRadius[SolId],RepId)*mm);
                                tHype_outerRadius.push_back(CalFormula(fHype_outerRadius[SolId],RepId)*mm);
                                tHype_innerStereo.push_back(CalFormula(fHype_innerStereo[SolId],RepId)*deg);
                                tHype_outerStereo.push_back(CalFormula(fHype_outerStereo[SolId],RepId)*deg);
                                tHype_Length.push_back(CalFormula(fHype_Length[SolId],RepId)*mm);
                        }
                        Hype_innerRadius.push_back(tHype_innerRadius);
                        Hype_outerRadius.push_back(tHype_outerRadius);
                        Hype_innerStereo.push_back(tHype_innerStereo);
                        Hype_outerStereo.push_back(tHype_outerStereo);
                        Hype_Length.push_back(tHype_Length);
                }
                else if( SolidType[VolId] == "TwistedTubs" ){
                        std::vector<G4double> tTwistedTubs_twistedangle;
                        std::vector<G4double> tTwistedTubs_endinnerrad;
                        std::vector<G4double> tTwistedTubs_endouterrad;
                        std::vector<G4double> tTwistedTubs_Length;
                        std::vector<G4double> tTwistedTubs_dphi;
                        for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                tTwistedTubs_twistedangle.push_back(CalFormula(fTwistedTubs_twistedangle[SolId],RepId)*deg);
                                tTwistedTubs_endinnerrad.push_back(CalFormula(fTwistedTubs_endinnerrad[SolId],RepId)*mm);
                                tTwistedTubs_endouterrad.push_back(CalFormula(fTwistedTubs_endouterrad[SolId],RepId)*mm);
                                tTwistedTubs_Length.push_back(CalFormula(fTwistedTubs_Length[SolId],RepId)*mm);
                                tTwistedTubs_dphi.push_back(CalFormula(fTwistedTubs_dphi[SolId],RepId)*deg);
                        }
                        TwistedTubs_twistedangle.push_back(tTwistedTubs_twistedangle);
                        TwistedTubs_endinnerrad.push_back(tTwistedTubs_endinnerrad);
                        TwistedTubs_endouterrad.push_back(tTwistedTubs_endouterrad);
                        TwistedTubs_Length.push_back(tTwistedTubs_Length);
                        TwistedTubs_dphi.push_back(tTwistedTubs_dphi);
                }
                else if( SolidType[VolId] == "Cons" ){
                        std::vector<G4double> tCons_RMax1;
                        std::vector<G4double> tCons_RMin1;
                        std::vector<G4double> tCons_RMax2;
                        std::vector<G4double> tCons_RMin2;
                        std::vector<G4double> tCons_Length;
                        std::vector<G4double> tCons_StartAng;
                        std::vector<G4double> tCons_SpanAng;
                        for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                tCons_RMax1.push_back(CalFormula(fCons_RMax1[SolId],RepId)*mm);
                                tCons_RMin1.push_back(CalFormula(fCons_RMin1[SolId],RepId)*mm);
                                tCons_RMax2.push_back(CalFormula(fCons_RMax2[SolId],RepId)*mm);
                                tCons_RMin2.push_back(CalFormula(fCons_RMin2[SolId],RepId)*mm);
                                tCons_Length.push_back(CalFormula(fCons_Length[SolId],RepId)*mm);
                                tCons_StartAng.push_back(CalFormula(fCons_StartAng[SolId],RepId)*deg);
                                tCons_SpanAng.push_back(CalFormula(fCons_SpanAng[SolId],RepId)*deg);
                        }
                        Cons_RMax1.push_back(tCons_RMax1);
                        Cons_RMin1.push_back(tCons_RMin1);
                        Cons_RMax2.push_back(tCons_RMax2);
                        Cons_RMin2.push_back(tCons_RMin2);
                        Cons_Length.push_back(tCons_Length);
                        Cons_StartAng.push_back(tCons_StartAng);
                        Cons_SpanAng.push_back(tCons_SpanAng);
                }
                else if( SolidType[VolId] == "Polycone" ){
                        std::vector<G4double> tPolycone_StartAng;
                        std::vector<G4double> tPolycone_SpanAng;
                        for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                tPolycone_StartAng.push_back(CalFormula(fPolycone_StartAng[SolId],RepId)*deg);
                                tPolycone_SpanAng.push_back(CalFormula(fPolycone_SpanAng[SolId],RepId)*deg);
                        }
                        Polycone_StartAng.push_back(tPolycone_StartAng);
                        Polycone_SpanAng.push_back(tPolycone_SpanAng);
                        std::vector<std::vector<G4double> > iPolycone_RMax;
                        std::vector<std::vector<G4double> > iPolycone_RMin;
                        std::vector<std::vector<G4double> > iPolycone_Z;
                        for ( int ConeId = 0; ConeId < Polycone_numZ[SolId]; ConeId++ ){
                                std::vector<G4double> tPolycone_RMax;
                                std::vector<G4double> tPolycone_RMin;
                                std::vector<G4double> tPolycone_Z;
                                for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                        tPolycone_RMax.push_back(CalFormula(fPolycone_RMax[SolId][ConeId],RepId)*mm);
                                        tPolycone_RMin.push_back(CalFormula(fPolycone_RMin[SolId][ConeId],RepId)*mm);
                                        tPolycone_Z.push_back(CalFormula(fPolycone_Z[SolId][ConeId],RepId)*mm);
                                }
                                iPolycone_RMax.push_back(tPolycone_RMax);
                                iPolycone_RMin.push_back(tPolycone_RMin);
                                iPolycone_Z.push_back(tPolycone_Z);
                        }
                        Polycone_RMax.push_back(iPolycone_RMax);
                        Polycone_RMin.push_back(iPolycone_RMin);
                        Polycone_Z.push_back(iPolycone_Z);
                }
                else if( SolidType[VolId] == "ExtrudedSolid" ){
                        std::vector<std::vector<G4double> > iExtrudedSolid_X;
                        std::vector<std::vector<G4double> > iExtrudedSolid_Y;
                        std::vector<std::vector<G4double> > iExtrudedSolid_Z;
                        std::vector<std::vector<G4double> > iExtrudedSolid_X0;
                        std::vector<std::vector<G4double> > iExtrudedSolid_Y0;
                        std::vector<std::vector<G4double> > iExtrudedSolid_Scale;
                        for ( int ConeId = 0; ConeId < ExtrudedSolid_numZ[SolId]; ConeId++ ){
                                std::vector<G4double> tExtrudedSolid_Z;
                                std::vector<G4double> tExtrudedSolid_X0;
                                std::vector<G4double> tExtrudedSolid_Y0;
                                std::vector<G4double> tExtrudedSolid_Scale;
                                for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                        tExtrudedSolid_Z.push_back(CalFormula(fExtrudedSolid_Z[SolId][ConeId],RepId)*mm);
                                        tExtrudedSolid_X0.push_back(CalFormula(fExtrudedSolid_X0[SolId][ConeId],RepId)*mm);
                                        tExtrudedSolid_Y0.push_back(CalFormula(fExtrudedSolid_Y0[SolId][ConeId],RepId)*mm);
                                        tExtrudedSolid_Scale.push_back(CalFormula(fExtrudedSolid_Scale[SolId][ConeId],RepId));
                                }
                                iExtrudedSolid_Z.push_back(tExtrudedSolid_Z);
                                iExtrudedSolid_X0.push_back(tExtrudedSolid_X0);
                                iExtrudedSolid_Y0.push_back(tExtrudedSolid_Y0);
                                iExtrudedSolid_Scale.push_back(tExtrudedSolid_Scale);
                        }
                        for ( int ConeId = 0; ConeId < ExtrudedSolid_numP[SolId]; ConeId++ ){
                                std::vector<G4double> tExtrudedSolid_X;
                                std::vector<G4double> tExtrudedSolid_Y;
                                for ( int RepId = 0; RepId < RepNo[VolId]; RepId++ ){
                                        tExtrudedSolid_X.push_back(CalFormula(fExtrudedSolid_X[SolId][ConeId],RepId)*mm);
                                        tExtrudedSolid_Y.push_back(CalFormula(fExtrudedSolid_Y[SolId][ConeId],RepId)*mm);
                                }
                                iExtrudedSolid_X.push_back(tExtrudedSolid_X);
                                iExtrudedSolid_Y.push_back(tExtrudedSolid_Y);
                        }
                        ExtrudedSolid_X.push_back(iExtrudedSolid_X);
                        ExtrudedSolid_Y.push_back(iExtrudedSolid_Y);
                        ExtrudedSolid_Z.push_back(iExtrudedSolid_Z);
                        ExtrudedSolid_X0.push_back(iExtrudedSolid_X0);
                        ExtrudedSolid_Y0.push_back(iExtrudedSolid_Y0);
                        ExtrudedSolid_Scale.push_back(iExtrudedSolid_Scale);
                }
        }
//      std::cout<<"End of SimpleGeometryParameter::Calculate"<<std::endl; // to be deleted
}
double MyConfigure::CalFormula (G4String formula, int iRep = 0) [inherited]
Definition at line 23 of file MyConfigure.cc.
Referenced by Calculate(), and PrimaryGeneratorAction::ReadCard().
{
//      std::cout<<"TO Calculate for: \""<<formula<<"\" "<<iRep<<std::endl; // to be deleted
//      formula = ReplaceMacro(formula);
        TF1 *f1 = new TF1("f1", formula);
        double value = f1->Eval(iRep);
//      std::cout<<"\t=>"<<value<<std::endl;
        delete f1;
        return value;
}
bool SimpleGeometryParameter::check_BooleanSolidId (int BooleanSolidId) [inline, private]
Definition at line 549 of file SimpleGeometryParameter.hh.
References BooleanSolidNo.
Referenced by get_BooleanSolid_Ephi(), get_BooleanSolid_Epsi(), get_BooleanSolid_Etheta(), get_BooleanSolid_PosX(), get_BooleanSolid_PosY(), get_BooleanSolid_PosZ(), get_BooleanSolid_sol1(), get_BooleanSolid_sol2(), get_BooleanSolid_type(), get_index(), set_BooleanSolid_Ephi(), set_BooleanSolid_Epsi(), set_BooleanSolid_Etheta(), set_BooleanSolid_PosX(), set_BooleanSolid_PosY(), set_BooleanSolid_PosZ(), set_BooleanSolid_sol1(), set_BooleanSolid_sol2(), and set_BooleanSolid_type().
{
                        if ( BooleanSolidId < BooleanSolidNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, BooleanSolidId is out of range! BooleanSolidId = "<<BooleanSolidId<<", BooleanSolidNo = "<<BooleanSolidNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::check_BooleanSolidNo (int No) [inline, private]
Definition at line 556 of file SimpleGeometryParameter.hh.
References BooleanSolidNo.
{
                        if( No != BooleanSolidNo ){
                                std::cout<<"In SimpleGeometryParameter::InitFromFile(), insufficient BooleanSolid info! BooleanSolidNo = "<<BooleanSolidNo<<", while only "<<No<<" BooleanSolid were found."<<std::endl;
                                return false;
                        }
                        else return true;
                }
bool SimpleGeometryParameter::check_BoxId (int BoxId) [inline, private]
Definition at line 416 of file SimpleGeometryParameter.hh.
References BoxNo.
Referenced by get_Box_X(), get_Box_Y(), get_Box_Z(), and get_index().
{
                        if ( BoxId < BoxNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, BoxId is out of range! BoxId = "<<BoxId<<", BoxNo = "<<BoxNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::check_BoxNo (int No) [inline, private]
Definition at line 430 of file SimpleGeometryParameter.hh.
References BoxNo.
{
                        if( No != BoxNo ){
                                std::cout<<"In SimpleGeometryParameter::InitFromFile(), insufficient Box info! BoxNo = "<<BoxNo<<", while only "<<No<<" Box were found."<<std::endl;
                                return false;
                        }
                        else return true;
                }
bool SimpleGeometryParameter::check_ConsId (int ConsId) [inline, private]
Definition at line 507 of file SimpleGeometryParameter.hh.
References ConsNo.
Referenced by get_Cons_Length(), get_Cons_RMax1(), get_Cons_RMax2(), get_Cons_RMin1(), get_Cons_RMin2(), get_Cons_SpanAng(), get_Cons_StartAng(), and get_index().
{
                        if ( ConsId < ConsNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, ConsId is out of range! ConsId = "<<ConsId<<", ConsNo = "<<ConsNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::check_ConsNo (int No) [inline, private]
Definition at line 514 of file SimpleGeometryParameter.hh.
References ConsNo.
{
                        if( No != ConsNo ){
                                std::cout<<"In SimpleGeometryParameter::InitFromFile(), insufficient Cons info! ConsNo = "<<ConsNo<<", while only "<<No<<" Cons were found."<<std::endl;
                                return false;
                        }
                        else return true;
                }
bool SimpleGeometryParameter::check_EllipticalTubeId (int EllipticalTubeId) [inline, private]
Definition at line 423 of file SimpleGeometryParameter.hh.
References EllipticalTubeNo.
Referenced by get_EllipticalTube_X(), get_EllipticalTube_Y(), get_EllipticalTube_Z(), and get_index().
{
                        if ( EllipticalTubeId < EllipticalTubeNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, EllipticalTubeId is out of range! EllipticalTubeId = "<<EllipticalTubeId<<", EllipticalTubeNo = "<<EllipticalTubeNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::check_ExtrudedSolidId (int ExtrudedSolidId) [inline, private]
Definition at line 535 of file SimpleGeometryParameter.hh.
References ExtrudedSolidNo.
Referenced by get_ExtrudedSolid_numP(), get_ExtrudedSolid_numZ(), get_ExtrudedSolid_Scale(), get_ExtrudedSolid_X(), get_ExtrudedSolid_X0(), get_ExtrudedSolid_Y(), get_ExtrudedSolid_Y0(), get_ExtrudedSolid_Z(), get_index(), set_ExtrudedSolid_numP(), set_ExtrudedSolid_numZ(), set_ExtrudedSolid_Scale(), set_ExtrudedSolid_X(), set_ExtrudedSolid_X0(), set_ExtrudedSolid_Y(), set_ExtrudedSolid_Y0(), and set_ExtrudedSolid_Z().
{
                        if ( ExtrudedSolidId < ExtrudedSolidNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, ExtrudedSolidId is out of range! ExtrudedSolidId = "<<ExtrudedSolidId<<", ExtrudedSolidNo = "<<ExtrudedSolidNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::check_ExtrudedSolidNo (int No) [inline, private]
Definition at line 542 of file SimpleGeometryParameter.hh.
References ExtrudedSolidNo.
{
                        if( No != ExtrudedSolidNo ){
                                std::cout<<"In SimpleGeometryParameter::InitFromFile(), insufficient ExtrudedSolid info! ExtrudedSolidNo = "<<ExtrudedSolidNo<<", while only "<<No<<" ExtrudedSolid were found."<<std::endl;
                                return false;
                        }
                        else return true;
                }
bool SimpleGeometryParameter::check_HypeId (int HypeId) [inline, private]
Definition at line 479 of file SimpleGeometryParameter.hh.
References HypeNo.
Referenced by get_Hype_innerRadius(), get_Hype_innerStereo(), get_Hype_Length(), get_Hype_outerRadius(), get_Hype_outerStereo(), and get_index().
{
                        if ( HypeId < HypeNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, HypeId is out of range! HypeId = "<<HypeId<<", HypeNo = "<<HypeNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::check_HypeNo (int No) [inline, private]
Definition at line 486 of file SimpleGeometryParameter.hh.
References HypeNo.
{
                        if( No != HypeNo ){
                                std::cout<<"In SimpleGeometryParameter::InitFromFile(), insufficient Hype info! HypeNo = "<<HypeNo<<", while only "<<No<<" Hype were found."<<std::endl;
                                return false;
                        }
                        else return true;
                }
bool SimpleGeometryParameter::check_PolyconeId (int PolyconeId) [inline, private]
Definition at line 521 of file SimpleGeometryParameter.hh.
References PolyconeNo.
Referenced by get_index(), get_Polycone_numZ(), get_Polycone_RMax(), get_Polycone_RMin(), get_Polycone_SpanAng(), get_Polycone_StartAng(), get_Polycone_Z(), set_Polycone_numZ(), set_Polycone_RMax(), set_Polycone_RMin(), set_Polycone_SpanAng(), set_Polycone_StartAng(), and set_Polycone_Z().
{
                        if ( PolyconeId < PolyconeNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, PolyconeId is out of range! PolyconeId = "<<PolyconeId<<", PolyconeNo = "<<PolyconeNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::check_PolyconeNo (int No) [inline, private]
Definition at line 528 of file SimpleGeometryParameter.hh.
References PolyconeNo.
{
                        if( No != PolyconeNo ){
                                std::cout<<"In SimpleGeometryParameter::InitFromFile(), insufficient Polycone info! PolyconeNo = "<<PolyconeNo<<", while only "<<No<<" Polycone were found."<<std::endl;
                                return false;
                        }
                        else return true;
                }
bool SimpleGeometryParameter::check_SphereId (int SphereId) [inline, private]
Definition at line 465 of file SimpleGeometryParameter.hh.
References SphereNo.
Referenced by get_index(), get_Sphere_RMax(), get_Sphere_RMin(), get_Sphere_SpanPhi(), get_Sphere_SpanTheta(), get_Sphere_StartPhi(), and get_Sphere_StartTheta().
{
                        if ( SphereId < SphereNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, SphereId is out of range! SphereId = "<<SphereId<<", SphereNo = "<<SphereNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::check_SphereNo (int No) [inline, private]
Definition at line 472 of file SimpleGeometryParameter.hh.
References SphereNo.
{
                        if( No != SphereNo ){
                                std::cout<<"In SimpleGeometryParameter::InitFromFile(), insufficient Sphere info! SphereNo = "<<SphereNo<<", while only "<<No<<" Sphere were found."<<std::endl;
                                return false;
                        }
                        else return true;
                }
bool SimpleGeometryParameter::check_TorusId (int TorusId) [inline, private]
Definition at line 451 of file SimpleGeometryParameter.hh.
References TorusNo.
Referenced by get_index(), get_Torus_RMax(), get_Torus_RMin(), get_Torus_Rtor(), get_Torus_SpanAng(), and get_Torus_StartAng().
{
                        if ( TorusId < TorusNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, TorusId is out of range! TorusId = "<<TorusId<<", TorusNo = "<<TorusNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::check_TorusNo (int No) [inline, private]
Definition at line 458 of file SimpleGeometryParameter.hh.
References TorusNo.
{
                        if( No != TorusNo ){
                                std::cout<<"In SimpleGeometryParameter::InitFromFile(), insufficient Torus info! TorusNo = "<<TorusNo<<", while only "<<No<<" Torus were found."<<std::endl;
                                return false;
                        }
                        else return true;
                }
bool SimpleGeometryParameter::check_TubsId (int TubsId) [inline, private]
Definition at line 437 of file SimpleGeometryParameter.hh.
References TubsNo.
Referenced by get_index(), get_Tubs_Length(), get_Tubs_RMax(), get_Tubs_RMin(), get_Tubs_SpanAng(), and get_Tubs_StartAng().
{
                        if ( TubsId < TubsNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, TubsId is out of range! TubsId = "<<TubsId<<", TubsNo = "<<TubsNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::check_TubsNo (int No) [inline, private]
Definition at line 444 of file SimpleGeometryParameter.hh.
References TubsNo.
{
                        if( No != TubsNo ){
                                std::cout<<"In SimpleGeometryParameter::InitFromFile(), insufficient Tubs info! TubsNo = "<<TubsNo<<", while only "<<No<<" Tubs were found."<<std::endl;
                                return false;
                        }
                        else return true;
                }
bool SimpleGeometryParameter::check_TwistedTubsId (int TwistedTubsId) [inline, private]
Definition at line 493 of file SimpleGeometryParameter.hh.
References TwistedTubsNo.
Referenced by get_index(), get_TwistedTubs_dphi(), get_TwistedTubs_endinnerrad(), get_TwistedTubs_endouterrad(), get_TwistedTubs_Length(), and get_TwistedTubs_twistedangle().
{
                        if ( TwistedTubsId < TwistedTubsNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, TwistedTubsId is out of range! TwistedTubsId = "<<TwistedTubsId<<", TwistedTubsNo = "<<TwistedTubsNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::check_TwistedTubsNo (int No) [inline, private]
Definition at line 500 of file SimpleGeometryParameter.hh.
References TwistedTubsNo.
{
                        if( No != TwistedTubsNo ){
                                std::cout<<"In SimpleGeometryParameter::InitFromFile(), insufficient TwistedTubs info! TwistedTubsNo = "<<TwistedTubsNo<<", while only "<<No<<" TwistedTubs were found."<<std::endl;
                                return false;
                        }
                        else return true;
                }
bool SimpleGeometryParameter::check_VolId (int VolId) [inline, private]
Definition at line 409 of file SimpleGeometryParameter.hh.
References VolNo.
Referenced by get_b(), get_Ephi(), get_Epsi(), get_Etheta(), get_g(), get_material(), get_MotherName(), get_name(), get_PosX(), get_PosY(), get_PosZ(), get_r(), get_RepNo(), get_SDName(), get_SolidBoolean(), get_SolidIndex(), get_SolidType(), get_SRepNo(), get_t(), and get_vis().
{
                        if ( VolId < VolNo ) return true;
                        else{
                                std::cout<<"In SimpleGeometryParameter, VolId is out of range! VolId = "<<VolId<<", VolNo = "<<VolNo<<std::endl;
                                return false;
                        }
                }
bool SimpleGeometryParameter::CheckInfo ()
Reimplemented from MyVGeometryParameter.
Definition at line 365 of file SimpleGeometryParameter.cc.
Referenced by InitFromFile().
{
        bool flag = false;// false means no problem
        flag = MyVGeometryParameter::CheckInfo();
        if (flag) return flag;// if something is wrong with its Parent Class, then return the status.
        //examine
        return flag;
}
void MyVGeometryParameter::DEBUG (G4String content, int level = 1) [inline, inherited]
Definition at line 54 of file MyVGeometryParameter.hh.
Referenced by get_index(), and InitFromFile().
{
                        if (level >= 1){
                                G4Exception("MyVGeometryParameter","Run0031",
                                                FatalException, content);
                        }
                        else if (level == 0){
                                std::cout<<"In MyVGeometryParameter, "<<content<<std::endl;
                        }
                }
void SimpleGeometryParameter::Dump () [virtual]
Reimplemented from MyVGeometryParameter.
Definition at line 359 of file SimpleGeometryParameter.cc.
References DumpInfo().
Referenced by SimpleGeometrySvc::SetGeometry().
{
        DumpInfo();
}
void SimpleGeometryParameter::dump_general_header () [private]
Definition at line 1459 of file SimpleGeometryParameter.cc.
Referenced by DumpInfo().
{
        std::cout<<std::setiosflags(std::ios::left)<<std::setw(15)<<"Name"
                 <<std::setiosflags(std::ios::left)<<std::setw(15)<<"MotherName"
                 <<std::setiosflags(std::ios::left)<<std::setw(15)<<"Matierial"
                 <<std::setiosflags(std::ios::left)<<std::setw(15)<<"SDName"
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"PosX"
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"PosY"
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"PosZ"
                 <<std::setiosflags(std::ios::left)<<std::setw(6) <<"RepNo"
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Ephi"
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Etheta"
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Epsi";
}
void SimpleGeometryParameter::dump_general_note () [private]
Definition at line 1473 of file SimpleGeometryParameter.cc.
Referenced by DumpInfo().
{
        std::cout<<std::setiosflags(std::ios::left)<<std::setw(15)<<""
                 <<std::setiosflags(std::ios::left)<<std::setw(15)<<""
                 <<std::setiosflags(std::ios::left)<<std::setw(15)<<""
                 <<std::setiosflags(std::ios::left)<<std::setw(15)<<""
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                 <<std::setiosflags(std::ios::left)<<std::setw(6) <<""
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg"
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg"
                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg";
}
void SimpleGeometryParameter::dump_general_value (G4int index, G4int j = 0) [private]
Definition at line 1487 of file SimpleGeometryParameter.cc.
References Ephi, Epsi, Etheta, Material, MotherName, Name, Pos, PosType, RepNo, SDName, and SolidBoolean.
Referenced by DumpInfo().
{
        std::cout<<std::setiosflags(std::ios::left)<<std::setw(15)<<Name[index]<<" ";
        if (!SolidBoolean[index]){
                std::cout<<std::setiosflags(std::ios::left)<<std::setw(15)<<MotherName[index]<<" "
                                 <<std::setiosflags(std::ios::left)<<std::setw(15)<<Material[index]<<" "
                                 <<std::setiosflags(std::ios::left)<<std::setw(15)<<SDName[index]<<" ";
                if (PosType[index]=="Cartesian"){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(2) <<"C"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<Pos[index][j].x()/mm
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<Pos[index][j].y()/mm
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<Pos[index][j].z()/mm;
                }
                else if (PosType[index]=="Polar"){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(2) <<"P"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<Pos[index][j].rho()/mm
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<Pos[index][j].phi()/deg
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<Pos[index][j].z()/mm;
                }
                else if (PosType[index]=="Spherical"){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(2) <<"S"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<Pos[index][j].mag()/mm
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<Pos[index][j].phi()/deg
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<Pos[index][j].theta()/deg;
                }
                std::cout<<std::setiosflags(std::ios::left)<<std::setw(6) <<RepNo[index]
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<Ephi[index][j]/deg
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<Etheta[index][j]/deg
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<Epsi[index][j]/deg;
        }
        else{
                std::cout<<"            [BOOLEANCOMPONENT!]";
        }
}
void SimpleGeometryParameter::DumpInfo (void)
Reimplemented from MyVGeometryParameter.
Definition at line 1023 of file SimpleGeometryParameter.cc.
References BooleanSolid_Ephi, BooleanSolid_Epsi, BooleanSolid_Etheta, BooleanSolid_GenIndex, BooleanSolid_Pos, BooleanSolid_PosType, BooleanSolid_sol1, BooleanSolid_sol2, BooleanSolid_type, BooleanSolidNo, Box_GenIndex, Box_X, Box_Y, Box_Z, BoxNo, Cons_GenIndex, Cons_Length, Cons_RMax1, Cons_RMax2, Cons_RMin1, Cons_RMin2, Cons_SpanAng, Cons_StartAng, ConsNo, dump_general_header(), dump_general_note(), dump_general_value(), EllipticalTube_GenIndex, EllipticalTube_X, EllipticalTube_Y, EllipticalTube_Z, EllipticalTubeNo, ExtrudedSolid_GenIndex, ExtrudedSolid_numP, ExtrudedSolid_numZ, ExtrudedSolid_Scale, ExtrudedSolid_X, ExtrudedSolid_X0, ExtrudedSolid_Y, ExtrudedSolid_Y0, ExtrudedSolid_Z, ExtrudedSolidNo, Hype_GenIndex, Hype_innerRadius, Hype_innerStereo, Hype_Length, Hype_outerRadius, Hype_outerStereo, HypeNo, Polycone_GenIndex, Polycone_numZ, Polycone_RMax, Polycone_RMin, Polycone_SpanAng, Polycone_StartAng, Polycone_Z, PolyconeNo, RepNo, Sphere_GenIndex, Sphere_RMax, Sphere_RMin, Sphere_SpanPhi, Sphere_SpanTheta, Sphere_StartPhi, Sphere_StartTheta, SphereNo, Torus_GenIndex, Torus_RMax, Torus_RMin, Torus_Rtor, Torus_SpanAng, Torus_StartAng, TorusNo, Tubs_GenIndex, Tubs_Length, Tubs_RMax, Tubs_RMin, Tubs_SpanAng, Tubs_StartAng, TubsNo, TwistedTubs_dphi, TwistedTubs_endinnerrad, TwistedTubs_endouterrad, TwistedTubs_GenIndex, TwistedTubs_Length, TwistedTubs_twistedangle, and TwistedTubsNo.
Referenced by Dump().
{
        MyVGeometryParameter::DumpInfo();// dump info of its Parent Class first
        std::cout<<"------SimpleGeometry info :--------"<<std::endl;
//      std::cout<<std::scientific<<std::setprecision(2);
        for( G4int i = 0; i < BoxNo; i++ ){
                if ( i == 0 ){
                        std::cout<<"=>Box info:"<<BoxNo<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"x"
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"y"
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"z";
                        dump_general_header();
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm";
                        dump_general_note();
                        std::cout<<std::endl;
                }
                int index = Box_GenIndex[i];
                int repNo = RepNo[index];
                for ( G4int j = 0; j < repNo; j++ ){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Box_X[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Box_Y[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Box_Z[i][j]/mm;
                        dump_general_value(index,j);
                        std::cout<<std::endl;
                }
        }
        for( G4int i = 0; i < EllipticalTubeNo; i++ ){
                if ( i == 0 ){
                        std::cout<<"=>EllipticalTube info:"<<EllipticalTubeNo<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Dx"
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Dy"
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Dz";
                        dump_general_header();
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm";
                        dump_general_note();
                        std::cout<<std::endl;
                }
                int index = EllipticalTube_GenIndex[i];
                int repNo = RepNo[index];
                for ( G4int j = 0; j < repNo; j++ ){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<EllipticalTube_X[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<EllipticalTube_Y[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<EllipticalTube_Z[i][j]/mm;
                        dump_general_value(index,j);
                        std::cout<<std::endl;
                }
        }
        for( G4int i = 0; i < TubsNo; i++ ){
                if ( i == 0 ){
                        std::cout<<"=>Tubs info:"<<TubsNo<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMin"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMax"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Length"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"StartAng"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"SpanAng";
                        dump_general_header();
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg";
                        dump_general_note();
                        std::cout<<std::endl;
                }
                int index = Tubs_GenIndex[i];
                int repNo = RepNo[index];
                for ( G4int j = 0; j < repNo; j++ ){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Tubs_RMin[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Tubs_RMax[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Tubs_Length[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Tubs_StartAng[i][j]/deg
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Tubs_SpanAng[i][j]/deg;
                        dump_general_value(index,j);
                        std::cout<<std::endl;
                }
        }
        for( G4int i = 0; i < TorusNo; i++ ){
                if ( i == 0 ){
                        std::cout<<"=>Torus info:"<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMin"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMax"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Rtor"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"StartAng"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"SpanAng";
                        dump_general_header();
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg";
                        dump_general_note();
                        std::cout<<std::endl;
                }
                int index = Torus_GenIndex[i];
                int repNo = RepNo[index];
                for ( G4int j = 0; j < repNo; j++ ){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Torus_RMin[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Torus_RMax[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Torus_Rtor[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Torus_StartAng[i][j]/deg
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Torus_SpanAng[i][j]/deg;
                        dump_general_value(index,j);
                        std::cout<<std::endl;
                }
        }
        for( G4int i = 0; i < SphereNo; i++ ){
                if ( i == 0 ){
                        std::cout<<"=>Sphere info:"<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMin"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMax"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"StartPhi"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"SpanPhi"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"StartThe"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"SpanThe";
                        dump_general_header();
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg";
                        dump_general_note();
                        std::cout<<std::endl;
                }
                int index = Sphere_GenIndex[i];
                int repNo = RepNo[index];
                for ( G4int j = 0; j < repNo; j++ ){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Sphere_RMin[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Sphere_RMax[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Sphere_StartPhi[i][j]/deg
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Sphere_SpanPhi[i][j]/deg
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<Sphere_StartTheta[i][j]/deg
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<Sphere_SpanTheta[i][j]/deg;
                        dump_general_value(index);
                        std::cout<<std::endl;
                }
        }
        for( G4int i = 0; i < HypeNo; i++ ){
                if ( i == 0 ){
                        std::cout<<"=>Hype info:"<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<"iRadius"
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<"oRadius"
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<"iStereo"
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<"oStereo"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Length";
                        dump_general_header();
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<"deg"
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<"deg"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm";
                        dump_general_note();
                        std::cout<<std::endl;
                }
                int index = Hype_GenIndex[i];
                int repNo = RepNo[index];
                for ( G4int j = 0; j < repNo; j++ ){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<Hype_innerRadius[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<Hype_outerRadius[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<Hype_innerStereo[i][j]/deg
                                <<std::setiosflags(std::ios::left)<<std::setw(10)<<Hype_outerStereo[i][j]/deg
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Hype_Length[i][j]/mm;
                        dump_general_value(index);
                        std::cout<<std::endl;
                }
        }
        for( G4int i = 0; i < TwistedTubsNo; i++ ){
                if ( i == 0 ){
                        std::cout<<"=>TwistedTubs info:"<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                <<std::setiosflags(std::ios::left)<<std::setw(13)<<"TwistedAngle"
                                <<std::setiosflags(std::ios::left)<<std::setw(12)<<"EndInnerRad"
                                <<std::setiosflags(std::ios::left)<<std::setw(12)<<"EndOuterRad"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Length"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"dphi";
                        dump_general_header();
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(13)<<"deg"
                                <<std::setiosflags(std::ios::left)<<std::setw(12)<<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(12)<<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg";
                        dump_general_note();
                        std::cout<<std::endl;
                }
                int index = TwistedTubs_GenIndex[i];
                int repNo = RepNo[index];
                for ( G4int j = 0; j < repNo; j++ ){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                                <<std::setiosflags(std::ios::left)<<std::setw(13)<<TwistedTubs_twistedangle[i][j]/deg
                                <<std::setiosflags(std::ios::left)<<std::setw(12)<<TwistedTubs_endinnerrad[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(12)<<TwistedTubs_endouterrad[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<TwistedTubs_Length[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<TwistedTubs_dphi[i][j]/deg;
                        dump_general_value(index);
                        std::cout<<std::endl;
                }
        }
        for( G4int i = 0; i < ConsNo; i++ ){
                if ( i == 0 ){
                        std::cout<<"=>Cons info:"<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMin1"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMax1"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMin2"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMax2"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Length"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"StartAng"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"SpanAng";
                        dump_general_header();
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg";
                        dump_general_note();
                        std::cout<<std::endl;
                }
                int index = Cons_GenIndex[i];
                int repNo = RepNo[index];
                for ( G4int j = 0; j < repNo; j++ ){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Cons_RMin1[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Cons_RMax1[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Cons_RMin2[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Cons_RMax2[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Cons_Length[i][j]/mm
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Cons_StartAng[i][j]/deg
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Cons_SpanAng[i][j]/deg;
                        dump_general_value(index);
                        std::cout<<std::endl;
                }
        }
        for( G4int i = 0; i < PolyconeNo; i++ ){
                if ( i == 0 ){
                        std::cout<<"=>Polycone info:"<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"numZ"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"StartAng"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"SpanAng";
                        dump_general_header();
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg";
                        dump_general_note();
                        std::cout<<std::endl;
                }
                int index = Polycone_GenIndex[i];
                int repNo = RepNo[index];
                for ( G4int j = 0; j < repNo; j++ ){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Polycone_numZ[i]
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Polycone_StartAng[i][j]/deg
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<Polycone_SpanAng[i][j]/deg;
                        dump_general_value(index);
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Z"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMin"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"RMax"
                                <<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::endl;
                        for (int k = 0; k< Polycone_numZ[i]; k++){
                                std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<k
                                        <<std::setiosflags(std::ios::left)<<std::setw(10) <<Polycone_Z[i][k][j]/mm
                                        <<std::setiosflags(std::ios::left)<<std::setw(10) <<Polycone_RMin[i][k][j]/mm
                                        <<std::setiosflags(std::ios::left)<<std::setw(10) <<Polycone_RMax[i][k][j]/mm
                                        <<std::endl;
                        }
                }
        }
        for( G4int i = 0; i < ExtrudedSolidNo; i++ ){
                if ( i == 0 ){
                        std::cout<<"=>ExtrudedSolid info:"<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"numZ"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"numP";
                        dump_general_header();
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"";
                        dump_general_note();
                        std::cout<<std::endl;
                }
                int index = ExtrudedSolid_GenIndex[i];
                int repNo = RepNo[index];
                for ( G4int j = 0; j < repNo; j++ ){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<ExtrudedSolid_numZ[i]
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<ExtrudedSolid_numP[i];
                        dump_general_value(index);
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Z"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"X0"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Y0"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Scale"
                                <<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<""
                                <<std::endl;
                        for (int k = 0; k< ExtrudedSolid_numZ[i]; k++){
                                std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<k
                                        <<std::setiosflags(std::ios::left)<<std::setw(10) <<ExtrudedSolid_Z[i][k][j]/mm
                                        <<std::setiosflags(std::ios::left)<<std::setw(10) <<ExtrudedSolid_X0[i][k][j]/mm
                                        <<std::setiosflags(std::ios::left)<<std::setw(10) <<ExtrudedSolid_Y0[i][k][j]/mm
                                        <<std::setiosflags(std::ios::left)<<std::setw(10) <<ExtrudedSolid_Scale[i][k][j]
                                        <<std::endl;
                        }
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"X"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Y"
                                <<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                <<std::endl;
                        for (int k = 0; k< ExtrudedSolid_numP[i]; k++){
                                std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<k
                                        <<std::setiosflags(std::ios::left)<<std::setw(10) <<ExtrudedSolid_X[i][k][j]/mm
                                        <<std::setiosflags(std::ios::left)<<std::setw(10) <<ExtrudedSolid_Y[i][k][j]/mm
                                        <<std::endl;
                        }
                }
        }
        for( G4int i = 0; i < BooleanSolidNo; i++ ){
                if ( i == 0 ){
                        std::cout<<"=>BooleanSolid info:"<<BooleanSolidNo<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(10) <<"type."
                                 <<std::setiosflags(std::ios::left)<<std::setw(20) <<"solid1"
                                 <<std::setiosflags(std::ios::left)<<std::setw(20) <<"solid2"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"PosX"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"PosY"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"PosZ"
                                         <<std::setiosflags(std::ios::left)<<std::setw(6) <<"RepNo"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Ephi"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Etheta"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"Epsi";
                        dump_general_header();
                        std::cout<<std::endl;
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(10) <<""
                                 <<std::setiosflags(std::ios::left)<<std::setw(20) <<""
                                 <<std::setiosflags(std::ios::left)<<std::setw(20) <<""
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"mm"
                                         <<std::setiosflags(std::ios::left)<<std::setw(6) <<""
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg"
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) <<"deg";
                        dump_general_note();
                        std::cout<<std::endl;
                }
                int index = BooleanSolid_GenIndex[i];
                int repNo = RepNo[index];
                for ( G4int j = 0; j < repNo; j++ ){
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                                <<std::setiosflags(std::ios::left)<<std::setw(10) <<BooleanSolid_type[i]
                                <<std::setiosflags(std::ios::left)<<std::setw(20)<<BooleanSolid_sol1[i]<<" "
                                <<std::setiosflags(std::ios::left)<<std::setw(20)<<BooleanSolid_sol2[i]<<" ";
                        if (BooleanSolid_PosType[i]=="Cartesian"){
                                std::cout<<std::setiosflags(std::ios::left)<<std::setw(2) <<"C"
                                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<BooleanSolid_Pos[i][j].x()/mm
                                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<BooleanSolid_Pos[i][j].y()/mm
                                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<BooleanSolid_Pos[i][j].z()/mm;
                        }
                        else if (BooleanSolid_PosType[i]=="Polar"){
                                std::cout<<std::setiosflags(std::ios::left)<<std::setw(2) <<"P"
                                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<BooleanSolid_Pos[i][j].rho()/mm
                                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<BooleanSolid_Pos[i][j].phi()/deg
                                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<BooleanSolid_Pos[i][j].z()/mm;
                        }
                        else if (BooleanSolid_PosType[i]=="Spherical"){
                                std::cout<<std::setiosflags(std::ios::left)<<std::setw(2) <<"S"
                                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<BooleanSolid_Pos[i][j].mag()/mm
                                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<BooleanSolid_Pos[i][j].phi()/deg
                                                 <<std::setiosflags(std::ios::left)<<std::setw(10) <<BooleanSolid_Pos[i][j].theta()/deg;
                        }
                        std::cout<<std::setiosflags(std::ios::left)<<std::setw(10) << BooleanSolid_Ephi[i][j]/deg
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) << BooleanSolid_Etheta[i][j]/deg
                                         <<std::setiosflags(std::ios::left)<<std::setw(10) << BooleanSolid_Epsi[i][j]/deg;
                        dump_general_value(index,j);
                        std::cout<<std::endl;
                }
        }
}
bool MyConfigure::FindMacro (G4String word, G4String & value) [inherited]
Definition at line 87 of file MyConfigure.cc.
References MyConfigure::knownValueNames, and MyConfigure::knownValues.
Referenced by MyConfigure::Replace(), and MyConfigure::ReplaceMacro().
{
        bool found = false;
        for (int i = 0; i< knownValues.size(); i++){
                if (knownValueNames[i]==word){
                        value = knownValues[i];
                        found = true;
                        break;
                }
        }
        return found;
}
G4double SimpleGeometryParameter::get_b (G4int VolId) [inline]
Definition at line 179 of file SimpleGeometryParameter.hh.
References check_VolId(), and vB.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return vB[VolId]; else return 0;}
G4double SimpleGeometryParameter::get_BooleanSolid_Ephi (G4int BooleanSolidId, G4int j = 0) [inline]
Definition at line 168 of file SimpleGeometryParameter.hh.
References BooleanSolid_Ephi, and check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Ephi[BooleanSolidId][j]; else return 0;}
G4double SimpleGeometryParameter::get_BooleanSolid_Epsi (G4int BooleanSolidId, G4int j = 0) [inline]
Definition at line 170 of file SimpleGeometryParameter.hh.
References BooleanSolid_Epsi, and check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Epsi[BooleanSolidId][j]; else return 0;}
G4double SimpleGeometryParameter::get_BooleanSolid_Etheta (G4int BooleanSolidId, G4int j = 0) [inline]
Definition at line 169 of file SimpleGeometryParameter.hh.
References BooleanSolid_Etheta, and check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Etheta[BooleanSolidId][j]; else return 0;}
G4double SimpleGeometryParameter::get_BooleanSolid_PosX (G4int BooleanSolidId, G4int j = 0) [inline]
Definition at line 171 of file SimpleGeometryParameter.hh.
References BooleanSolid_Pos, and check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Pos[BooleanSolidId][j].x(); else return 0;}
G4double SimpleGeometryParameter::get_BooleanSolid_PosY (G4int BooleanSolidId, G4int j = 0) [inline]
Definition at line 172 of file SimpleGeometryParameter.hh.
References BooleanSolid_Pos, and check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Pos[BooleanSolidId][j].y(); else return 0;}
G4double SimpleGeometryParameter::get_BooleanSolid_PosZ (G4int BooleanSolidId, G4int j = 0) [inline]
Definition at line 173 of file SimpleGeometryParameter.hh.
References BooleanSolid_Pos, and check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Pos[BooleanSolidId][j].z(); else return 0;}
G4String SimpleGeometryParameter::get_BooleanSolid_sol1 (G4int BooleanSolidId) [inline]
Definition at line 166 of file SimpleGeometryParameter.hh.
References BooleanSolid_sol1, and check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_sol1[BooleanSolidId]; else return "";}
G4String SimpleGeometryParameter::get_BooleanSolid_sol2 (G4int BooleanSolidId) [inline]
Definition at line 167 of file SimpleGeometryParameter.hh.
References BooleanSolid_sol2, and check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_sol2[BooleanSolidId]; else return "";}
G4String SimpleGeometryParameter::get_BooleanSolid_type (G4int BooleanSolidId) [inline]
Definition at line 165 of file SimpleGeometryParameter.hh.
References BooleanSolid_type, and check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_type[BooleanSolidId]; else return "";}
G4double SimpleGeometryParameter::get_Box_X (G4int BoxId, G4int j = 0) [inline]
Definition at line 83 of file SimpleGeometryParameter.hh.
References Box_X, and check_BoxId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BoxId(BoxId)) return Box_X[BoxId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Box_Y (G4int BoxId, G4int j = 0) [inline]
Definition at line 84 of file SimpleGeometryParameter.hh.
References Box_Y, and check_BoxId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BoxId(BoxId)) return Box_Y[BoxId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Box_Z (G4int BoxId, G4int j = 0) [inline]
Definition at line 85 of file SimpleGeometryParameter.hh.
References Box_Z, and check_BoxId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BoxId(BoxId)) return Box_Z[BoxId][j]; else return 0;}
G4int SimpleGeometryParameter::get_BoxNo () [inline]
Definition at line 82 of file SimpleGeometryParameter.hh.
References BoxNo.
{return BoxNo;}
bool MyVGeometryParameter::get_checkoverlap () [inline, inherited]
Definition at line 66 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::checkoverlap.
Referenced by SimpleGeometrySvc::PlaceVolumes().
{return checkoverlap;}
G4double SimpleGeometryParameter::get_Cons_Length (G4int ConsId, G4int j = 0) [inline]
Definition at line 140 of file SimpleGeometryParameter.hh.
References check_ConsId(), and Cons_Length.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_Length[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_RMax1 (G4int ConsId, G4int j = 0) [inline]
Definition at line 136 of file SimpleGeometryParameter.hh.
References check_ConsId(), and Cons_RMax1.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_RMax1[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_RMax2 (G4int ConsId, G4int j = 0) [inline]
Definition at line 138 of file SimpleGeometryParameter.hh.
References check_ConsId(), and Cons_RMax2.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_RMax2[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_RMin1 (G4int ConsId, G4int j = 0) [inline]
Definition at line 137 of file SimpleGeometryParameter.hh.
References check_ConsId(), and Cons_RMin1.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_RMin1[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_RMin2 (G4int ConsId, G4int j = 0) [inline]
Definition at line 139 of file SimpleGeometryParameter.hh.
References check_ConsId(), and Cons_RMin2.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_RMin2[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_SpanAng (G4int ConsId, G4int j = 0) [inline]
Definition at line 142 of file SimpleGeometryParameter.hh.
References check_ConsId(), and Cons_SpanAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_SpanAng[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_StartAng (G4int ConsId, G4int j = 0) [inline]
Definition at line 141 of file SimpleGeometryParameter.hh.
References check_ConsId(), and Cons_StartAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_StartAng[ConsId][j]; else return 0;}
G4int SimpleGeometryParameter::get_ConsNo () [inline]
Definition at line 135 of file SimpleGeometryParameter.hh.
References ConsNo.
{return ConsNo;}
G4double SimpleGeometryParameter::get_EllipticalTube_X (G4int EllipticalTubeId, G4int j = 0) [inline]
Definition at line 89 of file SimpleGeometryParameter.hh.
References check_EllipticalTubeId(), and EllipticalTube_X.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_EllipticalTubeId(EllipticalTubeId)) return EllipticalTube_X[EllipticalTubeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_EllipticalTube_Y (G4int EllipticalTubeId, G4int j = 0) [inline]
Definition at line 90 of file SimpleGeometryParameter.hh.
References check_EllipticalTubeId(), and EllipticalTube_Y.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_EllipticalTubeId(EllipticalTubeId)) return EllipticalTube_Y[EllipticalTubeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_EllipticalTube_Z (G4int EllipticalTubeId, G4int j = 0) [inline]
Definition at line 91 of file SimpleGeometryParameter.hh.
References check_EllipticalTubeId(), and EllipticalTube_Z.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_EllipticalTubeId(EllipticalTubeId)) return EllipticalTube_Z[EllipticalTubeId][j]; else return 0;}
G4int SimpleGeometryParameter::get_EllipticalTubeNo () [inline]
Definition at line 88 of file SimpleGeometryParameter.hh.
References EllipticalTubeNo.
{return EllipticalTubeNo;}
G4double SimpleGeometryParameter::get_Ephi (G4int VolId, G4int j = 0) [inline]
Definition at line 76 of file SimpleGeometryParameter.hh.
References check_VolId(), and Ephi.
Referenced by SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return Ephi[VolId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Epsi (G4int VolId, G4int j = 0) [inline]
Definition at line 78 of file SimpleGeometryParameter.hh.
References check_VolId(), and Epsi.
Referenced by SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return Epsi[VolId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Etheta (G4int VolId, G4int j = 0) [inline]
Definition at line 77 of file SimpleGeometryParameter.hh.
References check_VolId(), and Etheta.
Referenced by SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return Etheta[VolId][j]; else return 0;}
G4int SimpleGeometryParameter::get_ExtrudedSolid_numP (G4int ExtrudedSolidId, G4int j = 0) [inline]
Definition at line 156 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), and ExtrudedSolid_numP.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId)) return ExtrudedSolid_numP[ExtrudedSolidId]; else return 0;}
G4int SimpleGeometryParameter::get_ExtrudedSolid_numZ (G4int ExtrudedSolidId, G4int j = 0) [inline]
Definition at line 155 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), and ExtrudedSolid_numZ.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId)) return ExtrudedSolid_numZ[ExtrudedSolidId]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_Scale (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline]
Definition at line 162 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, and ExtrudedSolid_Scale.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) return ExtrudedSolid_Scale[ExtrudedSolidId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_X (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline]
Definition at line 157 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numP, and ExtrudedSolid_X.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numP[ExtrudedSolidId]) return ExtrudedSolid_X[ExtrudedSolidId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_X0 (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline]
Definition at line 160 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, and ExtrudedSolid_X0.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) return ExtrudedSolid_X0[ExtrudedSolidId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_Y (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline]
Definition at line 158 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numP, and ExtrudedSolid_Y.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numP[ExtrudedSolidId]) return ExtrudedSolid_Y[ExtrudedSolidId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_Y0 (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline]
Definition at line 161 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, and ExtrudedSolid_Y0.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) return ExtrudedSolid_Y0[ExtrudedSolidId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_Z (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline]
Definition at line 159 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, and ExtrudedSolid_Z.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) return ExtrudedSolid_Z[ExtrudedSolidId][i][j]; else return 0;}
G4int SimpleGeometryParameter::get_ExtrudedSolidNo () [inline]
Definition at line 154 of file SimpleGeometryParameter.hh.
References ExtrudedSolidNo.
{return ExtrudedSolidNo;}
G4String MyVGeometryParameter::get_filename () [inline, inherited]
Definition at line 69 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::m_filename.
{ return m_filename; }
G4double SimpleGeometryParameter::get_g (G4int VolId) [inline]
Definition at line 178 of file SimpleGeometryParameter.hh.
References check_VolId(), and vG.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return vG[VolId]; else return 0;}
G4double SimpleGeometryParameter::get_Hype_innerRadius (G4int HypeId, G4int j = 0) [inline]
Definition at line 120 of file SimpleGeometryParameter.hh.
References check_HypeId(), and Hype_innerRadius.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_HypeId(HypeId)) return Hype_innerRadius[HypeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Hype_innerStereo (G4int HypeId, G4int j = 0) [inline]
Definition at line 122 of file SimpleGeometryParameter.hh.
References check_HypeId(), and Hype_innerStereo.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_HypeId(HypeId)) return Hype_innerStereo[HypeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Hype_Length (G4int HypeId, G4int j = 0) [inline]
Definition at line 124 of file SimpleGeometryParameter.hh.
References check_HypeId(), and Hype_Length.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_HypeId(HypeId)) return Hype_Length[HypeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Hype_outerRadius (G4int HypeId, G4int j = 0) [inline]
Definition at line 121 of file SimpleGeometryParameter.hh.
References check_HypeId(), and Hype_outerRadius.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_HypeId(HypeId)) return Hype_outerRadius[HypeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Hype_outerStereo (G4int HypeId, G4int j = 0) [inline]
Definition at line 123 of file SimpleGeometryParameter.hh.
References check_HypeId(), and Hype_outerStereo.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_HypeId(HypeId)) return Hype_outerStereo[HypeId][j]; else return 0;}
G4int SimpleGeometryParameter::get_HypeNo () [inline]
Definition at line 119 of file SimpleGeometryParameter.hh.
References HypeNo.
{return HypeNo;}
int SimpleGeometryParameter::get_index (G4String type, G4int i) [inline, private]
Definition at line 391 of file SimpleGeometryParameter.hh.
References BooleanSolid_GenIndex, Box_GenIndex, check_BooleanSolidId(), check_BoxId(), check_ConsId(), check_EllipticalTubeId(), check_ExtrudedSolidId(), check_HypeId(), check_PolyconeId(), check_SphereId(), check_TorusId(), check_TubsId(), check_TwistedTubsId(), Cons_GenIndex, MyVGeometryParameter::DEBUG(), EllipticalTube_GenIndex, ExtrudedSolid_GenIndex, Hype_GenIndex, Polycone_GenIndex, Sphere_GenIndex, Torus_GenIndex, Tubs_GenIndex, and TwistedTubs_GenIndex.
Referenced by set_b(), set_Ephi(), set_Epsi(), set_Etheta(), set_g(), set_material(), set_MotherName(), set_name(), set_PosX(), set_PosY(), set_PosZ(), set_r(), set_RepNo(), set_SDName(), set_SolidBoolean(), set_SRepNo(), set_t(), and set_vis().
{
                        int k = -1;
                        if ( type == "Box" && check_BoxId(i) ) k = Box_GenIndex[i];
                        else if ( type == "EllipticalTube" && check_EllipticalTubeId(i) ) k = EllipticalTube_GenIndex[i];
                        else if ( type == "Tubs" && check_TubsId(i) ) k = Tubs_GenIndex[i];
                        else if ( type == "Torus" && check_TorusId(i) ) k = Torus_GenIndex[i];
                        else if ( type == "Sphere" && check_SphereId(i) ) k = Sphere_GenIndex[i];
                        else if ( type == "Hype" && check_HypeId(i) ) k = Hype_GenIndex[i];
                        else if ( type == "TwistedTubs" && check_TwistedTubsId(i) ) k = TwistedTubs_GenIndex[i];
                        else if ( type == "Cons" && check_ConsId(i) ) k = Cons_GenIndex[i];
                        else if ( type == "Polycone" && check_PolyconeId(i) ) k = Polycone_GenIndex[i];
                        else if ( type == "ExtrudedSolid_Scale" && check_ExtrudedSolidId(i) ) k = ExtrudedSolid_GenIndex[i];
                        else if ( type == "BooleanSolid" && check_BooleanSolidId(i) ) k = BooleanSolid_GenIndex[i];
                        else DEBUG("Wrong index number or unknown volume type!");
                        return k;
                }
G4String SimpleGeometryParameter::get_material (G4int VolId) [inline]
Definition at line 71 of file SimpleGeometryParameter.hh.
References check_VolId(), and Material.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return Material[VolId]; else return "";}
G4String SimpleGeometryParameter::get_MotherName (G4int VolId) [inline]
Definition at line 70 of file SimpleGeometryParameter.hh.
References check_VolId(), and MotherName.
Referenced by SimpleGeometrySvc::PlaceVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return MotherName[VolId]; else return "";}
G4String MyVGeometryParameter::get_Name () [inline, inherited]
Definition at line 68 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::m_Name.
{ return m_Name; }
G4String SimpleGeometryParameter::get_name (G4int VolId) [inline]
Definition at line 68 of file SimpleGeometryParameter.hh.
References check_VolId(), and Name.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return Name[VolId]; else return "";}
G4int SimpleGeometryParameter::get_Polycone_numZ (G4int PolyconeId, G4int j = 0) [inline]
Definition at line 146 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), and Polycone_numZ.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId)) return Polycone_numZ[PolyconeId]; else return 0;}
G4double SimpleGeometryParameter::get_Polycone_RMax (G4int PolyconeId, G4int i, G4int j = 0) [inline]
Definition at line 147 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), Polycone_numZ, and Polycone_RMax.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) return Polycone_RMax[PolyconeId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_Polycone_RMin (G4int PolyconeId, G4int i, G4int j = 0) [inline]
Definition at line 148 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), Polycone_numZ, and Polycone_RMin.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) return Polycone_RMin[PolyconeId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_Polycone_SpanAng (G4int PolyconeId, G4int j = 0) [inline]
Definition at line 151 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), and Polycone_SpanAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId)) return Polycone_SpanAng[PolyconeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Polycone_StartAng (G4int PolyconeId, G4int j = 0) [inline]
Definition at line 150 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), and Polycone_StartAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId)) return Polycone_StartAng[PolyconeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Polycone_Z (G4int PolyconeId, G4int i, G4int j = 0) [inline]
Definition at line 149 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), Polycone_numZ, and Polycone_Z.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) return Polycone_Z[PolyconeId][i][j]; else return 0;}
G4int SimpleGeometryParameter::get_PolyconeNo () [inline]
Definition at line 145 of file SimpleGeometryParameter.hh.
References PolyconeNo.
{return PolyconeNo;}
G4double SimpleGeometryParameter::get_PosX (G4int VolId, G4int j = 0) [inline]
Definition at line 65 of file SimpleGeometryParameter.hh.
References check_VolId(), and Pos.
Referenced by SimpleGeometrySvc::PlaceVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return Pos[VolId][j].x(); else return 0;}
G4double SimpleGeometryParameter::get_PosY (G4int VolId, G4int j = 0) [inline]
Definition at line 66 of file SimpleGeometryParameter.hh.
References check_VolId(), and Pos.
Referenced by SimpleGeometrySvc::PlaceVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return Pos[VolId][j].y(); else return 0;}
G4double SimpleGeometryParameter::get_PosZ (G4int VolId, G4int j = 0) [inline]
Definition at line 67 of file SimpleGeometryParameter.hh.
References check_VolId(), and Pos.
Referenced by SimpleGeometrySvc::PlaceVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return Pos[VolId][j].z(); else return 0;}
G4double SimpleGeometryParameter::get_r (G4int VolId) [inline]
Definition at line 177 of file SimpleGeometryParameter.hh.
References check_VolId(), and vR.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return vR[VolId]; else return 0;}
void MyVGeometryParameter::get_RepCont (G4String RepCont, G4int & SRepNo, G4int & RepNo) [inherited]
Definition at line 84 of file MyVGeometryParameter.cc.
References MyString2Anything::get_I().
Referenced by GetValue().
{
        size_t sLast = RepCont.last(',');
        if(sLast!=G4String::npos){
                G4String part1 = RepCont.substr(0,sLast);
                G4String part2 = RepCont.substr(sLast+1,RepCont.length()-sLast-1);
                MyString2Anything::get_I(part1,SRepNo);
                MyString2Anything::get_I(part2,RepNo);
        }
        else{ // not found
                sLast = RepCont.last('-');
                if (sLast==G4String::npos){// not found
                        sLast = RepCont.last('~');
                }
                if (sLast!=G4String::npos){
                        G4String part1 = RepCont.substr(0,sLast);
                        G4String part2 = RepCont.substr(sLast+1,RepCont.length()-sLast-1);
                        MyString2Anything::get_I(part1,SRepNo);
                        G4int endNo;
                        MyString2Anything::get_I(part2,endNo);
                        RepNo = endNo - SRepNo + 1;
                }
                else{// not found
                        SRepNo = 0;
                        MyString2Anything::get_I(RepCont,RepNo);
                }
        }
//      std::cout<<"in get_RepCont: \""<<RepCont<<"\" -> ("<<SRepNo<<","<<RepNo<<")"<<std::endl; // to be deleted
}
G4int SimpleGeometryParameter::get_RepNo (G4int VolId) [inline]
Definition at line 73 of file SimpleGeometryParameter.hh.
References check_VolId(), and RepNo.
Referenced by SimpleGeometrySvc::ConstructVolumes(), SimpleGeometrySvc::PlaceVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return RepNo[VolId]; else return 0;}
G4String SimpleGeometryParameter::get_SDName (G4int VolId) [inline]
Definition at line 69 of file SimpleGeometryParameter.hh.
References check_VolId(), and SDName.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return SDName[VolId]; else return "";}
G4bool SimpleGeometryParameter::get_SolidBoolean (G4int VolId) [inline]
Definition at line 79 of file SimpleGeometryParameter.hh.
References check_VolId(), and SolidBoolean.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return SolidBoolean[VolId]; else return false;}
G4int SimpleGeometryParameter::get_SolidIndex (G4int VolId) [inline]
Definition at line 75 of file SimpleGeometryParameter.hh.
References check_VolId(), and SolidIndex.
Referenced by SimpleGeometrySvc::ConstructVolumes(), set_BooleanSolid_Ephi(), set_BooleanSolid_Epsi(), set_BooleanSolid_Etheta(), set_BooleanSolid_PosX(), set_BooleanSolid_PosY(), set_BooleanSolid_PosZ(), set_BooleanSolid_sol1(), set_BooleanSolid_sol2(), set_BooleanSolid_type(), set_Box_X(), set_Box_Y(), set_Box_Z(), set_Cons_Length(), set_Cons_RMax1(), set_Cons_RMax2(), set_Cons_RMin1(), set_Cons_RMin2(), set_Cons_SpanAng(), set_Cons_StartAng(), set_EllipticalTube_X(), set_EllipticalTube_Y(), set_EllipticalTube_Z(), set_ExtrudedSolid_numP(), set_ExtrudedSolid_numZ(), set_ExtrudedSolid_Scale(), set_ExtrudedSolid_X(), set_ExtrudedSolid_X0(), set_ExtrudedSolid_Y(), set_ExtrudedSolid_Y0(), set_ExtrudedSolid_Z(), set_Hype_innerRadius(), set_Hype_innerStereo(), set_Hype_Length(), set_Hype_outerRadius(), set_Hype_outerStereo(), set_Polycone_numZ(), set_Polycone_RMax(), set_Polycone_RMin(), set_Polycone_SpanAng(), set_Polycone_StartAng(), set_Polycone_Z(), set_Sphere_RMax(), set_Sphere_RMin(), set_Sphere_SpanPhi(), set_Sphere_SpanTheta(), set_Sphere_StartPhi(), set_Sphere_StartTheta(), set_Torus_RMax(), set_Torus_RMin(), set_Torus_Rtor(), set_Torus_SpanAng(), set_Torus_StartAng(), set_Tubs_Length(), set_Tubs_RMax(), set_Tubs_RMin(), set_Tubs_SpanAng(), set_Tubs_StartAng(), set_TwistedTubs_dphi(), set_TwistedTubs_endinnerrad(), set_TwistedTubs_endouterrad(), set_TwistedTubs_Length(), set_TwistedTubs_twistedangle(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return SolidIndex[VolId]; else return 0;}
G4String SimpleGeometryParameter::get_SolidType (G4int VolId) [inline]
Definition at line 74 of file SimpleGeometryParameter.hh.
References check_VolId(), and SolidType.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return SolidType[VolId]; else return "";}
G4double SimpleGeometryParameter::get_Sphere_RMax (G4int SphereId, G4int j = 0) [inline]
Definition at line 111 of file SimpleGeometryParameter.hh.
References check_SphereId(), and Sphere_RMax.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_RMax[SphereId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Sphere_RMin (G4int SphereId, G4int j = 0) [inline]
Definition at line 112 of file SimpleGeometryParameter.hh.
References check_SphereId(), and Sphere_RMin.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_RMin[SphereId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Sphere_SpanPhi (G4int SphereId, G4int j = 0) [inline]
Definition at line 114 of file SimpleGeometryParameter.hh.
References check_SphereId(), and Sphere_SpanPhi.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_SpanPhi[SphereId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Sphere_SpanTheta (G4int SphereId, G4int j = 0) [inline]
Definition at line 116 of file SimpleGeometryParameter.hh.
References check_SphereId(), and Sphere_SpanTheta.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_SpanTheta[SphereId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Sphere_StartPhi (G4int SphereId, G4int j = 0) [inline]
Definition at line 113 of file SimpleGeometryParameter.hh.
References check_SphereId(), and Sphere_StartPhi.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_StartPhi[SphereId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Sphere_StartTheta (G4int SphereId, G4int j = 0) [inline]
Definition at line 115 of file SimpleGeometryParameter.hh.
References check_SphereId(), and Sphere_StartTheta.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_StartTheta[SphereId][j]; else return 0;}
G4int SimpleGeometryParameter::get_SphereNo () [inline]
Definition at line 110 of file SimpleGeometryParameter.hh.
References SphereNo.
{return SphereNo;}
G4int SimpleGeometryParameter::get_SRepNo (G4int VolId) [inline]
Definition at line 72 of file SimpleGeometryParameter.hh.
References check_VolId(), and SRepNo.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return SRepNo[VolId]; else return 0;}
G4double SimpleGeometryParameter::get_t (G4int VolId) [inline]
Definition at line 180 of file SimpleGeometryParameter.hh.
References check_VolId(), and vT.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return vT[VolId]; else return 0;}
G4double SimpleGeometryParameter::get_Torus_RMax (G4int TorusId, G4int j = 0) [inline]
Definition at line 103 of file SimpleGeometryParameter.hh.
References check_TorusId(), and Torus_RMax.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TorusId(TorusId)) return Torus_RMax[TorusId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Torus_RMin (G4int TorusId, G4int j = 0) [inline]
Definition at line 104 of file SimpleGeometryParameter.hh.
References check_TorusId(), and Torus_RMin.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TorusId(TorusId)) return Torus_RMin[TorusId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Torus_Rtor (G4int TorusId, G4int j = 0) [inline]
Definition at line 105 of file SimpleGeometryParameter.hh.
References check_TorusId(), and Torus_Rtor.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TorusId(TorusId)) return Torus_Rtor[TorusId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Torus_SpanAng (G4int TorusId, G4int j = 0) [inline]
Definition at line 107 of file SimpleGeometryParameter.hh.
References check_TorusId(), and Torus_SpanAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TorusId(TorusId)) return Torus_SpanAng[TorusId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Torus_StartAng (G4int TorusId, G4int j = 0) [inline]
Definition at line 106 of file SimpleGeometryParameter.hh.
References check_TorusId(), and Torus_StartAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TorusId(TorusId)) return Torus_StartAng[TorusId][j]; else return 0;}
G4int SimpleGeometryParameter::get_TorusNo () [inline]
Definition at line 102 of file SimpleGeometryParameter.hh.
References TorusNo.
{return TorusNo;}
G4double SimpleGeometryParameter::get_Tubs_Length (G4int TubsId, G4int j = 0) [inline]
Definition at line 97 of file SimpleGeometryParameter.hh.
References check_TubsId(), and Tubs_Length.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_TubsId(TubsId)) return Tubs_Length[TubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Tubs_RMax (G4int TubsId, G4int j = 0) [inline]
Definition at line 95 of file SimpleGeometryParameter.hh.
References check_TubsId(), and Tubs_RMax.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_TubsId(TubsId)) return Tubs_RMax[TubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Tubs_RMin (G4int TubsId, G4int j = 0) [inline]
Definition at line 96 of file SimpleGeometryParameter.hh.
References check_TubsId(), and Tubs_RMin.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_TubsId(TubsId)) return Tubs_RMin[TubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Tubs_SpanAng (G4int TubsId, G4int j = 0) [inline]
Definition at line 99 of file SimpleGeometryParameter.hh.
References check_TubsId(), and Tubs_SpanAng.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_TubsId(TubsId)) return Tubs_SpanAng[TubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Tubs_StartAng (G4int TubsId, G4int j = 0) [inline]
Definition at line 98 of file SimpleGeometryParameter.hh.
References check_TubsId(), and Tubs_StartAng.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_TubsId(TubsId)) return Tubs_StartAng[TubsId][j]; else return 0;}
G4int SimpleGeometryParameter::get_TubsNo () [inline]
Definition at line 94 of file SimpleGeometryParameter.hh.
References TubsNo.
{return TubsNo;}
G4double SimpleGeometryParameter::get_TwistedTubs_dphi (G4int TwistedTubsId, G4int j = 0) [inline]
Definition at line 132 of file SimpleGeometryParameter.hh.
References check_TwistedTubsId(), and TwistedTubs_dphi.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TwistedTubsId(TwistedTubsId)) return TwistedTubs_dphi[TwistedTubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_TwistedTubs_endinnerrad (G4int TwistedTubsId, G4int j = 0) [inline]
Definition at line 129 of file SimpleGeometryParameter.hh.
References check_TwistedTubsId(), and TwistedTubs_endinnerrad.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TwistedTubsId(TwistedTubsId)) return TwistedTubs_endinnerrad[TwistedTubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_TwistedTubs_endouterrad (G4int TwistedTubsId, G4int j = 0) [inline]
Definition at line 130 of file SimpleGeometryParameter.hh.
References check_TwistedTubsId(), and TwistedTubs_endouterrad.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TwistedTubsId(TwistedTubsId)) return TwistedTubs_endouterrad[TwistedTubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_TwistedTubs_Length (G4int TwistedTubsId, G4int j = 0) [inline]
Definition at line 131 of file SimpleGeometryParameter.hh.
References check_TwistedTubsId(), and TwistedTubs_Length.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TwistedTubsId(TwistedTubsId)) return TwistedTubs_Length[TwistedTubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_TwistedTubs_twistedangle (G4int TwistedTubsId, G4int j = 0) [inline]
Definition at line 128 of file SimpleGeometryParameter.hh.
References check_TwistedTubsId(), and TwistedTubs_twistedangle.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TwistedTubsId(TwistedTubsId)) return TwistedTubs_twistedangle[TwistedTubsId][j]; else return 0;}
G4int SimpleGeometryParameter::get_TwistedTubsNo () [inline]
Definition at line 127 of file SimpleGeometryParameter.hh.
References TwistedTubsNo.
{return TwistedTubsNo;}
int MyVGeometryParameter::get_VerboseLevel () [inline, inherited]
Definition at line 67 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::fVerboseLevel.
{return fVerboseLevel;}
bool SimpleGeometryParameter::get_vis (G4int VolId) [inline]
Definition at line 176 of file SimpleGeometryParameter.hh.
References check_VolId(), and vVis.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return vVis[VolId]; else return 0;}
G4int SimpleGeometryParameter::get_VolIndex (G4String name) [inline]
Definition at line 54 of file SimpleGeometryParameter.hh.
References Name, and VolNo.
Referenced by MyDetectorManager::GetParaFromVolume(), SimpleGeometrySvc::PlaceVolumes(), set_b(), set_BooleanSolid_Ephi(), set_BooleanSolid_Epsi(), set_BooleanSolid_Etheta(), set_BooleanSolid_PosX(), set_BooleanSolid_PosY(), set_BooleanSolid_PosZ(), set_BooleanSolid_sol1(), set_BooleanSolid_sol2(), set_BooleanSolid_type(), set_Box_X(), set_Box_Y(), set_Box_Z(), set_Cons_Length(), set_Cons_RMax1(), set_Cons_RMax2(), set_Cons_RMin1(), set_Cons_RMin2(), set_Cons_SpanAng(), set_Cons_StartAng(), set_EllipticalTube_X(), set_EllipticalTube_Y(), set_EllipticalTube_Z(), set_Ephi(), set_Epsi(), set_Etheta(), set_ExtrudedSolid_numP(), set_ExtrudedSolid_numZ(), set_ExtrudedSolid_Scale(), set_ExtrudedSolid_X(), set_ExtrudedSolid_X0(), set_ExtrudedSolid_Y(), set_ExtrudedSolid_Y0(), set_ExtrudedSolid_Z(), set_g(), set_Hype_innerRadius(), set_Hype_innerStereo(), set_Hype_Length(), set_Hype_outerRadius(), set_Hype_outerStereo(), set_material(), set_MotherName(), set_name(), set_Polycone_numZ(), set_Polycone_RMax(), set_Polycone_RMin(), set_Polycone_SpanAng(), set_Polycone_StartAng(), set_Polycone_Z(), set_PosX(), set_PosY(), set_PosZ(), set_r(), set_RepNo(), set_SDName(), set_SolidBoolean(), set_Sphere_RMax(), set_Sphere_RMin(), set_Sphere_SpanPhi(), set_Sphere_SpanTheta(), set_Sphere_StartPhi(), set_Sphere_StartTheta(), set_SRepNo(), set_t(), set_Torus_RMax(), set_Torus_RMin(), set_Torus_Rtor(), set_Torus_SpanAng(), set_Torus_StartAng(), set_Tubs_Length(), set_Tubs_RMax(), set_Tubs_RMin(), set_Tubs_SpanAng(), set_Tubs_StartAng(), set_TwistedTubs_dphi(), set_TwistedTubs_endinnerrad(), set_TwistedTubs_endouterrad(), set_TwistedTubs_Length(), set_TwistedTubs_twistedangle(), set_vis(), and PrimaryGeneratorAction::SetUniformPosition().
{
                        int index = -1;
                        for ( int i = 0; i < VolNo; i++ ){
                                if ( Name[i] == name ){
                                        index = i;
                                        break;
                                }
                        }
                        return index;
                }
G4int SimpleGeometryParameter::get_VolNo () [inline]
Definition at line 64 of file SimpleGeometryParameter.hh.
References VolNo.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and SimpleGeometrySvc::PlaceVolumes().
{ return VolNo; }
int SimpleGeometryParameter::GetValue (G4String s_card)
Reimplemented from MyVGeometryParameter.
Definition at line 574 of file SimpleGeometryParameter.cc.
References achieved_componets_Polycone, achieved_P_ExtrudedSolid, achieved_Z_ExtrudedSolid, BooleanSolid_GenIndex, BooleanSolid_PosType, BooleanSolid_sol1, BooleanSolid_sol2, BooleanSolid_type, BooleanSolidNo, Box_GenIndex, BoxNo, Cons_GenIndex, ConsNo, EllipticalTube_GenIndex, EllipticalTubeNo, ExtrudedSolid_GenIndex, ExtrudedSolid_numP, ExtrudedSolid_numZ, ExtrudedSolidNo, fBooleanSolid_Ephi, fBooleanSolid_Epsi, fBooleanSolid_Etheta, fBooleanSolid_PosPhi, fBooleanSolid_PosR, fBooleanSolid_PosTheta, fBooleanSolid_PosX, fBooleanSolid_PosY, fBooleanSolid_PosZ, fBox_X, fBox_Y, fBox_Z, fCons_Length, fCons_RMax1, fCons_RMax2, fCons_RMin1, fCons_RMin2, fCons_SpanAng, fCons_StartAng, fEllipticalTube_X, fEllipticalTube_Y, fEllipticalTube_Z, fEphi, fEpsi, fEtheta, fExtrudedSolid_Scale, fExtrudedSolid_X, fExtrudedSolid_X0, fExtrudedSolid_Y, fExtrudedSolid_Y0, fExtrudedSolid_Z, fHype_innerRadius, fHype_innerStereo, fHype_Length, fHype_outerRadius, fHype_outerStereo, fPolycone_RMax, fPolycone_RMin, fPolycone_SpanAng, fPolycone_StartAng, fPolycone_Z, fPosPhi, fPosR, fPosTheta, fPosX, fPosY, fPosZ, fSphere_RMax, fSphere_RMin, fSphere_SpanPhi, fSphere_SpanTheta, fSphere_StartPhi, fSphere_StartTheta, fTorus_RMax, fTorus_RMin, fTorus_Rtor, fTorus_SpanAng, fTorus_StartAng, fTubs_Length, fTubs_RMax, fTubs_RMin, fTubs_SpanAng, fTubs_StartAng, fTwistedTubs_dphi, fTwistedTubs_endinnerrad, fTwistedTubs_endouterrad, fTwistedTubs_Length, fTwistedTubs_twistedangle, MyVGeometryParameter::get_RepCont(), MyVGeometryParameter::GetValue(), Hype_GenIndex, HypeNo, MyConfigure::knownValueNames, MyConfigure::knownValues, Material, MotherName, Name, notReSetVis, Polycone_GenIndex, Polycone_numZ, PolyconeNo, PosType, MyConfigure::ReplaceMacro(), RepNo, ReSetVis(), SDName, set_b(), set_g(), set_r(), set_t(), set_vis(), SolidBoolean, SolidIndex, SolidType, Sphere_GenIndex, SphereNo, SRepNo, Torus_GenIndex, TorusNo, Tubs_GenIndex, TubsNo, TwistedTubs_GenIndex, TwistedTubsNo, VolNo, waited_ExtrudedSolid_iVol, and waited_Polycone_iVol.
Referenced by InitFromFile().
{
        if (!MyVGeometryParameter::GetValue(s_card)) return 0;// if found by Parent Class, then return.
        int status = 0;// 0 means found the value
        std::stringstream buf_card;
        buf_card.str("");
        buf_card.clear();
        buf_card<<s_card;
        G4String name;
        buf_card>>name;
        G4String s_para;
        int iVol = VolNo;
        bool GoOn = true;
//      std::cout<<"==> "<<s_card<<std::endl; // to be deleted
        if (waited_Polycone_iVol>=0){
                GoOn = false;
                if (achieved_componets_Polycone<Polycone_numZ[waited_Polycone_iVol]){
                        if (name=="PCI"){
                                G4String tPolycone_RMax;
                                G4String tPolycone_RMin;
                                G4String tPolycone_Z;
                                buf_card>>tPolycone_Z>>tPolycone_RMin>>tPolycone_RMax;
                                fPolycone_RMax[waited_Polycone_iVol][achieved_componets_Polycone] = ReplaceMacro(tPolycone_RMax);
                                fPolycone_RMin[waited_Polycone_iVol][achieved_componets_Polycone] = ReplaceMacro(tPolycone_RMin);
                                fPolycone_Z[waited_Polycone_iVol][achieved_componets_Polycone] = ReplaceMacro(tPolycone_Z);
                                achieved_componets_Polycone++;
                        }
                        else {
                                std::cout<<"Not enough Polycone components! Needed: "<<Polycone_numZ[waited_Polycone_iVol]<<", got: "<<achieved_componets_Polycone+1<<std::endl;
                                Polycone_numZ[waited_Polycone_iVol]=achieved_componets_Polycone;
                                GoOn = true;
                        }
                        if (Polycone_numZ[waited_Polycone_iVol]==achieved_componets_Polycone){
                                waited_Polycone_iVol=-1;
                                achieved_componets_Polycone=0;
                        }
                }
        }
        else if (waited_ExtrudedSolid_iVol>=0){
                GoOn = false;
                if (achieved_Z_ExtrudedSolid<ExtrudedSolid_numZ[waited_ExtrudedSolid_iVol]){
                        if (name=="ESZ"){
                                G4String tExtrudedSolid_Z;
                                G4String tExtrudedSolid_X0;
                                G4String tExtrudedSolid_Y0;
                                G4String tExtrudedSolid_Scale;
                                buf_card>>tExtrudedSolid_Z>>tExtrudedSolid_X0>>tExtrudedSolid_Y0>>tExtrudedSolid_Scale;
                                fExtrudedSolid_Z[waited_ExtrudedSolid_iVol][achieved_Z_ExtrudedSolid] = ReplaceMacro(tExtrudedSolid_Z);
                                fExtrudedSolid_X0[waited_ExtrudedSolid_iVol][achieved_Z_ExtrudedSolid] = ReplaceMacro(tExtrudedSolid_X0);
                                fExtrudedSolid_Y0[waited_ExtrudedSolid_iVol][achieved_Z_ExtrudedSolid] = ReplaceMacro(tExtrudedSolid_Y0);
                                fExtrudedSolid_Scale[waited_ExtrudedSolid_iVol][achieved_Z_ExtrudedSolid] = ReplaceMacro(tExtrudedSolid_Scale);
                                achieved_Z_ExtrudedSolid++;
                        }
                }
                if (achieved_P_ExtrudedSolid<ExtrudedSolid_numP[waited_ExtrudedSolid_iVol]){
                        if (name=="ESP"){
                                G4String tExtrudedSolid_X;
                                G4String tExtrudedSolid_Y;
                                buf_card>>tExtrudedSolid_X>>tExtrudedSolid_Y;
                                fExtrudedSolid_X[waited_ExtrudedSolid_iVol][achieved_P_ExtrudedSolid] = ReplaceMacro(tExtrudedSolid_X);
                                fExtrudedSolid_Y[waited_ExtrudedSolid_iVol][achieved_P_ExtrudedSolid] = ReplaceMacro(tExtrudedSolid_Y);
                                achieved_P_ExtrudedSolid++;
                        }
                }
                if (ExtrudedSolid_numP[waited_ExtrudedSolid_iVol]==achieved_P_ExtrudedSolid&&ExtrudedSolid_numZ[waited_ExtrudedSolid_iVol]==achieved_Z_ExtrudedSolid){
                        waited_ExtrudedSolid_iVol=-1;
                        achieved_P_ExtrudedSolid=0;
                        achieved_Z_ExtrudedSolid=0;
                }
        }
        if (GoOn){
                bool foundVolume = false;
                if( name == "B" ){
                        SolidType.push_back("Box");
                        SolidIndex.push_back(BoxNo);
                        G4String tBox_X;
                        G4String tBox_Y;
                        G4String tBox_Z;
                        buf_card>>tBox_X>>tBox_Y>>tBox_Z;
                        fBox_X.push_back(ReplaceMacro(tBox_X));
                        fBox_Y.push_back(ReplaceMacro(tBox_Y));
                        fBox_Z.push_back(ReplaceMacro(tBox_Z));
                        Box_GenIndex.push_back(iVol);
                        BoxNo++;
                        foundVolume = true;
                }
                if( name == "ET" ){
                        SolidType.push_back("EllipticalTube");
                        SolidIndex.push_back(EllipticalTubeNo);
                        G4String tEllipticalTube_X;
                        G4String tEllipticalTube_Y;
                        G4String tEllipticalTube_Z;
                        buf_card>>tEllipticalTube_X>>tEllipticalTube_Y>>tEllipticalTube_Z;
                        fEllipticalTube_X.push_back(ReplaceMacro(tEllipticalTube_X));
                        fEllipticalTube_Y.push_back(ReplaceMacro(tEllipticalTube_Y));
                        fEllipticalTube_Z.push_back(ReplaceMacro(tEllipticalTube_Z));
                        EllipticalTube_GenIndex.push_back(iVol);
                        EllipticalTubeNo++;
                        foundVolume = true;
                }
                else if( name == "T" ){
                        SolidType.push_back("Tubs");
                        SolidIndex.push_back(TubsNo);
                        G4String tTubs_RMax;
                        G4String tTubs_RMin;
                        G4String tTubs_Length;
                        G4String tTubs_StartAng;
                        G4String tTubs_SpanAng;
                        buf_card>>tTubs_RMin>>tTubs_RMax>>tTubs_Length>>tTubs_StartAng>>tTubs_SpanAng;
                        fTubs_RMax.push_back(ReplaceMacro(tTubs_RMax));
                        fTubs_RMin.push_back(ReplaceMacro(tTubs_RMin));
                        fTubs_Length.push_back(ReplaceMacro(tTubs_Length));
                        fTubs_StartAng.push_back(ReplaceMacro(tTubs_StartAng));
                        fTubs_SpanAng.push_back(ReplaceMacro(tTubs_SpanAng));
                        Tubs_GenIndex.push_back(iVol);
                        TubsNo++;
                        foundVolume = true;
                }
                else if( name == "Tor" ){
                        SolidType.push_back("Torus");
                        SolidIndex.push_back(TorusNo);
                        G4String tTorus_RMax;
                        G4String tTorus_RMin;
                        G4String tTorus_Rtor;
                        G4String tTorus_StartAng;
                        G4String tTorus_SpanAng;
                        buf_card>>tTorus_RMin>>tTorus_RMax>>tTorus_Rtor>>tTorus_StartAng>>tTorus_SpanAng;
                        fTorus_RMax.push_back(ReplaceMacro(tTorus_RMax));;
                        fTorus_RMin.push_back(ReplaceMacro(tTorus_RMin));;
                        fTorus_Rtor.push_back(ReplaceMacro(tTorus_Rtor));;
                        fTorus_StartAng.push_back(ReplaceMacro(tTorus_StartAng));;
                        fTorus_SpanAng.push_back(ReplaceMacro(tTorus_SpanAng));;
                        Torus_GenIndex.push_back(iVol);
                        TorusNo++;
                        foundVolume = true;
                }
                else if( name == "Sph" ){
                        SolidType.push_back("Sphere");
                        SolidIndex.push_back(SphereNo);
                        G4String tSphere_RMax;
                        G4String tSphere_RMin;
                        G4String tSphere_StartPhi;
                        G4String tSphere_SpanPhi;
                        G4String tSphere_StartTheta;
                        G4String tSphere_SpanTheta;
                        buf_card>>tSphere_RMin>>tSphere_RMax>>tSphere_StartPhi>>tSphere_SpanPhi>>tSphere_StartTheta>>tSphere_SpanTheta;
                        fSphere_RMax.push_back(ReplaceMacro(tSphere_RMax));;
                        fSphere_RMin.push_back(ReplaceMacro(tSphere_RMin));;
                        fSphere_StartPhi.push_back(ReplaceMacro(tSphere_StartPhi));;
                        fSphere_SpanPhi.push_back(ReplaceMacro(tSphere_SpanPhi));;
                        fSphere_StartTheta.push_back(ReplaceMacro(tSphere_StartTheta));;
                        fSphere_SpanTheta.push_back(ReplaceMacro(tSphere_SpanTheta));;
                        Sphere_GenIndex.push_back(iVol);
                        SphereNo++;
                        foundVolume = true;
                }
                else if( name == "H" ){
                        SolidType.push_back("Hype");
                        SolidIndex.push_back(HypeNo);
                        G4String tHype_innerRadius;
                        G4String tHype_outerRadius;
                        G4String tHype_innerStereo;
                        G4String tHype_outerStereo;
                        G4String tHype_Length;
                        buf_card>>tHype_innerRadius>>tHype_outerRadius>>tHype_innerStereo>>tHype_outerStereo>>tHype_Length;
                        fHype_innerRadius.push_back(ReplaceMacro(tHype_innerRadius));;
                        fHype_outerRadius.push_back(ReplaceMacro(tHype_outerRadius));;
                        fHype_innerStereo.push_back(ReplaceMacro(tHype_innerStereo));;
                        fHype_outerStereo.push_back(ReplaceMacro(tHype_outerStereo));;
                        fHype_Length.push_back(ReplaceMacro(tHype_Length));;
                        Hype_GenIndex.push_back(iVol);
                        HypeNo++;
                        foundVolume = true;
                }
                else if( name == "TT" ){
                        SolidType.push_back("TwistedTubs");
                        SolidIndex.push_back(TwistedTubsNo);
                        G4String tTwistedTubs_twistedangle;
                        G4String tTwistedTubs_endinnerrad;
                        G4String tTwistedTubs_endouterrad;
                        G4String tTwistedTubs_Length;
                        G4String tTwistedTubs_dphi;
                        buf_card>>tTwistedTubs_twistedangle>>tTwistedTubs_endinnerrad>>tTwistedTubs_endouterrad>>tTwistedTubs_Length>>tTwistedTubs_dphi;
                        fTwistedTubs_twistedangle.push_back(ReplaceMacro(tTwistedTubs_twistedangle));;
                        fTwistedTubs_endinnerrad.push_back(ReplaceMacro(tTwistedTubs_endinnerrad));;
                        fTwistedTubs_endouterrad.push_back(ReplaceMacro(tTwistedTubs_endouterrad));;
                        fTwistedTubs_Length.push_back(ReplaceMacro(tTwistedTubs_Length));;
                        fTwistedTubs_dphi.push_back(ReplaceMacro(tTwistedTubs_dphi));;
                        TwistedTubs_GenIndex.push_back(iVol);
                        TwistedTubsNo++;
                        foundVolume = true;
                }
                else if( name == "C" ){
                        SolidType.push_back("Cons");
                        SolidIndex.push_back(ConsNo);
                        G4String tCons_RMax1;
                        G4String tCons_RMin1;
                        G4String tCons_RMax2;
                        G4String tCons_RMin2;
                        G4String tCons_Length;
                        G4String tCons_StartAng;
                        G4String tCons_SpanAng;
                        buf_card>>tCons_RMin1>>tCons_RMax1>>tCons_RMin2>>tCons_RMax2>>tCons_Length>>tCons_StartAng>>tCons_SpanAng;
                        fCons_RMax1.push_back(ReplaceMacro(tCons_RMax1));;
                        fCons_RMin1.push_back(ReplaceMacro(tCons_RMin1));;
                        fCons_RMax2.push_back(ReplaceMacro(tCons_RMax2));;
                        fCons_RMin2.push_back(ReplaceMacro(tCons_RMin2));;
                        fCons_Length.push_back(ReplaceMacro(tCons_Length));;
                        fCons_StartAng.push_back(ReplaceMacro(tCons_StartAng));;
                        fCons_SpanAng.push_back(ReplaceMacro(tCons_SpanAng));;
                        Cons_GenIndex.push_back(iVol);
                        ConsNo++;
                        foundVolume = true;
                }
                else if( name == "PC" ){
                        SolidType.push_back("Polycone");
                        SolidIndex.push_back(PolyconeNo);
                        G4int tPolycone_numZ;
                        G4String tPolycone_StartAng;
                        G4String tPolycone_SpanAng;
                        buf_card>>tPolycone_numZ>>tPolycone_StartAng>>tPolycone_SpanAng;
                        Polycone_numZ.push_back(tPolycone_numZ);
                        fPolycone_StartAng.push_back(ReplaceMacro(tPolycone_StartAng));;
                        fPolycone_SpanAng.push_back(ReplaceMacro(tPolycone_SpanAng));;
                        Polycone_GenIndex.push_back(iVol);
                        std::vector<G4String> empty_vec;
                        empty_vec.resize(tPolycone_numZ);
                        fPolycone_RMax.push_back(empty_vec);;
                        fPolycone_RMin.push_back(empty_vec);;
                        fPolycone_Z.push_back(empty_vec);;
                        waited_Polycone_iVol = PolyconeNo;
                        achieved_componets_Polycone = 0;
                        PolyconeNo++;
                        foundVolume = true;
                }
                else if( name == "ES" ){
                        SolidType.push_back("ExtrudedSolid");
                        SolidIndex.push_back(ExtrudedSolidNo);
                        G4int tExtrudedSolid_numZ;
                        G4int tExtrudedSolid_numP;
                        buf_card>>tExtrudedSolid_numZ>>tExtrudedSolid_numP;
                        ExtrudedSolid_numZ.push_back(tExtrudedSolid_numZ);
                        ExtrudedSolid_numP.push_back(tExtrudedSolid_numP);
                        ExtrudedSolid_GenIndex.push_back(iVol);
                        std::vector<G4String> empty_vec;
                        empty_vec.resize(tExtrudedSolid_numP);
                        fExtrudedSolid_X.push_back(empty_vec);;
                        fExtrudedSolid_Y.push_back(empty_vec);;
                        empty_vec.resize(tExtrudedSolid_numZ);
                        fExtrudedSolid_Z.push_back(empty_vec);;
                        fExtrudedSolid_X0.push_back(empty_vec);;
                        fExtrudedSolid_Y0.push_back(empty_vec);;
                        fExtrudedSolid_Scale.push_back(empty_vec);;
                        waited_ExtrudedSolid_iVol = ExtrudedSolidNo;
                        achieved_P_ExtrudedSolid = 0;
                        achieved_Z_ExtrudedSolid = 0;
                        ExtrudedSolidNo++;
                        foundVolume = true;
                }
                else if( name == "BL" ){
                        SolidType.push_back("BooleanSolid");
                        SolidIndex.push_back(BooleanSolidNo);
                        G4String dump;
                        G4String tBooleanSolid_type;
                        G4String tBooleanSolid_sol1;
                        G4String tBooleanSolid_sol2;
                        G4String tBooleanSolid_Ephi;
                        G4String tBooleanSolid_Etheta;
                        G4String tBooleanSolid_Epsi;
                        G4String tBooleanSolid_PosX;
                        G4String tBooleanSolid_PosY;
                        G4String tBooleanSolid_PosZ;
                        G4String tBooleanSolid_PosR;
                        G4String tBooleanSolid_PosTheta;
                        G4String tBooleanSolid_PosPhi;
                        G4String tBooleanSolid_PosType;
                        buf_card>>tBooleanSolid_type>>tBooleanSolid_sol1>>tBooleanSolid_sol2>>tBooleanSolid_Ephi>>tBooleanSolid_Etheta>>tBooleanSolid_Epsi>>dump;
                        if (dump=="P"){ // Need Polar Coordinates
                                buf_card>>tBooleanSolid_PosR>>tBooleanSolid_PosPhi>>tBooleanSolid_PosZ;
                                tBooleanSolid_PosType = "Polar";
                        }
                        else if (dump=="S"){ // Need Spherical Coordinates
                                buf_card>>tBooleanSolid_PosR>>tBooleanSolid_PosPhi>>tBooleanSolid_PosTheta;
                                tBooleanSolid_PosType = "Spherical";
                        }
                        else if (dump=="C"){ // Need Cartesian Coordinates
                                buf_card>>tBooleanSolid_PosX>>tBooleanSolid_PosY>>tBooleanSolid_PosZ;
                                tBooleanSolid_PosType = "Cartesian";
                        }
                        else{ // By default, need Cartesian Coordinates
                                tBooleanSolid_PosX=dump;
                                buf_card>>tBooleanSolid_PosY>>tBooleanSolid_PosZ;
                                tBooleanSolid_PosType = "Cartesian";
                        }
                        BooleanSolid_type.push_back(tBooleanSolid_type);
                        BooleanSolid_sol1.push_back(tBooleanSolid_sol1);
                        BooleanSolid_sol2.push_back(tBooleanSolid_sol2);
                        fBooleanSolid_Ephi.push_back(ReplaceMacro(tBooleanSolid_Ephi));
                        fBooleanSolid_Etheta.push_back(ReplaceMacro(tBooleanSolid_Etheta));
                        fBooleanSolid_Epsi.push_back(ReplaceMacro(tBooleanSolid_Epsi));
                        fBooleanSolid_PosX.push_back(ReplaceMacro(tBooleanSolid_PosX));
                        fBooleanSolid_PosY.push_back(ReplaceMacro(tBooleanSolid_PosY));
                        fBooleanSolid_PosZ.push_back(ReplaceMacro(tBooleanSolid_PosZ));
                        fBooleanSolid_PosR.push_back(ReplaceMacro(tBooleanSolid_PosR));
                        fBooleanSolid_PosTheta.push_back(ReplaceMacro(tBooleanSolid_PosTheta));
                        fBooleanSolid_PosPhi.push_back(ReplaceMacro(tBooleanSolid_PosPhi));
                        BooleanSolid_PosType.push_back(ReplaceMacro(tBooleanSolid_PosType));
                        BooleanSolid_GenIndex.push_back(iVol);
                        BooleanSolidNo++;
                        foundVolume = true;
                }
                if (foundVolume){
                        G4String dump;
                        G4String tPosX;
                        G4String tPosY;
                        G4String tPosZ;
                        G4String tPosR;
                        G4String tPosTheta;
                        G4String tPosPhi;
                        G4String tPosType;
                        G4String tRepCont;
                        G4int tRepNo = 1;
                        G4int tSRepNo = 0;
                        G4String tSDName;
                        G4String tEphi;
                        G4String tEtheta;
                        G4String tEpsi;
                        G4String tName;
                        G4String tMotherName;
                        G4String tMaterial;
                        G4bool   tSolidBoolean = true;
                        buf_card>>tName>>tRepCont;
                        get_RepCont(tRepCont,tSRepNo,tRepNo);
                        if(buf_card>>tMotherName){
                                tSolidBoolean = false;
                                buf_card>>tMaterial>>tSDName>>dump;
                                if (dump=="P"){ // Need Polar Coordinates
                                        buf_card>>tPosR>>tPosPhi>>tPosZ;
                                        tPosType = "Polar";
                                }
                                else if (dump=="S"){ // Need Spherical Coordinates
                                        buf_card>>tPosR>>tPosPhi>>tPosTheta;
                                        tPosType = "Spherical";
                                }
                                else if (dump=="C"){ // Need Cartesian Coordinates
                                        buf_card>>tPosX>>tPosY>>tPosZ;
                                        tPosType = "Cartesian";
                                }
                                else{ // By default, need Cartesian Coordinates
                                        tPosX=dump;
                                        buf_card>>tPosY>>tPosZ;
                                        tPosType = "Cartesian";
                                }
                                buf_card>>tEphi>>tEtheta>>tEpsi;
                        }
                        fPosX.push_back(ReplaceMacro(tPosX));;
                        fPosY.push_back(ReplaceMacro(tPosY));;
                        fPosZ.push_back(ReplaceMacro(tPosZ));;
                        fPosR.push_back(ReplaceMacro(tPosR));;
                        fPosPhi.push_back(ReplaceMacro(tPosPhi));;
                        fPosTheta.push_back(ReplaceMacro(tPosTheta));;
                        PosType.push_back(tPosType);
                        Name.push_back(tName);
                        MotherName.push_back(tMotherName);
                        Material.push_back(tMaterial);
                        SDName.push_back(tSDName);
                        SRepNo.push_back(tSRepNo);
                        RepNo.push_back(tRepNo);
                        fEphi.push_back(ReplaceMacro(tEphi));;
                        fEtheta.push_back(ReplaceMacro(tEtheta));;
                        fEpsi.push_back(ReplaceMacro(tEpsi));;
                        SolidBoolean.push_back(tSolidBoolean);
                        VolNo++;
//                      std::cout<<"found Volume:"<<tName<<std::endl; // to be deleted
                }
                else if ( name == "DEFINE:" ){
                        G4String MacroName;
                        G4String MacroValue;
                        buf_card>>MacroName>>MacroValue;
//                      std::cout<<"found DEFINE:"<<std::endl; // to be deleted
                        MacroValue = ReplaceMacro(MacroValue);
                        std::cout<<"Define: "<<MacroName<<":\t"<<MacroValue<<std::endl;
                        bool foundName = false;
                        for (int i = 0; i < knownValueNames.size(); i++){
                                if (knownValueNames[i]==MacroName){ // If this name occurred once, replace the value
                                        foundName = true;
                                        knownValues[i]=MacroValue;
                                        break;
                                }
                        }
                        if (!foundName){
                                knownValueNames.push_back(MacroName);
                                knownValues.push_back(MacroValue);
                        }
                }
                else if ( name == "VISSETTING" ){
                        if(notReSetVis) ReSetVis();
                        status = -1;
                }
                else{
                        bool foundornot = false;
                        if ( name.substr(0,4) == "vis_" ){
                                std::stringstream buf_temp;
                                for ( G4int i = 0; i < VolNo; i++ ){
                                        buf_temp.str("");
                                        buf_temp.clear();
                                        buf_temp<<"vis_"<<Name[i];
                                        if( (std::string)name == buf_temp.str() ){
                                                set_vis(i,true);
                                                G4double vTr, vTg, vTb;
                                                G4double vTT = 0;
                                                buf_card>>vTr>>vTg>>vTb>>vTT;
                                                if (!vTT) vTT = 1;
                                                set_r(i,vTr);
                                                set_g(i,vTg);
                                                set_b(i,vTb);
                                                set_t(i,vTT);
                                                foundornot = true;
                                                break; // got the parameter, go to next line
                                        }
                                }
                                buf_temp.str("");
                                buf_temp.clear();
                        }
                        if (!foundornot){
                                status = 1;
                        }
                }
        }
        buf_card.str("");
        buf_card.clear();
        return status;
}
std::vector< G4String > MyConfigure::GetWords (G4String formula) [inherited]
Definition at line 48 of file MyConfigure.cc.
Referenced by MyConfigure::ReplaceMacro().
{
        std::vector<G4String> words;
        words.clear();
        const char* cformula = formula.c_str();
        int length = strlen(cformula);
        char temp[1240];
        int tempoffset = 0;
        for ( int offset = 0; offset < length; offset++ ){
                char c = cformula[offset];
                bool isword = false;
                if (c>='a'&&c<='z'
                        ||c>='A'&&c<='Z'
                        ||c>='0'&&c<='9'
                        ||c=='_'
                   ){
                        temp[tempoffset++] = cformula[offset];
                        isword = true;
                }
                if (!isword||offset==length-1){
                        if (tempoffset>0){
                                temp[tempoffset++] = '\0';
                                tempoffset=0;
                                G4String word = temp;
                                bool found = false;
                                for(int iWord = 0; iWord<words.size(); iWord++){
                                        if (words[iWord]==word){
                                                found = true;
                                                break;
                                        }
                                }
                                if (!found){
                                        words.push_back(word);
                                }
                        }
                }
        }
        return words;
}
void SimpleGeometryParameter::InitFromFile (G4String file_name) [virtual]
Reimplemented from MyVGeometryParameter.
Definition at line 39 of file SimpleGeometryParameter.cc.
References Calculate(), CheckInfo(), MyVGeometryParameter::DEBUG(), GetValue(), MyVGeometryParameter::ISEMPTY(), Preset(), and MyVGeometryParameter::set_filename().
{
        set_filename(file_name);
        //Remember to preset first!
        Preset();
        std::ifstream fin_card(file_name);
        if(!fin_card){
                G4String content = "SimpleGeometryParameter::InitFromFile(), cannot find output card \"" + file_name + "\"";
                DEBUG(content);
        }
        G4String s_card;
        while(getline(fin_card,s_card)){
                //eleminate useless lines
                if ( ISEMPTY(s_card) ) continue;
                int status = GetValue(s_card);
                if( status > 0 ){
                        G4String content = "SimpleGeometryParameter: unknown line:" + s_card + "\n  in file " + file_name + "! Will ignore this line!";
                        DEBUG(content,0);
                }
        }
        fin_card.close();
        if (CheckInfo()){
                DEBUG("SimpleGeometryParameter::InitFromFile(), insufficient simple solid info");
        }
        Calculate();
}
bool MyVGeometryParameter::ISEMPTY (G4String s_card) [inherited]
Definition at line 115 of file MyVGeometryParameter.cc.
Referenced by InitFromFile().
{
        bool flag = false;
        const char* c_card = s_card.c_str();
        G4int length = strlen(c_card);
        G4int offset = 0;
        for ( ; offset < length; offset++ ){
                if ( c_card[offset] != ' ' ) break;
        }
        if ( c_card[offset] == '#' || (c_card[offset] == '/' && c_card[offset+1] == '/') || length - offset == 0 ){
                flag = true;
        }
        return flag;
}
void SimpleGeometryParameter::Preset ()
Reimplemented from MyVGeometryParameter.
Definition at line 374 of file SimpleGeometryParameter.cc.
References achieved_componets_Polycone, achieved_P_ExtrudedSolid, achieved_Z_ExtrudedSolid, BooleanSolid_Ephi, BooleanSolid_Epsi, BooleanSolid_Etheta, BooleanSolid_GenIndex, BooleanSolid_Pos, BooleanSolid_PosType, BooleanSolid_sol1, BooleanSolid_sol2, BooleanSolid_type, BooleanSolidNo, Box_GenIndex, Box_X, Box_Y, Box_Z, BoxNo, Cons_GenIndex, Cons_Length, Cons_RMax1, Cons_RMax2, Cons_RMin1, Cons_RMin2, Cons_SpanAng, Cons_StartAng, ConsNo, EllipticalTube_GenIndex, EllipticalTube_X, EllipticalTube_Y, EllipticalTube_Z, EllipticalTubeNo, Ephi, Epsi, Etheta, ExtrudedSolid_GenIndex, ExtrudedSolid_numP, ExtrudedSolid_numZ, ExtrudedSolid_Scale, ExtrudedSolid_X, ExtrudedSolid_X0, ExtrudedSolid_Y, ExtrudedSolid_Y0, ExtrudedSolid_Z, ExtrudedSolidNo, fBooleanSolid_Ephi, fBooleanSolid_Epsi, fBooleanSolid_Etheta, fBooleanSolid_PosPhi, fBooleanSolid_PosR, fBooleanSolid_PosTheta, fBooleanSolid_PosX, fBooleanSolid_PosY, fBooleanSolid_PosZ, fBox_X, fBox_Y, fBox_Z, fCons_Length, fCons_RMax1, fCons_RMax2, fCons_RMin1, fCons_RMin2, fCons_SpanAng, fCons_StartAng, fEllipticalTube_X, fEllipticalTube_Y, fEllipticalTube_Z, fEphi, fEpsi, fEtheta, fExtrudedSolid_Scale, fExtrudedSolid_X, fExtrudedSolid_X0, fExtrudedSolid_Y, fExtrudedSolid_Y0, fExtrudedSolid_Z, fHype_innerRadius, fHype_innerStereo, fHype_Length, fHype_outerRadius, fHype_outerStereo, fPolycone_RMax, fPolycone_RMin, fPolycone_SpanAng, fPolycone_StartAng, fPolycone_Z, fPosPhi, fPosR, fPosTheta, fPosX, fPosY, fPosZ, fSphere_RMax, fSphere_RMin, fSphere_SpanPhi, fSphere_SpanTheta, fSphere_StartPhi, fSphere_StartTheta, fTorus_RMax, fTorus_RMin, fTorus_Rtor, fTorus_SpanAng, fTorus_StartAng, fTubs_Length, fTubs_RMax, fTubs_RMin, fTubs_SpanAng, fTubs_StartAng, fTwistedTubs_dphi, fTwistedTubs_endinnerrad, fTwistedTubs_endouterrad, fTwistedTubs_Length, fTwistedTubs_twistedangle, Hype_GenIndex, Hype_innerRadius, Hype_innerStereo, Hype_Length, Hype_outerRadius, Hype_outerStereo, HypeNo, Material, MotherName, Name, notReSetVis, Polycone_GenIndex, Polycone_numZ, Polycone_RMax, Polycone_RMin, Polycone_SpanAng, Polycone_StartAng, Polycone_Z, PolyconeNo, Pos, PosType, RepNo, SDName, SolidBoolean, SolidIndex, SolidType, Sphere_GenIndex, Sphere_RMax, Sphere_RMin, Sphere_SpanPhi, Sphere_SpanTheta, Sphere_StartPhi, Sphere_StartTheta, SphereNo, SRepNo, Torus_GenIndex, Torus_RMax, Torus_RMin, Torus_Rtor, Torus_SpanAng, Torus_StartAng, TorusNo, Tubs_GenIndex, Tubs_Length, Tubs_RMax, Tubs_RMin, Tubs_SpanAng, Tubs_StartAng, TubsNo, TwistedTubs_dphi, TwistedTubs_endinnerrad, TwistedTubs_endouterrad, TwistedTubs_GenIndex, TwistedTubs_Length, TwistedTubs_twistedangle, TwistedTubsNo, VolNo, waited_ExtrudedSolid_iVol, and waited_Polycone_iVol.
Referenced by InitFromFile().
{
        MyVGeometryParameter::Preset();// Call its Parent class to preset
        notReSetVis = true;
        VolNo = 0;
        BoxNo = 0;
        EllipticalTubeNo = 0;
        TubsNo = 0;
        TorusNo = 0;
        SphereNo = 0;
        HypeNo = 0;
        TwistedTubsNo = 0;
        ConsNo = 0;
        PolyconeNo = 0;
        ExtrudedSolidNo = 0;
        BooleanSolidNo = 0;
        //General info about volume
        Name.clear();
        MotherName.clear();
        SDName.clear();
        Material.clear();
        SRepNo.clear();
        RepNo.clear();
        SolidType.clear();
        SolidIndex.clear();
        SolidBoolean.clear();
        fPosX.clear();
        fPosY.clear();
        fPosZ.clear();
        fPosR.clear();
        fPosPhi.clear();
        fPosTheta.clear();
        PosType.clear();
        fEphi.clear();
        fEtheta.clear();
        fEpsi.clear();
        Pos.clear();
        Ephi.clear();
        Etheta.clear();
        Epsi.clear();
        //Box info
        fBox_X.clear();
        fBox_Y.clear();
        fBox_Z.clear();
        Box_X.clear();
        Box_Y.clear();
        Box_Z.clear();
        Box_GenIndex.clear();
        //EllipticalTube info
        fEllipticalTube_X.clear();
        fEllipticalTube_Y.clear();
        fEllipticalTube_Z.clear();
        EllipticalTube_X.clear();
        EllipticalTube_Y.clear();
        EllipticalTube_Z.clear();
        EllipticalTube_GenIndex.clear();
        //Tubs info
        fTubs_RMax.clear();
        fTubs_RMin.clear();
        fTubs_Length.clear();
        fTubs_StartAng.clear();
        fTubs_SpanAng.clear();
        Tubs_RMax.clear();
        Tubs_RMin.clear();
        Tubs_Length.clear();
        Tubs_StartAng.clear();
        Tubs_SpanAng.clear();
        Tubs_GenIndex.clear();
        //Torus info
        fTorus_RMax.clear();
        fTorus_RMin.clear();
        fTorus_Rtor.clear();
        fTorus_StartAng.clear();
        fTorus_SpanAng.clear();
        Torus_RMax.clear();
        Torus_RMin.clear();
        Torus_Rtor.clear();
        Torus_StartAng.clear();
        Torus_SpanAng.clear();
        Torus_GenIndex.clear();
        //Sphere info
        fSphere_RMax.clear();
        fSphere_RMin.clear();
        fSphere_StartPhi.clear();
        fSphere_SpanPhi.clear();
        fSphere_StartTheta.clear();
        fSphere_SpanTheta.clear();
        Sphere_RMax.clear();
        Sphere_RMin.clear();
        Sphere_StartPhi.clear();
        Sphere_SpanPhi.clear();
        Sphere_StartTheta.clear();
        Sphere_SpanTheta.clear();
        Sphere_GenIndex.clear();
        //Hype info
        fHype_innerRadius.clear();
        fHype_outerRadius.clear();
        fHype_innerStereo.clear();
        fHype_outerStereo.clear();
        fHype_Length.clear();
        Hype_innerRadius.clear();
        Hype_outerRadius.clear();
        Hype_innerStereo.clear();
        Hype_outerStereo.clear();
        Hype_Length.clear();
        Hype_GenIndex.clear();
        //TwistedTubs info
        fTwistedTubs_twistedangle.clear();
        fTwistedTubs_endinnerrad.clear();
        fTwistedTubs_endouterrad.clear();
        fTwistedTubs_Length.clear();
        fTwistedTubs_dphi.clear();
        TwistedTubs_twistedangle.clear();
        TwistedTubs_endinnerrad.clear();
        TwistedTubs_endouterrad.clear();
        TwistedTubs_Length.clear();
        TwistedTubs_dphi.clear();
        TwistedTubs_GenIndex.clear();
        //Cons info
        fCons_RMax1.clear();
        fCons_RMin1.clear();
        fCons_RMax2.clear();
        fCons_RMin2.clear();
        fCons_Length.clear();
        fCons_StartAng.clear();
        fCons_SpanAng.clear();
        Cons_RMax1.clear();
        Cons_RMin1.clear();
        Cons_RMax2.clear();
        Cons_RMin2.clear();
        Cons_Length.clear();
        Cons_StartAng.clear();
        Cons_SpanAng.clear();
        Cons_GenIndex.clear();
        //Polycone info
        fPolycone_RMax.clear();
        fPolycone_RMin.clear();
        fPolycone_Z.clear();
        Polycone_RMax.clear();
        Polycone_RMin.clear();
        Polycone_Z.clear();
        Polycone_numZ.clear();
        fPolycone_StartAng.clear();
        fPolycone_SpanAng.clear();
        Polycone_StartAng.clear();
        Polycone_SpanAng.clear();
        Polycone_GenIndex.clear();
        waited_Polycone_iVol = -1;
        achieved_componets_Polycone = 0;
        //ExtrudedSolid info
        fExtrudedSolid_X.clear();
        fExtrudedSolid_Y.clear();
        fExtrudedSolid_Z.clear();
        fExtrudedSolid_X0.clear();
        fExtrudedSolid_Y0.clear();
        fExtrudedSolid_Scale.clear();
        ExtrudedSolid_X.clear();
        ExtrudedSolid_Y.clear();
        ExtrudedSolid_Z.clear();
        ExtrudedSolid_X0.clear();
        ExtrudedSolid_Y0.clear();
        ExtrudedSolid_Scale.clear();
        ExtrudedSolid_numZ.clear();
        ExtrudedSolid_numP.clear();
        ExtrudedSolid_GenIndex.clear();
        waited_ExtrudedSolid_iVol = -1;
        achieved_Z_ExtrudedSolid = 0;
        achieved_P_ExtrudedSolid = 0;
        //BooleanSolid info
        BooleanSolid_type.clear();
        BooleanSolid_sol1.clear();
        BooleanSolid_sol2.clear();
        fBooleanSolid_Ephi.clear();
        fBooleanSolid_Etheta.clear();
        fBooleanSolid_Epsi.clear();
        fBooleanSolid_PosX.clear();
        fBooleanSolid_PosY.clear();
        fBooleanSolid_PosZ.clear();
        fBooleanSolid_PosR.clear();
        fBooleanSolid_PosPhi.clear();
        fBooleanSolid_PosTheta.clear();
        BooleanSolid_PosType.clear();
        BooleanSolid_Ephi.clear();
        BooleanSolid_Etheta.clear();
        BooleanSolid_Epsi.clear();
        BooleanSolid_Pos.clear();
        BooleanSolid_GenIndex.clear();
}
void MyConfigure::Replace (G4String & formula, G4String word, G4String value) [inherited]
Definition at line 99 of file MyConfigure.cc.
References MyConfigure::FindMacro().
Referenced by MyConfigure::ReplaceMacro().
{
//      std::cout<<"-- \""<<formula<<"\""<<std::endl; // to be deleted
        G4String newform = "";
        const char* cformula = formula.c_str();
        int length = strlen(cformula);
        char temp[1024];
        int tempoffset = 0;
        char cnewform[1024];
        int newformoffset = 0;
        for ( int offset = 0; offset < length; offset++ ){
                char c = cformula[offset];
                bool isword = false;
                if (c>='a'&&c<='z'
                        ||c>='A'&&c<='Z'
                        ||c>='0'&&c<='9'
                        ||c=='_'
                   ){
                        temp[tempoffset++] = cformula[offset];
                        isword = true;
                }
                if (!isword||offset==length-1){
                        if (tempoffset>0){
                                temp[tempoffset] = '\0';
                                tempoffset=0;
                                if (newformoffset>0){
                                        cnewform[newformoffset] = '\0';
                                        newformoffset=0;
                                        G4String newformtemp = cnewform;
                                        newform=newform+newformtemp;
                                }
                                G4String word = temp;
//                              std::cout<<"            \""<<word<<"\""<<std::endl; // to be deleted
                                G4String newword;
                                bool found = FindMacro(word,newword);
                                if (found){
                                        newform=newform+"("+newword+")";
                                }
                                else{
                                        newform=newform+word;
                                }
//                              std::cout<<"            to \""<<newword<<"\""<<std::endl; // to be deleted
                        }
                        if(!isword){
                                cnewform[newformoffset++] = cformula[offset];
                        }
                        if (offset==length-1){
                                cnewform[newformoffset] = '\0';
                                G4String newformtemp = cnewform;
                                newform=newform+newformtemp;
                        }
                }
        }
//      std::cout<<"    -->\""<<newform<<"\""<<std::endl; // to be deleted
        formula = newform;
}
G4String MyConfigure::ReplaceMacro (G4String formula) [inherited]
Definition at line 33 of file MyConfigure.cc.
References MyConfigure::FindMacro(), MyConfigure::GetWords(), and MyConfigure::Replace().
Referenced by GetValue(), and PrimaryGeneratorAction::ReadCard().
{
//      std::cout<<"TO replace for: \""<<formula<<"\""<<std::endl; // to be deleted
        std::vector<G4String> words = GetWords(formula);
//      std::cout<<"    "<<words.size()<<" words"<<std::endl; // to be deleted
        for (int iWord = 0; iWord < words.size(); iWord++ ){
//              std::cout<<"            "<<iWord<<std::endl; // to be deleted
                G4String value;
                if (FindMacro(words[iWord],value)){
                        Replace(formula,words[iWord],value);
                }
        }
//      std::cout<<"\t=>"<<formula<<std::endl;
        return formula;
}
void SimpleGeometryParameter::ReSetVis () [private]
Definition at line 1009 of file SimpleGeometryParameter.cc.
References notReSetVis, vB, vG, VolNo, vR, vT, and vVis.
Referenced by GetValue().
{
        vVis.resize(VolNo);
        vR.resize(VolNo);
        vG.resize(VolNo);
        vB.resize(VolNo);
        vT.resize(VolNo);
        for ( G4int i = 0; i < VolNo; i++ ){
                vVis[i] = false;
        }
        notReSetVis = false;
}
void SimpleGeometryParameter::set_b (G4String name, G4double val) [inline]
Definition at line 385 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and vB.
{int k = get_VolIndex(name); vB[k] = val;}
void SimpleGeometryParameter::set_b (G4int i, G4double val) [inline]
Definition at line 379 of file SimpleGeometryParameter.hh.
References vB.
{ vB[i] = val;}
void SimpleGeometryParameter::set_b (G4String type, G4int i, G4double val) [inline]
Definition at line 373 of file SimpleGeometryParameter.hh.
References get_index(), and vB.
Referenced by GetValue(), and SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); vB[k] = val;}
void SimpleGeometryParameter::set_BooleanSolid_Ephi (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 362 of file SimpleGeometryParameter.hh.
References BooleanSolid_Ephi, check_BooleanSolidId(), get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Ephi[i][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_Ephi (G4int BooleanSolidId, G4double val, G4int j = 0) [inline]
Definition at line 352 of file SimpleGeometryParameter.hh.
References BooleanSolid_Ephi, and check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Ephi[BooleanSolidId][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_Epsi (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 364 of file SimpleGeometryParameter.hh.
References BooleanSolid_Epsi, check_BooleanSolidId(), get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Epsi[i][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_Epsi (G4int BooleanSolidId, G4double val, G4int j = 0) [inline]
Definition at line 354 of file SimpleGeometryParameter.hh.
References BooleanSolid_Epsi, and check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Epsi[BooleanSolidId][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_Etheta (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 363 of file SimpleGeometryParameter.hh.
References BooleanSolid_Etheta, check_BooleanSolidId(), get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Etheta[i][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_Etheta (G4int BooleanSolidId, G4double val, G4int j = 0) [inline]
Definition at line 353 of file SimpleGeometryParameter.hh.
References BooleanSolid_Etheta, and check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Etheta[BooleanSolidId][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_PosX (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 365 of file SimpleGeometryParameter.hh.
References BooleanSolid_Pos, check_BooleanSolidId(), get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Pos[i][j].setX(val);}
void SimpleGeometryParameter::set_BooleanSolid_PosX (G4int BooleanSolidId, G4double val, G4int j = 0) [inline]
Definition at line 355 of file SimpleGeometryParameter.hh.
References BooleanSolid_Pos, and check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Pos[BooleanSolidId][j].setX(val);}
void SimpleGeometryParameter::set_BooleanSolid_PosY (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 366 of file SimpleGeometryParameter.hh.
References BooleanSolid_Pos, check_BooleanSolidId(), get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Pos[i][j].setY(val);}
void SimpleGeometryParameter::set_BooleanSolid_PosY (G4int BooleanSolidId, G4double val, G4int j = 0) [inline]
Definition at line 356 of file SimpleGeometryParameter.hh.
References BooleanSolid_Pos, and check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Pos[BooleanSolidId][j].setY(val);}
void SimpleGeometryParameter::set_BooleanSolid_PosZ (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 367 of file SimpleGeometryParameter.hh.
References BooleanSolid_Pos, check_BooleanSolidId(), get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Pos[i][j].setZ(val);}
void SimpleGeometryParameter::set_BooleanSolid_PosZ (G4int BooleanSolidId, G4double val, G4int j = 0) [inline]
Definition at line 357 of file SimpleGeometryParameter.hh.
References BooleanSolid_Pos, and check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Pos[BooleanSolidId][j].setZ(val);}
void SimpleGeometryParameter::set_BooleanSolid_sol1 (G4String name, G4String val) [inline]
Definition at line 360 of file SimpleGeometryParameter.hh.
References BooleanSolid_sol1, check_BooleanSolidId(), get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_sol1[i]=val;}
void SimpleGeometryParameter::set_BooleanSolid_sol1 (G4int BooleanSolidId, G4String val) [inline]
Definition at line 350 of file SimpleGeometryParameter.hh.
References BooleanSolid_sol1, and check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_sol1[BooleanSolidId]=val;}
void SimpleGeometryParameter::set_BooleanSolid_sol2 (G4String name, G4String val) [inline]
Definition at line 361 of file SimpleGeometryParameter.hh.
References BooleanSolid_sol2, check_BooleanSolidId(), get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_sol2[i]=val;}
void SimpleGeometryParameter::set_BooleanSolid_sol2 (G4int BooleanSolidId, G4String val) [inline]
Definition at line 351 of file SimpleGeometryParameter.hh.
References BooleanSolid_sol2, and check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_sol2[BooleanSolidId]=val;}
void SimpleGeometryParameter::set_BooleanSolid_type (G4String name, G4String val) [inline]
Definition at line 359 of file SimpleGeometryParameter.hh.
References BooleanSolid_type, check_BooleanSolidId(), get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_type[i]=val;}
void SimpleGeometryParameter::set_BooleanSolid_type (G4int BooleanSolidId, G4String val) [inline]
Definition at line 349 of file SimpleGeometryParameter.hh.
References BooleanSolid_type, and check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_type[BooleanSolidId]=val;}
void SimpleGeometryParameter::set_Box_X (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 217 of file SimpleGeometryParameter.hh.
References Box_X, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Box_X[i][j] = val;}
void SimpleGeometryParameter::set_Box_X (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 213 of file SimpleGeometryParameter.hh.
References Box_X.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Box_X[i][j] = val;}
void SimpleGeometryParameter::set_Box_Y (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 218 of file SimpleGeometryParameter.hh.
References Box_Y, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Box_Y[i][j] = val;}
void SimpleGeometryParameter::set_Box_Y (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 214 of file SimpleGeometryParameter.hh.
References Box_Y.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Box_Y[i][j] = val;}
void SimpleGeometryParameter::set_Box_Z (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 219 of file SimpleGeometryParameter.hh.
References Box_Z, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Box_Z[i][j] = val;}
void SimpleGeometryParameter::set_Box_Z (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 215 of file SimpleGeometryParameter.hh.
References Box_Z.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Box_Z[i][j] = val;}
void MyVGeometryParameter::set_checkoverlap (bool val) [inline, inherited]
Definition at line 73 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::checkoverlap.
Referenced by MyVGeometryParameterMessenger::MySetNewValue().
{ checkoverlap = val;}
void SimpleGeometryParameter::set_Cons_Length (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 310 of file SimpleGeometryParameter.hh.
References Cons_Length, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_Length[i][j] = val;}
void SimpleGeometryParameter::set_Cons_Length (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 302 of file SimpleGeometryParameter.hh.
References Cons_Length.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_Length[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMax1 (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 306 of file SimpleGeometryParameter.hh.
References Cons_RMax1, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_RMax1[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMax1 (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 298 of file SimpleGeometryParameter.hh.
References Cons_RMax1.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_RMax1[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMax2 (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 308 of file SimpleGeometryParameter.hh.
References Cons_RMax2, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_RMax2[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMax2 (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 300 of file SimpleGeometryParameter.hh.
References Cons_RMax2.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_RMax2[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMin1 (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 307 of file SimpleGeometryParameter.hh.
References Cons_RMin1, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_RMin1[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMin1 (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 299 of file SimpleGeometryParameter.hh.
References Cons_RMin1.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_RMin1[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMin2 (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 309 of file SimpleGeometryParameter.hh.
References Cons_RMin2, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_RMin2[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMin2 (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 301 of file SimpleGeometryParameter.hh.
References Cons_RMin2.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_RMin2[i][j] = val;}
void SimpleGeometryParameter::set_Cons_SpanAng (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 312 of file SimpleGeometryParameter.hh.
References Cons_SpanAng, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Cons_SpanAng (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 304 of file SimpleGeometryParameter.hh.
References Cons_SpanAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Cons_StartAng (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 311 of file SimpleGeometryParameter.hh.
References Cons_StartAng, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_Cons_StartAng (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 303 of file SimpleGeometryParameter.hh.
References Cons_StartAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_X (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 226 of file SimpleGeometryParameter.hh.
References EllipticalTube_X, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); EllipticalTube_X[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_X (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 222 of file SimpleGeometryParameter.hh.
References EllipticalTube_X.
{ EllipticalTube_X[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_Y (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 227 of file SimpleGeometryParameter.hh.
References EllipticalTube_Y, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); EllipticalTube_Y[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_Y (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 223 of file SimpleGeometryParameter.hh.
References EllipticalTube_Y.
{ EllipticalTube_Y[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_Z (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 228 of file SimpleGeometryParameter.hh.
References EllipticalTube_Z, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); EllipticalTube_Z[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_Z (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 224 of file SimpleGeometryParameter.hh.
References EllipticalTube_Z.
{ EllipticalTube_Z[i][j] = val;}
void SimpleGeometryParameter::set_Ephi (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 208 of file SimpleGeometryParameter.hh.
References Ephi, and get_VolIndex().
{ int k = get_VolIndex(name); Ephi[k][j] = val;}
void SimpleGeometryParameter::set_Ephi (G4String type, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 193 of file SimpleGeometryParameter.hh.
References Ephi, and get_index().
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Ephi[k][j] = val;}
void SimpleGeometryParameter::set_Epsi (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 210 of file SimpleGeometryParameter.hh.
References Epsi, and get_VolIndex().
{ int k = get_VolIndex(name); Epsi[k][j] = val;}
void SimpleGeometryParameter::set_Epsi (G4String type, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 195 of file SimpleGeometryParameter.hh.
References Epsi, and get_index().
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Epsi[k][j] = val;}
void SimpleGeometryParameter::set_Etheta (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 209 of file SimpleGeometryParameter.hh.
References Etheta, and get_VolIndex().
{ int k = get_VolIndex(name); Etheta[k][j] = val;}
void SimpleGeometryParameter::set_Etheta (G4String type, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 194 of file SimpleGeometryParameter.hh.
References Etheta, and get_index().
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Etheta[k][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_numP (G4String name, G4int val, G4int j = 0) [inline]
Definition at line 340 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numP, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i)) ExtrudedSolid_numP[i] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_numP (G4int ExtrudedSolidId, G4int val, G4int j = 0) [inline]
Definition at line 331 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), and ExtrudedSolid_numP.
{if(check_ExtrudedSolidId(ExtrudedSolidId)) ExtrudedSolid_numP[ExtrudedSolidId] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_numZ (G4String name, G4int val, G4int j = 0) [inline]
Definition at line 339 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i)) ExtrudedSolid_numZ[i] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_numZ (G4int ExtrudedSolidId, G4int val, G4int j = 0) [inline]
Definition at line 330 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), and ExtrudedSolid_numZ.
{if(check_ExtrudedSolidId(ExtrudedSolidId)) ExtrudedSolid_numZ[ExtrudedSolidId] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Scale (G4String name, G4int iCone, G4double val, G4int j = 0) [inline]
Definition at line 346 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, ExtrudedSolid_Scale, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numZ[i]) ExtrudedSolid_Scale[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Scale (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 337 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, and ExtrudedSolid_Scale.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) ExtrudedSolid_Scale[ExtrudedSolidId][i][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_X (G4String name, G4int iCone, G4double val, G4int j = 0) [inline]
Definition at line 341 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numP, ExtrudedSolid_X, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numP[i]) ExtrudedSolid_X[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_X (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 332 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numP, and ExtrudedSolid_X.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numP[ExtrudedSolidId]) ExtrudedSolid_X[ExtrudedSolidId][i][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_X0 (G4String name, G4int iCone, G4double val, G4int j = 0) [inline]
Definition at line 344 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, ExtrudedSolid_X0, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numZ[i]) ExtrudedSolid_X0[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_X0 (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 335 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, and ExtrudedSolid_X0.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) ExtrudedSolid_X0[ExtrudedSolidId][i][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Y (G4String name, G4int iCone, G4double val, G4int j = 0) [inline]
Definition at line 342 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numP, ExtrudedSolid_Y, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numP[i]) ExtrudedSolid_Y[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Y (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 333 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numP, and ExtrudedSolid_Y.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numP[ExtrudedSolidId]) ExtrudedSolid_Y[ExtrudedSolidId][i][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Y0 (G4String name, G4int iCone, G4double val, G4int j = 0) [inline]
Definition at line 345 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, ExtrudedSolid_Y0, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numZ[i]) ExtrudedSolid_Y0[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Y0 (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 336 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, and ExtrudedSolid_Y0.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) ExtrudedSolid_Y0[ExtrudedSolidId][i][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Z (G4String name, G4int iCone, G4double val, G4int j = 0) [inline]
Definition at line 343 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, ExtrudedSolid_Z, get_SolidIndex(), and get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numZ[i]) ExtrudedSolid_Z[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Z (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 334 of file SimpleGeometryParameter.hh.
References check_ExtrudedSolidId(), ExtrudedSolid_numZ, and ExtrudedSolid_Z.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) ExtrudedSolid_Z[ExtrudedSolidId][i][j] = val;}
void MyVGeometryParameter::set_filename (G4String val) [inline, inherited]
Definition at line 77 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::m_filename.
Referenced by InitFromFile().
{ m_filename = val; }
void SimpleGeometryParameter::set_g (G4String name, G4double val) [inline]
Definition at line 384 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and vG.
{int k = get_VolIndex(name); vG[k] = val;}
void SimpleGeometryParameter::set_g (G4int i, G4double val) [inline]
Definition at line 378 of file SimpleGeometryParameter.hh.
References vG.
{ vG[i] = val;}
void SimpleGeometryParameter::set_g (G4String type, G4int i, G4double val) [inline]
Definition at line 372 of file SimpleGeometryParameter.hh.
References get_index(), and vG.
Referenced by GetValue(), and SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); vG[k] = val;}
void MyVGeometryParameter::set_GeometryParameterMessenger (MyVGeometryParameterMessenger * val) [inline, inherited]
Definition at line 75 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::m_GeometryParameterMessenger.
Referenced by SimpleGeometryParameter().
{m_GeometryParameterMessenger = val;};
void SimpleGeometryParameter::set_Hype_innerRadius (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 278 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Hype_innerRadius.
{int i = get_SolidIndex(get_VolIndex(name)); Hype_innerRadius[i][j] = val;}
void SimpleGeometryParameter::set_Hype_innerRadius (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 272 of file SimpleGeometryParameter.hh.
References Hype_innerRadius.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Hype_innerRadius[i][j] = val;}
void SimpleGeometryParameter::set_Hype_innerStereo (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 280 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Hype_innerStereo.
{int i = get_SolidIndex(get_VolIndex(name)); Hype_innerStereo[i][j] = val;}
void SimpleGeometryParameter::set_Hype_innerStereo (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 274 of file SimpleGeometryParameter.hh.
References Hype_innerStereo.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Hype_innerStereo[i][j] = val;}
void SimpleGeometryParameter::set_Hype_Length (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 282 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Hype_Length.
{int i = get_SolidIndex(get_VolIndex(name)); Hype_Length[i][j] = val;}
void SimpleGeometryParameter::set_Hype_Length (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 276 of file SimpleGeometryParameter.hh.
References Hype_Length.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Hype_Length[i][j] = val;}
void SimpleGeometryParameter::set_Hype_outerRadius (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 279 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Hype_outerRadius.
{int i = get_SolidIndex(get_VolIndex(name)); Hype_outerRadius[i][j] = val;}
void SimpleGeometryParameter::set_Hype_outerRadius (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 273 of file SimpleGeometryParameter.hh.
References Hype_outerRadius.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Hype_outerRadius[i][j] = val;}
void SimpleGeometryParameter::set_Hype_outerStereo (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 281 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Hype_outerStereo.
{int i = get_SolidIndex(get_VolIndex(name)); Hype_outerStereo[i][j] = val;}
void SimpleGeometryParameter::set_Hype_outerStereo (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 275 of file SimpleGeometryParameter.hh.
References Hype_outerStereo.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Hype_outerStereo[i][j] = val;}
void SimpleGeometryParameter::set_material (G4String name, G4String val) [inline]
Definition at line 201 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and Material.
{ int k = get_VolIndex(name); Material[k] = val;}
void SimpleGeometryParameter::set_material (G4String type, G4int i, G4String val) [inline]
Definition at line 190 of file SimpleGeometryParameter.hh.
References get_index(), and Material.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Material[k] = val;}
void SimpleGeometryParameter::set_MotherName (G4String name, G4String val) [inline]
Definition at line 200 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and MotherName.
{ int k = get_VolIndex(name); MotherName[k] = val;}
void SimpleGeometryParameter::set_MotherName (G4String type, G4int i, G4String val) [inline]
Definition at line 189 of file SimpleGeometryParameter.hh.
References get_index(), and MotherName.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); MotherName[k] = val;}
void MyVGeometryParameter::set_Name (G4String val) [inline, inherited]
Definition at line 76 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::m_Name.
Referenced by MyVGeometryParameter::MyVGeometryParameter().
{ m_Name = val; }
void SimpleGeometryParameter::set_name (G4String name, G4String val) [inline]
Definition at line 198 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and Name.
{ int k = get_VolIndex(name); Name[k] = val;}
void SimpleGeometryParameter::set_name (G4String type, G4int i, G4String val) [inline]
Definition at line 187 of file SimpleGeometryParameter.hh.
References get_index(), and Name.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Name[k] = val;}
void SimpleGeometryParameter::set_Polycone_numZ (G4String name, G4int val, G4int j = 0) [inline]
Definition at line 322 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), get_SolidIndex(), get_VolIndex(), and Polycone_numZ.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i)) Polycone_numZ[i] = val;}
void SimpleGeometryParameter::set_Polycone_numZ (G4int PolyconeId, G4int val, G4int j = 0) [inline]
Definition at line 315 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), and Polycone_numZ.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId)) Polycone_numZ[PolyconeId] = val;}
void SimpleGeometryParameter::set_Polycone_RMax (G4String name, G4int iCone, G4double val, G4int j = 0) [inline]
Definition at line 323 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), get_SolidIndex(), get_VolIndex(), Polycone_numZ, and Polycone_RMax.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i) && iCone < Polycone_numZ[i]) Polycone_RMax[i][iCone][j] = val;}
void SimpleGeometryParameter::set_Polycone_RMax (G4int PolyconeId, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 316 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), Polycone_numZ, and Polycone_RMax.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) Polycone_RMax[PolyconeId][i][j] = val;}
void SimpleGeometryParameter::set_Polycone_RMin (G4String name, G4int iCone, G4double val, G4int j = 0) [inline]
Definition at line 324 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), get_SolidIndex(), get_VolIndex(), Polycone_numZ, and Polycone_RMin.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i) && iCone < Polycone_numZ[i]) Polycone_RMin[i][iCone][j] = val;}
void SimpleGeometryParameter::set_Polycone_RMin (G4int PolyconeId, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 317 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), Polycone_numZ, and Polycone_RMin.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) Polycone_RMin[PolyconeId][i][j] = val;}
void SimpleGeometryParameter::set_Polycone_SpanAng (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 327 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), get_SolidIndex(), get_VolIndex(), and Polycone_SpanAng.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i)) Polycone_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Polycone_SpanAng (G4int PolyconeId, G4double val, G4int j = 0) [inline]
Definition at line 320 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), and Polycone_SpanAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId)) Polycone_SpanAng[PolyconeId][j] = val;}
void SimpleGeometryParameter::set_Polycone_StartAng (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 326 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), get_SolidIndex(), get_VolIndex(), and Polycone_StartAng.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i)) Polycone_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_Polycone_StartAng (G4int PolyconeId, G4double val, G4int j = 0) [inline]
Definition at line 319 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), and Polycone_StartAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId)) Polycone_StartAng[PolyconeId][j] = val;}
void SimpleGeometryParameter::set_Polycone_Z (G4String name, G4int iCone, G4double val, G4int j = 0) [inline]
Definition at line 325 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), get_SolidIndex(), get_VolIndex(), Polycone_numZ, and Polycone_Z.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i) && iCone < Polycone_numZ[i]) Polycone_Z[i][iCone][j] = val;}
void SimpleGeometryParameter::set_Polycone_Z (G4int PolyconeId, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 318 of file SimpleGeometryParameter.hh.
References check_PolyconeId(), Polycone_numZ, and Polycone_Z.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) Polycone_Z[PolyconeId][i][j] = val;}
void SimpleGeometryParameter::set_PosX (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 205 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and Pos.
{ int k = get_VolIndex(name); Pos[k][j].setX(val);}
void SimpleGeometryParameter::set_PosX (G4String type, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 184 of file SimpleGeometryParameter.hh.
References get_index(), and Pos.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Pos[k][j].setX(val);}
void SimpleGeometryParameter::set_PosY (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 206 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and Pos.
{ int k = get_VolIndex(name); Pos[k][j].setY(val);}
void SimpleGeometryParameter::set_PosY (G4String type, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 185 of file SimpleGeometryParameter.hh.
References get_index(), and Pos.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Pos[k][j].setY(val);}
void SimpleGeometryParameter::set_PosZ (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 207 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and Pos.
{ int k = get_VolIndex(name); Pos[k][j].setZ(val);}
void SimpleGeometryParameter::set_PosZ (G4String type, G4int i, G4double val, G4int j = 0) [inline]
Definition at line 186 of file SimpleGeometryParameter.hh.
References get_index(), and Pos.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Pos[k][j].setZ(val);}
void SimpleGeometryParameter::set_r (G4String name, G4double val) [inline]
Definition at line 383 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and vR.
{int k = get_VolIndex(name); vR[k] = val;}
void SimpleGeometryParameter::set_r (G4int i, G4double val) [inline]
Definition at line 377 of file SimpleGeometryParameter.hh.
References vR.
{ vR[i] = val;}
void SimpleGeometryParameter::set_r (G4String type, G4int i, G4double val) [inline]
Definition at line 371 of file SimpleGeometryParameter.hh.
References get_index(), and vR.
Referenced by GetValue(), and SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); vR[k] = val;}
void SimpleGeometryParameter::set_RepNo (G4String name, G4int val) [inline]
Definition at line 203 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and RepNo.
{ int k = get_VolIndex(name); RepNo[k] = val;}
void SimpleGeometryParameter::set_RepNo (G4String type, G4int i, G4int val) [inline]
Definition at line 192 of file SimpleGeometryParameter.hh.
References get_index(), and RepNo.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); RepNo[k] = val;}
void SimpleGeometryParameter::set_SDName (G4String name, G4String val) [inline]
Definition at line 199 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and SDName.
{ int k = get_VolIndex(name); SDName[k] = val;}
void SimpleGeometryParameter::set_SDName (G4String type, G4int i, G4String val) [inline]
Definition at line 188 of file SimpleGeometryParameter.hh.
References get_index(), and SDName.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); SDName[k] = val;}
void SimpleGeometryParameter::set_SolidBoolean (G4String name, G4int val) [inline]
Definition at line 204 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and SolidBoolean.
{ int k = get_VolIndex(name); SolidBoolean[k] = val;}
void SimpleGeometryParameter::set_SolidBoolean (G4String type, G4int i, G4int val) [inline]
Definition at line 196 of file SimpleGeometryParameter.hh.
References get_index(), and SolidBoolean.
{ int k = get_index(type, i); SolidBoolean[k] = val;}
void SimpleGeometryParameter::set_Sphere_RMax (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 264 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Sphere_RMax.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_RMax (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 257 of file SimpleGeometryParameter.hh.
References Sphere_RMax.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_RMin (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 265 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Sphere_RMin.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_RMin (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 258 of file SimpleGeometryParameter.hh.
References Sphere_RMin.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_SpanPhi (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 267 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Sphere_SpanPhi.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_SpanPhi[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_SpanPhi (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 260 of file SimpleGeometryParameter.hh.
References Sphere_SpanPhi.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_SpanPhi[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_SpanTheta (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 269 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Sphere_SpanTheta.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_SpanTheta[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_SpanTheta (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 262 of file SimpleGeometryParameter.hh.
References Sphere_SpanTheta.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_SpanTheta[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_StartPhi (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 266 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Sphere_StartPhi.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_StartPhi[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_StartPhi (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 259 of file SimpleGeometryParameter.hh.
References Sphere_StartPhi.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_StartPhi[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_StartTheta (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 268 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Sphere_StartTheta.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_StartTheta[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_StartTheta (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 261 of file SimpleGeometryParameter.hh.
References Sphere_StartTheta.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_StartTheta[i][j] = val;}
void SimpleGeometryParameter::set_SRepNo (G4String name, G4int val) [inline]
Definition at line 202 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and SRepNo.
{ int k = get_VolIndex(name); SRepNo[k] = val;}
void SimpleGeometryParameter::set_SRepNo (G4String type, G4int i, G4int val) [inline]
Definition at line 191 of file SimpleGeometryParameter.hh.
References get_index(), and SRepNo.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); SRepNo[k] = val;}
void SimpleGeometryParameter::set_t (G4String name, G4double val) [inline]
Definition at line 386 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and vT.
{int k = get_VolIndex(name); vT[k] = val;}
void SimpleGeometryParameter::set_t (G4int i, G4double val) [inline]
Definition at line 380 of file SimpleGeometryParameter.hh.
References vT.
{ vT[i] = val;}
void SimpleGeometryParameter::set_t (G4String type, G4int i, G4double val) [inline]
Definition at line 374 of file SimpleGeometryParameter.hh.
References get_index(), and vT.
Referenced by GetValue().
{ int k = get_index(type, i); vT[k] = val;}
void SimpleGeometryParameter::set_Torus_RMax (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 250 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Torus_RMax.
{int i = get_SolidIndex(get_VolIndex(name)); Torus_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Torus_RMax (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 244 of file SimpleGeometryParameter.hh.
References Torus_RMax.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Torus_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Torus_RMin (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 251 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Torus_RMin.
{int i = get_SolidIndex(get_VolIndex(name)); Torus_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Torus_RMin (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 245 of file SimpleGeometryParameter.hh.
References Torus_RMin.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Torus_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Torus_Rtor (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 252 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Torus_Rtor.
{int i = get_SolidIndex(get_VolIndex(name)); Torus_Rtor[i][j] = val;}
void SimpleGeometryParameter::set_Torus_Rtor (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 246 of file SimpleGeometryParameter.hh.
References Torus_Rtor.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Torus_Rtor[i][j] = val;}
void SimpleGeometryParameter::set_Torus_SpanAng (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 254 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Torus_SpanAng.
{int i = get_SolidIndex(get_VolIndex(name)); Torus_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Torus_SpanAng (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 248 of file SimpleGeometryParameter.hh.
References Torus_SpanAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Torus_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Torus_StartAng (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 253 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Torus_StartAng.
{int i = get_SolidIndex(get_VolIndex(name)); Torus_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_Torus_StartAng (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 247 of file SimpleGeometryParameter.hh.
References Torus_StartAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Torus_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_Length (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 239 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Tubs_Length.
{int i = get_SolidIndex(get_VolIndex(name)); Tubs_Length[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_Length (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 233 of file SimpleGeometryParameter.hh.
References Tubs_Length.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Tubs_Length[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_RMax (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 237 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Tubs_RMax.
{int i = get_SolidIndex(get_VolIndex(name)); Tubs_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_RMax (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 231 of file SimpleGeometryParameter.hh.
References Tubs_RMax.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Tubs_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_RMin (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 238 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Tubs_RMin.
{int i = get_SolidIndex(get_VolIndex(name)); Tubs_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_RMin (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 232 of file SimpleGeometryParameter.hh.
References Tubs_RMin.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Tubs_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_SpanAng (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 241 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Tubs_SpanAng.
{int i = get_SolidIndex(get_VolIndex(name)); Tubs_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_SpanAng (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 235 of file SimpleGeometryParameter.hh.
References Tubs_SpanAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Tubs_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_StartAng (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 240 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and Tubs_StartAng.
{int i = get_SolidIndex(get_VolIndex(name)); Tubs_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_StartAng (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 234 of file SimpleGeometryParameter.hh.
References Tubs_StartAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Tubs_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_dphi (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 295 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and TwistedTubs_dphi.
{int i = get_SolidIndex(get_VolIndex(name)); TwistedTubs_dphi[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_dphi (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 289 of file SimpleGeometryParameter.hh.
References TwistedTubs_dphi.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ TwistedTubs_dphi[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_endinnerrad (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 292 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and TwistedTubs_endinnerrad.
{int i = get_SolidIndex(get_VolIndex(name)); TwistedTubs_endinnerrad[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_endinnerrad (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 286 of file SimpleGeometryParameter.hh.
References TwistedTubs_endinnerrad.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ TwistedTubs_endinnerrad[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_endouterrad (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 293 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and TwistedTubs_endouterrad.
{int i = get_SolidIndex(get_VolIndex(name)); TwistedTubs_endouterrad[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_endouterrad (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 287 of file SimpleGeometryParameter.hh.
References TwistedTubs_endouterrad.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ TwistedTubs_endouterrad[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_Length (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 294 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and TwistedTubs_Length.
{int i = get_SolidIndex(get_VolIndex(name)); TwistedTubs_Length[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_Length (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 288 of file SimpleGeometryParameter.hh.
References TwistedTubs_Length.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ TwistedTubs_Length[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_twistedangle (G4String name, G4double val, G4int j = 0) [inline]
Definition at line 291 of file SimpleGeometryParameter.hh.
References get_SolidIndex(), get_VolIndex(), and TwistedTubs_twistedangle.
{int i = get_SolidIndex(get_VolIndex(name)); TwistedTubs_twistedangle[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_twistedangle (G4int i, G4double val, G4int j = 0) [inline]
Definition at line 285 of file SimpleGeometryParameter.hh.
References TwistedTubs_twistedangle.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ TwistedTubs_twistedangle[i][j] = val;}
void MyVGeometryParameter::set_VerboseLevel (int val) [inline, inherited]
Definition at line 74 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::fVerboseLevel.
Referenced by MyVGeometryParameterMessenger::MySetNewValue().
{ fVerboseLevel = val;}
void SimpleGeometryParameter::set_vis (G4String name, bool val) [inline]
Definition at line 382 of file SimpleGeometryParameter.hh.
References get_VolIndex(), and vVis.
{int k = get_VolIndex(name); vVis[k] = val;}
void SimpleGeometryParameter::set_vis (G4int i, bool val) [inline]
Definition at line 376 of file SimpleGeometryParameter.hh.
References vVis.
{ vVis[i] = val;}
void SimpleGeometryParameter::set_vis (G4String type, G4int i, bool val) [inline]
Definition at line 370 of file SimpleGeometryParameter.hh.
References get_index(), and vVis.
Referenced by GetValue(), and SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); vVis[k] = val;}
Member Data Documentation
G4int SimpleGeometryParameter::achieved_componets_Polycone [private]
Definition at line 721 of file SimpleGeometryParameter.hh.
Referenced by GetValue(), and Preset().
G4int SimpleGeometryParameter::achieved_P_ExtrudedSolid [private]
Definition at line 741 of file SimpleGeometryParameter.hh.
Referenced by GetValue(), and Preset().
G4int SimpleGeometryParameter::achieved_Z_ExtrudedSolid [private]
Definition at line 742 of file SimpleGeometryParameter.hh.
Referenced by GetValue(), and Preset().
std::vector<std::vector<G4double> > SimpleGeometryParameter::BooleanSolid_Ephi [private]
Definition at line 750 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_BooleanSolid_Ephi(), Preset(), and set_BooleanSolid_Ephi().
std::vector<std::vector<G4double> > SimpleGeometryParameter::BooleanSolid_Epsi [private]
Definition at line 752 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_BooleanSolid_Epsi(), Preset(), and set_BooleanSolid_Epsi().
std::vector<std::vector<G4double> > SimpleGeometryParameter::BooleanSolid_Etheta [private]
Definition at line 751 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_BooleanSolid_Etheta(), Preset(), and set_BooleanSolid_Etheta().
std::vector<G4int> SimpleGeometryParameter::BooleanSolid_GenIndex [private]
Definition at line 749 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_index(), GetValue(), and Preset().
std::vector<std::vector<G4ThreeVector> > SimpleGeometryParameter::BooleanSolid_Pos [private]
Definition at line 753 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_BooleanSolid_PosX(), get_BooleanSolid_PosY(), get_BooleanSolid_PosZ(), Preset(), set_BooleanSolid_PosX(), set_BooleanSolid_PosY(), and set_BooleanSolid_PosZ().
std::vector<G4String> SimpleGeometryParameter::BooleanSolid_PosType [private]
Definition at line 763 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::BooleanSolid_sol1 [private]
Definition at line 747 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_BooleanSolid_sol1(), GetValue(), Preset(), and set_BooleanSolid_sol1().
std::vector<G4String> SimpleGeometryParameter::BooleanSolid_sol2 [private]
Definition at line 748 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_BooleanSolid_sol2(), GetValue(), Preset(), and set_BooleanSolid_sol2().
std::vector<G4String> SimpleGeometryParameter::BooleanSolid_type [private]
Definition at line 746 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_BooleanSolid_type(), GetValue(), Preset(), and set_BooleanSolid_type().
G4int SimpleGeometryParameter::BooleanSolidNo [private]
Definition at line 745 of file SimpleGeometryParameter.hh.
Referenced by check_BooleanSolidId(), check_BooleanSolidNo(), DumpInfo(), GetValue(), and Preset().
std::vector<G4int> SimpleGeometryParameter::Box_GenIndex [private]
Definition at line 604 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_index(), GetValue(), and Preset().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Box_X [private]
Definition at line 598 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Box_X(), Preset(), and set_Box_X().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Box_Y [private]
Definition at line 599 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Box_Y(), Preset(), and set_Box_Y().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Box_Z [private]
Definition at line 600 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Box_Z(), Preset(), and set_Box_Z().
G4int SimpleGeometryParameter::BoxNo [private]
Definition at line 597 of file SimpleGeometryParameter.hh.
Referenced by check_BoxId(), check_BoxNo(), DumpInfo(), get_BoxNo(), GetValue(), and Preset().
std::vector<G4int> SimpleGeometryParameter::Cons_GenIndex [private]
Definition at line 704 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_index(), GetValue(), and Preset().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Cons_Length [private]
Definition at line 701 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Cons_Length(), Preset(), and set_Cons_Length().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Cons_RMax1 [private]
Definition at line 697 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Cons_RMax1(), Preset(), and set_Cons_RMax1().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Cons_RMax2 [private]
Definition at line 699 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Cons_RMax2(), Preset(), and set_Cons_RMax2().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Cons_RMin1 [private]
Definition at line 698 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Cons_RMin1(), Preset(), and set_Cons_RMin1().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Cons_RMin2 [private]
Definition at line 700 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Cons_RMin2(), Preset(), and set_Cons_RMin2().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Cons_SpanAng [private]
Definition at line 703 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Cons_SpanAng(), Preset(), and set_Cons_SpanAng().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Cons_StartAng [private]
Definition at line 702 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Cons_StartAng(), Preset(), and set_Cons_StartAng().
G4int SimpleGeometryParameter::ConsNo [private]
Definition at line 689 of file SimpleGeometryParameter.hh.
Referenced by check_ConsId(), check_ConsNo(), DumpInfo(), get_ConsNo(), GetValue(), and Preset().
std::vector<G4int> SimpleGeometryParameter::EllipticalTube_GenIndex [private]
Definition at line 614 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_index(), GetValue(), and Preset().
std::vector<std::vector<G4double> > SimpleGeometryParameter::EllipticalTube_X [private]
Definition at line 608 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_EllipticalTube_X(), Preset(), and set_EllipticalTube_X().
std::vector<std::vector<G4double> > SimpleGeometryParameter::EllipticalTube_Y [private]
Definition at line 609 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_EllipticalTube_Y(), Preset(), and set_EllipticalTube_Y().
std::vector<std::vector<G4double> > SimpleGeometryParameter::EllipticalTube_Z [private]
Definition at line 610 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_EllipticalTube_Z(), Preset(), and set_EllipticalTube_Z().
G4int SimpleGeometryParameter::EllipticalTubeNo [private]
Definition at line 607 of file SimpleGeometryParameter.hh.
Referenced by check_EllipticalTubeId(), DumpInfo(), get_EllipticalTubeNo(), GetValue(), and Preset().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Ephi [private]
Definition at line 588 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), dump_general_value(), get_Ephi(), Preset(), and set_Ephi().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Epsi [private]
Definition at line 590 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), dump_general_value(), get_Epsi(), Preset(), and set_Epsi().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Etheta [private]
Definition at line 589 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), dump_general_value(), get_Etheta(), Preset(), and set_Etheta().
std::vector<G4int> SimpleGeometryParameter::ExtrudedSolid_GenIndex [private]
Definition at line 739 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_index(), GetValue(), and Preset().
std::vector<G4int> SimpleGeometryParameter::ExtrudedSolid_numP [private]
Definition at line 726 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_ExtrudedSolid_numP(), get_ExtrudedSolid_X(), get_ExtrudedSolid_Y(), GetValue(), Preset(), set_ExtrudedSolid_numP(), set_ExtrudedSolid_X(), and set_ExtrudedSolid_Y().
std::vector<G4int> SimpleGeometryParameter::ExtrudedSolid_numZ [private]
Definition at line 725 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_ExtrudedSolid_numZ(), get_ExtrudedSolid_Scale(), get_ExtrudedSolid_X0(), get_ExtrudedSolid_Y0(), get_ExtrudedSolid_Z(), GetValue(), Preset(), set_ExtrudedSolid_numZ(), set_ExtrudedSolid_Scale(), set_ExtrudedSolid_X0(), set_ExtrudedSolid_Y0(), and set_ExtrudedSolid_Z().
std::vector<std::vector<std::vector<G4double> > > SimpleGeometryParameter::ExtrudedSolid_Scale [private]
Definition at line 738 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_ExtrudedSolid_Scale(), Preset(), and set_ExtrudedSolid_Scale().
std::vector<std::vector<std::vector<G4double> > > SimpleGeometryParameter::ExtrudedSolid_X [private]
Definition at line 733 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_ExtrudedSolid_X(), Preset(), and set_ExtrudedSolid_X().
std::vector<std::vector<std::vector<G4double> > > SimpleGeometryParameter::ExtrudedSolid_X0 [private]
Definition at line 736 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_ExtrudedSolid_X0(), Preset(), and set_ExtrudedSolid_X0().
std::vector<std::vector<std::vector<G4double> > > SimpleGeometryParameter::ExtrudedSolid_Y [private]
Definition at line 734 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_ExtrudedSolid_Y(), Preset(), and set_ExtrudedSolid_Y().
std::vector<std::vector<std::vector<G4double> > > SimpleGeometryParameter::ExtrudedSolid_Y0 [private]
Definition at line 737 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_ExtrudedSolid_Y0(), Preset(), and set_ExtrudedSolid_Y0().
std::vector<std::vector<std::vector<G4double> > > SimpleGeometryParameter::ExtrudedSolid_Z [private]
Definition at line 735 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_ExtrudedSolid_Z(), Preset(), and set_ExtrudedSolid_Z().
G4int SimpleGeometryParameter::ExtrudedSolidNo [private]
Definition at line 724 of file SimpleGeometryParameter.hh.
Referenced by check_ExtrudedSolidId(), check_ExtrudedSolidNo(), DumpInfo(), get_ExtrudedSolidNo(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBooleanSolid_Ephi [private]
Definition at line 754 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBooleanSolid_Epsi [private]
Definition at line 756 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBooleanSolid_Etheta [private]
Definition at line 755 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBooleanSolid_PosPhi [private]
Definition at line 761 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBooleanSolid_PosR [private]
Definition at line 762 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBooleanSolid_PosTheta [private]
Definition at line 760 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBooleanSolid_PosX [private]
Definition at line 757 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBooleanSolid_PosY [private]
Definition at line 758 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBooleanSolid_PosZ [private]
Definition at line 759 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBox_X [private]
Definition at line 601 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBox_Y [private]
Definition at line 602 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fBox_Z [private]
Definition at line 603 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fCons_Length [private]
Definition at line 694 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fCons_RMax1 [private]
Definition at line 690 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fCons_RMax2 [private]
Definition at line 692 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fCons_RMin1 [private]
Definition at line 691 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fCons_RMin2 [private]
Definition at line 693 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fCons_SpanAng [private]
Definition at line 696 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fCons_StartAng [private]
Definition at line 695 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fEllipticalTube_X [private]
Definition at line 611 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fEllipticalTube_Y [private]
Definition at line 612 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fEllipticalTube_Z [private]
Definition at line 613 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fEphi [private]
Definition at line 591 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fEpsi [private]
Definition at line 593 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fEtheta [private]
Definition at line 592 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<std::vector<G4String> > SimpleGeometryParameter::fExtrudedSolid_Scale [private]
Definition at line 732 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<std::vector<G4String> > SimpleGeometryParameter::fExtrudedSolid_X [private]
Definition at line 727 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<std::vector<G4String> > SimpleGeometryParameter::fExtrudedSolid_X0 [private]
Definition at line 730 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<std::vector<G4String> > SimpleGeometryParameter::fExtrudedSolid_Y [private]
Definition at line 728 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<std::vector<G4String> > SimpleGeometryParameter::fExtrudedSolid_Y0 [private]
Definition at line 731 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<std::vector<G4String> > SimpleGeometryParameter::fExtrudedSolid_Z [private]
Definition at line 729 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fHype_innerRadius [private]
Definition at line 662 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fHype_innerStereo [private]
Definition at line 664 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fHype_Length [private]
Definition at line 666 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fHype_outerRadius [private]
Definition at line 663 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fHype_outerStereo [private]
Definition at line 665 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<std::vector<G4String> > SimpleGeometryParameter::fPolycone_RMax [private]
Definition at line 709 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<std::vector<G4String> > SimpleGeometryParameter::fPolycone_RMin [private]
Definition at line 710 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fPolycone_SpanAng [private]
Definition at line 716 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fPolycone_StartAng [private]
Definition at line 715 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<std::vector<G4String> > SimpleGeometryParameter::fPolycone_Z [private]
Definition at line 711 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fPosPhi [private]
Definition at line 576 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fPosR [private]
Definition at line 575 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fPosTheta [private]
Definition at line 577 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fPosX [private]
Definition at line 572 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fPosY [private]
Definition at line 573 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fPosZ [private]
Definition at line 574 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fSphere_RMax [private]
Definition at line 646 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fSphere_RMin [private]
Definition at line 647 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fSphere_SpanPhi [private]
Definition at line 649 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fSphere_SpanTheta [private]
Definition at line 651 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fSphere_StartPhi [private]
Definition at line 648 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fSphere_StartTheta [private]
Definition at line 650 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTorus_RMax [private]
Definition at line 632 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTorus_RMin [private]
Definition at line 633 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTorus_Rtor [private]
Definition at line 634 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTorus_SpanAng [private]
Definition at line 636 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTorus_StartAng [private]
Definition at line 635 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTubs_Length [private]
Definition at line 625 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTubs_RMax [private]
Definition at line 623 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTubs_RMin [private]
Definition at line 624 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTubs_SpanAng [private]
Definition at line 627 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTubs_StartAng [private]
Definition at line 626 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTwistedTubs_dphi [private]
Definition at line 680 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTwistedTubs_endinnerrad [private]
Definition at line 677 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTwistedTubs_endouterrad [private]
Definition at line 678 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTwistedTubs_Length [private]
Definition at line 679 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::fTwistedTubs_twistedangle [private]
Definition at line 676 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), GetValue(), and Preset().
std::vector<G4int> SimpleGeometryParameter::Hype_GenIndex [private]
Definition at line 672 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_index(), GetValue(), and Preset().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Hype_innerRadius [private]
Definition at line 667 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Hype_innerRadius(), Preset(), and set_Hype_innerRadius().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Hype_innerStereo [private]
Definition at line 669 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Hype_innerStereo(), Preset(), and set_Hype_innerStereo().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Hype_Length [private]
Definition at line 671 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Hype_Length(), Preset(), and set_Hype_Length().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Hype_outerRadius [private]
Definition at line 668 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Hype_outerRadius(), Preset(), and set_Hype_outerRadius().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Hype_outerStereo [private]
Definition at line 670 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Hype_outerStereo(), Preset(), and set_Hype_outerStereo().
G4int SimpleGeometryParameter::HypeNo [private]
Definition at line 661 of file SimpleGeometryParameter.hh.
Referenced by check_HypeId(), check_HypeNo(), DumpInfo(), get_HypeNo(), GetValue(), and Preset().
std::vector< G4String > MyConfigure::knownValueNames [static, inherited]
Definition at line 24 of file MyConfigure.hh.
Referenced by MyConfigure::FindMacro(), GetValue(), and PrimaryGeneratorAction::ReadCard().
std::vector< G4String > MyConfigure::knownValues [static, inherited]
Definition at line 25 of file MyConfigure.hh.
Referenced by MyConfigure::FindMacro(), GetValue(), and PrimaryGeneratorAction::ReadCard().
std::vector<G4String> SimpleGeometryParameter::Material [private]
Definition at line 583 of file SimpleGeometryParameter.hh.
Referenced by dump_general_value(), get_material(), GetValue(), Preset(), and set_material().
std::vector<G4String> SimpleGeometryParameter::MotherName [private]
Definition at line 581 of file SimpleGeometryParameter.hh.
Referenced by dump_general_value(), get_MotherName(), GetValue(), Preset(), and set_MotherName().
std::vector<G4String> SimpleGeometryParameter::Name [private]
Definition at line 580 of file SimpleGeometryParameter.hh.
Referenced by dump_general_value(), get_name(), get_VolIndex(), GetValue(), Preset(), and set_name().
bool SimpleGeometryParameter::notReSetVis [private]
Definition at line 770 of file SimpleGeometryParameter.hh.
Referenced by GetValue(), Preset(), and ReSetVis().
std::vector<G4int> SimpleGeometryParameter::Polycone_GenIndex [private]
Definition at line 719 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_index(), GetValue(), and Preset().
std::vector<G4int> SimpleGeometryParameter::Polycone_numZ [private]
Definition at line 708 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Polycone_numZ(), get_Polycone_RMax(), get_Polycone_RMin(), get_Polycone_Z(), GetValue(), Preset(), set_Polycone_numZ(), set_Polycone_RMax(), set_Polycone_RMin(), and set_Polycone_Z().
std::vector<std::vector<std::vector<G4double> > > SimpleGeometryParameter::Polycone_RMax [private]
Definition at line 712 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Polycone_RMax(), Preset(), and set_Polycone_RMax().
std::vector<std::vector<std::vector<G4double> > > SimpleGeometryParameter::Polycone_RMin [private]
Definition at line 713 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Polycone_RMin(), Preset(), and set_Polycone_RMin().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Polycone_SpanAng [private]
Definition at line 718 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Polycone_SpanAng(), Preset(), and set_Polycone_SpanAng().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Polycone_StartAng [private]
Definition at line 717 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Polycone_StartAng(), Preset(), and set_Polycone_StartAng().
std::vector<std::vector<std::vector<G4double> > > SimpleGeometryParameter::Polycone_Z [private]
Definition at line 714 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Polycone_Z(), Preset(), and set_Polycone_Z().
G4int SimpleGeometryParameter::PolyconeNo [private]
Definition at line 707 of file SimpleGeometryParameter.hh.
Referenced by check_PolyconeId(), check_PolyconeNo(), DumpInfo(), get_PolyconeNo(), GetValue(), and Preset().
std::vector<std::vector<G4ThreeVector> > SimpleGeometryParameter::Pos [private]
Definition at line 579 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), dump_general_value(), get_PosX(), get_PosY(), get_PosZ(), Preset(), set_PosX(), set_PosY(), and set_PosZ().
std::vector<G4String> SimpleGeometryParameter::PosType [private]
Definition at line 578 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), dump_general_value(), GetValue(), and Preset().
std::vector<G4int> SimpleGeometryParameter::RepNo [private]
Definition at line 585 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), dump_general_value(), DumpInfo(), get_RepNo(), GetValue(), Preset(), and set_RepNo().
std::vector<G4String> SimpleGeometryParameter::SDName [private]
Definition at line 582 of file SimpleGeometryParameter.hh.
Referenced by dump_general_value(), get_SDName(), GetValue(), Preset(), and set_SDName().
std::vector<G4bool> SimpleGeometryParameter::SolidBoolean [private]
Definition at line 594 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), dump_general_value(), get_SolidBoolean(), GetValue(), Preset(), and set_SolidBoolean().
std::vector<G4int> SimpleGeometryParameter::SolidIndex [private]
Definition at line 587 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), get_SolidIndex(), GetValue(), and Preset().
std::vector<G4String> SimpleGeometryParameter::SolidType [private]
Definition at line 586 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), get_SolidType(), GetValue(), and Preset().
std::vector<G4int> SimpleGeometryParameter::Sphere_GenIndex [private]
Definition at line 658 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_index(), GetValue(), and Preset().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Sphere_RMax [private]
Definition at line 652 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Sphere_RMax(), Preset(), and set_Sphere_RMax().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Sphere_RMin [private]
Definition at line 653 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Sphere_RMin(), Preset(), and set_Sphere_RMin().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Sphere_SpanPhi [private]
Definition at line 655 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Sphere_SpanPhi(), Preset(), and set_Sphere_SpanPhi().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Sphere_SpanTheta [private]
Definition at line 657 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Sphere_SpanTheta(), Preset(), and set_Sphere_SpanTheta().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Sphere_StartPhi [private]
Definition at line 654 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Sphere_StartPhi(), Preset(), and set_Sphere_StartPhi().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Sphere_StartTheta [private]
Definition at line 656 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Sphere_StartTheta(), Preset(), and set_Sphere_StartTheta().
G4int SimpleGeometryParameter::SphereNo [private]
Definition at line 645 of file SimpleGeometryParameter.hh.
Referenced by check_SphereId(), check_SphereNo(), DumpInfo(), get_SphereNo(), GetValue(), and Preset().
std::vector<G4int> SimpleGeometryParameter::SRepNo [private]
Definition at line 584 of file SimpleGeometryParameter.hh.
Referenced by get_SRepNo(), GetValue(), Preset(), and set_SRepNo().
std::vector<G4int> SimpleGeometryParameter::Torus_GenIndex [private]
Definition at line 642 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_index(), GetValue(), and Preset().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Torus_RMax [private]
Definition at line 637 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Torus_RMax(), Preset(), and set_Torus_RMax().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Torus_RMin [private]
Definition at line 638 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Torus_RMin(), Preset(), and set_Torus_RMin().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Torus_Rtor [private]
Definition at line 639 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Torus_Rtor(), Preset(), and set_Torus_Rtor().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Torus_SpanAng [private]
Definition at line 641 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Torus_SpanAng(), Preset(), and set_Torus_SpanAng().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Torus_StartAng [private]
Definition at line 640 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Torus_StartAng(), Preset(), and set_Torus_StartAng().
G4int SimpleGeometryParameter::TorusNo [private]
Definition at line 631 of file SimpleGeometryParameter.hh.
Referenced by check_TorusId(), check_TorusNo(), DumpInfo(), get_TorusNo(), GetValue(), and Preset().
std::vector<G4int> SimpleGeometryParameter::Tubs_GenIndex [private]
Definition at line 628 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_index(), GetValue(), and Preset().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Tubs_Length [private]
Definition at line 620 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Tubs_Length(), Preset(), and set_Tubs_Length().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Tubs_RMax [private]
Definition at line 618 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Tubs_RMax(), Preset(), and set_Tubs_RMax().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Tubs_RMin [private]
Definition at line 619 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Tubs_RMin(), Preset(), and set_Tubs_RMin().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Tubs_SpanAng [private]
Definition at line 622 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Tubs_SpanAng(), Preset(), and set_Tubs_SpanAng().
std::vector<std::vector<G4double> > SimpleGeometryParameter::Tubs_StartAng [private]
Definition at line 621 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Tubs_StartAng(), Preset(), and set_Tubs_StartAng().
G4int SimpleGeometryParameter::TubsNo [private]
Definition at line 617 of file SimpleGeometryParameter.hh.
Referenced by check_TubsId(), check_TubsNo(), DumpInfo(), get_TubsNo(), GetValue(), and Preset().
std::vector<std::vector<G4double> > SimpleGeometryParameter::TwistedTubs_dphi [private]
Definition at line 685 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_TwistedTubs_dphi(), Preset(), and set_TwistedTubs_dphi().
std::vector<std::vector<G4double> > SimpleGeometryParameter::TwistedTubs_endinnerrad [private]
Definition at line 682 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_TwistedTubs_endinnerrad(), Preset(), and set_TwistedTubs_endinnerrad().
std::vector<std::vector<G4double> > SimpleGeometryParameter::TwistedTubs_endouterrad [private]
Definition at line 683 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_TwistedTubs_endouterrad(), Preset(), and set_TwistedTubs_endouterrad().
std::vector<G4int> SimpleGeometryParameter::TwistedTubs_GenIndex [private]
Definition at line 686 of file SimpleGeometryParameter.hh.
Referenced by DumpInfo(), get_index(), GetValue(), and Preset().
std::vector<std::vector<G4double> > SimpleGeometryParameter::TwistedTubs_Length [private]
Definition at line 684 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_TwistedTubs_Length(), Preset(), and set_TwistedTubs_Length().
std::vector<std::vector<G4double> > SimpleGeometryParameter::TwistedTubs_twistedangle [private]
Definition at line 681 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_TwistedTubs_twistedangle(), Preset(), and set_TwistedTubs_twistedangle().
G4int SimpleGeometryParameter::TwistedTubsNo [private]
Definition at line 675 of file SimpleGeometryParameter.hh.
Referenced by check_TwistedTubsId(), check_TwistedTubsNo(), DumpInfo(), get_TwistedTubsNo(), GetValue(), and Preset().
std::vector<G4double> SimpleGeometryParameter::vB [private]
Definition at line 767 of file SimpleGeometryParameter.hh.
Referenced by get_b(), ReSetVis(), and set_b().
std::vector<G4double> SimpleGeometryParameter::vG [private]
Definition at line 767 of file SimpleGeometryParameter.hh.
Referenced by get_g(), ReSetVis(), and set_g().
G4int SimpleGeometryParameter::VolNo [private]
Definition at line 571 of file SimpleGeometryParameter.hh.
Referenced by Calculate(), check_VolId(), get_VolIndex(), get_VolNo(), GetValue(), Preset(), and ReSetVis().
std::vector<G4double> SimpleGeometryParameter::vR [private]
Definition at line 767 of file SimpleGeometryParameter.hh.
Referenced by get_r(), ReSetVis(), and set_r().
std::vector<G4double> SimpleGeometryParameter::vT [private]
Definition at line 767 of file SimpleGeometryParameter.hh.
Referenced by get_t(), ReSetVis(), and set_t().
std::vector<bool> SimpleGeometryParameter::vVis [private]
Definition at line 766 of file SimpleGeometryParameter.hh.
Referenced by get_vis(), ReSetVis(), and set_vis().
G4int SimpleGeometryParameter::waited_ExtrudedSolid_iVol [private]
Definition at line 740 of file SimpleGeometryParameter.hh.
Referenced by GetValue(), and Preset().
G4int SimpleGeometryParameter::waited_Polycone_iVol [private]
Definition at line 720 of file SimpleGeometryParameter.hh.
Referenced by GetValue(), and Preset().
The documentation for this class was generated from the following files:
include/SimpleGeometryParameter.hh
src/SimpleGeometryParameter.cc