g4sim: MyTrackingAction Class Reference
MyTrackingAction Class Reference
#include <MyTrackingAction.hh>
Public Member Functions
MyTrackingAction ()
~MyTrackingAction ()
void PreUserTrackingAction (const G4Track *)
void PostUserTrackingAction (const G4Track *)
Detailed Description
Definition at line 39 of file MyTrackingAction.hh.
Constructor & Destructor Documentation
MyTrackingAction::MyTrackingAction ()
Definition at line 42 of file MyTrackingAction.cc.
{ }
MyTrackingAction::~MyTrackingAction () [inline]
Definition at line 44 of file MyTrackingAction.hh.
{};
Member Function Documentation
void MyTrackingAction::PostUserTrackingAction (const G4Track * aTrack)
Definition at line 73 of file MyTrackingAction.cc.
References MyAnalysisSvc::GetMyAnalysisSvc(), and MyAnalysisSvc::PostUserTrackingAction().
{
        MyAnalysisSvc::GetMyAnalysisSvc()->PostUserTrackingAction(aTrack);
//  G4int trackID= aTrack->GetTrackID(); //G4 track ID of current track.
//      G4int   nbSteps = aTrack->GetCurrentStepNumber();
//      G4double trackLength = aTrack->GetTrackLength();
//      std::cout<<"End of track "<<trackID<<std::endl;
//      std::cout<<"    number of steps: "<<nbSteps<<std::endl;
//      std::cout<<"    track length: "<<trackLength/mm<<"mm"<<std::endl;
}
void MyTrackingAction::PreUserTrackingAction (const G4Track * aTrack)
Definition at line 45 of file MyTrackingAction.cc.
References MyAnalysisSvc::GetMyAnalysisSvc(), and MyAnalysisSvc::PreUserTrackingAction().
{
        MyAnalysisSvc::GetMyAnalysisSvc()->PreUserTrackingAction(aTrack);
//      G4String processName;
//      const G4VProcess* process = aTrack->GetCreatorProcess();
//      if (process) {
//              processName = process->GetProcessName();
//      }
//      else{
//              processName = "NULL";
//      }
//  G4int trackID= aTrack->GetTrackID(); //G4 track ID of current track.
//  G4int ptid = aTrack->GetParentID(); //parent G4 track ID of current track.
//      G4int pid = aTrack->GetParticleDefinition()->GetPDGEncoding();
//  G4double globalT=aTrack->GetGlobalTime();//Time since the event in which the track belongs is created
//      G4ThreeVector mom_3vec = aTrack->GetMomentum();
//      G4double mom = mom_3vec.mag();
//
//      std::cout<<"Begin of track "<<trackID<<std::endl;
//      std::cout<<"    pid: "<<pid<<std::endl;
//      std::cout<<"    ptid: "<<ptid<<std::endl;
//      std::cout<<"    process: "<<processName<<std::endl;
//      std::cout<<"    Global time: "<<globalT/ns<<"ns"<<std::endl;
//      std::cout<<"    momentum: "<<mom/MeV<<"MeV"<<std::endl;
}
The documentation for this class was generated from the following files:
include/MyTrackingAction.hh
src/MyTrackingAction.cc