g4sim: DetectorConstruction Class Reference
DetectorConstruction Class Reference
#include <DetectorConstruction.hh>
Public Member Functions
DetectorConstruction ()
~DetectorConstruction ()
G4VPhysicalVolume * Construct ()
void ResetMag (G4String)
void ReloadGeo (G4String)
void UpdateGeometry ()
Private Member Functions
G4VPhysicalVolume * ConstructDetector ()
Private Attributes
DetectorMessenger * detectorMessenger
G4VPhysicalVolume * world_pvol
MyFieldSvc * pMyFieldSvc
MyDetectorManager * pMyDetectorManager
Detailed Description
Definition at line 20 of file DetectorConstruction.hh.
Constructor & Destructor Documentation
DetectorConstruction::DetectorConstruction ()
Definition at line 23 of file DetectorConstruction.cc.
References detectorMessenger, MyDetectorManager::GetMyDetectorManager(), MyFieldSvc::GetMyFieldSvc(), pMyDetectorManager, and pMyFieldSvc.
{
  detectorMessenger = new DetectorMessenger(this);
        pMyFieldSvc = MyFieldSvc::GetMyFieldSvc();
        pMyDetectorManager = MyDetectorManager::GetMyDetectorManager();
}
DetectorConstruction::~DetectorConstruction ()
Definition at line 29 of file DetectorConstruction.cc.
References detectorMessenger.
{
  delete detectorMessenger;
}
Member Function Documentation
G4VPhysicalVolume * DetectorConstruction::Construct ()
Definition at line 33 of file DetectorConstruction.cc.
References ConstructDetector(), MaterialSvc::GetMaterialSvc(), pMyDetectorManager, pMyFieldSvc, MyDetectorManager::ReadCard(), MyFieldSvc::ReadCard(), and MaterialSvc::SetMaterial().
{
        G4String CardName;
        //=>Material
        CardName = getenv("MATERIALLISTROOT");
        MaterialSvc* materialSvc = MaterialSvc::GetMaterialSvc();
        materialSvc->SetMaterial(CardName);
        //=>MagField
        CardName = getenv("MAGFIELDCARDROOT");
        pMyFieldSvc->ReadCard( CardName );
        //=>Geometry
        CardName = getenv("GEOCARDROOT");
        pMyDetectorManager->ReadCard( CardName );
        //=>ConstructDetector
  return ConstructDetector();
}
G4VPhysicalVolume * DetectorConstruction::ConstructDetector () [private]
Definition at line 53 of file DetectorConstruction.cc.
References pMyDetectorManager, pMyFieldSvc, MyFieldSvc::SetField(), MyDetectorManager::SetGeometry(), and world_pvol.
Referenced by Construct(), and UpdateGeometry().
{
        // Clean old geometry, if any
        G4GeometryManager::GetInstance()->OpenGeometry();
        G4PhysicalVolumeStore::GetInstance()->Clean();
        G4LogicalVolumeStore::GetInstance()->Clean();
        G4SolidStore::GetInstance()->Clean();
        // Geometry
        world_pvol = pMyDetectorManager->SetGeometry();
        //MagField
        G4LogicalVolume* world_lvol = world_pvol->GetLogicalVolume();
        pMyFieldSvc->SetField(world_lvol);
        // reset userlimit
        world_pvol->GetLogicalVolume()->SetUserLimits(new G4UserLimits());
        //always return the physical world
        return world_pvol;
}
void DetectorConstruction::ReloadGeo (G4String file_name)
Definition at line 77 of file DetectorConstruction.cc.
References MyDetectorManager::ClearGeo(), pMyDetectorManager, MyDetectorManager::ReadCard(), and UpdateGeometry().
Referenced by DetectorMessenger::SetNewValue().
{
        pMyDetectorManager->ClearGeo();
        pMyDetectorManager->ReadCard(file_name);
        UpdateGeometry();
}
void DetectorConstruction::ResetMag (G4String file_name)
Definition at line 83 of file DetectorConstruction.cc.
References pMyFieldSvc, MyFieldSvc::ReadCard(), MyFieldSvc::SetField(), and world_pvol.
Referenced by DetectorMessenger::SetNewValue().
{
        pMyFieldSvc->ReadCard(file_name);
        pMyFieldSvc->SetField(world_pvol->GetLogicalVolume());
}
void DetectorConstruction::UpdateGeometry ()
Definition at line 88 of file DetectorConstruction.cc.
References ConstructDetector().
Referenced by ReloadGeo(), and DetectorMessenger::SetNewValue().
{
        G4RunManager::GetRunManager()->DefineWorldVolume(ConstructDetector());
}
Member Data Documentation
DetectorMessenger* DetectorConstruction::detectorMessenger [private]
Definition at line 41 of file DetectorConstruction.hh.
Referenced by DetectorConstruction(), and ~DetectorConstruction().
MyDetectorManager* DetectorConstruction::pMyDetectorManager [private]
Definition at line 45 of file DetectorConstruction.hh.
Referenced by Construct(), ConstructDetector(), DetectorConstruction(), and ReloadGeo().
MyFieldSvc* DetectorConstruction::pMyFieldSvc [private]
Definition at line 44 of file DetectorConstruction.hh.
Referenced by Construct(), ConstructDetector(), DetectorConstruction(), and ResetMag().
G4VPhysicalVolume* DetectorConstruction::world_pvol [private]
Definition at line 43 of file DetectorConstruction.hh.
Referenced by ConstructDetector(), and ResetMag().
The documentation for this class was generated from the following files:
include/DetectorConstruction.hh
src/DetectorConstruction.cc