g4sim: TimeImpl Class Reference
TimeImpl Class Reference
Public Member Functions
TimeImpl (int n, G4double t[], G4double b[], G4double e[]=0)
void setPeriod (G4double v)
G4double factorB (G4double t)
G4double factorE (G4double t)
Static Public Member Functions
static TimeImpl * readTime (InputFile &in, MyBLArgumentVector argv, MyBLArgumentMap namedArgs)
Private Attributes
BTSpline1D B
BTSpline1D E
G4double tMin
G4double tMax
G4double period
Detailed Description
class TimeImpl -- class implementation of a time dependence.
Definition at line 177 of file MyBLFieldMap.cc.
Constructor & Destructor Documentation
TimeImpl::TimeImpl (int n, G4double t[], G4double b[], G4double e[] = 0) [inline]
Constructor. n is # points in the arrays, t[] is the list of time values (ns), b[] and e[] are the factors for B field and E field. t[], b[], and e[] are copied so the caller can delete them after calling this routine.
Definition at line 189 of file MyBLFieldMap.cc.
References period, tMax, and tMin.
Referenced by readTime().
                                                                    :
        B(n,t,b), E(n,t,(e?e:b)) {
            tMin = t[0];
            tMax = t[n-1];
            period = -1.0;
        }
        void setPeriod(G4double v) { period = v; }
Member Function Documentation
G4double TimeImpl::factorB (G4double t) [inline]
Definition at line 196 of file MyBLFieldMap.cc.
References B, period, tMax, and tMin.
Referenced by MyBLFieldMap::getFieldValue(), and MyBLFieldMap::getTimeFactor().
{
            if(period > 0.0) {
                t -= floor(t/period)*period;
            }
            else {
                if(t < tMin) t = tMin;
                if(t > tMax) t = tMax;
            }
            return B(t);
        }
G4double TimeImpl::factorE (G4double t) [inline]
Definition at line 206 of file MyBLFieldMap.cc.
References E, period, tMax, and tMin.
Referenced by MyBLFieldMap::getFieldValue(), and MyBLFieldMap::getTimeFactor().
{
            if(period > 0.0) {
                t -= floor(t/period)*period;
            }
            else {
                if(t < tMin) t = tMin;
                if(t > tMax) t = tMax;
            }
            return E(t);
        }
TimeImpl * TimeImpl::readTime (InputFile & in, MyBLArgumentVector argv, MyBLArgumentMap namedArgs) [static]
Definition at line 379 of file MyBLFieldMap.cc.
References argDouble(), B, E, InputFile::getline(), period, InputFile::repeatLine(), setPeriod(), and TimeImpl().
Referenced by MyBLFieldMap::readFile().
{
    G4double period=-1.0;
    argDouble(period,"period",namedArgs);
    std::vector<G4double> T;
    std::vector<G4double> B;
    std::vector<G4double> E;
    char *line;
    while((line=in.getline()) != 0) {
        if(isalpha(line[0])) {
            in.repeatLine();
            break;
        }
        G4double t,b,e;
        int j = sscanf(line,"%lf%lf%lf",&t,&b,&e);
        if(j < 2 || j > 3) return 0;
        if(j == 2) e = b;
        T.push_back(t);
        B.push_back(b);
        E.push_back(e);
    }
    if(T.size() > 0) {
        TimeImpl *impl =
            new TimeImpl(T.size(),&T[0],&B[0],&E[0]);
        impl->setPeriod(period);
        return impl;
    }
    return 0;
}
void TimeImpl::setPeriod (G4double v) [inline]
Definition at line 195 of file MyBLFieldMap.cc.
References period.
Referenced by MyBLFieldMap::createTimeDependence(), and readTime().
{ period = v; }
Member Data Documentation
BTSpline1D TimeImpl::B [private]
Definition at line 178 of file MyBLFieldMap.cc.
Referenced by factorB(), and readTime().
BTSpline1D TimeImpl::E [private]
Definition at line 179 of file MyBLFieldMap.cc.
Referenced by factorE(), and readTime().
G4double TimeImpl::period [private]
Definition at line 182 of file MyBLFieldMap.cc.
Referenced by factorB(), factorE(), readTime(), setPeriod(), and TimeImpl().
G4double TimeImpl::tMax [private]
Definition at line 181 of file MyBLFieldMap.cc.
Referenced by factorB(), factorE(), and TimeImpl().
G4double TimeImpl::tMin [private]
Definition at line 180 of file MyBLFieldMap.cc.
Referenced by factorB(), factorE(), and TimeImpl().
The documentation for this class was generated from the following file:
src/MyBLFieldMap.cc