g4sim: MyVGeometryParameter Class Reference
MyVGeometryParameter Class Reference
#include <MyVGeometryParameter.hh>
Public Member Functions
MyVGeometryParameter (G4String name, G4String opt="")
virtual ~MyVGeometryParameter (void)
virtual void InitFromFile (G4String)
virtual void Calculate ()
virtual void Dump ()
int GetValue (G4String)
void Preset ()
bool CheckInfo ()
void DumpInfo ()
void get_RepCont (G4String RepCont, G4int &SRepNo, G4int &RepNo)
bool ISEMPTY (G4String)
void DEBUG (G4String content, int level=1)
bool get_checkoverlap ()
int get_VerboseLevel ()
G4String get_Name ()
G4String get_filename ()
void set_checkoverlap (bool val)
void set_VerboseLevel (int val)
void set_GeometryParameterMessenger (MyVGeometryParameterMessenger *val)
void set_Name (G4String val)
void set_filename (G4String val)
std::vector< G4String > GetWords (G4String formula)
bool FindMacro (G4String word, G4String &value)
void Replace (G4String &formula, G4String word, G4String value)
double CalFormula (G4String formula, int iRep=0)
G4String ReplaceMacro (G4String formula)
Static Public Attributes
static std::vector< G4String > knownValueNames
static std::vector< G4String > knownValues
Private Attributes
bool checkoverlap
int fVerboseLevel
G4String m_filename
G4String m_Name
MyVGeometryParameterMessenger * m_GeometryParameterMessenger
Detailed Description
Definition at line 24 of file MyVGeometryParameter.hh.
Constructor & Destructor Documentation
MyVGeometryParameter::MyVGeometryParameter (G4String name, G4String opt = "")
Definition at line 22 of file MyVGeometryParameter.cc.
References set_Name().
        : MyConfigure()
{
        if ( opt == "" ){
                std::cout<<"MyVGeometryParameter is a virtual class, should be called with opt not empty!"<<std::endl;
    G4Exception("MyVGeometryParameter::MyVGeometryParameter()","Run0031",
        FatalException, "illegal construction.");
        }
        set_Name(name);
}
MyVGeometryParameter::~MyVGeometryParameter (void) [virtual]
Definition at line 33 of file MyVGeometryParameter.cc.
References m_GeometryParameterMessenger.
{
        std::cout<<"======>In ~MyVGeometryParameter, delete GeometryParameterMessenger at ("<<(void*)m_GeometryParameterMessenger<<")!"<<std::endl;
  delete m_GeometryParameterMessenger;
}
Member Function Documentation
virtual void MyVGeometryParameter::Calculate () [inline, virtual]
Reimplemented in SimpleGeometryParameter.
Definition at line 33 of file MyVGeometryParameter.hh.
{};
double MyConfigure::CalFormula (G4String formula, int iRep = 0) [inherited]
Definition at line 23 of file MyConfigure.cc.
Referenced by SimpleGeometryParameter::Calculate(), and PrimaryGeneratorAction::ReadCard().
{
//      std::cout<<"TO Calculate for: \""<<formula<<"\" "<<iRep<<std::endl; // to be deleted
//      formula = ReplaceMacro(formula);
        TF1 *f1 = new TF1("f1", formula);
        double value = f1->Eval(iRep);
//      std::cout<<"\t=>"<<value<<std::endl;
        delete f1;
        return value;
}
bool MyVGeometryParameter::CheckInfo ()
Reimplemented in SimpleGeometryParameter.
Definition at line 39 of file MyVGeometryParameter.cc.
{
        bool flag = false;// false means no problem
        //examine
        return flag;
}
void MyVGeometryParameter::DEBUG (G4String content, int level = 1) [inline]
Definition at line 54 of file MyVGeometryParameter.hh.
Referenced by SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::InitFromFile().
{
                        if (level >= 1){
                                G4Exception("MyVGeometryParameter","Run0031",
                                                FatalException, content);
                        }
                        else if (level == 0){
                                std::cout<<"In MyVGeometryParameter, "<<content<<std::endl;
                        }
                }
virtual void MyVGeometryParameter::Dump () [inline, virtual]
Reimplemented in SimpleGeometryParameter.
Definition at line 35 of file MyVGeometryParameter.hh.
{};
void MyVGeometryParameter::DumpInfo (void)
Reimplemented in SimpleGeometryParameter.
Definition at line 71 of file MyVGeometryParameter.cc.
References checkoverlap, fVerboseLevel, m_filename, and m_Name.
{
        std::cout<<"*********************************"<<m_Name<<" Geometry Info***********************************"<<std::endl;
        std::cout<<"------General info:--------"<<std::endl;
        std::cout<<" Initialized from \""<<m_filename<<"\""<<std::endl;
        std::cout<<" checkoverlap? "<<(checkoverlap?"yes":"no")<<std::endl;
        std::cout<<" VerboseLevel = "<<fVerboseLevel<<std::endl;
}
bool MyConfigure::FindMacro (G4String word, G4String & value) [inherited]
Definition at line 87 of file MyConfigure.cc.
References MyConfigure::knownValueNames, and MyConfigure::knownValues.
Referenced by MyConfigure::Replace(), and MyConfigure::ReplaceMacro().
{
        bool found = false;
        for (int i = 0; i< knownValues.size(); i++){
                if (knownValueNames[i]==word){
                        value = knownValues[i];
                        found = true;
                        break;
                }
        }
        return found;
}
bool MyVGeometryParameter::get_checkoverlap () [inline]
Definition at line 66 of file MyVGeometryParameter.hh.
References checkoverlap.
Referenced by SimpleGeometrySvc::PlaceVolumes().
{return checkoverlap;}
G4String MyVGeometryParameter::get_filename () [inline]
Definition at line 69 of file MyVGeometryParameter.hh.
References m_filename.
{ return m_filename; }
G4String MyVGeometryParameter::get_Name () [inline]
Definition at line 68 of file MyVGeometryParameter.hh.
References m_Name.
{ return m_Name; }
void MyVGeometryParameter::get_RepCont (G4String RepCont, G4int & SRepNo, G4int & RepNo)
Definition at line 84 of file MyVGeometryParameter.cc.
References MyString2Anything::get_I().
Referenced by SimpleGeometryParameter::GetValue().
{
        size_t sLast = RepCont.last(',');
        if(sLast!=G4String::npos){
                G4String part1 = RepCont.substr(0,sLast);
                G4String part2 = RepCont.substr(sLast+1,RepCont.length()-sLast-1);
                MyString2Anything::get_I(part1,SRepNo);
                MyString2Anything::get_I(part2,RepNo);
        }
        else{ // not found
                sLast = RepCont.last('-');
                if (sLast==G4String::npos){// not found
                        sLast = RepCont.last('~');
                }
                if (sLast!=G4String::npos){
                        G4String part1 = RepCont.substr(0,sLast);
                        G4String part2 = RepCont.substr(sLast+1,RepCont.length()-sLast-1);
                        MyString2Anything::get_I(part1,SRepNo);
                        G4int endNo;
                        MyString2Anything::get_I(part2,endNo);
                        RepNo = endNo - SRepNo + 1;
                }
                else{// not found
                        SRepNo = 0;
                        MyString2Anything::get_I(RepCont,RepNo);
                }
        }
//      std::cout<<"in get_RepCont: \""<<RepCont<<"\" -> ("<<SRepNo<<","<<RepNo<<")"<<std::endl; // to be deleted
}
int MyVGeometryParameter::get_VerboseLevel () [inline]
Definition at line 67 of file MyVGeometryParameter.hh.
References fVerboseLevel.
{return fVerboseLevel;}
int MyVGeometryParameter::GetValue (G4String s_card)
Reimplemented in SimpleGeometryParameter.
Definition at line 53 of file MyVGeometryParameter.cc.
References checkoverlap, and fVerboseLevel.
Referenced by SimpleGeometryParameter::GetValue().
{
        int status = 0;
        std::stringstream buf_card;
        buf_card.str("");
        buf_card.clear();
        buf_card<<s_card;
        G4String name;
        buf_card>>name;
        G4String s_para;
        if( name == "VerboseLevel:" ) buf_card>>fVerboseLevel;
        else if( name == "checkoverlap" ) checkoverlap = true;
        else status = 1;
        buf_card.str("");
        buf_card.clear();
        return status;
}
std::vector< G4String > MyConfigure::GetWords (G4String formula) [inherited]
Definition at line 48 of file MyConfigure.cc.
Referenced by MyConfigure::ReplaceMacro().
{
        std::vector<G4String> words;
        words.clear();
        const char* cformula = formula.c_str();
        int length = strlen(cformula);
        char temp[1240];
        int tempoffset = 0;
        for ( int offset = 0; offset < length; offset++ ){
                char c = cformula[offset];
                bool isword = false;
                if (c>='a'&&c<='z'
                        ||c>='A'&&c<='Z'
                        ||c>='0'&&c<='9'
                        ||c=='_'
                   ){
                        temp[tempoffset++] = cformula[offset];
                        isword = true;
                }
                if (!isword||offset==length-1){
                        if (tempoffset>0){
                                temp[tempoffset++] = '\0';
                                tempoffset=0;
                                G4String word = temp;
                                bool found = false;
                                for(int iWord = 0; iWord<words.size(); iWord++){
                                        if (words[iWord]==word){
                                                found = true;
                                                break;
                                        }
                                }
                                if (!found){
                                        words.push_back(word);
                                }
                        }
                }
        }
        return words;
}
virtual void MyVGeometryParameter::InitFromFile (G4String) [inline, virtual]
Reimplemented in SimpleGeometryParameter.
Definition at line 31 of file MyVGeometryParameter.hh.
Referenced by MyVGeometryParameterMessenger::MySetNewValue(), and MyVGeometrySvc::ReadCard().
{};//Get necessary parameters from given file
bool MyVGeometryParameter::ISEMPTY (G4String s_card)
Definition at line 115 of file MyVGeometryParameter.cc.
Referenced by SimpleGeometryParameter::InitFromFile().
{
        bool flag = false;
        const char* c_card = s_card.c_str();
        G4int length = strlen(c_card);
        G4int offset = 0;
        for ( ; offset < length; offset++ ){
                if ( c_card[offset] != ' ' ) break;
        }
        if ( c_card[offset] == '#' || (c_card[offset] == '/' && c_card[offset+1] == '/') || length - offset == 0 ){
                flag = true;
        }
        return flag;
}
void MyVGeometryParameter::Preset ()
Reimplemented in SimpleGeometryParameter.
Definition at line 47 of file MyVGeometryParameter.cc.
References checkoverlap, and fVerboseLevel.
{
        fVerboseLevel = 0;
        checkoverlap = false;
}
void MyConfigure::Replace (G4String & formula, G4String word, G4String value) [inherited]
Definition at line 99 of file MyConfigure.cc.
References MyConfigure::FindMacro().
Referenced by MyConfigure::ReplaceMacro().
{
//      std::cout<<"-- \""<<formula<<"\""<<std::endl; // to be deleted
        G4String newform = "";
        const char* cformula = formula.c_str();
        int length = strlen(cformula);
        char temp[1024];
        int tempoffset = 0;
        char cnewform[1024];
        int newformoffset = 0;
        for ( int offset = 0; offset < length; offset++ ){
                char c = cformula[offset];
                bool isword = false;
                if (c>='a'&&c<='z'
                        ||c>='A'&&c<='Z'
                        ||c>='0'&&c<='9'
                        ||c=='_'
                   ){
                        temp[tempoffset++] = cformula[offset];
                        isword = true;
                }
                if (!isword||offset==length-1){
                        if (tempoffset>0){
                                temp[tempoffset] = '\0';
                                tempoffset=0;
                                if (newformoffset>0){
                                        cnewform[newformoffset] = '\0';
                                        newformoffset=0;
                                        G4String newformtemp = cnewform;
                                        newform=newform+newformtemp;
                                }
                                G4String word = temp;
//                              std::cout<<"            \""<<word<<"\""<<std::endl; // to be deleted
                                G4String newword;
                                bool found = FindMacro(word,newword);
                                if (found){
                                        newform=newform+"("+newword+")";
                                }
                                else{
                                        newform=newform+word;
                                }
//                              std::cout<<"            to \""<<newword<<"\""<<std::endl; // to be deleted
                        }
                        if(!isword){
                                cnewform[newformoffset++] = cformula[offset];
                        }
                        if (offset==length-1){
                                cnewform[newformoffset] = '\0';
                                G4String newformtemp = cnewform;
                                newform=newform+newformtemp;
                        }
                }
        }
//      std::cout<<"    -->\""<<newform<<"\""<<std::endl; // to be deleted
        formula = newform;
}
G4String MyConfigure::ReplaceMacro (G4String formula) [inherited]
Definition at line 33 of file MyConfigure.cc.
References MyConfigure::FindMacro(), MyConfigure::GetWords(), and MyConfigure::Replace().
Referenced by SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
{
//      std::cout<<"TO replace for: \""<<formula<<"\""<<std::endl; // to be deleted
        std::vector<G4String> words = GetWords(formula);
//      std::cout<<"    "<<words.size()<<" words"<<std::endl; // to be deleted
        for (int iWord = 0; iWord < words.size(); iWord++ ){
//              std::cout<<"            "<<iWord<<std::endl; // to be deleted
                G4String value;
                if (FindMacro(words[iWord],value)){
                        Replace(formula,words[iWord],value);
                }
        }
//      std::cout<<"\t=>"<<formula<<std::endl;
        return formula;
}
void MyVGeometryParameter::set_checkoverlap (bool val) [inline]
Definition at line 73 of file MyVGeometryParameter.hh.
References checkoverlap.
Referenced by MyVGeometryParameterMessenger::MySetNewValue().
{ checkoverlap = val;}
void MyVGeometryParameter::set_filename (G4String val) [inline]
Definition at line 77 of file MyVGeometryParameter.hh.
References m_filename.
Referenced by SimpleGeometryParameter::InitFromFile().
{ m_filename = val; }
void MyVGeometryParameter::set_GeometryParameterMessenger (MyVGeometryParameterMessenger * val) [inline]
Definition at line 75 of file MyVGeometryParameter.hh.
References m_GeometryParameterMessenger.
Referenced by SimpleGeometryParameter::SimpleGeometryParameter().
{m_GeometryParameterMessenger = val;};
void MyVGeometryParameter::set_Name (G4String val) [inline]
Definition at line 76 of file MyVGeometryParameter.hh.
References m_Name.
Referenced by MyVGeometryParameter().
{ m_Name = val; }
void MyVGeometryParameter::set_VerboseLevel (int val) [inline]
Definition at line 74 of file MyVGeometryParameter.hh.
References fVerboseLevel.
Referenced by MyVGeometryParameterMessenger::MySetNewValue().
{ fVerboseLevel = val;}
Member Data Documentation
bool MyVGeometryParameter::checkoverlap [private]
Definition at line 81 of file MyVGeometryParameter.hh.
Referenced by DumpInfo(), get_checkoverlap(), GetValue(), Preset(), and set_checkoverlap().
int MyVGeometryParameter::fVerboseLevel [private]
Definition at line 82 of file MyVGeometryParameter.hh.
Referenced by DumpInfo(), get_VerboseLevel(), GetValue(), Preset(), and set_VerboseLevel().
std::vector< G4String > MyConfigure::knownValueNames [static, inherited]
Definition at line 24 of file MyConfigure.hh.
Referenced by MyConfigure::FindMacro(), SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
std::vector< G4String > MyConfigure::knownValues [static, inherited]
Definition at line 25 of file MyConfigure.hh.
Referenced by MyConfigure::FindMacro(), SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
G4String MyVGeometryParameter::m_filename [private]
Definition at line 84 of file MyVGeometryParameter.hh.
Referenced by DumpInfo(), get_filename(), and set_filename().
MyVGeometryParameterMessenger* MyVGeometryParameter::m_GeometryParameterMessenger [private]
Definition at line 86 of file MyVGeometryParameter.hh.
Referenced by set_GeometryParameterMessenger(), and ~MyVGeometryParameter().
G4String MyVGeometryParameter::m_Name [private]
Definition at line 85 of file MyVGeometryParameter.hh.
Referenced by DumpInfo(), get_Name(), and set_Name().
The documentation for this class was generated from the following files:
include/MyVGeometryParameter.hh
src/MyVGeometryParameter.cc