g4sim: CdcCellGeometryParameterMessenger Class Reference
CdcCellGeometryParameterMessenger Class Reference
#include <CdcCellGeometryParameterMessenger.hh>
Public Member Functions
CdcCellGeometryParameterMessenger (MyVGeometryParameter *, G4String)
virtual ~CdcCellGeometryParameterMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
int MySetNewValue (G4UIcommand *, G4String)
CdcCellGeometryParameter * get_GeometryParameter ()
void set_GeometryParameter (CdcCellGeometryParameter *val)
void set_GeometryParameter (SimpleGeometryParameter *val)
void set_GeometryParameter (MyVGeometryParameter *val)
G4String get_Name ()
G4String get_GeoDirName ()
void set_Name (G4String val)
void set_GeoDirName (G4String val)
Private Attributes
CdcCellGeometryParameter * m_GeometryParameter
G4String m_SubDirName
G4UIdirectory * SubDir
Detailed Description
Definition at line 20 of file CdcCellGeometryParameterMessenger.hh.
Constructor & Destructor Documentation
CdcCellGeometryParameterMessenger::CdcCellGeometryParameterMessenger (MyVGeometryParameter * pGeometryParameter, G4String dirName)
Definition at line 20 of file CdcCellGeometryParameterMessenger.cc.
References MyVGeometryParameterMessenger::get_GeoDirName(), m_GeometryParameter, m_SubDirName, and SubDir.
:SimpleGeometryParameterMessenger(pGeometryParameter, dirName)
{
        m_GeometryParameter = dynamic_cast<CdcCellGeometryParameter*> (pGeometryParameter);
        if (!m_GeometryParameter){
                std::cout<<"In CdcCellGeometryParameterMessenger, Cannot convert pointer from MyVGeometryParameter* to CdcCellGeometryParameter!!!"<<std::endl;
    G4Exception("CdcCellGeometryParameterMessenger::CdcCellGeometryParameterMessenger()",
        "InvalidSetup", FatalException,
        "Cannot convert pointer from MyVGeometryParameter* to CdcCellGeometryParameter!!!");
        }
        G4String fGeoDirName = get_GeoDirName();
        m_SubDirName = fGeoDirName+"CdcCellGeometry/";
        SubDir = new G4UIdirectory(m_SubDirName);
        SubDir->SetGuidance("geometry control");
}
CdcCellGeometryParameterMessenger::~CdcCellGeometryParameterMessenger () [virtual]
Definition at line 40 of file CdcCellGeometryParameterMessenger.cc.
References SubDir.
{
        delete SubDir;
}
Member Function Documentation
G4String MyVGeometryParameterMessenger::get_GeoDirName () [inline, inherited]
Definition at line 32 of file MyVGeometryParameterMessenger.hh.
References MyVGeometryParameterMessenger::m_GeoDirName.
Referenced by CdcCellGeometryParameterMessenger(), CdcGeometryParameterMessenger::CdcGeometryParameterMessenger(), and SimpleGeometryParameterMessenger::SimpleGeometryParameterMessenger().
{ return m_GeoDirName; }
CdcCellGeometryParameter* CdcCellGeometryParameterMessenger::get_GeometryParameter () [inline]
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 32 of file CdcCellGeometryParameterMessenger.hh.
References m_GeometryParameter.
{ return m_GeometryParameter; }
G4String MyVGeometryParameterMessenger::get_Name () [inline, inherited]
Definition at line 30 of file MyVGeometryParameterMessenger.hh.
References MyVGeometryParameterMessenger::m_Name.
{ return m_Name; }
int CdcCellGeometryParameterMessenger::MySetNewValue (G4UIcommand * command, G4String newValue)
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 51 of file CdcCellGeometryParameterMessenger.cc.
Referenced by SetNewValue().
{
        int status = 0; //0 means found the value
        status = MyVGeometryParameterMessenger::MySetNewValue(command, newValue); //check Parent Class first
        if ( !status ) return status;
        return status;
}
void MyVGeometryParameterMessenger::set_GeoDirName (G4String val) [inline, inherited]
Definition at line 37 of file MyVGeometryParameterMessenger.hh.
References MyVGeometryParameterMessenger::m_GeoDirName.
{ m_GeoDirName = val; }
void MyVGeometryParameterMessenger::set_GeometryParameter (MyVGeometryParameter * val) [inline, inherited]
Definition at line 36 of file MyVGeometryParameterMessenger.hh.
References MyVGeometryParameterMessenger::m_GeometryParameter.
Referenced by MyVGeometryParameterMessenger::MyVGeometryParameterMessenger().
{ m_GeometryParameter = val; }
void SimpleGeometryParameterMessenger::set_GeometryParameter (SimpleGeometryParameter * val) [inline, inherited]
Definition at line 38 of file SimpleGeometryParameterMessenger.hh.
References SimpleGeometryParameterMessenger::m_GeometryParameter.
{ m_GeometryParameter = val; }
void CdcCellGeometryParameterMessenger::set_GeometryParameter (CdcCellGeometryParameter * val) [inline]
Definition at line 35 of file CdcCellGeometryParameterMessenger.hh.
References m_GeometryParameter.
{ m_GeometryParameter = val; }
void MyVGeometryParameterMessenger::set_Name (G4String val) [inline, inherited]
Definition at line 35 of file MyVGeometryParameterMessenger.hh.
References MyVGeometryParameterMessenger::m_Name.
Referenced by MyVGeometryParameterMessenger::MyVGeometryParameterMessenger().
{ m_Name = val; }
void CdcCellGeometryParameterMessenger::SetNewValue (G4UIcommand * command, G4String newValue) [virtual]
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 45 of file CdcCellGeometryParameterMessenger.cc.
References MySetNewValue().
{
        MySetNewValue(command, newValue);
}
Member Data Documentation
CdcCellGeometryParameter* CdcCellGeometryParameterMessenger::m_GeometryParameter [private]
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 39 of file CdcCellGeometryParameterMessenger.hh.
Referenced by CdcCellGeometryParameterMessenger(), get_GeometryParameter(), and set_GeometryParameter().
G4String CdcCellGeometryParameterMessenger::m_SubDirName [private]
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 41 of file CdcCellGeometryParameterMessenger.hh.
Referenced by CdcCellGeometryParameterMessenger().
G4UIdirectory* CdcCellGeometryParameterMessenger::SubDir [private]
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 42 of file CdcCellGeometryParameterMessenger.hh.
Referenced by CdcCellGeometryParameterMessenger(), and ~CdcCellGeometryParameterMessenger().
The documentation for this class was generated from the following files:
include/CdcCellGeometryParameterMessenger.hh
src/CdcCellGeometryParameterMessenger.cc