g4sim: SimpleGeometrySvc Class Reference
SimpleGeometrySvc Class Reference
#include <SimpleGeometrySvc.hh>
Public Member Functions
SimpleGeometrySvc (G4String name, G4String opt="")
virtual ~SimpleGeometrySvc ()
virtual G4VPhysicalVolume * SetGeometry ()
void ConstructVolumes ()
G4VPhysicalVolume * PlaceVolumes ()
SimpleGeometryParameter * get_GeometryParameter ()
void set_GeometryParameter (SimpleGeometryParameter *val)
void ReadCard (G4String)
G4LogicalVolume * get_logicalVolume (G4String name)
int get_VerboseLevel ()
G4String get_Name ()
void set_GeometryParameter (MyVGeometryParameter *val)
void set_VerboseLevel (int val)
void set_Name (G4String val)
std::vector< G4String > GetWords (G4String formula)
bool FindMacro (G4String word, G4String &value)
void Replace (G4String &formula, G4String word, G4String value)
double CalFormula (G4String formula, int iRep=0)
G4String ReplaceMacro (G4String formula)
Static Public Attributes
static std::vector< G4String > knownValueNames
static std::vector< G4String > knownValues
Private Attributes
SimpleGeometryParameter * m_GeometryParameter
Detailed Description
Definition at line 27 of file SimpleGeometrySvc.hh.
Constructor & Destructor Documentation
SimpleGeometrySvc::SimpleGeometrySvc (G4String name, G4String opt = "")
Definition at line 45 of file SimpleGeometrySvc.cc.
References set_GeometryParameter().
        : MyVGeometrySvc(name, "S") // Use a not-empty opt to stop inherited class from creating new GeometryParameter
{
        if ( opt == "" ){//called directly by user. set up parameter class.
                SimpleGeometryParameter *pointer = new SimpleGeometryParameter(name);
//              std::cout<<"======>In SimpleGeometrySvc, new SimpleGeometryParameter at ("<<(void*)pointer<<")!"<<std::endl;
                set_GeometryParameter(pointer);
        }
}
SimpleGeometrySvc::~SimpleGeometrySvc () [virtual]
Definition at line 55 of file SimpleGeometrySvc.cc.
{
        printf("~SimpleGeometrySvc");
}
Member Function Documentation
double MyConfigure::CalFormula (G4String formula, int iRep = 0) [inherited]
Definition at line 23 of file MyConfigure.cc.
Referenced by SimpleGeometryParameter::Calculate(), and PrimaryGeneratorAction::ReadCard().
{
//      std::cout<<"TO Calculate for: \""<<formula<<"\" "<<iRep<<std::endl; // to be deleted
//      formula = ReplaceMacro(formula);
        TF1 *f1 = new TF1("f1", formula);
        double value = f1->Eval(iRep);
//      std::cout<<"\t=>"<<value<<std::endl;
        delete f1;
        return value;
}
void SimpleGeometrySvc::ConstructVolumes ()
Reimplemented from MyVGeometrySvc.
Definition at line 76 of file SimpleGeometrySvc.cc.
References SimpleGeometryParameter::get_b(), SimpleGeometryParameter::get_BooleanSolid_Ephi(), SimpleGeometryParameter::get_BooleanSolid_Epsi(), SimpleGeometryParameter::get_BooleanSolid_Etheta(), SimpleGeometryParameter::get_BooleanSolid_PosX(), SimpleGeometryParameter::get_BooleanSolid_PosY(), SimpleGeometryParameter::get_BooleanSolid_PosZ(), SimpleGeometryParameter::get_BooleanSolid_sol1(), SimpleGeometryParameter::get_BooleanSolid_sol2(), SimpleGeometryParameter::get_BooleanSolid_type(), SimpleGeometryParameter::get_Box_X(), SimpleGeometryParameter::get_Box_Y(), SimpleGeometryParameter::get_Box_Z(), SimpleGeometryParameter::get_Cons_Length(), SimpleGeometryParameter::get_Cons_RMax1(), SimpleGeometryParameter::get_Cons_RMax2(), SimpleGeometryParameter::get_Cons_RMin1(), SimpleGeometryParameter::get_Cons_RMin2(), SimpleGeometryParameter::get_Cons_SpanAng(), SimpleGeometryParameter::get_Cons_StartAng(), SimpleGeometryParameter::get_EllipticalTube_X(), SimpleGeometryParameter::get_EllipticalTube_Y(), SimpleGeometryParameter::get_EllipticalTube_Z(), SimpleGeometryParameter::get_ExtrudedSolid_numP(), SimpleGeometryParameter::get_ExtrudedSolid_numZ(), SimpleGeometryParameter::get_ExtrudedSolid_Scale(), SimpleGeometryParameter::get_ExtrudedSolid_X(), SimpleGeometryParameter::get_ExtrudedSolid_X0(), SimpleGeometryParameter::get_ExtrudedSolid_Y(), SimpleGeometryParameter::get_ExtrudedSolid_Y0(), SimpleGeometryParameter::get_ExtrudedSolid_Z(), SimpleGeometryParameter::get_g(), SimpleGeometryParameter::get_Hype_innerRadius(), SimpleGeometryParameter::get_Hype_innerStereo(), SimpleGeometryParameter::get_Hype_Length(), SimpleGeometryParameter::get_Hype_outerRadius(), SimpleGeometryParameter::get_Hype_outerStereo(), SimpleGeometryParameter::get_material(), SimpleGeometryParameter::get_name(), SimpleGeometryParameter::get_Polycone_numZ(), SimpleGeometryParameter::get_Polycone_RMax(), SimpleGeometryParameter::get_Polycone_RMin(), SimpleGeometryParameter::get_Polycone_SpanAng(), SimpleGeometryParameter::get_Polycone_StartAng(), SimpleGeometryParameter::get_Polycone_Z(), SimpleGeometryParameter::get_r(), SimpleGeometryParameter::get_RepNo(), SimpleGeometryParameter::get_SDName(), SimpleGeometryParameter::get_SolidBoolean(), SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_SolidType(), SimpleGeometryParameter::get_Sphere_RMax(), SimpleGeometryParameter::get_Sphere_RMin(), SimpleGeometryParameter::get_Sphere_SpanPhi(), SimpleGeometryParameter::get_Sphere_SpanTheta(), SimpleGeometryParameter::get_Sphere_StartPhi(), SimpleGeometryParameter::get_Sphere_StartTheta(), SimpleGeometryParameter::get_SRepNo(), SimpleGeometryParameter::get_t(), SimpleGeometryParameter::get_Torus_RMax(), SimpleGeometryParameter::get_Torus_RMin(), SimpleGeometryParameter::get_Torus_Rtor(), SimpleGeometryParameter::get_Torus_SpanAng(), SimpleGeometryParameter::get_Torus_StartAng(), SimpleGeometryParameter::get_Tubs_Length(), SimpleGeometryParameter::get_Tubs_RMax(), SimpleGeometryParameter::get_Tubs_RMin(), SimpleGeometryParameter::get_Tubs_SpanAng(), SimpleGeometryParameter::get_Tubs_StartAng(), SimpleGeometryParameter::get_TwistedTubs_dphi(), SimpleGeometryParameter::get_TwistedTubs_endinnerrad(), SimpleGeometryParameter::get_TwistedTubs_endouterrad(), SimpleGeometryParameter::get_TwistedTubs_Length(), SimpleGeometryParameter::get_TwistedTubs_twistedangle(), SimpleGeometryParameter::get_vis(), SimpleGeometryParameter::get_VolNo(), MyDetectorManager::GetMyDetectorManager(), MyDetectorManager::GetSD(), and m_GeometryParameter.
Referenced by SetGeometry().
{
        MyVGeometrySvc::ConstructVolumes();
        bool vis;
        double r, g, b, t;
        std::stringstream buffer;
        G4Material* pttoMaterial;
        int nVol = m_GeometryParameter->get_VolNo();
        for ( int i_Vol = 0; i_Vol < nVol; i_Vol++ ){
                G4String name, mat_name, SDName;
                G4String SolidType;
                G4int SolidIndex;
                G4int SRepNo;
                G4int RepNo;
                SolidIndex = m_GeometryParameter->get_SolidIndex(i_Vol);
                SolidType = m_GeometryParameter->get_SolidType(i_Vol);
                name = m_GeometryParameter->get_name(i_Vol);
                SRepNo = m_GeometryParameter->get_SRepNo(i_Vol);
                RepNo = m_GeometryParameter->get_RepNo(i_Vol);
                for ( int i = 0; i < RepNo; i++ ){
                        G4VSolid* sol_Vol = 0;
                        G4String iname = name;
                        if (RepNo>1){
                                buffer.str("");
                                buffer.clear();
                                buffer<<name<<"_"<<i;
                                iname = buffer.str();
                        }
                        if ( SolidType == "Box" ){
                                G4double halfX, halfY, halfZ;
                                halfX = m_GeometryParameter->get_Box_X(SolidIndex,i)/2;
                                halfY = m_GeometryParameter->get_Box_Y(SolidIndex,i)/2;
                                halfZ = m_GeometryParameter->get_Box_Z(SolidIndex,i)/2;
                                sol_Vol=new G4Box(iname,halfX,halfY,halfZ);
                        }
                        else if ( SolidType == "EllipticalTube" ){
                                G4double halfX, halfY, halfZ;
                                halfX = m_GeometryParameter->get_EllipticalTube_X(SolidIndex,i)/2;
                                halfY = m_GeometryParameter->get_EllipticalTube_Y(SolidIndex,i)/2;
                                halfZ = m_GeometryParameter->get_EllipticalTube_Z(SolidIndex,i)/2;
                                sol_Vol=new G4EllipticalTube(iname,halfX,halfY,halfZ);
                        }
                        else if ( SolidType == "Tubs" ){
                                G4double RMax, RMin, halfLength, StartAng, SpanAng;
                                RMax = m_GeometryParameter->get_Tubs_RMax(SolidIndex,i);
                                RMin = m_GeometryParameter->get_Tubs_RMin(SolidIndex,i);
                                halfLength = m_GeometryParameter->get_Tubs_Length(SolidIndex,i)/2;
                                StartAng = m_GeometryParameter->get_Tubs_StartAng(SolidIndex,i);
                                SpanAng = m_GeometryParameter->get_Tubs_SpanAng(SolidIndex,i);
                                sol_Vol=new G4Tubs(iname,RMin,RMax,halfLength,StartAng,SpanAng);
                        }
                        else if ( SolidType == "Torus" ){
                                G4double RMax, RMin, Rtor, StartAng, SpanAng;
                                RMax = m_GeometryParameter->get_Torus_RMax(SolidIndex,i);
                                RMin = m_GeometryParameter->get_Torus_RMin(SolidIndex,i);
                                Rtor = m_GeometryParameter->get_Torus_Rtor(SolidIndex,i);
                                StartAng = m_GeometryParameter->get_Torus_StartAng(SolidIndex,i);
                                SpanAng = m_GeometryParameter->get_Torus_SpanAng(SolidIndex,i);
                                sol_Vol=new G4Torus(iname,RMin,RMax,Rtor,StartAng,SpanAng);
                        }
                        else if ( SolidType == "Sphere" ){
                                G4double RMax, RMin, StartPhi, SpanPhi, StartTheta, SpanTheta;
                                RMax = m_GeometryParameter->get_Sphere_RMax(SolidIndex,i);
                                RMin = m_GeometryParameter->get_Sphere_RMin(SolidIndex,i);
                                StartPhi = m_GeometryParameter->get_Sphere_StartPhi(SolidIndex,i);
                                SpanPhi = m_GeometryParameter->get_Sphere_SpanPhi(SolidIndex,i);
                                StartTheta = m_GeometryParameter->get_Sphere_StartTheta(SolidIndex,i);
                                SpanTheta = m_GeometryParameter->get_Sphere_SpanTheta(SolidIndex,i);
                                sol_Vol=new G4Sphere(iname,RMin,RMax,StartPhi,SpanPhi,StartTheta,SpanTheta);
                        }
                        else if ( SolidType == "Hype" ){
                                G4double innerRadius, outerRadius, halfLength, innerStereo, outerStereo;
                                innerRadius = m_GeometryParameter->get_Hype_innerRadius(SolidIndex,i);
                                outerRadius = m_GeometryParameter->get_Hype_outerRadius(SolidIndex,i);
                                halfLength = m_GeometryParameter->get_Hype_Length(SolidIndex,i)/2;
                                innerStereo = m_GeometryParameter->get_Hype_innerStereo(SolidIndex,i);
                                outerStereo = m_GeometryParameter->get_Hype_outerStereo(SolidIndex,i);
                                sol_Vol=new G4Hype(iname,innerRadius,outerRadius,innerStereo,outerStereo,halfLength);
                        }
                        else if ( SolidType == "TwistedTubs" ){
                                G4double endinnerrad, endouterrad, halfLength, twistedangle, dphi;
                                twistedangle = m_GeometryParameter->get_TwistedTubs_twistedangle(SolidIndex,i);
                                endinnerrad = m_GeometryParameter->get_TwistedTubs_endinnerrad(SolidIndex,i);
                                endouterrad = m_GeometryParameter->get_TwistedTubs_endouterrad(SolidIndex,i);
                                halfLength = m_GeometryParameter->get_TwistedTubs_Length(SolidIndex,i)/2;
                                dphi = m_GeometryParameter->get_TwistedTubs_dphi(SolidIndex,i);
                                sol_Vol=new G4TwistedTubs(iname,twistedangle,endinnerrad,endouterrad,halfLength,dphi);
                        }
                        else if ( SolidType == "Cons" ){
                                G4double RMax1, RMin1, RMax2, RMin2, halfLength, StartAng, SpanAng;
                                RMax1 = m_GeometryParameter->get_Cons_RMax1(SolidIndex,i);
                                RMin1 = m_GeometryParameter->get_Cons_RMin1(SolidIndex,i);
                                RMax2 = m_GeometryParameter->get_Cons_RMax2(SolidIndex,i);
                                RMin2 = m_GeometryParameter->get_Cons_RMin2(SolidIndex,i);
                                halfLength = m_GeometryParameter->get_Cons_Length(SolidIndex,i)/2;
                                StartAng = m_GeometryParameter->get_Cons_StartAng(SolidIndex,i);
                                SpanAng = m_GeometryParameter->get_Cons_SpanAng(SolidIndex,i);
                                sol_Vol=new G4Cons(iname,RMin1,RMax1,RMin2,RMax2,halfLength,StartAng,SpanAng);
                        }
                        else if ( SolidType == "Polycone" ){
                                G4double StartAng, SpanAng;
                                G4int numZ;
                                numZ = m_GeometryParameter->get_Polycone_numZ(SolidIndex,i);
                                G4double *RMax = new G4double[numZ];
                                G4double *RMin = new G4double[numZ];
                                G4double *Z = new G4double[numZ];
                                for ( int j = 0; j < numZ; j++ ){
                                        RMax[j] = m_GeometryParameter->get_Polycone_RMax(SolidIndex,j,i);
                                        RMin[j] = m_GeometryParameter->get_Polycone_RMin(SolidIndex,j,i);
                                        Z[j] = m_GeometryParameter->get_Polycone_Z(SolidIndex,j,i);
                                        std::cout<<j<<": RMax = "<<RMax[j]/mm<<"mm, RMin = "<<RMin[j]/mm<<"mm, "<<Z[j]/mm<<"mm"<<std::endl;
                                }
                                StartAng = m_GeometryParameter->get_Polycone_StartAng(SolidIndex,i);
                                SpanAng = m_GeometryParameter->get_Polycone_SpanAng(SolidIndex,i);
                                sol_Vol=new G4Polycone(iname,StartAng,SpanAng,numZ,Z,RMin,RMax);
                        }
                        else if ( SolidType == "ExtrudedSolid" ){
                                G4int numZ, numP;
                                numZ = m_GeometryParameter->get_ExtrudedSolid_numZ(SolidIndex,i);
                                numP = m_GeometryParameter->get_ExtrudedSolid_numP(SolidIndex,i);
                                std::vector<G4TwoVector> polygon;
                                std::vector<G4ExtrudedSolid::ZSection>    zsections;
                                for ( int j = 0; j < numZ; j++ ){
                                        zsections.push_back(G4ExtrudedSolid::ZSection(m_GeometryParameter->get_ExtrudedSolid_Z(SolidIndex,j,i),
                                                                             G4TwoVector(m_GeometryParameter->get_ExtrudedSolid_X0(SolidIndex,j,i),
                                                                                         m_GeometryParameter->get_ExtrudedSolid_Y0(SolidIndex,j,i)),
                                                                             m_GeometryParameter->get_ExtrudedSolid_Scale(SolidIndex,j,i)));
                                }
                                for ( int j = 0; j < numP; j++ ){
                                        polygon.push_back(G4TwoVector(m_GeometryParameter->get_ExtrudedSolid_X(SolidIndex,j,i),
                                                                              m_GeometryParameter->get_ExtrudedSolid_Y(SolidIndex,j,i)));
                                }
                                sol_Vol=new G4ExtrudedSolid(iname,polygon,zsections);
                        }
                        else if ( SolidType == "BooleanSolid" ){
                                G4double Ephi = m_GeometryParameter->get_BooleanSolid_Ephi(SolidIndex,i);
                                G4double Etheta = m_GeometryParameter->get_BooleanSolid_Etheta(SolidIndex,i);
                                G4double Epsi = m_GeometryParameter->get_BooleanSolid_Epsi(SolidIndex,i);
                                G4double PosX  = m_GeometryParameter->get_BooleanSolid_PosX(SolidIndex,i);
                                G4double PosY  = m_GeometryParameter->get_BooleanSolid_PosY(SolidIndex,i);
                                G4double PosZ  = m_GeometryParameter->get_BooleanSolid_PosZ(SolidIndex,i);
                                G4RotationMatrix* rot =new G4RotationMatrix(Ephi,Etheta,Epsi);
                                G4ThreeVector trans(PosX ,PosY ,PosZ);
                                G4String type = m_GeometryParameter->get_BooleanSolid_type(SolidIndex);
                                G4String sol_name1 = m_GeometryParameter->get_BooleanSolid_sol1(SolidIndex);
                                G4String sol_name2 = m_GeometryParameter->get_BooleanSolid_sol2(SolidIndex);
                                G4String isol_name1 = sol_name1;
                                G4String isol_name2 = sol_name2;
                                if (RepNo>1){
                                        buffer.str("");
                                        buffer.clear();
                                        buffer<<sol_name1<<"_"<<i;
                                        isol_name1 = buffer.str();
                                        buffer.str("");
                                        buffer.clear();
                                        buffer<<sol_name2<<"_"<<i;
                                        isol_name2 = buffer.str();
                                }
                                G4SolidStore *pSolidStore = G4SolidStore::GetInstance();
                                G4VSolid *sol1 = pSolidStore->GetSolid(isol_name1);
                                G4VSolid *sol2 = pSolidStore->GetSolid(isol_name2);
                                if (!sol1||!sol2){
                                        std::cout<<"ERROR: in SimpleGeometrySvc::ConstructVolumes(), cannot find solids for BooleanSolid \""<<iname<<"\" !!!"<<std::endl;
                                        continue;
                                }
                                if ( type == "plus" ){
                                        sol_Vol = new G4UnionSolid(iname,sol1,sol2,rot,trans);
                                }
                                else if ( type == "minus" ){
                                        sol_Vol = new G4SubtractionSolid(iname,sol1,sol2,rot,trans);
                                }
                                else if ( type == "times" ){
                                        sol_Vol = new G4IntersectionSolid(iname,sol1,sol2,rot,trans);
                                }
                                else {
                                        std::cout<<"ERROR: in SimpleGeometrySvc::ConstructVolumes(), cannot recognize BooleanSolid type \""<<type<<"\""<<"for \""<<iname<<"\"!!!"<<std::endl;
                                        continue;
                                }
                        }
                        else {
                                std::cout<<"SolidType "<<SolidType<<" is not supported yet!"<<std::endl;
                                G4Exception("SimpleGeometrySvc::ConstructVolumes()",
                                                "InvalidSetup", FatalException,
                                                "unknown SolidType");
                        }
                        if (m_GeometryParameter->get_SolidBoolean(i_Vol)) continue;
                        SDName = m_GeometryParameter->get_SDName(i_Vol);
                        mat_name = m_GeometryParameter->get_material(i_Vol);
                        pttoMaterial = G4Material::GetMaterial(mat_name);
                        //              std::cout<<"name = "<<name
                        //                       <<", i_Vol = "<<i_Vol
                        //                       <<", SolidType = "<<SolidType
                        //                       <<", SolidIndex = "<<SolidIndex
                        //                       <<std::endl;
                        if (!pttoMaterial){
                                std::cout<<"Material "<<mat_name<<" is not defined!"<<std::endl;
                                G4Exception("SimpleGeometrySvc::ConstructVolumes()",
                                                "InvalidSetup", FatalException,
                                                "unknown material name");
                        }
                        G4LogicalVolume* log_Vol;
                        log_Vol = new G4LogicalVolume(sol_Vol, pttoMaterial, iname,0,0,0);
                        G4VSensitiveDetector* aSD;
                        aSD = MyDetectorManager::GetMyDetectorManager()->GetSD(iname, SDName, const_cast<SimpleGeometrySvc*>(this) );
                        log_Vol->SetSensitiveDetector(aSD);
                        //visual
                        vis = m_GeometryParameter->get_vis(i_Vol);
                        if (!vis){
                                log_Vol->SetVisAttributes(G4VisAttributes::Invisible);
                        }
                        else{
                                r = m_GeometryParameter->get_r(i_Vol);
                                g = m_GeometryParameter->get_g(i_Vol);
                                b = m_GeometryParameter->get_b(i_Vol);
                                t = m_GeometryParameter->get_t(i_Vol);
                                G4VisAttributes* visAttributes = new G4VisAttributes;
                                visAttributes->SetVisibility(true);
                                visAttributes->SetColour(r,g,b,t);
                                log_Vol->SetVisAttributes(visAttributes);
                        }
                }
        }
}
bool MyConfigure::FindMacro (G4String word, G4String & value) [inherited]
Definition at line 87 of file MyConfigure.cc.
References MyConfigure::knownValueNames, and MyConfigure::knownValues.
Referenced by MyConfigure::Replace(), and MyConfigure::ReplaceMacro().
{
        bool found = false;
        for (int i = 0; i< knownValues.size(); i++){
                if (knownValueNames[i]==word){
                        value = knownValues[i];
                        found = true;
                        break;
                }
        }
        return found;
}
SimpleGeometryParameter* SimpleGeometrySvc::get_GeometryParameter () [inline]
Reimplemented from MyVGeometrySvc.
Definition at line 41 of file SimpleGeometrySvc.hh.
References m_GeometryParameter.
{ return m_GeometryParameter; }
G4LogicalVolume * MyVGeometrySvc::get_logicalVolume (G4String name) [inherited]
Definition at line 51 of file MyVGeometrySvc.cc.
Referenced by PlaceVolumes().
{
        //get mother_volume
  G4LogicalVolumeStore* logicalVolumeStore = G4LogicalVolumeStore::GetInstance();
  G4LogicalVolume* log_volume = logicalVolumeStore->GetVolume(name,false);
  if (!log_volume){
    std::cout<<"Logical volume "<<name<<" of MyVGeometry can not be found!!!"<<std::endl;
    G4Exception("MyVGeometrySvc::get_logicalVolume()","Run0031",
        FatalException, "unknown logical volume.");
  }
  return log_volume;
}
G4String MyVGeometrySvc::get_Name () [inline, inherited]
Definition at line 50 of file MyVGeometrySvc.hh.
References MyVGeometrySvc::m_Name.
{ return m_Name; }
int MyVGeometrySvc::get_VerboseLevel () [inline, inherited]
Definition at line 48 of file MyVGeometrySvc.hh.
References MyVGeometrySvc::fVerboseLevel.
{ return fVerboseLevel; }
std::vector< G4String > MyConfigure::GetWords (G4String formula) [inherited]
Definition at line 48 of file MyConfigure.cc.
Referenced by MyConfigure::ReplaceMacro().
{
        std::vector<G4String> words;
        words.clear();
        const char* cformula = formula.c_str();
        int length = strlen(cformula);
        char temp[1240];
        int tempoffset = 0;
        for ( int offset = 0; offset < length; offset++ ){
                char c = cformula[offset];
                bool isword = false;
                if (c>='a'&&c<='z'
                        ||c>='A'&&c<='Z'
                        ||c>='0'&&c<='9'
                        ||c=='_'
                   ){
                        temp[tempoffset++] = cformula[offset];
                        isword = true;
                }
                if (!isword||offset==length-1){
                        if (tempoffset>0){
                                temp[tempoffset++] = '\0';
                                tempoffset=0;
                                G4String word = temp;
                                bool found = false;
                                for(int iWord = 0; iWord<words.size(); iWord++){
                                        if (words[iWord]==word){
                                                found = true;
                                                break;
                                        }
                                }
                                if (!found){
                                        words.push_back(word);
                                }
                        }
                }
        }
        return words;
}
G4VPhysicalVolume * SimpleGeometrySvc::PlaceVolumes ()
Reimplemented from MyVGeometrySvc.
Definition at line 301 of file SimpleGeometrySvc.cc.
References MyVGeometryParameter::get_checkoverlap(), SimpleGeometryParameter::get_Ephi(), SimpleGeometryParameter::get_Epsi(), SimpleGeometryParameter::get_Etheta(), MyVGeometrySvc::get_logicalVolume(), SimpleGeometryParameter::get_MotherName(), SimpleGeometryParameter::get_name(), SimpleGeometryParameter::get_PosX(), SimpleGeometryParameter::get_PosY(), SimpleGeometryParameter::get_PosZ(), SimpleGeometryParameter::get_RepNo(), SimpleGeometryParameter::get_SolidBoolean(), SimpleGeometryParameter::get_SRepNo(), SimpleGeometryParameter::get_VolIndex(), SimpleGeometryParameter::get_VolNo(), MyDetectorManager::GetMyDetectorManager(), MyDetectorManager::GetParaFromVolume(), and m_GeometryParameter.
Referenced by SetGeometry().
{
        std::stringstream buffer;
        G4VPhysicalVolume* world_pvol = 0;
        bool checkOverlap = m_GeometryParameter->get_checkoverlap();
        int nVol = m_GeometryParameter->get_VolNo();
        for ( int i_Vol = 0; i_Vol < nVol; i_Vol++ ){
                if (m_GeometryParameter->get_SolidBoolean(i_Vol)) continue;
                G4double PosX, PosY, PosZ;
                G4String name, motVolName;
                G4int SRepNo;
                G4int RepNo;
                name = m_GeometryParameter->get_name(i_Vol);
//              std::cout<<"Place \""<<name<<"\""<<std::endl; // to be deleted
                motVolName = m_GeometryParameter->get_MotherName(i_Vol);
                SRepNo = m_GeometryParameter->get_SRepNo(i_Vol);
                RepNo = m_GeometryParameter->get_RepNo(i_Vol);
                G4LogicalVolume* log_container;
                int motRepNo = 1;
                if ( name == "World" ) motRepNo = 1;
                else{
                        SimpleGeometryParameter* motPara = MyDetectorManager::GetMyDetectorManager()->GetParaFromVolume(motVolName);
                        if (motPara)
                                motRepNo = motPara->get_RepNo(motPara->get_VolIndex(motVolName));
                        else{
                                std::cout<<"We can't find parameter pointer!!"<<std::endl;
                        }
                }
                for ( int im = 0; im < motRepNo; im++ ){
                        if ( name == "World" ) log_container = 0;
                        else {
                                G4String imotVolName = motVolName;
                                if (motRepNo>1){
                                        buffer.str("");
                                        buffer.clear();
                                        buffer<<motVolName<<"_"<<im;
                                        imotVolName = buffer.str();
                                }
                                log_container = get_logicalVolume(imotVolName);
                        }
                        for ( int i = 0; i < RepNo; i++ ){
                                G4String iname = name;
                                if (RepNo>1){
                                        buffer.str("");
                                        buffer.clear();
                                        buffer<<name<<"_"<<i;
                                        iname = buffer.str();
                                }
                                G4LogicalVolume* log_Vol = get_logicalVolume(iname);
                                PosX  = m_GeometryParameter->get_PosX(i_Vol,i);
                                PosY  = m_GeometryParameter->get_PosY(i_Vol,i);
                                PosZ  = m_GeometryParameter->get_PosZ(i_Vol,i);
                                G4ThreeVector pos(PosX ,PosY ,PosZ);
                                G4double Ephi = m_GeometryParameter->get_Ephi(i_Vol,i);
                                G4double Etheta = m_GeometryParameter->get_Etheta(i_Vol,i);
                                G4double Epsi = m_GeometryParameter->get_Epsi(i_Vol,i);
                                G4RotationMatrix* rotateMatrix=new G4RotationMatrix(Ephi,Etheta,Epsi);
                                if ( name == "World" ) rotateMatrix = 0;
                                G4VPhysicalVolume* phy_Vol =
                                        new G4PVPlacement(rotateMatrix,                //rotation
                                                        pos,                              //position
                                                        log_Vol,                          //its logical volume
                                                        name,                             //its name
                                                        log_container,                    //its mother volume
                                                        false,                            //no boolean operation
                                                        i+SRepNo,                                //copy number
                                                        checkOverlap);                    //overlaps checking
                                if ( name == "World" ) world_pvol = phy_Vol;
                        }
                }
        }
//      std::cout<<"Finished!"<<std::endl; // to be deleted
        G4VPhysicalVolume *former = MyVGeometrySvc::PlaceVolumes();
        if (!world_pvol) world_pvol=former;
        return world_pvol;
}
void MyVGeometrySvc::ReadCard (G4String file_name) [inherited]
Definition at line 42 of file MyVGeometrySvc.cc.
References MyVGeometryParameter::InitFromFile(), and MyVGeometrySvc::m_GeometryParameter.
Referenced by MyDetectorManager::AddGeo(), and MyDetectorManager::ReadCard().
{
        if(file_name[0] != '/'){ // Relative Dir
                G4String dir_name = getenv("CONFIGUREROOT");
                if (dir_name[dir_name.size()-1] != '/') dir_name.append("/");
                file_name = dir_name + file_name;
        }
        m_GeometryParameter->InitFromFile(file_name);
}
void MyConfigure::Replace (G4String & formula, G4String word, G4String value) [inherited]
Definition at line 99 of file MyConfigure.cc.
References MyConfigure::FindMacro().
Referenced by MyConfigure::ReplaceMacro().
{
//      std::cout<<"-- \""<<formula<<"\""<<std::endl; // to be deleted
        G4String newform = "";
        const char* cformula = formula.c_str();
        int length = strlen(cformula);
        char temp[1024];
        int tempoffset = 0;
        char cnewform[1024];
        int newformoffset = 0;
        for ( int offset = 0; offset < length; offset++ ){
                char c = cformula[offset];
                bool isword = false;
                if (c>='a'&&c<='z'
                        ||c>='A'&&c<='Z'
                        ||c>='0'&&c<='9'
                        ||c=='_'
                   ){
                        temp[tempoffset++] = cformula[offset];
                        isword = true;
                }
                if (!isword||offset==length-1){
                        if (tempoffset>0){
                                temp[tempoffset] = '\0';
                                tempoffset=0;
                                if (newformoffset>0){
                                        cnewform[newformoffset] = '\0';
                                        newformoffset=0;
                                        G4String newformtemp = cnewform;
                                        newform=newform+newformtemp;
                                }
                                G4String word = temp;
//                              std::cout<<"            \""<<word<<"\""<<std::endl; // to be deleted
                                G4String newword;
                                bool found = FindMacro(word,newword);
                                if (found){
                                        newform=newform+"("+newword+")";
                                }
                                else{
                                        newform=newform+word;
                                }
//                              std::cout<<"            to \""<<newword<<"\""<<std::endl; // to be deleted
                        }
                        if(!isword){
                                cnewform[newformoffset++] = cformula[offset];
                        }
                        if (offset==length-1){
                                cnewform[newformoffset] = '\0';
                                G4String newformtemp = cnewform;
                                newform=newform+newformtemp;
                        }
                }
        }
//      std::cout<<"    -->\""<<newform<<"\""<<std::endl; // to be deleted
        formula = newform;
}
G4String MyConfigure::ReplaceMacro (G4String formula) [inherited]
Definition at line 33 of file MyConfigure.cc.
References MyConfigure::FindMacro(), MyConfigure::GetWords(), and MyConfigure::Replace().
Referenced by SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
{
//      std::cout<<"TO replace for: \""<<formula<<"\""<<std::endl; // to be deleted
        std::vector<G4String> words = GetWords(formula);
//      std::cout<<"    "<<words.size()<<" words"<<std::endl; // to be deleted
        for (int iWord = 0; iWord < words.size(); iWord++ ){
//              std::cout<<"            "<<iWord<<std::endl; // to be deleted
                G4String value;
                if (FindMacro(words[iWord],value)){
                        Replace(formula,words[iWord],value);
                }
        }
//      std::cout<<"\t=>"<<formula<<std::endl;
        return formula;
}
void MyVGeometrySvc::set_GeometryParameter (MyVGeometryParameter * val) [inline, inherited]
Definition at line 53 of file MyVGeometrySvc.hh.
References MyVGeometrySvc::m_GeometryParameter.
{ m_GeometryParameter = val; }
void SimpleGeometrySvc::set_GeometryParameter (SimpleGeometryParameter * val)
Definition at line 60 of file SimpleGeometrySvc.cc.
References m_GeometryParameter.
Referenced by SimpleGeometrySvc().
{
        m_GeometryParameter = val;
        MyVGeometrySvc::set_GeometryParameter(m_GeometryParameter);
}
void MyVGeometrySvc::set_Name (G4String val) [inline, inherited]
Definition at line 57 of file MyVGeometrySvc.hh.
References MyVGeometrySvc::m_Name.
Referenced by MyVGeometrySvc::MyVGeometrySvc().
{ m_Name = val; }
void MyVGeometrySvc::set_VerboseLevel (int val) [inline, inherited]
Definition at line 55 of file MyVGeometrySvc.hh.
References MyVGeometrySvc::fVerboseLevel.
Referenced by MyDetectorManager::AddGeo(), and MyDetectorManager::ReadCard().
{ fVerboseLevel = val; }
G4VPhysicalVolume * SimpleGeometrySvc::SetGeometry () [virtual]
Reimplemented from MyVGeometrySvc.
Definition at line 67 of file SimpleGeometrySvc.cc.
References ConstructVolumes(), SimpleGeometryParameter::Dump(), m_GeometryParameter, and PlaceVolumes().
{
        m_GeometryParameter->Dump();
        ConstructVolumes();
        G4VPhysicalVolume *current = PlaceVolumes();
        return current;
}
Member Data Documentation
std::vector< G4String > MyConfigure::knownValueNames [static, inherited]
Definition at line 24 of file MyConfigure.hh.
Referenced by MyConfigure::FindMacro(), SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
std::vector< G4String > MyConfigure::knownValues [static, inherited]
Definition at line 25 of file MyConfigure.hh.
Referenced by MyConfigure::FindMacro(), SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
SimpleGeometryParameter* SimpleGeometrySvc::m_GeometryParameter [private]
Reimplemented from MyVGeometrySvc.
Definition at line 48 of file SimpleGeometrySvc.hh.
Referenced by ConstructVolumes(), get_GeometryParameter(), PlaceVolumes(), set_GeometryParameter(), and SetGeometry().
The documentation for this class was generated from the following files:
include/SimpleGeometrySvc.hh
src/SimpleGeometrySvc.cc