g4sim: MyDetectorManager Class Reference
MyDetectorManager Class Reference
#include <MyDetectorManager.hh>
Public Member Functions
MyDetectorManager ()
~MyDetectorManager ()
void ReadCard (G4String)
void AddGeo (G4String, G4String, G4String)
void ClearGeo ()
G4VPhysicalVolume * SetGeometry ()
void ReadOutputCard (G4String)
void SetBranch ()
G4VSensitiveDetector * GetSD (G4String, G4String, MyVGeometrySvc *)
G4VSensitiveDetector * GetSD (G4String, G4String)
MyVGeometrySvc * GetSvc (G4String name)
SimpleGeometryParameter * GetParaFromVolume (G4String name)
void RegistorDM (G4String)
void Digitize ()
void SetVerbose (int val)
Static Public Member Functions
static MyDetectorManager * GetMyDetectorManager ()
Private Member Functions
void DEBUG (G4String)
Private Attributes
MyDetectorManagerMessenger * m_MyDetectorManagerMessenger
G4SDManager * fSDman
std::vector< MySD * > fSDList
std::vector< G4String > fSDName
std::vector< G4String > fVolName
std::vector< G4String > fDMName
int fVerboseLevel
std::vector< MyVGeometrySvc * > fMyVGeometrySvc
std::vector< G4String > fSvcName
Static Private Attributes
static MyDetectorManager * fMyDetectorManager = 0
Detailed Description
Definition at line 36 of file MyDetectorManager.hh.
Constructor & Destructor Documentation
MyDetectorManager::MyDetectorManager ()
Definition at line 39 of file MyDetectorManager.cc.
References DEBUG(), fMyDetectorManager, fSDman, and m_MyDetectorManagerMessenger.
        :fVerboseLevel(0)
{
  if (fMyDetectorManager){
    G4Exception("MyDetectorManager::MyDetectorManager()","Run0031",
        FatalException, "MyDetectorManager constructed twice.");
  }
  fMyDetectorManager = this;
        fSDman = G4SDManager::GetSDMpointer();
        if (!fSDman) DEBUG("Can not find G4SDManager.");
  m_MyDetectorManagerMessenger = new MyDetectorManagerMessenger(this);
}
MyDetectorManager::~MyDetectorManager ()
Definition at line 52 of file MyDetectorManager.cc.
References m_MyDetectorManagerMessenger.
{
        delete m_MyDetectorManagerMessenger;
}
Member Function Documentation
void MyDetectorManager::AddGeo (G4String name, G4String file, G4String type)
Definition at line 143 of file MyDetectorManager.cc.
References fMyVGeometrySvc, fSvcName, fVerboseLevel, MyVGeometrySvc::ReadCard(), and MyVGeometrySvc::set_VerboseLevel().
Referenced by SetGeometry(), and MyDetectorManagerMessenger::SetNewValue().
{
        MyVGeometrySvc* aGSvc = 0;
        if( type == "Simple" ){
                aGSvc = new SimpleGeometrySvc( name );
        }
        else if( type == "Cdc" ){
                aGSvc = new CdcGeometrySvc( name );
        }
        else{
                std::cout<<"In MyDetectorManager::ReadCard, unsupported GeometrySvc type: "<<type<<"! Will ignore this line!"<<std::endl;
        }
        if (aGSvc){
                aGSvc->set_VerboseLevel(fVerboseLevel);
                //push and call ReadCard
                fMyVGeometrySvc.push_back(aGSvc);
                fSvcName.push_back(name);
                aGSvc->ReadCard(file);
        }
}
void MyDetectorManager::ClearGeo ()
Definition at line 162 of file MyDetectorManager.cc.
References fMyVGeometrySvc, and fSvcName.
Referenced by DetectorConstruction::ReloadGeo(), and MyDetectorManagerMessenger::SetNewValue().
{
        fSvcName.clear();
        fMyVGeometrySvc.clear();
        printf("MyDetectorManager::ClearGeo()\n");
}
void MyDetectorManager::DEBUG (G4String content) [private]
Definition at line 384 of file MyDetectorManager.cc.
Referenced by GetSD(), and MyDetectorManager().
{
        G4Exception("MyDetectorManager","Run0031",
                        FatalException, content);
}
void MyDetectorManager::Digitize ()
Definition at line 375 of file MyDetectorManager.cc.
References fDMName.
Referenced by MyAnalysisSvc::EndOfEventAction().
{
        for ( int i = 0; i < fDMName.size(); i++ ){
                G4String DMName = fDMName[i];
                G4DigiManager::GetDMpointer()->Digitize(DMName);
        }
}
MyDetectorManager * MyDetectorManager::GetMyDetectorManager () [static]
Definition at line 57 of file MyDetectorManager.cc.
References fMyDetectorManager.
Referenced by SimpleGeometrySvc::ConstructVolumes(), CdcGeometrySvc::ConstructVolumes(), DetectorConstruction::DetectorConstruction(), MyAnalysisSvc::MyAnalysisSvc(), SimpleGeometrySvc::PlaceVolumes(), MyTriggerSvc::SetMyTrigger(), and PrimaryGeneratorAction::SetUniformPosition().
{
  if ( !fMyDetectorManager ){
    fMyDetectorManager = new MyDetectorManager;
  }
  return fMyDetectorManager;
}
SimpleGeometryParameter* MyDetectorManager::GetParaFromVolume (G4String name) [inline]
Definition at line 104 of file MyDetectorManager.hh.
References fMyVGeometrySvc, and SimpleGeometryParameter::get_VolIndex().
Referenced by SimpleGeometrySvc::PlaceVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{
                        SimpleGeometryParameter* pointer = 0;
                        for ( int i = 0; i < fMyVGeometrySvc.size(); i++ ){
                                SimpleGeometryParameter* ipointer = (SimpleGeometryParameter*) fMyVGeometrySvc[i]->get_GeometryParameter();
                                if ( ipointer->get_VolIndex(name) >= 0 ){
                                        pointer = ipointer;
                                        break;
                                }
                        }
                        return pointer;
                }
G4VSensitiveDetector * MyDetectorManager::GetSD (G4String VolName, G4String SDName)
Definition at line 319 of file MyDetectorManager.cc.
References DEBUG(), fSDList, fSDName, and fVolName.
{
        //check SDName
        G4String newVolName;
        G4String newSDName;
        size_t sLast = SDName.last('/');
        if(sLast==std::string::npos){ // Sensitive Detector name only
                newVolName = VolName;
                newSDName = SDName;
        }
        else{
                newVolName = SDName.substr(0,sLast);
                newSDName = SDName.substr(sLast+1,SDName.length()-sLast-1);
        }
        //Search for (VolName, SDName).
        MySD* aMySD = 0;
        //std::cout<<"Searching for ["<<newVolName<<","<<newSDName<<"]"<<std::endl;
        for ( int i = 0; i < fSDList.size(); i++ ){
                //std::cout<<"["<<fVolName[i]<<","<<fSDName[i]<<"]"<<std::endl;
                if ( fSDName[i] == newSDName ){
                        //std::cout<<"VolName Matched!"<<std::endl;
                        if ( fVolName[i] == newVolName ){
                                //std::cout<<"SDName Matched!"<<std::endl;
                                aMySD = fSDList[i];
                                if ( !aMySD ) DEBUG("An element of fSDList is zero!"); //G4Exception would be called
                                break;
                        }
                }
        }
        //if not found ...
        G4VSensitiveDetector* aG4SD = 0;
        if ( !aMySD ){
        }
        else {
                aG4SD = dynamic_cast<G4VSensitiveDetector*> (aMySD);
                if ( aG4SD == NULL ){
                        G4String content = "Cannot convert "+newSDName+" from G4VSensitiveDetector* to MySD* at construction";
                        DEBUG(content);
                }
        }
        return aG4SD;
}
G4VSensitiveDetector * MyDetectorManager::GetSD (G4String VolName, G4String SDName, MyVGeometrySvc * pointer)
Definition at line 217 of file MyDetectorManager.cc.
References DEBUG(), fMyVGeometrySvc, fSDList, fSDman, fSDName, fVerboseLevel, fVolName, MyVGeometrySvc::get_GeometryParameter(), MYDETM_LINEINFO, MySD::set_GeometryParameter(), and MySD::SetVerbose().
Referenced by SimpleGeometrySvc::ConstructVolumes(), CdcGeometrySvc::ConstructVolumes(), and MyTriggerSvc::SetMyTrigger().
{
        MYDETM_LINEINFO()
        MyVGeometryParameter* pPara = pointer->get_GeometryParameter();
        //Safety check
        int index = -1;
        for ( int i = 0; i < fMyVGeometrySvc.size(); i++ ){
                if ( (void*) pointer == (void*) fMyVGeometrySvc[i]) index = i;
        }
        if (index == -1){
                std::cout<<"WRONG!!! unrecorded MyVGeometrySvc pointer!!!"<<std::endl;
    G4Exception("MyDetectorManager::GetSD()","Run0031",
        FatalException, "unrecorded MyVGeometrySvc pointer.");
        }
        //check SDName
        G4String newVolName;
        G4String newSDName;
        size_t sLast = SDName.last('/');
        if(sLast==std::string::npos){ // Sensitive Detector name only
                newVolName = VolName;
                newSDName = SDName;
        }
        else{
                newVolName = SDName.substr(0,sLast);
                newSDName = SDName.substr(sLast+1,SDName.length()-sLast-1);
        }
        //Search for (VolName, SDName).
        MYDETM_LINEINFO()
        MySD* aMySD = 0;
        for ( int i = 0; i < fSDList.size(); i++ ){
                if ( fSDName[i] == newSDName ){
                        if ( fVolName[i] == newVolName ){
                                aMySD = fSDList[i];
                                if ( !aMySD ) DEBUG("An element of fSDList is zero!"); //G4Exception would be called
                                //Found it. Modify
                                aMySD->set_GeometryParameter(pPara);
                                break;
                        }
                }
        }
        MYDETM_LINEINFO()
        //if not found, then create a new one w.r.t SDName
        G4VSensitiveDetector* aG4SD = 0;
        if ( !aMySD ){
                G4String FullSDName = newVolName + "/" + newSDName;
                if ( newSDName == "CdcSD" ){
                        aG4SD = new CdcSD( FullSDName, pPara );
                        fSDman->AddNewDetector( aG4SD );
                }
                else if ( newSDName == "CdcSimpleSD" ){
                        aG4SD = new CdcSimpleSD( FullSDName, pPara );
                        fSDman->AddNewDetector( aG4SD );
                }
                else if ( newSDName == "KillerSD" ){
                        aG4SD = new KillerSD( FullSDName, pPara );
                        fSDman->AddNewDetector( aG4SD );
                }
                else if ( newSDName == "CdcIonSD" ){
                        aG4SD = new CdcIonSD( FullSDName, pPara );
                        fSDman->AddNewDetector( aG4SD );
                }
                else if ( newSDName == "MonitorSD" ){
                        aG4SD = new MonitorSD( FullSDName, pPara );
                        fSDman->AddNewDetector( aG4SD );
                }
                else if ( newSDName == "CdcLayerSD" ){
                        aG4SD = new CdcLayerSD( FullSDName, pPara );
                        fSDman->AddNewDetector( aG4SD );
                }
                else if ( newSDName != "none" ) {//"none" means the user does not want to use a SD. aSD set to 0 and will not be pushed to vecto
                        DEBUG("Sensitive detector type " + newSDName + " is not supported yet!!!");
                }
                if ( aG4SD ){
                        MySD* aSD = dynamic_cast<MySD*> (aG4SD);
                        aSD->SetVerbose(fVerboseLevel);
                        if ( aSD == NULL ){
                                G4String content = "Cannot convert "+newSDName+" from G4VSensitiveDetector* to MySD* at construction";
                                DEBUG(content);
                        }
                        fSDList.push_back(aSD);
                        fVolName.push_back(newVolName);
                        fSDName.push_back(newSDName);
                }
        }
        MYDETM_LINEINFO()
        else {
                aMySD->SetVerbose(fVerboseLevel);
                aG4SD = dynamic_cast<G4VSensitiveDetector*> (aMySD);
                if ( aG4SD == NULL ){
                        G4String content = "Cannot convert "+newSDName+" from G4VSensitiveDetector* to MySD* at construction";
                        DEBUG(content);
                }
        }
        MYDETM_LINEINFO()
        return aG4SD;
}
MyVGeometrySvc* MyDetectorManager::GetSvc (G4String name) [inline]
Definition at line 92 of file MyDetectorManager.hh.
References fMyVGeometrySvc, and fSvcName.
Referenced by PrimaryGeneratorAction::SetUniformPosition().
{
                        MyVGeometrySvc* pointer = 0;
                        for ( int i = 0; i < fSvcName.size(); i++ ){
                                if ( fSvcName[i] == name ){
                                        pointer = fMyVGeometrySvc[i];
                                        break;
                                }
                        }
                        return pointer;
                }
void MyDetectorManager::ReadCard (G4String file_name)
Definition at line 72 of file MyDetectorManager.cc.
References fMyVGeometrySvc, fSvcName, fVerboseLevel, MyVGeometrySvc::ReadCard(), and MyVGeometrySvc::set_VerboseLevel().
Referenced by DetectorConstruction::Construct(), DetectorConstruction::ReloadGeo(), and MyDetectorManagerMessenger::SetNewValue().
{
        //delete and clear
        for ( int i = 0; i < fMyVGeometrySvc.size(); i++ ){
                if (fMyVGeometrySvc[i]) delete (fMyVGeometrySvc[i]);
        }
        fMyVGeometrySvc.clear();
        fSvcName.clear();
        //get the file
        if(file_name[0] != '/'){ // Relative Dir
                G4String dir_name = getenv("CONFIGUREROOT");
                if (dir_name[dir_name.size()-1] != '/') dir_name.append("/");
                file_name = dir_name + file_name;
        }
        //std::cout<<"MyDetectorManager: Reading \""<<file_name<<"\""<<std::endl;
  std::ifstream fin_card(file_name);
  if ( !fin_card ){
    std::cout<<"Geometry file: "<<file_name<<" is not available!!!"<<std::endl;
    G4Exception("MyDetectorManager::ReadCard()","Run0031",
        FatalException, "Geometry file is not available.");
  }
        //read line by line
  std::stringstream buf_card;
  std::string s_card;
  while(getline(fin_card,s_card)){
    buf_card.str("");
    buf_card.clear();
    buf_card<<s_card;
    const char* c = s_card.c_str();
    int length = strlen(c);
    int offset = 0;
    for ( ; offset < length; offset++ ){
      if ( c[offset] != ' ' ) break;
    }
    if ( c[offset] == '#' ) continue;
    else if ( c[offset] == '/' && c[offset+1] == '/' ) continue;
    else if ( length - offset == 0 ) continue;
                G4String name, type, file;
                MyVGeometrySvc* aGSvc = 0;
                buf_card>>name;
                //std::cout<<"MyDetectorManager: "<<buf_card.str()<<std::endl;
                if ( name == "VerboseLevel" ){
                        buf_card>>fVerboseLevel;
                }
                else{
                        buf_card>>type>>file;
                        if( type == "Simple" ){
                                aGSvc = new SimpleGeometrySvc( name );
                        }
                        else if( type == "Cdc" ){
                                aGSvc = new CdcGeometrySvc( name );
                        }
                        else{
                                std::cout<<"In MyDetectorManager::ReadCard, unsupported GeometrySvc type: "<<type<<"! Will ignore this line!"<<std::endl;
                        }
                }
                if (aGSvc){
                        aGSvc->set_VerboseLevel(fVerboseLevel);
                        //push and call ReadCard
                        fMyVGeometrySvc.push_back(aGSvc);
                        fSvcName.push_back(name);
                        aGSvc->ReadCard(file);
                }
        }
}
void MyDetectorManager::ReadOutputCard (G4String file_name)
Definition at line 187 of file MyDetectorManager.cc.
References fSDList.
Referenced by MyAnalysisSvc::set_out_card().
{
        for ( int i = 0; i < fSDList.size(); i++ ){
                fSDList[i]->ReadOutputCard(file_name);
        }
}
void MyDetectorManager::RegistorDM (G4String DMName)
Definition at line 368 of file MyDetectorManager.cc.
References fDMName.
{
        if ( DMName != "none" ) fDMName.push_back(DMName);
}
void MyDetectorManager::SetBranch (void)
Definition at line 195 of file MyDetectorManager.cc.
References fSDList.
Referenced by MyAnalysisSvc::BeginOfRunAction().
{
        for ( int i = 0; i < fSDList.size(); i++ ){
                fSDList[i]->SetBranch();
        }
}
G4VPhysicalVolume * MyDetectorManager::SetGeometry ()
Definition at line 172 of file MyDetectorManager.cc.
References AddGeo(), and fMyVGeometrySvc.
Referenced by DetectorConstruction::ConstructDetector().
{
        if (fMyVGeometrySvc.size()==0){
                AddGeo("default","world_default","Simple");
        }
        G4VPhysicalVolume* vol_world = (fMyVGeometrySvc[0])->SetGeometry();
        for ( int i = 1; i < fMyVGeometrySvc.size(); i++ ){
                (fMyVGeometrySvc[i])->SetGeometry();
        }
        return vol_world;
}
void MyDetectorManager::SetVerbose (int val) [inline]
Definition at line 124 of file MyDetectorManager.hh.
References fVerboseLevel.
{fVerboseLevel = val;};
Member Data Documentation
std::vector<G4String> MyDetectorManager::fDMName [private]
Definition at line 143 of file MyDetectorManager.hh.
Referenced by Digitize(), and RegistorDM().
MyDetectorManager * MyDetectorManager::fMyDetectorManager = 0 [static, private]
Definition at line 132 of file MyDetectorManager.hh.
Referenced by GetMyDetectorManager(), and MyDetectorManager().
std::vector<MyVGeometrySvc*> MyDetectorManager::fMyVGeometrySvc [private]
Definition at line 148 of file MyDetectorManager.hh.
Referenced by AddGeo(), ClearGeo(), GetParaFromVolume(), GetSD(), GetSvc(), ReadCard(), and SetGeometry().
std::vector<MySD*> MyDetectorManager::fSDList [private]
Definition at line 140 of file MyDetectorManager.hh.
Referenced by GetSD(), ReadOutputCard(), and SetBranch().
G4SDManager* MyDetectorManager::fSDman [private]
Definition at line 138 of file MyDetectorManager.hh.
Referenced by GetSD(), and MyDetectorManager().
std::vector<G4String> MyDetectorManager::fSDName [private]
Definition at line 141 of file MyDetectorManager.hh.
Referenced by GetSD().
std::vector<G4String> MyDetectorManager::fSvcName [private]
Definition at line 149 of file MyDetectorManager.hh.
Referenced by AddGeo(), ClearGeo(), GetSvc(), and ReadCard().
int MyDetectorManager::fVerboseLevel [private]
Definition at line 147 of file MyDetectorManager.hh.
Referenced by AddGeo(), GetSD(), ReadCard(), and SetVerbose().
std::vector<G4String> MyDetectorManager::fVolName [private]
Definition at line 142 of file MyDetectorManager.hh.
Referenced by GetSD().
MyDetectorManagerMessenger* MyDetectorManager::m_MyDetectorManagerMessenger [private]
Definition at line 134 of file MyDetectorManager.hh.
Referenced by MyDetectorManager(), and ~MyDetectorManager().
The documentation for this class was generated from the following files:
include/MyDetectorManager.hh
src/MyDetectorManager.cc