g4sim: MySD Class Reference
MySD Class Reference
#include <MySD.hh>
Public Member Functions
MySD (G4String, MyVGeometryParameter *)
virtual ~MySD ()
void SetVerbose (int val)
virtual void ReadOutputCard (G4String)
virtual void SetBranch (void)
G4String get_VolName ()
int get_VerboseLevel ()
MyVGeometryParameter * get_GeometryParameter ()
void set_VerboseLevel (int val)
void set_GeometryParameter (MyVGeometryParameter *val)
Private Attributes
int fVerboseLevel
MyVGeometryParameter * m_GeometryParameter
G4String m_VolumeName
Detailed Description
Definition at line 16 of file MySD.hh.
Constructor & Destructor Documentation
MySD::MySD (G4String name, MyVGeometryParameter * pointer)
Definition at line 3 of file MySD.cc.
References fVerboseLevel, and m_VolumeName.
        :G4VSensitiveDetector(name), m_GeometryParameter(pointer)
{
        fVerboseLevel = 0;
        G4String HCName = name.c_str();
        char* c = const_cast<char*> (HCName.c_str());
        for ( int i = 0; i < HCName.length(); i++ ){
                if ( c[i] == '/' ) c[i] = '_';
        }
  collectionName.insert(c); //Make the HC name unique, so that one can keep many copies of the same SD during a run
        m_VolumeName = GetPathName();
        char *pFast, *pSlow, *pC;
        pC = pFast = pSlow = const_cast<char*> (m_VolumeName.c_str());
        while( '\0' != *pFast ){
                if ( *pFast == '/' ) pFast++;
                else{
                        *pSlow = *pFast;
                        pSlow++;
                        pFast++;
                }
        }
        *pSlow = '\0';
        m_VolumeName = pC;
}
MySD::~MySD () [virtual]
Definition at line 28 of file MySD.cc.
{}
Member Function Documentation
MyVGeometryParameter* MySD::get_GeometryParameter () [inline]
Reimplemented in CdcIonSD, CdcSD, and CdcSimpleSD.
Definition at line 28 of file MySD.hh.
References m_GeometryParameter.
{ return m_GeometryParameter; }
int MySD::get_VerboseLevel () [inline]
Definition at line 27 of file MySD.hh.
References fVerboseLevel.
Referenced by CdcIonSD::CalculateHitInfo(), CdcSD::FindClosestPoint(), CdcSimpleSD::ProcessHits(), CdcSD::ProcessHits(), CdcIonSD::ProcessHits(), CdcSimpleSD::ShowOutCard(), and CdcSD::ShowOutCard().
{ return fVerboseLevel; }
G4String MySD::get_VolName () [inline]
Definition at line 26 of file MySD.hh.
References m_VolumeName.
Referenced by MonitorSD::ReadOutputCard(), KillerSD::ReadOutputCard(), CdcSimpleSD::ReadOutputCard(), CdcSD::ReadOutputCard(), CdcLayerSD::ReadOutputCard(), CdcIonSD::ReadOutputCard(), MonitorSD::SetBranch(), CdcSimpleSD::SetBranch(), CdcSD::SetBranch(), CdcLayerSD::SetBranch(), CdcIonSD::SetBranch(), MonitorSD::ShowOutCard(), KillerSD::ShowOutCard(), CdcSimpleSD::ShowOutCard(), CdcSD::ShowOutCard(), CdcLayerSD::ShowOutCard(), and CdcIonSD::ShowOutCard().
{ return m_VolumeName; }
virtual void MySD::ReadOutputCard (G4String) [inline, virtual]
Reimplemented in CdcIonSD, CdcLayerSD, CdcSD, CdcSimpleSD, KillerSD, and MonitorSD.
Definition at line 22 of file MySD.hh.
{};
void MySD::set_GeometryParameter (MyVGeometryParameter * val) [inline]
Definition at line 32 of file MySD.hh.
References m_GeometryParameter.
Referenced by MyDetectorManager::GetSD().
{ m_GeometryParameter = val; }
void MySD::set_VerboseLevel (int val) [inline]
Definition at line 31 of file MySD.hh.
References fVerboseLevel.
{ fVerboseLevel = val; }
virtual void MySD::SetBranch (void) [inline, virtual]
Reimplemented in CdcIonSD, CdcLayerSD, CdcSD, CdcSimpleSD, KillerSD, and MonitorSD.
Definition at line 23 of file MySD.hh.
{};
void MySD::SetVerbose (int val) [inline]
Definition at line 21 of file MySD.hh.
References fVerboseLevel.
Referenced by MyDetectorManager::GetSD().
{fVerboseLevel = val;}
Field Documentation
int MySD::fVerboseLevel [private]
Definition at line 35 of file MySD.hh.
Referenced by get_VerboseLevel(), MySD(), set_VerboseLevel(), and SetVerbose().
MyVGeometryParameter* MySD::m_GeometryParameter [private]
Reimplemented in CdcIonSD, CdcLayerSD, CdcSD, and CdcSimpleSD.
Definition at line 36 of file MySD.hh.
Referenced by get_GeometryParameter(), and set_GeometryParameter().
G4String MySD::m_VolumeName [private]
Definition at line 37 of file MySD.hh.
Referenced by get_VolName(), and MySD().
The documentation for this class was generated from the following files:
include/MySD.hh
src/MySD.cc