g4sim: MyAnalysisSvc Class Reference
MyAnalysisSvc Class Reference
#include <MyAnalysisSvc.hh>
Public Member Functions
MyAnalysisSvc ()
virtual ~MyAnalysisSvc ()
void set_out_card (G4String filename)
void set_PrintModulo (int i)
void set_ofile_name (G4String &val)
void set_tree_name (G4String &val)
void set_run_name (G4String &val)
void set_minT (double val)
void set_maxT (double val)
void ReadOutputCard (G4String filename)
int GetRunID ()
void BeginOfRunAction ()
void EndOfRunAction (const G4Run *)
void PreUserTrackingAction (const G4Track *)
void PostUserTrackingAction (const G4Track *)
void BeginOfEventAction ()
void EndOfEventAction (const G4Event *)
void InitialStepAction (const G4Step *)
void SteppingAction (const G4Step *)
void ASDI (G4String)
void PSDI (G4String)
Static Public Member Functions
static MyAnalysisSvc * GetMyAnalysisSvc ()
Private Attributes
MyAnalysisSvcMessenger * pMyAnalysisSvcMessenger
G4String out_card
G4String run_name
G4String ofile_name
G4String tree_name
int run_num
int fAutoSave
int fCircular
int fVerbose
int fPrintModulo
double m_minT
double m_maxT
clock_t t_begin
clock_t t_end
double event_start_time
MyRoot * pMyRoot
EventHeaderSvc * pEventHeaderSvc
MyDetectorManager * pMyDetectorManager
McTruthSvc * pMcTruthSvc
ProcessCountingSvc * pProcessCountingSvc
MyTriggerSvc * pMyTriggerSvc
PrimaryGeneratorAction * pPrimaryGeneratorAction
MyProcessManager * pMyProcessManager
Static Private Attributes
static MyAnalysisSvc * fMyAnalysisSvc = 0
Detailed Description
Definition at line 28 of file MyAnalysisSvc.hh.
Constructor & Destructor Documentation
MyAnalysisSvc::MyAnalysisSvc ()
Definition at line 31 of file MyAnalysisSvc.cc.
References fMyAnalysisSvc, fPrintModulo, EventHeaderSvc::GetEventHeaderSvc(), McTruthSvc::GetMcTruthSvc(), MyDetectorManager::GetMyDetectorManager(), MyProcessManager::GetMyProcessManager(), MyRoot::GetMyRoot(), MyTriggerSvc::GetMyTriggerSvc(), PrimaryGeneratorAction::GetPrimaryGeneratorAction(), ProcessCountingSvc::GetProcessCountingSvc(), m_maxT, m_minT, ofile_name, out_card, pEventHeaderSvc, pMcTruthSvc, pMyAnalysisSvcMessenger, pMyDetectorManager, pMyProcessManager, pMyRoot, pMyTriggerSvc, pPrimaryGeneratorAction, pProcessCountingSvc, run_name, and set_out_card().
{
        if (fMyAnalysisSvc){
                G4Exception("MyAnalysisSvc::MyAnalysisSvc()","Run0031",
                                FatalException, "MyAnalysisSvc constructed twice.");
        }
        fMyAnalysisSvc = this;
        //get pointers
        pMyAnalysisSvcMessenger = new MyAnalysisSvcMessenger(this);
        pMyRoot = MyRoot::GetMyRoot();
        pMyDetectorManager = MyDetectorManager::GetMyDetectorManager();
        pEventHeaderSvc = EventHeaderSvc::GetEventHeaderSvc();
        pMcTruthSvc = McTruthSvc::GetMcTruthSvc();
        pProcessCountingSvc = ProcessCountingSvc::GetProcessCountingSvc();
        pMyTriggerSvc = MyTriggerSvc::GetMyTriggerSvc();
        pPrimaryGeneratorAction  = PrimaryGeneratorAction::GetPrimaryGeneratorAction();
        pMyProcessManager = MyProcessManager::GetMyProcessManager();
        //default logfile
        run_name = getenv("RUNNAMEROOT");
        //default output file
        ofile_name = getenv("OFILENAMEROOT");
        //set default output card, read it, and inform relative files.
        std::string out_card = getenv("OUTCARDROOT");
        set_out_card(out_card.c_str());
        //default trigger card
        m_minT = -1;
        m_maxT = -1;
        fPrintModulo = 100;
}
MyAnalysisSvc::~MyAnalysisSvc () [virtual]
Definition at line 63 of file MyAnalysisSvc.cc.
References pMyAnalysisSvcMessenger.
{
        delete pMyAnalysisSvcMessenger;
}
Member Function Documentation
void MyAnalysisSvc::ASDI (G4String name)
Definition at line 212 of file MyAnalysisSvc.cc.
References ProcessCountingSvc::AddASDI(), and pProcessCountingSvc.
{
        pProcessCountingSvc->AddASDI(name);
}
void MyAnalysisSvc::BeginOfEventAction ()
Definition at line 139 of file MyAnalysisSvc.cc.
References event_start_time, ProcessCountingSvc::Initialize(), McTruthSvc::Initialize(), pMcTruthSvc, and pProcessCountingSvc.
Referenced by EventAction::BeginOfEventAction().
{
        event_start_time = (double) clock();
//      std::cout<<"event_start_time = "<<event_start_time<<std::endl;
        //Initialize
        pMcTruthSvc->Initialize();
        pProcessCountingSvc->Initialize();
}
void MyAnalysisSvc::BeginOfRunAction ()
Definition at line 94 of file MyAnalysisSvc.cc.
References LogSvc::AddLog(), MyRoot::CreateTree(), fCircular, LogSvc::GetLogSvc(), ofile_name, MyRoot::OpenFile(), pEventHeaderSvc, pMcTruthSvc, pMyDetectorManager, pMyRoot, pProcessCountingSvc, run_name, run_num, ProcessCountingSvc::SetBranch(), McTruthSvc::SetBranch(), EventHeaderSvc::SetBranch(), MyDetectorManager::SetBranch(), LogSvc::SetLogFile(), t_begin, and tree_name.
Referenced by RunAction::BeginOfRunAction().
{
        //deal with log
        std::string log_name = getenv("LOGFILEROOT");
        if ( std::strlen(log_name.c_str()) != 0 ){
                LogSvc::GetLogSvc()->SetLogFile( log_name.c_str() );
        }
        run_num = LogSvc::GetLogSvc()->AddLog( run_name.c_str() );
        std::cout<<"logfile finished for "<<run_name<<", "<<run_num<<std::endl;
        //set root file
        pMyRoot->OpenFile(ofile_name);
        pMyRoot->CreateTree(tree_name, fCircular);
        //set branches
        pMyDetectorManager->SetBranch();
        pEventHeaderSvc->SetBranch();
        pMcTruthSvc->SetBranch();
        pProcessCountingSvc->SetBranch();
        t_begin = (double)clock();
        std::cout<<"evt_num  memSize  time  R0  R1"<<std::endl;
        std::cout<<"         MB       sec         "<<std::endl;
}
void MyAnalysisSvc::EndOfEventAction (const G4Event * evt)
Definition at line 147 of file MyAnalysisSvc.cc.
References MyDetectorManager::Digitize(), fAutoSave, MyRoot::Fill(), MyRoot::FlushBaskets(), fPrintModulo, PrimaryGeneratorAction::get_extra(), EventHeaderSvc::get_R0(), EventHeaderSvc::get_R1(), MyProcessManager::GetMemorySize(), pEventHeaderSvc, pMyDetectorManager, pMyProcessManager, pMyRoot, pMyTriggerSvc, pPrimaryGeneratorAction, run_num, MyRoot::Save(), EventHeaderSvc::SetValue(), t_begin, and MyTriggerSvc::TriggerIt().
Referenced by EventAction::EndOfEventAction().
{
        int evt_num = evt->GetEventID();
        //Digitze
        pMyDetectorManager->Digitize();
        //Set event header
        double weight = 1;
        void *result = pPrimaryGeneratorAction->get_extra("weight");
        if (result) weight = *((double*)result);
        pEventHeaderSvc->SetValue(evt,run_num,weight);
        //Fill
        if ( pMyTriggerSvc->TriggerIt(evt) ) pMyRoot->Fill();
        //AutoSave
        if (fAutoSave){
                if ( evt_num%fAutoSave == 0 ){
                        pMyRoot->Save();
                        int nBytes = pMyRoot->FlushBaskets();
                        std::cout<<"Event "<<evt_num<<", "<<nBytes<<"Bytes data written"<<std::endl;
                }
        }
        //print per event (modulo n)
        if (evt_num%fPrintModulo == 0) {
                std::cout <<evt_num
                   <<"  "<<pMyProcessManager->GetMemorySize()
                   <<"  "<<(((double)clock()-t_begin)/CLOCKS_PER_SEC)
                   <<"  "<<pEventHeaderSvc->get_R0()
                   <<"  "<<pEventHeaderSvc->get_R1()
                   <<std::endl;
        }
}
void MyAnalysisSvc::EndOfRunAction (const G4Run * aRun)
Definition at line 128 of file MyAnalysisSvc.cc.
References MyRoot::Close(), pMyRoot, t_begin, t_end, and MyRoot::Write().
Referenced by RunAction::EndOfRunAction().
{
        int NbOfEvents = aRun->GetNumberOfEvent();
        t_end = (double)clock();
        std::cout<<"\n##############################################"<<std::endl;
        std::cout<<"TOTAL TIME COST IS:  "<<(double)(t_end-t_begin)/CLOCKS_PER_SEC*1000<<"ms"<<std::endl;
        std::cout<<"TIME COST PER EVENT: "<<(double)(t_end-t_begin)/CLOCKS_PER_SEC/NbOfEvents*1000<<"ms"<<std::endl;
        std::cout<<"##############################################\n"<<std::endl;
        pMyRoot->Write();
        pMyRoot->Close();
}
MyAnalysisSvc * MyAnalysisSvc::GetMyAnalysisSvc () [static]
Definition at line 68 of file MyAnalysisSvc.cc.
References fMyAnalysisSvc.
Referenced by EventAction::BeginOfEventAction(), RunAction::BeginOfRunAction(), EventAction::EndOfEventAction(), RunAction::EndOfRunAction(), MyTrackingAction::PostUserTrackingAction(), MyTrackingAction::PreUserTrackingAction(), and SteppingAction::UserSteppingAction().
{
        if ( !fMyAnalysisSvc ){
                fMyAnalysisSvc = new MyAnalysisSvc;
        }
        return fMyAnalysisSvc;
}
int MyAnalysisSvc::GetRunID () [inline]
Definition at line 47 of file MyAnalysisSvc.hh.
References run_num.
{return run_num;};
void MyAnalysisSvc::InitialStepAction (const G4Step * aStep)
Definition at line 208 of file MyAnalysisSvc.cc.
References ProcessCountingSvc::InitialStep(), and pProcessCountingSvc.
{
        pProcessCountingSvc->InitialStep(aStep);
}
void MyAnalysisSvc::PostUserTrackingAction (const G4Track * aTrack)
Definition at line 123 of file MyAnalysisSvc.cc.
References pMcTruthSvc, and McTruthSvc::SetValuePost().
Referenced by MyTrackingAction::PostUserTrackingAction().
{
        //set McTruth
        pMcTruthSvc->SetValuePost(aTrack);
}
void MyAnalysisSvc::PreUserTrackingAction (const G4Track * aTrack)
Definition at line 118 of file MyAnalysisSvc.cc.
References pMcTruthSvc, and McTruthSvc::SetValuePre().
Referenced by MyTrackingAction::PreUserTrackingAction().
{
        //set McTruth
        pMcTruthSvc->SetValuePre(aTrack);
}
void MyAnalysisSvc::PSDI (G4String name)
Definition at line 216 of file MyAnalysisSvc.cc.
References ProcessCountingSvc::AddPSDI(), and pProcessCountingSvc.
{
        pProcessCountingSvc->AddPSDI(name);
}
void MyAnalysisSvc::ReadOutputCard (G4String filename)
Definition at line 220 of file MyAnalysisSvc.cc.
References fAutoSave, fCircular, fPrintModulo, fVerbose, and tree_name.
Referenced by set_out_card().
{
        std::ifstream fin_card(file_name);
        if(!fin_card){
                std::cout<<"In MyAnalysisSvc::ReadOutputCard, cannot open "<<file_name<<"!!!"<<std::endl;
                G4Exception("MyAnalysisSvc::ReadOutputCard()",
                                "InvalidSetup", FatalException,
                                "cannot find output card");
        }
        std::stringstream buf_card;
        std::string s_card;
        bool find_tree_name = false;
        bool find_AutoSave = false;
        bool find_Circular = false;
        bool find_Verbose = false;
        bool find_PrintModulo = false;
        while(getline(fin_card,s_card)){
                buf_card.str("");
                buf_card.clear();
                buf_card<<s_card;
                //eleminate useless lines
                const char* c_card = s_card.c_str();
                int length = strlen(c_card);
                int offset = 0;
                for ( ; offset < length; offset++ ){
                        if ( c_card[offset] != ' ' ) break;
                }
                if ( c_card[offset] == '#' || (c_card[offset] == '/' && c_card[offset+1] == '/') || length - offset == 0 ){
                        continue;
                }
                std::string name;
                buf_card>>name;
                if ( name == "tree_name" ){
                        buf_card>>tree_name;
                        std::cout<<"In MyAnalysisSvc::ReadOutputCard, tree_name will be set to "<<tree_name<<std::endl;
                        find_tree_name = true;
                }
                else if ( name == "AutoSave" ){
                        buf_card>>fAutoSave;
                        std::cout<<"In MyAnalysisSvc::ReadOutputCard, fAutoSave will be set to "<<fAutoSave<<std::endl;
                        find_AutoSave = true;
                }
                else if ( name == "Circular" ){
                        buf_card>>fCircular;
                        std::cout<<"In MyAnalysisSvc::ReadOutputCard, fCircular will be set to "<<fCircular<<std::endl;
                        find_Circular = true;
                }
                else if ( name == "Verbose" ){
                        buf_card>>fVerbose;
                        std::cout<<"In MyAnalysisSvc::ReadOutputCard, fVerbose will be set to "<<fVerbose<<std::endl;
                        find_Verbose = true;
                }
                else if ( name == "PrintModulo" ){
                        buf_card>>fPrintModulo;
                        std::cout<<"In MyAnalysisSvc::ReadOutputCard, fPrintModulo will be set to "<<fPrintModulo<<std::endl;
                        find_PrintModulo = true;
                }
                if ( find_Verbose && find_PrintModulo && find_Circular && find_AutoSave && find_tree_name ) break;
        }
        if (!find_tree_name){
                std::cout<<"In MyAnalysisSvc::ReadOutputCard, tree_name not found in card, will be set to t as default"<<std::endl;
                tree_name = "t";
        }
        if (!find_AutoSave){
                std::cout<<"In MyAnalysisSvc::ReadOutputCard, AutoSave not found in card, will be set to 0 as default"<<std::endl;
                fAutoSave = 0;
        }
        if (!find_Circular){
                std::cout<<"In MyAnalysisSvc::ReadOutputCard, Circular not found in card, will be set to 0 as default"<<std::endl;
                fCircular = 0;
        }
        if (!find_Verbose){
                std::cout<<"In MyAnalysisSvc::ReadOutputCard, Verbose not found in card, will be set to 0 as default"<<std::endl;
                fVerbose = 0;
        }
        if (!find_PrintModulo){
                std::cout<<"In MyAnalysisSvc::ReadOutputCard, PrintModulo not found in card, will be set to 0 as default"<<std::endl;
                fPrintModulo = 100;
        }
        fin_card.close();
        buf_card.str("");
        buf_card.clear();
}
void MyAnalysisSvc::set_maxT (double val) [inline]
Definition at line 44 of file MyAnalysisSvc.hh.
References m_maxT.
Referenced by MyAnalysisSvcMessenger::SetNewValue().
{m_maxT=val;};
void MyAnalysisSvc::set_minT (double val) [inline]
Definition at line 43 of file MyAnalysisSvc.hh.
References m_minT.
Referenced by MyAnalysisSvcMessenger::SetNewValue().
{m_minT=val;};
void MyAnalysisSvc::set_ofile_name (G4String & val) [inline]
Definition at line 39 of file MyAnalysisSvc.hh.
References ofile_name.
Referenced by MyAnalysisSvcMessenger::SetNewValue().
{ ofile_name = val; };
void MyAnalysisSvc::set_out_card (G4String filename)
Definition at line 75 of file MyAnalysisSvc.cc.
References fPrintModulo, fVerbose, pEventHeaderSvc, pMcTruthSvc, pMyDetectorManager, pMyRoot, pMyTriggerSvc, pProcessCountingSvc, ReadOutputCard(), ProcessCountingSvc::ReadOutputCard(), McTruthSvc::ReadOutputCard(), MyDetectorManager::ReadOutputCard(), EventHeaderSvc::ReadOutputCard(), MyTriggerSvc::SetMyTrigger(), MyRoot::SetPrintModulo(), and MyRoot::SetVerbose().
Referenced by MyAnalysisSvc(), and MyAnalysisSvcMessenger::SetNewValue().
{
        if(file_name[0] != '/'){ // Relative Dir
                G4String dir_name = getenv("CONFIGUREROOT");
                if (dir_name[dir_name.size()-1] != '/') dir_name.append("/");
                file_name = dir_name + file_name;
        }
        //inform relative files
        pEventHeaderSvc->ReadOutputCard(file_name);
        pMyDetectorManager->ReadOutputCard(file_name);
        pMcTruthSvc->ReadOutputCard(file_name);
        pProcessCountingSvc->ReadOutputCard(file_name);
        pMyTriggerSvc->SetMyTrigger(file_name);
        //read output card
        ReadOutputCard(file_name);
        //set verbose
        pMyRoot->SetVerbose(fVerbose);
        pMyRoot->SetPrintModulo(fPrintModulo);
}
void MyAnalysisSvc::set_PrintModulo (int i) [inline]
Definition at line 37 of file MyAnalysisSvc.hh.
References fPrintModulo.
Referenced by MyAnalysisSvcMessenger::SetNewValue().
{fPrintModulo = i;};
void MyAnalysisSvc::set_run_name (G4String & val) [inline]
Definition at line 41 of file MyAnalysisSvc.hh.
References run_name.
Referenced by MyAnalysisSvcMessenger::SetNewValue().
{ run_name = val; };
void MyAnalysisSvc::set_tree_name (G4String & val) [inline]
Definition at line 40 of file MyAnalysisSvc.hh.
References tree_name.
Referenced by MyAnalysisSvcMessenger::SetNewValue().
{ tree_name = val; };
void MyAnalysisSvc::SteppingAction (const G4Step * aStep)
Definition at line 180 of file MyAnalysisSvc.cc.
References event_start_time, m_maxT, m_minT, pProcessCountingSvc, and ProcessCountingSvc::SetValue().
Referenced by SteppingAction::UserSteppingAction().
{
//    CLHEP::HepRandom::showEngineStatus();
        //set ProcessCounting
        double current_time = (double) clock();
//      std::cout<<"current_time = "<<current_time<<", deltaT = "<<(current_time - event_start_time)/CLOCKS_PER_SEC<<std::endl;
        pProcessCountingSvc->SetValue(aStep);
        G4Track* aTrack = aStep->GetTrack() ;
        G4int nSteps = aTrack->GetCurrentStepNumber();
        bool needStopAndKill = false;
        if (nSteps>2e5){
                std::cout<<"### This track is killed for that nSteps>2e5 ###"<<std::endl;
                needStopAndKill = true;
        }
        G4double globalT=aTrack->GetGlobalTime();//Time since the event in which the track belongs is created
        if ((m_minT>=0&&m_minT>globalT)&&(m_maxT>=0&&m_maxT<globalT)){
                std::cout<<"### This track is killed for that globalT < "<<m_minT<<" || globalT > "<<m_maxT<<" ###"<<std::endl;
                needStopAndKill = true;
        }
        if (( current_time - event_start_time > 5*CLOCKS_PER_SEC)){
                std::cout<<"### This track is killed for that elapsed time in this event is larger than 5 sec ###"<<std::endl;
                needStopAndKill = true;
        }
        if (needStopAndKill){
                aTrack->SetTrackStatus(fStopAndKill);
                std::cout<<" => ["<<aTrack->GetTrackID()<<"]: "<<aTrack->GetParticleDefinition()->GetParticleName()<<", "<<G4BestUnit(aStep->GetPreStepPoint()->GetKineticEnergy(),"Energy")<<", @ \""<<aStep->GetPreStepPoint()->GetTouchable()->GetVolume(0)->GetName()<<"\""<<std::endl;
        }
}
Member Data Documentation
double MyAnalysisSvc::event_start_time [private]
Definition at line 79 of file MyAnalysisSvc.hh.
Referenced by BeginOfEventAction(), and SteppingAction().
int MyAnalysisSvc::fAutoSave [private]
Definition at line 69 of file MyAnalysisSvc.hh.
Referenced by EndOfEventAction(), and ReadOutputCard().
int MyAnalysisSvc::fCircular [private]
Definition at line 70 of file MyAnalysisSvc.hh.
Referenced by BeginOfRunAction(), and ReadOutputCard().
MyAnalysisSvc * MyAnalysisSvc::fMyAnalysisSvc = 0 [static, private]
Definition at line 61 of file MyAnalysisSvc.hh.
Referenced by GetMyAnalysisSvc(), and MyAnalysisSvc().
int MyAnalysisSvc::fPrintModulo [private]
Definition at line 72 of file MyAnalysisSvc.hh.
Referenced by EndOfEventAction(), MyAnalysisSvc(), ReadOutputCard(), set_out_card(), and set_PrintModulo().
int MyAnalysisSvc::fVerbose [private]
Definition at line 71 of file MyAnalysisSvc.hh.
Referenced by ReadOutputCard(), and set_out_card().
double MyAnalysisSvc::m_maxT [private]
Definition at line 75 of file MyAnalysisSvc.hh.
Referenced by MyAnalysisSvc(), set_maxT(), and SteppingAction().
double MyAnalysisSvc::m_minT [private]
Definition at line 74 of file MyAnalysisSvc.hh.
Referenced by MyAnalysisSvc(), set_minT(), and SteppingAction().
G4String MyAnalysisSvc::ofile_name [private]
Definition at line 66 of file MyAnalysisSvc.hh.
Referenced by BeginOfRunAction(), MyAnalysisSvc(), and set_ofile_name().
G4String MyAnalysisSvc::out_card [private]
Definition at line 64 of file MyAnalysisSvc.hh.
Referenced by MyAnalysisSvc().
EventHeaderSvc* MyAnalysisSvc::pEventHeaderSvc [private]
Definition at line 82 of file MyAnalysisSvc.hh.
Referenced by BeginOfRunAction(), EndOfEventAction(), MyAnalysisSvc(), and set_out_card().
McTruthSvc* MyAnalysisSvc::pMcTruthSvc [private]
Definition at line 84 of file MyAnalysisSvc.hh.
Referenced by BeginOfEventAction(), BeginOfRunAction(), MyAnalysisSvc(), PostUserTrackingAction(), PreUserTrackingAction(), and set_out_card().
MyAnalysisSvcMessenger* MyAnalysisSvc::pMyAnalysisSvcMessenger [private]
Definition at line 62 of file MyAnalysisSvc.hh.
Referenced by MyAnalysisSvc(), and ~MyAnalysisSvc().
MyDetectorManager* MyAnalysisSvc::pMyDetectorManager [private]
Definition at line 83 of file MyAnalysisSvc.hh.
Referenced by BeginOfRunAction(), EndOfEventAction(), MyAnalysisSvc(), and set_out_card().
MyProcessManager* MyAnalysisSvc::pMyProcessManager [private]
Definition at line 88 of file MyAnalysisSvc.hh.
Referenced by EndOfEventAction(), and MyAnalysisSvc().
MyRoot* MyAnalysisSvc::pMyRoot [private]
Definition at line 81 of file MyAnalysisSvc.hh.
Referenced by BeginOfRunAction(), EndOfEventAction(), EndOfRunAction(), MyAnalysisSvc(), and set_out_card().
MyTriggerSvc* MyAnalysisSvc::pMyTriggerSvc [private]
Definition at line 86 of file MyAnalysisSvc.hh.
Referenced by EndOfEventAction(), MyAnalysisSvc(), and set_out_card().
PrimaryGeneratorAction* MyAnalysisSvc::pPrimaryGeneratorAction [private]
Definition at line 87 of file MyAnalysisSvc.hh.
Referenced by EndOfEventAction(), and MyAnalysisSvc().
ProcessCountingSvc* MyAnalysisSvc::pProcessCountingSvc [private]
Definition at line 85 of file MyAnalysisSvc.hh.
Referenced by ASDI(), BeginOfEventAction(), BeginOfRunAction(), InitialStepAction(), MyAnalysisSvc(), PSDI(), set_out_card(), and SteppingAction().
G4String MyAnalysisSvc::run_name [private]
Definition at line 65 of file MyAnalysisSvc.hh.
Referenced by BeginOfRunAction(), MyAnalysisSvc(), and set_run_name().
int MyAnalysisSvc::run_num [private]
Definition at line 68 of file MyAnalysisSvc.hh.
Referenced by BeginOfRunAction(), EndOfEventAction(), and GetRunID().
clock_t MyAnalysisSvc::t_begin [private]
Definition at line 77 of file MyAnalysisSvc.hh.
Referenced by BeginOfRunAction(), EndOfEventAction(), and EndOfRunAction().
clock_t MyAnalysisSvc::t_end [private]
Definition at line 78 of file MyAnalysisSvc.hh.
Referenced by EndOfRunAction().
G4String MyAnalysisSvc::tree_name [private]
Definition at line 67 of file MyAnalysisSvc.hh.
Referenced by BeginOfRunAction(), ReadOutputCard(), and set_tree_name().
The documentation for this class was generated from the following files:
include/MyAnalysisSvc.hh
src/MyAnalysisSvc.cc