g4sim: MyBLFuncs Class Reference
MyBLFuncs Class Reference
#include <MyBLFuncs.hh>
Public Member Functions
MyBLFuncs ()
int parseArgs (const G4String &line, MyBLArgumentVector &argv, MyBLArgumentMap &namedArgs)
G4String getString (G4String name)
void setParam (G4String name, G4String value)
void setParam (G4String name, G4double value)
void setParam (G4String name, G4int value)
G4String expand (G4String str)
Private Types
enum TokenType { NONE, ARGNAME, ARGVALUE }
Static Private Member Functions
static void init ()
static G4String nextToken (const G4String &line, G4String::size_type &place, TokenType &type)
Static Private Attributes
static std::map< G4String,
G4String > * paramMap
Detailed Description
Definition at line 20 of file MyBLFuncs.hh.
Member Enumeration Documentation
enum MyBLFuncs::TokenType [private]
Enumerator:
NONE
ARGNAME
ARGVALUE
Definition at line 37 of file MyBLFuncs.hh.
{ NONE, ARGNAME, ARGVALUE };
Constructor & Destructor Documentation
MyBLFuncs::MyBLFuncs () [inline]
Definition at line 25 of file MyBLFuncs.hh.
References init().
{ init();}
Member Function Documentation
G4String MyBLFuncs::expand (G4String str)
Definition at line 109 of file MyBLFuncs.cc.
References getString().
Referenced by parseArgs().
{
    static G4String nameChars("ABCDEFGHIJKLMNOPQRSTUVWXYZ_"
        "abcdefghijklmnopqrstuvwxyz0123456789");
    G4String out;
    G4String::size_type place=0;
    while(place < str.size()) {
        G4String::size_type i=str.find('$',place);
        if(i == str.npos) {
            out += str.substr(place);
            break;
        }
        out += str.substr(place,i-place);
        place = i + 1;
        // leave $1 - $9 and $# alone (for define command)
        if(isdigit(str[place]) || str[place] == '#') {
            out += "$";
            continue;
        }
        // replace $$ with $ (delayed evaluation of $param)
        if(str[place] == '$') {
            out += "$";
            ++place;
            continue;
        }
        G4String::size_type j=str.find_first_not_of(nameChars,place);
        if(j == str.npos) j = str.size();
        G4String name=str.substr(place,j-place);
        if(j == place || isdigit(str[place])) {
            G4cerr << "MyBLFuncs::expand ERROR: Invalid parameter name "
                << name << G4endl;
        }
        else {
            out += getString(name);
        }
        place = j;
    }
    return out;
}
G4String MyBLFuncs::getString (G4String name)
Definition at line 152 of file MyBLFuncs.cc.
References init(), paramMap, and setParam().
Referenced by expand().
{
    init();
    if((*paramMap).count(name) == 0) {
        // define it from the environment, if possible
        char *p = getenv(name.c_str());
        if(p) {
            setParam(name,p);
        }
        else {
            G4cerr << "MyBLFuncs::getString ERROR: Unknown parameter "
                << name << G4endl;
        }
    }
    return (*paramMap)[name];                         // "" if not found
}
void MyBLFuncs::init () [static, private]
Definition at line 10 of file MyBLFuncs.cc.
References paramMap.
Referenced by getString(), MyBLFuncs(), and setParam().
                     {
    if (!paramMap) paramMap = new std::map<G4String,G4String>;
    //if (!paramHelpText) paramHelpText = new std::map<G4String,G4String>;
}
G4String MyBLFuncs::nextToken (const G4String & line, G4String::size_type & place, TokenType & type) [static, private]
Definition at line 44 of file MyBLFuncs.cc.
References ARGNAME, ARGVALUE, and NONE.
Referenced by parseArgs().
                 {
    // (add +- for particlecolor pi+=1,1,1)
    static const char namechars[] = ",+-ABCDEFGHIJKLMNOPQRSTUVWXYZ_"
        "abcdefghijklmnopqrstuvwxyz0123456789";
    G4String::size_type i;
    // check if previous token was ARGNAME
    if(line[place] == '=') {
        ++place;
        goto value;
    }
    // skip initial whitespace
    while(place < line.size() && isspace(line[place])) ++place;
    // check for ARGNAME
    if(isalnum(line[place]) || line[place] == '_') {
        i = line.find_first_not_of(namechars,place);
        if(i > place && i < line.size() && line[i] == '=' &&
        line[i+1] != '=') {
            G4String retval = line.substr(place,i-place);
            place = i;
            type = ARGNAME;
            return retval;
        }
    }
    value:
    if(line[place] == '"') {
        ++place;
        i = line.find('"',place);
        if(i <line.size()) {
            G4String retval = line.substr(place,i-place);
            place = i + 1;
            type = ARGVALUE;
            return retval;
        }
    }
    else if(line[place] == '\'') {
        ++place;
        i = line.find('\'',place);
        if(i <line.size()) {
            G4String retval = line.substr(place,i-place);
            place = i + 1;
            type = ARGVALUE;
            return retval;
        }
    }
    if(place >= line.size()) {
        type = NONE;
        return "";
    }
    // find next whitespace
    G4String::size_type start = place;
    while(place < line.size() && !isspace(line[place])) ++place;
    type = ARGVALUE;
    return line.substr(start,place-start);
}
int MyBLFuncs::parseArgs (const G4String & line, MyBLArgumentVector & argv, MyBLArgumentMap & namedArgs)
Definition at line 17 of file MyBLFuncs.cc.
References ARGNAME, ARGVALUE, expand(), nextToken(), and NONE.
Referenced by MyBLFieldMap::readFile().
{
    G4String::size_type place = 0;
    while(place < line.size()) {
        TokenType type;
        G4String arg = nextToken(line,place,type), val;
        switch(type) {
            case NONE:
                break;
            case ARGNAME:
                val = nextToken(line,place,type);
                if(type != ARGVALUE) {
                    G4cerr << "Syntax error parsing arguments" << G4endl;
                    return -1;
                }
                namedArgs[arg] = expand(val);
                break;
            case ARGVALUE:
                argv.push_back(expand(arg));
                break;
        }
    }
    return 0;
}
void MyBLFuncs::setParam (G4String name, G4int value)
Definition at line 185 of file MyBLFuncs.cc.
References setParam().
{
    char tmp[32];
    sprintf(tmp,"%d",value);
    setParam(name,tmp);
}
void MyBLFuncs::setParam (G4String name, G4double value)
Definition at line 177 of file MyBLFuncs.cc.
References setParam().
{
    char tmp[32];
    sprintf(tmp,"%g",value);
    setParam(name,tmp);
}
void MyBLFuncs::setParam (G4String name, G4String value)
Definition at line 170 of file MyBLFuncs.cc.
References init().
Referenced by getString(), and setParam().
{
    init();
    (*paramMap)[name] = value;
}
Member Data Documentation
std::map< G4String, G4String > * MyBLFuncs::paramMap [static, private]
Definition at line 21 of file MyBLFuncs.hh.
Referenced by getString(), and init().
The documentation for this class was generated from the following files:
include/MyBLFuncs.hh
src/MyBLFuncs.cc