g4sim: MyGlobalField Class Reference
MyGlobalField Class Reference
#include <MyGlobalField.hh>
Public Member Functions
void GetFieldValue (const G4double *point, G4double *field) const
G4bool DoesFieldChangeEnergy () const
DoesFieldChangeEnergy() returns true.
void addElementField (MyElementField *f)
void clear ()
void updateField ()
updates all field tracking objects and clear()
void SetStepperType (G4int i)
Set the Stepper types.
void SetStepper ()
Set the Stepper.
void SetMinStep (G4double s)
Set the minimum step length.
void SetDeltaChord (G4double s)
Set the delta chord length.
void SetDeltaOneStep (G4double s)
Set the delta one step length.
void SetDeltaIntersection (G4double s)
Set the delta intersection length.
void SetEpsMin (G4double s)
Set the minimum eps length.
void SetEpsMax (G4double s)
Set the maximum eps length.
FieldList * getFields ()
Return the list of Element Fields.
Static Public Member Functions
static MyGlobalField * getObject ()
Protected Member Functions
G4FieldManager * GetGlobalFieldManager ()
Get the global field manager.
Private Member Functions
MyGlobalField ()
MyGlobalField (const MyGlobalField &)
~MyGlobalField ()
MyGlobalField & operator= (const MyGlobalField &)
void setupArray ()
Private Attributes
G4int nfp
G4bool first
FieldList * fields
const MyElementField ** fp
G4int fStepperType
G4double minStep
G4double deltaChord
G4double deltaOneStep
G4double deltaIntersection
G4double epsMin
G4double epsMax
G4EqEMFieldWithSpin * fEquation
G4FieldManager * fFieldManager
G4PropagatorInField * fFieldPropagator
G4MagIntegratorStepper * fStepper
G4ChordFinder * fChordFinder
MyGlobalFieldMessenger * fGlobalFieldMessenger
Static Private Attributes
static MyGlobalField * object = 0
Detailed Description
Definition at line 67 of file MyGlobalField.hh.
Constructor & Destructor Documentation
MyGlobalField::MyGlobalField () [private]
Definition at line 45 of file MyGlobalField.cc.
References fGlobalFieldMessenger, fields, fStepperType, and updateField().
Referenced by getObject().
                             : G4ElectroMagneticField(),
minStep(0.01*mm), deltaChord(3.0*mm),
deltaOneStep(0.01*mm), deltaIntersection(0.1*mm),
epsMin(2.5e-7*mm), epsMax(0.05*mm),
fEquation(0), fFieldManager(0),
fFieldPropagator(0), fStepper(0), fChordFinder(0) {
    //MyGlobalField::MyGlobalField() : G4MagneticField(),
    //                             minStep(0.01*mm), deltaChord(3.0*mm),
    //                             deltaOneStep(0.01*mm), deltaIntersection(0.1*mm),
    //                             epsMin(2.5e-7*mm), epsMax(0.05*mm),
    //                             fEquation(0), fFieldManager(0),
    //                             fFieldPropagator(0), fStepper(0), fChordFinder(0)
    fGlobalFieldMessenger = new MyGlobalFieldMessenger(this);
    fields = new FieldList();
    fStepperType = 4 ;                                // ClassicalRK4 is default stepper
    //  set object
    object = this;
    updateField();
}
MyGlobalField::MyGlobalField (const MyGlobalField &) [private]
MyGlobalField::~MyGlobalField () [private]
Definition at line 71 of file MyGlobalField.cc.
References clear(), fChordFinder, fEquation, fFieldManager, fFieldPropagator, fGlobalFieldMessenger, and fStepper.
{
    clear();
    delete fGlobalFieldMessenger;
    if (fEquation)        delete fEquation;
    if (fFieldManager)    delete fFieldManager;
    if (fFieldPropagator) delete fFieldPropagator;
    if (fStepper)         delete fStepper;
    if (fChordFinder)     delete fChordFinder;
}
Member Function Documentation
void MyGlobalField::addElementField (MyElementField * f) [inline]
addElementField() adds the ElementField object for a single element to the global field.
Definition at line 97 of file MyGlobalField.hh.
References fields.
Referenced by MyElementField::MyElementField().
{ if (fields) fields->push_back(f); }
void MyGlobalField::clear ()
clear() removes all ElementField-s from the global object, and destroys them. Used before the geometry is completely re-created.
Definition at line 235 of file MyGlobalField.cc.
References fields, first, fp, and nfp.
Referenced by updateField(), and ~MyGlobalField().
{
    if (fields) {
        if (fields->size()>0) {
            FieldList::iterator i;
            for (i=fields->begin(); i!=fields->end(); ++i) delete *i;
            fields->clear();
        }
    }
    if (fp) delete[] fp;
    first = true;
    nfp = 0;
    fp = NULL;
}
G4bool MyGlobalField::DoesFieldChangeEnergy () const [inline]
DoesFieldChangeEnergy() returns true.
Definition at line 93 of file MyGlobalField.hh.
{ return true; }
FieldList* MyGlobalField::getFields () [inline]
Return the list of Element Fields.
Definition at line 132 of file MyGlobalField.hh.
References fields.
Referenced by RunAction::BeginOfRunAction().
{ return fields; }
void MyGlobalField::GetFieldValue (const G4double * point, G4double * field) const
GetFieldValue() returns the field value at a given point[]. field is really field[6]: Bx,By,Bz,Ex,Ey,Ez. point[] is in global coordinates: x,y,z,t.
Definition at line 204 of file MyGlobalField.cc.
References MyElementField::addFieldValue(), first, fp, MyElementField::isInBoundingBox(), and nfp.
Referenced by MyGlobalFieldMessenger::SetNewValue().
{
    // NOTE: this routine dominates the CPU time for tracking.
    // Using the simple array fp[] instead of fields[]
    // directly sped it up
    field[0] = field[1] = field[2] = field[3] = field[4] = field[5] = 0.0;
    // protect against Geant4 bug that calls us with point[] NaN.
    if(point[0] != point[0]) return;
    // (can't use nfp or fp, as they may change)
    if (first) ((MyGlobalField*)this)->setupArray();  // (cast away const)
    for (int i=0; i<nfp; ++i) {
        const MyElementField* p = fp[i];
        if (p->isInBoundingBox(point)) {
            p->addFieldValue(point,field);
        }
    }
    if(0) {
        G4cout << "Point = [" << point[0]/cm << ", "
            << point[1]/cm << ", " << point[2]/cm << "] cm" << G4endl;
        G4cout << " Field = [" << field[0]/tesla << ", " << field[1]/tesla << ", "
            << field[2]/tesla << "]" << G4endl
            << "         [" << field[3] << ", " << field[4]
            << ", " << field[5]<< "] " << G4endl;
    }
}
G4FieldManager * MyGlobalField::GetGlobalFieldManager () [protected]
Get the global field manager.
Definition at line 198 of file MyGlobalField.cc.
Referenced by updateField().
{
    return G4TransportationManager::GetTransportationManager()
        ->GetFieldManager();
}
MyGlobalField * MyGlobalField::getObject () [static]
getObject() returns the single MyGlobalField object. It is constructed, if necessary.
Definition at line 147 of file MyGlobalField.cc.
References MyGlobalField(), and object.
Referenced by RunAction::BeginOfRunAction(), MyElementField::MyElementField(), and MyFieldSvc::MyFieldSvc().
{
    if (!object) new MyGlobalField();
    return object;
}
MyGlobalField& MyGlobalField::operator= (const MyGlobalField &) [private]
void MyGlobalField::SetDeltaChord (G4double s) [inline]
Set the delta chord length.
Definition at line 117 of file MyGlobalField.hh.
References deltaChord.
Referenced by MyGlobalFieldMessenger::SetNewValue().
{ deltaChord = s; }
void MyGlobalField::SetDeltaIntersection (G4double s) [inline]
Set the delta intersection length.
Definition at line 123 of file MyGlobalField.hh.
References deltaIntersection.
{ deltaIntersection = s; }
void MyGlobalField::SetDeltaOneStep (G4double s) [inline]
Set the delta one step length.
Definition at line 120 of file MyGlobalField.hh.
References deltaOneStep.
{ deltaOneStep = s; }
void MyGlobalField::SetEpsMax (G4double s) [inline]
Set the maximum eps length.
Definition at line 129 of file MyGlobalField.hh.
References epsMax.
Referenced by MyGlobalFieldMessenger::SetNewValue().
{ epsMax = s; }
void MyGlobalField::SetEpsMin (G4double s) [inline]
Set the minimum eps length.
Definition at line 126 of file MyGlobalField.hh.
References epsMin.
Referenced by MyGlobalFieldMessenger::SetNewValue().
{ epsMin = s; }
void MyGlobalField::SetMinStep (G4double s) [inline]
Set the minimum step length.
Definition at line 114 of file MyGlobalField.hh.
References minStep.
Referenced by MyGlobalFieldMessenger::SetNewValue().
{ minStep = s; }
void MyGlobalField::SetStepper ()
Set the Stepper.
Definition at line 153 of file MyGlobalField.cc.
References fEquation, fStepper, and fStepperType.
Referenced by updateField().
{
    if(fStepper) delete fStepper;
    switch ( fStepperType ) {
        case 0:
            //      fStepper = new G4ExplicitEuler( fEquation, 8 ); // no spin tracking
                                                      // with spin tracking
            fStepper = new G4ExplicitEuler( fEquation, 12 );
            G4cout << "G4ExplicitEuler is called" << G4endl;
            break;
        case 1:
            //      fStepper = new G4ImplicitEuler( fEquation, 8 ); // no spin tracking
                                                      // with spin tracking
            fStepper = new G4ImplicitEuler( fEquation, 12 );
            G4cout << "G4ImplicitEuler is called" << G4endl;
            break;
        case 2:
            //      fStepper = new G4SimpleRunge( fEquation, 8 ); // no spin tracking
                                                      // with spin tracking
            fStepper = new G4SimpleRunge( fEquation, 12 );
            G4cout << "G4SimpleRunge is called" << G4endl;
            break;
        case 3:
            //      fStepper = new G4SimpleHeum( fEquation, 8 ); // no spin tracking
                                                      // with spin tracking
            fStepper = new G4SimpleHeum( fEquation, 12 );
            G4cout << "G4SimpleHeum is called" << G4endl;
            break;
        case 4:
            //      fStepper = new G4ClassicalRK4( fEquation, 8 ); // no spin tracking
                                                      // with spin tracking
            fStepper = new G4ClassicalRK4( fEquation, 12 );
            G4cout << "G4ClassicalRK4 (default) is called" << G4endl;
            break;
        case 5:
            //      fStepper = new G4CashKarpRKF45( fEquation, 8 ); // no spin tracking
                                                      // with spin tracking
            fStepper = new G4CashKarpRKF45( fEquation, 12 );
            G4cout << "G4CashKarpRKF45 is called" << G4endl;
            break;
        default: fStepper = 0;
    }
}
void MyGlobalField::SetStepperType (G4int i) [inline]
Set the Stepper types.
Definition at line 108 of file MyGlobalField.hh.
References fStepperType.
Referenced by MyGlobalFieldMessenger::SetNewValue().
{ fStepperType = i; }
void MyGlobalField::setupArray () [private]
Definition at line 253 of file MyGlobalField.cc.
References fields, first, fp, and nfp.
{
    first = false;
    nfp = fields->size();
    fp = new const MyElementField* [nfp+1];           // add 1 so it's never 0
    for (int i=0; i<nfp; ++i) fp[i] = (*fields)[i];
    //G4cout << " In MyGlobalField::setupArray nfp is " << nfp << G4endl;
}
void MyGlobalField::updateField ()
updates all field tracking objects and clear()
Definition at line 84 of file MyGlobalField.cc.
References clear(), deltaChord, deltaIntersection, deltaOneStep, epsMax, epsMin, fChordFinder, fEquation, fFieldManager, fFieldPropagator, first, fp, fStepper, GetGlobalFieldManager(), minStep, nfp, and SetStepper().
Referenced by MyGlobalField(), and MyGlobalFieldMessenger::SetNewValue().
{
    first = true;
    nfp = 0;
    fp = 0;
    clear();
    //  Construct equ. of motion of particles through B fields
    //  fEquation = new G4Mag_EqRhs(this);
    //  Construct equ. of motion of particles through e.m. fields
    //  fEquation = new G4EqMagElectricField(this);
    //  Construct equ. of motion of particles including spin through B fields
    //  fEquation = new G4Mag_SpinEqRhs(this);
    //  Construct equ. of motion of particles including spin through e.m. fields
    fEquation = new G4EqEMFieldWithSpin(this);
    //  Get transportation, field, and propagator managers
    G4TransportationManager* fTransportManager =
        G4TransportationManager::GetTransportationManager();
    fFieldManager = GetGlobalFieldManager();
    fFieldPropagator = fTransportManager->GetPropagatorInField();
    //  Need to SetFieldChangesEnergy to account for a time varying electric
    //  field (r.f. fields)
    fFieldManager->SetFieldChangesEnergy(true);
    //  Set the field
    fFieldManager->SetDetectorField(this);
    //  Choose a stepper for integration of the equation of motion
    SetStepper();
    //  Create a cord finder providing the (global field, min step length,
    //  a pointer to the stepper)
    fChordFinder = new G4ChordFinder((G4MagneticField*)this,minStep,fStepper);
    // Set accuracy parameters
    fChordFinder->SetDeltaChord( deltaChord );
    fFieldManager->SetAccuraciesWithDeltaOneStep(deltaOneStep);
    fFieldManager->SetDeltaIntersection(deltaIntersection);
    fFieldPropagator->SetMinimumEpsilonStep(epsMin);
    fFieldPropagator->SetMaximumEpsilonStep(epsMax);
    G4cout << "Accuracy Parameters:" <<
        " MinStep=" << minStep <<
        " DeltaChord=" << deltaChord <<
        " DeltaOneStep=" << deltaOneStep << G4endl;
    G4cout << "                    " <<
        " DeltaIntersection=" << deltaIntersection <<
        " EpsMin=" << epsMin <<
        " EpsMax=" << epsMax <<  G4endl;
    fFieldManager->SetChordFinder(fChordFinder);
}
Member Data Documentation
G4double MyGlobalField::deltaChord [private]
Definition at line 155 of file MyGlobalField.hh.
Referenced by SetDeltaChord(), and updateField().
G4double MyGlobalField::deltaIntersection [private]
Definition at line 157 of file MyGlobalField.hh.
Referenced by SetDeltaIntersection(), and updateField().
G4double MyGlobalField::deltaOneStep [private]
Definition at line 156 of file MyGlobalField.hh.
Referenced by SetDeltaOneStep(), and updateField().
G4double MyGlobalField::epsMax [private]
Definition at line 159 of file MyGlobalField.hh.
Referenced by SetEpsMax(), and updateField().
G4double MyGlobalField::epsMin [private]
Definition at line 158 of file MyGlobalField.hh.
Referenced by SetEpsMin(), and updateField().
G4ChordFinder* MyGlobalField::fChordFinder [private]
Definition at line 170 of file MyGlobalField.hh.
Referenced by updateField(), and ~MyGlobalField().
G4EqEMFieldWithSpin* MyGlobalField::fEquation [private]
Definition at line 165 of file MyGlobalField.hh.
Referenced by SetStepper(), updateField(), and ~MyGlobalField().
G4FieldManager* MyGlobalField::fFieldManager [private]
Definition at line 167 of file MyGlobalField.hh.
Referenced by updateField(), and ~MyGlobalField().
G4PropagatorInField* MyGlobalField::fFieldPropagator [private]
Definition at line 168 of file MyGlobalField.hh.
Referenced by updateField(), and ~MyGlobalField().
MyGlobalFieldMessenger* MyGlobalField::fGlobalFieldMessenger [private]
Definition at line 172 of file MyGlobalField.hh.
Referenced by MyGlobalField(), and ~MyGlobalField().
FieldList* MyGlobalField::fields [private]
Definition at line 146 of file MyGlobalField.hh.
Referenced by addElementField(), clear(), getFields(), MyGlobalField(), and setupArray().
G4bool MyGlobalField::first [private]
Definition at line 144 of file MyGlobalField.hh.
Referenced by clear(), GetFieldValue(), setupArray(), and updateField().
const MyElementField** MyGlobalField::fp [private]
Definition at line 148 of file MyGlobalField.hh.
Referenced by clear(), GetFieldValue(), setupArray(), and updateField().
G4MagIntegratorStepper* MyGlobalField::fStepper [private]
Definition at line 169 of file MyGlobalField.hh.
Referenced by SetStepper(), updateField(), and ~MyGlobalField().
G4int MyGlobalField::fStepperType [private]
Definition at line 152 of file MyGlobalField.hh.
Referenced by MyGlobalField(), SetStepper(), and SetStepperType().
G4double MyGlobalField::minStep [private]
Definition at line 154 of file MyGlobalField.hh.
Referenced by SetMinStep(), and updateField().
G4int MyGlobalField::nfp [private]
Definition at line 143 of file MyGlobalField.hh.
Referenced by clear(), GetFieldValue(), setupArray(), and updateField().
MyGlobalField * MyGlobalField::object = 0 [static, private]
Definition at line 141 of file MyGlobalField.hh.
Referenced by getObject().
The documentation for this class was generated from the following files:
include/MyGlobalField.hh
src/MyGlobalField.cc