g4sim: CdcGeometryParameter Class Reference
CdcGeometryParameter Class Reference
#include <CdcGeometryParameter.hh>
Public Member Functions
CdcGeometryParameter (G4String name, G4String opt="")
virtual ~CdcGeometryParameter (void)
virtual void InitFromFile (G4String)
virtual void Calculate ()
virtual void Dump ()
int GetValue (G4String)
void Preset ()
bool CheckInfo ()
void DumpInfo (void)
G4String get_MotherLogicalVolume ()
G4String get_SensitiveDetector ()
G4String get_SDVolumeName ()
G4String get_SignalWireMaterial ()
G4String get_FieldWireMaterial ()
G4String get_CellMaterial ()
G4double get_SignalWireRadius ()
G4double get_FieldWireRadius ()
G4int get_LayerNo ()
G4double get_Cdc_RMax ()
G4double get_layer_length (G4int layerId)
G4double get_layer_RMin (G4int layerId)
G4double get_layer_RMid (G4int layerId)
G4double get_layer_SPhi (G4int layerId)
G4double get_layer_ncells4rotate (G4int layerId)
G4double get_layer_angle4rotate (G4int layerId)
G4int get_layer_cell_num (G4int layerId)
G4int get_layer_firstWire (G4int layerId)
G4int get_layer_type (G4int layerId)
G4double get_layer_cell_dphi (G4int layerId)
G4int get_ReplicaNo (G4int layerId, G4int cellId)
G4int get_layerIdcellId (G4int ReplicaNo, G4int *layerId, G4int *cellId)
G4double get_layer_cell_phi (G4int layerId, G4int cellId)
bool get_vis_layer ()
G4double get_r_layer ()
G4double get_g_layer ()
G4double get_b_layer ()
bool get_vis_cell ()
G4double get_r_cell ()
G4double get_g_cell ()
G4double get_b_cell ()
bool get_vis_FieldWire ()
bool get_vis_SignalWire ()
G4double get_r_FieldWire ()
G4double get_g_FieldWire ()
G4double get_b_FieldWire ()
G4double get_r_SignalWire ()
G4double get_g_SignalWire ()
G4double get_b_SignalWire ()
G4int get_VolIndex (G4String name)
G4int get_VolNo ()
G4double get_PosX (G4int VolId, G4int j=0)
G4double get_PosY (G4int VolId, G4int j=0)
G4double get_PosZ (G4int VolId, G4int j=0)
G4String get_name (G4int VolId)
G4String get_SDName (G4int VolId)
G4String get_MotherName (G4int VolId)
G4String get_material (G4int VolId)
G4int get_SRepNo (G4int VolId)
G4int get_RepNo (G4int VolId)
G4String get_SolidType (G4int VolId)
G4int get_SolidIndex (G4int VolId)
G4double get_Ephi (G4int VolId, G4int j=0)
G4double get_Etheta (G4int VolId, G4int j=0)
G4double get_Epsi (G4int VolId, G4int j=0)
G4bool get_SolidBoolean (G4int VolId)
G4int get_BoxNo ()
G4double get_Box_X (G4int BoxId, G4int j=0)
G4double get_Box_Y (G4int BoxId, G4int j=0)
G4double get_Box_Z (G4int BoxId, G4int j=0)
G4int get_EllipticalTubeNo ()
G4double get_EllipticalTube_X (G4int EllipticalTubeId, G4int j=0)
G4double get_EllipticalTube_Y (G4int EllipticalTubeId, G4int j=0)
G4double get_EllipticalTube_Z (G4int EllipticalTubeId, G4int j=0)
G4int get_TubsNo ()
G4double get_Tubs_RMax (G4int TubsId, G4int j=0)
G4double get_Tubs_RMin (G4int TubsId, G4int j=0)
G4double get_Tubs_Length (G4int TubsId, G4int j=0)
G4double get_Tubs_StartAng (G4int TubsId, G4int j=0)
G4double get_Tubs_SpanAng (G4int TubsId, G4int j=0)
G4int get_TorusNo ()
G4double get_Torus_RMax (G4int TorusId, G4int j=0)
G4double get_Torus_RMin (G4int TorusId, G4int j=0)
G4double get_Torus_Rtor (G4int TorusId, G4int j=0)
G4double get_Torus_StartAng (G4int TorusId, G4int j=0)
G4double get_Torus_SpanAng (G4int TorusId, G4int j=0)
G4int get_SphereNo ()
G4double get_Sphere_RMax (G4int SphereId, G4int j=0)
G4double get_Sphere_RMin (G4int SphereId, G4int j=0)
G4double get_Sphere_StartPhi (G4int SphereId, G4int j=0)
G4double get_Sphere_SpanPhi (G4int SphereId, G4int j=0)
G4double get_Sphere_StartTheta (G4int SphereId, G4int j=0)
G4double get_Sphere_SpanTheta (G4int SphereId, G4int j=0)
G4int get_HypeNo ()
G4double get_Hype_innerRadius (G4int HypeId, G4int j=0)
G4double get_Hype_outerRadius (G4int HypeId, G4int j=0)
G4double get_Hype_innerStereo (G4int HypeId, G4int j=0)
G4double get_Hype_outerStereo (G4int HypeId, G4int j=0)
G4double get_Hype_Length (G4int HypeId, G4int j=0)
G4int get_TwistedTubsNo ()
G4double get_TwistedTubs_twistedangle (G4int TwistedTubsId, G4int j=0)
G4double get_TwistedTubs_endinnerrad (G4int TwistedTubsId, G4int j=0)
G4double get_TwistedTubs_endouterrad (G4int TwistedTubsId, G4int j=0)
G4double get_TwistedTubs_Length (G4int TwistedTubsId, G4int j=0)
G4double get_TwistedTubs_dphi (G4int TwistedTubsId, G4int j=0)
G4int get_ConsNo ()
G4double get_Cons_RMax1 (G4int ConsId, G4int j=0)
G4double get_Cons_RMin1 (G4int ConsId, G4int j=0)
G4double get_Cons_RMax2 (G4int ConsId, G4int j=0)
G4double get_Cons_RMin2 (G4int ConsId, G4int j=0)
G4double get_Cons_Length (G4int ConsId, G4int j=0)
G4double get_Cons_StartAng (G4int ConsId, G4int j=0)
G4double get_Cons_SpanAng (G4int ConsId, G4int j=0)
G4int get_PolyconeNo ()
G4int get_Polycone_numZ (G4int PolyconeId, G4int j=0)
G4double get_Polycone_RMax (G4int PolyconeId, G4int i, G4int j=0)
G4double get_Polycone_RMin (G4int PolyconeId, G4int i, G4int j=0)
G4double get_Polycone_Z (G4int PolyconeId, G4int i, G4int j=0)
G4double get_Polycone_StartAng (G4int PolyconeId, G4int j=0)
G4double get_Polycone_SpanAng (G4int PolyconeId, G4int j=0)
G4int get_ExtrudedSolidNo ()
G4int get_ExtrudedSolid_numZ (G4int ExtrudedSolidId, G4int j=0)
G4int get_ExtrudedSolid_numP (G4int ExtrudedSolidId, G4int j=0)
G4double get_ExtrudedSolid_X (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4double get_ExtrudedSolid_Y (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4double get_ExtrudedSolid_Z (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4double get_ExtrudedSolid_X0 (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4double get_ExtrudedSolid_Y0 (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4double get_ExtrudedSolid_Scale (G4int ExtrudedSolidId, G4int i, G4int j=0)
G4String get_BooleanSolid_type (G4int BooleanSolidId)
G4String get_BooleanSolid_sol1 (G4int BooleanSolidId)
G4String get_BooleanSolid_sol2 (G4int BooleanSolidId)
G4double get_BooleanSolid_Ephi (G4int BooleanSolidId, G4int j=0)
G4double get_BooleanSolid_Etheta (G4int BooleanSolidId, G4int j=0)
G4double get_BooleanSolid_Epsi (G4int BooleanSolidId, G4int j=0)
G4double get_BooleanSolid_PosX (G4int BooleanSolidId, G4int j=0)
G4double get_BooleanSolid_PosY (G4int BooleanSolidId, G4int j=0)
G4double get_BooleanSolid_PosZ (G4int BooleanSolidId, G4int j=0)
bool get_vis (G4int VolId)
G4double get_r (G4int VolId)
G4double get_g (G4int VolId)
G4double get_b (G4int VolId)
G4double get_t (G4int VolId)
void set_PosX (G4String type, G4int i, G4double val, G4int j=0)
void set_PosX (G4String name, G4double val, G4int j=0)
void set_PosY (G4String type, G4int i, G4double val, G4int j=0)
void set_PosY (G4String name, G4double val, G4int j=0)
void set_PosZ (G4String type, G4int i, G4double val, G4int j=0)
void set_PosZ (G4String name, G4double val, G4int j=0)
void set_name (G4String type, G4int i, G4String val)
void set_name (G4String name, G4String val)
void set_SDName (G4String type, G4int i, G4String val)
void set_SDName (G4String name, G4String val)
void set_MotherName (G4String type, G4int i, G4String val)
void set_MotherName (G4String name, G4String val)
void set_material (G4String type, G4int i, G4String val)
void set_material (G4String name, G4String val)
void set_SRepNo (G4String type, G4int i, G4int val)
void set_SRepNo (G4String name, G4int val)
void set_RepNo (G4String type, G4int i, G4int val)
void set_RepNo (G4String name, G4int val)
void set_Ephi (G4String type, G4int i, G4double val, G4int j=0)
void set_Ephi (G4String name, G4double val, G4int j=0)
void set_Etheta (G4String type, G4int i, G4double val, G4int j=0)
void set_Etheta (G4String name, G4double val, G4int j=0)
void set_Epsi (G4String type, G4int i, G4double val, G4int j=0)
void set_Epsi (G4String name, G4double val, G4int j=0)
void set_SolidBoolean (G4String type, G4int i, G4int val)
void set_SolidBoolean (G4String name, G4int val)
void set_Box_X (G4int i, G4double val, G4int j=0)
void set_Box_X (G4String name, G4double val, G4int j=0)
void set_Box_Y (G4int i, G4double val, G4int j=0)
void set_Box_Y (G4String name, G4double val, G4int j=0)
void set_Box_Z (G4int i, G4double val, G4int j=0)
void set_Box_Z (G4String name, G4double val, G4int j=0)
void set_EllipticalTube_X (G4int i, G4double val, G4int j=0)
void set_EllipticalTube_X (G4String name, G4double val, G4int j=0)
void set_EllipticalTube_Y (G4int i, G4double val, G4int j=0)
void set_EllipticalTube_Y (G4String name, G4double val, G4int j=0)
void set_EllipticalTube_Z (G4int i, G4double val, G4int j=0)
void set_EllipticalTube_Z (G4String name, G4double val, G4int j=0)
void set_Tubs_RMax (G4int i, G4double val, G4int j=0)
void set_Tubs_RMax (G4String name, G4double val, G4int j=0)
void set_Tubs_RMin (G4int i, G4double val, G4int j=0)
void set_Tubs_RMin (G4String name, G4double val, G4int j=0)
void set_Tubs_Length (G4int i, G4double val, G4int j=0)
void set_Tubs_Length (G4String name, G4double val, G4int j=0)
void set_Tubs_StartAng (G4int i, G4double val, G4int j=0)
void set_Tubs_StartAng (G4String name, G4double val, G4int j=0)
void set_Tubs_SpanAng (G4int i, G4double val, G4int j=0)
void set_Tubs_SpanAng (G4String name, G4double val, G4int j=0)
void set_Torus_RMax (G4int i, G4double val, G4int j=0)
void set_Torus_RMax (G4String name, G4double val, G4int j=0)
void set_Torus_RMin (G4int i, G4double val, G4int j=0)
void set_Torus_RMin (G4String name, G4double val, G4int j=0)
void set_Torus_Rtor (G4int i, G4double val, G4int j=0)
void set_Torus_Rtor (G4String name, G4double val, G4int j=0)
void set_Torus_StartAng (G4int i, G4double val, G4int j=0)
void set_Torus_StartAng (G4String name, G4double val, G4int j=0)
void set_Torus_SpanAng (G4int i, G4double val, G4int j=0)
void set_Torus_SpanAng (G4String name, G4double val, G4int j=0)
void set_Sphere_RMax (G4int i, G4double val, G4int j=0)
void set_Sphere_RMax (G4String name, G4double val, G4int j=0)
void set_Sphere_RMin (G4int i, G4double val, G4int j=0)
void set_Sphere_RMin (G4String name, G4double val, G4int j=0)
void set_Sphere_StartPhi (G4int i, G4double val, G4int j=0)
void set_Sphere_StartPhi (G4String name, G4double val, G4int j=0)
void set_Sphere_SpanPhi (G4int i, G4double val, G4int j=0)
void set_Sphere_SpanPhi (G4String name, G4double val, G4int j=0)
void set_Sphere_StartTheta (G4int i, G4double val, G4int j=0)
void set_Sphere_StartTheta (G4String name, G4double val, G4int j=0)
void set_Sphere_SpanTheta (G4int i, G4double val, G4int j=0)
void set_Sphere_SpanTheta (G4String name, G4double val, G4int j=0)
void set_Hype_innerRadius (G4int i, G4double val, G4int j=0)
void set_Hype_innerRadius (G4String name, G4double val, G4int j=0)
void set_Hype_outerRadius (G4int i, G4double val, G4int j=0)
void set_Hype_outerRadius (G4String name, G4double val, G4int j=0)
void set_Hype_innerStereo (G4int i, G4double val, G4int j=0)
void set_Hype_innerStereo (G4String name, G4double val, G4int j=0)
void set_Hype_outerStereo (G4int i, G4double val, G4int j=0)
void set_Hype_outerStereo (G4String name, G4double val, G4int j=0)
void set_Hype_Length (G4int i, G4double val, G4int j=0)
void set_Hype_Length (G4String name, G4double val, G4int j=0)
void set_TwistedTubs_twistedangle (G4int i, G4double val, G4int j=0)
void set_TwistedTubs_twistedangle (G4String name, G4double val, G4int j=0)
void set_TwistedTubs_endinnerrad (G4int i, G4double val, G4int j=0)
void set_TwistedTubs_endinnerrad (G4String name, G4double val, G4int j=0)
void set_TwistedTubs_endouterrad (G4int i, G4double val, G4int j=0)
void set_TwistedTubs_endouterrad (G4String name, G4double val, G4int j=0)
void set_TwistedTubs_Length (G4int i, G4double val, G4int j=0)
void set_TwistedTubs_Length (G4String name, G4double val, G4int j=0)
void set_TwistedTubs_dphi (G4int i, G4double val, G4int j=0)
void set_TwistedTubs_dphi (G4String name, G4double val, G4int j=0)
void set_Cons_RMax1 (G4int i, G4double val, G4int j=0)
void set_Cons_RMax1 (G4String name, G4double val, G4int j=0)
void set_Cons_RMin1 (G4int i, G4double val, G4int j=0)
void set_Cons_RMin1 (G4String name, G4double val, G4int j=0)
void set_Cons_RMax2 (G4int i, G4double val, G4int j=0)
void set_Cons_RMax2 (G4String name, G4double val, G4int j=0)
void set_Cons_RMin2 (G4int i, G4double val, G4int j=0)
void set_Cons_RMin2 (G4String name, G4double val, G4int j=0)
void set_Cons_Length (G4int i, G4double val, G4int j=0)
void set_Cons_Length (G4String name, G4double val, G4int j=0)
void set_Cons_StartAng (G4int i, G4double val, G4int j=0)
void set_Cons_StartAng (G4String name, G4double val, G4int j=0)
void set_Cons_SpanAng (G4int i, G4double val, G4int j=0)
void set_Cons_SpanAng (G4String name, G4double val, G4int j=0)
void set_Polycone_numZ (G4int PolyconeId, G4int val, G4int j=0)
void set_Polycone_numZ (G4String name, G4int val, G4int j=0)
void set_Polycone_RMax (G4int PolyconeId, G4int i, G4double val, G4int j=0)
void set_Polycone_RMax (G4String name, G4int iCone, G4double val, G4int j=0)
void set_Polycone_RMin (G4int PolyconeId, G4int i, G4double val, G4int j=0)
void set_Polycone_RMin (G4String name, G4int iCone, G4double val, G4int j=0)
void set_Polycone_Z (G4int PolyconeId, G4int i, G4double val, G4int j=0)
void set_Polycone_Z (G4String name, G4int iCone, G4double val, G4int j=0)
void set_Polycone_StartAng (G4int PolyconeId, G4double val, G4int j=0)
void set_Polycone_StartAng (G4String name, G4double val, G4int j=0)
void set_Polycone_SpanAng (G4int PolyconeId, G4double val, G4int j=0)
void set_Polycone_SpanAng (G4String name, G4double val, G4int j=0)
void set_ExtrudedSolid_numZ (G4int ExtrudedSolidId, G4int val, G4int j=0)
void set_ExtrudedSolid_numZ (G4String name, G4int val, G4int j=0)
void set_ExtrudedSolid_numP (G4int ExtrudedSolidId, G4int val, G4int j=0)
void set_ExtrudedSolid_numP (G4String name, G4int val, G4int j=0)
void set_ExtrudedSolid_X (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_X (G4String name, G4int iCone, G4double val, G4int j=0)
void set_ExtrudedSolid_Y (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_Y (G4String name, G4int iCone, G4double val, G4int j=0)
void set_ExtrudedSolid_Z (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_Z (G4String name, G4int iCone, G4double val, G4int j=0)
void set_ExtrudedSolid_X0 (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_X0 (G4String name, G4int iCone, G4double val, G4int j=0)
void set_ExtrudedSolid_Y0 (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_Y0 (G4String name, G4int iCone, G4double val, G4int j=0)
void set_ExtrudedSolid_Scale (G4int ExtrudedSolidId, G4int i, G4double val, G4int j=0)
void set_ExtrudedSolid_Scale (G4String name, G4int iCone, G4double val, G4int j=0)
void set_BooleanSolid_type (G4int BooleanSolidId, G4String val)
void set_BooleanSolid_type (G4String name, G4String val)
void set_BooleanSolid_sol1 (G4int BooleanSolidId, G4String val)
void set_BooleanSolid_sol1 (G4String name, G4String val)
void set_BooleanSolid_sol2 (G4int BooleanSolidId, G4String val)
void set_BooleanSolid_sol2 (G4String name, G4String val)
void set_BooleanSolid_Ephi (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_Ephi (G4String name, G4double val, G4int j=0)
void set_BooleanSolid_Etheta (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_Etheta (G4String name, G4double val, G4int j=0)
void set_BooleanSolid_Epsi (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_Epsi (G4String name, G4double val, G4int j=0)
void set_BooleanSolid_PosX (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_PosX (G4String name, G4double val, G4int j=0)
void set_BooleanSolid_PosY (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_PosY (G4String name, G4double val, G4int j=0)
void set_BooleanSolid_PosZ (G4int BooleanSolidId, G4double val, G4int j=0)
void set_BooleanSolid_PosZ (G4String name, G4double val, G4int j=0)
void set_vis (G4String type, G4int i, bool val)
void set_vis (G4int i, bool val)
void set_vis (G4String name, bool val)
void set_r (G4String type, G4int i, G4double val)
void set_r (G4int i, G4double val)
void set_r (G4String name, G4double val)
void set_g (G4String type, G4int i, G4double val)
void set_g (G4int i, G4double val)
void set_g (G4String name, G4double val)
void set_b (G4String type, G4int i, G4double val)
void set_b (G4int i, G4double val)
void set_b (G4String name, G4double val)
void set_t (G4String type, G4int i, G4double val)
void set_t (G4int i, G4double val)
void set_t (G4String name, G4double val)
void get_RepCont (G4String RepCont, G4int &SRepNo, G4int &RepNo)
bool ISEMPTY (G4String)
void DEBUG (G4String content, int level=1)
bool get_checkoverlap ()
int get_VerboseLevel ()
G4String get_Name ()
G4String get_filename ()
void set_checkoverlap (bool val)
void set_VerboseLevel (int val)
void set_GeometryParameterMessenger (MyVGeometryParameterMessenger *val)
void set_Name (G4String val)
void set_filename (G4String val)
std::vector< G4String > GetWords (G4String formula)
bool FindMacro (G4String word, G4String &value)
void Replace (G4String &formula, G4String word, G4String value)
double CalFormula (G4String formula, int iRep=0)
G4String ReplaceMacro (G4String formula)
Static Public Attributes
static std::vector< G4String > knownValueNames
static std::vector< G4String > knownValues
Private Member Functions
bool check_layerId (int layerId)
bool check_cellId (int layerId, int cellId)
bool check_LayerNo (int No)
Private Attributes
G4String MotherLogicalVolume
G4String SensitiveDetector
G4String SDVolumeName
G4String SignalWireMaterial
G4String FieldWireMaterial
G4String CellMaterial
G4double SignalWireRadius
G4double FieldWireRadius
G4int LayerNo
G4double Cdc_RMax
std::vector< G4double > layer_length
std::vector< G4double > layer_RMin
std::vector< G4double > layer_RMid
std::vector< G4double > layer_SPhi
std::vector< G4double > layer_ncells4rotate
std::vector< G4double > layer_angle4rotate
std::vector< G4int > layer_cell_num
std::vector< G4int > layer_firstWire
std::vector< G4int > layer_type
std::vector< G4int > layer_cell_startNo
std::vector< G4double > layer_cell_dphi
bool vis_layer
G4double r_layer
G4double g_layer
G4double b_layer
bool vis_cell
G4double r_cell
G4double g_cell
G4double b_cell
bool vis_FieldWire
bool vis_SignalWire
G4double r_SignalWire
G4double g_SignalWire
G4double b_SignalWire
G4double r_FieldWire
G4double g_FieldWire
G4double b_FieldWire
Detailed Description
Definition at line 61 of file CdcGeometryParameter.hh.
Constructor & Destructor Documentation
CdcGeometryParameter::CdcGeometryParameter (G4String name, G4String opt = "")
Definition at line 61 of file CdcGeometryParameter.cc.
References MyVGeometryParameter::set_GeometryParameterMessenger().
        : SimpleGeometryParameter(name, "S") // Use a not-empty opt to stop inherited class from creating new GeometryParameterMessenger
{
        if ( opt == "" ){
                CdcGeometryParameterMessenger *pointer = new CdcGeometryParameterMessenger(this, name);
                //std::cout<<"======>In CdcGeometryParameter, new CdcGeometryParameterMessenger at ("<<(void*)pointer<<")!"<<std::endl;
                set_GeometryParameterMessenger(pointer);
        }
}
CdcGeometryParameter::~CdcGeometryParameter (void) [virtual]
Definition at line 71 of file CdcGeometryParameter.cc.
{
        printf("~CdcGeometryParameter");
}
Member Function Documentation
void CdcGeometryParameter::Calculate () [virtual]
Reimplemented from SimpleGeometryParameter.
Definition at line 216 of file CdcGeometryParameter.cc.
References Cdc_RMax, layer_angle4rotate, layer_cell_dphi, layer_cell_num, layer_cell_startNo, layer_ncells4rotate, layer_RMin, layer_type, and LayerNo.
Referenced by InitFromFile().
{
        SimpleGeometryParameter::Calculate();
        layer_angle4rotate.resize(LayerNo);
        layer_type.resize(LayerNo);
        layer_cell_startNo.resize(LayerNo+1);
        layer_cell_dphi.resize(LayerNo);
        for ( G4int i = 0; i < LayerNo; i++ ){
                //set layer_cell_startNo
                if ( i == 0 ){
                        layer_cell_startNo[i] = 0;
                }
                else{
                        layer_cell_startNo[i] = layer_cell_startNo[i-1] + layer_cell_num[i-1];
                }
                if ( i == LayerNo - 1 ){
                        layer_cell_startNo[i+1] = layer_cell_startNo[i] + layer_cell_num[i];
                }
                //set layer_angle4rotate
                layer_angle4rotate[i] = 2*pi*layer_ncells4rotate[i]/layer_cell_num[i];
                //set layer_cell_dphi
                layer_cell_dphi[i] = 2*pi/layer_cell_num[i];
                G4double R;
                if (i == LayerNo - 1) R = Cdc_RMax;
                else R = layer_RMin[i+1];
                //set layer_type
                if ( i == LayerNo -1 ){
                        layer_type[i] = 1;//TYPE 1: Out most layer
                }
                else if ( fabs(layer_ncells4rotate[i]) != fabs(layer_ncells4rotate[i+1]) ){
                        if ( layer_ncells4rotate[i] == 0 ){
                                layer_type[i] = 3;//TYPE 3: Axial layer beneath a stereo layer
                        }
                        else{
                                layer_type[i] = 5;//TYPE 5: Stereo layer beneath an axial layer
                        }
                }
                else if ( i != 0 ? fabs(layer_ncells4rotate[i]) != fabs(layer_ncells4rotate[i-1]) : 0 ){
                        if ( layer_ncells4rotate[i] == 0 ){
                                layer_type[i] = 4;//TYPE 4: Axial layer upon a stereo layer
                        }
                        else{
                                layer_type[i] = 2;//TYPE 2: Stereo layer upon an axial layer
                        }
                }
                else{
                        layer_type[i] = 0;//TYPE 0: Ordinary layer
                }
        }
}
double MyConfigure::CalFormula (G4String formula, int iRep = 0) [inherited]
Definition at line 23 of file MyConfigure.cc.
Referenced by SimpleGeometryParameter::Calculate(), and PrimaryGeneratorAction::ReadCard().
{
//      std::cout<<"TO Calculate for: \""<<formula<<"\" "<<iRep<<std::endl; // to be deleted
//      formula = ReplaceMacro(formula);
        TF1 *f1 = new TF1("f1", formula);
        double value = f1->Eval(iRep);
//      std::cout<<"\t=>"<<value<<std::endl;
        delete f1;
        return value;
}
bool CdcGeometryParameter::check_cellId (int layerId, int cellId) [inline, private]
Definition at line 192 of file CdcGeometryParameter.hh.
References layer_cell_num.
Referenced by get_layer_cell_phi(), and get_ReplicaNo().
{
                        if ( cellId < layer_cell_num[layerId] ) return true;
                        else{
                                std::cout<<"In CdcGeometryParameter, cellId is out of range! cellId = "<<cellId<<", cellNo= "<<layer_cell_num[layerId]<<std::endl;
                                return false;
                        }
                }
bool CdcGeometryParameter::check_layerId (int layerId) [inline, private]
Definition at line 185 of file CdcGeometryParameter.hh.
References LayerNo.
Referenced by get_layer_angle4rotate(), get_layer_cell_dphi(), get_layer_cell_num(), get_layer_cell_phi(), get_layer_firstWire(), get_layer_length(), get_layer_ncells4rotate(), get_layer_RMid(), get_layer_RMin(), get_layer_SPhi(), get_layer_type(), and get_ReplicaNo().
{
                        if ( layerId < LayerNo ) return true;
                        else{
                                std::cout<<"In CdcGeometryParameter, layerId is out of range! layerId = "<<layerId<<", LayerNo = "<<LayerNo<<std::endl;
                                return false;
                        }
                }
bool CdcGeometryParameter::check_LayerNo (int No) [inline, private]
Definition at line 199 of file CdcGeometryParameter.hh.
References LayerNo.
Referenced by CheckInfo().
{
                        if( No != LayerNo ){
                                std::cout<<"In CdcGeometryParameter::InitFromFile(), insufficient layer info! LayerNo = "<<LayerNo<<", whilie only "<<No<<" layers were found."<<std::endl;
                                return false;
                        }
                        else return true;
                }
bool CdcGeometryParameter::CheckInfo ()
Reimplemented from SimpleGeometryParameter.
Definition at line 110 of file CdcGeometryParameter.cc.
References check_LayerNo(), layer_length, and layer_RMin.
Referenced by InitFromFile().
{
        bool flag = false;// false means no problem
        flag = SimpleGeometryParameter::CheckInfo();
        if (flag) return flag;// if something is wrong with its Parent Class, then return the status.
        //examine
        if(     !check_LayerNo(layer_RMin.size()) ||
                        !check_LayerNo(layer_length.size()) ){
                flag = true;
        }
        return flag;
}
void MyVGeometryParameter::DEBUG (G4String content, int level = 1) [inline, inherited]
Definition at line 54 of file MyVGeometryParameter.hh.
Referenced by SimpleGeometryParameter::get_index(), SimpleGeometryParameter::InitFromFile(), and InitFromFile().
{
                        if (level >= 1){
                                G4Exception("MyVGeometryParameter","Run0031",
                                                FatalException, content);
                        }
                        else if (level == 0){
                                std::cout<<"In MyVGeometryParameter, "<<content<<std::endl;
                        }
                }
void CdcGeometryParameter::Dump () [virtual]
Reimplemented from SimpleGeometryParameter.
Definition at line 104 of file CdcGeometryParameter.cc.
References DumpInfo().
Referenced by CdcGeometrySvc::SetGeometry().
{
        DumpInfo();
}
void CdcGeometryParameter::DumpInfo (void)
Reimplemented from SimpleGeometryParameter.
Definition at line 268 of file CdcGeometryParameter.cc.
References Cdc_RMax, FieldWireMaterial, FieldWireRadius, layer_cell_num, layer_firstWire, layer_length, layer_ncells4rotate, layer_RMid, layer_RMin, layer_SPhi, layer_type, LayerNo, MotherLogicalVolume, SDVolumeName, SensitiveDetector, SignalWireMaterial, and SignalWireRadius.
Referenced by Dump().
{
        SimpleGeometryParameter::DumpInfo();// dump info of its Parent Class first
        std::cout<<"------CdcGeometry info :--------"<<std::endl;
        std::cout<<"=>General info:"<<std::endl;
        std::cout<<" MotherLogicalVolume:  "<<MotherLogicalVolume<<std::endl;
        std::cout<<" SensitiveDetector:    "<<SensitiveDetector<<std::endl;
        std::cout<<" SDVolumeName:         "<<SDVolumeName<<std::endl;
        std::cout<<"=>Wires info:"<<std::endl;
        std::cout<<" SignalWireRadius:     "<<SignalWireRadius/um<<"um"<<std::endl;
        std::cout<<" FieldWireRadius:      "<<FieldWireRadius/um<<"um"<<std::endl;
        std::cout<<" signalWire material:  "<<SignalWireMaterial<<std::endl;
        std::cout<<" fieldWire material:   "<<FieldWireMaterial<<std::endl;
        std::cout<<"=>Layers info:"<<std::endl;
        std::cout<<" LayerNo: "<<LayerNo<<std::endl;
        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<"No."
                <<std::setiosflags(std::ios::left)<<std::setw(7) <<"StartR"
                <<std::setiosflags(std::ios::left)<<std::setw(8) <<"MiddleR"
                <<std::setiosflags(std::ios::left)<<std::setw(7) <<"length"
                <<std::setiosflags(std::ios::left)<<std::setw(9) <<"StartPhi"
                <<std::setiosflags(std::ios::left)<<std::setw(11)<<"RotateCell"
                <<std::setiosflags(std::ios::left)<<std::setw(17)<<"FirstWire"
                <<std::setiosflags(std::ios::left)<<std::setw(7) <<"CellNo"
                <<std::setiosflags(std::ios::left)<<std::setw(5) <<"type"
                <<std::endl;
        std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                <<std::setiosflags(std::ios::left)<<std::setw(7) <<"mm"
                <<std::setiosflags(std::ios::left)<<std::setw(8) <<"mm"
                <<std::setiosflags(std::ios::left)<<std::setw(7) <<"mm"
                <<std::setiosflags(std::ios::left)<<std::setw(9) <<"rad"
                <<std::setiosflags(std::ios::left)<<std::setw(11)<<""
                <<std::setiosflags(std::ios::left)<<std::setw(17)<<"1:signal/0:field"
                <<std::setiosflags(std::ios::left)<<std::setw(7) <<""
                <<std::setiosflags(std::ios::left)<<std::setw(5) <<""
                <<std::endl;
        for ( G4int i = 0; i < LayerNo; i++ ){
                std::cout<<std::setiosflags(std::ios::left)<<std::setw(5) <<i
                        <<std::setiosflags(std::ios::left)<<std::setw(7) <<layer_RMin[i]/mm
                        <<std::setiosflags(std::ios::left)<<std::setw(8) <<layer_RMid[i]/mm
                        <<std::setiosflags(std::ios::left)<<std::setw(7) <<layer_length[i]/mm
                        <<std::setiosflags(std::ios::left)<<std::setw(9) <<layer_SPhi[i]/rad
                        <<std::setiosflags(std::ios::left)<<std::setw(11)<<layer_ncells4rotate[i]
                        <<std::setiosflags(std::ios::left)<<std::setw(17)<<layer_firstWire[i]
                        <<std::setiosflags(std::ios::left)<<std::setw(7) <<layer_cell_num[i]
                        <<std::setiosflags(std::ios::left)<<std::setw(5) <<layer_type[i]
                        <<std::endl;
        }
        std::cout<<"Out most radius: "<<Cdc_RMax<<"mm"<<std::endl;
}
bool MyConfigure::FindMacro (G4String word, G4String & value) [inherited]
Definition at line 87 of file MyConfigure.cc.
References MyConfigure::knownValueNames, and MyConfigure::knownValues.
Referenced by MyConfigure::Replace(), and MyConfigure::ReplaceMacro().
{
        bool found = false;
        for (int i = 0; i< knownValues.size(); i++){
                if (knownValueNames[i]==word){
                        value = knownValues[i];
                        found = true;
                        break;
                }
        }
        return found;
}
G4double SimpleGeometryParameter::get_b (G4int VolId) [inline, inherited]
Definition at line 179 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::vB.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return vB[VolId]; else return 0;}
G4double CdcGeometryParameter::get_b_cell () [inline]
Definition at line 172 of file CdcGeometryParameter.hh.
References b_cell.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return b_cell;}
G4double CdcGeometryParameter::get_b_FieldWire () [inline]
Definition at line 177 of file CdcGeometryParameter.hh.
References b_FieldWire.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return b_FieldWire;}
G4double CdcGeometryParameter::get_b_layer () [inline]
Definition at line 168 of file CdcGeometryParameter.hh.
References b_layer.
{return b_layer;}
G4double CdcGeometryParameter::get_b_SignalWire () [inline]
Definition at line 180 of file CdcGeometryParameter.hh.
References b_SignalWire.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return b_SignalWire;}
G4double SimpleGeometryParameter::get_BooleanSolid_Ephi (G4int BooleanSolidId, G4int j = 0) [inline, inherited]
Definition at line 168 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Ephi, and SimpleGeometryParameter::check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Ephi[BooleanSolidId][j]; else return 0;}
G4double SimpleGeometryParameter::get_BooleanSolid_Epsi (G4int BooleanSolidId, G4int j = 0) [inline, inherited]
Definition at line 170 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Epsi, and SimpleGeometryParameter::check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Epsi[BooleanSolidId][j]; else return 0;}
G4double SimpleGeometryParameter::get_BooleanSolid_Etheta (G4int BooleanSolidId, G4int j = 0) [inline, inherited]
Definition at line 169 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Etheta, and SimpleGeometryParameter::check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Etheta[BooleanSolidId][j]; else return 0;}
G4double SimpleGeometryParameter::get_BooleanSolid_PosX (G4int BooleanSolidId, G4int j = 0) [inline, inherited]
Definition at line 171 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Pos, and SimpleGeometryParameter::check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Pos[BooleanSolidId][j].x(); else return 0;}
G4double SimpleGeometryParameter::get_BooleanSolid_PosY (G4int BooleanSolidId, G4int j = 0) [inline, inherited]
Definition at line 172 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Pos, and SimpleGeometryParameter::check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Pos[BooleanSolidId][j].y(); else return 0;}
G4double SimpleGeometryParameter::get_BooleanSolid_PosZ (G4int BooleanSolidId, G4int j = 0) [inline, inherited]
Definition at line 173 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Pos, and SimpleGeometryParameter::check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_Pos[BooleanSolidId][j].z(); else return 0;}
G4String SimpleGeometryParameter::get_BooleanSolid_sol1 (G4int BooleanSolidId) [inline, inherited]
Definition at line 166 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_sol1, and SimpleGeometryParameter::check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_sol1[BooleanSolidId]; else return "";}
G4String SimpleGeometryParameter::get_BooleanSolid_sol2 (G4int BooleanSolidId) [inline, inherited]
Definition at line 167 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_sol2, and SimpleGeometryParameter::check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_sol2[BooleanSolidId]; else return "";}
G4String SimpleGeometryParameter::get_BooleanSolid_type (G4int BooleanSolidId) [inline, inherited]
Definition at line 165 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_type, and SimpleGeometryParameter::check_BooleanSolidId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BooleanSolidId(BooleanSolidId)) return BooleanSolid_type[BooleanSolidId]; else return "";}
G4double SimpleGeometryParameter::get_Box_X (G4int BoxId, G4int j = 0) [inline, inherited]
Definition at line 83 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Box_X, and SimpleGeometryParameter::check_BoxId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BoxId(BoxId)) return Box_X[BoxId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Box_Y (G4int BoxId, G4int j = 0) [inline, inherited]
Definition at line 84 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Box_Y, and SimpleGeometryParameter::check_BoxId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BoxId(BoxId)) return Box_Y[BoxId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Box_Z (G4int BoxId, G4int j = 0) [inline, inherited]
Definition at line 85 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Box_Z, and SimpleGeometryParameter::check_BoxId().
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_BoxId(BoxId)) return Box_Z[BoxId][j]; else return 0;}
G4int SimpleGeometryParameter::get_BoxNo () [inline, inherited]
Definition at line 82 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BoxNo.
{return BoxNo;}
G4double CdcGeometryParameter::get_Cdc_RMax () [inline]
Definition at line 102 of file CdcGeometryParameter.hh.
References Cdc_RMax.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return Cdc_RMax;}
G4String CdcGeometryParameter::get_CellMaterial () [inline]
Definition at line 96 of file CdcGeometryParameter.hh.
References CellMaterial.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return CellMaterial;}
bool MyVGeometryParameter::get_checkoverlap () [inline, inherited]
Definition at line 66 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::checkoverlap.
Referenced by CdcGeometrySvc::ConstructVolumes(), and SimpleGeometrySvc::PlaceVolumes().
{return checkoverlap;}
G4double SimpleGeometryParameter::get_Cons_Length (G4int ConsId, G4int j = 0) [inline, inherited]
Definition at line 140 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ConsId(), and SimpleGeometryParameter::Cons_Length.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_Length[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_RMax1 (G4int ConsId, G4int j = 0) [inline, inherited]
Definition at line 136 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ConsId(), and SimpleGeometryParameter::Cons_RMax1.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_RMax1[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_RMax2 (G4int ConsId, G4int j = 0) [inline, inherited]
Definition at line 138 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ConsId(), and SimpleGeometryParameter::Cons_RMax2.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_RMax2[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_RMin1 (G4int ConsId, G4int j = 0) [inline, inherited]
Definition at line 137 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ConsId(), and SimpleGeometryParameter::Cons_RMin1.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_RMin1[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_RMin2 (G4int ConsId, G4int j = 0) [inline, inherited]
Definition at line 139 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ConsId(), and SimpleGeometryParameter::Cons_RMin2.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_RMin2[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_SpanAng (G4int ConsId, G4int j = 0) [inline, inherited]
Definition at line 142 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ConsId(), and SimpleGeometryParameter::Cons_SpanAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_SpanAng[ConsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Cons_StartAng (G4int ConsId, G4int j = 0) [inline, inherited]
Definition at line 141 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ConsId(), and SimpleGeometryParameter::Cons_StartAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ConsId(ConsId)) return Cons_StartAng[ConsId][j]; else return 0;}
G4int SimpleGeometryParameter::get_ConsNo () [inline, inherited]
Definition at line 135 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::ConsNo.
{return ConsNo;}
G4double SimpleGeometryParameter::get_EllipticalTube_X (G4int EllipticalTubeId, G4int j = 0) [inline, inherited]
Definition at line 89 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_EllipticalTubeId(), and SimpleGeometryParameter::EllipticalTube_X.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_EllipticalTubeId(EllipticalTubeId)) return EllipticalTube_X[EllipticalTubeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_EllipticalTube_Y (G4int EllipticalTubeId, G4int j = 0) [inline, inherited]
Definition at line 90 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_EllipticalTubeId(), and SimpleGeometryParameter::EllipticalTube_Y.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_EllipticalTubeId(EllipticalTubeId)) return EllipticalTube_Y[EllipticalTubeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_EllipticalTube_Z (G4int EllipticalTubeId, G4int j = 0) [inline, inherited]
Definition at line 91 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_EllipticalTubeId(), and SimpleGeometryParameter::EllipticalTube_Z.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_EllipticalTubeId(EllipticalTubeId)) return EllipticalTube_Z[EllipticalTubeId][j]; else return 0;}
G4int SimpleGeometryParameter::get_EllipticalTubeNo () [inline, inherited]
Definition at line 88 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::EllipticalTubeNo.
{return EllipticalTubeNo;}
G4double SimpleGeometryParameter::get_Ephi (G4int VolId, G4int j = 0) [inline, inherited]
Definition at line 76 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::Ephi.
Referenced by SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return Ephi[VolId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Epsi (G4int VolId, G4int j = 0) [inline, inherited]
Definition at line 78 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::Epsi.
Referenced by SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return Epsi[VolId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Etheta (G4int VolId, G4int j = 0) [inline, inherited]
Definition at line 77 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::Etheta.
Referenced by SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return Etheta[VolId][j]; else return 0;}
G4int SimpleGeometryParameter::get_ExtrudedSolid_numP (G4int ExtrudedSolidId, G4int j = 0) [inline, inherited]
Definition at line 156 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), and SimpleGeometryParameter::ExtrudedSolid_numP.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId)) return ExtrudedSolid_numP[ExtrudedSolidId]; else return 0;}
G4int SimpleGeometryParameter::get_ExtrudedSolid_numZ (G4int ExtrudedSolidId, G4int j = 0) [inline, inherited]
Definition at line 155 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), and SimpleGeometryParameter::ExtrudedSolid_numZ.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId)) return ExtrudedSolid_numZ[ExtrudedSolidId]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_Scale (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline, inherited]
Definition at line 162 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, and SimpleGeometryParameter::ExtrudedSolid_Scale.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) return ExtrudedSolid_Scale[ExtrudedSolidId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_X (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline, inherited]
Definition at line 157 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numP, and SimpleGeometryParameter::ExtrudedSolid_X.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numP[ExtrudedSolidId]) return ExtrudedSolid_X[ExtrudedSolidId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_X0 (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline, inherited]
Definition at line 160 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, and SimpleGeometryParameter::ExtrudedSolid_X0.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) return ExtrudedSolid_X0[ExtrudedSolidId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_Y (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline, inherited]
Definition at line 158 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numP, and SimpleGeometryParameter::ExtrudedSolid_Y.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numP[ExtrudedSolidId]) return ExtrudedSolid_Y[ExtrudedSolidId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_Y0 (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline, inherited]
Definition at line 161 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, and SimpleGeometryParameter::ExtrudedSolid_Y0.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) return ExtrudedSolid_Y0[ExtrudedSolidId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_ExtrudedSolid_Z (G4int ExtrudedSolidId, G4int i, G4int j = 0) [inline, inherited]
Definition at line 159 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, and SimpleGeometryParameter::ExtrudedSolid_Z.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) return ExtrudedSolid_Z[ExtrudedSolidId][i][j]; else return 0;}
G4int SimpleGeometryParameter::get_ExtrudedSolidNo () [inline, inherited]
Definition at line 154 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::ExtrudedSolidNo.
{return ExtrudedSolidNo;}
G4String CdcGeometryParameter::get_FieldWireMaterial () [inline]
Definition at line 95 of file CdcGeometryParameter.hh.
References FieldWireMaterial.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return FieldWireMaterial;}
G4double CdcGeometryParameter::get_FieldWireRadius () [inline]
Definition at line 98 of file CdcGeometryParameter.hh.
References FieldWireRadius.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return FieldWireRadius;}
G4String MyVGeometryParameter::get_filename () [inline, inherited]
Definition at line 69 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::m_filename.
{ return m_filename; }
G4double SimpleGeometryParameter::get_g (G4int VolId) [inline, inherited]
Definition at line 178 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::vG.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return vG[VolId]; else return 0;}
G4double CdcGeometryParameter::get_g_cell () [inline]
Definition at line 171 of file CdcGeometryParameter.hh.
References g_cell.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return g_cell;}
G4double CdcGeometryParameter::get_g_FieldWire () [inline]
Definition at line 176 of file CdcGeometryParameter.hh.
References g_FieldWire.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return g_FieldWire;}
G4double CdcGeometryParameter::get_g_layer () [inline]
Definition at line 167 of file CdcGeometryParameter.hh.
References g_layer.
{return g_layer;}
G4double CdcGeometryParameter::get_g_SignalWire () [inline]
Definition at line 179 of file CdcGeometryParameter.hh.
References g_SignalWire.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return g_SignalWire;}
G4double SimpleGeometryParameter::get_Hype_innerRadius (G4int HypeId, G4int j = 0) [inline, inherited]
Definition at line 120 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_HypeId(), and SimpleGeometryParameter::Hype_innerRadius.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_HypeId(HypeId)) return Hype_innerRadius[HypeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Hype_innerStereo (G4int HypeId, G4int j = 0) [inline, inherited]
Definition at line 122 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_HypeId(), and SimpleGeometryParameter::Hype_innerStereo.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_HypeId(HypeId)) return Hype_innerStereo[HypeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Hype_Length (G4int HypeId, G4int j = 0) [inline, inherited]
Definition at line 124 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_HypeId(), and SimpleGeometryParameter::Hype_Length.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_HypeId(HypeId)) return Hype_Length[HypeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Hype_outerRadius (G4int HypeId, G4int j = 0) [inline, inherited]
Definition at line 121 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_HypeId(), and SimpleGeometryParameter::Hype_outerRadius.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_HypeId(HypeId)) return Hype_outerRadius[HypeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Hype_outerStereo (G4int HypeId, G4int j = 0) [inline, inherited]
Definition at line 123 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_HypeId(), and SimpleGeometryParameter::Hype_outerStereo.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_HypeId(HypeId)) return Hype_outerStereo[HypeId][j]; else return 0;}
G4int SimpleGeometryParameter::get_HypeNo () [inline, inherited]
Definition at line 119 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::HypeNo.
{return HypeNo;}
G4double CdcGeometryParameter::get_layer_angle4rotate (G4int layerId) [inline]
Definition at line 123 of file CdcGeometryParameter.hh.
References check_layerId(), and layer_angle4rotate.
Referenced by CdcIonSD::CalculateHitInfo(), CdcGeometrySvc::ConstructVolumes(), and CdcSD::FindClosestPoint().
{
                        if( check_layerId(layerId) ) return layer_angle4rotate[layerId];
                        else return 0;
                }
G4double CdcGeometryParameter::get_layer_cell_dphi (G4int layerId) [inline]
Definition at line 139 of file CdcGeometryParameter.hh.
References check_layerId(), and layer_cell_dphi.
Referenced by CdcGeometrySvc::ConstructVolumes().
{
                        if( check_layerId(layerId) ) return layer_cell_dphi[layerId];
                        else return 0;
                }
G4int CdcGeometryParameter::get_layer_cell_num (G4int layerId) [inline]
Definition at line 127 of file CdcGeometryParameter.hh.
References check_layerId(), and layer_cell_num.
Referenced by CdcGeometrySvc::ConstructVolumes(), CdcSimpleSD::Initialize(), CdcSD::Initialize(), and CdcIonSD::Initialize().
{
                        if( check_layerId(layerId) ) return layer_cell_num[layerId];
                        else return 0;
                }
G4double CdcGeometryParameter::get_layer_cell_phi (G4int layerId, G4int cellId) [inline]
Definition at line 158 of file CdcGeometryParameter.hh.
References check_cellId(), check_layerId(), layer_angle4rotate, layer_cell_dphi, layer_firstWire, and layer_SPhi.
Referenced by CdcIonSD::CalculateHitInfo(), CdcGeometrySvc::ConstructVolumes(), and CdcSD::FindClosestPoint().
{
                        if( !check_layerId(layerId) || !check_cellId(layerId, cellId) ) return 0;
                        G4double phi = layer_SPhi[layerId] + layer_angle4rotate[layerId]/2. + (cellId + ( 1. - layer_firstWire[layerId] )/2. )*layer_cell_dphi[layerId];
                        return phi;
                }
G4int CdcGeometryParameter::get_layer_firstWire (G4int layerId) [inline]
Definition at line 131 of file CdcGeometryParameter.hh.
References check_layerId(), and layer_firstWire.
{
                        if( check_layerId(layerId) ) return layer_firstWire[layerId];
                        else return 0;
                }
G4double CdcGeometryParameter::get_layer_length (G4int layerId) [inline]
Definition at line 103 of file CdcGeometryParameter.hh.
References check_layerId(), and layer_length.
Referenced by CdcIonSD::CalculateHitInfo(), CdcGeometrySvc::ConstructVolumes(), and CdcSD::FindClosestPoint().
{
                        if( check_layerId(layerId) ) return layer_length[layerId];
                        else return 0;
                }
G4double CdcGeometryParameter::get_layer_ncells4rotate (G4int layerId) [inline]
Definition at line 119 of file CdcGeometryParameter.hh.
References check_layerId(), and layer_ncells4rotate.
{
                        if( check_layerId(layerId) ) return layer_ncells4rotate[layerId];
                        else return 0;
                }
G4double CdcGeometryParameter::get_layer_RMid (G4int layerId) [inline]
Definition at line 111 of file CdcGeometryParameter.hh.
References check_layerId(), and layer_RMid.
Referenced by CdcIonSD::CalculateHitInfo(), CdcGeometrySvc::ConstructVolumes(), and CdcSD::FindClosestPoint().
{
                        if( check_layerId(layerId) ) return layer_RMid[layerId];
                        else return 0;
                }
G4double CdcGeometryParameter::get_layer_RMin (G4int layerId) [inline]
Definition at line 107 of file CdcGeometryParameter.hh.
References check_layerId(), and layer_RMin.
Referenced by CdcGeometrySvc::ConstructVolumes().
{
                        if( check_layerId(layerId) ) return layer_RMin[layerId];
                        else return 0;
                }
G4double CdcGeometryParameter::get_layer_SPhi (G4int layerId) [inline]
Definition at line 115 of file CdcGeometryParameter.hh.
References check_layerId(), and layer_SPhi.
{
                        if( check_layerId(layerId) ) return layer_SPhi[layerId];
                        else return 0;
                }
G4int CdcGeometryParameter::get_layer_type (G4int layerId) [inline]
Definition at line 135 of file CdcGeometryParameter.hh.
References check_layerId(), and layer_type.
Referenced by CdcGeometrySvc::ConstructVolumes().
{
                        if( check_layerId(layerId) ) return layer_type[layerId];
                        else return 0;
                }
G4int CdcGeometryParameter::get_layerIdcellId (G4int ReplicaNo, G4int * layerId, G4int * cellId) [inline]
Definition at line 147 of file CdcGeometryParameter.hh.
References layer_cell_startNo, and LayerNo.
Referenced by CdcSimpleSD::ProcessHits(), CdcSD::ProcessHits(), and CdcIonSD::ProcessHits().
{
                        for ( G4int i = 0; i <= LayerNo; i++ ){
                                if ( ReplicaNo < layer_cell_startNo[i] ){
                                        *layerId = i - 1;
                                        *cellId = ReplicaNo - layer_cell_startNo[i-1];
                                        return 0;//found it
                                }
                        }
                        return 1;//not found!
                }
G4int CdcGeometryParameter::get_LayerNo () [inline]
Definition at line 101 of file CdcGeometryParameter.hh.
References LayerNo.
Referenced by CdcGeometrySvc::ConstructVolumes(), CdcSimpleSD::Initialize(), CdcSD::Initialize(), and CdcIonSD::Initialize().
{return LayerNo;}
G4String SimpleGeometryParameter::get_material (G4int VolId) [inline, inherited]
Definition at line 71 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::Material.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return Material[VolId]; else return "";}
G4String CdcGeometryParameter::get_MotherLogicalVolume () [inline]
Definition at line 89 of file CdcGeometryParameter.hh.
References MotherLogicalVolume.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return MotherLogicalVolume;}
G4String SimpleGeometryParameter::get_MotherName (G4int VolId) [inline, inherited]
Definition at line 70 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::MotherName.
Referenced by SimpleGeometrySvc::PlaceVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return MotherName[VolId]; else return "";}
G4String MyVGeometryParameter::get_Name () [inline, inherited]
Definition at line 68 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::m_Name.
{ return m_Name; }
G4String SimpleGeometryParameter::get_name (G4int VolId) [inline, inherited]
Definition at line 68 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::Name.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return Name[VolId]; else return "";}
G4int SimpleGeometryParameter::get_Polycone_numZ (G4int PolyconeId, G4int j = 0) [inline, inherited]
Definition at line 146 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), and SimpleGeometryParameter::Polycone_numZ.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId)) return Polycone_numZ[PolyconeId]; else return 0;}
G4double SimpleGeometryParameter::get_Polycone_RMax (G4int PolyconeId, G4int i, G4int j = 0) [inline, inherited]
Definition at line 147 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::Polycone_numZ, and SimpleGeometryParameter::Polycone_RMax.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) return Polycone_RMax[PolyconeId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_Polycone_RMin (G4int PolyconeId, G4int i, G4int j = 0) [inline, inherited]
Definition at line 148 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::Polycone_numZ, and SimpleGeometryParameter::Polycone_RMin.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) return Polycone_RMin[PolyconeId][i][j]; else return 0;}
G4double SimpleGeometryParameter::get_Polycone_SpanAng (G4int PolyconeId, G4int j = 0) [inline, inherited]
Definition at line 151 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), and SimpleGeometryParameter::Polycone_SpanAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId)) return Polycone_SpanAng[PolyconeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Polycone_StartAng (G4int PolyconeId, G4int j = 0) [inline, inherited]
Definition at line 150 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), and SimpleGeometryParameter::Polycone_StartAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId)) return Polycone_StartAng[PolyconeId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Polycone_Z (G4int PolyconeId, G4int i, G4int j = 0) [inline, inherited]
Definition at line 149 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::Polycone_numZ, and SimpleGeometryParameter::Polycone_Z.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) return Polycone_Z[PolyconeId][i][j]; else return 0;}
G4int SimpleGeometryParameter::get_PolyconeNo () [inline, inherited]
Definition at line 145 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::PolyconeNo.
{return PolyconeNo;}
G4double SimpleGeometryParameter::get_PosX (G4int VolId, G4int j = 0) [inline, inherited]
Definition at line 65 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::Pos.
Referenced by SimpleGeometrySvc::PlaceVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return Pos[VolId][j].x(); else return 0;}
G4double SimpleGeometryParameter::get_PosY (G4int VolId, G4int j = 0) [inline, inherited]
Definition at line 66 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::Pos.
Referenced by SimpleGeometrySvc::PlaceVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return Pos[VolId][j].y(); else return 0;}
G4double SimpleGeometryParameter::get_PosZ (G4int VolId, G4int j = 0) [inline, inherited]
Definition at line 67 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::Pos.
Referenced by SimpleGeometrySvc::PlaceVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return Pos[VolId][j].z(); else return 0;}
G4double SimpleGeometryParameter::get_r (G4int VolId) [inline, inherited]
Definition at line 177 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::vR.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return vR[VolId]; else return 0;}
G4double CdcGeometryParameter::get_r_cell () [inline]
Definition at line 170 of file CdcGeometryParameter.hh.
References r_cell.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return r_cell;}
G4double CdcGeometryParameter::get_r_FieldWire () [inline]
Definition at line 175 of file CdcGeometryParameter.hh.
References r_FieldWire.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return r_FieldWire;}
G4double CdcGeometryParameter::get_r_layer () [inline]
Definition at line 166 of file CdcGeometryParameter.hh.
References r_layer.
{return r_layer;}
G4double CdcGeometryParameter::get_r_SignalWire () [inline]
Definition at line 178 of file CdcGeometryParameter.hh.
References r_SignalWire.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return r_SignalWire;}
void MyVGeometryParameter::get_RepCont (G4String RepCont, G4int & SRepNo, G4int & RepNo) [inherited]
Definition at line 84 of file MyVGeometryParameter.cc.
References MyString2Anything::get_I().
Referenced by SimpleGeometryParameter::GetValue().
{
        size_t sLast = RepCont.last(',');
        if(sLast!=G4String::npos){
                G4String part1 = RepCont.substr(0,sLast);
                G4String part2 = RepCont.substr(sLast+1,RepCont.length()-sLast-1);
                MyString2Anything::get_I(part1,SRepNo);
                MyString2Anything::get_I(part2,RepNo);
        }
        else{ // not found
                sLast = RepCont.last('-');
                if (sLast==G4String::npos){// not found
                        sLast = RepCont.last('~');
                }
                if (sLast!=G4String::npos){
                        G4String part1 = RepCont.substr(0,sLast);
                        G4String part2 = RepCont.substr(sLast+1,RepCont.length()-sLast-1);
                        MyString2Anything::get_I(part1,SRepNo);
                        G4int endNo;
                        MyString2Anything::get_I(part2,endNo);
                        RepNo = endNo - SRepNo + 1;
                }
                else{// not found
                        SRepNo = 0;
                        MyString2Anything::get_I(RepCont,RepNo);
                }
        }
//      std::cout<<"in get_RepCont: \""<<RepCont<<"\" -> ("<<SRepNo<<","<<RepNo<<")"<<std::endl; // to be deleted
}
G4int CdcGeometryParameter::get_ReplicaNo (G4int layerId, G4int cellId) [inline]
Definition at line 143 of file CdcGeometryParameter.hh.
References check_cellId(), check_layerId(), and layer_cell_startNo.
Referenced by CdcGeometrySvc::ConstructVolumes().
{
                        if( check_layerId(layerId) && check_cellId(layerId, cellId) ) return cellId + layer_cell_startNo[layerId];
                        else return 0;
                }
G4int SimpleGeometryParameter::get_RepNo (G4int VolId) [inline, inherited]
Definition at line 73 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::RepNo.
Referenced by SimpleGeometrySvc::ConstructVolumes(), SimpleGeometrySvc::PlaceVolumes(), CdcLayerSD::ProcessHits(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return RepNo[VolId]; else return 0;}
G4String SimpleGeometryParameter::get_SDName (G4int VolId) [inline, inherited]
Definition at line 69 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::SDName.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return SDName[VolId]; else return "";}
G4String CdcGeometryParameter::get_SDVolumeName () [inline]
Definition at line 91 of file CdcGeometryParameter.hh.
References SDVolumeName.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return SDVolumeName;}
G4String CdcGeometryParameter::get_SensitiveDetector () [inline]
Definition at line 90 of file CdcGeometryParameter.hh.
References SensitiveDetector.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return SensitiveDetector;}
G4String CdcGeometryParameter::get_SignalWireMaterial () [inline]
Definition at line 94 of file CdcGeometryParameter.hh.
References SignalWireMaterial.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return SignalWireMaterial;}
G4double CdcGeometryParameter::get_SignalWireRadius () [inline]
Definition at line 97 of file CdcGeometryParameter.hh.
References SignalWireRadius.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return SignalWireRadius;}
G4bool SimpleGeometryParameter::get_SolidBoolean (G4int VolId) [inline, inherited]
Definition at line 79 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::SolidBoolean.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return SolidBoolean[VolId]; else return false;}
G4int SimpleGeometryParameter::get_SolidIndex (G4int VolId) [inline, inherited]
Definition at line 75 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::SolidIndex.
Referenced by SimpleGeometrySvc::ConstructVolumes(), CdcLayerSD::ProcessHits(), SimpleGeometryParameter::set_BooleanSolid_Ephi(), SimpleGeometryParameter::set_BooleanSolid_Epsi(), SimpleGeometryParameter::set_BooleanSolid_Etheta(), SimpleGeometryParameter::set_BooleanSolid_PosX(), SimpleGeometryParameter::set_BooleanSolid_PosY(), SimpleGeometryParameter::set_BooleanSolid_PosZ(), SimpleGeometryParameter::set_BooleanSolid_sol1(), SimpleGeometryParameter::set_BooleanSolid_sol2(), SimpleGeometryParameter::set_BooleanSolid_type(), SimpleGeometryParameter::set_Box_X(), SimpleGeometryParameter::set_Box_Y(), SimpleGeometryParameter::set_Box_Z(), SimpleGeometryParameter::set_Cons_Length(), SimpleGeometryParameter::set_Cons_RMax1(), SimpleGeometryParameter::set_Cons_RMax2(), SimpleGeometryParameter::set_Cons_RMin1(), SimpleGeometryParameter::set_Cons_RMin2(), SimpleGeometryParameter::set_Cons_SpanAng(), SimpleGeometryParameter::set_Cons_StartAng(), SimpleGeometryParameter::set_EllipticalTube_X(), SimpleGeometryParameter::set_EllipticalTube_Y(), SimpleGeometryParameter::set_EllipticalTube_Z(), SimpleGeometryParameter::set_ExtrudedSolid_numP(), SimpleGeometryParameter::set_ExtrudedSolid_numZ(), SimpleGeometryParameter::set_ExtrudedSolid_Scale(), SimpleGeometryParameter::set_ExtrudedSolid_X(), SimpleGeometryParameter::set_ExtrudedSolid_X0(), SimpleGeometryParameter::set_ExtrudedSolid_Y(), SimpleGeometryParameter::set_ExtrudedSolid_Y0(), SimpleGeometryParameter::set_ExtrudedSolid_Z(), SimpleGeometryParameter::set_Hype_innerRadius(), SimpleGeometryParameter::set_Hype_innerStereo(), SimpleGeometryParameter::set_Hype_Length(), SimpleGeometryParameter::set_Hype_outerRadius(), SimpleGeometryParameter::set_Hype_outerStereo(), SimpleGeometryParameter::set_Polycone_numZ(), SimpleGeometryParameter::set_Polycone_RMax(), SimpleGeometryParameter::set_Polycone_RMin(), SimpleGeometryParameter::set_Polycone_SpanAng(), SimpleGeometryParameter::set_Polycone_StartAng(), SimpleGeometryParameter::set_Polycone_Z(), SimpleGeometryParameter::set_Sphere_RMax(), SimpleGeometryParameter::set_Sphere_RMin(), SimpleGeometryParameter::set_Sphere_SpanPhi(), SimpleGeometryParameter::set_Sphere_SpanTheta(), SimpleGeometryParameter::set_Sphere_StartPhi(), SimpleGeometryParameter::set_Sphere_StartTheta(), SimpleGeometryParameter::set_Torus_RMax(), SimpleGeometryParameter::set_Torus_RMin(), SimpleGeometryParameter::set_Torus_Rtor(), SimpleGeometryParameter::set_Torus_SpanAng(), SimpleGeometryParameter::set_Torus_StartAng(), SimpleGeometryParameter::set_Tubs_Length(), SimpleGeometryParameter::set_Tubs_RMax(), SimpleGeometryParameter::set_Tubs_RMin(), SimpleGeometryParameter::set_Tubs_SpanAng(), SimpleGeometryParameter::set_Tubs_StartAng(), SimpleGeometryParameter::set_TwistedTubs_dphi(), SimpleGeometryParameter::set_TwistedTubs_endinnerrad(), SimpleGeometryParameter::set_TwistedTubs_endouterrad(), SimpleGeometryParameter::set_TwistedTubs_Length(), SimpleGeometryParameter::set_TwistedTubs_twistedangle(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return SolidIndex[VolId]; else return 0;}
G4String SimpleGeometryParameter::get_SolidType (G4int VolId) [inline, inherited]
Definition at line 74 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::SolidType.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_VolId(VolId)) return SolidType[VolId]; else return "";}
G4double SimpleGeometryParameter::get_Sphere_RMax (G4int SphereId, G4int j = 0) [inline, inherited]
Definition at line 111 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_SphereId(), and SimpleGeometryParameter::Sphere_RMax.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_RMax[SphereId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Sphere_RMin (G4int SphereId, G4int j = 0) [inline, inherited]
Definition at line 112 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_SphereId(), and SimpleGeometryParameter::Sphere_RMin.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_RMin[SphereId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Sphere_SpanPhi (G4int SphereId, G4int j = 0) [inline, inherited]
Definition at line 114 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_SphereId(), and SimpleGeometryParameter::Sphere_SpanPhi.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_SpanPhi[SphereId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Sphere_SpanTheta (G4int SphereId, G4int j = 0) [inline, inherited]
Definition at line 116 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_SphereId(), and SimpleGeometryParameter::Sphere_SpanTheta.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_SpanTheta[SphereId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Sphere_StartPhi (G4int SphereId, G4int j = 0) [inline, inherited]
Definition at line 113 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_SphereId(), and SimpleGeometryParameter::Sphere_StartPhi.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_StartPhi[SphereId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Sphere_StartTheta (G4int SphereId, G4int j = 0) [inline, inherited]
Definition at line 115 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_SphereId(), and SimpleGeometryParameter::Sphere_StartTheta.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_SphereId(SphereId)) return Sphere_StartTheta[SphereId][j]; else return 0;}
G4int SimpleGeometryParameter::get_SphereNo () [inline, inherited]
Definition at line 110 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::SphereNo.
{return SphereNo;}
G4int SimpleGeometryParameter::get_SRepNo (G4int VolId) [inline, inherited]
Definition at line 72 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::SRepNo.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and SimpleGeometrySvc::PlaceVolumes().
{if(check_VolId(VolId)) return SRepNo[VolId]; else return 0;}
G4double SimpleGeometryParameter::get_t (G4int VolId) [inline, inherited]
Definition at line 180 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::vT.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return vT[VolId]; else return 0;}
G4double SimpleGeometryParameter::get_Torus_RMax (G4int TorusId, G4int j = 0) [inline, inherited]
Definition at line 103 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TorusId(), and SimpleGeometryParameter::Torus_RMax.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TorusId(TorusId)) return Torus_RMax[TorusId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Torus_RMin (G4int TorusId, G4int j = 0) [inline, inherited]
Definition at line 104 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TorusId(), and SimpleGeometryParameter::Torus_RMin.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TorusId(TorusId)) return Torus_RMin[TorusId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Torus_Rtor (G4int TorusId, G4int j = 0) [inline, inherited]
Definition at line 105 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TorusId(), and SimpleGeometryParameter::Torus_Rtor.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TorusId(TorusId)) return Torus_Rtor[TorusId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Torus_SpanAng (G4int TorusId, G4int j = 0) [inline, inherited]
Definition at line 107 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TorusId(), and SimpleGeometryParameter::Torus_SpanAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TorusId(TorusId)) return Torus_SpanAng[TorusId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Torus_StartAng (G4int TorusId, G4int j = 0) [inline, inherited]
Definition at line 106 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TorusId(), and SimpleGeometryParameter::Torus_StartAng.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TorusId(TorusId)) return Torus_StartAng[TorusId][j]; else return 0;}
G4int SimpleGeometryParameter::get_TorusNo () [inline, inherited]
Definition at line 102 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::TorusNo.
{return TorusNo;}
G4double SimpleGeometryParameter::get_Tubs_Length (G4int TubsId, G4int j = 0) [inline, inherited]
Definition at line 97 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TubsId(), and SimpleGeometryParameter::Tubs_Length.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_TubsId(TubsId)) return Tubs_Length[TubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Tubs_RMax (G4int TubsId, G4int j = 0) [inline, inherited]
Definition at line 95 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TubsId(), and SimpleGeometryParameter::Tubs_RMax.
Referenced by SimpleGeometrySvc::ConstructVolumes(), CdcLayerSD::ProcessHits(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_TubsId(TubsId)) return Tubs_RMax[TubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Tubs_RMin (G4int TubsId, G4int j = 0) [inline, inherited]
Definition at line 96 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TubsId(), and SimpleGeometryParameter::Tubs_RMin.
Referenced by SimpleGeometrySvc::ConstructVolumes(), CdcLayerSD::ProcessHits(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_TubsId(TubsId)) return Tubs_RMin[TubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Tubs_SpanAng (G4int TubsId, G4int j = 0) [inline, inherited]
Definition at line 99 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TubsId(), and SimpleGeometryParameter::Tubs_SpanAng.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_TubsId(TubsId)) return Tubs_SpanAng[TubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_Tubs_StartAng (G4int TubsId, G4int j = 0) [inline, inherited]
Definition at line 98 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TubsId(), and SimpleGeometryParameter::Tubs_StartAng.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and PrimaryGeneratorAction::SetUniformPosition().
{if(check_TubsId(TubsId)) return Tubs_StartAng[TubsId][j]; else return 0;}
G4int SimpleGeometryParameter::get_TubsNo () [inline, inherited]
Definition at line 94 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::TubsNo.
{return TubsNo;}
G4double SimpleGeometryParameter::get_TwistedTubs_dphi (G4int TwistedTubsId, G4int j = 0) [inline, inherited]
Definition at line 132 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TwistedTubsId(), and SimpleGeometryParameter::TwistedTubs_dphi.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TwistedTubsId(TwistedTubsId)) return TwistedTubs_dphi[TwistedTubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_TwistedTubs_endinnerrad (G4int TwistedTubsId, G4int j = 0) [inline, inherited]
Definition at line 129 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TwistedTubsId(), and SimpleGeometryParameter::TwistedTubs_endinnerrad.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TwistedTubsId(TwistedTubsId)) return TwistedTubs_endinnerrad[TwistedTubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_TwistedTubs_endouterrad (G4int TwistedTubsId, G4int j = 0) [inline, inherited]
Definition at line 130 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TwistedTubsId(), and SimpleGeometryParameter::TwistedTubs_endouterrad.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TwistedTubsId(TwistedTubsId)) return TwistedTubs_endouterrad[TwistedTubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_TwistedTubs_Length (G4int TwistedTubsId, G4int j = 0) [inline, inherited]
Definition at line 131 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TwistedTubsId(), and SimpleGeometryParameter::TwistedTubs_Length.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TwistedTubsId(TwistedTubsId)) return TwistedTubs_Length[TwistedTubsId][j]; else return 0;}
G4double SimpleGeometryParameter::get_TwistedTubs_twistedangle (G4int TwistedTubsId, G4int j = 0) [inline, inherited]
Definition at line 128 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_TwistedTubsId(), and SimpleGeometryParameter::TwistedTubs_twistedangle.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_TwistedTubsId(TwistedTubsId)) return TwistedTubs_twistedangle[TwistedTubsId][j]; else return 0;}
G4int SimpleGeometryParameter::get_TwistedTubsNo () [inline, inherited]
Definition at line 127 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::TwistedTubsNo.
{return TwistedTubsNo;}
int MyVGeometryParameter::get_VerboseLevel () [inline, inherited]
Definition at line 67 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::fVerboseLevel.
{return fVerboseLevel;}
bool SimpleGeometryParameter::get_vis (G4int VolId) [inline, inherited]
Definition at line 176 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_VolId(), and SimpleGeometryParameter::vVis.
Referenced by SimpleGeometrySvc::ConstructVolumes().
{if(check_VolId(VolId)) return vVis[VolId]; else return 0;}
bool CdcGeometryParameter::get_vis_cell () [inline]
Definition at line 169 of file CdcGeometryParameter.hh.
References vis_cell.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return vis_cell;}
bool CdcGeometryParameter::get_vis_FieldWire () [inline]
Definition at line 173 of file CdcGeometryParameter.hh.
References vis_FieldWire.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return vis_FieldWire;}
bool CdcGeometryParameter::get_vis_layer () [inline]
Definition at line 165 of file CdcGeometryParameter.hh.
References vis_layer.
{return vis_layer;}
bool CdcGeometryParameter::get_vis_SignalWire () [inline]
Definition at line 174 of file CdcGeometryParameter.hh.
References vis_SignalWire.
Referenced by CdcGeometrySvc::ConstructVolumes().
{return vis_SignalWire;}
G4int SimpleGeometryParameter::get_VolIndex (G4String name) [inline, inherited]
Definition at line 54 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Name, and SimpleGeometryParameter::VolNo.
Referenced by MyDetectorManager::GetParaFromVolume(), SimpleGeometrySvc::PlaceVolumes(), CdcLayerSD::ProcessHits(), SimpleGeometryParameter::set_b(), SimpleGeometryParameter::set_BooleanSolid_Ephi(), SimpleGeometryParameter::set_BooleanSolid_Epsi(), SimpleGeometryParameter::set_BooleanSolid_Etheta(), SimpleGeometryParameter::set_BooleanSolid_PosX(), SimpleGeometryParameter::set_BooleanSolid_PosY(), SimpleGeometryParameter::set_BooleanSolid_PosZ(), SimpleGeometryParameter::set_BooleanSolid_sol1(), SimpleGeometryParameter::set_BooleanSolid_sol2(), SimpleGeometryParameter::set_BooleanSolid_type(), SimpleGeometryParameter::set_Box_X(), SimpleGeometryParameter::set_Box_Y(), SimpleGeometryParameter::set_Box_Z(), SimpleGeometryParameter::set_Cons_Length(), SimpleGeometryParameter::set_Cons_RMax1(), SimpleGeometryParameter::set_Cons_RMax2(), SimpleGeometryParameter::set_Cons_RMin1(), SimpleGeometryParameter::set_Cons_RMin2(), SimpleGeometryParameter::set_Cons_SpanAng(), SimpleGeometryParameter::set_Cons_StartAng(), SimpleGeometryParameter::set_EllipticalTube_X(), SimpleGeometryParameter::set_EllipticalTube_Y(), SimpleGeometryParameter::set_EllipticalTube_Z(), SimpleGeometryParameter::set_Ephi(), SimpleGeometryParameter::set_Epsi(), SimpleGeometryParameter::set_Etheta(), SimpleGeometryParameter::set_ExtrudedSolid_numP(), SimpleGeometryParameter::set_ExtrudedSolid_numZ(), SimpleGeometryParameter::set_ExtrudedSolid_Scale(), SimpleGeometryParameter::set_ExtrudedSolid_X(), SimpleGeometryParameter::set_ExtrudedSolid_X0(), SimpleGeometryParameter::set_ExtrudedSolid_Y(), SimpleGeometryParameter::set_ExtrudedSolid_Y0(), SimpleGeometryParameter::set_ExtrudedSolid_Z(), SimpleGeometryParameter::set_g(), SimpleGeometryParameter::set_Hype_innerRadius(), SimpleGeometryParameter::set_Hype_innerStereo(), SimpleGeometryParameter::set_Hype_Length(), SimpleGeometryParameter::set_Hype_outerRadius(), SimpleGeometryParameter::set_Hype_outerStereo(), SimpleGeometryParameter::set_material(), SimpleGeometryParameter::set_MotherName(), SimpleGeometryParameter::set_name(), SimpleGeometryParameter::set_Polycone_numZ(), SimpleGeometryParameter::set_Polycone_RMax(), SimpleGeometryParameter::set_Polycone_RMin(), SimpleGeometryParameter::set_Polycone_SpanAng(), SimpleGeometryParameter::set_Polycone_StartAng(), SimpleGeometryParameter::set_Polycone_Z(), SimpleGeometryParameter::set_PosX(), SimpleGeometryParameter::set_PosY(), SimpleGeometryParameter::set_PosZ(), SimpleGeometryParameter::set_r(), SimpleGeometryParameter::set_RepNo(), SimpleGeometryParameter::set_SDName(), SimpleGeometryParameter::set_SolidBoolean(), SimpleGeometryParameter::set_Sphere_RMax(), SimpleGeometryParameter::set_Sphere_RMin(), SimpleGeometryParameter::set_Sphere_SpanPhi(), SimpleGeometryParameter::set_Sphere_SpanTheta(), SimpleGeometryParameter::set_Sphere_StartPhi(), SimpleGeometryParameter::set_Sphere_StartTheta(), SimpleGeometryParameter::set_SRepNo(), SimpleGeometryParameter::set_t(), SimpleGeometryParameter::set_Torus_RMax(), SimpleGeometryParameter::set_Torus_RMin(), SimpleGeometryParameter::set_Torus_Rtor(), SimpleGeometryParameter::set_Torus_SpanAng(), SimpleGeometryParameter::set_Torus_StartAng(), SimpleGeometryParameter::set_Tubs_Length(), SimpleGeometryParameter::set_Tubs_RMax(), SimpleGeometryParameter::set_Tubs_RMin(), SimpleGeometryParameter::set_Tubs_SpanAng(), SimpleGeometryParameter::set_Tubs_StartAng(), SimpleGeometryParameter::set_TwistedTubs_dphi(), SimpleGeometryParameter::set_TwistedTubs_endinnerrad(), SimpleGeometryParameter::set_TwistedTubs_endouterrad(), SimpleGeometryParameter::set_TwistedTubs_Length(), SimpleGeometryParameter::set_TwistedTubs_twistedangle(), SimpleGeometryParameter::set_vis(), and PrimaryGeneratorAction::SetUniformPosition().
{
                        int index = -1;
                        for ( int i = 0; i < VolNo; i++ ){
                                if ( Name[i] == name ){
                                        index = i;
                                        break;
                                }
                        }
                        return index;
                }
G4int SimpleGeometryParameter::get_VolNo () [inline, inherited]
Definition at line 64 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::VolNo.
Referenced by SimpleGeometrySvc::ConstructVolumes(), and SimpleGeometrySvc::PlaceVolumes().
{ return VolNo; }
int CdcGeometryParameter::GetValue (G4String s_card)
Reimplemented from SimpleGeometryParameter.
Definition at line 133 of file CdcGeometryParameter.cc.
References b_cell, b_FieldWire, b_layer, b_SignalWire, Cdc_RMax, CellMaterial, FieldWireMaterial, FieldWireRadius, g_cell, g_FieldWire, g_layer, g_SignalWire, SimpleGeometryParameter::GetValue(), layer_cell_num, layer_firstWire, layer_length, layer_ncells4rotate, layer_RMid, layer_RMin, layer_SPhi, LayerNo, MotherLogicalVolume, r_cell, r_FieldWire, r_layer, r_SignalWire, SDVolumeName, SensitiveDetector, SignalWireMaterial, SignalWireRadius, vis_cell, vis_FieldWire, vis_layer, and vis_SignalWire.
Referenced by InitFromFile().
{
        if (!SimpleGeometryParameter::GetValue(s_card)) return 0; // if found by Parent Class, then return.
        int status = 0;// 0 means found the value
        std::stringstream buf_card;
        buf_card.str("");
        buf_card.clear();
        buf_card<<s_card;
        std::string name;
        buf_card>>name;
        std::string s_para;
        if( name == "MotherLogicalVolume:" ) buf_card>>MotherLogicalVolume;
        else if( name == "CellMaterial:" ) buf_card>>CellMaterial;
        else if( name == "SensitiveDetector:" ) buf_card>>SensitiveDetector;
        else if( name == "SDVolumeName:" ) buf_card>>SDVolumeName;
        else if( name == "SignalWireMaterial:" ) buf_card>>SignalWireMaterial;
        else if( name == "FieldWireMaterial:" ) buf_card>>FieldWireMaterial;
        else if( name == "SignalWireRadius:" ) {
                buf_card>>SignalWireRadius;
                SignalWireRadius *= um;
        }
        else if( name == "FieldWireRadius:" ) {
                buf_card>>FieldWireRadius;
                FieldWireRadius *= um;
        }
        else if( name == "LayerNo:" ) buf_card>>LayerNo;
        else if( name == "vis_layer" ){
                vis_layer = true;
                buf_card>>r_layer>>g_layer>>b_layer;
        }
        else if( name == "vis_cell" ){
                vis_cell = true;
                buf_card>>r_cell>>g_cell>>b_cell;
        }
        else if( name == "vis_FieldWire" ){
                vis_FieldWire = true;
                buf_card>>r_FieldWire>>g_FieldWire>>b_FieldWire;
        }
        else if( name == "vis_SignalWire" ){
                vis_SignalWire = true;
                buf_card>>r_SignalWire>>g_SignalWire>>b_SignalWire;
        }
        else{
                std::stringstream buf_temp;
                if( name == "F" ){
                        std::string dump;
                        G4double tlayer_RMin;
                        buf_card>>tlayer_RMin;
                        tlayer_RMin *= mm;
                        layer_RMin.push_back(tlayer_RMin);
                }
                else if( name == "S" ){
                        std::string dump;
                        G4int twire_num, tlayer_firstWire;
                        G4double tlayer_ncells4rotate;
                        G4double tlayer_RMid, tlayer_length, tlayer_SPhi;
                        buf_card>>dump>>dump>>twire_num>>tlayer_length>>tlayer_RMid>>tlayer_SPhi>>tlayer_firstWire>>tlayer_ncells4rotate;
                        tlayer_length *= mm;
                        tlayer_RMid *= mm;
                        tlayer_SPhi *= rad;
                        layer_cell_num.push_back(twire_num);
                        layer_length.push_back(tlayer_length);
                        layer_RMid.push_back(tlayer_RMid);
                        layer_SPhi.push_back(tlayer_SPhi);
                        layer_firstWire.push_back(tlayer_firstWire);
                        layer_ncells4rotate.push_back(tlayer_ncells4rotate);
                }
                else if( name == "LF" ){
                        std::string dump;
                        buf_card>>Cdc_RMax;
                }
                else{
                        status = 1;
                }
                buf_temp.str("");
                buf_temp.clear();
        }
        buf_card.str("");
        buf_card.clear();
        return status;
}
std::vector< G4String > MyConfigure::GetWords (G4String formula) [inherited]
Definition at line 48 of file MyConfigure.cc.
Referenced by MyConfigure::ReplaceMacro().
{
        std::vector<G4String> words;
        words.clear();
        const char* cformula = formula.c_str();
        int length = strlen(cformula);
        char temp[1240];
        int tempoffset = 0;
        for ( int offset = 0; offset < length; offset++ ){
                char c = cformula[offset];
                bool isword = false;
                if (c>='a'&&c<='z'
                        ||c>='A'&&c<='Z'
                        ||c>='0'&&c<='9'
                        ||c=='_'
                   ){
                        temp[tempoffset++] = cformula[offset];
                        isword = true;
                }
                if (!isword||offset==length-1){
                        if (tempoffset>0){
                                temp[tempoffset++] = '\0';
                                tempoffset=0;
                                G4String word = temp;
                                bool found = false;
                                for(int iWord = 0; iWord<words.size(); iWord++){
                                        if (words[iWord]==word){
                                                found = true;
                                                break;
                                        }
                                }
                                if (!found){
                                        words.push_back(word);
                                }
                        }
                }
        }
        return words;
}
void CdcGeometryParameter::InitFromFile (G4String file_name) [virtual]
Reimplemented from SimpleGeometryParameter.
Definition at line 77 of file CdcGeometryParameter.cc.
References Calculate(), CheckInfo(), MyVGeometryParameter::DEBUG(), GetValue(), MyVGeometryParameter::ISEMPTY(), Preset(), and MyVGeometryParameter::set_filename().
{
        set_filename(file_name);
        //Remember to preset first!
        Preset();
        std::ifstream fin_card(file_name);
        if(!fin_card){
                DEBUG("CdcGeometryParameter::InitFromFile(), cannot find subgeometry card: \""+file_name+"\"");
        }
        std::string s_card;
        while(getline(fin_card,s_card)){
                //eleminate useless lines
                if ( ISEMPTY(s_card) ) continue;
                int status = GetValue(s_card);
                if( status > 0 ){
                        G4String content = "CdcGeometryParameter: unknown line:" + s_card + "\n  in file " + file_name + "! Will ignore this line!";
                        DEBUG(content,0);
                }
        }
        fin_card.close();
        if (CheckInfo()){
                DEBUG("CdcGeometryParameter::InitFromFile(), insufficient simple solid info");
        }
        Calculate();
}
bool MyVGeometryParameter::ISEMPTY (G4String s_card) [inherited]
Definition at line 115 of file MyVGeometryParameter.cc.
Referenced by SimpleGeometryParameter::InitFromFile(), and InitFromFile().
{
        bool flag = false;
        const char* c_card = s_card.c_str();
        G4int length = strlen(c_card);
        G4int offset = 0;
        for ( ; offset < length; offset++ ){
                if ( c_card[offset] != ' ' ) break;
        }
        if ( c_card[offset] == '#' || (c_card[offset] == '/' && c_card[offset+1] == '/') || length - offset == 0 ){
                flag = true;
        }
        return flag;
}
void CdcGeometryParameter::Preset ()
Reimplemented from SimpleGeometryParameter.
Definition at line 123 of file CdcGeometryParameter.cc.
References LayerNo, vis_cell, vis_FieldWire, vis_layer, and vis_SignalWire.
Referenced by InitFromFile().
{
        SimpleGeometryParameter::Preset();// Call its Parent class to preset
        vis_cell = false;
        vis_layer = false;
        vis_SignalWire = false;
        vis_FieldWire = false;
        LayerNo = 0;
}
void MyConfigure::Replace (G4String & formula, G4String word, G4String value) [inherited]
Definition at line 99 of file MyConfigure.cc.
References MyConfigure::FindMacro().
Referenced by MyConfigure::ReplaceMacro().
{
//      std::cout<<"-- \""<<formula<<"\""<<std::endl; // to be deleted
        G4String newform = "";
        const char* cformula = formula.c_str();
        int length = strlen(cformula);
        char temp[1024];
        int tempoffset = 0;
        char cnewform[1024];
        int newformoffset = 0;
        for ( int offset = 0; offset < length; offset++ ){
                char c = cformula[offset];
                bool isword = false;
                if (c>='a'&&c<='z'
                        ||c>='A'&&c<='Z'
                        ||c>='0'&&c<='9'
                        ||c=='_'
                   ){
                        temp[tempoffset++] = cformula[offset];
                        isword = true;
                }
                if (!isword||offset==length-1){
                        if (tempoffset>0){
                                temp[tempoffset] = '\0';
                                tempoffset=0;
                                if (newformoffset>0){
                                        cnewform[newformoffset] = '\0';
                                        newformoffset=0;
                                        G4String newformtemp = cnewform;
                                        newform=newform+newformtemp;
                                }
                                G4String word = temp;
//                              std::cout<<"            \""<<word<<"\""<<std::endl; // to be deleted
                                G4String newword;
                                bool found = FindMacro(word,newword);
                                if (found){
                                        newform=newform+"("+newword+")";
                                }
                                else{
                                        newform=newform+word;
                                }
//                              std::cout<<"            to \""<<newword<<"\""<<std::endl; // to be deleted
                        }
                        if(!isword){
                                cnewform[newformoffset++] = cformula[offset];
                        }
                        if (offset==length-1){
                                cnewform[newformoffset] = '\0';
                                G4String newformtemp = cnewform;
                                newform=newform+newformtemp;
                        }
                }
        }
//      std::cout<<"    -->\""<<newform<<"\""<<std::endl; // to be deleted
        formula = newform;
}
G4String MyConfigure::ReplaceMacro (G4String formula) [inherited]
Definition at line 33 of file MyConfigure.cc.
References MyConfigure::FindMacro(), MyConfigure::GetWords(), and MyConfigure::Replace().
Referenced by SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
{
//      std::cout<<"TO replace for: \""<<formula<<"\""<<std::endl; // to be deleted
        std::vector<G4String> words = GetWords(formula);
//      std::cout<<"    "<<words.size()<<" words"<<std::endl; // to be deleted
        for (int iWord = 0; iWord < words.size(); iWord++ ){
//              std::cout<<"            "<<iWord<<std::endl; // to be deleted
                G4String value;
                if (FindMacro(words[iWord],value)){
                        Replace(formula,words[iWord],value);
                }
        }
//      std::cout<<"\t=>"<<formula<<std::endl;
        return formula;
}
void SimpleGeometryParameter::set_b (G4String name, G4double val) [inline, inherited]
Definition at line 385 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::vB.
{int k = get_VolIndex(name); vB[k] = val;}
void SimpleGeometryParameter::set_b (G4int i, G4double val) [inline, inherited]
Definition at line 379 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::vB.
{ vB[i] = val;}
void SimpleGeometryParameter::set_b (G4String type, G4int i, G4double val) [inline, inherited]
Definition at line 373 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::vB.
Referenced by SimpleGeometryParameter::GetValue(), and SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); vB[k] = val;}
void SimpleGeometryParameter::set_BooleanSolid_Ephi (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 362 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Ephi, SimpleGeometryParameter::check_BooleanSolidId(), SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Ephi[i][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_Ephi (G4int BooleanSolidId, G4double val, G4int j = 0) [inline, inherited]
Definition at line 352 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Ephi, and SimpleGeometryParameter::check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Ephi[BooleanSolidId][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_Epsi (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 364 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Epsi, SimpleGeometryParameter::check_BooleanSolidId(), SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Epsi[i][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_Epsi (G4int BooleanSolidId, G4double val, G4int j = 0) [inline, inherited]
Definition at line 354 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Epsi, and SimpleGeometryParameter::check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Epsi[BooleanSolidId][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_Etheta (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 363 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Etheta, SimpleGeometryParameter::check_BooleanSolidId(), SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Etheta[i][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_Etheta (G4int BooleanSolidId, G4double val, G4int j = 0) [inline, inherited]
Definition at line 353 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Etheta, and SimpleGeometryParameter::check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Etheta[BooleanSolidId][j]=val;}
void SimpleGeometryParameter::set_BooleanSolid_PosX (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 365 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Pos, SimpleGeometryParameter::check_BooleanSolidId(), SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Pos[i][j].setX(val);}
void SimpleGeometryParameter::set_BooleanSolid_PosX (G4int BooleanSolidId, G4double val, G4int j = 0) [inline, inherited]
Definition at line 355 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Pos, and SimpleGeometryParameter::check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Pos[BooleanSolidId][j].setX(val);}
void SimpleGeometryParameter::set_BooleanSolid_PosY (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 366 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Pos, SimpleGeometryParameter::check_BooleanSolidId(), SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Pos[i][j].setY(val);}
void SimpleGeometryParameter::set_BooleanSolid_PosY (G4int BooleanSolidId, G4double val, G4int j = 0) [inline, inherited]
Definition at line 356 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Pos, and SimpleGeometryParameter::check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Pos[BooleanSolidId][j].setY(val);}
void SimpleGeometryParameter::set_BooleanSolid_PosZ (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 367 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Pos, SimpleGeometryParameter::check_BooleanSolidId(), SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_Pos[i][j].setZ(val);}
void SimpleGeometryParameter::set_BooleanSolid_PosZ (G4int BooleanSolidId, G4double val, G4int j = 0) [inline, inherited]
Definition at line 357 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_Pos, and SimpleGeometryParameter::check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_Pos[BooleanSolidId][j].setZ(val);}
void SimpleGeometryParameter::set_BooleanSolid_sol1 (G4String name, G4String val) [inline, inherited]
Definition at line 360 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_sol1, SimpleGeometryParameter::check_BooleanSolidId(), SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_sol1[i]=val;}
void SimpleGeometryParameter::set_BooleanSolid_sol1 (G4int BooleanSolidId, G4String val) [inline, inherited]
Definition at line 350 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_sol1, and SimpleGeometryParameter::check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_sol1[BooleanSolidId]=val;}
void SimpleGeometryParameter::set_BooleanSolid_sol2 (G4String name, G4String val) [inline, inherited]
Definition at line 361 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_sol2, SimpleGeometryParameter::check_BooleanSolidId(), SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_sol2[i]=val;}
void SimpleGeometryParameter::set_BooleanSolid_sol2 (G4int BooleanSolidId, G4String val) [inline, inherited]
Definition at line 351 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_sol2, and SimpleGeometryParameter::check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_sol2[BooleanSolidId]=val;}
void SimpleGeometryParameter::set_BooleanSolid_type (G4String name, G4String val) [inline, inherited]
Definition at line 359 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_type, SimpleGeometryParameter::check_BooleanSolidId(), SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_BooleanSolidId(i)) BooleanSolid_type[i]=val;}
void SimpleGeometryParameter::set_BooleanSolid_type (G4int BooleanSolidId, G4String val) [inline, inherited]
Definition at line 349 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::BooleanSolid_type, and SimpleGeometryParameter::check_BooleanSolidId().
{if(check_BooleanSolidId(BooleanSolidId)) BooleanSolid_type[BooleanSolidId]=val;}
void SimpleGeometryParameter::set_Box_X (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 217 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Box_X, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Box_X[i][j] = val;}
void SimpleGeometryParameter::set_Box_X (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 213 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Box_X.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Box_X[i][j] = val;}
void SimpleGeometryParameter::set_Box_Y (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 218 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Box_Y, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Box_Y[i][j] = val;}
void SimpleGeometryParameter::set_Box_Y (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 214 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Box_Y.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Box_Y[i][j] = val;}
void SimpleGeometryParameter::set_Box_Z (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 219 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Box_Z, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Box_Z[i][j] = val;}
void SimpleGeometryParameter::set_Box_Z (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 215 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Box_Z.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Box_Z[i][j] = val;}
void MyVGeometryParameter::set_checkoverlap (bool val) [inline, inherited]
Definition at line 73 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::checkoverlap.
Referenced by MyVGeometryParameterMessenger::MySetNewValue().
{ checkoverlap = val;}
void SimpleGeometryParameter::set_Cons_Length (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 310 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_Length, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_Length[i][j] = val;}
void SimpleGeometryParameter::set_Cons_Length (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 302 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_Length.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_Length[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMax1 (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 306 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_RMax1, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_RMax1[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMax1 (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 298 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_RMax1.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_RMax1[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMax2 (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 308 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_RMax2, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_RMax2[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMax2 (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 300 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_RMax2.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_RMax2[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMin1 (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 307 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_RMin1, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_RMin1[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMin1 (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 299 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_RMin1.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_RMin1[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMin2 (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 309 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_RMin2, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_RMin2[i][j] = val;}
void SimpleGeometryParameter::set_Cons_RMin2 (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 301 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_RMin2.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_RMin2[i][j] = val;}
void SimpleGeometryParameter::set_Cons_SpanAng (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 312 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_SpanAng, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Cons_SpanAng (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 304 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_SpanAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Cons_StartAng (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 311 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_StartAng, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); Cons_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_Cons_StartAng (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 303 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Cons_StartAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Cons_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_X (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 226 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::EllipticalTube_X, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); EllipticalTube_X[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_X (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 222 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::EllipticalTube_X.
{ EllipticalTube_X[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_Y (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 227 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::EllipticalTube_Y, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); EllipticalTube_Y[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_Y (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 223 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::EllipticalTube_Y.
{ EllipticalTube_Y[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_Z (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 228 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::EllipticalTube_Z, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name)); EllipticalTube_Z[i][j] = val;}
void SimpleGeometryParameter::set_EllipticalTube_Z (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 224 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::EllipticalTube_Z.
{ EllipticalTube_Z[i][j] = val;}
void SimpleGeometryParameter::set_Ephi (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 208 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Ephi, and SimpleGeometryParameter::get_VolIndex().
{ int k = get_VolIndex(name); Ephi[k][j] = val;}
void SimpleGeometryParameter::set_Ephi (G4String type, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 193 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Ephi, and SimpleGeometryParameter::get_index().
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Ephi[k][j] = val;}
void SimpleGeometryParameter::set_Epsi (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 210 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Epsi, and SimpleGeometryParameter::get_VolIndex().
{ int k = get_VolIndex(name); Epsi[k][j] = val;}
void SimpleGeometryParameter::set_Epsi (G4String type, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 195 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Epsi, and SimpleGeometryParameter::get_index().
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Epsi[k][j] = val;}
void SimpleGeometryParameter::set_Etheta (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 209 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Etheta, and SimpleGeometryParameter::get_VolIndex().
{ int k = get_VolIndex(name); Etheta[k][j] = val;}
void SimpleGeometryParameter::set_Etheta (G4String type, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 194 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Etheta, and SimpleGeometryParameter::get_index().
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Etheta[k][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_numP (G4String name, G4int val, G4int j = 0) [inline, inherited]
Definition at line 340 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numP, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i)) ExtrudedSolid_numP[i] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_numP (G4int ExtrudedSolidId, G4int val, G4int j = 0) [inline, inherited]
Definition at line 331 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), and SimpleGeometryParameter::ExtrudedSolid_numP.
{if(check_ExtrudedSolidId(ExtrudedSolidId)) ExtrudedSolid_numP[ExtrudedSolidId] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_numZ (G4String name, G4int val, G4int j = 0) [inline, inherited]
Definition at line 339 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i)) ExtrudedSolid_numZ[i] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_numZ (G4int ExtrudedSolidId, G4int val, G4int j = 0) [inline, inherited]
Definition at line 330 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), and SimpleGeometryParameter::ExtrudedSolid_numZ.
{if(check_ExtrudedSolidId(ExtrudedSolidId)) ExtrudedSolid_numZ[ExtrudedSolidId] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Scale (G4String name, G4int iCone, G4double val, G4int j = 0) [inline, inherited]
Definition at line 346 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, SimpleGeometryParameter::ExtrudedSolid_Scale, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numZ[i]) ExtrudedSolid_Scale[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Scale (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 337 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, and SimpleGeometryParameter::ExtrudedSolid_Scale.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) ExtrudedSolid_Scale[ExtrudedSolidId][i][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_X (G4String name, G4int iCone, G4double val, G4int j = 0) [inline, inherited]
Definition at line 341 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numP, SimpleGeometryParameter::ExtrudedSolid_X, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numP[i]) ExtrudedSolid_X[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_X (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 332 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numP, and SimpleGeometryParameter::ExtrudedSolid_X.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numP[ExtrudedSolidId]) ExtrudedSolid_X[ExtrudedSolidId][i][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_X0 (G4String name, G4int iCone, G4double val, G4int j = 0) [inline, inherited]
Definition at line 344 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, SimpleGeometryParameter::ExtrudedSolid_X0, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numZ[i]) ExtrudedSolid_X0[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_X0 (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 335 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, and SimpleGeometryParameter::ExtrudedSolid_X0.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) ExtrudedSolid_X0[ExtrudedSolidId][i][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Y (G4String name, G4int iCone, G4double val, G4int j = 0) [inline, inherited]
Definition at line 342 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numP, SimpleGeometryParameter::ExtrudedSolid_Y, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numP[i]) ExtrudedSolid_Y[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Y (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 333 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numP, and SimpleGeometryParameter::ExtrudedSolid_Y.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numP[ExtrudedSolidId]) ExtrudedSolid_Y[ExtrudedSolidId][i][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Y0 (G4String name, G4int iCone, G4double val, G4int j = 0) [inline, inherited]
Definition at line 345 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, SimpleGeometryParameter::ExtrudedSolid_Y0, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numZ[i]) ExtrudedSolid_Y0[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Y0 (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 336 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, and SimpleGeometryParameter::ExtrudedSolid_Y0.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) ExtrudedSolid_Y0[ExtrudedSolidId][i][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Z (G4String name, G4int iCone, G4double val, G4int j = 0) [inline, inherited]
Definition at line 343 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, SimpleGeometryParameter::ExtrudedSolid_Z, SimpleGeometryParameter::get_SolidIndex(), and SimpleGeometryParameter::get_VolIndex().
{int i = get_SolidIndex(get_VolIndex(name));if(check_ExtrudedSolidId(i) && iCone < ExtrudedSolid_numZ[i]) ExtrudedSolid_Z[i][iCone][j] = val;}
void SimpleGeometryParameter::set_ExtrudedSolid_Z (G4int ExtrudedSolidId, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 334 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_ExtrudedSolidId(), SimpleGeometryParameter::ExtrudedSolid_numZ, and SimpleGeometryParameter::ExtrudedSolid_Z.
{if(check_ExtrudedSolidId(ExtrudedSolidId) && i < ExtrudedSolid_numZ[ExtrudedSolidId]) ExtrudedSolid_Z[ExtrudedSolidId][i][j] = val;}
void MyVGeometryParameter::set_filename (G4String val) [inline, inherited]
Definition at line 77 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::m_filename.
Referenced by SimpleGeometryParameter::InitFromFile(), and InitFromFile().
{ m_filename = val; }
void SimpleGeometryParameter::set_g (G4String name, G4double val) [inline, inherited]
Definition at line 384 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::vG.
{int k = get_VolIndex(name); vG[k] = val;}
void SimpleGeometryParameter::set_g (G4int i, G4double val) [inline, inherited]
Definition at line 378 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::vG.
{ vG[i] = val;}
void SimpleGeometryParameter::set_g (G4String type, G4int i, G4double val) [inline, inherited]
Definition at line 372 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::vG.
Referenced by SimpleGeometryParameter::GetValue(), and SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); vG[k] = val;}
void MyVGeometryParameter::set_GeometryParameterMessenger (MyVGeometryParameterMessenger * val) [inline, inherited]
Definition at line 75 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::m_GeometryParameterMessenger.
Referenced by CdcGeometryParameter(), and SimpleGeometryParameter::SimpleGeometryParameter().
{m_GeometryParameterMessenger = val;};
void SimpleGeometryParameter::set_Hype_innerRadius (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 278 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Hype_innerRadius.
{int i = get_SolidIndex(get_VolIndex(name)); Hype_innerRadius[i][j] = val;}
void SimpleGeometryParameter::set_Hype_innerRadius (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 272 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Hype_innerRadius.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Hype_innerRadius[i][j] = val;}
void SimpleGeometryParameter::set_Hype_innerStereo (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 280 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Hype_innerStereo.
{int i = get_SolidIndex(get_VolIndex(name)); Hype_innerStereo[i][j] = val;}
void SimpleGeometryParameter::set_Hype_innerStereo (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 274 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Hype_innerStereo.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Hype_innerStereo[i][j] = val;}
void SimpleGeometryParameter::set_Hype_Length (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 282 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Hype_Length.
{int i = get_SolidIndex(get_VolIndex(name)); Hype_Length[i][j] = val;}
void SimpleGeometryParameter::set_Hype_Length (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 276 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Hype_Length.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Hype_Length[i][j] = val;}
void SimpleGeometryParameter::set_Hype_outerRadius (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 279 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Hype_outerRadius.
{int i = get_SolidIndex(get_VolIndex(name)); Hype_outerRadius[i][j] = val;}
void SimpleGeometryParameter::set_Hype_outerRadius (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 273 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Hype_outerRadius.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Hype_outerRadius[i][j] = val;}
void SimpleGeometryParameter::set_Hype_outerStereo (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 281 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Hype_outerStereo.
{int i = get_SolidIndex(get_VolIndex(name)); Hype_outerStereo[i][j] = val;}
void SimpleGeometryParameter::set_Hype_outerStereo (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 275 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Hype_outerStereo.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Hype_outerStereo[i][j] = val;}
void SimpleGeometryParameter::set_material (G4String name, G4String val) [inline, inherited]
Definition at line 201 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Material.
{ int k = get_VolIndex(name); Material[k] = val;}
void SimpleGeometryParameter::set_material (G4String type, G4int i, G4String val) [inline, inherited]
Definition at line 190 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::Material.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Material[k] = val;}
void SimpleGeometryParameter::set_MotherName (G4String name, G4String val) [inline, inherited]
Definition at line 200 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::MotherName.
{ int k = get_VolIndex(name); MotherName[k] = val;}
void SimpleGeometryParameter::set_MotherName (G4String type, G4int i, G4String val) [inline, inherited]
Definition at line 189 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::MotherName.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); MotherName[k] = val;}
void MyVGeometryParameter::set_Name (G4String val) [inline, inherited]
Definition at line 76 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::m_Name.
Referenced by MyVGeometryParameter::MyVGeometryParameter().
{ m_Name = val; }
void SimpleGeometryParameter::set_name (G4String name, G4String val) [inline, inherited]
Definition at line 198 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Name.
{ int k = get_VolIndex(name); Name[k] = val;}
void SimpleGeometryParameter::set_name (G4String type, G4int i, G4String val) [inline, inherited]
Definition at line 187 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::Name.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Name[k] = val;}
void SimpleGeometryParameter::set_Polycone_numZ (G4String name, G4int val, G4int j = 0) [inline, inherited]
Definition at line 322 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Polycone_numZ.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i)) Polycone_numZ[i] = val;}
void SimpleGeometryParameter::set_Polycone_numZ (G4int PolyconeId, G4int val, G4int j = 0) [inline, inherited]
Definition at line 315 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), and SimpleGeometryParameter::Polycone_numZ.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId)) Polycone_numZ[PolyconeId] = val;}
void SimpleGeometryParameter::set_Polycone_RMax (G4String name, G4int iCone, G4double val, G4int j = 0) [inline, inherited]
Definition at line 323 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), SimpleGeometryParameter::Polycone_numZ, and SimpleGeometryParameter::Polycone_RMax.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i) && iCone < Polycone_numZ[i]) Polycone_RMax[i][iCone][j] = val;}
void SimpleGeometryParameter::set_Polycone_RMax (G4int PolyconeId, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 316 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::Polycone_numZ, and SimpleGeometryParameter::Polycone_RMax.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) Polycone_RMax[PolyconeId][i][j] = val;}
void SimpleGeometryParameter::set_Polycone_RMin (G4String name, G4int iCone, G4double val, G4int j = 0) [inline, inherited]
Definition at line 324 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), SimpleGeometryParameter::Polycone_numZ, and SimpleGeometryParameter::Polycone_RMin.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i) && iCone < Polycone_numZ[i]) Polycone_RMin[i][iCone][j] = val;}
void SimpleGeometryParameter::set_Polycone_RMin (G4int PolyconeId, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 317 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::Polycone_numZ, and SimpleGeometryParameter::Polycone_RMin.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) Polycone_RMin[PolyconeId][i][j] = val;}
void SimpleGeometryParameter::set_Polycone_SpanAng (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 327 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Polycone_SpanAng.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i)) Polycone_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Polycone_SpanAng (G4int PolyconeId, G4double val, G4int j = 0) [inline, inherited]
Definition at line 320 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), and SimpleGeometryParameter::Polycone_SpanAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId)) Polycone_SpanAng[PolyconeId][j] = val;}
void SimpleGeometryParameter::set_Polycone_StartAng (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 326 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Polycone_StartAng.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i)) Polycone_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_Polycone_StartAng (G4int PolyconeId, G4double val, G4int j = 0) [inline, inherited]
Definition at line 319 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), and SimpleGeometryParameter::Polycone_StartAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId)) Polycone_StartAng[PolyconeId][j] = val;}
void SimpleGeometryParameter::set_Polycone_Z (G4String name, G4int iCone, G4double val, G4int j = 0) [inline, inherited]
Definition at line 325 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), SimpleGeometryParameter::Polycone_numZ, and SimpleGeometryParameter::Polycone_Z.
{int i = get_SolidIndex(get_VolIndex(name));if(check_PolyconeId(i) && iCone < Polycone_numZ[i]) Polycone_Z[i][iCone][j] = val;}
void SimpleGeometryParameter::set_Polycone_Z (G4int PolyconeId, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 318 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::check_PolyconeId(), SimpleGeometryParameter::Polycone_numZ, and SimpleGeometryParameter::Polycone_Z.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{if(check_PolyconeId(PolyconeId) && i < Polycone_numZ[PolyconeId]) Polycone_Z[PolyconeId][i][j] = val;}
void SimpleGeometryParameter::set_PosX (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 205 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Pos.
{ int k = get_VolIndex(name); Pos[k][j].setX(val);}
void SimpleGeometryParameter::set_PosX (G4String type, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 184 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::Pos.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Pos[k][j].setX(val);}
void SimpleGeometryParameter::set_PosY (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 206 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Pos.
{ int k = get_VolIndex(name); Pos[k][j].setY(val);}
void SimpleGeometryParameter::set_PosY (G4String type, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 185 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::Pos.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Pos[k][j].setY(val);}
void SimpleGeometryParameter::set_PosZ (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 207 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Pos.
{ int k = get_VolIndex(name); Pos[k][j].setZ(val);}
void SimpleGeometryParameter::set_PosZ (G4String type, G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 186 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::Pos.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); Pos[k][j].setZ(val);}
void SimpleGeometryParameter::set_r (G4String name, G4double val) [inline, inherited]
Definition at line 383 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::vR.
{int k = get_VolIndex(name); vR[k] = val;}
void SimpleGeometryParameter::set_r (G4int i, G4double val) [inline, inherited]
Definition at line 377 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::vR.
{ vR[i] = val;}
void SimpleGeometryParameter::set_r (G4String type, G4int i, G4double val) [inline, inherited]
Definition at line 371 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::vR.
Referenced by SimpleGeometryParameter::GetValue(), and SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); vR[k] = val;}
void SimpleGeometryParameter::set_RepNo (G4String name, G4int val) [inline, inherited]
Definition at line 203 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::RepNo.
{ int k = get_VolIndex(name); RepNo[k] = val;}
void SimpleGeometryParameter::set_RepNo (G4String type, G4int i, G4int val) [inline, inherited]
Definition at line 192 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::RepNo.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); RepNo[k] = val;}
void SimpleGeometryParameter::set_SDName (G4String name, G4String val) [inline, inherited]
Definition at line 199 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::SDName.
{ int k = get_VolIndex(name); SDName[k] = val;}
void SimpleGeometryParameter::set_SDName (G4String type, G4int i, G4String val) [inline, inherited]
Definition at line 188 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::SDName.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); SDName[k] = val;}
void SimpleGeometryParameter::set_SolidBoolean (G4String name, G4int val) [inline, inherited]
Definition at line 204 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::SolidBoolean.
{ int k = get_VolIndex(name); SolidBoolean[k] = val;}
void SimpleGeometryParameter::set_SolidBoolean (G4String type, G4int i, G4int val) [inline, inherited]
Definition at line 196 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::SolidBoolean.
{ int k = get_index(type, i); SolidBoolean[k] = val;}
void SimpleGeometryParameter::set_Sphere_RMax (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 264 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Sphere_RMax.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_RMax (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 257 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Sphere_RMax.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_RMin (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 265 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Sphere_RMin.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_RMin (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 258 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Sphere_RMin.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_SpanPhi (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 267 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Sphere_SpanPhi.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_SpanPhi[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_SpanPhi (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 260 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Sphere_SpanPhi.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_SpanPhi[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_SpanTheta (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 269 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Sphere_SpanTheta.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_SpanTheta[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_SpanTheta (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 262 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Sphere_SpanTheta.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_SpanTheta[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_StartPhi (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 266 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Sphere_StartPhi.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_StartPhi[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_StartPhi (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 259 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Sphere_StartPhi.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_StartPhi[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_StartTheta (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 268 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Sphere_StartTheta.
{int i = get_SolidIndex(get_VolIndex(name)); Sphere_StartTheta[i][j] = val;}
void SimpleGeometryParameter::set_Sphere_StartTheta (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 261 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Sphere_StartTheta.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Sphere_StartTheta[i][j] = val;}
void SimpleGeometryParameter::set_SRepNo (G4String name, G4int val) [inline, inherited]
Definition at line 202 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::SRepNo.
{ int k = get_VolIndex(name); SRepNo[k] = val;}
void SimpleGeometryParameter::set_SRepNo (G4String type, G4int i, G4int val) [inline, inherited]
Definition at line 191 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::SRepNo.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); SRepNo[k] = val;}
void SimpleGeometryParameter::set_t (G4String name, G4double val) [inline, inherited]
Definition at line 386 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::vT.
{int k = get_VolIndex(name); vT[k] = val;}
void SimpleGeometryParameter::set_t (G4int i, G4double val) [inline, inherited]
Definition at line 380 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::vT.
{ vT[i] = val;}
void SimpleGeometryParameter::set_t (G4String type, G4int i, G4double val) [inline, inherited]
Definition at line 374 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::vT.
Referenced by SimpleGeometryParameter::GetValue().
{ int k = get_index(type, i); vT[k] = val;}
void SimpleGeometryParameter::set_Torus_RMax (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 250 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Torus_RMax.
{int i = get_SolidIndex(get_VolIndex(name)); Torus_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Torus_RMax (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 244 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Torus_RMax.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Torus_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Torus_RMin (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 251 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Torus_RMin.
{int i = get_SolidIndex(get_VolIndex(name)); Torus_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Torus_RMin (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 245 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Torus_RMin.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Torus_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Torus_Rtor (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 252 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Torus_Rtor.
{int i = get_SolidIndex(get_VolIndex(name)); Torus_Rtor[i][j] = val;}
void SimpleGeometryParameter::set_Torus_Rtor (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 246 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Torus_Rtor.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Torus_Rtor[i][j] = val;}
void SimpleGeometryParameter::set_Torus_SpanAng (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 254 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Torus_SpanAng.
{int i = get_SolidIndex(get_VolIndex(name)); Torus_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Torus_SpanAng (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 248 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Torus_SpanAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Torus_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Torus_StartAng (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 253 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Torus_StartAng.
{int i = get_SolidIndex(get_VolIndex(name)); Torus_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_Torus_StartAng (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 247 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Torus_StartAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Torus_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_Length (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 239 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Tubs_Length.
{int i = get_SolidIndex(get_VolIndex(name)); Tubs_Length[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_Length (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 233 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Tubs_Length.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Tubs_Length[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_RMax (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 237 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Tubs_RMax.
{int i = get_SolidIndex(get_VolIndex(name)); Tubs_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_RMax (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 231 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Tubs_RMax.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Tubs_RMax[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_RMin (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 238 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Tubs_RMin.
{int i = get_SolidIndex(get_VolIndex(name)); Tubs_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_RMin (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 232 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Tubs_RMin.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Tubs_RMin[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_SpanAng (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 241 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Tubs_SpanAng.
{int i = get_SolidIndex(get_VolIndex(name)); Tubs_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_SpanAng (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 235 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Tubs_SpanAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Tubs_SpanAng[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_StartAng (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 240 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::Tubs_StartAng.
{int i = get_SolidIndex(get_VolIndex(name)); Tubs_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_Tubs_StartAng (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 234 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::Tubs_StartAng.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ Tubs_StartAng[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_dphi (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 295 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::TwistedTubs_dphi.
{int i = get_SolidIndex(get_VolIndex(name)); TwistedTubs_dphi[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_dphi (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 289 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::TwistedTubs_dphi.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ TwistedTubs_dphi[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_endinnerrad (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 292 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::TwistedTubs_endinnerrad.
{int i = get_SolidIndex(get_VolIndex(name)); TwistedTubs_endinnerrad[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_endinnerrad (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 286 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::TwistedTubs_endinnerrad.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ TwistedTubs_endinnerrad[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_endouterrad (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 293 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::TwistedTubs_endouterrad.
{int i = get_SolidIndex(get_VolIndex(name)); TwistedTubs_endouterrad[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_endouterrad (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 287 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::TwistedTubs_endouterrad.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ TwistedTubs_endouterrad[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_Length (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 294 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::TwistedTubs_Length.
{int i = get_SolidIndex(get_VolIndex(name)); TwistedTubs_Length[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_Length (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 288 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::TwistedTubs_Length.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ TwistedTubs_Length[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_twistedangle (G4String name, G4double val, G4int j = 0) [inline, inherited]
Definition at line 291 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_SolidIndex(), SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::TwistedTubs_twistedangle.
{int i = get_SolidIndex(get_VolIndex(name)); TwistedTubs_twistedangle[i][j] = val;}
void SimpleGeometryParameter::set_TwistedTubs_twistedangle (G4int i, G4double val, G4int j = 0) [inline, inherited]
Definition at line 285 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::TwistedTubs_twistedangle.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{ TwistedTubs_twistedangle[i][j] = val;}
void MyVGeometryParameter::set_VerboseLevel (int val) [inline, inherited]
Definition at line 74 of file MyVGeometryParameter.hh.
References MyVGeometryParameter::fVerboseLevel.
Referenced by MyVGeometryParameterMessenger::MySetNewValue().
{ fVerboseLevel = val;}
void SimpleGeometryParameter::set_vis (G4String name, bool val) [inline, inherited]
Definition at line 382 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_VolIndex(), and SimpleGeometryParameter::vVis.
{int k = get_VolIndex(name); vVis[k] = val;}
void SimpleGeometryParameter::set_vis (G4int i, bool val) [inline, inherited]
Definition at line 376 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::vVis.
{ vVis[i] = val;}
void SimpleGeometryParameter::set_vis (G4String type, G4int i, bool val) [inline, inherited]
Definition at line 370 of file SimpleGeometryParameter.hh.
References SimpleGeometryParameter::get_index(), and SimpleGeometryParameter::vVis.
Referenced by SimpleGeometryParameter::GetValue(), and SimpleGeometryParameterMessenger::MySetNewValue().
{ int k = get_index(type, i); vVis[k] = val;}
Member Data Documentation
G4double CdcGeometryParameter::b_cell [private]
Definition at line 239 of file CdcGeometryParameter.hh.
Referenced by get_b_cell(), and GetValue().
G4double CdcGeometryParameter::b_FieldWire [private]
Definition at line 243 of file CdcGeometryParameter.hh.
Referenced by get_b_FieldWire(), and GetValue().
G4double CdcGeometryParameter::b_layer [private]
Definition at line 237 of file CdcGeometryParameter.hh.
Referenced by get_b_layer(), and GetValue().
G4double CdcGeometryParameter::b_SignalWire [private]
Definition at line 242 of file CdcGeometryParameter.hh.
Referenced by get_b_SignalWire(), and GetValue().
G4double CdcGeometryParameter::Cdc_RMax [private]
Definition at line 222 of file CdcGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_Cdc_RMax(), and GetValue().
G4String CdcGeometryParameter::CellMaterial [private]
Definition at line 216 of file CdcGeometryParameter.hh.
Referenced by get_CellMaterial(), and GetValue().
G4String CdcGeometryParameter::FieldWireMaterial [private]
Definition at line 215 of file CdcGeometryParameter.hh.
Referenced by DumpInfo(), get_FieldWireMaterial(), and GetValue().
G4double CdcGeometryParameter::FieldWireRadius [private]
Definition at line 218 of file CdcGeometryParameter.hh.
Referenced by DumpInfo(), get_FieldWireRadius(), and GetValue().
G4double CdcGeometryParameter::g_cell [private]
Definition at line 239 of file CdcGeometryParameter.hh.
Referenced by get_g_cell(), and GetValue().
G4double CdcGeometryParameter::g_FieldWire [private]
Definition at line 243 of file CdcGeometryParameter.hh.
Referenced by get_g_FieldWire(), and GetValue().
G4double CdcGeometryParameter::g_layer [private]
Definition at line 237 of file CdcGeometryParameter.hh.
Referenced by get_g_layer(), and GetValue().
G4double CdcGeometryParameter::g_SignalWire [private]
Definition at line 242 of file CdcGeometryParameter.hh.
Referenced by get_g_SignalWire(), and GetValue().
std::vector< G4String > MyConfigure::knownValueNames [static, inherited]
Definition at line 24 of file MyConfigure.hh.
Referenced by MyConfigure::FindMacro(), SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
std::vector< G4String > MyConfigure::knownValues [static, inherited]
Definition at line 25 of file MyConfigure.hh.
Referenced by MyConfigure::FindMacro(), SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
std::vector<G4double> CdcGeometryParameter::layer_angle4rotate [private]
Definition at line 228 of file CdcGeometryParameter.hh.
Referenced by Calculate(), get_layer_angle4rotate(), and get_layer_cell_phi().
std::vector<G4double> CdcGeometryParameter::layer_cell_dphi [private]
Definition at line 233 of file CdcGeometryParameter.hh.
Referenced by Calculate(), get_layer_cell_dphi(), and get_layer_cell_phi().
std::vector<G4int> CdcGeometryParameter::layer_cell_num [private]
Definition at line 229 of file CdcGeometryParameter.hh.
Referenced by Calculate(), check_cellId(), DumpInfo(), get_layer_cell_num(), and GetValue().
std::vector<G4int> CdcGeometryParameter::layer_cell_startNo [private]
Definition at line 232 of file CdcGeometryParameter.hh.
Referenced by Calculate(), get_layerIdcellId(), and get_ReplicaNo().
std::vector<G4int> CdcGeometryParameter::layer_firstWire [private]
Definition at line 230 of file CdcGeometryParameter.hh.
Referenced by DumpInfo(), get_layer_cell_phi(), get_layer_firstWire(), and GetValue().
std::vector<G4double> CdcGeometryParameter::layer_length [private]
Definition at line 223 of file CdcGeometryParameter.hh.
Referenced by CheckInfo(), DumpInfo(), get_layer_length(), and GetValue().
std::vector<G4double> CdcGeometryParameter::layer_ncells4rotate [private]
Definition at line 227 of file CdcGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), get_layer_ncells4rotate(), and GetValue().
std::vector<G4double> CdcGeometryParameter::layer_RMid [private]
Definition at line 225 of file CdcGeometryParameter.hh.
Referenced by DumpInfo(), get_layer_RMid(), and GetValue().
std::vector<G4double> CdcGeometryParameter::layer_RMin [private]
Definition at line 224 of file CdcGeometryParameter.hh.
Referenced by Calculate(), CheckInfo(), DumpInfo(), get_layer_RMin(), and GetValue().
std::vector<G4double> CdcGeometryParameter::layer_SPhi [private]
Definition at line 226 of file CdcGeometryParameter.hh.
Referenced by DumpInfo(), get_layer_cell_phi(), get_layer_SPhi(), and GetValue().
std::vector<G4int> CdcGeometryParameter::layer_type [private]
Definition at line 231 of file CdcGeometryParameter.hh.
Referenced by Calculate(), DumpInfo(), and get_layer_type().
G4int CdcGeometryParameter::LayerNo [private]
Definition at line 221 of file CdcGeometryParameter.hh.
Referenced by Calculate(), check_layerId(), check_LayerNo(), DumpInfo(), get_layerIdcellId(), get_LayerNo(), GetValue(), and Preset().
G4String CdcGeometryParameter::MotherLogicalVolume [private]
Definition at line 209 of file CdcGeometryParameter.hh.
Referenced by DumpInfo(), get_MotherLogicalVolume(), and GetValue().
G4double CdcGeometryParameter::r_cell [private]
Definition at line 239 of file CdcGeometryParameter.hh.
Referenced by get_r_cell(), and GetValue().
G4double CdcGeometryParameter::r_FieldWire [private]
Definition at line 243 of file CdcGeometryParameter.hh.
Referenced by get_r_FieldWire(), and GetValue().
G4double CdcGeometryParameter::r_layer [private]
Definition at line 237 of file CdcGeometryParameter.hh.
Referenced by get_r_layer(), and GetValue().
G4double CdcGeometryParameter::r_SignalWire [private]
Definition at line 242 of file CdcGeometryParameter.hh.
Referenced by get_r_SignalWire(), and GetValue().
G4String CdcGeometryParameter::SDVolumeName [private]
Definition at line 211 of file CdcGeometryParameter.hh.
Referenced by DumpInfo(), get_SDVolumeName(), and GetValue().
G4String CdcGeometryParameter::SensitiveDetector [private]
Definition at line 210 of file CdcGeometryParameter.hh.
Referenced by DumpInfo(), get_SensitiveDetector(), and GetValue().
G4String CdcGeometryParameter::SignalWireMaterial [private]
Definition at line 214 of file CdcGeometryParameter.hh.
Referenced by DumpInfo(), get_SignalWireMaterial(), and GetValue().
G4double CdcGeometryParameter::SignalWireRadius [private]
Definition at line 217 of file CdcGeometryParameter.hh.
Referenced by DumpInfo(), get_SignalWireRadius(), and GetValue().
bool CdcGeometryParameter::vis_cell [private]
Definition at line 238 of file CdcGeometryParameter.hh.
Referenced by get_vis_cell(), GetValue(), and Preset().
bool CdcGeometryParameter::vis_FieldWire [private]
Definition at line 240 of file CdcGeometryParameter.hh.
Referenced by get_vis_FieldWire(), GetValue(), and Preset().
bool CdcGeometryParameter::vis_layer [private]
Definition at line 236 of file CdcGeometryParameter.hh.
Referenced by get_vis_layer(), GetValue(), and Preset().
bool CdcGeometryParameter::vis_SignalWire [private]
Definition at line 241 of file CdcGeometryParameter.hh.
Referenced by get_vis_SignalWire(), GetValue(), and Preset().
The documentation for this class was generated from the following files:
include/CdcGeometryParameter.hh
src/CdcGeometryParameter.cc