g4sim: MyVGeometrySvc Class Reference
MyVGeometrySvc Class Reference
#include <MyVGeometrySvc.hh>
Public Member Functions
MyVGeometrySvc (G4String name, G4String opt="")
virtual ~MyVGeometrySvc ()
virtual G4VPhysicalVolume * SetGeometry ()
void ReadCard (G4String)
void ConstructVolumes ()
G4VPhysicalVolume * PlaceVolumes ()
G4LogicalVolume * get_logicalVolume (G4String name)
MyVGeometryParameter * get_GeometryParameter ()
int get_VerboseLevel ()
G4String get_Name ()
void set_GeometryParameter (MyVGeometryParameter *val)
void set_VerboseLevel (int val)
void set_Name (G4String val)
std::vector< G4String > GetWords (G4String formula)
bool FindMacro (G4String word, G4String &value)
void Replace (G4String &formula, G4String word, G4String value)
double CalFormula (G4String formula, int iRep=0)
G4String ReplaceMacro (G4String formula)
Static Public Attributes
static std::vector< G4String > knownValueNames
static std::vector< G4String > knownValues
Private Attributes
MyVGeometryParameter * m_GeometryParameter
int fVerboseLevel
G4String m_Name
Detailed Description
Definition at line 26 of file MyVGeometrySvc.hh.
Constructor & Destructor Documentation
MyVGeometrySvc::MyVGeometrySvc (G4String name, G4String opt = "")
Definition at line 26 of file MyVGeometrySvc.cc.
References set_Name().
        :MyConfigure()
{
        if ( opt == "" ){
                std::cout<<"MyVGeometrySvc is a virtual class, should be called with opt not empty!"<<std::endl;
    G4Exception("MyVGeometrySvc::MyVGeometrySvc()","Run0031",
        FatalException, "illegal construction.");
        }
        set_Name(name);
}
MyVGeometrySvc::~MyVGeometrySvc () [virtual]
Definition at line 37 of file MyVGeometrySvc.cc.
References m_GeometryParameter.
{
        std::cout<<"======>In ~MyVGeometrySvc, delete GeometryParameter at ("<<(void*)m_GeometryParameter<<")!"<<std::endl;
        delete m_GeometryParameter;
}
Member Function Documentation
double MyConfigure::CalFormula (G4String formula, int iRep = 0) [inherited]
Definition at line 23 of file MyConfigure.cc.
Referenced by SimpleGeometryParameter::Calculate(), and PrimaryGeneratorAction::ReadCard().
{
//      std::cout<<"TO Calculate for: \""<<formula<<"\" "<<iRep<<std::endl; // to be deleted
//      formula = ReplaceMacro(formula);
        TF1 *f1 = new TF1("f1", formula);
        double value = f1->Eval(iRep);
//      std::cout<<"\t=>"<<value<<std::endl;
        delete f1;
        return value;
}
void MyVGeometrySvc::ConstructVolumes () [inline]
Reimplemented in SimpleGeometrySvc.
Definition at line 38 of file MyVGeometrySvc.hh.
{};
bool MyConfigure::FindMacro (G4String word, G4String & value) [inherited]
Definition at line 87 of file MyConfigure.cc.
References MyConfigure::knownValueNames, and MyConfigure::knownValues.
Referenced by MyConfigure::Replace(), and MyConfigure::ReplaceMacro().
{
        bool found = false;
        for (int i = 0; i< knownValues.size(); i++){
                if (knownValueNames[i]==word){
                        value = knownValues[i];
                        found = true;
                        break;
                }
        }
        return found;
}
MyVGeometryParameter* MyVGeometrySvc::get_GeometryParameter () [inline]
Reimplemented in SimpleGeometrySvc.
Definition at line 46 of file MyVGeometrySvc.hh.
References m_GeometryParameter.
Referenced by MyDetectorManager::GetSD(), and PrimaryGeneratorAction::SetUniformPosition().
{ return m_GeometryParameter; }
G4LogicalVolume * MyVGeometrySvc::get_logicalVolume (G4String name)
Definition at line 51 of file MyVGeometrySvc.cc.
Referenced by SimpleGeometrySvc::PlaceVolumes().
{
        //get mother_volume
  G4LogicalVolumeStore* logicalVolumeStore = G4LogicalVolumeStore::GetInstance();
  G4LogicalVolume* log_volume = logicalVolumeStore->GetVolume(name,false);
  if (!log_volume){
    std::cout<<"Logical volume "<<name<<" of MyVGeometry can not be found!!!"<<std::endl;
    G4Exception("MyVGeometrySvc::get_logicalVolume()","Run0031",
        FatalException, "unknown logical volume.");
  }
  return log_volume;
}
G4String MyVGeometrySvc::get_Name () [inline]
Definition at line 50 of file MyVGeometrySvc.hh.
References m_Name.
{ return m_Name; }
int MyVGeometrySvc::get_VerboseLevel () [inline]
Definition at line 48 of file MyVGeometrySvc.hh.
References fVerboseLevel.
{ return fVerboseLevel; }
std::vector< G4String > MyConfigure::GetWords (G4String formula) [inherited]
Definition at line 48 of file MyConfigure.cc.
Referenced by MyConfigure::ReplaceMacro().
{
        std::vector<G4String> words;
        words.clear();
        const char* cformula = formula.c_str();
        int length = strlen(cformula);
        char temp[1240];
        int tempoffset = 0;
        for ( int offset = 0; offset < length; offset++ ){
                char c = cformula[offset];
                bool isword = false;
                if (c>='a'&&c<='z'
                        ||c>='A'&&c<='Z'
                        ||c>='0'&&c<='9'
                        ||c=='_'
                   ){
                        temp[tempoffset++] = cformula[offset];
                        isword = true;
                }
                if (!isword||offset==length-1){
                        if (tempoffset>0){
                                temp[tempoffset++] = '\0';
                                tempoffset=0;
                                G4String word = temp;
                                bool found = false;
                                for(int iWord = 0; iWord<words.size(); iWord++){
                                        if (words[iWord]==word){
                                                found = true;
                                                break;
                                        }
                                }
                                if (!found){
                                        words.push_back(word);
                                }
                        }
                }
        }
        return words;
}
G4VPhysicalVolume* MyVGeometrySvc::PlaceVolumes () [inline]
Reimplemented in SimpleGeometrySvc.
Definition at line 40 of file MyVGeometrySvc.hh.
{return 0;}
void MyVGeometrySvc::ReadCard (G4String file_name)
Definition at line 42 of file MyVGeometrySvc.cc.
References MyVGeometryParameter::InitFromFile(), and m_GeometryParameter.
Referenced by MyDetectorManager::AddGeo(), and MyDetectorManager::ReadCard().
{
        if(file_name[0] != '/'){ // Relative Dir
                G4String dir_name = getenv("CONFIGUREROOT");
                if (dir_name[dir_name.size()-1] != '/') dir_name.append("/");
                file_name = dir_name + file_name;
        }
        m_GeometryParameter->InitFromFile(file_name);
}
void MyConfigure::Replace (G4String & formula, G4String word, G4String value) [inherited]
Definition at line 99 of file MyConfigure.cc.
References MyConfigure::FindMacro().
Referenced by MyConfigure::ReplaceMacro().
{
//      std::cout<<"-- \""<<formula<<"\""<<std::endl; // to be deleted
        G4String newform = "";
        const char* cformula = formula.c_str();
        int length = strlen(cformula);
        char temp[1024];
        int tempoffset = 0;
        char cnewform[1024];
        int newformoffset = 0;
        for ( int offset = 0; offset < length; offset++ ){
                char c = cformula[offset];
                bool isword = false;
                if (c>='a'&&c<='z'
                        ||c>='A'&&c<='Z'
                        ||c>='0'&&c<='9'
                        ||c=='_'
                   ){
                        temp[tempoffset++] = cformula[offset];
                        isword = true;
                }
                if (!isword||offset==length-1){
                        if (tempoffset>0){
                                temp[tempoffset] = '\0';
                                tempoffset=0;
                                if (newformoffset>0){
                                        cnewform[newformoffset] = '\0';
                                        newformoffset=0;
                                        G4String newformtemp = cnewform;
                                        newform=newform+newformtemp;
                                }
                                G4String word = temp;
//                              std::cout<<"            \""<<word<<"\""<<std::endl; // to be deleted
                                G4String newword;
                                bool found = FindMacro(word,newword);
                                if (found){
                                        newform=newform+"("+newword+")";
                                }
                                else{
                                        newform=newform+word;
                                }
//                              std::cout<<"            to \""<<newword<<"\""<<std::endl; // to be deleted
                        }
                        if(!isword){
                                cnewform[newformoffset++] = cformula[offset];
                        }
                        if (offset==length-1){
                                cnewform[newformoffset] = '\0';
                                G4String newformtemp = cnewform;
                                newform=newform+newformtemp;
                        }
                }
        }
//      std::cout<<"    -->\""<<newform<<"\""<<std::endl; // to be deleted
        formula = newform;
}
G4String MyConfigure::ReplaceMacro (G4String formula) [inherited]
Definition at line 33 of file MyConfigure.cc.
References MyConfigure::FindMacro(), MyConfigure::GetWords(), and MyConfigure::Replace().
Referenced by SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
{
//      std::cout<<"TO replace for: \""<<formula<<"\""<<std::endl; // to be deleted
        std::vector<G4String> words = GetWords(formula);
//      std::cout<<"    "<<words.size()<<" words"<<std::endl; // to be deleted
        for (int iWord = 0; iWord < words.size(); iWord++ ){
//              std::cout<<"            "<<iWord<<std::endl; // to be deleted
                G4String value;
                if (FindMacro(words[iWord],value)){
                        Replace(formula,words[iWord],value);
                }
        }
//      std::cout<<"\t=>"<<formula<<std::endl;
        return formula;
}
void MyVGeometrySvc::set_GeometryParameter (MyVGeometryParameter * val) [inline]
Definition at line 53 of file MyVGeometrySvc.hh.
References m_GeometryParameter.
{ m_GeometryParameter = val; }
void MyVGeometrySvc::set_Name (G4String val) [inline]
Definition at line 57 of file MyVGeometrySvc.hh.
References m_Name.
Referenced by MyVGeometrySvc().
{ m_Name = val; }
void MyVGeometrySvc::set_VerboseLevel (int val) [inline]
Definition at line 55 of file MyVGeometrySvc.hh.
References fVerboseLevel.
Referenced by MyDetectorManager::AddGeo(), and MyDetectorManager::ReadCard().
{ fVerboseLevel = val; }
virtual G4VPhysicalVolume* MyVGeometrySvc::SetGeometry () [inline, virtual]
Reimplemented in SimpleGeometrySvc.
Definition at line 33 of file MyVGeometrySvc.hh.
{return 0;} //Setup geometry. Should be called before the begin of a run
Member Data Documentation
int MyVGeometrySvc::fVerboseLevel [private]
Definition at line 63 of file MyVGeometrySvc.hh.
Referenced by get_VerboseLevel(), and set_VerboseLevel().
std::vector< G4String > MyConfigure::knownValueNames [static, inherited]
Definition at line 24 of file MyConfigure.hh.
Referenced by MyConfigure::FindMacro(), SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
std::vector< G4String > MyConfigure::knownValues [static, inherited]
Definition at line 25 of file MyConfigure.hh.
Referenced by MyConfigure::FindMacro(), SimpleGeometryParameter::GetValue(), and PrimaryGeneratorAction::ReadCard().
MyVGeometryParameter* MyVGeometrySvc::m_GeometryParameter [private]
Reimplemented in SimpleGeometrySvc.
Definition at line 61 of file MyVGeometrySvc.hh.
Referenced by get_GeometryParameter(), ReadCard(), set_GeometryParameter(), and ~MyVGeometrySvc().
G4String MyVGeometrySvc::m_Name [private]
Definition at line 65 of file MyVGeometrySvc.hh.
Referenced by get_Name(), and set_Name().
The documentation for this class was generated from the following files:
include/MyVGeometrySvc.hh
src/MyVGeometrySvc.cc