g4sim: MyString2Anything Class Reference
MyString2Anything Class Reference
#include <MyString2Anything.hh>
Public Member Functions
MyString2Anything ()
~MyString2Anything ()
Static Public Member Functions
static void get_SD (G4String cont, G4String &m_str, G4double &m_dou)
static void get_SDUI (G4String cont, G4String &m_str, G4double &m_dou, G4int &m_int)
static void get_SIDU (G4String cont, G4String &m_str, G4int &m_int, G4double &m_dou)
static void get_SIDUI (G4String cont, G4String &m_str, G4int &m_int, G4double &m_dou, G4int &m_int2)
static void get_SIIDU (G4String cont, G4String &m_str, G4int &m_int1, G4int &m_int2, G4double &m_dou)
static void get_SIB (G4String cont, G4String &m_str, G4int &m_int, bool &m_bool)
static void get_SID (G4String cont, G4String &m_str, G4int &m_int, G4double &m_dou)
static void get_SI (G4String cont, G4String &m_str, G4int &m_int)
static void get_SII (G4String cont, G4String &m_str, G4int &m_int, G4int &m_int2)
static void get_SB (G4String cont, G4String &m_str, G4bool &m_bool)
static void get_SS (G4String cont, G4String &m_str, G4String &m_str2)
static void get_SSS (G4String cont, G4String &m_str, G4String &m_str2, G4String &m_str3)
static void get_SIS (G4String cont, G4String &m_str, G4int &m_int, G4String &m_str2)
static void get_IS (G4String cont, G4int &m_int, G4String &m_str)
static void get_I (G4String cont, G4int &m_int)
static void get_IDU (G4String cont, G4int &m_int, G4double &m_dou)
static void get_IIDU (G4String cont, G4int &m_int1, G4int &m_int2, G4double &m_dou)
static double get_U (G4String cont)
static void get_ID (G4String cont, G4int &m_int, G4double &m_dou)
static void get_IB (G4String cont, G4int &m_int, bool &m_bool)
static G4bool ConvertToBool (G4String st)
Detailed Description
Definition at line 10 of file MyString2Anything.hh.
Constructor & Destructor Documentation
MyString2Anything::MyString2Anything ()
Definition at line 3 of file MyString2Anything.cc.
{}
MyString2Anything::~MyString2Anything ()
Definition at line 5 of file MyString2Anything.cc.
{}
Member Function Documentation
static G4bool MyString2Anything::ConvertToBool (G4String st) [inline, static]
Definition at line 136 of file MyString2Anything.hh.
Referenced by get_IB(), and get_SIB().
                {
                        st.toUpper();
                        G4bool vl = false;
                        if( st=="Y" || st=="YES" || st=="1" || st=="T" || st=="TRUE" )
                        { vl = true; }
                        return vl;
                }
static void MyString2Anything::get_I (G4String cont, G4int & m_int) [inline, static]
Definition at line 96 of file MyString2Anything.hh.
Referenced by MyVGeometryParameter::get_RepCont().
{
                        std::stringstream buf(cont);
                        buf>>m_int;
                }
static void MyString2Anything::get_IB (G4String cont, G4int & m_int, bool & m_bool) [inline, static]
Definition at line 129 of file MyString2Anything.hh.
References ConvertToBool().
{
                        G4String t_str;
                        std::stringstream buf(cont);
                        buf>>m_int>>t_str;
                        m_bool = ConvertToBool(t_str);
                }
static void MyString2Anything::get_ID (G4String cont, G4int & m_int, G4double & m_dou) [inline, static]
Definition at line 124 of file MyString2Anything.hh.
{
                        std::stringstream buf(cont);
                        buf>>m_int>>m_dou;
                }
static void MyString2Anything::get_IDU (G4String cont, G4int & m_int, G4double & m_dou) [inline, static]
Definition at line 101 of file MyString2Anything.hh.
{
                        G4String m_unit;
                        std::stringstream buf(cont);
                        buf>>m_int>>m_dou>>m_unit;
                        m_dou *= G4UnitDefinition::GetValueOf(m_unit);
                }
static void MyString2Anything::get_IIDU (G4String cont, G4int & m_int1, G4int & m_int2, G4double & m_dou) [inline, static]
Definition at line 108 of file MyString2Anything.hh.
{
                        G4String m_unit;
                        std::stringstream buf(cont);
                        buf>>m_int1>>m_int2>>m_dou>>m_unit;
                        m_dou *= G4UnitDefinition::GetValueOf(m_unit);
                }
static void MyString2Anything::get_IS (G4String cont, G4int & m_int, G4String & m_str) [inline, static]
Definition at line 91 of file MyString2Anything.hh.
{
                        std::stringstream buf(cont);
                        buf>>m_int>>m_str;
                }
static void MyString2Anything::get_SB (G4String cont, G4String & m_str, G4bool & m_bool) [inline, static]
Definition at line 71 of file MyString2Anything.hh.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{
                        std::stringstream buf(cont);
                        buf>>m_str>>m_bool;
                }
static void MyString2Anything::get_SD (G4String cont, G4String & m_str, G4double & m_dou) [inline, static]
Definition at line 16 of file MyString2Anything.hh.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{
                        std::stringstream buf(cont);
                        buf>>m_str>>m_dou;
                }
static void MyString2Anything::get_SDUI (G4String cont, G4String & m_str, G4double & m_dou, G4int & m_int) [inline, static]
Definition at line 21 of file MyString2Anything.hh.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{
                        G4String m_unit;
                        std::stringstream buf(cont);
                        buf>>m_str>>m_dou>>m_unit>>m_int;
                        m_dou *= G4UnitDefinition::GetValueOf(m_unit);
                }
static void MyString2Anything::get_SI (G4String cont, G4String & m_str, G4int & m_int) [inline, static]
Definition at line 61 of file MyString2Anything.hh.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{
                        std::stringstream buf(cont);
                        buf>>m_str>>m_int;
                }
static void MyString2Anything::get_SIB (G4String cont, G4String & m_str, G4int & m_int, bool & m_bool) [inline, static]
Definition at line 49 of file MyString2Anything.hh.
References ConvertToBool().
{
                        std::string val;
                        std::stringstream buf(cont);
                        buf>>m_str>>m_int>>val;
                        m_bool = ConvertToBool(val);
                }
static void MyString2Anything::get_SID (G4String cont, G4String & m_str, G4int & m_int, G4double & m_dou) [inline, static]
Definition at line 56 of file MyString2Anything.hh.
{
                        std::stringstream buf(cont);
                        buf>>m_str>>m_int>>m_dou;
                }
static void MyString2Anything::get_SIDU (G4String cont, G4String & m_str, G4int & m_int, G4double & m_dou) [inline, static]
Definition at line 28 of file MyString2Anything.hh.
{
                        G4String m_unit;
                        std::stringstream buf(cont);
                        buf>>m_str>>m_int>>m_dou>>m_unit;
                        m_dou *= G4UnitDefinition::GetValueOf(m_unit);
                }
static void MyString2Anything::get_SIDUI (G4String cont, G4String & m_str, G4int & m_int, G4double & m_dou, G4int & m_int2) [inline, static]
Definition at line 35 of file MyString2Anything.hh.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{
                        G4String m_unit;
                        std::stringstream buf(cont);
                        buf>>m_str>>m_int>>m_dou>>m_unit>>m_int2;
                        m_dou *= G4UnitDefinition::GetValueOf(m_unit);
                }
static void MyString2Anything::get_SII (G4String cont, G4String & m_str, G4int & m_int, G4int & m_int2) [inline, static]
Definition at line 66 of file MyString2Anything.hh.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{
                        std::stringstream buf(cont);
                        buf>>m_str>>m_int>>m_int2;
                }
static void MyString2Anything::get_SIIDU (G4String cont, G4String & m_str, G4int & m_int1, G4int & m_int2, G4double & m_dou) [inline, static]
Definition at line 42 of file MyString2Anything.hh.
{
                        G4String m_unit;
                        std::stringstream buf(cont);
                        buf>>m_str>>m_int1>>m_int2>>m_dou>>m_unit;
                        m_dou *= G4UnitDefinition::GetValueOf(m_unit);
                }
static void MyString2Anything::get_SIS (G4String cont, G4String & m_str, G4int & m_int, G4String & m_str2) [inline, static]
Definition at line 86 of file MyString2Anything.hh.
{
                        std::stringstream buf(cont);
                        buf>>m_str>>m_int>>m_str2;
                }
static void MyString2Anything::get_SS (G4String cont, G4String & m_str, G4String & m_str2) [inline, static]
Definition at line 76 of file MyString2Anything.hh.
Referenced by SimpleGeometryParameterMessenger::MySetNewValue().
{
                        std::stringstream buf(cont);
                        buf>>m_str>>m_str2;
                }
static void MyString2Anything::get_SSS (G4String cont, G4String & m_str, G4String & m_str2, G4String & m_str3) [inline, static]
Definition at line 81 of file MyString2Anything.hh.
Referenced by MyDetectorManagerMessenger::SetNewValue().
{
                        std::stringstream buf(cont);
                        buf>>m_str>>m_str2>>m_str3;
                }
static double MyString2Anything::get_U (G4String cont) [inline, static]
Definition at line 115 of file MyString2Anything.hh.
Referenced by ProcessCountingSvc::ReadOutputCard(), MonitorSD::ReadOutputCard(), McTruthSvc::ReadOutputCard(), KillerSD::ReadOutputCard(), MonitorSD::ReSet(), and MyTriggerSvc::SetMyTrigger().
{
                        double val = G4UnitDefinition::GetValueOf(cont);
                        if (!val){
                                std::cout<<"WARNING: value of unit ("<<cont<<") is 0!!! will set it to 1!!!"<<std::endl;
                                val = 1;
                        }
                        return val;
                }
The documentation for this class was generated from the following files:
include/MyString2Anything.hh
src/MyString2Anything.cc