g4sim: MyProcessManager Class Reference
MyProcessManager Class Reference
#include <MyProcessManager.hh>
Public Member Functions
MyProcessManager ()
virtual ~MyProcessManager ()
int OpenFile ()
void CloseFile ()
int GetMemorySize ()
Static Public Member Functions
static MyProcessManager * GetMyProcessManager ()
Private Attributes
int MemoryConsumption
std::ifstream * fin_card
std::stringstream buff
bool fileOpened
Static Private Attributes
static MyProcessManager * fMyProcessManager = 0
Detailed Description
Definition at line 7 of file MyProcessManager.hh.
Constructor & Destructor Documentation
MyProcessManager::MyProcessManager ()
Definition at line 11 of file MyProcessManager.cc.
References fileOpened, fin_card, fMyProcessManager, and MemoryConsumption.
{
        if (fMyProcessManager){
                G4Exception("MyProcessManager::MyProcessManager()","Run0031",
                                FatalException, "MyProcessManager constructed twice.");
        }
        fileOpened = false;
        fin_card = 0;
        MemoryConsumption = 0;
}
MyProcessManager::~MyProcessManager () [virtual]
Definition at line 22 of file MyProcessManager.cc.
References buff, and CloseFile().
{
        CloseFile();
        delete &buff;
}
Member Function Documentation
void MyProcessManager::CloseFile ()
Definition at line 53 of file MyProcessManager.cc.
References fileOpened, and fin_card.
Referenced by OpenFile(), and ~MyProcessManager().
{
        if (fileOpened&&fin_card){
                fin_card->close();
        }
        fileOpened = false;
        fin_card = 0;
}
int MyProcessManager::GetMemorySize ()
Definition at line 61 of file MyProcessManager.cc.
References buff, fileOpened, fin_card, and OpenFile().
Referenced by MyAnalysisSvc::EndOfEventAction().
{
        if (!fileOpened){
                OpenFile();
        }
        if (fin_card&&fileOpened){
                std::string s_card;
                std::string temp;
                double size = -2;
                while(getline(*fin_card,s_card)){
                        buff.str("");
                        buff.clear();
                        buff<<s_card;
                        buff>>temp;
//                      std::cout<<"In MyProcessManager::GetMemorySize: Found Line \""<<s_card<<"\""<<std::endl;
                        if (temp=="VmSize:"){
                                buff>>size>>temp;
                                if (temp == "kB" || temp == "KB" || temp == "kb"){
                                        size /= 1024;
                                }
                                else if (temp == "mB" || temp == "MB" || temp == "mb"){
                                }
                                else if (temp == "gB" || temp == "GB" || temp == "gb"){
                                        size *= 1024;
                                }
                                else if (temp == "Byte" || temp == "B" || temp == "b"){
                                        size /= 1024*1024;
                                }
                                fin_card->clear();
                                fin_card->seekg(0,std::ios::beg);
                                break;
                        }
                }
                return size;
        }
        else{
                return -1;
        }
}
MyProcessManager * MyProcessManager::GetMyProcessManager () [static]
Definition at line 28 of file MyProcessManager.cc.
References fMyProcessManager.
Referenced by MyAnalysisSvc::MyAnalysisSvc().
{
        if ( !fMyProcessManager ){
                fMyProcessManager = new MyProcessManager;
        }
        return fMyProcessManager;
}
int MyProcessManager::OpenFile ()
Definition at line 35 of file MyProcessManager.cc.
References buff, CloseFile(), fileOpened, and fin_card.
Referenced by GetMemorySize().
{
        CloseFile();
        pid_t id = getpid();
        buff.str("");
        buff.clear();
        buff<<"/proc/"<<id<<"/status";
        fin_card = new std::ifstream (buff.str().c_str());
        std::cout<<"In MyProcessManager::OpenFile: Opened file \""<<buff.str()<<"\""<<std::endl;
        if ( !fin_card ){
                fileOpened = false;
                return 1;
        }
        else{
                fileOpened = true;
                return 0;
        }
}
Member Data Documentation
std::stringstream MyProcessManager::buff [private]
Definition at line 23 of file MyProcessManager.hh.
Referenced by GetMemorySize(), OpenFile(), and ~MyProcessManager().
bool MyProcessManager::fileOpened [private]
Definition at line 24 of file MyProcessManager.hh.
Referenced by CloseFile(), GetMemorySize(), MyProcessManager(), and OpenFile().
std::ifstream* MyProcessManager::fin_card [private]
Definition at line 22 of file MyProcessManager.hh.
Referenced by CloseFile(), GetMemorySize(), MyProcessManager(), and OpenFile().
MyProcessManager * MyProcessManager::fMyProcessManager = 0 [static, private]
Definition at line 20 of file MyProcessManager.hh.
Referenced by GetMyProcessManager(), and MyProcessManager().
int MyProcessManager::MemoryConsumption [private]
Definition at line 21 of file MyProcessManager.hh.
Referenced by MyProcessManager().
The documentation for this class was generated from the following files:
include/MyProcessManager.hh
src/MyProcessManager.cc