g4sim: CdcGeometryParameterMessenger Class Reference
CdcGeometryParameterMessenger Class Reference
#include <CdcGeometryParameterMessenger.hh>
Public Member Functions
CdcGeometryParameterMessenger (MyVGeometryParameter *, G4String)
virtual ~CdcGeometryParameterMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
int MySetNewValue (G4UIcommand *, G4String)
CdcGeometryParameter * get_GeometryParameter ()
void set_GeometryParameter (CdcGeometryParameter *val)
void set_GeometryParameter (SimpleGeometryParameter *val)
void set_GeometryParameter (MyVGeometryParameter *val)
G4String get_Name ()
G4String get_GeoDirName ()
void set_Name (G4String val)
void set_GeoDirName (G4String val)
Private Attributes
CdcGeometryParameter * m_GeometryParameter
G4String m_SubDirName
G4UIdirectory * SubDir
Detailed Description
Definition at line 20 of file CdcGeometryParameterMessenger.hh.
Constructor & Destructor Documentation
CdcGeometryParameterMessenger::CdcGeometryParameterMessenger (MyVGeometryParameter * pGeometryParameter, G4String dirName)
Definition at line 20 of file CdcGeometryParameterMessenger.cc.
References MyVGeometryParameterMessenger::get_GeoDirName(), m_GeometryParameter, m_SubDirName, and SubDir.
:SimpleGeometryParameterMessenger(pGeometryParameter, dirName)
{
        m_GeometryParameter = dynamic_cast<CdcGeometryParameter*> (pGeometryParameter);
        if (!m_GeometryParameter){
                std::cout<<"In CdcGeometryParameterMessenger, Cannot convert pointer from MyVGeometryParameter* to CdcGeometryParameter!!!"<<std::endl;
    G4Exception("CdcGeometryParameterMessenger::CdcGeometryParameterMessenger()",
        "InvalidSetup", FatalException,
        "Cannot convert pointer from MyVGeometryParameter* to CdcGeometryParameter!!!");
        }
        G4String fGeoDirName = get_GeoDirName();
        m_SubDirName = fGeoDirName+"CdcGeometry/";
        SubDir = new G4UIdirectory(m_SubDirName);
        SubDir->SetGuidance("geometry control");
}
CdcGeometryParameterMessenger::~CdcGeometryParameterMessenger () [virtual]
Definition at line 40 of file CdcGeometryParameterMessenger.cc.
References SubDir.
{
        delete SubDir;
}
Member Function Documentation
G4String MyVGeometryParameterMessenger::get_GeoDirName () [inline, inherited]
Definition at line 32 of file MyVGeometryParameterMessenger.hh.
References MyVGeometryParameterMessenger::m_GeoDirName.
Referenced by CdcGeometryParameterMessenger(), and SimpleGeometryParameterMessenger::SimpleGeometryParameterMessenger().
{ return m_GeoDirName; }
CdcGeometryParameter* CdcGeometryParameterMessenger::get_GeometryParameter () [inline]
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 32 of file CdcGeometryParameterMessenger.hh.
References m_GeometryParameter.
{ return m_GeometryParameter; }
G4String MyVGeometryParameterMessenger::get_Name () [inline, inherited]
Definition at line 30 of file MyVGeometryParameterMessenger.hh.
References MyVGeometryParameterMessenger::m_Name.
{ return m_Name; }
int CdcGeometryParameterMessenger::MySetNewValue (G4UIcommand * command, G4String newValue)
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 51 of file CdcGeometryParameterMessenger.cc.
Referenced by SetNewValue().
{
        int status = 0; //0 means found the value
        status = MyVGeometryParameterMessenger::MySetNewValue(command, newValue); //check Parent Class first
        if ( !status ) return status;
        return status;
}
void MyVGeometryParameterMessenger::set_GeoDirName (G4String val) [inline, inherited]
Definition at line 37 of file MyVGeometryParameterMessenger.hh.
References MyVGeometryParameterMessenger::m_GeoDirName.
{ m_GeoDirName = val; }
void MyVGeometryParameterMessenger::set_GeometryParameter (MyVGeometryParameter * val) [inline, inherited]
Definition at line 36 of file MyVGeometryParameterMessenger.hh.
References MyVGeometryParameterMessenger::m_GeometryParameter.
Referenced by MyVGeometryParameterMessenger::MyVGeometryParameterMessenger().
{ m_GeometryParameter = val; }
void SimpleGeometryParameterMessenger::set_GeometryParameter (SimpleGeometryParameter * val) [inline, inherited]
Definition at line 38 of file SimpleGeometryParameterMessenger.hh.
References SimpleGeometryParameterMessenger::m_GeometryParameter.
{ m_GeometryParameter = val; }
void CdcGeometryParameterMessenger::set_GeometryParameter (CdcGeometryParameter * val) [inline]
Definition at line 35 of file CdcGeometryParameterMessenger.hh.
References m_GeometryParameter.
{ m_GeometryParameter = val; }
void MyVGeometryParameterMessenger::set_Name (G4String val) [inline, inherited]
Definition at line 35 of file MyVGeometryParameterMessenger.hh.
References MyVGeometryParameterMessenger::m_Name.
Referenced by MyVGeometryParameterMessenger::MyVGeometryParameterMessenger().
{ m_Name = val; }
void CdcGeometryParameterMessenger::SetNewValue (G4UIcommand * command, G4String newValue) [virtual]
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 45 of file CdcGeometryParameterMessenger.cc.
References MySetNewValue().
{
        MySetNewValue(command, newValue);
}
Member Data Documentation
CdcGeometryParameter* CdcGeometryParameterMessenger::m_GeometryParameter [private]
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 39 of file CdcGeometryParameterMessenger.hh.
Referenced by CdcGeometryParameterMessenger(), get_GeometryParameter(), and set_GeometryParameter().
G4String CdcGeometryParameterMessenger::m_SubDirName [private]
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 41 of file CdcGeometryParameterMessenger.hh.
Referenced by CdcGeometryParameterMessenger().
G4UIdirectory* CdcGeometryParameterMessenger::SubDir [private]
Reimplemented from SimpleGeometryParameterMessenger.
Definition at line 42 of file CdcGeometryParameterMessenger.hh.
Referenced by CdcGeometryParameterMessenger(), and ~CdcGeometryParameterMessenger().
The documentation for this class was generated from the following files:
include/CdcGeometryParameterMessenger.hh
src/CdcGeometryParameterMessenger.cc