g4sim: MyRoot Class Reference
MyRoot Class Reference
#include <MyRoot.hh>
Public Member Functions
MyRoot ()
~MyRoot ()
void OpenFile (std::string filename)
void CreateTree (std::string branchname, int fCircular=0)
void Fill ()
void SetBranch (std::string name, std::vector< double > *pVecD)
void SetBranch (std::string name, std::vector< int > *pVecI)
void SetBranch (std::string name, int *pI)
void SetBranch (std::string name, double *pD)
void SetBranch (std::string name, std::vector< std::string > *pVecCa)
void Save ()
int FlushBaskets ()
void Write ()
void Close ()
void SetVerbose (int val)
void SetPrintModulo (int val)
Static Public Member Functions
static MyRoot * GetMyRoot ()
Private Attributes
int fVerbose
int fPrintModulo
int nbFilled
TFile * m_file
TTree * m_tree
Static Private Attributes
static MyRoot * fMyRoot = 0
Detailed Description
Definition at line 18 of file MyRoot.hh.
Constructor & Destructor Documentation
MyRoot::MyRoot ()
Definition at line 14 of file MyRoot.cc.
References fMyRoot, fPrintModulo, and fVerbose.
        :m_file(0)
{
  if (fMyRoot){
    G4Exception("MyRoot::MyRoot()","Run0031",
        FatalException, "MyRoot constructed twice.");
  }
  fVerbose = 0;
  fPrintModulo = 0;
  fMyRoot = this;
        if ( fVerbose >= 5 ){
                printf("MyRoot\n");
        }
}
MyRoot::~MyRoot ()
Definition at line 29 of file MyRoot.cc.
References fVerbose, m_file, and m_tree.
{
        m_tree->Delete();
        if (m_file) delete m_file;
        if ( fVerbose >= 5 ){
                printf("~MyRoot\n");
        }
}
Member Function Documentation
void MyRoot::Close ()
Definition at line 110 of file MyRoot.cc.
References fVerbose, and m_file.
Referenced by MyAnalysisSvc::EndOfRunAction().
                  {
  m_file->Close();
        if ( fVerbose >= 5 ){
                std::cout<<"In MyRoot::Close"<<std::endl;
                std::cout<<"  m_file->Close()"<<std::endl;
        }
}
void MyRoot::CreateTree (std::string branchname, int fCircular = 0)
Definition at line 38 of file MyRoot.cc.
References fVerbose, m_tree, and nbFilled.
Referenced by MyAnalysisSvc::BeginOfRunAction().
{
  m_tree = new TTree(tree_name.c_str(),tree_name.c_str());
  nbFilled = 0;
//  m_tree->SetName(tree_name);
  //set circular
  if (fCircular){
                m_tree->SetCircular(fCircular);
        }
        if ( fVerbose >= 5 ){
                std::cout<<"In MyRoot::CreateTree"<<std::endl;
                std::cout<<"  New tree booked!!"<<std::endl;
                std::cout<<"  Name: "<<tree_name<<std::endl;
                std::cout<<"  Circular: "<<fCircular<<std::endl;
        }
}
void MyRoot::Fill ()
Definition at line 72 of file MyRoot.cc.
References fPrintModulo, fVerbose, m_tree, and nbFilled.
Referenced by MyAnalysisSvc::EndOfEventAction().
                 {
  m_tree->Fill();
        nbFilled++;
        if ( fVerbose >= 5 ){
                if ( fPrintModulo ){
                        if ( nbFilled%fPrintModulo == 0 ){
                                std::cout<<"In MyRoot::Fill"<<std::endl;
                                std::cout<<"  m_tree->Fill()"<<std::endl;
                                std::cout<<"  "<<nbFilled<<" times for this tree"<<std::endl;
                        }
                }
        }
}
int MyRoot::FlushBaskets ()
Definition at line 94 of file MyRoot.cc.
References fVerbose, and m_tree.
Referenced by MyAnalysisSvc::EndOfEventAction().
{
        if ( fVerbose >= 5 ){
                std::cout<<"In MyRoot::FlushBaskets"<<std::endl;
                std::cout<<"  m_tree->FlushBaskets()"<<std::endl;
        }
        return (m_tree->FlushBaskets());
}
MyRoot * MyRoot::GetMyRoot () [static]
Definition at line 65 of file MyRoot.cc.
References fMyRoot.
Referenced by MyAnalysisSvc::MyAnalysisSvc(), ProcessCountingSvc::SetBranch(), MonitorSD::SetBranch(), McTruthSvc::SetBranch(), and EventHeaderSvc::SetBranch().
{
  if ( !fMyRoot ){
    fMyRoot = new MyRoot;
  }
  return fMyRoot;
}
void MyRoot::OpenFile (std::string filename)
Definition at line 54 of file MyRoot.cc.
References fVerbose, and m_file.
Referenced by MyAnalysisSvc::BeginOfRunAction().
{
        if (m_file) delete m_file;
  m_file = new TFile (file_name.c_str(), "RECREATE");
        if ( fVerbose >= 5 ){
                std::cout<<"In MyRoot::OpenFile"<<std::endl;
                std::cout<<"  New file open!!"<<std::endl;
                std::cout<<"  Name: "<<file_name<<std::endl;
        }
}
void MyRoot::Save ()
Definition at line 86 of file MyRoot.cc.
References fVerbose, and m_tree.
Referenced by MyAnalysisSvc::EndOfEventAction().
                 {
        m_tree->AutoSave();
        if ( fVerbose >= 5 ){
                std::cout<<"In MyRoot::Save"<<std::endl;
                std::cout<<"  m_tree->AutoSave()"<<std::endl;
        }
}
void MyRoot::SetBranch (std::string name, std::vector< std::string > * pVecCa)
Definition at line 158 of file MyRoot.cc.
References fVerbose, and m_tree.
{
  m_tree->Branch(name.c_str(), pVecCa);
        if ( fVerbose >= 5 ){
                std::cout<<"In MyRoot::SetBranch"<<std::endl;
                std::cout<<"  New branch created!!"<<std::endl;
                std::cout<<"  Name: "<<name<<std::endl;
                std::cout<<"  Type: vector<string>"<<std::endl;
        }
}
void MyRoot::SetBranch (std::string name, double * pD)
Definition at line 148 of file MyRoot.cc.
References fVerbose, and m_tree.
{
  m_tree->Branch(name.c_str(), pD);
        if ( fVerbose >= 5 ){
                std::cout<<"In MyRoot::SetBranch"<<std::endl;
                std::cout<<"  New branch created!!"<<std::endl;
                std::cout<<"  Name: "<<name<<std::endl;
                std::cout<<"  Type: double"<<std::endl;
        }
}
void MyRoot::SetBranch (std::string name, int * pI)
Definition at line 138 of file MyRoot.cc.
References fVerbose, and m_tree.
{
  m_tree->Branch(name.c_str(), pI);
        if ( fVerbose >= 5 ){
                std::cout<<"In MyRoot::SetBranch"<<std::endl;
                std::cout<<"  New branch created!!"<<std::endl;
                std::cout<<"  Name: "<<name<<std::endl;
                std::cout<<"  Type: int"<<std::endl;
        }
}
void MyRoot::SetBranch (std::string name, std::vector< int > * pVecI)
Definition at line 128 of file MyRoot.cc.
References fVerbose, and m_tree.
{
  m_tree->Branch(name.c_str(), pVecI);
        if ( fVerbose >= 5 ){
                std::cout<<"In MyRoot::SetBranch"<<std::endl;
                std::cout<<"  New branch created!!"<<std::endl;
                std::cout<<"  Name: "<<name<<std::endl;
                std::cout<<"  Type: vector<int>"<<std::endl;
        }
}
void MyRoot::SetBranch (std::string name, std::vector< double > * pVecD)
Definition at line 118 of file MyRoot.cc.
References fVerbose, and m_tree.
Referenced by ProcessCountingSvc::SetBranch(), MonitorSD::SetBranch(), McTruthSvc::SetBranch(), and EventHeaderSvc::SetBranch().
{
  m_tree->Branch(name.c_str(), pVecD);
        if ( fVerbose >= 5 ){
                std::cout<<"In MyRoot::SetBranch"<<std::endl;
                std::cout<<"  New branch created!!"<<std::endl;
                std::cout<<"  Name: "<<name<<std::endl;
                std::cout<<"  Type: vector<double>"<<std::endl;
        }
}
void MyRoot::SetPrintModulo (int val) [inline]
Definition at line 46 of file MyRoot.hh.
References fPrintModulo.
Referenced by MyAnalysisSvc::set_out_card().
{fPrintModulo = val;};
void MyRoot::SetVerbose (int val) [inline]
Definition at line 45 of file MyRoot.hh.
References fVerbose.
Referenced by MyAnalysisSvc::set_out_card().
{fVerbose = val;};
void MyRoot::Write ()
Definition at line 102 of file MyRoot.cc.
References fVerbose, and m_tree.
Referenced by MyAnalysisSvc::EndOfRunAction().
                  {
  m_tree->Write();
        if ( fVerbose >= 5 ){
                std::cout<<"In MyRoot::Write"<<std::endl;
                std::cout<<"  m_tree->Write()"<<std::endl;
        }
}
Member Data Documentation
MyRoot * MyRoot::fMyRoot = 0 [static, private]
Definition at line 46 of file MyRoot.hh.
Referenced by GetMyRoot(), and MyRoot().
int MyRoot::fPrintModulo [private]
Definition at line 53 of file MyRoot.hh.
Referenced by Fill(), MyRoot(), and SetPrintModulo().
int MyRoot::fVerbose [private]
Definition at line 52 of file MyRoot.hh.
Referenced by Close(), CreateTree(), Fill(), FlushBaskets(), MyRoot(), OpenFile(), Save(), SetBranch(), SetVerbose(), Write(), and ~MyRoot().
TFile* MyRoot::m_file [private]
Definition at line 57 of file MyRoot.hh.
Referenced by Close(), OpenFile(), and ~MyRoot().
TTree* MyRoot::m_tree [private]
Definition at line 58 of file MyRoot.hh.
Referenced by CreateTree(), Fill(), FlushBaskets(), Save(), SetBranch(), Write(), and ~MyRoot().
int MyRoot::nbFilled [private]
Definition at line 54 of file MyRoot.hh.
Referenced by CreateTree(), and Fill().
The documentation for this class was generated from the following files:
include/MyRoot.hh
src/MyRoot.cc