g4sim: src/MyBLFieldMap.cc File Reference
src/MyBLFieldMap.cc File Reference
#include <fstream>
#include <string.h>
#include <ctype.h>
#include <assert.h>
#include "G4ElectroMagneticField.hh"
#include "MyBLFieldMap.hh"
#include "MyBLFuncs.hh"
#include "BTSpline1D.hh"
Classes
class InputFile
class FieldMapImpl
class GridImpl
class CylinderImpl
class TimeImpl
Defines
#define COMPONENT(C)
Functions
static void argDouble (G4double &var, const char *name, MyBLArgumentMap &namedArgs)
argDouble handles an argument with a value of G4double
static void argInt (G4int &var, const char *name, MyBLArgumentMap &namedArgs)
argInt handles an argument with a value of G4int
static G4String d2string (G4double v)
d2string converts a double to a G4String
static G4String i2string (int v)
i2string converts an int to a G4String
Define Documentation
#define COMPONENT (C)
Value:
G4double C = 0.0; \
        if(map##C) C =  map##C[m]*f0 + map##C[m+1]*f1 + \
                map##C[m+nX]*f2 + map##C[m+nX+1]*f3 + \
                map##C[m+nY*nX]*f4 + map##C[m+nY*nX+1]*f5 + \
                map##C[m+nY*nX+nX]*f6 + map##C[m+nY*nX+nX+1]*f7;
Referenced by GridImpl::getFieldValue().
Function Documentation
static void argDouble (G4double & var, const char * name, MyBLArgumentMap & namedArgs) [static]
argDouble handles an argument with a value of G4double
Definition at line 221 of file MyBLFieldMap.cc.
Referenced by CylinderImpl::CylinderImpl(), GridImpl::GridImpl(), MyBLFieldMap::readFile(), and TimeImpl::readTime().
{
    if(namedArgs.count(name) == 0) return;
    char *q;
    const char *p=namedArgs[name].c_str();
    G4double v = strtod(p,&q);
    if(p == q || *q != '\0') {
        G4cerr << "Invalid value for "<< name<<" in MyBLFieldMap"
            << G4endl;
        return;
    }
    var = v;
}
static void argInt (G4int & var, const char * name, MyBLArgumentMap & namedArgs) [static]
argInt handles an argument with a value of G4int
Definition at line 237 of file MyBLFieldMap.cc.
Referenced by CylinderImpl::CylinderImpl(), GridImpl::GridImpl(), and MyBLFieldMap::readFile().
{
    if(namedArgs.count(name) == 0) return;
    char *q;
    const char *p=namedArgs[name].c_str();
    G4int v = strtol(p,&q,0);
    if(p == q || *q != '\0') {
        G4cerr << "Invalid value for "<< name<<" in MyBLFieldMap"
            << G4endl;
        return;
    }
    var = v;
}
static G4String d2string (G4double v) [static]
d2string converts a double to a G4String
Definition at line 252 of file MyBLFieldMap.cc.
Referenced by MyBLFieldMap::createCylinderMap(), and MyBLFieldMap::createGridMap().
{
    char tmp[32];
    sprintf(tmp,"%.8g",v);
    return G4String(tmp);
}
static G4String i2string (int v) [static]
i2string converts an int to a G4String
Definition at line 260 of file MyBLFieldMap.cc.
Referenced by MyBLFieldMap::createCylinderMap(), and MyBLFieldMap::createGridMap().
{
    char tmp[32];
    sprintf(tmp,"%d",v);
    return G4String(tmp);
}