AlcapDAQ: CAEN/CAENUpgrader-1.4.1/CAENBridgeUpgrade/inc/A3818Upgrade.h File Reference
A3818Upgrade.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <time.h>
#include <sys/types.h>
#include <sys/timeb.h>
#include <string.h>
#include <stdarg.h>
#include <CAENVMElib.h>
#include "p30.h"
#include <a3818.h>
Macros
#define BITSTREAM_BYTES 1756544
#define FIRST_FIRMWARE_PAGE_BASE_WORD_ADDRESS 0x000000
#define SECOND_FIRMWARE_PAGE_BASE_WORD_ADDRESS 0x200000
#define THIRD_FIRMWARE_PAGE_BASE_WORD_ADDRESS 0x400000
#define FOURTH_FIRMWARE_PAGE_BASE_WORD_ADDRESS 0x600000
Typedefs
typedef enum A3818Upgrade_Mode A3818Upgrade_Mode
Enumerations
enum A3818Upgrade_Mode { A3818_UPGRADE_FULL = 0, A3818_UPGRADE_ERASE_ONLY = 1, A3818_UPGRADE_VERIFY_ONLY = 2 }
Functions
int A3818UpgradeFromFile (int32_t A3818_handle, FILE *binfile, int fwcopy, A3818Upgrade_Mode mode)
int A3818UpgradeFromMem (int32_t A3818_handle, char *fwdata, int fwsize, int fwcopy, A3818Upgrade_Mode mode)
Macro Definition Documentation
#define BITSTREAM_BYTES 1756544
Definition at line 48 of file A3818Upgrade.h.
Referenced by A3818UpgradeFromFile(), and A3818UpgradeFromMem().
#define FIRST_FIRMWARE_PAGE_BASE_WORD_ADDRESS 0x000000
Definition at line 51 of file A3818Upgrade.h.
#define FOURTH_FIRMWARE_PAGE_BASE_WORD_ADDRESS 0x600000
Definition at line 54 of file A3818Upgrade.h.
#define SECOND_FIRMWARE_PAGE_BASE_WORD_ADDRESS 0x200000
Definition at line 52 of file A3818Upgrade.h.
#define THIRD_FIRMWARE_PAGE_BASE_WORD_ADDRESS 0x400000
Definition at line 53 of file A3818Upgrade.h.
Typedef Documentation
typedef enum A3818Upgrade_Mode A3818Upgrade_Mode
Enumeration Type Documentation
enum A3818Upgrade_Mode
Enumerator
A3818_UPGRADE_FULL
A3818_UPGRADE_ERASE_ONLY
A3818_UPGRADE_VERIFY_ONLY
Definition at line 39 of file A3818Upgrade.h.
{
 /* Error Types */
  A3818_UPGRADE_FULL               =  0,
  A3818_UPGRADE_ERASE_ONLY         =  1,
  A3818_UPGRADE_VERIFY_ONLY        =  2,
  } A3818Upgrade_Mode;
Function Documentation
int A3818UpgradeFromFile (int32_t A3818_handle, FILE * binfile, int fwcopy, A3818Upgrade_Mode mode)
Definition at line 52 of file A3818Upgrade.c.
References A3818_EnableBPIAccess(), A3818_EnableSPIAccess(), A3818_UPGRADE_ERASE_ONLY, A3818_UPGRADE_FULL, A3818_UPGRADE_VERIFY_ONLY, BITSTREAM_BYTES, c, c1, eraseFirmware(), FIRST_FIRMWARE_PAGE_BASE_WORD_ADDRESS, FOURTH_FIRMWARE_PAGE_BASE_WORD_ADDRESS, get_time(), i, printf(), SECOND_FIRMWARE_PAGE_BASE_WORD_ADDRESS, THIRD_FIRMWARE_PAGE_BASE_WORD_ADDRESS, verifyFlash(), and writeFlash().
Referenced by main().
{
         uint32_t baseAddress;
         long currentTime, elapsedTime;
         int finish;
         unsigned char c, c1;
         uint32_t      bp;
         uint32_t      bufferLength;
         uint32_t      *buffer;
         unsigned int  verifyErrors = 0;
         buffer = malloc(BITSTREAM_BYTES * sizeof(uint32_t));
         switch(fwcopy) {
           case 0 :
              baseAddress =  FIRST_FIRMWARE_PAGE_BASE_WORD_ADDRESS;
              break;
           case 1 :
              baseAddress =  SECOND_FIRMWARE_PAGE_BASE_WORD_ADDRESS;
              break;
           case 2 :
              baseAddress =  THIRD_FIRMWARE_PAGE_BASE_WORD_ADDRESS;
              break;
           case 3 :
              baseAddress =  FOURTH_FIRMWARE_PAGE_BASE_WORD_ADDRESS;
              break;
           default :
              baseAddress =  SECOND_FIRMWARE_PAGE_BASE_WORD_ADDRESS;
              break;
         }
         bp = 0;
         finish = 0;
         // Carica il bitsream in un buffer di memoria
         currentTime = get_time();
         while( !finish ) {
            c = (unsigned char)fgetc(binfile);  // read one byte from file
            c1 = (unsigned char)fgetc(binfile);  // read one byte from file (Strataflash a 16 bit)
 #ifdef __SWAP__
            swap = 0;
            // Swap primo byte
            for( i = 0; i < 8; i++ )
              if( c & (1 << i) )
                 swap = swap | (0x80 >> i);
            swap1 = 0;
            // Swap secondo byte
            for( i = 0; i < 8; i++ )
              if( c1 & (1 << i) )
                swap1 = swap1 | (0x80 >> i);
            buffer[bp] = (uint32_t) ((swap1 <<8) | swap); // HACK : swap o non swap?
 #else
            buffer[bp] = (uint32_t) ((c1 <<8) | c);
 #endif // __SWAP__
            bp++;
            if( feof(binfile) )
              finish = 1;
         }  // end of while loop
         bufferLength = (--bp);
         if ((bufferLength*2) != BITSTREAM_BYTES) {
            printf("\nERROR: Input BIN file length (%d bytes) is different than expected bitstream size (%d bytes). Exiting.....\n", bufferLength*2, BITSTREAM_BYTES);
            free(buffer);
            return -1;
         }
         elapsedTime = get_time() - currentTime;
         printf("\nBitstream (%d bytes) loaded in %ld milliseconds\n", bufferLength*2, elapsedTime);
         A3818_EnableBPIAccess(A3818_handle);
         /* Cancellazione della zona di flash riservata al firmware */
         if ( (mode == A3818_UPGRADE_FULL      ) ||
              (mode == A3818_UPGRADE_ERASE_ONLY) ) {
             printf("Erasing flash ");
             fflush(stdout);
             currentTime = get_time();
             eraseFirmware(A3818_handle, baseAddress, fwcopy);
             elapsedTime = get_time() - currentTime;
             printf("\nFlash erased in %ld milliseconds\n", elapsedTime);
         }
         /* Programmazione immagine firmware in flash */
         if ( (mode == A3818_UPGRADE_FULL      ) ) {
             currentTime = get_time();
             writeFlash(A3818_handle, buffer, bufferLength, baseAddress);
             elapsedTime = get_time() - currentTime;
             printf("\n%d 16-bit words programmed in %ld milliseconds\n", bufferLength, elapsedTime);
         }
         /* Verifica immagine firmware in flash */
         if ( (mode == A3818_UPGRADE_FULL      ) ||
              (mode == A3818_UPGRADE_VERIFY_ONLY) ) {
             currentTime = get_time();
             verifyErrors = verifyFlash(A3818_handle, buffer, bufferLength, baseAddress);
             elapsedTime = get_time() - currentTime;
             printf("\n%d 16-bit words verified in %ld milliseconds\n", bufferLength, elapsedTime);
         }
         A3818_EnableSPIAccess(A3818_handle);
         if( verifyErrors > 0 ) {
                 printf("\n\n%d errors found during verify!\n",verifyErrors);
         } else {
                 printf("\n\nFirmware updated without errors. Written %d words\n",bufferLength);
         }
         free(buffer);
         return 0;
 }
int A3818UpgradeFromMem (int32_t A3818_handle, char * fwdata, int fwsize, int fwcopy, A3818Upgrade_Mode mode)
Definition at line 171 of file A3818Upgrade.c.
References A3818_EnableBPIAccess(), A3818_EnableSPIAccess(), A3818_UPGRADE_ERASE_ONLY, A3818_UPGRADE_FULL, A3818_UPGRADE_VERIFY_ONLY, BITSTREAM_BYTES, c, c1, eraseFirmware(), FIRST_FIRMWARE_PAGE_BASE_WORD_ADDRESS, FOURTH_FIRMWARE_PAGE_BASE_WORD_ADDRESS, get_time(), i, printf(), SECOND_FIRMWARE_PAGE_BASE_WORD_ADDRESS, THIRD_FIRMWARE_PAGE_BASE_WORD_ADDRESS, verifyFlash(), and writeFlash().
Referenced by main().
{
                 int fi = 0;
         uint32_t baseAddress;
         long currentTime, elapsedTime;
         int finish;
         unsigned char c, c1;
         uint32_t      bp;
         uint32_t      bufferLength;
         uint32_t      *buffer;
         unsigned int  verifyErrors = 0;
         buffer = malloc(BITSTREAM_BYTES * sizeof(uint32_t));
         switch(fwcopy) {
           case 0 :
              baseAddress =  FIRST_FIRMWARE_PAGE_BASE_WORD_ADDRESS;
              break;
           case 1 :
              baseAddress =  SECOND_FIRMWARE_PAGE_BASE_WORD_ADDRESS;
              break;
           case 2 :
              baseAddress =  THIRD_FIRMWARE_PAGE_BASE_WORD_ADDRESS;
              break;
           case 3 :
              baseAddress =  FOURTH_FIRMWARE_PAGE_BASE_WORD_ADDRESS;
              break;
           default :
              baseAddress =  SECOND_FIRMWARE_PAGE_BASE_WORD_ADDRESS;
              break;
         }
         bp = 0;
         finish = 0;
         // Carica il bitsream in un buffer di memoria
         currentTime = get_time();
         while( !finish ) {
            c = (unsigned char)fwdata[fi++];  // read one byte from file
            c1 = (unsigned char)fwdata[fi++];  // read one byte from file (Strataflash a 16 bit)
 #ifdef __SWAP__
            swap = 0;
            // Swap primo byte
            for( i = 0; i < 8; i++ )
              if( c & (1 << i) )
                 swap = swap | (0x80 >> i);
            swap1 = 0;
            // Swap secondo byte
            for( i = 0; i < 8; i++ )
              if( c1 & (1 << i) )
                swap1 = swap1 | (0x80 >> i);
            buffer[bp] = (uint32_t) ((swap1 <<8) | swap); // HACK : swap o non swap?
 #else
            buffer[bp] = (uint32_t) ((c1 <<8) | c);
 #endif // __SWAP__
            bp++;
            if( fi >= fwsize )
              finish = 1;
         }  // end of while loop
         bufferLength = (--bp);
         if ((bufferLength*2) != BITSTREAM_BYTES) {
            printf("\nERROR: Input BIN file length (%d bytes) is different than expected bitstream size (%d bytes). Exiting.....\n", bufferLength*2, BITSTREAM_BYTES);
            free(buffer);
            return -1;
         }
         elapsedTime = get_time() - currentTime;
         printf("\nBitstream (%d bytes) loaded in %ld milliseconds\n", bufferLength*2, elapsedTime);
         A3818_EnableBPIAccess(A3818_handle);
         /* Cancellazione della zona di flash riservata al firmware */
         if ( (mode == A3818_UPGRADE_FULL      ) ||
              (mode == A3818_UPGRADE_ERASE_ONLY) ) {
             printf("Erasing flash ");
             fflush(stdout);
             currentTime = get_time();
             eraseFirmware(A3818_handle, baseAddress, fwcopy);
             elapsedTime = get_time() - currentTime;
             printf("\nFlash erased in %ld milliseconds\n", elapsedTime);
         }
         /* Programmazione immagine firmware in flash */
         if ( (mode == A3818_UPGRADE_FULL      ) ) {
             currentTime = get_time();
             writeFlash(A3818_handle, buffer, bufferLength, baseAddress);
             elapsedTime = get_time() - currentTime;
             printf("\n%d 16-bit words programmed in %ld milliseconds\n", bufferLength, elapsedTime);
         }
         /* Verifica immagine firmware in flash */
         if ( (mode == A3818_UPGRADE_FULL      ) ||
              (mode == A3818_UPGRADE_VERIFY_ONLY) ) {
             currentTime = get_time();
             verifyErrors = verifyFlash(A3818_handle, buffer, bufferLength, baseAddress);
             elapsedTime = get_time() - currentTime;
             printf("\n%d 16-bit words verified in %ld milliseconds\n", bufferLength, elapsedTime);
         }
         A3818_EnableSPIAccess(A3818_handle);
         if( verifyErrors > 0 ) {
                 printf("\n\n%d errors found during verify!\n",verifyErrors);
         } else {
                 printf("\n\nFirmware updated without errors. Written %d words\n",bufferLength);
         }
         free(buffer);
         return 0;
 }