AlcapDAQ: analyzer/scripts/AlcapDict.cxx File Reference
AlcapDict.cxx File Reference
#include "RConfig.h"
#include "AlcapDict.h"
#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"
#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"
#include <new>
Data Structures
class G__Sizep2memfuncAlcapDict
class G__cpp_setup_initAlcapDict
Namespaces
ROOT
ROOT::Shadow
Constant Groups
ROOT
ROOT::Shadow
Macros
#define R__DICTIONARY_FILENAME AlcapDict
#define private public
#define protected public
#define G__ROOT
Typedefs
typedef TSetupData G__TTSetupData
typedef TPulseIsland G__TTPulseIsland
typedef TGlobalData G__TTGlobalData
Functions
void ROOT::TSetupData_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TSetupData (void *p=0)
static void * ROOT::newArray_TSetupData (Long_t size, void *p)
static void ROOT::delete_TSetupData (void *p)
static void ROOT::deleteArray_TSetupData (void *p)
static void ROOT::destruct_TSetupData (void *p)
static void ROOT::streamer_TSetupData (TBuffer &buf, void *obj)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TSetupData *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TSetupData *)
::ROOT::TGenericClassInfo * ROOT::_R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const ::TPulseIsland*)0x0)
ROOT::R__UseDummy (_R__UNIQUE_(Init))
void ROOT::TPulseIsland_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TPulseIsland (void *p=0)
static void * ROOT::newArray_TPulseIsland (Long_t size, void *p)
static void ROOT::delete_TPulseIsland (void *p)
static void ROOT::deleteArray_TPulseIsland (void *p)
static void ROOT::destruct_TPulseIsland (void *p)
static void ROOT::streamer_TPulseIsland (TBuffer &buf, void *obj)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TPulseIsland *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TPulseIsland *)
void ROOT::TGlobalData_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TGlobalData (void *p=0)
static void * ROOT::newArray_TGlobalData (Long_t size, void *p)
static void ROOT::delete_TGlobalData (void *p)
static void ROOT::deleteArray_TGlobalData (void *p)
static void ROOT::destruct_TGlobalData (void *p)
static void ROOT::streamer_TGlobalData (TBuffer &buf, void *obj)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TGlobalData *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TGlobalData *)
void ROOT::maplEstringcOdoublegR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOdoublegR_Dictionary ()
static void * ROOT::new_maplEstringcOdoublegR (void *p=0)
static void * ROOT::newArray_maplEstringcOdoublegR (Long_t size, void *p)
static void ROOT::delete_maplEstringcOdoublegR (void *p)
static void ROOT::deleteArray_maplEstringcOdoublegR (void *p)
static void ROOT::destruct_maplEstringcOdoublegR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< string, double > *)
void ROOT::maplEstringcOintgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOintgR_Dictionary ()
static void * ROOT::new_maplEstringcOintgR (void *p=0)
static void * ROOT::newArray_maplEstringcOintgR (Long_t size, void *p)
static void ROOT::delete_maplEstringcOintgR (void *p)
static void ROOT::deleteArray_maplEstringcOintgR (void *p)
static void ROOT::destruct_maplEstringcOintgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< string, int > *)
void ROOT::maplEstringcOstringgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOstringgR_Dictionary ()
static void * ROOT::new_maplEstringcOstringgR (void *p=0)
static void * ROOT::newArray_maplEstringcOstringgR (Long_t size, void *p)
static void ROOT::delete_maplEstringcOstringgR (void *p)
static void ROOT::deleteArray_maplEstringcOstringgR (void *p)
static void ROOT::destruct_maplEstringcOstringgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< string, string > *)
void ROOT::maplEstringcOvectorlETPulseIslandmUgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary ()
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p=0)
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void *p)
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *)
void ROOT::vectorlETPulseIslandmUgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::vectorlETPulseIslandmUgR_Dictionary ()
static void * ROOT::new_vectorlETPulseIslandmUgR (void *p=0)
static void * ROOT::newArray_vectorlETPulseIslandmUgR (Long_t size, void *p)
static void ROOT::delete_vectorlETPulseIslandmUgR (void *p)
static void ROOT::deleteArray_vectorlETPulseIslandmUgR (void *p)
static void ROOT::destruct_vectorlETPulseIslandmUgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const vector< TPulseIsland * > *)
void ROOT::vectorlEintgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::vectorlEintgR_Dictionary ()
static void * ROOT::new_vectorlEintgR (void *p=0)
static void * ROOT::newArray_vectorlEintgR (Long_t size, void *p)
static void ROOT::delete_vectorlEintgR (void *p)
static void ROOT::deleteArray_vectorlEintgR (void *p)
static void ROOT::destruct_vectorlEintgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const vector< int > *)
void G__cpp_reset_tagtableAlcapDict ()
void G__set_cpp_environmentAlcapDict ()
int G__cpp_dllrevAlcapDict ()
static int G__AlcapDict_504_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_28 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_29 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_30 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_34 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_35 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_36 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_37 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_38 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_39 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_40 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_41 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_504_0_42 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_28 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_29 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_30 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_31 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_512_0_32 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__AlcapDict_516_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
size_t G__get_sizep2memfuncAlcapDict ()
void G__cpp_setup_inheritanceAlcapDict ()
void G__cpp_setup_typetableAlcapDict ()
static void G__setup_memvarTSetupData (void)
static void G__setup_memvarTPulseIsland (void)
static void G__setup_memvarTGlobalData (void)
void G__cpp_setup_memvarAlcapDict ()
static void G__setup_memfuncTSetupData (void)
static void G__setup_memfuncTPulseIsland (void)
static void G__setup_memfuncTGlobalData (void)
void G__cpp_setup_memfuncAlcapDict ()
static void G__cpp_setup_global0 ()
static void G__cpp_setup_global1 ()
static void G__cpp_setup_global2 ()
void G__cpp_setup_globalAlcapDict ()
static void G__cpp_setup_func0 ()
static void G__cpp_setup_func1 ()
static void G__cpp_setup_func2 ()
static void G__cpp_setup_func3 ()
static void G__cpp_setup_func4 ()
static void G__cpp_setup_func5 ()
static void G__cpp_setup_func6 ()
static void G__cpp_setup_func7 ()
static void G__cpp_setup_func8 ()
static void G__cpp_setup_func9 ()
static void G__cpp_setup_func10 ()
static void G__cpp_setup_func11 ()
static void G__cpp_setup_func12 ()
static void G__cpp_setup_func13 ()
static void G__cpp_setup_func14 ()
static void G__cpp_setup_func15 ()
static void G__cpp_setup_func16 ()
static void G__cpp_setup_func17 ()
static void G__cpp_setup_func18 ()
static void G__cpp_setup_func19 ()
static void G__cpp_setup_func20 ()
void G__cpp_setup_funcAlcapDict ()
void G__cpp_setup_tagtableAlcapDict ()
void G__cpp_setupAlcapDict (void)
Variables
G__linked_taginfo G__AlcapDictLN_TClass = { "TClass" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_TBuffer = { "TBuffer" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_TObject = { "TObject" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_string = { "string" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_TH1I = { "TH1I" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_TSetupData = { "TSetupData" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_TPulseIsland = { "TPulseIsland" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_TGlobalData = { "TGlobalData" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR = { "vector<TPulseIsland*,allocator<TPulseIsland*> >" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator>" , 99 , -1 }
G__linked_taginfo G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >" , 99 , -1 }
G__cpp_setup_initAlcapDict G__cpp_setup_initializerAlcapDict
Macro Definition Documentation
#define G__ROOT
Definition at line 26 of file AlcapDict.cxx.
#define private public
Definition at line 11 of file AlcapDict.cxx.
#define protected public
Definition at line 12 of file AlcapDict.cxx.
#define R__DICTIONARY_FILENAME AlcapDict
Definition at line 7 of file AlcapDict.cxx.
Typedef Documentation
typedef TGlobalData G__TTGlobalData
Definition at line 1805 of file AlcapDict.cxx.
typedef TPulseIsland G__TTPulseIsland
Definition at line 1654 of file AlcapDict.cxx.
typedef TSetupData G__TTSetupData
Definition at line 1377 of file AlcapDict.cxx.
Function Documentation
static int G__AlcapDict_504_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1116 of file AlcapDict.cxx.
References TSetupData::Instance().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 85, (long) TSetupData::Instance());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1185 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 105, (long) ((const TSetupData*) G__getstructoffset())->GetTriggerPolarity(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1191 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 105, (long) ((const TSetupData*) G__getstructoffset())->GetPedestal(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1197 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) ((TSetupData*) G__getstructoffset())->SetDetectorName(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1203 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetClockTick(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1210 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetNBits(*((string*) G__int(libp->para[0])), (int) G__int(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1217 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetTimeShift(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1224 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetTriggerPolarity(*((string*) G__int(libp->para[0])), (int) G__int(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1231 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetPedestal(*((string*) G__int(libp->para[0])), (int) G__int(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1238 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetADCSlopeCalib(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1245 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetADCOffsetCalib(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1122 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       {
          string* pobj;
          string xobj = ((TSetupData*) G__getstructoffset())->GetBankName(*((string*) G__int(libp->para[0])));
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1252 of file AlcapDict.cxx.
References TSetupData::IsFADC().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) TSetupData::IsFADC(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1258 of file AlcapDict.cxx.
References TSetupData::IsHoustonCAEN().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) TSetupData::IsHoustonCAEN(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1264 of file AlcapDict.cxx.
References TSetupData::IsBostonCAEN().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) TSetupData::IsBostonCAEN(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1270 of file AlcapDict.cxx.
References TSetupData::IsSlow().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) TSetupData::IsSlow(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1276 of file AlcapDict.cxx.
References TSetupData::IsFast().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) TSetupData::IsFast(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1282 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 85, (long) TSetupData::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_28 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1288 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 67, (long) TSetupData::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_29 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1294 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 115, (long) TSetupData::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1135 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       {
          const string* pobj;
          const string xobj = ((const TSetupData*) G__getstructoffset())->GetDetectorName(*((string*) G__int(libp->para[0])));
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_30 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1300 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       TSetupData::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_34 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1307 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_35 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1314 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 67, (long) TSetupData::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_36 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1320 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 105, (long) TSetupData::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_37 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1326 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 67, (long) TSetupData::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_38 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1332 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 105, (long) TSetupData::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_39 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1339 of file AlcapDict.cxx.
References G__AlcapDictLN_TSetupData.
Referenced by G__setup_memfuncTSetupData().
 {
    TSetupData *p;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TSetupData[n];
      } else {
        p = new((void*) gvp) TSetupData[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TSetupData;
      } else {
        p = new((void*) gvp) TSetupData;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__AlcapDictLN_TSetupData));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1148 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       ((const TSetupData*) G__getstructoffset())->GetAllDetectors(*(map<std::string,std::string>*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_40 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1364 of file AlcapDict.cxx.
References G__AlcapDictLN_TSetupData.
Referenced by G__setup_memfuncTSetupData().
 {
    TSetupData* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TSetupData(*(TSetupData*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__AlcapDictLN_TSetupData));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_41 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1378 of file AlcapDict.cxx.
References i.
Referenced by G__setup_memfuncTSetupData().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TSetupData*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TSetupData*) (soff+(sizeof(TSetupData)*i)))->~G__TTSetupData();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TSetupData*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TSetupData*) (soff))->~G__TTSetupData();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_42 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1415 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
    TSetupData* dest = (TSetupData*) G__getstructoffset();
    *dest = *(TSetupData*) libp->para[0].ref;
    const TSetupData& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1155 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letdouble(result7, 100, (double) ((const TSetupData*) G__getstructoffset())->GetClockTick(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1161 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 105, (long) ((const TSetupData*) G__getstructoffset())->GetNBits(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1167 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letdouble(result7, 100, (double) ((const TSetupData*) G__getstructoffset())->GetADCSlopeCalib(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1173 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letdouble(result7, 100, (double) ((const TSetupData*) G__getstructoffset())->GetADCOffsetCalib(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_504_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1179 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letdouble(result7, 100, (double) ((const TSetupData*) G__getstructoffset())->GetTimeShift(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1427 of file AlcapDict.cxx.
References G__AlcapDictLN_TPulseIsland.
Referenced by G__setup_memfuncTPulseIsland().
 {
    TPulseIsland* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TPulseIsland[n];
      } else {
        p = new((void*) gvp) TPulseIsland[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TPulseIsland;
      } else {
        p = new((void*) gvp) TPulseIsland;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__AlcapDictLN_TPulseIsland));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1536 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetFastPulseAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1542 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetSlowPulseAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1548 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetPulseHeight());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1554 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetPulseTime());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1560 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 85, (long) ((const TPulseIsland*) G__getstructoffset())->GetPulseWaveform(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1566 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) ((const TPulseIsland*) G__getstructoffset())->GetPulseLength());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1572 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) ((const TPulseIsland*) G__getstructoffset())->GetPeakSample());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1578 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetPedestal((int) G__int(libp->para[0])));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1584 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 85, (long) TPulseIsland::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1590 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 67, (long) TPulseIsland::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1451 of file AlcapDict.cxx.
References G__AlcapDictLN_TPulseIsland.
Referenced by G__setup_memfuncTPulseIsland().
 {
    TPulseIsland* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 3
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new TPulseIsland(
 (int) G__int(libp->para[0]), *(vector<int>*) libp->para[1].ref
 , *((string*) G__int(libp->para[2])));
    } else {
      p = new((void*) gvp) TPulseIsland(
 (int) G__int(libp->para[0]), *(vector<int>*) libp->para[1].ref
 , *((string*) G__int(libp->para[2])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__AlcapDictLN_TPulseIsland));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1596 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 115, (long) TPulseIsland::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1602 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       TPulseIsland::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1609 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       ((TPulseIsland*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1616 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 67, (long) TPulseIsland::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1622 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) TPulseIsland::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_28 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1628 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 67, (long) TPulseIsland::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_29 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1634 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) TPulseIsland::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1471 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
    switch (libp->paran) {
    case 1:
       ((TPulseIsland*) G__getstructoffset())->Reset((Option_t*) G__int(libp->para[0]));
       G__setnull(result7);
       break;
    case 0:
       ((TPulseIsland*) G__getstructoffset())->Reset();
       G__setnull(result7);
       break;
    }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_30 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1641 of file AlcapDict.cxx.
References G__AlcapDictLN_TPulseIsland.
Referenced by G__setup_memfuncTPulseIsland().
 {
    TPulseIsland* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TPulseIsland(*(TPulseIsland*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__AlcapDictLN_TPulseIsland));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_31 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1655 of file AlcapDict.cxx.
References i.
Referenced by G__setup_memfuncTPulseIsland().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TPulseIsland*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TPulseIsland*) (soff+(sizeof(TPulseIsland)*i)))->~G__TTPulseIsland();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TPulseIsland*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TPulseIsland*) (soff))->~G__TTPulseIsland();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_32 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1692 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
    TPulseIsland* dest = (TPulseIsland*) G__getstructoffset();
    *dest = *(TPulseIsland*) libp->para[0].ref;
    const TPulseIsland& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1486 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       {
          const vector<int>* pobj;
          const vector<int> xobj = ((const TPulseIsland*) G__getstructoffset())->GetSamples();
          pobj = new vector<int>(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1499 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) ((const TPulseIsland*) G__getstructoffset())->GetTimeStamp());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1505 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       {
          const string* pobj;
          const string xobj = ((const TPulseIsland*) G__getstructoffset())->GetBankName();
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1518 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetClockTickInNs());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1524 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) ((const TPulseIsland*) G__getstructoffset())->GetTriggerPolarity());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_512_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1530 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1704 of file AlcapDict.cxx.
References TGlobalData::Instance().
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 85, (long) TGlobalData::Instance());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1742 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 67, (long) TGlobalData::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1748 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 105, (long) TGlobalData::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1754 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 67, (long) TGlobalData::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1760 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 105, (long) TGlobalData::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1767 of file AlcapDict.cxx.
References G__AlcapDictLN_TGlobalData.
Referenced by G__setup_memfuncTGlobalData().
 {
    TGlobalData *p;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TGlobalData[n];
      } else {
        p = new((void*) gvp) TGlobalData[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TGlobalData;
      } else {
        p = new((void*) gvp) TGlobalData;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__AlcapDictLN_TGlobalData));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1792 of file AlcapDict.cxx.
References G__AlcapDictLN_TGlobalData.
Referenced by G__setup_memfuncTGlobalData().
 {
    TGlobalData* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TGlobalData(*(TGlobalData*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__AlcapDictLN_TGlobalData));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1806 of file AlcapDict.cxx.
References i.
Referenced by G__setup_memfuncTGlobalData().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TGlobalData*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TGlobalData*) (soff+(sizeof(TGlobalData)*i)))->~G__TTGlobalData();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TGlobalData*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TGlobalData*) (soff))->~G__TTGlobalData();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1843 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTGlobalData().
 {
    TGlobalData* dest = (TGlobalData*) G__getstructoffset();
    *dest = *(TGlobalData*) libp->para[0].ref;
    const TGlobalData& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1710 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 85, (long) TGlobalData::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1716 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 67, (long) TGlobalData::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1722 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 115, (long) TGlobalData::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1728 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTGlobalData().
 {
       TGlobalData::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__AlcapDict_516_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1735 of file AlcapDict.cxx.
Referenced by G__setup_memfuncTGlobalData().
 {
       ((TGlobalData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
int G__cpp_dllrevAlcapDict ()
Definition at line 1109 of file AlcapDict.cxx.
 { return(30051515); }
void G__cpp_reset_tagtableAlcapDict ()
Definition at line 2338 of file AlcapDict.cxx.
References G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR, G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR, G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR, G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__AlcapDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR, G__AlcapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR, G__AlcapDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR, G__AlcapDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR, G__AlcapDictLN_string, G__AlcapDictLN_TBuffer, G__AlcapDictLN_TClass, G__AlcapDictLN_TGlobalData, G__AlcapDictLN_TH1I, G__AlcapDictLN_TMemberInspector, G__AlcapDictLN_TObject, G__AlcapDictLN_TPulseIsland, G__AlcapDictLN_TSetupData, G__AlcapDictLN_TVectorTlEdoublegR, G__AlcapDictLN_TVectorTlEfloatgR, G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR, G__AlcapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR, G__AlcapDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR, and G__AlcapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.
Referenced by G__set_cpp_environmentAlcapDict().
{
   G__AlcapDictLN_TClass.tagnum = -1 ;
   G__AlcapDictLN_TBuffer.tagnum = -1 ;
   G__AlcapDictLN_TMemberInspector.tagnum = -1 ;
   G__AlcapDictLN_TObject.tagnum = -1 ;
   G__AlcapDictLN_string.tagnum = -1 ;
   G__AlcapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
   G__AlcapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__AlcapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
   G__AlcapDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__AlcapDictLN_TVectorTlEfloatgR.tagnum = -1 ;
   G__AlcapDictLN_TVectorTlEdoublegR.tagnum = -1 ;
   G__AlcapDictLN_TH1I.tagnum = -1 ;
   G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR.tagnum = -1 ;
   G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR.tagnum = -1 ;
   G__AlcapDictLN_TSetupData.tagnum = -1 ;
   G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
   G__AlcapDictLN_TPulseIsland.tagnum = -1 ;
   G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
   G__AlcapDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__AlcapDictLN_TGlobalData.tagnum = -1 ;
   G__AlcapDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR.tagnum = -1 ;
   G__AlcapDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
 }
static void G__cpp_setup_func0 () static
Definition at line 2218 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
    G__lastifuncposition();
 }
static void G__cpp_setup_func1 () static
Definition at line 2223 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func10 () static
Definition at line 2250 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func11 () static
Definition at line 2253 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func12 () static
Definition at line 2256 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func13 () static
Definition at line 2259 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func14 () static
Definition at line 2262 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func15 () static
Definition at line 2265 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func16 () static
Definition at line 2268 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func17 () static
Definition at line 2271 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func18 () static
Definition at line 2274 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func19 () static
Definition at line 2277 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func2 () static
Definition at line 2226 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func20 () static
Definition at line 2280 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
    G__resetifuncposition();
 }
static void G__cpp_setup_func3 () static
Definition at line 2229 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func4 () static
Definition at line 2232 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func5 () static
Definition at line 2235 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func6 () static
Definition at line 2238 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func7 () static
Definition at line 2241 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func8 () static
Definition at line 2244 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
static void G__cpp_setup_func9 () static
Definition at line 2247 of file AlcapDict.cxx.
Referenced by G__cpp_setup_funcAlcapDict().
{
 }
void G__cpp_setup_funcAlcapDict ()
Definition at line 2285 of file AlcapDict.cxx.
References G__cpp_setup_func0(), G__cpp_setup_func1(), G__cpp_setup_func10(), G__cpp_setup_func11(), G__cpp_setup_func12(), G__cpp_setup_func13(), G__cpp_setup_func14(), G__cpp_setup_func15(), G__cpp_setup_func16(), G__cpp_setup_func17(), G__cpp_setup_func18(), G__cpp_setup_func19(), G__cpp_setup_func2(), G__cpp_setup_func20(), G__cpp_setup_func3(), G__cpp_setup_func4(), G__cpp_setup_func5(), G__cpp_setup_func6(), G__cpp_setup_func7(), G__cpp_setup_func8(), and G__cpp_setup_func9().
Referenced by G__cpp_setupAlcapDict().
{
   G__cpp_setup_func0();
   G__cpp_setup_func1();
   G__cpp_setup_func2();
   G__cpp_setup_func3();
   G__cpp_setup_func4();
   G__cpp_setup_func5();
   G__cpp_setup_func6();
   G__cpp_setup_func7();
   G__cpp_setup_func8();
   G__cpp_setup_func9();
   G__cpp_setup_func10();
   G__cpp_setup_func11();
   G__cpp_setup_func12();
   G__cpp_setup_func13();
   G__cpp_setup_func14();
   G__cpp_setup_func15();
   G__cpp_setup_func16();
   G__cpp_setup_func17();
   G__cpp_setup_func18();
   G__cpp_setup_func19();
   G__cpp_setup_func20();
 }
static void G__cpp_setup_global0 () static
Definition at line 2195 of file AlcapDict.cxx.
Referenced by G__cpp_setup_globalAlcapDict().
{
    /* Setting up global variables */
    G__resetplocal();
 }
static void G__cpp_setup_global1 () static
Definition at line 2202 of file AlcapDict.cxx.
Referenced by G__cpp_setup_globalAlcapDict().
{
 }
static void G__cpp_setup_global2 () static
Definition at line 2205 of file AlcapDict.cxx.
Referenced by G__cpp_setup_globalAlcapDict().
{
    G__resetglobalenv();
 }
void G__cpp_setup_globalAlcapDict ()
Definition at line 2209 of file AlcapDict.cxx.
References G__cpp_setup_global0(), G__cpp_setup_global1(), and G__cpp_setup_global2().
Referenced by G__cpp_setupAlcapDict().
{
   G__cpp_setup_global0();
   G__cpp_setup_global1();
   G__cpp_setup_global2();
 }
void G__cpp_setup_inheritanceAlcapDict ()
Definition at line 1898 of file AlcapDict.cxx.
References G__AlcapDictLN_TGlobalData, G__AlcapDictLN_TObject, G__AlcapDictLN_TPulseIsland, and G__AlcapDictLN_TSetupData.
Referenced by G__cpp_setupAlcapDict().
{
    /* Setting up class inheritance */
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__AlcapDictLN_TSetupData))) {
      TSetupData *G__Lderived;
      G__Lderived=(TSetupData*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__AlcapDictLN_TSetupData),G__get_linked_tagnum(&G__AlcapDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__AlcapDictLN_TPulseIsland))) {
      TPulseIsland *G__Lderived;
      G__Lderived=(TPulseIsland*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__AlcapDictLN_TPulseIsland),G__get_linked_tagnum(&G__AlcapDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__AlcapDictLN_TGlobalData))) {
      TGlobalData *G__Lderived;
      G__Lderived=(TGlobalData*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__AlcapDictLN_TGlobalData),G__get_linked_tagnum(&G__AlcapDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
 }
void G__cpp_setup_memfuncAlcapDict ()
Definition at line 2189 of file AlcapDict.cxx.
Referenced by G__cpp_setupAlcapDict().
{
 }
void G__cpp_setup_memvarAlcapDict ()
Definition at line 2038 of file AlcapDict.cxx.
Referenced by G__cpp_setupAlcapDict().
{
 }
void G__cpp_setup_tagtableAlcapDict ()
Definition at line 2365 of file AlcapDict.cxx.
References G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR, G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR, G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR, G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__AlcapDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR, G__AlcapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR, G__AlcapDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR, G__AlcapDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR, G__AlcapDictLN_string, G__AlcapDictLN_TBuffer, G__AlcapDictLN_TClass, G__AlcapDictLN_TGlobalData, G__AlcapDictLN_TH1I, G__AlcapDictLN_TMemberInspector, G__AlcapDictLN_TObject, G__AlcapDictLN_TPulseIsland, G__AlcapDictLN_TSetupData, G__AlcapDictLN_TVectorTlEdoublegR, G__AlcapDictLN_TVectorTlEfloatgR, G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR, G__AlcapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR, G__AlcapDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR, G__AlcapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR, G__setup_memfuncTGlobalData(), G__setup_memfuncTPulseIsland(), G__setup_memfuncTSetupData(), G__setup_memvarTGlobalData(), G__setup_memvarTPulseIsland(), and G__setup_memvarTSetupData().
Referenced by G__cpp_setupAlcapDict().
{
    /* Setting up class,struct,union tag entry */
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_TClass);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_TBuffer);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_TMemberInspector);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_TObject);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_string);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_TVectorTlEfloatgR);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_TVectorTlEdoublegR);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_TH1I);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__AlcapDictLN_TSetupData),sizeof(TSetupData),-1,28672,(char*)NULL,G__setup_memvarTSetupData,G__setup_memfuncTSetupData);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__AlcapDictLN_TPulseIsland),sizeof(TPulseIsland),-1,61696,(char*)NULL,G__setup_memvarTPulseIsland,G__setup_memfuncTPulseIsland);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__AlcapDictLN_TGlobalData),sizeof(TGlobalData),-1,28672,(char*)NULL,G__setup_memvarTGlobalData,G__setup_memfuncTGlobalData);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR);
 }
void G__cpp_setup_typetableAlcapDict ()
Definition at line 1930 of file AlcapDict.cxx.
References G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR, G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR, G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR, G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__AlcapDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR, G__AlcapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR, G__AlcapDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR, G__AlcapDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR, G__AlcapDictLN_TVectorTlEdoublegR, G__AlcapDictLN_TVectorTlEfloatgR, G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR, G__AlcapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR, G__AlcapDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR, and G__AlcapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.
Referenced by G__cpp_setupAlcapDict().
{
    /* Setting up typedef entry */
    G__search_typename2("Version_t",115,-1,0,-1);
    G__setnewtype(-1,"Class version identifier (short)",0);
    G__search_typename2("Option_t",99,-1,256,-1);
    G__setnewtype(-1,"Option string (const char)",0);
    G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__AlcapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AlcapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AlcapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AlcapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AlcapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__AlcapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AlcapDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AlcapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AlcapDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AlcapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__AlcapDictLN_TVectorTlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__AlcapDictLN_TVectorTlEdoublegR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,std::string>",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,double>",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,double>",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,int>",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,int>",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AlcapDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AlcapDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TPulseIsland*>",117,G__get_linked_tagnum(&G__AlcapDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AlcapDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AlcapDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AlcapDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AlcapDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,std::vector<TPulseIsland*> >",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,std::vector<TPulseIsland*> >",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string> >",117,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
 }
void G__cpp_setupAlcapDict (void)
Definition at line 2392 of file AlcapDict.cxx.
References G__cpp_setup_funcAlcapDict(), G__cpp_setup_globalAlcapDict(), G__cpp_setup_inheritanceAlcapDict(), G__cpp_setup_memfuncAlcapDict(), G__cpp_setup_memvarAlcapDict(), G__cpp_setup_tagtableAlcapDict(), G__cpp_setup_typetableAlcapDict(), G__get_sizep2memfuncAlcapDict(), and G__set_cpp_environmentAlcapDict().
Referenced by G__cpp_setup_initAlcapDict::G__cpp_setup_initAlcapDict().
{
   G__check_setup_version(30051515,"G__cpp_setupAlcapDict()");
   G__set_cpp_environmentAlcapDict();
   G__cpp_setup_tagtableAlcapDict();
   G__cpp_setup_inheritanceAlcapDict();
   G__cpp_setup_typetableAlcapDict();
   G__cpp_setup_memvarAlcapDict();
   G__cpp_setup_memfuncAlcapDict();
   G__cpp_setup_globalAlcapDict();
   G__cpp_setup_funcAlcapDict();
    if(0==G__getsizep2memfunc()) G__get_sizep2memfuncAlcapDict();
   return;
 }
size_t G__get_sizep2memfuncAlcapDict ()
Definition at line 1881 of file AlcapDict.cxx.
References G__Sizep2memfuncAlcapDict::sizep2memfunc().
Referenced by G__cpp_setupAlcapDict().
 {
   G__Sizep2memfuncAlcapDict a;
   G__setsizep2memfunc((int)a.sizep2memfunc());
   return((size_t)a.sizep2memfunc());
 }
void G__set_cpp_environmentAlcapDict ()
Definition at line 1100 of file AlcapDict.cxx.
References G__cpp_reset_tagtableAlcapDict().
Referenced by G__cpp_setupAlcapDict().
{
   G__add_compiledheader("TObject.h");
   G__add_compiledheader("TMemberInspector.h");
   G__add_compiledheader("../src/common/TPulseIsland.h");
   G__add_compiledheader("../src/common/TGlobalData.h");
   G__add_compiledheader("../src/common/TSetupData.h");
   G__cpp_reset_tagtableAlcapDict();
 }
static void G__setup_memfuncTGlobalData (void) static
Definition at line 2158 of file AlcapDict.cxx.
References G__AlcapDict_516_0_1(), G__AlcapDict_516_0_10(), G__AlcapDict_516_0_11(), G__AlcapDict_516_0_12(), G__AlcapDict_516_0_13(), G__AlcapDict_516_0_14(), G__AlcapDict_516_0_15(), G__AlcapDict_516_0_16(), G__AlcapDict_516_0_17(), G__AlcapDict_516_0_2(), G__AlcapDict_516_0_3(), G__AlcapDict_516_0_4(), G__AlcapDict_516_0_5(), G__AlcapDict_516_0_9(), G__AlcapDictLN_TClass, G__AlcapDictLN_TGlobalData, and TGlobalData::Instance().
Referenced by G__cpp_setup_tagtableAlcapDict().
{
    /* TGlobalData */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__AlcapDictLN_TGlobalData));
    G__memfunc_setup("Instance",821,G__AlcapDict_516_0_1, 85, G__get_linked_tagnum(&G__AlcapDictLN_TGlobalData), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TGlobalData* (*)())(&TGlobalData::Instance) ), 0);
    G__memfunc_setup("Class",502,G__AlcapDict_516_0_2, 85, G__get_linked_tagnum(&G__AlcapDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TGlobalData::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__AlcapDict_516_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TGlobalData::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__AlcapDict_516_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TGlobalData::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__AlcapDict_516_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TGlobalData::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__AlcapDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__AlcapDict_516_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__AlcapDict_516_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TGlobalData::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__AlcapDict_516_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TGlobalData::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__AlcapDict_516_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TGlobalData::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__AlcapDict_516_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TGlobalData::DeclFileLine) ), 0);
    // automatic default constructor
    G__memfunc_setup("TGlobalData", 1055, G__AlcapDict_516_0_14, (int) ('i'), G__get_linked_tagnum(&G__AlcapDictLN_TGlobalData), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    // automatic copy constructor
    G__memfunc_setup("TGlobalData", 1055, G__AlcapDict_516_0_15, (int) ('i'), G__get_linked_tagnum(&G__AlcapDictLN_TGlobalData), -1, 0, 1, 1, 1, 0, "u 'TGlobalData' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TGlobalData", 1181, G__AlcapDict_516_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__AlcapDict_516_0_17, (int) ('u'), G__get_linked_tagnum(&G__AlcapDictLN_TGlobalData), -1, 1, 1, 1, 1, 0, "u 'TGlobalData' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncTPulseIsland (void) static
Definition at line 2114 of file AlcapDict.cxx.
References G__AlcapDict_512_0_1(), G__AlcapDict_512_0_10(), G__AlcapDict_512_0_11(), G__AlcapDict_512_0_12(), G__AlcapDict_512_0_13(), G__AlcapDict_512_0_14(), G__AlcapDict_512_0_15(), G__AlcapDict_512_0_16(), G__AlcapDict_512_0_17(), G__AlcapDict_512_0_18(), G__AlcapDict_512_0_19(), G__AlcapDict_512_0_2(), G__AlcapDict_512_0_20(), G__AlcapDict_512_0_21(), G__AlcapDict_512_0_25(), G__AlcapDict_512_0_26(), G__AlcapDict_512_0_27(), G__AlcapDict_512_0_28(), G__AlcapDict_512_0_29(), G__AlcapDict_512_0_3(), G__AlcapDict_512_0_30(), G__AlcapDict_512_0_31(), G__AlcapDict_512_0_32(), G__AlcapDict_512_0_4(), G__AlcapDict_512_0_5(), G__AlcapDict_512_0_6(), G__AlcapDict_512_0_7(), G__AlcapDict_512_0_8(), G__AlcapDict_512_0_9(), G__AlcapDictLN_string, G__AlcapDictLN_TClass, G__AlcapDictLN_TH1I, G__AlcapDictLN_TPulseIsland, and G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR.
Referenced by G__cpp_setup_tagtableAlcapDict().
{
    /* TPulseIsland */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__AlcapDictLN_TPulseIsland));
    G__memfunc_setup("TPulseIsland",1208,G__AlcapDict_512_0_1, 105, G__get_linked_tagnum(&G__AlcapDictLN_TPulseIsland), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("TPulseIsland",1208,G__AlcapDict_512_0_2, 105, G__get_linked_tagnum(&G__AlcapDictLN_TPulseIsland), -1, 0, 3, 1, 1, 0,
 "i - - 0 - timestamp u 'vector<int,allocator<int> >' 'vector<int>' 11 - samples_vector "
 "u 'string' - 0 - bank_name", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Reset",515,G__AlcapDict_512_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' o", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetSamples",1013,G__AlcapDict_512_0_4, 117, G__get_linked_tagnum(&G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetTimeStamp",1204,G__AlcapDict_512_0_5, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetBankName",1053,G__AlcapDict_512_0_6, 117, G__get_linked_tagnum(&G__AlcapDictLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetClockTickInNs",1551,G__AlcapDict_512_0_7, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetTriggerPolarity",1864,G__AlcapDict_512_0_8, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetAmplitude",1221,G__AlcapDict_512_0_9, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetFastPulseAmplitude",2140,G__AlcapDict_512_0_10, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetSlowPulseAmplitude",2163,G__AlcapDict_512_0_11, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPulseHeight",1410,G__AlcapDict_512_0_12, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPulseTime",1208,G__AlcapDict_512_0_13, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPulseWaveform",1648,G__AlcapDict_512_0_14, 85, G__get_linked_tagnum(&G__AlcapDictLN_TH1I), -1, 0, 2, 1, 1, 8,
 "u 'string' - 0 - histname u 'string' - 0 - histtitle", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPulseLength",1419,G__AlcapDict_512_0_15, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPeakSample",1283,G__AlcapDict_512_0_16, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPedestal",1106,G__AlcapDict_512_0_17, 100, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - nPedSamples", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__AlcapDict_512_0_18, 85, G__get_linked_tagnum(&G__AlcapDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TPulseIsland::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__AlcapDict_512_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPulseIsland::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__AlcapDict_512_0_20, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TPulseIsland::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__AlcapDict_512_0_21, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TPulseIsland::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__AlcapDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__AlcapDict_512_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__AlcapDict_512_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPulseIsland::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__AlcapDict_512_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPulseIsland::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__AlcapDict_512_0_28, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPulseIsland::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__AlcapDict_512_0_29, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPulseIsland::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("TPulseIsland", 1208, G__AlcapDict_512_0_30, (int) ('i'), G__get_linked_tagnum(&G__AlcapDictLN_TPulseIsland), -1, 0, 1, 1, 1, 0, "u 'TPulseIsland' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TPulseIsland", 1334, G__AlcapDict_512_0_31, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__AlcapDict_512_0_32, (int) ('u'), G__get_linked_tagnum(&G__AlcapDictLN_TPulseIsland), -1, 1, 1, 1, 1, 0, "u 'TPulseIsland' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncTSetupData (void) static
Definition at line 2052 of file AlcapDict.cxx.
References G__AlcapDict_504_0_1(), G__AlcapDict_504_0_10(), G__AlcapDict_504_0_11(), G__AlcapDict_504_0_12(), G__AlcapDict_504_0_13(), G__AlcapDict_504_0_14(), G__AlcapDict_504_0_15(), G__AlcapDict_504_0_16(), G__AlcapDict_504_0_17(), G__AlcapDict_504_0_18(), G__AlcapDict_504_0_19(), G__AlcapDict_504_0_2(), G__AlcapDict_504_0_20(), G__AlcapDict_504_0_21(), G__AlcapDict_504_0_22(), G__AlcapDict_504_0_23(), G__AlcapDict_504_0_24(), G__AlcapDict_504_0_27(), G__AlcapDict_504_0_28(), G__AlcapDict_504_0_29(), G__AlcapDict_504_0_3(), G__AlcapDict_504_0_30(), G__AlcapDict_504_0_34(), G__AlcapDict_504_0_35(), G__AlcapDict_504_0_36(), G__AlcapDict_504_0_37(), G__AlcapDict_504_0_38(), G__AlcapDict_504_0_39(), G__AlcapDict_504_0_4(), G__AlcapDict_504_0_40(), G__AlcapDict_504_0_41(), G__AlcapDict_504_0_42(), G__AlcapDict_504_0_5(), G__AlcapDict_504_0_6(), G__AlcapDict_504_0_7(), G__AlcapDict_504_0_8(), G__AlcapDict_504_0_9(), G__AlcapDictLN_string, G__AlcapDictLN_TClass, G__AlcapDictLN_TSetupData, TSetupData::Instance(), TSetupData::IsBostonCAEN(), TSetupData::IsFADC(), TSetupData::IsFast(), TSetupData::IsHoustonCAEN(), and TSetupData::IsSlow().
Referenced by G__cpp_setup_tagtableAlcapDict().
{
    /* TSetupData */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__AlcapDictLN_TSetupData));
    G__memfunc_setup("Instance",821,G__AlcapDict_504_0_1, 85, G__get_linked_tagnum(&G__AlcapDictLN_TSetupData), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TSetupData* (*)())(&TSetupData::Instance) ), 0);
    G__memfunc_setup("GetBankName",1053,G__AlcapDict_504_0_2, 117, G__get_linked_tagnum(&G__AlcapDictLN_string), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - DetectorName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetDetectorName",1499,G__AlcapDict_504_0_3, 117, G__get_linked_tagnum(&G__AlcapDictLN_string), -1, 0, 1, 1, 1, 8, "u 'string' - 0 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetAllDetectors",1510,G__AlcapDict_504_0_4, 121, -1, -1, 0, 1, 1, 1, 8, "u 'map<string,string,less<string>,allocator<pair<const string,string> > >' 'map<std::string,std::string>' 1 - detectors", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetClockTick",1175,G__AlcapDict_504_0_5, 100, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetNBits",768,G__AlcapDict_504_0_6, 105, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetADCSlopeCalib",1478,G__AlcapDict_504_0_7, 100, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetADCOffsetCalib",1578,G__AlcapDict_504_0_8, 100, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetTimeShift",1197,G__AlcapDict_504_0_9, 100, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetTriggerPolarity",1864,G__AlcapDict_504_0_10, 105, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPedestal",1106,G__AlcapDict_504_0_11, 105, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetDetectorName",1511,G__AlcapDict_504_0_12, 103, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName u 'string' - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetClockTick",1187,G__AlcapDict_504_0_13, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName d - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetNBits",780,G__AlcapDict_504_0_14, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName i - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetTimeShift",1209,G__AlcapDict_504_0_15, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName d - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetTriggerPolarity",1876,G__AlcapDict_504_0_16, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName i - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetPedestal",1118,G__AlcapDict_504_0_17, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName i - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetADCSlopeCalib",1490,G__AlcapDict_504_0_18, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName d - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetADCOffsetCalib",1590,G__AlcapDict_504_0_19, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName d - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("IsFADC",458,G__AlcapDict_504_0_20, 103, -1, -1, 0, 1, 3, 1, 0, "u 'string' - 11 - BankName", "if the first letter is N then the bank name is for a FADC", (void*) G__func2void( (bool (*)(const string&))(&TSetupData::IsFADC) ), 0);
    G__memfunc_setup("IsHoustonCAEN",1219,G__AlcapDict_504_0_21, 103, -1, -1, 0, 1, 3, 1, 0, "u 'string' - 11 - BankName", "if the first letter is C then the bank name is for a CAEN", (void*) G__func2void( (bool (*)(const string&))(&TSetupData::IsHoustonCAEN) ), 0);
    G__memfunc_setup("IsBostonCAEN",1096,G__AlcapDict_504_0_22, 103, -1, -1, 0, 1, 3, 1, 0, "u 'string' - 11 - BankName", "if the first letter is C then the bank name is for a CAEN", (void*) G__func2void( (bool (*)(const string&))(&TSetupData::IsBostonCAEN) ), 0);
    G__memfunc_setup("IsSlow",609,G__AlcapDict_504_0_23, 103, -1, -1, 0, 1, 3, 1, 0, "u 'string' - 11 - BankName", "if the last letter is S then the bank name is for a Slow pulse", (void*) G__func2void( (bool (*)(const string&))(&TSetupData::IsSlow) ), 0);
    G__memfunc_setup("IsFast",586,G__AlcapDict_504_0_24, 103, -1, -1, 0, 1, 3, 1, 0, "u 'string' - 11 - BankName", "if the last letter is F then the bank name is for a Fast pulse", (void*) G__func2void( (bool (*)(const string&))(&TSetupData::IsFast) ), 0);
    G__memfunc_setup("GetValue",797,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 2, 1, 4, 8,
 "u 'map<string,double,less<string>,allocator<pair<const string,double> > >' 'map<std::string,double>' 11 - map u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetValue",797,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 2, 1, 4, 8,
 "u 'map<string,int,less<string>,allocator<pair<const string,int> > >' 'map<std::string,int>' 11 - map u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__AlcapDict_504_0_27, 85, G__get_linked_tagnum(&G__AlcapDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TSetupData::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__AlcapDict_504_0_28, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSetupData::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__AlcapDict_504_0_29, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TSetupData::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__AlcapDict_504_0_30, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TSetupData::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__AlcapDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__AlcapDict_504_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__AlcapDict_504_0_35, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSetupData::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__AlcapDict_504_0_36, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TSetupData::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__AlcapDict_504_0_37, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSetupData::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__AlcapDict_504_0_38, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TSetupData::DeclFileLine) ), 0);
    // automatic default constructor
    G__memfunc_setup("TSetupData", 991, G__AlcapDict_504_0_39, (int) ('i'), G__get_linked_tagnum(&G__AlcapDictLN_TSetupData), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    // automatic copy constructor
    G__memfunc_setup("TSetupData", 991, G__AlcapDict_504_0_40, (int) ('i'), G__get_linked_tagnum(&G__AlcapDictLN_TSetupData), -1, 0, 1, 1, 1, 0, "u 'TSetupData' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TSetupData", 1117, G__AlcapDict_504_0_41, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__AlcapDict_504_0_42, (int) ('u'), G__get_linked_tagnum(&G__AlcapDictLN_TSetupData), -1, 1, 1, 1, 1, 0, "u 'TSetupData' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memvarTGlobalData (void) static
Definition at line 2029 of file AlcapDict.cxx.
References TGlobalData::fPulseIslandToChannelMap, G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__AlcapDictLN_TClass, and G__AlcapDictLN_TGlobalData.
Referenced by G__cpp_setup_tagtableAlcapDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__AlcapDictLN_TGlobalData));
    { TGlobalData *p; p=(TGlobalData*)0x1000; if (p) { }
    G__memvar_setup((void*)((long)(&p->fPulseIslandToChannelMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),G__defined_typename("map<std::string,std::vector<TPulseIsland*> >"),-1,1,"fPulseIslandToChannelMap=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AlcapDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarTPulseIsland (void) static
Definition at line 2016 of file AlcapDict.cxx.
References G__AlcapDictLN_string, G__AlcapDictLN_TClass, G__AlcapDictLN_TPulseIsland, and G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR.
Referenced by G__cpp_setup_tagtableAlcapDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__AlcapDictLN_TPulseIsland));
    { TPulseIsland *p; p=(TPulseIsland*)0x1000; if (p) { }
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"fSamples=",0,"adc samples");
    G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fTimeStamp=",0,"time stamp in clock ticks");
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__AlcapDictLN_string),-1,-1,4,"fBankName=",0,"FADC Bank name of this island's channel");
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AlcapDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarTSetupData (void) static
Definition at line 1998 of file AlcapDict.cxx.
References TSetupData::fBankToADCOffsetCalibMap, TSetupData::fBankToADCSlopeCalibMap, TSetupData::fBankToBitMap, TSetupData::fBankToClockTickMap, TSetupData::fBankToDetectorMap, TSetupData::fBankToPedestalMap, TSetupData::fBankToPolarityMap, TSetupData::fBankToTimeShift, G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR, G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR, G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR, G__AlcapDictLN_TClass, and G__AlcapDictLN_TSetupData.
Referenced by G__cpp_setup_tagtableAlcapDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__AlcapDictLN_TSetupData));
    { TSetupData *p; p=(TSetupData*)0x1000; if (p) { }
    G__memvar_setup((void*)((long)(&p->fBankToDetectorMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),G__defined_typename("map<std::string,std::string>"),-1,1,"fBankToDetectorMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToClockTickMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),G__defined_typename("map<std::string,double>"),-1,1,"fBankToClockTickMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToBitMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),G__defined_typename("map<std::string,int>"),-1,1,"fBankToBitMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToADCSlopeCalibMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),G__defined_typename("map<std::string,double>"),-1,1,"fBankToADCSlopeCalibMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToADCOffsetCalibMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),G__defined_typename("map<std::string,double>"),-1,1,"fBankToADCOffsetCalibMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToTimeShift)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),G__defined_typename("map<std::string,double>"),-1,1,"fBankToTimeShift=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToPolarityMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),G__defined_typename("map<std::string,int>"),-1,1,"fBankToPolarityMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToPedestalMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),G__defined_typename("map<std::string,int>"),-1,1,"fBankToPedestalMap=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AlcapDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
Variable Documentation
G__linked_taginfo G__AlcapDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 }
Definition at line 2326 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), G__cpp_setup_typetableAlcapDict(), and G__setup_memvarTSetupData().
G__linked_taginfo G__AlcapDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 }
Definition at line 2325 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), G__cpp_setup_typetableAlcapDict(), and G__setup_memvarTSetupData().
G__linked_taginfo G__AlcapDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 }
Definition at line 2328 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), G__cpp_setup_typetableAlcapDict(), and G__setup_memvarTSetupData().
G__linked_taginfo G__AlcapDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >" , 99 , -1 }
Definition at line 2335 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), G__cpp_setup_typetableAlcapDict(), and G__setup_memvarTGlobalData().
G__linked_taginfo G__AlcapDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 }
Definition at line 2331 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), and G__cpp_setup_typetableAlcapDict().
G__linked_taginfo G__AlcapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 }
Definition at line 2319 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), and G__cpp_setup_typetableAlcapDict().
G__linked_taginfo G__AlcapDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator>" , 99 , -1 }
Definition at line 2334 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), and G__cpp_setup_typetableAlcapDict().
G__linked_taginfo G__AlcapDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 }
Definition at line 2321 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), and G__cpp_setup_typetableAlcapDict().
G__linked_taginfo G__AlcapDictLN_string = { "string" , 99 , -1 }
Definition at line 2317 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), G__setup_memfuncTPulseIsland(), G__setup_memfuncTSetupData(), and G__setup_memvarTPulseIsland().
G__linked_taginfo G__AlcapDictLN_TBuffer = { "TBuffer" , 99 , -1 }
Definition at line 2314 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), and G__cpp_setup_tagtableAlcapDict().
G__linked_taginfo G__AlcapDictLN_TClass = { "TClass" , 99 , -1 }
Definition at line 2313 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), G__setup_memfuncTGlobalData(), G__setup_memfuncTPulseIsland(), G__setup_memfuncTSetupData(), G__setup_memvarTGlobalData(), G__setup_memvarTPulseIsland(), and G__setup_memvarTSetupData().
G__linked_taginfo G__AlcapDictLN_TGlobalData = { "TGlobalData" , 99 , -1 }
Definition at line 2332 of file AlcapDict.cxx.
Referenced by G__AlcapDict_516_0_14(), G__AlcapDict_516_0_15(), G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_inheritanceAlcapDict(), G__cpp_setup_tagtableAlcapDict(), G__setup_memfuncTGlobalData(), and G__setup_memvarTGlobalData().
G__linked_taginfo G__AlcapDictLN_TH1I = { "TH1I" , 99 , -1 }
Definition at line 2324 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), and G__setup_memfuncTPulseIsland().
G__linked_taginfo G__AlcapDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 }
Definition at line 2315 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), and G__cpp_setup_tagtableAlcapDict().
G__linked_taginfo G__AlcapDictLN_TObject = { "TObject" , 99 , -1 }
Definition at line 2316 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_inheritanceAlcapDict(), and G__cpp_setup_tagtableAlcapDict().
G__linked_taginfo G__AlcapDictLN_TPulseIsland = { "TPulseIsland" , 99 , -1 }
Definition at line 2329 of file AlcapDict.cxx.
Referenced by G__AlcapDict_512_0_1(), G__AlcapDict_512_0_2(), G__AlcapDict_512_0_30(), G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_inheritanceAlcapDict(), G__cpp_setup_tagtableAlcapDict(), G__setup_memfuncTPulseIsland(), and G__setup_memvarTPulseIsland().
G__linked_taginfo G__AlcapDictLN_TSetupData = { "TSetupData" , 99 , -1 }
Definition at line 2327 of file AlcapDict.cxx.
Referenced by G__AlcapDict_504_0_39(), G__AlcapDict_504_0_40(), G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_inheritanceAlcapDict(), G__cpp_setup_tagtableAlcapDict(), G__setup_memfuncTSetupData(), and G__setup_memvarTSetupData().
G__linked_taginfo G__AlcapDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 }
Definition at line 2323 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), and G__cpp_setup_typetableAlcapDict().
G__linked_taginfo G__AlcapDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 }
Definition at line 2322 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), and G__cpp_setup_typetableAlcapDict().
G__linked_taginfo G__AlcapDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 }
Definition at line 2330 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), G__cpp_setup_typetableAlcapDict(), G__setup_memfuncTPulseIsland(), and G__setup_memvarTPulseIsland().
G__linked_taginfo G__AlcapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 }
Definition at line 2318 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), and G__cpp_setup_typetableAlcapDict().
G__linked_taginfo G__AlcapDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR = { "vector<TPulseIsland*,allocator<TPulseIsland*> >" , 99 , -1 }
Definition at line 2333 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), and G__cpp_setup_typetableAlcapDict().
G__linked_taginfo G__AlcapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 }
Definition at line 2320 of file AlcapDict.cxx.
Referenced by G__cpp_reset_tagtableAlcapDict(), G__cpp_setup_tagtableAlcapDict(), and G__cpp_setup_typetableAlcapDict().
G__cpp_setup_initAlcapDict G__cpp_setup_initializerAlcapDict
Definition at line 2415 of file AlcapDict.cxx.