AlcapDAQ: analyzer/md5-lib/mddriver.c File Reference
analyzer/md5-lib/mddriver.c File Reference
#include <stdio.h>
#include <time.h>
#include <string.h>
#include "global.h"
#include "md5.h"
Defines
#define MD 5
#define TEST_BLOCK_LEN 1000
#define TEST_BLOCK_COUNT 1000
#define MD5_CTX MD5_CTX
#define MDInit MD5Init
#define MDUpdate MD5Update
#define MDFinal MD5Final
Functions
static void MDString PROTO_LIST ((char *))
static void MDTimeTrial PROTO_LIST ((void))
static void MDPrint PROTO_LIST ((unsigned char[16]))
int main (int argc, argv)
static void MDString (char *string)
static void MDTimeTrial ()
static void MDTestSuite ()
static void MDFile (char *filename)
static void MDFilter ()
static void MDPrint (digest)
Define Documentation
#define MD 5
Definition at line 20 of file mddriver.c.
Referenced by MDFile(), MDString(), MDTestSuite(), and MDTimeTrial().
#define MD5_CTX MD5_CTX
Definition at line 62 of file mddriver.c.
#define MDFinal MD5Final
Definition at line 65 of file mddriver.c.
Referenced by MDFile(), MDFilter(), MDString(), and MDTimeTrial().
#define MDInit MD5Init
Definition at line 63 of file mddriver.c.
Referenced by MDFile(), MDFilter(), MDString(), and MDTimeTrial().
#define MDUpdate MD5Update
Definition at line 64 of file mddriver.c.
Referenced by MDFile(), MDFilter(), MDString(), and MDTimeTrial().
#define TEST_BLOCK_COUNT 1000
Definition at line 40 of file mddriver.c.
Referenced by MDTimeTrial().
#define TEST_BLOCK_LEN 1000
Definition at line 39 of file mddriver.c.
Referenced by MDTimeTrial().
Function Documentation
int main (int argc, argv)
Definition at line 77 of file mddriver.c.
References i, MDFile(), MDFilter(), MDString(), MDTestSuite(), and MDTimeTrial().
{
  int i;
  if (argc > 1)
 for (i = 1; i < argc; i++)
   if (argv[i][0] == '-' && argv[i][1] == 's')
     MDString (argv[i] + 2);
   else if (strcmp (argv[i], "-t") == 0)
     MDTimeTrial ();
   else if (strcmp (argv[i], "-x") == 0)
     MDTestSuite ();
   else
     MDFile (argv[i]);
  else
 MDFilter ();
  return (0);
}
static void MDFile (char * filename) [static]
Definition at line 178 of file mddriver.c.
References buffer, MD, MDFinal, MDInit, MDPrint(), and MDUpdate.
Referenced by main().
{
  FILE *file;
  MD5_CTX context;
  int len;
  unsigned char buffer[1024], digest[16];
  if ((file = fopen (filename, "rb")) == NULL)
 printf ("%s can't be opened\n", filename);
  else {
 MDInit (&context);
 while (len = fread (buffer, 1, 1024, file))
   MDUpdate (&context, buffer, len);
 MDFinal (digest, &context);
 fclose (file);
 printf ("MD%d (%s) = ", MD, filename);
 MDPrint (digest);
 printf ("\n");
  }
}
static void MDFilter () [static]
Definition at line 205 of file mddriver.c.
References buffer, MDFinal, MDInit, MDPrint(), and MDUpdate.
Referenced by main().
{
  MD5_CTX context;
  int len;
  unsigned char buffer[16], digest[16];
  MDInit (&context);
  while (len = fread (buffer, 1, 16, stdin))
 MDUpdate (&context, buffer, len);
  MDFinal (digest, &context);
  MDPrint (digest);
  printf ("\n");
}
static void MDPrint (digest) [static]
Definition at line 222 of file mddriver.c.
References i.
Referenced by MDFile(), MDFilter(), MDString(), and MDTimeTrial().
{
  unsigned int i;
  for (i = 0; i < 16; i++)
 printf ("%02x", digest[i]);
}
static void MDString (char * string) [static]
Definition at line 102 of file mddriver.c.
References MD, MDFinal, MDInit, MDPrint(), and MDUpdate.
Referenced by main(), and MDTestSuite().
{
  MD5_CTX context;
  unsigned char digest[16];
  unsigned int len = strlen (string);
  MDInit (&context);
  MDUpdate (&context, string, len);
  MDFinal (digest, &context);
  printf ("MD%d (\"%s\") = ", MD, string);
  MDPrint (digest);
  printf ("\n");
}
static void MDTestSuite () [static]
Definition at line 160 of file mddriver.c.
References MD, and MDString().
Referenced by main().
{
  printf ("MD%d test suite:\n", MD);
  MDString ("");
  MDString ("a");
  MDString ("abc");
  MDString ("message digest");
  MDString ("abcdefghijklmnopqrstuvwxyz");
  MDString
 ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789");
  MDString
 ("1234567890123456789012345678901234567890\
1234567890123456789012345678901234567890");
}
static void MDTimeTrial () [static]
Definition at line 121 of file mddriver.c.
References i, MD, MDFinal, MDInit, MDPrint(), MDUpdate, TEST_BLOCK_COUNT, TEST_BLOCK_LEN, and time.
Referenced by main().
{
  MD5_CTX context;
  time_t endTime, startTime;
  unsigned char block[TEST_BLOCK_LEN], digest[16];
  unsigned int i;
  printf
 ("MD%d time trial. Digesting %d %d-byte blocks ...", MD,
  TEST_BLOCK_LEN, TEST_BLOCK_COUNT);
  /* Initialize block */
  for (i = 0; i < TEST_BLOCK_LEN; i++)
 block[i] = (unsigned char)(i & 0xff);
  /* Start timer */
  time (&startTime);
  /* Digest blocks */
  MDInit (&context);
  for (i = 0; i < TEST_BLOCK_COUNT; i++)
 MDUpdate (&context, block, TEST_BLOCK_LEN);
  MDFinal (digest, &context);
  /* Stop timer */
  time (&endTime);
  printf (" done\n");
  printf ("Digest = ");
  MDPrint (digest);
  printf ("\nTime = %ld seconds\n", (long)(endTime-startTime));
  printf
 ("Speed = %ld bytes/second\n",
  (long)TEST_BLOCK_LEN * (long)TEST_BLOCK_COUNT/(endTime-startTime));
}
static void MDPrint PROTO_LIST ((unsigned char[16])) [static]
static void MDFilter PROTO_LIST ((void)) [static]
static void MDFile PROTO_LIST ((char *)) [static]