AlcapDAQ: midas/drivers/bus/bt617/btapi.h File Reference
midas/drivers/bus/bt617/btapi.h File Reference
#include <stddef.h>
#include "btdef.h"
Defines
#define BT_EXTERN extern
#define BT_METHOD
Functions
BT_EXTERN bt_dev_t BT_METHOD bt_str2dev (const char *name_p)
BT_EXTERN char *BT_METHOD bt_gen_name (int unit, bt_dev_t logdev, char *devname_p, size_t max_devname)
BT_EXTERN bt_error_t BT_METHOD bt_open (bt_desc_t *btd_p, const char *devname_p, bt_accessflag_t flags)
BT_EXTERN bt_error_t BT_METHOD bt_close (bt_desc_t btd_p)
BT_EXTERN bt_error_t BT_METHOD bt_chkerr (bt_desc_t btd_p)
BT_EXTERN bt_error_t BT_METHOD bt_clrerr (bt_desc_t btd_p)
BT_EXTERN bt_error_t BT_METHOD bt_perror (bt_desc_t btd_p, bt_error_t errval, const char *msg_p)
BT_EXTERN char *BT_METHOD bt_strerror (bt_desc_t btd_p, bt_error_t status, const char *msg_p, char *buf_p, size_t buf_len)
BT_EXTERN bt_error_t BT_METHOD bt_init (bt_desc_t btd_p)
BT_EXTERN bt_error_t BT_METHOD bt_read (bt_desc_t btd_p, void *buf_p, bt_devaddr_t xfer_off, size_t xfer_len, size_t *xfer_done_p)
BT_EXTERN bt_error_t BT_METHOD bt_write (bt_desc_t btd_p, void *buf_p, bt_devaddr_t xfer_off, size_t xfer_len, size_t *xfer_done_p)
BT_EXTERN bt_error_t BT_METHOD bt_get_info (bt_desc_t btd_p, bt_info_t param, bt_devdata_t *value_p)
BT_EXTERN bt_error_t BT_METHOD bt_set_info (bt_desc_t btd_p, bt_info_t param, bt_devdata_t value)
BT_EXTERN bt_error_t BT_METHOD bt_icbr_install (bt_desc_t btd_p, bt_irq_t irq_type, bt_icbr_t *icbr_p, void *param_p, bt_data32_t vector)
BT_EXTERN bt_error_t BT_METHOD bt_icbr_remove (bt_desc_t btd_p, bt_irq_t irq_type, bt_icbr_t *icbr_p)
BT_EXTERN bt_error_t BT_METHOD bt_lock (bt_desc_t btd_p, bt_msec_t wait_len)
BT_EXTERN bt_error_t BT_METHOD bt_unlock (bt_desc_t btd_p)
BT_EXTERN bt_error_t BT_METHOD bt_mmap (bt_desc_t btd_p, void **map_p, bt_devaddr_t map_off, size_t map_len, bt_accessflag_t flags, bt_swap_t swapping)
BT_EXTERN bt_error_t BT_METHOD bt_unmmap (bt_desc_t btd_p, void *map_p, size_t map_len)
BT_EXTERN bt_error_t BT_METHOD bt_bind (bt_desc_t btd_p, bt_binddesc_t *bind_p, bt_devaddr_t *offset_p, void *buf_p, size_t buf_len, bt_accessflag_t flags, bt_swap_t swapping)
BT_EXTERN bt_error_t BT_METHOD bt_unbind (bt_desc_t btd_p, bt_binddesc_t desc)
BT_EXTERN const char *BT_METHOD bt_dev2str (bt_dev_t type)
BT_EXTERN bt_error_t BT_METHOD bt_ctrl (bt_desc_t btd_p, int ctrl, void *param_p)
Define Documentation
#define BT_EXTERN extern
Definition at line 31 of file btapi.h.
#define BT_METHOD
Definition at line 41 of file btapi.h.
Function Documentation
BT_EXTERN bt_error_t BT_METHOD bt_bind (bt_desc_t btd_p, bt_binddesc_t * bind_p, bt_devaddr_t * offset_p, void * buf_p, size_t buf_len, bt_accessflag_t flags, bt_swap_t swapping)
BT_EXTERN bt_error_t BT_METHOD bt_chkerr (bt_desc_t btd_p)
Referenced by application_icbr().
BT_EXTERN bt_error_t BT_METHOD bt_close (bt_desc_t btd_p)
Referenced by fb_exit(), fb_init(), and vme_close().
BT_EXTERN bt_error_t BT_METHOD bt_clrerr (bt_desc_t btd_p)
Referenced by fb_init(), and vme_open().
BT_EXTERN bt_error_t BT_METHOD bt_ctrl (bt_desc_t btd_p, int ctrl, void * param_p)
BT_EXTERN const char* BT_METHOD bt_dev2str (bt_dev_t type)
BT_EXTERN char* BT_METHOD bt_gen_name (int unit, bt_dev_t logdev, char * devname_p, size_t max_devname)
Referenced by fb_init(), and vme_open().
BT_EXTERN bt_error_t BT_METHOD bt_get_info (bt_desc_t btd_p, bt_info_t param, bt_devdata_t * value_p)
Referenced by fb_init(), and vme_ioctl().
BT_EXTERN bt_error_t BT_METHOD bt_icbr_install (bt_desc_t btd_p, bt_irq_t irq_type, bt_icbr_t * icbr_p, void * param_p, bt_data32_t vector)
Referenced by fb_interrupt_attach().
BT_EXTERN bt_error_t BT_METHOD bt_icbr_remove (bt_desc_t btd_p, bt_irq_t irq_type, bt_icbr_t * icbr_p)
Referenced by fb_interrupt_detach().
BT_EXTERN bt_error_t BT_METHOD bt_init (bt_desc_t btd_p)
Referenced by fb_init(), and vme_open().
BT_EXTERN bt_error_t BT_METHOD bt_lock (bt_desc_t btd_p, bt_msec_t wait_len)
BT_EXTERN bt_error_t BT_METHOD bt_mmap (bt_desc_t btd_p, void ** map_p, bt_devaddr_t map_off, size_t map_len, bt_accessflag_t flags, bt_swap_t swapping)
Referenced by fb_init(), and vme_mmap().
BT_EXTERN bt_error_t BT_METHOD bt_open (bt_desc_t * btd_p, const char * devname_p, bt_accessflag_t flags)
Referenced by fb_init(), and vme_open().
BT_EXTERN bt_error_t BT_METHOD bt_perror (bt_desc_t btd_p, bt_error_t errval, const char * msg_p)
Referenced by fb_interrupt_attach(), vme_close(), vme_mmap(), vme_open(), vme_read(), vme_unmap(), and vme_write().
BT_EXTERN bt_error_t BT_METHOD bt_read (bt_desc_t btd_p, void * buf_p, bt_devaddr_t xfer_off, size_t xfer_len, size_t * xfer_done_p)
Referenced by vme_read().
BT_EXTERN bt_error_t BT_METHOD bt_set_info (bt_desc_t btd_p, bt_info_t param, bt_devdata_t value)
Referenced by fb_init(), vme_ioctl(), vme_open(), vme_read(), and vme_write().
BT_EXTERN bt_dev_t BT_METHOD bt_str2dev (const char * name_p)
BT_EXTERN char* BT_METHOD bt_strerror (bt_desc_t btd_p, bt_error_t status, const char * msg_p, char * buf_p, size_t buf_len)
BT_EXTERN bt_error_t BT_METHOD bt_unbind (bt_desc_t btd_p, bt_binddesc_t desc)
BT_EXTERN bt_error_t BT_METHOD bt_unlock (bt_desc_t btd_p)
BT_EXTERN bt_error_t BT_METHOD bt_unmmap (bt_desc_t btd_p, void * map_p, size_t map_len)
Referenced by fb_exit(), and vme_unmap().
BT_EXTERN bt_error_t BT_METHOD bt_write (bt_desc_t btd_p, void * buf_p, bt_devaddr_t xfer_off, size_t xfer_len, size_t * xfer_done_p)
Referenced by vme_write().