AlcapDAQ: CAEN/CAENVMELib/CAENVMELib-2.30.2/sample/CAENVMEDemoMain.c File Reference
CAENVMEDemoMain.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include "CAENVMElib.h"
#include "console.h"
Functions
void CaenVmeManual (long, short)
int main (int argc, void *argv[])
Function Documentation
void CaenVmeManual (long , short)
Referenced by main().
int main (int argc, void * argv[])
Definition at line 57 of file CAENVMEDemoMain.c.
References CAENVME_End(), CAENVME_Init(), CaenVmeManual(), con_end(), con_init(), cvSuccess, cvV1718, cvV2718, and printf().
 {
 CVBoardTypes  VMEBoard;
 short         Link;
 short         Device;
 int32_t       BHandle;
 if( (argc != 3) && (argc != 4) )
     {
     printf("Usage: CAENVMEDemo V1718 <VMEDevice>\n");
     printf("       CAENVMEDemo V2718 <VMEDevice> <VMELink>\n");
     exit(1);
     }
 else
     {
     if( strcmp((char*)argv[1], "V1718") == 0 )
         {
         if( argc == 3 )
             {
             VMEBoard = cvV1718;
             Device = atoi((const char*)argv[2]);
             Link = 0;
             }
         else
             {
             printf("       CAENVMEDemo V1718 <VMEDevice>\n");
             exit(1);
             }
         }
     else
         {
         if( strcmp((char*)argv[1], "V2718") == 0 )
             {
             if( argc == 4 )
                 {
                 Device = atoi((const char*) argv[2]);
                 Link = atoi((const char*) argv[3]);
                 VMEBoard = cvV2718;
                 }
             else
                 {
                 printf("       CAENVMEDemo V2718 <VMEDevice> <VMELink>\n");
                 exit(1);
                 }
             }
         else
             {
             printf("Usage: CAENVMEDemo V1718 <VMEDevice>\n");
             printf("       CAENVMEDemo V2718 <VMEDevice> <VMELink>\n");
             exit(1);
             }
         }
     }
 // Initialize the Board
 if( CAENVME_Init(VMEBoard, Link, Device, &BHandle) != cvSuccess )
     {
     printf("\n\n Error opening the device\n");
     exit(1);
     }
 con_init() ;
 // CAENVME_SetFIFOMode(BHandle,1) ;
 CaenVmeManual(BHandle,1) ;
 con_end() ;
 CAENVME_End(BHandle);
 }