AlcapDAQ: midas/drivers/device/caen170a.c File Reference
midas/drivers/device/caen170a.c File Reference
#include "midas.h"
#include "msystem.h"
#include "camacnul.c"
#include "esone.c"
Defines
#define FRAME_TO_CHANNEL 0
#define CHANNEL_TO_FRAME 1
#define CAEN170A_STR "\Branch = INT : 0\n\Crate = INT : 7\n\Station = INT : 1\n\Mainframe = INT[16] :\n\[0] 11\n\[1] 21\n\[2] 0\n\[3] 0\n\[4] 0\n\[5] 0\n\[6] 0\n\[7] 0\n\[8] 0\n\[9] 0\n\[10] 0\n\[11] 0\n\[12] 0\n\[13] 0\n\[14] 0\n\[15] 0\n\"
Functions
INT caen170a_init (HNDLE hKeyRoot, INT index, INT channels)
INT caen170a_exit (INT index)
INT caen170a_assign_channel (INT direction, INT *channel, INT *frame, INT *chanframe)
INT caen170a_set (INT index, INT channel, float fvalue)
INT caen170a_set_all (INT index, INT channels, float value)
INT caen170a_get (INT index, INT channel, float *pvalue)
INT caen170a_get_all (INT index, INT channels, float *array)
INT caen170a (INT cmd,...)
Variables
struct {
INT branch
INT crate
INT station
INT mainframe [16]
INT ext0
INT ext1
unsigned long st
} caen
Define Documentation
#define CAEN170A_STR "\Branch = INT : 0\n\Crate = INT : 7\n\Station = INT : 1\n\Mainframe = INT[16] :\n\[0] 11\n\[1] 21\n\[2] 0\n\[3] 0\n\[4] 0\n\[5] 0\n\[6] 0\n\[7] 0\n\[8] 0\n\[9] 0\n\[10] 0\n\[11] 0\n\[12] 0\n\[13] 0\n\[14] 0\n\[15] 0\n\"
Definition at line 42 of file caen170a.c.
Referenced by caen170a_init().
#define CHANNEL_TO_FRAME 1
Definition at line 40 of file caen170a.c.
Referenced by caen170a_assign_channel(), caen170a_get(), caen170a_set(), lrs4032_assign_channel(), lrs4032_get(), and lrs4032_set().
#define FRAME_TO_CHANNEL 0
Definition at line 39 of file caen170a.c.
Referenced by caen170a_assign_channel(), and lrs4032_assign_channel().
Function Documentation
INT caen170a (INT cmd, ...)
Definition at line 309 of file caen170a.c.
References caen170a_exit(), caen170a_get(), caen170a_get_all(), caen170a_init(), caen170a_set(), caen170a_set_all(), channel, cm_msg, CMD_EXIT, CMD_GET, CMD_GET_ALL, CMD_GET_CURRENT, CMD_GET_CURRENT_ALL, CMD_INIT, CMD_SET, CMD_SET_ALL, CMD_SET_CURRENT_LIMIT, FE_ERR_DRIVER, FE_SUCCESS, hKey, index, MERROR, status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status, index;
   float value, *pvalue;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      index = va_arg(argptr, INT);
      channel = va_arg(argptr, INT);
      status = caen170a_init(hKey, index, channel);
      break;
   case CMD_EXIT:
      index = va_arg(argptr, INT);
      status = caen170a_exit(index);
      break;
   case CMD_SET:
      index = va_arg(argptr, INT);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
#ifdef DEBUG
      printf("in caen170a cmd set ->:%i -chan:%i -Val:%f ", cmd, channel, value);
#endif
      status = caen170a_set(index, channel, value);
      break;
   case CMD_SET_ALL:
      index = va_arg(argptr, INT);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
#ifdef DEBUG
      printf("in caen170a cmd set all:%i -chan:%i -Val:%f ", cmd, channel, value);
#endif
      status = caen170a_set_all(index, channel, value);
      break;
   case CMD_GET:
      index = va_arg(argptr, INT);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = caen170a_get(index, channel, pvalue);
#ifdef DEBUG
      printf("in caen170a cmd get <-:%i -Chan:%i -Val:%f ", cmd, channel, *pvalue);
#endif
      break;
   case CMD_GET_ALL:
      index = va_arg(argptr, INT);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = caen170a_get_all(index, channel, pvalue);
#ifdef DEBUG
      printf("in caen170a cmd get all:%i -Chan:%i -Val:%f ", cmd, channel, *pvalue);
#endif
      break;
      /* current measurements not supported in CAEN170A */
   case CMD_GET_CURRENT:
      break;
   case CMD_GET_CURRENT_ALL:
      break;
   case CMD_SET_CURRENT_LIMIT:
      break;
   default:
      cm_msg(MERROR, "caen170a device driver", "Received unknown command %d", cmd);
      status = FE_ERR_DRIVER;
      break;
   }
   va_end(argptr);
   return status;
}
INT caen170a_assign_channel (INT direction, INT * channel, INT * frame, INT * chanframe)
Definition at line 121 of file caen170a.c.
References caen, CHANNEL_TO_FRAME, FE_SUCCESS, and FRAME_TO_CHANNEL.
Referenced by caen170a_get(), and caen170a_set().
{
   INT ch;
   ch = *channel;
   switch (direction) {
   case FRAME_TO_CHANNEL:
      printf("caen170a_assign_channel: FRAME_TO_CHANNEL not implemented\n");
      break;
   case CHANNEL_TO_FRAME:
      *frame = caen.mainframe[(ch / 64)];
      *chanframe = (ch % 64);
#ifdef DEBUG
      printf("%i ->", ch);
      printf(" %i %i ", *frame, *chanframe);
#endif
      break;
   }
   return FE_SUCCESS;
}
INT caen170a_exit (INT index)
Definition at line 115 of file caen170a.c.
References FE_SUCCESS.
Referenced by caen170a().
{
   return FE_SUCCESS;
}
INT caen170a_get (INT index, INT channel, float * pvalue)
Definition at line 226 of file caen170a.c.
References caen, caen170a_assign_channel(), cfsa(), CHANNEL_TO_FRAME, cmd, FE_ERR_ODB, FE_SUCCESS, ss_sleep(), and value.
Referenced by caen170a(), and caen170a_get_all().
{
   INT cmd, frame, fch;
   INT nlam, q;
   INT value;
   /* convert channel to frame and channel within frame */
   if (caen170a_assign_channel(CHANNEL_TO_FRAME, &channel, &frame, &fch) < 0)
      return FE_ERR_ODB;
   /* clear LAM */
   cfsa(9, caen.ext0, (unsigned long *) &cmd, &q);
   /* HAS to be there! */
   ss_sleep(400);
   /* host = 1 */
   cmd = 1;
   cfsa(16, caen.ext0, (unsigned long *) &cmd, &q);
   /* mainframe CAEN address */
   cfsa(16, caen.ext0, (unsigned long *) &frame, &q);
   /* operation 0x0000 Read Module name */
   /* operation 0x02.. Read Vset , .. channel# */
   /* operation 0x01.. Read Vmon , .. channel# */
   cmd = 0x0100 | (fch & 0xff);
   cfsa(16, caen.ext0, (unsigned long *) &cmd, &q);
   /* ship op request */
   cmd = 1;
   cfsa(17, caen.ext0, (unsigned long *) &cmd, &q);
   /* HAS to be there! */
   ss_sleep(400);
   nlam = 0;
   do {
      ss_sleep(100);
      cfsa(0, caen.ext0, (unsigned long *) &value, &q);
      nlam++;
   } while ((nlam < 10) && (q != 1));
   /* read data & decode value remove relay status (bit 15) if below error status */
   cfsa(0, caen.ext0, (unsigned long *) &value, &q);
   /* error returned :
      0xff00 : busy.
      0xff01 : unknown code or erro in the request.
      0xff02 : no channel present.
      0xff03 : Vset > HVin.
      0xff04 : HVin > 1500 ON command not enabled.
      0xff05 : Config number > 9.
      0xfffd : No data transmitted.
      0xfffe : The master ID is incorrect.
      0xffff : The address slave does not exist.
    */
   if (value < 0xff00)
      *pvalue = (float) (value & 0x7fff);
#ifdef DEBUG
   printf(" - value :0x%x - value:%f - qx:%i : nlam:%i\n", value, *pvalue, q, nlam);
#endif
   return FE_SUCCESS;
}
INT caen170a_get_all (INT index, INT channels, float * array)
Definition at line 293 of file caen170a.c.
References caen170a_get(), cm_yield(), FE_SUCCESS, i, and value.
Referenced by caen170a().
{
   float value;
   INT i;
   /* read ALL this equip channels */
   for (i = 0; i <= channels; i++) {
      caen170a_get(index, i, (float *) &value);
      array[i] = (float) value;
      cm_yield(0);              /* check for watchdog requests */
   }
   return FE_SUCCESS;
}
INT caen170a_init (HNDLE hKeyRoot, INT index, INT channels)
Definition at line 78 of file caen170a.c.
References caen, CAEN170A_STR, cdreg(), cfsa(), cm_get_experiment_database(), cm_msg, db_create_record(), db_find_key(), db_get_data(), db_get_value(), DB_SUCCESS, FE_ERR_ODB, FE_SUCCESS, hDB, MERROR, MINFO, size, status, TID_INT, and TRUE.
Referenced by caen170a().
{
   INT status, size, q;
   HNDLE hKeyFrame;
   HNDLE hDB;
   cm_get_experiment_database(&hDB, NULL);
   status = db_create_record(hDB, hKeyRoot, "", CAEN170A_STR);
   if (status != DB_SUCCESS) {
      cm_msg(MERROR, "caen170a_init", "Cannot create BCN_Mainframe\n");
      return FE_ERR_ODB;
   }
   size = sizeof(caen.branch);
   status = db_get_value(hDB, hKeyRoot, "Branch", &caen.branch, &size, TID_INT, TRUE);
   if (status != DB_SUCCESS) {
      cm_msg(MINFO, "caen170a_init",
             "Cannot find 'Branch' entry in ../Devices/HV170A database");
      return FE_ERR_ODB;
   }
   status = db_get_value(hDB, hKeyRoot, "Crate", &caen.crate, &size, TID_INT, TRUE);
   status = db_get_value(hDB, hKeyRoot, "Station", &caen.station, &size, TID_INT, TRUE);
   size = sizeof(caen.mainframe);
   status = db_find_key(hDB, hKeyRoot, "Mainframe", &hKeyFrame);
   status = db_get_data(hDB, hKeyFrame, &caen.mainframe[0], &size, TID_INT);
   /* save ext for HV slot */
   cdreg(&caen.ext0, caen.branch, caen.crate, caen.station, 0);
   cdreg(&caen.ext1, caen.branch, caen.crate, caen.station, 1);
   cfsa(24, caen.ext1, &caen.st, &q);
   cfsa(9, caen.ext1, &caen.st, &q);
   return FE_SUCCESS;
}
INT caen170a_set (INT index, INT channel, float fvalue)
Definition at line 144 of file caen170a.c.
References abs, caen, caen170a_assign_channel(), cfsa(), CHANNEL_TO_FRAME, cmd, FE_ERR_ODB, FE_SUCCESS, ss_sleep(), status, and value.
Referenced by caen170a(), and caen170a_set_all().
{
   INT cmd, frame, fch, nlam, q, status, value, svalue;
   value = (INT) abs(fvalue);
   /* convert channel to frame and channel within frame */
   if (caen170a_assign_channel(CHANNEL_TO_FRAME, &channel, &frame, &fch) < 0)
      return FE_ERR_ODB;
   /* Clear buffer */
   cfsa(9, caen.ext0, &caen.st, &q);
   /* HAS to be there! */
   ss_sleep(400);
   /* host */
   status = 1;
   cfsa(16, caen.ext0, &caen.st, &q);
   /* crate */
   cfsa(16, caen.ext0, (unsigned long *) &frame, &q);
   /* operation 0x05.. Set relay OFF , .. channel# */
   /* operation 0x04.. Set relay ON , .. channel# */
   /* operation 0x03.. write Vset, .. channel# */
   cmd = 0x0300 | (fch & 0xff);
   cfsa(16, caen.ext0, (unsigned long *) &cmd, &q);
   /* set HV */
   cfsa(16, caen.ext0, (unsigned long *) &value, &q);
   /* ship op request */
   status = 1;
   cfsa(17, caen.ext0, &caen.st, &q);
   /* HAS to be there! */
   ss_sleep(300);
   nlam = 0;
   do {
      ss_sleep(100);
      cfsa(0, caen.ext0, (unsigned long *) &svalue, &q);
      nlam++;
   } while ((nlam < 10) && (q != 1));
   /* decode value */
   /* error returned :
      0xff00 : busy.
      0xff01 : unknown code or erro in the request.
      0xff02 : no channel present.
      0xff03 : Vset > HVin.
      0xff04 : HVin > 1500 ON command not enabled.
      0xff05 : Config number > 9.
      0xfffd : No data transmitted.
      0xfffe : The master ID is incorrect.
      0xffff : The address slave does not exist.
    */
   cfsa(0, caen.ext0, (unsigned long *) &svalue, &q);
#ifdef DEBUG
   printf(" - value :0x%x - value:%i - qx:%i : nlam:%i\n", svalue, svalue, q, nlam);
#endif
   return FE_SUCCESS;
}
INT caen170a_set_all (INT index, INT channels, float value)
Definition at line 212 of file caen170a.c.
References caen170a_set(), cm_yield(), FE_SUCCESS, and i.
Referenced by caen170a().
{
   INT i;
   for (i = 0; i < channels; i++) {
      caen170a_set(index, i, value);
      cm_yield(0);              /* check for watchdog requests */
   }
   return FE_SUCCESS;
}
Variable Documentation
INT branch
Definition at line 67 of file caen170a.c.
Referenced by cam_init().
struct { ... } caen [static]
INT crate
Definition at line 68 of file caen170a.c.
INT ext0
Definition at line 71 of file caen170a.c.
INT ext1
Definition at line 72 of file caen170a.c.
INT mainframe[16]
Definition at line 70 of file caen170a.c.
unsigned long st
Definition at line 73 of file caen170a.c.
Referenced by ss_settime().
INT station
Definition at line 69 of file caen170a.c.