AlcapDAQ: CAEN/CAENDigitizer/CAENDigitizer_2.3.2/include/CAENDigitizer.h File Reference
CAEN/CAENDigitizer/CAENDigitizer_2.3.2/include/CAENDigitizer.h File Reference
CAEN - Digitizer Library.
#include "CAENDigitizerType.h"
Defines
#define DPP_DEPRECATED(func) func
Functions
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_OpenDigitizer (CAEN_DGTZ_ConnectionType LinkType, int LinkNum, int ConetNode, uint32_t VMEBaseAddress, int *handle)
Opens the Digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_CloseDigitizer (int handle)
Closes the Digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_WriteRegister (int handle, uint32_t Address, uint32_t Data)
Writes a 32-bit word in a specific address offset of the digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_ReadRegister (int handle, uint32_t Address, uint32_t *Data)
Reads a 32-bit word from a specific address offset of the digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetInfo (int handle, CAEN_DGTZ_BoardInfo_t *BoardInfo)
Retrieves the board information of the digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_Reset (int handle)
Resets the Digitizer. All internal registers and states are restored to defaults.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_ClearData (int handle)
Clears the data stored in the buffers of the Digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SendSWtrigger (int handle)
Sends a Software trigger to the Digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SWStartAcquisition (int handle)
Starts Digitizers acquisition.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SWStopAcquisition (int handle)
Stops Digitizer acquisition.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetInterruptConfig (int handle, CAEN_DGTZ_EnaDis_t state, uint8_t level, uint32_t status_id, uint16_t event_number, CAEN_DGTZ_IRQMode_t mode)
Enable/disable Interrupts and set the Interrupt level used by the Digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetInterruptConfig (int handle, CAEN_DGTZ_EnaDis_t *state, uint8_t *level, uint32_t *status_id, uint16_t *event_number, CAEN_DGTZ_IRQMode_t *mode)
Gets current Interrupt settings of the Digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_IRQWait (int handle, uint32_t timeout)
Waits for an interrupt by the Digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_VMEIRQWait (CAEN_DGTZ_ConnectionType LinkType, int LinkNum, int ConetNode, uint8_t IRQMask, uint32_t timeout, int *VMEHandle)
Waits for an interrupt from a CAEN VME Bridge.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_VMEIRQCheck (int VMEHandle, uint8_t *Mask)
Checks VME interrupt level.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_IACKCycle (int handle, int32_t *board_id)
Performs an interrupt acknowledge cycle to know the board_id of the board that raised an interrupt.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_VMEIACKCycle (int VMEHandle, uint8_t level, int32_t *board_id)
Performs a VME Interrupt Acknowledge cycle to know the board_id of the board that raised an interrupt.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDESMode (int handle, CAEN_DGTZ_EnaDis_t enable)
Sets Dual Edge Sampling (DES) mode. Valid only for digitizers that supports this acquisiton mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDESMode (int handle, CAEN_DGTZ_EnaDis_t *enable)
Gets Dual Edge Sampling (DES) mode. Valid only for digitizers that supports this acquisiton mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetRecordLength (int handle, uint32_t size,...)
Sets acquisition record length.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetRecordLength (int handle, uint32_t *size,...)
Gets current acquisition record length.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelEnableMask (int handle, uint32_t mask)
Sets channels that will be enabled into events.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelEnableMask (int handle, uint32_t *mask)
Gets current mask of enabled channels in events. If a mask bit is set, corresponding channel is currenly enabled for event readout.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupEnableMask (int handle, uint32_t mask)
Sets channels group that will be enabled into events.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupEnableMask (int handle, uint32_t *mask)
Gets current mask of enabled channel groups in events. Valid only for digitizers that supports channel groups (V1740, DT5740 for instance).
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetSWTriggerMode (int handle, CAEN_DGTZ_TriggerMode_t mode)
Sets oneof the available trigger mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetExtTriggerInputMode (int handle, CAEN_DGTZ_TriggerMode_t mode)
Sets external trigger input mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetExtTriggerInputMode (int handle, CAEN_DGTZ_TriggerMode_t *mode)
Gets current external trigger input mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetSWTriggerMode (int handle, CAEN_DGTZ_TriggerMode_t *mode)
Sets software trigger mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelSelfTrigger (int handle, CAEN_DGTZ_TriggerMode_t mode, uint32_t channelmask)
Sets channel self trigger mode according to CAEN_DGTZ_TriggerMode_t.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelSelfTrigger (int handle, uint32_t channel, CAEN_DGTZ_TriggerMode_t *mode)
Gets current channel self trigger mode setting.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupSelfTrigger (int handle, CAEN_DGTZ_TriggerMode_t mode, uint32_t groupmask)
Sets channel group self trigger mode according to mode Valid only for digitizers that supports channel groups (V1740, DT5740 for instance).
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupSelfTrigger (int handle, uint32_t group, CAEN_DGTZ_TriggerMode_t *mode)
Gets channel group self trigger mode. Valid only for digitizers that supports channel groups (V1740, DT5740 for instance).
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelGroupMask (int handle, uint32_t group, uint32_t channelmask)
Selects which channel is enabled to contribute to event among available channels of selected channel group. Valid only for digitizers that supports channel groups (V1740, DT5740 for instance).
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelGroupMask (int handle, uint32_t group, uint32_t *channelmask)
Gets current channel that are enabled to contribute to event among available channels of selected channel group. Valid only for digitizers that supports channel groups (V1740, DT5740 for instance).
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetPostTriggerSize (int handle, uint32_t percent)
Sets post trigger for next acquisitions.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetPostTriggerSize (int handle, uint32_t *percent)
Gets current post trigger length.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPPPreTriggerSize (int handle, int ch, uint32_t samples)
Sets the pre-trigger size, which is the portion of acquisition window visible before a trigger.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPPPreTriggerSize (int handle, int ch, uint32_t *samples)
Gets the pre-trigger size.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelDCOffset (int handle, uint32_t channel, uint32_t Tvalue)
Sets the DC offset for a specified channel.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelDCOffset (int handle, uint32_t channel, uint32_t *Tvalue)
Gets the DC offset for a specified channel.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupDCOffset (int handle, uint32_t group, uint32_t Tvalue)
Sets the DC offset for a specified group of channels.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupDCOffset (int handle, uint32_t group, uint32_t *Tvalue)
Gets the DC offset from a specified group of channels.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelTriggerThreshold (int handle, uint32_t channel, uint32_t Tvalue)
Sets the Trigger Threshold for a specific channel.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelTriggerThreshold (int handle, uint32_t channel, uint32_t *Tvalue)
Gets current Trigger Threshold from a specified channel.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelPulsePolarity (int handle, uint32_t channel, CAEN_DGTZ_PulsePolarity_t pol)
Set the pulse polarity for the specified channel.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelPulsePolarity (int handle, uint32_t channel, CAEN_DGTZ_PulsePolarity_t *pol)
Get the value of the pulse polarity for the specified channel.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupTriggerThreshold (int handle, uint32_t group, uint32_t Tvalue)
Sets the Trigger Threshold for a specified group of channels.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupTriggerThreshold (int handle, uint32_t group, uint32_t *Tvalue)
Gets the Trigger Threshold from a specified group of channels.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetZeroSuppressionMode (int handle, CAEN_DGTZ_ZS_Mode_t mode)
Sets Zero Suppression mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetZeroSuppressionMode (int handle, CAEN_DGTZ_ZS_Mode_t *mode)
Gets current Zero Suppression mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelZSParams (int handle, uint32_t channel, CAEN_DGTZ_ThresholdWeight_t weight, int32_t threshold, int32_t nsamp)
Sets Zero Suppression parameters for a specific channel.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelZSParams (int handle, uint32_t channel, CAEN_DGTZ_ThresholdWeight_t *weight, int32_t *threshold, int32_t *nsamp)
Gets current Zero Suppression parameters from a specified channel.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetAcquisitionMode (int handle, CAEN_DGTZ_AcqMode_t mode)
Sets digitizer acquisition mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetAcquisitionMode (int handle, CAEN_DGTZ_AcqMode_t *mode)
Gets the acquisition mode of the digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetRunSynchronizationMode (int handle, CAEN_DGTZ_RunSyncMode_t mode)
Sets the run synchronization mode of the digitizer, used to synchronize an acquisition on multiple boards.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetRunSynchronizationMode (int handle, CAEN_DGTZ_RunSyncMode_t *mode)
Gets the run synchronization mode of the digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetAnalogMonOutput (int handle, CAEN_DGTZ_AnalogMonitorOutputMode_t mode)
Sets waveform to output on Digitizer Analog Monitor Front Panel output.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetAnalogMonOutput (int handle, CAEN_DGTZ_AnalogMonitorOutputMode_t *mode)
Gets current waveform selected to drive Digitizer Analog Monitor Front Panel output.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetAnalogInspectionMonParams (int handle, uint32_t channelmask, uint32_t offset, CAEN_DGTZ_AnalogMonitorMagnify_t mf, CAEN_DGTZ_AnalogMonitorInspectorInverter_t ami)
Sets the Analog Inspection Monitor parameters for a digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetAnalogInspectionMonParams (int handle, uint32_t *channelmask, uint32_t *offset, CAEN_DGTZ_AnalogMonitorMagnify_t *mf, CAEN_DGTZ_AnalogMonitorInspectorInverter_t *ami)
Gets Analog Inspection Monitor parameters from a digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_DisableEventAlignedReadout (int handle)
Disables BERR as transfer termination signal from slave (digitizer).
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetEventPackaging (int handle, CAEN_DGTZ_EnaDis_t mode)
Enable or disable the Pack 2.5 mode of V1720/DT5720 Digitizers.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetEventPackaging (int handle, CAEN_DGTZ_EnaDis_t *mode)
get the information about the Pack 2.5 mode of V1720/DT5720 Digitizers
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetMaxNumAggregatesBLT (int handle, uint32_t numAggr)
Sets max aggregate number for each transfer DPP-PHA, DPP-PSD and DPP-CI you can use CAEN_DGTZ_SetDPPEventAggregation.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetMaxNumEventsBLT (int handle, uint32_t numEvents)
Sets max event number for each transfer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetMaxNumAggregatesBLT (int handle, uint32_t *numAggr)
Gets the max number of aggregates of each block transfer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetMaxNumEventsBLT (int handle, uint32_t *numEvents)
Gets the max number of events of each block transfer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_MallocReadoutBuffer (int handle, char **buffer, uint32_t *size)
Allocates memory buffer to hold data received from digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_ReadData (int handle, CAEN_DGTZ_ReadMode_t mode, char *buffer, uint32_t *bufferSize)
Reads data (events) from the digitizer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeReadoutBuffer (char **buffer)
Frees memory allocated by the CAEN_DGTZ_MallocReadoutBuffer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetNumEvents (int handle, char *buffer, uint32_t buffsize, uint32_t *numEvents)
Gets current number of event stored in the acquisition buffer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetEventInfo (int handle, char *buffer, uint32_t buffsize, int32_t numEvent, CAEN_DGTZ_EventInfo_t *eventInfo, char **EventPtr)
Retrieves the information associated with a specified event.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_DecodeEvent (int handle, char *evtPtr, void **Evt)
Decodes a specified event stored in the acquisition buffer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeEvent (int handle, void **Evt)
Releases the event returned by the CAEN_DGTZ_DecodeEvent.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPPEvents (int handle, char *buffer, uint32_t buffsize, void **events, uint32_t *numEventsArray)
Decodes and returns all the DPP events stored in the acquisition buffers.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_MallocDPPEvents (int handle, void **events, uint32_t *allocatedSize)
Allocates the event buffer matrix which is handled by CAEN_DGTZ_GetDPPEvents. The matrix has one event array per channel and must be declared as a MAX_CH-sized array of pointers.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeDPPEvents (int handle, void **events)
Deallocates the event buffer matrix.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_MallocDPPWaveforms (int handle, void **waveforms, uint32_t *allocatedSize)
Allocates the waveform buffer, which is used by CAEN_DGTZ_DecodeDPPWaveforms.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeDPPWaveforms (int handle, void *Waveforms)
Deallocates the waveform buffer.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_DecodeDPPWaveforms (int handle, void *event, void *waveforms)
Decodes the waveforms contained inside an event.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetNumEventsPerAggregate (int handle, uint32_t numEvents,...)
Sets the number of events that each aggregate will contain.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetNumEventsPerAggregate (int handle, uint32_t *numEvents,...)
Gets the number of events that each aggregate will contain.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPPEventAggregation (int handle, int threshold, int maxsize)
Set event aggregation parameters.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPPParameters (int handle, uint32_t channelMask, void *params)
Set DPP configuration parameters for DPP-PHA, DPP-PSD or DPP-CI.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPPAcquisitionMode (int handle, CAEN_DGTZ_DPP_AcqMode_t mode, CAEN_DGTZ_DPP_SaveParam_t param)
Set the DPP acquisition mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPPAcquisitionMode (int handle, CAEN_DGTZ_DPP_AcqMode_t *mode, CAEN_DGTZ_DPP_SaveParam_t *param)
Get the information about the DPP acquisition mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPPTriggerMode (int handle, CAEN_DGTZ_DPP_TriggerMode_t mode)
Sets the DPP Trigger mode (DPP-PSD and DPP-CI only).
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPPTriggerMode (int handle, CAEN_DGTZ_DPP_TriggerMode_t *mode)
Gets the current DPP Trigger mode (DPP-PSD and DPP-CI only).
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPP_PHA_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t mode, CAEN_DGTZ_DPP_PHA_VirtualProbe1_t vp1, CAEN_DGTZ_DPP_PHA_VirtualProbe2_t vp2, CAEN_DGTZ_DPP_PHA_DigitalProbe_t dp)
Set the information about the output signal of the DPP-PHA acquisition mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPP_PHA_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t *mode, CAEN_DGTZ_DPP_PHA_VirtualProbe1_t *vp1, CAEN_DGTZ_DPP_PHA_VirtualProbe2_t *vp2, CAEN_DGTZ_DPP_PHA_DigitalProbe_t *dp)
Get the information about the output signal of the DPP-PHA acquisition mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPP_PSD_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t mode, CAEN_DGTZ_DPP_PSD_VirtualProbe_t vp, CAEN_DGTZ_DPP_PSD_DigitalProbe1_t dp1, CAEN_DGTZ_DPP_PSD_DigitalProbe2_t dp2)
Set the information about the output signal of the DPP-PSD acquisition mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPP_PSD_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t *mode, CAEN_DGTZ_DPP_PSD_VirtualProbe_t *vp, CAEN_DGTZ_DPP_PSD_DigitalProbe1_t *dp1, CAEN_DGTZ_DPP_PSD_DigitalProbe2_t *dp2)
Get the information about the output signal of the DPP-PSD acquisition mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPP_CI_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t mode, CAEN_DGTZ_DPP_CI_VirtualProbe_t vp, CAEN_DGTZ_DPP_CI_DigitalProbe1_t dp1, CAEN_DGTZ_DPP_CI_DigitalProbe2_t dp2)
Set the information about the output signal of the DPP-CI acquisition mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPP_CI_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t *mode, CAEN_DGTZ_DPP_CI_VirtualProbe_t *vp, CAEN_DGTZ_DPP_CI_DigitalProbe1_t *dp1, CAEN_DGTZ_DPP_CI_DigitalProbe2_t *dp2)
Get the information about the output signal of the DPP-CI acquisition mode.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_AllocateEvent (int handle, void **Evt)
Allocate the memory for the event.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetIOLevel (int handle, CAEN_DGTZ_IOLevel_t level)
Sets the IO Level.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetIOLevel (int handle, CAEN_DGTZ_IOLevel_t *level)
Gets the IO Level.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetTriggerPolarity (int handle, uint32_t channel, CAEN_DGTZ_TriggerPolarity_t Polarity)
Sets the trigger polarity of a specified channel.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetTriggerPolarity (int handle, uint32_t channel, CAEN_DGTZ_TriggerPolarity_t *Polarity)
Gets the trigger polarity of a specified channel.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_RearmInterrupt (int handle)
Rearm the Interrupt.
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDRS4SamplingFrequency (int handle, CAEN_DGTZ_DRS4Frequency_t frequency)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDRS4SamplingFrequency (int handle, CAEN_DGTZ_DRS4Frequency_t *frequency)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetOutputSignalMode (int handle, CAEN_DGTZ_OutputSignalMode_t mode)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetOutputSignalMode (int handle, CAEN_DGTZ_OutputSignalMode_t *mode)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupFastTriggerThreshold (int handle, uint32_t group, uint32_t Tvalue)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupFastTriggerThreshold (int handle, uint32_t group, uint32_t *Tvalue)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupFastTriggerDCOffset (int handle, uint32_t group, uint32_t DCvalue)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupFastTriggerDCOffset (int handle, uint32_t group, uint32_t *DCvalue)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetFastTriggerDigitizing (int handle, CAEN_DGTZ_EnaDis_t enable)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetFastTriggerDigitizing (int handle, CAEN_DGTZ_EnaDis_t *enable)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetFastTriggerMode (int handle, CAEN_DGTZ_TriggerMode_t mode)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetFastTriggerMode (int handle, CAEN_DGTZ_TriggerMode_t *mode)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_LoadDRS4CorrectionData (int handle, CAEN_DGTZ_DRS4Frequency_t frequency)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_EnableDRS4Correction (int handle)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_DisableDRS4Correction (int handle)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_DecodeZLEWaveforms (int handle, void *event, void *waveforms)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeZLEWaveforms (int handle, void *waveforms)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_MallocZLEWaveforms (int handle, void **waveforms, uint32_t *allocatedSize)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeZLEEvents (int handle, void **events)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_MallocZLEEvents (int handle, void **events, uint32_t *allocatedSize)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetZLEEvents (int handle, char *buffer, uint32_t buffsize, void **events, uint32_t *numEventsArray)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetZLEParameters (int handle, uint32_t channelMask, void *params)
Detailed Description
CAEN - Digitizer Library.
Note:
TERMS OF USE: This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. The user relies on the software, documentation and results solely at his own risk.
Author:
Alberto Lucchesi, Giovanni Bianchi (support.computing@caen.it)
This library provide functions, structures and definitions for the CAEN digitizer family
Definition in file CAENDigitizer.h.
Define Documentation
#define DPP_DEPRECATED (func) func
Definition at line 41 of file CAENDigitizer.h.
Function Documentation
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_AllocateEvent (int handle, void ** Evt)
Allocate the memory for the event.
Parameters:
[IN] handle : digitizer handle
[IN] Evt: the reference to the Event pointer
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_ClearData (int handle)
Clears the data stored in the buffers of the Digitizer.
Parameters:
[IN] handle: digitizer handle.
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_pre_bor(), main(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_CloseDigitizer (int handle)
Closes the Digitizer.
Parameters:
[IN] handle: digitizer handle to be closed
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_exit(), main(), and v1724_exit().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_DecodeDPPWaveforms (int handle, void * event, void * waveforms)
Decodes the waveforms contained inside an event.
Note:
Part of the new readout API
Parameters:
[IN] handle : digitizer handle
[IN] events : pointer to the event
[OUT] waveforms : pointer to the (preallocated) waveform list
Returns:
0 = Success; negative numbers are error codes
Referenced by main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_DecodeEvent (int handle, char * evtPtr, void ** Evt)
Decodes a specified event stored in the acquisition buffer.
Deprecated:
On DPP-PHA, DPP-PSD and DPP-CI use the new readout API
Parameters:
[IN] handle : digitizer handle
[IN] EventPtr : pointer to the requested event in the acquisition buffer
[OUT] Evt : event structure with the requested event data
Returns:
0 = Success; negative numbers are error codes
Referenced by main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_DecodeZLEWaveforms (int handle, void * event, void * waveforms)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_DisableDRS4Correction (int handle)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_DisableEventAlignedReadout (int handle)
Disables BERR as transfer termination signal from slave (digitizer).
Parameters:
[IN] handle : digitizer handle
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_EnableDRS4Correction (int handle)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeDPPEvents (int handle, void ** events)
Deallocates the event buffer matrix.
Note:
Part of the new readout API
Parameters:
[IN] handle : digitizer handle
[IN] events : pointer to the event buffer
Returns:
0 = Success; negative numbers are error codes
Referenced by main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeDPPWaveforms (int handle, void * Waveforms)
Deallocates the waveform buffer.
Note:
Part of the new readout API
Parameters:
[IN] handle : digitizer handle
[IN] waveforms : pointer to the waveform buffer
Returns:
0 = Success; negative numbers are error codes
Referenced by main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeEvent (int handle, void ** Evt)
Releases the event returned by the CAEN_DGTZ_DecodeEvent.
Deprecated:
On DPP-PHA, DPP-PSD and DPP-CI use the new readout API
Parameters:
[IN] handle : digitizer handle
[IN] Evt : event structure that store the decoded event.
Returns:
0 = Success; negative numbers are error codes
Referenced by main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeReadoutBuffer (char ** buffer)
Frees memory allocated by the CAEN_DGTZ_MallocReadoutBuffer.
Note:
Grandfathered into the new readout API
Parameters:
[IN] handle : digitizer handle
[IN] buffer : address to the acquisition buffer returned by CAEN_DGTZ_MallocReadoutBuffer
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_eor(), main(), and v1724_exit().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeZLEEvents (int handle, void ** events)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_FreeZLEWaveforms (int handle, void * waveforms)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetAcquisitionMode (int handle, CAEN_DGTZ_AcqMode_t * mode)
Gets the acquisition mode of the digitizer.
Parameters:
[IN] handle : digitizer handle
[OUT] mode : the acquisition mode set
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetAnalogInspectionMonParams (int handle, uint32_t * channelmask, uint32_t * offset, CAEN_DGTZ_AnalogMonitorMagnify_t * mf, CAEN_DGTZ_AnalogMonitorInspectorInverter_t * ami)
Gets Analog Inspection Monitor parameters from a digitizer.
Parameters:
[IN] handle : digitizer handle
[OUT] channelmask : channel enable mask for Analog Inspection
[OUT] offset : Analog Inspection Offset
[OUT] mf : Analog Inspection Multiply Factor
[OUT] ami : Analog Inspection Invert
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetAnalogMonOutput (int handle, CAEN_DGTZ_AnalogMonitorOutputMode_t * mode)
Gets current waveform selected to drive Digitizer Analog Monitor Front Panel output.
Parameters:
[IN] handle : digitizer handle
[OUT] mode : Analog Monitor output mode
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelDCOffset (int handle, uint32_t channel, uint32_t * Tvalue)
Gets the DC offset for a specified channel.
Parameters:
[IN] handle : digitizer handle.
[IN] channel : the channel which takes the information.
[OUT] Tvalue : the DC offset set. Tvalue is expressed in channel DAC (Digital to Analog Converter) steps. Please refer to digitizer documentation for possible value range.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelEnableMask (int handle, uint32_t * mask)
Gets current mask of enabled channels in events. If a mask bit is set, corresponding channel is currenly enabled for event readout.
Parameters:
[IN] handle : digitizer handle.
[OUT] mask : enabled channels mask.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelGroupMask (int handle, uint32_t group, uint32_t * channelmask)
Gets current channel that are enabled to contribute to event among available channels of selected channel group. Valid only for digitizers that supports channel groups (V1740, DT5740 for instance).
Parameters:
[IN] handle : digitizer handle.
[IN] group : the group of channels.
[OUT] channelmask : mask of channels to enable in event readout
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelPulsePolarity (int handle, uint32_t channel, CAEN_DGTZ_PulsePolarity_t * pol)
Get the value of the pulse polarity for the specified channel.
Parameters:
[IN] handle : digitizer handle.
[IN] channel : channel to get information from
[OUT] pol : the value of the pulse polarity
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelSelfTrigger (int handle, uint32_t channel, CAEN_DGTZ_TriggerMode_t * mode)
Gets current channel self trigger mode setting.
Parameters:
[IN] handle : digitizer handle
[IN] channel : select channel to get the self trigger mode
[OUT] mode : current trigger mode for selected channel
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelTriggerThreshold (int handle, uint32_t channel, uint32_t * Tvalue)
Gets current Trigger Threshold from a specified channel.
Parameters:
[IN] handle : digitizer handle.
[IN] channel : the channel which takes the information.
[OUT] Tvalue : the threshold value set
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetChannelZSParams (int handle, uint32_t channel, CAEN_DGTZ_ThresholdWeight_t * weight, int32_t * threshold, int32_t * nsamp)
Gets current Zero Suppression parameters from a specified channel.
Parameters:
[IN] handle : digitizer handle
[IN] channel : target channel
[OUT] weight : Zero Suppression Weight
[OUT] threshold : Zero Suppression Threshold
[OUT] nsamp : Number of samples to store before/after threshold crossing
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDESMode (int handle, CAEN_DGTZ_EnaDis_t * enable)
Gets Dual Edge Sampling (DES) mode. Valid only for digitizers that supports this acquisiton mode.
Parameters:
[IN] handle : digitizer handle
[OUT] enable : shows current DES mode status (enabled/disabled)
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPP_CI_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t * mode, CAEN_DGTZ_DPP_CI_VirtualProbe_t * vp, CAEN_DGTZ_DPP_CI_DigitalProbe1_t * dp1, CAEN_DGTZ_DPP_CI_DigitalProbe2_t * dp2)
Get the information about the output signal of the DPP-CI acquisition mode.
Parameters:
[IN] handle : digitizer handle
[OUT] mode: The Virtual Probe mode
[OUT] vp: The Virtual Probe mode
[OUT] dp1: The Digital Probe1 mode
[OUT] dp2: The Digital Probe2 mode
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPP_PHA_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t * mode, CAEN_DGTZ_DPP_PHA_VirtualProbe1_t * vp1, CAEN_DGTZ_DPP_PHA_VirtualProbe2_t * vp2, CAEN_DGTZ_DPP_PHA_DigitalProbe_t * dp)
Get the information about the output signal of the DPP-PHA acquisition mode.
Parameters:
[IN] handle : digitizer handle
[OUT] mode: The Virtual Probe mode
[OUT] vp1: The Virtual Probe1 mode
[OUT] vp2: The Virtual Probe2 mode
[OUT] dp: The Digital Probe mode
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPP_PSD_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t * mode, CAEN_DGTZ_DPP_PSD_VirtualProbe_t * vp, CAEN_DGTZ_DPP_PSD_DigitalProbe1_t * dp1, CAEN_DGTZ_DPP_PSD_DigitalProbe2_t * dp2)
Get the information about the output signal of the DPP-PSD acquisition mode.
Parameters:
[IN] handle : digitizer handle
[OUT] mode: The Virtual Probe mode
[OUT] vp: The Virtual Probe mode
[OUT] dp1: The Digital Probe1 mode
[OUT] dp2: The Digital Probe2 mode
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPPAcquisitionMode (int handle, CAEN_DGTZ_DPP_AcqMode_t * mode, CAEN_DGTZ_DPP_SaveParam_t * param)
Get the information about the DPP acquisition mode.
Parameters:
[IN] handle : digitizer handle
[OUT] mode: The DPP acquisition mode
[OUT] param: The acquisition data to retrieve in acquisition
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPPEvents (int handle, char * buffer, uint32_t buffsize, void ** events, uint32_t * numEventsArray)
Decodes and returns all the DPP events stored in the acquisition buffers.
Note:
Part of the new readout API
Parameters:
[IN] handle : digitizer handle
[IN] buffer : address of the acquisition buffer
[IN] buffsize : acquisition buffer size (in samples)
[OUT] events : pointer to the event list (allocated via MallocDPPEvents)
[OUT] numEventsArray : pointer to an array of int which will contain the number of events found per channel
Returns:
0 = Success; negative numbers are error codes
Referenced by main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPPPreTriggerSize (int handle, int ch, uint32_t * samples)
Gets the pre-trigger size.
Parameters:
[IN] handle : digitizer handle
[IN] ch : the channel to get the pre-trigger of
[OUT] sample : the pre-trigger size, in samples
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDPPTriggerMode (int handle, CAEN_DGTZ_DPP_TriggerMode_t * mode)
Gets the current DPP Trigger mode (DPP-PSD and DPP-CI only).
Parameters:
[IN] handle : digitizer handle
[OUT] mode: the current trigger mode
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetDRS4SamplingFrequency (int handle, CAEN_DGTZ_DRS4Frequency_t * frequency)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetEventInfo (int handle, char * buffer, uint32_t buffsize, int32_t numEvent, CAEN_DGTZ_EventInfo_t * eventInfo, char ** EventPtr)
Retrieves the information associated with a specified event.
Deprecated:
On DPP-PHA, DPP-PSD and DPP-CI use the new readout API
Parameters:
[IN] handle : digitizer handle
[IN] buffer : Address of the acquisition buffer
[IN] bufferSize : acquisition buffer size (in samples)
[IN] numEvents : Number of events stored in the acquisition buffer
[OUT] eventInfo : Event Info structure containing the information about the specified event
[OUT] EventPtr : Pointer to the requested event in the acquisition buffer
Returns:
0 = Success; negative numbers are error codes
Referenced by main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetEventPackaging (int handle, CAEN_DGTZ_EnaDis_t * mode)
get the information about the Pack 2.5 mode of V1720/DT5720 Digitizers
Parameters:
[IN] handle : digitizer handle
[OUT] mode: Enable/Disable the Pack 2,5 mode
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetExtTriggerInputMode (int handle, CAEN_DGTZ_TriggerMode_t * mode)
Gets current external trigger input mode.
Parameters:
[IN] handle : digitizer handle.
[OUT] mode : extrnal input trigger mode.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetFastTriggerDigitizing (int handle, CAEN_DGTZ_EnaDis_t * enable)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetFastTriggerMode (int handle, CAEN_DGTZ_TriggerMode_t * mode)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupDCOffset (int handle, uint32_t group, uint32_t * Tvalue)
Gets the DC offset from a specified group of channels.
Parameters:
[IN] handle : digitizer handle.
[IN] group : the group of channels which takes the information.
[OUT] Tvalue : the DC offset set Tvalue is expressed in channel DAC (Digital to Analog Converter) steps. Please refer to digitizer documentation for possible value range.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupEnableMask (int handle, uint32_t * mask)
Gets current mask of enabled channel groups in events. Valid only for digitizers that supports channel groups (V1740, DT5740 for instance).
Parameters:
[IN] handle : digitizer handle.
[OUT] mask : current channels group mask.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupFastTriggerDCOffset (int handle, uint32_t group, uint32_t * DCvalue)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupFastTriggerThreshold (int handle, uint32_t group, uint32_t * Tvalue)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupSelfTrigger (int handle, uint32_t group, CAEN_DGTZ_TriggerMode_t * mode)
Gets channel group self trigger mode. Valid only for digitizers that supports channel groups (V1740, DT5740 for instance).
Parameters:
[IN] handle : digitizer handle
[IN] group : the group of channels to get the trigger information
[OUT] mode : the mode of the trigger
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetGroupTriggerThreshold (int handle, uint32_t group, uint32_t * Tvalue)
Gets the Trigger Threshold from a specified group of channels.
Parameters:
[IN] handle : digitizer handle.
[IN] group : the group of channels which takes the information.
[OUT] Tvalue : the threshold value to set.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetInfo (int handle, CAEN_DGTZ_BoardInfo_t * BoardInfo)
Retrieves the board information of the digitizer.
Parameters:
[IN] handle : the digitizer handle
[OUT] BoardInfo : the CAEN_DGTZ_BoardInfo_t with the board information retrieved from the device
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_init(), main(), and v1724_init().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetInterruptConfig (int handle, CAEN_DGTZ_EnaDis_t * state, uint8_t * level, uint32_t * status_id, uint16_t * event_number, CAEN_DGTZ_IRQMode_t * mode)
Gets current Interrupt settings of the Digitizer.
Parameters:
[IN] handle : digitizer handle.
[OUT] state : interrupts state [CAEN_DGTZ_ENABLE|CAEN_DGTZ_DISABLE]
[OUT] level : current VME IRQ Level of the Digitizer
[OUT] status_id : current VME status_id of the the Digitizer
[OUT] event_number: number of event required to raise an interrupt
[OUT] mode : interrupt mode [CAEN_DGTZ_IRQ_MODE_RORA|CAEN_DGTZ_IRQ_MODE_ROAK]
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetIOLevel (int handle, CAEN_DGTZ_IOLevel_t * level)
Gets the IO Level.
Parameters:
[IN] handle : digitizer handle
[OUT] level : The IO level of the digitizer
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetMaxNumAggregatesBLT (int handle, uint32_t * numAggr)
Gets the max number of aggregates of each block transfer.
Parameters:
[IN] handle : digitizer handle
[OUT] numEvents : the number of aggregates set.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetMaxNumEventsBLT (int handle, uint32_t * numEvents)
Gets the max number of events of each block transfer.
Deprecated:
On DPP-PHA, DPP-PSD and DPP-CI use CAEN_DGTZ_SetDPPEventAggregation
Parameters:
[IN] handle : digitizer handle
[OUT] numEvents : the number of events set.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetNumEvents (int handle, char * buffer, uint32_t buffsize, uint32_t * numEvents)
Gets current number of event stored in the acquisition buffer.
Deprecated:
On DPP-PHA, DPP-PSD and DPP-CI use the new readout API
Parameters:
[IN] handle : digitizer handle
[IN] buffer : Address to the acquisition buffer
[IN] bufferSize : Size of the data stored in the acquisition buffer
[OUT] numEvents : Number of events stored in the acquisition buffer
Returns:
0 = Success; negative numbers are error codes
Referenced by main(), and v1724_readout().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetNumEventsPerAggregate (int handle, uint32_t * numEvents, ...)
Gets the number of events that each aggregate will contain.
Deprecated:
Parameters:
[IN] handle : digitizer handle
[OUT] numEvents : number of events per aggregate
[IN] channel : optional parameter in the form of an int to specify the channel (required for DPP-PSD and DPP-CI, ignored by DPP-PHA)
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetOutputSignalMode (int handle, CAEN_DGTZ_OutputSignalMode_t * mode)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetPostTriggerSize (int handle, uint32_t * percent)
Gets current post trigger length.
Parameters:
[IN] handle : digitizer handle
[IN] percent : the percent of the record
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetRecordLength (int handle, uint32_t * size, ...)
Gets current acquisition record length.
Parameters:
[IN] handle : digitizer handle
[OUT] size : the size of the record (in samples)
[IN] channel : int specifying the channel to get the record length for. DPP-PSD and DPP-CI require this parameter, DPP-PHA ignores it
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetRunSynchronizationMode (int handle, CAEN_DGTZ_RunSyncMode_t * mode)
Gets the run synchronization mode of the digitizer.
Parameters:
[IN] handle : digitizer handle
[OUT] mode : the current run synchronization mode
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetSWTriggerMode (int handle, CAEN_DGTZ_TriggerMode_t * mode)
Sets software trigger mode.
Parameters:
[IN] handle : digitizer handle
[OUT] mode : trigger mode
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetTriggerPolarity (int handle, uint32_t channel, CAEN_DGTZ_TriggerPolarity_t * Polarity)
Gets the trigger polarity of a specified channel.
Parameters:
[IN] handle : digitizer handle
[IN] channel : select channel to get the trigger polarity
[OUT] Polarity : The polarity of the specified channel
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetZeroSuppressionMode (int handle, CAEN_DGTZ_ZS_Mode_t * mode)
Gets current Zero Suppression mode.
Parameters:
[IN] handle : digitizer handle
[OUT] mode : Zero Suppression mode
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_GetZLEEvents (int handle, char * buffer, uint32_t buffsize, void ** events, uint32_t * numEventsArray)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_IACKCycle (int handle, int32_t * board_id)
Performs an interrupt acknowledge cycle to know the board_id of the board that raised an interrupt.
Parameters:
[IN] handle : digitizer handle.
[OUT] board_id : board id of the Digitizer that raised the interrupt.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_IRQWait (int handle, uint32_t timeout)
Waits for an interrupt by the Digitizer.
Parameters:
[IN] handle : digitizer handle
[IN] timeout : timeout (in milliseconds)
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_LoadDRS4CorrectionData (int handle, CAEN_DGTZ_DRS4Frequency_t frequency)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_MallocDPPEvents (int handle, void ** events, uint32_t * allocatedSize)
Allocates the event buffer matrix which is handled by CAEN_DGTZ_GetDPPEvents. The matrix has one event array per channel and must be declared as a MAX_CH-sized array of pointers.
Note:
Part of the new readout API
Parameters:
[IN] handle : digitizer handle
[OUT] events : pointer to the event matrix, which shall be of type:
CAEN_DGTZ_DPP_PHA_Event_t, for DPP-PHA,
CAEN_DGTZ_DPP_PSD_Event_t, for DPP-PSD
CAEN_DGTZ_DPP_CI_Event_t, for DPP-CI
[OUT] allocatedSize : size in bytes of the event list
Returns:
0 = Success; negative numbers are error codes
Referenced by main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_MallocDPPWaveforms (int handle, void ** waveforms, uint32_t * allocatedSize)
Allocates the waveform buffer, which is used by CAEN_DGTZ_DecodeDPPWaveforms.
Note:
Part of the new readout API
Parameters:
[IN] handle : digitizer handle
[OUT] waveforms : pointer to the waveform buffer, which shall be of type:
CAEN_DGTZ_DPP_PHA_Waveforms_t, for DPP-PHA
CAEN_DGTZ_DPP_PSD_Waveforms_t, for DPP-PSD
CAEN_DGTZ_DPP_CI_Waveforms_t, for DPP-CI
[OUT] allocatedSize : size in bytes of the waveform buffer
Returns:
0 = Success; negative numbers are error codes
Referenced by main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_MallocReadoutBuffer (int handle, char ** buffer, uint32_t * size)
Allocates memory buffer to hold data received from digitizer.
Note:
Grandfathered into the new readout API
Parameters:
[IN] handle : digitizer handle
[OUT] buffer : the address of the buffer pointer (WARNING: the *buffer MUST be initialized to NULL)
[OUT] size : the size in byte of the buffer allocated
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_pre_bor(), main(), and v1724_init().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_MallocZLEEvents (int handle, void ** events, uint32_t * allocatedSize)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_MallocZLEWaveforms (int handle, void ** waveforms, uint32_t * allocatedSize)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_OpenDigitizer (CAEN_DGTZ_ConnectionType LinkType, int LinkNum, int ConetNode, uint32_t VMEBaseAddress, int * handle)
Opens the Digitizer.
Parameters:
[IN] LinkType : The link used by the device
[IN] LinkNum:
when using CONET, it is the optical link number to be used
when using USB, it is the USB device number to be used
[IN] ConetNode :
for CONET identify which device in the daisy-chain is addressed
for USB must be 0.
[IN] VMEBaseAddress: The VME base address of the board in case you want to access a board through VME bus, 0 otherwise.
[OUT] handle : device handler
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_init(), main(), and v1724_init().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_ReadData (int handle, CAEN_DGTZ_ReadMode_t mode, char * buffer, uint32_t * bufferSize)
Reads data (events) from the digitizer.
Note:
Grandfathered into the new readout API
Parameters:
[IN] handle : digitizer handle
[OUT] buffer : address of the buffer that will store data (acquisition buffer)
[OUT] bufferSize : the size of the data stored in the buffer
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_readout(), main(), and v1724_readout().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_ReadRegister (int handle, uint32_t Address, uint32_t * Data)
Reads a 32-bit word from a specific address offset of the digitizer.
Parameters:
[IN] handle : the digitizer handle
[IN] Address : the register address offset
[IN] Data : the 32-bit data read from the digitizer
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), main(), v1724_init(), v1724_pre_bor(), and v1724_readout().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_RearmInterrupt (int handle)
Rearm the Interrupt.
Parameters:
[IN] handle : digitizer handle
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_Reset (int handle)
Resets the Digitizer. All internal registers and states are restored to defaults.
Parameters:
[IN] handle: digitizer handle to be reset
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_init(), main(), ProgramDigitizer(), v1724_init(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SendSWtrigger (int handle)
Sends a Software trigger to the Digitizer.
Parameters:
[IN] handle: digitizer handle.
Returns:
0 = Success; negative numbers are error codes
Referenced by main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetAcquisitionMode (int handle, CAEN_DGTZ_AcqMode_t mode)
Sets digitizer acquisition mode.
Parameters:
[IN] handle : digitizer handle
[IN] mode : acquisition mode
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_pre_bor(), dt5720_update_digitizer(), main(), ProgramDigitizer(), and v1724_pre_bor().
CAEN_DGTZ_SetAnalogInspectionMonParams (int handle, uint32_t channelmask, uint32_t offset, CAEN_DGTZ_AnalogMonitorMagnify_t mf, CAEN_DGTZ_AnalogMonitorInspectorInverter_t ami)
Sets the Analog Inspection Monitor parameters for a digitizer.
Parameters:
[IN] handle : digitizer handle
[IN] channelmask : channel enable mask for Analog Inspection
[IN] offset : Analog Inspection Offset
[IN] mf : Analog Inspection Multiply Factor
[IN] ami : Analog Inspection Invert
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetAnalogMonOutput (int handle, CAEN_DGTZ_AnalogMonitorOutputMode_t mode)
Sets waveform to output on Digitizer Analog Monitor Front Panel output.
Parameters:
[IN] handle : digitizer handle.
[IN] mode : Analog Monitor mode.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelDCOffset (int handle, uint32_t channel, uint32_t Tvalue)
Sets the DC offset for a specified channel.
Parameters:
[IN] handle : digitizer handle
[IN] channel : the channel to set
[IN] Tvalue : the DC offset to set. Tvalue is expressed in channel DAC (Digital to Analog Converter) steps. Please refer to digitizer documentation for possible value range.
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), main(), ProgramDigitizer(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelEnableMask (int handle, uint32_t mask)
Sets channels that will be enabled into events.
Parameters:
[IN] handle : digitizer handle.
[IN] mask : enabled channels mask.
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), main(), ProgramDigitizer(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelGroupMask (int handle, uint32_t group, uint32_t channelmask)
Selects which channel is enabled to contribute to event among available channels of selected channel group. Valid only for digitizers that supports channel groups (V1740, DT5740 for instance).
Parameters:
[IN] handle : digitizer handle.
[IN] group : channel group.
[IN] channelmask : mask of channels to enable in event readout
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelPulsePolarity (int handle, uint32_t channel, CAEN_DGTZ_PulsePolarity_t pol)
Set the pulse polarity for the specified channel.
Parameters:
[IN] handle : digitizer handle.
[IN] channel : channel to set.
[IN] pol : the value of the pulse polarity
Returns:
0 = Success; negative numbers are error codes
Referenced by main(), ProgramDigitizer(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelSelfTrigger (int handle, CAEN_DGTZ_TriggerMode_t mode, uint32_t channelmask)
Sets channel self trigger mode according to CAEN_DGTZ_TriggerMode_t.
Parameters:
[IN] handle : digitizer handle
[IN] mode : self trigger mode
[IN] channelmask : channel mask to select affected channels.
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), main(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelTriggerThreshold (int handle, uint32_t channel, uint32_t Tvalue)
Sets the Trigger Threshold for a specific channel.
Parameters:
[IN] handle : digitizer handle
[IN] channel : channel to set
[IN] Tvalue : threshold value to set
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), main(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetChannelZSParams (int handle, uint32_t channel, CAEN_DGTZ_ThresholdWeight_t weight, int32_t threshold, int32_t nsamp)
Sets Zero Suppression parameters for a specific channel.
Parameters:
[IN] handle : digitizer handle
[IN] channel : target channel
[IN] weight : Zero Suppression Weight
[IN] threshold : Zero Suppression Threshold
[IN] nsamp : Number of samples to store before/after threshold crossing
Returns:
0 = Success; negative numbers are error codes
Referenced by v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDESMode (int handle, CAEN_DGTZ_EnaDis_t enable)
Sets Dual Edge Sampling (DES) mode. Valid only for digitizers that supports this acquisiton mode.
Parameters:
[IN] handle : digitizer handle
[IN] enable : Enable/Disable Dual Edge Sampling mode
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPP_CI_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t mode, CAEN_DGTZ_DPP_CI_VirtualProbe_t vp, CAEN_DGTZ_DPP_CI_DigitalProbe1_t dp1, CAEN_DGTZ_DPP_CI_DigitalProbe2_t dp2)
Set the information about the output signal of the DPP-CI acquisition mode.
Parameters:
[IN] handle : digitizer handle
[IN] mode: The Virtual Probe mode
[IN] vp: The Virtual Probe mode
[IN] dp1: The Digital Probe1 mode
[IN] dp2: The Digital Probe2 mode
Returns:
0 = Success; negative numbers are error codes
Referenced by ProgramDigitizer().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPP_PHA_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t mode, CAEN_DGTZ_DPP_PHA_VirtualProbe1_t vp1, CAEN_DGTZ_DPP_PHA_VirtualProbe2_t vp2, CAEN_DGTZ_DPP_PHA_DigitalProbe_t dp)
Set the information about the output signal of the DPP-PHA acquisition mode.
Parameters:
[IN] handle : digitizer handle
[IN] mode: The Virtual Probe mode
[IN] vp1: The Virtual Probe1 mode
[IN] vp2: The Virtual Probe2 mode
[IN] dp: The Digital Probe mode
Returns:
0 = Success; negative numbers are error codes
Referenced by ProgramDigitizer().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPP_PSD_VirtualProbe (int handle, CAEN_DGTZ_DPP_VirtualProbe_t mode, CAEN_DGTZ_DPP_PSD_VirtualProbe_t vp, CAEN_DGTZ_DPP_PSD_DigitalProbe1_t dp1, CAEN_DGTZ_DPP_PSD_DigitalProbe2_t dp2)
Set the information about the output signal of the DPP-PSD acquisition mode.
Parameters:
[IN] handle : digitizer handle
[IN] mode: The Virtual Probe mode
[IN] vp: The Virtual Probe mode NOTE: ignored for x751, VirtualProbes are always Input and Baseline
[IN] dp1: The Digital Probe1 mode
[IN] dp2: The Digital Probe2 mode
Returns:
0 = Success; negative numbers are error codes
Referenced by ProgramDigitizer().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPPAcquisitionMode (int handle, CAEN_DGTZ_DPP_AcqMode_t mode, CAEN_DGTZ_DPP_SaveParam_t param)
Set the DPP acquisition mode.
Parameters:
[IN] handle : digitizer handle
[IN] mode: The DPP acquisition mode
[IN] param: The acquisition data to retrieve in acquisition
Returns:
0 = Success; negative numbers are error codes
Referenced by ProgramDigitizer().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPPEventAggregation (int handle, int threshold, int maxsize)
Set event aggregation parameters.
Note:
Only for DPP-PHA, DPP-PSD and DPP-CI
Parameters:
[IN] handle : digitizer handle
[IN] threshold : Specifies how many events to let accumulate in the board memory before they are rendered available for readout. A low number maximizes responsiveness, since data are read as soon as they are stored in memory, while a high number maximizes efficiency, since fewer transfers are made. Supplying 0 will let the library choose the best value depending on acquisition mode and other parameters.
[IN] maxsize : Specifies the maximum size in bytes of the event buffer on the PC side. This parameter might be useful in case the computer has very low RAM. Normally, though, it is safe to supply 0 as this parameter, so that the library will choose an appropriate value automatically.
Returns:
0 = Success; negative numbers are error codes
Referenced by ProgramDigitizer().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPPParameters (int handle, uint32_t channelMask, void * params)
Set DPP configuration parameters for DPP-PHA, DPP-PSD or DPP-CI.
Note:
Only for DPP-PHA, DPP-PSD and DPP-CI
Parameters:
[IN] handle : digitizer handle
[IN] channelMask : A bit mask indicating the channels to apply the DPP parameters
[IN] params : Pointer to a preallocated struct of type:
CAEN_DGTZ_DPP_PHA_Params_t, in case of DPP-PHA
CAEN_DGTZ_DPP_PSD_Params_t, in case of DPP-PSD
CAEN_DGTZ_DPP_CI_Params_t, in case of DPP-CI
Returns:
0 = Success; negative numbers are error codes
Referenced by ProgramDigitizer().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPPPreTriggerSize (int handle, int ch, uint32_t samples)
Sets the pre-trigger size, which is the portion of acquisition window visible before a trigger.
Note:
This function is only available to DPP enabled firmwares and only to DPP-PHA, DPP-PSD and DPP-CI
Parameters:
[IN] handle : digitizer handle
[IN] ch : the channel to set the pre-trigger for. ch=-1 writes the value for all channels. DPP-CI only supports ch=-1 (different channels must have the same pre-trigger)
[IN] sample : the pre-trigger size, in samples
Returns:
0 = Success; negative numbers are error codes
Referenced by ProgramDigitizer().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDPPTriggerMode (int handle, CAEN_DGTZ_DPP_TriggerMode_t mode)
Sets the DPP Trigger mode (DPP-PSD and DPP-CI only).
Parameters:
[IN] handle : digitizer handle
[IN] mode: the desired trigger mode:
CAEN_DGTZ_DPP_TriggerMode_Normal
CAEN_DGTZ_DPP_TriggerMode_Coincidence
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetDRS4SamplingFrequency (int handle, CAEN_DGTZ_DRS4Frequency_t frequency)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetEventPackaging (int handle, CAEN_DGTZ_EnaDis_t mode)
Enable or disable the Pack 2.5 mode of V1720/DT5720 Digitizers.
Parameters:
[IN] handle : digitizer handle
[IN] mode: Enable/Disable the Pack 2,5 mode
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetExtTriggerInputMode (int handle, CAEN_DGTZ_TriggerMode_t mode)
Sets external trigger input mode.
Parameters:
[IN] handle : digitizer handle.
[IN] mode : external trigger input mode.
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), and ProgramDigitizer().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetFastTriggerDigitizing (int handle, CAEN_DGTZ_EnaDis_t enable)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetFastTriggerMode (int handle, CAEN_DGTZ_TriggerMode_t mode)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupDCOffset (int handle, uint32_t group, uint32_t Tvalue)
Sets the DC offset for a specified group of channels.
Parameters:
[IN] handle : digitizer handle
[IN] group : the group of channels to set
[IN] Tvalue : the DC offset to set Tvalue is expressed in channel DAC (Digital to Analog Converter) steps. Please refer to digitizer documentation for possible value range.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupEnableMask (int handle, uint32_t mask)
Sets channels group that will be enabled into events.
Valid only for digitizers that supports channel groups (V1740, DT5740 for instance). Please refer to digitizers documentation.
Parameters:
[IN] handle : digitizer handle.
[IN] mask : channels group mask.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupFastTriggerDCOffset (int handle, uint32_t group, uint32_t DCvalue)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupFastTriggerThreshold (int handle, uint32_t group, uint32_t Tvalue)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupSelfTrigger (int handle, CAEN_DGTZ_TriggerMode_t mode, uint32_t groupmask)
Sets channel group self trigger mode according to mode Valid only for digitizers that supports channel groups (V1740, DT5740 for instance).
Parameters:
[IN] handle : digitizer handle
[IN] mode : trigger mode to set for selected channel groups
[IN] groupmask : channel group selection mask
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetGroupTriggerThreshold (int handle, uint32_t group, uint32_t Tvalue)
Sets the Trigger Threshold for a specified group of channels.
Parameters:
[IN] handle : digitizer handle.
[IN] group : the group of channels to set.
[IN] Tvalue : the threshold value to set.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetInterruptConfig (int handle, CAEN_DGTZ_EnaDis_t state, uint8_t level, uint32_t status_id, uint16_t event_number, CAEN_DGTZ_IRQMode_t mode)
Enable/disable Interrupts and set the Interrupt level used by the Digitizer.
Parameters:
[IN] handle : digitizer handle.
[IN] state : interrupts enable status
[IN] level : VME IRQ Level
[IN] status_id : VME status_id to assign to the Digitizer
[IN] event_number : number of event required to raise interrupt
[IN] mode : interrupt mode [CAEN_DGTZ_IRQ_MODE_RORA|CAEN_DGTZ_IRQ_MODE_ROAK]
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetIOLevel (int handle, CAEN_DGTZ_IOLevel_t level)
Sets the IO Level.
Parameters:
[IN] handle : digitizer handle
[IN] level : The level to set
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), and ProgramDigitizer().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetMaxNumAggregatesBLT (int handle, uint32_t numAggr)
Sets max aggregate number for each transfer DPP-PHA, DPP-PSD and DPP-CI you can use CAEN_DGTZ_SetDPPEventAggregation.
Parameters:
[IN] handle : digitizer handle
[IN] numAggr : Maximum Event Number for transfer
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetMaxNumEventsBLT (int handle, uint32_t numEvents)
Sets max event number for each transfer.
Deprecated:
On DPP-PHA, DPP-PSD and DPP-CI use CAEN_DGTZ_SetDPPEventAggregation
Parameters:
[IN] handle : digitizer handle
[IN] numEvents : Maximum Event Number for transfer
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), main(), and v1724_init().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetNumEventsPerAggregate (int handle, uint32_t numEvents, ...)
Sets the number of events that each aggregate will contain.
Parameters:
[IN] handle : digitizer handle
[IN] numEvents : number of events per aggregate
[IN] channel : optional parameter in the form of an int to specify the channel (required for DPP-PSD and DPP-CI, ignored by DPP-PHA)
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetOutputSignalMode (int handle, CAEN_DGTZ_OutputSignalMode_t mode)
Referenced by main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetPostTriggerSize (int handle, uint32_t percent)
Sets post trigger for next acquisitions.
Parameters:
[IN] handle : digitizer handle
[IN] percent : the percent of current record length
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetRecordLength (int handle, uint32_t size, ...)
Sets acquisition record length.
Parameters:
[IN] handle : digitizer handle
[IN] size : the size of the record (in samples)
[IN] channel : int specifying the channel to set the record length for. DPP-PSD and DPP-CI require this parameter, DPP-PHA ignores it
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), main(), ProgramDigitizer(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetRunSynchronizationMode (int handle, CAEN_DGTZ_RunSyncMode_t mode)
Sets the run synchronization mode of the digitizer, used to synchronize an acquisition on multiple boards.
Parameters:
[IN] handle : digitizer handle
[IN] mode : the run synchronization mode to set
Returns:
0 = Success; negative numbers are error codes
Referenced by ProgramDigitizer().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetSWTriggerMode (int handle, CAEN_DGTZ_TriggerMode_t mode)
Sets oneof the available trigger mode.
Parameters:
[IN] handle : digitizer handle
[IN] mode : trigger mode
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), and main().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetTriggerPolarity (int handle, uint32_t channel, CAEN_DGTZ_TriggerPolarity_t Polarity)
Sets the trigger polarity of a specified channel.
Parameters:
[IN] handle : digitizer handle
[IN] channel : select channel to set the trigger polarity
[IN] Polarity : The polarity to set
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetZeroSuppressionMode (int handle, CAEN_DGTZ_ZS_Mode_t mode)
Sets Zero Suppression mode.
Parameters:
[IN] handle : digitizer handle
[IN] mode : Zero Suppression mode.
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_update_digitizer(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SetZLEParameters (int handle, uint32_t channelMask, void * params)
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SWStartAcquisition (int handle)
Starts Digitizers acquisition.
Parameters:
[IN] handle: digitizer handle.
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_pre_bor(), main(), and v1724_pre_bor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_SWStopAcquisition (int handle)
Stops Digitizer acquisition.
Parameters:
[IN] handle: digitizer handle.
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_eor(), main(), and v1724_eor().
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_VMEIACKCycle (int VMEHandle, uint8_t level, int32_t * board_id)
Performs a VME Interrupt Acknowledge cycle to know the board_id of the board that raised an interrupt.
Parameters:
[IN] handle : handle of the CAEN VME Bridge that raised the interrupt (retrieved from CAEN_DGTZ_VMEIRQWait function)
[IN] level : VME interrupt level to acknowledge
[OUT] board_id : VME Digitizer board id of the interrupter
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_VMEIRQCheck (int VMEHandle, uint8_t * Mask)
Checks VME interrupt level.
Parameters:
[IN] VMEhandle : handle of CAEN VME Bridge that raised the interrupt request (retrieved from CAEN_DGTZ_VMEIRQWait function)
[OUT] Mask : bitmask representing the active VME interrupt requests.
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_VMEIRQWait (CAEN_DGTZ_ConnectionType LinkType, int LinkNum, int ConetNode, uint8_t IRQMask, uint32_t timeout, int * VMEHandle)
Waits for an interrupt from a CAEN VME Bridge.
Parameters:
[IN] LinkType : The link used to connect to the CAEN VME Bridge
[IN] LinkNum :
when using CONET, it is the optical link number to be used
when using USB, it is the USB device number to be used
[IN] ConetNode :
for CONET identify witch device in the daisy-chain is addressed
for USB must be 0.
[IN] IRQMask : A bit-mask indicating the IRQ lines
[IN] timeout : timeout (in milliseconds)
[OUT] VMEHandle : device handler of the CAEN VME Bridge that received interrupt request
Returns:
0 = Success; negative numbers are error codes
CAEN_DGTZ_ErrorCode CAENDGTZ_API CAEN_DGTZ_WriteRegister (int handle, uint32_t Address, uint32_t Data)
Writes a 32-bit word in a specific address offset of the digitizer.
Parameters:
[IN] handle : the digitizer handle
[IN] Address : the register address offset
[IN] Data : the 32-bit data to write
Returns:
0 = Success; negative numbers are error codes
Referenced by dt5720_init(), dt5720_update_digitizer(), main(), ProgramDigitizer(), v1724_init(), and v1724_pre_bor().