AlcapDAQ: CAEN/CAENUpgrader-1.4.1/CAENBridgeUpgrade/src/flash.c File Reference
flash.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include "flash.h"
#include "CAENVMElib.h"
Functions
static int GetFlashStatus32 (cvFlashAccess *Flash, uint8_t *Status)
static int GetFlashStatus (cvFlashAccess *Flash, uint8_t *Status)
static int WriteFlashPage32 (cvFlashAccess *Flash, uint8_t *data, int pagenum)
static int ReadFlashPage32 (cvFlashAccess *Flash, uint8_t *data, int pagenum)
static int ReadFlashSecurityReg32 (cvFlashAccess *Flash, uint8_t *data)
int WriteFlashPage (cvFlashAccess *Flash, uint8_t *data, int pagenum)
int ReadFlashPage (cvFlashAccess *Flash, uint8_t *data, int pagenum)
int ReadFlashSecurityReg (cvFlashAccess *Flash, uint8_t *data)
Function Documentation
static int GetFlashStatus (cvFlashAccess * Flash, uint8_t * Status) static
Definition at line 35 of file flash.c.
References GetFlashStatus32().
Referenced by WriteFlashPage32().
{
   int ret;
     ret = GetFlashStatus32(Flash, Status);
   return ret;
 }
static int GetFlashStatus32 (cvFlashAccess * Flash, uint8_t * Status) static
Definition at line 8 of file flash.c.
References CAENVME_ReadRegister(), CAENVME_WriteRegister(), FlashAccess::FlashEnable, FlashAccess::Handle, FlashAccess::RW_Flash, FlashAccess::Sel_Flash, and STATUS_READ_CMD.
Referenced by GetFlashStatus().
 {
     int res = 0;
     uint32_t reg32;
         // Enable flash
     res |= CAENVME_WriteRegister(Flash->Handle,Flash->Sel_Flash,Flash->FlashEnable);
         // Status read Command
         reg32 = STATUS_READ_CMD;
         res |= CAENVME_WriteRegister(Flash->Handle, Flash->RW_Flash, reg32);
         // Status read
         res |= CAENVME_ReadRegister(Flash->Handle, Flash->RW_Flash, &reg32);
         // Disable flash
         res |= CAENVME_WriteRegister(Flash->Handle, Flash->Sel_Flash, !Flash->FlashEnable);
         *Status = (uint8_t)(reg32 & 0xFF);
     return res;
 }
int ReadFlashPage (cvFlashAccess * Flash, uint8_t * data, int pagenum)
Definition at line 202 of file flash.c.
{
   int ret;
     ret = ReadFlashPage32(Flash, data, pagenum);
   return ret;
 }
static int ReadFlashPage32 (cvFlashAccess * Flash, uint8_t * data, int pagenum) static
Definition at line 95 of file flash.c.
References CAENVME_ReadRegister(), CAENVME_WriteRegister(), FlashAccess::FlashEnable, FlashAccess::Handle, i, MAIN_MEM_PAGE_READ_CMD, FlashAccess::PageSize, FlashAccess::RW_Flash, and FlashAccess::Sel_Flash.
Referenced by ReadFlashPage().
 {
     unsigned int i;
     int res = 0;
     uint32_t flash_addr;
     uint32_t Rbuff;
         uint32_t reg32;
     int  rcnt = 0;
         if (Flash->PageSize == 264)       // 4 and 8 Mbit
                 flash_addr = (uint32_t)pagenum << 9;
         else if (Flash->PageSize == 528)  // 16 and 32 Mbit
                 flash_addr = (uint32_t)pagenum << 10;
         else                              // 64 Mbit
                 flash_addr = (uint32_t)pagenum << 11;
     reg32 = !Flash->FlashEnable;
         res |= CAENVME_WriteRegister(Flash->Handle, Flash->Sel_Flash, reg32);
         // Enable flash
     res |= CAENVME_WriteRegister(Flash->Handle, Flash->Sel_Flash, Flash->FlashEnable);
         // Opcode
    res |= CAENVME_WriteRegister(Flash->Handle, Flash->RW_Flash, MAIN_MEM_PAGE_READ_CMD);
         // Page address
     res |= CAENVME_WriteRegister(Flash->Handle, Flash->RW_Flash, (flash_addr>>16) & 0xFF);
     res |= CAENVME_WriteRegister(Flash->Handle, Flash->RW_Flash, (flash_addr>>8) & 0xFF);
     res |= CAENVME_WriteRegister(Flash->Handle, Flash->RW_Flash, flash_addr & 0xFF);
         // additional don't care bytes
     for (i=0; i<4; i++) {
                 res |= CAENVME_WriteRegister(Flash->Handle, Flash->RW_Flash, 0);
     }
     // Read Flash Page
     rcnt = 0;
     for (i=0; i<Flash->PageSize; i++) {
                 CAENVME_ReadRegister(Flash->Handle, Flash->RW_Flash, &Rbuff);
                 data[i] = (uint8_t) Rbuff;
     }
         // Disable flash
     reg32 = !Flash->FlashEnable;
         res |= CAENVME_WriteRegister(Flash->Handle, Flash->Sel_Flash, reg32);
     return res;
 }
int ReadFlashSecurityReg (cvFlashAccess * Flash, uint8_t * data)
Definition at line 217 of file flash.c.
{
   int ret;
     ret = ReadFlashSecurityReg32(Flash, data);
   return ret;
 }
static int ReadFlashSecurityReg32 (cvFlashAccess * Flash, uint8_t * data) static
Definition at line 146 of file flash.c.
References AT45_IDREG_LENGTH, AT45_READ_SECURITY_REGISTER_OPCODE, CAENVME_ReadRegister(), CAENVME_WriteRegister(), FlashAccess::FlashEnable, FlashAccess::Handle, i, FlashAccess::RW_Flash, and FlashAccess::Sel_Flash.
Referenced by ReadFlashSecurityReg().
 {
   int i;
   int res = 0;
   uint32_t data32[2048];
   uint32_t reg32;
   reg32 = !Flash->FlashEnable;
   res |= CAENVME_WriteRegister(Flash->Handle, Flash->Sel_Flash, reg32);
   // enable flash (NCS = 0)
   res |= CAENVME_WriteRegister(Flash->Handle, Flash->Sel_Flash, Flash->FlashEnable);
   // write opcode
   reg32 = AT45_READ_SECURITY_REGISTER_OPCODE;
   res |= CAENVME_WriteRegister(Flash->Handle, Flash->RW_Flash, reg32);
   // additional don't care bytes
   reg32 = 0;
   for (i=0; i<3; i++)
       res |= CAENVME_WriteRegister(Flash->Handle, Flash->RW_Flash, reg32);
   // read flash page
   for (i=0; i<AT45_IDREG_LENGTH; i++)
       res |= CAENVME_ReadRegister(Flash->Handle, Flash->RW_Flash,(data32+i));
   // disable flash (NCS = 1)
   reg32 = !Flash->FlashEnable;
   res |= CAENVME_WriteRegister(Flash->Handle, Flash->Sel_Flash, reg32);
   for (i=0; i<AT45_IDREG_LENGTH; i++)
           data[i] = (uint8_t)data32[i];
   return res;
 }
int WriteFlashPage (cvFlashAccess * Flash, uint8_t * data, int pagenum)
Definition at line 186 of file flash.c.
{
   int ret;
     ret = WriteFlashPage32(Flash, data, pagenum);
   return ret;
 }
static int WriteFlashPage32 (cvFlashAccess * Flash, uint8_t * data, int pagenum) static
Definition at line 46 of file flash.c.
References CAENVME_WriteRegister(), FlashAccess::FlashEnable, GetFlashStatus(), FlashAccess::Handle, i, MAIN_MEM_PAGE_PROG_TH_BUF1_CMD, FlashAccess::PageSize, FlashAccess::RW_Flash, and FlashAccess::Sel_Flash.
Referenced by WriteFlashPage().
 {
     unsigned int i;
     int res = 0;
     uint8_t stat;
     uint32_t flash_addr;
         uint32_t reg32;
         if (Flash->PageSize == 264)  // 4 and 8 Mbit
                 flash_addr = (uint32_t)pagenum << 9;
         else if (Flash->PageSize == 528)  // 16 and 32 Mbit
                 flash_addr = (uint32_t)pagenum << 10;
         else  // 64 Mbit
                 flash_addr = (uint32_t)pagenum << 11;
         reg32 = !Flash->FlashEnable;
         res |= CAENVME_WriteRegister(Flash->Handle, Flash->Sel_Flash, reg32);
         // Enable flash
     res |= CAENVME_WriteRegister(Flash->Handle, Flash->Sel_Flash, Flash->FlashEnable);
     // Opcode
     res |= CAENVME_WriteRegister(Flash->Handle, Flash->RW_Flash, MAIN_MEM_PAGE_PROG_TH_BUF1_CMD);
         // Page address
     res |= CAENVME_WriteRegister(Flash->Handle,Flash->RW_Flash, (flash_addr>>16) & 0xFF);
     res |= CAENVME_WriteRegister(Flash->Handle,Flash->RW_Flash, (flash_addr>>8) & 0xFF);
     res |= CAENVME_WriteRegister(Flash->Handle,Flash->RW_Flash, flash_addr & 0xFF);
     // Fill buffer
     for (i=0; i<Flash->PageSize; i++) {
                 res |= CAENVME_WriteRegister(Flash->Handle,Flash->RW_Flash, data[i]);
     }
     // Disable flash
    reg32 = !Flash->FlashEnable;
         res |= CAENVME_WriteRegister(Flash->Handle, Flash->Sel_Flash, reg32);
     // wait for Tep (Time of erase and programming)
         do
                 res |= GetFlashStatus(Flash, &stat);
         while (!(stat & 0x80));
     return res;
 }