AlcapDAQ: TOnlineFrame Class Reference
TOnlineFrame Class Reference
#include <TOnlineFrame.h>
Public Member Functions
TOnlineFrame (const TGWindow *p, std::string module_file_name)
~TOnlineFrame ()
void CloseWindow ()
Bool_t ProcessMessage (Long_t msg, Long_t param1, Long_t param2)
void ConsiderCycling ()
void ConsiderAutoupdate (const Bool_t force=kFALSE)
void runMacro (const char *macro)
void print_msg (const char *msg, const Int_t partidx=0)
const char * getServerName () const
void setServerName (const char *name)
const unsigned int getServerPort () const
void setServerPort (const unsigned int port_nr)
const unsigned int getAutoUpdateTime () const
TSocket * ConnectToServer ()
TFile * OpenRootFile (const char *filename, const Bool_t update_filename=kTRUE)
TSocket * GetSocketHandle ()
TH1 * GetHist (const char *histname)
std::vector< TString > GetHistTitles ()
void UpdateDisplay ()
Data Fields
std::set< std::string > fLoadedMacros
std::map< std::string,
TGTextButton * > fButtons
Private Attributes
TGHorizontalFrame * fTopFrame
TGButton * fUpdateButton
TGButton * fPrintButton
TGButton * fConnectButton
TGButton * fFileOpenButton
TRootEmbeddedCanvas * fEmbeddedCanvas
TGCheckButton * fCycleDisplays
TGCheckButton * fAutoUpdate
TGTextEntry * fAutoUpdateTime
TGTextEntry * fFileName
int fCurrentDisplay
TGStatusBar * fStatusBar
TGTextEntry * fServerName
TGTextEntry * fServerPort
ULong_t run_nr
TSocket * fpSock
Detailed Description
Definition at line 22 of file TOnlineFrame.h.
Constructor & Destructor Documentation
TOnlineFrame::TOnlineFrame (const TGWindow * p, std::string module_file_name)
Definition at line 34 of file TOnlineFrame.cpp.
References B_AUTOUPDATE, B_CONNECT, B_CYCLE, B_FILE_OPEN, B_PRINT, B_UPDATE, buf, fAutoUpdate, fAutoUpdateTime, fButtons, fConnectButton, fCurrentDisplay, fCycleDisplays, fEmbeddedCanvas, fFileName, fFileOpenButton, fPrintButton, fServerName, fServerPort, fStatusBar, fTopFrame, fUpdateButton, gROOT, screen_info::hasArgs, height, i, screen_info::macroArgs, screen_info::macroName, run_nr, screens, SCREENS_BASE, screen_info::visibleName, and width.
                                                                        :TGMainFrame(p, width,
                 height)
 {
         fCurrentDisplay = 8;
         run_nr = 0;
         // read macroses from the external file
         //const char *is_name = "/home/daq/DAQ/online-display/MODULES";
         const char *env_name = "DAQdir";
         std::string env_value = "";
         std::string is_name;
         if ( getenv(env_name) )
         {
                 if (module_file_name.empty() ) module_file_name="MODULES";
                 env_value = getenv(env_name);
                 is_name = env_value + "/online-display/"+module_file_name;
         }
         else
         {
                 std::cerr << "***ERROR! shell variable " << env_name << " is not set. The program will not be able to find display modules." << std::endl;
         }
         //const char *is_name = "/home/daq/DAQ/online-display/MODULES";
         std::cout << "Reading modules from file [" << is_name << "]" << std::endl;
         ifstream *is = new ifstream( is_name.c_str() );
         char buf[1024];
         std::string args;
         while ( is->good() )
         {
                 *is >> std::ws;
                 is->getline(buf,1024);
                 if ( buf[0] == '#' ) continue;
                 if ( is->gcount() < 2 ) break;
                 std::istringstream iss (buf,std::istringstream::in);
                 screen_info info={"","","",false};
                 iss >> std::ws >> info.visibleName >> std::ws >> info.macroName>> std::ws >>args;
                 if (!args.empty()) {
                         info.macroArgs=args;
                         info.hasArgs =true;
                 }
                 screens.push_back(info);
                 std::cout << buf << std::endl;
                 args="";
         }
         delete is;
         // configure macro path
         std::string macro_path = gROOT->GetMacroPath();
         macro_path += std::string(":")+std::string(env_value)+std::string("/online-display/modules");
         gROOT->SetMacroPath( macro_path.c_str() );
         // a little frame at the top
         fTopFrame = new TGHorizontalFrame(this, width - 10, 30, kChildFrame);//, kFixedWidth);
         AddFrame(fTopFrame, new TGLayoutHints(kLHintsExpandX) );
         // an "update" button
         fUpdateButton = new TGTextButton(fTopFrame, "Update", B_UPDATE);
         fUpdateButton->Associate(this);
         fTopFrame->AddFrame(fUpdateButton, new TGLayoutHints(kLHintsLeft,2,2,2,2));
         // Autoupdate checkbox
         fAutoUpdate = new TGCheckButton(fTopFrame, "AutoUpdate", B_AUTOUPDATE);
         fAutoUpdate->Associate(this);
         fTopFrame->AddFrame(fAutoUpdate, new TGLayoutHints(kLHintsLeft|kLHintsCenterY));
         TGLabel *label = new TGLabel(fTopFrame,"every");
         fTopFrame->AddFrame(label, new TGLayoutHints(kLHintsLeft|kLHintsCenterY,0,2,2,2));
         fAutoUpdateTime = new TGTextEntry(fTopFrame,"10");
         fAutoUpdateTime->SetWidth(20);
         fAutoUpdateTime->SetMaxLength(4);
         fTopFrame->AddFrame(fAutoUpdateTime, new TGLayoutHints(kLHintsLeft|kLHintsCenterY,2,2,2,2));
         label = new TGLabel(fTopFrame,"s");
         fTopFrame->AddFrame(label, new TGLayoutHints(kLHintsLeft|kLHintsCenterY,1,2,2,2));
         // a "cycle" checkbox
         fCycleDisplays = new TGCheckButton(fTopFrame, "Cycle", B_CYCLE);
         fCycleDisplays->Associate(this);
         fTopFrame->AddFrame(fCycleDisplays, new TGLayoutHints(kLHintsLeft|kLHintsCenterY,2,1,2,2));
         // separator
         TGVertical3DLine *vline = new TGVertical3DLine(fTopFrame);
         fTopFrame->AddFrame(vline, new TGLayoutHints(kLHintsLeft|kLHintsExpandY,1,2,2,2));
         // server name
         label = new TGLabel(fTopFrame,"Server");
         fTopFrame->AddFrame(label, new TGLayoutHints(kLHintsLeft|kLHintsCenterY,2,1,2,2));
         fServerName = new TGTextEntry(fTopFrame,"");
         fServerName->SetWidth(150);
         fServerName->SetMaxLength(64);
         fTopFrame->AddFrame(fServerName, new TGLayoutHints(kLHintsLeft|kLHintsCenterY,2,2,2,2));
         // server port
         label = new TGLabel(fTopFrame,"port");
         fTopFrame->AddFrame(label, new TGLayoutHints(kLHintsLeft|kLHintsCenterY,2,2,2,2));
         fServerPort = new TGTextEntry(fTopFrame,"");
         fServerPort->SetWidth(50);
         fServerPort->SetMaxLength(6);
         fTopFrame->AddFrame(fServerPort, new TGLayoutHints(kLHintsLeft|kLHintsCenterY,2,2,2,2));
         // connect to server button
         fConnectButton = new TGTextButton(fTopFrame, "Connect", B_CONNECT);
         fConnectButton->Associate(this);
         fTopFrame->AddFrame(fConnectButton, new TGLayoutHints(kLHintsLeft,2,2,2,2));
         // separator
         vline = new TGVertical3DLine(fTopFrame);
         fTopFrame->AddFrame(vline, new TGLayoutHints(kLHintsLeft|kLHintsExpandY,1,2,2,2));
         // ROOT file
         label = new TGLabel(fTopFrame,"File");
         fTopFrame->AddFrame(label, new TGLayoutHints(kLHintsLeft|kLHintsCenterY,2,2,2,2));
         fFileName = new TGTextEntry(fTopFrame,"");
         fFileName->SetWidth(100);
         fFileName->SetMaxLength(32);
         //fFileName->SetState(kFALSE);
         fFileName->Associate(this);
         fTopFrame->AddFrame(fFileName, new TGLayoutHints(kLHintsLeft|kLHintsCenterY,2,2,2,2));
         // Open File button
         fFileOpenButton = new TGTextButton(fTopFrame, "Open", B_FILE_OPEN);
         fFileOpenButton->Associate(this);
         fTopFrame->AddFrame(fFileOpenButton, new TGLayoutHints(kLHintsLeft,2,2,2,2));
         // separator
         vline = new TGVertical3DLine(fTopFrame);
         fTopFrame->AddFrame(vline, new TGLayoutHints(kLHintsLeft|kLHintsExpandY,1,2,2,2));
         // a "print" button
         fPrintButton = new TGTextButton(fTopFrame, "Print to File", B_PRINT);
         fPrintButton->Associate(this);
         fTopFrame->AddFrame(fPrintButton, new TGLayoutHints(kLHintsRight,2,2,2,2));
         // containter for user buttons and canvas
         TGHorizontalFrame *frame_aux = new TGHorizontalFrame(this, 50, 80);
         AddFrame(frame_aux, new TGLayoutHints(kLHintsExpandY|kLHintsExpandX,1,1,1,1) );
         // left frame for user script buttons
         TGVerticalFrame *frame_user = new TGVerticalFrame(frame_aux, 10, 30);
         frame_aux->AddFrame(frame_user, new TGLayoutHints(kLHintsExpandY,1,1,1,1) );
         // a menu for changing screens
         //fScreenFrame = new TGHorizontalFrame(fTopFrame, 480, 28, kChildFrame);//, kFixedWidth);
         //fTopFrame->AddFrame(fScreenFrame, new TGLayoutHints(kLHintsLeft));
         for (unsigned int i = 0; i < screens.size(); i++)
         {
                 TGTextButton *b = new TGTextButton(frame_user, screens[i].visibleName,
                                 SCREENS_BASE + i);
                 b->SetToolTipText((screens[i].macroName + screens[i].macroArgs).c_str());
                 b->Associate(this);
                 frame_user->AddFrame(b, new TGLayoutHints(kLHintsLeft|kFitWidth));
                 fButtons[screens[i].visibleName]=b;
         }
         // our big embedded canvas
         fEmbeddedCanvas =
                 new TRootEmbeddedCanvas("Canvas", frame_aux, width - 10, height - 32,kSunkenFrame|kDoubleBorder|kFitWidth|kFitHeight);
         fEmbeddedCanvas->SetAutoFit( kTRUE );
         frame_aux->AddFrame(fEmbeddedCanvas, new TGLayoutHints(kLHintsExpandX | kLHintsExpandY, 1, 1, 1, 1));
         fStatusBar = new TGStatusBar(this);
         AddFrame(fStatusBar,  new TGLayoutHints(kLHintsExpandX, 1, 1, 1, 1));
         int parts[] = {70,10,20};
         fStatusBar->SetParts(parts,3);
         SetWindowName("MIDAS Online Display");
         MapSubwindows();
         Resize(GetDefaultSize());
         MapWindow();
         SetMinWidth(300);
 // Define the histogram
         gROOT->LoadMacro("modules/common/get_histogram.C");
         gROOT->LoadMacro("modules/common/get_histogram_2d.C");
 }
TOnlineFrame::~TOnlineFrame ()
Definition at line 226 of file TOnlineFrame.cpp.
 {
 }
Member Function Documentation
void TOnlineFrame::CloseWindow ()
Definition at line 337 of file TOnlineFrame.cpp.
 {
         DeleteWindow();
         gApplication->Terminate(0);
         exit(1);
 }
TSocket * TOnlineFrame::ConnectToServer ()
Definition at line 398 of file TOnlineFrame.cpp.
References fEmbeddedCanvas, fFileName, fpSock, fServerName, getServerName(), getServerPort(), gROOT, msg, openSocket(), print_msg(), s, and sprintf().
Referenced by main(), and ProcessMessage().
 {
         TSocket *s = NULL;
         const char *hostname = getServerName();
         const unsigned int port_nr = getServerPort();
         char msg[1024];
         gROOT->DeleteAll();
         fEmbeddedCanvas->GetCanvas()->Clear();
         fEmbeddedCanvas->Clear();
         ULong_t ucolor_white;
         gClient->GetColorByName("#ffffff",ucolor_white);
         if ( (s = openSocket(hostname,port_nr)) == 0 )
         {
                 sprintf(msg,"Cannot connect to port %d on host [%s]",port_nr,hostname);
                 print_msg(msg);
                 print_msg("ERROR",2);
                 exit(1);
                 //fServerName->ChangeBackground(ucolor_white);
         }
         else
         {
                 sprintf(msg,"Connected to remote server %s:%d",hostname,port_nr);
                 print_msg(msg);
                 sprintf(msg,"%s:%d",hostname,port_nr);
                 print_msg(msg,2);
                 //ConsiderAutoupdate( kTRUE );
                 ULong_t ucolor_green;
                 gClient->GetColorByName("#A0F5A0",ucolor_green);
                 fServerName->ChangeBackground(ucolor_green);
         }
         //fFileName->SetText("");
         fFileName->ChangeBackground(ucolor_white);
         fpSock = s;
         return s;
 }
void TOnlineFrame::ConsiderAutoupdate (const Bool_t force = kFALSE)
Parameters
force Force update if true
Definition at line 360 of file TOnlineFrame.cpp.
References fAutoUpdate, fCurrentDisplay, fCycleDisplays, runMacro(), and screens.
Referenced by main(), and ProcessMessage().
 {
         if (((fAutoUpdate->GetState() == kButtonDown) && fCycleDisplays->GetState()) != kButtonDown || force )
         {
                 const char *macro = screens[fCurrentDisplay].macroName.c_str();
                 runMacro(macro);
         }
 }
void TOnlineFrame::ConsiderCycling ()
Definition at line 344 of file TOnlineFrame.cpp.
References fCurrentDisplay, fCycleDisplays, runMacro(), and screens.
Referenced by main().
 {
         if(fCycleDisplays->GetState() == kButtonDown)
         {
                 fCurrentDisplay = (fCurrentDisplay+1) % screens.size();
                 const char *macro = screens[fCurrentDisplay].macroName.c_str();
                 runMacro(macro);
         }
 }
const unsigned int TOnlineFrame::getAutoUpdateTime () const
Definition at line 391 of file TOnlineFrame.cpp.
References fAutoUpdateTime.
Referenced by main().
 {
         unsigned int t = atol(fAutoUpdateTime->GetText());
         if ( t < 1 ) t = 1;
         return t;
 }
TH1 * TOnlineFrame::GetHist (const char * histname)
Definition at line 557 of file TOnlineFrame.cpp.
References fpSock, msg, req, and sprintf().
Referenced by main().
 {
         if (!fpSock)
                 return NULL;
         char req[2048];
         sprintf(req, "GET %s", histname);
         TMessage *msg;
         fpSock->Send(req);
         fpSock->Recv(msg);
         TH1 *hist = (TH1*) msg->ReadObject(msg->GetClass());
         //hist->Print();
         //hist->Draw();
         delete msg;
         return hist;
 }
std::vector< TString > TOnlineFrame::GetHistTitles ()
Definition at line 576 of file TOnlineFrame.cpp.
References fpSock, i, msg, and title.
Referenced by main().
 {
         std::vector<TString> v;
         if(!fpSock)
                 return v;
         fpSock->Send("LIST");
         TMessage *msg;
         fpSock->Recv(msg);
         TObjArray *objArray = (TObjArray *)msg->ReadObject(msg->GetClass());
         for (int i = 0; i < objArray->GetEntries(); ++i)
         {
                 TObjString *title = (TObjString *)objArray->At(i);
                 v.push_back((TString)title->GetString());
         }
         delete msg;
         return v;
 }
const char * TOnlineFrame::getServerName () const
Definition at line 369 of file TOnlineFrame.cpp.
References fServerName.
Referenced by ConnectToServer().
 {
         return fServerName->GetText();
 }
const unsigned int TOnlineFrame::getServerPort () const
Definition at line 379 of file TOnlineFrame.cpp.
References fServerPort.
Referenced by ConnectToServer().
 {
         return atol(fServerPort->GetText());
 }
TSocket* TOnlineFrame::GetSocketHandle () inline
Definition at line 60 of file TOnlineFrame.h.
References fpSock.
 {return fpSock;}
TFile * TOnlineFrame::OpenRootFile (const char * filename, const Bool_t update_filename = kTRUE)
Definition at line 438 of file TOnlineFrame.cpp.
References basename, fEmbeddedCanvas, fFileName, fServerName, gROOT, msg, openRootFile(), print_msg(), and sprintf().
Referenced by main(), and ProcessMessage().
 {
         TFile *f = NULL;
         char msg[1024];
         gROOT->DeleteAll();
         fEmbeddedCanvas->GetCanvas()->Clear();
         fEmbeddedCanvas->Clear();
         ULong_t ucolor_white;
         gClient->GetColorByName("#ffffff",ucolor_white);
         if ( (f = openRootFile(filename)) == 0 )
         {
                 sprintf(msg,"Cannot open ROOT file [%s]",filename);
                 print_msg(msg);
                 print_msg("ERROR",1);
                 print_msg("ERROR",2);
                 exit(1);
                 //fFileName->SetText("");
                 //fFileName->ChangeBackground(ucolor_white);
         }
         else
         {
                 sprintf(msg,"Connected to ROOT file %s",filename);
                 print_msg(msg);
                 print_msg(basename((char*)filename),1);
                 print_msg("File",2);
                 //fFileName->SetText(basename(filename));
                 //ConsiderAutoupdate( kTRUE );
                 ULong_t ucolor_green;
                 gClient->GetColorByName("#A0FfA0",ucolor_green);
                 fFileName->ChangeBackground(ucolor_green);
         }
         if ( update_filename )
                 fFileName->SetText(basename((char*)filename));
         fServerName->ChangeBackground(ucolor_white);
         return f;
 }
void TOnlineFrame::print_msg (const char * msg, const Int_t partidx = 0)
Definition at line 536 of file TOnlineFrame.cpp.
References fStatusBar, and printf().
Referenced by ConnectToServer(), OpenRootFile(), ProcessMessage(), and runMacro().
 {
         printf("%s\n",msg);
         fStatusBar->SetText(msg, partidx);
 }
Bool_t TOnlineFrame::ProcessMessage (Long_t msg, Long_t param1, Long_t param2)
Definition at line 230 of file TOnlineFrame.cpp.
References B_CONNECT, B_FILE_OPEN, B_PRINT, B_UPDATE, ConnectToServer(), ConsiderAutoupdate(), fButtons, fCurrentDisplay, fEmbeddedCanvas, fFileName, OpenRootFile(), print_msg(), printf(), run_nr, screens, SCREENS_BASE, sprintf(), time, and UpdateDisplay().
 {
         Bool_t ret = false;
         char name[1024];
         char text[1024];
         switch (GET_MSG(msg))
         {
                 case kC_COMMAND:
                         switch (GET_SUBMSG(msg))
{
                                 case kCM_BUTTON:
                                         if (param1 >= SCREENS_BASE)
{
                                                 ULong_t ucolor_black;
                                                 gClient->GetColorByName("#000000",ucolor_black);
                                                 fButtons[screens[fCurrentDisplay].visibleName]->SetTextColor(ucolor_black);
                                                 fCurrentDisplay = param1 - SCREENS_BASE;
                                         }
                                         if ( param1 == B_UPDATE || param1 >= SCREENS_BASE )
{
                                                 UpdateDisplay();
                                         }
                                         else if (param1 == B_PRINT)
{
                                                 unsigned long int t = time(NULL);
                                                 sprintf(name,"%s_run_%06ld_%lu.pdf",screens[fCurrentDisplay].visibleName,run_nr,t);
                                                 fEmbeddedCanvas->GetCanvas()->Print(name);
                                                 sprintf(name,"%s_run_%06ld_%lu.png",screens[fCurrentDisplay].visibleName,run_nr,t);
                                                 fEmbeddedCanvas->GetCanvas()->Print(name);
                                                 sprintf(text,"Canvas printed to file [%s]",name);
                                                 print_msg(text);
                                         }
                                         else if ( param1 == B_CONNECT )
{
                                                 if ( ConnectToServer() )
{
                                                         ConsiderAutoupdate( kTRUE );
                                                 }
                                         }
                                         else if ( param1 == B_FILE_OPEN )
{
                                                 TGFileInfo fi;
                                                 const char *file_types[] = {"hist files", "h*.root",
                                                         0, 0};
                                                 fi.fFileTypes = file_types;
                                                 fi.fMultipleSelection = kFALSE;
                                                 fi.SetMultipleSelection( kFALSE );
                                                 //TGFileDialog *f = new TGFileDialog(gClient->GetRoot(),this,kFDOpen,&fi);
                                                 if ( fi.fFilename )
{
                                                         if ( OpenRootFile(fi.fFilename) )
{
                                                                 ConsiderAutoupdate( kTRUE );
                                                         }
                                                 }
                                         }
                                         ret = true;
                                         break;
                                 default:
                                         printf("Unknown command received\n");
                                         break;
                         } // switch (GET_SUBMSG(msg))
                         break; // case kC_COMMAND
                 case kC_TEXTENTRY:
                         switch (GET_SUBMSG(msg))
{
                                 case kTE_ENTER:
                                         if ( OpenRootFile( fFileName->GetText(), kFALSE ) )
{
                                                 ConsiderAutoupdate( kTRUE );
                                         }
                                         break;
                         }
                         break; // case kC_TEXTENTRY
         } // switch (GET_MSG(msg))
         return ret;
 }
void TOnlineFrame::runMacro (const char * macro)
Definition at line 483 of file TOnlineFrame.cpp.
References clear_recv_buffer(), fEmbeddedCanvas, get_run_number(), get_status_code(), gROOT, msg, print_msg(), RDISP_ERR_BAD_RESPONSE, RDISP_ERR_BROKEN_PIPE, RDISP_ERR_NO_CON, RDISP_ERR_NO_FILE, RDISP_ERR_NO_FOLDER, RDISP_ERR_NO_RESPONSE, RDISP_ERR_NO_SOURCE, run_nr, sprintf(), and status.
Referenced by ConsiderAutoupdate(), and ConsiderCycling().
 {
         char txt[1024];
         run_nr = get_run_number();
         sprintf(txt,"%ld",run_nr);
         print_msg(txt,1);
         sprintf(txt,"Executing  macro [%s]",macro);
         print_msg(txt);
         gROOT->DeleteAll();
         clear_recv_buffer();
         fEmbeddedCanvas->GetCanvas()->Clear();
         fEmbeddedCanvas->Clear();
         gROOT->cd();
         gROOT->Macro(macro);
         // check status
         int status = get_status_code();
         if ( status != 0 )
         {
                 const char *msg = "";
                 switch ( status )
                 {
                         case RDISP_ERR_NO_CON:
                                 msg = "No connection to remote server";
                                 break;
                         case RDISP_ERR_BAD_RESPONSE:
                                 msg = "Bad response from the server";
                                 break;
                         case RDISP_ERR_NO_RESPONSE:
                                 msg = "No response from the server";
                                 break;
                         case RDISP_ERR_NO_SOURCE:
                                 msg = "No sources opened";
                                 break;
                         case RDISP_ERR_BROKEN_PIPE:
                                 msg = "Broken pipe";
                                 break;
                         case RDISP_ERR_NO_FILE:
                                 msg = "Cannot open ROOT file";
                                 break;
                         case RDISP_ERR_NO_FOLDER:
                                 msg = "Cannot load root folder from the ROOT file";
                                 break;
                         default:
                                 msg = "Unknown error";
                                 break;
                 }
                 print_msg( msg );
         }
 }
void TOnlineFrame::setServerName (const char * name)
Definition at line 374 of file TOnlineFrame.cpp.
References fServerName.
Referenced by main().
 {
         return fServerName->SetText( name );
 }
void TOnlineFrame::setServerPort (const unsigned int port_nr)
Definition at line 384 of file TOnlineFrame.cpp.
References fServerPort, and sprintf().
Referenced by main().
 {
         char txt[32];
         sprintf(txt,"%d",port_nr);
         return fServerPort->SetText( txt );
 }
void TOnlineFrame::UpdateDisplay ()
Definition at line 313 of file TOnlineFrame.cpp.
References fButtons, fCurrentDisplay, fLoadedMacros, gROOT, screen_info::hasArgs, screen_info::macroArgs, screen_info::macroName, and screens.
Referenced by main(), and ProcessMessage().
{
         screen_info &current_display=screens[fCurrentDisplay];
         //runMacro(macro);
         if(fLoadedMacros.count(current_display.macroName) ==0) {
                 gROOT->LoadMacro(current_display.macroName.c_str());
                 cout<<"Loaded macro: "<<current_display.macroName<<endl;
                 fLoadedMacros.insert(current_display.macroName);
         }
         int last_slash=current_display.macroName.rfind("/")+1;
         std::string command=current_display.macroName.substr(last_slash);
         int extension_start=command.find(".");
         command=command.substr(0,extension_start);
         if(!current_display.hasArgs) command+="()";
         else command+=current_display.macroArgs;
         cout<<"Processing Line: "<<command<<endl;
         gROOT->ProcessLine(command.c_str());
         cout<< "about to set color"<<endl;
                 ULong_t ucolor_red;
                 gClient->GetColorByName("#FF0000",ucolor_red);
         fButtons[screens[fCurrentDisplay].visibleName]->SetTextColor(ucolor_red);
         gPad->Update();
 }
Field Documentation
TGCheckButton* TOnlineFrame::fAutoUpdate private
Definition at line 33 of file TOnlineFrame.h.
Referenced by ConsiderAutoupdate(), and TOnlineFrame().
TGTextEntry* TOnlineFrame::fAutoUpdateTime private
Definition at line 34 of file TOnlineFrame.h.
Referenced by getAutoUpdateTime(), and TOnlineFrame().
std::map<std::string, TGTextButton*> TOnlineFrame::fButtons
Definition at line 67 of file TOnlineFrame.h.
Referenced by ProcessMessage(), TOnlineFrame(), and UpdateDisplay().
TGButton* TOnlineFrame::fConnectButton private
Definition at line 29 of file TOnlineFrame.h.
Referenced by TOnlineFrame().
int TOnlineFrame::fCurrentDisplay private
Definition at line 36 of file TOnlineFrame.h.
Referenced by ConsiderAutoupdate(), ConsiderCycling(), ProcessMessage(), TOnlineFrame(), and UpdateDisplay().
TGCheckButton* TOnlineFrame::fCycleDisplays private
Definition at line 32 of file TOnlineFrame.h.
Referenced by ConsiderAutoupdate(), ConsiderCycling(), and TOnlineFrame().
TRootEmbeddedCanvas* TOnlineFrame::fEmbeddedCanvas private
Definition at line 31 of file TOnlineFrame.h.
Referenced by ConnectToServer(), OpenRootFile(), ProcessMessage(), runMacro(), and TOnlineFrame().
TGTextEntry* TOnlineFrame::fFileName private
Definition at line 35 of file TOnlineFrame.h.
Referenced by ConnectToServer(), OpenRootFile(), ProcessMessage(), and TOnlineFrame().
TGButton* TOnlineFrame::fFileOpenButton private
Definition at line 30 of file TOnlineFrame.h.
Referenced by TOnlineFrame().
std::set<std::string> TOnlineFrame::fLoadedMacros
Definition at line 66 of file TOnlineFrame.h.
Referenced by UpdateDisplay().
TGButton* TOnlineFrame::fPrintButton private
Definition at line 28 of file TOnlineFrame.h.
Referenced by TOnlineFrame().
TSocket* TOnlineFrame::fpSock private
Definition at line 41 of file TOnlineFrame.h.
Referenced by ConnectToServer(), GetHist(), GetHistTitles(), and GetSocketHandle().
TGTextEntry* TOnlineFrame::fServerName private
Definition at line 38 of file TOnlineFrame.h.
Referenced by ConnectToServer(), getServerName(), OpenRootFile(), setServerName(), and TOnlineFrame().
TGTextEntry* TOnlineFrame::fServerPort private
Definition at line 39 of file TOnlineFrame.h.
Referenced by getServerPort(), setServerPort(), and TOnlineFrame().
TGStatusBar* TOnlineFrame::fStatusBar private
Definition at line 37 of file TOnlineFrame.h.
Referenced by print_msg(), and TOnlineFrame().
TGHorizontalFrame* TOnlineFrame::fTopFrame private
Definition at line 25 of file TOnlineFrame.h.
Referenced by TOnlineFrame().
TGButton* TOnlineFrame::fUpdateButton private
Definition at line 27 of file TOnlineFrame.h.
Referenced by TOnlineFrame().
ULong_t TOnlineFrame::run_nr private
Definition at line 40 of file TOnlineFrame.h.
Referenced by ProcessMessage(), runMacro(), and TOnlineFrame().
The documentation for this class was generated from the following files:
online-display/TOnlineFrame.h
online-display/TOnlineFrame.cpp