AlcapDAQ: TMuonEvent Class Reference
TMuonEvent Class Reference
#include <TMuonEvent.h>
Public Member Functions
TMuonEvent ()
~TMuonEvent ()
TDetectorPulse * GetPulse (const std::string &detector) const
void SetPulse (const std::string &detector, TDetectorPulse *pulse)
int GetNumPulses () const
TDetectorPulse * GetGe () const
void SetGe (TDetectorPulse *p)
TDetectorPulse * GetLiquidSc () const
void SetLiquidSc (TDetectorPulse *p)
TDetectorPulse * GetNDet () const
void SetNDet (TDetectorPulse *p)
TDetectorPulse * GetNDet2 () const
void SetNDet2 (TDetectorPulse *p)
TDetectorPulse * GetScGe () const
void SetScGe (TDetectorPulse *p)
TDetectorPulse * GetScL () const
void SetScL (TDetectorPulse *p)
TDetectorPulse * GetScR () const
void SetScR (TDetectorPulse *p)
TDetectorPulse * GetScVe () const
void SetScVe (TDetectorPulse *p)
TDetectorPulse * GetSiL1_1 () const
void SetSiL1_1 (TDetectorPulse *p)
TDetectorPulse * GetSiL1_2 () const
void SetSiL1_2 (TDetectorPulse *p)
TDetectorPulse * GetSiL1_3 () const
void SetSiL1_3 (TDetectorPulse *p)
TDetectorPulse * GetSiL1_4 () const
void SetSiL1_4 (TDetectorPulse *p)
TDetectorPulse * GetSiL2 () const
void SetSiL2 (TDetectorPulse *p)
TDetectorPulse * GetSiR1_1 () const
void SetSiR1_1 (TDetectorPulse *p)
TDetectorPulse * GetSiR1_2 () const
void SetSiR1_2 (TDetectorPulse *p)
TDetectorPulse * GetSiR1_3 () const
void SetSiR1_3 (TDetectorPulse *p)
TDetectorPulse * GetSiR1_4 () const
void SetSiR1_4 (TDetectorPulse *p)
TDetectorPulse * GetSiR1_sum () const
void SetSiR1_sum (TDetectorPulse *p)
TDetectorPulse * GetSiR2 () const
void SetSiR2 (TDetectorPulse *p)
TDetectorPulse * GetMuSc () const
void SetMuSc (TDetectorPulse *p)
TDetectorPulse * GetMuScA () const
void SetMuScA (TDetectorPulse *p)
Private Member Functions
void ResetDetectors ()
Private Attributes
TDetectorPulse * fGe
TDetectorPulse * fLiquidSc
TDetectorPulse * fNDet
TDetectorPulse * fNDet2
TDetectorPulse * fScGe
TDetectorPulse * fScL
TDetectorPulse * fScR
TDetectorPulse * fScVe
TDetectorPulse * fSiL1_1
TDetectorPulse * fSiL1_2
TDetectorPulse * fSiL1_3
TDetectorPulse * fSiL1_4
TDetectorPulse * fSiL2
TDetectorPulse * fSiR1_1
TDetectorPulse * fSiR1_2
TDetectorPulse * fSiR1_3
TDetectorPulse * fSiR1_4
TDetectorPulse * fSiR1_sum
TDetectorPulse * fSiR2
TDetectorPulse * fMuSc
TDetectorPulse * fMuScA
Static Private Attributes
static std::vector< std::string > fDetectorNames
Detailed Description
Definition at line 15 of file TMuonEvent.h.
Constructor & Destructor Documentation
TMuonEvent::TMuonEvent ()
Definition at line 9 of file TMuonEvent.cpp.
References fDetectorNames, and ResetDetectors().
                      {
        // The first muon_event to be created will fill the vector of detector names
        if(fDetectorNames.size() ==0){
                const int num_det_names=21;
                const char* det_names[num_det_names]={
                        "Ge", "LiquidSc", "NDet", "NDet2", "ScGe", "ScL", "ScR",
                        "ScVe", "SiL1_1", "SiL1_2", "SiL1_3", "SiL1_4", "SiL2", "SiR1_1",
                        "SiR1_2", "SiR1_3", "SiR1_4", "SiR1_sum", "SiR2", "MuSc", "MuScA" };
                for(int i=0;i<num_det_names;i++) fDetectorNames.push_back(det_names[i]);
        }
        ResetDetectors();
}
TMuonEvent::~TMuonEvent ()
Definition at line 22 of file TMuonEvent.cpp.
                       {
}
Member Function Documentation
TDetectorPulse* TMuonEvent::GetGe () const [inline]
Definition at line 29 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetLiquidSc () const [inline]
Definition at line 30 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetMuSc () const [inline]
Definition at line 48 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetMuScA () const [inline]
Definition at line 49 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetNDet () const [inline]
Definition at line 31 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetNDet2 () const [inline]
Definition at line 32 of file TMuonEvent.h.
int TMuonEvent::GetNumPulses () const
Definition at line 33 of file TMuonEvent.cpp.
References fDetectorNames, and GetPulse().
Referenced by MaxTimeDiffMEGenerator::ProcessPulses().
{
        int count=0;
        for(size_t i=0;i<fDetectorNames.size();i++){
                if(GetPulse(fDetectorNames[i])) count++;
        }
        return count;
}
TDetectorPulse * TMuonEvent::GetPulse (const std::string & detector) const
Definition at line 44 of file TMuonEvent.cpp.
References GET_DET_IF.
Referenced by GetNumPulses().
{
        if(detector=="") return NULL;
        GET_DET_IF(detector,Ge)
        GET_DET_IF(detector,LiquidSc)
        GET_DET_IF(detector,NDet)
        GET_DET_IF(detector,NDet2)
        GET_DET_IF(detector,ScGe)
        GET_DET_IF(detector,ScL)
        GET_DET_IF(detector,ScR)
        GET_DET_IF(detector,ScVe)
        GET_DET_IF(detector,SiL1_1)
        GET_DET_IF(detector,SiL1_2)
        GET_DET_IF(detector,SiL1_3)
        GET_DET_IF(detector,SiL1_4)
        GET_DET_IF(detector,SiL2)
        GET_DET_IF(detector,SiR1_1)
        GET_DET_IF(detector,SiR1_2)
        GET_DET_IF(detector,SiR1_3)
        GET_DET_IF(detector,SiR1_4)
        GET_DET_IF(detector,SiR1_sum)
        GET_DET_IF(detector,SiR2)
        GET_DET_IF(detector,MuSc)
        GET_DET_IF(detector,MuScA)
        // No detector exists with that name, complain and return NULL
        cout<<"No detector called '"<<detector<<"' exists."<<endl;
        return NULL;
}
TDetectorPulse* TMuonEvent::GetScGe () const [inline]
Definition at line 33 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetScL () const [inline]
Definition at line 34 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetScR () const [inline]
Definition at line 35 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetScVe () const [inline]
Definition at line 36 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetSiL1_1 () const [inline]
Definition at line 37 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetSiL1_2 () const [inline]
Definition at line 38 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetSiL1_3 () const [inline]
Definition at line 39 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetSiL1_4 () const [inline]
Definition at line 40 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetSiL2 () const [inline]
Definition at line 41 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetSiR1_1 () const [inline]
Definition at line 42 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetSiR1_2 () const [inline]
Definition at line 43 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetSiR1_3 () const [inline]
Definition at line 44 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetSiR1_4 () const [inline]
Definition at line 45 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetSiR1_sum () const [inline]
Definition at line 46 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::GetSiR2 () const [inline]
Definition at line 47 of file TMuonEvent.h.
void TMuonEvent::ResetDetectors () [private]
Definition at line 25 of file TMuonEvent.cpp.
References fDetectorNames, and SetPulse().
Referenced by TMuonEvent().
{
   // For now just NULL the pointers, but we need to decide an ownership scheme
   // in which case we may want to delete them as well
   for(size_t i=0;i<fDetectorNames.size();i++){
       SetPulse(fDetectorNames[i],NULL);
   }
}
void TMuonEvent::SetGe (TDetectorPulse * p) [inline]
Definition at line 29 of file TMuonEvent.h.
void TMuonEvent::SetLiquidSc (TDetectorPulse * p) [inline]
Definition at line 30 of file TMuonEvent.h.
void TMuonEvent::SetMuSc (TDetectorPulse * p) [inline]
Definition at line 48 of file TMuonEvent.h.
void TMuonEvent::SetMuScA (TDetectorPulse * p) [inline]
Definition at line 49 of file TMuonEvent.h.
void TMuonEvent::SetNDet (TDetectorPulse * p) [inline]
Definition at line 31 of file TMuonEvent.h.
void TMuonEvent::SetNDet2 (TDetectorPulse * p) [inline]
Definition at line 32 of file TMuonEvent.h.
void TMuonEvent::SetPulse (const std::string & detector, TDetectorPulse * pulse)
Definition at line 76 of file TMuonEvent.cpp.
References SET_DET_IF.
Referenced by MaxTimeDiffMEGenerator::ProcessPulses(), and ResetDetectors().
{
        if(detector=="") return;
        SET_DET_IF(detector , Ge       , pulse)
        SET_DET_IF(detector , LiquidSc , pulse)
        SET_DET_IF(detector , NDet     , pulse)
        SET_DET_IF(detector , NDet2    , pulse)
        SET_DET_IF(detector , ScGe     , pulse)
        SET_DET_IF(detector , ScL      , pulse)
        SET_DET_IF(detector , ScR      , pulse)
        SET_DET_IF(detector , ScVe     , pulse)
        SET_DET_IF(detector , SiL1_1   , pulse)
        SET_DET_IF(detector , SiL1_2   , pulse)
        SET_DET_IF(detector , SiL1_3   , pulse)
        SET_DET_IF(detector , SiL1_4   , pulse)
        SET_DET_IF(detector , SiL2     , pulse)
        SET_DET_IF(detector , SiR1_1   , pulse)
        SET_DET_IF(detector , SiR1_2   , pulse)
        SET_DET_IF(detector , SiR1_3   , pulse)
        SET_DET_IF(detector , SiR1_4   , pulse)
        SET_DET_IF(detector , SiR1_sum , pulse)
        SET_DET_IF(detector , SiR2     , pulse)
        SET_DET_IF(detector , MuSc     , pulse)
        SET_DET_IF(detector , MuScA    , pulse)
        // No detector exists with that name, complain and return NULL
        cout<<"No detector called '"<<detector<<"' exists."<<endl;
        return;
}
void TMuonEvent::SetScGe (TDetectorPulse * p) [inline]
Definition at line 33 of file TMuonEvent.h.
void TMuonEvent::SetScL (TDetectorPulse * p) [inline]
Definition at line 34 of file TMuonEvent.h.
void TMuonEvent::SetScR (TDetectorPulse * p) [inline]
Definition at line 35 of file TMuonEvent.h.
void TMuonEvent::SetScVe (TDetectorPulse * p) [inline]
Definition at line 36 of file TMuonEvent.h.
void TMuonEvent::SetSiL1_1 (TDetectorPulse * p) [inline]
Definition at line 37 of file TMuonEvent.h.
void TMuonEvent::SetSiL1_2 (TDetectorPulse * p) [inline]
Definition at line 38 of file TMuonEvent.h.
void TMuonEvent::SetSiL1_3 (TDetectorPulse * p) [inline]
Definition at line 39 of file TMuonEvent.h.
void TMuonEvent::SetSiL1_4 (TDetectorPulse * p) [inline]
Definition at line 40 of file TMuonEvent.h.
void TMuonEvent::SetSiL2 (TDetectorPulse * p) [inline]
Definition at line 41 of file TMuonEvent.h.
void TMuonEvent::SetSiR1_1 (TDetectorPulse * p) [inline]
Definition at line 42 of file TMuonEvent.h.
void TMuonEvent::SetSiR1_2 (TDetectorPulse * p) [inline]
Definition at line 43 of file TMuonEvent.h.
void TMuonEvent::SetSiR1_3 (TDetectorPulse * p) [inline]
Definition at line 44 of file TMuonEvent.h.
void TMuonEvent::SetSiR1_4 (TDetectorPulse * p) [inline]
Definition at line 45 of file TMuonEvent.h.
void TMuonEvent::SetSiR1_sum (TDetectorPulse * p) [inline]
Definition at line 46 of file TMuonEvent.h.
void TMuonEvent::SetSiR2 (TDetectorPulse * p) [inline]
Definition at line 47 of file TMuonEvent.h.
Member Data Documentation
std::vector< std::string > TMuonEvent::fDetectorNames [static, private]
Definition at line 51 of file TMuonEvent.h.
Referenced by GetNumPulses(), ResetDetectors(), and TMuonEvent().
TDetectorPulse* TMuonEvent::fGe [private]
Definition at line 29 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fLiquidSc [private]
Definition at line 30 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fMuSc [private]
Definition at line 48 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fMuScA [private]
Definition at line 49 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fNDet [private]
Definition at line 31 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fNDet2 [private]
Definition at line 32 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fScGe [private]
Definition at line 33 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fScL [private]
Definition at line 34 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fScR [private]
Definition at line 35 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fScVe [private]
Definition at line 36 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fSiL1_1 [private]
Definition at line 37 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fSiL1_2 [private]
Definition at line 38 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fSiL1_3 [private]
Definition at line 39 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fSiL1_4 [private]
Definition at line 40 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fSiL2 [private]
Definition at line 41 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fSiR1_1 [private]
Definition at line 42 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fSiR1_2 [private]
Definition at line 43 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fSiR1_3 [private]
Definition at line 44 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fSiR1_4 [private]
Definition at line 45 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fSiR1_sum [private]
Definition at line 46 of file TMuonEvent.h.
TDetectorPulse* TMuonEvent::fSiR2 [private]
Definition at line 47 of file TMuonEvent.h.
The documentation for this class was generated from the following files:
rootana/src/TME_generators/TMuonEvent.h
rootana/src/TME_generators/TMuonEvent.cpp