AlcapDAQ: modules::navigator Class Reference
modules::navigator Class Reference
#include <ModulesNavigator.h>
Public Member Functions
int LoadConfigFile (const char *filename)
int MakeModules ()
BaseModule * GetModule (const std::string &module) const
Get a named module.
BaseModule * GetModule (const int &i) const
template<typename T >
T * GetModule (const std::string &module) const
int HowMany (const std::string &name) const
Get the number of instances that the named module has been requested.
bool Before (const std::string &first, const std::string &second) const
modules::iterator Begin ()
Return an iterator to the first module in the list.
modules::const_iterator Begin () const
Return a const iterator to the first module in the list.
modules::iterator End ()
Return an iterator to the last module in the list.
modules::const_iterator End () const
Return a const iterator to the last module in the list.
unsigned int Size () const
Return the number of modules in the list.
unsigned int GetNumModules () const
Return the number of modules in the list.
void SetDebug (bool d=true)
bool Debug () const
bool DumpInputFile () const
void SetOutFile (TFile *file)
Tell the navigator which output file to be used.
Static Public Member Functions
static navigator * Instance ()
Static method to obtain the singleton instance of the navigator.
Private Member Functions
navigator ()
~navigator ()
void AddModule (const std::string &, BaseModule *)
Private Attributes
bool fModulesLoaded
bool fModulesMade
bool fDebug
bool fDumpInputFile
modules::ordered_list fModules
modules::list fModulesSearch
modules::reader fModulesFile
TFile * fOutFile
Detailed Description
Singleton class tasked with:
Storing all modules that have been created
Providing random access to each module
Providing an iterable list of modules for the main event loop
Definition at line 27 of file ModulesNavigator.h.
Constructor & Destructor Documentation
modules::navigator::navigator () [private]
Definition at line 10 of file ModulesNavigator.cpp.
Referenced by Instance().
:fModulesLoaded(false),fModulesMade(false),fDebug(false),fDumpInputFile(false),fOutFile(NULL){};
modules::navigator::~navigator () [inline, private]
Definition at line 30 of file ModulesNavigator.h.
{};
Member Function Documentation
void modules::navigator::AddModule (const std::string & name, BaseModule * mod) [private]
Definition at line 91 of file ModulesNavigator.cpp.
References fModules, and fModulesSearch.
Referenced by MakeModules().
{
    fModules.push_back(std::make_pair(name,mod));
    fModulesSearch.insert(std::make_pair(name,mod));
}
bool modules::navigator::Before (const std::string & first, const std::string & second) const
Returns true if module 'first' is before module 'second' in the modules list
Definition at line 111 of file ModulesNavigator.cpp.
References fModules.
{
    modules::const_iterator i_first= std::find_if(fModules.begin(),fModules.end(),first_in_pair_equals(first));
    if(i_first==fModules.end()){
        cout<<"Error: Unable to find module "<<first<<endl;
        return false;
    }
    modules::const_iterator i_second= std::find_if(fModules.begin(),fModules.end(),first_in_pair_equals(second));
    if(i_second==fModules.end()){
        cout<<"Error: Unable to find module "<<second<<endl;
        return false;
    }
    int dist=std::distance(i_first,i_second);
    return dist>0;
}
modules::const_iterator modules::navigator::Begin () const [inline]
Return a const iterator to the first module in the list.
Definition at line 70 of file ModulesNavigator.h.
References fModules.
{return fModules.begin();};
modules::iterator modules::navigator::Begin () [inline]
Return an iterator to the first module in the list.
Definition at line 68 of file ModulesNavigator.h.
References fModules.
Referenced by LoopSequence::Postprocess(), LoopSequence::Preprocess(), and LoopSequence::Process().
{return fModules.begin();};
bool modules::navigator::Debug () const [inline]
Definition at line 81 of file ModulesNavigator.h.
References fDebug.
Referenced by MakeModules().
{return fDebug;}
bool modules::navigator::DumpInputFile () const [inline]
Definition at line 83 of file ModulesNavigator.h.
References fDumpInputFile.
{return fDumpInputFile;}
modules::const_iterator modules::navigator::End () const [inline]
Return a const iterator to the last module in the list.
Definition at line 74 of file ModulesNavigator.h.
References fModules.
{return fModules.end();};
modules::iterator modules::navigator::End () [inline]
Return an iterator to the last module in the list.
Definition at line 72 of file ModulesNavigator.h.
References fModules.
Referenced by LoopSequence::Postprocess(), LoopSequence::Preprocess(), and LoopSequence::Process().
{return fModules.end();};
template<typename T > T* modules::navigator::GetModule (const std::string & module) const [inline]
Returns:
NULL if the module doesn't exist
modules::BaseModule * modules::navigator::GetModule (const int & i) const [inline]
Get a module by its position in the modules list as specified by the MODULES file.
Returns:
NULL if the module doesn't exist
Definition at line 130 of file ModulesNavigator.h.
References fModules.
{
        return fModules[i].second;
}
T * modules::navigator::GetModule (const std::string & module) const [inline]
Get a named module.
Definition at line 107 of file ModulesNavigator.h.
References fModulesSearch.
{
    modules::list::const_iterator mod=fModulesSearch.find(module.c_str());
    if(mod==fModulesSearch.end()) return NULL;
    return mod->second;
}
unsigned int modules::navigator::GetNumModules () const [inline]
Return the number of modules in the list.
Definition at line 78 of file ModulesNavigator.h.
References fModules.
{return fModules.size();};
int modules::navigator::HowMany (const std::string & name) const
Get the number of instances that the named module has been requested.
Definition at line 96 of file ModulesNavigator.cpp.
References fModulesFile, fModulesMade, fModulesSearch, and modules::reader::HowMany().
{
    if(fModulesMade) return fModulesSearch.count(name);
    return fModulesFile.HowMany(name);
}
modules::navigator * modules::navigator::Instance () [inline, static]
Static method to obtain the singleton instance of the navigator.
Definition at line 102 of file ModulesNavigator.h.
References navigator().
Referenced by BaseModule::BaseModule(), SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), ClearGlobalData(), main(), MakeModules(), LoopSequence::Postprocess(), PrepareSingletonObjects(), LoopSequence::Preprocess(), LoopSequence::Process(), and modules::reader::ProcessGlobalOption().
{
    static modules::navigator* instance=new navigator();
    return instance;
}
int modules::navigator::LoadConfigFile (const char * filename)
read in a modules file, constructing each module and adding it to the list returns 0 on success and non-zero on failure
Definition at line 12 of file ModulesNavigator.cpp.
References modules::reader::DumpInputFile(), fDumpInputFile, fModulesFile, fModulesLoaded, modules::reader::GetNumModules(), and modules::reader::ReadFile().
{
    // Check we haven't already opened a modules file
    if(fModulesLoaded ) {
            cout<<"Error: Loading a new modules file, when one was already loaded"<<endl;
            return 1;
    }
    // Read in the file and dump the processed options
    int retVal=fModulesFile.ReadFile(filename);
    if(retVal!=0) return retVal;
    // check if we were asked to dump the input file's contents
    if(fModulesFile.DumpInputFile()) fDumpInputFile=true;
    // Check the file contained at least one module
    size_t num_modules=fModulesFile.GetNumModules();
    if(num_modules==0){
            cout<<"Warning: No modules were requested for use, so there's nothing to be done!"<<endl;
            return 2;
    }
    cout<<"Number of modules requested: "<<num_modules<<endl;
    // Everything finished ok
    fModulesLoaded=true;
    return 0;
}
int modules::navigator::MakeModules ()
Make all modules that were requested through the modules file Requires that LoadConfigFile has already been called successfully
Definition at line 38 of file ModulesNavigator.cpp.
References AddModule(), TemplateFactory< BaseModule, OptionsType >::canCreate(), TemplateFactory< BaseModule, OptionsType >::createModule(), Debug(), modules::options::DumpOptions(), fModulesFile, fModulesLoaded, fModulesMade, fOutFile, modules::reader::GetModule(), modules::reader::GetNumModules(), modules::reader::GetOptions(), and Instance().
{
    // Check we've been given a valid output file
    if(! (fOutFile && fOutFile->IsWritable()) ){
            cout<<"Error: Output file is not useable"<<endl;
            return 1;
    }
    // Check that we've already opened a modules file
    if(!fModulesLoaded) {
            cout<<"Error: MakeModules(): Cannot make modules until you load a Modules file."<<endl;
            return 1;
    }
    // Check that we've not already called this method
    if(fModulesMade) {
            cout<<"Error: MakeModules(): You've already called MakeModules."<<endl;
            return 1;
    }
    // Loop over each requested module and build it
    // If we have any problems making a module then stop running
    modules::factory* mgr = modules::factory::Instance();
    std::string name;
    modules::options* opts;
    BaseModule* mod=NULL;
    size_t num_modules=fModulesFile.GetNumModules();
    for(unsigned i=0;i<num_modules;i++){
            name = fModulesFile.GetModule(i);
            opts =  fModulesFile.GetOptions(i);
        if(mgr->canCreate(name)){
            if(Debug()){
                cout<<"Creating module: "<<name<<endl;
                cout<<"With options:"<<endl;
                opts->DumpOptions("  ");
            }
            gDirectory->cd("/");
            mod = mgr->createModule(name,opts);
            gDirectory->cd("/");
            if(mod){
                AddModule(name, mod);
            }
            else return 3;
        }else {
            std::cout<<"Unknown module requested: "<<name<<std::endl;
            return 4;
        }
    }
    // Everything finished ok
    fModulesMade=true;
    return 0;
}
void modules::navigator::SetDebug (bool d = true) [inline]
Definition at line 80 of file ModulesNavigator.h.
References fDebug.
Referenced by modules::reader::ProcessGlobalOption().
{fDebug=d;}
void modules::navigator::SetOutFile (TFile * file) [inline]
Tell the navigator which output file to be used.
Definition at line 86 of file ModulesNavigator.h.
References fOutFile.
{fOutFile=file;}
unsigned int modules::navigator::Size () const [inline]
Return the number of modules in the list.
Definition at line 76 of file ModulesNavigator.h.
References fModules.
{return fModules.size();};
Member Data Documentation
bool modules::navigator::fDebug [private]
Definition at line 94 of file ModulesNavigator.h.
Referenced by Debug(), and SetDebug().
bool modules::navigator::fDumpInputFile [private]
Definition at line 95 of file ModulesNavigator.h.
Referenced by DumpInputFile(), and LoadConfigFile().
modules::ordered_list modules::navigator::fModules [private]
Definition at line 96 of file ModulesNavigator.h.
Referenced by AddModule(), Before(), Begin(), End(), GetModule(), GetNumModules(), and Size().
modules::reader modules::navigator::fModulesFile [private]
Definition at line 98 of file ModulesNavigator.h.
Referenced by HowMany(), LoadConfigFile(), and MakeModules().
bool modules::navigator::fModulesLoaded [private]
Definition at line 92 of file ModulesNavigator.h.
Referenced by LoadConfigFile(), and MakeModules().
bool modules::navigator::fModulesMade [private]
Definition at line 93 of file ModulesNavigator.h.
Referenced by HowMany(), and MakeModules().
modules::list modules::navigator::fModulesSearch [private]
Definition at line 97 of file ModulesNavigator.h.
Referenced by AddModule(), GetModule(), and HowMany().
TFile* modules::navigator::fOutFile [private]
Definition at line 99 of file ModulesNavigator.h.
Referenced by MakeModules(), and SetOutFile().
The documentation for this class was generated from the following files:
rootana/src/framework/ModulesNavigator.h
rootana/src/framework/ModulesNavigator.cpp