AlcapDAQ: Normalization Class Reference
Normalization Class Reference
#include <Normalization.h>
Public Member Functions
Normalization (char *HistogramDirectoryName, int threshold)
~Normalization ()
virtual int ProcessEntry (TGlobalData *gData, TSetupData *gSetup)
int ProcessGenericEntry (TGlobalData *gData, TSetupData *gSetup)
virtual int BeforeFirstEntry (TGlobalData *gData, TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, TSetupData *setup)
const char * GetName () const
Static Public Member Functions
static unsigned int GetMuonCount ()
Protected Member Functions
bool Debug () const
Protected Attributes
TDirectory * dir
TSetupData * fSetup
Private Member Functions
bool IsOverThreshold (std::vector< TPulseIsland * >::iterator &)
Private Attributes
unsigned int fNMuons
int fThreshold
Static Private Attributes
static unsigned int N_MU = 0
Detailed Description
Definition at line 11 of file Normalization.h.
Constructor & Destructor Documentation
Normalization::Normalization (char * HistogramDirectoryName, int threshold = 350)
Definition at line 12 of file Normalization.cpp.
References hNumberOfMuons, and N_MU.
                                                                               :
   FillHistBase(HistogramDirectoryName), fNMuons(0), fThreshold(threshold) {
   N_MU = 0;
   hNumberOfMuons = new TH1F("hNumberOfMuons", "hNumberOfMuons", 1,0,1);
   gDirectory->cd("/");
 }
Normalization::~Normalization ()
Definition at line 22 of file Normalization.cpp.
{
 }
Member Function Documentation
virtual int FillHistBase::AfterLastEntry (TGlobalData * gData, TSetupData * setup) inline virtual inherited
Reimplemented in TestModule.
Definition at line 39 of file FillHistBase.h.
 {return 0;};
virtual int FillHistBase::BeforeFirstEntry (TGlobalData * gData, TSetupData * setup) inline virtual inherited
Reimplemented in ExportPulse, MakeAnalysedPulses, MakeDetectorPulses, MakeMuonEvents, and TestModule.
Definition at line 38 of file FillHistBase.h.
 {return 0;};
bool FillHistBase::Debug () const inline protected inherited
Definition at line 45 of file FillHistBase.h.
References FillHistBase::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), TestModule::AfterLastEntry(), TestModule::BeforeFirstEntry(), MakeMuonEvents::BeforeFirstEntry(), MakeDetectorPulses::MakeGenerator(), ExportPulse::MakePlot(), and MakeAnalysedPulses::ProcessEntry().
 {return fDebug;};
unsigned int Normalization::GetMuonCount () static
Definition at line 76 of file Normalization.cpp.
References N_MU.
{
   return N_MU;
 }
const char* FillHistBase::GetName () const inline inherited
Definition at line 40 of file FillHistBase.h.
References FillHistBase::dir.
Referenced by DeadTimeGe::ProcessEntry(), PlotTime::ProcessEntry(), and PlotAmplitude::ProcessEntry().
 {return dir->GetName();};
bool Normalization::IsOverThreshold (std::vector< TPulseIsland * >::iterator & pulse) private
Definition at line 65 of file Normalization.cpp.
References fThreshold, and samples.
Referenced by ProcessEntry().
{
   std::vector<int> samples = (*pulse)->GetSamples();
   static std::vector<int>::iterator iSample;
   for (iSample = samples.begin(); iSample != samples.end(); ++iSample)
     if (*iSample > fThreshold)
       return true;
   return false;
 }
int Normalization::ProcessEntry (TGlobalData * gData, TSetupData * gSetup) virtual
Reimplemented from FillHistBase.
Definition at line 25 of file Normalization.cpp.
References TSetupData::fBankToDetectorMap, fNMuons, TGlobalData::fPulseIslandToChannelMap, hNumberOfMuons, IsOverThreshold(), and N_MU.
{
   // Make sure no other module changed N_MU
   if (N_MU != fNMuons) {
     std::cout << "ERROR: Normalization::N_MU changed unexpectadly!" << std::endl;
     return -1;
   }
   fNMuons = 0;
   // Find the bankname associated with muSc
   std::string bankname = "";
   std::map<std::string, std::string>& B2D = gSetup->fBankToDetectorMap;
   static std::map<std::string, std::string>::iterator iBank;
   for (iBank = B2D.begin(); iBank != B2D.end(); ++iBank) {
     if (iBank->second == "muSc") {
       bankname = iBank->first;
       break;
     }
   }
   // Make certain we found muSc
   if (bankname == "") {
     std::cout << "Warning: Could not find muSc pulses! (TPulseIsland* vector not found, N_MU set to zero)" << std::endl;
     Normalization::N_MU = 0;
     return 0;
   }
   // Count the muons
   std::vector<TPulseIsland*>& pulses = gData->fPulseIslandToChannelMap.at(bankname);
   static std::vector<TPulseIsland*>::iterator iPulse;
   for (iPulse = pulses.begin(); iPulse != pulses.end(); ++iPulse)
     if (IsOverThreshold(iPulse))
       ++fNMuons;
   N_MU = fNMuons;
   hNumberOfMuons->Fill("muons", fNMuons);
   return 0;
 }
int FillHistBase::ProcessGenericEntry (TGlobalData * gData, TSetupData * gSetup) inherited
Definition at line 24 of file FillHistBase.cpp.
References FillHistBase::dir, and FillHistBase::ProcessEntry().
{
   // This is called by our main routine and would allow later to split into different
   // process routines if we have more than one Tree and hence different tpyes of data input.
   if(dir) dir->cd();
   int ret = ProcessEntry(gData, gSetup);
   gDirectory->cd("/");
   return ret;
 }
Field Documentation
TDirectory* FillHistBase::dir protected inherited
Definition at line 40 of file FillHistBase.h.
Referenced by DeadTimeGe::DeadTimeGe(), ExportPulse::ExportPulse(), FillHistBase::FillHistBase(), FillHistBase::GetName(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmplitude::PlotAmplitude(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTime::PlotTime(), and FillHistBase::ProcessGenericEntry().
unsigned int Normalization::fNMuons private
Definition at line 19 of file Normalization.h.
Referenced by ProcessEntry().
TSetupData* FillHistBase::fSetup protected inherited
Definition at line 44 of file FillHistBase.h.
int Normalization::fThreshold private
Definition at line 20 of file Normalization.h.
Referenced by IsOverThreshold().
unsigned int Normalization::N_MU = 0 static private
Definition at line 17 of file Normalization.h.
Referenced by GetMuonCount(), Normalization(), and ProcessEntry().
The documentation for this class was generated from the following files:
analyzer/rootana/src/physics/Normalization.h
analyzer/rootana/src/physics/Normalization.cpp