AlcapDAQ: CFTimeAPGenerator Class Reference
CFTimeAPGenerator Class Reference
#include <CFTimeAPGenerator.h>
Public Member Functions
CFTimeAPGenerator (TAPGeneratorOptions *opts)
virtual ~CFTimeAPGenerator ()
virtual int ProcessPulses (const PulseIslandList &, AnalysedPulseList &)
This method is called on each vector of pulses from a MIDAS event.
virtual bool MayDivideTPIs ()
void SetPulseList (PulseIslandList *list)
template<typename TypeOfTAP >
TypeOfTAP * MakeNewTAP (int parent_index) const
The suggested method for constructing a new TAP.
TAnalysedPulse * MakeNewTAP (int parent_index) const
bool Debug () const
IDs::channel GetChannel () const
const IDs::source & GetSource () const
Get the source id for this generator being used on the current channel.
Static Public Member Functions
static const char * TapType ()
Protected Member Functions
virtual void SetChannel (const std::string &det)
Set the channel for this generator. Should NOT be called by user code.
Private Attributes
Algorithm::ConstantFractionTime fConstantFractionTime
The algorithms that will be used by this generator.
Friends
class MakeAnalysedPulses
Detailed Description
Definition at line 10 of file CFTimeAPGenerator.h.
Constructor & Destructor Documentation
CFTimeAPGenerator::CFTimeAPGenerator (TAPGeneratorOptions * opts)
Definition at line 19 of file CFTimeAPGenerator.cpp.
                                                             :
  TVAnalysedPulseGenerator("CFTimeAPGenerator",opts),
  // Set-up the algorithm in the generator list (it looks a bit messy)
  fConstantFractionTime(SetupNavigator::Instance()->GetPedestal(GetChannel()),
                        TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        TSetupData::Instance()->GetClockTick(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        opts->GetDouble("time_shift", TSetupData::Instance()->GetTimeShift(TSetupData::Instance()->GetBankName(GetChannel().str()))),
                        opts->GetDouble("constant_fraction", -0.10)
                        ) {
}
virtual CFTimeAPGenerator::~CFTimeAPGenerator () [inline, virtual]
Definition at line 14 of file CFTimeAPGenerator.h.
{};
Member Function Documentation
bool TVAnalysedPulseGenerator::Debug () const [inline, inherited]
Definition at line 82 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fDebug.
Referenced by GaussFitAPGenerator::FitPulse(), TemplateConvolveAPGenerator::ProcessPulses(), and IntegralRatioAPGenerator::ProcessPulses().
{return fDebug;};
IDs::channel TVAnalysedPulseGenerator::GetChannel () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 86 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), and TVAnalysedPulseGenerator::fSource.
Referenced by FirstCompleteAPGenerator::DrawPulse(), FirstCompleteAPGenerator::FirstCompleteAPGenerator(), IntegralRatioAPGenerator::ProcessPulses(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), and TemplateFitAPGenerator::TemplateFitAPGenerator().
{return fSource.Channel();};
const IDs::source& TVAnalysedPulseGenerator::GetSource () const [inline, inherited]
Get the source id for this generator being used on the current channel.
Useful for a generator to know the full source much like in the above GetChannel method, but this could also be useful for checking that this generator is the one that made a given TAP in later analysis by comparing this value to that stored in the TAP itself.
Definition at line 95 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fSource.
Referenced by TVAnalysedPulseGenerator::MakeNewTAP(), and IntegralRatioAPGenerator::ProcessPulses().
{return fSource;};
TAnalysedPulse* TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
Definition at line 78 of file TVAnalysedPulseGenerator.h.
{
            return MakeNewTAP<TAnalysedPulse>(parent_index);
        }
template<typename TypeOfTAP > TypeOfTAP * TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
The suggested method for constructing a new TAP.
In the process of constructing TAP, information that isn't immediately obvious how to get needs to be passed to TAP. This method returns a pointer to a TAP construced for you, and all you need to pass it is the TPulseIslandID.
In the case where a generator wants to add extra information to the standard TAP information, we expect people to derive from TAnalysedPulse. If your generator is one of these, then use the template argument to produce the type of TAP you desire. Note that this forces the constructor of the specialised TAP to be the same as for TAnalysedPulse itself.
For example, for to make a specialied analysed pulse called TSpecialAnalysedPulse (original, huh?) you would do:
 TSpecialAnalysedPulse* tsap=MakeNewTAP<TSpecialAnalysedPulse>(parent_index);
Parameters:
[in] parent_index The TPulseIslandID of the TPI being used to make the new TAP.
Template Parameters:
in] TypeOfTAP The type of specialisation of TAnalysedPulse that you want to create.
Definition at line 125 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList, and TVAnalysedPulseGenerator::GetSource().
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), SimpIntAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), CFTimeMBAmpAPGenerator::ProcessPulses(), and ProcessPulses().
{
    TypeOfTAP* pulse=NULL;
    TPulseIsland* parent = fPulseList->at(parent_index);
    pulse=new TypeOfTAP(GetSource(),parent_index,parent);
    return pulse;
}
virtual bool CFTimeAPGenerator::MayDivideTPIs () [inline, virtual]
Todo:
Document this
Implements TVAnalysedPulseGenerator.
Definition at line 21 of file CFTimeAPGenerator.h.
{return true;};
int CFTimeAPGenerator::ProcessPulses (const PulseIslandList & pil, AnalysedPulseList & apl) [virtual]
This method is called on each vector of pulses from a MIDAS event.
Parameters:
[in] pil The vector of TPIs to produce TAPs from.
[out] apl The vector of TAPs to append the new TAPs to.
Implements TVAnalysedPulseGenerator.
Definition at line 31 of file CFTimeAPGenerator.cpp.
References fConstantFractionTime, TVAnalysedPulseGenerator::MakeNewTAP(), and TAnalysedPulse::SetTime().
{
  for (unsigned int iTPI = 0; iTPI < pulseList.size(); ++iTPI) {
    TPulseIsland* tpi = pulseList.at(iTPI);
    double time = fConstantFractionTime(tpi);
    TAnalysedPulse* tap = MakeNewTAP(iTPI);
    tap->SetTime(time);
    analysedList.push_back(tap);
  }
  return 0;
}
virtual void TVAnalysedPulseGenerator::SetChannel (const std::string & det) [inline, protected, virtual, inherited]
Set the channel for this generator. Should NOT be called by user code.
Called by MakeAnalysedPulses to tell this generator what channel it is looking at.
Definition at line 107 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), and TVAnalysedPulseGenerator::fSource.
Referenced by TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{fSource.Channel()=det;};
void TVAnalysedPulseGenerator::SetPulseList (PulseIslandList * list) [inline, inherited]
Definition at line 49 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList.
{fPulseList=list;};
static const char* TVAnalysedPulseGenerator::TapType () [inline, static, inherited]
Reimplemented in GaussFitAPGenerator, IntegralRatioAPGenerator, TemplateConvolveAPGenerator, and TemplateFitAPGenerator.
Definition at line 97 of file TVAnalysedPulseGenerator.h.
{return TAnalysedPulse::Class()->GetName();}
Friends And Related Function Documentation
friend class MakeAnalysedPulses [friend, inherited]
Definition at line 100 of file TVAnalysedPulseGenerator.h.
Member Data Documentation
Algorithm::ConstantFractionTime CFTimeAPGenerator::fConstantFractionTime [private]
The algorithms that will be used by this generator.
Definition at line 21 of file CFTimeAPGenerator.h.
Referenced by ProcessPulses().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/CFTimeAPGenerator.h
rootana/src/TAP_generators/CFTimeAPGenerator.cpp