AlcapDAQ: PulseEstimate Class Reference
PulseEstimate Class Reference
[Odbcheck]
Estimates corrections for certian ODB values.
#include <PulseEstimate.hh>
Public Member Functions
PulseEstimate ()
Default constructor.
void Estimate (TH2 *pulses, TH1 *timing)
Getters
int GetPedestal () const
int GetPolarity () const
int GetOffset () const
Private Attributes
int fPedestal
int fPolarity
int fOffset
Detailed Description
Estimates corrections for certian ODB values.
PulseEstimate takes data quality histograms from an alcapana production and predicts what certain ODB values are. These are the pedestal, polarity, and timing offset.
Definition at line 17 of file PulseEstimate.hh.
Constructor & Destructor Documentation
PulseEstimate::PulseEstimate ()
Default constructor.
Definition at line 8 of file PulseEstimate.cc.
: fPedestal(0), fPolarity(1), fOffset(0) {}
Member Function Documentation
void PulseEstimate::Estimate (TH2 * pulses, TH1 * timing)
Estimate ODB values based on data quality histograms.
Parameters:
[in] pulses The shapes (persistance) histogram.
[in] timing The muSc timeing difference histogram.
Definition at line 10 of file PulseEstimate.cc.
References fOffset, fPedestal, fPolarity, and nPreSamples.
Referenced by ODBCheck::Check().
{
  /* Get pedestal and polarity */
  if (pulses && pulses->GetEntries()) {
    int nPreSamples = 10; // Number of presamples to project
    // Project out first few samples to get pedestal
    // Project everything to get polarity
    TH1* pulses_proj_ped = pulses->ProjectionY("_ped", 1, nPreSamples);
    TH1* pulses_proj_pol = pulses->ProjectionY("_pol");
    /* Get pedestal */
    // First reduce range slightly; specifically Ge preamp reset caused flatlining
    // We want to miss underflow/overflow due to this
    static const int nBinsIgnore = 5; // This number is arbitrary. Logically it should be 1, maybe 2, but 5 can't hurt
    int nbins = pulses_proj_ped->GetXaxis()->GetNbins();
    pulses_proj_ped->GetXaxis()->SetRange(nBinsIgnore, nbins - nBinsIgnore);
    // Get the pedestal
    fPedestal = (int)pulses_proj_ped->GetBinCenter(pulses_proj_ped->GetMaximumBin());
    // Reset bin range
    pulses_proj_ped->GetXaxis()->SetRange();
    /* Get polarity */
    int min = 0, max = 0;
    bool min_found = false, max_found = false;
    // Again, ignore 5 bin on each side to get rid of flatlines
    for (int i = nBinsIgnore; i <= nbins - nBinsIgnore; ++i) {
      if (!min_found && pulses_proj_pol->GetBinContent(i) > 0.) {
        min_found = true;
        min = i;
      }
      if (!max_found && pulses_proj_pol->GetBinContent(nbins - i) > 0.) {
        max_found = true;
        max = nbins - i;
      }
      if (min_found && max_found)
        break;
    }
    if (max - fPedestal > fPedestal - min)
      fPolarity = 1;
    else
      fPolarity = -1;
  } else {
    // If no pulses, default to positive polarity and zero pedestal
    std::cout << "PulseEstimate ERROR: Cannot estimate nonexistent or empty shapes histogram!" << std::endl;
    fPedestal = 0;
    fPolarity = 1;
  }
  /* Get Timing */
  // Rebin until we have plenty of samples at the peak
  if (timing && timing->GetEntries()) {
    int nRebins = 0;
    static int min_time_correlation_height = 10;
    while (timing->GetBinContent(timing->GetMaximumBin()) < min_time_correlation_height && nRebins++ < 3)
      timing->Rebin();
    fOffset = timing->GetBinCenter(timing->GetMaximumBin());
  } else {
    // If no timing, default to zero offset
    std::cout << "PulseEstimate ERROR: Cannot estimate nonexistent or empty timing histogram!" << std::endl;
    fOffset = 0;
  }
}
int PulseEstimate::GetOffset () const
Returns:
Estimated timing offset (TimeShift)
Definition at line 80 of file PulseEstimate.cc.
References fOffset.
Referenced by ODBCheck::Check().
{
  return fOffset;
}
int PulseEstimate::GetPedestal () const
Returns:
Estimated pedestal
Definition at line 72 of file PulseEstimate.cc.
References fPedestal.
Referenced by ODBCheck::Check().
{
  return fPedestal;
}
int PulseEstimate::GetPolarity () const
Returns:
Estimated polarity
Definition at line 76 of file PulseEstimate.cc.
References fPolarity.
Referenced by ODBCheck::Check().
{
  return fPolarity;
}
Member Data Documentation
int PulseEstimate::fOffset [private]
The estimated timing offset from the muSc time difference histograms. The bin containing the peak is used.
Definition at line 33 of file PulseEstimate.hh.
Referenced by Estimate(), and GetOffset().
int PulseEstimate::fPedestal [private]
Estimateed pedestal from the Y projection of the first few (10) bins of the shapes (persistance) histogram. The bin containing the peak is considered the pedestal.
Definition at line 23 of file PulseEstimate.hh.
Referenced by Estimate(), and GetPedestal().
int PulseEstimate::fPolarity [private]
Estimated polarity from fPedestal and the Y projection of the entire shapes histogram. The non-zero bin that is farthest from the peak determines the polarity. Whichever is farther indicates the polarity of the pulse. The first and last 5 bins are ignored so that problems with certain detectors (premplifier reset in the germanium) don't interfere.
Definition at line 30 of file PulseEstimate.hh.
Referenced by Estimate(), and GetPolarity().
The documentation for this class was generated from the following files:
odb_check/include/PulseEstimate.hh
odb_check/src/PulseEstimate.cc