AlcapDAQ: PlotTDiff Class Reference
PlotTDiff Class Reference
[Modules]
A one line description of what your module does.
#include <PlotTDiff.h>
Public Member Functions
PlotTDiff (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~PlotTDiff ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
Protected Attributes
TDirectory * dir
Private Types
typedef std::vector< IDs::source > SourceVector
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Private Attributes
std::string fDetNameA
Don't forget to forget descirptions for each field...
std::string fDetNameB
std::map< std::string, TH2F * > intA_plots
std::map< std::string, TH2F * > intB_plots
std::map< std::string, TH2F * > ampA_plots
std::map< std::string, TH2F * > ampB_plots
std::map< std::string, TH2F * > fine_plots
std::map< std::string, TH1F * > oned_plots
SourceVector fDetASources
SourceVector fDetBSources
Detailed Description
A one line description of what your module does.
Author:
AuthorName
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 26 of file PlotTDiff.h.
Member Typedef Documentation
typedef std::vector<IDs::source> PlotTDiff::SourceVector [private]
Definition at line 27 of file PlotTDiff.h.
Constructor & Destructor Documentation
PlotTDiff::PlotTDiff (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 28 of file PlotTDiff.cpp.
References fDetNameA, fDetNameB, and modules::options::GetString().
                                        :
    BaseModule("PlotTDiff",opts){
        fDetNameA = opts->GetString("det1");
        fDetNameB = opts->GetString("det2");
    }
PlotTDiff::~PlotTDiff ()
Is anything done in the destructor?
Definition at line 36 of file PlotTDiff.cpp.
                     {
}
Member Function Documentation
int PlotTDiff::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::AfterLastEntry
[in] setup See BaseModule::AfterLastEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 196 of file PlotTDiff.cpp.
{
    return 0;
}
int PlotTDiff::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::BeforeFirstEntry
[in] setup See BaseModule::BeforeFirstEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 41 of file PlotTDiff.cpp.
References fDetASources, fDetBSources, fDetNameA, fDetNameB, and gAnalysedPulseMap.
{
    //call my source finders and build histogram for each source with
    //a time component.
    //should I continue to work on just two? or should I have this loop
    //through all pairs
    for(SourceAnalPulseMap::const_iterator sourceIt = gAnalysedPulseMap.begin();
            sourceIt != gAnalysedPulseMap.end(); sourceIt++) {
        //std::string fBankNameB = setup->GetBank(fDetNameB);
        if( sourceIt->first.Channel() != fDetNameA) {
            cout << sourceIt->first.Channel() << "   " << fDetNameA << endl;
            continue;   //check for detector A
        }
        //I need to check that this source generates a time
        AnalysedPulseList pulses = sourceIt->second;
        for(SourceAnalPulseMap::const_iterator sourceIt2 = gAnalysedPulseMap.begin(); sourceIt2 != gAnalysedPulseMap.end(); sourceIt2++)
        {
            if(sourceIt2->first.Channel() != fDetNameB)
                continue;  //check for detector B
            if(sourceIt2->first.Generator() != sourceIt->first.Generator())
                continue;  //make sure they have the same generator
            //I should make a vector of the sources for detA and detB
            fDetASources.push_back(sourceIt->first);
            fDetBSources.push_back(sourceIt2->first);
        }
    }
    return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), TemplateCreator::AddPulseToTemplate(), ExportPulse::AddToExportList(), TemplateCreator::AfterLastEntry(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotPedestalAndNoise::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeMuonEvents::BeforeFirstEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotPedestalAndNoise::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), and PulseViewer::ProcessEntry().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by SavePulses::AfterLastEntry(), and PlotTDPs::BeforeFirstEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTime::ProcessEntry(), PlotAmplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int PlotTDiff::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::ProcessEntry
[in] gSetup See BaseModule::ProcessEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 77 of file PlotTDiff.cpp.
References ampA_plots, ampB_plots, definitions::DefaultValue, fDetASources, fDetBSources, fDetNameA, fDetNameB, gAnalysedPulseMap, TSetupData::GetBankName(), TSetupData::GetNBits(), intA_plots, intB_plots, and oned_plots.
{
    for(SourceVector::const_iterator sourceIt = fDetASources.begin(); sourceIt != fDetASources.end(); sourceIt++)
    {
        const AnalysedPulseList& detAPulses = gAnalysedPulseMap[*sourceIt];
        //Get DetB pulses for the same Generator
        for(SourceVector::const_iterator sourceIt2 = fDetBSources.begin();
                sourceIt2 != fDetBSources.end(); sourceIt2++){
            // only compare sources with the same generator
            if((*sourceIt2).Generator() != (*sourceIt).Generator()) continue;
            const AnalysedPulseList& detBPulses = gAnalysedPulseMap[*sourceIt2];
            //now I should build my histograms, need some keyname(source1?)
            //std::string keyname = sourceIt;
            std::string keyname =  sourceIt->str();
            int nBits = setup->GetNBits(setup->GetBankName(fDetNameA));
            int maxAmpA = std::pow(2, nBits);
            nBits = setup->GetNBits(setup->GetBankName(fDetNameB));
            int maxAmpB = std::pow(2, nBits);
            //if histogram does not exist, make histograms (amp and/or int, or 1D)
            if((ampA_plots.find(keyname) == ampA_plots.end()) ) {
                //ampA plots
                std::string histname = "h" + fDetNameB + "_" + keyname + "TDiff_AmpA";
                std::string histtitle = "Amplitude of " + fDetNameA
                    + " vs time difference with " + fDetNameB + " detectors with the "
                    + (*sourceIt).Generator().str() + " generator";
                TH2F* AAplots = new TH2F(histname.c_str(), histtitle.c_str(), 200, -10000, 10000, 200, 0, maxAmpA);
                AAplots->GetXaxis()->SetTitle("Time Difference (ns)");
                AAplots->GetYaxis()->SetTitle("Amplitude (ADC counts)");
                ampA_plots[keyname] = AAplots;
                //ampB plots
                histname = "h" + fDetNameB + "_" + keyname + " TDiff_AmpB";
                histtitle = "Amplitude of " + fDetNameB
                    + " vs time difference with " + fDetNameA + " detectors with the "
                    + (*sourceIt).Generator().str() + " generator";
                TH2F* ABplots = new TH2F(histname.c_str(), histtitle.c_str(), 200, -10000, 10000, 200, 0, maxAmpB);
                ABplots->GetXaxis()->SetTitle("Time Difference (ns)");
                ABplots->GetYaxis()->SetTitle("Amplitude (ADC counts)");
                ampB_plots[keyname] = ABplots;
            }
            if(intA_plots.find(keyname) == intA_plots.end() ) {
                //intA plots
                std::string histname = "h" + fDetNameB + "_" + keyname + " TDiff_IntA";
                std::string histtitle = "Integral of " + fDetNameA + " vs time difference with " + fDetNameB + " detectors with the " + (*sourceIt).Generator().str() + " generator";
                TH2F* IAplots = new TH2F(histname.c_str(), histtitle.c_str(), 200, -10000, 10000, 200, 0, 5*maxAmpA);
                IAplots->GetXaxis()->SetTitle("Time Difference (ns)");
                IAplots->GetYaxis()->SetTitle("Integral (ADC counts)");
                intA_plots[keyname] = IAplots;
                //intB plots
                histname = "h" + fDetNameB + "_" + keyname + " TDiff_IntB";
                histtitle = "Integral of " + fDetNameB + " vs time difference with " + fDetNameA + " detectors with the " + (*sourceIt).Generator().str() + " generator";
                TH2F* IBplots = new TH2F(histname.c_str(), histtitle.c_str(), 200, -10000, 10000, 200, 0, 5*maxAmpB);
                IBplots->GetXaxis()->SetTitle("Time Difference (ns)");
                IBplots->GetYaxis()->SetTitle("Integral (ADC counts)");
                intB_plots[keyname] = IBplots;
            }
            if(oned_plots.find(keyname) == oned_plots.end()) {
                std::string histname = "h" + fDetNameB + "_" + keyname + "TDiff_1D";
                std::string histtitle = "Time difference between  " + fDetNameA + " and " + fDetNameB + " detectors with the " + (*sourceIt).Generator().str() + " generator";
                TH1F* dplots = new TH1F(histname.c_str(), histtitle.c_str(), 500, -10000, 10000);
                dplots->GetXaxis()->SetTitle("Time Difference (ns)");
                dplots->GetYaxis()->SetTitle("Count");
                oned_plots[keyname] = dplots;
            }
            for(AnalysedPulseList::const_iterator pulseIt = detAPulses.begin();
                    pulseIt != detAPulses.end(); ++pulseIt) {
                for(AnalysedPulseList::const_iterator pulseIt2 = detBPulses.begin();
                        pulseIt2 != detBPulses.end(); ++pulseIt2) {
                    double timeA = (*pulseIt)->GetTime(), timeB = (*pulseIt2)->GetTime();
                    double tDiff = timeA - timeB;
                    double ampA = (*pulseIt)->GetAmplitude(), ampB = (*pulseIt2)->GetAmplitude();
                    double intA = (*pulseIt)->GetIntegral(), intB = (*pulseIt2)->GetIntegral();
                    if(ampA != definitions::DefaultValue)
                    {
                        ampA_plots[keyname]->Fill(tDiff, ampA);
                        ampB_plots[keyname]->Fill(tDiff, ampB);
                    }
                    if(intA != definitions::DefaultValue)
                    {
                        intA_plots[keyname]->Fill(tDiff, intA);
                        intB_plots[keyname]->Fill(tDiff, intB);
                    }
                    if((intA == definitions::DefaultValue) && (ampA ==definitions::DefaultValue))
                        oned_plots[keyname]->Fill(tDiff);
                }//end detBPulse loop
            }//end detAPulse loop
        }//end sourceIt2 loop
    }//end sourceIt loop
    return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
std::map<std::string, TH2F*> PlotTDiff::ampA_plots [private]
Definition at line 72 of file PlotTDiff.h.
Referenced by ProcessEntry().
std::map<std::string, TH2F*> PlotTDiff::ampB_plots [private]
Definition at line 72 of file PlotTDiff.h.
Referenced by ProcessEntry().
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 97 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), ExportPulse::ExportPulse(), FastSlowCompare::FastSlowCompare(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
SourceVector PlotTDiff::fDetASources [private]
Definition at line 75 of file PlotTDiff.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
SourceVector PlotTDiff::fDetBSources [private]
Definition at line 75 of file PlotTDiff.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
std::string PlotTDiff::fDetNameA [private]
Don't forget to forget descirptions for each field...
...and don't hesitate to include details.
Definition at line 70 of file PlotTDiff.h.
Referenced by BeforeFirstEntry(), PlotTDiff(), and ProcessEntry().
std::string PlotTDiff::fDetNameB [private]
Definition at line 70 of file PlotTDiff.h.
Referenced by BeforeFirstEntry(), PlotTDiff(), and ProcessEntry().
std::map<std::string, TH2F*> PlotTDiff::fine_plots [private]
Definition at line 72 of file PlotTDiff.h.
std::map<std::string, TH2F*> PlotTDiff::intA_plots [private]
Definition at line 72 of file PlotTDiff.h.
Referenced by ProcessEntry().
std::map<std::string, TH2F*> PlotTDiff::intB_plots [private]
Definition at line 72 of file PlotTDiff.h.
Referenced by ProcessEntry().
std::map<std::string, TH1F*> PlotTDiff::oned_plots [private]
Definition at line 74 of file PlotTDiff.h.
Referenced by ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/plotters/PlotTDiff.h
rootana/src/plotters/PlotTDiff.cpp