AlcapDAQ: tut::test_group< Data, MaxTestsInGroup > Class Template Reference
tut::test_group< Data, MaxTestsInGroup > Class Template Reference
#include <tut.h>
Data Structures
class safe_holder
Public Types
typedef test_object< Data > object
Public Member Functions
test_group (const char *name, groupfinalization final=NULL)
test_group (const char *name, test_runner &another_runner)
void reg (int n, testmethod tm)
void rewind ()
test_result run_next ()
test_result run_test (int n)
void group_completed ()
Private Types
typedef void(test_object< Data >::* testmethod)()
typedef std::map< int, testmethod > tests
typedef tests::iterator tests_iterator
typedef tests::const_iterator tests_const_iterator
typedef
tests::const_reverse_iterator tests_const_reverse_iterator
typedef tests::size_type size_type
typedef void(* groupfinalization)()
Private Member Functions
test_result run_test_ (const tests_iterator &ti, safe_holder< object > &obj)
bool run_test_seh_ (testmethod tm, safe_holder< object > &obj)
void reset_holder_ (safe_holder< object > &obj)
Private Attributes
const char * name_
tests tests_
tests_iterator current_test_
groupfinalization group_finalization_
Detailed Description
template<class Data, int MaxTestsInGroup = 50>
class tut::test_group< Data, MaxTestsInGroup >
Test group; used to recreate test object instance for each new test since we have to have reinitialized Data base class.
Definition at line 603 of file tut.h.
Member Typedef Documentation
template<class Data , int MaxTestsInGroup = 50> typedef void(* tut::test_group< Data, MaxTestsInGroup >::groupfinalization)() [private]
Definition at line 615 of file tut.h.
template<class Data , int MaxTestsInGroup = 50> typedef test_object<Data> tut::test_group< Data, MaxTestsInGroup >::object
Definition at line 720 of file tut.h.
template<class Data , int MaxTestsInGroup = 50> typedef tests::size_type tut::test_group< Data, MaxTestsInGroup >::size_type [private]
Definition at line 613 of file tut.h.
template<class Data , int MaxTestsInGroup = 50> typedef void(test_object<Data>::* tut::test_group< Data, MaxTestsInGroup >::testmethod)() [private]
Definition at line 607 of file tut.h.
template<class Data , int MaxTestsInGroup = 50> typedef std::map<int,testmethod> tut::test_group< Data, MaxTestsInGroup >::tests [private]
Definition at line 608 of file tut.h.
template<class Data , int MaxTestsInGroup = 50> typedef tests::const_iterator tut::test_group< Data, MaxTestsInGroup >::tests_const_iterator [private]
Definition at line 610 of file tut.h.
template<class Data , int MaxTestsInGroup = 50> typedef tests::const_reverse_iterator tut::test_group< Data, MaxTestsInGroup >::tests_const_reverse_iterator [private]
Definition at line 612 of file tut.h.
template<class Data , int MaxTestsInGroup = 50> typedef tests::iterator tut::test_group< Data, MaxTestsInGroup >::tests_iterator [private]
Definition at line 609 of file tut.h.
Constructor & Destructor Documentation
template<class Data , int MaxTestsInGroup = 50> tut::test_group< Data, MaxTestsInGroup >::test_group (const char * name, groupfinalization final = NULL) [inline]
Creates and registers test group with specified name.
Definition at line 725 of file tut.h.
References tut::test_runner_singleton::get(), tut::test_group< Data, MaxTestsInGroup >::name_, tut::test_group< Data, MaxTestsInGroup >::reg(), tut::test_runner::register_group(), and tut::runner.
      : name_(name), group_finalization_(final)
    {
      // register itself
      runner.get().register_group(name_,this);
      // register all tests
      tests_registerer<object,test_group,MaxTestsInGroup>::reg(*this);
    };
template<class Data , int MaxTestsInGroup = 50> tut::test_group< Data, MaxTestsInGroup >::test_group (const char * name, test_runner & another_runner) [inline]
This constructor is used in self-test run only.
Definition at line 738 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::name_, tut::test_group< Data, MaxTestsInGroup >::reg(), and tut::test_runner::register_group().
      : name_(name), group_finalization_(NULL)
    {
      // register itself
      another_runner.register_group(name_,this);
      // register all tests
      tests_registerer<test_object<Data>,
                       test_group,MaxTestsInGroup>::reg(*this);
    };
Member Function Documentation
template<class Data , int MaxTestsInGroup = 50> void tut::test_group< Data, MaxTestsInGroup >::group_completed () [inline, virtual]
Implements tut::group_base.
Definition at line 809 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::group_finalization_.
{
      if (group_finalization_ != NULL) group_finalization_();
    }
template<class Data , int MaxTestsInGroup = 50> void tut::test_group< Data, MaxTestsInGroup >::reg (int n, testmethod tm) [inline]
Registers test method under given number.
Definition at line 752 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::tests_.
Referenced by tut::test_group< Data, MaxTestsInGroup >::test_group().
    {
      tests_[n] = tm;
    }
template<class Data , int MaxTestsInGroup = 50> void tut::test_group< Data, MaxTestsInGroup >::reset_holder_ (safe_holder< object > & obj) [inline, private]
Definition at line 918 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::reset().
Referenced by tut::test_group< Data, MaxTestsInGroup >::run_test_seh_().
    {
      try
      {
        obj.reset();
      }
      catch(const std::exception& ex)
      {
        throw bad_ctor(ex.what());
      }
      catch(...)
      {
        throw bad_ctor("test constructor has generated an exception; group execution is terminated");
      }
    }
template<class Data , int MaxTestsInGroup = 50> void tut::test_group< Data, MaxTestsInGroup >::rewind () [inline, virtual]
Reset test position before first test.
Implements tut::group_base.
Definition at line 760 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::current_test_, and tut::test_group< Data, MaxTestsInGroup >::tests_.
    {
      current_test_ = tests_.begin();
    }
template<class Data , int MaxTestsInGroup = 50> test_result tut::test_group< Data, MaxTestsInGroup >::run_next () [inline, virtual]
Runs next test.
Implements tut::group_base.
Definition at line 768 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::current_test_, tut::test_group< Data, MaxTestsInGroup >::run_test_(), and tut::test_group< Data, MaxTestsInGroup >::tests_.
    {
      if( current_test_ == tests_.end() )
      {
        throw no_more_tests();
      }
      // find next user-specialized test
      safe_holder<object> obj;
      while( current_test_ != tests_.end() )
      {
        try
        {
          return run_test_(current_test_++,obj);
        }
        catch( const no_such_test& )
        {
          continue;
        }
      }
      throw no_more_tests();
    }
template<class Data , int MaxTestsInGroup = 50> test_result tut::test_group< Data, MaxTestsInGroup >::run_test (int n) [inline, virtual]
Runs one test by position.
Implements tut::group_base.
Definition at line 795 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::run_test_(), and tut::test_group< Data, MaxTestsInGroup >::tests_.
    {
      // beyond tests is special case to discover upper limit
      if( tests_.rbegin() == tests_.rend() ) throw beyond_last_test();
      if( tests_.rbegin()->first < n ) throw beyond_last_test();
      // withing scope; check if given test exists
      tests_iterator ti = tests_.find(n);
      if( ti == tests_.end() ) throw no_such_test();
      safe_holder<object> obj;
      return run_test_(ti,obj);
    }
template<class Data , int MaxTestsInGroup = 50> test_result tut::test_group< Data, MaxTestsInGroup >::run_test_ (const tests_iterator & ti, safe_holder< object > & obj) [inline, private]
VC allows only one exception handling type per function, so I have to split the method
Definition at line 818 of file tut.h.
References tut::test_result::ex, tut::test_result::ex_ctor, tut::test_result::fail, tut::test_group< Data, MaxTestsInGroup >::name_, tut::test_result::ok, tut::test_group< Data, MaxTestsInGroup >::run_test_seh_(), tut::test_result::term, and tut::test_result::warn.
Referenced by tut::test_group< Data, MaxTestsInGroup >::run_next(), and tut::test_group< Data, MaxTestsInGroup >::run_test().
    {
      try
      {
        if( run_test_seh_(ti->second,obj) == false )
          throw seh("seh");
      }
      catch(const no_such_test&)
      {
        throw;
      }
      catch(const warning& ex)
      {
        // test ok, but destructor failed
        test_result tr(name_,ti->first,test_result::warn,ex);
        return tr;
      }
      catch(const failure& ex)
      {
        // test failed because of ensure() or similar method
        test_result tr(name_,ti->first,test_result::fail,ex);
        return tr;
      }
      catch(const seh& ex)
      {
        // test failed with sigsegv, divide by zero, etc
        test_result tr(name_,ti->first,test_result::term,ex);
        return tr;
      }
      catch(const bad_ctor& ex)
      {
        // test failed because test ctor failed; stop the whole group
        test_result tr(name_,ti->first,test_result::ex_ctor,ex);
        return tr;
      }
      catch(const std::exception& ex)
      {
        // test failed with std::exception
        test_result tr(name_,ti->first,test_result::ex,ex);
        return tr;
      }
      catch(...)
      {
        // test failed with unknown exception
        test_result tr(name_,ti->first,test_result::ex);
        return tr;
      }
      // test passed
      test_result tr(name_,ti->first,test_result::ok);
      return tr;
    }
template<class Data , int MaxTestsInGroup = 50> bool tut::test_group< Data, MaxTestsInGroup >::run_test_seh_ (testmethod tm, safe_holder< object > & obj) [inline, private]
Runs one under SEH if platform supports it.
Definition at line 874 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::get(), tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::permit_throw(), tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::release(), and tut::test_group< Data, MaxTestsInGroup >::reset_holder_().
Referenced by tut::test_group< Data, MaxTestsInGroup >::run_test_().
    {
#if defined(TUT_USE_SEH)
      __try
      {
#endif
        if( obj.get() == 0 )
        {
          reset_holder_(obj);
        }
        obj->called_method_was_a_dummy_test_ = false;
#if defined(TUT_USE_SEH)
        __try
        {
#endif
          (obj.get()->*tm)();
#if defined(TUT_USE_SEH)
        }
        __except(handle_seh_(::GetExceptionCode()))
        {
          // throw seh("SEH");
          return false;
        }
#endif
        if( obj->called_method_was_a_dummy_test_ )
        {
          // do not call obj.release(); reuse object
          throw no_such_test();
        }
        obj.permit_throw();
        obj.release();
#if defined(TUT_USE_SEH)
      }
      __except(handle_seh_(::GetExceptionCode()))
      {
        return false;
      }
#endif
      return true;
    }
Field Documentation
template<class Data , int MaxTestsInGroup = 50> tests_iterator tut::test_group< Data, MaxTestsInGroup >::current_test_ [private]
Definition at line 618 of file tut.h.
Referenced by tut::test_group< Data, MaxTestsInGroup >::rewind(), and tut::test_group< Data, MaxTestsInGroup >::run_next().
template<class Data , int MaxTestsInGroup = 50> groupfinalization tut::test_group< Data, MaxTestsInGroup >::group_finalization_ [private]
Definition at line 619 of file tut.h.
Referenced by tut::test_group< Data, MaxTestsInGroup >::group_completed().
template<class Data , int MaxTestsInGroup = 50> const char* tut::test_group< Data, MaxTestsInGroup >::name_ [private]
Definition at line 605 of file tut.h.
Referenced by tut::test_group< Data, MaxTestsInGroup >::run_test_(), and tut::test_group< Data, MaxTestsInGroup >::test_group().
template<class Data , int MaxTestsInGroup = 50> tests tut::test_group< Data, MaxTestsInGroup >::tests_ [private]
Definition at line 617 of file tut.h.
Referenced by tut::test_group< Data, MaxTestsInGroup >::reg(), tut::test_group< Data, MaxTestsInGroup >::rewind(), tut::test_group< Data, MaxTestsInGroup >::run_next(), and tut::test_group< Data, MaxTestsInGroup >::run_test().
The documentation for this class was generated from the following file:
rootana/src/unit_test/tut.h