AlcapDAQ: TME_Al50_EvdE Class Reference
TME_Al50_EvdE Class Reference
[Modules]
Testing the TMEs for my Al50 analysis.
#include <TME_Al50_EvdE.h>
Classes
struct Arm
Public Member Functions
TME_Al50_EvdE (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~TME_Al50_EvdE ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::vector< IDs::channel > DetectorList
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Private Attributes
long int fNullCount
long int fTdpCount
bool fQuit
DetectorList fSiL1
IDs::channel * fSiL2
DetectorList fSiR1
IDs::channel * fSiR2
struct TME_Al50_EvdE::Arm fLeftArm
struct TME_Al50_EvdE::Arm fLeftArmQuad1
struct TME_Al50_EvdE::Arm fLeftArmQuad2
struct TME_Al50_EvdE::Arm fLeftArmQuad3
struct TME_Al50_EvdE::Arm fLeftArmQuad4
struct TME_Al50_EvdE::Arm fRightArm
struct TME_Al50_EvdE::Arm fRightArmQuad1
struct TME_Al50_EvdE::Arm fRightArmQuad2
struct TME_Al50_EvdE::Arm fRightArmQuad3
struct TME_Al50_EvdE::Arm fRightArmQuad4
std::vector< Arm > fArms
bool fStoppedProtonCut
Detailed Description
Testing the TMEs for my Al50 analysis.
Author:
Andrew Edmonds
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 29 of file TME_Al50_EvdE.h.
Member Typedef Documentation
typedef std::vector<IDs::channel> TME_Al50_EvdE::DetectorList [private]
Definition at line 65 of file TME_Al50_EvdE.h.
Constructor & Destructor Documentation
TME_Al50_EvdE::TME_Al50_EvdE (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 22 of file TME_Al50_EvdE.cpp.
References fStoppedProtonCut, and modules::options::GetBool().
                                                :
  BaseModule("TME_Al50_EvdE",opts),fNullCount(0),fTdpCount(0){
  fStoppedProtonCut=opts->GetBool("stopped_proton_cut", false);
}
TME_Al50_EvdE::~TME_Al50_EvdE ()
Is anything done in the destructor?
Definition at line 28 of file TME_Al50_EvdE.cpp.
{
}
Member Function Documentation
int TME_Al50_EvdE::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 283 of file TME_Al50_EvdE.cpp.
{
  return 0;
}
int TME_Al50_EvdE::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 31 of file TME_Al50_EvdE.cpp.
References TME_Al50_EvdE::Arm::detname, fArms, fLeftArm, fLeftArmQuad1, fLeftArmQuad2, fLeftArmQuad3, fLeftArmQuad4, fRightArm, fRightArmQuad1, fRightArmQuad2, fRightArmQuad3, fRightArmQuad4, fSiL1, fSiL2, fSiR1, fSiR2, fStoppedProtonCut, IDs::kNotApplicable, IDs::kSiL1_1, IDs::kSiL1_2, IDs::kSiL1_3, IDs::kSiL1_4, IDs::kSiL2, IDs::kSiR1_1, IDs::kSiR1_2, IDs::kSiR1_3, IDs::kSiR1_4, IDs::kSiR2, TME_Al50_EvdE::Arm::lower_time_cut, TME_Al50_EvdE::Arm::thick, TME_Al50_EvdE::Arm::thin, and TME_Al50_EvdE::Arm::upper_time_cut.
{
  fLeftArm.detname = "SiL";
  fLeftArmQuad1.detname = "SiL_Quad1";
  fLeftArmQuad2.detname = "SiL_Quad2";
  fLeftArmQuad3.detname = "SiL_Quad3";
  fLeftArmQuad4.detname = "SiL_Quad4";
  fRightArm.detname = "SiR";
  fRightArmQuad1.detname = "SiR_Quad1";
  fRightArmQuad2.detname = "SiR_Quad2";
  fRightArmQuad3.detname = "SiR_Quad3";
  fRightArmQuad4.detname = "SiR_Quad4";
  using namespace IDs;
  fSiL1.push_back(IDs::channel (kSiL1_1 , kNotApplicable ));
  fSiL1.push_back(IDs::channel (kSiL1_2 , kNotApplicable ));
  fSiL1.push_back(IDs::channel (kSiL1_3 , kNotApplicable ));
  fSiL1.push_back(IDs::channel (kSiL1_4 , kNotApplicable ));
  fSiL2 = new IDs::channel (kSiL2   , kNotApplicable );
  fSiR1.push_back(IDs::channel (kSiR1_1 , kNotApplicable ));
  fSiR1.push_back(IDs::channel (kSiR1_2 , kNotApplicable ));
  fSiR1.push_back(IDs::channel (kSiR1_3 , kNotApplicable ));
  fSiR1.push_back(IDs::channel (kSiR1_4 , kNotApplicable ));
  fSiR2 = new IDs::channel (kSiR2   , kNotApplicable );
  fLeftArm.thin = fSiL1;
  fLeftArm.thick = fSiL2;
  DetectorList left_quad_1; left_quad_1.push_back(IDs::channel (kSiL1_1 , kNotApplicable));
  fLeftArmQuad1.thin = left_quad_1;
  fLeftArmQuad1.thick = fSiL2;
  DetectorList left_quad_2; left_quad_2.push_back(IDs::channel (kSiL1_2 , kNotApplicable));
  fLeftArmQuad2.thin = left_quad_2;
  fLeftArmQuad2.thick = fSiL2;
  DetectorList left_quad_3; left_quad_3.push_back(IDs::channel (kSiL1_3 , kNotApplicable));
  fLeftArmQuad3.thin = left_quad_3;
  fLeftArmQuad3.thick = fSiL2;
  DetectorList left_quad_4; left_quad_4.push_back(IDs::channel (kSiL1_4 , kNotApplicable));
  fLeftArmQuad4.thin = left_quad_4;
  fLeftArmQuad4.thick = fSiL2;
  fRightArm.thin = fSiR1;
  fRightArm.thick = fSiR2;
  DetectorList right_quad_1; right_quad_1.push_back(IDs::channel (kSiR1_1 , kNotApplicable));
  fRightArmQuad1.thin = right_quad_1;
  fRightArmQuad1.thick = fSiR2;
  DetectorList right_quad_2; right_quad_2.push_back(IDs::channel (kSiR1_2 , kNotApplicable));
  fRightArmQuad2.thin = right_quad_2;
  fRightArmQuad2.thick = fSiR2;
  DetectorList right_quad_3; right_quad_3.push_back(IDs::channel (kSiR1_3 , kNotApplicable));
  fRightArmQuad3.thin = right_quad_3;
  fRightArmQuad3.thick = fSiR2;
  DetectorList right_quad_4; right_quad_4.push_back(IDs::channel (kSiR1_4 , kNotApplicable));
  fRightArmQuad4.thin = right_quad_4;
  fRightArmQuad4.thick = fSiR2;
  // Hard-coded for the time being
  fLeftArm.lower_time_cut = 0;
  fLeftArm.upper_time_cut = 10000;
  fLeftArmQuad1.lower_time_cut = 0;
  fLeftArmQuad1.upper_time_cut = 999999999;
  fLeftArmQuad2.lower_time_cut = 0;
  fLeftArmQuad2.upper_time_cut = 999999999;
  fLeftArmQuad3.lower_time_cut = 0;
  fLeftArmQuad3.upper_time_cut = 999999999;
  fLeftArmQuad4.lower_time_cut = 0;
  fLeftArmQuad4.upper_time_cut = 999999999;
  fRightArm.lower_time_cut = 0;
  fRightArm.upper_time_cut = 10000;
  fRightArmQuad1.lower_time_cut = 0;
  fRightArmQuad1.upper_time_cut = 999999999;
  fRightArmQuad2.lower_time_cut = 0;
  fRightArmQuad2.upper_time_cut = 999999999;
  fRightArmQuad3.lower_time_cut = 0;
  fRightArmQuad3.upper_time_cut = 999999999;
  fRightArmQuad4.lower_time_cut = 0;
  fRightArmQuad4.upper_time_cut = 999999999;
  fArms.push_back(fLeftArm);
  fArms.push_back(fLeftArmQuad1);
  fArms.push_back(fLeftArmQuad2);
  fArms.push_back(fLeftArmQuad3);
  fArms.push_back(fLeftArmQuad4);
  fArms.push_back(fRightArm);
  fArms.push_back(fRightArmQuad1);
  fArms.push_back(fRightArmQuad2);
  fArms.push_back(fRightArmQuad3);
  fArms.push_back(fRightArmQuad4);
  // Create the histograms for each arm
  for (std::vector<Arm>::iterator i_arm = fArms.begin(); i_arm != fArms.end(); ++i_arm) {
    std::string evde_histname = i_arm->detname + "_EvdE";
    std::string evde_histtitle = "The E v dE plot for " + i_arm->detname;
    i_arm->h_EvdE = new TH2F(evde_histname.c_str(), evde_histtitle.c_str(), 250,0,25000, 100,0,10000);
    i_arm->h_EvdE->SetXTitle("E + dE [keV]");
    i_arm->h_EvdE->SetYTitle("dE [keV]");
    std::string time_histname = i_arm->detname + "_Time";
    std::string time_histtitle = "The time of hits in " + i_arm->detname;
    i_arm->h_Time = new TH1F(time_histname.c_str(), time_histtitle.c_str(), 2500,0,10000);
    i_arm->h_Time->SetXTitle("Time [ns]");
    i_arm->h_Time->SetYTitle("Count");
    if (fStoppedProtonCut) {
      TTree* pid_cuts_tree = new TTree();
      std::string pid_cuts_filename = "/gpfs/home/edmonds_a/AlcapDAQ/analyzer/rootana/src/Al50/pid-cuts-" + i_arm->detname + ".txt";
      pid_cuts_tree->ReadFile(pid_cuts_filename.c_str());
      pid_cuts_tree->Print();
      TBranch* energy_branch = (TBranch*) pid_cuts_tree->GetBranch("energy");
      double energy;
      energy_branch->SetAddress(&energy);
      TBranch* d_energy_branch = (TBranch*) pid_cuts_tree->GetBranch("dEnergy");
      double d_energy;
      d_energy_branch->SetAddress(&d_energy);
      TBranch* stopped_proton_prob_branch = (TBranch*) pid_cuts_tree->GetBranch("p_stop_prob");
      double stopped_proton_prob;
      stopped_proton_prob_branch->SetAddress(&stopped_proton_prob);
      std::string prob_histname = i_arm->detname + "_StoppedProtonProb";
      std::string prob_histtitle = "Probability that at a given (E, dE) that the hit is a proton in " + i_arm->detname;
      i_arm->h_stopped_proton_prob = new TH2F(prob_histname.c_str(), prob_histtitle.c_str(), 100,0,10000, 100,0,10000);
      i_arm->h_stopped_proton_prob->SetXTitle("E [keV]");
      i_arm->h_stopped_proton_prob->SetYTitle("dE [keV]");
      for (int i_entry = 0; i_entry < pid_cuts_tree->GetEntries(); ++i_entry) {
        pid_cuts_tree->GetEntry(i_entry);
        i_arm->h_stopped_proton_prob->Fill(energy, d_energy, stopped_proton_prob);
        //      std::cout << i_arm->detname << ": Filling @ (" << energy << ", " << d_energy << "): " << stopped_proton_prob << std::endl;
      }
      delete pid_cuts_tree;
    }
    else {
      i_arm->h_stopped_proton_prob = NULL;
    }
  }
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int TME_Al50_EvdE::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 176 of file TME_Al50_EvdE.cpp.
References fArms, fStoppedProtonCut, TDetectorPulse::GetAmplitude(), TAnalysedPulse::GetEnergy(), TDetectorPulse::GetTAP(), TDetectorPulse::GetTime(), gMuonEvents, and TDetectorPulse::kFast.
{
    for(MuonEventList::const_iterator i_tme=gMuonEvents.begin();
            i_tme!=gMuonEvents.end(); ++i_tme){
      // First, check for pile-up in the muSc
      if ( (*i_tme)->HasMuonPileup()) {
        continue;
      }
      double tme_time= (*i_tme)->GetTime(); // this is the same as the muSc time
      // Loop through the arms and plots
      for (std::vector<Arm>::const_iterator i_arm = fArms.begin(); i_arm != fArms.end(); ++i_arm) {
        // Check that there are pulses in both the thin and the thick silicon detectors
        DetectorList si_thin = (*i_arm).thin;
        IDs::channel* si_thick = (*i_arm).thick;
        // Get the thick detector
        int si_thick_source_index=(*i_tme)->GetSourceIndex(*si_thick);
        // While there are thick detector sources still around
        while (si_thick_source_index>-1) {
          const IDs::source& si_thick_source=(*i_tme)->GetSource(si_thick_source_index);
          int n_si_thick = (*i_tme)->NumPulses(si_thick_source);
          // Loop through the pulses in the thick detector
          for (int i_thick_pulse=0; i_thick_pulse<n_si_thick; ++i_thick_pulse) {
            const TDetectorPulse* tdp_si_thick=(*i_tme)->GetPulse(si_thick_source,i_thick_pulse);
            double thick_energy = tdp_si_thick->GetTAP(TDetectorPulse::kFast)->GetEnergy();
            // Skip to next pulse if energy <100 keV
            if (thick_energy < 100) {
              continue;
            }
            double thick_amplitude = tdp_si_thick->GetAmplitude();
            double thick_time = tdp_si_thick->GetTime();
            // Loop through the thin quadrants
            for(DetectorList::const_iterator i_det=si_thin.begin();
                i_det!=si_thin.end(); ++i_det){
              // Get the thin quadrant and loop through its sources
              int si_thin_source_index=(*i_tme)->GetSourceIndex(*i_det);
              while(si_thin_source_index>-1){
                const IDs::source& si_thin_source=(*i_tme)->GetSource(si_thin_source_index);
                int n_si_thin = (*i_tme)->NumPulses(si_thin_source);
                // Loop through the pulses in this quadrant
                for(int i_thin_pulse=0; i_thin_pulse<n_si_thin; ++i_thin_pulse){
                  const TDetectorPulse* tdp_si_thin=(*i_tme)->GetPulse(si_thin_source,i_thin_pulse);
                  double thin_energy = tdp_si_thin->GetTAP(TDetectorPulse::kFast)->GetEnergy();
                  if (thin_energy < 100) {
                    continue;
                  }
                  double thin_amplitude = tdp_si_thin->GetAmplitude();
                  double thin_time = tdp_si_thin->GetTime();
                  bool passes_cuts = false;
                  double arrival_time = thick_time - tme_time;
                  if ( arrival_time > i_arm->lower_time_cut && arrival_time < i_arm->upper_time_cut ) {
                    // Now check if this passes our proton cut
                    if (fStoppedProtonCut) {
                      int bin = i_arm->h_stopped_proton_prob->FindBin(thick_energy+thin_energy, thin_energy);
                      double probability = i_arm->h_stopped_proton_prob->GetBinContent(bin);
                      //                      std::cout << "(E+dE, dE) = (" << thick_energy+thin_energy << ", " << thin_energy << "): Prob = " << probability << std::endl;
                      if (probability > 0.99) {
                        passes_cuts = true;
                      }
                    }
                    else { // everything passes if we're not cutting on protons
                      passes_cuts = true;
                    }
                  }
                  if (std::abs(thin_time - thick_time) > 500) {
                    //              std::cout << "abs(t_thin - t_thick) = " << std::fabs(thin_time - thick_time) << std::endl;
                    passes_cuts=false;
                  }
                  if (fStoppedProtonCut && (thick_energy+thin_energy < 1500 || thick_energy+thin_energy > 8000)) {
                    passes_cuts=false; // only accept proton if E is between 1.5 and 8 MeV (like Nam's cut)
                  }
                  if (passes_cuts) {
                    //              std::cout << "Amplitude --> Energy (thick): " << thick_amplitude << " --> " << thick_energy << std::endl;
                    //              std::cout << "Amplitude --> Energy (thin): " << thin_amplitude << " --> " << thin_energy << std::endl;
                    //              std::cout << "Plotting: " << thick_energy+thin_energy << ", " << thin_energy << std::endl;
                    i_arm->h_EvdE->Fill(thick_energy+thin_energy, thin_energy);
                    i_arm->h_Time->Fill(arrival_time);
                  }
                }
                si_thin_source_index=(*i_tme)->GetSourceIndex(*i_det,si_thin_source_index+1);
              }
            }
          }
          si_thick_source_index=(*i_tme)->GetSourceIndex(*si_thick,si_thick_source_index+1);
        }
      }
    }
    return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
std::vector<Arm> TME_Al50_EvdE::fArms [private]
Definition at line 84 of file TME_Al50_EvdE.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
struct TME_Al50_EvdE::Arm TME_Al50_EvdE::fLeftArm [private]
Referenced by BeforeFirstEntry().
struct TME_Al50_EvdE::Arm TME_Al50_EvdE::fLeftArmQuad1 [private]
Referenced by BeforeFirstEntry().
struct TME_Al50_EvdE::Arm TME_Al50_EvdE::fLeftArmQuad2 [private]
Referenced by BeforeFirstEntry().
struct TME_Al50_EvdE::Arm TME_Al50_EvdE::fLeftArmQuad3 [private]
Referenced by BeforeFirstEntry().
struct TME_Al50_EvdE::Arm TME_Al50_EvdE::fLeftArmQuad4 [private]
Referenced by BeforeFirstEntry().
long int TME_Al50_EvdE::fNullCount [private]
Definition at line 61 of file TME_Al50_EvdE.h.
bool TME_Al50_EvdE::fQuit [private]
Definition at line 63 of file TME_Al50_EvdE.h.
struct TME_Al50_EvdE::Arm TME_Al50_EvdE::fRightArm [private]
Referenced by BeforeFirstEntry().
struct TME_Al50_EvdE::Arm TME_Al50_EvdE::fRightArmQuad1 [private]
Referenced by BeforeFirstEntry().
struct TME_Al50_EvdE::Arm TME_Al50_EvdE::fRightArmQuad2 [private]
Referenced by BeforeFirstEntry().
struct TME_Al50_EvdE::Arm TME_Al50_EvdE::fRightArmQuad3 [private]
Referenced by BeforeFirstEntry().
struct TME_Al50_EvdE::Arm TME_Al50_EvdE::fRightArmQuad4 [private]
Referenced by BeforeFirstEntry().
DetectorList TME_Al50_EvdE::fSiL1 [private]
Definition at line 66 of file TME_Al50_EvdE.h.
Referenced by BeforeFirstEntry().
IDs::channel* TME_Al50_EvdE::fSiL2 [private]
Definition at line 67 of file TME_Al50_EvdE.h.
Referenced by BeforeFirstEntry().
DetectorList TME_Al50_EvdE::fSiR1 [private]
Definition at line 68 of file TME_Al50_EvdE.h.
Referenced by BeforeFirstEntry().
IDs::channel* TME_Al50_EvdE::fSiR2 [private]
Definition at line 69 of file TME_Al50_EvdE.h.
Referenced by BeforeFirstEntry().
bool TME_Al50_EvdE::fStoppedProtonCut [private]
Definition at line 86 of file TME_Al50_EvdE.h.
Referenced by BeforeFirstEntry(), ProcessEntry(), and TME_Al50_EvdE().
long int TME_Al50_EvdE::fTdpCount [private]
Definition at line 61 of file TME_Al50_EvdE.h.
The documentation for this class was generated from the following files:
rootana/src/Al50/TME_Al50_EvdE.h
rootana/src/Al50/TME_Al50_EvdE.cpp