AlcapDAQ: CheckTMEs Class Reference
CheckTMEs Class Reference
[Modules]
Produce various plots that characterise the produced TMuonEvents.
#include <CheckTMEs.h>
Public Member Functions
CheckTMEs (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~CheckTMEs ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::vector< IDs::channel > DetectorList
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Private Attributes
long int fNullCount
long int fTdpCount
DetectorList fDetectors
TH1F * fTotalPulses
TH2F * fPulsesPerDetector
TH2F * fTDiffPerDetector
TH1F * fFlags
Detailed Description
Produce various plots that characterise the produced TMuonEvents.
Author:
Ben Krikler
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 26 of file CheckTMEs.h.
Member Typedef Documentation
typedef std::vector<IDs::channel> CheckTMEs::DetectorList [private]
Definition at line 60 of file CheckTMEs.h.
Constructor & Destructor Documentation
CheckTMEs::CheckTMEs (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 19 of file CheckTMEs.cpp.
                                        :
   BaseModule("CheckTMEs",opts),fNullCount(0),fTdpCount(0){
}
CheckTMEs::~CheckTMEs ()
Is anything done in the destructor?
Definition at line 23 of file CheckTMEs.cpp.
                     {
}
Member Function Documentation
int CheckTMEs::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 122 of file CheckTMEs.cpp.
References fNullCount, fTDiffPerDetector, and fTdpCount.
{
  cout<<"CheckTMEs::AfterLastEntry: NULL TDP in TME ("<<++fNullCount<<")"<<endl;
  cout<<"CheckTMEs::AfterLastEntry: Total number of TDPs ("<<++fTdpCount<<")"<<endl;
                  cout<<"CheckTMEs::AfterLastEntry: Total entries in fTDiffPerDetector: "<<fTDiffPerDetector->GetEntries()<<endl;
  return 0;
}
int CheckTMEs::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 26 of file CheckTMEs.cpp.
References fDetectors, fFlags, fPulsesPerDetector, fTDiffPerDetector, fTotalPulses, IDs::kGe, IDs::kMuSc, IDs::kMuScA, IDs::kNDet, IDs::kNDet2, IDs::kNotApplicable, IDs::kScGe, IDs::kScL, IDs::kScR, IDs::kScVe, IDs::kSiL1_1, IDs::kSiL1_2, IDs::kSiL1_3, IDs::kSiL1_4, IDs::kSiL2, IDs::kSiR1_1, IDs::kSiR1_2, IDs::kSiR1_3, IDs::kSiR1_4, and IDs::kSiR2.
{
    using namespace IDs;
    fDetectors.push_back(IDs::channel (kGe     , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kScR    , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kScL    , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kScVe   , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kScGe   , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiL1_1 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiL1_2 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiL1_3 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiL1_4 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiR1_1 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiR1_2 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiR1_3 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiR1_4 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiR2   , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiL2   , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kMuSc   , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kMuScA  , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kNDet   , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kNDet2  , kNotApplicable ));
    // Plot the total number of pulses
    fTotalPulses=new TH1F("hTotalPulses", "Total number of pulses per TME", 100, 0 ,100);
    fTotalPulses->SetXTitle("Number of pulses");
    // Plot the number of pulses per channel
    fPulsesPerDetector=new TH2F("hPulsesPerChannel", "Pulses per channel per TME",
            50, 0 ,50,fDetectors.size(),0,fDetectors.size());
    fPulsesPerDetector->SetXTitle("Number of pulses");
    //fPulsesPerDetector->SetYTitle("Detector");
    fTDiffPerDetector=new TH2F("hTDiffPerChannel", "TDiff to muSc for each channel per TME",
            5000, -1.2e4,1.2e4,fDetectors.size(),0,fDetectors.size());
    fTDiffPerDetector->SetXTitle("TDiff to central muon (ns)");
    for(DetectorList::const_iterator i_det=fDetectors.begin();
            i_det!=fDetectors.end(); ++i_det){
        fPulsesPerDetector->GetYaxis()->SetBinLabel(i_det-fDetectors.begin()+1, i_det->str().c_str());
        fTDiffPerDetector->GetYaxis()->SetBinLabel(i_det-fDetectors.begin()+1, i_det->str().c_str());
    }
    fPulsesPerDetector->SetDrawOption("colz");
    fTDiffPerDetector->SetDrawOption("colz");
    // Plot the number of TME flags
    fFlags=new TH1F("hFlags", "Number of flagged per TME", 5,0,5);
    fFlags->SetYTitle("Number of pulses");
    int count=0;
    fFlags->GetXaxis()->SetBinLabel(++count,"Healthy");
    fFlags->GetXaxis()->SetBinLabel(++count,"Late");
    fFlags->GetXaxis()->SetBinLabel(++count,"Early");
    fFlags->GetXaxis()->SetBinLabel(++count,"Muon Hit");
    fFlags->GetXaxis()->SetBinLabel(++count,"Muon PileUp");
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int CheckTMEs::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 83 of file CheckTMEs.cpp.
References TDetectorPulse::CouldBePaired(), fDetectors, fFlags, fNullCount, fPulsesPerDetector, fTDiffPerDetector, fTdpCount, fTotalPulses, TDetectorPulse::GetTime(), gMuonEvents, and TDetectorPulse::IsPairedPulse().
{
    // Loop over each TME
    for(MuonEventList::const_iterator i_tme=gMuonEvents.begin();
            i_tme!=gMuonEvents.end(); ++i_tme){
        // total pulses
        fTotalPulses->Fill((*i_tme)->TotalNumPulses());
        for(DetectorList::const_iterator i_det=fDetectors.begin();
                i_det!=fDetectors.end(); ++i_det){
            // pulses per channel
            int N=0, n;
            double tme_time= (*i_tme)->GetTime();
            int source_index=(*i_tme)->GetSourceIndex(*i_det);
            while(source_index>-1){
              const IDs::source& source=(*i_tme)->GetSource(source_index);
              n=(*i_tme)->NumPulses(source);
              N+=n;
              for(int i=0; i<n; ++i){
                 const TDetectorPulse* tdp=(*i_tme)->GetPulse(source,i);
                 if(tdp && (tdp->IsPairedPulse() || !tdp->CouldBePaired()) )
                    fTDiffPerDetector->Fill(tdp->GetTime() - tme_time, i_det - fDetectors.begin());
                 else if(!tdp)
                    ++fNullCount;
                ++fTdpCount;
              }
             source_index=(*i_tme)->GetSourceIndex(*i_det,source_index+1);
            }
            fPulsesPerDetector->Fill(N, i_det - fDetectors.begin());
        }
        // fill flags hist
        if((*i_tme)->HasMuonHit()) fFlags->Fill("Muon Hit",1.);
        if((*i_tme)->HasMuonPileup()) fFlags->Fill("Muon PileUp",1.);
        //if((*i_tme)->WasEarlyInEvent()) fFlags->Fill("Early",1.);
        //else if((*i_tme)->WasLateInEvent()) fFlags->Fill("Late",1.);
        //else
            fFlags->Fill("Healthy",1.);
    }
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
DetectorList CheckTMEs::fDetectors [private]
Definition at line 61 of file CheckTMEs.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
TH1F* CheckTMEs::fFlags [private]
Definition at line 66 of file CheckTMEs.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
long int CheckTMEs::fNullCount [private]
Definition at line 58 of file CheckTMEs.h.
Referenced by AfterLastEntry(), and ProcessEntry().
TH2F* CheckTMEs::fPulsesPerDetector [private]
Definition at line 64 of file CheckTMEs.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
TH2F* CheckTMEs::fTDiffPerDetector [private]
Definition at line 65 of file CheckTMEs.h.
Referenced by AfterLastEntry(), BeforeFirstEntry(), and ProcessEntry().
long int CheckTMEs::fTdpCount [private]
Definition at line 58 of file CheckTMEs.h.
Referenced by AfterLastEntry(), and ProcessEntry().
TH1F* CheckTMEs::fTotalPulses [private]
Definition at line 63 of file CheckTMEs.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/plotters/CheckTMEs.h
rootana/src/plotters/CheckTMEs.cpp