AlcapDAQ: TVMuonEventGenerator Class Reference
TVMuonEventGenerator Class Reference
#include <TVMuonEventGenerator.h>
Public Member Functions
TVMuonEventGenerator (const char *name, TMEGeneratorOptions *opts)
virtual ~TVMuonEventGenerator ()
virtual int ProcessPulses (MuonEventList &muonEventsOut, const SourceDetPulseMap &detectorPulsesIn)=0
const IDs::generator & GetGenerator () const
Protected Member Functions
bool Debug () const
Private Attributes
bool fDebug
IDs::generator fGenerator
Detailed Description
Definition at line 12 of file TVMuonEventGenerator.h.
Constructor & Destructor Documentation
TVMuonEventGenerator::TVMuonEventGenerator (const char * name, TMEGeneratorOptions * opts) [inline]
Definition at line 14 of file TVMuonEventGenerator.h.
References fDebug, and modules::options::GetFlag().
                                                                                :
            fDebug(false),fGenerator(name,opts->StringDescription()){
                        if(opts && opts->GetFlag("debug")) fDebug=true;
                };
                virtual ~TVMuonEventGenerator(){};
virtual TVMuonEventGenerator::~TVMuonEventGenerator () [inline, virtual]
Definition at line 18 of file TVMuonEventGenerator.h.
{};
Member Function Documentation
bool TVMuonEventGenerator::Debug () const [inline, protected]
Definition at line 25 of file TVMuonEventGenerator.h.
Referenced by MaxTimeDiffMEGenerator::ProcessPulses().
{return fDebug;};
const IDs::generator& TVMuonEventGenerator::GetGenerator () const [inline]
Definition at line 22 of file TVMuonEventGenerator.h.
References fGenerator.
{return fGenerator;}
virtual int TVMuonEventGenerator::ProcessPulses (MuonEventList & muonEventsOut, const SourceDetPulseMap & detectorPulsesIn) [pure virtual]
Implemented in FixedWindowMEGenerator, and MaxTimeDiffMEGenerator.
Referenced by MakeMuonEvents::ProcessEntry().
Member Data Documentation
bool TVMuonEventGenerator::fDebug [private]
Definition at line 25 of file TVMuonEventGenerator.h.
Referenced by TVMuonEventGenerator().
IDs::generator TVMuonEventGenerator::fGenerator [private]
Definition at line 28 of file TVMuonEventGenerator.h.
Referenced by GetGenerator().
The documentation for this class was generated from the following file:
rootana/src/TME_generators/TVMuonEventGenerator.h