AlcapDAQ: Except::MultiHistogramFitFCN Class Reference
Except::MultiHistogramFitFCN Class Reference
#include <MultiHistogramFitFCN.h>
Public Member Functions
MultiHistogramFitFCN ()
MultiHistogramFitFCN (const char *message)
MultiHistogramFitFCN (const char *file, int line)
const char * what (void) const throw ()
const char * bt (void) const throw ()
void AppendWhat (const char *child)
void AppendWhat (const char *child, const char *message)
void AppendWhat (const char *child, const char *file, int line)
Static Public Attributes
static unsigned int gBacktraceSymbols = 5
The number of backtrace symbols to add to the "what" string.
Detailed Description
Definition at line 13 of file MultiHistogramFitFCN.h.
Constructor & Destructor Documentation
Except::MultiHistogramFitFCN::MultiHistogramFitFCN () [inline]
Definition at line 13 of file MultiHistogramFitFCN.h.
: public ROOT::Minuit2::FCNBase {
Except::MultiHistogramFitFCN::MultiHistogramFitFCN (const char * message) [inline]
Definition at line 13 of file MultiHistogramFitFCN.h.
: public ROOT::Minuit2::FCNBase {
Except::MultiHistogramFitFCN::MultiHistogramFitFCN (const char * file, int line) [inline]
Definition at line 13 of file MultiHistogramFitFCN.h.
: public ROOT::Minuit2::FCNBase {
Member Function Documentation
void Except::Base::AppendWhat (const char * child, const char * file, int line) [inherited]
Used in conjunction with the LOCATION macro, see documentation of Except::Base
Definition at line 81 of file AlcapExcept.cpp.
References Except::Base::AppendWhat(), and Except::Base::fWhat.
{
  AppendWhat (child);
  unsigned int wLen = std::strlen(fWhat);
  unsigned int fLen = std::strlen(file);
  if (fLen+wLen < sizeof(fWhat)-16) {
    char buf[16];
    buf[0]=0;
    snprintf(buf,16,":%d)", line);
    std::strcat(fWhat," (");
    std::strcat(fWhat,file);
    std::strcat(fWhat,buf);
  }
}
void Except::Base::AppendWhat (const char * child, const char * message) [inherited]
Used in constructors of classes which inherit from Except::Base to add message text to the What() string.
Definition at line 70 of file AlcapExcept.cpp.
References Except::Base::AppendWhat(), and Except::Base::fWhat.
{
  AppendWhat(child);
  unsigned int wLen = std::strlen(fWhat);
  unsigned int mLen = std::strlen(message);
  if (wLen+mLen < sizeof(fWhat)-9) {
    std::strcat(fWhat,"  \"");
    std::strcat(fWhat,message);
    std::strcat(fWhat,"\"");
  }
}
void Except::Base::AppendWhat (const char * child) [inherited]
Used in constructors of classes which inherit from Except::Base to add text to the What() string.
Definition at line 61 of file AlcapExcept.cpp.
References Except::Base::fWhat.
Referenced by Except::Base::AppendWhat().
{
  unsigned int wLen = std::strlen(fWhat);
  unsigned int cLen = std::strlen(child);
  if (wLen+cLen < sizeof(fWhat)-5) {
    std::strcat(fWhat,"::");
    std::strcat(fWhat,child);
  }
}
const char* Except::Base::bt (void) const throw () [inline, inherited]
Inherited from exception to return the name of the exception as a null terminated string.
Definition at line 82 of file AlcapExcept.h.
References Except::Base::fTrace.
Referenced by LoopSequence::Run().
{return fTrace;}
const char* Except::Base::what (void) const throw () [inline, inherited]
Inherited from exception to return the name of the exception as a null terminated string.
Definition at line 78 of file AlcapExcept.h.
References Except::Base::fWhat.
Referenced by LoopSequence::Run().
{return fWhat;}
Member Data Documentation
unsigned int Except::Base::gBacktraceSymbols = 5 [static, inherited]
The number of backtrace symbols to add to the "what" string.
Definition at line 71 of file AlcapExcept.h.
Referenced by Except::Base::Base().
The documentation for this class was generated from the following file:
rootana/src/TAP_generators/utils/MultiHistogramFitFCN.h