AlcapDAQ: PrePulse Class Reference
PrePulse Class Reference
#include <PrePulse.h>
Public Member Functions
PrePulse (int start, int stop, int location, int height, TPulseIsland *pulse)
~PrePulse ()
int GetStart () const
int GetStop () const
int GetLocation () const
int GetHeight () const
TPulseIsland * GetPulse () const
void Print ()
Static Public Member Functions
static std::vector< PrePulse > FindPrePulses (TPulseIsland *, int rise, int fall)
Private Attributes
int fStart
int fStop
int fLocation
int fHeight
TPulseIsland * fPulse
Detailed Description
Definition at line 8 of file PrePulse.h.
Constructor & Destructor Documentation
PrePulse::PrePulse (int start, int stop, int location, int height, TPulseIsland * pulse)
Definition at line 8 of file PrePulse.cpp.
Referenced by FindPrePulses().
                                                                                 :
   fStart(start), fStop(stop), fLocation(loc), fHeight(height), fPulse(pulse) {}
PrePulse::~PrePulse ()
Definition at line 11 of file PrePulse.cpp.
 {}
Member Function Documentation
std::vector< PrePulse > PrePulse::FindPrePulses (TPulseIsland * pulse, int rise, int fall) static
Definition at line 44 of file PrePulse.cpp.
References found, TPulseIsland::GetPedestal(), TPulseIsland::GetSamples(), TPulseIsland::GetTriggerPolarity(), height, i, PrePulse(), and samples.
Referenced by MakeTemplate::ProcessEntry().
{
   // Looks through pulse to look for samples that go rise as fast as rise between two samples
   // and then fall
   std::vector<int> samples = pulse->GetSamples();
   unsigned int nsamps = samples.size();
   int pPed = pulse->GetPedestal(0);
   int pPol = pulse->GetTriggerPolarity();
   std::vector<PrePulse> prepulses;
   int s1, s2, ds;
   int start, stop, loc, height;
   bool found = false;
   for (unsigned int i = 1; i < nsamps; ++i) {
     s1 = pPol * (samples[i-1] - pPed);
     s2 = pPol * (samples[i] - pPed);
     ds = s2 - s1;
     if (found) {
       if (-ds > fall) {
         stop = (int)i;
         prepulses.push_back(PrePulse(start, stop, loc, height, pulse));
         start = stop = loc = height = 0;
         found = false;
       }
       if (s2 > height) {
         loc = (int)i;
         height = s2;
       }
     } else {
       if (ds > rise) {
         found = true;
         start = (int)(i - 1);
         loc = start + 1;
         height = s2;
       }
     }
   }
   return prepulses;
 }
int PrePulse::GetHeight () const
Definition at line 25 of file PrePulse.cpp.
References fHeight.
{
   return fHeight;
 }
int PrePulse::GetLocation () const
Definition at line 21 of file PrePulse.cpp.
References fLocation.
{
   return fLocation;
 }
TPulseIsland * PrePulse::GetPulse () const
Definition at line 29 of file PrePulse.cpp.
References fPulse.
{
   return fPulse;
 }
int PrePulse::GetStart () const
Definition at line 13 of file PrePulse.cpp.
References fStart.
{
   return fStart;
 }
int PrePulse::GetStop () const
Definition at line 17 of file PrePulse.cpp.
References fStop.
{
   return fStop;
 }
void PrePulse::Print ()
Definition at line 33 of file PrePulse.cpp.
References fHeight, fLocation, fStart, and fStop.
                      {
   std::cout << "PrePulse Information:"
             << "\t" << "Strt" << "\t" << "Stop"
             << "\t" << "Loc" << "\t" << "Hght"
             << std::endl;
   std::cout << "                     "
             << "\t" << fStart << "\t" << fStop
             << "\t" << fLocation << "\t" << fHeight
             << std::endl;
 }
Field Documentation
int PrePulse::fHeight private
Definition at line 14 of file PrePulse.h.
Referenced by GetHeight(), and Print().
int PrePulse::fLocation private
Definition at line 13 of file PrePulse.h.
Referenced by GetLocation(), and Print().
TPulseIsland* PrePulse::fPulse private
Definition at line 15 of file PrePulse.h.
Referenced by GetPulse().
int PrePulse::fStart private
Definition at line 11 of file PrePulse.h.
Referenced by GetStart(), and Print().
int PrePulse::fStop private
Definition at line 12 of file PrePulse.h.
Referenced by GetStop(), and Print().
The documentation for this class was generated from the following files:
analyzer/rootana/src/TAP_generators/PrePulse.h
analyzer/rootana/src/TAP_generators/PrePulse.cpp