AlcapDAQ: PlotIntegralRatios Class Reference
PlotIntegralRatios Class Reference
[Modules]
A one line description of what your module does.
#include <PlotIntegralRatios.h>
Classes
struct SourcePlots_t
Public Member Functions
PlotIntegralRatios (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~PlotIntegralRatios ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::vector
< SourcePlots_t > SourceList_t
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Private Attributes
SourceList_t fSourcesToPlot
IDs::source fSource
double fShiftFull
double fShiftDifference
Detailed Description
A one line description of what your module does.
Author:
AuthorName
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 25 of file PlotIntegralRatios.h.
Member Typedef Documentation
typedef std::vector<SourcePlots_t> PlotIntegralRatios::SourceList_t [private]
Definition at line 33 of file PlotIntegralRatios.h.
Constructor & Destructor Documentation
PlotIntegralRatios::PlotIntegralRatios (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 20 of file PlotIntegralRatios.cpp.
References fShiftDifference, fShiftFull, and modules::options::GetDouble().
                                                          :
   BaseModule("PlotIntegralRatios",opts),
    fSource(opts->GetString("source","SiR2-*#IntegralRatio#any")){
    fShiftFull=opts->GetDouble("shift_full",0);
    fShiftDifference=opts->GetDouble("shift_diff",0);
}
PlotIntegralRatios::~PlotIntegralRatios ()
Is anything done in the destructor?
Definition at line 27 of file PlotIntegralRatios.cpp.
{
}
Member Function Documentation
int PlotIntegralRatios::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 188 of file PlotIntegralRatios.cpp.
{
  return 0;
}
int PlotIntegralRatios::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 30 of file PlotIntegralRatios.cpp.
References PlotIntegralRatios::SourcePlots_t::diff_v_ratio, fSource, fSourcesToPlot, PlotIntegralRatios::SourcePlots_t::full_integral, PlotIntegralRatios::SourcePlots_t::full_v_ratio, PlotIntegralRatios::SourcePlots_t::full_v_tail, gAnalysedPulseMap, PlotIntegralRatios::SourcePlots_t::ratio, PlotIntegralRatios::SourcePlots_t::ratio_zoomed, PlotIntegralRatios::SourcePlots_t::src, IDs::source::str(), and modules::parser::ToCppValid().
{
    SourcePlots_t tmp;
    for(SourceAnalPulseMap::const_iterator i_source = gAnalysedPulseMap.begin();
            i_source!=gAnalysedPulseMap.end(); ++i_source){
        if(i_source->first.matches(fSource)){
            tmp.src=i_source->first;
            tmp.ratio=new TH1F(
                    modules::parser::ToCppValid("h"+tmp.src.str()+"_ratio").c_str(),
                    ("Ratio of integrals for "+tmp.src.str()).c_str(),
                    1000,0,1);
            tmp.ratio->SetXTitle("Ratio of total to tail integral");
            //tmp.ratio->SetDirectory(GetDirectory("ratios"));
            tmp.ratio_zoomed=new TH1F(
                    modules::parser::ToCppValid("h"+tmp.src.str()+"_ratio_zoomed").c_str(),
                    ("Zoomed Ratio of integrals for "+tmp.src.str()).c_str(),
                    2000,0.1,0.25);
            tmp.ratio_zoomed->SetXTitle("Ratio of total to tail integral");
            //tmp.ratio_zoomed->SetDirectory(GetDirectory("ratios"));
            tmp.full_integral=new TH1F(
                    modules::parser::ToCppValid("h"+tmp.src.str()+"_integral").c_str(),
                    ("Integrals for "+tmp.src.str()).c_str(),
                    1000,0,-1);
            tmp.full_integral->SetXTitle("Total integral");
            //tmp.full_integral->SetDirectory(GetDirectory("ratios"));
//            tmp.assymetry=new TH1F(
//                    modules::parser::ToCppValid("h"+tmp.src.str()+"_assymetry").c_str(),
//                    ("Assymetry (first - second)/(first+second) for "+tmp.src.str()).c_str(),
//                    200,0,-1);
//            tmp.assymetry->SetXTitle("Assymetry of total to tail integral");
//
//            tmp.assymetry2d=new TH2F(
//                    modules::parser::ToCppValid("h"+tmp.src.str()+"_assymetry2d").c_str(),
//                    ("Assymetry (first - second) vs (first+second) for "+tmp.src.str()).c_str(),
//                    200,0,-1,200,0,-1);
//            tmp.assymetry2d->SetXTitle("Total integral");
//            tmp.assymetry2d->SetYTitle("Difference between first and tail");
            tmp.full_v_tail=new TH2F(
                    modules::parser::ToCppValid("h"+tmp.src.str()+"_2d").c_str(),
                    ("Integrals for "+tmp.src.str()).c_str(),
                    400,0,-1,400,0,-1);
            tmp.full_v_tail->SetXTitle("tail integral");
            tmp.full_v_tail->SetYTitle("full integral");
            //tmp.full_v_tail->SetDirectory(GetDirectory("miscs"));
            tmp.full_v_ratio=new TH2F(
                    modules::parser::ToCppValid("h"+tmp.src.str()+"_integral_v_ratio").c_str(),
                    ("Integral vs ratio of tail to integral for "+tmp.src.str()).c_str(),
                    400,0,-3,400,0,-1);
            tmp.full_v_ratio->SetXTitle("ratio of tail to full integrals");
            tmp.full_v_ratio->SetYTitle("full integral");
            //tmp.full_v_ratio->SetDirectory(GetDirectory("miscs"));
            tmp.diff_v_ratio=new TH2F(
                    modules::parser::ToCppValid("h"+tmp.src.str()+"_diff_v_ratio").c_str(),
                    ("Difference vs ratio of tail to integral for "+tmp.src.str()).c_str(),
                    400,0,-1,400,0,-1);
            tmp.diff_v_ratio->SetXTitle("ratio of tail to full integrals");
            tmp.diff_v_ratio->SetYTitle("differente of tail to full integrals");
            //tmp.diff_v_ratio->SetDirectory(GetDirectory("miscs"));
            //tmp.mean_vs_min=new TH2F(
            //        modules::parser::ToCppValid("h"+tmp.src.str()+"_mean_vs_min").c_str(),
            //        ("mean vs min values for "+tmp.src.str()).c_str(),
            //        200,0,-1,200,0,-1);
            //tmp.mean_vs_min->SetXTitle("minimum value");
            //tmp.mean_vs_min->SetYTitle("mean value");
            //tmp.mean_vs_min->SetDirectory(GetDirectory("min_max_mean"));
            //tmp.mean_vs_max=new TH2F(
            //        modules::parser::ToCppValid("h"+tmp.src.str()+"_mean_vs_max").c_str(),
            //        ("mean vs max values for "+tmp.src.str()).c_str(),
            //        200,0,-1,200,0,-1);
            //tmp.mean_vs_max->SetXTitle("maximum value");
            //tmp.mean_vs_max->SetYTitle("mean value");
            //tmp.mean_vs_max->SetDirectory(GetDirectory("min_max_mean"));
            //tmp.mean=new TH1F(
            //        modules::parser::ToCppValid("h"+tmp.src.str()+"_mean").c_str(),
            //        ("mean value for "+tmp.src.str()).c_str(),
            //        400,0,-1);
            //tmp.mean->SetXTitle("mean value");
            //tmp.mean->SetDirectory(GetDirectory("min_max_mean"));
            //tmp.max=new TH1F(
            //        modules::parser::ToCppValid("h"+tmp.src.str()+"_max").c_str(),
            //        ("max value for "+tmp.src.str()).c_str(),
            //        400,0,-1);
            //tmp.max->SetXTitle("max value");
            //tmp.max->SetDirectory(GetDirectory("min_max_mean"));
            //tmp.min=new TH1F(
            //        modules::parser::ToCppValid("h"+tmp.src.str()+"_min").c_str(),
            //        ("min value for "+tmp.src.str()).c_str(),
            //        400,0,-1);
            //tmp.min->SetXTitle("min value");
            //tmp.min->SetDirectory(GetDirectory("min_max_mean"));
            fSourcesToPlot.push_back(tmp);
        }
    }
    if(fSourcesToPlot.empty()){
        cout<<"PlotIntegralRatios:BeforeFirstEntry: Error: No sources in gAnalysedPulseMap match "<<fSource<<endl;
        return 1;
    }
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int PlotIntegralRatios::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 144 of file PlotIntegralRatios.cpp.
References fShiftDifference, fSourcesToPlot, gAnalysedPulseMap, TAnalysedPulse::GetIntegral(), TIntegralRatioAnalysedPulse::GetIntegralRatio(), and TIntegralRatioAnalysedPulse::GetIntegralSmall().
{
    TIntegralRatioAnalysedPulse* pulse=0;
    for(SourceList_t::const_iterator i_source=fSourcesToPlot.begin();
            i_source!=fSourcesToPlot.end(); ++i_source){
        const AnalysedPulseList& pulseList=gAnalysedPulseMap.at(i_source->src);
        for(AnalysedPulseList::const_iterator i_pulse=pulseList.begin();
                i_pulse!=pulseList.end(); ++i_pulse){
            if(i_pulse==pulseList.begin()){
                pulse=dynamic_cast<TIntegralRatioAnalysedPulse*>(*i_pulse);
                if(!pulse) {
                    cout<<"PlotIntegralRatios::ProcessEntry: Error: Pulses in "<<i_source->src
                        <<" aren't of type TIntegralRatioAnalysedPulse"<<endl;
                    return 2;
                }
            }else{
                pulse=static_cast<TIntegralRatioAnalysedPulse*>(*i_pulse);
            }
            double ratio=pulse->GetIntegralRatio();
            double full=pulse->GetIntegral();
            double tail=pulse->GetIntegralSmall();
            double diff=full-2*tail-fShiftDifference;
            i_source->ratio->Fill(ratio);
            i_source->ratio_zoomed->Fill(ratio);
            i_source->full_integral->Fill(full);
            i_source->full_v_tail->Fill(tail,full);
            i_source->full_v_ratio->Fill(ratio,full);
            i_source->diff_v_ratio->Fill(ratio,diff);
            //i_source->assymetry->Fill(diff/(full-fShiftFull));
            //i_source->assymetry2d->Fill(full,(full-2*tail));
            //double mean=pulse->GetMean();
            //double min=pulse->GetMin();
            //double max=pulse->GetMax();
            //i_source->mean->Fill(mean);
            //i_source->max->Fill(max);
            //i_source->min->Fill(min);
            //i_source->mean_vs_min->Fill(min,mean);
            //i_source->mean_vs_max->Fill(max,mean);
        }
    }
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
double PlotIntegralRatios::fShiftDifference [private]
Definition at line 67 of file PlotIntegralRatios.h.
Referenced by PlotIntegralRatios(), and ProcessEntry().
double PlotIntegralRatios::fShiftFull [private]
Definition at line 67 of file PlotIntegralRatios.h.
Referenced by PlotIntegralRatios().
IDs::source PlotIntegralRatios::fSource [private]
Definition at line 66 of file PlotIntegralRatios.h.
Referenced by BeforeFirstEntry().
SourceList_t PlotIntegralRatios::fSourcesToPlot [private]
Definition at line 65 of file PlotIntegralRatios.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/PlotIntegralRatios.h
rootana/src/PlotIntegralRatios.cpp