AlcapDAQ: tut::test_group< Data, MaxTestsInGroup >::safe_holder< T > Class Template Reference
tut::test_group< Data, MaxTestsInGroup >::safe_holder< T > Class Template Reference
Public Member Functions
safe_holder ()
~safe_holder ()
T * operator-> () const
T * get () const
void permit_throw ()
void release ()
void reset ()
bool delete_obj ()
Private Member Functions
safe_holder (const safe_holder &)
safe_holder & operator= (const safe_holder &)
Private Attributes
T * p_
bool permit_throw_in_dtor
Detailed Description
template<class Data, int MaxTestsInGroup = 50>
template<class T>
class tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >
Exception-in-destructor-safe smart-pointer class.
Definition at line 625 of file tut.h.
Constructor & Destructor Documentation
template<class Data , int MaxTestsInGroup = 50> template<class T> tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::safe_holder (const safe_holder< T > &) [private]
template<class Data , int MaxTestsInGroup = 50> template<class T> tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::safe_holder () [inline]
Definition at line 634 of file tut.h.
                    : p_(0),permit_throw_in_dtor(false)
      {
      }
template<class Data , int MaxTestsInGroup = 50> template<class T> tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::~safe_holder () [inline]
Definition at line 638 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::release().
      {
        release();
      }
Member Function Documentation
template<class Data , int MaxTestsInGroup = 50> template<class T> bool tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::delete_obj () [inline]
Definition at line 696 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::p_, and tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::permit_throw_in_dtor.
Referenced by tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::release().
      {
#if defined(TUT_USE_SEH)
        __try
        {
#endif
          T* p = p_;
          p_ = 0;
          delete p;
#if defined(TUT_USE_SEH)
        }
        __except(handle_seh_(::GetExceptionCode()))
        {
          if( permit_throw_in_dtor )
          {
            return false;
          }
        }
#endif
        return true;
      }
template<class Data , int MaxTestsInGroup = 50> template<class T> T* tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::get () const [inline]
Definition at line 644 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::p_.
Referenced by tut::test_group< Data, MaxTestsInGroup >::run_test_seh_().
{ return p_; };
template<class Data , int MaxTestsInGroup = 50> template<class T> T* tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::operator-> () const [inline]
Definition at line 643 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::p_.
{ return p_; };
template<class Data , int MaxTestsInGroup = 50> template<class T> safe_holder& tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::operator= (const safe_holder< T > &) [private]
template<class Data , int MaxTestsInGroup = 50> template<class T> void tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::permit_throw () [inline]
Tell ptr it can throw from destructor. Right way is to use std::uncaught_exception(), but some compilers lack correct implementation of the function.
Definition at line 651 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::permit_throw_in_dtor.
Referenced by tut::test_group< Data, MaxTestsInGroup >::run_test_seh_().
{ permit_throw_in_dtor = true; }
template<class Data , int MaxTestsInGroup = 50> template<class T> void tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::release () [inline]
Specially treats exceptions in test object destructor; if test itself failed, exceptions in destructor are ignored; if test was successful and destructor failed, warning exception throwed.
Definition at line 659 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::delete_obj(), and tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::permit_throw_in_dtor.
Referenced by tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::reset(), tut::test_group< Data, MaxTestsInGroup >::run_test_seh_(), and tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::~safe_holder().
      {
        try
        {
          if( delete_obj() == false )
          {
            throw warning("destructor of test object raised an SEH exception");
          }
        }
        catch( const std::exception& ex )
        {
          if( permit_throw_in_dtor )
          {
            std::string msg = "destructor of test object raised exception: ";
            msg += ex.what();
            throw warning(msg);
          }
        }
        catch( ... )
        {
          if( permit_throw_in_dtor )
          {
            throw warning("destructor of test object raised an exception");
          }
        }
      }
template<class Data , int MaxTestsInGroup = 50> template<class T> void tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::reset () [inline]
Re-init holder to get brand new object.
Definition at line 689 of file tut.h.
References tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::p_, tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::permit_throw_in_dtor, and tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::release().
Referenced by tut::test_group< Data, MaxTestsInGroup >::reset_holder_().
      {
        release();
        permit_throw_in_dtor = false;
        p_ = new T();
      }
Field Documentation
template<class Data , int MaxTestsInGroup = 50> template<class T> T* tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::p_ [private]
Definition at line 627 of file tut.h.
Referenced by tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::delete_obj(), tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::get(), tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::operator->(), and tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::reset().
template<class Data , int MaxTestsInGroup = 50> template<class T> bool tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::permit_throw_in_dtor [private]
Definition at line 628 of file tut.h.
Referenced by tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::delete_obj(), tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::permit_throw(), tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::release(), and tut::test_group< Data, MaxTestsInGroup >::safe_holder< T >::reset().
The documentation for this class was generated from the following file:
rootana/src/unit_test/tut.h