AlcapDAQ: TemplateFitter Class Reference
TemplateFitter Class Reference
#include <TemplateFitter.h>
Public Member Functions
TemplateFitter (std::string detname, int refine_factor)
~TemplateFitter ()
int FitPulseToTemplate (TH1D *hTemplate, TH1D *hPulse, std::string bankname)
double GetPedestalOffset ()
double GetAmplitudeScaleFactor ()
double GetTimeOffset ()
double GetChi2 ()
double GetNDoF ()
void SetInitialParameterEstimates (double pedestal, double amplitude, double time)
Sets the intial estimates for the template fitter.
Private Attributes
TFitterMinuit * fMinuitFitter
IDs::channel fChannel
double fPedestalOffset
double fAmplitudeScaleFactor
double fTimeOffset
double fChi2
int fNDoF
double fPedestalOffset_estimate
Store the initial estimates for the parameters.
double fAmplitudeScaleFactor_estimate
double fTimeOffset_estimate
double fPedestalOffset_minimum
Store the minimum parameter bounds.
double fAmplitudeScaleFactor_minimum
double fTimeOffset_minimum
double fPedestalOffset_maximum
Store the maximum parameter bounds.
double fAmplitudeScaleFactor_maximum
double fTimeOffset_maximum
int fRefineFactor
Detailed Description
Definition at line 10 of file TemplateFitter.h.
Constructor & Destructor Documentation
TemplateFitter::TemplateFitter (std::string detname, int refine_factor)
Definition at line 8 of file TemplateFitter.cpp.
References fMinuitFitter, fRefineFactor, and HistogramFitFCN::SetRefineFactor().
                                                                  : fChannel(detname), fRefineFactor(refine_factor) {
  HistogramFitFCN* fcn = new HistogramFitFCN();
  fMinuitFitter = new TFitterMinuit(2); //  Two (2) parameters to modify (amplitude, pedestal). We will try and do the time one ourselves
  fMinuitFitter->SetMinuitFCN(fcn);
  fMinuitFitter->SetPrintLevel(-1); // set the debug level to quiet (-1=quiet, 0=normal, 1=verbose)
  fcn->SetRefineFactor(fRefineFactor);
}
TemplateFitter::~TemplateFitter ()
Definition at line 17 of file TemplateFitter.cpp.
{
}
Member Function Documentation
int TemplateFitter::FitPulseToTemplate (TH1D * hTemplate, TH1D * hPulse, std::string bankname)
Definition at line 20 of file TemplateFitter.cpp.
References fAmplitudeScaleFactor, fAmplitudeScaleFactor_estimate, fAmplitudeScaleFactor_maximum, fAmplitudeScaleFactor_minimum, fChi2, fMinuitFitter, fNDoF, fPedestalOffset, fPedestalOffset_estimate, fPedestalOffset_maximum, fPedestalOffset_minimum, fRefineFactor, fTimeOffset, fTimeOffset_estimate, fTimeOffset_maximum, fTimeOffset_minimum, TSetupData::GetNBits(), HistogramFitFCN::GetNDoF(), TSetupData::Instance(), HistogramFitFCN::SetPulseHist(), HistogramFitFCN::SetTemplateHist(), and HistogramFitFCN::SetTimeOffset().
Referenced by TemplateCreator::ProcessEntry().
{
  int status; // the status of the minimisation
  static int print_dbg = false;
  // Calculate the max ADC value
  int n_bits = TSetupData::Instance()->GetNBits(bankname);
  double max_adc_value = std::pow(2, n_bits);
  // Prepare for minimizations
  fMinuitFitter->Clear();
  HistogramFitFCN* fcn = (HistogramFitFCN*)fMinuitFitter->GetMinuitFCN();
  fcn->SetTemplateHist(hTemplate);
  fcn->SetPulseHist(hPulse);
  //  fMinuitFitter->SetParameter(2, "TimeOffset", fTimeOffset, 1., -10, 10); // Timing should have step size no smaller than binning,
                                                    // *IF* the fourth argument is step size this is okay,
                                                    // or later implement some interpolation method, note
                                                    // *DERIVATIVES* at bounderies of interpolation may cause
                                                    // problems since MIGRAD (the default method) relies on
                                                    // these heavily.
  // Loop through some time offsets ourselved
  double max_time_offset = 4*fRefineFactor; // maximum distance to go from the initial estimate
  double best_time_offset = 0;
  double best_pedestal_offset = 0;
  double best_amplitude_scale_factor = 0;
  double best_chi2 = 99999999999;
  int best_status = -10000;
  // Calculate the bounds of the parameters
  fTimeOffset_minimum = fTimeOffset_estimate - max_time_offset;
  fTimeOffset_maximum = fTimeOffset_estimate + max_time_offset;
  fPedestalOffset_minimum = 0;
  fPedestalOffset_maximum = max_adc_value;
  fAmplitudeScaleFactor_minimum = 0.1;
  fAmplitudeScaleFactor_maximum = 100;
  for (double time_offset = fTimeOffset_minimum; time_offset <= fTimeOffset_maximum; ++time_offset) {
    if (print_dbg) {
      std::cout << "TemplateFitter: Checking time_offset = " << time_offset << std::endl;
    }
    fcn->SetTimeOffset(time_offset);
    // Reset the estimates
    fPedestalOffset = fPedestalOffset_estimate;
    fAmplitudeScaleFactor = fAmplitudeScaleFactor_estimate;
    fMinuitFitter->SetParameter(0, "PedestalOffset", fPedestalOffset, 0.1, fPedestalOffset_minimum, fPedestalOffset_maximum);
    fMinuitFitter->SetParameter(1, "AmplitudeScaleFactor", fAmplitudeScaleFactor, 0.1, fAmplitudeScaleFactor_minimum, fAmplitudeScaleFactor_maximum);
    fMinuitFitter->CreateMinimizer(TFitterMinuit::kMigrad);
    // Minimize and notify if there was a problem
    status = fMinuitFitter->Minimize(1000); // set limit of 1000 calls to FCN
    if (print_dbg) {
      if (status != 0)
        std::cout << "ERROR: Problem with fit (" << status << ")!" << std::endl;
    }
    // Get the fitted values
    fPedestalOffset = fMinuitFitter->GetParameter(0);
    fAmplitudeScaleFactor = fMinuitFitter->GetParameter(1);
    double delta_ped_offset_error = 1; // if the given parameter is within this much of the boundaries, then we will ignore it
    double delta_amp_sf_error = 0.001;
    if ( (fPedestalOffset < fPedestalOffset_minimum + delta_ped_offset_error && fPedestalOffset > fPedestalOffset_minimum - delta_ped_offset_error) ||
         (fPedestalOffset < fPedestalOffset_maximum + delta_ped_offset_error && fPedestalOffset > fPedestalOffset_maximum - delta_ped_offset_error) ) {
      if (print_dbg) {
        std::cout << "ERROR: PedestalOffset has hit a boundary (" << fPedestalOffset << ")" << std::endl;
      }
      status = -9999;
    }
    else if ( (fAmplitudeScaleFactor < fAmplitudeScaleFactor_minimum + delta_amp_sf_error && fAmplitudeScaleFactor > fAmplitudeScaleFactor_minimum - delta_amp_sf_error) ||
              (fAmplitudeScaleFactor < fAmplitudeScaleFactor_maximum + delta_amp_sf_error && fAmplitudeScaleFactor > fAmplitudeScaleFactor_maximum - delta_amp_sf_error) ) {
      if (print_dbg) {
        std::cout << "ERROR: AmplitudeScaleFactor has hit a boundary (" << fAmplitudeScaleFactor << ")" << std::endl;
      }
      status = -9999;
    }
    //    fTimeOffset = fMinuitFitter->GetParameter(2);
    // Store the Chi2, and then we can delete the pulse
    std::vector<double> params;
    params.push_back(fPedestalOffset);
    params.push_back(fAmplitudeScaleFactor);
    //    params.push_back(fTimeOffset);
    fChi2 = (*fcn)(params);
    fNDoF = fcn->GetNDoF();
    if (status == 0 && fChi2 < best_chi2) {
      best_time_offset = time_offset;
      best_pedestal_offset = fPedestalOffset;
      best_amplitude_scale_factor = fAmplitudeScaleFactor;
      best_chi2 = fChi2;
      best_status = status;
    }
    if (print_dbg) {
      std::cout << "TemplateFitter::FitPulseToTemplate(): Fit:\tChi2 " << fChi2 << "\tP "
                << fPedestalOffset << "\tA " << fAmplitudeScaleFactor << "\tT " << fTimeOffset
                << ", ndof = " << fNDoF << ", prob = " << TMath::Prob(fChi2, fNDoF) << std::endl;
    }
  }
  // Store the final best values
  fChi2 = best_chi2;
  fTimeOffset = best_time_offset;
  fPedestalOffset = best_pedestal_offset;
  fAmplitudeScaleFactor = best_amplitude_scale_factor;
  double delta_time_offset_error = 1;
  if ( (fTimeOffset < fTimeOffset_minimum + delta_time_offset_error && fTimeOffset > fTimeOffset_minimum - delta_time_offset_error) ||
       (fTimeOffset < fTimeOffset_maximum + delta_time_offset_error && fTimeOffset > fTimeOffset_maximum - delta_time_offset_error) ) {
      if (print_dbg) {
        std::cout << "ERROR: TimeOffset has hit a boundary (" << fTimeOffset << ")" << std::endl;
      }
      best_status = -9999;
  }
  return best_status; // return status for the calling module to look at
}
double TemplateFitter::GetAmplitudeScaleFactor () [inline]
Definition at line 21 of file TemplateFitter.h.
References fAmplitudeScaleFactor.
Referenced by TemplateCreator::CorrectSampleValue(), and TemplateCreator::ProcessEntry().
{ return fAmplitudeScaleFactor; }
double TemplateFitter::GetChi2 () [inline]
Definition at line 23 of file TemplateFitter.h.
References fChi2.
Referenced by TemplateCreator::ProcessEntry().
{ return fChi2; }
double TemplateFitter::GetNDoF () [inline]
Definition at line 24 of file TemplateFitter.h.
References fNDoF.
Referenced by TemplateCreator::ProcessEntry().
{ return fNDoF; }
double TemplateFitter::GetPedestalOffset () [inline]
Definition at line 20 of file TemplateFitter.h.
References fPedestalOffset.
Referenced by TemplateCreator::CorrectSampleValue(), and TemplateCreator::ProcessEntry().
{ return fPedestalOffset; }
double TemplateFitter::GetTimeOffset () [inline]
Definition at line 22 of file TemplateFitter.h.
References fTimeOffset.
Referenced by TemplateCreator::AddPulseToTemplate(), and TemplateCreator::ProcessEntry().
{ return fTimeOffset; }
void TemplateFitter::SetInitialParameterEstimates (double pedestal, double amplitude, double time)
Sets the intial estimates for the template fitter.
Definition at line 164 of file TemplateFitter.cpp.
References fAmplitudeScaleFactor_estimate, fPedestalOffset_estimate, and fTimeOffset_estimate.
Referenced by TemplateCreator::ProcessEntry().
{
  fPedestalOffset_estimate = pedestal;
  fAmplitudeScaleFactor_estimate = amplitude;
  fTimeOffset_estimate = time;
}
Member Data Documentation
double TemplateFitter::fAmplitudeScaleFactor [private]
Definition at line 29 of file TemplateFitter.h.
Referenced by FitPulseToTemplate(), and GetAmplitudeScaleFactor().
double TemplateFitter::fAmplitudeScaleFactor_estimate [private]
Definition at line 37 of file TemplateFitter.h.
Referenced by FitPulseToTemplate(), and SetInitialParameterEstimates().
double TemplateFitter::fAmplitudeScaleFactor_maximum [private]
Definition at line 49 of file TemplateFitter.h.
Referenced by FitPulseToTemplate().
double TemplateFitter::fAmplitudeScaleFactor_minimum [private]
Definition at line 43 of file TemplateFitter.h.
Referenced by FitPulseToTemplate().
IDs::channel TemplateFitter::fChannel [private]
Definition at line 27 of file TemplateFitter.h.
double TemplateFitter::fChi2 [private]
Definition at line 31 of file TemplateFitter.h.
Referenced by FitPulseToTemplate(), and GetChi2().
TFitterMinuit* TemplateFitter::fMinuitFitter [private]
Definition at line 16 of file TemplateFitter.h.
Referenced by FitPulseToTemplate(), and TemplateFitter().
int TemplateFitter::fNDoF [private]
Definition at line 32 of file TemplateFitter.h.
Referenced by FitPulseToTemplate(), and GetNDoF().
double TemplateFitter::fPedestalOffset [private]
Definition at line 28 of file TemplateFitter.h.
Referenced by FitPulseToTemplate(), and GetPedestalOffset().
double TemplateFitter::fPedestalOffset_estimate [private]
Store the initial estimates for the parameters.
Definition at line 36 of file TemplateFitter.h.
Referenced by FitPulseToTemplate(), and SetInitialParameterEstimates().
double TemplateFitter::fPedestalOffset_maximum [private]
Store the maximum parameter bounds.
Definition at line 48 of file TemplateFitter.h.
Referenced by FitPulseToTemplate().
double TemplateFitter::fPedestalOffset_minimum [private]
Store the minimum parameter bounds.
Definition at line 42 of file TemplateFitter.h.
Referenced by FitPulseToTemplate().
int TemplateFitter::fRefineFactor [private]
Definition at line 58 of file TemplateFitter.h.
Referenced by FitPulseToTemplate(), and TemplateFitter().
double TemplateFitter::fTimeOffset [private]
Definition at line 30 of file TemplateFitter.h.
Referenced by FitPulseToTemplate(), and GetTimeOffset().
double TemplateFitter::fTimeOffset_estimate [private]
Definition at line 38 of file TemplateFitter.h.
Referenced by FitPulseToTemplate(), and SetInitialParameterEstimates().
double TemplateFitter::fTimeOffset_maximum [private]
Definition at line 50 of file TemplateFitter.h.
Referenced by FitPulseToTemplate().
double TemplateFitter::fTimeOffset_minimum [private]
Definition at line 44 of file TemplateFitter.h.
Referenced by FitPulseToTemplate().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/utils/TemplateFitter.h
rootana/src/TAP_generators/utils/TemplateFitter.cpp