AlcapDAQ: MakeTemplate Class Reference
MakeTemplate Class Reference
#include <MakeTemplate.h>
Public Member Functions
MakeTemplate (char *HistogramDirectoryName)
~MakeTemplate ()
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)=0
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)=0
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
The big kahuna. Overload this in the derived class and it will be called for each event.
Private Attributes
TFile * fTemplateFile
std::map< std::string,
PulseTemplate * > fTemplates
Detailed Description
Definition at line 14 of file MakeTemplate.h.
Constructor & Destructor Documentation
MakeTemplate::MakeTemplate (char * HistogramDirectoryName)
Definition at line 15 of file MakeTemplate.cpp.
References fTemplateFile.
                                                       :
        BaseModule(HistogramDirectoryName)
{
  fTemplateFile = new TFile("template.root", "RECREATE");
  gDirectory->cd("/");
}
MakeTemplate::~MakeTemplate ()
Definition at line 22 of file MakeTemplate.cpp.
References fTemplateFile, and fTemplates.
                           { // Save and destroy templates
  std::map<std::string, PulseTemplate*>::iterator iTemplate;
  for (iTemplate = fTemplates.begin(); iTemplate != fTemplates.end(); ++iTemplate) {
    if (iTemplate->second) {
      iTemplate->second->Save(fTemplateFile);
      delete iTemplate->second;
      iTemplate->second = NULL;
    }
  }
  fTemplates.clear();
  fTemplateFile->Close();
  delete fTemplateFile;
}
Member Function Documentation
virtual int BaseModule::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [pure virtual, inherited]
Optional method which is called once after the main event loop Can be used to dump a summary or finalise a histogram
Returns:
0 on sucess and non-zero if a problem occurred
Implemented in TME_Al50_EvdE, TME_SiArmTDiff, TMEViewer, IslandAmplitude, IslandLength, FastSlowCompare, GeSpectrum, LoadPulses, PlotIntegralRatios, CalcCoarseTimeOffset, CheckTMEs, ExportPulse, PlotAmpVsMuScTDiff, PlotAmpVsTDiff, PlotTAP_Amplitude, PlotTAP_Energy, PlotTAP_Integral, PlotTAP_selfCorrelation, PlotTAP_TDiff, PlotTAP_Time, PlotTDP_TDiff, PlotTDPs, PlotTME_activeSiRmuStops, PlotTPI_PedestalAndNoise, PulseViewer, SavePulses, MakeAnalysedPulses, PulseCandidateFinder_InvestigateParameters, TemplateCreator, MakeDetectorPulses, MakeMuonEvents, and MakeSiliconEvents.
Referenced by BaseModule::Postprocess().
virtual int BaseModule::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [pure virtual, inherited]
Optional method which is called once before the main event loop Can be used to parse options and setup histograms.
Returns:
0 on sucess and non-zero if a problem occurred
Implemented in TME_Al50_EvdE, TME_SiArmTDiff, TMEViewer, IslandAmplitude, IslandLength, FastSlowCompare, GeSpectrum, LoadPulses, PlotIntegralRatios, CalcCoarseTimeOffset, CheckTMEs, ExportPulse, PlotAmpVsMuScTDiff, PlotAmpVsTDiff, PlotTAP_Amplitude, PlotTAP_Energy, PlotTAP_Integral, PlotTAP_selfCorrelation, PlotTAP_TDiff, PlotTAP_Time, PlotTDP_TDiff, PlotTDPs, PlotTME_activeSiRmuStops, PlotTPI_PedestalAndNoise, PulseViewer, SavePulses, MakeAnalysedPulses, PulseCandidateFinder_InvestigateParameters, TemplateCreator, MakeDetectorPulses, MakeMuonEvents, and MakeSiliconEvents.
Referenced by BaseModule::Preprocess().
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int MakeTemplate::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
The big kahuna. Overload this in the derived class and it will be called for each event.
Parameters:
gData Pointer to current map of all TPIs [ WILL CHANGE SHORTLY ]
gSetup Pointer to TSetupData for this run [ WILL CHANGE SHORTLY ]
Returns:
0 on success and non-zero on failure
Implements BaseModule.
Definition at line 36 of file MakeTemplate.cpp.
References PulseTemplate::AddPulse(), PulseTemplate::Chi2Fit(), PulseTemplate::Converged(), PrePulse::FindPrePulses(), TGlobalData::fPulseIslandToChannelMap, fTemplateFile, fTemplates, TSetupData::GetClockTick(), TSetupData::GetNBits(), PulseTemplate::GetNumberOfPulses(), TSetupData::GetPedestal(), TPulseIsland::GetSamples(), TSetupData::GetTriggerPolarity(), PulseTemplate::Print(), and PulseTemplate::Save().
{
  std::map< std::string, std::vector<TPulseIsland*> >& detPulses = gData->fPulseIslandToChannelMap;
  std::map< std::string, std::vector<TPulseIsland*> >::iterator iDetPulses;
  for (iDetPulses = detPulses.begin(); iDetPulses != detPulses.end(); ++iDetPulses) {
    std::string bank = iDetPulses->first;
    if (!fTemplates.count(bank))
      fTemplates[bank] = new PulseTemplate();
    PulseTemplate* pTemplate = fTemplates[bank];
    double pDT = gSetup->GetClockTick(bank);
    int pPol = gSetup->GetTriggerPolarity(bank);
    double pPed = (double)gSetup->GetPedestal(bank);
    double pMax = std::pow(2.,(double)(gSetup->GetNBits(bank))) - 1.;
    double pThresh = (pPol > 0 ? (pMax - pPed) / 2. : pPed / 2.);
    std::vector<TPulseIsland*>& pulses = iDetPulses->second;
    int iPulse = 0;
    while (!pTemplate->Converged() && iPulse < pulses.size()) {
      TPulseIsland* pulse = pulses[iPulse++];
      std::vector<PrePulse> prepulses = PrePulse::FindPrePulses(pulse, pThresh/2., pThresh/4.);
      if (prepulses.size() == 1) {
        if (pTemplate->GetNumberOfPulses() == 0) {
          // If this is the first pulse, first guess at timing is
          // weighted based on peak size relative to immediate
          // neighbors
          std::vector<int> samples = pulse->GetSamples();
          int i = prepulses.at(0).GetLocation();
          double s1 = (double)samples[i-1];
          double s2 = (double)samples[i];
          double s3 = (double)samples[i+1];
          double t = (s3 - s1) / (s1 + s2 + s3);
          pTemplate->AddPulse(pulse, t);
          pTemplate->Save(fTemplateFile);
        } else {
          double p, a, t, t0;
          p = pPed;
          a = pPol * ((double)prepulses.at(0).GetHeight() - pPed);
          t0 = (double)prepulses.at(0).GetLocation();
          t = t0;
          pTemplate->Chi2Fit(pulse, p, a, t);
          pTemplate->AddPulse(pulse, t - t0);
        }
        prepulses.at(0).Print();
        pTemplate->Print();
      }
    }
  }
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
TFile* MakeTemplate::fTemplateFile [private]
Definition at line 17 of file MakeTemplate.h.
Referenced by MakeTemplate(), ProcessEntry(), and ~MakeTemplate().
std::map<std::string, PulseTemplate*> MakeTemplate::fTemplates [private]
Definition at line 18 of file MakeTemplate.h.
Referenced by ProcessEntry(), and ~MakeTemplate().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/legacy/MakeTemplate.h
rootana/src/TAP_generators/legacy/MakeTemplate.cpp