AlcapDAQ: TIntegralRatioAnalysedPulse Class Reference
TIntegralRatioAnalysedPulse Class Reference
#include <TIntegralRatioAnalysedPulse.h>
Public Member Functions
TIntegralRatioAnalysedPulse ()
Needed by ROOT but not expected to be used.
TIntegralRatioAnalysedPulse (const IDs::source &sourceID, const TPulseIslandID &parentID, const TPulseIsland *parentTPI)
Construct a TIntegralRatioAnalysedPulse.
virtual ~TIntegralRatioAnalysedPulse ()
double GetMean () const
double GetMin () const
double GetMax () const
void SetMean (double v)
void SetMin (double v)
void SetMax (double v)
virtual void Draw (const TH1F *tpi_pulse) const
@brief overload the TAnalysedPulse::Draw method
virtual void Copy (TObject &rhs) const
void Reset (Option_t *o="")
Clear the TAP. This will probably not be used.
Getters
double GetIntegralSmall () const
double GetIntegralRatio () const
Setters
Set both the value and error for each field
void SetIntegralSmall (const double &val)
void SetIntegralRatio (const double &val)
Getters
TPulseIslandID GetParentID () const
int GetTPILength () const
double GetAmplitude () const
double GetTime () const
double GetIntegral () const
double GetEnergy () const
double GetPedestal () const
double GetTriggerTime () const
const IDs::source & GetSource () const
Setters
The TAP generators will set whatever TAP values it must through these methods. Not all need be set; the default values are obviously unphysical and several Sanity methods are provided to check if a value was set later in the analysis.
void SetParentID (const TPulseIslandID &val)
void SetTPILength (const int &val)
void SetAmplitude (const double &val)
void SetTime (const double &val)
void SetIntegral (const double &val)
void SetEnergy (const double &val)
void SetPedestal (const double &val)
void SetTriggerTime (const double &val)
void SetParentTPIProperties (const TPulseIslandID &id, const TPulseIsland *parent)
Sanity
bool IsParentIDSet () const
bool IsTPILengthSet () const
bool IsAmplitudeSet () const
bool IsTimeSet () const
bool IsIntegralSet () const
bool IsEnergySet () const
bool IsPedestalSet () const
bool IsTriggerTimeSet () const
Private Member Functions
ClassDef (TIntegralRatioAnalysedPulse, 1)
Private Attributes
double fIntegralSmall
double fIntegralRatio
double fMean
double fMin
double fMax
Detailed Description
Definition at line 7 of file TIntegralRatioAnalysedPulse.h.
Constructor & Destructor Documentation
TIntegralRatioAnalysedPulse::TIntegralRatioAnalysedPulse () [inline]
Needed by ROOT but not expected to be used.
Definition at line 10 of file TIntegralRatioAnalysedPulse.h.
:TAnalysedPulse(){};
TIntegralRatioAnalysedPulse::TIntegralRatioAnalysedPulse (const IDs::source & sourceID, const TPulseIslandID & parentID, const TPulseIsland * parentTPI) [inline]
Construct a TIntegralRatioAnalysedPulse.
Same signature as for TAnalysedPulse so that MakeNewTAP can create these specialised TAPs
Definition at line 15 of file TIntegralRatioAnalysedPulse.h.
                                                                              :
            TAnalysedPulse(sourceID,parentID,parentTPI){}
virtual TIntegralRatioAnalysedPulse::~TIntegralRatioAnalysedPulse () [inline, virtual]
Definition at line 20 of file TIntegralRatioAnalysedPulse.h.
{};
Member Function Documentation
TIntegralRatioAnalysedPulse::ClassDef (TIntegralRatioAnalysedPulse , 1) [private]
virtual void TAnalysedPulse::Copy (TObject & rhs) const [inline, virtual, inherited]
Reimplemented in TTemplateConvolveAnalysedPulse.
Definition at line 40 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude, TAnalysedPulse::fEnergy, TAnalysedPulse::fIntegral, TAnalysedPulse::fParentID, TAnalysedPulse::fPedestal, TAnalysedPulse::fSource, TAnalysedPulse::fTime, TAnalysedPulse::fTPILength, and TAnalysedPulse::fTriggerTime.
{
    TObject::Copy(rhs);
    if(rhs.InheritsFrom(Class())){
      TAnalysedPulse* tap=static_cast<TAnalysedPulse*>(&rhs);
      tap->fParentID=fParentID;
      tap->fTPILength=fTPILength;
      tap->fAmplitude=fAmplitude;
      tap->fTime=fTime;
      tap->fIntegral=fIntegral;
      tap->fEnergy=fEnergy;
      tap->fPedestal=fPedestal;
      tap->fTriggerTime=fTriggerTime;
      tap->fSource=fSource;
    }
  }
void TIntegralRatioAnalysedPulse::Draw (const TH1F * tpi_pulse) const [virtual]
@brief overload the TAnalysedPulse::Draw method
Reimplemented from TAnalysedPulse.
Definition at line 6 of file TIntegralRatioAnalysedPulse.cpp.
{
}
double TAnalysedPulse::GetAmplitude () const [inline, inherited]
Definition at line 100 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude.
Referenced by TTemplateFitAnalysedPulse::Draw(), TTemplateConvolveAnalysedPulse::Draw(), TGaussFitAnalysedPulse::Draw(), TTemplateFitAnalysedPulse::GetBinContent(), PulseViewer::GetParameterValue(), PlotTAP_selfCorrelation::PassesCutA(), TemplateFitAPGenerator::RefitWithTwo(), and TTemplateFitAnalysedPulse::SetAmplitudeScaleFactor().
{return fAmplitude;};
double TAnalysedPulse::GetEnergy () const [inline, inherited]
Definition at line 103 of file TAnalysedPulse.h.
References TAnalysedPulse::fEnergy.
Referenced by PulseViewer::GetParameterValue(), and TME_Al50_EvdE::ProcessEntry().
{return fEnergy;};
double TAnalysedPulse::GetIntegral () const [inline, inherited]
Definition at line 102 of file TAnalysedPulse.h.
References TAnalysedPulse::fIntegral.
Referenced by PulseViewer::GetParameterValue(), and PlotIntegralRatios::ProcessEntry().
{return fIntegral;};
double TIntegralRatioAnalysedPulse::GetIntegralRatio () const [inline]
Definition at line 25 of file TIntegralRatioAnalysedPulse.h.
References fIntegralRatio.
Referenced by PulseViewer::GetParameterValue(), and PlotIntegralRatios::ProcessEntry().
{return fIntegralRatio;}
double TIntegralRatioAnalysedPulse::GetIntegralSmall () const [inline]
Definition at line 24 of file TIntegralRatioAnalysedPulse.h.
References fIntegralSmall.
Referenced by PulseViewer::GetParameterValue(), and PlotIntegralRatios::ProcessEntry().
{return fIntegralSmall;}
double TIntegralRatioAnalysedPulse::GetMax () const [inline]
Definition at line 37 of file TIntegralRatioAnalysedPulse.h.
References fMax.
{return fMax;}
double TIntegralRatioAnalysedPulse::GetMean () const [inline]
Definition at line 35 of file TIntegralRatioAnalysedPulse.h.
References fMean.
{return fMean;}
double TIntegralRatioAnalysedPulse::GetMin () const [inline]
Definition at line 36 of file TIntegralRatioAnalysedPulse.h.
References fMin.
{return fMin;}
TPulseIslandID TAnalysedPulse::GetParentID () const [inline, inherited]
Definition at line 98 of file TAnalysedPulse.h.
References TAnalysedPulse::fParentID.
Referenced by ExportPulse::AddToExportList(), TTemplateFitAnalysedPulse::GetHisto(), and TemplateFitAPGenerator::RefitWithTwo().
{return fParentID;};
double TAnalysedPulse::GetPedestal () const [inline, inherited]
Definition at line 104 of file TAnalysedPulse.h.
References TAnalysedPulse::fPedestal.
Referenced by TTemplateConvolveAnalysedPulse::Draw(), TGaussFitAnalysedPulse::Draw(), TTemplateFitAnalysedPulse::GetBinContent(), PulseViewer::GetParameterValue(), and TemplateFitAPGenerator::RefitWithTwo().
{return fPedestal;};
const IDs::source& TAnalysedPulse::GetSource () const [inline, inherited]
Definition at line 106 of file TAnalysedPulse.h.
References TAnalysedPulse::fSource, and FlyWeight< ValueType, UniqueTag >::GetValue().
Referenced by ExportPulse::AddToExportList(), TTemplateConvolveAnalysedPulse::Draw(), TTemplateFitAnalysedPulse::GetHisto(), MaxTimeDiffDPGenerator::ProcessPulses(), and TDetectorPulse::TDetectorPulse().
{return fSource.GetValue();};
double TAnalysedPulse::GetTime () const [inline, inherited]
Definition at line 101 of file TAnalysedPulse.h.
References TAnalysedPulse::fTime.
Referenced by TTemplateFitAnalysedPulse::Draw(), TTemplateConvolveAnalysedPulse::Draw(), TGaussFitAnalysedPulse::Draw(), TTemplateFitAnalysedPulse::GetBinContent(), PulseViewer::GetParameterValue(), TemplateFitAPGenerator::InitializeSecondPulse(), IsTimeOrdered(), MaxTimeDiffDPGenerator::ProcessPulses(), TemplateFitAPGenerator::RefitWithTwo(), and TTemplateFitAnalysedPulse::SetTimeOffset().
{return fTime;};
int TAnalysedPulse::GetTPILength () const [inline, inherited]
Definition at line 99 of file TAnalysedPulse.h.
References TAnalysedPulse::fTPILength.
Referenced by TTemplateFitAnalysedPulse::GetHisto(), and PulseViewer::GetParameterValue().
{return fTPILength;};
double TAnalysedPulse::GetTriggerTime () const [inline, inherited]
Definition at line 105 of file TAnalysedPulse.h.
References TAnalysedPulse::fTriggerTime.
Referenced by PulseViewer::GetParameterValue().
{return fTriggerTime;};
bool TAnalysedPulse::IsAmplitudeSet () const [inline, inherited]
Definition at line 135 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude, and TAnalysedPulse::fDefaultValue.
{return fAmplitude!=fDefaultValue;};
bool TAnalysedPulse::IsEnergySet () const [inline, inherited]
Definition at line 138 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fEnergy.
{return fEnergy!=fDefaultValue;};
bool TAnalysedPulse::IsIntegralSet () const [inline, inherited]
Definition at line 137 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fIntegral.
{return fIntegral!=fDefaultValue;};
bool TAnalysedPulse::IsParentIDSet () const [inline, inherited]
Definition at line 133 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fParentID.
{return fParentID!=fDefaultValue;};
bool TAnalysedPulse::IsPedestalSet () const [inline, inherited]
Definition at line 139 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fPedestal.
{return fPedestal!=fDefaultValue;};
bool TAnalysedPulse::IsTimeSet () const [inline, inherited]
Definition at line 136 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTime.
{return fTime!=fDefaultValue;};
bool TAnalysedPulse::IsTPILengthSet () const [inline, inherited]
Definition at line 134 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTPILength.
{return fTPILength!=fDefaultValue;};
bool TAnalysedPulse::IsTriggerTimeSet () const [inline, inherited]
Definition at line 140 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTriggerTime.
{return fTriggerTime!=fDefaultValue;};
void TAnalysedPulse::Reset (Option_t * o = "") [inherited]
Clear the TAP. This will probably not be used.
Definition at line 42 of file TAnalysedPulse.cpp.
References TAnalysedPulse::fAmplitude, TAnalysedPulse::fDefaultValue, TAnalysedPulse::fEnergy, TAnalysedPulse::fIntegral, TAnalysedPulse::fParentID, TAnalysedPulse::fPedestal, TAnalysedPulse::fTime, TAnalysedPulse::fTPILength, and TAnalysedPulse::fTriggerTime.
{
  fParentID=fDefaultValue;
  fTPILength=fDefaultValue;
  fAmplitude=fDefaultValue;
  fTime=fDefaultValue;
  fIntegral=fDefaultValue;
  fEnergy=fDefaultValue;
  fPedestal=fDefaultValue;
  fTriggerTime=fDefaultValue;
}
void TAnalysedPulse::SetAmplitude (const double & val) [inline, inherited]
Definition at line 120 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateConvolveAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), IntegralRatioAPGenerator::ProcessPulses(), and CFTimeMBAmpAPGenerator::ProcessPulses().
{ fAmplitude=val;};
void TAnalysedPulse::SetEnergy (const double & val) [inline, inherited]
Definition at line 123 of file TAnalysedPulse.h.
References TAnalysedPulse::fEnergy.
{ fEnergy=val;};
void TAnalysedPulse::SetIntegral (const double & val) [inline, inherited]
Definition at line 122 of file TAnalysedPulse.h.
References TAnalysedPulse::fIntegral.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateFitAPGenerator::ProcessPulses(), TemplateConvolveAPGenerator::ProcessPulses(), SimpIntAPGenerator::ProcessPulses(), and IntegralRatioAPGenerator::ProcessPulses().
{ fIntegral=val;};
void TIntegralRatioAnalysedPulse::SetIntegralRatio (const double & val) [inline]
Definition at line 32 of file TIntegralRatioAnalysedPulse.h.
References fIntegralRatio.
Referenced by IntegralRatioAPGenerator::ProcessPulses().
{fIntegralRatio=val;}
void TIntegralRatioAnalysedPulse::SetIntegralSmall (const double & val) [inline]
Definition at line 31 of file TIntegralRatioAnalysedPulse.h.
References fIntegralSmall.
Referenced by IntegralRatioAPGenerator::ProcessPulses().
{fIntegralSmall=val;}
void TIntegralRatioAnalysedPulse::SetMax (double v) [inline]
Definition at line 41 of file TIntegralRatioAnalysedPulse.h.
References fMax.
{fMax =v;}
void TIntegralRatioAnalysedPulse::SetMean (double v) [inline]
Definition at line 39 of file TIntegralRatioAnalysedPulse.h.
References fMean.
{fMean=v;}
void TIntegralRatioAnalysedPulse::SetMin (double v) [inline]
Definition at line 40 of file TIntegralRatioAnalysedPulse.h.
References fMin.
{fMin =v;}
void TAnalysedPulse::SetParentID (const TPulseIslandID & val) [inline, inherited]
Definition at line 118 of file TAnalysedPulse.h.
References TAnalysedPulse::fParentID.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fParentID=val;};
void TAnalysedPulse::SetParentTPIProperties (const TPulseIslandID & id, const TPulseIsland * parent) [inherited]
Definition at line 65 of file TAnalysedPulse.cpp.
References TPulseIsland::GetClockTickInNs(), TPulseIsland::GetPulseLength(), TPulseIsland::GetTimeStamp(), TAnalysedPulse::SetParentID(), TAnalysedPulse::SetTPILength(), and TAnalysedPulse::SetTriggerTime().
Referenced by TAnalysedPulse::TAnalysedPulse().
{
  SetParentID(id);
  if(!pulse) {
    std::cerr<<"NULL pointer to TPulseIsland passed as parent for TAnalysedPulse."<<std::endl;
    return;
  }
  SetTPILength(pulse->GetPulseLength());
  SetTriggerTime(pulse->GetTimeStamp()*pulse->GetClockTickInNs());
}
void TAnalysedPulse::SetPedestal (const double & val) [inline, inherited]
Definition at line 124 of file TAnalysedPulse.h.
References TAnalysedPulse::fPedestal.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{ fPedestal=val;};
void TAnalysedPulse::SetTime (const double & val) [inline, inherited]
Definition at line 121 of file TAnalysedPulse.h.
References TAnalysedPulse::fTime.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateConvolveAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), IntegralRatioAPGenerator::ProcessPulses(), CFTimeMBAmpAPGenerator::ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{ fTime=val;};
void TAnalysedPulse::SetTPILength (const int & val) [inline, inherited]
Definition at line 119 of file TAnalysedPulse.h.
References TAnalysedPulse::fTPILength.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fTPILength=val;};
void TAnalysedPulse::SetTriggerTime (const double & val) [inline, inherited]
Definition at line 125 of file TAnalysedPulse.h.
References TAnalysedPulse::fTriggerTime.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fTriggerTime=val;};
Member Data Documentation
double TIntegralRatioAnalysedPulse::fIntegralRatio [private]
Definition at line 48 of file TIntegralRatioAnalysedPulse.h.
Referenced by GetIntegralRatio(), and SetIntegralRatio().
double TIntegralRatioAnalysedPulse::fIntegralSmall [private]
Definition at line 47 of file TIntegralRatioAnalysedPulse.h.
Referenced by GetIntegralSmall(), and SetIntegralSmall().
double TIntegralRatioAnalysedPulse::fMax [private]
Definition at line 52 of file TIntegralRatioAnalysedPulse.h.
Referenced by GetMax(), and SetMax().
double TIntegralRatioAnalysedPulse::fMean [private]
Definition at line 50 of file TIntegralRatioAnalysedPulse.h.
Referenced by GetMean(), and SetMean().
double TIntegralRatioAnalysedPulse::fMin [private]
Definition at line 51 of file TIntegralRatioAnalysedPulse.h.
Referenced by GetMin(), and SetMin().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/TIntegralRatioAnalysedPulse.h
rootana/src/TAP_generators/TIntegralRatioAnalysedPulse.cpp