AlcapDAQ: tut::test_runner Class Reference
tut::test_runner Class Reference
#include <tut.h>
Public Member Functions
test_runner ()
void register_group (const std::string &name, group_base *gr)
void set_callback (callback *cb)
callback & get_callback () const
const groupnames list_groups () const
void run_tests () const
void run_tests (const std::string &group_name) const
test_result run_test (const std::string &group_name, int n) const
Protected Types
typedef std::map< std::string,
group_base * > groups
typedef groups::iterator iterator
typedef groups::const_iterator const_iterator
Protected Attributes
groups groups_
callback default_callback_
callback * callback_
Private Member Functions
void run_all_tests_in_group_ (const_iterator i) const
Detailed Description
Test runner.
Definition at line 220 of file tut.h.
Member Typedef Documentation
typedef groups::const_iterator tut::test_runner::const_iterator [protected]
Definition at line 225 of file tut.h.
typedef std::map<std::string,group_base*> tut::test_runner::groups [protected]
Definition at line 223 of file tut.h.
typedef groups::iterator tut::test_runner::iterator [protected]
Definition at line 224 of file tut.h.
Constructor & Destructor Documentation
tut::test_runner::test_runner () [inline]
Constructor
Definition at line 235 of file tut.h.
                  : callback_(&default_callback_)
    {
    }
Member Function Documentation
callback& tut::test_runner::get_callback () const [inline]
Returns callback object.
Definition at line 272 of file tut.h.
References callback_.
    {
      return *callback_;
    }
const groupnames tut::test_runner::list_groups () const [inline]
Returns list of known test groups.
Definition at line 280 of file tut.h.
References groups_.
    {
      groupnames ret;
      const_iterator i = groups_.begin();
      const_iterator e = groups_.end();
      while( i != e )
      {
        ret.push_back(i->first);
        ++i;
      }
      return ret;
    }
void tut::test_runner::register_group (const std::string & name, group_base * gr) [inline]
Stores another group for getting by name.
Definition at line 242 of file tut.h.
References groups_.
Referenced by tut::test_group< Data, MaxTestsInGroup >::test_group().
    {
      if( gr == 0 )
      {
        throw std::invalid_argument("group shall be non-null");
      }
      groups::iterator found = groups_.find(name);
      if( found != groups_.end() )
      {
        std::string msg("attempt to add already existent group "+name);
        // this exception terminates application so we use cerr also
        std::cerr << msg << std::endl;
        throw std::logic_error(msg);
      }
      groups_[name] = gr;
    }
void tut::test_runner::run_all_tests_in_group_ (const_iterator i) const [inline, private]
Definition at line 381 of file tut.h.
References callback_, tut::test_result::ex_ctor, tut::test_result::result, and tut::callback::test_completed().
Referenced by run_tests().
    {
      i->second->rewind();
      for( ;; )
      {
        test_result tr = i->second->run_next();
        callback_->test_completed(tr);
        if( tr.result == test_result::ex_ctor )
        {
          throw no_more_tests();
        }
      }
    }
test_result tut::test_runner::run_test (const std::string & group_name, int n) const [inline]
Runs one test in specified group.
Definition at line 350 of file tut.h.
References callback_, groups_, tut::callback::run_completed(), tut::callback::run_started(), and tut::callback::test_completed().
    {
      callback_->run_started();
      const_iterator i = groups_.find(group_name);
      if( i == groups_.end() )
      {
        throw no_such_group(group_name);
      }
      try
      {
        test_result tr = i->second->run_test(n);
        callback_->test_completed(tr);
        i->second->group_completed();
        callback_->run_completed();
        return tr;
      }
      catch( const beyond_last_test& )
      {
        callback_->run_completed();
        throw;
      }
      catch( const no_such_test& )
      {
        callback_->run_completed();
        throw;
      }
    }
void tut::test_runner::run_tests (const std::string & group_name) const [inline]
Runs all tests in specified group.
Definition at line 324 of file tut.h.
References callback_, groups_, run_all_tests_in_group_(), tut::callback::run_completed(), and tut::callback::run_started().
    {
      callback_->run_started();
      const_iterator i = groups_.find(group_name);
      if( i == groups_.end() )
      {
        throw no_such_group(group_name);
      }
      try
      {
        run_all_tests_in_group_(i);
      }
      catch( const no_more_tests& )
      {
        // ok
        i->second->group_completed();
      }
      callback_->run_completed();
    }
void tut::test_runner::run_tests () const [inline]
Runs all tests in all groups.
Parameters:
callback Callback object if exists; null otherwise
Definition at line 297 of file tut.h.
References callback_, groups_, run_all_tests_in_group_(), tut::callback::run_completed(), and tut::callback::run_started().
    {
      callback_->run_started();
      const_iterator i = groups_.begin();
      const_iterator e = groups_.end();
      while( i != e )
      {
        try
        {
          run_all_tests_in_group_(i);
        }
        catch( const no_more_tests& )
        {
          // ok
          i->second->group_completed();
        }
        ++i;
      }
      callback_->run_completed();
    }
void tut::test_runner::set_callback (callback * cb) [inline]
Stores callback object.
Definition at line 264 of file tut.h.
References callback_, and default_callback_.
    {
      callback_ = cb==0? &default_callback_:cb;
    }
Field Documentation
callback* tut::test_runner::callback_ [protected]
Definition at line 229 of file tut.h.
Referenced by get_callback(), run_all_tests_in_group_(), run_test(), run_tests(), and set_callback().
callback tut::test_runner::default_callback_ [protected]
Definition at line 228 of file tut.h.
Referenced by set_callback().
groups tut::test_runner::groups_ [protected]
Definition at line 226 of file tut.h.
Referenced by list_groups(), register_group(), run_test(), and run_tests().
The documentation for this class was generated from the following file:
rootana/src/unit_test/tut.h