AlcapDAQ: DeadTimeGe Class Reference
DeadTimeGe Class Reference
#include <DeadTimeGe.h>
Public Member Functions
DeadTimeGe (char *HistogramDirectoryName)
~DeadTimeGe ()
virtual int ProcessEntry (TGlobalData *gData, TSetupData *gSetup)
int ProcessGenericEntry (TGlobalData *gData, TSetupData *gSetup)
virtual int BeforeFirstEntry (TGlobalData *gData, TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, TSetupData *setup)
const char * GetName () const
Protected Member Functions
bool Debug () const
Protected Attributes
TDirectory * dir
TSetupData * fSetup
Detailed Description
Definition at line 8 of file DeadTimeGe.h.
Constructor & Destructor Documentation
DeadTimeGe::DeadTimeGe (char * HistogramDirectoryName)
Definition at line 27 of file DeadTimeGe.cpp.
References FillHistBase::dir.
                                                    :
   FillHistBase(HistogramDirectoryName){
   dir->cd("/");
 }
DeadTimeGe::~DeadTimeGe ()
Definition at line 32 of file DeadTimeGe.cpp.
{
 }
Member Function Documentation
virtual int FillHistBase::AfterLastEntry (TGlobalData * gData, TSetupData * setup) inline virtual inherited
Reimplemented in TestModule.
Definition at line 39 of file FillHistBase.h.
 {return 0;};
virtual int FillHistBase::BeforeFirstEntry (TGlobalData * gData, TSetupData * setup) inline virtual inherited
Reimplemented in ExportPulse, MakeAnalysedPulses, MakeDetectorPulses, MakeMuonEvents, and TestModule.
Definition at line 38 of file FillHistBase.h.
 {return 0;};
bool FillHistBase::Debug () const inline protected inherited
Definition at line 45 of file FillHistBase.h.
References FillHistBase::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), TestModule::AfterLastEntry(), TestModule::BeforeFirstEntry(), MakeMuonEvents::BeforeFirstEntry(), MakeDetectorPulses::MakeGenerator(), ExportPulse::MakePlot(), and MakeAnalysedPulses::ProcessEntry().
 {return fDebug;};
const char* FillHistBase::GetName () const inline inherited
Definition at line 40 of file FillHistBase.h.
References FillHistBase::dir.
Referenced by ProcessEntry(), PlotTime::ProcessEntry(), and PlotAmplitude::ProcessEntry().
 {return dir->GetName();};
int DeadTimeGe::ProcessEntry (TGlobalData * gData, TSetupData * gSetup) virtual
Reimplemented from FillHistBase.
Definition at line 35 of file DeadTimeGe.cpp.
References gAnalysedPulseMap, FillHistBase::GetName(), and i.
{
   std::string detname = "Ge-S";
   AnalysedPulseList detA_pulses = gAnalysedPulseMap[detname];
   AnalysedPulseList::iterator currentDetAPulse = detA_pulses.begin();
   if (timediff_plots.find(detname) == timediff_plots.end())
   {
         std::string histname = "h" + detname + "_" + GetName();
         std::string histtitle = "Time difference between to consecutive pulses on " + detname;
         TH1F * htimediff = new TH1F(histname.c_str(), histtitle.c_str(),
                         1e6, 10, 4.2e7);
         htimediff->GetXaxis()->SetTitle("Time [ns]");
         htimediff->GetYaxis()->SetTitle("Arbitary unit");
         timediff_plots[detname] = htimediff;
   }
   std::vector<double> detA_times;
   for (AnalysedPulseList::iterator detAPulseIter = currentDetAPulse;
                 detAPulseIter != detA_pulses.end(); ++detAPulseIter)
   {
         double detA_time = (*detAPulseIter)->GetTime();
         detA_times.push_back(detA_time);
   }
   for (unsigned int i = 0; i < detA_times.size()-1; ++i)
   {
         //printf("%.2f %.2f %.2f\n", detA_times.at(i+1), detA_times.at(i),
                         //detA_times.at(i+1) - detA_times.at(i));
         timediff_plots[detname]->Fill(detA_times.at(i+1) - detA_times.at(i));
   }
   return 0;
 }
int FillHistBase::ProcessGenericEntry (TGlobalData * gData, TSetupData * gSetup) inherited
Definition at line 24 of file FillHistBase.cpp.
References FillHistBase::dir, and FillHistBase::ProcessEntry().
{
   // This is called by our main routine and would allow later to split into different
   // process routines if we have more than one Tree and hence different tpyes of data input.
   if(dir) dir->cd();
   int ret = ProcessEntry(gData, gSetup);
   gDirectory->cd("/");
   return ret;
 }
Field Documentation
TDirectory* FillHistBase::dir protected inherited
Definition at line 40 of file FillHistBase.h.
Referenced by DeadTimeGe(), ExportPulse::ExportPulse(), FillHistBase::FillHistBase(), FillHistBase::GetName(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmplitude::PlotAmplitude(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTime::PlotTime(), and FillHistBase::ProcessGenericEntry().
TSetupData* FillHistBase::fSetup protected inherited
Definition at line 44 of file FillHistBase.h.
The documentation for this class was generated from the following files:
analyzer/rootana/src/physics/DeadTimeGe.h
analyzer/rootana/src/physics/DeadTimeGe.cpp