AlcapDAQ: LoopSequence Class Reference
LoopSequence Class Reference
#include <LoopSequence.h>
Public Member Functions
void Run () const
Long64_t StartEntry () const
Long64_t StopEntry () const
const ARGUMENTS & GetCommandLineArgs ()
Protected Member Functions
LoopSequence (const ARGUMENTS &args)
LoopSequence (const LoopSequence &src)
LoopSequence & operator= (const LoopSequence &rhs)
void Init ()
void Preprocess () const
void Process () const
void Postprocess () const
void Checkpoint (Long64_t entry) const
Private Attributes
const ARGUMENTS fArgs
Long64_t fStart
Long64_t fStop
Friends
class EventNavigator
Detailed Description
Definition at line 14 of file LoopSequence.h.
Constructor & Destructor Documentation
LoopSequence::LoopSequence (const ARGUMENTS & args) [inline, protected]
Definition at line 26 of file LoopSequence.h.
References Init().
    : fArgs(args)
  {
    Init();
  }
LoopSequence::LoopSequence (const LoopSequence & src) [protected]
Member Function Documentation
void LoopSequence::Checkpoint (Long64_t entry) const [protected]
Definition at line 183 of file LoopSequence.cpp.
References fStart, and fStop.
Referenced by Process().
{
  Long64_t n = entry-fStart;
  static Long64_t nTot = fStop-fStart;
  static int nDig = 1+std::floor(std::log10(nTot));
  if ( n  < 10 || n %(nTot/10)==0 ) {
    std::cout << "Processed  " << std::setw(nDig) << n
              << "/" << std::setw(nDig) << nTot
              << "  (" <<std::setw(2)<< std::floor((100.*n) / nTot)
              << "%)" << std::endl;
  }
  return;
}
const ARGUMENTS& LoopSequence::GetCommandLineArgs () [inline]
Definition at line 22 of file LoopSequence.h.
References fArgs.
{return fArgs;}
void LoopSequence::Init () [protected]
Definition at line 63 of file LoopSequence.cpp.
References fArgs, fStart, fStop, EventNavigator::GetInputNEntries(), EventNavigator::Instance(), ARGUMENTS::start, and ARGUMENTS::stop.
Referenced by LoopSequence().
{
  // How many entries should we loop over?
  Long64_t nEntries = EventNavigator::Instance().GetInputNEntries();
  bool has_start = (fArgs.start > 0) && (fArgs.start < nEntries);
  fStart = (has_start) ? fArgs.start : 0;
  bool has_stop = (fArgs.stop > 0) && (fArgs.stop < nEntries);
  fStop = (has_stop) ? fArgs.stop : nEntries;
}
LoopSequence& LoopSequence::operator= (const LoopSequence & rhs) [protected]
void LoopSequence::Postprocess () const [protected]
Definition at line 120 of file LoopSequence.cpp.
References modules::navigator::Begin(), modules::navigator::End(), fStop, EventNavigator::GetRawData(), EventNavigator::GetSetupData(), modules::navigator::Instance(), EventNavigator::Instance(), and BaseModule::Postprocess().
Referenced by Run().
{
  EventNavigator& enav = EventNavigator::Instance();
  int err_code =0;
  modules::navigator& mn = *modules::navigator::Instance();
  BaseModule* mod =NULL;
  for (modules::iterator it = mn.Begin(); it != mn.End() && !err_code; ++it) {
    mod = it->second;
    err_code |= mod->Postprocess(enav.GetRawData(), enav.GetSetupData());
  }
  if ( err_code ) throw postprocess_error(fStop-1,mod);
}
void LoopSequence::Preprocess () const [protected]
Definition at line 75 of file LoopSequence.cpp.
References modules::navigator::Begin(), modules::navigator::End(), fStart, EventNavigator::GetEntry(), EventNavigator::GetRawData(), EventNavigator::GetSetupData(), modules::navigator::Instance(), EventNavigator::Instance(), and BaseModule::Preprocess().
Referenced by Run().
{
  EventNavigator& enav = EventNavigator::Instance();
  enav.GetEntry(fStart);
  int err_code =0;
  modules::navigator& mn = *modules::navigator::Instance();
  BaseModule* mod =NULL;
  for (modules::iterator it = mn.Begin(); it != mn.End() && !err_code; ++it) {
    mod = it->second;
    err_code |= mod->Preprocess(enav.GetRawData(), enav.GetSetupData());
  }
  if (err_code) throw preprocess_error(fStart,mod);
}
void LoopSequence::Process () const [protected]
Definition at line 91 of file LoopSequence.cpp.
References modules::navigator::Begin(), Checkpoint(), TGlobalData::Clear(), ClearGlobalData(), modules::navigator::End(), fStart, fStop, EventNavigator::GetEntry(), EventNavigator::GetRawData(), EventNavigator::GetSetupData(), modules::navigator::Instance(), EventNavigator::Instance(), and BaseModule::ProcessGenericEntry().
Referenced by Run().
{
  EventNavigator& enav = EventNavigator::Instance();
  BaseModule* mod =NULL;
  for (Long64_t jentry = fStart; jentry < fStop; ++jentry){
    //This to move unrder event navigator
    TGlobalData* raw_data = enav.GetRawData();
    if (raw_data){
      raw_data->Clear("C");
      ClearGlobalData(raw_data);
    }
    Checkpoint(jentry);
    enav.GetEntry(jentry);
    int err_code = 0;
    modules::navigator& mn = *modules::navigator::Instance();
    for (modules::iterator it = mn.Begin(); it != mn.End() && ! err_code; ++it) {
      mod = it->second;
      err_code |= mod->ProcessGenericEntry(raw_data,enav.GetSetupData());
    }
    if (err_code) throw process_error(jentry,mod);
  }
  return;
}
void LoopSequence::Run () const
Definition at line 135 of file LoopSequence.cpp.
References Except::Base::bt(), module_error::fEvent, module_error::fModule, BaseModule::GetName(), Postprocess(), Preprocess(), Process(), and Except::Base::what().
Referenced by Main_event_loop().
{
  try {
    this->Preprocess();
    this->Process();
    this->Postprocess();
  }
  catch (preprocess_error& e){
    std::cout << "\nError while preprocessing first entry ("
              << e.fEvent << ")";
    if(e.fModule) std::cout<<" for module "<<e.fModule->GetName();
  }
  catch (process_error& e){
    try{
        // try to let each module finish to save plots etc
        this->Postprocess();
    } catch(...) {
        // if postprocess throws an error assume it's related to the process
        // error
        if(e.fModule) std::cout<<"\nModule "<<e.fModule->GetName();
        else std::cout << "\nA module";
        std::cout<<" returned non-zero on entry " << e.fEvent;
        throw;
    }
    if(e.fModule) std::cout<<"\nModule "<<e.fModule->GetName();
    else std::cout << "\nA module";
    std::cout<<" returned non-zero on entry " << e.fEvent;
  }
  catch (postprocess_error& e){
    if(e.fModule) std::cout<<"\nModule "<<e.fModule->GetName();
    else std::cout << "\nA module";
    std::cout<<" returned non-zero on during post-processing last entry " << e.fEvent;
  }
  catch (module_error& e){
    if(e.fModule) std::cout<<"\nModule "<<e.fModule->GetName();
    else std::cout << "\nA module";
    std::cout<<" returned non-zero on during pre-processing first entry " << e.fEvent;
  }
  catch (Except::Base& e){
      std::cout<<"Alcap exception was thrown: "<<std::endl;
      std::cout<<e.what()<<std::endl;
      std::cout<<e.bt()<<std::endl;
  }
  std::cout << std::endl;
}
Long64_t LoopSequence::StartEntry () const [inline]
Definition at line 19 of file LoopSequence.h.
References fStart.
Referenced by EventNavigator::GetStartEntry().
{return fStart;}
Long64_t LoopSequence::StopEntry () const [inline]
Definition at line 20 of file LoopSequence.h.
References fStop.
Referenced by EventNavigator::GetStopEntry().
{return fStop;}
Friends And Related Function Documentation
friend class EventNavigator [friend]
Definition at line 15 of file LoopSequence.h.
Member Data Documentation
const ARGUMENTS LoopSequence::fArgs [private]
Definition at line 42 of file LoopSequence.h.
Referenced by GetCommandLineArgs(), and Init().
Long64_t LoopSequence::fStart [private]
Definition at line 43 of file LoopSequence.h.
Referenced by Checkpoint(), Init(), Preprocess(), Process(), and StartEntry().
Long64_t LoopSequence::fStop [private]
Definition at line 44 of file LoopSequence.h.
Referenced by Checkpoint(), Init(), Postprocess(), Process(), and StopEntry().
The documentation for this class was generated from the following files:
rootana/src/framework/LoopSequence.h
rootana/src/framework/LoopSequence.cpp