AlcapDAQ: PlotTAP_selfCorrelation Class Reference
PlotTAP_selfCorrelation Class Reference
[Modules]
A one line description of what your module does.
#include <PlotTAP_selfCorrelation.h>
Public Member Functions
PlotTAP_selfCorrelation (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~PlotTAP_selfCorrelation ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::map< std::string,
std::vector< TH2F * > > HistList
typedef std::vector< IDs::source > SourceList
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
void BookHistograms (const TSetupData *)
Prepare histograms.
bool PassesCutA (const TAnalysedPulse *tap) const
bool PassesMuScCut (const TAnalysedPulse *tap, const AnalysedPulseList &) const
Private Attributes
std::string fDetNameA
std::string fDetNameB
double fTimeLow
double fTimeHigh
double fMinAmpA
double fMaxAmpA
double fMuScWindow
HistList fHists
SourceList fDetASources
SourceList fDetBSources
IDs::source fMuScSource
Detailed Description
A one line description of what your module does.
Author:
AuthorName
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 27 of file PlotTAP_selfCorrelation.h.
Member Typedef Documentation
typedef std::map<std::string, std::vector<TH2F*> > PlotTAP_selfCorrelation::HistList [private]
Definition at line 70 of file PlotTAP_selfCorrelation.h.
typedef std::vector<IDs::source> PlotTAP_selfCorrelation::SourceList [private]
Definition at line 73 of file PlotTAP_selfCorrelation.h.
Constructor & Destructor Documentation
PlotTAP_selfCorrelation::PlotTAP_selfCorrelation (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 17 of file PlotTAP_selfCorrelation.cpp.
                                                                    :
  BaseModule("PlotTAP_selfCorrelation",opts),
  fDetNameA(opts->GetString("det1")), fDetNameB(opts->GetString("det2")),
  fTimeLow(opts->GetDouble("time_low",-1.e5)),
  fTimeHigh(opts->GetDouble("time_high",1.e5)),
  fMinAmpA(opts->GetDouble("min_amp",0)),
  fMaxAmpA(opts->GetDouble("max_amp",1e20)),
  fMuScWindow(opts->GetDouble("musc_window",10)*1e3){
}
PlotTAP_selfCorrelation::~PlotTAP_selfCorrelation ()
Is anything done in the destructor?
Definition at line 27 of file PlotTAP_selfCorrelation.cpp.
{
}
Member Function Documentation
int PlotTAP_selfCorrelation::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 96 of file PlotTAP_selfCorrelation.cpp.
{
  return 0;
}
int PlotTAP_selfCorrelation::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 30 of file PlotTAP_selfCorrelation.cpp.
References BookHistograms(), fDetASources, fDetBSources, fDetNameA, fDetNameB, fMuScSource, and gAnalysedPulseMap.
{
IDs::channel muSc("muSc");
  for(SourceAnalPulseMap::const_iterator sourceIt = gAnalysedPulseMap.begin();
      sourceIt != gAnalysedPulseMap.end(); sourceIt++) {
    // only use the last matching muSc source for now
    if( sourceIt->first.matches(muSc)) fMuScSource=sourceIt->first;
    if( sourceIt->first.Channel() != fDetNameA)
      continue;   //check for detector A
    for(SourceAnalPulseMap::const_iterator sourceIt2 = gAnalysedPulseMap.begin(); sourceIt2 != gAnalysedPulseMap.end(); ++sourceIt2)
      {
        if(sourceIt2->first.Channel() != fDetNameB)
          continue;  //check for detector B
        //I should make a vector of the sources for detA and detB
        fDetASources.push_back(sourceIt->first);
        fDetBSources.push_back(sourceIt2->first);
        break;
      }
  }
  BookHistograms(setup);
  return 0;
}
void PlotTAP_selfCorrelation::BookHistograms (const TSetupData * setup) [private]
Prepare histograms.
Definition at line 100 of file PlotTAP_selfCorrelation.cpp.
References fDetASources, fDetNameA, fDetNameB, fHists, fTimeHigh, fTimeLow, TSetupData::GetBankName(), and TSetupData::GetNBits().
Referenced by BeforeFirstEntry().
{
  for (unsigned int i = 0; i < fDetASources.size(); ++i) {
    const std::string gen = fDetASources.at(i).Generator().str();
    const int maxAmpA = std::pow(2, setup->GetNBits(setup->GetBankName(fDetNameA)));
    const int maxAmpB = std::pow(2, setup->GetNBits(setup->GetBankName(fDetNameB)));
    std::vector<TH2F*>& hists = fHists[fDetASources.at(i).str()];
    //ampA plots
    std::string histname("hTDiff_AmpA");
    std::string histtitle="Amplitude of " + fDetNameA + " vs time difference with " + fDetNameB
              + " detectors with the " + gen + " generator;Time Difference (ns);Amplitude (ADC counts)";
    hists.push_back(new TH2F(histname.c_str(), histtitle.c_str(), 200, fTimeLow, fTimeHigh, 200, 0, maxAmpA));
    //ampB plots
    histname = "hTDiff_AmpB";
    histtitle = "Amplitude of " + fDetNameB + " vs time difference with " + fDetNameA
              + " detectors with the " + gen + " generator;Time Difference (ns);Amplitude (ADC counts)";
    hists.push_back(new TH2F(histname.c_str(), histtitle.c_str(), 200, fTimeLow, fTimeHigh, 200, 0, maxAmpB));
    //intA plots
    histname = "hTDiff_IntA";
    histtitle = "Integral of " + fDetNameA + " vs time difference with " + fDetNameB
              + " detectors with the " + gen + " generator;Time Difference (ns);Integral (ADC counts)";
    hists.push_back(new TH2F(histname.c_str(), histtitle.c_str(), 200, fTimeLow, fTimeHigh, 200, 0, 5*maxAmpA));
    //intB plots
    histname = "hTDiff_IntB";
    histtitle = "Integral of " + fDetNameB + " vs time difference with " + fDetNameA
              + " detectors with the " + gen + " generator;Time Difference (ns);Integral (ADC counts)";
    hists.push_back(new TH2F(histname.c_str(), histtitle.c_str(), 200, fTimeLow, fTimeHigh, 200, 0, 5*maxAmpB));
  }
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
bool PlotTAP_selfCorrelation::PassesCutA (const TAnalysedPulse * tap) const [private]
Definition at line 86 of file PlotTAP_selfCorrelation.cpp.
References fMaxAmpA, and TAnalysedPulse::GetAmplitude().
Referenced by ProcessEntry().
{
  const double amp=tap->GetAmplitude();
  if(amp < fMinAmpA || amp > fMaxAmpA) return false;
  return true;
}
bool PlotTAP_selfCorrelation::PassesMuScCut (const TAnalysedPulse * tap, const AnalysedPulseList & muScPulseList) const [private]
Definition at line 92 of file PlotTAP_selfCorrelation.cpp.
Referenced by ProcessEntry().
{
  return true;
}
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int PlotTAP_selfCorrelation::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 58 of file PlotTAP_selfCorrelation.cpp.
References fDetASources, fDetBSources, fHists, fMuScSource, gAnalysedPulseMap, PassesCutA(), and PassesMuScCut().
{
  const AnalysedPulseList& muScPulseList=gAnalysedPulseMap.at(fMuScSource);
  for(unsigned int i = 0; i < fDetASources.size(); ++i) {
    const AnalysedPulseList& detAPulses = gAnalysedPulseMap[fDetASources[i]];
    const AnalysedPulseList& detBPulses = gAnalysedPulseMap[fDetBSources[i]];
    const std::vector<TH2F*>& hists = fHists[fDetASources[i].str()];
    for(AnalysedPulseList::const_iterator pulseIt = detAPulses.begin();
        pulseIt != detAPulses.end(); ++pulseIt) {
      if(!PassesCutA(*pulseIt)) continue;
      if(!PassesMuScCut(*pulseIt, muScPulseList)) continue;
      for(AnalysedPulseList::const_iterator pulseIt2 = detBPulses.begin();
          pulseIt2 != detBPulses.end(); ++pulseIt2) {
        double tDiff = (*pulseIt)->GetTime() - (*pulseIt2)->GetTime();
        hists[0]->Fill(tDiff, (*pulseIt)->GetAmplitude());
        hists[1]->Fill(tDiff, (*pulseIt2)->GetAmplitude());
        hists[2]->Fill(tDiff, (*pulseIt)->GetIntegral());
        hists[3]->Fill(tDiff, (*pulseIt2)->GetIntegral());
      }//end detBPulse loop
    }//end detAPulse loop
  }//end sources loop
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
SourceList PlotTAP_selfCorrelation::fDetASources [private]
Definition at line 74 of file PlotTAP_selfCorrelation.h.
Referenced by BeforeFirstEntry(), BookHistograms(), and ProcessEntry().
SourceList PlotTAP_selfCorrelation::fDetBSources [private]
Definition at line 74 of file PlotTAP_selfCorrelation.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
std::string PlotTAP_selfCorrelation::fDetNameA [private]
Definition at line 65 of file PlotTAP_selfCorrelation.h.
Referenced by BeforeFirstEntry(), and BookHistograms().
std::string PlotTAP_selfCorrelation::fDetNameB [private]
Definition at line 65 of file PlotTAP_selfCorrelation.h.
Referenced by BeforeFirstEntry(), and BookHistograms().
HistList PlotTAP_selfCorrelation::fHists [private]
Definition at line 71 of file PlotTAP_selfCorrelation.h.
Referenced by BookHistograms(), and ProcessEntry().
double PlotTAP_selfCorrelation::fMaxAmpA [private]
Definition at line 67 of file PlotTAP_selfCorrelation.h.
Referenced by PassesCutA().
double PlotTAP_selfCorrelation::fMinAmpA [private]
Definition at line 67 of file PlotTAP_selfCorrelation.h.
IDs::source PlotTAP_selfCorrelation::fMuScSource [private]
Definition at line 75 of file PlotTAP_selfCorrelation.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
double PlotTAP_selfCorrelation::fMuScWindow [private]
Definition at line 68 of file PlotTAP_selfCorrelation.h.
double PlotTAP_selfCorrelation::fTimeHigh [private]
Definition at line 66 of file PlotTAP_selfCorrelation.h.
Referenced by BookHistograms().
double PlotTAP_selfCorrelation::fTimeLow [private]
Definition at line 66 of file PlotTAP_selfCorrelation.h.
Referenced by BookHistograms().
The documentation for this class was generated from the following files:
rootana/src/plotters/PlotTAP_selfCorrelation.h
rootana/src/plotters/PlotTAP_selfCorrelation.cpp