AlcapDAQ: IslandLength Class Reference
IslandLength Class Reference
[Modules]
A one line description of what your module does.
#include <IslandLength.h>
Public Member Functions
IslandLength (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~IslandLength ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef const std::map
< std::string, std::string > mapSS_t
typedef mapSS_t::const_iterator mapSS_iter
typedef std::map< std::string,
TH1F * > mapSH_t
typedef
StringPulseIslandMap::iterator mapSP_iter
typedef PulseIslandList::iterator PIL_iter
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
IslandLength (const IslandLength &src)
Copy C'tor is diallowed becasue i dont know what it might do.
IslandLength & operator() (const IslandLength &rhs)
virtual void Book (TGlobalData *data, const TSetupData *setup)
Book histograms and similar.
Private Attributes
mapSH_t fHistos
Map of histograms, keyed by bank_name;.
mapSH_t fHistosNorm
Map of normalised histograms, keyed by bank_name;.
TH1 * fNormHist
The histogram that we use for normalising to;.
int fNProcessed
Detailed Description
A one line description of what your module does.
Author:
AuthorName
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 23 of file IslandLength.h.
Member Typedef Documentation
typedef std::map<std::string, TH1F*> IslandLength::mapSH_t [private]
Definition at line 64 of file IslandLength.h.
typedef StringPulseIslandMap::iterator IslandLength::mapSP_iter [private]
Definition at line 65 of file IslandLength.h.
typedef mapSS_t::const_iterator IslandLength::mapSS_iter [private]
Definition at line 63 of file IslandLength.h.
typedef const std::map<std::string, std::string> IslandLength::mapSS_t [private]
Definition at line 62 of file IslandLength.h.
typedef PulseIslandList::iterator IslandLength::PIL_iter [private]
Definition at line 66 of file IslandLength.h.
Constructor & Destructor Documentation
IslandLength::IslandLength (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 13 of file IslandLength.cpp.
  : BaseModule("IslandLength",opts)
{
  // Do something with opts here.  Has the user specified any
  // particular configuration that you want to know?
  // For example, perhaps this module wants an axis range:
  //fXMax=opts->GetDouble("x_max",100);
}
IslandLength::~IslandLength ()
Is anything done in the destructor?
Definition at line 26 of file IslandLength.cpp.
{
}
IslandLength::IslandLength (const IslandLength & src) [private]
Copy C'tor is diallowed becasue i dont know what it might do.
Member Function Documentation
int IslandLength::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::AfterLastEntry
[in] setup See BaseModule::AfterLastEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 86 of file IslandLength.cpp.
References BaseModule::Debug(), fHistos, fHistosNorm, fNormHist, and fNProcessed.
{
  // Return non-zero to indicate a problem
  if(Debug()){
    std::cout << "-----IslandLength::AfterLastEntry(): I'm debugging!"
              << std::endl;
  }
  double run_norm = fNormHist->Integral(0,-1);
  for (mapSH_t::iterator it = fHistos.begin(); it != fHistos.end(); ++it){
    TH1F* h = it->second;
    TObject* obj = h->Clone((std::string(h->GetName()) + "_RunNorm").c_str());
    TH1* hn = static_cast<TH1*>(obj);
    hn->SetTitle((std::string(h->GetTitle()) + " (run normalised)").c_str());
    hn->Scale(1./run_norm);
  }
  for (mapSH_t::iterator it = fHistosNorm.begin(); it != fHistosNorm.end(); ++it){
    it->second->Scale(1./fNProcessed);
  }
  return 0;
}
int IslandLength::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::BeforeFirstEntry
[in] setup See BaseModule::BeforeFirstEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 32 of file IslandLength.cpp.
References Book(), BaseModule::Debug(), and fNProcessed.
{
  // Called before the main event loop
  // Can be used to set things up, like histograms etc
  // Return non-zero to indicate a problem
  // Print extra info if we're debugging this module:
  if(Debug()){
    std::cout<<"-----IslandLength::BeforeFirstEntry(): I'm debugging!"
             <<std::endl;
  }
  fNProcessed = 0;
  Book(data, setup);
  return 0;
}
void IslandLength::Book (TGlobalData * data, const TSetupData * setup) [private, virtual]
Book histograms and similar.
Definition at line 110 of file IslandLength.cpp.
References fHistos, fHistosNorm, fNormHist, TGlobalData::fPulseIslandToChannelMap, and TSetupData::GetDetectorName().
Referenced by BeforeFirstEntry().
{
  //Change: Use the same map as when processing entries. This should
  //guarentee that all histograms we try to fill also exist
  StringPulseIslandMap& islands = data->fPulseIslandToChannelMap;
  for (mapSP_iter it = islands.begin(); it != islands.end(); ++it){
    std::string bank_name = it->first;
    std::string det_name = setup->GetDetectorName(bank_name);
    std::string hist_name = "hDQ_IslandLength_" + det_name + "" + bank_name;
    std::string hist_title = "Length of TPulseIslands in " + det_name;
    std::string axis_title = ";Length /samples;Number of Islands";
    TH1F* histo = new TH1F(hist_name.c_str(), (hist_title + axis_title).c_str(),
                           500, 0, 2000);
    fHistos[bank_name] = histo;
    if (det_name == "muSc") fNormHist = histo;
    hist_name += "_EvtNorm";
    hist_title += " (event normalised)";
    histo = new TH1F(hist_name.c_str(), (hist_title + axis_title).c_str(),
                     500, 0, 2000);
    fHistosNorm[bank_name] = histo;
  }
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
IslandLength& IslandLength::operator() (const IslandLength & rhs) [private]
Copy assignment is disallowed becasue i dont know what it might do
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int IslandLength::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::ProcessEntry
[in] gSetup See BaseModule::ProcessEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 51 of file IslandLength.cpp.
References banks, fHistos, fHistosNorm, fNProcessed, TGlobalData::fPulseIslandToChannelMap, and TSetupData::GetDetectorName().
{
  ++fNProcessed;
  // Called once for each event in the main event loop
  // Return non-zero to indicate a problem and terminate the event loop
  StringPulseIslandMap& banks = data->fPulseIslandToChannelMap;
  //typedef StringPulseIslandMap::iterator mapSP_iter;
  int entry_norm = -1;
  for (mapSP_iter biter = banks.begin(); biter != banks.end(); ++biter){
    std::string det_name = setup->GetDetectorName(biter->first);
    if (det_name == "muSc"){
      entry_norm = biter->second.size();
    }
  }
  for (mapSP_iter biter = banks.begin(); biter != banks.end(); ++biter){
    std::string bank_name = biter->first;
    std::string det_name = setup->GetDetectorName(bank_name);
    PulseIslandList& islands = biter->second;
    TH1F* hist = fHistos.find(bank_name)->second;
    TH1F* histNorm = fHistosNorm.find(bank_name)->second;
    for (PIL_iter piter = islands.begin(); piter != islands.end(); ++piter){
      int length = (*piter)->GetSamples().size();
      hist->Fill(length);
      if (entry_norm!=0) histNorm->Fill(length, 1./entry_norm);
    }
  }
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
mapSH_t IslandLength::fHistos [private]
Map of histograms, keyed by bank_name;.
Definition at line 80 of file IslandLength.h.
Referenced by AfterLastEntry(), Book(), and ProcessEntry().
mapSH_t IslandLength::fHistosNorm [private]
Map of normalised histograms, keyed by bank_name;.
Definition at line 83 of file IslandLength.h.
Referenced by AfterLastEntry(), Book(), and ProcessEntry().
TH1* IslandLength::fNormHist [private]
The histogram that we use for normalising to;.
Definition at line 86 of file IslandLength.h.
Referenced by AfterLastEntry(), and Book().
int IslandLength::fNProcessed [private]
Definition at line 89 of file IslandLength.h.
Referenced by AfterLastEntry(), BeforeFirstEntry(), and ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/data_quality/IslandLength.h
rootana/src/data_quality/IslandLength.cpp