AlcapDAQ: TAnalysedPulse Class Reference
TAnalysedPulse Class Reference
[rootana]
A TAnalysedPulse (TAP) is the product of the second level of analysis in the framework.
#include <TAnalysedPulse.h>
Public Member Functions
TAnalysedPulse ()
This constructor must exist for ROOT I/O, but should not be used as you cannot set the source outside of the constructor.
TAnalysedPulse (const IDs::source &sourceID, const TPulseIslandID &parentID, const TPulseIsland *parentTPI)
The constructor one should use if we need use one.
virtual ~TAnalysedPulse ()
void Reset (Option_t *o="")
Clear the TAP. This will probably not be used.
virtual void Draw (const TH1F *tpi_pulse) const
Visualize the TAP interpretation of the TPI.
Getters
TPulseIslandID GetParentID () const
int GetTPILength () const
double GetAmplitude () const
double GetTime () const
double GetIntegral () const
double GetEnergy () const
double GetPedestal () const
double GetTriggerTime () const
const IDs::source & GetSource () const
Setters
The TAP generators will set whatever TAP values it must through these methods. Not all need be set; the default values are obviously unphysical and several Sanity methods are provided to check if a value was set later in the analysis.
void SetParentID (const TPulseIslandID &val)
void SetTPILength (const int &val)
void SetAmplitude (const double &val)
void SetTime (const double &val)
void SetIntegral (const double &val)
void SetEnergy (const double &val)
void SetPedestal (const double &val)
void SetTriggerTime (const double &val)
void SetParentTPIProperties (const TPulseIslandID &id, const TPulseIsland *parent)
Sanity
bool IsParentIDSet () const
bool IsTPILengthSet () const
bool IsAmplitudeSet () const
bool IsTimeSet () const
bool IsIntegralSet () const
bool IsEnergySet () const
bool IsPedestalSet () const
bool IsTriggerTimeSet () const
Private Types
SourceProxy
A flyweight for identifying which source was used to make the TAP without copying the entire source.
Because many TAPs will be using the same source, and we don't want to waste the space storing copies of them or the time making them, we instead store a single copy in a vector of each source used throughout the invocation of this program in the making of TAPs. If a TAP generator uses a source, that source is searched for in ProxyToSourceMap and the index identifying where it is is saved with this TAP. If the source does not exists, it is created and appended to the end.
typedef int SourceProxy_t
typedef std::vector< IDs::source > ProxyToSourceMap
typedef std::map< IDs::source,
SourceProxy_t > SourceToProxyMap
Private Member Functions
void SetSource (const IDs::source &sourceID)
ClassDef (TAnalysedPulse, 4)
Private Attributes
TPulseIslandID fParentID
SourceProxy_t fSource
int fTPILength
double fAmplitude
double fTime
double fIntegral
double fEnergy
double fPedestal
double fTriggerTime
Static Private Attributes
static const int fDefaultValue = -99999
To enable sanity checks, we have an unphysical value that all fields are set to.
static ProxyToSourceMap sProxyToSources
See description of SourceProxy. This is the single instance of that map needed.
static SourceToProxyMap sSourceToProxies
See description of SourceProxy. This is the single instance of the map needed.
Detailed Description
A TAnalysedPulse (TAP) is the product of the second level of analysis in the framework.
A TAP is generated from a TPulseIsland and represents the next higher level, more intuitive representation of a physical hit in a detector. It has properties more commonly associated with a physics event, such as time and energy, that are derived from the TPI using the methods in generator (derived from TVAnalysedPulseGenerator). Different generators can calculate the same quantitites using different techniques, leading to multiple TAPs coming from a single TPI.
Definition at line 30 of file TAnalysedPulse.h.
Member Typedef Documentation
typedef std::vector<IDs::source> TAnalysedPulse::ProxyToSourceMap [private]
Definition at line 49 of file TAnalysedPulse.h.
typedef int TAnalysedPulse::SourceProxy_t [private]
Definition at line 48 of file TAnalysedPulse.h.
typedef std::map<IDs::source,SourceProxy_t> TAnalysedPulse::SourceToProxyMap [private]
Definition at line 50 of file TAnalysedPulse.h.
Constructor & Destructor Documentation
TAnalysedPulse::TAnalysedPulse ()
This constructor must exist for ROOT I/O, but should not be used as you cannot set the source outside of the constructor.
Definition at line 34 of file TAnalysedPulse.cpp.
                              :
  fParentID(fDefaultValue),
  fSource(fDefaultValue),
  fTPILength(fDefaultValue),
  fAmplitude(fDefaultValue),
  fTime(fDefaultValue),
  fIntegral(fDefaultValue),
  fEnergy(fDefaultValue),
  fPedestal(fDefaultValue),
  fTriggerTime(fDefaultValue){
    //Reset();
}
TAnalysedPulse::TAnalysedPulse (const IDs::source & sourceID, const TPulseIslandID & parentID, const TPulseIsland * parentTPI)
The constructor one should use if we need use one.
This constructor, which is the only constructor the user should use, takes all the information neessary to identify the genesis of this TAP. Generally a user would not use this constructor, but would instead call TVAnalysedPulseGenerator::MakeNewTAP which determines the source and TPI from the TPulseIslandID and where in the code it's being called.
Parameters:
[in] sourceID The source identifying the detector the TPI is from and what generator processed it.
[in] parentID The position in the TGD vector of the TPI used to make this TAP.
[in] parentTPI The pulse that was used to produce this TAP.
Definition at line 19 of file TAnalysedPulse.cpp.
References SetParentTPIProperties(), and SetSource().
                                                                           :
  fParentID(fDefaultValue),
  fSource(fDefaultValue),
  fTPILength(fDefaultValue),
  fAmplitude(fDefaultValue),
  fTime(fDefaultValue),
  fIntegral(fDefaultValue),
  fEnergy(fDefaultValue),
  fPedestal(fDefaultValue),
  fTriggerTime(fDefaultValue){
    SetSource(sourceID);
    SetParentTPIProperties(parentID, parentTPI);
}
virtual TAnalysedPulse::~TAnalysedPulse () [inline, virtual]
Definition at line 76 of file TAnalysedPulse.h.
{};
Member Function Documentation
TAnalysedPulse::ClassDef (TAnalysedPulse , 4) [private]
void TAnalysedPulse::Draw (const TH1F * tpi_pulse) const [virtual]
Visualize the TAP interpretation of the TPI.
Since there are different methods for determining the physical values in the TAP from the TPI, here we can get a visual feel for how right those values might be. If passed a TH1F representation of the TPI, Draw makes a new histogram with the same histogram dimensions and a single bin at the determined time weighted with the determined amplitude.
Todo:
Clean this up
Parameters:
[in] tpi_pulse A histogram representation of the parent pulse
Reimplemented in TGaussFitAnalysedPulse.
Definition at line 58 of file TAnalysedPulse.cpp.
References fAmplitude, and fTime.
Referenced by ExportPulse::PlotTAP().
{
        if(tpi_pulse) {
          std::string name=tpi_pulse->GetName();
          int n_bins=tpi_pulse->GetXaxis()->GetNbins();
          double x_max=tpi_pulse->GetXaxis()->GetXmax();
          double x_min=tpi_pulse->GetXaxis()->GetXmin();
          TH1F* tap_pulse=new TH1F((name+"_AP").c_str(),("TAP for "+name).c_str(),n_bins,x_min,x_max);
          int bin=tap_pulse->FindBin(fTime);
          tap_pulse->SetBinContent(bin,fAmplitude);
        }
}
double TAnalysedPulse::GetAmplitude () const [inline]
Definition at line 103 of file TAnalysedPulse.h.
References fAmplitude.
Referenced by TGaussFitAnalysedPulse::Draw(), TDetectorPulse::GetFastPulseAmplitude(), PulseViewer::GetParameterValue(), and TDetectorPulse::GetSlowPulseAmplitude().
{return fAmplitude;};
double TAnalysedPulse::GetEnergy () const [inline]
Definition at line 106 of file TAnalysedPulse.h.
References fEnergy.
Referenced by PulseViewer::GetParameterValue().
{return fEnergy;};
double TAnalysedPulse::GetIntegral () const [inline]
Definition at line 105 of file TAnalysedPulse.h.
References fIntegral.
Referenced by TDetectorPulse::GetFastPulseIntegral(), PulseViewer::GetParameterValue(), and TDetectorPulse::GetSlowPulseIntegral().
{return fIntegral;};
TPulseIslandID TAnalysedPulse::GetParentID () const [inline]
Definition at line 101 of file TAnalysedPulse.h.
References fParentID.
Referenced by ExportPulse::AddToExportList().
{return fParentID;};
double TAnalysedPulse::GetPedestal () const [inline]
Definition at line 107 of file TAnalysedPulse.h.
References fPedestal.
Referenced by TGaussFitAnalysedPulse::Draw(), and PulseViewer::GetParameterValue().
{return fPedestal;};
const IDs::source& TAnalysedPulse::GetSource () const [inline]
Definition at line 109 of file TAnalysedPulse.h.
References fSource, and sProxyToSources.
Referenced by ExportPulse::AddToExportList(), and MaxTimeDiffDPGenerator::ProcessPulses().
{return sProxyToSources.at(fSource);};
double TAnalysedPulse::GetTime () const [inline]
Definition at line 104 of file TAnalysedPulse.h.
References fTime.
Referenced by TGaussFitAnalysedPulse::Draw(), TDetectorPulse::GetFastPulseTime(), PulseViewer::GetParameterValue(), TDetectorPulse::GetSlowPulseTime(), IsTimeOrdered(), and MaxTimeDiffDPGenerator::ProcessPulses().
{return fTime;};
int TAnalysedPulse::GetTPILength () const [inline]
Definition at line 102 of file TAnalysedPulse.h.
References fTPILength.
Referenced by PulseViewer::GetParameterValue().
{return fTPILength;};
double TAnalysedPulse::GetTriggerTime () const [inline]
Definition at line 108 of file TAnalysedPulse.h.
References fTriggerTime.
Referenced by PulseViewer::GetParameterValue().
{return fTriggerTime;};
bool TAnalysedPulse::IsAmplitudeSet () const [inline]
Definition at line 138 of file TAnalysedPulse.h.
References fAmplitude, and fDefaultValue.
{return fAmplitude!=fDefaultValue;};
bool TAnalysedPulse::IsEnergySet () const [inline]
Definition at line 141 of file TAnalysedPulse.h.
References fDefaultValue, and fEnergy.
{return fEnergy!=fDefaultValue;};
bool TAnalysedPulse::IsIntegralSet () const [inline]
Definition at line 140 of file TAnalysedPulse.h.
References fDefaultValue, and fIntegral.
{return fIntegral!=fDefaultValue;};
bool TAnalysedPulse::IsParentIDSet () const [inline]
Definition at line 136 of file TAnalysedPulse.h.
References fDefaultValue, and fParentID.
{return fParentID!=fDefaultValue;};
bool TAnalysedPulse::IsPedestalSet () const [inline]
Definition at line 142 of file TAnalysedPulse.h.
References fDefaultValue, and fPedestal.
{return fPedestal!=fDefaultValue;};
bool TAnalysedPulse::IsTimeSet () const [inline]
Definition at line 139 of file TAnalysedPulse.h.
References fDefaultValue, and fTime.
{return fTime!=fDefaultValue;};
bool TAnalysedPulse::IsTPILengthSet () const [inline]
Definition at line 137 of file TAnalysedPulse.h.
References fDefaultValue, and fTPILength.
{return fTPILength!=fDefaultValue;};
bool TAnalysedPulse::IsTriggerTimeSet () const [inline]
Definition at line 143 of file TAnalysedPulse.h.
References fDefaultValue, and fTriggerTime.
{return fTriggerTime!=fDefaultValue;};
void TAnalysedPulse::Reset (Option_t * o = "")
Clear the TAP. This will probably not be used.
Definition at line 47 of file TAnalysedPulse.cpp.
References fAmplitude, fDefaultValue, fEnergy, fIntegral, fParentID, fPedestal, fTime, fTPILength, and fTriggerTime.
{
  fParentID=fDefaultValue;
  fTPILength=fDefaultValue;
  fAmplitude=fDefaultValue;
  fTime=fDefaultValue;
  fIntegral=fDefaultValue;
  fEnergy=fDefaultValue;
  fPedestal=fDefaultValue;
  fTriggerTime=fDefaultValue;
}
void TAnalysedPulse::SetAmplitude (const double & val) [inline]
Definition at line 123 of file TAnalysedPulse.h.
References fAmplitude.
Referenced by MaxBinAPGenerator::ProcessPulses().
{ fAmplitude=val;};
void TAnalysedPulse::SetEnergy (const double & val) [inline]
Definition at line 126 of file TAnalysedPulse.h.
References fEnergy.
Referenced by SimpIntAPGenerator::ProcessPulses(), and MaxBinAPGenerator::ProcessPulses().
{ fEnergy=val;};
void TAnalysedPulse::SetIntegral (const double & val) [inline]
Definition at line 125 of file TAnalysedPulse.h.
References fIntegral.
Referenced by SimpIntAPGenerator::ProcessPulses().
{ fIntegral=val;};
void TAnalysedPulse::SetParentID (const TPulseIslandID & val) [inline]
Definition at line 121 of file TAnalysedPulse.h.
References fParentID.
Referenced by SetParentTPIProperties().
{ fParentID=val;};
void TAnalysedPulse::SetParentTPIProperties (const TPulseIslandID & id, const TPulseIsland * parent)
Definition at line 70 of file TAnalysedPulse.cpp.
References TPulseIsland::GetClockTickInNs(), TPulseIsland::GetPulseLength(), TPulseIsland::GetTimeStamp(), SetParentID(), SetTPILength(), and SetTriggerTime().
Referenced by TAnalysedPulse().
{
  SetParentID(id);
  if(!pulse) {
    std::cerr<<"NULL pointer to TPulseIsland passed as parent for TAnalysedPulse."<<std::endl;
    return;
  }
  SetTPILength(pulse->GetPulseLength());
  SetTriggerTime(pulse->GetTimeStamp()*pulse->GetClockTickInNs());
}
void TAnalysedPulse::SetPedestal (const double & val) [inline]
Definition at line 127 of file TAnalysedPulse.h.
References fPedestal.
{ fPedestal=val;};
void TAnalysedPulse::SetSource (const IDs::source & sourceID) [private]
Todo:
Why is this private?
Definition at line 81 of file TAnalysedPulse.cpp.
References fSource, sProxyToSources, and sSourceToProxies.
Referenced by TAnalysedPulse().
{
    // Is this proxy already contained in the maps
    SourceToProxyMap::const_iterator it=sSourceToProxies.find(sourceID);
    if(it!=sSourceToProxies.end()){
      fSource=it->second;
    } else {
      // if it's a new kind, add the source to the hash table
      fSource=sSourceToProxies.size();
      sSourceToProxies[sourceID]=fSource;
      sProxyToSources.push_back(sourceID);
    }
}
void TAnalysedPulse::SetTime (const double & val) [inline]
Definition at line 124 of file TAnalysedPulse.h.
References fTime.
Referenced by MaxBinAPGenerator::ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{ fTime=val;};
void TAnalysedPulse::SetTPILength (const int & val) [inline]
Definition at line 122 of file TAnalysedPulse.h.
References fTPILength.
Referenced by SetParentTPIProperties().
{ fTPILength=val;};
void TAnalysedPulse::SetTriggerTime (const double & val) [inline]
Definition at line 128 of file TAnalysedPulse.h.
References fTriggerTime.
Referenced by SetParentTPIProperties().
{ fTriggerTime=val;};
Member Data Documentation
double TAnalysedPulse::fAmplitude [private]
Definition at line 154 of file TAnalysedPulse.h.
Referenced by Draw(), GetAmplitude(), IsAmplitudeSet(), Reset(), and SetAmplitude().
const int TAnalysedPulse::fDefaultValue = -99999 [static, private]
To enable sanity checks, we have an unphysical value that all fields are set to.
Definition at line 164 of file TAnalysedPulse.h.
Referenced by IsAmplitudeSet(), IsEnergySet(), IsIntegralSet(), IsParentIDSet(), IsPedestalSet(), IsTimeSet(), IsTPILengthSet(), IsTriggerTimeSet(), and Reset().
double TAnalysedPulse::fEnergy [private]
Definition at line 157 of file TAnalysedPulse.h.
Referenced by GetEnergy(), IsEnergySet(), Reset(), and SetEnergy().
double TAnalysedPulse::fIntegral [private]
Definition at line 156 of file TAnalysedPulse.h.
Referenced by GetIntegral(), IsIntegralSet(), Reset(), and SetIntegral().
TPulseIslandID TAnalysedPulse::fParentID [private]
Definition at line 151 of file TAnalysedPulse.h.
Referenced by GetParentID(), IsParentIDSet(), Reset(), and SetParentID().
double TAnalysedPulse::fPedestal [private]
Definition at line 158 of file TAnalysedPulse.h.
Referenced by GetPedestal(), IsPedestalSet(), Reset(), and SetPedestal().
SourceProxy_t TAnalysedPulse::fSource [private]
Definition at line 152 of file TAnalysedPulse.h.
Referenced by GetSource(), and SetSource().
double TAnalysedPulse::fTime [private]
Definition at line 155 of file TAnalysedPulse.h.
Referenced by Draw(), GetTime(), IsTimeSet(), Reset(), and SetTime().
int TAnalysedPulse::fTPILength [private]
Definition at line 153 of file TAnalysedPulse.h.
Referenced by GetTPILength(), IsTPILengthSet(), Reset(), and SetTPILength().
double TAnalysedPulse::fTriggerTime [private]
Definition at line 159 of file TAnalysedPulse.h.
Referenced by GetTriggerTime(), IsTriggerTimeSet(), Reset(), and SetTriggerTime().
TAnalysedPulse::ProxyToSourceMap TAnalysedPulse::sProxyToSources [static, private]
See description of SourceProxy. This is the single instance of that map needed.
Definition at line 168 of file TAnalysedPulse.h.
Referenced by GetSource(), and SetSource().
TAnalysedPulse::SourceToProxyMap TAnalysedPulse::sSourceToProxies [static, private]
See description of SourceProxy. This is the single instance of the map needed.
Definition at line 172 of file TAnalysedPulse.h.
Referenced by SetSource().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/TAnalysedPulse.h
rootana/src/TAP_generators/TAnalysedPulse.cpp