AlcapDAQ: TemplateArchive Class Reference
TemplateArchive Class Reference
[Modules]
Utility class that manages reading and writing template histograms to a ROOT file.
#include <TemplateArchive.h>
Public Member Functions
TemplateArchive (const char *filename, const char *option)
constructor to make separate template files
TemplateArchive (TDirectory *dir)
constructor to use a directory in an existing file
~TemplateArchive ()
Empty destructor.
const char * GetName () const
TTemplate * GetTemplate (const char *template_name)
Gets the template histogram of the given name and returns it.
TTemplate * GetTemplate (const IDs::channel &channel)
Gets the template histogram of the given name and returns it.
void SaveTemplate (const TTemplate *hTemplate)
Takes the given histogram and saves it to the ROOT file.
Private Attributes
TFile * fTemplateFile
The ROOT file that contains the templates.
TDirectory * fDirectory
Detailed Description
Utility class that manages reading and writing template histograms to a ROOT file.
Author:
Andrew Edmonds
Ben Krikler
Definition at line 18 of file TemplateArchive.h.
Constructor & Destructor Documentation
TemplateArchive::TemplateArchive (const char * filename, const char * option)
constructor to make separate template files
Given a file name and a standard ROOT TFile option (e.g. "READ", "RECREATE" etc.) and opens the ROOT file ready for reading and writing
Definition at line 8 of file TemplateArchive.cpp.
References fDirectory, and fTemplateFile.
{
  TDirectory* tmp=gDirectory;
  fTemplateFile = new TFile(filename, option);
  fDirectory=TDirectory::CurrentDirectory();
  tmp->cd();
}
TemplateArchive::TemplateArchive (TDirectory * dir)
constructor to use a directory in an existing file
Definition at line 15 of file TemplateArchive.cpp.
References fDirectory.
                                               :fTemplateFile(NULL){
  fDirectory=dir;
}
TemplateArchive::~TemplateArchive ()
Empty destructor.
Definition at line 19 of file TemplateArchive.cpp.
References fTemplateFile.
{
  if(fTemplateFile) fTemplateFile->Close();
}
Member Function Documentation
const char* TemplateArchive::GetName () const [inline]
Definition at line 44 of file TemplateArchive.h.
References fTemplateFile.
Referenced by TemplateFitAPGenerator::TemplateFitAPGenerator().
{return fTemplateFile?fTemplateFile->GetName(): "";}
TTemplate * TemplateArchive::GetTemplate (const IDs::channel & channel)
Gets the template histogram of the given name and returns it.
Definition at line 23 of file TemplateArchive.cpp.
References GetTemplate(), and TTemplate::MakeName().
{
  return GetTemplate(TTemplate::MakeName(ch).c_str());
}
TTemplate * TemplateArchive::GetTemplate (const char * template_name)
Gets the template histogram of the given name and returns it.
Definition at line 29 of file TemplateArchive.cpp.
References fDirectory, and fTemplateFile.
Referenced by GetTemplate(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), and TemplateFitAPGenerator::TemplateFitAPGenerator().
{
  TTemplate* hTemplate = NULL;
  fDirectory->GetObject(template_name, hTemplate);
  if(!hTemplate) {
   cout<< "TemplateArchive::GetTemplate: ERROR: Unable to find a template called '"
       <<template_name<<"' in file '"<<fTemplateFile->GetName()<<"'"<<endl;
  }
  return hTemplate;
}
void TemplateArchive::SaveTemplate (const TTemplate * hTemplate)
Takes the given histogram and saves it to the ROOT file.
Definition at line 42 of file TemplateArchive.cpp.
References fDirectory.
Referenced by TemplateCreator::AfterLastEntry().
{
  TDirectory* oldDir = TDirectory::CurrentDirectory(); // should be the directory we were already in
  if (hTemplate) {
    fDirectory->cd();
    hTemplate->Write();
  }
  oldDir->cd(); // go back to the old directory
}
Member Data Documentation
TDirectory* TemplateArchive::fDirectory [private]
Definition at line 24 of file TemplateArchive.h.
Referenced by GetTemplate(), SaveTemplate(), and TemplateArchive().
TFile* TemplateArchive::fTemplateFile [private]
The ROOT file that contains the templates.
Definition at line 23 of file TemplateArchive.h.
Referenced by GetName(), GetTemplate(), TemplateArchive(), and ~TemplateArchive().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/template_fitting/TemplateArchive.h
rootana/src/TAP_generators/template_fitting/TemplateArchive.cpp