AlcapDAQ: EventNavigator Class Reference
EventNavigator Class Reference
The EventNavigator class provides acess to all the collections in the (MIDAS) Event, which corresponds to a single ROOT branch.
#include <EventNavigator.h>
Public Types
enum OutputMode { kNew = 0, kOverwrite }
Public Member Functions
~EventNavigator ()
const TSetupData *const GetSetupData ()
const LoopSequence & GetLoopSequence () const
const char * GetOutputFileName () const
const LoopSequence & MakeLoopSequence (const ARGUMENTS &args)
Bool_t ConnectInput (const char *input_name)
Bool_t ConnectOutput (const char *output_name, OutputMode mode=kOverwrite)
Bool_t ConnectOutputFile (const char *output_file_name, Bool_t append=false)
Long64_t EntryNo () const
Returns the current event number.
Long64_t GetInputNEntries () const
Long64_t GetStartEntry () const
Returns the entry processing starts from.
Long64_t GetStopEntry () const
Returns the past-the-end entry processing stops at.
Long64_t GetLoopNEntries () const
Int_t NextEntry ()
Int_t GetEntry (Long64_t entry)
Int_t WriteCurrentEntry ()
void SetSavePulseIslands (bool save=1)
void Adopt (PulseIslandList &pil, const SourceID &sid)
void Adopt (AnalysedPulseList &apl, const SourceID &sid)
void Adopt (DetectorPulseList &dpl, const SourceID &sid)
void Adopt (PulseIslandList &pil, const ChannelID &cid)
This will probably become protected, for copying TAPs.
void AdoptTemporary (PulseIslandList &pil, const SourceID &sid)
void AdoptTemporary (AnalysedPulseList &apl, const SourceID &sid)
void AdoptTemporary (DetectorPulseList &dpl, const SourceID &sid)
void AdoptTemporary (PulseIslandList &pil, const ChannelID &cid)
This will probably become protected, for copying TAPs.
PulseIslandBankIter MatchIslandBanks (const SourceID &sid) const
Iterable getters for a list of banks.
PulseIslandBankIter MatchAnalysedBanks (const SourceID &sid) const
PulseIslandBankIter MatchDetectorBanks (const SourceID &sid) const
PulseIslandBankIter MatchIslandBanks (const ChannelID &cid, GeneratorStr gid="") const
AnalysedPulseBankIter MatchAnalysedBanks (const ChannelID &cid, GeneratorStr gid="") const
AnalysedPulseBankIter MatchDetectorBanks (const ChannelID &cid, GeneratorStr gid="") const
void Close ()
TGlobalData * GetRawData () const
TTree * GetRawTree () const
void DumpRawTree () const
Static Public Member Functions
static EventNavigator & InitInstance (const ARGUMENTS &command_line)
static EventNavigator & Instance ()
static const SetupRecord & GetSetupRecord ()
Protected Member Functions
TGlobalData * ConnectRawData (TFile *raw_file)
Bool_t VerifyRawData (TTree *raw_tree)
TSetupData * ConnectSetupData (TFile *raw_file)
Bool_t VerifySetupData (TTree *setup_tree)
Bool_t MirrorRawInputFormat ()
Copy the input raw data tree (TGlobalData) to the output file.
Int_t LoadEntry (Long64_t entry)
Implementation for loading an entry.
Private Types
typedef IDs::channel ChannelID
typedef IDs::generator GeneratorID
typedef IDs::source SourceID
typedef IDs::Generator_t GeneratorStr
typedef IDs::Config_t Config
Private Member Functions
EventNavigator ()
EventNavigator (const ARGUMENTS &command_line)
EventNavigator (const EventNavigator &src)
EventNavigator & operator= (const EventNavigator &rhs)
Private Attributes
Bool_t fCopyRaw
TFile * fRawInput
Input ROOT file, raw format.
TFile * fOutput
Output ROOT file (may be same as input file).
Int_t fEntryNo
The current entry number.
TTree * fRawTree
Input Raw Data (Event) Tree.
TTree * fSetupTree
Input Setup Tree.
TTree * fEventTree
TTree * fOutputTreeTPI
TGlobalData * fRawData
TSetupData * fSetupData
SetupRecord * fSetupRecord
LoopSequence * fLoopSequence
Static Private Attributes
static EventNavigator * fInstance = 0x0
Detailed Description
The EventNavigator class provides acess to all the collections in the (MIDAS) Event, which corresponds to a single ROOT branch.
The general principle is that the event navigator owns all objects that are read or written to disk. Thus....
Definition at line 40 of file EventNavigator.h.
Member Typedef Documentation
typedef IDs::channel EventNavigator::ChannelID [private]
Definition at line 41 of file EventNavigator.h.
typedef IDs::Config_t EventNavigator::Config [private]
Definition at line 45 of file EventNavigator.h.
typedef IDs::generator EventNavigator::GeneratorID [private]
Definition at line 42 of file EventNavigator.h.
typedef IDs::Generator_t EventNavigator::GeneratorStr [private]
Definition at line 44 of file EventNavigator.h.
typedef IDs::source EventNavigator::SourceID [private]
Definition at line 43 of file EventNavigator.h.
Member Enumeration Documentation
enum EventNavigator::OutputMode
Enumerator:
kNew
kOverwrite
Definition at line 49 of file EventNavigator.h.
{kNew = 0, kOverwrite }; //, kAppend};
Constructor & Destructor Documentation
EventNavigator::~EventNavigator () [inline]
Definition at line 58 of file EventNavigator.h.
{}
EventNavigator::EventNavigator () [private]
Definition at line 59 of file EventNavigator.cpp.
References fOutput, and fRawInput.
Referenced by InitInstance(), and Instance().
  : fCopyRaw(true)
  , fLoopSequence(0x0)
{
  fRawInput = 0x0;
  fOutput = 0x0;
  //no-op
}
EventNavigator::EventNavigator (const ARGUMENTS & command_line) [private]
Definition at line 69 of file EventNavigator.cpp.
  : fCopyRaw(true)
  , fRawInput(0x0)
  , fOutput(0x0)
  , fLoopSequence(new LoopSequence(args))
{
}
EventNavigator::EventNavigator (const EventNavigator & src) [inline, private]
Definition at line 231 of file EventNavigator.h.
{};
Member Function Documentation
void EventNavigator::Adopt (PulseIslandList & pil, const ChannelID & cid)
This will probably become protected, for copying TAPs.
void EventNavigator::Adopt (DetectorPulseList & dpl, const SourceID & sid)
void EventNavigator::Adopt (AnalysedPulseList & apl, const SourceID & sid)
void EventNavigator::Adopt (PulseIslandList & pil, const SourceID & sid)
Adoption: take ownership of a container of reconstruction objects. The calling code should lose ownership so the object is frozen at adoption. Implemetaion could use a swaped body.
void EventNavigator::AdoptTemporary (PulseIslandList & pil, const ChannelID & cid)
This will probably become protected, for copying TAPs.
void EventNavigator::AdoptTemporary (DetectorPulseList & dpl, const SourceID & sid)
void EventNavigator::AdoptTemporary (AnalysedPulseList & apl, const SourceID & sid)
void EventNavigator::AdoptTemporary (PulseIslandList & pil, const SourceID & sid)
Adoption of temporaries: As Adopt(), but the adopted objects expire and are deleted at the end of the current event.
void EventNavigator::Close ()
Definition at line 378 of file EventNavigator.cpp.
References fOutput, and fRawInput.
Referenced by Finish().
{
  if (fRawInput) fRawInput->Close();
  if (fOutput) fOutput->Close();
}
Bool_t EventNavigator::ConnectInput (const char * input_name)
Opens an input file and connects to the trees therein. Returns true if file exists, is a ROOT file, and contains at least one EACH of setup and event trees that we recognise. Else false.
Definition at line 115 of file EventNavigator.cpp.
References ConnectRawData(), ConnectSetupData(), AlCapFormat::Raw::DataTreeName, fEntryNo, fSetupTree, and AlCapFormat::Raw::SetupTreeName.
Referenced by main().
{
  TFile* ifile = TFile::Open(input_name, "READ");
  if (!ifile) return false;
  TList* lok = ifile->GetListOfKeys();
  bool success_data = false;
  bool success_meta = false;
  fSetupTree = 0x0;
  if (lok->Contains(Format::Raw::SetupTreeName) ) {
    if ( ConnectSetupData(ifile) != 0x0)
      success_meta = true;
  }
  //TTree* raw_tree = 0x0;
  if (lok->Contains(Format::Raw::DataTreeName) ) {
    if ( ConnectRawData(ifile) != 0x0)
      success_data = true;
  }
  //if (TODO: lok contians other trees)
  fEntryNo = 0;
  return success_data && success_meta;
}
Bool_t EventNavigator::ConnectOutput (const char * output_name, OutputMode mode = kOverwrite)
Opens an output file to put trees and histograms in. By default this overites any existing file with the same name but we can change it to fail instead.
Definition at line 267 of file EventNavigator.cpp.
References fCopyRaw, fOutput, fRawData, fRawTree, and MirrorRawInputFormat().
{
  static const char* output_mode[3] = {"NEW", "RECREATE", "UPDATE"};
  TFile* ofile = TFile::Open(output_name, output_mode[mode]);
  if (!ofile) return false;
  fOutput = ofile;
#ifdef DEFER
  if (fRawTree && fRawData && fCopyRaw) MirrorRawInputFormat();
#endif
  return true;
}
Bool_t EventNavigator::ConnectOutputFile (const char * output_file_name, Bool_t append = false)
Opens an output file. By default this overwrites the output file Appending not yet implemented
Definition at line 338 of file EventNavigator.cpp.
References fOutput.
{
  //Not very careful about tidying up after failures or repeat attempts
  //here.  Probably doesen't matter since the program is likely to
  //abort shortly afterward.  Revisit if that is not true.
  TFile* prev_output = fOutput;
  fOutput = TFile::Open(output_file_name, (append ? "UPDATE" : "RECREATE"));
  if (!fOutput || fOutput->IsZombie()) return false;
  prev_output->cd();
  return true;
}
TGlobalData * EventNavigator::ConnectRawData (TFile * raw_file) [protected]
Attach a raw data tree (found in raw_file). If sucessful will load the zeroth entry return a non-null pointer
Definition at line 141 of file EventNavigator.cpp.
References AlCapFormat::Raw::DataBranchName, AlCapFormat::Raw::DataTreeName, fRawData, fRawTree, LoadEntry(), and VerifyRawData().
Referenced by ConnectInput().
{
  raw_file->GetObject(Format::Raw::DataTreeName, fRawTree);
  if ( !VerifyRawData(fRawTree) ){
    raw_file->Delete(Format::Raw::DataTreeName);
    fRawTree = 0x0;
    fRawData = 0x0;
    return 0x0;
  }
  //Allocate memory locations to hold branches
  //TGlobalData* raw_data(0x0);
  fRawData = new TGlobalData;
  int status = fRawTree->SetBranchAddress(Format::Raw::DataBranchName,
                                          &fRawData);
  if (status!=0){
    fRawTree = 0x0;
    fRawData = 0x0;
    return 0x0;
  }
  this->LoadEntry(0);
  return fRawData;
}
TSetupData * EventNavigator::ConnectSetupData (TFile * raw_file) [protected]
Attach a setup data tree (found in raw_file). If sucessful will load the SetupDAta into memory, which can be accesed via fSetupData (depricated) or fSetupRecord (preferred)
Definition at line 217 of file EventNavigator.cpp.
References fSetupData, fSetupRecord, fSetupTree, AlCapFormat::Raw::SetupBranchName, AlCapFormat::Raw::SetupTreeName, and VerifySetupData().
Referenced by ConnectInput().
{
  raw_file->GetObject(Format::Raw::SetupTreeName, fSetupTree);
  if ( !VerifySetupData(fSetupTree) ){
    raw_file->Delete(Format::Raw::SetupTreeName);
    fSetupData = 0x0;
    fSetupTree = 0x0;
    return 0x0;
  }
  //Allocate memory locations to hold branches
  fSetupData = new TSetupData;
  int status = fSetupTree->SetBranchAddress(Format::Raw::SetupBranchName,
                                            &fSetupData);
  if (status!=0){
    fSetupTree = 0x0;
    fSetupData = 0x0;
    return 0x0;
  }
  fSetupTree->GetEntry(0);
  fSetupRecord = new SetupRecord(fSetupData);
  return fSetupData;
}
void EventNavigator::DumpRawTree () const
Definition at line 191 of file EventNavigator.cpp.
References AlCapFormat::Raw::DataBranchName, GetRawTree(), and AlCapFormat::Raw::SetupBranchName.
Referenced by main().
{
  TTree* raw_tree=GetRawTree();
  if ( !raw_tree ){
    std::cerr << "No raw data tree in file" << std::endl;
    return;
  }
  std::cout << "Raw Tree '" << raw_tree->GetName() << "' has " <<
      raw_tree->GetEntriesFast()<<" entries. "<< std::endl;
  TBranch* raw_branch=raw_tree->GetBranch(Format::Raw::DataBranchName);
  if(!raw_branch) {
    std::cout << "Tree " << raw_tree->GetName()
              << " has no branch called " << Format::Raw::SetupBranchName
              << " which should normally contain the input data." << std::endl;
  } else {
    raw_branch->Print();
  }
}
Long64_t EventNavigator::EntryNo () const [inline]
Returns the current event number.
Definition at line 95 of file EventNavigator.h.
References fEntryNo.
Referenced by PulseViewer::ConsiderDrawing(), FirstCompleteAPGenerator::DrawPulse(), and MakeAnalysedPulses::ProcessEntry().
{return fEntryNo;}
Int_t EventNavigator::GetEntry (Long64_t entry) [inline]
Load the branches for a particular entry from the input file. Random access probably only make sense if it output is not being written. Return values are same as for NextEntry()
Definition at line 123 of file EventNavigator.h.
References LoadEntry().
Referenced by MirrorRawInputFormat(), LoopSequence::Preprocess(), and LoopSequence::Process().
{
    return LoadEntry(entry);
  }
Long64_t EventNavigator::GetInputNEntries () const [inline]
Returns the number of entries in the input file. TODO revisit this with multiple inputs??
Definition at line 99 of file EventNavigator.h.
References fRawTree.
Referenced by LoopSequence::Init(), and Main_event_loop().
{return fRawTree->GetEntriesFast();}
Long64_t EventNavigator::GetLoopNEntries () const [inline]
Returns the total number of entries selected for processing, assuming no errors
Definition at line 109 of file EventNavigator.h.
References GetStartEntry(), and GetStopEntry().
Referenced by PlotTME_activeSiRmuStops::BeforeFirstEntry().
  { return GetStopEntry() - GetStartEntry(); }
const LoopSequence & EventNavigator::GetLoopSequence () const
Gives read access to the LoopSequence, which must first be initailised with MakeLoopSequence() in main()
Definition at line 79 of file EventNavigator.cpp.
References fLoopSequence.
Referenced by GetStartEntry(), GetStopEntry(), and MakeLoopSequence().
{
  if (!fLoopSequence) throw std::runtime_error("No LoopSequence");
  return *fLoopSequence;
}
const char * EventNavigator::GetOutputFileName () const
Definition at line 96 of file EventNavigator.cpp.
References fOutput.
{
  return fOutput? fOutput->GetName():"";
}
TGlobalData* EventNavigator::GetRawData () const [inline]
Definition at line 198 of file EventNavigator.h.
References fRawData.
Referenced by Main_event_loop(), LoopSequence::Postprocess(), LoopSequence::Preprocess(), and LoopSequence::Process().
{return fRawData;}
TTree* EventNavigator::GetRawTree () const [inline]
Definition at line 199 of file EventNavigator.h.
References fRawTree.
Referenced by DumpRawTree(), and main().
{return fRawTree;}
const TSetupData* const EventNavigator::GetSetupData () [inline]
Transitional function to replace gSetup. Users should use the GetSetupRecord interface.
Definition at line 62 of file EventNavigator.h.
References fSetupData.
Referenced by LoopSequence::Postprocess(), LoopSequence::Preprocess(), and LoopSequence::Process().
{return fSetupData;}
static const SetupRecord& EventNavigator::GetSetupRecord () [inline, static]
Gives access to the run meta-data, including all information stored in the TSetupData struct
Definition at line 66 of file EventNavigator.h.
References fSetupRecord, and Instance().
Referenced by TTemplateConvolveAnalysedPulse::Draw(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and TemplateMultiFitter::TemplateMultiFitter().
{return *Instance().fSetupRecord;}
Long64_t EventNavigator::GetStartEntry () const
Returns the entry processing starts from.
Definition at line 101 of file EventNavigator.cpp.
References GetLoopSequence(), and LoopSequence::StartEntry().
Referenced by PlotTME_activeSiRmuStops::BeforeFirstEntry(), LoadPulses::BeforeFirstEntry(), and GetLoopNEntries().
{
  return GetLoopSequence().StartEntry();
}
Long64_t EventNavigator::GetStopEntry () const
Returns the past-the-end entry processing stops at.
Definition at line 108 of file EventNavigator.cpp.
References GetLoopSequence(), and LoopSequence::StopEntry().
Referenced by PlotTME_activeSiRmuStops::BeforeFirstEntry(), and GetLoopNEntries().
{
  return GetLoopSequence().StopEntry();
}
EventNavigator & EventNavigator::InitInstance (const ARGUMENTS & command_line) [static]
Definition at line 36 of file EventNavigator.cpp.
References EventNavigator(), and fInstance.
{
  if (fInstance) {
    std::cout << "WARNING: "
              << "Instance has already been created and will not be altered"
              << std::endl;
  }
  else {
    fInstance = new EventNavigator(command_line);
    //fInstance->fCopyRaw = true;
  }
  return *fInstance;
}
EventNavigator & EventNavigator::Instance () [static]
The user accessor. Not sure yet if it can be used without providing initalisation info.
Definition at line 50 of file EventNavigator.cpp.
References EventNavigator(), and fInstance.
Referenced by TemplateCreator::BeforeFirstEntry(), PlotTME_activeSiRmuStops::BeforeFirstEntry(), LoadPulses::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), FirstCompleteAPGenerator::DrawPulse(), Finish(), TTemplateFitAnalysedPulse::GetHisto(), GetSetupRecord(), LoopSequence::Init(), main(), Main_event_loop(), LoopSequence::Postprocess(), PrepareSingletonObjects(), LoopSequence::Preprocess(), LoopSequence::Process(), MakeAnalysedPulses::ProcessEntry(), ExportPulse::ProcessEntry(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and TemplateMultiFitter::TemplateMultiFitter().
{
  if (!fInstance){
    fInstance = new EventNavigator();
  }
  return *fInstance;
}
Int_t EventNavigator::LoadEntry (Long64_t entry) [protected]
Implementation for loading an entry.
Definition at line 354 of file EventNavigator.cpp.
References TGlobalData::Clear(), fEntryNo, fEventTree, fRawData, and fRawTree.
Referenced by ConnectRawData(), GetEntry(), MirrorRawInputFormat(), and NextEntry().
{
  Int_t nBytes = 0;
  if (fRawTree){
    fRawData->Clear();
    nBytes = fRawTree->GetEntry(entry);
  }
  else if (fEventTree) {
    nBytes = fEventTree->GetEntry(entry);
  }
  else return 0;
  if (nBytes < 0) throw io_error();
  fEntryNo = entry;
  return nBytes;
}
const LoopSequence & EventNavigator::MakeLoopSequence (const ARGUMENTS & args)
Initialises the LoopSequence this must be called once beforit is used. Calling it a second time is undefined behavior (currently forces an exception)
Definition at line 86 of file EventNavigator.cpp.
References fLoopSequence, and GetLoopSequence().
Referenced by Main_event_loop().
{
  //Not sure if allowing this to be replaced is safe. Lets err on the
  //side of caution and make it a runtime error for now.
  if (fLoopSequence) throw std::runtime_error("Redfined LoopSequence");
  fLoopSequence = new LoopSequence(args);
  return GetLoopSequence();
}
AnalysedPulseBankIter EventNavigator::MatchAnalysedBanks (const ChannelID & cid, GeneratorStr gid = "") const
PulseIslandBankIter EventNavigator::MatchAnalysedBanks (const SourceID & sid) const
AnalysedPulseBankIter EventNavigator::MatchDetectorBanks (const ChannelID & cid, GeneratorStr gid = "") const
PulseIslandBankIter EventNavigator::MatchDetectorBanks (const SourceID & sid) const
PulseIslandBankIter EventNavigator::MatchIslandBanks (const ChannelID & cid, GeneratorStr gid = "") const
PulseIslandBankIter EventNavigator::MatchIslandBanks (const SourceID & sid) const
Iterable getters for a list of banks.
Bool_t EventNavigator::MirrorRawInputFormat () [protected]
Copy the input raw data tree (TGlobalData) to the output file.
Definition at line 283 of file EventNavigator.cpp.
References fEntryNo, fOutputTreeTPI, TGlobalData::fPulseIslandToChannelMap, fRawData, GetEntry(), and LoadEntry().
Referenced by ConnectOutput().
{
  int prev_entry_no = fEntryNo;
  //loop untill we find an entry in which the object is filled (should
  //be the first one)
  int nBytes = 0;
  int entry = fEntryNo;
  while (( nBytes = LoadEntry(++entry) )){
    if (fRawData->fPulseIslandToChannelMap.size() > 0) break;
  }
  if (nBytes <= 0) return false;
  fOutputTreeTPI = new TTree("TPI","TPulseIslands");
  fOutputTreeTPI->SetAutoSave(3000000);
  typedef StringPulseIslandMap::const_iterator raw_map_iter;
  StringPulseIslandMap& rawBanks = fRawData->fPulseIslandToChannelMap;
  //fBufferTPI = new PulseIslandList*[rawBanks.size()];
  TObjArray* obj_arr = new TObjArray(rawBanks.size());
  //obj_arr = new TObjArray(rawBanks.size());
  //raw_map_iter b_it = fRawData->fPulseIslandToChannelMap.begin();
  Int_t element =0;
  for (raw_map_iter b_it = rawBanks.begin(); b_it != rawBanks.end(); ++b_it) {
    std::string bank_name = b_it->first;
    //fBufferTPI[element] = new PulseIslandList;
    //fRecordTPI.insert(make_pair(bank_name, fBufferTPI[element]));
    //fRecordTPI[bank_Name] = fBufferTPI[element]
    //fOutputTreeTPI->Branch(bank_name.c_str(), &fBufferTPI[element]);
    ++element;
    //TNamed* foo = new TNamed((bank_name + "_name").c_str(), (bank_name + "_title").c_str());
    BankBranch<PulseIslandList>* foo =
      new BankBranch<PulseIslandList>(IDs::generator(bank_name));
    obj_arr->Add(foo);
  }
  fOutputTreeTPI->Branch(obj_arr);
  fOutputTreeTPI->Print();
  fOutputTreeTPI->Write();
  GetEntry(prev_entry_no);
  return true;
}
Int_t EventNavigator::NextEntry () [inline]
Load the next entry in the input tree. Returns the number of bytes if sucessful, 0 if reached the end or there is no input tree. Throws an exception for an underlying I/O error
Definition at line 116 of file EventNavigator.h.
References fEntryNo, and LoadEntry().
{
    return LoadEntry(fEntryNo + 1);
  }
EventNavigator& EventNavigator::operator= (const EventNavigator & rhs) [inline, private]
Definition at line 232 of file EventNavigator.h.
{return *this;}
void EventNavigator::SetSavePulseIslands (bool save = 1) [inline]
Save (or not) TPulseIslands in output file. By default they are not saved, call this method to enable saving.
Definition at line 132 of file EventNavigator.h.
References fCopyRaw.
{fCopyRaw =save;};
Bool_t EventNavigator::VerifyRawData (TTree * raw_tree) [protected]
Verifies that the raw data tree found conforms to the expected format.
Definition at line 169 of file EventNavigator.cpp.
References AlCapFormat::Raw::DataBranchName, and AlCapFormat::Raw::SetupBranchName.
Referenced by ConnectRawData().
{
  if ( !raw_tree ){
    std::cerr << "No raw data tree in file" << std::endl;
    return false;
  }
  if ( raw_tree->GetEntriesFast() == 0 ){
    std::cerr << "Tree " << raw_tree->GetName() << " is empty!"
              << std::endl;
    return false;
  }
  TObjArray* lob = raw_tree->GetListOfBranches();
  if ( !lob->Contains(Format::Raw::DataBranchName ) ){
    std::cerr << "Tree " << raw_tree->GetName()
              << " has no branch " << Format::Raw::SetupBranchName
              << "!" << std::endl;
    return false;
  }
  return true;
}
Bool_t EventNavigator::VerifySetupData (TTree * setup_tree) [protected]
Verifies that the setup data tree found conforms to the expected format.
Definition at line 244 of file EventNavigator.cpp.
References AlCapFormat::Raw::SetupBranchName.
Referenced by ConnectSetupData().
{
  if ( !setup_tree ){
    std::cerr << "No 'Setup' tree in file" << std::endl;
    return false;
  }
  if ( setup_tree->GetEntriesFast() == 0 ){
    std::cerr << "Tree " << setup_tree->GetName() << " is empty!"
              << std::endl;
    return false;
  }
  TObjArray* lob = setup_tree->GetListOfBranches();
  if ( !lob->Contains(Format::Raw::SetupBranchName ) ){
    std::cerr << "Tree " << setup_tree->GetName()
              << " has no branch " << Format::Raw::SetupBranchName
              << "!" << std::endl;
    return false;
  }
  return true;
}
Int_t EventNavigator::WriteCurrentEntry ()
Definition at line 371 of file EventNavigator.cpp.
References fOutputTreeTPI.
{
  fOutputTreeTPI->Fill();
  return 0;
}
Member Data Documentation
Bool_t EventNavigator::fCopyRaw [private]
Definition at line 236 of file EventNavigator.h.
Referenced by ConnectOutput(), and SetSavePulseIslands().
Int_t EventNavigator::fEntryNo [private]
The current entry number.
Definition at line 245 of file EventNavigator.h.
Referenced by ConnectInput(), EntryNo(), LoadEntry(), MirrorRawInputFormat(), and NextEntry().
TTree* EventNavigator::fEventTree [private]
Definition at line 254 of file EventNavigator.h.
Referenced by LoadEntry().
EventNavigator * EventNavigator::fInstance = 0x0 [static, private]
Definition at line 234 of file EventNavigator.h.
Referenced by InitInstance(), and Instance().
LoopSequence* EventNavigator::fLoopSequence [private]
Definition at line 264 of file EventNavigator.h.
Referenced by GetLoopSequence(), and MakeLoopSequence().
TFile* EventNavigator::fOutput [private]
Output ROOT file (may be same as input file).
Definition at line 242 of file EventNavigator.h.
Referenced by Close(), ConnectOutput(), ConnectOutputFile(), EventNavigator(), and GetOutputFileName().
TTree* EventNavigator::fOutputTreeTPI [private]
Definition at line 256 of file EventNavigator.h.
Referenced by MirrorRawInputFormat(), and WriteCurrentEntry().
TGlobalData* EventNavigator::fRawData [private]
Definition at line 258 of file EventNavigator.h.
Referenced by ConnectOutput(), ConnectRawData(), GetRawData(), LoadEntry(), and MirrorRawInputFormat().
TFile* EventNavigator::fRawInput [private]
Input ROOT file, raw format.
Definition at line 239 of file EventNavigator.h.
Referenced by Close(), and EventNavigator().
TTree* EventNavigator::fRawTree [private]
Input Raw Data (Event) Tree.
Definition at line 248 of file EventNavigator.h.
Referenced by ConnectOutput(), ConnectRawData(), GetInputNEntries(), GetRawTree(), and LoadEntry().
TSetupData* EventNavigator::fSetupData [private]
Definition at line 260 of file EventNavigator.h.
Referenced by ConnectSetupData(), and GetSetupData().
SetupRecord* EventNavigator::fSetupRecord [private]
Definition at line 262 of file EventNavigator.h.
Referenced by ConnectSetupData(), and GetSetupRecord().
TTree* EventNavigator::fSetupTree [private]
Input Setup Tree.
Definition at line 251 of file EventNavigator.h.
Referenced by ConnectInput(), and ConnectSetupData().
The documentation for this class was generated from the following files:
rootana/src/framework/EventNavigator.h
rootana/src/framework/EventNavigator.cpp