AlcapDAQ: PassThroughDPGenerator Class Reference
PassThroughDPGenerator Class Reference
#include <PassThroughDPGenerator.h>
Public Member Functions
PassThroughDPGenerator (TDPGeneratorOptions *opts)
virtual ~PassThroughDPGenerator ()
virtual bool ChecksForPileUp () const
virtual int ProcessPulses (DetectorPulseList &output)
void SetPulseSources (const IDs::source &fast, const IDs::source &slow)
void SetPulseLists (const AnalysedPulseList *fast, const AnalysedPulseList *slow)
void SetDebug (const bool &val=true)
bool Debug ()
TDetectorPulse * MakeTDP (int fast_parent, int slow_parent) const
IDs::source GetSource () const
IDs::source GetFastSource () const
IDs::source GetSlowSource () const
void SetChannel (const IDs::channel &ch)
IDs::generator GetGeneratorID () const
const AnalysedPulseList * FastPulseList () const
const AnalysedPulseList * SlowPulseList () const
const AnalysedPulseList * PulseList (bool getFast) const
Static Public Member Functions
static const IDs::generator & GetStaticId ()
Private Attributes
bool fUseFast
Static Private Attributes
static IDs::generator fStaticId = IDs::generator("PassThrough", IDs::kAnyConfig)
Detailed Description
Definition at line 6 of file PassThroughDPGenerator.h.
Constructor & Destructor Documentation
PassThroughDPGenerator::PassThroughDPGenerator (TDPGeneratorOptions * opts)
Definition at line 10 of file PassThroughDPGenerator.cpp.
                                                                       :
    TVDetectorPulseGenerator("PassThrough",opts), fUseFast(opts->GetBool("use_fast",true)){
    // double check that we can use the slow source, ie. for detectors where
    // the fast / slow channel are different
}
virtual PassThroughDPGenerator::~PassThroughDPGenerator () [inline, virtual]
Definition at line 10 of file PassThroughDPGenerator.h.
{};
Member Function Documentation
virtual bool PassThroughDPGenerator::ChecksForPileUp () const [inline, virtual]
Implements TVDetectorPulseGenerator.
Definition at line 11 of file PassThroughDPGenerator.h.
{return false;};
bool TVDetectorPulseGenerator::Debug () [inline, inherited]
Definition at line 34 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fDebug.
Referenced by MaxTimeDiffDPGenerator::ProcessPulses().
{return fDebug;};
const AnalysedPulseList* TVDetectorPulseGenerator::FastPulseList () const [inline, inherited]
Definition at line 53 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fFastPulses.
Referenced by MaxTimeDiffDPGenerator::ProcessPulses().
{return fFastPulses;}
IDs::source TVDetectorPulseGenerator::GetFastSource () const [inline, inherited]
Definition at line 48 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fFastSource.
Referenced by MaxTimeDiffDPGenerator::ProcessPulses().
{return fFastSource;};
IDs::generator TVDetectorPulseGenerator::GetGeneratorID () const [inline, inherited]
Definition at line 51 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fSource, and IDs::source::Generator().
Referenced by MakeDetectorPulses::MakeGenerator().
{return fSource.Generator();}
IDs::source TVDetectorPulseGenerator::GetSlowSource () const [inline, inherited]
Definition at line 49 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fSlowSource.
Referenced by MaxTimeDiffDPGenerator::ProcessPulses().
{return fSlowSource;};
IDs::source TVDetectorPulseGenerator::GetSource () const [inline, inherited]
Definition at line 47 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fSource.
Referenced by MakeDetectorPulses::GetPassThruGeneratorID(), and TVDetectorPulseGenerator::MakeTDP().
{return fSource;};
static const IDs::generator& PassThroughDPGenerator::GetStaticId () [inline, static]
Definition at line 12 of file PassThroughDPGenerator.h.
References fStaticId.
Referenced by PlotTDPs::BeforeFirstEntry().
{return fStaticId;};
TDetectorPulse* TVDetectorPulseGenerator::MakeTDP (int fast_parent, int slow_parent) const [inline, inherited]
Definition at line 36 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fFastPulses, TVDetectorPulseGenerator::fSlowPulses, and TVDetectorPulseGenerator::GetSource().
Referenced by ProcessPulses(), and MaxTimeDiffDPGenerator::ProcessPulses().
{
      TDetectorPulse* pulse=NULL;
      const TAnalysedPulse* fast=NULL;
      if(fFastPulses && fast_parent>=0) fast=fFastPulses->at(fast_parent);
      const TAnalysedPulse* slow=NULL;
      if(fSlowPulses && slow_parent>=0) slow=fSlowPulses->at(slow_parent);
      if(fast || slow) {
          pulse=new TDetectorPulse(GetSource(),fast_parent,fast,slow_parent,slow);
      }
      return pulse;
  }
int PassThroughDPGenerator::ProcessPulses (DetectorPulseList & output) [virtual]
Implements TVDetectorPulseGenerator.
Definition at line 16 of file PassThroughDPGenerator.cpp.
References fUseFast, TVDetectorPulseGenerator::MakeTDP(), TVDetectorPulseGenerator::PulseList(), and TVDetectorPulseGenerator::SetPulseLists().
{
    const AnalysedPulseList* pulses=PulseList(fUseFast);
    // Major hack to force fill both channels in the produced TDP which makes
    // later analysis easier
    SetPulseLists(pulses,pulses);
    for(AnalysedPulseList::const_iterator i_pulse=pulses->begin();
            i_pulse!=pulses->end(); i_pulse++){
        TDetectorPulse* det_pulse = MakeTDP(i_pulse-pulses->begin(),i_pulse-pulses->begin()); // Create the TDetectorPulse
        output.push_back(det_pulse);
    }
    return 0;
}
const AnalysedPulseList* TVDetectorPulseGenerator::PulseList (bool getFast) const [inline, inherited]
Definition at line 55 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fFastPulses, and TVDetectorPulseGenerator::fSlowPulses.
Referenced by ProcessPulses().
{return getFast?fFastPulses:fSlowPulses;}
void TVDetectorPulseGenerator::SetChannel (const IDs::channel & ch) [inline, inherited]
Definition at line 50 of file TVDetectorPulseGenerator.h.
References IDs::source::Channel(), and TVDetectorPulseGenerator::fSource.
{fSource.Channel()=ch;};
void TVDetectorPulseGenerator::SetDebug (const bool & val = true) [inline, inherited]
Definition at line 33 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fDebug.
Referenced by MakeDetectorPulses::MakeGenerator().
{fDebug=val;};
void TVDetectorPulseGenerator::SetPulseLists (const AnalysedPulseList * fast, const AnalysedPulseList * slow) [inline, inherited]
Definition at line 28 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fFastPulses, and TVDetectorPulseGenerator::fSlowPulses.
Referenced by ProcessPulses().
{
      fFastPulses=fast;
      fSlowPulses=slow;
  }
void TVDetectorPulseGenerator::SetPulseSources (const IDs::source & fast, const IDs::source & slow) [inline, inherited]
Definition at line 24 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fFastSource, and TVDetectorPulseGenerator::fSlowSource.
Referenced by MakeDetectorPulses::MakeGenerator().
{
      fFastSource=fast;
      fSlowSource=slow;
  }
const AnalysedPulseList* TVDetectorPulseGenerator::SlowPulseList () const [inline, inherited]
Definition at line 54 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fSlowPulses.
Referenced by MaxTimeDiffDPGenerator::ProcessPulses().
{return fSlowPulses;}
Member Data Documentation
IDs::generator PassThroughDPGenerator::fStaticId = IDs::generator("PassThrough", IDs::kAnyConfig) [static, private]
Definition at line 19 of file PassThroughDPGenerator.h.
Referenced by GetStaticId().
bool PassThroughDPGenerator::fUseFast [private]
Definition at line 18 of file PassThroughDPGenerator.h.
Referenced by ProcessPulses().
The documentation for this class was generated from the following files:
rootana/src/TDP_generators/PassThroughDPGenerator.h
rootana/src/TDP_generators/PassThroughDPGenerator.cpp