AlcapDAQ: LoadPulses Class Reference
LoadPulses Class Reference
[Modules]
A one line description of what your module does.
#include <LoadPulses.h>
Public Member Functions
LoadPulses (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~LoadPulses ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::map< IDs::source,
TClonesArray * > SourceToClonesArrayMap
typedef std::vector< std::pair
< IDs::source, TBranch * > > BranchList
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Private Attributes
std::string fFileName
std::string fTreeName
TTree * fInTree
Long64_t fCurrentEntry
Long64_t fNumEntries
SourceToClonesArrayMap fArrays
BranchList fBranches
Detailed Description
A one line description of what your module does.
Author:
AuthorName
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 25 of file LoadPulses.h.
Member Typedef Documentation
typedef std::vector<std::pair<IDs::source, TBranch*> > LoadPulses::BranchList [private]
Definition at line 64 of file LoadPulses.h.
typedef std::map<IDs::source,TClonesArray*> LoadPulses::SourceToClonesArrayMap [private]
Definition at line 62 of file LoadPulses.h.
Constructor & Destructor Documentation
LoadPulses::LoadPulses (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 23 of file LoadPulses.cpp.
References fFileName, fTreeName, and modules::options::GetString().
                                          :
   BaseModule("LoadPulses",opts){
       fFileName=opts->GetString("file_name");
       fTreeName=opts->GetString("tree_name","TAP_tree");
}
LoadPulses::~LoadPulses ()
Is anything done in the destructor?
Definition at line 29 of file LoadPulses.cpp.
                       {
}
Member Function Documentation
int LoadPulses::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 117 of file LoadPulses.cpp.
{
  return 0;
}
int LoadPulses::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 32 of file LoadPulses.cpp.
References fArrays, fBranches, fCurrentEntry, fFileName, fInTree, fNumEntries, fTreeName, gAnalysedPulseMap, EventNavigator::GetStartEntry(), and EventNavigator::Instance().
{
    // open the file
    if(fFileName.empty()){
        cout<<"LoadPulses: Error: no input file specified "<<endl;
        return 1;
    }
    TFile* inFile=TFile::Open(fFileName.c_str(), "READ");
    if(!inFile){
        cout<<"LoadPulses: Error: Unable to open input file, "<<fFileName<<endl;
        return 2;
    }
    // open the tree
    inFile->GetObject(fTreeName.c_str(),fInTree);
    if(!fInTree){
        cout<<"LoadPulses: Error: Unable to find input tree, "<<fTreeName<<" in file "<<fFileName<<endl;
        return 3;
    }
    // Prepare the TAP flyweights
    FlyWeight<IDs::source,TAnalysedPulse::Tag>::LoadProxyList(gDirectory,"TAP_sources");
    // Loop over each branch
    TObjArray* listOfArraysOfTAPs=fInTree->GetListOfBranches();
    TBranchClones* branch;
    IDs::source tmp_source;
    for(int i_array=0;i_array<listOfArraysOfTAPs->GetSize();i_array++){
        // Get the branch
        branch=(TBranchClones*)listOfArraysOfTAPs->At(i_array);
        if(!branch) continue;
        // Create the corrsponding source ID
        tmp_source=branch->GetName();
        // Add to the list of branches
        fBranches.push_back(std::make_pair(tmp_source,branch));
        // Prepare gAnalysedPulseMap
        gAnalysedPulseMap[tmp_source];
    }
    for(BranchList::iterator i_branch=fBranches.begin();
            i_branch!=fBranches.end(); ++i_branch){
        // Set the TClonesArray address
        i_branch->second->SetAddress(&fArrays[i_branch->first]);
    }
    //fInTree->SetDebug();
    // Get the first entry to read from
    fCurrentEntry=EventNavigator::Instance().GetStartEntry();
    fNumEntries=fInTree->GetEntries();
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int LoadPulses::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 80 of file LoadPulses.cpp.
References fArrays, fCurrentEntry, fInTree, fNumEntries, and gAnalysedPulseMap.
{
    if(fCurrentEntry>fNumEntries){
        cout<<"LoadPulses: Error: input file contains no more entries so I'm stopping the run"<<endl;
        return 1;
    }
    fInTree->GetEntry(fCurrentEntry);
    int n_entries=0;
    SourceAnalPulseMap::iterator i_output;
    AnalysedPulseList* pulseList;
    for(SourceToClonesArrayMap::iterator i_array=fArrays.begin();
            i_array!=fArrays.end(); ++i_array){
        // Get the pulse list to put the TAPs into
        i_output=gAnalysedPulseMap.find(i_array->first);
        if(i_output==gAnalysedPulseMap.end()){
            cout<<"LoadPulses: Error: gAnalysedPulseMap doesn't contain a pulse list for "<<i_array->first<<endl;
            return 1;
        }
        pulseList=&i_output->second;
        // Loop over each TAP on file and put it into gAnalysedPulseMap;
        n_entries=i_array->second->GetEntries();
        TAnalysedPulse* pulse;
        for(int i_pulse=0;i_pulse<n_entries;++i_pulse){
            pulse=(TAnalysedPulse*)(i_array->second->At(i_pulse));
            pulseList->push_back(pulse);
        }
    }
    //for (SourceAnalPulseMap::const_iterator i_source = gAnalysedPulseMap.begin();
    //        i_source != gAnalysedPulseMap.end(); ++i_source) {
    //    cout<<i_source->second.size()<<" pulses for source: "<<i_source->first<<"  "<<endl;
    //}
    ++fCurrentEntry;
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
SourceToClonesArrayMap LoadPulses::fArrays [private]
Definition at line 63 of file LoadPulses.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
BranchList LoadPulses::fBranches [private]
Definition at line 65 of file LoadPulses.h.
Referenced by BeforeFirstEntry().
Long64_t LoadPulses::fCurrentEntry [private]
Definition at line 60 of file LoadPulses.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
std::string LoadPulses::fFileName [private]
Definition at line 57 of file LoadPulses.h.
Referenced by BeforeFirstEntry(), and LoadPulses().
TTree* LoadPulses::fInTree [private]
Definition at line 59 of file LoadPulses.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
Long64_t LoadPulses::fNumEntries [private]
Definition at line 61 of file LoadPulses.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
std::string LoadPulses::fTreeName [private]
Definition at line 58 of file LoadPulses.h.
Referenced by BeforeFirstEntry(), and LoadPulses().
The documentation for this class was generated from the following files:
rootana/src/LoadPulses.h
rootana/src/LoadPulses.cpp