AlcapDAQ: hash_utils::MurmurHash3 Class Reference
hash_utils::MurmurHash3 Class Reference
#include <hash.h>
Public Types
typedef const Byte_t * MsgPtr_t
typedef UInt_t Hash_t
typedef Int_t Length_t
typedef Byte_t Rot_t
Public Member Functions
MurmurHash3 (unsigned int seed=0xe086c5ff)
void Add (MsgPtr_t msg_ptr, Length_t len)
Hash_t End ()
Private Member Functions
void MixTail (MsgPtr_t &data, Length_t &len)
UInt_t rot32 (UInt_t bits, Rot_t r)
void mmix (Hash_t &h, UInt_t &bits)
void final_mix (Hash_t &h)
Private Attributes
Hash_t fHash
UInt_t fTail
UInt_t fCount
UInt_t fSize
Static Private Attributes
static const UInt_t kMply1 = 0xcc9e2d51
static const UInt_t kMply2 = 0x1b873593
Detailed Description
Definition at line 27 of file hash.h.
Member Typedef Documentation
typedef UInt_t hash_utils::MurmurHash3::Hash_t
Definition at line 30 of file hash.h.
typedef Int_t hash_utils::MurmurHash3::Length_t
Definition at line 31 of file hash.h.
typedef const Byte_t* hash_utils::MurmurHash3::MsgPtr_t
Definition at line 29 of file hash.h.
typedef Byte_t hash_utils::MurmurHash3::Rot_t
Definition at line 32 of file hash.h.
Constructor & Destructor Documentation
hash_utils::MurmurHash3::MurmurHash3 (unsigned int seed = 0xe086c5ff) [inline]
Definition at line 34 of file hash.h.
    : fHash(seed), fTail(0), fCount(0), fSize(0)
  {}
Member Function Documentation
void MurmurHash3::Add (MsgPtr_t msg_ptr, Length_t len)
Definition at line 53 of file hash.cpp.
References fHash, fSize, MixTail(), and mmix().
{
  fSize += len;
  while(len >= 4) {
    UInt_t k = *(reinterpret_cast<const UInt_t*>(msg_ptr));
    mmix(fHash, k);
    msg_ptr += 4;
    len -= 4;
  }
  MixTail(msg_ptr,len);
}
MurmurHash3::Hash_t MurmurHash3::End ()
Definition at line 71 of file hash.cpp.
References fHash, final_mix(), fSize, fTail, and mmix().
{
  if (fTail) mmix(fHash, fTail);
  fHash ^= fSize;
  final_mix(fHash);
  return fHash;
}
void hash_utils::MurmurHash3::final_mix (Hash_t & h) [inline, private]
Definition at line 55 of file hash.h.
Referenced by End().
  {
    h ^= h >> 16;   h *= 0x85ebca6b;
    h ^= h >> 13;   h *= 0xc2b2ae35;
    h ^= h >> 16;
  }
void MurmurHash3::MixTail (MsgPtr_t & data, Length_t & len) [private]
Definition at line 83 of file hash.cpp.
References fCount, fHash, fTail, and mmix().
Referenced by Add().
{
  while( len && ((len<4) || fCount)) {
    fTail |= (*data++) << (fCount * 8);
    fCount++;
    len--;
    if(fCount == 4){
      mmix(fHash, fTail);
      fTail = 0;
      fCount = 0;
    }
  }
}
void hash_utils::MurmurHash3::mmix (Hash_t & h, UInt_t & bits) [inline, private]
Definition at line 49 of file hash.h.
References kMply1, kMply2, and rot32().
Referenced by Add(), End(), and MixTail().
  {
    bits *= kMply1;   bits = rot32(bits, 15);   bits *= kMply2;
    h ^= bits;   h = rot32(h, 13) * 5 + 0xe6546b64;
  }
UInt_t hash_utils::MurmurHash3::rot32 (UInt_t bits, Rot_t r) [inline, private]
Definition at line 44 of file hash.h.
Referenced by mmix().
  {
    return (bits << r) | (bits >> (32 - r));
  }
Member Data Documentation
UInt_t hash_utils::MurmurHash3::fCount [private]
Definition at line 72 of file hash.h.
Referenced by MixTail().
Hash_t hash_utils::MurmurHash3::fHash [private]
Definition at line 70 of file hash.h.
Referenced by Add(), End(), and MixTail().
UInt_t hash_utils::MurmurHash3::fSize [private]
Definition at line 73 of file hash.h.
Referenced by Add(), and End().
UInt_t hash_utils::MurmurHash3::fTail [private]
Definition at line 71 of file hash.h.
Referenced by End(), and MixTail().
const UInt_t hash_utils::MurmurHash3::kMply1 = 0xcc9e2d51 [static, private]
Definition at line 62 of file hash.h.
Referenced by mmix().
const UInt_t hash_utils::MurmurHash3::kMply2 = 0x1b873593 [static, private]
Definition at line 63 of file hash.h.
Referenced by mmix().
The documentation for this class was generated from the following files:
rootana/src/framework/hash.h
rootana/src/framework/hash.cpp