AlcapDAQ: MakeDetectorPulses Class Reference
MakeDetectorPulses Class Reference
#include <MakeDetectorPulses.h>
Classes
struct Detector_t
Public Member Functions
MakeDetectorPulses (modules::options *opts)
~MakeDetectorPulses ()
void SetAlgorithm (const TString &algorithm)
void SetDetectorPulseMap (StringDetPulseMap &aMap)
IDs::generator GetPassThruGeneratorID () const
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::set< Detector_t > ChannelPairing_t
Private Member Functions
TVDetectorPulseGenerator * MakeGenerator (const std::string &generatorType, TDPGeneratorOptions *opts)
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
The big kahuna. Overload this in the derived class and it will be called for each event.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
void DumpgAnalysedPulseMap (const SourceAnalPulseMap &aMap)
Private Attributes
TVDetectorPulseGenerator * fPassThruGenerator
TVDetectorPulseGenerator * fGenerator
StringDetPulseMap * fDetectorPulseMap
ChannelPairing_t fFastSlowPairs
modules::options * fOptions
std::string fAlgorithm
std::string fPassThruName
Detailed Description
Definition at line 18 of file MakeDetectorPulses.h.
Member Typedef Documentation
typedef std::set<Detector_t > MakeDetectorPulses::ChannelPairing_t [private]
Definition at line 57 of file MakeDetectorPulses.h.
Constructor & Destructor Documentation
MakeDetectorPulses::MakeDetectorPulses (modules::options * opts)
Definition at line 13 of file MakeDetectorPulses.cpp.
References fAlgorithm, fPassThruName, and modules::options::GetString().
                                                          :
    BaseModule("MakeDetectorPulses",opts,false),fOptions(opts){
        // Get the algorithm option from the modules file
        // If nothing was set, use MaxTimeDiff by default
        fAlgorithm=opts->GetString("default_algorithm","MaxTimeDiff");
        fPassThruName=opts->GetString("pass_through_algorithm","PassThrough");
    }
MakeDetectorPulses::~MakeDetectorPulses ()
Definition at line 21 of file MakeDetectorPulses.cpp.
{
}
Member Function Documentation
virtual int MakeDetectorPulses::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [inline, private, virtual]
Optional method which is called once after the main event loop Can be used to dump a summary or finalise a histogram
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 49 of file MakeDetectorPulses.h.
{return 0;}
int MakeDetectorPulses::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Optional method which is called once before the main event loop Can be used to parse options and setup histograms.
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 24 of file MakeDetectorPulses.cpp.
References IDs::source::Channel(), BaseModule::Debug(), fAlgorithm, fFastSlowPairs, fGenerator, fOptions, fPassThruGenerator, fPassThruName, gAnalysedPulseMap, gDetectorPulseMap, IDs::source::Generator(), IDs::channel::GetCorrespondingFastSlow(), TVDetectorPulseGenerator::GetGeneratorID(), IDs::channel::isFast(), IDs::kNotApplicable, MakeGenerator(), and IDs::generator::Type().
{
    // Set up the generator
    TDPGeneratorOptions gen_opts("gen opts",fOptions);
    fGenerator=MakeGenerator(fAlgorithm,&gen_opts);
    fPassThruGenerator=MakeGenerator(fPassThruName,&gen_opts);
    if(!fGenerator) return 1;
    const IDs::channel* ch;
    const IDs::generator* gen;
    IDs::source partner;
    IDs::source tdp_source;
    // Find all fast detectors
    TVDetectorPulseGenerator* generator;
    for (SourceAnalPulseMap::const_iterator i_source = gAnalysedPulseMap.begin();
            i_source != gAnalysedPulseMap.end(); i_source++) {
        ch=&i_source->first.Channel();
        gen=&i_source->first.Generator();
        // Find the correct source since the generator options could be different
        for (SourceAnalPulseMap::const_iterator j_source = gAnalysedPulseMap.begin();
             j_source != gAnalysedPulseMap.end(); ++j_source) {
          if (j_source->first.Generator().Type() == gen->Type()
              && j_source->first.Channel() == ch->GetCorrespondingFastSlow()) {
            partner = j_source->first;
          }
        }
        if (gAnalysedPulseMap.count(partner)==0) partner=i_source->first;
        // if there is no corresponding fast / slow channel then use the pass
        // through generator
        if(partner==i_source->first) {
            generator=fPassThruGenerator;
        } else {
            generator=fGenerator;
        }
        // Prepare the source ID for the TDP generator
        tdp_source=i_source->first;
        tdp_source.Channel().SlowFast(IDs::kNotApplicable);
        tdp_source.Generator()=generator->GetGeneratorID();
        if(ch->isFast()) {
            // fast channels go first
            fFastSlowPairs.insert(Detector_t(tdp_source, i_source->first,partner,generator));
        }else{
            // slow channels go second
            // if both fast and slow are the same then later there will be
            // nothing to do.
            fFastSlowPairs.insert(Detector_t(tdp_source, partner,i_source->first,generator));
        }
    }
    // setup gDetectorPulseMap to contain all pulse lists for each TDP source
    for( ChannelPairing_t::iterator i=fFastSlowPairs.begin();i!=fFastSlowPairs.end();i++){
        gDetectorPulseMap[i->source];
        if(Debug()){
            std::cout<<"Paired: "<<i->fast<<" with "<<i->slow<<" processed by: "<<i->generator->GetGeneratorID()<<std::endl;
        }
    }
    return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeGenerator(), ExportPulse::PlotTPI(), ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
void MakeDetectorPulses::DumpgAnalysedPulseMap (const SourceAnalPulseMap & aMap) [private]
Definition at line 156 of file MakeDetectorPulses.cpp.
Referenced by ProcessEntry().
{
    std::cout<<"gAnalysedPulseMap contains:"<<std::endl;
    for(SourceAnalPulseMap::const_iterator it=aMap.begin();
            it!=aMap.end(); it++){
        cout<<it->first<<" contains "<<it->second.size()<<" TAPs"<<endl;
    }
}
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
IDs::generator MakeDetectorPulses::GetPassThruGeneratorID () const [inline]
Definition at line 41 of file MakeDetectorPulses.h.
References fPassThruGenerator, IDs::source::Generator(), and TVDetectorPulseGenerator::GetSource().
Referenced by PlotTDPs::BeforeFirstEntry().
{
        return fPassThruGenerator?fPassThruGenerator->GetSource().Generator():IDs::generator();
    }
TVDetectorPulseGenerator * MakeDetectorPulses::MakeGenerator (const std::string & generatorType, TDPGeneratorOptions * opts) [private]
Definition at line 145 of file MakeDetectorPulses.cpp.
References TemplateFactory< BaseModule, OptionsType >::createModule(), BaseModule::Debug(), TDPGeneratorFactory::Instance(), and TVDetectorPulseGenerator::SetDebug().
Referenced by BeforeFirstEntry().
{
    // Select the generator type
    TVDetectorPulseGenerator* generator=TDPGeneratorFactory::Instance()->createModule(generatorType,opts);
    if (!generator){
        return NULL;
    }
    // setup some options on the generator
    generator->SetDebug(Debug());
    return generator;
}
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int MakeDetectorPulses::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
The big kahuna. Overload this in the derived class and it will be called for each event.
Parameters:
gData Pointer to current map of all TPIs [ WILL CHANGE SHORTLY ]
gSetup Pointer to TSetupData for this run [ WILL CHANGE SHORTLY ]
Returns:
0 on success and non-zero on failure
Implements BaseModule.
Definition at line 87 of file MakeDetectorPulses.cpp.
References BaseModule::Debug(), DumpgAnalysedPulseMap(), fFastSlowPairs, gAnalysedPulseMap, gDetectorPulseMap, IDs::kAnyDetector, IDs::kNotApplicable, and IDs::source::source().
{
    IDs::channel detector(IDs::kAnyDetector,IDs::kNotApplicable);
    IDs::source source;
    const AnalysedPulseList *slow_pulses;
    const AnalysedPulseList *fast_pulses;
    SourceAnalPulseMap::const_iterator current;
    //DetectorPulseList *detectorPulses;
    // Loop through paired channels
    for (ChannelPairing_t::const_iterator i_detector = fFastSlowPairs.begin();
            i_detector != fFastSlowPairs.end(); i_detector++) {
        detector=i_detector->fast.Channel();
        // find the list of analyzed pulses for the fast channel
        current=gAnalysedPulseMap.find(i_detector->fast);
        if(current==gAnalysedPulseMap.end()){
            std::cout<<"Unable to find source for fast channel: "<<i_detector->fast<<std::endl;
            DumpgAnalysedPulseMap(gAnalysedPulseMap);
            return 1;
        }
        fast_pulses=&(current->second);
        // check if the fast_pulses is empty
        if(fast_pulses->empty()) {
            if(Debug()) cout<< "List of TAPs for "<<i_detector->fast<<" is empty."<<endl;
            continue;
        }
        // if the fast and slow sources are the same then pass the slow channel
        // as NULL
        if(i_detector->fast==i_detector->slow) slow_pulses=NULL;
        else{
            current=gAnalysedPulseMap.find(i_detector->slow);
            if(current==gAnalysedPulseMap.end()){
                std::cout<<"Unable to find source for slow channel: "<<i_detector->slow<<std::endl;
                DumpgAnalysedPulseMap(gAnalysedPulseMap);
                return 1;
            }
            slow_pulses=&(current->second);
            // check if the fast_pulses is empty
            if(slow_pulses->empty()) {
                if(Debug())
                cout<< "List of TAPs for "<<i_detector->slow<<" is empty."<<endl;
                continue;
            }
        }
        // Set the channel
        i_detector->generator->SetChannel(detector);
        // Set the pulse lists
        i_detector->generator->SetPulseLists(fast_pulses,slow_pulses);
        // Process the pulses
        source=i_detector->source;
        i_detector->generator->ProcessPulses(gDetectorPulseMap.at(source));
    }
    return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void MakeDetectorPulses::SetAlgorithm (const TString & algorithm) [inline]
Definition at line 38 of file MakeDetectorPulses.h.
References fAlgorithm.
{fAlgorithm=algorithm;};
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
void MakeDetectorPulses::SetDetectorPulseMap (StringDetPulseMap & aMap) [inline]
Definition at line 39 of file MakeDetectorPulses.h.
References fDetectorPulseMap.
{fDetectorPulseMap=&aMap;}
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
std::string MakeDetectorPulses::fAlgorithm [private]
Definition at line 60 of file MakeDetectorPulses.h.
Referenced by BeforeFirstEntry(), MakeDetectorPulses(), and SetAlgorithm().
StringDetPulseMap* MakeDetectorPulses::fDetectorPulseMap [private]
Definition at line 56 of file MakeDetectorPulses.h.
Referenced by SetDetectorPulseMap().
ChannelPairing_t MakeDetectorPulses::fFastSlowPairs [private]
Definition at line 58 of file MakeDetectorPulses.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
TVDetectorPulseGenerator* MakeDetectorPulses::fGenerator [private]
Definition at line 55 of file MakeDetectorPulses.h.
Referenced by BeforeFirstEntry().
modules::options* MakeDetectorPulses::fOptions [private]
Definition at line 59 of file MakeDetectorPulses.h.
Referenced by BeforeFirstEntry().
TVDetectorPulseGenerator* MakeDetectorPulses::fPassThruGenerator [private]
Definition at line 54 of file MakeDetectorPulses.h.
Referenced by BeforeFirstEntry(), and GetPassThruGeneratorID().
std::string MakeDetectorPulses::fPassThruName [private]
Definition at line 60 of file MakeDetectorPulses.h.
Referenced by BeforeFirstEntry(), and MakeDetectorPulses().
The documentation for this class was generated from the following files:
rootana/src/TDP_generators/MakeDetectorPulses.h
rootana/src/TDP_generators/MakeDetectorPulses.cpp