AlcapDAQ: MqlArray< T > Class Template Reference
MqlArray< T > Class Template Reference
#include <MqlArray.h>
Public Member Functions
MqlArray ()
~MqlArray ()
T & operator[] (int i)
int next ()
int size ()
void setSize (int size)
void reset ()
void finish ()
void sort (int(*compar)(const void *, const void *))
bool checkSort (int(*compar)(const void *, const void *))
void realloc (int minSize)
void fromBank (void *pevent, char *bankName)
void toBank (void *pevent, char *bankName)
Private Attributes
T * fArray
int fAllocation
int fSize
int fLastSize
bool fImmutable
Detailed Description
template<typename T>
class MqlArray< T >
Definition at line 18 of file MqlArray.h.
Constructor & Destructor Documentation
template<typename T> MqlArray< T >::MqlArray () inline
Definition at line 22 of file MqlArray.h.
References MqlArray< T >::fAllocation, MqlArray< T >::fArray, MqlArray< T >::fImmutable, MqlArray< T >::fLastSize, and MqlArray< T >::fSize.
              {
     fArray = NULL;
     fSize = 0;
     fLastSize = 0;
     fAllocation = 0;
     fImmutable = false;
   }
template<typename T> MqlArray< T >::~MqlArray () inline
Definition at line 30 of file MqlArray.h.
References MqlArray< T >::fArray, and MqlArray< T >::fImmutable.
               {
     if(!fImmutable && fArray != NULL) {
       delete[] fArray;
     }
   }
Member Function Documentation
template<typename T> bool MqlArray< T >::checkSort (int(*)(const void *, const void *) compar) inline
Definition at line 90 of file MqlArray.h.
References MqlArray< T >::fSize, i, and printf().
Referenced by MMuPC1AnalysisMQL(), and MMuSCAnalysisMQL().
{
     for(int i = 1; i < fSize; i++) {
 //      if(compar(&fArray[i-1], &fArray[i]) > 0) {
       if(compar(&(*this)[i-1], &(*this)[i]) > 0) {
 printf("checkSort: problem at element %d\n", i);
         return false;
       }
     }
     return true;
   }
template<typename T> void MqlArray< T >::finish () inline
Definition at line 67 of file MqlArray.h.
References MqlArray< T >::fAllocation, MqlArray< T >::fArray, MqlArray< T >::fImmutable, MqlArray< T >::fLastSize, and MqlArray< T >::fSize.
Referenced by MMuPC1AnalysisMQL(), and MMuSCAnalysisMQL().
{
 #if 0
     if(!fImmutable) {
       fAllocation = 0;
       fLastSize = fSize;
       fSize = 0;
       if(fArray != NULL) {
         delete[] fArray;
         fArray = NULL;
       }
     }
 #else
     if(!fImmutable) {
       fSize = 0;
     }
 #endif
   }
template<typename T> void MqlArray< T >::fromBank (void * pevent, char * bankName) inline
Definition at line 126 of file MqlArray.h.
References MqlArray< T >::fArray, MqlArray< T >::fImmutable, MqlArray< T >::fSize, and printf().
Referenced by MMuPC1AnalysisMQL(), and MMuSCAnalysisMQL().
{
     fSize = bk_locate(pevent, bankName, (DWORD*) &fArray)
              * sizeof(DWORD) / sizeof(T);
     if(fArray == NULL)
     {
       printf("Warning: could not find bank %s\n", bankName);
     }
     fImmutable = true;
   }
template<typename T> int MqlArray< T >::next () inline
Definition at line 40 of file MqlArray.h.
References MqlArray< T >::fSize, and MqlArray< T >::setSize().
Referenced by MMuPC1AnalysisMQL(), and MMuSCAnalysisMQL().
                     {
     int retval = fSize;
     setSize(fSize + 1);
     return retval;
   }
template<typename T> T& MqlArray< T >::operator[] (int i) inline
Definition at line 36 of file MqlArray.h.
References MqlArray< T >::fArray, and i.
{
     return fArray[i];
   }
template<typename T> void MqlArray< T >::realloc (int minSize) inline
Definition at line 102 of file MqlArray.h.
References MqlArray< T >::fAllocation, MqlArray< T >::fArray, MqlArray< T >::fSize, REALLOC_C, and REALLOC_N.
Referenced by MqlArray< T >::reset(), and MqlArray< T >::setSize().
{
     int newSize = REALLOC_N*fAllocation + REALLOC_C;
     if(minSize > newSize) {
       newSize = minSize;
     }
     // make a new array and put it into place
     T *oldArray = fArray;
     T *newArray = new T[newSize];
     fArray = newArray;
     fAllocation = newSize;
     // copy the contents and delete the old array
     if(oldArray != NULL) {
       memcpy(newArray, oldArray, fSize*sizeof(T));
       memset(newArray+fSize, 0, (newSize-fSize)*sizeof(T));
       delete[] oldArray;
     } else {
       memset(newArray, 0, (newSize)*sizeof(T));
     }
   }
template<typename T> void MqlArray< T >::reset () inline
Definition at line 57 of file MqlArray.h.
References MqlArray< T >::fImmutable, MqlArray< T >::fLastSize, MqlArray< T >::fSize, and MqlArray< T >::realloc().
Referenced by MMuPC1AnalysisMQL(), and MMuSCAnalysisMQL().
                       {
 #if 0
     if(!fImmutable) {
       int nextSize = (int) (fLastSize * 0.9);
       fSize = 0;
       realloc(nextSize);
     }
 #endif
   }
template<typename T> void MqlArray< T >::setSize (int size) inline
Definition at line 50 of file MqlArray.h.
References MqlArray< T >::fAllocation, MqlArray< T >::fSize, MqlArray< T >::realloc(), and MqlArray< T >::size().
Referenced by MqlArray< T >::next().
{
     if(size > fAllocation) {
       realloc(size);
     }
     fSize = size;
   }
template<typename T> int MqlArray< T >::size () inline
Definition at line 46 of file MqlArray.h.
References MqlArray< T >::fSize.
Referenced by MMuPC1AnalysisMQL(), MMuSCAnalysisMQL(), and MqlArray< T >::setSize().
                     {
     return fSize;
   }
template<typename T> void MqlArray< T >::sort (int(*)(const void *, const void *) compar) inline
Definition at line 86 of file MqlArray.h.
References MqlArray< T >::fArray, and MqlArray< T >::fSize.
Referenced by MMuPC1AnalysisMQL().
{
     qsort(fArray, fSize, sizeof(T), compar);
   }
template<typename T> void MqlArray< T >::toBank (void * pevent, char * bankName) inline
Definition at line 136 of file MqlArray.h.
References MqlArray< T >::fArray, and MqlArray< T >::fSize.
Referenced by MMuPC1AnalysisMQL().
{
     T *outputArray;
     bk_create(pevent, bankName, TID_DWORD, (DWORD*) &outputArray);
     memcpy(outputArray, fArray, fSize * sizeof(T));
     bk_close(pevent, outputArray + fSize);
   }
Field Documentation
template<typename T> int MqlArray< T >::fAllocation private
Definition at line 146 of file MqlArray.h.
Referenced by MqlArray< T >::finish(), MqlArray< T >::MqlArray(), MqlArray< T >::realloc(), and MqlArray< T >::setSize().
template<typename T> T* MqlArray< T >::fArray private
Definition at line 145 of file MqlArray.h.
Referenced by MqlArray< T >::finish(), MqlArray< T >::fromBank(), MqlArray< T >::MqlArray(), MqlArray< T >::operator[](), MqlArray< T >::realloc(), MqlArray< T >::sort(), MqlArray< T >::toBank(), and MqlArray< T >::~MqlArray().
template<typename T> bool MqlArray< T >::fImmutable private
Definition at line 149 of file MqlArray.h.
Referenced by MqlArray< T >::finish(), MqlArray< T >::fromBank(), MqlArray< T >::MqlArray(), MqlArray< T >::reset(), and MqlArray< T >::~MqlArray().
template<typename T> int MqlArray< T >::fLastSize private
Definition at line 148 of file MqlArray.h.
Referenced by MqlArray< T >::finish(), MqlArray< T >::MqlArray(), and MqlArray< T >::reset().
template<typename T> int MqlArray< T >::fSize private
Definition at line 147 of file MqlArray.h.
Referenced by MqlArray< T >::checkSort(), MqlArray< T >::finish(), MqlArray< T >::fromBank(), MqlArray< T >::MqlArray(), MqlArray< T >::next(), MqlArray< T >::realloc(), MqlArray< T >::reset(), MqlArray< T >::setSize(), MqlArray< T >::size(), MqlArray< T >::sort(), and MqlArray< T >::toBank().
The documentation for this class was generated from the following file:
analyzer/src/muSC_muPC/MqlArray.h