AlcapDAQ: TestModule Class Reference
TestModule Class Reference
#include <TestModule.h>
Public Member Functions
TestModule (modules::options *opts)
~TestModule ()
int ProcessGenericEntry (TGlobalData *gData, TSetupData *gSetup)
const char * GetName () const
Protected Member Functions
bool Debug () const
Protected Attributes
TDirectory * dir
TSetupData * fSetup
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, TSetupData *gSetup)
virtual int BeforeFirstEntry (TGlobalData *gData, TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, TSetupData *setup)
Private Attributes
int fXMax
Detailed Description
Definition at line 9 of file TestModule.h.
Constructor & Destructor Documentation
TestModule::TestModule (modules::options * opts)
Definition at line 11 of file TestModule.cpp.
References fXMax, and modules::options::GetDouble().
                                           :
    FillHistBase("TestModule",opts){
   // Do something with opts here.  Has the user specified any
   // particular configuration that you want to know?
   // For example, perhaps this module wants an axis range:
   fXMax=opts->GetDouble("x_max",100);
 }
TestModule::~TestModule ()
Definition at line 21 of file TestModule.cpp.
{
 }
Member Function Documentation
int TestModule::AfterLastEntry (TGlobalData * gData, TSetupData * setup) private virtual
Reimplemented from FillHistBase.
Definition at line 45 of file TestModule.cpp.
References FillHistBase::Debug().
{
   // Print extra info if we're debugging this module:
   if(Debug()){
      cout<<"-----I'm debugging TestModule::AfterLastEntry()"<<endl;
   }
   return 0;
 }
int TestModule::BeforeFirstEntry (TGlobalData * gData, TSetupData * setup) private virtual
Reimplemented from FillHistBase.
Definition at line 27 of file TestModule.cpp.
References FillHistBase::Debug().
{
   // Print extra info if we're debugging this module:
   if(Debug()){
      cout<<"-----I'm debugging TestModule::BeforeFirstEntry() "<<endl;
   }
   return 0;
 }
bool FillHistBase::Debug () const inline protected inherited
Definition at line 45 of file FillHistBase.h.
References FillHistBase::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), AfterLastEntry(), BeforeFirstEntry(), MakeMuonEvents::BeforeFirstEntry(), MakeDetectorPulses::MakeGenerator(), ExportPulse::MakePlot(), and MakeAnalysedPulses::ProcessEntry().
 {return fDebug;};
const char* FillHistBase::GetName () const inline inherited
Definition at line 40 of file FillHistBase.h.
References FillHistBase::dir.
Referenced by DeadTimeGe::ProcessEntry(), PlotTime::ProcessEntry(), and PlotAmplitude::ProcessEntry().
 {return dir->GetName();};
int TestModule::ProcessEntry (TGlobalData * gData, TSetupData * gSetup) private virtual
Reimplemented from FillHistBase.
Definition at line 38 of file TestModule.cpp.
{
   return 0;
 }
int FillHistBase::ProcessGenericEntry (TGlobalData * gData, TSetupData * gSetup) inherited
Definition at line 24 of file FillHistBase.cpp.
References FillHistBase::dir, and FillHistBase::ProcessEntry().
{
   // This is called by our main routine and would allow later to split into different
   // process routines if we have more than one Tree and hence different tpyes of data input.
   if(dir) dir->cd();
   int ret = ProcessEntry(gData, gSetup);
   gDirectory->cd("/");
   return ret;
 }
Field Documentation
TDirectory* FillHistBase::dir protected inherited
Definition at line 40 of file FillHistBase.h.
Referenced by DeadTimeGe::DeadTimeGe(), ExportPulse::ExportPulse(), FillHistBase::FillHistBase(), FillHistBase::GetName(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmplitude::PlotAmplitude(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTime::PlotTime(), and FillHistBase::ProcessGenericEntry().
TSetupData* FillHistBase::fSetup protected inherited
Definition at line 44 of file FillHistBase.h.
int TestModule::fXMax private
Definition at line 20 of file TestModule.h.
Referenced by TestModule().
The documentation for this class was generated from the following files:
analyzer/rootana/src/TestModule.h
analyzer/rootana/src/TestModule.cpp