AlcapDAQ: TTemplateConvolveAnalysedPulse Class Reference
TTemplateConvolveAnalysedPulse Class Reference
#include <TTemplateConvolveAnalysedPulse.h>
Public Types
typedef std::vector< double > SamplesVector
Public Member Functions
TTemplateConvolveAnalysedPulse ()
Needed by ROOT but not expected to be used.
TTemplateConvolveAnalysedPulse (const IDs::source &sourceID, const TPulseIslandID &parentID, const TPulseIsland *parentTPI)
Construct a TTemplateConvolveAnalysedPulse.
virtual ~TTemplateConvolveAnalysedPulse ()
virtual void Copy (TObject &rhs) const
virtual void Draw (const TH1F *tpi_pulse) const
@brief overload the TAnalysedPulse::Draw method
void Reset (Option_t *o="")
Clear the TAP. This will probably not be used.
Getters
double GetIntegralRatio () const
int GetNPeaks () const
int GetPeakRank () const
const TTemplate * GetTemplate () const
Setters
void SetNPeaks (int val)
void SetPeakRank (int val)
void SetTimeOffset (double val)
void SetAmplitudeScale (double val)
void SetIntegralRatio (double val)
void SetQuadraticFit (double a, double b, double c)
void SetEnergyConvolve (const SamplesVector &r)
void SetTimeConvolve (const SamplesVector &r)
void SetTemplate (TTemplate *val)
Getters
TPulseIslandID GetParentID () const
int GetTPILength () const
double GetAmplitude () const
double GetTime () const
double GetIntegral () const
double GetEnergy () const
double GetPedestal () const
double GetTriggerTime () const
const IDs::source & GetSource () const
Setters
The TAP generators will set whatever TAP values it must through these methods. Not all need be set; the default values are obviously unphysical and several Sanity methods are provided to check if a value was set later in the analysis.
void SetParentID (const TPulseIslandID &val)
void SetTPILength (const int &val)
void SetAmplitude (const double &val)
void SetTime (const double &val)
void SetIntegral (const double &val)
void SetEnergy (const double &val)
void SetPedestal (const double &val)
void SetTriggerTime (const double &val)
void SetParentTPIProperties (const TPulseIslandID &id, const TPulseIsland *parent)
Sanity
bool IsParentIDSet () const
bool IsTPILengthSet () const
bool IsAmplitudeSet () const
bool IsTimeSet () const
bool IsIntegralSet () const
bool IsEnergySet () const
bool IsPedestalSet () const
bool IsTriggerTimeSet () const
Private Member Functions
ClassDef (TTemplateConvolveAnalysedPulse, 2)
Private Attributes
int fNPeaks
int fPeakRank
double fIntegralRatio
double fQuad
double fLinear
double fConstant
double fTimeOffset
double fAmplitudeScale
TRef fTemplate
SamplesVector fEnergySamples
SamplesVector fTimeSamples
Detailed Description
Definition at line 13 of file TTemplateConvolveAnalysedPulse.h.
Member Typedef Documentation
typedef std::vector<double> TTemplateConvolveAnalysedPulse::SamplesVector
Definition at line 16 of file TTemplateConvolveAnalysedPulse.h.
Constructor & Destructor Documentation
TTemplateConvolveAnalysedPulse::TTemplateConvolveAnalysedPulse ()
Needed by ROOT but not expected to be used.
Definition at line 10 of file TTemplateConvolveAnalysedPulse.cpp.
                                                              :TAnalysedPulse(),
      fNPeaks(0), fPeakRank(0), fIntegralRatio(0){}
TTemplateConvolveAnalysedPulse::TTemplateConvolveAnalysedPulse (const IDs::source & sourceID, const TPulseIslandID & parentID, const TPulseIsland * parentTPI)
Construct a TTemplateConvolveAnalysedPulse.
Same signature as for TAnalysedPulse so that MakeNewTAP can create these specialised TAPs
Definition at line 13 of file TTemplateConvolveAnalysedPulse.cpp.
                                                                                                :
            TAnalysedPulse(sourceID,parentID,parentTPI),
      fNPeaks(0), fPeakRank(0), fIntegralRatio(0)
{}
TTemplateConvolveAnalysedPulse::~TTemplateConvolveAnalysedPulse () [virtual]
Definition at line 19 of file TTemplateConvolveAnalysedPulse.cpp.
{
}
Member Function Documentation
TTemplateConvolveAnalysedPulse::ClassDef (TTemplateConvolveAnalysedPulse , 2) [private]
virtual void TTemplateConvolveAnalysedPulse::Copy (TObject & rhs) const [inline, virtual]
Reimplemented from TAnalysedPulse.
Definition at line 31 of file TTemplateConvolveAnalysedPulse.h.
References fAmplitudeScale, fConstant, fIntegralRatio, fLinear, fNPeaks, fPeakRank, fQuad, and fTimeOffset.
{
         TAnalysedPulse::Copy(rhs);
         if(rhs.InheritsFrom(Class())){
           TTemplateConvolveAnalysedPulse* tap=static_cast<TTemplateConvolveAnalysedPulse*>(&rhs);
            tap->fNPeaks       =fNPeaks;
            tap->fPeakRank     =fPeakRank;
            tap->fIntegralRatio=fIntegralRatio;
            tap->fQuad=fQuad;
            tap->fLinear=fLinear;
            tap->fConstant=fConstant;
            tap->fTimeOffset=fTimeOffset;
            tap->fAmplitudeScale=fAmplitudeScale;
         }
      }
void TTemplateConvolveAnalysedPulse::Draw (const TH1F * tpi_pulse) const [virtual]
@brief overload the TAnalysedPulse::Draw method
make the energy (template convolution) waveform
make the time (second derivative of the energy) waveform
Reimplemented from TAnalysedPulse.
Definition at line 22 of file TTemplateConvolveAnalysedPulse.cpp.
References fAmplitudeScale, fConstant, fEnergySamples, fLinear, fQuad, fTimeOffset, fTimeSamples, TAnalysedPulse::GetAmplitude(), TAnalysedPulse::GetPedestal(), SetupRecord::GetPolarity(), EventNavigator::GetSetupRecord(), TAnalysedPulse::GetSource(), TAnalysedPulse::GetTime(), and functions::VectorToHist().
{
   // make sure theres a TPI
   if(!tpi_pulse) return;
   std::string name(tpi_pulse->GetName());
   TH1F* energy_hist=functions::VectorToHist(fEnergySamples,name+"_energy","Convolution with template");
   TH1F* time_hist=functions::VectorToHist(fTimeSamples,name+"_time","First derivative of convolution with template");
   //TMarker* marker=new TMarker(GetTime(), GetAmplitude()+10, 23);
   int polarity=EventNavigator::GetSetupRecord().GetPolarity(GetSource().Channel());
   double bottom= GetPedestal() - (polarity>0?0:GetAmplitude());
   double top= GetPedestal() + (polarity>0?GetAmplitude():0);
   TLine* line=new TLine(GetTime(), bottom, GetTime(), top);
   line->SetLineColor(kRed);
   tpi_pulse->GetListOfFunctions()->Add(line->Clone());
   line->SetX1(fTimeOffset);
   line->SetX2(fTimeOffset);
   line->SetY1(0);
   line->SetY2(fAmplitudeScale);
   energy_hist->GetListOfFunctions()->Add(line);
   time_hist->GetListOfFunctions()->Add(line->Clone());
   TPaveText* text_b=new TPaveText(0.7,0.60,0.9,0.9,"NB NDC");
   text_b->AddText(Form("A = %g",GetAmplitude()));
   text_b->AddText(Form("t = %g",GetTime()));
   text_b->AddText(Form("a = %g",fQuad));
   text_b->AddText(Form("b = %g",fLinear));
   text_b->AddText(Form("c = %g",fConstant));
   text_b->SetFillColor(kWhite);
   text_b->SetBorderSize(1);
   energy_hist->GetListOfFunctions()->Add(text_b);
   TF1* fit=new TF1("Fit","[0]*(x-[3])**2+[1]*(x-[3])+[2]", 0 , energy_hist->GetNbinsX());
   fit->SetParameter(0,fQuad);
   fit->SetParameter(1,fLinear);
   fit->SetParameter(2,fConstant);
   fit->SetParameter(3,fTimeOffset );
   energy_hist->GetListOfFunctions()->Add(fit);
   energy_hist->Write();
   time_hist->Write();
   //tap_pulse->Write();
}
double TAnalysedPulse::GetAmplitude () const [inline, inherited]
Definition at line 100 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude.
Referenced by TTemplateFitAnalysedPulse::Draw(), Draw(), TGaussFitAnalysedPulse::Draw(), TTemplateFitAnalysedPulse::GetBinContent(), PulseViewer::GetParameterValue(), PlotTAP_selfCorrelation::PassesCutA(), TemplateFitAPGenerator::RefitWithTwo(), and TTemplateFitAnalysedPulse::SetAmplitudeScaleFactor().
{return fAmplitude;};
double TAnalysedPulse::GetEnergy () const [inline, inherited]
Definition at line 103 of file TAnalysedPulse.h.
References TAnalysedPulse::fEnergy.
Referenced by PulseViewer::GetParameterValue(), and TME_Al50_EvdE::ProcessEntry().
{return fEnergy;};
double TAnalysedPulse::GetIntegral () const [inline, inherited]
Definition at line 102 of file TAnalysedPulse.h.
References TAnalysedPulse::fIntegral.
Referenced by PulseViewer::GetParameterValue(), and PlotIntegralRatios::ProcessEntry().
{return fIntegral;};
double TTemplateConvolveAnalysedPulse::GetIntegralRatio () const [inline]
Definition at line 48 of file TTemplateConvolveAnalysedPulse.h.
References fIntegralRatio.
Referenced by PulseViewer::GetParameterValue().
{return fIntegralRatio;}
int TTemplateConvolveAnalysedPulse::GetNPeaks () const [inline]
Definition at line 49 of file TTemplateConvolveAnalysedPulse.h.
References fNPeaks.
Referenced by PulseViewer::GetParameterValue().
{return fNPeaks;}
TPulseIslandID TAnalysedPulse::GetParentID () const [inline, inherited]
Definition at line 98 of file TAnalysedPulse.h.
References TAnalysedPulse::fParentID.
Referenced by ExportPulse::AddToExportList(), TTemplateFitAnalysedPulse::GetHisto(), and TemplateFitAPGenerator::RefitWithTwo().
{return fParentID;};
int TTemplateConvolveAnalysedPulse::GetPeakRank () const [inline]
Definition at line 50 of file TTemplateConvolveAnalysedPulse.h.
References fPeakRank.
Referenced by PulseViewer::GetParameterValue().
{return fPeakRank;}
double TAnalysedPulse::GetPedestal () const [inline, inherited]
Definition at line 104 of file TAnalysedPulse.h.
References TAnalysedPulse::fPedestal.
Referenced by Draw(), TGaussFitAnalysedPulse::Draw(), TTemplateFitAnalysedPulse::GetBinContent(), PulseViewer::GetParameterValue(), and TemplateFitAPGenerator::RefitWithTwo().
{return fPedestal;};
const IDs::source& TAnalysedPulse::GetSource () const [inline, inherited]
Definition at line 106 of file TAnalysedPulse.h.
References TAnalysedPulse::fSource, and FlyWeight< ValueType, UniqueTag >::GetValue().
Referenced by ExportPulse::AddToExportList(), Draw(), TTemplateFitAnalysedPulse::GetHisto(), MaxTimeDiffDPGenerator::ProcessPulses(), and TDetectorPulse::TDetectorPulse().
{return fSource.GetValue();};
const TTemplate* TTemplateConvolveAnalysedPulse::GetTemplate () const [inline]
Definition at line 51 of file TTemplateConvolveAnalysedPulse.h.
References fTemplate.
{return (const TTemplate*) fTemplate.GetObject();}
double TAnalysedPulse::GetTime () const [inline, inherited]
Definition at line 101 of file TAnalysedPulse.h.
References TAnalysedPulse::fTime.
Referenced by TTemplateFitAnalysedPulse::Draw(), Draw(), TGaussFitAnalysedPulse::Draw(), TTemplateFitAnalysedPulse::GetBinContent(), PulseViewer::GetParameterValue(), TemplateFitAPGenerator::InitializeSecondPulse(), IsTimeOrdered(), MaxTimeDiffDPGenerator::ProcessPulses(), TemplateFitAPGenerator::RefitWithTwo(), and TTemplateFitAnalysedPulse::SetTimeOffset().
{return fTime;};
int TAnalysedPulse::GetTPILength () const [inline, inherited]
Definition at line 99 of file TAnalysedPulse.h.
References TAnalysedPulse::fTPILength.
Referenced by TTemplateFitAnalysedPulse::GetHisto(), and PulseViewer::GetParameterValue().
{return fTPILength;};
double TAnalysedPulse::GetTriggerTime () const [inline, inherited]
Definition at line 105 of file TAnalysedPulse.h.
References TAnalysedPulse::fTriggerTime.
Referenced by PulseViewer::GetParameterValue().
{return fTriggerTime;};
bool TAnalysedPulse::IsAmplitudeSet () const [inline, inherited]
Definition at line 135 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude, and TAnalysedPulse::fDefaultValue.
{return fAmplitude!=fDefaultValue;};
bool TAnalysedPulse::IsEnergySet () const [inline, inherited]
Definition at line 138 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fEnergy.
{return fEnergy!=fDefaultValue;};
bool TAnalysedPulse::IsIntegralSet () const [inline, inherited]
Definition at line 137 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fIntegral.
{return fIntegral!=fDefaultValue;};
bool TAnalysedPulse::IsParentIDSet () const [inline, inherited]
Definition at line 133 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fParentID.
{return fParentID!=fDefaultValue;};
bool TAnalysedPulse::IsPedestalSet () const [inline, inherited]
Definition at line 139 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fPedestal.
{return fPedestal!=fDefaultValue;};
bool TAnalysedPulse::IsTimeSet () const [inline, inherited]
Definition at line 136 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTime.
{return fTime!=fDefaultValue;};
bool TAnalysedPulse::IsTPILengthSet () const [inline, inherited]
Definition at line 134 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTPILength.
{return fTPILength!=fDefaultValue;};
bool TAnalysedPulse::IsTriggerTimeSet () const [inline, inherited]
Definition at line 140 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTriggerTime.
{return fTriggerTime!=fDefaultValue;};
void TAnalysedPulse::Reset (Option_t * o = "") [inherited]
Clear the TAP. This will probably not be used.
Definition at line 42 of file TAnalysedPulse.cpp.
References TAnalysedPulse::fAmplitude, TAnalysedPulse::fDefaultValue, TAnalysedPulse::fEnergy, TAnalysedPulse::fIntegral, TAnalysedPulse::fParentID, TAnalysedPulse::fPedestal, TAnalysedPulse::fTime, TAnalysedPulse::fTPILength, and TAnalysedPulse::fTriggerTime.
{
  fParentID=fDefaultValue;
  fTPILength=fDefaultValue;
  fAmplitude=fDefaultValue;
  fTime=fDefaultValue;
  fIntegral=fDefaultValue;
  fEnergy=fDefaultValue;
  fPedestal=fDefaultValue;
  fTriggerTime=fDefaultValue;
}
void TAnalysedPulse::SetAmplitude (const double & val) [inline, inherited]
Definition at line 120 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateConvolveAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), IntegralRatioAPGenerator::ProcessPulses(), and CFTimeMBAmpAPGenerator::ProcessPulses().
{ fAmplitude=val;};
void TTemplateConvolveAnalysedPulse::SetAmplitudeScale (double val) [inline]
Definition at line 59 of file TTemplateConvolveAnalysedPulse.h.
References fAmplitudeScale.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{ fAmplitudeScale=val; }
void TAnalysedPulse::SetEnergy (const double & val) [inline, inherited]
Definition at line 123 of file TAnalysedPulse.h.
References TAnalysedPulse::fEnergy.
{ fEnergy=val;};
void TTemplateConvolveAnalysedPulse::SetEnergyConvolve (const SamplesVector & r) [inline]
Definition at line 62 of file TTemplateConvolveAnalysedPulse.h.
References fEnergySamples.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{fEnergySamples=r;};
void TAnalysedPulse::SetIntegral (const double & val) [inline, inherited]
Definition at line 122 of file TAnalysedPulse.h.
References TAnalysedPulse::fIntegral.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateFitAPGenerator::ProcessPulses(), TemplateConvolveAPGenerator::ProcessPulses(), SimpIntAPGenerator::ProcessPulses(), and IntegralRatioAPGenerator::ProcessPulses().
{ fIntegral=val;};
void TTemplateConvolveAnalysedPulse::SetIntegralRatio (double val) [inline]
Definition at line 60 of file TTemplateConvolveAnalysedPulse.h.
References fIntegralRatio.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{fIntegralRatio=val;}
void TTemplateConvolveAnalysedPulse::SetNPeaks (int val) [inline]
Definition at line 56 of file TTemplateConvolveAnalysedPulse.h.
References fNPeaks.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{fNPeaks=val;}
void TAnalysedPulse::SetParentID (const TPulseIslandID & val) [inline, inherited]
Definition at line 118 of file TAnalysedPulse.h.
References TAnalysedPulse::fParentID.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fParentID=val;};
void TAnalysedPulse::SetParentTPIProperties (const TPulseIslandID & id, const TPulseIsland * parent) [inherited]
Definition at line 65 of file TAnalysedPulse.cpp.
References TPulseIsland::GetClockTickInNs(), TPulseIsland::GetPulseLength(), TPulseIsland::GetTimeStamp(), TAnalysedPulse::SetParentID(), TAnalysedPulse::SetTPILength(), and TAnalysedPulse::SetTriggerTime().
Referenced by TAnalysedPulse::TAnalysedPulse().
{
  SetParentID(id);
  if(!pulse) {
    std::cerr<<"NULL pointer to TPulseIsland passed as parent for TAnalysedPulse."<<std::endl;
    return;
  }
  SetTPILength(pulse->GetPulseLength());
  SetTriggerTime(pulse->GetTimeStamp()*pulse->GetClockTickInNs());
}
void TTemplateConvolveAnalysedPulse::SetPeakRank (int val) [inline]
Definition at line 57 of file TTemplateConvolveAnalysedPulse.h.
References fPeakRank.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{ fPeakRank=val; }
void TAnalysedPulse::SetPedestal (const double & val) [inline, inherited]
Definition at line 124 of file TAnalysedPulse.h.
References TAnalysedPulse::fPedestal.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{ fPedestal=val;};
void TTemplateConvolveAnalysedPulse::SetQuadraticFit (double a, double b, double c) [inline]
Definition at line 61 of file TTemplateConvolveAnalysedPulse.h.
References fConstant, fLinear, and fQuad.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{fQuad=a; fLinear=b; fConstant=c;};
void TTemplateConvolveAnalysedPulse::SetTemplate (TTemplate * val) [inline]
Definition at line 64 of file TTemplateConvolveAnalysedPulse.h.
References fTemplate.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{fTemplate=val;}
void TAnalysedPulse::SetTime (const double & val) [inline, inherited]
Definition at line 121 of file TAnalysedPulse.h.
References TAnalysedPulse::fTime.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateConvolveAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), IntegralRatioAPGenerator::ProcessPulses(), CFTimeMBAmpAPGenerator::ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{ fTime=val;};
void TTemplateConvolveAnalysedPulse::SetTimeConvolve (const SamplesVector & r) [inline]
Definition at line 63 of file TTemplateConvolveAnalysedPulse.h.
References fTimeSamples.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{fTimeSamples=r;};
void TTemplateConvolveAnalysedPulse::SetTimeOffset (double val) [inline]
Definition at line 58 of file TTemplateConvolveAnalysedPulse.h.
References fTimeOffset.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{ fTimeOffset=val; }
void TAnalysedPulse::SetTPILength (const int & val) [inline, inherited]
Definition at line 119 of file TAnalysedPulse.h.
References TAnalysedPulse::fTPILength.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fTPILength=val;};
void TAnalysedPulse::SetTriggerTime (const double & val) [inline, inherited]
Definition at line 125 of file TAnalysedPulse.h.
References TAnalysedPulse::fTriggerTime.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fTriggerTime=val;};
Member Data Documentation
double TTemplateConvolveAnalysedPulse::fAmplitudeScale [private]
Definition at line 75 of file TTemplateConvolveAnalysedPulse.h.
Referenced by Copy(), Draw(), and SetAmplitudeScale().
double TTemplateConvolveAnalysedPulse::fConstant [private]
Definition at line 74 of file TTemplateConvolveAnalysedPulse.h.
Referenced by Copy(), Draw(), and SetQuadraticFit().
SamplesVector TTemplateConvolveAnalysedPulse::fEnergySamples [private]
Definition at line 77 of file TTemplateConvolveAnalysedPulse.h.
Referenced by Draw(), and SetEnergyConvolve().
double TTemplateConvolveAnalysedPulse::fIntegralRatio [private]
Definition at line 73 of file TTemplateConvolveAnalysedPulse.h.
Referenced by Copy(), GetIntegralRatio(), and SetIntegralRatio().
double TTemplateConvolveAnalysedPulse::fLinear [private]
Definition at line 74 of file TTemplateConvolveAnalysedPulse.h.
Referenced by Copy(), Draw(), and SetQuadraticFit().
int TTemplateConvolveAnalysedPulse::fNPeaks [private]
Definition at line 71 of file TTemplateConvolveAnalysedPulse.h.
Referenced by Copy(), GetNPeaks(), and SetNPeaks().
int TTemplateConvolveAnalysedPulse::fPeakRank [private]
Definition at line 72 of file TTemplateConvolveAnalysedPulse.h.
Referenced by Copy(), GetPeakRank(), and SetPeakRank().
double TTemplateConvolveAnalysedPulse::fQuad [private]
Definition at line 74 of file TTemplateConvolveAnalysedPulse.h.
Referenced by Copy(), Draw(), and SetQuadraticFit().
TRef TTemplateConvolveAnalysedPulse::fTemplate [private]
Definition at line 76 of file TTemplateConvolveAnalysedPulse.h.
Referenced by GetTemplate(), and SetTemplate().
double TTemplateConvolveAnalysedPulse::fTimeOffset [private]
Definition at line 75 of file TTemplateConvolveAnalysedPulse.h.
Referenced by Copy(), Draw(), and SetTimeOffset().
SamplesVector TTemplateConvolveAnalysedPulse::fTimeSamples [private]
Definition at line 78 of file TTemplateConvolveAnalysedPulse.h.
Referenced by Draw(), and SetTimeConvolve().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/TTemplateConvolveAnalysedPulse.h
rootana/src/TAP_generators/TTemplateConvolveAnalysedPulse.cpp