AlcapDAQ: SetupNavigator Class Reference
SetupNavigator Class Reference
#include <SetupNavigator.h>
Public Member Functions
void Close ()
void SetCommandLineArgs (const ARGUMENTS &args)
Closes the database if this is a calibration run.
int GetRunNumber () const
std::string GetBank (const IDs::channel &) const
void CacheCalibDB ()
Caches the information stored in the calib DB.
double GetPedestal (const IDs::channel &channel) const
Gets the pedestal from the SQLite database.
double GetNoise (const IDs::channel &channel) const
Gets the error on the pedestal from the SQLite database.
double GetCoarseTimeOffset (IDs::source src) const
std::pair< double, double > GetEnergyCalibrationConstants (const IDs::channel &) const
Gets the energy calibration constants.
double GetAdcToEnergyGain (const IDs::channel &ch) const
double GetAdcToEnergyConstant (const IDs::channel &ch) const
void SetPedestalAndNoise (const IDs::channel &channel, double pedestal, double noise)
void SetCoarseTimeOffset (const IDs::source &src, double dt)
Static Public Member Functions
static SetupNavigator * Instance ()
Private Types
typedef std::pair< double, double > EnergyCalibRow_t
The map that stores energy calibration constants as <Gain,Pedestal> pairs.
Private Member Functions
SetupNavigator ()
~SetupNavigator ()
Closes the database if open or saves.
bool ReadPedestalAndNoiseValues ()
Reads the pedestal and pedestal error values.
bool ReadCoarseTimeOffsetValues ()
Reads the gross time offset values.
std::vector< std::string > GetCoarseTimeOffsetColumns ()
Read in gross time offset columns determining what TAP generators we're ready for.
bool ReadEnergyCalibrationConstants ()
Read in energy calibration constants.
void OutputCalibCSV ()
bool IsCalibRun () const
Private Attributes
ARGUMENTS fCommandLineArgs
const std::string fSQLiteFilename
The SQLite filename, the SQLite server object and the current table name.
TSQLiteServer * fServer
const std::string fPedestalNoiseTableName
const std::string fCoarseTimeOffsetTableName
const std::string fEnergyCalibrationConstantsTableName
Static Private Attributes
static SetupNavigator * fThis = NULL
static std::map< IDs::channel,
double > fPedestalValues
The map that stores the pedestal values that we get from the SQLite database.
static std::map< IDs::channel,
double > fNoiseValues
The map that stores the pedestal error values (i.e. noise) that we get from the SQLite database.
static std::map< IDs::source,
double > fCoarseTimeOffset
The map that stores the gross time offset values from SQLite database.
static std::map< IDs::channel,
EnergyCalibRow_t > fEnergyCalibrationConstants
Detailed Description
Definition at line 21 of file SetupNavigator.h.
Member Typedef Documentation
typedef std::pair<double,double> SetupNavigator::EnergyCalibRow_t [private]
The map that stores energy calibration constants as <Gain,Pedestal> pairs.
Definition at line 100 of file SetupNavigator.h.
Constructor & Destructor Documentation
SetupNavigator::SetupNavigator () [private]
Definition at line 37 of file SetupNavigator.cpp.
References fServer.
Referenced by Instance().
                               :
  fCommandLineArgs(),
  fSQLiteFilename("sqlite://calibration.db"), fServer(new TSQLiteServer(fSQLiteFilename.c_str())),
  fPedestalNoiseTableName("PedestalAndNoise"), fCoarseTimeOffsetTableName("CoarseTimeOffset"),
  fEnergyCalibrationConstantsTableName("Energy") {
  if (fServer->IsZombie()) {
    std::cout << "SetupNavigator: ERROR: Couldn't connect to SQLite database." << std::endl;
    throw Except::NoCalibDB();
  }
}
SetupNavigator::~SetupNavigator () [private]
Closes the database if open or saves.
Definition at line 49 of file SetupNavigator.cpp.
{
}
Member Function Documentation
void SetupNavigator::CacheCalibDB ()
Caches the information stored in the calib DB.
Definition at line 73 of file SetupNavigator.cpp.
References fCoarseTimeOffsetTableName, fEnergyCalibrationConstantsTableName, fPedestalNoiseTableName, fServer, GetRunNumber(), IsCalibRun(), ReadCoarseTimeOffsetValues(), ReadEnergyCalibrationConstants(), and ReadPedestalAndNoiseValues().
Referenced by main().
{
  // Cache all the variables we have in the database
  // First the pedestals and noises
  if (!fServer->HasTable(fPedestalNoiseTableName.c_str())) {
    std::cout << "SetupNavigator: ERROR: Table " << fPedestalNoiseTableName << " does not exist." << std::endl;
    if (!IsCalibRun()) throw Except::MissingTable(fPedestalNoiseTableName.c_str());
  } else {
    if (!ReadPedestalAndNoiseValues()) {
      std::cout << "SetupNavigator: ERROR: Table " << fPedestalNoiseTableName
                << " contains no calib data for this run ("<<GetRunNumber()<<")" << std::endl;
    if (!IsCalibRun()) throw Except::UncalibratedRun();
    }
  }
  if (!fServer->HasTable(fCoarseTimeOffsetTableName.c_str())) {
    std::cout << "SetupNavigator: ERROR: Table " << fCoarseTimeOffsetTableName << " does not exist." << std::endl;
    if(!IsCalibRun()) throw Except::MissingTable(fPedestalNoiseTableName.c_str());
  } else {
    if (!ReadCoarseTimeOffsetValues()) {
      std::cout << "SetupNavigator: ERROR: Table " << fCoarseTimeOffsetTableName
                << " contains no calib data for this run ("<<GetRunNumber()<<")" << std::endl;
    if (!IsCalibRun()) throw Except::UncalibratedRun();
    }
  }
  if (!fServer->HasTable(fEnergyCalibrationConstantsTableName.c_str())) {
    std::cout << "SetupNavigator: Error: Table " << fEnergyCalibrationConstantsTableName << " does not exist." << std::endl;
    if (!IsCalibRun()) throw Except::MissingTable(fEnergyCalibrationConstantsTableName.c_str());
  } else {
    if (!ReadEnergyCalibrationConstants()) {
      std::cout << "SetupNavigator: ERROR: Table " << fEnergyCalibrationConstantsTableName
                << " contains no calib data for this run ("<<GetRunNumber()<<")" << std::endl;
      if (!IsCalibRun()) throw Except::UncalibratedRun();
    }
  }
}
void SetupNavigator::Close ()
Definition at line 53 of file SetupNavigator.cpp.
References fServer, fThis, IsCalibRun(), and OutputCalibCSV().
Referenced by Finish().
{
  if(IsCalibRun())
    OutputCalibCSV();
  fServer->Close();
  if (fThis)
    delete fThis;
  fThis = NULL;
}
double SetupNavigator::GetAdcToEnergyConstant (const IDs::channel & ch) const [inline]
Definition at line 54 of file SetupNavigator.h.
Referenced by PlotTAP_Energy::ProcessEntry(), and TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{return GetEnergyCalibrationConstants(ch).second;}
double SetupNavigator::GetAdcToEnergyGain (const IDs::channel & ch) const [inline]
Definition at line 53 of file SetupNavigator.h.
Referenced by PlotTAP_Energy::ProcessEntry(), and TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{return GetEnergyCalibrationConstants(ch).first;}
std::string SetupNavigator::GetBank (const IDs::channel & src) const
Definition at line 63 of file SetupNavigator.cpp.
References modules::parser::iequals(), Instance(), and IDs::channel::str().
Referenced by TVAnalysedPulseGenerator::SetChannel().
{
  std::map<std::string, std::string>* bankDetNameMap=&TSetupData::Instance()->fBankToDetectorMap;
  for(std::map<std::string, std::string>::iterator it = bankDetNameMap->begin();
      it != bankDetNameMap->end(); ++it){
    if(modules::parser::iequals(it->second , src.str())) return it->first;
  }
  std::cout << "Invalid detector name: " << src.str() << std::endl;
  throw Except::InvalidDetector();
}
double SetupNavigator::GetCoarseTimeOffset (IDs::source src) const
Definition at line 262 of file SetupNavigator.cpp.
References fCoarseTimeOffset, IDs::source::Generator(), IDs::source::matches(), and IDs::source::str().
{
// Massive hack to remove config strings that specify other options.  Assumes
// the timing option is placed first for the generator
 std::string conf=source.Generator().Config();
 unsigned curly_br=conf.find('}');
if(curly_br!=std::string::npos){ source.Generator().Config(conf.substr(0,curly_br+1));}
 return source.matches(IDs::channel("muSc")) ? 0. : alcap::at<Except::InvalidDetector>(fCoarseTimeOffset,source,source.str().c_str());
 }
std::vector< std::string > SetupNavigator::GetCoarseTimeOffsetColumns () [private]
Read in gross time offset columns determining what TAP generators we're ready for.
Definition at line 164 of file SetupNavigator.cpp.
References fCoarseTimeOffsetTableName, and fServer.
Referenced by ReadCoarseTimeOffsetValues().
{
  std::vector<std::string> cols;
  std::stringstream cmd;
  cmd << "PRAGMA table_info(" << fCoarseTimeOffsetTableName << ")";
  TSQLResult* res = fServer->Query(cmd.str().c_str());
  TSQLRow* row;
  while ((row = res->Next())) {
    if (row->GetField(1) != std::string("run") && row->GetField(1) != std::string("channel"))
      cols.push_back(std::string(row->GetField(1)));
    delete row;
  }
  delete res;
  return cols;
}
SetupNavigator::EnergyCalibRow_t SetupNavigator::GetEnergyCalibrationConstants (const IDs::channel & ch) const
Gets the energy calibration constants.
Definition at line 259 of file SetupNavigator.cpp.
References fEnergyCalibrationConstants, and IDs::channel::str().
Referenced by GeSpectrum::GeSpectrum().
{
  return alcap::at<Except::InvalidDetector>(fEnergyCalibrationConstants, ch, ch.str().c_str());
}
double SetupNavigator::GetNoise (const IDs::channel & channel) const
Gets the error on the pedestal from the SQLite database.
Definition at line 252 of file SetupNavigator.cpp.
References fNoiseValues, and IDs::channel::str().
Referenced by functions::InterpolatePulse(), and PulseCandidateFinder::SetChannel().
{
  return alcap::at<Except::InvalidDetector>(fNoiseValues,channel,channel.str().c_str());
}
double SetupNavigator::GetPedestal (const IDs::channel & channel) const
Gets the pedestal from the SQLite database.
Definition at line 255 of file SetupNavigator.cpp.
References fPedestalValues, and IDs::channel::str().
Referenced by PulseCandidateFinder::SetChannel().
{
  return alcap::at<Except::InvalidDetector>(fPedestalValues,channel,channel.str().c_str());
}
int SetupNavigator::GetRunNumber () const [inline]
Definition at line 35 of file SetupNavigator.h.
Referenced by CacheCalibDB(), PulseCandidateFinder::FillParameterHistogram(), OutputCalibCSV(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), ReadCoarseTimeOffsetValues(), ReadEnergyCalibrationConstants(), and ReadPedestalAndNoiseValues().
{return fCommandLineArgs.run;};
SetupNavigator * SetupNavigator::Instance () [inline, static]
Definition at line 105 of file SetupNavigator.h.
References fThis, and SetupNavigator().
Referenced by PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTAP_TDiff::AfterLastEntry(), CalcCoarseTimeOffset::AfterLastEntry(), PlotTDPs::BeforeFirstEntry(), PulseCandidateFinder::FillParameterHistogram(), Finish(), GeSpectrum::GeSpectrum(), GetBank(), PlotAmpVsMuScTDiff::GetHistogram(), functions::InterpolatePulse(), main(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), PulseCandidateFinder::SetChannel(), TVAnalysedPulseGenerator::SetChannel(), and TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{
  if(!fThis) fThis=new SetupNavigator();
  return fThis;
}
bool SetupNavigator::IsCalibRun () const [inline, private]
Definition at line 75 of file SetupNavigator.h.
Referenced by CacheCalibDB(), Close(), SetCoarseTimeOffset(), and SetPedestalAndNoise().
{return fCommandLineArgs.calib;}
void SetupNavigator::OutputCalibCSV () [private]
Definition at line 200 of file SetupNavigator.cpp.
References fCoarseTimeOffset, fCoarseTimeOffsetTableName, fNoiseValues, fPedestalNoiseTableName, fPedestalValues, and GetRunNumber().
Referenced by Close().
{
  char r[6];
  sprintf(r, "%05d", GetRunNumber());
  std::ofstream fPN((std::string("calib.run") + r + "." + fPedestalNoiseTableName + ".csv").c_str());
  fPN << "run,channel,pedestal,noise" << std::endl;
  for (std::map<IDs::channel, double>::const_iterator i = fPedestalValues.begin(); i != fPedestalValues.end(); ++i)
    fPN << GetRunNumber() << "," << i->first.str() << ","
        << i->second << "," << fNoiseValues.at(i->first) << std::endl;
  std::ofstream fTO((std::string("calib.run") + r + "." + fCoarseTimeOffsetTableName + ".csv").c_str());
  std::set<IDs::generator> gens;
  std::set<IDs::channel> chns;
  for (std::map<IDs::source, double>::const_iterator i = fCoarseTimeOffset.begin(); i != fCoarseTimeOffset.end(); ++i) {
    gens.insert(i->first.Generator());
    chns.insert(i->first.Channel());
  }
  fTO << "run,channel";
  for (std::set<IDs::generator>::const_iterator i = gens.begin(); i != gens.end(); ++i)
    fTO << "," << i->str();
  fTO << std::endl;
  for (std::set<IDs::channel>::const_iterator i = chns.begin(); i != chns.end(); ++i) {
    fTO << GetRunNumber() << "," << i->str();
    for (std::set<IDs::generator>::const_iterator j = gens.begin(); j != gens.end(); ++j) {
      fTO << ",";
      if (fCoarseTimeOffset.count(IDs::source(*i, *j)))
        fTO << fCoarseTimeOffset.at(IDs::source(*i, *j));
    }
    fTO << std::endl;
  }
}
bool SetupNavigator::ReadCoarseTimeOffsetValues () [private]
Reads the gross time offset values.
Definition at line 138 of file SetupNavigator.cpp.
References DEBUG_VALUE, fCoarseTimeOffset, fCoarseTimeOffsetTableName, IDs::field_separator, fServer, GetCoarseTimeOffsetColumns(), and GetRunNumber().
Referenced by CacheCalibDB().
{
  // The values that we will read in
  const std::vector<std::string> table = GetCoarseTimeOffsetColumns();
for(unsigned i=0;i<table.size();++i) DEBUG_VALUE(i, table[i]);
  std::stringstream query;
  query << "SELECT channel";
  for (unsigned int i = 0; i < table.size(); ++i)
    query << ",\"" << table[i] << '"';
  query << " FROM " << fCoarseTimeOffsetTableName << " WHERE run==" << GetRunNumber();
  TSQLResult* res = fServer->Query(query.str().c_str());
  TSQLRow* row;
  while ((row = res->Next())) {
    for (unsigned int i = 0; i < table.size(); ++i) {
      std::stringstream srcstr;
      srcstr << row->GetField(0) << IDs::field_separator << table[i];
      if(row->GetField(1+i))
             fCoarseTimeOffset[IDs::source(srcstr.str())] = atof(row->GetField(1 + i));
    }
    delete row;
  }
  delete res;
  return !fCoarseTimeOffset.empty();
}
bool SetupNavigator::ReadEnergyCalibrationConstants () [private]
Read in energy calibration constants.
Definition at line 180 of file SetupNavigator.cpp.
References fEnergyCalibrationConstants, fEnergyCalibrationConstantsTableName, fServer, and GetRunNumber().
Referenced by CacheCalibDB().
{
  std::stringstream cmd;
  // // Ben:  In the future we will want to include generator parameters in the
  // // table to be able to calibrate multiple generators simultaneously:
  // cmd << "SELECT channel,gen_params,gain,offset FROM " << fEnergyCalibrationConstantsTableName
  cmd << "SELECT channel,gain,offset FROM " << fEnergyCalibrationConstantsTableName
      << " WHERE run==" << GetRunNumber();
  TSQLResult* res = fServer->Query(cmd.str().c_str());
  TSQLRow* row;
  while ((row = res->Next())) {
    fEnergyCalibrationConstants[IDs::channel(row->GetField(0))] =
      EnergyCalibRow_t(atof(row->GetField(1)), atof(row->GetField(2)));
    delete row;
  }
  delete res;
  //  return !fEnergyCalibrationConstants.empty();
  return true; // Right now there's no reason this should be filled for anything
}
bool SetupNavigator::ReadPedestalAndNoiseValues () [private]
Reads the pedestal and pedestal error values.
Definition at line 108 of file SetupNavigator.cpp.
References definitions::DefaultValue, fNoiseValues, fPedestalNoiseTableName, fPedestalValues, fServer, and GetRunNumber().
Referenced by CacheCalibDB().
{
  // The values that we will read in
  double pedestal=definitions::DefaultValue;
  double noise=definitions::DefaultValue;
  std::string channelname;
  std::stringstream query;
  int run_number = GetRunNumber(); // get this run number (Note that if we don't have a catalogue of pedestals and noises for each run then we will want to change this)
  query << "SELECT * FROM " << fPedestalNoiseTableName << " WHERE run=" << run_number << ";"; // get all the pedestals and noises
  TSQLiteResult* result = (TSQLiteResult*) fServer->Query(query.str().c_str());  // get the result of this query
  query.str(""); // clear the stringstream after use
  TSQLiteRow* row = (TSQLiteRow*) result->Next(); // get the first row
  while (row != NULL) {
    channelname = row->GetField(1);
    pedestal = atof(row->GetField(2));
    noise = atof(row->GetField(3));
    fPedestalValues[channelname] = pedestal;
    fNoiseValues[channelname] = noise;
    delete row;
    row = (TSQLiteRow*) result->Next(); // get the next row
  }
  delete result; // user has to delete the result
  return !fPedestalValues.empty();
}
void SetupNavigator::SetCoarseTimeOffset (const IDs::source & src, double dt)
Definition at line 242 of file SetupNavigator.cpp.
References IDs::source::Channel(), fCoarseTimeOffset, IDs::source::Generator(), IsCalibRun(), and StripTimeShiftConfigFromString().
Referenced by PlotTAP_TDiff::AfterLastEntry(), and CalcCoarseTimeOffset::AfterLastEntry().
{
  if(!IsCalibRun()) {
    std::cout << "SetupNavigator: Warning: Request to edit coarse time offsets "
                 "when not flagged as calibration. Not setting." << std::endl;
    return;
  }
  // The excess code here is to strip {no_time_shift=*} from the generator config string
  fCoarseTimeOffset[IDs::source(src.Channel(), IDs::generator(StripTimeShiftConfigFromString(src.Generator().str())))] = dt;
}
void SetupNavigator::SetCommandLineArgs (const ARGUMENTS & args) [inline]
Closes the database if this is a calibration run.
Definition at line 33 of file SetupNavigator.h.
Referenced by main().
{fCommandLineArgs = args;}
void SetupNavigator::SetPedestalAndNoise (const IDs::channel & channel, double pedestal, double noise)
Definition at line 232 of file SetupNavigator.cpp.
References fNoiseValues, fPedestalValues, and IsCalibRun().
Referenced by PlotTPI_PedestalAndNoise::AfterLastEntry().
{
  if(!IsCalibRun()) {
    std::cout << "SetupNavigator: Warning: Request to edit pedestals and "
                 "noises when not flagged as calibration. Not setting." << std::endl;
    return;
  }
  fPedestalValues[chn] = ped;
  fNoiseValues[chn] = nse;
}
Member Data Documentation
std::map< IDs::source, double > SetupNavigator::fCoarseTimeOffset [static, private]
The map that stores the gross time offset values from SQLite database.
Definition at line 97 of file SetupNavigator.h.
Referenced by GetCoarseTimeOffset(), OutputCalibCSV(), ReadCoarseTimeOffsetValues(), and SetCoarseTimeOffset().
const std::string SetupNavigator::fCoarseTimeOffsetTableName [private]
Definition at line 86 of file SetupNavigator.h.
Referenced by CacheCalibDB(), GetCoarseTimeOffsetColumns(), OutputCalibCSV(), and ReadCoarseTimeOffsetValues().
ARGUMENTS SetupNavigator::fCommandLineArgs [private]
Definition at line 79 of file SetupNavigator.h.
std::map< IDs::channel, SetupNavigator::EnergyCalibRow_t > SetupNavigator::fEnergyCalibrationConstants [static, private]
Definition at line 101 of file SetupNavigator.h.
Referenced by GetEnergyCalibrationConstants(), and ReadEnergyCalibrationConstants().
const std::string SetupNavigator::fEnergyCalibrationConstantsTableName [private]
Definition at line 87 of file SetupNavigator.h.
Referenced by CacheCalibDB(), and ReadEnergyCalibrationConstants().
std::map< IDs::channel, double > SetupNavigator::fNoiseValues [static, private]
The map that stores the pedestal error values (i.e. noise) that we get from the SQLite database.
Definition at line 94 of file SetupNavigator.h.
Referenced by GetNoise(), OutputCalibCSV(), ReadPedestalAndNoiseValues(), and SetPedestalAndNoise().
const std::string SetupNavigator::fPedestalNoiseTableName [private]
Definition at line 85 of file SetupNavigator.h.
Referenced by CacheCalibDB(), OutputCalibCSV(), and ReadPedestalAndNoiseValues().
std::map< IDs::channel, double > SetupNavigator::fPedestalValues [static, private]
The map that stores the pedestal values that we get from the SQLite database.
Definition at line 91 of file SetupNavigator.h.
Referenced by GetPedestal(), OutputCalibCSV(), ReadPedestalAndNoiseValues(), and SetPedestalAndNoise().
TSQLiteServer* SetupNavigator::fServer [private]
Definition at line 84 of file SetupNavigator.h.
Referenced by CacheCalibDB(), Close(), GetCoarseTimeOffsetColumns(), ReadCoarseTimeOffsetValues(), ReadEnergyCalibrationConstants(), ReadPedestalAndNoiseValues(), and SetupNavigator().
const std::string SetupNavigator::fSQLiteFilename [private]
The SQLite filename, the SQLite server object and the current table name.
Definition at line 83 of file SetupNavigator.h.
SetupNavigator * SetupNavigator::fThis = NULL [static, private]
Definition at line 78 of file SetupNavigator.h.
Referenced by Close(), and Instance().
The documentation for this class was generated from the following files:
rootana/src/framework/SetupNavigator.h
rootana/src/framework/SetupNavigator.cpp