AlcapDAQ: TSetupData Class Reference
TSetupData Class Reference
#include <TSetupData.h>
Public Member Functions
std::string GetBankName (std::string DetectorName)
std::string GetDetectorName (std::string BankName) const
void GetAllDetectors (std::map< std::string, std::string > &detectors) const
void GetAllDetectors (std::vector< std::string > &detectors) const
double GetClockTick (const std::string &BankName) const
int GetNBits (const std::string &BankName) const
double GetADCSlopeCalib (const std::string &BankName) const
double GetADCOffsetCalib (const std::string &BankName) const
double GetTimeShift (const std::string &BankName) const
int GetTriggerPolarity (const std::string &BankName) const
int GetPedestal (const std::string &BankName) const
bool GetEnableBit (const std::string &BankName) const
bool SetDetectorName (std::string BankName, std::string value)
void SetClockTick (std::string BankName, double value)
void SetNBits (std::string BankName, int value)
void SetTimeShift (std::string BankName, double value)
void SetTriggerPolarity (std::string BankName, int value)
void SetPedestal (std::string BankName, int value)
void SetADCSlopeCalib (std::string BankName, double value)
void SetADCOffsetCalib (std::string BankName, double value)
void SetEnableBit (std::string BankName, bool value)
bool IsEnable (const std::string &BankName)
Static Public Member Functions
static TSetupData * Instance ()
static bool IsFADC (const std::string &BankName)
static bool IsHoustonCAEN (const std::string &BankName)
static bool IsBostonCAEN (const std::string &BankName)
static bool IsSlow (const std::string &BankName)
static bool IsFast (const std::string &BankName)
Data Fields
std::map< std::string,
std::string > fBankToDetectorMap
std::map< std::string, double > fBankToClockTickMap
std::map< std::string, int > fBankToBitMap
std::map< std::string, double > fBankToADCSlopeCalibMap
std::map< std::string, double > fBankToADCOffsetCalibMap
std::map< std::string, double > fBankToTimeShift
std::map< std::string, int > fBankToPolarityMap
std::map< std::string, int > fBankToPedestalMap
std::map< std::string, bool > fBankToEnableBitMap
Private Member Functions
double GetValue (const std::map< std::string, double > &map, const std::string &BankName) const
int GetValue (const std::map< std::string, int > &map, const std::string &BankName) const
bool GetValue (const std::map< std::string, bool > &map, const std::string &BankName) const
Detailed Description
This class holds all of the setup data for each run.
Definition at line 13 of file TSetupData.h.
Member Function Documentation
double TSetupData::GetADCOffsetCalib (const std::string & BankName) const inline
Definition at line 56 of file TSetupData.h.
References fBankToADCOffsetCalibMap, and GetValue().
Referenced by MaxBinAPGenerator::SetBankInfo().
 { return GetValue(fBankToADCOffsetCalibMap,BankName); };
double TSetupData::GetADCSlopeCalib (const std::string & BankName) const inline
Definition at line 55 of file TSetupData.h.
References fBankToADCSlopeCalibMap, and GetValue().
Referenced by MaxBinAPGenerator::SetBankInfo().
 { return GetValue(fBankToADCSlopeCalibMap,BankName); };
void TSetupData::GetAllDetectors (std::map< std::string, std::string > & detectors) const
Definition at line 14 of file TSetupData.cpp.
References fBankToDetectorMap.
Referenced by MakeAnalysedPulses::BeforeFirstEntry().
{
    std::map<std::string, std::string>::const_iterator it;
    for (it=fBankToDetectorMap.begin();it!= fBankToDetectorMap.end();it++){
        if(it->second!="blank" ) detectors[it->second]=it->first;
    }
 }
void TSetupData::GetAllDetectors (std::vector< std::string > & detectors) const
Definition at line 21 of file TSetupData.cpp.
References fBankToDetectorMap.
{
    std::map<std::string, std::string>::const_iterator it;
    for (it=fBankToDetectorMap.begin();it!= fBankToDetectorMap.end();it++){
        if(it->second!="blank" ) detectors.push_back(it->second);
    }
 }
std::string TSetupData::GetBankName (std::string DetectorName)
Referenced by ExportPulse::BeforeFirstEntry(), MDQ_muScTDiff(), MDQ_TDCCheck(), MFastSlowCorrelator(), MMuSCTimeDifferences(), PlotAmplitude::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), and ExportPulse::SetCurrentDetectorName().
double TSetupData::GetClockTick (const std::string & BankName) const inline
Definition at line 53 of file TSetupData.h.
References fBankToClockTickMap, and GetValue().
Referenced by TPulseIsland::GetClockTickInNs(), PrintSetupData(), MakeTemplate::ProcessEntry(), MaxBinCFAPGenerator::ProcessPulses(), and MaxBinAPGenerator::SetBankInfo().
 { return GetValue(fBankToClockTickMap,BankName);}
std::string TSetupData::GetDetectorName (std::string BankName) const inline
Definition at line 41 of file TSetupData.h.
References fBankToDetectorMap.
Referenced by MCombinePulses_init(), MCommonOnlineDisplayPlots(), MCommonOnlineDisplayPlots_init(), MdEdxPlot_init(), MDQ_Amplitude(), MDQ_Amplitude_eor(), MDQ_Amplitude_init(), MDQ_DigitizerOverflow(), MDQ_DigitizerOverflow_init(), MDQ_IslandCounter(), MDQ_IslandCounter_eor(), MDQ_IslandCounter_init(), MDQ_IslandLength(), MDQ_IslandLength_eor(), MDQ_IslandLength_init(), MDQ_IslandRate(), MDQ_IslandTimestamp(), MDQ_IslandTimestamp_eor(), MDQ_IslandTimestamp_init(), MDQ_muScTDiff(), MDQ_muScTDiff_eor(), MDQ_muScTDiff_init(), MDQ_PulseShapes(), MDQ_PulseShapes_eor(), MDQ_PulseShapes_init(), MDQ_Thresholds_init(), MPulseLengths_init(), MPulseTimeSeparation_init(), MShortPulseTimes(), MShortPulseTimes_init(), PrintSetupData(), MaxBinCFAPGenerator::ProcessPulses(), and MaxBinAPGenerator::SetBankInfo().
{
     if (fBankToDetectorMap.find(BankName)->second!= "blank")
       return fBankToDetectorMap.find(BankName)->second;
     else
       return BankName;
   };
bool TSetupData::GetEnableBit (const std::string & BankName) const inline
Definition at line 60 of file TSetupData.h.
References fBankToEnableBitMap, and GetValue().
Referenced by IsEnable().
 {return GetValue(fBankToEnableBitMap, BankName);};
int TSetupData::GetNBits (const std::string & BankName) const inline
Definition at line 54 of file TSetupData.h.
References fBankToBitMap, and GetValue().
Referenced by MDQ_Amplitude_init(), MDQ_DigitizerOverflow(), MDQ_PulseShapes_init(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PrintSetupData(), PlotAmplitude::ProcessEntry(), and MakeTemplate::ProcessEntry().
 { return GetValue(fBankToBitMap,BankName);}
int TSetupData::GetPedestal (const std::string & BankName) const inline
Definition at line 59 of file TSetupData.h.
References fBankToPedestalMap, and GetValue().
Referenced by TPulseIsland::GetPedestal(), PrintSetupData(), MakeTemplate::ProcessEntry(), MaxBinCFAPGenerator::ProcessPulses(), and MaxBinAPGenerator::SetBankInfo().
 {return GetValue(fBankToPedestalMap,BankName);};
double TSetupData::GetTimeShift (const std::string & BankName) const inline
Definition at line 57 of file TSetupData.h.
References fBankToTimeShift, and GetValue().
Referenced by GetTime(), PrintSetupData(), MaxBinCFAPGenerator::ProcessPulses(), and MaxBinAPGenerator::SetBankInfo().
 { return GetValue(fBankToTimeShift,BankName); };
int TSetupData::GetTriggerPolarity (const std::string & BankName) const inline
Definition at line 58 of file TSetupData.h.
References fBankToPolarityMap, and GetValue().
Referenced by TPulseIsland::GetTriggerPolarity(), PrintSetupData(), MakeTemplate::ProcessEntry(), MaxBinCFAPGenerator::ProcessPulses(), and MaxBinAPGenerator::SetBankInfo().
 {return GetValue(fBankToPolarityMap,BankName);};
double TSetupData::GetValue (const std::map< std::string, double > & map, const std::string & BankName) const inline private
Definition at line 89 of file TSetupData.h.
Referenced by GetADCOffsetCalib(), GetADCSlopeCalib(), GetClockTick(), GetEnableBit(), GetNBits(), GetPedestal(), GetTimeShift(), and GetTriggerPolarity().
{
           std::map<std::string, double>::const_iterator it=map.find(BankName);
           if(it!=map.end()) return it->second;
           return 0.;
   }
int TSetupData::GetValue (const std::map< std::string, int > & map, const std::string & BankName) const inline private
Definition at line 95 of file TSetupData.h.
{
           std::map<std::string, int>::const_iterator it=map.find(BankName);
           if(it!=map.end()) return it->second;
           return 0;
   }
bool TSetupData::GetValue (const std::map< std::string, bool > & map, const std::string & BankName) const inline private
Definition at line 101 of file TSetupData.h.
{
                 std::map<std::string, bool>::const_iterator it=map.find(BankName);
                 if(it!=map.end())
                         return it->second;
                 else
                         return false;
         }
TSetupData * TSetupData::Instance () static
Definition at line 275 of file main.cpp.
References GetTree(), gInFile, and printf().
Referenced by G__AlcapDict_504_0_1(), G__DataLibraryDict_504_0_1(), G__Dict_504_0_1(), G__setup_memfuncTSetupData(), TPulseIsland::GetAmplitude(), TPulseIsland::GetClockTickInNs(), TPulseIsland::GetPedestal(), TPulseIsland::GetTriggerPolarity(), Main_event_loop(), MDQ_Thresholds_eor(), PlotAmpVsTDiff::PlotAmpVsTDiff(), and PrepareSingletonObjects().
 {
   static TSetupData *s_data=NULL;
   // if s_data is already setup then we can just return it immediately
   if(s_data) return s_data;
   // Check we have a valid tree for the setup data
   TTree* setupTree= GetTree(gInFile, "SetupTree");
   if(!setupTree) return NULL;
   // Hook up the branch in the file to s_data and load in the data
   setupTree->SetBranchAddress("Setup",&s_data);
   if(!s_data) {
      printf("Unable to find TSetupData branch 'Setup' in the file");
      return NULL;
   }
   setupTree->GetEntry(0);
   return s_data;
 }
static bool TSetupData::IsBostonCAEN (const std::string & BankName) inline static
Definition at line 82 of file TSetupData.h.
Referenced by G__AlcapDict_504_0_22(), G__DataLibraryDict_504_0_22(), G__DataLibraryDict_504_0_25(), G__Dict_504_0_22(), G__setup_memfuncTSetupData(), MCommonOnlineDisplayPlots_init(), module_event_sort_and_stitch(), module_init(), and UpdateDetectorBankNameMap().
 { return BankName.substr(2,2)  == "BU"; } // if the first letter is C then the bank name is for a CAEN
bool TSetupData::IsEnable (const std::string & BankName) inline
Definition at line 86 of file TSetupData.h.
References GetEnableBit().
 {return GetEnableBit(BankName);}
static bool TSetupData::IsFADC (const std::string & BankName) inline static
Definition at line 80 of file TSetupData.h.
Referenced by G__AlcapDict_504_0_20(), G__DataLibraryDict_504_0_20(), G__DataLibraryDict_504_0_23(), G__Dict_504_0_20(), G__setup_memfuncTSetupData(), MCommonOnlineDisplayPlots_init(), MDQ_Thresholds_eor(), MOctalFADCProcessRaw_init(), and UpdateDetectorBankNameMap().
 { return BankName[0] == 'N'; } // if the first letter is N then the bank name is for a FADC
static bool TSetupData::IsFast (const std::string & BankName) inline static
Definition at line 84 of file TSetupData.h.
Referenced by MakeDetectorPulses::BeforeFirstEntry(), MakeAnalysedPulses::BeforeFirstEntry(), G__AlcapDict_504_0_24(), G__DataLibraryDict_504_0_24(), G__DataLibraryDict_504_0_27(), G__Dict_504_0_24(), G__setup_memfuncTSetupData(), MakeDetectorPulses::GetOtherChannelName(), and MaxTimeDiffDPGenerator::ProcessPulses().
 { return (*(BankName.end() -1)  == 'F' || BankName.substr(0,2) == "Sc" ); } // if the last letter is F then the bank name is for a Fast pulse
static bool TSetupData::IsHoustonCAEN (const std::string & BankName) inline static
Definition at line 81 of file TSetupData.h.
Referenced by G__AlcapDict_504_0_21(), G__DataLibraryDict_504_0_21(), G__DataLibraryDict_504_0_24(), G__Dict_504_0_21(), G__setup_memfuncTSetupData(), MCommonOnlineDisplayPlots_init(), module_event_sort_and_stitch(), module_init(), and UpdateDetectorBankNameMap().
 { return BankName.substr(2,2) == "UH"; } // if the first letter is C then the bank name is for a CAEN
static bool TSetupData::IsSlow (const std::string & BankName) inline static
Definition at line 83 of file TSetupData.h.
Referenced by G__AlcapDict_504_0_23(), G__DataLibraryDict_504_0_23(), G__DataLibraryDict_504_0_26(), G__Dict_504_0_23(), G__setup_memfuncTSetupData(), and MaxTimeDiffDPGenerator::ProcessPulses().
 { return (*BankName.end() -1 ) == 'S'; } // if the last letter is S then the bank name is for a Slow pulse
void TSetupData::SetADCOffsetCalib (std::string BankName, double value) inline
Definition at line 77 of file TSetupData.h.
References fBankToADCOffsetCalibMap, and value.
Referenced by UpdateDetectorBankNameMap().
 { fBankToADCOffsetCalibMap[BankName] = value; };
void TSetupData::SetADCSlopeCalib (std::string BankName, double value) inline
Definition at line 76 of file TSetupData.h.
References fBankToADCSlopeCalibMap, and value.
Referenced by UpdateDetectorBankNameMap().
 { fBankToADCSlopeCalibMap[BankName] = value; }
void TSetupData::SetClockTick (std::string BankName, double value) inline
Definition at line 71 of file TSetupData.h.
References fBankToClockTickMap, and value.
Referenced by UpdateDetectorBankNameMap().
 { fBankToClockTickMap[BankName]=value; }
bool TSetupData::SetDetectorName (std::string BankName, std::string value) inline
Definition at line 63 of file TSetupData.h.
References fBankToDetectorMap, and value.
Referenced by UpdateDetectorBankNameMap().
{
     std::map< std::string, std::string >::iterator it;
     for (it = fBankToDetectorMap.begin(); it != fBankToDetectorMap.end(); ++it)
       if (it->second == value)
         return false;
     fBankToDetectorMap[BankName] = value;
     return true;
   }
void TSetupData::SetEnableBit (std::string BankName, bool value) inline
Definition at line 78 of file TSetupData.h.
References fBankToEnableBitMap, and value.
Referenced by UpdateDetectorBankNameMap().
 {fBankToEnableBitMap[BankName] = value;};
void TSetupData::SetNBits (std::string BankName, int value) inline
Definition at line 72 of file TSetupData.h.
References fBankToBitMap, and value.
Referenced by UpdateDetectorBankNameMap().
 { fBankToBitMap[BankName]=value; }
void TSetupData::SetPedestal (std::string BankName, int value) inline
Definition at line 75 of file TSetupData.h.
References fBankToPedestalMap, and value.
Referenced by UpdateDetectorBankNameMap().
 { fBankToPedestalMap[BankName]=value; }
void TSetupData::SetTimeShift (std::string BankName, double value) inline
Definition at line 73 of file TSetupData.h.
References fBankToTimeShift, and value.
Referenced by UpdateDetectorBankNameMap().
 { fBankToTimeShift[BankName]=value; }
void TSetupData::SetTriggerPolarity (std::string BankName, int value) inline
Definition at line 74 of file TSetupData.h.
References fBankToPolarityMap, and value.
Referenced by UpdateDetectorBankNameMap().
 { fBankToPolarityMap[BankName]=value; }
Field Documentation
std::map<std::string, double> TSetupData::fBankToADCOffsetCalibMap
Definition at line 33 of file TSetupData.h.
Referenced by G__setup_memvarTSetupData(), GetADCOffsetCalib(), and SetADCOffsetCalib().
std::map<std::string, double> TSetupData::fBankToADCSlopeCalibMap
Definition at line 32 of file TSetupData.h.
Referenced by G__setup_memvarTSetupData(), GetADCSlopeCalib(), and SetADCSlopeCalib().
std::map<std::string, int> TSetupData::fBankToBitMap
Definition at line 31 of file TSetupData.h.
Referenced by G__setup_memvarTSetupData(), GetNBits(), and SetNBits().
std::map<std::string, double> TSetupData::fBankToClockTickMap
Definition at line 30 of file TSetupData.h.
Referenced by G__setup_memvarTSetupData(), GetClockTick(), and SetClockTick().
std::map<std::string, std::string> TSetupData::fBankToDetectorMap
Definition at line 29 of file TSetupData.h.
Referenced by G__setup_memvarTSetupData(), GetAllDetectors(), GetDetectorName(), MCombinePulses_init(), MCommonOnlineDisplayPlots_bor(), MCommonOnlineDisplayPlots_init(), MdEdxPlot_init(), MDQ_Amplitude_init(), MDQ_DigitizerOverflow_init(), MDQ_IslandCounter_init(), MDQ_IslandLength_init(), MDQ_IslandTimestamp_init(), MDQ_muScTDiff_init(), MDQ_PulseShapes_eor(), MDQ_PulseShapes_init(), MDQ_Thresholds_eor(), MDQ_Thresholds_init(), MFastSlowCorrelator_init(), MHitTime(), MHitTime_init(), MMuSCTimeDifferences_init(), MOctalFADCProcessRaw_init(), module_init(), MPileUpPerBlock(), MPulseLengths_init(), MPulseTimeSeparation_init(), MShortPulseTimes_init(), MStoppedMuonsPerBlock(), PrintSetupData(), Normalization::ProcessEntry(), and SetDetectorName().
std::map<std::string, bool> TSetupData::fBankToEnableBitMap
Definition at line 37 of file TSetupData.h.
Referenced by G__setup_memvarTSetupData(), GetEnableBit(), and SetEnableBit().
std::map<std::string, int> TSetupData::fBankToPedestalMap
Definition at line 36 of file TSetupData.h.
Referenced by G__setup_memvarTSetupData(), GetPedestal(), and SetPedestal().
std::map<std::string, int> TSetupData::fBankToPolarityMap
Definition at line 35 of file TSetupData.h.
Referenced by G__setup_memvarTSetupData(), GetTriggerPolarity(), and SetTriggerPolarity().
std::map<std::string, double> TSetupData::fBankToTimeShift
Definition at line 34 of file TSetupData.h.
Referenced by G__setup_memvarTSetupData(), GetTimeShift(), and SetTimeShift().
The documentation for this class was generated from the following files:
analyzer/src/common/TSetupData.h
analyzer/rootana/src/main.cpp
analyzer/src/common/analyzer.cpp
analyzer/src/common/TSetupData.cpp