AlcapDAQ: TMEGeneratorOptions Class Reference
TMEGeneratorOptions Class Reference
#include <TMEGeneratorOptions.h>
Public Types
typedef std::map< std::string,
std::string > OptionsList_t
Helper typedef, intended for the list of key-value pairs for each option.
typedef std::vector
< OptionsList_t::iterator > OptionsOrder_t
Helper typedef, intended to keep the order of option declaration.
Public Member Functions
TMEGeneratorOptions (const std::string &name)
~TMEGeneratorOptions ()
TMEGeneratorOptions (const std::string &name, const modules::options *opts)
TMEGeneratorOptions & operator= (const modules::options &rhs)
std::string StringDescription () const
Flatten all options into a string.
void SetOption (const std::string &key, const std::string &value)
Set the value of an option.
bool AppendToOption (const std::string &key, const std::string &value)
Append a new value to a list.
void AddArgument (const int &number, const std::string &value)
Set the value of an argument.
int GetInt (const std::string &name, int defVal, const std::string &range="") const
Get the named option as an int.
int GetInt (const std::string &name, const std::string &range="") const
Get the named option as an int, which MUST exist.
double GetDouble (const std::string &name, double defVal, const std::string &range="") const
Get the named option as a double.
double GetDouble (const std::string &name, const std::string &range="") const
Get the named option as a double, which MUST exist.
std::string GetString (const std::string &name, const std::string &defVal) const
Get the named option as a string.
std::string GetString (const std::string &name) const
Get the named option as a string.
bool GetBool (const std::string &name, bool defVal) const
Get the named option as a bool.
bool GetBool (const std::string &name) const
Get the named option as a bool.
int GetVectorStringsByWhiteSpace (const std::string &name, std::vector< std::string > &vect) const
Fill a vector of strings with whitespace delimited tokens found in the named option.
int GetVectorStringsByDelimiter (const std::string &name, std::vector< std::string > &vect, const char *delim=":") const
Fill a vector of strings with tokens found in the named option @ Uses strtok so not suitable for multi-threading (if we ever do something like that).
bool HasOption (const std::string &name) const
Check if a named option has been set.
bool GetFlag (const std::string &name) const
Check if a flag option has been set.
bool GetNumOptions () const
Get the number of options managed by this options list.
std::string GetOption (const std::string &name, bool complain=false) const
Returns the unprocessed value assigned to name.
OptionsList_t::const_iterator begin () const
Get a const iterator to the first key-value pair (sorted alphabetically by.
OptionsList_t::const_iterator end () const
Get a const iterator to the last key-value pair (sorted alphabetically by key).
void DumpOptions (const std::string &prefix=" ") const
Print all options managed by this list to cout.
void SetAlias (const std::string &alias)
Set the alias option for this module.
std::string GetAlias (const std::string &defVal="") const
Get the alias option for this module.
Protected Attributes
std::string fModuleName
Detailed Description
Class to handle options for a TME generator Inherite from the options class for modules to share the implementation and interface.
Definition at line 9 of file TMEGeneratorOptions.h.
Member Typedef Documentation
typedef std::map<std::string,std::string> modules::options::OptionsList_t [inherited]
Helper typedef, intended for the list of key-value pairs for each option.
Definition at line 29 of file ModulesOptions.h.
typedef std::vector<OptionsList_t::iterator> modules::options::OptionsOrder_t [inherited]
Helper typedef, intended to keep the order of option declaration.
Definition at line 31 of file ModulesOptions.h.
Constructor & Destructor Documentation
TMEGeneratorOptions::TMEGeneratorOptions (const std::string & name) [inline]
Definition at line 11 of file TMEGeneratorOptions.h.
                                                  :
                modules::options(name){};
        ~TMEGeneratorOptions(){};
TMEGeneratorOptions::~TMEGeneratorOptions () [inline]
Definition at line 13 of file TMEGeneratorOptions.h.
{};
TMEGeneratorOptions::TMEGeneratorOptions (const std::string & name, const modules::options * opts) [inline]
Definition at line 15 of file TMEGeneratorOptions.h.
References operator=().
                                                                         :
        modules::options(name){
            modules::options::operator=(*opts);
        }
Member Function Documentation
void modules::options::AddArgument (const int & number, const std::string & value) [inherited]
Set the value of an argument.
If the module has not specified a name for this argument, the key for this option is set to number ALCAP_REGISTER_MODULE
Parameters:
number The number of the argument to set
value The new value of the argument
Reimplemented in TAPGeneratorOptions, and TDPGeneratorOptions.
Definition at line 117 of file ModulesOptions.cpp.
References modules::options::fModuleName, TemplateFactory< BaseModule, OptionsType >::GetArgumentName(), modules::factory::Instance(), and modules::options::SetOption().
Referenced by modules::reader::AddModule().
{
    // Get the name of this argument
    std::string name = modules::factory::Instance()->GetArgumentName(fModuleName,number);
    // Set the value of the corresponding option
    modules::options::SetOption(name,option);
}
bool modules::options::AppendToOption (const std::string & key, const std::string & value) [inherited]
Append a new value to a list.
The new value is separated from the previous one with: " : "
Parameters:
key The name of the option to add to
value The value to append
Returns:
true if a value existed already and false if not
Definition at line 124 of file ModulesOptions.cpp.
References modules::options::fOptions.
Referenced by modules::reader::AddOption().
{
    // Get the option
    OptionsList_t::iterator it= fOptions.find(name);
    // If no option exists return false
    if(it==fOptions.end()) return false;
    // Add the value to it
    it->second+=" : "+option;
    return true;
}
OptionsList_t::const_iterator modules::options::begin () const [inline, inherited]
Get a const iterator to the first key-value pair (sorted alphabetically by.
Definition at line 184 of file ModulesOptions.h.
References modules::options::fOptions.
Referenced by ExportPulse::BeforeFirstEntry().
{return fOptions.begin();};
void modules::options::DumpOptions (const std::string & prefix = " ") const [inherited]
Print all options managed by this list to cout.
Parameters:
prefix Appended before each line is printed
Definition at line 105 of file ModulesOptions.cpp.
References modules::options::fOrder.
Referenced by load_config_file(), and modules::navigator::MakeModules().
{
    //std::cout<<"key  "<<" = "<<" value "<<std::endl;
    OptionsOrder_t::const_iterator it;
    for(it=fOrder.begin();it!=fOrder.end();it++){
        std::cout<<prefix<<(*it)->first;
        if((*it)->second!=""){
           std::cout<<" = "<<(*it)->second;
        }
        std::cout<<std::endl;
    }
}
OptionsList_t::const_iterator modules::options::end () const [inline, inherited]
Get a const iterator to the last key-value pair (sorted alphabetically by key).
Definition at line 186 of file ModulesOptions.h.
References modules::options::fOptions.
Referenced by ExportPulse::BeforeFirstEntry().
{return fOptions.end();};
std::string modules::options::GetAlias (const std::string & defVal = "") const [inline, inherited]
Get the alias option for this module.
Definition at line 198 of file ModulesOptions.h.
References modules::options::GetString().
Referenced by BaseModule::BaseModule().
{return GetString("alias",defVal);};
bool modules::options::GetBool (const std::string & name) const [inherited]
Get the named option as a bool.
Parameters:
name Name of the option to get
Definition at line 74 of file ModulesOptions.cpp.
References modules::options::GetString(), and modules::parser::IsTrue().
{
    return modules::parser::IsTrue(GetString(name));
}
bool modules::options::GetBool (const std::string & name, bool defVal) const [inherited]
Get the named option as a bool.
Parameters:
name Name of the option to get
defVal Value to use if not found
Definition at line 78 of file ModulesOptions.cpp.
References modules::options::GetString(), and modules::parser::IsTrue().
Referenced by BaseModule::BaseModule(), FirstCompleteAPGenerator::FirstCompleteAPGenerator(), modules::options::GetFlag(), PulseViewer::PulseViewer(), TemplateCreator::TemplateCreator(), and TME_Al50_EvdE::TME_Al50_EvdE().
{
    return modules::parser::IsTrue(GetString(name,Form("%d",defVal)));
}
double modules::options::GetDouble (const std::string & name, const std::string & range = "") const [inherited]
Get the named option as a double, which MUST exist.
Throws module::missing_option if the named option doesn't exist.
Use the range string to specify a validity range. Behind the scenes this uses ROOTs TFormula so any boolean operation is valid. Within the expression, either use the option's name as specified by the first argument to this method, or use "x". If the value fails the validity check, the modules::bad_value exception is thrown
Parameters:
name Name of the option to get
range Optional range for acceptable values
Definition at line 54 of file ModulesOptions.cpp.
{
    return GetOption<double>(name,0,true,range);
}
double modules::options::GetDouble (const std::string & name, double defVal, const std::string & range = "") const [inherited]
Get the named option as a double.
Use the range string to specify a validity range. Behind the scenes this uses ROOTs TFormula so any boolean operation is valid. Within the expression, either use the option's name as specified by the first argument to this method, or use "x". If the value fails the validity check, the modules::bad_value exception is thrown
Parameters:
name Name of the option to get
defVal Value to use if not found
range Optional range for acceptable values
Definition at line 57 of file ModulesOptions.cpp.
Referenced by FixedWindowMEGenerator::FixedWindowMEGenerator(), GaussFitAPGenerator::GaussFitAPGenerator(), MaxTimeDiffDPGenerator::MaxTimeDiffDPGenerator(), PlotIntegralRatios::PlotIntegralRatios(), PlotTDPs::PlotTDPs(), PulseCandidateFinder::PulseCandidateFinder(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateCreator::TemplateCreator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and GeSpectrum::ThrowIfInputsInsane().
{
    return GetOption<double>(name,defVal,false,range);
}
bool modules::options::GetFlag (const std::string & name) const [inline, inherited]
Check if a flag option has been set.
If the option is present with no value return true, else return true if the value gives boolean true
Parameters:
name Name of option to use
Returns:
true if option was set, false if not
Definition at line 243 of file ModulesOptions.h.
References modules::options::GetBool(), modules::options::GetOption(), and modules::options::HasOption().
Referenced by TemplateCreator::ChannelSet::ChannelSet(), ExportPulse::ExportPulse(), PlotTDPs::PlotTDPs(), PulseCandidateFinder::PulseCandidateFinder(), PulseViewer::PulseViewer(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and TVMuonEventGenerator::TVMuonEventGenerator().
{
    return (HasOption(name) && (GetOption(name).empty() || GetBool(name)));
}
int modules::options::GetInt (const std::string & name, const std::string & range = "") const [inherited]
Get the named option as an int, which MUST exist.
Throws module::missing_option if the named option doesn't exist.
Use the range string to specify a validity range. Behind the scenes this uses ROOTs TFormula so any boolean operation is valid. Within the expression, either use the option's name as specified by the first argument to this method, or use "x". If the value fails the validity check, the modules::bad_value exception is thrown
Parameters:
name Name of the option to get
range Optional range for acceptable values
Definition at line 47 of file ModulesOptions.cpp.
{
    return GetOption<int>(name,0,true,range);
}
int modules::options::GetInt (const std::string & name, int defVal, const std::string & range = "") const [inherited]
Get the named option as an int.
Use the range string to specify a validity range. Behind the scenes this uses ROOTs TFormula so any boolean operation is valid. Within the expression, either use the option's name as specified by the first argument to this method, or use "x". If the value fails the validity check, the modules::bad_value exception is thrown
Parameters:
name Name of the option to get
defVal Value to use if not found
range Optional range for acceptable values
Definition at line 50 of file ModulesOptions.cpp.
Referenced by PulseCandidateFinder::PulseCandidateFinder(), PulseViewer::PulseViewer(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateCreator::TemplateCreator(), and TemplateFitAPGenerator::TemplateFitAPGenerator().
{
    return GetOption<int>(name,defVal,false,range);
}
bool modules::options::GetNumOptions () const [inline, inherited]
Get the number of options managed by this options list.
Definition at line 177 of file ModulesOptions.h.
References modules::options::fOptions.
Referenced by MakeAnalysedPulses::AddGenerator().
{return fOptions.size();};
std::string modules::options::GetOption (const std::string & name, bool complain = false) const [inherited]
Returns the unprocessed value assigned to name.
Parameters:
name Name of the option to get
Definition at line 15 of file ModulesOptions.cpp.
References modules::options::fModuleName, and modules::options::fOptions.
Referenced by BaseModule::BaseModule(), modules::options::GetFlag(), modules::options::GetOption(), modules::options::GetString(), modules::options::GetVectorStringsByDelimiter(), and modules::options::GetVectorStringsByWhiteSpace().
{
    OptionsList_t::const_iterator it = fOptions.find(key);
    if(it==fOptions.end()){
        if(complain){
            throw missing_option(fModuleName,key);
        }
        return "";
    }
    return it->second;
}
std::string modules::options::GetString (const std::string & name) const [inherited]
Get the named option as a string.
Trims whitespace from the front and back of the option
Parameters:
name Name of the option to get
Definition at line 61 of file ModulesOptions.cpp.
References modules::options::GetOption(), and modules::parser::TrimWhiteSpaceBeforeAfter().
{
    std::string ret_val=GetOption(name,true);
    modules::parser::TrimWhiteSpaceBeforeAfter(ret_val);
    return ret_val;
}
std::string modules::options::GetString (const std::string & name, const std::string & defVal) const [inherited]
Get the named option as a string.
Trims whitespace from the front and back of the option (but not for the default value if the modules file didn't specify anything)
Parameters:
name Name of the option to get
defVal Value to use if not found
Definition at line 67 of file ModulesOptions.cpp.
References modules::options::GetOption(), and modules::parser::TrimWhiteSpaceBeforeAfter().
Referenced by MakeDetectorPulses::BeforeFirstEntry(), CalcCoarseTimeOffset::CalcCoarseTimeOffset(), modules::options::GetAlias(), modules::options::GetBool(), LoadPulses::LoadPulses(), MakeDetectorPulses::MakeDetectorPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTDP_TDiff::PlotTDP_TDiff(), PulseViewer::PulseViewer(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateCreator::TemplateCreator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and GeSpectrum::ThrowIfInputsInsane().
{
    std::string ret_val=GetOption(name,false);
    modules::parser::TrimWhiteSpaceBeforeAfter(ret_val);
    if(ret_val=="") ret_val=defVal;
    return ret_val;
}
int modules::options::GetVectorStringsByDelimiter (const std::string & name, std::vector< std::string > & vect, const char * delim = ":") const [inherited]
Fill a vector of strings with tokens found in the named option @ Uses strtok so not suitable for multi-threading (if we ever do something like that).
Parameters:
name Name of option to use
vect vector to fill with tokens
delim c-string of chars to use as delimiter
Returns:
Number of tokens pushed in to vect
Definition at line 92 of file ModulesOptions.cpp.
References modules::options::GetOption().
Referenced by MakeAnalysedPulses::BeforeFirstEntry(), ExportPulse::BeforeFirstEntry(), and TemplateCreator::TemplateCreator().
{
    char line[2048];
    strcpy(line,GetOption(name).c_str());
    char* word = strtok(line,delim);
    int num_tokens=0;
    for(;word != NULL; num_tokens++) {
            //std::cout<<"ModulesOptions:GetVectorStringsByDelimiter() "<<word<<std::endl;
        vect.push_back(word);
        word = strtok(NULL,delim);
    }
    return num_tokens;
}
int modules::options::GetVectorStringsByWhiteSpace (const std::string & name, std::vector< std::string > & vect) const [inherited]
Fill a vector of strings with whitespace delimited tokens found in the named option.
Parameters:
name Name of option to use
vect vector to fill with tokens
Returns:
Number of tokens pushed in to vect
Definition at line 82 of file ModulesOptions.cpp.
References modules::options::GetOption().
Referenced by MakeAnalysedPulses::MakeAnalysedPulses(), and MakeDetectorPulses::MakeDetectorPulses().
{
    std::stringstream ss(GetOption(name));
    std::string val;
    int num_tokens=0;
    for(;ss>>val; num_tokens++) {
      vect.push_back(val);
    }
    return num_tokens;
}
bool modules::options::HasOption (const std::string & name) const [inline, inherited]
Check if a named option has been set.
Parameters:
name Name of option to use
Returns:
true if option was set, false if not
Definition at line 239 of file ModulesOptions.h.
References modules::options::fOptions.
Referenced by BaseModule::BaseModule(), MakeDetectorPulses::BeforeFirstEntry(), MakeAnalysedPulses::BeforeFirstEntry(), modules::options::GetFlag(), PulseCandidateFinder::PulseCandidateFinder(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{
    return fOptions.find(name)!=fOptions.end();
}
TMEGeneratorOptions& TMEGeneratorOptions::operator= (const modules::options & rhs) [inline]
Definition at line 20 of file TMEGeneratorOptions.h.
Referenced by TMEGeneratorOptions().
{
        modules::options::operator=(rhs);
        return *this;
    }
void modules::options::SetAlias (const std::string & alias) [inline, inherited]
Set the alias option for this module.
Definition at line 196 of file ModulesOptions.h.
References modules::options::SetOption().
Referenced by modules::reader::AddModule().
{SetOption("alias",alias);};
void modules::options::SetOption (const std::string & key, const std::string & value) [inline, inherited]
Set the value of an option.
If a previous value was set, it is replaced by this one
Parameters:
key The name of the option to set
value The new value
Definition at line 232 of file ModulesOptions.h.
References modules::options::fOptions, and modules::options::fOrder.
Referenced by TDPGeneratorOptions::AddArgument(), TAPGeneratorOptions::AddArgument(), modules::options::AddArgument(), modules::reader::AddOption(), FirstCompleteAPGenerator::FirstCompleteAPGenerator(), MakeAnalysedPulses::MakeAnalysedPulses(), and modules::options::SetAlias().
{
    // if a new key was added, store an iterator in the order list
    OptionsList_t::iterator it = fOptions.find(name);
    fOptions[name]=option;
    if(it==fOptions.end()) fOrder.push_back(fOptions.find(name));
}
std::string modules::options::StringDescription () const [inherited]
Flatten all options into a string.
Used to provide unique identifiers of a module or generator, based on it's configuration
Definition at line 141 of file ModulesOptions.cpp.
References modules::options::fOrder.
Referenced by BaseModule::BaseModule(), TVAnalysedPulseGenerator::TVAnalysedPulseGenerator(), and TVDetectorPulseGenerator::TVDetectorPulseGenerator().
{
    const char* key_val_sep="=";
    const char* start_key_val="{";
    const char* stop_key_val="}";
    OptionsOrder_t::const_iterator it;
    std::string description;
    for(it=fOrder.begin();it!=fOrder.end();it++){
        description+=start_key_val;
        description+=(*it)->first;
        if((*it)->second!=""){
            description+=key_val_sep;
            description+=(*it)->second;
        }
        description+=stop_key_val;
    }
    return description;
}
Member Data Documentation
std::string modules::options::fModuleName [protected, inherited]
Definition at line 228 of file ModulesOptions.h.
Referenced by TDPGeneratorOptions::AddArgument(), TAPGeneratorOptions::AddArgument(), modules::options::AddArgument(), modules::options::CheckValid(), and modules::options::GetOption().
The documentation for this class was generated from the following file:
rootana/src/TME_generators/TMEGeneratorOptions.h