AlcapDAQ: MakeAnalysedPulses Class Reference
MakeAnalysedPulses Class Reference
#include <MakeAnalysedPulses.h>
Public Member Functions
MakeAnalysedPulses (modules::options *opts)
~MakeAnalysedPulses ()
bool AddGenerator (const std::string &detector, std::string generatorType, TAPGeneratorOptions *opts=NULL)
bool ParseGeneratorList (std::string generatorList, const std::vector< std::string > &)
void SetAnalysedPulseMap (StringAnalPulseMap &aMap)
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::vector
< TVAnalysedPulseGenerator * > ChannelGenerators_t
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
The big kahuna. Overload this in the derived class and it will be called for each event.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
void CalibratePulses (const TVAnalysedPulseGenerator *generator, AnalysedPulseList &theAnalysedPulses) const
Private Attributes
ChannelGenerators_t fGenerators
StringAnalPulseMap * fAnalysedPulseMap
std::string fSlowGeneratorType
std::string fFastGeneratorType
std::vector< std::string > fChannelsToAnalyse
modules::options * fOptions
TAPGeneratorOptions * fDefaultOpts
Detailed Description
Definition at line 19 of file MakeAnalysedPulses.h.
Member Typedef Documentation
typedef std::vector<TVAnalysedPulseGenerator*> MakeAnalysedPulses::ChannelGenerators_t [private]
Definition at line 20 of file MakeAnalysedPulses.h.
Constructor & Destructor Documentation
MakeAnalysedPulses::MakeAnalysedPulses (modules::options * opts)
Definition at line 21 of file MakeAnalysedPulses.cpp.
References BaseModule::Debug(), fChannelsToAnalyse, fDefaultOpts, modules::options::GetVectorStringsByWhiteSpace(), and modules::options::SetOption().
                                                          :
  BaseModule("MakeAnalysedPulses",opts,false),
  fSlowGeneratorType(opts->GetString("default_slow_generator","MaxBin")),
  fFastGeneratorType(opts->GetString("default_fast_generator","MaxBin")),
  fChannelsToAnalyse(),
  fOptions(opts),
  fDefaultOpts(new TAPGeneratorOptions("default generator options")){
    opts->GetVectorStringsByWhiteSpace("analyse_channels",fChannelsToAnalyse);
    if(Debug()) fDefaultOpts->SetOption("debug","true");
}
MakeAnalysedPulses::~MakeAnalysedPulses ()
Definition at line 32 of file MakeAnalysedPulses.cpp.
{
}
Member Function Documentation
bool MakeAnalysedPulses::AddGenerator (const std::string & detector, std::string generatorType, TAPGeneratorOptions * opts = NULL)
Definition at line 192 of file MakeAnalysedPulses.cpp.
References TemplateFactory< BaseModule, OptionsType >::createModule(), BaseModule::Debug(), TAPGeneratorOptions::Debug(), fDefaultOpts, fFastGeneratorType, fGenerators, fSlowGeneratorType, modules::options::GetNumOptions(), TAPGeneratorFactory::Instance(), IDs::kFast, IDs::kSlow, and TAPGeneratorOptions::SetChannel().
Referenced by ParseGeneratorList().
{
    // If generatorType is '!FAST!' or '!SLOW!' replace with default value
    enum {kFast, kSlow, kArbitrary} requestType;
    if(generatorType=="!FAST!") {
        generatorType=fFastGeneratorType;
        requestType=kFast;
    }else if(generatorType=="!SLOW!"){
        generatorType=fSlowGeneratorType;
        requestType=kSlow;
    }else requestType=kArbitrary;
    // Make sure opts is not null
    if(!opts) opts=new TAPGeneratorOptions(*fDefaultOpts);
    opts->SetChannel(detector);
    opts->Debug(Debug());
    // Get the requested generator
    TVAnalysedPulseGenerator* generator=
        TAPGeneratorFactory::Instance()->createModule(generatorType,opts);
    if(!generator) return false;
    // print something
    if(Debug()) {
        cout<<detector<<": using ";
        if (requestType ==kFast) cout<<"default fast: ";
        else if (requestType ==kSlow) cout<<"default slow: ";
        else cout<<"generator: ";
        cout<<generatorType ;
        if(opts) cout<<" with "<<opts->GetNumOptions()<<" option(s).";
        cout<<endl;
    }
    // Add this generator to the list for the required detector
    fGenerators.push_back(generator);
    return true;
}
virtual int MakeAnalysedPulses::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [inline, private, virtual]
Optional method which is called once after the main event loop Can be used to dump a summary or finalise a histogram
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 33 of file MakeAnalysedPulses.h.
{return 0;};
int MakeAnalysedPulses::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Optional method which is called once before the main event loop Can be used to parse options and setup histograms.
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 35 of file MakeAnalysedPulses.cpp.
References detectors, fChannelsToAnalyse, fGenerators, fOptions, gAnalysedPulseMap, TSetupData::GetAllDetectors(), modules::options::GetVectorStringsByDelimiter(), modules::options::HasOption(), modules::parser::iequals(), TSetupData::IsFast(), and ParseGeneratorList().
{
    // Loop over every named detector channel in TSetupData
    std::vector<std::string> detectors;
    setup->GetAllDetectors(detectors);
    // do we analyse all channels?
    bool analyse_all=fChannelsToAnalyse.empty();
    if(!analyse_all){
        for(unsigned i=0;i<fChannelsToAnalyse.size();i++){
            if (fChannelsToAnalyse[i]=="all"){
                analyse_all=true;
                break;
            }
        }
    }
    std::cout<<"MakeAnalysedPulses::BeforeFirstEntry: Will analyse ";
    if(analyse_all) std::cout<<"all ";
    else std::cout<<fChannelsToAnalyse.size()<<" of ";
    std::cout<<detectors.size()<<" channels"<<std::endl;
    // For each channel:
    bool skip_detector=false;
    std::string des_gen;
    for(std::vector<std::string>::const_iterator det=detectors.begin();
            det!=detectors.end(); det++){
        // if we should not analyse det, leave generator as NULL
        skip_detector=false;
        if(! analyse_all ){
            std::vector<std::string>::const_iterator it_chan;
            for(it_chan=fChannelsToAnalyse.begin();
                    it_chan!=fChannelsToAnalyse.end();
                    it_chan++){
                if(modules::parser::iequals((*it_chan), (*det)) )break;
            }
            if(it_chan== fChannelsToAnalyse.end() ) skip_detector=true;
        }
        if(skip_detector)
          continue;
        // else find the right generator to build
        if(fOptions->HasOption(*det)){
            // If this channel is named explicitly, use that generator type
            // Get a vector for the generator(s) that we want to use for this detector
            std::vector<std::string> generatorList;
            fOptions->GetVectorStringsByDelimiter(*det,generatorList);
            bool success=ParseGeneratorList(*det,generatorList);
            if(! success) return 1;
        } else{
            // else use default value for this type of channel (fast or slow)
            if(TSetupData::IsFast(*det)){
                std::vector<std::string> generatorList;
                fOptions->GetVectorStringsByDelimiter("default_fast_generator",generatorList);
                bool success=ParseGeneratorList(*det,generatorList);
                if(!success) return 1;
            } else {
                std::vector<std::string> generatorList;
                fOptions->GetVectorStringsByDelimiter("default_slow_generator",generatorList);
                bool success=ParseGeneratorList(*det,generatorList);
                if(!success) return 1;
            }
        }
    }
    // now make an entry in gAnalysedPulseMap for each generator added
    for(ChannelGenerators_t::const_iterator i_gen=fGenerators.begin();
            i_gen!=fGenerators.end();i_gen++){
        gAnalysedPulseMap[(*i_gen)->GetSource()];
    }
    return 0;
}
void MakeAnalysedPulses::CalibratePulses (const TVAnalysedPulseGenerator * generator, AnalysedPulseList & theAnalysedPulses) const [private]
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
bool MakeAnalysedPulses::ParseGeneratorList (std::string generatorList, const std::vector< std::string > & generatorList)
Definition at line 155 of file MakeAnalysedPulses.cpp.
References TAPGeneratorOptions::AddArgument(), AddGenerator(), and modules::parser::GetOneWord().
Referenced by BeforeFirstEntry().
{
    //scan to next item in the list
    size_t start_br=0;
    size_t end_br=std::string::npos;
    std::vector<std::string>::const_iterator gen;
    std::string arg,generator;
    TAPGeneratorOptions* opts;
    bool still_good=true;
    for(gen=generatorList.begin();gen!= generatorList.end();gen++){
      // check if we have options for this generator
      start_br=gen->find('(');
      generator=GetOneWord(*gen,0,start_br);
      if(start_br!=std::string::npos){
        std::stringstream sstream;
        // There are options for this generator
        ++start_br; // Move to first character after '('
        end_br=gen->find(')');
        sstream.str(gen->substr(start_br,end_br-start_br));
        opts=new TAPGeneratorOptions(generator);
        for(int count=0; std::getline(sstream, arg,','); count++){
          opts->AddArgument(count,arg);
        }
      }
      still_good = AddGenerator(detector,generator,opts);
      // Is everything ok to continue?
      if (!still_good) {
        return false;
      }
      // Get ready for next iteration
      opts=NULL;
    }
    // Everything went ok, return true
    return true;
}
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int MakeAnalysedPulses::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
The big kahuna. Overload this in the derived class and it will be called for each event.
Parameters:
gData Pointer to current map of all TPIs [ WILL CHANGE SHORTLY ]
gSetup Pointer to TSetupData for this run [ WILL CHANGE SHORTLY ]
Returns:
0 on success and non-zero on failure
Implements BaseModule.
Definition at line 105 of file MakeAnalysedPulses.cpp.
References BaseModule::Debug(), EventNavigator::EntryNo(), fGenerators, TGlobalData::fPulseIslandToChannelMap, gAnalysedPulseMap, EventNavigator::Instance(), and IDs::channel::str().
{
    // Generator just receives a bunch of TPIs and must return a list of TAPs
    // Loop over each generator
    IDs::channel detector;
    PulseIslandList* thePulseIslands;
    ChannelGenerators_t::iterator generator;
    AnalysedPulseList theAnalysedPulses;
    int retVal=0;
    for(generator = fGenerators.begin(); generator != fGenerators.end(); generator++){
        // Get the bank name
        detector = (*generator)->GetChannel().str();
        // Get the TPIs
        thePulseIslands=&gData->fPulseIslandToChannelMap[(*generator)->GetBank()];
        if(thePulseIslands->empty() ){
          if( Debug()) cout << "Event No: "
                            << EventNavigator::Instance().EntryNo()
                            <<": List of TPIs for '"<< detector
                            <<"' was empty "<< endl;
          continue;
        }
        // clear the list of analyse_pulses from the last iteration
        theAnalysedPulses.clear();
        // generate the new list of analyse_pulses
        (*generator)->SetPulseList(thePulseIslands);
        retVal=(*generator)->ProcessPulses( *thePulseIslands,theAnalysedPulses);
        if(retVal!=0) return retVal;
        // find the pulse list in gAnalysedPulseMap
        SourceAnalPulseMap::iterator it=gAnalysedPulseMap.find((*generator)->GetSource());
        if(it==gAnalysedPulseMap.end()){
            // source doesn't seem to exist in gAnalysedPulseMap
          cout <<"Error: New TAP source \"" << (*generator)->GetSource()
               <<"\" seems to have been created during processing of pulses."
               <<endl;
            return 1;
        }
        // add the pulses into the map
        it->second=theAnalysedPulses;
        (*generator)->CalibratePulses(it->second);
    }
    return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
void MakeAnalysedPulses::SetAnalysedPulseMap (StringAnalPulseMap & aMap) [inline]
Definition at line 29 of file MakeAnalysedPulses.h.
References fAnalysedPulseMap.
{fAnalysedPulseMap=&aMap;}
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
StringAnalPulseMap* MakeAnalysedPulses::fAnalysedPulseMap [private]
Definition at line 38 of file MakeAnalysedPulses.h.
Referenced by SetAnalysedPulseMap().
std::vector<std::string> MakeAnalysedPulses::fChannelsToAnalyse [private]
Definition at line 41 of file MakeAnalysedPulses.h.
Referenced by BeforeFirstEntry(), and MakeAnalysedPulses().
TAPGeneratorOptions* MakeAnalysedPulses::fDefaultOpts [private]
Definition at line 43 of file MakeAnalysedPulses.h.
Referenced by AddGenerator(), and MakeAnalysedPulses().
std::string MakeAnalysedPulses::fFastGeneratorType [private]
Definition at line 40 of file MakeAnalysedPulses.h.
Referenced by AddGenerator().
ChannelGenerators_t MakeAnalysedPulses::fGenerators [private]
Definition at line 37 of file MakeAnalysedPulses.h.
Referenced by AddGenerator(), BeforeFirstEntry(), and ProcessEntry().
modules::options* MakeAnalysedPulses::fOptions [private]
Definition at line 42 of file MakeAnalysedPulses.h.
Referenced by BeforeFirstEntry().
std::string MakeAnalysedPulses::fSlowGeneratorType [private]
Definition at line 39 of file MakeAnalysedPulses.h.
Referenced by AddGenerator().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/MakeAnalysedPulses.h
rootana/src/TAP_generators/MakeAnalysedPulses.cpp