AlcapDAQ: TGaussFitAnalysedPulse Class Reference
TGaussFitAnalysedPulse Class Reference
#include <TGaussFitAnalysedPulse.h>
Public Member Functions
TGaussFitAnalysedPulse ()
Needed by ROOT but not expected to be used.
TGaussFitAnalysedPulse (const IDs::source &sourceID, const TPulseIslandID &parentID, const TPulseIsland *parentTPI)
Construct a TGaussFitAnalysedPulse.
virtual ~TGaussFitAnalysedPulse ()
virtual void Draw (const TH1F *tpi_pulse) const
@brief overload the TAnalysedPulse::Draw method
virtual void Copy (TObject &rhs) const
void Reset (Option_t *o="")
Clear the TAP. This will probably not be used.
Getters
int GetFitStatus () const
double GetChi2 () const
double GetGradient () const
double GetWidth () const
Error_Getters
double GetGradientErr () const
double GetWidthErr () const
double GetTimeErr () const
double GetPedestalErr () const
double GetAmplitudeErr () const
Setters
Set both the value and error for each field
void SetTime (const double &val, const double &err)
void SetAmplitude (const double &val, const double &err)
void SetPedestal (const double &val, const double &err)
void SetGradient (const double &val, const double &err)
void SetWidth (const double &val, const double &err)
void SetChi2 (const double &val)
void SetFitStatus (const double &val)
Getters
TPulseIslandID GetParentID () const
int GetTPILength () const
double GetAmplitude () const
double GetTime () const
double GetIntegral () const
double GetEnergy () const
double GetPedestal () const
double GetTriggerTime () const
const IDs::source & GetSource () const
Setters
The TAP generators will set whatever TAP values it must through these methods. Not all need be set; the default values are obviously unphysical and several Sanity methods are provided to check if a value was set later in the analysis.
void SetParentID (const TPulseIslandID &val)
void SetTPILength (const int &val)
void SetAmplitude (const double &val)
void SetTime (const double &val)
void SetIntegral (const double &val)
void SetEnergy (const double &val)
void SetPedestal (const double &val)
void SetTriggerTime (const double &val)
void SetParentTPIProperties (const TPulseIslandID &id, const TPulseIsland *parent)
Sanity
bool IsParentIDSet () const
bool IsTPILengthSet () const
bool IsAmplitudeSet () const
bool IsTimeSet () const
bool IsIntegralSet () const
bool IsEnergySet () const
bool IsPedestalSet () const
bool IsTriggerTimeSet () const
Private Member Functions
ClassDef (TGaussFitAnalysedPulse, 1)
Private Attributes
int fStatus
double fChi2
double fWidth
double fGradient
double fTimeErr
double fWidthErr
double fAmplitudeErr
double fPedestalErr
double fGradientErr
Detailed Description
Definition at line 7 of file TGaussFitAnalysedPulse.h.
Constructor & Destructor Documentation
TGaussFitAnalysedPulse::TGaussFitAnalysedPulse () [inline]
Needed by ROOT but not expected to be used.
Definition at line 10 of file TGaussFitAnalysedPulse.h.
:TAnalysedPulse(){};
TGaussFitAnalysedPulse::TGaussFitAnalysedPulse (const IDs::source & sourceID, const TPulseIslandID & parentID, const TPulseIsland * parentTPI) [inline]
Construct a TGaussFitAnalysedPulse.
Same signature as for TAnalysedPulse so that MakeNewTAP can create these specialised TAPs
Definition at line 15 of file TGaussFitAnalysedPulse.h.
                                                                              :
            TAnalysedPulse(sourceID,parentID,parentTPI){}
virtual TGaussFitAnalysedPulse::~TGaussFitAnalysedPulse () [inline, virtual]
Definition at line 20 of file TGaussFitAnalysedPulse.h.
{};
Member Function Documentation
TGaussFitAnalysedPulse::ClassDef (TGaussFitAnalysedPulse , 1) [private]
virtual void TAnalysedPulse::Copy (TObject & rhs) const [inline, virtual, inherited]
Reimplemented in TTemplateConvolveAnalysedPulse.
Definition at line 40 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude, TAnalysedPulse::fEnergy, TAnalysedPulse::fIntegral, TAnalysedPulse::fParentID, TAnalysedPulse::fPedestal, TAnalysedPulse::fSource, TAnalysedPulse::fTime, TAnalysedPulse::fTPILength, and TAnalysedPulse::fTriggerTime.
{
    TObject::Copy(rhs);
    if(rhs.InheritsFrom(Class())){
      TAnalysedPulse* tap=static_cast<TAnalysedPulse*>(&rhs);
      tap->fParentID=fParentID;
      tap->fTPILength=fTPILength;
      tap->fAmplitude=fAmplitude;
      tap->fTime=fTime;
      tap->fIntegral=fIntegral;
      tap->fEnergy=fEnergy;
      tap->fPedestal=fPedestal;
      tap->fTriggerTime=fTriggerTime;
      tap->fSource=fSource;
    }
  }
void TGaussFitAnalysedPulse::Draw (const TH1F * tpi_pulse) const [virtual]
@brief overload the TAnalysedPulse::Draw method
Reimplemented from TAnalysedPulse.
Definition at line 6 of file TGaussFitAnalysedPulse.cpp.
References fGradient, fWidth, functions::gauss_lin(), TAnalysedPulse::GetAmplitude(), TAnalysedPulse::GetPedestal(), and TAnalysedPulse::GetTime().
{
        if(tpi_pulse) {
          std::string name=tpi_pulse->GetName();
          TF1* tap_pulse=new TF1((name+"_AP").c_str(),functions::gauss_lin,0,1000,5);
    // parameters:
    // 0: constant (pedestal)
    // 1: gradient
    // 2: Gauss amplitude
    // 3: Gauss mean
    // 4: Gauss width
      tap_pulse->SetParameters(GetPedestal(),fGradient,GetAmplitude(),GetTime(),fWidth);
      tap_pulse->Draw();
      tap_pulse->Write();
        }
}
double TAnalysedPulse::GetAmplitude () const [inline, inherited]
Definition at line 100 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude.
Referenced by TTemplateFitAnalysedPulse::Draw(), TTemplateConvolveAnalysedPulse::Draw(), Draw(), TTemplateFitAnalysedPulse::GetBinContent(), PulseViewer::GetParameterValue(), PlotTAP_selfCorrelation::PassesCutA(), TemplateFitAPGenerator::RefitWithTwo(), and TTemplateFitAnalysedPulse::SetAmplitudeScaleFactor().
{return fAmplitude;};
double TGaussFitAnalysedPulse::GetAmplitudeErr () const [inline]
Definition at line 36 of file TGaussFitAnalysedPulse.h.
References fAmplitudeErr.
{return fAmplitudeErr;}
double TGaussFitAnalysedPulse::GetChi2 () const [inline]
Definition at line 25 of file TGaussFitAnalysedPulse.h.
References fChi2.
{return fChi2;}
double TAnalysedPulse::GetEnergy () const [inline, inherited]
Definition at line 103 of file TAnalysedPulse.h.
References TAnalysedPulse::fEnergy.
Referenced by PulseViewer::GetParameterValue(), and TME_Al50_EvdE::ProcessEntry().
{return fEnergy;};
int TGaussFitAnalysedPulse::GetFitStatus () const [inline]
Definition at line 24 of file TGaussFitAnalysedPulse.h.
References fStatus.
{return fStatus;}
double TGaussFitAnalysedPulse::GetGradient () const [inline]
Definition at line 26 of file TGaussFitAnalysedPulse.h.
References fGradient.
{return fGradient;}
double TGaussFitAnalysedPulse::GetGradientErr () const [inline]
Definition at line 32 of file TGaussFitAnalysedPulse.h.
References fGradientErr.
{return fGradientErr;}
double TAnalysedPulse::GetIntegral () const [inline, inherited]
Definition at line 102 of file TAnalysedPulse.h.
References TAnalysedPulse::fIntegral.
Referenced by PulseViewer::GetParameterValue(), and PlotIntegralRatios::ProcessEntry().
{return fIntegral;};
TPulseIslandID TAnalysedPulse::GetParentID () const [inline, inherited]
Definition at line 98 of file TAnalysedPulse.h.
References TAnalysedPulse::fParentID.
Referenced by ExportPulse::AddToExportList(), TTemplateFitAnalysedPulse::GetHisto(), and TemplateFitAPGenerator::RefitWithTwo().
{return fParentID;};
double TAnalysedPulse::GetPedestal () const [inline, inherited]
Definition at line 104 of file TAnalysedPulse.h.
References TAnalysedPulse::fPedestal.
Referenced by TTemplateConvolveAnalysedPulse::Draw(), Draw(), TTemplateFitAnalysedPulse::GetBinContent(), PulseViewer::GetParameterValue(), and TemplateFitAPGenerator::RefitWithTwo().
{return fPedestal;};
double TGaussFitAnalysedPulse::GetPedestalErr () const [inline]
Definition at line 35 of file TGaussFitAnalysedPulse.h.
References fPedestalErr.
{return fPedestalErr;}
const IDs::source& TAnalysedPulse::GetSource () const [inline, inherited]
Definition at line 106 of file TAnalysedPulse.h.
References TAnalysedPulse::fSource, and FlyWeight< ValueType, UniqueTag >::GetValue().
Referenced by ExportPulse::AddToExportList(), TTemplateConvolveAnalysedPulse::Draw(), TTemplateFitAnalysedPulse::GetHisto(), MaxTimeDiffDPGenerator::ProcessPulses(), and TDetectorPulse::TDetectorPulse().
{return fSource.GetValue();};
double TAnalysedPulse::GetTime () const [inline, inherited]
Definition at line 101 of file TAnalysedPulse.h.
References TAnalysedPulse::fTime.
Referenced by TTemplateFitAnalysedPulse::Draw(), TTemplateConvolveAnalysedPulse::Draw(), Draw(), TTemplateFitAnalysedPulse::GetBinContent(), PulseViewer::GetParameterValue(), TemplateFitAPGenerator::InitializeSecondPulse(), IsTimeOrdered(), MaxTimeDiffDPGenerator::ProcessPulses(), TemplateFitAPGenerator::RefitWithTwo(), and TTemplateFitAnalysedPulse::SetTimeOffset().
{return fTime;};
double TGaussFitAnalysedPulse::GetTimeErr () const [inline]
Definition at line 34 of file TGaussFitAnalysedPulse.h.
References fTimeErr.
{return fTimeErr;}
int TAnalysedPulse::GetTPILength () const [inline, inherited]
Definition at line 99 of file TAnalysedPulse.h.
References TAnalysedPulse::fTPILength.
Referenced by TTemplateFitAnalysedPulse::GetHisto(), and PulseViewer::GetParameterValue().
{return fTPILength;};
double TAnalysedPulse::GetTriggerTime () const [inline, inherited]
Definition at line 105 of file TAnalysedPulse.h.
References TAnalysedPulse::fTriggerTime.
Referenced by PulseViewer::GetParameterValue().
{return fTriggerTime;};
double TGaussFitAnalysedPulse::GetWidth () const [inline]
Definition at line 27 of file TGaussFitAnalysedPulse.h.
References fWidth.
{return fWidth;}
double TGaussFitAnalysedPulse::GetWidthErr () const [inline]
Definition at line 33 of file TGaussFitAnalysedPulse.h.
References fWidthErr.
{return fWidthErr;}
bool TAnalysedPulse::IsAmplitudeSet () const [inline, inherited]
Definition at line 135 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude, and TAnalysedPulse::fDefaultValue.
{return fAmplitude!=fDefaultValue;};
bool TAnalysedPulse::IsEnergySet () const [inline, inherited]
Definition at line 138 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fEnergy.
{return fEnergy!=fDefaultValue;};
bool TAnalysedPulse::IsIntegralSet () const [inline, inherited]
Definition at line 137 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fIntegral.
{return fIntegral!=fDefaultValue;};
bool TAnalysedPulse::IsParentIDSet () const [inline, inherited]
Definition at line 133 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fParentID.
{return fParentID!=fDefaultValue;};
bool TAnalysedPulse::IsPedestalSet () const [inline, inherited]
Definition at line 139 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fPedestal.
{return fPedestal!=fDefaultValue;};
bool TAnalysedPulse::IsTimeSet () const [inline, inherited]
Definition at line 136 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTime.
{return fTime!=fDefaultValue;};
bool TAnalysedPulse::IsTPILengthSet () const [inline, inherited]
Definition at line 134 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTPILength.
{return fTPILength!=fDefaultValue;};
bool TAnalysedPulse::IsTriggerTimeSet () const [inline, inherited]
Definition at line 140 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTriggerTime.
{return fTriggerTime!=fDefaultValue;};
void TAnalysedPulse::Reset (Option_t * o = "") [inherited]
Clear the TAP. This will probably not be used.
Definition at line 42 of file TAnalysedPulse.cpp.
References TAnalysedPulse::fAmplitude, TAnalysedPulse::fDefaultValue, TAnalysedPulse::fEnergy, TAnalysedPulse::fIntegral, TAnalysedPulse::fParentID, TAnalysedPulse::fPedestal, TAnalysedPulse::fTime, TAnalysedPulse::fTPILength, and TAnalysedPulse::fTriggerTime.
{
  fParentID=fDefaultValue;
  fTPILength=fDefaultValue;
  fAmplitude=fDefaultValue;
  fTime=fDefaultValue;
  fIntegral=fDefaultValue;
  fEnergy=fDefaultValue;
  fPedestal=fDefaultValue;
  fTriggerTime=fDefaultValue;
}
void TAnalysedPulse::SetAmplitude (const double & val) [inline, inherited]
Definition at line 120 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateConvolveAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), IntegralRatioAPGenerator::ProcessPulses(), and CFTimeMBAmpAPGenerator::ProcessPulses().
{ fAmplitude=val;};
void TGaussFitAnalysedPulse::SetAmplitude (const double & val, const double & err) [inline]
Definition at line 43 of file TGaussFitAnalysedPulse.h.
References fAmplitudeErr.
Referenced by GaussFitAPGenerator::ProcessPulses().
{TAnalysedPulse::SetAmplitude(val); fAmplitudeErr=err;}
void TGaussFitAnalysedPulse::SetChi2 (const double & val) [inline]
Definition at line 47 of file TGaussFitAnalysedPulse.h.
References fChi2.
Referenced by GaussFitAPGenerator::ProcessPulses().
{fChi2=val;}
void TAnalysedPulse::SetEnergy (const double & val) [inline, inherited]
Definition at line 123 of file TAnalysedPulse.h.
References TAnalysedPulse::fEnergy.
{ fEnergy=val;};
void TGaussFitAnalysedPulse::SetFitStatus (const double & val) [inline]
Definition at line 48 of file TGaussFitAnalysedPulse.h.
References fStatus.
Referenced by GaussFitAPGenerator::ProcessPulses().
{fStatus=val;}
void TGaussFitAnalysedPulse::SetGradient (const double & val, const double & err) [inline]
Definition at line 45 of file TGaussFitAnalysedPulse.h.
References fGradient, and fGradientErr.
Referenced by GaussFitAPGenerator::ProcessPulses().
{fGradient=val; fGradientErr=err;}
void TAnalysedPulse::SetIntegral (const double & val) [inline, inherited]
Definition at line 122 of file TAnalysedPulse.h.
References TAnalysedPulse::fIntegral.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateFitAPGenerator::ProcessPulses(), TemplateConvolveAPGenerator::ProcessPulses(), SimpIntAPGenerator::ProcessPulses(), and IntegralRatioAPGenerator::ProcessPulses().
{ fIntegral=val;};
void TAnalysedPulse::SetParentID (const TPulseIslandID & val) [inline, inherited]
Definition at line 118 of file TAnalysedPulse.h.
References TAnalysedPulse::fParentID.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fParentID=val;};
void TAnalysedPulse::SetParentTPIProperties (const TPulseIslandID & id, const TPulseIsland * parent) [inherited]
Definition at line 65 of file TAnalysedPulse.cpp.
References TPulseIsland::GetClockTickInNs(), TPulseIsland::GetPulseLength(), TPulseIsland::GetTimeStamp(), TAnalysedPulse::SetParentID(), TAnalysedPulse::SetTPILength(), and TAnalysedPulse::SetTriggerTime().
Referenced by TAnalysedPulse::TAnalysedPulse().
{
  SetParentID(id);
  if(!pulse) {
    std::cerr<<"NULL pointer to TPulseIsland passed as parent for TAnalysedPulse."<<std::endl;
    return;
  }
  SetTPILength(pulse->GetPulseLength());
  SetTriggerTime(pulse->GetTimeStamp()*pulse->GetClockTickInNs());
}
void TAnalysedPulse::SetPedestal (const double & val) [inline, inherited]
Definition at line 124 of file TAnalysedPulse.h.
References TAnalysedPulse::fPedestal.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{ fPedestal=val;};
void TGaussFitAnalysedPulse::SetPedestal (const double & val, const double & err) [inline]
Definition at line 44 of file TGaussFitAnalysedPulse.h.
References fPedestalErr.
Referenced by GaussFitAPGenerator::ProcessPulses().
{TAnalysedPulse::SetPedestal(val); fPedestalErr=err;}
void TAnalysedPulse::SetTime (const double & val) [inline, inherited]
Definition at line 121 of file TAnalysedPulse.h.
References TAnalysedPulse::fTime.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateConvolveAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), IntegralRatioAPGenerator::ProcessPulses(), CFTimeMBAmpAPGenerator::ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{ fTime=val;};
void TGaussFitAnalysedPulse::SetTime (const double & val, const double & err) [inline]
Definition at line 42 of file TGaussFitAnalysedPulse.h.
References fTimeErr.
{TAnalysedPulse::SetTime(val); fTimeErr=err;}
void TAnalysedPulse::SetTPILength (const int & val) [inline, inherited]
Definition at line 119 of file TAnalysedPulse.h.
References TAnalysedPulse::fTPILength.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fTPILength=val;};
void TAnalysedPulse::SetTriggerTime (const double & val) [inline, inherited]
Definition at line 125 of file TAnalysedPulse.h.
References TAnalysedPulse::fTriggerTime.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fTriggerTime=val;};
void TGaussFitAnalysedPulse::SetWidth (const double & val, const double & err) [inline]
Definition at line 46 of file TGaussFitAnalysedPulse.h.
References fWidth, and fWidthErr.
Referenced by GaussFitAPGenerator::ProcessPulses().
{fWidth=val; fWidthErr=err;}
Member Data Documentation
double TGaussFitAnalysedPulse::fAmplitudeErr [private]
Definition at line 57 of file TGaussFitAnalysedPulse.h.
Referenced by GetAmplitudeErr(), and SetAmplitude().
double TGaussFitAnalysedPulse::fChi2 [private]
Definition at line 56 of file TGaussFitAnalysedPulse.h.
Referenced by GetChi2(), and SetChi2().
double TGaussFitAnalysedPulse::fGradient [private]
Definition at line 56 of file TGaussFitAnalysedPulse.h.
Referenced by Draw(), GetGradient(), and SetGradient().
double TGaussFitAnalysedPulse::fGradientErr [private]
Definition at line 57 of file TGaussFitAnalysedPulse.h.
Referenced by GetGradientErr(), and SetGradient().
double TGaussFitAnalysedPulse::fPedestalErr [private]
Definition at line 57 of file TGaussFitAnalysedPulse.h.
Referenced by GetPedestalErr(), and SetPedestal().
int TGaussFitAnalysedPulse::fStatus [private]
Definition at line 55 of file TGaussFitAnalysedPulse.h.
Referenced by GetFitStatus(), and SetFitStatus().
double TGaussFitAnalysedPulse::fTimeErr [private]
Definition at line 57 of file TGaussFitAnalysedPulse.h.
Referenced by GetTimeErr(), and SetTime().
double TGaussFitAnalysedPulse::fWidth [private]
Definition at line 56 of file TGaussFitAnalysedPulse.h.
Referenced by Draw(), GetWidth(), and SetWidth().
double TGaussFitAnalysedPulse::fWidthErr [private]
Definition at line 57 of file TGaussFitAnalysedPulse.h.
Referenced by GetWidthErr(), and SetWidth().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/TGaussFitAnalysedPulse.h
rootana/src/TAP_generators/TGaussFitAnalysedPulse.cpp