AlcapDAQ: PlotTME_activeSiRmuStops Class Reference
PlotTME_activeSiRmuStops Class Reference
[Modules]
Produce various plots that characterise the produced TMuonEvents.
#include <PlotTME_activeSiRmuStops.h>
Public Member Functions
PlotTME_activeSiRmuStops (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~PlotTME_activeSiRmuStops ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
void FillHistograms (const TMuonEvent *tme, const IDs::source &muSc_source, const IDs::source &siR2_source)
Private Attributes
long int fStoppedMus
long int fStoppedMus_PP
long int fNStopsThisEvent
long int fNStopsThisEvent_PP
long int fEventNo
IDs::channel fMuSc
IDs::channel fSiR2
TDetectorPulse::ParentChannel_t fChannel
double fMuScMax
double fMuScMin
double fSiR2Max
double fSiR2Min
TMEAlgorithm::ActiveSiRStop * fHasStoppedMuon
TH1F * fTDiff_PP
TH1F * fTDiff
TH1F * fTDiffMuons
TH1F * fTDiffMuons_PP
TH1F * fStopsPerEvent
TH1F * fStopsPerEvent_PP
TH1F * fStops
TH1F * fStops_PP
TH2F * fAmplitudes
TH2F * fAmplitudes_PP
TH2F * fTDiffVsAmpSiR2
TH2F * fTDiffVsAmpSiR2_PP
TH2F * fTDiffVsAmpSiR2_MuStop
TH2F * fTDiffVsAmpSiR2_MuStop_PP
Detailed Description
Produce various plots that characterise the produced TMuonEvents.
Author:
Ben Krikler
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 29 of file PlotTME_activeSiRmuStops.h.
Constructor & Destructor Documentation
PlotTME_activeSiRmuStops::PlotTME_activeSiRmuStops (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 22 of file PlotTME_activeSiRmuStops.cpp.
References DEBUG_VALUE, fChannel, fMuSc, and fSiR2.
                                                                      :
   BaseModule("PlotTME_activeSiRmuStops",opts),
   fStoppedMus(0),fStoppedMus_PP(0), fNStopsThisEvent(0),fNStopsThisEvent_PP(0), fEventNo(1),
   fMuSc(opts->GetString("second","muSc")),
   fSiR2(opts->GetString("first","SiR2")),
   fChannel((TDetectorPulse::ParentChannel_t) (IDs::channel::GetSlowFastEnum(opts->GetString("channel","fast"))-IDs::kFast)),
   fMuScMax(opts->GetDouble("muSc_max",1e9)),
   fMuScMin(opts->GetDouble("muSc_min",0)),
   fSiR2Max(opts->GetDouble("SiR2_max",1e9)),
   fSiR2Min(opts->GetDouble("SiR2_min",0)),
   fHasStoppedMuon(new TMEAlgorithm::ActiveSiRStop(IDs::source(),fMuScMin,fMuScMax,fSiR2Min,fSiR2Max))
{
DEBUG_VALUE(fMuSc, fSiR2,fChannel);
}
PlotTME_activeSiRmuStops::~PlotTME_activeSiRmuStops ()
Is anything done in the destructor?
Definition at line 37 of file PlotTME_activeSiRmuStops.cpp.
References fHasStoppedMuon.
{
  if(fHasStoppedMuon) delete fHasStoppedMuon;
}
Member Function Documentation
int PlotTME_activeSiRmuStops::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 180 of file PlotTME_activeSiRmuStops.cpp.
References fAmplitudes, fAmplitudes_PP, fMuScMax, fMuScMin, fStoppedMus, and fTDiffVsAmpSiR2_MuStop_PP.
{
  double y_min=fAmplitudes->GetYaxis()->GetXmin();
  double y_max=fAmplitudes->GetYaxis()->GetXmax();
  TLine* muSc_cut=new TLine(fMuScMin, y_min, fMuScMin, y_max);
  muSc_cut->SetLineColor(kRed);
  fAmplitudes->GetListOfFunctions()->Add(muSc_cut->Clone());
  fAmplitudes_PP->GetListOfFunctions()->Add(muSc_cut->Clone());
  muSc_cut->SetX1(fMuScMax);
  muSc_cut->SetX2(fMuScMax);
  fAmplitudes->GetListOfFunctions()->Add(muSc_cut->Clone());
  fAmplitudes_PP->GetListOfFunctions()->Add(muSc_cut->Clone());
  fTDiffVsAmpSiR2_MuStop_PP->ProjectionY("_py",236);
  cout<<"PlotTME_activeSiRmuStops::AfterLastEntry: Total number of muon stops = "<<fStoppedMus<<endl;
  return 0;
}
int PlotTME_activeSiRmuStops::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 41 of file PlotTME_activeSiRmuStops.cpp.
References fAmplitudes, fAmplitudes_PP, fStops, fStops_PP, fStopsPerEvent, fStopsPerEvent_PP, fTDiff, fTDiff_PP, fTDiffMuons, fTDiffMuons_PP, fTDiffVsAmpSiR2, fTDiffVsAmpSiR2_MuStop_PP, fTDiffVsAmpSiR2_PP, EventNavigator::GetLoopNEntries(), EventNavigator::GetStartEntry(), EventNavigator::GetStopEntry(), and EventNavigator::Instance().
{
    fTDiff=new TH1F("hTDiff", "TDiff of SiR2 hits compared to muSc (with pile-up)", 5000, -1.2e4,1.2e4);
    fTDiff->SetXTitle("t_{SiR2} - t_{muSc} (ns)");
    fTDiff_PP=new TH1F("hTDiff_PP", "TDiff of SiR2 hits compared to muSc (pile-up protected)", 5000, -1.2e4,1.2e4);
    fTDiff_PP->SetXTitle(fTDiff->GetXaxis()->GetTitle());
    fTDiffMuons=new TH1F("hTDiffMuons", "TDiff of muons considered to have stopped (with pile-up)", 5000, -1.2e4,1.2e4);
    fTDiffMuons->SetXTitle("t_{SiR2} - t_{muSc} (ns)");
    fTDiffMuons_PP=new TH1F("hTDiffMuons_PP", "TDiff of muons considered to have stopped (pile-up protected)", 5000, -1.2e4,1.2e4);
    fTDiffMuons_PP->SetXTitle(fTDiffMuons->GetXaxis()->GetTitle());
    fTDiffVsAmpSiR2=new TH2F("hTDiffVsAmpSiR2",
                             "Amplitudes of SiR2 hits (with pile-up) against the time difference compared to muSc ",
                              400, -1.1e4, 1.1e4, 400,0,4000);
    fTDiffVsAmpSiR2->SetXTitle(fTDiff->GetXaxis()->GetTitle());
    fTDiffVsAmpSiR2->SetYTitle("Amplitude in SiR2 (ADC units)");
    fTDiffVsAmpSiR2_PP=new TH2F("hTDiffVsAmpSiR2_PP",
                             "Amplitudes of SiR2 hits (pile-up protected) against the time diference compared to muSc",
                              400, -1.1e4, 1.1e4, 400,0,4000);
    fTDiffVsAmpSiR2_PP->SetXTitle(fTDiffVsAmpSiR2->GetXaxis()->GetTitle());
    fTDiffVsAmpSiR2_PP->SetYTitle(fTDiffVsAmpSiR2->GetYaxis()->GetTitle());
    //fTDiffVsAmpSiR2_MuStop=new TH2F("hTDiffVsAmpSiR2_MuStop",
    //                                "Amplitudes of SiR2 hits compared to muSc (with pile-up) against the time diference",
    //                                 400, -1.1e4, 1.1e4, 400,0,4000);
    //fTDiffVsAmpSiR2_MuStop->SetXTitle(fTDiff->GetXaxis()->GetTitle());
    //fTDiffVsAmpSiR2_MuStop->SetYTitle("Amplitude in SiR2 (ADC units)");
    fTDiffVsAmpSiR2_MuStop_PP=new TH2F("hTDiffVsAmpSiR2_MuStop_PP",
                                    "Amplitudes of SiR2 hits compared to muSc (pile-up protected) against the time diference",
                                     400, -1.1e4, 1.1e4, 400,0,4000);
    fTDiffVsAmpSiR2_MuStop_PP->SetXTitle(fTDiffVsAmpSiR2->GetXaxis()->GetTitle());
    fTDiffVsAmpSiR2_MuStop_PP->SetYTitle(fTDiffVsAmpSiR2->GetYaxis()->GetTitle());
    fAmplitudes=new TH2F("hAmp2d", "Amplitudes of SiR2 hits compared to muSc (with pile-up)", 400, 0,4000, 400,0,4000);
    fAmplitudes->SetXTitle("Amplitude in muSc (ADC units)");
    fAmplitudes->SetYTitle("Amplitude in SiR2 (ADC units)");
    fAmplitudes_PP=new TH2F("hAmp2d_PP", "Amplitudes of SiR2 hits compared to muSc (pile-up protected)", 400, 0,4000, 400,0,4000);
    fAmplitudes_PP->SetXTitle(fAmplitudes->GetXaxis()->GetTitle());
    fAmplitudes_PP->SetYTitle(fAmplitudes->GetYaxis()->GetTitle());
    const EventNavigator& event_ngtr= EventNavigator::Instance();
    fStopsPerEvent=new TH1F("hStoppedPerEvent","Number of #mu stops per midas event (with pile-up)",
                  event_ngtr.GetLoopNEntries(), event_ngtr.GetStartEntry(), event_ngtr.GetStopEntry());
    fStopsPerEvent->SetXTitle("Event Number");
    fStopsPerEvent->SetYTitle("Number of #mu stops");
    fStopsPerEvent_PP=new TH1F("hStoppedPerEvent_PP","Number of #mu stops per midas event (pile-up protected)",
                  event_ngtr.GetLoopNEntries(), event_ngtr.GetStartEntry(), event_ngtr.GetStopEntry());
    fStopsPerEvent_PP->SetXTitle("Event Number");
    fStopsPerEvent_PP->SetYTitle("Number of #mu stops");
    fStops=new TH1F("hStopped","Number of #mu stops per midas event (pile-up protected)", 250, 0, 250);
    fStops->SetXTitle("Number of #mu stops");
    fStops_PP=new TH1F("hStopped_PP","Number of #mu stops per midas event (pile-up protected)", 250, 0, 250);
    fStops_PP->SetXTitle("Number of #mu stops");
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
void PlotTME_activeSiRmuStops::FillHistograms (const TMuonEvent * tme, const IDs::source & muSc_source, const IDs::source & siR2_source) [private]
Definition at line 137 of file PlotTME_activeSiRmuStops.cpp.
References fAmplitudes, fAmplitudes_PP, fChannel, fHasStoppedMuon, fMuScMax, fMuScMin, fNStopsThisEvent, fNStopsThisEvent_PP, fTDiff, fTDiff_PP, fTDiffMuons_PP, fTDiffVsAmpSiR2, fTDiffVsAmpSiR2_MuStop_PP, fTDiffVsAmpSiR2_PP, TDetectorPulse::GetAmplitude(), TMuonEvent::GetCentralMuon(), TDetectorPulse::GetTime(), TMuonEvent::GetTime(), TDetectorPulse::kFast, TMuonEvent::NumPulses(), and TMEAlgorithm::ActiveSiRStop::SetSiR2Source().
Referenced by ProcessEntry().
{
  //check if we pass the muSc muon cut
  const double muSc_amp=tme->GetCentralMuon()->GetAmplitude(TDetectorPulse::kFast);
  const double time=tme->GetTime();
  const int N_muSc=tme->NumPulses(muSc_source);
  const int N_sir2=tme->NumPulses(sir2_source);
  // Scan for a muon hit in the SiR2
  fHasStoppedMuon->SetSiR2Source(sir2_source);
  bool a_stop=(*fHasStoppedMuon)(tme,fChannel);
  if(a_stop) {
    ++fNStopsThisEvent;
    if(!tme->HasMuonPileup()) ++fNStopsThisEvent_PP;
  }
  // Fill all plots for SiR2
  for(int i=0; i< N_sir2; ++i){
    const TDetectorPulse* sir2_tdp=tme->GetPulse(sir2_source,i);
    const double t_diff=sir2_tdp->GetTime(fChannel) - time;
    const double sir2_amp=sir2_tdp->GetAmplitude(fChannel);
    fTDiff->Fill(t_diff);
    fTDiffVsAmpSiR2->Fill(t_diff, sir2_amp );
    if(!tme->HasMuonPileup()){
      if(muSc_amp>fMuScMin && muSc_amp< fMuScMax){
         fTDiff_PP->Fill(t_diff);
         fTDiffVsAmpSiR2_PP->Fill(t_diff, sir2_amp );
         if(a_stop){
           fTDiffMuons_PP->Fill(t_diff);
           fTDiffVsAmpSiR2_MuStop_PP->Fill(t_diff,sir2_amp);
         }
      }
    }
    for(int j=0; j< N_muSc; ++j){
      const double muSc_amp=tme->GetPulse(muSc_source,j)->GetAmplitude(TDetectorPulse::kFast);
      fAmplitudes->Fill(muSc_amp, sir2_amp );
      if(!tme->HasMuonPileup()){
         fAmplitudes_PP->Fill(muSc_amp, sir2_amp );
      }
    }
  }
}
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int PlotTME_activeSiRmuStops::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 103 of file PlotTME_activeSiRmuStops.cpp.
References fEventNo, FillHistograms(), fMuSc, fNStopsThisEvent, fNStopsThisEvent_PP, fSiR2, fStoppedMus, fStoppedMus_PP, fStops, fStops_PP, fStopsPerEvent, fStopsPerEvent_PP, and gMuonEvents.
{
    // Reset the number of mu stops in the event
    fNStopsThisEvent=0;
    fNStopsThisEvent_PP=0;
    // Loop over each TME
    for(MuonEventList::const_iterator i_tme=gMuonEvents.begin();
            i_tme!=gMuonEvents.end(); ++i_tme){
       // Loop over each muSc source
       for(int muSc_source_index = (*i_tme)->GetFirstSourceIndex(fMuSc);
               muSc_source_index < (*i_tme)->GetLastSourceIndex(fMuSc)
                  && muSc_source_index > -1; ++muSc_source_index){
         const IDs::source& muSc_source=(*i_tme)->GetSource(muSc_source_index);
         // Loop over each SiR2 source
         for(int siR2_source_index = (*i_tme)->GetFirstSourceIndex(fSiR2);
                 siR2_source_index < (*i_tme)->GetLastSourceIndex(fSiR2)
                    && siR2_source_index > -1; ++siR2_source_index){
           const IDs::source& siR2_source=(*i_tme)->GetSource(siR2_source_index);
           // Fill histograms from the various sources
           FillHistograms(*i_tme, muSc_source, siR2_source);
         } // loop over SiR2 sources
       } // loop over muSc sources
    } // loop over each TME
    fStopsPerEvent->Fill(fEventNo, fNStopsThisEvent);
    fStopsPerEvent_PP->Fill(fEventNo, fNStopsThisEvent_PP);
    fStops->Fill( fNStopsThisEvent);
    fStops_PP->Fill( fNStopsThisEvent_PP);
    ++fEventNo;
    fStoppedMus+=fNStopsThisEvent;
    fStoppedMus_PP+=fNStopsThisEvent_PP;
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
TH2F* PlotTME_activeSiRmuStops::fAmplitudes [private]
Definition at line 76 of file PlotTME_activeSiRmuStops.h.
Referenced by AfterLastEntry(), BeforeFirstEntry(), and FillHistograms().
TH2F * PlotTME_activeSiRmuStops::fAmplitudes_PP [private]
Definition at line 76 of file PlotTME_activeSiRmuStops.h.
Referenced by AfterLastEntry(), BeforeFirstEntry(), and FillHistograms().
TDetectorPulse::ParentChannel_t PlotTME_activeSiRmuStops::fChannel [private]
Definition at line 69 of file PlotTME_activeSiRmuStops.h.
Referenced by FillHistograms(), and PlotTME_activeSiRmuStops().
long int PlotTME_activeSiRmuStops::fEventNo [private]
Definition at line 66 of file PlotTME_activeSiRmuStops.h.
Referenced by ProcessEntry().
TMEAlgorithm::ActiveSiRStop* PlotTME_activeSiRmuStops::fHasStoppedMuon [private]
Definition at line 73 of file PlotTME_activeSiRmuStops.h.
Referenced by FillHistograms(), and ~PlotTME_activeSiRmuStops().
IDs::channel PlotTME_activeSiRmuStops::fMuSc [private]
Definition at line 68 of file PlotTME_activeSiRmuStops.h.
Referenced by PlotTME_activeSiRmuStops(), and ProcessEntry().
double PlotTME_activeSiRmuStops::fMuScMax [private]
Definition at line 71 of file PlotTME_activeSiRmuStops.h.
Referenced by AfterLastEntry(), and FillHistograms().
double PlotTME_activeSiRmuStops::fMuScMin [private]
Definition at line 71 of file PlotTME_activeSiRmuStops.h.
Referenced by AfterLastEntry(), and FillHistograms().
long int PlotTME_activeSiRmuStops::fNStopsThisEvent [private]
Definition at line 65 of file PlotTME_activeSiRmuStops.h.
Referenced by FillHistograms(), and ProcessEntry().
long int PlotTME_activeSiRmuStops::fNStopsThisEvent_PP [private]
Definition at line 65 of file PlotTME_activeSiRmuStops.h.
Referenced by FillHistograms(), and ProcessEntry().
IDs::channel PlotTME_activeSiRmuStops::fSiR2 [private]
Definition at line 68 of file PlotTME_activeSiRmuStops.h.
Referenced by PlotTME_activeSiRmuStops(), and ProcessEntry().
double PlotTME_activeSiRmuStops::fSiR2Max [private]
Definition at line 71 of file PlotTME_activeSiRmuStops.h.
double PlotTME_activeSiRmuStops::fSiR2Min [private]
Definition at line 71 of file PlotTME_activeSiRmuStops.h.
long int PlotTME_activeSiRmuStops::fStoppedMus [private]
Definition at line 64 of file PlotTME_activeSiRmuStops.h.
Referenced by AfterLastEntry(), and ProcessEntry().
long int PlotTME_activeSiRmuStops::fStoppedMus_PP [private]
Definition at line 64 of file PlotTME_activeSiRmuStops.h.
Referenced by ProcessEntry().
TH1F * PlotTME_activeSiRmuStops::fStops [private]
Definition at line 75 of file PlotTME_activeSiRmuStops.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
TH1F * PlotTME_activeSiRmuStops::fStops_PP [private]
Definition at line 75 of file PlotTME_activeSiRmuStops.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
TH1F * PlotTME_activeSiRmuStops::fStopsPerEvent [private]
Definition at line 75 of file PlotTME_activeSiRmuStops.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
TH1F * PlotTME_activeSiRmuStops::fStopsPerEvent_PP [private]
Definition at line 75 of file PlotTME_activeSiRmuStops.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
TH1F * PlotTME_activeSiRmuStops::fTDiff [private]
Definition at line 75 of file PlotTME_activeSiRmuStops.h.
Referenced by BeforeFirstEntry(), and FillHistograms().
TH1F* PlotTME_activeSiRmuStops::fTDiff_PP [private]
Definition at line 75 of file PlotTME_activeSiRmuStops.h.
Referenced by BeforeFirstEntry(), and FillHistograms().
TH1F * PlotTME_activeSiRmuStops::fTDiffMuons [private]
Definition at line 75 of file PlotTME_activeSiRmuStops.h.
Referenced by BeforeFirstEntry().
TH1F * PlotTME_activeSiRmuStops::fTDiffMuons_PP [private]
Definition at line 75 of file PlotTME_activeSiRmuStops.h.
Referenced by BeforeFirstEntry(), and FillHistograms().
TH2F * PlotTME_activeSiRmuStops::fTDiffVsAmpSiR2 [private]
Definition at line 76 of file PlotTME_activeSiRmuStops.h.
Referenced by BeforeFirstEntry(), and FillHistograms().
TH2F * PlotTME_activeSiRmuStops::fTDiffVsAmpSiR2_MuStop [private]
Definition at line 76 of file PlotTME_activeSiRmuStops.h.
TH2F * PlotTME_activeSiRmuStops::fTDiffVsAmpSiR2_MuStop_PP [private]
Definition at line 76 of file PlotTME_activeSiRmuStops.h.
Referenced by AfterLastEntry(), BeforeFirstEntry(), and FillHistograms().
TH2F * PlotTME_activeSiRmuStops::fTDiffVsAmpSiR2_PP [private]
Definition at line 76 of file PlotTME_activeSiRmuStops.h.
Referenced by BeforeFirstEntry(), and FillHistograms().
The documentation for this class was generated from the following files:
rootana/src/plotters/PlotTME_activeSiRmuStops.h
rootana/src/plotters/PlotTME_activeSiRmuStops.cpp