AlcapDAQ: TMEGeneratorFactory Class Reference
TMEGeneratorFactory Class Reference
#include <TMEGeneratorFactory.h>
Public Types
typedef TVMuonEventGenerator *(* maker)(TMEGeneratorOptions *)
Public Member Functions
void registerModule (const std::string &, maker)
Add a maker function to the list of makers.
virtual TVMuonEventGenerator * createModule (const std::string &, TMEGeneratorOptions *)
Create a module with options.
TVMuonEventGenerator * createModule (const std::string &name)
Create a module and look up its options from the internal list.
void addOptions (const std::string &name, TMEGeneratorOptions *opts)
void addArguments (const std::string &all_args)
void addArgument (const std::string &module, const std::string &argument)
void addArgument (const std::string &argument)
std::string GetArgumentName (const std::string &module, const int &argument)
void SetDebug (bool debug=true)
Static Public Member Functions
static TMEGeneratorFactory * Instance ()
Private Member Functions
TMEGeneratorFactory ()
~TMEGeneratorFactory ()
Detailed Description
Definition at line 8 of file TMEGeneratorFactory.h.
Member Typedef Documentation
typedef TVMuonEventGenerator *(* TemplateFactory< TVMuonEventGenerator , TMEGeneratorOptions >::maker)(TMEGeneratorOptions *) [inherited]
Definition at line 25 of file TemplateFactory.h.
Constructor & Destructor Documentation
TMEGeneratorFactory::TMEGeneratorFactory () [inline, private]
Definition at line 10 of file TMEGeneratorFactory.h.
Referenced by Instance().
                                     :
                        TemplateFactory<TVMuonEventGenerator,TMEGeneratorOptions>(){};
                ~TMEGeneratorFactory(){};
TMEGeneratorFactory::~TMEGeneratorFactory () [inline, private]
Definition at line 12 of file TMEGeneratorFactory.h.
{};
Member Function Documentation
void TemplateFactory< TVMuonEventGenerator , TMEGeneratorOptions >::addArgument (const std::string & argument) [inherited]
void TemplateFactory< TVMuonEventGenerator , TMEGeneratorOptions >::addArgument (const std::string & module, const std::string & argument) [inherited]
void TemplateFactory< TVMuonEventGenerator , TMEGeneratorOptions >::addArguments (const std::string & all_args) [inherited]
void TemplateFactory< TVMuonEventGenerator , TMEGeneratorOptions >::addOptions (const std::string & name, TMEGeneratorOptions * opts) [inherited]
TVMuonEventGenerator * TemplateFactory< TVMuonEventGenerator , TMEGeneratorOptions >::createModule (const std::string & name) [inherited]
Create a module and look up its options from the internal list.
virtual TVMuonEventGenerator * TemplateFactory< TVMuonEventGenerator , TMEGeneratorOptions >::createModule (const std::string & , TMEGeneratorOptions *) [virtual, inherited]
Create a module with options.
std::string TemplateFactory< TVMuonEventGenerator , TMEGeneratorOptions >::GetArgumentName (const std::string & module, const int & argument) [inherited]
TMEGeneratorFactory * TMEGeneratorFactory::Instance () [inline, static]
Definition at line 18 of file TMEGeneratorFactory.h.
References TMEGeneratorFactory().
Referenced by MakeMuonEvents::BeforeFirstEntry().
{
    static TMEGeneratorFactory* instance=NULL;
    if(!instance) {
        instance=new TMEGeneratorFactory();
    }
    return instance;
}
void TemplateFactory< TVMuonEventGenerator , TMEGeneratorOptions >::registerModule (const std::string & , maker) [inherited]
Add a maker function to the list of makers.
void TemplateFactory< TVMuonEventGenerator , TMEGeneratorOptions >::SetDebug (bool debug = true) [inline, inherited]
Definition at line 39 of file TemplateFactory.h.
{fDebug=debug;};
The documentation for this class was generated from the following file:
rootana/src/TME_generators/TMEGeneratorFactory.h