AlcapDAQ: TPulseIsland Class Reference
TPulseIsland Class Reference
[alcapana, rootana]
A uniform format for data from many different detectors.
#include <TPulseIsland.h>
Public Member Functions
TPulseIsland ()
This defaultconstructor I believe exists so ROOT can load these from file and is not used explcitly.
TPulseIsland (int timestamp, const std::vector< int > &samples_vector, std::string bank_name)
TPulseIsland (int timestamp, const std::vector< int >::const_iterator &first, const std::vector< int >::const_iterator &last, std::string bank_name)
Construct a TPI from a sub-range of an existing vector of ints.
void Reset (Option_t *o="")
The TPI goes to the state the default constructor would set it to. Not generally used.
void SetBankName (const std::string &name)
void SetTimeStamp (int t)
void SetSamples (const std::vector< int >::const_iterator &first, const std::vector< int >::const_iterator &last)
Getters
Return copies of all fields in the TPI and TSD.
const std::vector< int > & GetSamples () const
int GetTimeStamp () const
std::string GetBankName () const
double GetClockTickInNs () const
int GetTriggerPolarity () const
double GetAmplitude () const
Deprecated.
double GetFastPulseAmplitude () const
Deprecated.
double GetSlowPulseAmplitude () const
Deprecated.
double GetPulseHeight () const
double GetPulseTime () const
TH1I * GetPulseWaveform (std::string histname, std::string histtitle) const
int GetPulseLength () const
int GetPeakSample () const
double GetPedestal (int nPedSamples) const
Private Member Functions
TPulseIsland (const TPulseIsland &src)
Copying is made explicitly private since we do not need it yet.
TPulseIsland operator= (const TPulseIsland &rhs)
Assignment is made explicitly private since we do not need it yet.
ClassDef (TPulseIsland, 2)
Private Attributes
std::vector< int > fSamples
Time ordered ADC samples of the pulse.
int fTimeStamp
The time, in sample clock ticks, of the first samples.
std::string fBankName
The name describing the digitizer channel the pulse originated.
Detailed Description
A uniform format for data from many different detectors.
The TPulseIsland (TPI) class is a simple format for pulses from many different detectors. The pulse shape is stored, the time stamp, and the bank (digitizer channel) the pulse is from. More information is stored in TSetupData (TSD) which TPIs depend on.
Definition at line 23 of file TPulseIsland.h.
Constructor & Destructor Documentation
TPulseIsland::TPulseIsland ()
This defaultconstructor I believe exists so ROOT can load these from file and is not used explcitly.
Definition at line 13 of file TPulseIsland.cpp.
                           : fSamples(), fTimeStamp(0), fBankName("") {
}
TPulseIsland::TPulseIsland (int timestamp, const std::vector< int > & samples_vector, std::string bank_name)
The constructor we should use.
Parameters:
[in] timestamp The time in units of clock ticks of the first sample in the pulse
[in] samples_vector Consecutive ADC values representing the pulse
[in] bank_name The (4 character long) name identifying the digitizer channel the pulse originated.
Definition at line 21 of file TPulseIsland.cpp.
                                                                                             :
  fSamples(samples_vector), fTimeStamp(timestamp), fBankName(bank_name) {
}
TPulseIsland::TPulseIsland (int timestamp, const std::vector< int >::const_iterator & first, const std::vector< int >::const_iterator & last, std::string bank_name)
Construct a TPI from a sub-range of an existing vector of ints.
Copies all samples in the range [first,last[
Parameters:
[in] timestamp The time in units of clock ticks of the first sample in the pulse
[in] first Iterator to the first sample of the input waveform
[in] first Iterator to the last sample of the input waveform
[in] bank_name The (4 character long) name identifying the digitizer channel the pulse originated.
Definition at line 16 of file TPulseIsland.cpp.
                                                                 :
  fSamples(first,last), fTimeStamp(timestamp), fBankName(bank_name) {
}
TPulseIsland::TPulseIsland (const TPulseIsland & src) [private]
Copying is made explicitly private since we do not need it yet.
Member Function Documentation
TPulseIsland::ClassDef (TPulseIsland , 2) [private]
double TPulseIsland::GetAmplitude () const
Deprecated.
Definition at line 34 of file TPulseIsland.cpp.
References fBankName, GetFastPulseAmplitude(), GetSlowPulseAmplitude(), and TSetupData::Instance().
{
  if (TSetupData::Instance()->IsFast(fBankName))
    return GetFastPulseAmplitude();
  else
    return GetSlowPulseAmplitude();
}
std::string TPulseIsland::GetBankName () const [inline]
Definition at line 63 of file TPulseIsland.h.
References fBankName.
Referenced by PulseTemplate::AddPulse(), PulseCandidateFinder::CheckDigitiserOverflow(), PulseCandidateFinder::FillParameterHistogram(), PulseCandidateFinder::FindCandidatePulses_Fast(), PulseCandidateFinder::FindCandidatePulses_Slow(), PulseCandidateFinder::GetPulseCandidates(), GetTime(), functions::InterpolatePulse(), isValid(), and pulse_islands_stitch().
{ return fBankName; }
double TPulseIsland::GetClockTickInNs () const [inline]
Definition at line 65 of file TPulseIsland.h.
References fBankName, TSetupData::GetClockTick(), and TSetupData::Instance().
Referenced by PulseTemplate::AddPulse(), GetPulseTime(), GetTime(), and TAnalysedPulse::SetParentTPIProperties().
{ return TSetupData::Instance()->GetClockTick(fBankName); }
double TPulseIsland::GetFastPulseAmplitude () const
Deprecated.
Definition at line 46 of file TPulseIsland.cpp.
References fSamples, GetPeakSample(), GetPedestal(), and GetTriggerPolarity().
Referenced by GetAmplitude().
{
  double pedestal = GetPedestal(10);
  int peak_sample_element = GetPeakSample();
  return ( GetTriggerPolarity()*(fSamples.at(peak_sample_element) - pedestal) );
}
int TPulseIsland::GetPeakSample () const
Returns:
Index in samples vector corresponding to pulse peak.
Definition at line 90 of file TPulseIsland.cpp.
References fSamples, and GetTriggerPolarity().
Referenced by GetFastPulseAmplitude(), GetPulseHeight(), GetPulseTime(), GetSlowPulseAmplitude(), and TemplateCreator::StartTemplate().
{
  std::vector<int>::const_iterator peak;
  if(GetTriggerPolarity() == 1)
    peak = std::max_element(fSamples.begin(), fSamples.end());
  else
    peak = std::min_element(fSamples.begin(), fSamples.end());
  return peak - fSamples.begin();
}
double TPulseIsland::GetPedestal (int nPedSamples) const
Parameters:
[in] nPedSamples Deprecated
Returns:
Pedestal as stored in ODB
Definition at line 101 of file TPulseIsland.cpp.
References fBankName, TSetupData::GetPedestal(), and TSetupData::Instance().
Referenced by PulseTemplate::AddPulse(), PrePulse::FindPrePulses(), GetFastPulseAmplitude(), GetPulseHeight(), and GetSlowPulseAmplitude().
{
  return TSetupData::Instance()->GetPedestal(fBankName);
}
double TPulseIsland::GetPulseHeight () const
Returns:
Pedestal subtracted value of largest (smallest) sample for positive (negative) pulses.
Definition at line 62 of file TPulseIsland.cpp.
References fSamples, GetPeakSample(), GetPedestal(), and GetTriggerPolarity().
{
  double pedestal = GetPedestal(10);
  int peak_sample_element = GetPeakSample();
  return ( GetTriggerPolarity()*(fSamples.at(peak_sample_element) - pedestal) );
}
int TPulseIsland::GetPulseLength () const [inline]
Definition at line 81 of file TPulseIsland.h.
References fSamples.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), GaussFitAPGenerator::FitPulse(), ExportPulse::MakeHistTPI(), ExportPulse::PlotTPI(), and TAnalysedPulse::SetParentTPIProperties().
{ return fSamples.size(); }
double TPulseIsland::GetPulseTime () const
Returns:
Time in nanoseconds of the peak of the pulse.
Definition at line 70 of file TPulseIsland.cpp.
References fTimeStamp, GetClockTickInNs(), and GetPeakSample().
Referenced by GetTime().
{
  return (fTimeStamp + GetPeakSample()) * GetClockTickInNs();
}
TH1I * TPulseIsland::GetPulseWaveform (std::string histname, std::string histtitle) const
Returns:
An histogram representing the pulse for drawing or fitting.
Definition at line 77 of file TPulseIsland.cpp.
References fSamples.
Referenced by GaussFitAPGenerator::FitPulse().
{
  TH1I* hWaveform = new TH1I(histname.c_str(), histtitle.c_str(), fSamples.size(),0,fSamples.size());
  // Loop over the samples and fill the histogram
  for (std::vector<int>::const_iterator sampleIter = fSamples.begin(); sampleIter != fSamples.end(); sampleIter++) {
    hWaveform->Fill(sampleIter - fSamples.begin(), *sampleIter);
  }
  return hWaveform;
}
const std::vector<int>& TPulseIsland::GetSamples () const [inline]
Definition at line 61 of file TPulseIsland.h.
References fSamples.
Referenced by PulseTemplate::AddPulse(), PulseCandidateFinder::CheckDigitiserOverflow(), PulseTemplate::Chi2Fit(), PulseCandidateFinder::FillParameterHistogram(), PulseCandidateFinder::FindCandidatePulses_Fast(), PulseCandidateFinder::FindCandidatePulses_Slow(), PrePulse::FindPrePulses(), PulseCandidateFinder::GetPulseCandidates(), GetTime(), functions::InterpolatePulse(), isValid(), ExportPulse::MakeHistTPI(), Algorithm::SimpleIntegral::operator()(), Algorithm::ConstantFractionTime::operator()(), Algorithm::MaxBinTime::operator()(), Algorithm::MaxBinAmplitude::operator()(), MakeTemplate::ProcessEntry(), pulse_islands_stitch(), Algorithm::IntegralRatio::SetPedestalToMinimum(), and TemplateCreator::StartTemplate().
{ return fSamples; }
double TPulseIsland::GetSlowPulseAmplitude () const
Deprecated.
Definition at line 54 of file TPulseIsland.cpp.
References fSamples, GetPeakSample(), GetPedestal(), and GetTriggerPolarity().
Referenced by GetAmplitude().
{
  double pedestal = GetPedestal(10);
  int peak_sample_element = GetPeakSample();
  return ( GetTriggerPolarity()*(fSamples.at(peak_sample_element) - pedestal) );
}
int TPulseIsland::GetTimeStamp () const [inline]
Definition at line 62 of file TPulseIsland.h.
References fTimeStamp.
Referenced by TemplateConvolveAPGenerator::CalibrateTime(), PulseCandidateFinder::GetPulseCandidates(), GetTime(), Algorithm::ConstantFractionTime::operator()(), Algorithm::MaxBinTime::operator()(), ExportPulse::PlotTPI(), pulse_islands_stitch(), pulse_islands_t_comp(), and TAnalysedPulse::SetParentTPIProperties().
{ return fTimeStamp; }
int TPulseIsland::GetTriggerPolarity () const [inline]
Definition at line 66 of file TPulseIsland.h.
References fBankName, TSetupData::GetTriggerPolarity(), and TSetupData::Instance().
Referenced by PulseTemplate::AddPulse(), PulseCandidateFinder::FillParameterHistogram(), PulseCandidateFinder::FindCandidatePulses_Fast(), PulseCandidateFinder::FindCandidatePulses_Slow(), PrePulse::FindPrePulses(), GetFastPulseAmplitude(), GetPeakSample(), GetPulseHeight(), and GetSlowPulseAmplitude().
{return TSetupData::Instance()->GetTriggerPolarity(fBankName);};
TPulseIsland TPulseIsland::operator= (const TPulseIsland & rhs) [private]
Assignment is made explicitly private since we do not need it yet.
void TPulseIsland::Reset (Option_t * o = "")
The TPI goes to the state the default constructor would set it to. Not generally used.
Definition at line 25 of file TPulseIsland.cpp.
References fBankName, fSamples, and fTimeStamp.
{
  fTimeStamp = 0;
  fSamples.clear();
  fBankName = "";
}
void TPulseIsland::SetBankName (const std::string & name) [inline]
Definition at line 90 of file TPulseIsland.h.
References fBankName.
Referenced by PulseCandidateFinder::GetPulseCandidates().
{fBankName=name;}
void TPulseIsland::SetSamples (const std::vector< int >::const_iterator & first, const std::vector< int >::const_iterator & last) [inline]
Definition at line 92 of file TPulseIsland.h.
References fSamples.
Referenced by PulseCandidateFinder::GetPulseCandidates().
                                                   {fSamples.assign(first,last);}
void TPulseIsland::SetTimeStamp (int t) [inline]
Definition at line 91 of file TPulseIsland.h.
References fTimeStamp.
Referenced by PulseCandidateFinder::GetPulseCandidates().
{fTimeStamp=t;}
Member Data Documentation
std::string TPulseIsland::fBankName [private]
The name describing the digitizer channel the pulse originated.
Definition at line 30 of file TPulseIsland.h.
Referenced by GetAmplitude(), GetBankName(), GetClockTickInNs(), GetPedestal(), GetTriggerPolarity(), Reset(), and SetBankName().
std::vector<int> TPulseIsland::fSamples [private]
Time ordered ADC samples of the pulse.
Definition at line 26 of file TPulseIsland.h.
Referenced by GetFastPulseAmplitude(), GetPeakSample(), GetPulseHeight(), GetPulseLength(), GetPulseWaveform(), GetSamples(), GetSlowPulseAmplitude(), Reset(), and SetSamples().
int TPulseIsland::fTimeStamp [private]
The time, in sample clock ticks, of the first samples.
Definition at line 28 of file TPulseIsland.h.
Referenced by GetPulseTime(), GetTimeStamp(), Reset(), and SetTimeStamp().
The documentation for this class was generated from the following files:
src/common/TPulseIsland.h
src/common/TPulseIsland.cpp