AlcapDAQ: Lifetime Class Reference
Lifetime Class Reference
#include <Lifetime.h>
Public Member Functions
Lifetime (char *HistogramDirectoryName)
~Lifetime ()
int ProcessGenericEntry (TGlobalData *gData, TSetupData *gSetup)
virtual int BeforeFirstEntry (TGlobalData *gData, TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, TSetupData *setup)
const char * GetName () const
Protected Member Functions
bool Debug () const
Protected Attributes
TDirectory * dir
TSetupData * fSetup
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, TSetupData *gSetup)
Detailed Description
Definition at line 9 of file Lifetime.h.
Constructor & Destructor Documentation
Lifetime::Lifetime (char * HistogramDirectoryName)
Definition at line 21 of file Lifetime.cpp.
References nECut, tCut, and tPileUp.
                                                :
   FillHistBase(HistogramDirectoryName) {
   // Time in ns
   tCut[0] = 800.;
   tCut[1] = 5000.;
   tPileUp = 10000.;
   // Energy cuts in ADC
   eCut.push_back(100);
   eCut.push_back(200);
   eCut.push_back(300);
   eCut.push_back(400);
   eCut.push_back(500);
   eCut.push_back(600);
   eCut.push_back(700);
   eCut.push_back(800);
   eCut.push_back(900);
   eCut.push_back(1000);
   eCut.push_back(1100);
   eCut.push_back(1200);
   eCut.push_back(1300);
   eCut.push_back(1400);
   eCut.push_back(1500);
   sNames.push_back("hLifetime100");
   sNames.push_back("hLifetime200");
   sNames.push_back("hLifetime300");
   sNames.push_back("hLifetime400");
   sNames.push_back("hLifetime500");
   sNames.push_back("hLifetime600");
   sNames.push_back("hLifetime700");
   sNames.push_back("hLifetime800");
   sNames.push_back("hLifetime900");
   sNames.push_back("hLifetime1000");
   sNames.push_back("hLifetime1100");
   sNames.push_back("hLifetime1200");
   sNames.push_back("hLifetime1300");
   sNames.push_back("hLifetime1400");
   sNames.push_back("hLifetime1500");
   sTitles.push_back("Lifetime (100 ADC cut)");
   sTitles.push_back("Lifetime (200 ADC cut)");
   sTitles.push_back("Lifetime (300 ADC cut)");
   sTitles.push_back("Lifetime (400 ADC cut)");
   sTitles.push_back("Lifetime (500 ADC cut)");
   sTitles.push_back("Lifetime (600 ADC cut)");
   sTitles.push_back("Lifetime (700 ADC cut)");
   sTitles.push_back("Lifetime (800 ADC cut)");
   sTitles.push_back("Lifetime (900 ADC cut)");
   sTitles.push_back("Lifetime (1000 ADC cut)");
   sTitles.push_back("Lifetime (1100 ADC cut)");
   sTitles.push_back("Lifetime (1200 ADC cut)");
   sTitles.push_back("Lifetime (1300 ADC cut)");
   sTitles.push_back("Lifetime (1400 ADC cut)");
   sTitles.push_back("Lifetime (1500 ADC cut)");
   // Number to index later
   nECut = eCut.size();
   // Sanity check: All vectors are the same size above
   if (nECut != sNames.size() || nECut != sTitles.size())
     std::cout << "Error! Coder forgot a line or two in initialization of Lifetime module in rootana!" << std::endl;
   // Prepare histograms
   for (unsigned int iECut = 0; iECut < nECut; ++iECut)
     hLifetime.push_back(new TH1I(sNames[iECut].c_str(), sTitles[iECut].c_str(), 1000, 0., 2000.));
   gDirectory->cd("/");
 }
Lifetime::~Lifetime ()
Definition at line 86 of file Lifetime.cpp.
                    {
 }
Member Function Documentation
virtual int FillHistBase::AfterLastEntry (TGlobalData * gData, TSetupData * setup) inline virtual inherited
Reimplemented in TestModule.
Definition at line 39 of file FillHistBase.h.
 {return 0;};
virtual int FillHistBase::BeforeFirstEntry (TGlobalData * gData, TSetupData * setup) inline virtual inherited
Reimplemented in ExportPulse, MakeAnalysedPulses, MakeDetectorPulses, MakeMuonEvents, and TestModule.
Definition at line 38 of file FillHistBase.h.
 {return 0;};
bool FillHistBase::Debug () const inline protected inherited
Definition at line 45 of file FillHistBase.h.
References FillHistBase::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), TestModule::AfterLastEntry(), TestModule::BeforeFirstEntry(), MakeMuonEvents::BeforeFirstEntry(), MakeDetectorPulses::MakeGenerator(), ExportPulse::MakePlot(), and MakeAnalysedPulses::ProcessEntry().
 {return fDebug;};
const char* FillHistBase::GetName () const inline inherited
Definition at line 40 of file FillHistBase.h.
References FillHistBase::dir.
Referenced by DeadTimeGe::ProcessEntry(), PlotTime::ProcessEntry(), and PlotAmplitude::ProcessEntry().
 {return dir->GetName();};
int Lifetime::ProcessEntry (TGlobalData * gData, TSetupData * gSetup) private virtual
Reimplemented from FillHistBase.
Definition at line 89 of file Lifetime.cpp.
References gAnalysedPulseMap, nECut, tCut, and tPileUp.
{
   // Look for muSc and at least one arm
   AnalysedPulseList *musc;
   AnalysedPulseList *sir, *sil;
   if (gAnalysedPulseMap.count("muSc")) musc = &gAnalysedPulseMap.at("muSc");
   else return 0;
   if (gAnalysedPulseMap.count("SiR2-F")) sir = &gAnalysedPulseMap.at("SiR2-F");
   else sir = NULL;
   if (gAnalysedPulseMap.count("SiL2-F")) sil = &gAnalysedPulseMap.at("SiL2-F");
   else sil = NULL;
   // If neither arm had hits, there's nothing to loop through
   if (sil == NULL && sir == NULL) return 0;
   // Iterators through aforementioned vectors
   AnalysedPulseList::iterator cMusc;
   AnalysedPulseList::iterator cSiR, cSiL;
   cMusc = musc->begin();
   if (sir)
     cSiR = sir->begin();
   if (sil)
     cSiL = sil->begin();
   unsigned int iECut;
   double tMusc;
   bool bFound[15];
   for (; cMusc < musc->end(); ++cMusc) {
     tMusc = (*cMusc)->GetTime();
     // If there's pile-up, advance beyond it
     if ((cMusc+1) != musc->end() && (*(cMusc + 1))->GetTime() - tMusc < tPileUp) {
       ++cMusc;
       continue;
     }
     // Set all flags to 'not-found-yet' status
     for (iECut = 0; iECut < nECut; ++iECut)
       bFound[iECut] = false;
     // Advance silicon pulses beyond time of muSc
     if (sir)
       while (cSiR != sir->end() && (*cSiR)->GetTime() -tMusc < tCut[0])
         ++cSiR;
     if (sil)
       while (cSiL != sil->end() && (*cSiL)->GetTime() < tMusc)
         ++cSiL;
     // Check for hits
     if (sir)
       while (cSiR != sir->end() && (*cSiR)->GetTime() - tMusc < tCut[1]) {
         for (iECut = 0; iECut < nECut; ++iECut)
           if (!(bFound[iECut]))
             if ((*cSiR)->GetAmplitude() > eCut[iECut]) {
               hLifetime[iECut]->Fill((*cSiR)->GetTime() - tMusc);
               bFound[iECut] = true;
             }
         ++cSiR;
       }
     if (sil)
       while (cSiL != sil->end() && (*cSiL)->GetTime() - tMusc < tCut[1]) {
         for (iECut = 0; iECut < nECut; ++iECut)
           if (!(bFound[iECut]))
             if ((*cSiL)->GetAmplitude() > eCut[iECut]) {
               hLifetime[iECut]->Fill((*cSiL)->GetTime() - tMusc);
               bFound[iECut] = true;
             }
         ++cSiL;
       }
   }
   return 0;
 }
int FillHistBase::ProcessGenericEntry (TGlobalData * gData, TSetupData * gSetup) inherited
Definition at line 24 of file FillHistBase.cpp.
References FillHistBase::dir, and FillHistBase::ProcessEntry().
{
   // This is called by our main routine and would allow later to split into different
   // process routines if we have more than one Tree and hence different tpyes of data input.
   if(dir) dir->cd();
   int ret = ProcessEntry(gData, gSetup);
   gDirectory->cd("/");
   return ret;
 }
Field Documentation
TDirectory* FillHistBase::dir protected inherited
Definition at line 40 of file FillHistBase.h.
Referenced by DeadTimeGe::DeadTimeGe(), ExportPulse::ExportPulse(), FillHistBase::FillHistBase(), FillHistBase::GetName(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmplitude::PlotAmplitude(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTime::PlotTime(), and FillHistBase::ProcessGenericEntry().
TSetupData* FillHistBase::fSetup protected inherited
Definition at line 44 of file FillHistBase.h.
The documentation for this class was generated from the following files:
analyzer/rootana/src/physics/Lifetime.h
analyzer/rootana/src/physics/Lifetime.cpp