AlcapDAQ: TNaIHit Class Reference
TNaIHit Class Reference
#include <TNaIHit.h>
Data Structures
struct TimeSortNaIHits
struct TNaIHitComparator
struct TNaIHitTimeComparator
Public Member Functions
TNaIHit ()
TNaIHit (const TOctalFADCIsland &timePulse, const TOctalFADCIsland &energyPulse, int count, int nAv)
TNaIHit (const TOctalFADCIsland &timePulse, const TOctalFADCIsland &energyPulse, int count)
double GetTime () const
double GetEnergy () const
int GetDetector () const
void SetFromTimingPulse (const TOctalFADCIsland &timePulse)
void SetFromEnergyPulse (const TOctalFADCIsland &energyPulse)
const TOctalFADCIsland * GetTimingIsland () const
const TOctalFADCIsland * GetEnergyIsland () const
void SetTimingIsland (const TOctalFADCIsland *island)
void SetEnergyIsland (const TOctalFADCIsland *island)
double GetTimingTime () const
double GetTimingAmp () const
double GetEnergyTime () const
double GetEnergyAmp () const
void SetTimingTime (double time)
void SetEnergyTime (double time)
void SetTimingAmp (double amp)
void SetEnergyAmp (double amp)
void SetDetector (int det)
double GetCount () const
double GetnAverage () const
bool GetPileUp () const
bool GetNoisy () const
void SetCount (int counts)
void SetnAverage (int Av)
void SetPileUp (bool PU)
void SetNoisy (bool fN)
Private Member Functions
ClassDef (TNaIHit, 1)
This does not own the FADC Islands.
Private Attributes
double fTimingTime
double fTimingAmp
double fEnergyTime
double fEnergyAmp
int detector
int fCount
int nAverage
bool fPileUp
bool fNoisy
const TOctalFADCIsland * fTimePulse
const TOctalFADCIsland * fEnergyPulse
This does not own the FADC Islands.
Detailed Description
This class is a wrapper for the two NaI channels (timing, egy)
Definition at line 10 of file TNaIHit.h.
Constructor & Destructor Documentation
TNaIHit::TNaIHit ()
TNaIHit::TNaIHit (const TOctalFADCIsland & timePulse, const TOctalFADCIsland & energyPulse, int count, int nAv)
Definition at line 12 of file TNaIHit.cpp.
References count, fCount, fNoisy, fPileUp, nAverage, SetFromEnergyPulse(), and SetFromTimingPulse().
 {
   fCount=count;
   nAverage = nAv;
   fPileUp = false;
   fNoisy = false;
   SetFromTimingPulse(timePulse);
   SetFromEnergyPulse(energyPulse);
 }
TNaIHit::TNaIHit (const TOctalFADCIsland & timePulse, const TOctalFADCIsland & energyPulse, int count)
Definition at line 22 of file TNaIHit.cpp.
References count, fCount, fNoisy, fPileUp, TOctalFADCIsland::GetFADCChannel(), nAverage, SetDetector(), SetFromEnergyPulse(), and SetFromTimingPulse().
 {
   fCount=count;
   nAverage = 1;
   fPileUp = false;
   fNoisy = false;
   SetFromTimingPulse(timePulse);
   SetFromEnergyPulse(energyPulse);
   SetDetector(1+(int)(timePulse.GetFADCChannel()/2));
 }
Member Function Documentation
TNaIHit::ClassDef (TNaIHit , 1) private
This does not own the FADC Islands.
double TNaIHit::GetCount () const inline
Definition at line 40 of file TNaIHit.h.
References fCount.
 { return fCount; }
int TNaIHit::GetDetector () const inline
Definition at line 18 of file TNaIHit.h.
References detector.
 { return detector;}
double TNaIHit::GetEnergy () const inline
Definition at line 17 of file TNaIHit.h.
References GetEnergyAmp().
 { return GetEnergyAmp(); }
double TNaIHit::GetEnergyAmp () const inline
Definition at line 32 of file TNaIHit.h.
References fEnergyAmp.
Referenced by GetEnergy().
 { return  fEnergyAmp; }
const TOctalFADCIsland* TNaIHit::GetEnergyIsland () const inline
Definition at line 24 of file TNaIHit.h.
References fEnergyPulse.
 { return fEnergyPulse; }
double TNaIHit::GetEnergyTime () const inline
Definition at line 31 of file TNaIHit.h.
References fEnergyTime.
 { return fEnergyTime; }
double TNaIHit::GetnAverage () const inline
Definition at line 41 of file TNaIHit.h.
References nAverage.
 { return nAverage; }
bool TNaIHit::GetNoisy () const inline
Definition at line 43 of file TNaIHit.h.
References fNoisy.
 { return fNoisy; }
bool TNaIHit::GetPileUp () const inline
Definition at line 42 of file TNaIHit.h.
References fPileUp.
 { return fPileUp; }
double TNaIHit::GetTime () const inline
Definition at line 16 of file TNaIHit.h.
References GetTimingTime().
Referenced by TNaIHit::TNaIHitTimeComparator::operator()(), TNaIHit::TNaIHitComparator::operator()(), and TNaIHit::TimeSortNaIHits::operator()().
 { return GetTimingTime(); }
double TNaIHit::GetTimingAmp () const inline
Definition at line 30 of file TNaIHit.h.
References fTimingAmp.
 { return  fTimingAmp; }
const TOctalFADCIsland* TNaIHit::GetTimingIsland () const inline
Definition at line 23 of file TNaIHit.h.
References fTimePulse.
 { return fTimePulse; }
double TNaIHit::GetTimingTime () const inline
Definition at line 29 of file TNaIHit.h.
References fTimingTime.
Referenced by GetTime().
 { return fTimingTime; }
void TNaIHit::SetCount (int counts) inline
Definition at line 47 of file TNaIHit.h.
References fCount.
 { fCount = counts; }
void TNaIHit::SetDetector (int det) inline
Definition at line 38 of file TNaIHit.h.
References detector.
Referenced by TNaIHit().
 { detector = det;}
void TNaIHit::SetEnergyAmp (double amp) inline
Definition at line 37 of file TNaIHit.h.
References fEnergyAmp.
Referenced by SetFromEnergyPulse().
 { fEnergyAmp = amp; }
void TNaIHit::SetEnergyIsland (const TOctalFADCIsland * island) inline
Definition at line 27 of file TNaIHit.h.
References fEnergyPulse.
Referenced by SetFromEnergyPulse().
 { fEnergyPulse = island;}
void TNaIHit::SetEnergyTime (double time) inline
Definition at line 35 of file TNaIHit.h.
References fEnergyTime, and time.
Referenced by SetFromEnergyPulse().
 { fEnergyTime = time; }
void TNaIHit::SetFromEnergyPulse (const TOctalFADCIsland & energyPulse)
Sets the time and energy parameters of TNaIHit for the energy data. Uses the maximum bin of the pulse for the time and the maximum value as the amplitude.
Definition at line 54 of file TNaIHit.cpp.
References TOctalFADCIsland::GetAverageMax(), TOctalFADCIsland::GetFADCChannel(), TOctalFADCIsland::GetMax(), TOctalFADCIsland::GetMaxBinBlockTime(), nAverage, octalfadc_parameters, SetEnergyAmp(), SetEnergyIsland(), and SetEnergyTime().
Referenced by TNaIHit().
 {
   double energyClockPeriod = octalfadc_parameters.kClockPeriod[energyPulse.GetFADCChannel()];
   double maxbintime = (energyPulse.GetMaxBinBlockTime()) * energyClockPeriod;
   SetEnergyTime( maxbintime );
   if(nAverage > 1) { SetEnergyAmp( energyPulse.GetAverageMax(nAverage)); } else {SetEnergyAmp( energyPulse.GetMax());}
   //SetEnergyAmp( energyPulse.GetMax());
   SetEnergyIsland( &energyPulse );
 }
void TNaIHit::SetFromTimingPulse (const TOctalFADCIsland & timePulse)
Sets the time and energy parameters of TNaIHit for the timing data. Uses the CF time of the pulse for the time and the maximum value as the amplitude.
Definition at line 37 of file TNaIHit.cpp.
References TOctalFADCIsland::GetAverageMax(), TOctalFADCIsland::GetCFBlockTime(), TOctalFADCIsland::GetFADCChannel(), TOctalFADCIsland::GetMax(), TOctalFADCIsland::GetPulseQuality(), nAverage, octalfadc_parameters, SetNoisy(), SetTimingAmp(), SetTimingIsland(), and SetTimingTime().
Referenced by TNaIHit().
 {
   double timingClockPeriod = octalfadc_parameters.kClockPeriod[timePulse.GetFADCChannel()];
   double cftime = (timePulse.GetCFBlockTime()) * timingClockPeriod;
   SetTimingTime( cftime );
   if(nAverage> 1) { SetTimingAmp( timePulse.GetAverageMax(nAverage)); } else {SetTimingAmp( timePulse.GetMax());}
   // SetTimingAmp( timePulse.GetMax());
   SetTimingIsland( &timePulse );
   if(timePulse.GetPulseQuality()==3){SetNoisy(true);}
 }
void TNaIHit::SetnAverage (int Av) inline
Definition at line 48 of file TNaIHit.h.
References nAverage.
 { nAverage = Av;}
void TNaIHit::SetNoisy (bool fN) inline
Definition at line 50 of file TNaIHit.h.
References fNoisy.
Referenced by SetFromTimingPulse().
 { fNoisy = fN; }
void TNaIHit::SetPileUp (bool PU) inline
Definition at line 49 of file TNaIHit.h.
References fPileUp.
 { fPileUp = PU; }
void TNaIHit::SetTimingAmp (double amp) inline
Definition at line 36 of file TNaIHit.h.
References fTimingAmp.
Referenced by SetFromTimingPulse().
 { fTimingAmp = amp;}
void TNaIHit::SetTimingIsland (const TOctalFADCIsland * island) inline
Definition at line 26 of file TNaIHit.h.
References fTimePulse.
Referenced by SetFromTimingPulse().
 { fTimePulse = island;}
void TNaIHit::SetTimingTime (double time) inline
Definition at line 34 of file TNaIHit.h.
References fTimingTime, and time.
Referenced by SetFromTimingPulse().
 { fTimingTime = time;}
Field Documentation
int TNaIHit::detector private
Definition at line 84 of file TNaIHit.h.
Referenced by GetDetector(), and SetDetector().
int TNaIHit::fCount private
Definition at line 85 of file TNaIHit.h.
Referenced by GetCount(), SetCount(), and TNaIHit().
double TNaIHit::fEnergyAmp private
Definition at line 82 of file TNaIHit.h.
Referenced by GetEnergyAmp(), and SetEnergyAmp().
const TOctalFADCIsland* TNaIHit::fEnergyPulse private
This does not own the FADC Islands.
Definition at line 91 of file TNaIHit.h.
Referenced by GetEnergyIsland(), and SetEnergyIsland().
double TNaIHit::fEnergyTime private
Definition at line 81 of file TNaIHit.h.
Referenced by GetEnergyTime(), and SetEnergyTime().
bool TNaIHit::fNoisy private
Definition at line 88 of file TNaIHit.h.
Referenced by GetNoisy(), SetNoisy(), and TNaIHit().
bool TNaIHit::fPileUp private
Definition at line 87 of file TNaIHit.h.
Referenced by GetPileUp(), SetPileUp(), and TNaIHit().
const TOctalFADCIsland* TNaIHit::fTimePulse private
Definition at line 90 of file TNaIHit.h.
Referenced by GetTimingIsland(), and SetTimingIsland().
double TNaIHit::fTimingAmp private
Definition at line 80 of file TNaIHit.h.
Referenced by GetTimingAmp(), and SetTimingAmp().
double TNaIHit::fTimingTime private
Definition at line 79 of file TNaIHit.h.
Referenced by GetTimingTime(), and SetTimingTime().
int TNaIHit::nAverage private
Definition at line 86 of file TNaIHit.h.
Referenced by GetnAverage(), SetFromEnergyPulse(), SetFromTimingPulse(), SetnAverage(), and TNaIHit().
The documentation for this class was generated from the following files:
musun_analysis_code/TNaIHit.h
musun_analysis_code/TNaIHit.cpp