AlcapDAQ: PulseCandidateFinder Class Reference
PulseCandidateFinder Class Reference
[Modules]
Utility class to find pulse candidates on a TPulseIsland.
#include <PulseCandidateFinder.h>
Classes
struct Location
Location is a struct containing the start and stop location (in terms of sample number) of a candidate pulse.
Public Member Functions
PulseCandidateFinder (std::string detname, modules::options *opts)
The constructor.
~PulseCandidateFinder ()
Empty destructor.
void FindPulseCandidates (TPulseIsland *pulse)
Find the pulse candidates on the given TPulseIsland.
int GetNPulseCandidates ()
Returns the number of pulse candidates that were found.
void GetPulseCandidates (std::vector< TPulseIsland * > &) const
Returns the actual TPulseIsland of each candidate.
void FillParameterHistogram (TH1D *histogram)
Takes a histogram and fills it with the parameters (either sample height above pedestals or sample differences between consecutive samples).
Private Member Functions
void FindCandidatePulses_Fast (int rise)
The algorithm for finding fast pulses.
void FindCandidatePulses_Slow (int threshold)
The algorithm for finding slow pulses.
void FillSampleDifferencesHistogram (TH1D *histogram)
Fills the given histogram with the sample differences between consecutive pulses.
void FillSampleHeightsHistogram (TH1D *histogram)
Fills the given histogram with the sample's height above pedestal.
void SetDefaultParameterValues ()
Called in the constructor if fDefaultParameterValues is empty, so that it can be filled.
void SetOneSigmaValues ()
Called if "n_sigma" is specified as an option in the modules file and if fOneSigmaValues is empty.
void SetPedestalValues ()
Called to set the pedestal values.
Private Attributes
TPulseIsland * fPulseIsland
The TPulseIsland that we are looking for candidates on.
std::vector< Location > fPulseCandidateLocations
The vector that we store the pulse candidate locations in.
IDs::channel fChannel
The channel that this PulseCandidateFinder works on.
double fParameterValue
The value of the parameter to start a candidate pulse.
double fNoise
The noise value for this channel.
double fPedestal
The pedestal value for this channel.
int fNSigma
The number of sigma (i.e. noise) that we want the threshold to be set to.
Static Private Attributes
static std::map< IDs::channel,
int > fDefaultParameterValues
The map that stores the default parameter values in case there isn't one specified in the modules file.
static std::map< IDs::channel,
double > fOneSigmaValues
The map that stores the one sigma values that we get from the SQLite database.
static std::map< IDs::channel,
double > fPedestalValues
The map that stores the pedestal values that we get from the SQLite database.
Detailed Description
Utility class to find pulse candidates on a TPulseIsland.
Author:
Andrew Edmonds
This utility class stores the location of candidate pulses of a TPulseIsland. These candidate pulses can be retrieved later by the calling module.
Note that there are two algorithms used to find candidate pulses. For slow pulses, we simply look for when a sample has gone above a certain threshold and for fast pulses, we look to see if there's a sudden rise in sample value between consecutive pulses.
The final thing this class does is to fill a given histogram with the relevant parameters (either sample height or sample difference). This ability is used by the PulseCandidateFinder_InvestigateParameters module
Definition at line 27 of file PulseCandidateFinder.h.
Constructor & Destructor Documentation
PulseCandidateFinder::PulseCandidateFinder (std::string detname, modules::options * opts)
The constructor.
The constructor looks in the opts for any changes to the defailt parameter, "n_sigma" and "debug"
Parameters:
[in] opts Describe the options this module takes.
PulseCandidateFinder() The constructor just sets all the parameter values
Definition at line 18 of file PulseCandidateFinder.cpp.
References fChannel, fDefaultParameterValues, fNoise, fNSigma, fOneSigmaValues, fParameterValue, fPedestal, fPedestalValues, modules::options::GetBool(), modules::options::GetInt(), modules::options::GetOption(), modules::options::HasOption(), SetDefaultParameterValues(), SetOneSigmaValues(), and SetPedestalValues().
                                                                                 : fChannel(detname) {
  if (fDefaultParameterValues.empty()) {
    SetDefaultParameterValues();
  }
  if (fOneSigmaValues.empty()) {
    SetOneSigmaValues();
  }
  if (fPedestalValues.empty()) {
    SetPedestalValues();
  }
  fNSigma = opts->GetInt("n_sigma", 0);
  if (fNSigma == 0) {
    fParameterValue = opts->GetInt(detname, fDefaultParameterValues[fChannel]); // set the parameter value for this channel
  }
  else {
    fParameterValue = fNSigma * fOneSigmaValues[IDs::channel(detname)];
  }
  fNoise = fOneSigmaValues[IDs::channel(fChannel)];
  fPedestal = fPedestalValues[IDs::channel(fChannel)];
  if (opts->HasOption("debug") && (opts->GetOption("debug").empty() || opts->GetBool("debug"))) {
    std::cout << "Parameter Value for " << fChannel << " PulseCandidateFinder is " << fParameterValue << std::endl; // would be nice to know which module this is for
  }
}
PulseCandidateFinder::~PulseCandidateFinder ()
Empty destructor.
Definition at line 70 of file PulseCandidateFinder.cpp.
{
}
Member Function Documentation
void PulseCandidateFinder::FillParameterHistogram (TH1D * histogram)
Takes a histogram and fills it with the parameters (either sample height above pedestals or sample differences between consecutive samples).
FillParameterHistogram Fills the given histogram with the relevant parameter based on the channel
Definition at line 223 of file PulseCandidateFinder.cpp.
References FillSampleDifferencesHistogram(), FillSampleHeightsHistogram(), fPulseIsland, TPulseIsland::GetBankName(), TSetupData::GetDetectorName(), SetupNavigator::GetRunNumber(), SetupNavigator::Instance(), TSetupData::Instance(), IDs::channel::isFast(), and IDs::channel::isSlow().
Referenced by PulseCandidateFinder_InvestigateParameters::ProcessEntry().
{
  std::string detname = TSetupData::Instance()->GetDetectorName(fPulseIsland->GetBankName());
  IDs::channel theChannel = detname;
  std::string parameter_name = "Unknown";
  // We have a different algorithm for fast and slow pulses
  if (theChannel.isFast()) {
    parameter_name = "SampleDifference";
    FillSampleDifferencesHistogram(histogram);
  }
  else if (theChannel.isSlow()) {
    parameter_name = "SampleHeight";
    FillSampleHeightsHistogram(histogram);
  }
  else {
    // it's a scintillator so plot the fast parameters
    parameter_name = "SampleDifference";
    FillSampleDifferencesHistogram(histogram);
  }
  std::stringstream histtitle;
  histtitle << "Plot of " << parameter_name << " for " << detname << " for Run " << SetupNavigator::Instance()->GetRunNumber();
  histogram->SetTitle(histtitle.str().c_str());
  histogram->GetYaxis()->SetTitle("");
  histogram->GetXaxis()->SetTitle(parameter_name.c_str());
}
void PulseCandidateFinder::FillSampleDifferencesHistogram (TH1D * histogram) [private]
Fills the given histogram with the sample differences between consecutive pulses.
FillSampleDifferencesHistogram Fills the given histogram with the differences between consecutive samples
Definition at line 254 of file PulseCandidateFinder.cpp.
References fPedestal, fPulseIsland, TPulseIsland::GetSamples(), and TPulseIsland::GetTriggerPolarity().
Referenced by FillParameterHistogram().
{
  const std::vector<int>& samples = fPulseIsland->GetSamples();
  unsigned int n_samples = samples.size();
  int polarity = fPulseIsland->GetTriggerPolarity();
  int s1, s2, ds; // this sample value, the previous sample value and the change in the sample value
  // Loop through the samples
  for (unsigned int i = 1; i < n_samples; ++i) {
    s1 = polarity * (samples[i-1] - fPedestal);
    s2 = polarity * (samples[i] - fPedestal);
    ds = s2 - s1;
    histogram->Fill(ds);
  }
}
void PulseCandidateFinder::FillSampleHeightsHistogram (TH1D * histogram) [private]
Fills the given histogram with the sample's height above pedestal.
FillSampleHeightsHistogram Fills the given histogram with the heights between consecutive samples
Definition at line 274 of file PulseCandidateFinder.cpp.
References fPedestal, fPulseIsland, TPulseIsland::GetSamples(), and TPulseIsland::GetTriggerPolarity().
Referenced by FillParameterHistogram().
{
  const std::vector<int>& samples = fPulseIsland->GetSamples();
  unsigned int n_samples = samples.size();
  int polarity = fPulseIsland->GetTriggerPolarity();
  int sample_height; // the height of this sample above pedestal
  // Loop through the samples
  for (unsigned int i = 0; i < n_samples; ++i) {
    sample_height = polarity * (samples[i] - fPedestal);
    histogram->Fill(sample_height);
  }
}
void PulseCandidateFinder::FindCandidatePulses_Fast (int rise) [private]
The algorithm for finding fast pulses.
Check the difference between consecutive samples and if it's above a certain value then it's that start of a candidate pulse. The end of the candidate pulse is when the samples go below pedestal
FindCandidatePulses_Fast Finds pulse candidates on fast pulse islands by looking for a sudden rise between consecutive samples
Definition at line 113 of file PulseCandidateFinder.cpp.
References fNoise, fPedestal, fPulseCandidateLocations, fPulseIsland, TPulseIsland::GetBankName(), TPulseIsland::GetSamples(), TPulseIsland::GetTriggerPolarity(), PulseCandidateFinder::Location::start, and PulseCandidateFinder::Location::stop.
Referenced by FindPulseCandidates().
{
  const std::vector<int>& samples = fPulseIsland->GetSamples();
  unsigned int n_samples = samples.size();
  std::string bankname = fPulseIsland->GetBankName();
  int polarity = fPulseIsland->GetTriggerPolarity();
  int s1, s2, ds; // this sample value, the previous sample value and the change in the sample value
  bool found = false;
  Location location;
  // Loop through the samples
  int n_before_start_samples = 2; // take a few samples from before the official start
  for (unsigned int i = 1; i < n_samples; ++i) {
    s1 = polarity * (samples[i-1] - fPedestal);
    s2 = polarity * (samples[i] - fPedestal);
    ds = s2 - s1;
    if (found) {
      if (s2 < fNoise) { // stop if the sample goes below pedestal
        location.stop = (int)i;
        if (location.stop >= (int)samples.size()) {
          location.stop = samples.size() - 1;
        }
        fPulseCandidateLocations.push_back(location);
        found = false;
      }
      else if (i == n_samples-1) { // Also stop if we are at the last sample (only do this check if we failed the above one)
        location.stop = (int) i;
        fPulseCandidateLocations.push_back(location);
        found = false;
      }
    } else {
      if (ds > rise) {
        found = true;
        location.start = (int)(i - 1) - n_before_start_samples;
        if (location.start < 0) {
          location.start = 0;
        }
      }
    }
  }
}
void PulseCandidateFinder::FindCandidatePulses_Slow (int threshold) [private]
The algorithm for finding slow pulses.
Check the height above pedestal of each sample and if it's above a certain value then it's that start of a candidate pulse. The end of the candidate pulse is when the samples go below pedestal
FindCandidatePulses_Slow Finds pulse candidates on slow pulse islands by seeing if a sample goes above a threshold
Definition at line 164 of file PulseCandidateFinder.cpp.
References fNoise, fPedestal, fPulseCandidateLocations, fPulseIsland, TPulseIsland::GetBankName(), TPulseIsland::GetSamples(), TPulseIsland::GetTriggerPolarity(), PulseCandidateFinder::Location::start, and PulseCandidateFinder::Location::stop.
Referenced by FindPulseCandidates().
{
  const std::vector<int>& samples = fPulseIsland->GetSamples();
  unsigned int n_samples = samples.size();
  std::string bankname = fPulseIsland->GetBankName();
  int polarity = fPulseIsland->GetTriggerPolarity();
  int sample_height; // the sample's height above pedestal
  int start, stop; // the start and stop location
  bool found = false;
  Location location;
  // Loop through the samples
  for (unsigned int i = 0; i < n_samples; ++i) {
    sample_height = polarity * (samples[i] - fPedestal);
    if (found) {
      if (sample_height < fNoise) { // stop if the sample goes below pedestal
        location.stop = (int)i;
        if (location.stop >=(int) samples.size()) {
          location.stop = samples.size() - 1;
        }
        start = stop = 0;
        fPulseCandidateLocations.push_back(location);
        found = false;
      }
      else if (i == n_samples-1) { // Also stop if we are at the last sample (only do this check if we failed the above one)
        location.stop = (int) i;
        fPulseCandidateLocations.push_back(location);
        found = false;
      }
    } else {
      if (sample_height > threshold) {
        found = true;
        // Track back until we get to the pedestal again so that we get the whole pulse (Ge-S pulses were being cut-off at the start)
        location.start = (int)(i);
        for (int j = i; j > 0; --j) {
          sample_height = polarity * (samples[j] - fPedestal);
          if (sample_height <= 0) {
            location.start = (int)(j);
            break;
          }
        }
        if (location.start < 0) {
          location.start = 0;
        }
      }
    }
  }
}
void PulseCandidateFinder::FindPulseCandidates (TPulseIsland * pulse)
Find the pulse candidates on the given TPulseIsland.
FindPulseCandidates() Finds the pulse candidates on the given TPulseIsland
Definition at line 50 of file PulseCandidateFinder.cpp.
References fChannel, FindCandidatePulses_Fast(), FindCandidatePulses_Slow(), fParameterValue, fPulseCandidateLocations, fPulseIsland, IDs::channel::isFast(), and IDs::channel::isSlow().
Referenced by TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), and FirstCompleteAPGenerator::ProcessPulses().
{
  // Clear the vector of pulse candidate locations first since it will still contain them from previous pulses
  fPulseCandidateLocations.clear();
  fPulseIsland = pulse;
  // We have a different algorithm for fast and slow pulses
  if (fChannel.isFast()) {
    FindCandidatePulses_Fast(fParameterValue);
  }
  else if (fChannel.isSlow()) {
    FindCandidatePulses_Slow(fParameterValue);
  }
  else {
    // this is a scintillator so do the fast pulse analysis
    FindCandidatePulses_Fast(fParameterValue);
  }
}
int PulseCandidateFinder::GetNPulseCandidates () [inline]
Returns the number of pulse candidates that were found.
Definition at line 66 of file PulseCandidateFinder.h.
References fPulseCandidateLocations.
Referenced by TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), and FirstCompleteAPGenerator::ProcessPulses().
{ return fPulseCandidateLocations.size(); }
void PulseCandidateFinder::GetPulseCandidates (std::vector< TPulseIsland * > & pulse_candidates) const
Returns the actual TPulseIsland of each candidate.
GetPulseCandidates() Fills a vector of the TPulseIslands of the pulse candidates that have been found
Definition at line 75 of file PulseCandidateFinder.cpp.
References fPulseCandidateLocations, fPulseIsland, TPulseIsland::GetBankName(), TPulseIsland::GetSamples(), TPulseIsland::GetTimeStamp(), TPulseIsland::SetBankName(), TPulseIsland::SetSamples(), and TPulseIsland::SetTimeStamp().
Referenced by FirstCompleteAPGenerator::ProcessPulses().
{
  // Loop through the pulse candidate locations
  std::vector<int>::const_iterator start_new, stop_new;
  for (std::vector<Location>::const_iterator locationIter = fPulseCandidateLocations.begin();
          locationIter != fPulseCandidateLocations.end(); ++locationIter) {
    // Get iterator to the start locations
    start_new=fPulseIsland->GetSamples().begin();
    std::advance(start_new,locationIter->start);
    // Get iterator to the stop locations
    stop_new=fPulseIsland->GetSamples().begin();
    std::advance(stop_new,locationIter->stop);
    // Get the bank name and work out what the new timestamp will be
    std::string bankname = fPulseIsland->GetBankName();
    int new_timestamp = fPulseIsland->GetTimeStamp() + locationIter->start;
    // Make the new TPI
    int index=locationIter-fPulseCandidateLocations.begin();
    if((int)pulse_candidates.size() <= index || !pulse_candidates.at(index)){
        TPulseIsland* pulse_island = new TPulseIsland(new_timestamp, start_new, stop_new, bankname);
        pulse_candidates.push_back(pulse_island);
    }else{
        TPulseIsland* pulse_island=pulse_candidates.at(index);
        pulse_island->SetSamples(start_new,stop_new);
        pulse_island->SetTimeStamp(new_timestamp);
        pulse_island->SetBankName(bankname);
    }
  }
  for(unsigned int i=fPulseCandidateLocations.size();i< pulse_candidates.size();++i){
      pulse_candidates.at(i)->Reset();
  }
}
void PulseCandidateFinder::SetDefaultParameterValues () [private]
Called in the constructor if fDefaultParameterValues is empty, so that it can be filled.
SetDefaultParameterValues Sets the default parameter values
Definition at line 295 of file PulseCandidateFinder.cpp.
References fDefaultParameterValues.
Referenced by PulseCandidateFinder().
{
  // Set all the default values for the fast channels
  fDefaultParameterValues[IDs::channel("muSc")] = 300;
  fDefaultParameterValues[IDs::channel("muScA")] = 100;
  fDefaultParameterValues[IDs::channel("NDet")] = 100;
  fDefaultParameterValues[IDs::channel("NDet2")] = 100;
  fDefaultParameterValues[IDs::channel("Ge-F")] = 40;
  fDefaultParameterValues[IDs::channel("ScL")] = 15;
  fDefaultParameterValues[IDs::channel("ScR")] = 20;
  fDefaultParameterValues[IDs::channel("ScGe")] = 20;
  fDefaultParameterValues[IDs::channel("ScVe")] = 30;
  fDefaultParameterValues[IDs::channel("SiL2-F")] = 80;
  fDefaultParameterValues[IDs::channel("SiL1-1-F")] = 40;
  fDefaultParameterValues[IDs::channel("SiL1-2-F")] = 20;
  fDefaultParameterValues[IDs::channel("SiL1-3-F")] = 20;
  fDefaultParameterValues[IDs::channel("SiL1-4-F")] = 80;
  fDefaultParameterValues[IDs::channel("SiR2-F")] = 20;
  fDefaultParameterValues[IDs::channel("SiR1-1-F")] = 40;
  fDefaultParameterValues[IDs::channel("SiR1-2-F")] = 60;
  fDefaultParameterValues[IDs::channel("SiR1-3-F")] = 80;
  fDefaultParameterValues[IDs::channel("SiR1-4-F")] = 40;
  // Set all the default values for the slow parameters
  fDefaultParameterValues[IDs::channel("Ge-S")] = 500;
  fDefaultParameterValues[IDs::channel("SiL2-S")] = 20;
  fDefaultParameterValues[IDs::channel("SiL1-1-S")] = 20;
  fDefaultParameterValues[IDs::channel("SiL1-2-S")] = 150;
  fDefaultParameterValues[IDs::channel("SiL1-3-S")] = 20;
  fDefaultParameterValues[IDs::channel("SiL1-4-S")] = 40;
  fDefaultParameterValues[IDs::channel("SiR2-S")] = 50;
  fDefaultParameterValues[IDs::channel("SiR1-1-S")] = 50;
  fDefaultParameterValues[IDs::channel("SiR1-2-S")] = 30;
  fDefaultParameterValues[IDs::channel("SiR1-3-S")] = 40;
  fDefaultParameterValues[IDs::channel("SiR1-4-S")] = 40;
}
void PulseCandidateFinder::SetOneSigmaValues () [private]
Called if "n_sigma" is specified as an option in the modules file and if fOneSigmaValues is empty.
SetOneSigmaValues() Sets the one sigma values that we get from the text file TODO: use SetupNavigator::GetPedestalError instead of doing it ourselves
Definition at line 344 of file PulseCandidateFinder.cpp.
References fOneSigmaValues.
Referenced by PulseCandidateFinder().
{
  // The values that we will read in
  std::string run_number;
  std::string detname, bankname;
  std::string pedestal, noise;
  // Get the SQLite database file
  TSQLiteServer* server = new TSQLiteServer("sqlite://pedestals-and-noises.sqlite");
  std::stringstream query;
  std::string tablename = "pedestals_and_noises";
  if (server) {
    query << "SELECT * FROM " << tablename << ";"; // get all the pedestals and noises
    TSQLiteResult* result = (TSQLiteResult*) server->Query(query.str().c_str());  // get the result of this query
    query.str(""); // clear the stringstream after use
    TSQLiteRow* row = (TSQLiteRow*) result->Next(); // get the first row
    while (row != NULL) {
      //      std::cout << row->GetField(0) << " " << row->GetField(1) << " " << row->GetField(2) << " " << row->GetField(3) << " " << row->GetField(4) << std::endl;
      run_number = row->GetField(0);
      detname = row->GetField(1);
      bankname = row->GetField(2);
      pedestal = row->GetField(3);
      noise = row->GetField(4);
      fOneSigmaValues[IDs::channel(detname)] = atof(noise.c_str());
      delete row;
      row = (TSQLiteRow*) result->Next(); // get the next row
    }
    delete result; // user has to delete the result
  }
  else {
    std::cout << "Error: Couldn't connect to SQLite database" << std::endl;
  }
}
void PulseCandidateFinder::SetPedestalValues () [private]
Called to set the pedestal values.
SetPedestalValues() Sets the one sigma values that we get from the text file TODO: use SetupNavigator::GetPedestal instead of doing it ourselves
Definition at line 389 of file PulseCandidateFinder.cpp.
References fPedestalValues.
Referenced by PulseCandidateFinder().
{
  // The values that we will read in
  std::string run_number;
  std::string detname, bankname;
  std::string pedestal, noise;
  // Get the SQLite database file
  TSQLiteServer* server = new TSQLiteServer("sqlite://pedestals-and-noises.sqlite");
  std::stringstream query;
  std::string tablename = "pedestals_and_noises";
  if (server) {
    query << "SELECT * FROM " << tablename << ";"; // get all the pedestals and noises
    TSQLiteResult* result = (TSQLiteResult*) server->Query(query.str().c_str());  // get the result of this query
    query.str(""); // clear the stringstream after use
    TSQLiteRow* row = (TSQLiteRow*) result->Next(); // get the first row
    while (row != NULL) {
      //      std::cout << row->GetField(0) << " " << row->GetField(1) << " " << row->GetField(2) << " " << row->GetField(3) << " " << row->GetField(4) << std::endl;
      run_number = row->GetField(0);
      detname = row->GetField(1);
      bankname = row->GetField(2);
      pedestal = row->GetField(3);
      noise = row->GetField(4);
      fPedestalValues[IDs::channel(detname)] = atof(pedestal.c_str());
      delete row;
      row = (TSQLiteRow*) result->Next(); // get the next row
    }
    delete result; // user has to delete the result
  }
  else {
    std::cout << "Error: Couldn't connect to SQLite database" << std::endl;
  }
}
Member Data Documentation
IDs::channel PulseCandidateFinder::fChannel [private]
The channel that this PulseCandidateFinder works on.
Definition at line 108 of file PulseCandidateFinder.h.
Referenced by FindPulseCandidates(), and PulseCandidateFinder().
std::map< IDs::channel, int > PulseCandidateFinder::fDefaultParameterValues [static, private]
The map that stores the default parameter values in case there isn't one specified in the modules file.
Need to declare this outside of any method.
Definition at line 121 of file PulseCandidateFinder.h.
Referenced by PulseCandidateFinder(), and SetDefaultParameterValues().
double PulseCandidateFinder::fNoise [private]
The noise value for this channel.
Definition at line 114 of file PulseCandidateFinder.h.
Referenced by FindCandidatePulses_Fast(), FindCandidatePulses_Slow(), and PulseCandidateFinder().
int PulseCandidateFinder::fNSigma [private]
The number of sigma (i.e. noise) that we want the threshold to be set to.
Definition at line 128 of file PulseCandidateFinder.h.
Referenced by PulseCandidateFinder().
std::map< IDs::channel, double > PulseCandidateFinder::fOneSigmaValues [static, private]
The map that stores the one sigma values that we get from the SQLite database.
Need to declare this outside of any method.
Definition at line 131 of file PulseCandidateFinder.h.
Referenced by PulseCandidateFinder(), and SetOneSigmaValues().
double PulseCandidateFinder::fParameterValue [private]
The value of the parameter to start a candidate pulse.
Definition at line 111 of file PulseCandidateFinder.h.
Referenced by FindPulseCandidates(), and PulseCandidateFinder().
double PulseCandidateFinder::fPedestal [private]
The pedestal value for this channel.
Definition at line 117 of file PulseCandidateFinder.h.
Referenced by FillSampleDifferencesHistogram(), FillSampleHeightsHistogram(), FindCandidatePulses_Fast(), FindCandidatePulses_Slow(), and PulseCandidateFinder().
std::map< IDs::channel, double > PulseCandidateFinder::fPedestalValues [static, private]
The map that stores the pedestal values that we get from the SQLite database.
Need to declare this outside of any method.
Definition at line 138 of file PulseCandidateFinder.h.
Referenced by PulseCandidateFinder(), and SetPedestalValues().
std::vector<Location> PulseCandidateFinder::fPulseCandidateLocations [private]
The vector that we store the pulse candidate locations in.
Definition at line 57 of file PulseCandidateFinder.h.
Referenced by FindCandidatePulses_Fast(), FindCandidatePulses_Slow(), FindPulseCandidates(), GetNPulseCandidates(), and GetPulseCandidates().
TPulseIsland* PulseCandidateFinder::fPulseIsland [private]
The TPulseIsland that we are looking for candidates on.
Definition at line 54 of file PulseCandidateFinder.h.
Referenced by FillParameterHistogram(), FillSampleDifferencesHistogram(), FillSampleHeightsHistogram(), FindCandidatePulses_Fast(), FindCandidatePulses_Slow(), FindPulseCandidates(), and GetPulseCandidates().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/utils/PulseCandidateFinder.h
rootana/src/TAP_generators/utils/PulseCandidateFinder.cpp