AlcapDAQ: G__Sizep2memfuncfileY4ZaA5 Class Reference
G__Sizep2memfuncfileY4ZaA5 Class Reference
Public Member Functions
G__Sizep2memfuncfileY4ZaA5 ()
size_t sizep2memfunc ()
Private Attributes
size_t(G__Sizep2memfuncfileY4ZaA5::* p)()
Detailed Description
Definition at line 95 of file fileY4ZaA5.cxx.
Constructor & Destructor Documentation
G__Sizep2memfuncfileY4ZaA5::G__Sizep2memfuncfileY4ZaA5 () inline
Definition at line 97 of file fileY4ZaA5.cxx.
References sizep2memfunc().
 {p=&G__Sizep2memfuncfileY4ZaA5::sizep2memfunc;}
Member Function Documentation
size_t G__Sizep2memfuncfileY4ZaA5::sizep2memfunc () inline
Definition at line 98 of file fileY4ZaA5.cxx.
Referenced by G__get_sizep2memfuncfileY4ZaA5(), and G__Sizep2memfuncfileY4ZaA5().
 { return(sizeof(p)); }
Field Documentation
size_t(G__Sizep2memfuncfileY4ZaA5::* G__Sizep2memfuncfileY4ZaA5::p)() private
Definition at line 100 of file fileY4ZaA5.cxx.
The documentation for this class was generated from the following file:
www/html/online/wfd/fileY4ZaA5.cxx