AlcapDAQ: PlotAmpVsTDiff Class Reference
PlotAmpVsTDiff Class Reference
#include <PlotAmpVsTDiff.h>
Public Member Functions
PlotAmpVsTDiff (char *HistogramDirectoryName, std::string det_name_a, std::string det_name_b)
PlotAmpVsTDiff (modules::options *opts)
~PlotAmpVsTDiff ()
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
The big kahuna. Overload this in the derived class and it will be called for each event.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
Private Attributes
TH2F * amp_vs_tdiff_plot_coarse
TH2F * amp_vs_tdiff_plot_fine
std::string fDetNameA
std::string fDetNameB
Detailed Description
Definition at line 11 of file PlotAmpVsTDiff.h.
Constructor & Destructor Documentation
PlotAmpVsTDiff::PlotAmpVsTDiff (char * HistogramDirectoryName, std::string det_name_a, std::string det_name_b)
Definition at line 25 of file PlotAmpVsTDiff.cpp.
References amp_vs_tdiff_plot_coarse, amp_vs_tdiff_plot_fine, BaseModule::dir, fDetNameA, fDetNameB, TSetupData::GetNBits(), and TSetupData::Instance().
                                                                                                       :
  BaseModule(HistogramDirectoryName){
  fDetNameA = det_name_a;
  fDetNameB = det_name_b;
  // hAmpVsTDiff
  std::string histname = "h" + fDetNameA + "-" + fDetNameB + "_AmpVsTDiff_Coarse";
  std::string histtitle = "Plot of the amplitude vs time difference for the " + fDetNameA + " and " + fDetNameB + " detector";
  int n_bits = TSetupData::Instance()->GetNBits(TSetupData::Instance()->GetBankName(fDetNameB));
  double max_adc_value = std::pow(2, n_bits);
  std::string x_axis_title = "Time Difference (" + fDetNameB + " - " + fDetNameA + ") [ns]";
  std::string y_axis_title = "Amplitude of " + fDetNameB + " [ADC Value]";
  amp_vs_tdiff_plot_coarse = new TH2F(histname.c_str(), histtitle.c_str(), 100,-50000,50000, max_adc_value,0,max_adc_value);
  amp_vs_tdiff_plot_coarse->GetXaxis()->SetTitle(x_axis_title.c_str());
  amp_vs_tdiff_plot_coarse->GetYaxis()->SetTitle(y_axis_title.c_str());
  histname = "h" + fDetNameA + "-" + fDetNameB + "_AmpVsTDiff_Fine";
  amp_vs_tdiff_plot_fine = new TH2F(histname.c_str(), histtitle.c_str(), 5000,-5000,20000, max_adc_value,0,max_adc_value);
  amp_vs_tdiff_plot_fine->GetXaxis()->SetTitle(x_axis_title.c_str());
  amp_vs_tdiff_plot_fine->GetYaxis()->SetTitle(y_axis_title.c_str());
  dir->cd("/");
}
PlotAmpVsTDiff::PlotAmpVsTDiff (modules::options * opts)
Definition at line 52 of file PlotAmpVsTDiff.cpp.
References amp_vs_tdiff_plot_coarse, amp_vs_tdiff_plot_fine, BaseModule::dir, fDetNameA, fDetNameB, TSetupData::GetNBits(), modules::options::GetString(), and TSetupData::Instance().
                                                   : BaseModule( (opts->GetString("0")).c_str() ) {
  fDetNameA = opts->GetString("1");
  fDetNameB = opts->GetString("2");
  // hAmpVsTDiff
  std::string histname = "h" + fDetNameA + "-" + fDetNameB + "_AmpVsTDiff_Coarse";
  std::string histtitle = "Plot of the amplitude vs time difference for the " + fDetNameA + " and " + fDetNameB + " detector";
  int n_bits = TSetupData::Instance()->GetNBits(TSetupData::Instance()->GetBankName(fDetNameB));
  double max_adc_value = std::pow(2, n_bits);
  std::string x_axis_title = "Time Difference (" + fDetNameB + " - " + fDetNameA + ") [ns]";
  std::string y_axis_title = "Amplitude of " + fDetNameB + " [ADC Value]";
  amp_vs_tdiff_plot_coarse = new TH2F(histname.c_str(), histtitle.c_str(), 100,-50000,50000, max_adc_value,0,max_adc_value);
  amp_vs_tdiff_plot_coarse->GetXaxis()->SetTitle(x_axis_title.c_str());
  amp_vs_tdiff_plot_coarse->GetYaxis()->SetTitle(y_axis_title.c_str());
  histname = "h" + fDetNameA + "-" + fDetNameB + "_AmpVsTDiff_Fine";
  amp_vs_tdiff_plot_fine = new TH2F(histname.c_str(), histtitle.c_str(), 5000,-5000,20000, max_adc_value,0,max_adc_value);
  amp_vs_tdiff_plot_fine->GetXaxis()->SetTitle(x_axis_title.c_str());
  amp_vs_tdiff_plot_fine->GetYaxis()->SetTitle(y_axis_title.c_str());
  dir->cd("/");
}
PlotAmpVsTDiff::~PlotAmpVsTDiff ()
Definition at line 78 of file PlotAmpVsTDiff.cpp.
{
}
Member Function Documentation
virtual int PlotAmpVsTDiff::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [inline, private, virtual]
Optional method which is called once after the main event loop Can be used to dump a summary or finalise a histogram
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 19 of file PlotAmpVsTDiff.h.
{return 0;};
virtual int PlotAmpVsTDiff::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [inline, private, virtual]
Optional method which is called once before the main event loop Can be used to parse options and setup histograms.
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 20 of file PlotAmpVsTDiff.h.
{return 0;};
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int PlotAmpVsTDiff::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
The big kahuna. Overload this in the derived class and it will be called for each event.
Parameters:
gData Pointer to current map of all TPIs [ WILL CHANGE SHORTLY ]
gSetup Pointer to TSetupData for this run [ WILL CHANGE SHORTLY ]
Returns:
0 on success and non-zero on failure
Implements BaseModule.
Definition at line 81 of file PlotAmpVsTDiff.cpp.
References amp_vs_tdiff_plot_coarse, amp_vs_tdiff_plot_fine, fDetNameA, fDetNameB, and gAnalysedPulseMap.
{
  // Get the detA and detB pulses ready but make sure they exist first
  AnalysedPulseList detA_pulses;
  AnalysedPulseList detB_pulses;
  if (gAnalysedPulseMap.find(fDetNameA) == gAnalysedPulseMap.end()) {
    std::cout << fDetNameA << " pulses not found" << std::endl;
  }
  else {
      detA_pulses = gAnalysedPulseMap[fDetNameA];
  }
  if (gAnalysedPulseMap.find(fDetNameB) == gAnalysedPulseMap.end()) {
    std::cout << fDetNameB << " pulses not found" << std::endl;
  }
  else {
      detB_pulses = gAnalysedPulseMap[fDetNameB];
  }
  AnalysedPulseList::iterator currentDetAPulse = detA_pulses.begin(); // want to keep track of how far we are through the detA pulses
  // Loop through the detB pulses
  for (AnalysedPulseList::iterator detBPulseIter = detB_pulses.begin(); detBPulseIter != detB_pulses.end(); ++detBPulseIter) {
    // Loop through the detA pulses
    //bool coinc_found = false;
    for (AnalysedPulseList::iterator detAPulseIter = currentDetAPulse; detAPulseIter != detA_pulses.end(); ++detAPulseIter) {
      double detB_time = (*detBPulseIter)->GetTime();
      double detA_time = (*detAPulseIter)->GetTime();
      double t_diff = detB_time - detA_time;
      double detB_amplitude = (*detBPulseIter)->GetAmplitude();
      amp_vs_tdiff_plot_coarse->Fill(t_diff, detB_amplitude);
      amp_vs_tdiff_plot_fine->Fill(t_diff, detB_amplitude);
    } // end loop through detA pulses
  } // end loop through detB pulses
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TH2F* PlotAmpVsTDiff::amp_vs_tdiff_plot_coarse [private]
Definition at line 20 of file PlotAmpVsTDiff.h.
Referenced by PlotAmpVsTDiff(), and ProcessEntry().
TH2F* PlotAmpVsTDiff::amp_vs_tdiff_plot_fine [private]
Definition at line 23 of file PlotAmpVsTDiff.h.
Referenced by PlotAmpVsTDiff(), and ProcessEntry().
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff().
std::string PlotAmpVsTDiff::fDetNameA [private]
Definition at line 26 of file PlotAmpVsTDiff.h.
Referenced by PlotAmpVsTDiff(), and ProcessEntry().
std::string PlotAmpVsTDiff::fDetNameB [private]
Definition at line 27 of file PlotAmpVsTDiff.h.
Referenced by PlotAmpVsTDiff(), and ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/plotters/legacy/PlotAmpVsTDiff.h
rootana/src/plotters/legacy/PlotAmpVsTDiff.cpp