AlcapDAQ: TemplateConvolver Class Reference
TemplateConvolver Class Reference
#include <TemplateConvolver.h>
Classes
struct FoundPeaks
Public Types
typedef std::set< FoundPeaks > PeaksVector
typedef std::vector< double > SamplesVector
Public Member Functions
TemplateConvolver (const IDs::channel ch, TTemplate *tpl, int peak_fit_samples, int left, int right)
~TemplateConvolver ()
bool IsValid () const
int Convolve (const Algorithm::TpiMinusPedestal_iterator &begin, const Algorithm::TpiMinusPedestal_iterator &end)
void CharacteriseTemplate ()
const SamplesVector & GetEnergyConvolution () const
const SamplesVector & GetTimeConvolution () const
const PeaksVector & GetPeaks () const
double GetTimeShift () const
double GetLeftSafety () const
double GetAmplitudeScale () const
TH1 * GetTemplateACF () const
int FindPeaks (bool expect_pile_up, const Algorithm::TpiMinusPedestal_iterator &waveform)
Private Member Functions
int FindAllPeaks (const SamplesVector &, const SamplesVector &, const Algorithm::TpiMinusPedestal_iterator *pedestal)
int FindBestPeak (const SamplesVector &, const SamplesVector &, const Algorithm::TpiMinusPedestal_iterator *pedestal)
void FitPeak (FoundPeaks &output, int index, const SamplesVector &energy, const SamplesVector &time, double pedestal)
bool ResetVectors (int size)
Private Attributes
IDs::channel fChannel
TTemplate * fTemplate
Algorithm::Convolver
< Algorithm::TH1_c_iterator > * fEnergyConvolve
Algorithm::Convolver
< std::vector< int >::iterator > * fTimeConvolve
functions::QuadraticFit fQuadFit
const int fPolarity
const int fLeftSafety
const int fRightSafety
const int fTemplateLength
const double fTemplateTime
double fTemplateQuad
double fTemplateLin
double fTemplateConst
double fTemplateScale
PeaksVector fPeaks
SamplesVector fEnergySamples
SamplesVector fTimeSamples
std::vector< int > fTimeWeights
SamplesVector fTemplateACF
SamplesVector fTemplateACFDerivative
TH1 * fTemplateACFHist
TH1 * fTemplateACFDerivativeHist
Detailed Description
Definition at line 15 of file TemplateConvolver.h.
Member Typedef Documentation
typedef std::set<FoundPeaks> TemplateConvolver::PeaksVector
Definition at line 38 of file TemplateConvolver.h.
typedef std::vector<double> TemplateConvolver::SamplesVector
Definition at line 39 of file TemplateConvolver.h.
Constructor & Destructor Documentation
TemplateConvolver::TemplateConvolver (const IDs::channel ch, TTemplate * tpl, int peak_fit_samples, int left, int right)
Definition at line 13 of file TemplateConvolver.cpp.
References fEnergyConvolve, fLeftSafety, fRightSafety, fTemplate, fTemplateLength, fTimeConvolve, fTimeWeights, and TTemplate::GetHisto().
                                                                                                                  :
     fChannel(ch), fTemplate(tpl),fQuadFit(peak_fit_samples), fPolarity(EventNavigator::GetSetupRecord().GetPolarity(ch)),
     fLeftSafety(left),fRightSafety(right),
     fTemplateLength(fTemplate->GetHisto()->GetNbinsX() - fLeftSafety - fRightSafety),
     fTemplateTime(fTemplate->GetTime()-fLeftSafety){
   if(fTemplateLength <0) return;
   TH1_wrapper hist(fTemplate->GetHisto());
   fEnergyConvolve=new Convolver<TH1_c_iterator>(hist.begin(fLeftSafety), hist.end(fRightSafety));
   const int num_weights=2;
   const int weights[num_weights]={-1,1};
   fTimeWeights.assign(weights, weights+num_weights);
   fTimeConvolve=new Convolver<std::vector<int>::iterator>(fTimeWeights.begin(),fTimeWeights.end());
}
TemplateConvolver::~TemplateConvolver ()
Definition at line 29 of file TemplateConvolver.cpp.
References fEnergyConvolve, and fTimeConvolve.
{
  delete fTimeConvolve;
  delete fEnergyConvolve;
}
Member Function Documentation
void TemplateConvolver::CharacteriseTemplate ()
Definition at line 121 of file TemplateConvolver.cpp.
References fEnergyConvolve, FindBestPeak(), fPeaks, fTemplate, fTemplateACF, fTemplateACFDerivative, fTemplateACFDerivativeHist, fTemplateACFHist, fTemplateConst, fTemplateLength, fTemplateLin, fTemplateQuad, fTemplateScale, fTemplateTime, fTimeConvolve, fTimeWeights, TTemplate::GetAmplitude(), TTemplate::GetHisto(), Algorithm::Convolver< WeightIterator >::Process(), and functions::VectorToHist().
Referenced by TemplateConvolveAPGenerator::TemplateConvolveAPGenerator().
{
   fPeaks.clear();
   // prepare vectors / iterators
   TH1_wrapper hist(fTemplate->GetHisto());
   fTemplateACF.assign(fTemplate->GetHisto()->GetNbinsX()- fTemplateLength,0);
   fTemplateACFDerivative.assign(fTemplateACF.size()- fTimeWeights.size(),0);
   // Run convolution
   fEnergyConvolve->Process(hist.begin(), hist.end(), fTemplateACF.begin());
   fTimeConvolve->Process(fTemplateACF.begin(), fTemplateACF.end(), fTemplateACFDerivative.begin());
   FindBestPeak(fTemplateACF, fTemplateACFDerivative, NULL);
   // Prepare the quadratic coefficients of the template itself
   fTemplateQuad=fPeaks.begin()->quad;
   fTemplateLin=fPeaks.begin()->linear;
   fTemplateConst=fPeaks.begin()->constant;
   fTemplateScale=fTemplate->GetAmplitude();
   fTemplateScale/=fPeaks.begin()->constant - fPeaks.begin()->linear*fPeaks.begin()->linear/4/fPeaks.begin()->quad;
   // Convert to histograms
   fTemplateACFHist=functions::VectorToHist(fTemplateACF,"Template_ACF","Auto-correlation of template");
   TF1* fit=new TF1("Fit","[0]*(x-[3])**2+[1]*(x-[3])+[2]", 0 , fTemplateACFHist->GetNbinsX());
   fit->SetParameter(0,fTemplateQuad);
   fit->SetParameter(1,fTemplateLin);
   fit->SetParameter(2,fTemplateConst);
   fit->SetParameter(3,fPeaks.begin()->time + fTemplateTime);
   fTemplateACFHist->GetListOfFunctions()->Add(fit);
   fTemplateACFHist->Clone()->Write();
   fTemplateACFDerivativeHist=functions::VectorToHist(fTemplateACFDerivative,"Template_ACF_derivative","Derivative of auto-correlation of template");
   fTemplateACFDerivativeHist->Clone()->Write();
   fPeaks.clear();
}
int TemplateConvolver::Convolve (const Algorithm::TpiMinusPedestal_iterator & begin, const Algorithm::TpiMinusPedestal_iterator & end)
Definition at line 34 of file TemplateConvolver.cpp.
References fEnergyConvolve, fEnergySamples, fTimeConvolve, fTimeSamples, Algorithm::Convolver< WeightIterator >::Process(), and ResetVectors().
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{
   // initialize for convolution
   if(!ResetVectors(end - begin)){
     return -1;
   }
   // convole the waveform with the template
   fEnergyConvolve->Process(begin,end, fEnergySamples.begin());
   // now run the timing filter (in the future this and the last step could be merged)
   fTimeConvolve->Process(fEnergySamples.begin(),fEnergySamples.end(),fTimeSamples.begin());
   return 0;
}
int TemplateConvolver::FindAllPeaks (const SamplesVector & energy, const SamplesVector & time, const Algorithm::TpiMinusPedestal_iterator * pedestal) [private]
Definition at line 64 of file TemplateConvolver.cpp.
References FitPeak(), fPeaks, and Algorithm::Pedestal_iterator< InputIterator >::GetPedestal().
Referenced by FindPeaks().
{
   double last_sample=time.front();
   FoundPeaks tmp=FoundPeaks();
   for(SamplesVector::const_iterator i_sample=time.begin()+1; i_sample!=time.end(); ++i_sample){
// check if we've crossed zero gradient (signs will be different => product is less than zero)
// and check we crossed in the right direction
      if( (last_sample * *i_sample)<0 && (*i_sample - last_sample ) <0 ){
        int peak=i_sample - time.begin();
        if(pedestal) FitPeak(tmp, peak, energy, time,pedestal->GetPedestal());
        else FitPeak(tmp, peak, energy, time, 0);
        fPeaks.insert(tmp);
      }
      last_sample = *i_sample;
   }
   return fPeaks.size();
}
int TemplateConvolver::FindBestPeak (const SamplesVector & energy, const SamplesVector & time, const Algorithm::TpiMinusPedestal_iterator * pedestal) [private]
Definition at line 83 of file TemplateConvolver.cpp.
References TemplateConvolver::FoundPeaks::amplitude, FitPeak(), fPeaks, and Algorithm::Pedestal_iterator< InputIterator >::GetPedestal().
Referenced by CharacteriseTemplate(), and FindPeaks().
{
   double last_sample=time.front();
   double best_amp=-1e9;
   FoundPeaks tmp=FoundPeaks();
   FoundPeaks best=FoundPeaks();
   int peak_count=0;
   for(SamplesVector::const_iterator i_sample=time.begin()+1; i_sample!=time.end(); ++i_sample){
      if( last_sample>0 && *i_sample<0){
        int peak=i_sample - time.begin();
        if(pedestal) FitPeak(tmp, peak, energy, time,pedestal->GetPedestal());
        else FitPeak(tmp, peak, energy, time, 0);
        if( (tmp.amplitude > best_amp) ){
            best=tmp;
            best_amp=tmp.amplitude;
        }
        ++peak_count;
      }
      last_sample = *i_sample;
   }
   fPeaks.insert(best);
   return peak_count;
}
int TemplateConvolver::FindPeaks (bool expect_pile_up, const Algorithm::TpiMinusPedestal_iterator & waveform)
Definition at line 59 of file TemplateConvolver.cpp.
References fEnergySamples, FindAllPeaks(), FindBestPeak(), and fTimeSamples.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{
   if(expect_pile_up) return FindAllPeaks(fEnergySamples, fTimeSamples,&waveform);
   return FindBestPeak(fEnergySamples, fTimeSamples,&waveform);
}
void TemplateConvolver::FitPeak (FoundPeaks & output, int index, const SamplesVector & energy, const SamplesVector & time, double pedestal) [private]
Definition at line 108 of file TemplateConvolver.cpp.
References TemplateConvolver::FoundPeaks::amplitude, TemplateConvolver::FoundPeaks::constant, functions::QuadraticFit::Fit(), fQuadFit, functions::QuadraticFit::GetSize(), TemplateConvolver::FoundPeaks::linear, TemplateConvolver::FoundPeaks::pedestal, TemplateConvolver::FoundPeaks::quad, and TemplateConvolver::FoundPeaks::time.
Referenced by FindAllPeaks(), and FindBestPeak().
{
   // about where do need to fit?
   int peak=(fQuadFit.GetSize()-1)/2;
   // if the index we've been asked to fit to is greater than the minimum needed samples then use that
   if( index > peak) peak=index-peak;
   // run the fit calculation
   fQuadFit.Fit(energy.begin() + peak, output.quad, output.linear, output.constant);
   output.time= index + output.linear/2/output.quad;
   output.pedestal=pedestal;
   output.amplitude=output.constant - output.linear*output.linear/4/output.quad;
}
double TemplateConvolver::GetAmplitudeScale () const [inline]
Definition at line 55 of file TemplateConvolver.h.
References fTemplateScale.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{return fTemplateScale;}
const SamplesVector& TemplateConvolver::GetEnergyConvolution () const [inline]
Definition at line 50 of file TemplateConvolver.h.
References fEnergySamples.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{return fEnergySamples;};
double TemplateConvolver::GetLeftSafety () const [inline]
Definition at line 54 of file TemplateConvolver.h.
References fLeftSafety.
{return fLeftSafety;}
const PeaksVector& TemplateConvolver::GetPeaks () const [inline]
Definition at line 52 of file TemplateConvolver.h.
References fPeaks.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{return fPeaks;};
TH1* TemplateConvolver::GetTemplateACF () const [inline]
Definition at line 56 of file TemplateConvolver.h.
References fTemplateACFHist.
{return fTemplateACFHist;}
const SamplesVector& TemplateConvolver::GetTimeConvolution () const [inline]
Definition at line 51 of file TemplateConvolver.h.
References fTimeSamples.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{return fTimeSamples;};
double TemplateConvolver::GetTimeShift () const [inline]
Definition at line 53 of file TemplateConvolver.h.
References fTemplateTime.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{return fTemplateTime;}
bool TemplateConvolver::IsValid () const [inline]
Definition at line 44 of file TemplateConvolver.h.
References fTemplateLength.
{return fTemplateLength>0;}
bool TemplateConvolver::ResetVectors (int size) [private]
Definition at line 49 of file TemplateConvolver.cpp.
References fEnergySamples, fPeaks, fTemplateLength, fTimeSamples, and fTimeWeights.
Referenced by Convolve().
{
   // make sure we're big enough for the number of samples we'll get
   size-=fTemplateLength;
   if( size < 1 ) return false;
   fEnergySamples.resize(size);
   fTimeSamples.resize(size - fTimeWeights.size() );
   fPeaks.clear();
   return true;
}
Member Data Documentation
IDs::channel TemplateConvolver::fChannel [private]
Definition at line 67 of file TemplateConvolver.h.
Algorithm::Convolver<Algorithm::TH1_c_iterator>* TemplateConvolver::fEnergyConvolve [private]
Definition at line 69 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate(), Convolve(), TemplateConvolver(), and ~TemplateConvolver().
SamplesVector TemplateConvolver::fEnergySamples [private]
Definition at line 78 of file TemplateConvolver.h.
Referenced by Convolve(), FindPeaks(), GetEnergyConvolution(), and ResetVectors().
const int TemplateConvolver::fLeftSafety [private]
Definition at line 73 of file TemplateConvolver.h.
Referenced by GetLeftSafety(), and TemplateConvolver().
PeaksVector TemplateConvolver::fPeaks [private]
Definition at line 77 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate(), FindAllPeaks(), FindBestPeak(), GetPeaks(), and ResetVectors().
const int TemplateConvolver::fPolarity [private]
Definition at line 72 of file TemplateConvolver.h.
functions::QuadraticFit TemplateConvolver::fQuadFit [private]
Definition at line 71 of file TemplateConvolver.h.
Referenced by FitPeak().
const int TemplateConvolver::fRightSafety [private]
Definition at line 73 of file TemplateConvolver.h.
Referenced by TemplateConvolver().
TTemplate* TemplateConvolver::fTemplate [private]
Definition at line 68 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate(), and TemplateConvolver().
SamplesVector TemplateConvolver::fTemplateACF [private]
Definition at line 81 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate().
SamplesVector TemplateConvolver::fTemplateACFDerivative [private]
Definition at line 81 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate().
TH1 * TemplateConvolver::fTemplateACFDerivativeHist [private]
Definition at line 82 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate().
TH1* TemplateConvolver::fTemplateACFHist [private]
Definition at line 82 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate(), and GetTemplateACF().
double TemplateConvolver::fTemplateConst [private]
Definition at line 76 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate().
const int TemplateConvolver::fTemplateLength [private]
Definition at line 74 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate(), IsValid(), ResetVectors(), and TemplateConvolver().
double TemplateConvolver::fTemplateLin [private]
Definition at line 76 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate().
double TemplateConvolver::fTemplateQuad [private]
Definition at line 76 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate().
double TemplateConvolver::fTemplateScale [private]
Definition at line 76 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate(), and GetAmplitudeScale().
const double TemplateConvolver::fTemplateTime [private]
Definition at line 75 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate(), and GetTimeShift().
Algorithm::Convolver<std::vector<int>::iterator>* TemplateConvolver::fTimeConvolve [private]
Definition at line 70 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate(), Convolve(), TemplateConvolver(), and ~TemplateConvolver().
SamplesVector TemplateConvolver::fTimeSamples [private]
Definition at line 79 of file TemplateConvolver.h.
Referenced by Convolve(), FindPeaks(), GetTimeConvolution(), and ResetVectors().
std::vector<int> TemplateConvolver::fTimeWeights [private]
Definition at line 80 of file TemplateConvolver.h.
Referenced by CharacteriseTemplate(), ResetVectors(), and TemplateConvolver().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/template_fitting/TemplateConvolver.h
rootana/src/TAP_generators/template_fitting/TemplateConvolver.cpp