AlcapDAQ: MaxBinCFAPGenerator Class Reference
MaxBinCFAPGenerator Class Reference abstract
#include <MaxBinCFAPGenerator.h>
Public Member Functions
MaxBinCFAPGenerator (double fraction=0.5)
virtual void ProcessPulses (const TSetupData *, const PulseIslandList_t &, AnalysedPulseList_t &)
virtual int ProcessPulses (const PulseIslandList &, AnalysedPulseList &)=0
virtual bool MayDivideTPIs ()=0
void SetChannel (const std::string &det)
const char * GetChannel ()
bool Debug () const
Private Attributes
double fFraction
Detailed Description
Definition at line 8 of file MaxBinCFAPGenerator.h.
Constructor & Destructor Documentation
MaxBinCFAPGenerator::MaxBinCFAPGenerator (double fraction = 0.5)
Definition at line 18 of file MaxBinCFAPGenerator.cpp.
 : fFraction(fraction) {}
Member Function Documentation
bool TVAnalysedPulseGenerator::Debug () const inline inherited
Definition at line 30 of file TVAnalysedPulseGenerator.h.
 {return fDebug;};
const char* TVAnalysedPulseGenerator::GetChannel () inline inherited
Definition at line 29 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fDetector.
 {return fDetector.c_str();};
virtual bool TVAnalysedPulseGenerator::MayDivideTPIs () pure virtual inherited
Implemented in MaxBinAPGenerator.
void MaxBinCFAPGenerator::ProcessPulses (const TSetupData * eventSetup, const PulseIslandList_t & pulseList, AnalysedPulseList_t & analysedList) virtual
Definition at line 27 of file MaxBinCFAPGenerator.cpp.
References fFraction, TSetupData::GetClockTick(), TSetupData::GetDetectorName(), TSetupData::GetPedestal(), TSetupData::GetTimeShift(), TSetupData::GetTriggerPolarity(), gSetup, IsTimeOrdered(), ped, and samples.
virtual int TVAnalysedPulseGenerator::ProcessPulses (const PulseIslandList & , AnalysedPulseList &) pure virtual inherited
Implemented in MaxBinAPGenerator.
void TVAnalysedPulseGenerator::SetChannel (const std::string & det) inline inherited
Definition at line 28 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fDetector.
Referenced by MakeAnalysedPulses::AddGenerator().
 {fDetector=det;};
Field Documentation
double MaxBinCFAPGenerator::fFraction private
Definition at line 11 of file MaxBinCFAPGenerator.h.
Referenced by ProcessPulses().
The documentation for this class was generated from the following files:
analyzer/rootana/src/test/MaxBinCFAPGenerator.h
analyzer/rootana/src/test/MaxBinCFAPGenerator.cpp