AlcapDAQ: TMEAlgorithm::ActiveSiRStop Class Reference
TMEAlgorithm::ActiveSiRStop Class Reference
#include <ActiveSiRMuStopAlgo.h>
Public Member Functions
ActiveSiRStop (const IDs::source &sir2, double muSc_min, double muSc_max, double SiR2_min, double SiR2_max)
void SetSiR2Source (const IDs::source so)
bool operator() (const TMuonEvent *tme, TDetectorPulse::ParentChannel_t) const
Private Attributes
double fMuScMax
double fMuScMin
double fSiR2Max
double fSiR2Min
IDs::source fSiR2source
Detailed Description
Definition at line 12 of file ActiveSiRMuStopAlgo.h.
Constructor & Destructor Documentation
TMEAlgorithm::ActiveSiRStop::ActiveSiRStop (const IDs::source & sir2, double muSc_min, double muSc_max, double SiR2_min, double SiR2_max)
Definition at line 5 of file ActiveSiRMuStopAlgo.cpp.
                                                                                                                                 :
     fMuScMax(muSc_max),fMuScMin(muSc_min),  fSiR2Max(SiR2_max),fSiR2Min(SiR2_min),fSiR2source(sir2){
}
Member Function Documentation
bool TMEAlgorithm::ActiveSiRStop::operator() (const TMuonEvent * tme, TDetectorPulse::ParentChannel_t channel) const
Definition at line 10 of file ActiveSiRMuStopAlgo.cpp.
References fMuScMax, fMuScMin, fSiR2Max, fSiR2Min, fSiR2source, TDetectorPulse::GetAmplitude(), TMuonEvent::GetCentralMuon(), TMuonEvent::GetPulse(), TDetectorPulse::kFast, and TMuonEvent::NumPulses().
{
  const double muSc_amp=tme->GetCentralMuon()->GetAmplitude(TDetectorPulse::kFast);
  bool ret_val=false;
  if(muSc_amp>fMuScMin && muSc_amp< fMuScMax){
    const int N_sir2=tme->NumPulses(fSiR2source);
    for(int i=0; i< N_sir2; ++i){
      const double sir2_amp=tme->GetPulse(fSiR2source,i)->GetAmplitude(channel);
      if(sir2_amp > fSiR2Min && sir2_amp < fSiR2Max){
         ret_val=true;
         break;
      }
    }
  }
  return ret_val;
}
void TMEAlgorithm::ActiveSiRStop::SetSiR2Source (const IDs::source so) [inline]
Definition at line 16 of file ActiveSiRMuStopAlgo.h.
References fSiR2source.
Referenced by PlotTME_activeSiRmuStops::FillHistograms().
{fSiR2source=so;}
Member Data Documentation
double TMEAlgorithm::ActiveSiRStop::fMuScMax [private]
Definition at line 20 of file ActiveSiRMuStopAlgo.h.
Referenced by operator()().
double TMEAlgorithm::ActiveSiRStop::fMuScMin [private]
Definition at line 20 of file ActiveSiRMuStopAlgo.h.
Referenced by operator()().
double TMEAlgorithm::ActiveSiRStop::fSiR2Max [private]
Definition at line 20 of file ActiveSiRMuStopAlgo.h.
Referenced by operator()().
double TMEAlgorithm::ActiveSiRStop::fSiR2Min [private]
Definition at line 20 of file ActiveSiRMuStopAlgo.h.
Referenced by operator()().
IDs::source TMEAlgorithm::ActiveSiRStop::fSiR2source [private]
Definition at line 21 of file ActiveSiRMuStopAlgo.h.
Referenced by operator()(), and SetSiR2Source().
The documentation for this class was generated from the following files:
rootana/src/TME_generators/ActiveSiRMuStopAlgo.h
rootana/src/TME_generators/ActiveSiRMuStopAlgo.cpp