AlcapDAQ: BaseModule Class Reference
BaseModule Class Reference
#include <BaseModule.h>
Public Member Functions
BaseModule (const char *module_name, modules::options *opts=NULL, bool with_directory=true)
Constructor of a module class. Provides several virtual methods that should be overloaded in the derived class. Derived classes should hard-code their name as the first argument to the constructor.
virtual ~BaseModule ()
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)=0
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)=0
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)=0
The big kahuna. Overload this in the derived class and it will be called for each event.
Private Attributes
TSetupData * fSetup
bool fDebug
std::string fName
TDirectory * fDirectory
std::string fAlias
Detailed Description
Base class for a generic analysis module. Provides several virtual methods for the derived class to overload. Also sets up a directory where all histograms and other ROOT objects created by the module will be saved in the output root file.
Definition at line 16 of file BaseModule.h.
Constructor & Destructor Documentation
BaseModule::BaseModule (const char * module_name, modules::options * opts = NULL, bool with_directory = true)
Constructor of a module class. Provides several virtual methods that should be overloaded in the derived class. Derived classes should hard-code their name as the first argument to the constructor.
Parameters:
module_name The name of the module
opts Options given to the module from the modules file
setup [To be removed soon]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 7 of file BaseModule.cpp.
References dir, fDebug, fDirectory, fName, GetAlias(), modules::options::GetAlias(), modules::options::GetBool(), modules::options::GetOption(), modules::options::HasOption(), modules::navigator::Instance(), SetAlias(), and modules::options::StringDescription().
                                                                               :
        fSetup(TSetupData::Instance()),fDebug(false),fName(name),fDirectory(NULL){
  // Pass common options
  if(opts){
    fDebug=(opts->HasOption("debug") && (opts->GetOption("debug").empty() || opts->GetBool("debug")));
    SetAlias(opts->GetAlias());
  }
  // Make a directory for this module if desired
  if(with_directory){
    // check if one exists
    fDirectory=gDirectory->GetDirectory(fName.c_str());
    // if not create one
    if(!fDirectory) fDirectory=gDirectory->mkdir(fName.c_str());
    // now make check if there's more than one instance of this module
    if(modules::navigator::Instance()->HowMany(fName)>1) {
        // and if there is, make a subdirectory and change into it
        fDirectory=fDirectory->mkdir(GetAlias().c_str());
    }
    fDirectory->SetTitle(opts->StringDescription().c_str());
    fDirectory->cd();
    // write the config into the file as a string
    TObjString *title=new TObjString(opts->StringDescription().c_str());
    title->Write();
  } else {
      // Set this module to use the top-level directory of the file
      fDirectory=gDirectory->GetDirectory("/");
  }
  dir=fDirectory;
}
BaseModule::~BaseModule () [virtual]
Definition at line 40 of file BaseModule.cpp.
{
}
Member Function Documentation
virtual int BaseModule::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [pure virtual]
Optional method which is called once after the main event loop Can be used to dump a summary or finalise a histogram
Returns:
0 on sucess and non-zero if a problem occurred
Implemented in IslandAmplitude, IslandLength, FastSlowCompare, LoadPulses, PlotIntegralRatios, CalcCoarseTimeOffset, CheckTMEs, ExportPulse, PlotAmpVsMuScTDiff, PlotAmpVsTDiff, PlotTAP_Amplitude, PlotTAP_Integral, PlotTAP_TDiff, PlotTAP_Time, PlotTDP_TDiff, PlotTDPs, PlotTPI_PedestalAndNoise, PulseViewer, SavePulses, MakeAnalysedPulses, PulseCandidateFinder_InvestigateParameters, TemplateCreator, MakeDetectorPulses, and MakeMuonEvents.
Referenced by Postprocess().
virtual int BaseModule::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [pure virtual]
Optional method which is called once before the main event loop Can be used to parse options and setup histograms.
Returns:
0 on sucess and non-zero if a problem occurred
Implemented in IslandAmplitude, IslandLength, FastSlowCompare, LoadPulses, PlotIntegralRatios, CalcCoarseTimeOffset, CheckTMEs, ExportPulse, PlotAmpVsMuScTDiff, PlotAmpVsTDiff, PlotTAP_Amplitude, PlotTAP_Integral, PlotTAP_TDiff, PlotTAP_Time, PlotTDP_TDiff, PlotTDPs, PlotTPI_PedestalAndNoise, PulseViewer, SavePulses, MakeAnalysedPulses, PulseCandidateFinder_InvestigateParameters, TemplateCreator, MakeDetectorPulses, and MakeMuonEvents.
Referenced by Preprocess().
bool BaseModule::Debug () const [inline, protected]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References fAlias.
Referenced by BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected]
Definition at line 77 of file BaseModule.cpp.
References dir, and fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::PlotTPI(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup)
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References AfterLastEntry(), and fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup)
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BeforeFirstEntry(), and fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
virtual int BaseModule::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, pure virtual]
The big kahuna. Overload this in the derived class and it will be called for each event.
Parameters:
gData Pointer to current map of all TPIs [ WILL CHANGE SHORTLY ]
gSetup Pointer to TSetupData for this run [ WILL CHANGE SHORTLY ]
Returns:
0 on success and non-zero on failure
Implemented in IslandAmplitude, IslandLength, FastSlowCompare, LoadPulses, PlotIntegralRatios, CalcCoarseTimeOffset, CheckTMEs, ExportPulse, PlotAmpVsMuScTDiff, PlotAmpVsTDiff, PlotTAP_Amplitude, PlotTAP_Integral, PlotTAP_TDiff, PlotTAP_Time, PlotTDP_TDiff, PlotTDPs, PlotTPI_PedestalAndNoise, PulseViewer, SavePulses, MakeTemplate, MakeAnalysedPulses, PulseCandidateFinder_InvestigateParameters, TemplateCreator, MakeDetectorPulses, and MakeMuonEvents.
Referenced by ProcessGenericEntry().
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup)
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References fDirectory, and ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References fAlias.
Referenced by BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule(), FastSlowCompare::FastSlowCompare(), GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
std::string BaseModule::fAlias [private]
Definition at line 92 of file BaseModule.h.
Referenced by GetAlias(), and SetAlias().
bool BaseModule::fDebug [private]
Definition at line 89 of file BaseModule.h.
Referenced by BaseModule(), and Debug().
TDirectory* BaseModule::fDirectory [private]
Definition at line 91 of file BaseModule.h.
Referenced by BaseModule(), GetDirectory(), Postprocess(), Preprocess(), and ProcessGenericEntry().
std::string BaseModule::fName [private]
Definition at line 90 of file BaseModule.h.
Referenced by BaseModule(), and GetName().
TSetupData* BaseModule::fSetup [private]
Reimplemented in ExportPulse.
Definition at line 88 of file BaseModule.h.
The documentation for this class was generated from the following files:
rootana/src/framework/BaseModule.h
rootana/src/framework/BaseModule.cpp