AlcapDAQ: SimpleHistograms Class Reference
SimpleHistograms Class Reference
#include <SimpleHistograms.h>
Public Member Functions
SimpleHistograms (const char *HistogramDirectoryName)
~SimpleHistograms ()
int ProcessGenericEntry (TGlobalData *gData, TSetupData *gSetup)
virtual int BeforeFirstEntry (TGlobalData *gData, TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, TSetupData *setup)
const char * GetName () const
Protected Member Functions
bool Debug () const
Protected Attributes
TDirectory * dir
TSetupData * fSetup
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData)
Detailed Description
Definition at line 7 of file SimpleHistograms.h.
Constructor & Destructor Documentation
SimpleHistograms::SimpleHistograms (const char * HistogramDirectoryName)
Definition at line 22 of file SimpleHistograms.cpp.
References hBankSize, hNumberOfNoCoincidences, and i.
                                                                      :
   FillHistBase(HistogramDirectoryName){
   // The following are the banks we want to compare in this example
   banks.push_back("Nec0");
   banks.push_back("Nfc0");
   banks.push_back("Ngc0");
   banks.push_back("Nhc0");
   banks.push_back("Nae0");
   banks.push_back("Nbe0");
   banks.push_back("Nce0");
   banks.push_back("Nee0");
 //  banks.push_back("Nfe0");
 //  banks.push_back("Nge0");
 //  banks.push_back("Nhe0");
   hBankSize = new TH2F("hBankSize", "Bank size",
                        1500, -1.5, 1498.5, banks.size(), 0.5, banks.size()+0.5);
   for(unsigned int i = 1; i<=banks.size(); ++i) hBankSize->GetYaxis()->SetBinLabel(i, banks.at(i-1).data());
   // Let's compare the number of comparisons. If N is the size of the bank vector, then we need
   // (N-1) + (N-2) +... + 1 comparisons
   int NrComparisons = banks.size() * (banks.size()-1) / 2;
   hNumberOfNoCoincidences = new TH2F("hNumberOfNoCoincidences", "Number of missing coincidences per tree entry",
                                      1000, -1.5, 998.5, NrComparisons, 0.5, NrComparisons+0.5);
 }
SimpleHistograms::~SimpleHistograms ()
Definition at line 51 of file SimpleHistograms.cpp.
{
 }
Member Function Documentation
virtual int FillHistBase::AfterLastEntry (TGlobalData * gData, TSetupData * setup) inline virtual inherited
Reimplemented in TestModule.
Definition at line 39 of file FillHistBase.h.
 {return 0;};
virtual int FillHistBase::BeforeFirstEntry (TGlobalData * gData, TSetupData * setup) inline virtual inherited
Reimplemented in ExportPulse, MakeAnalysedPulses, MakeDetectorPulses, MakeMuonEvents, and TestModule.
Definition at line 38 of file FillHistBase.h.
 {return 0;};
bool FillHistBase::Debug () const inline protected inherited
Definition at line 45 of file FillHistBase.h.
References FillHistBase::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), TestModule::AfterLastEntry(), TestModule::BeforeFirstEntry(), MakeMuonEvents::BeforeFirstEntry(), MakeDetectorPulses::MakeGenerator(), ExportPulse::MakePlot(), and MakeAnalysedPulses::ProcessEntry().
 {return fDebug;};
const char* FillHistBase::GetName () const inline inherited
Definition at line 40 of file FillHistBase.h.
References FillHistBase::dir.
Referenced by DeadTimeGe::ProcessEntry(), PlotTime::ProcessEntry(), and PlotAmplitude::ProcessEntry().
 {return dir->GetName();};
int SimpleHistograms::ProcessEntry (TGlobalData * gData) private virtual
Definition at line 54 of file SimpleHistograms.cpp.
References count, TGlobalData::fPulseIslandToChannelMap, hBankSize, hNumberOfNoCoincidences, i, last, printf(), size, sprintf(), title, and verbose.
{
   typedef StringPulseIslandMap::iterator map_iterator;
   vector<TPulseIsland*> islands[banks.size()];
   for(unsigned int b1 = 0; b1 < banks.size(); ++b1){
     string bank = banks.at(b1);
     for(map_iterator iter = gData->fPulseIslandToChannelMap.begin();
         iter != gData->fPulseIslandToChannelMap.end(); iter++){
       if(strcmp((iter->first).data(), bank.data()) == 0){
         islands[b1] = iter->second;
       }
     }
     hBankSize->Fill(islands[b1].size(), b1+1);
   }
   PulseIslandList islands1, islands2;
   int count  = 1;
   for(unsigned int b1 = 0; b1 < banks.size()-1; ++b1){
     for(unsigned int b2 = b1+1; b2 < banks.size(); ++b2){
       char title[100];
       sprintf(title, "%s - %s", banks.at(b1).data(), banks.at(b2).data());
       hNumberOfNoCoincidences->GetYaxis()->SetBinLabel(count, title);
       int last = 0;
       int NumberOfNoCoincidences = 0;
       if(verbose){
         for(unsigned int i = 0; i < islands[b1].size(); ++i){
           std::cout << "i = " << i << ": " <<  islands[b1][i]->GetTimeStamp() * islands[b1][i]->GetClockTickInNs() << "\n";
         }
         for(unsigned int i = 0; i < islands[b2].size(); ++i){
           std::cout << "i = " << i << ": " <<  islands[b2][i]->GetTimeStamp() * islands[b2][i]->GetClockTickInNs() << "\n";
         }
       }
       for(unsigned int i = 0; i < islands[b1].size(); ++i){
         double t1 = islands[b1][i]->GetTimeStamp(); // * islands1[i]->GetClockTickInNs();
         bool foundCoincidence = false;
         for(unsigned int j = last; j < islands[b2].size(); ++j){
           double t2 = islands[b2][j]->GetTimeStamp(); // * islands2[j]->GetClockTickInNs();
           double tdiff = t2 - t1;
           if(tdiff < -200.){
             last = j;
             continue;
           }
           if(tdiff > 200.){
             break;
           }
           // Found a coincidence
           foundCoincidence = true;
         }
         // Check if we found a coincidence
         if(!foundCoincidence){
           ++NumberOfNoCoincidences;
         }
       }
       if(verbose)
         printf("Found %d tree entries with no coincidence for banks %s and %s.\n", NumberOfNoCoincidences,
                banks.at(b1).data(), banks.at(b2).data());
       hNumberOfNoCoincidences->Fill(NumberOfNoCoincidences, count++);
     }
   }
   return 0;
 }
int FillHistBase::ProcessGenericEntry (TGlobalData * gData, TSetupData * gSetup) inherited
Definition at line 24 of file FillHistBase.cpp.
References FillHistBase::dir, and FillHistBase::ProcessEntry().
{
   // This is called by our main routine and would allow later to split into different
   // process routines if we have more than one Tree and hence different tpyes of data input.
   if(dir) dir->cd();
   int ret = ProcessEntry(gData, gSetup);
   gDirectory->cd("/");
   return ret;
 }
Field Documentation
TDirectory* FillHistBase::dir protected inherited
Definition at line 40 of file FillHistBase.h.
Referenced by DeadTimeGe::DeadTimeGe(), ExportPulse::ExportPulse(), FillHistBase::FillHistBase(), FillHistBase::GetName(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmplitude::PlotAmplitude(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTime::PlotTime(), and FillHistBase::ProcessGenericEntry().
TSetupData* FillHistBase::fSetup protected inherited
Definition at line 44 of file FillHistBase.h.
The documentation for this class was generated from the following files:
analyzer/rootana/src/examples/SimpleHistograms.h
analyzer/rootana/src/examples/SimpleHistograms.cpp