AlcapDAQ: CalcCoarseTimeOffset Class Reference
CalcCoarseTimeOffset Class Reference
[Modules]
A one line description of what your module does.
#include <CalcCoarseTimeOffset.h>
Public Member Functions
CalcCoarseTimeOffset (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~CalcCoarseTimeOffset ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::vector< IDs::source > SourceVector
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
void CreateHistogramsIfDontExist (const std::string &source, const std::string &generator)
Private Attributes
std::string fDetNameA
Don't forget to forget descirptions for each field...
std::string fDetNameB
std::map< std::string, TH1F * > oned_plots
SourceVector fDetASources
SourceVector fDetBSources
Detailed Description
A one line description of what your module does.
Author:
AuthorName
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 25 of file CalcCoarseTimeOffset.h.
Member Typedef Documentation
typedef std::vector<IDs::source> CalcCoarseTimeOffset::SourceVector [private]
Definition at line 26 of file CalcCoarseTimeOffset.h.
Constructor & Destructor Documentation
CalcCoarseTimeOffset::CalcCoarseTimeOffset (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 28 of file CalcCoarseTimeOffset.cpp.
References fDetNameA, fDetNameB, and modules::options::GetString().
                                                              :
  BaseModule("CalcCoarseTimeOffset",opts){
  fDetNameA = opts->GetString("det1");
  fDetNameB = opts->GetString("det2");
}
CalcCoarseTimeOffset::~CalcCoarseTimeOffset ()
Is anything done in the destructor?
Definition at line 36 of file CalcCoarseTimeOffset.cpp.
{
}
Member Function Documentation
int CalcCoarseTimeOffset::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::AfterLastEntry
[in] setup See BaseModule::AfterLastEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 103 of file CalcCoarseTimeOffset.cpp.
References fDetASources, SetupNavigator::Instance(), oned_plots, and SetupNavigator::SetCoarseTimeOffset().
{
  for (unsigned int i = 0; i < fDetASources.size(); ++i) {
    const std::string keyname = fDetASources[i].str();
    const double dt = oned_plots[keyname]->GetBinCenter(oned_plots[keyname]->GetMaximumBin());
    SetupNavigator::Instance()->SetCoarseTimeOffset(fDetASources[i], dt);
  }
  return 0;
}
int CalcCoarseTimeOffset::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::BeforeFirstEntry
[in] setup See BaseModule::BeforeFirstEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 41 of file CalcCoarseTimeOffset.cpp.
References fDetASources, fDetBSources, fDetNameA, fDetNameB, and gAnalysedPulseMap.
{
  //call my source finders and build histogram for each source with
  //a time component.
  //should I continue to work on just two? or should I have this loop
  //through all pairs
  for(SourceAnalPulseMap::const_iterator sourceIt = gAnalysedPulseMap.begin();
      sourceIt != gAnalysedPulseMap.end(); sourceIt++) {
    if( sourceIt->first.Channel() != fDetNameA) {
      continue;   //check for detector A
    }
    //I need to check that this source generates a time
    AnalysedPulseList pulses = sourceIt->second;
    for(SourceAnalPulseMap::const_iterator sourceIt2 = gAnalysedPulseMap.begin(); sourceIt2 != gAnalysedPulseMap.end(); sourceIt2++) {
      if(sourceIt2->first.Channel() != fDetNameB)
        continue;  //check for detector B
      if(sourceIt2->first.Generator() != sourceIt->first.Generator())
        continue;  //make sure they have the same generator
      //I should make a vector of the sources for detA and detB
      fDetASources.push_back(sourceIt->first);
      fDetBSources.push_back(sourceIt2->first);
    }
  }
  return 0;
}
void CalcCoarseTimeOffset::CreateHistogramsIfDontExist (const std::string & source, const std::string & generator) [private]
Definition at line 112 of file CalcCoarseTimeOffset.cpp.
References fDetNameA, fDetNameB, and oned_plots.
Referenced by ProcessEntry().
{
  if( oned_plots.find(src) == oned_plots.end() ) {
    std::string histname = "h" + fDetNameB + "_" + src + "TDiff_1D";
    std::string histtitle = "Time difference between  " + fDetNameA + " and " + fDetNameB + " detectors with the " + gen + " generator";
    TH1F* dplots = new TH1F(histname.c_str(), histtitle.c_str(), 500, -10000, 10000);
    dplots->GetXaxis()->SetTitle("Time Difference (ns)");
    dplots->GetYaxis()->SetTitle("Count");
    oned_plots[src] = dplots;
  }
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int CalcCoarseTimeOffset::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::ProcessEntry
[in] gSetup See BaseModule::ProcessEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 74 of file CalcCoarseTimeOffset.cpp.
References CreateHistogramsIfDontExist(), fDetASources, fDetBSources, gAnalysedPulseMap, and oned_plots.
{
  for(SourceVector::const_iterator sourceIt = fDetASources.begin(); sourceIt != fDetASources.end(); sourceIt++) {
    const AnalysedPulseList& detAPulses = gAnalysedPulseMap[*sourceIt];
    const AnalysedPulseList& detBPulses = gAnalysedPulseMap[fDetBSources.at(sourceIt - fDetASources.begin())];
    const std::string keyname = sourceIt->str();
    CreateHistogramsIfDontExist(keyname, (*sourceIt).Generator().str());
    for(AnalysedPulseList::const_iterator pulseIt = detAPulses.begin();
        pulseIt != detAPulses.end(); ++pulseIt) {
      double timeA = (*pulseIt)->GetTime();
      for(AnalysedPulseList::const_iterator pulseIt2 = detBPulses.begin();
          pulseIt2 != detBPulses.end(); ++pulseIt2) {
        double timeB = (*pulseIt2)->GetTime();
        double tDiff = timeA - timeB;
        oned_plots[keyname]->Fill(tDiff);
      }//end detBPulse loop
    }//end detAPulse loop
  }//end sourceIt loop
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
SourceVector CalcCoarseTimeOffset::fDetASources [private]
Definition at line 74 of file CalcCoarseTimeOffset.h.
Referenced by AfterLastEntry(), BeforeFirstEntry(), and ProcessEntry().
SourceVector CalcCoarseTimeOffset::fDetBSources [private]
Definition at line 74 of file CalcCoarseTimeOffset.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
std::string CalcCoarseTimeOffset::fDetNameA [private]
Don't forget to forget descirptions for each field...
...and don't hesitate to include details.
Definition at line 71 of file CalcCoarseTimeOffset.h.
Referenced by BeforeFirstEntry(), CalcCoarseTimeOffset(), and CreateHistogramsIfDontExist().
std::string CalcCoarseTimeOffset::fDetNameB [private]
Definition at line 71 of file CalcCoarseTimeOffset.h.
Referenced by BeforeFirstEntry(), CalcCoarseTimeOffset(), and CreateHistogramsIfDontExist().
std::map<std::string, TH1F*> CalcCoarseTimeOffset::oned_plots [private]
Definition at line 73 of file CalcCoarseTimeOffset.h.
Referenced by AfterLastEntry(), CreateHistogramsIfDontExist(), and ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/plotters/CalcCoarseTimeOffset.h
rootana/src/plotters/CalcCoarseTimeOffset.cpp