AlcapDAQ: TVDetectorPulseGenerator Class Reference
TVDetectorPulseGenerator Class Reference
#include <TVDetectorPulseGenerator.h>
Public Member Functions
TVDetectorPulseGenerator (const char *name, TDPGeneratorOptions *opts)
virtual ~TVDetectorPulseGenerator ()
virtual int ProcessPulses (DetectorPulseList &output)=0
virtual bool ChecksForPileUp () const =0
void SetPulseSources (const IDs::source &fast, const IDs::source &slow)
void SetPulseLists (const AnalysedPulseList *fast, const AnalysedPulseList *slow)
void SetDebug (const bool &val=true)
bool Debug ()
TDetectorPulse * MakeTDP (int fast_parent, int slow_parent) const
IDs::source GetSource () const
IDs::source GetFastSource () const
IDs::source GetSlowSource () const
void SetChannel (const IDs::channel &ch)
IDs::generator GetGeneratorID () const
const AnalysedPulseList * FastPulseList () const
const AnalysedPulseList * SlowPulseList () const
Private Attributes
bool fDebug
IDs::source fFastSource
IDs::source fSlowSource
IDs::source fSource
const AnalysedPulseList * fFastPulses
const AnalysedPulseList * fSlowPulses
Detailed Description
Definition at line 10 of file TVDetectorPulseGenerator.h.
Constructor & Destructor Documentation
TVDetectorPulseGenerator::TVDetectorPulseGenerator (const char * name, TDPGeneratorOptions * opts) [inline]
Definition at line 14 of file TVDetectorPulseGenerator.h.
References fSource, IDs::source::Generator(), and modules::options::StringDescription().
                                                                       :
      fDebug(false),fFastPulses(NULL),fSlowPulses(NULL){
            fSource.Generator()=IDs::generator(name,opts->StringDescription());
      }
  virtual ~TVDetectorPulseGenerator(){}
virtual TVDetectorPulseGenerator::~TVDetectorPulseGenerator () [inline, virtual]
Definition at line 18 of file TVDetectorPulseGenerator.h.
{}
Member Function Documentation
virtual bool TVDetectorPulseGenerator::ChecksForPileUp () const [pure virtual]
Implemented in MaxTimeDiffDPGenerator, and PassThroughDPGenerator.
bool TVDetectorPulseGenerator::Debug () [inline]
Definition at line 34 of file TVDetectorPulseGenerator.h.
References fDebug.
Referenced by MaxTimeDiffDPGenerator::ProcessPulses().
{return fDebug;};
const AnalysedPulseList* TVDetectorPulseGenerator::FastPulseList () const [inline]
Definition at line 53 of file TVDetectorPulseGenerator.h.
References fFastPulses.
Referenced by PassThroughDPGenerator::ProcessPulses(), and MaxTimeDiffDPGenerator::ProcessPulses().
{return fFastPulses;}
IDs::source TVDetectorPulseGenerator::GetFastSource () const [inline]
Definition at line 48 of file TVDetectorPulseGenerator.h.
References fFastSource.
Referenced by MaxTimeDiffDPGenerator::ProcessPulses().
{return fFastSource;};
IDs::generator TVDetectorPulseGenerator::GetGeneratorID () const [inline]
Definition at line 51 of file TVDetectorPulseGenerator.h.
References fSource, and IDs::source::Generator().
Referenced by MakeDetectorPulses::BeforeFirstEntry().
{return fSource.Generator();}
IDs::source TVDetectorPulseGenerator::GetSlowSource () const [inline]
Definition at line 49 of file TVDetectorPulseGenerator.h.
References fSlowSource.
Referenced by MaxTimeDiffDPGenerator::ProcessPulses().
{return fSlowSource;};
IDs::source TVDetectorPulseGenerator::GetSource () const [inline]
Definition at line 47 of file TVDetectorPulseGenerator.h.
References fSource.
Referenced by MakeDetectorPulses::GetPassThruGeneratorID(), and MakeTDP().
{return fSource;};
TDetectorPulse* TVDetectorPulseGenerator::MakeTDP (int fast_parent, int slow_parent) const [inline]
Definition at line 36 of file TVDetectorPulseGenerator.h.
References fFastPulses, fSlowPulses, and GetSource().
Referenced by PassThroughDPGenerator::ProcessPulses(), and MaxTimeDiffDPGenerator::ProcessPulses().
{
      TDetectorPulse* pulse=NULL;
      const TAnalysedPulse* fast=NULL;
      if(fFastPulses && fast_parent>=0) fast=fFastPulses->at(fast_parent);
      const TAnalysedPulse* slow=NULL;
      if(fSlowPulses && slow_parent>=0) slow=fSlowPulses->at(slow_parent);
      if(fast || slow) {
          pulse=new TDetectorPulse(GetSource(),fast_parent,fast,slow_parent,slow);
      }
      return pulse;
  }
virtual int TVDetectorPulseGenerator::ProcessPulses (DetectorPulseList & output) [pure virtual]
Implemented in MaxTimeDiffDPGenerator, and PassThroughDPGenerator.
void TVDetectorPulseGenerator::SetChannel (const IDs::channel & ch) [inline]
Definition at line 50 of file TVDetectorPulseGenerator.h.
References IDs::source::Channel(), and fSource.
{fSource.Channel()=ch;};
void TVDetectorPulseGenerator::SetDebug (const bool & val = true) [inline]
Definition at line 33 of file TVDetectorPulseGenerator.h.
References fDebug.
Referenced by MakeDetectorPulses::MakeGenerator().
{fDebug=val;};
void TVDetectorPulseGenerator::SetPulseLists (const AnalysedPulseList * fast, const AnalysedPulseList * slow) [inline]
Definition at line 28 of file TVDetectorPulseGenerator.h.
References fFastPulses, and fSlowPulses.
{
      fFastPulses=fast;
      fSlowPulses=slow;
  }
void TVDetectorPulseGenerator::SetPulseSources (const IDs::source & fast, const IDs::source & slow) [inline]
Definition at line 24 of file TVDetectorPulseGenerator.h.
References fFastSource, and fSlowSource.
{
      fFastSource=fast;
      fSlowSource=slow;
  }
const AnalysedPulseList* TVDetectorPulseGenerator::SlowPulseList () const [inline]
Definition at line 54 of file TVDetectorPulseGenerator.h.
References fSlowPulses.
Referenced by MaxTimeDiffDPGenerator::ProcessPulses().
{return fSlowPulses;}
Member Data Documentation
bool TVDetectorPulseGenerator::fDebug [private]
Definition at line 57 of file TVDetectorPulseGenerator.h.
Referenced by Debug(), and SetDebug().
const AnalysedPulseList* TVDetectorPulseGenerator::fFastPulses [private]
Definition at line 59 of file TVDetectorPulseGenerator.h.
Referenced by FastPulseList(), MakeTDP(), and SetPulseLists().
IDs::source TVDetectorPulseGenerator::fFastSource [private]
Definition at line 58 of file TVDetectorPulseGenerator.h.
Referenced by GetFastSource(), and SetPulseSources().
const AnalysedPulseList * TVDetectorPulseGenerator::fSlowPulses [private]
Definition at line 59 of file TVDetectorPulseGenerator.h.
Referenced by MakeTDP(), SetPulseLists(), and SlowPulseList().
IDs::source TVDetectorPulseGenerator::fSlowSource [private]
Definition at line 58 of file TVDetectorPulseGenerator.h.
Referenced by GetSlowSource(), and SetPulseSources().
IDs::source TVDetectorPulseGenerator::fSource [private]
Definition at line 58 of file TVDetectorPulseGenerator.h.
Referenced by GetGeneratorID(), GetSource(), SetChannel(), and TVDetectorPulseGenerator().
The documentation for this class was generated from the following file:
rootana/src/TDP_generators/TVDetectorPulseGenerator.h