AlcapDAQ: IDs::generator Class Reference
IDs::generator Class Reference
Streamable identifier for an instance of a generator.
#include <IdGenerator.h>
Public Member Functions
generator (Generator_t g, Config_t c)
Constructor taking two strings for the Generator type and its configuration.
generator ()
Default constructor for a generator ID. Will match true against all generator IDs.
generator (const std::string &s)
Construct a source ID from a single string.
virtual ~generator ()
Generator_t Type () const
Returns the type of generator that this ID represents.
void Type (const Generator_t &g)
Set the type of generator that this ID represents.
Config_t Config () const
Returns the configuration of the generator that this ID represents.
void Config (const Config_t &c)
Set the configuration of the generator that this ID represents.
bool operator== (const generator &rhs) const
bool matches (const generator &rhs) const
bool operator!= (const generator &rhs) const
bool operator< (const generator &rhs) const
Not intuitively meaningful but maybe useful for sorting.
bool operator> (const generator &rhs) const
Not intuitively meaningful but maybe useful for sorting.
std::string str () const
Get this ID as a string.
IDs::generator & operator= (const std::string &rhs)
bool isWildCardType () const
Check if the Generator_t part of the ID is a wildcard.
bool isWildCardConfig () const
Check if the Config_t part of the ID is a wildcard.
bool isWildCard () const
Check if any part of the ID is a wildcard.
void Debug () const
Print the individual components of the ID.
Private Member Functions
ClassDef (generator, 1)
Private Attributes
Generator_t fType
Stores the type of this generator.
Config_t fConfig
Stores the configuration of this generator.
Detailed Description
Streamable identifier for an instance of a generator.
Definition at line 25 of file IdGenerator.h.
Constructor & Destructor Documentation
IDs::generator::generator (Generator_t g, Config_t c) [inline]
Constructor taking two strings for the Generator type and its configuration.
Parameters:
g The type of the generator
c The configuration of the generator
Definition at line 119 of file IdGenerator.h.
References fConfig, and IDs::kAnyConfig.
                                                        :
        fType(t),fConfig(c){
                if(fConfig=="") fConfig=kAnyConfig;
}
IDs::generator::generator () [inline]
Default constructor for a generator ID. Will match true against all generator IDs.
Definition at line 36 of file IdGenerator.h.
:fType(kAnyGenerator),fConfig(kAnyConfig){};
IDs::generator::generator (const std::string & s) [inline]
Construct a source ID from a single string.
Equivalent to calling the defualt constructor following by operator=(std::string)
Definition at line 41 of file IdGenerator.h.
References operator=().
        : fType(kAnyGenerator),fConfig(kAnyConfig) {
            operator=(s);
        };
virtual IDs::generator::~generator () [inline, virtual]
Definition at line 46 of file IdGenerator.h.
{};
Member Function Documentation
IDs::generator::ClassDef (generator , 1) [private]
void IDs::generator::Config (const Config_t & c) [inline]
Set the configuration of the generator that this ID represents.
Definition at line 59 of file IdGenerator.h.
References fConfig.
{fConfig=c;};
Config_t IDs::generator::Config () const [inline]
Returns the configuration of the generator that this ID represents.
Definition at line 56 of file IdGenerator.h.
References fConfig.
Referenced by Debug(), and operator=().
{return fConfig;};
void IDs::generator::Debug () const
Print the individual components of the ID.
Definition at line 30 of file IdGenerator.cpp.
References Config(), and Type().
Referenced by IDs::source::Debug().
{
    std::cout<<"Generator: "<<Type()<<std::endl;
    std::cout<<"Config: "<<Config()<<std::endl;
}
bool IDs::generator::isWildCard () const [inline]
Check if any part of the ID is a wildcard.
Definition at line 87 of file IdGenerator.h.
References isWildCardConfig(), and isWildCardType().
Referenced by IDs::source::isWildCardGenerator().
{ return isWildCardConfig() || isWildCardType(); }
bool IDs::generator::isWildCardConfig () const [inline]
Check if the Config_t part of the ID is a wildcard.
Definition at line 84 of file IdGenerator.h.
References fConfig, and IDs::kAnyConfig.
Referenced by isWildCard(), and matches().
{ return fConfig == kAnyConfig; }
bool IDs::generator::isWildCardType () const [inline]
Check if the Generator_t part of the ID is a wildcard.
Definition at line 81 of file IdGenerator.h.
References fType, and IDs::kAnyGenerator.
Referenced by isWildCard(), and matches().
{ return fType == kAnyGenerator; }
bool IDs::generator::matches (const generator & rhs) const [inline]
Definition at line 105 of file IdGenerator.h.
References fConfig, fType, isWildCardConfig(), and isWildCardType().
Referenced by IDs::source::matches().
{
        return (isWildCardType() || rhs.isWildCardType() || fType==rhs.fType)
                && (isWildCardConfig() || rhs.isWildCardConfig() || fConfig==rhs.fConfig) ;
}
bool IDs::generator::operator!= (const generator & rhs) const [inline]
Is this generator the different to another, and do both this and the other id have fields not set to kAny
Definition at line 68 of file IdGenerator.h.
References operator==().
{return !(this->operator==(rhs));};
bool IDs::generator::operator< (const generator & rhs) const [inline]
Not intuitively meaningful but maybe useful for sorting.
Definition at line 115 of file IdGenerator.h.
References fConfig, and fType.
{
        int type_cmp=fType.compare(rhs.fType);
        return  type_cmp<0 || (type_cmp==0 && fConfig.compare(rhs.fConfig)<0);
}
IDs::generator & IDs::generator::operator= (const std::string & rhs)
Definition at line 17 of file IdGenerator.cpp.
References Config(), IDs::field_separator, and Type().
Referenced by generator().
{
    // Find the first delimiter
    size_t delim=rhs.find(IDs::field_separator.c_str());
    if(delim==std::string::npos){
        std::cout<<"Warning: Strange looking string given to IDs::source: "<<rhs<<std::endl;
        Type(rhs);
    } else{
        Type(rhs.substr(0,delim));
        Config(rhs.substr(delim+1));
    }
    return *this;
}
bool IDs::generator::operator== (const generator & rhs) const [inline]
Is this generator the same as another, or is this or the other id have fields set to kAny
Definition at line 101 of file IdGenerator.h.
References fConfig, and fType.
Referenced by operator!=().
{
        return (fType==rhs.fType) && (fConfig==rhs.fConfig) ;
}
bool IDs::generator::operator> (const generator & rhs) const [inline]
Not intuitively meaningful but maybe useful for sorting.
Definition at line 110 of file IdGenerator.h.
References fConfig, and fType.
{
        int type_cmp=fType.compare(rhs.fType);
        return  type_cmp>0 || (type_cmp==0 && fConfig.compare(rhs.fConfig)>0);
}
std::string IDs::generator::str () const
Get this ID as a string.
Definition at line 8 of file IdGenerator.cpp.
References fConfig, IDs::field_separator, and fType.
Referenced by PlotTDPs::BeforeFirstEntry(), and IDs::source::str().
{
  return fType+IDs::field_separator+fConfig;
}
void IDs::generator::Type (const Generator_t & g) [inline]
Set the type of generator that this ID represents.
Definition at line 53 of file IdGenerator.h.
References fType.
{ fType=g;};
Generator_t IDs::generator::Type () const [inline]
Returns the type of generator that this ID represents.
Definition at line 50 of file IdGenerator.h.
References fType.
Referenced by MakeDetectorPulses::BeforeFirstEntry(), Debug(), TAPGeneratorFactory::GetTAPType(), and operator=().
{return fType;};
Member Data Documentation
Config_t IDs::generator::fConfig [private]
Stores the configuration of this generator.
Definition at line 96 of file IdGenerator.h.
Referenced by Config(), generator(), isWildCardConfig(), matches(), operator<(), operator==(), operator>(), and str().
Generator_t IDs::generator::fType [private]
Stores the type of this generator.
Definition at line 94 of file IdGenerator.h.
Referenced by isWildCardType(), matches(), operator<(), operator==(), operator>(), str(), and Type().
The documentation for this class was generated from the following files:
rootana/src/framework/IdGenerator.h
rootana/src/framework/IdGenerator.cpp