AlcapDAQ: GeSpectrum Class Reference
GeSpectrum Class Reference
[Modules]
This produces the height spectrum of the germanium based on timing cuts.
#include <GeSpectrum.h>
Public Member Functions
GeSpectrum (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~GeSpectrum ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
Histograms the heights in the germanium with time cuts relative to muSc.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
Does nothing.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
Does nothing.
std::vector< double > CalculateTimes (const IDs::channel &chan, const std::vector< TPulseIsland * > &tpis)
Takes a vector of TPIs and calculates all of their times.
std::vector< double > CalculateEnergies (const IDs::channel &chan, const std::vector< TPulseIsland * > &tpis)
Takes a vector of TPIs and calculates all of their energies.
void ThrowIfInputsInsane (const modules::options *)
void ThrowIfGeInsane (const std::vector< TPulseIsland * > &ge_fasts, const std::vector< TPulseIsland * > &ge_slows)
void RemovePileupMuScPulses (std::vector< double > &time, std::vector< double > &energy)
Private Attributes
TH1 * fHist_ADC
TH1 * fHist_Energy
TH1 * fHist_Time
TH1 * fHist_MoreTime
TH1 * fHist_ADCOOT
TH1 * fHist_EnergyOOT
TH1 * fHist_ADCFarOOT
TH1 * fHist_EnergyFarOOT
TH1 * fHist_TimeOOT
TH1 * fHist_TimeFarOOT
TH2 * fHist_TimeADC
TH2 * fHist_TimeEnergy
TH1 * fHist_MeanTOffset
const Algorithm::MaxBinAmplitude fMBAmpGe
const Algorithm::MaxBinAmplitude fMBAmpMuSc
const
Algorithm::ConstantFractionTime fCFTimeGe
const
Algorithm::ConstantFractionTime fCFTimeMuSc
TF1 * fADC2Energy
const double fTimeWindow_Small
const double fTimeWindow_Big
const double fPileupProtectionWindow
Static Private Attributes
static const IDs::channel fGeS
static const IDs::channel fGeF
static const IDs::channel fMuSc
Detailed Description
This produces the height spectrum of the germanium based on timing cuts.
Author:
John R Quirk
We look near muon entrances for the xrays and several microseconds away for longer lived nuclear decays. We also look at medium time distances for captures. These refer to the "Energy", "EnergyFarOOT" and "EnergyOOT" histograms respectively. Also plots time vs energy in tight window in TimeEnergy histogram, and looks for timing correlations with muSc in MeanTOffset within a MIDAS event (as each event might have a slightly different offset due to clock reset).
Definition at line 34 of file GeSpectrum.h.
Constructor & Destructor Documentation
GeSpectrum::GeSpectrum (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 30 of file GeSpectrum.cpp.
References BaseModule::dir, fADC2Energy, fHist_ADC, fHist_ADCFarOOT, fHist_ADCOOT, fHist_Energy, fHist_EnergyFarOOT, fHist_EnergyOOT, fHist_MeanTOffset, fHist_MoreTime, fHist_Time, fHist_TimeADC, fHist_TimeEnergy, fHist_TimeFarOOT, fHist_TimeOOT, fTimeWindow_Big, fTimeWindow_Small, SetupNavigator::GetEnergyCalibrationConstants(), SetupNavigator::Instance(), and ThrowIfInputsInsane().
                                           :
  BaseModule("GeSpectrum",opts),
  fHist_Energy(NULL), fHist_Time(NULL), fHist_MoreTime(NULL),
  fHist_EnergyOOT(NULL), fHist_EnergyFarOOT(NULL), fHist_TimeEnergy(NULL), fHist_MeanTOffset(NULL),
  fMBAmpGe(SetupNavigator::Instance()->GetPedestal(fGeS), TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(fGeS.str()))),
  fMBAmpMuSc(SetupNavigator::Instance()->GetPedestal(fMuSc), TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(fMuSc.str()))),
  fCFTimeGe(SetupNavigator::Instance()->GetPedestal(fGeF),
            TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(fGeF.str())),
            TSetupData::Instance()->GetClockTick(TSetupData::Instance()->GetBankName(fGeF.str())),
            SetupNavigator::Instance()->GetCoarseTimeOffset(IDs::source(fGeF, IDs::generator(opts->GetString("gef_gen"), opts->GetString("gef_cfg")))),
            opts->GetDouble("gef_cf")),
  fCFTimeMuSc(SetupNavigator::Instance()->GetPedestal(fMuSc),
              TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(fMuSc.str())),
              TSetupData::Instance()->GetClockTick(TSetupData::Instance()->GetBankName(fMuSc.str())),
              0.,
              opts->GetDouble("musc_cf")),
  fADC2Energy(new TF1("adc2energy","[0]*x+[1]")),
  fTimeWindow_Small(1000.), fTimeWindow_Big(5000.), fPileupProtectionWindow(15000.) {
  const static int nbins = std::pow(2.,14);
  const std::pair<double,double> adc2energy_par = SetupNavigator::Instance()->GetEnergyCalibrationConstants(IDs::channel("Ge-S"));
  fADC2Energy->SetParameters(adc2energy_par.first, adc2energy_par.second);
  TDirectory* cwd = TDirectory::CurrentDirectory();
  dir->cd();
  fHist_ADC          = new TH1D("hADC", "Energy of Gammas;Energy (ADC);Counts", nbins, 0., nbins);
  double energy_bin_width = 0.1; // keV
  double min_energy = 0;
  double max_energy = 2000;
  int n_energy_bins = (max_energy - min_energy) / energy_bin_width;
  fHist_Energy       = new TH1D("hEnergy", "Energy of Gammas;Energy (keV);Counts", n_energy_bins, min_energy, max_energy);
  fHist_Time         = new TH1D("hTime", "Time of Gammas within Energy Window", 1000, -10000., 10000.);
  fHist_MoreTime     = new TH1D("hMoreTime", "Time of Gammas within Energy Window (Wide)", 1000, -100000., 100000.);
  fHist_ADCOOT       = new TH1D("hADCOOT", "Energy of Gammas outside of Time Window;Energy (ADC);Counts", nbins, 0., nbins);
  fHist_EnergyOOT    = new TH1D("hEnergyOOT", "Energy of Gammas outside of Time Window;Energy (keV);Counts", n_energy_bins, min_energy, max_energy);
  fHist_ADCFarOOT    = new TH1D("hADCFarOOT", "Energy of Gammas far from Muons;Energy (ADC);Counts", nbins, 0., nbins);
  fHist_EnergyFarOOT = new TH1D("hEnergyFarOOT", "Energy of Gammas far from Muons;Energy (keV);Counts", n_energy_bins, min_energy, max_energy);
  fHist_TimeOOT      = new TH1D("hTimeOOT", "Time of Gammas outside of Time Window", 1000., -2.*fTimeWindow_Small, 2.*fTimeWindow_Small);
  fHist_TimeFarOOT   = new TH1D("hTimeFarOOT", "Time of Gammas far from Muons", 1000., -100.*fTimeWindow_Big, 100.*fTimeWindow_Big);
  fHist_TimeADC      = new TH2D("hTimeADC", "Energy of Gammas within Time Window;Energy (ADC);Time (ns);Counts", 100, -fTimeWindow_Small, fTimeWindow_Small, nbins, 0., nbins);
  fHist_TimeEnergy   = new TH2D("hTimeEnergy", "Energy of Gammas within Time Window;Energy (keV);Time (ns);Counts", 100, -fTimeWindow_Small, fTimeWindow_Small, n_energy_bins, min_energy, max_energy);
  fHist_MeanTOffset  = new TH1D("hMeanTOffset", "Mean offset from nearest muon taken over MIDAS event", 4000, -4.*fTimeWindow_Big, 4.*fTimeWindow_Big);
  cwd->cd();
  ThrowIfInputsInsane(opts);
}
GeSpectrum::~GeSpectrum ()
Is anything done in the destructor?
Definition at line 75 of file GeSpectrum.cpp.
                       {
}
Member Function Documentation
int GeSpectrum::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Does nothing.
Parameters:
[in] gData See BaseModule::AfterLastEntry
[in] setup See BaseModule::AfterLastEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 225 of file GeSpectrum.cpp.
{
  return 0;
}
int GeSpectrum::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Does nothing.
Parameters:
[in] gData See BaseModule::BeforeFirstEntry
[in] setup See BaseModule::BeforeFirstEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 81 of file GeSpectrum.cpp.
{
  return 0;
}
std::vector< double > GeSpectrum::CalculateEnergies (const IDs::channel & chan, const std::vector< TPulseIsland * > & tpis) [private]
Takes a vector of TPIs and calculates all of their energies.
Definition at line 244 of file GeSpectrum.cpp.
References fGeS, fMBAmpGe, fMBAmpMuSc, and fMuSc.
Referenced by ProcessEntry().
{
  std::vector<double> e;
  if (ch == fGeS)
    for (unsigned int i = 0; i < tpis.size(); ++i)
      e.push_back(fMBAmpGe(tpis[i]));
  else if (ch == fMuSc)
    for (unsigned int i = 0; i < tpis.size(); ++i)
      e.push_back(fMBAmpMuSc(tpis[i]));
  else
    throw std::logic_error("GeSpectrum: Invalid channel to calculate energies for.");
  return e;
}
std::vector< double > GeSpectrum::CalculateTimes (const IDs::channel & chan, const std::vector< TPulseIsland * > & tpis) [private]
Takes a vector of TPIs and calculates all of their times.
Since we'll be using the std::upper_bound/stdlower_bound methods, this makes it possible to use the times of the TPIs without writing some hacky compare function (that would use the TAPAlgorithms).
Definition at line 230 of file GeSpectrum.cpp.
References fCFTimeGe, fCFTimeMuSc, fGeF, and fMuSc.
Referenced by ProcessEntry().
{
  std::vector<double> t;
  if (ch == fMuSc)
    for (unsigned int i = 0; i < tpis.size(); ++i)
      t.push_back(fCFTimeMuSc(tpis[i]));
  else if (ch == fGeF)
    for (unsigned int i = 0; i < tpis.size(); ++i)
      t.push_back(fCFTimeGe(tpis[i]));
  else
    throw std::logic_error("GeSpectrum: Invalid channel to calculate times for.");
  return t;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int GeSpectrum::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
Histograms the heights in the germanium with time cuts relative to muSc.
Parameters:
[in] gData See BaseModule::ProcessEntry
[in] gSetup See BaseModule::ProcessEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 87 of file GeSpectrum.cpp.
References CalculateEnergies(), CalculateTimes(), fADC2Energy, fGeF, fGeS, fHist_ADC, fHist_ADCFarOOT, fHist_ADCOOT, fHist_Energy, fHist_EnergyFarOOT, fHist_EnergyOOT, fHist_MeanTOffset, fHist_TimeADC, fHist_TimeEnergy, fHist_TimeFarOOT, fHist_TimeOOT, fMuSc, TGlobalData::fPulseIslandToChannelMap, fTimeWindow_Big, fTimeWindow_Small, TSetupData::GetBankName(), TSetupData::Instance(), RemovePileupMuScPulses(), IDs::channel::str(), and ThrowIfGeInsane().
{
  static const std::string bank_musc = TSetupData::Instance()->GetBankName(fMuSc.str());
  static const std::string bank_ges  = TSetupData::Instance()->GetBankName(fGeS.str());
  static const std::string bank_gef  = TSetupData::Instance()->GetBankName(fGeF.str());
  const std::map< std::string, std::vector<TPulseIsland*> >& TPIMap = gData->fPulseIslandToChannelMap;
  ThrowIfGeInsane(TPIMap.at(bank_ges), TPIMap.at(bank_gef));
  if (!(TPIMap.count(bank_musc) && TPIMap.count(bank_ges) && TPIMap.count(bank_gef)))
    return 0;
  else if (TPIMap.at(bank_musc).size() == 0 || TPIMap.at(bank_ges).size() == 0 || TPIMap.at(bank_gef).size() == 0)
    return 0;
  const std::vector<double> muScTimes  = CalculateTimes(fMuSc,   TPIMap.at(bank_musc));
  const std::vector<double> muScEnergies  = CalculateEnergies(fMuSc,   TPIMap.at(bank_musc));
  const std::vector<double> geTimes    = CalculateTimes(fGeF,    TPIMap.at(bank_gef));
  const std::vector<double> geEnergies = CalculateEnergies(fGeS, TPIMap.at(bank_ges));
  std::vector<double> muScTimesPP(muScTimes), muScEnergiesPP(muScEnergies);
  RemovePileupMuScPulses(muScTimesPP, muScEnergiesPP);
  //************************************//
  //***** First get average offset *****//
  //************************************//
  TH1I hTOff("hTOff", "Time Offset", 4000, -20000., 20000.);
  for (std::vector<double>::const_iterator geT = geTimes.begin(), prev = muScTimesPP.begin(), next;
       geT != geTimes.end();
       ++geT) {
    static const double unfound = 1e9;
    double dt[2] = {unfound, unfound}, &dt_prev = dt[0], &dt_next = dt[1];
    std::vector<double>::const_iterator end = muScTimesPP.end();
    next = std::upper_bound(prev, end, *geT);
    prev = next - 1;
    if (next == muScTimesPP.end())
      dt_prev = *geT - *prev;
    else if (next == muScTimesPP.begin()) {
      dt_next = *geT - *next;
      prev = next;
    } else {
      dt_prev = *geT - *prev;
      dt_next = *geT - *next;
    }
    for (unsigned int it = 0; it < 2; ++it)
      if (std::abs(dt[it]) < 20000.)
        hTOff.Fill(dt[it]);
  }
  double tOff = 0.;
  if (hTOff.Integral() > 1) {
    tOff = hTOff.GetMean();
    fHist_MeanTOffset->Fill(tOff);
  }
  //**************************//
  //***** Now make plots *****//
  //**************************//
  for (std::vector<double>::const_iterator geT = geTimes.begin(), geE = geEnergies.begin(), prev = muScTimesPP.begin(), next;
       geT != geTimes.end() && geE != geEnergies.end();
       ++geT, ++geE) {
    bool prev_found = false, next_found = false;
    double dt_prev, dt_next;
    // Find the time difference with the most recent muon
    // both before and after.
    std::vector<double>::const_iterator end = muScTimesPP.end();
    next = std::upper_bound(prev, end, *geT);
    prev = next - 1;
    if (next == muScTimesPP.end()) {
      dt_prev = *geT - *prev;
      prev_found = true;
    } else if (next == muScTimesPP.begin()) {
      dt_next = *geT - *next;
      next_found = true;
    } else {
      // The vast majority of cases are here
      dt_prev = *geT - *prev;
      dt_next = *geT - *next;
      prev_found = next_found = true;
    }
    // Plot energy
    if (( !prev_found || dt_prev > fTimeWindow_Big) && ( !next_found || dt_next < -fTimeWindow_Big) ) {
      fHist_ADCFarOOT->Fill(*geE);
      fHist_EnergyFarOOT->Fill(fADC2Energy->Eval(*geE));
    } else if ( (!prev_found || dt_prev > fTimeWindow_Small) && (!next_found || dt_next < -fTimeWindow_Small) ) {
      fHist_ADCOOT->Fill(*geE);
      fHist_EnergyOOT->Fill(fADC2Energy->Eval(*geE));
    } else {
      if (prev_found && dt_prev <= fTimeWindow_Small) {
        fHist_TimeADC->Fill(dt_prev, *geE);
        fHist_TimeEnergy->Fill(dt_prev, fADC2Energy->Eval(*geE));
      } else if (next_found && dt_next >= -fTimeWindow_Small) {
        fHist_TimeADC->Fill(dt_next, *geE);
        fHist_TimeEnergy->Fill(dt_next, fADC2Energy->Eval(*geE));
      } else {
        std::cout << "WARNING: Unexpected branch! Prev: (" << prev_found << ", " << dt_prev << "), Next: (" << next_found << ", " << dt_next << ")" << std::endl;
      }
    }
    fHist_ADC->Fill(*geE);
    fHist_Energy->Fill(fADC2Energy->Eval(*geE));
    // Plot time
    if (prev_found) {
      if (dt_prev > fTimeWindow_Big)
        fHist_TimeFarOOT->Fill(dt_prev);
      else if (dt_prev > fTimeWindow_Small)
        fHist_TimeOOT->Fill(dt_prev);
    }
    if (next_found) {
      if (dt_next < -fTimeWindow_Big)
        fHist_TimeFarOOT->Fill(dt_next);
      else if (dt_next < -fTimeWindow_Small)
        fHist_TimeOOT->Fill(dt_next);
    }
    // Silicon XRay
    //if (ge_energy >= 3260 && energy_ge <= 3290)
    // Aluminium XRay
    //if (*geE >= 340 && *geE <= 350) {
    // Mg27 Gamma
    // if (*geE >= 838 && *geE <= 848) {
    //   if (dt_prev != unfound) {
    //  fHist_Time->Fill(dt_prev);
    //  fHist_MoreTime->Fill(dt_prev);
    //   }
    //   if (dt_next != unfound) {
    //  fHist_Time->Fill(dt_next);
    //  fHist_MoreTime->Fill(dt_next);
    //   }
    // }
  }
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void GeSpectrum::RemovePileupMuScPulses (std::vector< double > & time, std::vector< double > & energy) [private]
Definition at line 280 of file GeSpectrum.cpp.
References fPileupProtectionWindow.
Referenced by ProcessEntry().
{
  if (t.empty()) return;
  std::vector<bool> rm(t.size(), false);
  if (t.front() < fPileupProtectionWindow) rm.front() = true;
  for (unsigned int i = 1; i < t.size(); ++i)
    if (t[i] - t[i-1] < fPileupProtectionWindow)
      rm[i] = rm[i-1] = true;
  rm.back() = true;
  for (unsigned int i = 0; i < t.size(); ++i) {
    if (rm[i]) {
      t.erase(t.begin()+i);
      e.erase(e.begin()+i);
      rm.erase(rm.begin()+i);
      --i;
    }
  }
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
void GeSpectrum::ThrowIfGeInsane (const std::vector< TPulseIsland * > & ge_fasts, const std::vector< TPulseIsland * > & ge_slows) [private]
Definition at line 258 of file GeSpectrum.cpp.
Referenced by ProcessEntry().
{
  if (ge1s.size() != ge2s.size())
    throw std::logic_error("Fast and slow vectors are not same size!");
  for (std::vector<TPulseIsland*>::const_iterator ge1 = ge1s.begin(), ge2 = ge2s.begin(); ge1 != ge1s.end(); ++ge1, ++ge2)
    if ((*ge1)->GetTimeStamp() != (*ge2)->GetTimeStamp())
      throw std::logic_error("Fast and slow timestamps don't match up when getting time");
}
void GeSpectrum::ThrowIfInputsInsane (const modules::options * opts) [private]
Definition at line 266 of file GeSpectrum.cpp.
References modules::options::GetDouble(), and modules::options::GetString().
Referenced by GeSpectrum().
{
  const std::string& gef_cfg = opts->GetString("gef_cfg");
  const double       gef_cf  = opts->GetDouble("gef_cf");
  const double       musc_cf = opts->GetDouble("musc_cf");
  const std::string  cf_str("constant_fraction=");
  std::stringstream ss(gef_cfg.substr(gef_cfg.find(cf_str) + cf_str.size()));
  double cf;
  ss >> cf;
  if (cf != gef_cf)
    throw std::logic_error("GeSpectrum: GeF CF in options don't match.");
  if (gef_cf <= 0. || gef_cf > 1. || musc_cf <= 0. || musc_cf > 1.)
    throw std::logic_error("GeSpectrum: CF are out of reasonable bounds (0. to 1.).");
}
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
TF1* GeSpectrum::fADC2Energy [private]
Definition at line 56 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
const Algorithm::ConstantFractionTime GeSpectrum::fCFTimeGe [private]
Definition at line 55 of file GeSpectrum.h.
Referenced by CalculateTimes().
const Algorithm::ConstantFractionTime GeSpectrum::fCFTimeMuSc [private]
Definition at line 55 of file GeSpectrum.h.
Referenced by CalculateTimes().
const IDs::channel GeSpectrum::fGeF [static, private]
Definition at line 64 of file GeSpectrum.h.
Referenced by CalculateTimes(), and ProcessEntry().
const IDs::channel GeSpectrum::fGeS [static, private]
Definition at line 63 of file GeSpectrum.h.
Referenced by CalculateEnergies(), and ProcessEntry().
TH1* GeSpectrum::fHist_ADC [private]
Definition at line 38 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
TH1* GeSpectrum::fHist_ADCFarOOT [private]
Definition at line 44 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
TH1* GeSpectrum::fHist_ADCOOT [private]
Definition at line 42 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
TH1* GeSpectrum::fHist_Energy [private]
Definition at line 39 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
TH1* GeSpectrum::fHist_EnergyFarOOT [private]
Definition at line 45 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
TH1* GeSpectrum::fHist_EnergyOOT [private]
Definition at line 43 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
TH1* GeSpectrum::fHist_MeanTOffset [private]
Definition at line 50 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
TH1* GeSpectrum::fHist_MoreTime [private]
Definition at line 41 of file GeSpectrum.h.
Referenced by GeSpectrum().
TH1* GeSpectrum::fHist_Time [private]
Definition at line 40 of file GeSpectrum.h.
Referenced by GeSpectrum().
TH2* GeSpectrum::fHist_TimeADC [private]
Definition at line 48 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
TH2* GeSpectrum::fHist_TimeEnergy [private]
Definition at line 49 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
TH1* GeSpectrum::fHist_TimeFarOOT [private]
Definition at line 47 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
TH1* GeSpectrum::fHist_TimeOOT [private]
Definition at line 46 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
const Algorithm::MaxBinAmplitude GeSpectrum::fMBAmpGe [private]
Definition at line 53 of file GeSpectrum.h.
Referenced by CalculateEnergies().
const Algorithm::MaxBinAmplitude GeSpectrum::fMBAmpMuSc [private]
Definition at line 54 of file GeSpectrum.h.
Referenced by CalculateEnergies().
const IDs::channel GeSpectrum::fMuSc [static, private]
Definition at line 65 of file GeSpectrum.h.
Referenced by CalculateEnergies(), CalculateTimes(), and ProcessEntry().
const double GeSpectrum::fPileupProtectionWindow [private]
Definition at line 60 of file GeSpectrum.h.
Referenced by RemovePileupMuScPulses().
const double GeSpectrum::fTimeWindow_Big [private]
Definition at line 59 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
const double GeSpectrum::fTimeWindow_Small [private]
Definition at line 58 of file GeSpectrum.h.
Referenced by GeSpectrum(), and ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/GeSpectrum.h
rootana/src/GeSpectrum.cpp