AlcapDAQ: PlotPedestalAndNoise Class Reference
PlotPedestalAndNoise Class Reference
[Modules]
Plots the pedestal and noise of each TPulseIsland and writes these to an SQLite database.
#include <PlotPedestalAndNoise.h>
Public Member Functions
PlotPedestalAndNoise (modules::options *opts)
The constructor.
~PlotPedestalAndNoise ()
Empty destructor.
int ProcessGenericEntry (TGlobalData *gData, TSetupData *gSetup)
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
Protected Attributes
TDirectory * dir
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, TSetupData *gSetup)
In every event, we loop over all the detectors and all the TPulseIslands and calculate the RMS and mean of the first fNSamples samples in the digitised pulse (i.e. the noise and the pedestal respectively).
virtual int BeforeFirstEntry (TGlobalData *gData, TSetupData *setup)
Nothing is done before each run.
virtual int AfterLastEntry (TGlobalData *gData, TSetupData *setup)
After each run, we write the mean and RMS of the first fNSamples to an SQLite database.
Private Attributes
std::map< std::string, TH2D * > fPedestalVsNoiseHistograms
The map that we store the pedestal vs. noise histograms for each channel.
int fNSamples
The number of samples we will look at in the TPulseIsland to calculate the mean and RMS (opt = "n_samples", default = 5).
bool fExportSQL
A bool to decide whether we export the pedestal and noise to the SQLite database (opt = "export_sql", default = false).
Detailed Description
Plots the pedestal and noise of each TPulseIsland and writes these to an SQLite database.
Author:
Andrew Edmonds
This module loops over TPulseIsland and plots the mean and RMS of the first n_samples into a 2D histogram. At the end of the run, it writes the mean values of each axis to an SQLite database along with the channel and bank names. This SQLite database can then be used by PulseCandidateFinder to set parameter values based on a certain number of sigma.
Definition at line 25 of file PlotPedestalAndNoise.h.
Constructor & Destructor Documentation
PlotPedestalAndNoise::PlotPedestalAndNoise (modules::options * opts)
The constructor.
The constructor looks in the opts for "n_samples" and sets the fNSamples variable (default = 5).
Parameters:
[in] opts Describe the options this module takes.
Definition at line 21 of file PlotPedestalAndNoise.cpp.
References fExportSQL, fNSamples, modules::options::GetBool(), and modules::options::GetInt().
                                                              :
   BaseModule("PlotPedestalAndNoise",opts){
  // Do something with opts here.  Has the user specified any
  // particular configuration that you want to know?
  // For example, perhaps this module wants an axis range:
  fNSamples = opts->GetInt("n_samples", 5);
  fExportSQL = opts->GetBool("export_sql", false);
}
PlotPedestalAndNoise::~PlotPedestalAndNoise ()
Empty destructor.
Definition at line 31 of file PlotPedestalAndNoise.cpp.
{
}
Member Function Documentation
int PlotPedestalAndNoise::AfterLastEntry (TGlobalData * gData, TSetupData * setup) [private, virtual]
After each run, we write the mean and RMS of the first fNSamples to an SQLite database.
Parameters:
[in] gData See BaseModule::AfterLastEntry
[in] setup See BaseModule::AfterLastEntry
Returns:
Non-zero to indicate a problem.
Reimplemented from BaseModule.
Definition at line 116 of file PlotPedestalAndNoise.cpp.
References BaseModule::Debug(), fExportSQL, fPedestalVsNoiseHistograms, TSetupData::GetBankName(), SetupNavigator::GetRunNumber(), and SetupNavigator::Instance().
{
  // Print extra info if we're debugging this module:
  if(Debug()){
     cout<<"-----PlotPedestalAndNoise::AfterLastEntry(): I'm debugging!"<<endl;
  }
  if (fExportSQL) {
    // Get the SQLite database file
    TSQLiteServer* server = new TSQLiteServer("sqlite://pedestals-and-noises.sqlite");
    std::stringstream query;
    std::string tablename = "pedestals_and_noises";
    if (server) {
      // Create the pedestals_and_noises table if it doesn't already exist
      query << "CREATE TABLE IF NOT EXISTS " << tablename << " (run INT, channel STRING, bank STRING, pedestal FLOAT, noise FLOAT)";
      server->Exec(query.str().c_str());
      query.str(""); // clear the stringstream after use
      int run_number = SetupNavigator::Instance()->GetRunNumber();
      // Now loop through the histograms and record the run_numberm channel, bank and mean and RMS of first fNSamples to the SQLite table
      for (std::map<std::string, TH2D*>::iterator histIter = fPedestalVsNoiseHistograms.begin(); histIter != fPedestalVsNoiseHistograms.end(); ++histIter) {
        std::string detname = histIter->first;
        std::string bankname = setup->GetBankName(detname);
        TH2D* pedestal_vs_noise_histogram = histIter->second;
        double pedestal = pedestal_vs_noise_histogram->GetMean(1);
        double noise = pedestal_vs_noise_histogram->GetMean(2);
        // See if this row already exists (result will equal 1 if it does)
        query << "SELECT COUNT(*) FROM " << tablename << " WHERE channel=\'" << detname << "\'";
        TSQLiteResult* result = (TSQLiteResult*) server->Query(query.str().c_str());  // get the result of this query
        TSQLiteRow* row = (TSQLiteRow*) result->Next(); // get the first row
        query.str(""); // clear the stringstream after use
        std::string n_table_entries = row->GetField(0);
        if (n_table_entries == "0") {
          // insert a new set of values
          query << "INSERT INTO " << tablename << " VALUES (" << run_number << ", \"" << detname << "\", \"" << bankname << "\", " << pedestal << ", " << noise << ");"; // insert the values
          server->Exec(query.str().c_str());
          query.str(""); // clear the stringstream after use
        }
        else if (n_table_entries == "1") {
          // just update the values that are already there
          query << "UPDATE " << tablename << " SET run=" << run_number << ", bank=\'" << bankname << "\', pedestal=" << pedestal << ", noise=" << noise << " WHERE channel=\'" << detname << "\';";
          server->Exec(query.str().c_str());
          query.str(""); // clear the stringstream after use
        }
        // Need to delete the TSQLiteResult and TSQLiteRow like the ROOT documentation says so
        delete result;
        delete row;
      }
    }
    else {
      std::cout << "Error: Couldn't connect to SQLite database" << std::endl;
    }
  }
  return 0;
}
int PlotPedestalAndNoise::BeforeFirstEntry (TGlobalData * gData, TSetupData * setup) [private, virtual]
Nothing is done before each run.
Parameters:
[in] gData See BaseModule::BeforeFirstEntry
[in] setup See BaseModule::BeforeFirstEntry
Returns:
Non-zero to indicate a problem.
Reimplemented from BaseModule.
Definition at line 37 of file PlotPedestalAndNoise.cpp.
References BaseModule::Debug().
{
  // Print extra info if we're debugging this module:
  if(Debug()){
     cout<<"-----PlotPedestalAndNoise::BeforeFirstEntry(): I'm debugging!"<<endl;
  }
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 59 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), TemplateCreator::AfterLastEntry(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), AfterLastEntry(), IslandLength::AfterLastEntry(), MakeMuonEvents::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), and PulseViewer::ProcessEntry().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 51 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 62 of file BaseModule.h.
References BaseModule::fDirectory.
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 54 of file BaseModule.h.
References BaseModule::fName.
Referenced by PlotTime::ProcessEntry(), and PlotAmplitude::ProcessEntry().
{return fName.c_str();};
int PlotPedestalAndNoise::ProcessEntry (TGlobalData * gData, TSetupData * gSetup) [private, virtual]
In every event, we loop over all the detectors and all the TPulseIslands and calculate the RMS and mean of the first fNSamples samples in the digitised pulse (i.e. the noise and the pedestal respectively).
Parameters:
[in] gData See BaseModule::ProcessEntry
[in] gSetup See BaseModule::ProcessEntry
Returns:
Non-zero to indicate a problem.
Reimplemented from BaseModule.
Definition at line 48 of file PlotPedestalAndNoise.cpp.
References fNSamples, fPedestalVsNoiseHistograms, TGlobalData::fPulseIslandToChannelMap, TSetupData::GetDetectorName(), TSetupData::GetNBits(), and TSetupData::Instance().
{
  // Prepare a few variables
  std::string bankname, detname;
  PulseIslandList thePulseIslands;
  StringPulseIslandMap::const_iterator it;
  // Loop over each detector
  for(it = gData->fPulseIslandToChannelMap.begin(); it != gData->fPulseIslandToChannelMap.end(); ++it){
    // Get the bank and detector names for this detector
    bankname = it->first;
    detname = setup->GetDetectorName(bankname);
    // Get the TPIs
    thePulseIslands = it->second;
    if (thePulseIslands.size() == 0) continue; // no pulses here..
    // Create the histogram that will store all the average RMS noises from each event
    if (fPedestalVsNoiseHistograms.find(detname) == fPedestalVsNoiseHistograms.end()) {
      int n_bits = TSetupData::Instance()->GetNBits(bankname);
      int x_min = 0;
      int x_max = std::pow(2, n_bits);
      int n_bins_x = (x_max - x_min)/10;
      int y_min = 0;
      int y_max = 200;
      int n_bins_y = (y_max - y_min)*10;
      std::string histname = "fPedestalVsNoiseHistogram_" + detname;
      std::stringstream histtitle;
      histtitle << "Plot of the Pedestal vs Noise (mean and RMS of first " << fNSamples << " samples) in " << detname;
      TH2D* histogram = new TH2D(histname.c_str(), histtitle.str().c_str(), n_bins_x,x_min,x_max, n_bins_y,y_min,y_max);
      histogram->GetXaxis()->SetTitle("Pedestal [ADC]");
      histogram->GetYaxis()->SetTitle("Noise [ADC]");
      fPedestalVsNoiseHistograms[detname] = histogram;
    }
    TH2D* pedestal_vs_noise_histogram = fPedestalVsNoiseHistograms[detname];
    // Loop through all the pulses
    for (PulseIslandList::iterator pulseIter = thePulseIslands.begin(); pulseIter != thePulseIslands.end(); ++pulseIter) {
      const std::vector<int>& theSamples = (*pulseIter)->GetSamples();
      double sum = 0;
      for (int iSample = 0; iSample < fNSamples; ++iSample) {
        sum += theSamples.at(iSample);
      }
      double mean = sum / fNSamples;
      double sum_of_deviations_squared = 0;
      for (int iSample = 0; iSample < fNSamples; ++iSample) {
        sum_of_deviations_squared += (theSamples.at(iSample) - mean)*(theSamples.at(iSample) - mean);
      }
      double RMS = std::sqrt(sum_of_deviations_squared);
      pedestal_vs_noise_histogram->Fill(mean, RMS);
    } // end loop through pulses
  } // end loop through detectors
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 49 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 47 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Field Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 85 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), ExportPulse::ExportPulse(), MakeMuonEvents::MakeMuonEvents(), PlotAmplitude::PlotAmplitude(), PlotAmpVsTDiff::PlotAmpVsTDiff(), and PlotTime::PlotTime().
bool PlotPedestalAndNoise::fExportSQL [private]
A bool to decide whether we export the pedestal and noise to the SQLite database (opt = "export_sql", default = false).
Definition at line 80 of file PlotPedestalAndNoise.h.
Referenced by AfterLastEntry(), and PlotPedestalAndNoise().
int PlotPedestalAndNoise::fNSamples [private]
The number of samples we will look at in the TPulseIsland to calculate the mean and RMS (opt = "n_samples", default = 5).
Definition at line 75 of file PlotPedestalAndNoise.h.
Referenced by PlotPedestalAndNoise(), and ProcessEntry().
std::map<std::string, TH2D*> PlotPedestalAndNoise::fPedestalVsNoiseHistograms [private]
The map that we store the pedestal vs. noise histograms for each channel.
Definition at line 70 of file PlotPedestalAndNoise.h.
Referenced by AfterLastEntry(), and ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/plotters/PlotPedestalAndNoise.h
rootana/src/plotters/PlotPedestalAndNoise.cpp