AlcapDAQ: PlotTDP_TDiff Class Reference
PlotTDP_TDiff Class Reference
[Modules]
This module plots the time difference between TDetectorPulses (TDPs) in two given detectors.
#include <PlotTDP_TDiff.h>
Public Member Functions
PlotTDP_TDiff (modules::options *opts)
Constructor.
~PlotTDP_TDiff ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
In every entry the time difference between all the TDPs in one detector and all the TDPs in the other detector is calculated and plotted into a histogram.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
Before each run, the DetectorPulseLists for the necessary detectors are stored and the histograms are created.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
Nothing needs to be done after each run.
Private Attributes
IDs::source fSourceA
The sources that are requested.
IDs::source fSourceB
DetectorPulseList fDetPulsesA
The pulse lists for the detector pulses that we want.
DetectorPulseList fDetPulsesB
double fTimeLow
double fTimeHigh
TH1F * fTDiffPlot
The histogram we fill.
Detailed Description
This module plots the time difference between TDetectorPulses (TDPs) in two given detectors.
Author:
Andrew Edmonds
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 24 of file PlotTDP_TDiff.h.
Constructor & Destructor Documentation
PlotTDP_TDiff::PlotTDP_TDiff (modules::options * opts)
Constructor.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 17 of file PlotTDP_TDiff.cpp.
References fSourceA, fSourceB, and modules::options::GetString().
                                                :
   BaseModule("PlotTDP_TDiff",opts),
  fTimeLow(opts->GetDouble("time_low",-1.e5)), fTimeHigh(opts->GetDouble("time_high",1.e5)){
  // Do something with opts here.  Has the user specified any
  // particular configuration that you want to know?
  // For example, perhaps this module wants an axis range:
  fSourceA = IDs::source(opts->GetString("source_a"));
  fSourceB = IDs::source(opts->GetString("source_b"));
}
PlotTDP_TDiff::~PlotTDP_TDiff ()
Is anything done in the destructor?
Definition at line 29 of file PlotTDP_TDiff.cpp.
{
}
Member Function Documentation
int PlotTDP_TDiff::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Nothing needs to be done after each run.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 100 of file PlotTDP_TDiff.cpp.
References BaseModule::Debug().
{
  // Print extra info if we're debugging this module:
  if(Debug()){
     cout<<"-----PlotTDP_TDiff::AfterLastEntry(): I'm debugging!"<<endl;
  }
  return 0;
}
int PlotTDP_TDiff::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Before each run, the DetectorPulseLists for the necessary detectors are stored and the histograms are created.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 35 of file PlotTDP_TDiff.cpp.
References IDs::source::Channel(), BaseModule::Debug(), fSourceA, fSourceB, fTDiffPlot, fTimeLow, BaseModule::GetName(), modules::navigator::Instance(), IDs::source::str(), and modules::parser::ToCppValid().
{
  // Print extra info if we're debugging this module:
  if(Debug()){
     cout<<"-----PlotTDP_TDiff::BeforeFirstEntry(): I'm debugging!"<<endl;
  }
  if(!modules::navigator::Instance()->Before("MakeDetectorPulses",GetName())){
    cout<<"MakeDetectorPulses must be used before PlotTDP_TDiff"<<endl;
    return 1;
  }
  // Create the histogram
  std::string detname_a = fSourceA.Channel().str();
  std::string detname_b = fSourceB.Channel().str();
  std::string histogram_name = modules::parser::ToCppValid("h" + fSourceA.str() + "_" + fSourceB.str() + "_TDiff");
  std::string histogram_title = "Time Difference between TDP source " + fSourceA.str() + "_" + fSourceB.str();
  fTDiffPlot = new TH1F(histogram_name.c_str(), histogram_title.c_str(), 600, fTimeLow, fTimeLow);
  std::string axis_title = "t_{" + detname_a + "} - t_{" + detname_b + "} [ns]";
  fTDiffPlot->GetXaxis()->SetTitle(axis_title.c_str());
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int PlotTDP_TDiff::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
In every entry the time difference between all the TDPs in one detector and all the TDPs in the other detector is calculated and plotted into a histogram.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 62 of file PlotTDP_TDiff.cpp.
References BaseModule::Debug(), fDetPulsesA, fDetPulsesB, fSourceA, fSourceB, fTDiffPlot, and gDetectorPulseMap.
{
  // Loop over all TDP sources
  for(SourceDetPulseMap::const_iterator i_source=gDetectorPulseMap.begin();
      i_source!= gDetectorPulseMap.end(); ++i_source){
    //    std::cout << i_source->first << ", " << fSourceA << std::endl;
    if ( (i_source->first).matches(fSourceA)) {
      fDetPulsesA = i_source->second;
      if (Debug()) {
        std::cout << "PlotTDP_TDiff: " << fSourceA << " pulses found. (" << fDetPulsesA.size() << " pulses)" << std::endl;;
      }
    }
    else if ((i_source->first).matches(fSourceB)) {
      fDetPulsesB = i_source->second;
      if (Debug()) {
        std::cout << "PlotTDP_TDiff: " << fSourceB << " pulses found. (" << fDetPulsesB.size() << " pulses)" << std::endl;
      }
    }
  }
  // Loop through the TDPs in both channels
  for (DetectorPulseList::const_iterator i_det_pulse_a = fDetPulsesA.begin(); i_det_pulse_a != fDetPulsesA.end(); ++i_det_pulse_a) {
    for (DetectorPulseList::const_iterator i_det_pulse_b = fDetPulsesB.begin(); i_det_pulse_b != fDetPulsesB.end(); ++i_det_pulse_b) {
      double time_det_pulse_a = (*i_det_pulse_a)->GetTime();
      double time_det_pulse_b = (*i_det_pulse_b)->GetTime();
      double time_difference = time_det_pulse_a - time_det_pulse_b; // this is the same way as specified in PlotTAP_TDiff to maintain consistency
      fTDiffPlot->Fill(time_difference);
    }
  }
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
DetectorPulseList PlotTDP_TDiff::fDetPulsesA [private]
The pulse lists for the detector pulses that we want.
Definition at line 61 of file PlotTDP_TDiff.h.
Referenced by ProcessEntry().
DetectorPulseList PlotTDP_TDiff::fDetPulsesB [private]
Definition at line 61 of file PlotTDP_TDiff.h.
Referenced by ProcessEntry().
IDs::source PlotTDP_TDiff::fSourceA [private]
The sources that are requested.
Definition at line 58 of file PlotTDP_TDiff.h.
Referenced by BeforeFirstEntry(), PlotTDP_TDiff(), and ProcessEntry().
IDs::source PlotTDP_TDiff::fSourceB [private]
Definition at line 58 of file PlotTDP_TDiff.h.
Referenced by BeforeFirstEntry(), PlotTDP_TDiff(), and ProcessEntry().
TH1F* PlotTDP_TDiff::fTDiffPlot [private]
The histogram we fill.
Definition at line 67 of file PlotTDP_TDiff.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
double PlotTDP_TDiff::fTimeHigh [private]
Definition at line 63 of file PlotTDP_TDiff.h.
double PlotTDP_TDiff::fTimeLow [private]
Definition at line 63 of file PlotTDP_TDiff.h.
Referenced by BeforeFirstEntry().
The documentation for this class was generated from the following files:
rootana/src/plotters/PlotTDP_TDiff.h
rootana/src/plotters/PlotTDP_TDiff.cpp