AlcapDAQ: MakeSiliconEvents Class Reference
MakeSiliconEvents Class Reference
[Modules]
A one line description of what your module does.
#include <MakeSiliconEvents.h>
Public Member Functions
MakeSiliconEvents (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~MakeSiliconEvents ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Member Functions
const IDs::source & GetTDPSource (const std::string &ch)
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
The big kahuna. Overload this in the derived class and it will be called for each event.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
Private Attributes
IDs::source fSourceList [LR::kNum][Ch::kNum]
double fSiWindow
Detailed Description
A one line description of what your module does.
Author:
AuthorName
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 36 of file MakeSiliconEvents.h.
Constructor & Destructor Documentation
MakeSiliconEvents::MakeSiliconEvents (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 17 of file MakeSiliconEvents.cpp.
                                                        :
   BaseModule("MakeSiliconEvents",opts,false),
  fSiWindow(opts->GetDouble("si_window",100)){
}
MakeSiliconEvents::~MakeSiliconEvents ()
Is anything done in the destructor?
Definition at line 22 of file MakeSiliconEvents.cpp.
{
}
Member Function Documentation
int MakeSiliconEvents::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Optional method which is called once after the main event loop Can be used to dump a summary or finalise a histogram
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 69 of file MakeSiliconEvents.cpp.
{
  return 0;
}
int MakeSiliconEvents::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Optional method which is called once before the main event loop Can be used to parse options and setup histograms.
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 25 of file MakeSiliconEvents.cpp.
References fSourceList, and GetTDPSource().
{
  // Get all the sources for the silicon channels
  for(int i=0;i<LR::kNum;i++){
     for(int ch=0;ch<Ch::kNum;ch++){
        fSourceList[i][ch]=GetTDPSource(Form("Si%s%s",LR::str(i),Ch::str(ch)));
     }
  }
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
const IDs::source & MakeSiliconEvents::GetTDPSource (const std::string & ch) [private]
Definition at line 73 of file MakeSiliconEvents.cpp.
References gDetectorPulseMap, IDs::kErrorDetector, and IDs::kErrorSlowFast.
Referenced by BeforeFirstEntry().
{
    IDs::channel chan(ch);
    SourceDetPulseMap::const_iterator i_so=gDetectorPulseMap.begin();
    while(i_so!=gDetectorPulseMap.end() && !(i_so->first==chan)) ++i_so;
    if(i_so==gDetectorPulseMap.end()){
        static IDs::source invalid(IDs::kErrorDetector, IDs::kErrorSlowFast, "","");
        return invalid;
    }
    return i_so->first;
}
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int MakeSiliconEvents::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
The big kahuna. Overload this in the derived class and it will be called for each event.
Parameters:
gData Pointer to current map of all TPIs [ WILL CHANGE SHORTLY ]
gSetup Pointer to TSetupData for this run [ WILL CHANGE SHORTLY ]
Returns:
0 on success and non-zero on failure
Implements BaseModule.
Definition at line 35 of file MakeSiliconEvents.cpp.
References TSiliconEvent::AddThin(), TMuonEvent::BeginPulses(), TMuonEvent::EndPulses(), fSiWindow, fSourceList, TDetectorPulse::GetEnergy(), TDetectorPulse::GetTime(), gMuonEvents, TMuonEvent::InsertSiliconEvent(), TDetectorPulse::IsGood(), TDetectorPulse::kFast, TDetectorPulse::kSlow, TSiliconEvent::Reset(), and TSiliconEvent::SetThick().
{
  // loop over each TME
  TSiliconEvent si_hit;
  for(MuonEventList::iterator i_tme=gMuonEvents.begin();
          i_tme!=gMuonEvents.end(); ++i_tme){
    TMuonEvent* tme=*i_tme;
    // loop over both Si packages
    for(int i_side=0;i_side <2; ++i_side){
       // Loop over the thick silicon
       for(DetectorPulseList::const_iterator i_Si2=tme->BeginPulses(fSourceList[i_side][Ch::k2]);
             i_Si2!=tme->EndPulses(fSourceList[i_side][Ch::k2]); ++i_Si2){
           si_hit.Reset();
           double thick_time=(*i_Si2)->GetTime();
           double E_thick=(*i_Si2)->GetEnergy(TDetectorPulse::kSlow);
           si_hit.SetThick(E_thick,thick_time);
           for(int i=0; i<4;++i){
              for(DetectorPulseList::const_iterator i_thin=tme->BeginPulses(fSourceList[i_side][i]);
             i_thin!=tme->EndPulses(fSourceList[i_side][i]); ++i_thin){
                 const TDetectorPulse* pulse=*i_thin;
                 if(!pulse->IsGood())continue;
                 double time=pulse->GetTime(TDetectorPulse::kFast);
                 if( time > thick_time +fSiWindow) break;
                 if( time < thick_time -fSiWindow) continue;
                 si_hit.AddThin(i+1,pulse->GetEnergy(TDetectorPulse::kSlow));
              }
           }
           tme->InsertSiliconEvent((TMuonEvent::LeftRight_t) i_side,si_hit);
       }
    } // loop over both Si packages
  } // loop over each TME
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
double MakeSiliconEvents::fSiWindow [private]
Definition at line 57 of file MakeSiliconEvents.h.
Referenced by ProcessEntry().
IDs::source MakeSiliconEvents::fSourceList[LR::kNum][Ch::kNum] [private]
Definition at line 56 of file MakeSiliconEvents.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/TME_generators/MakeSiliconEvents.h
rootana/src/TME_generators/MakeSiliconEvents.cpp