AlcapDAQ: FixedWindowMEGenerator Class Reference
FixedWindowMEGenerator Class Reference
#include <FixedWindowMEGenerator.h>
Classes
struct Detector_t
Public Member Functions
FixedWindowMEGenerator (TMEGeneratorOptions *opts)
virtual ~FixedWindowMEGenerator ()
virtual int ProcessPulses (MuonEventList &muonEventsOut, const SourceDetPulseMap &detectorPulsesIn)
const IDs::generator & GetGenerator () const
Protected Member Functions
bool Debug () const
Private Types
typedef std::vector< Detector_t > SourceList
Private Member Functions
int Init (const SourceDetPulseMap &)
void Reset ()
void AddPulsesInWindow (TMuonEvent *tme, double window, Detector_t &detector)
Private Attributes
bool fInit
double fEventWindow
Detector_t fMuSc
SourceList fDetectors
Detailed Description
Definition at line 8 of file FixedWindowMEGenerator.h.
Member Typedef Documentation
typedef std::vector<Detector_t> FixedWindowMEGenerator::SourceList [private]
Definition at line 29 of file FixedWindowMEGenerator.h.
Constructor & Destructor Documentation
FixedWindowMEGenerator::FixedWindowMEGenerator (TMEGeneratorOptions * opts)
Definition at line 12 of file FixedWindowMEGenerator.cpp.
References fEventWindow, and modules::options::GetDouble().
                                                                       :
        TVMuonEventGenerator("FixedWindow",opts),fInit(true){
        fEventWindow=opts->GetDouble("event_window",1e4);
}
virtual FixedWindowMEGenerator::~FixedWindowMEGenerator () [inline, virtual]
Definition at line 33 of file FixedWindowMEGenerator.h.
{};
Member Function Documentation
void FixedWindowMEGenerator::AddPulsesInWindow (TMuonEvent * tme, double window, Detector_t & detector) [private]
Definition at line 77 of file FixedWindowMEGenerator.cpp.
References TMuonEvent::AddPulses(), TMuonEvent::AllPulsesUsed(), FixedWindowMEGenerator::Detector_t::end_window, TMuonEvent::GetTime(), TDetectorPulse::kFast, FixedWindowMEGenerator::Detector_t::pulses, FixedWindowMEGenerator::Detector_t::source, and FixedWindowMEGenerator::Detector_t::start_window.
Referenced by ProcessPulses().
{
    // Get the central time for this event;
    double central_time=tme->GetTime();
    double early_edge=central_time-window;
    double late_edge=central_time+window;
    // advance the start and stop iterators that define the range of pulses
    // contained in the window
    DetectorPulseList::const_iterator& start=detector.start_window;
    DetectorPulseList::const_iterator& stop=detector.end_window;
    const DetectorPulseList::const_iterator& end=detector.pulses->end();
    //const DetectorPulseList::const_iterator& begin=detector.pulses->begin();
    // skip empty lists
    if(start==end) return;
    // Move the iterator for the start of the window
    DetectorPulseList::const_iterator i_tmp=start;
    while( (i_tmp !=end)){
        // skip over bad TDPs
        while( (i_tmp!=end) && !(*i_tmp)->IsGood() ) ++i_tmp;
        // if there are no TDPs left we can finish already
        if(i_tmp==end) return;
        double time=(*i_tmp)->GetTime(TDetectorPulse::kFast);
        if(time<early_edge) ++i_tmp;
        else break;
    }
    start=i_tmp;
    // Move the iteator for the end of the window
    while( (i_tmp !=end)){
        // skip over bad TDPs
        while( (i_tmp!=end) && !(*i_tmp)->IsGood() ) ++i_tmp;
        // if there are no TDPs left we can finish already
        if(i_tmp==end) break;
        double time=(*i_tmp)->GetTime(TDetectorPulse::kFast);
        if(time<late_edge) ++i_tmp;
        else break;
    }
    stop=i_tmp;
    // Add all pulses in the current window to the tme
    tme->AddPulses(*detector.source,start,stop);
    // Flag if we've used all of a channels pulses
    if(stop==detector.pulses->end()) tme->AllPulsesUsed(*detector.source);
}
bool TVMuonEventGenerator::Debug () const [inline, protected, inherited]
Definition at line 25 of file TVMuonEventGenerator.h.
Referenced by MaxTimeDiffMEGenerator::ProcessPulses().
{return fDebug;};
const IDs::generator& TVMuonEventGenerator::GetGenerator () const [inline, inherited]
Definition at line 22 of file TVMuonEventGenerator.h.
References TVMuonEventGenerator::fGenerator.
{return fGenerator;}
int FixedWindowMEGenerator::Init (const SourceDetPulseMap & detectorPulsesIn) [private]
Definition at line 17 of file FixedWindowMEGenerator.cpp.
References fDetectors, fMuSc, IDs::source::isWildCardChannel(), IDs::kMuSc, and FixedWindowMEGenerator::Detector_t::source.
Referenced by ProcessPulses().
{
    for(SourceDetPulseMap::const_iterator i_source=detectorPulsesIn.begin();
            i_source!=detectorPulsesIn.end();++i_source){
        // if i_source->source is muSc then
        if(i_source->first.matches(IDs::channel(IDs::kMuSc))){
            // if source is wildcard then select fMuSc
            if(!fMuSc.source || fMuSc.source->isWildCardChannel()){
                fMuSc=Detector_t(i_source);
            }else{
                cout<<"FixedWindowMEGenerator: Error: Multiple muSc TDP sources found"<<endl;
                return 1;
            }
        }else{
            fDetectors.push_back(Detector_t(i_source));
        }
    }
    return 0;
}
int FixedWindowMEGenerator::ProcessPulses (MuonEventList & muonEventsOut, const SourceDetPulseMap & detectorPulsesIn) [virtual]
Implements TVMuonEventGenerator.
Definition at line 44 of file FixedWindowMEGenerator.cpp.
References AddPulsesInWindow(), fDetectors, fEventWindow, fInit, fMuSc, Init(), FixedWindowMEGenerator::Detector_t::pulses, and Reset().
{
    if(fInit) {
        int error=Init(detectorPulsesIn);
        if(error) return error;
        fInit=false;
    }else{
        Reset();
    }
    // Loop over all muons
    for(DetectorPulseList::const_iterator i_muSc=fMuSc.pulses->begin();
            i_muSc!=fMuSc.pulses->end(); ++i_muSc){
        // Make a TME centred on this muon
        TMuonEvent* tme=new TMuonEvent(*i_muSc, fEventWindow);
        // Add all muon pulses in the event window to this TME
        AddPulsesInWindow(tme,fEventWindow,fMuSc);
        for(SourceList::iterator i_det=fDetectors.begin();
                i_det!=fDetectors.end(); ++i_det){
            // Add all pulses in the event window to this TME
            AddPulsesInWindow(tme,fEventWindow,*i_det);
        }
        //if(Debug()) cout<<"FixedWindowMEGenerator::ProcessPulses:"
        //    " Created TME with "<<tme->TotalNumPulses()<<" pulses" <<endl;
        // Add TME to list of event
        muonEventsOut.push_back(tme);
    }
    return 0;
}
void FixedWindowMEGenerator::Reset () [private]
Definition at line 36 of file FixedWindowMEGenerator.cpp.
References fDetectors, fMuSc, and FixedWindowMEGenerator::Detector_t::Reset().
Referenced by ProcessPulses().
{
    fMuSc.Reset();
    for(SourceList::iterator i_det=fDetectors.begin();
            i_det!=fDetectors.end(); ++i_det){
        i_det->Reset();
    }
}
Member Data Documentation
SourceList FixedWindowMEGenerator::fDetectors [private]
Definition at line 48 of file FixedWindowMEGenerator.h.
Referenced by Init(), ProcessPulses(), and Reset().
double FixedWindowMEGenerator::fEventWindow [private]
Definition at line 46 of file FixedWindowMEGenerator.h.
Referenced by FixedWindowMEGenerator(), and ProcessPulses().
bool FixedWindowMEGenerator::fInit [private]
Definition at line 45 of file FixedWindowMEGenerator.h.
Referenced by ProcessPulses().
Detector_t FixedWindowMEGenerator::fMuSc [private]
Definition at line 47 of file FixedWindowMEGenerator.h.
Referenced by Init(), ProcessPulses(), and Reset().
The documentation for this class was generated from the following files:
rootana/src/TME_generators/FixedWindowMEGenerator.h
rootana/src/TME_generators/FixedWindowMEGenerator.cpp