AlcapDAQ: DataDir Class Reference
DataDir Class Reference
Keeps track of the directories related to processing files for ODBCheck.
#include <DataDir.hh>
Public Member Functions
DataDir ()
Setters
Set the directory locations. Either pass the path for the directory or the user will be prompted.
void SetRawDir (const std::string &raw_dir)
void SetRawDir ()
void SetODBDir (const std::string &odb_dir)
void SetODBDir ()
void SetHistDir (const std::string &hist_dir)
void SetHistDir ()
void SetCorrDir (const std::string &corr_dir)
void SetCorrDir ()
Getters
Get path to files corresponding to run number.
Parameters
[in] run Run number
std::string GetRawFileName (int run) const
std::string GetODBFileName (int run) const
std::string GetHistFileName (int run) const
std::string GetCorrFileName (int run) const
Static Private Member Functions
static std::string GetCanonicalRun (int run)
Private Attributes
Extensions
The extensions associated with each of the file types.
std::string fRawExt
std::string fODBExt
std::string fHistExt
std::string fCorrExt
Directories
The directories where the files are located.
std::string fRawDir
std::string fODBDir
std::string fHistDir
std::string fCorrDir
Prepensions
Each file type has certain naming conventions. These are the first few characters of a file name.
std::string fRawPre
std::string fODBPre
std::string fHistPre
std::string fCorrPre
Detailed Description
Keeps track of the directories related to processing files for ODBCheck.
The raw data, ODB files, histogram files, and correction files are all (possible) required at some point. Once those directories have been set here, with just a run number the methods of DataDir allow one to get a string that represents the path to any of these files.
Definition at line 24 of file DataDir.hh.
Constructor & Destructor Documentation
DataDir::DataDir ()
Definition at line 7 of file DataDir.cc.
                  : fRawExt(".mid"), fODBExt(".odb"), fHistExt(".root"), fCorrExt(".odb"),
                      fRawDir(""), fODBDir(""), fHistDir(""), fCorrDir(""),
                      fRawPre("run"), fODBPre("run"), fHistPre("hist"), fCorrPre("corr") {}
Member Function Documentation
std::string DataDir::GetCanonicalRun (int run) static private
Takes run number and returns in a format that can be included in a file name.
Parameters
[in] run Run number
Returns
String representing the run number (5 characters)
Definition at line 11 of file DataDir.cc.
References sprintf().
Referenced by GetCorrFileName(), GetHistFileName(), GetODBFileName(), and GetRawFileName().
{
   static const std::string def("00000");
   char num[8];
   if (run < 0 || run > 99999)
     return def;
   sprintf(num, "%05d", run);
   return std::string(num);
 }
std::string DataDir::GetCorrFileName (int run) const
Definition at line 67 of file DataDir.cc.
References fCorrDir, fCorrExt, fCorrPre, and GetCanonicalRun().
Referenced by ODBCheck::OutputCorrections().
{
   return fCorrDir + fCorrPre + GetCanonicalRun(run) + fCorrExt;
 }
std::string DataDir::GetHistFileName (int run) const
Definition at line 63 of file DataDir.cc.
References fHistDir, fHistExt, fHistPre, and GetCanonicalRun().
Referenced by ODBCheck::Check().
{
   return fHistDir + fHistPre + GetCanonicalRun(run) + fHistExt;
 }
std::string DataDir::GetODBFileName (int run) const
Definition at line 59 of file DataDir.cc.
References fODBDir, fODBExt, fODBPre, and GetCanonicalRun().
Referenced by ODBCheck::Check().
{
   return fODBDir + fODBPre + GetCanonicalRun(run) + fODBExt;
 }
std::string DataDir::GetRawFileName (int run) const
Definition at line 55 of file DataDir.cc.
References fRawDir, fRawExt, fRawPre, and GetCanonicalRun().
{
   return fRawDir + fRawPre + GetCanonicalRun(run) + fRawExt;
 }
void DataDir::SetCorrDir (const std::string & corr_dir)
Definition at line 46 of file DataDir.cc.
References fCorrDir.
Referenced by ODBCheck::SetDirs().
{
   fCorrDir = corr_dir;
 }
void DataDir::SetCorrDir ()
Definition at line 50 of file DataDir.cc.
References fCorrDir.
{
   std::cout << "Enter corrections directory: ";
   std::cin >> fCorrDir;
 }
void DataDir::SetHistDir (const std::string & hist_dir)
Definition at line 37 of file DataDir.cc.
References fHistDir.
Referenced by ODBCheck::SetDirs().
{
   fHistDir = hist_dir;
 }
void DataDir::SetHistDir ()
Definition at line 41 of file DataDir.cc.
References fHistDir.
{
   std::cout << "Enter histogram directory: ";
   std::cin >> fHistDir;
 }
void DataDir::SetODBDir (const std::string & odb_dir)
Definition at line 28 of file DataDir.cc.
References fODBDir.
Referenced by ODBCheck::SetDirs().
{
   fODBDir = odb_dir;
 }
void DataDir::SetODBDir ()
Definition at line 32 of file DataDir.cc.
References fODBDir.
{
   std::cout << "Enter ODB directory: ";
   std::cin >> fODBDir;
 }
void DataDir::SetRawDir (const std::string & raw_dir)
Definition at line 20 of file DataDir.cc.
References fRawDir.
Referenced by ODBCheck::SetDirs().
{
   fRawDir = raw_dir;
 }
void DataDir::SetRawDir ()
Definition at line 23 of file DataDir.cc.
References fRawDir.
{
   std::cout << "Enter raw data directory: ";
   std::cin >> fRawDir;
 }
Field Documentation
std::string DataDir::fCorrDir private
Definition at line 36 of file DataDir.hh.
Referenced by GetCorrFileName(), and SetCorrDir().
std::string DataDir::fCorrExt private
Definition at line 31 of file DataDir.hh.
Referenced by GetCorrFileName().
std::string DataDir::fCorrPre private
Definition at line 42 of file DataDir.hh.
Referenced by GetCorrFileName().
std::string DataDir::fHistDir private
Definition at line 36 of file DataDir.hh.
Referenced by GetHistFileName(), and SetHistDir().
std::string DataDir::fHistExt private
Definition at line 31 of file DataDir.hh.
Referenced by GetHistFileName().
std::string DataDir::fHistPre private
Definition at line 42 of file DataDir.hh.
Referenced by GetHistFileName().
std::string DataDir::fODBDir private
Definition at line 36 of file DataDir.hh.
Referenced by GetODBFileName(), and SetODBDir().
std::string DataDir::fODBExt private
Definition at line 31 of file DataDir.hh.
Referenced by GetODBFileName().
std::string DataDir::fODBPre private
Definition at line 42 of file DataDir.hh.
Referenced by GetODBFileName().
std::string DataDir::fRawDir private
Definition at line 36 of file DataDir.hh.
Referenced by GetRawFileName(), and SetRawDir().
std::string DataDir::fRawExt private
Definition at line 31 of file DataDir.hh.
Referenced by GetRawFileName().
std::string DataDir::fRawPre private
Definition at line 42 of file DataDir.hh.
Referenced by GetRawFileName().
The documentation for this class was generated from the following files:
analyzer/odb_check/include/DataDir.hh
analyzer/odb_check/src/DataDir.cc