AlcapDAQ: MakeMuonEvents Class Reference
MakeMuonEvents Class Reference
#include <MakeMuonEvents.h>
Public Member Functions
MakeMuonEvents (modules::options *opts)
~MakeMuonEvents ()
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Member Functions
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *aSetup)
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *aSetup)
The big kahuna. Overload this in the derived class and it will be called for each event.
Private Attributes
std::string fAlgorithm
TVMuonEventGenerator * fGenerator
modules::options * fOptions
Detailed Description
Definition at line 12 of file MakeMuonEvents.h.
Constructor & Destructor Documentation
MakeMuonEvents::MakeMuonEvents (modules::options * opts)
Definition at line 23 of file MakeMuonEvents.cpp.
References BaseModule::dir, fAlgorithm, fOptions, and modules::options::GetString().
                                                  :
  BaseModule("MakeMuonEvents",opts,false),fOptions(opts){
      if(fOptions){
          fAlgorithm=fOptions->GetString("algorithm","FixedWindow");
      }
  dir->cd("/");
}
MakeMuonEvents::~MakeMuonEvents ()
Definition at line 31 of file MakeMuonEvents.cpp.
{
}
Member Function Documentation
virtual int MakeMuonEvents::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [inline, private, virtual]
Optional method which is called once after the main event loop Can be used to dump a summary or finalise a histogram
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 20 of file MakeMuonEvents.h.
{return 0;};
int MakeMuonEvents::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Optional method which is called once before the main event loop Can be used to parse options and setup histograms.
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 34 of file MakeMuonEvents.cpp.
References TemplateFactory< BaseModule, OptionsType >::createModule(), fAlgorithm, fGenerator, fOptions, and TMEGeneratorFactory::Instance().
{
    if(fAlgorithm.empty()) return 1;
    fGenerator=TMEGeneratorFactory::Instance()->createModule(
            fAlgorithm,new TMEGeneratorOptions(fAlgorithm,fOptions));
    if(!fGenerator) return 2;
    return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int MakeMuonEvents::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
The big kahuna. Overload this in the derived class and it will be called for each event.
Parameters:
gData Pointer to current map of all TPIs [ WILL CHANGE SHORTLY ]
gSetup Pointer to TSetupData for this run [ WILL CHANGE SHORTLY ]
Returns:
0 on success and non-zero on failure
Implements BaseModule.
Definition at line 42 of file MakeMuonEvents.cpp.
References fGenerator, gDetectorPulseMap, gMuonEvents, and TVMuonEventGenerator::ProcessPulses().
{
  //gMuonEvents.clear();
  int retVal=fGenerator->ProcessPulses(gMuonEvents,gDetectorPulseMap);
  return retVal;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
std::string MakeMuonEvents::fAlgorithm [private]
Definition at line 23 of file MakeMuonEvents.h.
Referenced by BeforeFirstEntry(), and MakeMuonEvents().
TVMuonEventGenerator* MakeMuonEvents::fGenerator [private]
Definition at line 24 of file MakeMuonEvents.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
modules::options* MakeMuonEvents::fOptions [private]
Definition at line 25 of file MakeMuonEvents.h.
Referenced by BeforeFirstEntry(), and MakeMuonEvents().
The documentation for this class was generated from the following files:
rootana/src/TME_generators/MakeMuonEvents.h
rootana/src/TME_generators/MakeMuonEvents.cpp