AlcapDAQ: G__Sizep2memfuncfileBjq1zj Class Reference
G__Sizep2memfuncfileBjq1zj Class Reference
Public Member Functions
G__Sizep2memfuncfileBjq1zj ()
size_t sizep2memfunc ()
Private Attributes
size_t(G__Sizep2memfuncfileBjq1zj::* p)()
Detailed Description
Definition at line 110 of file fileBjq1zj.cxx.
Constructor & Destructor Documentation
G__Sizep2memfuncfileBjq1zj::G__Sizep2memfuncfileBjq1zj () [inline]
Definition at line 112 of file fileBjq1zj.cxx.
References p, and sizep2memfunc().
{p=&G__Sizep2memfuncfileBjq1zj::sizep2memfunc;}
Member Function Documentation
size_t G__Sizep2memfuncfileBjq1zj::sizep2memfunc () [inline]
Definition at line 113 of file fileBjq1zj.cxx.
References p.
Referenced by G__get_sizep2memfuncfileBjq1zj(), and G__Sizep2memfuncfileBjq1zj().
{ return(sizeof(p)); }
Field Documentation
size_t(G__Sizep2memfuncfileBjq1zj::* G__Sizep2memfuncfileBjq1zj::p)() [private]
Referenced by G__Sizep2memfuncfileBjq1zj(), and sizep2memfunc().
The documentation for this class was generated from the following file:
www/html/online/wfd/fileBjq1zj.cxx