AlcapDAQ: PlotTPI_PedestalAndNoise Class Reference
PlotTPI_PedestalAndNoise Class Reference
[Modules]
Plots the pedestal and noise of each TPulseIsland and writes these to an SQLite database.
#include <PlotTPI_PedestalAndNoise.h>
Public Member Functions
PlotTPI_PedestalAndNoise (modules::options *opts)
The constructor.
~PlotTPI_PedestalAndNoise ()
Empty destructor.
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
In every event, we loop over all the detectors and all the TPulseIslands and calculate the RMS and mean of the first fNSamples samples in the digitised pulse (i.e. the noise and the pedestal respectively).
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
Nothing is done before each run.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
After each run, we write the mean and RMS of the first fNSamples to an SQLite database via SetupNavigator.
Private Attributes
std::map< std::string, TH2D * > fPedestalVsNoiseHistograms
The map that we store the pedestal vs. noise histograms for each channel.
const int fNSamples
The number of samples we will look at in the TPulseIsland to calculate the mean and RMS (opt = "n_samples").
const bool fExportSQL
A bool to decide whether we export the pedestal and noise to the SQLite database (opt = "export_sql", default = false).
Detailed Description
Plots the pedestal and noise of each TPulseIsland and writes these to an SQLite database.
Author:
Andrew Edmonds
This module loops over TPulseIsland and plots the mean and RMS of the first n_samples into a 2D histogram. At the end of the run, it writes the mean values of each axis to an SQLite database along with the channel and bank names. This SQLite database can then be used by PulseCandidateFinder to set parameter values based on a certain number of sigma.
Definition at line 25 of file PlotTPI_PedestalAndNoise.h.
Constructor & Destructor Documentation
PlotTPI_PedestalAndNoise::PlotTPI_PedestalAndNoise (modules::options * opts)
The constructor.
The constructor looks in the opts for "n_samples" and sets the fNSamples variable (default = 5).
Parameters:
[in] opts Describe the options this module takes.
Definition at line 22 of file PlotTPI_PedestalAndNoise.cpp.
                                                                      :
  BaseModule("PlotTPI_PedestalAndNoise",opts),
  fNSamples(opts->GetInt("n_samples")),
  fExportSQL(opts->GetBool("export_sql", false)) {
}
PlotTPI_PedestalAndNoise::~PlotTPI_PedestalAndNoise ()
Empty destructor.
Definition at line 28 of file PlotTPI_PedestalAndNoise.cpp.
{
}
Member Function Documentation
int PlotTPI_PedestalAndNoise::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
After each run, we write the mean and RMS of the first fNSamples to an SQLite database via SetupNavigator.
Parameters:
[in] gData See BaseModule::AfterLastEntry
[in] setup See BaseModule::AfterLastEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 118 of file PlotTPI_PedestalAndNoise.cpp.
References BaseModule::Debug(), fExportSQL, fPedestalVsNoiseHistograms, SetupNavigator::Instance(), and SetupNavigator::SetPedestalAndNoise().
{
  // Print extra info if we're debugging this module:
  if(Debug()){
     cout<<"-----PlotTPI_PedestalAndNoise::AfterLastEntry(): I'm debugging!"<<endl;
  }
  if (fExportSQL) {
    // Now loop through the histograms and record the channel, mean and RMS of first fNSamples
    for (std::map<std::string, TH2D*>::iterator histIter = fPedestalVsNoiseHistograms.begin(); histIter != fPedestalVsNoiseHistograms.end(); ++histIter) {
      std::string detname = histIter->first;
      IDs::channel channel(detname);
      TH2D* pedestal_vs_noise_histogram = histIter->second;
      double pedestal = pedestal_vs_noise_histogram->GetMean(1);
      double noise = pedestal_vs_noise_histogram->GetMean(2);
      SetupNavigator::Instance()->SetPedestalAndNoise(channel, pedestal, noise);
    }
  }
  return 0;
}
int PlotTPI_PedestalAndNoise::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Nothing is done before each run.
Parameters:
[in] gData See BaseModule::BeforeFirstEntry
[in] setup See BaseModule::BeforeFirstEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 34 of file PlotTPI_PedestalAndNoise.cpp.
References BaseModule::Debug().
{
  // Print extra info if we're debugging this module:
  if(Debug()){
     cout<<"-----PlotTPI_PedestalAndNoise::BeforeFirstEntry(): I'm debugging!"<<endl;
  }
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int PlotTPI_PedestalAndNoise::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
In every event, we loop over all the detectors and all the TPulseIslands and calculate the RMS and mean of the first fNSamples samples in the digitised pulse (i.e. the noise and the pedestal respectively).
Parameters:
[in] gData See BaseModule::ProcessEntry
[in] gSetup See BaseModule::ProcessEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 45 of file PlotTPI_PedestalAndNoise.cpp.
References fNSamples, fPedestalVsNoiseHistograms, TGlobalData::fPulseIslandToChannelMap, TSetupData::GetDetectorName(), TSetupData::GetNBits(), and TSetupData::Instance().
{
  // Prepare a few variables
  std::string bankname, detname;
  PulseIslandList thePulseIslands;
  StringPulseIslandMap::const_iterator it;
  // Loop over each detector
  for(it = gData->fPulseIslandToChannelMap.begin(); it != gData->fPulseIslandToChannelMap.end(); ++it){
    // Get the bank and detector names for this detector
    bankname = it->first;
    detname = setup->GetDetectorName(bankname);
    // Get the TPIs
    thePulseIslands = it->second;
    if (thePulseIslands.size() == 0) continue; // no pulses here..
    // Create the histogram that will store all the average RMS noises from each event
    if (fPedestalVsNoiseHistograms.find(detname) == fPedestalVsNoiseHistograms.end()) {
      int n_bits = TSetupData::Instance()->GetNBits(bankname);
      int x_min = 0;
      int x_max = std::pow(2, n_bits);
      int n_bins_x = 100;
      int y_min = 0;
      int y_max = 200;
      int n_bins_y = (y_max - y_min)*5;
      std::string histname = "fPedestalVsNoiseHistogram_" + detname;
      std::stringstream histtitle;
      histtitle << "Plot of the Pedestal vs Noise (mean and RMS of first " << fNSamples << " samples) in " << detname;
      TH2D* histogram = new TH2D(histname.c_str(), histtitle.str().c_str(), n_bins_x,x_min,x_max, n_bins_y,y_min,y_max);
      histogram->GetXaxis()->SetTitle("Pedestal [ADC]");
      histogram->GetYaxis()->SetTitle("Noise [ADC]");
      fPedestalVsNoiseHistograms[detname] = histogram;
    }
    TH2D* pedestal_vs_noise_histogram = fPedestalVsNoiseHistograms[detname];
    // Loop through all the pulses
    for (PulseIslandList::iterator pulseIter = thePulseIslands.begin(); pulseIter != thePulseIslands.end(); ++pulseIter) {
      const std::vector<int>& theSamples = (*pulseIter)->GetSamples();
      int limit=fNSamples;
      if((int)theSamples.size() < fNSamples) limit=theSamples.size();
      double sum = 0;
      for (int iSample = 0; iSample < limit; ++iSample) {
          sum += theSamples.at(iSample);
      }
      double mean = sum / limit;
      double sum_of_deviations_squared = 0;
      for (int iSample = 0; iSample < limit; ++iSample) {
          sum_of_deviations_squared += (theSamples.at(iSample) - mean)*(theSamples.at(iSample) - mean);
      }
      double stdev = std::sqrt(sum_of_deviations_squared / limit);
      pedestal_vs_noise_histogram->Fill(mean, stdev);
    } // end loop through pulses
  } // end loop through detectors
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
const bool PlotTPI_PedestalAndNoise::fExportSQL [private]
A bool to decide whether we export the pedestal and noise to the SQLite database (opt = "export_sql", default = false).
Definition at line 80 of file PlotTPI_PedestalAndNoise.h.
Referenced by AfterLastEntry().
const int PlotTPI_PedestalAndNoise::fNSamples [private]
The number of samples we will look at in the TPulseIsland to calculate the mean and RMS (opt = "n_samples").
Definition at line 75 of file PlotTPI_PedestalAndNoise.h.
Referenced by ProcessEntry().
std::map<std::string, TH2D*> PlotTPI_PedestalAndNoise::fPedestalVsNoiseHistograms [private]
The map that we store the pedestal vs. noise histograms for each channel.
Definition at line 70 of file PlotTPI_PedestalAndNoise.h.
Referenced by AfterLastEntry(), and ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/plotters/PlotTPI_PedestalAndNoise.h
rootana/src/plotters/PlotTPI_PedestalAndNoise.cpp