AlcapDAQ: TAPGeneratorFactory Class Reference
TAPGeneratorFactory Class Reference
#include <TAPGeneratorFactory.h>
Public Types
typedef
TVAnalysedPulseGenerator *(* ModuleMaker)(TAPGeneratorOptions *)
typedef std::vector< std::string > ArgumentsVector
Public Member Functions
std::string GetTAPType (const IDs::source &s)
std::string GetTAPType (const IDs::generator &g)
void registerModule (const std::string &, ModuleMaker, const std::string &out="")
Add a ModuleMaker function to the list of makers.
virtual TVAnalysedPulseGenerator * createModule (const std::string &, TAPGeneratorOptions *opts=NULL)
Create a module with options.
bool canCreate (const std::string &name) const
Check if a module with this name has been registered.
void addOptions (const std::string &name, TAPGeneratorOptions *opts)
void addArguments (const std::string &all_args)
void addArgument (const std::string &module, const std::string &argument)
void addArgument (const std::string &argument)
std::string GetArgumentName (const std::string &module, const int &argument)
std::string GetProduct (const std::string &module)
void SetDebug (bool debug=true)
void PrintPossibleModules () const
Static Public Member Functions
static TAPGeneratorFactory * Instance ()
Private Member Functions
TAPGeneratorFactory ()
~TAPGeneratorFactory ()
Detailed Description
Definition at line 10 of file TAPGeneratorFactory.h.
Member Typedef Documentation
typedef std::vector<std::string> TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::ArgumentsVector [inherited]
Definition at line 18 of file TemplateFactory.h.
typedef TVAnalysedPulseGenerator *(* TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::ModuleMaker)(TAPGeneratorOptions *) [inherited]
Definition at line 17 of file TemplateFactory.h.
Constructor & Destructor Documentation
TAPGeneratorFactory::TAPGeneratorFactory () [inline, private]
Definition at line 12 of file TAPGeneratorFactory.h.
Referenced by Instance().
                                     :
                        TemplateFactory<TVAnalysedPulseGenerator,TAPGeneratorOptions>("TAPGeneratorFactory"){};
                ~TAPGeneratorFactory(){};
TAPGeneratorFactory::~TAPGeneratorFactory () [inline, private]
Definition at line 14 of file TAPGeneratorFactory.h.
{};
Member Function Documentation
void TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::addArgument (const std::string & argument) [inherited]
void TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::addArgument (const std::string & module, const std::string & argument) [inherited]
void TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::addArguments (const std::string & all_args) [inherited]
void TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::addOptions (const std::string & name, TAPGeneratorOptions * opts) [inherited]
bool TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::canCreate (const std::string & name) const [inline, inherited]
Check if a module with this name has been registered.
Definition at line 44 of file TemplateFactory.h.
{return (bool) fModules.count(name);};
virtual TVAnalysedPulseGenerator * TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::createModule (const std::string & , TAPGeneratorOptions * opts = NULL) [virtual, inherited]
Create a module with options.
std::string TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::GetArgumentName (const std::string & module, const int & argument) [inherited]
std::string TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::GetProduct (const std::string & module) [inherited]
Referenced by GetTAPType().
std::string TAPGeneratorFactory::GetTAPType (const IDs::generator & g) [inline]
Definition at line 22 of file TAPGeneratorFactory.h.
References TemplateFactory< TVAnalysedPulseGenerator, TAPGeneratorOptions >::GetProduct(), and IDs::generator::Type().
{
            std::string gen=g.Type();
            size_t n_subtract=gen.find("APGenerator");
            if(n_subtract!=std::string::npos)
               gen.erase(n_subtract); //remove APGenerator part
            return GetProduct(gen);
        }
std::string TAPGeneratorFactory::GetTAPType (const IDs::source & s) [inline]
Definition at line 18 of file TAPGeneratorFactory.h.
References IDs::source::Generator().
Referenced by SavePulses::BeforeFirstEntry().
{
            return GetTAPType(s.Generator());
        }
TAPGeneratorFactory * TAPGeneratorFactory::Instance () [inline, static]
Definition at line 34 of file TAPGeneratorFactory.h.
References TAPGeneratorFactory().
Referenced by TAPGeneratorOptions::AddArgument(), MakeAnalysedPulses::AddGenerator(), and SavePulses::BeforeFirstEntry().
{
    static TAPGeneratorFactory* instance=NULL;
    if(!instance) {
        instance=new TAPGeneratorFactory();
    }
    return instance;
}
void TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::PrintPossibleModules () const [inherited]
void TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::registerModule (const std::string & , ModuleMaker , const std::string & out = "") [inherited]
Add a ModuleMaker function to the list of makers.
void TemplateFactory< TVAnalysedPulseGenerator , TAPGeneratorOptions >::SetDebug (bool debug = true) [inline, inherited]
Definition at line 53 of file TemplateFactory.h.
{fDebug=debug;};
The documentation for this class was generated from the following file:
rootana/src/TAP_generators/TAPGeneratorFactory.h