AlcapDAQ: FlyWeight< ValueType, UniqueTag > Class Template Reference
FlyWeight< ValueType, UniqueTag > Class Template Reference
#include <FlyWeight.h>
Public Types
typedef int Proxy_t
Public Member Functions
FlyWeight ()
FlyWeight (const ValueType &val)
void Reset ()
void operator= (const ValueType &v)
void DumpTable () const
Static Public Member Functions
static void InitProxyList ()
Private Member Functions
ClassDef (FlyWeight, 2)
Private Attributes
Proxy_t fProxy
FlyWeight
A generic flyweight to store relatively bulky objects that are massively re-used, such as the source IDs in each TAP / TDP.
Objects such as TAPs and TDPs often contain largely repeated data such as the source ID for all pulses coming from the same algorithm applied to the same detector channel. To reduce the redundancy and therefore save memory and some processing time, this class implements a simple version of the flyweight pattern, which replaces each different value with an int, but provides a similar interface to the object that it wraps. When we want to store a new value, it is searched for in the ProxyToValueMap and the index identifying where it is is saved is used instead. If the value has not been used already, it is added to the list of values
Template Parameters:
ValueType The type of value this flyweight contains
UniqueTag An optional template parameter to make sure the flyweight is unique, such as to separate the flyweight for TAPs from TDPs, even though the ValueType is the same
static FlyWeightLists
< ValueType, UniqueTag > * fProxyList = NULL
void SetValue (const ValueType &)
const ValueType & GetValue () const
static int LoadProxyList (TDirectory *file, const std::string &name)
static int SaveProxyList (TDirectory *file, const std::string &name)
Detailed Description
template<typename ValueType, typename UniqueTag = int>
class FlyWeight< ValueType, UniqueTag >
Definition at line 55 of file FlyWeight.h.
Member Typedef Documentation
template<typename ValueType, typename UniqueTag = int> typedef int FlyWeight< ValueType, UniqueTag >::Proxy_t
Definition at line 57 of file FlyWeight.h.
Constructor & Destructor Documentation
template<typename ValueType, typename UniqueTag = int> FlyWeight< ValueType, UniqueTag >::FlyWeight () [inline]
Definition at line 59 of file FlyWeight.h.
:fProxy(-1){}
template<typename ValueType, typename UniqueTag = int> FlyWeight< ValueType, UniqueTag >::FlyWeight (const ValueType & val) [inline]
Definition at line 60 of file FlyWeight.h.
                                       :fProxy(-1){
            SetValue(val);
        }
Member Function Documentation
template<typename ValueType, typename UniqueTag = int> FlyWeight< ValueType, UniqueTag >::ClassDef (FlyWeight< ValueType, UniqueTag > , 2) [private]
template<typename ValueType, typename UniqueTag = int> void FlyWeight< ValueType, UniqueTag >::DumpTable () const [inline]
Definition at line 70 of file FlyWeight.h.
{fProxyList->DumpTable();}
template<typename ValueType , typename UniqueTag > const ValueType & FlyWeight< ValueType, UniqueTag >::GetValue () const [inline]
Definition at line 85 of file FlyWeight.h.
References FlyWeight< ValueType, UniqueTag >::fProxy, and FlyWeight< ValueType, UniqueTag >::fProxyList.
Referenced by TDetectorPulse::GetSource(), and TAnalysedPulse::GetSource().
{
    if(fProxy<0) std::cerr<<"Trying to get a value "
        "from an unitialized flyweight"<<std::endl;
    return fProxyList->GetValue(fProxy);
}
template<typename ValueType, typename UniqueTag = int> static void FlyWeight< ValueType, UniqueTag >::InitProxyList () [inline, static]
Definition at line 74 of file FlyWeight.h.
Referenced by FlyWeight< ValueType, UniqueTag >::SetValue().
{fProxyList=new FlyWeightLists<ValueType,UniqueTag>();};
template<typename ValueType , typename UniqueTag > int FlyWeight< ValueType, UniqueTag >::LoadProxyList (TDirectory * file, const std::string & name) [inline, static]
Definition at line 98 of file FlyWeight.h.
References FlyWeight< ValueType, UniqueTag >::fProxyList.
{
    if(fProxyList && !fProxyList->empty()){
        std::cout<<"FlyWeight: Error: Proxy list is not empty but was asked to load the list from a file"<<std::endl;
        return 1;
    }
    if(!file) {
        std::cout<<"FlyWeight: Error: Cannot load a proxy list from a NULL file"<<std::endl;
        return 2;
    }
    file->GetObject(name.c_str(),fProxyList);
    if(!fProxyList){
        std::cout<<"FlyWeight: Error: Couldn't find proxy list '"<<name
            <<"' in file '"<<file->GetName()<<"'"<<std::endl;
        return 3;
    }
    return 0;
}
template<typename ValueType, typename UniqueTag = int> void FlyWeight< ValueType, UniqueTag >::operator= (const ValueType & v) [inline]
Definition at line 65 of file FlyWeight.h.
{
            SetValue(v);
        }
template<typename ValueType, typename UniqueTag = int> void FlyWeight< ValueType, UniqueTag >::Reset () [inline]
Definition at line 63 of file FlyWeight.h.
Referenced by TDetectorPulse::Reset().
{fProxy=-1;}
template<typename ValueType , typename UniqueTag > int FlyWeight< ValueType, UniqueTag >::SaveProxyList (TDirectory * file, const std::string & name) [inline, static]
Definition at line 118 of file FlyWeight.h.
References FlyWeight< ValueType, UniqueTag >::fProxyList.
{
    if(!file) {
        std::cout<<"FlyWeight: Error: Cannot save a proxy list from a NULL file"<<std::endl;
        return 1;
    }
    file->WriteObject(fProxyList,name.c_str());
    return 0;
}
template<typename ValueType, typename UniqueTag > void FlyWeight< ValueType, UniqueTag >::SetValue (const ValueType & v) [inline]
Definition at line 92 of file FlyWeight.h.
References FlyWeight< ValueType, UniqueTag >::fProxy, FlyWeight< ValueType, UniqueTag >::fProxyList, and FlyWeight< ValueType, UniqueTag >::InitProxyList().
Referenced by FlyWeight< IDs::source, TAnalysedPulse::Tag >::FlyWeight(), and FlyWeight< IDs::source, TAnalysedPulse::Tag >::operator=().
{
    if(!fProxyList)InitProxyList();
    fProxy=fProxyList->GetProxy(v);
}
Member Data Documentation
template<typename ValueType, typename UniqueTag = int> Proxy_t FlyWeight< ValueType, UniqueTag >::fProxy [private]
Definition at line 74 of file FlyWeight.h.
Referenced by FlyWeight< ValueType, UniqueTag >::GetValue(), FlyWeight< IDs::source, TAnalysedPulse::Tag >::Reset(), and FlyWeight< ValueType, UniqueTag >::SetValue().
template<typename ValueType, typename UniqueTag = int> FlyWeightLists< ValueType, UniqueTag > * FlyWeight< ValueType, UniqueTag >::fProxyList = NULL [inline, static, private]
Definition at line 79 of file FlyWeight.h.
Referenced by FlyWeight< IDs::source, TAnalysedPulse::Tag >::DumpTable(), FlyWeight< ValueType, UniqueTag >::GetValue(), FlyWeight< IDs::source, TAnalysedPulse::Tag >::InitProxyList(), FlyWeight< ValueType, UniqueTag >::LoadProxyList(), FlyWeight< ValueType, UniqueTag >::SaveProxyList(), and FlyWeight< ValueType, UniqueTag >::SetValue().
The documentation for this class was generated from the following file:
rootana/src/framework/FlyWeight.h