AlcapDAQ: TemplateFitAPGenerator Class Reference
TemplateFitAPGenerator Class Reference
#include <TemplateFitAPGenerator.h>
Public Member Functions
TemplateFitAPGenerator (TAPGeneratorOptions *opts)
virtual ~TemplateFitAPGenerator ()
virtual int ProcessPulses (const PulseIslandList &, AnalysedPulseList &)
This method is called on each vector of pulses from a MIDAS event.
virtual bool MayDivideTPIs ()
void SetPulseList (PulseIslandList *list)
template<typename TypeOfTAP >
TypeOfTAP * MakeNewTAP (int parent_index) const
The suggested method for constructing a new TAP.
TAnalysedPulse * MakeNewTAP (int parent_index) const
bool Debug () const
IDs::channel GetChannel () const
std::string GetBank () const
const IDs::source & GetSource () const
Get the source id for this generator being used on the current channel.
virtual void CalibratePulses (AnalysedPulseList &theAnalysedPulses) const
Static Public Member Functions
static const char * TapType ()
Protected Member Functions
virtual void SetChannel (const std::string &det)
Set the channel for this generator. Should NOT be called by user code.
Private Member Functions
bool PassesIntegralRatio (const TPulseIsland *pulse, double &integral, double &ratio) const
bool RefitWithTwo (TH1D *tpi, TTemplateFitAnalysedPulse *&tap_one, TTemplateFitAnalysedPulse *&tap_two) const
void InitializeSecondPulse (TH1D *tpi, const TTemplateFitAnalysedPulse *tap_one, int &second_time, double &second_scale) const
Private Attributes
double fIntegralMax
double fIntegralMin
double fIntegralRatioMax
double fIntegralRatioMin
double fTemplateAmp
double fTemplatePed
double fTemplateTime
double fTemplate2Amp
double fTemplate2Ped
double fTemplate2Time
double fInitPedestal
double fChi2MinToRefit
TTemplate * fTemplate
TTemplate * fTemplate2
TemplateMultiFitter * fFitter
TemplateMultiFitter * fDoubleFitter
Algorithm::IntegralRatio * fIntegralRatio
Algorithm::MaxBinAmplitude fMaxBin
Static Private Attributes
static TemplateArchive * fTemplateArchive = NULL
static TemplateArchive * fTemplateArchive2 = NULL
Friends
class MakeAnalysedPulses
Detailed Description
Definition at line 14 of file TemplateFitAPGenerator.h.
Constructor & Destructor Documentation
TemplateFitAPGenerator::TemplateFitAPGenerator (TAPGeneratorOptions * opts)
Definition at line 16 of file TemplateFitAPGenerator.cpp.
References TemplateMultiFitter::AddTemplate(), fChi2MinToRefit, fDoubleFitter, fFitter, fIntegralMax, fIntegralMin, fIntegralRatio, fIntegralRatioMax, fIntegralRatioMin, fTemplate, fTemplate2, fTemplate2Amp, fTemplate2Ped, fTemplate2Time, fTemplateAmp, fTemplateArchive, fTemplateArchive2, fTemplatePed, fTemplateTime, TTemplate::GetAmplitude(), TVAnalysedPulseGenerator::GetChannel(), modules::options::GetDouble(), modules::options::GetFlag(), modules::options::GetInt(), TemplateArchive::GetName(), TTemplate::GetPedestal(), SetupRecord::GetPolarity(), EventNavigator::GetSetupRecord(), modules::options::GetString(), TemplateArchive::GetTemplate(), TTemplate::GetTime(), modules::options::HasOption(), TemplateMultiFitter::Init(), and EventNavigator::Instance().
                                                                       :
   TVAnalysedPulseGenerator("TemplateFitAPGenerator",opts),
    fInitPedestal(EventNavigator::Instance().GetSetupRecord().GetPedestal(GetChannel())),
    fTemplate2(NULL),
    fIntegralRatio(NULL),
    fMaxBin(fInitPedestal, EventNavigator::Instance().GetSetupRecord().GetPolarity(GetChannel()))
{
   // get the templates from the archive
   if(!fTemplateArchive){
     fTemplateArchive=new TemplateArchive(opts->GetString("template_archive").c_str(),"READ");
   }
   if(opts->HasOption("template_archive_2")){
     std::string template_2_src=opts->GetString("template_archive_2");
     if (template_2_src!=fTemplateArchive->GetName() && !fTemplateArchive2)
        fTemplateArchive2=new TemplateArchive(opts->GetString("template_archive_2").c_str(),"READ");
     else if(!fTemplateArchive2){
        fTemplateArchive2=fTemplateArchive;
     }
   }
   fTemplate=fTemplateArchive->GetTemplate(GetChannel());
   if(fTemplateArchive2) fTemplate2=fTemplateArchive2->GetTemplate(GetChannel());
   // make the fitters
   fFitter = new TemplateMultiFitter(GetChannel().str());
   fFitter->AddTemplate(fTemplate);
   fFitter->Init();
   if(fTemplate2){
     fDoubleFitter = new TemplateMultiFitter(GetChannel().str());
     fDoubleFitter->AddTemplate(fTemplate);
     fDoubleFitter->AddTemplate(fTemplate2);
     fDoubleFitter->Init();
   }
   // prepare the integral ratio cuts
   if(opts->GetFlag("use_IR_cut")){
      fIntegralRatio=new Algorithm::IntegralRatio(
                      opts->GetInt("start_integral",10),
                      opts->GetInt("start_tail",60),
                      opts->GetInt("stop_integral",0),
                      EventNavigator::Instance().GetSetupRecord().GetPolarity(GetChannel()));
      fIntegralMax=opts->GetDouble("max_integral");
      fIntegralMin=opts->GetDouble("min_integral");
      fIntegralRatioMax=opts->GetDouble("max_ratio");
      fIntegralRatioMin=opts->GetDouble("min_ratio");
  }
  // cache the template parameters so we dont need to look them up
  fTemplateAmp=fTemplate->GetAmplitude();
  fTemplateTime=fTemplate->GetTime();
  fTemplatePed=fTemplate->GetPedestal();
  if(fTemplate2){
     fTemplate2Amp=fTemplate2->GetAmplitude();
     fTemplate2Time=fTemplate2->GetTime();
     fTemplate2Ped=fTemplate2->GetPedestal();
  }
  // chi2 to determine when we refit with 2 pulses
  fChi2MinToRefit=opts->GetDouble("min_chi2_to_refit",2e5);
}
TemplateFitAPGenerator::~TemplateFitAPGenerator () [virtual]
Definition at line 77 of file TemplateFitAPGenerator.cpp.
References fDoubleFitter, fFitter, fIntegralRatio, fTemplateArchive, and fTemplateArchive2.
{
  delete fFitter;
  delete fDoubleFitter;
  if(fIntegralRatio) delete fIntegralRatio;
  if(fTemplateArchive) {
    delete fTemplateArchive;
    fTemplateArchive=NULL;
  }
  if(fTemplateArchive2) {
    delete fTemplateArchive2;
    fTemplateArchive2=NULL;
  }
}
Member Function Documentation
void TVAnalysedPulseGenerator::CalibratePulses (AnalysedPulseList & theAnalysedPulses) const [virtual, inherited]
Definition at line 23 of file TVAnalysedPulseGenerator.cpp.
References TVAnalysedPulseGenerator::fAdcToEnergyGain, TVAnalysedPulseGenerator::fAdcToEnergyOffset, and TVAnalysedPulseGenerator::fCanCalibrate.
{
   if(fCanCalibrate){
      for(AnalysedPulseList::iterator i_tap=theAnalysedPulses.begin(); i_tap != theAnalysedPulses.end(); ++i_tap){
         const double amplitude=(*i_tap)->GetAmplitude();
         (*i_tap)->SetEnergy(fAdcToEnergyGain * amplitude + fAdcToEnergyOffset);
      }
   }
}
bool TVAnalysedPulseGenerator::Debug () const [inline, inherited]
Definition at line 77 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fDebug.
Referenced by GaussFitAPGenerator::FitPulse(), TemplateConvolveAPGenerator::ProcessPulses(), and IntegralRatioAPGenerator::ProcessPulses().
{return fDebug;};
std::string TVAnalysedPulseGenerator::GetBank () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 85 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fBankName.
{return fBankName;};
IDs::channel TVAnalysedPulseGenerator::GetChannel () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 81 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), and TVAnalysedPulseGenerator::fSource.
Referenced by FirstCompleteAPGenerator::DrawPulse(), FirstCompleteAPGenerator::FirstCompleteAPGenerator(), IntegralRatioAPGenerator::ProcessPulses(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateFitAPGenerator(), and TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{return fSource.Channel();};
const IDs::source& TVAnalysedPulseGenerator::GetSource () const [inline, inherited]
Get the source id for this generator being used on the current channel.
Useful for a generator to know the full source much like in the above GetChannel method, but this could also be useful for checking that this generator is the one that made a given TAP in later analysis by comparing this value to that stored in the TAP itself.
Definition at line 94 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fSource.
Referenced by TVAnalysedPulseGenerator::MakeNewTAP(), and IntegralRatioAPGenerator::ProcessPulses().
{return fSource;};
void TemplateFitAPGenerator::InitializeSecondPulse (TH1D * tpi, const TTemplateFitAnalysedPulse * tap_one, int & second_time, double & second_scale) const [private]
Definition at line 220 of file TemplateFitAPGenerator.cpp.
References fTemplate, fTemplate2, TTemplate::GetAmplitude(), TTemplateFitAnalysedPulse::GetBinContent(), TTemplate::GetHisto(), TTemplate::GetTime(), and TAnalysedPulse::GetTime().
Referenced by RefitWithTwo().
{
    // scan from the time of the first tap and find the bin with the largest residual (within some window)
    int limit = tpi->GetNbinsX();
    int template_limit=tap_one->GetTime() - fTemplate->GetTime() + fTemplate->GetHisto()->GetNbinsX()-10;
    if(template_limit <  limit ) limit= template_limit;
    double residual, max_residual=-1e6;
    int max_bin=0;
    for( int bin=tap_one->GetTime(); bin < limit; ++bin){
      residual=tpi->GetBinContent(bin) - tap_one->GetBinContent(bin);
      if(residual>max_residual){
        max_residual=residual;
        max_bin=bin;
      }
    }
    second_time=max_bin - fTemplate2->GetTime();
    second_scale=max_residual / fTemplate2->GetAmplitude();
}
TAnalysedPulse* TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
Definition at line 73 of file TVAnalysedPulseGenerator.h.
{
            return MakeNewTAP<TAnalysedPulse>(parent_index);
        }
template<typename TypeOfTAP > TypeOfTAP * TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
The suggested method for constructing a new TAP.
In the process of constructing TAP, information that isn't immediately obvious how to get needs to be passed to TAP. This method returns a pointer to a TAP construced for you, and all you need to pass it is the TPulseIslandID.
In the case where a generator wants to add extra information to the standard TAP information, we expect people to derive from TAnalysedPulse. If your generator is one of these, then use the template argument to produce the type of TAP you desire. Note that this forces the constructor of the specialised TAP to be the same as for TAnalysedPulse itself.
For example, for to make a specialied analysed pulse called TSpecialAnalysedPulse (original, huh?) you would do:
 TSpecialAnalysedPulse* tsap=MakeNewTAP<TSpecialAnalysedPulse>(parent_index);
Parameters:
[in] parent_index The TPulseIslandID of the TPI being used to make the new TAP.
Template Parameters:
in] TypeOfTAP The type of specialisation of TAnalysedPulse that you want to create.
Definition at line 137 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList, and TVAnalysedPulseGenerator::GetSource().
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), SimpIntAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), CFTimeMBAmpAPGenerator::ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{
    TypeOfTAP* pulse=NULL;
    TPulseIsland* parent = fPulseList->at(parent_index);
    pulse=new TypeOfTAP(GetSource(),parent_index,parent);
    return pulse;
}
virtual bool TemplateFitAPGenerator::MayDivideTPIs () [inline, virtual]
Todo:
Document this
Implements TVAnalysedPulseGenerator.
Definition at line 25 of file TemplateFitAPGenerator.h.
{return true;};
bool TemplateFitAPGenerator::PassesIntegralRatio (const TPulseIsland * pulse, double & integral, double & ratio) const [private]
Definition at line 149 of file TemplateFitAPGenerator.cpp.
References fIntegralRatio, Algorithm::IntegralRatio::GetRatio(), Algorithm::IntegralRatio::GetTotal(), and Algorithm::IntegralRatio::SetPedestalToMinimum().
Referenced by ProcessPulses().
{
   if(!fIntegralRatio) return true;
   try{
     fIntegralRatio->SetPedestalToMinimum(pulse);
     (*fIntegralRatio)(pulse);
   }catch(std::out_of_range& e){
     return false;
   }
   integral=fIntegralRatio->GetTotal();
   ratio=fIntegralRatio->GetRatio();
   if( fIntegralMax < integral || fIntegralMin > integral
       || fIntegralRatioMax < ratio || fIntegralRatioMin > ratio) {
       return false;
   }
   return true;
}
int TemplateFitAPGenerator::ProcessPulses (const PulseIslandList & pil, AnalysedPulseList & apl) [virtual]
This method is called on each vector of pulses from a MIDAS event.
Parameters:
[in] pil The vector of TPIs to produce TAPs from.
[out] apl The vector of TAPs to append the new TAPs to.
Implements TVAnalysedPulseGenerator.
Definition at line 92 of file TemplateFitAPGenerator.cpp.
References fChi2MinToRefit, fFitter, fInitPedestal, fIntegralRatio, TemplateMultiFitter::FitWithOneTimeFree(), fMaxBin, fTemplate, fTemplate2, fTemplateAmp, fTemplateTime, TemplateMultiFitter::GetAmplitude(), TemplateMultiFitter::GetChi2(), TemplateMultiFitter::GetNDoF(), TemplateMultiFitter::GetPedestal(), TTemplate::GetRefineFactor(), TemplateMultiFitter::GetTime(), Algorithm::MaxBinAmplitude::GetTime(), functions::InterpolatePulse(), PassesIntegralRatio(), RefitWithTwo(), TTemplateFitAnalysedPulse::SetAmplitude(), TTemplateFitAnalysedPulse::SetChi2(), TTemplateFitAnalysedPulse::SetFitStatus(), TAnalysedPulse::SetIntegral(), TTemplateFitAnalysedPulse::SetIntegralRatio(), TTemplateFitAnalysedPulse::SetNDoF(), TTemplateFitAnalysedPulse::SetPedestal(), TemplateMultiFitter::SetPedestal(), TemplateMultiFitter::SetPulseEstimates(), TTemplateFitAnalysedPulse::SetTemplate(), and TTemplateFitAnalysedPulse::SetTime().
{
  // Loop over all the TPIs given to us
  TTemplateFitAnalysedPulse* tap;
  double integral, ratio;
  for (PulseIslandList::const_iterator tpi=pulseList.begin();
       tpi!=pulseList.end(); tpi++){
    if(fIntegralRatio && !PassesIntegralRatio(*tpi, integral,ratio)){
       continue;
    }
    double init_amp=fMaxBin(*tpi)/fTemplateAmp;
    double init_time=  fMaxBin.GetTime() * fTemplate->GetRefineFactor()- fTemplateTime ;
    fFitter->SetPedestal(fInitPedestal);
    fFitter->SetPulseEstimates(0, init_amp, init_time);
    // Make histo for TPI
    TH1D* hPulseToFit=InterpolatePulse(*tpi,"hPulseToFit","hPulseToFit",false,fTemplate->GetRefineFactor());
    int fit_status = fFitter->FitWithOneTimeFree(0, hPulseToFit);
    // Now that we've found the information we were looking for make a TAP to
    // hold it.  This method makes a TAP and sets the parent TPI info.  It needs
    // the index of the parent TPI in the container as an argument
    tap = MakeNewTAP<TTemplateFitAnalysedPulse>(tpi-pulseList.begin());
    tap->SetTemplate(fTemplate);
    tap->SetPedestal(fFitter->GetPedestal());
    tap->SetAmplitude(fFitter->GetAmplitude(0));
    tap->SetTime(-fFitter->GetTime(0));
    tap->SetChi2(fFitter->GetChi2());
    tap->SetNDoF(fFitter->GetNDoF());
    tap->SetFitStatus(fit_status);
    tap->SetIntegral(integral);
    tap->SetIntegralRatio(ratio);
    if(fTemplate2 && fFitter->GetChi2() > fChi2MinToRefit){
        TTemplateFitAnalysedPulse* second_tap=NULL;
        bool better_with_2 = RefitWithTwo(hPulseToFit, tap, second_tap);
        if(better_with_2){
           analysedList.push_back(tap);
           analysedList.push_back(second_tap);
        } else{
           analysedList.push_back(tap);
           if(second_tap) delete second_tap;
        }
    } else {
       analysedList.push_back(tap);
    }
   }
   // returning 0 tells the caller that we were successful, return non-zero if not
   return 0;
}
bool TemplateFitAPGenerator::RefitWithTwo (TH1D * tpi, TTemplateFitAnalysedPulse *& tap_one, TTemplateFitAnalysedPulse *& tap_two) const [private]
Definition at line 166 of file TemplateFitAPGenerator.cpp.
References fDoubleFitter, TemplateMultiFitter::FitWithAllTimesFixed(), TemplateMultiFitter::FitWithOneTimeFree(), fTemplate2, TemplateMultiFitter::GetAmplitude(), TAnalysedPulse::GetAmplitude(), TemplateMultiFitter::GetChi2(), TTemplateFitAnalysedPulse::GetChi2(), TemplateMultiFitter::GetNDoF(), TTemplateFitAnalysedPulse::GetNDoF(), TAnalysedPulse::GetParentID(), TemplateMultiFitter::GetPedestal(), TAnalysedPulse::GetPedestal(), TemplateMultiFitter::GetTime(), TAnalysedPulse::GetTime(), InitializeSecondPulse(), TTemplateFitAnalysedPulse::IsPileUpPulse(), TTemplateFitAnalysedPulse::SetAmplitude(), TTemplateFitAnalysedPulse::SetChi2(), TTemplateFitAnalysedPulse::SetFitStatus(), TTemplateFitAnalysedPulse::SetNDoF(), TTemplateFitAnalysedPulse::SetOtherPulse(), TTemplateFitAnalysedPulse::SetPedestal(), TemplateMultiFitter::SetPedestal(), TemplateMultiFitter::SetPulseEstimates(), TTemplateFitAnalysedPulse::SetTemplate(), and TTemplateFitAnalysedPulse::SetTime().
Referenced by ProcessPulses().
{
  // find the max bin after the current fitted tap
  int second_time=-9999999;
  double second_scale=-9999999;
  InitializeSecondPulse(tpi,tap_one,second_time,second_scale);
  // fit the second template around the second peak
  fDoubleFitter->SetPedestal(tap_one->GetPedestal());
  fDoubleFitter->SetPulseEstimates( 0, tap_one->GetAmplitude(), tap_one->GetTime());
  fDoubleFitter->SetPulseEstimates( 1, second_scale, second_time);
  int fit_status = fDoubleFitter->FitWithOneTimeFree(1, tpi);
  // fit the first pulse again
  fit_status = fDoubleFitter->FitWithOneTimeFree(0, tpi);
  // fit the second pulse again
  fit_status = fDoubleFitter->FitWithAllTimesFixed(tpi);
  if(fit_status==0){
    // Has the double fit improved the chi-2 per NDoF
    double old_chi2=tap_one->GetChi2()/tap_one->GetNDoF();
    double new_chi2=fDoubleFitter->GetChi2()/fDoubleFitter->GetNDoF();
    if( (old_chi2 - new_chi2) < 0){
      // refill tap_one's values
      tap_one->SetPedestal(fDoubleFitter->GetPedestal());
      tap_one->SetAmplitude(fDoubleFitter->GetAmplitude(0));
      tap_one->SetTime(fDoubleFitter->GetTime(0));
      tap_one->SetChi2(fDoubleFitter->GetChi2());
      tap_one->SetNDoF(fDoubleFitter->GetNDoF());
      tap_one->SetFitStatus(fit_status);
      // make the second tap
      tap_two = MakeNewTAP<TTemplateFitAnalysedPulse>(tap_one->GetParentID());
      tap_two->SetTemplate(fTemplate2);
      tap_two->SetPedestal(fDoubleFitter->GetPedestal());
      tap_two->SetAmplitude(fDoubleFitter->GetAmplitude(1));
      tap_two->SetTime(fDoubleFitter->GetTime(1));
      tap_two->SetChi2(fDoubleFitter->GetChi2());
      tap_two->SetNDoF(fDoubleFitter->GetNDoF());
      tap_two->SetFitStatus(fit_status);
      // link the two pulses together
      tap_one->SetOtherPulse(tap_two);
      tap_two->SetOtherPulse(tap_one);
      tap_two->IsPileUpPulse();
      return true;
    }
  }
  return false;
}
virtual void TVAnalysedPulseGenerator::SetChannel (const std::string & det) [inline, protected, virtual, inherited]
Set the channel for this generator. Should NOT be called by user code.
Called by MakeAnalysedPulses to tell this generator what channel it is looking at.
Definition at line 108 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), TVAnalysedPulseGenerator::fBankName, TVAnalysedPulseGenerator::fSource, SetupNavigator::GetBank(), and SetupNavigator::Instance().
Referenced by TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{
           fSource.Channel()=det;
           fBankName= SetupNavigator::Instance()->GetBank(det);
         };
void TVAnalysedPulseGenerator::SetPulseList (PulseIslandList * list) [inline, inherited]
Definition at line 44 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList.
{fPulseList=list;};
static const char* TemplateFitAPGenerator::TapType () [inline, static]
Reimplemented from TVAnalysedPulseGenerator.
Definition at line 28 of file TemplateFitAPGenerator.h.
{
        return TTemplateFitAnalysedPulse::Class()->GetName();
    }
Friends And Related Function Documentation
friend class MakeAnalysedPulses [friend, inherited]
Definition at line 101 of file TVAnalysedPulseGenerator.h.
Member Data Documentation
double TemplateFitAPGenerator::fChi2MinToRefit [private]
Definition at line 46 of file TemplateFitAPGenerator.h.
Referenced by ProcessPulses(), and TemplateFitAPGenerator().
TemplateMultiFitter* TemplateFitAPGenerator::fDoubleFitter [private]
Definition at line 50 of file TemplateFitAPGenerator.h.
Referenced by RefitWithTwo(), TemplateFitAPGenerator(), and ~TemplateFitAPGenerator().
TemplateMultiFitter* TemplateFitAPGenerator::fFitter [private]
Definition at line 49 of file TemplateFitAPGenerator.h.
Referenced by ProcessPulses(), TemplateFitAPGenerator(), and ~TemplateFitAPGenerator().
double TemplateFitAPGenerator::fInitPedestal [private]
Definition at line 45 of file TemplateFitAPGenerator.h.
Referenced by ProcessPulses().
double TemplateFitAPGenerator::fIntegralMax [private]
Definition at line 41 of file TemplateFitAPGenerator.h.
Referenced by TemplateFitAPGenerator().
double TemplateFitAPGenerator::fIntegralMin [private]
Definition at line 41 of file TemplateFitAPGenerator.h.
Referenced by TemplateFitAPGenerator().
Algorithm::IntegralRatio* TemplateFitAPGenerator::fIntegralRatio [private]
Definition at line 51 of file TemplateFitAPGenerator.h.
Referenced by PassesIntegralRatio(), ProcessPulses(), TemplateFitAPGenerator(), and ~TemplateFitAPGenerator().
double TemplateFitAPGenerator::fIntegralRatioMax [private]
Definition at line 42 of file TemplateFitAPGenerator.h.
Referenced by TemplateFitAPGenerator().
double TemplateFitAPGenerator::fIntegralRatioMin [private]
Definition at line 42 of file TemplateFitAPGenerator.h.
Referenced by TemplateFitAPGenerator().
Algorithm::MaxBinAmplitude TemplateFitAPGenerator::fMaxBin [private]
Definition at line 52 of file TemplateFitAPGenerator.h.
Referenced by ProcessPulses().
TTemplate* TemplateFitAPGenerator::fTemplate [private]
Definition at line 47 of file TemplateFitAPGenerator.h.
Referenced by InitializeSecondPulse(), ProcessPulses(), and TemplateFitAPGenerator().
TTemplate* TemplateFitAPGenerator::fTemplate2 [private]
Definition at line 48 of file TemplateFitAPGenerator.h.
Referenced by InitializeSecondPulse(), ProcessPulses(), RefitWithTwo(), and TemplateFitAPGenerator().
double TemplateFitAPGenerator::fTemplate2Amp [private]
Definition at line 44 of file TemplateFitAPGenerator.h.
Referenced by TemplateFitAPGenerator().
double TemplateFitAPGenerator::fTemplate2Ped [private]
Definition at line 44 of file TemplateFitAPGenerator.h.
Referenced by TemplateFitAPGenerator().
double TemplateFitAPGenerator::fTemplate2Time [private]
Definition at line 44 of file TemplateFitAPGenerator.h.
Referenced by TemplateFitAPGenerator().
double TemplateFitAPGenerator::fTemplateAmp [private]
Definition at line 43 of file TemplateFitAPGenerator.h.
Referenced by ProcessPulses(), and TemplateFitAPGenerator().
TemplateArchive * TemplateFitAPGenerator::fTemplateArchive = NULL [static, private]
Definition at line 39 of file TemplateFitAPGenerator.h.
Referenced by TemplateFitAPGenerator(), and ~TemplateFitAPGenerator().
TemplateArchive * TemplateFitAPGenerator::fTemplateArchive2 = NULL [static, private]
Definition at line 40 of file TemplateFitAPGenerator.h.
Referenced by TemplateFitAPGenerator(), and ~TemplateFitAPGenerator().
double TemplateFitAPGenerator::fTemplatePed [private]
Definition at line 43 of file TemplateFitAPGenerator.h.
Referenced by TemplateFitAPGenerator().
double TemplateFitAPGenerator::fTemplateTime [private]
Definition at line 43 of file TemplateFitAPGenerator.h.
Referenced by ProcessPulses(), and TemplateFitAPGenerator().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/TemplateFitAPGenerator.h
rootana/src/TAP_generators/TemplateFitAPGenerator.cpp