AlcapDAQ: TemplateFactory< BaseModule, OptionsType > Class Template Reference
TemplateFactory< BaseModule, OptionsType > Class Template Reference
#include <TemplateFactory.h>
Classes
struct PerModule
Public Types
typedef BaseModule *(* ModuleMaker)(OptionsType *)
typedef std::vector< std::string > ArgumentsVector
Public Member Functions
void registerModule (const std::string &, ModuleMaker, const std::string &out="")
Add a ModuleMaker function to the list of makers.
virtual BaseModule * createModule (const std::string &, OptionsType *opts=NULL)
Create a module with options.
bool canCreate (const std::string &name) const
Check if a module with this name has been registered.
void addOptions (const std::string &name, OptionsType *opts)
void addArguments (const std::string &all_args)
void addArgument (const std::string &module, const std::string &argument)
void addArgument (const std::string &argument)
std::string GetArgumentName (const std::string &module, const int &argument)
std::string GetProduct (const std::string &module)
void SetDebug (bool debug=true)
void PrintPossibleModules () const
Protected Member Functions
TemplateFactory (const std::string &name)
virtual ~TemplateFactory ()
Private Types
typedef std::map< std::string,
PerModule > ModuleList
Private Member Functions
const PerModule & GetModuleDetails (const std::string &) const
Private Attributes
ModuleList fModules
std::string fMostRecentRegister
bool fDebug
std::string fName
Detailed Description
template<typename BaseModule, typename OptionsType>
class TemplateFactory< BaseModule, OptionsType >
Definition at line 14 of file TemplateFactory.h.
Member Typedef Documentation
template<typename BaseModule, typename OptionsType> typedef std::vector<std::string> TemplateFactory< BaseModule, OptionsType >::ArgumentsVector
Definition at line 18 of file TemplateFactory.h.
template<typename BaseModule, typename OptionsType> typedef std::map<std::string, PerModule> TemplateFactory< BaseModule, OptionsType >::ModuleList [private]
Definition at line 28 of file TemplateFactory.h.
template<typename BaseModule, typename OptionsType> typedef BaseModule*(* TemplateFactory< BaseModule, OptionsType >::ModuleMaker)(OptionsType *)
Definition at line 17 of file TemplateFactory.h.
Constructor & Destructor Documentation
template<typename BaseModule, typename OptionsType> TemplateFactory< BaseModule, OptionsType >::TemplateFactory (const std::string & name) [inline, protected]
protected constructor only callable by derived class as this shoule be a singleton class
Definition at line 33 of file TemplateFactory.h.
:fName(name){};
template<typename BaseModule, typename OptionsType> virtual TemplateFactory< BaseModule, OptionsType >::~TemplateFactory () [inline, protected, virtual]
Definition at line 34 of file TemplateFactory.h.
{
            fModules.clear();
        }
Member Function Documentation
template<typename BaseModule , typename OptionsType > void TemplateFactory< BaseModule, OptionsType >::addArgument (const std::string & argument) [inline]
Definition at line 5 of file TemplateFactory.tpl.
References TemplateFactory< BaseModule, OptionsType >::addArgument(), and TemplateFactory< BaseModule, OptionsType >::fMostRecentRegister.
{
    addArgument(fMostRecentRegister,argument);
}
template<typename BaseModule , typename OptionsType > void TemplateFactory< BaseModule, OptionsType >::addArgument (const std::string & module, const std::string & argument) [inline]
Definition at line 11 of file TemplateFactory.tpl.
References TemplateFactory< BaseModule, OptionsType >::fModules.
Referenced by TemplateFactory< BaseModule, OptionsType >::addArgument(), and TemplateFactory< BaseModule, OptionsType >::addArguments().
{
    fModules[module].arguments.push_back(argument);
}
template<typename BaseModule , typename OptionsType > void TemplateFactory< BaseModule, OptionsType >::addArguments (const std::string & all_args) [inline]
Definition at line 75 of file TemplateFactory.tpl.
References TemplateFactory< BaseModule, OptionsType >::addArgument(), and modules::parser::TokeniseByDelimiter().
{
    std::vector<std::string> args;
    modules::parser::TokeniseByDelimiter(all_args,args,", ");
    for(unsigned i=0;i<args.size();i++){
        addArgument(args[i]);
    }
}
template<typename BaseModule , typename OptionsType> void TemplateFactory< BaseModule, OptionsType >::addOptions (const std::string & name, OptionsType * opts) [inline]
Definition at line 69 of file TemplateFactory.tpl.
References TemplateFactory< BaseModule, OptionsType >::fModules.
{
    fModules[name].opts=opts;
}
template<typename BaseModule, typename OptionsType> bool TemplateFactory< BaseModule, OptionsType >::canCreate (const std::string & name) const [inline]
Check if a module with this name has been registered.
Definition at line 44 of file TemplateFactory.h.
Referenced by modules::navigator::MakeModules().
{return (bool) fModules.count(name);};
template<typename BaseModule , typename OptionsType> BaseModule * TemplateFactory< BaseModule, OptionsType >::createModule (const std::string & name, OptionsType * opts = NULL) [inline, virtual]
Create a module with options.
Definition at line 23 of file TemplateFactory.tpl.
References TemplateFactory< BaseModule, OptionsType >::fName, TemplateFactory< BaseModule, OptionsType >::GetModuleDetails(), TemplateFactory< BaseModule, OptionsType >::PerModule::maker, module(), and TemplateFactory< BaseModule, OptionsType >::PerModule::opts.
Referenced by MakeAnalysedPulses::AddGenerator(), MakeMuonEvents::BeforeFirstEntry(), load_config_file(), MakeDetectorPulses::MakeGenerator(), and modules::navigator::MakeModules().
{
    // get the maker for the requested module
    BaseModule* module=NULL;
    const PerModule& details=GetModuleDetails(name);
    // make the module
    try{
        module=details.maker(opts?opts:details.opts);
    }catch(modules::missing_option& e){
        std::cout<<fName<<"::createModule: Error: "<<e.what()<<std::endl;
        return NULL;
    }catch(modules::bad_value& e){
        std::cout<<fName<<"::createModule: Error: "<<e.what()<<std::endl;
        return NULL;
    }
    return module;
}
template<typename BaseModule , typename OptionsType > std::string TemplateFactory< BaseModule, OptionsType >::GetArgumentName (const std::string & module, const int & argument) [inline]
Definition at line 17 of file TemplateFactory.tpl.
References TemplateFactory< BaseModule, OptionsType >::fModules.
Referenced by TAPGeneratorOptions::AddArgument(), and modules::options::AddArgument().
{
        return fModules.at(module).arguments.at(argument);
}
template<typename BaseModule , typename OptionsType > const TemplateFactory< BaseModule, OptionsType >::PerModule & TemplateFactory< BaseModule, OptionsType >::GetModuleDetails (const std::string & name) const [inline, private]
Definition at line 57 of file TemplateFactory.tpl.
References TemplateFactory< BaseModule, OptionsType >::fModules, TemplateFactory< BaseModule, OptionsType >::fName, and TemplateFactory< BaseModule, OptionsType >::PrintPossibleModules().
Referenced by TemplateFactory< BaseModule, OptionsType >::createModule(), and TemplateFactory< BaseModule, OptionsType >::GetProduct().
{
    typename ModuleList::const_iterator it  = fModules.find(name);
    if(it == fModules.end() ){
        std::cout<<fName<<"::GetModuleDetails: Error: I don't know how to make : "<<name<<std::endl;
        PrintPossibleModules();
        throw std::out_of_range(("unknown: "+name).c_str());
    }
    return it->second;
}
template<typename BaseModule , typename OptionsType > std::string TemplateFactory< BaseModule, OptionsType >::GetProduct (const std::string & module) [inline]
Definition at line 52 of file TemplateFactory.tpl.
References TemplateFactory< BaseModule, OptionsType >::GetModuleDetails(), and TemplateFactory< BaseModule, OptionsType >::PerModule::product.
{
    return GetModuleDetails(module).product;
}
template<typename BaseModule , typename OptionsType > void TemplateFactory< BaseModule, OptionsType >::PrintPossibleModules () const [inline]
Definition at line 84 of file TemplateFactory.tpl.
References TemplateFactory< BaseModule, OptionsType >::fModules.
Referenced by TemplateFactory< BaseModule, OptionsType >::GetModuleDetails(), and modules::reader::ProcessGlobalOption().
{
  std::cout<<"Available modules are:"<<std::endl;
  for(typename ModuleList::const_iterator it=fModules.begin();
                                 it!=fModules.end(); it++){
                                 std::cout<<"  "<<it->first<<std::endl;
 }
}
template<typename BaseModule , typename OptionsType > void TemplateFactory< BaseModule, OptionsType >::registerModule (const std::string & name, TemplateFactory< BaseModule, OptionsType >::ModuleMaker make, const std::string & out = "") [inline]
Add a ModuleMaker function to the list of makers.
Definition at line 42 of file TemplateFactory.tpl.
References TemplateFactory< BaseModule, OptionsType >::fModules, and TemplateFactory< BaseModule, OptionsType >::fMostRecentRegister.
{
    fModules[name].maker=make;
    fModules[name].product=out;
    fMostRecentRegister=name;
}
template<typename BaseModule, typename OptionsType> void TemplateFactory< BaseModule, OptionsType >::SetDebug (bool debug = true) [inline]
Definition at line 53 of file TemplateFactory.h.
Referenced by modules::reader::SetDebug().
{fDebug=debug;};
Member Data Documentation
template<typename BaseModule, typename OptionsType> bool TemplateFactory< BaseModule, OptionsType >::fDebug [private]
Definition at line 67 of file TemplateFactory.h.
Referenced by TemplateFactory< modules::BaseModule, modules::options >::SetDebug().
template<typename BaseModule, typename OptionsType> ModuleList TemplateFactory< BaseModule, OptionsType >::fModules [private]
Definition at line 61 of file TemplateFactory.h.
Referenced by TemplateFactory< BaseModule, OptionsType >::addArgument(), TemplateFactory< BaseModule, OptionsType >::addOptions(), TemplateFactory< modules::BaseModule, modules::options >::canCreate(), TemplateFactory< BaseModule, OptionsType >::GetArgumentName(), TemplateFactory< BaseModule, OptionsType >::GetModuleDetails(), TemplateFactory< BaseModule, OptionsType >::PrintPossibleModules(), TemplateFactory< BaseModule, OptionsType >::registerModule(), and TemplateFactory< modules::BaseModule, modules::options >::~TemplateFactory().
template<typename BaseModule, typename OptionsType> std::string TemplateFactory< BaseModule, OptionsType >::fMostRecentRegister [private]
Definition at line 64 of file TemplateFactory.h.
Referenced by TemplateFactory< BaseModule, OptionsType >::addArgument(), and TemplateFactory< BaseModule, OptionsType >::registerModule().
template<typename BaseModule, typename OptionsType> std::string TemplateFactory< BaseModule, OptionsType >::fName [private]
Definition at line 68 of file TemplateFactory.h.
Referenced by TemplateFactory< BaseModule, OptionsType >::createModule(), and TemplateFactory< BaseModule, OptionsType >::GetModuleDetails().
The documentation for this class was generated from the following files:
rootana/src/framework/TemplateFactory.h
rootana/src/framework/TemplateFactory.tpl