AlcapDAQ: TME_SiArmTDiff Class Reference
TME_SiArmTDiff Class Reference
[Modules]
Testing the TMEs for my Al50 analysis.
#include <TME_SiArmTDiff.h>
Public Member Functions
TME_SiArmTDiff (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~TME_SiArmTDiff ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::vector< IDs::channel > DetectorList
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Private Attributes
long int fNullCount
long int fTdpCount
bool fQuit
DetectorList fSiL1
IDs::channel * fSiL2
DetectorList fSiR1
IDs::channel * fSiR2
TH1F * fSiLTDiffs
TH1F * fSiRTDiffs
Detailed Description
Testing the TMEs for my Al50 analysis.
Author:
Andrew Edmonds
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 28 of file TME_SiArmTDiff.h.
Member Typedef Documentation
typedef std::vector<IDs::channel> TME_SiArmTDiff::DetectorList [private]
Definition at line 64 of file TME_SiArmTDiff.h.
Constructor & Destructor Documentation
TME_SiArmTDiff::TME_SiArmTDiff (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 21 of file TME_SiArmTDiff.cpp.
                                                  :
   BaseModule("TME_SiArmTDiff",opts),fNullCount(0),fTdpCount(0){
}
TME_SiArmTDiff::~TME_SiArmTDiff ()
Is anything done in the destructor?
Definition at line 25 of file TME_SiArmTDiff.cpp.
{
}
Member Function Documentation
int TME_SiArmTDiff::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 128 of file TME_SiArmTDiff.cpp.
{
  return 0;
}
int TME_SiArmTDiff::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 28 of file TME_SiArmTDiff.cpp.
References fSiL1, fSiL2, fSiLTDiffs, fSiR1, fSiR2, fSiRTDiffs, IDs::kNotApplicable, IDs::kSiL1_1, IDs::kSiL1_2, IDs::kSiL1_3, IDs::kSiL1_4, IDs::kSiL2, IDs::kSiR1_1, IDs::kSiR1_2, IDs::kSiR1_3, IDs::kSiR1_4, and IDs::kSiR2.
{
    using namespace IDs;
    fSiL1.push_back(IDs::channel (kSiL1_1 , kNotApplicable ));
    fSiL1.push_back(IDs::channel (kSiL1_2 , kNotApplicable ));
    fSiL1.push_back(IDs::channel (kSiL1_3 , kNotApplicable ));
    fSiL1.push_back(IDs::channel (kSiL1_4 , kNotApplicable ));
    fSiL2 = new IDs::channel (kSiL2   , kNotApplicable );
    fSiR1.push_back(IDs::channel (kSiR1_1 , kNotApplicable ));
    fSiR1.push_back(IDs::channel (kSiR1_2 , kNotApplicable ));
    fSiR1.push_back(IDs::channel (kSiR1_3 , kNotApplicable ));
    fSiR1.push_back(IDs::channel (kSiR1_4 , kNotApplicable ));
    fSiR2 = new IDs::channel (kSiR2   , kNotApplicable );
    //    fSiL1.push_back(IDs::channel (kMuSc   , kNotApplicable ));
    fSiLTDiffs = new TH1F("hSiLTDiffs", "TDiffs Between thick and thin SiL", 5000, -5e3,5e3);
    fSiLTDiffs->SetXTitle("t_thick - t_thin (ns)");
    fSiRTDiffs = new TH1F("hSiRTDiffs", "TDiffs Between thick and thin SiR", 5000, -5e3,5e3);
    fSiRTDiffs->SetXTitle("t_thick - t_thin (ns)");
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int TME_SiArmTDiff::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 50 of file TME_SiArmTDiff.cpp.
References fSiL1, fSiL2, fSiLTDiffs, fSiR1, fSiR2, fSiRTDiffs, TDetectorPulse::GetTime(), and gMuonEvents.
{
    for(MuonEventList::const_iterator i_tme=gMuonEvents.begin();
            i_tme!=gMuonEvents.end(); ++i_tme){
      // First, check for pile-up in the muSc
      if ( (*i_tme)->HasMuonPileup()) {
        continue;
      }
      double tme_time= (*i_tme)->GetTime(); // this is the same as the muSc time
      // Now loop through the SiL1
      for(DetectorList::const_iterator i_det=fSiL1.begin();
                i_det!=fSiL1.end(); ++i_det){
        // pulses per channel
        int SiL1_source_index=(*i_tme)->GetSourceIndex(*i_det);
        while(SiL1_source_index>-1){
          const IDs::source& SiL1_source=(*i_tme)->GetSource(SiL1_source_index);
          int n_SiL1 = (*i_tme)->NumPulses(SiL1_source);
          //          std::cout << SiL1_source << " has " << n_SiL1 << " pulses" << std::endl;
          for(int i=0; i<n_SiL1; ++i){
            const TDetectorPulse* tdp=(*i_tme)->GetPulse(SiL1_source,i);
            double thin_time = tdp->GetTime();
            // Loop trhough the SiL2 pulses
            int SiL2_source_index=(*i_tme)->GetSourceIndex(*fSiL2);
            while (SiL2_source_index>-1) {
              const IDs::source& SiL2_source=(*i_tme)->GetSource(SiL2_source_index);
              int n_SiL2 = (*i_tme)->NumPulses(SiL2_source);
              for (int j=0; j<n_SiL2; ++j) {
                const TDetectorPulse* tdp_SiL2=(*i_tme)->GetPulse(SiL2_source,j);
                double thick_time = tdp_SiL2->GetTime();
                fSiLTDiffs->Fill(thick_time - thin_time);
              }
              SiL2_source_index=(*i_tme)->GetSourceIndex(*fSiL2,SiL2_source_index+1);
            }
          }
          SiL1_source_index=(*i_tme)->GetSourceIndex(*i_det,SiL1_source_index+1);
        }
      }
      // Now loop through the SiR1
      for(DetectorList::const_iterator i_det=fSiR1.begin();
                i_det!=fSiR1.end(); ++i_det){
        // pulses per channel
        int SiR1_source_index=(*i_tme)->GetSourceIndex(*i_det);
        while(SiR1_source_index>-1){
          const IDs::source& SiR1_source=(*i_tme)->GetSource(SiR1_source_index);
          int n_SiR1 = (*i_tme)->NumPulses(SiR1_source);
          //          std::cout << SiR1_source << " has " << n_SiR1 << " pulses" << std::endl;
          for(int i=0; i<n_SiR1; ++i){
            const TDetectorPulse* tdp=(*i_tme)->GetPulse(SiR1_source,i);
            double thin_time = tdp->GetTime();
            // Loop trhough the SiR2 pulses
            int SiR2_source_index=(*i_tme)->GetSourceIndex(*fSiR2);
            while (SiR2_source_index>-1) {
              const IDs::source& SiR2_source=(*i_tme)->GetSource(SiR2_source_index);
              int n_SiR2 = (*i_tme)->NumPulses(SiR2_source);
              for (int j=0; j<n_SiR2; ++j) {
                const TDetectorPulse* tdp_SiR2=(*i_tme)->GetPulse(SiR2_source,j);
                double thick_time = tdp_SiR2->GetTime();
                fSiRTDiffs->Fill(thick_time - thin_time);
              }
              SiR2_source_index=(*i_tme)->GetSourceIndex(*fSiR2,SiR2_source_index+1);
            }
          }
          SiR1_source_index=(*i_tme)->GetSourceIndex(*i_det,SiR1_source_index+1);
        }
      }
    }
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
long int TME_SiArmTDiff::fNullCount [private]
Definition at line 60 of file TME_SiArmTDiff.h.
bool TME_SiArmTDiff::fQuit [private]
Definition at line 62 of file TME_SiArmTDiff.h.
DetectorList TME_SiArmTDiff::fSiL1 [private]
Definition at line 65 of file TME_SiArmTDiff.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
IDs::channel* TME_SiArmTDiff::fSiL2 [private]
Definition at line 66 of file TME_SiArmTDiff.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
TH1F* TME_SiArmTDiff::fSiLTDiffs [private]
Definition at line 70 of file TME_SiArmTDiff.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
DetectorList TME_SiArmTDiff::fSiR1 [private]
Definition at line 67 of file TME_SiArmTDiff.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
IDs::channel* TME_SiArmTDiff::fSiR2 [private]
Definition at line 68 of file TME_SiArmTDiff.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
TH1F* TME_SiArmTDiff::fSiRTDiffs [private]
Definition at line 71 of file TME_SiArmTDiff.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
long int TME_SiArmTDiff::fTdpCount [private]
Definition at line 60 of file TME_SiArmTDiff.h.
The documentation for this class was generated from the following files:
rootana/src/Al50/TME_SiArmTDiff.h
rootana/src/Al50/TME_SiArmTDiff.cpp