AlcapDAQ: MaxTimeDiffMEGenerator Class Reference
MaxTimeDiffMEGenerator Class Reference
#include <MaxTimeDiffMEGenerator.h>
Public Member Functions
MaxTimeDiffMEGenerator (TMEGeneratorOptions *opts)
virtual ~MaxTimeDiffMEGenerator ()
virtual int ProcessPulses (MuonEventList &muonEventsOut, const SourceDetPulseMap &detectorPulsesIn)
const IDs::generator & GetGenerator () const
Protected Member Functions
bool Debug () const
Detailed Description
Definition at line 6 of file MaxTimeDiffMEGenerator.h.
Constructor & Destructor Documentation
MaxTimeDiffMEGenerator::MaxTimeDiffMEGenerator (TMEGeneratorOptions * opts) [inline]
Definition at line 9 of file MaxTimeDiffMEGenerator.h.
: TVMuonEventGenerator("MaxTimeDiff",opts){};
virtual MaxTimeDiffMEGenerator::~MaxTimeDiffMEGenerator () [inline, virtual]
Definition at line 10 of file MaxTimeDiffMEGenerator.h.
{};
Member Function Documentation
bool TVMuonEventGenerator::Debug () const [inline, protected, inherited]
Definition at line 25 of file TVMuonEventGenerator.h.
Referenced by ProcessPulses().
{return fDebug;};
const IDs::generator& TVMuonEventGenerator::GetGenerator () const [inline, inherited]
Definition at line 22 of file TVMuonEventGenerator.h.
References TVMuonEventGenerator::fGenerator.
{return fGenerator;}
int MaxTimeDiffMEGenerator::ProcessPulses (MuonEventList & muonEventsOut, const SourceDetPulseMap & detectorPulsesIn) [virtual]
Implements TVMuonEventGenerator.
Definition at line 9 of file MaxTimeDiffMEGenerator.cpp.
References TMuonEvent::AddPulse(), TVMuonEventGenerator::Debug(), TDetectorPulse::GetSource(), TDetectorPulse::GetTime(), GetTime(), and TMuonEvent::TotalNumPulses().
{
          std::vector<DetectorPulseList::const_iterator> pulseIters;
          std::vector<DetectorPulseList::const_iterator> finalIters;
          for(SourceDetPulseMap::const_iterator i_detector=detectorPulsesIn.begin();
                          i_detector!=detectorPulsesIn.end(); i_detector++){
                          pulseIters.push_back(i_detector->second.begin());
                          finalIters.push_back(i_detector->second.end());
          }
          // Loop through both TAnalysedPulse vectors until they are both finished
          double min_time = 999999; // something large
          double pulse_time;
          while (pulseIters.size() > 0) {
            // Find out which of the next fast or slow pulsees happened next
            for (unsigned int b = 0; b < pulseIters.size(); ++b) {
              pulse_time = (*pulseIters[b])->GetTime() * 1e-6; // convert to ms
              min_time = std::min(min_time, pulse_time);
            }
            // Now go through and find all the pulses that are within a certain time of this
            double time_difference = 0.1; // 0.1 ms
            TMuonEvent* muon_event=new TMuonEvent();
            for (unsigned int b = 0; b < pulseIters.size(); ++b) {
              TDetectorPulse* pulse = *(pulseIters[b]);
              double pulse_time = pulse->GetTime() * 1e-6; // convert to ms
              if (std::fabs(pulse_time - min_time) < time_difference) {
                 if(Debug()) cout<<"Using pulse from: " << pulse->GetSource() << std::endl;
                 muon_event->AddPulse(pulse->GetSource(), pulse);
                ++(pulseIters[b]); // increment the iterator because we used the pulse
              }
            }
            muonEventsOut.push_back(muon_event);
            if(Debug()){
                cout<<"Created a TMuonEvent with "<<muon_event->TotalNumPulses();
                cout<< std::endl;
            }
            //Delete the iterators to finished banks. Go through in reverse to
            //avoid invalidation problems
            for (int b = pulseIters.size()-1; b >= 0; --b) {
              if (pulseIters[b] == finalIters[b]){
                pulseIters.erase(pulseIters.begin() + b);
                finalIters.erase(finalIters.begin() + b);
              }
            } // for (int b -reversed)
          } // end for
          return 0;
}
The documentation for this class was generated from the following files:
rootana/src/TME_generators/MaxTimeDiffMEGenerator.h
rootana/src/TME_generators/MaxTimeDiffMEGenerator.cpp