AlcapDAQ: WireMap Class Reference
WireMap Class Reference
C++ Class containing certain ODB keys in a usable form.
#include <WireMap.hh>
Public Types
enum key_t {
BANK, DETECTOR, ENABLED, PEDESTAL,
POLARITY, TIMESHIFT, FREQUENCY, UNKNOWN
}
Public Member Functions
WireMap ()
This constructs an empty WireMap.
WireMap (int run, std::string &odb_file)
void SetRun (unsigned int)
Set the run number.
void Enable ()
Enable the last channel added.
bool Enable (unsigned int)
Enable a channel.
void Disable ()
Disable last channel added.
bool Disable (unsigned int)
Disable a channel.
unsigned int GetRun () const
unsigned int GetNDets () const
std::vector< std::string > & GetBanks ()
std::vector< std::string > & GetDets ()
std::vector< bool > & GetEnableds ()
std::vector< int > & GetPedestals ()
std::vector< int > & GetPolarities ()
std::vector< int > & GetOffsets ()
std::vector< double > & GetFrequencies ()
void Add (const char bankname[], const char detname[], bool en, int ped, int pol, int off, double freq)
Add new value to WireMap.
void Add (std::string &bankname, std::string &detname, bool en, int ped, int pol, int off, double freq)
Add new value to WireMap. See Add(const char[], const char[], bool, int, int, int, double).
void Add (WireMap &wm, int index)
void UniqueFixes ()
void Load (int run, const std::string &odb_file)
void LoadOver (WireMap &)
Load another WireMap over this one in the same manner ODB Edit loads one ODb over another.
void Clear ()
Reset this WireMap to a state similar to what it would be if called with the default constructor.
void ResizeToBanks ()
bool AreThereDuplicates ()
void ClearDisabledDuplicateDetectors ()
void Print ()
Print for debugging.
Static Public Member Functions
static WireMap Default ()
Private Member Functions
void AddBank (const std::string &)
Add only bank name. This is the only method that adds a single element AND iIncrements fNDets.
void AddDet (const std::string &)
Add only detector name.
void AddEnabled (bool)
Add only enabled status.
void AddPedestal (int)
Add only pedestal.
void AddPolarity (int)
Add only polarity.
void AddOffset (int)
Add only timing offset (TimeShift).
void AddFrequency (double)
Add only frequency/.
Static Private Member Functions
static bool IsODBFile (const std::string &fname)
static int GetArraySize (const char(&tmp)[256])
static key_t GetKey (std::string &key)
Private Attributes
unsigned int fRun
Run number.
unsigned int fNDets
Number of detectors.
std::vector< std::string > fBankName
Name of each channel.
std::vector< std::string > fDetName
Detector attached to each channel.
std::vector< bool > fEnabled
Enabled status for each channel.
std::vector< int > fPedestal
Pedestals for each channel.
std::vector< int > fPolarity
Polarity of each channel.
std::vector< int > fOffset
Timing offset (TimeShift) for each channel.
std::vector< double > fFrequency
Sampling frequency of each channel.
Detailed Description
C++ Class containing certain ODB keys in a usable form.
The WireMap contains some information from the ODB wiremap. Specifically the run, banks names, detector names, enabled/disabled status, pedestals, polarities, and offsets. Can be given the path to an ODB file to construct from or built up with the Add method.
Definition at line 17 of file WireMap.hh.
Member Enumeration Documentation
enum WireMap::key_t
Each member corresponds to an ODB key used in WireMap. The method GetKey takes a string and if it matches an ODB key used by WireMap, returns the corresponding one (or UNKNOWN if not found.
Enumerator
BANK
DETECTOR
ENABLED
PEDESTAL
POLARITY
TIMESHIFT
FREQUENCY
UNKNOWN
Definition at line 36 of file WireMap.hh.
              { BANK, DETECTOR, ENABLED,
                PEDESTAL, POLARITY, TIMESHIFT,
                FREQUENCY, UNKNOWN };
Constructor & Destructor Documentation
WireMap::WireMap ()
This constructs an empty WireMap.
Definition at line 10 of file WireMap.cc.
                  {
 }
WireMap::WireMap (int run, std::string & odb_file)
Construct a WireMap from an ODB file.
Parameters
[in] run The run number needs to be specified since, as of yet, it isn't got from the ODB file.
[in] odb_file Path to the ODB files to use to construct a WireMap.
Definition at line 13 of file WireMap.cc.
References Load().
{
   Load(run, odb_file);
 }
Member Function Documentation
void WireMap::Add (const char bankname[], const char detname[], bool en, int ped, int pol, int off, double freq)
Add new value to WireMap.
Parameters
[in] bankname Channel name
[in] detname Detector name
[in] en Enabled status
[in] ped Pedestal
[in] pol Polarity
[in] off Timing offset (TimeShift)
[in] freq Sampling frequency
Definition at line 46 of file WireMap.cc.
Referenced by ODBCheck::Check(), and Default().
{
   std::string bn(bankname);
   std::string dn(detname);
   Add(bn, dn, en, ped, pol, off, freq);
 }
void WireMap::Add (std::string & bankname, std::string & detname, bool en, int ped, int pol, int off, double freq)
Add new value to WireMap. See Add(const char[], const char[], bool, int, int, int, double).
Definition at line 52 of file WireMap.cc.
References fBankName, fDetName, fEnabled, fFrequency, fNDets, fOffset, fPedestal, and fPolarity.
{
   ++fNDets;
   fBankName.push_back(bankname);
   fDetName.push_back(detname);
   fEnabled.push_back(en);
   fPedestal.push_back(ped);
   fPolarity.push_back(pol);
   fOffset.push_back(off);
   fFrequency.push_back(freq);
 }
void WireMap::Add (WireMap & wm, int index)
Add new value to WireMap from another WireMap
Parameters
[in] wm WireMap that has element we wish to copy to this WireMap.
[in] index Which element of this WireMap to copy.
Definition at line 63 of file WireMap.cc.
References fBankName, fDetName, fEnabled, fFrequency, fNDets, fOffset, fPedestal, fPolarity, GetBanks(), GetDets(), GetEnableds(), GetFrequencies(), GetOffsets(), GetPedestals(), GetPolarities(), and i.
{
   ++fNDets;
   fBankName.push_back(wm.GetBanks()[i]);
   fDetName.push_back(wm.GetDets()[i]);
   fEnabled.push_back(wm.GetEnableds()[i]);
   fPedestal.push_back(wm.GetPedestals()[i]);
   fPolarity.push_back(wm.GetPolarities()[i]);
   fOffset.push_back(wm.GetOffsets()[i]);
   fFrequency.push_back(wm.GetFrequencies()[i]);
 }
void WireMap::AddBank (const std::string & bank) private
Add only bank name. This is the only method that adds a single element AND iIncrements fNDets.
Definition at line 91 of file WireMap.cc.
References fBankName, and fNDets.
{
   ++fNDets;
   fBankName.push_back(bank);
 }
void WireMap::AddDet (const std::string & det) private
Add only detector name.
Definition at line 96 of file WireMap.cc.
References fDetName.
{
   fDetName.push_back(det);
 }
void WireMap::AddEnabled (bool en) private
Add only enabled status.
Definition at line 100 of file WireMap.cc.
References fEnabled.
{
   fEnabled.push_back(en);
 }
void WireMap::AddFrequency (double freq) private
Add only frequency/.
Definition at line 116 of file WireMap.cc.
References fFrequency.
{
   fFrequency.push_back(freq);
 }
void WireMap::AddOffset (int off) private
Add only timing offset (TimeShift).
Definition at line 112 of file WireMap.cc.
References fOffset.
Referenced by Default().
{
   fOffset.push_back(off);
 }
void WireMap::AddPedestal (int ped) private
Add only pedestal.
Definition at line 104 of file WireMap.cc.
References fPedestal.
{
   fPedestal.push_back(ped);
 }
void WireMap::AddPolarity (int pol) private
Add only polarity.
Definition at line 108 of file WireMap.cc.
References fPolarity.
{
   fPolarity.push_back(pol);
 }
bool WireMap::AreThereDuplicates ()
Check for duplicate detectors that are both enabled.
Returns
True if there exist two detectors with the same name that are both enabled.
Definition at line 306 of file WireMap.cc.
References fDetName, fEnabled, and i.
{
   unsigned int n = 0;
   if (fEnabled.size() < fDetName.size()) {
     std::cout << "WireMap WARNING: Array of enabled information is smaller than " <<
       "                 array of detector name information." << std::endl;
     n = fEnabled.size();
   } else if (fEnabled.size() > fDetName.size()) {
     std::cout << "WireMap WARNING: Array of enabled information is larger than " <<
       "array of detector name information." << std::endl;
     n = fDetName.size();
   }
   // If two channels are both the same detector and
   // both enabled, return true because there is a problem.
   for (unsigned int i = 0; i < n; ++i)
     for (unsigned int j = i + 1; j < n; ++j)
       if (fDetName[i] == fDetName[j] &&
           fEnabled[i] == fEnabled[j])
         return true;
   return false;
 }
void WireMap::Clear ()
Reset this WireMap to a state similar to what it would be if called with the default constructor.
Definition at line 257 of file WireMap.cc.
References fBankName, fDetName, fEnabled, fFrequency, fNDets, fOffset, fPedestal, fPolarity, and fRun.
Referenced by ODBCheck::Check(), and Load().
                     {
   fRun = 0;
   fNDets = 0;
   fBankName.clear();
   fDetName.clear();
   fEnabled.clear();
   fPedestal.clear();
   fPolarity.clear();
   fOffset.clear();
   fFrequency.clear();
 }
void WireMap::ClearDisabledDuplicateDetectors ()
Removes duplicate detectors as long as only one is enabled.
If there are multiple detectors with the same name, this sets the name of all of them to "blank" as long as only a single one of the duplicates is enabled.
Definition at line 329 of file WireMap.cc.
References fDetName, fEnabled, fRun, and i.
Referenced by ODBCheck::Check().
{
   static const std::string default_det("blank");
   for (unsigned int i = 0; i < fDetName.size(); ++i) {
     for (unsigned int j = i + 1; j < fDetName.size(); ++j) {
       if (fDetName[i] == fDetName[j]) {
         if (j < fEnabled.size() && !fEnabled[j]) {
           fDetName[j] = default_det;
         } else if (i < fEnabled.size() && !fEnabled[i]) {
           fDetName[i] = default_det;
         } else {
           std::cout << "WireMap ERROR: Couldn't determine which detector " << fDetName[i] <<
             " to remove in run " << fRun << "!" << std::endl;
         }
       }
     }
   }
 }
WireMap WireMap::Default () static
Return default WireMap
The batch scripts cause a number of ODB files to be loaded in analyzer/odb/ that can confuse issues. The WireMap that would result from loading all of these defaults has been hardcoded here.
Returns
The default WireMap.
Definition at line 430 of file WireMap.cc.
References Add(), and AddOffset().
Referenced by ODBCheck::Check().
{
   WireMap wm;
   wm.Add("Na80", "SiL2-S", true, 2745, -1, 4000, 1.7e+07);
   wm.Add("Nb80", "SiR2-S", true, 2730, -1, 4000, 1.7e+07);
   wm.Add("Nc80", "blank", true, 1000, -1, 0, 8.5e+06);
   wm.Add("Nd80", "blank", false, 1, -1, 0, 1.7e+07);
   wm.Add("Ne80", "blank", false, 1, -1, 0, 1.7e+08);
   wm.Add("Nf80", "blank", false, 1, -1, 0, 1.7e+08);
   wm.Add("Ng80", "blank", false, 1, -1, 0, 1.7e+08);
   wm.Add("Nh80", "blank", false, 1, -1, 0, 1.7e+08);
   wm.Add("Na81", "SiL2-F", true, 1415, 1, 407, 1.7e+08);
   wm.Add("Nb81", "SiR2-F", true, 1210, 1, 444, 1.7e+08);
   wm.Add("Nc81", "SiL1-1-F", true, 1292, 1, 146.7, 1.7e+08);
   wm.Add("Nd81", "SiL1-2-F", true, 1300, 1, 150, 1.7e+08);
   wm.Add("Ne81", "SiL1-3-F", true, 1280, 1, 149, 1.7e+08);
   wm.Add("Nf81", "SiL1-4-F", true, 1290, 1, 149.4, 1.7e+08);
   wm.Add("Ng81", "SiR1-sum-F", true, 1, 1, 0, 1.7e+08);
   wm.Add("Nh81", "Ge-F", true, 1390, 1, 81.1, 1.7e+08);
   wm.Add("Na82", "SiL1-1-S", true, 2760, -1, 2431, 1.7e+07);
   wm.Add("Nb82", "SiL1-2-S", true, 2820, -1, 2427, 1.7e+07);
   wm.Add("Nc82", "SiL1-3-S", true, 2740, -1, 2431, 1.7e+07);
   wm.Add("Nd82", "SiL1-4-S", true, 2740, -1, 2429, 1.7e+07);
   wm.Add("Ne82", "SiR1-1-S", true, 2750, -1, 2600, 1.7e+07);
   wm.Add("Nf82", "SiR1-2-S", true, 2750, -1, 2600, 1.7e+07);
   wm.Add("Ng82", "SiR1-3-S", true, 2740, -1, 2600, 1.7e+07);
   wm.Add("Nh82", "SiR1-4-S", true, 2740, -1, 2600, 1.7e+07);
   wm.Add("Na83", "ScL", true, 1, 1, 69.7, 1.7e+07);
   wm.Add("Nb83", "ScR", false, 1, 1, 69.2, 3.4e+07);
   wm.Add("Nc83", "ScGe", true, 1185, -1, 81.1, 1.7e+08);
   wm.Add("Nd83", "ScVe", false, 1, 1, 71.9, 3.4e+07);
   wm.Add("Ne83", "blank", false, 1, 1, 146.7, 3.4e+07);
   wm.Add("Nf83", "blank", false, 1, 1, 150, 3.4e+07);
   wm.Add("Ng83", "LiquidSc", false, 1, 1, 149, 3.4e+07);
   wm.Add("Nh83", "blank", false, 1, 1, 149, 3.4e+07);
   wm.Add("CaUH","Ge-S", true, 1140,-1, 42000, 1e+08);
   wm.Add("CbUH","blank", false, 1, -1, 37000, 1e+08);
   wm.Add("CcUH","blank", false, 1, -1, 0, 1e+08);
   wm.Add("CdUH","blank", false, 1, -1, 0, 1e+08);
   wm.Add("CeUH","blank", false, 1, -1, 0, 1e+08);
   wm.Add("CfUH","blank", false, 1, -1, 0, 1e+08);
   wm.Add("CgUH","blank", false, 1, -1, 0, 1e+08);
   wm.Add("ChUH","blank", false, 1, -1, 0, 1e+08);
   wm.Add("CaBU","muSc", false, 2071, 1, 0, 2.5e+08);
   wm.Add("CbBU","muScA", false, 2122, 1, 12.7, 2.5e+08);
   wm.Add("CcBU","muScA", false, 1, 1, 0, 2.5e+08);
   wm.Add("CdBU","blank", false, 1, 1, 0, 2.5e+08);
   wm.Add("ZZZZ","blank", false, 1, -1, 0, 0.);
   wm.Add("ZZZZ","blank", false, 1, -1, 0, 0.);
   wm.Add("ZZZZ","blank", false, 1, -1, 0, 0.);
   wm.Add("ZZZZ","blank", false, 1, -1, 0, 0.);
   wm.AddOffset(0);
   wm.AddOffset(0);
   wm.AddOffset(0);
   wm.AddOffset(0);
   return wm;
 }
void WireMap::Disable ()
Disable last channel added.
Definition at line 36 of file WireMap.cc.
References fEnabled.
Referenced by ODBCheck::Check().
                       {
   fEnabled.back() = false;
 }
bool WireMap::Disable (unsigned int i)
Disable a channel.
Returns
True if succesful.
Definition at line 40 of file WireMap.cc.
References fEnabled.
{
   if (i < fEnabled.size())
     return !(fEnabled[i] = false);
   return false;
 }
void WireMap::Enable ()
Enable the last channel added.
Definition at line 26 of file WireMap.cc.
References fEnabled.
                      {
   fEnabled.back() = true;
 }
bool WireMap::Enable (unsigned int i)
Enable a channel.
Returns
True if succesful.
Definition at line 30 of file WireMap.cc.
References fEnabled.
{
   if (i < fEnabled.size())
     return (fEnabled[i] = true);
   return false;
 }
int WireMap::GetArraySize (const char(&) tmp[256]) static private
Determines the number of elements in an ODB key's array
The ODB records how many elements are in an key that is an array. The key declaration in the ODB file is of the form
VARIABLE = TYPE [##] :
Parameters
tmp The part of the key declaration of the form " = TYPE [##] :"
Returns
The number of elemented in the array.
Definition at line 351 of file WireMap.cc.
Referenced by Load().
{
   // Get # of detectors from line in ODB of the form
   // VARIBALE = TYPE[#] :
   std::string str(tmp);
   std::stringstream ss;
   int n;
   int pos[2];
   pos[0] = str.find('[') + 1;
   pos[1] = str.find(']');
   str = str.substr(pos[0], pos[1] - pos[0]);
   ss << str;
   ss >> n;
   return n;
 }
std::vector< std::string > & WireMap::GetBanks ()
Returns
Reference to vector of bank names.
Definition at line 376 of file WireMap.cc.
References fBankName.
Referenced by Add(), ODBCheck::Check(), and LoadOver().
{
   return fBankName;
 }
std::vector< std::string > & WireMap::GetDets ()
Returns
Reference to vector of detector names.
Definition at line 380 of file WireMap.cc.
References fDetName.
Referenced by Add(), ODBCheck::Check(), LoadOver(), and ODBCheck::OutputCorrections().
{
   return fDetName;
 }
std::vector< bool > & WireMap::GetEnableds ()
Returns
Reference to vector of channel's enabled status.
Definition at line 384 of file WireMap.cc.
References fEnabled.
Referenced by Add(), LoadOver(), and ODBCheck::OutputCorrections().
{
   return fEnabled;
 }
std::vector< double > & WireMap::GetFrequencies ()
Returns
Reference to vector of sampling frequencies.
Definition at line 400 of file WireMap.cc.
References fFrequency.
Referenced by Add(), ODBCheck::Check(), LoadOver(), and ODBCheck::OutputCorrections().
{
   return fFrequency;
 }
WireMap::key_t WireMap::GetKey (std::string & key) static private
Get the ODB key from its declaration in the ODB file.
Keys in an ODB file are declared akin to
KEYNAME = KEYTYPE
Parameters
[in] key The string in the ODB file that declares the key. Just the stirng KEYNAME
Returns
The key type.
Definition at line 404 of file WireMap.cc.
References BANK, DETECTOR, ENABLED, FREQUENCY, PEDESTAL, POLARITY, TIMESHIFT, and UNKNOWN.
Referenced by Load().
{
   static const std::string bankname_key("BankName");
   static const std::string detname_key("DetectorName");
   static const std::string enabled_key("Enabled");
   static const std::string polarity_key("TriggerPolarity");
   static const std::string pedestal_key("Pedestal");
   static const std::string offset_key("TimeShift");
   static const std::string frequency_key("SamplingFrequency");
   if (key == bankname_key)
     return BANK;
   else if (key == detname_key)
     return DETECTOR;
   else if (key == enabled_key)
     return ENABLED;
   else if (key == polarity_key)
     return POLARITY;
   else if (key == pedestal_key)
     return PEDESTAL;
   else if (key == offset_key)
     return TIMESHIFT;
   else if (key == frequency_key)
     return FREQUENCY;
   return UNKNOWN;
 }
unsigned int WireMap::GetNDets () const
Returns
Number of detectors.
Definition at line 372 of file WireMap.cc.
References fNDets.
Referenced by ODBCheck::Check(), LoadOver(), and ODBCheck::OutputCorrections().
{
   return fNDets;
 }
std::vector< int > & WireMap::GetOffsets ()
Returns
Reference to vector of timing offsets (TimeShift).
Definition at line 396 of file WireMap.cc.
References fOffset.
Referenced by Add(), LoadOver(), and ODBCheck::OutputCorrections().
{
   return fOffset;
 }
std::vector< int > & WireMap::GetPedestals ()
Returns
Reference to vector of pedestals.
Definition at line 388 of file WireMap.cc.
References fPedestal.
Referenced by Add(), LoadOver(), and ODBCheck::OutputCorrections().
{
   return fPedestal;
 }
std::vector< int > & WireMap::GetPolarities ()
Returns
Reference to vector of polarities (+/- 1).
Definition at line 392 of file WireMap.cc.
References fPolarity.
Referenced by Add(), LoadOver(), and ODBCheck::OutputCorrections().
{
   return fPolarity;
 }
unsigned int WireMap::GetRun () const
Returns
Run number.
Definition at line 368 of file WireMap.cc.
References fRun.
Referenced by LoadOver(), and ODBCheck::OutputCorrections().
{
   return fRun;
 }
bool WireMap::IsODBFile (const std::string & fname) static private
Checks extension for 'odb'
This is called internally before trying to load an ODB file.
Parameters
[in] fname Path to ODB file.
Returns
True if the extension indicates the path points to an ODB file..
Definition at line 347 of file WireMap.cc.
Referenced by Load().
{
   return ".odb" == fname.substr(fname.size() - 4);
 }
void WireMap::Load (int run, const std::string & odb_file)
Load ODB values into WireMap from an ODB file.
Parses an ODB file, finds keys indicating what the WireMap can hold, and loads those.
Parameters
[in] run Run number. Needs to be included here because it's not parsed from the ODB file yet.
[in] odb_file Path to ODB file to load.
Definition at line 120 of file WireMap.cc.
References BANK, c, Clear(), DETECTOR, ENABLED, fBankName, fDetName, fEnabled, fFrequency, fNDets, fOffset, fPedestal, fPolarity, FREQUENCY, fRun, GetArraySize(), GetKey(), i, IsODBFile(), key, PEDESTAL, POLARITY, run_number, and TIMESHIFT.
Referenced by WireMap().
{
   static const std::string header("[/Analyzer/WireMap]");
   static char tmp[256];
   if (!IsODBFile(odb_file)) {
     std::cout <<
       "WireMap ERROR: Not recognized as ODB file input! Must be ODB file." <<
       std::endl;
     return;
   }
   Clear();
   fRun = run_number;
   // Look through ODB file for appropriate banks
   std::ifstream f(odb_file.c_str());
   std::string str;
   key_t key;
   int x;
   char c;
   double d;
   while (f.good()) {
     f >> str;
     if (str == header) {
       while (f.good()) {
         f >> str;
         key = GetKey(str);
         f.getline(tmp, 256);
         unsigned int n = 0; // Array size
         if (key == BANK) {
           n = GetArraySize(tmp);
           fBankName.reserve(n);
           fNDets = n; // Set number of detectors equal to number of banks
           for (unsigned int i = 0; i < n; ++i) {
             f >> str;
             if (f.read(tmp, 1).peek() == '\n') // Strings can be null, cause streaming problems
               str = "";
             else
               f >> str;
             fBankName.push_back(str);
           }
         } else if (key == DETECTOR) {
           n = GetArraySize(tmp);
           fDetName.reserve(n);
           for (unsigned int i = 0; i < n; ++i) {
             f >> str;
             if (f.read(tmp, 1).peek() == '\n') // Strings can be null, cause streaming problems
               str = "";
             else
               f >> str;
             fDetName.push_back(str);
           }
         } else if (key == ENABLED) {
           n = GetArraySize(tmp);
           fEnabled.reserve(n);
           for (unsigned int i =0; i < n; ++i) {
             f >> str >> c;
             if (c == 'y') fEnabled.push_back(true);
             else if (c == 'n') fEnabled.push_back(false);
             else std::cout << "WireMap ERROR: '" << c <<
                    "' is not an ODB boolean!" << std::endl;
           }
         } else if (key == PEDESTAL) {
           n = GetArraySize(tmp);
           fPedestal.reserve(n);
           for (unsigned int i = 0; i < n; ++i) {
             f >> str >> x;
             fPedestal.push_back(x);
           }
         } else if (key == POLARITY) {
           n = GetArraySize(tmp);
           fPolarity.reserve(n);
           for (unsigned int i = 0; i < n; ++i) {
             f >> str >> x;
             fPolarity.push_back(x);
           }
         } else if (key == TIMESHIFT) {
           n = GetArraySize(tmp);
           fOffset.reserve(n);
           for (unsigned int i = 0; i < n; ++i) {
             f >> str >> x;
             fOffset.push_back(x);
           }
         } else if (key == FREQUENCY) {
           n = GetArraySize(tmp);
           fFrequency.reserve(n);
           for (unsigned int i = 0; i < n; ++i) {
             f >> str >> d;
             fFrequency.push_back(d);
           }
         }
         // If for some reason haven't got the number of detectors
         // from number of banks, then grab the first non-zero
         // array sized key from ODB
         if (fNDets == 0)
           fNDets = n;
         // If everything is the right size
         // That means everything is finished
         if (fNDets != 0 &&
             fBankName.size() == fNDets &&
             fDetName.size() == fNDets &&
             fPedestal.size() == fNDets &&
             fPolarity.size() == fNDets &&
             fOffset.size() == fNDets &&
             fFrequency.size() == fNDets)
           return;
       }
     }
   }
   // If we get to this point, vectors are not all equal in size
   std::cout <<
     "WireMap WARNING: Didn't find everything in the ODB! (" <<
     odb_file << ")" << std::endl;
 }
void WireMap::LoadOver (WireMap & wm)
Load another WireMap over this one in the same manner ODB Edit loads one ODb over another.
Definition at line 236 of file WireMap.cc.
References fBankName, fDetName, fEnabled, fFrequency, fNDets, fOffset, fPedestal, fPolarity, fRun, GetBanks(), GetDets(), GetEnableds(), GetFrequencies(), GetNDets(), GetOffsets(), GetPedestals(), GetPolarities(), and GetRun().
Referenced by ODBCheck::Check().
{
   // Load the new WireMap variables if they exist
   // This seems to be how the ODB operates
   fRun = wm.GetRun();
   fNDets = wm.GetNDets();
   if (wm.GetBanks().size() > 0)
     fBankName = wm.GetBanks();
   if (wm.GetDets().size() > 0)
     fDetName = wm.GetDets();
   if (wm.GetEnableds().size() > 0)
     fEnabled = wm.GetEnableds();
   if (wm.GetPedestals().size() > 0)
     fPedestal = wm.GetPedestals();
   if (wm.GetPolarities().size() > 0)
     fPolarity = wm.GetPolarities();
   if (wm.GetOffsets().size() > 0)
     fOffset = wm.GetOffsets();
   if (wm.GetFrequencies().size() > 0)
     fFrequency = wm.GetFrequencies();
 }
void WireMap::Print ()
Print for debugging.
Definition at line 495 of file WireMap.cc.
References fBankName, fDetName, fEnabled, fFrequency, fNDets, fOffset, fPedestal, fPolarity, fRun, and i.
                     {
   using namespace std;
   stringstream ss;
   std::vector<unsigned int> sizes;
   sizes.push_back(fBankName.size());
   sizes.push_back(fDetName.size());
   sizes.push_back(fEnabled.size());
   sizes.push_back(fPedestal.size());
   sizes.push_back(fPolarity.size());
   sizes.push_back(fOffset.size());
   sizes.push_back(fFrequency.size());
   unsigned int n = sizes[0];
   for (unsigned int i = 1; i < sizes.size(); ++i)
     if (sizes[i] > n)
       n = sizes[i];
   cout << left;
   cout << setw(24) << "Run Number:" << fRun << endl;
   cout << setw(24) << "Number of detectors:" << fNDets << endl;
   ss << "Bank (" << fBankName.size() << ")";
   cout << setw(11) << ss.str(); ss.str(string());
   ss << "Detector (" << fDetName.size() << ")";
   cout << setw(15) << ss.str(); ss.str(string());
   ss << "Enabled (" << fEnabled.size() << ")";
   cout << setw(14) << ss.str(); ss.str(string());
   ss << "Pedestal (" << fPedestal.size() << ")";
   cout << setw(15) << ss.str(); ss.str(string());
   ss << "Polarity (" << fPolarity.size() << ")";
   cout << setw(15) << ss.str(); ss.str(string());
   ss << "TimeShift (" << fOffset.size() << ")";
   cout << setw(16) << ss.str(); ss.str(string());
   ss << "Frequency (" << fFrequency.size() << ")";
   cout << setw(16) << ss.str(); ss.str(string());
   cout << endl;
   cout << setfill('-') << setw(98) << '-' << setfill(' ') << endl;
   cout << setfill(' ') << right;
   for (unsigned int i = 0; i < n; ++i) {
     cout << setw(11);
     if (i < fBankName.size()) cout << fBankName[i];
     else cout << ' ';
     cout << setw(15);
     if (i < fDetName.size()) cout << fDetName[i];
     else cout << ' ';
     cout << setw(14);
     if (i < fEnabled.size()) cout << (fEnabled[i] ? 'y' : 'n');
     else cout << ' ';
     cout << setw(15);
     if (i < fPedestal.size()) cout << fPedestal[i];
     else cout << ' ';
     cout << setw(15);
     if (i < fPolarity.size()) cout << (fPolarity[i] == -1 ? '-' : '+');
     else cout << ' ';
     cout << setw(16);
     if (i < fOffset.size()) cout << -fOffset[i];
     else cout << ' ';
     cout << setw(16);
     if (i < fFrequency.size()) cout << fFrequency[i];
     else cout << ' ';
     cout << endl;
   }
 }
void WireMap::ResizeToBanks ()
Resize all vectors to size of banks.
It's possible that upond loading an ODB file not all of the data vectors (bank name, detector names, enabled status, ...) are equal in size. This poses a problem because the index of these vectors are what correspond the data to one another.
This resizes all vectors to the same size as the bank name vector by trimming them down or bloating them up. The trimming is done by removing the last element of the data vectors until they're short enough, or by appending default values until long enough. Ideally, this would never be necessary; however it was needed during development of odb_check.cc and is being kept in case it is needed again.
Definition at line 269 of file WireMap.cc.
References fBankName, fDetName, fEnabled, fFrequency, fNDets, fOffset, fPedestal, and fPolarity.
{
   static const std::string default_det("blank");
   static const bool default_en = false;
   static const int default_ped = 0;
   static const int default_pol = 1;
   static const int default_off = 0;
   static const double default_freq = 0.;
   fNDets = fBankName.size();
   // Trim down
   while (fDetName.size() > fNDets)
     fDetName.pop_back();
   while (fEnabled.size() > fNDets)
     fEnabled.pop_back();
   while (fPedestal.size() > fNDets)
     fPedestal.pop_back();
   while (fPolarity.size() > fNDets)
     fPedestal.pop_back();;
   while (fOffset.size() > fNDets)
     fOffset.pop_back();
   while (fFrequency.size() > fNDets)
     fFrequency.pop_back();
   // Bulk up
   while (fDetName.size() < fNDets)
     fDetName.push_back(default_det);
   while (fEnabled.size() < fNDets)
     fEnabled.push_back(default_en);
   while (fPedestal.size() < fNDets)
     fPedestal.push_back(default_ped);
   while (fPolarity.size() < fNDets)
     fPolarity.push_back(default_pol);
   while (fOffset.size() < fNDets)
     fOffset.push_back(default_off);
   while (fFrequency.size() < fNDets)
     fFrequency.push_back(default_freq);
 }
void WireMap::SetRun (unsigned int run)
Set the run number.
Definition at line 17 of file WireMap.cc.
References fRun.
Referenced by ODBCheck::Check().
{
   if (run > 0 && run < 100000)
     fRun = run;
   else
     std::cout <<
       "WireMap WARNING: Run outside range! (" << run << ")" <<
       std::endl;
 }
void WireMap::UniqueFixes ()
Unique fixes for certain runs
For runs 2091-2103, correct the sampling frequency
Definition at line 74 of file WireMap.cc.
References fBankName, fFrequency, fRun, i, and size.
Referenced by ODBCheck::Check().
{
   // The UH CAEN had the incorrect sampling
   // for runs 2091-2103
   double default_freq = 0.;
   double freq_fix = 1.6129e7;
   if (fRun >= 2091 && fRun <= 2103) {
     for (unsigned int i = 0; i < fBankName.size(); ++i) {
       if (fBankName[i].substr(0,1) == "C" && fBankName[i].substr(fBankName[i].size() - 2) == "UH") {
         while (fFrequency.size() <= i) {
           fFrequency.push_back(default_freq);
         }
         fFrequency[i] = freq_fix;
       }
     }
   }
 }
Field Documentation
std::vector<std::string> WireMap::fBankName private
Name of each channel.
Definition at line 21 of file WireMap.hh.
Referenced by Add(), AddBank(), Clear(), GetBanks(), Load(), LoadOver(), Print(), ResizeToBanks(), and UniqueFixes().
std::vector<std::string> WireMap::fDetName private
Detector attached to each channel.
Definition at line 22 of file WireMap.hh.
Referenced by Add(), AddDet(), AreThereDuplicates(), Clear(), ClearDisabledDuplicateDetectors(), GetDets(), Load(), LoadOver(), Print(), and ResizeToBanks().
std::vector<bool> WireMap::fEnabled private
Enabled status for each channel.
Definition at line 23 of file WireMap.hh.
Referenced by Add(), AddEnabled(), AreThereDuplicates(), Clear(), ClearDisabledDuplicateDetectors(), Disable(), Enable(), GetEnableds(), Load(), LoadOver(), Print(), and ResizeToBanks().
std::vector<double> WireMap::fFrequency private
Sampling frequency of each channel.
Definition at line 27 of file WireMap.hh.
Referenced by Add(), AddFrequency(), Clear(), GetFrequencies(), Load(), LoadOver(), Print(), ResizeToBanks(), and UniqueFixes().
unsigned int WireMap::fNDets private
Number of detectors.
Definition at line 20 of file WireMap.hh.
Referenced by Add(), AddBank(), Clear(), GetNDets(), Load(), LoadOver(), Print(), and ResizeToBanks().
std::vector<int> WireMap::fOffset private
Timing offset (TimeShift) for each channel.
Definition at line 26 of file WireMap.hh.
Referenced by Add(), AddOffset(), Clear(), GetOffsets(), Load(), LoadOver(), Print(), and ResizeToBanks().
std::vector<int> WireMap::fPedestal private
Pedestals for each channel.
Definition at line 24 of file WireMap.hh.
Referenced by Add(), AddPedestal(), Clear(), GetPedestals(), Load(), LoadOver(), Print(), and ResizeToBanks().
std::vector<int> WireMap::fPolarity private
Polarity of each channel.
Definition at line 25 of file WireMap.hh.
Referenced by Add(), AddPolarity(), Clear(), GetPolarities(), Load(), LoadOver(), Print(), and ResizeToBanks().
unsigned int WireMap::fRun private
Run number.
Definition at line 19 of file WireMap.hh.
Referenced by Clear(), ClearDisabledDuplicateDetectors(), GetRun(), Load(), LoadOver(), Print(), SetRun(), and UniqueFixes().
The documentation for this class was generated from the following files:
analyzer/odb_check/include/WireMap.hh
analyzer/odb_check/src/WireMap.cc