AlcapDAQ: modules::options Class Reference
modules::options Class Reference
Class to handle options given through the MODULES file.
#include <ModulesOptions.h>
Public Types
typedef std::map< std::string,
std::string > OptionsList_t
Helper typedef, intended for the list of key-value pairs for each option.
typedef std::vector
< OptionsList_t::iterator > OptionsOrder_t
Helper typedef, intended to keep the order of option declaration.
Public Member Functions
options (const std::string &name)
Constructor of an option. The name of the module that will.
virtual ~options ()
std::string StringDescription () const
Flatten all options into a string.
void SetOption (const std::string &key, const std::string &value)
Set the value of an option.
bool AppendToOption (const std::string &key, const std::string &value)
Append a new value to a list.
void AddArgument (const int &number, const std::string &value)
Set the value of an argument.
int GetInt (const std::string &name, int defVal, const std::string &range="") const
Get the named option as an int.
double GetDouble (const std::string &name, double defVal, const std::string &range="") const
Get the named option as a double.
std::string GetString (const std::string &name, const std::string &defVal) const
Get the named option as a string.
bool GetBool (const std::string &name, bool defVal) const
Get the named option as a bool.
int GetInt (const std::string &name, const std::string &range="") const
Get the named option as an int, which MUST exist.
double GetDouble (const std::string &name, const std::string &range="") const
Get the named option as a double, which MUST exist.
std::string GetString (const std::string &name) const
Get the named option as a string.
bool GetBool (const std::string &name) const
Get the named option as a bool.
int GetVectorStringsByWhiteSpace (const std::string &name, std::vector< std::string > &vect) const
Fill a vector of strings with whitespace delimited tokens found in the named option.
int GetVectorStringsByDelimiter (const std::string &name, std::vector< std::string > &vect, const char *delim=":") const
Fill a vector of strings with tokens found in the named option @ Uses strtok so not suitable for multi-threading (if we ever do something like that).
bool HasOption (const std::string &name) const
Check if a named option has been set.
bool GetFlag (const std::string &name) const
Check if a flag option has been set.
bool GetNumOptions () const
Get the number of options managed by this options list.
std::string GetOption (const std::string &name, bool complain=false) const
Returns the unprocessed value assigned to name.
OptionsList_t::const_iterator begin () const
Get a const iterator to the first key-value pair (sorted alphabetically by.
OptionsList_t::const_iterator end () const
Get a const iterator to the last key-value pair (sorted alphabetically by key).
void DumpOptions (const std::string &prefix=" ") const
Print all options managed by this list to cout.
void SetAlias (const std::string &alias)
Set the alias option for this module.
std::string GetAlias (const std::string &defVal="") const
Get the alias option for this module.
Protected Attributes
std::string fModuleName
Private Member Functions
template<typename T >
T GetOption (const std::string &name, const T &defVal, bool complain, const std::string &range="") const
Get an option using std::stringstream.
void CheckValid (const std::string &name, const char *expression, double value) const
Check the validity of an option's value.
Static Private Member Functions
static int MakeIdNumber ()
Create a unique ID number used for each option.
Private Attributes
OptionsList_t fOptions
OptionsOrder_t fOrder
int fIdNumber
Detailed Description
Class to handle options given through the MODULES file.
Definition at line 26 of file ModulesOptions.h.
Member Typedef Documentation
typedef std::map<std::string,std::string> modules::options::OptionsList_t
Helper typedef, intended for the list of key-value pairs for each option.
Definition at line 29 of file ModulesOptions.h.
typedef std::vector<OptionsList_t::iterator> modules::options::OptionsOrder_t
Helper typedef, intended to keep the order of option declaration.
Definition at line 31 of file ModulesOptions.h.
Constructor & Destructor Documentation
modules::options::options (const std::string & name) [inline]
Constructor of an option. The name of the module that will.
Definition at line 36 of file ModulesOptions.h.
References fIdNumber, and MakeIdNumber().
                                      :fModuleName(name){
            fIdNumber=MakeIdNumber();
        };
virtual modules::options::~options () [inline, virtual]
Definition at line 39 of file ModulesOptions.h.
{};
Member Function Documentation
void modules::options::AddArgument (const int & number, const std::string & value)
Set the value of an argument.
If the module has not specified a name for this argument, the key for this option is set to number ALCAP_REGISTER_MODULE
Parameters:
number The number of the argument to set
value The new value of the argument
Reimplemented in TAPGeneratorOptions, and TDPGeneratorOptions.
Definition at line 117 of file ModulesOptions.cpp.
References fModuleName, TemplateFactory< BaseModule, OptionsType >::GetArgumentName(), modules::factory::Instance(), and SetOption().
Referenced by modules::reader::AddModule().
{
    // Get the name of this argument
    std::string name = modules::factory::Instance()->GetArgumentName(fModuleName,number);
    // Set the value of the corresponding option
    modules::options::SetOption(name,option);
}
bool modules::options::AppendToOption (const std::string & key, const std::string & value)
Append a new value to a list.
The new value is separated from the previous one with: " : "
Parameters:
key The name of the option to add to
value The value to append
Returns:
true if a value existed already and false if not
Definition at line 124 of file ModulesOptions.cpp.
References fOptions.
Referenced by modules::reader::AddOption().
{
    // Get the option
    OptionsList_t::iterator it= fOptions.find(name);
    // If no option exists return false
    if(it==fOptions.end()) return false;
    // Add the value to it
    it->second+=" : "+option;
    return true;
}
OptionsList_t::const_iterator modules::options::begin () const [inline]
Get a const iterator to the first key-value pair (sorted alphabetically by.
Definition at line 184 of file ModulesOptions.h.
References fOptions.
Referenced by ExportPulse::BeforeFirstEntry().
{return fOptions.begin();};
void modules::options::CheckValid (const std::string & name, const char * expression, double value) const [private]
Check the validity of an option's value.
Parameters:
name Option's name, used in reporting validity
expression Expression to define range.
value The value of the option to check
Definition at line 35 of file ModulesOptions.cpp.
References fModuleName, and modules::parser::ReplaceWords().
Referenced by GetOption().
{
    std::string expr(expression);
    modules::parser::ReplaceWords(expr,name,"x");
    TFormula formula((name+"_validity").c_str(), expr.c_str());
    formula.Compile();
    double eval=formula.Eval(value);
    if(eval!=1){
        throw bad_value(fModuleName.c_str(),name.c_str(),expression,value);
    }
}
void modules::options::DumpOptions (const std::string & prefix = " ") const
Print all options managed by this list to cout.
Parameters:
prefix Appended before each line is printed
Definition at line 105 of file ModulesOptions.cpp.
References fOrder.
Referenced by load_config_file(), and modules::navigator::MakeModules().
{
    //std::cout<<"key  "<<" = "<<" value "<<std::endl;
    OptionsOrder_t::const_iterator it;
    for(it=fOrder.begin();it!=fOrder.end();it++){
        std::cout<<prefix<<(*it)->first;
        if((*it)->second!=""){
           std::cout<<" = "<<(*it)->second;
        }
        std::cout<<std::endl;
    }
}
OptionsList_t::const_iterator modules::options::end () const [inline]
Get a const iterator to the last key-value pair (sorted alphabetically by key).
Definition at line 186 of file ModulesOptions.h.
References fOptions.
Referenced by ExportPulse::BeforeFirstEntry().
{return fOptions.end();};
std::string modules::options::GetAlias (const std::string & defVal = "") const [inline]
Get the alias option for this module.
Definition at line 198 of file ModulesOptions.h.
References GetString().
Referenced by BaseModule::BaseModule().
{return GetString("alias",defVal);};
bool modules::options::GetBool (const std::string & name) const
Get the named option as a bool.
Parameters:
name Name of the option to get
Definition at line 74 of file ModulesOptions.cpp.
References GetString(), and modules::parser::IsTrue().
{
    return modules::parser::IsTrue(GetString(name));
}
bool modules::options::GetBool (const std::string & name, bool defVal) const
Get the named option as a bool.
Parameters:
name Name of the option to get
defVal Value to use if not found
Definition at line 78 of file ModulesOptions.cpp.
References GetString(), and modules::parser::IsTrue().
Referenced by BaseModule::BaseModule(), FirstCompleteAPGenerator::FirstCompleteAPGenerator(), GetFlag(), PulseViewer::PulseViewer(), TemplateCreator::TemplateCreator(), and TME_Al50_EvdE::TME_Al50_EvdE().
{
    return modules::parser::IsTrue(GetString(name,Form("%d",defVal)));
}
double modules::options::GetDouble (const std::string & name, const std::string & range = "") const
Get the named option as a double, which MUST exist.
Throws module::missing_option if the named option doesn't exist.
Use the range string to specify a validity range. Behind the scenes this uses ROOTs TFormula so any boolean operation is valid. Within the expression, either use the option's name as specified by the first argument to this method, or use "x". If the value fails the validity check, the modules::bad_value exception is thrown
Parameters:
name Name of the option to get
range Optional range for acceptable values
Definition at line 54 of file ModulesOptions.cpp.
{
    return GetOption<double>(name,0,true,range);
}
double modules::options::GetDouble (const std::string & name, double defVal, const std::string & range = "") const
Get the named option as a double.
Use the range string to specify a validity range. Behind the scenes this uses ROOTs TFormula so any boolean operation is valid. Within the expression, either use the option's name as specified by the first argument to this method, or use "x". If the value fails the validity check, the modules::bad_value exception is thrown
Parameters:
name Name of the option to get
defVal Value to use if not found
range Optional range for acceptable values
Definition at line 57 of file ModulesOptions.cpp.
Referenced by FixedWindowMEGenerator::FixedWindowMEGenerator(), GaussFitAPGenerator::GaussFitAPGenerator(), MaxTimeDiffDPGenerator::MaxTimeDiffDPGenerator(), PlotIntegralRatios::PlotIntegralRatios(), PlotTDPs::PlotTDPs(), PulseCandidateFinder::PulseCandidateFinder(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateCreator::TemplateCreator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and GeSpectrum::ThrowIfInputsInsane().
{
    return GetOption<double>(name,defVal,false,range);
}
bool modules::options::GetFlag (const std::string & name) const [inline]
Check if a flag option has been set.
If the option is present with no value return true, else return true if the value gives boolean true
Parameters:
name Name of option to use
Returns:
true if option was set, false if not
Definition at line 243 of file ModulesOptions.h.
References GetBool(), GetOption(), and HasOption().
Referenced by TemplateCreator::ChannelSet::ChannelSet(), ExportPulse::ExportPulse(), PlotTDPs::PlotTDPs(), PulseCandidateFinder::PulseCandidateFinder(), PulseViewer::PulseViewer(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and TVMuonEventGenerator::TVMuonEventGenerator().
{
    return (HasOption(name) && (GetOption(name).empty() || GetBool(name)));
}
int modules::options::GetInt (const std::string & name, const std::string & range = "") const
Get the named option as an int, which MUST exist.
Throws module::missing_option if the named option doesn't exist.
Use the range string to specify a validity range. Behind the scenes this uses ROOTs TFormula so any boolean operation is valid. Within the expression, either use the option's name as specified by the first argument to this method, or use "x". If the value fails the validity check, the modules::bad_value exception is thrown
Parameters:
name Name of the option to get
range Optional range for acceptable values
Definition at line 47 of file ModulesOptions.cpp.
{
    return GetOption<int>(name,0,true,range);
}
int modules::options::GetInt (const std::string & name, int defVal, const std::string & range = "") const
Get the named option as an int.
Use the range string to specify a validity range. Behind the scenes this uses ROOTs TFormula so any boolean operation is valid. Within the expression, either use the option's name as specified by the first argument to this method, or use "x". If the value fails the validity check, the modules::bad_value exception is thrown
Parameters:
name Name of the option to get
defVal Value to use if not found
range Optional range for acceptable values
Definition at line 50 of file ModulesOptions.cpp.
Referenced by PulseCandidateFinder::PulseCandidateFinder(), PulseViewer::PulseViewer(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateCreator::TemplateCreator(), and TemplateFitAPGenerator::TemplateFitAPGenerator().
{
    return GetOption<int>(name,defVal,false,range);
}
bool modules::options::GetNumOptions () const [inline]
Get the number of options managed by this options list.
Definition at line 177 of file ModulesOptions.h.
References fOptions.
Referenced by MakeAnalysedPulses::AddGenerator().
{return fOptions.size();};
template<typename T > T modules::options::GetOption (const std::string & name, const T & defVal, bool complain, const std::string & range = "") const [inline, private]
Get an option using std::stringstream.
Template Parameters:
T return type
Parameters:
name Name of option to get
defVal value to use if no option exists
complain If true, throw an exception if named option doesn't exist
range Expression to check for validity of option value
Definition at line 27 of file ModulesOptions.cpp.
References CheckValid(), and GetOption().
{
    std::stringstream ss(GetOption(key,complain));
    T val=defVal;
    ss>>val;
    if(!range.empty()) CheckValid(key,range.c_str(),val);
    return val;
}
std::string modules::options::GetOption (const std::string & name, bool complain = false) const
Returns the unprocessed value assigned to name.
Parameters:
name Name of the option to get
Definition at line 15 of file ModulesOptions.cpp.
References fModuleName, and fOptions.
Referenced by BaseModule::BaseModule(), GetFlag(), GetOption(), GetString(), GetVectorStringsByDelimiter(), and GetVectorStringsByWhiteSpace().
{
    OptionsList_t::const_iterator it = fOptions.find(key);
    if(it==fOptions.end()){
        if(complain){
            throw missing_option(fModuleName,key);
        }
        return "";
    }
    return it->second;
}
std::string modules::options::GetString (const std::string & name) const
Get the named option as a string.
Trims whitespace from the front and back of the option
Parameters:
name Name of the option to get
Definition at line 61 of file ModulesOptions.cpp.
References GetOption(), and modules::parser::TrimWhiteSpaceBeforeAfter().
{
    std::string ret_val=GetOption(name,true);
    modules::parser::TrimWhiteSpaceBeforeAfter(ret_val);
    return ret_val;
}
std::string modules::options::GetString (const std::string & name, const std::string & defVal) const
Get the named option as a string.
Trims whitespace from the front and back of the option (but not for the default value if the modules file didn't specify anything)
Parameters:
name Name of the option to get
defVal Value to use if not found
Definition at line 67 of file ModulesOptions.cpp.
References GetOption(), and modules::parser::TrimWhiteSpaceBeforeAfter().
Referenced by MakeDetectorPulses::BeforeFirstEntry(), CalcCoarseTimeOffset::CalcCoarseTimeOffset(), GetAlias(), GetBool(), LoadPulses::LoadPulses(), MakeDetectorPulses::MakeDetectorPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTDP_TDiff::PlotTDP_TDiff(), PulseViewer::PulseViewer(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateCreator::TemplateCreator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and GeSpectrum::ThrowIfInputsInsane().
{
    std::string ret_val=GetOption(name,false);
    modules::parser::TrimWhiteSpaceBeforeAfter(ret_val);
    if(ret_val=="") ret_val=defVal;
    return ret_val;
}
int modules::options::GetVectorStringsByDelimiter (const std::string & name, std::vector< std::string > & vect, const char * delim = ":") const
Fill a vector of strings with tokens found in the named option @ Uses strtok so not suitable for multi-threading (if we ever do something like that).
Parameters:
name Name of option to use
vect vector to fill with tokens
delim c-string of chars to use as delimiter
Returns:
Number of tokens pushed in to vect
Definition at line 92 of file ModulesOptions.cpp.
References GetOption().
Referenced by MakeAnalysedPulses::BeforeFirstEntry(), ExportPulse::BeforeFirstEntry(), and TemplateCreator::TemplateCreator().
{
    char line[2048];
    strcpy(line,GetOption(name).c_str());
    char* word = strtok(line,delim);
    int num_tokens=0;
    for(;word != NULL; num_tokens++) {
            //std::cout<<"ModulesOptions:GetVectorStringsByDelimiter() "<<word<<std::endl;
        vect.push_back(word);
        word = strtok(NULL,delim);
    }
    return num_tokens;
}
int modules::options::GetVectorStringsByWhiteSpace (const std::string & name, std::vector< std::string > & vect) const
Fill a vector of strings with whitespace delimited tokens found in the named option.
Parameters:
name Name of option to use
vect vector to fill with tokens
Returns:
Number of tokens pushed in to vect
Definition at line 82 of file ModulesOptions.cpp.
References GetOption().
Referenced by MakeAnalysedPulses::MakeAnalysedPulses(), and MakeDetectorPulses::MakeDetectorPulses().
{
    std::stringstream ss(GetOption(name));
    std::string val;
    int num_tokens=0;
    for(;ss>>val; num_tokens++) {
      vect.push_back(val);
    }
    return num_tokens;
}
bool modules::options::HasOption (const std::string & name) const [inline]
Check if a named option has been set.
Parameters:
name Name of option to use
Returns:
true if option was set, false if not
Definition at line 239 of file ModulesOptions.h.
References fOptions.
Referenced by BaseModule::BaseModule(), MakeDetectorPulses::BeforeFirstEntry(), MakeAnalysedPulses::BeforeFirstEntry(), GetFlag(), PulseCandidateFinder::PulseCandidateFinder(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{
    return fOptions.find(name)!=fOptions.end();
}
int modules::options::MakeIdNumber () [static, private]
Create a unique ID number used for each option.
Definition at line 136 of file ModulesOptions.cpp.
Referenced by options().
{
        static int count=0;
        return count++;
}
void modules::options::SetAlias (const std::string & alias) [inline]
Set the alias option for this module.
Definition at line 196 of file ModulesOptions.h.
References SetOption().
Referenced by modules::reader::AddModule().
{SetOption("alias",alias);};
void modules::options::SetOption (const std::string & key, const std::string & value) [inline]
Set the value of an option.
If a previous value was set, it is replaced by this one
Parameters:
key The name of the option to set
value The new value
Definition at line 232 of file ModulesOptions.h.
References fOptions, and fOrder.
Referenced by TDPGeneratorOptions::AddArgument(), TAPGeneratorOptions::AddArgument(), AddArgument(), modules::reader::AddOption(), FirstCompleteAPGenerator::FirstCompleteAPGenerator(), MakeAnalysedPulses::MakeAnalysedPulses(), and SetAlias().
{
    // if a new key was added, store an iterator in the order list
    OptionsList_t::iterator it = fOptions.find(name);
    fOptions[name]=option;
    if(it==fOptions.end()) fOrder.push_back(fOptions.find(name));
}
std::string modules::options::StringDescription () const
Flatten all options into a string.
Used to provide unique identifiers of a module or generator, based on it's configuration
Definition at line 141 of file ModulesOptions.cpp.
References fOrder.
Referenced by BaseModule::BaseModule(), TVAnalysedPulseGenerator::TVAnalysedPulseGenerator(), and TVDetectorPulseGenerator::TVDetectorPulseGenerator().
{
    const char* key_val_sep="=";
    const char* start_key_val="{";
    const char* stop_key_val="}";
    OptionsOrder_t::const_iterator it;
    std::string description;
    for(it=fOrder.begin();it!=fOrder.end();it++){
        description+=start_key_val;
        description+=(*it)->first;
        if((*it)->second!=""){
            description+=key_val_sep;
            description+=(*it)->second;
        }
        description+=stop_key_val;
    }
    return description;
}
Member Data Documentation
int modules::options::fIdNumber [private]
Definition at line 225 of file ModulesOptions.h.
Referenced by options().
std::string modules::options::fModuleName [protected]
Definition at line 228 of file ModulesOptions.h.
Referenced by TDPGeneratorOptions::AddArgument(), TAPGeneratorOptions::AddArgument(), AddArgument(), CheckValid(), and GetOption().
OptionsList_t modules::options::fOptions [private]
Definition at line 223 of file ModulesOptions.h.
Referenced by AppendToOption(), begin(), end(), GetNumOptions(), GetOption(), HasOption(), and SetOption().
OptionsOrder_t modules::options::fOrder [private]
Definition at line 224 of file ModulesOptions.h.
Referenced by DumpOptions(), SetOption(), and StringDescription().
The documentation for this class was generated from the following files:
rootana/src/framework/ModulesOptions.h
rootana/src/framework/ModulesOptions.cpp