AlcapDAQ: SiR2Target Class Reference
SiR2Target Class Reference
#include <SiR2Target.h>
Public Member Functions
SiR2Target (char *HistogramDirectoryName)
~SiR2Target ()
virtual int ProcessEntry (TGlobalData *gData, TSetupData *gSetup)
int ProcessGenericEntry (TGlobalData *gData, TSetupData *gSetup)
virtual int BeforeFirstEntry (TGlobalData *gData, TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, TSetupData *setup)
const char * GetName () const
Protected Member Functions
bool Debug () const
Protected Attributes
TDirectory * dir
TSetupData * fSetup
Private Attributes
TH1I * fhSpectrum
double ftCoincidence
Detailed Description
Definition at line 12 of file SiR2Target.h.
Constructor & Destructor Documentation
SiR2Target::SiR2Target (char * HistogramDirectoryName)
Definition at line 17 of file SiR2Target.cpp.
References fhSpectrum, and ftCoincidence.
                                                    :
   FillHistBase(HistogramDirectoryName) {
   ftCoincidence = 2000.;
   fhSpectrum = new TH1I("hSiR2Spectrum","Spectrum of Silicon Target", 26000, 0., 26000.);
   gDirectory->cd("/");
 }
SiR2Target::~SiR2Target ()
Definition at line 26 of file SiR2Target.cpp.
{
 }
Member Function Documentation
virtual int FillHistBase::AfterLastEntry (TGlobalData * gData, TSetupData * setup) inline virtual inherited
Reimplemented in TestModule.
Definition at line 39 of file FillHistBase.h.
 {return 0;};
virtual int FillHistBase::BeforeFirstEntry (TGlobalData * gData, TSetupData * setup) inline virtual inherited
Reimplemented in ExportPulse, MakeAnalysedPulses, MakeDetectorPulses, MakeMuonEvents, and TestModule.
Definition at line 38 of file FillHistBase.h.
 {return 0;};
bool FillHistBase::Debug () const inline protected inherited
Definition at line 45 of file FillHistBase.h.
References FillHistBase::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), TestModule::AfterLastEntry(), TestModule::BeforeFirstEntry(), MakeMuonEvents::BeforeFirstEntry(), MakeDetectorPulses::MakeGenerator(), ExportPulse::MakePlot(), and MakeAnalysedPulses::ProcessEntry().
 {return fDebug;};
const char* FillHistBase::GetName () const inline inherited
Definition at line 40 of file FillHistBase.h.
References FillHistBase::dir.
Referenced by DeadTimeGe::ProcessEntry(), PlotAmplitude::ProcessEntry(), and PlotTime::ProcessEntry().
 {return dir->GetName();};
int SiR2Target::ProcessEntry (TGlobalData * gData, TSetupData * gSetup) virtual
Reimplemented from FillHistBase.
Definition at line 29 of file SiR2Target.cpp.
References fhSpectrum, and ftCoincidence.
{
   std::vector<TAnalysedPulse*>* pulses_musc = NULL;
   std::vector<TAnalysedPulse*>* pulses_targ = NULL;
   std::vector<TAnalysedPulse*>* pulses_thick = NULL;
   std::vector<TAnalysedPulse*>* pulses_thin1 = NULL;
   std::vector<TAnalysedPulse*>* pulses_thin2 = NULL;
   std::vector<TAnalysedPulse*>* pulses_thin3 = NULL;
   std::vector<TAnalysedPulse*>* pulses_thin4 = NULL;
   // Find the pulses if they exist
   if (gAnalysedPulseMap.count("muSc") == 0) {
     std::cout << "INFO: No beam counter hits" << std::endl;
     return 0;
   } else if (gAnalysedPulseMap.count("SiR2-S") == 0) {
     std::cout << "INFO: No target hits" << std::endl;
     return 0;
   } else if (gAnalysedPulseMap.count("SiL2-S") == 0) {
     std::cout << "INFO: No thick external hits" << std::endl;
     return 0;
   }
   pulses_musc = &gAnalysedPulseMap.at("muSc");
   pulses_targ = &gAnalysedPulseMap.at("SiR2-S");
   pulses_thick = &gAnalysedPulseMap.at("SiL2-S");
   if (gAnalysedPulseMap.count("SiL1-1-S"))
     pulses_thin1 = &gAnalysedPulseMap.at("SiL1-1-S");
   if (gAnalysedPulseMap.count("SiL1-2-S"))
     pulses_thin2 = &gAnalysedPulseMap.at("SiL1-2-S");
   if (gAnalysedPulseMap.count("SiL1-3-S"))
     pulses_thin3 = &gAnalysedPulseMap.at("SiL1-3-S");
   if (gAnalysedPulseMap.count("SiL1-4-S"))
     pulses_thin4 = &gAnalysedPulseMap.at("SiL1-4-S");
   if(!(pulses_thin1 || pulses_thin2 || pulses_thin3 || pulses_thin4)) {
     std::cout << "INFO: No thin external hits" << std::endl;
     return 0;
   }
   std::vector<TAnalysedPulse*>::iterator iMusc;
   std::vector<TAnalysedPulse*>::iterator iTarg;
   std::vector<TAnalysedPulse*>::iterator iThick;
   std::vector<TAnalysedPulse*>::iterator iThin1;
   std::vector<TAnalysedPulse*>::iterator iThin2;
   std::vector<TAnalysedPulse*>::iterator iThin3;
   std::vector<TAnalysedPulse*>::iterator iThin4;
   iMusc = pulses_musc->begin();
   iTarg = pulses_targ->begin();
   iThick = pulses_thick->begin();
   if (pulses_thin1)
     iThin1 = pulses_thin1->begin();
   if (pulses_thin2)
     iThin2 = pulses_thin2->begin();
   if (pulses_thin3)
     iThin3 = pulses_thin3->begin();
   if (pulses_thin4)
     iThin4 = pulses_thin4->begin();
   double e, t;
   for (; iMusc != pulses_musc->end(); ++iMusc) {
     e = 0.;
     t = (*iMusc)->GetTime();
     // Advance target and external detectors to time window, and
     // then check that we haven't run out of pulses.
     for (; iTarg != pulses_targ->end(); ++iTarg)
       if ((*iTarg)->GetTime() - t >= -ftCoincidence)
         break;
     for (; iThick != pulses_thick->end(); ++iThick)
       if ((*iThick)->GetTime() - t >= -ftCoincidence)
         break;
     if (pulses_thin1)
       for (; iThin1 != pulses_thin1->end(); ++iThin1)
         if ((*iThin1)->GetTime() - t >= -ftCoincidence)
           break;
     if (pulses_thin2)
       for (; iThin2 != pulses_thin2->end(); ++iThin2)
         if ((*iThin2)->GetTime() - t >= -ftCoincidence)
           break;
     if (pulses_thin3)
       for (; iThin3 != pulses_thin3->end(); ++iThin3)
         if ((*iThin3)->GetTime() - t >= -ftCoincidence)
           break;
     if (pulses_thin4)
       for (; iThin4 != pulses_thin4->end(); ++iThin4)
         if ((*iThin4)->GetTime() - t >= -ftCoincidence)
           break;
     // Check we didn't run out of pulses
     if (iTarg == pulses_targ->end()) {
       break;
     } else if ((*iTarg)->GetTime() - t < ftCoincidence) {
       e = (*iTarg)->GetEnergy();
       ++iTarg;
     } else {
       continue;
     }
     if (iThick == pulses_thick->end()) {
       break;
     } else if ((*iThick)->GetTime() - t < ftCoincidence) {
       e += (*iThick)->GetEnergy();
       ++iThick;
     } else {
       continue;
     }
     bool pulse_found = false;
     bool out_of_pulses = true;
     if (pulses_thin1) {
       if (iThin1 != pulses_thin1->end()) {
         out_of_pulses = false;
         if ((*iThin1)->GetTime() - t < ftCoincidence) {
           e += (*iThin1)->GetEnergy();
           ++iThin1;
           pulse_found = true;
         }
       }
     }
     if (pulses_thin2) {
       if (iThin2 != pulses_thin2->end()) {
         out_of_pulses = false;
         if ((*iThin2)->GetTime() - t < ftCoincidence) {
           e += (*iThin2)->GetEnergy();
           ++iThin2;
           pulse_found = true;
         }
       }
     }
     if (pulses_thin3) {
       if (iThin3 != pulses_thin3->end()) {
         out_of_pulses = false;
         if ((*iThin3)->GetTime() - t < ftCoincidence) {
           e += (*iThin3)->GetEnergy();
           ++iThin3;
           pulse_found = true;
         }
       }
     }
     if (pulses_thin4) {
       if (iThin4 != pulses_thin4->end()) {
         out_of_pulses = false;
         if ((*iThin4)->GetTime() - t < ftCoincidence) {
           e += (*iThin4)->GetEnergy();
           ++iThin4;
           pulse_found = true;
         }
       }
     }
     if (out_of_pulses)
       break;
     else if (!pulse_found)
       continue;
     // Fill the energy
     fhSpectrum->Fill(e);
   }
   return 0;
 }
int FillHistBase::ProcessGenericEntry (TGlobalData * gData, TSetupData * gSetup) inherited
Definition at line 24 of file FillHistBase.cpp.
References FillHistBase::dir, and FillHistBase::ProcessEntry().
{
   // This is called by our main routine and would allow later to split into different
   // process routines if we have more than one Tree and hence different tpyes of data input.
   if(dir) dir->cd();
   int ret = ProcessEntry(gData, gSetup);
   gDirectory->cd("/");
   return ret;
 }
Field Documentation
TDirectory* FillHistBase::dir protected inherited
Definition at line 40 of file FillHistBase.h.
Referenced by DeadTimeGe::DeadTimeGe(), ExportPulse::ExportPulse(), FillHistBase::FillHistBase(), FillHistBase::GetName(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmplitude::PlotAmplitude(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTime::PlotTime(), and FillHistBase::ProcessGenericEntry().
TH1I* SiR2Target::fhSpectrum private
Definition at line 18 of file SiR2Target.h.
Referenced by ProcessEntry(), and SiR2Target().
TSetupData* FillHistBase::fSetup protected inherited
Definition at line 44 of file FillHistBase.h.
double SiR2Target::ftCoincidence private
Definition at line 19 of file SiR2Target.h.
Referenced by ProcessEntry(), and SiR2Target().
The documentation for this class was generated from the following files:
analyzer/rootana/src/physics/SiR2Target.h
analyzer/rootana/src/physics/SiR2Target.cpp