AlcapDAQ: CFTimeMBAmpAPGenerator Class Reference
CFTimeMBAmpAPGenerator Class Reference
#include <CFTimeMBAmpAPGenerator.h>
Public Member Functions
CFTimeMBAmpAPGenerator (TAPGeneratorOptions *opts)
virtual ~CFTimeMBAmpAPGenerator ()
virtual int ProcessPulses (const PulseIslandList &, AnalysedPulseList &)
This method is called on each vector of pulses from a MIDAS event.
virtual bool MayDivideTPIs ()
void SetPulseList (PulseIslandList *list)
template<typename TypeOfTAP >
TypeOfTAP * MakeNewTAP (int parent_index) const
The suggested method for constructing a new TAP.
TAnalysedPulse * MakeNewTAP (int parent_index) const
bool Debug () const
IDs::channel GetChannel () const
std::string GetBank () const
const IDs::source & GetSource () const
Get the source id for this generator being used on the current channel.
virtual void CalibratePulses (AnalysedPulseList &theAnalysedPulses) const
Static Public Member Functions
static const char * TapType ()
Protected Member Functions
virtual void SetChannel (const std::string &det)
Set the channel for this generator. Should NOT be called by user code.
Private Attributes
Algorithm::ConstantFractionTime fConstantFractionTime
The algorithms that will be used by this generator.
Algorithm::MaxBinAmplitude fMaxBinAmplitude
Friends
class MakeAnalysedPulses
Detailed Description
Definition at line 10 of file CFTimeMBAmpAPGenerator.h.
Constructor & Destructor Documentation
CFTimeMBAmpAPGenerator::CFTimeMBAmpAPGenerator (TAPGeneratorOptions * opts)
Definition at line 19 of file CFTimeMBAmpAPGenerator.cpp.
                                                                        :
  TVAnalysedPulseGenerator("CFTimeMBAmpAPGenerator",opts),
  fConstantFractionTime(SetupNavigator::Instance()->GetPedestal(GetChannel()),
                        TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        TSetupData::Instance()->GetClockTick(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        opts->GetBool("no_time_shift") ? 0. : SetupNavigator::Instance()->GetCoarseTimeOffset(GetSource()),
                        opts->GetDouble("constant_fraction", -0.10)),
  fMaxBinAmplitude(SetupNavigator::Instance()->GetPedestal(GetChannel()),
                   TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(GetChannel().str()))) {
}
virtual CFTimeMBAmpAPGenerator::~CFTimeMBAmpAPGenerator () [inline, virtual]
Definition at line 14 of file CFTimeMBAmpAPGenerator.h.
{};
Member Function Documentation
void TVAnalysedPulseGenerator::CalibratePulses (AnalysedPulseList & theAnalysedPulses) const [virtual, inherited]
Definition at line 23 of file TVAnalysedPulseGenerator.cpp.
References TVAnalysedPulseGenerator::fAdcToEnergyGain, TVAnalysedPulseGenerator::fAdcToEnergyOffset, and TVAnalysedPulseGenerator::fCanCalibrate.
{
   if(fCanCalibrate){
      for(AnalysedPulseList::iterator i_tap=theAnalysedPulses.begin(); i_tap != theAnalysedPulses.end(); ++i_tap){
         const double amplitude=(*i_tap)->GetAmplitude();
         (*i_tap)->SetEnergy(fAdcToEnergyGain * amplitude + fAdcToEnergyOffset);
      }
   }
}
bool TVAnalysedPulseGenerator::Debug () const [inline, inherited]
Definition at line 77 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fDebug.
Referenced by GaussFitAPGenerator::FitPulse(), TemplateConvolveAPGenerator::ProcessPulses(), and IntegralRatioAPGenerator::ProcessPulses().
{return fDebug;};
std::string TVAnalysedPulseGenerator::GetBank () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 85 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fBankName.
{return fBankName;};
IDs::channel TVAnalysedPulseGenerator::GetChannel () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 81 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), and TVAnalysedPulseGenerator::fSource.
Referenced by FirstCompleteAPGenerator::DrawPulse(), FirstCompleteAPGenerator::FirstCompleteAPGenerator(), IntegralRatioAPGenerator::ProcessPulses(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{return fSource.Channel();};
const IDs::source& TVAnalysedPulseGenerator::GetSource () const [inline, inherited]
Get the source id for this generator being used on the current channel.
Useful for a generator to know the full source much like in the above GetChannel method, but this could also be useful for checking that this generator is the one that made a given TAP in later analysis by comparing this value to that stored in the TAP itself.
Definition at line 94 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fSource.
Referenced by TVAnalysedPulseGenerator::MakeNewTAP(), and IntegralRatioAPGenerator::ProcessPulses().
{return fSource;};
TAnalysedPulse* TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
Definition at line 73 of file TVAnalysedPulseGenerator.h.
{
            return MakeNewTAP<TAnalysedPulse>(parent_index);
        }
template<typename TypeOfTAP > TypeOfTAP * TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
The suggested method for constructing a new TAP.
In the process of constructing TAP, information that isn't immediately obvious how to get needs to be passed to TAP. This method returns a pointer to a TAP construced for you, and all you need to pass it is the TPulseIslandID.
In the case where a generator wants to add extra information to the standard TAP information, we expect people to derive from TAnalysedPulse. If your generator is one of these, then use the template argument to produce the type of TAP you desire. Note that this forces the constructor of the specialised TAP to be the same as for TAnalysedPulse itself.
For example, for to make a specialied analysed pulse called TSpecialAnalysedPulse (original, huh?) you would do:
 TSpecialAnalysedPulse* tsap=MakeNewTAP<TSpecialAnalysedPulse>(parent_index);
Parameters:
[in] parent_index The TPulseIslandID of the TPI being used to make the new TAP.
Template Parameters:
in] TypeOfTAP The type of specialisation of TAnalysedPulse that you want to create.
Definition at line 137 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList, and TVAnalysedPulseGenerator::GetSource().
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), SimpIntAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{
    TypeOfTAP* pulse=NULL;
    TPulseIsland* parent = fPulseList->at(parent_index);
    pulse=new TypeOfTAP(GetSource(),parent_index,parent);
    return pulse;
}
virtual bool CFTimeMBAmpAPGenerator::MayDivideTPIs () [inline, virtual]
Todo:
Document this
Implements TVAnalysedPulseGenerator.
Definition at line 21 of file CFTimeMBAmpAPGenerator.h.
{return true;};
int CFTimeMBAmpAPGenerator::ProcessPulses (const PulseIslandList & pil, AnalysedPulseList & apl) [virtual]
This method is called on each vector of pulses from a MIDAS event.
Parameters:
[in] pil The vector of TPIs to produce TAPs from.
[out] apl The vector of TAPs to append the new TAPs to.
Implements TVAnalysedPulseGenerator.
Definition at line 30 of file CFTimeMBAmpAPGenerator.cpp.
References fConstantFractionTime, fMaxBinAmplitude, TVAnalysedPulseGenerator::MakeNewTAP(), TAnalysedPulse::SetAmplitude(), and TAnalysedPulse::SetTime().
{
  for (unsigned int iTPI = 0; iTPI < pulseList.size(); ++iTPI) {
    TPulseIsland* tpi = pulseList.at(iTPI);
    double time = fConstantFractionTime(tpi);
    double amplitude  = fMaxBinAmplitude(tpi);
    TAnalysedPulse* tap = MakeNewTAP(iTPI);
    tap->SetTime(time);
    tap->SetAmplitude(amplitude);
    analysedList.push_back(tap);
  }
  return 0;
}
virtual void TVAnalysedPulseGenerator::SetChannel (const std::string & det) [inline, protected, virtual, inherited]
Set the channel for this generator. Should NOT be called by user code.
Called by MakeAnalysedPulses to tell this generator what channel it is looking at.
Definition at line 108 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), TVAnalysedPulseGenerator::fBankName, TVAnalysedPulseGenerator::fSource, SetupNavigator::GetBank(), and SetupNavigator::Instance().
Referenced by TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{
           fSource.Channel()=det;
           fBankName= SetupNavigator::Instance()->GetBank(det);
         };
void TVAnalysedPulseGenerator::SetPulseList (PulseIslandList * list) [inline, inherited]
Definition at line 44 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList.
{fPulseList=list;};
static const char* TVAnalysedPulseGenerator::TapType () [inline, static, inherited]
Reimplemented in GaussFitAPGenerator, IntegralRatioAPGenerator, TemplateConvolveAPGenerator, and TemplateFitAPGenerator.
Definition at line 96 of file TVAnalysedPulseGenerator.h.
{return TAnalysedPulse::Class()->GetName();}
Friends And Related Function Documentation
friend class MakeAnalysedPulses [friend, inherited]
Definition at line 101 of file TVAnalysedPulseGenerator.h.
Member Data Documentation
Algorithm::ConstantFractionTime CFTimeMBAmpAPGenerator::fConstantFractionTime [private]
The algorithms that will be used by this generator.
Definition at line 21 of file CFTimeMBAmpAPGenerator.h.
Referenced by ProcessPulses().
Algorithm::MaxBinAmplitude CFTimeMBAmpAPGenerator::fMaxBinAmplitude [private]
Definition at line 28 of file CFTimeMBAmpAPGenerator.h.
Referenced by ProcessPulses().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/CFTimeMBAmpAPGenerator.h
rootana/src/TAP_generators/CFTimeMBAmpAPGenerator.cpp