AlcapDAQ: TMEViewer Class Reference
TMEViewer Class Reference
[Modules]
Testing the TMEs for my Al50 analysis.
#include <TMEViewer.h>
Public Member Functions
TMEViewer (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~TMEViewer ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::vector< IDs::channel > DetectorList
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Private Attributes
long int fNullCount
long int fTdpCount
bool fQuit
DetectorList fDetectors
TCanvas * fCanvas
TApplication * fApp
TH2F * fTDiffPerDetector
Detailed Description
Testing the TMEs for my Al50 analysis.
Author:
Andrew Edmonds
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 28 of file TMEViewer.h.
Member Typedef Documentation
typedef std::vector<IDs::channel> TMEViewer::DetectorList [private]
Definition at line 64 of file TMEViewer.h.
Constructor & Destructor Documentation
TMEViewer::TMEViewer (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 21 of file TMEViewer.cpp.
                                        :
   BaseModule("TMEViewer",opts),fNullCount(0),fTdpCount(0){
}
TMEViewer::~TMEViewer ()
Is anything done in the destructor?
Definition at line 25 of file TMEViewer.cpp.
                     {
}
Member Function Documentation
int TMEViewer::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 158 of file TMEViewer.cpp.
{
  return 0;
}
int TMEViewer::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 28 of file TMEViewer.cpp.
References fApp, fCanvas, fDetectors, fQuit, fTDiffPerDetector, IDs::kMuSc, IDs::kNotApplicable, IDs::kSiL1_1, IDs::kSiL1_2, IDs::kSiL1_3, IDs::kSiL1_4, IDs::kSiL2, IDs::kSiR1_1, IDs::kSiR1_2, IDs::kSiR1_3, IDs::kSiR1_4, and IDs::kSiR2.
{
    using namespace IDs;
    fDetectors.push_back(IDs::channel (kSiL1_1 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiL1_2 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiL1_3 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiL1_4 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiL2   , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiR1_1 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiR1_2 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiR1_3 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiR1_4 , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kSiR2   , kNotApplicable ));
    fDetectors.push_back(IDs::channel (kMuSc   , kNotApplicable ));
    fTDiffPerDetector=new TH2F("hTDiffPerChannel", "TDiff to muSc for each channel per TME",
            5000, -1.2e4,1.2e4,fDetectors.size(),0,fDetectors.size());
    fTDiffPerDetector->SetXTitle("TDiff to central muon (ns)");
    fTDiffPerDetector->SetDrawOption("COLZ");
    fTDiffPerDetector->SetStats(false);
    for(DetectorList::const_iterator i_det=fDetectors.begin();
            i_det!=fDetectors.end(); ++i_det){
        fTDiffPerDetector->GetYaxis()->SetBinLabel(i_det-fDetectors.begin()+1, i_det->str().c_str());
    }
    fQuit = false;
    char** args;
    fApp = new TApplication("app",0,args); //  so we can see the Canvas when we draw it
    fCanvas = new TCanvas("fCanvas", "fCanvas");
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int TMEViewer::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 59 of file TMEViewer.cpp.
References TDetectorPulse::CouldBePaired(), fCanvas, fDetectors, fQuit, fTDiffPerDetector, TDetectorPulse::GetTime(), gMuonEvents, and TDetectorPulse::IsPairedPulse().
{
  // Loop over each TME
  MuonEventList::const_iterator i_tme = gMuonEvents.begin();
  std::string input;
  bool found_interesting_event = false;
  while (!fQuit || !found_interesting_event) {
    found_interesting_event = false;
    fTDiffPerDetector->Reset();
    // Loop through the detecotrs
    for(DetectorList::const_iterator i_det=fDetectors.begin();i_det!=fDetectors.end(); ++i_det){
      // pulses per channel
      int N=0, n;
      double tme_time= (*i_tme)->GetTime();
      int source_index=(*i_tme)->GetSourceIndex(*i_det);
      while(source_index>-1){
        const IDs::source& source=(*i_tme)->GetSource(source_index);
        n=(*i_tme)->NumPulses(source);
        N+=n;
        for(int i=0; i<n; ++i){
          const TDetectorPulse* tdp=(*i_tme)->GetPulse(source,i);
          if(tdp && (tdp->IsPairedPulse() || !tdp->CouldBePaired()) )
            fTDiffPerDetector->Fill(tdp->GetTime() - tme_time, i_det - fDetectors.begin());
        }
        source_index=(*i_tme)->GetSourceIndex(*i_det,source_index+1);
      }
    }
    if (fTDiffPerDetector->GetEntries() > 1 && !(*i_tme)->HasMuonPileup()) {
      std::cout << "TME #" << i_tme - gMuonEvents.begin() << std::endl;
      found_interesting_event = true;
      fTDiffPerDetector->Draw("COLZ");
      fCanvas->Update();
      std::cout << "Press any key to go to next TME (q to quit)" << std::endl;
      std::getline( std::cin, input);
      if (input == "q") {
        fQuit = true;
        break;
      }
    }
    std::cout << "TME #" << i_tme - gMuonEvents.begin() << std::endl;
    ++i_tme;
    if (i_tme == gMuonEvents.end() ) {
      std::cout << "At the end" << std::endl;
      break;
    }
  }
  /*    for(MuonEventList::const_iterator i_tme=gMuonEvents.begin();
            i_tme!=gMuonEvents.end(); ++i_tme){
      // First, check for pile-up in the muSc
      if ( (*i_tme)->HasMuonPileup()) {
        continue;
      }
      double tme_time= (*i_tme)->GetTime(); // this is the same as the muSc time
  */
      /*      int source_index = (*i_tme)->GetSourceIndex(*fMuSc);
      const IDs::source& source=(*i_tme)->GetSource(source_index);
      const TDetectorPulse* muSc_tdp = (*i_tme)->GetPulse(source,0);
      double muSc_time = muSc_tdp->GetTime();
      std::cout << tme_time << " - " << muSc_time << " = " << tme_time - muSc_time << std::endl;
      */
  /*
      // Now loop through the SiL1
      for(DetectorList::const_iterator i_det=fSiL1.begin();
                i_det!=fSiL1.end(); ++i_det){
        // pulses per channel
        int SiL1_source_index=(*i_tme)->GetSourceIndex(*i_det);
        while(SiL1_source_index>-1){
          const IDs::source& SiL1_source=(*i_tme)->GetSource(SiL1_source_index);
          int n_SiL1 = (*i_tme)->NumPulses(SiL1_source);
          //          std::cout << SiL1_source << " has " << n_SiL1 << " pulses" << std::endl;
          for(int i=0; i<n_SiL1; ++i){
            const TDetectorPulse* tdp=(*i_tme)->GetPulse(SiL1_source,i);
            double thin_amplitude = tdp->GetAmplitude();
            // Loop trhough the SiL2 pulses
            int SiL2_source_index=(*i_tme)->GetSourceIndex(*fSiL2);
            const IDs::source& SiL2_source=(*i_tme)->GetSource(SiL2_source_index);
            int n_SiL2 = (*i_tme)->NumPulses(SiL2_source);
            for (int j=0; j<n_SiL2; ++j) {
              const TDetectorPulse* tdp_SiL2=(*i_tme)->GetPulse(SiL2_source,j);
              double thick_amplitude = tdp_SiL2->GetAmplitude();
              std::cout << "(i, j) = (" << i << ", " << j << ") = " << thin_amplitude << ", " << thick_amplitude << std::endl;
              fAvdA_SiL->Fill(thin_amplitude, thin_amplitude+thick_amplitude);
            }
          }
          SiL1_source_index=(*i_tme)->GetSourceIndex(*i_det,SiL1_source_index+1);
        }
      }
    }
*/
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
TApplication* TMEViewer::fApp [private]
Definition at line 68 of file TMEViewer.h.
Referenced by BeforeFirstEntry().
TCanvas* TMEViewer::fCanvas [private]
Definition at line 67 of file TMEViewer.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
DetectorList TMEViewer::fDetectors [private]
Definition at line 65 of file TMEViewer.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
long int TMEViewer::fNullCount [private]
Definition at line 60 of file TMEViewer.h.
bool TMEViewer::fQuit [private]
Definition at line 62 of file TMEViewer.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
TH2F* TMEViewer::fTDiffPerDetector [private]
Definition at line 69 of file TMEViewer.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
long int TMEViewer::fTdpCount [private]
Definition at line 60 of file TMEViewer.h.
The documentation for this class was generated from the following files:
rootana/src/Al50/TMEViewer.h
rootana/src/Al50/TMEViewer.cpp