AlcapDAQ: MultiHistogramFitFCN Class Reference
MultiHistogramFitFCN Class Reference
#include <MultiHistogramFitFCN.h>
Classes
struct HistogramDetails_t
Public Member Functions
MultiHistogramFitFCN (double refine_factor=1)
~MultiHistogramFitFCN ()
void AddTemplate (const TH1D *hist, double time=0)
void SetTemplateHist (int n, const TH1D *hist)
void SetTimeOffset (int n, double offset)
void SetTime (int n, double time)
void SetAmplitude (int n, double amp)
void SetInitialValues (int n, double time_offset, double amp)
void SetPulseHist (const TH1D *pulse)
void SetRefineFactor (int refine_factor)
double & GetAmplitudeScaleFactor (int i) const
double & GetTimeOffset (int i) const
int GetNTemplates () const
double operator() (const std::vector< double > &par) const
Used to calculate the chi-2.
double Up () const
Used for error... somehow?
int GetNDoF ()
Private Types
typedef std::vector
< HistogramDetails_t > TemplateList
Private Member Functions
void UnpackParameters (const std::vector< double > &par) const
void GetHistogramBounds (int safety, int &low_edge, int &high_edge) const
Private Attributes
int fNDoF
double fChi2
double fPedestal
int fRefineFactor
TemplateList fTemplates
const TH1D * fPulseHist
Detailed Description
Definition at line 16 of file MultiHistogramFitFCN.h.
Member Typedef Documentation
typedef std::vector<HistogramDetails_t> MultiHistogramFitFCN::TemplateList [private]
Definition at line 24 of file MultiHistogramFitFCN.h.
Constructor & Destructor Documentation
MultiHistogramFitFCN::MultiHistogramFitFCN (double refine_factor = 1)
Definition at line 7 of file MultiHistogramFitFCN.cpp.
                                                              :
  fRefineFactor(refine_factor){
}
MultiHistogramFitFCN::~MultiHistogramFitFCN ()
Definition at line 11 of file MultiHistogramFitFCN.cpp.
{
}
Member Function Documentation
void MultiHistogramFitFCN::AddTemplate (const TH1D * hist, double time = 0) [inline]
Definition at line 30 of file MultiHistogramFitFCN.h.
References MultiHistogramFitFCN::HistogramDetails_t::fNDoF, MultiHistogramFitFCN::HistogramDetails_t::fTemplateHist, fTemplates, and MultiHistogramFitFCN::HistogramDetails_t::fTimeOffset.
Referenced by TemplateMultiFitter::Init().
{
     HistogramDetails_t tmp;
     tmp.fTemplateHist=hist;
     tmp.fTimeOffset=time;
     tmp.fNDoF=0;
     fTemplates.push_back(tmp);
  }
double& MultiHistogramFitFCN::GetAmplitudeScaleFactor (int i) const [inline]
Definition at line 57 of file MultiHistogramFitFCN.h.
References fTemplates.
{return fTemplates.at(i).fAmplitudeScale;}
void MultiHistogramFitFCN::GetHistogramBounds (int safety, int & low_edge, int & high_edge) const [inline, private]
Definition at line 96 of file MultiHistogramFitFCN.h.
References fPulseHist, and fTemplates.
Referenced by operator()().
{
  // init to pulse histogram
  low_edge=safety;
  high_edge=fPulseHist->GetNbinsX()-safety;
  // for each templatint
  int tpl_start, tpl_stop;
  for(TemplateList::const_iterator i_tpl=fTemplates.begin(); i_tpl!=fTemplates.end(); ++i_tpl){
    tpl_start=i_tpl->fTimeOffset + safety;
    tpl_stop=i_tpl->fTimeOffset+i_tpl->fTemplateHist->GetNbinsX() - safety;
    // find the maximum of all the starts of a template
    if(high_edge>tpl_stop) high_edge=tpl_stop;
    // find the minimum of all the ends of a template
    if(low_edge>tpl_start) low_edge=tpl_start;
  }
}
int MultiHistogramFitFCN::GetNDoF () [inline]
Definition at line 76 of file MultiHistogramFitFCN.h.
References fNDoF.
Referenced by TemplateMultiFitter::FitWithAllTimesFixed(), and TemplateMultiFitter::FitWithOneTimeFree().
{ return fNDoF; }
int MultiHistogramFitFCN::GetNTemplates () const [inline]
Definition at line 59 of file MultiHistogramFitFCN.h.
References fTemplates.
{return fTemplates.size();}
double& MultiHistogramFitFCN::GetTimeOffset (int i) const [inline]
Definition at line 58 of file MultiHistogramFitFCN.h.
References fTemplates.
{return fTemplates.at(i).fTimeOffset;}
double MultiHistogramFitFCN::operator() (const std::vector< double > & par) const
Used to calculate the chi-2.
The return value is the chi squared weighted by errors in fTemplateHist Parameters: 0. Pedestal 1. Amplitude of first pulse 2. Amplitude of second pulse .... N Amplitude of Nth pulse
Definition at line 29 of file MultiHistogramFitFCN.cpp.
References fNDoF, fPulseHist, fRefineFactor, fTemplates, GetHistogramBounds(), and UnpackParameters().
{
  // Chi2 fit with pedestal P, amplitude A, and timing T
  // Warning: The time is truncated to an int, so if there's
  // so if the step size in MINUIT is smalled than 1,
  // Any value of T will probably be seen as minimized, which it
  // almost certainly will not be.
  UnpackParameters(par);
  double chi2 = 0.;
  int safety = 6*fRefineFactor; // remove a few bins from the fit
  int bounds[2];
  GetHistogramBounds(safety,bounds[0], bounds[1]);
  if( (bounds[1]-bounds[0]) < 40*fRefineFactor ) throw Except::SlimlyOverlappingTemplates();
  // Calculate the degrees of freedom ( #data - #fit_params)
  // +1 because we include both ends of the bounds when we loop through
  fNDoF = ((bounds[1] - bounds[0] + 1)/fRefineFactor) - par.size();
  double tpl_height,tpl_error;
  for (int i = bounds[0]+(fRefineFactor/2.0); i <= bounds[1]-(fRefineFactor/2.0); i += fRefineFactor) {
    // calculate the chi^2 based on the centre of the 5 bins to avoid getting
    // abonus from mathcing all 5.  We shift and scale the template so that it
    // matches the pulse.  This is because, when we have a normalised template,
    // we will get the actual amplitude, pedestal and time from the fit and not
    // just offsets
    tpl_height=0;
    tpl_error=0;
    for(TemplateList::const_iterator i_tpl=fTemplates.begin();
         i_tpl!=fTemplates.end(); ++i_tpl){
       tpl_height+=i_tpl->GetHeight(i);
       tpl_error+=i_tpl->fAmplitudeScale*i_tpl->GetError2(i);
    }
    double delta = fPulseHist->GetBinContent(i) - tpl_height;
    chi2 += delta*delta / tpl_error;
  }
  return chi2;
}
void MultiHistogramFitFCN::SetAmplitude (int n, double amp) [inline]
Definition at line 46 of file MultiHistogramFitFCN.h.
References fTemplates.
Referenced by SetInitialValues().
{
    fTemplates.at(n).fAmplitudeScale=amp/fTemplates[n].fTemplateHist->GetMaximum();
  }
void MultiHistogramFitFCN::SetInitialValues (int n, double time_offset, double amp) [inline]
Definition at line 49 of file MultiHistogramFitFCN.h.
References SetAmplitude(), and SetTime().
{
    SetTime(n, time_offset);
    SetAmplitude(n, amp);
  }
void MultiHistogramFitFCN::SetPulseHist (const TH1D * pulse) [inline]
Definition at line 54 of file MultiHistogramFitFCN.h.
References fPulseHist.
Referenced by TemplateMultiFitter::FitWithAllTimesFixed(), and TemplateMultiFitter::FitWithOneTimeFree().
{fPulseHist=pulse;}
void MultiHistogramFitFCN::SetRefineFactor (int refine_factor) [inline]
Definition at line 55 of file MultiHistogramFitFCN.h.
References fRefineFactor.
Referenced by TemplateMultiFitter::Init().
{fRefineFactor = refine_factor;}
void MultiHistogramFitFCN::SetTemplateHist (int n, const TH1D * hist) [inline]
Definition at line 37 of file MultiHistogramFitFCN.h.
References fTemplates.
{
    fTemplates.at(n).fTemplateHist=hist;
  }
void MultiHistogramFitFCN::SetTime (int n, double time) [inline]
Definition at line 43 of file MultiHistogramFitFCN.h.
References fTemplates.
Referenced by SetInitialValues().
{
    fTemplates.at(n).fTimeOffset=time - fTemplates[n].fTemplateHist->GetMaximumBin();
  }
void MultiHistogramFitFCN::SetTimeOffset (int n, double offset) [inline]
Definition at line 40 of file MultiHistogramFitFCN.h.
References fTemplates.
Referenced by TemplateMultiFitter::FitWithAllTimesFixed(), and TemplateMultiFitter::FitWithOneTimeFree().
{
    fTemplates.at(n).fTimeOffset=offset;
  }
void MultiHistogramFitFCN::UnpackParameters (const std::vector< double > & par) const [inline, private]
Definition at line 115 of file MultiHistogramFitFCN.h.
References fPedestal, and fTemplates.
Referenced by operator()().
{
    if ( par.size() < fTemplates.size()+1) return;
    const std::vector<double>::const_iterator begin=par.begin();
    std::vector<double>::const_iterator i_par=begin;
    fPedestal=*i_par;
    for(++i_par ; i_par!=par.end(); ++i_par){
      int n= (i_par-begin-1) ;
      fTemplates.at(n).fAmplitudeScale=*i_par;
    }
  }
double MultiHistogramFitFCN::Up () const [inline]
Used for error... somehow?
Definition at line 74 of file MultiHistogramFitFCN.h.
{return 1.;}
Member Data Documentation
double MultiHistogramFitFCN::fChi2 [mutable, private]
Definition at line 85 of file MultiHistogramFitFCN.h.
int MultiHistogramFitFCN::fNDoF [mutable, private]
record this for TemplateFitter to retrieve later (NB mutable so that it can be set in operator(), which is const)
Definition at line 84 of file MultiHistogramFitFCN.h.
Referenced by GetNDoF(), and operator()().
double MultiHistogramFitFCN::fPedestal [mutable, private]
Definition at line 86 of file MultiHistogramFitFCN.h.
Referenced by UnpackParameters().
const TH1D* MultiHistogramFitFCN::fPulseHist [private]
Definition at line 92 of file MultiHistogramFitFCN.h.
Referenced by GetHistogramBounds(), operator()(), and SetPulseHist().
int MultiHistogramFitFCN::fRefineFactor [private]
Definition at line 88 of file MultiHistogramFitFCN.h.
Referenced by operator()(), and SetRefineFactor().
TemplateList MultiHistogramFitFCN::fTemplates [mutable, private]
Definition at line 90 of file MultiHistogramFitFCN.h.
Referenced by AddTemplate(), GetAmplitudeScaleFactor(), GetHistogramBounds(), GetNTemplates(), GetTimeOffset(), operator()(), SetAmplitude(), SetTemplateHist(), SetTime(), SetTimeOffset(), and UnpackParameters().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/utils/MultiHistogramFitFCN.h
rootana/src/TAP_generators/utils/MultiHistogramFitFCN.cpp