AlcapDAQ: ExportPulse Class Reference
ExportPulse Class Reference
#include <ExportPulse.h>
Classes
struct PulseInfo_t
Public Member Functions
ExportPulse (modules::options *opts)
~ExportPulse ()
void AddToExportList (const std::string &channel, TPulseIslandID pulse_id)
Log a request to draw a given TPI.
void AddToExportList (const TAnalysedPulse *pulse)
Add TAP to draw. Also draws the TAPs parent TPI.
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Static Public Member Functions
static ExportPulse * Instance ()
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef int TPulseIslandID
typedef int EventID_t
typedef std::set< TPulseIslandID > PulseIDList_t
typedef std::map< std::string,
PulseIDList_t > ChannelPulseIDs_t
typedef std::map< EventID_t,
PulseIDList_t > EventPulseIDList_t
typedef std::map< std::string,
EventPulseIDList_t > EventChannelPulseIDs_t
typedef std::set< const
TAnalysedPulse * > TAPList_t
typedef std::map< std::string,
TAPList_t > ChannelTAPs_t
Private Member Functions
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
Plot all pulses that we were asked to draw for this event.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
int DrawTPIs ()
Draw all TPIs requested for this event.
int DrawTAPs ()
Draw all TAPs requested for this event.
int PlotTPI (const TPulseIsland *pulse, const PulseInfo_t &info)
Plot a single TPI.
TH1F * MakeHistTPI (const TPulseIsland *pulse, const std::string &name, int shift=0, int samples=0) const
int PlotTAP (const TAnalysedPulse *pulse, const PulseInfo_t &info) const
Plot a single TAP.
PulseIslandList * GetTPIsFromDetector (std::string bank="")
Get a pointer to the list of TPIs for a given detector.
void SetCurrentPulseID (const TPulseIslandID &id)
void SetCurrentEventNumber (const Long64_t &num)
void SetCurrentDetectorName (const std::string &detector)
Long64_t GetCurrentEventNumber () const
std::string GetCurrentBankName () const
Long64_t GetTotalNumberOfEvents () const
void ClearPulsesToExport ()
void AddToConfigRequestList (EventID_t event_id, const std::string &detector, TPulseIslandID pulse_id)
bool ParseEventRequest (std::string input, std::vector< EventID_t > &event_list)
void ShowGuidance ()
bool ParsePulseRequest (std::string input, std::vector< EventID_t > &list)
bool ParseRequest (std::string input, std::vector< EventID_t > &list, const std::string &type, Long64_t lower_limit, Long64_t upper_limit)
void LoadPulsesRequestedByConfig ()
Private Attributes
bool fGuidanceShown
Long64_t fTotalEvents
double fClockTick
double fTimeShift
ChannelPulseIDs_t fTPIsToPlot
ChannelTAPs_t fTAPsToPlot
EventChannelPulseIDs_t fRequestedByConfig
PulseInfo_t fPulseInfo
const TSetupData * fSetup
modules::options * fOptions
bool fUsePCF
PulseCandidateFinder * fPulseFinder
PulseIslandList fSubPulses
TDirectory * fTPIDirectory
TDirectory * fTAPDirectory
TGlobalData * fGlobalData
Detailed Description
Class to handle drawing of a given pulse.
See also:
https://github.com/alcap-org/AlcapDAQ/wiki/rootana_module_ExportPulses
Definition at line 24 of file ExportPulse.h.
Member Typedef Documentation
typedef std::map<std::string,PulseIDList_t> ExportPulse::ChannelPulseIDs_t [private]
Definition at line 28 of file ExportPulse.h.
typedef std::map<std::string,TAPList_t> ExportPulse::ChannelTAPs_t [private]
Definition at line 32 of file ExportPulse.h.
typedef std::map<std::string,EventPulseIDList_t> ExportPulse::EventChannelPulseIDs_t [private]
Definition at line 30 of file ExportPulse.h.
typedef int ExportPulse::EventID_t [private]
Definition at line 26 of file ExportPulse.h.
typedef std::map<EventID_t,PulseIDList_t> ExportPulse::EventPulseIDList_t [private]
Definition at line 29 of file ExportPulse.h.
typedef std::set<TPulseIslandID> ExportPulse::PulseIDList_t [private]
Definition at line 27 of file ExportPulse.h.
typedef std::set<const TAnalysedPulse*> ExportPulse::TAPList_t [private]
Definition at line 31 of file ExportPulse.h.
typedef int ExportPulse::TPulseIslandID [private]
Definition at line 25 of file ExportPulse.h.
Constructor & Destructor Documentation
ExportPulse::ExportPulse (modules::options * opts)
Definition at line 34 of file ExportPulse.cpp.
References ExportPulse::PulseInfo_t::bankname, ExportPulse::PulseInfo_t::detname, ExportPulse::PulseInfo_t::event, fPulseFinder, fPulseInfo, fTAPDirectory, fTPIDirectory, fUsePCF, BaseModule::GetDirectory(), modules::options::GetFlag(), and ExportPulse::PulseInfo_t::pulseID.
  : BaseModule("ExportPulse",opts),fGuidanceShown(false)
  , fSetup(NULL), fOptions(opts), fPulseFinder(NULL)
{
  fPulseInfo.pulseID=-1;
  fPulseInfo.event=-1;
  fPulseInfo.bankname="";
  fPulseInfo.detname="";
  fUsePCF=opts->GetFlag("run_pulse_finder");
  if(fUsePCF){
      fPulseFinder=new PulseCandidateFinder();
  }
  fTPIDirectory=GetDirectory("TPIs");
  fTAPDirectory=GetDirectory("TAPs");
}
ExportPulse::~ExportPulse ()
Definition at line 54 of file ExportPulse.cpp.
{}
Member Function Documentation
void ExportPulse::AddToConfigRequestList (EventID_t event_id, const std::string & detector, TPulseIslandID pulse_id) [inline, private]
Definition at line 156 of file ExportPulse.h.
References fRequestedByConfig.
Referenced by BeforeFirstEntry().
{
  fRequestedByConfig[detector][event_id].insert(pulse_id);
}
void ExportPulse::AddToExportList (const TAnalysedPulse * pulse) [inline]
Add TAP to draw. Also draws the TAPs parent TPI.
Parameters:
channel Name of channel that produced this pulse
pulse Pulse to be drawn
Definition at line 149 of file ExportPulse.h.
References AddToExportList(), IDs::source::Channel(), BaseModule::Debug(), fTAPsToPlot, TAnalysedPulse::GetParentID(), and TAnalysedPulse::GetSource().
{
  std::string channel=pulse->GetSource().Channel().str();
  if(Debug()) std::cout<<"ExportPulse: Asked to draw a TAP for "<<channel<<std::endl;
  fTAPsToPlot[channel].insert(pulse);
  AddToExportList(channel,pulse->GetParentID());
}
void ExportPulse::AddToExportList (const std::string & channel, TPulseIslandID pulse_id) [inline]
Log a request to draw a given TPI.
Parameters:
channel Name of channel to draw TPI from
pulse_id TPI location in list
Definition at line 145 of file ExportPulse.h.
References fTPIsToPlot.
Referenced by AddToExportList(), PulseViewer::ConsiderDrawing(), LoadPulsesRequestedByConfig(), and GaussFitAPGenerator::ProcessPulses().
{
  fTPIsToPlot[detector].insert(pulse_id);
}
virtual int ExportPulse::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [inline, private, virtual]
Optional method which is called once after the main event loop Can be used to dump a summary or finalise a histogram
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 84 of file ExportPulse.h.
{return 0;};
int ExportPulse::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
ExportPulse uses this method to process the config file for any specifically requested pulses
Implements BaseModule.
Definition at line 59 of file ExportPulse.cpp.
References AddToConfigRequestList(), modules::parser::Constructor_t::before, modules::options::begin(), modules::options::end(), fOptions, fSetup, fTotalEvents, TSetupData::GetBankName(), modules::options::GetVectorStringsByDelimiter(), modules::parser::Constructor_t::inside, Instance(), modules::parser::ParseConstructor(), ParseEventRequest(), ParsePulseRequest(), and ShowGuidance().
{
  fSetup=setup;
  if(!fSetup){
    cout<<"Error: TSetupData passed to ExportPulse is NULL..."<<endl;
    return 1 ;
  }
  fTotalEvents = EventNavigator::Instance().GetInputNEntries();
  if(fOptions){
    int num=0;
    std::vector<std::string> currentList;
    std::vector<EventID_t> event_list;
    std::vector<TPulseIslandID> pulse_list;
    modules::parser::Constructor_t event_pulse_request;
    std::string error_type;
    // Loop over all options
    for(modules::options::OptionsList_t::const_iterator i_opt = fOptions->begin();
        i_opt != fOptions->end(); i_opt++){
      // Continue if option is not "all" and not one of the detector names:
      if( i_opt->first != "all" && fSetup->GetBankName(i_opt->first)=="") continue;
      // Break the list into items
      currentList.clear();
      event_list.clear();
      pulse_list.clear();
      num=fOptions->GetVectorStringsByDelimiter(i_opt->first,currentList);
      if(num<=0) continue; // no options were actually specified
      for(std::vector<std::string>::iterator i_request=currentList.begin();
          i_request!=currentList.end();
          i_request++){
        event_pulse_request=modules::parser::ParseConstructor(*i_request,'(',')');
        // Check things look healthy
        if(event_pulse_request.before=="" )error_type="event";
        else if( event_pulse_request.inside=="")error_type="pulse";
        else if( !ParseEventRequest(event_pulse_request.before, event_list)) error_type="event";
        else if( !ParsePulseRequest(event_pulse_request.inside,pulse_list)) error_type="pulse";
        if(error_type != ""){
          cout<<"Skipping badly formatted "<<error_type<<" specification: "<<*i_request<<endl;
          cout<<"event="<<event_pulse_request.before<<", pulse="<<event_pulse_request.inside<<endl;
          ShowGuidance();
          continue;
        }
        // Everything is ok so add this request to the list
        for(std::vector<EventID_t>::const_iterator i_event=event_list.begin();
            i_event!=event_list.end();
            i_event++){
          for(std::vector<TPulseIslandID>::const_iterator i_pulse=pulse_list.begin();
              i_pulse!=pulse_list.end(); i_pulse++){
            AddToConfigRequestList(*i_event,i_opt->first,*i_pulse);
          }
        }
      }
    }
  }
  return 0;
}
void ExportPulse::ClearPulsesToExport () [private]
Definition at line 381 of file ExportPulse.cpp.
References fTAPsToPlot, and fTPIsToPlot.
Referenced by ProcessEntry().
{
  ChannelPulseIDs_t::iterator i_channel;
  for (i_channel=fTPIsToPlot.begin();i_channel!=fTPIsToPlot.end();i_channel++){
                  i_channel->second.clear();
  }
  fTPIsToPlot.clear();
  fTAPsToPlot.clear();
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
int ExportPulse::DrawTAPs () [private]
Draw all TAPs requested for this event.
Definition at line 142 of file ExportPulse.cpp.
References fPulseInfo, fTAPsToPlot, PlotTAP(), SetCurrentDetectorName(), and SetCurrentPulseID().
Referenced by ProcessEntry().
{
  // Initialise variables that would be used in the loops
  const TAPList_t* requestedPulses;
  // Loop over channel that we've been requested to draw a pulse from
  for(ChannelTAPs_t::const_iterator i_detector=fTAPsToPlot.begin();
      i_detector!=fTAPsToPlot.end();
      i_detector++){
    SetCurrentDetectorName(i_detector->first);
    // Get the pulse list for this channel
    requestedPulses=&(i_detector->second);
    // Loop over every requested pulse for that channel
    for(TAPList_t::const_iterator i_pulse=requestedPulses->begin();
      i_pulse!=requestedPulses->end();
      i_pulse++){
      SetCurrentPulseID((*i_pulse)->GetParentID());
      // Draw the pulse
      PlotTAP(*i_pulse,fPulseInfo);
    }
  }
  return 0;
}
int ExportPulse::DrawTPIs () [private]
Draw all TPIs requested for this event.
Definition at line 171 of file ExportPulse.cpp.
References fPulseInfo, fTPIsToPlot, GetTPIsFromDetector(), PlotTPI(), SetCurrentDetectorName(), and SetCurrentPulseID().
Referenced by ProcessEntry().
{
  // Initialise variables that would be used in the loops
  TPulseIsland* pulse;
  const PulseIDList_t* requestedPulses;
  PulseIslandList* pulseList;
  // Loop over channel that we've been requested to draw a pulse from
  for(ChannelPulseIDs_t::const_iterator i_detector=fTPIsToPlot.begin();
      i_detector!=fTPIsToPlot.end();
      i_detector++){
    SetCurrentDetectorName(i_detector->first);
    // Get the pulse list for this channel
    requestedPulses=&(i_detector->second);
    pulseList=GetTPIsFromDetector();
    // Loop over every requested pulse for that channel
    for(PulseIDList_t::const_iterator i_pulseID=requestedPulses->begin();
        i_pulseID!=requestedPulses->end();
        i_pulseID++){
      // Update the pulse info struct
      SetCurrentPulseID(*i_pulseID);
      // Get the current requested TPI for this channel
      try{
        pulse=pulseList->at(*i_pulseID);
      }
      catch(const std::out_of_range& oor){
        cout<<"Skipping out of range pulse: "<<*i_pulseID<<" on detector '"<<i_detector->first<<endl;
        continue;
      }
      // Draw the pulse
      PlotTPI(pulse,fPulseInfo);
    }
  }
  return 0;
}
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
std::string ExportPulse::GetCurrentBankName () const [inline, private]
Definition at line 107 of file ExportPulse.h.
References ExportPulse::PulseInfo_t::bankname, and fPulseInfo.
Referenced by GetTPIsFromDetector().
{return fPulseInfo.bankname;};
Long64_t ExportPulse::GetCurrentEventNumber () const [inline, private]
Definition at line 106 of file ExportPulse.h.
References ExportPulse::PulseInfo_t::event, and fPulseInfo.
Referenced by LoadPulsesRequestedByConfig().
{return fPulseInfo.event;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
Long64_t ExportPulse::GetTotalNumberOfEvents () const [inline, private]
Definition at line 108 of file ExportPulse.h.
References fTotalEvents.
Referenced by ParseEventRequest(), and ParsePulseRequest().
{return fTotalEvents;};
PulseIslandList * ExportPulse::GetTPIsFromDetector (std::string bank = "") [private]
Get a pointer to the list of TPIs for a given detector.
Definition at line 302 of file ExportPulse.cpp.
References fGlobalData, TGlobalData::fPulseIslandToChannelMap, and GetCurrentBankName().
Referenced by DrawTPIs().
{
  if(bank=="") bank=this->GetCurrentBankName();
  return &fGlobalData->fPulseIslandToChannelMap[bank];
}
ExportPulse * ExportPulse::Instance () [inline, static]
Static method to get the instance of ExportPulse.
Warning:
This method returns NULL if the ExportPulse module is not requested by the user through the modules file. Always check the returned pointer is not NULL before using it:
 if(ExportPulse::Instance()){
    // now we know it's safe, you can do something with this module
     ExportPulse::Instance()->AddToExportList(channel,0);
 }
Returns:
NULL if the module was not requested in the modules file
Definition at line 141 of file ExportPulse.h.
Referenced by PulseViewer::BeforeFirstEntry(), BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), GaussFitAPGenerator::ProcessPulses(), and SetCurrentDetectorName().
{
  return modules::navigator::Instance()->GetModule<ExportPulse>("ExportPulse");
}
void ExportPulse::LoadPulsesRequestedByConfig () [private]
Definition at line 361 of file ExportPulse.cpp.
References AddToExportList(), fRequestedByConfig, and GetCurrentEventNumber().
Referenced by ProcessEntry().
{
  // 7) In Process entry, invoke a method to check if there were requested or a pulse on a channel in this event
  //    and load them into fTPIsToPlot;
  for(EventChannelPulseIDs_t::iterator i_channel=fRequestedByConfig.begin();
      i_channel!=fRequestedByConfig.end(); i_channel++){
    EventPulseIDList_t::iterator i_event=i_channel->second.find(GetCurrentEventNumber());
    if(i_event!=i_channel->second.end()){
      for(PulseIDList_t::const_iterator i_pulse=i_event->second.begin();
          i_pulse!=i_event->second.end(); i_pulse++){
        AddToExportList(i_channel->first,*i_pulse);
      }
    }
  }
  // Check if all channels were requested
}
TH1F * ExportPulse::MakeHistTPI (const TPulseIsland * pulse, const std::string & name, int shift = 0, int samples = 0) const [private]
Definition at line 273 of file ExportPulse.cpp.
References TPulseIsland::GetPulseLength(), and TPulseIsland::GetSamples().
Referenced by PlotTPI().
{
  size_t num_samples = samples? samples: pulse->GetPulseLength();
  double min=0;
  double max= num_samples;
  TH1F* hPulse = new TH1F(name.c_str(), name.c_str(), num_samples,min,max);
  hPulse->SetDirectory(0);
  //double pedestal_error = SetupNavigator::Instance()->GetNoise(IDs::channel(info.detname));
  size_t bin=0;
  for ( size_t i=0;i <(size_t)pulse->GetPulseLength(); ++i) {
    bin=i+1+shift;
    hPulse->SetBinContent(bin, pulse->GetSamples().at(i));
    hPulse->SetBinError(bin, 0);//pedestal_error);
  }
  return hPulse;
}
bool ExportPulse::ParseEventRequest (std::string input, std::vector< EventID_t > & event_list) [private]
Definition at line 322 of file ExportPulse.cpp.
References GetTotalNumberOfEvents(), and ParseRequest().
Referenced by BeforeFirstEntry().
{
  return ParseRequest(input,event_list,"event",0, GetTotalNumberOfEvents());
}
bool ExportPulse::ParsePulseRequest (std::string input, std::vector< EventID_t > & list) [private]
Definition at line 329 of file ExportPulse.cpp.
References GetTotalNumberOfEvents(), and ParseRequest().
Referenced by BeforeFirstEntry().
{
  return ParseRequest(input,list,"pulse",0, GetTotalNumberOfEvents());
}
bool ExportPulse::ParseRequest (std::string input, std::vector< EventID_t > & list, const std::string & type, Long64_t lower_limit, Long64_t upper_limit) [private]
Definition at line 336 of file ExportPulse.cpp.
References modules::parser::GetNumber(), modules::parser::IsNumber(), and modules::parser::RemoveWhitespace().
Referenced by ParseEventRequest(), and ParsePulseRequest().
{
  // Strip all whitespace
  modules::parser::RemoveWhitespace(input);
  // Check if input string contains a number,
  if(modules::parser::IsNumber(input)){
    int event = modules::parser::GetNumber(input);
    if (event >=lower_limit && event < upper_limit ){
      list.push_back(event);
    } else {
      cout<<"Requested "<<type<<", "<<event<<" is out of range."<<endl;
      cout<<"Acceptable values are: ["<<lower_limit<<","<<upper_limit<<"[."<<endl;
      return false;
    }
    return true;
  }
  // Future Ideas:
  // Check if input contains a range,
  // Check if input contains a random request
  return false;
}
int ExportPulse::PlotTAP (const TAnalysedPulse * pulse, const PulseInfo_t & info) const [private]
Plot a single TAP.
Definition at line 293 of file ExportPulse.cpp.
References TAnalysedPulse::Draw(), fTPIDirectory, and ExportPulse::PulseInfo_t::MakeTPIName().
Referenced by DrawTAPs().
{
  std::string hist=info.MakeTPIName();
  TH1F* tpi_hist=NULL;
  fTPIDirectory->GetObject(hist.c_str(),tpi_hist);
  pulse->Draw(tpi_hist);
  return 0;
}
int ExportPulse::PlotTPI (const TPulseIsland * pulse, const PulseInfo_t & info) [private]
Plot a single TPI.
Definition at line 224 of file ExportPulse.cpp.
References ExportPulse::PulseInfo_t::bankname, BaseModule::Debug(), ExportPulse::PulseInfo_t::detname, ExportPulse::PulseInfo_t::event, PulseCandidateFinder::FindPulseCandidates(), fPulseFinder, fSubPulses, fTPIDirectory, fUsePCF, PulseCandidateFinder::GetPulseCandidates(), TPulseIsland::GetPulseLength(), TPulseIsland::GetTimeStamp(), MakeHistTPI(), ExportPulse::PulseInfo_t::MakeTPIName(), and ExportPulse::PulseInfo_t::pulseID.
Referenced by DrawTPIs().
{
  std::string hist=info.MakeTPIName();
  std::stringstream title;
  title << "Pulse " << info.pulseID;
  title << " from event " << info.event;
  title << " on detector " << info.detname;
  title << " (" << info.bankname<<")";
  // Print some stuff if wanted
  if(Debug()){
    cout<<"Plotting "<<title.str()<<"' ["<<hist<<"]"<<endl;
  }
  TH1F* fullPulse=MakeHistTPI(pulse,hist);
  fullPulse->SetDirectory(fTPIDirectory);
  fullPulse->SetTitle(title.str().c_str());
  if(fUsePCF){
      // don't save the original
      fullPulse->SetDirectory(0);
      // make the stack
      THStack* stack=new THStack((hist+"_pulse_candidates").c_str(),title.str().c_str());
      stack->Add(fullPulse);
      fPulseFinder->FindPulseCandidates(pulse);
      fPulseFinder->GetPulseCandidates(fSubPulses);
      for(PulseIslandList::const_iterator i_tpi=fSubPulses.begin(); i_tpi!=fSubPulses.end(); ++i_tpi){
          if((*i_tpi)->GetPulseLength() < 14) continue;
          int shift=(*i_tpi)->GetTimeStamp()-pulse->GetTimeStamp();
          TH1F* sub_pulse=MakeHistTPI(*i_tpi,"sub_pulse",shift,pulse->GetPulseLength());
          sub_pulse->SetFillColor(kMagenta);
          // need to subtract found pulse from full pulse else THStack
          // superposes the two regions
          fullPulse->Add(sub_pulse,-1);
          stack->Add(sub_pulse);
      }
      // Save the stack
      fTPIDirectory->Add(stack);
  }
  return 0;
}
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int ExportPulse::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
Plot all pulses that we were asked to draw for this event.
First loads pulses requested by the config file, then draws all TPIs, then draw all TAPs.
Implements BaseModule.
Definition at line 120 of file ExportPulse.cpp.
References ClearPulsesToExport(), DrawTAPs(), DrawTPIs(), fGlobalData, fTAPDirectory, fTPIDirectory, EventNavigator::Instance(), LoadPulsesRequestedByConfig(), and SetCurrentEventNumber().
{
  // To be corrected once Phill finishes the event navigator
  fGlobalData=gData;
  SetCurrentEventNumber(EventNavigator::Instance().EntryNo());
  // Check if we have any pulses to draw that were requested through the MODULEs file
  LoadPulsesRequestedByConfig();
  fTPIDirectory->cd();
  int ret_val=DrawTPIs();
  if(ret_val!=0) return ret_val;
  fTAPDirectory->cd();
  ret_val=DrawTAPs();
  if(ret_val!=0) return ret_val;
  ClearPulsesToExport();
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
void ExportPulse::SetCurrentDetectorName (const std::string & detector) [inline, private]
Definition at line 160 of file ExportPulse.h.
References ExportPulse::PulseInfo_t::bankname, ExportPulse::PulseInfo_t::detname, fClockTick, fPulseFinder, fPulseInfo, fSetup, fTimeShift, TSetupData::GetBankName(), Instance(), and PulseCandidateFinder::SetChannel().
Referenced by DrawTAPs(), and DrawTPIs().
{
  fPulseInfo.detname=detector;
  fPulseInfo.bankname=fSetup->GetBankName(detector);
  fClockTick = TSetupData::Instance()->GetClockTick(fPulseInfo.bankname);
  fTimeShift = TSetupData::Instance()->GetTimeShift(fPulseInfo.bankname);
  if(fPulseFinder) fPulseFinder->SetChannel(detector);
}
void ExportPulse::SetCurrentEventNumber (const Long64_t & num) [inline, private]
Definition at line 103 of file ExportPulse.h.
References ExportPulse::PulseInfo_t::event, and fPulseInfo.
Referenced by ProcessEntry().
{fPulseInfo.event=num;};
void ExportPulse::SetCurrentPulseID (const TPulseIslandID & id) [inline, private]
Definition at line 102 of file ExportPulse.h.
References fPulseInfo, and ExportPulse::PulseInfo_t::pulseID.
Referenced by DrawTAPs(), and DrawTPIs().
{fPulseInfo.pulseID=id;};
void ExportPulse::ShowGuidance () [private]
Definition at line 309 of file ExportPulse.cpp.
References fGuidanceShown.
Referenced by BeforeFirstEntry().
{
  // Only show guidance once
  if(fGuidanceShown) return;
  fGuidanceShown=true;
  cout<<"Requests to draw a pulse should be formatted as event(pulse),"<<endl;
  cout<<" where event and pulse are the numbers of each event and pulse you wish to draw"<<endl;
  //", a range (specified by A-Z, where A and Z are the first and last value of the range),"
  //" or a number of random events to select (specified by ~N where N is the number of events)";
}
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
double ExportPulse::fClockTick [private]
Definition at line 123 of file ExportPulse.h.
Referenced by SetCurrentDetectorName().
TGlobalData* ExportPulse::fGlobalData [private]
Definition at line 137 of file ExportPulse.h.
Referenced by GetTPIsFromDetector(), and ProcessEntry().
bool ExportPulse::fGuidanceShown [private]
Definition at line 121 of file ExportPulse.h.
Referenced by ShowGuidance().
modules::options* ExportPulse::fOptions [private]
Definition at line 130 of file ExportPulse.h.
Referenced by BeforeFirstEntry().
PulseCandidateFinder* ExportPulse::fPulseFinder [private]
Definition at line 132 of file ExportPulse.h.
Referenced by ExportPulse(), PlotTPI(), and SetCurrentDetectorName().
PulseInfo_t ExportPulse::fPulseInfo [private]
Definition at line 128 of file ExportPulse.h.
Referenced by DrawTAPs(), DrawTPIs(), ExportPulse(), GetCurrentBankName(), GetCurrentEventNumber(), SetCurrentDetectorName(), SetCurrentEventNumber(), and SetCurrentPulseID().
EventChannelPulseIDs_t ExportPulse::fRequestedByConfig [private]
Definition at line 127 of file ExportPulse.h.
Referenced by AddToConfigRequestList(), and LoadPulsesRequestedByConfig().
const TSetupData* ExportPulse::fSetup [private]
Reimplemented from BaseModule.
Definition at line 129 of file ExportPulse.h.
Referenced by BeforeFirstEntry(), and SetCurrentDetectorName().
PulseIslandList ExportPulse::fSubPulses [private]
Definition at line 133 of file ExportPulse.h.
Referenced by PlotTPI().
TDirectory* ExportPulse::fTAPDirectory [private]
Definition at line 135 of file ExportPulse.h.
Referenced by ExportPulse(), and ProcessEntry().
ChannelTAPs_t ExportPulse::fTAPsToPlot [private]
Definition at line 126 of file ExportPulse.h.
Referenced by AddToExportList(), ClearPulsesToExport(), and DrawTAPs().
double ExportPulse::fTimeShift [private]
Definition at line 124 of file ExportPulse.h.
Referenced by SetCurrentDetectorName().
Long64_t ExportPulse::fTotalEvents [private]
Definition at line 122 of file ExportPulse.h.
Referenced by BeforeFirstEntry(), and GetTotalNumberOfEvents().
TDirectory* ExportPulse::fTPIDirectory [private]
Definition at line 134 of file ExportPulse.h.
Referenced by ExportPulse(), PlotTAP(), PlotTPI(), and ProcessEntry().
ChannelPulseIDs_t ExportPulse::fTPIsToPlot [private]
Definition at line 125 of file ExportPulse.h.
Referenced by AddToExportList(), ClearPulsesToExport(), and DrawTPIs().
bool ExportPulse::fUsePCF [private]
Definition at line 131 of file ExportPulse.h.
Referenced by ExportPulse(), and PlotTPI().
The documentation for this class was generated from the following files:
rootana/src/plotters/ExportPulse.h
rootana/src/plotters/ExportPulse.cpp