AlcapDAQ: TAPGeneratorOptions Class Reference
TAPGeneratorOptions Class Reference
#include <TAPGeneratorOptions.h>
Public Types
typedef std::map< std::string,
std::string > OptionsList_t
typedef std::vector
< OptionsList_t::iterator > OptionsOrder_t
Public Member Functions
TAPGeneratorOptions (const std::string &name)
~TAPGeneratorOptions ()
void SetOption (const std::string &name, const std::string &option)
bool AppendToOption (const std::string &name, const std::string &option)
void AddArgument (const int &number, const std::string &option)
int GetInt (const std::string &, int defVal=-1) const
double GetDouble (const std::string &, double defVal=1.) const
std::string GetString (const std::string &, const std::string &defVal="") const
bool GetBool (const std::string &, bool defVal=false) const
int GetVectorStringsByWhiteSpace (const std::string &, std::vector< std::string > &vect) const
int GetVectorStringsByDelimiter (const std::string &, std::vector< std::string > &vect, const char *delim=":") const
int GetVectorStrings (const std::string &name, std::vector< std::string > &vect) const
bool HasOption (const std::string &) const
bool GetNumOptions () const
std::string GetOption (const std::string &) const
OptionsList_t::const_iterator begin () const
OptionsList_t::const_iterator end () const
void DumpOptions (const std::string &prefix=" ") const
Detailed Description
Class to handle options for a TAP generator Inherite from the options class for modules to share the implementation and interface.
Definition at line 9 of file TAPGeneratorOptions.h.
Member Typedef Documentation
typedef std::map<std::string,std::string> modules::options::OptionsList_t inherited
Definition at line 14 of file ModulesOptions.h.
typedef std::vector<OptionsList_t::iterator> modules::options::OptionsOrder_t inherited
Definition at line 15 of file ModulesOptions.h.
Constructor & Destructor Documentation
TAPGeneratorOptions::TAPGeneratorOptions (const std::string & name) inline
Definition at line 11 of file TAPGeneratorOptions.h.
                                                   :
                 modules::options(name){};
TAPGeneratorOptions::~TAPGeneratorOptions () inline
Definition at line 13 of file TAPGeneratorOptions.h.
 {};
Member Function Documentation
void modules::options::AddArgument (const int & number, const std::string & option) inherited
Definition at line 67 of file ModulesOptions.cpp.
References TemplateFactory< BaseModule, OptionsType >::GetArgumentName(), modules::factory::Instance(), and modules::options::SetOption().
Referenced by modules::reader::AddModule(), and MakeAnalysedPulses::ParseGeneratorList().
{
     // Get the name of this argument
     std::string name = modules::factory::Instance()->GetArgumentName(fModuleName,number);
     // Set the value of the corresponding option
     modules::options::SetOption(name,option);
 }
bool modules::options::AppendToOption (const std::string & name, const std::string & option) inherited
Definition at line 74 of file ModulesOptions.cpp.
Referenced by modules::reader::AddOption().
{
     // Get the option
     OptionsList_t::iterator it= fOptions.find(name);
     // If no option exists return false
     if(it==fOptions.end()) return false;
     // Add the value to it
     it->second+=" : "+option;
     return true;
 }
OptionsList_t::const_iterator modules::options::begin () const inline inherited
Definition at line 42 of file ModulesOptions.h.
References modules::options::fOptions.
Referenced by ExportPulse::BeforeFirstEntry().
 {return fOptions.begin();};
void modules::options::DumpOptions (const std::string & prefix = " ") const inherited
Definition at line 55 of file ModulesOptions.cpp.
Referenced by load_config_file(), and modules::navigator::LoadConfigFile().
{
     //std::cout<<"key  "<<" = "<<" value "<<std::endl;
     OptionsOrder_t::const_iterator it;
     for(it=fOrder.begin();it!=fOrder.end();it++){
         std::cout<<prefix<<(*it)->first;
         if((*it)->second!=""){
            std::cout<<" = "<<(*it)->second;
         }
         std::cout<<std::endl;
     }
 }
OptionsList_t::const_iterator modules::options::end () const inline inherited
Definition at line 44 of file ModulesOptions.h.
References modules::options::fOptions.
Referenced by ExportPulse::BeforeFirstEntry().
 {return fOptions.end();};
bool modules::options::GetBool (const std::string & name, bool defVal = false) const inherited
Definition at line 32 of file ModulesOptions.cpp.
{
     return GetOption<bool>(name,defVal);
 }
double modules::options::GetDouble (const std::string & name, double defVal = 1.) const inherited
Definition at line 24 of file ModulesOptions.cpp.
Referenced by TestModule::TestModule().
{
     return GetOption<double>(name,defVal);
 }
int modules::options::GetInt (const std::string & name, int defVal = -1) const inherited
Definition at line 20 of file ModulesOptions.cpp.
{
     return GetOption<int>(name,defVal);
 }
bool modules::options::GetNumOptions () const inline inherited
Definition at line 39 of file ModulesOptions.h.
References modules::options::fOptions.
Referenced by MakeAnalysedPulses::AddGenerator().
 {return fOptions.size();};
std::string modules::options::GetOption (const std::string & key) const inherited
Definition at line 7 of file ModulesOptions.cpp.
References modules::options::fOptions, and value.
{
     OptionsList_t::const_iterator it = fOptions.find(key);
     std::string value= it!=fOptions.end()? it->second : "";
     return value;
 }
std::string modules::options::GetString (const std::string & name, const std::string & defVal = "") const inherited
Definition at line 28 of file ModulesOptions.cpp.
Referenced by MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeDetectorPulses(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
{
     return GetOption<std::string>(name,defVal);
 }
int modules::options::GetVectorStrings (const std::string & name, std::vector< std::string > & vect) const inline inherited
Definition at line 34 of file ModulesOptions.h.
References modules::options::GetVectorStringsByWhiteSpace().
Referenced by MakeAnalysedPulses::MakeAnalysedPulses().
{
              return GetVectorStringsByWhiteSpace(name,vect);
         };
int modules::options::GetVectorStringsByDelimiter (const std::string & name, std::vector< std::string > & vect, const char * delim = ":") const inherited
Definition at line 43 of file ModulesOptions.cpp.
Referenced by ExportPulse::BeforeFirstEntry(), and MakeAnalysedPulses::ParseGeneratorList().
{
     char line[2048];
     strcpy(line,GetOption(name).c_str());
     char* word = strtok(line,delim);
     while(word != NULL){
             //std::cout<<"ModulesOptions:GetVectorStringsByDelimiter() "<<word<<std::endl;
         vect.push_back(word);
         word = strtok(NULL,delim);
     }
     return vect.size();
 }
int modules::options::GetVectorStringsByWhiteSpace (const std::string & name, std::vector< std::string > & vect) const inherited
Definition at line 36 of file ModulesOptions.cpp.
Referenced by modules::options::GetVectorStrings().
{
     std::stringstream ss(GetOption(name));
     std::string val;
     while(ss>>val) vect.push_back(val);
     return vect.size();
 }
bool modules::options::HasOption (const std::string & name) const inline inherited
Definition at line 67 of file ModulesOptions.h.
Referenced by MakeAnalysedPulses::BeforeFirstEntry(), FillHistBase::FillHistBase(), TVAnalysedPulseGenerator::TVAnalysedPulseGenerator(), and TVMuonEventGenerator::TVMuonEventGenerator().
{
     return fOptions.find(name)!=fOptions.end();
 }
void modules::options::SetOption (const std::string & name, const std::string & option) inline inherited
Definition at line 61 of file ModulesOptions.h.
References modules::options::fOptions, and modules::options::fOrder.
Referenced by modules::options::AddArgument(), modules::reader::AddOption(), and MakeMuonEvents::BeforeFirstEntry().
{
     std::pair<OptionsList_t::iterator, bool> ret = fOptions.insert(make_pair(name,option));
     // if a new key was added, store an iterator in the order list
     if(ret.second) fOrder.push_back(ret.first);
 }
The documentation for this class was generated from the following file:
analyzer/rootana/src/TAP_generators/TAPGeneratorOptions.h