AlcapDAQ: IntegralRatioAPGenerator Class Reference
IntegralRatioAPGenerator Class Reference
#include <IntegralRatioAPGenerator.h>
Public Member Functions
IntegralRatioAPGenerator (TAPGeneratorOptions *opts)
virtual ~IntegralRatioAPGenerator ()
virtual int ProcessPulses (const PulseIslandList &, AnalysedPulseList &)
This method is called on each vector of pulses from a MIDAS event.
virtual bool MayDivideTPIs ()
void SetPulseList (PulseIslandList *list)
template<typename TypeOfTAP >
TypeOfTAP * MakeNewTAP (int parent_index) const
The suggested method for constructing a new TAP.
TAnalysedPulse * MakeNewTAP (int parent_index) const
bool Debug () const
IDs::channel GetChannel () const
std::string GetBank () const
const IDs::source & GetSource () const
Get the source id for this generator being used on the current channel.
virtual void CalibratePulses (AnalysedPulseList &theAnalysedPulses) const
Static Public Member Functions
static const char * TapType ()
Protected Member Functions
virtual void SetChannel (const std::string &det)
Set the channel for this generator. Should NOT be called by user code.
Private Attributes
bool fStartTailAsFraction
double fStartIntegral
double fStopIntegral
double fStartTail
double fPedestal
double fPolarity
Algorithm::IntegralRatio fIntegralRatioAlgo
const Algorithm::MaxBinAmplitude fMaxBinAmplitude
Friends
class MakeAnalysedPulses
Detailed Description
Definition at line 9 of file IntegralRatioAPGenerator.h.
Constructor & Destructor Documentation
IntegralRatioAPGenerator::IntegralRatioAPGenerator (TAPGeneratorOptions * opts)
Definition at line 15 of file IntegralRatioAPGenerator.cpp.
                                                                           :
    TVAnalysedPulseGenerator("IntegralRatio",opts),
        fStartTailAsFraction(opts->GetBool("start_tail_as_fraction",false)),
        fStartIntegral(opts->GetInt("start_int","x>=0")),
        fStopIntegral(opts->GetInt("stop_int","x>=0")),
        fStartTail(opts->GetDouble("start_tail",
                                  fStartTailAsFraction?
                                  "x<1 && x>0":
                                  Form("x>%g",fStartIntegral))),
        //fPedestal(GetChannel().isFast()?900:2728),
        fPedestal(SetupNavigator::Instance()->GetPedestal(GetChannel())),
        //fPolarity(GetChannel().isFast()?1:-1),
        fPolarity(TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(GetChannel().str()))),
        fIntegralRatioAlgo( fStartIntegral, fStartTail, fStopIntegral,  fPolarity,fPedestal),
        fMaxBinAmplitude(fPedestal,fPolarity)
{
}
IntegralRatioAPGenerator::~IntegralRatioAPGenerator () [virtual]
Definition at line 33 of file IntegralRatioAPGenerator.cpp.
{}
Member Function Documentation
void TVAnalysedPulseGenerator::CalibratePulses (AnalysedPulseList & theAnalysedPulses) const [virtual, inherited]
Definition at line 23 of file TVAnalysedPulseGenerator.cpp.
References TVAnalysedPulseGenerator::fAdcToEnergyGain, TVAnalysedPulseGenerator::fAdcToEnergyOffset, and TVAnalysedPulseGenerator::fCanCalibrate.
{
   if(fCanCalibrate){
      for(AnalysedPulseList::iterator i_tap=theAnalysedPulses.begin(); i_tap != theAnalysedPulses.end(); ++i_tap){
         const double amplitude=(*i_tap)->GetAmplitude();
         (*i_tap)->SetEnergy(fAdcToEnergyGain * amplitude + fAdcToEnergyOffset);
      }
   }
}
bool TVAnalysedPulseGenerator::Debug () const [inline, inherited]
Definition at line 77 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fDebug.
Referenced by GaussFitAPGenerator::FitPulse(), TemplateConvolveAPGenerator::ProcessPulses(), and ProcessPulses().
{return fDebug;};
std::string TVAnalysedPulseGenerator::GetBank () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 85 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fBankName.
{return fBankName;};
IDs::channel TVAnalysedPulseGenerator::GetChannel () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 81 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), and TVAnalysedPulseGenerator::fSource.
Referenced by FirstCompleteAPGenerator::DrawPulse(), FirstCompleteAPGenerator::FirstCompleteAPGenerator(), ProcessPulses(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{return fSource.Channel();};
const IDs::source& TVAnalysedPulseGenerator::GetSource () const [inline, inherited]
Get the source id for this generator being used on the current channel.
Useful for a generator to know the full source much like in the above GetChannel method, but this could also be useful for checking that this generator is the one that made a given TAP in later analysis by comparing this value to that stored in the TAP itself.
Definition at line 94 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fSource.
Referenced by TVAnalysedPulseGenerator::MakeNewTAP(), and ProcessPulses().
{return fSource;};
TAnalysedPulse* TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
Definition at line 73 of file TVAnalysedPulseGenerator.h.
{
            return MakeNewTAP<TAnalysedPulse>(parent_index);
        }
template<typename TypeOfTAP > TypeOfTAP * TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
The suggested method for constructing a new TAP.
In the process of constructing TAP, information that isn't immediately obvious how to get needs to be passed to TAP. This method returns a pointer to a TAP construced for you, and all you need to pass it is the TPulseIslandID.
In the case where a generator wants to add extra information to the standard TAP information, we expect people to derive from TAnalysedPulse. If your generator is one of these, then use the template argument to produce the type of TAP you desire. Note that this forces the constructor of the specialised TAP to be the same as for TAnalysedPulse itself.
For example, for to make a specialied analysed pulse called TSpecialAnalysedPulse (original, huh?) you would do:
 TSpecialAnalysedPulse* tsap=MakeNewTAP<TSpecialAnalysedPulse>(parent_index);
Parameters:
[in] parent_index The TPulseIslandID of the TPI being used to make the new TAP.
Template Parameters:
in] TypeOfTAP The type of specialisation of TAnalysedPulse that you want to create.
Definition at line 137 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList, and TVAnalysedPulseGenerator::GetSource().
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), SimpIntAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), CFTimeMBAmpAPGenerator::ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{
    TypeOfTAP* pulse=NULL;
    TPulseIsland* parent = fPulseList->at(parent_index);
    pulse=new TypeOfTAP(GetSource(),parent_index,parent);
    return pulse;
}
virtual bool IntegralRatioAPGenerator::MayDivideTPIs () [inline, virtual]
Todo:
Document this
Implements TVAnalysedPulseGenerator.
Definition at line 22 of file IntegralRatioAPGenerator.h.
{return false;};
int IntegralRatioAPGenerator::ProcessPulses (const PulseIslandList & pil, AnalysedPulseList & apl) [virtual]
This method is called on each vector of pulses from a MIDAS event.
Parameters:
[in] pil The vector of TPIs to produce TAPs from.
[out] apl The vector of TAPs to append the new TAPs to.
Implements TVAnalysedPulseGenerator.
Definition at line 35 of file IntegralRatioAPGenerator.cpp.
References TVAnalysedPulseGenerator::Debug(), fIntegralRatioAlgo, fMaxBinAmplitude, fStartTail, fStartTailAsFraction, Algorithm::MaxBinAmplitude::GetAmplitude(), TVAnalysedPulseGenerator::GetChannel(), Algorithm::IntegralRatio::GetRatio(), TVAnalysedPulseGenerator::GetSource(), Algorithm::IntegralRatio::GetTail(), Algorithm::MaxBinAmplitude::GetTime(), Algorithm::IntegralRatio::GetTotal(), TAnalysedPulse::SetAmplitude(), TAnalysedPulse::SetIntegral(), TIntegralRatioAnalysedPulse::SetIntegralRatio(), TIntegralRatioAnalysedPulse::SetIntegralSmall(), Algorithm::IntegralRatio::SetPedestalToMinimum(), Algorithm::IntegralRatio::SetTailStart(), TAnalysedPulse::SetTime(), IDs::channel::str(), and IDs::source::str().
{
    // Loop over all the TPIs given to us
    int start_tail;
    TIntegralRatioAnalysedPulse* tap;
    for (PulseIslandList::const_iterator tpi=pulseList.begin();
            tpi!=pulseList.end(); tpi++){
        if(fStartTailAsFraction){
           start_tail=fStartTail*(*tpi)->GetPulseLength();
           fIntegralRatioAlgo.SetTailStart(start_tail);
        }
        // Analyse each TPI
        try{
            fIntegralRatioAlgo.SetPedestalToMinimum(*tpi);
            fIntegralRatioAlgo(*tpi);
        }catch(std::out_of_range& e){
            continue;
        }
        fMaxBinAmplitude(*tpi);
        // Now that we've found the information we were looking for make a TAP to
        // hold it.  This method makes a TAP and sets the parent TPI info.  It needs
        // the index of the parent TPI in the container as an argument
        tap = MakeNewTAP<TIntegralRatioAnalysedPulse>(tpi-pulseList.begin());
        tap->SetIntegral(fIntegralRatioAlgo.GetTotal());
        tap->SetIntegralSmall(fIntegralRatioAlgo.GetTail());
        tap->SetIntegralRatio(fIntegralRatioAlgo.GetRatio());
        tap->SetAmplitude(fMaxBinAmplitude.GetAmplitude());
        tap->SetTime(fMaxBinAmplitude.GetTime());
        // Finally add the new TAP to the output list
        analysedList.push_back(tap);
    }
    // Generators have a Debug method similar to modules
    if(Debug()){
        // They also have a unique ID, retrievable by GetSource and
        // a GetChannel method to get the ID of just the channel
        cout<<"Now running source: "<<GetSource().str()<<" which looks for TAPs on "
            "channel: "<<GetChannel().str()<<'\n';
    }
    // returning 0 tells the caller that we were successful, return non-zero if not
    return 0;
}
virtual void TVAnalysedPulseGenerator::SetChannel (const std::string & det) [inline, protected, virtual, inherited]
Set the channel for this generator. Should NOT be called by user code.
Called by MakeAnalysedPulses to tell this generator what channel it is looking at.
Definition at line 108 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), TVAnalysedPulseGenerator::fBankName, TVAnalysedPulseGenerator::fSource, SetupNavigator::GetBank(), and SetupNavigator::Instance().
Referenced by TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{
           fSource.Channel()=det;
           fBankName= SetupNavigator::Instance()->GetBank(det);
         };
void TVAnalysedPulseGenerator::SetPulseList (PulseIslandList * list) [inline, inherited]
Definition at line 44 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList.
{fPulseList=list;};
const char * IntegralRatioAPGenerator::TapType () [static]
Reimplemented from TVAnalysedPulseGenerator.
Definition at line 85 of file IntegralRatioAPGenerator.cpp.
{
    return TIntegralRatioAnalysedPulse::Class()->GetName();
}
Friends And Related Function Documentation
friend class MakeAnalysedPulses [friend, inherited]
Definition at line 101 of file TVAnalysedPulseGenerator.h.
Member Data Documentation
Algorithm::IntegralRatio IntegralRatioAPGenerator::fIntegralRatioAlgo [private]
Definition at line 30 of file IntegralRatioAPGenerator.h.
Referenced by ProcessPulses().
const Algorithm::MaxBinAmplitude IntegralRatioAPGenerator::fMaxBinAmplitude [private]
Definition at line 31 of file IntegralRatioAPGenerator.h.
Referenced by ProcessPulses().
double IntegralRatioAPGenerator::fPedestal [private]
Definition at line 28 of file IntegralRatioAPGenerator.h.
double IntegralRatioAPGenerator::fPolarity [private]
Definition at line 29 of file IntegralRatioAPGenerator.h.
double IntegralRatioAPGenerator::fStartIntegral [private]
Definition at line 25 of file IntegralRatioAPGenerator.h.
double IntegralRatioAPGenerator::fStartTail [private]
Definition at line 27 of file IntegralRatioAPGenerator.h.
Referenced by ProcessPulses().
bool IntegralRatioAPGenerator::fStartTailAsFraction [private]
Definition at line 22 of file IntegralRatioAPGenerator.h.
Referenced by ProcessPulses().
double IntegralRatioAPGenerator::fStopIntegral [private]
Definition at line 26 of file IntegralRatioAPGenerator.h.
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/IntegralRatioAPGenerator.h
rootana/src/TAP_generators/IntegralRatioAPGenerator.cpp