AlcapDAQ: SimpIntAPGenerator Class Reference
SimpIntAPGenerator Class Reference
#include <SimpIntAPGenerator.h>
Public Member Functions
SimpIntAPGenerator (TAPGeneratorOptions *opts)
virtual ~SimpIntAPGenerator ()
void SetBankInfo (std::string bankname)
virtual int ProcessPulses (const PulseIslandList &, AnalysedPulseList &)
This method is called on each vector of pulses from a MIDAS event.
virtual bool MayDivideTPIs ()
void SetPulseList (PulseIslandList *list)
template<typename TypeOfTAP >
TypeOfTAP * MakeNewTAP (int parent_index) const
The suggested method for constructing a new TAP.
TAnalysedPulse * MakeNewTAP (int parent_index) const
bool Debug () const
IDs::channel GetChannel () const
IDs::source GetSource () const
Get the source id for this generator being used on the current channel.
Private Attributes
std::string fBankname
std::string fDetname
double fPedestal
double fECalibSlope
double fECalibOffset
int fTriggerPolarity
TSetupData * fSetup
Detailed Description
Definition at line 8 of file SimpIntAPGenerator.h.
Constructor & Destructor Documentation
SimpIntAPGenerator::SimpIntAPGenerator (TAPGeneratorOptions * opts) [inline]
Definition at line 11 of file SimpIntAPGenerator.h.
                                               :
  TVAnalysedPulseGenerator("SimpInt", opts),fSetup(TSetupData::Instance()){};
  virtual ~SimpIntAPGenerator(){};
virtual SimpIntAPGenerator::~SimpIntAPGenerator () [inline, virtual]
Definition at line 13 of file SimpIntAPGenerator.h.
{};
Member Function Documentation
bool TVAnalysedPulseGenerator::Debug () const [inline, inherited]
Definition at line 79 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fDebug.
Referenced by GaussFitAPGenerator::FitPulse().
{return fDebug;};
IDs::channel TVAnalysedPulseGenerator::GetChannel () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 83 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), and TVAnalysedPulseGenerator::fSource.
{return fSource.Channel();};
IDs::source TVAnalysedPulseGenerator::GetSource () const [inline, inherited]
Get the source id for this generator being used on the current channel.
Useful for a generator to know the full source much like in the above GetChannel method, but this could also be useful for checking that this generator is the one that made a given TAP in later analysis by comparing this value to that stored in the TAP itself.
Definition at line 92 of file TVAnalysedPulseGenerator.h.
Referenced by TVAnalysedPulseGenerator::MakeNewTAP().
{return fSource;};
TAnalysedPulse* TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
Definition at line 75 of file TVAnalysedPulseGenerator.h.
{
            return MakeNewTAP<TAnalysedPulse>(parent_index);
        }
template<typename TypeOfTAP > TypeOfTAP * TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
The suggested method for constructing a new TAP.
In the process of constructing TAP, information that isn't immediately obvious how to get needs to be passed to TAP. This method returns a pointer to a TAP construced for you, and all you need to pass it is the TPulseIslandID.
In the case where a generator wants to add extra information to the standard TAP information, we expect people to derive from TAnalysedPulse. If your generator is one of these, then use the template argument to produce the type of TAP you desire. Note that this forces the constructor of the specialised TAP to be the same as for TAnalysedPulse itself.
For example, for to make a specialied analysed pulse called TSpecialAnalysedPulse (original, huh?) you would do:
 TSpecialAnalysedPulse* tsap=MakeNewTAP<TSpecialAnalysedPulse>(parent_index);
Parameters:
[in] parent_index The TPulseIslandID of the TPI being used to make the new TAP.
Template Parameters:
in] TypeOfTAP The type of specialisation of TAnalysedPulse that you want to create.
Definition at line 120 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList, and TVAnalysedPulseGenerator::GetSource().
Referenced by ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{
    TypeOfTAP* pulse=NULL;
    try{
        TPulseIsland* parent = fPulseList->at(parent_index);
        pulse=new TypeOfTAP(GetSource(),parent_index,parent);
    } catch (std::out_of_range){}
    return pulse;
}
virtual bool SimpIntAPGenerator::MayDivideTPIs () [inline, virtual]
Todo:
Document this
Implements TVAnalysedPulseGenerator.
Definition at line 28 of file SimpIntAPGenerator.h.
{return false;};
int SimpIntAPGenerator::ProcessPulses (const PulseIslandList & pil, AnalysedPulseList & apl) [virtual]
This method is called on each vector of pulses from a MIDAS event.
Parameters:
[in] pil The vector of TPIs to produce TAPs from.
[out] apl The vector of TAPs to append the new TAPs to.
Implements TVAnalysedPulseGenerator.
Definition at line 10 of file SimpIntAPGenerator.cpp.
References fECalibOffset, fECalibSlope, fPedestal, fTriggerPolarity, TVAnalysedPulseGenerator::MakeNewTAP(), SetBankInfo(), TAnalysedPulse::SetEnergy(), and TAnalysedPulse::SetIntegral().
{
  SetBankInfo(pulseList.at(0)->GetBankName());
  double integral, energy;
  TAnalysedPulse* outPulse;
  for(PulseIslandList::const_iterator pIt = pulseList.begin(); pIt != pulseList.end(); pIt++)
    {
      integral = 0;
      energy = 0;
      std::vector<int> samples = (*pIt)->GetSamples();
      double length = samples.size();
      double tempint = 0;
      for(std::vector<int>::iterator sIt = samples.begin(); sIt != samples.end(); sIt++)
          tempint += *sIt;
      integral = fTriggerPolarity * (tempint - (fPedestal * length));
      // We will need new calibration parameters from integral method
      energy = fECalibSlope* integral + fECalibOffset;
      outPulse=MakeNewTAP(pIt-pulseList.begin());
      outPulse->SetIntegral(integral);
      outPulse->SetEnergy(energy);
      // Add the pulse to the TAP list
      analysedList.push_back(outPulse);
    }
        // returning 0 tells the caller that we were successful, return non-zero if not
        return 0;
}
void SimpIntAPGenerator::SetBankInfo (std::string bankname) [inline]
Definition at line 15 of file SimpIntAPGenerator.h.
References fBankname, fDetname, fECalibOffset, fECalibSlope, fPedestal, fSetup, fTriggerPolarity, TSetupData::GetADCOffsetCalib(), TSetupData::GetADCSlopeCalib(), TSetupData::GetDetectorName(), TSetupData::GetPedestal(), and TSetupData::GetTriggerPolarity().
Referenced by ProcessPulses().
  {
    fBankname= bankname;
    fDetname = fSetup->GetDetectorName(bankname);
    fPedestal = fSetup->GetPedestal(bankname);
    fTriggerPolarity = fSetup->GetTriggerPolarity(bankname);
    fECalibSlope = fSetup->GetADCSlopeCalib(bankname);
    fECalibOffset = fSetup->GetADCOffsetCalib(bankname);
  }
void TVAnalysedPulseGenerator::SetPulseList (PulseIslandList * list) [inline, inherited]
Definition at line 46 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList.
{fPulseList=list;};
Member Data Documentation
std::string SimpIntAPGenerator::fBankname [private]
Definition at line 28 of file SimpIntAPGenerator.h.
Referenced by SetBankInfo().
std::string SimpIntAPGenerator::fDetname [private]
Definition at line 35 of file SimpIntAPGenerator.h.
Referenced by SetBankInfo().
double SimpIntAPGenerator::fECalibOffset [private]
Definition at line 36 of file SimpIntAPGenerator.h.
Referenced by ProcessPulses(), and SetBankInfo().
double SimpIntAPGenerator::fECalibSlope [private]
Definition at line 36 of file SimpIntAPGenerator.h.
Referenced by ProcessPulses(), and SetBankInfo().
double SimpIntAPGenerator::fPedestal [private]
Definition at line 36 of file SimpIntAPGenerator.h.
Referenced by ProcessPulses(), and SetBankInfo().
TSetupData* SimpIntAPGenerator::fSetup [private]
Definition at line 38 of file SimpIntAPGenerator.h.
Referenced by SetBankInfo().
int SimpIntAPGenerator::fTriggerPolarity [private]
Definition at line 37 of file SimpIntAPGenerator.h.
Referenced by ProcessPulses(), and SetBankInfo().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/SimpIntAPGenerator.h
rootana/src/TAP_generators/SimpIntAPGenerator.cpp