AlcapDAQ: PulseCandidateFinder_InvestigateParameters Class Reference
PulseCandidateFinder_InvestigateParameters Class Reference
[Modules]
Produces plots either the sample heights or the sample differences for each TPulseIsland.
#include <PulseCandidateFinder_InvestigateParameters.h>
Public Member Functions
PulseCandidateFinder_InvestigateParameters (modules::options *opts)
The constructor.
~PulseCandidateFinder_InvestigateParameters ()
Empty destructor.
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
In every event, we loop over all the detectors and create a ParameterHistogram, then we loop over the TPulseIslands and find the candidate pulses with PulseCandidateFinder::FindPulseCandidates(). Finally, we fill the parameter histogram with either the height of all samples, or the differences between consecutive samples.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
Nothing is done before each run.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
Nothing done at the end of each run.
Private Attributes
std::map< std::string, TH2D * > fParameterHistograms
The map that we store the parameter histograms for each channel.
modules::options * fOpts
Store the module options so that they can be passed to the PulseCandidateFinder.
Detailed Description
Produces plots either the sample heights or the sample differences for each TPulseIsland.
Author:
Andrew Edmonds
This module loops over TPulseIslands and sends them to PulseCandidateFinder::FillParameterHistogram() to plot either the height of the sample above pedestals (if the TPulseIsland is on a slow channel) or the difference between samples (if the TPulseIsland is on a fast channel).
The idea is that we can then look at these histograms to determine the values of the parameters for the PulseCandidateFinder
Definition at line 26 of file PulseCandidateFinder_InvestigateParameters.h.
Constructor & Destructor Documentation
PulseCandidateFinder_InvestigateParameters::PulseCandidateFinder_InvestigateParameters (modules::options * opts)
The constructor.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 16 of file PulseCandidateFinder_InvestigateParameters.cpp.
                                                                                                          :
  BaseModule("PulseCandidateFinder_InvestigateParameters",opts), fOpts(opts){
}
PulseCandidateFinder_InvestigateParameters::~PulseCandidateFinder_InvestigateParameters ()
Empty destructor.
Definition at line 21 of file PulseCandidateFinder_InvestigateParameters.cpp.
{
}
Member Function Documentation
int PulseCandidateFinder_InvestigateParameters::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Nothing done at the end of each run.
Parameters:
[in] gData See BaseModule::AfterLastEntry
[in] setup See BaseModule::AfterLastEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 102 of file PulseCandidateFinder_InvestigateParameters.cpp.
References BaseModule::Debug().
{
  // Print extra info if we're debugging this module:
  if(Debug()){
     cout<<"-----PulseCandidateFinder_InvestigateParameters::AfterLastEntry(): I'm debugging!"<<endl;
  }
  return 0;
}
int PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Nothing is done before each run.
Parameters:
[in] gData See BaseModule::BeforeFirstEntry
[in] setup See BaseModule::BeforeFirstEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 27 of file PulseCandidateFinder_InvestigateParameters.cpp.
References BaseModule::Debug().
{
  // Print extra info if we're debugging this module:
  if(Debug()){
     cout<<"-----PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(): I'm debugging!"<<endl;
  }
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int PulseCandidateFinder_InvestigateParameters::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
In every event, we loop over all the detectors and create a ParameterHistogram, then we loop over the TPulseIslands and find the candidate pulses with PulseCandidateFinder::FindPulseCandidates(). Finally, we fill the parameter histogram with either the height of all samples, or the differences between consecutive samples.
Parameters:
[in] gData See BaseModule::ProcessEntry
[in] gSetup See BaseModule::ProcessEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 38 of file PulseCandidateFinder_InvestigateParameters.cpp.
References BaseModule::Debug(), PulseCandidateFinder::FillParameterHistogram(), PulseCandidateFinder::FindPulseCandidates(), fOpts, fParameterHistograms, TGlobalData::fPulseIslandToChannelMap, TSetupData::GetDetectorName(), TSetupData::GetNBits(), PulseCandidateFinder::GetNPulseCandidates(), and TSetupData::Instance().
{
  // Prepare a few variables
  std::string bankname, detname;
  PulseIslandList thePulseIslands;
  StringPulseIslandMap::const_iterator it;
  // Loop over each detector
  for(it = gData->fPulseIslandToChannelMap.begin(); it != gData->fPulseIslandToChannelMap.end(); ++it){
    // Get the bank and detector names for this detector
    bankname = it->first;
    detname = setup->GetDetectorName(bankname);
    // Create the pulse candidate finder for this detector
    PulseCandidateFinder* pulse_candidate_finder = new PulseCandidateFinder(detname, fOpts);
    // Get the TPIs
    thePulseIslands = it->second;
    if (thePulseIslands.size() == 0) continue; // no pulses here..
    // Create the histogram that will store all the parameter values that we will look at to determine the best values
    if (fParameterHistograms.find(detname) == fParameterHistograms.end()) {
      int n_bits = TSetupData::Instance()->GetNBits(bankname);
      int max_adc_value = std::pow(2, n_bits);
      int min_value = 0;
      int max_value = max_adc_value;
      int bin_width = 10;
      int num_bins = (max_value - min_value) / bin_width;
      std::string histname = "fParameterHistogram_" + detname;
      TH2D* histogram = new TH2D(histname.c_str(), histname.c_str(), num_bins,min_value,max_value, num_bins,min_value,max_value);
      fParameterHistograms[detname] = histogram;
    }
    // Get the parameter histogram for this detector
    TH2D* parameter_histogram = fParameterHistograms[detname];
    // Loop through all the pulses
    for (PulseIslandList::iterator pulseIter = thePulseIslands.begin(); pulseIter != thePulseIslands.end(); ++pulseIter) {
      // Find the pulse candidates on this TPulseIsland and then fill the parameter histogram
      pulse_candidate_finder->FindPulseCandidates(*pulseIter);
      pulse_candidate_finder->FillParameterHistogram(parameter_histogram);
      // Use to export pulses (NB you will only want to run rootana on a few events to stop the output being large)
      int n_pulse_candidates = pulse_candidate_finder->GetNPulseCandidates();
      if (Debug()) {
        if (n_pulse_candidates > 0) {
          //      ExportPulse::Instance()->AddToExportList(detname, pulseIter - thePulseIslands.begin());
          if (n_pulse_candidates > 1) {
            std::cout << detname << "(" << bankname << "): Pulse #" << pulseIter - thePulseIslands.begin() << " has " << n_pulse_candidates << " pulse candidates\n";
          }
        }
      } // end if Debug
    } // end loop through pulses
  } //  end loop through detectors
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
modules::options* PulseCandidateFinder_InvestigateParameters::fOpts [private]
Store the module options so that they can be passed to the PulseCandidateFinder.
Definition at line 73 of file PulseCandidateFinder_InvestigateParameters.h.
Referenced by ProcessEntry().
std::map<std::string, TH2D*> PulseCandidateFinder_InvestigateParameters::fParameterHistograms [private]
The map that we store the parameter histograms for each channel.
Definition at line 69 of file PulseCandidateFinder_InvestigateParameters.h.
Referenced by ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/PulseCandidateFinder_InvestigateParameters.h
rootana/src/TAP_generators/PulseCandidateFinder_InvestigateParameters.cpp