AlcapDAQ: TemplateMultiFitter Class Reference
TemplateMultiFitter Class Reference
#include <TemplateMultiFitter.h>
Classes
struct TemplateDetails_t
Public Types
enum FitStatus {
kSuccess = 0, kPedestalOutOfBounds = -100, kAmplitudeOutOfBounds = -101, kTimeOutOfBounds = -102,
kFitNotConverged = 1, kInitialised = -200
}
Public Member Functions
TemplateMultiFitter (const IDs::channel &ch)
~TemplateMultiFitter ()
void Init ()
void AddTemplate (TTemplate *tpl)
fitting
Sets the intial estimates for the template fitter
void SetPedestal (double v)
void SetPulseEstimates (int index, double amp, double time)
int FitWithOneTimeFree (int index, const TH1D *hPulse)
int FitWithAllTimesFixed (const TH1D *hPulse)
getters
double GetPedestal () const
double GetAmplitude (int i) const
double GetTime (int i) const
double GetChi2 () const
double GetNDoF () const
Private Types
typedef std::vector
< TemplateDetails_t > TemplateList
Private Member Functions
void operator= (const TemplateMultiFitter &)
Private Attributes
TFitterMinuit * fMinuitFitter
MultiHistogramFitFCN * fFitFCN
IDs::channel fChannel
double fMaxADC
double fMinADC
double fPedestal
int fRefineFactor
TemplateList fTemplates
int fFreeTemplate
double fChi2
int fNDoF
Detailed Description
Definition at line 15 of file TemplateMultiFitter.h.
Member Typedef Documentation
typedef std::vector<TemplateDetails_t> TemplateMultiFitter::TemplateList [private]
Definition at line 29 of file TemplateMultiFitter.h.
Member Enumeration Documentation
enum TemplateMultiFitter::FitStatus
Enumerator:
kSuccess
kPedestalOutOfBounds
kAmplitudeOutOfBounds
kTimeOutOfBounds
kFitNotConverged
kInitialised
Definition at line 37 of file TemplateMultiFitter.h.
                {
    kSuccess=0 ,
    kPedestalOutOfBounds= -100,
    kAmplitudeOutOfBounds= -101,
    kTimeOutOfBounds= -102,
    kFitNotConverged= 1,
    kInitialised=-200
  };
Constructor & Destructor Documentation
TemplateMultiFitter::TemplateMultiFitter (const IDs::channel & ch)
Definition at line 14 of file TemplateMultiFitter.cpp.
References fChannel, fMaxADC, fMinADC, SetupRecord::GetMaxADC(), EventNavigator::GetSetupRecord(), and EventNavigator::Instance().
                                                            :
   fMinuitFitter(NULL), fFitFCN(NULL), fChannel(ch),fPedestal(0), fRefineFactor(0) {
  // Calculate the max ADC value
  fMinADC = 0;
  fMaxADC = EventNavigator::Instance().GetSetupRecord().GetMaxADC(fChannel);
}
TemplateMultiFitter::~TemplateMultiFitter ()
Definition at line 40 of file TemplateMultiFitter.cpp.
{
}
Member Function Documentation
void TemplateMultiFitter::AddTemplate (TTemplate * tpl)
Definition at line 169 of file TemplateMultiFitter.cpp.
References fRefineFactor, TemplateMultiFitter::TemplateDetails_t::fTemplate, fTemplates, and TTemplate::GetRefineFactor().
Referenced by TemplateFitAPGenerator::TemplateFitAPGenerator().
{
  TemplateDetails_t tmp;
  tmp.fTemplate=tpl;
  fTemplates.push_back(tmp);
  if(fRefineFactor==0) fRefineFactor=tpl->GetRefineFactor();
  else if(fRefineFactor!= tpl->GetRefineFactor()){
    throw Except::MismatchedTemplateRefineFactors();
  }
}
int TemplateMultiFitter::FitWithAllTimesFixed (const TH1D * hPulse)
Definition at line 137 of file TemplateMultiFitter.cpp.
References fChi2, fFitFCN, fMaxADC, fMinADC, fMinuitFitter, fNDoF, fPedestal, fTemplates, MultiHistogramFitFCN::GetNDoF(), MultiHistogramFitFCN::SetPulseHist(), and MultiHistogramFitFCN::SetTimeOffset().
Referenced by TemplateFitAPGenerator::RefitWithTwo().
{
  // Prepare for minimizations
  fMinuitFitter->Clear();
  fFitFCN->SetPulseHist(hPulse);
  fMinuitFitter->CreateMinimizer(TFitterMinuit::kMigrad);
  // initialise fit
  fMinuitFitter->SetParameter(0, "PedestalOffset", fPedestal, 0.1, fMinADC, fMaxADC);
  for(TemplateList::const_iterator i_tpl=fTemplates.begin(); i_tpl!=fTemplates.end(); ++i_tpl){
      int i=i_tpl-fTemplates.begin();
      fMinuitFitter->SetParameter(i+1, Form("AmplitudeScaleFactor_%d",i), i_tpl->fAmplitudeScaleFactor, 0.1, fMinADC, fMaxADC);
      fFitFCN->SetTimeOffset(i, i_tpl->fTimeOffset);
  }
  // run the fitter
  int status = fMinuitFitter->Minimize(1000);
  // get fitted parameters
  std::vector<double> parameters(1+fTemplates.size());
  parameters[0]=fPedestal=fMinuitFitter->GetParameter(0);
  for(TemplateList::iterator i_tpl=fTemplates.begin(); i_tpl!=fTemplates.end(); ++i_tpl)
     parameters[i_tpl-fTemplates.begin()+1]=i_tpl->fAmplitudeScaleFactor= fMinuitFitter->GetParameter(i_tpl-fTemplates.begin()+1);
  // check chi-2
  fChi2 = (*fFitFCN)(parameters);
  fNDoF = fFitFCN->GetNDoF();
  // return status
  return status;
}
int TemplateMultiFitter::FitWithOneTimeFree (int index, const TH1D * hPulse)
Definition at line 43 of file TemplateMultiFitter.cpp.
References DEBUG_VALUE, fChi2, fFitFCN, fMaxADC, fMinADC, fMinuitFitter, fNDoF, fPedestal, fRefineFactor, fTemplates, TemplateMultiFitter::TemplateDetails_t::fTimeOffset, MultiHistogramFitFCN::GetNDoF(), kAmplitudeOutOfBounds, kInitialised, kPedestalOutOfBounds, kTimeOutOfBounds, MultiHistogramFitFCN::SetPulseHist(), and MultiHistogramFitFCN::SetTimeOffset().
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{
  // Get the template we're going to shift around
  TemplateDetails_t& current=fTemplates.at(index);
  // Prepare for minimizations
  fMinuitFitter->Clear();
  fFitFCN->SetPulseHist(hPulse);
  fMinuitFitter->CreateMinimizer(TFitterMinuit::kMigrad);
  // Loop through some time offsets ourselved
  const double offset_range = 10*fRefineFactor; // maximum distance to go from the initial estimate
  double best_time_offset = 0;
  std::vector<double> best_parameters(1+fTemplates.size());
  double best_chi2 = 1e34;
  int best_ndof = 0;
  int best_status = kInitialised;
  int status = kInitialised;
  // Calculate the bounds of the parameters
  int min_offset = current.fTimeOffset - offset_range;
  int max_offset = current.fTimeOffset + offset_range;
  std::vector<double> parameters(1+fTemplates.size());
  for (double time_offset = min_offset; time_offset <= max_offset; ++time_offset) {
    fFitFCN->SetTimeOffset(index, time_offset);
    // Reset the estimates
    fMinuitFitter->SetParameter(0, "PedestalOffset", fPedestal, 0.1, fPedestal-10, fPedestal+10);
    for(TemplateList::const_iterator i_tpl=fTemplates.begin(); i_tpl!=fTemplates.end(); ++i_tpl){
        int i=i_tpl-fTemplates.begin();
        fMinuitFitter->SetParameter(i+1, Form("AmplitudeScaleFactor_%d",i), i_tpl->fAmplitudeScaleFactor, 0.1, fMinADC, fMaxADC);
    }
    // Minimize and notify if there was a problem
    status = fMinuitFitter->Minimize(1000); // set limit of 1000 calls to FCN
    DEBUG_VALUE(status);
    if(status!=0) continue;
    // Store the Chi2 and degrees of freedom
    parameters[0]=fMinuitFitter->GetParameter(0);
    for(std::vector<double>::iterator i_par=parameters.begin()+1; i_par!=parameters.end(); ++i_par){
       int n=i_par-parameters.begin();
       *i_par= fMinuitFitter->GetParameter(n);
    }
    // Check the bounds
    const double delta_ped_offset_error = 1; // if the given parameter is within this much of the boundaries, then we will ignore it
    const double delta_amp_sf_error = 0.001;
    if ( (parameters[0] < delta_ped_offset_error ) || (parameters[0] > fMaxADC - delta_ped_offset_error) ) {
      status = kPedestalOutOfBounds;
    } else {
       for(std::vector<double>::const_iterator i_par=parameters.begin()+1; i_par!=parameters.end(); ++i_par){
          if (    ( *i_par < fMinADC + delta_amp_sf_error ) || ( *i_par > fMaxADC - delta_amp_sf_error ) ) {
                DEBUG_VALUE(*i_par, delta_amp_sf_error, fMinADC, fMaxADC);
                status = kAmplitudeOutOfBounds;
                break;
          }
       }
    }
    // get the chi-2
    fChi2 = (*fFitFCN)(parameters);
    fNDoF = fFitFCN->GetNDoF();
    DEBUG_VALUE(status,parameters[0],fChi2,fNDoF);
    if (status == 0 && fChi2 < best_chi2) {
      best_time_offset = time_offset;
      best_parameters=parameters;
      best_chi2 = fChi2;
      best_status = status;
      best_ndof = fNDoF;
    }
  }
  // Store the final best values
  fChi2 = best_chi2;
  fNDoF = best_ndof;
  current.fTimeOffset = best_time_offset;
  fPedestal = best_parameters[0];
  for(TemplateList::iterator i_tpl=fTemplates.begin(); i_tpl!=fTemplates.end(); ++i_tpl){
      i_tpl->fAmplitudeScaleFactor=best_parameters[i_tpl-fTemplates.begin()+1];
  }
  static int offset_safety = 1;
  if ( (current.fTimeOffset < min_offset + offset_safety && current.fTimeOffset > min_offset - offset_safety) ||
       (current.fTimeOffset < max_offset + offset_safety && current.fTimeOffset > max_offset - offset_safety) ) {
      best_status = kTimeOutOfBounds;
  }
  return best_status; // return status for the calling module to look at
}
double TemplateMultiFitter::GetAmplitude (int i) const [inline]
Definition at line 62 of file TemplateMultiFitter.h.
References fTemplates.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{ return fTemplates.at(i).GetAmplitude();}
double TemplateMultiFitter::GetChi2 () const [inline]
Definition at line 64 of file TemplateMultiFitter.h.
References fChi2.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{ return fChi2; }
double TemplateMultiFitter::GetNDoF () const [inline]
Definition at line 65 of file TemplateMultiFitter.h.
References fNDoF.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{ return fNDoF; }
double TemplateMultiFitter::GetPedestal () const [inline]
Definition at line 61 of file TemplateMultiFitter.h.
References fPedestal.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{ return fPedestal; }
double TemplateMultiFitter::GetTime (int i) const [inline]
Definition at line 63 of file TemplateMultiFitter.h.
References fTemplates.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{ return fTemplates.at(i).GetTime(); }
void TemplateMultiFitter::Init ()
Definition at line 22 of file TemplateMultiFitter.cpp.
References MultiHistogramFitFCN::AddTemplate(), fFitFCN, fMinuitFitter, fRefineFactor, fTemplates, and MultiHistogramFitFCN::SetRefineFactor().
Referenced by TemplateFitAPGenerator::TemplateFitAPGenerator().
{
  if(fFitFCN || fMinuitFitter) {
     cout<< "TemplateMultiFitter: Warning: trying to initialize fitter which was already initialised!"<<endl;
     return;
  }
  fFitFCN=new MultiHistogramFitFCN(fRefineFactor);
  fFitFCN->SetRefineFactor(fRefineFactor);
  for(TemplateList::iterator i_tpl=fTemplates.begin(); i_tpl!=fTemplates.end(); ++i_tpl){
     fFitFCN->AddTemplate(i_tpl->fTemplate->GetHisto());
  }
  int num_params=fTemplates.size()+1; //  1 parameter per template (amplitude) + global pedestal.
  fMinuitFitter = new TFitterMinuit(num_params);
  fMinuitFitter->SetMinuitFCN(fFitFCN);
  fMinuitFitter->SetPrintLevel(-1); // set the debug level to quiet (-1=quiet, 0=normal, 1=verbose)
}
void TemplateMultiFitter::operator= (const TemplateMultiFitter &) [private]
void TemplateMultiFitter::SetPedestal (double v) [inline]
Definition at line 51 of file TemplateMultiFitter.h.
References fPedestal.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{fPedestal=v;}
void TemplateMultiFitter::SetPulseEstimates (int index, double amp, double time) [inline]
Definition at line 52 of file TemplateMultiFitter.h.
References fTemplates.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{
      fTemplates.at(index).Set(amp,time);
  }
Member Data Documentation
IDs::channel TemplateMultiFitter::fChannel [private]
Definition at line 71 of file TemplateMultiFitter.h.
Referenced by TemplateMultiFitter().
double TemplateMultiFitter::fChi2 [private]
Definition at line 79 of file TemplateMultiFitter.h.
Referenced by FitWithAllTimesFixed(), FitWithOneTimeFree(), and GetChi2().
MultiHistogramFitFCN* TemplateMultiFitter::fFitFCN [private]
Definition at line 70 of file TemplateMultiFitter.h.
Referenced by FitWithAllTimesFixed(), FitWithOneTimeFree(), and Init().
int TemplateMultiFitter::fFreeTemplate [private]
Definition at line 77 of file TemplateMultiFitter.h.
double TemplateMultiFitter::fMaxADC [private]
Definition at line 72 of file TemplateMultiFitter.h.
Referenced by FitWithAllTimesFixed(), FitWithOneTimeFree(), and TemplateMultiFitter().
double TemplateMultiFitter::fMinADC [private]
Definition at line 72 of file TemplateMultiFitter.h.
Referenced by FitWithAllTimesFixed(), FitWithOneTimeFree(), and TemplateMultiFitter().
TFitterMinuit* TemplateMultiFitter::fMinuitFitter [private]
Definition at line 69 of file TemplateMultiFitter.h.
Referenced by FitWithAllTimesFixed(), FitWithOneTimeFree(), and Init().
int TemplateMultiFitter::fNDoF [private]
Definition at line 80 of file TemplateMultiFitter.h.
Referenced by FitWithAllTimesFixed(), FitWithOneTimeFree(), and GetNDoF().
double TemplateMultiFitter::fPedestal [private]
Definition at line 74 of file TemplateMultiFitter.h.
Referenced by FitWithAllTimesFixed(), FitWithOneTimeFree(), GetPedestal(), and SetPedestal().
int TemplateMultiFitter::fRefineFactor [private]
Definition at line 75 of file TemplateMultiFitter.h.
Referenced by AddTemplate(), FitWithOneTimeFree(), and Init().
TemplateList TemplateMultiFitter::fTemplates [private]
Definition at line 76 of file TemplateMultiFitter.h.
Referenced by AddTemplate(), FitWithAllTimesFixed(), FitWithOneTimeFree(), GetAmplitude(), GetTime(), Init(), and SetPulseEstimates().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/template_fitting/TemplateMultiFitter.h
rootana/src/TAP_generators/template_fitting/TemplateMultiFitter.cpp