AlcapDAQ: PlotTAP_Integral Class Reference
PlotTAP_Integral Class Reference
[Modules]
A one line description of what your module does.
#include <PlotTAP_Integral.h>
Public Member Functions
PlotTAP_Integral (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~PlotTAP_Integral ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::map< IDs::source,
TH1F * > PlotList_t
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Private Attributes
PlotList_t fPlots
Detailed Description
A one line description of what your module does.
Author:
AuthorName
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 25 of file PlotTAP_Integral.h.
Member Typedef Documentation
typedef std::map<IDs::source,TH1F*> PlotTAP_Integral::PlotList_t [private]
Definition at line 58 of file PlotTAP_Integral.h.
Constructor & Destructor Documentation
PlotTAP_Integral::PlotTAP_Integral (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 19 of file PlotTAP_Integral.cpp.
                                                      :
   BaseModule("PlotTAP_Integral",opts){
}
PlotTAP_Integral::~PlotTAP_Integral ()
Is anything done in the destructor?
Definition at line 23 of file PlotTAP_Integral.cpp.
{
}
Member Function Documentation
int PlotTAP_Integral::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 81 of file PlotTAP_Integral.cpp.
{
  /*    for(PlotList_t::iterator i_plot=fPlots.begin();
            i_plot!=fPlots.end(); ++i_plot){
        i_plot->second->Draw();
    }
  */
  return 0;
}
int PlotTAP_Integral::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 26 of file PlotTAP_Integral.cpp.
References fPlots, gAnalysedPulseMap, IDs::source::str(), and modules::parser::ToCppValid().
{
    // For each source,
    TH1F* hist=NULL;
    std::string name, title;
    const IDs::source* source=NULL;
    for(SourceAnalPulseMap::const_iterator i_source = gAnalysedPulseMap.begin();
            i_source!=gAnalysedPulseMap.end(); ++i_source){
        source=&i_source->first;
        // setup the name and title for the histogram
        name="h"+modules::parser::ToCppValid(source->str())+"_integrals";
        title="Integral of pulses coming from "+source->str();
        // make a histogram
        int x_min = -100000;
        int x_max = 5000000;
        int bin_width = 100;
        int n_bins = (x_max - x_min) / bin_width;
        hist=new TH1F(name.c_str(),title.c_str(),n_bins,x_min,x_max);
        hist->SetXTitle("Integral of each pulse (arb. units)");
        // register histogram with list
        fPlots[*source]=hist;
    }
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int PlotTAP_Integral::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 53 of file PlotTAP_Integral.cpp.
References fPlots, and gAnalysedPulseMap.
{
    PlotList_t::iterator i_plot;
    const AnalysedPulseList* pulseList;
    const IDs::source* source;
    for(SourceAnalPulseMap::const_iterator i_source = gAnalysedPulseMap.begin();
            i_source!=gAnalysedPulseMap.end(); ++i_source){
        source=&i_source->first;
        pulseList=&i_source->second;
        // Find the corresponding histogram
        i_plot=fPlots.find(*source);
        if(i_plot==fPlots.end()){
            cout<<"PlotTAP_Integral: Error: Unable to find plot for source '"<<*source<<"'"<<endl;
            return 1;
        }
        // For each TAP
        for(AnalysedPulseList::const_iterator i_pulse=pulseList->begin();
                i_pulse!=pulseList->end();++i_pulse){
            // Fill integral histogram
            i_plot->second->Fill((*i_pulse)->GetIntegral());
        }
    }
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
PlotList_t PlotTAP_Integral::fPlots [private]
Definition at line 59 of file PlotTAP_Integral.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/plotters/PlotTAP_Integral.h
rootana/src/plotters/PlotTAP_Integral.cpp