AlcapDAQ: TemplateConvolveAPGenerator Class Reference
TemplateConvolveAPGenerator Class Reference
#include <TemplateConvolveAPGenerator.h>
Public Member Functions
TemplateConvolveAPGenerator (TAPGeneratorOptions *opts)
virtual ~TemplateConvolveAPGenerator ()
virtual int ProcessPulses (const PulseIslandList &, AnalysedPulseList &)
This method is called on each vector of pulses from a MIDAS event.
virtual bool MayDivideTPIs ()
void SetPulseList (PulseIslandList *list)
template<typename TypeOfTAP >
TypeOfTAP * MakeNewTAP (int parent_index) const
The suggested method for constructing a new TAP.
TAnalysedPulse * MakeNewTAP (int parent_index) const
bool Debug () const
IDs::channel GetChannel () const
std::string GetBank () const
const IDs::source & GetSource () const
Get the source id for this generator being used on the current channel.
virtual void CalibratePulses (AnalysedPulseList &theAnalysedPulses) const
Static Public Member Functions
static const char * TapType ()
Protected Member Functions
virtual void SetChannel (const std::string &det)
Set the channel for this generator. Should NOT be called by user code.
Private Member Functions
bool PassesIntegralRatio (const TPulseIsland *pulse, double &integral, double &ratio) const
double CalibrateTime (double clockTime, const TPulseIsland *tpi) const
Convert time from clock time within the TPI to real time.
Private Attributes
TTemplate * fTemplate
TemplateConvolver * fConvolver
double fIntegralMax
double fIntegralMin
double fIntegralRatioMax
double fIntegralRatioMin
double fTemplateAmp
double fTemplatePed
double fTemplateTime
double fPedestal
double fTicksPerNs
double fMuScTimeOffset
bool fExpectPileUp
Algorithm::IntegralRatio * fIntegralRatio
Static Private Attributes
static TemplateArchive * fTemplateArchive = NULL
Friends
class MakeAnalysedPulses
Detailed Description
Definition at line 15 of file TemplateConvolveAPGenerator.h.
Constructor & Destructor Documentation
TemplateConvolveAPGenerator::TemplateConvolveAPGenerator (TAPGeneratorOptions * opts)
Definition at line 16 of file TemplateConvolveAPGenerator.cpp.
References TemplateConvolver::CharacteriseTemplate(), fConvolver, fIntegralMax, fIntegralMin, fIntegralRatio, fIntegralRatioMax, fIntegralRatioMin, fTemplate, fTemplateArchive, TVAnalysedPulseGenerator::GetChannel(), modules::options::GetDouble(), modules::options::GetFlag(), TTemplate::GetHisto(), modules::options::GetInt(), SetupRecord::GetPolarity(), EventNavigator::GetSetupRecord(), modules::options::GetString(), TemplateArchive::GetTemplate(), EventNavigator::Instance(), TTemplate::NormaliseToSumSquares(), and TTemplate::RebinToOriginalSampling().
                                                                                 :
   TVAnalysedPulseGenerator("TemplateConvolve",opts),
    fPedestal(EventNavigator::Instance().GetSetupRecord().GetPedestal(GetChannel())),
    fTicksPerNs(EventNavigator::Instance().GetSetupRecord().GetTickLength(GetChannel())),
    //fMuScTimeOffset(SetupNavigator::Instance()->GetCoarseTimeOffset(GetSource())),
    fMuScTimeOffset(0.),
    fExpectPileUp(false), fIntegralRatio(NULL)
{
   // get the templates from the archive
   if(!fTemplateArchive){
     fTemplateArchive=new TemplateArchive(opts->GetString("template_archive").c_str(),"READ");
   }
   fTemplate=fTemplateArchive->GetTemplate(GetChannel());
   fTemplate->RebinToOriginalSampling();
   fTemplate->NormaliseToSumSquares();
   int fit_peak= opts->GetInt("n_quad_fit",5);
   int left= opts->GetInt("left",20);
   int right= opts->GetInt("right",120);
   fConvolver=new TemplateConvolver(GetChannel(), fTemplate, fit_peak, left, right);
   TH1* tpl=(TH1*)fTemplate->GetHisto()->Clone("Template");
   tpl->SetDirectory(gDirectory);
   fConvolver->CharacteriseTemplate();
   // prepare the integral ratio cuts
   if(opts->GetFlag("use_IR_cut")){
      fIntegralRatio=new Algorithm::IntegralRatio(
                      opts->GetInt("start_integral",10),
                      opts->GetInt("start_tail",60),
                      opts->GetInt("stop_integral",0),
                      EventNavigator::Instance().GetSetupRecord().GetPolarity(GetChannel()));
      fIntegralMax=opts->GetDouble("max_integral");
      fIntegralMin=opts->GetDouble("min_integral");
      fIntegralRatioMax=opts->GetDouble("max_ratio");
      fIntegralRatioMin=opts->GetDouble("min_ratio");
  }
}
virtual TemplateConvolveAPGenerator::~TemplateConvolveAPGenerator () [inline, virtual]
Definition at line 19 of file TemplateConvolveAPGenerator.h.
{};
Member Function Documentation
void TVAnalysedPulseGenerator::CalibratePulses (AnalysedPulseList & theAnalysedPulses) const [virtual, inherited]
Definition at line 23 of file TVAnalysedPulseGenerator.cpp.
References TVAnalysedPulseGenerator::fAdcToEnergyGain, TVAnalysedPulseGenerator::fAdcToEnergyOffset, and TVAnalysedPulseGenerator::fCanCalibrate.
{
   if(fCanCalibrate){
      for(AnalysedPulseList::iterator i_tap=theAnalysedPulses.begin(); i_tap != theAnalysedPulses.end(); ++i_tap){
         const double amplitude=(*i_tap)->GetAmplitude();
         (*i_tap)->SetEnergy(fAdcToEnergyGain * amplitude + fAdcToEnergyOffset);
      }
   }
}
double TemplateConvolveAPGenerator::CalibrateTime (double clockTime, const TPulseIsland * tpi) const [private]
Convert time from clock time within the TPI to real time.
Definition at line 139 of file TemplateConvolveAPGenerator.cpp.
References fMuScTimeOffset, fTicksPerNs, and TPulseIsland::GetTimeStamp().
Referenced by ProcessPulses().
{
  return (clockTime + (double)tpi->GetTimeStamp()) * fTicksPerNs - fMuScTimeOffset;
}
bool TVAnalysedPulseGenerator::Debug () const [inline, inherited]
Definition at line 77 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fDebug.
Referenced by GaussFitAPGenerator::FitPulse(), ProcessPulses(), and IntegralRatioAPGenerator::ProcessPulses().
{return fDebug;};
std::string TVAnalysedPulseGenerator::GetBank () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 85 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fBankName.
{return fBankName;};
IDs::channel TVAnalysedPulseGenerator::GetChannel () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 81 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), and TVAnalysedPulseGenerator::fSource.
Referenced by FirstCompleteAPGenerator::DrawPulse(), FirstCompleteAPGenerator::FirstCompleteAPGenerator(), IntegralRatioAPGenerator::ProcessPulses(), TemplateConvolveAPGenerator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{return fSource.Channel();};
const IDs::source& TVAnalysedPulseGenerator::GetSource () const [inline, inherited]
Get the source id for this generator being used on the current channel.
Useful for a generator to know the full source much like in the above GetChannel method, but this could also be useful for checking that this generator is the one that made a given TAP in later analysis by comparing this value to that stored in the TAP itself.
Definition at line 94 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fSource.
Referenced by TVAnalysedPulseGenerator::MakeNewTAP(), and IntegralRatioAPGenerator::ProcessPulses().
{return fSource;};
TAnalysedPulse* TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
Definition at line 73 of file TVAnalysedPulseGenerator.h.
{
            return MakeNewTAP<TAnalysedPulse>(parent_index);
        }
template<typename TypeOfTAP > TypeOfTAP * TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
The suggested method for constructing a new TAP.
In the process of constructing TAP, information that isn't immediately obvious how to get needs to be passed to TAP. This method returns a pointer to a TAP construced for you, and all you need to pass it is the TPulseIslandID.
In the case where a generator wants to add extra information to the standard TAP information, we expect people to derive from TAnalysedPulse. If your generator is one of these, then use the template argument to produce the type of TAP you desire. Note that this forces the constructor of the specialised TAP to be the same as for TAnalysedPulse itself.
For example, for to make a specialied analysed pulse called TSpecialAnalysedPulse (original, huh?) you would do:
 TSpecialAnalysedPulse* tsap=MakeNewTAP<TSpecialAnalysedPulse>(parent_index);
Parameters:
[in] parent_index The TPulseIslandID of the TPI being used to make the new TAP.
Template Parameters:
in] TypeOfTAP The type of specialisation of TAnalysedPulse that you want to create.
Definition at line 137 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList, and TVAnalysedPulseGenerator::GetSource().
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), SimpIntAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), CFTimeMBAmpAPGenerator::ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{
    TypeOfTAP* pulse=NULL;
    TPulseIsland* parent = fPulseList->at(parent_index);
    pulse=new TypeOfTAP(GetSource(),parent_index,parent);
    return pulse;
}
virtual bool TemplateConvolveAPGenerator::MayDivideTPIs () [inline, virtual]
Todo:
Document this
Implements TVAnalysedPulseGenerator.
Definition at line 24 of file TemplateConvolveAPGenerator.h.
{return true;};
bool TemplateConvolveAPGenerator::PassesIntegralRatio (const TPulseIsland * pulse, double & integral, double & ratio) const [private]
Definition at line 122 of file TemplateConvolveAPGenerator.cpp.
References fIntegralRatio, Algorithm::IntegralRatio::GetRatio(), Algorithm::IntegralRatio::GetTotal(), and Algorithm::IntegralRatio::SetPedestalToMinimum().
Referenced by ProcessPulses().
{
   if(!fIntegralRatio) return true;
   try{
     fIntegralRatio->SetPedestalToMinimum(pulse);
     (*fIntegralRatio)(pulse);
   }catch(std::out_of_range& e){
     return false;
   }
   integral=fIntegralRatio->GetTotal();
   ratio=fIntegralRatio->GetRatio();
   if( fIntegralMax < integral || fIntegralMin > integral
       || fIntegralRatioMax < ratio || fIntegralRatioMin > ratio) {
       return false;
   }
   return true;
}
int TemplateConvolveAPGenerator::ProcessPulses (const PulseIslandList & pil, AnalysedPulseList & apl) [virtual]
This method is called on each vector of pulses from a MIDAS event.
Parameters:
[in] pil The vector of TPIs to produce TAPs from.
[out] apl The vector of TAPs to append the new TAPs to.
Implements TVAnalysedPulseGenerator.
Definition at line 54 of file TemplateConvolveAPGenerator.cpp.
References CalibrateTime(), TemplateConvolver::Convolve(), TVAnalysedPulseGenerator::Debug(), fConvolver, fExpectPileUp, TemplateConvolver::FindPeaks(), fIntegralRatio, fPedestal, fTemplate, TemplateConvolver::GetAmplitudeScale(), TemplateConvolver::GetEnergyConvolution(), TemplateConvolver::GetPeaks(), TemplateConvolver::GetTimeConvolution(), TemplateConvolver::GetTimeShift(), PassesIntegralRatio(), TAnalysedPulse::SetAmplitude(), TTemplateConvolveAnalysedPulse::SetAmplitudeScale(), TTemplateConvolveAnalysedPulse::SetEnergyConvolve(), TAnalysedPulse::SetIntegral(), TTemplateConvolveAnalysedPulse::SetIntegralRatio(), TTemplateConvolveAnalysedPulse::SetNPeaks(), TTemplateConvolveAnalysedPulse::SetPeakRank(), TAnalysedPulse::SetPedestal(), TTemplateConvolveAnalysedPulse::SetQuadraticFit(), TTemplateConvolveAnalysedPulse::SetTemplate(), TAnalysedPulse::SetTime(), TTemplateConvolveAnalysedPulse::SetTimeConvolve(), and TTemplateConvolveAnalysedPulse::SetTimeOffset().
{
  // Loop over all the TPIs given to us
  double integral, ratio;
  TTemplateConvolveAnalysedPulse* tap;
  for (PulseIslandList::const_iterator tpi=pulseList.begin();
       tpi!=pulseList.end(); tpi++){
    // Check integral ratio if we're supposed to
    if(fIntegralRatio && !PassesIntegralRatio(*tpi, integral,ratio)){
       continue;
    }
    Algorithm::TpiMinusPedestal_iterator waveform((*tpi)->GetSamples().begin(),fPedestal);
    Algorithm::TpiMinusPedestal_iterator end((*tpi)->GetSamples().end());
    // convolve with the template
    int n_peaks=fConvolver->Convolve(waveform,end );
    if(n_peaks<0) {
      if(Debug())cout<<"Waveform too small to analyze"<<endl;
      continue;
    }
    n_peaks= fConvolver->FindPeaks(fExpectPileUp , waveform);
    const TemplateConvolver::PeaksVector& peaks=fConvolver->GetPeaks();
    int count=0;
    for(TemplateConvolver::PeaksVector::const_iterator i_tap=peaks.begin();
          i_tap!=peaks.end(); ++i_tap){
    //for(int i_peak=0; i_peak<3 || fConvolver->GetPeaks().size()==0 ; ++i_peak){
    //   // get the first pulse to be found
    //   const TemplateConvolver::FoundPeaks& i_tap=*fConvolver->GetPeaks().begin();
       // Make a new TAP to store the data.  This method makes a TAP and sets the parent TPI info.  It needs
       // the index of the parent TPI in the container as an argument
       tap = MakeNewTAP<TTemplateConvolveAnalysedPulse>(tpi-pulseList.begin());
       if(fIntegralRatio){
         tap->SetIntegral(integral);
         tap->SetIntegralRatio(ratio);
       }
       tap->SetNPeaks(n_peaks);
       tap->SetPeakRank(count);
       tap->SetEnergyConvolve(fConvolver->GetEnergyConvolution());
       tap->SetTimeConvolve(fConvolver->GetTimeConvolution());
       tap->SetTimeOffset(i_tap->time);
       tap->SetAmplitudeScale(i_tap->amplitude);
       tap->SetAmplitude(i_tap->amplitude*fConvolver->GetAmplitudeScale());
       tap->SetQuadraticFit(i_tap->quad,i_tap->linear, i_tap->constant);
       tap->SetTemplate(fTemplate);
       tap->SetPedestal(fPedestal);
       double time= CalibrateTime(i_tap->time + fConvolver->GetTimeShift() +0.5, *tpi);
       tap->SetTime(time);
       //DEBUG_VALUE(i_tap->amplitude, i_tap->time, i_tap->pedestal);
       // Finally add the new TAP to the output list
       analysedList.push_back(tap);
       //waveform.AddHistogram(fConvolver->GetTemplateACF(), i_tap.amplitude, -i_tap.time+fConvolver->GetLeftSafety());
       //n_peaks= fConvolver->Convolve(waveform,end );
       //if(n_peaks==0) break;
       count++;
    }
  }
  return 0;
}
virtual void TVAnalysedPulseGenerator::SetChannel (const std::string & det) [inline, protected, virtual, inherited]
Set the channel for this generator. Should NOT be called by user code.
Called by MakeAnalysedPulses to tell this generator what channel it is looking at.
Definition at line 108 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), TVAnalysedPulseGenerator::fBankName, TVAnalysedPulseGenerator::fSource, SetupNavigator::GetBank(), and SetupNavigator::Instance().
Referenced by TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{
           fSource.Channel()=det;
           fBankName= SetupNavigator::Instance()->GetBank(det);
         };
void TVAnalysedPulseGenerator::SetPulseList (PulseIslandList * list) [inline, inherited]
Definition at line 44 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList.
{fPulseList=list;};
static const char* TemplateConvolveAPGenerator::TapType () [inline, static]
Reimplemented from TVAnalysedPulseGenerator.
Definition at line 26 of file TemplateConvolveAPGenerator.h.
{
       return TTemplateConvolveAnalysedPulse::Class()->GetName();
   }
Friends And Related Function Documentation
friend class MakeAnalysedPulses [friend, inherited]
Definition at line 101 of file TVAnalysedPulseGenerator.h.
Member Data Documentation
TemplateConvolver* TemplateConvolveAPGenerator::fConvolver [private]
Definition at line 38 of file TemplateConvolveAPGenerator.h.
Referenced by ProcessPulses(), and TemplateConvolveAPGenerator().
bool TemplateConvolveAPGenerator::fExpectPileUp [private]
Definition at line 45 of file TemplateConvolveAPGenerator.h.
Referenced by ProcessPulses().
double TemplateConvolveAPGenerator::fIntegralMax [private]
Definition at line 40 of file TemplateConvolveAPGenerator.h.
Referenced by TemplateConvolveAPGenerator().
double TemplateConvolveAPGenerator::fIntegralMin [private]
Definition at line 40 of file TemplateConvolveAPGenerator.h.
Referenced by TemplateConvolveAPGenerator().
Algorithm::IntegralRatio* TemplateConvolveAPGenerator::fIntegralRatio [private]
Definition at line 47 of file TemplateConvolveAPGenerator.h.
Referenced by PassesIntegralRatio(), ProcessPulses(), and TemplateConvolveAPGenerator().
double TemplateConvolveAPGenerator::fIntegralRatioMax [private]
Definition at line 41 of file TemplateConvolveAPGenerator.h.
Referenced by TemplateConvolveAPGenerator().
double TemplateConvolveAPGenerator::fIntegralRatioMin [private]
Definition at line 41 of file TemplateConvolveAPGenerator.h.
Referenced by TemplateConvolveAPGenerator().
double TemplateConvolveAPGenerator::fMuScTimeOffset [private]
Definition at line 44 of file TemplateConvolveAPGenerator.h.
Referenced by CalibrateTime().
double TemplateConvolveAPGenerator::fPedestal [private]
Definition at line 43 of file TemplateConvolveAPGenerator.h.
Referenced by ProcessPulses().
TTemplate* TemplateConvolveAPGenerator::fTemplate [private]
Definition at line 37 of file TemplateConvolveAPGenerator.h.
Referenced by ProcessPulses(), and TemplateConvolveAPGenerator().
double TemplateConvolveAPGenerator::fTemplateAmp [private]
Definition at line 42 of file TemplateConvolveAPGenerator.h.
TemplateArchive * TemplateConvolveAPGenerator::fTemplateArchive = NULL [static, private]
Definition at line 36 of file TemplateConvolveAPGenerator.h.
Referenced by TemplateConvolveAPGenerator().
double TemplateConvolveAPGenerator::fTemplatePed [private]
Definition at line 42 of file TemplateConvolveAPGenerator.h.
double TemplateConvolveAPGenerator::fTemplateTime [private]
Definition at line 42 of file TemplateConvolveAPGenerator.h.
double TemplateConvolveAPGenerator::fTicksPerNs [private]
Definition at line 44 of file TemplateConvolveAPGenerator.h.
Referenced by CalibrateTime().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/TemplateConvolveAPGenerator.h
rootana/src/TAP_generators/TemplateConvolveAPGenerator.cpp