AlcapDAQ: GaussFitAPGenerator Class Reference
GaussFitAPGenerator Class Reference
#include <GaussFitAPGenerator.h>
Classes
struct FittedVals
Public Member Functions
GaussFitAPGenerator (TAPGeneratorOptions *opts)
virtual ~GaussFitAPGenerator ()
virtual int ProcessPulses (const PulseIslandList &, AnalysedPulseList &)
This method is called on each vector of pulses from a MIDAS event.
virtual bool MayDivideTPIs ()
void FitPulse (const TPulseIsland *tpi, const int &id, FittedVals &tap)
void SetPulseList (PulseIslandList *list)
template<typename TypeOfTAP >
TypeOfTAP * MakeNewTAP (int parent_index) const
The suggested method for constructing a new TAP.
TAnalysedPulse * MakeNewTAP (int parent_index) const
bool Debug () const
IDs::channel GetChannel () const
std::string GetBank () const
const IDs::source & GetSource () const
Get the source id for this generator being used on the current channel.
virtual void CalibratePulses (AnalysedPulseList &theAnalysedPulses) const
Static Public Member Functions
static const char * TapType ()
Protected Member Functions
virtual void SetChannel (const std::string &det)
Set the channel for this generator. Should NOT be called by user code.
Private Types
enum FitParams {
kAmplitude = 0, kTime, kPedestal, kGradient,
kWidth, kNumParams
}
an enum to help keep the parameters being fitted in order
Private Attributes
double fMean
double fWidth
double fAmplitude
double fPedestal
double fGradient
TF1 * fFitFunc
Static Private Attributes
static const char * fFitName = "GausLinear"
Friends
class MakeAnalysedPulses
Detailed Description
Definition at line 9 of file GaussFitAPGenerator.h.
Member Enumeration Documentation
enum GaussFitAPGenerator::FitParams [private]
an enum to help keep the parameters being fitted in order
Enumerator:
kAmplitude
kTime
kPedestal
kGradient
kWidth
kNumParams
Definition at line 12 of file GaussFitAPGenerator.h.
{ kAmplitude=0, kTime , kPedestal , kGradient , kWidth ,kNumParams};
Constructor & Destructor Documentation
GaussFitAPGenerator::GaussFitAPGenerator (TAPGeneratorOptions * opts)
Definition at line 17 of file GaussFitAPGenerator.cpp.
References fAmplitude, fFitFunc, fFitName, fGradient, fMean, fPedestal, fWidth, functions::gauss_lin(), modules::options::GetDouble(), kAmplitude, kGradient, kPedestal, kTime, and kWidth.
                                                                 :
    TVAnalysedPulseGenerator("GaussFit",opts){
        // Do things to set up the generator here.
        fMean=opts->GetDouble("time",200);
        fWidth=opts->GetDouble("width",60);
        fAmplitude=opts->GetDouble("amplitude",200);
        fPedestal=opts->GetDouble("pedestal",0);
        fGradient=opts->GetDouble("gradient",0);
        fFitFunc=new TF1(fFitName,functions::gauss_lin,0,1000,5);
        fFitFunc->SetParName(kPedestal,"pedestal");
        fFitFunc->SetParName(kAmplitude,"amplitude");
        fFitFunc->SetParName(kWidth,"width");
        fFitFunc->SetParName(kGradient,"gradient");
        fFitFunc->SetParName(kTime,"time");
    }
virtual GaussFitAPGenerator::~GaussFitAPGenerator () [inline, virtual]
Definition at line 24 of file GaussFitAPGenerator.h.
{};
Member Function Documentation
void TVAnalysedPulseGenerator::CalibratePulses (AnalysedPulseList & theAnalysedPulses) const [virtual, inherited]
Definition at line 23 of file TVAnalysedPulseGenerator.cpp.
References TVAnalysedPulseGenerator::fAdcToEnergyGain, TVAnalysedPulseGenerator::fAdcToEnergyOffset, and TVAnalysedPulseGenerator::fCanCalibrate.
{
   if(fCanCalibrate){
      for(AnalysedPulseList::iterator i_tap=theAnalysedPulses.begin(); i_tap != theAnalysedPulses.end(); ++i_tap){
         const double amplitude=(*i_tap)->GetAmplitude();
         (*i_tap)->SetEnergy(fAdcToEnergyGain * amplitude + fAdcToEnergyOffset);
      }
   }
}
bool TVAnalysedPulseGenerator::Debug () const [inline, inherited]
Definition at line 77 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fDebug.
Referenced by FitPulse(), TemplateConvolveAPGenerator::ProcessPulses(), and IntegralRatioAPGenerator::ProcessPulses().
{return fDebug;};
void GaussFitAPGenerator::FitPulse (const TPulseIsland * tpi, const int & id, FittedVals & tap)
Definition at line 74 of file GaussFitAPGenerator.cpp.
References GaussFitAPGenerator::FittedVals::chi2, TVAnalysedPulseGenerator::Debug(), GaussFitAPGenerator::FittedVals::error, fAmplitude, fFitFunc, fGradient, fMean, fPedestal, fWidth, TPulseIsland::GetPulseLength(), TPulseIsland::GetPulseWaveform(), kAmplitude, kGradient, kPedestal, kTime, kWidth, GaussFitAPGenerator::FittedVals::status, and GaussFitAPGenerator::FittedVals::value.
Referenced by ProcessPulses().
{
    // Fill a TH1 with the TPI samples
    std::stringstream histname("tpi_");
    histname<<id;
    TH1I* hPulse = tpi->GetPulseWaveform(histname.str(), histname.str());
    // Set the parameters for the fit
    fFitFunc->SetParameters(fPedestal,fGradient,fAmplitude,fMean,fWidth);
    fFitFunc->SetRange(0,tpi->GetPulseLength());
    // Perform the fit
    std::string options ="S R";
    if(!Debug()) options+=" Q";
    TFitResultPtr result=hPulse->Fit(fFitFunc,options.c_str());
    // Get the values from the fit
    tap.value[kAmplitude] = fFitFunc->GetParameter(kAmplitude);
    tap.value[kTime     ] = fFitFunc->GetParameter(kTime);
    tap.value[kPedestal ] = fFitFunc->GetParameter(kPedestal);
    tap.value[kGradient ] = fFitFunc->GetParameter(kGradient);
    tap.value[kWidth    ] = fFitFunc->GetParameter(kWidth);
    // Get errors from the fit
    tap.error[kAmplitude] = fFitFunc->GetParError(kAmplitude);
    tap.error[kTime     ] = fFitFunc->GetParError(kTime);
    tap.error[kPedestal ] = fFitFunc->GetParError(kPedestal);
    tap.error[kGradient ] = fFitFunc->GetParError(kGradient);
    tap.error[kWidth    ] = fFitFunc->GetParError(kWidth);
    // Set other fit properties
    tap.chi2          = result->Chi2();
    tap.status        = result;
    delete hPulse;
}
std::string TVAnalysedPulseGenerator::GetBank () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 85 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fBankName.
{return fBankName;};
IDs::channel TVAnalysedPulseGenerator::GetChannel () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 81 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), and TVAnalysedPulseGenerator::fSource.
Referenced by FirstCompleteAPGenerator::DrawPulse(), FirstCompleteAPGenerator::FirstCompleteAPGenerator(), IntegralRatioAPGenerator::ProcessPulses(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{return fSource.Channel();};
const IDs::source& TVAnalysedPulseGenerator::GetSource () const [inline, inherited]
Get the source id for this generator being used on the current channel.
Useful for a generator to know the full source much like in the above GetChannel method, but this could also be useful for checking that this generator is the one that made a given TAP in later analysis by comparing this value to that stored in the TAP itself.
Definition at line 94 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fSource.
Referenced by TVAnalysedPulseGenerator::MakeNewTAP(), and IntegralRatioAPGenerator::ProcessPulses().
{return fSource;};
TAnalysedPulse* TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
Definition at line 73 of file TVAnalysedPulseGenerator.h.
{
            return MakeNewTAP<TAnalysedPulse>(parent_index);
        }
template<typename TypeOfTAP > TypeOfTAP * TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
The suggested method for constructing a new TAP.
In the process of constructing TAP, information that isn't immediately obvious how to get needs to be passed to TAP. This method returns a pointer to a TAP construced for you, and all you need to pass it is the TPulseIslandID.
In the case where a generator wants to add extra information to the standard TAP information, we expect people to derive from TAnalysedPulse. If your generator is one of these, then use the template argument to produce the type of TAP you desire. Note that this forces the constructor of the specialised TAP to be the same as for TAnalysedPulse itself.
For example, for to make a specialied analysed pulse called TSpecialAnalysedPulse (original, huh?) you would do:
 TSpecialAnalysedPulse* tsap=MakeNewTAP<TSpecialAnalysedPulse>(parent_index);
Parameters:
[in] parent_index The TPulseIslandID of the TPI being used to make the new TAP.
Template Parameters:
in] TypeOfTAP The type of specialisation of TAnalysedPulse that you want to create.
Definition at line 137 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList, and TVAnalysedPulseGenerator::GetSource().
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), SimpIntAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), CFTimeMBAmpAPGenerator::ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{
    TypeOfTAP* pulse=NULL;
    TPulseIsland* parent = fPulseList->at(parent_index);
    pulse=new TypeOfTAP(GetSource(),parent_index,parent);
    return pulse;
}
virtual bool GaussFitAPGenerator::MayDivideTPIs () [inline, virtual]
Todo:
Document this
Implements TVAnalysedPulseGenerator.
Definition at line 31 of file GaussFitAPGenerator.h.
{return false;};
int GaussFitAPGenerator::ProcessPulses (const PulseIslandList & pil, AnalysedPulseList & apl) [virtual]
This method is called on each vector of pulses from a MIDAS event.
Parameters:
[in] pil The vector of TPIs to produce TAPs from.
[out] apl The vector of TAPs to append the new TAPs to.
Implements TVAnalysedPulseGenerator.
Definition at line 34 of file GaussFitAPGenerator.cpp.
References ExportPulse::AddToExportList(), GaussFitAPGenerator::FittedVals::chi2, GaussFitAPGenerator::FittedVals::error, FitPulse(), ExportPulse::Instance(), kAmplitude, kGradient, kPedestal, kWidth, TGaussFitAnalysedPulse::SetAmplitude(), TGaussFitAnalysedPulse::SetChi2(), TGaussFitAnalysedPulse::SetFitStatus(), TGaussFitAnalysedPulse::SetGradient(), TGaussFitAnalysedPulse::SetPedestal(), TGaussFitAnalysedPulse::SetWidth(), GaussFitAPGenerator::FittedVals::status, and GaussFitAPGenerator::FittedVals::value.
{
    // Do something here that takes the TPIs in the PulseIslandList and
    // fills the list of TAPS
    // Loop over all the TPIs given to us
    TGaussFitAnalysedPulse* tap;
    FittedVals tap_data;
    int index;
    for (PulseIslandList::const_iterator tpi=pulseList.begin();
            tpi!=pulseList.end(); tpi++){
        // Analyse each TPI
        index=tpi-pulseList.begin();
        FitPulse(*tpi,index,tap_data);
        // Make a TGaussFitAnalysedPulse
        tap = MakeNewTAP<TGaussFitAnalysedPulse>(index);
        // Now assign all the measure values
        tap->SetAmplitude ( tap_data.value[kAmplitude] , tap_data.error[kAmplitude] );
        tap->SetPedestal  ( tap_data.value[kPedestal]  , tap_data.error[kPedestal]  );
        tap->SetGradient  ( tap_data.value[kGradient]  , tap_data.error[kGradient]  );
        tap->SetWidth     ( tap_data.value[kWidth]     , tap_data.error[kWidth]     );
        tap->SetChi2      ( tap_data.chi2   );
        tap->SetFitStatus ( tap_data.status );
        if(ExportPulse::Instance() && tap_data.status!=0){
            ExportPulse::Instance()->AddToExportList(tap);
        }
        // Finally add the new TAP to the output list
        analysedList.push_back(tap);
    }
    // returning 0 tells the caller that we were successful, return non-zero if not
    return 0;
}
virtual void TVAnalysedPulseGenerator::SetChannel (const std::string & det) [inline, protected, virtual, inherited]
Set the channel for this generator. Should NOT be called by user code.
Called by MakeAnalysedPulses to tell this generator what channel it is looking at.
Definition at line 108 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), TVAnalysedPulseGenerator::fBankName, TVAnalysedPulseGenerator::fSource, SetupNavigator::GetBank(), and SetupNavigator::Instance().
Referenced by TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{
           fSource.Channel()=det;
           fBankName= SetupNavigator::Instance()->GetBank(det);
         };
void TVAnalysedPulseGenerator::SetPulseList (PulseIslandList * list) [inline, inherited]
Definition at line 44 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList.
{fPulseList=list;};
const char * GaussFitAPGenerator::TapType () [static]
Reimplemented from TVAnalysedPulseGenerator.
Definition at line 112 of file GaussFitAPGenerator.cpp.
{
    return TGaussFitAnalysedPulse::Class()->GetName();
}
Friends And Related Function Documentation
friend class MakeAnalysedPulses [friend, inherited]
Definition at line 101 of file TVAnalysedPulseGenerator.h.
Member Data Documentation
double GaussFitAPGenerator::fAmplitude [private]
Definition at line 37 of file GaussFitAPGenerator.h.
Referenced by FitPulse(), and GaussFitAPGenerator().
TF1* GaussFitAPGenerator::fFitFunc [private]
Definition at line 38 of file GaussFitAPGenerator.h.
Referenced by FitPulse(), and GaussFitAPGenerator().
const char * GaussFitAPGenerator::fFitName = "GausLinear" [static, private]
Definition at line 39 of file GaussFitAPGenerator.h.
Referenced by GaussFitAPGenerator().
double GaussFitAPGenerator::fGradient [private]
Definition at line 37 of file GaussFitAPGenerator.h.
Referenced by FitPulse(), and GaussFitAPGenerator().
double GaussFitAPGenerator::fMean [private]
Definition at line 37 of file GaussFitAPGenerator.h.
Referenced by FitPulse(), and GaussFitAPGenerator().
double GaussFitAPGenerator::fPedestal [private]
Definition at line 37 of file GaussFitAPGenerator.h.
Referenced by FitPulse(), and GaussFitAPGenerator().
double GaussFitAPGenerator::fWidth [private]
Definition at line 37 of file GaussFitAPGenerator.h.
Referenced by FitPulse(), and GaussFitAPGenerator().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/GaussFitAPGenerator.h
rootana/src/TAP_generators/GaussFitAPGenerator.cpp