AlcapDAQ: SavePulses Class Reference
SavePulses Class Reference
[Modules]
A one line description of what your module does.
#include <SavePulses.h>
Public Member Functions
SavePulses (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~SavePulses ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef std::map< IDs::source,
TClonesArray * > SourceToClonesArrayMap
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Private Attributes
TTree * fTree
SourceToClonesArrayMap fArrays
Detailed Description
A one line description of what your module does.
Author:
AuthorName
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 26 of file SavePulses.h.
Member Typedef Documentation
typedef std::map<IDs::source,TClonesArray*> SavePulses::SourceToClonesArrayMap [private]
Definition at line 28 of file SavePulses.h.
Constructor & Destructor Documentation
SavePulses::SavePulses (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 22 of file SavePulses.cpp.
References fTree.
                                          :
   BaseModule("SavePulses",opts,false){
       fTree=new TTree("TAP_tree","Tree storing all TAPs made in rootana");
}
SavePulses::~SavePulses ()
Is anything done in the destructor?
Definition at line 27 of file SavePulses.cpp.
                       {
}
Member Function Documentation
int SavePulses::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 76 of file SavePulses.cpp.
References BaseModule::GetDirectory().
{
    FlyWeight<IDs::source,TAnalysedPulse::Tag>::SaveProxyList(GetDirectory(),"TAP_sources");
  return 0;
}
int SavePulses::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 30 of file SavePulses.cpp.
References fArrays, fTree, gAnalysedPulseMap, BaseModule::GetName(), TAPGeneratorFactory::GetTAPType(), TAPGeneratorFactory::Instance(), modules::navigator::Instance(), and modules::parser::ToCppValid().
{
    // Check we're after MakeAnalysedPulses
    if(!modules::navigator::Instance()->Before("MakeAnalysedPulses",GetName())){
        cout<<"SavePulses: Error: I need to be run after MakeAnalysedPulses"<<endl;
        return 1;
    }
    // Loop over gAnalysedPulseMap and add a branch for each source
    TClonesArray* array;
    std::string name;
    for (SourceAnalPulseMap::const_iterator i_source = gAnalysedPulseMap.begin();
            i_source != gAnalysedPulseMap.end(); ++i_source) {
        std::string tap_type=TAPGeneratorFactory::Instance()->GetTAPType(i_source->first);
        array=new TClonesArray(tap_type.c_str());
        fArrays[i_source->first]=array;
        name=i_source->first.str();
        modules::parser::ToCppValid(name);
        fTree->Branch(name.c_str(), array);
    }
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int SavePulses::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 54 of file SavePulses.cpp.
References fArrays, fTree, and gAnalysedPulseMap.
{
    const AnalysedPulseList* pulseList;
    TClonesArray* array;
    TObject* tap;
    for (SourceAnalPulseMap::const_iterator i_source = gAnalysedPulseMap.begin();
            i_source != gAnalysedPulseMap.end(); ++i_source) {
        pulseList=&i_source->second;
        array=fArrays[i_source->first];
        for (AnalysedPulseList::const_iterator i_pulse = pulseList->begin();
                i_pulse != pulseList->end(); ++i_pulse) {
            tap= array->ConstructedAt(i_pulse-pulseList->begin());
            (*i_pulse)->Copy(*tap);
        }
    }
    fTree->Fill();
    for(SourceToClonesArrayMap::iterator i_array=fArrays.begin();
            i_array!=fArrays.end(); ++i_array){
        i_array->second->Clear("C");
    }
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
SourceToClonesArrayMap SavePulses::fArrays [private]
Definition at line 62 of file SavePulses.h.
Referenced by BeforeFirstEntry(), and ProcessEntry().
TTree* SavePulses::fTree [private]
Definition at line 61 of file SavePulses.h.
Referenced by BeforeFirstEntry(), ProcessEntry(), and SavePulses().
The documentation for this class was generated from the following files:
rootana/src/SavePulses.h
rootana/src/SavePulses.cpp