AlcapDAQ: MaxTimeDiffDPGenerator Class Reference
MaxTimeDiffDPGenerator Class Reference
#include <MaxTimeDiffDPGenerator.h>
Public Member Functions
MaxTimeDiffDPGenerator (TDPGeneratorOptions *opts)
virtual ~MaxTimeDiffDPGenerator ()
virtual bool ChecksForPileUp () const
virtual int ProcessPulses (DetectorPulseList &output)
void SetPulseSources (const IDs::source &fast, const IDs::source &slow)
void SetPulseLists (const AnalysedPulseList *fast, const AnalysedPulseList *slow)
void SetDebug (const bool &val=true)
bool Debug ()
TDetectorPulse * MakeTDP (int fast_parent, int slow_parent) const
IDs::source GetSource () const
IDs::source GetFastSource () const
IDs::source GetSlowSource () const
void SetChannel (const IDs::channel &ch)
IDs::generator GetGeneratorID () const
const AnalysedPulseList * FastPulseList () const
const AnalysedPulseList * SlowPulseList () const
Private Attributes
double fTimeDifference
Detailed Description
Definition at line 6 of file MaxTimeDiffDPGenerator.h.
Constructor & Destructor Documentation
MaxTimeDiffDPGenerator::MaxTimeDiffDPGenerator (TDPGeneratorOptions * opts)
Definition at line 10 of file MaxTimeDiffDPGenerator.cpp.
References fTimeDifference, and modules::options::GetDouble().
                                                                       :
    TVDetectorPulseGenerator("MaxTimeDiff",opts),fTimeDifference(0.1){
        fTimeDifference=opts->GetDouble("time_difference",fTimeDifference);
    }
virtual MaxTimeDiffDPGenerator::~MaxTimeDiffDPGenerator () [inline, virtual]
Definition at line 10 of file MaxTimeDiffDPGenerator.h.
{};
Member Function Documentation
virtual bool MaxTimeDiffDPGenerator::ChecksForPileUp () const [inline, virtual]
Implements TVDetectorPulseGenerator.
Definition at line 11 of file MaxTimeDiffDPGenerator.h.
{return false;};
bool TVDetectorPulseGenerator::Debug () [inline, inherited]
Definition at line 34 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fDebug.
Referenced by ProcessPulses().
{return fDebug;};
const AnalysedPulseList* TVDetectorPulseGenerator::FastPulseList () const [inline, inherited]
Definition at line 53 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fFastPulses.
Referenced by PassThroughDPGenerator::ProcessPulses(), and ProcessPulses().
{return fFastPulses;}
IDs::source TVDetectorPulseGenerator::GetFastSource () const [inline, inherited]
Definition at line 48 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fFastSource.
Referenced by ProcessPulses().
{return fFastSource;};
IDs::generator TVDetectorPulseGenerator::GetGeneratorID () const [inline, inherited]
Definition at line 51 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fSource, and IDs::source::Generator().
Referenced by MakeDetectorPulses::BeforeFirstEntry().
{return fSource.Generator();}
IDs::source TVDetectorPulseGenerator::GetSlowSource () const [inline, inherited]
Definition at line 49 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fSlowSource.
Referenced by ProcessPulses().
{return fSlowSource;};
IDs::source TVDetectorPulseGenerator::GetSource () const [inline, inherited]
Definition at line 47 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fSource.
Referenced by MakeDetectorPulses::GetPassThruGeneratorID(), and TVDetectorPulseGenerator::MakeTDP().
{return fSource;};
TDetectorPulse* TVDetectorPulseGenerator::MakeTDP (int fast_parent, int slow_parent) const [inline, inherited]
Definition at line 36 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fFastPulses, TVDetectorPulseGenerator::fSlowPulses, and TVDetectorPulseGenerator::GetSource().
Referenced by PassThroughDPGenerator::ProcessPulses(), and ProcessPulses().
{
      TDetectorPulse* pulse=NULL;
      const TAnalysedPulse* fast=NULL;
      if(fFastPulses && fast_parent>=0) fast=fFastPulses->at(fast_parent);
      const TAnalysedPulse* slow=NULL;
      if(fSlowPulses && slow_parent>=0) slow=fSlowPulses->at(slow_parent);
      if(fast || slow) {
          pulse=new TDetectorPulse(GetSource(),fast_parent,fast,slow_parent,slow);
      }
      return pulse;
  }
int MaxTimeDiffDPGenerator::ProcessPulses (DetectorPulseList & output) [virtual]
Implements TVDetectorPulseGenerator.
Definition at line 15 of file MaxTimeDiffDPGenerator.cpp.
References TVDetectorPulseGenerator::Debug(), TVDetectorPulseGenerator::FastPulseList(), fTimeDifference, TVDetectorPulseGenerator::GetFastSource(), TVDetectorPulseGenerator::GetSlowSource(), TAnalysedPulse::GetSource(), TDetectorPulse::GetTime(), TAnalysedPulse::GetTime(), GetTime(), IDs::source::isFast(), IDs::source::isSlow(), TDetectorPulse::kFast, TDetectorPulse::kSlow, TVDetectorPulseGenerator::MakeTDP(), TVDetectorPulseGenerator::SlowPulseList(), and IDs::source::str().
{
    if(!SlowPulseList()) {
        cout<<"Error: No pulse list for slow channel, "<<GetFastSource()<<" with MaxTimeDiffDPGenerator"<<endl;
        return 1;
    } else if(!FastPulseList()) {
        cout<<"Error: No pulse list for fast channel, "<<GetSlowSource()<<" with MaxTimeDiffDPGenerator"<<endl;
        return 2;
    }
    AnalysedPulseList::const_iterator fastPulseIter = FastPulseList()->begin();
    AnalysedPulseList::const_iterator slowPulseIter = SlowPulseList()->begin();
    AnalysedPulseList::const_iterator finalFastPulseIter = FastPulseList()->end();
    AnalysedPulseList::const_iterator finalSlowPulseIter = SlowPulseList()->end();
    std::vector< std::pair<
        AnalysedPulseList::const_iterator,
        AnalysedPulseList::const_iterator> > pulseIters;
    pulseIters.push_back(std::make_pair(fastPulseIter,finalFastPulseIter));
    pulseIters.push_back(std::make_pair(slowPulseIter,finalSlowPulseIter));
    // Loop through both TAnalysedPulse vectors until they are both finished
    // NB with this alogirthm this can be extended to more than 2
    double min_time = 999999; // something large
    double pulse_time;
    //int count=0;
    int fast_pulse, slow_pulse;
    while (pulseIters.size() > 0) {
        fast_pulse=-1.;
        slow_pulse=-1.;
        min_time = 999999e9;
        // Find out which of the next fast or slow pulses happened next
        for (unsigned int b = 0; b < pulseIters.size(); ++b) {
            pulse_time = (*pulseIters.at(b).first)->GetTime() * 1e-6; // convert to ms
            min_time = std::min(min_time, pulse_time);
        }
        // Now go through and find all the pulses that are within a certain time of this
        for (unsigned int b = 0; b < pulseIters.size(); ++b) {
            TAnalysedPulse* pulse = *(pulseIters[b].first);
            double pulse_time = pulse->GetTime() * 1e-6; // convert to ms
            if (std::fabs(pulse_time - min_time) < fTimeDifference) {
                if ( pulse->GetSource().isFast()) {
                    if(Debug()) cout<<"Fast? " << pulse->GetSource().str() << std::endl;
                    fast_pulse = pulseIters[b].first - FastPulseList()->begin();
                } else if ( pulse->GetSource().isSlow()) {
                    if(Debug()) cout<<"Slow? " << pulse->GetSource().str() << std::endl;
                    slow_pulse = pulseIters[b].first - SlowPulseList()->begin();
                }
                ++(pulseIters[b].first); // increment the iterator because we used the pulse
            }
        }
        TDetectorPulse* det_pulse = MakeTDP( fast_pulse, slow_pulse); // Create the TDetectorPulse
        if(det_pulse){
            output.push_back(det_pulse);
            if(Debug()){
                cout<<"Created a TDetectorPulse with:\n";
                cout<<"Fast Pulse: " << det_pulse->GetTime(TDetectorPulse::kFast) * 1e-6 << std::endl;
                cout<< "Slow Pulse: " << det_pulse->GetTime(TDetectorPulse::kSlow) * 1e-6 << std::endl;
                cout<< std::endl;
            }
        }
        //Delete the iterators to finished banks. Go through in reverse to
        //avoid invalidation problems
        for (int b = pulseIters.size()-1; b >= 0; --b) {
            if (pulseIters[b].first == pulseIters[b].second){
                pulseIters.erase(pulseIters.begin() + b);
            }
        } // for (int b -reversed)
    } // end for
    return 0;
}
void TVDetectorPulseGenerator::SetChannel (const IDs::channel & ch) [inline, inherited]
Definition at line 50 of file TVDetectorPulseGenerator.h.
References IDs::source::Channel(), and TVDetectorPulseGenerator::fSource.
{fSource.Channel()=ch;};
void TVDetectorPulseGenerator::SetDebug (const bool & val = true) [inline, inherited]
Definition at line 33 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fDebug.
Referenced by MakeDetectorPulses::MakeGenerator().
{fDebug=val;};
void TVDetectorPulseGenerator::SetPulseLists (const AnalysedPulseList * fast, const AnalysedPulseList * slow) [inline, inherited]
Definition at line 28 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fFastPulses, and TVDetectorPulseGenerator::fSlowPulses.
{
      fFastPulses=fast;
      fSlowPulses=slow;
  }
void TVDetectorPulseGenerator::SetPulseSources (const IDs::source & fast, const IDs::source & slow) [inline, inherited]
Definition at line 24 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fFastSource, and TVDetectorPulseGenerator::fSlowSource.
{
      fFastSource=fast;
      fSlowSource=slow;
  }
const AnalysedPulseList* TVDetectorPulseGenerator::SlowPulseList () const [inline, inherited]
Definition at line 54 of file TVDetectorPulseGenerator.h.
References TVDetectorPulseGenerator::fSlowPulses.
Referenced by ProcessPulses().
{return fSlowPulses;}
Member Data Documentation
double MaxTimeDiffDPGenerator::fTimeDifference [private]
Definition at line 17 of file MaxTimeDiffDPGenerator.h.
Referenced by MaxTimeDiffDPGenerator(), and ProcessPulses().
The documentation for this class was generated from the following files:
rootana/src/TDP_generators/MaxTimeDiffDPGenerator.h
rootana/src/TDP_generators/MaxTimeDiffDPGenerator.cpp