AlcapDAQ: FirstCompleteAPGenerator Class Reference
FirstCompleteAPGenerator Class Reference
#include <FirstCompleteAPGenerator.h>
Public Member Functions
FirstCompleteAPGenerator (TAPGeneratorOptions *opts)
virtual ~FirstCompleteAPGenerator ()
virtual int ProcessPulses (const PulseIslandList &, AnalysedPulseList &)
This method is called on each vector of pulses from a MIDAS event.
virtual bool MayDivideTPIs ()
void SetPulseList (PulseIslandList *list)
template<typename TypeOfTAP >
TypeOfTAP * MakeNewTAP (int parent_index) const
The suggested method for constructing a new TAP.
TAnalysedPulse * MakeNewTAP (int parent_index) const
bool Debug () const
IDs::channel GetChannel () const
std::string GetBank () const
const IDs::source & GetSource () const
Get the source id for this generator being used on the current channel.
virtual void CalibratePulses (AnalysedPulseList &theAnalysedPulses) const
Static Public Member Functions
static const char * TapType ()
Protected Member Functions
virtual void SetChannel (const std::string &det)
Set the channel for this generator. Should NOT be called by user code.
Private Member Functions
void DrawPulse (int original, int pulse_timestamp, int n_pulse_samples)
void MakeTAPsWithPCF (int tpi_ID, const TPulseIsland *tpi, AnalysedPulseList &analysedList)
void AnalyseOneTpi (int tpi_ID, const TPulseIsland *tpi, AnalysedPulseList &analysedList)
Private Attributes
const Algorithm::MaxBinAmplitude fMaxBinAmplitude
const
Algorithm::ConstantFractionTime fConstantFractionTime
const Algorithm::SimpleIntegral fSimpleIntegral
PulseCandidateFinder * fPulseCandidateFinder
PulseIslandList fSubPulses
Friends
class MakeAnalysedPulses
Detailed Description
Definition at line 11 of file FirstCompleteAPGenerator.h.
Constructor & Destructor Documentation
FirstCompleteAPGenerator::FirstCompleteAPGenerator (TAPGeneratorOptions * opts)
Definition at line 15 of file FirstCompleteAPGenerator.cpp.
References TAPGeneratorOptions::Debug(), fPulseCandidateFinder, modules::options::GetBool(), TVAnalysedPulseGenerator::GetChannel(), and modules::options::SetOption().
                                                                           :
  TVAnalysedPulseGenerator("FirstComplete",opts),
  fMaxBinAmplitude(SetupNavigator::Instance()->GetPedestal(GetChannel()),
                   TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(GetChannel().str()))),
  fConstantFractionTime(SetupNavigator::Instance()->GetPedestal(GetChannel()),
                        TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        TSetupData::Instance()->GetClockTick(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        opts->GetBool("no_time_shift", false) ? 0. : SetupNavigator::Instance()->GetCoarseTimeOffset(GetSource()),
                        opts->GetDouble("constant_fraction")),
  fSimpleIntegral(SetupNavigator::Instance()->GetPedestal(GetChannel()),
                  TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(GetChannel().str()))),
  fPulseCandidateFinder(NULL) {
  if(opts->GetBool("use_pcf",true)){
     if(opts->Debug()) opts->SetOption("debug","true");
     fPulseCandidateFinder=new PulseCandidateFinder(GetChannel().str(), opts);
  }
}
FirstCompleteAPGenerator::~FirstCompleteAPGenerator () [virtual]
Definition at line 33 of file FirstCompleteAPGenerator.cpp.
References fSubPulses.
{
    // delete all sub-pulses
    for(PulseIslandList::iterator i_tpi=fSubPulses.begin(); i_tpi!=fSubPulses.end(); ++i_tpi){
        delete *i_tpi;
    }
}
Member Function Documentation
void FirstCompleteAPGenerator::AnalyseOneTpi (int tpi_ID, const TPulseIsland * tpi, AnalysedPulseList & analysedList) [private]
Definition at line 65 of file FirstCompleteAPGenerator.cpp.
References fConstantFractionTime, fMaxBinAmplitude, fSimpleIntegral, TPulseIsland::GetPulseLength(), TVAnalysedPulseGenerator::MakeNewTAP(), TAnalysedPulse::SetAmplitude(), TAnalysedPulse::SetIntegral(), and TAnalysedPulse::SetTime().
Referenced by MakeTAPsWithPCF(), and ProcessPulses().
{
    if(tpi->GetPulseLength() < 14) return;
    // Analyse each TPI
    double amplitude=fMaxBinAmplitude(tpi);
    double time=fConstantFractionTime(tpi);
    double integral=fSimpleIntegral(tpi);
    // Now that we've found the information we were looking for make a TAP to
    // hold it.  This method makes a TAP and sets the parent TPI info.  It needs
    // the index of the parent TPI in the container as an argument
    TAnalysedPulse* tap = MakeNewTAP(tpi_ID);
    tap->SetAmplitude(amplitude);
    tap->SetTime(time);
    tap->SetIntegral(integral);
    // Finally add the new TAP to the output list
    analysedList.push_back(tap);
}
void TVAnalysedPulseGenerator::CalibratePulses (AnalysedPulseList & theAnalysedPulses) const [virtual, inherited]
Definition at line 23 of file TVAnalysedPulseGenerator.cpp.
References TVAnalysedPulseGenerator::fAdcToEnergyGain, TVAnalysedPulseGenerator::fAdcToEnergyOffset, and TVAnalysedPulseGenerator::fCanCalibrate.
{
   if(fCanCalibrate){
      for(AnalysedPulseList::iterator i_tap=theAnalysedPulses.begin(); i_tap != theAnalysedPulses.end(); ++i_tap){
         const double amplitude=(*i_tap)->GetAmplitude();
         (*i_tap)->SetEnergy(fAdcToEnergyGain * amplitude + fAdcToEnergyOffset);
      }
   }
}
bool TVAnalysedPulseGenerator::Debug () const [inline, inherited]
Definition at line 77 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fDebug.
Referenced by GaussFitAPGenerator::FitPulse(), TemplateConvolveAPGenerator::ProcessPulses(), and IntegralRatioAPGenerator::ProcessPulses().
{return fDebug;};
void FirstCompleteAPGenerator::DrawPulse (int original, int pulse_timestamp, int n_pulse_samples) [private]
Definition at line 85 of file FirstCompleteAPGenerator.cpp.
References EventNavigator::EntryNo(), fSubPulses, TVAnalysedPulseGenerator::GetChannel(), EventNavigator::Instance(), and modules::parser::ToCppValid().
{
  /*    if( ExportPulse::Instance())
        ExportPulse::Instance()->AddToExportList(GetChannel().str(), original);
    else return;
  */
    for (std::vector<TPulseIsland*>::const_iterator subPulseIter = fSubPulses.begin();
            subPulseIter != fSubPulses.end(); ++subPulseIter) {
        std::stringstream histname;
        histname << "hSubPulse_" << GetChannel() << "_Event"
            << EventNavigator::Instance().EntryNo() <<"_Pulse" << original
            << "_SubPulse" << subPulseIter - fSubPulses.begin();
        const std::vector<int>& sub_pulse_samples = (*subPulseIter)->GetSamples();
        TH1D* hPulse = new TH1D(modules::parser::ToCppValid(histname.str()).c_str(),
                histname.str().c_str(), n_pulse_samples,0,n_pulse_samples);
        hPulse->SetLineColor(kMagenta);
        int delay = (*subPulseIter)->GetTimeStamp() - pulse_timestamp;
        for (std::vector<int>::const_iterator subPulseSampleIter = sub_pulse_samples.begin();
                subPulseSampleIter != sub_pulse_samples.end(); ++subPulseSampleIter) {
            hPulse->Fill( (subPulseSampleIter - sub_pulse_samples.begin()) + delay, (*subPulseSampleIter) );
        }
    }
}
std::string TVAnalysedPulseGenerator::GetBank () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 85 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fBankName.
{return fBankName;};
IDs::channel TVAnalysedPulseGenerator::GetChannel () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 81 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), and TVAnalysedPulseGenerator::fSource.
Referenced by DrawPulse(), FirstCompleteAPGenerator(), IntegralRatioAPGenerator::ProcessPulses(), TemplateConvolveAPGenerator::TemplateConvolveAPGenerator(), TemplateFitAPGenerator::TemplateFitAPGenerator(), and TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{return fSource.Channel();};
const IDs::source& TVAnalysedPulseGenerator::GetSource () const [inline, inherited]
Get the source id for this generator being used on the current channel.
Useful for a generator to know the full source much like in the above GetChannel method, but this could also be useful for checking that this generator is the one that made a given TAP in later analysis by comparing this value to that stored in the TAP itself.
Definition at line 94 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fSource.
Referenced by TVAnalysedPulseGenerator::MakeNewTAP(), and IntegralRatioAPGenerator::ProcessPulses().
{return fSource;};
TAnalysedPulse* TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
Definition at line 73 of file TVAnalysedPulseGenerator.h.
{
            return MakeNewTAP<TAnalysedPulse>(parent_index);
        }
template<typename TypeOfTAP > TypeOfTAP * TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
The suggested method for constructing a new TAP.
In the process of constructing TAP, information that isn't immediately obvious how to get needs to be passed to TAP. This method returns a pointer to a TAP construced for you, and all you need to pass it is the TPulseIslandID.
In the case where a generator wants to add extra information to the standard TAP information, we expect people to derive from TAnalysedPulse. If your generator is one of these, then use the template argument to produce the type of TAP you desire. Note that this forces the constructor of the specialised TAP to be the same as for TAnalysedPulse itself.
For example, for to make a specialied analysed pulse called TSpecialAnalysedPulse (original, huh?) you would do:
 TSpecialAnalysedPulse* tsap=MakeNewTAP<TSpecialAnalysedPulse>(parent_index);
Parameters:
[in] parent_index The TPulseIslandID of the TPI being used to make the new TAP.
Template Parameters:
in] TypeOfTAP The type of specialisation of TAnalysedPulse that you want to create.
Definition at line 137 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList, and TVAnalysedPulseGenerator::GetSource().
Referenced by AnalyseOneTpi(), SimpIntAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), CFTimeMBAmpAPGenerator::ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{
    TypeOfTAP* pulse=NULL;
    TPulseIsland* parent = fPulseList->at(parent_index);
    pulse=new TypeOfTAP(GetSource(),parent_index,parent);
    return pulse;
}
void FirstCompleteAPGenerator::MakeTAPsWithPCF (int tpi_ID, const TPulseIsland * tpi, AnalysedPulseList & analysedList) [private]
Definition at line 54 of file FirstCompleteAPGenerator.cpp.
References AnalyseOneTpi(), PulseCandidateFinder::FindPulseCandidates(), fPulseCandidateFinder, fSubPulses, and PulseCandidateFinder::GetPulseCandidates().
Referenced by ProcessPulses().
{
    // Look for more than one pulse on the TPI
    fPulseCandidateFinder->FindPulseCandidates(original_tpi);
    fPulseCandidateFinder->GetPulseCandidates(fSubPulses);
    // now loop over all sub-pulses
    for(PulseIslandList::const_iterator i_tpi=fSubPulses.begin(); i_tpi!=fSubPulses.end(); ++i_tpi){
        AnalyseOneTpi( tpi_ID, *i_tpi,analysedList);
    }
}
virtual bool FirstCompleteAPGenerator::MayDivideTPIs () [inline, virtual]
Todo:
Document this
Implements TVAnalysedPulseGenerator.
Definition at line 22 of file FirstCompleteAPGenerator.h.
{return true;};
int FirstCompleteAPGenerator::ProcessPulses (const PulseIslandList & pil, AnalysedPulseList & apl) [virtual]
This method is called on each vector of pulses from a MIDAS event.
Parameters:
[in] pil The vector of TPIs to produce TAPs from.
[out] apl The vector of TAPs to append the new TAPs to.
Implements TVAnalysedPulseGenerator.
Definition at line 40 of file FirstCompleteAPGenerator.cpp.
References AnalyseOneTpi(), fPulseCandidateFinder, and MakeTAPsWithPCF().
{
    // Loop over all the TPIs given to us
    for (PulseIslandList::const_iterator i_tpi=pulseList.begin();
            i_tpi!=pulseList.end(); ++i_tpi){
        int tpi_ID = i_tpi - pulseList.begin();
        if(fPulseCandidateFinder) MakeTAPsWithPCF(tpi_ID,*i_tpi,analysedList);
        else AnalyseOneTpi(tpi_ID, *i_tpi,analysedList);
    }
    return 0;
}
virtual void TVAnalysedPulseGenerator::SetChannel (const std::string & det) [inline, protected, virtual, inherited]
Set the channel for this generator. Should NOT be called by user code.
Called by MakeAnalysedPulses to tell this generator what channel it is looking at.
Definition at line 108 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), TVAnalysedPulseGenerator::fBankName, TVAnalysedPulseGenerator::fSource, SetupNavigator::GetBank(), and SetupNavigator::Instance().
Referenced by TVAnalysedPulseGenerator::TVAnalysedPulseGenerator().
{
           fSource.Channel()=det;
           fBankName= SetupNavigator::Instance()->GetBank(det);
         };
void TVAnalysedPulseGenerator::SetPulseList (PulseIslandList * list) [inline, inherited]
Definition at line 44 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList.
{fPulseList=list;};
static const char* TVAnalysedPulseGenerator::TapType () [inline, static, inherited]
Reimplemented in GaussFitAPGenerator, IntegralRatioAPGenerator, TemplateConvolveAPGenerator, and TemplateFitAPGenerator.
Definition at line 96 of file TVAnalysedPulseGenerator.h.
{return TAnalysedPulse::Class()->GetName();}
Friends And Related Function Documentation
friend class MakeAnalysedPulses [friend, inherited]
Definition at line 101 of file TVAnalysedPulseGenerator.h.
Member Data Documentation
const Algorithm::ConstantFractionTime FirstCompleteAPGenerator::fConstantFractionTime [private]
Definition at line 31 of file FirstCompleteAPGenerator.h.
Referenced by AnalyseOneTpi().
const Algorithm::MaxBinAmplitude FirstCompleteAPGenerator::fMaxBinAmplitude [private]
Definition at line 30 of file FirstCompleteAPGenerator.h.
Referenced by AnalyseOneTpi().
PulseCandidateFinder* FirstCompleteAPGenerator::fPulseCandidateFinder [private]
Definition at line 35 of file FirstCompleteAPGenerator.h.
Referenced by FirstCompleteAPGenerator(), MakeTAPsWithPCF(), and ProcessPulses().
const Algorithm::SimpleIntegral FirstCompleteAPGenerator::fSimpleIntegral [private]
Definition at line 32 of file FirstCompleteAPGenerator.h.
Referenced by AnalyseOneTpi().
PulseIslandList FirstCompleteAPGenerator::fSubPulses [private]
Definition at line 39 of file FirstCompleteAPGenerator.h.
Referenced by DrawPulse(), MakeTAPsWithPCF(), and ~FirstCompleteAPGenerator().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/FirstCompleteAPGenerator.h
rootana/src/TAP_generators/FirstCompleteAPGenerator.cpp