AlcapDAQ: TTemplateFitAnalysedPulse Class Reference
TTemplateFitAnalysedPulse Class Reference
#include <TTemplateFitAnalysedPulse.h>
Public Member Functions
TTemplateFitAnalysedPulse ()
Needed by ROOT but not expected to be used.
TTemplateFitAnalysedPulse (const IDs::source &sourceID, const TPulseIslandID &parentID, const TPulseIsland *parentTPI)
Construct a TTemplateFitAnalysedPulse.
virtual ~TTemplateFitAnalysedPulse ()
void SetOtherPulse (TTemplateFitAnalysedPulse *pulse)
void IsPileUpPulse (bool is=true)
virtual void Draw (const TH1F *tpi_pulse) const
@brief overload the TAnalysedPulse::Draw method
virtual void Copy (TObject &rhs) const
void Reset (Option_t *o="")
Clear the TAP. This will probably not be used.
Getters
int GetFitStatus () const
double GetChi2 () const
int GetNDoF () const
double GetTimeErr () const
double GetPedestalErr () const
double GetAmplitudeErr () const
const TTemplate * GetTemplate () const
double GetResidualIntegral () const
double GetIntegralRatio () const
bool WasFirstOfDouble () const
Histogram_getters
double GetBinContent (int i) const
const TH1F * GetHisto () const
const TH1F * GetResidual () const
Setters
Set both the value and error for each field
void SetTimeOffset (const double &val)
void SetAmplitudeScaleFactor (const double &val)
void SetTime (const double &val, const double &err)
void SetAmplitude (const double &val, const double &err)
void SetPedestal (const double &val, const double &err)
void SetChi2 (const double &val)
void SetNDoF (const double &val)
void SetFitStatus (const double &val)
void SetTemplate (TTemplate *val)
void SetResidual (const TH1F *val)
void SetResidualIntegral (double val)
void SetIntegralRatio (double val)
Getters
TPulseIslandID GetParentID () const
int GetTPILength () const
double GetAmplitude () const
double GetTime () const
double GetIntegral () const
double GetEnergy () const
double GetPedestal () const
double GetTriggerTime () const
const IDs::source & GetSource () const
Setters
The TAP generators will set whatever TAP values it must through these methods. Not all need be set; the default values are obviously unphysical and several Sanity methods are provided to check if a value was set later in the analysis.
void SetParentID (const TPulseIslandID &val)
void SetTPILength (const int &val)
void SetAmplitude (const double &val)
void SetTime (const double &val)
void SetIntegral (const double &val)
void SetEnergy (const double &val)
void SetPedestal (const double &val)
void SetTriggerTime (const double &val)
void SetParentTPIProperties (const TPulseIslandID &id, const TPulseIsland *parent)
Sanity
bool IsParentIDSet () const
bool IsTPILengthSet () const
bool IsAmplitudeSet () const
bool IsTimeSet () const
bool IsIntegralSet () const
bool IsEnergySet () const
bool IsPedestalSet () const
bool IsTriggerTimeSet () const
Private Member Functions
ClassDef (TTemplateFitAnalysedPulse, 1)
Private Attributes
int fStatus
double fChi2
double fNDoF
double fIntegralRatio
double fTimeErr
double fAmplitudeErr
double fPedestalErr
TRef fTemplate
const TH1F * fResidual
const TH1F * fHisto
double fResidualTotal
bool fIsPileUpPulse
TTemplateFitAnalysedPulse * fOtherPulse
Detailed Description
Definition at line 9 of file TTemplateFitAnalysedPulse.h.
Constructor & Destructor Documentation
TTemplateFitAnalysedPulse::TTemplateFitAnalysedPulse () [inline]
Needed by ROOT but not expected to be used.
Definition at line 12 of file TTemplateFitAnalysedPulse.h.
:TAnalysedPulse(){};
TTemplateFitAnalysedPulse::TTemplateFitAnalysedPulse (const IDs::source & sourceID, const TPulseIslandID & parentID, const TPulseIsland * parentTPI)
Construct a TTemplateFitAnalysedPulse.
Same signature as for TAnalysedPulse so that MakeNewTAP can create these specialised TAPs
Definition at line 9 of file TTemplateFitAnalysedPulse.cpp.
                                                                                                :
            TAnalysedPulse(sourceID,parentID,parentTPI),
             fResidual(NULL), fHisto(NULL),fIsPileUpPulse(false),fOtherPulse(NULL){}
TTemplateFitAnalysedPulse::~TTemplateFitAnalysedPulse () [virtual]
Definition at line 14 of file TTemplateFitAnalysedPulse.cpp.
{
   //if(fHisto) delete fHisto;
}
Member Function Documentation
TTemplateFitAnalysedPulse::ClassDef (TTemplateFitAnalysedPulse , 1) [private]
virtual void TAnalysedPulse::Copy (TObject & rhs) const [inline, virtual, inherited]
Reimplemented in TTemplateConvolveAnalysedPulse.
Definition at line 40 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude, TAnalysedPulse::fEnergy, TAnalysedPulse::fIntegral, TAnalysedPulse::fParentID, TAnalysedPulse::fPedestal, TAnalysedPulse::fSource, TAnalysedPulse::fTime, TAnalysedPulse::fTPILength, and TAnalysedPulse::fTriggerTime.
{
    TObject::Copy(rhs);
    if(rhs.InheritsFrom(Class())){
      TAnalysedPulse* tap=static_cast<TAnalysedPulse*>(&rhs);
      tap->fParentID=fParentID;
      tap->fTPILength=fTPILength;
      tap->fAmplitude=fAmplitude;
      tap->fTime=fTime;
      tap->fIntegral=fIntegral;
      tap->fEnergy=fEnergy;
      tap->fPedestal=fPedestal;
      tap->fTriggerTime=fTriggerTime;
      tap->fSource=fSource;
    }
  }
void TTemplateFitAnalysedPulse::Draw (const TH1F * tpi_pulse) const [virtual]
@brief overload the TAnalysedPulse::Draw method
Reimplemented from TAnalysedPulse.
Definition at line 18 of file TTemplateFitAnalysedPulse.cpp.
References fIsPileUpPulse, fOtherPulse, TAnalysedPulse::GetAmplitude(), GetChi2(), GetFitStatus(), GetHisto(), GetNDoF(), GetTemplate(), and TAnalysedPulse::GetTime().
{
   if(tpi_pulse) {
      std::string name=tpi_pulse->GetName();
      name+="_templateAP";
      TH1F* tap_pulse=(TH1F*)GetHisto()->Clone(name.c_str());
      tap_pulse->SetDirectory(TDirectory::CurrentDirectory());
      TPaveText* text_b=new TPaveText(0.7,0.60,0.9,0.9,"NB NDC");
      text_b->AddText(Form("#chi^2 = %3.2g",GetChi2()));
      text_b->AddText(Form("Status = %d",GetFitStatus()));
      text_b->AddText(Form("Time = %g",GetTime()));
      text_b->AddText(Form("Ampl. = %g",GetAmplitude()));
      text_b->AddText(Form("NDoF = %d",GetNDoF()));
      text_b->SetFillColor(kWhite);
      text_b->SetBorderSize(1);
      tap_pulse->GetListOfFunctions()->Add(text_b);
      TH1F* tap_pulse2=NULL;
      if(fOtherPulse && !fIsPileUpPulse){
        name+="2";
        tap_pulse2=(TH1F*)fOtherPulse->GetHisto()->Clone(name.c_str());
        tap_pulse2->SetDirectory(TDirectory::CurrentDirectory());
      }
      //TMarker* marker=new TMarker(GetTime(), GetAmplitude()+GetPedestal()+10, 23);
      //marker->SetMarkerColor(kRed);
      //tap_pulse->GetListOfFunctions()->Add(marker);
      //tap_pulse->Write();
      TH1F* residual=(TH1F*) tpi_pulse->Clone(Form("%s_residual",tpi_pulse->GetName()));
      TH1F* tap_rebinned=(TH1F*) tap_pulse->Rebin(GetTemplate()->GetRefineFactor(),Form("%s_rebin",tap_pulse->GetName()));
      residual->Add(tap_rebinned, -1./GetTemplate()->GetRefineFactor());
      if(tap_pulse2) {
        delete tap_rebinned;
        tap_rebinned=(TH1F*) tap_pulse2->Rebin(GetTemplate()->GetRefineFactor(),Form("%s_rebin",tap_pulse->GetName()));
        residual->Add(tap_rebinned, -1./GetTemplate()->GetRefineFactor());
      }
      double integral=residual->Integral(5,residual->GetNbinsX()-5);
      text_b->AddText(Form("Total residue = %g",integral));
      delete tap_rebinned;
      //residual->Write();
   }
}
double TAnalysedPulse::GetAmplitude () const [inline, inherited]
Definition at line 100 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude.
Referenced by Draw(), TTemplateConvolveAnalysedPulse::Draw(), TGaussFitAnalysedPulse::Draw(), GetBinContent(), PulseViewer::GetParameterValue(), PlotTAP_selfCorrelation::PassesCutA(), TemplateFitAPGenerator::RefitWithTwo(), and SetAmplitudeScaleFactor().
{return fAmplitude;};
double TTemplateFitAnalysedPulse::GetAmplitudeErr () const [inline]
Definition at line 30 of file TTemplateFitAnalysedPulse.h.
References fAmplitudeErr.
{return fAmplitudeErr;}
double TTemplateFitAnalysedPulse::GetBinContent (int i) const
Definition at line 82 of file TTemplateFitAnalysedPulse.cpp.
References TAnalysedPulse::GetAmplitude(), TTemplate::GetHisto(), TAnalysedPulse::GetPedestal(), TTemplate::GetRefineFactor(), GetTemplate(), TTemplate::GetTime(), and TAnalysedPulse::GetTime().
Referenced by GetHisto(), and TemplateFitAPGenerator::InitializeSecondPulse().
{
      // deduce right bin to look in
      int tpl_bin=GetTime()-GetTemplate()->GetTime()/GetTemplate()->GetRefineFactor()+bin;
      // get bin sample
      double sample=GetTemplate()->GetHisto()->GetBinContent(tpl_bin);
      // Set sample in histogram that's to be saved
      return sample*GetAmplitude() + GetPedestal();
}
double TTemplateFitAnalysedPulse::GetChi2 () const [inline]
Definition at line 26 of file TTemplateFitAnalysedPulse.h.
References fChi2.
Referenced by Draw(), PulseViewer::GetParameterValue(), and TemplateFitAPGenerator::RefitWithTwo().
{return fChi2;}
double TAnalysedPulse::GetEnergy () const [inline, inherited]
Definition at line 103 of file TAnalysedPulse.h.
References TAnalysedPulse::fEnergy.
Referenced by PulseViewer::GetParameterValue(), and TME_Al50_EvdE::ProcessEntry().
{return fEnergy;};
int TTemplateFitAnalysedPulse::GetFitStatus () const [inline]
Definition at line 25 of file TTemplateFitAnalysedPulse.h.
References fStatus.
Referenced by Draw(), and PulseViewer::GetParameterValue().
{return fStatus;}
const TH1F * TTemplateFitAnalysedPulse::GetHisto () const
Definition at line 63 of file TTemplateFitAnalysedPulse.cpp.
References fHisto, GetBinContent(), TAnalysedPulse::GetParentID(), TTemplate::GetRefineFactor(), TAnalysedPulse::GetSource(), GetTemplate(), TAnalysedPulse::GetTPILength(), and EventNavigator::Instance().
Referenced by Draw().
{
      if(fHisto) return fHisto;
      std::string name=Form("Pulse_%s_%4lld_%3d_templateAP",
                                GetSource().Channel().str().c_str(),
                                EventNavigator::Instance().EntryNo(),
                                GetParentID());
      int num_samples=GetTPILength()*GetTemplate()->GetRefineFactor();
      TH1F* tap_pulse=new TH1F(name.c_str(), name.c_str(),num_samples,0,GetTPILength());
      for ( int i=0; i<num_samples; i++){
         double height=GetBinContent(i);
         tap_pulse->SetBinContent(i,height);
      }
      tap_pulse->SetDirectory(0);
      fHisto=tap_pulse;
      return fHisto;
}
double TAnalysedPulse::GetIntegral () const [inline, inherited]
Definition at line 102 of file TAnalysedPulse.h.
References TAnalysedPulse::fIntegral.
Referenced by PulseViewer::GetParameterValue(), and PlotIntegralRatios::ProcessEntry().
{return fIntegral;};
double TTemplateFitAnalysedPulse::GetIntegralRatio () const [inline]
Definition at line 33 of file TTemplateFitAnalysedPulse.h.
References fIntegralRatio.
Referenced by PulseViewer::GetParameterValue().
{return fIntegralRatio;}
int TTemplateFitAnalysedPulse::GetNDoF () const [inline]
Definition at line 27 of file TTemplateFitAnalysedPulse.h.
References fNDoF.
Referenced by Draw(), and TemplateFitAPGenerator::RefitWithTwo().
{return fNDoF;}
TPulseIslandID TAnalysedPulse::GetParentID () const [inline, inherited]
Definition at line 98 of file TAnalysedPulse.h.
References TAnalysedPulse::fParentID.
Referenced by ExportPulse::AddToExportList(), GetHisto(), and TemplateFitAPGenerator::RefitWithTwo().
{return fParentID;};
double TAnalysedPulse::GetPedestal () const [inline, inherited]
Definition at line 104 of file TAnalysedPulse.h.
References TAnalysedPulse::fPedestal.
Referenced by TTemplateConvolveAnalysedPulse::Draw(), TGaussFitAnalysedPulse::Draw(), GetBinContent(), PulseViewer::GetParameterValue(), and TemplateFitAPGenerator::RefitWithTwo().
{return fPedestal;};
double TTemplateFitAnalysedPulse::GetPedestalErr () const [inline]
Definition at line 29 of file TTemplateFitAnalysedPulse.h.
References fPedestalErr.
{return fPedestalErr;}
const TH1F* TTemplateFitAnalysedPulse::GetResidual () const [inline]
Definition at line 41 of file TTemplateFitAnalysedPulse.h.
References fResidual.
{return fResidual;}
double TTemplateFitAnalysedPulse::GetResidualIntegral () const [inline]
Definition at line 32 of file TTemplateFitAnalysedPulse.h.
References fResidualTotal.
{return fResidualTotal;}
const IDs::source& TAnalysedPulse::GetSource () const [inline, inherited]
Definition at line 106 of file TAnalysedPulse.h.
References TAnalysedPulse::fSource, and FlyWeight< ValueType, UniqueTag >::GetValue().
Referenced by ExportPulse::AddToExportList(), TTemplateConvolveAnalysedPulse::Draw(), GetHisto(), MaxTimeDiffDPGenerator::ProcessPulses(), and TDetectorPulse::TDetectorPulse().
{return fSource.GetValue();};
const TTemplate* TTemplateFitAnalysedPulse::GetTemplate () const [inline]
Definition at line 31 of file TTemplateFitAnalysedPulse.h.
References fTemplate.
Referenced by Draw(), GetBinContent(), GetHisto(), SetAmplitudeScaleFactor(), and SetTimeOffset().
{return (const TTemplate*) fTemplate.GetObject();}
double TAnalysedPulse::GetTime () const [inline, inherited]
Definition at line 101 of file TAnalysedPulse.h.
References TAnalysedPulse::fTime.
Referenced by Draw(), TTemplateConvolveAnalysedPulse::Draw(), TGaussFitAnalysedPulse::Draw(), GetBinContent(), PulseViewer::GetParameterValue(), TemplateFitAPGenerator::InitializeSecondPulse(), IsTimeOrdered(), MaxTimeDiffDPGenerator::ProcessPulses(), TemplateFitAPGenerator::RefitWithTwo(), and SetTimeOffset().
{return fTime;};
double TTemplateFitAnalysedPulse::GetTimeErr () const [inline]
Definition at line 28 of file TTemplateFitAnalysedPulse.h.
References fTimeErr.
{return fTimeErr;}
int TAnalysedPulse::GetTPILength () const [inline, inherited]
Definition at line 99 of file TAnalysedPulse.h.
References TAnalysedPulse::fTPILength.
Referenced by GetHisto(), and PulseViewer::GetParameterValue().
{return fTPILength;};
double TAnalysedPulse::GetTriggerTime () const [inline, inherited]
Definition at line 105 of file TAnalysedPulse.h.
References TAnalysedPulse::fTriggerTime.
Referenced by PulseViewer::GetParameterValue().
{return fTriggerTime;};
bool TAnalysedPulse::IsAmplitudeSet () const [inline, inherited]
Definition at line 135 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude, and TAnalysedPulse::fDefaultValue.
{return fAmplitude!=fDefaultValue;};
bool TAnalysedPulse::IsEnergySet () const [inline, inherited]
Definition at line 138 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fEnergy.
{return fEnergy!=fDefaultValue;};
bool TAnalysedPulse::IsIntegralSet () const [inline, inherited]
Definition at line 137 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fIntegral.
{return fIntegral!=fDefaultValue;};
bool TAnalysedPulse::IsParentIDSet () const [inline, inherited]
Definition at line 133 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fParentID.
{return fParentID!=fDefaultValue;};
bool TAnalysedPulse::IsPedestalSet () const [inline, inherited]
Definition at line 139 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fPedestal.
{return fPedestal!=fDefaultValue;};
void TTemplateFitAnalysedPulse::IsPileUpPulse (bool is = true) [inline]
Definition at line 62 of file TTemplateFitAnalysedPulse.h.
References fIsPileUpPulse.
Referenced by TemplateFitAPGenerator::RefitWithTwo().
{fIsPileUpPulse=is;}
bool TAnalysedPulse::IsTimeSet () const [inline, inherited]
Definition at line 136 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTime.
{return fTime!=fDefaultValue;};
bool TAnalysedPulse::IsTPILengthSet () const [inline, inherited]
Definition at line 134 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTPILength.
{return fTPILength!=fDefaultValue;};
bool TAnalysedPulse::IsTriggerTimeSet () const [inline, inherited]
Definition at line 140 of file TAnalysedPulse.h.
References TAnalysedPulse::fDefaultValue, and TAnalysedPulse::fTriggerTime.
{return fTriggerTime!=fDefaultValue;};
void TAnalysedPulse::Reset (Option_t * o = "") [inherited]
Clear the TAP. This will probably not be used.
Definition at line 42 of file TAnalysedPulse.cpp.
References TAnalysedPulse::fAmplitude, TAnalysedPulse::fDefaultValue, TAnalysedPulse::fEnergy, TAnalysedPulse::fIntegral, TAnalysedPulse::fParentID, TAnalysedPulse::fPedestal, TAnalysedPulse::fTime, TAnalysedPulse::fTPILength, and TAnalysedPulse::fTriggerTime.
{
  fParentID=fDefaultValue;
  fTPILength=fDefaultValue;
  fAmplitude=fDefaultValue;
  fTime=fDefaultValue;
  fIntegral=fDefaultValue;
  fEnergy=fDefaultValue;
  fPedestal=fDefaultValue;
  fTriggerTime=fDefaultValue;
}
void TAnalysedPulse::SetAmplitude (const double & val) [inline, inherited]
Definition at line 120 of file TAnalysedPulse.h.
References TAnalysedPulse::fAmplitude.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateConvolveAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), IntegralRatioAPGenerator::ProcessPulses(), and CFTimeMBAmpAPGenerator::ProcessPulses().
{ fAmplitude=val;};
void TTemplateFitAnalysedPulse::SetAmplitude (const double & val, const double & err) [inline]
Definition at line 50 of file TTemplateFitAnalysedPulse.h.
References fAmplitudeErr.
Referenced by TemplateFitAPGenerator::ProcessPulses(), TemplateFitAPGenerator::RefitWithTwo(), and SetAmplitudeScaleFactor().
{TAnalysedPulse::SetAmplitude(val); fAmplitudeErr=err;}
void TTemplateFitAnalysedPulse::SetAmplitudeScaleFactor (const double & val) [inline]
Definition at line 48 of file TTemplateFitAnalysedPulse.h.
References TAnalysedPulse::GetAmplitude(), GetTemplate(), and SetAmplitude().
{TAnalysedPulse::SetAmplitude(GetTemplate()->GetAmplitude()*val);}
void TTemplateFitAnalysedPulse::SetChi2 (const double & val) [inline]
Definition at line 52 of file TTemplateFitAnalysedPulse.h.
References fChi2.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{fChi2=val;}
void TAnalysedPulse::SetEnergy (const double & val) [inline, inherited]
Definition at line 123 of file TAnalysedPulse.h.
References TAnalysedPulse::fEnergy.
{ fEnergy=val;};
void TTemplateFitAnalysedPulse::SetFitStatus (const double & val) [inline]
Definition at line 54 of file TTemplateFitAnalysedPulse.h.
References fStatus.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{fStatus=val;}
void TAnalysedPulse::SetIntegral (const double & val) [inline, inherited]
Definition at line 122 of file TAnalysedPulse.h.
References TAnalysedPulse::fIntegral.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateFitAPGenerator::ProcessPulses(), TemplateConvolveAPGenerator::ProcessPulses(), SimpIntAPGenerator::ProcessPulses(), and IntegralRatioAPGenerator::ProcessPulses().
{ fIntegral=val;};
void TTemplateFitAnalysedPulse::SetIntegralRatio (double val) [inline]
Definition at line 58 of file TTemplateFitAnalysedPulse.h.
References fIntegralRatio.
Referenced by TemplateFitAPGenerator::ProcessPulses().
{fIntegralRatio=val;}
void TTemplateFitAnalysedPulse::SetNDoF (const double & val) [inline]
Definition at line 53 of file TTemplateFitAnalysedPulse.h.
References fNDoF.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{fNDoF=val;}
void TTemplateFitAnalysedPulse::SetOtherPulse (TTemplateFitAnalysedPulse * pulse) [inline]
Definition at line 61 of file TTemplateFitAnalysedPulse.h.
References fOtherPulse.
Referenced by TemplateFitAPGenerator::RefitWithTwo().
{fOtherPulse=pulse;}
void TAnalysedPulse::SetParentID (const TPulseIslandID & val) [inline, inherited]
Definition at line 118 of file TAnalysedPulse.h.
References TAnalysedPulse::fParentID.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fParentID=val;};
void TAnalysedPulse::SetParentTPIProperties (const TPulseIslandID & id, const TPulseIsland * parent) [inherited]
Definition at line 65 of file TAnalysedPulse.cpp.
References TPulseIsland::GetClockTickInNs(), TPulseIsland::GetPulseLength(), TPulseIsland::GetTimeStamp(), TAnalysedPulse::SetParentID(), TAnalysedPulse::SetTPILength(), and TAnalysedPulse::SetTriggerTime().
Referenced by TAnalysedPulse::TAnalysedPulse().
{
  SetParentID(id);
  if(!pulse) {
    std::cerr<<"NULL pointer to TPulseIsland passed as parent for TAnalysedPulse."<<std::endl;
    return;
  }
  SetTPILength(pulse->GetPulseLength());
  SetTriggerTime(pulse->GetTimeStamp()*pulse->GetClockTickInNs());
}
void TAnalysedPulse::SetPedestal (const double & val) [inline, inherited]
Definition at line 124 of file TAnalysedPulse.h.
References TAnalysedPulse::fPedestal.
Referenced by TemplateConvolveAPGenerator::ProcessPulses().
{ fPedestal=val;};
void TTemplateFitAnalysedPulse::SetPedestal (const double & val, const double & err) [inline]
Definition at line 51 of file TTemplateFitAnalysedPulse.h.
References fPedestalErr.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{TAnalysedPulse::SetPedestal(val); fPedestalErr=err;}
void TTemplateFitAnalysedPulse::SetResidual (const TH1F * val) [inline]
Definition at line 56 of file TTemplateFitAnalysedPulse.h.
References fResidual.
{fResidual=val;}
void TTemplateFitAnalysedPulse::SetResidualIntegral (double val) [inline]
Definition at line 57 of file TTemplateFitAnalysedPulse.h.
References fResidualTotal.
{fResidualTotal=val;}
void TTemplateFitAnalysedPulse::SetTemplate (TTemplate * val) [inline]
Definition at line 55 of file TTemplateFitAnalysedPulse.h.
References fTemplate.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and TemplateFitAPGenerator::RefitWithTwo().
{fTemplate=val;}
void TAnalysedPulse::SetTime (const double & val) [inline, inherited]
Definition at line 121 of file TAnalysedPulse.h.
References TAnalysedPulse::fTime.
Referenced by FirstCompleteAPGenerator::AnalyseOneTpi(), TemplateConvolveAPGenerator::ProcessPulses(), MaxBinAPGenerator::ProcessPulses(), IntegralRatioAPGenerator::ProcessPulses(), CFTimeMBAmpAPGenerator::ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{ fTime=val;};
void TTemplateFitAnalysedPulse::SetTime (const double & val, const double & err) [inline]
Definition at line 49 of file TTemplateFitAnalysedPulse.h.
References fTimeErr.
Referenced by TemplateFitAPGenerator::ProcessPulses(), TemplateFitAPGenerator::RefitWithTwo(), and SetTimeOffset().
{TAnalysedPulse::SetTime(val); fTimeErr=err;}
void TTemplateFitAnalysedPulse::SetTimeOffset (const double & val) [inline]
Definition at line 47 of file TTemplateFitAnalysedPulse.h.
References GetTemplate(), TAnalysedPulse::GetTime(), and SetTime().
{TAnalysedPulse::SetTime(GetTemplate()->GetTime()/GetTemplate()->GetRefineFactor()+val);}
void TAnalysedPulse::SetTPILength (const int & val) [inline, inherited]
Definition at line 119 of file TAnalysedPulse.h.
References TAnalysedPulse::fTPILength.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fTPILength=val;};
void TAnalysedPulse::SetTriggerTime (const double & val) [inline, inherited]
Definition at line 125 of file TAnalysedPulse.h.
References TAnalysedPulse::fTriggerTime.
Referenced by TAnalysedPulse::SetParentTPIProperties().
{ fTriggerTime=val;};
bool TTemplateFitAnalysedPulse::WasFirstOfDouble () const [inline]
Definition at line 34 of file TTemplateFitAnalysedPulse.h.
References fIsPileUpPulse, and fOtherPulse.
Referenced by PulseViewer::GetParameterValue().
{return fOtherPulse && !fIsPileUpPulse;}
Member Data Documentation
double TTemplateFitAnalysedPulse::fAmplitudeErr [private]
Definition at line 75 of file TTemplateFitAnalysedPulse.h.
Referenced by GetAmplitudeErr(), and SetAmplitude().
double TTemplateFitAnalysedPulse::fChi2 [private]
Definition at line 73 of file TTemplateFitAnalysedPulse.h.
Referenced by GetChi2(), and SetChi2().
const TH1F* TTemplateFitAnalysedPulse::fHisto [mutable, private]
Definition at line 78 of file TTemplateFitAnalysedPulse.h.
Referenced by GetHisto().
double TTemplateFitAnalysedPulse::fIntegralRatio [private]
Definition at line 74 of file TTemplateFitAnalysedPulse.h.
Referenced by GetIntegralRatio(), and SetIntegralRatio().
bool TTemplateFitAnalysedPulse::fIsPileUpPulse [private]
Definition at line 81 of file TTemplateFitAnalysedPulse.h.
Referenced by Draw(), IsPileUpPulse(), and WasFirstOfDouble().
double TTemplateFitAnalysedPulse::fNDoF [private]
Definition at line 73 of file TTemplateFitAnalysedPulse.h.
Referenced by GetNDoF(), and SetNDoF().
TTemplateFitAnalysedPulse* TTemplateFitAnalysedPulse::fOtherPulse [private]
Definition at line 82 of file TTemplateFitAnalysedPulse.h.
Referenced by Draw(), SetOtherPulse(), and WasFirstOfDouble().
double TTemplateFitAnalysedPulse::fPedestalErr [private]
Definition at line 75 of file TTemplateFitAnalysedPulse.h.
Referenced by GetPedestalErr(), and SetPedestal().
const TH1F* TTemplateFitAnalysedPulse::fResidual [private]
Definition at line 77 of file TTemplateFitAnalysedPulse.h.
Referenced by GetResidual(), and SetResidual().
double TTemplateFitAnalysedPulse::fResidualTotal [private]
Definition at line 79 of file TTemplateFitAnalysedPulse.h.
Referenced by GetResidualIntegral(), and SetResidualIntegral().
int TTemplateFitAnalysedPulse::fStatus [private]
Definition at line 72 of file TTemplateFitAnalysedPulse.h.
Referenced by GetFitStatus(), and SetFitStatus().
TRef TTemplateFitAnalysedPulse::fTemplate [private]
Definition at line 76 of file TTemplateFitAnalysedPulse.h.
Referenced by GetTemplate(), and SetTemplate().
double TTemplateFitAnalysedPulse::fTimeErr [private]
Definition at line 75 of file TTemplateFitAnalysedPulse.h.
Referenced by GetTimeErr(), and SetTime().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/TTemplateFitAnalysedPulse.h
rootana/src/TAP_generators/TTemplateFitAnalysedPulse.cpp