AlcapDAQ: PulseViewer Class Reference
PulseViewer Class Reference
Module to plot pulses meeting a certain criteria.
#include <PulseViewer.h>
Public Member Functions
PulseViewer (modules::options *opts)
~PulseViewer ()
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
enum ParameterType {
kAmplitude, kTime, kIntegral, kTPILength,
kEnergy, kPedestal, kTriggerTime, kEventNo,
kIntegralRatio, kIntegralTail, kChi2, kStatus,
kWasDouble, kNPeaks, kPeakRank
}
enum PulseType { kTAP, kIntegralRatioAP, kTemplateFitAP, kTemplateConvolveAP }
typedef int TPulseIslandID
typedef int TAnalysedPulseID
typedef int EventID_t
typedef std::map
< TPulseIslandID, int > PulseIDList_t
typedef std::map< EventID_t,
PulseIDList_t > EventPulseIDList_t
typedef std::map< std::string,
ParameterType > ParameterKeys
typedef std::map< std::string,
PulseType > PulseKeys
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
The big kahuna. Overload this in the derived class and it will be called for each event.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
IDs::source GetSource () const
Get the channel as a string.
int ConsiderDrawing (const TAnalysedPulseID &id, const TAnalysedPulse *i_pulse)
double GetParameterValue (const TAnalysedPulse *pulse, const ParameterType &parameter)
Get the value of interest from pulse.
double GetParameterValue (const TIntegralRatioAnalysedPulse *pulse, const ParameterType &parameter)
double GetParameterValue (const TTemplateFitAnalysedPulse *pulse, const ParameterType &parameter)
double GetParameterValue (const TTemplateConvolveAnalysedPulse *pulse, const ParameterType &parameter)
int ParseTriggerString (const std::string &trigger_condition)
int CheckPulseType (const std::string &pulse_type)
bool TestPulseType (const TAnalysedPulse *pulse_type)
bool SummarisePlots ()
Dump a summary of what was done.
Private Attributes
IDs::source fSource
std::string fRequestedSource
std::string fTriggerCondition
PulseType fPulseType
std::string fRequestedPulseType
long int fTotalPlotted
long int fMaxToPlot
long int fMaxToPlotPerEvent
bool fSummarize
bool fStopAtMax
EventPulseIDList_t fPulsesPlotted
TFormula * fFormula
int fEvent
Static Private Attributes
static ParameterKeys fAvailableParams
static PulseKeys fAvailablePulseTypes
Detailed Description
Module to plot pulses meeting a certain criteria.
See also:
https://github.com/alcap-org/AlcapDAQ/wiki/rootana-module-PulseViewer
Definition at line 16 of file PulseViewer.h.
Member Typedef Documentation
typedef int PulseViewer::EventID_t [private]
Definition at line 19 of file PulseViewer.h.
typedef std::map<EventID_t,PulseIDList_t> PulseViewer::EventPulseIDList_t [private]
Definition at line 21 of file PulseViewer.h.
typedef std::map<std::string,ParameterType> PulseViewer::ParameterKeys [private]
Definition at line 92 of file PulseViewer.h.
typedef std::map<TPulseIslandID,int> PulseViewer::PulseIDList_t [private]
Definition at line 20 of file PulseViewer.h.
typedef std::map<std::string,PulseType> PulseViewer::PulseKeys [private]
Definition at line 95 of file PulseViewer.h.
typedef int PulseViewer::TAnalysedPulseID [private]
Definition at line 18 of file PulseViewer.h.
typedef int PulseViewer::TPulseIslandID [private]
Definition at line 17 of file PulseViewer.h.
Member Enumeration Documentation
enum PulseViewer::ParameterType [private]
Enumerator:
kAmplitude
kTime
kIntegral
kTPILength
kEnergy
kPedestal
kTriggerTime
kEventNo
kIntegralRatio
kIntegralTail
kChi2
kStatus
kWasDouble
kNPeaks
kPeakRank
Definition at line 23 of file PulseViewer.h.
{
        kAmplitude,
        kTime,
        kIntegral,
        kTPILength,
        kEnergy,
        kPedestal,
        kTriggerTime,
        kEventNo,
        kIntegralRatio,
        kIntegralTail,
        kChi2,
        kStatus,
        kWasDouble,
        kNPeaks,
        kPeakRank
    };
enum PulseViewer::PulseType [private]
Enumerator:
kTAP
kIntegralRatioAP
kTemplateFitAP
kTemplateConvolveAP
Definition at line 41 of file PulseViewer.h.
                  {
        kTAP,
        kIntegralRatioAP,
        kTemplateFitAP,
        kTemplateConvolveAP
    };
Constructor & Destructor Documentation
PulseViewer::PulseViewer (modules::options * opts)
Definition at line 37 of file PulseViewer.cpp.
References IDs::source::Channel(), fMaxToPlot, fMaxToPlotPerEvent, fRequestedPulseType, fRequestedSource, fSource, fStopAtMax, fSummarize, fTriggerCondition, modules::options::GetBool(), modules::options::GetFlag(), modules::options::GetInt(), and modules::options::GetString().
                                            :
    BaseModule("PulseViewer",opts),fTotalPlotted(0),fFormula(NULL),fEvent(0){
        fRequestedSource=opts->GetString("source");
        fRequestedPulseType=opts->GetString("pulse_type","TAnalysedPulse");
        fSource.Channel()=fRequestedSource;
        fTriggerCondition=opts->GetString("trigger");
        fSummarize=opts->GetFlag("summarize");
        fMaxToPlot=opts->GetInt("max_plots",-1);
        fMaxToPlotPerEvent=opts->GetInt("max_plots_event",-1);
        fStopAtMax=opts->GetBool("stop_at_max_plots",true);
    }
PulseViewer::~PulseViewer ()
Definition at line 49 of file PulseViewer.cpp.
References fFormula.
{
    if(fFormula) delete fFormula;
}
Member Function Documentation
int PulseViewer::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Optional method which is called once after the main event loop Can be used to dump a summary or finalise a histogram
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 290 of file PulseViewer.cpp.
References fPulsesPlotted, fSource, fTotalPlotted, fTriggerCondition, and SummarisePlots().
{
  // Print extra info if we're requested to summarize the found pulses
  if(SummarisePlots()){
      const std::string prefix="     ";
      cout<<"Summary for pulse criteria: ("<<fTriggerCondition <<") on channel "<<fSource<<endl;
      if(!fPulsesPlotted.empty()){
          cout<<prefix<<" Event | Pulse IDs drawn (sub_pulse ID)"<<endl;
          cout<<prefix<<" ----- | ------------ "<<endl;
          for(EventPulseIDList_t::const_iterator i_event=fPulsesPlotted.begin();
                  i_event!=fPulsesPlotted.end();i_event++){
              cout<<prefix<<std::setw(6)<< i_event->first<<" | ";
              for(PulseIDList_t::const_iterator i_pulse=i_event->second.begin();
                      i_pulse!=i_event->second.end();i_pulse++){
                  cout<<std::setw(2)<< i_pulse->first <<"("<< i_pulse->second<<")" <<", ";
              }
              cout<<endl;
          }
          cout<<prefix<<" ----- | ------------ "<<endl;
      }
      cout<<prefix<<"Total pulses plotted = "<<fTotalPlotted<<endl;
      cout<<"Summary for pulse criteria: ("<<fTriggerCondition <<") on channel "<<fSource<<endl;
  }
  return 0;
}
int PulseViewer::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
Optional method which is called once before the main event loop Can be used to parse options and setup histograms.
Returns:
0 on sucess and non-zero if a problem occurred
Implements BaseModule.
Definition at line 53 of file PulseViewer.cpp.
References IDs::source::Channel(), CheckPulseType(), fAvailableParams, fAvailablePulseTypes, fRequestedPulseType, fRequestedSource, fSource, fTriggerCondition, ExportPulse::Instance(), kAmplitude, kEnergy, kEventNo, kIntegral, kIntegralRatioAP, kPedestal, kTAP, kTemplateConvolveAP, kTemplateFitAP, kTime, kTPILength, kTriggerTime, and ParseTriggerString().
{
   // Check we're also running with the ExportPulse module
   if(!ExportPulse::Instance()){
           cout<<"PulseViewer: Error: You need to run with ExportPulse to use PulseViewer module"<<std::endl;
           return 1;
   }
   // Check the channel is valid
   if(!fSource.Channel().isValid()){
           cout<<"PulseViewer: Error: No detector called '"<<fRequestedSource<<"' exists"<<endl;
           return 2;
   }
   // setup the possible parameters
   if(fAvailableParams.empty()){
     fAvailableParams["amplitude"]=kAmplitude;
     fAvailableParams["time"]=kTime;
     fAvailableParams["TPI_length"]=kTPILength;
     fAvailableParams["integral"]=kIntegral;
     fAvailableParams["energy"]=kEnergy;
     fAvailableParams["pedestal"]=kPedestal;
     fAvailableParams["trigger_time"]=kTriggerTime;
     fAvailableParams["event_no"]=kEventNo;
   }
   if(fAvailablePulseTypes.empty()){
     fAvailablePulseTypes["TAnalysedPulse"]=kTAP;
     fAvailablePulseTypes["IntegralRatioAP"]=kIntegralRatioAP;
     fAvailablePulseTypes["TemplateFitAP"]=kTemplateFitAP;
     fAvailablePulseTypes["TemplateConvolveAP"]=kTemplateConvolveAP;
   }
   int ret_val= CheckPulseType(fRequestedPulseType);
   if(ret_val) return ret_val;
   // Parse the trigger string
   return ParseTriggerString(fTriggerCondition);
}
int PulseViewer::CheckPulseType (const std::string & pulse_type) [private]
Definition at line 93 of file PulseViewer.cpp.
References fAvailableParams, fAvailablePulseTypes, fPulseType, kChi2, kIntegralRatio, kIntegralRatioAP, kIntegralTail, kNPeaks, kPeakRank, kStatus, kTAP, kTemplateConvolveAP, kTemplateFitAP, and kWasDouble.
Referenced by BeforeFirstEntry().
{
   PulseKeys::const_iterator i_type=fAvailablePulseTypes.find(pulse_type);
   if(i_type==fAvailablePulseTypes.end()) {
      cout<<"PulseViewer::CheckPulseType: Error: Bad pulse_type: "<<pulse_type<<endl;
     for(PulseKeys::const_iterator it=fAvailablePulseTypes.begin();
             it!=fAvailablePulseTypes.end(); it++){
         cout<<"    |-"<<it->first<<endl;
     }
     return 1;
   }
   fPulseType=i_type->second;
   switch(fPulseType){
      case kTAP: break;
      case kTemplateConvolveAP:
         fAvailableParams["NPeaks"]=kNPeaks;
         fAvailableParams["PeakRank"]=kPeakRank;
         fAvailableParams["Integral_ratio"]=kIntegralRatio;
         break;
      case kTemplateFitAP:
         fAvailableParams["Chi2"]=kChi2;
         fAvailableParams["Status"]=kStatus;
         fAvailableParams["Integral_ratio"]=kIntegralRatio;
         fAvailableParams["Double_fitted"]=kWasDouble;
         break;
      case kIntegralRatioAP:
         fAvailableParams["Integral_ratio"]=kIntegralRatio;
         fAvailableParams["Integral_tail"]=kIntegralTail;
      break;
   }
   return 0;
}
int PulseViewer::ConsiderDrawing (const TAnalysedPulseID & id, const TAnalysedPulse * i_pulse) [private]
Ask ExportPulse to draw this pulse if it matches the trigger criteria
Returns:
0 on success, non-zero otherwise
Definition at line 253 of file PulseViewer.cpp.
References ExportPulse::AddToExportList(), BaseModule::Debug(), EventNavigator::EntryNo(), fAvailableParams, fFormula, fPulsesPlotted, fPulseType, fTotalPlotted, fTriggerCondition, GetVals, ExportPulse::Instance(), EventNavigator::Instance(), kIntegralRatioAP, kTAP, kTemplateConvolveAP, and kTemplateFitAP.
Referenced by ProcessEntry().
{
  // Check pulse passes trigger condition
    double vals[fAvailableParams.size()];
    switch (fPulseType){
       case kTAP: GetVals(vals,pulse); break;
       case kTemplateConvolveAP: if(true){
            const TTemplateConvolveAnalysedPulse* tc_pulse =static_cast<const TTemplateConvolveAnalysedPulse*>(pulse);
            GetVals(vals,tc_pulse);
            } break;
       case kTemplateFitAP: if(true){
            const TTemplateFitAnalysedPulse* tf_pulse =static_cast<const TTemplateFitAnalysedPulse*>(pulse);
            GetVals(vals,tf_pulse);
            } break;
       case kIntegralRatioAP: if(true){
            const TIntegralRatioAnalysedPulse* ir_pulse =static_cast<const TIntegralRatioAnalysedPulse*>(pulse);
            GetVals(vals,ir_pulse);
            } break;
    }
    fFormula->SetParameters(vals);
    double value=fFormula->Eval(0);
  if(!value) return 0;
  if(Debug()){
    cout<<"PulseViewer: Event: "<<EventNavigator::Instance().EntryNo()
        <<" Plotting pulse "<<id<<" [ "<<fTriggerCondition<<" => "<<fFormula->GetExpFormula("P")<<" ]"<<endl;
  }
  // If it does, ask ExportPulse to draw it
  // We're safe to assume Instance will return becuase we test it's
  // existence in BeforeFirstEntry
  if(fPulsesPlotted[EventNavigator::Instance().EntryNo()].count(id)==0){
      ExportPulse::Instance()->AddToExportList(pulse);
      fTotalPlotted++;
  }
  fPulsesPlotted[EventNavigator::Instance().EntryNo()][id]++;
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), IslandAmplitude::AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), IslandAmplitude::BeforeFirstEntry(), ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Energy::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
double PulseViewer::GetParameterValue (const TTemplateConvolveAnalysedPulse * pulse, const ParameterType & parameter) [private]
Definition at line 242 of file PulseViewer.cpp.
References TTemplateConvolveAnalysedPulse::GetIntegralRatio(), TTemplateConvolveAnalysedPulse::GetNPeaks(), GetParameterValue(), TTemplateConvolveAnalysedPulse::GetPeakRank(), kIntegralRatio, kNPeaks, and kPeakRank.
{
   double retVal=0;
   switch (parameter){
       case kIntegralRatio: retVal=pulse->GetIntegralRatio(); break;
       case kNPeaks: retVal=pulse->GetNPeaks(); break;
       case kPeakRank: retVal=pulse->GetPeakRank(); break;
       default: retVal=GetParameterValue( static_cast<const TAnalysedPulse*>(pulse),parameter);
    }
    return retVal;
}
double PulseViewer::GetParameterValue (const TTemplateFitAnalysedPulse * pulse, const ParameterType & parameter) [private]
Definition at line 230 of file PulseViewer.cpp.
References TTemplateFitAnalysedPulse::GetChi2(), TTemplateFitAnalysedPulse::GetFitStatus(), TTemplateFitAnalysedPulse::GetIntegralRatio(), GetParameterValue(), kChi2, kIntegralRatio, kStatus, kWasDouble, and TTemplateFitAnalysedPulse::WasFirstOfDouble().
{
   double retVal=0;
   switch (parameter){
       case kIntegralRatio: retVal=pulse->GetIntegralRatio(); break;
       case kChi2: retVal=pulse->GetChi2(); break;
       case kStatus: retVal=pulse->GetFitStatus(); break;
       case kWasDouble: retVal=pulse->WasFirstOfDouble(); break;
       default: retVal=GetParameterValue( static_cast<const TAnalysedPulse*>(pulse),parameter);
    }
    return retVal;
}
double PulseViewer::GetParameterValue (const TIntegralRatioAnalysedPulse * pulse, const ParameterType & parameter) [private]
Definition at line 220 of file PulseViewer.cpp.
References TIntegralRatioAnalysedPulse::GetIntegralRatio(), TIntegralRatioAnalysedPulse::GetIntegralSmall(), GetParameterValue(), kIntegralRatio, and kIntegralTail.
{
   double retVal=0;
   switch (parameter){
       case kIntegralTail: retVal=pulse->GetIntegralSmall(); break;
       case kIntegralRatio: retVal=pulse->GetIntegralRatio(); break;
       default: retVal=GetParameterValue( static_cast<const TAnalysedPulse*>(pulse),parameter);
    }
    return retVal;
}
double PulseViewer::GetParameterValue (const TAnalysedPulse * pulse, const ParameterType & parameter) [private]
Get the value of interest from pulse.
Definition at line 203 of file PulseViewer.cpp.
References definitions::DefaultValue, fEvent, TAnalysedPulse::GetAmplitude(), TAnalysedPulse::GetEnergy(), TAnalysedPulse::GetIntegral(), TAnalysedPulse::GetPedestal(), TAnalysedPulse::GetTime(), TAnalysedPulse::GetTPILength(), TAnalysedPulse::GetTriggerTime(), kAmplitude, kEnergy, kEventNo, kIntegral, kPedestal, kTime, kTPILength, and kTriggerTime.
Referenced by GetParameterValue().
{
   double retVal=0;
   switch (parameter){
       case kAmplitude: retVal=pulse->GetAmplitude(); break;
       case kTime: retVal=pulse->GetTime(); break;
       case kIntegral: retVal=pulse->GetIntegral(); break;
       case kTPILength: retVal=pulse->GetTPILength(); break;
       case kEnergy: retVal=pulse->GetEnergy(); break;
       case kPedestal: retVal=pulse->GetPedestal(); break;
       case kTriggerTime: retVal=pulse->GetTriggerTime(); break;
       case kEventNo: retVal=fEvent; break;
       default: retVal=definitions::DefaultValue;
           cout<<"PulseViewer::GetParameterValue: Error: Cannot get param: "<<parameter<<" from a TAnalysedPulse"<<endl;
    }
    return retVal;
}
IDs::source PulseViewer::GetSource () const [inline, private]
Get the channel as a string.
Definition at line 58 of file PulseViewer.h.
References fSource.
Referenced by ProcessEntry().
{return fSource;};
int PulseViewer::ParseTriggerString (const std::string & trigger_condition) [private]
Parse a trigger condition and set up the values needed to handle it
Returns:
0 on success, non-zero otherwise
Definition at line 125 of file PulseViewer.cpp.
References fAvailableParams, fFormula, fTriggerCondition, and modules::parser::ReplaceWords().
Referenced by BeforeFirstEntry().
{
    std::string expression =fTriggerCondition;
    for(ParameterKeys::const_iterator i_key=fAvailableParams.begin();
            i_key!=fAvailableParams.end();i_key++){
        modules::parser::ReplaceWords(expression,i_key->first,Form("[%d]",i_key->second));
    }
    fFormula=new TFormula("PulseViewerTrigger",expression.c_str());
    int ret= fFormula->Compile();
    if(ret){
        cout<<"Error: Bad trigger expression: '"<<fTriggerCondition<<"'"<<endl;
        cout<<"   Only use parameters from"<<endl;
        for(ParameterKeys::const_iterator it=fAvailableParams.begin();
                it!=fAvailableParams.end();
                it++){
            cout<<"    |-"<<it->first<<endl;
        }
    }
    return ret;
}
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int PulseViewer::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
The big kahuna. Overload this in the derived class and it will be called for each event.
Parameters:
gData Pointer to current map of all TPIs [ WILL CHANGE SHORTLY ]
gSetup Pointer to TSetupData for this run [ WILL CHANGE SHORTLY ]
Returns:
0 on success and non-zero on failure
Implements BaseModule.
Definition at line 146 of file PulseViewer.cpp.
References ConsiderDrawing(), BaseModule::Debug(), fEvent, fMaxToPlot, fStopAtMax, fTotalPlotted, gAnalysedPulseMap, GetSource(), and TestPulseType().
{
    // Have we drawn the number of pulses we were meant to?
    if(fMaxToPlot>0 && fTotalPlotted>=fMaxToPlot){
        if(fStopAtMax){
            cout<<"PulseViewer::ProcessEntry: "<<fTotalPlotted<<" pulses have already been drawn which "
                <<"is greater than the limit of "<<fMaxToPlot<<" so I'm stopping execution.\n";
            //cout<<"You can probably ignore any of the immediate errors that follow this."<<endl;
            return 1;
        }
        return 0;
    }
    // Get the TAPs for this channel
    AnalysedPulseList* allTAPs=NULL;
    for(SourceAnalPulseMap::iterator i_source=gAnalysedPulseMap.begin();
            i_source!=gAnalysedPulseMap.end(); ++i_source){
        if(i_source->first.matches(GetSource())){
            allTAPs=&i_source->second;
            break;
        }
    }
    if(!allTAPs){
       cout<<"Problem getting TAP list for "<<GetSource()<<endl;
            return 1;
    }else if(allTAPs->empty() ){
       if(Debug()) cout<<"List of TAPS for '"<< GetSource()<<"' was empty "<<endl;
       return 0;
    }
    // Check each TAP against trigger
    int retVal=0;
    for(AnalysedPulseList::iterator i_pulse=allTAPs->begin();
                i_pulse!=allTAPs->end() && retVal==0;
                i_pulse++){
            if(fEvent==0){
                retVal=TestPulseType(*i_pulse);
            }
            retVal=ConsiderDrawing((*i_pulse)->GetParentID() ,*i_pulse);
    }
    if(retVal!=0) return retVal;
    fEvent++;
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
bool PulseViewer::SummarisePlots () [inline, private]
Dump a summary of what was done.
Definition at line 77 of file PulseViewer.h.
References fSummarize.
Referenced by AfterLastEntry().
{return fSummarize;};
bool PulseViewer::TestPulseType (const TAnalysedPulse * pulse_type) [private]
Definition at line 193 of file PulseViewer.cpp.
References fPulseType, kIntegralRatioAP, kTAP, kTemplateConvolveAP, and kTemplateFitAP.
Referenced by ProcessEntry().
{
  switch(fPulseType){
    case kTAP: return false;
    case kIntegralRatioAP: return dynamic_cast<const TIntegralRatioAnalysedPulse*>(pulse);
    case kTemplateFitAP: return dynamic_cast<const TTemplateFitAnalysedPulse*>(pulse);
    case kTemplateConvolveAP: return dynamic_cast<const TTemplateConvolveAnalysedPulse*>(pulse);
  }
  return false;
}
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
PulseViewer::ParameterKeys PulseViewer::fAvailableParams [static, private]
Definition at line 93 of file PulseViewer.h.
Referenced by BeforeFirstEntry(), CheckPulseType(), ConsiderDrawing(), and ParseTriggerString().
PulseViewer::PulseKeys PulseViewer::fAvailablePulseTypes [static, private]
Definition at line 96 of file PulseViewer.h.
Referenced by BeforeFirstEntry(), and CheckPulseType().
int PulseViewer::fEvent [private]
Definition at line 90 of file PulseViewer.h.
Referenced by GetParameterValue(), and ProcessEntry().
TFormula* PulseViewer::fFormula [private]
Definition at line 89 of file PulseViewer.h.
Referenced by ConsiderDrawing(), ParseTriggerString(), and ~PulseViewer().
long int PulseViewer::fMaxToPlot [private]
Definition at line 86 of file PulseViewer.h.
Referenced by ProcessEntry(), and PulseViewer().
long int PulseViewer::fMaxToPlotPerEvent [private]
Definition at line 86 of file PulseViewer.h.
Referenced by PulseViewer().
EventPulseIDList_t PulseViewer::fPulsesPlotted [private]
Definition at line 88 of file PulseViewer.h.
Referenced by AfterLastEntry(), and ConsiderDrawing().
PulseType PulseViewer::fPulseType [private]
Definition at line 83 of file PulseViewer.h.
Referenced by CheckPulseType(), ConsiderDrawing(), and TestPulseType().
std::string PulseViewer::fRequestedPulseType [private]
Definition at line 84 of file PulseViewer.h.
Referenced by BeforeFirstEntry(), and PulseViewer().
std::string PulseViewer::fRequestedSource [private]
Definition at line 81 of file PulseViewer.h.
Referenced by BeforeFirstEntry(), and PulseViewer().
IDs::source PulseViewer::fSource [private]
Definition at line 77 of file PulseViewer.h.
Referenced by AfterLastEntry(), BeforeFirstEntry(), GetSource(), and PulseViewer().
bool PulseViewer::fStopAtMax [private]
Definition at line 87 of file PulseViewer.h.
Referenced by ProcessEntry(), and PulseViewer().
bool PulseViewer::fSummarize [private]
Definition at line 87 of file PulseViewer.h.
Referenced by PulseViewer(), and SummarisePlots().
long int PulseViewer::fTotalPlotted [private]
Definition at line 85 of file PulseViewer.h.
Referenced by AfterLastEntry(), ConsiderDrawing(), and ProcessEntry().
std::string PulseViewer::fTriggerCondition [private]
Definition at line 82 of file PulseViewer.h.
Referenced by AfterLastEntry(), BeforeFirstEntry(), ConsiderDrawing(), ParseTriggerString(), and PulseViewer().
The documentation for this class was generated from the following files:
rootana/src/plotters/PulseViewer.h
rootana/src/plotters/PulseViewer.cpp