AlcapDAQ: modules::reader Class Reference
modules::reader Class Reference
#include <ModulesReader.h>
Classes
struct Option_t
Public Member Functions
reader ()
virtual ~reader ()
int ReadFile (const char *name)
void PrintAllOptions () const
int HowMany (const std::string &name) const
bool DumpInputFile () const
size_t GetNumModules () const
std::string GetModule (unsigned int i) const
modules::options * GetOptions (unsigned int i) const
void SetDebug ()
void SetDebugAll ()
Private Types
enum OptionMode_t { kSet, kAppend }
typedef std::vector< std::string > OptionsList
typedef std::map< std::string,
modules::options * > SectionsList
typedef std::vector< std::pair
< std::string,
modules::options * > > ModuleList
typedef std::map< std::string,
int > ModuleCounts
Private Member Functions
int OpenFile (const char *name, std::ifstream &infile)
bool AddSection (const std::string &name, const std::string &type="")
int AddModule (std::string line)
void ProcessGlobalOption (Option_t opt)
void AddOption (const std::string &module, const Option_t &opt)
void AddOption (const std::string &module, const std::string &flag)
void AddOption (modules::options *module, const Option_t &opt)
void AddOption (modules::options *module, const std::string &flag)
void AddOptionAll (const std::string &key, const std::string &value="")
void AddOptionAll (const Option_t &opt)
Option_t SplitOption (const std::string &line)
int MakeModules (const SectionsList &)
bool isComment (std::stringstream &line)
std::string findSectionName (const std::string &line)
std::ostream & PrintProblem ()
Private Attributes
SectionsList fAllOptions
ModuleList fModules
ModuleCounts fModulesCounts
int fLineNumber
bool fShouldPrint
bool fDebugAll
bool fDumpContents
bool fDumpInputFile
Static Private Attributes
static const char * fGlobalModule = "global"
Detailed Description
Definition at line 15 of file ModulesReader.h.
Member Typedef Documentation
typedef std::map<std::string,int > modules::reader::ModuleCounts [private]
Definition at line 21 of file ModulesReader.h.
typedef std::vector<std::pair<std::string, modules::options*> > modules::reader::ModuleList [private]
Definition at line 20 of file ModulesReader.h.
typedef std::vector<std::string> modules::reader::OptionsList [private]
Definition at line 18 of file ModulesReader.h.
typedef std::map<std::string,modules::options* > modules::reader::SectionsList [private]
Definition at line 19 of file ModulesReader.h.
Member Enumeration Documentation
enum modules::reader::OptionMode_t [private]
Enumerator:
kSet
kAppend
Definition at line 22 of file ModulesReader.h.
{ kSet , kAppend };
Constructor & Destructor Documentation
modules::reader::reader () [inline]
Definition at line 31 of file ModulesReader.h.
:fShouldPrint(false),fDebugAll(false),fDumpContents(false),fDumpInputFile(false){};
virtual modules::reader::~reader () [inline, virtual]
Definition at line 34 of file ModulesReader.h.
{};
Member Function Documentation
int modules::reader::AddModule (std::string line) [private]
Definition at line 104 of file ModulesReader.cpp.
References modules::options::AddArgument(), AddOption(), AddSection(), modules::parser::Constructor_t::before, fAllOptions, fDebugAll, fModules, fModulesCounts, fShouldPrint, modules::parser::Constructor_t::inside, modules::parser::ParseConstructor(), PrintProblem(), modules::options::SetAlias(), modules::parser::TokeniseByDelimiter(), and modules::parser::TrimWhiteSpaceBeforeAfter().
Referenced by ReadFile().
{
    std::string alias, type;
    // How is this module specified ?
    // If  the line contains an equals sign, assume we have a alias and a type
    // (and possibly arguments), if not, assume it's just a type (and possibly
    // arguments)
    Constructor_t constructor=ParseConstructor(line,'(',')');
    std::vector<std::string> name_alias;
    TokeniseByDelimiter(constructor.before, name_alias,"=");
    if(name_alias.size()>2) {
            PrintProblem()<<"Multiple equals signs (=) in line gives an ambiguous alias / alias."<<std::endl;
            return 1;
    }else if(name_alias.size()==2) {
            alias=name_alias[0];
            type=name_alias[1];
            TrimWhiteSpaceBeforeAfter(alias);
    }else if(name_alias.size()==1) type=name_alias[0];
    else {
            PrintProblem()<<"No module requested"<<std::endl;
            return 2;
    }
    TrimWhiteSpaceBeforeAfter(type);
    // Get arguments to the module if they're provided
    std::vector<std::string> args;
    TokeniseByDelimiter(constructor.inside,args,",");
    if(fShouldPrint){
        std::cout<<"Adding module: '"<<type<<"'"<<std::endl;
        std::cout<<"   with alias: '"<<alias<<"'"<<std::endl;
        std::cout<<"   and "<<args.size()<<" arguments:"<<std::endl;
        for(unsigned i=0;i<args.size() ;i++)
                std::cout<<"     "<<i<<'\t'<<args[i]<<std::endl;
    }
    //Add the module to the list of modules
    modules::options* opts;
    if(alias==""){
        opts=new modules::options(type);
    }else{
        // since the module has been named, create a section to store other
        // options that may be provided subsequently
        if(!AddSection(alias,type)){
            PrintProblem()<<" module alias is being reused"<<std::endl;
            return 1;
        }
        opts=fAllOptions[alias];
        opts->SetAlias(alias);
    }
    // Add all arguments passed to this module to it's options
    for(unsigned i=0;i<args.size();i++) {
        opts->AddArgument(i,args[i]);
    }
    // Stick this module into the list of modules
    fModules.push_back(std::make_pair(type,opts));
    fModulesCounts[type]++;
    // Apply current global options to new module
    if(fDebugAll) AddOption(opts,"debug");
    return 0;
}
void modules::reader::AddOption (modules::options * module, const std::string & flag) [private]
Definition at line 211 of file ModulesReader.cpp.
References modules::options::SetOption().
{
    options->SetOption(flag,"");
}
void modules::reader::AddOption (modules::options * module, const Option_t & opt) [private]
Definition at line 193 of file ModulesReader.cpp.
References modules::options::AppendToOption(), fShouldPrint, kAppend, modules::reader::Option_t::key, kSet, modules::reader::Option_t::mode, modules::options::SetOption(), and modules::reader::Option_t::value.
{
    bool exists;
    switch (opt.mode){
        case kSet:
            options->SetOption(opt.key,opt.value);
            break;
        case kAppend:
            exists= options->AppendToOption(opt.key,opt.value);
            if(!exists &&fShouldPrint){
                    std::cout<<"Cannot append to '"<<opt.key<<"' as it doesn't already exist"<<std::endl;
            }
            break;
        default:
            std::cout<<"modules::reader::AddOption(): That's odd!  How did I end up here?"<<std::endl;
            break;
    }
}
void modules::reader::AddOption (const std::string & module, const std::string & flag) [inline, private]
Definition at line 54 of file ModulesReader.h.
References AddOption(), and fAllOptions.
Referenced by AddOption().
{ AddOption(fAllOptions[module],flag); }
void modules::reader::AddOption (const std::string & module, const Option_t & opt) [inline, private]
Definition at line 53 of file ModulesReader.h.
References AddOption(), and fAllOptions.
Referenced by AddModule(), AddOption(), and ReadFile().
{ AddOption(fAllOptions[module],opt); }
void modules::reader::AddOptionAll (const Option_t & opt) [inline, private]
Definition at line 86 of file ModulesReader.h.
References AddOptionAll(), modules::reader::Option_t::key, and modules::reader::Option_t::value.
{
        AddOptionAll(opt.key,opt.value);
}
void modules::reader::AddOptionAll (const std::string & key, const std::string & value = "") [private]
Definition at line 259 of file ModulesReader.cpp.
References fAllOptions, and fGlobalModule.
Referenced by AddOptionAll(), and SetDebugAll().
{
    for(SectionsList::iterator it_sec=fAllOptions.begin(); it_sec != fAllOptions.end();it_sec++){
       if(it_sec->first==fGlobalModule) continue;
       it_sec->second->SetOption(key,value);
    }
}
bool modules::reader::AddSection (const std::string & name, const std::string & type = "") [inline, private]
Definition at line 78 of file ModulesReader.h.
References fAllOptions.
Referenced by AddModule(), and ReadFile().
{
    if(fAllOptions.find(name)==fAllOptions.end()){
        fAllOptions[name] =new modules::options(type);
        return true;
    }
    return false;
}
bool modules::reader::DumpInputFile () const [inline]
Definition at line 40 of file ModulesReader.h.
References fDumpInputFile.
Referenced by modules::navigator::LoadConfigFile().
{return fDumpInputFile;}
std::string modules::reader::findSectionName (const std::string & line) [private]
Definition at line 98 of file ModulesReader.cpp.
References modules::parser::Constructor_t::inside, and modules::parser::ParseConstructor().
Referenced by ReadFile().
{
    // sections are marked with [] either side of the name
        Constructor_t section= modules::parser::ParseConstructor(line,'[',']');
    return section.inside;
}
std::string modules::reader::GetModule (unsigned int i) const [inline]
Definition at line 43 of file ModulesReader.h.
References fModules.
Referenced by load_config_file(), and modules::navigator::MakeModules().
{return fModules[i].first;};
size_t modules::reader::GetNumModules () const [inline]
Definition at line 42 of file ModulesReader.h.
References fModules.
Referenced by load_config_file(), modules::navigator::LoadConfigFile(), and modules::navigator::MakeModules().
{return fModules.size();};
modules::options* modules::reader::GetOptions (unsigned int i) const [inline]
Definition at line 44 of file ModulesReader.h.
References fModules.
Referenced by load_config_file(), and modules::navigator::MakeModules().
{return fModules[i].second;};
int modules::reader::HowMany (const std::string & name) const
Definition at line 299 of file ModulesReader.cpp.
References fModulesCounts.
Referenced by modules::navigator::HowMany().
{
    ModuleCounts::const_iterator it=fModulesCounts.find(name);
    if(it!=fModulesCounts.end()) return it->second;
    return 0;
}
bool modules::reader::isComment (std::stringstream & line) [private]
Definition at line 86 of file ModulesReader.cpp.
Referenced by ReadFile().
{
    char word='\0';
    line>>word;
    if(word=='#' || word =='\0'){
        return true;
    }
    line.clear();
    line.seekg(0,std::stringstream::beg);
    //line<<word;
    return false;
}
int modules::reader::MakeModules (const SectionsList &) [private]
int modules::reader::OpenFile (const char * name, std::ifstream & infile) [private]
Definition at line 75 of file ModulesReader.cpp.
References fShouldPrint.
Referenced by ReadFile().
{
    infile.close();
    infile.open(name, std::ifstream::in);
    if(!infile.is_open()) {
        std::cout<<"Problem opening modules file: "<<name<<std::endl;
        return 1;
    }
    if(fShouldPrint) std::cout<<"Found modules file: "<<name<<std::endl;
    return 0;
}
void modules::reader::PrintAllOptions () const
Definition at line 215 of file ModulesReader.cpp.
References fAllOptions, fGlobalModule, and fModules.
Referenced by load_config_file(), and ReadFile().
{
    // Global options that were set
    SectionsList::const_iterator it_sec=fAllOptions.find(fGlobalModule);
    if(it_sec!=fAllOptions.end() && it_sec->second->GetNumOptions()>0){
       std::cout<<"== Global otions =="<<std::endl;
       it_sec->second->DumpOptions();
       std::cout<<std::endl;
    }
    // Modules that were requested
    std::cout<<"== All modules =="<<std::endl;
    ModuleList::const_iterator it_mod;
    for(it_mod=fModules.begin(); it_mod != fModules.end();it_mod++){
        std::cout<<"Module: "<<it_mod->first<<std::endl;
        it_mod->second->DumpOptions();
        std::cout<<std::endl;
    }
    // Sections that were added, but don't correspond to a module
    std::cout<<"== Unused sections =="<<std::endl;
    for(it_sec=fAllOptions.begin(); it_sec != fAllOptions.end();it_sec++){
        if(it_sec->first==fGlobalModule) continue;
        for(it_mod=fModules.begin(); it_mod != fModules.end();it_mod++){
            if(it_sec->second==it_mod->second ) break;
        }
        if(it_mod!=fModules.end()) continue;
        std::cout<<"Section: "<<it_sec->first<<std::endl;
        it_sec->second->DumpOptions();
        std::cout<<std::endl;
    }
}
std::ostream & modules::reader::PrintProblem () [private]
Definition at line 295 of file ModulesReader.cpp.
References fLineNumber.
Referenced by AddModule().
{
        return std::cout<<"Problem on line "<<fLineNumber<<": ";
}
void modules::reader::ProcessGlobalOption (Option_t opt) [private]
Definition at line 266 of file ModulesReader.cpp.
References fDumpContents, fDumpInputFile, fShouldPrint, modules::factory::Instance(), modules::navigator::Instance(), kAppend, modules::reader::Option_t::key, modules::reader::Option_t::mode, TemplateFactory< BaseModule, OptionsType >::PrintPossibleModules(), SetDebug(), modules::navigator::SetDebug(), SetDebugAll(), modules::parser::TokeniseByWhiteSpace(), and modules::reader::Option_t::value.
Referenced by ReadFile().
{
  if (opt.mode==kAppend) {
     if(fShouldPrint) std::cout<<"Warning: over-writing '"<<opt.key<<"' with '"
                     << opt.value<<"' despite append operator being used"<<std::endl;
  }
  if (opt.key=="debug"){
     std::vector<std::string> args;
     modules::parser::TokeniseByWhiteSpace(opt.value,args );
     for(unsigned i=0;i<args.size();i++){
       if (args[i]=="all"){
          SetDebugAll();
       }else if (args[i]=="modules_navigator"){
       modules::navigator::Instance()->SetDebug();
       }else if (args[i]=="modules_reader"){
          SetDebug();
       }
     }
  }else if(opt.key=="list_modules"){
    modules::factory::Instance()->PrintPossibleModules();
  }else if(opt.key=="show_input_data"){
    fDumpInputFile=true;
  }else if(opt.key=="dump_contents"){
    fDumpContents=true;
  }else {
     if(fShouldPrint) std::cout<<"Warning: Unknown global option given, '"<<opt.key<<"'"<<std::endl;
     return;
  }
}
int modules::reader::ReadFile (const char * name)
Definition at line 17 of file ModulesReader.cpp.
References AddModule(), AddOption(), AddSection(), fDumpContents, fGlobalModule, findSectionName(), fLineNumber, fShouldPrint, isComment(), OpenFile(), PrintAllOptions(), ProcessGlobalOption(), and SplitOption().
Referenced by load_config_file(), and modules::navigator::LoadConfigFile().
{
    // Open config file
    std::ifstream infile;
    int ret = OpenFile(name,infile);
    if(ret!=0) return ret;
    // make sure we have a default section set up
    AddSection(fGlobalModule);
    // Loop over each line
    std::string full_line;
    std::string section=fGlobalModule, new_section;
    Option_t current_opt;
    fLineNumber=0;
    while(std::getline(infile,full_line)){
      fLineNumber++;
      // tokenize the line straight away
      std::stringstream line(full_line);
      // check if this line is a comment
      if(isComment(line) ) continue;
      // If this line contains a section name make sure we begin a new section
      new_section=findSectionName(full_line);
      if(new_section!="") {
          section=new_section;
          if(fShouldPrint) std::cout<<"Found new section: '"<<section<<"'"<<std::endl;
          if(section!="MODULES") {
            AddSection(section);
          }
          continue;
      }
      if(section=="MODULES") {
        //  In the MODULES secton each line specifies a module to use
          ret=AddModule(full_line);
          if(ret!=0) return ret;
      }else{
          // Parse the contents of this option
          current_opt=SplitOption(full_line);
          // Handle the option as required
          if(section==fGlobalModule) {
            ProcessGlobalOption(current_opt);
          } else{
            AddOption(section,current_opt);
          }
          if(fShouldPrint) std::cout<<"Found option: "<<full_line<<std::endl;
      }
    }
    // were we asked to dump everything that's been processed?
    if(fDumpContents) PrintAllOptions();
    return 0;
}
void modules::reader::SetDebug ()
Definition at line 247 of file ModulesReader.cpp.
References fShouldPrint, modules::factory::Instance(), and TemplateFactory< BaseModule, OptionsType >::SetDebug().
Referenced by ProcessGlobalOption().
{
    std::cout<<"Debug mode activated"<<std::endl;
    fShouldPrint=true;
    modules::factory::Instance()->SetDebug();
}
void modules::reader::SetDebugAll ()
Definition at line 253 of file ModulesReader.cpp.
References AddOptionAll(), and fDebugAll.
Referenced by ProcessGlobalOption().
{
    //SetDebug();
    fDebugAll=true;
    AddOptionAll("debug");
}
modules::reader::Option_t modules::reader::SplitOption (const std::string & line) [private]
Definition at line 170 of file ModulesReader.cpp.
References kAppend, modules::reader::Option_t::key, kSet, modules::reader::Option_t::mode, and modules::reader::Option_t::value.
Referenced by ReadFile().
{
    Option_t opt;
    opt.value="";
    opt.mode=kSet;
    //split the line around any equals sign
    size_t equ_pos=line.find('=');
    if(equ_pos==std::string::npos) {
      // no equal sign, treat option as bool flag
        opt.key=line;
    }else if(line[equ_pos-1]=='+'){
      // option should be appended to an existing one
        opt.key=line.substr(0,equ_pos-1);
        opt.value=line.substr(equ_pos+1);
        opt.mode=kAppend;
    }else{
      // option is simple key value pair
        opt.key=line.substr(0,equ_pos);
        opt.value=line.substr(equ_pos+1);
    }
    return opt;
}
Member Data Documentation
SectionsList modules::reader::fAllOptions [private]
Definition at line 67 of file ModulesReader.h.
Referenced by AddModule(), AddOption(), AddOptionAll(), AddSection(), and PrintAllOptions().
bool modules::reader::fDebugAll [private]
Definition at line 73 of file ModulesReader.h.
Referenced by AddModule(), and SetDebugAll().
bool modules::reader::fDumpContents [private]
Definition at line 74 of file ModulesReader.h.
Referenced by ProcessGlobalOption(), and ReadFile().
bool modules::reader::fDumpInputFile [private]
Definition at line 75 of file ModulesReader.h.
Referenced by DumpInputFile(), and ProcessGlobalOption().
const char * modules::reader::fGlobalModule = "global" [static, private]
Definition at line 70 of file ModulesReader.h.
Referenced by AddOptionAll(), PrintAllOptions(), and ReadFile().
int modules::reader::fLineNumber [private]
Definition at line 71 of file ModulesReader.h.
Referenced by PrintProblem(), and ReadFile().
ModuleList modules::reader::fModules [private]
Definition at line 68 of file ModulesReader.h.
Referenced by AddModule(), GetModule(), GetNumModules(), GetOptions(), and PrintAllOptions().
ModuleCounts modules::reader::fModulesCounts [private]
Definition at line 69 of file ModulesReader.h.
Referenced by AddModule(), and HowMany().
bool modules::reader::fShouldPrint [private]
Definition at line 72 of file ModulesReader.h.
Referenced by AddModule(), AddOption(), OpenFile(), ProcessGlobalOption(), ReadFile(), and SetDebug().
The documentation for this class was generated from the following files:
rootana/src/framework/ModulesReader.h
rootana/src/framework/ModulesReader.cpp