AlcapDAQ: MaxBinAPGenerator Class Reference
MaxBinAPGenerator Class Reference
#include <MaxBinAPGenerator.h>
Public Member Functions
MaxBinAPGenerator (TAPGeneratorOptions *opts)
virtual ~MaxBinAPGenerator ()
void SetBankInfo (std::string bankname)
virtual int ProcessPulses (const PulseIslandList &, AnalysedPulseList &)
This method is called on each vector of pulses from a MIDAS event.
virtual bool MayDivideTPIs ()
void GetAllParameters_MaxBin (const TPulseIsland *pulse, double &amplitude, double &time, double &integral, double &energy)
void SetPulseList (PulseIslandList *list)
template<typename TypeOfTAP >
TypeOfTAP * MakeNewTAP (int parent_index) const
The suggested method for constructing a new TAP.
TAnalysedPulse * MakeNewTAP (int parent_index) const
bool Debug () const
IDs::channel GetChannel () const
IDs::source GetSource () const
Get the source id for this generator being used on the current channel.
Private Attributes
std::string fBankname
std::string fDetName
double fPedestal
int fTriggerPolarity
double fECalibSlope
double fECalibOffset
double fClockTick
double fTimeShift
TSetupData * fSetup
Detailed Description
Definition at line 12 of file MaxBinAPGenerator.h.
Constructor & Destructor Documentation
MaxBinAPGenerator::MaxBinAPGenerator (TAPGeneratorOptions * opts) [inline]
Definition at line 15 of file MaxBinAPGenerator.h.
                                              :
          TVAnalysedPulseGenerator("MaxBin", opts),fSetup(TSetupData::Instance()){};
virtual MaxBinAPGenerator::~MaxBinAPGenerator () [inline, virtual]
Definition at line 18 of file MaxBinAPGenerator.h.
{};
Member Function Documentation
bool TVAnalysedPulseGenerator::Debug () const [inline, inherited]
Definition at line 79 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fDebug.
Referenced by GaussFitAPGenerator::FitPulse().
{return fDebug;};
void MaxBinAPGenerator::GetAllParameters_MaxBin (const TPulseIsland * pulse, double & amplitude, double & time, double & integral, double & energy)
Definition at line 44 of file MaxBinAPGenerator.cpp.
References fClockTick, fECalibOffset, fECalibSlope, fPedestal, fTimeShift, fTriggerPolarity, TPulseIsland::GetSamples(), and TPulseIsland::GetTimeStamp().
Referenced by ProcessPulses().
{
  // First find the position of the peak
  std::vector<int> pulseSamples = pulse->GetSamples();
  std::vector<int>::iterator peak_sample_pos;
  if (fTriggerPolarity == 1)
    peak_sample_pos = std::max_element(pulseSamples.begin(), pulseSamples.end());
  else
    peak_sample_pos = std::min_element(pulseSamples.begin(), pulseSamples.end());
  // Now assign the parameters
  amplitude = fTriggerPolarity*(*peak_sample_pos - fPedestal);
  time = ((pulse->GetTimeStamp() + (peak_sample_pos - pulseSamples.begin())) * fClockTick) - fTimeShift;
  integral = 0;
  energy = fECalibSlope * amplitude + fECalibOffset;
}
IDs::channel TVAnalysedPulseGenerator::GetChannel () const [inline, inherited]
A convenience method for analysis to get the channel ID of the channel being analysed
Definition at line 83 of file TVAnalysedPulseGenerator.h.
References IDs::source::Channel(), and TVAnalysedPulseGenerator::fSource.
{return fSource.Channel();};
IDs::source TVAnalysedPulseGenerator::GetSource () const [inline, inherited]
Get the source id for this generator being used on the current channel.
Useful for a generator to know the full source much like in the above GetChannel method, but this could also be useful for checking that this generator is the one that made a given TAP in later analysis by comparing this value to that stored in the TAP itself.
Definition at line 92 of file TVAnalysedPulseGenerator.h.
Referenced by TVAnalysedPulseGenerator::MakeNewTAP().
{return fSource;};
TAnalysedPulse* TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
Definition at line 75 of file TVAnalysedPulseGenerator.h.
{
            return MakeNewTAP<TAnalysedPulse>(parent_index);
        }
template<typename TypeOfTAP > TypeOfTAP * TVAnalysedPulseGenerator::MakeNewTAP (int parent_index) const [inline, inherited]
The suggested method for constructing a new TAP.
In the process of constructing TAP, information that isn't immediately obvious how to get needs to be passed to TAP. This method returns a pointer to a TAP construced for you, and all you need to pass it is the TPulseIslandID.
In the case where a generator wants to add extra information to the standard TAP information, we expect people to derive from TAnalysedPulse. If your generator is one of these, then use the template argument to produce the type of TAP you desire. Note that this forces the constructor of the specialised TAP to be the same as for TAnalysedPulse itself.
For example, for to make a specialied analysed pulse called TSpecialAnalysedPulse (original, huh?) you would do:
 TSpecialAnalysedPulse* tsap=MakeNewTAP<TSpecialAnalysedPulse>(parent_index);
Parameters:
[in] parent_index The TPulseIslandID of the TPI being used to make the new TAP.
Template Parameters:
in] TypeOfTAP The type of specialisation of TAnalysedPulse that you want to create.
Definition at line 120 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList, and TVAnalysedPulseGenerator::GetSource().
Referenced by SimpIntAPGenerator::ProcessPulses(), ProcessPulses(), and CFTimeAPGenerator::ProcessPulses().
{
    TypeOfTAP* pulse=NULL;
    try{
        TPulseIsland* parent = fPulseList->at(parent_index);
        pulse=new TypeOfTAP(GetSource(),parent_index,parent);
    } catch (std::out_of_range){}
    return pulse;
}
virtual bool MaxBinAPGenerator::MayDivideTPIs () [inline, virtual]
Todo:
Document this
Implements TVAnalysedPulseGenerator.
Definition at line 32 of file MaxBinAPGenerator.h.
{return false;};
int MaxBinAPGenerator::ProcessPulses (const PulseIslandList & pil, AnalysedPulseList & apl) [virtual]
This method is called on each vector of pulses from a MIDAS event.
Parameters:
[in] pil The vector of TPIs to produce TAPs from.
[out] apl The vector of TAPs to append the new TAPs to.
Implements TVAnalysedPulseGenerator.
Definition at line 16 of file MaxBinAPGenerator.cpp.
References GetAllParameters_MaxBin(), IsTimeOrdered(), TVAnalysedPulseGenerator::MakeNewTAP(), TAnalysedPulse::SetAmplitude(), SetBankInfo(), TAnalysedPulse::SetEnergy(), and TAnalysedPulse::SetTime().
{
      SetBankInfo(pulseList.at(0)->GetBankName());
      double amplitude, time, integral, energy;
      TAnalysedPulse* outPulse;
      for (PulseIslandList::const_iterator pulseIter = pulseList.begin(); pulseIter != pulseList.end(); pulseIter++) {
         amplitude = 0;
         time = 0;
         integral = 0;
         energy = 0.;
         // Assume one TAnalysedPulse per TPulseIsland
         GetAllParameters_MaxBin(*pulseIter,amplitude,time,integral,energy);
         // Make the TAnalysedPulse pulse
         outPulse=MakeNewTAP(pulseIter-pulseList.begin());
         outPulse->SetAmplitude(amplitude);
         outPulse->SetTime(time);
         outPulse->SetEnergy(energy);
         // Add the pulse into the list
         analysedList.push_back(outPulse);
      }
      std::sort(analysedList.begin(), analysedList.end(), IsTimeOrdered);
      return 0;
}
void MaxBinAPGenerator::SetBankInfo (std::string bankname) [inline]
Definition at line 19 of file MaxBinAPGenerator.h.
References fBankname, fClockTick, fDetName, fECalibOffset, fECalibSlope, fPedestal, fSetup, fTimeShift, fTriggerPolarity, TSetupData::GetADCOffsetCalib(), TSetupData::GetADCSlopeCalib(), TSetupData::GetClockTick(), TSetupData::GetDetectorName(), TSetupData::GetPedestal(), TSetupData::GetTimeShift(), and TSetupData::GetTriggerPolarity().
Referenced by ProcessPulses().
{
      fBankname=bankname;
      fPedestal = fSetup->GetPedestal(bankname);
      fTriggerPolarity = fSetup->GetTriggerPolarity(bankname);
      fECalibSlope = fSetup->GetADCSlopeCalib(bankname);
      fECalibOffset = fSetup->GetADCOffsetCalib(bankname);
      fClockTick = fSetup->GetClockTick(bankname);
      fTimeShift = fSetup->GetTimeShift(bankname);
      fDetName=fSetup->GetDetectorName(bankname);
   }
void TVAnalysedPulseGenerator::SetPulseList (PulseIslandList * list) [inline, inherited]
Definition at line 46 of file TVAnalysedPulseGenerator.h.
References TVAnalysedPulseGenerator::fPulseList.
{fPulseList=list;};
Field Documentation
std::string MaxBinAPGenerator::fBankname [private]
Definition at line 40 of file MaxBinAPGenerator.h.
Referenced by SetBankInfo().
double MaxBinAPGenerator::fClockTick [private]
Definition at line 46 of file MaxBinAPGenerator.h.
Referenced by GetAllParameters_MaxBin(), and SetBankInfo().
std::string MaxBinAPGenerator::fDetName [private]
Definition at line 41 of file MaxBinAPGenerator.h.
Referenced by SetBankInfo().
double MaxBinAPGenerator::fECalibOffset [private]
Definition at line 45 of file MaxBinAPGenerator.h.
Referenced by GetAllParameters_MaxBin(), and SetBankInfo().
double MaxBinAPGenerator::fECalibSlope [private]
Definition at line 44 of file MaxBinAPGenerator.h.
Referenced by GetAllParameters_MaxBin(), and SetBankInfo().
double MaxBinAPGenerator::fPedestal [private]
Definition at line 42 of file MaxBinAPGenerator.h.
Referenced by GetAllParameters_MaxBin(), and SetBankInfo().
TSetupData* MaxBinAPGenerator::fSetup [private]
Definition at line 48 of file MaxBinAPGenerator.h.
Referenced by SetBankInfo().
double MaxBinAPGenerator::fTimeShift [private]
Definition at line 47 of file MaxBinAPGenerator.h.
Referenced by GetAllParameters_MaxBin(), and SetBankInfo().
int MaxBinAPGenerator::fTriggerPolarity [private]
Definition at line 43 of file MaxBinAPGenerator.h.
Referenced by GetAllParameters_MaxBin(), and SetBankInfo().
The documentation for this class was generated from the following files:
rootana/src/TAP_generators/MaxBinAPGenerator.h
rootana/src/TAP_generators/MaxBinAPGenerator.cpp