AlcapDAQ: PlotTime Class Reference
PlotTime Class Reference
#include <PlotTime.h>
Public Member Functions
PlotTime (char *HistogramDirectoryName)
PlotTime (modules::options *opts)
~PlotTime ()
int ProcessGenericEntry (TGlobalData *gData, TSetupData *gSetup)
virtual int BeforeFirstEntry (TGlobalData *gData, TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, TSetupData *setup)
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
Protected Attributes
TDirectory * dir
TSetupData * fSetup
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, TSetupData *gSetup)
The big kahuna. Overload this in the derived class and it will be called for each event.
Private Attributes
std::map< std::string, TH1F * > fTimePlots
Detailed Description
Definition at line 9 of file PlotTime.h.
Constructor & Destructor Documentation
PlotTime::PlotTime (char * HistogramDirectoryName)
Definition at line 25 of file PlotTime.cpp.
References BaseModule::dir.
                                               :
  BaseModule(HistogramDirectoryName){
  dir->cd("/");
}
PlotTime::PlotTime (modules::options * opts)
Definition at line 30 of file PlotTime.cpp.
References BaseModule::dir.
                                       : BaseModule(opts->GetString("0").c_str()) {
  dir->cd("/");
}
PlotTime::~PlotTime ()
Definition at line 34 of file PlotTime.cpp.
                   {
}
Member Function Documentation
virtual int BaseModule::AfterLastEntry (TGlobalData * gData, TSetupData * setup) [inline, virtual, inherited]
Optional method which is called once after the main event loop Can be used to dump a summary or finalise a histogram
Returns:
0 on sucess and non-zero if a problem occurred
Reimplemented in PlotPedestalAndNoise, PulseViewer, PulseCandidateFinder_InvestigateParameters, and TemplateCreator.
Definition at line 44 of file BaseModule.h.
{return 0;};
virtual int BaseModule::BeforeFirstEntry (TGlobalData * gData, TSetupData * setup) [inline, virtual, inherited]
Optional method which is called once before the main event loop Can be used to parse options and setup histograms.
Returns:
0 on sucess and non-zero if a problem occurred
Reimplemented in ExportPulse, PlotPedestalAndNoise, PulseViewer, MakeAnalysedPulses, PulseCandidateFinder_InvestigateParameters, TemplateCreator, MakeDetectorPulses, and MakeMuonEvents.
Definition at line 39 of file BaseModule.h.
{return 0;};
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 60 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), TemplateCreator::AfterLastEntry(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PulseViewer::AfterLastEntry(), PlotPedestalAndNoise::AfterLastEntry(), MakeMuonEvents::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotPedestalAndNoise::BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), and PulseViewer::ProcessEntry().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 52 of file BaseModule.h.
References BaseModule::fAlias.
{return fAlias;};
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 55 of file BaseModule.h.
References BaseModule::dir.
Referenced by ProcessEntry(), and PlotAmplitude::ProcessEntry().
{return dir->GetName();};
int PlotTime::ProcessEntry (TGlobalData * gData, TSetupData * gSetup) [private, virtual]
The big kahuna. Overload this in the derived class and it will be called for each event.
Parameters:
gData Pointer to current map of all TPIs [ WILL CHANGE SHORTLY ]
gSetup Pointer to TSetupData for this run [ WILL CHANGE SHORTLY ]
Returns:
0 on success and non-zero on failure
Reimplemented from BaseModule.
Definition at line 37 of file PlotTime.cpp.
References fTimePlots, gAnalysedPulseMap, and BaseModule::GetName().
{
  // Loop through and find a fast channel
  //  std::cout << "Size of gAnalysedPulseMap " << gAnalysedPulseMap.size() << std::endl;
  for (StringAnalPulseMap::iterator detIter = gAnalysedPulseMap.begin(); detIter != gAnalysedPulseMap.end(); detIter++) {
    std::string detname = detIter->first;
    // Create the histogram if it's not been created yet
    if ( fTimePlots.find(detname) == fTimePlots.end() ) {
      // hTimeCorrelation
      std::string histname = "h" + detname + "_" + GetName();
      std::string histtitle = "Plot of the time of pulses in the " + detname + " detector";
      TH1F* hTimeCorrelation = new TH1F(histname.c_str(), histtitle.c_str(), 1e6,0,1e8);
      hTimeCorrelation->GetXaxis()->SetTitle("Time [ns]");
      hTimeCorrelation->GetYaxis()->SetTitle("Arbitrary Unit");
      fTimePlots[detname] = hTimeCorrelation;
    }
    AnalysedPulseList pulses = detIter->second;
    for (AnalysedPulseList::iterator pulseIter = pulses.begin(); pulseIter != pulses.end(); ++pulseIter) {
      double time = (*pulseIter)->GetTime();
      fTimePlots[detname]->Fill(time);
    } // end loop through pulses
  } // end loop through detectors
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 25 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::ProcessEntry().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(dir) dir->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 48 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by modules::factory::createModule().
{fAlias=alias;};
Field Documentation
TDirectory* BaseModule::dir [protected, inherited]
Definition at line 73 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), ExportPulse::ExportPulse(), BaseModule::GetName(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmplitude::PlotAmplitude(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTime(), and BaseModule::ProcessGenericEntry().
TSetupData* BaseModule::fSetup [protected, inherited]
Reimplemented in ExportPulse.
Definition at line 74 of file BaseModule.h.
std::map<std::string, TH1F*> PlotTime::fTimePlots [private]
Definition at line 18 of file PlotTime.h.
Referenced by ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/plotters/PlotTime.h
rootana/src/plotters/PlotTime.cpp