AlcapDAQ: TDetectorPulse Class Reference
TDetectorPulse Class Reference
#include <TDetectorPulse.h>
Classes
struct Tag
Public Types
enum ParentChannel_t { kSlow, kFast, kNumParents }
Public Member Functions
TDetectorPulse ()
TDetectorPulse (const IDs::source &sourceID, int s_parentID, const TAnalysedPulse *s_parent, int f_parentID, const TAnalysedPulse *f_parent)
virtual ~TDetectorPulse ()
void Reset (Option_t *o="")
double GetTime (ParentChannel_t ch=kFast) const
double GetAmplitude (ParentChannel_t ch=kFast) const
double GetIntegral (ParentChannel_t ch=kFast) const
double GetPedestal (ParentChannel_t ch=kFast) const
const TAnalysedPulse * GetTAP (ParentChannel_t ch) const
const IDs::source & GetSource () const
bool IsPileUpSafe () const
void SetPileUpSafe (const bool &val=true)
bool WasPileUpChecked () const
void SetPileUpChecked (const bool &val=true)
bool IsPairedPulse () const
Private Member Functions
ClassDef (TDetectorPulse, 2)
Private Attributes
bool fCheckedForPileUp
bool fPileUpSafe
const TAnalysedPulse * fParentPulse [kNumParents]
int fParentID [kNumParents]
FlyWeight< IDs::source,
TAnalysedPulse::Tag > fParentSource [kNumParents]
FlyWeight< IDs::source, Tag > fSource
Detailed Description
Definition at line 19 of file TDetectorPulse.h.
Member Enumeration Documentation
enum TDetectorPulse::ParentChannel_t
Enumerator:
kSlow
kFast
kNumParents
Definition at line 21 of file TDetectorPulse.h.
{ kSlow,kFast, kNumParents};
Constructor & Destructor Documentation
TDetectorPulse::TDetectorPulse ()
Definition at line 14 of file TDetectorPulse.cpp.
References Reset().
{
  Reset();
}
TDetectorPulse::TDetectorPulse (const IDs::source & sourceID, int s_parentID, const TAnalysedPulse * s_parent, int f_parentID, const TAnalysedPulse * f_parent)
Definition at line 18 of file TDetectorPulse.cpp.
References fParentID, fParentPulse, fParentSource, fSource, TAnalysedPulse::GetSource(), kFast, kSlow, and Reset().
                 {
  Reset();
  fParentPulse[kSlow] = s_parent;
  fParentPulse[kFast] = f_parent;
  if(s_parent) fParentSource[kSlow]= s_parent->GetSource();
  if(f_parent) fParentSource[kFast]= f_parent->GetSource();
  fParentID[kSlow]=s_parentID;
  fParentID[kFast]=f_parentID;
  fSource=sourceID;
}
TDetectorPulse::~TDetectorPulse () [virtual]
Definition at line 12 of file TDetectorPulse.cpp.
{}
Member Function Documentation
TDetectorPulse::ClassDef (TDetectorPulse , 2) [private]
double TDetectorPulse::GetAmplitude (ParentChannel_t ch = kFast) const [inline]
Definition at line 36 of file TDetectorPulse.h.
References TDP_GetField.
{
            TDP_GetField(ch,Amplitude); }
double TDetectorPulse::GetIntegral (ParentChannel_t ch = kFast) const [inline]
Definition at line 38 of file TDetectorPulse.h.
References TDP_GetField.
{
            TDP_GetField(ch,Integral); }
double TDetectorPulse::GetPedestal (ParentChannel_t ch = kFast) const [inline]
Definition at line 40 of file TDetectorPulse.h.
References TDP_GetField.
{
            TDP_GetField(ch,Pedestal); }
const IDs::source& TDetectorPulse::GetSource () const [inline]
Definition at line 44 of file TDetectorPulse.h.
References fSource, and FlyWeight< ValueType, UniqueTag >::GetValue().
Referenced by MaxTimeDiffMEGenerator::ProcessPulses().
{ return fSource.GetValue(); }
const TAnalysedPulse* TDetectorPulse::GetTAP (ParentChannel_t ch) const [inline]
Definition at line 42 of file TDetectorPulse.h.
References fParentPulse.
{return fParentPulse[ch];}
double TDetectorPulse::GetTime (ParentChannel_t ch = kFast) const [inline]
Definition at line 34 of file TDetectorPulse.h.
References TDP_GetField.
Referenced by TMuonEvent::GetTime(), MaxTimeDiffMEGenerator::ProcessPulses(), and MaxTimeDiffDPGenerator::ProcessPulses().
{
            TDP_GetField(ch,Time); }
bool TDetectorPulse::IsPairedPulse () const [inline]
Definition at line 51 of file TDetectorPulse.h.
References fParentPulse, kFast, and kSlow.
{return fParentPulse[kFast]&&fParentPulse[kSlow];}
bool TDetectorPulse::IsPileUpSafe () const [inline]
Definition at line 46 of file TDetectorPulse.h.
References fCheckedForPileUp, and fPileUpSafe.
{return fPileUpSafe&&fCheckedForPileUp;};
void TDetectorPulse::Reset (Option_t * o = "")
Definition at line 32 of file TDetectorPulse.cpp.
References fCheckedForPileUp, fParentID, fParentPulse, fParentSource, fPileUpSafe, kNumParents, and FlyWeight< ValueType, UniqueTag >::Reset().
Referenced by TDetectorPulse().
{
    for(int i=0;i<kNumParents;++i){
        fParentPulse[i] = NULL;
        fParentID[i]=-1;
        fParentSource[i].Reset();
    }
    fCheckedForPileUp=false;
    fPileUpSafe=false;
}
void TDetectorPulse::SetPileUpChecked (const bool & val = true) [inline]
Definition at line 49 of file TDetectorPulse.h.
References fCheckedForPileUp.
{ fCheckedForPileUp=val;};
void TDetectorPulse::SetPileUpSafe (const bool & val = true) [inline]
Definition at line 47 of file TDetectorPulse.h.
References fCheckedForPileUp, and fPileUpSafe.
{fPileUpSafe=val;fCheckedForPileUp=true;};
bool TDetectorPulse::WasPileUpChecked () const [inline]
Definition at line 48 of file TDetectorPulse.h.
References fCheckedForPileUp.
{return fCheckedForPileUp;};
Member Data Documentation
bool TDetectorPulse::fCheckedForPileUp [private]
Definition at line 54 of file TDetectorPulse.h.
Referenced by IsPileUpSafe(), Reset(), SetPileUpChecked(), SetPileUpSafe(), and WasPileUpChecked().
int TDetectorPulse::fParentID[kNumParents] [private]
Definition at line 58 of file TDetectorPulse.h.
Referenced by Reset(), and TDetectorPulse().
const TAnalysedPulse* TDetectorPulse::fParentPulse[kNumParents] [private]
Definition at line 57 of file TDetectorPulse.h.
Referenced by GetTAP(), IsPairedPulse(), Reset(), and TDetectorPulse().
FlyWeight<IDs::source,TAnalysedPulse::Tag> TDetectorPulse::fParentSource[kNumParents] [private]
Definition at line 61 of file TDetectorPulse.h.
Referenced by Reset(), and TDetectorPulse().
bool TDetectorPulse::fPileUpSafe [private]
Definition at line 55 of file TDetectorPulse.h.
Referenced by IsPileUpSafe(), Reset(), and SetPileUpSafe().
FlyWeight<IDs::source,Tag> TDetectorPulse::fSource [private]
Definition at line 62 of file TDetectorPulse.h.
Referenced by GetSource(), and TDetectorPulse().
The documentation for this class was generated from the following files:
rootana/src/TDP_generators/TDetectorPulse.h
rootana/src/TDP_generators/TDetectorPulse.cpp