AlcapDAQ: FillHistBase Class Reference
FillHistBase Class Reference
#include <FillHistBase.h>
Public Member Functions
FillHistBase (const char *HistogramDirectoryName, modules::options *opts=NULL, TSetupData *setup=NULL)
virtual ~FillHistBase ()
int ProcessGenericEntry (TGlobalData *gData, TSetupData *gSetup)
virtual int BeforeFirstEntry (TGlobalData *gData, TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, TSetupData *setup)
const char * GetName () const
Protected Member Functions
bool Debug () const
Protected Attributes
TDirectory * dir
TSetupData * fSetup
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, TSetupData *gSetup)
Private Attributes
bool fDebug
Detailed Description
Definition at line 31 of file FillHistBase.h.
Constructor & Destructor Documentation
FillHistBase::FillHistBase (const char * HistogramDirectoryName, modules::options * opts = NULL, TSetupData * setup = NULL)
Definition at line 5 of file FillHistBase.cpp.
References dir, fDebug, and modules::options::HasOption().
                                                                                                    :
         fSetup(setup),fDebug(false){
   if(opts){
     fDebug=opts->HasOption("debug");
     //std::cout<<"Should we debug module: "<<HistogramDirectoryName<<": "<<(fDebug?"yes":"no")<<std::endl;
   }
   dir = gDirectory->mkdir(HistogramDirectoryName);
   dir->cd();
 }
FillHistBase::~FillHistBase () virtual
Definition at line 15 of file FillHistBase.cpp.
 {
 }
Member Function Documentation
virtual int FillHistBase::AfterLastEntry (TGlobalData * gData, TSetupData * setup) inline virtual
Reimplemented in TestModule.
Definition at line 39 of file FillHistBase.h.
 {return 0;};
virtual int FillHistBase::BeforeFirstEntry (TGlobalData * gData, TSetupData * setup) inline virtual
Reimplemented in ExportPulse, MakeAnalysedPulses, MakeDetectorPulses, MakeMuonEvents, and TestModule.
Definition at line 38 of file FillHistBase.h.
 {return 0;};
bool FillHistBase::Debug () const inline protected
Definition at line 45 of file FillHistBase.h.
References fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), TestModule::AfterLastEntry(), TestModule::BeforeFirstEntry(), MakeMuonEvents::BeforeFirstEntry(), MakeDetectorPulses::MakeGenerator(), ExportPulse::MakePlot(), and MakeAnalysedPulses::ProcessEntry().
 {return fDebug;};
const char* FillHistBase::GetName () const inline
Definition at line 40 of file FillHistBase.h.
References dir.
Referenced by DeadTimeGe::ProcessEntry(), PlotAmplitude::ProcessEntry(), and PlotTime::ProcessEntry().
 {return dir->GetName();};
int FillHistBase::ProcessEntry (TGlobalData * gData, TSetupData * gSetup) private virtual
Reimplemented in ExportPulse, MakeAnalysedPulses, MakeDetectorPulses, EvdE, MakeTemplate, Normalization, SiR2Target, MakeMuonEvents, PlotAmpVsTDiff, DeadTimeGe, PlotAmplitude, PlotTime, TestModule, and Lifetime.
Definition at line 19 of file FillHistBase.cpp.
Referenced by ProcessGenericEntry().
{
   // This is a virtual function and should be overwritten by the deriving analysis module!
   return 0;
 }
int FillHistBase::ProcessGenericEntry (TGlobalData * gData, TSetupData * gSetup)
Definition at line 24 of file FillHistBase.cpp.
References dir, and ProcessEntry().
{
   // This is called by our main routine and would allow later to split into different
   // process routines if we have more than one Tree and hence different tpyes of data input.
   if(dir) dir->cd();
   int ret = ProcessEntry(gData, gSetup);
   gDirectory->cd("/");
   return ret;
 }
Field Documentation
TDirectory* FillHistBase::dir protected
Definition at line 40 of file FillHistBase.h.
Referenced by DeadTimeGe::DeadTimeGe(), ExportPulse::ExportPulse(), FillHistBase(), GetName(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmplitude::PlotAmplitude(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTime::PlotTime(), and ProcessGenericEntry().
bool FillHistBase::fDebug private
Definition at line 49 of file FillHistBase.h.
Referenced by Debug(), and FillHistBase().
TSetupData* FillHistBase::fSetup protected
Definition at line 44 of file FillHistBase.h.
The documentation for this class was generated from the following files:
analyzer/rootana/src/framework/FillHistBase.h
analyzer/rootana/src/framework/FillHistBase.cpp