AlcapDAQ: PulseTemplate Class Reference
PulseTemplate Class Reference
#include <PulseTemplate.h>
Public Member Functions
PulseTemplate (int nSigma=3, int refine=100, double convergence=0.01)
~PulseTemplate ()
void AddPulse (TPulseIsland *pulse, double shift)
double Correlation (TPulseIsland *pulse, double &ped, double &amp, double &time)
double Chi2Fit (TPulseIsland *pulse, double &pedestal, double &amplitude, double &time)
bool Converged ()
void Save (TFile *outfile)
void Print ()
int GetNumberOfPulses ()
Private Attributes
TH1D * fTemplate
TFitterMinuit * fFitter
int fNPulses
int fNSigma
int fRefine
int fNBins
double fClockTick
double fSumX
double fSumX2
double fSum2X
double fConvergence
double fConvergenceLimit
Detailed Description
Definition at line 11 of file PulseTemplate.h.
Constructor & Destructor Documentation
PulseTemplate::PulseTemplate (int nSigma = 3, int refine = 100, double convergence = 0.01)
Definition at line 15 of file PulseTemplate.cpp.
References fFitter.
                                                                        : fTemplate(NULL), fFitter(NULL), fNPulses(0),
                                                                            fNSigma(nSigma), fRefine(refine), fNBins(0),
                                                                            fClockTick(0.), fSumX(0.), fSumX2(0.),
                                                                            fSum2X(0.), fConvergence(0.), fConvergenceLimit(convergence) {
   HistogramFitFCN* fcn = new HistogramFitFCN();
   fFitter = new TFitterMinuit(3); //  Three (3) parameters to modify (amplitude, time, pedestal)
   fFitter->SetMinuitFCN(fcn);
 }
PulseTemplate::~PulseTemplate ()
Definition at line 25 of file PulseTemplate.cpp.
References fFitter, and fTemplate.
{
   delete fTemplate;
   delete fFitter; // Fitter should own HistogramFitFCN and destroy it according to documentation
 }
Member Function Documentation
void PulseTemplate::AddPulse (TPulseIsland * pulse, double shift)
Definition at line 30 of file PulseTemplate.cpp.
References c, fClockTick, fConvergence, fNBins, fNPulses, fNSigma, fRefine, fSum2X, fSumX, fSumX2, fTemplate, TPulseIsland::GetBankName(), TPulseIsland::GetClockTickInNs(), TPulseIsland::GetPedestal(), TPulseIsland::GetSamples(), TPulseIsland::GetTriggerPolarity(), i, ped, samples, and sigma.
Referenced by MakeTemplate::ProcessEntry().
{
   // Function to average in pulse with template
   // Input--
   // pulse:     Pulse to average in
   // shift:     Bin shift (timing offset of peak)
   TH1D* old_template;
   double norm;
   double peak;
   double sigma;
   double pol;
   double ped;
   int nsamps;
   std::vector<int> samples;
   std::vector<double> rectified_samples, reshaped_pulse;
   if (fNPulses > 0)
     old_template = (TH1D*)fTemplate->Clone("old_histogram");
   pol = (double)pulse->GetTriggerPolarity();
   ped = pulse->GetPedestal(0);
   samples = pulse->GetSamples();
   ped = (double)(samples[0]+samples[1]+samples[2]+samples[3]) / 4.; /*** TEMPERARY PEDESTAL ***/
   nsamps = samples.size();
   for (int i = 0; i < nsamps; ++i)
     rectified_samples.push_back(pol*((double)samples[i]-ped));
   // Get peak value for normalization
   peak = 0.;
   norm = pol * (double)samples[0];
   for (int i = 1; i < nsamps; ++i) {
     if ((double)samples[i] * pol > norm) {
       peak = (double)i;
       norm = (double)samples[i];
     }
   }
   norm *= pol;
   // Get sigma for scaling
   sigma = 0.;
   for (int i = 0; i < nsamps; ++i) {
     std::cout << i << "\t" << sigma << "," << rectified_samples[i] << "\t";
     if (i % 10 == 0)
       std::cout << std::endl;
     sigma += rectified_samples[i] * std::pow(i - peak, 2.);
   }
   sigma = std::sqrt(std::abs(sigma)) / (double)nsamps;
   // If this is the first pulse, setup some variables
   if (fNPulses == 0) {
     fClockTick = pulse->GetClockTickInNs() / (double)fRefine;
     fNBins = (int)(2. * (double)fNSigma * sigma) * fRefine;
     std::cout << "Making histogram: " << fNBins << " " << fNSigma << " " << sigma << " " << nsamps << " " << ped << std::endl;
     TString str = "template_";
     str += pulse->GetBankName();
     fTemplate = new TH1D(str, "Template", fNBins, -(double)fNSigma, (double)fNSigma);
   }
   // Reshape pulse
   // To go from course binning somehwere in the pulse
   // to fine binning in the template, just use
   // a linear f(x)=mx+b
   int pulse_index;
   double m = 2. * (double)fNSigma * sigma / (double)fNBins;
   double b = (peak + shift) - (double)fNSigma * sigma;
   for (int i = 0; i < fNBins; ++i) {
     pulse_index = (int)((double)i * m + b + 0.5); // The half shift is for bin-centering since int floors the double
     reshaped_pulse.push_back((double)samples[pulse_index] / norm);
   }
   // If this is the first pulse added to the template, smooth it.
   // In C++11, we'll have direct access to the reshaped pulse's
   // data array with vector.data(), but now we have to use
   // a somewhat circuitous route. TH1::SmoothArray takes an array
   // of doubles to smooth as an argument.
   if (fNPulses == 0) {
     unsigned int l = reshaped_pulse.size();
     double *reshaped_pulse_array = new double[l];
     for (unsigned int i = 0; i < l; ++i)
       reshaped_pulse_array[i] = reshaped_pulse[i];
     TH1::SmoothArray(reshaped_pulse.size(), reshaped_pulse_array, 1);
     for (unsigned int i = 0; i < l; ++i)
       reshaped_pulse.at(i) = reshaped_pulse_array[i];
     delete [] reshaped_pulse_array;
   }
   // Add in pulse to template
   // Histogram indexing is off by one (index 0 is the underflow bin)
   // Hence the (i+1), which really corresponds to the ith element
   // in the reshaped_pulse array.
   double x, x_old;
   double e, e_old;
   for (int i = 0; i < fNBins; ++i) {
     x_old = fTemplate->GetBinContent(i+1);
     e_old = fTemplate->GetBinError(i+1);
     x = (double)fNPulses * x_old + reshaped_pulse[i];
     x /= (double)(fNPulses + 1);
     e = (double)(fNPulses - 1) * std::pow(e_old, 2.) + ((double)reshaped_pulse[i] - x_old) * ((double)reshaped_pulse[i] - x);
     e = std::sqrt(e / fNPulses);
     fTemplate->SetBinContent(i+1, x);
     fTemplate->SetBinError(i+1, e);
   }
   // Find the change and average it with previous changes.
   // That is the dot product of the last template with
   // the new one subtracted from 1.
   if (fNPulses > 0) {
     double mag_old = old_template->Integral(1, fNBins);
     double mag_new = fTemplate->Integral(1,fNBins);
     double dot_product = 0.;
     for (int i = 1; i <= fNBins; ++i)
       dot_product += old_template->GetBinContent(i) * fTemplate->GetBinContent(i);
     double cos_similarity = dot_product / (mag_old * mag_new);
     fConvergence = ((double)(fNPulses - 1) * fConvergence + (1 - cos_similarity))/(double)fNPulses;
   }
   // Recalculate values for correlation coefficient
   fSumX = 0.;
   fSumX2 = 0.;
   int c = 0;
   for (int i = 1; i <= fNBins; ++i) {
     c = fTemplate->GetBinContent(i);
     fSumX += c;
     fSumX2 += std::pow(c, 2.);
   }
   fSum2X = std::pow(fSumX, 2.);
   // Keep track of the number of pulses
   ++fNPulses;
 }
double PulseTemplate::Chi2Fit (TPulseIsland * pulse, double & pedestal, double & amplitude, double & time)
Definition at line 167 of file PulseTemplate.cpp.
References fFitter, fRefine, fTemplate, TPulseIsland::GetSamples(), i, samples, HistogramFitFCN::SetH1(), HistogramFitFCN::SetH2(), and status.
Referenced by MakeTemplate::ProcessEntry().
{
   // First make a histogram out of the pulse with the same bin width as the template,
   // Then pass to fitter.
   // Returns ped in units of ADC counts, amp in... scale units(?), and time in units
   // of bins since the beginning of pulse
   std::vector<int> samples = pulse->GetSamples();
   int nel = samples.size();
   TH1D* rebinned_pulse = new TH1D("pulse2fit", "pulse2fit", nel * fRefine, -0.5, nel - 0.5);
   for (int i = 0; i < nel; ++i)
     for (int j = 1; j <= fRefine; ++j)
       rebinned_pulse->SetBinContent(i * fRefine + j, samples.at(i));
   time *= fRefine;
   // Prepare for minimizations
   fFitter->Clear();
   HistogramFitFCN* fcn = (HistogramFitFCN*)fFitter->GetMinuitFCN();
   fcn->SetH1(fTemplate);
   fcn->SetH2(rebinned_pulse);
   fFitter->SetParameter(0, "Pedestal", ped, 0.1, 0, 0);
   fFitter->SetParameter(1, "Amplitude", amp, 0.1, 0, 0);
   fFitter->SetParameter(2, "Time", time, 1., 0, 0); // Timing should have step size no smaller than binning,
                                                     // *IF* the fourth argument is step size this is okay,
                                                     // or later implement some interpolation method, note
                                                     // *DERIVATIVES* at bounderies of interpolation may cause
                                                     // problems since MIGRAD (the default method) relies on
                                                     // these heavily.
   fFitter->CreateMinimizer();
   // Minimize and notify if there was a problem
   int status = fFitter->Minimize();
   if (status != 0)
     std::cout << "ERROR: Problem with fit (" << status << ")!" << std::endl;
   // Get parameters and return chi2 of fit
   ped  = fFitter->GetParameter(0);
   amp = fFitter->GetParameter(1);
   time = fFitter->GetParameter(2) / (double)fRefine;
   fcn = (HistogramFitFCN*)fFitter->GetMinuitFCN();
   std::vector<double> params;
   params.push_back(ped);
   params.push_back(amp);
   params.push_back(time);
   return (*fcn)(params);
 }
bool PulseTemplate::Converged ()
Definition at line 213 of file PulseTemplate.cpp.
Referenced by MakeTemplate::ProcessEntry().
{
   return (fConvergence <= fConvergenceLimit && fNPulses >= 2);
 }
double PulseTemplate::Correlation (TPulseIsland * pulse, double & ped, double & amp, double & time)
Definition at line 157 of file PulseTemplate.cpp.
{
   // Fits by finding the maximum correlation coefficient of template with pulse
   // Input--
   // pulse:    Pulse to fit
   // Output--
   // ped:      Pedestal of fit
   // amp:      Amplitude of fit
   return 0.;
 }
int PulseTemplate::GetNumberOfPulses ()
Definition at line 245 of file PulseTemplate.cpp.
References fNPulses.
Referenced by MakeTemplate::ProcessEntry().
{
   return fNPulses;
 }
void PulseTemplate::Print ()
Definition at line 228 of file PulseTemplate.cpp.
References fClockTick, fConvergence, fConvergenceLimit, fNBins, fNPulses, fNSigma, fRefine, fSum2X, fSumX, and fSumX2.
Referenced by MakeTemplate::ProcessEntry().
{
   std::cout << "Pulse Template Info:"
             << "\t" << "NP" << "\t" << "NS"
             << "\t" << "Ref" << "\t" << "NB"
             << "\t" << "T" << "\t" << "SX"
             << "\t" << "SX2" << "\t" << "S2X"
             << "\t" << "Conv" << "\t" << "ConLim"
             << std::endl;
   std::cout << "                    "
             << "\t" << fNPulses << "\t" << fNSigma
             << "\t" << fRefine << "\t" << fNBins
             << "\t" << fClockTick << "\t" << fSumX
             << "\t" << fSumX2 << "\t" << fSum2X
             << "\t" << fConvergence << "\t" << fConvergenceLimit
             << std::endl;
 }
void PulseTemplate::Save (TFile * outfile)
Definition at line 217 of file PulseTemplate.cpp.
References fTemplate.
Referenced by MakeTemplate::ProcessEntry().
{
   TDirectory* cwd = gDirectory;
   if (ofile == NULL || !ofile->IsOpen()) {
     std::cout << "ERROR: Cannot save template to file (file NULL or not open)!" << std::endl;
     return;
   }
   ofile->cd();
   fTemplate->Write();
   cwd->cd();
 }
Field Documentation
double PulseTemplate::fClockTick private
Definition at line 20 of file PulseTemplate.h.
Referenced by AddPulse(), and Print().
double PulseTemplate::fConvergence private
Definition at line 26 of file PulseTemplate.h.
Referenced by AddPulse(), and Print().
double PulseTemplate::fConvergenceLimit private
Definition at line 27 of file PulseTemplate.h.
Referenced by Print().
TFitterMinuit* PulseTemplate::fFitter private
Definition at line 14 of file PulseTemplate.h.
Referenced by Chi2Fit(), PulseTemplate(), and ~PulseTemplate().
int PulseTemplate::fNBins private
Definition at line 19 of file PulseTemplate.h.
Referenced by AddPulse(), and Print().
int PulseTemplate::fNPulses private
Definition at line 16 of file PulseTemplate.h.
Referenced by AddPulse(), GetNumberOfPulses(), and Print().
int PulseTemplate::fNSigma private
Definition at line 17 of file PulseTemplate.h.
Referenced by AddPulse(), and Print().
int PulseTemplate::fRefine private
Definition at line 18 of file PulseTemplate.h.
Referenced by AddPulse(), Chi2Fit(), and Print().
double PulseTemplate::fSum2X private
Definition at line 24 of file PulseTemplate.h.
Referenced by AddPulse(), and Print().
double PulseTemplate::fSumX private
Definition at line 22 of file PulseTemplate.h.
Referenced by AddPulse(), and Print().
double PulseTemplate::fSumX2 private
Definition at line 23 of file PulseTemplate.h.
Referenced by AddPulse(), and Print().
TH1D* PulseTemplate::fTemplate private
Definition at line 13 of file PulseTemplate.h.
Referenced by AddPulse(), Chi2Fit(), Save(), and ~PulseTemplate().
The documentation for this class was generated from the following files:
analyzer/rootana/src/TAP_generators/PulseTemplate.h
analyzer/rootana/src/TAP_generators/PulseTemplate.cpp