AlcapDAQ: IslandAmplitude Class Reference
IslandAmplitude Class Reference
[Modules]
A one line description of what your module does.
#include <IslandAmplitude.h>
Public Member Functions
IslandAmplitude (modules::options *opts)
Constructor description. If necessary, add a details tag like above.
~IslandAmplitude ()
Is anything done in the destructor?
int ProcessGenericEntry (TGlobalData *gData, const TSetupData *gSetup)
int Preprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
int Postprocess (TGlobalData *gData, const TSetupData *gSetup)
Method called by the main pre-process loop.
void SetAlias (const std::string &alias)
std::string GetAlias () const
const char * GetName () const
Get the name of this module as given to the constructor of the base class.
Protected Member Functions
bool Debug () const
TDirectory * GetDirectory () const
Get the TDirectory for this module.
TDirectory * GetDirectory (const std::string &name="")
Protected Attributes
TDirectory * dir
Private Types
typedef const std::map
< std::string, std::string > mapSS_t
typedef mapSS_t::const_iterator mapSS_iter
typedef std::map< std::string,
TH1F * > mapSH_t
typedef PulseIslandList::iterator PIL_iter
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, const TSetupData *gSetup)
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
virtual int BeforeFirstEntry (TGlobalData *gData, const TSetupData *setup)
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
virtual int AfterLastEntry (TGlobalData *gData, const TSetupData *setup)
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Private Attributes
mapSH_t fAmpHist
Don't forget to forget descirptions for each field...
mapSH_t fAmpHistNorm
TH1 * fAmpNorm
int fNProcessed
Detailed Description
A one line description of what your module does.
Author:
AuthorName
A longer, more descriptive block of text. Specifics like members and methods will be described later. You can add this to other groups instead of rootana_modules or in addition to rootana_modules by adding more of the ingroup tags.
Definition at line 23 of file IslandAmplitude.h.
Member Typedef Documentation
typedef std::map<std::string, TH1F*> IslandAmplitude::mapSH_t [private]
Definition at line 39 of file IslandAmplitude.h.
typedef mapSS_t::const_iterator IslandAmplitude::mapSS_iter [private]
Definition at line 38 of file IslandAmplitude.h.
typedef const std::map<std::string, std::string> IslandAmplitude::mapSS_t [private]
Definition at line 37 of file IslandAmplitude.h.
typedef PulseIslandList::iterator IslandAmplitude::PIL_iter [private]
Definition at line 40 of file IslandAmplitude.h.
Constructor & Destructor Documentation
IslandAmplitude::IslandAmplitude (modules::options * opts)
Constructor description. If necessary, add a details tag like above.
Parameters:
[in] opts Describe the options this module takes.
Definition at line 20 of file IslandAmplitude.cpp.
  : BaseModule("IslandAmplitude",opts)
{
  // Do something with opts here.
}
IslandAmplitude::~IslandAmplitude ()
Is anything done in the destructor?
Definition at line 28 of file IslandAmplitude.cpp.
{ }
Member Function Documentation
int IslandAmplitude::AfterLastEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needs to be done after each run? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::AfterLastEntry
[in] setup See BaseModule::AfterLastEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 140 of file IslandAmplitude.cpp.
References BaseModule::Debug(), fAmpHist, fAmpHistNorm, fAmpNorm, and fNProcessed.
{
  // Print extra info if we're debugging this module:
  if(Debug()){
     cout<<"-----IslandAmplitude::AfterLastEntry(): I'm debugging!"<<endl;
  }
  double run_norm = fAmpNorm->Integral(0,-1);
  for(mapSH_t::iterator it = fAmpHist.begin(); it != fAmpHist.end(); ++it)
    {
      TH1F* h = it->second;
      TObject* obj = h->Clone((std::string(h->GetName()) + "_RunNorm").c_str());
      TH1* hn = static_cast<TH1*>(obj);
      hn->SetTitle((std::string(h->GetTitle()) + " (run normalized)").c_str());
      hn->Scale(1.0/run_norm);
    }
  for(mapSH_t::iterator it = fAmpHistNorm.begin(); it != fAmpHistNorm.end(); ++it)
    it->second->Scale(1.0/fNProcessed);
  return 0;
}
int IslandAmplitude::BeforeFirstEntry (TGlobalData * gData, const TSetupData * setup) [private, virtual]
What needes to be done before each run? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::BeforeFirstEntry
[in] setup See BaseModule::BeforeFirstEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 35 of file IslandAmplitude.cpp.
References BaseModule::Debug(), fAmpHist, fAmpHistNorm, fAmpNorm, fNProcessed, TGlobalData::fPulseIslandToChannelMap, TSetupData::GetDetectorName(), and TSetupData::GetNBits().
  {
  // Print extra info if we're debugging this module:
  if(Debug()){
     cout<<"-----IslandAmplitude::BeforeFirstEntry(): I'm debugging!"<<endl;
  }
  fNProcessed = 0;
  StringPulseIslandMap& islands = data->fPulseIslandToChannelMap;
  for(StringPulseIslandMap::iterator mIt = islands.begin();
      mIt != islands.end(); ++mIt)
    {
      std::string bankname = mIt->first;
      std::string detname = setup->GetDetectorName(bankname);
      int max_adc_value = pow(2, setup->GetNBits(bankname));
      std::string histname = "hDQ_IslandAmplitudes_" + detname + "" + bankname;
      std::string histtitle = "Amplitude of Pulses in " + detname;
      TH1F* hDQ = new TH1F(histname.c_str(), histtitle.c_str(),
                         max_adc_value, 0, max_adc_value);
      hDQ->GetXaxis()->SetTitle("Amplitude (adc)");
      hDQ->GetYaxis()->SetTitle("Counts");
      fAmpHist[bankname] = hDQ;
      if(detname == "muSc")
        fAmpNorm=hDQ;
      histname += "_EvtNorm";
      histtitle +=" (event normalized)";
      hDQ = new TH1F(histname.c_str(), histtitle.c_str(),
                     500, 0, 2000);
      fAmpHistNorm[bankname] = hDQ;
    }
  TDirectory::CurrentDirectory()->cd("..");
  return 0;
}
bool BaseModule::Debug () const [inline, protected, inherited]
Check whether this module was asked to print extra debug information
Returns:
true if 'debug' was given in the modules file, false if not
Definition at line 71 of file BaseModule.h.
References BaseModule::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), ExportPulse::AddToExportList(), PulseCandidateFinder_InvestigateParameters::AfterLastEntry(), PlotTPI_PedestalAndNoise::AfterLastEntry(), PlotTDPs::AfterLastEntry(), PlotTDP_TDiff::AfterLastEntry(), IslandLength::AfterLastEntry(), AfterLastEntry(), MakeDetectorPulses::BeforeFirstEntry(), TemplateCreator::BeforeFirstEntry(), PulseCandidateFinder_InvestigateParameters::BeforeFirstEntry(), PlotTPI_PedestalAndNoise::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), IslandLength::BeforeFirstEntry(), BeforeFirstEntry(), PulseViewer::ConsiderDrawing(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeDetectorPulses::MakeGenerator(), ExportPulse::PlotTPI(), MakeDetectorPulses::ProcessEntry(), TemplateCreator::ProcessEntry(), PulseCandidateFinder_InvestigateParameters::ProcessEntry(), MakeAnalysedPulses::ProcessEntry(), PulseViewer::ProcessEntry(), PlotTDP_TDiff::ProcessEntry(), and TemplateCreator::StartTemplate().
{return fDebug;};
std::string BaseModule::GetAlias () const [inline, inherited]
Returns a string for the alias of this module. May be empty if no alias was given in the modules file.
Definition at line 63 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{return fAlias;};
TDirectory * BaseModule::GetDirectory (const std::string & name = "") [protected, inherited]
Definition at line 77 of file BaseModule.cpp.
References BaseModule::dir, and BaseModule::fDirectory.
{
  if(name.empty()) return fDirectory;
  TDirectory* dir=fDirectory->GetDirectory(name.c_str());
  if(dir) return dir;
  return fDirectory->mkdir(name.c_str());
}
TDirectory* BaseModule::GetDirectory () const [inline, protected, inherited]
Get the TDirectory for this module.
Definition at line 74 of file BaseModule.h.
References BaseModule::fDirectory.
Referenced by TemplateCreator::AfterLastEntry(), SavePulses::AfterLastEntry(), TemplateCreator::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), ExportPulse::ExportPulse(), and TemplateCreator::ProcessEntry().
{return fDirectory;}
const char* BaseModule::GetName () const [inline, inherited]
Get the name of this module as given to the constructor of the base class.
Definition at line 66 of file BaseModule.h.
References BaseModule::fName.
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Time::ProcessEntry(), PlotTAP_Amplitude::ProcessEntry(), and LoopSequence::Run().
{return fName.c_str();};
int BaseModule::Postprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through AfterLastEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 66 of file BaseModule.cpp.
References BaseModule::AfterLastEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Postprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = AfterLastEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int BaseModule::Preprocess (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main pre-process loop.
Does some simple work, then hooks into the derived class through BeforeFirstEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 55 of file BaseModule.cpp.
References BaseModule::BeforeFirstEntry(), and BaseModule::fDirectory.
Referenced by LoopSequence::Preprocess().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = BeforeFirstEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
int IslandAmplitude::ProcessEntry (TGlobalData * gData, const TSetupData * gSetup) [private, virtual]
What's calculated for every entry? Don't hesitate to repeat what was said in the class description.
Parameters:
[in] gData See BaseModule::ProcessEntry
[in] gSetup See BaseModule::ProcessEntry
Returns:
Non-zero to indicate a problem.
Implements BaseModule.
Definition at line 82 of file IslandAmplitude.cpp.
References banks, fAmpHist, fAmpHistNorm, fNProcessed, TGlobalData::fPulseIslandToChannelMap, TSetupData::GetDetectorName(), TSetupData::GetPedestal(), and TSetupData::GetTriggerPolarity().
{
  ++fNProcessed;
  StringPulseIslandMap& banks = data->fPulseIslandToChannelMap;
  int entry_norm =-1;
  for(StringPulseIslandMap::iterator mIter = banks.begin(); mIter != banks.end(); ++mIter)
    {
      std::string detname = setup->GetDetectorName(mIter->first);
      if(detname == "muSc")
        entry_norm = mIter->second.size();
    }
  for(StringPulseIslandMap::iterator mIter = banks.begin(); mIter != banks.end(); ++mIter)
    {
      std::string bankname = mIter->first;
      std::string detname = setup->GetDetectorName(bankname);
      PulseIslandList& pulses = mIter->second;
      TH1F* hist = fAmpHist.find(bankname)->second;
      TH1F* histnorm = fAmpHistNorm.find(bankname)->second;
      for(PIL_iter pIt = pulses.begin(); pIt != pulses.end(); ++pIt)
        {
          //
          double amp = 0;
          std::vector<int> samples = (*pIt)->GetSamples();
          std::vector<int>::iterator pos;
          int polarity = setup->GetTriggerPolarity(bankname);
          int pedestal = setup->GetPedestal(bankname);
          if(polarity == 1)
            pos = std::max_element(samples.begin(), samples.end());
          else if(polarity == -1)
            pos = std::min_element(samples.begin(), samples.end());
          amp = polarity * (*pos - pedestal);
          //
          hist->Fill(amp);
          if(entry_norm != 0)
            histnorm->Fill(amp, 1.0/entry_norm);
        }
    }
  return 0;
}
int BaseModule::ProcessGenericEntry (TGlobalData * gData, const TSetupData * gSetup) [inherited]
Method called by the main event loop for each entry in the input root tree. Does some simple work, then hooks into the derived class through ProcessEntry.
Returns:
0 on sucess and non-zero if a problem occurred
Definition at line 44 of file BaseModule.cpp.
References BaseModule::fDirectory, and BaseModule::ProcessEntry().
Referenced by LoopSequence::Process().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(fDirectory) fDirectory->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
void BaseModule::SetAlias (const std::string & alias) [inline, inherited]
Sets the alias for this module, which should be provided in the modules file
Definition at line 59 of file BaseModule.h.
References BaseModule::fAlias.
Referenced by BaseModule::BaseModule().
{fAlias=alias;};
Member Data Documentation
TDirectory* BaseModule::dir [protected, inherited]
Many modules use 'dir' still which was the old protected pointer to the modules directory. To prevent things being broken so soon, we keep this pointer available, but be warned that it will be removed shortly...
Definition at line 98 of file BaseModule.h.
Referenced by BaseModule::BaseModule(), FastSlowCompare::FastSlowCompare(), GeSpectrum::GeSpectrum(), BaseModule::GetDirectory(), MakeMuonEvents::MakeMuonEvents(), and PlotAmpVsTDiff::PlotAmpVsTDiff().
mapSH_t IslandAmplitude::fAmpHist [private]
Don't forget to forget descirptions for each field...
...and don't hesitate to include details.
Definition at line 74 of file IslandAmplitude.h.
Referenced by AfterLastEntry(), BeforeFirstEntry(), and ProcessEntry().
mapSH_t IslandAmplitude::fAmpHistNorm [private]
Definition at line 75 of file IslandAmplitude.h.
Referenced by AfterLastEntry(), BeforeFirstEntry(), and ProcessEntry().
TH1* IslandAmplitude::fAmpNorm [private]
Definition at line 77 of file IslandAmplitude.h.
Referenced by AfterLastEntry(), and BeforeFirstEntry().
int IslandAmplitude::fNProcessed [private]
Definition at line 79 of file IslandAmplitude.h.
Referenced by AfterLastEntry(), BeforeFirstEntry(), and ProcessEntry().
The documentation for this class was generated from the following files:
rootana/src/data_quality/IslandAmplitude.h
rootana/src/data_quality/IslandAmplitude.cpp