AlcapDAQ: analyzer/work/onlineana/client.cc File Reference
client.cc File Reference
Functions
if (!s->IsValid())
s Recv (ver, 100)
printf ("Online analyzer version: %s\n", ver)
printf ("Object listing ...\n")
sprintf (req,"LIST")
s Send (req)
s Recv (msg)
for (int i=0;i< names.GetEntries();++i)
Variables
char host_str [100] = "sc32"
int port = 9090
TSocket * s = new TSocket(host_str,port)
char ver [100]
char req [256]
TMessage * msg
TObjArray * names = (TObjArray*)msg->ReadObject(msg->GetClass())
Function Documentation
for ()
Definition at line 23 of file client.cc.
References i, and sprintf().
         {
                 TObjString *histname = names.At(i);
                 //printf("object %d: %s\n", i, histname->GetString().Data());
                 // Get the histogram
                 sprintf(req,"GET %s", histname->GetString().Data());
                 s->Send(req);
                 s->Recv(msg);
                 TH1 *hist = (TH1*) msg->ReadObject(msg->GetClass());
                 hist->Print();
                 hist->Draw();
         }
if (!s-> IsValid())
Definition at line 5 of file client.cc.
References printf().
         {
                 printf("Unable to establish connection to %s at port %d\n", host_str, port);
                 exit(1);
         }
printf ("Online analyzer version: %s\n" , ver)
Referenced by A3818UpgradeFromFile(), A3818UpgradeFromMem(), allPacketsReceived(), ana_begin_of_run(), ana_end_of_run(), analog2adc_offset(), analog2adc_trigger(), analyze_command_line(), analyzer_init(), binary_print(), caenV767_read1(), cam_init(), catastrophe(), catch_sigsegv(), check_arguments(), MqlArray< T >::checkSort(), cnaf_callback(), compress_bank(), compress_event(), cvUpgrade(), data_format_check(), DataConsistencyCheck(), decode_fadc(), decompress(), diag_print_impl(), directio_give_port(), directio_lock_port(), dt5720_init(), dt5720_pre_bor(), eb_user(), encode_caen(), encode_cmp_times(), epics_ca_set_label(), eraseFirmware(), event_display(), MyRun::Exec(), MyEvent::Exec(), MyGeomInit::Exec(), MyMaterialInit::Exec(), MyTracker::Exec(), MyRecTPC::Exec(), MyRecITS::Exec(), MyRecMUON::Exec(), MyRecPHOS::Exec(), MyRecRICH::Exec(), MyRecTRD::Exec(), MyRecGlobal::Exec(), expand_bank(), floppy_ttl_start_block(), for(), MqlArray< T >::fromBank(), frontend_early_init(), frontend_init(), ge_ln2_read(), get_input_event(), get_run_number(), get_status_code(), GetFWRel(), getObject(), getObjectFromFile(), getObjectFromSocket(), GetTree(), handFlush(), HelpMessage(), if(), TSetupData::Instance(), KeyInfo(), License(), load_fragment(), main(), Main_event_loop(), MDFile(), MDFilter(), MDPrint(), MDQ_DAQLivetime_eor(), MDQ_IslandRate_eor(), MDQ_RunTime_eor(), MDQ_TDCCheck_eor(), MDQ_Thresholds_eor(), MDString(), MDTestSuite(), MDTimeTrial(), MFastSlowCorrelator_init(), MMuPC1AnalysisMQL(), MMuSCAnalysisC_init(), MMuSCAnalysisMQL(), MOctalFADCProcessRaw(), module_event_caen(), MShortPulseTimes(), MTreeOutput_init(), MUnCompressRawData(), MVacuumHisto(), mvme_read(), mvme_write(), mvme_write_value(), MyModule::MyModule(), myprint_TPCstack_interval(), n2fadc_ndet_dump(), n2fadc_tpc_dump(), new_fadc_read(), nfadc_dump(), h1analysis::Notify(), openRootFile(), openSocket(), parport_init(), parport_poll_live(), parport_start_block(), pci_scan(), print_diag_output(), TOnlineFrame::print_msg(), print_TPCstack_interval(), PrintInterface(), PrintLocation(), PrintSetupData(), process_event(), SimpleHistograms::ProcessEntry(), TOctalFADCBankReader::ProcessEvent(), processIsland(), TOnlineFrame::ProcessMessage(), ProgramDigitizer(), read_separator_event(), read_temperature_probe(), receivePackets(), register_equipment(), replog(), rpv130_init(), rpv130_poll_live(), rpv130_PrintBusyStatus(), SaveHistogram(), scan_fragment(), setReg(), setupRegs(), show_mvme(), TAnalysedPulseMapWrapper::ShowInfo(), sis3600_bor1(), sis3600_read1(), source_booking(), source_scan(), source_unbooking(), start_cycle(), tr_prestart(), tr_start(), tr_stop(), update_odb(), UpdateDetectorBankNameMap(), usage(), Usage(), v1290_AcqModeRead(), v1290_DisableAllChannels(), v1290_MicroWrite(), v1290_ReadControlRegister(), v1290_ReadStatusRegister(), v1290_TriggerConfRead(), v1724_init(), v1724_pre_bor(), v1724_read(), v1724_readout(), vacuum_gauge_read(), verifyFlash(), write_log(), writeFlash(), WriteKey(), and xraycount().
printf ("Object listing ...\n")
s Recv (ver , 100)
s Recv (msg)
s Send (req)
sprintf (req , "LIST")
Referenced by caenV767_bor(), caenV767_pre_bor(), check_arguments(), close_buffers(), compress_event(), compress_event_skim(), TOnlineFrame::ConnectToServer(), decompress(), dl40x_bor(), dl40x_read(), dt5720_init(), dt5720_read(), eb_begin_of_run(), epics_ca_exception_handler(), epics_ca_init(), epics_ca_set_label(), expand_event(), for(), frontend_early_init(), get_run_number(), TemplateFactory< BaseModule, OptionsType >::GetArgumentName(), DataDir::GetCanonicalRun(), TOnlineFrame::GetHist(), getObjectFromSocket(), handFlush(), init_caen_histograms(), init_comp_histograms(), KeyInfo(), load_huffman(), lrs2249_bor(), main(), make_caen(), make_comp(), MCaenCompProcessRaw_init(), MDQ_DAQLivetime_eor(), MDQ_DigitizerOverflow_init(), MDQ_FADCBufferOverflow_init(), MDQ_FADCPacketLoss_init(), MDQ_IslandRate_eor(), MDQ_RunTime_eor(), MDQ_TDCCheck_eor(), MDQ_Thresholds_eor(), MMuPC1AnalysisC_init(), MMuSCAnalysisC(), MMuSCAnalysisC_init(), module_event_caen(), module_init(), module_init_sort_and_stitch(), MVacuumHisto(), new_fadc_read(), TOnlineFrame::OpenRootFile(), openSocket(), process_event(), SimpleHistograms::ProcessEntry(), processIsland(), TOnlineFrame::ProcessMessage(), register_equipment(), rpc_master_bor(), rpc_slave_bor(), rsp(), rsp_ndet0(), rsp_res_ana(), TOnlineFrame::runMacro(), s500_bor(), save_huffman(), SaveDigitalProbe(), SaveHistogram(), SaveWaveform(), TOnlineFrame::setServerPort(), setupRegs(), sis3600_bor(), source_scan(), tr_start(), UpdateDetectorBankNameMap(), v1724_init(), v1724_read(), validateModel(), vme_open(), and xraycount().
Variable Documentation
char host_str[100] = "sc32"
Definition at line 2 of file client.cc.
TMessage* msg
Definition at line 16 of file client.cc.
Referenced by TOnlineFrame::ConnectToServer(), epics_ca_event_handler(), epics_ca_init(), epics_ca_set(), TOnlineFrame::GetHist(), TOnlineFrame::GetHistTitles(), TOnlineFrame::OpenRootFile(), TOnlineFrame::runMacro(), ViewReadBltData(), and modules::parser::errors::unmatched_parenthesis::what().
TObjArray* names = (TObjArray*)msg->ReadObject(msg->GetClass())
Definition at line 22 of file client.cc.
Referenced by IDs::channel::GetDetectorEnum().
int port = 9090
Definition at line 3 of file client.cc.
Referenced by MMuSCAnalysisC().
char req[256]
Definition at line 15 of file client.cc.
Referenced by TOnlineFrame::GetHist().
TSocket* s = new TSocket(host_str,port)
Definition at line 4 of file client.cc.
Referenced by TOnlineFrame::ConnectToServer(), decode_bits(), decode_cmp_bits(), encode_bits(), encode_cmp_bits(), odb_connect(), odb_find_key(), odb_get_bool(), odb_get_boolarray(), odb_get_dword(), odb_get_int(), odb_get_word(), and xraycount().
char ver[100]
Definition at line 11 of file client.cc.