AlcapDAQ: analyzer/rootana/src/framework/CommandLine.cpp File Reference
CommandLine.cpp File Reference
#include <string.h>
#include "ModulesReader.h"
#include "ModulesFactory.h"
#include "CommandLine.h"
#include <stdio.h>
#include <string>
#include <stdlib.h>
#include <iostream>
Functions
void help_command_line (char *my_name)
bool isNumber (char *c)
int GetRunNumber (char *input_file)
int check_arguments (ARGUMENTS &arguments)
void PrintLocation ()
int analyze_command_line (int argc, char **argv, ARGUMENTS &arguments)
int load_config_file (const char *filename)
Variables
static char correction_file [300]
static char mod_file [300]
Function Documentation
int analyze_command_line (int argc, char ** argv, ARGUMENTS & arguments)
Definition at line 79 of file CommandLine.cpp.
References check_arguments(), ARGUMENTS::correction_file, help_command_line(), i, ARGUMENTS::infile, isNumber(), ARGUMENTS::mod_file, ARGUMENTS::outfile, printf(), ARGUMENTS::run, ARGUMENTS::start, and ARGUMENTS::stop.
Referenced by main().
{
   // Inialise the arguments to be consistently meaningless
   arguments.infile="";
   arguments.outfile="";
   arguments.correction_file="";
   arguments.start=0;
   arguments.stop=0;
   arguments.run=-1;
   // Now loop over all the arguments
   if(argc==1) {
       help_command_line(argv[0]);
       return 1;
   }
   if(strcmp(argv[1],"--help")==0){
       help_command_line(argv[0]);
       return 1;
   }
   for(int i=1; i<argc; /* incrementing of i done in the loop! */){
     if(argv[i][0] != '-'){
       printf("ERROR: Wrong argument %s\n",argv[i]);
       help_command_line(argv[0]); return 1;
     }
    if(strlen(&argv[i][1]) != 1){
      printf("ERROR: All options must be single characters, "
         "separated with a space and prefixed with a '-'\n");
       help_command_line(argv[0]); return 1;
    }
    switch(argv[i][1]){
    case 'm':
      if(i+1 < argc){
        arguments.mod_file = argv[i+1];
        i+=2;
      }
      else{
        printf("ERROR: No argument for module file specified\n");
        help_command_line(argv[0]); return 1;
      }
      break;
    case 'i':
      if(i+1 < argc){
        arguments.infile = argv[i+1];
        i+=2;
      }
      else{
        printf("ERROR: No argument for input file specified\n");
        help_command_line(argv[0]); return 1;
      }
      break;
    case 'o':
      if(i+1 < argc){
        arguments.outfile = argv[i+1];
        i+=2;
      }
      else{
        printf("ERROR: No argument for input file specified\n");
        help_command_line(argv[0]); return 1;
      }
      break;
         case 's':
      if(i+1 < argc){
        arguments.correction_file = argv[i+1];
        i+=2;
      }
      else{
        printf("ERROR: No argument for TSetupData correction file specified\n");
        help_command_line(argv[0]); return 1;
      }
      break;
    case 'n':
      if(i+1 < argc){
        if(isNumber(argv[i+1])){
          arguments.start = atoi(argv[i+1]);
          i+=2;
        }
        else{
          printf("ERROR: Argument %s for option -n is not a number\n",argv[i+1]);
          help_command_line(argv[0]); return 1;
        }
        if(i < argc && argv[i][0]!='-'){
          if(isNumber(argv[i])){
       arguments.stop = atoi(argv[i]);
       i+=1;
          }
          else{
       printf("ERROR: Argument %s for option -n is not a number\n", argv[i]);
       help_command_line(argv[0]); return 1;
          }
        }
      }
      else{
        printf("ERROR: No argument for number of processed events specified\n");
        help_command_line(argv[0]); return 1;
      }
      break;
    case 'r':
      if(i+1 < argc){
        if(isNumber(argv[i+1])){
          arguments.run = atoi(argv[i+1]);
          i+=2;
        }
        else{
          printf("ERROR: Argument %s for option -r is not a number\n",argv[i+1]);
          help_command_line(argv[0]); return 1;
        }
      }
      break;
    default:
      printf("ERROR: Argument %s not recognized\n",argv[i]);
      help_command_line(argv[0]); return 1;
    } // End switch block
   } // End for loop over all args
   // Everything looks ok, so we now check the arguments
   int ret = check_arguments( arguments);
   return ret;
 }
int check_arguments (ARGUMENTS & arguments)
Definition at line 42 of file CommandLine.cpp.
References ARGUMENTS::correction_file, correction_file, GetRunNumber(), ARGUMENTS::infile, ARGUMENTS::mod_file, mod_file, ARGUMENTS::outfile, printf(), ARGUMENTS::run, sprintf(), ARGUMENTS::start, and ARGUMENTS::stop.
Referenced by analyze_command_line().
{
   if(arguments.stop >0){
     if(arguments.stop <= arguments.start){
       printf("ERROR: Cannot process events from %d to %d because %d<=%d\n",
              arguments.start, arguments.stop, arguments.stop, arguments.start);
       return 1;
     }
   }
   if(strcmp(arguments.infile,"")==0){
     printf("ERROR: Empty input file name. Did you specify the -i option?\n");
     return 2;
   }
   if(strcmp(arguments.outfile,"")==0){
     printf("ERROR: Empty output file name. Did you specify the -o option?\n");
     return 3;
   }
   if(arguments.run==-1){
     // No run number has been set, obtain it from the filename
     arguments.run=GetRunNumber(arguments.infile);
   }
   if(strcmp(arguments.mod_file,"")==0){
     sprintf(mod_file,"MODULES");
     arguments.mod_file=mod_file;
   }
   if(strcmp(arguments.correction_file,"")==0){
     sprintf(correction_file,"wiremap_corrections/correct%d.dat",arguments.run);
     arguments.correction_file=correction_file;
   }
   return 0; //success
 }
int GetRunNumber (char * input_file)
Definition at line 31 of file CommandLine.cpp.
References run_number.
Referenced by check_arguments().
{
         std::string run_number=input_file;
         //remove the extension
         run_number=run_number.substr(0,run_number.find_last_of('.'));
         //find the last numbers
         run_number=run_number.substr(run_number.find_last_not_of("01234566789")+1);
         return atoi(run_number.c_str());
 }
void help_command_line (char * my_name)
Definition at line 10 of file CommandLine.cpp.
Referenced by analyze_command_line().
{
   fprintf (stderr,"\nusage: %s  [flags] \n\n",my_name);
   fprintf (stderr,"valid options are:\n");
   fprintf (stderr,"  -i <filename>\t\t Input root tree file.\n");
   fprintf (stderr,"  -o <filename>\t\t Output root tree file.\n");
   fprintf (stderr,"  -n <count>\t\t Analyze only <count> events.\n");
   fprintf (stderr,"     <first> <last>\t Analyze only events from "
            "<first> to <last>.\n");
   fprintf (stderr,"  -r <PSI run number>\t\t Run number specification for the shrubs.\n");
   fprintf (stderr,"  -m <modules file>\t\t Name of the MODULES file to be used.\n");
   fprintf (stderr,"\n");
   return;
 }
bool isNumber (char * c)
Definition at line 24 of file CommandLine.cpp.
References i.
Referenced by analyze_command_line().
                       {
   for(size_t i=0; i<strlen(c); i++){
     if(!isdigit(c[i])) return false;
   }
   return true;
 }
int load_config_file (const char * filename)
Definition at line 200 of file CommandLine.cpp.
References TemplateFactory< BaseModule, OptionsType >::createModule(), modules::options::DumpOptions(), modules::reader::GetModule(), modules::reader::GetNumModules(), modules::reader::GetOptions(), i, modules::factory::Instance(), modules::reader::PrintAllOptions(), and modules::reader::ReadFile().
{
     modules::reader modules_file;
     modules_file.ReadFile(filename);
     modules_file.PrintAllOptions();
     modules::factory* mgr = modules::factory::Instance();
     size_t num_modules=modules_file.GetNumModules();
     std::cout<<"number of modules requested: "<<num_modules<<std::endl;
     std::string name;
     modules::options* opts;
     modules::BaseModule *mods[num_modules];
     for(unsigned i=0;i<num_modules;i++){
             name = modules_file.GetModule(i);
             opts =  modules_file.GetOptions(i);
             std::cout<<"Creating module: "<<name<<std::endl;
             std::cout<<"With options:"<<std::endl;
             opts->DumpOptions("  ");
             mods[i] = mgr->createModule(name,opts);
     }
     return 0;
 }
void PrintLocation ()
Definition at line 74 of file CommandLine.cpp.
References count, and printf().
                     {
     static int count=0;
     printf("At location %d\n",count++);
 }
Variable Documentation
char correction_file[300] static
Definition at line 40 of file CommandLine.cpp.
Referenced by check_arguments().
char mod_file[300] static
Definition at line 41 of file CommandLine.cpp.
Referenced by check_arguments().