AlcapDAQ: CAEN/CAENVMELib/CAENVMELib-2.30.2/sample/console.h File Reference
console.h File Reference
Macros
#define ulong unsigned long
#define uint unsigned int
#define ushort unsigned short
#define uchar unsigned char
#define CR 0x0D /* carriage return */
#define BLANK 0x20 /* blank */
#define ESC 0x1B /* escape */
#define BSP 0x08 /* back space */
#define TERM_NOT_INIT FALSE
#define TERM_INIT TRUE
Functions
void con_init (void)
void con_end (void)
void write_log (char *)
int con_getch (void)
char con_kbhit (void)
int con_scanf (char *, void *)
int con_printf (char *,...)
void gotoxy (int, int)
int con_printf_xy (uint, uint, char *,...)
void clrscr (void)
void clear_line (uint)
void delay (int)
Macro Definition Documentation
#define BLANK 0x20 /* blank */
Definition at line 72 of file console.h.
#define BSP 0x08 /* back space */
Definition at line 74 of file console.h.
#define CR 0x0D /* carriage return */
Definition at line 71 of file console.h.
#define ESC 0x1B /* escape */
Definition at line 73 of file console.h.
#define TERM_INIT TRUE
Definition at line 78 of file console.h.
Referenced by con_init().
#define TERM_NOT_INIT FALSE
Definition at line 77 of file console.h.
#define uchar unsigned char
Definition at line 63 of file console.h.
Referenced by ViewReadBltData().
#define uint unsigned int
Definition at line 57 of file console.h.
#define ulong unsigned long
Definition at line 54 of file console.h.
#define ushort unsigned short
Definition at line 60 of file console.h.
Referenced by CaenVmeManual(), and ViewReadBltData().
Function Documentation
void clear_line (uint)
Definition at line 432 of file console.c.
References gotoxy(), and ocon.
Referenced by CaenVmeIrqCheck(), CaenVmeManual(), CaenVmeRead(), CaenVmeReadBlt(), CaenVmeWrite(), CaenVmeWriteBlt(), and ViewReadBltData().
 {
 #ifdef LINUX
   gotoxy(1, line);
   clrtoeol();
 #else
   COORD coordScreen;
   CONSOLE_SCREEN_BUFFER_INFO csbi; /* to get buffer info */
   BOOL bSuccess;
   DWORD cCharsWritten;
   DWORD dwLineSize; /* number of character cells in the line to clear */
   DWORD dwConSize; /* number of character cells in the current buffer */
   /* information about the specified console screen buffer*/
   bSuccess = GetConsoleScreenBufferInfo(ocon, &csbi);
   dwConSize = csbi.dwSize.X * csbi.dwSize.Y;
   dwLineSize = csbi.dwSize.X;
   coordScreen.X=0;
   coordScreen.Y=line-1;
   /* fill the entire screen with blanks */
   bSuccess = FillConsoleOutputCharacter(ocon, (TCHAR) ' ',
              dwLineSize, coordScreen, &cCharsWritten);
   coordScreen.X=0;
   coordScreen.Y=csbi.dwCursorPosition.Y;
   /* set the buffer's attributes */
   bSuccess = FillConsoleOutputAttribute(ocon, csbi.wAttributes,
              dwConSize, coordScreen, &cCharsWritten);
 #endif
 }
void clrscr (void)
Definition at line 388 of file console.c.
References ocon.
Referenced by CaenVmeManual(), con_init(), and ViewReadBltData().
 {
 #ifdef LINUX
   clear();
   move(0,0);
   refresh();
 #else
   COORD coordScreen = { 0, 0 };    /* home of the cursor */
   CONSOLE_SCREEN_BUFFER_INFO csbi; /* to get buffer info */
   BOOL bSuccess;
   DWORD cCharsWritten;
   DWORD dwConSize; /* number of character cells in the current buffer */
   /* information about the specified console screen buffer*/
   bSuccess = GetConsoleScreenBufferInfo(ocon, &csbi);
   dwConSize = csbi.dwSize.X * csbi.dwSize.Y;
   /* fill the entire screen with blanks */
   bSuccess = FillConsoleOutputCharacter(ocon, (TCHAR) ' ',
              dwConSize, coordScreen, &cCharsWritten);
   /* set the buffer's attributes */
   bSuccess = FillConsoleOutputAttribute(ocon, csbi.wAttributes,
              dwConSize, coordScreen, &cCharsWritten);
   /* put the cursor at (0, 0) */
   bSuccess = SetConsoleCursorPosition(ocon, coordScreen);
 #endif
 }
void con_end (void)
Definition at line 130 of file console.c.
Referenced by main().
 {
 #ifdef LINUX
   endwin();
 #endif
 }
int con_getch (void)
Definition at line 173 of file console.c.
References i.
Referenced by CaenVmeManual(), con_kbhit(), and ViewReadBltData().
 {
 #ifdef LINUX
   int i;
   while( ( i = getch() ) == ERR );
   return i;
 #else
   return _getch();
 #endif
 }
void con_init (void)
Definition at line 86 of file console.c.
References clrscr(), FALSE, icon, ocon, t_type, and TERM_INIT.
Referenced by main().
 {
 #ifdef LINUX
   initscr();
   cbreak();
   noecho();
   nodelay(stdscr, FALSE);
   curs_set(FALSE);
 #else
   COORD coordScreen = { 0, 0 };    /* home of the cursor */
   CONSOLE_SCREEN_BUFFER_INFO csbi; /* to get buffer info */
   BOOL bSuccess;
   DWORD cCharsWritten;
   DWORD dwConSize; /* number of character cells in the current buffer */
   ocon = GetStdHandle(STD_OUTPUT_HANDLE); /* handle for the standard output */
   icon = GetStdHandle(STD_INPUT_HANDLE);  /* handle for the standard input */
   t_type =TERM_INIT;
   clrscr();  /* clear the screen */
   /* information about the specified console screen buffer*/
   bSuccess = GetConsoleScreenBufferInfo(ocon, &csbi);
   dwConSize = csbi.dwSize.X * csbi.dwSize.Y;
   /* set the buffer's attributes */
   bSuccess = FillConsoleOutputAttribute(ocon, csbi.wAttributes,
              dwConSize, coordScreen, &cCharsWritten);
 #endif
 }
char con_kbhit (void)
Definition at line 201 of file console.c.
References c, con_getch(), FALSE, i, and TRUE.
Referenced by CaenVmeIrqCheck(), CaenVmeRead(), CaenVmeReadBlt(), CaenVmeWrite(), CaenVmeWriteBlt(), and con_scanf().
 {
 #ifdef LINUX
   int i, g;
   nodelay(stdscr, TRUE);
   i = ( ( g = getch() ) == ERR ? 0 : g );
   nodelay(stdscr, FALSE);
   return i;
 #else
   char c=0;
   if(kbhit())
     c = (char)con_getch();
   return(c);
 #endif
 }
int con_printf (char * , ...)
Definition at line 276 of file console.c.
References buf, and i.
Referenced by CaenVmeIrqCheck(), CaenVmeManual(), CaenVmeRead(), CaenVmeReadBlt(), CaenVmeWrite(), CaenVmeWriteBlt(), and ViewReadBltData().
 {
 #ifdef LINUX
   va_list marker;
   int     i;
   va_start(marker,fmt);
   i = vwprintw(stdscr,fmt,marker);
   va_end(marker);
   refresh();
   return i;
 #else
   va_list marker;
   char buf[256];
   va_start(marker, fmt);       /* Initialize variable arguments. */
   vsprintf(buf,fmt,marker);
   va_end(marker);              /* Reset variable arguments.      */
   fflush(stdout);              /* Empty the output buffer */
   return _cprintf(buf);
 #endif
 }
int con_printf_xy (uint , uint , char * , ...)
Definition at line 346 of file console.c.
References buf, gotoxy(), and i.
Referenced by CaenVmeIrqCheck(), CaenVmeManual(), CaenVmeRead(), CaenVmeReadBlt(), CaenVmeWrite(), CaenVmeWriteBlt(), and ViewReadBltData().
 {
 #ifdef LINUX
   va_list marker;
   int     i;
   move(ypos-1, xpos-1);
   refresh();
   va_start(marker,fmt);
   i = vwprintw(stdscr,fmt,marker);
   va_end(marker);
   refresh();
   return i;
 #else
   va_list marker;
   char buf[256];
   gotoxy(xpos, ypos);            /* Set the cursor position */
   va_start(marker, fmt);         /* Initialize variable arguments. */
   vsprintf(buf,fmt,marker);
   va_end(marker);                /* Reset variable arguments.      */
   fflush(stdout);                /* Empty the output buffer */
   return _cprintf(buf);
 #endif
 }
int con_scanf (char * , void *)
Definition at line 237 of file console.c.
References con_kbhit(), and i.
Referenced by CaenVmeIrqCheck(), CaenVmeManual(), CaenVmeWrite(), CaenVmeWriteBlt(), and ViewReadBltData().
 {
 #ifdef LINUX
   int i;
   echo();
   i = scanw(fmt,app);
   refresh();
   noecho();
   return i;
 #else
   int res;
   res = _cscanf(fmt, app) ;
   con_kbhit() ;                 /* Due to input reading problem */
   return res;
 #endif
 }
void delay (int)
Definition at line 480 of file console.c.
 {
 #ifdef LINUX
   usleep(msec*1000);
 #else
   Sleep(msec);
 #endif
 }
void gotoxy (int , int)
Definition at line 315 of file console.c.
References ocon.
Referenced by CaenVmeIrqCheck(), CaenVmeManual(), CaenVmeRead(), CaenVmeReadBlt(), CaenVmeWrite(), CaenVmeWriteBlt(), clear_line(), and con_printf_xy().
 {
 #ifdef LINUX
   move(y-1, x-1);
   refresh();
 #else
   COORD coord;
   coord.X = x-1;
   coord.Y = y-1;
   SetConsoleCursorPosition(ocon,coord);
 #endif
 }
void write_log (char *)
Definition at line 148 of file console.c.
References log_file, LOG_FILE_NAME, and printf().
 {
   if(log_file == NULL)
     {
     log_file = fopen(LOG_FILE_NAME,"w");   /* open log file */
     if(log_file == NULL)
       {
       printf("\n\nCan't open log file\n\n");
       exit(0);
       }
     }
   fprintf(log_file,"%s\n",msg);   /* write the error message in the log file */
   fflush(stdout);                 /* empty the output buffer */
 }