AlcapDAQ: CAEN/CAENVMELib/CAENVMELib-2.30.2/sample/console.c File Reference
CAEN/CAENVMELib/CAENVMELib-2.30.2/sample/console.c File Reference
#include "console.h"
#include <conio.h>
#include <stdio.h>
#include <stdarg.h>
#include <windows.h>
Functions
void con_init ()
void con_end ()
void write_log (char *msg)
int con_getch (void)
char con_kbhit ()
int con_scanf (char *fmt, void *app)
int con_printf (char *fmt,...)
void gotoxy (int x, int y)
int con_printf_xy (uint xpos, uint ypos, char *fmt,...)
void clrscr (void)
void clear_line (uint line)
void delay (int msec)
Variables
static HANDLE ocon
static HANDLE icon
FILE * log_file = NULL
char LOG_FILE_NAME [] = "LOG_FILE"
BOOL t_type = TERM_NOT_INIT
Function Documentation
void clear_line (uint line)
Definition at line 432 of file console.c.
References gotoxy(), and ocon.
Referenced by CaenVmeIrqCheck(), CaenVmeManual(), CaenVmeRead(), CaenVmeReadBlt(), CaenVmeWrite(), CaenVmeWriteBlt(), and ViewReadBltData().
{
#ifdef LINUX
  gotoxy(1, line);
  clrtoeol();
#else
  COORD coordScreen;
  CONSOLE_SCREEN_BUFFER_INFO csbi; /* to get buffer info */
  BOOL bSuccess;
  DWORD cCharsWritten;
  DWORD dwLineSize; /* number of character cells in the line to clear */
  DWORD dwConSize; /* number of character cells in the current buffer */
  /* information about the specified console screen buffer*/
  bSuccess = GetConsoleScreenBufferInfo(ocon, &csbi);
  dwConSize = csbi.dwSize.X * csbi.dwSize.Y;
  dwLineSize = csbi.dwSize.X;
  coordScreen.X=0;
  coordScreen.Y=line-1;
  /* fill the entire screen with blanks */
  bSuccess = FillConsoleOutputCharacter(ocon, (TCHAR) ' ',
             dwLineSize, coordScreen, &cCharsWritten);
  coordScreen.X=0;
  coordScreen.Y=csbi.dwCursorPosition.Y;
  /* set the buffer's attributes */
  bSuccess = FillConsoleOutputAttribute(ocon, csbi.wAttributes,
             dwConSize, coordScreen, &cCharsWritten);
#endif
}
void clrscr (void)
Definition at line 388 of file console.c.
References ocon.
Referenced by CaenVmeManual(), con_init(), ss_clear_screen(), and ViewReadBltData().
{
#ifdef LINUX
  clear();
  move(0,0);
  refresh();
#else
  COORD coordScreen = { 0, 0 };    /* home of the cursor */
  CONSOLE_SCREEN_BUFFER_INFO csbi; /* to get buffer info */
  BOOL bSuccess;
  DWORD cCharsWritten;
  DWORD dwConSize; /* number of character cells in the current buffer */
  /* information about the specified console screen buffer*/
  bSuccess = GetConsoleScreenBufferInfo(ocon, &csbi);
  dwConSize = csbi.dwSize.X * csbi.dwSize.Y;
  /* fill the entire screen with blanks */
  bSuccess = FillConsoleOutputCharacter(ocon, (TCHAR) ' ',
             dwConSize, coordScreen, &cCharsWritten);
  /* set the buffer's attributes */
  bSuccess = FillConsoleOutputAttribute(ocon, csbi.wAttributes,
             dwConSize, coordScreen, &cCharsWritten);
  /* put the cursor at (0, 0) */
  bSuccess = SetConsoleCursorPosition(ocon, coordScreen);
#endif
}
void con_end (void)
Definition at line 130 of file console.c.
Referenced by main().
{
#ifdef LINUX
  endwin();
#endif
}
int con_getch (void)
Definition at line 173 of file console.c.
References i.
Referenced by CaenVmeManual(), con_kbhit(), and ViewReadBltData().
{
#ifdef LINUX
  int i;
  while( ( i = getch() ) == ERR );
  return i;
#else
  return _getch();
#endif
}
void con_init (void)
Definition at line 86 of file console.c.
References clrscr(), FALSE, icon, ocon, t_type, and TERM_INIT.
Referenced by main().
{
#ifdef LINUX
  initscr();
  cbreak();
  noecho();
  nodelay(stdscr, FALSE);
  curs_set(FALSE);
#else
  COORD coordScreen = { 0, 0 };    /* home of the cursor */
  CONSOLE_SCREEN_BUFFER_INFO csbi; /* to get buffer info */
  BOOL bSuccess;
  DWORD cCharsWritten;
  DWORD dwConSize; /* number of character cells in the current buffer */
  ocon = GetStdHandle(STD_OUTPUT_HANDLE); /* handle for the standard output */
  icon = GetStdHandle(STD_INPUT_HANDLE);  /* handle for the standard input */
  t_type =TERM_INIT;
  clrscr();  /* clear the screen */
  /* information about the specified console screen buffer*/
  bSuccess = GetConsoleScreenBufferInfo(ocon, &csbi);
  dwConSize = csbi.dwSize.X * csbi.dwSize.Y;
  /* set the buffer's attributes */
  bSuccess = FillConsoleOutputAttribute(ocon, csbi.wAttributes,
             dwConSize, coordScreen, &cCharsWritten);
#endif
}
char con_kbhit (void)
Definition at line 201 of file console.c.
References c, con_getch(), FALSE, i, and TRUE.
Referenced by CaenVmeIrqCheck(), CaenVmeRead(), CaenVmeReadBlt(), CaenVmeWrite(), CaenVmeWriteBlt(), and con_scanf().
{
#ifdef LINUX
  int i, g;
  nodelay(stdscr, TRUE);
  i = ( ( g = getch() ) == ERR ? 0 : g );
  nodelay(stdscr, FALSE);
  return i;
#else
  char c=0;
  if(kbhit())
    c = (char)con_getch();
  return(c);
#endif
}
int con_printf (char * fmt, ...)
Definition at line 276 of file console.c.
References buf, and i.
Referenced by CaenVmeIrqCheck(), CaenVmeManual(), CaenVmeRead(), CaenVmeReadBlt(), CaenVmeWrite(), CaenVmeWriteBlt(), and ViewReadBltData().
{
#ifdef LINUX
  va_list marker;
  int     i;
  va_start(marker,fmt);
  i = vwprintw(stdscr,fmt,marker);
  va_end(marker);
  refresh();
  return i;
#else
  va_list marker;
  char buf[256];
  va_start(marker, fmt);       /* Initialize variable arguments. */
  vsprintf(buf,fmt,marker);
  va_end(marker);              /* Reset variable arguments.      */
  fflush(stdout);              /* Empty the output buffer */
  return _cprintf(buf);
#endif
}
int con_printf_xy (uint xpos, uint ypos, char * fmt, ...)
Definition at line 346 of file console.c.
References buf, gotoxy(), and i.
Referenced by CaenVmeIrqCheck(), CaenVmeManual(), CaenVmeRead(), CaenVmeReadBlt(), CaenVmeWrite(), CaenVmeWriteBlt(), and ViewReadBltData().
{
#ifdef LINUX
  va_list marker;
  int     i;
  move(ypos-1, xpos-1);
  refresh();
  va_start(marker,fmt);
  i = vwprintw(stdscr,fmt,marker);
  va_end(marker);
  refresh();
  return i;
#else
  va_list marker;
  char buf[256];
  gotoxy(xpos, ypos);            /* Set the cursor position */
  va_start(marker, fmt);         /* Initialize variable arguments. */
  vsprintf(buf,fmt,marker);
  va_end(marker);                /* Reset variable arguments.      */
  fflush(stdout);                /* Empty the output buffer */
  return _cprintf(buf);
#endif
}
int con_scanf (char * fmt, void * app)
Definition at line 237 of file console.c.
References con_kbhit(), and i.
Referenced by CaenVmeIrqCheck(), CaenVmeManual(), CaenVmeWrite(), CaenVmeWriteBlt(), and ViewReadBltData().
{
#ifdef LINUX
  int i;
  echo();
  i = scanw(fmt,app);
  refresh();
  noecho();
  return i;
#else
  int res;
  res = _cscanf(fmt, app) ;
  con_kbhit() ;                 /* Due to input reading problem */
  return res;
#endif
}
void delay (int msec)
Definition at line 480 of file console.c.
{
#ifdef LINUX
  usleep(msec*1000);
#else
  Sleep(msec);
#endif
}
void gotoxy (int x, int y)
Definition at line 315 of file console.c.
References ocon.
Referenced by CaenVmeIrqCheck(), CaenVmeManual(), CaenVmeRead(), CaenVmeReadBlt(), CaenVmeWrite(), CaenVmeWriteBlt(), clear_line(), con_printf_xy(), and ss_printf().
{
#ifdef LINUX
  move(y-1, x-1);
  refresh();
#else
  COORD coord;
  coord.X = x-1;
  coord.Y = y-1;
  SetConsoleCursorPosition(ocon,coord);
#endif
}
void write_log (char * msg)
Definition at line 148 of file console.c.
References log_file, and LOG_FILE_NAME.
{
  if(log_file == NULL)
    {
    log_file = fopen(LOG_FILE_NAME,"w");   /* open log file */
    if(log_file == NULL)
      {
      printf("\n\nCan't open log file\n\n");
      exit(0);
      }
    }
  fprintf(log_file,"%s\n",msg);   /* write the error message in the log file */
  fflush(stdout);                 /* empty the output buffer */
}
Variable Documentation
HANDLE icon [static]
Definition at line 59 of file console.c.
Referenced by con_init().
FILE* log_file = NULL
Definition at line 70 of file console.c.
Referenced by write_log().
char LOG_FILE_NAME[] = "LOG_FILE"
Definition at line 71 of file console.c.
Referenced by write_log().
HANDLE ocon [static]
Definition at line 59 of file console.c.
Referenced by clear_line(), clrscr(), con_init(), and gotoxy().
BOOL t_type = TERM_NOT_INIT
Definition at line 76 of file console.c.
Referenced by con_init().