AlcapDAQ: crate9/lrs2249.cpp File Reference
crate9/lrs2249.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <time.h>
#include "midas.h"
#include "crate.h"
#include "mcstd.h"
#include "odb_wrapper.h"
#include "camac_wrapper.h"
#include "diag.h"
Data Structures
struct lrs2249
Defines
#define MAX_LRS2249 8
#define N_CH_ADC 12
Functions
INT lrs2249_bor ()
INT lrs2249_read (char *pevent)
INT lrs2249_bor1 (struct lrs2249 *adc)
INT lrs2249_read1 (struct lrs2249 *adc, char *pevent)
Variables
struct readout_module lrs2249_module
struct lrs2249 lrs2249 [MAX_LRS2249]
Define Documentation
#define MAX_LRS2249 8
Definition at line 40 of file lrs2249.cpp.
#define N_CH_ADC 12
Definition at line 43 of file lrs2249.cpp.
Function Documentation
INT lrs2249_bor ()
Definition at line 71 of file lrs2249.cpp.
References bank_name, crate_number, diag_print(), enabled, lrs2249_bor1(), MAX_LRS2249, odb_find_key(), odb_get_bool(), lrs2249::odb_name, and SUCCESS.
{
  // Use the ODB to find any LRS2249 modules
  for(int j = 0; j < MAX_LRS2249; j++) {
    bool enabled = false;
    if (odb_find_key("/Equipment/Crate %d/Settings/LRS2249 %d", crate_number, j)) {
      diag_print(1, "ODB says LRS2249 %d is present, ", j);
      enabled =
        odb_get_bool("/Equipment/Crate %d/Settings/LRS2249 %d/enabled status",
            crate_number, j);
      if (enabled) {
        diag_print(1, "and is enabled.  Initializing...\n");
      } else {
        diag_print(1, "but is disabled.\n");
      }
    }
    lrs2249[j].enabled = enabled;
    // Set up the name of the MIDAS bank associated with the module
    sprintf(lrs2249[j].bank_name, "LAD%d", j);
    sprintf(lrs2249[j].odb_name, "LRS2249 %d", j);
    if(enabled) {
      lrs2249_bor1(&lrs2249[j]);
    }
  }
  return SUCCESS;
}
INT lrs2249_bor1 (struct lrs2249 * adc)
Definition at line 50 of file lrs2249.cpp.
References cam_init_once(), camc(), lrs2249::crate, crate_number, odb_get_int(), lrs2249::odb_name, lrs2249::slot, and SUCCESS.
{
  // Get the address of the module
  adc->crate = odb_get_int("/Equipment/Crate %d/Settings/%s/Crate",
                    crate_number, adc->odb_name);
  adc->slot = odb_get_int("/Equipment/Crate %d/Settings/%s/Slot",
                    crate_number, adc->odb_name);
  cam_init_once();
  camc(adc->crate, adc->slot, 0, 9);
  return SUCCESS;
}
INT lrs2249_read (char * pevent)
Definition at line 140 of file lrs2249.cpp.
References enabled, i, lrs2249_read1(), MAX_LRS2249, status, and SUCCESS.
{
  for(int i = 0; i < MAX_LRS2249; i++) {
    if(lrs2249[i].enabled) {
      int status = lrs2249_read1(&lrs2249[i], pevent);
       if(status != SUCCESS) {
         return status;
       }
    }
  }
  return SUCCESS;
}
INT lrs2249_read1 (struct lrs2249 * adc, char * pevent)
Definition at line 109 of file lrs2249.cpp.
References lrs2249::bank_name, camc(), camc_q(), cami(), lrs2249::crate, i, N_CH_ADC, lrs2249::slot, and SUCCESS.
{
  // Check whether the ADC has converted; if not, skip it
  INT q;
  camc_q(adc->crate, adc->slot, 0, 8, &q);
  if(!q) return SUCCESS;
  // Create the MIDAS bank
  WORD *pdata;
  bk_create(pevent, adc->bank_name, TID_WORD, &pdata);
  // Read ADC
  for(int i = 0; i < N_CH_ADC; i++) {
    cami(adc->crate, adc->slot, i, 0, pdata++);
  }
  // Clear ADC
  camc(adc->crate, adc->slot, 0, 9);
  // Close the bank
  bk_close(pevent, pdata);
  return SUCCESS;
}
Variable Documentation
struct lrs2249 lrs2249[MAX_LRS2249]
Definition at line 41 of file lrs2249.cpp.
struct readout_module lrs2249_module
Initial value:
 {
  NULL,
  NULL,
  NULL,
  lrs2249_bor,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  lrs2249_read,
}
Definition at line 19 of file lrs2249.cpp.