AlcapDAQ: crate6_CAEN_TDC/vmic_ttl.cpp File Reference
vmic_ttl.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/io.h>
#include "midas.h"
#include "crate.h"
#include "diag.h"
#include "odb_wrapper.h"
#include "vme.h"
Macros
#define VMIC_PORT12 0x12
#define VMIC_PORT34 0x10
#define VMIC_PORT56 0x16
#define VMIC_PORT78 0x14
#define VMIC_CSRU 0x20
#define VMIC_CSRL 0x21
#define VMIC_OUTPUT_1 0x00004000
#define VMIC_OUTPUT_2 0x00000800
#define VMIC_OUTPUT_3 0x00000100
#define VMIC_OUTPUT_4 0x00000030
#define VMIC_OUTPUT_5 0x00000004
#define VMIC_OUTPUT_6 0x00800000
#define VMIC_OUTPUT_7 0x00100000
#define VMIC_OUTPUT_8 0x00020000
#define VMIC_OUTPUT_EW1 VMIC_OUTPUT_1
#define VMIC_OUTPUT_EW2 VMIC_OUTPUT_2
#define VMIC_OUTPUT_LATCH_RESET VMIC_OUTPUT_3
#define VMIC_OUTPUT_CAENandCOMP VMIC_OUTPUT_4
#define VMIC_OUTPUT_CRATE4 VMIC_OUTPUT_5
#define VMIC_OUTPUT_SOFTSTOP VMIC_OUTPUT_6
#define VMIC_OUTPUT_CLOCK_RESET VMIC_OUTPUT_7
#define VMIC_OUTPUT_START1 (VMIC_OUTPUT_1 | VMIC_OUTPUT_4)
#define VMIC_OUTPUT_START2 (VMIC_OUTPUT_2 | VMIC_OUTPUT_4)
#define VMIC_INPUT_END_EVENT 62
#define VMIC_INPUT_BLOCK 59
Functions
INT vmic_ttl_init ()
INT vmic_ttl_start_block ()
INT vmic_ttl_stop_block ()
INT vmic_ttl_poll_live ()
INT cycle_ram ()
void vmic_set (DWORD new_value)
void vmic_turn_on (DWORD new_channels)
INT vmic_read_input (int channel)
Variables
struct readout_module vmic_ttl_module
static WORD vmic_vme_base
static struct vme_handle * vmic_handle
static WORD vmic_current_low
static WORD vmic_current_high
static BOOL vmic_enabled
static BOOL not_really_started
Macro Definition Documentation
#define VMIC_CSRL 0x21
Definition at line 40 of file vmic_ttl.cpp.
#define VMIC_CSRU 0x20
Definition at line 39 of file vmic_ttl.cpp.
Referenced by vmic_ttl_init().
#define VMIC_INPUT_BLOCK 59
Definition at line 71 of file vmic_ttl.cpp.
Referenced by vmic_ttl_start_block().
#define VMIC_INPUT_END_EVENT 62
Definition at line 70 of file vmic_ttl.cpp.
Referenced by vmic_ttl_poll_live(), and vmic_ttl_start_block().
#define VMIC_OUTPUT_1 0x00004000
Definition at line 45 of file vmic_ttl.cpp.
#define VMIC_OUTPUT_2 0x00000800
Definition at line 46 of file vmic_ttl.cpp.
#define VMIC_OUTPUT_3 0x00000100
Definition at line 47 of file vmic_ttl.cpp.
#define VMIC_OUTPUT_4 0x00000030
Definition at line 48 of file vmic_ttl.cpp.
#define VMIC_OUTPUT_5 0x00000004
Definition at line 49 of file vmic_ttl.cpp.
#define VMIC_OUTPUT_6 0x00800000
Definition at line 50 of file vmic_ttl.cpp.
#define VMIC_OUTPUT_7 0x00100000
Definition at line 51 of file vmic_ttl.cpp.
#define VMIC_OUTPUT_8 0x00020000
Definition at line 52 of file vmic_ttl.cpp.
#define VMIC_OUTPUT_CAENandCOMP VMIC_OUTPUT_4
Definition at line 60 of file vmic_ttl.cpp.
#define VMIC_OUTPUT_CLOCK_RESET VMIC_OUTPUT_7
Definition at line 63 of file vmic_ttl.cpp.
#define VMIC_OUTPUT_CRATE4 VMIC_OUTPUT_5
Definition at line 61 of file vmic_ttl.cpp.
Referenced by vmic_ttl_start_block().
#define VMIC_OUTPUT_EW1 VMIC_OUTPUT_1
Definition at line 57 of file vmic_ttl.cpp.
Referenced by vmic_ttl_start_block().
#define VMIC_OUTPUT_EW2 VMIC_OUTPUT_2
Definition at line 58 of file vmic_ttl.cpp.
Referenced by vmic_ttl_start_block().
#define VMIC_OUTPUT_LATCH_RESET VMIC_OUTPUT_3
Definition at line 59 of file vmic_ttl.cpp.
Referenced by vmic_ttl_start_block().
#define VMIC_OUTPUT_SOFTSTOP VMIC_OUTPUT_6
Definition at line 62 of file vmic_ttl.cpp.
Referenced by vmic_ttl_stop_block().
#define VMIC_OUTPUT_START1 (VMIC_OUTPUT_1 | VMIC_OUTPUT_4)
Definition at line 64 of file vmic_ttl.cpp.
Referenced by vmic_ttl_start_block().
#define VMIC_OUTPUT_START2 (VMIC_OUTPUT_2 | VMIC_OUTPUT_4)
Definition at line 65 of file vmic_ttl.cpp.
Referenced by vmic_ttl_start_block().
#define VMIC_PORT12 0x12
Definition at line 35 of file vmic_ttl.cpp.
Referenced by vmic_read_input(), and vmic_set().
#define VMIC_PORT34 0x10
Definition at line 36 of file vmic_ttl.cpp.
Referenced by vmic_read_input(), and vmic_set().
#define VMIC_PORT56 0x16
Definition at line 37 of file vmic_ttl.cpp.
Referenced by vmic_read_input().
#define VMIC_PORT78 0x14
Definition at line 38 of file vmic_ttl.cpp.
Referenced by vmic_read_input().
Function Documentation
INT cycle_ram ()
Definition at line 202 of file rpc_master.cpp.
 {
   return ((event_number + 1) % 2) + 1;
 }
INT vmic_read_input (int channel)
Definition at line 116 of file vmic_ttl.cpp.
References channel, status, vme_read_d16(), VMIC_PORT12, VMIC_PORT34, VMIC_PORT56, VMIC_PORT78, and vmic_vme_base.
Referenced by vmic_ttl_poll_live(), and vmic_ttl_start_block().
 {
   short status, mask;
   int reg;
   // decide which port and bit we're reading
   if ((channel >= 0) && (channel < 16)) {
     reg = VMIC_PORT56;
     mask = (1 << channel);
   } else if ((channel >= 16) && (channel < 32)) {
     reg = VMIC_PORT78;
     mask = (1 << (channel-16));
   } else if ((channel >= 32) && (channel < 48)) {
     reg = VMIC_PORT12;
     mask = (1 << (channel-32));
   } else if ((channel >= 48) && (channel < 64)) {
     reg = VMIC_PORT34;
     mask = (1 << (channel-48));
   }
   status = vme_read_d16(vmic_handle, vmic_vme_base | reg);
   if ((status & mask)==0) {
     return 0;
   } else {
     return 1;
   }
 }
void vmic_set (DWORD new_value)
Definition at line 90 of file vmic_ttl.cpp.
References vme_write_d16(), vmic_current_high, vmic_current_low, VMIC_PORT12, VMIC_PORT34, and vmic_vme_base.
Referenced by vmic_ttl_init(), vmic_ttl_poll_live(), vmic_ttl_start_block(), and vmic_turn_on().
 {
   WORD low = new_value & 0xffff;
   WORD high = (new_value >> 16) & 0xffff;
   if(low != vmic_current_low) {
     vme_write_d16(vmic_handle, vmic_vme_base | VMIC_PORT12, low);
     vmic_current_low = low;
   }
   if(high != vmic_current_high) {
     vme_write_d16(vmic_handle, vmic_vme_base | VMIC_PORT34, high);
     vmic_current_high = high;
   }
 }
INT vmic_ttl_init ()
Definition at line 150 of file vmic_ttl.cpp.
References crate_number, diag_print(), not_really_started, odb_find_key(), odb_get_word(), status, SUCCESS, vme_open(), vme_write_d16_checked(), VMEMAP_ASPACE_A16, VMEMAP_DWIDTH_16, VMEMAP_PRGDATAAM_DATA, VMEMAP_SUPUSERAM_SUPER, VMIC_CSRU, vmic_enabled, vmic_set(), and vmic_vme_base.
 {
   vmic_enabled =
     (odb_find_key("/Equipment/Crate %d/Settings/VMIC", crate_number) != 0);
   if(!vmic_enabled) {
     return SUCCESS;
   }
   diag_print(4,"vmic_ttl_init()\n");
   vmic_vme_base =
     odb_get_word("/Equipment/Crate %d/Settings/VMIC/vme address", crate_number);
   struct vme_mapping_ctrl mapping = {
           VMEMAP_DWIDTH_16,
           VMEMAP_ASPACE_A16,
           VMEMAP_SUPUSERAM_SUPER,
           VMEMAP_PRGDATAAM_DATA
   };
   vmic_handle = vme_open(vmic_vme_base, mapping, 0x100, 0);
   if(vmic_handle == NULL) {
     diag_print(0, "Unable to open handle for VMIC TTL I/O register\n");
     return FE_ERR_HW;
   }
   // Set control register: port 4 as input, all others as output
   int status =
     vme_write_d16_checked(vmic_handle, vmic_vme_base | VMIC_CSRU, 0xefff);
   if(status != SUCCESS) {
     diag_print(0, "Unable to write CSRU value to VMIC TTL I/O register\n");
     return FE_ERR_HW;
   }
   // Wait a moment to allow this setting to take effect
   ss_sleep(400);
   // Turn off all outputs
 /*
   vme_write_d16(vmic_handle, vmic_vme_base | VMIC_PORT12, 0);
   vmic_current_high = 0;
   vme_write_d16(vmic_handle, vmic_vme_base | VMIC_PORT34, 0);
   vmic_current_low = 0;
 */
   vmic_set(0);
   not_really_started = 0;
   return SUCCESS;
 }
INT vmic_ttl_poll_live ()
Definition at line 302 of file vmic_ttl.cpp.
References FE_END_BLOCK, not_really_started, SUCCESS, vmic_enabled, VMIC_INPUT_END_EVENT, vmic_read_input(), and vmic_set().
 {
   if(!vmic_enabled) {
     return SUCCESS;
   }
   //diag_print(4,"vmic_ttl_poll_live()\n");
   INT end_event = vmic_read_input(VMIC_INPUT_END_EVENT);
   if(end_event || not_really_started) {
     vmic_set(0);
     return FE_END_BLOCK;
   } else {
     return SUCCESS;
   }
 }
INT vmic_ttl_start_block ()
Definition at line 206 of file vmic_ttl.cpp.
References crate_is_participating(), cycle_ram(), diag_print(), not_really_started, SUCCESS, vmic_enabled, VMIC_INPUT_BLOCK, VMIC_INPUT_END_EVENT, VMIC_OUTPUT_CRATE4, VMIC_OUTPUT_EW1, VMIC_OUTPUT_EW2, VMIC_OUTPUT_LATCH_RESET, VMIC_OUTPUT_START1, VMIC_OUTPUT_START2, vmic_read_input(), and vmic_set().
 {
   if(!vmic_enabled) {
     return SUCCESS;
   }
   diag_print(4,"vmic_ttl_start_block()\n");
   // Is crate 4 going to be part of the cycle?
   DWORD maybe_crate4 = 0;
   if(crate_is_participating(4)) {
     maybe_crate4 = VMIC_OUTPUT_CRATE4;
   }
   // If there is already a block in progress, refuse to start another one.
   int block_input = vmic_read_input(VMIC_INPUT_BLOCK);
   if(block_input != 0) {
     diag_print(0, "BLOCK is high when it should be low!\n");
     vmic_set(0);
     ss_sleep(10);
     vmic_set(VMIC_OUTPUT_LATCH_RESET);
     ss_sleep(10);
     vmic_set(0);
     ss_sleep(100);
     not_really_started = 1;
     return FE_ERR_HW;
   }
   // First send a pulse on the latch reset line:
   vmic_set(0);
   vmic_set(VMIC_OUTPUT_LATCH_RESET | maybe_crate4);
 //  vmic_set(0 | maybe_crate4);
 #if 1
   // Now check whether the reset was effective--did it make the EndEvent
   // signal clear?
   if(vmic_read_input(VMIC_INPUT_END_EVENT) != 0) {
     diag_print(0, "END_EVENT signal not clearing with reset\n");
     not_really_started = 1;
     return FE_ERR_HW;
   }
 #endif
 #if 0
   // Try another reset...going straight into the start of the cycle
   // so that the compressor timing matches the CAENs.
   vmic_set(VMIC_OUTPUT_LATCH_RESET | maybe_crate4);
 #endif
   int ram = cycle_ram();
   diag_print(2, "Starting RAM %d cycle\n", ram);
   //
   // Finally, start the cycle.
   //
   if(ram == 1) {
     vmic_set(VMIC_OUTPUT_START1 | maybe_crate4);
     vmic_set(VMIC_OUTPUT_EW1 | maybe_crate4);
   } else {
     vmic_set(VMIC_OUTPUT_START2 | maybe_crate4);
     vmic_set(VMIC_OUTPUT_EW2 | maybe_crate4);
   }
   // We don't currently have any way of testing that the cycle started
   // correctly.  Perhaps something to think about adding...
   not_really_started = 0;
   return SUCCESS;
 }
INT vmic_ttl_stop_block ()
Definition at line 280 of file vmic_ttl.cpp.
References diag_print(), SUCCESS, vmic_enabled, VMIC_OUTPUT_SOFTSTOP, and vmic_turn_on().
 {
   if(!vmic_enabled) {
     return SUCCESS;
   }
   diag_print(4,"vmic_ttl_stop_block()\n");
   // set SOFTSTOP output
   vmic_turn_on(VMIC_OUTPUT_SOFTSTOP);
 }
void vmic_turn_on (DWORD new_channels)
Definition at line 109 of file vmic_ttl.cpp.
References vmic_current_high, vmic_current_low, and vmic_set().
Referenced by vmic_ttl_stop_block().
 {
   WORD low = vmic_current_low | (new_channels & 0xffff);
   WORD high = vmic_current_high | ((new_channels >> 16) & 0xffff);
   vmic_set((high << 16) | low);
 }
Variable Documentation
BOOL not_really_started static
Definition at line 83 of file vmic_ttl.cpp.
Referenced by vmic_ttl_init(), vmic_ttl_poll_live(), and vmic_ttl_start_block().
WORD vmic_current_high static
Definition at line 79 of file vmic_ttl.cpp.
Referenced by vmic_set(), and vmic_turn_on().
WORD vmic_current_low static
Definition at line 78 of file vmic_ttl.cpp.
Referenced by vmic_set(), and vmic_turn_on().
BOOL vmic_enabled static
Definition at line 81 of file vmic_ttl.cpp.
Referenced by vmic_ttl_init(), vmic_ttl_poll_live(), vmic_ttl_start_block(), and vmic_ttl_stop_block().
struct vme_handle* vmic_handle static
Definition at line 77 of file vmic_ttl.cpp.
struct readout_module vmic_ttl_module
Initial value:
= {
  vmic_ttl_init,
  NULL,
  NULL,
  NULL,
  NULL,
  vmic_ttl_poll_live,
  NULL,
  vmic_ttl_start_block,
  vmic_ttl_stop_block,
  NULL,
}
Definition at line 19 of file vmic_ttl.cpp.
WORD vmic_vme_base static
Definition at line 76 of file vmic_ttl.cpp.
Referenced by vmic_read_input(), vmic_set(), and vmic_ttl_init().