AlcapDAQ: crate3/diag.h File Reference
crate3/diag.h File Reference
#include <stdarg.h>
Functions
void diag_print_setup ()
void diag_print_impl (int level, char *format, va_list ap)
void diag_print (int level, char *format,...)
Variables
int diag_print_threshold
int diag_cm_msg_threshold
Function Documentation
void diag_print (int level, char * format, ...) [inline]
Definition at line 9 of file diag.h.
References diag_cm_msg_threshold, diag_print_impl(), diag_print_setup(), and diag_print_threshold.
Referenced by begin_of_run(), caenV767_bor(), caenV767_bor1(), caenV767_poll1(), caenV767_pre_bor(), caenV767_read1(), dl401_bor1(), dl401_read(), dl401_setPedestals(), dl403_init(), dl403_setClockCycle(), dl403_setClockRate(), dl40x_bor(), end_of_run(), floppy_ttl_init(), lrs2249_bor(), pre_begin_of_run(), read_periodic_event(), read_trigger_event(), rpc_end_of_cycle(), rpc_master_poll_live(), rpc_master_pre_bor(), rpc_master_read(), rpc_ready_for_cycle(), rpc_request_stop(), rpc_slave_bor(), rpc_slave_poll_live(), s500_bor(), send_ready_for_cycle(), sis3600_bor(), sis3600_bor1(), sis3600_fifo_read(), sis3600_poll1(), start_cycle(), vme_open(), vmic_ttl_init(), vmic_ttl_start_block(), and vmic_ttl_stop_block().
{
  if(diag_print_threshold < 0) {
    diag_print_setup();
  }
  // Return immediately if we don't even need to format the message.
  if(level > diag_print_threshold && level > diag_cm_msg_threshold) {
    return;
  }
  va_list argp;
  va_start(argp, format);
  diag_print_impl(level, format, argp);
  va_end(argp);
}
void diag_print_impl (int level, char * format, va_list ap)
Definition at line 35 of file diag.cpp.
{
  // Format the message.
  char buffer[4096];
  vsnprintf(buffer, sizeof(buffer), format, argp);
  // Print on standard output
  // if (level <= diag_print_threshold) {
    printf("%s", buffer);
    fflush(stdout);
  // }
  // Send to cm_msg
  if(level <= diag_cm_msg_threshold) {
    // Be careful to avoid sending too many messages...let's limit ourselves
    // to 10 per second.
    time_t now = time(NULL);
    if(last_message_time == now) {
      num_messages_this_second++;
      if(num_messages_this_second < 1) {
        cm_msg(MINFO, frontend_name, buffer);
      }
    } else {
      num_messages_this_second = 0;
    }
    last_message_time = now;
  }
}
void diag_print_setup ()
Definition at line 22 of file diag.cpp.
{
  // Read the diagnostic print thresholds from the ODB
  diag_print_threshold =
     odb_get_int("/Equipment/Crate %d/Settings/Diagnostic Print Level", crate_number);
  diag_cm_msg_threshold =
     odb_get_int("/Equipment/Crate %d/Settings/Operator Message Level", crate_number);
}
Variable Documentation
int diag_cm_msg_threshold
Definition at line 11 of file diag.cpp.
int diag_print_threshold
Definition at line 10 of file diag.cpp.