AlcapDAQ: crate3/crate.cpp File Reference
crate3/crate.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/time.h>
#include <sched.h>
#include "midas.h"
#include "msystem.h"
#include "odb_wrapper.h"
#include "crate.h"
#include "diag.h"
Defines
#define MAX_DATA_SIZE 262144
Functions
INT frontend_early_init ()
INT frontend_init ()
INT frontend_exit ()
INT pre_begin_of_run (INT run_number, char *error)
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
INT frontend_loop ()
INT poll_event (INT source, INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
INT read_trigger_event (char *pevent, INT off)
INT read_periodic_event (char *pevent, INT off)
void start_cycle ()
INT consider_start ()
void stop_cycle ()
void print_diag_output (char *pevent)
Variables
int run_state
int frontend_index
BOOL interrupts_enabled = FALSE
void(* interrupt_handler)() = NULL
char * frontend_name
char * frontend_file_name = __FILE__
BOOL frontend_call_loop = TRUE
INT display_period = 0
INT max_event_size = MAX_DATA_SIZE * sizeof(DWORD)
INT max_event_size_frag = 0
INT event_buffer_size = 2 * MAX_DATA_SIZE * sizeof(DWORD)
EQUIPMENT equipment []
struct readout_module rpc_master_module
struct readout_module rpc_slave_module
struct readout_module parport_module
struct readout_module * trigger_modules []
int num_trigger_modules = sizeof(trigger_modules)/sizeof(trigger_modules[0])
struct timeval readout_finished_time
struct readout_module s500_module
struct readout_module * periodic_modules []
int num_periodic_modules = sizeof(periodic_modules)/sizeof(periodic_modules[0])
int cycle_active = 0
bool event_avail = false
bool between_runs = true
int crate_number = -1
Define Documentation
#define MAX_DATA_SIZE 262144
Definition at line 46 of file crate.cpp.
Function Documentation
INT begin_of_run (INT run_number, char * error)
Definition at line 295 of file crate.cpp.
Referenced by tr_start(), and tr_start2().
{
  diag_print(1, "*** Begin of run %d ***\n", run_number);
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).bor != NULL) {
      int status = (*trigger_modules[i]).bor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  for(int i = 0; i < num_periodic_modules; i++) {
    if((*periodic_modules[i]).bor != NULL) {
      int status = (*periodic_modules[i]).bor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  cycle_active = 0;
  event_avail = false;
  between_runs = false;
  return SUCCESS;
}
INT consider_start ()
Definition at line 402 of file crate.cpp.
References FE_NEED_START, i, num_trigger_modules, start_cycle(), status, and SUCCESS.
Referenced by frontend_loop(), and read_trigger_event().
{
    for(int i = 0; i < num_trigger_modules; i++) {
      if((*trigger_modules[i]).poll_dead != NULL) {
        int status = (*trigger_modules[i]).poll_dead();
        if(status == FE_NEED_START && !event_avail) {
          start_cycle();
        } else if(status != SUCCESS) {
          return status;
        }
      }
    }
}
INT end_of_run (INT run_number, char * error)
Definition at line 330 of file crate.cpp.
Referenced by tr_prestop(), and tr_stop().
{
  diag_print(1, "*** End of run %d ***\n", run_number);
  between_runs = true;
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).eor != NULL) {
      int status = (*trigger_modules[i]).eor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  for(int i = 0; i < num_periodic_modules; i++) {
    if((*periodic_modules[i]).eor != NULL) {
      int status = (*periodic_modules[i]).eor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  return SUCCESS;
}
INT frontend_early_init (void)
Definition at line 145 of file crate.cpp.
Referenced by main().
{
  // Determine our crate ID by comparing against a list of hostnames
  printf("Entering frontend_early_init ... \n");
  //char *hostnames[] = {"fe1", "fe2", "fe3", "turtle", "fe5", "fe6"};
  //char *hostnames[] = {"fe1", "fe2", "daq2.MuSIC", "fe4", "fe5", "fe6", "fe7"};
  //int crate_numbers[] = {1, 2, 3, 4, 5, 6, 9};
  //char *hostnames[] = {"daq2.MuSIC"};
  //int crate_numbers[] = {3};
  //BOOL crate_has_periodic[] = {FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE};
  //int num_hostnames = sizeof(hostnames)/sizeof(char *);
  //char my_hostname[256];
  //gethostname(my_hostname, sizeof(my_hostname));
#if 0
  BOOL has_periodic = FALSE;
  for(int i = 0; i < num_hostnames; i++) {
    if(!strcmp(my_hostname, hostnames[i])) {
      crate_number = crate_numbers[i];
      has_periodic = crate_has_periodic[i];
    }
  }
#endif
  crate_number = 3;
  BOOL has_periodic = FALSE;
  printf("Hostname and crate cumber defined, crate number = %d  ... \n",crate_number);
  if(crate_number > 0) {
    frontend_name = new char[32];
    strcpy(frontend_name, "Crate ");
#if 0
    sprintf(equipment[0].name, "Crate %d", crate_number);
    sprintf(equipment[0].info.buffer, "BUF%d", crate_number);
    equipment[0].info.event_id = 1000 + crate_number;
#endif
    frontend_index = crate_number;
    printf("Crate number = %d\n",crate_number);
    if(has_periodic) {
      sprintf(equipment[1].name, "Periodic %d", crate_number);
      equipment[1].info.event_id = 2000 + crate_number;
    } else {
      sprintf(equipment[1].name, "");
    }
  }
  printf("Frontend early init returns success \n");
  return SUCCESS;
}
INT frontend_exit (void)
Definition at line 244 of file crate.cpp.
Referenced by main().
{
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).exit != NULL) {
      (*trigger_modules[i]).exit();
    }
  }
  for(int i = 0; i < num_periodic_modules; i++) {
    if((*periodic_modules[i]).exit != NULL) {
      (*periodic_modules[i]).exit();
    }
  }
  return SUCCESS;
}
INT frontend_init (void)
Definition at line 207 of file crate.cpp.
Referenced by main().
{
  printf("Entering frontend_init() ... \n");
  INT run_state = odb_get_int("/Runinfo/State");
  if (run_state != STATE_STOPPED) {
    cm_msg(MERROR, "Crate",
            "Run must be stopped before starting crate program.");
    return FE_ERR_HW;
  }
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).init != NULL) {
      int status = (*trigger_modules[i]).init();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  for(int i = 0; i < num_periodic_modules; i++) {
    if((*periodic_modules[i]).init != NULL) {
      int status = (*periodic_modules[i]).init();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  return SUCCESS;
}
INT frontend_loop (void)
Definition at line 435 of file crate.cpp.
Referenced by poll_event(), and scheduler().
{
  // If we're going to be pre-empted, get it over with during livetime
  // rather than deadtime.
  if (cycle_active || run_state != STATE_RUNNING || between_runs == TRUE) {
    dm_area_flush();
    sched_yield();
  }
  // Exit immediately if no run in progress
  if (run_state != STATE_RUNNING || between_runs == TRUE) {
    return SUCCESS;
  }
  // Call appropriate poll functions, depending on whether we're live or dead
  //printf("fe loop: cycle_active %i\n",cycle_active);
  if (cycle_active) {
    for(int i = 0; i < num_trigger_modules; i++) {
      if((*trigger_modules[i]).poll_live != NULL) {
        // There are conditions that can lead to changes in run state between
        // modules...
        if (run_state != STATE_RUNNING || between_runs == TRUE) {
          return SUCCESS;
        }
        int status = (*trigger_modules[i]).poll_live();
        if(status == FE_END_BLOCK) {
          cycle_active = 0;
          event_avail = true;
        } else if(status == FE_NEED_STOP) {
          stop_cycle();
        } else if(status != SUCCESS) {
          return status;
        }
      }
    }
  } else {
    consider_start();
  }
  return SUCCESS;
}
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Definition at line 505 of file crate.cpp.
Referenced by interrupt_enable(), main(), and register_equipment().
{
    switch (cmd) {
    case CMD_INTERRUPT_ENABLE:
        interrupts_enabled = TRUE;
        break;
    case CMD_INTERRUPT_DISABLE:
        interrupts_enabled = FALSE;
        break;
    case CMD_INTERRUPT_ATTACH:
        interrupt_handler = (void (*)(void)) adr;
        break;
    case CMD_INTERRUPT_DETACH:
        interrupts_enabled = FALSE;
        interrupt_handler = NULL;
        break;
    }
    return SUCCESS;
}
INT pause_run (INT run_number, char * error)
Definition at line 362 of file crate.cpp.
{
    return SUCCESS;
}
INT poll_event (INT source, INT count, BOOL test)
Definition at line 486 of file crate.cpp.
Referenced by register_equipment(), and scheduler().
{
    INT retval = false;
    if(!test) {
      count = 1;
    }
    for (int i = 0; i < count; i++) {
        frontend_loop();
        if(event_avail) {
          retval = true;
        }
    }
    return retval;
}
INT pre_begin_of_run (INT run_number, char * error)
Definition at line 264 of file crate.cpp.
Referenced by tr_prestart().
{
  diag_print(1, "*** Before begin of run %d ***\n", run_number);
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).pre_bor != NULL) {
      int status = (*trigger_modules[i]).pre_bor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  for(int i = 0; i < num_periodic_modules; i++) {
    if((*periodic_modules[i]).pre_bor != NULL) {
      int status = (*periodic_modules[i]).pre_bor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  return SUCCESS;
}
void print_diag_output (char * pevent)
Definition at line 525 of file crate.cpp.
References bk_iterate32(), i, MIN, BANK32::name, serial_number, and size.
Referenced by read_periodic_event(), and read_trigger_event().
{
  printf("--------\n");
  printf("Event number: %d\n", (((EVENT_HEADER *)pevent)-1)->serial_number);
  BANK32 *pbk = NULL;
  do {
    DWORD *pdata;
    int size = bk_iterate32(pevent, &pbk, &pdata);
    if(pbk != NULL) {
      printf("%c%c%c%c\t%d\t\t", pbk->name[0], pbk->name[1], pbk->name[2],
        pbk->name[3], size);
      for(int i = 0; i < MIN(4, size/4); i++) {
         printf("0x%08x ", pdata[i]);
      }
      printf("\n");
    }
  } while(pbk != NULL);
  printf("--------\n");
}
INT read_periodic_event (char * pevent, INT off)
Definition at line 593 of file crate.cpp.
References bk_init32(), bk_size(), diag_print(), diag_print_threshold, i, print_diag_output(), read, status, and SUCCESS.
{
  diag_print(2, "Periodic event readout:\n");
  // Initialize the event
  bk_init32(pevent);
  // Ask periodic_modules to read out
  for(int i = 0; i < num_periodic_modules; i++) {
     if((*periodic_modules[i]).read != NULL) {
       int status = (*periodic_modules[i]).read(pevent);
       if(status != SUCCESS) {
         return status;
       }
    }
  }
  // Print a diagnostic
  if(diag_print_threshold >= 2) {
    print_diag_output(pevent);
  }
  return bk_size(pevent);
}
INT read_trigger_event (char * pevent, INT off)
Definition at line 549 of file crate.cpp.
References bk_init32(), bk_size(), consider_start(), diag_print(), diag_print_threshold, i, num_trigger_modules, print_diag_output(), read, readout_finished_time, run_state, STATE_RUNNING, status, and SUCCESS.
{
  diag_print(2, "Event has ended.  Executing read_trigger_event.\n");
  // Remember that we have read out this event
  event_avail = false;
  // Initialize the event
  bk_init32(pevent);
  // Protection against readout after run has ended.
  if (run_state != STATE_RUNNING) {
    diag_print(1, "Readout after end of run!!!\n");
    return bk_size(pevent);
  }
  struct timeval readout_start_time;
  gettimeofday(&readout_start_time, NULL);
  // Ask trigger_modules to read out
  for(int i = 0; i < num_trigger_modules; i++) {
     if((*trigger_modules[i]).read != NULL) {
       int status = (*trigger_modules[i]).read(pevent);
       if(status != SUCCESS) {
         return status;
       }
    }
  }
  gettimeofday(&readout_finished_time, NULL);
  diag_print(2, "Spent %f microseconds for readout.\n",
    (readout_finished_time.tv_sec-readout_start_time.tv_sec)*1e6 +
      (readout_finished_time.tv_usec-readout_start_time.tv_usec));
  // Consider starting up the next block
  consider_start();
  // Print a diagnostic
  if(diag_print_threshold >= 2) {
    print_diag_output(pevent);
  }
  return bk_size(pevent);
}
INT resume_run (INT run_number, char * error)
Definition at line 371 of file crate.cpp.
{
    return SUCCESS;
}
void start_cycle ()
Definition at line 380 of file crate.cpp.
References diag_print(), i, num_trigger_modules, and readout_finished_time.
Referenced by consider_start(), and start_cycle().
{
  printf("starting new cycle in crate.cpp\n");
  struct timeval restart_time;
  gettimeofday(&restart_time, NULL);
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).start_cycle != NULL) {
      (*trigger_modules[i]).start_cycle();
    }
  }
  diag_print(2, "Waited %f microseconds for restart.\n",
    (restart_time.tv_sec-readout_finished_time.tv_sec)*1e6 +
      (restart_time.tv_usec-readout_finished_time.tv_usec));
  cycle_active = 1;
}
void stop_cycle ()
Definition at line 421 of file crate.cpp.
References i, and num_trigger_modules.
Referenced by frontend_loop(), and stop_cycle().
{
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).stop_cycle != NULL) {
      (*trigger_modules[i]).stop_cycle();
    }
  }
}
Variable Documentation
bool between_runs = true
Definition at line 137 of file crate.cpp.
int crate_number = -1
Definition at line 139 of file crate.cpp.
Referenced by caenV767_bor(), caenV767_bor1(), caenV767_pre_bor(), diag_print_setup(), dl401_bor1(), dl403_init(), dl40x_bor(), dt5720_init(), lrs2249_bor(), lrs2249_bor1(), main(), rpc_master_bor(), rpc_master_eor(), rpc_master_init(), rpc_master_poll_dead(), rpc_master_read(), rpc_ready_for_cycle(), rpc_request_stop(), rpc_slave_bor(), rpc_slave_stop_block(), s500_bor(), s500_bor1(), send_ready_for_cycle(), setupRegs(), sis3600_bor(), sis3600_bor1(), v1724_init(), and vmic_ttl_init().
int cycle_active = 0
Definition at line 134 of file crate.cpp.
INT display_period = 0
Definition at line 43 of file crate.cpp.
Referenced by main(), manual_trigger(), register_equipment(), scheduler(), tr_pause(), tr_prepause(), tr_prestop(), tr_resume(), tr_start(), and tr_stop().
EQUIPMENT equipment[]
Definition at line 72 of file crate.cpp.
bool event_avail = false
Definition at line 135 of file crate.cpp.
INT event_buffer_size = 2 * MAX_DATA_SIZE * sizeof(DWORD)
Definition at line 53 of file crate.cpp.
Referenced by main().
BOOL frontend_call_loop = TRUE
Definition at line 39 of file crate.cpp.
Referenced by scheduler().
char * frontend_file_name = __FILE__
Definition at line 36 of file crate.cpp.
Referenced by register_equipment().
int frontend_index
Definition at line 314 of file mfe_mucap.c.
Referenced by frontend_early_init(), get_frontend_index(), main(), and register_equipment().
char* frontend_name
Definition at line 33 of file crate.cpp.
Referenced by diag_print_impl(), display(), dl403_init(), frontend_early_init(), main(), read_separator_event(), and register_equipment().
void(* interrupt_handler)() = NULL
Referenced by interrupt_configure().
BOOL interrupts_enabled = FALSE
Definition at line 29 of file crate.cpp.
Referenced by interrupt_configure().
INT max_event_size = MAX_DATA_SIZE * sizeof(DWORD)
Definition at line 47 of file crate.cpp.
Referenced by handFlush(), load_fragment(), main(), scheduler(), send_event(), source_booking(), and source_scan().
INT max_event_size_frag = 0
Definition at line 50 of file crate.cpp.
Referenced by main(), and send_event().
int num_periodic_modules = sizeof(periodic_modules)/sizeof(periodic_modules[0])
Definition at line 132 of file crate.cpp.
int num_trigger_modules = sizeof(trigger_modules)/sizeof(trigger_modules[0])
Definition at line 120 of file crate.cpp.
Referenced by begin_of_run(), consider_start(), end_of_run(), frontend_exit(), frontend_init(), frontend_loop(), pre_begin_of_run(), read_trigger_event(), start_cycle(), and stop_cycle().
struct readout_module parport_module
Definition at line 35 of file parport_module.cpp.
struct readout_module* periodic_modules[]
Initial value:
 {
}
Definition at line 129 of file crate.cpp.
struct timeval readout_finished_time
Definition at line 122 of file crate.cpp.
Referenced by read_trigger_event(), and start_cycle().
struct readout_module rpc_master_module
Definition at line 38 of file rpc_master.cpp.
struct readout_module rpc_slave_module
Definition at line 35 of file rpc_slave.cpp.
int run_state
Definition at line 322 of file mfe_mucap.c.
Referenced by close_buffers(), display(), frontend_init(), frontend_loop(), handFlush(), interprete(), lazy_condition_check(), main(), read_trigger_event(), register_equipment(), scan_fragment(), scheduler(), tr_pause(), tr_prepause(), tr_prestart(), tr_prestop(), tr_resume(), tr_start(), tr_start2(), and tr_stop().
struct readout_module s500_module
Definition at line 18 of file s500.cpp.
struct readout_module* trigger_modules[]
Initial value:
 {
  &rpc_master_module,
  &parport_module,
  &rpc_slave_module,
}
Definition at line 114 of file crate.cpp.