AlcapDAQ: crate9/dl40x.h File Reference
dl40x.h File Reference
Macros
#define DL401_MAXMODULES 16
#define DL401_NCHAN 4 /* number of inputs per module */
#define DL401_PEDCHANBITS 6
#define DL401_PEDCHANMASK 0x3F /* pedestal mask (one chan) */
#define DL401_PEDBITMASK 0x00800000 /* pedestal bit mask */
#define DL401_PEDBITS 24
#define DL401_PEDMASK 0x00FFFFFF /* pedestal mask */
#define DL401_CNTMASK 0x03FF
#define DL401_CNTMAX 0x0400
#define DL401_ICNV 0x02 /* Internal CoNVert (D0) (R) */
#define DL401_CLIF 0x02 /* Clear Interrupt Flag (W) */
#define DL401_WDAC 0x12 /* Write serial DAC data (W) */
#define DL401_MRST 0x22 /* Module ReSeT (W) */
#define DL401_BASE 0x52 /* load BASE address (0x00) (W) */
#define DL401_MASK 0x62 /* MASK word (see below) (W) */
#define DL401_MODE 0x72 /* MODE word (see below) (R/W) */
#define DL401_RMAD 0x90 /* Read Memory ADdres counter (R) */
#define DL401_SMODSIZ 0x000f /* load SubMODule SIZe (==0) */
#define DL401_ADDRMOD 0x3f00 /* load ADDress MODifier */
#define DL401_ADDRMSH 8 /* ADDress Modifier SHift */
#define VME_AM_EXT_USR_DATA 0x09
#define DL401_AM_EXT_MODE (VME_AM_EXT_USR_DATA << DL401_ADDRMSH)
#define DL401_AM_STD_MODE (VME_AM_STD_USR_DATA << DL401_ADDRMSH)
#define DL401_LWIOENA 0x8000 /* Long Word I/O ENAble */
#define DL401_IRQVEC 0x00ff /* Interrupt VECtor (R/W) */
#define DL401_IRQPRI 0x0700 /* Interrupt PRIority (R/W) */
#define DL401_IRQMOD 0x0800 /* Interrupt MODe (R/W) */
#define DL401_DEFMODE 0x0000 /* DEFault MODe (W) */
#define DL401_INTMODE 0x1000 /* INTernal MODe (W) */
#define DL401_EXTMODE 0xefff /* EXTernal MODe (W) */
#define DL401_INTGATE 0x2000 /* internal gate (W) */
#define DL401_EXTGATE 0xdfff /* external gate (W) */
#define DL401_DACWDIS 0x4000 /* DAC Write DISable (W) */
#define DL401_DACWENA 0xbfff /* DAC Write ENAble (W) */
#define DL401_AUTOMODE 0x8000 /* AUTOstop MODE enable (W) */
#define DL401_CONTMODE 0x7fff /* CONTinuous MODE enable (W) */
#define DL401_ASTOPACT 0x1000 /* :0 auto stop active */
#define DL401_INTREQ 0x2000 /* :1 internal interrupt request*/
#define DL401_RDAC 0x4000 /* Read serial DAQ output */
#define DL403_MAXMODULES 4
#define DL403_CYCLESNUM 3
#define DL403_CYCLE1 0x02
#define DL403_CYCLE2 0x04
#define DL403_CYCLE3 0x06
#define DL403_RATE 0x08
#define DL403_START 0x0a
#define DL403_STOP 0x0c
#define DL403_MODE 0x72
#define DL403_RESET 0x22
#define DL403_EXTERN 0x00
#define DL403_SELECTED 0x01
#define DL403_50MHZ 0x02
#define DL403_100MHZ 0x03
#define DL403_ASYNC 0x1000
#define DL403_CONT 0x2000
#define DL403_STEADY 0x4000
#define DL403_RUN 0x1000
#define DL403_RUNSHFT 12
#define DL403_GO 0xffff /* used for start/stop commands */
Functions
INT dl401_init (struct dl401 *d)
void dl401_teardown ()
INLINE void dl401_setup (struct dl401 *d, u_short bs, u_short am, u_short md)
INLINE int dl401_setPedestals (struct dl401 *d, u_short p[], int np)
INLINE u_long dl401_getPedestals (struct dl401 *d)
INLINE u_short dl401_getCounts (struct dl401 *d)
INLINE u_short dl401_getMode (struct dl401 *d)
INLINE u_short dl401_getMask (struct dl401 *d)
INLINE void dl401_clear (struct dl401 *d)
INLINE void dl401_reset (struct dl401 *d)
INLINE void dl401_convert (struct dl401 *d)
INLINE int dl401_finished (struct dl401 *d)
INLINE int dl401_read (struct dl401 *d, u_int *data)
INLINE int dl401_dmaread (struct dl401 *d, u_int *data)
INT dl403_init (struct dl403 *d)
void dl403_setClockRate (struct dl403 *d, u_short clk1, u_short clk2, u_short clk3)
void dl403_setClockCycle (struct dl403 *d, u_short cyc1, u_short cyc2, u_short cyc3)
INLINE void dl403_asyncMode (struct dl403 *d)
INLINE void dl403_contMode (struct dl403 *d)
INLINE void dl403_steadyMode (struct dl403 *d)
INLINE short dl403_runBit (struct dl403 *d)
INLINE void dl403_start (struct dl403 *d)
INLINE void dl403_stop (struct dl403 *d)
INLINE void dl403_reset (struct dl403 *d)
INLINE short dl403_running (struct dl403 *d)
Macro Definition Documentation
#define DL401_ADDRMOD 0x3f00 /* load ADDress MODifier */
Definition at line 74 of file dl40x.h.
#define DL401_ADDRMSH 8 /* ADDress Modifier SHift */
Definition at line 75 of file dl40x.h.
#define DL401_AM_EXT_MODE (VME_AM_EXT_USR_DATA << DL401_ADDRMSH)
Definition at line 77 of file dl40x.h.
#define DL401_AM_STD_MODE (VME_AM_STD_USR_DATA << DL401_ADDRMSH)
Definition at line 78 of file dl40x.h.
#define DL401_ASTOPACT 0x1000 /* :0 auto stop active */
Definition at line 96 of file dl40x.h.
#define DL401_AUTOMODE 0x8000 /* AUTOstop MODE enable (W) */
Definition at line 93 of file dl40x.h.
#define DL401_BASE 0x52 /* load BASE address (0x00) (W) */
Definition at line 66 of file dl40x.h.
#define DL401_CLIF 0x02 /* Clear Interrupt Flag (W) */
Definition at line 63 of file dl40x.h.
#define DL401_CNTMASK 0x03FF
Definition at line 58 of file dl40x.h.
#define DL401_CNTMAX 0x0400
Definition at line 59 of file dl40x.h.
#define DL401_CONTMODE 0x7fff /* CONTinuous MODE enable (W) */
Definition at line 94 of file dl40x.h.
#define DL401_DACWDIS 0x4000 /* DAC Write DISable (W) */
Definition at line 91 of file dl40x.h.
#define DL401_DACWENA 0xbfff /* DAC Write ENAble (W) */
Definition at line 92 of file dl40x.h.
#define DL401_DEFMODE 0x0000 /* DEFault MODe (W) */
Definition at line 86 of file dl40x.h.
#define DL401_EXTGATE 0xdfff /* external gate (W) */
Definition at line 90 of file dl40x.h.
#define DL401_EXTMODE 0xefff /* EXTernal MODe (W) */
Definition at line 88 of file dl40x.h.
#define DL401_ICNV 0x02 /* Internal CoNVert (D0) (R) */
Definition at line 62 of file dl40x.h.
#define DL401_INTGATE 0x2000 /* internal gate (W) */
Definition at line 89 of file dl40x.h.
#define DL401_INTMODE 0x1000 /* INTernal MODe (W) */
Definition at line 87 of file dl40x.h.
#define DL401_INTREQ 0x2000 /* :1 internal interrupt request*/
Definition at line 97 of file dl40x.h.
#define DL401_IRQMOD 0x0800 /* Interrupt MODe (R/W) */
Definition at line 84 of file dl40x.h.
#define DL401_IRQPRI 0x0700 /* Interrupt PRIority (R/W) */
Definition at line 83 of file dl40x.h.
#define DL401_IRQVEC 0x00ff /* Interrupt VECtor (R/W) */
Definition at line 82 of file dl40x.h.
#define DL401_LWIOENA 0x8000 /* Long Word I/O ENAble */
Definition at line 79 of file dl40x.h.
#define DL401_MASK 0x62 /* MASK word (see below) (W) */
Definition at line 67 of file dl40x.h.
#define DL401_MAXMODULES 16
Definition at line 50 of file dl40x.h.
#define DL401_MODE 0x72 /* MODE word (see below) (R/W) */
Definition at line 68 of file dl40x.h.
#define DL401_MRST 0x22 /* Module ReSeT (W) */
Definition at line 65 of file dl40x.h.
#define DL401_NCHAN 4 /* number of inputs per module */
Definition at line 52 of file dl40x.h.
#define DL401_PEDBITMASK 0x00800000 /* pedestal bit mask */
Definition at line 55 of file dl40x.h.
#define DL401_PEDBITS 24
Definition at line 56 of file dl40x.h.
#define DL401_PEDCHANBITS 6
Definition at line 53 of file dl40x.h.
#define DL401_PEDCHANMASK 0x3F /* pedestal mask (one chan) */
Definition at line 54 of file dl40x.h.
#define DL401_PEDMASK 0x00FFFFFF /* pedestal mask */
Definition at line 57 of file dl40x.h.
#define DL401_RDAC 0x4000 /* Read serial DAQ output */
Definition at line 98 of file dl40x.h.
#define DL401_RMAD 0x90 /* Read Memory ADdres counter (R) */
Definition at line 69 of file dl40x.h.
#define DL401_SMODSIZ 0x000f /* load SubMODule SIZe (==0) */
Definition at line 73 of file dl40x.h.
#define DL401_WDAC 0x12 /* Write serial DAC data (W) */
Definition at line 64 of file dl40x.h.
#define DL403_100MHZ 0x03
Definition at line 120 of file dl40x.h.
#define DL403_50MHZ 0x02
Definition at line 119 of file dl40x.h.
#define DL403_ASYNC 0x1000
Definition at line 123 of file dl40x.h.
#define DL403_CONT 0x2000
Definition at line 124 of file dl40x.h.
#define DL403_CYCLE1 0x02
Definition at line 107 of file dl40x.h.
#define DL403_CYCLE2 0x04
Definition at line 108 of file dl40x.h.
#define DL403_CYCLE3 0x06
Definition at line 109 of file dl40x.h.
#define DL403_CYCLESNUM 3
Definition at line 104 of file dl40x.h.
#define DL403_EXTERN 0x00
Definition at line 117 of file dl40x.h.
#define DL403_GO 0xffff /* used for start/stop commands */
Definition at line 130 of file dl40x.h.
#define DL403_MAXMODULES 4
Definition at line 103 of file dl40x.h.
#define DL403_MODE 0x72
Definition at line 113 of file dl40x.h.
#define DL403_RATE 0x08
Definition at line 110 of file dl40x.h.
#define DL403_RESET 0x22
Definition at line 114 of file dl40x.h.
#define DL403_RUN 0x1000
Definition at line 127 of file dl40x.h.
#define DL403_RUNSHFT 12
Definition at line 128 of file dl40x.h.
#define DL403_SELECTED 0x01
Definition at line 118 of file dl40x.h.
#define DL403_START 0x0a
Definition at line 111 of file dl40x.h.
#define DL403_STEADY 0x4000
Definition at line 125 of file dl40x.h.
#define DL403_STOP 0x0c
Definition at line 112 of file dl40x.h.
#define VME_AM_EXT_USR_DATA 0x09
Definition at line 76 of file dl40x.h.
Function Documentation
INLINE void dl401_clear (struct dl401 * d)
Definition at line 280 of file dl40x.cpp.
References dl401::a16_base, dl401::a16_handle, DL401_CLIF, and vme_write_d16().
Referenced by dl401_bor1(), and dl40x_read().
 {
   vme_write_d16 (d->a16_handle, d->a16_base | DL401_CLIF, 0xffff);
 }
INLINE void dl401_convert (struct dl401 * d)
Definition at line 286 of file dl40x.cpp.
References dl401::a16_base, dl401::a16_handle, DL401_ICNV, and vme_read_d16().
 {
   vme_read_d16 (d->a16_handle, d->a16_base | DL401_ICNV);
 }
INLINE int dl401_dmaread (struct dl401 * d, u_int * data)
INLINE int dl401_finished (struct dl401 * d)
Definition at line 292 of file dl40x.cpp.
References dl401::a16_base, dl401::a16_handle, DL401_INTREQ, DL401_MODE, and vme_read_d16().
Referenced by dl40x_read().
 {
   WORD mode = vme_read_d16 (d->a16_handle, d->a16_base | DL401_MODE);
   return (mode & DL401_INTREQ);
 }
INLINE u_short dl401_getCounts (struct dl401 * d)
Definition at line 261 of file dl40x.cpp.
References dl401::a16_base, dl401::a16_handle, DL401_CNTMASK, DL401_RMAD, and vme_read_d16().
Referenced by dl401_read().
 {
   WORD rmad = vme_read_d16 (d->a16_handle, d->a16_base | DL401_RMAD);
   return rmad & DL401_CNTMASK;
 }
INLINE u_short dl401_getMask (struct dl401 * d)
INLINE u_short dl401_getMode (struct dl401 * d)
Definition at line 268 of file dl40x.cpp.
References dl401::a16_base, dl401::a16_handle, DL401_MODE, and vme_read_d16().
 {
   return vme_read_d16 (d->a16_handle, d->a16_base | DL401_MODE);
 }
INLINE u_long dl401_getPedestals (struct dl401 * d)
INT dl401_init (struct dl401 * d)
INLINE int dl401_read (struct dl401 * d, u_int * data)
Definition at line 300 of file dl40x.cpp.
References dl401::a32_base, dl401::a32_handle, diag_print(), DL401_CNTMAX, dl401_getCounts(), i, and vme_read_d32().
Referenced by dl40x_read().
 {
   register u_int i = 0;
   register u_int *addr;
   int counts;
   counts = dl401_getCounts (d);
   diag_print (2, "dl401_read: [%d] base=%p counts=%d\n", d, addr, counts);
   while (i < DL401_CNTMAX - counts)
     {
       data[i++] = vme_read_d32 (d->a32_handle, d->a32_base + (i + counts)*4);
     }
   i = 0;
   while (i < counts)
     {
       data[DL401_CNTMAX - counts + i] =
         vme_read_d32 (d->a32_handle, d->a32_base + i*4);
       i++;
     }
   diag_print (2, "--> done\n");
   return (DL401_CNTMAX);
 }
INLINE void dl401_reset (struct dl401 * d)
Definition at line 274 of file dl40x.cpp.
References dl401::a16_base, dl401::a16_handle, DL401_MRST, and vme_write_d16().
Referenced by dl401_bor1(), and dl40x_read().
 {
   vme_write_d16 (d->a16_handle, d->a16_base | DL401_MRST, 0xffff);
 }
INLINE int dl401_setPedestals (struct dl401 * d, u_short p[], int np)
Definition at line 226 of file dl40x.cpp.
References dl401::a16_base, dl401::a16_handle, diag_print(), DL401_DACWDIS, DL401_DACWENA, DL401_DEFMODE, DL401_MODE, DL401_NCHAN, DL401_PEDBITS, DL401_PEDCHANBITS, DL401_PEDCHANMASK, DL401_PEDMASK, DL401_WDAC, i, SUCCESS, and vme_write_d16().
Referenced by dl401_bor1().
 {
   if (np != DL401_NCHAN)
     return (-1);
   // compute word to write to pedestal DAC
   DWORD parPed = 0;
   for (int i = 0; i < np; i++) {
       parPed |= (u_long) (p[i] & DL401_PEDCHANMASK) << (i * DL401_PEDCHANBITS);
   }
   parPed &= DL401_PEDMASK;
   diag_print (2, "dl401_setPedestal: [%d] 0%08lo (", d, parPed);
   // enable writing to DAC
   vme_write_d16 (d->a16_handle, d->a16_base | DL401_MODE,
                  DL401_DEFMODE & DL401_DACWENA);
   // shift bits into DAC one at a time; it's a serial interface
   for (int i = 0; i < DL401_PEDBITS; i++)
     {
       u_short bit =
         ((parPed << i) & DL401_PEDBITMASK) >> (DL401_PEDBITS - 1);
       vme_write_d16 (d->a16_handle, d->a16_base | DL401_WDAC, bit & 0x0001);
       diag_print (2, "%1x", bit);
     }
   // disable writing to DAC
   vme_write_d16 (d->a16_handle, d->a16_base | DL401_MODE,
                  DL401_DEFMODE | DL401_DACWDIS);
   diag_print (2, ")\n");
   return SUCCESS;
 }
INLINE void dl401_setup (struct dl401 * d, u_short bs, u_short am, u_short md)
void dl401_teardown ()
INLINE void dl403_asyncMode (struct dl403 * d)
Definition at line 436 of file dl40x.cpp.
References dl403::a16_base, DL403_ASYNC, DL403_MODE, dl403::vme_handle, and vme_write_d16().
 {
   vme_write_d16 (d->vme_handle, d->a16_base | DL403_MODE, DL403_ASYNC);
 }
INLINE void dl403_contMode (struct dl403 * d)
Definition at line 442 of file dl40x.cpp.
References dl403::a16_base, DL403_CONT, DL403_MODE, dl403::vme_handle, and vme_write_d16().
 {
   vme_write_d16 (d->vme_handle, d->a16_base | DL403_MODE, DL403_CONT);
 }
INT dl403_init (struct dl403 * d)
Definition at line 352 of file dl40x.cpp.
References dl403::a16_base, crate_number, diag_print(), DL403_100MHZ, DL403_50MHZ, DL403_SELECTED, dl403_setClockCycle(), dl403_setClockRate(), dl403_start(), dl403_steadyMode(), dl403::enabled, FALSE, frontend_name, odb_find_key(), odb_get_int(), odb_get_word(), SUCCESS, TRUE, dl403::vme_handle, vme_open(), VMEMAP_ASPACE_A16, VMEMAP_DWIDTH_32, VMEMAP_PRGDATAAM_DATA, and VMEMAP_SUPUSERAM_SUPER.
Referenced by dl40x_bor().
 {
   // Do we have an FADC clock?
   if (odb_find_key("/Equipment/Crate %d/Settings/FADC CLOCK", crate_number)) {
     d->enabled = TRUE;
   } else {
     d->enabled = FALSE;
     return SUCCESS;
   }
   // find base address
   d->a16_base =
     odb_get_word ("/Equipment/Crate %d/Settings/FADC CLOCK/a16 base address",
                   crate_number);
   // Open a VME handle
   struct vme_mapping_ctrl a16_mapping = {
           VMEMAP_DWIDTH_32,
           VMEMAP_ASPACE_A16,
           VMEMAP_SUPUSERAM_SUPER,
           VMEMAP_PRGDATAAM_DATA
   };
   d->vme_handle = vme_open(d->a16_base, a16_mapping, 0x100, 0);
   // Set DL403 clock frequency
   INT fadc_frequency =
     odb_get_int ("/Equipment/Crate %d/Settings/FADC CLOCK/frequency", crate_number);
   switch (fadc_frequency)
     {
     case 100:
       dl403_setClockRate (d, DL403_100MHZ, 0x0, 0x0);
       break;
     case 50:
       dl403_setClockRate (d, DL403_50MHZ, 0x0, 0x0);
       break;
     case 25:
       dl403_setClockRate (d, DL403_SELECTED, 0x0, 0x0);
       break;
     default:
       cm_msg (MERROR, frontend_name,
               "FADC clock frequency must be 25, 50, or 100 MHz (currently %d)\n",
               fadc_frequency);
       dl403_setClockRate (d, DL403_50MHZ, 0x0, 0x0);
     }
   dl403_setClockCycle (d, 0x800, 0x800, 0x800);
   dl403_steadyMode (d);
   dl403_start (d);
   diag_print (2, "dl403_init 0x%08lx\n", d->a16_base);
   return SUCCESS;
 }
INLINE void dl403_reset (struct dl403 * d)
Definition at line 466 of file dl40x.cpp.
References dl403::a16_base, DL403_GO, DL403_RESET, dl403::vme_handle, and vme_write_d16().
 {
   vme_write_d16 (d->vme_handle, d->a16_base | DL403_RESET, DL403_GO);
 }
INLINE short dl403_runBit (struct dl403 * d)
Definition at line 472 of file dl40x.cpp.
References dl403::a16_base, DL403_MODE, DL403_RUN, dl403::vme_handle, and vme_read_d16().
 {
   WORD mode = vme_read_d16 (d->vme_handle, d->a16_base | DL403_MODE);
   return (mode & DL403_RUN);
 }
INLINE short dl403_running (struct dl403 * d)
Definition at line 479 of file dl40x.cpp.
References dl403::a16_base, DL403_MODE, DL403_RUN, dl403::vme_handle, and vme_read_d16().
Referenced by dl40x_read().
 {
   WORD mode = vme_read_d16 (d->vme_handle, d->a16_base | DL403_MODE);
   return !(mode & DL403_RUN);
 }
void dl403_setClockCycle (struct dl403 * d, u_short cyc1, u_short cyc2, u_short cyc3)
Definition at line 417 of file dl40x.cpp.
References dl403::a16_base, diag_print(), DL403_CYCLE1, DL403_CYCLE2, DL403_CYCLE3, dl403::vme_handle, and vme_write_d16().
Referenced by dl403_init().
 {
   vme_write_d16 (d->vme_handle, d->a16_base | DL403_CYCLE1, c1);
   vme_write_d16 (d->vme_handle, d->a16_base | DL403_CYCLE2, c2);
   vme_write_d16 (d->vme_handle, d->a16_base | DL403_CYCLE3, c3);
   diag_print (2,
               "dl403_setClockCycles: [%d] cyc1=0x%04hx cyc2=0x%04hx cyc3=0x%04hx\n",
               d, c1, c2, c3);
 }
void dl403_setClockRate (struct dl403 * d, u_short clk1, u_short clk2, u_short clk3)
Definition at line 407 of file dl40x.cpp.
References dl403::a16_base, diag_print(), DL403_RATE, dl403::vme_handle, and vme_write_d16().
Referenced by dl403_init().
 {
   diag_print (2, "dl403_setClockRate: [%d] rate=0x%02hx\n", d,
               (clk1 | (clk2 << 2) | (clk3 << 4)));
   vme_write_d16 (d->vme_handle, d->a16_base | DL403_RATE,
                  clk1 | (clk2 << 2) | (clk3 << 4));
 }
INLINE void dl403_start (struct dl403 * d)
Definition at line 454 of file dl40x.cpp.
References dl403::a16_base, DL403_GO, DL403_START, dl403::vme_handle, and vme_write_d16().
Referenced by dl403_init(), and dl40x_read().
 {
   vme_write_d16 (d->vme_handle, d->a16_base | DL403_START, DL403_GO);
 }
INLINE void dl403_steadyMode (struct dl403 * d)
Definition at line 448 of file dl40x.cpp.
References dl403::a16_base, DL403_MODE, DL403_STEADY, dl403::vme_handle, and vme_write_d16().
Referenced by dl403_init().
 {
   vme_write_d16 (d->vme_handle, d->a16_base | DL403_MODE, DL403_STEADY);
 }
INLINE void dl403_stop (struct dl403 * d)
Definition at line 460 of file dl40x.cpp.
References dl403::a16_base, DL403_GO, DL403_STOP, dl403::vme_handle, and vme_write_d16().
 {
   vme_write_d16 (d->vme_handle, d->a16_base | DL403_STOP, DL403_GO);
 }