AlcapDAQ: crate9/mfe_mucap.c File Reference
mfe_mucap.c File Reference
#include <stdio.h>
#include <assert.h>
#include "midas.h"
#include "msystem.h"
#include "mcstd.h"
Macros
#define SERVER_CACHE_SIZE 100000 /* event cache before buffer */
#define ODB_UPDATE_TIME 1000 /* 1 seconds for ODB update */
#define DEFAULT_FE_TIMEOUT 60000 /* 60 seconds for watchdog timeout */
#define EQUIPMENT_COMMON_STR "\Event ID = WORD : 0\n\Trigger mask = WORD : 0\n\Buffer = STRING : [32] SYSTEM\n\Type = INT : 0\n\Source = INT : 0\n\Format = STRING : [8] FIXED\n\Enabled = BOOL : 0\n\Read on = INT : 0\n\Period = INT : 0\n\Event limit = DOUBLE : 0\n\Num subevents = DWORD : 0\n\Log history = INT : 0\n\Frontend host = STRING : [32] \n\Frontend name = STRING : [32] \n\Frontend file name = STRING : [256] \n\"
#define EQUIPMENT_STATISTICS_STR "\Events sent = DOUBLE : 0\n\Events per sec. = DOUBLE : 0\n\kBytes per sec. = DOUBLE : 0\n\"
Functions
INT frontend_init (void)
INT frontend_exit (void)
INT frontend_loop (void)
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
INT poll_event (INT source, INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
int send_event (INT index)
void send_all_periodic_events (INT transition)
void interrupt_routine (void)
void interrupt_enable (BOOL flag)
void display (BOOL bInit)
INT tr_start (INT rn, char *error)
INT tr_stop (INT rn, char *error)
INT tr_pause (INT rn, char *error)
INT tr_resume (INT rn, char *error)
INT manual_trigger (INT index, void *prpc_param[])
INT register_equipment (void)
void update_odb (EVENT_HEADER *pevent, HNDLE hKey, INT format)
int message_print (const char *msg)
BOOL logger_root ()
INT scheduler (void)
INT get_frontend_index ()
int main (int argc, char *argv[])
Variables
char * frontend_name
char * frontend_file_name
int crate_number
BOOL frontend_call_loop
INT max_event_size
INT max_event_size_frag
INT event_buffer_size
INT display_period
INT run_state
INT run_number
DWORD actual_time
DWORD actual_millitime
char host_name [HOST_NAME_LENGTH]
char exp_name [NAME_LENGTH]
char full_frontend_name [256]
INT max_bytes_per_sec
INT optimize = 0
INT fe_stop = 0
BOOL debug
DWORD auto_restart = 0
INT manual_trigger_event_id = 0
INT frontend_index = -1
HNDLE hDB
EQUIPMENT equipment []
EQUIPMENT * interrupt_eq = NULL
EVENT_HEADER * interrupt_odb_buffer
BOOL interrupt_odb_buffer_valid
BOOL interrupt_enabled
Macro Definition Documentation
#define DEFAULT_FE_TIMEOUT 60000 /* 60 seconds for watchdog timeout */
Definition at line 297 of file mfe_mucap.c.
Referenced by main().
#define EQUIPMENT_COMMON_STR "\Event ID = WORD : 0\n\Trigger mask = WORD : 0\n\Buffer = STRING : [32] SYSTEM\n\Type = INT : 0\n\Source = INT : 0\n\Format = STRING : [8] FIXED\n\Enabled = BOOL : 0\n\Read on = INT : 0\n\Period = INT : 0\n\Event limit = DOUBLE : 0\n\Num subevents = DWORD : 0\n\Log history = INT : 0\n\Frontend host = STRING : [32] \n\Frontend name = STRING : [32] \n\Frontend file name = STRING : [256] \n\"
Definition at line 349 of file mfe_mucap.c.
Referenced by register_equipment().
#define EQUIPMENT_STATISTICS_STR "\Events sent = DOUBLE : 0\n\Events per sec. = DOUBLE : 0\n\kBytes per sec. = DOUBLE : 0\n\"
Definition at line 367 of file mfe_mucap.c.
Referenced by register_equipment().
#define ODB_UPDATE_TIME 1000 /* 1 seconds for ODB update */
Definition at line 295 of file mfe_mucap.c.
Referenced by scheduler().
#define SERVER_CACHE_SIZE 100000 /* event cache before buffer */
Definition at line 291 of file mfe_mucap.c.
Referenced by register_equipment(), and scheduler().
Function Documentation
INT begin_of_run (INT run_number, char * error)
Definition at line 295 of file crate.cpp.
References readout_module::bor, diag_print(), i, num_periodic_modules, num_trigger_modules, status, and SUCCESS.
Referenced by tr_start().
 {
   diag_print(1, "*** Begin of run %d ***\n", run_number);
   for(int i = 0; i < num_trigger_modules; i++) {
     if((*trigger_modules[i]).bor != NULL) {
       int status = (*trigger_modules[i]).bor();
       if(status != SUCCESS) {
         return status;
       }
     }
   }
   for(int i = 0; i < num_periodic_modules; i++) {
     if((*periodic_modules[i]).bor != NULL) {
       int status = (*periodic_modules[i]).bor();
       if(status != SUCCESS) {
         return status;
       }
     }
   }
   cycle_active = 0;
   event_avail = false;
   between_runs = false;
   return SUCCESS;
 }
void display (BOOL bInit)
INT end_of_run (INT run_number, char * error)
Definition at line 330 of file crate.cpp.
References diag_print(), readout_module::eor, i, num_periodic_modules, num_trigger_modules, status, and SUCCESS.
Referenced by tr_prestop(), and tr_stop().
 {
   diag_print(1, "*** End of run %d ***\n", run_number);
   between_runs = true;
   for(int i = 0; i < num_trigger_modules; i++) {
     if((*trigger_modules[i]).eor != NULL) {
       int status = (*trigger_modules[i]).eor();
       if(status != SUCCESS) {
         return status;
       }
     }
   }
   for(int i = 0; i < num_periodic_modules; i++) {
     if((*periodic_modules[i]).eor != NULL) {
       int status = (*periodic_modules[i]).eor();
       if(status != SUCCESS) {
         return status;
       }
     }
   }
   return SUCCESS;
 }
INT frontend_exit (void)
Definition at line 244 of file crate.cpp.
References readout_module::exit, i, num_periodic_modules, num_trigger_modules, and SUCCESS.
Referenced by main().
 {
   for(int i = 0; i < num_trigger_modules; i++) {
     if((*trigger_modules[i]).exit != NULL) {
       (*trigger_modules[i]).exit();
     }
   }
   for(int i = 0; i < num_periodic_modules; i++) {
     if((*periodic_modules[i]).exit != NULL) {
       (*periodic_modules[i]).exit();
     }
   }
   return SUCCESS;
 }
INT frontend_init (void)
Definition at line 207 of file crate.cpp.
References ACK, Alarm, FALSE, hDB, hKey, i, readout_module::init, INQ_MODE, kJustFilled, kLastFilled, kTimeLimit, missed_reads, num_periodic_modules, num_trigger_modules, odb_get_int(), printf(), resp, run_state, sJustFilled, sLastFilled, status, sTimeLimit, SUCCESS, vac_ready, vac_timeout, vacuum, vacuum_config, and vacuum_port.
Referenced by main().
 {
   printf("Entering frontend_init() ... \n");
   INT run_state = odb_get_int("/Runinfo/State");
   if (run_state != STATE_STOPPED) {
     cm_msg(MERROR, "Crate",
             "Run must be stopped before starting crate program.");
     return FE_ERR_HW;
   }
   for(int i = 0; i < num_trigger_modules; i++) {
     if((*trigger_modules[i]).init != NULL) {
       int status = (*trigger_modules[i]).init();
       if(status != SUCCESS) {
         return status;
       }
     }
   }
   for(int i = 0; i < num_periodic_modules; i++) {
     if((*periodic_modules[i]).init != NULL) {
       int status = (*periodic_modules[i]).init();
       if(status != SUCCESS) {
         return status;
       }
     }
   }
   return SUCCESS;
 }
INT frontend_loop (void)
Definition at line 435 of file crate.cpp.
References consider_start(), FE_END_BLOCK, FE_NEED_STOP, i, num_trigger_modules, run_state, status, stop_cycle(), SUCCESS, and TRUE.
Referenced by poll_event(), and scheduler().
 {
   // If we're going to be pre-empted, get it over with during livetime
   // rather than deadtime.
   if (cycle_active || run_state != STATE_RUNNING || between_runs == TRUE) {
     dm_area_flush();
     sched_yield();
   }
   // Exit immediately if no run in progress
   if (run_state != STATE_RUNNING || between_runs == TRUE) {
     return SUCCESS;
   }
   // Call appropriate poll functions, depending on whether we're live or dead
   //printf("fe loop: cycle_active %i\n",cycle_active);
   if (cycle_active) {
     for(int i = 0; i < num_trigger_modules; i++) {
       if((*trigger_modules[i]).poll_live != NULL) {
         // There are conditions that can lead to changes in run state between
         // modules...
         if (run_state != STATE_RUNNING || between_runs == TRUE) {
           return SUCCESS;
         }
         int status = (*trigger_modules[i]).poll_live();
         if(status == FE_END_BLOCK) {
           cycle_active = 0;
           event_avail = true;
         } else if(status == FE_NEED_STOP) {
           stop_cycle();
         } else if(status != SUCCESS) {
           return status;
         }
       }
     }
   } else {
     consider_start();
   }
   return SUCCESS;
 }
INT get_frontend_index ()
Definition at line 1928 of file mfe_mucap.c.
References frontend_index.
 {
    return frontend_index;
 }
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Definition at line 505 of file crate.cpp.
References FALSE, interrupt_handler, interrupts_enabled, SUCCESS, and TRUE.
Referenced by interrupt_enable(), main(), and register_equipment().
 {
     switch (cmd) {
     case CMD_INTERRUPT_ENABLE:
         interrupts_enabled = TRUE;
         break;
     case CMD_INTERRUPT_DISABLE:
         interrupts_enabled = FALSE;
         break;
     case CMD_INTERRUPT_ATTACH:
         interrupt_handler = (void (*)(void)) adr;
         break;
     case CMD_INTERRUPT_DETACH:
         interrupts_enabled = FALSE;
         interrupt_handler = NULL;
         break;
     }
     return SUCCESS;
 }
void interrupt_enable (BOOL flag)
void interrupt_routine (void)
BOOL logger_root ()
Definition at line 1335 of file mfe_mucap.c.
References FALSE, hDB, hKey, i, size, status, and TRUE.
 {
    int size, i, status;
    char str[80];
    HNDLE hKeyRoot, hKey;
    if (db_find_key(hDB, 0, "/Logger/Channels", &hKeyRoot) == DB_SUCCESS) {
       for (i = 0;; i++) {
          status = db_enum_key(hDB, hKeyRoot, i, &hKey);
          if (status == DB_NO_MORE_SUBKEYS)
             break;
          strcpy(str, "MIDAS");
          size = sizeof(str);
          db_get_value(hDB, hKey, "Settings/Format", str, &size, TID_STRING, TRUE);
          if (equal_ustring(str, "ROOT"))
             return TRUE;
       }
    }
    return FALSE;
 }
int main (int argc, char * argv[])
Definition at line 1938 of file mfe_mucap.c.
References cm_get_environment(), cnaf_callback(), crate_number, debug, DEFAULT_FE_TIMEOUT, display(), display_period, equipment, event_buffer_size, exp_name, FALSE, frontend_early_init(), frontend_exit(), frontend_index, frontend_init(), frontend_name, full_frontend_name, hDB, host_name, i, interrupt_configure(), interrupt_enable(), interrupt_eq, interrupt_odb_buffer, message_print(), printf(), register_equipment(), run_state, scheduler(), sprintf(), status, SUCCESS, tr_pause(), tr_prestart, tr_resume(), tr_start(), tr_stop, TRUE, and usage().
 {
    INT status, i, dm_size;
    INT daemon;
    host_name[0] = 0;
    exp_name[0] = 0;
    debug = FALSE;
    daemon = 0;
    setbuf(stdout, 0);
    setbuf(stderr, 0);
 #ifdef SIGPIPE
    signal(SIGPIPE, SIG_IGN);
 #endif
 #ifdef OS_VXWORKS
    if (ahost_name)
       strcpy(host_name, ahost_name);
    if (aexp_name)
       strcpy(exp_name, aexp_name);
    debug = adebug;
 #else
    /* get default from environment */
    cm_get_environment(host_name, sizeof(host_name), exp_name, sizeof(exp_name));
    /* parse command line parameters */
    for (i = 1; i < argc; i++) {
       if (argv[i][0] == '-' && argv[i][1] == 'd')
          debug = TRUE;
       else if (argv[i][0] == '-' && argv[i][1] == 'D')
          daemon = 1;
       else if (argv[i][0] == '-' && argv[i][1] == 'O')
          daemon = 2;
       else if (argv[i][0] == '-') {
          if (i + 1 >= argc || argv[i + 1][0] == '-')
             goto usage;
          if (argv[i][1] == 'e')
             strcpy(exp_name, argv[++i]);
          else if (argv[i][1] == 'h')
             strcpy(host_name, argv[++i]);
          else if (argv[i][1] == 'i')
             frontend_index = atoi(argv[++i]);
          else {
           usage:
             printf("usage: frontend [-h Hostname] [-e Experiment] [-d] [-D] [-O] [-i n]\n");
             printf("         [-d]     Used to debug the frontend\n");
             printf("         [-D]     Become a daemon\n");
             printf("         [-O]     Become a daemon but keep stdout\n");
             printf("         [-i n]   Set frontend index (used for event building)\n");
             return 0;
          }
       }
    }
 #endif
 #ifdef PART_OF_MUCAP
   frontend_early_init();
 #endif
    /* check event and buffer sizes */
    if (event_buffer_size < 2 * max_event_size) {
       printf("event_buffer_size too small for max. event size\n");
       ss_sleep(5000);
       return 1;
    }
    if (max_event_size > MAX_EVENT_SIZE) {
       printf("Requested max_event_size (%d) exceeds max. system event size (%d)",
              max_event_size, MAX_EVENT_SIZE);
       ss_sleep(5000);
       return 1;
    }
    dm_size = event_buffer_size;
 #ifdef OS_VXWORKS
    /* override dm_size in case of VxWorks
       take remaining free memory and use 20% of it for dm_ */
    dm_size = 2 * 10 * (max_event_size + sizeof(EVENT_HEADER) + sizeof(INT));
    if (dm_size > memFindMax()) {
       cm_msg(MERROR, "mainFE", "Not enough mem space for event size");
       return 0;
    }
    /* takes overall 20% of the available memory resource for dm_() */
    dm_size = 0.2 * memFindMax();
    /* there are two buffers */
    dm_size /= 2;
 #endif
    /* reduce memory size for MS-DOS */
 #ifdef OS_MSDOS
    if (dm_size > 0x4000)
       dm_size = 0x4000;         /* 16k */
 #endif
    /* add frontend index to frontend name if present */
    strcpy(full_frontend_name, frontend_name);
    if (frontend_index >= 0)
       sprintf(full_frontend_name+strlen(full_frontend_name), "%02d", frontend_index);
    /* inform user of settings */
    printf("Frontend name          :     %s\n", full_frontend_name);
    printf("Event buffer size      :     %d\n", event_buffer_size);
    printf("Buffer allocation      : 2 x %d\n", dm_size);
    printf("System max event size  :     %d\n", MAX_EVENT_SIZE);
    printf("User max event size    :     %d\n", max_event_size);
    if (max_event_size_frag > 0)
       printf("User max frag. size    :     %d\n", max_event_size_frag);
    printf("# of events per buffer :     %d\n\n", dm_size / max_event_size);
    if (daemon) {
       printf("\nBecoming a daemon...\n");
       ss_daemon_init(daemon == 2);
    }
    /* now connect to server */
    if (display_period) {
       if (host_name[0])
          printf("Connect to experiment %s on host %s...", exp_name, host_name);
       else
          printf("Connect to experiment %s...", exp_name);
    }
    status = cm_connect_experiment1(host_name, exp_name, full_frontend_name,
                                    NULL, DEFAULT_ODB_SIZE, DEFAULT_FE_TIMEOUT);
    if (status != CM_SUCCESS) {
       /* let user read message before window might close */
       ss_sleep(5000);
       return 1;
    }
    if (display_period)
       printf("OK\n");
    /* book buffer space */
    status = dm_buffer_create(dm_size, max_event_size);
    if (status != CM_SUCCESS) {
       printf("dm_buffer_create: Not enough memory or event too big\n");
       return 1;
    }
    /* remomve any dead frontend */
    cm_cleanup(full_frontend_name, FALSE);
    /* shutdown previous frontend */
    status = cm_shutdown(full_frontend_name, FALSE);
    if (status == CM_SUCCESS && display_period) {
       printf("Previous frontend stopped\n");
       /* let user read message */
       ss_sleep(3000);
    }
    /* register transition callbacks */
    if (cm_register_transition(TR_START, tr_prestart, 400+crate_number) != CM_SUCCESS ||
        cm_register_transition(TR_START, tr_start, 500+crate_number) != CM_SUCCESS ||
        cm_register_transition(TR_STOP, tr_stop, 500+crate_number) != CM_SUCCESS ||
        cm_register_transition(TR_PAUSE, tr_pause, 500+crate_number) != CM_SUCCESS ||
        cm_register_transition(TR_RESUME, tr_resume, 500+crate_number) != CM_SUCCESS) {
       printf("Failed to start local RPC server");
       cm_disconnect_experiment();
       dm_buffer_release();
       /* let user read message before window might close */
       ss_sleep(5000);
       return 1;
    }
 #ifdef HAVE_CAMAC
    /* register CNAF callback */
    cm_register_function(RPC_CNAF16, cnaf_callback);
    cm_register_function(RPC_CNAF24, cnaf_callback);
 #endif
    cm_get_experiment_database(&hDB, &status);
    /* set time from server */
 #ifdef OS_VXWORKS
    cm_synchronize(NULL);
 #endif
    /* turn off watchdog if in debug mode */
    if (debug)
       cm_set_watchdog_params(TRUE, 0);
    /* increase RPC timeout to 2min for logger with exabyte or blocked disk */
    rpc_set_option(-1, RPC_OTIMEOUT, 120000);
    /* set own message print function */
    if (display_period)
       cm_set_msg_print(MT_ALL, MT_ALL, message_print);
    /* call user init function */
    if (display_period)
       printf("Init hardware...");
    if (frontend_init() != SUCCESS) {
       if (display_period)
          printf("\n");
       cm_disconnect_experiment();
       dm_buffer_release();
       /* let user read message before window might close */
       ss_sleep(5000);
       return 1;
    }
    /* reqister equipment in ODB */
    if (register_equipment() != SUCCESS) {
       if (display_period)
          printf("\n");
       cm_disconnect_experiment();
       dm_buffer_release();
       /* let user read message before window might close */
       ss_sleep(5000);
       return 1;
    }
    if (display_period)
       printf("OK\n");
    /* initialize screen display */
    if (display_period) {
       ss_sleep(1000);
       display(TRUE);
    }
    /* switch on interrupts if running */
    if (interrupt_eq && run_state == STATE_RUNNING)
       interrupt_enable(TRUE);
    /* initialize ss_getchar */
    ss_getchar(0);
    /* call main scheduler loop */
    status = scheduler();
    /* reset terminal */
    ss_getchar(TRUE);
    /* switch off interrupts */
    if (interrupt_eq) {
       interrupt_configure(CMD_INTERRUPT_DISABLE, 0, 0);
       interrupt_configure(CMD_INTERRUPT_DETACH, 0, 0);
       if (interrupt_odb_buffer)
          free(interrupt_odb_buffer);
    }
    /* detach interrupts */
    if (interrupt_eq != NULL)
       interrupt_configure(CMD_INTERRUPT_DETACH, interrupt_eq->info.source, 0);
    /* call user exit function */
    frontend_exit();
    /* close slow control drivers */
    for (i = 0; equipment[i].name[0]; i++)
       if ((equipment[i].info.eq_type & EQ_SLOW) && equipment[i].status == FE_SUCCESS)
          equipment[i].cd(CMD_EXIT, &equipment[i]);
    /* close network connection to server */
    cm_disconnect_experiment();
    if (display_period) {
       if (status == RPC_SHUTDOWN) {
          ss_clear_screen();
          ss_printf(0, 0, "Frontend shut down.");
          ss_printf(0, 1, "");
       }
    }
    if (status != RPC_SHUTDOWN)
       printf("Network connection aborted.\n");
    dm_buffer_release();
    return 0;
 }
INT manual_trigger (INT index, void * prpc_param[])
Definition at line 520 of file mfe_mucap.c.
References manual_trigger_event_id, and SUCCESS.
 {
    manual_trigger_event_id = CWORD(0);
    return SUCCESS;
 }
int message_print (const char * msg)
Definition at line 1246 of file mfe_mucap.c.
 {
    char str[160];
    memset(str, ' ', 159);
    str[159] = 0;
    if (msg[0] == '[')
       msg = strchr(msg, ']') + 2;
    memcpy(str, msg, strlen(msg));
    ss_printf(0, 20, str);
    return 0;
 }
INT pause_run (INT run_number, char * error)
Definition at line 362 of file crate.cpp.
References SUCCESS.
Referenced by tr_pause(), and tr_prepause().
 {
     return SUCCESS;
 }
INT poll_event (INT source, INT count, BOOL test)
Definition at line 486 of file crate.cpp.
References count, frontend_loop(), and i.
Referenced by register_equipment(), and scheduler().
 {
     INT retval = false;
     if(!test) {
       count = 1;
     }
     for (int i = 0; i < count; i++) {
         frontend_loop();
         if(event_avail) {
           retval = true;
         }
     }
     return retval;
 }
INT register_equipment (void)
Definition at line 528 of file mfe_mucap.c.
References count, display_period, equipment, EQUIPMENT_COMMON_STR, EQUIPMENT_STATISTICS_STR, FALSE, frontend_file_name, frontend_index, full_frontend_name, hDB, hKey, i, interrupt_configure(), interrupt_eq, interrupt_odb_buffer, interrupt_routine(), manual_trigger(), poll_event(), printf(), run_number, run_state, SERVER_CACHE_SIZE, size, sprintf(), start_time, status, SUCCESS, and TRUE.
 {
    INT index, count, size, status, i, j, k, n;
    char str[256];
    EQUIPMENT_INFO *eq_info;
    EQUIPMENT_STATS *eq_stats;
    DWORD start_time, delta_time;
    HNDLE hKey;
    BOOL manual_trig_flag = FALSE;
    BANK_LIST *bank_list;
    DWORD dummy;
    /* get current ODB run state */
    size = sizeof(run_state);
    run_state = STATE_STOPPED;
    db_get_value(hDB, 0, "/Runinfo/State", &run_state, &size, TID_INT, TRUE);
    size = sizeof(run_number);
    run_number = 1;
    status =
        db_get_value(hDB, 0, "/Runinfo/Run number", &run_number, &size, TID_INT, TRUE);
    assert(status == SUCCESS);
    /* scan EQUIPMENT table from FRONTEND.C */
    for (index = 0; equipment[index].name[0]; index++) {
       eq_info = &equipment[index].info;
       eq_stats = &equipment[index].stats;
       if (eq_info->event_id == 0) {
          printf("\nEvent ID 0 for %s not allowed\n", equipment[index].name);
          cm_disconnect_experiment();
          ss_sleep(5000);
          exit(0);
       }
       /* init status */
       equipment[index].status = FE_SUCCESS;
       /* check for event builder event */
       if (eq_info->eq_type & EQ_EB) {
          if (frontend_index == -1) {
             printf("\nEquipment \"%s\" has EQ_EB set, but no", equipment[index].name);
             printf(" index specified via \"-i\" flag.\nExiting.");
             cm_disconnect_experiment();
             ss_sleep(5000);
             exit(0);
          }
          /* modify equipment name to <name>xx where xx is the frontend index*/
          sprintf(equipment[index].name+strlen(equipment[index].name), "%02d", frontend_index);
          /* modify event buffer name to <name>xx where xx is the frontend index*/
          sprintf(eq_info->buffer+strlen(eq_info->buffer), "%02d", frontend_index);
       }
       sprintf(str, "/Equipment/%s/Common", equipment[index].name);
       /* get last event limit from ODB */
       if (eq_info->eq_type != EQ_SLOW) {
          db_find_key(hDB, 0, str, &hKey);
          size = sizeof(double);
          if (hKey)
             db_get_value(hDB, hKey, "Event limit", &eq_info->event_limit, &size,
                          TID_DOUBLE, TRUE);
       }
       /* Create common subtree */
       status = db_check_record(hDB, 0, str, EQUIPMENT_COMMON_STR, TRUE);
       if (status != DB_SUCCESS) {
          printf("Cannot check equipment record, status = %d\n", status);
          ss_sleep(3000);
       }
       db_find_key(hDB, 0, str, &hKey);
       if (equal_ustring(eq_info->format, "YBOS"))
          equipment[index].format = FORMAT_YBOS;
       else if (equal_ustring(eq_info->format, "FIXED"))
          equipment[index].format = FORMAT_FIXED;
       else                      /* default format is MIDAS */
          equipment[index].format = FORMAT_MIDAS;
       gethostname(eq_info->frontend_host, sizeof(eq_info->frontend_host));
       strcpy(eq_info->frontend_name, full_frontend_name);
       strcpy(eq_info->frontend_file_name, frontend_file_name);
       /* set record from equipment[] table in frontend.c */
       db_set_record(hDB, hKey, eq_info, sizeof(EQUIPMENT_INFO), 0);
       /* open hot link to equipment info */
       db_open_record(hDB, hKey, eq_info, sizeof(EQUIPMENT_INFO), MODE_READ, NULL, NULL);
     /*---- Create variables record ---------------------------------*/
       sprintf(str, "/Equipment/%s/Variables", equipment[index].name);
       if (equipment[index].event_descrip) {
          if (equipment[index].format == FORMAT_FIXED)
             db_check_record(hDB, 0, str, (char *) equipment[index].event_descrip, TRUE);
          else {
             /* create bank descriptions */
             bank_list = (BANK_LIST *) equipment[index].event_descrip;
             for (; bank_list->name[0]; bank_list++) {
                /* mabye needed later...
                   if (bank_list->output_flag == 0)
                   continue;
                 */
                if (bank_list->type == TID_STRUCT) {
                   sprintf(str, "/Equipment/%s/Variables/%s", equipment[index].name,
                           bank_list->name);
                   status =
                       db_check_record(hDB, 0, str, strcomb(bank_list->init_str), TRUE);
                   if (status != DB_SUCCESS) {
                      printf("Cannot check/create record \"%s\", status = %d\n", str,
                             status);
                      ss_sleep(3000);
                   }
                } else {
                   sprintf(str, "/Equipment/%s/Variables/%s", equipment[index].name,
                           bank_list->name);
                   dummy = 0;
                   db_set_value(hDB, 0, str, &dummy, rpc_tid_size(bank_list->type), 1,
                                bank_list->type);
                }
             }
          }
       } else
          db_create_key(hDB, 0, str, TID_KEY);
       sprintf(str, "/Equipment/%s/Variables", equipment[index].name);
       db_find_key(hDB, 0, str, &hKey);
       equipment[index].hkey_variables = hKey;
       /*---- Create and initialize statistics tree -------------------*/
       sprintf(str, "/Equipment/%s/Statistics", equipment[index].name);
       status = db_check_record(hDB, 0, str, EQUIPMENT_STATISTICS_STR, TRUE);
       if (status != DB_SUCCESS) {
          printf("Cannot create/check statistics record, error %d\n", status);
          ss_sleep(3000);
       }
       status = db_find_key(hDB, 0, str, &hKey);
       if (status != DB_SUCCESS) {
          printf("Cannot find statistics record, error %d\n", status);
          ss_sleep(3000);
       }
       eq_stats->events_sent = 0;
       eq_stats->events_per_sec = 0;
       eq_stats->kbytes_per_sec = 0;
       /* open hot link to statistics tree */
       status =
           db_open_record(hDB, hKey, eq_stats, sizeof(EQUIPMENT_STATS), MODE_WRITE, NULL,
                          NULL);
       if (status != DB_SUCCESS) {
          cm_msg(MERROR, "register_equipment",
              "Cannot open statistics record, error %d. Probably other FE is using it",
               status);
          ss_sleep(3000);
       }
       /*---- open event buffer ---------------------------------------*/
       if (eq_info->buffer[0]) {
          status =
              bm_open_buffer(eq_info->buffer, EVENT_BUFFER_SIZE,
                             &equipment[index].buffer_handle);
          if (status != BM_SUCCESS && status != BM_CREATED) {
             cm_msg(MERROR, "register_equipment",
                    "Cannot open event buffer. Try to reduce EVENT_BUFFER_SIZE in midas.h \
 and rebuild the system.");
             return 0;
          }
          /* set the default buffer cache size */
          bm_set_cache_size(equipment[index].buffer_handle, 0, SERVER_CACHE_SIZE);
       } else
          equipment[index].buffer_handle = 0;
     /*---- evaluate polling count ----------------------------------*/
       if (eq_info->eq_type & EQ_POLLED) {
          if (display_period)
             printf("\nCalibrating");
          count = 1;
          do {
             if (display_period)
                printf(".");
             start_time = ss_millitime();
             poll_event(equipment[index].info.source, count, TRUE);
             delta_time = ss_millitime() - start_time;
             if (delta_time > 0)
                count = (INT) ((double) count * 100 / delta_time);
             else
                count *= 100;
          } while (delta_time > 120 || delta_time < 80);
          equipment[index].poll_count = (INT) ((double) eq_info->period / 100 * count);
          if (display_period)
             printf("OK\n");
       }
     /*---- initialize interrupt events -----------------------------*/
       if (eq_info->eq_type & EQ_INTERRUPT) {
          /* install interrupt for interrupt events */
          for (i = 0; equipment[i].name[0]; i++)
             if (equipment[i].info.eq_type & EQ_POLLED) {
                equipment[index].status = FE_ERR_DISABLED;
                cm_msg(MINFO, "register_equipment",
                       "Interrupt readout cannot be combined with polled readout");
             }
          if (equipment[index].status != FE_ERR_DISABLED) {
             if (eq_info->enabled) {
                if (interrupt_eq) {
                   equipment[index].status = FE_ERR_DISABLED;
                   cm_msg(MINFO, "register_equipment",
                          "Defined more than one equipment with interrupt readout");
                } else {
                   interrupt_configure(CMD_INTERRUPT_ATTACH, eq_info->source,
                                       (PTYPE) interrupt_routine);
                   interrupt_eq = &equipment[index];
                   interrupt_odb_buffer = malloc(MAX_EVENT_SIZE + sizeof(EVENT_HEADER));
                }
             } else {
                equipment[index].status = FE_ERR_DISABLED;
                cm_msg(MINFO, "register_equipment",
                       "Equipment %s disabled in file \"frontend.c\"",
                       equipment[index].name);
             }
          }
       }
     /*---- initialize slow control equipment -----------------------*/
       if (eq_info->eq_type & EQ_SLOW) {
          /* resolve duplicate device names */
          for (i = 0; equipment[index].driver[i].name[0]; i++)
             for (j = i + 1; equipment[index].driver[j].name[0]; j++)
                if (equal_ustring(equipment[index].driver[i].name,
                                  equipment[index].driver[j].name)) {
                   strcpy(str, equipment[index].driver[i].name);
                   for (k = 0, n = 0; equipment[index].driver[k].name[0]; k++)
                      if (equal_ustring(str, equipment[index].driver[k].name))
                         sprintf(equipment[index].driver[k].name, "%s_%d", str, n++);
                   break;
                }
          /* loop over equipment list and call class driver's init method */
          if (eq_info->enabled)
             equipment[index].status = equipment[index].cd(CMD_INIT, &equipment[index]);
          else {
             equipment[index].status = FE_ERR_DISABLED;
             cm_msg(MINFO, "register_equipment",
                    "Equipment %s disabled in file \"frontend.c\"", equipment[index].name);
          }
          /* let user read error messages */
          if (equipment[index].status != FE_SUCCESS)
             ss_sleep(3000);
       }
       /*---- register callback for manual triggered events -----------*/
       if (eq_info->eq_type & EQ_MANUAL_TRIG) {
          if (!manual_trig_flag)
             cm_register_function(RPC_MANUAL_TRIG, manual_trigger);
          manual_trig_flag = TRUE;
       }
    }
    return SUCCESS;
 }
INT resume_run (INT run_number, char * error)
Definition at line 371 of file crate.cpp.
References SUCCESS.
Referenced by tr_resume().
 {
     return SUCCESS;
 }
INT scheduler (void)
Definition at line 1362 of file mfe_mucap.c.
References actual_millitime, actual_time, auto_restart, display(), display_period, eq, equipment, FALSE, fe_stop, frontend_call_loop, frontend_loop(), hDB, i, interrupt_enable(), interrupt_eq, interrupt_odb_buffer, interrupt_odb_buffer_valid, logger_root(), manual_trigger_event_id, MAX, max_bytes_per_sec, ODB_UPDATE_TIME, optimize, poll_event(), run_number, run_state, send_event(), SERVER_CACHE_SIZE, size, status, SUCCESS, TRUE, and update_odb().
 {
    EQUIPMENT_INFO *eq_info;
    EQUIPMENT *eq;
    EVENT_HEADER *pevent;
    DWORD last_time_network = 0, last_time_display = 0, last_time_flush = 0, readout_start;
    INT i, j, index, status, ch, source, size, state;
    char str[80];
    BOOL buffer_done, flag, force_update = FALSE;
    INT opt_max = 0, opt_index = 0, opt_tcp_size = 128, opt_cnt = 0;
    INT err;
 #ifdef OS_VXWORKS
    rpc_set_opt_tcp_size(1024);
 #ifdef PPCxxx
    rpc_set_opt_tcp_size(NET_TCP_SIZE);
 #endif
 #endif
    /*----------------- MAIN equipment loop ------------------------------*/
    do {
       actual_millitime = ss_millitime();
       actual_time = ss_time();
       /*---- loop over equipment table -------------------------------*/
       for (index = 0;; index++) {
          eq = &equipment[index];
          eq_info = &eq->info;
          /* check if end of equipment list */
          if (!eq->name[0])
             break;
          if (!eq_info->enabled)
             continue;
          if (eq->status != FE_SUCCESS)
             continue;
          /*---- call idle routine for slow control equipment ----*/
          if ((eq_info->eq_type & EQ_SLOW) && eq->status == FE_SUCCESS) {
             if (eq_info->event_limit > 0 && run_state == STATE_RUNNING) {
                if (actual_time - eq->last_idle >= (DWORD) eq_info->event_limit) {
                   eq->cd(CMD_IDLE, eq);
                   eq->last_idle = actual_time;
                }
             } else
                eq->cd(CMD_IDLE, eq);
          }
          if (run_state == STATE_STOPPED && (eq_info->read_on & RO_STOPPED) == 0)
             continue;
          if (run_state == STATE_PAUSED && (eq_info->read_on & RO_PAUSED) == 0)
             continue;
          if (run_state == STATE_RUNNING && (eq_info->read_on & RO_RUNNING) == 0)
             continue;
          /*---- check periodic events ----*/
          if ((eq_info->eq_type & EQ_PERIODIC) || (eq_info->eq_type & EQ_SLOW)) {
             if (eq_info->period == 0)
                continue;
             /* check if period over */
             if (actual_millitime - eq->last_called >= (DWORD) eq_info->period) {
                /* disable interrupts during readout */
                interrupt_enable(FALSE);
                /* readout and send event */
                status = send_event(index);
                if (status != CM_SUCCESS) {
                   cm_msg(MERROR, "scheduler", "send_event error %d", status);
                   goto net_error;
                }
                /* re-enable the interrupt after periodic */
                interrupt_enable(TRUE);
             }
          }
          /* end of periodic equipments */
          /*---- check polled events ----*/
          if (eq_info->eq_type & EQ_POLLED) {
             readout_start = actual_millitime;
             pevent = NULL;
             while ((source = poll_event(eq_info->source, eq->poll_count, FALSE)) > 0) {
                pevent = dm_pointer_get();
                if (pevent == NULL) {
                   cm_msg(MERROR, "scheduler",
                          "polled, dm_pointer_get not returning valid pointer");
                   status = SS_NO_MEMORY;
                   goto net_error;
                }
                /* compose MIDAS event header */
                pevent->event_id = eq_info->event_id;
                pevent->trigger_mask = eq_info->trigger_mask;
                pevent->data_size = 0;
                pevent->time_stamp = actual_time;
                pevent->serial_number = eq->serial_number;
                /* put source at beginning of event, will be overwritten by
                   user readout code, just a special feature used by some
                   multi-source applications */
                *(INT *) (pevent + 1) = source;
                if (eq->info.num_subevents) {
                   eq->subevent_number = 0;
                   do {
                      *(INT *) ((char *) (pevent + 1) + pevent->data_size) = source;
                      /* call user readout routine for subevent indicating offset */
                      size = eq->readout((char *) (pevent + 1), pevent->data_size);
                      pevent->data_size += size;
                      if (size > 0) {
                         if (pevent->data_size + sizeof(EVENT_HEADER) >
                             (DWORD) max_event_size) {
                            cm_msg(MERROR, "scheduler",
                                   "Event size %ld larger than maximum size %d",
                                   (long) (pevent->data_size + sizeof(EVENT_HEADER)),
                                   max_event_size);
                         }
                         eq->subevent_number++;
                         eq->serial_number++;
                      }
                      /* wait for next event */
                      do {
                         source = poll_event(eq_info->source, eq->poll_count, FALSE);
                         if (source == FALSE) {
                            actual_millitime = ss_millitime();
                            /* repeat no more than period */
                            if (actual_millitime - readout_start > (DWORD) eq_info->period)
                               break;
                         }
                      } while (source == FALSE);
                   } while (eq->subevent_number < eq->info.num_subevents && source);
                   /* notify readout routine about end of super-event */
                   pevent->data_size = eq->readout((char *) (pevent + 1), -1);
                } else {
                   /* call user readout routine indicating event source */
                   pevent->data_size = eq->readout((char *) (pevent + 1), 0);
                   /* check event size */
                   if (pevent->data_size + sizeof(EVENT_HEADER) > (DWORD) max_event_size) {
                      cm_msg(MERROR, "scheduler",
                             "Event size %ld larger than maximum size %d",
                             (long) (pevent->data_size + sizeof(EVENT_HEADER)),
                             max_event_size);
                   }
                   /* increment serial number if event read out sucessfully */
                   if (pevent->data_size)
                      eq->serial_number++;
                }
                /* send event */
                if (pevent->data_size) {
                   if (eq->buffer_handle) {
                      /* send first event to ODB if logger writes in root format */
                      if (pevent->serial_number == 1)
                         if (logger_root())
                            update_odb(pevent, eq->hkey_variables, eq->format);
 #ifdef USE_EVENT_CHANNEL
                      dm_pointer_increment(eq->buffer_handle,
                                           pevent->data_size + sizeof(EVENT_HEADER));
 #else
                      status = rpc_send_event(eq->buffer_handle, pevent,
                                              pevent->data_size + sizeof(EVENT_HEADER),
                                              SYNC);
                      if (status != SUCCESS) {
                         cm_msg(MERROR, "scheduler", "rpc_send_event error %d", status);
                         goto net_error;
                      }
 #endif
                      eq->bytes_sent += pevent->data_size + sizeof(EVENT_HEADER);
                      if (eq->info.num_subevents)
                         eq->events_sent += eq->subevent_number;
                      else
                         eq->events_sent++;
                   }
                }
                actual_millitime = ss_millitime();
                /* repeat no more than period */
                if (actual_millitime - readout_start > (DWORD) eq_info->period)
                   break;
                /* quit if event limit is reached */
                if (eq_info->event_limit > 0 &&
                    eq->stats.events_sent + eq->events_sent >= eq_info->event_limit)
                   break;
             }
             /* send event to ODB */
             if (pevent && (eq_info->read_on & RO_ODB || eq_info->history)) {
                if (actual_millitime - eq->last_called > ODB_UPDATE_TIME && pevent != NULL) {
                   eq->last_called = actual_millitime;
                   update_odb(pevent, eq->hkey_variables, eq->format);
                   eq->odb_out++;
                }
             }
          }
          /*---- send interrupt events ----*/
          if (eq_info->eq_type & EQ_INTERRUPT) {
             /* not much to do as work being done independently in interrupt_routine() */
             /* update ODB */
             if (interrupt_odb_buffer_valid) {
                update_odb(interrupt_odb_buffer, interrupt_eq->hkey_variables,
                           interrupt_eq->format);
                interrupt_odb_buffer_valid = FALSE;
             }
          }
          /*---- check if event limit is reached ----*/
          if (eq_info->eq_type != EQ_SLOW &&
              eq_info->event_limit > 0 &&
              eq->stats.events_sent + eq->events_sent >= eq_info->event_limit &&
              run_state == STATE_RUNNING) {
             /* stop run */
             if (cm_transition(TR_STOP, 0, str, sizeof(str), SYNC, FALSE) != CM_SUCCESS)
                cm_msg(MERROR, "scheduler", "cannot stop run: %s", str);
             /* check if autorestart, main loop will take care of it */
             size = sizeof(BOOL);
             flag = FALSE;
             db_get_value(hDB, 0, "/Logger/Auto restart", &flag, &size, TID_BOOL, TRUE);
             if (flag)
                auto_restart = ss_time() + 20;   /* restart in 20 sec. */
             /* update event display correctly */
             force_update = TRUE;
          }
       }
       /*---- call frontend_loop periodically -------------------------*/
       if (frontend_call_loop) {
          status = frontend_loop();
          if (status != CM_SUCCESS)
             status = RPC_SHUTDOWN;
       }
       /*---- check for deferred transitions --------------------------*/
       cm_check_deferred_transition();
       /*---- check for manual triggered events -----------------------*/
       if (manual_trigger_event_id) {
          interrupt_enable(FALSE);
          /* readout and send event */
          status = BM_INVALID_PARAM;
          for (i = 0; equipment[i].name[0]; i++)
             if (equipment[i].info.event_id == manual_trigger_event_id) {
                status = send_event(i);
                break;
             }
          manual_trigger_event_id = 0;
          if (status != CM_SUCCESS) {
             cm_msg(MERROR, "scheduler", "send_event error %d", status);
             goto net_error;
          }
          /* re-enable the interrupt after periodic */
          interrupt_enable(TRUE);
       }
       /*---- calculate rates and update status page periodically -----*/
       if (force_update ||
           (display_period
            && actual_millitime - last_time_display > (DWORD) display_period)
           || (!display_period && actual_millitime - last_time_display > 3000)) {
          force_update = FALSE;
          /* calculate rates */
          if (actual_millitime != last_time_display) {
             max_bytes_per_sec = 0;
             for (i = 0; equipment[i].name[0]; i++) {
                eq = &equipment[i];
                eq->stats.events_sent += eq->events_sent;
                eq->stats.events_per_sec =
                    eq->events_sent / ((actual_millitime - last_time_display) / 1000.0);
                eq->stats.kbytes_per_sec =
                    eq->bytes_sent / 1024.0 / ((actual_millitime - last_time_display) /
                                               1000.0);
                if ((INT) eq->bytes_sent > max_bytes_per_sec)
                   max_bytes_per_sec = eq->bytes_sent;
                eq->bytes_sent = 0;
                eq->events_sent = 0;
             }
             max_bytes_per_sec = (DWORD)
                 ((double) max_bytes_per_sec /
                  ((actual_millitime - last_time_display) / 1000.0));
             /* tcp buffer size evaluation */
             if (optimize) {
                opt_max = MAX(opt_max, (INT) max_bytes_per_sec);
                ss_printf(0, opt_index, "%6d : %5.1lf %5.1lf", opt_tcp_size,
                          opt_max / 1024.0, max_bytes_per_sec / 1024.0);
                if (++opt_cnt == 10) {
                   opt_cnt = 0;
                   opt_max = 0;
                   opt_index++;
                   opt_tcp_size = 1 << (opt_index + 7);
                   rpc_set_opt_tcp_size(opt_tcp_size);
                   if (1 << (opt_index + 7) > 0x8000) {
                      opt_index = 0;
                      opt_tcp_size = 1 << 7;
                      rpc_set_opt_tcp_size(opt_tcp_size);
                   }
                }
             }
          }
          /* propagate changes in equipment to ODB */
          rpc_set_option(-1, RPC_OTRANSPORT, RPC_FTCP);
          db_send_changed_records();
          rpc_set_option(-1, RPC_OTRANSPORT, RPC_TCP);
          if (display_period) {
             display(FALSE);
             /* check keyboard */
             ch = 0;
             status = 0;
             while (ss_kbhit()) {
                ch = ss_getchar(0);
                if (ch == -1)
                   ch = getchar();
                if (ch == '!')
                   status = RPC_SHUTDOWN;
             }
             if (ch > 0)
                display(TRUE);
             if (status == RPC_SHUTDOWN)
                break;
          }
          last_time_display = actual_millitime;
       }
       /*---- check to flush cache ------------------------------------*/
       if (actual_millitime - last_time_flush > 1000) {
          last_time_flush = actual_millitime;
          /* if cache on server is not filled in one second at current
             data rate, flush it now to make events available to consumers */
          if (max_bytes_per_sec < SERVER_CACHE_SIZE) {
             interrupt_enable(FALSE);
 #ifdef USE_EVENT_CHANNEL
             if ((status = dm_area_flush()) != CM_SUCCESS)
                cm_msg(MERROR, "scheduler", "dm_area_flush: %i", status);
 #endif
             for (i = 0; equipment[i].name[0]; i++) {
                if (equipment[i].buffer_handle) {
                   /* check if buffer already flushed */
                   buffer_done = FALSE;
                   for (j = 0; j < i; j++)
                      if (equipment[i].buffer_handle == equipment[j].buffer_handle) {
                         buffer_done = TRUE;
                         break;
                      }
                   if (!buffer_done) {
                      rpc_set_option(-1, RPC_OTRANSPORT, RPC_FTCP);
                      rpc_flush_event();
                      err = bm_flush_cache(equipment[i].buffer_handle, ASYNC);
                      if (err != BM_SUCCESS) {
                         cm_msg(MERROR, "scheduler", "bm_flush_cache(ASYNC) error %d",
                                err);
                         return err;
                      }
                      rpc_set_option(-1, RPC_OTRANSPORT, RPC_TCP);
                   }
                }
             }
             interrupt_enable(TRUE);
          }
       }
       /*---- check for auto restart --------------------------------*/
       if (auto_restart > 0 && ss_time() > auto_restart) {
          /* check if really stopped */
          size = sizeof(state);
          status = db_get_value(hDB, 0, "Runinfo/State", &state, &size, TID_INT, TRUE);
          if (status != DB_SUCCESS)
             cm_msg(MERROR, "scheduler", "cannot get Runinfo/State in database");
          if (state == STATE_STOPPED) {
             auto_restart = 0;
             size = sizeof(run_number);
             status =
                 db_get_value(hDB, 0, "/Runinfo/Run number", &run_number, &size, TID_INT,
                              TRUE);
             assert(status == SUCCESS);
             if (run_number <= 0) {
                cm_msg(MERROR, "main", "aborting on attempt to use invalid run number %d",
                       run_number);
                abort();
             }
             cm_msg(MTALK, "main", "starting new run");
             status = cm_transition(TR_START, run_number + 1, NULL, 0, SYNC, FALSE);
             if (status != CM_SUCCESS)
                cm_msg(MERROR, "main", "cannot restart run");
          }
       }
       /*---- check network messages ----------------------------------*/
       if (run_state == STATE_RUNNING && interrupt_eq == NULL) {
          /* only call yield once every 100ms when running */
          if (actual_millitime - last_time_network > 100) {
             status = cm_yield(0);
             last_time_network = actual_millitime;
          } else
             status = RPC_SUCCESS;
       } else
          /* when run is stopped or interrupts used,
             call yield with 100ms timeout */
          status = cm_yield(100);
       /* exit for VxWorks */
       if (fe_stop)
          status = RPC_SHUTDOWN;
    } while (status != RPC_SHUTDOWN && status != SS_ABORT);
  net_error:
    return status;
 }
void send_all_periodic_events (INT transition)
int send_event (INT index)
INT tr_pause (INT rn, char * error)
Definition at line 471 of file mfe_mucap.c.
References display_period, FALSE, interrupt_enable(), pause_run(), run_number, run_state, send_all_periodic_events(), status, and TRUE.
Referenced by main().
 {
    INT status;
    /* disable interrupts */
    interrupt_enable(FALSE);
    status = pause_run(rn, error);
    if (status == CM_SUCCESS) {
       run_state = STATE_PAUSED;
       run_number = rn;
       send_all_periodic_events(TR_PAUSE);
       if (display_period)
          ss_printf(14, 2, "Paused  ");
    } else
       interrupt_enable(TRUE);
    return status;
 }
INT tr_resume (INT rn, char * error)
Definition at line 496 of file mfe_mucap.c.
References display_period, interrupt_enable(), resume_run(), run_number, run_state, send_all_periodic_events(), status, and TRUE.
 {
    INT status;
    status = resume_run(rn, error);
    if (status == CM_SUCCESS) {
       run_state = STATE_RUNNING;
       run_number = rn;
       send_all_periodic_events(TR_RESUME);
       if (display_period)
          ss_printf(14, 2, "Running ");
       /* enable interrupts */
       interrupt_enable(TRUE);
    }
    return status;
 }
INT tr_start (INT rn, char * error)
Definition at line 388 of file mfe_mucap.c.
References begin_of_run(), display_period, equipment, i, interrupt_enable(), run_number, run_state, send_all_periodic_events(), status, and TRUE.
 {
    INT i, status;
    /* reset serial numbers */
    for (i = 0; equipment[i].name[0]; i++) {
       equipment[i].serial_number = 1;
       equipment[i].subevent_number = 0;
       equipment[i].stats.events_sent = 0;
       equipment[i].odb_in = equipment[i].odb_out = 0;
    }
    status = begin_of_run(rn, error);
    if (status == CM_SUCCESS) {
       run_state = STATE_RUNNING;
       run_number = rn;
       send_all_periodic_events(TR_START);
       if (display_period) {
          ss_printf(14, 2, "Running ");
          ss_printf(36, 2, "%d", rn);
       }
       /* enable interrupts */
       interrupt_enable(TRUE);
    }
    return status;
 }
INT tr_stop (INT rn, char * error)
Definition at line 422 of file mfe_mucap.c.
References display_period, end_of_run(), eq, equipment, FALSE, i, interrupt_enable(), run_number, run_state, send_all_periodic_events(), status, and TRUE.
 {
    INT status, i;
    EQUIPMENT *eq;
    /* disable interrupts */
    interrupt_enable(FALSE);
    status = end_of_run(rn, error);
    if (status == CM_SUCCESS) {
       /* don't send events if already stopped */
       if (run_state != STATE_STOPPED)
          send_all_periodic_events(TR_STOP);
       run_state = STATE_STOPPED;
       run_number = rn;
       if (display_period)
          ss_printf(14, 2, "Stopped ");
    } else
       interrupt_enable(TRUE);
    /* flush remaining buffered events */
    rpc_flush_event();
    for (i = 0; equipment[i].name[0]; i++)
       if (equipment[i].buffer_handle) {
          INT err = bm_flush_cache(equipment[i].buffer_handle, SYNC);
          if (err != BM_SUCCESS) {
             cm_msg(MERROR, "tr_prestop", "bm_flush_cache(SYNC) error %d", err);
             return err;
          }
       }
    /* update final statistics record in ODB */
    for (i = 0; equipment[i].name[0]; i++) {
       eq = &equipment[i];
       eq->stats.events_sent += eq->events_sent;
       eq->bytes_sent = 0;
       eq->events_sent = 0;
    }
    db_send_changed_records();
    return status;
 }
void update_odb (EVENT_HEADER * pevent, HNDLE hKey, INT format)
Definition at line 812 of file mfe_mucap.c.
References hDB, i, key, MIN, printf(), size, and status.
 {
    INT size, i, ni4, tsize, status, n_data;
    void *pdata;
    char name[5];
    BANK_HEADER *pbh;
    BANK *pbk;
    BANK32 *pbk32;
    void *pydata;
    DWORD odb_type;
    DWORD *pyevt, bkname;
    WORD bktype;
    HNDLE hKeyRoot, hKeyl;
    KEY key;
    /* outcommented sind db_find_key does not work in FTCP mode, SR 25.4.03
       rpc_set_option(-1, RPC_OTRANSPORT, RPC_FTCP); */
    if (format == FORMAT_FIXED) {
       if (db_set_record(hDB, hKey, (char *) (pevent + 1),
                         pevent->data_size, 0) != DB_SUCCESS)
          cm_msg(MERROR, "update_odb", "event #%d size mismatch", pevent->event_id);
    } else if (format == FORMAT_MIDAS) {
       pbh = (BANK_HEADER *) (pevent + 1);
       pbk = NULL;
       pbk32 = NULL;
       do {
          /* scan all banks */
          if (bk_is32(pbh)) {
             size = bk_iterate32(pbh, &pbk32, &pdata);
             if (pbk32 == NULL)
                break;
             bkname = *((DWORD *) pbk32->name);
             bktype = (WORD) pbk32->type;
          } else {
             size = bk_iterate(pbh, &pbk, &pdata);
             if (pbk == NULL)
                break;
             bkname = *((DWORD *) pbk->name);
             bktype = (WORD) pbk->type;
          }
          n_data = size;
          if (rpc_tid_size(bktype & 0xFF))
             n_data /= rpc_tid_size(bktype & 0xFF);
          /* get bank key */
          *((DWORD *) name) = bkname;
          name[4] = 0;
          if (bktype == TID_STRUCT) {
             status = db_find_key(hDB, hKey, name, &hKeyRoot);
             if (status != DB_SUCCESS) {
                cm_msg(MERROR, "update_odb",
                       "please define bank %s in BANK_LIST in frontend.c", name);
                continue;
             }
             /* write structured bank */
             for (i = 0;; i++) {
                status = db_enum_key(hDB, hKeyRoot, i, &hKeyl);
                if (status == DB_NO_MORE_SUBKEYS)
                   break;
                db_get_key(hDB, hKeyl, &key);
                /* adjust for alignment */
                if (key.type != TID_STRING && key.type != TID_LINK)
                   pdata =
                       (void *) VALIGN(pdata, MIN(ss_get_struct_align(), key.item_size));
                status = db_set_data(hDB, hKeyl, pdata, key.item_size * key.num_values,
                                     key.num_values, key.type);
                if (status != DB_SUCCESS) {
                   cm_msg(MERROR, "update_odb", "cannot write %s to ODB", name);
                   continue;
                }
                /* shift data pointer to next item */
                pdata = (char *) pdata + key.item_size * key.num_values;
             }
          } else {
             /* write variable length bank  */
             if (n_data > 0)
                db_set_value(hDB, hKey, name, pdata, size, n_data, bktype & 0xFF);
          }
       } while (1);
    } else if (format == FORMAT_YBOS) {
 #ifdef YBOS_SUPPORT
       YBOS_BANK_HEADER *pybkh;
       /* skip the lrl (4 bytes per event) */
       pyevt = (DWORD *) (pevent + 1);
       pybkh = NULL;
       do {
          /* scan all banks */
          ni4 = ybk_iterate(pyevt, &pybkh, &pydata);
          if (pybkh == NULL || ni4 == 0)
             break;
          /* find the corresponding odb type */
          tsize = odb_type = 0;
          for (i = 0; id_map[0].ybos_type > 0; i++) {
             if (pybkh->type == id_map[i].ybos_type) {
                odb_type = id_map[i].odb_type;
                tsize = id_map[i].tsize;
                break;
             }
          }
          /* extract bank name (key name) */
          *((DWORD *) name) = pybkh->name;
          name[4] = 0;
          /* reject EVID bank */
          if (strncmp(name, "EVID", 4) == 0)
             continue;
          /* correct YBS number of entries */
          if (pybkh->type == D8_BKTYPE)
             ni4 /= 2;
          if (pybkh->type == I2_BKTYPE)
             ni4 *= 2;
          if (pybkh->type == I1_BKTYPE || pybkh->type == A1_BKTYPE)
             ni4 *= 4;
          /* write bank to ODB, ni4 always in I*4 */
          size = ni4 * tsize;
          if ((status =
               db_set_value(hDB, hKey, name, pydata, size, ni4,
                            odb_type & 0xFF)) != DB_SUCCESS) {
             printf("status:%i odb_type:%li name:%s ni4:%i size:%i tsize:%i\n", status,
                    odb_type, name, ni4, size, tsize);
             for (i = 0; i < 6; i++) {
                float * fpydata = (float *) pydata;
                printf("data: %f\n", *(fpydata)++);
             }
          }
       } while (1);
 #endif                          /* YBOS_SUPPORT */
    }
    rpc_set_option(-1, RPC_OTRANSPORT, RPC_TCP);
 }
Variable Documentation
DWORD actual_millitime
Definition at line 302 of file mfe_mucap.c.
DWORD actual_time
Definition at line 301 of file mfe_mucap.c.
DWORD auto_restart = 0
Definition at line 312 of file mfe_mucap.c.
int crate_number
Definition at line 139 of file crate.cpp.
Referenced by caenV767_bor(), caenV767_bor1(), caenV767_pre_bor(), crate_is_participating(), diag_print_setup(), dl401_bor1(), dl403_init(), dl40x_bor(), dt5720_init(), frontend_early_init(), lrs2249_bor(), lrs2249_bor1(), main(), rpc_master_bor(), rpc_master_eor(), rpc_master_init(), rpc_master_poll_dead(), rpc_master_read(), rpc_ready_for_cycle(), rpc_request_stop(), rpc_slave_bor(), rpc_slave_stop_block(), s500_bor(), s500_bor1(), send_ready_for_cycle(), setupRegs(), sis3600_bor(), sis3600_bor1(), v1724_init(), and vmic_ttl_init().
BOOL debug
Definition at line 311 of file mfe_mucap.c.
INT display_period
Definition at line 43 of file crate.cpp.
EQUIPMENT equipment[]
Definition at line 72 of file crate.cpp.
INT event_buffer_size
Definition at line 53 of file crate.cpp.
char exp_name[NAME_LENGTH]
Definition at line 305 of file mfe_mucap.c.
INT fe_stop = 0
Definition at line 310 of file mfe_mucap.c.
BOOL frontend_call_loop
Definition at line 39 of file crate.cpp.
char* frontend_file_name
Definition at line 36 of file crate.cpp.
INT frontend_index = -1
Definition at line 314 of file mfe_mucap.c.
Referenced by frontend_early_init(), get_frontend_index(), main(), and register_equipment().
char* frontend_name
Definition at line 33 of file crate.cpp.
char full_frontend_name[256]
Definition at line 306 of file mfe_mucap.c.
Referenced by load_fragment(), main(), register_equipment(), scan_fragment(), source_scan(), tr_start(), and tr_stop().
HNDLE hDB
Definition at line 316 of file mfe_mucap.c.
char host_name[HOST_NAME_LENGTH]
Definition at line 304 of file mfe_mucap.c.
BOOL interrupt_enabled
Definition at line 1179 of file mfe_mucap.c.
EQUIPMENT* interrupt_eq = NULL
Definition at line 337 of file mfe_mucap.c.
EVENT_HEADER* interrupt_odb_buffer
Definition at line 338 of file mfe_mucap.c.
BOOL interrupt_odb_buffer_valid
Definition at line 339 of file mfe_mucap.c.
INT manual_trigger_event_id = 0
Definition at line 313 of file mfe_mucap.c.
Referenced by manual_trigger(), and scheduler().
INT max_bytes_per_sec
Definition at line 308 of file mfe_mucap.c.
INT max_event_size
Definition at line 47 of file crate.cpp.
INT max_event_size_frag
Definition at line 50 of file crate.cpp.
INT optimize = 0
Definition at line 309 of file mfe_mucap.c.
INT run_number
Definition at line 300 of file mfe_mucap.c.
INT run_state
PROGRAM: crate.cpp DESCRIPTION: Control and readout of CAEN V1724 digitizers. author: V.Tishchenko date: 12-Aug-2012
Modifications:
Definition at line 299 of file mfe_mucap.c.