AlcapDAQ: crate6_CAEN_TDC/s500.cpp File Reference
s500.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <time.h>
#include "midas.h"
#include "crate.h"
#include "mcstd.h"
#include "odb_wrapper.h"
#include "diag.h"
Data Structures
struct s500
Macros
#define N_CH_S500 6
#define MAX_S500 8
Functions
INT s500_bor ()
INT s500_read (char *pevent)
INT s500_bor1 (struct s500 *s500)
Variables
struct readout_module s500_module
struct s500 s500 [MAX_S500]
Macro Definition Documentation
#define MAX_S500 8
Definition at line 41 of file s500.cpp.
Referenced by s500_bor(), and s500_read().
#define N_CH_S500 6
Definition at line 31 of file s500.cpp.
Referenced by s500_bor1(), and s500_read().
Function Documentation
INT s500_bor ()
Definition at line 76 of file s500.cpp.
References crate_number, diag_print(), enabled, s500::enabled, MAX_S500, odb_find_key(), odb_get_bool(), s500::odb_name, s500_bor1(), sprintf(), and SUCCESS.
 {
   // Use the ODB to find any S500 modules
   for(int j = 0; j < MAX_S500; j++) {
     bool enabled = false;
     if (odb_find_key("/Equipment/Crate %d/Settings/S500 %d", crate_number, j)) {
       diag_print(1, "ODB says S500 %d is present, ", j);
       enabled =
         odb_get_bool("/Equipment/Crate %d/Settings/S500 %d/enabled status",
             crate_number, j);
       if (enabled) {
         diag_print(1, "and is enabled.  Initializing...\n");
       } else {
         diag_print(1, "but is disabled.\n");
       }
     }
     s500[j].enabled = enabled;
     // Set up the name of the MIDAS bank associated with the module
     sprintf(s500[j].odb_name, "S500 %d", j);
     if(enabled) {
       s500_bor1(&s500[j]);
     }
   }
   return SUCCESS;
 }
INT s500_bor1 (struct s500 * s500)
Definition at line 49 of file s500.cpp.
References s500::acum, camo(), s500::crate, crate_number, i, N_CH_S500, odb_get_int(), s500::odb_name, s500::slot, and SUCCESS.
Referenced by s500_bor().
 {
   // Get the VME base address of the module
   s500->crate = odb_get_int("/Equipment/Crate %d/Settings/%s/Crate",
                     crate_number, s500->odb_name);
   s500->slot = odb_get_int("/Equipment/Crate %d/Settings/%s/Slot",
                     crate_number, s500->odb_name);
   // clear all channels
   for(int i = 0; i < N_CH_S500; i++) {
     camo(s500->crate, s500->slot, i, 9, 0);
   }
   // clear the accumulated values
   for(int i = 0; i < N_CH_S500; i++) {
     s500->acum[i] = 0;
   }
   return SUCCESS;
 }
INT s500_read (char * pevent)
Definition at line 114 of file s500.cpp.
References s500::acum, cam24i(), crate, enabled, i, MAX_S500, N_CH_S500, s500::slot, and SUCCESS.
 {
   DWORD *pdata;
   // first fill in the raw values
   bk_create(pevent, "S500", TID_DWORD, &pdata);
   for(int i = 0; i < MAX_S500; i++) {
     if(s500[i].enabled) {
       for(int j = 0; j < N_CH_S500; j++) {
         DWORD val;
         cam24i(s500[i].crate, s500[i].slot, j, 2, &val);
         *pdata++ = val;
         s500[i].acum[j] += val;
       }
     }
   }
   bk_close(pevent, pdata);
   // now the accumulated values
   bk_create(pevent, "ACUM", TID_DWORD, &pdata);
   for(int i = 0; i < MAX_S500; i++) {
     if(s500[i].enabled) {
       for(int j = 0; j < N_CH_S500; j++) {
         *pdata++ = s500[i].acum[j];
       }
     }
   }
   bk_close(pevent, pdata);
   return SUCCESS;
 }
Variable Documentation
struct s500 s500[MAX_S500]
Definition at line 42 of file s500.cpp.
struct readout_module s500_module
Initial value:
= {
  NULL,
  NULL,
  NULL,
  s500_bor,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  s500_read,
}
Definition at line 18 of file s500.cpp.