AlcapDAQ: CAEN/CAENUpgrader-1.4.1/cvUpgrade/include/flash.h File Reference
flash.h File Reference
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdint.h>
#include <CAENComm.h>
Data Structures
struct CROM_MAP
struct FlashAccess
Macros
#define Wait_ms(t) usleep((t)*1000)
#define CAENCOM_INVALID_FILE_HANDLE -1
#define MAIN_MEM_PAGE_READ_CMD 0xD2
#define MAIN_MEM_PAGE_PROG_TH_BUF1_CMD 0x82
#define STATUS_READ_CMD 0xD7
#define ROM_FLASH_PAGE 0
#define LICENSE_FLASH_PAGE 2
#define KEY_SIZE 64
#define LICENSE_DATA_SIZE 8
#define MAX_MULTIACCESS_BUFSIZE 2048
Typedefs
typedef enum AT45_OPCODES AT45_OPCODES
typedef struct CROM_MAP CROM_MAP
typedef struct FlashAccess cvFlashAccess
typedef enum cvupgrade_ErrorCode cvupgrade_ErrorCode
Enumerations
enum AT45_OPCODES {
AT45_PAGE_SIZE = 264, AT45_IDREG_LENGTH = 128, AT45_MAIN_MEM_PAGE_READ_OPCODE = 0x00D2, AT45_MAIN_MEM_PAGE_PROG_TH_BUF1_OPCODE = 0x0082,
AT45_READ_SECURITY_REGISTER_OPCODE = 0x0077, AT45_STATUS_READ_CMD_OPCODE = 0x00D7, AT45_PAGE_SIZE = 264, AT45_IDREG_LENGTH = 128,
AT45_MAIN_MEM_PAGE_READ_OPCODE = 0x00D2, AT45_MAIN_MEM_PAGE_PROG_TH_BUF1_OPCODE = 0x0082, AT45_READ_SECURITY_REGISTER_OPCODE = 0x0077, AT45_STATUS_READ_CMD_OPCODE = 0x00D7
}
enum cvupgrade_ErrorCode {
CvUpgrade_Success = 0, CvUpgrade_GenericError = -1, CvUpgrade_CAENCommError = -2, CvUpgrade_UnsupportedRegSize = -3,
CvUpgrade_FileAccessError = -4, CvUpgrade_Success = 0, CvUpgrade_GenericError = -1, CvUpgrade_CAENCommError = -2,
CvUpgrade_UnsupportedRegSize = -3, CvUpgrade_FileAccessError = -4
}
Functions
int ReadFlashPage (cvFlashAccess *Flash, uint8_t *data, int pagenum)
int WriteFlashPage (cvFlashAccess *Flash, uint8_t *data, int pagenum)
int ReadFlashSecurityReg (cvFlashAccess *Flash, uint8_t *data)
Macro Definition Documentation
#define CAENCOM_INVALID_FILE_HANDLE -1
Definition at line 26 of file flash.h.
#define KEY_SIZE 64
Definition at line 34 of file flash.h.
#define LICENSE_DATA_SIZE 8
Definition at line 35 of file flash.h.
#define LICENSE_FLASH_PAGE 2
Definition at line 33 of file flash.h.
#define MAIN_MEM_PAGE_PROG_TH_BUF1_CMD 0x82
Definition at line 29 of file flash.h.
#define MAIN_MEM_PAGE_READ_CMD 0xD2
Definition at line 28 of file flash.h.
#define MAX_MULTIACCESS_BUFSIZE 2048
Definition at line 36 of file flash.h.
#define ROM_FLASH_PAGE 0
Definition at line 32 of file flash.h.
#define STATUS_READ_CMD 0xD7
Definition at line 30 of file flash.h.
#define Wait_ms (t) usleep((t)*1000)
Definition at line 23 of file flash.h.
Typedef Documentation
typedef enum AT45_OPCODES AT45_OPCODES
typedef struct CROM_MAP CROM_MAP
typedef struct FlashAccess cvFlashAccess
typedef enum cvupgrade_ErrorCode cvupgrade_ErrorCode
Enumeration Type Documentation
enum AT45_OPCODES
Enumerator
AT45_PAGE_SIZE
AT45_IDREG_LENGTH
AT45_MAIN_MEM_PAGE_READ_OPCODE
AT45_MAIN_MEM_PAGE_PROG_TH_BUF1_OPCODE
AT45_READ_SECURITY_REGISTER_OPCODE
AT45_STATUS_READ_CMD_OPCODE
AT45_PAGE_SIZE
AT45_IDREG_LENGTH
AT45_MAIN_MEM_PAGE_READ_OPCODE
AT45_MAIN_MEM_PAGE_PROG_TH_BUF1_OPCODE
AT45_READ_SECURITY_REGISTER_OPCODE
AT45_STATUS_READ_CMD_OPCODE
Definition at line 39 of file flash.h.
 {
   AT45_PAGE_SIZE                        =  264,    // Number of bytes per page in the target flash
   AT45_IDREG_LENGTH                     =  128,    // Lunghezza (in bytes) del registro ID della flash Atmel
   AT45_MAIN_MEM_PAGE_READ_OPCODE        =  0x00D2,
   AT45_MAIN_MEM_PAGE_PROG_TH_BUF1_OPCODE=  0x0082,
   AT45_READ_SECURITY_REGISTER_OPCODE    =  0x0077,
   AT45_STATUS_READ_CMD_OPCODE           =  0x00D7,
 } AT45_OPCODES;
enum cvupgrade_ErrorCode
Enumerator
CvUpgrade_Success
CvUpgrade_GenericError
CvUpgrade_CAENCommError
CvUpgrade_UnsupportedRegSize
CvUpgrade_FileAccessError
CvUpgrade_Success
CvUpgrade_GenericError
CvUpgrade_CAENCommError
CvUpgrade_UnsupportedRegSize
CvUpgrade_FileAccessError
Definition at line 75 of file flash.h.
{
 /* Error Types */
  CvUpgrade_Success                    =  0,     /* Operation completed successfully                     */
  CvUpgrade_GenericError       = -1,     /* Generic error                                                */
  CvUpgrade_CAENCommError      = -2,     /* CAENComm function call error                         */
  CvUpgrade_UnsupportedRegSize = -3,     /* Unsupported Register Size from parameter file        */
  CvUpgrade_FileAccessError    = -4      /* File access  error */
 } cvupgrade_ErrorCode;
Function Documentation
int ReadFlashPage (cvFlashAccess * Flash, uint8_t * data, int pagenum)
Definition at line 202 of file flash.c.
References CvUpgrade_FileAccessError, ReadFlashPage16(), ReadFlashPage32(), and FlashAccess::RegSize.
{
   int ret;
     ret = ReadFlashPage32(Flash, data, pagenum);
   return ret;
 }
int ReadFlashSecurityReg (cvFlashAccess * Flash, uint8_t * data)
Definition at line 217 of file flash.c.
References CvUpgrade_FileAccessError, ReadFlashSecurityReg16(), ReadFlashSecurityReg32(), and FlashAccess::RegSize.
{
   int ret;
     ret = ReadFlashSecurityReg32(Flash, data);
   return ret;
 }
int WriteFlashPage (cvFlashAccess * Flash, uint8_t * data, int pagenum)
Definition at line 186 of file flash.c.
References CvUpgrade_FileAccessError, FlashAccess::RegSize, WriteFlashPage16(), and WriteFlashPage32().
{
   int ret;
     ret = WriteFlashPage32(Flash, data, pagenum);
   return ret;
 }