AlcapDAQ: midas/drivers/device/das1600.h File Reference
midas/drivers/device/das1600.h File Reference
Functions
INT das1600_ai (INT cmd,...)
INT das1600_ao (INT cmd,...)
INT das1600_di (INT cmd,...)
INT das1600_do (INT cmd,...)
Function Documentation
INT das1600_ai (INT cmd, ...)
Definition at line 187 of file das1600.c.
References channel, CMD_GET, CMD_INIT, das1600_get_analog(), das1600_init(), DF_INPUT, FE_SUCCESS, hKey, and status.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   float *pvalue;
   void *info;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      status = das1600_init(hKey, info, channel, DF_INPUT);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = das1600_get_analog(info, channel, pvalue);
      break;
   default:
      break;
   }
   va_end(argptr);
   return status;
}
INT das1600_ao (INT cmd, ...)
Definition at line 224 of file das1600.c.
References channel, CMD_INIT, CMD_SET, das1600_init(), das1600_set_analog(), DF_OUTPUT, FE_SUCCESS, hKey, status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   float value;
   void *info;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      status = das1600_init(hKey, info, channel, DF_OUTPUT);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = das1600_set_analog(info, channel, value);
      break;
   default:
      break;
   }
   va_end(argptr);
   return status;
}
INT das1600_di (INT cmd, ...)
INT das1600_do (INT cmd, ...)