AlcapDAQ: midas/examples/basic/deferredfe.c File Reference
midas/examples/basic/deferredfe.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "midas.h"
#include "mcstd.h"
#include "experim.h"
Defines
#define N_ADC 4
#define N_TDC 8
#define N_SCLR 4
#define CRATE 0
#define SLOT_IO 23
#define SLOT_ADC 1
#define SLOT_TDC 2
#define SLOT_SCLR 3
Functions
INT frontend_init ()
INT frontend_exit ()
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
INT frontend_loop ()
INT read_deferred_event (char *pevent, INT off)
ADC0_BANK_STR (adc0_bank_str)
BOOL wait_end_cycle (int transition, BOOL first)
INT poll_event (INT source, INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Variables
char * frontend_name = "deferredfe"
char * frontend_file_name = __FILE__
BOOL frontend_call_loop = FALSE
INT display_period = 000
INT max_event_size = 10000
INT max_event_size_frag = 5 * 1024 * 1024
INT event_buffer_size = 10 * 10000
BANK_LIST trigger_bank_list []
BANK_LIST scaler_bank_list []
EQUIPMENT equipment []
int pseudo_delay = 0
BOOL transition_PS_requested = FALSE
BOOL end_of_mcs_cycle = FALSE
Define Documentation
#define CRATE 0
Definition at line 106 of file deferredfe.c.
Referenced by frontend_init(), interrupt_configure(), read_deferred_event(), read_mantrig_event(), read_scaler_event(), and read_trigger_event().
#define N_ADC 4
Definition at line 101 of file deferredfe.c.
Referenced by adc_calib(), adc_calib_init(), analyze_trigger_event(), analyzer_init(), and read_trigger_event().
#define N_SCLR 4
Definition at line 103 of file deferredfe.c.
Referenced by read_deferred_event(), read_mantrig_event(), and read_scaler_event().
#define N_TDC 8
Definition at line 102 of file deferredfe.c.
Referenced by analyze_trigger_event(), analyzer_init(), and read_trigger_event().
#define SLOT_ADC 1
Definition at line 108 of file deferredfe.c.
Referenced by read_trigger_event().
#define SLOT_IO 23
Definition at line 107 of file deferredfe.c.
Referenced by frontend_init(), and read_trigger_event().
#define SLOT_SCLR 3
Definition at line 110 of file deferredfe.c.
Referenced by read_deferred_event(), read_mantrig_event(), and read_scaler_event().
#define SLOT_TDC 2
Definition at line 109 of file deferredfe.c.
Referenced by read_trigger_event().
Function Documentation
ADC0_BANK_STR (adc0_bank_str)
INT begin_of_run (INT run_number, char * error)
Definition at line 281 of file deferredfe.c.
References SUCCESS.
{
   /* put here clear scalers etc. */
   pseudo_delay = 0;
   return SUCCESS;
}
INT end_of_run (INT run_number, char * error)
Definition at line 290 of file deferredfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_exit (void)
Definition at line 274 of file deferredfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_init (void)
Definition at line 243 of file deferredfe.c.
References cam_crate_clear(), cam_crate_zinit(), cam_init(), cam_lam_enable(), camc(), camo(), cm_register_deferred_transition(), CRATE, SLOT_IO, SUCCESS, TR_PAUSE, TR_STOP, and wait_end_cycle().
{
   // register for deferred transition
   cm_register_deferred_transition(TR_STOP, wait_end_cycle);
   cm_register_deferred_transition(TR_PAUSE, wait_end_cycle);
   /* hardware initialization */
   cam_init();
   cam_crate_clear(CRATE);
   cam_crate_zinit(CRATE);
   /* enable LAM in IO unit */
   camc(CRATE, SLOT_IO, 0, 26);
   /* enable LAM in crate controller */
   cam_lam_enable(CRATE, SLOT_IO);
   /* reset external LAM Flip-Flop */
   camo(CRATE, SLOT_IO, 1, 16, 0xFF);
   camo(CRATE, SLOT_IO, 1, 16, 0);
   /* print message and return FE_ERR_HW if frontend should not be started */
   return SUCCESS;
}
INT frontend_loop (void)
Definition at line 311 of file deferredfe.c.
References SUCCESS.
{
   /* if frontend_call_loop is true, this routine gets called when
      the frontend is idle or once between every event */
   return SUCCESS;
}
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Definition at line 349 of file deferredfe.c.
References CMD_INTERRUPT_ATTACH, CMD_INTERRUPT_DETACH, CMD_INTERRUPT_DISABLE, CMD_INTERRUPT_ENABLE, and SUCCESS.
{
   switch (cmd) {
   case CMD_INTERRUPT_ENABLE:
      break;
   case CMD_INTERRUPT_DISABLE:
      break;
   case CMD_INTERRUPT_ATTACH:
      break;
   case CMD_INTERRUPT_DETACH:
      break;
   }
   return SUCCESS;
}
INT pause_run (INT run_number, char * error)
Definition at line 297 of file deferredfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT poll_event (INT source, INT count, BOOL test)
Definition at line 328 of file deferredfe.c.
References cam_lam_read(), i, LAM_SOURCE_CRATE, and LAM_SOURCE_STATION.
{
   int i;
   DWORD lam;
   for (i = 0; i < count; i++) {
      cam_lam_read(LAM_SOURCE_CRATE(source), &lam);
      if (lam & LAM_SOURCE_STATION(source))
         if (!test)
            return lam;
   }
   return 0;
}
INT read_deferred_event (char * pevent, INT off)
Definition at line 365 of file deferredfe.c.
References bk_close(), bk_create(), bk_init(), bk_size(), cam24i(), CRATE, EVENT_ID, N_SCLR, SERIAL_NUMBER, SLOT_SCLR, TID_DWORD, and TRUE.
{
   DWORD *pdata, a;
   /* init bank structure */
   bk_init(pevent);
   /* create SCLR bank */
   bk_create(pevent, "SCLR", TID_DWORD, &pdata);
   /* read scaler bank */
   for (a = 0; a < N_SCLR; a++)
      cam24i(CRATE, SLOT_SCLR, a, 0, pdata++);
   bk_close(pevent, pdata);
   if (transition_PS_requested) {
      // transition acknowledged, but...
      // carry on until hardware condition satisfied
      // ...
      if (pseudo_delay++ < 3) {
         // Ignore transition
         printf("Transition ignored, ");
      } else {
         // Time to do transition
         printf("End of cycle... perform transition\n");
         end_of_mcs_cycle = TRUE;
      }
   }
   printf("Event ID:%d - Event#: %d\n", EVENT_ID(pevent), SERIAL_NUMBER(pevent));
   return bk_size(pevent);
}
INT resume_run (INT run_number, char * error)
Definition at line 304 of file deferredfe.c.
References SUCCESS.
{
   return SUCCESS;
}
BOOL wait_end_cycle (int transition, BOOL first)
Definition at line 220 of file deferredfe.c.
References FALSE, and TRUE.
Referenced by frontend_init().
{
   // Get there after every
   if (first) {
      // Get there as soon as transition is requested
      transition_PS_requested = TRUE;
      printf("Transition requested...\n");
      // Defer the transition now
      return FALSE;
   }
   // Check user flag
   if (end_of_mcs_cycle) {
      // User flag set, ready to perform deferred transition now
      transition_PS_requested = FALSE;
      end_of_mcs_cycle = FALSE;
      return TRUE;
   } else {
      // User not ready for transition, defers it...
      return FALSE;
   }
}
Variable Documentation
INT display_period = 000
Definition at line 89 of file deferredfe.c.
BOOL end_of_mcs_cycle = FALSE
Definition at line 217 of file deferredfe.c.
EQUIPMENT equipment[]
Definition at line 149 of file deferredfe.c.
INT event_buffer_size = 10 * 10000
Definition at line 98 of file deferredfe.c.
BOOL frontend_call_loop = FALSE
Definition at line 86 of file deferredfe.c.
char* frontend_file_name = __FILE__
Definition at line 83 of file deferredfe.c.
char* frontend_name = "deferredfe"
Definition at line 81 of file deferredfe.c.
INT max_event_size = 10000
Definition at line 92 of file deferredfe.c.
INT max_event_size_frag = 5 * 1024 * 1024
Definition at line 95 of file deferredfe.c.
int pseudo_delay = 0
Definition at line 215 of file deferredfe.c.
BANK_LIST scaler_bank_list[]
Initial value:
 {
      {"SCLR", TID_DWORD, N_ADC, NULL}
      ,
      {""}
      ,
   }
Definition at line 138 of file deferredfe.c.
BOOL transition_PS_requested = FALSE
Definition at line 216 of file deferredfe.c.
BANK_LIST trigger_bank_list[]
Initial value:
 {
      {"ADC0", TID_STRUCT, sizeof(ADC0_BANK), adc0_bank_str}
      ,
      {"TDC0", TID_WORD, N_TDC, NULL}
      ,
      {""}
      ,
   }
Definition at line 128 of file deferredfe.c.