AlcapDAQ: online-display/Dictionary.cpp File Reference
Dictionary.cpp File Reference
#include "RConfig.h"
#include "Dictionary.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"
#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"
#include <new>
Data Structures
class G__Sizep2memfuncDictionary
class G__cpp_setup_initDictionary
Namespaces
ROOT
ROOT::Shadow
Constant Groups
ROOT
ROOT::Shadow
Macros
#define R__DICTIONARY_FILENAME Dictionary
#define private public
#define protected public
#define G__ROOT
Functions
void G__cpp_reset_tagtableDictionary ()
void G__set_cpp_environmentDictionary ()
int G__cpp_dllrevDictionary ()
static int G__Dictionary__0_1300 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
size_t G__get_sizep2memfuncDictionary ()
void G__cpp_setup_inheritanceDictionary ()
void G__cpp_setup_typetableDictionary ()
void G__cpp_setup_memvarDictionary ()
void G__cpp_setup_memfuncDictionary ()
static void G__cpp_setup_global0 ()
static void G__cpp_setup_global1 ()
void G__cpp_setup_globalDictionary ()
static void G__cpp_setup_func0 ()
static void G__cpp_setup_func1 ()
static void G__cpp_setup_func2 ()
static void G__cpp_setup_func3 ()
static void G__cpp_setup_func4 ()
static void G__cpp_setup_func5 ()
static void G__cpp_setup_func6 ()
static void G__cpp_setup_func7 ()
static void G__cpp_setup_func8 ()
static void G__cpp_setup_func9 ()
static void G__cpp_setup_func10 ()
static void G__cpp_setup_func11 ()
static void G__cpp_setup_func12 ()
void G__cpp_setup_funcDictionary ()
void G__cpp_setup_tagtableDictionary ()
void G__cpp_setupDictionary (void)
Variables
G__linked_taginfo G__DictionaryLN_TObject = { "TObject" , 99 , -1 }
G__linked_taginfo G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 }
G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 }
G__linked_taginfo G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 }
G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 }
G__cpp_setup_initDictionary G__cpp_setup_initializerDictionary
Macro Definition Documentation
#define G__ROOT
Definition at line 25 of file Dictionary.cpp.
#define private public
Definition at line 11 of file Dictionary.cpp.
#define protected public
Definition at line 12 of file Dictionary.cpp.
#define R__DICTIONARY_FILENAME Dictionary
Definition at line 7 of file Dictionary.cpp.
Function Documentation
int G__cpp_dllrevDictionary ()
Definition at line 65 of file Dictionary.cpp.
 { return(30051515); }
void G__cpp_reset_tagtableDictionary ()
Definition at line 260 of file Dictionary.cpp.
References G__DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR, G__DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR, G__DictionaryLN_TObject, G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR, and G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.
Referenced by G__set_cpp_environmentDictionary().
{
   G__DictionaryLN_TObject.tagnum = -1 ;
   G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
   G__DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
   G__DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
 }
static void G__cpp_setup_func0 () static
Definition at line 188 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
    G__lastifuncposition();
 }
static void G__cpp_setup_func1 () static
Definition at line 193 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
 }
static void G__cpp_setup_func10 () static
Definition at line 220 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
 }
static void G__cpp_setup_func11 () static
Definition at line 223 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
 }
static void G__cpp_setup_func12 () static
Definition at line 226 of file Dictionary.cpp.
References G__Dictionary__0_1300(), and G__DictionaryLN_TObject.
Referenced by G__cpp_setup_funcDictionary().
{
    G__memfunc_setup("getObject", 919, G__Dictionary__0_1300, 85, G__get_linked_tagnum(&G__DictionaryLN_TObject), -1, 0, 1, 1, 1, 0, "C - - 10 - name", (char*) NULL
 , (void*) NULL, 0);
    G__resetifuncposition();
 }
static void G__cpp_setup_func2 () static
Definition at line 196 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
 }
static void G__cpp_setup_func3 () static
Definition at line 199 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
 }
static void G__cpp_setup_func4 () static
Definition at line 202 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
 }
static void G__cpp_setup_func5 () static
Definition at line 205 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
 }
static void G__cpp_setup_func6 () static
Definition at line 208 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
 }
static void G__cpp_setup_func7 () static
Definition at line 211 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
 }
static void G__cpp_setup_func8 () static
Definition at line 214 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
 }
static void G__cpp_setup_func9 () static
Definition at line 217 of file Dictionary.cpp.
Referenced by G__cpp_setup_funcDictionary().
{
 }
void G__cpp_setup_funcDictionary ()
Definition at line 233 of file Dictionary.cpp.
References G__cpp_setup_func0(), G__cpp_setup_func1(), G__cpp_setup_func10(), G__cpp_setup_func11(), G__cpp_setup_func12(), G__cpp_setup_func2(), G__cpp_setup_func3(), G__cpp_setup_func4(), G__cpp_setup_func5(), G__cpp_setup_func6(), G__cpp_setup_func7(), G__cpp_setup_func8(), and G__cpp_setup_func9().
Referenced by G__cpp_setupDictionary().
{
   G__cpp_setup_func0();
   G__cpp_setup_func1();
   G__cpp_setup_func2();
   G__cpp_setup_func3();
   G__cpp_setup_func4();
   G__cpp_setup_func5();
   G__cpp_setup_func6();
   G__cpp_setup_func7();
   G__cpp_setup_func8();
   G__cpp_setup_func9();
   G__cpp_setup_func10();
   G__cpp_setup_func11();
   G__cpp_setup_func12();
 }
static void G__cpp_setup_global0 () static
Definition at line 169 of file Dictionary.cpp.
Referenced by G__cpp_setup_globalDictionary().
{
    /* Setting up global variables */
    G__resetplocal();
 }
static void G__cpp_setup_global1 () static
Definition at line 176 of file Dictionary.cpp.
Referenced by G__cpp_setup_globalDictionary().
{
    G__resetglobalenv();
 }
void G__cpp_setup_globalDictionary ()
Definition at line 180 of file Dictionary.cpp.
References G__cpp_setup_global0(), and G__cpp_setup_global1().
Referenced by G__cpp_setupDictionary().
{
   G__cpp_setup_global0();
   G__cpp_setup_global1();
 }
void G__cpp_setup_inheritanceDictionary ()
Definition at line 115 of file Dictionary.cpp.
Referenced by G__cpp_setupDictionary().
{
    /* Setting up class inheritance */
 }
void G__cpp_setup_memfuncDictionary ()
Definition at line 163 of file Dictionary.cpp.
Referenced by G__cpp_setupDictionary().
{
 }
void G__cpp_setup_memvarDictionary ()
Definition at line 145 of file Dictionary.cpp.
Referenced by G__cpp_setupDictionary().
{
 }
void G__cpp_setup_tagtableDictionary ()
Definition at line 269 of file Dictionary.cpp.
References G__DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR, G__DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR, G__DictionaryLN_TObject, G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR, and G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.
Referenced by G__cpp_setupDictionary().
{
    /* Setting up class,struct,union tag entry */
    G__get_linked_tagnum_fwd(&G__DictionaryLN_TObject);
    G__get_linked_tagnum_fwd(&G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
    G__get_linked_tagnum_fwd(&G__DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
    G__get_linked_tagnum_fwd(&G__DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
 }
void G__cpp_setup_typetableDictionary ()
Definition at line 123 of file Dictionary.cpp.
References G__DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR, G__DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR, G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR, and G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.
Referenced by G__cpp_setupDictionary().
{
    /* Setting up typedef entry */
    G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
    G__setnewtype(-1,NULL,0);
 }
void G__cpp_setupDictionary (void)
Definition at line 278 of file Dictionary.cpp.
References G__cpp_setup_funcDictionary(), G__cpp_setup_globalDictionary(), G__cpp_setup_inheritanceDictionary(), G__cpp_setup_memfuncDictionary(), G__cpp_setup_memvarDictionary(), G__cpp_setup_tagtableDictionary(), G__cpp_setup_typetableDictionary(), G__get_sizep2memfuncDictionary(), and G__set_cpp_environmentDictionary().
Referenced by G__cpp_setup_initDictionary::G__cpp_setup_initDictionary().
{
   G__check_setup_version(30051515,"G__cpp_setupDictionary()");
   G__set_cpp_environmentDictionary();
   G__cpp_setup_tagtableDictionary();
   G__cpp_setup_inheritanceDictionary();
   G__cpp_setup_typetableDictionary();
   G__cpp_setup_memvarDictionary();
   G__cpp_setup_memfuncDictionary();
   G__cpp_setup_globalDictionary();
   G__cpp_setup_funcDictionary();
    if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDictionary();
   return;
 }
static int G__Dictionary__0_1300 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 72 of file Dictionary.cpp.
References getObject().
Referenced by G__cpp_setup_func12().
 {
       G__letint(result7, 85, (long) getObject((const char*) G__int(libp->para[0])));
    return(1 || funcname || hash || result7 || libp) ;
 }
size_t G__get_sizep2memfuncDictionary ()
Definition at line 98 of file Dictionary.cpp.
References G__Sizep2memfuncDictionary::sizep2memfunc().
Referenced by G__cpp_setupDictionary().
 {
   G__Sizep2memfuncDictionary a;
   G__setsizep2memfunc((int)a.sizep2memfunc());
   return((size_t)a.sizep2memfunc());
 }
void G__set_cpp_environmentDictionary ()
Definition at line 58 of file Dictionary.cpp.
References G__cpp_reset_tagtableDictionary().
Referenced by G__cpp_setupDictionary().
{
   G__add_compiledheader("TObject.h");
   G__add_compiledheader("TMemberInspector.h");
   G__add_compiledheader("getHist.h");
   G__cpp_reset_tagtableDictionary();
 }
Variable Documentation
G__cpp_setup_initDictionary G__cpp_setup_initializerDictionary
Definition at line 301 of file Dictionary.cpp.
G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 }
Definition at line 255 of file Dictionary.cpp.
Referenced by G__cpp_reset_tagtableDictionary(), G__cpp_setup_tagtableDictionary(), and G__cpp_setup_typetableDictionary().
G__linked_taginfo G__DictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 }
Definition at line 257 of file Dictionary.cpp.
Referenced by G__cpp_reset_tagtableDictionary(), G__cpp_setup_tagtableDictionary(), and G__cpp_setup_typetableDictionary().
G__linked_taginfo G__DictionaryLN_TObject = { "TObject" , 99 , -1 }
Definition at line 253 of file Dictionary.cpp.
Referenced by G__cpp_reset_tagtableDictionary(), G__cpp_setup_func12(), and G__cpp_setup_tagtableDictionary().
G__linked_taginfo G__DictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 }
Definition at line 254 of file Dictionary.cpp.
Referenced by G__cpp_reset_tagtableDictionary(), G__cpp_setup_tagtableDictionary(), and G__cpp_setup_typetableDictionary().
G__linked_taginfo G__DictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 }
Definition at line 256 of file Dictionary.cpp.
Referenced by G__cpp_reset_tagtableDictionary(), G__cpp_setup_tagtableDictionary(), and G__cpp_setup_typetableDictionary().