AlcapDAQ: crate5_CAEN_DT5720/dt5720_module.c File Reference
dt5720_module.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/io.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>
#include "midas.h"
#include "crate.h"
#include "diag.h"
#include "CAENDigitizer.h"
#include "CAENDigitizerType.h"
Data Structures
struct s_dt5720_odb
Macros
#define S_DT5720_ODB_STR "\[.]\n\software_trigger_mode = BYTE : 0\n\hardware_trigger_mode = BYTE : 0\n\self_trigger_mode = BYTE : 0\n\trigger_positive_edge = BOOL : y\n\max_events_per_block = DWORD : 1024\n\event_aligned_readout = BOOL : y\n\logic_level = STRING : [4] NIM\n\post_trigger_size = BYTE : 20\n\gpi_acquisition_mode = BOOL : n\n\zero_suppression_mode = BYTE : 0\n\event_packing = BOOL : n\n\ext_clock = BOOL : n\n\waveform length = DWORD : 64\n\\n\[Ch00]\n\enable = BOOL : n\n\offset = FLOAT : 0\n\self_trigger_threshhold = FLOAT : 0\n\\n\[Ch01]\n\enable = BOOL : n\n\offset = FLOAT : 0\n\self_trigger_threshhold = FLOAT : 0\n\\n\[Ch02]\n\enable = BOOL : n\n\offset = FLOAT : 0\n\self_trigger_threshhold = FLOAT : 0\n\\n\[Ch03]\n\enable = BOOL : n\n\offset = FLOAT : 0\n\self_trigger_threshhold = FLOAT : 0\"
Typedefs
typedef struct timespec timer_start
typedef struct s_dt5720_odb S_DT5720_ODB_DEF
Functions
static INT dt5720_init ()
static void dt5720_exit ()
static INT dt5720_pre_bor ()
static INT dt5720_eor ()
static INT dt5720_poll_live ()
static INT dt5720_read (char *pevent)
static void dt5720_readout ()
static BOOL dt5720_update_digitizer ()
static BOOL is_caen_error (CAEN_DGTZ_ErrorCode, int, const char *)
static uint32_t analog2adc_trigger (int)
static uint32_t analog2adc_offset (int)
Variables
static int handle
static uint32_t VME_BASE = 0x00000000
static char * caen_data_buffer = NULL
static uint32_t caen_data_buffer_size = 0
static char * data_buffer
static uint32_t data_buffer_size
static uint32_t data_size
bool block_sig
struct readout_module dt5720_module
static S_DT5720_ODB_DEF S_DT5720_ODB
HNDLE hDB
Macro Definition Documentation
#define S_DT5720_ODB_STR "\[.]\n\software_trigger_mode = BYTE : 0\n\hardware_trigger_mode = BYTE : 0\n\self_trigger_mode = BYTE : 0\n\trigger_positive_edge = BOOL : y\n\max_events_per_block = DWORD : 1024\n\event_aligned_readout = BOOL : y\n\logic_level = STRING : [4] NIM\n\post_trigger_size = BYTE : 20\n\gpi_acquisition_mode = BOOL : n\n\zero_suppression_mode = BYTE : 0\n\event_packing = BOOL : n\n\ext_clock = BOOL : n\n\waveform length = DWORD : 64\n\\n\[Ch00]\n\enable = BOOL : n\n\offset = FLOAT : 0\n\self_trigger_threshhold = FLOAT : 0\n\\n\[Ch01]\n\enable = BOOL : n\n\offset = FLOAT : 0\n\self_trigger_threshhold = FLOAT : 0\n\\n\[Ch02]\n\enable = BOOL : n\n\offset = FLOAT : 0\n\self_trigger_threshhold = FLOAT : 0\n\\n\[Ch03]\n\enable = BOOL : n\n\offset = FLOAT : 0\n\self_trigger_threshhold = FLOAT : 0\"
Definition at line 110 of file dt5720_module.c.
Referenced by dt5720_init().
Typedef Documentation
typedef struct s_dt5720_odb S_DT5720_ODB_DEF
typedef struct timespec timer_start
Definition at line 53 of file dt5720_module.c.
Function Documentation
uint32_t analog2adc_offset (int ch) static
Definition at line 569 of file dt5720_module.c.
References s_dt5720_odb::ch00, s_dt5720_odb::ch01, s_dt5720_odb::ch02, s_dt5720_odb::ch03, s_dt5720_odb::offset, and printf().
Referenced by dt5720_update_digitizer().
 {
   static const uint32_t adcmax = 65535;
   static const uint32_t adcmin = 0;
   static const float analogmax = 1.;
   static const float analogmin = -1.;
   static const float slope = (float)(adcmax-adcmin)/(analogmax-analogmin);
   /*
     Map analogue voltage offset (-1V-1V) to 16 bit ADC value (0-65535=2^16-1)
     Dynamic ranges:
     0x0000 -> -2V to 0V
     0x8000 -> -1V to 1V
     0xFFFF ->  0V to 2V
   */
   float v;
   switch(ch)
     {
     case 0: v = S_DT5720_ODB.ch00.offset; break;
     case 1: v = S_DT5720_ODB.ch01.offset; break;
     case 2: v = S_DT5720_ODB.ch02.offset; break;
     case 3: v = S_DT5720_ODB.ch03.offset; break;
     default: return 0x8000;
     }
   if(v>analogmax)
     {
       cm_msg(MINFO,"dt5720_update_digitizer","Invalid voltage offset. Set to 1V.");
       return adcmin;
     }
   else if(v<analogmin)
     {
       cm_msg(MINFO,"dt5720_update_digitizer","Invalid voltage offset. Set to -1V.");
       return adcmax;
     }
   v += 1.;
   uint32_t dac = slope*v;
   printf("DAC offset: channel %i DAC %i\n",ch, dac);
   return dac;
 }
uint32_t analog2adc_trigger (int ch) static
Definition at line 615 of file dt5720_module.c.
References s_dt5720_odb::ch00, s_dt5720_odb::ch01, s_dt5720_odb::ch02, s_dt5720_odb::ch03, s_dt5720_odb::offset, printf(), and s_dt5720_odb::self_trigger_threshold.
Referenced by dt5720_update_digitizer().
 {
   static const float dynamicrange = 2.;
   static const uint32_t adcmax = 4095;
   //static const uint32_t adcmax = 65535;
   static const uint32_t adcmin = 0;
   static const float slope = (adcmax-adcmin)/dynamicrange;
   float v, vmin;
   switch(ch)
     {
     case 0:
       v = S_DT5720_ODB.ch00.self_trigger_threshold;
       vmin = S_DT5720_ODB.ch00.offset - 1.;
       break;
     case 1:
       v = S_DT5720_ODB.ch01.self_trigger_threshold;
       vmin = S_DT5720_ODB.ch01.offset - 1.;
       break;
     case 2:
       v = S_DT5720_ODB.ch02.self_trigger_threshold;
       vmin = S_DT5720_ODB.ch02.offset - 1.;
       break;
     case 3:
       v = S_DT5720_ODB.ch03.self_trigger_threshold;
       vmin = S_DT5720_ODB.ch03.offset - 1.;
       break;
     default:
       return (adcmax-adcmin)/2;
     }
   if(v<vmin || v>(vmin+dynamicrange))
     {
       v = vmin+dynamicrange/2.;
       cm_msg(MINFO,"dt5720_update_digitizer","Invalid self trigger threshold. Set to center.");
     }
   uint32_t dac = (v-vmin)*slope;
   printf("Trigger threshold: channel %i DAC %i DAC\n",ch,dac);
   return dac;
 }
INT dt5720_eor () static
Definition at line 255 of file dt5720_module.c.
References caen_data_buffer, CAEN_DGTZ_FreeReadoutBuffer(), CAEN_DGTZ_SWStopAcquisition(), handle, is_caen_error(), and SUCCESS.
 {
   CAEN_DGTZ_ErrorCode ret;
 #ifdef SW_CONTROL
   ret = CAEN_DGTZ_SWStopAcquisition(handle);
   if(is_caen_error(ret,__LINE__-1,"dt5720_bor")) return FE_ERR_HW;
 #endif /* SW_CONTROL */
   ret = CAEN_DGTZ_FreeReadoutBuffer(&caen_data_buffer);
   if(is_caen_error(ret,__LINE__-1,"dt5720_eor")) return FE_ERR_HW;
   caen_data_buffer = NULL;
   return SUCCESS;
 }
void dt5720_exit () static
Definition at line 218 of file dt5720_module.c.
References CAEN_DGTZ_CloseDigitizer(), data_buffer, handle, and is_caen_error().
 {
   CAEN_DGTZ_ErrorCode ret;
   ret = CAEN_DGTZ_CloseDigitizer(handle);
   is_caen_error(ret,__LINE__-1,"dt5720_exit");
   free(data_buffer);
 }
INT dt5720_init () static
Definition at line 150 of file dt5720_module.c.
References CAEN_DGTZ_BoardInfo_t::AMC_FirmwareRel, CAEN_DGTZ_ACQ_CONTROL_ADD, CAEN_DGTZ_GetInfo(), CAEN_DGTZ_OpenDigitizer(), CAEN_DGTZ_Reset(), CAEN_DGTZ_USB, CAEN_DGTZ_WriteRegister(), crate_number, s_dt5720_odb::ext_clock, FALSE, handle, hDB, hKey, is_caen_error(), CAEN_DGTZ_BoardInfo_t::ModelName, printf(), CAEN_DGTZ_BoardInfo_t::ROC_FirmwareRel, S_DT5720_ODB_STR, sprintf(), status, and VME_BASE.
 {
   printf("Opening CAEN USB interface ...");
   fflush(stdout);
   HNDLE hKey;
   CAEN_DGTZ_ErrorCode ret;
   CAEN_DGTZ_BoardInfo_t BoardInfo;
   /* Grab Board */
   /* int iLine = 0;
        ret = CAEN_DGTZ_OpenDigitizer(CAEN_DGTZ_USB,iLine,0,VME_BASE,&handle);*/
   ret = CAEN_DGTZ_OpenDigitizer(CAEN_DGTZ_USB,0,0,VME_BASE,&handle);
   /*
   while(ret==CAEN_DGTZ_CommError)
     {
       //iLine++;
       ret = CAEN_DGTZ_OpenDigitizer(CAEN_DGTZ_USB,iLine,0,VME_BASE,&handle);
     }
   */
   if(is_caen_error(ret,__LINE__-1,"dt5720_init")) return FE_ERR_HW;
   /* Get Board Info */
   ret = CAEN_DGTZ_GetInfo(handle,&BoardInfo);
   if(is_caen_error(ret,__LINE__-1,"dt5720_init")) return FE_ERR_HW;
   printf("\nConnected to CAEN Desktop Digitizer Model %s\n",BoardInfo.ModelName);
   printf("\tROC FPGA Release is %s\n",BoardInfo.ROC_FirmwareRel);
   printf("\tAMC FPGA Release is %s\n",BoardInfo.AMC_FirmwareRel);
   /* Reset Digitizer */
   ret = CAEN_DGTZ_Reset(handle);
   if(is_caen_error(ret,__LINE__-1,"dt5720_init")) return FE_ERR_HW;
   /* Link to Database */
   //cm_get_experiment_database(&hDB,NULL);
   char str[1024];
   sprintf(str,"/Equipment/Crate %i/Settings/CAEN",crate_number);
   int status = db_check_record(hDB,0,str,S_DT5720_ODB_STR,FALSE);
   if(status==DB_NO_KEY || status==DB_STRUCT_MISMATCH)
     {
       status = db_create_record(hDB,0,str,S_DT5720_ODB_STR);
       printf("Creating key with status: %d \n",status);
     }
   else if (status==DB_INVALID_HANDLE)
     {
       printf("Error: Cannot connect to database to setup CAEN DT5720.");
     }
   status = db_find_key(hDB,0,str,&hKey);
   status = db_open_record(hDB,hKey,&S_DT5720_ODB,sizeof(S_DT5720_ODB),MODE_READ,NULL,NULL);
   // configure clock input
   if ( S_DT5720_ODB.ext_clock )
     {
       printf("Using external clock\n");
       ret = CAEN_DGTZ_WriteRegister(handle, CAEN_DGTZ_ACQ_CONTROL_ADD, 1<<6);
       if(is_caen_error(ret,__LINE__-1,"dt5720_init")) return FE_ERR_HW;
     }
   else
     {
       printf("Using internal clock\n");
     }
   return status;
 }
INT dt5720_poll_live () static
Definition at line 326 of file dt5720_module.c.
References dt5720_readout(), and SUCCESS.
 {
   dt5720_readout();
   return SUCCESS;
 }
INT dt5720_pre_bor () static
Definition at line 227 of file dt5720_module.c.
References caen_data_buffer, caen_data_buffer_size, CAEN_DGTZ_ClearData(), CAEN_DGTZ_MallocReadoutBuffer(), CAEN_DGTZ_SetAcquisitionMode(), CAEN_DGTZ_SW_CONTROLLED, CAEN_DGTZ_SWStartAcquisition(), data_size, dt5720_update_digitizer(), handle, is_caen_error(), printf(), and SUCCESS.
 {
   CAEN_DGTZ_ErrorCode ret;
 #ifdef SW_CONTROL
   ret = CAEN_DGTZ_SetAcquisitionMode(handle,CAEN_DGTZ_SW_CONTROLLED);
   if(is_caen_error(ret,__LINE__-1,"dt5720_bor")) return FE_ERR_HW;
   ret = CAEN_DGTZ_SWStartAcquisition(handle);
   if(is_caen_error(ret,__LINE__-1,"dt5720_bor")) return FE_ERR_HW;
 #endif /* SW_CONTROL */
   /* Setup Digitizer */
   if(!dt5720_update_digitizer()) return FE_ERR_HW;
   /* Allocate space for readout from digitizer */
   ret = CAEN_DGTZ_MallocReadoutBuffer(handle,&caen_data_buffer,&caen_data_buffer_size);
   if(is_caen_error(ret,__LINE__-1,"dt5720_bor")) return FE_ERR_HW;
   printf("Allocated %i bytes for CAEN data buffer\n", caen_data_buffer_size);
   /* Clear any remaining data */
   ret = CAEN_DGTZ_ClearData(handle);
   if(is_caen_error(ret,__LINE__-1,"dt5720_bor")) return FE_ERR_HW;
   data_size = 0;
   return SUCCESS;
 }
INT dt5720_read (char * pevent) static
Definition at line 271 of file dt5720_module.c.
References data_buffer, data_size, dt5720_readout(), sprintf(), and SUCCESS.
 {
   //printf("Read out data from desktop digitizer\n");
   // =====================================================================================
   // Read out remaining data from the digitizer
   // =====================================================================================
   dt5720_readout();
   // =====================================================================================
   // Fill MIDAS event
   // =====================================================================================
   bk_init32(pevent);
   char bk_name[5];
   char *pdata;
   sprintf(bk_name,"CND0");
   bk_create(pevent, bk_name, TID_BYTE, &pdata);
   if ( data_size > MAX_EVENT_SIZE )
     {
       cm_msg(MERROR,"dt5720_read","Event size is too large. Truncating data...\n");
       data_size = MAX_EVENT_SIZE;
     }
   memcpy(pdata, data_buffer, data_size);
   pdata += data_size;
   bk_close(pevent, pdata);
   // reset data couner for the next event
   data_size = 0;
   return SUCCESS;
 }
void dt5720_readout () static
Definition at line 303 of file dt5720_module.c.
References caen_data_buffer, CAEN_DGTZ_ReadData(), CAEN_DGTZ_SLAVE_TERMINATED_READOUT_MBLT, data_buffer, data_buffer_size, data_size, handle, and is_caen_error().
Referenced by dt5720_poll_live(), and dt5720_read().
 {
   CAEN_DGTZ_ErrorCode ret;
   uint32_t caen_data_size;
   /* Read out data if there is any */
   ret = CAEN_DGTZ_ReadData(handle,CAEN_DGTZ_SLAVE_TERMINATED_READOUT_MBLT,caen_data_buffer, &caen_data_size);
   is_caen_error(ret,__LINE__-1,"dt5720_readout");
   /* If there's data, copy from digitizers local buffer to different local buffer */
   if(caen_data_size > 0)
     {
       //printf("data size: %i\n", caen_data_size);
       if(data_size+caen_data_size < data_buffer_size )
         {
           memcpy((data_buffer+data_size), caen_data_buffer, caen_data_size);
           data_size += caen_data_size;
         }
     }
 }
BOOL dt5720_update_digitizer () static
Definition at line 334 of file dt5720_module.c.
References analog2adc_offset(), analog2adc_trigger(), CAEN_DGTZ_BROAD_CH_CTRL_ADD, CAEN_DGTZ_DISABLE, CAEN_DGTZ_ENABLE, CAEN_DGTZ_IOLevel_NIM, CAEN_DGTZ_IOLevel_TTL, CAEN_DGTZ_ReadRegister(), CAEN_DGTZ_S_IN_CONTROLLED, CAEN_DGTZ_SetAcquisitionMode(), CAEN_DGTZ_SetChannelDCOffset(), CAEN_DGTZ_SetChannelEnableMask(), CAEN_DGTZ_SetChannelSelfTrigger(), CAEN_DGTZ_SetChannelTriggerThreshold(), CAEN_DGTZ_SetEventPackaging(), CAEN_DGTZ_SetExtTriggerInputMode(), CAEN_DGTZ_SetIOLevel(), CAEN_DGTZ_SetMaxNumEventsBLT(), CAEN_DGTZ_SetPostTriggerSize(), CAEN_DGTZ_SetRecordLength(), CAEN_DGTZ_SetSWTriggerMode(), CAEN_DGTZ_SetTriggerPolarity(), CAEN_DGTZ_SetZeroSuppressionMode(), CAEN_DGTZ_Success, CAEN_DGTZ_SW_CONTROLLED, CAEN_DGTZ_TRGMODE_ACQ_AND_EXTOUT, CAEN_DGTZ_TRGMODE_ACQ_ONLY, CAEN_DGTZ_TRGMODE_DISABLED, CAEN_DGTZ_TRGMODE_EXTOUT_ONLY, CAEN_DGTZ_TriggerOnFallingEdge, CAEN_DGTZ_TriggerOnRisingEdge, CAEN_DGTZ_WriteRegister(), CAEN_DGTZ_ZS_AMP, CAEN_DGTZ_ZS_NO, CAEN_DGTZ_ZS_ZLE, s_dt5720_odb::ch00, s_dt5720_odb::ch01, s_dt5720_odb::ch02, s_dt5720_odb::ch03, data_buffer, data_buffer_size, s_dt5720_odb::enable, s_dt5720_odb::event_packing, s_dt5720_odb::gpi_acquisition_mode, handle, s_dt5720_odb::hardware_trigger_mode, is_caen_error(), s_dt5720_odb::logic_level, s_dt5720_odb::max_events_per_block, s_dt5720_odb::post_trigger_size, s_dt5720_odb::self_trigger_mode, s_dt5720_odb::software_trigger_mode, s_dt5720_odb::trigger_positive_edge, s_dt5720_odb::wf_length, and s_dt5720_odb::zero_suppression_mode.
Referenced by dt5720_pre_bor().
 {
   CAEN_DGTZ_ErrorCode ret;
   /* General CAEN settings */
   switch(S_DT5720_ODB.software_trigger_mode)
     {
     case 0:
       ret = CAEN_DGTZ_SetSWTriggerMode(handle,CAEN_DGTZ_TRGMODE_DISABLED);
       break;
     case 1:
       ret = CAEN_DGTZ_SetSWTriggerMode(handle,CAEN_DGTZ_TRGMODE_ACQ_ONLY);
       break;
     case 2:
       ret = CAEN_DGTZ_SetSWTriggerMode(handle,CAEN_DGTZ_TRGMODE_EXTOUT_ONLY);
       break;
     case 3:
       ret = CAEN_DGTZ_SetSWTriggerMode(handle,CAEN_DGTZ_TRGMODE_ACQ_AND_EXTOUT);
       break;
     default:
       ret = CAEN_DGTZ_SetSWTriggerMode(handle,CAEN_DGTZ_TRGMODE_DISABLED);
       cm_msg(MINFO,"dt5720_update_digitizer","Invalid software trigger mode. Set to DISABLED. (%i)",(int)S_DT5720_ODB.software_trigger_mode);
       break;
     }
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   switch(S_DT5720_ODB.hardware_trigger_mode)
     {
     case 0:
       ret = CAEN_DGTZ_SetExtTriggerInputMode(handle,CAEN_DGTZ_TRGMODE_DISABLED);
       break;
     case 1:
       ret = CAEN_DGTZ_SetExtTriggerInputMode(handle,CAEN_DGTZ_TRGMODE_ACQ_ONLY);
       break;
     case 2:
       ret = CAEN_DGTZ_SetExtTriggerInputMode(handle,CAEN_DGTZ_TRGMODE_EXTOUT_ONLY);
       break;
     case 3:
       ret = CAEN_DGTZ_SetExtTriggerInputMode(handle,CAEN_DGTZ_TRGMODE_ACQ_AND_EXTOUT);
       break;
     default:
       ret = CAEN_DGTZ_SetExtTriggerInputMode(handle,CAEN_DGTZ_TRGMODE_DISABLED);
       cm_msg(MINFO,"dt5720_update_digitizer","Invalid hardware trigger mode. Set to DISABLED.");
       break;
     }
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   uint32_t caen_self_trigger_mask = 0b1111;
   switch(S_DT5720_ODB.self_trigger_mode)
     {
     case 0:
       ret = CAEN_DGTZ_SetChannelSelfTrigger(handle,CAEN_DGTZ_TRGMODE_DISABLED,caen_self_trigger_mask);
       break;
     case 1:
       ret = CAEN_DGTZ_SetChannelSelfTrigger(handle,CAEN_DGTZ_TRGMODE_ACQ_ONLY,caen_self_trigger_mask);
       break;
     case 2:
       ret = CAEN_DGTZ_SetChannelSelfTrigger(handle,CAEN_DGTZ_TRGMODE_EXTOUT_ONLY,caen_self_trigger_mask);
       break;
     case 3:
       ret = CAEN_DGTZ_SetChannelSelfTrigger(handle,CAEN_DGTZ_TRGMODE_ACQ_AND_EXTOUT,caen_self_trigger_mask);
       break;
     default:
       ret = CAEN_DGTZ_SetChannelSelfTrigger(handle,CAEN_DGTZ_TRGMODE_DISABLED,caen_self_trigger_mask);
       cm_msg(MINFO,"dt5720_update_digitizer","Invalid channel self trigger mode. Set to DISABLED. (%i)",(int)S_DT5720_ODB.self_trigger_mode);
       break;
     }
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   // According to correspondence with CAEN, second argument (channel nuumber) is ignored.
   // But just in case...
   if(S_DT5720_ODB.trigger_positive_edge)
     {
       ret = CAEN_DGTZ_SetTriggerPolarity(handle,0,CAEN_DGTZ_TriggerOnRisingEdge);
       ret = CAEN_DGTZ_SetTriggerPolarity(handle,1,CAEN_DGTZ_TriggerOnRisingEdge);
       ret = CAEN_DGTZ_SetTriggerPolarity(handle,2,CAEN_DGTZ_TriggerOnRisingEdge);
       ret = CAEN_DGTZ_SetTriggerPolarity(handle,3,CAEN_DGTZ_TriggerOnRisingEdge);
     }
   else
     {
       ret = CAEN_DGTZ_SetTriggerPolarity(handle,0,CAEN_DGTZ_TriggerOnFallingEdge);
       ret = CAEN_DGTZ_SetTriggerPolarity(handle,1,CAEN_DGTZ_TriggerOnFallingEdge);
       ret = CAEN_DGTZ_SetTriggerPolarity(handle,2,CAEN_DGTZ_TriggerOnFallingEdge);
       ret = CAEN_DGTZ_SetTriggerPolarity(handle,3,CAEN_DGTZ_TriggerOnFallingEdge);
     }
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   if(S_DT5720_ODB.max_events_per_block >= 2 && S_DT5720_ODB.max_events_per_block <= 1024)
     {
       ret = CAEN_DGTZ_SetMaxNumEventsBLT(handle,S_DT5720_ODB.max_events_per_block);
     }
   else
     {
       ret = CAEN_DGTZ_SetMaxNumEventsBLT(handle,1024);
       cm_msg(MINFO,"dt5720_update_digitizer","Invalid max block size. Set to 1024.");
     }
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   if(strcmp(S_DT5720_ODB.logic_level,"NIM") == 0)
     ret = CAEN_DGTZ_SetIOLevel(handle,CAEN_DGTZ_IOLevel_NIM);
   else if(strcmp(S_DT5720_ODB.logic_level,"TTL") == 0)
     ret = CAEN_DGTZ_SetIOLevel(handle,CAEN_DGTZ_IOLevel_TTL);
   else
     {
       ret = CAEN_DGTZ_SetIOLevel(handle,CAEN_DGTZ_IOLevel_NIM);
       cm_msg(MINFO,"dt5720_update_digitizer","Invalid logic level. Set to NIM.");
     }
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   if(S_DT5720_ODB.post_trigger_size >= 0 && S_DT5720_ODB.post_trigger_size <=100)
     {
       ret = CAEN_DGTZ_SetPostTriggerSize(handle,S_DT5720_ODB.post_trigger_size);
     }
   else
     {
       ret = CAEN_DGTZ_SetPostTriggerSize(handle,80);
       cm_msg(MINFO,"dt5720_update_digitizer","Invalid post trigger size. Set to 80 percent.");
     }
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   if(S_DT5720_ODB.gpi_acquisition_mode)
     {
       ret = CAEN_DGTZ_SetAcquisitionMode(handle,CAEN_DGTZ_S_IN_CONTROLLED);
     }
   else
     {
       ret = CAEN_DGTZ_SetAcquisitionMode(handle,CAEN_DGTZ_SW_CONTROLLED);
     }
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   switch(S_DT5720_ODB.zero_suppression_mode)
     {
     case 0:
       ret = CAEN_DGTZ_SetZeroSuppressionMode(handle,CAEN_DGTZ_ZS_NO);
       break;
     case 2:
       ret = CAEN_DGTZ_SetZeroSuppressionMode(handle,CAEN_DGTZ_ZS_ZLE);
       break;
     case 3:
       ret = CAEN_DGTZ_SetZeroSuppressionMode(handle,CAEN_DGTZ_ZS_AMP);
       break;
     default:
       ret = CAEN_DGTZ_SetZeroSuppressionMode(handle,CAEN_DGTZ_ZS_NO);
       cm_msg(MINFO,"dt5720_update_digitizer","Invalid zero suppression mode. Set to none.");
       break;
     }
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   if(S_DT5720_ODB.event_packing)
     {
       ret = CAEN_DGTZ_SetEventPackaging(handle,CAEN_DGTZ_ENABLE);
     }
   else
     {
       ret = CAEN_DGTZ_SetEventPackaging(handle,CAEN_DGTZ_DISABLE);
     }
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   // Channel specific
   uint32_t caen_channel_mask = 0;
   if(S_DT5720_ODB.ch00.enable)
     caen_channel_mask |= (1 << 0);
   if(S_DT5720_ODB.ch01.enable)
     caen_channel_mask |= (1 << 1);
   if(S_DT5720_ODB.ch02.enable)
     caen_channel_mask |= (1 << 2);
   if(S_DT5720_ODB.ch03.enable)
     caen_channel_mask |= (1 << 3);
   ret = CAEN_DGTZ_SetChannelEnableMask(handle,caen_channel_mask);
   ret = CAEN_DGTZ_SetChannelDCOffset(handle,
                                               0,
                                               analog2adc_offset(0));
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   ret = CAEN_DGTZ_SetChannelDCOffset(handle,
                                               1,
                                               analog2adc_offset(1));
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   ret = CAEN_DGTZ_SetChannelDCOffset(handle,
                                               2,
                                               analog2adc_offset(2));
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   ret = CAEN_DGTZ_SetChannelDCOffset(handle,
                                               3,
                                               analog2adc_offset(3));
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   ret = CAEN_DGTZ_SetChannelTriggerThreshold(handle,
                                                       0,
                                                       analog2adc_trigger(0));
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   ret = CAEN_DGTZ_SetChannelTriggerThreshold(handle,
                                                       1,
                                                       analog2adc_trigger(1));
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   ret = CAEN_DGTZ_SetChannelTriggerThreshold(handle,
                                                       2,
                                                       analog2adc_trigger(2));
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   ret = CAEN_DGTZ_SetChannelTriggerThreshold(handle,
                                                       3,
                                                       analog2adc_trigger(3));
   if(is_caen_error(ret,__LINE__,"dt5720_update_digitizer")) return false;
   // =====================================================================================
   // Record length
   // =====================================================================================
   ret = CAEN_DGTZ_SetRecordLength(handle, S_DT5720_ODB.wf_length);
   if ( ret != CAEN_DGTZ_Success )
     {
       cm_msg(MERROR,"dt5720_update_digitizer","Cannot SetRecordLength. Error 0x%08x\n",ret);
       return FE_ERR_HW;
     }
   // ======================================================================================
   // Channel configuration through register 0x8000=CAEN_DGTZ_BROAD_CH_CTRL_ADD
   // ======================================================================================
   uint32_t data;
   ret = CAEN_DGTZ_ReadRegister(handle, CAEN_DGTZ_BROAD_CH_CTRL_ADD, &data);
   if(is_caen_error(ret,__LINE__-1,"dt5720_update_digitizer")) return FE_ERR_HW;
   // Bit 4 must always be set to 1
   data |= (1<<4);
   // enable trigger overlap
   data |= (1<<1);
   ret = CAEN_DGTZ_WriteRegister(handle, CAEN_DGTZ_BROAD_CH_CTRL_ADD, data);
   if(is_caen_error(ret,__LINE__-1,"dt5720_update_digitizer")) return FE_ERR_HW;
   data_buffer_size = 32*1024*1024;
   data_buffer = (char*) malloc(data_buffer_size);
   return true;
 }
BOOL is_caen_error (CAEN_DGTZ_ErrorCode e, int l, const char * r) static
Definition at line 659 of file dt5720_module.c.
References CAEN_DGTZ_BadBoardType, CAEN_DGTZ_BadEventNumber, CAEN_DGTZ_BadInterruptLev, CAEN_DGTZ_CalibrationError, CAEN_DGTZ_ChannelBusy, CAEN_DGTZ_CommError, CAEN_DGTZ_DigitizerAlreadyOpen, CAEN_DGTZ_DigitizerMemoryCorrupted, CAEN_DGTZ_DigitizerNotFound, CAEN_DGTZ_DigitizerNotReady, CAEN_DGTZ_DPPFirmwareNotSupported, CAEN_DGTZ_EventNotFound, CAEN_DGTZ_FPIOModeInvalid, CAEN_DGTZ_FunctionNotAllowed, CAEN_DGTZ_GenericError, CAEN_DGTZ_InterruptNotConfigured, CAEN_DGTZ_InvalidBuffer, CAEN_DGTZ_InvalidChannelNumber, CAEN_DGTZ_InvalidEvent, CAEN_DGTZ_InvalidHandle, CAEN_DGTZ_InvalidLinkType, CAEN_DGTZ_InvalidParam, CAEN_DGTZ_MaxDevicesError, CAEN_DGTZ_NotYetImplemented, CAEN_DGTZ_OutOfMemory, CAEN_DGTZ_ReadDeviceRegisterFail, CAEN_DGTZ_Success, CAEN_DGTZ_Timeout, CAEN_DGTZ_WriteDeviceRegisterFail, CAEN_DGTZ_WrongAcqMode, FALSE, and TRUE.
Referenced by dt5720_eor(), dt5720_exit(), dt5720_init(), dt5720_pre_bor(), dt5720_readout(), and dt5720_update_digitizer().
 {
   /*
     l: line number
     f: file name
     r: parent routine
   */
   static char* f = __FILE__;
   if(e==CAEN_DGTZ_Success)
     return FALSE;
   switch(e)
     {
     case CAEN_DGTZ_CommError:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Communication error.");
       break;
     case CAEN_DGTZ_GenericError:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Generic (unspecified) error.");
       break;
     case CAEN_DGTZ_InvalidParam:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Invalid parameter error.");
       break;
     case CAEN_DGTZ_InvalidLinkType:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Invalid LinkType.");
       break;
     case CAEN_DGTZ_InvalidHandle:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Invalid handle.");
       break;
     case CAEN_DGTZ_MaxDevicesError:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Too many devices.");
       break;
     case CAEN_DGTZ_BadBoardType:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Operation not allowed on this model.");
       break;
     case CAEN_DGTZ_BadInterruptLev:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Invalid interrupt level.");
       break;
     case CAEN_DGTZ_BadEventNumber:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Invalid event number.");
       break;
     case CAEN_DGTZ_ReadDeviceRegisterFail:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Unable to read from registry.");
       break;
     case CAEN_DGTZ_WriteDeviceRegisterFail:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Unable to write to registry.");
       break;
     case CAEN_DGTZ_InvalidChannelNumber:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Invalid channel number.");
       break;
     case CAEN_DGTZ_ChannelBusy:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Channel is busy.");
       break;
     case CAEN_DGTZ_FPIOModeInvalid:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Invalid FPIO (?) mode.");
       break;
     case CAEN_DGTZ_WrongAcqMode:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Invalid acquisition mode.");
       break;
     case CAEN_DGTZ_FunctionNotAllowed:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Module does not support this function.");
       break;
     case CAEN_DGTZ_Timeout:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Communication timed out.");
       break;
     case CAEN_DGTZ_InvalidBuffer:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Invalid buffer (readout or event).");
       break;
     case CAEN_DGTZ_EventNotFound:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Unable to find event.");
       break;
     case CAEN_DGTZ_InvalidEvent:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Event is invalid.");
       break;
     case CAEN_DGTZ_OutOfMemory:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Memory has run out.");
       break;
     case CAEN_DGTZ_CalibrationError:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Calibration failed.");
       break;
     case CAEN_DGTZ_DigitizerNotFound:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Unable to locate digitizer.");
       break;
     case CAEN_DGTZ_DigitizerAlreadyOpen:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Digitizer is already open.");
       break;
     case CAEN_DGTZ_DigitizerNotReady:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Digitizer not ready.");
       break;
     case CAEN_DGTZ_InterruptNotConfigured:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Interrupts not configured.");
       break;
     case CAEN_DGTZ_DigitizerMemoryCorrupted:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Flash memory corrupted.");
       break;
     case CAEN_DGTZ_DPPFirmwareNotSupported:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Firmware not supported by these libraries.");
       break;
     case CAEN_DGTZ_NotYetImplemented:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Function not yet implemented.");
       break;
     default:
       cm_msg(MT_ERROR,f,l,r,"CAEN DT5720 Unknown error.");
       break;
     }
   return TRUE;
 }
Variable Documentation
bool block_sig
Definition at line 52 of file dt5720_module.c.
char* caen_data_buffer = NULL static
Definition at line 31 of file dt5720_module.c.
Referenced by dt5720_eor(), dt5720_pre_bor(), and dt5720_readout().
uint32_t caen_data_buffer_size = 0 static
Definition at line 32 of file dt5720_module.c.
Referenced by dt5720_pre_bor().
char* data_buffer static
Definition at line 33 of file dt5720_module.c.
Referenced by dt5720_exit(), dt5720_read(), dt5720_readout(), and dt5720_update_digitizer().
uint32_t data_buffer_size static
Definition at line 34 of file dt5720_module.c.
Referenced by dt5720_readout(), and dt5720_update_digitizer().
uint32_t data_size static
Definition at line 35 of file dt5720_module.c.
Referenced by dt5720_pre_bor(), dt5720_read(), and dt5720_readout().
struct readout_module dt5720_module
Initial value:
= {
  dt5720_init,
  dt5720_exit,
  dt5720_pre_bor,
  NULL,
  dt5720_eor,
  dt5720_poll_live,
  NULL,
  NULL,
  NULL,
  dt5720_read
}
Definition at line 55 of file dt5720_module.c.
int handle static
Definition at line 29 of file dt5720_module.c.
Referenced by dt5720_eor(), dt5720_exit(), dt5720_init(), dt5720_pre_bor(), dt5720_readout(), and dt5720_update_digitizer().
HNDLE hDB
Definition at line 11 of file mucap_compress.cpp.
Referenced by caen_load(), comp_load(), dt5720_init(), eb_begin_of_run(), epics_ca_get(), epics_ca_init(), epics_ca_set(), fadc_load(), frontend_init(), ge_ln2_read(), hits_load(), load_fragment(), load_huffman(), logger_root(), main(), MCaenCompProcessRaw_init(), MDQ_DAQLivetime_eor(), MDQ_DigitizerOverflow_init(), MDQ_FADCBufferOverflow_init(), MDQ_FADCPacketLoss_init(), MDQ_IslandRate_eor(), MDQ_RunTime_eor(), MDQ_TDCCheck_eor(), MDQ_Thresholds_eor(), MMuSCAnalysisC_init(), module_init(), module_init_sort_and_stitch(), n2fadc_ndet_load(), n2fadc_tpc_load(), nfadc_load(), odb_connect(), odb_find_key(), odb_get_bool(), odb_get_boolarray(), odb_get_dword(), odb_get_int(), odb_get_word(), process_file(), read_separator_event(), register_equipment(), save_huffman(), scheduler(), stck_load(), tdc400_load(), tr_prestart(), tr_start(), update_odb(), UpdateDetectorBankNameMap(), and v1724_init().
S_DT5720_ODB_DEF S_DT5720_ODB static
Definition at line 108 of file dt5720_module.c.
uint32_t VME_BASE = 0x00000000 static
Definition at line 30 of file dt5720_module.c.
Referenced by dt5720_init().