AlcapDAQ: midas/examples/eventbuilder/ebfe.c File Reference
midas/examples/eventbuilder/ebfe.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "midas.h"
#include "mcstd.h"
Defines
#define N_ADC 8
#define N_TDC 8
#define N_SCLR 8
#define CRATE 0
#define SLOT_IO 23
#define SLOT_ADC 1
#define SLOT_TDC 2
#define SLOT_SCLR 3
Functions
INT frontend_init ()
INT frontend_exit ()
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
INT frontend_loop ()
INT read_trigger_event (char *pevent, INT off)
INT read_scaler_event (char *pevent, INT off)
INT get_frontend_index ()
INT poll_event (INT source, INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Variables
char * frontend_name = "ebfe"
char * frontend_file_name = __FILE__
BOOL frontend_call_loop = FALSE
INT display_period = 3000
INT max_event_size = 1000
INT max_event_size_frag = 0
INT event_buffer_size = 10 * 1000
char Adcx [5]
char Tdcx [5]
char Sclx [5]
EQUIPMENT equipment []
Define Documentation
#define CRATE 0
Definition at line 79 of file ebfe.c.
#define N_ADC 8
Definition at line 74 of file ebfe.c.
#define N_SCLR 8
Definition at line 76 of file ebfe.c.
#define N_TDC 8
Definition at line 75 of file ebfe.c.
#define SLOT_ADC 1
Definition at line 81 of file ebfe.c.
#define SLOT_IO 23
Definition at line 80 of file ebfe.c.
#define SLOT_SCLR 3
Definition at line 83 of file ebfe.c.
#define SLOT_TDC 2
Definition at line 82 of file ebfe.c.
Function Documentation
INT begin_of_run (INT run_number, char * error)
Definition at line 209 of file ebfe.c.
References SUCCESS.
{
  /* put here clear scalers etc. */
  return SUCCESS;
}
INT end_of_run (INT run_number, char * error)
Definition at line 217 of file ebfe.c.
References SUCCESS.
{
  return SUCCESS;
}
INT frontend_exit (void)
Definition at line 203 of file ebfe.c.
References SUCCESS.
{
  return SUCCESS;
}
INT frontend_init (void)
Definition at line 174 of file ebfe.c.
References Adcx, cam_crate_clear(), cam_crate_zinit(), cam_init(), cam_lam_enable(), camc(), camo(), CRATE, get_frontend_index(), Sclx, SLOT_IO, SUCCESS, and Tdcx.
{
  /* Compose expected bank name under Ebuilder */
  sprintf(Adcx, "AD%02d", get_frontend_index());
  sprintf(Tdcx, "TC%02d", get_frontend_index());
  sprintf(Sclx, "SC%02d", get_frontend_index());
  /* hardware initialization */
  cam_init();
  cam_crate_clear(CRATE);
  cam_crate_zinit(CRATE);
  /* enable LAM in IO unit */
  camc(CRATE, SLOT_IO, 0, 26);
  /* enable LAM in crate controller */
  cam_lam_enable(CRATE, SLOT_IO);
  /* reset external LAM Flip-Flop */
  camo(CRATE, SLOT_IO, 1, 16, 0xFF);
  camo(CRATE, SLOT_IO, 1, 16, 0);
  /* print message and return FE_ERR_HW if frontend should not be started */
  return SUCCESS;
}
INT frontend_loop (void)
Definition at line 235 of file ebfe.c.
References SUCCESS.
{
  /* if frontend_call_loop is true, this routine gets called when
  the frontend is idle or once between every event */
  return SUCCESS;
}
INT get_frontend_index ()
Definition at line 1928 of file mfe_mucap.c.
{
   return frontend_index;
}
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Definition at line 272 of file ebfe.c.
References CMD_INTERRUPT_ATTACH, CMD_INTERRUPT_DETACH, CMD_INTERRUPT_DISABLE, CMD_INTERRUPT_ENABLE, and SUCCESS.
{
   switch (cmd) {
   case CMD_INTERRUPT_ENABLE:
      break;
   case CMD_INTERRUPT_DISABLE:
      break;
   case CMD_INTERRUPT_ATTACH:
      break;
   case CMD_INTERRUPT_DETACH:
      break;
   }
   return SUCCESS;
}
INT pause_run (INT run_number, char * error)
Definition at line 223 of file ebfe.c.
References SUCCESS.
{
  return SUCCESS;
}
INT poll_event (INT source, INT count, BOOL test)
Definition at line 251 of file ebfe.c.
References cam_lam_read(), cm_yield(), i, LAM_SOURCE_CRATE, and LAM_SOURCE_STATION.
{
  int i;
  DWORD lam;
  for (i = 0; i < count; i++) {
    cam_lam_read(LAM_SOURCE_CRATE(source), &lam);
    cm_yield(10);
    if (lam & LAM_SOURCE_STATION(source))
      if (!test)
        return lam;
  }
  return 0;
}
INT read_scaler_event (char * pevent, INT off)
Definition at line 336 of file ebfe.c.
{
   DWORD *pdata, a;
   /* init bank structure */
   bk_init(pevent);
   /* create SCLR bank */
   bk_create(pevent, Sclx, TID_DWORD, &pdata);
   /* read scaler bank */
   for (a = 0; a < N_SCLR; a++)
      cam24i(CRATE, SLOT_SCLR, a, 0, pdata++);
   bk_close(pevent, pdata);
   return bk_size(pevent);
}
INT read_trigger_event (char * pevent, INT off)
Definition at line 289 of file ebfe.c.
References Adcx, bk_close(), bk_create(), bk_init(), bk_size(), cam_lam_clear(), camc(), camo(), CRATE, N_ADC, N_TDC, SLOT_ADC, SLOT_IO, SLOT_TDC, Tdcx, TID_WORD, and timeout.
{
   WORD *pdata, a;
   INT q, timeout;
   /* init bank structure */
   bk_init(pevent);
   /* create ADC bank */
   bk_create(pevent, Adcx, TID_WORD, &pdata);
   /* read ADC bank */
   for (a = 0; a < N_ADC; a++)
      *pdata++ = a + 10;
   /* clear ADC */
   camc(CRATE, SLOT_ADC, 0, 9);
   bk_close(pevent, pdata);
   /* create TDC bank */
   bk_create(pevent, Tdcx, TID_WORD, &pdata);
   /* read TDC bank */
   for (a = 0; a < N_TDC; a++)
      *pdata++ = a + 20;
   /* clear TDC */
   camc(CRATE, SLOT_TDC, 0, 9);
   bk_close(pevent, pdata);
   /* clear IO unit LAM */
   camc(CRATE, SLOT_IO, 0, 10);
   /* clear LAM in crate controller */
   cam_lam_clear(CRATE, SLOT_IO);
   /* reset external LAM Flip-Flop */
   camo(CRATE, SLOT_IO, 1, 16, 0xFF);
   camo(CRATE, SLOT_IO, 1, 16, 0);
   return bk_size(pevent);
}
INT resume_run (INT run_number, char * error)
Definition at line 229 of file ebfe.c.
References SUCCESS.
{
   return SUCCESS;
}
Variable Documentation
char Adcx[5]
Definition at line 71 of file ebfe.c.
Referenced by frontend_init(), and read_trigger_event().
INT display_period = 3000
Definition at line 61 of file ebfe.c.
EQUIPMENT equipment[]
Definition at line 103 of file ebfe.c.
INT event_buffer_size = 10 * 1000
Definition at line 68 of file ebfe.c.
BOOL frontend_call_loop = FALSE
Definition at line 58 of file ebfe.c.
char* frontend_file_name = __FILE__
Definition at line 55 of file ebfe.c.
char* frontend_name = "ebfe"
Definition at line 53 of file ebfe.c.
INT max_event_size = 1000
Definition at line 64 of file ebfe.c.
INT max_event_size_frag = 0
Definition at line 65 of file ebfe.c.
char Sclx[5]
Definition at line 71 of file ebfe.c.
Referenced by frontend_init(), and read_scaler_event().
char Tdcx[5]
Definition at line 71 of file ebfe.c.
Referenced by frontend_init(), and read_trigger_event().