AlcapDAQ: rootana/src/FastSlowCompare.cpp File Reference
rootana/src/FastSlowCompare.cpp File Reference
#include "FastSlowCompare.h"
#include "RegisterModule.inc"
#include "TPulseIsland.h"
#include "TGlobalData.h"
#include "TSetupData.h"
#include "ModulesOptions.h"
#include "definitions.h"
#include "TH1I.h"
#include "TH2I.h"
#include "TDirectory.h"
#include <stdexcept>
#include <iostream>
#include <algorithm>
#include <numeric>
#include <cmath>
#include <climits>
#include <map>
#include <string>
Functions
static std::vector< double > TPI2Times (const std::vector< TPulseIsland * > &)
static double GetTime (const TPulseIsland *, const int)
static bool isValid (const TPulseIsland *)
ALCAP_REGISTER_MODULE (FastSlowCompare)
Function Documentation
ALCAP_REGISTER_MODULE (FastSlowCompare)
double GetTime (const TPulseIsland * tpi, const int pol) [static]
Definition at line 111 of file FastSlowCompare.cpp.
References TPulseIsland::GetBankName(), TPulseIsland::GetClockTickInNs(), TPulseIsland::GetSamples(), TSetupData::GetTimeShift(), TPulseIsland::GetTimeStamp(), and TSetupData::Instance().
{
  const static double cf_frac = 0.2;
  const std::vector<int>& samps = tpi->GetSamples();
  const std::vector<int>::const_iterator b = samps.begin(), e = samps.end();
  const unsigned int ped = std::accumulate(b, b + 5, 0)/5.;
  std::vector<int>::const_iterator m = pol > 0 ? std::max_element(b, e) : std::min_element(b, e);
  const unsigned int amp = *m;
  const unsigned int cf = pol > 0 ? (unsigned int)(cf_frac*(double)(amp-ped)) + ped : (unsigned int)((double)(ped-amp)*(1.-cf_frac) + amp);
  while (m != b && (pol > 0 ? *--m > (int)cf : *--m < (int)cf));
  //m = pol > 0 std::upper_bound(b, m, cf, ) : ;
  double dx = (double)(m-b);
  if (*(m+1) != *m)
    dx += (double)((int)cf - *m)/(double)(*(m+1) - *m);
  return (dx + (double)tpi->GetTimeStamp()) * tpi->GetClockTickInNs() - TSetupData::Instance()->GetTimeShift(tpi->GetBankName());
}
bool isValid (const TPulseIsland * tpi) [static]
Definition at line 154 of file FastSlowCompare.cpp.
References TPulseIsland::GetBankName(), TSetupData::GetNBits(), TPulseIsland::GetSamples(), and TSetupData::Instance().
{
  const std::vector<int>& samps = tpi->GetSamples();
  const int min = 0;
  const int max = (int)std::pow(2., (double)TSetupData::Instance()->GetNBits(tpi->GetBankName())) - 1;
  if (*std::min_element(samps.begin(), samps.end()) <= min ||
      *std::max_element(samps.begin(), samps.end()) >= max)
    return false;
  return true;
}
std::vector< double > TPI2Times (const std::vector< TPulseIsland * > & vec) [static]
Definition at line 145 of file FastSlowCompare.cpp.
References GetTime().
Referenced by FastSlowCompare::ProcessEntry().
{
  static std::vector<TPulseIsland*>::const_iterator tpi;
  std::vector<double> times;
  for (tpi = vec.begin(); tpi < vec.end(); ++tpi)
    //   if (isValid(*tpi))
    times.push_back(GetTime(*tpi, (*tpi)->GetTriggerPolarity()));
  return times;
}