AlcapDAQ: midas/include/ftplib.h File Reference
midas/include/ftplib.h File Reference
Data Structures
struct FTP_CON
Defines
#define MAX_ANSWERS 10
#define QUIT 0
#define Ctrl(x) ((x) - '@')
#define FREE(x) memset (&x , '\0' , sizeof x)
#define CUT(x) ((x)&0xff)
#define ftp_account(ftp, acc) ftp_command(ftp,"ACCT %s",acc,230,EOF)
#define ftp_user(ftp, user) ftp_command(ftp,"USER %s",user,230,331,332,EOF)
#define ftp_password(ftp, pas) ftp_command(ftp,"PASS %s",pas,230,332,EOF)
#define ftp_type(ftp, type) ftp_command(ftp,"TYPE %s",type,200,EOF)
#define ftp_chdir(ftp, dir) ftp_command(ftp,"CWD %s",dir,200,250,EOF)
#define ftp_mkdir(ftp, dir) ftp_command(ftp,"MKD %s",dir,200,257,EOF)
#define ftp_rm(ftp, dir) ftp_command(ftp,"DELE %s",dir,200,250,EOF)
#define ftp_ascii(ftp) ftp_type(ftp,"A")
#define ftp_binary(ftp) ftp_type(ftp,"I")
#define ftp_open_read(ftp, file) ftp_data(ftp,"RETR %s",file)
#define ftp_open_write(ftp, file) ftp_data(ftp,"STOR %s",file)
#define ftp_open_append(ftp, file) ftp_data(ftp,"APPE %s",file)
Functions
int EXPRT ftp_bye (FTP_CON *con)
int EXPRT ftp_close (FTP_CON *con)
int EXPRT ftp_connect (FTP_CON **con, char *host_name, unsigned short port)
int EXPRT ftp_login (FTP_CON **con, char *host, unsigned short port, char *user, char *pass, char *acct)
int EXPRT ftp_move (FTP_CON *con, char *old_name, char *new_name)
int EXPRT ftp_data (FTP_CON *con, char *command, char *param)
int EXPRT ftp_port (FTP_CON *con, int, int, int, int, int, int)
int EXPRT ftp_get (FTP_CON *con, char *local_name, char *remote_name)
int EXPRT ftp_put (FTP_CON *con, char *local_name, char *remote_name)
int EXPRT ftp_send (int sock, char *buffer, int n_bytes)
int EXPRT ftp_receive (int sock, char *buffer, int bsize)
int EXPRT ftp_send_message (FTP_CON *con, char *message)
int EXPRT ftp_get_message (FTP_CON *con, char *message)
BOOL EXPRT ftp_good (int number,...)
int EXPRT ftp_command (FTP_CON *con, char *command, char *param,...)
int EXPRT ftp_dir (FTP_CON *con, char *file)
char EXPRT * ftp_pwd (FTP_CON *con)
void EXPRT ftp_debug (int(*debug_func)(char *message), int(*error_func)(char *message))
Define Documentation
#define Ctrl (x) ((x) - '@')
Definition at line 7 of file ftplib.h.
#define CUT (x) ((x)&0xff)
Definition at line 9 of file ftplib.h.
Referenced by ftp_data().
#define FREE (x) memset (&x , '\0' , sizeof x)
Definition at line 8 of file ftplib.h.
#define ftp_account (ftp, acc) ftp_command(ftp,"ACCT %s",acc,230,EOF)
Definition at line 17 of file ftplib.h.
Referenced by ftp_login().
#define ftp_ascii (ftp) ftp_type(ftp,"A")
Definition at line 24 of file ftplib.h.
#define ftp_binary (ftp) ftp_type(ftp,"I")
Definition at line 25 of file ftplib.h.
Referenced by ftp_open().
#define ftp_chdir (ftp, dir) ftp_command(ftp,"CWD %s",dir,200,250,EOF)
Definition at line 21 of file ftplib.h.
Referenced by ftp_open().
#define ftp_mkdir (ftp, dir) ftp_command(ftp,"MKD %s",dir,200,257,EOF)
Definition at line 22 of file ftplib.h.
#define ftp_open_append (ftp, file) ftp_data(ftp,"APPE %s",file)
Definition at line 28 of file ftplib.h.
#define ftp_open_read (ftp, file) ftp_data(ftp,"RETR %s",file)
Definition at line 26 of file ftplib.h.
Referenced by ftp_get().
#define ftp_open_write (ftp, file) ftp_data(ftp,"STOR %s",file)
Definition at line 27 of file ftplib.h.
Referenced by ftp_open(), and ftp_put().
#define ftp_password (ftp, pas) ftp_command(ftp,"PASS %s",pas,230,332,EOF)
Definition at line 19 of file ftplib.h.
Referenced by ftp_login().
#define ftp_rm (ftp, dir) ftp_command(ftp,"DELE %s",dir,200,250,EOF)
Definition at line 23 of file ftplib.h.
#define ftp_type (ftp, type) ftp_command(ftp,"TYPE %s",type,200,EOF)
Definition at line 20 of file ftplib.h.
#define ftp_user (ftp, user) ftp_command(ftp,"USER %s",user,230,331,332,EOF)
Definition at line 18 of file ftplib.h.
Referenced by ftp_login().
#define MAX_ANSWERS 10
Definition at line 5 of file ftplib.h.
#define QUIT 0
Definition at line 6 of file ftplib.h.
Referenced by cnafsub(), decode_line(), ftp_command(), ftp_connect(), ftp_get_message(), ftp_port(), and mcstd_func().
Function Documentation
int EXPRT ftp_bye (FTP_CON * con)
Definition at line 444 of file ftplib.c.
References closesocket, ftp_get_message(), ftp_send_message(), FTP_SUCCESS, and FTP_CON::sock.
Referenced by ascii_log_close(), dump_log_close(), midas_log_close(), and yb_any_file_wclose().
{
   char str[256];
   ftp_send_message(con, "QUIT");
   ftp_get_message(con, str);
   closesocket(con->sock);
   free(con);
   return FTP_SUCCESS;
}
int EXPRT ftp_close (FTP_CON * con)
Definition at line 356 of file ftplib.c.
References closesocket, FTP_CON::data, and ftp_get_message().
Referenced by ascii_log_close(), dump_log_close(), ftp_dir(), ftp_get(), ftp_put(), midas_log_close(), and yb_any_file_wclose().
{
   char str[256];
   closesocket(con->data);
   return ftp_get_message(con, str);
}
int EXPRT ftp_command (FTP_CON * con, char * command, char * param, ...)
Definition at line 174 of file ftplib.c.
References FALSE, ftp_error_func, ftp_get_message(), FTP_NET_ERROR, FTP_RESPONSE_ERROR, ftp_send_message(), FTP_SUCCESS, QUIT, status, and TRUE.
Referenced by ftp_data(), ftp_move(), and ftp_open().
{
   va_list args;
   char str[2048];
   int status, code;
   BOOL result_ok;
   /* compose command string */
   sprintf(str, command, param);
   /* send command */
   if (ftp_send_message(con, str) != FTP_SUCCESS)
      return FTP_NET_ERROR;
   /* read reply */
   status = ftp_get_message(con, str);
   if (status == QUIT)
      return FTP_NET_ERROR;
   /* check reply code */
   va_start(args, param);
   result_ok = FALSE;
   do {
      code = va_arg(args, int);
      if (code == EOF)
         break;
      if (code == status)
         result_ok = TRUE;
   } while (!result_ok);
   va_end(args);
   if (!result_ok) {
      if (ftp_error_func != NULL)
         ftp_error_func(str);
      return FTP_RESPONSE_ERROR;
   }
   return -status;
}
int EXPRT ftp_connect (FTP_CON ** con, char * host_name, unsigned short port)
Definition at line 69 of file ftplib.c.
References closesocket, ftp_error_func, ftp_get_message(), ftp_good(), FTP_NET_ERROR, FTP_SUCCESS, QUIT, RPC_NET_ERROR, FTP_CON::sock, and status.
Referenced by ftp_login().
{
   struct sockaddr_in bind_addr;
   int sock;
   char str[4000];
   int status;
   struct hostent *phe;
   *con = NULL;
#ifdef OS_WINNT
   {
      WSADATA WSAData;
      /* Start windows sockets */
      if (WSAStartup(MAKEWORD(1, 1), &WSAData) != 0)
         return FTP_NET_ERROR;
   }
#endif
   if ((sock = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
      if (ftp_error_func)
         ftp_error_func("cannot create socket");
      return FTP_NET_ERROR;
   }
   /* connect to remote node */
   memset(&bind_addr, 0, sizeof(bind_addr));
   bind_addr.sin_family = AF_INET;
   bind_addr.sin_addr.s_addr = 0;
   bind_addr.sin_port = htons(port);
#ifdef OS_VXWORKS
   {
      INT host_addr;
      host_addr = hostGetByName(host_name);
      memcpy((char *) &(bind_addr.sin_addr), &host_addr, 4);
   }
#else
   phe = gethostbyname(host_name);
   if (phe == NULL) {
      if (ftp_error_func)
         ftp_error_func("cannot get host name");
      return RPC_NET_ERROR;
   }
   memcpy((char *) &(bind_addr.sin_addr), phe->h_addr, phe->h_length);
#endif
#ifdef OS_UNIX
   do {
      status = connect(sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
      /* don't return if an alarm signal was cought */
   } while (status == -1 && errno == EINTR);
#else
   status = connect(sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
#endif
   if (status != 0) {
      sprintf(str, "cannot connect to host %s, port %d", host_name, port);
      if (ftp_error_func)
         ftp_error_func(str);
      return FTP_NET_ERROR;
   }
   *con = (FTP_CON *) malloc(sizeof(FTP_CON));
   (*con)->sock = sock;
   (*con)->data = 0;
   memset(str, 0, sizeof(str));
   status = ftp_get_message(*con, str);
   /* check for status */
   if (status == QUIT || !ftp_good(status, 120, 220, EOF)) {
      closesocket(sock);
      free(*con);
      return FTP_NET_ERROR;
   }
   return FTP_SUCCESS;
}
int EXPRT ftp_data (FTP_CON * con, char * command, char * param)
Definition at line 281 of file ftplib.c.
References closesocket, CUT, FTP_CON::data, ftp_command(), FTP_NET_ERROR, ftp_port(), FTP_SUCCESS, host_name, and status.
Referenced by ftp_dir().
{
   struct sockaddr_in data, from;
   struct hostent *host;
   char host_name[256];
   int listen_socket, data_socket;
   int len = sizeof(data), one = 1, fromlen = sizeof(from), status;
   char *a, *b;
   memset(&data, 0, sizeof(data));
   memset(&from, 0, sizeof(from));
   if (gethostname(host_name, sizeof(host_name)) == -1)
      return FTP_NET_ERROR;
   if ((host = (struct hostent *) gethostbyname(host_name)) == 0)
      return FTP_NET_ERROR;
   if ((listen_socket = socket(AF_INET, SOCK_STREAM, 0)) == -1)
      return FTP_NET_ERROR;
   if (setsockopt(listen_socket, SOL_SOCKET, SO_REUSEADDR,
                  (char *) &one, sizeof(one)) < 0) {
      closesocket(listen_socket);
      return FTP_NET_ERROR;
   }
   data.sin_family = AF_INET;
   data.sin_port = htons(0);
   data.sin_addr.s_addr = *(unsigned long *) *(host->h_addr_list);
   if (bind(listen_socket, (struct sockaddr *) &data, sizeof(data)) == -1) {
      closesocket(listen_socket);
      return FTP_NET_ERROR;
   }
   if (getsockname(listen_socket, (struct sockaddr *) &data, &len) < 0) {
      closesocket(listen_socket);
      return FTP_NET_ERROR;
   }
   if (listen(listen_socket, 1) != 0) {
      closesocket(listen_socket);
      return FTP_NET_ERROR;
   }
   a = (char *) &data.sin_addr;
   b = (char *) &data.sin_port;
   status = ftp_port(con, CUT(a[0]), CUT(a[1]), CUT(a[2]),
                     CUT(a[3]), CUT(b[0]), CUT(b[1]));
   if (status != FTP_SUCCESS)
      return FTP_NET_ERROR;
   status = ftp_command(con, command, file, 200, 120, 150, 125, 250, EOF);
   if (status >= 0)
      return status;
   data_socket = accept(listen_socket, (struct sockaddr *) &from, &fromlen);
   if (data_socket == -1) {
      closesocket(listen_socket);
      return FTP_NET_ERROR;
   }
   closesocket(listen_socket);
   con->data = data_socket;
   return status;
}
void EXPRT ftp_debug (int(*)(char *message) debug_func, int(*)(char *message) error_func)
Definition at line 60 of file ftplib.c.
References ftp_debug_func, and ftp_error_func.
Referenced by ftp_open().
{
   ftp_debug_func = debug_func;
   ftp_error_func = error_func;
}
int EXPRT ftp_dir (FTP_CON * con, char * file)
Definition at line 609 of file ftplib.c.
References buffer, FTP_CON::data, FTP_CON::err_no, ftp_close(), ftp_data(), and ftp_receive().
{
   char command[256], buffer[8192];
   if (file == NULL || *file == '\0')
      strcpy(command, "LIST");
   else
      sprintf(command, "LIST %s", file);
   if (ftp_data(con, command, "") >= 0)
      return con->err_no;
   while (ftp_receive(con->data, buffer, sizeof(buffer)))
      printf(buffer);
   return ftp_close(con);
}
int EXPRT ftp_get (FTP_CON * con, char * local_name, char * remote_name)
Definition at line 497 of file ftplib.c.
References bars, count, FTP_CON::data, FTP_CON::err_no, ftp_close(), ftp_debug_func, FTP_FILE_ERROR, ftp_open_read, ftp_receive(), i, O_BINARY, ss_millitime(), status, total, and write.
{
   int fh;
   int status;
   char buff[8192];
   char str[256];
   int count, i;
   long total = 0;
   DWORD start, stop;
   if (ftp_open_read(con, remote_name) >= 0)
      return con->err_no;
   if ((fh = open(local_name, O_RDWR | O_CREAT | O_TRUNC | O_BINARY, 0644)) == -1)
      return FTP_FILE_ERROR;
   start = ss_millitime();
   while ((count = ftp_receive(con->data, buff, sizeof(buff))) > 0) {
      total += write(fh, buff, count);
      i = 0;
      if (ftp_debug_func != NULL) {
         printf("%c\r", bars[(i++) % 4]);
         fflush(stdout);
      }
   }
   close(fh);
   stop = ss_millitime();
   status = ftp_close(con);
   if (ftp_debug_func != NULL) {
      sprintf(str, "%ld bytes received in %1.2f seconds (%1.2lf kB/sec).",
              total, (stop - start) / 1000.0, total / 1024.0 / ((stop - start) / 1000.0));
      ftp_debug_func(str);
   }
   return status;
}
int EXPRT ftp_get_message (FTP_CON * con, char * message)
Definition at line 222 of file ftplib.c.
References FTP_CON::err_no, ftp_debug_func, ftp_get_message(), i, QUIT, and FTP_CON::sock.
Referenced by ftp_bye(), ftp_close(), ftp_command(), ftp_connect(), ftp_get_message(), ftp_port(), and ftp_pwd().
{
   int i, err_no;
   for (i = 0;; i++) {
      if (recv(con->sock, &message[i], 1, 0) != 1)
         return QUIT;
      if (i > 1 && message[i] == 10 && message[i - 1] == 13)
         break;
   }
   message[i - 1] = 0;
   err_no = atoi(message);
   if(err_no != 0) {
     con->err_no = err_no;
  }
   if (ftp_debug_func != NULL)
      ftp_debug_func(message);
   /* check for continuation message */
   if (message[3] == '-' || err_no == 0)
      ftp_get_message(con, message + strlen(message));
   return con->err_no;
}
BOOL EXPRT ftp_good (int number, ...)
Definition at line 254 of file ftplib.c.
References FALSE, and TRUE.
Referenced by ftp_connect(), and ftp_port().
{
   va_list args;
   BOOL result;
   int code;
   va_start(args, number);
   result = FALSE;
   do {
      code = va_arg(args, int);
      if (code == EOF)
         break;
      if (code == number)
         result = TRUE;
   } while (!result);
   va_end(args);
   return result;
}
int EXPRT ftp_login (FTP_CON ** con, char * host, unsigned short port, char * user, char * pass, char * acct)
Definition at line 410 of file ftplib.c.
References ftp_account, ftp_connect(), FTP_NET_ERROR, ftp_password, FTP_SUCCESS, ftp_user, and status.
Referenced by ftp_open().
{
   int status;
   status = ftp_connect(con, host, port);
   if (status != FTP_SUCCESS)
      return status;
   status = ftp_user(*con, user);
   if (status >= 0)
      return status;
   if (status == -230)
      return status;
   if (status == -332) {
      if (account == NULL)
         return FTP_NET_ERROR;
      status = ftp_account(*con, account);
      if (status < 1)
         return status;
      if (status == -230)
         return status;
   }
   return ftp_password(*con, password);
}
int EXPRT ftp_move (FTP_CON * con, char * old_name, char * new_name)
Definition at line 482 of file ftplib.c.
References ftp_command(), and status.
{
   int status;
   status = ftp_command(con, "RNFR %s", oldname, 200, 350, EOF);
   if (status < 0)
      return ftp_command(con, "RNTO %s", newname, 200, 250, EOF);
   else
      return status;
}
int EXPRT ftp_port (FTP_CON * con, int , int , int , int , int , int)
Definition at line 460 of file ftplib.c.
References cmd, ftp_get_message(), ftp_good(), FTP_NET_ERROR, ftp_send_message(), FTP_SUCCESS, QUIT, and status.
Referenced by ftp_data().
{
   char cmd[256];
   int status;
   sprintf(cmd, "PORT %d,%d,%d,%d,%d,%d", a, b, c, d, e, f);
   if (ftp_send_message(con, cmd) != FTP_SUCCESS)
      return FTP_NET_ERROR;
   status = ftp_get_message(con, cmd);
   if (status == QUIT)
      return QUIT;
   if (!ftp_good(status, 200, EOF))
      return FTP_NET_ERROR;
   return FTP_SUCCESS;
}
int EXPRT ftp_put (FTP_CON * con, char * local_name, char * remote_name)
Definition at line 540 of file ftplib.c.
References bars, count, FTP_CON::data, FTP_CON::err_no, ftp_close(), ftp_debug_func, FTP_FILE_ERROR, ftp_open_write, ftp_send(), i, O_BINARY, read, ss_millitime(), status, and total.
{
   int fh;
   int status;
   char buff[8193];
   char str[256];
   int count, i = 0;
   long total = 0;
   DWORD start, stop;
   if (ftp_open_write(con, remote_name) >= 0)
      return con->err_no;
   if ((fh = open(local_name, O_BINARY)) == -1)
      return FTP_FILE_ERROR;
   start = ss_millitime();
   while ((count = read(fh, buff, 8192)) > 0) {
      total += ftp_send(con->data, buff, count);
      if (ftp_debug_func != NULL) {
         printf("%c\r", bars[(i++) % 4]);
         fflush(stdout);
      }
   }
   close(fh);
   stop = ss_millitime();
   status = ftp_close(con);
   if (ftp_debug_func != NULL) {
      sprintf(str, "%ld bytes sent in %1.2f seconds (%1.2lf kB/sec).",
              total, (stop - start) / 1000.0, total / 1024.0 / ((stop - start) / 1000.0));
      ftp_debug_func(str);
   }
   return status;
}
char EXPRT* ftp_pwd (FTP_CON * con)
Definition at line 582 of file ftplib.c.
References ftp_error_func, ftp_get_message(), ftp_send_message(), FTP_SUCCESS, status, and tmp().
{
   static char str[256];
   char tmp[256];
   int status;
   str[0] = 0;
   if (ftp_send_message(con, "PWD") != FTP_SUCCESS)
      return str;
   status = ftp_get_message(con, tmp);
   if (status != 257) {
      if (ftp_error_func != NULL)
         ftp_error_func(tmp);
      return str;
   }
   sscanf(tmp, "%*[^\"]%*c%[^\"]%*s", str);
   return str;
}
int EXPRT ftp_receive (int sock, char * buffer, int bsize)
Definition at line 389 of file ftplib.c.
References count, i, and TRUE.
Referenced by ftp_dir(), and ftp_get().
{
   int count, i;
   i = 0;
   while (TRUE) {
      count = recv(sock, buffer + i, bsize - 1 - i, 0);
      if (count <= 0)
         return i;
      i += count;
      buffer[i] = 0;
      if (i >= bsize - 1)
         return i;
   }
}
int EXPRT ftp_send (int sock, char * buffer, int n_bytes)
Definition at line 368 of file ftplib.c.
References send().
Referenced by ascii_write(), dump_write(), ftp_put(), midas_flush_buffer(), and yb_any_dev_os_write().
{
   int n_bytes_left, n_written;
   n_bytes_left = n_bytes_to_write;
   while (n_bytes_left > 0) {
      n_written = send(sock, buffer, n_bytes_left > 8192 ? 8192 : n_bytes_left, 0);
      if (n_written <= 0)
         return n_bytes_to_write - n_bytes_left;
      n_bytes_left -= n_written;
      buffer += n_written;
   }
   return n_bytes_to_write;
}
int EXPRT ftp_send_message (FTP_CON * con, char * message)
Definition at line 157 of file ftplib.c.
References ftp_debug_func, FTP_NET_ERROR, FTP_SUCCESS, send(), and FTP_CON::sock.
Referenced by ftp_bye(), ftp_command(), ftp_port(), and ftp_pwd().
{
   if (send(con->sock, message, strlen(message), 0) == -1)
      return FTP_NET_ERROR;
   if (send(con->sock, "\r\n", 2, 0) == -1)
      return FTP_NET_ERROR;
   if (ftp_debug_func != NULL)
      ftp_debug_func(message);
   return FTP_SUCCESS;
}