AlcapDAQ: online-display/getHist.h File Reference
getHist.h File Reference
Macros
#define RDISP_ERR_NO_CON 1
cannot connect to the server
#define RDISP_ERR_BAD_RESPONSE 2
Bad response from the server.
#define RDISP_ERR_NO_RESPONSE 3
No response from the server.
#define RDISP_ERR_NO_SOURCE 4
No sourses open.
#define RDISP_ERR_BROKEN_PIPE 5
Broken pipe.
#define RDISP_ERR_NO_FILE 6
Cannot open file.
#define RDISP_ERR_NO_FOLDER 7
Cannot load root folder from file.
Functions
TFile * openRootFile (const char *filename)
TSocket * openSocket (const char *hostname, const int port_nr=9090)
void closeSource ()
TObject * getObject (const char *name)
void clear_recv_buffer ()
int get_status_code ()
ULong_t get_run_number ()
void reset_error_code ()
Macro Definition Documentation
#define RDISP_ERR_BAD_RESPONSE 2
Bad response from the server.
Definition at line 20 of file getHist.h.
Referenced by get_status_code(), openSocket(), and TOnlineFrame::runMacro().
#define RDISP_ERR_BROKEN_PIPE 5
Broken pipe.
Definition at line 29 of file getHist.h.
Referenced by get_status_code(), and TOnlineFrame::runMacro().
#define RDISP_ERR_NO_CON 1
cannot connect to the server
Definition at line 17 of file getHist.h.
Referenced by get_run_number(), get_status_code(), getObjectFromSocket(), openSocket(), and TOnlineFrame::runMacro().
#define RDISP_ERR_NO_FILE 6
Cannot open file.
Definition at line 32 of file getHist.h.
Referenced by get_status_code(), openRootFile(), and TOnlineFrame::runMacro().
#define RDISP_ERR_NO_FOLDER 7
Cannot load root folder from file.
Definition at line 35 of file getHist.h.
Referenced by get_status_code(), openRootFile(), and TOnlineFrame::runMacro().
#define RDISP_ERR_NO_RESPONSE 3
No response from the server.
Definition at line 23 of file getHist.h.
Referenced by get_status_code(), openSocket(), and TOnlineFrame::runMacro().
#define RDISP_ERR_NO_SOURCE 4
No sourses open.
Definition at line 26 of file getHist.h.
Referenced by get_status_code(), getObject(), getObjectFromFile(), and TOnlineFrame::runMacro().
Function Documentation
void clear_recv_buffer ()
Frees memory occupied by received objects
Definition at line 365 of file getHist.cpp.
References folder.
Referenced by closeSource(), and TOnlineFrame::runMacro().
 {
         if (folder) folder->Clear();
 }
void closeSource ()
close opened sources (socket or file)
Definition at line 178 of file getHist.cpp.
References clear_recv_buffer(), r_file, and r_socket.
Referenced by get_run_number(), getObjectFromSocket(), openRootFile(), and openSocket().
 {
         if (r_socket != NULL)
         {
                 r_socket->Close();
                 delete r_socket;
                 r_socket = NULL;
         }
         if (r_file != NULL)
         {
 #if 0
                 r_folder->Clear();
                 delete r_folder;
                 r_folder = NULL;
 #endif
                 r_file->Close("R");
                 delete r_file;
                 r_file = NULL;
         }
         clear_recv_buffer();
 }
ULong_t get_run_number ()
Return current run number
Definition at line 426 of file getHist.cpp.
References closeSource(), getObjectFromFile(), gl_status, printf(), r_file, r_socket, RDISP_ERR_NO_CON, sprintf(), status, and timeout.
Referenced by TOnlineFrame::runMacro().
 {
         ULong_t run_nr = 0;
         if (r_socket != NULL)
         {
                 TMessage *m;
                 char str[256];
                 sprintf(str, "GetRunNumber");
                 Int_t status = r_socket->Select(TSocket::kWrite,timeout);
                 if ( status != 1 )
                 {
                         printf("***ERROR! Broken connection to socket\n");
                         closeSource();
                         gl_status = RDISP_ERR_NO_CON;
                         return 0;
                 }
                 r_socket->Send(str);
                 status = r_socket->Select(TSocket::kRead,timeout);
                 if ( status != 1 )
                 {
                         printf("***ERROR! Broken connection to socket\n");
                         closeSource();
                         gl_status = RDISP_ERR_NO_CON;
                         return 0;
                 }
                 Int_t n = r_socket->Recv(m);
                 if ( n <= 0 )
                 {
                         printf("***ERROR! Broken pipe\n");
                         closeSource();
                         gl_status = RDISP_ERR_NO_CON;
                         return 0;
                 }
                 m->ReadULong( run_nr );
                 delete m;
         }
         else if ( r_file != NULL)
         {
                 TH1I *h1 = (TH1I*)getObjectFromFile( "run_number/h1_run_number" );
                 if ( h1 )
                 {
                         run_nr = h1->GetBinContent(1);
                 }
         }
         return run_nr;
 }
int get_status_code ()
Returns error code.
Returns
0 if no error
Definition at line 377 of file getHist.cpp.
References gl_status, printf(), RDISP_ERR_BAD_RESPONSE, RDISP_ERR_BROKEN_PIPE, RDISP_ERR_NO_CON, RDISP_ERR_NO_FILE, RDISP_ERR_NO_FOLDER, RDISP_ERR_NO_RESPONSE, and RDISP_ERR_NO_SOURCE.
Referenced by TOnlineFrame::runMacro().
 {
         switch ( gl_status )
         {
                 case 0:
                         // no error
                         break;
                 case RDISP_ERR_NO_CON:
                         printf("No connection to remote server\n");
                         break;
                 case RDISP_ERR_BAD_RESPONSE:
                         printf("Bad response from the server\n");
                         break;
                 case RDISP_ERR_NO_RESPONSE:
                         printf("No response from the server\n");
                         break;
                 case RDISP_ERR_NO_SOURCE:
                         printf("No sources opened\n");
                         break;
                 case RDISP_ERR_BROKEN_PIPE:
                         printf("Broken pipe\n");
                         break;
                 case RDISP_ERR_NO_FILE:
                         printf("Cannot open ROOT file\n");
                         break;
                 case RDISP_ERR_NO_FOLDER:
                         printf("Cannot load root folder from the ROOT file\n");
                         break;
                 default:
                         printf("Unknown error\n");
                         break;
         }
         return gl_status;
 }
TObject* getObject (const char * name)
no sources available
Definition at line 202 of file getHist.cpp.
References getObjectFromFile(), getObjectFromSocket(), gl_status, printf(), r_file, r_socket, and RDISP_ERR_NO_SOURCE.
Referenced by G__Dictionary__0_1300().
 {
         if (r_socket != NULL)
         {
                 return getObjectFromSocket( name );
         }
         else if (r_file != NULL)
         {
                 return getObjectFromFile( name );
         }
         if ( gl_status == 0 )
         {
                 printf("No connection\n");
                 gl_status = RDISP_ERR_NO_SOURCE;
         }
         return NULL;
 }
TFile* openRootFile (const char * filename)
Opens ROOT file on disk
Parameters
filename
Returns
pointer to opened file
Definition at line 75 of file getHist.cpp.
References closeSource(), gl_status, printf(), r_file, RDISP_ERR_NO_FILE, and RDISP_ERR_NO_FOLDER.
Referenced by TOnlineFrame::OpenRootFile().
 {
         closeSource();
         r_file = new TFile(filename);
         if ( r_file->IsZombie() )
         {
                 printf("***ERROR! Cannot open ROOT file [%s]\n",filename);
                 delete r_file;
                 r_file = NULL;
 #if 0
                 r_folder = NULL;
 #endif
                 gl_status = RDISP_ERR_NO_FILE;
         }
 #if 0
         else
         {
                 // *** get top folder ***
                 r_file->GetObject("histos",r_folder);
                 if ( !r_folder )
                 {
                         printf("**ERROR! Cannot load folder 'histos' from file [%filename]\n",filename);
                         delete r_file;
                         r_file = NULL;
                         r_folder = NULL;
                         gl_status = RDISP_ERR_NO_FOLDER;
                 }
                 else
                 {
                         r_folder->SetOwner( kTRUE );
                 }
         }
 #endif
         printf("Connected to source file :[%s]\n",filename);
         return r_file;
 }
TSocket* openSocket (const char * hostname, const int port_nr)
Connects to ROOT server (MIDAS analyzer)
Parameters
hostname
port_nr
Returns
opened socket or zero
Definition at line 124 of file getHist.cpp.
References closeSource(), gl_status, printf(), r_socket, RDISP_ERR_BAD_RESPONSE, RDISP_ERR_NO_CON, RDISP_ERR_NO_RESPONSE, sprintf(), status, and timeout.
Referenced by TOnlineFrame::ConnectToServer().
 {
         Int_t status;
         closeSource();
         r_socket = new TSocket(hostname, port_nr);
         if ( ! r_socket->IsValid()  )
         {
                 delete r_socket;
                 r_socket = NULL;
                 gl_status = RDISP_ERR_NO_CON;
                 return r_socket;
         }
         char str[64];
         sprintf(str,"ERROR");
         status = r_socket->Select(TSocket::kRead,timeout);
         if ( status == 1 )
         {
                 r_socket->Recv(str, sizeof(str));
                 if ( strncmp(str, "RMSERV", 6) != 0 )
                 {
                         // *** incorrect responce from the server ***
                         printf("***ERROR! Unexpected response from the server [%s] on port %i: [%s]",hostname,port_nr,str);
                         r_socket->Close();
                         delete r_socket;
                         r_socket = NULL;
                         gl_status = RDISP_ERR_BAD_RESPONSE;
                         return r_socket;
                 }
         }
         else
         {
                 // *** no response from the server ***
                 printf("***ERROR! No response from the server [%s] on port %i\n",hostname, port_nr);
                 r_socket->Close();
                 delete r_socket;
                 r_socket = NULL;
                 gl_status = RDISP_ERR_NO_RESPONSE;
                 return r_socket;
         }
         printf("Successfully connected to server on host [%s] port %i\n",hostname,port_nr);
         gl_status = 0;
         return r_socket;
 }
void reset_error_code ()
Clears error flag. All operations will be blocked untill ther error is cleared.
Definition at line 418 of file getHist.cpp.
References gl_status.
 {
         gl_status = 0;
 }