AlcapDAQ: Midas Dual Buffer Memory Functions (dm_xxx)
Midas Dual Buffer Memory Functions (dm_xxx)
[The midas.h & midas.c]
Data Structures
struct DMEM_AREA
struct DMEM_BUFFER
Defines
#define DM_FLUSH 10
#define DM_SEND 11
#define DM_KILL 12
#define DM_TIMEOUT 13
#define DM_ACTIVE_NULL 14
Functions
INT dm_buffer_create (INT size, INT user_max_event_size)
INT dm_buffer_release (void)
INLINE DMEM_AREA * dm_area_switch (void)
INLINE BOOL dm_area_full (void)
INLINE BOOL dm_active_full (void)
DWORD dm_buffer_time_get (void)
EVENT_HEADER * dm_pointer_get (void)
int dm_pointer_increment (INT buffer_handle, INT event_size)
INLINE INT dm_buffer_send (DMEM_AREA *larea)
INT dm_area_send (void)
INT dm_task (void *pointer)
INT dm_area_flush (void)
Variables
DMEM_BUFFER dm
INT dm_user_max_event_size
Detailed Description
dox dox
Define Documentation
#define DM_ACTIVE_NULL 14
Definition at line 17043 of file midas.c.
#define DM_FLUSH 10
dox
Definition at line 17039 of file midas.c.
Referenced by dm_area_flush(), and dm_task().
#define DM_KILL 12
Definition at line 17041 of file midas.c.
Referenced by dm_buffer_release(), and dm_task().
#define DM_SEND 11
Definition at line 17040 of file midas.c.
Referenced by dm_area_send(), and dm_task().
#define DM_TIMEOUT 13
Definition at line 17042 of file midas.c.
Function Documentation
INLINE BOOL dm_active_full (void)
Definition at line 17268 of file midas.c.
References DMEM_AREA::full, DMEM_BUFFER::pa, DMEM_AREA::pb, PTYPE, DMEM_AREA::pw, and TRUE.
Referenced by dm_pointer_get().
17270          : dm_active_full
17271
17272   Purpose: Test if there is sufficient space in either event buffer
17273            for another event.
17274   Input:
17275     none
17276   Output:
17277     none
17278   Function value:
17279     BOOL         TRUE if not enough space for another event
17280 \********************************************************************/
17281 {
17282    /* catch both full areas, waiting for transfer */
17283    if (dm.pa == NULL)
17284       return TRUE;
17285    /* Check the space in the active buffer only
17286       as I don't switch buffer here */
17287    if (dm.pa->full)
17288       return TRUE;
17289    return (((PTYPE) dm.pa->pb - (PTYPE) dm.pa->pw) < (INT)
17290            (dm_user_max_event_size + sizeof(EVENT_HEADER) + sizeof(INT)));
17291 }
INT dm_area_flush (void)
Definition at line 17649 of file midas.c.
References DMEM_BUFFER::action, DMEM_BUFFER::area1, DMEM_BUFFER::area2, CM_SUCCESS, dm_buffer_send(), DM_FLUSH, DMEM_BUFFER::last_active, DMEM_BUFFER::sem_flush, DMEM_BUFFER::sem_send, DMEM_AREA::serial, ss_millitime(), ss_mutex_release(), ss_mutex_wait_for(), and status.
Referenced by frontend_loop(), scheduler(), and send_event().
17651          : dm_area_flush
17652
17653   Purpose: Flush all the events in the areas.
17654            Used in mfe for BOR events, periodic events and
17655            if rate to low in main loop once a second. The standard
17656            data transfer should be done/triggered by dm_area_send (sync/async)
17657            in dm_pointer_get().
17658   Input:
17659     none
17660   Output:
17661     none
17662   Function value:
17663     CM_SUCCESS       Successful completion
17664     RPC_NET_ERROR    send error
17665 \********************************************************************/
17666 {
17667    INT status;
17668 #ifdef DM_DUAL_THREAD
17669    /* request FULL flush */
17670    dm.action = DM_FLUSH;
17671    ss_mutex_release(dm.sem_send);
17672 #ifdef OS_WINNT
17673    /* necessary for true MUTEX (NT) get semaphore back */
17674    ss_mutex_wait_for(dm.sem_send, 0);
17675 #endif
17676
17677    /* important to wait for completion before continue with timeout
17678       timeout specified milliseconds */
17679    status = ss_mutex_wait_for(dm.sem_flush, 10000);
17680 #ifdef DM_DEBUG
17681    printf("dm_area_flush after waiting %i\n", status);
17682 #endif
17683 #ifdef OS_WINNT
17684    ss_mutex_release(dm.sem_flush);      /* give it back now */
17685 #endif
17686
17687    return status;
17688 #else
17689    /* full flush done here */
17690    /* select in order both area independently of being full or not */
17691    if (dm.area1.serial <= dm.area2.serial) {
17692       status = dm_buffer_send(&dm.area1);
17693       if (status != CM_SUCCESS)
17694          return status;
17695       status = dm_buffer_send(&dm.area2);
17696       if (status != CM_SUCCESS)
17697          return status;
17698    } else {
17699       status = dm_buffer_send(&dm.area2);
17700       if (status != CM_SUCCESS)
17701          return status;
17702       status = dm_buffer_send(&dm.area1);
17703       if (status != CM_SUCCESS)
17704          return status;
17705    }
17706    /* reset serial counter */
17707    dm.area1.serial = dm.area2.serial = 0;
17708    dm.last_active = ss_millitime();
17709    return CM_SUCCESS;
17710 #endif
17711 }
INLINE BOOL dm_area_full (void)
Definition at line 17249 of file midas.c.
References DMEM_BUFFER::area1, DMEM_BUFFER::area2, FALSE, DMEM_AREA::full, DMEM_BUFFER::pa, and TRUE.
Referenced by dm_task().
17251          : dm_area_full
17252
17253   Purpose: Test if both area are full in order to block interrupt
17254   Input:
17255     none
17256   Output:
17257     none
17258   Function value:
17259     BOOL         TRUE if not enough space for another event
17260 \********************************************************************/
17261 {
17262    if (dm.pa == NULL || (dm.area1.full && dm.area2.full))
17263       return TRUE;
17264    return FALSE;
17265 }
INT dm_area_send (void)
Definition at line 17465 of file midas.c.
References DMEM_BUFFER::action, DMEM_BUFFER::area1, DMEM_BUFFER::area2, CM_SUCCESS, dm_buffer_send(), DM_SEND, DMEM_AREA::full, DMEM_BUFFER::pa, RPC_NET_ERROR, DMEM_BUFFER::sem_send, DMEM_AREA::serial, ss_mutex_release(), ss_mutex_wait_for(), SS_NO_MUTEX, and status.
Referenced by dm_pointer_get().
17467          : dm_area_send
17468
17469   Purpose: Empty the FULL area only in proper event order
17470            Meant to be use either in mfe.c scheduler on every event
17471
17472   Dual memory scheme:
17473    DM_DUAL_THREAD : Trigger sem_send
17474    !DM_DUAL_THREAD: empty full buffer in order, return active to area1
17475                     if dm.pa is NULL (were both full) and now both are empty
17476
17477   Input:
17478     none
17479   Output:
17480     none
17481   Function value:
17482     CM_SUCCESS                Successful completion
17483     RPC_NET_ERROR             send error
17484 \********************************************************************/
17485 {
17486 #ifdef DM_DUAL_THREAD
17487    INT status;
17488
17489    /* force a DM_SEND if possible. Don't wait for completion */
17490    dm.action = DM_SEND;
17491    ss_mutex_release(dm.sem_send);
17492 #ifdef OS_WINNT
17493    /* necessary for true MUTEX (NT) */
17494    status = ss_mutex_wait_for(dm.sem_send, 1);
17495    if (status == SS_NO_MUTEX) {
17496       printf(" timeout while waiting for sem_send\n");
17497       return RPC_NET_ERROR;
17498    }
17499 #endif
17500
17501    return CM_SUCCESS;
17502 #else
17503    /* ---------- NOT IN DUAL THREAD ----------- */
17504    INT status = 0;
17505
17506    /* if no DUAL thread everything is local then */
17507    /* select the full area */
17508    if (dm.area1.full && dm.area2.full)
17509       if (dm.area1.serial <= dm.area2.serial)
17510          status = dm_buffer_send(&dm.area1);
17511       else
17512          status = dm_buffer_send(&dm.area2);
17513    else if (dm.area1.full)
17514       status = dm_buffer_send(&dm.area1);
17515    else if (dm.area2.full)
17516       status = dm_buffer_send(&dm.area2);
17517    if (status != CM_SUCCESS)
17518       return status;            /* catch transfer error too */
17519
17520    if (dm.pa == NULL) {
17521       printf(" sync send dm.pa:%p full 1%li 2%li\n", dm.pa, dm.area1.full, dm.area2.full);
17522       dm.pa = &dm.area1;
17523    }
17524    return CM_SUCCESS;
17525 #endif
17526 }
INLINE DMEM_AREA* dm_area_switch (void)
Definition at line 17214 of file midas.c.
References DMEM_BUFFER::area1, DMEM_BUFFER::area2, DMEM_AREA::full, and DMEM_AREA::serial.
Referenced by dm_pointer_get().
17216          : dm_area_switch
17217
17218   Purpose: set active area to the other empty area or NULL if both
17219            area are full. May have to check the serial consistancy...
17220   Input:
17221     none
17222   Output:
17223     none
17224   Function value:
17225     DMEM_AREA *            Pointer to active area or both full
17226 \********************************************************************/
17227 {
17228    volatile BOOL full1, full2;
17229
17230    full1 = dm.area1.full;
17231    full2 = dm.area2.full;
17232
17233    if (!full1 && !full2) {
17234       if (dm.area1.serial <= dm.area2.serial)
17235          return (&(dm.area1));
17236       else
17237          return (&(dm.area2));
17238    }
17239
17240    if (!full1) {
17241       return (&(dm.area1));
17242    } else if (!full2) {
17243       return (&(dm.area2));
17244    }
17245    return (NULL);
17246 }
INT dm_buffer_create (INT size, INT user_max_event_size)
dox Setup a dual memory buffer. Has to be called initially before any other dm_xxx function
Parameters:
size Size in bytes
user_max_event_size max event size
Returns:
CM_SUCCESS, BM_NO_MEMORY, BM_MEMSIZE_MISMATCH
Definition at line 17079 of file midas.c.
References _send_sock, DMEM_BUFFER::area1, DMEM_BUFFER::area2, BM_MEMSIZE_MISMATCH, BM_NO_MEMORY, cm_msg, CM_SUCCESS, dm_task(), FALSE, DMEM_AREA::full, DMEM_BUFFER::last_active, M_MALLOC, MAX_EVENT_SIZE, MERROR, VX_TASK_SPAWN::name, DMEM_BUFFER::pa, DMEM_AREA::pb, DMEM_AREA::pe, VX_TASK_SPAWN::priority, DMEM_AREA::pt, DMEM_AREA::pw, rpc_get_event_sock(), DMEM_BUFFER::sem_flush, DMEM_BUFFER::sem_send, DMEM_BUFFER::serial, DMEM_AREA::serial, SS_CREATED, ss_millitime(), ss_mutex_create(), ss_mutex_wait_for(), SS_SUCCESS, ss_thread_create(), VX_TASK_SPAWN::stackSize, and status.
Referenced by main().
17080 {
17081
17082    dm.area1.pt = (char *) M_MALLOC(size);
17083    if (dm.area1.pt == NULL)
17084       return (BM_NO_MEMORY);
17085    dm.area2.pt = (char *) M_MALLOC(size);
17086    if (dm.area2.pt == NULL)
17087       return (BM_NO_MEMORY);
17088
17089    /* check user event size against the system MAX_EVENT_SIZE */
17090    if (user_max_event_size > MAX_EVENT_SIZE) {
17091       cm_msg(MERROR, "dm_buffer_create", "user max event size too large");
17092       return BM_MEMSIZE_MISMATCH;
17093    }
17094    dm_user_max_event_size = user_max_event_size;
17095
17096    memset(dm.area1.pt, 0, size);
17097    memset(dm.area2.pt, 0, size);
17098
17099    /* initialize pointers */
17100    dm.area1.pb = dm.area1.pt + size - 1024;
17101    dm.area1.pw = dm.area1.pe = dm.area1.pt;
17102    dm.area2.pb = dm.area2.pt + size - 1024;
17103    dm.area2.pw = dm.area2.pe = dm.area2.pt;
17104
17105   /*-PAA-*/
17106 #ifdef DM_DEBUG
17107    printf(" in dm_buffer_create ---------------------------------\n");
17108    printf(" %i %p %p %p %p\n", size, dm.area1.pt, dm.area1.pw, dm.area1.pe, dm.area1.pb);
17109    printf(" %i %p %p %p %p\n", size, dm.area2.pt, dm.area2.pw, dm.area2.pe, dm.area2.pb);
17110 #endif
17111
17112    /* activate first area */
17113    dm.pa = &dm.area1;
17114
17115    /* Default not full */
17116    dm.area1.full = dm.area2.full = FALSE;
17117
17118    /* Reset serial buffer number with proper starting sequence */
17119    dm.area1.serial = dm.area2.serial = 0;
17120    /* ensure proper serial on next increment */
17121    dm.serial = 1;
17122
17123    /* set active buffer time stamp */
17124    dm.last_active = ss_millitime();
17125
17126    /* get socket for event sending */
17127    _send_sock = rpc_get_event_sock();
17128
17129 #ifdef DM_DUAL_THREAD
17130    {
17131       INT status;
17132       VX_TASK_SPAWN starg;
17133
17134       /* create semaphore */
17135       status = ss_mutex_create("send", &dm.sem_send);
17136       if (status != SS_CREATED && status != SS_SUCCESS) {
17137          cm_msg(MERROR, "dm_buffer_create", "error in ss_mutex_create send");
17138          return status;
17139       }
17140       status = ss_mutex_create("flush", &dm.sem_flush);
17141       if (status != SS_CREATED && status != SS_SUCCESS) {
17142          cm_msg(MERROR, "dm_buffer_create", "error in ss_mutex_create flush");
17143          return status;
17144       }
17145       /* spawn dm_task */
17146       memset(&starg, 0, sizeof(VX_TASK_SPAWN));
17147
17148 #ifdef OS_VXWORKS
17149       /* Fill up the necessary arguments */
17150       strcpy(starg.name, "areaSend");
17151       starg.priority = 120;
17152       starg.stackSize = 20000;
17153 #endif
17154
17155       if ((status = ss_thread_create(dm_task, (void *) &starg))
17156           != SS_SUCCESS) {
17157          cm_msg(MERROR, "dm_buffer_create", "error in ss_thread_create");
17158          return status;
17159       }
17160 #ifdef OS_WINNT
17161       /* necessary for true MUTEX (NT) */
17162       ss_mutex_wait_for(dm.sem_send, 0);
17163 #endif
17164    }
17165 #endif                          /* DM_DUAL_THREAD */
17166
17167    return CM_SUCCESS;
17168 }
INT dm_buffer_release (void)
dox
Definition at line 17174 of file midas.c.
References DMEM_BUFFER::action, DMEM_BUFFER::area1, DMEM_BUFFER::area2, CM_SUCCESS, DM_KILL, DMEM_AREA::full, DMEM_AREA::pt, DMEM_BUFFER::sem_flush, DMEM_BUFFER::sem_send, DMEM_AREA::serial, DMEM_BUFFER::serial, ss_mutex_delete(), ss_mutex_release(), and TRUE.
Referenced by main().
17176          : dm_buffer_release
17177
17178   Purpose: Release dual memory buffers
17179   Input:
17180     none
17181   Output:
17182     none
17183   Function value:
17184     CM_SUCCESS              Successful completion
17185 \********************************************************************/
17186 {
17187    if (dm.area1.pt) {
17188       free(dm.area1.pt);
17189       dm.area1.pt = NULL;
17190    }
17191    if (dm.area2.pt) {
17192       free(dm.area2.pt);
17193       dm.area2.pt = NULL;
17194    }
17195    dm.serial = 0;
17196    dm.area1.full = dm.area2.full = TRUE;
17197    dm.area1.serial = dm.area2.serial = 0;
17198
17199 #ifdef DM_DUAL_THREAD
17200    /* kill spawned dm_task */
17201    dm.action = DM_KILL;
17202    ss_mutex_release(dm.sem_send);
17203    ss_mutex_release(dm.sem_flush);
17204
17205    /* release semaphore */
17206    ss_mutex_delete(dm.sem_send, 0);
17207    ss_mutex_delete(dm.sem_flush, 0);
17208 #endif
17209
17210    return CM_SUCCESS;
17211 }
INLINE INT dm_buffer_send (DMEM_AREA * larea)
Definition at line 17413 of file midas.c.
References _send_sock, ASYNC, bm_flush_cache(), CM_SUCCESS, FALSE, DMEM_AREA::full, DMEM_BUFFER::pa, DMEM_AREA::pe, DMEM_AREA::pt, PTYPE, DMEM_AREA::pw, RPC_NET_ERROR, and send_tcp().
Referenced by dm_area_flush(), dm_area_send(), and dm_task().
17415          : dm_buffer_send
17416
17417   Purpose: Ship data to the cache in fact!
17418            Basically the same do loop is done in the send_tcp.
17419            but _opt_tcp_size preveal if <= NET_TCP_SIZE.
17420            Introduced for bringing tcp option to user code.
17421   Input:
17422     DMEM_AREA * larea   The area to work with.
17423   Output:
17424     none
17425   Function value:
17426     CM_SUCCESS       Successful completion
17427     DM_ACTIVE_NULL   Both area were/are full
17428     RPC_NET_ERROR    send error
17429 \********************************************************************/
17430 {
17431    INT tot_size, nwrite;
17432    char *lpt;
17433
17434    /* if not connected remotely, use bm_send_event */
17435    if (_send_sock == 0)
17436       return bm_flush_cache(*((INT *) dm.pa->pw), ASYNC);
17437
17438    /* alias */
17439    lpt = larea->pt;
17440
17441    /* Get overall buffer size */
17442    tot_size = (PTYPE) larea->pe - (PTYPE) lpt;
17443
17444    /* shortcut for speed */
17445    if (tot_size == 0)
17446       return CM_SUCCESS;
17447
17448 #ifdef DM_DEBUG
17449    printf("lpt:%p size:%i ", lpt, tot_size);
17450 #endif
17451    nwrite = send_tcp(_send_sock, lpt, tot_size, 0);
17452 #ifdef DM_DEBUG
17453    printf("nwrite:%i  errno:%i\n", nwrite, errno);
17454 #endif
17455    if (nwrite < 0)
17456       return RPC_NET_ERROR;
17457
17458    /* reset area */
17459    larea->pw = larea->pe = larea->pt;
17460    larea->full = FALSE;
17461    return CM_SUCCESS;
17462 }
DWORD dm_buffer_time_get (void)
Definition at line 17294 of file midas.c.
References DMEM_BUFFER::last_active.
17296          : dm_buffer_time_get
17297
17298   Purpose: return the time from the last buffer switch.
17299
17300   Input:
17301     none
17302   Output:
17303     none
17304   Function value:
17305     DWORD        time stamp
17306
17307 \********************************************************************/
17308 {
17309    return (dm.last_active);
17310 }
EVENT_HEADER* dm_pointer_get (void)
Definition at line 17314 of file midas.c.
References DMEM_BUFFER::area1, DMEM_BUFFER::area2, cm_msg, dm_active_full(), dm_area_send(), dm_area_switch(), DMEM_AREA::full, DMEM_BUFFER::last_active, MERROR, DMEM_BUFFER::pa, DMEM_AREA::pw, RPC_NET_ERROR, DMEM_BUFFER::serial, DMEM_AREA::serial, ss_millitime(), ss_sleep(), status, timeout, and TRUE.
Referenced by interrupt_routine(), scheduler(), send_event(), and yb_file_fragment().
17316          : dm_pointer_get
17317
17318   Purpose: Get pointer to next free location in event buffer.
17319            after 10sec tries, it times out return NULL indicating a
17320            serious problem, i.e. abort.
17321   REMARK : Cannot be called twice in a raw due to +sizeof(INT)
17322   Input:
17323     none
17324   Output:
17325     DM_BUFFER * dm    local valid dm to work on
17326   Function value:
17327     EVENT_HEADER *    Pointer to free location
17328     NULL              cannot after several attempt get free space => abort
17329 \********************************************************************/
17330 {
17331    int timeout, status;
17332
17333    /* Is there still space in the active area ? */
17334    if (!dm_active_full())
17335       return (EVENT_HEADER *) (dm.pa->pw + sizeof(INT));
17336
17337    /* no more space => switch area */
17338
17339    /* Tag current area with global dm.serial for order consistency */
17340    dm.pa->serial = dm.serial++;
17341
17342    /* set active buffer time stamp */
17343    dm.last_active = ss_millitime();
17344
17345    /* mark current area full */
17346    dm.pa->full = TRUE;
17347
17348    /* Trigger/do data transfer (Now/don't wait) */
17349    if ((status = dm_area_send()) == RPC_NET_ERROR) {
17350       cm_msg(MERROR, "dm_pointer_get()", "Net error or timeout %i", status);
17351       return NULL;
17352    }
17353
17354    /* wait switch completion (max 10 sec) */
17355    timeout = ss_millitime();    /* with timeout */
17356    while ((ss_millitime() - timeout) < 10000) {
17357       dm.pa = dm_area_switch();
17358       if (dm.pa != NULL)
17359          return (EVENT_HEADER *) (dm.pa->pw + sizeof(INT));
17360       ss_sleep(200);
17361 #ifdef DM_DEBUG
17362       printf(" waiting for space ... %i  dm_buffer  %i %i %i %i %i \n",
17363              ss_millitime() - timeout, dm.area1.full, dm.area2.full, dm.area1.serial,
17364              dm.area2.serial, dm.serial);
17365 #endif
17366    }
17367
17368    /* Time running out abort */
17369    cm_msg(MERROR, "dm_pointer_get", "Timeout due to buffer full");
17370    return NULL;
17371 }
int dm_pointer_increment (INT buffer_handle, INT event_size)
Definition at line 17375 of file midas.c.
References _send_sock, ALIGN8, bm_send_event(), CM_SUCCESS, DMEM_BUFFER::pa, DMEM_AREA::pe, DMEM_AREA::pw, and SYNC.
Referenced by interrupt_routine(), scheduler(), send_event(), and yb_file_fragment().
17377          : dm_pointer_increment
17378
17379   Purpose: Increment write pointer of event buffer after an event
17380            has been copied into the buffer (at an address previously
17381            obtained via dm_pointer_get)
17382   Input:
17383     INT buffer_handle         Buffer handle event should be sent to
17384     INT event_size            Event size in bytes including header
17385   Output:
17386     none
17387   Function value:
17388     CM_SUCCESS                Successful completion
17389     status                    from bm_send_event for local connection
17390 \********************************************************************/
17391 {
17392    INT aligned_event_size;
17393
17394    /* if not connected remotely, use bm_send_event */
17395    if (_send_sock == 0) {
17396       *((INT *) dm.pa->pw) = buffer_handle;
17397       return bm_send_event(buffer_handle, dm.pa->pw + sizeof(INT), event_size, SYNC);
17398    }
17399    aligned_event_size = ALIGN8(event_size);
17400
17401    *((INT *) dm.pa->pw) = buffer_handle;
17402
17403    /* adjust write pointer */
17404    dm.pa->pw += sizeof(INT) + aligned_event_size;
17405
17406    /* adjust end pointer */
17407    dm.pa->pe = dm.pa->pw;
17408
17409    return CM_SUCCESS;
17410 }
INT dm_task (void * pointer)
Definition at line 17529 of file midas.c.
References DMEM_BUFFER::action, DMEM_BUFFER::area1, DMEM_BUFFER::area2, cm_msg, CM_SUCCESS, dm_area_full(), dm_buffer_send(), DM_FLUSH, DM_KILL, DM_SEND, DMEM_AREA::full, MERROR, DMEM_BUFFER::pa, DMEM_BUFFER::sem_flush, DMEM_BUFFER::sem_send, DMEM_BUFFER::serial, DMEM_AREA::serial, ss_millitime(), ss_mutex_release(), ss_mutex_wait_for(), ss_sleep(), status, and timeout.
Referenced by dm_buffer_create().
17531          : dm_task
17532
17533   Purpose: async send events doing a double purpose:
17534   a) send full buffer if found (DM_SEND) set by dm_active_full
17535   b) flush full areas (DM_FLUSH) set by dm_area_flush
17536   Input:
17537   none
17538   Output:
17539   none
17540   Function value:
17541   none
17542   \********************************************************************/
17543 {
17544 #ifdef DM_DUAL_THREAD
17545    INT status, timeout;
17546
17547    printf("Semaphores initialization ... in areaSend ");
17548    /* Check or Wait for semaphore to be setup */
17549    timeout = ss_millitime();
17550    while ((ss_millitime() - timeout < 3000) && (dm.sem_send == 0))
17551       ss_sleep(200);
17552    if (dm.sem_send == 0)
17553       goto kill;
17554
17555 #ifdef OS_WINNT
17556    /* necessary for true MUTEX (NT) get semaphore */
17557    ss_mutex_wait_for(dm.sem_flush, 0);
17558 #endif
17559
17560    /* Main FOREVER LOOP */
17561    printf("task areaSend ready...\n");
17562    while (1) {
17563       if (!dm_area_full()) {
17564          /* wait semaphore here ........ 0 == forever */
17565          ss_mutex_wait_for(dm.sem_send, 0);
17566 #ifdef OS_WINNT
17567          /* necessary for true MUTEX (NT) give semaphore */
17568          ss_mutex_release(dm.sem_send);
17569 #endif
17570       }
17571       if (dm.action == DM_SEND) {
17572 #ifdef DM_DEBUG
17573          printf("Send %i %i ", dm.area1.full, dm.area2.full);
17574 #endif
17575          /* DM_SEND : Empty the oldest buffer only. */
17576          if (dm.area1.full && dm.area2.full) {
17577             if (dm.area1.serial <= dm.area2.serial)
17578                status = dm_buffer_send(&dm.area1);
17579             else
17580                status = dm_buffer_send(&dm.area2);
17581          } else if (dm.area1.full)
17582             status = dm_buffer_send(&dm.area1);
17583          else if (dm.area2.full)
17584             status = dm_buffer_send(&dm.area2);
17585
17586          if (status != CM_SUCCESS) {
17587             cm_msg(MERROR, "dm_task", "network error %i", status);
17588             goto kill;
17589          }
17590       } /* if DM_SEND */
17591       else if (dm.action == DM_FLUSH) {
17592          /* DM_FLUSH: User is waiting for completion (i.e. No more incomming
17593             events) Empty both area in order independently of being full or not */
17594          if (dm.area1.serial <= dm.area2.serial) {
17595             status = dm_buffer_send(&dm.area1);
17596             if (status != CM_SUCCESS)
17597                goto error;
17598             status = dm_buffer_send(&dm.area2);
17599             if (status != CM_SUCCESS)
17600                goto error;
17601          } else {
17602             status = dm_buffer_send(&dm.area2);
17603             if (status != CM_SUCCESS)
17604                goto error;
17605             status = dm_buffer_send(&dm.area1);
17606             if (status != CM_SUCCESS)
17607                goto error;
17608          }
17609          /* reset counter */
17610          dm.area1.serial = 0;
17611          dm.area2.serial = dm.serial = 1;
17612 #ifdef DM_DEBUG
17613          printf("dm.action: Flushing ...\n");
17614 #endif
17615          /* reset area to #1 */
17616          dm.pa = &dm.area1;
17617
17618          /* release user */
17619          ss_mutex_release(dm.sem_flush);
17620 #ifdef OS_WINNT
17621          /* necessary for true MUTEX (NT) get semaphore back */
17622          ss_mutex_wait_for(dm.sem_flush, 0);
17623 #endif
17624       }
17625       /* if FLUSH */
17626       if (dm.action == DM_KILL)
17627          goto kill;
17628
17629    }                            /* FOREVER (go back wainting for semaphore) */
17630
17631    /* kill spawn now */
17632  error:
17633    cm_msg(MERROR, "dm_area_flush", "aSync Net error");
17634  kill:
17635    ss_mutex_release(dm.sem_flush);
17636 #ifdef OS_WINNT
17637    ss_mutex_wait_for(dm.sem_flush, 1);
17638 #endif
17639    cm_msg(MERROR, "areaSend", "task areaSend exiting now");
17640    exit;
17641    return 1;
17642 #else
17643    printf("DM_DUAL_THREAD not defined\n");
17644    return 0;
17645 #endif
17646 }
Variable Documentation
DMEM_BUFFER dm
Definition at line 17065 of file midas.c.
INT dm_user_max_event_size
Definition at line 17066 of file midas.c.