AlcapDAQ: MCAENPulseIslandSortAndStitch
MCAENPulseIslandSortAndStitch
[Raw Data Process]
Sort and stitches the TPIs.
Functions
static INT module_event_sort_and_stitch (EVENT_HEADER *pheader, void *pevent)
This method sorts pulses in time and then stitches them together.
static INT module_init_sort_and_stitch ()
static bool pulse_islands_t_comp (TPulseIsland *a, TPulseIsland *b)
Ordering of pulse islands in time base on timestamp.
static void pulse_islands_stitch (std::vector< TPulseIsland * > &pulses, unsigned int nSamples)
Stitch islands together if second of two that are time ordered is less than expected.
Variables
HNDLE hDB
TGlobalData * gData
Object to hold data used and produced by modules throughout alcapana stage of analysis.
TSetupData * gSetup
Hardware information about digitizers and detectors to be used during alcapana stage of analysis.
static unsigned int nUHSamples
Number of samples we expect a UH CAEN pulse to be no shorter than (from ODB).
static unsigned int nBUSamples
Number of samples we expect a BU CAEN pulse to be no shorter than (from ODB).
static unsigned int nUHPreSamples
Number of samples saved before a trigger on UH CAEN (from ODB).
static unsigned int nBUPreSamples
Number of samples saved before a trigger on BU CAEN (from ODB).
ANA_MODULE MCAENPulseIslandSortAndStitch_module
Detailed Description
Sort and stitches the TPIs.
Author:
John R Quirk
First sorts pulses based on time stamp (which is the timing that should be used). Then, if of two consecutive pulses the second is shorter than expected, stitch it to the first.
Function Documentation
INT module_event_sort_and_stitch (EVENT_HEADER * pheader, void * pevent) [static]
This method sorts pulses in time and then stitches them together.
Definition at line 111 of file MCAENPulseIslandSortAndStitch.cpp.
References TGlobalData::fPulseIslandToChannelMap, TSetupData::IsBostonCAEN(), TSetupData::IsHoustonCAEN(), nBUSamples, nUHSamples, pulse_islands_stitch(), and pulse_islands_t_comp().
{
  // Some typedefs
  typedef std::map<std::string, std::vector<TPulseIsland*> > TStringPulseIslandMap;
  // Fetch a reference to the gData structure that stores a map
  // of (bank_name, vector<TPulseIsland*>) pairs
  TStringPulseIslandMap& pulse_islands_map = gData->fPulseIslandToChannelMap;
  for (std::map<std::string, std::vector<TPulseIsland*> >::iterator it=pulse_islands_map.begin(); it!=pulse_islands_map.end(); ++it)
    {
      unsigned int nSamples = 0;
      if (TSetupData::IsBostonCAEN(it->first))
        nSamples = nBUSamples;
      else if (TSetupData::IsHoustonCAEN(it->first))
        nSamples = nUHSamples;
      if (nSamples != 0) {
        std::vector<TPulseIsland*> &v = it->second;
        std::sort(v.begin(), v.end(), pulse_islands_t_comp);
        pulse_islands_stitch(v, nSamples);
      }
    }
  return SUCCESS;
}
INT module_init_sort_and_stitch () [static]
Definition at line 80 of file MCAENPulseIslandSortAndStitch.cpp.
References hDB, nBUPreSamples, nBUSamples, nUHPreSamples, and nUHSamples.
{
   /*** Get necessary data from ODB ***/
  char key[80];
  int size;
  unsigned int post_trigger_percentage;
  sprintf(key, "/Equipment/Crate 4/Settings/CAEN0/waveform length");
  size = sizeof(nUHSamples);
  db_get_value(hDB, 0, key, &nUHSamples, &size, TID_DWORD, 1);
  post_trigger_percentage = 80; // This is hardcoded in the frontend
  nUHPreSamples = (int) (0.01 * ((100 - post_trigger_percentage) * nUHSamples));
  return SUCCESS;
  sprintf(key, "/Equipment/Crate 5/Settings/CAEN/waveform length");
  size = sizeof(nBUSamples);
  db_get_value(hDB, 0, key, &nBUSamples, &size, TID_DWORD, 1);
  sprintf(key, "/Equipment/Crate 5/Settings/CAEN/post_trigger_size");
  size = sizeof(post_trigger_percentage);
  db_get_value(hDB, 0, key, &post_trigger_percentage, &size, TID_BYTE, 1);
  //nBUPreSamples = (int) (0.01 * ((100 - post_trigger_percentage) * nBUSamples));
  nBUPreSamples = 20; // From the Golden Data, it looks like there are 20 presamples.
                    // The frontend does not seem to correctly load post_trigger_size
                    // onto the CAEN.
  return SUCCESS;
}
void pulse_islands_stitch (std::vector< TPulseIsland * > & pulses, unsigned int nSamples) [static]
Stitch islands together if second of two that are time ordered is less than expected.
If a pulse form the CAEN is less than expected, where what's expected is set in the ODB before a run, that usually means that this second pulse was cause by trigger pile-up of the first, and should be stitched onto the end.
Parameters:
[in] pulses Vector of TPIs contained time-sorted CANE pulses to stitch if necessary
[in] nSamples Number of samples we expect a pulse to be no shorter than; if shorter than this, a pulse is stitched to the end of the preceding pulse.
Todo:
Instead stitch together if the timestamps line up appropriately.
Definition at line 162 of file MCAENPulseIslandSortAndStitch.cpp.
References TPulseIsland::GetBankName(), TPulseIsland::GetSamples(), and TPulseIsland::GetTimeStamp().
Referenced by module_event_sort_and_stitch().
{
  unsigned int nPulses = pulses.size();
  if (nPulses == 0) return;
  std::vector<int> next_samples, current_samples;
  TPulseIsland* temp_pulse;
  for (unsigned int iPulse = 0; iPulse < nPulses - 1; ++iPulse) {
    next_samples = pulses[iPulse + 1]->GetSamples();
    // If the next pulse is less than the set number of samples,
    // it's a continuation of this pulse
    while (next_samples.size() < nSamples) {
      current_samples = pulses[iPulse]->GetSamples();
      for (unsigned int i = 0; i < next_samples.size(); ++i)
        current_samples.push_back(next_samples[i]);
      temp_pulse = pulses[iPulse];
      pulses[iPulse] = new TPulseIsland(temp_pulse->GetTimeStamp(), current_samples, temp_pulse->GetBankName());
      delete temp_pulse;
      delete pulses[iPulse + 1];
      pulses.erase(pulses.begin() + iPulse + 1);
      if (!(iPulse < --nPulses - 1)) break;
      next_samples = pulses[iPulse + 1]->GetSamples();
    }
  }
}
bool pulse_islands_t_comp (TPulseIsland * a, TPulseIsland * b) [static]
Ordering of pulse islands in time base on timestamp.
Definition at line 140 of file MCAENPulseIslandSortAndStitch.cpp.
References TPulseIsland::GetTimeStamp().
Referenced by module_event_sort_and_stitch().
{
  return (a->GetTimeStamp() < b->GetTimeStamp());
}
Variable Documentation
TGlobalData* gData
Object to hold data used and produced by modules throughout alcapana stage of analysis.
Definition at line 76 of file analyzer.cpp.
TSetupData* gSetup
Hardware information about digitizers and detectors to be used during alcapana stage of analysis.
Definition at line 80 of file analyzer.cpp.
HNDLE hDB
Referenced by MDQ_DAQLivetime_eor(), MDQ_DigitizerOverflow_init(), MDQ_FADCBufferOverflow_init(), MDQ_FADCPacketLoss_init(), MDQ_IslandRate_eor(), MDQ_MuPC_init(), MDQ_RunTime_eor(), MDQ_TDCCheck_eor(), MDQ_Thresholds_eor(), module_init(), module_init_sort_and_stitch(), and UpdateDetectorBankNameMap().
ANA_MODULE MCAENPulseIslandSortAndStitch_module
Initial value:
{
        "MCAENPulseIslandSortAndStitch",
        "Vladimir Tishchenko",
        module_event_sort_and_stitch,
        NULL,
        NULL,
        module_init_sort_and_stitch,
        NULL,
        NULL,
        0,
        NULL,
}
Definition at line 62 of file MCAENPulseIslandSortAndStitch.cpp.
unsigned int nBUPreSamples [static]
Number of samples saved before a trigger on BU CAEN (from ODB).
Definition at line 60 of file MCAENPulseIslandSortAndStitch.cpp.
Referenced by module_init_sort_and_stitch().
unsigned int nBUSamples [static]
Number of samples we expect a BU CAEN pulse to be no shorter than (from ODB).
Definition at line 52 of file MCAENPulseIslandSortAndStitch.cpp.
Referenced by module_event_sort_and_stitch(), and module_init_sort_and_stitch().
unsigned int nUHPreSamples [static]
Number of samples saved before a trigger on UH CAEN (from ODB).
Definition at line 56 of file MCAENPulseIslandSortAndStitch.cpp.
Referenced by module_init_sort_and_stitch().
unsigned int nUHSamples [static]
Number of samples we expect a UH CAEN pulse to be no shorter than (from ODB).
Definition at line 48 of file MCAENPulseIslandSortAndStitch.cpp.
Referenced by module_event_sort_and_stitch(), and module_init_sort_and_stitch().