AlcapDAQ: Camac Functions (camxxx)
Camac Functions (camxxx)
[Midas CAMAC standard]
Functions
EXTERNAL INLINE void EXPRT cam16i (const int c, const int n, const int a, const int f, WORD *d)
EXTERNAL INLINE void EXPRT cam24i (const int c, const int n, const int a, const int f, DWORD *d)
EXTERNAL INLINE void EXPRT cam8i_q (const int c, const int n, const int a, const int f, BYTE *d, int *x, int *q)
EXTERNAL INLINE void EXPRT cam16i_q (const int c, const int n, const int a, const int f, WORD *d, int *x, int *q)
EXTERNAL INLINE void EXPRT cam24i_q (const int c, const int n, const int a, const int f, DWORD *d, int *x, int *q)
EXTERNAL INLINE void EXPRT cam16i_r (const int c, const int n, const int a, const int f, WORD **d, const int r)
EXTERNAL INLINE void EXPRT cam24i_r (const int c, const int n, const int a, const int f, DWORD **d, const int r)
EXTERNAL INLINE void EXPRT cam8i_rq (const int c, const int n, const int a, const int f, BYTE **d, const int r)
EXTERNAL INLINE void EXPRT cam16i_rq (const int c, const int n, const int a, const int f, WORD **d, const int r)
EXTERNAL INLINE void EXPRT cam24i_rq (const int c, const int n, const int a, const int f, DWORD **d, const int r)
EXTERNAL INLINE void EXPRT cam8i_sa (const int c, const int n, const int a, const int f, BYTE **d, const int r)
EXTERNAL INLINE void EXPRT cam16i_sa (const int c, const int n, const int a, const int f, WORD **d, const int r)
EXTERNAL INLINE void EXPRT cam24i_sa (const int c, const int n, const int a, const int f, DWORD **d, const int r)
EXTERNAL INLINE void EXPRT cam8i_sn (const int c, const int n, const int a, const int f, BYTE **d, const int r)
EXTERNAL INLINE void EXPRT cam16i_sn (const int c, const int n, const int a, const int f, WORD **d, const int r)
EXTERNAL INLINE void EXPRT cam24i_sn (const int c, const int n, const int a, const int f, DWORD **d, const int r)
EXTERNAL INLINE void EXPRT cami (const int c, const int n, const int a, const int f, WORD *d)
EXTERNAL INLINE void EXPRT cam8o (const int c, const int n, const int a, const int f, BYTE d)
EXTERNAL INLINE void EXPRT cam16o (const int c, const int n, const int a, const int f, WORD d)
EXTERNAL INLINE void EXPRT cam24o (const int c, const int n, const int a, const int f, DWORD d)
EXTERNAL INLINE void EXPRT cam8o_q (const int c, const int n, const int a, const int f, BYTE d, int *x, int *q)
EXTERNAL INLINE void EXPRT cam16o_q (const int c, const int n, const int a, const int f, WORD d, int *x, int *q)
EXTERNAL INLINE void EXPRT cam24o_q (const int c, const int n, const int a, const int f, DWORD d, int *x, int *q)
EXTERNAL INLINE void EXPRT cam8o_r (const int c, const int n, const int a, const int f, BYTE *d, const int r)
EXTERNAL INLINE void EXPRT cam16o_r (const int c, const int n, const int a, const int f, WORD *d, const int r)
EXTERNAL INLINE void EXPRT cam24o_r (const int c, const int n, const int a, const int f, DWORD *d, const int r)
EXTERNAL INLINE void EXPRT camo (const int c, const int n, const int a, const int f, WORD d)
EXTERNAL INLINE int EXPRT camc_chk (const int c)
EXTERNAL INLINE void EXPRT camc (const int c, const int n, const int a, const int f)
EXTERNAL INLINE void EXPRT camc_q (const int c, const int n, const int a, const int f, int *q)
EXTERNAL INLINE void EXPRT camc_sa (const int c, const int n, const int a, const int f, const int r)
EXTERNAL INLINE void EXPRT camc_sn (const int c, const int n, const int a, const int f, const int r)
EXTERNAL INLINE int EXPRT cam_init (void)
EXTERNAL INLINE int EXPRT cam_init_rpc (char *host_name, char *exp_name, char *fe_name, char *client_name, char *rpc_server)
EXTERNAL INLINE void EXPRT cam_exit (void)
EXTERNAL INLINE void EXPRT cam_inhibit_set (const int c)
EXTERNAL INLINE void EXPRT cam_inhibit_clear (const int c)
EXTERNAL INLINE int EXPRT cam_inhibit_test (const int c)
EXTERNAL INLINE void EXPRT cam_crate_clear (const int c)
EXTERNAL INLINE void EXPRT cam_crate_zinit (const int c)
EXTERNAL INLINE void EXPRT cam_lam_enable (const int c, const int n)
EXTERNAL INLINE void EXPRT cam_lam_disable (const int c, const int n)
EXTERNAL INLINE void EXPRT cam_lam_read (const int c, DWORD *lam)
EXTERNAL INLINE void EXPRT cam_lam_clear (const int c, const int n)
EXTERNAL INLINE int EXPRT cam_lam_wait (int *c, DWORD *n, const int millisec)
EXTERNAL INLINE void EXPRT cam_interrupt_enable (const int c)
EXTERNAL INLINE void EXPRT cam_interrupt_disable (const int c)
EXTERNAL INLINE int EXPRT cam_interrupt_test (const int c)
EXTERNAL INLINE void EXPRT cam_interrupt_attach (const int c, const int n, void(*isr)(void))
EXTERNAL INLINE void EXPRT cam_interrupt_detach (const int c, const int n)
Detailed Description
dox dox
Function Documentation
EXTERNAL INLINE void EXPRT cam16i (const int c, const int n, const int a, const int f, WORD * d)
16 bits input.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d data read out data
Returns:
void
Definition at line 156 of file hyt1331.c.
References CBD_DESC_T::baseCrate, cami(), CBDWL_D16, cmd, cnaf16(), ext, handle, NAFCMD, pwCC32_ADR, sjy_read(), and SJY_STOP_ON_WORD.
Referenced by cam16i_q(), cam16i_r(), cam16i_rq(), cam16i_sa(), cam16i_sn(), cam_crate_clear(), cam_crate_zinit(), cam_inhibit_clear(), cam_inhibit_set(), camc(), cami(), and mcstd_func().
{
   cami(c, n, a, f, d);
}
EXTERNAL INLINE void EXPRT cam16i_q (const int c, const int n, const int a, const int f, WORD * d, int * x, int * q)
16 bits input with Q response.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d data read out data
x X response (0:failed,1:success)
q Q resonpse (0:no Q, 1: Q)
Returns:
void
Definition at line 202 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam16i(), cami(), CCR, CDMA, cmd, CNAF, cnaf16(), CSR, csr(), CSR1, DH, DL, DLR, DM, DONE, FUN, GO, handle, hConn, ieee_last_X, INP, INPW, loop, LXQ, MCR, N_SHIFT, NAF, NAF1, NAF2, NAFCMD, OPST, OUTP, OUTPW, plCC32_ADR, RL, RM, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, sjy_get_qx(), SJY_Q_STOP, sjy_read(), STA, status, and WS_16BIT.
Referenced by cam16i_rq(), cam16i_sn(), cc_services(), cnaf16(), cnaf_callback(), cnafsub(), csmad(), cssa(), lrs2415_get(), lrs2415_get_current(), and mcstd_func().
{
   WORD adr;
   BYTE status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
   status = (BYTE) INP(adr + 6);
   *((BYTE *) d) = INP(adr);
   *(((BYTE *) d) + 1) = INP(adr + 2);
   *q = status & 1;
   *x = status >> 7;
}
EXTERNAL INLINE void EXPRT cam16i_r (const int c, const int n, const int a, const int f, WORD ** d, const int r)
Repeat 16 bits input.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d data read out data
r repeat time
Returns:
void
Definition at line 245 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam16i(), CCR, CDMA, cmd, CNAF, cnaf16_r(), CSR, CSR1, DL, DLR, DM, DONE, FUN, GO, handle, hConn, i, INP, INPW, loop, MCR, N_SHIFT, NAF, NAF1, NAF2, NAFCMD, OPST, OUTP, OUTP_P, OUTPW, pwCC32_ADR, RL, RM, RM_COUNT, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, SJY_Q_REPEAT, sjy_read(), STA, status, and WS_16BIT.
Referenced by mcstd_func().
{
   WORD adr, i, status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr + 6, a);
   OUTP_P(adr + 10, f);
   status = (BYTE) INP(adr + 6);
   *((BYTE *) * d) = INP(adr);
   *(((BYTE *) * d) + 1) = INP(adr + 2);        /* read the first word */
   (*d)++;
   INPW_P(adr + 12);            /* trigger first cycle */
   for (i = 0; i < (r - 1); i++)
      *((*d)++) = INPW(adr + 12);       /* read data and trigger next cycle */
}
EXTERNAL INLINE void EXPRT cam16i_rq (const int c, const int n, const int a, const int f, WORD ** d, const int r)
Repeat 16 bits input with Q stop.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d pointer to data read out
r repeat time
Returns:
void
Definition at line 318 of file hyt1331.c.
References cam16i(), cam16i_q(), cami(), cmd, cnaf16_r(), CNAF_nQ, csr(), handle, hConn, i, INP, NAFCMD, OUTP, OUTP_P, plCC32_ADR, RM_QMODE, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, SJY_Q_STOP, sjy_read(), and status.
Referenced by cnaf16(), cnaf_callback(), and mcstd_func().
{
   WORD adr, i;
   int fail;
   /* following code is disabled by above code */
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr + 6, a);
   /* Turn on the Q-mode for repeat until Q=1 in the INPW(adr+12) */
   OUTP(adr + 1, 0x10);
   OUTP_P(adr + 10, f);
   INPW_P(adr + 12);            /* trigger first cycle */
   for (i = 0; i < r; i++) {
      /* read data and trigger next cycle fail = no valid Q within 12usec */
      **d = INPW_P(adr + 12);
      fail = ((BYTE) INP(adr + 6)) & 0x20;      // going to test!
      if (fail)
         break;
      (*d)++;
   }
   /* Turn off the Q-mode for repeat until Q=1 in the INPW(adr+12) */
   OUTP(adr + 1, 0x0);
}
EXTERNAL INLINE void EXPRT cam16i_sa (const int c, const int n, const int a, const int f, WORD ** d, const int r)
Read the given CAMAC address and increment the sub-address by one. Repeat r times.
WORD pbkdat[4];
cam16i_sa(crate, 5, 0, 2, &pbkdat, 4);
equivalent to :
cam16i(crate, 5, 0, 2, &pbkdat[0]);
cam16i(crate, 5, 1, 2, &pbkdat[1]);
cam16i(crate, 5, 2, 2, &pbkdat[2]);
cam16i(crate, 5, 3, 2, &pbkdat[3]);
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d pointer to data read out
r number of consecutive sub-address to read
Returns:
void
Definition at line 379 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam16i(), cami(), CCR, CDMA, CNAF, cnaf16_r(), CSR, CSR1, DL, DLR, DM, DONE, FUN, gbl_sw1d, GO, handle, hConn, i, INP, INPW, loop, MCR, N_SHIFT, NAF, NAF1, NAF2, OPST, OUTP, OUTP_P, OUTPW, pwCC32_ADR, RL, RM, RM_ASCAN, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, STA, status, and WS_16BIT.
Referenced by mcstd_func().
{
   WORD adr, i;
   if (gbl_sw1d[c]) {
      adr = io_base[c >> 2] + ((c % 3) << 4);
      /* enable auto increment */
      OUTP_P(adr + 10, 49);
      OUTP(adr + 8, n);
      OUTP(adr + 6, a - 1);
      OUTP_P(adr + 10, f);
      INPW_P(adr + 12);
      for (i = 0; i < r; i++)
         *((*d)++) = INPW_P(adr + 12);  /* read data and trigger next cycle */
      /* disable auto increment */
      OUTP_P(adr + 10, 48);
   } else
      for (i = 0; i < r; i++)
         cami(c, n, a + i, f, (*d)++);
}
EXTERNAL INLINE void EXPRT cam16i_sn (const int c, const int n, const int a, const int f, WORD ** d, const int r)
Read the given CAMAC address and increment the station number by one. Repeat r times.
WORD pbkdat[4];
cam16i_sa(crate, 5, 0, 2, &pbkdat, 4);
equivalent to :
cam16i(crate, 5, 0, 2, &pbkdat[0]);
cam16i(crate, 6, 0, 2, &pbkdat[1]);
cam16i(crate, 7, 0, 2, &pbkdat[2]);
cam16i(crate, 8, 0, 2, &pbkdat[3]);
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d pointer to data read out
r number of consecutive station to read
Returns:
void
Definition at line 436 of file hyt1331.c.
References cam16i(), cam16i_q(), CNAF, cnaf16_r(), hConn, i, RM_NSCAN, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, and status.
{
   int i;
   for (i = 0; i < r; i++)
      cam16i(c, n + i, a, f, (*d)++);
}
EXTERNAL INLINE void EXPRT cam16o (const int c, const int n, const int a, const int f, WORD d)
Write data to given CAMAC address.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (16..31)
d data to be written to CAMAC
Returns:
void
Definition at line 486 of file hyt1331.c.
References CBD_DESC_T::baseCrate, cam16o_q(), camo(), CBDWL_D16, ext, handle, pwCC32_ADR, qdummy, and xdummy.
Referenced by cam16o_q(), cam16o_r(), cam_crate_clear(), cam_crate_zinit(), cam_inhibit_clear(), cam_inhibit_set(), camc(), camo(), isr(), and mcstd_func().
{
   camo(c, n, a, f, d);
}
EXTERNAL INLINE void EXPRT cam16o_q (const int c, const int n, const int a, const int f, WORD d, int * x, int * q)
Write data to given CAMAC address with Q response.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (16..31)
d data to be written to CAMAC
x X response (0:failed,1:success)
q Q resonpse (0:no Q, 1: Q)
Returns:
void
Definition at line 508 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam16o(), cami(), CCR, CDMA, cmd, CNAF, cnaf16(), CSR, csr(), CSR1, DH, DL, DLR, DM, DONE, FUN, GO, handle, hConn, ieee_last_X, INP, INPW, loop, MCR, N_SHIFT, NAF, NAF1, NAF2, NAFCMD, OPST, OUTP, OUTPW, pwCC32_ADR, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, sjy_get_qx(), SJY_STOP_ON_WORD, sjy_write(), STA, status, WL, WM, and WS_16BIT.
Referenced by cam16o(), cc_services(), cnaf16(), cnaf_callback(), cnafsub(), cssa(), and mcstd_func().
{
   unsigned int adr, status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr, (BYTE) d);
   OUTP(adr + 2, *(((BYTE *) & d) + 1));
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
   status = (BYTE) INP(adr + 6);
   *q = status & 1;
   *x = status >> 7;
}
EXTERNAL INLINE void EXPRT cam16o_r (const int c, const int n, const int a, const int f, WORD * d, const int r)
Repeat write data to given CAMAC address r times.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (16..31)
d data to be written to CAMAC
r number of repeatition
Returns:
void
Definition at line 566 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam16o(), CCR, CDMA, cmd, CNAF, cnaf16_r(), CSR, CSR1, DH, DL, DLR, DM, DONE, FUN, GO, handle, hConn, i, INPW, MCR, N_SHIFT, NAF, NAF1, NAF2, NAFCMD, OUTP, OUTPW, pwCC32_ADR, RM_COUNT, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, SJY_Q_REPEAT, sjy_write(), STA, status, WL, WM, and WS_16BIT.
Referenced by mcstd_func().
{
   WORD adr, i;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   /* trigger first cycle */
   OUTP(adr + 8, n);
   OUTP(adr, *((BYTE *) d));
   OUTP(adr + 2, *(((BYTE *) d) + 1));
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
   for (i = 0; i < r - 1; i++)
      OUTPW(adr + 12, *(++d));  /* write data and trigger next cycle */
}
EXTERNAL INLINE void EXPRT cam24i (const int c, const int n, const int a, const int f, DWORD * d)
24 bits input.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d data read out data
Returns:
void
Definition at line 163 of file hyt1331.c.
References A_SHIFT, ADD, CBD_DESC_T::baseCrate, C, CACY, CBDWL_D24, CCR, CDMA, cmd, CNAF, cnaf24(), CSR, CSR1, DH, DHR, DL, DLR, DM, DONE, ext, FUN, GO, handle, hConn, INP, INPW, iobase, loop, MCR, N_SHIFT, NAF, NAF1, NAF2, NAFCMD, OPST, OUTP, OUTPW, plCC32_ADR, regCOMMAND, regDATA, regGO, RH, RL, RM, rpc_client_call(), RPC_CNAF24, RPC_SUCCESS, size, SJY_D24_MODE, sjy_read(), SJY_STOP_ON_WORD, STA, status, wait_done(), and WS_24BIT.
Referenced by cam24i_q(), cam24i_r(), cam24i_rq(), cam24i_sa(), cam24i_sn(), cam_lam_disable(), cam_lam_enable(), cam_lam_read(), main(), mcstd_func(), read_deferred_event(), read_mantrig_event(), read_scaler_event(), and s500_read().
{
   WORD adr;
   BYTE status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
   status = (BYTE) INP(adr + 6);
   *((BYTE *) d) = INP(adr);
   *(((BYTE *) d) + 1) = INP(adr + 2);
   *(((BYTE *) d) + 2) = INP(adr + 4);
   *(((BYTE *) d) + 3) = 0;
}
EXTERNAL INLINE void EXPRT cam24i_q (const int c, const int n, const int a, const int f, DWORD * d, int * x, int * q)
24 bits input with Q response.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d data read out data
x X response (0:failed,1:success)
q Q resonpse (0:no Q, 1: Q)
Returns:
void
Definition at line 223 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam24i(), cami(), CCR, CDMA, cmd, CNAF, cnaf24(), CSR, csr(), CSR1, DH, DHR, DL, DLR, DM, DONE, FUN, GO, handle, hConn, ieee_last_X, INP, INPW, iobase, loop, LXQ, MCR, N_SHIFT, NAF, NAF1, NAF2, NAFCMD, OPST, OUTP, OUTPW, plCC32_ADR, regCOMMAND, regDATA, regGO, RH, RL, RM, rpc_client_call(), RPC_CNAF24, RPC_SUCCESS, size, SJY_D24_MODE, sjy_get_qx(), SJY_Q_STOP, sjy_read(), STA, status, wait_done(), and WS_24BIT.
Referenced by cam24i_rq(), cam24i_sn(), cc_services(), cfmad(), cfsa(), cnaf24(), cnaf_callback(), cnafsub(), and mcstd_func().
{
   WORD adr, status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
   status = (BYTE) INP(adr + 6);
   *((BYTE *) d) = INP(adr);
   *(((BYTE *) d) + 1) = INP(adr + 2);
   *(((BYTE *) d) + 2) = INP(adr + 4);
   *(((BYTE *) d) + 3) = 0;
   *q = status & 1;
   *x = status >> 7;
}
EXTERNAL INLINE void EXPRT cam24i_r (const int c, const int n, const int a, const int f, DWORD ** d, const int r)
Repeat 24 bits input.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d data read out
r repeat time
Returns:
void
Definition at line 269 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam24i(), CCR, CDMA, cmd, CNAF, cnaf24_r(), CSR, CSR1, DH, DHR, DL, DLR, DM, DONE, FUN, GO, handle, hConn, i, INP, INPW, loop, MCR, N_SHIFT, NAF, NAF1, NAF2, NAFCMD, OPST, OUTP, OUTPW, plCC32_ADR, RH, RL, RM, RM_COUNT, rpc_client_call(), RPC_CNAF24, RPC_SUCCESS, size, SJY_D24_MODE, SJY_Q_REPEAT, sjy_read(), STA, status, and WS_24BIT.
Referenced by mcstd_func().
{
   WORD adr, i, status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr + 6, a);
   for (i = 0; i < r; i++) {
      OUTP(adr + 10, f);
      status = (BYTE) INP(adr + 6);
      *((BYTE *) * d) = INP(adr);
      *(((BYTE *) * d) + 1) = INP(adr + 2);
      *(((BYTE *) * d) + 2) = INP(adr + 4);
      *(((BYTE *) * d) + 3) = 0;
      (*d)++;
   }
   /*
      gives unrealiable results, SR 6.4.00
      adr = io_base[c >> 2]+((c % 3)<<4);
      OUTP(adr+8, n);
      OUTP(adr+6, a);
      OUTP_P(adr+10,f);
      status = (BYTE) INP(adr+6);
      *((BYTE *) *d) = INP(adr);
      *(((BYTE *) *d)+1) = INP(adr+2); // read the first word
      *(((BYTE *) *d)+2) = INP(adr+4);
      *(((BYTE *) *d)+3) = 0;
      (*d)++;
      INPW_P(adr+12); // trigger first cycle
      for (i=0 ; i<(r-1) ; i++)
      {
      *(((BYTE *) *d)+2) = INP_P(adr+4);
      *(((BYTE *) *d)+3) = 0;
      *((WORD *) *d) = INPW_P(adr+12);
      (*d)++;
      }
    */
}
EXTERNAL INLINE void EXPRT cam24i_rq (const int c, const int n, const int a, const int f, DWORD ** d, const int r)
Repeat 24 bits input with Q stop.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d pointer to data read out
r repeat time
Returns:
void
Definition at line 348 of file hyt1331.c.
References cam24i(), cam24i_q(), cami(), cmd, cnaf24_r(), CNAF_nQ, csr(), handle, hConn, i, INP, NAFCMD, OUTP, OUTP_P, plCC32_ADR, RM_QMODE, rpc_client_call(), RPC_CNAF24, RPC_SUCCESS, size, SJY_D24_MODE, SJY_Q_STOP, sjy_read(), and status.
Referenced by cnaf24(), cnaf_callback(), and mcstd_func().
{
   WORD adr;
   int i, fail;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr + 6, a);
   /* Turn on the Q-mode for repeat until Q=1 in the INPW(adr+12) */
   OUTP(adr + 1, 0x10);
   OUTP_P(adr + 10, f);
   INPW_P(adr + 12);            /* trigger first cycle */
   for (i = 0; i < r; i++) {
      /* read data and trigger next cycle fail = no valid Q within 12usec */
      *(((BYTE *) * d) + 2) = INP(adr + 4);
      *(((BYTE *) * d) + 3) = 0;
      *((WORD *) * d) = INPW_P(adr + 12);
      fail = ((BYTE) INP(adr + 6)) & 0x20;      // going to test!
      if (fail)
         break;
      (*d)++;
   }
   /* Turn off the Q-mode for repeat until Q=1 in the INPW(adr+12) */
   OUTP(adr + 1, 0x0);
}
EXTERNAL INLINE void EXPRT cam24i_sa (const int c, const int n, const int a, const int f, DWORD ** d, const int r)
Read the given CAMAC address and increment the sub-address by one. Repeat r times.
DWORD pbkdat[8];
cam24i_sa(crate, 5, 0, 2, &pbkdat, 8);
equivalent to
cam24i(crate, 5, 0, 2, &pbkdat[0]);
cam24i(crate, 6, 0, 2, &pbkdat[1]);
cam24i(crate, 7, 0, 2, &pbkdat[2]);
cam24i(crate, 8, 0, 2, &pbkdat[3]);
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d pointer to data read out
r number of consecutive sub-address to read
Returns:
void
Definition at line 405 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam24i(), CCR, CDMA, CNAF, cnaf24_r(), CSR, CSR1, DH, DHR, DL, DLR, DM, DONE, FUN, gbl_sw1d, GO, handle, hConn, i, INP, INPW, loop, MCR, N_SHIFT, NAF, NAF1, NAF2, OPST, OUTP, OUTP_P, OUTPW, plCC32_ADR, RH, RL, RM, RM_ASCAN, rpc_client_call(), RPC_CNAF24, RPC_SUCCESS, size, STA, status, and WS_24BIT.
Referenced by mcstd_func().
{
   WORD adr, i;
   if (gbl_sw1d[c]) {
      adr = io_base[c >> 2] + ((c % 3) << 4);
      /* enable auto increment */
      OUTP_P(adr + 10, 49);
      OUTP(adr + 8, n);
      OUTP(adr + 6, a - 1);
      OUTP_P(adr + 10, f);
      INPW_P(adr + 12);
      for (i = 0; i < r; i++) {
         /* read data and trigger next cycle */
         *(((BYTE *) * d) + 2) = INP(adr + 4);
         *(((BYTE *) * d) + 3) = 0;
         *((WORD *) * d) = INPW_P(adr + 12);
         (*d)++;
      }
      /* disable auto increment */
      OUTP_P(adr + 10, 48);
   } else
      for (i = 0; i < r; i++)
         cam24i(c, n, a + i, f, (*d)++);
}
EXTERNAL INLINE void EXPRT cam24i_sn (const int c, const int n, const int a, const int f, DWORD ** d, const int r)
Read the given CAMAC address and increment the station number by one. Repeat r times.
DWORD pbkdat[4];
cam24i_sa(crate, 5, 0, 2, &pbkdat, 4);
equivalent to :
cam24i(crate, 5, 0, 2, &pbkdat[0]);
cam24i(crate, 6, 0, 2, &pbkdat[1]);
cam24i(crate, 7, 0, 2, &pbkdat[2]);
cam24i(crate, 8, 0, 2, &pbkdat[3]);
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d pointer to data read out
r number of consecutive station to read
Returns:
void
Definition at line 447 of file hyt1331.c.
References cam24i(), cam24i_q(), CNAF, cnaf24_r(), hConn, i, RM_NSCAN, rpc_client_call(), RPC_CNAF24, RPC_SUCCESS, size, and status.
Referenced by mcstd_func().
{
   int i;
   for (i = 0; i < r; i++)
      cam24i(c, n + i, a, f, (*d)++);
}
EXTERNAL INLINE void EXPRT cam24o (const int c, const int n, const int a, const int f, DWORD d)
Write data to given CAMAC address.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (16..31)
d data to be written to CAMAC
Returns:
void
Definition at line 493 of file hyt1331.c.
References A_SHIFT, ADD, CBD_DESC_T::baseCrate, C, CACY, cam24o_q(), CBDWL_D24, CCR, CDMA, CNAF, cnaf24(), CSR, CSR1, DH, DHR, DL, DLR, DM, DONE, ext, FUN, GO, handle, hConn, INP, INPW, iobase, loop, MCR, N_SHIFT, NAF, NAF1, NAF2, OPST, OUTP, OUTPW, plCC32_ADR, qdummy, regCOMMAND, regDATA, regGO, rpc_client_call(), RPC_CNAF24, RPC_SUCCESS, size, STA, status, wait_done(), WH, WL, WM, WS_24BIT, and xdummy.
Referenced by cam24o_q(), cam24o_r(), cam_lam_disable(), cam_lam_enable(), main(), and mcstd_func().
{
   unsigned int adr;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr, (BYTE) d);
   OUTP(adr + 2, *(((BYTE *) & d) + 1));
   OUTP(adr + 4, *(((BYTE *) & d) + 2));
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
}
EXTERNAL INLINE void EXPRT cam24o_q (const int c, const int n, const int a, const int f, DWORD d, int * x, int * q)
Write data to given CAMAC address with Q response.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (16..31)
d data to be written to CAMAC
x X response (0:failed,1:success)
q Q response (0:no Q, 1: Q)
Returns:
void
Definition at line 527 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam24o(), cami(), CCR, CDMA, cmd, CNAF, cnaf24(), CSR, csr(), CSR1, DH, DHR, DL, DLR, DM, DONE, FUN, GO, handle, hConn, ieee_last_X, INP, INPW, iobase, loop, LXQ, MCR, N_SHIFT, NAF, NAF1, NAF2, NAFCMD, OPST, OUTP, OUTPW, plCC32_ADR, regCOMMAND, regDATA, regGO, rpc_client_call(), RPC_CNAF24, RPC_SUCCESS, size, SJY_D24_MODE, sjy_get_qx(), SJY_STOP_ON_WORD, sjy_write(), STA, status, wait_done(), WH, WL, WM, and WS_24BIT.
Referenced by cam24o(), cc_services(), cfsa(), cnaf24(), cnaf_callback(), cnafsub(), and mcstd_func().
{
   unsigned int adr, status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr, (BYTE) d);
   OUTP(adr + 2, *(((BYTE *) & d) + 1));
   OUTP(adr + 4, *(((BYTE *) & d) + 2));
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
   status = (BYTE) INP(adr + 6);
   *q = status & 1;
   *x = status >> 7;
}
EXTERNAL INLINE void EXPRT cam24o_r (const int c, const int n, const int a, const int f, DWORD * d, const int r)
Repeat write data to given CAMAC address r times.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (16..31)
d data to be written to CAMAC
r number of repeatition
Returns:
void
Definition at line 586 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam24o(), CCR, CDMA, cmd, CNAF, cnaf24_r(), CSR, CSR1, DH, DHR, DL, DLR, DM, DONE, FUN, GO, handle, hConn, i, INPW, MCR, N_SHIFT, NAF, NAF1, NAF2, NAFCMD, OUTP, OUTPW, plCC32_ADR, RM_COUNT, rpc_client_call(), RPC_CNAF24, RPC_SUCCESS, size, SJY_D24_MODE, SJY_Q_REPEAT, sjy_write(), STA, status, WH, WL, WM, and WS_24BIT.
Referenced by mcstd_func().
{
   WORD adr, i;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   /* trigger first cycle */
   OUTP(adr + 8, n);
   OUTP(adr, *((BYTE *) d));
   OUTP(adr + 2, *(((BYTE *) d) + 1));
   OUTP(adr + 4, *(((BYTE *) d) + 2));
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
   for (i = 0; i < r - 1; i++) {
      d++;
      OUTP(adr + 4, *(((BYTE *) d) + 2));
      OUTPW(adr + 12, (WORD) * d);      /* write data and trigger next cycle */
   }
}
EXTERNAL INLINE void EXPRT cam8i_q (const int c, const int n, const int a, const int f, BYTE * d, int * x, int * q)
8 bits input with Q response.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d data read out data
x X response (0:failed,1:success)
q Q resonpse (0:no Q, 1: Q)
Returns:
void
Definition at line 182 of file hyt1331.c.
References cnaf8(), INP, iobase, OUTP, OUTPW, regCOMMAND, regDATA, regGO, status, and wait_done().
{
   WORD adr;
   BYTE status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
   status = (BYTE) INP(adr + 6);
   *((BYTE *) d) = INP(adr);
   *q = status & 1;
   *x = status >> 7;
}
EXTERNAL INLINE void EXPRT cam8i_rq (const int c, const int n, const int a, const int f, BYTE ** d, const int r)
Repeat 8 bits input with Q stop.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d pointer to data read out
r repeat time
Returns:
void
EXTERNAL INLINE void EXPRT cam8i_sa (const int c, const int n, const int a, const int f, BYTE ** d, const int r)
Read the given CAMAC address and increment the sub-address by one. Repeat r times.
BYTE pbkdat[4];
cam8i_sa(crate, 5, 0, 2, &pbkdat, 4);
equivalent to :
cam8i(crate, 5, 0, 2, &pbkdat[0]);
cam8i(crate, 5, 1, 2, &pbkdat[1]);
cam8i(crate, 5, 2, 2, &pbkdat[2]);
cam8i(crate, 5, 3, 2, &pbkdat[3]);
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d pointer to data read out
r number of consecutive sub-address to read
Returns:
void
EXTERNAL INLINE void EXPRT cam8i_sn (const int c, const int n, const int a, const int f, BYTE ** d, const int r)
Read the given CAMAC address and increment the station number by one. Repeat r times.
BYTE pbkdat[4];
cam8i_sa(crate, 5, 0, 2, &pbkdat, 4);
equivalent to :
cam8i(crate, 5, 0, 2, &pbkdat[0]);
cam8i(crate, 6, 0, 2, &pbkdat[1]);
cam8i(crate, 7, 0, 2, &pbkdat[2]);
cam8i(crate, 8, 0, 2, &pbkdat[3]);
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (0..7)
d pointer to data read out
r number of consecutive station to read
Returns:
void
EXTERNAL INLINE void EXPRT cam8o (const int c, const int n, const int a, const int f, BYTE d)
Write data to given CAMAC address.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (16..31)
d data to be written to CAMAC
Returns:
void
Definition at line 458 of file hyt1331.c.
References cnaf8(), iobase, OUTP, OUTPW, regCOMMAND, regDATA, regGO, and wait_done().
Referenced by cam8o_r().
{
   unsigned int adr;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr, d);
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
}
EXTERNAL INLINE void EXPRT cam8o_q (const int c, const int n, const int a, const int f, BYTE d, int * x, int * q)
Write data to given CAMAC address with Q response.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (16..31)
d data to be written to CAMAC
x X response (0:failed,1:success)
q Q resonpse (0:no Q, 1: Q)
Returns:
void
EXTERNAL INLINE void EXPRT cam8o_r (const int c, const int n, const int a, const int f, BYTE * d, const int r)
Repeat write data to given CAMAC address r times.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (16..31)
d data to be written to CAMAC
r number of repeatition
Returns:
void
Definition at line 547 of file hyt1331.c.
References cam8o(), cnaf8_r(), i, OUTP, OUTPW, and RM_COUNT.
{
   WORD adr, i;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   /* trigger first cycle */
   OUTP(adr + 8, n);
   OUTP(adr, *((BYTE *) d));
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
   for (i = 0; i < r - 1; i++)
      OUTPW(adr + 12, (BYTE) * (++d));  /* write data and trigger next cycle */
}
EXTERNAL INLINE void EXPRT cam_crate_clear (const int c)
Issue CLEAR to crate.
Parameters:
c crate number (0..)
Returns:
void
Definition at line 710 of file hyt1331.c.
References C, CACY, cam16i(), cam16o(), camc(), CDMA, CLEAR, CNAF_CRATE_CLEAR, CONTROL_KEPT_BIT_MASK, CSR1, ctrlCLEAR, DH, DL, DM, handle, hcamac, hConn, INPW, iobase, NAF1, NAF2, OP_CRATE_CLEAR, OUTP, pwCC32_ADR, regCONTROL, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, status, and ZCI.
Referenced by cc_services(), cccc(), cnaf16(), cnaf_callback(), frontend_init(), and mcstd_func().
{
   unsigned int adr;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 10, 36);
}
EXTERNAL INLINE void EXPRT cam_crate_zinit (const int c)
Issue Z to crate.
Parameters:
c crate number (0..)
Returns:
void
Definition at line 720 of file hyt1331.c.
References C, CACY, cam16i(), cam16o(), camc(), CDMA, CNAF_CRATE_ZINIT, CONTROL_KEPT_BIT_MASK, CSR1, ctrlINITIALIZE, DH, DL, DM, handle, hcamac, hConn, INPW, iobase, NAF1, NAF2, OP_CRATE_ZINIT, OUTP, pwCC32_ADR, regCONTROL, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, status, ZCI, and ZINIT.
Referenced by cc_services(), cccz(), cnaf16(), cnaf_callback(), frontend_init(), main(), and mcstd_func().
{
   unsigned int adr;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 10, 34);
}
EXTERNAL INLINE void EXPRT cam_exit (void)
Close CAMAC accesss.
Definition at line 1147 of file hyt1331.c.
References _hdio, buffer, c, CAMAC_BASE, cc32_close(), cdchn(), cm_disconnect_client(), cm_disconnect_experiment(), crate, directio_lock_port(), FALSE, filename, handle, hcamac, hConn, i, iobase, jorway_crate_opened, MAX_DEVICES, MAX_PCI_ADD, midas_connect, rpc_client_disconnect(), size, SJY_BRANCH_MAX, status, vh, vme_close(), and vme_unmap().
Referenced by frontend_exit(), and main().
{
   int i;
   /* lock IO ports */
   for (i = 0; i < MAX_DEVICES; i++)
      if (io_base[i])
         directio_lock_port(io_base[i], io_base[i] + 4 * 0x10);
}
EXTERNAL INLINE void EXPRT cam_inhibit_clear (const int c)
Clear Crate inhibit.
Parameters:
c crate number (0..)
Returns:
void
Definition at line 688 of file hyt1331.c.
References CACY, cam16i(), cam16o(), camc(), CDMA, CNAF_INHIBIT_CLEAR, CONTROL_KEPT_BIT_MASK, CSR1, ctrlINHIBIT, DH, DL, DM, handle, hcamac, hConn, INHIBIT, INPW, iobase, NAF1, NAF2, OP_INHIBIT_CLEAR, OUTP, pwCC32_ADR, regCONTROL, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, status, and ZCI.
Referenced by cam_init_once(), cc_services(), ccci(), cnaf16(), cnaf_callback(), main(), and mcstd_func().
{
   unsigned int adr;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 10, 32);
}
EXTERNAL INLINE void EXPRT cam_inhibit_set (const int c)
Set Crate inhibit.
Parameters:
c crate number (0..)
Returns:
void
Definition at line 678 of file hyt1331.c.
References C, CACY, cam16i(), cam16o(), camc(), CDMA, CNAF_INHIBIT_SET, CONTROL_KEPT_BIT_MASK, CSR1, ctrlINHIBIT, DH, DL, DM, handle, hcamac, hConn, INHIBIT, INPW, iobase, NAF1, NAF2, OP_INHIBIT_SET, OUTP, pwCC32_ADR, regCONTROL, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, status, and ZCI.
Referenced by cc_services(), ccci(), cnaf16(), cnaf_callback(), and mcstd_func().
{
   unsigned int adr;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 10, 33);
}
EXTERNAL INLINE int EXPRT cam_inhibit_test (const int c)
Test Crate Inhibit.
Parameters:
c crate number (0..)
Returns:
1 for set, 0 for cleared
Definition at line 698 of file hyt1331.c.
References hcamac, INP, OP_INHIBIT_TEST, and status.
Referenced by ctci().
{
   unsigned int adr;
   BYTE status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   status = (BYTE) INP(adr + 6);
   return (status & 1) > 0;
}
EXTERNAL INLINE int EXPRT cam_init (void)
Initialize CAMAC access.
Returns:
1: success
Definition at line 1054 of file hyt1331.c.
References _hdio, branch, buffer, c, CACY, CAM_S_SUCCESS, CAMAC_BASE, catch_sigsegv(), CBD8210_BASE, cc32_open(), ccctype(), cdchn(), cm_msg, crate, ctrlRESET, directio_give_port(), directio_lock_port(), FE_ERR_HW, filename, gbl_sw1d, handle, hcamac, i, INP, iobase, irq, jorway_crate_opened, MAX_PCI_ADD, MERROR, MVME_A24D16, MVME_AMOD_A24_ND, MVME_IOCTL_AMOD_GET, MVME_IOCTL_AMOD_SET, n, OUTP, OUTPW, pci_scan(), regCONTROL, size, SJY_BRANCH_MAX, sjy_getdev(), status, SUCCESS, vh, vme_ioctl(), vme_mmap(), vme_open(), and ZCI.
Referenced by cam_init_once(), ccinit(), fccinit(), frontend_init(), and main().
{
   BYTE status, n_dev, i, n, a, f;
   WORD isa_io_base[] = { 0x200, 0x280, 0x300, 0x380 };
   WORD base_test;
   DWORD base_addr[6];
   /* set signal handler for segmet violation */
   signal(SIGSEGV, catch_sigsegv);
   /* scan PCI cards */
   for (n_dev = 0;; n_dev++) {
      if (!pci_scan(0x1196, 0x5331, n_dev + 1, irq + n_dev, base_addr))
         break;
      io_base[n_dev] = (WORD) (base_addr[3] & (~0x3UL));
      printf("hyt1331.c: Found PCI card at 0x%X, IRQ %d\n", io_base[n_dev], irq[n_dev]);
      if (directio_give_port(io_base[n_dev], io_base[n_dev] + 4 * 0x10) < 0) {
         signal(SIGSEGV, SIG_DFL);
         return 0;
      } else {
         n_dev++;
         break;                 // currently only supports one PCI interface
      }
   }
   /* scan ISA cards */
   for (i = 0; i < 4; i++) {
      base_test = isa_io_base[i];
      if (directio_give_port(base_test, base_test + 4 * 0x10) < 0) {
         signal(SIGSEGV, SIG_DFL);
         return 0;
      }
      /* Test if address is writable */
      OUTP(base_test, 0);
      status = INP(base_test);
      if (status != 0) {
         directio_lock_port(base_test, base_test + 4 * 0x10);
         continue;
      }
      /* Test A,N,F readback of ISA card */
      OUTP(base_test + 8, 1);
      OUTP(base_test + 6, 2);
      OUTP(base_test + 10, 32);
      a = (BYTE) INP(base_test + 10);
      n = (BYTE) INP(base_test + 10);
      f = (BYTE) INP(base_test + 10);
      if (n != 1 || a != 2 || f != 32) {
         directio_lock_port(base_test, base_test + 4 * 0x10);
         continue;
      }
      /* ISA card found */
      printf("hyt1331.c: Found ISA card at 0x%X\n", base_test);
      io_base[n_dev++] = base_test;
   }
   if (n_dev == 0) {
      printf("hyt1331.c: No PCI or ISA cards found\n");
      signal(SIGSEGV, SIG_DFL);
      return 0;
   }
   /* open port 80 for delayed write */
   directio_give_port(0x80, 0x80);
   /* check if we have access */
   OUTP(io_base[0], 0);
   signal(SIGSEGV, SIG_DFL);
   /* test auto increment switch SW1D */
   for (i = 0; i < n_dev; i++) {
      status = INP(io_base[i] + 6);
      if (!(status & (1 << 6))) {
         gbl_sw1d[i] = 0;
      } else {
         gbl_sw1d[i] = 1;
      }
   }
   return SUCCESS;
}
EXTERNAL INLINE int EXPRT cam_init_rpc (char * host_name, char * exp_name, char * fe_name, char * client_name, char * rpc_server)
Initialize CAMAC access for rpc calls
Definition at line 826 of file hyt1331.c.
References cm_connect_client(), cm_connect_experiment(), cm_disconnect_client(), cm_disconnect_experiment(), cm_get_experiment_database(), CM_NO_CLIENT, cm_set_msg_print(), CM_SUCCESS, CM_UNDEF_EXP, CNAF_TEST, data, db_enum_key(), db_find_key(), db_get_value(), DB_NO_MORE_SUBKEYS, DB_SUCCESS, FALSE, hConn, hDB, hKey, hSubkey, i, midas_connect, MT_ALL, rpc_client_call(), rpc_client_connect(), RPC_CNAF16, rpc_get_internal_list(), RPC_NET_ERROR, rpc_register_functions(), rpc_set_name(), RPC_SUCCESS, size, status, SUCCESS, TID_STRING, and TRUE.
Referenced by main().
{
   /* dummy routine for compatibility */
   return 1;
}
EXTERNAL INLINE void EXPRT cam_interrupt_attach (const int c, const int n, void(*)(void) isr)
Attach service routine to LAM of specific crate and station.
Parameters:
c crate number (0..)
n station number
(*isr) Function pointer to attach to the LAM
Returns:
void
Definition at line 214 of file camacnul.c.
References hcamac, i, isr, lam_dispatch(), lam_table, LAM_TABLE_SIZE, n_lam_registered, and old_handler.
Referenced by cclnk(), interrupt_configure(), and main().
{
}
EXTERNAL INLINE void EXPRT cam_interrupt_detach (const int c, const int n)
Detach service routine from LAM.
Parameters:
c crate number (0..)
n station number
Returns:
void
Definition at line 217 of file camacnul.c.
References hcamac, i, lam_table, LAM_TABLE_SIZE, n_lam_registered, and old_handler.
Referenced by cculk(), and interrupt_configure().
{
}
EXTERNAL INLINE void EXPRT cam_interrupt_disable (const int c)
Disables interrupts in specific crate
Parameters:
c crate number (0..)
Returns:
void
Definition at line 765 of file hyt1331.c.
References hcamac, INP, mask, OP_INTERRUPT_DISABLE, and OUTP.
Referenced by cccd(), and interrupt_configure().
{
   unsigned int adr;
   /* disable interrupts in controller */
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 10, 40);
}
EXTERNAL INLINE void EXPRT cam_interrupt_enable (const int c)
Enable interrupts in specific crate
Parameters:
c crate number (0..)
Returns:
void
Definition at line 754 of file hyt1331.c.
References hcamac, INP, mask, OP_INTERRUPT_ENABLE, and OUTP.
Referenced by cccd(), ccrgl(), interrupt_configure(), isr(), and main().
{
   unsigned int adr;
   /* enable interrupts in controller */
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 10, 41);
}
EXTERNAL INLINE int EXPRT cam_interrupt_test (const int c)
Test Crate Interrupt.
Parameters:
c crate number (0..)
Returns:
1 for set, 0 for cleared
Definition at line 776 of file hyt1331.c.
References hcamac, INP, OP_INTERRUPT_TEST, and status.
Referenced by ctcd().
{
   unsigned int adr;
   BYTE status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   status = (BYTE) INP(adr + 6);
   return (status & (1 << 2)) > 0;
}
EXTERNAL INLINE void EXPRT cam_lam_clear (const int c, const int n)
Clear the LAM register of the crate controller. It doesn't clear the LAM of the particular station.
Parameters:
c crate number (0..)
n LAM station
Returns:
void
Definition at line 807 of file hyt1331.c.
References camc(), handle, hcamac, INP, OP_LAM_CLEAR, OUTP, and pwCC32_ADR.
Referenced by cclnk(), ccrgl(), isr(), main(), mcstd_func(), and read_trigger_event().
{
   unsigned int adr;
   /*
      note that the LAM flip-flop in unit must be cleared via
      camc(c, n, 0, 10);
      in the user code prior to the call of cam_lam_clear()
    */
   /* restart LAM scanner in controller */
   adr = io_base[c >> 2] + ((c % 3) << 4);
   INP(adr + 8);
}
EXTERNAL INLINE void EXPRT cam_lam_disable (const int c, const int n)
Disable LAM generation for given station to the Crate controller. It doesn't disable the LAM of the actual station itself.
Parameters:
c crate number (0..)
n LAM station
Returns:
void
Definition at line 742 of file hyt1331.c.
References cam24i(), cam24o(), camc(), CONTROL_KEPT_BIT_MASK, ctrlENABLEINTERRUPT, handle, hcamac, INPW, iobase, jorway_crate_LAM, mask, OP_LAM_DISABLE, OUTP, plCC32_ADR, regCONTROL, and wait.
Referenced by cc_services(), and mcstd_func().
{
   /* disable the station number */
   unsigned int adr;
   /* disable LAM in controller */
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 10, 128 + n);
}
EXTERNAL INLINE void EXPRT cam_lam_enable (const int c, const int n)
Enable LAM generation for given station to the Crate controller. It doesn't enable the LAM of the actual station itself.
Parameters:
c crate number (0..)
n LAM station
Returns:
void
Definition at line 730 of file hyt1331.c.
References cam24i(), cam24o(), camc(), CIO1_CNTRL_ADRS, CIO2_CNTRL_ADRS, CONTROL_KEPT_BIT_MASK, ctrlENABLEINTERRUPT, handle, hcamac, INPW, iobase, jorway_crate_LAM, mask, OP_LAM_ENABLE, OUTP, plCC32_ADR, regCONTROL, and wait.
Referenced by cc_services(), cclnk(), ccrgl(), frontend_init(), main(), and mcstd_func().
{
   /* enable the station number */
   unsigned int adr;
   /* enable LAM in controller */
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 10, 64 + n);
}
EXTERNAL INLINE void EXPRT cam_lam_read (const int c, DWORD * lam)
Reads in lam the lam pattern of the entire crate.
Parameters:
c crate number (0..)
lam LAM pattern of the crate
Returns:
void
Definition at line 788 of file hyt1331.c.
References cam24i(), CDMA, csr(), handle, hcamac, INP, iobase, LXQ, OP_LAM_READ, OUTP, plCC32_ADR, and regLAM.
Referenced by cc_services(), ctgl(), mcstd_func(), and poll_event().
{
   /*
      return a BITWISE coded station NOT the station number
      i.e.: n = 5  ==> lam = 0x10
    */
   unsigned int adr, csr;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   csr = (BYTE) INP(adr + 6);
   if (csr & (1 << 3)) {
      *lam = ((BYTE) INP(adr + 8)) & 0x1F;      // mask upper 3 bits
      *lam = 1 << (*lam - 1);
   } else
      *lam = 0;
}
EXTERNAL INLINE int EXPRT cam_lam_wait (int * c, DWORD * n, const int millisec)
Wait for a LAM to occur with a certain timeout. Return crate and station if LAM occurs.
Parameters:
c crate number (0..)
n LAM station
millisec If there is no LAM after this timeout, the routine returns
Returns:
1 if LAM occured, 0 else
Definition at line 454 of file camac.c.
References d, FD_SETSIZE, hcamac, and read.
{
   unsigned int d;
   fd_set readfds;
   struct timeval timeout;
   FD_ZERO(&readfds);
   FD_SET(hcamac, &readfds);
   timeout.tv_sec = millisec / 1000;
   timeout.tv_usec = (millisec % 1000) * 1000;
   select(FD_SETSIZE, (void *) &readfds, NULL, NULL, (void *) &timeout);
   if (FD_ISSET(hcamac, &readfds)) {
      read(hcamac, &d, 4);
      *lam = (1 << (d & 0xFFFF));
      *c = (d >> 16);
      return 1;
   }
   return 0;
}
EXTERNAL INLINE void EXPRT camc (const int c, const int n, const int a, const int f)
CAMAC command (no data).
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (8..15, 24..31)
Returns:
void
Definition at line 631 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam16i(), cam16o(), camc_q(), CCR, CDMA, CNAF, cnaf8(), CSR, CSR1, d, DONE, FUN, GO, handle, hConn, INPW, iobase, MCR, N_SHIFT, NAF, NAF1, NAF2, OUTP, OUTPW, plCC32_ADR, qdummy, regCOMMAND, regGO, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, STA, status, temp, wait_done(), and WS_16BIT.
Referenced by cam_crate_clear(), cam_crate_zinit(), cam_inhibit_clear(), cam_inhibit_set(), cam_lam_clear(), cam_lam_disable(), cam_lam_enable(), camc_chk(), camc_q(), camc_sa(), camc_sn(), cclc(), cclm(), frontend_init(), isr(), lrs2249_bor1(), lrs2249_read1(), lrs2365_set(), lrs2415_get(), lrs2415_get_current(), main(), mcstd_func(), and read_trigger_event().
{
   unsigned int adr;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
}
EXTERNAL INLINE int EXPRT camc_chk (const int c)
Crate presence check.
Parameters:
c crate number (0..)
Returns:
0:Success, -1:No CAMAC response
Definition at line 610 of file hyt1331.c.
References A_FIELD, A_SHIFT, ADD, CAM_BTBCHK, camc(), CDMA, CSR, DONE, F_FIELD, FUN, hcamac, INP, INPW, iobase, n, N_FIELD, N_SHIFT, NAF, NAF1, NAF2, OP_CRATE_CHECK, OUTPW, RDNAF, regSTATUS, sjy_tur(), STA, and status.
{
   unsigned int adr, n, a, f;
   /* clear inhibit */
   camc(c, 1, 2, 32);
   /* read back naf */
   adr = io_base[c >> 2] + ((c % 3) << 4);
   a = (BYTE) INP(adr + 10);
   n = (BYTE) INP(adr + 10);
   f = (BYTE) INP(adr + 10);
   if (n != 1 || a != 2 || f != 32)
      return -1;
   return 0;
}
EXTERNAL INLINE void EXPRT camc_q (const int c, const int n, const int a, const int f, int * q)
CAMAC command with Q response (no data).
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (8..15, 24..31)
q Q response (0:no Q, 1:Q)
Returns:
void
Definition at line 643 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, camc(), cami(), CCR, CDMA, cmd, CNAF, cnaf8(), CSR, csr(), CSR1, d, DONE, FUN, GO, handle, hConn, INP, INPW, iobase, LXQ, MCR, N_SHIFT, NAF, NAF1, NAF2, NAFCMD, OUTP, OUTPW, plCC32_ADR, regCOMMAND, regGO, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, sjy_get_qx(), sjy_nondata(), STA, status, wait_done(), and WS_16BIT.
Referenced by camc(), cfsa(), cssa(), ctlm(), lrs2249_read1(), mcstd_func(), ps7106_set(), and read_trigger_event().
{
   unsigned int adr, status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
   status = (BYTE) INP(adr + 6);
   *q = status & 1;
}
EXTERNAL INLINE void EXPRT camc_sa (const int c, const int n, const int a, const int f, const int r)
Scan CAMAC command on sub-address.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (8..15, 24..31)
r number of consecutive sub-address to read
Returns:
void
Definition at line 658 of file hyt1331.c.
References camc(), cnaf8_r(), i, and RM_ASCAN.
{
   int i;
   for (i = 0; i < r; i++)
      camc(c, n, a + i, f);
}
EXTERNAL INLINE void EXPRT camc_sn (const int c, const int n, const int a, const int f, const int r)
Scan CAMAC command on station.
Parameters:
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
f function (8..15, 24..31)
r number of consecutive station to read
Returns:
void
Definition at line 668 of file hyt1331.c.
References camc(), cnaf8_r(), i, and RM_NSCAN.
{
   int i;
   for (i = 0; i < r; i++)
      camc(c, n + i, a, f);
}
EXTERNAL INLINE void EXPRT cami (const int c, const int n, const int a, const int f, WORD * d)
Same as cam16i()
Definition at line 140 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam16i(), CCR, CDMA, CNAF, cnaf16(), CSR, CSR1, DL, DLR, DM, DONE, FUN, GO, hConn, INP, INPW, loop, MCR, N_SHIFT, NAF, NAF1, NAF2, OPST, OUTP, OUTPW, RL, RM, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, STA, status, and WS_16BIT.
Referenced by cam16i(), cam16i_q(), cam16i_rq(), cam16i_sa(), cam16o_q(), cam24i_q(), cam24i_rq(), cam24o_q(), camc_q(), lrs2249_read1(), lrs2365_set(), ps7106_set(), and read_trigger_event().
{
   WORD adr, status;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
   status = (BYTE) INP(adr + 6);
   *((BYTE *) d) = INP(adr);
   *(((BYTE *) d) + 1) = INP(adr + 2);
}
EXTERNAL INLINE void EXPRT camo (const int c, const int n, const int a, const int f, WORD d)
Same as cam16o()
Definition at line 471 of file hyt1331.c.
References A_SHIFT, ADD, C, CACY, cam16o(), CCR, CDMA, CNAF, cnaf16(), CSR, CSR1, DH, DL, DLR, DM, DONE, FUN, GO, hConn, INP, INPW, loop, MCR, N_SHIFT, NAF, NAF1, NAF2, OPST, OUTP, OUTPW, rpc_client_call(), RPC_CNAF16, RPC_SUCCESS, size, STA, status, WL, WM, and WS_16BIT.
Referenced by cam16o(), frontend_init(), lrs2365_set(), lrs2415_set(), lrs2415_set_current_limit(), ps7106_set(), read_trigger_event(), and s500_bor1().
{
   unsigned int adr;
   adr = io_base[c >> 2] + ((c % 3) << 4);
   OUTP(adr + 8, n);
   OUTP(adr, (BYTE) d);
   OUTP(adr + 2, *(((BYTE *) & d) + 1));
   OUTP(adr + 6, a);
   OUTP(adr + 10, f);
}