AlcapDAQ: Midas Alarm Functions (al_xxx)
Midas Alarm Functions (al_xxx)
[The midas.h & midas.c]
Functions
BOOL al_evaluate_condition (char *condition, char *value)
INT al_trigger_alarm (char *alarm_name, char *alarm_message, char *default_class, char *cond_str, INT type)
INT al_trigger_class (char *alarm_class, char *alarm_message, BOOL first)
INT al_reset_alarm (char *alarm_name)
INT al_check ()
Detailed Description
dox dox dox
Function Documentation
INT al_check ()
Definition at line 16417 of file midas.c.
References ALARM::active, al_evaluate_condition(), AL_SUCCESS, al_trigger_alarm(), PROGRAM_INFO::alarm_class, ALARM::alarm_class, ALARM_CLASS_STR, ALARM::alarm_message, ALARM_ODB_STR, ALARM_PERIODIC_STR, AT_EVALUATED, AT_LAST, AT_PERIODIC, AT_PROGRAM, PROGRAM_INFO::auto_restart, PROGRAM_INFO::check_interval, ALARM::check_interval, ALARM::checked_last, cm_exist(), cm_get_experiment_database(), cm_get_experiment_mutex(), cm_msg, CM_NO_CLIENT, ALARM::condition, db_check_record(), db_create_record(), db_enum_key(), db_find_key(), db_get_key(), db_get_record(), db_get_value(), DB_NO_MORE_SUBKEYS, db_set_record(), DB_SUCCESS, equal_ustring(), FALSE, PROGRAM_INFO::first_failed, flag, hDB, i, key, MERROR, MTALK, KEY::name, RPC_AL_CHECK, rpc_call(), rpc_get_name(), rpc_is_remote(), size, ss_mutex_release(), ss_mutex_wait_for(), SS_SUCCESS, ss_system(), ss_time(), PROGRAM_INFO::start_command, status, strcomb(), SUCCESS, TID_BOOL, TID_INT, TID_KEY, TRUE, KEY::type, ALARM::type, and value.
Referenced by cm_yield(), rpc_server_dispatch(), and rpc_server_thread().
16420          : al_scan
16421
16422   Purpose: Scan ODB alarams and programs
16423
16424   Input:
16425
16426   Output:
16427
16428   Function value:
16429     AL_SUCCESS              Successful completion
16430
16431 \********************************************************************/
16432 {
16433    if (rpc_is_remote())
16434       return rpc_call(RPC_AL_CHECK);
16435
16436 #ifdef LOCAL_ROUTINES
16437    {
16438       INT i, status, size, mutex;
16439       HNDLE hDB, hkeyroot, hkey;
16440       KEY key;
16441       ALARM alarm;
16442       char str[256], value[256];
16443       DWORD now;
16444       PROGRAM_INFO program_info;
16445       BOOL flag;
16446
16447       ALARM_CLASS_STR(alarm_class_str);
16448       ALARM_ODB_STR(alarm_odb_str);
16449       ALARM_PERIODIC_STR(alarm_periodic_str);
16450
16451       cm_get_experiment_database(&hDB, NULL);
16452
16453       if (hDB == 0)
16454          return AL_SUCCESS;     /* called from server not yet connected */
16455
16456       /* check online mode */
16457       flag = TRUE;
16458       size = sizeof(flag);
16459       db_get_value(hDB, 0, "/Runinfo/Online Mode", &flag, &size, TID_INT, TRUE);
16460       if (!flag)
16461          return AL_SUCCESS;
16462
16463       /* check global alarm flag */
16464       flag = TRUE;
16465       size = sizeof(flag);
16466       db_get_value(hDB, 0, "/Alarms/Alarm system active", &flag, &size, TID_BOOL, TRUE);
16467       if (!flag)
16468          return AL_SUCCESS;
16469
16470       /* request semaphore */
16471       cm_get_experiment_mutex(&mutex, NULL);
16472       status = ss_mutex_wait_for(mutex, 100);
16473       if (status != SS_SUCCESS)
16474          return SUCCESS;        /* someone else is doing alarm business */
16475
16476       /* check ODB alarms */
16477       db_find_key(hDB, 0, "/Alarms/Alarms", &hkeyroot);
16478       if (!hkeyroot) {
16479          /* create default ODB alarm */
16480          status =
16481              db_create_record(hDB, 0, "/Alarms/Alarms/Demo ODB", strcomb(alarm_odb_str));
16482          db_find_key(hDB, 0, "/Alarms/Alarms", &hkeyroot);
16483          if (!hkeyroot) {
16484             ss_mutex_release(mutex);
16485             return SUCCESS;
16486          }
16487
16488          status =
16489              db_create_record(hDB, 0, "/Alarms/Alarms/Demo periodic",
16490                               strcomb(alarm_periodic_str));
16491          db_find_key(hDB, 0, "/Alarms/Alarms", &hkeyroot);
16492          if (!hkeyroot) {
16493             ss_mutex_release(mutex);
16494             return SUCCESS;
16495          }
16496
16497          /* create default alarm classes */
16498          status =
16499              db_create_record(hDB, 0, "/Alarms/Classes/Alarm", strcomb(alarm_class_str));
16500          status =
16501              db_create_record(hDB, 0, "/Alarms/Classes/Warning",
16502                               strcomb(alarm_class_str));
16503          if (status != DB_SUCCESS) {
16504             ss_mutex_release(mutex);
16505             return SUCCESS;
16506          }
16507       }
16508
16509       for (i = 0;; i++) {
16510          status = db_enum_key(hDB, hkeyroot, i, &hkey);
16511          if (status == DB_NO_MORE_SUBKEYS)
16512             break;
16513
16514          db_get_key(hDB, hkey, &key);
16515
16516          size = sizeof(alarm);
16517          status = db_get_record(hDB, hkey, &alarm, &size, 0);
16518          if (status != DB_SUCCESS || alarm.type < 1 || alarm.type > AT_LAST) {
16519             /* make sure alarm record has right structure */
16520             db_check_record(hDB, hkey, "", strcomb(alarm_odb_str), TRUE);
16521             size = sizeof(alarm);
16522             status = db_get_record(hDB, hkey, &alarm, &size, 0);
16523             if (status != DB_SUCCESS || alarm.type < 1 || alarm.type > AT_LAST) {
16524                cm_msg(MERROR, "al_check", "Cannot get alarm record");
16525                continue;
16526             }
16527          }
16528
16529          /* check periodic alarm only when active */
16530          if (alarm.active &&
16531              alarm.type == AT_PERIODIC &&
16532              alarm.check_interval > 0 &&
16533              (INT) ss_time() - (INT) alarm.checked_last > alarm.check_interval) {
16534             /* if checked_last has not been set, set it to current time */
16535             if (alarm.checked_last == 0) {
16536                alarm.checked_last = ss_time();
16537                db_set_record(hDB, hkey, &alarm, size, 0);
16538             } else
16539                al_trigger_alarm(key.name, alarm.alarm_message, alarm.alarm_class, "",
16540                                 AT_PERIODIC);
16541          }
16542
16543          /* check alarm only when active and not internal */
16544          if (alarm.active &&
16545              alarm.type == AT_EVALUATED &&
16546              alarm.check_interval > 0 &&
16547              (INT) ss_time() - (INT) alarm.checked_last > alarm.check_interval) {
16548             /* if condition is true, trigger alarm */
16549             if (al_evaluate_condition(alarm.condition, value)) {
16550                sprintf(str, alarm.alarm_message, value);
16551                al_trigger_alarm(key.name, str, alarm.alarm_class, "", AT_EVALUATED);
16552             } else {
16553                alarm.checked_last = ss_time();
16554                status = db_set_record(hDB, hkey, &alarm, sizeof(alarm), 0);
16555                if (status != DB_SUCCESS) {
16556                   cm_msg(MERROR, "al_check", "Cannot write back alarm record");
16557                   continue;
16558                }
16559             }
16560          }
16561       }
16562
16563       /* check /programs alarms */
16564       db_find_key(hDB, 0, "/Programs", &hkeyroot);
16565       if (hkeyroot) {
16566          for (i = 0;; i++) {
16567             status = db_enum_key(hDB, hkeyroot, i, &hkey);
16568             if (status == DB_NO_MORE_SUBKEYS)
16569                break;
16570
16571             db_get_key(hDB, hkey, &key);
16572
16573             /* don't check "execute on xxx" */
16574             if (key.type != TID_KEY)
16575                continue;
16576
16577             size = sizeof(program_info);
16578             status = db_get_record(hDB, hkey, &program_info, &size, 0);
16579             if (status != DB_SUCCESS) {
16580                cm_msg(MERROR, "al_check", "Cannot get program info record");
16581                continue;
16582             }
16583
16584             now = ss_time();
16585
16586             rpc_get_name(str);
16587             str[strlen(key.name)] = 0;
16588             if (!equal_ustring(str, key.name) &&
16589                 cm_exist(key.name, FALSE) == CM_NO_CLIENT) {
16590                if (program_info.first_failed == 0)
16591                   program_info.first_failed = now;
16592
16593                /* fire alarm when not running for more than what specified in check interval */
16594                if (now - program_info.first_failed >= program_info.check_interval / 1000) {
16595                   /* if not running and alarm calss defined, trigger alarm */
16596                   if (program_info.alarm_class[0]) {
16597                      sprintf(str, "Program %s is not running", key.name);
16598                      al_trigger_alarm(key.name, str, program_info.alarm_class,
16599                                       "Program not running", AT_PROGRAM);
16600                   }
16601
16602                   /* auto restart program */
16603                   if (program_info.auto_restart && program_info.start_command[0]) {
16604                      ss_system(program_info.start_command);
16605                      program_info.first_failed = 0;
16606                      cm_msg(MTALK, "al_check", "Program %s restarted", key.name);
16607                   }
16608                }
16609             } else
16610                program_info.first_failed = 0;
16611
16612             db_set_record(hDB, hkey, &program_info, sizeof(program_info), 0);
16613          }
16614       }
16615
16616       ss_mutex_release(mutex);
16617    }
16618 #endif                          /* LOCAL_COUTINES */
16619
16620    return SUCCESS;
16621 }
BOOL al_evaluate_condition (char * condition, char * value)
dox
Definition at line 15975 of file midas.c.
References cm_get_experiment_database(), cm_msg, data, db_find_key(), db_get_data(), db_get_key(), db_get_key_time(), db_sprintf(), equal_ustring(), FALSE, hDB, i, index, j, key, MERROR, size, time, and KEY::type.
Referenced by al_check(), and show_alarm_page().
15976 {
15977    HNDLE hDB, hkey;
15978    int i, j, index, size;
15979    KEY key;
15980    double value1, value2;
15981    char str[256], op[3], function[80];
15982    char data[10000];
15983    DWORD time;
15984
15985    strcpy(str, condition);
15986    op[1] = op[2] = 0;
15987    value1 = value2 = 0;
15988    index = 0;
15989
15990    /* find value and operator */
15991    for (i = strlen(str) - 1; i > 0; i--)
15992       if (strchr("<>=!", str[i]) != NULL)
15993          break;
15994    op[0] = str[i];
15995    value2 = atof(str + i + 1);
15996    str[i] = 0;
15997
15998    if (i > 0 && strchr("<>=!", str[i - 1])) {
15999       op[1] = op[0];
16000       op[0] = str[--i];
16001       str[i] = 0;
16002    }
16003
16004    i--;
16005    while (i > 0 && str[i] == ' ')
16006       i--;
16007    str[i + 1] = 0;
16008
16009    /* check if function */
16010    function[0] = 0;
16011    if (str[i] == ')') {
16012       str[i--] = 0;
16013       if (strchr(str, '(')) {
16014          *strchr(str, '(') = 0;
16015          strcpy(function, str);
16016          for (i = strlen(str) + 1, j = 0; str[i]; i++, j++)
16017             str[j] = str[i];
16018          str[j] = 0;
16019          i = j - 1;
16020       }
16021    }
16022
16023    /* find key */
16024    if (str[i] == ']') {
16025       str[i--] = 0;
16026       while (i > 0 && isdigit(str[i]))
16027          i--;
16028       index = atoi(str + i + 1);
16029       str[i] = 0;
16030    }
16031
16032    cm_get_experiment_database(&hDB, NULL);
16033    db_find_key(hDB, 0, str, &hkey);
16034    if (!hkey) {
16035       cm_msg(MERROR, "al_evaluate_condition",
16036              "Cannot find key %s to evaluate alarm condition", str);
16037       if (value)
16038          strcpy(value, "unknown");
16039       return FALSE;
16040    }
16041
16042    if (equal_ustring(function, "access")) {
16043       /* check key access time */
16044       db_get_key_time(hDB, hkey, &time);
16045       sprintf(str, "%ld", time);
16046       value1 = atof(str);
16047    } else {
16048       /* get key data and convert to double */
16049       db_get_key(hDB, hkey, &key);
16050       size = sizeof(data);
16051       db_get_data(hDB, hkey, data, &size, key.type);
16052       db_sprintf(str, data, size, index, key.type);
16053       value1 = atof(str);
16054    }
16055
16056    /* return value */
16057    if (value)
16058       strcpy(value, str);
16059
16060    /* now do logical operation */
16061    if (strcmp(op, "=") == 0)
16062       return value1 == value2;
16063    if (strcmp(op, "==") == 0)
16064       return value1 == value2;
16065    if (strcmp(op, "!=") == 0)
16066       return value1 != value2;
16067    if (strcmp(op, "<") == 0)
16068       return value1 < value2;
16069    if (strcmp(op, ">") == 0)
16070       return value1 > value2;
16071    if (strcmp(op, "<=") == 0)
16072       return value1 <= value2;
16073    if (strcmp(op, ">=") == 0)
16074       return value1 >= value2;
16075
16076    return FALSE;
16077 }
INT al_reset_alarm (char * alarm_name)
Definition at line 16313 of file midas.c.
References AL_ERROR_ODB, AL_INVALID_NAME, AL_RESET, al_reset_alarm(), AL_SUCCESS, ALARM::alarm_class, ALARM::checked_last, cm_get_experiment_database(), cm_msg, db_enum_link(), db_find_key(), db_get_key(), db_get_record(), db_set_record(), DB_SUCCESS, ALARM_CLASS::execute_last, hDB, i, key, MERROR, KEY::name, size, status, ALARM_CLASS::system_message_last, ALARM::time_triggered_first, ALARM::time_triggered_last, and ALARM::triggered.
Referenced by al_reset_alarm(), command_loop(), epics_ca_get(), epics_ca_init(), ge_ln2_read(), interprete(), and lazy_main().
16316          : al_reset_alarm
16317
16318   Purpose: Reset (acknowledge) alarm
16319
16320   Input:
16321     char   *alarm_name      Alarm name, must be defined in /Alarms/Alarms
16322                             If NULL reset all alarms
16323
16324   Output:
16325     <none>
16326
16327   Function value:
16328     AL_INVALID_NAME         Alarm name not defined
16329     AL_RESET                Alarm was triggered and reset
16330     AL_SUCCESS              Successful completion
16331
16332 \********************************************************************/
16333 {
16334    int status, size, i;
16335    HNDLE hDB, hkeyalarm, hkeyclass, hsubkey;
16336    KEY key;
16337    char str[256];
16338    ALARM alarm;
16339    ALARM_CLASS ac;
16340
16341    cm_get_experiment_database(&hDB, NULL);
16342
16343    if (alarm_name == NULL) {
16344       /* reset all alarms */
16345       db_find_key(hDB, 0, "/Alarms/Alarms", &hkeyalarm);
16346       if (hkeyalarm) {
16347          for (i = 0;; i++) {
16348             db_enum_link(hDB, hkeyalarm, i, &hsubkey);
16349
16350             if (!hsubkey)
16351                break;
16352
16353             db_get_key(hDB, hsubkey, &key);
16354             al_reset_alarm(key.name);
16355          }
16356       }
16357       return AL_SUCCESS;
16358    }
16359
16360    /* find alarm and alarm class */
16361    sprintf(str, "/Alarms/Alarms/%s", alarm_name);
16362    db_find_key(hDB, 0, str, &hkeyalarm);
16363    if (!hkeyalarm) {
16364       cm_msg(MERROR, "al_reset_alarm", "Alarm %s not found in ODB", alarm_name);
16365       return AL_INVALID_NAME;
16366    }
16367
16368    size = sizeof(alarm);
16369    status = db_get_record(hDB, hkeyalarm, &alarm, &size, 0);
16370    if (status != DB_SUCCESS) {
16371       cm_msg(MERROR, "al_reset_alarm", "Cannot get alarm record");
16372       return AL_ERROR_ODB;
16373    }
16374
16375    sprintf(str, "/Alarms/Classes/%s", alarm.alarm_class);
16376    db_find_key(hDB, 0, str, &hkeyclass);
16377    if (!hkeyclass) {
16378       cm_msg(MERROR, "al_reset_alarm", "Alarm class %s not found in ODB",
16379              alarm.alarm_class);
16380       return AL_INVALID_NAME;
16381    }
16382
16383    size = sizeof(ac);
16384    status = db_get_record(hDB, hkeyclass, &ac, &size, 0);
16385    if (status != DB_SUCCESS) {
16386       cm_msg(MERROR, "al_reset_alarm", "Cannot get alarm class record");
16387       return AL_ERROR_ODB;
16388    }
16389
16390    if (alarm.triggered) {
16391       alarm.triggered = 0;
16392       alarm.time_triggered_first[0] = 0;
16393       alarm.time_triggered_last[0] = 0;
16394       alarm.checked_last = 0;
16395
16396       ac.system_message_last = 0;
16397       ac.execute_last = 0;
16398
16399       status = db_set_record(hDB, hkeyalarm, &alarm, sizeof(alarm), 0);
16400       if (status != DB_SUCCESS) {
16401          cm_msg(MERROR, "al_reset_alarm", "Cannot update alarm record");
16402          return AL_ERROR_ODB;
16403       }
16404       status = db_set_record(hDB, hkeyclass, &ac, sizeof(ac), 0);
16405       if (status != DB_SUCCESS) {
16406          cm_msg(MERROR, "al_reset_alarm", "Cannot update alarm class record");
16407          return AL_ERROR_ODB;
16408       }
16409       return AL_RESET;
16410    }
16411
16412    return AL_SUCCESS;
16413 }
INT al_trigger_alarm (char * alarm_name, char * alarm_message, char * default_class, char * cond_str, INT type)
dox Trigger a certain alarm.
 ...
  lazy.alarm[0] = 0;
  size = sizeof(lazy.alarm);
  db_get_value(hDB, pLch->hKey, "Settings/Alarm Class", lazy.alarm, &size, TID_STRING, TRUE);
  // trigger alarm if defined
  if (lazy.alarm[0])
    al_trigger_alarm("Tape", "Tape full...load new one!", lazy.alarm, "Tape full", AT_INTERNAL);
  ...
Parameters:
alarm_name Alarm name, defined in /alarms/alarms
alarm_message Optional message which goes with alarm
default_class If alarm is not yet defined under /alarms/alarms/<alarm_name>, a new one is created and this default class is used.
cond_str String displayed in alarm condition
type Alarm type, one of AT_xxx
Returns:
AL_SUCCESS, AL_INVALID_NAME
Definition at line 16104 of file midas.c.
References ALARM::active, AL_ERROR_ODB, AL_SUCCESS, al_trigger_class(), ALARM::alarm_class, ALARM::alarm_message, ALARM_ODB_STR, AT_EVALUATED, AT_LAST, AT_PERIODIC, ALARM::check_interval, ALARM::checked_last, cm_asctime(), cm_get_experiment_database(), cm_msg, db_check_record(), db_create_record(), db_find_key(), db_get_record(), db_get_value(), db_set_record(), db_set_value(), DB_SUCCESS, flag, hDB, MERROR, RPC_AL_TRIGGER_ALARM, rpc_call(), rpc_is_remote(), size, ss_time(), status, strcomb(), TID_BOOL, TID_INT, TID_STRING, ALARM::time_triggered_first, ALARM::time_triggered_last, ALARM::triggered, TRUE, and ALARM::type.
Referenced by al_check(), ge_ln2_read(), lazy_main(), and rpc_server_dispatch().
16106 {
16107    if (rpc_is_remote())
16108       return rpc_call(RPC_AL_TRIGGER_ALARM, alarm_name, alarm_message,
16109                       default_class, cond_str, type);
16110
16111 #ifdef LOCAL_ROUTINES
16112    {
16113       int status, size;
16114       HNDLE hDB, hkeyalarm;
16115       char str[256];
16116       ALARM alarm;
16117       BOOL flag;
16118       ALARM_ODB_STR(alarm_odb_str);
16119
16120       cm_get_experiment_database(&hDB, NULL);
16121
16122       /* check online mode */
16123       flag = TRUE;
16124       size = sizeof(flag);
16125       db_get_value(hDB, 0, "/Runinfo/Online Mode", &flag, &size, TID_INT, TRUE);
16126       if (!flag)
16127          return AL_SUCCESS;
16128
16129       /* find alarm */
16130       sprintf(str, "/Alarms/Alarms/%s", alarm_name);
16131       db_find_key(hDB, 0, str, &hkeyalarm);
16132       if (!hkeyalarm) {
16133          /* alarm must be an internal analyzer alarm, so create a default alarm */
16134          status = db_create_record(hDB, 0, str, strcomb(alarm_odb_str));
16135          db_find_key(hDB, 0, str, &hkeyalarm);
16136          if (!hkeyalarm) {
16137             cm_msg(MERROR, "al_trigger_alarm", "Cannot create alarm record");
16138             return AL_ERROR_ODB;
16139          }
16140
16141          if (default_class && default_class[0])
16142             db_set_value(hDB, hkeyalarm, "Alarm Class", default_class, 32, 1, TID_STRING);
16143          status = TRUE;
16144          db_set_value(hDB, hkeyalarm, "Active", &status, sizeof(status), 1, TID_BOOL);
16145       }
16146
16147       /* set parameters for internal alarms */
16148       if (type != AT_EVALUATED && type != AT_PERIODIC) {
16149          db_set_value(hDB, hkeyalarm, "Type", &type, sizeof(INT), 1, TID_INT);
16150          strcpy(str, cond_str);
16151          db_set_value(hDB, hkeyalarm, "Condition", str, 256, 1, TID_STRING);
16152       }
16153
16154       size = sizeof(alarm);
16155       status = db_get_record(hDB, hkeyalarm, &alarm, &size, 0);
16156       if (status != DB_SUCCESS || alarm.type < 1 || alarm.type > AT_LAST) {
16157          /* make sure alarm record has right structure */
16158          db_check_record(hDB, hkeyalarm, "", strcomb(alarm_odb_str), TRUE);
16159
16160          size = sizeof(alarm);
16161          status = db_get_record(hDB, hkeyalarm, &alarm, &size, 0);
16162          if (status != DB_SUCCESS) {
16163             cm_msg(MERROR, "al_trigger_alarm", "Cannot get alarm record");
16164             return AL_ERROR_ODB;
16165          }
16166       }
16167
16168       /* if internal alarm, check if active and check interval */
16169       if (alarm.type != AT_EVALUATED && alarm.type != AT_PERIODIC) {
16170          /* check global alarm flag */
16171          flag = TRUE;
16172          size = sizeof(flag);
16173          db_get_value(hDB, 0, "/Alarms/Alarm system active", &flag, &size, TID_BOOL,
16174                       TRUE);
16175          if (!flag)
16176             return AL_SUCCESS;
16177
16178          if (!alarm.active)
16179             return AL_SUCCESS;
16180
16181          if ((INT) ss_time() - (INT) alarm.checked_last < alarm.check_interval)
16182             return AL_SUCCESS;
16183
16184          /* now the alarm will be triggered, so save time */
16185          alarm.checked_last = ss_time();
16186       }
16187
16188       /* write back alarm message for internal alarms */
16189       if (alarm.type != AT_EVALUATED && alarm.type != AT_PERIODIC) {
16190          strncpy(alarm.alarm_message, alarm_message, 79);
16191          alarm.alarm_message[79] = 0;
16192       }
16193
16194       /* now trigger alarm class defined in this alarm */
16195       if (alarm.alarm_class[0])
16196          al_trigger_class(alarm.alarm_class, alarm_message, alarm.triggered > 0);
16197
16198       /* signal alarm being triggered */
16199       cm_asctime(str, sizeof(str));
16200
16201       if (!alarm.triggered)
16202          strcpy(alarm.time_triggered_first, str);
16203
16204       alarm.triggered++;
16205       strcpy(alarm.time_triggered_last, str);
16206
16207       alarm.checked_last = ss_time();
16208
16209       status = db_set_record(hDB, hkeyalarm, &alarm, sizeof(alarm), 0);
16210       if (status != DB_SUCCESS) {
16211          cm_msg(MERROR, "al_trigger_alarm", "Cannot update alarm record");
16212          return AL_ERROR_ODB;
16213       }
16214
16215    }
16216 #endif                          /* LOCAL_ROUTINES */
16217
16218    return AL_SUCCESS;
16219 }
INT al_trigger_class (char * alarm_class, char * alarm_message, BOOL first)
dox
Definition at line 16225 of file midas.c.
References AL_ERROR_ODB, AL_INVALID_NAME, AL_SUCCESS, ASYNC, cm_get_experiment_database(), cm_msg, cm_transition(), db_find_key(), db_get_record(), db_get_value(), db_set_record(), DB_SUCCESS, el_submit(), ALARM_CLASS::execute_command, ALARM_CLASS::execute_interval, ALARM_CLASS::execute_last, FALSE, hDB, MERROR, MINFO, MTALK, size, ss_system(), ss_time(), STATE_STOPPED, status, ALARM_CLASS::stop_run, ALARM_CLASS::system_message_interval, ALARM_CLASS::system_message_last, tag, TID_INT, TR_STOP, TRUE, ALARM_CLASS::write_elog_message, and ALARM_CLASS::write_system_message.
Referenced by al_trigger_alarm().
16228          : al_trigger_class
16229
16230   Purpose: Trigger a certain alarm class
16231
16232   Input:
16233     char   *alarm_class     Alarm class, must be defined in
16234                             /alarms/classes
16235     char   *alarm_message   Optional message which goes with alarm
16236     BOOL   first            TRUE if alarm is triggered first time
16237                             (used for elog)
16238
16239   Output:
16240
16241   Function value:
16242     AL_INVALID_NAME         Alarm class not defined
16243     AL_SUCCESS              Successful completion
16244
16245 \********************************************************************/
16246 {
16247    int status, size, state;
16248    HNDLE hDB, hkeyclass;
16249    char str[256], command[256], tag[32];
16250    ALARM_CLASS ac;
16251
16252    cm_get_experiment_database(&hDB, NULL);
16253
16254    /* get alarm class */
16255    sprintf(str, "/Alarms/Classes/%s", alarm_class);
16256    db_find_key(hDB, 0, str, &hkeyclass);
16257    if (!hkeyclass) {
16258       cm_msg(MERROR, "al_trigger_class", "Alarm class %s not found in ODB", alarm_class);
16259       return AL_INVALID_NAME;
16260    }
16261
16262    size = sizeof(ac);
16263    status = db_get_record(hDB, hkeyclass, &ac, &size, 0);
16264    if (status != DB_SUCCESS) {
16265       cm_msg(MERROR, "al_trigger_class", "Cannot get alarm class record");
16266       return AL_ERROR_ODB;
16267    }
16268
16269    /* write system message */
16270    if (ac.write_system_message &&
16271        (INT) ss_time() - (INT) ac.system_message_last > ac.system_message_interval) {
16272       sprintf(str, "%s: %s", alarm_class, alarm_message);
16273       cm_msg(MTALK, "al_trigger_class", str);
16274       ac.system_message_last = ss_time();
16275    }
16276
16277    /* write elog message on first trigger */
16278    if (ac.write_elog_message && first)
16279       el_submit(0, "Alarm system", "Alarm", "General", alarm_class, str,
16280                 "", "plain", "", "", 0, "", "", 0, "", "", 0, tag, 32);
16281
16282    /* execute command */
16283    if (ac.execute_command[0] &&
16284        ac.execute_interval > 0 &&
16285        (INT) ss_time() - (INT) ac.execute_last > ac.execute_interval) {
16286       sprintf(str, "%s: %s", alarm_class, alarm_message);
16287       sprintf(command, ac.execute_command, str);
16288       cm_msg(MINFO, "al_trigger_class", "Execute: %s", command);
16289       ss_system(command);
16290       ac.execute_last = ss_time();
16291    }
16292
16293    /* stop run */
16294    if (ac.stop_run) {
16295       state = STATE_STOPPED;
16296       size = sizeof(state);
16297       db_get_value(hDB, 0, "/Runinfo/State", &state, &size, TID_INT, TRUE);
16298       if (state != STATE_STOPPED)
16299          cm_transition(TR_STOP, 0, NULL, 0, ASYNC, FALSE);
16300    }
16301
16302    status = db_set_record(hDB, hkeyclass, &ac, sizeof(ac), 0);
16303    if (status != DB_SUCCESS) {
16304       cm_msg(MERROR, "al_trigger_class", "Cannot update alarm class record");
16305       return AL_ERROR_ODB;
16306    }
16307
16308    return AL_SUCCESS;
16309 }