AlcapDAQ: MDQ_IslandLength
MDQ_IslandLength
[Low Level Data Quality Checks]
Plots information related to length of TPIs in each bank per MIDAS event.
Functions
INT MDQ_IslandLength_init (void)
INT MDQ_IslandLength (EVENT_HEADER *, void *)
INT MDQ_IslandLength_eor (INT)
Variables
HNDLE hDB
TGlobalData * gData
Object to hold data used and produced by modules throughout alcapana stage of analysis.
TSetupData * gSetup
Hardware information about digitizers and detectors to be used during alcapana stage of analysis.
map< std::string, TH1F * > DQ_IslandLength_histograms_map
Map of bank name to histogram of TPI lengths per event.
map< std::string, TH1F * > DQ_IslandLength_histograms_normalised_map
Same as DQ_IslandLength_histograms_map but normalized to number of muons according to TDC.
TH1F * hDQ_TDCCheck_muSc
Coount of number of muSc hits in a run in the TDC.
ANA_MODULE MDQ_IslandLength_module
Detailed Description
Plots information related to length of TPIs in each bank per MIDAS event.
Author:
Nam Tran
Creates several histograms.
Function Documentation
INT MDQ_IslandLength (EVENT_HEADER * pheader, void * pevent)
This method fills the histograms
Definition at line 155 of file MDQ_IslandLength.cpp.
References DQ_IslandLength_histograms_map, DQ_IslandLength_histograms_normalised_map, TGlobalData::fPulseIslandToChannelMap, and TSetupData::GetDetectorName().
{
        // Get the event number
        int midas_event_number = pheader->serial_number;
        // Some typedefs
        typedef map<string, vector<TPulseIsland*> > TStringPulseIslandMap;
        typedef pair<string, vector<TPulseIsland*> > TStringPulseIslandPair;
        typedef map<string, vector<TPulseIsland*> >::iterator map_iterator;
        // Fetch a reference to the gData structure that stores a map
        // of (bank_name, vector<TPulseIsland*>) pairs
        TStringPulseIslandMap& pulse_islands_map =
                gData->fPulseIslandToChannelMap;
        // Loop over the map and get each bankname, vector pair
        for (map_iterator mapIter = pulse_islands_map.begin();
                        mapIter != pulse_islands_map.end(); ++mapIter)
        {
          std::string bankname = mapIter->first;
          std::string detname = gSetup->GetDetectorName(bankname);
          std::vector<TPulseIsland*> thePulses = mapIter->second;
          // Get the histograms before looping through the pulses
          TH1F* hDQ_IslandLength = DQ_IslandLength_histograms_map[bankname];
          TH1F* hDQ_IslandLength_Norm = DQ_IslandLength_histograms_normalised_map[bankname];
          // Loop over the TPulseIslands and plot the histogram
          for (std::vector<TPulseIsland*>::iterator pulseIter = thePulses.begin();
                                pulseIter != thePulses.end(); ++pulseIter) {
            // Make sure the histograms exist and then fill them
            if (DQ_IslandLength_histograms_map.find(bankname) != DQ_IslandLength_histograms_map.end())
              {
                const std::vector<int>& theSamples = (*pulseIter)->GetSamples();
                hDQ_IslandLength->Fill(theSamples.size());
                hDQ_IslandLength_Norm->Fill(theSamples.size());
            }
          }
        }
        return SUCCESS;
}
INT MDQ_IslandLength_eor (INT run_number)
This method does any last minute things to the histograms at the end of the run
Definition at line 125 of file MDQ_IslandLength.cpp.
References DQ_IslandLength_histograms_normalised_map, TGlobalData::fPulseIslandToChannelMap, TSetupData::GetDetectorName(), and hDQ_TDCCheck_muSc.
{
  // Some typedefs
  typedef map<string, vector<TPulseIsland*> > TStringPulseIslandMap;
  typedef pair<string, vector<TPulseIsland*> > TStringPulseIslandPair;
  typedef map<string, vector<TPulseIsland*> >::iterator map_iterator;
  // Fetch a reference to the gData structure that stores a map
  // of (bank_name, vector<TPulseIsland*>) pairs
  TStringPulseIslandMap& pulse_islands_map =
    gData->fPulseIslandToChannelMap;
  // Loop over the map and get each bankname, vector pair
  for (map_iterator mapIter = pulse_islands_map.begin(); mapIter != pulse_islands_map.end(); ++mapIter) {
    std::string bankname = mapIter->first;
    std::string detname = gSetup->GetDetectorName(bankname);
    // Make sure the histograms exist and then fill them
    if (DQ_IslandLength_histograms_normalised_map.find(bankname) != DQ_IslandLength_histograms_normalised_map.end()) {
      DQ_IslandLength_histograms_normalised_map[bankname]->Scale(1./hDQ_TDCCheck_muSc->GetEntries());
    }
  }
  return SUCCESS;
}
INT MDQ_IslandLength_init ()
This method initializes histograms.
Definition at line 81 of file MDQ_IslandLength.cpp.
References DQ_IslandLength_histograms_map, DQ_IslandLength_histograms_normalised_map, TSetupData::fBankToDetectorMap, and TSetupData::GetDetectorName().
{
  // See if the DataQuality_LowLevel/ directory already exists
  std::string dir_name("DataQuality_LowLevel/");
  if (!gDirectory->Cd(dir_name.c_str())) {
    gDirectory->mkdir(dir_name.c_str());
    gDirectory->Cd(dir_name.c_str());
  }
  // Create a histogram for each detector
  std::map<std::string, std::string> bank_to_detector_map = gSetup->fBankToDetectorMap;
  for(std::map<std::string, std::string>::iterator mapIter = bank_to_detector_map.begin();
      mapIter != bank_to_detector_map.end(); mapIter++) {
    std::string bankname = mapIter->first;
    std::string detname = gSetup->GetDetectorName(bankname);
    // hDQ_IslandLength_[DetName]_[BankName]
    std::string histname = "hDQ_IslandLength_" + detname + "_" + bankname;
    std::string histtitle = "Length of each TPulseIsland in " + detname;
    TH1F* hDQ_Histogram = new TH1F(histname.c_str(), histtitle.c_str(),
                                10000, 0, 10000);
    hDQ_Histogram->GetXaxis()->SetTitle("Length [samples]");
    hDQ_Histogram->GetYaxis()->SetTitle("Number of Islands");
    DQ_IslandLength_histograms_map[bankname] = hDQ_Histogram;
    // The normalised histogram
    histname += "_normalised";
    histtitle += " (normalised)";
    TH1F* hDQ_Histogram_Normalised = new TH1F(histname.c_str(), histtitle.c_str(), 10000,0,10000);
    hDQ_Histogram_Normalised->GetXaxis()->SetTitle("Length [samples]");
    std::string yaxislabel = hDQ_Histogram->GetYaxis()->GetTitle();
    yaxislabel += " per TDC muSc Hit";
    hDQ_Histogram_Normalised->GetYaxis()->SetTitle(yaxislabel.c_str());
    DQ_IslandLength_histograms_normalised_map[bankname] = hDQ_Histogram_Normalised;
  }
  gDirectory->Cd("/MidasHists/");
  return SUCCESS;
}
Variable Documentation
DQ_IslandLength_histograms_map
Map of bank name to histogram of TPI lengths per event.
Definition at line 60 of file MDQ_IslandLength.cpp.
Referenced by MDQ_IslandLength(), and MDQ_IslandLength_init().
DQ_IslandLength_histograms_normalised_map
Same as DQ_IslandLength_histograms_map but normalized to number of muons according to TDC.
Definition at line 61 of file MDQ_IslandLength.cpp.
Referenced by MDQ_IslandLength(), MDQ_IslandLength_eor(), and MDQ_IslandLength_init().
TGlobalData* gData
Object to hold data used and produced by modules throughout alcapana stage of analysis.
Definition at line 76 of file analyzer.cpp.
TSetupData* gSetup
Hardware information about digitizers and detectors to be used during alcapana stage of analysis.
Definition at line 80 of file analyzer.cpp.
HNDLE hDB
TH1F* hDQ_TDCCheck_muSc
Coount of number of muSc hits in a run in the TDC.
Definition at line 84 of file MDQ_TDCCheck.cpp.
ANA_MODULE MDQ_IslandLength_module
Initial value:
{
        "MDQ_IslandLength",
        "Nam Tran",
        MDQ_IslandLength,
        NULL,
        MDQ_IslandLength_eor,
        MDQ_IslandLength_init,
        NULL,
        NULL,
        0,
        NULL,
}
Definition at line 65 of file MDQ_IslandLength.cpp.