AlcapDAQ: rootana
rootana
Second stage of analysis in the AlCap framework.
Classes
class TGlobalData
This class holds all of the data created by alcapana analysis modules.
class TPulseIsland
A uniform format for data from many different detectors.
class TSetupData
Holds data relevent to each run.
class TAnalysedPulse
A TAnalysedPulse (TAP) is the product of the second level of analysis in the framework.
class TAnalysedPulseMapWrapper
class TVAnalysedPulseGenerator
The intended ancestor of all TAnalysedPulse generators, used to create TAPs from TPIs.
Modules
Modules
Analysis modules for rootana.
Analyzed Pulse Generators
TAnalysedPulse generators used by rootana.
Detector Pulse Generators
TDetectorPulse generators used by rootana.
Int_t Main_event_loop (TTree *dataTree, ARGUMENTS &arguments)
Detailed Description
Second stage of analysis in the AlCap framework.
Function Documentation
Int_t Main_event_loop (TTree * dataTree, ARGUMENTS & arguments)
rootana_main
Definition at line 165 of file main.cpp.
References TGlobalData::Clear(), gAnalysedPulseMap, gAnalysedPulseTree, gEntryNumber, gTotalEntries, TSetupData::Instance(), modules::navigator::Instance(), TAnalysedPulseMapWrapper::SetMap(), ARGUMENTS::start, and ARGUMENTS::stop.
Referenced by main().
{
/*************************************************************************\
| Loop over tree entries and call histogramming modules.                  |
\*************************************************************************/
  Long64_t nentries = dataTree->GetEntriesFast();
  printf("There are %d entries\n",(int)nentries);
  std::cout<<"Processing file, which may take a while. "
     "Have patience young padawan.."<<std::endl;
  //set up the input data
  if (g_event){
    g_event->Clear("C");
    dataTree->SetBranchAddress("Event",&g_event);
  }
  // How many entries should we loop over?
  Long64_t start = 0;
  Long64_t stop = nentries;
  if(arguments.stop>0){
    if(arguments.start>0)
      start = (Long64_t)(arguments.start-1);
    if((Long64_t)arguments.stop < nentries)
      stop = (Long64_t)arguments.stop;
  }
  else if((Long64_t)arguments.start < nentries && arguments.start > 0){
    stop = (Long64_t)arguments.start;
  }
  gTotalEntries=&stop;
  // wind the file on to the first event
  dataTree->GetEntry(start);
  // Get the first and last module to run with
  modules::iterator first_module = modules::navigator::Instance()->Begin();
  modules::iterator last_module = modules::navigator::Instance()->End();
  modules::iterator it_mod;
  int q = 0;
  for (it_mod=first_module; it_mod != last_module; it_mod++) {
      q |= it_mod->second->BeforeFirstEntry(g_event, TSetupData::Instance());
      if(q){
          printf("Error during pre-processing for module %s\n",it_mod->first.c_str());
          return q;
      }
  }
  q = 0;
  //process entries
  Long64_t jentry;
  gEntryNumber=&jentry;
  for ( jentry=start; jentry<stop;jentry++) {
    if(g_event){
      g_event->Clear("C");
      //ClearGlobalData(g_event);
      dataTree->SetBranchAddress("Event",&g_event);
    }
    if (jentry%100 == 0) {
      printf("Completed %lld events out of %lld\n", jentry, stop);
    }
    // Let's get the next event
    dataTree->GetEntry(jentry);
    for (it_mod=first_module; it_mod != last_module; it_mod++) {
        q |= it_mod->second->ProcessGenericEntry(g_event,TSetupData::Instance());
        if(q){
            printf("q was non-zero for module %s when jentry was %lld\n",it_mod->first.c_str(), jentry);
            return q;
        }
    }
    gAnalysedPulseMapWrapper->SetMap(gAnalysedPulseMap);
    //gAnalysedPulseMapWrapper->ShowInfo();
    gAnalysedPulseTree->Fill();
  }
  //post-process on last entry
  q = 0;
  for (it_mod=first_module; it_mod != last_module; it_mod++) {
    q |= it_mod->second->AfterLastEntry(g_event,TSetupData::Instance());
        if(q){
            printf("Error during post-processing for module %s\n",it_mod->first.c_str());
            return q;
        }
  }
  if (q) {
     printf("Error during post-processing last entry (%lld)\n",(stop-1));
      return q;
  }
  printf("Finished processing data normally\n");
  return 0;
}