AlcapDAQ: MDQ_IslandTimestamp
MDQ_IslandTimestamp
[Low Level Data Quality Checks]
Histograms the timestamps from each MIDAS event for each detector.
Functions
INT MDQ_IslandTimestamp_init (void)
INT MDQ_IslandTimestamp (EVENT_HEADER *, void *)
INT MDQ_IslandTimestamp_eor (INT)
Variables
HNDLE hDB
TGlobalData * gData
Object to hold data used and produced by modules throughout alcapana stage of analysis.
TSetupData * gSetup
Hardware information about digitizers and detectors to be used during alcapana stage of analysis.
map< std::string, TH1F * > DQ_IslandTimestamp_histograms_map
Map of bank name to histogram of time stamps within a MIDAS event.
map< std::string, TH1F * > DQ_IslandTimestamp_histograms_normalised_map
Same as DQ_IslandTimestamp_histograms_map, but vertical axis is normalised to number of muon hits according to TDC.
TH1F * hDQ_TDCCheck_muSc
Coount of number of muSc hits in a run in the TDC.
ANA_MODULE MDQ_IslandTimestamp_module
Detailed Description
Histograms the timestamps from each MIDAS event for each detector.
Author:
Andrew Edmonds
Creates a number of histograms.
Function Documentation
INT MDQ_IslandTimestamp (EVENT_HEADER * pheader, void * pevent)
This method fills the histograms
Definition at line 156 of file MDQ_IslandTimestamp.cpp.
References DQ_IslandTimestamp_histograms_map, DQ_IslandTimestamp_histograms_normalised_map, TGlobalData::fPulseIslandToChannelMap, and TSetupData::GetDetectorName().
{
        // Get the event number
        int midas_event_number = pheader->serial_number;
        // Some typedefs
        typedef map<string, vector<TPulseIsland*> > TStringPulseIslandMap;
        typedef pair<string, vector<TPulseIsland*> > TStringPulseIslandPair;
        typedef map<string, vector<TPulseIsland*> >::iterator map_iterator;
        // Fetch a reference to the gData structure that stores a map
        // of (bank_name, vector<TPulseIsland*>) pairs
        TStringPulseIslandMap& pulse_islands_map =
                gData->fPulseIslandToChannelMap;
        // Loop over the map and get each bankname, vector pair
        for (map_iterator mapIter = pulse_islands_map.begin(); mapIter != pulse_islands_map.end(); ++mapIter)
        {
          std::string bankname = mapIter->first;
          std::string detname = gSetup->GetDetectorName(bankname);
          std::vector<TPulseIsland*> thePulses = mapIter->second;
          // Get the histograms before looping through the pulses
          TH1F* hDQ_IslandTimestamp = DQ_IslandTimestamp_histograms_map[bankname];
          TH1F* hDQ_IslandTimestamp_Norm = DQ_IslandTimestamp_histograms_normalised_map[bankname];
          // Loop over the TPulseIslands and plot the histogram
          for (std::vector<TPulseIsland*>::iterator pulseIter = thePulses.begin(); pulseIter != thePulses.end(); ++pulseIter) {
            // Make sure the histograms exist and then fill them
            if (DQ_IslandTimestamp_histograms_map.find(bankname) != DQ_IslandTimestamp_histograms_map.end()) {
              int time_stamp = (*pulseIter)->GetTimeStamp();
              double clock_tick_in_ns = (*pulseIter)->GetClockTickInNs();
              double block_time = time_stamp * clock_tick_in_ns;
              hDQ_IslandTimestamp->Fill(block_time);
              hDQ_IslandTimestamp_Norm->Fill(block_time);
            }
          }
        }
        return SUCCESS;
}
INT MDQ_IslandTimestamp_eor (INT run_number)
This method does any last minute things to the histograms at the end of the run
Definition at line 127 of file MDQ_IslandTimestamp.cpp.
References DQ_IslandTimestamp_histograms_normalised_map, TGlobalData::fPulseIslandToChannelMap, TSetupData::GetDetectorName(), and hDQ_TDCCheck_muSc.
{
  // Some typedefs
  typedef map<string, vector<TPulseIsland*> > TStringPulseIslandMap;
  typedef pair<string, vector<TPulseIsland*> > TStringPulseIslandPair;
  typedef map<string, vector<TPulseIsland*> >::iterator map_iterator;
  // Fetch a reference to the gData structure that stores a map
  // of (bank_name, vector<TPulseIsland*>) pairs
  TStringPulseIslandMap& pulse_islands_map =
    gData->fPulseIslandToChannelMap;
  // Loop over the map and get each bankname, vector pair
  for (map_iterator mapIter = pulse_islands_map.begin(); mapIter != pulse_islands_map.end(); ++mapIter) {
    std::string bankname = mapIter->first;
    std::string detname = gSetup->GetDetectorName(bankname);
    // Make sure the histograms exist and then fill them
    if (DQ_IslandTimestamp_histograms_normalised_map.find(bankname) != DQ_IslandTimestamp_histograms_normalised_map.end()) {
      DQ_IslandTimestamp_histograms_normalised_map[bankname]->Scale(1./hDQ_TDCCheck_muSc->GetEntries());
    }
  }
  return SUCCESS;
}
INT MDQ_IslandTimestamp_init ()
This method initializes histograms.
Definition at line 79 of file MDQ_IslandTimestamp.cpp.
References DQ_IslandTimestamp_histograms_map, DQ_IslandTimestamp_histograms_normalised_map, TSetupData::fBankToDetectorMap, TSetupData::GetClockTick(), and TSetupData::GetDetectorName().
{
  // See if the DataQuality_LowLevel/ directory already exists
  if (!gDirectory->Cd("DataQuality_LowLevel")) {
    std::string dir_name("DataQuality_LowLevel/");
    gDirectory->mkdir(dir_name.c_str());
    gDirectory->Cd(dir_name.c_str());
  }
  // Create a histogram for each detector
  std::map<std::string, std::string> bank_to_detector_map = gSetup->fBankToDetectorMap;
  for(std::map<std::string, std::string>::iterator mapIter = bank_to_detector_map.begin();
      mapIter != bank_to_detector_map.end(); mapIter++) {
    std::string bankname = mapIter->first;
    std::string detname = gSetup->GetDetectorName(bankname);
    double bin_width = gSetup->GetClockTick(bankname) * 1000;
    double bin_max = 120e6;
    int n_bins = bin_max / bin_width;
    // hDQ_IslandTimestamp_[DetName]_[BankName]
    std::string histname = "hDQ_IslandTimestamp_" + detname + "_" + bankname;
    std::string histtitle = "Distribution of time stamps in " + detname;
    TH1F* hDQ_Histogram = new TH1F(histname.c_str(), histtitle.c_str(), n_bins, 0, bin_max);
    hDQ_Histogram->GetXaxis()->SetTitle("Time Stamp [ns]");
    hDQ_Histogram->GetYaxis()->SetTitle("Number of TPulseIslands");
    DQ_IslandTimestamp_histograms_map[bankname] = hDQ_Histogram;
    // The normalised histogram
    histname += "_normalised";
    histtitle += " (normalised)";
    TH1F* hDQ_Histogram_Normalised = new TH1F(histname.c_str(), histtitle.c_str(), n_bins,0,bin_max);
    hDQ_Histogram_Normalised->GetXaxis()->SetTitle("Time Stamp [ns]");
    std::string yaxislabel = hDQ_Histogram->GetYaxis()->GetTitle();
    yaxislabel += " per TDC muSc Hit";
    hDQ_Histogram_Normalised->GetYaxis()->SetTitle(yaxislabel.c_str());
    DQ_IslandTimestamp_histograms_normalised_map[bankname] = hDQ_Histogram_Normalised;
  }
  gDirectory->Cd("/MidasHists/");
  return SUCCESS;
}
Variable Documentation
DQ_IslandTimestamp_histograms_map
Map of bank name to histogram of time stamps within a MIDAS event.
Definition at line 58 of file MDQ_IslandTimestamp.cpp.
Referenced by MDQ_IslandTimestamp(), and MDQ_IslandTimestamp_init().
DQ_IslandTimestamp_histograms_normalised_map
Same as DQ_IslandTimestamp_histograms_map, but vertical axis is normalised to number of muon hits according to TDC.
Definition at line 59 of file MDQ_IslandTimestamp.cpp.
Referenced by MDQ_IslandTimestamp(), MDQ_IslandTimestamp_eor(), and MDQ_IslandTimestamp_init().
TGlobalData* gData
Object to hold data used and produced by modules throughout alcapana stage of analysis.
Definition at line 76 of file analyzer.cpp.
TSetupData* gSetup
Hardware information about digitizers and detectors to be used during alcapana stage of analysis.
Definition at line 80 of file analyzer.cpp.
HNDLE hDB
TH1F* hDQ_TDCCheck_muSc
Coount of number of muSc hits in a run in the TDC.
Definition at line 84 of file MDQ_TDCCheck.cpp.
ANA_MODULE MDQ_IslandTimestamp_module
Initial value:
{
        "MDQ_IslandTimestamp",
        "Andrew Edmonds",
        MDQ_IslandTimestamp,
        NULL,
        MDQ_IslandTimestamp_eor,
        MDQ_IslandTimestamp_init,
        NULL,
        NULL,
        0,
        NULL,
}
Definition at line 63 of file MDQ_IslandTimestamp.cpp.