AlcapDAQ: midas/drivers/class/hv.h File Reference
midas/drivers/class/hv.h File Reference
Functions
INT cd_hv (INT cmd, PEQUIPMENT pequipment)
INT cd_hv_read (char *pevent, int)
Function Documentation
INT cd_hv (INT cmd, PEQUIPMENT pequipment)
Definition at line 819 of file hv.c.
References cm_msg, CMD_EXIT, CMD_IDLE, CMD_INIT, FE_ERR_DRIVER, hv_exit(), hv_idle(), hv_init(), MERROR, and status.
{
   INT status;
   switch (cmd) {
   case CMD_INIT:
      status = hv_init(pequipment);
      break;
   case CMD_EXIT:
      status = hv_exit(pequipment);
      break;
   case CMD_IDLE:
      status = hv_idle(pequipment);
      break;
   default:
      cm_msg(MERROR, "HV class driver", "Received unknown command %d", cmd);
      status = FE_ERR_DRIVER;
      break;
   }
   return status;
}
INT cd_hv_read (char * pevent, int)
Definition at line 740 of file hv.c.
References bk_close(), bk_create(), bk_init(), bk_size(), eqpmnt::cd_info, HV_INFO::current, HV_INFO::demand, EVENT_ID, F4_BKTYPE, HV_INFO::format, FORMAT_FIXED, FORMAT_MIDAS, FORMAT_YBOS, I4_BKTYPE, if, HV_INFO::measured, HV_INFO::num_channels, SERIAL_NUMBER, TID_FLOAT, TIME_STAMP, ybk_close(), ybk_create(), ybk_init(), and ybk_size().
{
   float *pdata;
   DWORD *pdw;
   HV_INFO *hv_info;
   EQUIPMENT *pequipment;
   pequipment = *((EQUIPMENT **) pevent);
   hv_info = (HV_INFO *) pequipment->cd_info;
   if (hv_info->format == FORMAT_FIXED) {
      memcpy(pevent, hv_info->demand, sizeof(float) * hv_info->num_channels);
      pevent += sizeof(float) * hv_info->num_channels;
      memcpy(pevent, hv_info->measured, sizeof(float) * hv_info->num_channels);
      pevent += sizeof(float) * hv_info->num_channels;
      memcpy(pevent, hv_info->current, sizeof(float) * hv_info->num_channels);
      pevent += sizeof(float) * hv_info->num_channels;
      return 3 * sizeof(float) * hv_info->num_channels;
   } else if (hv_info->format == FORMAT_MIDAS) {
      bk_init(pevent);
      /* create DMND bank */
      bk_create(pevent, "DMND", TID_FLOAT, &pdata);
      memcpy(pdata, hv_info->demand, sizeof(float) * hv_info->num_channels);
      pdata += hv_info->num_channels;
      bk_close(pevent, pdata);
      /* create MSRD bank */
      bk_create(pevent, "MSRD", TID_FLOAT, &pdata);
      memcpy(pdata, hv_info->measured, sizeof(float) * hv_info->num_channels);
      pdata += hv_info->num_channels;
      bk_close(pevent, pdata);
      /* create CRNT bank */
      bk_create(pevent, "CRNT", TID_FLOAT, &pdata);
      memcpy(pdata, hv_info->current, sizeof(float) * hv_info->num_channels);
      pdata += hv_info->num_channels;
      bk_close(pevent, pdata);
      return bk_size(pevent);
   } else if (hv_info->format == FORMAT_YBOS) {
      ybk_init((DWORD *) pevent);
      /* create EVID bank */
      ybk_create((DWORD *) pevent, "EVID", I4_BKTYPE, (DWORD *) (&pdw));
      *(pdw)++ = EVENT_ID(pevent);      /* Event_ID + Mask */
      *(pdw)++ = SERIAL_NUMBER(pevent); /* Serial number */
      *(pdw)++ = TIME_STAMP(pevent);    /* Time Stamp */
      ybk_close((DWORD *) pevent, pdw);
      /* create DMND bank */
      ybk_create((DWORD *) pevent, "DMND", F4_BKTYPE, (DWORD *) & pdata);
      memcpy(pdata, hv_info->demand, sizeof(float) * hv_info->num_channels);
      pdata += hv_info->num_channels;
      ybk_close((DWORD *) pevent, pdata);
      /* create MSRD bank */
      ybk_create((DWORD *) pevent, "MSRD", F4_BKTYPE, (DWORD *) & pdata);
      memcpy(pdata, hv_info->measured, sizeof(float) * hv_info->num_channels);
      pdata += hv_info->num_channels;
      ybk_close((DWORD *) pevent, pdata);
      /* create CRNT bank */
      ybk_create((DWORD *) pevent, "CRNT", F4_BKTYPE, (DWORD *) & pdata);
      memcpy(pdata, hv_info->current, sizeof(float) * hv_info->num_channels);
      pdata += hv_info->num_channels;
      ybk_close((DWORD *) pevent, pdata);
      return ybk_size((DWORD *) pevent);
   }
   return 0;
}