AlcapDAQ: CAEN/CAENVMELib/CAENVMELib-2.30.2/include/CAENVMElib.h File Reference
CAENVMElib.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include "CAENVMEoslib.h"
#include "CAENVMEtypes.h"
Functions
const char * CAENVME_DecodeError (CVErrorCodes Code)
CAENVME_API CAENVME_SWRelease (char *SwRel)
CAENVME_API CAENVME_BoardFWRelease (int32_t Handle, char *FWRel)
CAENVME_API CAENVME_DriverRelease (int32_t Handle, char *Rel)
CAENVME_API CAENVME_DeviceReset (int32_t dev)
CAENVME_API CAENVME_Init (CVBoardTypes BdType, short Link, short BdNum, int32_t *Handle)
CAENVME_API CAENVME_End (int32_t Handle)
CAENVME_API CAENVME_ReadCycle (int32_t Handle, uint32_t Address, void *Data, CVAddressModifier AM, CVDataWidth DW)
CAENVME_API CAENVME_RMWCycle (int32_t Handle, uint32_t Address, void *Data, CVAddressModifier AM, CVDataWidth DW)
CAENVME_API CAENVME_WriteCycle (int32_t Handle, uint32_t Address, void *Data, CVAddressModifier AM, CVDataWidth DW)
CAENVME_API CAENVME_MultiRead (int32_t Handle, uint32_t *Addrs, uint32_t *Buffer, int NCycles, CVAddressModifier *AMs, CVDataWidth *DWs, CVErrorCodes *ECs)
CAENVME_API CAENVME_MultiWrite (int32_t Handle, uint32_t *Addrs, uint32_t *Buffer, int NCycles, CVAddressModifier *AMs, CVDataWidth *DWs, CVErrorCodes *ECs)
CAENVME_API CAENVME_BLTReadCycle (int32_t Handle, uint32_t Address, void *Buffer, int Size, CVAddressModifier AM, CVDataWidth DW, int *count)
CAENVME_API CAENVME_FIFOBLTReadCycle (int32_t Handle, uint32_t Address, void *Buffer, int Size, CVAddressModifier AM, CVDataWidth DW, int *count)
CAENVME_API CAENVME_MBLTReadCycle (int32_t Handle, uint32_t Address, void *Buffer, int Size, CVAddressModifier AM, int *count)
CAENVME_API CAENVME_FIFOMBLTReadCycle (int32_t Handle, uint32_t Address, void *Buffer, int Size, CVAddressModifier AM, int *count)
CAENVME_API CAENVME_BLTWriteCycle (int32_t Handle, uint32_t Address, void *Buffer, int size, CVAddressModifier AM, CVDataWidth DW, int *count)
CAENVME_API CAENVME_FIFOBLTWriteCycle (int32_t Handle, uint32_t Address, void *Buffer, int size, CVAddressModifier AM, CVDataWidth DW, int *count)
CAENVME_API CAENVME_MBLTWriteCycle (int32_t Handle, uint32_t Address, void *Buffer, int size, CVAddressModifier AM, int *count)
CAENVME_API CAENVME_FIFOMBLTWriteCycle (int32_t Handle, uint32_t Address, void *Buffer, int size, CVAddressModifier AM, int *count)
CAENVME_API CAENVME_ADOCycle (int32_t Handle, uint32_t Address, CVAddressModifier AM)
CAENVME_API CAENVME_ADOHCycle (int32_t Handle, uint32_t Address, CVAddressModifier AM)
CAENVME_API CAENVME_IACKCycle (int32_t Handle, CVIRQLevels Level, void *Vector, CVDataWidth DW)
CAENVME_API CAENVME_IRQCheck (int32_t Handle, CAEN_BYTE *Mask)
CAENVME_API CAENVME_IRQEnable (int32_t Handle, uint32_t Mask)
CAENVME_API CAENVME_IRQDisable (int32_t Handle, uint32_t Mask)
CAENVME_API CAENVME_IRQWait (int32_t Handle, uint32_t Mask, uint32_t Timeout)
CAENVME_API CAENVME_SetPulserConf (int32_t Handle, CVPulserSelect PulSel, unsigned char Period, unsigned char Width, CVTimeUnits Unit, unsigned char PulseNo, CVIOSources Start, CVIOSources Reset)
CAENVME_API CAENVME_SetScalerConf (int32_t Handle, short Limit, short AutoReset, CVIOSources Hit, CVIOSources Gate, CVIOSources Reset)
CAENVME_API CAENVME_SetOutputConf (int32_t Handle, CVOutputSelect OutSel, CVIOPolarity OutPol, CVLEDPolarity LEDPol, CVIOSources Source)
CAENVME_API CAENVME_SetInputConf (int32_t Handle, CVInputSelect InSel, CVIOPolarity InPol, CVLEDPolarity LEDPol)
CAENVME_API CAENVME_GetPulserConf (int32_t Handle, CVPulserSelect PulSel, unsigned char *Period, unsigned char *Width, CVTimeUnits *Unit, unsigned char *PulseNo, CVIOSources *Start, CVIOSources *Reset)
CAENVME_API CAENVME_GetScalerConf (int32_t Handle, short *Limit, short *AutoReset, CVIOSources *Hit, CVIOSources *Gate, CVIOSources *Reset)
CAENVME_API CAENVME_GetOutputConf (int32_t Handle, CVOutputSelect OutSel, CVIOPolarity *OutPol, CVLEDPolarity *LEDPol, CVIOSources *Source)
CAENVME_API CAENVME_GetInputConf (int32_t Handle, CVInputSelect InSel, CVIOPolarity *InPol, CVLEDPolarity *LEDPol)
CAENVME_API CAENVME_ReadRegister (int32_t Handle, CVRegisters Reg, unsigned int *Data)
CAENVME_API CAENVME_WriteRegister (int32_t Handle, CVRegisters Reg, unsigned int Data)
CAENVME_API CAENVME_SetOutputRegister (int32_t Handle, unsigned short Mask)
CAENVME_API CAENVME_ClearOutputRegister (int32_t Handle, unsigned short Mask)
CAENVME_API CAENVME_PulseOutputRegister (int32_t Handle, unsigned short Mask)
CAENVME_API CAENVME_ReadDisplay (int32_t Handle, CVDisplay *Value)
CAENVME_API CAENVME_SetArbiterType (int32_t Handle, CVArbiterTypes Value)
CAENVME_API CAENVME_SetRequesterType (int32_t Handle, CVRequesterTypes Value)
CAENVME_API CAENVME_SetReleaseType (int32_t Handle, CVReleaseTypes Value)
CAENVME_API CAENVME_SetBusReqLevel (int32_t Handle, CVBusReqLevels Value)
CAENVME_API CAENVME_SetTimeout (int32_t Handle, CVVMETimeouts Value)
CAENVME_API CAENVME_SetLocationMonitor (int32_t Handle, uint32_t Address, CVAddressModifier Am, short Write, short Lword, short Iack)
CAENVME_API CAENVME_SetFIFOMode (int32_t Handle, short Value)
CAENVME_API CAENVME_GetArbiterType (int32_t Handle, CVArbiterTypes *Value)
CAENVME_API CAENVME_GetRequesterType (int32_t Handle, CVRequesterTypes *Value)
CAENVME_API CAENVME_GetReleaseType (int32_t Handle, CVReleaseTypes *Value)
CAENVME_API CAENVME_GetBusReqLevel (int32_t Handle, CVBusReqLevels *Value)
CAENVME_API CAENVME_GetTimeout (int32_t Handle, CVVMETimeouts *Value)
CAENVME_API CAENVME_GetFIFOMode (int32_t Handle, short *Value)
CAENVME_API CAENVME_SystemReset (int32_t Handle)
CAENVME_API CAENVME_ResetScalerCount (int32_t Handle)
CAENVME_API CAENVME_EnableScalerGate (int32_t Handle)
CAENVME_API CAENVME_DisableScalerGate (int32_t Handle)
CAENVME_API CAENVME_StartPulser (int32_t Handle, CVPulserSelect PulSel)
CAENVME_API CAENVME_StopPulser (int32_t Handle, CVPulserSelect PulSel)
CAENVME_API CAENVME_WriteFlashPage (int32_t Handle, unsigned char *Data, int PageNum)
CAENVME_API CAENVME_ReadFlashPage (int32_t Handle, unsigned char *Data, int PageNum)
CAENVME_API CAENVME_EraseFlashPage (int32_t Handle, int Pagenum)
Function Documentation
CAENVME_API CAENVME_ADOCycle (int32_t Handle, uint32_t Address, CVAddressModifier AM)
CAENVME_API CAENVME_ADOHCycle (int32_t Handle, uint32_t Address, CVAddressModifier AM)
CAENVME_API CAENVME_BLTReadCycle (int32_t Handle, uint32_t Address, void * Buffer, int Size, CVAddressModifier AM, CVDataWidth DW, int * count)
Referenced by CaenVmeReadBlt().
CAENVME_API CAENVME_BLTWriteCycle (int32_t Handle, uint32_t Address, void * Buffer, int size, CVAddressModifier AM, CVDataWidth DW, int * count)
Referenced by CaenVmeWriteBlt().
CAENVME_API CAENVME_BoardFWRelease (int32_t Handle, char * FWRel)
Referenced by main().
CAENVME_API CAENVME_ClearOutputRegister (int32_t Handle, unsigned short Mask)
const char* CAENVME_DecodeError (CVErrorCodes Code)
           --- CAEN SpA - Computing Systems Division ---
CAENVMElib.h
Created: March 2004
CAENVME_API CAENVME_DeviceReset (int32_t dev)
CAENVME_API CAENVME_DisableScalerGate (int32_t Handle)
CAENVME_API CAENVME_DriverRelease (int32_t Handle, char * Rel)
CAENVME_API CAENVME_EnableScalerGate (int32_t Handle)
CAENVME_API CAENVME_End (int32_t Handle)
Referenced by main().
CAENVME_API CAENVME_EraseFlashPage (int32_t Handle, int Pagenum)
CAENVME_API CAENVME_FIFOBLTReadCycle (int32_t Handle, uint32_t Address, void * Buffer, int Size, CVAddressModifier AM, CVDataWidth DW, int * count)
CAENVME_API CAENVME_FIFOBLTWriteCycle (int32_t Handle, uint32_t Address, void * Buffer, int size, CVAddressModifier AM, CVDataWidth DW, int * count)
CAENVME_API CAENVME_FIFOMBLTReadCycle (int32_t Handle, uint32_t Address, void * Buffer, int Size, CVAddressModifier AM, int * count)
CAENVME_API CAENVME_FIFOMBLTWriteCycle (int32_t Handle, uint32_t Address, void * Buffer, int size, CVAddressModifier AM, int * count)
CAENVME_API CAENVME_GetArbiterType (int32_t Handle, CVArbiterTypes * Value)
CAENVME_API CAENVME_GetBusReqLevel (int32_t Handle, CVBusReqLevels * Value)
CAENVME_API CAENVME_GetFIFOMode (int32_t Handle, short * Value)
CAENVME_API CAENVME_GetInputConf (int32_t Handle, CVInputSelect InSel, CVIOPolarity * InPol, CVLEDPolarity * LEDPol)
CAENVME_API CAENVME_GetOutputConf (int32_t Handle, CVOutputSelect OutSel, CVIOPolarity * OutPol, CVLEDPolarity * LEDPol, CVIOSources * Source)
CAENVME_API CAENVME_GetPulserConf (int32_t Handle, CVPulserSelect PulSel, unsigned char * Period, unsigned char * Width, CVTimeUnits * Unit, unsigned char * PulseNo, CVIOSources * Start, CVIOSources * Reset)
CAENVME_API CAENVME_GetReleaseType (int32_t Handle, CVReleaseTypes * Value)
CAENVME_API CAENVME_GetRequesterType (int32_t Handle, CVRequesterTypes * Value)
CAENVME_API CAENVME_GetScalerConf (int32_t Handle, short * Limit, short * AutoReset, CVIOSources * Hit, CVIOSources * Gate, CVIOSources * Reset)
CAENVME_API CAENVME_GetTimeout (int32_t Handle, CVVMETimeouts * Value)
CAENVME_API CAENVME_IACKCycle (int32_t Handle, CVIRQLevels Level, void * Vector, CVDataWidth DW)
Referenced by CaenVmeIrqCheck().
CAENVME_API CAENVME_Init (CVBoardTypes BdType, short Link, short BdNum, int32_t * Handle)
Referenced by main().
CAENVME_API CAENVME_IRQCheck (int32_t Handle, CAEN_BYTE * Mask)
Referenced by CaenVmeIrqCheck().
CAENVME_API CAENVME_IRQDisable (int32_t Handle, uint32_t Mask)
CAENVME_API CAENVME_IRQEnable (int32_t Handle, uint32_t Mask)
CAENVME_API CAENVME_IRQWait (int32_t Handle, uint32_t Mask, uint32_t Timeout)
CAENVME_API CAENVME_MBLTReadCycle (int32_t Handle, uint32_t Address, void * Buffer, int Size, CVAddressModifier AM, int * count)
CAENVME_API CAENVME_MBLTWriteCycle (int32_t Handle, uint32_t Address, void * Buffer, int size, CVAddressModifier AM, int * count)
CAENVME_API CAENVME_MultiRead (int32_t Handle, uint32_t * Addrs, uint32_t * Buffer, int NCycles, CVAddressModifier * AMs, CVDataWidth * DWs, CVErrorCodes * ECs)
CAENVME_API CAENVME_MultiWrite (int32_t Handle, uint32_t * Addrs, uint32_t * Buffer, int NCycles, CVAddressModifier * AMs, CVDataWidth * DWs, CVErrorCodes * ECs)
CAENVME_API CAENVME_PulseOutputRegister (int32_t Handle, unsigned short Mask)
CAENVME_API CAENVME_ReadCycle (int32_t Handle, uint32_t Address, void * Data, CVAddressModifier AM, CVDataWidth DW)
Referenced by CaenVmeRead().
CAENVME_API CAENVME_ReadDisplay (int32_t Handle, CVDisplay * Value)
CAENVME_API CAENVME_ReadFlashPage (int32_t Handle, unsigned char * Data, int PageNum)
Referenced by main().
CAENVME_API CAENVME_ReadRegister (int32_t Handle, CVRegisters Reg, unsigned int * Data)
Referenced by A3818_EnableBPIAccess(), A3818_EnableSPIAccess(), bpi_flash_read(), GetFlashStatus32(), ReadFlashPage32(), and ReadFlashSecurityReg32().
CAENVME_API CAENVME_ResetScalerCount (int32_t Handle)
CAENVME_API CAENVME_RMWCycle (int32_t Handle, uint32_t Address, void * Data, CVAddressModifier AM, CVDataWidth DW)
CAENVME_API CAENVME_SetArbiterType (int32_t Handle, CVArbiterTypes Value)
CAENVME_API CAENVME_SetBusReqLevel (int32_t Handle, CVBusReqLevels Value)
CAENVME_API CAENVME_SetFIFOMode (int32_t Handle, short Value)
CAENVME_API CAENVME_SetInputConf (int32_t Handle, CVInputSelect InSel, CVIOPolarity InPol, CVLEDPolarity LEDPol)
CAENVME_API CAENVME_SetLocationMonitor (int32_t Handle, uint32_t Address, CVAddressModifier Am, short Write, short Lword, short Iack)
CAENVME_API CAENVME_SetOutputConf (int32_t Handle, CVOutputSelect OutSel, CVIOPolarity OutPol, CVLEDPolarity LEDPol, CVIOSources Source)
CAENVME_API CAENVME_SetOutputRegister (int32_t Handle, unsigned short Mask)
CAENVME_API CAENVME_SetPulserConf (int32_t Handle, CVPulserSelect PulSel, unsigned char Period, unsigned char Width, CVTimeUnits Unit, unsigned char PulseNo, CVIOSources Start, CVIOSources Reset)
CAENVME_API CAENVME_SetReleaseType (int32_t Handle, CVReleaseTypes Value)
CAENVME_API CAENVME_SetRequesterType (int32_t Handle, CVRequesterTypes Value)
CAENVME_API CAENVME_SetScalerConf (int32_t Handle, short Limit, short AutoReset, CVIOSources Hit, CVIOSources Gate, CVIOSources Reset)
CAENVME_API CAENVME_SetTimeout (int32_t Handle, CVVMETimeouts Value)
CAENVME_API CAENVME_StartPulser (int32_t Handle, CVPulserSelect PulSel)
CAENVME_API CAENVME_StopPulser (int32_t Handle, CVPulserSelect PulSel)
CAENVME_API CAENVME_SWRelease (char * SwRel)
CAENVME_API CAENVME_SystemReset (int32_t Handle)
CAENVME_API CAENVME_WriteCycle (int32_t Handle, uint32_t Address, void * Data, CVAddressModifier AM, CVDataWidth DW)
Referenced by CaenVmeWrite().
CAENVME_API CAENVME_WriteFlashPage (int32_t Handle, unsigned char * Data, int PageNum)
Referenced by main().
CAENVME_API CAENVME_WriteRegister (int32_t Handle, CVRegisters Reg, unsigned int Data)
Referenced by A3818_EnableBPIAccess(), A3818_EnableSPIAccess(), bpi_flash_read(), bpi_flash_write(), GetFlashStatus32(), main(), ReadFlashPage32(), ReadFlashSecurityReg32(), and WriteFlashPage32().