AlcapDAQ: analyzer/compress/io_buffer.cpp File Reference
io_buffer.cpp File Reference
#include <stdio.h>
#include <assert.h>
#include "midas.h"
#include "mucap_compress.h"
Functions
void start_output_buffer (io_buffer *buffer, unsigned char *p)
int flush_output_buffer (io_buffer *buffer)
void io_buffer_put (io_buffer *buffer, unsigned int code_bits, int code_length)
void start_input_buffer (io_buffer *buffer, unsigned char *p)
unsigned int io_buffer_get (io_buffer *buffer, int num_bits)
Function Documentation
int flush_output_buffer (io_buffer * buffer)
Definition at line 23 of file io_buffer.cpp.
References io_buffer::num_codes, io_buffer::p, io_buffer::start, io_buffer::w, and io_buffer::w_bits.
Referenced by encode_caen(), encode_cmp_times(), encode_fadc(), encode_hits(), encode_n2fadc_ndet(), encode_n2fadc_tpc(), encode_nfadc(), encode_times(), and flush_rle().
 {
   // store the last word
   *((buffer->p)++) = buffer->w << buffer->w_bits;
   // remember the length of the buffer, in bytes and in codes
   *(buffer->start) = buffer->num_codes;
   //return ((unsigned int) buffer->p) - ((unsigned int) buffer->start);
   return (int) (((char *) buffer->p) - ((char *) buffer->start));
 }
unsigned int io_buffer_get (io_buffer * buffer, int num_bits)
Definition at line 70 of file io_buffer.cpp.
References io_buffer_get(), io_buffer::p, io_buffer::w, and io_buffer::w_bits.
Referenced by decode_caen(), decode_cmp_times(), decode_fadc(), decode_hits(), decode_n2fadc_ndet(), decode_n2fadc_tpc(), decode_nfadc(), decode_times(), io_buffer_get(), and rle_get().
 {
   if (buffer->w_bits == 0) {
     buffer->w = *((buffer->p)++);
     buffer->w_bits = 32;
   }
   int w_bits = buffer->w_bits;
   unsigned int retval;
   if (num_bits <= w_bits) {
     retval = buffer->w >> (32 - num_bits);
     buffer->w = buffer->w << num_bits;
     buffer->w_bits = w_bits - num_bits;
   } else {
     unsigned int first_part =
         io_buffer_get(buffer, w_bits) << (num_bits - w_bits);
     retval = first_part | io_buffer_get(buffer, num_bits - w_bits);
   }
   return retval;
 }
void io_buffer_put (io_buffer * buffer, unsigned int code_bits, int code_length)
Definition at line 36 of file io_buffer.cpp.
References io_buffer::p, io_buffer::w, and io_buffer::w_bits.
Referenced by encode_caen(), encode_cmp_times(), encode_fadc(), encode_hits(), encode_n2fadc_ndet(), encode_n2fadc_tpc(), encode_nfadc(), encode_times(), flush_rle(), huffman_put_symbol(), and rle_put().
 {
   assert(code_length > 0 && code_length < 32);
   // Does this symbol fit in our buffer word?
   if (code_length < buffer->w_bits) {
     // OK, so put it there...
     buffer->w = (buffer->w << code_length) | code_bits;
     buffer->w_bits -= code_length;
   } else if (code_length == buffer->w_bits) {
     // Only barely...write out the buffer word
     buffer->w = (buffer->w << code_length) | code_bits;
     *((buffer->p)++) = buffer->w;
     buffer->w_bits = 32;
   } else {
     // No, we'll have to split the code across two words.
     unsigned int first_code_bits =
         code_bits >> (code_length - buffer->w_bits);
     *((buffer->p)++) = (buffer->w << buffer->w_bits) | first_code_bits;
     buffer->w = code_bits;
     buffer->w_bits = 32 - code_length + buffer->w_bits;
   }
 }
void start_input_buffer (io_buffer * buffer, unsigned char * p)
Definition at line 61 of file io_buffer.cpp.
References io_buffer::num_codes, io_buffer::p, io_buffer::start, io_buffer::w, and io_buffer::w_bits.
Referenced by caen_expand(), cmp_expand(), fadc_expand(), hits_expand(), n2fadc_ndet_expand(), n2fadc_tpc_expand(), nfadc_expand(), stck_expand(), and tdc400_expand().
 {
   buffer->w = 0;
   buffer->w_bits = 0;
   buffer->start = (unsigned int *) p;
   buffer->p = buffer->start + 1;
   buffer->num_codes = *(buffer->start);
 }
void start_output_buffer (io_buffer * buffer, unsigned char * p)
Definition at line 14 of file io_buffer.cpp.
References io_buffer::num_codes, io_buffer::p, io_buffer::start, io_buffer::w, and io_buffer::w_bits.
Referenced by caen_compress(), cmp_compress(), fadc_compress(), hits_compress(), n2fadc_ndet_compress(), n2fadc_tpc_compress(), nfadc_compress(), stck_compress(), and tdc400_compress().
 {
   buffer->w = 0;
   buffer->w_bits = 32;
   buffer->start = (unsigned int *) p;
   buffer->p = buffer->start + 1;
   buffer->num_codes = 0;
 }