AlcapDAQ: midas/drivers/device/lrs2415.h File Reference
midas/drivers/device/lrs2415.h File Reference
Functions
INT lrs2415 (INT cmd,...)
Function Documentation
INT lrs2415 (INT cmd, ...)
Definition at line 149 of file lrs2415.c.
References channel, CMD_EXIT, CMD_GET, CMD_GET_ALL, CMD_GET_CURRENT, CMD_INIT, CMD_SET, CMD_SET_ALL, CMD_SET_CURRENT_LIMIT, FE_SUCCESS, hKey, index, lrs2415_exit(), lrs2415_get(), lrs2415_get_current(), lrs2415_init(), lrs2415_set(), lrs2415_set_current_limit(), status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT index, channel, status;
   float value, *pvalue;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      index = va_arg(argptr, INT);
      channel = va_arg(argptr, INT);
      status = lrs2415_init(hKey, index, channel);
      break;
   case CMD_EXIT:
      index = va_arg(argptr, INT);
      status = lrs2415_exit(index);
      break;
   case CMD_SET:
   case CMD_SET_ALL:
      index = va_arg(argptr, INT);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = lrs2415_set(index, channel, value);
      break;
   case CMD_GET:
   case CMD_GET_ALL:
      index = va_arg(argptr, INT);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs2415_get(index, channel, pvalue);
      break;
   case CMD_GET_CURRENT:
      index = va_arg(argptr, INT);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs2415_get_current(index, channel, pvalue);
      break;
   case CMD_SET_CURRENT_LIMIT:
      index = va_arg(argptr, INT);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = lrs2415_set_current_limit(index, channel, value);
      break;
   default:
      break;
   }
   va_end(argptr);
   return status;
}