AlcapDAQ: analyzer/src/caen/MCAENPulseIslandSortAndStitch.cpp File Reference
MCAENPulseIslandSortAndStitch.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <map>
#include <utility>
#include <sstream>
#include <algorithm>
#include <iostream>
#include "midas.h"
#include "TGlobalData.h"
#include "TSetupData.h"
#include "TPulseIsland.h"
Functions
static INT module_event_sort_and_stitch (EVENT_HEADER *pheader, void *pevent)
static INT module_init_sort_and_stitch ()
static bool pulse_islands_t_comp (TPulseIsland *a, TPulseIsland *b)
static void pulse_islands_stitch (std::vector< TPulseIsland * > &v)
Variables
HNDLE hDB
TGlobalData * gData
TSetupData * gSetup
static unsigned int nSamples
static unsigned int nUHSamples
static unsigned int nBUSamples
static unsigned int nUHPreSamples
static unsigned int nBUPreSamples
ANA_MODULE MCAENPulseIslandSortAndStitch_module
Function Documentation
INT module_event_sort_and_stitch (EVENT_HEADER * pheader, void * pevent) static
This method sorts pulses in time and then stitches them together
Definition at line 97 of file MCAENPulseIslandSortAndStitch.cpp.
References TGlobalData::fPulseIslandToChannelMap, TSetupData::IsBostonCAEN(), TSetupData::IsHoustonCAEN(), nBUSamples, nSamples, nUHSamples, pulse_islands_stitch(), pulse_islands_t_comp(), and SUCCESS.
 {
   // Some typedefs
   typedef std::map<std::string, std::vector<TPulseIsland*> > TStringPulseIslandMap;
   // Fetch a reference to the gData structure that stores a map
   // of (bank_name, vector<TPulseIsland*>) pairs
   TStringPulseIslandMap& pulse_islands_map = gData->fPulseIslandToChannelMap;
   for (std::map<std::string, std::vector<TPulseIsland*> >::iterator it=pulse_islands_map.begin(); it!=pulse_islands_map.end(); ++it)
     {
       nSamples = 0;
       if (TSetupData::IsBostonCAEN(it->first))
         nSamples = nBUSamples;
       else if (TSetupData::IsHoustonCAEN(it->first))
         nSamples = nUHSamples;
       if (nSamples != 0) {
         std::vector<TPulseIsland*> &v = it->second;
         std::sort(v.begin(), v.end(), pulse_islands_t_comp);
         pulse_islands_stitch(v);
       }
     }
   return SUCCESS;
 }
INT module_init_sort_and_stitch () static
Definition at line 65 of file MCAENPulseIslandSortAndStitch.cpp.
References hDB, key, nBUPreSamples, nBUSamples, nSamples, nUHPreSamples, nUHSamples, size, sprintf(), and SUCCESS.
{
    /*** Get necessary data from ODB ***/
   char key[80];
   int size;
   unsigned int post_trigger_percentage;
   sprintf(key, "/Equipment/Crate 4/Settings/CAEN0/waveform length");
   size = sizeof(nUHSamples);
   db_get_value(hDB, 0, key, &nUHSamples, &size, TID_DWORD, 1);
   post_trigger_percentage = 80; // This is hardcoded in the frontend
   nUHPreSamples = (int) (0.01 * ((100 - post_trigger_percentage) * nUHSamples));
   return SUCCESS;
   sprintf(key, "/Equipment/Crate 5/Settings/CAEN/waveform length");
   size = sizeof(nBUSamples);
   db_get_value(hDB, 0, key, &nSamples, &size, TID_DWORD, 1);
   sprintf(key, "/Equipment/Crate 5/Settings/CAEN/post_trigger_size");
   size = sizeof(post_trigger_percentage);
   db_get_value(hDB, 0, key, &post_trigger_percentage, &size, TID_BYTE, 1);
   //nBUPreSamples = (int) (0.01 * ((100 - post_trigger_percentage) * nBUSamples));
   nBUPreSamples = 20; // From the Golden Data, it looks like there are 20 presamples.
                     // The frontend does not seem to correctly load post_trigger_size
                     // onto the CAEN.
   return SUCCESS;
 }
void pulse_islands_stitch (std::vector< TPulseIsland * > & pulses) static
Stitch islands together
Definition at line 135 of file MCAENPulseIslandSortAndStitch.cpp.
References TPulseIsland::GetBankName(), TPulseIsland::GetTimeStamp(), i, and nSamples.
Referenced by module_event_sort_and_stitch().
{
   unsigned int nPulses = pulses.size();
   std::vector<int> next_samples, current_samples;
   TPulseIsland* temp_pulse;
   for (unsigned int iPulse = 0; iPulse < nPulses - 1; ++iPulse) {
     next_samples = pulses[iPulse + 1]->GetSamples();
     // If the next pulse is less than the set number of samples,
     // it's a continuation of this pulse
     while (next_samples.size() < nSamples) {
       current_samples = pulses[iPulse]->GetSamples();
       for (unsigned int i = 0; i < next_samples.size(); ++i)
         current_samples.push_back(next_samples[i]);
       temp_pulse = pulses[iPulse];
       pulses[iPulse] = new TPulseIsland(temp_pulse->GetTimeStamp(), current_samples, temp_pulse->GetBankName());
       delete temp_pulse;
       delete pulses[iPulse + 1];
       pulses.erase(pulses.begin() + iPulse + 1);
       if (!(iPulse < --nPulses - 1)) break;
       next_samples = pulses[iPulse + 1]->GetSamples();
     }
   }
 }
bool pulse_islands_t_comp (TPulseIsland * a, TPulseIsland * b) static
Ordering of pulse islands in time
Definition at line 127 of file MCAENPulseIslandSortAndStitch.cpp.
References TPulseIsland::GetTimeStamp().
Referenced by module_event_sort_and_stitch().
 {
   return (a->GetTimeStamp() < b->GetTimeStamp());
 }
Variable Documentation
TGlobalData* gData
Definition at line 54 of file analyzer.cpp.
Referenced by analyzer_exit(), and ExportPulse::ProcessEntry().
TSetupData* gSetup
Definition at line 55 of file analyzer.cpp.
Referenced by analyzer_exit(), and MaxBinCFAPGenerator::ProcessPulses().
HNDLE hDB
Definition at line 11 of file mucap_compress.cpp.
ANA_MODULE MCAENPulseIslandSortAndStitch_module
Initial value:
=
{
        "MCAENPulseIslandSortAndStitch",
        "Vladimir Tishchenko",
        module_event_sort_and_stitch,
        NULL,
        NULL,
        module_init_sort_and_stitch,
        NULL,
        NULL,
        0,
        NULL,
}
Definition at line 47 of file MCAENPulseIslandSortAndStitch.cpp.
unsigned int nBUPreSamples static
Definition at line 45 of file MCAENPulseIslandSortAndStitch.cpp.
Referenced by module_init_sort_and_stitch().
unsigned int nBUSamples static
Definition at line 43 of file MCAENPulseIslandSortAndStitch.cpp.
Referenced by module_event_sort_and_stitch(), and module_init_sort_and_stitch().
unsigned int nSamples static
Definition at line 41 of file MCAENPulseIslandSortAndStitch.cpp.
Referenced by module_event_sort_and_stitch(), module_init_sort_and_stitch(), TOctalFADCBankReader::ProcessEvent(), and pulse_islands_stitch().
unsigned int nUHPreSamples static
Definition at line 44 of file MCAENPulseIslandSortAndStitch.cpp.
Referenced by module_init_sort_and_stitch().
unsigned int nUHSamples static
Definition at line 42 of file MCAENPulseIslandSortAndStitch.cpp.
Referenced by module_event_sort_and_stitch(), and module_init_sort_and_stitch().