AlcapDAQ: midas/gui/hvedit/windows/MExperiment.cpp File Reference
midas/gui/hvedit/windows/MExperiment.cpp File Reference
#include "stdafx.h"
#include "hvedit.h"
#include "midas.h"
#include "MHostDlg.h"
#include "MExperiment.h"
#include "MPasswddlg.h"
Functions
int MidasMessage (const char *str)
void CALLBACK EXPORT TimerProc (HWND hWnd, UINT nMsg, UINT nIDEvent, DWORD dwTime)
void GetPassword (char *password)
Function Documentation
void GetPassword (char * password)
Definition at line 56 of file MExperiment.cpp.
References CMPasswdDlg::m_strPassword.
Referenced by CMExperiment::Connect().
{
CMPasswdDlg passwddlg;
  if (passwddlg.DoModal() == IDCANCEL)
    {
    password[0] = 0;
    return;
    }
  strcpy(password, passwddlg.m_strPassword);
  return;
}
int MidasMessage (const char * str)
Definition at line 20 of file MExperiment.cpp.
References cm_get_client_info(), and name.
Referenced by CMExperiment::Connect(), and CMExperiment::StartTimer().
{
char name[80];
  cm_get_client_info(name);
  MessageBox(GetFocus(), str, name, MB_OK);
  return 0;
}
void CALLBACK EXPORT TimerProc (HWND hWnd, UINT nMsg, UINT nIDEvent, DWORD dwTime)
Definition at line 32 of file MExperiment.cpp.
References cm_yield(), RPC_SHUTDOWN, SS_ABORT, and status.
Referenced by CMExperiment::StartTimer().
{
int   status;
CWnd* pWnd;
  pWnd = AfxGetMainWnd();
  pWnd->KillTimer(1175);
  status = cm_yield(0);
  if (status == SS_ABORT || status == RPC_SHUTDOWN)
    {
    pWnd->PostMessage(WM_CLOSE, 0, 0);
    return;
    }
  if (!pWnd->SetTimer(1175, 100, TimerProc))
    pWnd->MessageBox("Cannot set timer");
}