AlcapDAQ: midas/examples/experiment/frontend.c File Reference
midas/examples/experiment/frontend.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "midas.h"
#include "mcstd.h"
#include "experim.h"
Defines
#define N_ADC 4
#define N_TDC 4
#define N_SCLR 4
#define CRATE 0
#define SLOT_IO 23
#define SLOT_ADC 1
#define SLOT_TDC 2
#define SLOT_SCLR 3
Functions
INT frontend_init ()
INT frontend_exit ()
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
INT frontend_loop ()
INT read_trigger_event (char *pevent, INT off)
INT read_scaler_event (char *pevent, INT off)
INT poll_event (INT source, INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Variables
char * frontend_name = "Sample Frontend"
char * frontend_file_name = __FILE__
BOOL frontend_call_loop = FALSE
INT display_period = 3000
INT max_event_size = 10000
INT max_event_size_frag = 5 * 1024 * 1024
INT event_buffer_size = 10 * 10000
EQUIPMENT equipment []
Define Documentation
#define CRATE 0
Definition at line 123 of file frontend.c.
#define N_ADC 4
Definition at line 118 of file frontend.c.
#define N_SCLR 4
Definition at line 120 of file frontend.c.
#define N_TDC 4
Definition at line 119 of file frontend.c.
#define SLOT_ADC 1
Definition at line 125 of file frontend.c.
#define SLOT_IO 23
Definition at line 124 of file frontend.c.
#define SLOT_SCLR 3
Definition at line 127 of file frontend.c.
#define SLOT_TDC 2
Definition at line 126 of file frontend.c.
Function Documentation
INT begin_of_run (INT run_number, char * error)
Definition at line 252 of file frontend.c.
References SUCCESS.
{
   /* put here clear scalers etc. */
   return SUCCESS;
}
INT end_of_run (INT run_number, char * error)
Definition at line 261 of file frontend.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_exit (void)
Definition at line 245 of file frontend.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_init (void)
Definition at line 220 of file frontend.c.
References cam_crate_clear(), cam_crate_zinit(), cam_init(), cam_lam_enable(), camc(), camo(), CRATE, SLOT_IO, and SUCCESS.
{
   /* hardware initialization */
   cam_init();
   cam_crate_clear(CRATE);
   cam_crate_zinit(CRATE);
   /* enable LAM in IO unit */
   camc(CRATE, SLOT_IO, 0, 26);
   /* enable LAM in crate controller */
   cam_lam_enable(CRATE, SLOT_IO);
   /* reset external LAM Flip-Flop */
   camo(CRATE, SLOT_IO, 1, 16, 0xFF);
   camo(CRATE, SLOT_IO, 1, 16, 0);
   /* print message and return FE_ERR_HW if frontend should not be started */
   return SUCCESS;
}
INT frontend_loop (void)
Definition at line 282 of file frontend.c.
References SUCCESS.
{
   /* if frontend_call_loop is true, this routine gets called when
      the frontend is idle or once between every event */
   return SUCCESS;
}
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Definition at line 320 of file frontend.c.
References CMD_INTERRUPT_ATTACH, CMD_INTERRUPT_DETACH, CMD_INTERRUPT_DISABLE, CMD_INTERRUPT_ENABLE, and SUCCESS.
{
   switch (cmd) {
   case CMD_INTERRUPT_ENABLE:
      break;
   case CMD_INTERRUPT_DISABLE:
      break;
   case CMD_INTERRUPT_ATTACH:
      break;
   case CMD_INTERRUPT_DETACH:
      break;
   }
   return SUCCESS;
}
INT pause_run (INT run_number, char * error)
Definition at line 268 of file frontend.c.
References SUCCESS.
{
   return SUCCESS;
}
INT poll_event (INT source, INT count, BOOL test)
Definition at line 299 of file frontend.c.
References cam_lam_read(), i, LAM_SOURCE_CRATE, and LAM_SOURCE_STATION.
{
   int i;
   DWORD lam;
   for (i = 0; i < count; i++) {
      cam_lam_read(LAM_SOURCE_CRATE(source), &lam);
      if (lam & LAM_SOURCE_STATION(source))
         if (!test)
            return lam;
   }
   return 0;
}
INT read_scaler_event (char * pevent, INT off)
Definition at line 407 of file frontend.c.
References bk_close(), bk_create(), bk_init(), bk_size(), cam24i(), CRATE, N_SCLR, SLOT_SCLR, and TID_DWORD.
{
   DWORD *pdata, a;
   /* init bank structure */
   bk_init(pevent);
   /* create SCLR bank */
   bk_create(pevent, "SCLR", TID_DWORD, &pdata);
   /* read scaler bank */
   for (a = 0; a < N_SCLR; a++)
      cam24i(CRATE, SLOT_SCLR, a, 0, pdata++);
   bk_close(pevent, pdata);
   return bk_size(pevent);
}
INT read_trigger_event (char * pevent, INT off)
Definition at line 337 of file frontend.c.
References bk_close(), bk_create(), bk_init(), bk_size(), cam_lam_clear(), camc(), camc_q(), camo(), CRATE, N_ADC, N_TDC, SLOT_ADC, SLOT_IO, SLOT_TDC, ss_printf(), ss_sleep(), TID_WORD, and timeout.
{
   WORD *pdata, a;
   INT q, timeout;
   /* init bank structure */
   bk_init(pevent);
   /* create structured ADC0 bank */
   bk_create(pevent, "ADC0", TID_WORD, &pdata);
   /* wait for ADC conversion */
   for (timeout = 100; timeout > 0; timeout--) {
      camc_q(CRATE, SLOT_ADC, 0, 8, &q);
      if (q)
         break;
   }
   if (timeout == 0)
      ss_printf(0, 10, "No ADC gate!");
   /* use following code to read out real CAMAC ADC */
   /*
      for (a=0 ; a<N_ADC ; a++)
      cami(CRATE, SLOT_ADC, a, 0, pdata++);
    */
   /* Use following code to "simulate" data */
   for (a = 0; a < N_ADC; a++)
      *pdata++ = rand() % 1024;
   /* clear ADC */
   camc(CRATE, SLOT_ADC, 0, 9);
   bk_close(pevent, pdata);
   /* create variable length TDC bank */
   bk_create(pevent, "TDC0", TID_WORD, &pdata);
   /* use following code to read out real CAMAC TDC */
   /*
      for (a=0 ; a<N_TDC ; a++)
      cami(CRATE, SLOT_TDC, a, 0, pdata++);
    */
   /* Use following code to "simulate" data */
   for (a = 0; a < N_TDC; a++)
      *pdata++ = rand() % 1024;
   /* clear TDC */
   camc(CRATE, SLOT_TDC, 0, 9);
   bk_close(pevent, pdata);
   /* clear IO unit LAM */
   camc(CRATE, SLOT_IO, 0, 10);
   /* clear LAM in crate controller */
   cam_lam_clear(CRATE, SLOT_IO);
   /* reset external LAM Flip-Flop */
   camo(CRATE, SLOT_IO, 1, 16, 0xFF);
   camo(CRATE, SLOT_IO, 1, 16, 0);
   ss_sleep(10);
   return bk_size(pevent);
}
INT resume_run (INT run_number, char * error)
Definition at line 275 of file frontend.c.
References SUCCESS.
{
   return SUCCESS;
}
Variable Documentation
INT display_period = 3000
Definition at line 106 of file frontend.c.
EQUIPMENT equipment[]
Definition at line 146 of file frontend.c.
INT event_buffer_size = 10 * 10000
Definition at line 115 of file frontend.c.
BOOL frontend_call_loop = FALSE
Definition at line 103 of file frontend.c.
char* frontend_file_name = __FILE__
Definition at line 100 of file frontend.c.
char* frontend_name = "Sample Frontend"
Definition at line 98 of file frontend.c.
INT max_event_size = 10000
Definition at line 109 of file frontend.c.
INT max_event_size_frag = 5 * 1024 * 1024
Definition at line 112 of file frontend.c.