AlcapDAQ: midas/examples/basic/minife.c File Reference
midas/examples/basic/minife.c File Reference
#include "midas.h"
#include "msystem.h"
#include <stdio.h>
Functions
INT tr_start (INT rn, char *error)
INT tr_stop (INT rn, char *error)
main ()
Variables
INT running
INT serial = 0
INT run_number = 0
HNDLE hBuf
Function Documentation
main (void)
Definition at line 65 of file minife.c.
References ASYNC, BM_ASYNC_RETURN, bm_compose_event(), bm_open_buffer(), bm_set_cache_size(), BM_SUCCESS, cm_connect_experiment(), cm_disconnect_experiment(), cm_register_transition(), cm_set_watchdog_params(), CM_SUCCESS, cm_yield(), EVENT_BUFFER_NAME, EVENT_BUFFER_SIZE, FALSE, hBuf, host_name, last_time, rpc_convert_single(), rpc_get_convert_flags(), RPC_OUTGOING, rpc_send_event(), RPC_SHUTDOWN, run_number, running, serial, size, SS_ABORT, ss_gets(), ss_millitime(), status, TID_DWORD, tr_start(), TR_START, tr_stop, TR_STOP, and TRUE.
{
   INT status, size, *pdata, id;
   INT convert_flags;
   DWORD last_time = 0;
   char event[2000];
   char host_name[256];
   char dash[] = "-/|\\";
   BOOL blocked = FALSE;
#ifdef OS_VXWORKS
   strcpy(host_name, ahost_name);
#else
   printf("Host to connect: ");
   ss_gets(host_name, 256);
#endif
   /* now connect to server */
   status = cm_connect_experiment(host_name, "", "MiniFE", NULL);
   if (status != CM_SUCCESS)
      return 1;
   if (cm_register_transition(TR_START, tr_start) != CM_SUCCESS ||
       cm_register_transition(TR_STOP, tr_stop) != CM_SUCCESS) {
      printf("Cannot start server");
      return 0;
   }
#ifdef _DEBUG
   cm_set_watchdog_params(TRUE, 0);
#endif
   /* open the "system" buffer, 1M size */
   bm_open_buffer(EVENT_BUFFER_NAME, EVENT_BUFFER_SIZE, &hBuf);
   /* set the buffer cache size on the server */
   bm_set_cache_size(hBuf, 0, 100000);
   pdata = (INT *) (event + sizeof(EVENT_HEADER));
   size = 1000;
   /* compose an event */
   bm_compose_event((EVENT_HEADER *) event, 1, 1, size, serial);
   pdata[0] = size;             /* simulate data for consume.exe */
   pdata[size / 4 - 1] = size;
   /* convert test data if necessary to format on server */
   rpc_get_convert_flags(&convert_flags);
   if (convert_flags) {
      rpc_convert_single(&pdata[0], TID_DWORD, RPC_OUTGOING, convert_flags);
      rpc_convert_single(&pdata[size / 4 - 1], TID_DWORD, RPC_OUTGOING, convert_flags);
   }
   do {
      if (!running) {
         /* if run is not started, call yield with a timeout of 1s */
         status = cm_yield(1000);
         if (status == RPC_SHUTDOWN || status == SS_ABORT)
            break;
      } else {
         /* if run is started, call yield with a timeout of 0 once each second.
            This minimizes the calls to select() inside rpc_server_yield and
            increases the network speed */
         if (ss_millitime() - last_time > 300) {
            printf("%c\r", dash[id++ % 4]);
            fflush(stdout);
            status = cm_yield(0);
            if (status == RPC_SHUTDOWN || status == SS_ABORT)
               break;
            last_time = ss_millitime();
         }
      }
      /* if run is started, send event */
      if (running) {
         /* only compose new event if not blocked by previous send */
         if (!blocked) {
            /* increment serial number */
            ((EVENT_HEADER *) event)->serial_number = serial++;
         }
         status = rpc_send_event(hBuf, event, size + sizeof(EVENT_HEADER), ASYNC);
         if (status == BM_ASYNC_RETURN)
            blocked = TRUE;
         else if (status == BM_SUCCESS)
            blocked = FALSE;
         else if (status != BM_SUCCESS) {
            printf("Error sending event");
            goto error;
         }
      }
   } while (run_number < 1000);
   cm_disconnect_experiment();
 error:
   return 1;
}
INT tr_start (INT rn, char * error)
Definition at line 35 of file minife.c.
References CM_SUCCESS, run_number, running, serial, and TRUE.
{
   printf("Start run %d\n", rn);
   serial = 0;
   run_number = rn;
   running = TRUE;
   return CM_SUCCESS;
}
INT tr_stop (INT rn, char * error)
Definition at line 46 of file minife.c.
References bm_flush_cache(), CM_SUCCESS, FALSE, hBuf, rpc_flush_event(), running, and SYNC.
{
   printf("Stop run %d -", rn);
   running = FALSE;
   rpc_flush_event();           /* send events in TCP cache */
   bm_flush_cache(hBuf, SYNC);  /* flush buffer cache */
   printf(" done\n");
   return CM_SUCCESS;
}
Variable Documentation
HNDLE hBuf
Definition at line 33 of file minife.c.
Referenced by command_loop(), handFlush(), main(), source_booking(), source_scan(), source_unbooking(), and tr_stop().
INT run_number = 0
Definition at line 31 of file minife.c.
INT running
Definition at line 29 of file minife.c.
Referenced by main(), tr_start(), and tr_stop().
INT serial = 0
Definition at line 30 of file minife.c.
Referenced by eb_user(), main(), source_booking(), source_scan(), and tr_start().