AlcapDAQ: midas/examples/basic/miniana.c File Reference
midas/examples/basic/miniana.c File Reference
#include <stdio.h>
#include "midas.h"
Functions
void process_event (HNDLE hBuf, HNDLE request_id, EVENT_HEADER *pheader, void *pevent)
main ()
Function Documentation
main (void)
Definition at line 31 of file miniana.c.
References bm_open_buffer(), bm_request_event(), cm_connect_experiment(), cm_disconnect_experiment(), CM_SUCCESS, cm_yield(), EVENT_BUFFER_SIZE, GET_ALL, hBufEvent, process_event(), RPC_SHUTDOWN, SS_ABORT, status, and TRIGGER_ALL.
{
   INT status, request_id;
   HNDLE hBufEvent;
   status = cm_connect_experiment("", "sample", "Simple Analyzer", NULL);
   if (status != CM_SUCCESS)
      return 1;
   bm_open_buffer("SYSTEM", EVENT_BUFFER_SIZE, &hBufEvent);
   bm_request_event(hBufEvent, 1, TRIGGER_ALL, GET_ALL, &request_id, process_event);
   do {
      status = cm_yield(1000);
   } while (status != RPC_SHUTDOWN && status != SS_ABORT);
   cm_disconnect_experiment();
   return 0;
}
void process_event (HNDLE hBuf, HNDLE request_id, EVENT_HEADER * pheader, void * pevent)
Definition at line 26 of file miniana.c.
References EVENT_HEADER::serial_number.
Referenced by analyze_run(), main(), process_file(), receive_event(), scheduler(), and send_event().
{
   printf("Received event #%d\r", pheader->serial_number);
}