AlcapDAQ: analyzer/src/muSC_muPC/MMuPC1AnalysisMQL.cpp File Reference
MMuPC1AnalysisMQL.cpp File Reference
#include <midas.h>
#include "MqlArray.h"
#include "MqlNtupleColumn.h"
#include "Mql.h"
#include <stdio.h>
#include <stdlib.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TNtuple.h>
#include <common.h>
#include <ucb_common.h>
#include "HITS.h"
Data Structures
struct _u_MMuPC1AnalysisMQL_1
struct _u_MMuPC1AnalysisMQL_2
struct _u_MMuPC1AnalysisMQL_3
struct _u_MMuPC1AnalysisMQL_4
struct _u_MMuPC1AnalysisMQL_5
struct _u_MMuPC1AnalysisMQL_6
struct _u_MMuPC1AnalysisMQL_7
struct _u_MMuPC1AnalysisMQL_8
struct _u_MMuPC1AnalysisMQL_9
struct _u_MMuPC1AnalysisMQL_10
struct _u_MMuPC1AnalysisMQL_11
struct _u_MMuPC1AnalysisMQL_12
struct _u_MMuPC1AnalysisMQL_13
struct _u_MMuPC1AnalysisMQL_14
struct _u_MMuPC1AnalysisMQL_15
struct _u_MMuPC1AnalysisMQL_16
struct _u_MMuPC1AnalysisMQL_17
struct _u_MMuPC1AnalysisMQL_18
struct _u_MMuPC1AnalysisMQL_19
struct _u_MMuPC1AnalysisMQL_20
struct _u_MMuPC1AnalysisMQL_21
struct _u_MMuPC1AnalysisMQL_22
struct _u_MMuPC1AnalysisMQL_23
struct _u_MMuPC1AnalysisMQL_24
struct _u_MMuPC1AnalysisMQL_25
struct _u_MMuPC1AnalysisMQL_26
struct _u_MMuPC1AnalysisMQL_27
struct _u_MMuPC1AnalysisMQL_28
struct _u_MMuPC1AnalysisMQL_29
struct _u_MMuPC1AnalysisMQL_30
struct _u_MMuPC1AnalysisMQL_31
struct _u_MMuPC1AnalysisMQL_32
struct _u_MMuPC1AnalysisMQL_33
struct _u_MMuPC1AnalysisMQL_34
struct _u_MMuPC1AnalysisMQL_35
struct _u_MMuPC1AnalysisMQL_36
struct _u_MMuPC1AnalysisMQL_37
struct _u_MMuPC1AnalysisMQL_38
Macros
#define Tier1 ON
#define Tier2 OFF
#define Tier3 OFF
Functions
INT MMuPC1AnalysisMQL_init ()
INT MMuPC1AnalysisMQL (EVENT_HEADER *, void *)
static int _u_MMuPC1AnalysisMQL_39 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_40 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_41 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_42 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_43 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_44 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_45 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_46 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_47 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_48 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_49 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_50 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_51 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_52 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_53 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_54 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_55 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_56 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_57 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_58 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_59 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_60 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_61 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_62 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_63 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_64 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_65 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_66 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_67 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_68 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_69 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_70 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_71 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_72 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_73 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_74 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_75 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_76 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_77 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_78 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_79 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_80 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_81 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_82 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_83 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_84 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_85 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_86 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_87 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_88 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_89 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_90 (const void *_v1, const void *_v2)
static int _u_MMuPC1AnalysisMQL_91 (const void *_v1, const void *_v2)
Variables
ANA_MODULE MMuPC1AnalysisMQL_module
static MqlArray< struct
_u_MMuPC1AnalysisMQL_1 > _t_hits
static MqlArray< struct
_u_MMuPC1AnalysisMQL_2 > _t_muPC1_hits
static TH1D * _h_parameters_muPC1
static MqlArray< struct
_u_MMuPC1AnalysisMQL_3 > _t_muPC1X_raw
static MqlArray< struct
_u_MMuPC1AnalysisMQL_4 > _t_muPC1X_raw_auto
static TH2D * _h_muPC1_X_raw_autosingles_2D
static TH1D * _h_muPC1_X_raw_autocorr_all_1D
static TH2D * _h_muPC1_X_raw_autocorr_2D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_5 > _t_muPC1X_spark_search
static TH1D * _h_muPC1_spark_search_Xwires
static MqlArray< struct
_u_MMuPC1AnalysisMQL_6 > _t_muPC1X_sparks
static TH1D * _h_muPC1_spark_count_Xwires
static MqlArray< struct
_u_MMuPC1AnalysisMQL_7 > _t_muPC1X_SC
static MqlArray< struct
_u_MMuPC1AnalysisMQL_8 > _t_muPC1X_SC_auto
static TH1D * _h_muPC1_X_SC_autocorr_all_1D
static TH2D * _h_muPC1_X_SC_autocorr_2D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_9 > _t_muPC1X_AD
static MqlArray< struct
_u_MMuPC1AnalysisMQL_10 > _t_muPC1X_AD_auto
static TH1D * _h_muPC1_X_AD_autocorr_all_1D
static TH2D * _h_muPC1_X_AD_autocorr_2D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_11 > _t_muPC1X_cluster_contiguous
static MqlArray< struct
_u_MMuPC1AnalysisMQL_12 > _t_muPC1X_cluster_contiguous_sep
static TH1D * _h_muPC1_X_cluster_contiguous_separation
static MqlArray< struct
_u_MMuPC1AnalysisMQL_13 > _t_muPC1X
static TH1D * _h_muPC1_X_final_cluster_size
static TH1D * _h_muPC1_X_final_cluster_width
static TH1D * _h_muPC1_X_final_cluster_avg
static MqlArray< struct
_u_MMuPC1AnalysisMQL_14 > _t_muPC1X_export
static MqlArray< struct
_u_MMuPC1AnalysisMQL_15 > _t_muPC1X_auto
static TH1D * _h_muPC1_X_final_cluster_autocorr_all_1D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_16 > _t_muPC1X_spatial_auto
static TH1D * _h_muPC1_X_final_cluster_autocorr_spatial_all_1D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_17 > _t_muPC1Y_raw
static MqlArray< struct
_u_MMuPC1AnalysisMQL_18 > _t_muPC1Y_raw_auto
static TH2D * _h_muPC1_Y_raw_autosingles_2D
static TH1D * _h_muPC1_Y_raw_autocorr_all_1D
static TH2D * _h_muPC1_Y_raw_autocorr_2D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_19 > _t_muPC1Y_spark_search
static TH1D * _h_muPC1_spark_search_Ywires
static MqlArray< struct
_u_MMuPC1AnalysisMQL_20 > _t_muPC1Y_sparks
static TH1D * _h_muPC1_spark_count_Ywires
static MqlArray< struct
_u_MMuPC1AnalysisMQL_21 > _t_muPC1Y_SC
static MqlArray< struct
_u_MMuPC1AnalysisMQL_22 > _t_muPC1Y_SC_auto
static TH1D * _h_muPC1_Y_SC_autocorr_all_1D
static TH2D * _h_muPC1_Y_SC_autocorr_2D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_23 > _t_muPC1Y_AD
static MqlArray< struct
_u_MMuPC1AnalysisMQL_24 > _t_muPC1Y_AD_auto
static TH1D * _h_muPC1_Y_AD_autocorr_all_1D
static TH2D * _h_muPC1_Y_AD_autocorr_2D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_25 > _t_muPC1Y_cluster_contiguous
static MqlArray< struct
_u_MMuPC1AnalysisMQL_26 > _t_muPC1Y_cluster_contiguous_sep
static TH1D * _h_muPC1_Y_cluster_contiguous_separation
static MqlArray< struct
_u_MMuPC1AnalysisMQL_27 > _t_muPC1Y
static TH1D * _h_muPC1_Y_final_cluster_size
static TH1D * _h_muPC1_Y_final_cluster_width
static TH1D * _h_muPC1_Y_final_cluster_avg
static MqlArray< struct
_u_MMuPC1AnalysisMQL_28 > _t_muPC1Y_export
static MqlArray< struct
_u_MMuPC1AnalysisMQL_29 > _t_muPC1Y_temporal_auto
static TH1D * _h_muPC1_Y_final_cluster_autocorr_all_1D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_30 > _t_muPC1Y_spatial_auto
static TH1D * _h_muPC1_Y_final_cluster_autocorr_spatial_all_1D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_31 > _t_muPC1XY
static TH1D * _h_muPC1_coinc_XY_tdiff
static MqlArray< struct
_u_MMuPC1AnalysisMQL_32 > _t_muPC1
static TH2D * _h_muPC1_coinc_XY_2D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_33 > _t_muPC1_auto
static TH1D * _h_muPC1_coinc_XY_autocorr_all_1D
static MqlArray< struct
_u_MMuPC1AnalysisMQL_34 > _t_muSC
static MqlArray< struct
_u_MMuPC1AnalysisMQL_35 > _t_muSC_muPC1
static TH1D * _h_muSC_muPC1_time_difference
static TH2D * _h_muPC1_coinc_XY_2D_with_muSC
static MqlArray< struct
_u_MMuPC1AnalysisMQL_36 > _t_muPC1_sparks_union
static MqlArray< struct
_u_MMuPC1AnalysisMQL_37 > _t_muPC1_sparks_clustered
static TH1D * _h_muPC1_spark_clustered_blocktime
static MqlArray< struct
_u_MMuPC1AnalysisMQL_38 > _t_muPC1_sparks_chamberwide
static TH1D * _h_muPC1_spark_chamberwide_count
static TH1D * _h_muPC1_spark_chamberwide_blocktime
Macro Definition Documentation
#define Tier1 ON
Definition at line 38 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
#define Tier2 OFF
Definition at line 39 of file MMuPC1AnalysisMQL.cpp.
#define Tier3 OFF
Definition at line 40 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
Function Documentation
static int _u_MMuPC1AnalysisMQL_39 (const void * _v1, const void * _v2) static
Definition at line 71 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_3::time, and _u_MMuPC1AnalysisMQL_3::Xwire.
 {
   struct _u_MMuPC1AnalysisMQL_3 *_o1 = (struct _u_MMuPC1AnalysisMQL_3 *) _v1;
   struct _u_MMuPC1AnalysisMQL_3 *_o2 = (struct _u_MMuPC1AnalysisMQL_3 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_40 (const void * _v1, const void * _v2) static
Definition at line 92 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_3::time, and _u_MMuPC1AnalysisMQL_3::Xwire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_3 *_o1 = (struct _u_MMuPC1AnalysisMQL_3 *) _v1;
   struct _u_MMuPC1AnalysisMQL_3 *_o2 = (struct _u_MMuPC1AnalysisMQL_3 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_41 (const void * _v1, const void * _v2) static
Definition at line 123 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_3::time, and _u_MMuPC1AnalysisMQL_3::Xwire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_3 *_o1 = (struct _u_MMuPC1AnalysisMQL_3 *) _v1;
   struct _u_MMuPC1AnalysisMQL_3 *_o2 = (struct _u_MMuPC1AnalysisMQL_3 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_42 (const void * _v1, const void * _v2) static
Definition at line 144 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_5::cluster_size, time, and _u_MMuPC1AnalysisMQL_5::time.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_5 *_o1 = (struct _u_MMuPC1AnalysisMQL_5 *) _v1;
   struct _u_MMuPC1AnalysisMQL_5 *_o2 = (struct _u_MMuPC1AnalysisMQL_5 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int cluster_size = _o1->cluster_size;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int cluster_size = _o2->cluster_size;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_43 (const void * _v1, const void * _v2) static
Definition at line 180 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_3::time, and _u_MMuPC1AnalysisMQL_3::Xwire.
 {
   struct _u_MMuPC1AnalysisMQL_3 *_o1 = (struct _u_MMuPC1AnalysisMQL_3 *) _v1;
   struct _u_MMuPC1AnalysisMQL_3 *_o2 = (struct _u_MMuPC1AnalysisMQL_3 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_44 (const void * _v1, const void * _v2) static
Definition at line 201 of file MMuPC1AnalysisMQL.cpp.
References time, and _u_MMuPC1AnalysisMQL_6::time.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_6 *_o1 = (struct _u_MMuPC1AnalysisMQL_6 *) _v1;
   struct _u_MMuPC1AnalysisMQL_6 *_o2 = (struct _u_MMuPC1AnalysisMQL_6 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_45 (const void * _v1, const void * _v2) static
Definition at line 229 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_7::time, and _u_MMuPC1AnalysisMQL_7::Xwire.
 {
   struct _u_MMuPC1AnalysisMQL_7 *_o1 = (struct _u_MMuPC1AnalysisMQL_7 *) _v1;
   struct _u_MMuPC1AnalysisMQL_7 *_o2 = (struct _u_MMuPC1AnalysisMQL_7 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_46 (const void * _v1, const void * _v2) static
Definition at line 250 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_7::time, and _u_MMuPC1AnalysisMQL_7::Xwire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_7 *_o1 = (struct _u_MMuPC1AnalysisMQL_7 *) _v1;
   struct _u_MMuPC1AnalysisMQL_7 *_o2 = (struct _u_MMuPC1AnalysisMQL_7 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_47 (const void * _v1, const void * _v2) static
Definition at line 280 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_7::time, and _u_MMuPC1AnalysisMQL_7::Xwire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_7 *_o1 = (struct _u_MMuPC1AnalysisMQL_7 *) _v1;
   struct _u_MMuPC1AnalysisMQL_7 *_o2 = (struct _u_MMuPC1AnalysisMQL_7 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_48 (const void * _v1, const void * _v2) static
Definition at line 301 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_9::time, and _u_MMuPC1AnalysisMQL_9::Xwire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_9 *_o1 = (struct _u_MMuPC1AnalysisMQL_9 *) _v1;
   struct _u_MMuPC1AnalysisMQL_9 *_o2 = (struct _u_MMuPC1AnalysisMQL_9 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_49 (const void * _v1, const void * _v2) static
Definition at line 331 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_9::time, and _u_MMuPC1AnalysisMQL_9::Xwire.
 {
   struct _u_MMuPC1AnalysisMQL_9 *_o1 = (struct _u_MMuPC1AnalysisMQL_9 *) _v1;
   struct _u_MMuPC1AnalysisMQL_9 *_o2 = (struct _u_MMuPC1AnalysisMQL_9 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_50 (const void * _v1, const void * _v2) static
Definition at line 352 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_9::time, and _u_MMuPC1AnalysisMQL_9::Xwire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_9 *_o1 = (struct _u_MMuPC1AnalysisMQL_9 *) _v1;
   struct _u_MMuPC1AnalysisMQL_9 *_o2 = (struct _u_MMuPC1AnalysisMQL_9 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_51 (const void * _v1, const void * _v2) static
Definition at line 383 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_9::time, and _u_MMuPC1AnalysisMQL_9::Xwire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_9 *_o1 = (struct _u_MMuPC1AnalysisMQL_9 *) _v1;
   struct _u_MMuPC1AnalysisMQL_9 *_o2 = (struct _u_MMuPC1AnalysisMQL_9 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_52 (const void * _v1, const void * _v2) static
Definition at line 404 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_11::time, _u_MMuPC1AnalysisMQL_11::Xwire_max, and _u_MMuPC1AnalysisMQL_11::Xwire_min.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_11 *_o1 = (struct _u_MMuPC1AnalysisMQL_11 *) _v1;
   struct _u_MMuPC1AnalysisMQL_11 *_o2 = (struct _u_MMuPC1AnalysisMQL_11 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire_min = _o1->Xwire_min;
     int Xwire_max = _o1->Xwire_max;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire_min = _o2->Xwire_min;
     int Xwire_max = _o2->Xwire_max;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_53 (const void * _v1, const void * _v2) static
Definition at line 433 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_11::time, _u_MMuPC1AnalysisMQL_11::Xwire_max, and _u_MMuPC1AnalysisMQL_11::Xwire_min.
 {
   struct _u_MMuPC1AnalysisMQL_11 *_o1 = (struct _u_MMuPC1AnalysisMQL_11 *) _v1;
   struct _u_MMuPC1AnalysisMQL_11 *_o2 = (struct _u_MMuPC1AnalysisMQL_11 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire_min = _o1->Xwire_min;
     int Xwire_max = _o1->Xwire_max;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire_min = _o2->Xwire_min;
     int Xwire_max = _o2->Xwire_max;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_54 (const void * _v1, const void * _v2) static
Definition at line 456 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_11::time, _u_MMuPC1AnalysisMQL_11::Xwire_max, and _u_MMuPC1AnalysisMQL_11::Xwire_min.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_11 *_o1 = (struct _u_MMuPC1AnalysisMQL_11 *) _v1;
   struct _u_MMuPC1AnalysisMQL_11 *_o2 = (struct _u_MMuPC1AnalysisMQL_11 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire_min = _o1->Xwire_min;
     int Xwire_max = _o1->Xwire_max;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire_min = _o2->Xwire_min;
     int Xwire_max = _o2->Xwire_max;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_55 (const void * _v1, const void * _v2) static
Definition at line 489 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_9::time, and _u_MMuPC1AnalysisMQL_9::Xwire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_9 *_o1 = (struct _u_MMuPC1AnalysisMQL_9 *) _v1;
   struct _u_MMuPC1AnalysisMQL_9 *_o2 = (struct _u_MMuPC1AnalysisMQL_9 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Xwire = _o1->Xwire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Xwire = _o2->Xwire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_56 (const void * _v1, const void * _v2) static
Definition at line 510 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_13::cluster_size, _u_MMuPC1AnalysisMQL_13::cluster_width, time, _u_MMuPC1AnalysisMQL_13::time, and _u_MMuPC1AnalysisMQL_13::Xwire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_13 *_o1 = (struct _u_MMuPC1AnalysisMQL_13 *) _v1;
   struct _u_MMuPC1AnalysisMQL_13 *_o2 = (struct _u_MMuPC1AnalysisMQL_13 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Xwire = _o1->Xwire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Xwire = _o2->Xwire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_57 (const void * _v1, const void * _v2) static
Definition at line 552 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_13::cluster_size, _u_MMuPC1AnalysisMQL_13::cluster_width, time, _u_MMuPC1AnalysisMQL_13::time, and _u_MMuPC1AnalysisMQL_13::Xwire.
 {
   struct _u_MMuPC1AnalysisMQL_13 *_o1 = (struct _u_MMuPC1AnalysisMQL_13 *) _v1;
   struct _u_MMuPC1AnalysisMQL_13 *_o2 = (struct _u_MMuPC1AnalysisMQL_13 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Xwire = _o1->Xwire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Xwire = _o2->Xwire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_58 (const void * _v1, const void * _v2) static
Definition at line 577 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_13::cluster_size, _u_MMuPC1AnalysisMQL_13::cluster_width, time, _u_MMuPC1AnalysisMQL_13::time, and _u_MMuPC1AnalysisMQL_13::Xwire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_13 *_o1 = (struct _u_MMuPC1AnalysisMQL_13 *) _v1;
   struct _u_MMuPC1AnalysisMQL_13 *_o2 = (struct _u_MMuPC1AnalysisMQL_13 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Xwire = _o1->Xwire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Xwire = _o2->Xwire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_59 (const void * _v1, const void * _v2) static
Definition at line 611 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_13::cluster_size, _u_MMuPC1AnalysisMQL_13::cluster_width, time, _u_MMuPC1AnalysisMQL_13::time, and _u_MMuPC1AnalysisMQL_13::Xwire.
 {
   struct _u_MMuPC1AnalysisMQL_13 *_o1 = (struct _u_MMuPC1AnalysisMQL_13 *) _v1;
   struct _u_MMuPC1AnalysisMQL_13 *_o2 = (struct _u_MMuPC1AnalysisMQL_13 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Xwire = _o1->Xwire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Xwire = _o2->Xwire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_60 (const void * _v1, const void * _v2) static
Definition at line 636 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_13::cluster_size, _u_MMuPC1AnalysisMQL_13::cluster_width, time, _u_MMuPC1AnalysisMQL_13::time, and _u_MMuPC1AnalysisMQL_13::Xwire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_13 *_o1 = (struct _u_MMuPC1AnalysisMQL_13 *) _v1;
   struct _u_MMuPC1AnalysisMQL_13 *_o2 = (struct _u_MMuPC1AnalysisMQL_13 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Xwire = _o1->Xwire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Xwire = _o2->Xwire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_61 (const void * _v1, const void * _v2) static
Definition at line 678 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_17::time, and _u_MMuPC1AnalysisMQL_17::Ywire.
 {
   struct _u_MMuPC1AnalysisMQL_17 *_o1 = (struct _u_MMuPC1AnalysisMQL_17 *) _v1;
   struct _u_MMuPC1AnalysisMQL_17 *_o2 = (struct _u_MMuPC1AnalysisMQL_17 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_62 (const void * _v1, const void * _v2) static
Definition at line 699 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_17::time, and _u_MMuPC1AnalysisMQL_17::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_17 *_o1 = (struct _u_MMuPC1AnalysisMQL_17 *) _v1;
   struct _u_MMuPC1AnalysisMQL_17 *_o2 = (struct _u_MMuPC1AnalysisMQL_17 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_63 (const void * _v1, const void * _v2) static
Definition at line 730 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_17::time, and _u_MMuPC1AnalysisMQL_17::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_17 *_o1 = (struct _u_MMuPC1AnalysisMQL_17 *) _v1;
   struct _u_MMuPC1AnalysisMQL_17 *_o2 = (struct _u_MMuPC1AnalysisMQL_17 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_64 (const void * _v1, const void * _v2) static
Definition at line 751 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_19::cluster_size, time, and _u_MMuPC1AnalysisMQL_19::time.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_19 *_o1 = (struct _u_MMuPC1AnalysisMQL_19 *) _v1;
   struct _u_MMuPC1AnalysisMQL_19 *_o2 = (struct _u_MMuPC1AnalysisMQL_19 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int cluster_size = _o1->cluster_size;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int cluster_size = _o2->cluster_size;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_65 (const void * _v1, const void * _v2) static
Definition at line 787 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_17::time, and _u_MMuPC1AnalysisMQL_17::Ywire.
 {
   struct _u_MMuPC1AnalysisMQL_17 *_o1 = (struct _u_MMuPC1AnalysisMQL_17 *) _v1;
   struct _u_MMuPC1AnalysisMQL_17 *_o2 = (struct _u_MMuPC1AnalysisMQL_17 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_66 (const void * _v1, const void * _v2) static
Definition at line 808 of file MMuPC1AnalysisMQL.cpp.
References time, and _u_MMuPC1AnalysisMQL_20::time.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_20 *_o1 = (struct _u_MMuPC1AnalysisMQL_20 *) _v1;
   struct _u_MMuPC1AnalysisMQL_20 *_o2 = (struct _u_MMuPC1AnalysisMQL_20 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_67 (const void * _v1, const void * _v2) static
Definition at line 836 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_21::time, and _u_MMuPC1AnalysisMQL_21::Ywire.
 {
   struct _u_MMuPC1AnalysisMQL_21 *_o1 = (struct _u_MMuPC1AnalysisMQL_21 *) _v1;
   struct _u_MMuPC1AnalysisMQL_21 *_o2 = (struct _u_MMuPC1AnalysisMQL_21 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_68 (const void * _v1, const void * _v2) static
Definition at line 857 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_21::time, and _u_MMuPC1AnalysisMQL_21::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_21 *_o1 = (struct _u_MMuPC1AnalysisMQL_21 *) _v1;
   struct _u_MMuPC1AnalysisMQL_21 *_o2 = (struct _u_MMuPC1AnalysisMQL_21 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_69 (const void * _v1, const void * _v2) static
Definition at line 887 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_21::time, and _u_MMuPC1AnalysisMQL_21::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_21 *_o1 = (struct _u_MMuPC1AnalysisMQL_21 *) _v1;
   struct _u_MMuPC1AnalysisMQL_21 *_o2 = (struct _u_MMuPC1AnalysisMQL_21 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_70 (const void * _v1, const void * _v2) static
Definition at line 908 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_23::time, and _u_MMuPC1AnalysisMQL_23::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_23 *_o1 = (struct _u_MMuPC1AnalysisMQL_23 *) _v1;
   struct _u_MMuPC1AnalysisMQL_23 *_o2 = (struct _u_MMuPC1AnalysisMQL_23 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_71 (const void * _v1, const void * _v2) static
Definition at line 938 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_23::time, and _u_MMuPC1AnalysisMQL_23::Ywire.
 {
   struct _u_MMuPC1AnalysisMQL_23 *_o1 = (struct _u_MMuPC1AnalysisMQL_23 *) _v1;
   struct _u_MMuPC1AnalysisMQL_23 *_o2 = (struct _u_MMuPC1AnalysisMQL_23 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_72 (const void * _v1, const void * _v2) static
Definition at line 959 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_23::time, and _u_MMuPC1AnalysisMQL_23::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_23 *_o1 = (struct _u_MMuPC1AnalysisMQL_23 *) _v1;
   struct _u_MMuPC1AnalysisMQL_23 *_o2 = (struct _u_MMuPC1AnalysisMQL_23 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_73 (const void * _v1, const void * _v2) static
Definition at line 990 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_23::time, and _u_MMuPC1AnalysisMQL_23::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_23 *_o1 = (struct _u_MMuPC1AnalysisMQL_23 *) _v1;
   struct _u_MMuPC1AnalysisMQL_23 *_o2 = (struct _u_MMuPC1AnalysisMQL_23 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_74 (const void * _v1, const void * _v2) static
Definition at line 1011 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_25::time, _u_MMuPC1AnalysisMQL_25::Ywire_max, and _u_MMuPC1AnalysisMQL_25::Ywire_min.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_25 *_o1 = (struct _u_MMuPC1AnalysisMQL_25 *) _v1;
   struct _u_MMuPC1AnalysisMQL_25 *_o2 = (struct _u_MMuPC1AnalysisMQL_25 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire_min = _o1->Ywire_min;
     int Ywire_max = _o1->Ywire_max;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire_min = _o2->Ywire_min;
     int Ywire_max = _o2->Ywire_max;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_75 (const void * _v1, const void * _v2) static
Definition at line 1040 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_25::time, _u_MMuPC1AnalysisMQL_25::Ywire_max, and _u_MMuPC1AnalysisMQL_25::Ywire_min.
 {
   struct _u_MMuPC1AnalysisMQL_25 *_o1 = (struct _u_MMuPC1AnalysisMQL_25 *) _v1;
   struct _u_MMuPC1AnalysisMQL_25 *_o2 = (struct _u_MMuPC1AnalysisMQL_25 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire_min = _o1->Ywire_min;
     int Ywire_max = _o1->Ywire_max;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire_min = _o2->Ywire_min;
     int Ywire_max = _o2->Ywire_max;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_76 (const void * _v1, const void * _v2) static
Definition at line 1063 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_25::time, _u_MMuPC1AnalysisMQL_25::Ywire_max, and _u_MMuPC1AnalysisMQL_25::Ywire_min.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_25 *_o1 = (struct _u_MMuPC1AnalysisMQL_25 *) _v1;
   struct _u_MMuPC1AnalysisMQL_25 *_o2 = (struct _u_MMuPC1AnalysisMQL_25 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire_min = _o1->Ywire_min;
     int Ywire_max = _o1->Ywire_max;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire_min = _o2->Ywire_min;
     int Ywire_max = _o2->Ywire_max;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_77 (const void * _v1, const void * _v2) static
Definition at line 1096 of file MMuPC1AnalysisMQL.cpp.
References time, _u_MMuPC1AnalysisMQL_23::time, and _u_MMuPC1AnalysisMQL_23::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_23 *_o1 = (struct _u_MMuPC1AnalysisMQL_23 *) _v1;
   struct _u_MMuPC1AnalysisMQL_23 *_o2 = (struct _u_MMuPC1AnalysisMQL_23 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     int Ywire = _o1->Ywire;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     int Ywire = _o2->Ywire;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_78 (const void * _v1, const void * _v2) static
Definition at line 1117 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_27::cluster_size, _u_MMuPC1AnalysisMQL_27::cluster_width, time, _u_MMuPC1AnalysisMQL_27::time, and _u_MMuPC1AnalysisMQL_27::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_27 *_o1 = (struct _u_MMuPC1AnalysisMQL_27 *) _v1;
   struct _u_MMuPC1AnalysisMQL_27 *_o2 = (struct _u_MMuPC1AnalysisMQL_27 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Ywire = _o1->Ywire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Ywire = _o2->Ywire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_79 (const void * _v1, const void * _v2) static
Definition at line 1159 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_27::cluster_size, _u_MMuPC1AnalysisMQL_27::cluster_width, time, _u_MMuPC1AnalysisMQL_27::time, and _u_MMuPC1AnalysisMQL_27::Ywire.
 {
   struct _u_MMuPC1AnalysisMQL_27 *_o1 = (struct _u_MMuPC1AnalysisMQL_27 *) _v1;
   struct _u_MMuPC1AnalysisMQL_27 *_o2 = (struct _u_MMuPC1AnalysisMQL_27 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Ywire = _o1->Ywire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Ywire = _o2->Ywire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_80 (const void * _v1, const void * _v2) static
Definition at line 1184 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_27::cluster_size, _u_MMuPC1AnalysisMQL_27::cluster_width, time, _u_MMuPC1AnalysisMQL_27::time, and _u_MMuPC1AnalysisMQL_27::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_27 *_o1 = (struct _u_MMuPC1AnalysisMQL_27 *) _v1;
   struct _u_MMuPC1AnalysisMQL_27 *_o2 = (struct _u_MMuPC1AnalysisMQL_27 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Ywire = _o1->Ywire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Ywire = _o2->Ywire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_81 (const void * _v1, const void * _v2) static
Definition at line 1218 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_27::cluster_size, _u_MMuPC1AnalysisMQL_27::cluster_width, time, _u_MMuPC1AnalysisMQL_27::time, and _u_MMuPC1AnalysisMQL_27::Ywire.
 {
   struct _u_MMuPC1AnalysisMQL_27 *_o1 = (struct _u_MMuPC1AnalysisMQL_27 *) _v1;
   struct _u_MMuPC1AnalysisMQL_27 *_o2 = (struct _u_MMuPC1AnalysisMQL_27 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Ywire = _o1->Ywire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Ywire = _o2->Ywire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_82 (const void * _v1, const void * _v2) static
Definition at line 1243 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_27::cluster_size, _u_MMuPC1AnalysisMQL_27::cluster_width, time, _u_MMuPC1AnalysisMQL_27::time, and _u_MMuPC1AnalysisMQL_27::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_27 *_o1 = (struct _u_MMuPC1AnalysisMQL_27 *) _v1;
   struct _u_MMuPC1AnalysisMQL_27 *_o2 = (struct _u_MMuPC1AnalysisMQL_27 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Ywire = _o1->Ywire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Ywire = _o2->Ywire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_83 (const void * _v1, const void * _v2) static
Definition at line 1278 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_13::cluster_size, _u_MMuPC1AnalysisMQL_13::cluster_width, time, _u_MMuPC1AnalysisMQL_13::time, and _u_MMuPC1AnalysisMQL_13::Xwire.
 {
   struct _u_MMuPC1AnalysisMQL_13 *_o1 = (struct _u_MMuPC1AnalysisMQL_13 *) _v1;
   struct _u_MMuPC1AnalysisMQL_13 *_o2 = (struct _u_MMuPC1AnalysisMQL_13 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Xwire = _o1->Xwire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Xwire = _o2->Xwire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_84 (const void * _v1, const void * _v2) static
Definition at line 1303 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_27::cluster_size, _u_MMuPC1AnalysisMQL_27::cluster_width, time, _u_MMuPC1AnalysisMQL_27::time, and _u_MMuPC1AnalysisMQL_27::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_27 *_o1 = (struct _u_MMuPC1AnalysisMQL_27 *) _v1;
   struct _u_MMuPC1AnalysisMQL_27 *_o2 = (struct _u_MMuPC1AnalysisMQL_27 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     double Ywire = _o1->Ywire;
     int cluster_size = _o1->cluster_size;
     int cluster_width = _o1->cluster_width;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     double Ywire = _o2->Ywire;
     int cluster_size = _o2->cluster_size;
     int cluster_width = _o2->cluster_width;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_85 (const void * _v1, const void * _v2) static
Definition at line 1328 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_31::muPC1Time, _u_MMuPC1AnalysisMQL_31::Xwire, _u_MMuPC1AnalysisMQL_31::XYtdiff, and _u_MMuPC1AnalysisMQL_31::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_31 *_o1 = (struct _u_MMuPC1AnalysisMQL_31 *) _v1;
   struct _u_MMuPC1AnalysisMQL_31 *_o2 = (struct _u_MMuPC1AnalysisMQL_31 *) _v2;
   double _sv1, _sv2;
   {
     double Xwire = _o1->Xwire;
     double Ywire = _o1->Ywire;
     double muPC1Time = _o1->muPC1Time;
     double XYtdiff = _o1->XYtdiff;
     _sv1 = muPC1Time;
   }
   {
     double Xwire = _o2->Xwire;
     double Ywire = _o2->Ywire;
     double muPC1Time = _o2->muPC1Time;
     double XYtdiff = _o2->XYtdiff;
     _sv2 = muPC1Time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_86 (const void * _v1, const void * _v2) static
Definition at line 1370 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_32::muPC1Time, _u_MMuPC1AnalysisMQL_32::Xwire, and _u_MMuPC1AnalysisMQL_32::Ywire.
 {
   struct _u_MMuPC1AnalysisMQL_32 *_o1 = (struct _u_MMuPC1AnalysisMQL_32 *) _v1;
   struct _u_MMuPC1AnalysisMQL_32 *_o2 = (struct _u_MMuPC1AnalysisMQL_32 *) _v2;
   double _sv1, _sv2;
   {
     double Xwire = _o1->Xwire;
     double Ywire = _o1->Ywire;
     double muPC1Time = _o1->muPC1Time;
     _sv1 = muPC1Time;
   }
   {
     double Xwire = _o2->Xwire;
     double Ywire = _o2->Ywire;
     double muPC1Time = _o2->muPC1Time;
     _sv2 = muPC1Time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_87 (const void * _v1, const void * _v2) static
Definition at line 1393 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_32::muPC1Time, _u_MMuPC1AnalysisMQL_32::Xwire, and _u_MMuPC1AnalysisMQL_32::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_32 *_o1 = (struct _u_MMuPC1AnalysisMQL_32 *) _v1;
   struct _u_MMuPC1AnalysisMQL_32 *_o2 = (struct _u_MMuPC1AnalysisMQL_32 *) _v2;
   double _sv1, _sv2;
   {
     double Xwire = _o1->Xwire;
     double Ywire = _o1->Ywire;
     double muPC1Time = _o1->muPC1Time;
     _sv1 = muPC1Time;
   }
   {
     double Xwire = _o2->Xwire;
     double Ywire = _o2->Ywire;
     double muPC1Time = _o2->muPC1Time;
     _sv2 = muPC1Time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_88 (const void * _v1, const void * _v2) static
Definition at line 1432 of file MMuPC1AnalysisMQL.cpp.
References time, and _u_MMuPC1AnalysisMQL_34::time.
 {
   struct _u_MMuPC1AnalysisMQL_34 *_o1 = (struct _u_MMuPC1AnalysisMQL_34 *) _v1;
   struct _u_MMuPC1AnalysisMQL_34 *_o2 = (struct _u_MMuPC1AnalysisMQL_34 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_89 (const void * _v1, const void * _v2) static
Definition at line 1451 of file MMuPC1AnalysisMQL.cpp.
References _u_MMuPC1AnalysisMQL_32::muPC1Time, _u_MMuPC1AnalysisMQL_32::Xwire, and _u_MMuPC1AnalysisMQL_32::Ywire.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_32 *_o1 = (struct _u_MMuPC1AnalysisMQL_32 *) _v1;
   struct _u_MMuPC1AnalysisMQL_32 *_o2 = (struct _u_MMuPC1AnalysisMQL_32 *) _v2;
   double _sv1, _sv2;
   {
     double Xwire = _o1->Xwire;
     double Ywire = _o1->Ywire;
     double muPC1Time = _o1->muPC1Time;
     _sv1 = muPC1Time;
   }
   {
     double Xwire = _o2->Xwire;
     double Ywire = _o2->Ywire;
     double muPC1Time = _o2->muPC1Time;
     _sv2 = muPC1Time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_90 (const void * _v1, const void * _v2) static
Definition at line 1482 of file MMuPC1AnalysisMQL.cpp.
References time, and _u_MMuPC1AnalysisMQL_36::time.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_36 *_o1 = (struct _u_MMuPC1AnalysisMQL_36 *) _v1;
   struct _u_MMuPC1AnalysisMQL_36 *_o2 = (struct _u_MMuPC1AnalysisMQL_36 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
static int _u_MMuPC1AnalysisMQL_91 (const void * _v1, const void * _v2) static
Definition at line 1508 of file MMuPC1AnalysisMQL.cpp.
References time, and _u_MMuPC1AnalysisMQL_36::time.
Referenced by MMuPC1AnalysisMQL().
 {
   struct _u_MMuPC1AnalysisMQL_36 *_o1 = (struct _u_MMuPC1AnalysisMQL_36 *) _v1;
   struct _u_MMuPC1AnalysisMQL_36 *_o2 = (struct _u_MMuPC1AnalysisMQL_36 *) _v2;
   double _sv1, _sv2;
   {
     double time = _o1->time;
     _sv1 = time;
   }
   {
     double time = _o2->time;
     _sv2 = time;
   }
   double _diff = _sv1 - _sv2;
   if(_diff < 0) return -1;
   if(_diff == 0) return 0;
   if(_diff > 0) return  1;
 }
INT MMuPC1AnalysisMQL (EVENT_HEADER * pheader, void * pevent)
Definition at line 1792 of file MMuPC1AnalysisMQL.cpp.
References _h_muPC1_coinc_XY_2D, _h_muPC1_coinc_XY_2D_with_muSC, _h_muPC1_coinc_XY_autocorr_all_1D, _h_muPC1_coinc_XY_tdiff, _h_muPC1_spark_chamberwide_blocktime, _h_muPC1_spark_chamberwide_count, _h_muPC1_spark_clustered_blocktime, _h_muPC1_spark_count_Xwires, _h_muPC1_spark_count_Ywires, _h_muPC1_spark_search_Xwires, _h_muPC1_spark_search_Ywires, _h_muPC1_X_AD_autocorr_2D, _h_muPC1_X_AD_autocorr_all_1D, _h_muPC1_X_cluster_contiguous_separation, _h_muPC1_X_final_cluster_autocorr_all_1D, _h_muPC1_X_final_cluster_autocorr_spatial_all_1D, _h_muPC1_X_final_cluster_avg, _h_muPC1_X_final_cluster_size, _h_muPC1_X_final_cluster_width, _h_muPC1_X_raw_autocorr_2D, _h_muPC1_X_raw_autocorr_all_1D, _h_muPC1_X_raw_autosingles_2D, _h_muPC1_X_SC_autocorr_2D, _h_muPC1_X_SC_autocorr_all_1D, _h_muPC1_Y_AD_autocorr_2D, _h_muPC1_Y_AD_autocorr_all_1D, _h_muPC1_Y_cluster_contiguous_separation, _h_muPC1_Y_final_cluster_autocorr_all_1D, _h_muPC1_Y_final_cluster_autocorr_spatial_all_1D, _h_muPC1_Y_final_cluster_avg, _h_muPC1_Y_final_cluster_size, _h_muPC1_Y_final_cluster_width, _h_muPC1_Y_raw_autocorr_2D, _h_muPC1_Y_raw_autocorr_all_1D, _h_muPC1_Y_raw_autosingles_2D, _h_muPC1_Y_SC_autocorr_2D, _h_muPC1_Y_SC_autocorr_all_1D, _h_muSC_muPC1_time_difference, _h_parameters_muPC1, _u_MMuPC1AnalysisMQL_40(), _u_MMuPC1AnalysisMQL_41(), _u_MMuPC1AnalysisMQL_42(), _u_MMuPC1AnalysisMQL_44(), _u_MMuPC1AnalysisMQL_46(), _u_MMuPC1AnalysisMQL_47(), _u_MMuPC1AnalysisMQL_48(), _u_MMuPC1AnalysisMQL_50(), _u_MMuPC1AnalysisMQL_51(), _u_MMuPC1AnalysisMQL_52(), _u_MMuPC1AnalysisMQL_54(), _u_MMuPC1AnalysisMQL_55(), _u_MMuPC1AnalysisMQL_56(), _u_MMuPC1AnalysisMQL_58(), _u_MMuPC1AnalysisMQL_60(), _u_MMuPC1AnalysisMQL_62(), _u_MMuPC1AnalysisMQL_63(), _u_MMuPC1AnalysisMQL_64(), _u_MMuPC1AnalysisMQL_66(), _u_MMuPC1AnalysisMQL_68(), _u_MMuPC1AnalysisMQL_69(), _u_MMuPC1AnalysisMQL_70(), _u_MMuPC1AnalysisMQL_72(), _u_MMuPC1AnalysisMQL_73(), _u_MMuPC1AnalysisMQL_74(), _u_MMuPC1AnalysisMQL_76(), _u_MMuPC1AnalysisMQL_77(), _u_MMuPC1AnalysisMQL_78(), _u_MMuPC1AnalysisMQL_80(), _u_MMuPC1AnalysisMQL_82(), _u_MMuPC1AnalysisMQL_84(), _u_MMuPC1AnalysisMQL_85(), _u_MMuPC1AnalysisMQL_87(), _u_MMuPC1AnalysisMQL_89(), _u_MMuPC1AnalysisMQL_90(), _u_MMuPC1AnalysisMQL_91(), MqlArray< T >::checkSort(), MqlArray< T >::finish(), MqlArray< T >::fromBank(), kMuPC1NumXWires, kMuPC1NumYWires, kMuPC1XClusterInterval, kMuPC1XClusterMaxGap, kMuPC1XSparkSizeCutoff, kMuPC1YClusterInterval, kMuPC1YClusterMaxGap, kMuPC1YSparkSizeCutoff, kSparkCutDeadtime, MAX, MIN, MqlArray< T >::next(), parameter, printf(), MqlArray< T >::reset(), MqlArray< T >::size(), MqlArray< T >::sort(), SUCCESS, Tier1, Tier3, time, and MqlArray< T >::toBank().
 {
   _t_muPC1X_auto.reset();
   _t_muPC1_sparks_union.reset();
   _t_muPC1X_cluster_contiguous.reset();
   _t_muPC1Y_temporal_auto.reset();
   _t_muPC1X_raw_auto.reset();
   _t_muPC1X_AD.reset();
   _t_muPC1Y_spark_search.reset();
   _t_muPC1X_cluster_contiguous_sep.reset();
   _t_muPC1X_spatial_auto.reset();
   _t_muPC1X_export.reset();
   _t_muPC1X_SC.reset();
   _t_muPC1Y_export.reset();
   _t_muPC1Y_raw_auto.reset();
   _t_muPC1Y.reset();
   _t_muPC1X.reset();
   _t_muSC.reset();
   _t_muPC1Y_cluster_contiguous_sep.reset();
   _t_muPC1_auto.reset();
   _t_muPC1Y_SC_auto.reset();
   _t_hits.reset();
   _t_muPC1X_spark_search.reset();
   _t_muPC1X_AD_auto.reset();
   _t_muPC1X_sparks.reset();
   _t_muPC1Y_sparks.reset();
   _t_muPC1.reset();
   _t_muPC1Y_AD.reset();
   _t_muPC1_sparks_clustered.reset();
   _t_muPC1_hits.reset();
   _t_muPC1Y_raw.reset();
   _t_muPC1Y_SC.reset();
   _t_muSC_muPC1.reset();
   _t_muPC1_sparks_chamberwide.reset();
   _t_muPC1Y_AD_auto.reset();
   _t_muPC1Y_cluster_contiguous.reset();
   _t_muPC1XY.reset();
   _t_muPC1Y_spatial_auto.reset();
   _t_muPC1X_raw.reset();
   _t_muPC1X_SC_auto.reset();
   int _u_MMuPC1AnalysisMQL_92 = 0;
   double _u_MMuPC1AnalysisMQL_93 = 0;
   bool _u_MMuPC1AnalysisMQL_94 = false;
   bool _u_MMuPC1AnalysisMQL_95 = false;
   int _u_MMuPC1AnalysisMQL_96 = 0;
   int _u_MMuPC1AnalysisMQL_97 = 0;
   double _u_MMuPC1AnalysisMQL_98 = 0;
   bool _u_MMuPC1AnalysisMQL_99 = false;
   bool _u_MMuPC1AnalysisMQL_100 = false;
   int _u_MMuPC1AnalysisMQL_101 = 0;
   int _u_MMuPC1AnalysisMQL_102 = 0;
   double _u_MMuPC1AnalysisMQL_103 = 0;
   bool _u_MMuPC1AnalysisMQL_104 = false;
   bool _u_MMuPC1AnalysisMQL_105 = false;
   int _u_MMuPC1AnalysisMQL_106 = 0;
   int _u_MMuPC1AnalysisMQL_107 = 0;
   double _u_MMuPC1AnalysisMQL_108 = 0;
   bool _u_MMuPC1AnalysisMQL_109 = false;
   bool _u_MMuPC1AnalysisMQL_110 = false;
   int _u_MMuPC1AnalysisMQL_111 = 0;
   int _u_MMuPC1AnalysisMQL_112 = 0;
   double _u_MMuPC1AnalysisMQL_113 = 0;
   bool _u_MMuPC1AnalysisMQL_114 = false;
   bool _u_MMuPC1AnalysisMQL_115 = false;
   int _u_MMuPC1AnalysisMQL_116 = 0;
   int _u_MMuPC1AnalysisMQL_117 = 0;
   double _u_MMuPC1AnalysisMQL_118 = 0;
   bool _u_MMuPC1AnalysisMQL_119 = false;
   bool _u_MMuPC1AnalysisMQL_120 = false;
   int _u_MMuPC1AnalysisMQL_121 = 0;
   double _u_MMuPC1AnalysisMQL_122 = 0;
   bool _u_MMuPC1AnalysisMQL_123 = false;
   bool _u_MMuPC1AnalysisMQL_124 = false;
   int _u_MMuPC1AnalysisMQL_125 = 0;
   double _u_MMuPC1AnalysisMQL_126 = 0;
   bool _u_MMuPC1AnalysisMQL_127 = false;
   bool _u_MMuPC1AnalysisMQL_128 = false;
   int _u_MMuPC1AnalysisMQL_129 = 0;
   int _u_MMuPC1AnalysisMQL_130 = 0;
   double _u_MMuPC1AnalysisMQL_131 = 0;
   bool _u_MMuPC1AnalysisMQL_132 = false;
   bool _u_MMuPC1AnalysisMQL_133 = false;
   int _u_MMuPC1AnalysisMQL_134 = 0;
   int _u_MMuPC1AnalysisMQL_135 = 0;
   double _u_MMuPC1AnalysisMQL_136 = 0;
   bool _u_MMuPC1AnalysisMQL_137 = false;
   bool _u_MMuPC1AnalysisMQL_138 = false;
   int _u_MMuPC1AnalysisMQL_139 = 0;
   int _u_MMuPC1AnalysisMQL_140 = 0;
   double _u_MMuPC1AnalysisMQL_141 = 0;
   bool _u_MMuPC1AnalysisMQL_142 = false;
   bool _u_MMuPC1AnalysisMQL_143 = false;
   int _u_MMuPC1AnalysisMQL_144 = 0;
   int _u_MMuPC1AnalysisMQL_145 = 0;
   double _u_MMuPC1AnalysisMQL_146 = 0;
   bool _u_MMuPC1AnalysisMQL_147 = false;
   bool _u_MMuPC1AnalysisMQL_148 = false;
   int _u_MMuPC1AnalysisMQL_149 = 0;
   int _u_MMuPC1AnalysisMQL_150 = 0;
   double _u_MMuPC1AnalysisMQL_151 = 0;
   bool _u_MMuPC1AnalysisMQL_152 = false;
   bool _u_MMuPC1AnalysisMQL_153 = false;
   int _u_MMuPC1AnalysisMQL_154 = 0;
   double _u_MMuPC1AnalysisMQL_155 = 0;
   bool _u_MMuPC1AnalysisMQL_156 = false;
   bool _u_MMuPC1AnalysisMQL_157 = false;
   int _u_MMuPC1AnalysisMQL_158 = 0;
   double _u_MMuPC1AnalysisMQL_159 = 0;
   bool _u_MMuPC1AnalysisMQL_160 = false;
   bool _u_MMuPC1AnalysisMQL_161 = false;
   int _u_MMuPC1AnalysisMQL_162 = 0;
   double _u_MMuPC1AnalysisMQL_163 = 0;
   bool _u_MMuPC1AnalysisMQL_164 = false;
   bool _u_MMuPC1AnalysisMQL_165 = false;
   int _u_MMuPC1AnalysisMQL_166 = 0;
   double _u_MMuPC1AnalysisMQL_167 = 0;
   bool _u_MMuPC1AnalysisMQL_168 = false;
   bool _u_MMuPC1AnalysisMQL_169 = false;
   int _u_MMuPC1AnalysisMQL_170 = 0;
   _t_hits.fromBank(pevent, "HITS");
   for(int _u_MMuPC1AnalysisMQL_171 = 0; _u_MMuPC1AnalysisMQL_171 < _t_hits.size(); _u_MMuPC1AnalysisMQL_171++)
   {
     double time = _t_hits[_u_MMuPC1AnalysisMQL_171].time;
     int parameter = _t_hits[_u_MMuPC1AnalysisMQL_171].parameter;
     if((parameter >= 4001) && (parameter <= 4074))
     {
       {
         double time_0 = time;
         int parameter_0 = parameter;
         double time = time_0;
         int parameter = parameter_0;
         if((parameter >= 4001) && (parameter <= (4000+kMuPC1NumXWires)))
         {
           {
             double time_0 = time;
             int Xwire = parameter - 4000;
             double time = time_0;
             int _u_MMuPC1AnalysisMQL_172 = _t_muPC1X_raw.next();
             _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_172].time = time_0;
             _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_172].Xwire = Xwire;
           }
         }
         if((parameter >= 4051) && (parameter <= (4050+kMuPC1NumYWires)))
         {
           {
             double time_0 = time;
             int Ywire = parameter - 4050;
             double time = time_0;
             int _u_MMuPC1AnalysisMQL_173 = _t_muPC1Y_raw.next();
             _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_173].time = time_0;
             _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_173].Ywire = Ywire;
           }
         }
         if(Tier1)
         {
           _h_parameters_muPC1->Fill(parameter);
         }
       }
     }
     if((parameter == 6011))
     {
       {
         double time_0 = time;
         double time = time_0;
         int _u_MMuPC1AnalysisMQL_174 = _t_muSC.next();
         _t_muSC[_u_MMuPC1AnalysisMQL_174].time = time_0;
       }
     }
   }
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_175 = 0; _u_MMuPC1AnalysisMQL_175 < _t_muPC1X_raw.size(); _u_MMuPC1AnalysisMQL_175++)
     {
       double time = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_175].time;
       int Xwire = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_175].Xwire;
       {
         double time_1 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_175].time;
         int Xwire_1 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_175].Xwire;
         if(!_u_MMuPC1AnalysisMQL_94)
         {
           if(!_t_muPC1X_raw.checkSort(_u_MMuPC1AnalysisMQL_40))
           {
             printf("Warning: table muPC1X_raw is not sorted on time_2 as required for join with muPC1X_raw (_u_MMuPC1AnalysisMQL_40)\n");
           }
           _u_MMuPC1AnalysisMQL_94 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_95)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_93))
           {
             printf("Warning: table muPC1X_raw is not sorted on time_1 as required for join with muPC1X_raw\n");
             _u_MMuPC1AnalysisMQL_95 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_93 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_92 < _t_muPC1X_raw.size(); _u_MMuPC1AnalysisMQL_92++)
         {
           double time_2 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_92].time;
           int Xwire_2 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_92].Xwire;
           double _u_MMuPC1AnalysisMQL_176 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_176 < 1)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_178 = _u_MMuPC1AnalysisMQL_92; _u_MMuPC1AnalysisMQL_178 < _t_muPC1X_raw.size(); _u_MMuPC1AnalysisMQL_178++)
         {
           double time_2 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_178].time;
           int Xwire_2 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_178].Xwire;
           double _u_MMuPC1AnalysisMQL_176 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_176 < -50005)
           {
             break;
           }
           {
             double time_1_0 = time_1;
             int Xwire_1_0 = Xwire_1;
             double time_2_0 = time_2;
             int Xwire_2_0 = Xwire_2;
             double time_1 = time_1_0;
             int Xwire_1 = Xwire_1_0;
             double time_2 = time_2_0;
             int Xwire_2 = Xwire_2_0;
             if(Tier3)
             {
               _h_muPC1_X_raw_autosingles_2D->Fill(Xwire_1, Xwire_2);
             }
             if(Tier3)
             {
               if((time_2 - time_1) >= 0)
               {
                 _h_muPC1_X_raw_autocorr_all_1D->Fill(time_2 - time_1);
               }
             }
             if(Tier3)
             {
               if(((time_2 - time_1) >= 0) && (Xwire_1==Xwire_2))
               {
                 _h_muPC1_X_raw_autocorr_2D->Fill(time_2 - time_1, Xwire_1);
               }
             }
           }
         }
       }
     }
   }
   bool _u_MMuPC1AnalysisMQL_179[_t_muPC1X_raw.size()];
   memset(_u_MMuPC1AnalysisMQL_179, 0, sizeof(_u_MMuPC1AnalysisMQL_179));
   if(!_t_muPC1X_raw.checkSort(_u_MMuPC1AnalysisMQL_41))
   {
     printf("Warning: table muPC1X_raw is not sorted on time_1 as required for cluster.\n");
   }
   for(int _u_MMuPC1AnalysisMQL_180 = 0; _u_MMuPC1AnalysisMQL_180 < _t_muPC1X_raw.size(); _u_MMuPC1AnalysisMQL_180++)
   {
     double time = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_180].time;
     int Xwire = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_180].Xwire;
     if(_u_MMuPC1AnalysisMQL_179[_u_MMuPC1AnalysisMQL_180])
     {
       continue;
     }
     _u_MMuPC1AnalysisMQL_179[_u_MMuPC1AnalysisMQL_180] = true;
     int cluster_size = 1;
     int cluster_members[_t_muPC1X_raw.size()];
     cluster_members[0] = _u_MMuPC1AnalysisMQL_180;
     for(int _u_MMuPC1AnalysisMQL_181 = _u_MMuPC1AnalysisMQL_180 + 1; _u_MMuPC1AnalysisMQL_181 < _t_muPC1X_raw.size(); _u_MMuPC1AnalysisMQL_181++)
     {
       if(_u_MMuPC1AnalysisMQL_179[_u_MMuPC1AnalysisMQL_181])
       {
         continue;
       }
       bool coincidence_seen = false;
       for(int _u_MMuPC1AnalysisMQL_182 = 0; _u_MMuPC1AnalysisMQL_182 < cluster_size; _u_MMuPC1AnalysisMQL_182++)
       {
         int _u_MMuPC1AnalysisMQL_183 = cluster_members[_u_MMuPC1AnalysisMQL_182];
         double time_1 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_183].time;
         double time_2 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_181].time;
         int Xwire_1 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_183].Xwire;
         int Xwire_2 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_181].Xwire;
         double _u_MMuPC1AnalysisMQL_184 = time_1 - time_2;
         if(_u_MMuPC1AnalysisMQL_184 < -1000)
         {
           continue;
         }
         coincidence_seen = true;
         cluster_members[cluster_size++] = _u_MMuPC1AnalysisMQL_181;
         _u_MMuPC1AnalysisMQL_179[_u_MMuPC1AnalysisMQL_181] = true;
         _u_MMuPC1AnalysisMQL_181 = _u_MMuPC1AnalysisMQL_180;
         break;
       }
       if(!coincidence_seen)
       {
         break;
       }
     }
     double time_min = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_180].time;
     double time_max = time_min;
     double time_sum = 0;
     int Xwire_min = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_180].Xwire;
     int Xwire_max = Xwire_min;
     int Xwire_sum = 0;
     for(int _u_MMuPC1AnalysisMQL_182 = 0; _u_MMuPC1AnalysisMQL_182 < cluster_size; _u_MMuPC1AnalysisMQL_182++)
     {
       int _u_MMuPC1AnalysisMQL_183 = cluster_members[_u_MMuPC1AnalysisMQL_182];
       time = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_183].time;
       time_min = MIN(time_min, time);
       time_max = MAX(time_max, time);
       time_sum = time_sum + time;
       Xwire = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_183].Xwire;
       Xwire_min = MIN(Xwire_min, Xwire);
       Xwire_max = MAX(Xwire_max, Xwire);
       Xwire_sum = Xwire_sum + Xwire;
     }
     double time_1 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_180].time;
     double time_avg = time_sum/((double)cluster_size);
     double time_width = time_max - time_min + 1;
     int Xwire_1 = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_180].Xwire;
     double Xwire_avg = Xwire_sum/((double)cluster_size);
     int Xwire_width = Xwire_max - Xwire_min + 1;
     {
       double time = time_min;
       int cluster_size_0 = cluster_size;
       int cluster_size = cluster_size_0;
       if((cluster_size >= kMuPC1XSparkSizeCutoff))
       {
         {
           double time_0 = time;
           double time = time_0;
           if(Tier1)
           {
             _h_muPC1_spark_count_Xwires->Fill(1);
           }
           int _u_MMuPC1AnalysisMQL_185 = _t_muPC1X_sparks.next();
           _t_muPC1X_sparks[_u_MMuPC1AnalysisMQL_185].time = time_0;
         }
       }
       if(Tier1)
       {
         _h_muPC1_spark_search_Xwires->Fill(cluster_size);
       }
     }
   }
   _t_muPC1X_spark_search.sort(_u_MMuPC1AnalysisMQL_42);
   for(int _u_MMuPC1AnalysisMQL_186 = 0; _u_MMuPC1AnalysisMQL_186 < _t_muPC1X_raw.size(); _u_MMuPC1AnalysisMQL_186++)
   {
     double time = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_186].time;
     int Xwire = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_186].Xwire;
     {
       double muPC1X_raw_time = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_186].time;
       int Xwire = _t_muPC1X_raw[_u_MMuPC1AnalysisMQL_186].Xwire;
       if(!_u_MMuPC1AnalysisMQL_99)
       {
         if(!_t_muPC1X_sparks.checkSort(_u_MMuPC1AnalysisMQL_44))
         {
           printf("Warning: table muPC1X_sparks is not sorted on muPC1X_sparks_time as required for join with muPC1X_raw (_u_MMuPC1AnalysisMQL_44)\n");
         }
         _u_MMuPC1AnalysisMQL_99 = true;
       }
       else if(!_u_MMuPC1AnalysisMQL_100)
       {
         if(!(muPC1X_raw_time >= _u_MMuPC1AnalysisMQL_98))
         {
           printf("Warning: table muPC1X_raw is not sorted on muPC1X_raw_time as required for join with muPC1X_sparks\n");
           _u_MMuPC1AnalysisMQL_100 = true;
         }
       }
       _u_MMuPC1AnalysisMQL_98 = muPC1X_raw_time;
       for( ; _u_MMuPC1AnalysisMQL_97 < _t_muPC1X_sparks.size(); _u_MMuPC1AnalysisMQL_97++)
       {
         double muPC1X_sparks_time = _t_muPC1X_sparks[_u_MMuPC1AnalysisMQL_97].time;
         double _u_MMuPC1AnalysisMQL_187 = muPC1X_raw_time - muPC1X_sparks_time;
         if(_u_MMuPC1AnalysisMQL_187 < kSparkCutDeadtime)
         {
           break;
         }
       }
       _u_MMuPC1AnalysisMQL_101 = 0;
       for(int _u_MMuPC1AnalysisMQL_189 = _u_MMuPC1AnalysisMQL_97; _u_MMuPC1AnalysisMQL_189 < _t_muPC1X_sparks.size(); _u_MMuPC1AnalysisMQL_189++)
       {
         double muPC1X_sparks_time = _t_muPC1X_sparks[_u_MMuPC1AnalysisMQL_189].time;
         double _u_MMuPC1AnalysisMQL_187 = muPC1X_raw_time - muPC1X_sparks_time;
         if(_u_MMuPC1AnalysisMQL_187 < -100)
         {
           break;
         }
         _u_MMuPC1AnalysisMQL_101++;
       }
       if(_u_MMuPC1AnalysisMQL_101 == 0)
       {
         {
           double time = muPC1X_raw_time;
           int Xwire_0 = Xwire;
           int Xwire = Xwire_0;
           int _u_MMuPC1AnalysisMQL_190 = _t_muPC1X_SC.next();
           _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_190].time = time;
           _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_190].Xwire = Xwire_0;
         }
       }
     }
   }
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_191 = 0; _u_MMuPC1AnalysisMQL_191 < _t_muPC1X_SC.size(); _u_MMuPC1AnalysisMQL_191++)
     {
       double time = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_191].time;
       int Xwire = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_191].Xwire;
       {
         double time_1 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_191].time;
         int Xwire_1 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_191].Xwire;
         if(!_u_MMuPC1AnalysisMQL_104)
         {
           if(!_t_muPC1X_SC.checkSort(_u_MMuPC1AnalysisMQL_46))
           {
             printf("Warning: table muPC1X_SC is not sorted on time_2 as required for join with muPC1X_SC (_u_MMuPC1AnalysisMQL_46)\n");
           }
           _u_MMuPC1AnalysisMQL_104 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_105)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_103))
           {
             printf("Warning: table muPC1X_SC is not sorted on time_1 as required for join with muPC1X_SC\n");
             _u_MMuPC1AnalysisMQL_105 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_103 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_102 < _t_muPC1X_SC.size(); _u_MMuPC1AnalysisMQL_102++)
         {
           double time_2 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_102].time;
           int Xwire_2 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_102].Xwire;
           double _u_MMuPC1AnalysisMQL_192 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_192 < 1)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_194 = _u_MMuPC1AnalysisMQL_102; _u_MMuPC1AnalysisMQL_194 < _t_muPC1X_SC.size(); _u_MMuPC1AnalysisMQL_194++)
         {
           double time_2 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_194].time;
           int Xwire_2 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_194].Xwire;
           double _u_MMuPC1AnalysisMQL_192 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_192 < -50005)
           {
             break;
           }
           {
             double time_1_0 = time_1;
             int Xwire_1_0 = Xwire_1;
             double time_2_0 = time_2;
             int Xwire_2_0 = Xwire_2;
             double time_1 = time_1_0;
             int Xwire_1 = Xwire_1_0;
             double time_2 = time_2_0;
             int Xwire_2 = Xwire_2_0;
             if(Tier3)
             {
               if((time_2 - time_1) >= 0)
               {
                 _h_muPC1_X_SC_autocorr_all_1D->Fill(time_2 - time_1);
               }
             }
             if(Tier3)
             {
               if(((time_2 - time_1) >= 0) && (Xwire_1==Xwire_2))
               {
                 _h_muPC1_X_SC_autocorr_2D->Fill(time_2 - time_1, Xwire_1);
               }
             }
           }
         }
       }
     }
   }
   bool _u_MMuPC1AnalysisMQL_195[_t_muPC1X_SC.size()];
   memset(_u_MMuPC1AnalysisMQL_195, 0, sizeof(_u_MMuPC1AnalysisMQL_195));
   if(!_t_muPC1X_SC.checkSort(_u_MMuPC1AnalysisMQL_47))
   {
     printf("Warning: table muPC1X_SC is not sorted on time_1 as required for cluster.\n");
   }
   for(int _u_MMuPC1AnalysisMQL_196 = 0; _u_MMuPC1AnalysisMQL_196 < _t_muPC1X_SC.size(); _u_MMuPC1AnalysisMQL_196++)
   {
     double time = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_196].time;
     int Xwire = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_196].Xwire;
     if(_u_MMuPC1AnalysisMQL_195[_u_MMuPC1AnalysisMQL_196])
     {
       continue;
     }
     _u_MMuPC1AnalysisMQL_195[_u_MMuPC1AnalysisMQL_196] = true;
     int cluster_size = 1;
     int cluster_members[_t_muPC1X_SC.size()];
     cluster_members[0] = _u_MMuPC1AnalysisMQL_196;
     for(int _u_MMuPC1AnalysisMQL_197 = _u_MMuPC1AnalysisMQL_196 + 1; _u_MMuPC1AnalysisMQL_197 < _t_muPC1X_SC.size(); _u_MMuPC1AnalysisMQL_197++)
     {
       if(_u_MMuPC1AnalysisMQL_195[_u_MMuPC1AnalysisMQL_197])
       {
         continue;
       }
       bool coincidence_seen = false;
       for(int _u_MMuPC1AnalysisMQL_198 = 0; _u_MMuPC1AnalysisMQL_198 < cluster_size; _u_MMuPC1AnalysisMQL_198++)
       {
         if(_u_MMuPC1AnalysisMQL_198 > 0) break;
         int _u_MMuPC1AnalysisMQL_199 = cluster_members[_u_MMuPC1AnalysisMQL_198];
         double time_1 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_199].time;
         double time_2 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_197].time;
         int Xwire_1 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_199].Xwire;
         int Xwire_2 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_197].Xwire;
         double _u_MMuPC1AnalysisMQL_200 = time_1 - time_2;
         if(_u_MMuPC1AnalysisMQL_200 < -kMuPC1XClusterInterval)
         {
           continue;
         }
         coincidence_seen = true;
         if(!(Xwire_1 == Xwire_2))
         {
           continue;
         }
         cluster_members[cluster_size++] = _u_MMuPC1AnalysisMQL_197;
         _u_MMuPC1AnalysisMQL_195[_u_MMuPC1AnalysisMQL_197] = true;
         break;
       }
       if(!coincidence_seen)
       {
         break;
       }
     }
     double time_min = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_196].time;
     double time_max = time_min;
     double time_sum = 0;
     int Xwire_min = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_196].Xwire;
     int Xwire_max = Xwire_min;
     int Xwire_sum = 0;
     for(int _u_MMuPC1AnalysisMQL_198 = 0; _u_MMuPC1AnalysisMQL_198 < cluster_size; _u_MMuPC1AnalysisMQL_198++)
     {
       int _u_MMuPC1AnalysisMQL_199 = cluster_members[_u_MMuPC1AnalysisMQL_198];
       time = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_199].time;
       time_min = MIN(time_min, time);
       time_max = MAX(time_max, time);
       time_sum = time_sum + time;
       Xwire = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_199].Xwire;
       Xwire_min = MIN(Xwire_min, Xwire);
       Xwire_max = MAX(Xwire_max, Xwire);
       Xwire_sum = Xwire_sum + Xwire;
     }
     double time_1 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_196].time;
     double time_avg = time_sum/((double)cluster_size);
     double time_width = time_max - time_min + 1;
     int Xwire_1 = _t_muPC1X_SC[_u_MMuPC1AnalysisMQL_196].Xwire;
     double Xwire_avg = Xwire_sum/((double)cluster_size);
     int Xwire_width = Xwire_max - Xwire_min + 1;
     {
       double time = time_min;
       int Xwire = Xwire_1;
       int _u_MMuPC1AnalysisMQL_201 = _t_muPC1X_AD.next();
       _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_201].time = time;
       _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_201].Xwire = Xwire;
     }
   }
   _t_muPC1X_AD.sort(_u_MMuPC1AnalysisMQL_48);
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_202 = 0; _u_MMuPC1AnalysisMQL_202 < _t_muPC1X_AD.size(); _u_MMuPC1AnalysisMQL_202++)
     {
       double time = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_202].time;
       int Xwire = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_202].Xwire;
       {
         double time_1 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_202].time;
         int Xwire_1 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_202].Xwire;
         if(!_u_MMuPC1AnalysisMQL_109)
         {
           if(!_t_muPC1X_AD.checkSort(_u_MMuPC1AnalysisMQL_50))
           {
             printf("Warning: table muPC1X_AD is not sorted on time_2 as required for join with muPC1X_AD (_u_MMuPC1AnalysisMQL_50)\n");
           }
           _u_MMuPC1AnalysisMQL_109 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_110)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_108))
           {
             printf("Warning: table muPC1X_AD is not sorted on time_1 as required for join with muPC1X_AD\n");
             _u_MMuPC1AnalysisMQL_110 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_108 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_107 < _t_muPC1X_AD.size(); _u_MMuPC1AnalysisMQL_107++)
         {
           double time_2 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_107].time;
           int Xwire_2 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_107].Xwire;
           double _u_MMuPC1AnalysisMQL_203 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_203 < 1)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_205 = _u_MMuPC1AnalysisMQL_107; _u_MMuPC1AnalysisMQL_205 < _t_muPC1X_AD.size(); _u_MMuPC1AnalysisMQL_205++)
         {
           double time_2 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_205].time;
           int Xwire_2 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_205].Xwire;
           double _u_MMuPC1AnalysisMQL_203 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_203 < -50005)
           {
             break;
           }
           {
             double time_1_0 = time_1;
             int Xwire_1_0 = Xwire_1;
             double time_2_0 = time_2;
             int Xwire_2_0 = Xwire_2;
             double time_1 = time_1_0;
             int Xwire_1 = Xwire_1_0;
             double time_2 = time_2_0;
             int Xwire_2 = Xwire_2_0;
             if(Tier3)
             {
               if((time_2 - time_1) >= 0)
               {
                 _h_muPC1_X_AD_autocorr_all_1D->Fill(time_2 - time_1);
               }
             }
             if(Tier3)
             {
               if(((time_2 - time_1) >= 0) && (Xwire_1==Xwire_2))
               {
                 _h_muPC1_X_AD_autocorr_2D->Fill(time_2 - time_1, Xwire_1);
               }
             }
           }
         }
       }
     }
   }
   bool _u_MMuPC1AnalysisMQL_206[_t_muPC1X_AD.size()];
   memset(_u_MMuPC1AnalysisMQL_206, 0, sizeof(_u_MMuPC1AnalysisMQL_206));
   if(!_t_muPC1X_AD.checkSort(_u_MMuPC1AnalysisMQL_51))
   {
     printf("Warning: table muPC1X_AD is not sorted on time_1 as required for cluster.\n");
   }
   for(int _u_MMuPC1AnalysisMQL_207 = 0; _u_MMuPC1AnalysisMQL_207 < _t_muPC1X_AD.size(); _u_MMuPC1AnalysisMQL_207++)
   {
     double time = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_207].time;
     int Xwire = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_207].Xwire;
     if(_u_MMuPC1AnalysisMQL_206[_u_MMuPC1AnalysisMQL_207])
     {
       continue;
     }
     _u_MMuPC1AnalysisMQL_206[_u_MMuPC1AnalysisMQL_207] = true;
     int cluster_size = 1;
     int cluster_members[_t_muPC1X_AD.size()];
     cluster_members[0] = _u_MMuPC1AnalysisMQL_207;
     for(int _u_MMuPC1AnalysisMQL_208 = _u_MMuPC1AnalysisMQL_207 + 1; _u_MMuPC1AnalysisMQL_208 < _t_muPC1X_AD.size(); _u_MMuPC1AnalysisMQL_208++)
     {
       if(_u_MMuPC1AnalysisMQL_206[_u_MMuPC1AnalysisMQL_208])
       {
         continue;
       }
       bool coincidence_seen = false;
       for(int _u_MMuPC1AnalysisMQL_209 = 0; _u_MMuPC1AnalysisMQL_209 < cluster_size; _u_MMuPC1AnalysisMQL_209++)
       {
         int _u_MMuPC1AnalysisMQL_210 = cluster_members[_u_MMuPC1AnalysisMQL_209];
         double time_1 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_210].time;
         double time_2 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_208].time;
         int Xwire_1 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_210].Xwire;
         int Xwire_2 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_208].Xwire;
         double _u_MMuPC1AnalysisMQL_211 = time_1 - time_2;
         if(_u_MMuPC1AnalysisMQL_211 < -kMuPC1XClusterInterval)
         {
           continue;
         }
         coincidence_seen = true;
         if(!(((abs(Xwire_1-Xwire_2)-1) == 0)))
         {
           continue;
         }
         cluster_members[cluster_size++] = _u_MMuPC1AnalysisMQL_208;
         _u_MMuPC1AnalysisMQL_206[_u_MMuPC1AnalysisMQL_208] = true;
         _u_MMuPC1AnalysisMQL_208 = _u_MMuPC1AnalysisMQL_207;
         break;
       }
       if(!coincidence_seen)
       {
         break;
       }
     }
     double time_min = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_207].time;
     double time_max = time_min;
     double time_sum = 0;
     int Xwire_min = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_207].Xwire;
     int Xwire_max = Xwire_min;
     int Xwire_sum = 0;
     for(int _u_MMuPC1AnalysisMQL_209 = 0; _u_MMuPC1AnalysisMQL_209 < cluster_size; _u_MMuPC1AnalysisMQL_209++)
     {
       int _u_MMuPC1AnalysisMQL_210 = cluster_members[_u_MMuPC1AnalysisMQL_209];
       time = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_210].time;
       time_min = MIN(time_min, time);
       time_max = MAX(time_max, time);
       time_sum = time_sum + time;
       Xwire = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_210].Xwire;
       Xwire_min = MIN(Xwire_min, Xwire);
       Xwire_max = MAX(Xwire_max, Xwire);
       Xwire_sum = Xwire_sum + Xwire;
     }
     double time_1 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_207].time;
     double time_avg = time_sum/((double)cluster_size);
     double time_width = time_max - time_min + 1;
     int Xwire_1 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_207].Xwire;
     double Xwire_avg = Xwire_sum/((double)cluster_size);
     int Xwire_width = Xwire_max - Xwire_min + 1;
     {
       double time = time_min;
       int Xwire_min_0 = Xwire_min;
       int Xwire_max_0 = Xwire_max;
       int Xwire_min = Xwire_min_0;
       int Xwire_max = Xwire_max_0;
       int _u_MMuPC1AnalysisMQL_212 = _t_muPC1X_cluster_contiguous.next();
       _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_212].time = time;
       _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_212].Xwire_min = Xwire_min_0;
       _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_212].Xwire_max = Xwire_max_0;
     }
   }
   _t_muPC1X_cluster_contiguous.sort(_u_MMuPC1AnalysisMQL_52);
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_213 = 0; _u_MMuPC1AnalysisMQL_213 < _t_muPC1X_cluster_contiguous.size(); _u_MMuPC1AnalysisMQL_213++)
     {
       double time = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_213].time;
       int Xwire_min = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_213].Xwire_min;
       int Xwire_max = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_213].Xwire_max;
       {
         double time_1 = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_213].time;
         int Xwire_min_1 = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_213].Xwire_min;
         int Xwire_max_1 = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_213].Xwire_max;
         if(!_u_MMuPC1AnalysisMQL_114)
         {
           if(!_t_muPC1X_cluster_contiguous.checkSort(_u_MMuPC1AnalysisMQL_54))
           {
             printf("Warning: table muPC1X_cluster_contiguous is not sorted on time_2 as required for join with muPC1X_cluster_contiguous (_u_MMuPC1AnalysisMQL_54)\n");
           }
           _u_MMuPC1AnalysisMQL_114 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_115)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_113))
           {
             printf("Warning: table muPC1X_cluster_contiguous is not sorted on time_1 as required for join with muPC1X_cluster_contiguous\n");
             _u_MMuPC1AnalysisMQL_115 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_113 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_112 < _t_muPC1X_cluster_contiguous.size(); _u_MMuPC1AnalysisMQL_112++)
         {
           double time_2 = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_112].time;
           int Xwire_min_2 = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_112].Xwire_min;
           int Xwire_max_2 = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_112].Xwire_max;
           double _u_MMuPC1AnalysisMQL_214 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_214 < 5)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_216 = _u_MMuPC1AnalysisMQL_112; _u_MMuPC1AnalysisMQL_216 < _t_muPC1X_cluster_contiguous.size(); _u_MMuPC1AnalysisMQL_216++)
         {
           double time_2 = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_216].time;
           int Xwire_min_2 = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_216].Xwire_min;
           int Xwire_max_2 = _t_muPC1X_cluster_contiguous[_u_MMuPC1AnalysisMQL_216].Xwire_max;
           double _u_MMuPC1AnalysisMQL_214 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_214 < -kMuPC1XClusterInterval)
           {
             break;
           }
           if(!((time_1==time_2) && (Xwire_min_1==Xwire_min_2) && (Xwire_max_1==Xwire_max_2)) &&
           ((Xwire_min_1 > Xwire_max_2) || (Xwire_min_2 > Xwire_max_1)))
           {
             {
               int cluster_sep = MIN(abs(Xwire_min_1-Xwire_max_2),abs(Xwire_min_2-Xwire_max_1));
               if(Tier3)
               {
                 _h_muPC1_X_cluster_contiguous_separation->Fill(cluster_sep);
               }
             }
           }
         }
       }
     }
   }
   bool _u_MMuPC1AnalysisMQL_217[_t_muPC1X_AD.size()];
   memset(_u_MMuPC1AnalysisMQL_217, 0, sizeof(_u_MMuPC1AnalysisMQL_217));
   if(!_t_muPC1X_AD.checkSort(_u_MMuPC1AnalysisMQL_55))
   {
     printf("Warning: table muPC1X_AD is not sorted on time_1 as required for cluster.\n");
   }
   for(int _u_MMuPC1AnalysisMQL_218 = 0; _u_MMuPC1AnalysisMQL_218 < _t_muPC1X_AD.size(); _u_MMuPC1AnalysisMQL_218++)
   {
     double time = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_218].time;
     int Xwire = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_218].Xwire;
     if(_u_MMuPC1AnalysisMQL_217[_u_MMuPC1AnalysisMQL_218])
     {
       continue;
     }
     _u_MMuPC1AnalysisMQL_217[_u_MMuPC1AnalysisMQL_218] = true;
     int cluster_size = 1;
     int cluster_members[_t_muPC1X_AD.size()];
     cluster_members[0] = _u_MMuPC1AnalysisMQL_218;
     for(int _u_MMuPC1AnalysisMQL_219 = _u_MMuPC1AnalysisMQL_218 + 1; _u_MMuPC1AnalysisMQL_219 < _t_muPC1X_AD.size(); _u_MMuPC1AnalysisMQL_219++)
     {
       if(_u_MMuPC1AnalysisMQL_217[_u_MMuPC1AnalysisMQL_219])
       {
         continue;
       }
       bool coincidence_seen = false;
       for(int _u_MMuPC1AnalysisMQL_220 = 0; _u_MMuPC1AnalysisMQL_220 < cluster_size; _u_MMuPC1AnalysisMQL_220++)
       {
         int _u_MMuPC1AnalysisMQL_221 = cluster_members[_u_MMuPC1AnalysisMQL_220];
         double time_1 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_221].time;
         double time_2 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_219].time;
         int Xwire_1 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_221].Xwire;
         int Xwire_2 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_219].Xwire;
         double _u_MMuPC1AnalysisMQL_222 = time_1 - time_2;
         if(_u_MMuPC1AnalysisMQL_222 < -kMuPC1XClusterInterval)
         {
           continue;
         }
         coincidence_seen = true;
         if(!((abs(Xwire_1-Xwire_2)-1) <= kMuPC1XClusterMaxGap))
         {
           continue;
         }
         cluster_members[cluster_size++] = _u_MMuPC1AnalysisMQL_219;
         _u_MMuPC1AnalysisMQL_217[_u_MMuPC1AnalysisMQL_219] = true;
         _u_MMuPC1AnalysisMQL_219 = _u_MMuPC1AnalysisMQL_218;
         break;
       }
       if(!coincidence_seen)
       {
         break;
       }
     }
     double time_min = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_218].time;
     double time_max = time_min;
     double time_sum = 0;
     int Xwire_min = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_218].Xwire;
     int Xwire_max = Xwire_min;
     int Xwire_sum = 0;
     for(int _u_MMuPC1AnalysisMQL_220 = 0; _u_MMuPC1AnalysisMQL_220 < cluster_size; _u_MMuPC1AnalysisMQL_220++)
     {
       int _u_MMuPC1AnalysisMQL_221 = cluster_members[_u_MMuPC1AnalysisMQL_220];
       time = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_221].time;
       time_min = MIN(time_min, time);
       time_max = MAX(time_max, time);
       time_sum = time_sum + time;
       Xwire = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_221].Xwire;
       Xwire_min = MIN(Xwire_min, Xwire);
       Xwire_max = MAX(Xwire_max, Xwire);
       Xwire_sum = Xwire_sum + Xwire;
     }
     double time_1 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_218].time;
     double time_avg = time_sum/((double)cluster_size);
     double time_width = time_max - time_min + 1;
     int Xwire_1 = _t_muPC1X_AD[_u_MMuPC1AnalysisMQL_218].Xwire;
     double Xwire_avg = Xwire_sum/((double)cluster_size);
     int Xwire_width = Xwire_max - Xwire_min + 1;
     {
       double time = time_min;
       double Xwire = Xwire_avg;
       int cluster_size_0 = cluster_size;
       int cluster_width = Xwire_width;
       int cluster_size = cluster_size_0;
       if(Tier1)
       {
         _h_muPC1_X_final_cluster_size->Fill(cluster_size);
       }
       if(Tier1)
       {
         _h_muPC1_X_final_cluster_width->Fill(cluster_width);
       }
       if(Tier1)
       {
         _h_muPC1_X_final_cluster_avg->Fill(Xwire);
       }
       {
         double Xwire_0 = Xwire;
         double muPC1Time = time;
         double Xwire = Xwire_0;
         int _u_MMuPC1AnalysisMQL_223 = _t_muPC1X_export.next();
         _t_muPC1X_export[_u_MMuPC1AnalysisMQL_223].Xwire = Xwire_0;
         _t_muPC1X_export[_u_MMuPC1AnalysisMQL_223].muPC1Time = muPC1Time;
       }
       int _u_MMuPC1AnalysisMQL_224 = _t_muPC1X.next();
       _t_muPC1X[_u_MMuPC1AnalysisMQL_224].time = time;
       _t_muPC1X[_u_MMuPC1AnalysisMQL_224].Xwire = Xwire;
       _t_muPC1X[_u_MMuPC1AnalysisMQL_224].cluster_size = cluster_size_0;
       _t_muPC1X[_u_MMuPC1AnalysisMQL_224].cluster_width = cluster_width;
     }
   }
   _t_muPC1X.sort(_u_MMuPC1AnalysisMQL_56);
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_225 = 0; _u_MMuPC1AnalysisMQL_225 < _t_muPC1X.size(); _u_MMuPC1AnalysisMQL_225++)
     {
       double time = _t_muPC1X[_u_MMuPC1AnalysisMQL_225].time;
       double Xwire = _t_muPC1X[_u_MMuPC1AnalysisMQL_225].Xwire;
       int cluster_size = _t_muPC1X[_u_MMuPC1AnalysisMQL_225].cluster_size;
       int cluster_width = _t_muPC1X[_u_MMuPC1AnalysisMQL_225].cluster_width;
       {
         double time_1 = _t_muPC1X[_u_MMuPC1AnalysisMQL_225].time;
         double Xwire_1 = _t_muPC1X[_u_MMuPC1AnalysisMQL_225].Xwire;
         int cluster_size_1 = _t_muPC1X[_u_MMuPC1AnalysisMQL_225].cluster_size;
         int cluster_width_1 = _t_muPC1X[_u_MMuPC1AnalysisMQL_225].cluster_width;
         if(!_u_MMuPC1AnalysisMQL_119)
         {
           if(!_t_muPC1X.checkSort(_u_MMuPC1AnalysisMQL_58))
           {
             printf("Warning: table muPC1X is not sorted on time_2 as required for join with muPC1X (_u_MMuPC1AnalysisMQL_58)\n");
           }
           _u_MMuPC1AnalysisMQL_119 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_120)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_118))
           {
             printf("Warning: table muPC1X is not sorted on time_1 as required for join with muPC1X\n");
             _u_MMuPC1AnalysisMQL_120 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_118 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_117 < _t_muPC1X.size(); _u_MMuPC1AnalysisMQL_117++)
         {
           double time_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_117].time;
           double Xwire_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_117].Xwire;
           int cluster_size_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_117].cluster_size;
           int cluster_width_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_117].cluster_width;
           double _u_MMuPC1AnalysisMQL_226 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_226 < 1)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_228 = _u_MMuPC1AnalysisMQL_117; _u_MMuPC1AnalysisMQL_228 < _t_muPC1X.size(); _u_MMuPC1AnalysisMQL_228++)
         {
           double time_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_228].time;
           double Xwire_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_228].Xwire;
           int cluster_size_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_228].cluster_size;
           int cluster_width_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_228].cluster_width;
           double _u_MMuPC1AnalysisMQL_226 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_226 < -50005)
           {
             break;
           }
           {
             double time_1_0 = time_1;
             double time_2_0 = time_2;
             double time_1 = time_1_0;
             double time_2 = time_2_0;
             if(Tier3)
             {
               if((time_2 - time_1) >= 0)
               {
                 _h_muPC1_X_final_cluster_autocorr_all_1D->Fill(time_2 - time_1);
               }
             }
           }
         }
       }
     }
   }
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_229 = 0; _u_MMuPC1AnalysisMQL_229 < _t_muPC1X.size(); _u_MMuPC1AnalysisMQL_229++)
     {
       double time = _t_muPC1X[_u_MMuPC1AnalysisMQL_229].time;
       double Xwire = _t_muPC1X[_u_MMuPC1AnalysisMQL_229].Xwire;
       int cluster_size = _t_muPC1X[_u_MMuPC1AnalysisMQL_229].cluster_size;
       int cluster_width = _t_muPC1X[_u_MMuPC1AnalysisMQL_229].cluster_width;
       {
         double time_1 = _t_muPC1X[_u_MMuPC1AnalysisMQL_229].time;
         double Xwire_1 = _t_muPC1X[_u_MMuPC1AnalysisMQL_229].Xwire;
         int cluster_size_1 = _t_muPC1X[_u_MMuPC1AnalysisMQL_229].cluster_size;
         int cluster_width_1 = _t_muPC1X[_u_MMuPC1AnalysisMQL_229].cluster_width;
         if(!_u_MMuPC1AnalysisMQL_123)
         {
           if(!_t_muPC1X.checkSort(_u_MMuPC1AnalysisMQL_60))
           {
             printf("Warning: table muPC1X is not sorted on time_2 as required for join with muPC1X (_u_MMuPC1AnalysisMQL_60)\n");
           }
           _u_MMuPC1AnalysisMQL_123 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_124)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_122))
           {
             printf("Warning: table muPC1X is not sorted on time_1 as required for join with muPC1X\n");
             _u_MMuPC1AnalysisMQL_124 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_122 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_121 < _t_muPC1X.size(); _u_MMuPC1AnalysisMQL_121++)
         {
           double time_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_121].time;
           double Xwire_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_121].Xwire;
           int cluster_size_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_121].cluster_size;
           int cluster_width_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_121].cluster_width;
           double _u_MMuPC1AnalysisMQL_230 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_230 < 1)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_232 = _u_MMuPC1AnalysisMQL_121; _u_MMuPC1AnalysisMQL_232 < _t_muPC1X.size(); _u_MMuPC1AnalysisMQL_232++)
         {
           double time_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_232].time;
           double Xwire_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_232].Xwire;
           int cluster_size_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_232].cluster_size;
           int cluster_width_2 = _t_muPC1X[_u_MMuPC1AnalysisMQL_232].cluster_width;
           double _u_MMuPC1AnalysisMQL_230 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_230 < -150)
           {
             break;
           }
           {
             double time1 = time_1;
             double time2 = time_2;
             double wire_diff = fabs(Xwire_1-Xwire_2);
             if(Tier3)
             {
               if(fabs(time_2-time_1)>=0)
               {
                 _h_muPC1_X_final_cluster_autocorr_spatial_all_1D->Fill(wire_diff);
               }
             }
           }
         }
       }
     }
   }
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_233 = 0; _u_MMuPC1AnalysisMQL_233 < _t_muPC1Y_raw.size(); _u_MMuPC1AnalysisMQL_233++)
     {
       double time = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_233].time;
       int Ywire = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_233].Ywire;
       {
         double time_1 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_233].time;
         int Ywire_1 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_233].Ywire;
         if(!_u_MMuPC1AnalysisMQL_127)
         {
           if(!_t_muPC1Y_raw.checkSort(_u_MMuPC1AnalysisMQL_62))
           {
             printf("Warning: table muPC1Y_raw is not sorted on time_2 as required for join with muPC1Y_raw (_u_MMuPC1AnalysisMQL_62)\n");
           }
           _u_MMuPC1AnalysisMQL_127 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_128)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_126))
           {
             printf("Warning: table muPC1Y_raw is not sorted on time_1 as required for join with muPC1Y_raw\n");
             _u_MMuPC1AnalysisMQL_128 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_126 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_125 < _t_muPC1Y_raw.size(); _u_MMuPC1AnalysisMQL_125++)
         {
           double time_2 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_125].time;
           int Ywire_2 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_125].Ywire;
           double _u_MMuPC1AnalysisMQL_234 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_234 < 1)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_236 = _u_MMuPC1AnalysisMQL_125; _u_MMuPC1AnalysisMQL_236 < _t_muPC1Y_raw.size(); _u_MMuPC1AnalysisMQL_236++)
         {
           double time_2 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_236].time;
           int Ywire_2 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_236].Ywire;
           double _u_MMuPC1AnalysisMQL_234 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_234 < -50005)
           {
             break;
           }
           {
             double time_1_0 = time_1;
             int Ywire_1_0 = Ywire_1;
             double time_2_0 = time_2;
             int Ywire_2_0 = Ywire_2;
             double time_1 = time_1_0;
             int Ywire_1 = Ywire_1_0;
             double time_2 = time_2_0;
             int Ywire_2 = Ywire_2_0;
             if(Tier3)
             {
               _h_muPC1_Y_raw_autosingles_2D->Fill(Ywire_1, Ywire_2);
             }
             if(Tier3)
             {
               if((time_2 - time_1) >= 0)
               {
                 _h_muPC1_Y_raw_autocorr_all_1D->Fill(time_2 - time_1);
               }
             }
             if(Tier3)
             {
               if(((time_2 - time_1) >= 0) && (Ywire_1==Ywire_2))
               {
                 _h_muPC1_Y_raw_autocorr_2D->Fill(time_2 - time_1, Ywire_1);
               }
             }
           }
         }
       }
     }
   }
   bool _u_MMuPC1AnalysisMQL_237[_t_muPC1Y_raw.size()];
   memset(_u_MMuPC1AnalysisMQL_237, 0, sizeof(_u_MMuPC1AnalysisMQL_237));
   if(!_t_muPC1Y_raw.checkSort(_u_MMuPC1AnalysisMQL_63))
   {
     printf("Warning: table muPC1Y_raw is not sorted on time_1 as required for cluster.\n");
   }
   for(int _u_MMuPC1AnalysisMQL_238 = 0; _u_MMuPC1AnalysisMQL_238 < _t_muPC1Y_raw.size(); _u_MMuPC1AnalysisMQL_238++)
   {
     double time = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_238].time;
     int Ywire = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_238].Ywire;
     if(_u_MMuPC1AnalysisMQL_237[_u_MMuPC1AnalysisMQL_238])
     {
       continue;
     }
     _u_MMuPC1AnalysisMQL_237[_u_MMuPC1AnalysisMQL_238] = true;
     int cluster_size = 1;
     int cluster_members[_t_muPC1Y_raw.size()];
     cluster_members[0] = _u_MMuPC1AnalysisMQL_238;
     for(int _u_MMuPC1AnalysisMQL_239 = _u_MMuPC1AnalysisMQL_238 + 1; _u_MMuPC1AnalysisMQL_239 < _t_muPC1Y_raw.size(); _u_MMuPC1AnalysisMQL_239++)
     {
       if(_u_MMuPC1AnalysisMQL_237[_u_MMuPC1AnalysisMQL_239])
       {
         continue;
       }
       bool coincidence_seen = false;
       for(int _u_MMuPC1AnalysisMQL_240 = 0; _u_MMuPC1AnalysisMQL_240 < cluster_size; _u_MMuPC1AnalysisMQL_240++)
       {
         int _u_MMuPC1AnalysisMQL_241 = cluster_members[_u_MMuPC1AnalysisMQL_240];
         double time_1 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_241].time;
         double time_2 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_239].time;
         int Ywire_1 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_241].Ywire;
         int Ywire_2 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_239].Ywire;
         double _u_MMuPC1AnalysisMQL_242 = time_1 - time_2;
         if(_u_MMuPC1AnalysisMQL_242 < -1000)
         {
           continue;
         }
         coincidence_seen = true;
         cluster_members[cluster_size++] = _u_MMuPC1AnalysisMQL_239;
         _u_MMuPC1AnalysisMQL_237[_u_MMuPC1AnalysisMQL_239] = true;
         _u_MMuPC1AnalysisMQL_239 = _u_MMuPC1AnalysisMQL_238;
         break;
       }
       if(!coincidence_seen)
       {
         break;
       }
     }
     double time_min = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_238].time;
     double time_max = time_min;
     double time_sum = 0;
     int Ywire_min = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_238].Ywire;
     int Ywire_max = Ywire_min;
     int Ywire_sum = 0;
     for(int _u_MMuPC1AnalysisMQL_240 = 0; _u_MMuPC1AnalysisMQL_240 < cluster_size; _u_MMuPC1AnalysisMQL_240++)
     {
       int _u_MMuPC1AnalysisMQL_241 = cluster_members[_u_MMuPC1AnalysisMQL_240];
       time = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_241].time;
       time_min = MIN(time_min, time);
       time_max = MAX(time_max, time);
       time_sum = time_sum + time;
       Ywire = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_241].Ywire;
       Ywire_min = MIN(Ywire_min, Ywire);
       Ywire_max = MAX(Ywire_max, Ywire);
       Ywire_sum = Ywire_sum + Ywire;
     }
     double time_1 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_238].time;
     double time_avg = time_sum/((double)cluster_size);
     double time_width = time_max - time_min + 1;
     int Ywire_1 = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_238].Ywire;
     double Ywire_avg = Ywire_sum/((double)cluster_size);
     int Ywire_width = Ywire_max - Ywire_min + 1;
     {
       double time = time_min;
       int cluster_size_0 = cluster_size;
       int cluster_size = cluster_size_0;
       if((cluster_size >= kMuPC1YSparkSizeCutoff))
       {
         {
           double time_0 = time;
           double time = time_0;
           if(Tier1)
           {
             _h_muPC1_spark_count_Ywires->Fill(1);
           }
           int _u_MMuPC1AnalysisMQL_243 = _t_muPC1Y_sparks.next();
           _t_muPC1Y_sparks[_u_MMuPC1AnalysisMQL_243].time = time_0;
         }
       }
       if(Tier1)
       {
         _h_muPC1_spark_search_Ywires->Fill(cluster_size);
       }
     }
   }
   _t_muPC1Y_spark_search.sort(_u_MMuPC1AnalysisMQL_64);
   for(int _u_MMuPC1AnalysisMQL_244 = 0; _u_MMuPC1AnalysisMQL_244 < _t_muPC1Y_raw.size(); _u_MMuPC1AnalysisMQL_244++)
   {
     double time = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_244].time;
     int Ywire = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_244].Ywire;
     {
       double muPC1Y_raw_time = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_244].time;
       int Ywire = _t_muPC1Y_raw[_u_MMuPC1AnalysisMQL_244].Ywire;
       if(!_u_MMuPC1AnalysisMQL_132)
       {
         if(!_t_muPC1Y_sparks.checkSort(_u_MMuPC1AnalysisMQL_66))
         {
           printf("Warning: table muPC1Y_sparks is not sorted on muPC1Y_sparks_time as required for join with muPC1Y_raw (_u_MMuPC1AnalysisMQL_66)\n");
         }
         _u_MMuPC1AnalysisMQL_132 = true;
       }
       else if(!_u_MMuPC1AnalysisMQL_133)
       {
         if(!(muPC1Y_raw_time >= _u_MMuPC1AnalysisMQL_131))
         {
           printf("Warning: table muPC1Y_raw is not sorted on muPC1Y_raw_time as required for join with muPC1Y_sparks\n");
           _u_MMuPC1AnalysisMQL_133 = true;
         }
       }
       _u_MMuPC1AnalysisMQL_131 = muPC1Y_raw_time;
       for( ; _u_MMuPC1AnalysisMQL_130 < _t_muPC1Y_sparks.size(); _u_MMuPC1AnalysisMQL_130++)
       {
         double muPC1Y_sparks_time = _t_muPC1Y_sparks[_u_MMuPC1AnalysisMQL_130].time;
         double _u_MMuPC1AnalysisMQL_245 = muPC1Y_raw_time - muPC1Y_sparks_time;
         if(_u_MMuPC1AnalysisMQL_245 < kSparkCutDeadtime)
         {
           break;
         }
       }
       _u_MMuPC1AnalysisMQL_134 = 0;
       for(int _u_MMuPC1AnalysisMQL_247 = _u_MMuPC1AnalysisMQL_130; _u_MMuPC1AnalysisMQL_247 < _t_muPC1Y_sparks.size(); _u_MMuPC1AnalysisMQL_247++)
       {
         double muPC1Y_sparks_time = _t_muPC1Y_sparks[_u_MMuPC1AnalysisMQL_247].time;
         double _u_MMuPC1AnalysisMQL_245 = muPC1Y_raw_time - muPC1Y_sparks_time;
         if(_u_MMuPC1AnalysisMQL_245 < -100)
         {
           break;
         }
         _u_MMuPC1AnalysisMQL_134++;
       }
       if(_u_MMuPC1AnalysisMQL_134 == 0)
       {
         {
           double time = muPC1Y_raw_time;
           int Ywire_0 = Ywire;
           int Ywire = Ywire_0;
           int _u_MMuPC1AnalysisMQL_248 = _t_muPC1Y_SC.next();
           _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_248].time = time;
           _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_248].Ywire = Ywire_0;
         }
       }
     }
   }
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_249 = 0; _u_MMuPC1AnalysisMQL_249 < _t_muPC1Y_SC.size(); _u_MMuPC1AnalysisMQL_249++)
     {
       double time = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_249].time;
       int Ywire = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_249].Ywire;
       {
         double time_1 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_249].time;
         int Ywire_1 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_249].Ywire;
         if(!_u_MMuPC1AnalysisMQL_137)
         {
           if(!_t_muPC1Y_SC.checkSort(_u_MMuPC1AnalysisMQL_68))
           {
             printf("Warning: table muPC1Y_SC is not sorted on time_2 as required for join with muPC1Y_SC (_u_MMuPC1AnalysisMQL_68)\n");
           }
           _u_MMuPC1AnalysisMQL_137 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_138)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_136))
           {
             printf("Warning: table muPC1Y_SC is not sorted on time_1 as required for join with muPC1Y_SC\n");
             _u_MMuPC1AnalysisMQL_138 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_136 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_135 < _t_muPC1Y_SC.size(); _u_MMuPC1AnalysisMQL_135++)
         {
           double time_2 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_135].time;
           int Ywire_2 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_135].Ywire;
           double _u_MMuPC1AnalysisMQL_250 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_250 < 1)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_252 = _u_MMuPC1AnalysisMQL_135; _u_MMuPC1AnalysisMQL_252 < _t_muPC1Y_SC.size(); _u_MMuPC1AnalysisMQL_252++)
         {
           double time_2 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_252].time;
           int Ywire_2 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_252].Ywire;
           double _u_MMuPC1AnalysisMQL_250 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_250 < -50005)
           {
             break;
           }
           {
             double time_1_0 = time_1;
             int Ywire_1_0 = Ywire_1;
             double time_2_0 = time_2;
             int Ywire_2_0 = Ywire_2;
             double time_1 = time_1_0;
             int Ywire_1 = Ywire_1_0;
             double time_2 = time_2_0;
             int Ywire_2 = Ywire_2_0;
             if(Tier3)
             {
               if((time_2 - time_1) >= 0)
               {
                 _h_muPC1_Y_SC_autocorr_all_1D->Fill(time_2 - time_1);
               }
             }
             if(Tier3)
             {
               if(((time_2 - time_1) >= 0) && (Ywire_1==Ywire_2))
               {
                 _h_muPC1_Y_SC_autocorr_2D->Fill(time_2 - time_1, Ywire_1);
               }
             }
           }
         }
       }
     }
   }
   bool _u_MMuPC1AnalysisMQL_253[_t_muPC1Y_SC.size()];
   memset(_u_MMuPC1AnalysisMQL_253, 0, sizeof(_u_MMuPC1AnalysisMQL_253));
   if(!_t_muPC1Y_SC.checkSort(_u_MMuPC1AnalysisMQL_69))
   {
     printf("Warning: table muPC1Y_SC is not sorted on time_1 as required for cluster.\n");
   }
   for(int _u_MMuPC1AnalysisMQL_254 = 0; _u_MMuPC1AnalysisMQL_254 < _t_muPC1Y_SC.size(); _u_MMuPC1AnalysisMQL_254++)
   {
     double time = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_254].time;
     int Ywire = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_254].Ywire;
     if(_u_MMuPC1AnalysisMQL_253[_u_MMuPC1AnalysisMQL_254])
     {
       continue;
     }
     _u_MMuPC1AnalysisMQL_253[_u_MMuPC1AnalysisMQL_254] = true;
     int cluster_size = 1;
     int cluster_members[_t_muPC1Y_SC.size()];
     cluster_members[0] = _u_MMuPC1AnalysisMQL_254;
     for(int _u_MMuPC1AnalysisMQL_255 = _u_MMuPC1AnalysisMQL_254 + 1; _u_MMuPC1AnalysisMQL_255 < _t_muPC1Y_SC.size(); _u_MMuPC1AnalysisMQL_255++)
     {
       if(_u_MMuPC1AnalysisMQL_253[_u_MMuPC1AnalysisMQL_255])
       {
         continue;
       }
       bool coincidence_seen = false;
       for(int _u_MMuPC1AnalysisMQL_256 = 0; _u_MMuPC1AnalysisMQL_256 < cluster_size; _u_MMuPC1AnalysisMQL_256++)
       {
         if(_u_MMuPC1AnalysisMQL_256 > 0) break;
         int _u_MMuPC1AnalysisMQL_257 = cluster_members[_u_MMuPC1AnalysisMQL_256];
         double time_1 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_257].time;
         double time_2 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_255].time;
         int Ywire_1 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_257].Ywire;
         int Ywire_2 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_255].Ywire;
         double _u_MMuPC1AnalysisMQL_258 = time_1 - time_2;
         if(_u_MMuPC1AnalysisMQL_258 < -kMuPC1YClusterInterval)
         {
           continue;
         }
         coincidence_seen = true;
         if(!(Ywire_1 == Ywire_2))
         {
           continue;
         }
         cluster_members[cluster_size++] = _u_MMuPC1AnalysisMQL_255;
         _u_MMuPC1AnalysisMQL_253[_u_MMuPC1AnalysisMQL_255] = true;
         break;
       }
       if(!coincidence_seen)
       {
         break;
       }
     }
     double time_min = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_254].time;
     double time_max = time_min;
     double time_sum = 0;
     int Ywire_min = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_254].Ywire;
     int Ywire_max = Ywire_min;
     int Ywire_sum = 0;
     for(int _u_MMuPC1AnalysisMQL_256 = 0; _u_MMuPC1AnalysisMQL_256 < cluster_size; _u_MMuPC1AnalysisMQL_256++)
     {
       int _u_MMuPC1AnalysisMQL_257 = cluster_members[_u_MMuPC1AnalysisMQL_256];
       time = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_257].time;
       time_min = MIN(time_min, time);
       time_max = MAX(time_max, time);
       time_sum = time_sum + time;
       Ywire = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_257].Ywire;
       Ywire_min = MIN(Ywire_min, Ywire);
       Ywire_max = MAX(Ywire_max, Ywire);
       Ywire_sum = Ywire_sum + Ywire;
     }
     double time_1 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_254].time;
     double time_avg = time_sum/((double)cluster_size);
     double time_width = time_max - time_min + 1;
     int Ywire_1 = _t_muPC1Y_SC[_u_MMuPC1AnalysisMQL_254].Ywire;
     double Ywire_avg = Ywire_sum/((double)cluster_size);
     int Ywire_width = Ywire_max - Ywire_min + 1;
     {
       double time = time_min;
       int Ywire = Ywire_1;
       int _u_MMuPC1AnalysisMQL_259 = _t_muPC1Y_AD.next();
       _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_259].time = time;
       _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_259].Ywire = Ywire;
     }
   }
   _t_muPC1Y_AD.sort(_u_MMuPC1AnalysisMQL_70);
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_260 = 0; _u_MMuPC1AnalysisMQL_260 < _t_muPC1Y_AD.size(); _u_MMuPC1AnalysisMQL_260++)
     {
       double time = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_260].time;
       int Ywire = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_260].Ywire;
       {
         double time_1 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_260].time;
         int Ywire_1 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_260].Ywire;
         if(!_u_MMuPC1AnalysisMQL_142)
         {
           if(!_t_muPC1Y_AD.checkSort(_u_MMuPC1AnalysisMQL_72))
           {
             printf("Warning: table muPC1Y_AD is not sorted on time_2 as required for join with muPC1Y_AD (_u_MMuPC1AnalysisMQL_72)\n");
           }
           _u_MMuPC1AnalysisMQL_142 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_143)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_141))
           {
             printf("Warning: table muPC1Y_AD is not sorted on time_1 as required for join with muPC1Y_AD\n");
             _u_MMuPC1AnalysisMQL_143 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_141 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_140 < _t_muPC1Y_AD.size(); _u_MMuPC1AnalysisMQL_140++)
         {
           double time_2 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_140].time;
           int Ywire_2 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_140].Ywire;
           double _u_MMuPC1AnalysisMQL_261 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_261 < 1)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_263 = _u_MMuPC1AnalysisMQL_140; _u_MMuPC1AnalysisMQL_263 < _t_muPC1Y_AD.size(); _u_MMuPC1AnalysisMQL_263++)
         {
           double time_2 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_263].time;
           int Ywire_2 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_263].Ywire;
           double _u_MMuPC1AnalysisMQL_261 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_261 < -50005)
           {
             break;
           }
           {
             double time_1_0 = time_1;
             int Ywire_1_0 = Ywire_1;
             double time_2_0 = time_2;
             int Ywire_2_0 = Ywire_2;
             double time_1 = time_1_0;
             int Ywire_1 = Ywire_1_0;
             double time_2 = time_2_0;
             int Ywire_2 = Ywire_2_0;
             if(Tier3)
             {
               if((time_2 - time_1) >= 0)
               {
                 _h_muPC1_Y_AD_autocorr_all_1D->Fill(time_2 - time_1);
               }
             }
             if(Tier3)
             {
               if(((time_2 - time_1) >= 0) && (Ywire_1==Ywire_2))
               {
                 _h_muPC1_Y_AD_autocorr_2D->Fill(time_2 - time_1, Ywire_1);
               }
             }
           }
         }
       }
     }
   }
   bool _u_MMuPC1AnalysisMQL_264[_t_muPC1Y_AD.size()];
   memset(_u_MMuPC1AnalysisMQL_264, 0, sizeof(_u_MMuPC1AnalysisMQL_264));
   if(!_t_muPC1Y_AD.checkSort(_u_MMuPC1AnalysisMQL_73))
   {
     printf("Warning: table muPC1Y_AD is not sorted on time_1 as required for cluster.\n");
   }
   for(int _u_MMuPC1AnalysisMQL_265 = 0; _u_MMuPC1AnalysisMQL_265 < _t_muPC1Y_AD.size(); _u_MMuPC1AnalysisMQL_265++)
   {
     double time = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_265].time;
     int Ywire = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_265].Ywire;
     if(_u_MMuPC1AnalysisMQL_264[_u_MMuPC1AnalysisMQL_265])
     {
       continue;
     }
     _u_MMuPC1AnalysisMQL_264[_u_MMuPC1AnalysisMQL_265] = true;
     int cluster_size = 1;
     int cluster_members[_t_muPC1Y_AD.size()];
     cluster_members[0] = _u_MMuPC1AnalysisMQL_265;
     for(int _u_MMuPC1AnalysisMQL_266 = _u_MMuPC1AnalysisMQL_265 + 1; _u_MMuPC1AnalysisMQL_266 < _t_muPC1Y_AD.size(); _u_MMuPC1AnalysisMQL_266++)
     {
       if(_u_MMuPC1AnalysisMQL_264[_u_MMuPC1AnalysisMQL_266])
       {
         continue;
       }
       bool coincidence_seen = false;
       for(int _u_MMuPC1AnalysisMQL_267 = 0; _u_MMuPC1AnalysisMQL_267 < cluster_size; _u_MMuPC1AnalysisMQL_267++)
       {
         int _u_MMuPC1AnalysisMQL_268 = cluster_members[_u_MMuPC1AnalysisMQL_267];
         double time_1 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_268].time;
         double time_2 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_266].time;
         int Ywire_1 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_268].Ywire;
         int Ywire_2 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_266].Ywire;
         double _u_MMuPC1AnalysisMQL_269 = time_1 - time_2;
         if(_u_MMuPC1AnalysisMQL_269 < -kMuPC1YClusterInterval)
         {
           continue;
         }
         coincidence_seen = true;
         if(!(((abs(Ywire_1-Ywire_2)-1) == 0)))
         {
           continue;
         }
         cluster_members[cluster_size++] = _u_MMuPC1AnalysisMQL_266;
         _u_MMuPC1AnalysisMQL_264[_u_MMuPC1AnalysisMQL_266] = true;
         _u_MMuPC1AnalysisMQL_266 = _u_MMuPC1AnalysisMQL_265;
         break;
       }
       if(!coincidence_seen)
       {
         break;
       }
     }
     double time_min = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_265].time;
     double time_max = time_min;
     double time_sum = 0;
     int Ywire_min = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_265].Ywire;
     int Ywire_max = Ywire_min;
     int Ywire_sum = 0;
     for(int _u_MMuPC1AnalysisMQL_267 = 0; _u_MMuPC1AnalysisMQL_267 < cluster_size; _u_MMuPC1AnalysisMQL_267++)
     {
       int _u_MMuPC1AnalysisMQL_268 = cluster_members[_u_MMuPC1AnalysisMQL_267];
       time = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_268].time;
       time_min = MIN(time_min, time);
       time_max = MAX(time_max, time);
       time_sum = time_sum + time;
       Ywire = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_268].Ywire;
       Ywire_min = MIN(Ywire_min, Ywire);
       Ywire_max = MAX(Ywire_max, Ywire);
       Ywire_sum = Ywire_sum + Ywire;
     }
     double time_1 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_265].time;
     double time_avg = time_sum/((double)cluster_size);
     double time_width = time_max - time_min + 1;
     int Ywire_1 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_265].Ywire;
     double Ywire_avg = Ywire_sum/((double)cluster_size);
     int Ywire_width = Ywire_max - Ywire_min + 1;
     {
       double time = time_min;
       int Ywire_min_0 = Ywire_min;
       int Ywire_max_0 = Ywire_max;
       int Ywire_min = Ywire_min_0;
       int Ywire_max = Ywire_max_0;
       int _u_MMuPC1AnalysisMQL_270 = _t_muPC1Y_cluster_contiguous.next();
       _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_270].time = time;
       _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_270].Ywire_min = Ywire_min_0;
       _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_270].Ywire_max = Ywire_max_0;
     }
   }
   _t_muPC1Y_cluster_contiguous.sort(_u_MMuPC1AnalysisMQL_74);
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_271 = 0; _u_MMuPC1AnalysisMQL_271 < _t_muPC1Y_cluster_contiguous.size(); _u_MMuPC1AnalysisMQL_271++)
     {
       double time = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_271].time;
       int Ywire_min = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_271].Ywire_min;
       int Ywire_max = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_271].Ywire_max;
       {
         double time_1 = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_271].time;
         int Ywire_min_1 = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_271].Ywire_min;
         int Ywire_max_1 = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_271].Ywire_max;
         if(!_u_MMuPC1AnalysisMQL_147)
         {
           if(!_t_muPC1Y_cluster_contiguous.checkSort(_u_MMuPC1AnalysisMQL_76))
           {
             printf("Warning: table muPC1Y_cluster_contiguous is not sorted on time_2 as required for join with muPC1Y_cluster_contiguous (_u_MMuPC1AnalysisMQL_76)\n");
           }
           _u_MMuPC1AnalysisMQL_147 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_148)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_146))
           {
             printf("Warning: table muPC1Y_cluster_contiguous is not sorted on time_1 as required for join with muPC1Y_cluster_contiguous\n");
             _u_MMuPC1AnalysisMQL_148 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_146 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_145 < _t_muPC1Y_cluster_contiguous.size(); _u_MMuPC1AnalysisMQL_145++)
         {
           double time_2 = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_145].time;
           int Ywire_min_2 = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_145].Ywire_min;
           int Ywire_max_2 = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_145].Ywire_max;
           double _u_MMuPC1AnalysisMQL_272 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_272 < 5)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_274 = _u_MMuPC1AnalysisMQL_145; _u_MMuPC1AnalysisMQL_274 < _t_muPC1Y_cluster_contiguous.size(); _u_MMuPC1AnalysisMQL_274++)
         {
           double time_2 = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_274].time;
           int Ywire_min_2 = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_274].Ywire_min;
           int Ywire_max_2 = _t_muPC1Y_cluster_contiguous[_u_MMuPC1AnalysisMQL_274].Ywire_max;
           double _u_MMuPC1AnalysisMQL_272 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_272 < -kMuPC1YClusterInterval)
           {
             break;
           }
           if(!((time_1==time_2) && (Ywire_min_1==Ywire_min_2) && (Ywire_max_1==Ywire_max_2)) &&
           ((Ywire_min_1 > Ywire_max_2) || (Ywire_min_2 > Ywire_max_1)))
           {
             {
               int cluster_sep = MIN(abs(Ywire_min_1-Ywire_max_2),abs(Ywire_min_2-Ywire_max_1));
               if(Tier3)
               {
                 _h_muPC1_Y_cluster_contiguous_separation->Fill(cluster_sep);
               }
             }
           }
         }
       }
     }
   }
   bool _u_MMuPC1AnalysisMQL_275[_t_muPC1Y_AD.size()];
   memset(_u_MMuPC1AnalysisMQL_275, 0, sizeof(_u_MMuPC1AnalysisMQL_275));
   if(!_t_muPC1Y_AD.checkSort(_u_MMuPC1AnalysisMQL_77))
   {
     printf("Warning: table muPC1Y_AD is not sorted on time_1 as required for cluster.\n");
   }
   for(int _u_MMuPC1AnalysisMQL_276 = 0; _u_MMuPC1AnalysisMQL_276 < _t_muPC1Y_AD.size(); _u_MMuPC1AnalysisMQL_276++)
   {
     double time = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_276].time;
     int Ywire = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_276].Ywire;
     if(_u_MMuPC1AnalysisMQL_275[_u_MMuPC1AnalysisMQL_276])
     {
       continue;
     }
     _u_MMuPC1AnalysisMQL_275[_u_MMuPC1AnalysisMQL_276] = true;
     int cluster_size = 1;
     int cluster_members[_t_muPC1Y_AD.size()];
     cluster_members[0] = _u_MMuPC1AnalysisMQL_276;
     for(int _u_MMuPC1AnalysisMQL_277 = _u_MMuPC1AnalysisMQL_276 + 1; _u_MMuPC1AnalysisMQL_277 < _t_muPC1Y_AD.size(); _u_MMuPC1AnalysisMQL_277++)
     {
       if(_u_MMuPC1AnalysisMQL_275[_u_MMuPC1AnalysisMQL_277])
       {
         continue;
       }
       bool coincidence_seen = false;
       for(int _u_MMuPC1AnalysisMQL_278 = 0; _u_MMuPC1AnalysisMQL_278 < cluster_size; _u_MMuPC1AnalysisMQL_278++)
       {
         int _u_MMuPC1AnalysisMQL_279 = cluster_members[_u_MMuPC1AnalysisMQL_278];
         double time_1 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_279].time;
         double time_2 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_277].time;
         int Ywire_1 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_279].Ywire;
         int Ywire_2 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_277].Ywire;
         double _u_MMuPC1AnalysisMQL_280 = time_1 - time_2;
         if(_u_MMuPC1AnalysisMQL_280 < -kMuPC1YClusterInterval)
         {
           continue;
         }
         coincidence_seen = true;
         if(!((abs(Ywire_1-Ywire_2)-1) <= kMuPC1YClusterMaxGap))
         {
           continue;
         }
         cluster_members[cluster_size++] = _u_MMuPC1AnalysisMQL_277;
         _u_MMuPC1AnalysisMQL_275[_u_MMuPC1AnalysisMQL_277] = true;
         _u_MMuPC1AnalysisMQL_277 = _u_MMuPC1AnalysisMQL_276;
         break;
       }
       if(!coincidence_seen)
       {
         break;
       }
     }
     double time_min = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_276].time;
     double time_max = time_min;
     double time_sum = 0;
     int Ywire_min = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_276].Ywire;
     int Ywire_max = Ywire_min;
     int Ywire_sum = 0;
     for(int _u_MMuPC1AnalysisMQL_278 = 0; _u_MMuPC1AnalysisMQL_278 < cluster_size; _u_MMuPC1AnalysisMQL_278++)
     {
       int _u_MMuPC1AnalysisMQL_279 = cluster_members[_u_MMuPC1AnalysisMQL_278];
       time = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_279].time;
       time_min = MIN(time_min, time);
       time_max = MAX(time_max, time);
       time_sum = time_sum + time;
       Ywire = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_279].Ywire;
       Ywire_min = MIN(Ywire_min, Ywire);
       Ywire_max = MAX(Ywire_max, Ywire);
       Ywire_sum = Ywire_sum + Ywire;
     }
     double time_1 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_276].time;
     double time_avg = time_sum/((double)cluster_size);
     double time_width = time_max - time_min + 1;
     int Ywire_1 = _t_muPC1Y_AD[_u_MMuPC1AnalysisMQL_276].Ywire;
     double Ywire_avg = Ywire_sum/((double)cluster_size);
     int Ywire_width = Ywire_max - Ywire_min + 1;
     {
       double time = time_min;
       double Ywire = Ywire_avg;
       int cluster_size_0 = cluster_size;
       int cluster_width = Ywire_width;
       int cluster_size = cluster_size_0;
       if(Tier1)
       {
         _h_muPC1_Y_final_cluster_size->Fill(cluster_size);
       }
       if(Tier1)
       {
         _h_muPC1_Y_final_cluster_width->Fill(cluster_width);
       }
       if(Tier1)
       {
         _h_muPC1_Y_final_cluster_avg->Fill(Ywire);
       }
       {
         double Ywire_0 = Ywire;
         double muPC1Time = time;
         double Ywire = Ywire_0;
         int _u_MMuPC1AnalysisMQL_281 = _t_muPC1Y_export.next();
         _t_muPC1Y_export[_u_MMuPC1AnalysisMQL_281].Ywire = Ywire_0;
         _t_muPC1Y_export[_u_MMuPC1AnalysisMQL_281].muPC1Time = muPC1Time;
       }
       int _u_MMuPC1AnalysisMQL_282 = _t_muPC1Y.next();
       _t_muPC1Y[_u_MMuPC1AnalysisMQL_282].time = time;
       _t_muPC1Y[_u_MMuPC1AnalysisMQL_282].Ywire = Ywire;
       _t_muPC1Y[_u_MMuPC1AnalysisMQL_282].cluster_size = cluster_size_0;
       _t_muPC1Y[_u_MMuPC1AnalysisMQL_282].cluster_width = cluster_width;
     }
   }
   _t_muPC1Y.sort(_u_MMuPC1AnalysisMQL_78);
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_283 = 0; _u_MMuPC1AnalysisMQL_283 < _t_muPC1Y.size(); _u_MMuPC1AnalysisMQL_283++)
     {
       double time = _t_muPC1Y[_u_MMuPC1AnalysisMQL_283].time;
       double Ywire = _t_muPC1Y[_u_MMuPC1AnalysisMQL_283].Ywire;
       int cluster_size = _t_muPC1Y[_u_MMuPC1AnalysisMQL_283].cluster_size;
       int cluster_width = _t_muPC1Y[_u_MMuPC1AnalysisMQL_283].cluster_width;
       {
         double time_1 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_283].time;
         double Ywire_1 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_283].Ywire;
         int cluster_size_1 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_283].cluster_size;
         int cluster_width_1 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_283].cluster_width;
         if(!_u_MMuPC1AnalysisMQL_152)
         {
           if(!_t_muPC1Y.checkSort(_u_MMuPC1AnalysisMQL_80))
           {
             printf("Warning: table muPC1Y is not sorted on time_2 as required for join with muPC1Y (_u_MMuPC1AnalysisMQL_80)\n");
           }
           _u_MMuPC1AnalysisMQL_152 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_153)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_151))
           {
             printf("Warning: table muPC1Y is not sorted on time_1 as required for join with muPC1Y\n");
             _u_MMuPC1AnalysisMQL_153 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_151 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_150 < _t_muPC1Y.size(); _u_MMuPC1AnalysisMQL_150++)
         {
           double time_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_150].time;
           double Ywire_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_150].Ywire;
           int cluster_size_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_150].cluster_size;
           int cluster_width_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_150].cluster_width;
           double _u_MMuPC1AnalysisMQL_284 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_284 < 1)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_286 = _u_MMuPC1AnalysisMQL_150; _u_MMuPC1AnalysisMQL_286 < _t_muPC1Y.size(); _u_MMuPC1AnalysisMQL_286++)
         {
           double time_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_286].time;
           double Ywire_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_286].Ywire;
           int cluster_size_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_286].cluster_size;
           int cluster_width_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_286].cluster_width;
           double _u_MMuPC1AnalysisMQL_284 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_284 < -50005)
           {
             break;
           }
           {
             double time_1_0 = time_1;
             double time_2_0 = time_2;
             double time_1 = time_1_0;
             double time_2 = time_2_0;
             if(Tier3)
             {
               if((time_2 - time_1) >= 0)
               {
                 _h_muPC1_Y_final_cluster_autocorr_all_1D->Fill(time_2 - time_1);
               }
             }
           }
         }
       }
     }
   }
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_287 = 0; _u_MMuPC1AnalysisMQL_287 < _t_muPC1Y.size(); _u_MMuPC1AnalysisMQL_287++)
     {
       double time = _t_muPC1Y[_u_MMuPC1AnalysisMQL_287].time;
       double Ywire = _t_muPC1Y[_u_MMuPC1AnalysisMQL_287].Ywire;
       int cluster_size = _t_muPC1Y[_u_MMuPC1AnalysisMQL_287].cluster_size;
       int cluster_width = _t_muPC1Y[_u_MMuPC1AnalysisMQL_287].cluster_width;
       {
         double time_1 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_287].time;
         double Ywire_1 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_287].Ywire;
         int cluster_size_1 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_287].cluster_size;
         int cluster_width_1 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_287].cluster_width;
         if(!_u_MMuPC1AnalysisMQL_156)
         {
           if(!_t_muPC1Y.checkSort(_u_MMuPC1AnalysisMQL_82))
           {
             printf("Warning: table muPC1Y is not sorted on time_2 as required for join with muPC1Y (_u_MMuPC1AnalysisMQL_82)\n");
           }
           _u_MMuPC1AnalysisMQL_156 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_157)
         {
           if(!(time_1 >= _u_MMuPC1AnalysisMQL_155))
           {
             printf("Warning: table muPC1Y is not sorted on time_1 as required for join with muPC1Y\n");
             _u_MMuPC1AnalysisMQL_157 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_155 = time_1;
         for( ; _u_MMuPC1AnalysisMQL_154 < _t_muPC1Y.size(); _u_MMuPC1AnalysisMQL_154++)
         {
           double time_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_154].time;
           double Ywire_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_154].Ywire;
           int cluster_size_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_154].cluster_size;
           int cluster_width_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_154].cluster_width;
           double _u_MMuPC1AnalysisMQL_288 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_288 < 1)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_290 = _u_MMuPC1AnalysisMQL_154; _u_MMuPC1AnalysisMQL_290 < _t_muPC1Y.size(); _u_MMuPC1AnalysisMQL_290++)
         {
           double time_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_290].time;
           double Ywire_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_290].Ywire;
           int cluster_size_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_290].cluster_size;
           int cluster_width_2 = _t_muPC1Y[_u_MMuPC1AnalysisMQL_290].cluster_width;
           double _u_MMuPC1AnalysisMQL_288 = time_1 - time_2;
           if(_u_MMuPC1AnalysisMQL_288 < -150)
           {
             break;
           }
           {
             double time1 = time_1;
             double time2 = time_2;
             double wire_diff = fabs(Ywire_1-Ywire_2);
             if(Tier3)
             {
               if(fabs(time_2-time_1)>=0)
               {
                 _h_muPC1_Y_final_cluster_autocorr_spatial_all_1D->Fill(wire_diff);
               }
             }
           }
         }
       }
     }
   }
   for(int _u_MMuPC1AnalysisMQL_291 = 0; _u_MMuPC1AnalysisMQL_291 < _t_muPC1X.size(); _u_MMuPC1AnalysisMQL_291++)
   {
     double time = _t_muPC1X[_u_MMuPC1AnalysisMQL_291].time;
     double Xwire = _t_muPC1X[_u_MMuPC1AnalysisMQL_291].Xwire;
     int cluster_size = _t_muPC1X[_u_MMuPC1AnalysisMQL_291].cluster_size;
     int cluster_width = _t_muPC1X[_u_MMuPC1AnalysisMQL_291].cluster_width;
     {
       double muPC1X_time = _t_muPC1X[_u_MMuPC1AnalysisMQL_291].time;
       double Xwire = _t_muPC1X[_u_MMuPC1AnalysisMQL_291].Xwire;
       int muPC1X_cluster_size = _t_muPC1X[_u_MMuPC1AnalysisMQL_291].cluster_size;
       int muPC1X_cluster_width = _t_muPC1X[_u_MMuPC1AnalysisMQL_291].cluster_width;
       if(!_u_MMuPC1AnalysisMQL_160)
       {
         if(!_t_muPC1Y.checkSort(_u_MMuPC1AnalysisMQL_84))
         {
           printf("Warning: table muPC1Y is not sorted on muPC1Y_time as required for join with muPC1X (_u_MMuPC1AnalysisMQL_84)\n");
         }
         _u_MMuPC1AnalysisMQL_160 = true;
       }
       else if(!_u_MMuPC1AnalysisMQL_161)
       {
         if(!(muPC1X_time >= _u_MMuPC1AnalysisMQL_159))
         {
           printf("Warning: table muPC1X is not sorted on muPC1X_time as required for join with muPC1Y\n");
           _u_MMuPC1AnalysisMQL_161 = true;
         }
       }
       _u_MMuPC1AnalysisMQL_159 = muPC1X_time;
       for( ; _u_MMuPC1AnalysisMQL_158 < _t_muPC1Y.size(); _u_MMuPC1AnalysisMQL_158++)
       {
         double muPC1Y_time = _t_muPC1Y[_u_MMuPC1AnalysisMQL_158].time;
         double Ywire = _t_muPC1Y[_u_MMuPC1AnalysisMQL_158].Ywire;
         int muPC1Y_cluster_size = _t_muPC1Y[_u_MMuPC1AnalysisMQL_158].cluster_size;
         int muPC1Y_cluster_width = _t_muPC1Y[_u_MMuPC1AnalysisMQL_158].cluster_width;
         double _u_MMuPC1AnalysisMQL_292 = muPC1X_time - muPC1Y_time;
         if(_u_MMuPC1AnalysisMQL_292 < 601)
         {
           break;
         }
       }
       for(int _u_MMuPC1AnalysisMQL_294 = _u_MMuPC1AnalysisMQL_158; _u_MMuPC1AnalysisMQL_294 < _t_muPC1Y.size(); _u_MMuPC1AnalysisMQL_294++)
       {
         double muPC1Y_time = _t_muPC1Y[_u_MMuPC1AnalysisMQL_294].time;
         double Ywire = _t_muPC1Y[_u_MMuPC1AnalysisMQL_294].Ywire;
         int muPC1Y_cluster_size = _t_muPC1Y[_u_MMuPC1AnalysisMQL_294].cluster_size;
         int muPC1Y_cluster_width = _t_muPC1Y[_u_MMuPC1AnalysisMQL_294].cluster_width;
         double _u_MMuPC1AnalysisMQL_292 = muPC1X_time - muPC1Y_time;
         if(_u_MMuPC1AnalysisMQL_292 < -601)
         {
           break;
         }
         {
           double Xwire_0 = Xwire;
           double Ywire_0 = Ywire;
           double muPC1Time = MIN(muPC1X_time, muPC1Y_time);
           double XYtdiff = muPC1Y_time - muPC1X_time;
           double Xwire = Xwire_0;
           double Ywire = Ywire_0;
           int _u_MMuPC1AnalysisMQL_295 = _t_muPC1XY.next();
           _t_muPC1XY[_u_MMuPC1AnalysisMQL_295].Xwire = Xwire_0;
           _t_muPC1XY[_u_MMuPC1AnalysisMQL_295].Ywire = Ywire_0;
           _t_muPC1XY[_u_MMuPC1AnalysisMQL_295].muPC1Time = muPC1Time;
           _t_muPC1XY[_u_MMuPC1AnalysisMQL_295].XYtdiff = XYtdiff;
         }
       }
     }
   }
   _t_muPC1XY.sort(_u_MMuPC1AnalysisMQL_85);
   for(int _u_MMuPC1AnalysisMQL_296 = 0; _u_MMuPC1AnalysisMQL_296 < _t_muPC1XY.size(); _u_MMuPC1AnalysisMQL_296++)
   {
     double Xwire = _t_muPC1XY[_u_MMuPC1AnalysisMQL_296].Xwire;
     double Ywire = _t_muPC1XY[_u_MMuPC1AnalysisMQL_296].Ywire;
     double muPC1Time = _t_muPC1XY[_u_MMuPC1AnalysisMQL_296].muPC1Time;
     double XYtdiff = _t_muPC1XY[_u_MMuPC1AnalysisMQL_296].XYtdiff;
     if(Tier1)
     {
       _h_muPC1_coinc_XY_tdiff->Fill(XYtdiff);
     }
     if((XYtdiff >= -95) && (XYtdiff <= 95))
     {
       {
         double Xwire_0 = Xwire;
         double Ywire_0 = Ywire;
         double muPC1Time_0 = muPC1Time;
         double Xwire = Xwire_0;
         double Ywire = Ywire_0;
         double muPC1Time = muPC1Time_0;
         if(Tier1)
         {
           _h_muPC1_coinc_XY_2D->Fill(Xwire, Ywire);
         }
         int _u_MMuPC1AnalysisMQL_297 = _t_muPC1.next();
         _t_muPC1[_u_MMuPC1AnalysisMQL_297].Xwire = Xwire_0;
         _t_muPC1[_u_MMuPC1AnalysisMQL_297].Ywire = Ywire_0;
         _t_muPC1[_u_MMuPC1AnalysisMQL_297].muPC1Time = muPC1Time_0;
       }
     }
   }
   if(Tier3)
   {
     for(int _u_MMuPC1AnalysisMQL_298 = 0; _u_MMuPC1AnalysisMQL_298 < _t_muPC1.size(); _u_MMuPC1AnalysisMQL_298++)
     {
       double Xwire = _t_muPC1[_u_MMuPC1AnalysisMQL_298].Xwire;
       double Ywire = _t_muPC1[_u_MMuPC1AnalysisMQL_298].Ywire;
       double muPC1Time = _t_muPC1[_u_MMuPC1AnalysisMQL_298].muPC1Time;
       {
         double Xwire_1 = _t_muPC1[_u_MMuPC1AnalysisMQL_298].Xwire;
         double Ywire_1 = _t_muPC1[_u_MMuPC1AnalysisMQL_298].Ywire;
         double muPC1Time_1 = _t_muPC1[_u_MMuPC1AnalysisMQL_298].muPC1Time;
         if(!_u_MMuPC1AnalysisMQL_164)
         {
           if(!_t_muPC1.checkSort(_u_MMuPC1AnalysisMQL_87))
           {
             printf("Warning: table muPC1 is not sorted on muPC1Time_2 as required for join with muPC1 (_u_MMuPC1AnalysisMQL_87)\n");
           }
           _u_MMuPC1AnalysisMQL_164 = true;
         }
         else if(!_u_MMuPC1AnalysisMQL_165)
         {
           if(!(muPC1Time_1 >= _u_MMuPC1AnalysisMQL_163))
           {
             printf("Warning: table muPC1 is not sorted on muPC1Time_1 as required for join with muPC1\n");
             _u_MMuPC1AnalysisMQL_165 = true;
           }
         }
         _u_MMuPC1AnalysisMQL_163 = muPC1Time_1;
         for( ; _u_MMuPC1AnalysisMQL_162 < _t_muPC1.size(); _u_MMuPC1AnalysisMQL_162++)
         {
           double Xwire_2 = _t_muPC1[_u_MMuPC1AnalysisMQL_162].Xwire;
           double Ywire_2 = _t_muPC1[_u_MMuPC1AnalysisMQL_162].Ywire;
           double muPC1Time_2 = _t_muPC1[_u_MMuPC1AnalysisMQL_162].muPC1Time;
           double _u_MMuPC1AnalysisMQL_299 = muPC1Time_1 - muPC1Time_2;
           if(_u_MMuPC1AnalysisMQL_299 < 1)
           {
             break;
           }
         }
         for(int _u_MMuPC1AnalysisMQL_301 = _u_MMuPC1AnalysisMQL_162; _u_MMuPC1AnalysisMQL_301 < _t_muPC1.size(); _u_MMuPC1AnalysisMQL_301++)
         {
           double Xwire_2 = _t_muPC1[_u_MMuPC1AnalysisMQL_301].Xwire;
           double Ywire_2 = _t_muPC1[_u_MMuPC1AnalysisMQL_301].Ywire;
           double muPC1Time_2 = _t_muPC1[_u_MMuPC1AnalysisMQL_301].muPC1Time;
           double _u_MMuPC1AnalysisMQL_299 = muPC1Time_1 - muPC1Time_2;
           if(_u_MMuPC1AnalysisMQL_299 < -50005)
           {
             break;
           }
           {
             double muPC1Time_1_0 = muPC1Time_1;
             double muPC1Time_2_0 = muPC1Time_2;
             double muPC1Time_1 = muPC1Time_1_0;
             double muPC1Time_2 = muPC1Time_2_0;
             if(Tier3)
             {
               if((muPC1Time_2 - muPC1Time_1) >= 0)
               {
                 _h_muPC1_coinc_XY_autocorr_all_1D->Fill(muPC1Time_2 - muPC1Time_1);
               }
             }
           }
         }
       }
     }
   }
   for(int _u_MMuPC1AnalysisMQL_302 = 0; _u_MMuPC1AnalysisMQL_302 < _t_muSC.size(); _u_MMuPC1AnalysisMQL_302++)
   {
     double time = _t_muSC[_u_MMuPC1AnalysisMQL_302].time;
     {
       double time = _t_muSC[_u_MMuPC1AnalysisMQL_302].time;
       if(!_u_MMuPC1AnalysisMQL_168)
       {
         if(!_t_muPC1.checkSort(_u_MMuPC1AnalysisMQL_89))
         {
           printf("Warning: table muPC1 is not sorted on muPC1Time as required for join with muSC (_u_MMuPC1AnalysisMQL_89)\n");
         }
         _u_MMuPC1AnalysisMQL_168 = true;
       }
       else if(!_u_MMuPC1AnalysisMQL_169)
       {
         if(!(time >= _u_MMuPC1AnalysisMQL_167))
         {
           printf("Warning: table muSC is not sorted on time as required for join with muPC1\n");
           _u_MMuPC1AnalysisMQL_169 = true;
         }
       }
       _u_MMuPC1AnalysisMQL_167 = time;
       for( ; _u_MMuPC1AnalysisMQL_166 < _t_muPC1.size(); _u_MMuPC1AnalysisMQL_166++)
       {
         double Xwire = _t_muPC1[_u_MMuPC1AnalysisMQL_166].Xwire;
         double Ywire = _t_muPC1[_u_MMuPC1AnalysisMQL_166].Ywire;
         double muPC1Time = _t_muPC1[_u_MMuPC1AnalysisMQL_166].muPC1Time;
         double _u_MMuPC1AnalysisMQL_303 = time - muPC1Time;
         if(_u_MMuPC1AnalysisMQL_303 < 10000)
         {
           break;
         }
       }
       for(int _u_MMuPC1AnalysisMQL_305 = _u_MMuPC1AnalysisMQL_166; _u_MMuPC1AnalysisMQL_305 < _t_muPC1.size(); _u_MMuPC1AnalysisMQL_305++)
       {
         double Xwire = _t_muPC1[_u_MMuPC1AnalysisMQL_305].Xwire;
         double Ywire = _t_muPC1[_u_MMuPC1AnalysisMQL_305].Ywire;
         double muPC1Time = _t_muPC1[_u_MMuPC1AnalysisMQL_305].muPC1Time;
         double _u_MMuPC1AnalysisMQL_303 = time - muPC1Time;
         if(_u_MMuPC1AnalysisMQL_303 < -10000)
         {
           break;
         }
         {
           double Xwire_0 = Xwire;
           double Ywire_0 = Ywire;
           double time_0 = time;
           double muPC1Time_0 = muPC1Time;
           double Xwire = Xwire_0;
           double Ywire = Ywire_0;
           double time = time_0;
           double muPC1Time = muPC1Time_0;
           _h_muSC_muPC1_time_difference->Fill(time-muPC1Time);
           if(Tier1)
           {
             if(((time-muPC1Time) >= -160) && ((time-muPC1Time) <= 20))
             {
               _h_muPC1_coinc_XY_2D_with_muSC->Fill(Xwire, Ywire);
             }
           }
         }
       }
     }
   }
   for(int _u_MMuPC1AnalysisMQL_306 = 0; _u_MMuPC1AnalysisMQL_306 < _t_muPC1X_sparks.size(); _u_MMuPC1AnalysisMQL_306++)
   {
     double time = _t_muPC1X_sparks[_u_MMuPC1AnalysisMQL_306].time;
     {
       double time_0 = time;
       double time = time_0;
       int _u_MMuPC1AnalysisMQL_307 = _t_muPC1_sparks_union.next();
       _t_muPC1_sparks_union[_u_MMuPC1AnalysisMQL_307].time = time_0;
     }
   }
   for(int _u_MMuPC1AnalysisMQL_308 = 0; _u_MMuPC1AnalysisMQL_308 < _t_muPC1Y_sparks.size(); _u_MMuPC1AnalysisMQL_308++)
   {
     double time = _t_muPC1Y_sparks[_u_MMuPC1AnalysisMQL_308].time;
     {
       double time_0 = time;
       double time = time_0;
       int _u_MMuPC1AnalysisMQL_309 = _t_muPC1_sparks_union.next();
       _t_muPC1_sparks_union[_u_MMuPC1AnalysisMQL_309].time = time_0;
     }
   }
   _t_muPC1_sparks_union.sort(_u_MMuPC1AnalysisMQL_90);
   bool _u_MMuPC1AnalysisMQL_310[_t_muPC1_sparks_union.size()];
   memset(_u_MMuPC1AnalysisMQL_310, 0, sizeof(_u_MMuPC1AnalysisMQL_310));
   if(!_t_muPC1_sparks_union.checkSort(_u_MMuPC1AnalysisMQL_91))
   {
     printf("Warning: table muPC1_sparks_union is not sorted on time_1 as required for cluster.\n");
   }
   for(int _u_MMuPC1AnalysisMQL_311 = 0; _u_MMuPC1AnalysisMQL_311 < _t_muPC1_sparks_union.size(); _u_MMuPC1AnalysisMQL_311++)
   {
     double time = _t_muPC1_sparks_union[_u_MMuPC1AnalysisMQL_311].time;
     if(_u_MMuPC1AnalysisMQL_310[_u_MMuPC1AnalysisMQL_311])
     {
       continue;
     }
     _u_MMuPC1AnalysisMQL_310[_u_MMuPC1AnalysisMQL_311] = true;
     int cluster_size = 1;
     int cluster_members[_t_muPC1_sparks_union.size()];
     cluster_members[0] = _u_MMuPC1AnalysisMQL_311;
     for(int _u_MMuPC1AnalysisMQL_312 = _u_MMuPC1AnalysisMQL_311 + 1; _u_MMuPC1AnalysisMQL_312 < _t_muPC1_sparks_union.size(); _u_MMuPC1AnalysisMQL_312++)
     {
       if(_u_MMuPC1AnalysisMQL_310[_u_MMuPC1AnalysisMQL_312])
       {
         continue;
       }
       bool coincidence_seen = false;
       for(int _u_MMuPC1AnalysisMQL_313 = 0; _u_MMuPC1AnalysisMQL_313 < cluster_size; _u_MMuPC1AnalysisMQL_313++)
       {
         int _u_MMuPC1AnalysisMQL_314 = cluster_members[_u_MMuPC1AnalysisMQL_313];
         double time_1 = _t_muPC1_sparks_union[_u_MMuPC1AnalysisMQL_314].time;
         double time_2 = _t_muPC1_sparks_union[_u_MMuPC1AnalysisMQL_312].time;
         double _u_MMuPC1AnalysisMQL_315 = time_1 - time_2;
         if(_u_MMuPC1AnalysisMQL_315 < -200)
         {
           continue;
         }
         coincidence_seen = true;
         cluster_members[cluster_size++] = _u_MMuPC1AnalysisMQL_312;
         _u_MMuPC1AnalysisMQL_310[_u_MMuPC1AnalysisMQL_312] = true;
         _u_MMuPC1AnalysisMQL_312 = _u_MMuPC1AnalysisMQL_311;
         break;
       }
       if(!coincidence_seen)
       {
         break;
       }
     }
     double time_min = _t_muPC1_sparks_union[_u_MMuPC1AnalysisMQL_311].time;
     double time_max = time_min;
     double time_sum = 0;
     for(int _u_MMuPC1AnalysisMQL_313 = 0; _u_MMuPC1AnalysisMQL_313 < cluster_size; _u_MMuPC1AnalysisMQL_313++)
     {
       int _u_MMuPC1AnalysisMQL_314 = cluster_members[_u_MMuPC1AnalysisMQL_313];
       time = _t_muPC1_sparks_union[_u_MMuPC1AnalysisMQL_314].time;
       time_min = MIN(time_min, time);
       time_max = MAX(time_max, time);
       time_sum = time_sum + time;
     }
     double time_1 = _t_muPC1_sparks_union[_u_MMuPC1AnalysisMQL_311].time;
     double time_avg = time_sum/((double)cluster_size);
     double time_width = time_max - time_min + 1;
     {
       double time = time_min;
       int cluster_size_0 = cluster_size;
       int cluster_size = cluster_size_0;
       if(Tier1)
       {
         _h_muPC1_spark_clustered_blocktime->Fill(time);
       }
       if(cluster_size == 2)
       {
         {
           double time_0 = time;
           double time = time_0;
           if(Tier1)
           {
             _h_muPC1_spark_chamberwide_count->Fill(1);
           }
           if(Tier1)
           {
             _h_muPC1_spark_chamberwide_blocktime->Fill(time);
           }
         }
       }
     }
   }
   _t_muPC1X_auto.finish();
   _t_muPC1_sparks_union.toBank(pevent, "M1SP");
   _t_muPC1_sparks_union.finish();
   _t_muPC1X_cluster_contiguous.finish();
   _t_muPC1Y_temporal_auto.finish();
   _t_muPC1X_raw_auto.finish();
   _t_muPC1X_AD.finish();
   _t_muPC1Y_spark_search.finish();
   _t_muPC1X_cluster_contiguous_sep.finish();
   _t_muPC1X_spatial_auto.finish();
   _t_muPC1X_export.toBank(pevent, "MP1X");
   _t_muPC1X_export.finish();
   _t_muPC1X_SC.finish();
   _t_muPC1Y_export.toBank(pevent, "MP1Y");
   _t_muPC1Y_export.finish();
   _t_muPC1Y_raw_auto.finish();
   _t_muPC1Y.finish();
   _t_muPC1X.finish();
   _t_muSC.finish();
   _t_muPC1Y_cluster_contiguous_sep.finish();
   _t_muPC1_auto.finish();
   _t_muPC1Y_SC_auto.finish();
   _t_hits.finish();
   _t_muPC1X_spark_search.finish();
   _t_muPC1X_AD_auto.finish();
   _t_muPC1X_sparks.finish();
   _t_muPC1Y_sparks.finish();
   _t_muPC1.toBank(pevent, "MPC1");
   _t_muPC1.finish();
   _t_muPC1Y_AD.finish();
   _t_muPC1_sparks_clustered.finish();
   _t_muPC1_hits.finish();
   _t_muPC1Y_raw.finish();
   _t_muPC1Y_SC.finish();
   _t_muSC_muPC1.finish();
   _t_muPC1_sparks_chamberwide.finish();
   _t_muPC1Y_AD_auto.finish();
   _t_muPC1Y_cluster_contiguous.finish();
   _t_muPC1XY.finish();
   _t_muPC1Y_spatial_auto.finish();
   _t_muPC1X_raw.finish();
   _t_muPC1X_SC_auto.finish();
   return SUCCESS;
 }
INT MMuPC1AnalysisMQL_init ()
Definition at line 1536 of file MMuPC1AnalysisMQL.cpp.
References _h_muPC1_coinc_XY_2D, _h_muPC1_coinc_XY_2D_with_muSC, _h_muPC1_coinc_XY_autocorr_all_1D, _h_muPC1_coinc_XY_tdiff, _h_muPC1_spark_chamberwide_blocktime, _h_muPC1_spark_chamberwide_count, _h_muPC1_spark_clustered_blocktime, _h_muPC1_spark_count_Xwires, _h_muPC1_spark_count_Ywires, _h_muPC1_spark_search_Xwires, _h_muPC1_spark_search_Ywires, _h_muPC1_X_AD_autocorr_2D, _h_muPC1_X_AD_autocorr_all_1D, _h_muPC1_X_cluster_contiguous_separation, _h_muPC1_X_final_cluster_autocorr_all_1D, _h_muPC1_X_final_cluster_autocorr_spatial_all_1D, _h_muPC1_X_final_cluster_avg, _h_muPC1_X_final_cluster_size, _h_muPC1_X_final_cluster_width, _h_muPC1_X_raw_autocorr_2D, _h_muPC1_X_raw_autocorr_all_1D, _h_muPC1_X_raw_autosingles_2D, _h_muPC1_X_SC_autocorr_2D, _h_muPC1_X_SC_autocorr_all_1D, _h_muPC1_Y_AD_autocorr_2D, _h_muPC1_Y_AD_autocorr_all_1D, _h_muPC1_Y_cluster_contiguous_separation, _h_muPC1_Y_final_cluster_autocorr_all_1D, _h_muPC1_Y_final_cluster_autocorr_spatial_all_1D, _h_muPC1_Y_final_cluster_avg, _h_muPC1_Y_final_cluster_size, _h_muPC1_Y_final_cluster_width, _h_muPC1_Y_raw_autocorr_2D, _h_muPC1_Y_raw_autocorr_all_1D, _h_muPC1_Y_raw_autosingles_2D, _h_muPC1_Y_SC_autocorr_2D, _h_muPC1_Y_SC_autocorr_all_1D, _h_muSC_muPC1_time_difference, _h_parameters_muPC1, kMuPC1NumXWires, kMuPC1NumYWires, SUCCESS, Tier1, and Tier3.
 {
   if(Tier1)
   {
     _h_parameters_muPC1 = new TH1D("parameters_muPC1", "#muPC1 hits",
       101, 3999.5, 4100.5);
     _h_parameters_muPC1->GetXaxis()->SetTitle("parameter");
   }
   if(Tier3)
   {
     _h_muPC1_X_raw_autosingles_2D = new TH2D("muPC1_X_raw_autosingles_2D", "#muPC1 raw Xwire singles autocorr 2D",
       kMuPC1NumXWires, 0.5, kMuPC1NumXWires+0.5,
       kMuPC1NumXWires, 0.5, kMuPC1NumXWires+0.5);
     _h_muPC1_X_raw_autosingles_2D->GetXaxis()->SetTitle("Xwire_1");
     _h_muPC1_X_raw_autosingles_2D->GetYaxis()->SetTitle("Xwire_2");
   }
   if(Tier3)
   {
     _h_muPC1_X_raw_autocorr_all_1D = new TH1D("muPC1_X_raw_autocorr_all_1D", "#muPC1 raw Xwire autocorr neighbors 1D",
       11001, -5002.5, 50002.5);
     _h_muPC1_X_raw_autocorr_all_1D->GetXaxis()->SetTitle("time_2 - time_1");
   }
   if(Tier3)
   {
     _h_muPC1_X_raw_autocorr_2D = new TH2D("muPC1_X_raw_autocorr_2D", "#muPC1 raw Xwire autocorr 2D",
       11001, -5002.5, 50002.5,
       kMuPC1NumXWires, 0.5, kMuPC1NumXWires+0.5);
     _h_muPC1_X_raw_autocorr_2D->GetXaxis()->SetTitle("time_2 - time_1");
     _h_muPC1_X_raw_autocorr_2D->GetYaxis()->SetTitle("Xwire_1");
   }
   if(Tier1)
   {
     _h_muPC1_spark_search_Xwires = new TH1D("muPC1_spark_search_Xwires", "#muPC1 spark search Xwire cluster_size",
       (3*kMuPC1NumXWires), 0.5, (3*kMuPC1NumXWires)+0.5);
     _h_muPC1_spark_search_Xwires->GetXaxis()->SetTitle("cluster_size");
   }
   if(Tier1)
   {
     _h_muPC1_spark_count_Xwires = new TH1D("muPC1_spark_count_Xwires", "Number of #muPC1 Xwire sparks",
       3, -0.5, 2.5);
     _h_muPC1_spark_count_Xwires->GetXaxis()->SetTitle("1");
   }
   if(Tier3)
   {
     _h_muPC1_X_SC_autocorr_all_1D = new TH1D("muPC1_X_SC_autocorr_all_1D", "#muPC1 SC Xwire autocorr neighbors 1D",
       11001, -5002.5, 50002.5);
     _h_muPC1_X_SC_autocorr_all_1D->GetXaxis()->SetTitle("time_2 - time_1");
   }
   if(Tier3)
   {
     _h_muPC1_X_SC_autocorr_2D = new TH2D("muPC1_X_SC_autocorr_2D", "#muPC1 SC Xwire autocorr 2D",
       11001, -5002.5, 50002.5,
       kMuPC1NumXWires, 0.5, kMuPC1NumXWires+0.5);
     _h_muPC1_X_SC_autocorr_2D->GetXaxis()->SetTitle("time_2 - time_1");
     _h_muPC1_X_SC_autocorr_2D->GetYaxis()->SetTitle("Xwire_1");
   }
   if(Tier3)
   {
     _h_muPC1_X_AD_autocorr_all_1D = new TH1D("muPC1_X_AD_autocorr_all_1D", "#muPC1 AD Xwire autocorr neighbors 1D",
       11001, -5002.5, 50002.5);
     _h_muPC1_X_AD_autocorr_all_1D->GetXaxis()->SetTitle("time_2 - time_1");
   }
   if(Tier3)
   {
     _h_muPC1_X_AD_autocorr_2D = new TH2D("muPC1_X_AD_autocorr_2D", "#muPC1 AD Xwire autocorr 2D",
       11001, -5002.5, 50002.5,
       kMuPC1NumXWires, 0.5, kMuPC1NumXWires+0.5);
     _h_muPC1_X_AD_autocorr_2D->GetXaxis()->SetTitle("time_2 - time_1");
     _h_muPC1_X_AD_autocorr_2D->GetYaxis()->SetTitle("Xwire_1");
   }
   if(Tier3)
   {
     _h_muPC1_X_cluster_contiguous_separation = new TH1D("muPC1_X_cluster_contiguous_separation", "#muPC1 Xwire contiguous cluster wire separation",
       31, -0.5, 30.5);
     _h_muPC1_X_cluster_contiguous_separation->GetXaxis()->SetTitle("cluster_sep");
   }
   if(Tier1)
   {
     _h_muPC1_X_final_cluster_size = new TH1D("muPC1_X_final_cluster_size", "#muPC1 Xwire cluster size",
       kMuPC1NumXWires+1, 0.5, kMuPC1NumXWires+1.5);
     _h_muPC1_X_final_cluster_size->GetXaxis()->SetTitle("cluster_size");
   }
   if(Tier1)
   {
     _h_muPC1_X_final_cluster_width = new TH1D("muPC1_X_final_cluster_width", "#muPC1 Xwire cluster width",
       kMuPC1NumXWires+1, 0.5, kMuPC1NumXWires+1.5);
     _h_muPC1_X_final_cluster_width->GetXaxis()->SetTitle("cluster_width");
   }
   if(Tier1)
   {
     _h_muPC1_X_final_cluster_avg = new TH1D("muPC1_X_final_cluster_avg", "#muPC1 Xwire cluster average",
       kMuPC1NumXWires, 0.5, kMuPC1NumXWires+0.5);
     _h_muPC1_X_final_cluster_avg->GetXaxis()->SetTitle("Xwire");
   }
   if(Tier3)
   {
     _h_muPC1_X_final_cluster_autocorr_all_1D = new TH1D("muPC1_X_final_cluster_autocorr_all_1D", "#muPC1 clustered Xwire autocorr neighbors 1D",
       11001, -5002.5, 50002.5);
     _h_muPC1_X_final_cluster_autocorr_all_1D->GetXaxis()->SetTitle("time_2 - time_1");
   }
   if(Tier3)
   {
     _h_muPC1_X_final_cluster_autocorr_spatial_all_1D = new TH1D("muPC1_X_final_cluster_autocorr_spatial_all_1D", "#muPC1X clustered autocorr neighbors spatial, 0-150 ns",
       kMuPC1NumXWires+1, -0.5, kMuPC1NumXWires+0.5);
     _h_muPC1_X_final_cluster_autocorr_spatial_all_1D->GetXaxis()->SetTitle("wire_diff");
   }
   if(Tier3)
   {
     _h_muPC1_Y_raw_autosingles_2D = new TH2D("muPC1_Y_raw_autosingles_2D", "#muPC1 raw Ywire singles autocorr 2D",
       kMuPC1NumYWires, 0.5, kMuPC1NumYWires+0.5,
       kMuPC1NumYWires, 0.5, kMuPC1NumYWires+0.5);
     _h_muPC1_Y_raw_autosingles_2D->GetXaxis()->SetTitle("Ywire_1");
     _h_muPC1_Y_raw_autosingles_2D->GetYaxis()->SetTitle("Ywire_2");
   }
   if(Tier3)
   {
     _h_muPC1_Y_raw_autocorr_all_1D = new TH1D("muPC1_Y_raw_autocorr_all_1D", "#muPC1 raw Ywire autocorr neighbors 1D",
       11001, -5002.5, 50002.5);
     _h_muPC1_Y_raw_autocorr_all_1D->GetXaxis()->SetTitle("time_2 - time_1");
   }
   if(Tier3)
   {
     _h_muPC1_Y_raw_autocorr_2D = new TH2D("muPC1_Y_raw_autocorr_2D", "#muPC1 raw Ywire autocorr 2D",
       11001, -5002.5, 50002.5,
       kMuPC1NumYWires, 0.5, kMuPC1NumYWires+0.5);
     _h_muPC1_Y_raw_autocorr_2D->GetXaxis()->SetTitle("time_2 - time_1");
     _h_muPC1_Y_raw_autocorr_2D->GetYaxis()->SetTitle("Ywire_1");
   }
   if(Tier1)
   {
     _h_muPC1_spark_search_Ywires = new TH1D("muPC1_spark_search_Ywires", "#muPC1 spark search Ywire cluster_size",
       (3*kMuPC1NumYWires), 0.5, (3*kMuPC1NumYWires)+0.5);
     _h_muPC1_spark_search_Ywires->GetXaxis()->SetTitle("cluster_size");
   }
   if(Tier1)
   {
     _h_muPC1_spark_count_Ywires = new TH1D("muPC1_spark_count_Ywires", "Number of #muPC1 Ywire sparks",
       3, -0.5, 2.5);
     _h_muPC1_spark_count_Ywires->GetXaxis()->SetTitle("1");
   }
   if(Tier3)
   {
     _h_muPC1_Y_SC_autocorr_all_1D = new TH1D("muPC1_Y_SC_autocorr_all_1D", "#muPC1 SC Ywire autocorr neighbors 1D",
       11001, -5002.5, 50002.5);
     _h_muPC1_Y_SC_autocorr_all_1D->GetXaxis()->SetTitle("time_2 - time_1");
   }
   if(Tier3)
   {
     _h_muPC1_Y_SC_autocorr_2D = new TH2D("muPC1_Y_SC_autocorr_2D", "#muPC1 SC Ywire autocorr 2D",
       11001, -5002.5, 50002.5,
       kMuPC1NumYWires, 0.5, kMuPC1NumYWires+0.5);
     _h_muPC1_Y_SC_autocorr_2D->GetXaxis()->SetTitle("time_2 - time_1");
     _h_muPC1_Y_SC_autocorr_2D->GetYaxis()->SetTitle("Ywire_1");
   }
   if(Tier3)
   {
     _h_muPC1_Y_AD_autocorr_all_1D = new TH1D("muPC1_Y_AD_autocorr_all_1D", "#muPC1 AD Ywire autocorr neighbors 1D",
       11001, -5002.5, 50002.5);
     _h_muPC1_Y_AD_autocorr_all_1D->GetXaxis()->SetTitle("time_2 - time_1");
   }
   if(Tier3)
   {
     _h_muPC1_Y_AD_autocorr_2D = new TH2D("muPC1_Y_AD_autocorr_2D", "#muPC1 AD Ywire autocorr 2D",
       11001, -5002.5, 50002.5,
       kMuPC1NumYWires, 0.5, kMuPC1NumYWires+0.5);
     _h_muPC1_Y_AD_autocorr_2D->GetXaxis()->SetTitle("time_2 - time_1");
     _h_muPC1_Y_AD_autocorr_2D->GetYaxis()->SetTitle("Ywire_1");
   }
   if(Tier3)
   {
     _h_muPC1_Y_cluster_contiguous_separation = new TH1D("muPC1_Y_cluster_contiguous_separation", "#muPC1 Ywire contiguous cluster wire separation",
       31, -0.5, 30.5);
     _h_muPC1_Y_cluster_contiguous_separation->GetXaxis()->SetTitle("cluster_sep");
   }
   if(Tier1)
   {
     _h_muPC1_Y_final_cluster_size = new TH1D("muPC1_Y_final_cluster_size", "#muPC1 Ywire cluster size",
       kMuPC1NumYWires+1, 0.5, kMuPC1NumYWires+1.5);
     _h_muPC1_Y_final_cluster_size->GetXaxis()->SetTitle("cluster_size");
   }
   if(Tier1)
   {
     _h_muPC1_Y_final_cluster_width = new TH1D("muPC1_Y_final_cluster_width", "#muPC1 Ywire cluster width",
       kMuPC1NumYWires+1, 0.5, kMuPC1NumYWires+1.5);
     _h_muPC1_Y_final_cluster_width->GetXaxis()->SetTitle("cluster_width");
   }
   if(Tier1)
   {
     _h_muPC1_Y_final_cluster_avg = new TH1D("muPC1_Y_final_cluster_avg", "#muPC1 Ywire cluster average",
       kMuPC1NumYWires, 0.5, kMuPC1NumYWires+0.5);
     _h_muPC1_Y_final_cluster_avg->GetXaxis()->SetTitle("Ywire");
   }
   if(Tier3)
   {
     _h_muPC1_Y_final_cluster_autocorr_all_1D = new TH1D("muPC1_Y_final_cluster_autocorr_all_1D", "#muPC1 clustered Ywire autocorr neighbors 1D",
       11001, -5002.5, 50002.5);
     _h_muPC1_Y_final_cluster_autocorr_all_1D->GetXaxis()->SetTitle("time_2 - time_1");
   }
   if(Tier3)
   {
     _h_muPC1_Y_final_cluster_autocorr_spatial_all_1D = new TH1D("muPC1_Y_final_cluster_autocorr_spatial_all_1D", "#muPC1Y clustered autocorr neighbors spatial, 0-150 ns",
       kMuPC1NumYWires+1, -0.5, kMuPC1NumYWires+0.5);
     _h_muPC1_Y_final_cluster_autocorr_spatial_all_1D->GetXaxis()->SetTitle("wire_diff");
   }
   if(Tier1)
   {
     _h_muPC1_coinc_XY_tdiff = new TH1D("muPC1_coinc_XY_tdiff", "#muPC1 wires: T_{Y} - T_{X}",
       961, -600.625, 600.625);
     _h_muPC1_coinc_XY_tdiff->GetXaxis()->SetTitle("XYtdiff");
   }
   if(Tier1)
   {
     _h_muPC1_coinc_XY_2D = new TH2D("muPC1_coinc_XY_2D", "#muPC1 2D XY-coincidences",
       kMuPC1NumXWires, 0.5, kMuPC1NumXWires+0.5,
       kMuPC1NumYWires, 0.5, kMuPC1NumYWires+0.5);
     _h_muPC1_coinc_XY_2D->GetXaxis()->SetTitle("Xwire");
     _h_muPC1_coinc_XY_2D->GetYaxis()->SetTitle("Ywire");
   }
   if(Tier3)
   {
     _h_muPC1_coinc_XY_autocorr_all_1D = new TH1D("muPC1_coinc_XY_autocorr_all_1D", "#muPC1 XY-coinc autocorr neighbors 1D",
       11001, -5002.5, 50002.5);
     _h_muPC1_coinc_XY_autocorr_all_1D->GetXaxis()->SetTitle("muPC1Time_2 - muPC1Time_1");
   }
   _h_muSC_muPC1_time_difference = new TH1D("muSC_muPC1_time_difference", "Time difference of hits between muSC - muPC",
     501, -10020, 10020);
   _h_muSC_muPC1_time_difference->GetXaxis()->SetTitle("time-muPC1Time");
   if(Tier1)
   {
     _h_muPC1_coinc_XY_2D_with_muSC = new TH2D("muPC1_coinc_XY_2D_with_muSC", "#muPC1 2D XY-coincidences with muSC coincidence",
       kMuPC1NumXWires, 0.5, kMuPC1NumXWires+0.5,
       kMuPC1NumYWires, 0.5, kMuPC1NumYWires+0.5);
     _h_muPC1_coinc_XY_2D_with_muSC->GetXaxis()->SetTitle("Xwire");
     _h_muPC1_coinc_XY_2D_with_muSC->GetYaxis()->SetTitle("Ywire");
   }
   if(Tier1)
   {
     _h_muPC1_spark_clustered_blocktime = new TH1D("muPC1_spark_clustered_blocktime", "Time of muPC1 sparks, after clustering (500ms window)",
       500, 0, 500000000);
     _h_muPC1_spark_clustered_blocktime->GetXaxis()->SetTitle("time");
   }
   if(Tier1)
   {
     _h_muPC1_spark_chamberwide_count = new TH1D("muPC1_spark_chamberwide_count", "Number of 2-plane muPC1 sparks",
       3, -0.5, 2.5);
     _h_muPC1_spark_chamberwide_count->GetXaxis()->SetTitle("1");
   }
   if(Tier1)
   {
     _h_muPC1_spark_chamberwide_blocktime = new TH1D("muPC1_spark_chamberwide_blocktime", "Time of 2-plane muPC1 sparks (500ms window)",
       500, 0, 500000000);
     _h_muPC1_spark_chamberwide_blocktime->GetXaxis()->SetTitle("time");
   }
   return SUCCESS;
 }
Variable Documentation
TH2D* _h_muPC1_coinc_XY_2D static
Definition at line 1361 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH2D* _h_muPC1_coinc_XY_2D_with_muSC static
Definition at line 1474 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_coinc_XY_autocorr_all_1D static
Definition at line 1415 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_coinc_XY_tdiff static
Definition at line 1352 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_spark_chamberwide_blocktime static
Definition at line 1534 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_spark_chamberwide_count static
Definition at line 1533 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_spark_clustered_blocktime static
Definition at line 1526 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_spark_count_Xwires static
Definition at line 171 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_spark_count_Ywires static
Definition at line 778 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_spark_search_Xwires static
Definition at line 164 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_spark_search_Ywires static
Definition at line 771 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH2D* _h_muPC1_X_AD_autocorr_2D static
Definition at line 373 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_X_AD_autocorr_all_1D static
Definition at line 372 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_X_cluster_contiguous_separation static
Definition at line 478 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_X_final_cluster_autocorr_all_1D static
Definition at line 601 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_X_final_cluster_autocorr_spatial_all_1D static
Definition at line 660 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_X_final_cluster_avg static
Definition at line 536 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_X_final_cluster_size static
Definition at line 534 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_X_final_cluster_width static
Definition at line 535 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH2D* _h_muPC1_X_raw_autocorr_2D static
Definition at line 114 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_X_raw_autocorr_all_1D static
Definition at line 113 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH2D* _h_muPC1_X_raw_autosingles_2D static
Definition at line 112 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH2D* _h_muPC1_X_SC_autocorr_2D static
Definition at line 271 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_X_SC_autocorr_all_1D static
Definition at line 270 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH2D* _h_muPC1_Y_AD_autocorr_2D static
Definition at line 980 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_Y_AD_autocorr_all_1D static
Definition at line 979 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_Y_cluster_contiguous_separation static
Definition at line 1085 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_Y_final_cluster_autocorr_all_1D static
Definition at line 1208 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_Y_final_cluster_autocorr_spatial_all_1D static
Definition at line 1267 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_Y_final_cluster_avg static
Definition at line 1143 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_Y_final_cluster_size static
Definition at line 1141 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_Y_final_cluster_width static
Definition at line 1142 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH2D* _h_muPC1_Y_raw_autocorr_2D static
Definition at line 721 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_Y_raw_autocorr_all_1D static
Definition at line 720 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH2D* _h_muPC1_Y_raw_autosingles_2D static
Definition at line 719 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH2D* _h_muPC1_Y_SC_autocorr_2D static
Definition at line 878 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muPC1_Y_SC_autocorr_all_1D static
Definition at line 877 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_muSC_muPC1_time_difference static
Definition at line 1473 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
TH1D* _h_parameters_muPC1 static
Definition at line 53 of file MMuPC1AnalysisMQL.cpp.
Referenced by MMuPC1AnalysisMQL(), and MMuPC1AnalysisMQL_init().
MqlArray<struct _u_MMuPC1AnalysisMQL_1> _t_hits static
Definition at line 45 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_32> _t_muPC1 static
Definition at line 1359 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_33> _t_muPC1_auto static
Definition at line 1367 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_2> _t_muPC1_hits static
Definition at line 51 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_38> _t_muPC1_sparks_chamberwide static
Definition at line 1531 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_37> _t_muPC1_sparks_clustered static
Definition at line 1505 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_36> _t_muPC1_sparks_union static
Definition at line 1479 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_13> _t_muPC1X static
Definition at line 486 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_9> _t_muPC1X_AD static
Definition at line 277 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_10> _t_muPC1X_AD_auto static
Definition at line 328 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_15> _t_muPC1X_auto static
Definition at line 549 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_11> _t_muPC1X_cluster_contiguous static
Definition at line 380 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_12> _t_muPC1X_cluster_contiguous_sep static
Definition at line 430 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_14> _t_muPC1X_export static
Definition at line 542 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_3> _t_muPC1X_raw static
Definition at line 59 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_4> _t_muPC1X_raw_auto static
Definition at line 68 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_7> _t_muPC1X_SC static
Definition at line 177 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_8> _t_muPC1X_SC_auto static
Definition at line 226 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_5> _t_muPC1X_spark_search static
Definition at line 120 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_6> _t_muPC1X_sparks static
Definition at line 169 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_16> _t_muPC1X_spatial_auto static
Definition at line 608 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_31> _t_muPC1XY static
Definition at line 1275 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_27> _t_muPC1Y static
Definition at line 1093 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_23> _t_muPC1Y_AD static
Definition at line 884 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_24> _t_muPC1Y_AD_auto static
Definition at line 935 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_25> _t_muPC1Y_cluster_contiguous static
Definition at line 987 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_26> _t_muPC1Y_cluster_contiguous_sep static
Definition at line 1037 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_28> _t_muPC1Y_export static
Definition at line 1149 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_17> _t_muPC1Y_raw static
Definition at line 666 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_18> _t_muPC1Y_raw_auto static
Definition at line 675 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_21> _t_muPC1Y_SC static
Definition at line 784 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_22> _t_muPC1Y_SC_auto static
Definition at line 833 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_19> _t_muPC1Y_spark_search static
Definition at line 727 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_20> _t_muPC1Y_sparks static
Definition at line 776 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_30> _t_muPC1Y_spatial_auto static
Definition at line 1215 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_29> _t_muPC1Y_temporal_auto static
Definition at line 1156 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_34> _t_muSC static
Definition at line 1420 of file MMuPC1AnalysisMQL.cpp.
MqlArray<struct _u_MMuPC1AnalysisMQL_35> _t_muSC_muPC1 static
Definition at line 1429 of file MMuPC1AnalysisMQL.cpp.
ANA_MODULE MMuPC1AnalysisMQL_module
Initial value:
=
{
  "MMuPC1AnalysisMQL",
  "MqlCompiler",
  MMuPC1AnalysisMQL,
  NULL,
  NULL,
  MMuPC1AnalysisMQL_init,
  NULL,
  NULL,
  0,
  NULL,
}
Definition at line 22 of file MMuPC1AnalysisMQL.cpp.