AlcapDAQ: analyzer/src/Timing/MShortPulseTimes.cpp File Reference
MShortPulseTimes.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <map>
#include <utility>
#include <sstream>
#include "midas.h"
#include <TH1.h>
#include "TOctalFADCIsland.h"
#include "TOctalFADCBankReader.h"
#include "TGlobalData.h"
#include "TSetupData.h"
#include "TPulseIsland.h"
Functions
INT MShortPulseTimes_init (void)
INT MShortPulseTimes (EVENT_HEADER *, void *)
vector< string > GetAllBankNames ()
double GetClockTickForChannel (string bank_name)
Variables
string testname = "CaenCh0"
HNDLE hDB
TGlobalData * gData
TSetupData * gSetup
static vector
< TOctalFADCBankReader * > fadc_bank_readers
static std::map< std::string,
TH1 * > time_short_pulse_histogram_map
static std::map< std::string,
TH1 * > time_nshort_pulse_histogram_map
ANA_MODULE MShortPulseTimes_module
Function Documentation
vector<string> GetAllBankNames ()
double GetClockTickForChannel (string bank_name)
INT MShortPulseTimes (EVENT_HEADER * pheader, void * pevent)
This method processes one MIDAS block, producing a vector of TOctalFADCIsland objects from the raw Octal FADC data.
Definition at line 109 of file MShortPulseTimes.cpp.
References TGlobalData::fPulseIslandToChannelMap, TSetupData::GetDetectorName(), printf(), and SUCCESS.
 {
         // Get the event number
         int midas_event_number = pheader->serial_number;
         // Some typedefs
         typedef map<string, vector<TPulseIsland*> > TStringPulseIslandMap;
         typedef pair<string, vector<TPulseIsland*> > TStringPulseIslandPair;
         typedef map<string, vector<TPulseIsland*> >::iterator map_iterator;
         // Fetch a reference to the gData structure that stores a map
         // of (bank_name, vector<TPulseIsland*>) pairs
         TStringPulseIslandMap& pulse_islands_map =
                 gData->fPulseIslandToChannelMap;
         // Loop over the map and get each bankname, vector pair
         for (map_iterator theMapIter = pulse_islands_map.begin(); theMapIter != pulse_islands_map.end(); theMapIter++)
         {
           std::string bankname = theMapIter->first;
           std::vector<TPulseIsland*> thePulses = theMapIter->second;
           // Loop over the TPulseIslands and plot the histogram
           for (std::vector<TPulseIsland*>::iterator thePulseIter = thePulses.begin(); thePulseIter != thePulses.end(); thePulseIter++) {
         if (gSetup->GetDetectorName(theMapIter->first)=="CDG0" && ((*thePulseIter)->GetSamples().size()>0)) printf("\nfound caen\n");
         //samples = (*thePulseIter)->GetSamples();
         if ((*thePulseIter)->GetSamples().size()==4) time_short_pulse_histogram_map[bankname]->Fill((*thePulseIter)->GetPulseTime());
         else time_nshort_pulse_histogram_map[bankname]->Fill((*thePulseIter)->GetPulseTime());
           }
         }
         return SUCCESS;
 }
INT MShortPulseTimes_init ()
This method initializes histograms.
Definition at line 68 of file MShortPulseTimes.cpp.
References TSetupData::fBankToDetectorMap, TSetupData::GetDetectorName(), and SUCCESS.
 {
   // This histogram has the pulse times on the X-axis and the number of pulses on the Y-axis
   // One histogram is created for each detector
   // This uses the TH1::kCanRebin mechanism to expand automatically to the
   // number of FADC banks.
   std::map<std::string, std::string> bank_to_detector_map = gSetup->fBankToDetectorMap;
   for(std::map<std::string, std::string>::iterator mapIter = bank_to_detector_map.begin();
       mapIter != bank_to_detector_map.end(); mapIter++) {
     std::string detname = gSetup->GetDetectorName(mapIter->first);
     std::string histname = "h" + detname + "_ShortPulseTimes";
     std::string histtitle = "Plot of the short pulse times for the " + detname + " detector";
     TH1D* hShortPulseTime = new TH1D(histname.c_str(),histtitle.c_str(),240,0,120e6);
     hShortPulseTime->GetXaxis()->SetTitle("Pulse time (ns)");
     hShortPulseTime->GetXaxis()->CenterTitle(1);
     hShortPulseTime->GetYaxis()->SetTitle("Number of 4-sample pulses");
     hShortPulseTime->GetYaxis()->CenterTitle(1);
     //hShortPulseTime->SetBit(TH1::kCanRebin);
     std::string histname2 = "h" + detname + "_NonShortPulseTimes";
     std::string histtitle2 = "Plot of the non-short pulse times for the " + detname + " detector";
     TH1D* hNonShortPulseTime = new TH1D(histname2.c_str(),histtitle2.c_str(),240,0,120e6);
     hNonShortPulseTime->GetXaxis()->SetTitle("Pulse time (ns)");
     hNonShortPulseTime->GetXaxis()->CenterTitle(1);
     hNonShortPulseTime->GetYaxis()->SetTitle("Number of all other pulses");
     hNonShortPulseTime->GetYaxis()->CenterTitle(1);
     //hNonShortPulseTime->SetBit(TH1::kCanRebin);
     time_short_pulse_histogram_map[mapIter->first] = hShortPulseTime;
     time_nshort_pulse_histogram_map[mapIter->first] = hNonShortPulseTime;
   }
   return SUCCESS;
 }
Variable Documentation
vector<TOctalFADCBankReader*> fadc_bank_readers static
Definition at line 47 of file MShortPulseTimes.cpp.
TGlobalData* gData
Definition at line 54 of file analyzer.cpp.
TSetupData* gSetup
Definition at line 55 of file analyzer.cpp.
HNDLE hDB
Definition at line 11 of file mucap_compress.cpp.
ANA_MODULE MShortPulseTimes_module
Initial value:
=
{
        "MShortPulseTimes",
        "Joe Grange",
        MShortPulseTimes,
        NULL,
        NULL,
        MShortPulseTimes_init,
        NULL,
        NULL,
        0,
        NULL,
}
Definition at line 52 of file MShortPulseTimes.cpp.
string testname = "CaenCh0"
Definition at line 42 of file MShortPulseTimes.cpp.
std::map<std::string, TH1*> time_nshort_pulse_histogram_map static
Definition at line 50 of file MShortPulseTimes.cpp.
std::map<std::string, TH1*> time_short_pulse_histogram_map static
Definition at line 49 of file MShortPulseTimes.cpp.