AlcapDAQ: analyzer/compress/mucap_compress.h File Reference
mucap_compress.h File Reference
Data Structures
struct io_buffer
struct huffman_table
struct rle_state
Typedefs
typedef struct io_buffer io_buffer
typedef struct huffman_node huffman_node
typedef struct huffman_table huffman_table
typedef struct rle_state rle_state
typedef struct tdc400_word tdc400_word
typedef struct stack_elt stack_elt
typedef struct caen_word caen_word
typedef struct channel_hit channel_hit
typedef union comp_word comp_word
typedef struct fadc_word fadc_word
typedef struct nfadc_word nfadc_word
typedef struct n2fadc_tpc_word n2fadc_tpc_word
typedef struct n2fadc_ndet_word n2fadc_ndet_word
typedef int(* expand_fcn)(unsigned char *input, int input_size, void *output, int userParam)
Functions
void start_output_buffer (io_buffer *buffer, unsigned char *p)
int flush_output_buffer (io_buffer *buffer)
void io_buffer_put (io_buffer *buffer, unsigned int code_bits, int code_length)
void start_input_buffer (io_buffer *buffer, unsigned char *p)
unsigned int io_buffer_get (io_buffer *buffer, int num_bits)
void huffman_put_symbol (huffman_table *table, io_buffer *buffer, int symbol)
int huffman_get_symbol (huffman_table *table, io_buffer *buffer)
BOOL huffman_optimize_tree (huffman_table *table)
void huffman_init_default (huffman_table *table, int num_symbols)
BOOL save_huffman (char *key_dir, huffman_table *table)
BOOL load_huffman (char *key_dir, huffman_table *table)
void rle_bits_setup ()
void rle_put (unsigned char b, rle_state *s, io_buffer *output)
int flush_rle (rle_state *s, io_buffer *output)
int rle_get (io_buffer *input, rle_state *s)
void tdc400_load ()
void tdc400_optimize ()
int tdc400_compress (tdc400_word *input, int input_size, unsigned char *output, int userParam)
int tdc400_expand (unsigned char *input, int input_size, tdc400_word *output, int userParam)
void stck_load ()
void stck_optimize ()
int stck_compress (stack_elt *input, int input_size, unsigned char *output, int userParam)
int stck_expand (unsigned char *input, int input_size, stack_elt *output, int userParam)
void comp_load ()
void comp_optimize ()
int caen_compress (caen_word *input, int input_size, unsigned char *output, int userParam)
int caen_expand (unsigned char *input, int input_size, caen_word *output, int userParam)
void hits_load ()
void hits_optimize ()
int hits_compress (channel_hit *input, int input_size, unsigned char *output, int userParam)
int hits_expand (unsigned char *input, int input_size, channel_hit *output, int userParam)
void caen_load ()
void caen_optimize ()
int cmp_compress (comp_word *input, int input_size, unsigned char *output, int userParam)
int cmp_expand (unsigned char *input, int input_size, comp_word *output, int userParam)
void fadc_load ()
void fadc_optimize ()
int fadc_compress (fadc_word *input, int input_size, unsigned char *output, int userParam)
int fadc_expand (unsigned char *input, int input_size, fadc_word *output, int userParam)
void nfadc_load ()
void nfadc_optimize ()
int nfadc_compress (unsigned char *input, int input_size, unsigned char *output, int userParam)
int nfadc_expand (unsigned char *input, int input_size, unsigned char *output, int userParam)
void n2fadc_tpc_load ()
void n2fadc_tpc_optimize ()
int n2fadc_tpc_compress (unsigned char *input, int input_size, unsigned char *output, int userParam)
int n2fadc_tpc_expand (unsigned char *input, int input_size, unsigned char *output, int userParam)
void n2fadc_ndet_load ()
void n2fadc_ndet_optimize ()
int n2fadc_ndet_compress (unsigned char *input, int input_size, unsigned char *output, int userParam)
int n2fadc_ndet_expand (unsigned char *input, int input_size, unsigned char *output, int userParam)
int read_midas_event (FILE *fp, char *pevent)
void compress_event (void *input_event, void *output_event, bool USE_OLD_COMPRESSION=false)
void compress_event_skim (void *input_event, void *output_event, bool keep_etc, bool USE_OLD_COMPRESSION=false)
void expand_event (void *input_event, void *output_event, bool USE_OLD_COMPRESSION=false)
void expand_bank (unsigned char *input_data, int input_size, void *output_event, char *output_name, expand_fcn f, int userParam)
void compress_load_all (bool USE_OLD_COMPRESSION=false)
void compress_optimize_all (bool USE_OLD_COMPRESSION=false)
Variables
huffman_table time_huffman
huffman_table bits_huffman [2]
BOOL should_compress_tdc400
huffman_table caen_channel_huffman
BOOL should_compress_caen
huffman_table cmp_channel_huffman
huffman_table cmp_bits_huffman [2]
BOOL should_compress_comp
huffman_table fadc_run_huffman
huffman_table fadc_small_huffman
BOOL should_compress_fadc
BOOL should_compress_nfadc
BOOL should_compress_n2fadc_tpc
BOOL should_compress_n2fadc_ndet
HNDLE hDB
Typedef Documentation
typedef struct caen_word caen_word
Definition at line 81 of file mucap_compress.h.
typedef struct channel_hit channel_hit
Definition at line 93 of file mucap_compress.h.
typedef union comp_word comp_word
Definition at line 102 of file mucap_compress.h.
typedef int(* expand_fcn)(unsigned char *input, int input_size, void *output, int userParam)
Definition at line 164 of file mucap_compress.h.
typedef struct fadc_word fadc_word
Definition at line 114 of file mucap_compress.h.
typedef struct huffman_node huffman_node
Definition at line 20 of file mucap_compress.h.
typedef struct huffman_table huffman_table
typedef struct io_buffer io_buffer
typedef struct n2fadc_ndet_word n2fadc_ndet_word
Definition at line 150 of file mucap_compress.h.
typedef struct n2fadc_tpc_word n2fadc_tpc_word
Definition at line 139 of file mucap_compress.h.
typedef struct nfadc_word nfadc_word
Definition at line 126 of file mucap_compress.h.
typedef struct rle_state rle_state
typedef struct stack_elt stack_elt
Definition at line 70 of file mucap_compress.h.
typedef struct tdc400_word tdc400_word
Definition at line 56 of file mucap_compress.h.
Function Documentation
int caen_compress (caen_word * input, int input_size, unsigned char * output, int userParam)
Definition at line 117 of file caen_compress.cpp.
References encode_caen(), rle_bits_setup(), and start_output_buffer().
Referenced by compress_event().
 {
   input_size /= sizeof(caen_word);
   rle_bits_setup();
   io_buffer output_buffer;
   // reserve space for size of uncompressed data (may be different from
   // input size, since some hits may be stripped)
   int *uncompressed_size_p = (int *) output;
   output += sizeof(int);
   // reserve space for the size of the compressed data
   int *compressed_time_size_p = (int *) output;
   output += sizeof(int);
   // compress times
   start_output_buffer(&output_buffer, output);
   int compressed_time_size =
       encode_caen(input, input_size, &output_buffer, uncompressed_size_p);
   output += compressed_time_size;
   // store size of compressed times
   *compressed_time_size_p = compressed_time_size;
   return compressed_time_size + 2 * sizeof(int);
 }
int caen_expand (unsigned char * input, int input_size, caen_word * output, int userParam)
Definition at line 219 of file caen_compress.cpp.
References decode_caen(), rle_bits_setup(), and start_input_buffer().
Referenced by expand_event().
 {
   //
   // Uncompress the data produced by caen_compress().
   //
   rle_bits_setup();
   // Get uncompressed data size
   int *uncompressed_size_p = (int *) input;
   int uncompressed_size = *uncompressed_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Get size of compressed time data
   int *compressed_time_size_p = (int *) input;
   int compressed_time_size = *compressed_time_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress times
   io_buffer input_buffer;
   start_input_buffer(&input_buffer, input);
   decode_caen(&input_buffer, output);
   input += compressed_time_size;
   input_size -= compressed_time_size;
   return uncompressed_size * sizeof(caen_word);
 }
void caen_load ()
Definition at line 25 of file caen_compress.cpp.
References hDB, huffman_init_default(), load_huffman(), should_compress_caen, should_strip_r1, should_strip_trailing_edge, size, and TRUE.
Referenced by compress_load_all().
 {
   huffman_init_default(&caen_channel_huffman, 129);
   load_huffman("/Compression/Lossless/CAEN/Huffman/Channel", &caen_channel_huffman);
   int size = sizeof(BOOL);
   db_get_value(hDB, 0, "/Compression/Lossless/CAEN/Enabled", &should_compress_caen,
     &size, TID_BOOL, TRUE);
   size = sizeof(BOOL);
   db_get_value(hDB, 0, "/Compression/Lossless/CAEN/Strip trailing edge",
     &should_strip_trailing_edge, &size, TID_BOOL, TRUE);
   size = sizeof(BOOL);
   db_get_value(hDB, 0, "/Compression/Lossless/CAEN/Strip R1",
     &should_strip_r1, &size, TID_BOOL, TRUE);
 }
void caen_optimize ()
Definition at line 19 of file caen_compress.cpp.
References huffman_optimize_tree(), and save_huffman().
Referenced by compress_optimize_all().
 {
   huffman_optimize_tree(&caen_channel_huffman);
   save_huffman("/Compression/Lossless/CAEN/Huffman/Channel", &caen_channel_huffman);
 }
int cmp_compress (comp_word * input, int input_size, unsigned char * output, int userParam)
Definition at line 133 of file comp_compress.cpp.
References encode_cmp_bits(), encode_cmp_times(), rle_bits_setup(), and start_output_buffer().
Referenced by compress_event().
 {
   //
   // Encode compressor data, which are in the following format:
   // | B | A | FPGA number (6 bits) | Time (24 bits) |
   // ... followed by one or two 32-bit masks indicating which
   // channels
   // within the group have fired.
   //
   input_size /= sizeof(comp_word);
   rle_bits_setup();
   io_buffer output_buffer;
   // store size of input data
   int *uncompressed_size_p = (int *) output;
   *uncompressed_size_p = input_size;
   output += sizeof(int);
   // reserve space for the size of the compressed times
   int *compressed_time_size_p = (int *) output;
   output += sizeof(int);
   // compress times
   start_output_buffer(&output_buffer, output);
   int compressed_time_size =
       encode_cmp_times(input, input_size, &output_buffer);
   output += compressed_time_size;
   // store size of compressed times
   *compressed_time_size_p = compressed_time_size;
   // reserve space for the size of the compressed bit patterns
   int *compressed_bits_size_p = (int *) output;
   output += sizeof(int);
   // compress bit patterns
   start_output_buffer(&output_buffer, output);
   int compressed_bits_size =
       encode_cmp_bits(input, input_size, &output_buffer);
   output += compressed_time_size;
   // store size of compressed bit patterns
   *compressed_bits_size_p = compressed_bits_size;
   return compressed_time_size + compressed_bits_size + 3 * sizeof(int);
 }
int cmp_expand (unsigned char * input, int input_size, comp_word * output, int userParam)
Definition at line 243 of file comp_compress.cpp.
References decode_cmp_bits(), decode_cmp_times(), rle_bits_setup(), and start_input_buffer().
Referenced by expand_event().
 {
   //
   // Uncompress the data produced by cmp_compress().
   //
   rle_bits_setup();
   // Get uncompressed data size
   int *uncompressed_size_p = (int *) input;
   int uncompressed_size = *uncompressed_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Get size of compressed time data
   int *compressed_time_size_p = (int *) input;
   int compressed_time_size = *compressed_time_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress times
   io_buffer input_buffer;
   start_input_buffer(&input_buffer, input);
   decode_cmp_times(&input_buffer, output);
   input += compressed_time_size;
   input_size -= compressed_time_size;
   // Get size of compressed bit patterns
   int *compressed_bits_size_p = (int *) input;
   int compressed_bits_size = *compressed_bits_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress bit patterns
   start_input_buffer(&input_buffer, input);
   decode_cmp_bits(&input_buffer, output, uncompressed_size);
   return uncompressed_size * sizeof(comp_word);
 }
void comp_load ()
Definition at line 29 of file comp_compress.cpp.
References hDB, huffman_init_default(), load_huffman(), should_compress_comp, size, and TRUE.
Referenced by compress_load_all().
 {
   huffman_init_default(&cmp_channel_huffman, 256);
   huffman_init_default(&cmp_bits_huffman[0], 128);
   huffman_init_default(&cmp_bits_huffman[1], 128);
   load_huffman("/Compression/Lossless/COMP/Huffman/Channel", &cmp_channel_huffman);
   load_huffman("/Compression/Lossless/COMP/Huffman/Bits 0", &cmp_bits_huffman[0]);
   load_huffman("/Compression/Lossless/COMP/Huffman/Bits 1", &cmp_bits_huffman[1]);
   int size = sizeof(BOOL);
   db_get_value(hDB, 0, "/Compression/Lossless/COMP/Enabled", &should_compress_comp,
     &size, TID_BOOL, TRUE);
 }
void comp_optimize ()
Definition at line 18 of file comp_compress.cpp.
References huffman_optimize_tree(), and save_huffman().
Referenced by compress_optimize_all().
 {
   huffman_optimize_tree(&cmp_channel_huffman);
   huffman_optimize_tree(&cmp_bits_huffman[0]);
   huffman_optimize_tree(&cmp_bits_huffman[1]);
   save_huffman("/Compression/Lossless/COMP/Huffman/Channel", &cmp_channel_huffman);
   save_huffman("/Compression/Lossless/COMP/Huffman/Bits 0", &cmp_bits_huffman[0]);
   save_huffman("/Compression/Lossless/COMP/Huffman/Bits 1", &cmp_bits_huffman[1]);
 }
void compress_event (void * input_event, void * output_event, bool USE_OLD_COMPRESSION = false)
Definition at line 69 of file overall.cpp.
References caen_compress(), cmp_compress(), compress_bank(), fadc_compress(), n2fadc_ndet_compress(), n2fadc_tpc_compress(), nfadc_compress(), printf(), should_compress_caen, should_compress_comp, should_compress_fadc, should_compress_n2fadc_ndet, should_compress_n2fadc_tpc, should_compress_nfadc, should_compress_tdc400, sprintf(), and tdc400_compress().
Referenced by eb_user(), and main().
 {
     // If it's not a 32-bit event, just copy from input to output
     BANK_HEADER *bank_header = (BANK_HEADER *)input_event;
     BOOL is_32 = (bank_header->flags & BANK_FORMAT_32BIT);
     if(!is_32) {
       memcpy(output_event, input_event,
                  bank_header->data_size + sizeof(BANK_HEADER));
       return;
     }
     BANK32 *input_bank = NULL;
     void *input_data = NULL;
     while (1) {
         int input_size =
             bk_iterate32(input_event, &input_bank, &input_data);
         if (input_bank == NULL) {
             break;
         }
         char output_name[5];
         if (should_compress_tdc400 && !strncmp(input_bank->name, "TDC", 3)) {
             sprintf(output_name, "CTD%c", input_bank->name[3]);
             compress_bank(input_data, input_size, output_event,
                           output_name, (comp_fcn) tdc400_compress, 0);
         } else if (should_compress_fadc
                    && !strncmp(input_bank->name, "ADC", 3)) {
           sprintf(output_name, "CAD%c", input_bank->name[3]);
           compress_bank(input_data, input_size, output_event,
                         output_name, (comp_fcn) fadc_compress, 0);
         } else if (USE_OLD_COMPRESSION &&
                    should_compress_nfadc
                    && input_bank->name[0] == 'N'
                    && (input_bank->name[1] == 'a' ||
                        input_bank->name[1] == 'b' ||
                        input_bank->name[1] == 'c' ||
                        input_bank->name[1] == 'd')
                    && isxdigit(input_bank->name[2])
                    && isxdigit(input_bank->name[3])) {
           printf("Using run10 compression\n");
           sprintf(output_name, "n%c%c%c", input_bank->name[1],
                   input_bank->name[2], input_bank->name[3]);
           int board_number = 16*(input_bank->name[2]-'0') + (input_bank->name[3]-'0');
           compress_bank(input_data, input_size, output_event,
                         output_name, (comp_fcn) nfadc_compress, board_number);
         } //start paste
         else if (!USE_OLD_COMPRESSION &&
                  input_bank->name[0] == 'N'
                  && input_bank->name[1] >= 'a'
                  && input_bank->name[1] <= 'h'
                  && isxdigit(input_bank->name[2])
                  && isxdigit(input_bank->name[3])) {
           printf("Using run11+ compression\n");
           sprintf(output_name, "n%c%c%c", input_bank->name[1],
                   input_bank->name[2], input_bank->name[3]);
           int board_number = 16*(input_bank->name[2]-'0') + (input_bank->name[3]-'0');
           if(board_number < 128 && should_compress_n2fadc_tpc) {
             compress_bank(input_data, input_size, output_event,
                           output_name, (comp_fcn) n2fadc_tpc_compress, board_number);
           }else if(should_compress_n2fadc_ndet) {
             compress_bank(input_data, input_size, output_event,
                           output_name, (comp_fcn) n2fadc_ndet_compress, board_number);
           }
         }//end paste
         else if (should_compress_caen
                  && !strncmp(input_bank->name, "CAE", 3)) {
           sprintf(output_name, "CCA%c", input_bank->name[3]);
           compress_bank(input_data, input_size, output_event,
                         output_name, (comp_fcn) caen_compress, 0);
         } else if (should_compress_comp
                    && !strncmp(input_bank->name, "CMP", 3)) {
           sprintf(output_name, "CCM%c", input_bank->name[3]);
           compress_bank(input_data, input_size, output_event,
                         output_name, (comp_fcn) cmp_compress, 0);
         } else {
           // Otherwise: if the input and output events are not the same,
           // just copy the bank whole.
           if(input_event != output_event) {
             char *output_data;
             bk_create(output_event, input_bank->name, input_bank->type,
                       &output_data);
             memcpy(output_data, input_data, input_size);
             bk_close(output_event, output_data + input_size);
           }
         }
     }
 }
void compress_event_skim (void * input_event, void * output_event, bool keep_etc, bool USE_OLD_COMPRESSION = false)
Definition at line 160 of file overall.cpp.
References compress_bank(), fadc_compress(), hits_compress(), n2fadc_ndet_compress(), n2fadc_tpc_compress(), nfadc_compress(), should_compress_n2fadc_ndet, should_compress_n2fadc_tpc, should_compress_nfadc, sprintf(), and stck_compress().
 {
   // If it's not a 32-bit event, just copy from input to output
   BANK_HEADER *bank_header = (BANK_HEADER *)input_event;
   BOOL is_32 = (bank_header->flags & BANK_FORMAT_32BIT);
   if(!is_32 || EVENT_ID(input_event) != 1) {
     memcpy(output_event, input_event,
            bank_header->data_size + sizeof(BANK_HEADER));
     return;
   }
   BANK32 *input_bank = NULL;
   void *input_data = NULL;
   while (1) {
     int input_size =
       bk_iterate32(input_event, &input_bank, &input_data);
     if (input_bank == NULL) {
       break;
     }
     char output_name[5];
     if (!strncmp(input_bank->name, "RTPC", 4)) {
       compress_bank(input_data, input_size, output_event,
                     "CTPC", (comp_fcn) stck_compress, 0);
     } else if (!strncmp(input_bank->name, "RHIT", 4)) {
       compress_bank(input_data, input_size, output_event,
                     "HITZ", (comp_fcn) hits_compress, 0);
     } else if (!strncmp(input_bank->name, "SKIM", 4)) {
       // save bank of gskim triggers
       if(input_event != output_event) {
         char *output_data;
         bk_create(output_event, "GSKM", input_bank->type,
                   &output_data);
         memcpy(output_data, input_data, input_size);
         bk_close(output_event, output_data + input_size);
       }
     } else if (USE_OLD_COMPRESSION &&
                should_compress_nfadc
                && input_bank->name[0] == 'N'
                && (input_bank->name[1] == 'a' ||
                    input_bank->name[1] == 'b' ||
                    input_bank->name[1] == 'c' ||
                    input_bank->name[1] == 'd')
                && isxdigit(input_bank->name[2])
                && isxdigit(input_bank->name[3])) {
       sprintf(output_name, "n%c%c%c", input_bank->name[1],
               input_bank->name[2], input_bank->name[3]);
       int board_number = 16*(input_bank->name[2]-'0') + (input_bank->name[3]-'0');
       compress_bank(input_data, input_size, output_event,
                     output_name, (comp_fcn) nfadc_compress, board_number);
     } //start paste
     else if (!USE_OLD_COMPRESSION &&
              input_bank->name[0] == 'N'
              && input_bank->name[1] >= 'a'
              && input_bank->name[1] <= 'h'
              && isxdigit(input_bank->name[2])
              && isxdigit(input_bank->name[3])) {
       sprintf(output_name, "n%c%c%c", input_bank->name[1],
               input_bank->name[2], input_bank->name[3]);
       int board_number = 16*(input_bank->name[2]-'0') + (input_bank->name[3]-'0');
       if(board_number < 128 && should_compress_n2fadc_tpc) {
         compress_bank(input_data, input_size, output_event,
                       output_name, (comp_fcn) n2fadc_tpc_compress, board_number);
       }else if(should_compress_n2fadc_ndet) {
         compress_bank(input_data, input_size, output_event,
                       output_name, (comp_fcn) n2fadc_ndet_compress, board_number);
       }
     }//end paste
     else if (!strncmp(input_bank->name, "ADC", 3)) {
       sprintf(output_name, "CAD%c", input_bank->name[3]);
       compress_bank(input_data, input_size, output_event,
                     output_name, (comp_fcn) fadc_compress, 0);
     } else if (keep_etc && (!strncmp(input_bank->name, "LAD", 3) ||
                             //                              !strncmp(input_bank->name, "LSPK", 4) ||
                             !strncmp(input_bank->name, "CAET", 4)))
       {
         // Otherwise: if the input and output events are not the same,
         // just copy the bank whole.
         if(input_event != output_event) {
           char *output_data;
           bk_create(output_event, input_bank->name, input_bank->type,
                     &output_data);
           memcpy(output_data, input_data, input_size);
           bk_close(output_event, output_data + input_size);
         }
       }
   }
 }
void compress_load_all (bool USE_OLD_COMPRESSION = false)
Definition at line 373 of file overall.cpp.
References caen_load(), comp_load(), fadc_load(), hits_load(), n2fadc_ndet_load(), n2fadc_tpc_load(), nfadc_load(), stck_load(), and tdc400_load().
Referenced by eb_begin_of_run(), main(), MUnCompressRawData_init(), and process_file().
 {
   tdc400_load();
   fadc_load();
   if (USE_OLD_COMPRESSION){
     nfadc_load();}
   else{
     n2fadc_tpc_load();
     n2fadc_ndet_load();
   }
   caen_load();
   comp_load();
   hits_load();
   stck_load();
 }
void compress_optimize_all (bool USE_OLD_COMPRESSION = false)
Definition at line 390 of file overall.cpp.
References caen_optimize(), comp_optimize(), fadc_optimize(), n2fadc_ndet_optimize(), n2fadc_tpc_optimize(), nfadc_optimize(), and tdc400_optimize().
Referenced by main().
 {
   tdc400_optimize();
   fadc_optimize();
   if (USE_OLD_COMPRESSION){
     nfadc_optimize();
   }
   else{
     n2fadc_tpc_optimize();
     n2fadc_ndet_optimize();
   }
   caen_optimize();
   comp_optimize();
 }
void expand_bank (unsigned char * input_data, int input_size, void * output_event, char * output_name, expand_fcn f, int userParam)
Definition at line 255 of file overall.cpp.
References printf().
Referenced by expand_event().
 {
   unsigned char *uncompressed_bank;
   int bank_type = TID_DWORD;
   if(output_name[0] == 'N') bank_type = TID_BYTE;
   bk_create(output_event, output_name, bank_type, &uncompressed_bank);
   // uncompress the data; "sizeof(int)" accounts for the checksum word
   int uncompressed_size = (*f) (input_data, input_size - sizeof(int),
                                 uncompressed_bank, userParam);
   // verify the Adler32 checksum
   int checksum = adler32(0x5555, uncompressed_bank, uncompressed_size);
   int *checksum_ptr = (int *) &input_data[input_size-sizeof(int)];
   if(checksum != *checksum_ptr) {
     printf("*** CHECKSUM TEST FAILED: Bank %s (0x%x -> 0x%x) ***\n",
            output_name, *checksum_ptr, checksum);
   } else {
     //       printf("Checksum OK for bank %s (0x%x)\n", output_name, checksum);
   }
   bk_close(output_event, uncompressed_bank + uncompressed_size);
 }
void expand_event (void * input_event, void * output_event, bool USE_OLD_COMPRESSION = false)
Definition at line 283 of file overall.cpp.
References caen_expand(), cmp_expand(), expand_bank(), fadc_expand(), hits_expand(), n2fadc_ndet_expand(), n2fadc_tpc_expand(), nfadc_expand(), sprintf(), stck_expand(), and tdc400_expand().
Referenced by main(), MUnCompressRawData(), and process_file().
 {
   // If it's not a 32-bit event, just copy from input to output
   BANK_HEADER *bank_header = (BANK_HEADER *)input_event;
   BOOL is_32 = (bank_header->flags & BANK_FORMAT_32BIT);
   if(!is_32) {
     memcpy(output_event, input_event,
            bank_header->data_size + sizeof(BANK_HEADER));
     return;
   }
   BANK32 *input_bank = NULL;
   unsigned char *input_data = NULL;
   while (1) {
     int input_size =
       bk_iterate32(input_event, &input_bank, &input_data);
     if (input_bank == NULL) {
       break;
     }
     char output_name[5];
     if (!strncmp(input_bank->name, "CTD", 3)) {
       sprintf(output_name, "TDC%c", input_bank->name[3]);
       expand_bank(input_data, input_size, output_event,
                   output_name, (expand_fcn) tdc400_expand, 0);
     } else if(USE_OLD_COMPRESSION &&
               input_bank->name[0] == 'n'
               && (input_bank->name[1] == 'a' ||
                   input_bank->name[1] == 'b' ||
                   input_bank->name[1] == 'c' ||
                   input_bank->name[1] == 'd')
               && isxdigit(input_bank->name[2])
               && isxdigit(input_bank->name[3])) {
       sprintf(output_name, "N%c%c%c", input_bank->name[1],
               input_bank->name[2], input_bank->name[3]);
       int board_number = 16*(input_bank->name[2]-'0') + (input_bank->name[3]-'0');
       expand_bank(input_data, input_size, output_event,
                   output_name, (expand_fcn) nfadc_expand, board_number);
     }
     else if(!USE_OLD_COMPRESSION &&
             input_bank->name[0] == 'n'
             && input_bank->name[1] >= 'a'
             && input_bank->name[1] <= 'h'
             && isxdigit(input_bank->name[2])
             && isxdigit(input_bank->name[3])) {
       sprintf(output_name, "N%c%c%c", input_bank->name[1],
               input_bank->name[2], input_bank->name[3]);
       int board_number = 16*(input_bank->name[2]-'0') + (input_bank->name[3]-'0');
       if(board_number < 128) {
         expand_bank(input_data, input_size, output_event,
                     output_name, (expand_fcn) n2fadc_tpc_expand, board_number);
       } else {
         expand_bank(input_data, input_size, output_event,
                     output_name, (expand_fcn) n2fadc_ndet_expand, board_number);
       }
     }
     else if (!strncmp(input_bank->name, "CAD", 3)) {
       sprintf(output_name, "ADC%c", input_bank->name[3]);
       expand_bank(input_data, input_size, output_event,
                   output_name, (expand_fcn) fadc_expand, 0);
     } else if (!strncmp(input_bank->name, "CCA", 3)) {
       sprintf(output_name, "CAE%c", input_bank->name[3]);
       expand_bank(input_data, input_size, output_event,
                   output_name, (expand_fcn) caen_expand, 0);
     } else if (!strncmp(input_bank->name, "CCM", 3)) {
       sprintf(output_name, "CMP%c", input_bank->name[3]);
       expand_bank(input_data, input_size, output_event,
                   output_name, (expand_fcn) cmp_expand, 0);
     } else if (!strncmp(input_bank->name, "HITZ", 4)) {
       expand_bank(input_data, input_size, output_event,
                   "HITS", (expand_fcn) hits_expand, 0);
     } else if (!strncmp(input_bank->name, "CTPC", 4)) {
       expand_bank(input_data, input_size, output_event,
                   "STCK", (expand_fcn) stck_expand, 0);
     } else {
       // Otherwise: if the input and output events are not the same,
       // just copy the bank whole.
       if(input_event != output_event) {
         char *output_data;
         bk_create(output_event, input_bank->name, input_bank->type,
                   &output_data);
         memcpy(output_data, input_data, input_size);
         bk_close(output_event, output_data + input_size);
       }
     }
   }
 }
int fadc_compress (fadc_word * input, int input_size, unsigned char * output, int userParam)
Definition at line 92 of file fadc_compress.cpp.
References encode_fadc(), rle_bits_setup(), and start_output_buffer().
Referenced by compress_event(), and compress_event_skim().
 {
   input_size /= sizeof(fadc_word);
   rle_bits_setup();
   io_buffer output_buffer;
   // store size of input data
   int *uncompressed_size_p = (int *) output;
   *uncompressed_size_p = input_size;
   output += sizeof(int);
   // reserve space for the size of the compressed data
   int *compressed_time_size_p = (int *) output;
   output += sizeof(int);
   // compress samples
   start_output_buffer(&output_buffer, output);
   int compressed_size = encode_fadc(input, input_size, &output_buffer);
   output += compressed_size;
   // store size of compressed times
   *compressed_time_size_p = compressed_size;
   return compressed_size + 2 * sizeof(int);
 }
int fadc_expand (unsigned char * input, int input_size, fadc_word * output, int userParam)
Definition at line 165 of file fadc_compress.cpp.
References decode_fadc(), rle_bits_setup(), and start_input_buffer().
Referenced by expand_event().
 {
   //
   // Uncompress the data produced by caen_compress().
   //
   rle_bits_setup();
   // Get uncompressed data size
   int *uncompressed_size_p = (int *) input;
   int uncompressed_size = *uncompressed_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Get size of compressed data
   int *compressed_size_p = (int *) input;
   int compressed_size = *compressed_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress data
   io_buffer input_buffer;
   start_input_buffer(&input_buffer, input);
   decode_fadc(&input_buffer, output, uncompressed_size);
   input += compressed_size;
   input_size -= compressed_size;
   return uncompressed_size * sizeof(fadc_word);
 }
void fadc_load ()
Definition at line 29 of file fadc_compress.cpp.
References hDB, huffman_init_default(), load_huffman(), should_compress_fadc, size, and TRUE.
Referenced by compress_load_all().
 {
   huffman_init_default(&fadc_run_huffman, 32);
   huffman_init_default(&fadc_small_huffman, 9);
   load_huffman("/Compression/Lossless/FADC/Huffman/Run", &fadc_run_huffman);
   load_huffman("/Compression/Lossless/FADC/Huffman/Small", &fadc_small_huffman);
   int size = sizeof(BOOL);
   db_get_value(hDB, 0, "/Compression/Lossless/FADC/Enabled", &should_compress_fadc,
     &size, TID_BOOL, TRUE);
 }
void fadc_optimize ()
Definition at line 20 of file fadc_compress.cpp.
References huffman_optimize_tree(), and save_huffman().
Referenced by compress_optimize_all().
 {
   huffman_optimize_tree(&fadc_run_huffman);
   huffman_optimize_tree(&fadc_small_huffman);
   save_huffman("/Compression/Lossless/FADC/Huffman/Run", &fadc_run_huffman);
   save_huffman("/Compression/Lossless/FADC/Huffman/Small", &fadc_small_huffman);
 }
int flush_output_buffer (io_buffer * buffer)
Definition at line 23 of file io_buffer.cpp.
References io_buffer::num_codes, io_buffer::p, io_buffer::start, io_buffer::w, and io_buffer::w_bits.
Referenced by encode_caen(), encode_cmp_times(), encode_fadc(), encode_hits(), encode_n2fadc_ndet(), encode_n2fadc_tpc(), encode_nfadc(), encode_times(), and flush_rle().
 {
   // store the last word
   *((buffer->p)++) = buffer->w << buffer->w_bits;
   // remember the length of the buffer, in bytes and in codes
   *(buffer->start) = buffer->num_codes;
   //return ((unsigned int) buffer->p) - ((unsigned int) buffer->start);
   return (int) (((char *) buffer->p) - ((char *) buffer->start));
 }
int flush_rle (rle_state * s, io_buffer * output)
Definition at line 103 of file rle.cpp.
References flush_output_buffer(), rle_state::huffman, rle_state::huffman_length, huffman_put_symbol(), io_buffer_put(), rle_state::run_length, and rle_state::running_digit.
Referenced by encode_bits(), and encode_cmp_bits().
 {
   if (s->run_length != 0) {
       if(s->run_length < s->huffman_length[s->running_digit]) {
         huffman_put_symbol(&s->huffman[s->running_digit], output, s->run_length);
       } else {
         huffman_put_symbol(&s->huffman[s->running_digit], output, s->huffman_length[s->running_digit]);
         io_buffer_put(output, s->run_length, 24);
       }
   }
   return flush_output_buffer(output);
 }
int hits_compress (channel_hit * input, int input_size, unsigned char * output, int userParam)
Definition at line 77 of file hits_compress.cpp.
References encode_hits(), rle_bits_setup(), and start_output_buffer().
Referenced by compress_event_skim().
 {
   input_size /= sizeof(channel_hit);
   rle_bits_setup();
   io_buffer output_buffer;
   // reserve space for size of uncompressed data (may be different from
   // input size, since some hits may be stripped)
   int *uncompressed_size_p = (int *) output;
   output += sizeof(int);
   // reserve space for the size of the compressed data
   int *compressed_time_size_p = (int *) output;
   output += sizeof(int);
   // compress times
   start_output_buffer(&output_buffer, output);
   int compressed_time_size =
       encode_hits(input, input_size, &output_buffer, uncompressed_size_p);
   output += compressed_time_size;
   // store size of compressed times
   *compressed_time_size_p = compressed_time_size;
   return compressed_time_size + 2 * sizeof(int);
 }
int hits_expand (unsigned char * input, int input_size, channel_hit * output, int userParam)
Definition at line 148 of file hits_compress.cpp.
References decode_hits(), rle_bits_setup(), and start_input_buffer().
Referenced by expand_event().
 {
   //
   // Uncompress the data produced by hits_compress().
   //
   rle_bits_setup();
   // Get uncompressed data size
   int *uncompressed_size_p = (int *) input;
   int uncompressed_size = *uncompressed_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Get size of compressed time data
   int *compressed_time_size_p = (int *) input;
   int compressed_time_size = *compressed_time_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress times
   io_buffer input_buffer;
   start_input_buffer(&input_buffer, input);
   decode_hits(&input_buffer, output);
   input += compressed_time_size;
   input_size -= compressed_time_size;
   return uncompressed_size * sizeof(channel_hit);
 }
void hits_load ()
Definition at line 24 of file hits_compress.cpp.
References hDB, huffman_init_default(), load_huffman(), should_compress_hits, size, and TRUE.
Referenced by compress_load_all().
 {
   huffman_init_default(&hits_parameter_huffman, 322);
   load_huffman("/Compression/Lossless/HITS/Huffman/Parameter", &hits_parameter_huffman);
   int size = sizeof(BOOL);
   db_get_value(hDB, 0, "/Compression/Lossless/HITS/Enabled", &should_compress_hits,
     &size, TID_BOOL, TRUE);
 }
void hits_optimize ()
Definition at line 18 of file hits_compress.cpp.
References huffman_optimize_tree(), and save_huffman().
Referenced by compress_optimize_skim().
 {
   huffman_optimize_tree(&hits_parameter_huffman);
   save_huffman("/Compression/Lossless/HITS/Huffman/Parameter", &hits_parameter_huffman);
 }
int huffman_get_symbol (huffman_table * table, io_buffer * buffer)
Definition at line 87 of file huffman.cpp.
References huffman_node::branch0, huffman_node::branch1, huffman_table::code_length, huffman_table::decode_symbols, io_buffer::num_codes, io_buffer::p, huffman_node::symbol, huffman_table::tree, io_buffer::w, and io_buffer::w_bits.
Referenced by decode_caen(), decode_cmp_times(), decode_fadc(), decode_hits(), decode_times(), and rle_get().
 {
   // Get the next symbol from a Huffman-coded buffer.  Again, this
   // function is in an inner loop and therefore performance-critical.
   if (buffer->num_codes <= 0) {
     return -1;
   }
   buffer->num_codes--;
   // If we have at least 8 bits pre-read from the buffer, then check the
   // table of pre-computed short symbols.
   if(buffer->w_bits >= 8) {
     unsigned int byte = (buffer->w >> 24) & 0xff;
     int symbol = table->decode_symbols[byte];
     if(symbol != -1) {
       int code_length = table->code_length[symbol];
       buffer->w <<= code_length;
       buffer->w_bits -= code_length;
       return symbol;
     }
   }
   // Otherwise, do it the slow way, walking bit-by-bit through the tree
   huffman_node *node = table->tree;
   while (1) {
     // We may already be there...
     if (node->symbol != -1) {
       return node->symbol;
     } else {
       // If not, consume a bit from the input and follow the tree
       if (buffer->w_bits == 0) {
         buffer->w = *((buffer->p)++);
         buffer->w_bits = 32;
       }
       unsigned int bit = buffer->w & (1u << 31);
       buffer->w <<= 1;
       buffer->w_bits--;
       if (bit == 0) {
         node = node->branch0;
       } else {
         node = node->branch1;
       }
     }
   }
 }
void huffman_init_default (huffman_table * table, int num_symbols)
Definition at line 305 of file huffman.cpp.
References huffman_table::code_bits, huffman_table::code_length, huffman_table::frequency, huffman_optimize_tree(), i, huffman_table::num_symbols, and huffman_table::tree.
Referenced by caen_load(), comp_load(), fadc_load(), hits_load(), stck_load(), and tdc400_load().
 {
   table->num_symbols = num_symbols;
   table->frequency = new int[num_symbols];
   table->code_bits = new unsigned int[num_symbols];
   table->code_length = new int[num_symbols];
   table->tree = NULL;
   // Assume that all symbols have equal probability
   for (int i = 0; i < num_symbols; i++) {
     table->frequency[i] = 1;
   }
   huffman_optimize_tree(table);
 }
BOOL huffman_optimize_tree (huffman_table * table)
Definition at line 200 of file huffman.cpp.
References huffman_node::branch0, huffman_node::branch1, huffman_table::code_length, huffman_table::frequency, huffman_node::frequency, huffman_node_compare(), huffman_precompute_decode(), huffman_visit(), i, huffman_node::next, huffman_table::num_symbols, SUCCESS, huffman_node::symbol, and huffman_table::tree.
Referenced by caen_optimize(), comp_optimize(), fadc_optimize(), hits_optimize(), huffman_init_default(), stck_optimize(), and tdc400_optimize().
 {
   // Start by allocating terminal nodes for the symbols.
   huffman_node *terminals[table->num_symbols];
   for (int i = 0; i < table->num_symbols; i++) {
     huffman_node *node = new huffman_node;
     node->branch0 = NULL;
     node->branch1 = NULL;
     node->next = NULL;
     node->symbol = i;
     node->frequency = table->frequency[i];
     terminals[i] = node;
   }
   // Now sort the array of terminals by frequency.
   qsort(terminals, table->num_symbols,
         sizeof(huffman_node *), huffman_node_compare);
   // Set up the linked list pointers
   for (int i = 0; i < table->num_symbols - 1; i++) {
     terminals[i]->next = terminals[i + 1];
   }
   huffman_node *root = terminals[0];
   // Now repeat: draw the two least probable nodes
   // and combine them, sorting the resulting combination
   // into the correct position in the list.
   while (root->next != NULL) {
     huffman_node *node0 = root;
     huffman_node *node1 = node0->next;
     root = node1->next;
     huffman_node *combined = new huffman_node;
     combined->branch0 = node0;
     combined->branch1 = node1;
     combined->next = NULL;
     combined->symbol = -1;
     combined->frequency = node0->frequency + node1->frequency;
     if (root == NULL) {
       root = combined;
     } else {
       // Search through the list to find the right position for the
       // new
       // node, and put it there.
       huffman_node *pos = root;
       huffman_node *prev = NULL;
       while (pos != NULL) {
         if (combined->frequency <= pos->frequency) {
           combined->next = pos;
           if (prev != NULL) {
             prev->next = combined;
           } else {
             root = combined;
           }
           break;
         }
         prev = pos;
         pos = pos->next;
       }
       if (pos == NULL) {
         combined->next = NULL;
         prev->next = combined;
       }
 #ifdef DEBUG
       // Check that we didn't screw up
       pos = root;
       prev = NULL;
       int node_count = 0;
       while (pos != NULL) {
         if (prev != NULL && pos->frequency < prev->frequency) {
           cm_msg(MERROR, "huffman_optimize_tree", "List out of order");
           return !SUCCESS;
         }
         prev = pos;
         pos = pos->next;
         node_count++;
       }
 #endif
     }
   }
   table->tree = root;
   // Now we have the tree; read off the codes by recursively visiting
   // each node.
   huffman_visit(table, root, 0, 0);
   // Check that the number of bits used by each key is less than 32.
   for (int i = 0; i < table->num_symbols; i++) {
     if(table->code_length[i] > 32) {
       cm_msg(MERROR, "huffman_optimize_tree",
         "Code length for symbol %d is too long (%d bits)", i,
         table->code_length[i]);
       return !SUCCESS;
     }
   }
   huffman_precompute_decode(table);
   return SUCCESS;
 }
void huffman_put_symbol (huffman_table * table, io_buffer * buffer, int symbol)
Definition at line 28 of file huffman.cpp.
References huffman_table::code_bits, huffman_table::code_length, huffman_table::frequency, io_buffer_put(), io_buffer::num_codes, and huffman_node::symbol.
Referenced by encode_caen(), encode_cmp_times(), encode_fadc(), encode_hits(), encode_times(), flush_rle(), and rle_put().
 {
   // Huffman encode a single symbol and send it to an output buffer.
   // This function is in an inner loop and therefore
   // performance-critical.
   // Update the frequency count for this symbol.
   table->frequency[symbol]++;
   // Get the code corresponding to this symbol.
   unsigned int code_bits = table->code_bits[symbol];
   int code_length = table->code_length[symbol];
   // Put it in the buffer
   io_buffer_put(buffer, code_bits, code_length);
   buffer->num_codes++;
 }
unsigned int io_buffer_get (io_buffer * buffer, int num_bits)
Definition at line 70 of file io_buffer.cpp.
References io_buffer_get(), io_buffer::p, io_buffer::w, and io_buffer::w_bits.
Referenced by decode_caen(), decode_cmp_times(), decode_fadc(), decode_hits(), decode_n2fadc_ndet(), decode_n2fadc_tpc(), decode_nfadc(), decode_times(), io_buffer_get(), and rle_get().
 {
   if (buffer->w_bits == 0) {
     buffer->w = *((buffer->p)++);
     buffer->w_bits = 32;
   }
   int w_bits = buffer->w_bits;
   unsigned int retval;
   if (num_bits <= w_bits) {
     retval = buffer->w >> (32 - num_bits);
     buffer->w = buffer->w << num_bits;
     buffer->w_bits = w_bits - num_bits;
   } else {
     unsigned int first_part =
         io_buffer_get(buffer, w_bits) << (num_bits - w_bits);
     retval = first_part | io_buffer_get(buffer, num_bits - w_bits);
   }
   return retval;
 }
void io_buffer_put (io_buffer * buffer, unsigned int code_bits, int code_length)
Definition at line 36 of file io_buffer.cpp.
References io_buffer::p, io_buffer::w, and io_buffer::w_bits.
Referenced by encode_caen(), encode_cmp_times(), encode_fadc(), encode_hits(), encode_n2fadc_ndet(), encode_n2fadc_tpc(), encode_nfadc(), encode_times(), flush_rle(), huffman_put_symbol(), and rle_put().
 {
   assert(code_length > 0 && code_length < 32);
   // Does this symbol fit in our buffer word?
   if (code_length < buffer->w_bits) {
     // OK, so put it there...
     buffer->w = (buffer->w << code_length) | code_bits;
     buffer->w_bits -= code_length;
   } else if (code_length == buffer->w_bits) {
     // Only barely...write out the buffer word
     buffer->w = (buffer->w << code_length) | code_bits;
     *((buffer->p)++) = buffer->w;
     buffer->w_bits = 32;
   } else {
     // No, we'll have to split the code across two words.
     unsigned int first_code_bits =
         code_bits >> (code_length - buffer->w_bits);
     *((buffer->p)++) = (buffer->w << buffer->w_bits) | first_code_bits;
     buffer->w = code_bits;
     buffer->w_bits = 32 - code_length + buffer->w_bits;
   }
 }
BOOL load_huffman (char * key_dir, huffman_table * table)
Definition at line 429 of file huffman.cpp.
References huffman_table::code_bits, huffman_table::code_length, FALSE, huffman_table::frequency, hDB, huffman_build_tree(), i, huffman_table::num_symbols, size, sprintf(), and SUCCESS.
Referenced by caen_load(), comp_load(), fadc_load(), hits_load(), stck_load(), and tdc400_load().
 {
   char key_name[MAX_ODB_PATH];
   int size;
   for(int i = 0; i < table->num_symbols; i++) {
     table->frequency[i] = 1;
   }
   sprintf(key_name, "%s/code_bits", key_dir);
   size = table->num_symbols * sizeof(DWORD);
   int stat = db_get_value(hDB, 0, key_name, table->code_bits, &size,
     TID_DWORD, FALSE);
   if(stat != DB_SUCCESS || size != table->num_symbols * sizeof(DWORD)) {
     cm_msg(MERROR, "load_huffman", "Failed to load ODB key %s", key_name);
     return !SUCCESS;
   }
   sprintf(key_name, "%s/code_length", key_dir);
   size = table->num_symbols * sizeof(DWORD);
   db_get_value(hDB, 0, key_name, table->code_length, &size, TID_DWORD, FALSE);
   if(stat != DB_SUCCESS || size != table->num_symbols * sizeof(DWORD)) {
     cm_msg(MERROR, "load_huffman", "Failed to load ODB key %s", key_name);
     return !SUCCESS;
   }
   huffman_build_tree(table);
   return SUCCESS;
 }
int n2fadc_ndet_compress (unsigned char * input, int input_size, unsigned char * output, int userParam)
Definition at line 97 of file n2fadc_ndet_compress.cpp.
References encode_n2fadc_ndet(), and start_output_buffer().
Referenced by compress_event(), and compress_event_skim().
 {
   io_buffer output_buffer;
   // store size of input data
   int *uncompressed_size_p = (int *) output;
   *uncompressed_size_p = input_size;
   output += sizeof(int);
   // compress samples
   start_output_buffer(&output_buffer, output);
   int compressed_size = encode_n2fadc_ndet(input, input_size, &output_buffer, userParam);
   output += compressed_size;
   return compressed_size + sizeof(int);
 }
int n2fadc_ndet_expand (unsigned char * input, int input_size, unsigned char * output, int userParam)
Definition at line 166 of file n2fadc_ndet_compress.cpp.
References decode_n2fadc_ndet(), and start_input_buffer().
Referenced by expand_event().
 {
   //
   // Uncompress the data produced by n2fadc_ndet_compress().
   //
   // Get uncompressed data size
   int *uncompressed_size_p = (int *) input;
   int uncompressed_size = *uncompressed_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress data
   io_buffer input_buffer;
   start_input_buffer(&input_buffer, input);
   decode_n2fadc_ndet(&input_buffer, output, uncompressed_size, userParam);
   return uncompressed_size;
 }
void n2fadc_ndet_load ()
Definition at line 24 of file n2fadc_ndet_compress.cpp.
References hDB, should_compress_n2fadc_ndet, size, and TRUE.
Referenced by compress_load_all().
 {
   int size = sizeof(BOOL);
   db_get_value(hDB, 0, "/Compression/Lossless/NFADC/Enabled", &should_compress_n2fadc_ndet,
     &size, TID_BOOL, TRUE);
 }
void n2fadc_ndet_optimize ()
Definition at line 20 of file n2fadc_ndet_compress.cpp.
Referenced by compress_optimize_all().
 {
 }
int n2fadc_tpc_compress (unsigned char * input, int input_size, unsigned char * output, int userParam)
Definition at line 104 of file n2fadc_tpc_compress.cpp.
References encode_n2fadc_tpc(), and start_output_buffer().
Referenced by compress_event(), and compress_event_skim().
 {
   io_buffer output_buffer;
   // store size of input data
   int *uncompressed_size_p = (int *) output;
   *uncompressed_size_p = input_size;
   output += sizeof(int);
   // compress samples
   start_output_buffer(&output_buffer, output);
   int compressed_size = encode_n2fadc_tpc(input, input_size, &output_buffer, userParam);
   output += compressed_size;
   return compressed_size + sizeof(int);
 }
int n2fadc_tpc_expand (unsigned char * input, int input_size, unsigned char * output, int userParam)
Definition at line 172 of file n2fadc_tpc_compress.cpp.
References decode_n2fadc_tpc(), and start_input_buffer().
Referenced by expand_event().
 {
   //
   // Uncompress the data produced by n2fadc_tpc_compress().
   //
   // Get uncompressed data size
   int *uncompressed_size_p = (int *) input;
   int uncompressed_size = *uncompressed_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress data
   io_buffer input_buffer;
   start_input_buffer(&input_buffer, input);
   decode_n2fadc_tpc(&input_buffer, output, uncompressed_size, userParam);
   return uncompressed_size;
 }
void n2fadc_tpc_load ()
Definition at line 24 of file n2fadc_tpc_compress.cpp.
References hDB, should_compress_n2fadc_tpc, size, and TRUE.
Referenced by compress_load_all().
 {
   int size = sizeof(BOOL);
   db_get_value(hDB, 0, "/Compression/Lossless/NFADC/Enabled", &should_compress_n2fadc_tpc,
     &size, TID_BOOL, TRUE);
 }
void n2fadc_tpc_optimize ()
Definition at line 20 of file n2fadc_tpc_compress.cpp.
Referenced by compress_optimize_all().
 {
 }
int nfadc_compress (unsigned char * input, int input_size, unsigned char * output, int userParam)
Definition at line 108 of file nfadc_compress.cpp.
References encode_nfadc(), and start_output_buffer().
Referenced by compress_event(), and compress_event_skim().
 {
   io_buffer output_buffer;
   // store size of input data
   int *uncompressed_size_p = (int *) output;
   *uncompressed_size_p = input_size;
   output += sizeof(int);
   // compress samples
   start_output_buffer(&output_buffer, output);
   int compressed_size = encode_nfadc(input, input_size, &output_buffer, userParam);
   output += compressed_size;
   return compressed_size + sizeof(int);
 }
int nfadc_expand (unsigned char * input, int input_size, unsigned char * output, int userParam)
Definition at line 181 of file nfadc_compress.cpp.
References decode_nfadc(), and start_input_buffer().
Referenced by expand_event().
 {
   //
   // Uncompress the data produced by nfadc_compress().
   //
   // Get uncompressed data size
   int *uncompressed_size_p = (int *) input;
   int uncompressed_size = *uncompressed_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress data
   io_buffer input_buffer;
   start_input_buffer(&input_buffer, input);
   decode_nfadc(&input_buffer, output, uncompressed_size, userParam);
   return uncompressed_size;
 }
void nfadc_load ()
Definition at line 24 of file nfadc_compress.cpp.
References hDB, should_compress_nfadc, size, and TRUE.
Referenced by compress_load_all().
 {
   int size = sizeof(BOOL);
   db_get_value(hDB, 0, "/Compression/Lossless/NFADC/Enabled", &should_compress_nfadc,
     &size, TID_BOOL, TRUE);
 }
void nfadc_optimize ()
Definition at line 20 of file nfadc_compress.cpp.
Referenced by compress_optimize_all().
 {
 }
int read_midas_event (FILE * fp, char * pevent)
Definition at line 24 of file overall.cpp.
References data_size, le32_to_cpu, and SUCCESS.
Referenced by main().
 {
   int event_size, size_read;
     size_read = fread(pevent, 1, sizeof(EVENT_HEADER), fp);
     if (size_read != sizeof(EVENT_HEADER))
       return !SUCCESS;
     event_size = le32_to_cpu(((EVENT_HEADER *) pevent)->data_size);
     size_read = fread(pevent + sizeof(EVENT_HEADER), 1, event_size, fp);
     if (size_read != event_size)
       return !SUCCESS;
     bk_swap(pevent, 0);
     return SUCCESS;
 }
void rle_bits_setup ()
Definition at line 41 of file rle.cpp.
References i, num_leading_0, num_leading_1, num_leading_bits(), ones, and rle_bits_setup_done.
Referenced by caen_compress(), caen_expand(), cmp_compress(), cmp_expand(), fadc_compress(), fadc_expand(), hits_compress(), hits_expand(), stck_compress(), stck_expand(), tdc400_compress(), and tdc400_expand().
 {
   if(rle_bits_setup_done) {
     return;
   }
   //
   // Cache the number of leading 0s and 1s for all 8-bit values.
   //
   for (int i = 0; i < 256; i++) {
     num_leading_0[i] = num_leading_bits(i, 0);
     num_leading_1[i] = num_leading_bits(i, 1);
   }
   //
   // Cache the bit-strings consisting of all 1s, with lengths from 1 to
   // 8.
   //
   short o = 0;
   for (int i = 0; i < 9; i++) {
     ones[i] = o;
     o = (o << 1) | 1;
   }
 }
int rle_get (io_buffer * input, rle_state * s)
Definition at line 117 of file rle.cpp.
References rle_state::huffman, huffman_get_symbol(), rle_state::huffman_length, io_buffer_get(), ones, rle_state::run_length, and rle_state::running_digit.
Referenced by decode_bits(), and decode_cmp_bits().
 {
   //
   // Reverse the encoding performed by rle_bits.
   //
   unsigned char output_word = 0;
   int output_bits = 8;
   while (1) {
     if (s->run_length == 0) {
       s->running_digit = !s->running_digit;
       int run_length =
           huffman_get_symbol(&s->huffman[s->running_digit], input);
       if (run_length < 0) {
         return -1;
       } else if(run_length == s->huffman_length[s->running_digit]) {
         s->run_length = io_buffer_get(input, 24);
       } else {
         s->run_length = run_length;
       }
     }
     while (s->run_length > 0) {
       if (output_bits > s->run_length) {
         output_word = output_word << s->run_length;
         if (s->running_digit == 1) {
           output_word |= ones[s->run_length];
         }
         output_bits -= s->run_length;
         s->run_length = 0;
       } else {
         output_word = output_word << output_bits;
         if (s->running_digit == 1) {
           output_word |= ones[output_bits];
         }
         s->run_length -= output_bits;
         return output_word;
       }
     }
   }
 }
void rle_put (unsigned char b, rle_state * s, io_buffer * output)
Definition at line 66 of file rle.cpp.
References rle_state::huffman, rle_state::huffman_length, huffman_put_symbol(), io_buffer_put(), num_leading_0, num_leading_1, rle_state::run_length, rle_state::running_digit, and rle_state::use_extension_word.
Referenced by encode_bits(), and encode_cmp_bits().
 {
   int bits = 8;
   while (bits > 0) {
     int nr;
     if (s->running_digit == 0) {
       nr = num_leading_0[b];
     } else {
       nr = num_leading_1[b];
     }
     if (nr > bits) {
       nr = bits;
     }
     s->run_length += nr;
     bits -= nr;
     if (bits != 0 || (!s->use_extension_word &&
                      s->run_length >= s->huffman_length[s->running_digit]-8)) {
       b = b << nr;
       if(s->run_length < s->huffman_length[s->running_digit]) {
         huffman_put_symbol(&s->huffman[s->running_digit], output, s->run_length);
       } else {
         huffman_put_symbol(&s->huffman[s->running_digit], output, s->huffman_length[s->running_digit]);
         io_buffer_put(output,s->run_length, 24);
       }
       s->running_digit = !s->running_digit;
       s->run_length = 0;
     }
   }
 }
BOOL save_huffman (char * key_dir, huffman_table * table)
Definition at line 321 of file huffman.cpp.
References huffman_table::code_bits, huffman_table::code_length, huffman_table::frequency, hDB, huffman_table::num_symbols, size, sprintf(), and SUCCESS.
Referenced by caen_optimize(), comp_optimize(), fadc_optimize(), hits_optimize(), stck_optimize(), and tdc400_optimize().
 {
   char key_name[MAX_ODB_PATH];
   int size;
   sprintf(key_name, "%s/code_bits", key_dir);
   size = table->num_symbols * sizeof(DWORD);
   int stat = db_set_value(hDB, 0, key_name, table->code_bits, size,
     table->num_symbols, TID_DWORD);
   if(stat != DB_SUCCESS) {
     cm_msg(MERROR, "save_huffman", "Failed to save ODB key %s", key_name);
     return !SUCCESS;
   }
   sprintf(key_name, "%s/code_length", key_dir);
   stat = db_set_value(hDB, 0, key_name, table->code_length, size,
     table->num_symbols, TID_DWORD);
   if(stat != DB_SUCCESS) {
     cm_msg(MERROR, "save_huffman", "Failed to save ODB key %s", key_name);
     return !SUCCESS;
   }
   sprintf(key_name, "%s/frequency", key_dir);
   stat = db_set_value(hDB, 0, key_name, table->frequency, size,
     table->num_symbols, TID_DWORD);
   if(stat != DB_SUCCESS) {
     cm_msg(MERROR, "save_huffman", "Failed to save ODB key %s", key_name);
     return !SUCCESS;
   }
   return SUCCESS;
 }
void start_input_buffer (io_buffer * buffer, unsigned char * p)
Definition at line 61 of file io_buffer.cpp.
References io_buffer::num_codes, io_buffer::p, io_buffer::start, io_buffer::w, and io_buffer::w_bits.
Referenced by caen_expand(), cmp_expand(), fadc_expand(), hits_expand(), n2fadc_ndet_expand(), n2fadc_tpc_expand(), nfadc_expand(), stck_expand(), and tdc400_expand().
 {
   buffer->w = 0;
   buffer->w_bits = 0;
   buffer->start = (unsigned int *) p;
   buffer->p = buffer->start + 1;
   buffer->num_codes = *(buffer->start);
 }
void start_output_buffer (io_buffer * buffer, unsigned char * p)
Definition at line 14 of file io_buffer.cpp.
References io_buffer::num_codes, io_buffer::p, io_buffer::start, io_buffer::w, and io_buffer::w_bits.
Referenced by caen_compress(), cmp_compress(), fadc_compress(), hits_compress(), n2fadc_ndet_compress(), n2fadc_tpc_compress(), nfadc_compress(), stck_compress(), and tdc400_compress().
 {
   buffer->w = 0;
   buffer->w_bits = 32;
   buffer->start = (unsigned int *) p;
   buffer->p = buffer->start + 1;
   buffer->num_codes = 0;
 }
int stck_compress (stack_elt * input, int input_size, unsigned char * output, int userParam)
Definition at line 220 of file stck_compress.cpp.
References encode_bits(), encode_times(), rle_bits_setup(), and start_output_buffer().
Referenced by compress_event_skim().
 {
   //
   // Carry out lossless compression on the stacked TPC data.
   //
   input_size /= sizeof(stack_elt);
   //myprint_TPCstack_interval(input, 0, input_size-1);
   rle_bits_setup();
   io_buffer output_buffer;
   // store size of input data
   int *uncompressed_size_p = (int *) output;
   *uncompressed_size_p = input_size;
   output += sizeof(int);
   // reserve space for the size of the compressed times
   int *compressed_time_size_p = (int *) output;
   output += sizeof(int);
   // compress times
   start_output_buffer(&output_buffer, output);
   int compressed_time_size =
       encode_times(input, input_size, &output_buffer);
   output += compressed_time_size;
   // store size of compressed times
   *compressed_time_size_p = compressed_time_size;
   // reserve space for the size of the compressed bit patterns
   int *compressed_bits_size_p = (int *) output;
   output += sizeof(int);
   // compress bit patterns
   start_output_buffer(&output_buffer, output);
   int compressed_bits_size =
       encode_bits(input, input_size, &output_buffer);
   output += compressed_time_size;
   // store size of compressed bit patterns
   *compressed_bits_size_p = compressed_bits_size;
   return compressed_time_size + compressed_bits_size + 3 * sizeof(int);
 }
int stck_expand (unsigned char * input, int input_size, stack_elt * output, int userParam)
Definition at line 269 of file stck_compress.cpp.
References decode_bits(), decode_times(), rle_bits_setup(), and start_input_buffer().
Referenced by expand_event().
 {
   //
   //
   // Uncompress the data produced by stck_compress().
   //
   rle_bits_setup();
   // Get uncompressed data size
   int *uncompressed_size_p = (int *) input;
   int uncompressed_size = *uncompressed_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Get size of compressed time data
   int *compressed_time_size_p = (int *) input;
   int compressed_time_size = *compressed_time_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress times
   io_buffer input_buffer;
   start_input_buffer(&input_buffer, input);
   decode_times(&input_buffer, output);
   input += compressed_time_size;
   input_size -= compressed_time_size;
   // Get size of compressed bit patterns
   int *compressed_bits_size_p = (int *) input;
   int compressed_bits_size = *compressed_bits_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress bit patterns
   start_input_buffer(&input_buffer, input);
   decode_bits(&input_buffer, output, uncompressed_size);
   //myprint_TPCstack_interval(output, 0, uncompressed_size-1);
   return uncompressed_size * sizeof(stack_elt);
 }
void stck_load ()
Definition at line 32 of file stck_compress.cpp.
References hDB, huffman_init_default(), load_huffman(), should_compress_stck, size, and TRUE.
Referenced by compress_load_all().
 {
   huffman_init_default(&stck_time_huffman, 129);
   huffman_init_default(&stck_bits_huffman[0], 129);
   huffman_init_default(&stck_bits_huffman[1], 129);
   load_huffman("/Compression/Lossless/STCK/Huffman/Bits 0", &stck_bits_huffman[0]);
   load_huffman("/Compression/Lossless/STCK/Huffman/Bits 1", &stck_bits_huffman[1]);
   int size = sizeof(BOOL);
   db_get_value(hDB, 0, "/Compression/Lossless/STCK/Enabled", &should_compress_stck,
     &size, TID_BOOL, TRUE);
 }
void stck_optimize ()
Definition at line 22 of file stck_compress.cpp.
References huffman_optimize_tree(), and save_huffman().
Referenced by compress_optimize_skim().
 {
   huffman_optimize_tree(&stck_time_huffman);
   huffman_optimize_tree(&stck_bits_huffman[0]);
   huffman_optimize_tree(&stck_bits_huffman[1]);
   save_huffman("/Compression/Lossless/STCK/Huffman/Bits 0", &stck_bits_huffman[0]);
   save_huffman("/Compression/Lossless/STCK/Huffman/Bits 1", &stck_bits_huffman[1]);
 }
int tdc400_compress (tdc400_word * input, int input_size, unsigned char * output, int userParam)
Definition at line 207 of file tdc400_compress.cpp.
References encode_bits(), encode_times(), rle_bits_setup(), and start_output_buffer().
Referenced by compress_event().
 {
   //
   // Carry out lossless compression on the TPC data recorded by a
   // single TDC400.
   //
   input_size /= sizeof(tdc400_word);
   rle_bits_setup();
   io_buffer output_buffer;
   // store size of input data
   int *uncompressed_size_p = (int *) output;
   *uncompressed_size_p = input_size;
   output += sizeof(int);
   // reserve space for the size of the compressed times
   int *compressed_time_size_p = (int *) output;
   output += sizeof(int);
   // compress times
   start_output_buffer(&output_buffer, output);
   int compressed_time_size =
       encode_times(input, input_size, &output_buffer);
   output += compressed_time_size;
   // store size of compressed times
   *compressed_time_size_p = compressed_time_size;
   // reserve space for the size of the compressed bit patterns
   int *compressed_bits_size_p = (int *) output;
   output += sizeof(int);
   // compress bit patterns
   start_output_buffer(&output_buffer, output);
   int compressed_bits_size =
       encode_bits(input, input_size, &output_buffer);
   output += compressed_time_size;
   // store size of compressed bit patterns
   *compressed_bits_size_p = compressed_bits_size;
   return compressed_time_size + compressed_bits_size + 3 * sizeof(int);
 }
int tdc400_expand (unsigned char * input, int input_size, tdc400_word * output, int userParam)
Definition at line 255 of file tdc400_compress.cpp.
References decode_bits(), decode_times(), rle_bits_setup(), and start_input_buffer().
Referenced by expand_event().
 {
   //
   // Uncompress the data produced by tdc400_compress().
   //
   rle_bits_setup();
   // Get uncompressed data size
   int *uncompressed_size_p = (int *) input;
   int uncompressed_size = *uncompressed_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Get size of compressed time data
   int *compressed_time_size_p = (int *) input;
   int compressed_time_size = *compressed_time_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress times
   io_buffer input_buffer;
   start_input_buffer(&input_buffer, input);
   decode_times(&input_buffer, output);
   input += compressed_time_size;
   input_size -= compressed_time_size;
   // Get size of compressed bit patterns
   int *compressed_bits_size_p = (int *) input;
   int compressed_bits_size = *compressed_bits_size_p;
   input += sizeof(int);
   input_size -= sizeof(int);
   // Uncompress bit patterns
   start_input_buffer(&input_buffer, input);
   decode_bits(&input_buffer, output, uncompressed_size);
   return uncompressed_size * sizeof(tdc400_word);
 }
void tdc400_load ()
Definition at line 30 of file tdc400_compress.cpp.
References hDB, huffman_init_default(), load_huffman(), should_compress_tdc400, size, and TRUE.
Referenced by compress_load_all().
 {
   huffman_init_default(&time_huffman, 128);
   huffman_init_default(&bits_huffman[0], 128);
   huffman_init_default(&bits_huffman[1], 128);
   load_huffman("/Compression/Lossless/TDC400/Huffman/Time", &time_huffman);
   load_huffman("/Compression/Lossless/TDC400/Huffman/Bits 0", &bits_huffman[0]);
   load_huffman("/Compression/Lossless/TDC400/Huffman/Bits 1", &bits_huffman[1]);
   int size = sizeof(BOOL);
   db_get_value(hDB, 0, "/Compression/Lossless/TDC400/Enabled", &should_compress_tdc400,
     &size, TID_BOOL, TRUE);
 }
void tdc400_optimize ()
Definition at line 19 of file tdc400_compress.cpp.
References huffman_optimize_tree(), and save_huffman().
Referenced by compress_optimize_all().
 {
   huffman_optimize_tree(&time_huffman);
   huffman_optimize_tree(&bits_huffman[0]);
   huffman_optimize_tree(&bits_huffman[1]);
   save_huffman("/Compression/Lossless/TDC400/Huffman/Time", &time_huffman);
   save_huffman("/Compression/Lossless/TDC400/Huffman/Bits 0", &bits_huffman[0]);
   save_huffman("/Compression/Lossless/TDC400/Huffman/Bits 1", &bits_huffman[1]);
 }
Variable Documentation
huffman_table bits_huffman[2]
Definition at line 15 of file tdc400_compress.cpp.
huffman_table caen_channel_huffman
Definition at line 14 of file caen_compress.cpp.
huffman_table cmp_bits_huffman[2]
Definition at line 14 of file comp_compress.cpp.
huffman_table cmp_channel_huffman
Definition at line 15 of file comp_compress.cpp.
huffman_table fadc_run_huffman
Definition at line 14 of file fadc_compress.cpp.
huffman_table fadc_small_huffman
Definition at line 15 of file fadc_compress.cpp.
HNDLE hDB
Definition at line 11 of file mucap_compress.cpp.
BOOL should_compress_caen
Definition at line 15 of file caen_compress.cpp.
Referenced by caen_load(), and compress_event().
BOOL should_compress_comp
Definition at line 16 of file comp_compress.cpp.
Referenced by comp_load(), and compress_event().
BOOL should_compress_fadc
Definition at line 16 of file fadc_compress.cpp.
Referenced by compress_event(), and fadc_load().
BOOL should_compress_n2fadc_ndet
Definition at line 14 of file n2fadc_ndet_compress.cpp.
Referenced by compress_event(), compress_event_skim(), and n2fadc_ndet_load().
BOOL should_compress_n2fadc_tpc
Definition at line 14 of file n2fadc_tpc_compress.cpp.
Referenced by compress_event(), compress_event_skim(), and n2fadc_tpc_load().
BOOL should_compress_nfadc
Definition at line 14 of file nfadc_compress.cpp.
Referenced by compress_event(), compress_event_skim(), and nfadc_load().
BOOL should_compress_tdc400
Definition at line 17 of file tdc400_compress.cpp.
Referenced by compress_event(), and tdc400_load().
huffman_table time_huffman
Definition at line 16 of file tdc400_compress.cpp.