AlcapDAQ: analyzer/compress/mucap_structures.h File Reference
mucap_structures.h File Reference
Data Structures
struct tdc400_word
struct caen_word
struct channel_hit
union comp_word
struct fadc_word
struct td_elt
struct track_elt
struct sniff_elt
struct TPC_Anode_Map_elt
struct thresh_bits
struct stack_elt
Typedefs
typedef struct tdc400_word tdc400_word
typedef struct caen_word caen_word
typedef struct channel_hit channel_hit
typedef union comp_word comp_word
typedef struct fadc_word fadc_word
typedef struct td_elt td_elt
typedef struct track_elt track_elt
typedef struct sniff_elt sniff_elt
typedef struct TPC_Anode_Map_elt TPC_Anode_Map_elt
typedef struct thresh_bits thresh_bits
typedef struct stack_elt stack_elt
Functions
static unsigned char & tdc400_byte (tdc400_word &w, int i)
Typedef Documentation
typedef struct caen_word caen_word
typedef struct channel_hit channel_hit
typedef union comp_word comp_word
typedef struct fadc_word fadc_word
typedef struct sniff_elt sniff_elt
typedef struct stack_elt stack_elt
typedef struct td_elt td_elt
typedef struct tdc400_word tdc400_word
typedef struct thresh_bits thresh_bits
typedef struct TPC_Anode_Map_elt TPC_Anode_Map_elt
typedef struct track_elt track_elt
Function Documentation
static unsigned char& tdc400_byte (tdc400_word & w, int i) inline static
Definition at line 9 of file mucap_structures.h.
References tdc400_word::bytes1, tdc400_word::bytes2, and i.
Referenced by decode_bits(), encode_bits(), and event_display().
{
   if(i < 4) {
     return w.bytes1[3-i];
   } else {
     return w.bytes2[5-i];
   }
 }