AlcapDAQ: analyzer/compress/mucap_optimize.cpp File Reference
analyzer/compress/mucap_optimize.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <endian.h>
#include <byteswap.h>
#include "midas.h"
#include "mucap_structures.h"
#include "mucap_compress.h"
Functions
int main (int argc, char *argv[])
Variables
HNDLE hDB
Function Documentation
int main (int argc, char * argv[])
Definition at line 13 of file mucap_optimize.cpp.
References bk_init32(), cm_connect_experiment(), cm_disconnect_experiment(), cm_get_environment(), cm_get_experiment_database(), compress_event(), compress_load_all(), compress_optimize_all(), EVENT_HEADER::event_id, event_id, EVENTID_BOR, EVENTID_EOR, EVENTID_MESSAGE, exp_name, fp, hDB, host_name, MAX_EVENT_SIZE, read_midas_event(), and SUCCESS.
{
    char host_name[256], exp_name[32];
    cm_get_environment(host_name, sizeof(host_name), exp_name,
                       sizeof(exp_name));
    cm_connect_experiment(host_name, exp_name, "Compression", NULL);
    cm_get_experiment_database(&hDB, NULL);
    compress_load_all();
    if(argc != 2) {
      printf("Usage: mucap_optimize uncompressed_input.mid\n");
      exit(1);
    }
    FILE *fp = fopen(argv[1], "r");
    if (!fp) {
      printf("Unable to open %s\n", argv[1]);
      exit(1);
    }
    char *input_event = new char[MAX_EVENT_SIZE];
    char *output_event = new char[MAX_EVENT_SIZE];
    while (read_midas_event(fp, input_event) == SUCCESS) {
        EVENT_HEADER header = *((EVENT_HEADER *) input_event);
        int event_id = header.event_id;
        if (event_id == EVENTID_BOR || event_id == EVENTID_EOR ||
            event_id == EVENTID_MESSAGE) {
          continue;
        }
        bk_init32(output_event);
        compress_event(input_event + sizeof(EVENT_HEADER), output_event);
    }
    compress_optimize_all();
    fclose(fp);
    cm_disconnect_experiment();
}
Variable Documentation
HNDLE hDB
Definition at line 11 of file mucap_optimize.cpp.