AlcapDAQ: analyzer/src/common/MUnCompressRawData.cpp File Reference
MUnCompressRawData.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <endian.h>
#include <byteswap.h>
#include <time.h>
#include "midas.h"
#include "mucap_compress.h"
#include "common.h"
Functions
INT MUnCompressRawData_init (void)
INT MUnCompressRawData (EVENT_HEADER *, void *)
Variables
HNDLE hDB
ANA_MODULE MUnCompressRawData_module
Function Documentation
INT MUnCompressRawData (EVENT_HEADER * pheader, void * pevent)
Definition at line 67 of file MUnCompressRawData.cpp.
References event_id, expand_event(), printf(), and SUCCESS.
 {
   int event_id = pheader->event_id;
   int event_serial = pheader->serial_number;
   // *** modified by VT on 9-Oct-2008 ***
   //int skip_threshold = 40;
   int skip_threshold = 1;
   if (event_serial % skip_threshold !=0){
     printf("Event is not divisible by %d, no analysis will be done\n",skip_threshold);
     return ANA_SKIP;
   }
   time_t block_time = pheader->time_stamp;
   char fdate[] = "%Y-%m-%d", ftime[] = "%H:%M:%S";
   struct tm block_tm;
   localtime_r(&block_time, &block_tm);
   char sdate[100], stime[100];
   strftime(sdate, 100, fdate, &block_tm);
   strftime(stime, 100, ftime, &block_tm);
   //  printf("Current block (serial number %d) stored on %s at %s\n",
   //     event_serial, sdate, stime);
   if (event_id == EVENTID_BOR ||
       event_id == EVENTID_EOR ||
       event_id == EVENTID_MESSAGE) {
     // No decompression is necessary for non-ordinary events
   } else {
     expand_event(pevent, pevent);
   }
   return SUCCESS;
 }
INT MUnCompressRawData_init (void)
Definition at line 58 of file MUnCompressRawData.cpp.
References compress_load_all(), and SUCCESS.
 {
   compress_load_all();
   return SUCCESS;
 }
Variable Documentation
HNDLE hDB
Definition at line 11 of file mucap_compress.cpp.
ANA_MODULE MUnCompressRawData_module
Initial value:
= {
  "MUnCompressRawData",
  "Tom Banks",
  MUnCompressRawData,
  NULL,
  NULL,
  MUnCompressRawData_init,
  NULL,
  NULL,
  0,
  NULL,
}
Definition at line 43 of file MUnCompressRawData.cpp.