AlcapDAQ: modules::parser Namespace Reference
modules::parser Namespace Reference
Namespaces
namespace errors
Classes
struct Constructor_t
Functions
int TokeniseByDelimiter (const std::string &input, std::vector< std::string > &output, const char *delim)
int TokeniseByWhiteSpace (const std::string &input, std::vector< std::string > &output)
std::string GetOneWord (const std::string &in, size_t start=0, size_t stop=std::string::npos)
Constructor_t ParseConstructor (const std::string &input, char open='(', char close=')') throw (modules::parser::errors::unmatched_parenthesis)
void ToCppValid (std::string &input)
const std::string & ToCppValid (const std::string &input)
void ReplaceAll (std::string &input, const std::string &search, const std::string &replace)
void ReplaceWords (std::string &input, const std::string &search, const std::string &replace)
const std::string & ReplaceAll (const std::string &input, const std::string &search, const std::string &replace)
size_t RemoveWhitespace (std::string &input)
size_t RemoveWhitespace (std::string &input, std::string::iterator start, std::string::iterator end)
void TrimWhiteSpaceBeforeAfter (std::string &input)
bool IsWhitespace (char in)
bool IsDigit (char in)
bool IsDecimal (char in)
bool IsFloatChar (char in)
bool IsNotFloatChar (char in)
bool IsNumber (const std::string &input)
int GetNumber (const std::string &input)
bool IsTrue (const std::string &input)
double GetDouble (const std::string &input, size_t start=0, size_t stop=std::string::npos)
bool iequals (const std::string &a, const std::string &b)
bool iequals (const char a, const char b)
Variables
const int max_line = 2048
Function Documentation
double modules::parser::GetDouble (const std::string & input, size_t start = 0, size_t stop = std::string::npos)
Definition at line 161 of file ModulesParser.cpp.
{
        TString tstr=input.substr(start,stop-start);
        double value=tstr.Atof();
        return value;
}
int modules::parser::GetNumber (const std::string & input)
Definition at line 155 of file ModulesParser.cpp.
Referenced by ExportPulse::ParseRequest().
{
        int val;
        sscanf ( input.c_str(), "%d", &val );
        return val;
}
std::string modules::parser::GetOneWord (const std::string & in, size_t start = 0, size_t stop = std::string::npos)
Definition at line 33 of file ModulesParser.cpp.
Referenced by MakeAnalysedPulses::ParseGeneratorList().
{
        std::stringstream ss(in.substr(start,stop-start));
        std::string word;
        ss>>word;
        return word;
}
bool modules::parser::iequals (const char a, const char b)
Definition at line 167 of file ModulesParser.cpp.
{
    return ( a=='_' && b=='-' ) ||
           ( a=='-' && b=='_' ) ||
           ( tolower(a) == tolower(b));
}
bool modules::parser::iequals (const std::string & a, const std::string & b)
Definition at line 173 of file ModulesParser.cpp.
Referenced by MakeAnalysedPulses::BeforeFirstEntry(), SetupNavigator::GetBank(), IDs::channel::GetDetectorEnum(), IDs::channel::GetSlowFastEnum(), and IDs::channel::operator=().
{
  unsigned int sz = a.size();
  if (b.size() != sz) return false;
  for (unsigned int i = 0; i < sz; ++i){
      if (! iequals(a[i],b[i])) return false;
  }
  return true;
}
bool modules::parser::IsDecimal (char in)
Definition at line 139 of file ModulesParser.cpp.
Referenced by IsFloatChar().
{
        return in=='.';
}
bool modules::parser::IsDigit (char in)
Definition at line 129 of file ModulesParser.cpp.
Referenced by IsFloatChar().
{
        bool retval=false;
        switch(in){
                case '0': case '1': case '2': case '3': case '4':
                case '5': case '6': case '7': case '8': case '9':
                        retval=true;
        }
        return retval;
}
bool modules::parser::IsFloatChar (char in)
Definition at line 143 of file ModulesParser.cpp.
References IsDecimal(), and IsDigit().
Referenced by IsNotFloatChar().
{
        return IsDecimal(in) || IsDigit(in);
}
bool modules::parser::IsNotFloatChar (char in)
Definition at line 147 of file ModulesParser.cpp.
References IsFloatChar().
Referenced by IsNumber().
{
        return !IsFloatChar(in);
}
bool modules::parser::IsNumber (const std::string & input)
Definition at line 151 of file ModulesParser.cpp.
References IsNotFloatChar().
Referenced by ExportPulse::ParseRequest().
{
        return std::find_if(input.begin(),input.end(),IsNotFloatChar) == input.end();
}
bool modules::parser::IsTrue (const std::string & input)
Definition at line 182 of file ModulesParser.cpp.
Referenced by modules::options::GetBool().
{
    return  (val=="true")|| (val=="TRUE")|| (val=="YES")|| (val=="yes")|| (val=="on")|| (val=="ON")|| (val=="1");
}
bool modules::parser::IsWhitespace (char in)
Definition at line 117 of file ModulesParser.cpp.
Referenced by RemoveWhitespace().
{
        bool retval=false;
        switch(in){
                case ' ': case '\t':
                        retval=true;
                        break;
                default:
                        retval=false;
        }
        return retval;
}
modules::parser::Constructor_t modules::parser::ParseConstructor (const std::string & input, char open = '(', char close = ')') throw (modules::parser::errors::unmatched_parenthesis)
Definition at line 41 of file ModulesParser.cpp.
References modules::parser::Constructor_t::before, modules::parser::Constructor_t::inside, and TrimWhiteSpaceBeforeAfter().
Referenced by modules::reader::AddModule(), ExportPulse::BeforeFirstEntry(), modules::reader::findSectionName(), and MakeDetectorPulses::ParseGeneratorList().
{
    size_t end_br=std::string::npos;
    size_t start_br=input.find(open);
    Constructor_t retVal;
    // cut out the string before the first open character
    retVal.before=input.substr(0,start_br);
    // trim whitespace from the start and end of retVal.before string
    TrimWhiteSpaceBeforeAfter(retVal.before);
    // Look for the requested brackets
    if(start_br!=std::string::npos){
       end_br=input.rfind(close);
       if(end_br==std::string::npos){
               // No matching close, although there was an open
               throw modules::parser::errors::unmatched_parenthesis(open,close);
       }
       retVal.inside=input.substr(start_br+1,end_br-start_br-1);
       TrimWhiteSpaceBeforeAfter(retVal.inside);
    }
    return retVal;
}
size_t modules::parser::RemoveWhitespace (std::string & input, std::string::iterator start, std::string::iterator end)
Definition at line 67 of file ModulesParser.cpp.
References IsWhitespace().
{
        std::string::iterator new_end=std::remove_if(start,end,modules::parser::IsWhitespace);
        input.erase(new_end,end);
        return input.size();
}
size_t modules::parser::RemoveWhitespace (std::string & input)
Definition at line 63 of file ModulesParser.cpp.
Referenced by ExportPulse::ParseRequest(), and TrimWhiteSpaceBeforeAfter().
{
        return RemoveWhitespace(input, input.begin(),input.end());
}
const std::string & modules::parser::ReplaceAll (const std::string & input, const std::string & search, const std::string & replace)
Definition at line 81 of file ModulesParser.cpp.
{
    static std::string output;
    output.clear();
    for(std::string::const_iterator i_char=input.begin(); i_char!=input.end();++i_char){
        if(std::find(search.begin(),search.end(), *i_char)!=search.end()){
            output+=replace;
        } else{
            output+=*i_char;
        }
    }
    return output;
}
void modules::parser::ReplaceAll (std::string & input, const std::string & search, const std::string & replace)
Definition at line 94 of file ModulesParser.cpp.
Referenced by ToCppValid().
{
    input=ReplaceAll(const_cast<const std::string&>(input),search,replace);
}
void modules::parser::ReplaceWords (std::string & input, const std::string & search, const std::string & replace)
Definition at line 98 of file ModulesParser.cpp.
Referenced by modules::options::CheckValid(), and PulseViewer::ParseTriggerString().
{
    size_t match_start;
    for( match_start=input.find(search);
         match_start!=std::string::npos;
         match_start=input.find(search)){
        input=input.substr(0,match_start) + replace + input.substr(match_start+search.length());
    }
}
const std::string & modules::parser::ToCppValid (const std::string & input)
Definition at line 73 of file ModulesParser.cpp.
References ReplaceAll().
{
    return ReplaceAll(input," :{}#*()-=+$%^&!.,/?","_" );
}
void modules::parser::ToCppValid (std::string & input)
Definition at line 77 of file ModulesParser.cpp.
References ReplaceAll().
Referenced by SavePulses::BeforeFirstEntry(), PlotTDPs::BeforeFirstEntry(), PlotTDP_TDiff::BeforeFirstEntry(), PlotTAP_Integral::BeforeFirstEntry(), PlotIntegralRatios::BeforeFirstEntry(), FirstCompleteAPGenerator::DrawPulse(), ExportPulse::PulseInfo_t::MakeTPIName(), and IDs::source::str().
{
    ReplaceAll(input," :{}#*()-=+$%^&!.,/?","_" );
}
int modules::parser::TokeniseByDelimiter (const std::string & input, std::vector< std::string > & output, const char * delim)
Definition at line 21 of file ModulesParser.cpp.
References max_line.
Referenced by TemplateFactory< BaseModule, OptionsType >::addArguments(), modules::reader::AddModule(), and MakeDetectorPulses::ParseGeneratorList().
{
    char line[modules::parser::max_line];
    strcpy(line,input.c_str());
    char* word = strtok(line,delim);
    while(word != NULL){
            //std::cout<<"ModulesOptions:GetVectorStringsByDelimiter() "<<word<<std::endl;
        output.push_back(word);
        word = strtok(NULL,delim);
    }
    return output.size();
}
int modules::parser::TokeniseByWhiteSpace (const std::string & input, std::vector< std::string > & output)
Definition at line 14 of file ModulesParser.cpp.
Referenced by modules::reader::ProcessGlobalOption().
{
    std::stringstream ss(input);
    std::string val;
    while(ss>>val) output.push_back(val);
    return output.size();
}
void modules::parser::TrimWhiteSpaceBeforeAfter (std::string & input)
Definition at line 107 of file ModulesParser.cpp.
References RemoveWhitespace().
Referenced by modules::reader::AddModule(), modules::options::GetString(), and ParseConstructor().
{
        size_t not_white=line.find_first_not_of(" \t");
        if(not_white!=std::string::npos)
           RemoveWhitespace(line, line.begin(),line.begin()+not_white+1);
        not_white=line.find_last_not_of(" \t");
        if(not_white!=std::string::npos)
           RemoveWhitespace(line, line.begin()+not_white+1,line.end());
}
Variable Documentation
const int modules::parser::max_line = 2048
Definition at line 41 of file ModulesParser.h.
Referenced by TokeniseByDelimiter().