AlcapDAQ: ROOT Namespace Reference
ROOT Namespace Reference
Namespaces
Shadow
Functions
void IDscLcLchannel_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * new_IDscLcLchannel (void *p=0)
static void * newArray_IDscLcLchannel (Long_t size, void *p)
static void delete_IDscLcLchannel (void *p)
static void deleteArray_IDscLcLchannel (void *p)
static void destruct_IDscLcLchannel (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::IDs::channel *)
TGenericClassInfo * GenerateInitInstance (const ::IDs::channel *)
::ROOT::TGenericClassInfo * _R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const ::IDs::generator*)0x0)
R__UseDummy (_R__UNIQUE_(Init))
void IDscLcLgenerator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * new_IDscLcLgenerator (void *p=0)
static void * newArray_IDscLcLgenerator (Long_t size, void *p)
static void delete_IDscLcLgenerator (void *p)
static void deleteArray_IDscLcLgenerator (void *p)
static void destruct_IDscLcLgenerator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::IDs::generator *)
TGenericClassInfo * GenerateInitInstance (const ::IDs::generator *)
void IDscLcLsource_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * new_IDscLcLsource (void *p=0)
static void * newArray_IDscLcLsource (Long_t size, void *p)
static void delete_IDscLcLsource (void *p)
static void deleteArray_IDscLcLsource (void *p)
static void destruct_IDscLcLsource (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::IDs::source *)
TGenericClassInfo * GenerateInitInstance (const ::IDs::source *)
void TAnalysedPulse_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * new_TAnalysedPulse (void *p=0)
static void * newArray_TAnalysedPulse (Long_t size, void *p)
static void delete_TAnalysedPulse (void *p)
static void deleteArray_TAnalysedPulse (void *p)
static void destruct_TAnalysedPulse (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TAnalysedPulse *)
TGenericClassInfo * GenerateInitInstance (const ::TAnalysedPulse *)
void vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_Dictionary ()
static void * new_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p=0)
static void * newArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static void deleteArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static void destruct_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >::iterator *)
TGenericClassInfo * GenerateInitInstance (const ::vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >::iterator *)
void pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_Dictionary ()
static void * new_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p=0)
static void * newArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (Long_t size, void *p)
static void delete_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static void deleteArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static void destruct_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const pair< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > *)
TGenericClassInfo * GenerateInitInstance (const pair< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > *)
void maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary ()
static void * new_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p=0)
static void * newArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void deleteArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void destruct_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::map< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >, less< string >, allocator< pair< const string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > > >::iterator *)
TGenericClassInfo * GenerateInitInstance (const ::map< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >, less< string >, allocator< pair< const string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > > >::iterator *)
void TDetectorPulse_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * new_TDetectorPulse (void *p=0)
static void * newArray_TDetectorPulse (Long_t size, void *p)
static void delete_TDetectorPulse (void *p)
static void deleteArray_TDetectorPulse (void *p)
static void destruct_TDetectorPulse (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TDetectorPulse *)
TGenericClassInfo * GenerateInitInstance (const ::TDetectorPulse *)
void TAnalysedPulseMapWrapper_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * new_TAnalysedPulseMapWrapper (void *p=0)
static void * newArray_TAnalysedPulseMapWrapper (Long_t size, void *p)
static void delete_TAnalysedPulseMapWrapper (void *p)
static void deleteArray_TAnalysedPulseMapWrapper (void *p)
static void destruct_TAnalysedPulseMapWrapper (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TAnalysedPulseMapWrapper *)
TGenericClassInfo * GenerateInitInstance (const ::TAnalysedPulseMapWrapper *)
void maplEIDscLcLDetector_tcOstringgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void maplEIDscLcLDetector_tcOstringgR_Dictionary ()
static void * new_maplEIDscLcLDetector_tcOstringgR (void *p=0)
static void * newArray_maplEIDscLcLDetector_tcOstringgR (Long_t size, void *p)
static void delete_maplEIDscLcLDetector_tcOstringgR (void *p)
static void deleteArray_maplEIDscLcLDetector_tcOstringgR (void *p)
static void destruct_maplEIDscLcLDetector_tcOstringgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< IDs::Detector_t, string > *)
void maplEstringcOIDscLcLDetector_tgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void maplEstringcOIDscLcLDetector_tgR_Dictionary ()
static void * new_maplEstringcOIDscLcLDetector_tgR (void *p=0)
static void * newArray_maplEstringcOIDscLcLDetector_tgR (Long_t size, void *p)
static void delete_maplEstringcOIDscLcLDetector_tgR (void *p)
static void deleteArray_maplEstringcOIDscLcLDetector_tgR (void *p)
static void destruct_maplEstringcOIDscLcLDetector_tgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, IDs::Detector_t > *)
void maplEstringcOvectorlETAnalysedPulsemUgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void maplEstringcOvectorlETAnalysedPulsemUgRsPgR_Dictionary ()
static void * new_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p=0)
static void * newArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (Long_t size, void *p)
static void delete_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static void deleteArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static void destruct_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, vector< TAnalysedPulse * > > *)
void vectorlETAnalysedPulsemUgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void vectorlETAnalysedPulsemUgR_Dictionary ()
static void * new_vectorlETAnalysedPulsemUgR (void *p=0)
static void * newArray_vectorlETAnalysedPulsemUgR (Long_t size, void *p)
static void delete_vectorlETAnalysedPulsemUgR (void *p)
static void deleteArray_vectorlETAnalysedPulsemUgR (void *p)
static void destruct_vectorlETAnalysedPulsemUgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< TAnalysedPulse * > *)
void vectorlEstringgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void vectorlEstringgR_Dictionary ()
static void * new_vectorlEstringgR (void *p=0)
static void * newArray_vectorlEstringgR (Long_t size, void *p)
static void delete_vectorlEstringgR (void *p)
static void deleteArray_vectorlEstringgR (void *p)
static void destruct_vectorlEstringgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< string > *)
void TSetupData_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * new_TSetupData (void *p=0)
static void * newArray_TSetupData (Long_t size, void *p)
static void delete_TSetupData (void *p)
static void deleteArray_TSetupData (void *p)
static void destruct_TSetupData (void *p)
static void streamer_TSetupData (TBuffer &buf, void *obj)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TSetupData *)
TGenericClassInfo * GenerateInitInstance (const ::TSetupData *)
::ROOT::TGenericClassInfo * _R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const ::TPulseIsland*)0x0)
void TPulseIsland_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * new_TPulseIsland (void *p=0)
static void * newArray_TPulseIsland (Long_t size, void *p)
static void delete_TPulseIsland (void *p)
static void deleteArray_TPulseIsland (void *p)
static void destruct_TPulseIsland (void *p)
static void streamer_TPulseIsland (TBuffer &buf, void *obj)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TPulseIsland *)
TGenericClassInfo * GenerateInitInstance (const ::TPulseIsland *)
void TGlobalData_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * new_TGlobalData (void *p=0)
static void * newArray_TGlobalData (Long_t size, void *p)
static void delete_TGlobalData (void *p)
static void deleteArray_TGlobalData (void *p)
static void destruct_TGlobalData (void *p)
static void streamer_TGlobalData (TBuffer &buf, void *obj)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TGlobalData *)
TGenericClassInfo * GenerateInitInstance (const ::TGlobalData *)
void maplEstringcOdoublegR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void maplEstringcOdoublegR_Dictionary ()
static void * new_maplEstringcOdoublegR (void *p=0)
static void * newArray_maplEstringcOdoublegR (Long_t size, void *p)
static void delete_maplEstringcOdoublegR (void *p)
static void deleteArray_maplEstringcOdoublegR (void *p)
static void destruct_maplEstringcOdoublegR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, double > *)
void maplEstringcOintgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void maplEstringcOintgR_Dictionary ()
static void * new_maplEstringcOintgR (void *p=0)
static void * newArray_maplEstringcOintgR (Long_t size, void *p)
static void delete_maplEstringcOintgR (void *p)
static void deleteArray_maplEstringcOintgR (void *p)
static void destruct_maplEstringcOintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, int > *)
void maplEstringcOstringgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void maplEstringcOstringgR_Dictionary ()
static void * new_maplEstringcOstringgR (void *p=0)
static void * newArray_maplEstringcOstringgR (Long_t size, void *p)
static void delete_maplEstringcOstringgR (void *p)
static void deleteArray_maplEstringcOstringgR (void *p)
static void destruct_maplEstringcOstringgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, string > *)
void maplEstringcOvectorlETPulseIslandmUgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary ()
static void * new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p=0)
static void * newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void *p)
static void delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *)
void vectorlETPulseIslandmUgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void vectorlETPulseIslandmUgR_Dictionary ()
static void * new_vectorlETPulseIslandmUgR (void *p=0)
static void * newArray_vectorlETPulseIslandmUgR (Long_t size, void *p)
static void delete_vectorlETPulseIslandmUgR (void *p)
static void deleteArray_vectorlETPulseIslandmUgR (void *p)
static void destruct_vectorlETPulseIslandmUgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< TPulseIsland * > *)
void vectorlEintgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void vectorlEintgR_Dictionary ()
static void * new_vectorlEintgR (void *p=0)
static void * newArray_vectorlEintgR (Long_t size, void *p)
static void delete_vectorlEintgR (void *p)
static void deleteArray_vectorlEintgR (void *p)
static void destruct_vectorlEintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< int > *)
static void * new_TSetupData (void *p=0)
static void * newArray_TSetupData (Long_t size, void *p)
static void delete_TSetupData (void *p)
static void deleteArray_TSetupData (void *p)
static void destruct_TSetupData (void *p)
static void streamer_TSetupData (TBuffer &buf, void *obj)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TSetupData *)
::ROOT::TGenericClassInfo * _R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const ::TPulseIsland*)0x0)
static void * new_TPulseIsland (void *p=0)
static void * newArray_TPulseIsland (Long_t size, void *p)
static void delete_TPulseIsland (void *p)
static void deleteArray_TPulseIsland (void *p)
static void destruct_TPulseIsland (void *p)
static void streamer_TPulseIsland (TBuffer &buf, void *obj)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TPulseIsland *)
static void * new_TGlobalData (void *p=0)
static void * newArray_TGlobalData (Long_t size, void *p)
static void delete_TGlobalData (void *p)
static void deleteArray_TGlobalData (void *p)
static void destruct_TGlobalData (void *p)
static void streamer_TGlobalData (TBuffer &buf, void *obj)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TGlobalData *)
static void maplEstringcOdoublegR_Dictionary ()
static void * new_maplEstringcOdoublegR (void *p=0)
static void * newArray_maplEstringcOdoublegR (Long_t size, void *p)
static void delete_maplEstringcOdoublegR (void *p)
static void deleteArray_maplEstringcOdoublegR (void *p)
static void destruct_maplEstringcOdoublegR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, double > *)
static void maplEstringcOintgR_Dictionary ()
static void * new_maplEstringcOintgR (void *p=0)
static void * newArray_maplEstringcOintgR (Long_t size, void *p)
static void delete_maplEstringcOintgR (void *p)
static void deleteArray_maplEstringcOintgR (void *p)
static void destruct_maplEstringcOintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, int > *)
static void maplEstringcOstringgR_Dictionary ()
static void * new_maplEstringcOstringgR (void *p=0)
static void * newArray_maplEstringcOstringgR (Long_t size, void *p)
static void delete_maplEstringcOstringgR (void *p)
static void deleteArray_maplEstringcOstringgR (void *p)
static void destruct_maplEstringcOstringgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, string > *)
static void maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary ()
static void * new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p=0)
static void * newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void *p)
static void delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *)
static void vectorlETPulseIslandmUgR_Dictionary ()
static void * new_vectorlETPulseIslandmUgR (void *p=0)
static void * newArray_vectorlETPulseIslandmUgR (Long_t size, void *p)
static void delete_vectorlETPulseIslandmUgR (void *p)
static void deleteArray_vectorlETPulseIslandmUgR (void *p)
static void destruct_vectorlETPulseIslandmUgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< TPulseIsland * > *)
static void vectorlEintgR_Dictionary ()
static void * new_vectorlEintgR (void *p=0)
static void * newArray_vectorlEintgR (Long_t size, void *p)
static void delete_vectorlEintgR (void *p)
static void deleteArray_vectorlEintgR (void *p)
static void destruct_vectorlEintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< int > *)
static void * new_TSetupData (void *p=0)
static void * newArray_TSetupData (Long_t size, void *p)
static void delete_TSetupData (void *p)
static void deleteArray_TSetupData (void *p)
static void destruct_TSetupData (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TSetupData *)
::ROOT::TGenericClassInfo * _R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const pair<string,string>*)0x0)
void pairlEstringcOstringgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void pairlEstringcOstringgR_Dictionary ()
static void * new_pairlEstringcOstringgR (void *p=0)
static void * newArray_pairlEstringcOstringgR (Long_t size, void *p)
static void delete_pairlEstringcOstringgR (void *p)
static void deleteArray_pairlEstringcOstringgR (void *p)
static void destruct_pairlEstringcOstringgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const pair< string, string > *)
TGenericClassInfo * GenerateInitInstance (const pair< string, string > *)
void maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary ()
static void * new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p=0)
static void * newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static void deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static void destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::map< string, string, less< string >, allocator< pair< const string, string > > >::iterator *)
TGenericClassInfo * GenerateInitInstance (const ::map< string, string, less< string >, allocator< pair< const string, string > > >::iterator *)
static void * new_TPulseIsland (void *p=0)
static void * newArray_TPulseIsland (Long_t size, void *p)
static void delete_TPulseIsland (void *p)
static void deleteArray_TPulseIsland (void *p)
static void destruct_TPulseIsland (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TPulseIsland *)
static void * new_TGlobalData (void *p=0)
static void * newArray_TGlobalData (Long_t size, void *p)
static void delete_TGlobalData (void *p)
static void deleteArray_TGlobalData (void *p)
static void destruct_TGlobalData (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TGlobalData *)
void vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary ()
static void * new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p=0)
static void * newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static void deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static void destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *)
TGenericClassInfo * GenerateInitInstance (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *)
void pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary ()
static void * new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p=0)
static void * newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (Long_t size, void *p)
static void delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static void deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static void destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *)
TGenericClassInfo * GenerateInitInstance (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *)
void maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary ()
static void * new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p=0)
static void * newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *)
TGenericClassInfo * GenerateInitInstance (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *)
void TVacuumData_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * new_TVacuumData (void *p=0)
static void * newArray_TVacuumData (Long_t size, void *p)
static void delete_TVacuumData (void *p)
static void deleteArray_TVacuumData (void *p)
static void destruct_TVacuumData (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TVacuumData *)
TGenericClassInfo * GenerateInitInstance (const ::TVacuumData *)
void maplEstringcOboolgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void maplEstringcOboolgR_Dictionary ()
static void * new_maplEstringcOboolgR (void *p=0)
static void * newArray_maplEstringcOboolgR (Long_t size, void *p)
static void delete_maplEstringcOboolgR (void *p)
static void deleteArray_maplEstringcOboolgR (void *p)
static void destruct_maplEstringcOboolgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, bool > *)
static void maplEstringcOdoublegR_Dictionary ()
static void * new_maplEstringcOdoublegR (void *p=0)
static void * newArray_maplEstringcOdoublegR (Long_t size, void *p)
static void delete_maplEstringcOdoublegR (void *p)
static void deleteArray_maplEstringcOdoublegR (void *p)
static void destruct_maplEstringcOdoublegR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, double > *)
static void maplEstringcOintgR_Dictionary ()
static void * new_maplEstringcOintgR (void *p=0)
static void * newArray_maplEstringcOintgR (Long_t size, void *p)
static void delete_maplEstringcOintgR (void *p)
static void deleteArray_maplEstringcOintgR (void *p)
static void destruct_maplEstringcOintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, int > *)
static void maplEstringcOstringgR_Dictionary ()
static void * new_maplEstringcOstringgR (void *p=0)
static void * newArray_maplEstringcOstringgR (Long_t size, void *p)
static void delete_maplEstringcOstringgR (void *p)
static void deleteArray_maplEstringcOstringgR (void *p)
static void destruct_maplEstringcOstringgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, string > *)
static void maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary ()
static void * new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p=0)
static void * newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void *p)
static void delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *)
static void vectorlETPulseIslandmUgR_Dictionary ()
static void * new_vectorlETPulseIslandmUgR (void *p=0)
static void * newArray_vectorlETPulseIslandmUgR (Long_t size, void *p)
static void delete_vectorlETPulseIslandmUgR (void *p)
static void deleteArray_vectorlETPulseIslandmUgR (void *p)
static void destruct_vectorlETPulseIslandmUgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< TPulseIsland * > *)
void vectorlEfloatgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void vectorlEfloatgR_Dictionary ()
static void * new_vectorlEfloatgR (void *p=0)
static void * newArray_vectorlEfloatgR (Long_t size, void *p)
static void delete_vectorlEfloatgR (void *p)
static void deleteArray_vectorlEfloatgR (void *p)
static void destruct_vectorlEfloatgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< float > *)
static void vectorlEintgR_Dictionary ()
static void * new_vectorlEintgR (void *p=0)
static void * newArray_vectorlEintgR (Long_t size, void *p)
static void delete_vectorlEintgR (void *p)
static void deleteArray_vectorlEintgR (void *p)
static void destruct_vectorlEintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< int > *)
static void * new_TSetupData (void *p=0)
static void * newArray_TSetupData (Long_t size, void *p)
static void delete_TSetupData (void *p)
static void deleteArray_TSetupData (void *p)
static void destruct_TSetupData (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TSetupData *)
::ROOT::TGenericClassInfo * _R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const pair<string,string>*)0x0)
static void pairlEstringcOstringgR_Dictionary ()
static void * new_pairlEstringcOstringgR (void *p=0)
static void * newArray_pairlEstringcOstringgR (Long_t size, void *p)
static void delete_pairlEstringcOstringgR (void *p)
static void deleteArray_pairlEstringcOstringgR (void *p)
static void destruct_pairlEstringcOstringgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const pair< string, string > *)
static void maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary ()
static void * new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p=0)
static void * newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static void deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static void destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::map< string, string, less< string >, allocator< pair< const string, string > > >::iterator *)
static void * new_TPulseIsland (void *p=0)
static void * newArray_TPulseIsland (Long_t size, void *p)
static void delete_TPulseIsland (void *p)
static void deleteArray_TPulseIsland (void *p)
static void destruct_TPulseIsland (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TPulseIsland *)
static void * new_TGlobalData (void *p=0)
static void * newArray_TGlobalData (Long_t size, void *p)
static void delete_TGlobalData (void *p)
static void deleteArray_TGlobalData (void *p)
static void destruct_TGlobalData (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TGlobalData *)
static void vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary ()
static void * new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p=0)
static void * newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static void deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static void destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *)
static void pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary ()
static void * new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p=0)
static void * newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (Long_t size, void *p)
static void delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static void deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static void destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *)
static void maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary ()
static void * new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p=0)
static void * newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *)
static void * new_TVacuumData (void *p=0)
static void * newArray_TVacuumData (Long_t size, void *p)
static void delete_TVacuumData (void *p)
static void deleteArray_TVacuumData (void *p)
static void destruct_TVacuumData (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TVacuumData *)
static void maplEstringcOboolgR_Dictionary ()
static void * new_maplEstringcOboolgR (void *p=0)
static void * newArray_maplEstringcOboolgR (Long_t size, void *p)
static void delete_maplEstringcOboolgR (void *p)
static void deleteArray_maplEstringcOboolgR (void *p)
static void destruct_maplEstringcOboolgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, bool > *)
static void maplEstringcOdoublegR_Dictionary ()
static void * new_maplEstringcOdoublegR (void *p=0)
static void * newArray_maplEstringcOdoublegR (Long_t size, void *p)
static void delete_maplEstringcOdoublegR (void *p)
static void deleteArray_maplEstringcOdoublegR (void *p)
static void destruct_maplEstringcOdoublegR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, double > *)
static void maplEstringcOintgR_Dictionary ()
static void * new_maplEstringcOintgR (void *p=0)
static void * newArray_maplEstringcOintgR (Long_t size, void *p)
static void delete_maplEstringcOintgR (void *p)
static void deleteArray_maplEstringcOintgR (void *p)
static void destruct_maplEstringcOintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, int > *)
static void maplEstringcOstringgR_Dictionary ()
static void * new_maplEstringcOstringgR (void *p=0)
static void * newArray_maplEstringcOstringgR (Long_t size, void *p)
static void delete_maplEstringcOstringgR (void *p)
static void deleteArray_maplEstringcOstringgR (void *p)
static void destruct_maplEstringcOstringgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, string > *)
static void maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary ()
static void * new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p=0)
static void * newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void *p)
static void delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *)
static void vectorlETPulseIslandmUgR_Dictionary ()
static void * new_vectorlETPulseIslandmUgR (void *p=0)
static void * newArray_vectorlETPulseIslandmUgR (Long_t size, void *p)
static void delete_vectorlETPulseIslandmUgR (void *p)
static void deleteArray_vectorlETPulseIslandmUgR (void *p)
static void destruct_vectorlETPulseIslandmUgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< TPulseIsland * > *)
static void vectorlEfloatgR_Dictionary ()
static void * new_vectorlEfloatgR (void *p=0)
static void * newArray_vectorlEfloatgR (Long_t size, void *p)
static void delete_vectorlEfloatgR (void *p)
static void deleteArray_vectorlEfloatgR (void *p)
static void destruct_vectorlEfloatgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< float > *)
static void vectorlEintgR_Dictionary ()
static void * new_vectorlEintgR (void *p=0)
static void * newArray_vectorlEintgR (Long_t size, void *p)
static void delete_vectorlEintgR (void *p)
static void deleteArray_vectorlEintgR (void *p)
static void destruct_vectorlEintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< int > *)
static void * new_TSetupData (void *p=0)
static void * newArray_TSetupData (Long_t size, void *p)
static void delete_TSetupData (void *p)
static void deleteArray_TSetupData (void *p)
static void destruct_TSetupData (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TSetupData *)
::ROOT::TGenericClassInfo * _R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const pair<string,string>*)0x0)
static void pairlEstringcOstringgR_Dictionary ()
static void * new_pairlEstringcOstringgR (void *p=0)
static void * newArray_pairlEstringcOstringgR (Long_t size, void *p)
static void delete_pairlEstringcOstringgR (void *p)
static void deleteArray_pairlEstringcOstringgR (void *p)
static void destruct_pairlEstringcOstringgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const pair< string, string > *)
static void maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary ()
static void * new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p=0)
static void * newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static void deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static void destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::map< string, string, less< string >, allocator< pair< const string, string > > >::iterator *)
static void * new_TPulseIsland (void *p=0)
static void * newArray_TPulseIsland (Long_t size, void *p)
static void delete_TPulseIsland (void *p)
static void deleteArray_TPulseIsland (void *p)
static void destruct_TPulseIsland (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TPulseIsland *)
static void * new_TGlobalData (void *p=0)
static void * newArray_TGlobalData (Long_t size, void *p)
static void delete_TGlobalData (void *p)
static void deleteArray_TGlobalData (void *p)
static void destruct_TGlobalData (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TGlobalData *)
static void vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary ()
static void * new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p=0)
static void * newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static void deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static void destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *)
static void pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary ()
static void * new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p=0)
static void * newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (Long_t size, void *p)
static void delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static void deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static void destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *)
static void maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary ()
static void * new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p=0)
static void * newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *)
static void * new_TAnalysedPulse (void *p=0)
static void * newArray_TAnalysedPulse (Long_t size, void *p)
static void delete_TAnalysedPulse (void *p)
static void deleteArray_TAnalysedPulse (void *p)
static void destruct_TAnalysedPulse (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TAnalysedPulse *)
static void * new_TDetectorPulse (void *p=0)
static void * newArray_TDetectorPulse (Long_t size, void *p)
static void delete_TDetectorPulse (void *p)
static void deleteArray_TDetectorPulse (void *p)
static void destruct_TDetectorPulse (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TDetectorPulse *)
static void * new_TVacuumData (void *p=0)
static void * newArray_TVacuumData (Long_t size, void *p)
static void delete_TVacuumData (void *p)
static void deleteArray_TVacuumData (void *p)
static void destruct_TVacuumData (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TVacuumData *)
static void vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_Dictionary ()
static void * new_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p=0)
static void * newArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static void deleteArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static void destruct_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >::iterator *)
static void pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_Dictionary ()
static void * new_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p=0)
static void * newArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (Long_t size, void *p)
static void delete_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static void deleteArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static void destruct_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const pair< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > *)
static void maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary ()
static void * new_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p=0)
static void * newArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void deleteArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void destruct_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::map< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >, less< string >, allocator< pair< const string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > > >::iterator *)
static void maplEstringcOdoublegR_Dictionary ()
static void * new_maplEstringcOdoublegR (void *p=0)
static void * newArray_maplEstringcOdoublegR (Long_t size, void *p)
static void delete_maplEstringcOdoublegR (void *p)
static void deleteArray_maplEstringcOdoublegR (void *p)
static void destruct_maplEstringcOdoublegR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, double > *)
static void maplEstringcOintgR_Dictionary ()
static void * new_maplEstringcOintgR (void *p=0)
static void * newArray_maplEstringcOintgR (Long_t size, void *p)
static void delete_maplEstringcOintgR (void *p)
static void deleteArray_maplEstringcOintgR (void *p)
static void destruct_maplEstringcOintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, int > *)
static void maplEstringcOstringgR_Dictionary ()
static void * new_maplEstringcOstringgR (void *p=0)
static void * newArray_maplEstringcOstringgR (Long_t size, void *p)
static void delete_maplEstringcOstringgR (void *p)
static void deleteArray_maplEstringcOstringgR (void *p)
static void destruct_maplEstringcOstringgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, string > *)
static void maplEstringcOvectorlETAnalysedPulsemUgRsPgR_Dictionary ()
static void * new_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p=0)
static void * newArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (Long_t size, void *p)
static void delete_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static void deleteArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static void destruct_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, vector< TAnalysedPulse * > > *)
static void maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary ()
static void * new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p=0)
static void * newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void *p)
static void delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *)
static void vectorlETAnalysedPulsemUgR_Dictionary ()
static void * new_vectorlETAnalysedPulsemUgR (void *p=0)
static void * newArray_vectorlETAnalysedPulsemUgR (Long_t size, void *p)
static void delete_vectorlETAnalysedPulsemUgR (void *p)
static void deleteArray_vectorlETAnalysedPulsemUgR (void *p)
static void destruct_vectorlETAnalysedPulsemUgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< TAnalysedPulse * > *)
static void vectorlETPulseIslandmUgR_Dictionary ()
static void * new_vectorlETPulseIslandmUgR (void *p=0)
static void * newArray_vectorlETPulseIslandmUgR (Long_t size, void *p)
static void delete_vectorlETPulseIslandmUgR (void *p)
static void deleteArray_vectorlETPulseIslandmUgR (void *p)
static void destruct_vectorlETPulseIslandmUgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< TPulseIsland * > *)
static void vectorlEfloatgR_Dictionary ()
static void * new_vectorlEfloatgR (void *p=0)
static void * newArray_vectorlEfloatgR (Long_t size, void *p)
static void delete_vectorlEfloatgR (void *p)
static void deleteArray_vectorlEfloatgR (void *p)
static void destruct_vectorlEfloatgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< float > *)
static void vectorlEintgR_Dictionary ()
static void * new_vectorlEintgR (void *p=0)
static void * newArray_vectorlEintgR (Long_t size, void *p)
static void delete_vectorlEintgR (void *p)
static void deleteArray_vectorlEintgR (void *p)
static void destruct_vectorlEintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< int > *)
void TOctalFADCIsland_ShowMembers (void *obj, TMemberInspector &R__insp)
static void TOctalFADCIsland_Dictionary ()
static void * new_TOctalFADCIsland (void *p=0)
static void * newArray_TOctalFADCIsland (Long_t size, void *p)
static void delete_TOctalFADCIsland (void *p)
static void deleteArray_TOctalFADCIsland (void *p)
static void destruct_TOctalFADCIsland (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TOctalFADCIsland *)
TGenericClassInfo * GenerateInitInstance (const ::TOctalFADCIsland *)
::ROOT::TGenericClassInfo * _R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const ::TPulseIsland*)0x0)
static void * new_TPulseIsland (void *p=0)
static void * newArray_TPulseIsland (Long_t size, void *p)
static void delete_TPulseIsland (void *p)
static void deleteArray_TPulseIsland (void *p)
static void destruct_TPulseIsland (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TPulseIsland *)
static void * new_TGlobalData (void *p=0)
static void * newArray_TGlobalData (Long_t size, void *p)
static void delete_TGlobalData (void *p)
static void deleteArray_TGlobalData (void *p)
static void destruct_TGlobalData (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::TGlobalData *)
static void vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary ()
static void * new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p=0)
static void * newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static void deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static void destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *)
static void pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary ()
static void * new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p=0)
static void * newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (Long_t size, void *p)
static void delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static void deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static void destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *)
static void maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary ()
static void * new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p=0)
static void * newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *)
static void maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary ()
static void * new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p=0)
static void * newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void *p)
static void delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *)
static void vectorlETPulseIslandmUgR_Dictionary ()
static void * new_vectorlETPulseIslandmUgR (void *p=0)
static void * newArray_vectorlETPulseIslandmUgR (Long_t size, void *p)
static void delete_vectorlETPulseIslandmUgR (void *p)
static void deleteArray_vectorlETPulseIslandmUgR (void *p)
static void destruct_vectorlETPulseIslandmUgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< TPulseIsland * > *)
static void vectorlEintgR_Dictionary ()
static void * new_vectorlEintgR (void *p=0)
static void * newArray_vectorlEintgR (Long_t size, void *p)
static void delete_vectorlEintgR (void *p)
static void deleteArray_vectorlEintgR (void *p)
static void destruct_vectorlEintgR (void *p)
static TGenericClassInfo * GenerateInitInstanceLocal (const vector< int > *)
Function Documentation
ROOT::TGenericClassInfo * ROOT::_R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const ::TPulseIsland*)0x0) static
ROOT::TGenericClassInfo * ROOT::_R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const ::TPulseIsland*)0x0) static
ROOT::TGenericClassInfo * ROOT::_R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const ::IDs::generator*)0x0) static
ROOT::TGenericClassInfo * ROOT::_R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const pair<string,string>*)0x0) static
ROOT::TGenericClassInfo * ROOT::_R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const pair<string,string>*)0x0) static
ROOT::TGenericClassInfo * ROOT::_R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const pair<string,string>*)0x0) static
ROOT::TGenericClassInfo * ROOT::_R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const ::TPulseIsland*)0x0) static
static void ROOT::delete_IDscLcLchannel (void * p) static
Definition at line 617 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::IDs::channel*)p);
    }
static void ROOT::delete_IDscLcLgenerator (void * p) static
Definition at line 667 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::IDs::generator*)p);
    }
static void ROOT::delete_IDscLcLsource (void * p) static
Definition at line 717 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::IDs::source*)p);
    }
static void ROOT::delete_maplEIDscLcLDetector_tcOstringgR (void * p) static
Definition at line 999 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((map<IDs::Detector_t,string>*)p);
    }
static void ROOT::delete_maplEstringcOboolgR (void * p) static
Definition at line 923 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((map<string,bool>*)p);
    }
static void ROOT::delete_maplEstringcOboolgR (void * p) static
Definition at line 923 of file DataLibraryDict.cpp.
{
       delete ((map<string,bool>*)p);
    }
static void ROOT::delete_maplEstringcOdoublegR (void * p) static
Definition at line 780 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete ((map<string,double>*)p);
    }
static void ROOT::delete_maplEstringcOdoublegR (void * p) static
Definition at line 780 of file Dict.cxx.
{
       delete ((map<string,double>*)p);
    }
static void ROOT::delete_maplEstringcOdoublegR (void * p) static
Definition at line 981 of file DataLibraryDict.cpp.
{
       delete ((map<string,double>*)p);
    }
static void ROOT::delete_maplEstringcOdoublegR (void * p) static
Definition at line 981 of file DataLibraryDict.cpp.
{
       delete ((map<string,double>*)p);
    }
static void ROOT::delete_maplEstringcOdoublegR (void * p) static
Definition at line 1364 of file DataLibraryDict.cpp.
{
       delete ((map<string,double>*)p);
    }
static void ROOT::delete_maplEstringcOIDscLcLDetector_tgR (void * p) static
Definition at line 1057 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((map<string,IDs::Detector_t>*)p);
    }
static void ROOT::delete_maplEstringcOintgR (void * p) static
Definition at line 838 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete ((map<string,int>*)p);
    }
static void ROOT::delete_maplEstringcOintgR (void * p) static
Definition at line 838 of file Dict.cxx.
{
       delete ((map<string,int>*)p);
    }
static void ROOT::delete_maplEstringcOintgR (void * p) static
Definition at line 1039 of file DataLibraryDict.cpp.
{
       delete ((map<string,int>*)p);
    }
static void ROOT::delete_maplEstringcOintgR (void * p) static
Definition at line 1039 of file DataLibraryDict.cpp.
{
       delete ((map<string,int>*)p);
    }
static void ROOT::delete_maplEstringcOintgR (void * p) static
Definition at line 1422 of file DataLibraryDict.cpp.
{
       delete ((map<string,int>*)p);
    }
static void ROOT::delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 777 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*)p);
    }
static void ROOT::delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 777 of file DataLibraryDict.cpp.
{
       delete ((::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*)p);
    }
static void ROOT::delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 1218 of file DataLibraryDict.cpp.
{
       delete ((::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*)p);
    }
static void ROOT::delete_maplEstringcOstringgR (void * p) static
Definition at line 896 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete ((map<string,string>*)p);
    }
static void ROOT::delete_maplEstringcOstringgR (void * p) static
Definition at line 896 of file Dict.cxx.
{
       delete ((map<string,string>*)p);
    }
static void ROOT::delete_maplEstringcOstringgR (void * p) static
Definition at line 1097 of file DataLibraryDict.cpp.
{
       delete ((map<string,string>*)p);
    }
static void ROOT::delete_maplEstringcOstringgR (void * p) static
Definition at line 1097 of file DataLibraryDict.cpp.
{
       delete ((map<string,string>*)p);
    }
static void ROOT::delete_maplEstringcOstringgR (void * p) static
Definition at line 1480 of file DataLibraryDict.cpp.
{
       delete ((map<string,string>*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 857 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 1111 of file DataLibraryDict.cpp.
{
       delete ((::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void * p) static
Definition at line 1115 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((map<string,vector<TAnalysedPulse*> >*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void * p) static
Definition at line 1538 of file DataLibraryDict.cpp.
{
       delete ((map<string,vector<TAnalysedPulse*> >*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 531 of file DataLibraryDict.cpp.
{
       delete ((::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 656 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 656 of file DataLibraryDict.cpp.
{
       delete ((::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 923 of file DataLibraryDict.cpp.
{
       delete ((::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 629 of file DataLibraryDict.cpp.
{
       delete ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 954 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 954 of file Dict.cxx.
{
       delete ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 1155 of file DataLibraryDict.cpp.
{
       delete ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 1155 of file DataLibraryDict.cpp.
{
       delete ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 1596 of file DataLibraryDict.cpp.
{
       delete ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::delete_pairlEstringcOstringgR (void * p) static
Definition at line 817 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((pair<string,string>*)p);
    }
static void ROOT::delete_pairlEstringcOstringgR (void * p) static
Definition at line 817 of file DataLibraryDict.cpp.
{
       delete ((pair<string,string>*)p);
    }
static void ROOT::delete_pairlEstringcOstringgR (void * p) static
Definition at line 1258 of file DataLibraryDict.cpp.
{
       delete ((pair<string,string>*)p);
    }
static void ROOT::delete_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void * p) static
Definition at line 897 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*)p);
    }
static void ROOT::delete_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void * p) static
Definition at line 1151 of file DataLibraryDict.cpp.
{
       delete ((pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*)p);
    }
static void ROOT::delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 571 of file DataLibraryDict.cpp.
{
       delete ((pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)p);
    }
static void ROOT::delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 696 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)p);
    }
static void ROOT::delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 696 of file DataLibraryDict.cpp.
{
       delete ((pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)p);
    }
static void ROOT::delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 963 of file DataLibraryDict.cpp.
{
       delete ((pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)p);
    }
static void ROOT::delete_TAnalysedPulse (void * p) static
Definition at line 767 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::TAnalysedPulse*)p);
    }
static void ROOT::delete_TAnalysedPulse (void * p) static
Definition at line 1069 of file DataLibraryDict.cpp.
{
       delete ((::TAnalysedPulse*)p);
    }
static void ROOT::delete_TAnalysedPulseMapWrapper (void * p) static
Definition at line 941 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::TAnalysedPulseMapWrapper*)p);
    }
static void ROOT::delete_TDetectorPulse (void * p) static
Definition at line 815 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::TDetectorPulse*)p);
    }
static void ROOT::delete_TDetectorPulse (void * p) static
Definition at line 1197 of file DataLibraryDict.cpp.
{
       delete ((::TDetectorPulse*)p);
    }
static void ROOT::delete_TGlobalData (void * p) static
Definition at line 408 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::TGlobalData*)p);
    }
static void ROOT::delete_TGlobalData (void * p) static
Definition at line 408 of file Dict.cxx.
{
       delete ((::TGlobalData*)p);
    }
static void ROOT::delete_TGlobalData (void * p) static
Definition at line 402 of file DataLibraryDict.cpp.
{
       delete ((::TGlobalData*)p);
    }
static void ROOT::delete_TGlobalData (void * p) static
Definition at line 567 of file DataLibraryDict.cpp.
{
       delete ((::TGlobalData*)p);
    }
static void ROOT::delete_TGlobalData (void * p) static
Definition at line 567 of file DataLibraryDict.cpp.
{
       delete ((::TGlobalData*)p);
    }
static void ROOT::delete_TGlobalData (void * p) static
Definition at line 834 of file DataLibraryDict.cpp.
{
       delete ((::TGlobalData*)p);
    }
static void ROOT::delete_TOctalFADCIsland (void * p) static
Definition at line 441 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::TOctalFADCIsland*)p);
    }
static void ROOT::delete_TPulseIsland (void * p) static
Definition at line 315 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::TPulseIsland*)p);
    }
static void ROOT::delete_TPulseIsland (void * p) static
Definition at line 315 of file Dict.cxx.
{
       delete ((::TPulseIsland*)p);
    }
static void ROOT::delete_TPulseIsland (void * p) static
Definition at line 489 of file DataLibraryDict.cpp.
{
       delete ((::TPulseIsland*)p);
    }
static void ROOT::delete_TPulseIsland (void * p) static
Definition at line 614 of file DataLibraryDict.cpp.
{
       delete ((::TPulseIsland*)p);
    }
static void ROOT::delete_TPulseIsland (void * p) static
Definition at line 614 of file DataLibraryDict.cpp.
{
       delete ((::TPulseIsland*)p);
    }
static void ROOT::delete_TPulseIsland (void * p) static
Definition at line 881 of file DataLibraryDict.cpp.
{
       delete ((::TPulseIsland*)p);
    }
static void ROOT::delete_TSetupData (void * p) static
Definition at line 718 of file Dict.cxx.
{
       delete ((::TSetupData*)p);
    }
static void ROOT::delete_TSetupData (void * p) static
Definition at line 718 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::TSetupData*)p);
    }
static void ROOT::delete_TSetupData (void * p) static
Definition at line 756 of file DataLibraryDict.cpp.
{
       delete ((::TSetupData*)p);
    }
static void ROOT::delete_TSetupData (void * p) static
Definition at line 756 of file DataLibraryDict.cpp.
{
       delete ((::TSetupData*)p);
    }
static void ROOT::delete_TSetupData (void * p) static
Definition at line 1021 of file DataLibraryDict.cpp.
{
       delete ((::TSetupData*)p);
    }
static void ROOT::delete_TVacuumData (void * p) static
Definition at line 865 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::TVacuumData*)p);
    }
static void ROOT::delete_TVacuumData (void * p) static
Definition at line 865 of file DataLibraryDict.cpp.
{
       delete ((::TVacuumData*)p);
    }
static void ROOT::delete_TVacuumData (void * p) static
Definition at line 1306 of file DataLibraryDict.cpp.
{
       delete ((::TVacuumData*)p);
    }
static void ROOT::delete_vectorlEfloatgR (void * p) static
Definition at line 1271 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((vector<float>*)p);
    }
static void ROOT::delete_vectorlEfloatgR (void * p) static
Definition at line 1271 of file DataLibraryDict.cpp.
{
       delete ((vector<float>*)p);
    }
static void ROOT::delete_vectorlEfloatgR (void * p) static
Definition at line 1770 of file DataLibraryDict.cpp.
{
       delete ((vector<float>*)p);
    }
static void ROOT::delete_vectorlEintgR (void * p) static
Definition at line 745 of file DataLibraryDict.cpp.
{
       delete ((vector<int>*)p);
    }
static void ROOT::delete_vectorlEintgR (void * p) static
Definition at line 1070 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete ((vector<int>*)p);
    }
static void ROOT::delete_vectorlEintgR (void * p) static
Definition at line 1070 of file Dict.cxx.
{
       delete ((vector<int>*)p);
    }
static void ROOT::delete_vectorlEintgR (void * p) static
Definition at line 1329 of file DataLibraryDict.cpp.
{
       delete ((vector<int>*)p);
    }
static void ROOT::delete_vectorlEintgR (void * p) static
Definition at line 1329 of file DataLibraryDict.cpp.
{
       delete ((vector<int>*)p);
    }
static void ROOT::delete_vectorlEintgR (void * p) static
Definition at line 1828 of file DataLibraryDict.cpp.
{
       delete ((vector<int>*)p);
    }
static void ROOT::delete_vectorlEstringgR (void * p) static
Definition at line 1231 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((vector<string>*)p);
    }
static void ROOT::delete_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void * p) static
Definition at line 836 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*)p);
    }
static void ROOT::delete_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void * p) static
Definition at line 1090 of file DataLibraryDict.cpp.
{
       delete ((::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*)p);
    }
static void ROOT::delete_vectorlETAnalysedPulsemUgR (void * p) static
Definition at line 1173 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((vector<TAnalysedPulse*>*)p);
    }
static void ROOT::delete_vectorlETAnalysedPulsemUgR (void * p) static
Definition at line 1654 of file DataLibraryDict.cpp.
{
       delete ((vector<TAnalysedPulse*>*)p);
    }
static void ROOT::delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 510 of file DataLibraryDict.cpp.
{
       delete ((::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)p);
    }
static void ROOT::delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 635 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete ((::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)p);
    }
static void ROOT::delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 635 of file DataLibraryDict.cpp.
{
       delete ((::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)p);
    }
static void ROOT::delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 902 of file DataLibraryDict.cpp.
{
       delete ((::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)p);
    }
static void ROOT::delete_vectorlETPulseIslandmUgR (void * p) static
Definition at line 687 of file DataLibraryDict.cpp.
{
       delete ((vector<TPulseIsland*>*)p);
    }
static void ROOT::delete_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1012 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete ((vector<TPulseIsland*>*)p);
    }
static void ROOT::delete_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1012 of file Dict.cxx.
{
       delete ((vector<TPulseIsland*>*)p);
    }
static void ROOT::delete_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1213 of file DataLibraryDict.cpp.
{
       delete ((vector<TPulseIsland*>*)p);
    }
static void ROOT::delete_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1213 of file DataLibraryDict.cpp.
{
       delete ((vector<TPulseIsland*>*)p);
    }
static void ROOT::delete_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1712 of file DataLibraryDict.cpp.
{
       delete ((vector<TPulseIsland*>*)p);
    }
static void ROOT::deleteArray_IDscLcLchannel (void * p) static
Definition at line 620 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::IDs::channel*)p);
    }
static void ROOT::deleteArray_IDscLcLgenerator (void * p) static
Definition at line 670 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::IDs::generator*)p);
    }
static void ROOT::deleteArray_IDscLcLsource (void * p) static
Definition at line 720 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::IDs::source*)p);
    }
static void ROOT::deleteArray_maplEIDscLcLDetector_tcOstringgR (void * p) static
Definition at line 1002 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((map<IDs::Detector_t,string>*)p);
    }
static void ROOT::deleteArray_maplEstringcOboolgR (void * p) static
Definition at line 926 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((map<string,bool>*)p);
    }
static void ROOT::deleteArray_maplEstringcOboolgR (void * p) static
Definition at line 926 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,bool>*)p);
    }
static void ROOT::deleteArray_maplEstringcOdoublegR (void * p) static
Definition at line 783 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((map<string,double>*)p);
    }
static void ROOT::deleteArray_maplEstringcOdoublegR (void * p) static
Definition at line 783 of file Dict.cxx.
{
       delete [] ((map<string,double>*)p);
    }
static void ROOT::deleteArray_maplEstringcOdoublegR (void * p) static
Definition at line 984 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,double>*)p);
    }
static void ROOT::deleteArray_maplEstringcOdoublegR (void * p) static
Definition at line 984 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,double>*)p);
    }
static void ROOT::deleteArray_maplEstringcOdoublegR (void * p) static
Definition at line 1367 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,double>*)p);
    }
static void ROOT::deleteArray_maplEstringcOIDscLcLDetector_tgR (void * p) static
Definition at line 1060 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((map<string,IDs::Detector_t>*)p);
    }
static void ROOT::deleteArray_maplEstringcOintgR (void * p) static
Definition at line 841 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((map<string,int>*)p);
    }
static void ROOT::deleteArray_maplEstringcOintgR (void * p) static
Definition at line 841 of file Dict.cxx.
{
       delete [] ((map<string,int>*)p);
    }
static void ROOT::deleteArray_maplEstringcOintgR (void * p) static
Definition at line 1042 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,int>*)p);
    }
static void ROOT::deleteArray_maplEstringcOintgR (void * p) static
Definition at line 1042 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,int>*)p);
    }
static void ROOT::deleteArray_maplEstringcOintgR (void * p) static
Definition at line 1425 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,int>*)p);
    }
static void ROOT::deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 780 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*)p);
    }
static void ROOT::deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 780 of file DataLibraryDict.cpp.
{
       delete [] ((::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*)p);
    }
static void ROOT::deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 1221 of file DataLibraryDict.cpp.
{
       delete [] ((::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*)p);
    }
static void ROOT::deleteArray_maplEstringcOstringgR (void * p) static
Definition at line 899 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((map<string,string>*)p);
    }
static void ROOT::deleteArray_maplEstringcOstringgR (void * p) static
Definition at line 899 of file Dict.cxx.
{
       delete [] ((map<string,string>*)p);
    }
static void ROOT::deleteArray_maplEstringcOstringgR (void * p) static
Definition at line 1100 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,string>*)p);
    }
static void ROOT::deleteArray_maplEstringcOstringgR (void * p) static
Definition at line 1100 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,string>*)p);
    }
static void ROOT::deleteArray_maplEstringcOstringgR (void * p) static
Definition at line 1483 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,string>*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 860 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 1114 of file DataLibraryDict.cpp.
{
       delete [] ((::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void * p) static
Definition at line 1118 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((map<string,vector<TAnalysedPulse*> >*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void * p) static
Definition at line 1541 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,vector<TAnalysedPulse*> >*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 534 of file DataLibraryDict.cpp.
{
       delete [] ((::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 659 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 659 of file DataLibraryDict.cpp.
{
       delete [] ((::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 926 of file DataLibraryDict.cpp.
{
       delete [] ((::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 632 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 957 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 957 of file Dict.cxx.
{
       delete [] ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 1158 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 1158 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 1599 of file DataLibraryDict.cpp.
{
       delete [] ((map<string,vector<TPulseIsland*> >*)p);
    }
static void ROOT::deleteArray_pairlEstringcOstringgR (void * p) static
Definition at line 820 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((pair<string,string>*)p);
    }
static void ROOT::deleteArray_pairlEstringcOstringgR (void * p) static
Definition at line 820 of file DataLibraryDict.cpp.
{
       delete [] ((pair<string,string>*)p);
    }
static void ROOT::deleteArray_pairlEstringcOstringgR (void * p) static
Definition at line 1261 of file DataLibraryDict.cpp.
{
       delete [] ((pair<string,string>*)p);
    }
static void ROOT::deleteArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void * p) static
Definition at line 900 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*)p);
    }
static void ROOT::deleteArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void * p) static
Definition at line 1154 of file DataLibraryDict.cpp.
{
       delete [] ((pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*)p);
    }
static void ROOT::deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 574 of file DataLibraryDict.cpp.
{
       delete [] ((pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)p);
    }
static void ROOT::deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 699 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)p);
    }
static void ROOT::deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 699 of file DataLibraryDict.cpp.
{
       delete [] ((pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)p);
    }
static void ROOT::deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 966 of file DataLibraryDict.cpp.
{
       delete [] ((pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)p);
    }
static void ROOT::deleteArray_TAnalysedPulse (void * p) static
Definition at line 770 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::TAnalysedPulse*)p);
    }
static void ROOT::deleteArray_TAnalysedPulse (void * p) static
Definition at line 1072 of file DataLibraryDict.cpp.
{
       delete [] ((::TAnalysedPulse*)p);
    }
static void ROOT::deleteArray_TAnalysedPulseMapWrapper (void * p) static
Definition at line 944 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::TAnalysedPulseMapWrapper*)p);
    }
static void ROOT::deleteArray_TDetectorPulse (void * p) static
Definition at line 818 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::TDetectorPulse*)p);
    }
static void ROOT::deleteArray_TDetectorPulse (void * p) static
Definition at line 1200 of file DataLibraryDict.cpp.
{
       delete [] ((::TDetectorPulse*)p);
    }
static void ROOT::deleteArray_TGlobalData (void * p) static
Definition at line 411 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::TGlobalData*)p);
    }
static void ROOT::deleteArray_TGlobalData (void * p) static
Definition at line 411 of file Dict.cxx.
{
       delete [] ((::TGlobalData*)p);
    }
static void ROOT::deleteArray_TGlobalData (void * p) static
Definition at line 405 of file DataLibraryDict.cpp.
{
       delete [] ((::TGlobalData*)p);
    }
static void ROOT::deleteArray_TGlobalData (void * p) static
Definition at line 570 of file DataLibraryDict.cpp.
{
       delete [] ((::TGlobalData*)p);
    }
static void ROOT::deleteArray_TGlobalData (void * p) static
Definition at line 570 of file DataLibraryDict.cpp.
{
       delete [] ((::TGlobalData*)p);
    }
static void ROOT::deleteArray_TGlobalData (void * p) static
Definition at line 837 of file DataLibraryDict.cpp.
{
       delete [] ((::TGlobalData*)p);
    }
static void ROOT::deleteArray_TOctalFADCIsland (void * p) static
Definition at line 444 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::TOctalFADCIsland*)p);
    }
static void ROOT::deleteArray_TPulseIsland (void * p) static
Definition at line 318 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::TPulseIsland*)p);
    }
static void ROOT::deleteArray_TPulseIsland (void * p) static
Definition at line 318 of file Dict.cxx.
{
       delete [] ((::TPulseIsland*)p);
    }
static void ROOT::deleteArray_TPulseIsland (void * p) static
Definition at line 492 of file DataLibraryDict.cpp.
{
       delete [] ((::TPulseIsland*)p);
    }
static void ROOT::deleteArray_TPulseIsland (void * p) static
Definition at line 617 of file DataLibraryDict.cpp.
{
       delete [] ((::TPulseIsland*)p);
    }
static void ROOT::deleteArray_TPulseIsland (void * p) static
Definition at line 617 of file DataLibraryDict.cpp.
{
       delete [] ((::TPulseIsland*)p);
    }
static void ROOT::deleteArray_TPulseIsland (void * p) static
Definition at line 884 of file DataLibraryDict.cpp.
{
       delete [] ((::TPulseIsland*)p);
    }
static void ROOT::deleteArray_TSetupData (void * p) static
Definition at line 721 of file Dict.cxx.
{
       delete [] ((::TSetupData*)p);
    }
static void ROOT::deleteArray_TSetupData (void * p) static
Definition at line 721 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::TSetupData*)p);
    }
static void ROOT::deleteArray_TSetupData (void * p) static
Definition at line 759 of file DataLibraryDict.cpp.
{
       delete [] ((::TSetupData*)p);
    }
static void ROOT::deleteArray_TSetupData (void * p) static
Definition at line 759 of file DataLibraryDict.cpp.
{
       delete [] ((::TSetupData*)p);
    }
static void ROOT::deleteArray_TSetupData (void * p) static
Definition at line 1024 of file DataLibraryDict.cpp.
{
       delete [] ((::TSetupData*)p);
    }
static void ROOT::deleteArray_TVacuumData (void * p) static
Definition at line 868 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::TVacuumData*)p);
    }
static void ROOT::deleteArray_TVacuumData (void * p) static
Definition at line 868 of file DataLibraryDict.cpp.
{
       delete [] ((::TVacuumData*)p);
    }
static void ROOT::deleteArray_TVacuumData (void * p) static
Definition at line 1309 of file DataLibraryDict.cpp.
{
       delete [] ((::TVacuumData*)p);
    }
static void ROOT::deleteArray_vectorlEfloatgR (void * p) static
Definition at line 1274 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((vector<float>*)p);
    }
static void ROOT::deleteArray_vectorlEfloatgR (void * p) static
Definition at line 1274 of file DataLibraryDict.cpp.
{
       delete [] ((vector<float>*)p);
    }
static void ROOT::deleteArray_vectorlEfloatgR (void * p) static
Definition at line 1773 of file DataLibraryDict.cpp.
{
       delete [] ((vector<float>*)p);
    }
static void ROOT::deleteArray_vectorlEintgR (void * p) static
Definition at line 748 of file DataLibraryDict.cpp.
{
       delete [] ((vector<int>*)p);
    }
static void ROOT::deleteArray_vectorlEintgR (void * p) static
Definition at line 1073 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((vector<int>*)p);
    }
static void ROOT::deleteArray_vectorlEintgR (void * p) static
Definition at line 1073 of file Dict.cxx.
{
       delete [] ((vector<int>*)p);
    }
static void ROOT::deleteArray_vectorlEintgR (void * p) static
Definition at line 1332 of file DataLibraryDict.cpp.
{
       delete [] ((vector<int>*)p);
    }
static void ROOT::deleteArray_vectorlEintgR (void * p) static
Definition at line 1332 of file DataLibraryDict.cpp.
{
       delete [] ((vector<int>*)p);
    }
static void ROOT::deleteArray_vectorlEintgR (void * p) static
Definition at line 1831 of file DataLibraryDict.cpp.
{
       delete [] ((vector<int>*)p);
    }
static void ROOT::deleteArray_vectorlEstringgR (void * p) static
Definition at line 1234 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((vector<string>*)p);
    }
static void ROOT::deleteArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void * p) static
Definition at line 839 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*)p);
    }
static void ROOT::deleteArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void * p) static
Definition at line 1093 of file DataLibraryDict.cpp.
{
       delete [] ((::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*)p);
    }
static void ROOT::deleteArray_vectorlETAnalysedPulsemUgR (void * p) static
Definition at line 1176 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((vector<TAnalysedPulse*>*)p);
    }
static void ROOT::deleteArray_vectorlETAnalysedPulsemUgR (void * p) static
Definition at line 1657 of file DataLibraryDict.cpp.
{
       delete [] ((vector<TAnalysedPulse*>*)p);
    }
static void ROOT::deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 513 of file DataLibraryDict.cpp.
{
       delete [] ((::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)p);
    }
static void ROOT::deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 638 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)p);
    }
static void ROOT::deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 638 of file DataLibraryDict.cpp.
{
       delete [] ((::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)p);
    }
static void ROOT::deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 905 of file DataLibraryDict.cpp.
{
       delete [] ((::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)p);
    }
static void ROOT::deleteArray_vectorlETPulseIslandmUgR (void * p) static
Definition at line 690 of file DataLibraryDict.cpp.
{
       delete [] ((vector<TPulseIsland*>*)p);
    }
static void ROOT::deleteArray_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1015 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       delete [] ((vector<TPulseIsland*>*)p);
    }
static void ROOT::deleteArray_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1015 of file Dict.cxx.
{
       delete [] ((vector<TPulseIsland*>*)p);
    }
static void ROOT::deleteArray_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1216 of file DataLibraryDict.cpp.
{
       delete [] ((vector<TPulseIsland*>*)p);
    }
static void ROOT::deleteArray_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1216 of file DataLibraryDict.cpp.
{
       delete [] ((vector<TPulseIsland*>*)p);
    }
static void ROOT::deleteArray_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1715 of file DataLibraryDict.cpp.
{
       delete [] ((vector<TPulseIsland*>*)p);
    }
static void ROOT::destruct_IDscLcLchannel (void * p) static
Definition at line 623 of file RootanaDataClasses.cpp.
References channel.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::IDs::channel current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_IDscLcLgenerator (void * p) static
Definition at line 673 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::IDs::generator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_IDscLcLsource (void * p) static
Definition at line 723 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::IDs::source current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEIDscLcLDetector_tcOstringgR (void * p) static
Definition at line 1005 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef map<IDs::Detector_t,string> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOboolgR (void * p) static
Definition at line 929 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef map<string,bool> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOboolgR (void * p) static
Definition at line 929 of file DataLibraryDict.cpp.
{
       typedef map<string,bool> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOdoublegR (void * p) static
Definition at line 786 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       typedef map<string,double> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOdoublegR (void * p) static
Definition at line 786 of file Dict.cxx.
{
       typedef map<string,double> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOdoublegR (void * p) static
Definition at line 987 of file DataLibraryDict.cpp.
{
       typedef map<string,double> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOdoublegR (void * p) static
Definition at line 987 of file DataLibraryDict.cpp.
{
       typedef map<string,double> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOdoublegR (void * p) static
Definition at line 1370 of file DataLibraryDict.cpp.
{
       typedef map<string,double> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOIDscLcLDetector_tgR (void * p) static
Definition at line 1063 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef map<string,IDs::Detector_t> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOintgR (void * p) static
Definition at line 844 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       typedef map<string,int> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOintgR (void * p) static
Definition at line 844 of file Dict.cxx.
{
       typedef map<string,int> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOintgR (void * p) static
Definition at line 1045 of file DataLibraryDict.cpp.
{
       typedef map<string,int> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOintgR (void * p) static
Definition at line 1045 of file DataLibraryDict.cpp.
{
       typedef map<string,int> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOintgR (void * p) static
Definition at line 1428 of file DataLibraryDict.cpp.
{
       typedef map<string,int> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 783 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 783 of file DataLibraryDict.cpp.
{
       typedef ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 1224 of file DataLibraryDict.cpp.
{
       typedef ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOstringgR (void * p) static
Definition at line 902 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       typedef map<string,string> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOstringgR (void * p) static
Definition at line 902 of file Dict.cxx.
{
       typedef map<string,string> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOstringgR (void * p) static
Definition at line 1103 of file DataLibraryDict.cpp.
{
       typedef map<string,string> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOstringgR (void * p) static
Definition at line 1103 of file DataLibraryDict.cpp.
{
       typedef map<string,string> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOstringgR (void * p) static
Definition at line 1486 of file DataLibraryDict.cpp.
{
       typedef map<string,string> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 863 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 1117 of file DataLibraryDict.cpp.
{
       typedef ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void * p) static
Definition at line 1121 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef map<string,vector<TAnalysedPulse*> > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void * p) static
Definition at line 1544 of file DataLibraryDict.cpp.
{
       typedef map<string,vector<TAnalysedPulse*> > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 537 of file DataLibraryDict.cpp.
{
       typedef ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 662 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 662 of file DataLibraryDict.cpp.
{
       typedef ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p) static
Definition at line 929 of file DataLibraryDict.cpp.
{
       typedef ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 635 of file DataLibraryDict.cpp.
{
       typedef map<string,vector<TPulseIsland*> > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 960 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       typedef map<string,vector<TPulseIsland*> > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 960 of file Dict.cxx.
{
       typedef map<string,vector<TPulseIsland*> > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 1161 of file DataLibraryDict.cpp.
{
       typedef map<string,vector<TPulseIsland*> > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 1161 of file DataLibraryDict.cpp.
{
       typedef map<string,vector<TPulseIsland*> > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p) static
Definition at line 1602 of file DataLibraryDict.cpp.
{
       typedef map<string,vector<TPulseIsland*> > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_pairlEstringcOstringgR (void * p) static
Definition at line 823 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef pair<string,string> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_pairlEstringcOstringgR (void * p) static
Definition at line 823 of file DataLibraryDict.cpp.
{
       typedef pair<string,string> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_pairlEstringcOstringgR (void * p) static
Definition at line 1264 of file DataLibraryDict.cpp.
{
       typedef pair<string,string> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void * p) static
Definition at line 903 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void * p) static
Definition at line 1157 of file DataLibraryDict.cpp.
{
       typedef pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 577 of file DataLibraryDict.cpp.
{
       typedef pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 702 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 702 of file DataLibraryDict.cpp.
{
       typedef pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p) static
Definition at line 969 of file DataLibraryDict.cpp.
{
       typedef pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TAnalysedPulse (void * p) static
Definition at line 773 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::TAnalysedPulse current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TAnalysedPulse (void * p) static
Definition at line 1075 of file DataLibraryDict.cpp.
{
       typedef ::TAnalysedPulse current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TAnalysedPulseMapWrapper (void * p) static
Definition at line 947 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::TAnalysedPulseMapWrapper current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TDetectorPulse (void * p) static
Definition at line 821 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::TDetectorPulse current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TDetectorPulse (void * p) static
Definition at line 1203 of file DataLibraryDict.cpp.
{
       typedef ::TDetectorPulse current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TGlobalData (void * p) static
Definition at line 414 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::TGlobalData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TGlobalData (void * p) static
Definition at line 414 of file Dict.cxx.
{
       typedef ::TGlobalData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TGlobalData (void * p) static
Definition at line 408 of file DataLibraryDict.cpp.
{
       typedef ::TGlobalData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TGlobalData (void * p) static
Definition at line 573 of file DataLibraryDict.cpp.
{
       typedef ::TGlobalData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TGlobalData (void * p) static
Definition at line 573 of file DataLibraryDict.cpp.
{
       typedef ::TGlobalData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TGlobalData (void * p) static
Definition at line 840 of file DataLibraryDict.cpp.
{
       typedef ::TGlobalData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TOctalFADCIsland (void * p) static
Definition at line 447 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::TOctalFADCIsland current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TPulseIsland (void * p) static
Definition at line 321 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::TPulseIsland current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TPulseIsland (void * p) static
Definition at line 321 of file Dict.cxx.
{
       typedef ::TPulseIsland current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TPulseIsland (void * p) static
Definition at line 495 of file DataLibraryDict.cpp.
{
       typedef ::TPulseIsland current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TPulseIsland (void * p) static
Definition at line 620 of file DataLibraryDict.cpp.
{
       typedef ::TPulseIsland current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TPulseIsland (void * p) static
Definition at line 620 of file DataLibraryDict.cpp.
{
       typedef ::TPulseIsland current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TPulseIsland (void * p) static
Definition at line 887 of file DataLibraryDict.cpp.
{
       typedef ::TPulseIsland current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TSetupData (void * p) static
Definition at line 724 of file Dict.cxx.
{
       typedef ::TSetupData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TSetupData (void * p) static
Definition at line 724 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::TSetupData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TSetupData (void * p) static
Definition at line 762 of file DataLibraryDict.cpp.
{
       typedef ::TSetupData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TSetupData (void * p) static
Definition at line 762 of file DataLibraryDict.cpp.
{
       typedef ::TSetupData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TSetupData (void * p) static
Definition at line 1027 of file DataLibraryDict.cpp.
{
       typedef ::TSetupData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TVacuumData (void * p) static
Definition at line 871 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::TVacuumData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TVacuumData (void * p) static
Definition at line 871 of file DataLibraryDict.cpp.
{
       typedef ::TVacuumData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_TVacuumData (void * p) static
Definition at line 1312 of file DataLibraryDict.cpp.
{
       typedef ::TVacuumData current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlEfloatgR (void * p) static
Definition at line 1277 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef vector<float> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlEfloatgR (void * p) static
Definition at line 1277 of file DataLibraryDict.cpp.
{
       typedef vector<float> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlEfloatgR (void * p) static
Definition at line 1776 of file DataLibraryDict.cpp.
{
       typedef vector<float> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlEintgR (void * p) static
Definition at line 751 of file DataLibraryDict.cpp.
{
       typedef vector<int> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlEintgR (void * p) static
Definition at line 1076 of file Dict.cxx.
{
       typedef vector<int> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlEintgR (void * p) static
Definition at line 1076 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       typedef vector<int> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlEintgR (void * p) static
Definition at line 1335 of file DataLibraryDict.cpp.
{
       typedef vector<int> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlEintgR (void * p) static
Definition at line 1335 of file DataLibraryDict.cpp.
{
       typedef vector<int> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlEintgR (void * p) static
Definition at line 1834 of file DataLibraryDict.cpp.
{
       typedef vector<int> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlEstringgR (void * p) static
Definition at line 1237 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef vector<string> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void * p) static
Definition at line 842 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void * p) static
Definition at line 1096 of file DataLibraryDict.cpp.
{
       typedef ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETAnalysedPulsemUgR (void * p) static
Definition at line 1179 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef vector<TAnalysedPulse*> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETAnalysedPulsemUgR (void * p) static
Definition at line 1660 of file DataLibraryDict.cpp.
{
       typedef vector<TAnalysedPulse*> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 516 of file DataLibraryDict.cpp.
{
       typedef ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 641 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       typedef ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 641 of file DataLibraryDict.cpp.
{
       typedef ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p) static
Definition at line 908 of file DataLibraryDict.cpp.
{
       typedef ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETPulseIslandmUgR (void * p) static
Definition at line 693 of file DataLibraryDict.cpp.
{
       typedef vector<TPulseIsland*> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1018 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       typedef vector<TPulseIsland*> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1018 of file Dict.cxx.
{
       typedef vector<TPulseIsland*> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1219 of file DataLibraryDict.cpp.
{
       typedef vector<TPulseIsland*> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1219 of file DataLibraryDict.cpp.
{
       typedef vector<TPulseIsland*> current_t;
       ((current_t*)p)->~current_t();
    }
static void ROOT::destruct_vectorlETPulseIslandmUgR (void * p) static
Definition at line 1718 of file DataLibraryDict.cpp.
{
       typedef vector<TPulseIsland*> current_t;
       ((current_t*)p)->~current_t();
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TSetupData *)
Definition at line 68 of file AlcapDict.cxx.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::TSetupData*)0);
    }
TGenericClassInfo* ROOT::GenerateInitInstance (const ::IDs::channel *)
Definition at line 77 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::IDs::channel*)0);
    }
TGenericClassInfo* ROOT::GenerateInitInstance (const ::TOctalFADCIsland *)
Definition at line 100 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::TOctalFADCIsland*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TPulseIsland *)
Definition at line 103 of file AlcapDict.cxx.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::TPulseIsland*)0);
    }
TGenericClassInfo* ROOT::GenerateInitInstance (const ::IDs::generator *)
Definition at line 110 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::IDs::generator*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const pair< string, string > *)
Definition at line 124 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((pair<string,string>*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TGlobalData *)
Definition at line 138 of file AlcapDict.cxx.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::TGlobalData*)0);
    }
TGenericClassInfo* ROOT::GenerateInitInstance (const ::IDs::source *)
Definition at line 143 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::IDs::source*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const ::map< string, string, less< string >, allocator< pair< const string, string > > >::iterator *)
Definition at line 164 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TAnalysedPulse *)
Definition at line 176 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::TAnalysedPulse*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const ::vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >::iterator *)
Definition at line 210 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const pair< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > *)
Definition at line 252 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *)
Definition at line 270 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const ::map< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >, less< string >, allocator< pair< const string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > > >::iterator *)
Definition at line 292 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *)
Definition at line 312 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TDetectorPulse *)
Definition at line 331 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::TDetectorPulse*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *)
Definition at line 352 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)0);
    }
TGenericClassInfo* ROOT::GenerateInitInstance (const ::TAnalysedPulseMapWrapper *)
Definition at line 364 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::TAnalysedPulseMapWrapper*)0);
    }
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TVacuumData *)
Definition at line 391 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
    {
       return GenerateInitInstanceLocal((::TVacuumData*)0);
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TSetupData *) static
Definition at line 51 of file Dict.cxx.
References delete_TSetupData(), deleteArray_TSetupData(), destruct_TSetupData(), new_TSetupData(), newArray_TSetupData(), and streamer_TSetupData().
    {
       ::TSetupData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TSetupData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TSetupData", ::TSetupData::Class_Version(), "./../src/common/TSetupData.h", 13,
                   typeid(::TSetupData), DefineBehavior(ptr, ptr),
                   &::TSetupData::Dictionary, isa_proxy, 0,
                   sizeof(::TSetupData) );
       instance.SetNew(&new_TSetupData);
       instance.SetNewArray(&newArray_TSetupData);
       instance.SetDelete(&delete_TSetupData);
       instance.SetDeleteArray(&deleteArray_TSetupData);
       instance.SetDestructor(&destruct_TSetupData);
       instance.SetStreamerFunc(&streamer_TSetupData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TSetupData *) static
Definition at line 51 of file AlcapDict.cxx.
References delete_TSetupData(), deleteArray_TSetupData(), destruct_TSetupData(), new_TSetupData(), newArray_TSetupData(), and streamer_TSetupData().
    {
       ::TSetupData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TSetupData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TSetupData", ::TSetupData::Class_Version(), "./../src/common/TSetupData.h", 13,
                   typeid(::TSetupData), DefineBehavior(ptr, ptr),
                   &::TSetupData::Dictionary, isa_proxy, 0,
                   sizeof(::TSetupData) );
       instance.SetNew(&new_TSetupData);
       instance.SetNewArray(&newArray_TSetupData);
       instance.SetDelete(&delete_TSetupData);
       instance.SetDeleteArray(&deleteArray_TSetupData);
       instance.SetDestructor(&destruct_TSetupData);
       instance.SetStreamerFunc(&streamer_TSetupData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::IDs::channel *) static
Definition at line 61 of file RootanaDataClasses.cpp.
References delete_IDscLcLchannel(), deleteArray_IDscLcLchannel(), destruct_IDscLcLchannel(), new_IDscLcLchannel(), and newArray_IDscLcLchannel().
Referenced by GenerateInitInstance(), maplEIDscLcLDetector_tcOstringgR_Dictionary(), maplEstringcOboolgR_Dictionary(), maplEstringcOdoublegR_Dictionary(), maplEstringcOIDscLcLDetector_tgR_Dictionary(), maplEstringcOintgR_Dictionary(), maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary(), maplEstringcOstringgR_Dictionary(), maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary(), maplEstringcOvectorlETAnalysedPulsemUgRsPgR_Dictionary(), maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary(), maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary(), pairlEstringcOstringgR_Dictionary(), pairlEstringcOstringgR_ShowMembers(), pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_Dictionary(), pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_ShowMembers(), pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary(), pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers(), TOctalFADCIsland_Dictionary(), TOctalFADCIsland_ShowMembers(), vectorlEfloatgR_Dictionary(), vectorlEintgR_Dictionary(), vectorlEstringgR_Dictionary(), vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_Dictionary(), vectorlETAnalysedPulsemUgR_Dictionary(), vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary(), and vectorlETPulseIslandmUgR_Dictionary().
    {
       ::IDs::channel *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::IDs::channel >(0);
       static ::ROOT::TGenericClassInfo
          instance("IDs::channel", ::IDs::channel::Class_Version(), "src/framework/IdChannel.h", 25,
                   typeid(::IDs::channel), DefineBehavior(ptr, ptr),
                   &::IDs::channel::Dictionary, isa_proxy, 4,
                   sizeof(::IDs::channel) );
       instance.SetNew(&new_IDscLcLchannel);
       instance.SetNewArray(&newArray_IDscLcLchannel);
       instance.SetDelete(&delete_IDscLcLchannel);
       instance.SetDeleteArray(&deleteArray_IDscLcLchannel);
       instance.SetDestructor(&destruct_IDscLcLchannel);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TSetupData *) static
Definition at line 72 of file DataLibraryDict.cpp.
References delete_TSetupData(), deleteArray_TSetupData(), destruct_TSetupData(), new_TSetupData(), and newArray_TSetupData().
    {
       ::TSetupData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TSetupData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TSetupData", ::TSetupData::Class_Version(), "./../../src/common/TSetupData.h", 13,
                   typeid(::TSetupData), DefineBehavior(ptr, ptr),
                   &::TSetupData::Dictionary, isa_proxy, 4,
                   sizeof(::TSetupData) );
       instance.SetNew(&new_TSetupData);
       instance.SetNewArray(&newArray_TSetupData);
       instance.SetDelete(&delete_TSetupData);
       instance.SetDeleteArray(&deleteArray_TSetupData);
       instance.SetDestructor(&destruct_TSetupData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TSetupData *) static
Definition at line 72 of file DataLibraryDict.cpp.
References delete_TSetupData(), deleteArray_TSetupData(), destruct_TSetupData(), new_TSetupData(), and newArray_TSetupData().
    {
       ::TSetupData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TSetupData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TSetupData", ::TSetupData::Class_Version(), "./../../src/common/TSetupData.h", 13,
                   typeid(::TSetupData), DefineBehavior(ptr, ptr),
                   &::TSetupData::Dictionary, isa_proxy, 4,
                   sizeof(::TSetupData) );
       instance.SetNew(&new_TSetupData);
       instance.SetNewArray(&newArray_TSetupData);
       instance.SetDelete(&delete_TSetupData);
       instance.SetDeleteArray(&deleteArray_TSetupData);
       instance.SetDestructor(&destruct_TSetupData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TOctalFADCIsland *) static
Definition at line 82 of file DataLibraryDict.cpp.
References delete_TOctalFADCIsland(), deleteArray_TOctalFADCIsland(), destruct_TOctalFADCIsland(), new_TOctalFADCIsland(), newArray_TOctalFADCIsland(), TOctalFADCIsland_Dictionary(), and TOctalFADCIsland_ShowMembers().
    {
       // Make sure the shadow class has the right sizeof
       R__ASSERT(sizeof(::TOctalFADCIsland) == sizeof(::ROOT::Shadow::TOctalFADCIsland));
       ::TOctalFADCIsland *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::TOctalFADCIsland),0);
       static ::ROOT::TGenericClassInfo
          instance("TOctalFADCIsland", "./../../src/FADC/TOctalFADCIsland.h", 10,
                   typeid(::TOctalFADCIsland), DefineBehavior(ptr, ptr),
                   &TOctalFADCIsland_ShowMembers, &TOctalFADCIsland_Dictionary, isa_proxy, 4,
                   sizeof(::TOctalFADCIsland) );
       instance.SetNew(&new_TOctalFADCIsland);
       instance.SetNewArray(&newArray_TOctalFADCIsland);
       instance.SetDelete(&delete_TOctalFADCIsland);
       instance.SetDeleteArray(&deleteArray_TOctalFADCIsland);
       instance.SetDestructor(&destruct_TOctalFADCIsland);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TSetupData *) static
Definition at line 83 of file DataLibraryDict.cpp.
References delete_TSetupData(), deleteArray_TSetupData(), destruct_TSetupData(), new_TSetupData(), and newArray_TSetupData().
    {
       ::TSetupData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TSetupData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TSetupData", ::TSetupData::Class_Version(), "./../../src/common/TSetupData.h", 13,
                   typeid(::TSetupData), DefineBehavior(ptr, ptr),
                   &::TSetupData::Dictionary, isa_proxy, 4,
                   sizeof(::TSetupData) );
       instance.SetNew(&new_TSetupData);
       instance.SetNewArray(&newArray_TSetupData);
       instance.SetDelete(&delete_TSetupData);
       instance.SetDeleteArray(&deleteArray_TSetupData);
       instance.SetDestructor(&destruct_TSetupData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TPulseIsland *) static
Definition at line 86 of file Dict.cxx.
References delete_TPulseIsland(), deleteArray_TPulseIsland(), destruct_TPulseIsland(), new_TPulseIsland(), newArray_TPulseIsland(), and streamer_TPulseIsland().
    {
       ::TPulseIsland *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TPulseIsland >(0);
       static ::ROOT::TGenericClassInfo
          instance("TPulseIsland", ::TPulseIsland::Class_Version(), "./../src/common/TPulseIsland.h", 11,
                   typeid(::TPulseIsland), DefineBehavior(ptr, ptr),
                   &::TPulseIsland::Dictionary, isa_proxy, 0,
                   sizeof(::TPulseIsland) );
       instance.SetNew(&new_TPulseIsland);
       instance.SetNewArray(&newArray_TPulseIsland);
       instance.SetDelete(&delete_TPulseIsland);
       instance.SetDeleteArray(&deleteArray_TPulseIsland);
       instance.SetDestructor(&destruct_TPulseIsland);
       instance.SetStreamerFunc(&streamer_TPulseIsland);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TPulseIsland *) static
Definition at line 86 of file AlcapDict.cxx.
References delete_TPulseIsland(), deleteArray_TPulseIsland(), destruct_TPulseIsland(), new_TPulseIsland(), newArray_TPulseIsland(), and streamer_TPulseIsland().
    {
       ::TPulseIsland *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TPulseIsland >(0);
       static ::ROOT::TGenericClassInfo
          instance("TPulseIsland", ::TPulseIsland::Class_Version(), "./../src/common/TPulseIsland.h", 11,
                   typeid(::TPulseIsland), DefineBehavior(ptr, ptr),
                   &::TPulseIsland::Dictionary, isa_proxy, 0,
                   sizeof(::TPulseIsland) );
       instance.SetNew(&new_TPulseIsland);
       instance.SetNewArray(&newArray_TPulseIsland);
       instance.SetDelete(&delete_TPulseIsland);
       instance.SetDeleteArray(&deleteArray_TPulseIsland);
       instance.SetDestructor(&destruct_TPulseIsland);
       instance.SetStreamerFunc(&streamer_TPulseIsland);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::IDs::generator *) static
Definition at line 94 of file RootanaDataClasses.cpp.
References delete_IDscLcLgenerator(), deleteArray_IDscLcLgenerator(), destruct_IDscLcLgenerator(), new_IDscLcLgenerator(), and newArray_IDscLcLgenerator().
    {
       ::IDs::generator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::IDs::generator >(0);
       static ::ROOT::TGenericClassInfo
          instance("IDs::generator", ::IDs::generator::Class_Version(), "src/framework/IdGenerator.h", 19,
                   typeid(::IDs::generator), DefineBehavior(ptr, ptr),
                   &::IDs::generator::Dictionary, isa_proxy, 4,
                   sizeof(::IDs::generator) );
       instance.SetNew(&new_IDscLcLgenerator);
       instance.SetNewArray(&newArray_IDscLcLgenerator);
       instance.SetDelete(&delete_IDscLcLgenerator);
       instance.SetDeleteArray(&deleteArray_IDscLcLgenerator);
       instance.SetDestructor(&destruct_IDscLcLgenerator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const pair< string, string > *) static
Definition at line 106 of file DataLibraryDict.cpp.
References delete_pairlEstringcOstringgR(), deleteArray_pairlEstringcOstringgR(), destruct_pairlEstringcOstringgR(), new_pairlEstringcOstringgR(), newArray_pairlEstringcOstringgR(), pairlEstringcOstringgR_Dictionary(), and pairlEstringcOstringgR_ShowMembers().
    {
       // Make sure the shadow class has the right sizeof
       R__ASSERT(sizeof(pair<string,string>) == sizeof(::ROOT::Shadow::pairlEstringcOstringgR));
       pair<string,string> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(pair<string,string>),0);
       static ::ROOT::TGenericClassInfo
          instance("pair<string,string>", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/utility", 17,
                   typeid(pair<string,string>), DefineBehavior(ptr, ptr),
                   &pairlEstringcOstringgR_ShowMembers, &pairlEstringcOstringgR_Dictionary, isa_proxy, 4,
                   sizeof(pair<string,string>) );
       instance.SetNew(&new_pairlEstringcOstringgR);
       instance.SetNewArray(&newArray_pairlEstringcOstringgR);
       instance.SetDelete(&delete_pairlEstringcOstringgR);
       instance.SetDeleteArray(&deleteArray_pairlEstringcOstringgR);
       instance.SetDestructor(&destruct_pairlEstringcOstringgR);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const pair< string, string > *) static
Definition at line 106 of file DataLibraryDict.cpp.
References delete_pairlEstringcOstringgR(), deleteArray_pairlEstringcOstringgR(), destruct_pairlEstringcOstringgR(), new_pairlEstringcOstringgR(), newArray_pairlEstringcOstringgR(), pairlEstringcOstringgR_Dictionary(), and pairlEstringcOstringgR_ShowMembers().
    {
       // Make sure the shadow class has the right sizeof
       R__ASSERT(sizeof(pair<string,string>) == sizeof(::ROOT::Shadow::pairlEstringcOstringgR));
       pair<string,string> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(pair<string,string>),0);
       static ::ROOT::TGenericClassInfo
          instance("pair<string,string>", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/utility", 17,
                   typeid(pair<string,string>), DefineBehavior(ptr, ptr),
                   &pairlEstringcOstringgR_ShowMembers, &pairlEstringcOstringgR_Dictionary, isa_proxy, 4,
                   sizeof(pair<string,string>) );
       instance.SetNew(&new_pairlEstringcOstringgR);
       instance.SetNewArray(&newArray_pairlEstringcOstringgR);
       instance.SetDelete(&delete_pairlEstringcOstringgR);
       instance.SetDeleteArray(&deleteArray_pairlEstringcOstringgR);
       instance.SetDestructor(&destruct_pairlEstringcOstringgR);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const pair< string, string > *) static
Definition at line 117 of file DataLibraryDict.cpp.
References delete_pairlEstringcOstringgR(), deleteArray_pairlEstringcOstringgR(), destruct_pairlEstringcOstringgR(), new_pairlEstringcOstringgR(), newArray_pairlEstringcOstringgR(), pairlEstringcOstringgR_Dictionary(), and pairlEstringcOstringgR_ShowMembers().
    {
       // Make sure the shadow class has the right sizeof
       R__ASSERT(sizeof(pair<string,string>) == sizeof(::ROOT::Shadow::pairlEstringcOstringgR));
       pair<string,string> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(pair<string,string>),0);
       static ::ROOT::TGenericClassInfo
          instance("pair<string,string>", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/utility", 17,
                   typeid(pair<string,string>), DefineBehavior(ptr, ptr),
                   &pairlEstringcOstringgR_ShowMembers, &pairlEstringcOstringgR_Dictionary, isa_proxy, 4,
                   sizeof(pair<string,string>) );
       instance.SetNew(&new_pairlEstringcOstringgR);
       instance.SetNewArray(&newArray_pairlEstringcOstringgR);
       instance.SetDelete(&delete_pairlEstringcOstringgR);
       instance.SetDeleteArray(&deleteArray_pairlEstringcOstringgR);
       instance.SetDestructor(&destruct_pairlEstringcOstringgR);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TGlobalData *) static
Definition at line 121 of file AlcapDict.cxx.
References delete_TGlobalData(), deleteArray_TGlobalData(), destruct_TGlobalData(), new_TGlobalData(), newArray_TGlobalData(), and streamer_TGlobalData().
    {
       ::TGlobalData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TGlobalData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TGlobalData", ::TGlobalData::Class_Version(), "./../src/common/TGlobalData.h", 13,
                   typeid(::TGlobalData), DefineBehavior(ptr, ptr),
                   &::TGlobalData::Dictionary, isa_proxy, 0,
                   sizeof(::TGlobalData) );
       instance.SetNew(&new_TGlobalData);
       instance.SetNewArray(&newArray_TGlobalData);
       instance.SetDelete(&delete_TGlobalData);
       instance.SetDeleteArray(&deleteArray_TGlobalData);
       instance.SetDestructor(&destruct_TGlobalData);
       instance.SetStreamerFunc(&streamer_TGlobalData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TGlobalData *) static
Definition at line 121 of file Dict.cxx.
References delete_TGlobalData(), deleteArray_TGlobalData(), destruct_TGlobalData(), new_TGlobalData(), newArray_TGlobalData(), and streamer_TGlobalData().
    {
       ::TGlobalData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TGlobalData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TGlobalData", ::TGlobalData::Class_Version(), "./../src/common/TGlobalData.h", 13,
                   typeid(::TGlobalData), DefineBehavior(ptr, ptr),
                   &::TGlobalData::Dictionary, isa_proxy, 0,
                   sizeof(::TGlobalData) );
       instance.SetNew(&new_TGlobalData);
       instance.SetNewArray(&newArray_TGlobalData);
       instance.SetDelete(&delete_TGlobalData);
       instance.SetDeleteArray(&deleteArray_TGlobalData);
       instance.SetDestructor(&destruct_TGlobalData);
       instance.SetStreamerFunc(&streamer_TGlobalData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TPulseIsland *) static
Definition at line 123 of file DataLibraryDict.cpp.
References delete_TPulseIsland(), deleteArray_TPulseIsland(), destruct_TPulseIsland(), new_TPulseIsland(), and newArray_TPulseIsland().
    {
       ::TPulseIsland *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TPulseIsland >(0);
       static ::ROOT::TGenericClassInfo
          instance("TPulseIsland", ::TPulseIsland::Class_Version(), "./../../src/common/TPulseIsland.h", 9,
                   typeid(::TPulseIsland), DefineBehavior(ptr, ptr),
                   &::TPulseIsland::Dictionary, isa_proxy, 4,
                   sizeof(::TPulseIsland) );
       instance.SetNew(&new_TPulseIsland);
       instance.SetNewArray(&newArray_TPulseIsland);
       instance.SetDelete(&delete_TPulseIsland);
       instance.SetDeleteArray(&deleteArray_TPulseIsland);
       instance.SetDestructor(&destruct_TPulseIsland);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::IDs::source *) static
Definition at line 127 of file RootanaDataClasses.cpp.
References delete_IDscLcLsource(), deleteArray_IDscLcLsource(), destruct_IDscLcLsource(), new_IDscLcLsource(), and newArray_IDscLcLsource().
    {
       ::IDs::source *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::IDs::source >(0);
       static ::ROOT::TGenericClassInfo
          instance("IDs::source", ::IDs::source::Class_Version(), "src/framework/IdSource.h", 16,
                   typeid(::IDs::source), DefineBehavior(ptr, ptr),
                   &::IDs::source::Dictionary, isa_proxy, 4,
                   sizeof(::IDs::source) );
       instance.SetNew(&new_IDscLcLsource);
       instance.SetNewArray(&newArray_IDscLcLsource);
       instance.SetDelete(&delete_IDscLcLsource);
       instance.SetDeleteArray(&deleteArray_IDscLcLsource);
       instance.SetDestructor(&destruct_IDscLcLsource);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::map< string, string, less< string >, allocator< pair< const string, string > > >::iterator *) static
Definition at line 148 of file DataLibraryDict.cpp.
References delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary(), new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), and newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
    {
       ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,string,less<string>,allocator<pair<const string,string> > >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 103,
                   typeid(::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator) );
       instance.SetNew(&new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetDelete(&delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::map< string, string, less< string >, allocator< pair< const string, string > > >::iterator *) static
Definition at line 148 of file DataLibraryDict.cpp.
References delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary(), new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), and newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
    {
       ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,string,less<string>,allocator<pair<const string,string> > >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 103,
                   typeid(::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator) );
       instance.SetNew(&new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetDelete(&delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TGlobalData *) static
Definition at line 156 of file DataLibraryDict.cpp.
References delete_TGlobalData(), deleteArray_TGlobalData(), destruct_TGlobalData(), new_TGlobalData(), and newArray_TGlobalData().
    {
       ::TGlobalData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TGlobalData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TGlobalData", ::TGlobalData::Class_Version(), "./../../src/common/TGlobalData.h", 14,
                   typeid(::TGlobalData), DefineBehavior(ptr, ptr),
                   &::TGlobalData::Dictionary, isa_proxy, 4,
                   sizeof(::TGlobalData) );
       instance.SetNew(&new_TGlobalData);
       instance.SetNewArray(&newArray_TGlobalData);
       instance.SetDelete(&delete_TGlobalData);
       instance.SetDeleteArray(&deleteArray_TGlobalData);
       instance.SetDestructor(&destruct_TGlobalData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::map< string, string, less< string >, allocator< pair< const string, string > > >::iterator *) static
Definition at line 159 of file DataLibraryDict.cpp.
References delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary(), new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), and newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
    {
       ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,string,less<string>,allocator<pair<const string,string> > >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 103,
                   typeid(::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator) );
       instance.SetNew(&new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetDelete(&delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TAnalysedPulse *) static
Definition at line 160 of file RootanaDataClasses.cpp.
References delete_TAnalysedPulse(), deleteArray_TAnalysedPulse(), destruct_TAnalysedPulse(), new_TAnalysedPulse(), and newArray_TAnalysedPulse().
    {
       ::TAnalysedPulse *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TAnalysedPulse >(0);
       static ::ROOT::TGenericClassInfo
          instance("TAnalysedPulse", ::TAnalysedPulse::Class_Version(), "src/TAP_generators/TAnalysedPulse.h", 13,
                   typeid(::TAnalysedPulse), DefineBehavior(ptr, ptr),
                   &::TAnalysedPulse::Dictionary, isa_proxy, 4,
                   sizeof(::TAnalysedPulse) );
       instance.SetNew(&new_TAnalysedPulse);
       instance.SetNewArray(&newArray_TAnalysedPulse);
       instance.SetDelete(&delete_TAnalysedPulse);
       instance.SetDeleteArray(&deleteArray_TAnalysedPulse);
       instance.SetDestructor(&destruct_TAnalysedPulse);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TPulseIsland *) static
Definition at line 187 of file DataLibraryDict.cpp.
References delete_TPulseIsland(), deleteArray_TPulseIsland(), destruct_TPulseIsland(), new_TPulseIsland(), and newArray_TPulseIsland().
    {
       ::TPulseIsland *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TPulseIsland >(0);
       static ::ROOT::TGenericClassInfo
          instance("TPulseIsland", ::TPulseIsland::Class_Version(), "./../../src/common/TPulseIsland.h", 11,
                   typeid(::TPulseIsland), DefineBehavior(ptr, ptr),
                   &::TPulseIsland::Dictionary, isa_proxy, 4,
                   sizeof(::TPulseIsland) );
       instance.SetNew(&new_TPulseIsland);
       instance.SetNewArray(&newArray_TPulseIsland);
       instance.SetDelete(&delete_TPulseIsland);
       instance.SetDeleteArray(&deleteArray_TPulseIsland);
       instance.SetDestructor(&destruct_TPulseIsland);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TPulseIsland *) static
Definition at line 187 of file DataLibraryDict.cpp.
References delete_TPulseIsland(), deleteArray_TPulseIsland(), destruct_TPulseIsland(), new_TPulseIsland(), and newArray_TPulseIsland().
    {
       ::TPulseIsland *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TPulseIsland >(0);
       static ::ROOT::TGenericClassInfo
          instance("TPulseIsland", ::TPulseIsland::Class_Version(), "./../../src/common/TPulseIsland.h", 11,
                   typeid(::TPulseIsland), DefineBehavior(ptr, ptr),
                   &::TPulseIsland::Dictionary, isa_proxy, 4,
                   sizeof(::TPulseIsland) );
       instance.SetNew(&new_TPulseIsland);
       instance.SetNewArray(&newArray_TPulseIsland);
       instance.SetDelete(&delete_TPulseIsland);
       instance.SetDeleteArray(&deleteArray_TPulseIsland);
       instance.SetDestructor(&destruct_TPulseIsland);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *) static
Definition at line 190 of file DataLibraryDict.cpp.
References delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), and vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary().
    {
       ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 218,
                   typeid(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator), DefineBehavior(ptr, ptr),
                   0, &vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator) );
       instance.SetNew(&new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDelete(&delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >::iterator *) static
Definition at line 194 of file RootanaDataClasses.cpp.
References delete_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), deleteArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), destruct_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), new_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), newArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), and vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_Dictionary().
    {
       ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 218,
                   typeid(::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator), DefineBehavior(ptr, ptr),
                   0, &vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator) );
       instance.SetNew(&new_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
       instance.SetDelete(&delete_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TPulseIsland *) static
Definition at line 198 of file DataLibraryDict.cpp.
References delete_TPulseIsland(), deleteArray_TPulseIsland(), destruct_TPulseIsland(), new_TPulseIsland(), and newArray_TPulseIsland().
    {
       ::TPulseIsland *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TPulseIsland >(0);
       static ::ROOT::TGenericClassInfo
          instance("TPulseIsland", ::TPulseIsland::Class_Version(), "./../../src/common/TPulseIsland.h", 11,
                   typeid(::TPulseIsland), DefineBehavior(ptr, ptr),
                   &::TPulseIsland::Dictionary, isa_proxy, 4,
                   sizeof(::TPulseIsland) );
       instance.SetNew(&new_TPulseIsland);
       instance.SetNewArray(&newArray_TPulseIsland);
       instance.SetDelete(&delete_TPulseIsland);
       instance.SetDeleteArray(&deleteArray_TPulseIsland);
       instance.SetDestructor(&destruct_TPulseIsland);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TGlobalData *) static
Definition at line 220 of file DataLibraryDict.cpp.
References delete_TGlobalData(), deleteArray_TGlobalData(), destruct_TGlobalData(), new_TGlobalData(), and newArray_TGlobalData().
    {
       ::TGlobalData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TGlobalData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TGlobalData", ::TGlobalData::Class_Version(), "./../../src/common/TGlobalData.h", 13,
                   typeid(::TGlobalData), DefineBehavior(ptr, ptr),
                   &::TGlobalData::Dictionary, isa_proxy, 4,
                   sizeof(::TGlobalData) );
       instance.SetNew(&new_TGlobalData);
       instance.SetNewArray(&newArray_TGlobalData);
       instance.SetDelete(&delete_TGlobalData);
       instance.SetDeleteArray(&deleteArray_TGlobalData);
       instance.SetDestructor(&destruct_TGlobalData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TGlobalData *) static
Definition at line 220 of file DataLibraryDict.cpp.
References delete_TGlobalData(), deleteArray_TGlobalData(), destruct_TGlobalData(), new_TGlobalData(), and newArray_TGlobalData().
    {
       ::TGlobalData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TGlobalData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TGlobalData", ::TGlobalData::Class_Version(), "./../../src/common/TGlobalData.h", 13,
                   typeid(::TGlobalData), DefineBehavior(ptr, ptr),
                   &::TGlobalData::Dictionary, isa_proxy, 4,
                   sizeof(::TGlobalData) );
       instance.SetNew(&new_TGlobalData);
       instance.SetNewArray(&newArray_TGlobalData);
       instance.SetDelete(&delete_TGlobalData);
       instance.SetDeleteArray(&deleteArray_TGlobalData);
       instance.SetDestructor(&destruct_TGlobalData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *) static
Definition at line 230 of file DataLibraryDict.cpp.
References delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary(), and pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers().
    {
       // Make sure the shadow class has the right sizeof
       R__ASSERT(sizeof(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >) == sizeof(::ROOT::Shadow::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR));
       pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >),0);
       static ::ROOT::TGenericClassInfo
          instance("pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/utility", 17,
                   typeid(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >), DefineBehavior(ptr, ptr),
                   &pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers, &pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >) );
       instance.SetNew(&new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetNewArray(&newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDelete(&delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDeleteArray(&deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDestructor(&destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TGlobalData *) static
Definition at line 231 of file DataLibraryDict.cpp.
References delete_TGlobalData(), deleteArray_TGlobalData(), destruct_TGlobalData(), new_TGlobalData(), and newArray_TGlobalData().
    {
       ::TGlobalData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TGlobalData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TGlobalData", ::TGlobalData::Class_Version(), "./../../src/common/TGlobalData.h", 13,
                   typeid(::TGlobalData), DefineBehavior(ptr, ptr),
                   &::TGlobalData::Dictionary, isa_proxy, 4,
                   sizeof(::TGlobalData) );
       instance.SetNew(&new_TGlobalData);
       instance.SetNewArray(&newArray_TGlobalData);
       instance.SetDelete(&delete_TGlobalData);
       instance.SetDeleteArray(&deleteArray_TGlobalData);
       instance.SetDestructor(&destruct_TGlobalData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const pair< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > *) static
Definition at line 234 of file RootanaDataClasses.cpp.
References delete_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), deleteArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), destruct_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), new_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), newArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_Dictionary(), and pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_ShowMembers().
    {
       // Make sure the shadow class has the right sizeof
       R__ASSERT(sizeof(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >) == sizeof(::ROOT::Shadow::pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
       pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >),0);
       static ::ROOT::TGenericClassInfo
          instance("pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/utility", 17,
                   typeid(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >), DefineBehavior(ptr, ptr),
                   &pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_ShowMembers, &pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >) );
       instance.SetNew(&new_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
       instance.SetNewArray(&newArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
       instance.SetDelete(&delete_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
       instance.SetDeleteArray(&deleteArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
       instance.SetDestructor(&destruct_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *) static
Definition at line 254 of file DataLibraryDict.cpp.
References delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), and vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary().
    {
       ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 218,
                   typeid(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator), DefineBehavior(ptr, ptr),
                   0, &vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator) );
       instance.SetNew(&new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDelete(&delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *) static
Definition at line 254 of file DataLibraryDict.cpp.
References delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), and vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary().
    {
       ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 218,
                   typeid(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator), DefineBehavior(ptr, ptr),
                   0, &vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator) );
       instance.SetNew(&new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDelete(&delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *) static
Definition at line 265 of file DataLibraryDict.cpp.
References delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), and vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary().
    {
       ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 218,
                   typeid(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator), DefineBehavior(ptr, ptr),
                   0, &vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator) );
       instance.SetNew(&new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDelete(&delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *) static
Definition at line 272 of file DataLibraryDict.cpp.
References delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary(), new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), and newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
    {
       ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 103,
                   typeid(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator) );
       instance.SetNew(&new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDelete(&delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::map< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >, less< string >, allocator< pair< const string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > > >::iterator *) static
Definition at line 276 of file RootanaDataClasses.cpp.
References delete_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), deleteArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), destruct_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary(), new_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), and newArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
    {
       ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 103,
                   typeid(::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator) );
       instance.SetNew(&new_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDelete(&delete_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *) static
Definition at line 294 of file DataLibraryDict.cpp.
References delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary(), and pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers().
    {
       // Make sure the shadow class has the right sizeof
       R__ASSERT(sizeof(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >) == sizeof(::ROOT::Shadow::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR));
       pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >),0);
       static ::ROOT::TGenericClassInfo
          instance("pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/utility", 17,
                   typeid(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >), DefineBehavior(ptr, ptr),
                   &pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers, &pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >) );
       instance.SetNew(&new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetNewArray(&newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDelete(&delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDeleteArray(&deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDestructor(&destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *) static
Definition at line 294 of file DataLibraryDict.cpp.
References delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary(), and pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers().
    {
       // Make sure the shadow class has the right sizeof
       R__ASSERT(sizeof(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >) == sizeof(::ROOT::Shadow::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR));
       pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >),0);
       static ::ROOT::TGenericClassInfo
          instance("pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/utility", 17,
                   typeid(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >), DefineBehavior(ptr, ptr),
                   &pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers, &pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >) );
       instance.SetNew(&new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetNewArray(&newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDelete(&delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDeleteArray(&deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDestructor(&destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *) static
Definition at line 305 of file DataLibraryDict.cpp.
References delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary(), and pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers().
    {
       // Make sure the shadow class has the right sizeof
       R__ASSERT(sizeof(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >) == sizeof(::ROOT::Shadow::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR));
       pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >),0);
       static ::ROOT::TGenericClassInfo
          instance("pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/utility", 17,
                   typeid(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >), DefineBehavior(ptr, ptr),
                   &pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers, &pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >) );
       instance.SetNew(&new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetNewArray(&newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDelete(&delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDeleteArray(&deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       instance.SetDestructor(&destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TDetectorPulse *) static
Definition at line 315 of file RootanaDataClasses.cpp.
References delete_TDetectorPulse(), deleteArray_TDetectorPulse(), destruct_TDetectorPulse(), new_TDetectorPulse(), and newArray_TDetectorPulse().
    {
       ::TDetectorPulse *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TDetectorPulse >(0);
       static ::ROOT::TGenericClassInfo
          instance("TDetectorPulse", ::TDetectorPulse::Class_Version(), "src/TDP_generators/TDetectorPulse.h", 15,
                   typeid(::TDetectorPulse), DefineBehavior(ptr, ptr),
                   &::TDetectorPulse::Dictionary, isa_proxy, 4,
                   sizeof(::TDetectorPulse) );
       instance.SetNew(&new_TDetectorPulse);
       instance.SetNewArray(&newArray_TDetectorPulse);
       instance.SetDelete(&delete_TDetectorPulse);
       instance.SetDeleteArray(&deleteArray_TDetectorPulse);
       instance.SetDestructor(&destruct_TDetectorPulse);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *) static
Definition at line 336 of file DataLibraryDict.cpp.
References delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary(), new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), and newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
    {
       ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 103,
                   typeid(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator) );
       instance.SetNew(&new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDelete(&delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *) static
Definition at line 336 of file DataLibraryDict.cpp.
References delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary(), new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), and newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
    {
       ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 103,
                   typeid(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator) );
       instance.SetNew(&new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDelete(&delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *) static
Definition at line 347 of file DataLibraryDict.cpp.
References delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary(), new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), and newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
    {
       ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 103,
                   typeid(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator) );
       instance.SetNew(&new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDelete(&delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TAnalysedPulseMapWrapper *) static
Definition at line 348 of file RootanaDataClasses.cpp.
References delete_TAnalysedPulseMapWrapper(), deleteArray_TAnalysedPulseMapWrapper(), destruct_TAnalysedPulseMapWrapper(), new_TAnalysedPulseMapWrapper(), and newArray_TAnalysedPulseMapWrapper().
    {
       ::TAnalysedPulseMapWrapper *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TAnalysedPulseMapWrapper >(0);
       static ::ROOT::TGenericClassInfo
          instance("TAnalysedPulseMapWrapper", ::TAnalysedPulseMapWrapper::Class_Version(), "src/TAP_generators/TAnalysedPulseMapWrapper.h", 17,
                   typeid(::TAnalysedPulseMapWrapper), DefineBehavior(ptr, ptr),
                   &::TAnalysedPulseMapWrapper::Dictionary, isa_proxy, 4,
                   sizeof(::TAnalysedPulseMapWrapper) );
       instance.SetNew(&new_TAnalysedPulseMapWrapper);
       instance.SetNewArray(&newArray_TAnalysedPulseMapWrapper);
       instance.SetDelete(&delete_TAnalysedPulseMapWrapper);
       instance.SetDeleteArray(&deleteArray_TAnalysedPulseMapWrapper);
       instance.SetDestructor(&destruct_TAnalysedPulseMapWrapper);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TVacuumData *) static
Definition at line 375 of file DataLibraryDict.cpp.
References delete_TVacuumData(), deleteArray_TVacuumData(), destruct_TVacuumData(), new_TVacuumData(), and newArray_TVacuumData().
    {
       ::TVacuumData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TVacuumData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TVacuumData", ::TVacuumData::Class_Version(), "./../../src/common/TVacuumData.h", 10,
                   typeid(::TVacuumData), DefineBehavior(ptr, ptr),
                   &::TVacuumData::Dictionary, isa_proxy, 4,
                   sizeof(::TVacuumData) );
       instance.SetNew(&new_TVacuumData);
       instance.SetNewArray(&newArray_TVacuumData);
       instance.SetDelete(&delete_TVacuumData);
       instance.SetDeleteArray(&deleteArray_TVacuumData);
       instance.SetDestructor(&destruct_TVacuumData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TVacuumData *) static
Definition at line 375 of file DataLibraryDict.cpp.
References delete_TVacuumData(), deleteArray_TVacuumData(), destruct_TVacuumData(), new_TVacuumData(), and newArray_TVacuumData().
    {
       ::TVacuumData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TVacuumData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TVacuumData", ::TVacuumData::Class_Version(), "./../../src/common/TVacuumData.h", 10,
                   typeid(::TVacuumData), DefineBehavior(ptr, ptr),
                   &::TVacuumData::Dictionary, isa_proxy, 4,
                   sizeof(::TVacuumData) );
       instance.SetNew(&new_TVacuumData);
       instance.SetNewArray(&newArray_TVacuumData);
       instance.SetDelete(&delete_TVacuumData);
       instance.SetDeleteArray(&deleteArray_TVacuumData);
       instance.SetDestructor(&destruct_TVacuumData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TAnalysedPulse *) static
Definition at line 386 of file DataLibraryDict.cpp.
References delete_TAnalysedPulse(), deleteArray_TAnalysedPulse(), destruct_TAnalysedPulse(), new_TAnalysedPulse(), and newArray_TAnalysedPulse().
    {
       ::TAnalysedPulse *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TAnalysedPulse >(0);
       static ::ROOT::TGenericClassInfo
          instance("TAnalysedPulse", ::TAnalysedPulse::Class_Version(), "./../../src/common/TAnalysedPulse.h", 13,
                   typeid(::TAnalysedPulse), DefineBehavior(ptr, ptr),
                   &::TAnalysedPulse::Dictionary, isa_proxy, 4,
                   sizeof(::TAnalysedPulse) );
       instance.SetNew(&new_TAnalysedPulse);
       instance.SetNewArray(&newArray_TAnalysedPulse);
       instance.SetDelete(&delete_TAnalysedPulse);
       instance.SetDeleteArray(&deleteArray_TAnalysedPulse);
       instance.SetDestructor(&destruct_TAnalysedPulse);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TDetectorPulse *) static
Definition at line 419 of file DataLibraryDict.cpp.
References delete_TDetectorPulse(), deleteArray_TDetectorPulse(), destruct_TDetectorPulse(), new_TDetectorPulse(), and newArray_TDetectorPulse().
    {
       ::TDetectorPulse *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TDetectorPulse >(0);
       static ::ROOT::TGenericClassInfo
          instance("TDetectorPulse", ::TDetectorPulse::Class_Version(), "./../../src/common/TDetectorPulse.h", 15,
                   typeid(::TDetectorPulse), DefineBehavior(ptr, ptr),
                   &::TDetectorPulse::Dictionary, isa_proxy, 4,
                   sizeof(::TDetectorPulse) );
       instance.SetNew(&new_TDetectorPulse);
       instance.SetNewArray(&newArray_TDetectorPulse);
       instance.SetDelete(&delete_TDetectorPulse);
       instance.SetDeleteArray(&deleteArray_TDetectorPulse);
       instance.SetDestructor(&destruct_TDetectorPulse);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::TVacuumData *) static
Definition at line 452 of file DataLibraryDict.cpp.
References delete_TVacuumData(), deleteArray_TVacuumData(), destruct_TVacuumData(), new_TVacuumData(), and newArray_TVacuumData().
    {
       ::TVacuumData *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TVacuumData >(0);
       static ::ROOT::TGenericClassInfo
          instance("TVacuumData", ::TVacuumData::Class_Version(), "./../../src/common/TVacuumData.h", 10,
                   typeid(::TVacuumData), DefineBehavior(ptr, ptr),
                   &::TVacuumData::Dictionary, isa_proxy, 4,
                   sizeof(::TVacuumData) );
       instance.SetNew(&new_TVacuumData);
       instance.SetNewArray(&newArray_TVacuumData);
       instance.SetDelete(&delete_TVacuumData);
       instance.SetDeleteArray(&deleteArray_TVacuumData);
       instance.SetDestructor(&destruct_TVacuumData);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >::iterator *) static
Definition at line 486 of file DataLibraryDict.cpp.
References delete_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), deleteArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), destruct_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), new_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), newArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), and vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_Dictionary().
    {
       ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 218,
                   typeid(::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator), DefineBehavior(ptr, ptr),
                   0, &vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator) );
       instance.SetNew(&new_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
       instance.SetDelete(&delete_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const pair< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > *) static
Definition at line 526 of file DataLibraryDict.cpp.
References delete_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), deleteArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), destruct_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), new_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), newArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_Dictionary(), and pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_ShowMembers().
    {
       // Make sure the shadow class has the right sizeof
       R__ASSERT(sizeof(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >) == sizeof(::ROOT::Shadow::pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
       pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >),0);
       static ::ROOT::TGenericClassInfo
          instance("pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/utility", 17,
                   typeid(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >), DefineBehavior(ptr, ptr),
                   &pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_ShowMembers, &pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >) );
       instance.SetNew(&new_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
       instance.SetNewArray(&newArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
       instance.SetDelete(&delete_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
       instance.SetDeleteArray(&deleteArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
       instance.SetDestructor(&destruct_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const ::map< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >, less< string >, allocator< pair< const string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > > >::iterator *) static
Definition at line 568 of file DataLibraryDict.cpp.
References delete_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), deleteArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), destruct_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary(), new_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), and newArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
    {
       ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator", "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 103,
                   typeid(::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary, isa_proxy, 0,
                   sizeof(::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator) );
       instance.SetNew(&new_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDelete(&delete_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *) static
Definition at line 593 of file DataLibraryDict.cpp.
References delete_maplEstringcOvectorlETPulseIslandmUgRsPgR(), deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR(), destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR(), maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary(), new_maplEstringcOvectorlETPulseIslandmUgRsPgR(), and newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR().
    {
       map<string,vector<TPulseIsland*> > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,vector<TPulseIsland*> >),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TPulseIsland*> >", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,vector<TPulseIsland*> >), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(map<string,vector<TPulseIsland*> >) );
       instance.SetNew(&new_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDelete(&delete_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,vector<TPulseIsland*> > >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< TPulseIsland * > *) static
Definition at line 651 of file DataLibraryDict.cpp.
References delete_vectorlETPulseIslandmUgR(), deleteArray_vectorlETPulseIslandmUgR(), destruct_vectorlETPulseIslandmUgR(), new_vectorlETPulseIslandmUgR(), newArray_vectorlETPulseIslandmUgR(), and vectorlETPulseIslandmUgR_Dictionary().
    {
       vector<TPulseIsland*> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TPulseIsland*>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TPulseIsland*>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 49,
                   typeid(vector<TPulseIsland*>), DefineBehavior(ptr, ptr),
                   0, &vectorlETPulseIslandmUgR_Dictionary, isa_proxy, 4,
                   sizeof(vector<TPulseIsland*>) );
       instance.SetNew(&new_vectorlETPulseIslandmUgR);
       instance.SetNewArray(&newArray_vectorlETPulseIslandmUgR);
       instance.SetDelete(&delete_vectorlETPulseIslandmUgR);
       instance.SetDeleteArray(&deleteArray_vectorlETPulseIslandmUgR);
       instance.SetDestructor(&destruct_vectorlETPulseIslandmUgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TPulseIsland*> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< int > *) static
Definition at line 709 of file DataLibraryDict.cpp.
References delete_vectorlEintgR(), deleteArray_vectorlEintgR(), destruct_vectorlEintgR(), new_vectorlEintgR(), newArray_vectorlEintgR(), and vectorlEintgR_Dictionary().
    {
       vector<int> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<int>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 49,
                   typeid(vector<int>), DefineBehavior(ptr, ptr),
                   0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                   sizeof(vector<int>) );
       instance.SetNew(&new_vectorlEintgR);
       instance.SetNewArray(&newArray_vectorlEintgR);
       instance.SetDelete(&delete_vectorlEintgR);
       instance.SetDeleteArray(&deleteArray_vectorlEintgR);
       instance.SetDestructor(&destruct_vectorlEintgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, double > *) static
Definition at line 744 of file AlcapDict.cxx.
References delete_maplEstringcOdoublegR(), deleteArray_maplEstringcOdoublegR(), destruct_maplEstringcOdoublegR(), maplEstringcOdoublegR_Dictionary(), new_maplEstringcOdoublegR(), and newArray_maplEstringcOdoublegR().
    {
       map<string,double> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,double>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,double>", -2, "map.dll", 0,
                   typeid(map<string,double>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOdoublegR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,double>) );
       instance.SetNew(&new_maplEstringcOdoublegR);
       instance.SetNewArray(&newArray_maplEstringcOdoublegR);
       instance.SetDelete(&delete_maplEstringcOdoublegR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOdoublegR);
       instance.SetDestructor(&destruct_maplEstringcOdoublegR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,double> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, double > *) static
Definition at line 744 of file Dict.cxx.
References delete_maplEstringcOdoublegR(), deleteArray_maplEstringcOdoublegR(), destruct_maplEstringcOdoublegR(), maplEstringcOdoublegR_Dictionary(), new_maplEstringcOdoublegR(), and newArray_maplEstringcOdoublegR().
    {
       map<string,double> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,double>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,double>", -2, "map.dll", 0,
                   typeid(map<string,double>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOdoublegR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,double>) );
       instance.SetNew(&new_maplEstringcOdoublegR);
       instance.SetNewArray(&newArray_maplEstringcOdoublegR);
       instance.SetDelete(&delete_maplEstringcOdoublegR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOdoublegR);
       instance.SetDestructor(&destruct_maplEstringcOdoublegR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,double> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, int > *) static
Definition at line 802 of file Dict.cxx.
References delete_maplEstringcOintgR(), deleteArray_maplEstringcOintgR(), destruct_maplEstringcOintgR(), maplEstringcOintgR_Dictionary(), new_maplEstringcOintgR(), and newArray_maplEstringcOintgR().
    {
       map<string,int> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,int>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,int>", -2, "map.dll", 0,
                   typeid(map<string,int>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOintgR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,int>) );
       instance.SetNew(&new_maplEstringcOintgR);
       instance.SetNewArray(&newArray_maplEstringcOintgR);
       instance.SetDelete(&delete_maplEstringcOintgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOintgR);
       instance.SetDestructor(&destruct_maplEstringcOintgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,int> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, int > *) static
Definition at line 802 of file AlcapDict.cxx.
References delete_maplEstringcOintgR(), deleteArray_maplEstringcOintgR(), destruct_maplEstringcOintgR(), maplEstringcOintgR_Dictionary(), new_maplEstringcOintgR(), and newArray_maplEstringcOintgR().
    {
       map<string,int> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,int>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,int>", -2, "map.dll", 0,
                   typeid(map<string,int>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOintgR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,int>) );
       instance.SetNew(&new_maplEstringcOintgR);
       instance.SetNewArray(&newArray_maplEstringcOintgR);
       instance.SetDelete(&delete_maplEstringcOintgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOintgR);
       instance.SetDestructor(&destruct_maplEstringcOintgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,int> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, string > *) static
Definition at line 860 of file AlcapDict.cxx.
References delete_maplEstringcOstringgR(), deleteArray_maplEstringcOstringgR(), destruct_maplEstringcOstringgR(), maplEstringcOstringgR_Dictionary(), new_maplEstringcOstringgR(), and newArray_maplEstringcOstringgR().
    {
       map<string,string> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,string>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,string>", -2, "prec_stl/map", 63,
                   typeid(map<string,string>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOstringgR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,string>) );
       instance.SetNew(&new_maplEstringcOstringgR);
       instance.SetNewArray(&newArray_maplEstringcOstringgR);
       instance.SetDelete(&delete_maplEstringcOstringgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOstringgR);
       instance.SetDestructor(&destruct_maplEstringcOstringgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,string> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, string > *) static
Definition at line 860 of file Dict.cxx.
References delete_maplEstringcOstringgR(), deleteArray_maplEstringcOstringgR(), destruct_maplEstringcOstringgR(), maplEstringcOstringgR_Dictionary(), new_maplEstringcOstringgR(), and newArray_maplEstringcOstringgR().
    {
       map<string,string> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,string>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,string>", -2, "prec_stl/map", 63,
                   typeid(map<string,string>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOstringgR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,string>) );
       instance.SetNew(&new_maplEstringcOstringgR);
       instance.SetNewArray(&newArray_maplEstringcOstringgR);
       instance.SetDelete(&delete_maplEstringcOstringgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOstringgR);
       instance.SetDestructor(&destruct_maplEstringcOstringgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,string> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, bool > *) static
Definition at line 887 of file DataLibraryDict.cpp.
References delete_maplEstringcOboolgR(), deleteArray_maplEstringcOboolgR(), destruct_maplEstringcOboolgR(), maplEstringcOboolgR_Dictionary(), new_maplEstringcOboolgR(), and newArray_maplEstringcOboolgR().
    {
       map<string,bool> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,bool>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,bool>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,bool>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOboolgR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,bool>) );
       instance.SetNew(&new_maplEstringcOboolgR);
       instance.SetNewArray(&newArray_maplEstringcOboolgR);
       instance.SetDelete(&delete_maplEstringcOboolgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOboolgR);
       instance.SetDestructor(&destruct_maplEstringcOboolgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,bool> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, bool > *) static
Definition at line 887 of file DataLibraryDict.cpp.
References delete_maplEstringcOboolgR(), deleteArray_maplEstringcOboolgR(), destruct_maplEstringcOboolgR(), maplEstringcOboolgR_Dictionary(), new_maplEstringcOboolgR(), and newArray_maplEstringcOboolgR().
    {
       map<string,bool> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,bool>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,bool>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,bool>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOboolgR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,bool>) );
       instance.SetNew(&new_maplEstringcOboolgR);
       instance.SetNewArray(&newArray_maplEstringcOboolgR);
       instance.SetDelete(&delete_maplEstringcOboolgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOboolgR);
       instance.SetDestructor(&destruct_maplEstringcOboolgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,bool> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *) static
Definition at line 918 of file AlcapDict.cxx.
References delete_maplEstringcOvectorlETPulseIslandmUgRsPgR(), deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR(), destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR(), maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary(), new_maplEstringcOvectorlETPulseIslandmUgRsPgR(), and newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR().
    {
       map<string,vector<TPulseIsland*> > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,vector<TPulseIsland*> >),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TPulseIsland*> >", -2, "prec_stl/map", 63,
                   typeid(map<string,vector<TPulseIsland*> >), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,vector<TPulseIsland*> >) );
       instance.SetNew(&new_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDelete(&delete_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,vector<TPulseIsland*> > >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *) static
Definition at line 918 of file Dict.cxx.
References delete_maplEstringcOvectorlETPulseIslandmUgRsPgR(), deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR(), destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR(), maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary(), new_maplEstringcOvectorlETPulseIslandmUgRsPgR(), and newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR().
    {
       map<string,vector<TPulseIsland*> > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,vector<TPulseIsland*> >),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TPulseIsland*> >", -2, "prec_stl/map", 63,
                   typeid(map<string,vector<TPulseIsland*> >), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,vector<TPulseIsland*> >) );
       instance.SetNew(&new_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDelete(&delete_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,vector<TPulseIsland*> > >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, double > *) static
Definition at line 945 of file DataLibraryDict.cpp.
References delete_maplEstringcOdoublegR(), deleteArray_maplEstringcOdoublegR(), destruct_maplEstringcOdoublegR(), maplEstringcOdoublegR_Dictionary(), new_maplEstringcOdoublegR(), and newArray_maplEstringcOdoublegR().
    {
       map<string,double> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,double>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,double>", -2, "map.dll", 0,
                   typeid(map<string,double>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOdoublegR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,double>) );
       instance.SetNew(&new_maplEstringcOdoublegR);
       instance.SetNewArray(&newArray_maplEstringcOdoublegR);
       instance.SetDelete(&delete_maplEstringcOdoublegR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOdoublegR);
       instance.SetDestructor(&destruct_maplEstringcOdoublegR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,double> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, double > *) static
Definition at line 945 of file DataLibraryDict.cpp.
References delete_maplEstringcOdoublegR(), deleteArray_maplEstringcOdoublegR(), destruct_maplEstringcOdoublegR(), maplEstringcOdoublegR_Dictionary(), new_maplEstringcOdoublegR(), and newArray_maplEstringcOdoublegR().
    {
       map<string,double> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,double>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,double>", -2, "map.dll", 0,
                   typeid(map<string,double>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOdoublegR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,double>) );
       instance.SetNew(&new_maplEstringcOdoublegR);
       instance.SetNewArray(&newArray_maplEstringcOdoublegR);
       instance.SetDelete(&delete_maplEstringcOdoublegR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOdoublegR);
       instance.SetDestructor(&destruct_maplEstringcOdoublegR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,double> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< IDs::Detector_t, string > *) static
Definition at line 963 of file RootanaDataClasses.cpp.
References delete_maplEIDscLcLDetector_tcOstringgR(), deleteArray_maplEIDscLcLDetector_tcOstringgR(), destruct_maplEIDscLcLDetector_tcOstringgR(), maplEIDscLcLDetector_tcOstringgR_Dictionary(), new_maplEIDscLcLDetector_tcOstringgR(), and newArray_maplEIDscLcLDetector_tcOstringgR().
    {
       map<IDs::Detector_t,string> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<IDs::Detector_t,string>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<IDs::Detector_t,string>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<IDs::Detector_t,string>), DefineBehavior(ptr, ptr),
                   0, &maplEIDscLcLDetector_tcOstringgR_Dictionary, isa_proxy, 4,
                   sizeof(map<IDs::Detector_t,string>) );
       instance.SetNew(&new_maplEIDscLcLDetector_tcOstringgR);
       instance.SetNewArray(&newArray_maplEIDscLcLDetector_tcOstringgR);
       instance.SetDelete(&delete_maplEIDscLcLDetector_tcOstringgR);
       instance.SetDeleteArray(&deleteArray_maplEIDscLcLDetector_tcOstringgR);
       instance.SetDestructor(&destruct_maplEIDscLcLDetector_tcOstringgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<IDs::Detector_t,string> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< TPulseIsland * > *) static
Definition at line 976 of file AlcapDict.cxx.
References delete_vectorlETPulseIslandmUgR(), deleteArray_vectorlETPulseIslandmUgR(), destruct_vectorlETPulseIslandmUgR(), new_vectorlETPulseIslandmUgR(), newArray_vectorlETPulseIslandmUgR(), and vectorlETPulseIslandmUgR_Dictionary().
    {
       vector<TPulseIsland*> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TPulseIsland*>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TPulseIsland*>", -2, "prec_stl/vector", 49,
                   typeid(vector<TPulseIsland*>), DefineBehavior(ptr, ptr),
                   0, &vectorlETPulseIslandmUgR_Dictionary, isa_proxy, 0,
                   sizeof(vector<TPulseIsland*>) );
       instance.SetNew(&new_vectorlETPulseIslandmUgR);
       instance.SetNewArray(&newArray_vectorlETPulseIslandmUgR);
       instance.SetDelete(&delete_vectorlETPulseIslandmUgR);
       instance.SetDeleteArray(&deleteArray_vectorlETPulseIslandmUgR);
       instance.SetDestructor(&destruct_vectorlETPulseIslandmUgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TPulseIsland*> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< TPulseIsland * > *) static
Definition at line 976 of file Dict.cxx.
References delete_vectorlETPulseIslandmUgR(), deleteArray_vectorlETPulseIslandmUgR(), destruct_vectorlETPulseIslandmUgR(), new_vectorlETPulseIslandmUgR(), newArray_vectorlETPulseIslandmUgR(), and vectorlETPulseIslandmUgR_Dictionary().
    {
       vector<TPulseIsland*> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TPulseIsland*>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TPulseIsland*>", -2, "prec_stl/vector", 49,
                   typeid(vector<TPulseIsland*>), DefineBehavior(ptr, ptr),
                   0, &vectorlETPulseIslandmUgR_Dictionary, isa_proxy, 0,
                   sizeof(vector<TPulseIsland*>) );
       instance.SetNew(&new_vectorlETPulseIslandmUgR);
       instance.SetNewArray(&newArray_vectorlETPulseIslandmUgR);
       instance.SetDelete(&delete_vectorlETPulseIslandmUgR);
       instance.SetDeleteArray(&deleteArray_vectorlETPulseIslandmUgR);
       instance.SetDestructor(&destruct_vectorlETPulseIslandmUgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TPulseIsland*> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, int > *) static
Definition at line 1003 of file DataLibraryDict.cpp.
References delete_maplEstringcOintgR(), deleteArray_maplEstringcOintgR(), destruct_maplEstringcOintgR(), maplEstringcOintgR_Dictionary(), new_maplEstringcOintgR(), and newArray_maplEstringcOintgR().
    {
       map<string,int> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,int>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,int>", -2, "map.dll", 0,
                   typeid(map<string,int>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOintgR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,int>) );
       instance.SetNew(&new_maplEstringcOintgR);
       instance.SetNewArray(&newArray_maplEstringcOintgR);
       instance.SetDelete(&delete_maplEstringcOintgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOintgR);
       instance.SetDestructor(&destruct_maplEstringcOintgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,int> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, int > *) static
Definition at line 1003 of file DataLibraryDict.cpp.
References delete_maplEstringcOintgR(), deleteArray_maplEstringcOintgR(), destruct_maplEstringcOintgR(), maplEstringcOintgR_Dictionary(), new_maplEstringcOintgR(), and newArray_maplEstringcOintgR().
    {
       map<string,int> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,int>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,int>", -2, "map.dll", 0,
                   typeid(map<string,int>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOintgR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,int>) );
       instance.SetNew(&new_maplEstringcOintgR);
       instance.SetNewArray(&newArray_maplEstringcOintgR);
       instance.SetDelete(&delete_maplEstringcOintgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOintgR);
       instance.SetDestructor(&destruct_maplEstringcOintgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,int> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, IDs::Detector_t > *) static
Definition at line 1021 of file RootanaDataClasses.cpp.
References delete_maplEstringcOIDscLcLDetector_tgR(), deleteArray_maplEstringcOIDscLcLDetector_tgR(), destruct_maplEstringcOIDscLcLDetector_tgR(), maplEstringcOIDscLcLDetector_tgR_Dictionary(), new_maplEstringcOIDscLcLDetector_tgR(), and newArray_maplEstringcOIDscLcLDetector_tgR().
    {
       map<string,IDs::Detector_t> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,IDs::Detector_t>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,IDs::Detector_t>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,IDs::Detector_t>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOIDscLcLDetector_tgR_Dictionary, isa_proxy, 4,
                   sizeof(map<string,IDs::Detector_t>) );
       instance.SetNew(&new_maplEstringcOIDscLcLDetector_tgR);
       instance.SetNewArray(&newArray_maplEstringcOIDscLcLDetector_tgR);
       instance.SetDelete(&delete_maplEstringcOIDscLcLDetector_tgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOIDscLcLDetector_tgR);
       instance.SetDestructor(&destruct_maplEstringcOIDscLcLDetector_tgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,IDs::Detector_t> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< int > *) static
Definition at line 1034 of file Dict.cxx.
References delete_vectorlEintgR(), deleteArray_vectorlEintgR(), destruct_vectorlEintgR(), new_vectorlEintgR(), newArray_vectorlEintgR(), and vectorlEintgR_Dictionary().
    {
       vector<int> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<int>", -2, "prec_stl/vector", 49,
                   typeid(vector<int>), DefineBehavior(ptr, ptr),
                   0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                   sizeof(vector<int>) );
       instance.SetNew(&new_vectorlEintgR);
       instance.SetNewArray(&newArray_vectorlEintgR);
       instance.SetDelete(&delete_vectorlEintgR);
       instance.SetDeleteArray(&deleteArray_vectorlEintgR);
       instance.SetDestructor(&destruct_vectorlEintgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< int > *) static
Definition at line 1034 of file AlcapDict.cxx.
References delete_vectorlEintgR(), deleteArray_vectorlEintgR(), destruct_vectorlEintgR(), new_vectorlEintgR(), newArray_vectorlEintgR(), and vectorlEintgR_Dictionary().
    {
       vector<int> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<int>", -2, "prec_stl/vector", 49,
                   typeid(vector<int>), DefineBehavior(ptr, ptr),
                   0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                   sizeof(vector<int>) );
       instance.SetNew(&new_vectorlEintgR);
       instance.SetNewArray(&newArray_vectorlEintgR);
       instance.SetDelete(&delete_vectorlEintgR);
       instance.SetDeleteArray(&deleteArray_vectorlEintgR);
       instance.SetDestructor(&destruct_vectorlEintgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, string > *) static
Definition at line 1061 of file DataLibraryDict.cpp.
References delete_maplEstringcOstringgR(), deleteArray_maplEstringcOstringgR(), destruct_maplEstringcOstringgR(), maplEstringcOstringgR_Dictionary(), new_maplEstringcOstringgR(), and newArray_maplEstringcOstringgR().
    {
       map<string,string> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,string>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,string>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,string>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOstringgR_Dictionary, isa_proxy, 4,
                   sizeof(map<string,string>) );
       instance.SetNew(&new_maplEstringcOstringgR);
       instance.SetNewArray(&newArray_maplEstringcOstringgR);
       instance.SetDelete(&delete_maplEstringcOstringgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOstringgR);
       instance.SetDestructor(&destruct_maplEstringcOstringgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,string> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, string > *) static
Definition at line 1061 of file DataLibraryDict.cpp.
References delete_maplEstringcOstringgR(), deleteArray_maplEstringcOstringgR(), destruct_maplEstringcOstringgR(), maplEstringcOstringgR_Dictionary(), new_maplEstringcOstringgR(), and newArray_maplEstringcOstringgR().
    {
       map<string,string> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,string>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,string>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,string>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOstringgR_Dictionary, isa_proxy, 4,
                   sizeof(map<string,string>) );
       instance.SetNew(&new_maplEstringcOstringgR);
       instance.SetNewArray(&newArray_maplEstringcOstringgR);
       instance.SetDelete(&delete_maplEstringcOstringgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOstringgR);
       instance.SetDestructor(&destruct_maplEstringcOstringgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,string> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, vector< TAnalysedPulse * > > *) static
Definition at line 1079 of file RootanaDataClasses.cpp.
References delete_maplEstringcOvectorlETAnalysedPulsemUgRsPgR(), deleteArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR(), destruct_maplEstringcOvectorlETAnalysedPulsemUgRsPgR(), maplEstringcOvectorlETAnalysedPulsemUgRsPgR_Dictionary(), new_maplEstringcOvectorlETAnalysedPulsemUgRsPgR(), and newArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR().
    {
       map<string,vector<TAnalysedPulse*> > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,vector<TAnalysedPulse*> >),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TAnalysedPulse*> >", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,vector<TAnalysedPulse*> >), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETAnalysedPulsemUgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(map<string,vector<TAnalysedPulse*> >) );
       instance.SetNew(&new_maplEstringcOvectorlETAnalysedPulsemUgRsPgR);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR);
       instance.SetDelete(&delete_maplEstringcOvectorlETAnalysedPulsemUgRsPgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETAnalysedPulsemUgRsPgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,vector<TAnalysedPulse*> > >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *) static
Definition at line 1119 of file DataLibraryDict.cpp.
References delete_maplEstringcOvectorlETPulseIslandmUgRsPgR(), deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR(), destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR(), maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary(), new_maplEstringcOvectorlETPulseIslandmUgRsPgR(), and newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR().
    {
       map<string,vector<TPulseIsland*> > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,vector<TPulseIsland*> >),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TPulseIsland*> >", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,vector<TPulseIsland*> >), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(map<string,vector<TPulseIsland*> >) );
       instance.SetNew(&new_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDelete(&delete_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,vector<TPulseIsland*> > >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *) static
Definition at line 1119 of file DataLibraryDict.cpp.
References delete_maplEstringcOvectorlETPulseIslandmUgRsPgR(), deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR(), destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR(), maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary(), new_maplEstringcOvectorlETPulseIslandmUgRsPgR(), and newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR().
    {
       map<string,vector<TPulseIsland*> > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,vector<TPulseIsland*> >),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TPulseIsland*> >", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,vector<TPulseIsland*> >), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(map<string,vector<TPulseIsland*> >) );
       instance.SetNew(&new_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDelete(&delete_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,vector<TPulseIsland*> > >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< TAnalysedPulse * > *) static
Definition at line 1137 of file RootanaDataClasses.cpp.
References delete_vectorlETAnalysedPulsemUgR(), deleteArray_vectorlETAnalysedPulsemUgR(), destruct_vectorlETAnalysedPulsemUgR(), new_vectorlETAnalysedPulsemUgR(), newArray_vectorlETAnalysedPulsemUgR(), and vectorlETAnalysedPulsemUgR_Dictionary().
    {
       vector<TAnalysedPulse*> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TAnalysedPulse*>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TAnalysedPulse*>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 49,
                   typeid(vector<TAnalysedPulse*>), DefineBehavior(ptr, ptr),
                   0, &vectorlETAnalysedPulsemUgR_Dictionary, isa_proxy, 4,
                   sizeof(vector<TAnalysedPulse*>) );
       instance.SetNew(&new_vectorlETAnalysedPulsemUgR);
       instance.SetNewArray(&newArray_vectorlETAnalysedPulsemUgR);
       instance.SetDelete(&delete_vectorlETAnalysedPulsemUgR);
       instance.SetDeleteArray(&deleteArray_vectorlETAnalysedPulsemUgR);
       instance.SetDestructor(&destruct_vectorlETAnalysedPulsemUgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TAnalysedPulse*> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< TPulseIsland * > *) static
Definition at line 1177 of file DataLibraryDict.cpp.
References delete_vectorlETPulseIslandmUgR(), deleteArray_vectorlETPulseIslandmUgR(), destruct_vectorlETPulseIslandmUgR(), new_vectorlETPulseIslandmUgR(), newArray_vectorlETPulseIslandmUgR(), and vectorlETPulseIslandmUgR_Dictionary().
    {
       vector<TPulseIsland*> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TPulseIsland*>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TPulseIsland*>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 49,
                   typeid(vector<TPulseIsland*>), DefineBehavior(ptr, ptr),
                   0, &vectorlETPulseIslandmUgR_Dictionary, isa_proxy, 4,
                   sizeof(vector<TPulseIsland*>) );
       instance.SetNew(&new_vectorlETPulseIslandmUgR);
       instance.SetNewArray(&newArray_vectorlETPulseIslandmUgR);
       instance.SetDelete(&delete_vectorlETPulseIslandmUgR);
       instance.SetDeleteArray(&deleteArray_vectorlETPulseIslandmUgR);
       instance.SetDestructor(&destruct_vectorlETPulseIslandmUgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TPulseIsland*> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< TPulseIsland * > *) static
Definition at line 1177 of file DataLibraryDict.cpp.
References delete_vectorlETPulseIslandmUgR(), deleteArray_vectorlETPulseIslandmUgR(), destruct_vectorlETPulseIslandmUgR(), new_vectorlETPulseIslandmUgR(), newArray_vectorlETPulseIslandmUgR(), and vectorlETPulseIslandmUgR_Dictionary().
    {
       vector<TPulseIsland*> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TPulseIsland*>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TPulseIsland*>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 49,
                   typeid(vector<TPulseIsland*>), DefineBehavior(ptr, ptr),
                   0, &vectorlETPulseIslandmUgR_Dictionary, isa_proxy, 4,
                   sizeof(vector<TPulseIsland*>) );
       instance.SetNew(&new_vectorlETPulseIslandmUgR);
       instance.SetNewArray(&newArray_vectorlETPulseIslandmUgR);
       instance.SetDelete(&delete_vectorlETPulseIslandmUgR);
       instance.SetDeleteArray(&deleteArray_vectorlETPulseIslandmUgR);
       instance.SetDestructor(&destruct_vectorlETPulseIslandmUgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TPulseIsland*> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< string > *) static
Definition at line 1195 of file RootanaDataClasses.cpp.
References delete_vectorlEstringgR(), deleteArray_vectorlEstringgR(), destruct_vectorlEstringgR(), new_vectorlEstringgR(), newArray_vectorlEstringgR(), and vectorlEstringgR_Dictionary().
    {
       vector<string> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<string>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<string>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 49,
                   typeid(vector<string>), DefineBehavior(ptr, ptr),
                   0, &vectorlEstringgR_Dictionary, isa_proxy, 4,
                   sizeof(vector<string>) );
       instance.SetNew(&new_vectorlEstringgR);
       instance.SetNewArray(&newArray_vectorlEstringgR);
       instance.SetDelete(&delete_vectorlEstringgR);
       instance.SetDeleteArray(&deleteArray_vectorlEstringgR);
       instance.SetDestructor(&destruct_vectorlEstringgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<string> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< float > *) static
Definition at line 1235 of file DataLibraryDict.cpp.
References delete_vectorlEfloatgR(), deleteArray_vectorlEfloatgR(), destruct_vectorlEfloatgR(), new_vectorlEfloatgR(), newArray_vectorlEfloatgR(), and vectorlEfloatgR_Dictionary().
    {
       vector<float> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<float>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<float>", -2, "vector.dll", 0,
                   typeid(vector<float>), DefineBehavior(ptr, ptr),
                   0, &vectorlEfloatgR_Dictionary, isa_proxy, 0,
                   sizeof(vector<float>) );
       instance.SetNew(&new_vectorlEfloatgR);
       instance.SetNewArray(&newArray_vectorlEfloatgR);
       instance.SetDelete(&delete_vectorlEfloatgR);
       instance.SetDeleteArray(&deleteArray_vectorlEfloatgR);
       instance.SetDestructor(&destruct_vectorlEfloatgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<float> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< float > *) static
Definition at line 1235 of file DataLibraryDict.cpp.
References delete_vectorlEfloatgR(), deleteArray_vectorlEfloatgR(), destruct_vectorlEfloatgR(), new_vectorlEfloatgR(), newArray_vectorlEfloatgR(), and vectorlEfloatgR_Dictionary().
    {
       vector<float> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<float>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<float>", -2, "vector.dll", 0,
                   typeid(vector<float>), DefineBehavior(ptr, ptr),
                   0, &vectorlEfloatgR_Dictionary, isa_proxy, 0,
                   sizeof(vector<float>) );
       instance.SetNew(&new_vectorlEfloatgR);
       instance.SetNewArray(&newArray_vectorlEfloatgR);
       instance.SetDelete(&delete_vectorlEfloatgR);
       instance.SetDeleteArray(&deleteArray_vectorlEfloatgR);
       instance.SetDestructor(&destruct_vectorlEfloatgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<float> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< int > *) static
Definition at line 1293 of file DataLibraryDict.cpp.
References delete_vectorlEintgR(), deleteArray_vectorlEintgR(), destruct_vectorlEintgR(), new_vectorlEintgR(), newArray_vectorlEintgR(), and vectorlEintgR_Dictionary().
    {
       vector<int> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<int>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 49,
                   typeid(vector<int>), DefineBehavior(ptr, ptr),
                   0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                   sizeof(vector<int>) );
       instance.SetNew(&new_vectorlEintgR);
       instance.SetNewArray(&newArray_vectorlEintgR);
       instance.SetDelete(&delete_vectorlEintgR);
       instance.SetDeleteArray(&deleteArray_vectorlEintgR);
       instance.SetDestructor(&destruct_vectorlEintgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< int > *) static
Definition at line 1293 of file DataLibraryDict.cpp.
References delete_vectorlEintgR(), deleteArray_vectorlEintgR(), destruct_vectorlEintgR(), new_vectorlEintgR(), newArray_vectorlEintgR(), and vectorlEintgR_Dictionary().
    {
       vector<int> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<int>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 49,
                   typeid(vector<int>), DefineBehavior(ptr, ptr),
                   0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                   sizeof(vector<int>) );
       instance.SetNew(&new_vectorlEintgR);
       instance.SetNewArray(&newArray_vectorlEintgR);
       instance.SetDelete(&delete_vectorlEintgR);
       instance.SetDeleteArray(&deleteArray_vectorlEintgR);
       instance.SetDestructor(&destruct_vectorlEintgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, double > *) static
Definition at line 1328 of file DataLibraryDict.cpp.
References delete_maplEstringcOdoublegR(), deleteArray_maplEstringcOdoublegR(), destruct_maplEstringcOdoublegR(), maplEstringcOdoublegR_Dictionary(), new_maplEstringcOdoublegR(), and newArray_maplEstringcOdoublegR().
    {
       map<string,double> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,double>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,double>", -2, "map.dll", 0,
                   typeid(map<string,double>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOdoublegR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,double>) );
       instance.SetNew(&new_maplEstringcOdoublegR);
       instance.SetNewArray(&newArray_maplEstringcOdoublegR);
       instance.SetDelete(&delete_maplEstringcOdoublegR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOdoublegR);
       instance.SetDestructor(&destruct_maplEstringcOdoublegR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,double> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, int > *) static
Definition at line 1386 of file DataLibraryDict.cpp.
References delete_maplEstringcOintgR(), deleteArray_maplEstringcOintgR(), destruct_maplEstringcOintgR(), maplEstringcOintgR_Dictionary(), new_maplEstringcOintgR(), and newArray_maplEstringcOintgR().
    {
       map<string,int> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,int>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,int>", -2, "map.dll", 0,
                   typeid(map<string,int>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOintgR_Dictionary, isa_proxy, 0,
                   sizeof(map<string,int>) );
       instance.SetNew(&new_maplEstringcOintgR);
       instance.SetNewArray(&newArray_maplEstringcOintgR);
       instance.SetDelete(&delete_maplEstringcOintgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOintgR);
       instance.SetDestructor(&destruct_maplEstringcOintgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,int> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, string > *) static
Definition at line 1444 of file DataLibraryDict.cpp.
References delete_maplEstringcOstringgR(), deleteArray_maplEstringcOstringgR(), destruct_maplEstringcOstringgR(), maplEstringcOstringgR_Dictionary(), new_maplEstringcOstringgR(), and newArray_maplEstringcOstringgR().
    {
       map<string,string> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,string>),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,string>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,string>), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOstringgR_Dictionary, isa_proxy, 4,
                   sizeof(map<string,string>) );
       instance.SetNew(&new_maplEstringcOstringgR);
       instance.SetNewArray(&newArray_maplEstringcOstringgR);
       instance.SetDelete(&delete_maplEstringcOstringgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOstringgR);
       instance.SetDestructor(&destruct_maplEstringcOstringgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,string> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, vector< TAnalysedPulse * > > *) static
Definition at line 1502 of file DataLibraryDict.cpp.
References delete_maplEstringcOvectorlETAnalysedPulsemUgRsPgR(), deleteArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR(), destruct_maplEstringcOvectorlETAnalysedPulsemUgRsPgR(), maplEstringcOvectorlETAnalysedPulsemUgRsPgR_Dictionary(), new_maplEstringcOvectorlETAnalysedPulsemUgRsPgR(), and newArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR().
    {
       map<string,vector<TAnalysedPulse*> > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,vector<TAnalysedPulse*> >),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TAnalysedPulse*> >", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,vector<TAnalysedPulse*> >), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETAnalysedPulsemUgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(map<string,vector<TAnalysedPulse*> >) );
       instance.SetNew(&new_maplEstringcOvectorlETAnalysedPulsemUgRsPgR);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR);
       instance.SetDelete(&delete_maplEstringcOvectorlETAnalysedPulsemUgRsPgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETAnalysedPulsemUgRsPgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,vector<TAnalysedPulse*> > >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *) static
Definition at line 1560 of file DataLibraryDict.cpp.
References delete_maplEstringcOvectorlETPulseIslandmUgRsPgR(), deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR(), destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR(), maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary(), new_maplEstringcOvectorlETPulseIslandmUgRsPgR(), and newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR().
    {
       map<string,vector<TPulseIsland*> > *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<string,vector<TPulseIsland*> >),0);
       static ::ROOT::TGenericClassInfo
          instance("map<string,vector<TPulseIsland*> >", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/map", 63,
                   typeid(map<string,vector<TPulseIsland*> >), DefineBehavior(ptr, ptr),
                   0, &maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary, isa_proxy, 4,
                   sizeof(map<string,vector<TPulseIsland*> >) );
       instance.SetNew(&new_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetNewArray(&newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDelete(&delete_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDeleteArray(&deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.SetDestructor(&destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<string,vector<TPulseIsland*> > >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< TAnalysedPulse * > *) static
Definition at line 1618 of file DataLibraryDict.cpp.
References delete_vectorlETAnalysedPulsemUgR(), deleteArray_vectorlETAnalysedPulsemUgR(), destruct_vectorlETAnalysedPulsemUgR(), new_vectorlETAnalysedPulsemUgR(), newArray_vectorlETAnalysedPulsemUgR(), and vectorlETAnalysedPulsemUgR_Dictionary().
    {
       vector<TAnalysedPulse*> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TAnalysedPulse*>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TAnalysedPulse*>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 49,
                   typeid(vector<TAnalysedPulse*>), DefineBehavior(ptr, ptr),
                   0, &vectorlETAnalysedPulsemUgR_Dictionary, isa_proxy, 4,
                   sizeof(vector<TAnalysedPulse*>) );
       instance.SetNew(&new_vectorlETAnalysedPulsemUgR);
       instance.SetNewArray(&newArray_vectorlETAnalysedPulsemUgR);
       instance.SetDelete(&delete_vectorlETAnalysedPulsemUgR);
       instance.SetDeleteArray(&deleteArray_vectorlETAnalysedPulsemUgR);
       instance.SetDestructor(&destruct_vectorlETAnalysedPulsemUgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TAnalysedPulse*> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< TPulseIsland * > *) static
Definition at line 1676 of file DataLibraryDict.cpp.
References delete_vectorlETPulseIslandmUgR(), deleteArray_vectorlETPulseIslandmUgR(), destruct_vectorlETPulseIslandmUgR(), new_vectorlETPulseIslandmUgR(), newArray_vectorlETPulseIslandmUgR(), and vectorlETPulseIslandmUgR_Dictionary().
    {
       vector<TPulseIsland*> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<TPulseIsland*>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<TPulseIsland*>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 49,
                   typeid(vector<TPulseIsland*>), DefineBehavior(ptr, ptr),
                   0, &vectorlETPulseIslandmUgR_Dictionary, isa_proxy, 4,
                   sizeof(vector<TPulseIsland*>) );
       instance.SetNew(&new_vectorlETPulseIslandmUgR);
       instance.SetNewArray(&newArray_vectorlETPulseIslandmUgR);
       instance.SetDelete(&delete_vectorlETPulseIslandmUgR);
       instance.SetDeleteArray(&deleteArray_vectorlETPulseIslandmUgR);
       instance.SetDestructor(&destruct_vectorlETPulseIslandmUgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<TPulseIsland*> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< float > *) static
Definition at line 1734 of file DataLibraryDict.cpp.
References delete_vectorlEfloatgR(), deleteArray_vectorlEfloatgR(), destruct_vectorlEfloatgR(), new_vectorlEfloatgR(), newArray_vectorlEfloatgR(), and vectorlEfloatgR_Dictionary().
    {
       vector<float> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<float>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<float>", -2, "vector.dll", 0,
                   typeid(vector<float>), DefineBehavior(ptr, ptr),
                   0, &vectorlEfloatgR_Dictionary, isa_proxy, 0,
                   sizeof(vector<float>) );
       instance.SetNew(&new_vectorlEfloatgR);
       instance.SetNewArray(&newArray_vectorlEfloatgR);
       instance.SetDelete(&delete_vectorlEfloatgR);
       instance.SetDeleteArray(&deleteArray_vectorlEfloatgR);
       instance.SetDestructor(&destruct_vectorlEfloatgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<float> >()));
       return &instance;
    }
static TGenericClassInfo* ROOT::GenerateInitInstanceLocal (const vector< int > *) static
Definition at line 1792 of file DataLibraryDict.cpp.
References delete_vectorlEintgR(), deleteArray_vectorlEintgR(), destruct_vectorlEintgR(), new_vectorlEintgR(), newArray_vectorlEintgR(), and vectorlEintgR_Dictionary().
    {
       vector<int> *ptr = 0;
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
       static ::ROOT::TGenericClassInfo
          instance("vector<int>", -2, "/home/jrquirk/.local/root_5.34.07/cint/cint/lib/prec_stl/vector", 49,
                   typeid(vector<int>), DefineBehavior(ptr, ptr),
                   0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                   sizeof(vector<int>) );
       instance.SetNew(&new_vectorlEintgR);
       instance.SetNewArray(&newArray_vectorlEintgR);
       instance.SetDelete(&delete_vectorlEintgR);
       instance.SetDeleteArray(&deleteArray_vectorlEintgR);
       instance.SetDestructor(&destruct_vectorlEintgR);
       instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
       return &instance;
    }
void ROOT::IDscLcLchannel_ShowMembers (void * obj, TMemberInspector & R__insp)
void ROOT::IDscLcLgenerator_ShowMembers (void * obj, TMemberInspector & R__insp)
void ROOT::IDscLcLsource_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::maplEIDscLcLDetector_tcOstringgR_Dictionary () static
Definition at line 984 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<IDs::Detector_t,string>*)0x0)->GetClass();
    }
void ROOT::maplEIDscLcLDetector_tcOstringgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::maplEstringcOboolgR_Dictionary () static
Definition at line 908 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,bool>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOboolgR_Dictionary () static
Definition at line 908 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,bool>*)0x0)->GetClass();
    }
void ROOT::maplEstringcOboolgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::maplEstringcOdoublegR_Dictionary () static
Definition at line 765 of file AlcapDict.cxx.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,double>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOdoublegR_Dictionary () static
Definition at line 765 of file Dict.cxx.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,double>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOdoublegR_Dictionary () static
Definition at line 966 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,double>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOdoublegR_Dictionary () static
Definition at line 966 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,double>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOdoublegR_Dictionary () static
Definition at line 1349 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,double>*)0x0)->GetClass();
    }
void ROOT::maplEstringcOdoublegR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::maplEstringcOIDscLcLDetector_tgR_Dictionary () static
Definition at line 1042 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,IDs::Detector_t>*)0x0)->GetClass();
    }
void ROOT::maplEstringcOIDscLcLDetector_tgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::maplEstringcOintgR_Dictionary () static
Definition at line 823 of file Dict.cxx.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,int>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOintgR_Dictionary () static
Definition at line 823 of file AlcapDict.cxx.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,int>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOintgR_Dictionary () static
Definition at line 1024 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,int>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOintgR_Dictionary () static
Definition at line 1024 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,int>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOintgR_Dictionary () static
Definition at line 1407 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,int>*)0x0)->GetClass();
    }
void ROOT::maplEstringcOintgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary () static
Definition at line 172 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary () static
Definition at line 172 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary () static
Definition at line 183 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*)0x0)->GetClass();
    }
void ROOT::maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::maplEstringcOstringgR_Dictionary () static
Definition at line 881 of file AlcapDict.cxx.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,string>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOstringgR_Dictionary () static
Definition at line 881 of file Dict.cxx.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,string>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOstringgR_Dictionary () static
Definition at line 1082 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,string>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOstringgR_Dictionary () static
Definition at line 1082 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,string>*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOstringgR_Dictionary () static
Definition at line 1465 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,string>*)0x0)->GetClass();
    }
void ROOT::maplEstringcOstringgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary () static
Definition at line 300 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary () static
Definition at line 592 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*)0x0)->GetClass();
    }
void ROOT::maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::maplEstringcOvectorlETAnalysedPulsemUgRsPgR_Dictionary () static
Definition at line 1100 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,vector<TAnalysedPulse*> >*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOvectorlETAnalysedPulsemUgRsPgR_Dictionary () static
Definition at line 1523 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,vector<TAnalysedPulse*> >*)0x0)->GetClass();
    }
void ROOT::maplEstringcOvectorlETAnalysedPulsemUgRsPgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary () static
Definition at line 296 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary () static
Definition at line 360 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary () static
Definition at line 360 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary () static
Definition at line 371 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)0x0)->GetClass();
    }
void ROOT::maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary () static
Definition at line 614 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,vector<TPulseIsland*> >*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary () static
Definition at line 939 of file AlcapDict.cxx.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,vector<TPulseIsland*> >*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary () static
Definition at line 939 of file Dict.cxx.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,vector<TPulseIsland*> >*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary () static
Definition at line 1140 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,vector<TPulseIsland*> >*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary () static
Definition at line 1140 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,vector<TPulseIsland*> >*)0x0)->GetClass();
    }
static void ROOT::maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary () static
Definition at line 1581 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const map<string,vector<TPulseIsland*> >*)0x0)->GetClass();
    }
void ROOT::maplEstringcOvectorlETPulseIslandmUgRsPgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void * ROOT::new_IDscLcLchannel (void * p = 0) static
Definition at line 610 of file RootanaDataClasses.cpp.
References channel.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::IDs::channel : new ::IDs::channel;
    }
static void * ROOT::new_IDscLcLgenerator (void * p = 0) static
Definition at line 660 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? new(p) ::IDs::generator : new ::IDs::generator;
    }
static void * ROOT::new_IDscLcLsource (void * p = 0) static
Definition at line 710 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? new(p) ::IDs::source : new ::IDs::source;
    }
static void * ROOT::new_maplEIDscLcLDetector_tcOstringgR (void * p = 0) static
Definition at line 992 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<IDs::Detector_t,string> : new map<IDs::Detector_t,string>;
    }
static void * ROOT::new_maplEstringcOboolgR (void * p = 0) static
Definition at line 916 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,bool> : new map<string,bool>;
    }
static void * ROOT::new_maplEstringcOboolgR (void * p = 0) static
Definition at line 916 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,bool> : new map<string,bool>;
    }
static void * ROOT::new_maplEstringcOdoublegR (void * p = 0) static
Definition at line 773 of file Dict.cxx.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double> : new map<string,double>;
    }
static void * ROOT::new_maplEstringcOdoublegR (void * p = 0) static
Definition at line 773 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double> : new map<string,double>;
    }
static void * ROOT::new_maplEstringcOdoublegR (void * p = 0) static
Definition at line 974 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double> : new map<string,double>;
    }
static void * ROOT::new_maplEstringcOdoublegR (void * p = 0) static
Definition at line 974 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double> : new map<string,double>;
    }
static void * ROOT::new_maplEstringcOdoublegR (void * p = 0) static
Definition at line 1357 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double> : new map<string,double>;
    }
static void * ROOT::new_maplEstringcOIDscLcLDetector_tgR (void * p = 0) static
Definition at line 1050 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,IDs::Detector_t> : new map<string,IDs::Detector_t>;
    }
static void * ROOT::new_maplEstringcOintgR (void * p = 0) static
Definition at line 831 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int> : new map<string,int>;
    }
static void * ROOT::new_maplEstringcOintgR (void * p = 0) static
Definition at line 831 of file Dict.cxx.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int> : new map<string,int>;
    }
static void * ROOT::new_maplEstringcOintgR (void * p = 0) static
Definition at line 1032 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int> : new map<string,int>;
    }
static void * ROOT::new_maplEstringcOintgR (void * p = 0) static
Definition at line 1032 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int> : new map<string,int>;
    }
static void * ROOT::new_maplEstringcOintgR (void * p = 0) static
Definition at line 1415 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int> : new map<string,int>;
    }
static void * ROOT::new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p = 0) static
Definition at line 770 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator : new ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator;
    }
static void * ROOT::new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p = 0) static
Definition at line 770 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator : new ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator;
    }
static void * ROOT::new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void * p = 0) static
Definition at line 1211 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator : new ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator;
    }
static void * ROOT::new_maplEstringcOstringgR (void * p = 0) static
Definition at line 889 of file Dict.cxx.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string> : new map<string,string>;
    }
static void * ROOT::new_maplEstringcOstringgR (void * p = 0) static
Definition at line 889 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string> : new map<string,string>;
    }
static void * ROOT::new_maplEstringcOstringgR (void * p = 0) static
Definition at line 1090 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string> : new map<string,string>;
    }
static void * ROOT::new_maplEstringcOstringgR (void * p = 0) static
Definition at line 1090 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string> : new map<string,string>;
    }
static void * ROOT::new_maplEstringcOstringgR (void * p = 0) static
Definition at line 1473 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string> : new map<string,string>;
    }
static void * ROOT::new_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p = 0) static
Definition at line 850 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator : new ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator;
    }
static void * ROOT::new_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p = 0) static
Definition at line 1104 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator : new ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator;
    }
static void * ROOT::new_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void * p = 0) static
Definition at line 1108 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TAnalysedPulse*> > : new map<string,vector<TAnalysedPulse*> >;
    }
static void * ROOT::new_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void * p = 0) static
Definition at line 1531 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TAnalysedPulse*> > : new map<string,vector<TAnalysedPulse*> >;
    }
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p = 0) static
Definition at line 524 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator : new ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator;
    }
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p = 0) static
Definition at line 649 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator : new ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator;
    }
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p = 0) static
Definition at line 649 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator : new ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator;
    }
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void * p = 0) static
Definition at line 916 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator : new ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator;
    }
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p = 0) static
Definition at line 622 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> > : new map<string,vector<TPulseIsland*> >;
    }
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p = 0) static
Definition at line 947 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> > : new map<string,vector<TPulseIsland*> >;
    }
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p = 0) static
Definition at line 947 of file Dict.cxx.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> > : new map<string,vector<TPulseIsland*> >;
    }
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p = 0) static
Definition at line 1148 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> > : new map<string,vector<TPulseIsland*> >;
    }
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p = 0) static
Definition at line 1148 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> > : new map<string,vector<TPulseIsland*> >;
    }
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void * p = 0) static
Definition at line 1589 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> > : new map<string,vector<TPulseIsland*> >;
    }
static void * ROOT::new_pairlEstringcOstringgR (void * p = 0) static
Definition at line 810 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,string> : new pair<string,string>;
    }
static void * ROOT::new_pairlEstringcOstringgR (void * p = 0) static
Definition at line 810 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,string> : new pair<string,string>;
    }
static void * ROOT::new_pairlEstringcOstringgR (void * p = 0) static
Definition at line 1251 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,string> : new pair<string,string>;
    }
static void * ROOT::new_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void * p = 0) static
Definition at line 890 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > : new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >;
    }
static void * ROOT::new_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void * p = 0) static
Definition at line 1144 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > : new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >;
    }
static void * ROOT::new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p = 0) static
Definition at line 564 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > : new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >;
    }
static void * ROOT::new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p = 0) static
Definition at line 689 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > : new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >;
    }
static void * ROOT::new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p = 0) static
Definition at line 689 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > : new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >;
    }
static void * ROOT::new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void * p = 0) static
Definition at line 956 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > : new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >;
    }
static void * ROOT::new_TAnalysedPulse (void * p = 0) static
Definition at line 760 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? new(p) ::TAnalysedPulse : new ::TAnalysedPulse;
    }
static void * ROOT::new_TAnalysedPulse (void * p = 0) static
Definition at line 1062 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TAnalysedPulse : new ::TAnalysedPulse;
    }
static void * ROOT::new_TAnalysedPulseMapWrapper (void * p = 0) static
Definition at line 934 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? new(p) ::TAnalysedPulseMapWrapper : new ::TAnalysedPulseMapWrapper;
    }
static void * ROOT::new_TDetectorPulse (void * p = 0) static
Definition at line 808 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? new(p) ::TDetectorPulse : new ::TDetectorPulse;
    }
static void * ROOT::new_TDetectorPulse (void * p = 0) static
Definition at line 1190 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TDetectorPulse : new ::TDetectorPulse;
    }
static void * ROOT::new_TGlobalData (void * p = 0) static
Definition at line 401 of file Dict.cxx.
{
       return  p ? new(p) ::TGlobalData : new ::TGlobalData;
    }
static void * ROOT::new_TGlobalData (void * p = 0) static
Definition at line 401 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? new(p) ::TGlobalData : new ::TGlobalData;
    }
static void * ROOT::new_TGlobalData (void * p = 0) static
Definition at line 395 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TGlobalData : new ::TGlobalData;
    }
static void * ROOT::new_TGlobalData (void * p = 0) static
Definition at line 560 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TGlobalData : new ::TGlobalData;
    }
static void * ROOT::new_TGlobalData (void * p = 0) static
Definition at line 560 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TGlobalData : new ::TGlobalData;
    }
static void * ROOT::new_TGlobalData (void * p = 0) static
Definition at line 827 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TGlobalData : new ::TGlobalData;
    }
static void * ROOT::new_TOctalFADCIsland (void * p = 0) static
Definition at line 434 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TOctalFADCIsland : new ::TOctalFADCIsland;
    }
static void * ROOT::new_TPulseIsland (void * p = 0) static
Definition at line 308 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? new(p) ::TPulseIsland : new ::TPulseIsland;
    }
static void * ROOT::new_TPulseIsland (void * p = 0) static
Definition at line 308 of file Dict.cxx.
{
       return  p ? new(p) ::TPulseIsland : new ::TPulseIsland;
    }
static void * ROOT::new_TPulseIsland (void * p = 0) static
Definition at line 482 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TPulseIsland : new ::TPulseIsland;
    }
static void * ROOT::new_TPulseIsland (void * p = 0) static
Definition at line 607 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TPulseIsland : new ::TPulseIsland;
    }
static void * ROOT::new_TPulseIsland (void * p = 0) static
Definition at line 607 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TPulseIsland : new ::TPulseIsland;
    }
static void * ROOT::new_TPulseIsland (void * p = 0) static
Definition at line 874 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TPulseIsland : new ::TPulseIsland;
    }
static void * ROOT::new_TSetupData (void * p = 0) static
Definition at line 711 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? new(p) ::TSetupData : new ::TSetupData;
    }
static void * ROOT::new_TSetupData (void * p = 0) static
Definition at line 711 of file Dict.cxx.
{
       return  p ? new(p) ::TSetupData : new ::TSetupData;
    }
static void * ROOT::new_TSetupData (void * p = 0) static
Definition at line 749 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TSetupData : new ::TSetupData;
    }
static void * ROOT::new_TSetupData (void * p = 0) static
Definition at line 749 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TSetupData : new ::TSetupData;
    }
static void * ROOT::new_TSetupData (void * p = 0) static
Definition at line 1014 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TSetupData : new ::TSetupData;
    }
static void * ROOT::new_TVacuumData (void * p = 0) static
Definition at line 858 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? new(p) ::TVacuumData : new ::TVacuumData;
    }
static void * ROOT::new_TVacuumData (void * p = 0) static
Definition at line 858 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TVacuumData : new ::TVacuumData;
    }
static void * ROOT::new_TVacuumData (void * p = 0) static
Definition at line 1299 of file DataLibraryDict.cpp.
{
       return  p ? new(p) ::TVacuumData : new ::TVacuumData;
    }
static void * ROOT::new_vectorlEfloatgR (void * p = 0) static
Definition at line 1264 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float> : new vector<float>;
    }
static void * ROOT::new_vectorlEfloatgR (void * p = 0) static
Definition at line 1264 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float> : new vector<float>;
    }
static void * ROOT::new_vectorlEfloatgR (void * p = 0) static
Definition at line 1763 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float> : new vector<float>;
    }
static void * ROOT::new_vectorlEintgR (void * p = 0) static
Definition at line 738 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
    }
static void * ROOT::new_vectorlEintgR (void * p = 0) static
Definition at line 1063 of file Dict.cxx.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
    }
static void * ROOT::new_vectorlEintgR (void * p = 0) static
Definition at line 1063 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
    }
static void * ROOT::new_vectorlEintgR (void * p = 0) static
Definition at line 1322 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
    }
static void * ROOT::new_vectorlEintgR (void * p = 0) static
Definition at line 1322 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
    }
static void * ROOT::new_vectorlEintgR (void * p = 0) static
Definition at line 1821 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
    }
static void * ROOT::new_vectorlEstringgR (void * p = 0) static
Definition at line 1224 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string> : new vector<string>;
    }
static void * ROOT::new_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void * p = 0) static
Definition at line 829 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator : new ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator;
    }
static void * ROOT::new_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void * p = 0) static
Definition at line 1083 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator : new ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator;
    }
static void * ROOT::new_vectorlETAnalysedPulsemUgR (void * p = 0) static
Definition at line 1166 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TAnalysedPulse*> : new vector<TAnalysedPulse*>;
    }
static void * ROOT::new_vectorlETAnalysedPulsemUgR (void * p = 0) static
Definition at line 1647 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TAnalysedPulse*> : new vector<TAnalysedPulse*>;
    }
static void * ROOT::new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p = 0) static
Definition at line 503 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator : new ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator;
    }
static void * ROOT::new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p = 0) static
Definition at line 628 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator : new ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator;
    }
static void * ROOT::new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p = 0) static
Definition at line 628 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator : new ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator;
    }
static void * ROOT::new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void * p = 0) static
Definition at line 895 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator : new ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator;
    }
static void * ROOT::new_vectorlETPulseIslandmUgR (void * p = 0) static
Definition at line 680 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*> : new vector<TPulseIsland*>;
    }
static void * ROOT::new_vectorlETPulseIslandmUgR (void * p = 0) static
Definition at line 1005 of file Dict.cxx.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*> : new vector<TPulseIsland*>;
    }
static void * ROOT::new_vectorlETPulseIslandmUgR (void * p = 0) static
Definition at line 1005 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*> : new vector<TPulseIsland*>;
    }
static void * ROOT::new_vectorlETPulseIslandmUgR (void * p = 0) static
Definition at line 1206 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*> : new vector<TPulseIsland*>;
    }
static void * ROOT::new_vectorlETPulseIslandmUgR (void * p = 0) static
Definition at line 1206 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*> : new vector<TPulseIsland*>;
    }
static void * ROOT::new_vectorlETPulseIslandmUgR (void * p = 0) static
Definition at line 1705 of file DataLibraryDict.cpp.
{
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*> : new vector<TPulseIsland*>;
    }
static void * ROOT::newArray_IDscLcLchannel (Long_t size, void * p) static
Definition at line 613 of file RootanaDataClasses.cpp.
References channel.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::IDs::channel[nElements] : new ::IDs::channel[nElements];
    }
static void * ROOT::newArray_IDscLcLgenerator (Long_t size, void * p) static
Definition at line 663 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? new(p) ::IDs::generator[nElements] : new ::IDs::generator[nElements];
    }
static void * ROOT::newArray_IDscLcLsource (Long_t size, void * p) static
Definition at line 713 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? new(p) ::IDs::source[nElements] : new ::IDs::source[nElements];
    }
static void * ROOT::newArray_maplEIDscLcLDetector_tcOstringgR (Long_t size, void * p) static
Definition at line 995 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<IDs::Detector_t,string>[nElements] : new map<IDs::Detector_t,string>[nElements];
    }
static void * ROOT::newArray_maplEstringcOboolgR (Long_t size, void * p) static
Definition at line 919 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,bool>[nElements] : new map<string,bool>[nElements];
    }
static void * ROOT::newArray_maplEstringcOboolgR (Long_t size, void * p) static
Definition at line 919 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,bool>[nElements] : new map<string,bool>[nElements];
    }
static void * ROOT::newArray_maplEstringcOdoublegR (Long_t size, void * p) static
Definition at line 776 of file Dict.cxx.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double>[nElements] : new map<string,double>[nElements];
    }
static void * ROOT::newArray_maplEstringcOdoublegR (Long_t size, void * p) static
Definition at line 776 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double>[nElements] : new map<string,double>[nElements];
    }
static void * ROOT::newArray_maplEstringcOdoublegR (Long_t size, void * p) static
Definition at line 977 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double>[nElements] : new map<string,double>[nElements];
    }
static void * ROOT::newArray_maplEstringcOdoublegR (Long_t size, void * p) static
Definition at line 977 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double>[nElements] : new map<string,double>[nElements];
    }
static void * ROOT::newArray_maplEstringcOdoublegR (Long_t size, void * p) static
Definition at line 1360 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,double>[nElements] : new map<string,double>[nElements];
    }
static void * ROOT::newArray_maplEstringcOIDscLcLDetector_tgR (Long_t size, void * p) static
Definition at line 1053 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,IDs::Detector_t>[nElements] : new map<string,IDs::Detector_t>[nElements];
    }
static void * ROOT::newArray_maplEstringcOintgR (Long_t size, void * p) static
Definition at line 834 of file Dict.cxx.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int>[nElements] : new map<string,int>[nElements];
    }
static void * ROOT::newArray_maplEstringcOintgR (Long_t size, void * p) static
Definition at line 834 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int>[nElements] : new map<string,int>[nElements];
    }
static void * ROOT::newArray_maplEstringcOintgR (Long_t size, void * p) static
Definition at line 1035 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int>[nElements] : new map<string,int>[nElements];
    }
static void * ROOT::newArray_maplEstringcOintgR (Long_t size, void * p) static
Definition at line 1035 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int>[nElements] : new map<string,int>[nElements];
    }
static void * ROOT::newArray_maplEstringcOintgR (Long_t size, void * p) static
Definition at line 1418 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,int>[nElements] : new map<string,int>[nElements];
    }
static void * ROOT::newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 773 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator[nElements] : new ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator[nElements];
    }
static void * ROOT::newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 773 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator[nElements] : new ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator[nElements];
    }
static void * ROOT::newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 1214 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator[nElements] : new ::map<string,string,less<string>,allocator<pair<const string,string> > >::iterator[nElements];
    }
static void * ROOT::newArray_maplEstringcOstringgR (Long_t size, void * p) static
Definition at line 892 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string>[nElements] : new map<string,string>[nElements];
    }
static void * ROOT::newArray_maplEstringcOstringgR (Long_t size, void * p) static
Definition at line 892 of file Dict.cxx.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string>[nElements] : new map<string,string>[nElements];
    }
static void * ROOT::newArray_maplEstringcOstringgR (Long_t size, void * p) static
Definition at line 1093 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string>[nElements] : new map<string,string>[nElements];
    }
static void * ROOT::newArray_maplEstringcOstringgR (Long_t size, void * p) static
Definition at line 1093 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string>[nElements] : new map<string,string>[nElements];
    }
static void * ROOT::newArray_maplEstringcOstringgR (Long_t size, void * p) static
Definition at line 1476 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,string>[nElements] : new map<string,string>[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 853 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator[nElements] : new ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 1107 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator[nElements] : new ::map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (Long_t size, void * p) static
Definition at line 1111 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TAnalysedPulse*> >[nElements] : new map<string,vector<TAnalysedPulse*> >[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (Long_t size, void * p) static
Definition at line 1534 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TAnalysedPulse*> >[nElements] : new map<string,vector<TAnalysedPulse*> >[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 527 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator[nElements] : new ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 652 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator[nElements] : new ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 652 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator[nElements] : new ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 919 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator[nElements] : new ::map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void * p) static
Definition at line 625 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> >[nElements] : new map<string,vector<TPulseIsland*> >[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void * p) static
Definition at line 950 of file Dict.cxx.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> >[nElements] : new map<string,vector<TPulseIsland*> >[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void * p) static
Definition at line 950 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> >[nElements] : new map<string,vector<TPulseIsland*> >[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void * p) static
Definition at line 1151 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> >[nElements] : new map<string,vector<TPulseIsland*> >[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void * p) static
Definition at line 1151 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> >[nElements] : new map<string,vector<TPulseIsland*> >[nElements];
    }
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void * p) static
Definition at line 1592 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<string,vector<TPulseIsland*> >[nElements] : new map<string,vector<TPulseIsland*> >[nElements];
    }
static void * ROOT::newArray_pairlEstringcOstringgR (Long_t size, void * p) static
Definition at line 813 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,string>[nElements] : new pair<string,string>[nElements];
    }
static void * ROOT::newArray_pairlEstringcOstringgR (Long_t size, void * p) static
Definition at line 813 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,string>[nElements] : new pair<string,string>[nElements];
    }
static void * ROOT::newArray_pairlEstringcOstringgR (Long_t size, void * p) static
Definition at line 1254 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,string>[nElements] : new pair<string,string>[nElements];
    }
static void * ROOT::newArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (Long_t size, void * p) static
Definition at line 893 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >[nElements] : new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >[nElements];
    }
static void * ROOT::newArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (Long_t size, void * p) static
Definition at line 1147 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >[nElements] : new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >[nElements];
    }
static void * ROOT::newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (Long_t size, void * p) static
Definition at line 567 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >[nElements] : new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >[nElements];
    }
static void * ROOT::newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (Long_t size, void * p) static
Definition at line 692 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >[nElements] : new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >[nElements];
    }
static void * ROOT::newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (Long_t size, void * p) static
Definition at line 692 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >[nElements] : new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >[nElements];
    }
static void * ROOT::newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (Long_t size, void * p) static
Definition at line 959 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >[nElements] : new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >[nElements];
    }
static void * ROOT::newArray_TAnalysedPulse (Long_t size, void * p) static
Definition at line 763 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? new(p) ::TAnalysedPulse[nElements] : new ::TAnalysedPulse[nElements];
    }
static void * ROOT::newArray_TAnalysedPulse (Long_t size, void * p) static
Definition at line 1065 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TAnalysedPulse[nElements] : new ::TAnalysedPulse[nElements];
    }
static void * ROOT::newArray_TAnalysedPulseMapWrapper (Long_t size, void * p) static
Definition at line 937 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? new(p) ::TAnalysedPulseMapWrapper[nElements] : new ::TAnalysedPulseMapWrapper[nElements];
    }
static void * ROOT::newArray_TDetectorPulse (Long_t size, void * p) static
Definition at line 811 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? new(p) ::TDetectorPulse[nElements] : new ::TDetectorPulse[nElements];
    }
static void * ROOT::newArray_TDetectorPulse (Long_t size, void * p) static
Definition at line 1193 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TDetectorPulse[nElements] : new ::TDetectorPulse[nElements];
    }
static void * ROOT::newArray_TGlobalData (Long_t size, void * p) static
Definition at line 404 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return p ? new(p) ::TGlobalData[nElements] : new ::TGlobalData[nElements];
    }
static void * ROOT::newArray_TGlobalData (Long_t size, void * p) static
Definition at line 404 of file Dict.cxx.
{
       return p ? new(p) ::TGlobalData[nElements] : new ::TGlobalData[nElements];
    }
static void * ROOT::newArray_TGlobalData (Long_t size, void * p) static
Definition at line 398 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TGlobalData[nElements] : new ::TGlobalData[nElements];
    }
static void * ROOT::newArray_TGlobalData (Long_t size, void * p) static
Definition at line 563 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TGlobalData[nElements] : new ::TGlobalData[nElements];
    }
static void * ROOT::newArray_TGlobalData (Long_t size, void * p) static
Definition at line 563 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TGlobalData[nElements] : new ::TGlobalData[nElements];
    }
static void * ROOT::newArray_TGlobalData (Long_t size, void * p) static
Definition at line 830 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TGlobalData[nElements] : new ::TGlobalData[nElements];
    }
static void * ROOT::newArray_TOctalFADCIsland (Long_t size, void * p) static
Definition at line 437 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TOctalFADCIsland[nElements] : new ::TOctalFADCIsland[nElements];
    }
static void * ROOT::newArray_TPulseIsland (Long_t size, void * p) static
Definition at line 311 of file Dict.cxx.
{
       return p ? new(p) ::TPulseIsland[nElements] : new ::TPulseIsland[nElements];
    }
static void * ROOT::newArray_TPulseIsland (Long_t size, void * p) static
Definition at line 311 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return p ? new(p) ::TPulseIsland[nElements] : new ::TPulseIsland[nElements];
    }
static void * ROOT::newArray_TPulseIsland (Long_t size, void * p) static
Definition at line 485 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TPulseIsland[nElements] : new ::TPulseIsland[nElements];
    }
static void * ROOT::newArray_TPulseIsland (Long_t size, void * p) static
Definition at line 610 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TPulseIsland[nElements] : new ::TPulseIsland[nElements];
    }
static void * ROOT::newArray_TPulseIsland (Long_t size, void * p) static
Definition at line 610 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TPulseIsland[nElements] : new ::TPulseIsland[nElements];
    }
static void * ROOT::newArray_TPulseIsland (Long_t size, void * p) static
Definition at line 877 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TPulseIsland[nElements] : new ::TPulseIsland[nElements];
    }
static void * ROOT::newArray_TSetupData (Long_t size, void * p) static
Definition at line 714 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return p ? new(p) ::TSetupData[nElements] : new ::TSetupData[nElements];
    }
static void * ROOT::newArray_TSetupData (Long_t size, void * p) static
Definition at line 714 of file Dict.cxx.
{
       return p ? new(p) ::TSetupData[nElements] : new ::TSetupData[nElements];
    }
static void * ROOT::newArray_TSetupData (Long_t size, void * p) static
Definition at line 752 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TSetupData[nElements] : new ::TSetupData[nElements];
    }
static void * ROOT::newArray_TSetupData (Long_t size, void * p) static
Definition at line 752 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TSetupData[nElements] : new ::TSetupData[nElements];
    }
static void * ROOT::newArray_TSetupData (Long_t size, void * p) static
Definition at line 1017 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TSetupData[nElements] : new ::TSetupData[nElements];
    }
static void * ROOT::newArray_TVacuumData (Long_t size, void * p) static
Definition at line 861 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? new(p) ::TVacuumData[nElements] : new ::TVacuumData[nElements];
    }
static void * ROOT::newArray_TVacuumData (Long_t size, void * p) static
Definition at line 861 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TVacuumData[nElements] : new ::TVacuumData[nElements];
    }
static void * ROOT::newArray_TVacuumData (Long_t size, void * p) static
Definition at line 1302 of file DataLibraryDict.cpp.
{
       return p ? new(p) ::TVacuumData[nElements] : new ::TVacuumData[nElements];
    }
static void * ROOT::newArray_vectorlEfloatgR (Long_t size, void * p) static
Definition at line 1267 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float>[nElements] : new vector<float>[nElements];
    }
static void * ROOT::newArray_vectorlEfloatgR (Long_t size, void * p) static
Definition at line 1267 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float>[nElements] : new vector<float>[nElements];
    }
static void * ROOT::newArray_vectorlEfloatgR (Long_t size, void * p) static
Definition at line 1766 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float>[nElements] : new vector<float>[nElements];
    }
static void * ROOT::newArray_vectorlEintgR (Long_t size, void * p) static
Definition at line 741 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
    }
static void * ROOT::newArray_vectorlEintgR (Long_t size, void * p) static
Definition at line 1066 of file Dict.cxx.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
    }
static void * ROOT::newArray_vectorlEintgR (Long_t size, void * p) static
Definition at line 1066 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
    }
static void * ROOT::newArray_vectorlEintgR (Long_t size, void * p) static
Definition at line 1325 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
    }
static void * ROOT::newArray_vectorlEintgR (Long_t size, void * p) static
Definition at line 1325 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
    }
static void * ROOT::newArray_vectorlEintgR (Long_t size, void * p) static
Definition at line 1824 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
    }
static void * ROOT::newArray_vectorlEstringgR (Long_t size, void * p) static
Definition at line 1227 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string>[nElements] : new vector<string>[nElements];
    }
static void * ROOT::newArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 832 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator[nElements] : new ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator[nElements];
    }
static void * ROOT::newArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 1086 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator[nElements] : new ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator[nElements];
    }
static void * ROOT::newArray_vectorlETAnalysedPulsemUgR (Long_t size, void * p) static
Definition at line 1169 of file RootanaDataClasses.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TAnalysedPulse*>[nElements] : new vector<TAnalysedPulse*>[nElements];
    }
static void * ROOT::newArray_vectorlETAnalysedPulsemUgR (Long_t size, void * p) static
Definition at line 1650 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TAnalysedPulse*>[nElements] : new vector<TAnalysedPulse*>[nElements];
    }
static void * ROOT::newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 506 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator[nElements] : new ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator[nElements];
    }
static void * ROOT::newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 631 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator[nElements] : new ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator[nElements];
    }
static void * ROOT::newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 631 of file DataLibraryDict.cpp.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator[nElements] : new ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator[nElements];
    }
static void * ROOT::newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (Long_t size, void * p) static
Definition at line 898 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator[nElements] : new ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator[nElements];
    }
static void * ROOT::newArray_vectorlETPulseIslandmUgR (Long_t size, void * p) static
Definition at line 683 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*>[nElements] : new vector<TPulseIsland*>[nElements];
    }
static void * ROOT::newArray_vectorlETPulseIslandmUgR (Long_t size, void * p) static
Definition at line 1008 of file Dict.cxx.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*>[nElements] : new vector<TPulseIsland*>[nElements];
    }
static void * ROOT::newArray_vectorlETPulseIslandmUgR (Long_t size, void * p) static
Definition at line 1008 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*>[nElements] : new vector<TPulseIsland*>[nElements];
    }
static void * ROOT::newArray_vectorlETPulseIslandmUgR (Long_t size, void * p) static
Definition at line 1209 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*>[nElements] : new vector<TPulseIsland*>[nElements];
    }
static void * ROOT::newArray_vectorlETPulseIslandmUgR (Long_t size, void * p) static
Definition at line 1209 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*>[nElements] : new vector<TPulseIsland*>[nElements];
    }
static void * ROOT::newArray_vectorlETPulseIslandmUgR (Long_t size, void * p) static
Definition at line 1708 of file DataLibraryDict.cpp.
{
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<TPulseIsland*>[nElements] : new vector<TPulseIsland*>[nElements];
    }
static void ROOT::pairlEstringcOstringgR_Dictionary () static
Definition at line 132 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const pair<string,string>*)0x0)->GetClass();
    }
static void ROOT::pairlEstringcOstringgR_Dictionary () static
Definition at line 132 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const pair<string,string>*)0x0)->GetClass();
    }
static void ROOT::pairlEstringcOstringgR_Dictionary () static
Definition at line 143 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const pair<string,string>*)0x0)->GetClass();
    }
void ROOT::pairlEstringcOstringgR_ShowMembers (void * obj, TMemberInspector & R__insp)
Definition at line 791 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
    {
       // Inspect the data members of an object of class pair<string,string>.
       typedef ::ROOT::Shadow::pairlEstringcOstringgR ShadowClass;
       ShadowClass *sobj = (ShadowClass*)obj;
       if (sobj) { } // Dummy usage just in case there is no datamember.
       TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const pair<string,string>*)0x0)->GetClass();
       if (R__cl || R__insp.IsA()) { }
       R__insp.Inspect(R__cl, R__insp.GetParent(), "first", (void*)&sobj->first);
       R__insp.InspectMember("string", (void*)&sobj->first, "first.", false);
       R__insp.Inspect(R__cl, R__insp.GetParent(), "second", (void*)&sobj->second);
       R__insp.InspectMember("string", (void*)&sobj->second, "second.", false);
    }
static void ROOT::pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_Dictionary () static
Definition at line 260 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*)0x0)->GetClass();
    }
static void ROOT::pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_Dictionary () static
Definition at line 552 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*)0x0)->GetClass();
    }
void ROOT::pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_ShowMembers (void * obj, TMemberInspector & R__insp)
Definition at line 871 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
    {
       // Inspect the data members of an object of class pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >.
       typedef ::ROOT::Shadow::pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR ShadowClass;
       ShadowClass *sobj = (ShadowClass*)obj;
       if (sobj) { } // Dummy usage just in case there is no datamember.
       TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*)0x0)->GetClass();
       if (R__cl || R__insp.IsA()) { }
       R__insp.Inspect(R__cl, R__insp.GetParent(), "first", (void*)&sobj->first);
       R__insp.InspectMember("string", (void*)&sobj->first, "first.", false);
       R__insp.Inspect(R__cl, R__insp.GetParent(), "second", (void*)&sobj->second);
       R__insp.InspectMember("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >", (void*)&sobj->second, "second.", false);
    }
static void ROOT::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary () static
Definition at line 256 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)0x0)->GetClass();
    }
static void ROOT::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary () static
Definition at line 320 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)0x0)->GetClass();
    }
static void ROOT::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary () static
Definition at line 320 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)0x0)->GetClass();
    }
static void ROOT::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary () static
Definition at line 331 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)0x0)->GetClass();
    }
void ROOT::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers (void * obj, TMemberInspector & R__insp)
Definition at line 670 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
    {
       // Inspect the data members of an object of class pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >.
       typedef ::ROOT::Shadow::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR ShadowClass;
       ShadowClass *sobj = (ShadowClass*)obj;
       if (sobj) { } // Dummy usage just in case there is no datamember.
       TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)0x0)->GetClass();
       if (R__cl || R__insp.IsA()) { }
       R__insp.Inspect(R__cl, R__insp.GetParent(), "first", (void*)&sobj->first);
       R__insp.InspectMember("string", (void*)&sobj->first, "first.", false);
       R__insp.Inspect(R__cl, R__insp.GetParent(), "second", (void*)&sobj->second);
       R__insp.InspectMember("vector<TPulseIsland*,allocator<TPulseIsland*> >", (void*)&sobj->second, "second.", false);
    }
ROOT::R__UseDummy (_R__UNIQUE_(Init))
static void ROOT::streamer_TGlobalData (TBuffer & buf, void * obj) static
Definition at line 419 of file Dict.cxx.
{
       ((::TGlobalData*)obj)->::TGlobalData::Streamer(buf);
    }
static void ROOT::streamer_TGlobalData (TBuffer & buf, void * obj) static
Definition at line 419 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       ((::TGlobalData*)obj)->::TGlobalData::Streamer(buf);
    }
static void ROOT::streamer_TPulseIsland (TBuffer & buf, void * obj) static
Definition at line 326 of file Dict.cxx.
{
       ((::TPulseIsland*)obj)->::TPulseIsland::Streamer(buf);
    }
static void ROOT::streamer_TPulseIsland (TBuffer & buf, void * obj) static
Definition at line 326 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       ((::TPulseIsland*)obj)->::TPulseIsland::Streamer(buf);
    }
static void ROOT::streamer_TSetupData (TBuffer & buf, void * obj) static
Definition at line 729 of file AlcapDict.cxx.
Referenced by GenerateInitInstanceLocal().
{
       ((::TSetupData*)obj)->::TSetupData::Streamer(buf);
    }
static void ROOT::streamer_TSetupData (TBuffer & buf, void * obj) static
Definition at line 729 of file Dict.cxx.
{
       ((::TSetupData*)obj)->::TSetupData::Streamer(buf);
    }
void ROOT::TAnalysedPulse_ShowMembers (void * obj, TMemberInspector & R__insp)
void ROOT::TAnalysedPulseMapWrapper_ShowMembers (void * obj, TMemberInspector & R__insp)
void ROOT::TDetectorPulse_ShowMembers (void * obj, TMemberInspector & R__insp)
void ROOT::TGlobalData_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::TOctalFADCIsland_Dictionary () static
Definition at line 108 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::TOctalFADCIsland*)0x0)->GetClass();
    }
void ROOT::TOctalFADCIsland_ShowMembers (void * obj, TMemberInspector & R__insp)
Definition at line 416 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
    {
       // Inspect the data members of an object of class TOctalFADCIsland.
       typedef ::ROOT::Shadow::TOctalFADCIsland ShadowClass;
       ShadowClass *sobj = (ShadowClass*)obj;
       if (sobj) { } // Dummy usage just in case there is no datamember.
       TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::TOctalFADCIsland*)0x0)->GetClass();
       if (R__cl || R__insp.IsA()) { }
       R__insp.Inspect(R__cl, R__insp.GetParent(), "fTime", &sobj->fTime);
       R__insp.Inspect(R__cl, R__insp.GetParent(), "fData", (void*)&sobj->fData);
       R__insp.InspectMember("vector<int>", (void*)&sobj->fData, "fData.", false);
    }
void ROOT::TPulseIsland_ShowMembers (void * obj, TMemberInspector & R__insp)
void ROOT::TSetupData_ShowMembers (void * obj, TMemberInspector & R__insp)
void ROOT::TVacuumData_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::vectorlEfloatgR_Dictionary () static
Definition at line 1256 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<float>*)0x0)->GetClass();
    }
static void ROOT::vectorlEfloatgR_Dictionary () static
Definition at line 1256 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<float>*)0x0)->GetClass();
    }
static void ROOT::vectorlEfloatgR_Dictionary () static
Definition at line 1755 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<float>*)0x0)->GetClass();
    }
void ROOT::vectorlEfloatgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::vectorlEintgR_Dictionary () static
Definition at line 730 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
    }
static void ROOT::vectorlEintgR_Dictionary () static
Definition at line 1055 of file Dict.cxx.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
    }
static void ROOT::vectorlEintgR_Dictionary () static
Definition at line 1055 of file AlcapDict.cxx.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
    }
static void ROOT::vectorlEintgR_Dictionary () static
Definition at line 1314 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
    }
static void ROOT::vectorlEintgR_Dictionary () static
Definition at line 1314 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
    }
static void ROOT::vectorlEintgR_Dictionary () static
Definition at line 1813 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
    }
void ROOT::vectorlEintgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::vectorlEstringgR_Dictionary () static
Definition at line 1216 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<string>*)0x0)->GetClass();
    }
void ROOT::vectorlEstringgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_Dictionary () static
Definition at line 218 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*)0x0)->GetClass();
    }
static void ROOT::vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_Dictionary () static
Definition at line 510 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*)0x0)->GetClass();
    }
void ROOT::vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::vectorlETAnalysedPulsemUgR_Dictionary () static
Definition at line 1158 of file RootanaDataClasses.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<TAnalysedPulse*>*)0x0)->GetClass();
    }
static void ROOT::vectorlETAnalysedPulsemUgR_Dictionary () static
Definition at line 1639 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<TAnalysedPulse*>*)0x0)->GetClass();
    }
void ROOT::vectorlETAnalysedPulsemUgR_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary () static
Definition at line 214 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)0x0)->GetClass();
    }
static void ROOT::vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary () static
Definition at line 278 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)0x0)->GetClass();
    }
static void ROOT::vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary () static
Definition at line 278 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)0x0)->GetClass();
    }
static void ROOT::vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary () static
Definition at line 289 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const ::vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)0x0)->GetClass();
    }
void ROOT::vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_ShowMembers (void * obj, TMemberInspector & R__insp)
static void ROOT::vectorlETPulseIslandmUgR_Dictionary () static
Definition at line 672 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<TPulseIsland*>*)0x0)->GetClass();
    }
static void ROOT::vectorlETPulseIslandmUgR_Dictionary () static
Definition at line 997 of file Dict.cxx.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<TPulseIsland*>*)0x0)->GetClass();
    }
static void ROOT::vectorlETPulseIslandmUgR_Dictionary () static
Definition at line 997 of file AlcapDict.cxx.
References GenerateInitInstanceLocal().
Referenced by GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<TPulseIsland*>*)0x0)->GetClass();
    }
static void ROOT::vectorlETPulseIslandmUgR_Dictionary () static
Definition at line 1198 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<TPulseIsland*>*)0x0)->GetClass();
    }
static void ROOT::vectorlETPulseIslandmUgR_Dictionary () static
Definition at line 1198 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<TPulseIsland*>*)0x0)->GetClass();
    }
static void ROOT::vectorlETPulseIslandmUgR_Dictionary () static
Definition at line 1697 of file DataLibraryDict.cpp.
References GenerateInitInstanceLocal().
{
       ::ROOT::GenerateInitInstanceLocal((const vector<TPulseIsland*>*)0x0)->GetClass();
    }
void ROOT::vectorlETPulseIslandmUgR_ShowMembers (void * obj, TMemberInspector & R__insp)