AlcapDAQ: functions Namespace Reference
functions Namespace Reference
Classes
class QuadraticFit
Functor(-ish) class to calculate fit of a quadratic to N data-points.
Functions
double gauss_lin (double *x, double *par)
TH1D * InterpolatePulse (const TPulseIsland *pulse, std::string histname, std::string histtitle, bool interpolate, int refine)
void FillBinLabels (double *labels, int size, int start=-1, int increment=1)
template<typename ValueType >
TH1F * VectorToHist (const std::vector< ValueType > &vect, std::string name, std::string title)
Function Documentation
void functions::FillBinLabels (double * labels, int size, int start = -1, int increment = 1)
Definition at line 67 of file InterpolatePulse.cpp.
Referenced by VectorToHist().
{
   unique_n uniq(start,increment);
   std::generate_n(labels,size, uniq);
}
double functions::gauss_lin (double * x, double * par)
Definition at line 5 of file Functions.cpp.
Referenced by TGaussFitAnalysedPulse::Draw(), and GaussFitAPGenerator::GaussFitAPGenerator().
{
    // parameters:
    // 0: constant (pedestal)
    // 1: gradient
    // 2: Gauss amplitude
    // 3: Gauss mean
    // 4: Gauss width
    Double_t arg=(x[0]-par[3])/par[4];
    Double_t gauss1=par[2]*TMath::Exp(-0.5*arg*arg)/(2.5066283*par[4]);
    // function=gauss+constant background
    return gauss1+par[0] + par[1]*x[0];
}
TH1D * functions::InterpolatePulse (const TPulseIsland * pulse, std::string histname, std::string histtitle, bool interpolate, int refine)
Definition at line 10 of file InterpolatePulse.cpp.
References TPulseIsland::GetBankName(), TSetupData::GetDetectorName(), SetupNavigator::GetNoise(), TPulseIsland::GetSamples(), SetupNavigator::Instance(), and TSetupData::Instance().
Referenced by TemplateCreator::CreateRefinedPulseHistogram(), and TemplateFitAPGenerator::ProcessPulses().
{
  // Get a few things first
  const std::string& bankname = pulse->GetBankName();
  const std::string detname = TSetupData::Instance()->GetDetectorName(bankname);
  const std::vector<int>& theSamples = pulse->GetSamples();
  int n_samples = theSamples.size();
  int n_bins = refine*n_samples; // number of bins in the template
  // Create the higher resolution histogram
  TH1D* hist = new TH1D(histname.c_str(), histtitle.c_str(), n_bins, 0, n_samples);
  double pedestal_error = SetupNavigator::Instance()->GetNoise(detname);
  // Go through the bins in the high-resolution histogram
  // NB sample numbers go grom 0 to n-1 and bins go from 1 to n
  for (int i = 0; i < n_bins; ++i) {
    int bin = i+1; // bins go from 1 to n rather than 0 to n-1
    int sample_number = i / refine;
    double remainder = i % refine;
    double sample_value;
    // We may want to interpolate between the samples in the samples vector
    if (interpolate) {
      try {
        sample_value = theSamples.at(sample_number)
                     + (remainder / refine)*(theSamples.at(sample_number+1)
                                                     - theSamples.at(sample_number));
      }
      catch (const std::out_of_range& oor) { // if we'll be going out of range of the samples vector
        sample_value = theSamples.at(sample_number);
      }
    }
    else {
      sample_value = theSamples.at(sample_number);
    }
    // Set the bin contents and bin error
    hist->SetBinContent( bin, sample_value);
    hist->SetBinError( bin, pedestal_error);
  }
  hist->SetDirectory(0);
  return hist;
}
template<typename ValueType > TH1F* functions::VectorToHist (const std::vector< ValueType > & vect, std::string name, std::string title) [inline]
Definition at line 18 of file InterpolatePulse.h.
References FillBinLabels().
Referenced by TemplateConvolver::CharacteriseTemplate(), and TTemplateConvolveAnalysedPulse::Draw().
                     {
   const int size=vect.size();
   double labels[size];
   FillBinLabels(labels,size);
   TH1F* hist=new TH1F(name.c_str(),title.c_str(), size,0,size);
   hist->FillN(size,labels,vect.data());
   hist->SetDirectory(0);
   return hist;
}