AlcapDAQ: crate9/new_fadc_2007_07_17.cpp File Reference
new_fadc_2007_07_17.cpp File Reference
#include <map>
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <net/if.h>
#include <net/ethernet.h>
#include <netinet/in.h>
#include <linux/if_packet.h>
#include "midas.h"
#include "crate.h"
#include "vme.h"
#include "odb_wrapper.h"
#include "diag.h"
Data Structures
struct fadc_packet
struct fadc_board
Functions
INT new_fadc_bor ()
INT new_fadc_eor ()
INT new_fadc_read (char *pevent)
bool allPacketsReceived (bool diag=false)
void receivePackets ()
void forgetPackets ()
void setReg (char *if_name, int board, int fadc, int reg, unsigned long long value)
void setupRegs ()
Variables
const int TP_BLOCK_SIZE = 8192
const int TP_NUM_BLOCKS = 512
const int FRAME_SIZE = 2048
const int NUM_FRAMES = 2048
unsigned char * packet_space = 0
bool frame_examined [NUM_FRAMES]
struct readout_module new_fadc_module
int packet_socket
const int max_boards = 256
struct fadc_board board [max_boards]
static struct timeval tv_start
Function Documentation
bool allPacketsReceived (bool diag = false)
void forgetPackets ()
Definition at line 139 of file new_fadc_2007_07_17.cpp.
References board, enabled, fadc_board::first_packet_time, frame_examined, FRAME_SIZE, i, max_boards, NUM_FRAMES, packet_space, fadc_board::packets, fadc_board::start_packet_seen, and fadc_board::stop_packet_seen.
 {
   for(int i = 0; i < max_boards; i++) {
     if(board[i].enabled) {
       board[i].packets.clear();
       board[i].start_packet_seen = false;
       board[i].stop_packet_seen = false;
       board[i].first_packet_time = -1;
     }
   }
   // release all frame buffers back to the kernel
   for(int i = 0; i < NUM_FRAMES; i++) {
     unsigned char *frame = packet_space + i*FRAME_SIZE;
     struct tpacket_hdr *tph = (struct tpacket_hdr *) frame;
     tph->tp_status = TP_STATUS_KERNEL;
     frame_examined[i] = false;
   }
 }
INT new_fadc_bor ()
INT new_fadc_eor ()
INT new_fadc_read (char * pevent)
void receivePackets ()
Definition at line 88 of file new_fadc_2007_07_17.cpp.
References fadc_packet::admin_message, board, fadc_packet::buffer_number, fadc_packet::content_length, enabled, fadc_board::first_packet, fadc_board::first_packet_time, frame_examined, FRAME_SIZE, i, fadc_board::last_packet, fadc_board::last_packet_time, NUM_FRAMES, fadc_packet::packet_serial, packet_space, fadc_board::packets, printf(), fadc_packet::src_addr, fadc_board::start_packet, fadc_board::start_packet_seen, fadc_board::stop_packet, and fadc_board::stop_packet_seen.
 {
   for(int i = 0; i < NUM_FRAMES; i++) {
     if(frame_examined[i]) continue;
     unsigned char *frame = packet_space + i*FRAME_SIZE;
     struct tpacket_hdr *tph = (struct tpacket_hdr *) frame;
     if(!(tph->tp_status & TP_STATUS_USER)) continue;
     struct fadc_packet *pkt = (struct fadc_packet *) (frame + tph->tp_mac);
     int board_number = pkt->src_addr[5];
     if(!board[board_number].enabled) continue;
     int content_length = ntohs(pkt->content_length);
     int buffer_number = pkt->buffer_number;
     int admin_message = pkt->admin_message;
     int packet_serial = ntohs(pkt->packet_serial);
 #if 0
     printf("board %d length %d buffer %d admin %d serial %d\n",
        board_number, content_length, buffer_number,
        admin_message, packet_serial);
 #endif
     board[board_number].packets[packet_serial] = pkt;
     if(admin_message & 0x1) {
       board[board_number].start_packet = packet_serial;
       board[board_number].start_packet_seen = true;
     }
    if(admin_message & 0x2) {
      board[board_number].stop_packet = packet_serial;
      board[board_number].stop_packet_seen = true;
    }
    double packet_time = tph->tp_sec*1e6 + tph->tp_usec;
    double fpt = board[board_number].first_packet_time;
    if(packet_time < fpt || fpt < 0) {
      board[board_number].first_packet = packet_serial;
      board[board_number].first_packet_time = packet_time;
    }
    double lpt = board[board_number].last_packet_time;
    if(packet_time > lpt || lpt < 0) {
      board[board_number].last_packet = packet_serial;
      board[board_number].last_packet_time = packet_time;
    }
    frame_examined[i] = true;
   }
 }
void setReg (char * if_name, int board, int fadc, int reg, unsigned long long value)
Definition at line 226 of file new_fadc_2007_07_17.cpp.
References board, packet_socket, printf(), and value.
 {
   // look up the index of the interface
   int if_index = if_nametoindex(if_name);
   if(if_index < 0) {
     printf("Unknown interface %s\n", if_name);
     return;
   }
   struct ifreq req;
   strcpy(req.ifr_name, if_name);
   if(ioctl(packet_socket, SIOCGIFHWADDR, &req) < 0) {
     perror("SIOCGIFHWADDR");
     return;
   }
   unsigned char src[ETH_ALEN];
   memcpy(src, req.ifr_hwaddr.sa_data, ETH_ALEN);
   unsigned char dst[ETH_ALEN] = { 0x00, 0x12, 0x6d, 0x12, 0x34, 0xff};
   dst[5] = board;
   struct sockaddr_ll dstaddr;
   dstaddr.sll_family = AF_PACKET;
   dstaddr.sll_protocol = htons(ETH_P_ALL);
   dstaddr.sll_ifindex = if_index;
   dstaddr.sll_hatype = 0;
   dstaddr.sll_pkttype = 0;
   dstaddr.sll_halen = ETH_ALEN;
   memcpy(dstaddr.sll_addr, dst, ETH_ALEN);
   // format a packet
   unsigned char packet[512];
   memcpy(&packet[0], dst, ETH_ALEN);
   memcpy(&packet[6], src, ETH_ALEN);
   // protocol
   packet[12] = 0x0b;
   packet[13] = 0x04;
   // the content
   packet[14] = (fadc << 5) | reg;
   packet[15] = (value >> 56) & 0xff;
   packet[16] = (value >> 48) & 0xff;
   packet[17] = (value >> 40) & 0xff;
   packet[18] = (value >> 32) & 0xff;
   packet[19] = (value >> 24) & 0xff;
   packet[20] = (value >> 16) & 0xff;
   packet[21] = (value >>  8) & 0xff;
   packet[22] = (value      ) & 0xff;
   int packet_length = 512;
   if(sendto(packet_socket, packet, packet_length, 0, (const sockaddr *) &dstaddr, sizeof(dstaddr)) < 0) {
     perror("sendto");
   }
 }
void setupRegs ()
Definition at line 283 of file new_fadc_2007_07_17.cpp.
References board, crate_number, enabled, fadc_board::enabled, i, max_boards, odb_find_key(), odb_get_bool(), odb_get_int(), printf(), and setReg().
 {
   for(int i = 0; i < max_boards; i++) {
     // If no settings exist for the board, disable it.
     if(!odb_find_key("/Equipment/Crate %d/Settings/NFADC %02x",
                      crate_number, i)) {
       board[i].enabled = false;
       continue;
     }
     printf("Found board %02x\n", i);
     bool enabled =
       odb_get_bool("/Equipment/Crate %d/Settings/NFADC %02x/Enabled",
                    crate_number, i);
     board[i].enabled = enabled;
     for(int chan = 0; chan < 8; chan++) {
       int led_mode =
         odb_get_int("/Equipment/Crate %d/Settings/NFADC %02x/Channel %d/LED Mode",
                     crate_number, i, chan);
       int lower_threshold =
         odb_get_int("/Equipment/Crate %d/Settings/NFADC %02x/Channel %d/Lower threshold",
                      crate_number, i, chan);
       int upper_threshold =
         odb_get_int("/Equipment/Crate %d/Settings/NFADC %02x/Channel %d/Upper threshold",
                     crate_number, i, chan);
       int pulser_period =
         odb_get_int("/Equipment/Crate %d/Settings/NFADC %02x/Channel %d/Pulser period",
                     crate_number, i, chan);
       int trigger_mask =
         odb_get_int("/Equipment/Crate %d/Settings/NFADC %02x/Channel %d/Trigger mask",
                     crate_number, i, chan);
       int presamples =
         odb_get_int("/Equipment/Crate %d/Settings/NFADC %02x/Channel %d/Presamples",
                     crate_number, i, chan);
       int stretch_samples =
         odb_get_int("/Equipment/Crate %d/Settings/NFADC %02x/Channel %d/Stretch samples",
                   crate_number, i, chan);
       int dcm_phase =
         odb_get_int("/Equipment/Crate %d/Settings/NFADC %02x/Channel %d/DCM phase",
                   crate_number, i, chan);
       if(enabled) {
         unsigned long long r0;
         if(i == 0xff) {
           r0 = (lower_threshold & 0xfff) |
                ((upper_threshold & 0xfff) << 12) |
                ((trigger_mask & 0xf) << 24) |
                ((presamples & 0xf) << 28) |
                (((unsigned long long) (stretch_samples & 0xff)) << 32);
         } else {
           r0 = (lower_threshold & 0xfff) |
                ((upper_threshold & 0xfff) << 12) |
                ((trigger_mask & 0xf) << 24) |
                ((presamples & 0xfff) << 28) |
                (((unsigned long long) (stretch_samples & 0xfff)) << 40);
         }
         unsigned long long r1 =
            (pulser_period & 0xffffffff) |
            (((unsigned long long) (led_mode & 0xf)) << 32);
         unsigned long long r2 = dcm_phase;
         int frontend = chan/2;
         if(i == 0xff) {
           if(frontend == 1) {
             frontend = 2;
           } else if(frontend == 2) {
             frontend = 1;
           }
         }
         if(chan % 2 == 0) {
           setReg("eth1", i, frontend, 0, r0);
           setReg("eth1", i, frontend, 1, r1);
           setReg("eth1", i, frontend, 4, r2);
         } else {
           setReg("eth1", i, frontend, 2, r0);
           setReg("eth1", i, frontend, 3, r1);
           setReg("eth1", i, frontend, 5, r2);
         }
       }
     }
   }
 }
Variable Documentation
struct fadc_board board[max_boards]
Definition at line 86 of file new_fadc_2007_07_17.cpp.
bool frame_examined[NUM_FRAMES]
Definition at line 40 of file new_fadc_2007_07_17.cpp.
const int FRAME_SIZE = 2048
Definition at line 36 of file new_fadc_2007_07_17.cpp.
const int max_boards = 256
Definition at line 72 of file new_fadc_2007_07_17.cpp.
struct readout_module new_fadc_module
Initial value:
= {
  NULL,
  NULL,
  NULL,
  new_fadc_bor,
  new_fadc_eor,
  NULL,
  NULL,
  NULL,
  NULL,
  new_fadc_read,
}
Definition at line 42 of file new_fadc_2007_07_17.cpp.
const int NUM_FRAMES = 2048
Definition at line 37 of file new_fadc_2007_07_17.cpp.
int packet_socket
Definition at line 57 of file new_fadc_2007_07_17.cpp.
unsigned char* packet_space = 0
Definition at line 39 of file new_fadc_2007_07_17.cpp.
const int TP_BLOCK_SIZE = 8192
Definition at line 34 of file new_fadc_2007_07_17.cpp.
const int TP_NUM_BLOCKS = 512
Definition at line 35 of file new_fadc_2007_07_17.cpp.
struct timeval tv_start static
Definition at line 418 of file new_fadc_2007_07_17.cpp.