AlcapDAQ: midas/drivers/device/nitronic.c File Reference
midas/drivers/device/nitronic.c File Reference
#include <stdio.h>
#include <math.h>
#include <stdarg.h>
#include "midas.h"
Data Structures
struct NITRONIC_SETTINGS
struct NITRONIC_INFO
Defines
#define NITRONIC_SETTINGS_STR "\Address = INT : 0\n\"
Functions
void nitronic_switch (NITRONIC_INFO *info)
INT nitronic_init (HNDLE hkey, void **pinfo, INT channels, INT(*bd)(INT cmd,...))
INT nitronic_exit (NITRONIC_INFO *info)
INT nitronic_set (NITRONIC_INFO *info, INT channel, float value)
INT nitronic_set_all (NITRONIC_INFO *info, INT channels, float value)
INT nitronic_get (NITRONIC_INFO *info, INT channel, float *pvalue)
INT nitronic_get_current (NITRONIC_INFO *info, INT channel, float *pvalue)
INT nitronic_get_all (NITRONIC_INFO *info, INT channels, float *array)
INT nitronic_get_current_all (NITRONIC_INFO *info, INT channels, float *array)
INT nitronic_set_current_limit (NITRONIC_INFO *info, float limit)
INT nitronic (INT cmd,...)
Define Documentation
#define NITRONIC_SETTINGS_STR "\Address = INT : 0\n\"
Definition at line 46 of file nitronic.c.
Referenced by nitronic_init().
Function Documentation
INT nitronic (INT cmd, ...)
Definition at line 285 of file nitronic.c.
References channel, cm_msg, CMD_EXIT, CMD_GET, CMD_GET_ALL, CMD_GET_CURRENT, CMD_GET_CURRENT_ALL, CMD_GET_DEFAULT_NAME, CMD_INIT, CMD_SET, CMD_SET_ALL, CMD_SET_CURRENT_LIMIT, CMD_SET_CURRENT_LIMIT_ALL, CMD_SET_LABEL, FE_ERR_DRIVER, FE_SUCCESS, hKey, MERROR, nitronic_exit(), nitronic_get(), nitronic_get_all(), nitronic_get_current(), nitronic_init(), nitronic_set(), nitronic_set_all(), nitronic_set_current_limit(), status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, flags, status;
   float value, *pvalue;
   void *info, *bd;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      flags = va_arg(argptr, INT);
      bd = va_arg(argptr, void *);
      status = nitronic_init(hKey, info, channel, bd);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = nitronic_exit(info);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = nitronic_set(info, channel, value);
      break;
   case CMD_SET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue   =  va_arg(argptr, float *);
      status = nitronic_set_all(info, channel, *pvalue);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue  = va_arg(argptr, float*);
      status = nitronic_get(info, channel, pvalue);
      break;
   case CMD_GET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = nitronic_get_all(info, channel, pvalue);
      break;
   case CMD_GET_CURRENT:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = nitronic_get_current(info, channel, pvalue);
      break;
   case CMD_GET_CURRENT_ALL:
      break;
   case CMD_SET_CURRENT_LIMIT:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      if (channel == 0)         /* one one limit for all channels */
         status = nitronic_set_current_limit(info, value);
      else
         status = FE_SUCCESS;
      break;
    case CMD_SET_LABEL:
      status = FE_SUCCESS;
      break;
    case CMD_GET_DEFAULT_NAME:
      status = FE_SUCCESS;
      break;
    case CMD_SET_CURRENT_LIMIT_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float*);
      status = nitronic_set_current_limit(info, pvalue[0]);
      break;
   default:
      cm_msg(MERROR, "nitronic device driver", "Received unknown command %d", cmd);
      status = FE_ERR_DRIVER;
      break;
   }
   va_end(argptr);
   return status;
}
INT nitronic_exit (NITRONIC_INFO * info)
Definition at line 140 of file nitronic.c.
References NITRONIC_INFO::bd, NITRONIC_INFO::bd_info, CMD_EXIT, and FE_SUCCESS.
Referenced by nitronic().
{
   info->bd(CMD_EXIT, info->bd_info);
   free(info);
   return FE_SUCCESS;
}
INT nitronic_get (NITRONIC_INFO * info, INT channel, float * pvalue)
Definition at line 184 of file nitronic.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, nitronic_switch(), and value.
Referenced by nitronic().
{
   int value;
   char str[256];
   nitronic_switch(info);
   sprintf(str, "CH%02dL", channel + 1);
   BD_PUTS(str);
   BD_GETS(str, sizeof(str), "+", 3000);
   sscanf(str + 14, "%d", &value);
   *pvalue = (float) value;
   return FE_SUCCESS;
}
INT nitronic_get_all (NITRONIC_INFO * info, INT channels, float * array)
Definition at line 222 of file nitronic.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, i, nitronic_switch(), and value.
Referenced by nitronic().
{
   int value, i;
   char str[256];
   nitronic_switch(info);
   BD_PUTS("CH01A");
   BD_GETS(str, sizeof(str), "\r", 5000);
   for (i = 0; i < 32; i++) {
      BD_GETS(str, sizeof(str), "\r", 5000);
      if (i < channels) {
         sscanf(str + 12, "%d", &value);
         array[i] = (float) value;
      }
   }
   BD_GETS(str, sizeof(str), "+", 2000);
   return FE_SUCCESS;
}
INT nitronic_get_current (NITRONIC_INFO * info, INT channel, float * pvalue)
Definition at line 203 of file nitronic.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, nitronic_switch(), and value.
Referenced by nitronic().
{
   int value;
   char str[256];
   nitronic_switch(info);
   sprintf(str, "CH%02dL", channel + 1);
   BD_PUTS(str);
   BD_GETS(str, sizeof(str), "+", 3000);
   sscanf(str + 19, "%d", &value);
   *pvalue = (float) value;
   return FE_SUCCESS;
}
INT nitronic_get_current_all (NITRONIC_INFO * info, INT channels, float * array)
Definition at line 246 of file nitronic.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, i, nitronic_switch(), and value.
{
   int value, i;
   char str[256];
   nitronic_switch(info);
   BD_PUTS("CH01A");
   BD_GETS(str, sizeof(str), "\r", 5000);
   for (i = 0; i < 32; i++) {
      BD_GETS(str, sizeof(str), "\r", 5000);
      if (i < channels) {
         sscanf(str + 19, "%d", &value);
         array[i] = (float) value;
      }
   }
   BD_GETS(str, sizeof(str), "+", 2000);
   return FE_SUCCESS;
}
INT nitronic_init (HNDLE hkey, void ** pinfo, INT channels, INT(*)(INT cmd,...) bd)
Definition at line 82 of file nitronic.c.
References NITRONIC_SETTINGS::address, NITRONIC_INFO::bd, BD_GETS, NITRONIC_INFO::bd_info, BD_PUTS, cm_get_experiment_database(), cm_msg, CMD_DEBUG, CMD_INIT, db_create_record(), db_find_key(), db_get_record(), DB_SUCCESS, FALSE, FE_ERR_HW, FE_ERR_ODB, FE_SUCCESS, hDB, MERROR, NITRONIC_SETTINGS_STR, NITRONIC_INFO::num_channels, NITRONIC_INFO::settings, size, status, and SUCCESS.
Referenced by nitronic().
{
   int status, size;
   char str[256];
   HNDLE hDB, hkeydd;
   NITRONIC_INFO *info;
   /* allocate info structure */
   info = (NITRONIC_INFO *) calloc(1, sizeof(NITRONIC_INFO));
   *pinfo = info;
   cm_get_experiment_database(&hDB, NULL);
   /* create NITRONIC settings record */
   status = db_create_record(hDB, hkey, "DD", NITRONIC_SETTINGS_STR);
   if (status != DB_SUCCESS)
      return FE_ERR_ODB;
   db_find_key(hDB, hkey, "DD", &hkeydd);
   size = sizeof(info->settings);
   db_get_record(hDB, hkeydd, &info->settings, &size, 0);
   info->num_channels = channels;
   info->bd = bd;
   /* initialize bus driver */
   if (!bd)
      return FE_ERR_ODB;
   status = bd(CMD_INIT, hkey, &info->bd_info);
   if (status != SUCCESS)
      return status;
   bd(CMD_DEBUG, FALSE);
   /* check if module is living  */
   sprintf(str, "M%02d", info->settings.address);
   BD_PUTS(str);
   status = BD_GETS(str, sizeof(str), "\r+", 2000);
   if (!status) {
      cm_msg(MERROR, "nitronic_init",
             "NITRONIC adr %d doesn't respond. Check power and RS232 connection.",
             info->settings.address);
      return FE_ERR_HW;
   }
   /* turn on HV main switch */
   BD_PUTS("ONA");
   BD_GETS(str, sizeof(str), "\r+", 5000);
   BD_PUTS("M16\r\n");
   return FE_SUCCESS;
}
INT nitronic_set (NITRONIC_INFO * info, INT channel, float value)
Definition at line 151 of file nitronic.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, and nitronic_switch().
Referenced by nitronic().
{
   char str[80];
   nitronic_switch(info);
   sprintf(str, "UCH%02d%04.0fL", channel + 1, value);
   BD_PUTS(str);
   BD_GETS(str, sizeof(str), "+", 3000);
   return FE_SUCCESS;
}
INT nitronic_set_all (NITRONIC_INFO * info, INT channels, float value)
Definition at line 166 of file nitronic.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, i, and nitronic_switch().
Referenced by nitronic().
{
   char str[80];
   INT i;
   nitronic_switch(info);
   for (i = 0; i < channels; i++) {
      sprintf(str, "UCH%02d%04.0fL", i + 1, value);
      BD_PUTS(str);
      BD_GETS(str, sizeof(str), "+", 3000);
   }
   return FE_SUCCESS;
}
INT nitronic_set_current_limit (NITRONIC_INFO * info, float limit)
Definition at line 270 of file nitronic.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, and nitronic_switch().
Referenced by nitronic().
{
   char str[256];
   nitronic_switch(info);
   sprintf(str, "ICH01%04dA", (int) limit);
   BD_PUTS(str);
   BD_GETS(str, sizeof(str), "\r+", 5000);
   return FE_SUCCESS;
}
void nitronic_switch (NITRONIC_INFO * info)
Definition at line 59 of file nitronic.c.
References NITRONIC_SETTINGS::address, BD_GETS, BD_PUTS, cm_msg, MERROR, NITRONIC_INFO::settings, and status.
Referenced by nitronic_get(), nitronic_get_all(), nitronic_get_current(), nitronic_get_current_all(), nitronic_set(), nitronic_set_all(), and nitronic_set_current_limit().
{
   static INT last_address = -1;
   char str[80];
   INT status;
   if (info->settings.address != last_address) {
      sprintf(str, "M%02d", info->settings.address);
      BD_PUTS(str);
      status = BD_GETS(str, sizeof(str), "\r+", 5000);
      if (!status) {
         cm_msg(MERROR, "nitronic_switch",
                "NITRONIC adr %d doesn't respond. Check power and RS232 connection.",
                info->settings.address);
         return;
      }
      last_address = info->settings.address;
   }
}