AlcapDAQ: midas/drivers/bus/null.h File Reference
midas/drivers/bus/null.h File Reference
Functions
INT null (INT cmd,...)
Function Documentation
INT null (INT cmd, ...)
Definition at line 241 of file null.c.
References CMD_DEBUG, CMD_EXIT, CMD_GETS, CMD_INIT, CMD_NAME, CMD_PUTS, CMD_READ, CMD_WRITE, debug_flag, FE_SUCCESS, null_exit(), null_gets(), null_init(), null_puts(), null_read(), null_write(), size, status, and timeout.
{
   va_list argptr;
   HNDLE hkey;
   INT status, size, timeout;
   void *info;
   char *str, *pattern;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hkey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      status = null_init(hkey, info);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = null_exit(info);
      break;
   case CMD_NAME:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      strcpy(str, "null");
      break;
   case CMD_WRITE:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, int);
      status = null_write(info, str, size);
      break;
   case CMD_READ:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, INT);
      timeout = va_arg(argptr, INT);
      status = null_read(info, str, size, timeout);
      break;
   case CMD_PUTS:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      status = null_puts(info, str);
      break;
   case CMD_GETS:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, INT);
      pattern = va_arg(argptr, char *);
      timeout = va_arg(argptr, INT);
      status = null_gets(info, str, size, pattern, timeout);
      break;
   case CMD_DEBUG:
      status = va_arg(argptr, INT);
      debug_flag = status;
      break;
   }
   va_end(argptr);
   return status;
}