AlcapDAQ: analyzer/work/onlineana/DataLibraryDict.cpp File Reference
DataLibraryDict.cpp File Reference
#include "RConfig.h"
#include "DataLibraryDict.h"
#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"
#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"
#include <new>
Data Structures
class G__Sizep2memfuncDataLibraryDict
class G__cpp_setup_initDataLibraryDict
Namespaces
ROOT
ROOT::Shadow
Constant Groups
ROOT
ROOT::Shadow
Macros
#define R__DICTIONARY_FILENAME DataLibraryDict
#define private public
#define protected public
#define G__ROOT
Typedefs
typedef TSetupData G__TTSetupData
typedef map< string, string,
less< string >, allocator
< pair< const string, string > > > G__TmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR
typedef pair< string, string > G__TpairlEstringcOstringgR
typedef map< string, string,
less< string >, allocator
< pair< const string, string >
> >::iterator G__TmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator
typedef TPulseIsland G__TTPulseIsland
typedef TGlobalData G__TTGlobalData
typedef vector< TPulseIsland
*, allocator< TPulseIsland * > > G__TvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR
typedef vector< TPulseIsland
*, allocator< TPulseIsland * >
>::iterator G__TvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator
typedef map< string, vector
< TPulseIsland *, allocator
< TPulseIsland * > >, less
< string >, allocator< pair
< const string, vector
< TPulseIsland *, allocator
< TPulseIsland * > > > > > G__TmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR
typedef pair< string, vector
< TPulseIsland *, allocator
< TPulseIsland * > > > G__TpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR
typedef map< string, vector
< TPulseIsland *, allocator
< TPulseIsland * > >, less
< string >, allocator< pair
< const string, vector
< TPulseIsland *, allocator
< TPulseIsland * >
> > > >::iterator G__TmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator
typedef TAnalysedPulse G__TTAnalysedPulse
typedef TDetectorPulse G__TTDetectorPulse
typedef TVacuumData G__TTVacuumData
typedef vector< TAnalysedPulse
*, allocator< TAnalysedPulse * > > G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR
typedef vector< TAnalysedPulse
*, allocator< TAnalysedPulse * >
>::iterator G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator
typedef map< string, vector
< TAnalysedPulse *, allocator
< TAnalysedPulse * > >, less
< string >, allocator< pair
< const string, vector
< TAnalysedPulse *, allocator
< TAnalysedPulse * > > > > > G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR
typedef pair< string, vector
< TAnalysedPulse *, allocator
< TAnalysedPulse * > > > G__TpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR
typedef map< string, vector
< TAnalysedPulse *, allocator
< TAnalysedPulse * > >, less
< string >, allocator< pair
< const string, vector
< TAnalysedPulse *, allocator
< TAnalysedPulse * >
> > > >::iterator G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator
Functions
void ROOT::TSetupData_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TSetupData (void *p=0)
static void * ROOT::newArray_TSetupData (Long_t size, void *p)
static void ROOT::delete_TSetupData (void *p)
static void ROOT::deleteArray_TSetupData (void *p)
static void ROOT::destruct_TSetupData (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TSetupData *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TSetupData *)
::ROOT::TGenericClassInfo * ROOT::_R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const pair<string,string>*)0x0)
ROOT::R__UseDummy (_R__UNIQUE_(Init))
void ROOT::pairlEstringcOstringgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::pairlEstringcOstringgR_Dictionary ()
static void * ROOT::new_pairlEstringcOstringgR (void *p=0)
static void * ROOT::newArray_pairlEstringcOstringgR (Long_t size, void *p)
static void ROOT::delete_pairlEstringcOstringgR (void *p)
static void ROOT::deleteArray_pairlEstringcOstringgR (void *p)
static void ROOT::destruct_pairlEstringcOstringgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const pair< string, string > *)
TGenericClassInfo * ROOT::GenerateInitInstance (const pair< string, string > *)
void ROOT::maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator_Dictionary ()
static void * ROOT::new_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p=0)
static void * ROOT::newArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void ROOT::delete_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static void ROOT::deleteArray_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static void ROOT::destruct_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::map< string, string, less< string >, allocator< pair< const string, string > > >::iterator *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::map< string, string, less< string >, allocator< pair< const string, string > > >::iterator *)
void ROOT::TPulseIsland_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TPulseIsland (void *p=0)
static void * ROOT::newArray_TPulseIsland (Long_t size, void *p)
static void ROOT::delete_TPulseIsland (void *p)
static void ROOT::deleteArray_TPulseIsland (void *p)
static void ROOT::destruct_TPulseIsland (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TPulseIsland *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TPulseIsland *)
void ROOT::TGlobalData_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TGlobalData (void *p=0)
static void * ROOT::newArray_TGlobalData (Long_t size, void *p)
static void ROOT::delete_TGlobalData (void *p)
static void ROOT::deleteArray_TGlobalData (void *p)
static void ROOT::destruct_TGlobalData (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TGlobalData *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TGlobalData *)
void ROOT::vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator_Dictionary ()
static void * ROOT::new_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p=0)
static void * ROOT::newArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (Long_t size, void *p)
static void ROOT::delete_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static void ROOT::deleteArray_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static void ROOT::destruct_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::vector< TPulseIsland *, allocator< TPulseIsland * > >::iterator *)
void ROOT::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR_Dictionary ()
static void * ROOT::new_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p=0)
static void * ROOT::newArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (Long_t size, void *p)
static void ROOT::delete_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static void ROOT::deleteArray_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static void ROOT::destruct_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *)
TGenericClassInfo * ROOT::GenerateInitInstance (const pair< string, vector< TPulseIsland *, allocator< TPulseIsland * > > > *)
void ROOT::maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary ()
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p=0)
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::map< string, vector< TPulseIsland *, allocator< TPulseIsland * > >, less< string >, allocator< pair< const string, vector< TPulseIsland *, allocator< TPulseIsland * > > > > >::iterator *)
void ROOT::TAnalysedPulse_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TAnalysedPulse (void *p=0)
static void * ROOT::newArray_TAnalysedPulse (Long_t size, void *p)
static void ROOT::delete_TAnalysedPulse (void *p)
static void ROOT::deleteArray_TAnalysedPulse (void *p)
static void ROOT::destruct_TAnalysedPulse (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TAnalysedPulse *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TAnalysedPulse *)
void ROOT::TDetectorPulse_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TDetectorPulse (void *p=0)
static void * ROOT::newArray_TDetectorPulse (Long_t size, void *p)
static void ROOT::delete_TDetectorPulse (void *p)
static void ROOT::deleteArray_TDetectorPulse (void *p)
static void ROOT::destruct_TDetectorPulse (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TDetectorPulse *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TDetectorPulse *)
void ROOT::TVacuumData_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TVacuumData (void *p=0)
static void * ROOT::newArray_TVacuumData (Long_t size, void *p)
static void ROOT::delete_TVacuumData (void *p)
static void ROOT::deleteArray_TVacuumData (void *p)
static void ROOT::destruct_TVacuumData (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TVacuumData *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TVacuumData *)
void ROOT::vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_Dictionary ()
static void * ROOT::new_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p=0)
static void * ROOT::newArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (Long_t size, void *p)
static void ROOT::delete_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static void ROOT::deleteArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static void ROOT::destruct_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >::iterator *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >::iterator *)
void ROOT::pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_Dictionary ()
static void * ROOT::new_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p=0)
static void * ROOT::newArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (Long_t size, void *p)
static void ROOT::delete_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static void ROOT::deleteArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static void ROOT::destruct_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const pair< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > *)
TGenericClassInfo * ROOT::GenerateInitInstance (const pair< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > *)
void ROOT::maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary ()
static void * ROOT::new_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p=0)
static void * ROOT::newArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void ROOT::delete_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void ROOT::deleteArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void ROOT::destruct_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::map< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >, less< string >, allocator< pair< const string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > > >::iterator *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::map< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >, less< string >, allocator< pair< const string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > > >::iterator *)
void ROOT::maplEstringcOdoublegR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOdoublegR_Dictionary ()
static void * ROOT::new_maplEstringcOdoublegR (void *p=0)
static void * ROOT::newArray_maplEstringcOdoublegR (Long_t size, void *p)
static void ROOT::delete_maplEstringcOdoublegR (void *p)
static void ROOT::deleteArray_maplEstringcOdoublegR (void *p)
static void ROOT::destruct_maplEstringcOdoublegR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< string, double > *)
void ROOT::maplEstringcOintgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOintgR_Dictionary ()
static void * ROOT::new_maplEstringcOintgR (void *p=0)
static void * ROOT::newArray_maplEstringcOintgR (Long_t size, void *p)
static void ROOT::delete_maplEstringcOintgR (void *p)
static void ROOT::deleteArray_maplEstringcOintgR (void *p)
static void ROOT::destruct_maplEstringcOintgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< string, int > *)
void ROOT::maplEstringcOstringgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOstringgR_Dictionary ()
static void * ROOT::new_maplEstringcOstringgR (void *p=0)
static void * ROOT::newArray_maplEstringcOstringgR (Long_t size, void *p)
static void ROOT::delete_maplEstringcOstringgR (void *p)
static void ROOT::deleteArray_maplEstringcOstringgR (void *p)
static void ROOT::destruct_maplEstringcOstringgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< string, string > *)
void ROOT::maplEstringcOvectorlETAnalysedPulsemUgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOvectorlETAnalysedPulsemUgRsPgR_Dictionary ()
static void * ROOT::new_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p=0)
static void * ROOT::newArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (Long_t size, void *p)
static void ROOT::delete_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static void ROOT::deleteArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static void ROOT::destruct_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< string, vector< TAnalysedPulse * > > *)
void ROOT::maplEstringcOvectorlETPulseIslandmUgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOvectorlETPulseIslandmUgRsPgR_Dictionary ()
static void * ROOT::new_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p=0)
static void * ROOT::newArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (Long_t size, void *p)
static void ROOT::delete_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void ROOT::deleteArray_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static void ROOT::destruct_maplEstringcOvectorlETPulseIslandmUgRsPgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< string, vector< TPulseIsland * > > *)
void ROOT::vectorlETAnalysedPulsemUgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::vectorlETAnalysedPulsemUgR_Dictionary ()
static void * ROOT::new_vectorlETAnalysedPulsemUgR (void *p=0)
static void * ROOT::newArray_vectorlETAnalysedPulsemUgR (Long_t size, void *p)
static void ROOT::delete_vectorlETAnalysedPulsemUgR (void *p)
static void ROOT::deleteArray_vectorlETAnalysedPulsemUgR (void *p)
static void ROOT::destruct_vectorlETAnalysedPulsemUgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const vector< TAnalysedPulse * > *)
void ROOT::vectorlETPulseIslandmUgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::vectorlETPulseIslandmUgR_Dictionary ()
static void * ROOT::new_vectorlETPulseIslandmUgR (void *p=0)
static void * ROOT::newArray_vectorlETPulseIslandmUgR (Long_t size, void *p)
static void ROOT::delete_vectorlETPulseIslandmUgR (void *p)
static void ROOT::deleteArray_vectorlETPulseIslandmUgR (void *p)
static void ROOT::destruct_vectorlETPulseIslandmUgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const vector< TPulseIsland * > *)
void ROOT::vectorlEfloatgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::vectorlEfloatgR_Dictionary ()
static void * ROOT::new_vectorlEfloatgR (void *p=0)
static void * ROOT::newArray_vectorlEfloatgR (Long_t size, void *p)
static void ROOT::delete_vectorlEfloatgR (void *p)
static void ROOT::deleteArray_vectorlEfloatgR (void *p)
static void ROOT::destruct_vectorlEfloatgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const vector< float > *)
void ROOT::vectorlEintgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::vectorlEintgR_Dictionary ()
static void * ROOT::new_vectorlEintgR (void *p=0)
static void * ROOT::newArray_vectorlEintgR (Long_t size, void *p)
static void ROOT::delete_vectorlEintgR (void *p)
static void ROOT::deleteArray_vectorlEintgR (void *p)
static void ROOT::destruct_vectorlEintgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const vector< int > *)
void G__cpp_reset_tagtableDataLibraryDict ()
void G__set_cpp_environmentDataLibraryDict ()
int G__cpp_dllrevDataLibraryDict ()
static int G__DataLibraryDict_504_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_28 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_29 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_30 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_34 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_35 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_36 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_37 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_38 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_39 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_40 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_41 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_504_0_42 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_507_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_508_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_508_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_508_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_508_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_509_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_28 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_29 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_30 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_31 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_512_0_32 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_516_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_28 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_29 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_30 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_31 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_518_0_32 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_519_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_523_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_524_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_524_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_524_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_524_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_525_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_528_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_529_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_530_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_28 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_29 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_30 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_31 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_532_0_32 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_533_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_537_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_538_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_538_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_538_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_538_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict_539_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict__0_2003 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__DataLibraryDict__0_2080 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
size_t G__get_sizep2memfuncDataLibraryDict ()
void G__cpp_setup_inheritanceDataLibraryDict ()
void G__cpp_setup_typetableDataLibraryDict ()
static void G__setup_memvarTSetupData (void)
static void G__setup_memvarmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR (void)
static void G__setup_memvarpairlEstringcOstringgR (void)
static void G__setup_memvarmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void)
static void G__setup_memvarTPulseIsland (void)
static void G__setup_memvarTGlobalData (void)
static void G__setup_memvarvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR (void)
static void G__setup_memvarvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void)
static void G__setup_memvarmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR (void)
static void G__setup_memvarpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void)
static void G__setup_memvarmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void)
static void G__setup_memvarTAnalysedPulse (void)
static void G__setup_memvarTDetectorPulse (void)
static void G__setup_memvarTVacuumData (void)
static void G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR (void)
static void G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void)
static void G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR (void)
static void G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void)
static void G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void)
void G__cpp_setup_memvarDataLibraryDict ()
static void G__setup_memfuncTSetupData (void)
static void G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR (void)
static void G__setup_memfuncpairlEstringcOstringgR (void)
static void G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void)
static void G__setup_memfuncTPulseIsland (void)
static void G__setup_memfuncTGlobalData (void)
static void G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR (void)
static void G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void)
static void G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR (void)
static void G__setup_memfuncpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void)
static void G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void)
static void G__setup_memfuncTAnalysedPulse (void)
static void G__setup_memfuncTDetectorPulse (void)
static void G__setup_memfuncTVacuumData (void)
static void G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR (void)
static void G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void)
static void G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR (void)
static void G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void)
static void G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void)
void G__cpp_setup_memfuncDataLibraryDict ()
static void G__cpp_setup_global0 ()
static void G__cpp_setup_global1 ()
void G__cpp_setup_globalDataLibraryDict ()
static void G__cpp_setup_func0 ()
static void G__cpp_setup_func1 ()
static void G__cpp_setup_func2 ()
static void G__cpp_setup_func3 ()
static void G__cpp_setup_func4 ()
static void G__cpp_setup_func5 ()
static void G__cpp_setup_func6 ()
static void G__cpp_setup_func7 ()
static void G__cpp_setup_func8 ()
static void G__cpp_setup_func9 ()
static void G__cpp_setup_func10 ()
static void G__cpp_setup_func11 ()
static void G__cpp_setup_func12 ()
static void G__cpp_setup_func13 ()
static void G__cpp_setup_func14 ()
static void G__cpp_setup_func15 ()
static void G__cpp_setup_func16 ()
static void G__cpp_setup_func17 ()
static void G__cpp_setup_func18 ()
static void G__cpp_setup_func19 ()
static void G__cpp_setup_func20 ()
static void G__cpp_setup_func21 ()
void G__cpp_setup_funcDataLibraryDict ()
void G__cpp_setup_tagtableDataLibraryDict ()
void G__cpp_setupDataLibraryDict (void)
Variables
G__linked_taginfo G__DataLibraryDictLN_TClass = { "TClass" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TBuffer = { "TBuffer" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TObject = { "TObject" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_string = { "string" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_lesslEstringgR = { "less<string>" , 115 , -1 }
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TH1I = { "TH1I" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TSetupData = { "TSetupData" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOstringgRsPgR = { "allocator<pair<const string,string> >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_pairlEstringcOstringgR = { "pair<string,string>" , 115 , -1 }
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator = { "map<string,string,less<string>,allocator<pair<const string,string> > >::iterator" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLreverse_iterator = { "map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_pairlEmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<string,string,less<string>,allocator<pair<const string,string> > >::iterator,bool>" , 115 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TPulseIsland = { "TPulseIsland" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TGlobalData = { "TGlobalData" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR = { "vector<TPulseIsland*,allocator<TPulseIsland*> >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator = { "vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator>" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgR = { "allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR = { "pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >" , 115 , -1 }
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator = { "map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator = { "map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator,bool>" , 115 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TAnalysedPulse = { "TAnalysedPulse" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TDetectorPulse = { "TDetectorPulse" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_TVacuumData = { "TVacuumData" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR = { "vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator = { "vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator>" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR = { "allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR = { "pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >" , 115 , -1 }
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator" , 99 , -1 }
G__linked_taginfo G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator,bool>" , 115 , -1 }
G__cpp_setup_initDataLibraryDict G__cpp_setup_initializerDataLibraryDict
Macro Definition Documentation
#define G__ROOT
Definition at line 26 of file DataLibraryDict.cpp.
#define private public
Definition at line 11 of file DataLibraryDict.cpp.
#define protected public
Definition at line 12 of file DataLibraryDict.cpp.
#define R__DICTIONARY_FILENAME DataLibraryDict
Definition at line 7 of file DataLibraryDict.cpp.
Typedef Documentation
typedef map<string,string,less<string>,allocator<pair<const string,string> > > G__TmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR
Definition at line 2462 of file DataLibraryDict.cpp.
typedef map<string,string,less<string>,allocator<pair<const string,string> > >::iterator G__TmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator
Definition at line 2719 of file DataLibraryDict.cpp.
typedef map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > > G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR
Definition at line 5871 of file DataLibraryDict.cpp.
typedef map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator
Definition at line 6128 of file DataLibraryDict.cpp.
typedef map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > > G__TmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR
Definition at line 4064 of file DataLibraryDict.cpp.
typedef map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator G__TmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator
Definition at line 4321 of file DataLibraryDict.cpp.
typedef pair<string,string> G__TpairlEstringcOstringgR
Definition at line 2555 of file DataLibraryDict.cpp.
typedef pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > G__TpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR
Definition at line 5964 of file DataLibraryDict.cpp.
typedef pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > G__TpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR
Definition at line 4157 of file DataLibraryDict.cpp.
typedef TAnalysedPulse G__TTAnalysedPulse
Definition at line 4528 of file DataLibraryDict.cpp.
typedef TDetectorPulse G__TTDetectorPulse
Definition at line 4756 of file DataLibraryDict.cpp.
typedef TGlobalData G__TTGlobalData
Definition at line 3136 of file DataLibraryDict.cpp.
typedef TPulseIsland G__TTPulseIsland
Definition at line 2985 of file DataLibraryDict.cpp.
typedef TSetupData G__TTSetupData
Definition at line 2130 of file DataLibraryDict.cpp.
typedef TVacuumData G__TTVacuumData
Definition at line 4943 of file DataLibraryDict.cpp.
typedef vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR
Definition at line 5316 of file DataLibraryDict.cpp.
typedef vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator
Definition at line 5550 of file DataLibraryDict.cpp.
typedef vector<TPulseIsland*,allocator<TPulseIsland*> > G__TvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR
Definition at line 3509 of file DataLibraryDict.cpp.
typedef vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator G__TvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator
Definition at line 3743 of file DataLibraryDict.cpp.
Function Documentation
int G__cpp_dllrevDataLibraryDict ()
Definition at line 1862 of file DataLibraryDict.cpp.
 { return(30051515); }
void G__cpp_reset_tagtableDataLibraryDict ()
static void G__cpp_setup_func0 () static
Definition at line 7364 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
    G__lastifuncposition();
 }
static void G__cpp_setup_func1 () static
Definition at line 7369 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func10 () static
Definition at line 7396 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func11 () static
Definition at line 7399 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func12 () static
Definition at line 7402 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func13 () static
Definition at line 7405 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func14 () static
Definition at line 7408 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func15 () static
Definition at line 7411 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func16 () static
Definition at line 7414 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func17 () static
Definition at line 7417 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func18 () static
Definition at line 7420 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func19 () static
Definition at line 7423 of file DataLibraryDict.cpp.
References G__DataLibraryDict__0_2003().
Referenced by G__cpp_setup_funcDataLibraryDict().
{
    G__memfunc_setup("operator!=", 970, G__DataLibraryDict__0_2003, 103, -1, -1, 0, 2, 1, 1, 8,
 "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' - 11 - x u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' - 11 - y", (char*) NULL
 , (void*) NULL, 0);
 }
static void G__cpp_setup_func2 () static
Definition at line 7372 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func20 () static
Definition at line 7429 of file DataLibraryDict.cpp.
References G__DataLibraryDict__0_2080().
Referenced by G__cpp_setup_funcDataLibraryDict().
{
    G__memfunc_setup("operator!=", 970, G__DataLibraryDict__0_2080, 103, -1, -1, 0, 2, 1, 1, 8,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 11 - x u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 11 - y", (char*) NULL
 , (void*) NULL, 0);
 }
static void G__cpp_setup_func21 () static
Definition at line 7435 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
    G__resetifuncposition();
 }
static void G__cpp_setup_func3 () static
Definition at line 7375 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func4 () static
Definition at line 7378 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func5 () static
Definition at line 7381 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func6 () static
Definition at line 7384 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func7 () static
Definition at line 7387 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func8 () static
Definition at line 7390 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
static void G__cpp_setup_func9 () static
Definition at line 7393 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_funcDataLibraryDict().
{
 }
void G__cpp_setup_funcDataLibraryDict ()
Definition at line 7440 of file DataLibraryDict.cpp.
References G__cpp_setup_func0(), G__cpp_setup_func1(), G__cpp_setup_func10(), G__cpp_setup_func11(), G__cpp_setup_func12(), G__cpp_setup_func13(), G__cpp_setup_func14(), G__cpp_setup_func15(), G__cpp_setup_func16(), G__cpp_setup_func17(), G__cpp_setup_func18(), G__cpp_setup_func19(), G__cpp_setup_func2(), G__cpp_setup_func20(), G__cpp_setup_func21(), G__cpp_setup_func3(), G__cpp_setup_func4(), G__cpp_setup_func5(), G__cpp_setup_func6(), G__cpp_setup_func7(), G__cpp_setup_func8(), and G__cpp_setup_func9().
{
   G__cpp_setup_func0();
   G__cpp_setup_func1();
   G__cpp_setup_func2();
   G__cpp_setup_func3();
   G__cpp_setup_func4();
   G__cpp_setup_func5();
   G__cpp_setup_func6();
   G__cpp_setup_func7();
   G__cpp_setup_func8();
   G__cpp_setup_func9();
   G__cpp_setup_func10();
   G__cpp_setup_func11();
   G__cpp_setup_func12();
   G__cpp_setup_func13();
   G__cpp_setup_func14();
   G__cpp_setup_func15();
   G__cpp_setup_func16();
   G__cpp_setup_func17();
   G__cpp_setup_func18();
   G__cpp_setup_func19();
   G__cpp_setup_func20();
   G__cpp_setup_func21();
 }
static void G__cpp_setup_global0 () static
Definition at line 7345 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_globalDataLibraryDict().
{
    /* Setting up global variables */
    G__resetplocal();
 }
static void G__cpp_setup_global1 () static
Definition at line 7352 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_globalDataLibraryDict().
{
    G__resetglobalenv();
 }
void G__cpp_setup_globalDataLibraryDict ()
Definition at line 7356 of file DataLibraryDict.cpp.
References G__cpp_setup_global0(), and G__cpp_setup_global1().
{
   G__cpp_setup_global0();
   G__cpp_setup_global1();
 }
void G__cpp_setup_inheritanceDataLibraryDict ()
Definition at line 6254 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TAnalysedPulse, G__DataLibraryDictLN_TDetectorPulse, G__DataLibraryDictLN_TGlobalData, G__DataLibraryDictLN_TObject, G__DataLibraryDictLN_TPulseIsland, G__DataLibraryDictLN_TSetupData, and G__DataLibraryDictLN_TVacuumData.
{
    /* Setting up class inheritance */
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DataLibraryDictLN_TSetupData))) {
      TSetupData *G__Lderived;
      G__Lderived=(TSetupData*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TSetupData),G__get_linked_tagnum(&G__DataLibraryDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland))) {
      TPulseIsland *G__Lderived;
      G__Lderived=(TPulseIsland*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland),G__get_linked_tagnum(&G__DataLibraryDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DataLibraryDictLN_TGlobalData))) {
      TGlobalData *G__Lderived;
      G__Lderived=(TGlobalData*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TGlobalData),G__get_linked_tagnum(&G__DataLibraryDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse))) {
      TAnalysedPulse *G__Lderived;
      G__Lderived=(TAnalysedPulse*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),G__get_linked_tagnum(&G__DataLibraryDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DataLibraryDictLN_TDetectorPulse))) {
      TDetectorPulse *G__Lderived;
      G__Lderived=(TDetectorPulse*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TDetectorPulse),G__get_linked_tagnum(&G__DataLibraryDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DataLibraryDictLN_TVacuumData))) {
      TVacuumData *G__Lderived;
      G__Lderived=(TVacuumData*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TVacuumData),G__get_linked_tagnum(&G__DataLibraryDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
 }
void G__cpp_setup_memfuncDataLibraryDict ()
Definition at line 7339 of file DataLibraryDict.cpp.
{
 }
void G__cpp_setup_memvarDataLibraryDict ()
Definition at line 6718 of file DataLibraryDict.cpp.
{
 }
void G__cpp_setup_tagtableDataLibraryDict ()
Definition at line 7571 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOstringgRsPgR, G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR, G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgR, G__DataLibraryDictLN_lesslEstringgR, G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator, G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLreverse_iterator, G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator, G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator, G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator, G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator, G__DataLibraryDictLN_pairlEmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiteratorcOboolgR, G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR, G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR, G__DataLibraryDictLN_pairlEstringcOstringgR, G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR, G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR, G__DataLibraryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR, G__DataLibraryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR, G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR, G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR, G__DataLibraryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR, G__DataLibraryDictLN_string, G__DataLibraryDictLN_TAnalysedPulse, G__DataLibraryDictLN_TBuffer, G__DataLibraryDictLN_TClass, G__DataLibraryDictLN_TDetectorPulse, G__DataLibraryDictLN_TGlobalData, G__DataLibraryDictLN_TH1I, G__DataLibraryDictLN_TMemberInspector, G__DataLibraryDictLN_TObject, G__DataLibraryDictLN_TPulseIsland, G__DataLibraryDictLN_TSetupData, G__DataLibraryDictLN_TVacuumData, G__DataLibraryDictLN_TVectorTlEdoublegR, G__DataLibraryDictLN_TVectorTlEfloatgR, G__DataLibraryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR, G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR, G__DataLibraryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR, G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR, G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator, G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR, G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator, G__DataLibraryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR, G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR(), G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR(), G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), G__setup_memfuncpairlEstringcOstringgR(), G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), G__setup_memfuncpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), G__setup_memfuncTAnalysedPulse(), G__setup_memfuncTDetectorPulse(), G__setup_memfuncTGlobalData(), G__setup_memfuncTPulseIsland(), G__setup_memfuncTSetupData(), G__setup_memfuncTVacuumData(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR(), G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator(), G__setup_memvarmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR(), G__setup_memvarmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator(), G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR(), G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), G__setup_memvarmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR(), G__setup_memvarmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator(), G__setup_memvarpairlEstringcOstringgR(), G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), G__setup_memvarpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR(), G__setup_memvarTAnalysedPulse(), G__setup_memvarTDetectorPulse(), G__setup_memvarTGlobalData(), G__setup_memvarTPulseIsland(), G__setup_memvarTSetupData(), G__setup_memvarTVacuumData(), G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR(), G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), G__setup_memvarvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR(), and G__setup_memvarvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
{
    /* Setting up class,struct,union tag entry */
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TClass);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TBuffer);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TMemberInspector);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TObject);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_string);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_lesslEstringgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TVectorTlEfloatgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TVectorTlEdoublegR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TH1I);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TSetupData),sizeof(TSetupData),-1,290816,(char*)NULL,G__setup_memvarTSetupData,G__setup_memfuncTSetupData);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOstringgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),sizeof(map<string,string,less<string>,allocator<pair<const string,string> > >),-1,298752,(char*)NULL,G__setup_memvarmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR,G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_pairlEstringcOstringgR),sizeof(pair<string,string>),-1,297216,(char*)NULL,G__setup_memvarpairlEstringcOstringgR,G__setup_memfuncpairlEstringcOstringgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator),sizeof(map<string,string,less<string>,allocator<pair<const string,string> > >::iterator),-1,2816,(char*)NULL,G__setup_memvarmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator,G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLreverse_iterator);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_pairlEmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiteratorcOboolgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TPulseIsland),sizeof(TPulseIsland),-1,323840,(char*)NULL,G__setup_memvarTPulseIsland,G__setup_memfuncTPulseIsland);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TGlobalData),sizeof(TGlobalData),-1,290816,(char*)NULL,G__setup_memvarTGlobalData,G__setup_memfuncTGlobalData);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR),sizeof(vector<TPulseIsland*,allocator<TPulseIsland*> >),-1,298752,(char*)NULL,G__setup_memvarvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR,G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator),sizeof(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator),-1,35072,(char*)NULL,G__setup_memvarvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator,G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),sizeof(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >),-1,298752,(char*)NULL,G__setup_memvarmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR,G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR),sizeof(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >),-1,297216,(char*)NULL,G__setup_memvarpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR,G__setup_memfuncpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator),sizeof(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator),-1,2816,(char*)NULL,G__setup_memvarmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator,G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TAnalysedPulse),sizeof(TAnalysedPulse),-1,324864,(char*)NULL,G__setup_memvarTAnalysedPulse,G__setup_memfuncTAnalysedPulse);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TDetectorPulse),sizeof(TDetectorPulse),-1,324864,(char*)NULL,G__setup_memvarTDetectorPulse,G__setup_memfuncTDetectorPulse);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_TVacuumData),sizeof(TVacuumData),-1,323840,(char*)NULL,G__setup_memvarTVacuumData,G__setup_memfuncTVacuumData);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR),sizeof(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >),-1,298752,(char*)NULL,G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR,G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator),sizeof(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator),-1,35072,(char*)NULL,G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator,G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),sizeof(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >),-1,298752,(char*)NULL,G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR,G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR),sizeof(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >),-1,297216,(char*)NULL,G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR,G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator),sizeof(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator),-1,2816,(char*)NULL,G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator,G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator);
    G__get_linked_tagnum_fwd(&G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR);
 }
void G__cpp_setup_typetableDataLibraryDict ()
Definition at line 6310 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOstringgRsPgR, G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR, G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgR, G__DataLibraryDictLN_lesslEstringgR, G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator, G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLreverse_iterator, G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator, G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator, G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator, G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator, G__DataLibraryDictLN_pairlEstringcOstringgR, G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR, G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR, G__DataLibraryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR, G__DataLibraryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR, G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR, G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR, G__DataLibraryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR, G__DataLibraryDictLN_string, G__DataLibraryDictLN_TAnalysedPulse, G__DataLibraryDictLN_TPulseIsland, G__DataLibraryDictLN_TVectorTlEdoublegR, G__DataLibraryDictLN_TVectorTlEfloatgR, G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR, G__DataLibraryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR, G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR, G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator, G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR, G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator, and G__DataLibraryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.
{
    /* Setting up typedef entry */
    G__search_typename2("Version_t",115,-1,0,-1);
    G__setnewtype(-1,"Class version identifier (short)",0);
    G__search_typename2("Option_t",99,-1,256,-1);
    G__setnewtype(-1,"Option string (const char)",0);
    G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_TVectorTlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_TVectorTlEdoublegR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,std::string>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_string),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("mapped_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_string),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("value_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_compare",117,G__get_linked_tagnum(&G__DataLibraryDictLN_lesslEstringgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("allocator_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOstringgRsPgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLreverse_iterator),256,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,double>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,double>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,int>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,int>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TPulseIsland*>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("value_type",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("pointer",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland),256,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reference",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland),1,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reference",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland),257,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("pointer",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reference",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland),1,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reference",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland),1,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,std::vector<TPulseIsland*> >",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,std::vector<TPulseIsland*> >",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_string),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("mapped_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("value_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_compare",117,G__get_linked_tagnum(&G__DataLibraryDictLN_lesslEstringgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("allocator_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator),256,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string> >",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TPulseIsland*> >",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("pair<string,vector<TPulseIsland*> >",117,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TAnalysedPulse*>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("value_type",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("pointer",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),256,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reference",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),1,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reference",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),257,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("pointer",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reference",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),1,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reference",85,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),1,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TAnalysedPulse*> >",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_string),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("mapped_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("value_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_compare",117,G__get_linked_tagnum(&G__DataLibraryDictLN_lesslEstringgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("allocator_type",117,G__get_linked_tagnum(&G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR),0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator),256,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string> >",117,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("pair<string,vector<TAnalysedPulse*> >",117,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
 }
void G__cpp_setupDataLibraryDict (void)
Definition at line 7623 of file DataLibraryDict.cpp.
References G__cpp_setup_funcDataLibraryDict(), G__cpp_setup_globalDataLibraryDict(), G__cpp_setup_inheritanceDataLibraryDict(), G__cpp_setup_memfuncDataLibraryDict(), G__cpp_setup_memvarDataLibraryDict(), G__cpp_setup_tagtableDataLibraryDict(), G__cpp_setup_typetableDataLibraryDict(), G__get_sizep2memfuncDataLibraryDict(), and G__set_cpp_environmentDataLibraryDict().
{
   G__check_setup_version(30051515,"G__cpp_setupDataLibraryDict()");
   G__set_cpp_environmentDataLibraryDict();
   G__cpp_setup_tagtableDataLibraryDict();
   G__cpp_setup_inheritanceDataLibraryDict();
   G__cpp_setup_typetableDataLibraryDict();
   G__cpp_setup_memvarDataLibraryDict();
   G__cpp_setup_memfuncDataLibraryDict();
   G__cpp_setup_globalDataLibraryDict();
   G__cpp_setup_funcDataLibraryDict();
    if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDataLibraryDict();
   return;
 }
static int G__DataLibraryDict_504_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1869 of file DataLibraryDict.cpp.
References TSetupData::Instance().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 85, (long) TSetupData::Instance());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1938 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 105, (long) ((const TSetupData*) G__getstructoffset())->GetTriggerPolarity(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1944 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 105, (long) ((const TSetupData*) G__getstructoffset())->GetPedestal(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1950 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) ((TSetupData*) G__getstructoffset())->SetDetectorName(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1956 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetClockTick(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1963 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetNBits(*((string*) G__int(libp->para[0])), (int) G__int(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1970 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetTimeShift(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1977 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetTriggerPolarity(*((string*) G__int(libp->para[0])), (int) G__int(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1984 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetPedestal(*((string*) G__int(libp->para[0])), (int) G__int(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1991 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetADCSlopeCalib(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1998 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->SetADCOffsetCalib(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1875 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       {
          string* pobj;
          string xobj = ((TSetupData*) G__getstructoffset())->GetBankName(*((string*) G__int(libp->para[0])));
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2005 of file DataLibraryDict.cpp.
References TSetupData::IsFADC().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) TSetupData::IsFADC(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2011 of file DataLibraryDict.cpp.
References TSetupData::IsHoustonCAEN().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) TSetupData::IsHoustonCAEN(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2017 of file DataLibraryDict.cpp.
References TSetupData::IsBostonCAEN().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) TSetupData::IsBostonCAEN(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2023 of file DataLibraryDict.cpp.
References TSetupData::IsSlow().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) TSetupData::IsSlow(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2029 of file DataLibraryDict.cpp.
References TSetupData::IsFast().
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 103, (long) TSetupData::IsFast(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2035 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 85, (long) TSetupData::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_28 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2041 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 67, (long) TSetupData::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_29 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2047 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 115, (long) TSetupData::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1888 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       {
          string* pobj;
          string xobj = ((TSetupData*) G__getstructoffset())->GetDetectorName(*((string*) G__int(libp->para[0])));
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_30 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2053 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       TSetupData::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_34 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2060 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       ((TSetupData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_35 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2067 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 67, (long) TSetupData::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_36 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2073 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 105, (long) TSetupData::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_37 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2079 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 67, (long) TSetupData::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_38 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2085 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 105, (long) TSetupData::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_39 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2092 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TSetupData.
Referenced by G__setup_memfuncTSetupData().
 {
    TSetupData *p;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TSetupData[n];
      } else {
        p = new((void*) gvp) TSetupData[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TSetupData;
      } else {
        p = new((void*) gvp) TSetupData;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TSetupData));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1901 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       ((const TSetupData*) G__getstructoffset())->GetAllDetectors(*(map<std::string,std::string>*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_40 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2117 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TSetupData.
Referenced by G__setup_memfuncTSetupData().
 {
    TSetupData* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TSetupData(*(TSetupData*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TSetupData));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_41 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2131 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncTSetupData().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TSetupData*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TSetupData*) (soff+(sizeof(TSetupData)*i)))->~G__TTSetupData();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TSetupData*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TSetupData*) (soff))->~G__TTSetupData();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_42 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2168 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
    TSetupData* dest = (TSetupData*) G__getstructoffset();
    *dest = *(TSetupData*) libp->para[0].ref;
    const TSetupData& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1908 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letdouble(result7, 100, (double) ((const TSetupData*) G__getstructoffset())->GetClockTick(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1914 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letint(result7, 105, (long) ((const TSetupData*) G__getstructoffset())->GetNBits(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1920 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letdouble(result7, 100, (double) ((const TSetupData*) G__getstructoffset())->GetADCSlopeCalib(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1926 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letdouble(result7, 100, (double) ((const TSetupData*) G__getstructoffset())->GetADCOffsetCalib(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_504_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1932 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTSetupData().
 {
       G__letdouble(result7, 100, (double) ((const TSetupData*) G__getstructoffset())->GetTimeShift(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2180 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
    map<string,string,less<string>,allocator<pair<const string,string> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,string,less<string>,allocator<pair<const string,string> > >[n];
      } else {
        p = new((void*) gvp) map<string,string,less<string>,allocator<pair<const string,string> > >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,string,less<string>,allocator<pair<const string,string> > >;
      } else {
        p = new((void*) gvp) map<string,string,less<string>,allocator<pair<const string,string> > >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2314 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       G__letint(result7, 103, (long) ((const map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->empty());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2320 of file DataLibraryDict.cpp.
References size.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2326 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->max_size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2332 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       {
          const string& obj = ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->operator[](*(string*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2342 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       {
          pair<map<string,string,less<string>,allocator<pair<const string,string> > >::iterator,bool>* pobj;
          pair<map<string,string,less<string>,allocator<pair<const string,string> > >::iterator,bool> xobj = ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->insert(*(map<string,string,less<string>,allocator<pair<const string,string> > >::value_type*) libp->para[0].ref);
          pobj = new pair<map<string,string,less<string>,allocator<pair<const string,string> > >::iterator,bool>(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2355 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       {
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator* pobj;
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator xobj = ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->insert(*((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__int(libp->para[0])), *(map<string,string,less<string>,allocator<pair<const string,string> > >::value_type*) libp->para[1].ref);
          pobj = new map<string,string,less<string>,allocator<pair<const string,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2368 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->insert(*((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__int(libp->para[0])), *((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2375 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->insert(*((map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2382 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->erase(*((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__int(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2389 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->erase(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2204 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
    map<string,string,less<string>,allocator<pair<const string,string> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,string,less<string>,allocator<pair<const string,string> > >(*((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__int(libp->para[0])), *((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<string,string,less<string>,allocator<pair<const string,string> > >(*((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__int(libp->para[0])), *((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2395 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->erase(*((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__int(libp->para[0])), *((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2402 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->swap(*(map<string,string,less<string>,allocator<pair<const string,string> > >*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2409 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->clear();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2416 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       {
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator* pobj;
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator xobj = ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->find(*(string*) libp->para[0].ref);
          pobj = new map<string,string,less<string>,allocator<pair<const string,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2429 of file DataLibraryDict.cpp.
References count.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->count(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2435 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       {
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator* pobj;
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator xobj = ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->lower_bound(*(string*) libp->para[0].ref);
          pobj = new map<string,string,less<string>,allocator<pair<const string,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2448 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       {
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator* pobj;
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator xobj = ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->upper_bound(*(string*) libp->para[0].ref);
          pobj = new map<string,string,less<string>,allocator<pair<const string,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2463 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (map<string,string,less<string>,allocator<pair<const string,string> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((map<string,string,less<string>,allocator<pair<const string,string> > >*) (soff+(sizeof(map<string,string,less<string>,allocator<pair<const string,string> > >)*i)))->~G__TmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (map<string,string,less<string>,allocator<pair<const string,string> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((map<string,string,less<string>,allocator<pair<const string,string> > >*) (soff))->~G__TmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2220 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
    map<string,string,less<string>,allocator<pair<const string,string> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,string,less<string>,allocator<pair<const string,string> > >(*((map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<string,string,less<string>,allocator<pair<const string,string> > >(*((map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2236 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
    map<string,string,less<string>,allocator<pair<const string,string> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,string,less<string>,allocator<pair<const string,string> > >(*(map<string,string,less<string>,allocator<pair<const string,string> > >*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) map<string,string,less<string>,allocator<pair<const string,string> > >(*(map<string,string,less<string>,allocator<pair<const string,string> > >*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2252 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       {
          const map<string,string,less<string>,allocator<pair<const string,string> > >& obj = ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->operator=(*(map<string,string,less<string>,allocator<pair<const string,string> > >*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2262 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       {
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator* pobj;
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator xobj = ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->begin();
          pobj = new map<string,string,less<string>,allocator<pair<const string,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2275 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       {
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator* pobj;
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator xobj = ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->end();
          pobj = new map<string,string,less<string>,allocator<pair<const string,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2288 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       {
          map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator* pobj;
          map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator xobj = ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->rbegin();
          pobj = new map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_507_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2301 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR().
 {
       {
          map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator* pobj;
          map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator xobj = ((map<string,string,less<string>,allocator<pair<const string,string> > >*) G__getstructoffset())->rend();
          pobj = new map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_508_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2501 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOstringgR.
Referenced by G__setup_memfuncpairlEstringcOstringgR().
 {
    pair<string,string>* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new pair<string,string>[n];
      } else {
        p = new((void*) gvp) pair<string,string>[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new pair<string,string>;
      } else {
        p = new((void*) gvp) pair<string,string>;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_508_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2525 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOstringgR.
Referenced by G__setup_memfuncpairlEstringcOstringgR().
 {
    pair<string,string>* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new pair<string,string>(*(string*) libp->para[0].ref, *(string*) libp->para[1].ref);
    } else {
      p = new((void*) gvp) pair<string,string>(*(string*) libp->para[0].ref, *(string*) libp->para[1].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_508_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2542 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOstringgR.
Referenced by G__setup_memfuncpairlEstringcOstringgR().
 {
    pair<string,string>* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new pair<string,string>(*(pair<string,string>*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_508_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2556 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncpairlEstringcOstringgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (pair<string,string>*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((pair<string,string>*) (soff+(sizeof(pair<string,string>)*i)))->~G__TpairlEstringcOstringgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (pair<string,string>*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((pair<string,string>*) (soff))->~G__TpairlEstringcOstringgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2594 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
    map<string,string,less<string>,allocator<pair<const string,string> > >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,string,less<string>,allocator<pair<const string,string> > >::iterator[n];
      } else {
        p = new((void*) gvp) map<string,string,less<string>,allocator<pair<const string,string> > >::iterator[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,string,less<string>,allocator<pair<const string,string> > >::iterator;
      } else {
        p = new((void*) gvp) map<string,string,less<string>,allocator<pair<const string,string> > >::iterator;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2706 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 103, (long) ((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__getstructoffset())->operator==(*(map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2712 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 103, (long) ((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__getstructoffset())->operator!=(*(map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2720 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) (soff+(sizeof(map<string,string,less<string>,allocator<pair<const string,string> > >::iterator)*i)))->~G__TmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) (soff))->~G__TmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2618 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
    map<string,string,less<string>,allocator<pair<const string,string> > >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,string,less<string>,allocator<pair<const string,string> > >::iterator(*(map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) map<string,string,less<string>,allocator<pair<const string,string> > >::iterator(*(map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2634 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,string,less<string>,allocator<pair<const string,string> > >::iterator& obj = ((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__getstructoffset())->operator=(*(map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2644 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,string,less<string>,allocator<pair<const string,string> > >::value_type& obj = ((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__getstructoffset())->operator*();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2654 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 85, (long) ((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__getstructoffset())->operator->());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2660 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,string,less<string>,allocator<pair<const string,string> > >::iterator& obj = ((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__getstructoffset())->operator++();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2670 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
       {
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator* pobj;
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator xobj = ((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__getstructoffset())->operator++((int) G__int(libp->para[0]));
          pobj = new map<string,string,less<string>,allocator<pair<const string,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2683 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,string,less<string>,allocator<pair<const string,string> > >::iterator& obj = ((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__getstructoffset())->operator--();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_509_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2693 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator().
 {
       {
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator* pobj;
          map<string,string,less<string>,allocator<pair<const string,string> > >::iterator xobj = ((map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*) G__getstructoffset())->operator--((int) G__int(libp->para[0]));
          pobj = new map<string,string,less<string>,allocator<pair<const string,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2758 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TPulseIsland.
Referenced by G__setup_memfuncTPulseIsland().
 {
    TPulseIsland* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TPulseIsland[n];
      } else {
        p = new((void*) gvp) TPulseIsland[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TPulseIsland;
      } else {
        p = new((void*) gvp) TPulseIsland;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2867 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetFastPulseAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2873 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetSlowPulseAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2879 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetPulseHeight());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2885 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetPulseTime());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2891 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 85, (long) ((const TPulseIsland*) G__getstructoffset())->GetPulseWaveform(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2897 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) ((const TPulseIsland*) G__getstructoffset())->GetPulseLength());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2903 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) ((const TPulseIsland*) G__getstructoffset())->GetPeakSample());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2909 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetPedestal((int) G__int(libp->para[0])));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2915 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 85, (long) TPulseIsland::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2921 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 67, (long) TPulseIsland::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2782 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TPulseIsland.
Referenced by G__setup_memfuncTPulseIsland().
 {
    TPulseIsland* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 3
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new TPulseIsland(
 (int) G__int(libp->para[0]), *(vector<int>*) libp->para[1].ref
 , *((string*) G__int(libp->para[2])));
    } else {
      p = new((void*) gvp) TPulseIsland(
 (int) G__int(libp->para[0]), *(vector<int>*) libp->para[1].ref
 , *((string*) G__int(libp->para[2])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2927 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 115, (long) TPulseIsland::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2933 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       TPulseIsland::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2940 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       ((TPulseIsland*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2947 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 67, (long) TPulseIsland::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2953 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) TPulseIsland::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_28 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2959 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 67, (long) TPulseIsland::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_29 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2965 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) TPulseIsland::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2802 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
    switch (libp->paran) {
    case 1:
       ((TPulseIsland*) G__getstructoffset())->Reset((Option_t*) G__int(libp->para[0]));
       G__setnull(result7);
       break;
    case 0:
       ((TPulseIsland*) G__getstructoffset())->Reset();
       G__setnull(result7);
       break;
    }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_30 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2972 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TPulseIsland.
Referenced by G__setup_memfuncTPulseIsland().
 {
    TPulseIsland* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TPulseIsland(*(TPulseIsland*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_31 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2986 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncTPulseIsland().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TPulseIsland*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TPulseIsland*) (soff+(sizeof(TPulseIsland)*i)))->~G__TTPulseIsland();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TPulseIsland*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TPulseIsland*) (soff))->~G__TTPulseIsland();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_32 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3023 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
    TPulseIsland* dest = (TPulseIsland*) G__getstructoffset();
    *dest = *(TPulseIsland*) libp->para[0].ref;
    const TPulseIsland& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2817 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       {
          const vector<int>* pobj;
          const vector<int> xobj = ((const TPulseIsland*) G__getstructoffset())->GetSamples();
          pobj = new vector<int>(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2830 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) ((const TPulseIsland*) G__getstructoffset())->GetTimeStamp());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2836 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       {
          const string* pobj;
          const string xobj = ((const TPulseIsland*) G__getstructoffset())->GetBankName();
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2849 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetClockTickInNs());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2855 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letint(result7, 105, (long) ((const TPulseIsland*) G__getstructoffset())->GetTriggerPolarity());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_512_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2861 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTPulseIsland().
 {
       G__letdouble(result7, 100, (double) ((const TPulseIsland*) G__getstructoffset())->GetAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3035 of file DataLibraryDict.cpp.
References TGlobalData::Instance().
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 85, (long) TGlobalData::Instance());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3073 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 67, (long) TGlobalData::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3079 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 105, (long) TGlobalData::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3085 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 67, (long) TGlobalData::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3091 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 105, (long) TGlobalData::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3098 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TGlobalData.
Referenced by G__setup_memfuncTGlobalData().
 {
    TGlobalData *p;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TGlobalData[n];
      } else {
        p = new((void*) gvp) TGlobalData[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TGlobalData;
      } else {
        p = new((void*) gvp) TGlobalData;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TGlobalData));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3123 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TGlobalData.
Referenced by G__setup_memfuncTGlobalData().
 {
    TGlobalData* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TGlobalData(*(TGlobalData*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TGlobalData));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3137 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncTGlobalData().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TGlobalData*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TGlobalData*) (soff+(sizeof(TGlobalData)*i)))->~G__TTGlobalData();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TGlobalData*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TGlobalData*) (soff))->~G__TTGlobalData();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3174 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTGlobalData().
 {
    TGlobalData* dest = (TGlobalData*) G__getstructoffset();
    *dest = *(TGlobalData*) libp->para[0].ref;
    const TGlobalData& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3041 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 85, (long) TGlobalData::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3047 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 67, (long) TGlobalData::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3053 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTGlobalData().
 {
       G__letint(result7, 115, (long) TGlobalData::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3059 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTGlobalData().
 {
       TGlobalData::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_516_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3066 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTGlobalData().
 {
       ((TGlobalData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3186 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::reference obj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->at((vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3277 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->resize((vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[0]), (TPulseIsland*) G__int(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3284 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->capacity());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3290 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       G__letint(result7, 103, (long) ((const vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->empty());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3296 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::reference obj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->operator[]((vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3306 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::const_reference obj = ((const vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->operator[]((vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3316 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
    vector<TPulseIsland*,allocator<TPulseIsland*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TPulseIsland*,allocator<TPulseIsland*> >[n];
      } else {
        p = new((void*) gvp) vector<TPulseIsland*,allocator<TPulseIsland*> >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TPulseIsland*,allocator<TPulseIsland*> >;
      } else {
        p = new((void*) gvp) vector<TPulseIsland*,allocator<TPulseIsland*> >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3340 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
    vector<TPulseIsland*,allocator<TPulseIsland*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    switch (libp->paran) {
    case 2:
      //m: 2
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TPulseIsland*,allocator<TPulseIsland*> >((vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[0]), libp->para[1].ref ? *(TPulseIsland**) libp->para[1].ref : *(TPulseIsland**) (void*) (&G__Mlong(libp->para[1])));
      } else {
        p = new((void*) gvp) vector<TPulseIsland*,allocator<TPulseIsland*> >((vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[0]), libp->para[1].ref ? *(TPulseIsland**) libp->para[1].ref : *(TPulseIsland**) (void*) (&G__Mlong(libp->para[1])));
      }
      break;
    case 1:
      //m: 1
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TPulseIsland*,allocator<TPulseIsland*> >((vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[0]));
      } else {
        p = new((void*) gvp) vector<TPulseIsland*,allocator<TPulseIsland*> >((vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[0]));
      }
      break;
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3368 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
    vector<TPulseIsland*,allocator<TPulseIsland*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new vector<TPulseIsland*,allocator<TPulseIsland*> >(*(vector<TPulseIsland*,allocator<TPulseIsland*> >*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) vector<TPulseIsland*,allocator<TPulseIsland*> >(*(vector<TPulseIsland*,allocator<TPulseIsland*> >*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3384 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
    vector<TPulseIsland*,allocator<TPulseIsland*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new vector<TPulseIsland*,allocator<TPulseIsland*> >(*((vector<TPulseIsland*,allocator<TPulseIsland*> >::const_iterator*) G__int(libp->para[0])), *((vector<TPulseIsland*,allocator<TPulseIsland*> >::const_iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) vector<TPulseIsland*,allocator<TPulseIsland*> >(*((vector<TPulseIsland*,allocator<TPulseIsland*> >::const_iterator*) G__int(libp->para[0])), *((vector<TPulseIsland*,allocator<TPulseIsland*> >::const_iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3400 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          const vector<TPulseIsland*,allocator<TPulseIsland*> >& obj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->operator=(*(vector<TPulseIsland*,allocator<TPulseIsland*> >*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3196 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::const_reference obj = ((const vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->at((vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3410 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->reserve((vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[0]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3417 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          TPulseIsland*& obj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->front();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3427 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          TPulseIsland*& obj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->back();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3437 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->push_back(libp->para[0].ref ? *(TPulseIsland**) libp->para[0].ref : *(TPulseIsland**) (void*) (&G__Mlong(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3444 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->swap(*(vector<TPulseIsland*,allocator<TPulseIsland*> >*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3451 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator* pobj;
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator xobj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->insert(*((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__int(libp->para[0])), libp->para[1].ref ? *(TPulseIsland**) libp->para[1].ref : *(TPulseIsland**) (void*) (&G__Mlong(libp->para[1])));
          pobj = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3464 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->insert(*((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__int(libp->para[0])), *((vector<TPulseIsland*,allocator<TPulseIsland*> >::const_iterator*) G__int(libp->para[1]))
 , *((vector<TPulseIsland*,allocator<TPulseIsland*> >::const_iterator*) G__int(libp->para[2])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3472 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->insert(*((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__int(libp->para[0])), (vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[1])
 , libp->para[2].ref ? *(TPulseIsland**) libp->para[2].ref : *(TPulseIsland**) (void*) (&G__Mlong(libp->para[2])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_28 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3480 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->pop_back();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_29 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3487 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->erase(*((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__int(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3206 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator* pobj;
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator xobj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->begin();
          pobj = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_30 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3494 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->erase(*((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__int(libp->para[0])), *((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_31 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3501 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->clear();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_32 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3510 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (vector<TPulseIsland*,allocator<TPulseIsland*> >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) (soff+(sizeof(vector<TPulseIsland*,allocator<TPulseIsland*> >)*i)))->~G__TvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (vector<TPulseIsland*,allocator<TPulseIsland*> >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) (soff))->~G__TvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3219 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator* pobj;
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator xobj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->end();
          pobj = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3232 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::reverse_iterator* pobj;
          vector<TPulseIsland*,allocator<TPulseIsland*> >::reverse_iterator xobj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->rbegin();
          pobj = new vector<TPulseIsland*,allocator<TPulseIsland*> >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3245 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::reverse_iterator* pobj;
          vector<TPulseIsland*,allocator<TPulseIsland*> >::reverse_iterator xobj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->rend();
          pobj = new vector<TPulseIsland*,allocator<TPulseIsland*> >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3258 of file DataLibraryDict.cpp.
References size.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3264 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->max_size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_518_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3270 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR().
 {
       ((vector<TPulseIsland*,allocator<TPulseIsland*> >*) G__getstructoffset())->resize((vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type) G__int(libp->para[0]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3548 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
    vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator[n];
      } else {
        p = new((void*) gvp) vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator;
      } else {
        p = new((void*) gvp) vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3660 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator& obj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator+=(*(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3670 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator* pobj;
          const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator xobj = ((const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator+(*(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          pobj = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3683 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator& obj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator-=(*(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3693 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator* pobj;
          const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator xobj = ((const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator-(*(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          pobj = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3706 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::pointer& obj = ((const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->base();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3716 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator* pobj;
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator xobj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator=(*(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) libp->para[0].ref);
          pobj = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3730 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
    vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator(*(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3744 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) (soff+(sizeof(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator)*i)))->~G__TvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) (soff))->~G__TvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3572 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
    vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator(libp->para[0].ref ? *(const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::pointer*) libp->para[0].ref : *(const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::pointer*) (void*) (&G__Mlong(libp->para[0])));
    } else {
      p = new((void*) gvp) vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator(libp->para[0].ref ? *(const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::pointer*) libp->para[0].ref : *(const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::pointer*) (void*) (&G__Mlong(libp->para[0])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3588 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::reference obj = ((const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator*();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3598 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       G__letint(result7, 85, (long) ((const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator->());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3604 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator& obj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator++();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3614 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator* pobj;
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator xobj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator++((int) G__int(libp->para[0]));
          pobj = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3627 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator& obj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator--();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3637 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator* pobj;
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator xobj = ((vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator--((int) G__int(libp->para[0]));
          pobj = new vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_519_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3650 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator().
 {
       {
          vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::reference obj = ((const vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) G__getstructoffset())->operator[](*(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3782 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >[n];
      } else {
        p = new((void*) gvp) map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >;
      } else {
        p = new((void*) gvp) map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3916 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 103, (long) ((const map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->empty());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3922 of file DataLibraryDict.cpp.
References size.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3928 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->max_size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3934 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       {
          const vector<TPulseIsland*,allocator<TPulseIsland*> >& obj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->operator[](*(string*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3944 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       {
          pair<map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator,bool>* pobj;
          pair<map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator,bool> xobj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->insert(*(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::value_type*) libp->para[0].ref);
          pobj = new pair<map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator,bool>(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3957 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator* pobj;
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator xobj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->insert(*((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__int(libp->para[0])), *(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::value_type*) libp->para[1].ref);
          pobj = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3970 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->insert(*((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3977 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->insert(*((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3984 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->erase(*((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__int(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3991 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->erase(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3806 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >(*((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >(*((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3997 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->erase(*((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4004 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->swap(*(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4011 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->clear();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4018 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator* pobj;
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator xobj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->find(*(string*) libp->para[0].ref);
          pobj = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4031 of file DataLibraryDict.cpp.
References count.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->count(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4037 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator* pobj;
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator xobj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->lower_bound(*(string*) libp->para[0].ref);
          pobj = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4050 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator* pobj;
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator xobj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->upper_bound(*(string*) libp->para[0].ref);
          pobj = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4065 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) (soff+(sizeof(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >)*i)))->~G__TmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) (soff))->~G__TmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3822 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >(*((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >(*((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3838 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >(*(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >(*(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3854 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       {
          const map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >& obj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->operator=(*(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3864 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator* pobj;
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator xobj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->begin();
          pobj = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3877 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator* pobj;
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator xobj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->end();
          pobj = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3890 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator* pobj;
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator xobj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->rbegin();
          pobj = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_523_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3903 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator* pobj;
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator xobj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*) G__getstructoffset())->rend();
          pobj = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_524_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4103 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR.
Referenced by G__setup_memfuncpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR().
 {
    pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >[n];
      } else {
        p = new((void*) gvp) pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >;
      } else {
        p = new((void*) gvp) pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_524_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4127 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR.
Referenced by G__setup_memfuncpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR().
 {
    pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >(*(string*) libp->para[0].ref, *(vector<TPulseIsland*,allocator<TPulseIsland*> >*) libp->para[1].ref);
    } else {
      p = new((void*) gvp) pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >(*(string*) libp->para[0].ref, *(vector<TPulseIsland*,allocator<TPulseIsland*> >*) libp->para[1].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_524_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4144 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR.
Referenced by G__setup_memfuncpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR().
 {
    pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >(*(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_524_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4158 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*) (soff+(sizeof(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >)*i)))->~G__TpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*) (soff))->~G__TpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4196 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
    map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator[n];
      } else {
        p = new((void*) gvp) map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator;
      } else {
        p = new((void*) gvp) map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4308 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 103, (long) ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__getstructoffset())->operator==(*(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4314 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 103, (long) ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__getstructoffset())->operator!=(*(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4322 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) (soff+(sizeof(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator)*i)))->~G__TmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) (soff))->~G__TmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4220 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
    map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator(*(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator(*(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4236 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator& obj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__getstructoffset())->operator=(*(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4246 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::value_type& obj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__getstructoffset())->operator*();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4256 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 85, (long) ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__getstructoffset())->operator->());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4262 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator& obj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__getstructoffset())->operator++();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4272 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator* pobj;
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator xobj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__getstructoffset())->operator++((int) G__int(libp->para[0]));
          pobj = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4285 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator& obj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__getstructoffset())->operator--();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_525_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4295 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator* pobj;
          map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator xobj = ((map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*) G__getstructoffset())->operator--((int) G__int(libp->para[0]));
          pobj = new map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4360 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TAnalysedPulse.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    TAnalysedPulse* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TAnalysedPulse[n];
      } else {
        p = new((void*) gvp) TAnalysedPulse[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TAnalysedPulse;
      } else {
        p = new((void*) gvp) TAnalysedPulse;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4464 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 67, (long) TAnalysedPulse::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4470 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 115, (long) TAnalysedPulse::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4476 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       TAnalysedPulse::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4483 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       ((TAnalysedPulse*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4490 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 67, (long) TAnalysedPulse::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4496 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 105, (long) TAnalysedPulse::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4502 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 67, (long) TAnalysedPulse::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4384 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TAnalysedPulse.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    TAnalysedPulse* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 5
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new TAnalysedPulse(
 (double) G__double(libp->para[0]), (double) G__double(libp->para[1])
 , (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
 , *((string*) G__int(libp->para[4])));
    } else {
      p = new((void*) gvp) TAnalysedPulse(
 (double) G__double(libp->para[0]), (double) G__double(libp->para[1])
 , (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
 , *((string*) G__int(libp->para[4])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4508 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 105, (long) TAnalysedPulse::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4515 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TAnalysedPulse.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    TAnalysedPulse* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TAnalysedPulse(*(TAnalysedPulse*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4529 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TAnalysedPulse*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TAnalysedPulse*) (soff+(sizeof(TAnalysedPulse)*i)))->~G__TTAnalysedPulse();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TAnalysedPulse*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TAnalysedPulse*) (soff))->~G__TTAnalysedPulse();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4566 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    TAnalysedPulse* dest = (TAnalysedPulse*) G__getstructoffset();
    *dest = *(TAnalysedPulse*) libp->para[0].ref;
    const TAnalysedPulse& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4406 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    switch (libp->paran) {
    case 1:
       ((TAnalysedPulse*) G__getstructoffset())->Reset((Option_t*) G__int(libp->para[0]));
       G__setnull(result7);
       break;
    case 0:
       ((TAnalysedPulse*) G__getstructoffset())->Reset();
       G__setnull(result7);
       break;
    }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4421 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letdouble(result7, 100, (double) ((const TAnalysedPulse*) G__getstructoffset())->GetAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4427 of file DataLibraryDict.cpp.
References GetTime().
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letdouble(result7, 100, (double) ((const TAnalysedPulse*) G__getstructoffset())->GetTime());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4433 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letdouble(result7, 100, (double) ((const TAnalysedPulse*) G__getstructoffset())->GetIntegral());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4439 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letdouble(result7, 100, (double) ((const TAnalysedPulse*) G__getstructoffset())->GetEnergy());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4445 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       {
          const string* pobj;
          const string xobj = ((const TAnalysedPulse*) G__getstructoffset())->GetDetName();
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_528_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4458 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 85, (long) TAnalysedPulse::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4578 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TDetectorPulse.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    TDetectorPulse* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TDetectorPulse[n];
      } else {
        p = new((void*) gvp) TDetectorPulse[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TDetectorPulse;
      } else {
        p = new((void*) gvp) TDetectorPulse;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TDetectorPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4673 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       {
          const string* pobj;
          const string xobj = ((const TDetectorPulse*) G__getstructoffset())->GetDetName();
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4686 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 85, (long) TDetectorPulse::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4692 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 67, (long) TDetectorPulse::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4698 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 115, (long) TDetectorPulse::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4704 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       TDetectorPulse::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4711 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       ((TDetectorPulse*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4718 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 67, (long) TDetectorPulse::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4602 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TDetectorPulse.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    TDetectorPulse* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 3
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new TDetectorPulse(
 (TAnalysedPulse*) G__int(libp->para[0]), (TAnalysedPulse*) G__int(libp->para[1])
 , *((string*) G__int(libp->para[2])));
    } else {
      p = new((void*) gvp) TDetectorPulse(
 (TAnalysedPulse*) G__int(libp->para[0]), (TAnalysedPulse*) G__int(libp->para[1])
 , *((string*) G__int(libp->para[2])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TDetectorPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4724 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 105, (long) TDetectorPulse::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4730 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 67, (long) TDetectorPulse::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4736 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 105, (long) TDetectorPulse::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4743 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TDetectorPulse.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    TDetectorPulse* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TDetectorPulse(*(TDetectorPulse*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TDetectorPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4757 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TDetectorPulse*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TDetectorPulse*) (soff+(sizeof(TDetectorPulse)*i)))->~G__TTDetectorPulse();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TDetectorPulse*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TDetectorPulse*) (soff))->~G__TTDetectorPulse();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4794 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    TDetectorPulse* dest = (TDetectorPulse*) G__getstructoffset();
    *dest = *(TDetectorPulse*) libp->para[0].ref;
    const TDetectorPulse& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4622 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    switch (libp->paran) {
    case 1:
       ((TDetectorPulse*) G__getstructoffset())->Reset((Option_t*) G__int(libp->para[0]));
       G__setnull(result7);
       break;
    case 0:
       ((TDetectorPulse*) G__getstructoffset())->Reset();
       G__setnull(result7);
       break;
    }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4637 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetFastPulseAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4643 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetSlowPulseAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4649 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetFastPulseTime());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4655 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetSlowPulseTime());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4661 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetFastPulseIntegral());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_529_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4667 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetSlowPulseIntegral());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4806 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TVacuumData.
Referenced by G__setup_memfuncTVacuumData().
 {
    TVacuumData* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TVacuumData[n];
      } else {
        p = new((void*) gvp) TVacuumData[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TVacuumData;
      } else {
        p = new((void*) gvp) TVacuumData;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TVacuumData));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4898 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
       ((TVacuumData*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4905 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
       G__letint(result7, 67, (long) TVacuumData::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4911 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
       G__letint(result7, 105, (long) TVacuumData::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4917 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
       G__letint(result7, 67, (long) TVacuumData::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4923 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
       G__letint(result7, 105, (long) TVacuumData::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4930 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TVacuumData.
Referenced by G__setup_memfuncTVacuumData().
 {
    TVacuumData* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TVacuumData(*(TVacuumData*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TVacuumData));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4944 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncTVacuumData().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TVacuumData*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TVacuumData*) (soff+(sizeof(TVacuumData)*i)))->~G__TTVacuumData();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TVacuumData*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TVacuumData*) (soff))->~G__TTVacuumData();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4981 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
    TVacuumData* dest = (TVacuumData*) G__getstructoffset();
    *dest = *(TVacuumData*) libp->para[0].ref;
    const TVacuumData& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4830 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TVacuumData.
Referenced by G__setup_memfuncTVacuumData().
 {
    TVacuumData* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 3
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new TVacuumData(
 *((vector<int>*) G__int(libp->para[0])), *((vector<int>*) G__int(libp->para[1]))
 , *((vector<float>*) G__int(libp->para[2])));
    } else {
      p = new((void*) gvp) TVacuumData(
 *((vector<int>*) G__int(libp->para[0])), *((vector<int>*) G__int(libp->para[1]))
 , *((vector<float>*) G__int(libp->para[2])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_TVacuumData));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4850 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
    switch (libp->paran) {
    case 1:
       ((TVacuumData*) G__getstructoffset())->Reset((Option_t*) G__int(libp->para[0]));
       G__setnull(result7);
       break;
    case 0:
       ((TVacuumData*) G__getstructoffset())->Reset();
       G__setnull(result7);
       break;
    }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4865 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
       ((TVacuumData*) G__getstructoffset())->AddPoint((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
 , (float) G__double(libp->para[2]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4873 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
       G__letint(result7, 85, (long) TVacuumData::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4879 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
       G__letint(result7, 67, (long) TVacuumData::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4885 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
       G__letint(result7, 115, (long) TVacuumData::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_530_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4891 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncTVacuumData().
 {
       TVacuumData::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4993 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reference obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->at((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5084 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->resize((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]), (TAnalysedPulse*) G__int(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5091 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->capacity());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5097 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       G__letint(result7, 103, (long) ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->empty());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5103 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reference obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->operator[]((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5113 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_reference obj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->operator[]((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5123 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >[n];
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >;
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5147 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    switch (libp->paran) {
    case 2:
      //m: 2
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]), libp->para[1].ref ? *(TAnalysedPulse**) libp->para[1].ref : *(TAnalysedPulse**) (void*) (&G__Mlong(libp->para[1])));
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]), libp->para[1].ref ? *(TAnalysedPulse**) libp->para[1].ref : *(TAnalysedPulse**) (void*) (&G__Mlong(libp->para[1])));
      }
      break;
    case 1:
      //m: 1
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
      }
      break;
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5175 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5191 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[0])), *((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[0])), *((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5207 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->operator=(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5003 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_reference obj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->at((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5217 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->reserve((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5224 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          TAnalysedPulse*& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->front();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5234 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          TAnalysedPulse*& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->back();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5244 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->push_back(libp->para[0].ref ? *(TAnalysedPulse**) libp->para[0].ref : *(TAnalysedPulse**) (void*) (&G__Mlong(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5251 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->swap(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5258 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->insert(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[0])), libp->para[1].ref ? *(TAnalysedPulse**) libp->para[1].ref : *(TAnalysedPulse**) (void*) (&G__Mlong(libp->para[1])));
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5271 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->insert(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[0])), *((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[1]))
 , *((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[2])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5279 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->insert(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[0])), (vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[1])
 , libp->para[2].ref ? *(TAnalysedPulse**) libp->para[2].ref : *(TAnalysedPulse**) (void*) (&G__Mlong(libp->para[2])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_28 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5287 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->pop_back();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_29 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5294 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->erase(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5013 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->begin();
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_30 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5301 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->erase(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[0])), *((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_31 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5308 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->clear();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_32 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5317 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) (soff+(sizeof(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >)*i)))->~G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) (soff))->~G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5026 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->end();
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5039 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->rbegin();
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5052 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->rend();
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5065 of file DataLibraryDict.cpp.
References size.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5071 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->max_size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_532_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5077 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->resize((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5355 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator[n];
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator;
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5467 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator+=(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5477 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator+(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5490 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator-=(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5500 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator-(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5513 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer& obj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->base();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5523 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator=(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) libp->para[0].ref);
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5537 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5551 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) (soff+(sizeof(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator)*i)))->~G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) (soff))->~G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5379 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(libp->para[0].ref ? *(const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer*) libp->para[0].ref : *(const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer*) (void*) (&G__Mlong(libp->para[0])));
    } else {
      p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(libp->para[0].ref ? *(const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer*) libp->para[0].ref : *(const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer*) (void*) (&G__Mlong(libp->para[0])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5395 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::reference obj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator*();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5405 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       G__letint(result7, 85, (long) ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator->());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5411 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator++();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5421 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator++((int) G__int(libp->para[0]));
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5434 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator--();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5444 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator--((int) G__int(libp->para[0]));
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_533_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5457 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::reference obj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator[](*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5589 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >[n];
      } else {
        p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >;
      } else {
        p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5723 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 103, (long) ((const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->empty());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5729 of file DataLibraryDict.cpp.
References size.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5735 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->max_size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5741 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->operator[](*(string*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5751 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          pair<map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator,bool>* pobj;
          pair<map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator,bool> xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->insert(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type*) libp->para[0].ref);
          pobj = new pair<map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator,bool>(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5764 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->insert(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])), *(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type*) libp->para[1].ref);
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5777 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->insert(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5784 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->insert(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5791 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->erase(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5798 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->erase(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5613 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5804 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->erase(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5811 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->swap(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5818 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->clear();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5825 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->find(*(string*) libp->para[0].ref);
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5838 of file DataLibraryDict.cpp.
References count.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->count(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5844 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->lower_bound(*(string*) libp->para[0].ref);
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5857 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->upper_bound(*(string*) libp->para[0].ref);
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5872 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) (soff+(sizeof(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >)*i)))->~G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) (soff))->~G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5629 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5645 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5661 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->operator=(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5671 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->begin();
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5684 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->end();
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5697 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->rbegin();
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_537_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5710 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->rend();
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_538_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5910 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR.
Referenced by G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR().
 {
    pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >[n];
      } else {
        p = new((void*) gvp) pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >;
      } else {
        p = new((void*) gvp) pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_538_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5934 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR.
Referenced by G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR().
 {
    pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >(*(string*) libp->para[0].ref, *(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[1].ref);
    } else {
      p = new((void*) gvp) pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >(*(string*) libp->para[0].ref, *(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[1].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_538_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5951 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR.
Referenced by G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR().
 {
    pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >(*(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_538_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5965 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*) (soff+(sizeof(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >)*i)))->~G__TpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*) (soff))->~G__TpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6003 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator[n];
      } else {
        p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator;
      } else {
        p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6115 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 103, (long) ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator==(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6121 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 103, (long) ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator!=(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6129 of file DataLibraryDict.cpp.
References i.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) (soff+(sizeof(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator)*i)))->~G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) (soff))->~G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6027 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6043 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator=(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6053 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator*();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6063 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 85, (long) ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator->());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6069 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator++();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6079 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator++((int) G__int(libp->para[0]));
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6092 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator--();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict_539_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6102 of file DataLibraryDict.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator--((int) G__int(libp->para[0]));
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict__0_2003 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6167 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_func19().
 {
       G__letint(result7, 103, (long) operator!=(*(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) libp->para[0].ref, *(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*) libp->para[1].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__DataLibraryDict__0_2080 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 6173 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_func20().
 {
       G__letint(result7, 103, (long) operator!=(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) libp->para[0].ref, *(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) libp->para[1].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
size_t G__get_sizep2memfuncDataLibraryDict ()
Definition at line 6237 of file DataLibraryDict.cpp.
References G__Sizep2memfuncDataLibraryDict::sizep2memfunc().
 {
   G__Sizep2memfuncDataLibraryDict a;
   G__setsizep2memfunc((int)a.sizep2memfunc());
   return((size_t)a.sizep2memfunc());
 }
void G__set_cpp_environmentDataLibraryDict ()
Definition at line 1858 of file DataLibraryDict.cpp.
References G__cpp_reset_tagtableDataLibraryDict().
{
   G__cpp_reset_tagtableDataLibraryDict();
 }
static void G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR (void) static
Definition at line 6794 of file DataLibraryDict.cpp.
References G__DataLibraryDict_507_0_1(), G__DataLibraryDict_507_0_10(), G__DataLibraryDict_507_0_11(), G__DataLibraryDict_507_0_12(), G__DataLibraryDict_507_0_13(), G__DataLibraryDict_507_0_14(), G__DataLibraryDict_507_0_15(), G__DataLibraryDict_507_0_16(), G__DataLibraryDict_507_0_17(), G__DataLibraryDict_507_0_18(), G__DataLibraryDict_507_0_19(), G__DataLibraryDict_507_0_2(), G__DataLibraryDict_507_0_20(), G__DataLibraryDict_507_0_21(), G__DataLibraryDict_507_0_22(), G__DataLibraryDict_507_0_23(), G__DataLibraryDict_507_0_24(), G__DataLibraryDict_507_0_25(), G__DataLibraryDict_507_0_26(), G__DataLibraryDict_507_0_27(), G__DataLibraryDict_507_0_3(), G__DataLibraryDict_507_0_4(), G__DataLibraryDict_507_0_5(), G__DataLibraryDict_507_0_6(), G__DataLibraryDict_507_0_7(), G__DataLibraryDict_507_0_8(), G__DataLibraryDict_507_0_9(), G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator, G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLreverse_iterator, G__DataLibraryDictLN_pairlEmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiteratorcOboolgR, and G__DataLibraryDictLN_string.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* map<string,string,less<string>,allocator<pair<const string,string> > > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    G__memfunc_setup("map<string,string,less<string>,allocator<pair<const string,string> > >",6772,G__DataLibraryDict_507_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,string,less<string>,allocator<pair<const string,string> > >",6772,G__DataLibraryDict_507_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 0 - first u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,string,less<string>,allocator<pair<const string,string> > >",6772,G__DataLibraryDict_507_0_3, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator' - 0 - first u 'map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,string,less<string>,allocator<pair<const string,string> > >",6772,G__DataLibraryDict_507_0_4, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR), -1, 0, 1, 1, 1, 0, "u 'map<string,string,less<string>,allocator<pair<const string,string> > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__DataLibraryDict_507_0_5, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR), -1, 1, 1, 1, 1, 0, "u 'map<string,string,less<string>,allocator<pair<const string,string> > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("begin",517,G__DataLibraryDict_507_0_6, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("end",311,G__DataLibraryDict_507_0_7, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rbegin",631,G__DataLibraryDict_507_0_8, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rend",425,G__DataLibraryDict_507_0_9, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("empty",559,G__DataLibraryDict_507_0_10, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("size",443,G__DataLibraryDict_507_0_11, 107, -1, G__defined_typename("map<string,string,less<string>,allocator<pair<const string,string> > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("max_size",864,G__DataLibraryDict_507_0_12, 107, -1, G__defined_typename("map<string,string,less<string>,allocator<pair<const string,string> > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__DataLibraryDict_507_0_13, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_string), -1, 1, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_507_0_14, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiteratorcOboolgR), -1, 0, 1, 1, 1, 0, "u 'pair<string,string>' 'map<string,string,less<string>,allocator<pair<const string,string> > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_507_0_15, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0,
 "u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 0 - position u 'pair<string,string>' 'map<string,string,less<string>,allocator<pair<const string,string> > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_507_0_16, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 0 - first u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_507_0_17, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator' - 0 - first u 'map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_507_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_507_0_19, 107, -1, G__defined_typename("map<string,string,less<string>,allocator<pair<const string,string> > >::size_type"), 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_507_0_20, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 0 - first u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("swap",443,G__DataLibraryDict_507_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,string,less<string>,allocator<pair<const string,string> > >' - 1 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("clear",519,G__DataLibraryDict_507_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("find",417,G__DataLibraryDict_507_0_23, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("count",553,G__DataLibraryDict_507_0_24, 107, -1, G__defined_typename("map<string,string,less<string>,allocator<pair<const string,string> > >::size_type"), 0, 1, 1, 1, 8, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("lower_bound",1184,G__DataLibraryDict_507_0_25, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("upper_bound",1187,G__DataLibraryDict_507_0_26, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~map<string,string,less<string>,allocator<pair<const string,string> > >", 6898, G__DataLibraryDict_507_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void) static
Definition at line 6848 of file DataLibraryDict.cpp.
References G__DataLibraryDict_509_0_1(), G__DataLibraryDict_509_0_10(), G__DataLibraryDict_509_0_11(), G__DataLibraryDict_509_0_12(), G__DataLibraryDict_509_0_2(), G__DataLibraryDict_509_0_3(), G__DataLibraryDict_509_0_4(), G__DataLibraryDict_509_0_5(), G__DataLibraryDict_509_0_6(), G__DataLibraryDict_509_0_7(), G__DataLibraryDict_509_0_8(), G__DataLibraryDict_509_0_9(), G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator, and G__DataLibraryDictLN_pairlEstringcOstringgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* map<string,string,less<string>,allocator<pair<const string,string> > >::iterator */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator));
    G__memfunc_setup("iterator",874,G__DataLibraryDict_509_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("iterator",874,G__DataLibraryDict_509_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__DataLibraryDict_509_0_3, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 1, 1, 1, 1, 0, "u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator*",918,G__DataLibraryDict_509_0_4, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR), G__defined_typename("map<string,string,less<string>,allocator<pair<const string,string> > >::value_type"), 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator->",983,G__DataLibraryDict_509_0_5, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR), G__defined_typename("map<string,string,less<string>,allocator<pair<const string,string> > >::value_type"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__DataLibraryDict_509_0_6, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__DataLibraryDict_509_0_7, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - a", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__DataLibraryDict_509_0_8, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__DataLibraryDict_509_0_9, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - a", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator==",998,G__DataLibraryDict_509_0_10, 103, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator!=",970,G__DataLibraryDict_509_0_11, 103, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,string,less<string>,allocator<pair<const string,string> > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~iterator", 1000, G__DataLibraryDict_509_0_12, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR (void) static
Definition at line 7261 of file DataLibraryDict.cpp.
References G__DataLibraryDict_537_0_1(), G__DataLibraryDict_537_0_10(), G__DataLibraryDict_537_0_11(), G__DataLibraryDict_537_0_12(), G__DataLibraryDict_537_0_13(), G__DataLibraryDict_537_0_14(), G__DataLibraryDict_537_0_15(), G__DataLibraryDict_537_0_16(), G__DataLibraryDict_537_0_17(), G__DataLibraryDict_537_0_18(), G__DataLibraryDict_537_0_19(), G__DataLibraryDict_537_0_2(), G__DataLibraryDict_537_0_20(), G__DataLibraryDict_537_0_21(), G__DataLibraryDict_537_0_22(), G__DataLibraryDict_537_0_23(), G__DataLibraryDict_537_0_24(), G__DataLibraryDict_537_0_25(), G__DataLibraryDict_537_0_26(), G__DataLibraryDict_537_0_27(), G__DataLibraryDict_537_0_3(), G__DataLibraryDict_537_0_4(), G__DataLibraryDict_537_0_5(), G__DataLibraryDict_537_0_6(), G__DataLibraryDict_537_0_7(), G__DataLibraryDict_537_0_8(), G__DataLibraryDict_537_0_9(), G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator, G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator, G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR, and G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__memfunc_setup("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >",15214,G__DataLibraryDict_537_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >",15214,G__DataLibraryDict_537_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - first u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >",15214,G__DataLibraryDict_537_0_3, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator' - 0 - first u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >",15214,G__DataLibraryDict_537_0_4, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR), -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__DataLibraryDict_537_0_5, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR), -1, 1, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("begin",517,G__DataLibraryDict_537_0_6, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("end",311,G__DataLibraryDict_537_0_7, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rbegin",631,G__DataLibraryDict_537_0_8, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rend",425,G__DataLibraryDict_537_0_9, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("empty",559,G__DataLibraryDict_537_0_10, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("size",443,G__DataLibraryDict_537_0_11, 107, -1, G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("max_size",864,G__DataLibraryDict_537_0_12, 107, -1, G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__DataLibraryDict_537_0_13, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 1, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_537_0_14, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR), -1, 0, 1, 1, 1, 0, "u 'pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >' 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_537_0_15, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - position u 'pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >' 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_537_0_16, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - first u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_537_0_17, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator' - 0 - first u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_537_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_537_0_19, 107, -1, G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::size_type"), 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_537_0_20, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - first u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("swap",443,G__DataLibraryDict_537_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >' - 1 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("clear",519,G__DataLibraryDict_537_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("find",417,G__DataLibraryDict_537_0_23, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("count",553,G__DataLibraryDict_537_0_24, 107, -1, G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::size_type"), 0, 1, 1, 1, 8, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("lower_bound",1184,G__DataLibraryDict_537_0_25, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("upper_bound",1187,G__DataLibraryDict_537_0_26, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >", 15340, G__DataLibraryDict_537_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void) static
Definition at line 7316 of file DataLibraryDict.cpp.
References G__DataLibraryDict_539_0_1(), G__DataLibraryDict_539_0_10(), G__DataLibraryDict_539_0_11(), G__DataLibraryDict_539_0_12(), G__DataLibraryDict_539_0_2(), G__DataLibraryDict_539_0_3(), G__DataLibraryDict_539_0_4(), G__DataLibraryDict_539_0_5(), G__DataLibraryDict_539_0_6(), G__DataLibraryDict_539_0_7(), G__DataLibraryDict_539_0_8(), G__DataLibraryDict_539_0_9(), G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator, and G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator));
    G__memfunc_setup("iterator",874,G__DataLibraryDict_539_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("iterator",874,G__DataLibraryDict_539_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__DataLibraryDict_539_0_3, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 1, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator*",918,G__DataLibraryDict_539_0_4, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type"), 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator->",983,G__DataLibraryDict_539_0_5, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__DataLibraryDict_539_0_6, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__DataLibraryDict_539_0_7, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - a", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__DataLibraryDict_539_0_8, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__DataLibraryDict_539_0_9, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - a", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator==",998,G__DataLibraryDict_539_0_10, 103, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator!=",970,G__DataLibraryDict_539_0_11, 103, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~iterator", 1000, G__DataLibraryDict_539_0_12, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR (void) static
Definition at line 7011 of file DataLibraryDict.cpp.
References G__DataLibraryDict_523_0_1(), G__DataLibraryDict_523_0_10(), G__DataLibraryDict_523_0_11(), G__DataLibraryDict_523_0_12(), G__DataLibraryDict_523_0_13(), G__DataLibraryDict_523_0_14(), G__DataLibraryDict_523_0_15(), G__DataLibraryDict_523_0_16(), G__DataLibraryDict_523_0_17(), G__DataLibraryDict_523_0_18(), G__DataLibraryDict_523_0_19(), G__DataLibraryDict_523_0_2(), G__DataLibraryDict_523_0_20(), G__DataLibraryDict_523_0_21(), G__DataLibraryDict_523_0_22(), G__DataLibraryDict_523_0_23(), G__DataLibraryDict_523_0_24(), G__DataLibraryDict_523_0_25(), G__DataLibraryDict_523_0_26(), G__DataLibraryDict_523_0_27(), G__DataLibraryDict_523_0_3(), G__DataLibraryDict_523_0_4(), G__DataLibraryDict_523_0_5(), G__DataLibraryDict_523_0_6(), G__DataLibraryDict_523_0_7(), G__DataLibraryDict_523_0_8(), G__DataLibraryDict_523_0_9(), G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator, G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator, G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR, and G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    G__memfunc_setup("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >",14358,G__DataLibraryDict_523_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >",14358,G__DataLibraryDict_523_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 0 - first u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >",14358,G__DataLibraryDict_523_0_3, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator' - 0 - first u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >",14358,G__DataLibraryDict_523_0_4, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR), -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__DataLibraryDict_523_0_5, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR), -1, 1, 1, 1, 1, 0, "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("begin",517,G__DataLibraryDict_523_0_6, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("end",311,G__DataLibraryDict_523_0_7, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rbegin",631,G__DataLibraryDict_523_0_8, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rend",425,G__DataLibraryDict_523_0_9, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("empty",559,G__DataLibraryDict_523_0_10, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("size",443,G__DataLibraryDict_523_0_11, 107, -1, G__defined_typename("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("max_size",864,G__DataLibraryDict_523_0_12, 107, -1, G__defined_typename("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__DataLibraryDict_523_0_13, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR), -1, 1, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_523_0_14, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR), -1, 0, 1, 1, 1, 0, "u 'pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >' 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_523_0_15, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 0 - position u 'pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >' 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_523_0_16, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 0 - first u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_523_0_17, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator' - 0 - first u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_523_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_523_0_19, 107, -1, G__defined_typename("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::size_type"), 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_523_0_20, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 0 - first u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("swap",443,G__DataLibraryDict_523_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >' - 1 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("clear",519,G__DataLibraryDict_523_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("find",417,G__DataLibraryDict_523_0_23, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("count",553,G__DataLibraryDict_523_0_24, 107, -1, G__defined_typename("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::size_type"), 0, 1, 1, 1, 8, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("lower_bound",1184,G__DataLibraryDict_523_0_25, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("upper_bound",1187,G__DataLibraryDict_523_0_26, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >", 14484, G__DataLibraryDict_523_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void) static
Definition at line 7066 of file DataLibraryDict.cpp.
References G__DataLibraryDict_525_0_1(), G__DataLibraryDict_525_0_10(), G__DataLibraryDict_525_0_11(), G__DataLibraryDict_525_0_12(), G__DataLibraryDict_525_0_2(), G__DataLibraryDict_525_0_3(), G__DataLibraryDict_525_0_4(), G__DataLibraryDict_525_0_5(), G__DataLibraryDict_525_0_6(), G__DataLibraryDict_525_0_7(), G__DataLibraryDict_525_0_8(), G__DataLibraryDict_525_0_9(), G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator, and G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator));
    G__memfunc_setup("iterator",874,G__DataLibraryDict_525_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("iterator",874,G__DataLibraryDict_525_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__DataLibraryDict_525_0_3, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 1, 1, 1, 1, 0, "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator*",918,G__DataLibraryDict_525_0_4, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR), G__defined_typename("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::value_type"), 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator->",983,G__DataLibraryDict_525_0_5, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR), G__defined_typename("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::value_type"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__DataLibraryDict_525_0_6, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__DataLibraryDict_525_0_7, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - a", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__DataLibraryDict_525_0_8, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__DataLibraryDict_525_0_9, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - a", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator==",998,G__DataLibraryDict_525_0_10, 103, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator!=",970,G__DataLibraryDict_525_0_11, 103, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~iterator", 1000, G__DataLibraryDict_525_0_12, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncpairlEstringcOstringgR (void) static
Definition at line 6834 of file DataLibraryDict.cpp.
References G__DataLibraryDict_508_0_1(), G__DataLibraryDict_508_0_2(), G__DataLibraryDict_508_0_4(), G__DataLibraryDict_508_0_5(), and G__DataLibraryDictLN_pairlEstringcOstringgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* pair<string,string> */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR));
    G__memfunc_setup("pair<string,string>",1920,G__DataLibraryDict_508_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("pair<string,string>",1920,G__DataLibraryDict_508_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR), -1, 0, 2, 1, 1, 0,
 "u 'string' - 11 - a u 'string' - 11 - b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR), -1, 1, 1, 1, 4, 0, "u 'pair<string,string>' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic copy constructor
    G__memfunc_setup("pair<string,string>", 1920, G__DataLibraryDict_508_0_4, (int) ('i'), G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR), -1, 0, 1, 1, 1, 0, "u 'pair<string,string>' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~pair<string,string>", 2046, G__DataLibraryDict_508_0_5, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void) static
Definition at line 7301 of file DataLibraryDict.cpp.
References G__DataLibraryDict_538_0_1(), G__DataLibraryDict_538_0_2(), G__DataLibraryDict_538_0_4(), G__DataLibraryDict_538_0_5(), and G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
    G__memfunc_setup("pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >",6157,G__DataLibraryDict_538_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >",6157,G__DataLibraryDict_538_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'string' - 11 - a u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >' - 11 - b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), -1, 1, 1, 1, 4, 0, "u 'pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic copy constructor
    G__memfunc_setup("pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >", 6157, G__DataLibraryDict_538_0_4, (int) ('i'),
 G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), -1, 0, 1, 1, 1, 0, "u 'pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >", 6283, G__DataLibraryDict_538_0_5, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void) static
Definition at line 7051 of file DataLibraryDict.cpp.
References G__DataLibraryDict_524_0_1(), G__DataLibraryDict_524_0_2(), G__DataLibraryDict_524_0_4(), G__DataLibraryDict_524_0_5(), and G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR));
    G__memfunc_setup("pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >",5729,G__DataLibraryDict_524_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >",5729,G__DataLibraryDict_524_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'string' - 11 - a u 'vector<TPulseIsland*,allocator<TPulseIsland*> >' - 11 - b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR), -1, 1, 1, 1, 4, 0, "u 'pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic copy constructor
    G__memfunc_setup("pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >", 5729, G__DataLibraryDict_524_0_4, (int) ('i'),
 G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR), -1, 0, 1, 1, 1, 0, "u 'pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >", 5855, G__DataLibraryDict_524_0_5, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncTAnalysedPulse (void) static
Definition at line 7085 of file DataLibraryDict.cpp.
References G__DataLibraryDict_528_0_1(), G__DataLibraryDict_528_0_10(), G__DataLibraryDict_528_0_11(), G__DataLibraryDict_528_0_12(), G__DataLibraryDict_528_0_16(), G__DataLibraryDict_528_0_17(), G__DataLibraryDict_528_0_18(), G__DataLibraryDict_528_0_19(), G__DataLibraryDict_528_0_2(), G__DataLibraryDict_528_0_20(), G__DataLibraryDict_528_0_21(), G__DataLibraryDict_528_0_22(), G__DataLibraryDict_528_0_23(), G__DataLibraryDict_528_0_3(), G__DataLibraryDict_528_0_4(), G__DataLibraryDict_528_0_5(), G__DataLibraryDict_528_0_6(), G__DataLibraryDict_528_0_7(), G__DataLibraryDict_528_0_8(), G__DataLibraryDict_528_0_9(), G__DataLibraryDictLN_string, G__DataLibraryDictLN_TAnalysedPulse, and G__DataLibraryDictLN_TClass.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* TAnalysedPulse */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse));
    G__memfunc_setup("TAnalysedPulse",1422,G__DataLibraryDict_528_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("TAnalysedPulse",1422,G__DataLibraryDict_528_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), -1, 0, 5, 1, 1, 0,
 "d - - 0 - amplitude d - - 0 - time "
 "d - - 0 - integral d - - 0 - energy "
 "u 'string' - 0 - det_name", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Reset",515,G__DataLibraryDict_528_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' o", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetAmplitude",1221,G__DataLibraryDict_528_0_4, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetTime",687,G__DataLibraryDict_528_0_5, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetIntegral",1110,G__DataLibraryDict_528_0_6, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetEnergy",906,G__DataLibraryDict_528_0_7, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetDetName",958,G__DataLibraryDict_528_0_8, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__DataLibraryDict_528_0_9, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TAnalysedPulse::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__DataLibraryDict_528_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TAnalysedPulse::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__DataLibraryDict_528_0_11, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TAnalysedPulse::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__DataLibraryDict_528_0_12, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TAnalysedPulse::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__DataLibraryDict_528_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__DataLibraryDict_528_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TAnalysedPulse::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__DataLibraryDict_528_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TAnalysedPulse::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__DataLibraryDict_528_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TAnalysedPulse::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__DataLibraryDict_528_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TAnalysedPulse::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("TAnalysedPulse", 1422, G__DataLibraryDict_528_0_21, (int) ('i'), G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), -1, 0, 1, 1, 1, 0, "u 'TAnalysedPulse' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TAnalysedPulse", 1548, G__DataLibraryDict_528_0_22, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__DataLibraryDict_528_0_23, (int) ('u'), G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), -1, 1, 1, 1, 1, 0, "u 'TAnalysedPulse' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncTDetectorPulse (void) static
Definition at line 7120 of file DataLibraryDict.cpp.
References G__DataLibraryDict_529_0_1(), G__DataLibraryDict_529_0_10(), G__DataLibraryDict_529_0_11(), G__DataLibraryDict_529_0_12(), G__DataLibraryDict_529_0_13(), G__DataLibraryDict_529_0_14(), G__DataLibraryDict_529_0_18(), G__DataLibraryDict_529_0_19(), G__DataLibraryDict_529_0_2(), G__DataLibraryDict_529_0_20(), G__DataLibraryDict_529_0_21(), G__DataLibraryDict_529_0_22(), G__DataLibraryDict_529_0_23(), G__DataLibraryDict_529_0_24(), G__DataLibraryDict_529_0_25(), G__DataLibraryDict_529_0_3(), G__DataLibraryDict_529_0_4(), G__DataLibraryDict_529_0_5(), G__DataLibraryDict_529_0_6(), G__DataLibraryDict_529_0_7(), G__DataLibraryDict_529_0_8(), G__DataLibraryDict_529_0_9(), G__DataLibraryDictLN_string, G__DataLibraryDictLN_TClass, and G__DataLibraryDictLN_TDetectorPulse.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* TDetectorPulse */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TDetectorPulse));
    G__memfunc_setup("TDetectorPulse",1431,G__DataLibraryDict_529_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_TDetectorPulse), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("TDetectorPulse",1431,G__DataLibraryDict_529_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_TDetectorPulse), -1, 0, 3, 1, 1, 0,
 "U 'TAnalysedPulse' - 0 - fast_pulse U 'TAnalysedPulse' - 0 - slow_pulse "
 "u 'string' - 0 - det_name", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Reset",515,G__DataLibraryDict_529_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' o", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetFastPulseAmplitude",2140,G__DataLibraryDict_529_0_4, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetSlowPulseAmplitude",2163,G__DataLibraryDict_529_0_5, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetFastPulseTime",1606,G__DataLibraryDict_529_0_6, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetSlowPulseTime",1629,G__DataLibraryDict_529_0_7, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetFastPulseIntegral",2029,G__DataLibraryDict_529_0_8, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetSlowPulseIntegral",2052,G__DataLibraryDict_529_0_9, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetDetName",958,G__DataLibraryDict_529_0_10, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__DataLibraryDict_529_0_11, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TDetectorPulse::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__DataLibraryDict_529_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDetectorPulse::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__DataLibraryDict_529_0_13, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TDetectorPulse::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__DataLibraryDict_529_0_14, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TDetectorPulse::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__DataLibraryDict_529_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__DataLibraryDict_529_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDetectorPulse::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__DataLibraryDict_529_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDetectorPulse::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__DataLibraryDict_529_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDetectorPulse::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__DataLibraryDict_529_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDetectorPulse::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("TDetectorPulse", 1431, G__DataLibraryDict_529_0_23, (int) ('i'), G__get_linked_tagnum(&G__DataLibraryDictLN_TDetectorPulse), -1, 0, 1, 1, 1, 0, "u 'TDetectorPulse' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TDetectorPulse", 1557, G__DataLibraryDict_529_0_24, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__DataLibraryDict_529_0_25, (int) ('u'), G__get_linked_tagnum(&G__DataLibraryDictLN_TDetectorPulse), -1, 1, 1, 1, 1, 0, "u 'TDetectorPulse' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncTGlobalData (void) static
Definition at line 6911 of file DataLibraryDict.cpp.
References G__DataLibraryDict_516_0_1(), G__DataLibraryDict_516_0_10(), G__DataLibraryDict_516_0_11(), G__DataLibraryDict_516_0_12(), G__DataLibraryDict_516_0_13(), G__DataLibraryDict_516_0_14(), G__DataLibraryDict_516_0_15(), G__DataLibraryDict_516_0_16(), G__DataLibraryDict_516_0_17(), G__DataLibraryDict_516_0_2(), G__DataLibraryDict_516_0_3(), G__DataLibraryDict_516_0_4(), G__DataLibraryDict_516_0_5(), G__DataLibraryDict_516_0_9(), G__DataLibraryDictLN_TClass, G__DataLibraryDictLN_TGlobalData, and TGlobalData::Instance().
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* TGlobalData */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TGlobalData));
    G__memfunc_setup("Instance",821,G__DataLibraryDict_516_0_1, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TGlobalData), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TGlobalData* (*)())(&TGlobalData::Instance) ), 0);
    G__memfunc_setup("Class",502,G__DataLibraryDict_516_0_2, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TGlobalData::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__DataLibraryDict_516_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TGlobalData::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__DataLibraryDict_516_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TGlobalData::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__DataLibraryDict_516_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TGlobalData::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__DataLibraryDict_516_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__DataLibraryDict_516_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TGlobalData::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__DataLibraryDict_516_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TGlobalData::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__DataLibraryDict_516_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TGlobalData::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__DataLibraryDict_516_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TGlobalData::DeclFileLine) ), 0);
    // automatic default constructor
    G__memfunc_setup("TGlobalData", 1055, G__DataLibraryDict_516_0_14, (int) ('i'), G__get_linked_tagnum(&G__DataLibraryDictLN_TGlobalData), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    // automatic copy constructor
    G__memfunc_setup("TGlobalData", 1055, G__DataLibraryDict_516_0_15, (int) ('i'), G__get_linked_tagnum(&G__DataLibraryDictLN_TGlobalData), -1, 0, 1, 1, 1, 0, "u 'TGlobalData' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TGlobalData", 1181, G__DataLibraryDict_516_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__DataLibraryDict_516_0_17, (int) ('u'), G__get_linked_tagnum(&G__DataLibraryDictLN_TGlobalData), -1, 1, 1, 1, 1, 0, "u 'TGlobalData' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncTPulseIsland (void) static
Definition at line 6867 of file DataLibraryDict.cpp.
References G__DataLibraryDict_512_0_1(), G__DataLibraryDict_512_0_10(), G__DataLibraryDict_512_0_11(), G__DataLibraryDict_512_0_12(), G__DataLibraryDict_512_0_13(), G__DataLibraryDict_512_0_14(), G__DataLibraryDict_512_0_15(), G__DataLibraryDict_512_0_16(), G__DataLibraryDict_512_0_17(), G__DataLibraryDict_512_0_18(), G__DataLibraryDict_512_0_19(), G__DataLibraryDict_512_0_2(), G__DataLibraryDict_512_0_20(), G__DataLibraryDict_512_0_21(), G__DataLibraryDict_512_0_25(), G__DataLibraryDict_512_0_26(), G__DataLibraryDict_512_0_27(), G__DataLibraryDict_512_0_28(), G__DataLibraryDict_512_0_29(), G__DataLibraryDict_512_0_3(), G__DataLibraryDict_512_0_30(), G__DataLibraryDict_512_0_31(), G__DataLibraryDict_512_0_32(), G__DataLibraryDict_512_0_4(), G__DataLibraryDict_512_0_5(), G__DataLibraryDict_512_0_6(), G__DataLibraryDict_512_0_7(), G__DataLibraryDict_512_0_8(), G__DataLibraryDict_512_0_9(), G__DataLibraryDictLN_string, G__DataLibraryDictLN_TClass, G__DataLibraryDictLN_TH1I, G__DataLibraryDictLN_TPulseIsland, and G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* TPulseIsland */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland));
    G__memfunc_setup("TPulseIsland",1208,G__DataLibraryDict_512_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("TPulseIsland",1208,G__DataLibraryDict_512_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), -1, 0, 3, 1, 1, 0,
 "i - - 0 - timestamp u 'vector<int,allocator<int> >' 'vector<int>' 11 - samples_vector "
 "u 'string' - 0 - bank_name", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Reset",515,G__DataLibraryDict_512_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' o", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetSamples",1013,G__DataLibraryDict_512_0_4, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetTimeStamp",1204,G__DataLibraryDict_512_0_5, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetBankName",1053,G__DataLibraryDict_512_0_6, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetClockTickInNs",1551,G__DataLibraryDict_512_0_7, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetTriggerPolarity",1864,G__DataLibraryDict_512_0_8, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetAmplitude",1221,G__DataLibraryDict_512_0_9, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetFastPulseAmplitude",2140,G__DataLibraryDict_512_0_10, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetSlowPulseAmplitude",2163,G__DataLibraryDict_512_0_11, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPulseHeight",1410,G__DataLibraryDict_512_0_12, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPulseTime",1208,G__DataLibraryDict_512_0_13, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPulseWaveform",1648,G__DataLibraryDict_512_0_14, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TH1I), -1, 0, 2, 1, 1, 8,
 "u 'string' - 0 - histname u 'string' - 0 - histtitle", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPulseLength",1419,G__DataLibraryDict_512_0_15, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPeakSample",1283,G__DataLibraryDict_512_0_16, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPedestal",1106,G__DataLibraryDict_512_0_17, 100, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - nPedSamples", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__DataLibraryDict_512_0_18, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TPulseIsland::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__DataLibraryDict_512_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPulseIsland::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__DataLibraryDict_512_0_20, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TPulseIsland::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__DataLibraryDict_512_0_21, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TPulseIsland::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__DataLibraryDict_512_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__DataLibraryDict_512_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPulseIsland::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__DataLibraryDict_512_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPulseIsland::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__DataLibraryDict_512_0_28, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPulseIsland::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__DataLibraryDict_512_0_29, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPulseIsland::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("TPulseIsland", 1208, G__DataLibraryDict_512_0_30, (int) ('i'), G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), -1, 0, 1, 1, 1, 0, "u 'TPulseIsland' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TPulseIsland", 1334, G__DataLibraryDict_512_0_31, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__DataLibraryDict_512_0_32, (int) ('u'), G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), -1, 1, 1, 1, 1, 0, "u 'TPulseIsland' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncTSetupData (void) static
Definition at line 6732 of file DataLibraryDict.cpp.
References G__DataLibraryDict_504_0_1(), G__DataLibraryDict_504_0_10(), G__DataLibraryDict_504_0_11(), G__DataLibraryDict_504_0_12(), G__DataLibraryDict_504_0_13(), G__DataLibraryDict_504_0_14(), G__DataLibraryDict_504_0_15(), G__DataLibraryDict_504_0_16(), G__DataLibraryDict_504_0_17(), G__DataLibraryDict_504_0_18(), G__DataLibraryDict_504_0_19(), G__DataLibraryDict_504_0_2(), G__DataLibraryDict_504_0_20(), G__DataLibraryDict_504_0_21(), G__DataLibraryDict_504_0_22(), G__DataLibraryDict_504_0_23(), G__DataLibraryDict_504_0_24(), G__DataLibraryDict_504_0_27(), G__DataLibraryDict_504_0_28(), G__DataLibraryDict_504_0_29(), G__DataLibraryDict_504_0_3(), G__DataLibraryDict_504_0_30(), G__DataLibraryDict_504_0_34(), G__DataLibraryDict_504_0_35(), G__DataLibraryDict_504_0_36(), G__DataLibraryDict_504_0_37(), G__DataLibraryDict_504_0_38(), G__DataLibraryDict_504_0_39(), G__DataLibraryDict_504_0_4(), G__DataLibraryDict_504_0_40(), G__DataLibraryDict_504_0_41(), G__DataLibraryDict_504_0_42(), G__DataLibraryDict_504_0_5(), G__DataLibraryDict_504_0_6(), G__DataLibraryDict_504_0_7(), G__DataLibraryDict_504_0_8(), G__DataLibraryDict_504_0_9(), G__DataLibraryDictLN_string, G__DataLibraryDictLN_TClass, G__DataLibraryDictLN_TSetupData, TSetupData::Instance(), TSetupData::IsBostonCAEN(), TSetupData::IsFADC(), TSetupData::IsFast(), TSetupData::IsHoustonCAEN(), and TSetupData::IsSlow().
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* TSetupData */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TSetupData));
    G__memfunc_setup("Instance",821,G__DataLibraryDict_504_0_1, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TSetupData), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TSetupData* (*)())(&TSetupData::Instance) ), 0);
    G__memfunc_setup("GetBankName",1053,G__DataLibraryDict_504_0_2, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_string), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - DetectorName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetDetectorName",1499,G__DataLibraryDict_504_0_3, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_string), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetAllDetectors",1510,G__DataLibraryDict_504_0_4, 121, -1, -1, 0, 1, 1, 1, 8, "u 'map<string,string,less<string>,allocator<pair<const string,string> > >' 'map<std::string,std::string>' 1 - detectors", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetClockTick",1175,G__DataLibraryDict_504_0_5, 100, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetNBits",768,G__DataLibraryDict_504_0_6, 105, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetADCSlopeCalib",1478,G__DataLibraryDict_504_0_7, 100, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetADCOffsetCalib",1578,G__DataLibraryDict_504_0_8, 100, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetTimeShift",1197,G__DataLibraryDict_504_0_9, 100, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetTriggerPolarity",1864,G__DataLibraryDict_504_0_10, 105, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetPedestal",1106,G__DataLibraryDict_504_0_11, 105, -1, -1, 0, 1, 1, 1, 8, "u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetDetectorName",1511,G__DataLibraryDict_504_0_12, 103, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName u 'string' - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetClockTick",1187,G__DataLibraryDict_504_0_13, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName d - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetNBits",780,G__DataLibraryDict_504_0_14, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName i - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetTimeShift",1209,G__DataLibraryDict_504_0_15, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName d - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetTriggerPolarity",1876,G__DataLibraryDict_504_0_16, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName i - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetPedestal",1118,G__DataLibraryDict_504_0_17, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName i - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetADCSlopeCalib",1490,G__DataLibraryDict_504_0_18, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName d - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetADCOffsetCalib",1590,G__DataLibraryDict_504_0_19, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'string' - 0 - BankName d - - 0 - value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("IsFADC",458,G__DataLibraryDict_504_0_20, 103, -1, -1, 0, 1, 3, 1, 0, "u 'string' - 11 - BankName", "if the first letter is N then the bank name is for a FADC", (void*) G__func2void( (bool (*)(const string&))(&TSetupData::IsFADC) ), 0);
    G__memfunc_setup("IsHoustonCAEN",1219,G__DataLibraryDict_504_0_21, 103, -1, -1, 0, 1, 3, 1, 0, "u 'string' - 11 - BankName", "if the first letter is C then the bank name is for a CAEN", (void*) G__func2void( (bool (*)(const string&))(&TSetupData::IsHoustonCAEN) ), 0);
    G__memfunc_setup("IsBostonCAEN",1096,G__DataLibraryDict_504_0_22, 103, -1, -1, 0, 1, 3, 1, 0, "u 'string' - 11 - BankName", "if the first letter is C then the bank name is for a CAEN", (void*) G__func2void( (bool (*)(const string&))(&TSetupData::IsBostonCAEN) ), 0);
    G__memfunc_setup("IsSlow",609,G__DataLibraryDict_504_0_23, 103, -1, -1, 0, 1, 3, 1, 0, "u 'string' - 11 - BankName", "if the last letter is S then the bank name is for a Slow pulse", (void*) G__func2void( (bool (*)(const string&))(&TSetupData::IsSlow) ), 0);
    G__memfunc_setup("IsFast",586,G__DataLibraryDict_504_0_24, 103, -1, -1, 0, 1, 3, 1, 0, "u 'string' - 11 - BankName", "if the last letter is F then the bank name is for a Fast pulse", (void*) G__func2void( (bool (*)(const string&))(&TSetupData::IsFast) ), 0);
    G__memfunc_setup("GetValue",797,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 2, 1, 4, 8,
 "u 'map<string,double,less<string>,allocator<pair<const string,double> > >' 'map<std::string,double>' 11 - map u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetValue",797,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 2, 1, 4, 8,
 "u 'map<string,int,less<string>,allocator<pair<const string,int> > >' 'map<std::string,int>' 11 - map u 'string' - 11 - BankName", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__DataLibraryDict_504_0_27, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TSetupData::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__DataLibraryDict_504_0_28, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSetupData::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__DataLibraryDict_504_0_29, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TSetupData::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__DataLibraryDict_504_0_30, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TSetupData::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__DataLibraryDict_504_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__DataLibraryDict_504_0_35, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSetupData::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__DataLibraryDict_504_0_36, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TSetupData::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__DataLibraryDict_504_0_37, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TSetupData::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__DataLibraryDict_504_0_38, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TSetupData::DeclFileLine) ), 0);
    // automatic default constructor
    G__memfunc_setup("TSetupData", 991, G__DataLibraryDict_504_0_39, (int) ('i'), G__get_linked_tagnum(&G__DataLibraryDictLN_TSetupData), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    // automatic copy constructor
    G__memfunc_setup("TSetupData", 991, G__DataLibraryDict_504_0_40, (int) ('i'), G__get_linked_tagnum(&G__DataLibraryDictLN_TSetupData), -1, 0, 1, 1, 1, 0, "u 'TSetupData' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TSetupData", 1117, G__DataLibraryDict_504_0_41, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__DataLibraryDict_504_0_42, (int) ('u'), G__get_linked_tagnum(&G__DataLibraryDictLN_TSetupData), -1, 1, 1, 1, 1, 0, "u 'TSetupData' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncTVacuumData (void) static
Definition at line 7156 of file DataLibraryDict.cpp.
References G__DataLibraryDict_530_0_1(), G__DataLibraryDict_530_0_12(), G__DataLibraryDict_530_0_13(), G__DataLibraryDict_530_0_14(), G__DataLibraryDict_530_0_15(), G__DataLibraryDict_530_0_16(), G__DataLibraryDict_530_0_17(), G__DataLibraryDict_530_0_18(), G__DataLibraryDict_530_0_19(), G__DataLibraryDict_530_0_2(), G__DataLibraryDict_530_0_3(), G__DataLibraryDict_530_0_4(), G__DataLibraryDict_530_0_5(), G__DataLibraryDict_530_0_6(), G__DataLibraryDict_530_0_7(), G__DataLibraryDict_530_0_8(), G__DataLibraryDictLN_TClass, and G__DataLibraryDictLN_TVacuumData.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* TVacuumData */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TVacuumData));
    G__memfunc_setup("TVacuumData",1087,G__DataLibraryDict_530_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_TVacuumData), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("TVacuumData",1087,G__DataLibraryDict_530_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_TVacuumData), -1, 0, 3, 1, 1, 0,
 "u 'vector<int,allocator<int> >' 'vector<int>' 0 - time u 'vector<int,allocator<int> >' 'vector<int>' 0 - status "
 "u 'vector<float,allocator<float> >' 'vector<float>' 0 - pressure", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Reset",515,G__DataLibraryDict_530_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' o", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("AddPoint",787,G__DataLibraryDict_530_0_4, 121, -1, -1, 0, 3, 1, 1, 0,
 "i - - 0 - time i - - 0 - status "
 "f - - 0 - pressure", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__DataLibraryDict_530_0_5, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TVacuumData::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__DataLibraryDict_530_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVacuumData::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__DataLibraryDict_530_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TVacuumData::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__DataLibraryDict_530_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TVacuumData::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DataLibraryDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__DataLibraryDict_530_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__DataLibraryDict_530_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVacuumData::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__DataLibraryDict_530_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TVacuumData::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__DataLibraryDict_530_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TVacuumData::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__DataLibraryDict_530_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TVacuumData::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("TVacuumData", 1087, G__DataLibraryDict_530_0_17, (int) ('i'), G__get_linked_tagnum(&G__DataLibraryDictLN_TVacuumData), -1, 0, 1, 1, 1, 0, "u 'TVacuumData' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TVacuumData", 1213, G__DataLibraryDict_530_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__DataLibraryDict_530_0_19, (int) ('u'), G__get_linked_tagnum(&G__DataLibraryDictLN_TVacuumData), -1, 1, 1, 1, 1, 0, "u 'TVacuumData' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR (void) static
Definition at line 7188 of file DataLibraryDict.cpp.
References G__DataLibraryDict_532_0_1(), G__DataLibraryDict_532_0_10(), G__DataLibraryDict_532_0_11(), G__DataLibraryDict_532_0_12(), G__DataLibraryDict_532_0_13(), G__DataLibraryDict_532_0_14(), G__DataLibraryDict_532_0_15(), G__DataLibraryDict_532_0_16(), G__DataLibraryDict_532_0_17(), G__DataLibraryDict_532_0_18(), G__DataLibraryDict_532_0_19(), G__DataLibraryDict_532_0_2(), G__DataLibraryDict_532_0_20(), G__DataLibraryDict_532_0_21(), G__DataLibraryDict_532_0_22(), G__DataLibraryDict_532_0_23(), G__DataLibraryDict_532_0_24(), G__DataLibraryDict_532_0_25(), G__DataLibraryDict_532_0_26(), G__DataLibraryDict_532_0_27(), G__DataLibraryDict_532_0_28(), G__DataLibraryDict_532_0_29(), G__DataLibraryDict_532_0_3(), G__DataLibraryDict_532_0_30(), G__DataLibraryDict_532_0_31(), G__DataLibraryDict_532_0_32(), G__DataLibraryDict_532_0_4(), G__DataLibraryDict_532_0_5(), G__DataLibraryDict_532_0_6(), G__DataLibraryDict_532_0_7(), G__DataLibraryDict_532_0_8(), G__DataLibraryDict_532_0_9(), G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR, G__DataLibraryDictLN_TAnalysedPulse, G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR, and G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__memfunc_setup("at",213,G__DataLibraryDict_532_0_1, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("at",213,G__DataLibraryDict_532_0_2, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("begin",517,G__DataLibraryDict_532_0_3, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("end",311,G__DataLibraryDict_532_0_4, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rbegin",631,G__DataLibraryDict_532_0_5, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rend",425,G__DataLibraryDict_532_0_6, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("size",443,G__DataLibraryDict_532_0_7, 107, -1, G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("max_size",864,G__DataLibraryDict_532_0_8, 107, -1, G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("resize",658,G__DataLibraryDict_532_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - sz", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("resize",658,G__DataLibraryDict_532_0_10, 121, -1, -1, 0, 2, 1, 1, 0,
 "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - sz U 'TAnalysedPulse' - 0 - c", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("capacity",846,G__DataLibraryDict_532_0_11, 107, -1, G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("empty",559,G__DataLibraryDict_532_0_12, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__DataLibraryDict_532_0_13, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__DataLibraryDict_532_0_14, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >",4868,G__DataLibraryDict_532_0_15, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >",4868,G__DataLibraryDict_532_0_16, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 0, 2, 1, 1, 0,
 "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n U 'TAnalysedPulse' - 41 '(TAnalysedPulse*)()' value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >",4868,G__DataLibraryDict_532_0_17, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 0, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >",4868,G__DataLibraryDict_532_0_18, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator' 10 - first u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__DataLibraryDict_532_0_19, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 1, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("reserve",764,G__DataLibraryDict_532_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("front",553,G__DataLibraryDict_532_0_21, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("back",401,G__DataLibraryDict_532_0_22, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("push_back",944,G__DataLibraryDict_532_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TAnalysedPulse' - 41 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("swap",443,G__DataLibraryDict_532_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >' - 1 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_532_0_25, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - position U 'TAnalysedPulse' - 41 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_532_0_26, 121, -1, -1, 0, 3, 1, 1, 0,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - position u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator' 10 - first "
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_532_0_27, 121, -1, -1, 0, 3, 1, 1, 0,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - position k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n "
 "U 'TAnalysedPulse' - 41 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("pop_back",831,G__DataLibraryDict_532_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_532_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_532_0_30, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - first u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("clear",519,G__DataLibraryDict_532_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >", 4994, G__DataLibraryDict_532_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void) static
Definition at line 7236 of file DataLibraryDict.cpp.
References G__DataLibraryDict_533_0_1(), G__DataLibraryDict_533_0_10(), G__DataLibraryDict_533_0_11(), G__DataLibraryDict_533_0_12(), G__DataLibraryDict_533_0_13(), G__DataLibraryDict_533_0_14(), G__DataLibraryDict_533_0_15(), G__DataLibraryDict_533_0_16(), G__DataLibraryDict_533_0_17(), G__DataLibraryDict_533_0_2(), G__DataLibraryDict_533_0_3(), G__DataLibraryDict_533_0_4(), G__DataLibraryDict_533_0_5(), G__DataLibraryDict_533_0_6(), G__DataLibraryDict_533_0_7(), G__DataLibraryDict_533_0_8(), G__DataLibraryDict_533_0_9(), G__DataLibraryDictLN_TAnalysedPulse, and G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__memfunc_setup("iterator",874,G__DataLibraryDict_533_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("iterator",874,G__DataLibraryDict_533_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 5, 1, 0, "U 'TAnalysedPulse' 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer' 11 - __i", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator*",918,G__DataLibraryDict_533_0_3, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::reference"), 1, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator->",983,G__DataLibraryDict_533_0_4, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__DataLibraryDict_533_0_5, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__DataLibraryDict_533_0_6, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__DataLibraryDict_533_0_7, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__DataLibraryDict_533_0_8, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__DataLibraryDict_533_0_9, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::reference"), 1, 1, 1, 1, 8, "l - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator+=",980,G__DataLibraryDict_533_0_10, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 1, 1, 1, 1, 0, "l - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator+",919,G__DataLibraryDict_533_0_11, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 8, "l - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator-=",982,G__DataLibraryDict_533_0_12, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 1, 1, 1, 1, 0, "l - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator-",921,G__DataLibraryDict_533_0_13, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 8, "l - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("base",411,G__DataLibraryDict_533_0_14, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer"), 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__DataLibraryDict_533_0_15, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic copy constructor
    G__memfunc_setup("iterator", 874, G__DataLibraryDict_533_0_16, (int) ('i'), G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~iterator", 1000, G__DataLibraryDict_533_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR (void) static
Definition at line 6938 of file DataLibraryDict.cpp.
References G__DataLibraryDict_518_0_1(), G__DataLibraryDict_518_0_10(), G__DataLibraryDict_518_0_11(), G__DataLibraryDict_518_0_12(), G__DataLibraryDict_518_0_13(), G__DataLibraryDict_518_0_14(), G__DataLibraryDict_518_0_15(), G__DataLibraryDict_518_0_16(), G__DataLibraryDict_518_0_17(), G__DataLibraryDict_518_0_18(), G__DataLibraryDict_518_0_19(), G__DataLibraryDict_518_0_2(), G__DataLibraryDict_518_0_20(), G__DataLibraryDict_518_0_21(), G__DataLibraryDict_518_0_22(), G__DataLibraryDict_518_0_23(), G__DataLibraryDict_518_0_24(), G__DataLibraryDict_518_0_25(), G__DataLibraryDict_518_0_26(), G__DataLibraryDict_518_0_27(), G__DataLibraryDict_518_0_28(), G__DataLibraryDict_518_0_29(), G__DataLibraryDict_518_0_3(), G__DataLibraryDict_518_0_30(), G__DataLibraryDict_518_0_31(), G__DataLibraryDict_518_0_32(), G__DataLibraryDict_518_0_4(), G__DataLibraryDict_518_0_5(), G__DataLibraryDict_518_0_6(), G__DataLibraryDict_518_0_7(), G__DataLibraryDict_518_0_8(), G__DataLibraryDict_518_0_9(), G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR, G__DataLibraryDictLN_TPulseIsland, G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR, and G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* vector<TPulseIsland*,allocator<TPulseIsland*> > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__memfunc_setup("at",213,G__DataLibraryDict_518_0_1, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("at",213,G__DataLibraryDict_518_0_2, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("begin",517,G__DataLibraryDict_518_0_3, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("end",311,G__DataLibraryDict_518_0_4, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rbegin",631,G__DataLibraryDict_518_0_5, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR), G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rend",425,G__DataLibraryDict_518_0_6, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR), G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("size",443,G__DataLibraryDict_518_0_7, 107, -1, G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("max_size",864,G__DataLibraryDict_518_0_8, 107, -1, G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("resize",658,G__DataLibraryDict_518_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type' 0 - sz", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("resize",658,G__DataLibraryDict_518_0_10, 121, -1, -1, 0, 2, 1, 1, 0,
 "k - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type' 0 - sz U 'TPulseIsland' - 0 - c", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("capacity",846,G__DataLibraryDict_518_0_11, 107, -1, G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("empty",559,G__DataLibraryDict_518_0_12, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__DataLibraryDict_518_0_13, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__DataLibraryDict_518_0_14, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TPulseIsland*,allocator<TPulseIsland*> >",4440,G__DataLibraryDict_518_0_15, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TPulseIsland*,allocator<TPulseIsland*> >",4440,G__DataLibraryDict_518_0_16, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR), -1, 0, 2, 1, 1, 0,
 "k - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type' 0 - n U 'TPulseIsland' - 41 '(TPulseIsland*)()' value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TPulseIsland*,allocator<TPulseIsland*> >",4440,G__DataLibraryDict_518_0_17, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR), -1, 0, 1, 1, 1, 0, "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TPulseIsland*,allocator<TPulseIsland*> >",4440,G__DataLibraryDict_518_0_18, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' 'vector<TPulseIsland*,allocator<TPulseIsland*> >::const_iterator' 10 - first u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' 'vector<TPulseIsland*,allocator<TPulseIsland*> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__DataLibraryDict_518_0_19, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR), -1, 1, 1, 1, 1, 0, "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("reserve",764,G__DataLibraryDict_518_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("front",553,G__DataLibraryDict_518_0_21, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("back",401,G__DataLibraryDict_518_0_22, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("push_back",944,G__DataLibraryDict_518_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TPulseIsland' - 41 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("swap",443,G__DataLibraryDict_518_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >' - 1 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_518_0_25, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0,
 "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' - 0 - position U 'TPulseIsland' - 41 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_518_0_26, 121, -1, -1, 0, 3, 1, 1, 0,
 "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' - 0 - position u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' 'vector<TPulseIsland*,allocator<TPulseIsland*> >::const_iterator' 10 - first "
 "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' 'vector<TPulseIsland*,allocator<TPulseIsland*> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__DataLibraryDict_518_0_27, 121, -1, -1, 0, 3, 1, 1, 0,
 "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' - 0 - position k - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::size_type' 0 - n "
 "U 'TPulseIsland' - 41 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("pop_back",831,G__DataLibraryDict_518_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_518_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__DataLibraryDict_518_0_30, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' - 0 - first u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("clear",519,G__DataLibraryDict_518_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~vector<TPulseIsland*,allocator<TPulseIsland*> >", 4566, G__DataLibraryDict_518_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void) static
Definition at line 6986 of file DataLibraryDict.cpp.
References G__DataLibraryDict_519_0_1(), G__DataLibraryDict_519_0_10(), G__DataLibraryDict_519_0_11(), G__DataLibraryDict_519_0_12(), G__DataLibraryDict_519_0_13(), G__DataLibraryDict_519_0_14(), G__DataLibraryDict_519_0_15(), G__DataLibraryDict_519_0_16(), G__DataLibraryDict_519_0_17(), G__DataLibraryDict_519_0_2(), G__DataLibraryDict_519_0_3(), G__DataLibraryDict_519_0_4(), G__DataLibraryDict_519_0_5(), G__DataLibraryDict_519_0_6(), G__DataLibraryDict_519_0_7(), G__DataLibraryDict_519_0_8(), G__DataLibraryDict_519_0_9(), G__DataLibraryDictLN_TPulseIsland, and G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    /* vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator));
    G__memfunc_setup("iterator",874,G__DataLibraryDict_519_0_1, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("iterator",874,G__DataLibraryDict_519_0_2, 105, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 0, 1, 5, 1, 0, "U 'TPulseIsland' 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::pointer' 11 - __i", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator*",918,G__DataLibraryDict_519_0_3, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::reference"), 1, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator->",983,G__DataLibraryDict_519_0_4, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::pointer"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__DataLibraryDict_519_0_5, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__DataLibraryDict_519_0_6, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__DataLibraryDict_519_0_7, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__DataLibraryDict_519_0_8, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__DataLibraryDict_519_0_9, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::reference"), 1, 1, 1, 1, 8, "l - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator+=",980,G__DataLibraryDict_519_0_10, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 1, 1, 1, 1, 0, "l - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator+",919,G__DataLibraryDict_519_0_11, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 8, "l - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator-=",982,G__DataLibraryDict_519_0_12, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 1, 1, 1, 1, 0, "l - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator-",921,G__DataLibraryDict_519_0_13, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 8, "l - 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("base",411,G__DataLibraryDict_519_0_14, 85, G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland), G__defined_typename("vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator::pointer"), 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__DataLibraryDict_519_0_15, 117, G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic copy constructor
    G__memfunc_setup("iterator", 874, G__DataLibraryDict_519_0_16, (int) ('i'), G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~iterator", 1000, G__DataLibraryDict_519_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memvarmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR (void) static
Definition at line 6532 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR));
    { map<string,string,less<string>,allocator<pair<const string,string> > > *p; p=(map<string,string,less<string>,allocator<pair<const string,string> > >*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator (void) static
Definition at line 6552 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator));
    { map<string,string,less<string>,allocator<pair<const string,string> > >::iterator *p; p=(map<string,string,less<string>,allocator<pair<const string,string> > >::iterator*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR (void) static
Definition at line 6691 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    { map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > > *p; p=(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void) static
Definition at line 6711 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator));
    { map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator *p; p=(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR (void) static
Definition at line 6603 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR));
    { map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > > *p; p=(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator (void) static
Definition at line 6623 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator));
    { map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator *p; p=(map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarpairlEstringcOstringgR (void) static
Definition at line 6541 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOstringgR, and G__DataLibraryDictLN_string.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOstringgR));
    { pair<string,string> *p; p=(pair<string,string>*)0x1000; if (p) { }
    G__memvar_setup((void*)((long)(&p->first)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_string),-1,-1,1,"first=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->second)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_string),-1,-1,1,"second=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void) static
Definition at line 6700 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR, G__DataLibraryDictLN_string, and G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
    { pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > *p; p=(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*)0x1000; if (p) { }
    G__memvar_setup((void*)((long)(&p->first)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_string),-1,-1,1,"first=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->second)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR),-1,-1,1,"second=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarpairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR (void) static
Definition at line 6612 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR, G__DataLibraryDictLN_string, and G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR));
    { pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > > *p; p=(pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >*)0x1000; if (p) { }
    G__memvar_setup((void*)((long)(&p->first)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_string),-1,-1,1,"first=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->second)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR),-1,-1,1,"second=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarTAnalysedPulse (void) static
Definition at line 6632 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_string, G__DataLibraryDictLN_TAnalysedPulse, and G__DataLibraryDictLN_TClass.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse));
    { TAnalysedPulse *p; p=(TAnalysedPulse*)0x1000; if (p) { }
    G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fAmplitude=",0,(char*)NULL);
    G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fTime=",0,(char*)NULL);
    G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fIntegral=",0,(char*)NULL);
    G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fEnergy=",0,(char*)NULL);
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_string),-1,-1,4,"fDetName=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarTDetectorPulse (void) static
Definition at line 6647 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_string, G__DataLibraryDictLN_TAnalysedPulse, G__DataLibraryDictLN_TClass, and G__DataLibraryDictLN_TDetectorPulse.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TDetectorPulse));
    { TDetectorPulse *p; p=(TDetectorPulse*)0x1000; if (p) { }
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),-1,-1,4,"fFastPulse=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_TAnalysedPulse),-1,-1,4,"fSlowPulse=",0,(char*)NULL);
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_string),-1,-1,4,"fDetName=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarTGlobalData (void) static
Definition at line 6574 of file DataLibraryDict.cpp.
References TGlobalData::fPulseIslandToChannelMap, G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__DataLibraryDictLN_TClass, and G__DataLibraryDictLN_TGlobalData.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TGlobalData));
    { TGlobalData *p; p=(TGlobalData*)0x1000; if (p) { }
    G__memvar_setup((void*)((long)(&p->fPulseIslandToChannelMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),G__defined_typename("map<std::string,std::vector<TPulseIsland*> >"),-1,1,"fPulseIslandToChannelMap=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarTPulseIsland (void) static
Definition at line 6561 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_string, G__DataLibraryDictLN_TClass, G__DataLibraryDictLN_TPulseIsland, and G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TPulseIsland));
    { TPulseIsland *p; p=(TPulseIsland*)0x1000; if (p) { }
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"fSamples=",0,"adc samples");
    G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fTimeStamp=",0,"time stamp in clock ticks");
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_string),-1,-1,4,"fBankName=",0,"FADC Bank name of this island's channel");
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarTSetupData (void) static
Definition at line 6514 of file DataLibraryDict.cpp.
References TSetupData::fBankToADCOffsetCalibMap, TSetupData::fBankToADCSlopeCalibMap, TSetupData::fBankToBitMap, TSetupData::fBankToClockTickMap, TSetupData::fBankToDetectorMap, TSetupData::fBankToPedestalMap, TSetupData::fBankToPolarityMap, TSetupData::fBankToTimeShift, G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR, G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR, G__DataLibraryDictLN_TClass, and G__DataLibraryDictLN_TSetupData.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TSetupData));
    { TSetupData *p; p=(TSetupData*)0x1000; if (p) { }
    G__memvar_setup((void*)((long)(&p->fBankToDetectorMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),G__defined_typename("map<std::string,std::string>"),-1,1,"fBankToDetectorMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToClockTickMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),G__defined_typename("map<std::string,double>"),-1,1,"fBankToClockTickMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToBitMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),G__defined_typename("map<std::string,int>"),-1,1,"fBankToBitMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToADCSlopeCalibMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),G__defined_typename("map<std::string,double>"),-1,1,"fBankToADCSlopeCalibMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToADCOffsetCalibMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),G__defined_typename("map<std::string,double>"),-1,1,"fBankToADCOffsetCalibMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToTimeShift)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),G__defined_typename("map<std::string,double>"),-1,1,"fBankToTimeShift=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToPolarityMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),G__defined_typename("map<std::string,int>"),-1,1,"fBankToPolarityMap=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->fBankToPedestalMap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),G__defined_typename("map<std::string,int>"),-1,1,"fBankToPedestalMap=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarTVacuumData (void) static
Definition at line 6660 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_TClass, G__DataLibraryDictLN_TVacuumData, G__DataLibraryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR, and G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_TVacuumData));
    { TVacuumData *p; p=(TVacuumData*)0x1000; if (p) { }
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"fStatus=",0,"Status");
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"fPressure=",0,"Pressure");
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"fTime=",0,"Time");
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataLibraryDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR (void) static
Definition at line 6673 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    { vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > *p; p=(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void) static
Definition at line 6682 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    { vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator *p; p=(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR (void) static
Definition at line 6585 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    { vector<TPulseIsland*,allocator<TPulseIsland*> > *p; p=(vector<TPulseIsland*,allocator<TPulseIsland*> >*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator (void) static
Definition at line 6594 of file DataLibraryDict.cpp.
References G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableDataLibraryDict().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator));
    { vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator *p; p=(vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
Variable Documentation
G__cpp_setup_initDataLibraryDict G__cpp_setup_initializerDataLibraryDict
Definition at line 7646 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOstringgRsPgR = { "allocator<pair<const string,string> >" , 99 , -1 }
Definition at line 7486 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR = { "allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > >" , 99 , -1 }
Definition at line 7511 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_tagtableDataLibraryDict(), and G__cpp_setup_typetableDataLibraryDict().
G__linked_taginfo G__DataLibraryDictLN_allocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgR = { "allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > >" , 99 , -1 }
Definition at line 7499 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_lesslEstringgR = { "less<string>" , 115 , -1 }
Definition at line 7479 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 }
Definition at line 7481 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 }
Definition at line 7480 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 }
Definition at line 7487 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiterator = { "map<string,string,less<string>,allocator<pair<const string,string> > >::iterator" , 99 , -1 }
Definition at line 7489 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLreverse_iterator = { "map<string,string,less<string>,allocator<pair<const string,string> > >::reverse_iterator" , 99 , -1 }
Definition at line 7490 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >" , 99 , -1 }
Definition at line 7512 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_tagtableDataLibraryDict(), G__cpp_setup_typetableDataLibraryDict(), G__DataLibraryDict_537_0_1(), G__DataLibraryDict_537_0_2(), G__DataLibraryDict_537_0_3(), G__DataLibraryDict_537_0_4(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR(), and G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator" , 99 , -1 }
Definition at line 7514 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_tagtableDataLibraryDict(), G__cpp_setup_typetableDataLibraryDict(), G__DataLibraryDict_539_0_1(), G__DataLibraryDict_539_0_2(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), and G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator" , 99 , -1 }
Definition at line 7515 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_tagtableDataLibraryDict(), G__cpp_setup_typetableDataLibraryDict(), and G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >" , 99 , -1 }
Definition at line 7500 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiterator = { "map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator" , 99 , -1 }
Definition at line 7502 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator = { "map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::reverse_iterator" , 99 , -1 }
Definition at line 7503 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_pairlEmaplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<string,string,less<string>,allocator<pair<const string,string> > >::iterator,bool>" , 115 , -1 }
Definition at line 7491 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator,bool>" , 115 , -1 }
Definition at line 7516 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_tagtableDataLibraryDict(), and G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
G__linked_taginfo G__DataLibraryDictLN_pairlEmaplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >::iterator,bool>" , 115 , -1 }
Definition at line 7504 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_pairlEstringcOstringgR = { "pair<string,string>" , 115 , -1 }
Definition at line 7488 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR = { "pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >" , 115 , -1 }
Definition at line 7513 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_tagtableDataLibraryDict(), G__cpp_setup_typetableDataLibraryDict(), G__DataLibraryDict_538_0_1(), G__DataLibraryDict_538_0_2(), G__DataLibraryDict_538_0_4(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), and G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR().
G__linked_taginfo G__DataLibraryDictLN_pairlEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgR = { "pair<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >" , 115 , -1 }
Definition at line 7501 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 }
Definition at line 7494 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 }
Definition at line 7476 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator>" , 99 , -1 }
Definition at line 7510 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_tagtableDataLibraryDict(), G__cpp_setup_typetableDataLibraryDict(), and G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator>" , 99 , -1 }
Definition at line 7498 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 }
Definition at line 7478 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_string = { "string" , 99 , -1 }
Definition at line 7474 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_TAnalysedPulse = { "TAnalysedPulse" , 99 , -1 }
Definition at line 7505 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_inheritanceDataLibraryDict(), G__cpp_setup_tagtableDataLibraryDict(), G__cpp_setup_typetableDataLibraryDict(), G__DataLibraryDict_528_0_1(), G__DataLibraryDict_528_0_2(), G__DataLibraryDict_528_0_21(), G__setup_memfuncTAnalysedPulse(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), G__setup_memvarTAnalysedPulse(), and G__setup_memvarTDetectorPulse().
G__linked_taginfo G__DataLibraryDictLN_TBuffer = { "TBuffer" , 99 , -1 }
Definition at line 7470 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_TClass = { "TClass" , 99 , -1 }
Definition at line 7469 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_TDetectorPulse = { "TDetectorPulse" , 99 , -1 }
Definition at line 7506 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_inheritanceDataLibraryDict(), G__cpp_setup_tagtableDataLibraryDict(), G__DataLibraryDict_529_0_1(), G__DataLibraryDict_529_0_2(), G__DataLibraryDict_529_0_23(), G__setup_memfuncTDetectorPulse(), and G__setup_memvarTDetectorPulse().
G__linked_taginfo G__DataLibraryDictLN_TGlobalData = { "TGlobalData" , 99 , -1 }
Definition at line 7495 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_TH1I = { "TH1I" , 99 , -1 }
Definition at line 7484 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 }
Definition at line 7471 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_TObject = { "TObject" , 99 , -1 }
Definition at line 7472 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_TPulseIsland = { "TPulseIsland" , 99 , -1 }
Definition at line 7492 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_TSetupData = { "TSetupData" , 99 , -1 }
Definition at line 7485 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_TVacuumData = { "TVacuumData" , 99 , -1 }
Definition at line 7507 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 }
Definition at line 7483 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 }
Definition at line 7482 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 }
Definition at line 7473 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 }
Definition at line 7493 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 }
Definition at line 7475 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR = { "vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >" , 99 , -1 }
Definition at line 7508 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_tagtableDataLibraryDict(), G__cpp_setup_typetableDataLibraryDict(), G__DataLibraryDict_532_0_15(), G__DataLibraryDict_532_0_16(), G__DataLibraryDict_532_0_17(), G__DataLibraryDict_532_0_18(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR(), G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), and G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
G__linked_taginfo G__DataLibraryDictLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator = { "vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator" , 99 , -1 }
Definition at line 7509 of file DataLibraryDict.cpp.
Referenced by G__cpp_setup_tagtableDataLibraryDict(), G__cpp_setup_typetableDataLibraryDict(), G__DataLibraryDict_533_0_1(), G__DataLibraryDict_533_0_16(), G__DataLibraryDict_533_0_2(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), and G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
G__linked_taginfo G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR = { "vector<TPulseIsland*,allocator<TPulseIsland*> >" , 99 , -1 }
Definition at line 7496 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiterator = { "vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator" , 99 , -1 }
Definition at line 7497 of file DataLibraryDict.cpp.
G__linked_taginfo G__DataLibraryDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 }
Definition at line 7477 of file DataLibraryDict.cpp.