AlcapDAQ: crate3/parport_module.cpp File Reference
parport_module.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/io.h>
#include <sys/time.h>
#include "midas.h"
#include "crate.h"
#include "diag.h"
Macros
#define PARALLEL_PORT0 0x1150
#define PARALLEL_PORT1 0x1151
Functions
INT setPP (char, int)
INT parport_init ()
INT parport_start_block ()
INT parport_poll_live ()
INT parport_poll_dead ()
Variables
bool block_sig
static unsigned int block_nr
struct readout_module parport_module
Macro Definition Documentation
#define PARALLEL_PORT0 0x1150
Definition at line 7 of file parport_module.cpp.
Referenced by parport_init(), and setPP().
#define PARALLEL_PORT1 0x1151
Definition at line 8 of file parport_module.cpp.
Referenced by parport_poll_live().
Function Documentation
INT parport_init ()
Definition at line 64 of file parport_module.cpp.
References block_nr, PARALLEL_PORT0, printf(), and SUCCESS.
 {
   printf("Opening parallel port %x\t\n", PARALLEL_PORT0);
   if (ioperm(PARALLEL_PORT0,3,1))
     {
       perror("PArallel POrt opening error\n");
       return 1;
     }
   /*
   int status = iopl( 3 );
   if (status < 0) {
     diag_print(0, "Unable to get permission to access I/O ports\n");
   }
   // turn off output
   outb(0x1d, 0x3f2);
   */
   block_nr = 0;
 #if 0
   gettimeofday(&t_0,NULL);
 #endif
         printf("Dummy master crate init\n");
   return SUCCESS;
 }
INT parport_poll_dead ()
Definition at line 159 of file parport_module.cpp.
 {
   //printf("Send to start block\n");
   //return FE_NEED_START;
   return 0;
 }
INT parport_poll_live ()
Definition at line 130 of file parport_module.cpp.
References FE_END_BLOCK, PARALLEL_PORT1, printf(), and SUCCESS.
 {
 #if 0
   struct timespec timer_now;
   clock_gettime(CLOCK_REALTIME, &timer_now);
   unsigned int time_elapse = (timer_now.tv_sec - timer_start.tv_sec) * 1000000000 +
     (timer_now.tv_nsec - timer_start.tv_nsec);
   printf("time elapse: %ld\n", time_elapse);
   if (time_elapse > 2*1000*1000)
     {
       printf("end of block\n");
       return FE_END_BLOCK;
     }
 #endif
   unsigned char p = inb(PARALLEL_PORT1);
   if ( !(p & 0x40) )
     {
       printf("p=%i, 0x%x\n",p, p);
       printf("end of block\n");
       return FE_END_BLOCK;
     }
   return SUCCESS;
 }
INT parport_start_block ()
Definition at line 98 of file parport_module.cpp.
References block_nr, block_sig, printf(), setPP(), and SUCCESS.
 {
   block_sig = true;
 #if 0
   clock_gettime(CLOCK_REALTIME,&timer_start);
 #endif
   block_nr++;
   printf("parport_start_block %i\n",block_nr);
   //setPP(255, 1);
   // Send reset
   setPP(1<<1, 1);
   setPP(0, 1);
   // start new segment
   setPP(1, 1);
   setPP(0, 1);
   return SUCCESS;
 }
INT setPP (char v, int usec)
Definition at line 54 of file parport_module.cpp.
References PARALLEL_PORT0.
Referenced by parport_start_block().
{
   outb(v,PARALLEL_PORT0);
   //outb(v,PARALLEL_PORT1);
   return 0;
 }
Variable Documentation
unsigned int block_nr static
Definition at line 33 of file parport_module.cpp.
Referenced by parport_init(), and parport_start_block().
bool block_sig
Definition at line 28 of file parport_module.cpp.
Referenced by parport_start_block().
struct readout_module parport_module
Initial value:
= {
  parport_init,
  NULL,
  NULL,
  NULL,
  NULL,
  parport_poll_live,
  parport_poll_dead,
  parport_start_block,
  NULL,
  NULL,
}
Definition at line 35 of file parport_module.cpp.