AlcapDAQ: CAEN/CAENDigitizer/CAENDigitizer_2.3.2/samples/ReadoutTest_DPP_PSD_x720/include/Functions.h File Reference
Functions.h File Reference
#include "keyb.h"
#include "CAENDigitizerType.h"
#include <unistd.h>
#include <stdint.h>
#include <ctype.h>
#include <sys/time.h>
Data Structures
struct DigitizerParams_t
Functions
long get_time ()
Get time in milliseconds.
int DataConsistencyCheck (uint32_t *buff32, int NumWords)
Do some data consistency check.
int SaveHistogram (char *basename, int b, int ch, uint32_t *EHisto)
int SaveWaveform (int b, int ch, int trace, int size, int16_t *WaveData)
int SaveDigitalProbe (int b, int ch, int trace, int size, uint8_t *WaveData)
Save Digital Waveforms to output file.
void PrintInterface ()
Print the interface to screen.
Function Documentation
int DataConsistencyCheck (uint32_t * buff32, int NumWords)
Do some data consistency check.
Returns
0=success; -1=error
Definition at line 64 of file Functions.c.
References i, and printf().
 {
     int i, zcnt=0, pnt=0;
     uint32_t EventSize;
     if (NumWords == 0)
         return 0;
     // Check for events integrity
     do {
         EventSize = buff32[pnt] & 0x0FFFFFFF;
         pnt += EventSize;  // Jump to next event
     } while (pnt<NumWords);
     if (pnt != NumWords) {
         printf("Data Error: Event truncation\n");
         return -1;
     }
     // Check for burst of zeroes (more than 2 consecutive zeroes)
     for(i=0; i<NumWords; i++) {
         if (buff32[i] == 0)   zcnt++;
         else                  zcnt=0;
         if (zcnt > 2) {
             printf("Data Error: Burst of zeroes\n");
             return -1;
         }
     }
     return 0;
 }
long get_time ()
Get time in milliseconds.
Returns
time in msec
Note
TERMS OF USE: This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. The user relies on the software, documentation and results solely at his own risk.
Returns
time in msec
Definition at line 43 of file Functions.c.
 {
     long time_ms;
 #ifdef WIN32
     struct _timeb timebuffer;
     _ftime( &timebuffer );
     time_ms = (long)timebuffer.time * 1000 + (long)timebuffer.millitm;
 #else
     struct timeval t1;
     struct timezone tz;
     gettimeofday(&t1, &tz);
     time_ms = (t1.tv_sec) * 1000 + t1.tv_usec / 1000;
 #endif
     return time_ms;
 }
void PrintInterface ()
Print the interface to screen.
Returns
none /* ------------------------------------------------------------------------------------------------------—
Definition at line 177 of file Functions.c.
References printf().
                       {
         printf("\ns ) Start acquisition\n");
         printf("S ) Stop acquisition\n");
         printf("r ) Restart acquisition\n");
         printf("q ) Quit\n");
         printf("t ) Send a software trigger\n");
         printf("h ) Save Histograms to file\n");
         printf("w ) Save waveforms to file\n\n\n");
 }
int SaveDigitalProbe (int b, int ch, int trace, int size, uint8_t * WaveData)
Save Digital Waveforms to output file.
Returns
0=success; -1=error
Definition at line 153 of file Functions.c.
References i, size, and sprintf().
 {
         /*
         This function saves the digital waveform in a textfile as a sequence of number representing the wave height
         */
     FILE *fh;
     int i;
     char filename[20];
     sprintf(filename, "DWaveform_%d_%d_%d.txt", b, ch, trace);
     fh = fopen(filename, "w");
     if (fh == NULL)
         return -1;
     for(i=0; i<size; i++)
         fprintf(fh, "%d\n", WaveData[i]); //&((1<<MAXNBITS)-1)
     fclose(fh);
     return 0;
 }
int SaveHistogram (char * basename, int b, int ch, uint32_t * EHisto)
Definition at line 101 of file Functions.c.
References i, printf(), and sprintf().
 {
         /*
         This function saves the first 10000 bin of each EHisto[ch] array in separate text files
         each array value is a number representing the histogram height in the corresponding bin
         NB: each EHisto[ch] must be a pointer already initialized with at least 10000 values
         */
     FILE *fh;
     int i;
     char filename[20];
     sprintf(filename, "%s_%d_%d.txt", basename, b, ch);
     fh = fopen(filename, "w");
     if (fh == NULL)
                 return -1;
     for(i=0; i<(1<<12); i++) {
                 fprintf(fh, "%d\n", EHisto[i]);
         }
     fclose(fh);
     printf("Histograms saved to '%s_<board>_<channel>.txt'\n", basename);
     return 0;
 }
int SaveWaveform (int b, int ch, int trace, int size, int16_t * WaveData)
Definition at line 129 of file Functions.c.
References i, size, and sprintf().
 {
         /*
         This function saves the waveform in a textfile as a sequence of number representing the wave height
         */
     FILE *fh;
     int i;
     char filename[20];
     sprintf(filename, "Waveform_%d_%d_%d.txt", b, ch, trace);
     fh = fopen(filename, "w");
     if (fh == NULL)
         return -1;
     for(i=0; i<size; i++)
         fprintf(fh, "%d\n", WaveData[i]); //&((1<<MAXNBITS)-1)
     fclose(fh);
     return 0;
 }