AlcapDAQ: analyzer/rootana/obj/RootanaDataClasses.cpp File Reference
RootanaDataClasses.cpp File Reference
#include "RConfig.h"
#include "RootanaDataClasses.h"
#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"
#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"
#include <new>
Data Structures
class G__Sizep2memfuncRootanaDataClasses
class G__cpp_setup_initRootanaDataClasses
Namespaces
ROOT
ROOT::Shadow
IDs
Constant Groups
ROOT
ROOT::Shadow
IDs
Macros
#define R__DICTIONARY_FILENAME objdIRootanaDataClasses
#define private public
#define protected public
#define G__ROOT
Typedefs
typedef pair< ::string, vector
< ::TAnalysedPulse
*, allocator< ::TAnalysedPulse * > > > ROOT::Shadow::pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR
typedef IDs::channel G__TIDscLcLchannel
typedef IDs::generator G__TIDscLcLgenerator
typedef IDs::source G__TIDscLcLsource
typedef TAnalysedPulse G__TTAnalysedPulse
typedef vector< TAnalysedPulse
*, allocator< TAnalysedPulse * > > G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR
typedef vector< TAnalysedPulse
*, allocator< TAnalysedPulse * >
>::iterator G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator
typedef map< string, vector
< TAnalysedPulse *, allocator
< TAnalysedPulse * > >, less
< string >, allocator< pair
< const string, vector
< TAnalysedPulse *, allocator
< TAnalysedPulse * > > > > > G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR
typedef pair< string, vector
< TAnalysedPulse *, allocator
< TAnalysedPulse * > > > G__TpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR
typedef map< string, vector
< TAnalysedPulse *, allocator
< TAnalysedPulse * > >, less
< string >, allocator< pair
< const string, vector
< TAnalysedPulse *, allocator
< TAnalysedPulse * >
> > > >::iterator G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator
typedef TDetectorPulse G__TTDetectorPulse
typedef vector< string,
allocator< string > > G__TvectorlEstringcOallocatorlEstringgRsPgR
typedef TAnalysedPulseMapWrapper G__TTAnalysedPulseMapWrapper
typedef map< string,
IDs::Detector_t, less< string >
, allocator< pair< const
string, IDs::Detector_t > > > G__TmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR
typedef map< IDs::Detector_t,
string, less< IDs::Detector_t >
, allocator< pair< const
IDs::Detector_t, string > > > G__TmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR
Functions
void ROOT::IDscLcLchannel_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_IDscLcLchannel (void *p=0)
static void * ROOT::newArray_IDscLcLchannel (Long_t size, void *p)
static void ROOT::delete_IDscLcLchannel (void *p)
static void ROOT::deleteArray_IDscLcLchannel (void *p)
static void ROOT::destruct_IDscLcLchannel (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::IDs::channel *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::IDs::channel *)
::ROOT::TGenericClassInfo * ROOT::_R__UNIQUE_ (Init) = GenerateInitInstanceLocal((const ::IDs::generator*)0x0)
ROOT::R__UseDummy (_R__UNIQUE_(Init))
void ROOT::IDscLcLgenerator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_IDscLcLgenerator (void *p=0)
static void * ROOT::newArray_IDscLcLgenerator (Long_t size, void *p)
static void ROOT::delete_IDscLcLgenerator (void *p)
static void ROOT::deleteArray_IDscLcLgenerator (void *p)
static void ROOT::destruct_IDscLcLgenerator (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::IDs::generator *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::IDs::generator *)
void ROOT::IDscLcLsource_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_IDscLcLsource (void *p=0)
static void * ROOT::newArray_IDscLcLsource (Long_t size, void *p)
static void ROOT::delete_IDscLcLsource (void *p)
static void ROOT::deleteArray_IDscLcLsource (void *p)
static void ROOT::destruct_IDscLcLsource (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::IDs::source *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::IDs::source *)
void ROOT::TAnalysedPulse_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TAnalysedPulse (void *p=0)
static void * ROOT::newArray_TAnalysedPulse (Long_t size, void *p)
static void ROOT::delete_TAnalysedPulse (void *p)
static void ROOT::deleteArray_TAnalysedPulse (void *p)
static void ROOT::destruct_TAnalysedPulse (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TAnalysedPulse *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TAnalysedPulse *)
void ROOT::vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator_Dictionary ()
static void * ROOT::new_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p=0)
static void * ROOT::newArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (Long_t size, void *p)
static void ROOT::delete_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static void ROOT::deleteArray_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static void ROOT::destruct_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >::iterator *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >::iterator *)
void ROOT::pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR_Dictionary ()
static void * ROOT::new_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p=0)
static void * ROOT::newArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (Long_t size, void *p)
static void ROOT::delete_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static void ROOT::deleteArray_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static void ROOT::destruct_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const pair< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > *)
TGenericClassInfo * ROOT::GenerateInitInstance (const pair< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > *)
void ROOT::maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator_Dictionary ()
static void * ROOT::new_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p=0)
static void * ROOT::newArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (Long_t size, void *p)
static void ROOT::delete_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void ROOT::deleteArray_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static void ROOT::destruct_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::map< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >, less< string >, allocator< pair< const string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > > >::iterator *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::map< string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > >, less< string >, allocator< pair< const string, vector< TAnalysedPulse *, allocator< TAnalysedPulse * > > > > >::iterator *)
void ROOT::TDetectorPulse_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TDetectorPulse (void *p=0)
static void * ROOT::newArray_TDetectorPulse (Long_t size, void *p)
static void ROOT::delete_TDetectorPulse (void *p)
static void ROOT::deleteArray_TDetectorPulse (void *p)
static void ROOT::destruct_TDetectorPulse (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TDetectorPulse *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TDetectorPulse *)
void ROOT::TAnalysedPulseMapWrapper_ShowMembers (void *obj, TMemberInspector &R__insp)
static void * ROOT::new_TAnalysedPulseMapWrapper (void *p=0)
static void * ROOT::newArray_TAnalysedPulseMapWrapper (Long_t size, void *p)
static void ROOT::delete_TAnalysedPulseMapWrapper (void *p)
static void ROOT::deleteArray_TAnalysedPulseMapWrapper (void *p)
static void ROOT::destruct_TAnalysedPulseMapWrapper (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const ::TAnalysedPulseMapWrapper *)
TGenericClassInfo * ROOT::GenerateInitInstance (const ::TAnalysedPulseMapWrapper *)
void ROOT::maplEIDscLcLDetector_tcOstringgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEIDscLcLDetector_tcOstringgR_Dictionary ()
static void * ROOT::new_maplEIDscLcLDetector_tcOstringgR (void *p=0)
static void * ROOT::newArray_maplEIDscLcLDetector_tcOstringgR (Long_t size, void *p)
static void ROOT::delete_maplEIDscLcLDetector_tcOstringgR (void *p)
static void ROOT::deleteArray_maplEIDscLcLDetector_tcOstringgR (void *p)
static void ROOT::destruct_maplEIDscLcLDetector_tcOstringgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< IDs::Detector_t, string > *)
void ROOT::maplEstringcOIDscLcLDetector_tgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOIDscLcLDetector_tgR_Dictionary ()
static void * ROOT::new_maplEstringcOIDscLcLDetector_tgR (void *p=0)
static void * ROOT::newArray_maplEstringcOIDscLcLDetector_tgR (Long_t size, void *p)
static void ROOT::delete_maplEstringcOIDscLcLDetector_tgR (void *p)
static void ROOT::deleteArray_maplEstringcOIDscLcLDetector_tgR (void *p)
static void ROOT::destruct_maplEstringcOIDscLcLDetector_tgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< string, IDs::Detector_t > *)
void ROOT::maplEstringcOvectorlETAnalysedPulsemUgRsPgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::maplEstringcOvectorlETAnalysedPulsemUgRsPgR_Dictionary ()
static void * ROOT::new_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p=0)
static void * ROOT::newArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (Long_t size, void *p)
static void ROOT::delete_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static void ROOT::deleteArray_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static void ROOT::destruct_maplEstringcOvectorlETAnalysedPulsemUgRsPgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const map< string, vector< TAnalysedPulse * > > *)
void ROOT::vectorlETAnalysedPulsemUgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::vectorlETAnalysedPulsemUgR_Dictionary ()
static void * ROOT::new_vectorlETAnalysedPulsemUgR (void *p=0)
static void * ROOT::newArray_vectorlETAnalysedPulsemUgR (Long_t size, void *p)
static void ROOT::delete_vectorlETAnalysedPulsemUgR (void *p)
static void ROOT::deleteArray_vectorlETAnalysedPulsemUgR (void *p)
static void ROOT::destruct_vectorlETAnalysedPulsemUgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const vector< TAnalysedPulse * > *)
void ROOT::vectorlEstringgR_ShowMembers (void *obj, TMemberInspector &R__insp)
static void ROOT::vectorlEstringgR_Dictionary ()
static void * ROOT::new_vectorlEstringgR (void *p=0)
static void * ROOT::newArray_vectorlEstringgR (Long_t size, void *p)
static void ROOT::delete_vectorlEstringgR (void *p)
static void ROOT::deleteArray_vectorlEstringgR (void *p)
static void ROOT::destruct_vectorlEstringgR (void *p)
static TGenericClassInfo * ROOT::GenerateInitInstanceLocal (const vector< string > *)
void G__cpp_reset_tagtableRootanaDataClasses ()
void G__set_cpp_environmentRootanaDataClasses ()
int G__cpp_dllrevRootanaDataClasses ()
static int G__RootanaDataClasses_404_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_404_0_28 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_407_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_28 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_408_0_29 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_430_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_28 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_29 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_30 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_31 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_432_0_32 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_433_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_446_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_447_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_447_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_447_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_447_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_448_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_28 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_29 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_30 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_451_0_31 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_28 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_29 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_30 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_31 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_591_0_32 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_594_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_597_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_1 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_2 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_3 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_4 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_5 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_6 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_7 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_8 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_9 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_10 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_11 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_12 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_13 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_14 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_15 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_16 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_17 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_18 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_19 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_20 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_21 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_22 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_23 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_24 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_25 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_26 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses_606_0_27 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
static int G__RootanaDataClasses__0_1771 (G__value *result7, G__CONST char *funcname, struct G__param *libp, int hash)
size_t G__get_sizep2memfuncRootanaDataClasses ()
void G__cpp_setup_inheritanceRootanaDataClasses ()
void G__cpp_setup_typetableRootanaDataClasses ()
static void G__setup_memvarIDscLcLchannel (void)
static void G__setup_memvarIDscLcLgenerator (void)
static void G__setup_memvarIDscLcLsource (void)
static void G__setup_memvarTAnalysedPulse (void)
static void G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR (void)
static void G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void)
static void G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR (void)
static void G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void)
static void G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void)
static void G__setup_memvarTDetectorPulse (void)
static void G__setup_memvarvectorlEstringcOallocatorlEstringgRsPgR (void)
static void G__setup_memvarTAnalysedPulseMapWrapper (void)
static void G__setup_memvarmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR (void)
static void G__setup_memvarmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR (void)
void G__cpp_setup_memvarRootanaDataClasses ()
static void G__setup_memfuncIDscLcLchannel (void)
static void G__setup_memfuncIDscLcLgenerator (void)
static void G__setup_memfuncIDscLcLsource (void)
static void G__setup_memfuncTAnalysedPulse (void)
static void G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR (void)
static void G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void)
static void G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR (void)
static void G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void)
static void G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void)
static void G__setup_memfuncTDetectorPulse (void)
static void G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR (void)
static void G__setup_memfuncTAnalysedPulseMapWrapper (void)
static void G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR (void)
static void G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR (void)
void G__cpp_setup_memfuncRootanaDataClasses ()
static void G__cpp_setup_global0 ()
static void G__cpp_setup_global1 ()
void G__cpp_setup_globalRootanaDataClasses ()
static void G__cpp_setup_func0 ()
static void G__cpp_setup_func1 ()
static void G__cpp_setup_func2 ()
static void G__cpp_setup_func3 ()
static void G__cpp_setup_func4 ()
static void G__cpp_setup_func5 ()
static void G__cpp_setup_func6 ()
static void G__cpp_setup_func7 ()
static void G__cpp_setup_func8 ()
static void G__cpp_setup_func9 ()
static void G__cpp_setup_func10 ()
static void G__cpp_setup_func11 ()
static void G__cpp_setup_func12 ()
static void G__cpp_setup_func13 ()
static void G__cpp_setup_func14 ()
static void G__cpp_setup_func15 ()
static void G__cpp_setup_func16 ()
static void G__cpp_setup_func17 ()
static void G__cpp_setup_func18 ()
static void G__cpp_setup_func19 ()
static void G__cpp_setup_func20 ()
static void G__cpp_setup_func21 ()
static void G__cpp_setup_func22 ()
static void G__cpp_setup_func23 ()
void G__cpp_setup_funcRootanaDataClasses ()
void G__cpp_setup_tagtableRootanaDataClasses ()
void G__cpp_setupRootanaDataClasses (void)
Variables
G__linked_taginfo G__RootanaDataClassesLN_TClass = { "TClass" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_TBuffer = { "TBuffer" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_TMemberInspector = { "TMemberInspector" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_TObject = { "TObject" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_string = { "string" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_lesslEstringgR = { "less<string>" , 115 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_IDs = { "IDs" , 110 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_IDscLcLchannel = { "IDs::channel" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_IDscLcLDetector_t = { "IDs::Detector_t" , 101 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_IDscLcLSlowFast_t = { "IDs::SlowFast_t" , 101 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_IDscLcLgenerator = { "IDs::generator" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_IDscLcLsource = { "IDs::source" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR = { "vector<TPulseIsland*,allocator<TPulseIsland*> >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator>" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEIDscLcLchannelgRcOallocatorlEpairlEconstsPIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR = { "map<IDs::channel,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<IDs::channel>,allocator<pair<const IDs::channel,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_TAnalysedPulse = { "TAnalysedPulse" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR = { "vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator = { "vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator>" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR = { "map<IDs::source,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<IDs::source>,allocator<pair<const IDs::source,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR = { "allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR = { "pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >" , 115 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator,bool>" , 115 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_TDetectorPulse = { "TDetectorPulse" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_vectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgR = { "vector<TDetectorPulse*,allocator<TDetectorPulse*> >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TDetectorPulse*,allocator<TDetectorPulse*> >::iterator>" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR = { "map<IDs::source,vector<TDetectorPulse*,allocator<TDetectorPulse*> >,less<IDs::source>,allocator<pair<const IDs::source,vector<TDetectorPulse*,allocator<TDetectorPulse*> > > > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TDetectorPulse*,allocator<TDetectorPulse*> >,less<string>,allocator<pair<const string,vector<TDetectorPulse*,allocator<TDetectorPulse*> > > > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_vectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgR = { "vector<TMuonEvent*,allocator<TMuonEvent*> >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMuonEvent*,allocator<TMuonEvent*> >::iterator>" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR = { "map<string,bool,less<string>,allocator<pair<const string,bool> > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator = { "vector<string,allocator<string> >::iterator" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_TAnalysedPulseMapWrapper = { "TAnalysedPulseMapWrapper" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgR = { "allocator<pair<const string,IDs::Detector_t> >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR = { "map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_pairlEstringcOIDscLcLDetector_tgR = { "pair<string,IDs::Detector_t>" , 115 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator = { "map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLreverse_iterator = { "map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_pairlEmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator,bool>" , 115 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_lesslEIDscLcLDetector_tgR = { "less<IDs::Detector_t>" , 115 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_allocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgR = { "allocator<pair<const IDs::Detector_t,string> >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR = { "map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_pairlEIDscLcLDetector_tcOstringgR = { "pair<IDs::Detector_t,string>" , 115 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator = { "map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLreverse_iterator = { "map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator" , 99 , -1 }
G__linked_taginfo G__RootanaDataClassesLN_pairlEmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator,bool>" , 115 , -1 }
G__cpp_setup_initRootanaDataClasses G__cpp_setup_initializerRootanaDataClasses
Macro Definition Documentation
#define G__ROOT
Definition at line 26 of file RootanaDataClasses.cpp.
#define private public
Definition at line 11 of file RootanaDataClasses.cpp.
#define protected public
Definition at line 12 of file RootanaDataClasses.cpp.
#define R__DICTIONARY_FILENAME objdIRootanaDataClasses
Definition at line 7 of file RootanaDataClasses.cpp.
Typedef Documentation
typedef IDs::channel G__TIDscLcLchannel
Definition at line 1521 of file RootanaDataClasses.cpp.
typedef IDs::generator G__TIDscLcLgenerator
Definition at line 1756 of file RootanaDataClasses.cpp.
typedef IDs::source G__TIDscLcLsource
Definition at line 2055 of file RootanaDataClasses.cpp.
typedef map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > > G__TmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR
Definition at line 4973 of file RootanaDataClasses.cpp.
typedef map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > > G__TmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR
Definition at line 4652 of file RootanaDataClasses.cpp.
typedef map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > > G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR
Definition at line 3236 of file RootanaDataClasses.cpp.
typedef map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator
Definition at line 3493 of file RootanaDataClasses.cpp.
typedef pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > G__TpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR
Definition at line 3329 of file RootanaDataClasses.cpp.
typedef TAnalysedPulse G__TTAnalysedPulse
Definition at line 2308 of file RootanaDataClasses.cpp.
typedef TAnalysedPulseMapWrapper G__TTAnalysedPulseMapWrapper
Definition at line 4320 of file RootanaDataClasses.cpp.
typedef TDetectorPulse G__TTDetectorPulse
Definition at line 3764 of file RootanaDataClasses.cpp.
typedef vector<string,allocator<string> > G__TvectorlEstringcOallocatorlEstringgRsPgR
Definition at line 4137 of file RootanaDataClasses.cpp.
typedef vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR
Definition at line 2681 of file RootanaDataClasses.cpp.
typedef vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator
Definition at line 2915 of file RootanaDataClasses.cpp.
Function Documentation
int G__cpp_dllrevRootanaDataClasses ()
Definition at line 1265 of file RootanaDataClasses.cpp.
 { return(30051515); }
void G__cpp_reset_tagtableRootanaDataClasses ()
Definition at line 6264 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_allocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgR, G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgR, G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR, G__RootanaDataClassesLN_IDs, G__RootanaDataClassesLN_IDscLcLchannel, G__RootanaDataClassesLN_IDscLcLDetector_t, G__RootanaDataClassesLN_IDscLcLgenerator, G__RootanaDataClassesLN_IDscLcLSlowFast_t, G__RootanaDataClassesLN_IDscLcLsource, G__RootanaDataClassesLN_lesslEIDscLcLDetector_tgR, G__RootanaDataClassesLN_lesslEstringgR, G__RootanaDataClassesLN_maplEIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEIDscLcLchannelgRcOallocatorlEpairlEconstsPIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR, G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLreverse_iterator, G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLreverse_iterator, G__RootanaDataClassesLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator, G__RootanaDataClassesLN_maplEstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_pairlEIDscLcLDetector_tcOstringgR, G__RootanaDataClassesLN_pairlEmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiteratorcOboolgR, G__RootanaDataClassesLN_pairlEmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiteratorcOboolgR, G__RootanaDataClassesLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR, G__RootanaDataClassesLN_pairlEstringcOIDscLcLDetector_tgR, G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_string, G__RootanaDataClassesLN_TAnalysedPulse, G__RootanaDataClassesLN_TAnalysedPulseMapWrapper, G__RootanaDataClassesLN_TBuffer, G__RootanaDataClassesLN_TClass, G__RootanaDataClassesLN_TDetectorPulse, G__RootanaDataClassesLN_TMemberInspector, G__RootanaDataClassesLN_TObject, G__RootanaDataClassesLN_TVectorTlEdoublegR, G__RootanaDataClassesLN_TVectorTlEfloatgR, G__RootanaDataClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR, G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR, G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator, G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR, G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator, G__RootanaDataClassesLN_vectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgR, G__RootanaDataClassesLN_vectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgR, G__RootanaDataClassesLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR, and G__RootanaDataClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.
Referenced by G__set_cpp_environmentRootanaDataClasses().
{
   G__RootanaDataClassesLN_TClass.tagnum = -1 ;
   G__RootanaDataClassesLN_TBuffer.tagnum = -1 ;
   G__RootanaDataClassesLN_TMemberInspector.tagnum = -1 ;
   G__RootanaDataClassesLN_TObject.tagnum = -1 ;
   G__RootanaDataClassesLN_string.tagnum = -1 ;
   G__RootanaDataClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__RootanaDataClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__RootanaDataClassesLN_lesslEstringgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_IDs.tagnum = -1 ;
   G__RootanaDataClassesLN_IDscLcLchannel.tagnum = -1 ;
   G__RootanaDataClassesLN_IDscLcLDetector_t.tagnum = -1 ;
   G__RootanaDataClassesLN_IDscLcLSlowFast_t.tagnum = -1 ;
   G__RootanaDataClassesLN_IDscLcLgenerator.tagnum = -1 ;
   G__RootanaDataClassesLN_IDscLcLsource.tagnum = -1 ;
   G__RootanaDataClassesLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEIDscLcLchannelgRcOallocatorlEpairlEconstsPIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_TAnalysedPulse.tagnum = -1 ;
   G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.tagnum = -1 ;
   G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator.tagnum = -1 ;
   G__RootanaDataClassesLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR.tagnum = -1 ;
   G__RootanaDataClassesLN_TDetectorPulse.tagnum = -1 ;
   G__RootanaDataClassesLN_vectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_reverse_iteratorlEvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_vectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_reverse_iteratorlEvectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__RootanaDataClassesLN_TVectorTlEfloatgR.tagnum = -1 ;
   G__RootanaDataClassesLN_TVectorTlEdoublegR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator.tagnum = -1 ;
   G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
   G__RootanaDataClassesLN_TAnalysedPulseMapWrapper.tagnum = -1 ;
   G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_pairlEstringcOIDscLcLDetector_tgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLreverse_iterator.tagnum = -1 ;
   G__RootanaDataClassesLN_pairlEmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiteratorcOboolgR.tagnum = -1 ;
   G__RootanaDataClassesLN_lesslEIDscLcLDetector_tgR.tagnum = -1 ;
   G__RootanaDataClassesLN_allocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR.tagnum = -1 ;
   G__RootanaDataClassesLN_pairlEIDscLcLDetector_tcOstringgR.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator.tagnum = -1 ;
   G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLreverse_iterator.tagnum = -1 ;
   G__RootanaDataClassesLN_pairlEmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiteratorcOboolgR.tagnum = -1 ;
 }
static void G__cpp_setup_func0 () static
Definition at line 6091 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
    G__lastifuncposition();
 }
static void G__cpp_setup_func1 () static
Definition at line 6096 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func10 () static
Definition at line 6123 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func11 () static
Definition at line 6126 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func12 () static
Definition at line 6129 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func13 () static
Definition at line 6132 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func14 () static
Definition at line 6135 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func15 () static
Definition at line 6138 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func16 () static
Definition at line 6141 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func17 () static
Definition at line 6144 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses__0_1771().
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
    G__memfunc_setup("operator!=", 970, G__RootanaDataClasses__0_1771, 103, -1, -1, 0, 2, 1, 1, 8,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 11 - x u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 11 - y", (char*) NULL
 , (void*) NULL, 0);
 }
static void G__cpp_setup_func18 () static
Definition at line 6150 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func19 () static
Definition at line 6153 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func2 () static
Definition at line 6099 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func20 () static
Definition at line 6156 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func21 () static
Definition at line 6159 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func22 () static
Definition at line 6162 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func23 () static
Definition at line 6165 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
    G__resetifuncposition();
 }
static void G__cpp_setup_func3 () static
Definition at line 6102 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func4 () static
Definition at line 6105 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func5 () static
Definition at line 6108 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func6 () static
Definition at line 6111 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func7 () static
Definition at line 6114 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func8 () static
Definition at line 6117 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
static void G__cpp_setup_func9 () static
Definition at line 6120 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_funcRootanaDataClasses().
{
 }
void G__cpp_setup_funcRootanaDataClasses ()
Definition at line 6170 of file RootanaDataClasses.cpp.
References G__cpp_setup_func0(), G__cpp_setup_func1(), G__cpp_setup_func10(), G__cpp_setup_func11(), G__cpp_setup_func12(), G__cpp_setup_func13(), G__cpp_setup_func14(), G__cpp_setup_func15(), G__cpp_setup_func16(), G__cpp_setup_func17(), G__cpp_setup_func18(), G__cpp_setup_func19(), G__cpp_setup_func2(), G__cpp_setup_func20(), G__cpp_setup_func21(), G__cpp_setup_func22(), G__cpp_setup_func23(), G__cpp_setup_func3(), G__cpp_setup_func4(), G__cpp_setup_func5(), G__cpp_setup_func6(), G__cpp_setup_func7(), G__cpp_setup_func8(), and G__cpp_setup_func9().
Referenced by G__cpp_setupRootanaDataClasses().
{
   G__cpp_setup_func0();
   G__cpp_setup_func1();
   G__cpp_setup_func2();
   G__cpp_setup_func3();
   G__cpp_setup_func4();
   G__cpp_setup_func5();
   G__cpp_setup_func6();
   G__cpp_setup_func7();
   G__cpp_setup_func8();
   G__cpp_setup_func9();
   G__cpp_setup_func10();
   G__cpp_setup_func11();
   G__cpp_setup_func12();
   G__cpp_setup_func13();
   G__cpp_setup_func14();
   G__cpp_setup_func15();
   G__cpp_setup_func16();
   G__cpp_setup_func17();
   G__cpp_setup_func18();
   G__cpp_setup_func19();
   G__cpp_setup_func20();
   G__cpp_setup_func21();
   G__cpp_setup_func22();
   G__cpp_setup_func23();
 }
static void G__cpp_setup_global0 () static
Definition at line 6072 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_globalRootanaDataClasses().
{
    /* Setting up global variables */
    G__resetplocal();
 }
static void G__cpp_setup_global1 () static
Definition at line 6079 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_globalRootanaDataClasses().
{
    G__resetglobalenv();
 }
void G__cpp_setup_globalRootanaDataClasses ()
Definition at line 6083 of file RootanaDataClasses.cpp.
References G__cpp_setup_global0(), and G__cpp_setup_global1().
Referenced by G__cpp_setupRootanaDataClasses().
{
   G__cpp_setup_global0();
   G__cpp_setup_global1();
 }
void G__cpp_setup_inheritanceRootanaDataClasses ()
Definition at line 5083 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLgenerator, G__RootanaDataClassesLN_IDscLcLsource, G__RootanaDataClassesLN_TAnalysedPulse, G__RootanaDataClassesLN_TAnalysedPulseMapWrapper, G__RootanaDataClassesLN_TDetectorPulse, and G__RootanaDataClassesLN_TObject.
Referenced by G__cpp_setupRootanaDataClasses().
{
    /* Setting up class inheritance */
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator))) {
      IDs::generator *G__Lderived;
      G__Lderived=(IDs::generator*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator),G__get_linked_tagnum(&G__RootanaDataClassesLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource))) {
      IDs::source *G__Lderived;
      G__Lderived=(IDs::source*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource),G__get_linked_tagnum(&G__RootanaDataClassesLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse))) {
      TAnalysedPulse *G__Lderived;
      G__Lderived=(TAnalysedPulse*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),G__get_linked_tagnum(&G__RootanaDataClassesLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__RootanaDataClassesLN_TDetectorPulse))) {
      TDetectorPulse *G__Lderived;
      G__Lderived=(TDetectorPulse*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_TDetectorPulse),G__get_linked_tagnum(&G__RootanaDataClassesLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper))) {
      TAnalysedPulseMapWrapper *G__Lderived;
      G__Lderived=(TAnalysedPulseMapWrapper*)0x1000;
      {
        TObject *G__Lpbase=(TObject*)G__Lderived;
        G__inheritance_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper),G__get_linked_tagnum(&G__RootanaDataClassesLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
      }
    }
 }
void G__cpp_setup_memfuncRootanaDataClasses ()
Definition at line 6066 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setupRootanaDataClasses().
{
 }
void G__cpp_setup_memvarRootanaDataClasses ()
Definition at line 5544 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setupRootanaDataClasses().
{
 }
void G__cpp_setup_tagtableRootanaDataClasses ()
Definition at line 6329 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_allocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgR, G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgR, G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR, G__RootanaDataClassesLN_IDs, G__RootanaDataClassesLN_IDscLcLchannel, G__RootanaDataClassesLN_IDscLcLDetector_t, G__RootanaDataClassesLN_IDscLcLgenerator, G__RootanaDataClassesLN_IDscLcLSlowFast_t, G__RootanaDataClassesLN_IDscLcLsource, G__RootanaDataClassesLN_lesslEIDscLcLDetector_tgR, G__RootanaDataClassesLN_lesslEstringgR, G__RootanaDataClassesLN_maplEIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEIDscLcLchannelgRcOallocatorlEpairlEconstsPIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR, G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLreverse_iterator, G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLreverse_iterator, G__RootanaDataClassesLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator, G__RootanaDataClassesLN_maplEstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_pairlEIDscLcLDetector_tcOstringgR, G__RootanaDataClassesLN_pairlEmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiteratorcOboolgR, G__RootanaDataClassesLN_pairlEmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiteratorcOboolgR, G__RootanaDataClassesLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR, G__RootanaDataClassesLN_pairlEstringcOIDscLcLDetector_tgR, G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_string, G__RootanaDataClassesLN_TAnalysedPulse, G__RootanaDataClassesLN_TAnalysedPulseMapWrapper, G__RootanaDataClassesLN_TBuffer, G__RootanaDataClassesLN_TClass, G__RootanaDataClassesLN_TDetectorPulse, G__RootanaDataClassesLN_TMemberInspector, G__RootanaDataClassesLN_TObject, G__RootanaDataClassesLN_TVectorTlEdoublegR, G__RootanaDataClassesLN_TVectorTlEfloatgR, G__RootanaDataClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR, G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR, G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator, G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR, G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator, G__RootanaDataClassesLN_vectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgR, G__RootanaDataClassesLN_vectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgR, G__RootanaDataClassesLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR, G__RootanaDataClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR, G__setup_memfuncIDscLcLchannel(), G__setup_memfuncIDscLcLgenerator(), G__setup_memfuncIDscLcLsource(), G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR(), G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), G__setup_memfuncTAnalysedPulse(), G__setup_memfuncTAnalysedPulseMapWrapper(), G__setup_memfuncTDetectorPulse(), G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), G__setup_memvarIDscLcLchannel(), G__setup_memvarIDscLcLgenerator(), G__setup_memvarIDscLcLsource(), G__setup_memvarmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR(), G__setup_memvarmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR(), G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR(), G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), G__setup_memvarTAnalysedPulse(), G__setup_memvarTAnalysedPulseMapWrapper(), G__setup_memvarTDetectorPulse(), G__setup_memvarvectorlEstringcOallocatorlEstringgRsPgR(), G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR(), and G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
Referenced by G__cpp_setupRootanaDataClasses().
{
    /* Setting up class,struct,union tag entry */
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_TClass);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_TBuffer);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_TMemberInspector);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_TObject);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_string);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_lesslEstringgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_IDs);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_IDscLcLchannel),sizeof(IDs::channel),-1,296192,(char*)NULL,G__setup_memvarIDscLcLchannel,G__setup_memfuncIDscLcLchannel);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_IDscLcLDetector_t),sizeof(int),-1,262144,(char*)NULL,NULL,NULL);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_IDscLcLSlowFast_t);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_IDscLcLgenerator),sizeof(IDs::generator),-1,324864,(char*)NULL,G__setup_memvarIDscLcLgenerator,G__setup_memfuncIDscLcLgenerator);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_IDscLcLsource),sizeof(IDs::source),-1,324864,(char*)NULL,G__setup_memvarIDscLcLsource,G__setup_memfuncIDscLcLsource);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEIDscLcLchannelgRcOallocatorlEpairlEconstsPIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_TAnalysedPulse),sizeof(TAnalysedPulse),-1,324864,(char*)NULL,G__setup_memvarTAnalysedPulse,G__setup_memfuncTAnalysedPulse);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR),sizeof(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >),-1,298752,(char*)NULL,G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR,G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator),sizeof(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator),-1,35072,(char*)NULL,G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator,G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),sizeof(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >),-1,298752,(char*)NULL,G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR,G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR),sizeof(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >),-1,297216,(char*)NULL,G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR,G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator),sizeof(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator),-1,2816,(char*)NULL,G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator,G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_TDetectorPulse),sizeof(TDetectorPulse),-1,324864,(char*)NULL,G__setup_memvarTDetectorPulse,G__setup_memfuncTDetectorPulse);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_vectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_vectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_TVectorTlEfloatgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_TVectorTlEdoublegR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR),sizeof(vector<string,allocator<string> >),-1,298752,(char*)NULL,G__setup_memvarvectorlEstringcOallocatorlEstringgRsPgR,G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper),sizeof(TAnalysedPulseMapWrapper),-1,324864,(char*)NULL,G__setup_memvarTAnalysedPulseMapWrapper,G__setup_memfuncTAnalysedPulseMapWrapper);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR),sizeof(map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >),-1,298752,(char*)NULL,G__setup_memvarmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR,G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_pairlEstringcOIDscLcLDetector_tgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLreverse_iterator);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_pairlEmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiteratorcOboolgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_lesslEIDscLcLDetector_tgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_allocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgR);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR),sizeof(map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >),-1,298752,(char*)NULL,G__setup_memvarmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR,G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_pairlEIDscLcLDetector_tcOstringgR);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLreverse_iterator);
    G__get_linked_tagnum_fwd(&G__RootanaDataClassesLN_pairlEmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiteratorcOboolgR);
 }
void G__cpp_setup_typetableRootanaDataClasses ()
Definition at line 5131 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_allocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgR, G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgR, G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR, G__RootanaDataClassesLN_IDs, G__RootanaDataClassesLN_IDscLcLDetector_t, G__RootanaDataClassesLN_lesslEIDscLcLDetector_tgR, G__RootanaDataClassesLN_lesslEstringgR, G__RootanaDataClassesLN_maplEIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEIDscLcLchannelgRcOallocatorlEpairlEconstsPIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR, G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLreverse_iterator, G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLreverse_iterator, G__RootanaDataClassesLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator, G__RootanaDataClassesLN_maplEstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_pairlEIDscLcLDetector_tcOstringgR, G__RootanaDataClassesLN_pairlEstringcOIDscLcLDetector_tgR, G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_string, G__RootanaDataClassesLN_TAnalysedPulse, G__RootanaDataClassesLN_TVectorTlEdoublegR, G__RootanaDataClassesLN_TVectorTlEfloatgR, G__RootanaDataClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR, G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR, G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator, G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR, G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator, G__RootanaDataClassesLN_vectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgR, G__RootanaDataClassesLN_vectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgR, G__RootanaDataClassesLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR, and G__RootanaDataClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.
Referenced by G__cpp_setupRootanaDataClasses().
{
    /* Setting up typedef entry */
    G__search_typename2("Version_t",115,-1,0,-1);
    G__setnewtype(-1,"Class version identifier (short)",0);
    G__search_typename2("Option_t",99,-1,256,-1);
    G__setnewtype(-1,"Option string (const char)",0);
    G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("Generator_t",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDs));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("Config_t",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDs));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TPulseIsland*>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::channel,PulseIslandList>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEIDscLcLchannelgRcOallocatorlEpairlEconstsPIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::channel,vector<TPulseIsland*,allocator<TPulseIsland*> > >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEIDscLcLchannelgRcOallocatorlEpairlEconstsPIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::channel,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<IDs::channel> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEIDscLcLchannelgRcOallocatorlEpairlEconstsPIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,PulseIslandList>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,PulseIslandList>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> > >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TAnalysedPulse*>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("value_type",85,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("pointer",85,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),256,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reference",85,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),1,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reference",85,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),257,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("pointer",85,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reference",85,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),1,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reference",85,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),1,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::source,AnalysedPulseList>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::source,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::source,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<IDs::source> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,AnalysedPulseList>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,AnalysedPulseList>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("mapped_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("value_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_compare",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_lesslEstringgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("allocator_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator),256,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("StringAnalPulseMap",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TDetectorPulse*>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::source,DetectorPulseList>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::source,vector<TDetectorPulse*,allocator<TDetectorPulse*> > >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::source,vector<TDetectorPulse*,allocator<TDetectorPulse*> >,less<IDs::source> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,DetectorPulseList>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,DetectorPulseList>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TDetectorPulse*,allocator<TDetectorPulse*> > >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TDetectorPulse*,allocator<TDetectorPulse*> >,less<string> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TMuonEvent*>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_TVectorTlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_TVectorTlEdoublegR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,std::string>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,double>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,double>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,int>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,int>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,bool>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,bool,less<string> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("value_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("pointer",85,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),256,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reference",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),1,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reference",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),257,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<std::string,IDs::Detector_t>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,IDs::Detector_t>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("mapped_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLDetector_t),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("value_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOIDscLcLDetector_tgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_compare",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_lesslEstringgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("allocator_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLreverse_iterator),256,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,IDs::Detector_t>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,IDs::Detector_t,less<string> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::Detector_t,std::string>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLDetector_t),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("mapped_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("value_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEIDscLcLDetector_tcOstringgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("key_compare",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_lesslEIDscLcLDetector_tgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("allocator_type",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_allocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgR),0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLreverse_iterator),256,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::Detector_t,string>",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<IDs::Detector_t,string,less<IDs::Detector_t> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("map<string,vector<TAnalysedPulse*> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("pair<string,vector<TAnalysedPulse*> >",117,G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
 }
void G__cpp_setupRootanaDataClasses (void)
Definition at line 6394 of file RootanaDataClasses.cpp.
References G__cpp_setup_funcRootanaDataClasses(), G__cpp_setup_globalRootanaDataClasses(), G__cpp_setup_inheritanceRootanaDataClasses(), G__cpp_setup_memfuncRootanaDataClasses(), G__cpp_setup_memvarRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__get_sizep2memfuncRootanaDataClasses(), and G__set_cpp_environmentRootanaDataClasses().
Referenced by G__cpp_setup_initRootanaDataClasses::G__cpp_setup_initRootanaDataClasses().
{
   G__check_setup_version(30051515,"G__cpp_setupRootanaDataClasses()");
   G__set_cpp_environmentRootanaDataClasses();
   G__cpp_setup_tagtableRootanaDataClasses();
   G__cpp_setup_inheritanceRootanaDataClasses();
   G__cpp_setup_typetableRootanaDataClasses();
   G__cpp_setup_memvarRootanaDataClasses();
   G__cpp_setup_memfuncRootanaDataClasses();
   G__cpp_setup_globalRootanaDataClasses();
   G__cpp_setup_funcRootanaDataClasses();
    if(0==G__getsizep2memfunc()) G__get_sizep2memfuncRootanaDataClasses();
   return;
 }
size_t G__get_sizep2memfuncRootanaDataClasses ()
Definition at line 5066 of file RootanaDataClasses.cpp.
References G__Sizep2memfuncRootanaDataClasses::sizep2memfunc().
Referenced by G__cpp_setupRootanaDataClasses().
 {
   G__Sizep2memfuncRootanaDataClasses a;
   G__setsizep2memfunc((int)a.sizep2memfunc());
   return((size_t)a.sizep2memfunc());
 }
static int G__RootanaDataClasses_404_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1272 of file RootanaDataClasses.cpp.
References channel, and G__RootanaDataClassesLN_IDscLcLchannel.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
    IDs::channel* p = NULL;
    char* gvp = (char*) G__getgvp();
    switch (libp->paran) {
    case 2:
      //m: 2
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::channel((IDs::Detector_t) G__int(libp->para[0]), (IDs::SlowFast_t) G__int(libp->para[1]));
      } else {
        p = new((void*) gvp) IDs::channel((IDs::Detector_t) G__int(libp->para[0]), (IDs::SlowFast_t) G__int(libp->para[1]));
      }
      break;
    case 1:
      //m: 1
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::channel((IDs::Detector_t) G__int(libp->para[0]));
      } else {
        p = new((void*) gvp) IDs::channel((IDs::Detector_t) G__int(libp->para[0]));
      }
      break;
    case 0:
      int n = G__getaryconstruct();
      if (n) {
        if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
          p = new IDs::channel[n];
        } else {
          p = new((void*) gvp) IDs::channel[n];
        }
      } else {
        if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
          p = new IDs::channel;
        } else {
          p = new((void*) gvp) IDs::channel;
        }
      }
      break;
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1393 of file RootanaDataClasses.cpp.
References IDs::channel::GetDetectorString().
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       {
          string* pobj;
          string xobj = IDs::channel::GetDetectorString((IDs::Detector_t) G__int(libp->para[0]));
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1406 of file RootanaDataClasses.cpp.
References IDs::channel::GetDetectorEnum().
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 105, (long) IDs::channel::GetDetectorEnum(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1412 of file RootanaDataClasses.cpp.
References IDs::channel::GetSlowFastString().
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       {
          string* pobj;
          string xobj = IDs::channel::GetSlowFastString((IDs::SlowFast_t) G__int(libp->para[0]));
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1425 of file RootanaDataClasses.cpp.
References IDs::channel::GetSlowFastEnum().
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 105, (long) IDs::channel::GetSlowFastEnum(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1431 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 85, (long) IDs::channel::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1437 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 67, (long) IDs::channel::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1443 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 115, (long) IDs::channel::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1449 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       IDs::channel::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1456 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 85, (long) ((const IDs::channel*) G__getstructoffset())->IsA());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1462 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       ((IDs::channel*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1316 of file RootanaDataClasses.cpp.
References channel, and G__RootanaDataClassesLN_IDscLcLchannel.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
    IDs::channel* p = NULL;
    char* gvp = (char*) G__getgvp();
    switch (libp->paran) {
    case 2:
      //m: 2
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::channel(*(string*) libp->para[0].ref, *(string*) libp->para[1].ref);
      } else {
        p = new((void*) gvp) IDs::channel(*(string*) libp->para[0].ref, *(string*) libp->para[1].ref);
      }
      break;
    case 1:
      //m: 1
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::channel(*(string*) libp->para[0].ref);
      } else {
        p = new((void*) gvp) IDs::channel(*(string*) libp->para[0].ref);
      }
      break;
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1469 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       ((IDs::channel*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1476 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       ((IDs::channel*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1483 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 67, (long) IDs::channel::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1489 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 105, (long) IDs::channel::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1495 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 67, (long) IDs::channel::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1501 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 105, (long) IDs::channel::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1508 of file RootanaDataClasses.cpp.
References channel, and G__RootanaDataClassesLN_IDscLcLchannel.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
    IDs::channel* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new IDs::channel(*(IDs::channel*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1522 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (IDs::channel*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((IDs::channel*) (soff+(sizeof(IDs::channel)*i)))->~G__TIDscLcLchannel();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (IDs::channel*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((IDs::channel*) (soff))->~G__TIDscLcLchannel();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_28 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1559 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
    IDs::channel* dest = (IDs::channel*) G__getstructoffset();
    *dest = *(IDs::channel*) libp->para[0].ref;
    const IDs::channel& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1344 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 105, (long) ((const IDs::channel*) G__getstructoffset())->Detector());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1350 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 105, (long) ((const IDs::channel*) G__getstructoffset())->SlowFast());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1356 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 103, (long) ((const IDs::channel*) G__getstructoffset())->operator==(*(IDs::channel*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1362 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 103, (long) ((const IDs::channel*) G__getstructoffset())->operator!=(*(IDs::channel*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1368 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 103, (long) ((const IDs::channel*) G__getstructoffset())->operator<(*(IDs::channel*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1374 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       G__letint(result7, 103, (long) ((const IDs::channel*) G__getstructoffset())->operator>(*(IDs::channel*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_404_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1380 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLchannel().
 {
       {
          const string* pobj;
          const string xobj = ((const IDs::channel*) G__getstructoffset())->str();
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1571 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLgenerator.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
    IDs::generator* p = NULL;
    char* gvp = (char*) G__getgvp();
    switch (libp->paran) {
    case 2:
      //m: 2
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::generator(*((IDs::Generator_t*) G__int(libp->para[0])), *((IDs::Config_t*) G__int(libp->para[1])));
      } else {
        p = new((void*) gvp) IDs::generator(*((IDs::Generator_t*) G__int(libp->para[0])), *((IDs::Config_t*) G__int(libp->para[1])));
      }
      break;
    case 1:
      //m: 1
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::generator(*((IDs::Generator_t*) G__int(libp->para[0])));
      } else {
        p = new((void*) gvp) IDs::generator(*((IDs::Generator_t*) G__int(libp->para[0])));
      }
      break;
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1686 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       G__letint(result7, 85, (long) IDs::generator::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1692 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       G__letint(result7, 67, (long) IDs::generator::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1698 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       G__letint(result7, 115, (long) IDs::generator::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1704 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       IDs::generator::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1711 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       ((IDs::generator*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1718 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       G__letint(result7, 67, (long) IDs::generator::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1724 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       G__letint(result7, 105, (long) IDs::generator::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1599 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLgenerator.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
    IDs::generator* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::generator[n];
      } else {
        p = new((void*) gvp) IDs::generator[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::generator;
      } else {
        p = new((void*) gvp) IDs::generator;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1730 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       G__letint(result7, 67, (long) IDs::generator::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1736 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       G__letint(result7, 105, (long) IDs::generator::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1743 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLgenerator.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
    IDs::generator* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new IDs::generator(*(IDs::generator*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1757 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (IDs::generator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((IDs::generator*) (soff+(sizeof(IDs::generator)*i)))->~G__TIDscLcLgenerator();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (IDs::generator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((IDs::generator*) (soff))->~G__TIDscLcLgenerator();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1794 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
    IDs::generator* dest = (IDs::generator*) G__getstructoffset();
    *dest = *(IDs::generator*) libp->para[0].ref;
    const IDs::generator& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1623 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       {
          const IDs::Generator_t* pobj;
          const IDs::Generator_t xobj = ((const IDs::generator*) G__getstructoffset())->Type();
          pobj = new IDs::Generator_t(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1636 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       {
          const IDs::Config_t* pobj;
          const IDs::Config_t xobj = ((const IDs::generator*) G__getstructoffset())->Config();
          pobj = new IDs::Config_t(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1649 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       G__letint(result7, 103, (long) ((const IDs::generator*) G__getstructoffset())->operator==(*(IDs::generator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1655 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       G__letint(result7, 103, (long) ((const IDs::generator*) G__getstructoffset())->operator!=(*(IDs::generator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1661 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       G__letint(result7, 103, (long) ((const IDs::generator*) G__getstructoffset())->operator<(*(IDs::generator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1667 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       G__letint(result7, 103, (long) ((const IDs::generator*) G__getstructoffset())->operator>(*(IDs::generator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_407_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1673 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLgenerator().
 {
       {
          const string* pobj;
          const string xobj = ((const IDs::generator*) G__getstructoffset())->str();
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1806 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLsource.
Referenced by G__setup_memfuncIDscLcLsource().
 {
    IDs::source* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::source[n];
      } else {
        p = new((void*) gvp) IDs::source[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::source;
      } else {
        p = new((void*) gvp) IDs::source;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1932 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       {
          const IDs::generator& obj = ((IDs::source*) G__getstructoffset())->Generator();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1942 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       {
          const IDs::channel& obj = ((IDs::source*) G__getstructoffset())->Channel();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1952 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       {
          const IDs::generator& obj = ((const IDs::source*) G__getstructoffset())->Generator();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1962 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       {
          const IDs::channel& obj = ((const IDs::source*) G__getstructoffset())->Channel();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1972 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       {
          const string* pobj;
          const string xobj = ((const IDs::source*) G__getstructoffset())->str();
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1985 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 85, (long) IDs::source::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1991 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 67, (long) IDs::source::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1997 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 115, (long) IDs::source::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2003 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       IDs::source::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1830 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLsource.
Referenced by G__setup_memfuncIDscLcLsource().
 {
    IDs::source* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new IDs::source(*(IDs::channel*) libp->para[0].ref, *(IDs::generator*) libp->para[1].ref);
    } else {
      p = new((void*) gvp) IDs::source(*(IDs::channel*) libp->para[0].ref, *(IDs::generator*) libp->para[1].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2010 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       ((IDs::source*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2017 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 67, (long) IDs::source::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2023 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 105, (long) IDs::source::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2029 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 67, (long) IDs::source::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2035 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 105, (long) IDs::source::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2042 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLsource.
Referenced by G__setup_memfuncIDscLcLsource().
 {
    IDs::source* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new IDs::source(*(IDs::source*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_28 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2056 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncIDscLcLsource().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (IDs::source*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((IDs::source*) (soff+(sizeof(IDs::source)*i)))->~G__TIDscLcLsource();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (IDs::source*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((IDs::source*) (soff))->~G__TIDscLcLsource();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_29 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2093 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
    IDs::source* dest = (IDs::source*) G__getstructoffset();
    *dest = *(IDs::source*) libp->para[0].ref;
    const IDs::source& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1846 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLsource.
Referenced by G__setup_memfuncIDscLcLsource().
 {
    IDs::source* p = NULL;
    char* gvp = (char*) G__getgvp();
    switch (libp->paran) {
    case 4:
      //m: 4
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::source(
 *(string*) libp->para[0].ref, *(string*) libp->para[1].ref
 , *(string*) libp->para[2].ref, *(string*) libp->para[3].ref);
      } else {
        p = new((void*) gvp) IDs::source(
 *(string*) libp->para[0].ref, *(string*) libp->para[1].ref
 , *(string*) libp->para[2].ref, *(string*) libp->para[3].ref);
      }
      break;
    case 3:
      //m: 3
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new IDs::source(
 *(string*) libp->para[0].ref, *(string*) libp->para[1].ref
 , *(string*) libp->para[2].ref);
      } else {
        p = new((void*) gvp) IDs::source(
 *(string*) libp->para[0].ref, *(string*) libp->para[1].ref
 , *(string*) libp->para[2].ref);
      }
      break;
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1882 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLsource.
Referenced by G__setup_memfuncIDscLcLsource().
 {
    IDs::source* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 4
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new IDs::source(
 (IDs::Detector_t) G__int(libp->para[0]), (IDs::SlowFast_t) G__int(libp->para[1])
 , *(IDs::Generator_t*) libp->para[2].ref, *(IDs::Config_t*) libp->para[3].ref);
    } else {
      p = new((void*) gvp) IDs::source(
 (IDs::Detector_t) G__int(libp->para[0]), (IDs::SlowFast_t) G__int(libp->para[1])
 , *(IDs::Generator_t*) libp->para[2].ref, *(IDs::Config_t*) libp->para[3].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1902 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 103, (long) ((const IDs::source*) G__getstructoffset())->operator==(*(IDs::source*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1908 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 103, (long) ((const IDs::source*) G__getstructoffset())->operator==(*(IDs::generator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1914 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 103, (long) ((const IDs::source*) G__getstructoffset())->operator==(*(IDs::channel*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1920 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 103, (long) ((const IDs::source*) G__getstructoffset())->operator>(*(IDs::source*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_408_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 1926 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncIDscLcLsource().
 {
       G__letint(result7, 103, (long) ((const IDs::source*) G__getstructoffset())->operator<(*(IDs::source*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2105 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_TAnalysedPulse.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    TAnalysedPulse* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TAnalysedPulse[n];
      } else {
        p = new((void*) gvp) TAnalysedPulse[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TAnalysedPulse;
      } else {
        p = new((void*) gvp) TAnalysedPulse;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2225 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       {
          const string* pobj;
          const string xobj = ((const TAnalysedPulse*) G__getstructoffset())->GetAlgorithmStamp();
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2238 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 85, (long) TAnalysedPulse::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2244 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 67, (long) TAnalysedPulse::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2250 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 115, (long) TAnalysedPulse::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2256 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       TAnalysedPulse::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2263 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       ((TAnalysedPulse*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2270 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 67, (long) TAnalysedPulse::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2129 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_TAnalysedPulse.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    TAnalysedPulse* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 5
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new TAnalysedPulse(
 (double) G__double(libp->para[0]), (double) G__double(libp->para[1])
 , (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
 , *((string*) G__int(libp->para[4])));
    } else {
      p = new((void*) gvp) TAnalysedPulse(
 (double) G__double(libp->para[0]), (double) G__double(libp->para[1])
 , (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
 , *((string*) G__int(libp->para[4])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2276 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 105, (long) TAnalysedPulse::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2282 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 67, (long) TAnalysedPulse::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2288 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letint(result7, 105, (long) TAnalysedPulse::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2295 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_TAnalysedPulse.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    TAnalysedPulse* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TAnalysedPulse(*(TAnalysedPulse*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2309 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TAnalysedPulse*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TAnalysedPulse*) (soff+(sizeof(TAnalysedPulse)*i)))->~G__TTAnalysedPulse();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TAnalysedPulse*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TAnalysedPulse*) (soff))->~G__TTAnalysedPulse();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2346 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    TAnalysedPulse* dest = (TAnalysedPulse*) G__getstructoffset();
    *dest = *(TAnalysedPulse*) libp->para[0].ref;
    const TAnalysedPulse& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2151 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_TAnalysedPulse.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    TAnalysedPulse* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 6
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new TAnalysedPulse(
 (double) G__double(libp->para[0]), (double) G__double(libp->para[1])
 , (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
 , *((string*) G__int(libp->para[4])), *((string*) G__int(libp->para[5])));
    } else {
      p = new((void*) gvp) TAnalysedPulse(
 (double) G__double(libp->para[0]), (double) G__double(libp->para[1])
 , (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
 , *((string*) G__int(libp->para[4])), *((string*) G__int(libp->para[5])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2173 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
    switch (libp->paran) {
    case 1:
       ((TAnalysedPulse*) G__getstructoffset())->Reset((Option_t*) G__int(libp->para[0]));
       G__setnull(result7);
       break;
    case 0:
       ((TAnalysedPulse*) G__getstructoffset())->Reset();
       G__setnull(result7);
       break;
    }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2188 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letdouble(result7, 100, (double) ((const TAnalysedPulse*) G__getstructoffset())->GetAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2194 of file RootanaDataClasses.cpp.
References GetTime().
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letdouble(result7, 100, (double) ((const TAnalysedPulse*) G__getstructoffset())->GetTime());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2200 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letdouble(result7, 100, (double) ((const TAnalysedPulse*) G__getstructoffset())->GetIntegral());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2206 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       G__letdouble(result7, 100, (double) ((const TAnalysedPulse*) G__getstructoffset())->GetEnergy());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_430_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2212 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulse().
 {
       {
          const string* pobj;
          const string xobj = ((const TAnalysedPulse*) G__getstructoffset())->GetDetName();
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2358 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reference obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->at((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2449 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->resize((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]), (TAnalysedPulse*) G__int(libp->para[1]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2456 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->capacity());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2462 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       G__letint(result7, 103, (long) ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->empty());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2468 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reference obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->operator[]((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2478 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_reference obj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->operator[]((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2488 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >[n];
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >;
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2512 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    switch (libp->paran) {
    case 2:
      //m: 2
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]), libp->para[1].ref ? *(TAnalysedPulse**) libp->para[1].ref : *(TAnalysedPulse**) (void*) (&G__Mlong(libp->para[1])));
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]), libp->para[1].ref ? *(TAnalysedPulse**) libp->para[1].ref : *(TAnalysedPulse**) (void*) (&G__Mlong(libp->para[1])));
      }
      break;
    case 1:
      //m: 1
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
      }
      break;
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2540 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2556 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[0])), *((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[0])), *((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2572 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->operator=(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2368 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_reference obj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->at((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2582 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->reserve((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2589 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          TAnalysedPulse*& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->front();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2599 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          TAnalysedPulse*& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->back();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2609 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->push_back(libp->para[0].ref ? *(TAnalysedPulse**) libp->para[0].ref : *(TAnalysedPulse**) (void*) (&G__Mlong(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2616 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->swap(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2623 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->insert(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[0])), libp->para[1].ref ? *(TAnalysedPulse**) libp->para[1].ref : *(TAnalysedPulse**) (void*) (&G__Mlong(libp->para[1])));
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2636 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->insert(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[0])), *((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[1]))
 , *((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator*) G__int(libp->para[2])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2644 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->insert(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[0])), (vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[1])
 , libp->para[2].ref ? *(TAnalysedPulse**) libp->para[2].ref : *(TAnalysedPulse**) (void*) (&G__Mlong(libp->para[2])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_28 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2652 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->pop_back();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_29 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2659 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->erase(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2378 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->begin();
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_30 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2666 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->erase(*((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[0])), *((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_31 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2673 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->clear();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_32 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2682 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) (soff+(sizeof(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >)*i)))->~G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) (soff))->~G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2391 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->end();
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2404 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->rbegin();
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2417 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->rend();
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2430 of file RootanaDataClasses.cpp.
References size.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2436 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->max_size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_432_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2442 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
 {
       ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) G__getstructoffset())->resize((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type) G__int(libp->para[0]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2720 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator[n];
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator;
      } else {
        p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2832 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator+=(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2842 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator+(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2855 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator-=(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2865 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator-(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2878 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer& obj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->base();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2888 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator=(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) libp->para[0].ref);
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2902 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2916 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) (soff+(sizeof(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator)*i)))->~G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) (soff))->~G__TvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2744 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
    vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(libp->para[0].ref ? *(const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer*) libp->para[0].ref : *(const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer*) (void*) (&G__Mlong(libp->para[0])));
    } else {
      p = new((void*) gvp) vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(libp->para[0].ref ? *(const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer*) libp->para[0].ref : *(const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer*) (void*) (&G__Mlong(libp->para[0])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2760 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::reference obj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator*();
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2770 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       G__letint(result7, 85, (long) ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator->());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2776 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator++();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2786 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator++((int) G__int(libp->para[0]));
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2799 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator& obj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator--();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2809 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator* pobj;
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator xobj = ((vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator--((int) G__int(libp->para[0]));
          pobj = new vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_433_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2822 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
 {
       {
          vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::reference obj = ((const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) G__getstructoffset())->operator[](*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type*) G__Longref(&libp->para[0]));
          result7->ref = (long) (&obj);
          G__letint(result7, 'U', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2954 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >[n];
      } else {
        p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >;
      } else {
        p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3088 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 103, (long) ((const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->empty());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3094 of file RootanaDataClasses.cpp.
References size.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3100 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->max_size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3106 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          const vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->operator[](*(string*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3116 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          pair<map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator,bool>* pobj;
          pair<map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator,bool> xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->insert(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type*) libp->para[0].ref);
          pobj = new pair<map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator,bool>(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3129 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->insert(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])), *(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type*) libp->para[1].ref);
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3142 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->insert(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3149 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->insert(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3156 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->erase(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3163 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->erase(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2978 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3169 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->erase(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3176 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->swap(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3183 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->clear();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3190 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->find(*(string*) libp->para[0].ref);
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3203 of file RootanaDataClasses.cpp.
References count.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->count(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3209 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->lower_bound(*(string*) libp->para[0].ref);
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3222 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->upper_bound(*(string*) libp->para[0].ref);
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3237 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) (soff+(sizeof(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >)*i)))->~G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) (soff))->~G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 2994 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3010 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3026 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->operator=(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3036 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->begin();
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3049 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->end();
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3062 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->rbegin();
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_446_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3075 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*) G__getstructoffset())->rend();
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_447_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3275 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR.
Referenced by G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR().
 {
    pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >[n];
      } else {
        p = new((void*) gvp) pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >;
      } else {
        p = new((void*) gvp) pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_447_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3299 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR.
Referenced by G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR().
 {
    pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >(*(string*) libp->para[0].ref, *(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[1].ref);
    } else {
      p = new((void*) gvp) pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >(*(string*) libp->para[0].ref, *(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*) libp->para[1].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_447_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3316 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR.
Referenced by G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR().
 {
    pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >(*(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_447_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3330 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*) (soff+(sizeof(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >)*i)))->~G__TpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*) (soff))->~G__TpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3368 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator[n];
      } else {
        p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator;
      } else {
        p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3480 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 103, (long) ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator==(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3486 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 103, (long) ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator!=(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3494 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) (soff+(sizeof(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator)*i)))->~G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) (soff))->~G__TmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3392 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
    map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3408 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator=(*(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3418 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator*();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3428 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       G__letint(result7, 85, (long) ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator->());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3434 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator++();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3444 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator++((int) G__int(libp->para[0]));
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3457 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          const map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator& obj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator--();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_448_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3467 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
 {
       {
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator* pobj;
          map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator xobj = ((map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*) G__getstructoffset())->operator--((int) G__int(libp->para[0]));
          pobj = new map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3532 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_TDetectorPulse.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    TDetectorPulse* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TDetectorPulse[n];
      } else {
        p = new((void*) gvp) TDetectorPulse[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TDetectorPulse;
      } else {
        p = new((void*) gvp) TDetectorPulse;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_TDetectorPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3627 of file RootanaDataClasses.cpp.
References GetTime().
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetTime());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3633 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3639 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       {
          const string* pobj;
          const string xobj = ((const TDetectorPulse*) G__getstructoffset())->GetDetName();
          pobj = new string(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3652 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 103, (long) ((const TDetectorPulse*) G__getstructoffset())->IsPileUpSafe());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3658 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    switch (libp->paran) {
    case 1:
       ((TDetectorPulse*) G__getstructoffset())->SetPileUpSafe(*(bool*) G__Boolref(&libp->para[0]));
       G__setnull(result7);
       break;
    case 0:
       ((TDetectorPulse*) G__getstructoffset())->SetPileUpSafe();
       G__setnull(result7);
       break;
    }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3673 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 103, (long) ((const TDetectorPulse*) G__getstructoffset())->WasPileUpChecked());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3679 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    switch (libp->paran) {
    case 1:
       ((TDetectorPulse*) G__getstructoffset())->SetPileUpChecked(*(bool*) G__Boolref(&libp->para[0]));
       G__setnull(result7);
       break;
    case 0:
       ((TDetectorPulse*) G__getstructoffset())->SetPileUpChecked();
       G__setnull(result7);
       break;
    }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3694 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 85, (long) TDetectorPulse::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3700 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 67, (long) TDetectorPulse::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3706 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 115, (long) TDetectorPulse::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3556 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_TDetectorPulse.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    TDetectorPulse* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 3
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new TDetectorPulse(
 (TAnalysedPulse*) G__int(libp->para[0]), (TAnalysedPulse*) G__int(libp->para[1])
 , *((string*) G__int(libp->para[2])));
    } else {
      p = new((void*) gvp) TDetectorPulse(
 (TAnalysedPulse*) G__int(libp->para[0]), (TAnalysedPulse*) G__int(libp->para[1])
 , *((string*) G__int(libp->para[2])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_TDetectorPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3712 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       TDetectorPulse::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3719 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       ((TDetectorPulse*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3726 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 67, (long) TDetectorPulse::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3732 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 105, (long) TDetectorPulse::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3738 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 67, (long) TDetectorPulse::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_28 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3744 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letint(result7, 105, (long) TDetectorPulse::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_29 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3751 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_TDetectorPulse.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    TDetectorPulse* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TDetectorPulse(*(TDetectorPulse*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_TDetectorPulse));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3576 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    switch (libp->paran) {
    case 1:
       ((TDetectorPulse*) G__getstructoffset())->Reset((Option_t*) G__int(libp->para[0]));
       G__setnull(result7);
       break;
    case 0:
       ((TDetectorPulse*) G__getstructoffset())->Reset();
       G__setnull(result7);
       break;
    }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_30 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3765 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TDetectorPulse*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TDetectorPulse*) (soff+(sizeof(TDetectorPulse)*i)))->~G__TTDetectorPulse();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TDetectorPulse*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TDetectorPulse*) (soff))->~G__TTDetectorPulse();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_31 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3802 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
    TDetectorPulse* dest = (TDetectorPulse*) G__getstructoffset();
    *dest = *(TDetectorPulse*) libp->para[0].ref;
    const TDetectorPulse& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3591 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetFastPulseAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3597 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetSlowPulseAmplitude());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3603 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetFastPulseTime());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3609 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetSlowPulseTime());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3615 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetFastPulseIntegral());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_451_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3621 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTDetectorPulse().
 {
       G__letdouble(result7, 100, (double) ((const TDetectorPulse*) G__getstructoffset())->GetSlowPulseIntegral());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3814 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          const vector<string,allocator<string> >::reference obj = ((vector<string,allocator<string> >*) G__getstructoffset())->at((vector<string,allocator<string> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3905 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       ((vector<string,allocator<string> >*) G__getstructoffset())->resize((vector<string,allocator<string> >::size_type) G__int(libp->para[0]), *((string*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3912 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<string,allocator<string> >*) G__getstructoffset())->capacity());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3918 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       G__letint(result7, 103, (long) ((const vector<string,allocator<string> >*) G__getstructoffset())->empty());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3924 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          const vector<string,allocator<string> >::reference obj = ((vector<string,allocator<string> >*) G__getstructoffset())->operator[]((vector<string,allocator<string> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3934 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          vector<string,allocator<string> >::const_reference obj = ((const vector<string,allocator<string> >*) G__getstructoffset())->operator[]((vector<string,allocator<string> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3944 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
    vector<string,allocator<string> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<string,allocator<string> >[n];
      } else {
        p = new((void*) gvp) vector<string,allocator<string> >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<string,allocator<string> >;
      } else {
        p = new((void*) gvp) vector<string,allocator<string> >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3968 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
    vector<string,allocator<string> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    switch (libp->paran) {
    case 2:
      //m: 2
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<string,allocator<string> >((vector<string,allocator<string> >::size_type) G__int(libp->para[0]), *(string*) libp->para[1].ref);
      } else {
        p = new((void*) gvp) vector<string,allocator<string> >((vector<string,allocator<string> >::size_type) G__int(libp->para[0]), *(string*) libp->para[1].ref);
      }
      break;
    case 1:
      //m: 1
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<string,allocator<string> >((vector<string,allocator<string> >::size_type) G__int(libp->para[0]));
      } else {
        p = new((void*) gvp) vector<string,allocator<string> >((vector<string,allocator<string> >::size_type) G__int(libp->para[0]));
      }
      break;
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3996 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
    vector<string,allocator<string> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new vector<string,allocator<string> >(*(vector<string,allocator<string> >*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) vector<string,allocator<string> >(*(vector<string,allocator<string> >*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4012 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
    vector<string,allocator<string> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new vector<string,allocator<string> >(*((vector<string,allocator<string> >::const_iterator*) G__int(libp->para[0])), *((vector<string,allocator<string> >::const_iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) vector<string,allocator<string> >(*((vector<string,allocator<string> >::const_iterator*) G__int(libp->para[0])), *((vector<string,allocator<string> >::const_iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4028 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          const vector<string,allocator<string> >& obj = ((vector<string,allocator<string> >*) G__getstructoffset())->operator=(*(vector<string,allocator<string> >*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3824 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          vector<string,allocator<string> >::const_reference obj = ((const vector<string,allocator<string> >*) G__getstructoffset())->at((vector<string,allocator<string> >::size_type) G__int(libp->para[0]));
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4038 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       ((vector<string,allocator<string> >*) G__getstructoffset())->reserve((vector<string,allocator<string> >::size_type) G__int(libp->para[0]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4045 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          const string& obj = ((vector<string,allocator<string> >*) G__getstructoffset())->front();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4055 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          const string& obj = ((vector<string,allocator<string> >*) G__getstructoffset())->back();
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4065 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       ((vector<string,allocator<string> >*) G__getstructoffset())->push_back(*(string*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4072 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       ((vector<string,allocator<string> >*) G__getstructoffset())->swap(*(vector<string,allocator<string> >*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4079 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          vector<string,allocator<string> >::iterator* pobj;
          vector<string,allocator<string> >::iterator xobj = ((vector<string,allocator<string> >*) G__getstructoffset())->insert(*((vector<string,allocator<string> >::iterator*) G__int(libp->para[0])), *(string*) libp->para[1].ref);
          pobj = new vector<string,allocator<string> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4092 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       ((vector<string,allocator<string> >*) G__getstructoffset())->insert(*((vector<string,allocator<string> >::iterator*) G__int(libp->para[0])), *((vector<string,allocator<string> >::const_iterator*) G__int(libp->para[1]))
 , *((vector<string,allocator<string> >::const_iterator*) G__int(libp->para[2])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4100 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       ((vector<string,allocator<string> >*) G__getstructoffset())->insert(*((vector<string,allocator<string> >::iterator*) G__int(libp->para[0])), (vector<string,allocator<string> >::size_type) G__int(libp->para[1])
 , *(string*) libp->para[2].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_28 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4108 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       ((vector<string,allocator<string> >*) G__getstructoffset())->pop_back();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_29 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4115 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       ((vector<string,allocator<string> >*) G__getstructoffset())->erase(*((vector<string,allocator<string> >::iterator*) G__int(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3834 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          vector<string,allocator<string> >::iterator* pobj;
          vector<string,allocator<string> >::iterator xobj = ((vector<string,allocator<string> >*) G__getstructoffset())->begin();
          pobj = new vector<string,allocator<string> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_30 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4122 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       ((vector<string,allocator<string> >*) G__getstructoffset())->erase(*((vector<string,allocator<string> >::iterator*) G__int(libp->para[0])), *((vector<string,allocator<string> >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_31 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4129 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       ((vector<string,allocator<string> >*) G__getstructoffset())->clear();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_32 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4138 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (vector<string,allocator<string> >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((vector<string,allocator<string> >*) (soff+(sizeof(vector<string,allocator<string> >)*i)))->~G__TvectorlEstringcOallocatorlEstringgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (vector<string,allocator<string> >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((vector<string,allocator<string> >*) (soff))->~G__TvectorlEstringcOallocatorlEstringgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3847 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          vector<string,allocator<string> >::iterator* pobj;
          vector<string,allocator<string> >::iterator xobj = ((vector<string,allocator<string> >*) G__getstructoffset())->end();
          pobj = new vector<string,allocator<string> >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3860 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          vector<string,allocator<string> >::reverse_iterator* pobj;
          vector<string,allocator<string> >::reverse_iterator xobj = ((vector<string,allocator<string> >*) G__getstructoffset())->rbegin();
          pobj = new vector<string,allocator<string> >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3873 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       {
          vector<string,allocator<string> >::reverse_iterator* pobj;
          vector<string,allocator<string> >::reverse_iterator xobj = ((vector<string,allocator<string> >*) G__getstructoffset())->rend();
          pobj = new vector<string,allocator<string> >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3886 of file RootanaDataClasses.cpp.
References size.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<string,allocator<string> >*) G__getstructoffset())->size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3892 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       G__letint(result7, 107, (long) ((const vector<string,allocator<string> >*) G__getstructoffset())->max_size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_591_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 3898 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
 {
       ((vector<string,allocator<string> >*) G__getstructoffset())->resize((vector<string,allocator<string> >::size_type) G__int(libp->para[0]));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4176 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_TAnalysedPulseMapWrapper.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
    TAnalysedPulseMapWrapper* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TAnalysedPulseMapWrapper[n];
      } else {
        p = new((void*) gvp) TAnalysedPulseMapWrapper[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new TAnalysedPulseMapWrapper;
      } else {
        p = new((void*) gvp) TAnalysedPulseMapWrapper;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4268 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       TAnalysedPulseMapWrapper::Dictionary();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4275 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       ((TAnalysedPulseMapWrapper*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4282 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       G__letint(result7, 67, (long) TAnalysedPulseMapWrapper::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4288 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       G__letint(result7, 105, (long) TAnalysedPulseMapWrapper::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4294 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       G__letint(result7, 67, (long) TAnalysedPulseMapWrapper::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4300 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       G__letint(result7, 105, (long) TAnalysedPulseMapWrapper::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4307 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_TAnalysedPulseMapWrapper.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
    TAnalysedPulseMapWrapper* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new TAnalysedPulseMapWrapper(*(TAnalysedPulseMapWrapper*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4200 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_TAnalysedPulseMapWrapper.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
    TAnalysedPulseMapWrapper* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new TAnalysedPulseMapWrapper(*((StringAnalPulseMap*) G__int(libp->para[0])));
    } else {
      p = new((void*) gvp) TAnalysedPulseMapWrapper(*((StringAnalPulseMap*) G__int(libp->para[0])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4321 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (TAnalysedPulseMapWrapper*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((TAnalysedPulseMapWrapper*) (soff+(sizeof(TAnalysedPulseMapWrapper)*i)))->~G__TTAnalysedPulseMapWrapper();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (TAnalysedPulseMapWrapper*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((TAnalysedPulseMapWrapper*) (soff))->~G__TTAnalysedPulseMapWrapper();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4358 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
    TAnalysedPulseMapWrapper* dest = (TAnalysedPulseMapWrapper*) G__getstructoffset();
    *dest = *(TAnalysedPulseMapWrapper*) libp->para[0].ref;
    const TAnalysedPulseMapWrapper& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4216 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       ((TAnalysedPulseMapWrapper*) G__getstructoffset())->ShowInfo();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4223 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       ((TAnalysedPulseMapWrapper*) G__getstructoffset())->Reset();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4230 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       {
          StringAnalPulseMap* pobj;
          StringAnalPulseMap xobj = ((TAnalysedPulseMapWrapper*) G__getstructoffset())->GetMap();
          pobj = new StringAnalPulseMap(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4243 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       ((TAnalysedPulseMapWrapper*) G__getstructoffset())->SetMap(*((StringAnalPulseMap*) G__int(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4250 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       G__letint(result7, 85, (long) TAnalysedPulseMapWrapper::Class());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4256 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       G__letint(result7, 67, (long) TAnalysedPulseMapWrapper::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_594_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4262 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncTAnalysedPulseMapWrapper().
 {
       G__letint(result7, 115, (long) TAnalysedPulseMapWrapper::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4370 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
    map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >[n];
      } else {
        p = new((void*) gvp) map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >;
      } else {
        p = new((void*) gvp) map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4504 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       G__letint(result7, 103, (long) ((const map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->empty());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4510 of file RootanaDataClasses.cpp.
References size.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4516 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->max_size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4522 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       {
          const IDs::Detector_t& obj = ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->operator[](*(string*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          G__letint(result7, 'i', (long)obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4532 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       {
          pair<map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator,bool>* pobj;
          pair<map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator,bool> xobj = ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->insert(*(map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::value_type*) libp->para[0].ref);
          pobj = new pair<map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator,bool>(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4545 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       {
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator* pobj;
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator xobj = ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->insert(*((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator*) G__int(libp->para[0])), *(map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::value_type*) libp->para[1].ref);
          pobj = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4558 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->insert(*((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator*) G__int(libp->para[0])), *((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4565 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->insert(*((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4572 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->erase(*((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator*) G__int(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4579 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->erase(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4394 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
    map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >(*((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator*) G__int(libp->para[0])), *((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >(*((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator*) G__int(libp->para[0])), *((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4585 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->erase(*((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator*) G__int(libp->para[0])), *((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4592 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->swap(*(map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4599 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->clear();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4606 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       {
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator* pobj;
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator xobj = ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->find(*(string*) libp->para[0].ref);
          pobj = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4619 of file RootanaDataClasses.cpp.
References count.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->count(*(string*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4625 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       {
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator* pobj;
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator xobj = ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->lower_bound(*(string*) libp->para[0].ref);
          pobj = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4638 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       {
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator* pobj;
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator xobj = ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->upper_bound(*(string*) libp->para[0].ref);
          pobj = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4653 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) (soff+(sizeof(map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >)*i)))->~G__TmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) (soff))->~G__TmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4410 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
    map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >(*((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >(*((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator*) G__int(libp->para[0])), *((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4426 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
    map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >(*(map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >(*(map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4442 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       {
          const map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >& obj = ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->operator=(*(map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4452 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       {
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator* pobj;
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator xobj = ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->begin();
          pobj = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4465 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       {
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator* pobj;
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator xobj = ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->end();
          pobj = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4478 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       {
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator* pobj;
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator xobj = ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->rbegin();
          pobj = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_597_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4491 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
 {
       {
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator* pobj;
          map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator xobj = ((map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*) G__getstructoffset())->rend();
          pobj = new map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_1 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4691 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
    map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >[n];
      } else {
        p = new((void*) gvp) map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >[n];
      }
    } else {
      if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >;
      } else {
        p = new((void*) gvp) map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >;
      }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_10 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4825 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       G__letint(result7, 103, (long) ((const map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->empty());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_11 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4831 of file RootanaDataClasses.cpp.
References size.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_12 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4837 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->max_size());
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_13 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4843 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       {
          const string& obj = ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->operator[](*(IDs::Detector_t*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_14 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4853 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       {
          pair<map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator,bool>* pobj;
          pair<map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator,bool> xobj = ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->insert(*(map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::value_type*) libp->para[0].ref);
          pobj = new pair<map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator,bool>(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_15 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4866 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       {
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator* pobj;
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator xobj = ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->insert(*((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator*) G__int(libp->para[0])), *(map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::value_type*) libp->para[1].ref);
          pobj = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_16 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4879 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->insert(*((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator*) G__int(libp->para[0])), *((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_17 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4886 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->insert(*((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator*) G__int(libp->para[0])), *((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_18 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4893 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->erase(*((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator*) G__int(libp->para[0])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_19 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4900 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->erase(*(IDs::Detector_t*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_2 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4715 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
    map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >(*((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator*) G__int(libp->para[0])), *((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >(*((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator*) G__int(libp->para[0])), *((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_20 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4906 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->erase(*((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator*) G__int(libp->para[0])), *((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator*) G__int(libp->para[1])));
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_21 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4913 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->swap(*(map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) libp->para[0].ref);
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_22 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4920 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->clear();
       G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_23 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4927 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       {
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator* pobj;
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator xobj = ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->find(*(IDs::Detector_t*) libp->para[0].ref);
          pobj = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_24 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4940 of file RootanaDataClasses.cpp.
References count.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       G__letint(result7, 107, (long) ((const map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->count(*(IDs::Detector_t*) libp->para[0].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_25 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4946 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       {
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator* pobj;
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator xobj = ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->lower_bound(*(IDs::Detector_t*) libp->para[0].ref);
          pobj = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_26 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4959 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       {
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator* pobj;
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator xobj = ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->upper_bound(*(IDs::Detector_t*) libp->para[0].ref);
          pobj = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_27 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4974 of file RootanaDataClasses.cpp.
References i.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
      return(1);
    }
    if (n) {
      if (gvp == (char*)G__PVOID) {
        delete[] (map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        for (int i = n - 1; i >= 0; --i) {
          ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) (soff+(sizeof(map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >)*i)))->~G__TmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR();
        }
        G__setgvp((long)gvp);
      }
    } else {
      if (gvp == (char*)G__PVOID) {
        delete (map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) soff;
      } else {
        G__setgvp((long) G__PVOID);
        ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) (soff))->~G__TmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR();
        G__setgvp((long)gvp);
      }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_3 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4731 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
    map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >(*((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator*) G__int(libp->para[0])), *((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator*) G__int(libp->para[1])));
    } else {
      p = new((void*) gvp) map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >(*((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator*) G__int(libp->para[0])), *((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_4 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4747 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
    map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
      p = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >(*(map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) libp->para[0].ref);
    } else {
      p = new((void*) gvp) map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >(*(map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_5 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4763 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       {
          const map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >& obj = ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->operator=(*(map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) libp->para[0].ref);
          result7->ref = (long) (&obj);
          result7->obj.i = (long) (&obj);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_6 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4773 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       {
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator* pobj;
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator xobj = ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->begin();
          pobj = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_7 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4786 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       {
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator* pobj;
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator xobj = ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->end();
          pobj = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_8 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4799 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       {
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator* pobj;
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator xobj = ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->rbegin();
          pobj = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses_606_0_9 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 4812 of file RootanaDataClasses.cpp.
Referenced by G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
 {
       {
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator* pobj;
          map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator xobj = ((map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*) G__getstructoffset())->rend();
          pobj = new map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator(xobj);
          result7->obj.i = (long) ((void*) pobj);
          result7->ref = result7->obj.i;
          G__store_tempobject(*result7);
       }
    return(1 || funcname || hash || result7 || libp) ;
 }
static int G__RootanaDataClasses__0_1771 (G__value * result7, G__CONST char * funcname, struct G__param * libp, int hash) static
Definition at line 5012 of file RootanaDataClasses.cpp.
Referenced by G__cpp_setup_func17().
 {
       G__letint(result7, 103, (long) operator!=(*(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) libp->para[0].ref, *(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*) libp->para[1].ref));
    return(1 || funcname || hash || result7 || libp) ;
 }
void G__set_cpp_environmentRootanaDataClasses ()
Definition at line 1261 of file RootanaDataClasses.cpp.
References G__cpp_reset_tagtableRootanaDataClasses().
Referenced by G__cpp_setupRootanaDataClasses().
{
   G__cpp_reset_tagtableRootanaDataClasses();
 }
static void G__setup_memfuncIDscLcLchannel (void) static
Definition at line 5558 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_404_0_1(), G__RootanaDataClasses_404_0_10(), G__RootanaDataClasses_404_0_11(), G__RootanaDataClasses_404_0_12(), G__RootanaDataClasses_404_0_13(), G__RootanaDataClasses_404_0_14(), G__RootanaDataClasses_404_0_15(), G__RootanaDataClasses_404_0_16(), G__RootanaDataClasses_404_0_17(), G__RootanaDataClasses_404_0_18(), G__RootanaDataClasses_404_0_19(), G__RootanaDataClasses_404_0_2(), G__RootanaDataClasses_404_0_20(), G__RootanaDataClasses_404_0_21(), G__RootanaDataClasses_404_0_22(), G__RootanaDataClasses_404_0_23(), G__RootanaDataClasses_404_0_24(), G__RootanaDataClasses_404_0_25(), G__RootanaDataClasses_404_0_26(), G__RootanaDataClasses_404_0_27(), G__RootanaDataClasses_404_0_28(), G__RootanaDataClasses_404_0_3(), G__RootanaDataClasses_404_0_4(), G__RootanaDataClasses_404_0_5(), G__RootanaDataClasses_404_0_6(), G__RootanaDataClasses_404_0_7(), G__RootanaDataClasses_404_0_8(), G__RootanaDataClasses_404_0_9(), G__RootanaDataClassesLN_IDscLcLchannel, G__RootanaDataClassesLN_IDscLcLDetector_t, G__RootanaDataClassesLN_IDscLcLSlowFast_t, G__RootanaDataClassesLN_string, G__RootanaDataClassesLN_TClass, IDs::channel::GetDetectorEnum(), IDs::channel::GetDetectorString(), IDs::channel::GetSlowFastEnum(), and IDs::channel::GetSlowFastString().
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* IDs::channel */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel));
    G__memfunc_setup("channel",729,G__RootanaDataClasses_404_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel), -1, 0, 2, 1, 1, 0,
 "i 'IDs::Detector_t' - 0 'kAnyDetector' det i 'IDs::SlowFast_t' - 0 'kAnySlowFast' type", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("channel",729,G__RootanaDataClasses_404_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel), -1, 0, 2, 1, 1, 0,
 "u 'string' - 11 - detector u 'string' - 11 '\"\"' type", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Detector",826,G__RootanaDataClasses_404_0_3, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLDetector_t), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SlowFast",819,G__RootanaDataClasses_404_0_4, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLSlowFast_t), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator==",998,G__RootanaDataClasses_404_0_5, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::channel' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator!=",970,G__RootanaDataClasses_404_0_6, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::channel' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator<",936,G__RootanaDataClasses_404_0_7, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::channel' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator>",938,G__RootanaDataClasses_404_0_8, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::channel' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("str",345,G__RootanaDataClasses_404_0_9, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetDetectorString",1745,G__RootanaDataClasses_404_0_10, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), -1, 0, 1, 3, 1, 0, "i 'IDs::Detector_t' - 0 - det", (char*)NULL, (void*) G__func2void( (string (*)(IDs::Detector_t))(&IDs::channel::GetDetectorString) ), 0);
    G__memfunc_setup("GetDetectorEnum",1519,G__RootanaDataClasses_404_0_11, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLDetector_t), -1, 0, 1, 3, 1, 0, "u 'string' - 11 - det", (char*)NULL, (void*) G__func2void( (IDs::Detector_t (*)(const string&))(&IDs::channel::GetDetectorEnum) ), 0);
    G__memfunc_setup("GetSlowFastString",1738,G__RootanaDataClasses_404_0_12, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), -1, 0, 1, 3, 1, 0, "i 'IDs::SlowFast_t' - 0 - sf", (char*)NULL, (void*) G__func2void( (string (*)(IDs::SlowFast_t))(&IDs::channel::GetSlowFastString) ), 0);
    G__memfunc_setup("GetSlowFastEnum",1512,G__RootanaDataClasses_404_0_13, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLSlowFast_t), -1, 0, 1, 3, 1, 0, "u 'string' - 11 - sf", (char*)NULL, (void*) G__func2void( (IDs::SlowFast_t (*)(const string&))(&IDs::channel::GetSlowFastEnum) ), 0);
    G__memfunc_setup("Class",502,G__RootanaDataClasses_404_0_14, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&IDs::channel::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__RootanaDataClasses_404_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDs::channel::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__RootanaDataClasses_404_0_16, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&IDs::channel::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__RootanaDataClasses_404_0_17, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&IDs::channel::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,G__RootanaDataClasses_404_0_18, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,G__RootanaDataClasses_404_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,G__RootanaDataClasses_404_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__RootanaDataClasses_404_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__RootanaDataClasses_404_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDs::channel::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__RootanaDataClasses_404_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&IDs::channel::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__RootanaDataClasses_404_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDs::channel::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__RootanaDataClasses_404_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&IDs::channel::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("channel", 729, G__RootanaDataClasses_404_0_26, (int) ('i'), G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel), -1, 0, 1, 1, 1, 0, "u 'IDs::channel' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~channel", 855, G__RootanaDataClasses_404_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__RootanaDataClasses_404_0_28, (int) ('u'), G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel), -1, 1, 1, 1, 1, 0, "u 'IDs::channel' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncIDscLcLgenerator (void) static
Definition at line 5597 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_407_0_1(), G__RootanaDataClasses_407_0_10(), G__RootanaDataClasses_407_0_11(), G__RootanaDataClasses_407_0_12(), G__RootanaDataClasses_407_0_13(), G__RootanaDataClasses_407_0_17(), G__RootanaDataClasses_407_0_18(), G__RootanaDataClasses_407_0_19(), G__RootanaDataClasses_407_0_2(), G__RootanaDataClasses_407_0_20(), G__RootanaDataClasses_407_0_21(), G__RootanaDataClasses_407_0_22(), G__RootanaDataClasses_407_0_23(), G__RootanaDataClasses_407_0_24(), G__RootanaDataClasses_407_0_3(), G__RootanaDataClasses_407_0_4(), G__RootanaDataClasses_407_0_5(), G__RootanaDataClasses_407_0_6(), G__RootanaDataClasses_407_0_7(), G__RootanaDataClasses_407_0_8(), G__RootanaDataClasses_407_0_9(), G__RootanaDataClassesLN_IDscLcLgenerator, G__RootanaDataClassesLN_string, and G__RootanaDataClassesLN_TClass.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* IDs::generator */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator));
    G__memfunc_setup("generator",967,G__RootanaDataClasses_407_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator), -1, 0, 2, 1, 1, 0,
 "u 'string' 'IDs::Generator_t' 0 - t u 'string' 'IDs::Config_t' 0 '\"\"' c", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("generator",967,G__RootanaDataClasses_407_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Type",418,G__RootanaDataClasses_407_0_3, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), G__defined_typename("IDs::Generator_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Config",598,G__RootanaDataClasses_407_0_4, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), G__defined_typename("IDs::Config_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator==",998,G__RootanaDataClasses_407_0_5, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::generator' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator!=",970,G__RootanaDataClasses_407_0_6, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::generator' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator<",936,G__RootanaDataClasses_407_0_7, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::generator' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator>",938,G__RootanaDataClasses_407_0_8, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::generator' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("str",345,G__RootanaDataClasses_407_0_9, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__RootanaDataClasses_407_0_10, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&IDs::generator::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__RootanaDataClasses_407_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDs::generator::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__RootanaDataClasses_407_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&IDs::generator::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__RootanaDataClasses_407_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&IDs::generator::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__RootanaDataClasses_407_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__RootanaDataClasses_407_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDs::generator::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__RootanaDataClasses_407_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&IDs::generator::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__RootanaDataClasses_407_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDs::generator::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__RootanaDataClasses_407_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&IDs::generator::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("generator", 967, G__RootanaDataClasses_407_0_22, (int) ('i'), G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator), -1, 0, 1, 1, 1, 0, "u 'IDs::generator' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~generator", 1093, G__RootanaDataClasses_407_0_23, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__RootanaDataClasses_407_0_24, (int) ('u'), G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator), -1, 1, 1, 1, 1, 0, "u 'IDs::generator' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncIDscLcLsource (void) static
Definition at line 5631 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_408_0_1(), G__RootanaDataClasses_408_0_10(), G__RootanaDataClasses_408_0_11(), G__RootanaDataClasses_408_0_12(), G__RootanaDataClasses_408_0_13(), G__RootanaDataClasses_408_0_14(), G__RootanaDataClasses_408_0_15(), G__RootanaDataClasses_408_0_16(), G__RootanaDataClasses_408_0_17(), G__RootanaDataClasses_408_0_18(), G__RootanaDataClasses_408_0_2(), G__RootanaDataClasses_408_0_22(), G__RootanaDataClasses_408_0_23(), G__RootanaDataClasses_408_0_24(), G__RootanaDataClasses_408_0_25(), G__RootanaDataClasses_408_0_26(), G__RootanaDataClasses_408_0_27(), G__RootanaDataClasses_408_0_28(), G__RootanaDataClasses_408_0_29(), G__RootanaDataClasses_408_0_3(), G__RootanaDataClasses_408_0_4(), G__RootanaDataClasses_408_0_5(), G__RootanaDataClasses_408_0_6(), G__RootanaDataClasses_408_0_7(), G__RootanaDataClasses_408_0_8(), G__RootanaDataClasses_408_0_9(), G__RootanaDataClassesLN_IDscLcLchannel, G__RootanaDataClassesLN_IDscLcLgenerator, G__RootanaDataClassesLN_IDscLcLsource, G__RootanaDataClassesLN_string, and G__RootanaDataClassesLN_TClass.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* IDs::source */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource));
    G__memfunc_setup("source",657,G__RootanaDataClasses_408_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("source",657,G__RootanaDataClasses_408_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource), -1, 0, 2, 1, 1, 0,
 "u 'IDs::channel' - 11 - ch u 'IDs::generator' - 11 - gen", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("source",657,G__RootanaDataClasses_408_0_3, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource), -1, 0, 4, 1, 1, 0,
 "u 'string' - 11 - det u 'string' - 11 - type "
 "u 'string' - 11 - gen u 'string' - 11 'IDs::kAnyConfig' cfg", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("source",657,G__RootanaDataClasses_408_0_4, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource), -1, 0, 4, 1, 1, 0,
 "i 'IDs::Detector_t' - 0 - det i 'IDs::SlowFast_t' - 0 - type "
 "u 'string' 'IDs::Generator_t' 11 - t u 'string' 'IDs::Config_t' 11 - c", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator==",998,G__RootanaDataClasses_408_0_5, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::source' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator==",998,G__RootanaDataClasses_408_0_6, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::generator' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator==",998,G__RootanaDataClasses_408_0_7, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::channel' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator>",938,G__RootanaDataClasses_408_0_8, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::source' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator<",936,G__RootanaDataClasses_408_0_9, 103, -1, -1, 0, 1, 1, 1, 8, "u 'IDs::source' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Generator",935,G__RootanaDataClasses_408_0_10, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Channel",697,G__RootanaDataClasses_408_0_11, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Generator",935,G__RootanaDataClasses_408_0_12, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator), -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Channel",697,G__RootanaDataClasses_408_0_13, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel), -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("str",345,G__RootanaDataClasses_408_0_14, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__RootanaDataClasses_408_0_15, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&IDs::source::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__RootanaDataClasses_408_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDs::source::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__RootanaDataClasses_408_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&IDs::source::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__RootanaDataClasses_408_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&IDs::source::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__RootanaDataClasses_408_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__RootanaDataClasses_408_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDs::source::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__RootanaDataClasses_408_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&IDs::source::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__RootanaDataClasses_408_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IDs::source::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__RootanaDataClasses_408_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&IDs::source::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("source", 657, G__RootanaDataClasses_408_0_27, (int) ('i'), G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource), -1, 0, 1, 1, 1, 0, "u 'IDs::source' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~source", 783, G__RootanaDataClasses_408_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__RootanaDataClasses_408_0_29, (int) ('u'), G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource), -1, 1, 1, 1, 1, 0, "u 'IDs::source' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR (void) static
Definition at line 6022 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_606_0_1(), G__RootanaDataClasses_606_0_10(), G__RootanaDataClasses_606_0_11(), G__RootanaDataClasses_606_0_12(), G__RootanaDataClasses_606_0_13(), G__RootanaDataClasses_606_0_14(), G__RootanaDataClasses_606_0_15(), G__RootanaDataClasses_606_0_16(), G__RootanaDataClasses_606_0_17(), G__RootanaDataClasses_606_0_18(), G__RootanaDataClasses_606_0_19(), G__RootanaDataClasses_606_0_2(), G__RootanaDataClasses_606_0_20(), G__RootanaDataClasses_606_0_21(), G__RootanaDataClasses_606_0_22(), G__RootanaDataClasses_606_0_23(), G__RootanaDataClasses_606_0_24(), G__RootanaDataClasses_606_0_25(), G__RootanaDataClasses_606_0_26(), G__RootanaDataClasses_606_0_27(), G__RootanaDataClasses_606_0_3(), G__RootanaDataClasses_606_0_4(), G__RootanaDataClasses_606_0_5(), G__RootanaDataClasses_606_0_6(), G__RootanaDataClasses_606_0_7(), G__RootanaDataClasses_606_0_8(), G__RootanaDataClasses_606_0_9(), G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR, G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLreverse_iterator, G__RootanaDataClassesLN_pairlEmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiteratorcOboolgR, and G__RootanaDataClassesLN_string.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    G__memfunc_setup("map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >",9010,G__RootanaDataClasses_606_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >",9010,G__RootanaDataClasses_606_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator' - 0 - first u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >",9010,G__RootanaDataClasses_606_0_3, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator' - 0 - first u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >",9010,G__RootanaDataClasses_606_0_4, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR), -1, 0, 1, 1, 1, 0, "u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__RootanaDataClasses_606_0_5, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR), -1, 1, 1, 1, 1, 0, "u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("begin",517,G__RootanaDataClasses_606_0_6, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("end",311,G__RootanaDataClasses_606_0_7, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rbegin",631,G__RootanaDataClasses_606_0_8, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rend",425,G__RootanaDataClasses_606_0_9, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("empty",559,G__RootanaDataClasses_606_0_10, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("size",443,G__RootanaDataClasses_606_0_11, 107, -1, G__defined_typename("map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("max_size",864,G__RootanaDataClasses_606_0_12, 107, -1, G__defined_typename("map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__RootanaDataClasses_606_0_13, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), -1, 1, 1, 1, 1, 0, "i 'IDs::Detector_t' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_606_0_14, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiteratorcOboolgR), -1, 0, 1, 1, 1, 0, "u 'pair<IDs::Detector_t,string>' 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_606_0_15, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0,
 "u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator' - 0 - position u 'pair<IDs::Detector_t,string>' 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_606_0_16, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator' - 0 - first u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_606_0_17, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator' - 0 - first u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_606_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_606_0_19, 107, -1, G__defined_typename("map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::size_type"), 0, 1, 1, 1, 0, "i 'IDs::Detector_t' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_606_0_20, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator' - 0 - first u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("swap",443,G__RootanaDataClasses_606_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >' - 1 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("clear",519,G__RootanaDataClasses_606_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("find",417,G__RootanaDataClasses_606_0_23, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i 'IDs::Detector_t' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("count",553,G__RootanaDataClasses_606_0_24, 107, -1, G__defined_typename("map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::size_type"), 0, 1, 1, 1, 8, "i 'IDs::Detector_t' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("lower_bound",1184,G__RootanaDataClasses_606_0_25, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i 'IDs::Detector_t' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("upper_bound",1187,G__RootanaDataClasses_606_0_26, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i 'IDs::Detector_t' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >", 9136, G__RootanaDataClasses_606_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR (void) static
Definition at line 5982 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_597_0_1(), G__RootanaDataClasses_597_0_10(), G__RootanaDataClasses_597_0_11(), G__RootanaDataClasses_597_0_12(), G__RootanaDataClasses_597_0_13(), G__RootanaDataClasses_597_0_14(), G__RootanaDataClasses_597_0_15(), G__RootanaDataClasses_597_0_16(), G__RootanaDataClasses_597_0_17(), G__RootanaDataClasses_597_0_18(), G__RootanaDataClasses_597_0_19(), G__RootanaDataClasses_597_0_2(), G__RootanaDataClasses_597_0_20(), G__RootanaDataClasses_597_0_21(), G__RootanaDataClasses_597_0_22(), G__RootanaDataClasses_597_0_23(), G__RootanaDataClasses_597_0_24(), G__RootanaDataClasses_597_0_25(), G__RootanaDataClasses_597_0_26(), G__RootanaDataClasses_597_0_27(), G__RootanaDataClasses_597_0_3(), G__RootanaDataClasses_597_0_4(), G__RootanaDataClasses_597_0_5(), G__RootanaDataClasses_597_0_6(), G__RootanaDataClasses_597_0_7(), G__RootanaDataClasses_597_0_8(), G__RootanaDataClasses_597_0_9(), G__RootanaDataClassesLN_IDscLcLDetector_t, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLreverse_iterator, and G__RootanaDataClassesLN_pairlEmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiteratorcOboolgR.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    G__memfunc_setup("map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >",8264,G__RootanaDataClasses_597_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >",8264,G__RootanaDataClasses_597_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator' - 0 - first u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >",8264,G__RootanaDataClasses_597_0_3, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator' - 0 - first u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >",8264,G__RootanaDataClasses_597_0_4, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR), -1, 0, 1, 1, 1, 0, "u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__RootanaDataClasses_597_0_5, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR), -1, 1, 1, 1, 1, 0, "u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("begin",517,G__RootanaDataClasses_597_0_6, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("end",311,G__RootanaDataClasses_597_0_7, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rbegin",631,G__RootanaDataClasses_597_0_8, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rend",425,G__RootanaDataClasses_597_0_9, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("empty",559,G__RootanaDataClasses_597_0_10, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("size",443,G__RootanaDataClasses_597_0_11, 107, -1, G__defined_typename("map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("max_size",864,G__RootanaDataClasses_597_0_12, 107, -1, G__defined_typename("map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__RootanaDataClasses_597_0_13, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLDetector_t), -1, 1, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_597_0_14, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiteratorcOboolgR), -1, 0, 1, 1, 1, 0, "u 'pair<string,IDs::Detector_t>' 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_597_0_15, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0,
 "u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator' - 0 - position u 'pair<string,IDs::Detector_t>' 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_597_0_16, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator' - 0 - first u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_597_0_17, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator' - 0 - first u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_597_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_597_0_19, 107, -1, G__defined_typename("map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::size_type"), 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_597_0_20, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator' - 0 - first u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("swap",443,G__RootanaDataClasses_597_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >' - 1 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("clear",519,G__RootanaDataClasses_597_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("find",417,G__RootanaDataClasses_597_0_23, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("count",553,G__RootanaDataClasses_597_0_24, 107, -1, G__defined_typename("map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::size_type"), 0, 1, 1, 1, 8, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("lower_bound",1184,G__RootanaDataClasses_597_0_25, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("upper_bound",1187,G__RootanaDataClasses_597_0_26, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >", 8390, G__RootanaDataClasses_597_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR (void) static
Definition at line 5787 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_446_0_1(), G__RootanaDataClasses_446_0_10(), G__RootanaDataClasses_446_0_11(), G__RootanaDataClasses_446_0_12(), G__RootanaDataClasses_446_0_13(), G__RootanaDataClasses_446_0_14(), G__RootanaDataClasses_446_0_15(), G__RootanaDataClasses_446_0_16(), G__RootanaDataClasses_446_0_17(), G__RootanaDataClasses_446_0_18(), G__RootanaDataClasses_446_0_19(), G__RootanaDataClasses_446_0_2(), G__RootanaDataClasses_446_0_20(), G__RootanaDataClasses_446_0_21(), G__RootanaDataClasses_446_0_22(), G__RootanaDataClasses_446_0_23(), G__RootanaDataClasses_446_0_24(), G__RootanaDataClasses_446_0_25(), G__RootanaDataClasses_446_0_26(), G__RootanaDataClasses_446_0_27(), G__RootanaDataClasses_446_0_3(), G__RootanaDataClasses_446_0_4(), G__RootanaDataClasses_446_0_5(), G__RootanaDataClasses_446_0_6(), G__RootanaDataClasses_446_0_7(), G__RootanaDataClasses_446_0_8(), G__RootanaDataClasses_446_0_9(), G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator, G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator, G__RootanaDataClassesLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR, and G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    G__memfunc_setup("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >",15214,G__RootanaDataClasses_446_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >",15214,G__RootanaDataClasses_446_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - first u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >",15214,G__RootanaDataClasses_446_0_3, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator' - 0 - first u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >",15214,G__RootanaDataClasses_446_0_4, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR), -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__RootanaDataClasses_446_0_5, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR), -1, 1, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("begin",517,G__RootanaDataClasses_446_0_6, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("end",311,G__RootanaDataClasses_446_0_7, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rbegin",631,G__RootanaDataClasses_446_0_8, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rend",425,G__RootanaDataClasses_446_0_9, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("empty",559,G__RootanaDataClasses_446_0_10, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("size",443,G__RootanaDataClasses_446_0_11, 107, -1, G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("max_size",864,G__RootanaDataClasses_446_0_12, 107, -1, G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__RootanaDataClasses_446_0_13, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 1, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_446_0_14, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR), -1, 0, 1, 1, 1, 0, "u 'pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >' 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_446_0_15, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - position u 'pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >' 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type' 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_446_0_16, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - first u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_446_0_17, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator' - 0 - first u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_446_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_446_0_19, 107, -1, G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::size_type"), 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_446_0_20, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - first u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("swap",443,G__RootanaDataClasses_446_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >' - 1 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("clear",519,G__RootanaDataClasses_446_0_22, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("find",417,G__RootanaDataClasses_446_0_23, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("count",553,G__RootanaDataClasses_446_0_24, 107, -1, G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::size_type"), 0, 1, 1, 1, 8, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("lower_bound",1184,G__RootanaDataClasses_446_0_25, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("upper_bound",1187,G__RootanaDataClasses_446_0_26, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >", 15340, G__RootanaDataClasses_446_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void) static
Definition at line 5842 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_448_0_1(), G__RootanaDataClasses_448_0_10(), G__RootanaDataClasses_448_0_11(), G__RootanaDataClasses_448_0_12(), G__RootanaDataClasses_448_0_2(), G__RootanaDataClasses_448_0_3(), G__RootanaDataClasses_448_0_4(), G__RootanaDataClasses_448_0_5(), G__RootanaDataClasses_448_0_6(), G__RootanaDataClasses_448_0_7(), G__RootanaDataClasses_448_0_8(), G__RootanaDataClasses_448_0_9(), G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator, and G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator));
    G__memfunc_setup("iterator",874,G__RootanaDataClasses_448_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("iterator",874,G__RootanaDataClasses_448_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__RootanaDataClasses_448_0_3, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 1, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator*",918,G__RootanaDataClasses_448_0_4, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type"), 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator->",983,G__RootanaDataClasses_448_0_5, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), G__defined_typename("map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::value_type"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__RootanaDataClasses_448_0_6, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__RootanaDataClasses_448_0_7, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - a", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__RootanaDataClasses_448_0_8, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__RootanaDataClasses_448_0_9, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - a", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator==",998,G__RootanaDataClasses_448_0_10, 103, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator!=",970,G__RootanaDataClasses_448_0_11, 103, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~iterator", 1000, G__RootanaDataClasses_448_0_12, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void) static
Definition at line 5827 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_447_0_1(), G__RootanaDataClasses_447_0_2(), G__RootanaDataClasses_447_0_4(), G__RootanaDataClasses_447_0_5(), and G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
    G__memfunc_setup("pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >",6157,G__RootanaDataClasses_447_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >",6157,G__RootanaDataClasses_447_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'string' - 11 - a u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >' - 11 - b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), -1, 1, 1, 1, 4, 0, "u 'pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic copy constructor
    G__memfunc_setup("pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >", 6157, G__RootanaDataClasses_447_0_4, (int) ('i'),
 G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR), -1, 0, 1, 1, 1, 0, "u 'pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >", 6283, G__RootanaDataClasses_447_0_5, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncTAnalysedPulse (void) static
Definition at line 5674 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_430_0_1(), G__RootanaDataClasses_430_0_10(), G__RootanaDataClasses_430_0_11(), G__RootanaDataClasses_430_0_12(), G__RootanaDataClasses_430_0_13(), G__RootanaDataClasses_430_0_14(), G__RootanaDataClasses_430_0_18(), G__RootanaDataClasses_430_0_19(), G__RootanaDataClasses_430_0_2(), G__RootanaDataClasses_430_0_20(), G__RootanaDataClasses_430_0_21(), G__RootanaDataClasses_430_0_22(), G__RootanaDataClasses_430_0_23(), G__RootanaDataClasses_430_0_24(), G__RootanaDataClasses_430_0_25(), G__RootanaDataClasses_430_0_3(), G__RootanaDataClasses_430_0_4(), G__RootanaDataClasses_430_0_5(), G__RootanaDataClasses_430_0_6(), G__RootanaDataClasses_430_0_7(), G__RootanaDataClasses_430_0_8(), G__RootanaDataClasses_430_0_9(), G__RootanaDataClassesLN_string, G__RootanaDataClassesLN_TAnalysedPulse, and G__RootanaDataClassesLN_TClass.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* TAnalysedPulse */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse));
    G__memfunc_setup("TAnalysedPulse",1422,G__RootanaDataClasses_430_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("TAnalysedPulse",1422,G__RootanaDataClasses_430_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), -1, 0, 5, 1, 1, 0,
 "d - - 0 - amplitude d - - 0 - time "
 "d - - 0 - integral d - - 0 - energy "
 "u 'string' - 0 - det_name", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("TAnalysedPulse",1422,G__RootanaDataClasses_430_0_3, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), -1, 0, 6, 1, 1, 0,
 "d - - 0 - amplitude d - - 0 - time "
 "d - - 0 - integral d - - 0 - energy "
 "u 'string' - 0 - det_name u 'string' - 0 - algo", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Reset",515,G__RootanaDataClasses_430_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' o", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetAmplitude",1221,G__RootanaDataClasses_430_0_5, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetTime",687,G__RootanaDataClasses_430_0_6, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetIntegral",1110,G__RootanaDataClasses_430_0_7, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetEnergy",906,G__RootanaDataClasses_430_0_8, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetDetName",958,G__RootanaDataClasses_430_0_9, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetAlgorithmStamp",1740,G__RootanaDataClasses_430_0_10, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__RootanaDataClasses_430_0_11, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TAnalysedPulse::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__RootanaDataClasses_430_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TAnalysedPulse::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__RootanaDataClasses_430_0_13, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TAnalysedPulse::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__RootanaDataClasses_430_0_14, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TAnalysedPulse::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__RootanaDataClasses_430_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__RootanaDataClasses_430_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TAnalysedPulse::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__RootanaDataClasses_430_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TAnalysedPulse::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__RootanaDataClasses_430_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TAnalysedPulse::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__RootanaDataClasses_430_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TAnalysedPulse::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("TAnalysedPulse", 1422, G__RootanaDataClasses_430_0_23, (int) ('i'), G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), -1, 0, 1, 1, 1, 0, "u 'TAnalysedPulse' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TAnalysedPulse", 1548, G__RootanaDataClasses_430_0_24, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__RootanaDataClasses_430_0_25, (int) ('u'), G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), -1, 1, 1, 1, 1, 0, "u 'TAnalysedPulse' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncTAnalysedPulseMapWrapper (void) static
Definition at line 5951 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_594_0_1(), G__RootanaDataClasses_594_0_10(), G__RootanaDataClasses_594_0_14(), G__RootanaDataClasses_594_0_15(), G__RootanaDataClasses_594_0_16(), G__RootanaDataClasses_594_0_17(), G__RootanaDataClasses_594_0_18(), G__RootanaDataClasses_594_0_19(), G__RootanaDataClasses_594_0_2(), G__RootanaDataClasses_594_0_20(), G__RootanaDataClasses_594_0_21(), G__RootanaDataClasses_594_0_3(), G__RootanaDataClasses_594_0_4(), G__RootanaDataClasses_594_0_5(), G__RootanaDataClasses_594_0_6(), G__RootanaDataClasses_594_0_7(), G__RootanaDataClasses_594_0_8(), G__RootanaDataClasses_594_0_9(), G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_TAnalysedPulseMapWrapper, and G__RootanaDataClassesLN_TClass.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* TAnalysedPulseMapWrapper */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper));
    G__memfunc_setup("TAnalysedPulseMapWrapper",2445,G__RootanaDataClasses_594_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("TAnalysedPulseMapWrapper",2445,G__RootanaDataClasses_594_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper), -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >' 'StringAnalPulseMap' 0 - aMap", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("ShowInfo",813,G__RootanaDataClasses_594_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Reset",515,G__RootanaDataClasses_594_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetMap",574,G__RootanaDataClasses_594_0_5, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR), G__defined_typename("StringAnalPulseMap"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetMap",586,G__RootanaDataClasses_594_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "u 'map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >' 'StringAnalPulseMap' 0 - aMap", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__RootanaDataClasses_594_0_7, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TAnalysedPulseMapWrapper::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__RootanaDataClasses_594_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TAnalysedPulseMapWrapper::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__RootanaDataClasses_594_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TAnalysedPulseMapWrapper::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__RootanaDataClasses_594_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TAnalysedPulseMapWrapper::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__RootanaDataClasses_594_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__RootanaDataClasses_594_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TAnalysedPulseMapWrapper::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__RootanaDataClasses_594_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TAnalysedPulseMapWrapper::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__RootanaDataClasses_594_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TAnalysedPulseMapWrapper::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__RootanaDataClasses_594_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TAnalysedPulseMapWrapper::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("TAnalysedPulseMapWrapper", 2445, G__RootanaDataClasses_594_0_19, (int) ('i'),
 G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper), -1, 0, 1, 1, 1, 0, "u 'TAnalysedPulseMapWrapper' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TAnalysedPulseMapWrapper", 2571, G__RootanaDataClasses_594_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__RootanaDataClasses_594_0_21, (int) ('u'), G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper), -1, 1, 1, 1, 1, 0, "u 'TAnalysedPulseMapWrapper' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncTDetectorPulse (void) static
Definition at line 5861 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_451_0_1(), G__RootanaDataClasses_451_0_10(), G__RootanaDataClasses_451_0_11(), G__RootanaDataClasses_451_0_12(), G__RootanaDataClasses_451_0_13(), G__RootanaDataClasses_451_0_14(), G__RootanaDataClasses_451_0_15(), G__RootanaDataClasses_451_0_16(), G__RootanaDataClasses_451_0_17(), G__RootanaDataClasses_451_0_18(), G__RootanaDataClasses_451_0_19(), G__RootanaDataClasses_451_0_2(), G__RootanaDataClasses_451_0_20(), G__RootanaDataClasses_451_0_24(), G__RootanaDataClasses_451_0_25(), G__RootanaDataClasses_451_0_26(), G__RootanaDataClasses_451_0_27(), G__RootanaDataClasses_451_0_28(), G__RootanaDataClasses_451_0_29(), G__RootanaDataClasses_451_0_3(), G__RootanaDataClasses_451_0_30(), G__RootanaDataClasses_451_0_31(), G__RootanaDataClasses_451_0_4(), G__RootanaDataClasses_451_0_5(), G__RootanaDataClasses_451_0_6(), G__RootanaDataClasses_451_0_7(), G__RootanaDataClasses_451_0_8(), G__RootanaDataClasses_451_0_9(), G__RootanaDataClassesLN_string, G__RootanaDataClassesLN_TClass, and G__RootanaDataClassesLN_TDetectorPulse.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* TDetectorPulse */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_TDetectorPulse));
    G__memfunc_setup("TDetectorPulse",1431,G__RootanaDataClasses_451_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_TDetectorPulse), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("TDetectorPulse",1431,G__RootanaDataClasses_451_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_TDetectorPulse), -1, 0, 3, 1, 1, 0,
 "U 'TAnalysedPulse' - 0 - fast_pulse U 'TAnalysedPulse' - 0 - slow_pulse "
 "u 'string' - 0 - det_name", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Reset",515,G__RootanaDataClasses_451_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' o", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetFastPulseAmplitude",2140,G__RootanaDataClasses_451_0_4, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetSlowPulseAmplitude",2163,G__RootanaDataClasses_451_0_5, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetFastPulseTime",1606,G__RootanaDataClasses_451_0_6, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetSlowPulseTime",1629,G__RootanaDataClasses_451_0_7, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetFastPulseIntegral",2029,G__RootanaDataClasses_451_0_8, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetSlowPulseIntegral",2052,G__RootanaDataClasses_451_0_9, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetTime",687,G__RootanaDataClasses_451_0_10, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetAmplitude",1221,G__RootanaDataClasses_451_0_11, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("GetDetName",958,G__RootanaDataClasses_451_0_12, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("IsPileUpSafe",1162,G__RootanaDataClasses_451_0_13, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetPileUpSafe",1274,G__RootanaDataClasses_451_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 11 'true' val", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("WasPileUpChecked",1569,G__RootanaDataClasses_451_0_15, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SetPileUpChecked",1570,G__RootanaDataClasses_451_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 11 'true' val", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__RootanaDataClasses_451_0_17, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TDetectorPulse::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__RootanaDataClasses_451_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDetectorPulse::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__RootanaDataClasses_451_0_19, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TDetectorPulse::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__RootanaDataClasses_451_0_20, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TDetectorPulse::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__RootanaDataClasses_451_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__RootanaDataClasses_451_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDetectorPulse::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__RootanaDataClasses_451_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDetectorPulse::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__RootanaDataClasses_451_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDetectorPulse::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__RootanaDataClasses_451_0_28, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDetectorPulse::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("TDetectorPulse", 1431, G__RootanaDataClasses_451_0_29, (int) ('i'), G__get_linked_tagnum(&G__RootanaDataClassesLN_TDetectorPulse), -1, 0, 1, 1, 1, 0, "u 'TDetectorPulse' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~TDetectorPulse", 1557, G__RootanaDataClasses_451_0_30, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__RootanaDataClasses_451_0_31, (int) ('u'), G__get_linked_tagnum(&G__RootanaDataClassesLN_TDetectorPulse), -1, 1, 1, 1, 1, 0, "u 'TDetectorPulse' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR (void) static
Definition at line 5903 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_591_0_1(), G__RootanaDataClasses_591_0_10(), G__RootanaDataClasses_591_0_11(), G__RootanaDataClasses_591_0_12(), G__RootanaDataClasses_591_0_13(), G__RootanaDataClasses_591_0_14(), G__RootanaDataClasses_591_0_15(), G__RootanaDataClasses_591_0_16(), G__RootanaDataClasses_591_0_17(), G__RootanaDataClasses_591_0_18(), G__RootanaDataClasses_591_0_19(), G__RootanaDataClasses_591_0_2(), G__RootanaDataClasses_591_0_20(), G__RootanaDataClasses_591_0_21(), G__RootanaDataClasses_591_0_22(), G__RootanaDataClasses_591_0_23(), G__RootanaDataClasses_591_0_24(), G__RootanaDataClasses_591_0_25(), G__RootanaDataClasses_591_0_26(), G__RootanaDataClasses_591_0_27(), G__RootanaDataClasses_591_0_28(), G__RootanaDataClasses_591_0_29(), G__RootanaDataClasses_591_0_3(), G__RootanaDataClasses_591_0_30(), G__RootanaDataClasses_591_0_31(), G__RootanaDataClasses_591_0_32(), G__RootanaDataClasses_591_0_4(), G__RootanaDataClasses_591_0_5(), G__RootanaDataClasses_591_0_6(), G__RootanaDataClasses_591_0_7(), G__RootanaDataClasses_591_0_8(), G__RootanaDataClasses_591_0_9(), G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_string, G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR, and G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* vector<string,allocator<string> > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    G__memfunc_setup("at",213,G__RootanaDataClasses_591_0_1, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), G__defined_typename("vector<string,allocator<string> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<string,allocator<string> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("at",213,G__RootanaDataClasses_591_0_2, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), G__defined_typename("vector<string,allocator<string> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<string,allocator<string> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("begin",517,G__RootanaDataClasses_591_0_3, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("end",311,G__RootanaDataClasses_591_0_4, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rbegin",631,G__RootanaDataClasses_591_0_5, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR), G__defined_typename("vector<string,allocator<string> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rend",425,G__RootanaDataClasses_591_0_6, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR), G__defined_typename("vector<string,allocator<string> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("size",443,G__RootanaDataClasses_591_0_7, 107, -1, G__defined_typename("vector<string,allocator<string> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("max_size",864,G__RootanaDataClasses_591_0_8, 107, -1, G__defined_typename("vector<string,allocator<string> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("resize",658,G__RootanaDataClasses_591_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<string,allocator<string> >::size_type' 0 - sz", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("resize",658,G__RootanaDataClasses_591_0_10, 121, -1, -1, 0, 2, 1, 1, 0,
 "k - 'vector<string,allocator<string> >::size_type' 0 - sz u 'string' - 0 - c", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("capacity",846,G__RootanaDataClasses_591_0_11, 107, -1, G__defined_typename("vector<string,allocator<string> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("empty",559,G__RootanaDataClasses_591_0_12, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__RootanaDataClasses_591_0_13, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), G__defined_typename("vector<string,allocator<string> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<string,allocator<string> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__RootanaDataClasses_591_0_14, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), G__defined_typename("vector<string,allocator<string> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<string,allocator<string> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<string,allocator<string> >",3266,G__RootanaDataClasses_591_0_15, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<string,allocator<string> >",3266,G__RootanaDataClasses_591_0_16, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR), -1, 0, 2, 1, 1, 0,
 "k - 'vector<string,allocator<string> >::size_type' 0 - n u 'string' - 11 'string()' value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<string,allocator<string> >",3266,G__RootanaDataClasses_591_0_17, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR), -1, 0, 1, 1, 1, 0, "u 'vector<string,allocator<string> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<string,allocator<string> >",3266,G__RootanaDataClasses_591_0_18, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'vector<string,allocator<string> >::iterator' 'vector<string,allocator<string> >::const_iterator' 10 - first u 'vector<string,allocator<string> >::iterator' 'vector<string,allocator<string> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__RootanaDataClasses_591_0_19, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR), -1, 1, 1, 1, 1, 0, "u 'vector<string,allocator<string> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("reserve",764,G__RootanaDataClasses_591_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<string,allocator<string> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("front",553,G__RootanaDataClasses_591_0_21, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("back",401,G__RootanaDataClasses_591_0_22, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_string), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("push_back",944,G__RootanaDataClasses_591_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("swap",443,G__RootanaDataClasses_591_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<string,allocator<string> >' - 1 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_591_0_25, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0,
 "u 'vector<string,allocator<string> >::iterator' - 0 - position u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_591_0_26, 121, -1, -1, 0, 3, 1, 1, 0,
 "u 'vector<string,allocator<string> >::iterator' - 0 - position u 'vector<string,allocator<string> >::iterator' 'vector<string,allocator<string> >::const_iterator' 10 - first "
 "u 'vector<string,allocator<string> >::iterator' 'vector<string,allocator<string> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_591_0_27, 121, -1, -1, 0, 3, 1, 1, 0,
 "u 'vector<string,allocator<string> >::iterator' - 0 - position k - 'vector<string,allocator<string> >::size_type' 0 - n "
 "u 'string' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("pop_back",831,G__RootanaDataClasses_591_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_591_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<string,allocator<string> >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_591_0_30, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'vector<string,allocator<string> >::iterator' - 0 - first u 'vector<string,allocator<string> >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("clear",519,G__RootanaDataClasses_591_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~vector<string,allocator<string> >", 3392, G__RootanaDataClasses_591_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR (void) static
Definition at line 5714 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_432_0_1(), G__RootanaDataClasses_432_0_10(), G__RootanaDataClasses_432_0_11(), G__RootanaDataClasses_432_0_12(), G__RootanaDataClasses_432_0_13(), G__RootanaDataClasses_432_0_14(), G__RootanaDataClasses_432_0_15(), G__RootanaDataClasses_432_0_16(), G__RootanaDataClasses_432_0_17(), G__RootanaDataClasses_432_0_18(), G__RootanaDataClasses_432_0_19(), G__RootanaDataClasses_432_0_2(), G__RootanaDataClasses_432_0_20(), G__RootanaDataClasses_432_0_21(), G__RootanaDataClasses_432_0_22(), G__RootanaDataClasses_432_0_23(), G__RootanaDataClasses_432_0_24(), G__RootanaDataClasses_432_0_25(), G__RootanaDataClasses_432_0_26(), G__RootanaDataClasses_432_0_27(), G__RootanaDataClasses_432_0_28(), G__RootanaDataClasses_432_0_29(), G__RootanaDataClasses_432_0_3(), G__RootanaDataClasses_432_0_30(), G__RootanaDataClasses_432_0_31(), G__RootanaDataClasses_432_0_32(), G__RootanaDataClasses_432_0_4(), G__RootanaDataClasses_432_0_5(), G__RootanaDataClasses_432_0_6(), G__RootanaDataClasses_432_0_7(), G__RootanaDataClasses_432_0_8(), G__RootanaDataClasses_432_0_9(), G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR, G__RootanaDataClassesLN_TAnalysedPulse, G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR, and G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    G__memfunc_setup("at",213,G__RootanaDataClasses_432_0_1, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("at",213,G__RootanaDataClasses_432_0_2, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("begin",517,G__RootanaDataClasses_432_0_3, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("end",311,G__RootanaDataClasses_432_0_4, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rbegin",631,G__RootanaDataClasses_432_0_5, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rend",425,G__RootanaDataClasses_432_0_6, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("size",443,G__RootanaDataClasses_432_0_7, 107, -1, G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("max_size",864,G__RootanaDataClasses_432_0_8, 107, -1, G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("resize",658,G__RootanaDataClasses_432_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - sz", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("resize",658,G__RootanaDataClasses_432_0_10, 121, -1, -1, 0, 2, 1, 1, 0,
 "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - sz U 'TAnalysedPulse' - 0 - c", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("capacity",846,G__RootanaDataClasses_432_0_11, 107, -1, G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("empty",559,G__RootanaDataClasses_432_0_12, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__RootanaDataClasses_432_0_13, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__RootanaDataClasses_432_0_14, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >",4868,G__RootanaDataClasses_432_0_15, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >",4868,G__RootanaDataClasses_432_0_16, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 0, 2, 1, 1, 0,
 "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n U 'TAnalysedPulse' - 41 '(TAnalysedPulse*)()' value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >",4868,G__RootanaDataClasses_432_0_17, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 0, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >",4868,G__RootanaDataClasses_432_0_18, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 0, 2, 1, 1, 0,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator' 10 - first u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__RootanaDataClasses_432_0_19, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR), -1, 1, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("reserve",764,G__RootanaDataClasses_432_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("front",553,G__RootanaDataClasses_432_0_21, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("back",401,G__RootanaDataClasses_432_0_22, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("push_back",944,G__RootanaDataClasses_432_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TAnalysedPulse' - 41 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("swap",443,G__RootanaDataClasses_432_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >' - 1 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_432_0_25, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - position U 'TAnalysedPulse' - 41 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_432_0_26, 121, -1, -1, 0, 3, 1, 1, 0,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - position u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator' 10 - first "
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__RootanaDataClasses_432_0_27, 121, -1, -1, 0, 3, 1, 1, 0,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - position k - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::size_type' 0 - n "
 "U 'TAnalysedPulse' - 41 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("pop_back",831,G__RootanaDataClasses_432_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_432_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__RootanaDataClasses_432_0_30, 121, -1, -1, 0, 2, 1, 1, 0,
 "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - first u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("clear",519,G__RootanaDataClasses_432_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >", 4994, G__RootanaDataClasses_432_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void) static
Definition at line 5762 of file RootanaDataClasses.cpp.
References G__RootanaDataClasses_433_0_1(), G__RootanaDataClasses_433_0_10(), G__RootanaDataClasses_433_0_11(), G__RootanaDataClasses_433_0_12(), G__RootanaDataClasses_433_0_13(), G__RootanaDataClasses_433_0_14(), G__RootanaDataClasses_433_0_15(), G__RootanaDataClasses_433_0_16(), G__RootanaDataClasses_433_0_17(), G__RootanaDataClasses_433_0_2(), G__RootanaDataClasses_433_0_3(), G__RootanaDataClasses_433_0_4(), G__RootanaDataClasses_433_0_5(), G__RootanaDataClasses_433_0_6(), G__RootanaDataClasses_433_0_7(), G__RootanaDataClasses_433_0_8(), G__RootanaDataClasses_433_0_9(), G__RootanaDataClassesLN_TAnalysedPulse, and G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    /* vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    G__memfunc_setup("iterator",874,G__RootanaDataClasses_433_0_1, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("iterator",874,G__RootanaDataClasses_433_0_2, 105, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 5, 1, 0, "U 'TAnalysedPulse' 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer' 11 - __i", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator*",918,G__RootanaDataClasses_433_0_3, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::reference"), 1, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator->",983,G__RootanaDataClasses_433_0_4, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__RootanaDataClasses_433_0_5, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator++",962,G__RootanaDataClasses_433_0_6, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__RootanaDataClasses_433_0_7, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator--",966,G__RootanaDataClasses_433_0_8, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__RootanaDataClasses_433_0_9, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::reference"), 1, 1, 1, 1, 8, "l - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator+=",980,G__RootanaDataClasses_433_0_10, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 1, 1, 1, 1, 0, "l - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator+",919,G__RootanaDataClasses_433_0_11, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 8, "l - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator-=",982,G__RootanaDataClasses_433_0_12, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 1, 1, 1, 1, 0, "l - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator-",921,G__RootanaDataClasses_433_0_13, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 8, "l - 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::difference_type' 11 - __n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("base",411,G__RootanaDataClasses_433_0_14, 85, G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse), G__defined_typename("vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator::pointer"), 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__RootanaDataClasses_433_0_15, 117, G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 11 - x", (char*)NULL, (void*) NULL, 0);
    // automatic copy constructor
    G__memfunc_setup("iterator", 874, G__RootanaDataClasses_433_0_16, (int) ('i'), G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator), -1, 0, 1, 1, 1, 0, "u 'vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~iterator", 1000, G__RootanaDataClasses_433_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
 }
static void G__setup_memvarIDscLcLchannel (void) static
Definition at line 5393 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLchannel, G__RootanaDataClassesLN_IDscLcLDetector_t, G__RootanaDataClassesLN_IDscLcLSlowFast_t, and G__RootanaDataClassesLN_TClass.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel));
    { IDs::channel *p; p=(IDs::channel*)0x1000; if (p) { }
    G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
    G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLDetector_t),-1,-1,4,"fDetector=",0,(char*)NULL);
    G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLSlowFast_t),-1,-1,4,"fSlowFast=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarIDscLcLgenerator (void) static
Definition at line 5406 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLgenerator, G__RootanaDataClassesLN_string, and G__RootanaDataClassesLN_TClass.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator));
    { IDs::generator *p; p=(IDs::generator*)0x1000; if (p) { }
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),G__defined_typename("Generator_t"),-1,4,"fType=",0,(char*)NULL);
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),G__defined_typename("Config_t"),-1,4,"fConfig=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarIDscLcLsource (void) static
Definition at line 5418 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_IDscLcLchannel, G__RootanaDataClassesLN_IDscLcLgenerator, G__RootanaDataClassesLN_IDscLcLsource, and G__RootanaDataClassesLN_TClass.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLsource));
    { IDs::source *p; p=(IDs::source*)0x1000; if (p) { }
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLchannel),-1,-1,4,"fChannel=",0,(char*)NULL);
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_IDscLcLgenerator),-1,-1,4,"fGenerator=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR (void) static
Definition at line 5537 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR));
    { map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > > *p; p=(map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR (void) static
Definition at line 5528 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR));
    { map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > > *p; p=(map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR (void) static
Definition at line 5464 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR));
    { map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > > *p; p=(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator (void) static
Definition at line 5484 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator));
    { map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator *p; p=(map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR (void) static
Definition at line 5473 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR, G__RootanaDataClassesLN_string, and G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR));
    { pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > *p; p=(pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >*)0x1000; if (p) { }
    G__memvar_setup((void*)((long)(&p->first)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),-1,-1,1,"first=",0,(char*)NULL);
    G__memvar_setup((void*)((long)(&p->second)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR),-1,-1,1,"second=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarTAnalysedPulse (void) static
Definition at line 5430 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_string, G__RootanaDataClassesLN_TAnalysedPulse, and G__RootanaDataClassesLN_TClass.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse));
    { TAnalysedPulse *p; p=(TAnalysedPulse*)0x1000; if (p) { }
    G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fAmplitude=",0,(char*)NULL);
    G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fTime=",0,(char*)NULL);
    G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fIntegral=",0,(char*)NULL);
    G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fEnergy=",0,(char*)NULL);
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),-1,-1,4,"fDetName=",0,(char*)NULL);
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),-1,-1,4,"fAlgo=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarTAnalysedPulseMapWrapper (void) static
Definition at line 5517 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR, G__RootanaDataClassesLN_TAnalysedPulseMapWrapper, and G__RootanaDataClassesLN_TClass.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulseMapWrapper));
    { TAnalysedPulseMapWrapper *p; p=(TAnalysedPulseMapWrapper*)0x1000; if (p) { }
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR),G__defined_typename("StringAnalPulseMap"),-1,4,"fChn2PulseMap=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarTDetectorPulse (void) static
Definition at line 5493 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_string, G__RootanaDataClassesLN_TAnalysedPulse, G__RootanaDataClassesLN_TClass, and G__RootanaDataClassesLN_TDetectorPulse.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_TDetectorPulse));
    { TDetectorPulse *p; p=(TDetectorPulse*)0x1000; if (p) { }
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),-1,-1,4,"fFastPulse=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_TAnalysedPulse),-1,-1,4,"fSlowPulse=",0,(char*)NULL);
    G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_string),-1,-1,4,"fDetName=",0,(char*)NULL);
    G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fCheckedForPileUp=",0,(char*)NULL);
    G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fPileUpSafe=",0,(char*)NULL);
    G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__RootanaDataClassesLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarvectorlEstringcOallocatorlEstringgRsPgR (void) static
Definition at line 5508 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR));
    { vector<string,allocator<string> > *p; p=(vector<string,allocator<string> >*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR (void) static
Definition at line 5446 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR));
    { vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > *p; p=(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
static void G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator (void) static
Definition at line 5455 of file RootanaDataClasses.cpp.
References G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator.
Referenced by G__cpp_setup_tagtableRootanaDataClasses().
{
    G__tag_memvar_setup(G__get_linked_tagnum(&G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator));
    { vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator *p; p=(vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
 }
Variable Documentation
G__cpp_setup_initRootanaDataClasses G__cpp_setup_initializerRootanaDataClasses
Definition at line 6417 of file RootanaDataClasses.cpp.
G__linked_taginfo G__RootanaDataClassesLN_allocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgR = { "allocator<pair<const IDs::Detector_t,string> >" , 99 , -1 }
Definition at line 6256 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgR = { "allocator<pair<const string,IDs::Detector_t> >" , 99 , -1 }
Definition at line 6249 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_allocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgR = { "allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > >" , 99 , -1 }
Definition at line 6228 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_IDs = { "IDs" , 110 , -1 }
Definition at line 6213 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_IDscLcLchannel = { "IDs::channel" , 99 , -1 }
Definition at line 6214 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__RootanaDataClasses_404_0_1(), G__RootanaDataClasses_404_0_2(), G__RootanaDataClasses_404_0_26(), G__setup_memfuncIDscLcLchannel(), G__setup_memfuncIDscLcLsource(), G__setup_memvarIDscLcLchannel(), and G__setup_memvarIDscLcLsource().
G__linked_taginfo G__RootanaDataClassesLN_IDscLcLDetector_t = { "IDs::Detector_t" , 101 , -1 }
Definition at line 6215 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__setup_memfuncIDscLcLchannel(), G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR(), and G__setup_memvarIDscLcLchannel().
G__linked_taginfo G__RootanaDataClassesLN_IDscLcLgenerator = { "IDs::generator" , 99 , -1 }
Definition at line 6217 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_inheritanceRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__RootanaDataClasses_407_0_1(), G__RootanaDataClasses_407_0_2(), G__RootanaDataClasses_407_0_22(), G__setup_memfuncIDscLcLgenerator(), G__setup_memfuncIDscLcLsource(), G__setup_memvarIDscLcLgenerator(), and G__setup_memvarIDscLcLsource().
G__linked_taginfo G__RootanaDataClassesLN_IDscLcLSlowFast_t = { "IDs::SlowFast_t" , 101 , -1 }
Definition at line 6216 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__setup_memfuncIDscLcLchannel(), and G__setup_memvarIDscLcLchannel().
G__linked_taginfo G__RootanaDataClassesLN_IDscLcLsource = { "IDs::source" , 99 , -1 }
Definition at line 6218 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_inheritanceRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__RootanaDataClasses_408_0_1(), G__RootanaDataClasses_408_0_2(), G__RootanaDataClasses_408_0_27(), G__RootanaDataClasses_408_0_3(), G__RootanaDataClasses_408_0_4(), G__setup_memfuncIDscLcLsource(), and G__setup_memvarIDscLcLsource().
G__linked_taginfo G__RootanaDataClassesLN_lesslEIDscLcLDetector_tgR = { "less<IDs::Detector_t>" , 115 , -1 }
Definition at line 6255 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_lesslEstringgR = { "less<string>" , 115 , -1 }
Definition at line 6210 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEIDscLcLchannelgRcOallocatorlEpairlEconstsPIDscLcLchannelcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR = { "map<IDs::channel,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<IDs::channel>,allocator<pair<const IDs::channel,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >" , 99 , -1 }
Definition at line 6221 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR = { "map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >" , 99 , -1 }
Definition at line 6257 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__RootanaDataClasses_606_0_1(), G__RootanaDataClasses_606_0_2(), G__RootanaDataClasses_606_0_3(), G__RootanaDataClasses_606_0_4(), G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR(), and G__setup_memvarmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiterator = { "map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator" , 99 , -1 }
Definition at line 6259 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), and G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLreverse_iterator = { "map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::reverse_iterator" , 99 , -1 }
Definition at line 6260 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), and G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR = { "map<IDs::source,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<IDs::source>,allocator<pair<const IDs::source,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >" , 99 , -1 }
Definition at line 6227 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_maplEIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEIDscLcLsourcegRcOallocatorlEpairlEconstsPIDscLcLsourcecOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR = { "map<IDs::source,vector<TDetectorPulse*,allocator<TDetectorPulse*> >,less<IDs::source>,allocator<pair<const IDs::source,vector<TDetectorPulse*,allocator<TDetectorPulse*> > > > >" , 99 , -1 }
Definition at line 6237 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR = { "map<string,bool,less<string>,allocator<pair<const string,bool> > >" , 99 , -1 }
Definition at line 6244 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 }
Definition at line 6212 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR = { "map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >" , 99 , -1 }
Definition at line 6250 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__RootanaDataClasses_597_0_1(), G__RootanaDataClasses_597_0_2(), G__RootanaDataClasses_597_0_3(), G__RootanaDataClasses_597_0_4(), G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR(), and G__setup_memvarmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiterator = { "map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator" , 99 , -1 }
Definition at line 6252 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), and G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLreverse_iterator = { "map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::reverse_iterator" , 99 , -1 }
Definition at line 6253 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), and G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 }
Definition at line 6211 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 }
Definition at line 6243 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >" , 99 , -1 }
Definition at line 6229 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__RootanaDataClasses_446_0_1(), G__RootanaDataClasses_446_0_2(), G__RootanaDataClasses_446_0_3(), G__RootanaDataClasses_446_0_4(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR(), G__setup_memfuncTAnalysedPulseMapWrapper(), G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR(), and G__setup_memvarTAnalysedPulseMapWrapper().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator" , 99 , -1 }
Definition at line 6231 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__RootanaDataClasses_448_0_1(), G__RootanaDataClasses_448_0_2(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), and G__setup_memvarmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLreverse_iterator = { "map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::reverse_iterator" , 99 , -1 }
Definition at line 6232 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), and G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TDetectorPulse*,allocator<TDetectorPulse*> >,less<string>,allocator<pair<const string,vector<TDetectorPulse*,allocator<TDetectorPulse*> > > > >" , 99 , -1 }
Definition at line 6238 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_maplEstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRsPgRsPgRsPgR = { "map<string,vector<TPulseIsland*,allocator<TPulseIsland*> >,less<string>,allocator<pair<const string,vector<TPulseIsland*,allocator<TPulseIsland*> > > > >" , 99 , -1 }
Definition at line 6222 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_pairlEIDscLcLDetector_tcOstringgR = { "pair<IDs::Detector_t,string>" , 115 , -1 }
Definition at line 6258 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_pairlEmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<IDs::Detector_t,string,less<IDs::Detector_t>,allocator<pair<const IDs::Detector_t,string> > >::iterator,bool>" , 115 , -1 }
Definition at line 6261 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_pairlEmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<string,IDs::Detector_t,less<string>,allocator<pair<const string,IDs::Detector_t> > >::iterator,bool>" , 115 , -1 }
Definition at line 6254 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__setup_memfuncmaplEstringcOIDscLcLDetector_tcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOIDscLcLDetector_tgRsPgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_pairlEmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR = { "pair<map<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >,less<string>,allocator<pair<const string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > > > >::iterator,bool>" , 115 , -1 }
Definition at line 6233 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_pairlEstringcOIDscLcLDetector_tgR = { "pair<string,IDs::Detector_t>" , 115 , -1 }
Definition at line 6251 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_pairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR = { "pair<string,vector<TAnalysedPulse*,allocator<TAnalysedPulse*> > >" , 115 , -1 }
Definition at line 6230 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__RootanaDataClasses_447_0_1(), G__RootanaDataClasses_447_0_2(), G__RootanaDataClasses_447_0_4(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgRcLcLiterator(), G__setup_memfuncpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), and G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 }
Definition at line 6207 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 }
Definition at line 6247 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), and G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator>" , 99 , -1 }
Definition at line 6226 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), and G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TDetectorPulse*,allocator<TDetectorPulse*> >::iterator>" , 99 , -1 }
Definition at line 6236 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMuonEvent*,allocator<TMuonEvent*> >::iterator>" , 99 , -1 }
Definition at line 6240 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TPulseIsland*,allocator<TPulseIsland*> >::iterator>" , 99 , -1 }
Definition at line 6220 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 }
Definition at line 6209 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_string = { "string" , 99 , -1 }
Definition at line 6205 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__setup_memfuncIDscLcLchannel(), G__setup_memfuncIDscLcLgenerator(), G__setup_memfuncIDscLcLsource(), G__setup_memfuncmaplEIDscLcLDetector_tcOstringcOlesslEIDscLcLDetector_tgRcOallocatorlEpairlEconstsPIDscLcLDetector_tcOstringgRsPgRsPgR(), G__setup_memfuncTAnalysedPulse(), G__setup_memfuncTDetectorPulse(), G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR(), G__setup_memvarIDscLcLgenerator(), G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), G__setup_memvarTAnalysedPulse(), and G__setup_memvarTDetectorPulse().
G__linked_taginfo G__RootanaDataClassesLN_TAnalysedPulse = { "TAnalysedPulse" , 99 , -1 }
Definition at line 6223 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_inheritanceRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__RootanaDataClasses_430_0_1(), G__RootanaDataClasses_430_0_2(), G__RootanaDataClasses_430_0_23(), G__RootanaDataClasses_430_0_3(), G__setup_memfuncTAnalysedPulse(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), G__setup_memvarTAnalysedPulse(), and G__setup_memvarTDetectorPulse().
G__linked_taginfo G__RootanaDataClassesLN_TAnalysedPulseMapWrapper = { "TAnalysedPulseMapWrapper" , 99 , -1 }
Definition at line 6248 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_inheritanceRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__RootanaDataClasses_594_0_1(), G__RootanaDataClasses_594_0_19(), G__RootanaDataClasses_594_0_2(), G__setup_memfuncTAnalysedPulseMapWrapper(), and G__setup_memvarTAnalysedPulseMapWrapper().
G__linked_taginfo G__RootanaDataClassesLN_TBuffer = { "TBuffer" , 99 , -1 }
Definition at line 6202 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), and G__cpp_setup_tagtableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_TClass = { "TClass" , 99 , -1 }
Definition at line 6201 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__setup_memfuncIDscLcLchannel(), G__setup_memfuncIDscLcLgenerator(), G__setup_memfuncIDscLcLsource(), G__setup_memfuncTAnalysedPulse(), G__setup_memfuncTAnalysedPulseMapWrapper(), G__setup_memfuncTDetectorPulse(), G__setup_memvarIDscLcLchannel(), G__setup_memvarIDscLcLgenerator(), G__setup_memvarIDscLcLsource(), G__setup_memvarTAnalysedPulse(), G__setup_memvarTAnalysedPulseMapWrapper(), and G__setup_memvarTDetectorPulse().
G__linked_taginfo G__RootanaDataClassesLN_TDetectorPulse = { "TDetectorPulse" , 99 , -1 }
Definition at line 6234 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_inheritanceRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__RootanaDataClasses_451_0_1(), G__RootanaDataClasses_451_0_2(), G__RootanaDataClasses_451_0_29(), G__setup_memfuncTDetectorPulse(), and G__setup_memvarTDetectorPulse().
G__linked_taginfo G__RootanaDataClassesLN_TMemberInspector = { "TMemberInspector" , 99 , -1 }
Definition at line 6203 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), and G__cpp_setup_tagtableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_TObject = { "TObject" , 99 , -1 }
Definition at line 6204 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_inheritanceRootanaDataClasses(), and G__cpp_setup_tagtableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 }
Definition at line 6242 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 }
Definition at line 6241 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 }
Definition at line 6206 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 }
Definition at line 6245 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__RootanaDataClasses_591_0_15(), G__RootanaDataClasses_591_0_16(), G__RootanaDataClasses_591_0_17(), G__RootanaDataClasses_591_0_18(), G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR(), and G__setup_memvarvectorlEstringcOallocatorlEstringgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator = { "vector<string,allocator<string> >::iterator" , 99 , -1 }
Definition at line 6246 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), and G__setup_memfuncvectorlEstringcOallocatorlEstringgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR = { "vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >" , 99 , -1 }
Definition at line 6224 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__RootanaDataClasses_432_0_15(), G__RootanaDataClasses_432_0_16(), G__RootanaDataClasses_432_0_17(), G__RootanaDataClasses_432_0_18(), G__setup_memfuncmaplEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgRsPgRsPgR(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR(), G__setup_memvarpairlEstringcOvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRsPgR(), and G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR().
G__linked_taginfo G__RootanaDataClassesLN_vectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator = { "vector<TAnalysedPulse*,allocator<TAnalysedPulse*> >::iterator" , 99 , -1 }
Definition at line 6225 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), G__cpp_setup_typetableRootanaDataClasses(), G__RootanaDataClasses_433_0_1(), G__RootanaDataClasses_433_0_16(), G__RootanaDataClasses_433_0_2(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgR(), G__setup_memfuncvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator(), and G__setup_memvarvectorlETAnalysedPulsemUcOallocatorlETAnalysedPulsemUgRsPgRcLcLiterator().
G__linked_taginfo G__RootanaDataClassesLN_vectorlETDetectorPulsemUcOallocatorlETDetectorPulsemUgRsPgR = { "vector<TDetectorPulse*,allocator<TDetectorPulse*> >" , 99 , -1 }
Definition at line 6235 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_vectorlETMuonEventmUcOallocatorlETMuonEventmUgRsPgR = { "vector<TMuonEvent*,allocator<TMuonEvent*> >" , 99 , -1 }
Definition at line 6239 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_vectorlETPulseIslandmUcOallocatorlETPulseIslandmUgRsPgR = { "vector<TPulseIsland*,allocator<TPulseIsland*> >" , 99 , -1 }
Definition at line 6219 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().
G__linked_taginfo G__RootanaDataClassesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 }
Definition at line 6208 of file RootanaDataClasses.cpp.
Referenced by G__cpp_reset_tagtableRootanaDataClasses(), G__cpp_setup_tagtableRootanaDataClasses(), and G__cpp_setup_typetableRootanaDataClasses().