AlcapDAQ: crate3/rpv130_module.cpp File Reference
rpv130_module.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/io.h>
#include <sys/time.h>
#include "midas.h"
#include "crate.h"
#include "diag.h"
#include "rpv130.h"
Macros
#define RPV130_BASE 0x8000
Functions
INT rpv130_init ()
INT rpv130_start_block ()
INT rpv130_poll_live ()
INT rpv130_poll_dead ()
Variables
bool block_sig
struct timespec timer_start
MVME_INTERFACE * myvme
struct readout_module rpv130_module
Macro Definition Documentation
#define RPV130_BASE 0x8000
Definition at line 15 of file rpv130_module.cpp.
Referenced by rpv130_poll_live(), and rpv130_start_block().
Function Documentation
INT rpv130_init ()
Definition at line 43 of file rpv130_module.cpp.
References mvme_open(), printf(), and SUCCESS.
 {
         printf("VME crate init...\n");
         mvme_open(&myvme,0);
   return SUCCESS;
 }
INT rpv130_poll_dead ()
Definition at line 92 of file rpv130_module.cpp.
 {
   return 0;
 }
INT rpv130_poll_live ()
Definition at line 73 of file rpv130_module.cpp.
References FE_END_BLOCK, printf(), RPV130_BASE, rpv130_IsBusy3(), and SUCCESS.
 {
         struct timespec timer_now;
         clock_gettime(CLOCK_REALTIME, &timer_now);
         unsigned int time_elapse =(timer_now.tv_sec - timer_start.tv_sec)*1000000000 +
                 (timer_now.tv_nsec - timer_start.tv_nsec);
         printf("time elapse: %ld\n", time_elapse);
         if (rpv130_IsBusy3(myvme, RPV130_BASE))
                 return FE_END_BLOCK;
         //if (time_elapse > 2*1000*1000)
         //{
                 //printf("end of block\n");
                 //return FE_END_BLOCK;
         //}
   return SUCCESS;
 }
INT rpv130_start_block ()
Definition at line 54 of file rpv130_module.cpp.
References RPV130_BASE, rpv130_ClearBusy3(), rpv130_Pulse(), and SUCCESS.
 {
         rpv130_Pulse(myvme, RPV130_BASE, 2);
         rpv130_ClearBusy3(myvme, RPV130_BASE);
         clock_gettime(CLOCK_REALTIME,&timer_start);
   return SUCCESS;
 }
Variable Documentation
bool block_sig
Definition at line 20 of file rpv130_module.cpp.
MVME_INTERFACE* myvme
Definition at line 22 of file rpv130_module.cpp.
struct readout_module rpv130_module
Initial value:
= {
  rpv130_init,
  NULL,
  NULL,
  NULL,
  NULL,
  rpv130_poll_live,
  rpv130_poll_dead,
  rpv130_start_block,
  NULL,
  NULL,
}
Definition at line 24 of file rpv130_module.cpp.
struct timespec timer_start
Definition at line 21 of file rpv130_module.cpp.