AlcapDAQ: bit3_mvme/rpv130.c File Reference
rpv130.c File Reference
#include "rpv130.h"
#include "bt617.h"
Functions
int rpv130_Clear (MVME_INTERFACE *vme, mvme_addr_t base_addr)
int rpv130_IsBusy1 (MVME_INTERFACE *vme, mvme_addr_t base_addr)
int rpv130_IsBusy2 (MVME_INTERFACE *vme, mvme_addr_t base_addr)
int rpv130_IsBusy3 (MVME_INTERFACE *vme, mvme_addr_t base_addr)
void rpv130_PrintBusyStatus (MVME_INTERFACE *vme, mvme_addr_t base_addr)
int rpv130_ClearBusy1 (MVME_INTERFACE *vme, mvme_addr_t base_addr)
int rpv130_ClearBusy2 (MVME_INTERFACE *vme, mvme_addr_t base_addr)
int rpv130_ClearBusy3 (MVME_INTERFACE *vme, mvme_addr_t base_addr)
int rpv130_Pulse (MVME_INTERFACE *vme, mvme_addr_t base_addr, int chn)
Function Documentation
int rpv130_Clear (MVME_INTERFACE * vme, mvme_addr_t base_addr)
Definition at line 11 of file rpv130.c.
References mvme_set_am(), mvme_set_dmode(), mvme_write_value(), RPV130_AM, RPV130_CSR_1, RPV130_CSR_2, and RPV130_DATA_SIZE.
 {
         mvme_set_dmode(vme, RPV130_DATA_SIZE);
         mvme_set_am(vme,RPV130_AM);
         mvme_write_value(vme,base_addr + RPV130_CSR_1, 0x3);
         mvme_write_value(vme,base_addr + RPV130_CSR_2, 0x3);
         return 0;
 }
int rpv130_ClearBusy1 (MVME_INTERFACE * vme, mvme_addr_t base_addr)
Definition at line 59 of file rpv130.c.
References mvme_set_am(), mvme_set_dmode(), mvme_write_value(), RPV130_AM, RPV130_CSR_1, and RPV130_DATA_SIZE.
 {
         mvme_set_dmode(vme, RPV130_DATA_SIZE);
         mvme_set_am(vme,RPV130_AM);
         mvme_write_value(vme,base_addr + RPV130_CSR_1, 0x2);
         return 0;
 }
int rpv130_ClearBusy2 (MVME_INTERFACE * vme, mvme_addr_t base_addr)
Definition at line 69 of file rpv130.c.
References mvme_set_am(), mvme_set_dmode(), mvme_write_value(), RPV130_AM, RPV130_CSR_2, and RPV130_DATA_SIZE.
 {
         mvme_set_dmode(vme, RPV130_DATA_SIZE);
         mvme_set_am(vme,RPV130_AM);
         mvme_write_value(vme,base_addr + RPV130_CSR_2, 0x2);
         return 0;
 }
int rpv130_ClearBusy3 (MVME_INTERFACE * vme, mvme_addr_t base_addr)
Definition at line 78 of file rpv130.c.
References mvme_set_am(), mvme_set_dmode(), mvme_write_value(), RPV130_AM, RPV130_CSR_2, and RPV130_DATA_SIZE.
Referenced by rpv130_start_block().
 {
         mvme_set_dmode(vme, RPV130_DATA_SIZE);
         mvme_set_am(vme,RPV130_AM);
         mvme_write_value(vme,base_addr + RPV130_CSR_2, 0x3);
         return 0;
 }
int rpv130_IsBusy1 (MVME_INTERFACE * vme, mvme_addr_t base_addr)
Definition at line 22 of file rpv130.c.
References mvme_read_value(), mvme_set_am(), mvme_set_dmode(), RPV130_AM, RPV130_CSR_1, and RPV130_DATA_SIZE.
Referenced by rpv130_PrintBusyStatus().
 {
         mvme_set_dmode(vme, RPV130_DATA_SIZE);
         mvme_set_am(vme,RPV130_AM);
         unsigned short int reg = mvme_read_value(vme,base_addr + RPV130_CSR_1);
         return ((reg & (1<<5))>>5);
 }
int rpv130_IsBusy2 (MVME_INTERFACE * vme, mvme_addr_t base_addr)
Definition at line 32 of file rpv130.c.
References mvme_read_value(), mvme_set_am(), mvme_set_dmode(), RPV130_AM, RPV130_CSR_2, and RPV130_DATA_SIZE.
Referenced by rpv130_PrintBusyStatus().
 {
         mvme_set_dmode(vme, RPV130_DATA_SIZE);
         mvme_set_am(vme,RPV130_AM);
         unsigned short int reg = mvme_read_value(vme,base_addr + RPV130_CSR_2);
         return ((reg & (1<<5))>>5);
 }
int rpv130_IsBusy3 (MVME_INTERFACE * vme, mvme_addr_t base_addr)
Definition at line 42 of file rpv130.c.
References mvme_read_value(), mvme_set_am(), mvme_set_dmode(), RPV130_AM, RPV130_CSR_2, and RPV130_DATA_SIZE.
Referenced by rpv130_poll_live(), and rpv130_PrintBusyStatus().
 {
         mvme_set_dmode(vme, RPV130_DATA_SIZE);
         mvme_set_am(vme,RPV130_AM);
         unsigned short int reg = mvme_read_value(vme,base_addr + RPV130_CSR_2);
         return ((reg & (1<<7))>>7);
 }
void rpv130_PrintBusyStatus (MVME_INTERFACE * vme, mvme_addr_t base_addr)
Definition at line 52 of file rpv130.c.
References printf(), rpv130_IsBusy1(), rpv130_IsBusy2(), and rpv130_IsBusy3().
 {
         printf("Busy1: %d\n",rpv130_IsBusy1(vme,base_addr));
         printf("Busy2: %d\n",rpv130_IsBusy2(vme,base_addr));
         printf("Busy3: %d\n",rpv130_IsBusy3(vme,base_addr));
 }
int rpv130_Pulse (MVME_INTERFACE * vme, mvme_addr_t base_addr, int chn)
Definition at line 87 of file rpv130.c.
References mvme_set_am(), mvme_set_dmode(), mvme_write_value(), RPV130_AM, RPV130_DATA_SIZE, and RPV130_PULSE.
Referenced by rpv130_start_block().
 {
         if ((chn < 1) || (chn > 8))
                 return -1;
         mvme_set_dmode(vme, RPV130_DATA_SIZE);
         mvme_set_am(vme,RPV130_AM);
         mvme_write_value(vme,base_addr + RPV130_PULSE, (0x1<<(chn-1)));
         return 0;
 }