AlcapDAQ: midas/mscb/embedded/scs_210.c File Reference
midas/mscb/embedded/scs_210.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mscb.h"
Functions
void user_write (unsigned char channel) reentrant
void write_gain (void)
void user_init (unsigned char init)
unsigned char user_read (unsigned char channel)
void user_write_conf (unsigned char channel) reentrant
void user_read_conf (unsigned char channel)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
void user_loop (void)
Variables
bit FREEZE_MODE
bit DEBUG_MODE
char code node_name [] = "SCS-210"
unsigned char idata _n_sub_addr = 1
bit terminal_mode
bit output_flag
unsigned char n_in
struct {
char output [32]
char input [32]
unsigned char baud
} user_data
MSCB_INFO_VAR code variables []
unsigned char xdata in_buf [300]
unsigned char xdata out_buf [300]
char idata obuf [8]
sbit EWD = P0 ^ 6
Function Documentation
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 178 of file scs_210.c.
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void user_init (unsigned char init)
Definition at line 102 of file scs_210.c.
References uart_init(), and user_data.
{
   /* initialize UART1 */
   if (init)
      user_data.baud = 1;       // 9600 by default
   uart_init(1, user_data.baud);
}
void user_loop (void)
Definition at line 191 of file scs_210.c.
References c, delay_ms(), EWD, flush(), for(), getchar_nowait(), i, led_blink(), n_in, output_flag, putchar(), terminal_mode, and user_data.
{
   char c;
   unsigned char i;
   if (output_flag)
      {
      output_flag = 0;
      /* delete input string */
      n_in = 0;
      for (i=0 ; i<32 ; i++)
         user_data.input[i] = 0;
      /* send output string */
      for (i=0 ; i<32 ; i++) {
         if (!user_data.output[i])
            break;
         putchar(user_data.output[i]);
         flush();
         /* delay for slow modules */
         delay_ms(10);
      }
   }
   if (!terminal_mode) {
      c = getchar_nowait();
      if (c != -1 && n_in < 32) {
         user_data.input[n_in++] = c;
         led_blink(1, 1, 50);
      }
   }
   /* toggle external watchdog */
   EWD = !EWD;
}
unsigned char user_read (unsigned char channel)
Definition at line 146 of file scs_210.c.
References c, getchar_nowait(), and out_buf.
{
   char c;
   if (channel == 0) {
      c = getchar_nowait();
      if (c != -1) {
         out_buf[1] = c;
         return 1;
      }
   }
   return 0;
}
void user_read_conf (unsigned char channel)
Definition at line 171 of file scs_210.c.
{
   if (channel);
}
void user_write (unsigned char channel)
Definition at line 120 of file scs_210.c.
References i, in_buf, index, n, output_flag, putchar(), terminal_mode, uart_init(), and user_data.
{
   unsigned char i, n;
   /* manage terminal functions */
   if (index == 0) {
      if (in_buf[2] == 27)
         terminal_mode = 0;
      else if (in_buf[2] == 0)
         terminal_mode = 1;
      else {
         n = (in_buf[0] & 0x07) - 1;
         for (i = 0; i < n; i++)
            putchar(in_buf[i + 2]);
      }
   }
   if (index == 1)
      output_flag = 1;
   if (index == 3)
      uart_init(1, user_data.baud);
}
void user_write_conf (unsigned char channel)
Definition at line 163 of file scs_210.c.
References channel, uart_init(), and user_data.
{
   if (channel == 0)
      uart_init(1, user_data.baud);
}
void write_gain (void)
Definition at line 219 of file scs_500.c.
Referenced by user_loop(), and user_write().
{
   unsigned char i;
   SR_STROBE = 0;
   SR_CLOCK = 0;
   for (i = 0; i < 4; i++) {
      SR_DATA = ((user_data.gain[3 - i] & 0x02) > 0);   // first bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
      SR_DATA = ((user_data.gain[3 - i] & 0x01) > 0);   // second bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
   }
   for (i = 0; i < 4; i++) {
      SR_DATA = ((user_data.gain[7 - i] & 0x02) > 0);   // first bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
      SR_DATA = ((user_data.gain[7 - i] & 0x01) > 0);   // second bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
   }
   SR_DATA = 0;
   SR_STROBE = 1;
   SR_STROBE = 0;
}
Variable Documentation
unsigned char idata _n_sub_addr = 1
Definition at line 67 of file scs_210.c.
unsigned char baud
Definition at line 80 of file scs_210.c.
bit DEBUG_MODE
Definition at line 247 of file mscbmain.c.
sbit EWD = P0 ^ 6
Definition at line 189 of file scs_210.c.
Referenced by user_loop().
bit FREEZE_MODE
Definition at line 249 of file mscbmain.c.
unsigned char xdata in_buf[300]
Definition at line 227 of file mscbmain.c.
char input[32]
Definition at line 79 of file scs_210.c.
Referenced by floppy_ttl_poll_live(), floppy_ttl_start_block(), and modules::parser::ParseConstructor().
unsigned char n_in
Definition at line 70 of file scs_210.c.
Referenced by user_loop().
char code node_name[] = "SCS-210"
Definition at line 64 of file scs_210.c.
char idata obuf[8]
Definition at line 118 of file scs_210.c.
Referenced by write_v1718().
unsigned char xdata out_buf[300]
Definition at line 227 of file mscbmain.c.
static void output
Definition at line 78 of file scs_210.c.
Referenced by cl_block(), compress(), IDs::channel::GetDetectorString(), IDs::channel::GetSlowFastString(), MakePulseHeightSums(), MakePulseTimeHeightMap(), ser_clock(), set_power(), IDs::channel::str(), SumPulses(), and user_init().
bit output_flag
Definition at line 69 of file scs_210.c.
Referenced by user_init(), user_loop(), and user_write().
bit terminal_mode
Definition at line 69 of file scs_210.c.
Referenced by user_init(), user_loop(), user_read(), and user_write().
struct { ... } user_data
MSCB_INFO_VAR code variables[]
Initial value:
 {
   1,   UNIT_ASCII,  0, 0, MSCBF_DATALESS, "RS232", 0,
   32,  UNIT_STRING, 0, 0,              0, "Output", &user_data.output[0],
   32,  UNIT_STRING, 0, 0,              0, "Input", &user_data.input[0],
   1,   UNIT_BAUD,   0, 0,              0, "Baud", &user_data.baud,
   0
}
Definition at line 83 of file scs_210.c.