AlcapDAQ: midas/mscb/embedded/scs_310.c File Reference
midas/mscb/embedded/scs_310.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "mscb.h"
Defines
#define GPIB_DATA P1
Functions
void user_write (unsigned char index) reentrant
char send (unsigned char adr, char *str)
char send_byte (unsigned char b)
void user_init (unsigned char init)
unsigned char user_read (unsigned char index)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
char enter (unsigned char adr, char *str, char maxlen)
void user_loop (void)
Variables
char code node_name [] = "SCS-310"
unsigned char idata _n_sub_addr = 1
bit terminal_mode
bit term_flag
bit output_flag
bit control_flag
xdata char term_buf [80]
char tbwp
char tbrp
struct {
char output [32]
char input [32]
char control
char srq
char gpib_adr
} user_data
MSCB_INFO_VAR code variables []
sbit GPIB_EOI = P2 ^ 1
sbit GPIB_DAV = P2 ^ 2
sbit GPIB_NRFD = P2 ^ 3
sbit GPIB_NDAC = P2 ^ 4
sbit GPIB_IFC = P2 ^ 5
sbit GPIB_SRQ = P2 ^ 6
sbit GPIB_ATN = P2 ^ 7
sbit GPIB_REM = P2 ^ 0
unsigned char xdata in_buf [300]
unsigned char xdata out_buf [300]
idata char str [32]
Define Documentation
#define GPIB_DATA P1
Definition at line 109 of file scs_310.c.
Referenced by enter(), send_byte(), and user_init().
Function Documentation
char enter (unsigned char adr, char * str, char maxlen)
Definition at line 294 of file scs_310.c.
References flag, GPIB_ATN, GPIB_DATA, GPIB_DAV, GPIB_EOI, GPIB_NDAC, GPIB_NRFD, i, j, led_blink(), send_byte(), time, and yield().
Referenced by user_loop().
{
   unsigned long t;
   unsigned char i, flag;
   unsigned int j;
  /*---- address cycle ----*/
   GPIB_ATN = 0;                // assert attention
   send_byte(0x3F);             // unlisten
   send_byte(0x5F);             // untalk
   send_byte(0x20 | 21);        // listen 21
   send_byte(0x40 | adr);       // talk device
   GPIB_ATN = 1;                // remove attention
  /*---- data cycles ----*/
   GPIB_NDAC = 0;               // init NDAC line
   memset(str, 0, maxlen);
   for (i = 0; i < maxlen; i++) {
      yield();
      GPIB_NRFD = 1;            // singal ready for data
      /* wait 1s for DAV go low */
      t = time();
      do {
         if (GPIB_DAV == 0)
            break;
         yield();
      } while (time() - t < 100);
      if (GPIB_DAV == 1) {
         GPIB_NDAC = 1;
         GPIB_NRFD = 1;
         return 0;              // timeout
      }
      led_blink(1, 1, 100);     // singal data received
      GPIB_NRFD = 0;            // signal busy
      str[i] = ~GPIB_DATA;      // read negated data
      flag = GPIB_EOI;          // read EOI flag
      GPIB_NDAC = 1;            // signal acknowledge
      /* wait for DAV go high */
      for (j = 0; j < 1000; j++)
         if (GPIB_DAV == 1)
            break;
      GPIB_NDAC = 0;            // remove acknowledge
      if (flag == 0)            // stop if end of data
         break;
   }
   GPIB_NDAC = 1;               // release handshake lines
   GPIB_NRFD = 1;
   /* stop talker */
   GPIB_ATN = 0;                // assert attention
   send_byte(0x3F);             // unlisten
   send_byte(0x5F);             // untalk
   GPIB_ATN = 1;                // remove attention
   return i;
}
char send (unsigned char adr, char * str)
Definition at line 266 of file scs_310.c.
References GPIB_ATN, GPIB_EOI, i, and send_byte().
Referenced by bb_psi_get(), bb_psi_set(), bl_psi_init(), bl_psi_rall(), bl_psi_set(), cm_list_experiments(), ftp_send(), ftp_send_message(), msend_tcp(), rpc_client_accept(), rpc_client_connect(), rpc_client_disconnect(), rpc_server_accept(), rpc_server_callback(), rpc_server_connect(), scope_send(), send_tcp(), send_udp(), sendmail(), server_loop(), ss_shell(), submit_elog(), tcpip_puts(), tcpip_write(), and user_loop().
{
   unsigned char i;
  /*---- address cycle ----*/
   GPIB_ATN = 0;                // assert attention
   send_byte(0x3F);             // unlisten
   send_byte(0x5F);             // untalk
   send_byte(0x20 | adr);       // listen device
   send_byte(0x40 | 21);        // talk 21
   GPIB_ATN = 1;                // remove attention
  /*---- data cycles ----*/
   for (i = 0; str[i] > 0; i++)
      if (send_byte(str[i]) == 0)
         return 0;
   GPIB_EOI = 0;
   send_byte(0x0A);             // NL
   GPIB_EOI = 1;
   return i;
}
char send_byte (unsigned char b)
Definition at line 221 of file scs_310.c.
References delay_us(), GPIB_DATA, GPIB_DAV, GPIB_NDAC, GPIB_NRFD, i, and yield().
{
   unsigned int i;
   yield();
   /* wait for NRFD go high */
   for (i = 0; i < 1000; i++)
      if (GPIB_NRFD == 1)
         break;
   if (GPIB_NRFD == 0)
      return 0;
   GPIB_DATA = ~b;              // negate
   delay_us(1);                 // let signals settle
   GPIB_DAV = 0;
   /* wait for NDAC go high */
   for (i = 0; i < 1000; i++)
      if (GPIB_NDAC == 1)
         break;
   if (GPIB_NDAC == 0) {
      GPIB_DAV = 1;
      GPIB_DATA = 0xFF;
      return 0;                 // timeout
   }
   GPIB_DAV = 1;
   GPIB_DATA = 0xFF;            // prepare for input
   /* wait for NRFD go high */
   for (i = 0; i < 1000; i++)
      if (GPIB_NRFD == 1)
         break;
   if (GPIB_NRFD == 0)
      return 0;
   return 1;
}
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 211 of file scs_310.c.
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void user_init (unsigned char init)
Definition at line 129 of file scs_310.c.
References delay_ms(), GPIB_ATN, GPIB_DATA, GPIB_DAV, GPIB_EOI, GPIB_IFC, GPIB_NDAC, GPIB_NRFD, GPIB_REM, GPIB_SRQ, output_flag, send_byte(), terminal_mode, and user_data.
{
   /* set initial state of lines */
   GPIB_DATA = 0xFF;
   GPIB_EOI = 1;
   GPIB_DAV = 1;
   GPIB_NRFD = 1;
   GPIB_NDAC = 1;
   GPIB_IFC = 1;
   GPIB_SRQ = 1;
   GPIB_ATN = 1;
   GPIB_REM = 1;
   /* initialize GPIB */
   GPIB_IFC = 0;
   delay_ms(1);
   GPIB_IFC = 1;
   GPIB_ATN = 0;
   send_byte(0x14);             // DCL
   GPIB_ATN = 1;
   terminal_mode = 0;
   output_flag = 0;
   if (init) {
      user_data.gpib_adr = 16;
      user_data.control = 0;
      user_data.srq = 0;
   }
}
void user_loop (void)
Definition at line 373 of file scs_310.c.
References control_flag, DISABLE_INTERRUPTS, ENABLE_INTERRUPTS, enter(), GPIB_ATN, led_blink(), output_flag, send(), send_byte(), tbwp, term_buf, term_flag, terminal_mode, and user_data.
{
   if (terminal_mode) {
      /* check terminal buffer */
      DISABLE_INTERRUPTS;
      if (tbwp > 0 && term_buf[tbwp - 1] == 13) {
         /* add trailing "0" */
         if (tbwp == sizeof(term_buf))
            tbwp--;
         term_buf[tbwp] = 0;
         /* send buffer */
         send(user_data.gpib_adr, term_buf);
         led_blink(1, 1, 100);
         /* receive buffer */
         tbwp = enter(user_data.gpib_adr, term_buf, sizeof(term_buf));
         if (tbwp > 0) {
            /* add newline */
            term_buf[tbwp++] = 10;
            term_flag = 1;
         } else
            term_flag = 0;
      }
      ENABLE_INTERRUPTS;
   }
   if (output_flag) {
      output_flag = 0;
      /* send buffer */
      send(user_data.gpib_adr, user_data.output);
      /* receive buffer */
      if (enter(user_data.gpib_adr, user_data.input, sizeof(user_data.input)))
         led_blink(1, 1, 100);
      /* stip NL */
      if (strlen(user_data.input) > 0 &&
          user_data.input[strlen(user_data.input) - 1] == 10)
         user_data.input[strlen(user_data.input) - 1] = 0;
   }
   if (control_flag) {
      control_flag = 0;
      GPIB_ATN = 0;             // assert attention
      send_byte(0x3F);          // unlisten
      send_byte(0x5F);          // untalk
      send_byte(0x20 | user_data.gpib_adr);     // listen device
      send_byte(0x40 | 21);     // talk 21
      send_byte(user_data.control);     // send control
      send_byte(0x3F);          // unlisten
      send_byte(0x5F);          // untalk
      GPIB_ATN = 1;             // remove attention
   }
}
unsigned char user_read (unsigned char index)
Definition at line 193 of file scs_310.c.
References out_buf, tbrp, tbwp, term_buf, term_flag, and terminal_mode.
{
   if (index == 0) {
      if (terminal_mode && term_flag == 1) {
         out_buf[1] = term_buf[tbrp++];
         if (tbrp == tbwp) {
            tbrp = tbwp = 0;
            term_flag = 0;
         }
         return 1;
      }
   }
   return 0;
}
void user_write (unsigned char index)
Definition at line 166 of file scs_310.c.
References control_flag, in_buf, index, output_flag, tbrp, tbwp, term_buf, term_flag, and terminal_mode.
{
   if (index == 0) {
      if (in_buf[2] == 27)
         terminal_mode = 0;
      else if (in_buf[2] == 0) {
         terminal_mode = 1;
         term_flag = 0;
         tbwp = 0;
         tbrp = 0;
      } else {
         /* put byte in terminal buffer for main loop */
         term_buf[tbwp] = in_buf[2];
         if (tbwp < sizeof(term_buf))
            tbwp++;
      }
   }
   if (index == 1)
      output_flag = 1;
   if (index == 3)
      control_flag = 1;
}
Variable Documentation
unsigned char idata _n_sub_addr = 1
Definition at line 74 of file scs_310.c.
char control
Definition at line 87 of file scs_310.c.
bit control_flag
Definition at line 76 of file scs_310.c.
Referenced by user_loop(), and user_write().
char gpib_adr
Definition at line 89 of file scs_310.c.
sbit GPIB_ATN = P2 ^ 7
Definition at line 118 of file scs_310.c.
Referenced by enter(), send(), user_init(), and user_loop().
sbit GPIB_DAV = P2 ^ 2
Definition at line 113 of file scs_310.c.
Referenced by enter(), send_byte(), and user_init().
sbit GPIB_EOI = P2 ^ 1
Definition at line 112 of file scs_310.c.
Referenced by enter(), send(), and user_init().
sbit GPIB_IFC = P2 ^ 5
Definition at line 116 of file scs_310.c.
Referenced by user_init().
sbit GPIB_NDAC = P2 ^ 4
Definition at line 115 of file scs_310.c.
Referenced by enter(), send_byte(), and user_init().
sbit GPIB_NRFD = P2 ^ 3
Definition at line 114 of file scs_310.c.
Referenced by enter(), send_byte(), and user_init().
sbit GPIB_REM = P2 ^ 0
Definition at line 119 of file scs_310.c.
Referenced by user_init().
sbit GPIB_SRQ = P2 ^ 6
Definition at line 117 of file scs_310.c.
Referenced by user_init().
unsigned char xdata in_buf[300]
Definition at line 227 of file mscbmain.c.
char input[32]
Definition at line 86 of file scs_310.c.
char code node_name[] = "SCS-310"
Definition at line 71 of file scs_310.c.
unsigned char xdata out_buf[300]
Definition at line 227 of file mscbmain.c.
char output[32]
Definition at line 85 of file scs_310.c.
bit output_flag
Definition at line 76 of file scs_310.c.
char srq
Definition at line 88 of file scs_310.c.
idata char str[32]
Definition at line 371 of file scs_310.c.
char tbrp
Definition at line 78 of file scs_310.c.
Referenced by user_read(), and user_write().
char tbwp
Definition at line 78 of file scs_310.c.
Referenced by user_loop(), user_read(), and user_write().
xdata char term_buf[80]
Definition at line 77 of file scs_310.c.
Referenced by user_loop(), user_read(), and user_write().
bit term_flag
Definition at line 76 of file scs_310.c.
Referenced by user_loop(), user_read(), and user_write().
bit terminal_mode
Definition at line 76 of file scs_310.c.
struct { ... } user_data
MSCB_INFO_VAR code variables[]
Initial value:
 {
   1,  UNIT_ASCII,  0, 0, MSCBF_DATALESS, "GPIB",                       0,
   32, UNIT_STRING, 0, 0,              0, "Output",  &user_data.output[0],
   32, UNIT_STRING, 0, 0,              0, "Input",    &user_data.input[0],
   1,  UNIT_BYTE,   0, 0,              0, "Control",   &user_data.control,
   1,  UNIT_BYTE,   0, 0,              0, "SRQ",           &user_data.srq,
   1,  UNIT_BYTE,   0, 0,              0, "GPIB Adr", &user_data.gpib_adr,
   0
}
Definition at line 92 of file scs_310.c.