AlcapDAQ: midas/mscb/embedded/scs_900.c File Reference
midas/mscb/embedded/scs_900.c File Reference
#include <stdio.h>
#include <math.h>
#include "mscb.h"
Defines
#define REG_STATUS 0
#define REG_MODE 1
#define REG_CONTROL 2
#define REG_FILTER 3
#define REG_ADCDATA 4
#define REG_ADCOFFSET 5
#define REG_ADCGAIN 6
#define REG_IOCONTROL 7
Functions
void user_write (unsigned char index) reentrant
void write_adc (unsigned char a, unsigned char d)
void user_init (unsigned char init)
void write_dac_cmd (unsigned char cmd, unsigned char adr, unsigned short d)
void write_dac (unsigned char index) reentrant
void read_adc8 (unsigned char a, unsigned char *d)
void read_adc24 (unsigned char a, unsigned long *d)
void adc_read ()
void adc_calib ()
unsigned char user_read (unsigned char index)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
void user_loop (void)
Variables
bit FREEZE_MODE
bit DEBUG_MODE
char code node_name [] = "SCS-900"
unsigned char idata _n_sub_addr = 1
sbit ADC_P1 = P1 ^ 1
sbit ADC_NRES = P1 ^ 2
sbit ADC_SCLK = P1 ^ 3
sbit ADC_NCS = P1 ^ 4
sbit ADC_NRDY = P1 ^ 5
sbit ADC_DOUT = P1 ^ 6
sbit ADC_DIN = P1 ^ 7
sbit DAC_NCS = P0 ^ 3
sbit DAC_SCK = P0 ^ 4
sbit DAC_CLR = P0 ^ 5
sbit DAC_DOUT = P0 ^ 6
sbit DAC_DIN = P0 ^ 7
sbit UNI_DAC = P1 ^ 0
sbit UNI_ADC = P0 ^ 2
struct {
float adc [8]
float dac [8]
char uni_dac
char uni_adc
char adc_25
} user_data
MSCB_INFO_VAR code variables []
unsigned char adc_chn = 0
SYS_INFO sys_info
unsigned char code dac_index [8] = {4, 5, 2, 3, 1, 0, 7, 6}
unsigned char code adc_index [8] = {6, 7, 0, 1, 2, 3, 4, 5}
Define Documentation
#define REG_ADCDATA 4
Definition at line 70 of file scs_900.c.
#define REG_ADCGAIN 6
Definition at line 72 of file scs_900.c.
#define REG_ADCOFFSET 5
Definition at line 71 of file scs_900.c.
#define REG_CONTROL 2
Definition at line 68 of file scs_900.c.
#define REG_FILTER 3
Definition at line 69 of file scs_900.c.
#define REG_IOCONTROL 7
Definition at line 73 of file scs_900.c.
#define REG_MODE 1
Definition at line 67 of file scs_900.c.
#define REG_STATUS 0
Definition at line 66 of file scs_900.c.
Function Documentation
void adc_calib ()
Definition at line 423 of file scs_900.c.
References ADC_NRDY, i, led_blink(), REG_CONTROL, REG_MODE, and write_adc().
{
   unsigned char i;
   for (i=0 ; i<8 ; i++) {
      write_adc(REG_CONTROL, i << 4 | 0x0F);
      /* zero calibration */
      write_adc(REG_MODE, 4);
      while (ADC_NRDY) led_blink(1, 1, 100);
      /* full scale calibration */
      write_adc(REG_MODE, 5);
      while (ADC_NRDY) led_blink(1, 1, 100);
   }
   /* restart continuous conversion */
   write_adc(REG_MODE, 3);
}
void adc_read ()
Definition at line 388 of file scs_900.c.
References adc_chn, adc_index, ADC_NRDY, DISABLE_INTERRUPTS, ENABLE_INTERRUPTS, i, read_adc24(), REG_ADCDATA, REG_CONTROL, user_data, value, and write_adc().
{
   unsigned char i;
   unsigned long value;
   float gvalue;
   if (ADC_NRDY)
       return;
   read_adc24(REG_ADCDATA, &value);
   /* convert to volts */
   gvalue = ((float)value / (1l<<24)) * 2.56;
   /* round result to 5 digits */
   gvalue = floor(gvalue*1E5+0.5)/1E5;
   /* apply range */
   if (user_data.adc_25 == 0) {
      if (user_data.uni_adc)
         gvalue *= 10.0/2.56;
      else
         gvalue = gvalue/2.56*20.0 - 10;
   }
   DISABLE_INTERRUPTS;
   user_data.adc[adc_chn] = gvalue;
   ENABLE_INTERRUPTS;
   /* start next conversion */
   adc_chn = (adc_chn + 1) % 8;
   i = adc_index[adc_chn];
   write_adc(REG_CONTROL, i << 4 | 0x0F); // adc_chn, +2.56V range
}
void read_adc24 (unsigned char a, unsigned long * d)
Definition at line 347 of file scs_900.c.
References ADC_DIN, ADC_DOUT, ADC_NCS, ADC_SCLK, and i.
{
   unsigned char i, m;
   /* write to communication register */
   ADC_NCS = 0;
   /* write zero to !WEN and one to R/!W */
   for (i=0 ; i<4 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = (i == 1);
      ADC_SCLK = 1;
   }
   /* register address */
   for (i=0,m=8 ; i<4 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = (a & m) > 0;
      ADC_SCLK = 1;
      m >>= 1;
   }
   ADC_NCS = 1;
   /* read from selected data register */
   ADC_NCS = 0;
   for (i=0,*d=0 ; i<24 ; i++) {
      *d <<= 1;
      ADC_SCLK = 0;
      *d |= ADC_DOUT;
      ADC_SCLK = 1;
   }
   ADC_NCS = 1;
}
void read_adc8 (unsigned char a, unsigned char * d)
Definition at line 307 of file scs_900.c.
References ADC_DIN, ADC_DOUT, ADC_NCS, ADC_SCLK, and i.
{
   unsigned char i, m;
   /* write to communication register */
   ADC_NCS = 0;
   /* write zero to !WEN and one to R/!W */
   for (i=0 ; i<4 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = (i == 1);
      ADC_SCLK = 1;
   }
   /* register address */
   for (i=0,m=8 ; i<4 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = (a & m) > 0;
      ADC_SCLK = 1;
      m >>= 1;
   }
   ADC_NCS = 1;
   /* read from selected data register */
   ADC_NCS = 0;
   for (i=0,m=0x80,*d=0 ; i<8 ; i++) {
      ADC_SCLK = 0;
      if (ADC_DOUT)
         *d |= m;
      ADC_SCLK = 1;
      m >>= 1;
   }
   ADC_NCS = 1;
}
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 462 of file scs_900.c.
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void user_init (unsigned char init)
Definition at line 129 of file scs_900.c.
References ADC0CN, adc_chn, ADC_NRES, DAC0CN, DAC1CN, DAC_CLR, i, P0, P1, PRT0CF, PRT1CF, REF0CN, REG_CONTROL, REG_FILTER, REG_MODE, UNI_ADC, UNI_DAC, user_data, user_write(), and write_adc().
{
   unsigned char i;
   ADC0CN = 0x00;               // disable ADC
   DAC0CN = 0x00;               // disable DAC0
   DAC1CN = 0x00;               // disable DAC1
   REF0CN = 0x00;               // disenable internal reference
   /* push-pull:
      P0.0    TX
      P0.1
      P0.2    SW_ADC
      P0.3    DAC_NCS
      P0.4    DAC_SCK
      P0.5    DAC_DIN
      P0.6
      P0.7    DAC_CLR
    */
   PRT0CF = 0xBD;
   P0 = 0xFF;
   /* push-pull:
      P1.0    SW_DAC
      P1.1
      P1.2    ADC_NRES
      P1.3    ADC_SCLK
      P1.4    ADC_NCS
      P1.5
      P1.6
      P1.7    ADC_DIN
    */
   PRT1CF = 0x9D;
   P1 = 0xFF;
   /* initial EEPROM value */
   if (init) {
      for (i = 0; i < 8; i++)
         user_data.dac[i] = 0;
   }
   /* set-up DAC & ADC */
   DAC_CLR = 1;
   ADC_NRES = 1;
   write_adc(REG_FILTER, 82);                   // SF value for 50Hz rejection
   write_adc(REG_MODE, 3);                      // continuous conversion
   write_adc(REG_CONTROL, adc_chn << 4 | 0x0F); // Chn. 1, +2.56V range
   /* write DACs and UNI_BIP */
   for (i=0 ; i<8 ; i++)
      user_write(i+8);
   user_write(16);
   /* swich unipolar/bipolar */
   user_data.uni_dac = 0;
   user_data.uni_adc = 0;
   user_data.adc_25 = 0;
   UNI_DAC = user_data.uni_dac;
   UNI_ADC = !user_data.uni_adc;
}
void user_loop (void)
Definition at line 472 of file scs_900.c.
References adc_read().
{
   adc_read();
}
unsigned char user_read (unsigned char index)
Definition at line 454 of file scs_900.c.
{
   if (index);
   return 0;
}
void user_write (unsigned char index)
Definition at line 446 of file scs_900.c.
References index, and write_dac().
{
   if (index > 7 && index < 16)
      write_dac(index-8);
}
void write_adc (unsigned char a, unsigned char d)
Definition at line 268 of file scs_900.c.
References ADC_DIN, ADC_NCS, ADC_SCLK, and i.
{
   unsigned char i, m;
   /* write to communication register */
   ADC_NCS = 0;
   /* write zeros to !WEN and R/!W */
   for (i=0 ; i<4 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = 0;
      ADC_SCLK = 1;
   }
   /* register address */
   for (i=0,m=8 ; i<4 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = (a & m) > 0;
      ADC_SCLK = 1;
      m >>= 1;
   }
   ADC_NCS = 1;
   /* write to selected data register */
   ADC_NCS = 0;
   for (i=0,m=0x80 ; i<8 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = (d & m) > 0;
      ADC_SCLK = 1;
      m >>= 1;
   }
   ADC_NCS = 1;
}
void write_dac (unsigned char index)
Definition at line 239 of file scs_900.c.
References d, dac_index, index, user_data, and write_dac_cmd().
{
   unsigned short d;
   if (user_data.uni_dac) {
      if (user_data.dac[index] < 0)
         user_data.dac[index] = 0;
      if (user_data.dac[index] > 10)
         user_data.dac[index] = 10;
      d = user_data.dac[index] / 10 * 65535 + 0.5;
   } else {
      if (user_data.dac[index] < -10)
         user_data.dac[index] = -10;
      if (user_data.dac[index] > 10)
         user_data.dac[index] = 10;
      d = (user_data.dac[index] + 10) / 20 * 65535 + 0.5;
   }
   /* do mapping */
   index = dac_index[index % 8];
   write_dac_cmd(0x3, index, d);
}
void write_dac_cmd (unsigned char cmd, unsigned char adr, unsigned short d)
Definition at line 199 of file scs_900.c.
References DAC_DIN, DAC_NCS, DAC_SCK, and i.
Referenced by write_dac().
{
unsigned char i, m, b;
   DAC_NCS = 0; // chip select
   for (i=0,m=8 ; i<4 ; i++) {
      DAC_SCK = 0;
      DAC_DIN = (cmd & m) > 0;
      DAC_SCK = 1;
      m >>= 1;
   }
   for (i=0,m=8 ; i<4 ; i++) {
      DAC_SCK = 0;
      DAC_DIN = (adr & m) > 0;
      DAC_SCK = 1;
      m >>= 1;
   }
   b = d >> 8;
   for (i=0,m=0x80 ; i<8 ; i++) {
      DAC_SCK = 0;
      DAC_DIN = (b & m) > 0;
      DAC_SCK = 1;
      m >>= 1;
   }
   b = d & 0xFF;
   for (i=0,m=0x80 ; i<8 ; i++) {
      DAC_SCK = 0;
      DAC_DIN = (b & m) > 0;
      DAC_SCK = 1;
      m >>= 1;
   }
   DAC_NCS = 1; // remove chip select
}
Variable Documentation
unsigned char idata _n_sub_addr = 1
Definition at line 43 of file scs_900.c.
float adc[8]
Definition at line 80 of file scs_900.c.
char adc_25
Definition at line 84 of file scs_900.c.
unsigned char adc_chn = 0
Definition at line 123 of file scs_900.c.
Referenced by adc_read(), user_init(), and user_loop().
sbit ADC_DIN = P1 ^ 7
Definition at line 52 of file scs_900.c.
sbit ADC_DOUT = P1 ^ 6
Definition at line 51 of file scs_900.c.
unsigned char code adc_index[8] = {6, 7, 0, 1, 2, 3, 4, 5}
Definition at line 386 of file scs_900.c.
sbit ADC_NCS = P1 ^ 4
Definition at line 49 of file scs_900.c.
sbit ADC_NRDY = P1 ^ 5
Definition at line 50 of file scs_900.c.
sbit ADC_NRES = P1 ^ 2
Definition at line 47 of file scs_900.c.
sbit ADC_P1 = P1 ^ 1
Definition at line 46 of file scs_900.c.
sbit ADC_SCLK = P1 ^ 3
Definition at line 48 of file scs_900.c.
float dac[8]
Definition at line 81 of file scs_900.c.
sbit DAC_CLR = P0 ^ 5
Definition at line 57 of file scs_900.c.
sbit DAC_DIN = P0 ^ 7
Definition at line 59 of file scs_900.c.
sbit DAC_DOUT = P0 ^ 6
Definition at line 58 of file scs_900.c.
unsigned char code dac_index[8] = {4, 5, 2, 3, 1, 0, 7, 6}
Definition at line 237 of file scs_900.c.
sbit DAC_NCS = P0 ^ 3
Definition at line 55 of file scs_900.c.
sbit DAC_SCK = P0 ^ 4
Definition at line 56 of file scs_900.c.
bit DEBUG_MODE
Definition at line 247 of file mscbmain.c.
bit FREEZE_MODE
Definition at line 249 of file mscbmain.c.
char code node_name[] = "SCS-900"
Definition at line 40 of file scs_900.c.
SYS_INFO sys_info
Definition at line 239 of file mscbmain.c.
char uni_adc
Definition at line 83 of file scs_900.c.
sbit UNI_ADC = P0 ^ 2
Definition at line 63 of file scs_900.c.
Referenced by user_init().
char uni_dac
Definition at line 82 of file scs_900.c.
sbit UNI_DAC = P1 ^ 0
Definition at line 62 of file scs_900.c.
Referenced by user_init().
struct { ... } user_data
MSCB_INFO_VAR code variables[]
Initial value:
 {
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "ADC0", &user_data.adc[0],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "ADC1", &user_data.adc[1],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "ADC2", &user_data.adc[2],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "ADC3", &user_data.adc[3],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "ADC4", &user_data.adc[4],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "ADC5", &user_data.adc[5],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "ADC6", &user_data.adc[6],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "ADC7", &user_data.adc[7],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "DAC0", &user_data.dac[0],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "DAC1", &user_data.dac[1],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "DAC2", &user_data.dac[2],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "DAC3", &user_data.dac[3],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "DAC4", &user_data.dac[4],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "DAC5", &user_data.dac[5],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "DAC6", &user_data.dac[6],
   4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "DAC7", &user_data.dac[7],
   1, UNIT_BOOLEAN, 0, 0, 0, "Uni DAC", &user_data.uni_dac,
   1, UNIT_BOOLEAN, 0, 0, 0, "Uni ADC", &user_data.uni_adc,
   1, UNIT_BOOLEAN, 0, 0, 0, "2.5V ADC", &user_data.adc_25,
   0
}
Definition at line 87 of file scs_900.c.