AlcapDAQ: midas/drivers/divers/sis3803.c File Reference
midas/drivers/divers/sis3803.c File Reference
#include "sis3803.h"
Functions
void myStub_sis3803 (void)
INLINE DWORD sis3803_module_ID (const DWORD base_adr)
INLINE void sis3803_module_reset (const DWORD base_adr)
INLINE DWORD sis3803_IRQ_REG_read (const DWORD base_adr)
INLINE DWORD sis3803_IRQ_REG_write (const DWORD base_adr, DWORD irq)
INLINE DWORD sis3803_input_mode (const DWORD base_adr, DWORD mode)
INLINE DWORD sis3803_ref1 (const DWORD base_adr, DWORD endis)
INLINE void sis3803_channel_enable (const DWORD base_adr, DWORD pat)
INLINE void sis3803_channel_disable (const DWORD base_adr, DWORD pat)
INLINE DWORD sis3803_CSR_read (const DWORD base_adr, const DWORD what)
INLINE DWORD sis3803_CSR_write (const DWORD base_adr, const DWORD what)
INLINE void sis3803_all_clear (const DWORD base_adr)
INLINE void sis3803_test_enable (const DWORD base_adr)
INLINE void sis3803_test_disable (const DWORD base_adr)
INLINE void sis3803_all_enable (const DWORD base_adr)
INLINE void sis3803_all_disable (const DWORD base_adr)
INLINE void sis3803_grp1_clear (const DWORD base_adr)
INLINE void sis3803_grp2_clear (const DWORD base_adr)
INLINE void sis3803_single_clear (const DWORD base_adr, const INT ch)
INLINE void sis3803_single_OVFL_clear (const DWORD base_adr, INT ch)
INLINE void sis3803_counter_read (const DWORD base_adr, INT ch, DWORD *pvalue)
INLINE void sis3803_all_read (const DWORD base_adr, DWORD *pvalue)
INLINE void sis3803_grp1_read (const DWORD base_adr, DWORD *pvalue)
INLINE void sis3803_grp2_read (const DWORD base_adr, DWORD *pvalue)
INLINE void sis3803_all_read_clear (const DWORD base_adr, DWORD *pvalue)
INLINE void sis3803_OVFL_grp1_read (const DWORD base_adr, DWORD *reg)
INLINE void sis3803_OVFL_grp2_read (const DWORD base_adr, DWORD *reg)
INLINE void sis3803_int_source_enable (const DWORD base_adr, const int intnum)
INLINE void sis3803_int_source_disable (const DWORD base_adr, const int intnum)
INLINE void sis3803_int_source (const DWORD base_adr, DWORD int_source)
INLINE void sis3803_int_attach (const DWORD base_adr, DWORD base_vect, int level, void(*isr)(void))
INLINE void sis3803_int_detach (const DWORD base_adr, DWORD base_vect, int level)
INLINE void sis3803_int_clear (const DWORD base_adr, const int intnum)
void sis3803_setup (const DWORD base_adr, int mode, int dsp)
void sis3803 (void)
void SIS3803_setup (const DWORD base_adr, int mode)
void SIS3803_CSR_read (const DWORD base_adr)
void SIS3803_all_read (const DWORD base_adr)
void SIS3803_all_read_clear (const DWORD base_adr)
void SIS3803_all_bread (const DWORD base_adr)
void SIS3803_all_bcread (const DWORD base_adr)
void test (DWORD mem)
Variables
DWORD * p = NULL
Function Documentation
void myStub_sis3803 (void)
Definition at line 30 of file sis3803.c.
References sis3803_int_source_disable(), and sis3803_int_source_enable().
Referenced by sis3803_int_detach().
{
   static int sis3803_private_counter = 0;
#ifdef OS_VXWORKS
   sis3803_int_source_disable(0, 0);
   logMsg("sis3803 IRQ#%i served\n", sis3803_private_counter++, 0, 0, 0, 0, 0);
   sis3803_int_source_enable(0, 0);
#endif
}
void sis3803 (void)
Definition at line 799 of file sis3803.c.
        : Display SIS3803 build-in commands
 Input:
    none
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   printf("\n---> SIS 3803 32 MultiScalers (sis3803.c) <---\n");
   printf("Inline : sis3803_module_ID (vmeBase);\n");
   printf("Inline : sis3803_IRQ_REG_read(vmeBase);\n");
   printf("Inline : sis3803_IRQ_REG_write(vmeBase, irq);\n");
   printf("Inline : sis3803_module_reset (vmeBase);\n");
   printf("Inline : sis3803_ref1 (vmeBase, enable/disable);\n");
   printf("Inline : sis3803_channel_enable (vmeBase, pattern);\n");
   printf("Inline : sis3803_channel_disable (vmeBase, pattern);\n");
   printf("Inline : sis3803_CSR_read (vmeBase, what);\n");
   printf("Inline : sis3803_CSR_write (vmeBase, what);\n");
   printf("Inline : sis3803_test_enable(vmeBase);\n");
   printf("Inline : sis3803_test_disable(vmeBase);\n");
   printf("Inline : sis3803_all_clear(vmeBase);\n");
   printf("Inline : sis3803_all_enable(vmeBase);\n");
   printf("Inline : sis3803_all_disable(vmeBase);\n");
   printf("Inline : sis3803_grp1_clear(vmeBase);\n");
   printf("Inline : sis3803_grp2_clear(vmeBase);\n");
   printf("Inline : sis3803_single_clear(vmeBase, ch);\n");
   printf("Inline : sis3803_single_OVFL_clear(vmeBase, ch);\n");
   printf("Inline : sis3803_counter_read(vmeBase, ch, *p);\n");
   printf("Inline : sis3803_all_read(vmeBase, *p);\n");
   printf("Inline : sis3803_grp1_read(vmeBase, *p);\n");
   printf("Inline : sis3803_grp2_read(vmeBase, *p);\n");
   printf("Inline : sis3803_all_read_clear(vmeBase, *p);\n");
   printf("Inline : sis3803_OVFL_grp1_read(vmeBase, *p);\n");
   printf("Inline : sis3803_OVFL_grp2_read(vmeBase, *p);\n");
   printf("Inline : sis3803_int_source (vmeBase, enable/disable);\n");
   printf("Inline : sis3803_int_source_enable (vmeBase, source (0..3));\n");
   printf("Inline : sis3803_int_source_disable (vmeBase, source (0..3));\n");
   printf("Inline : sis3803_int_attach (vmeBase, vect, level, void (*isr)(void));\n");
   printf("Inline : sis3803_int_detach (vmeBase, vect, level);\n");
   printf("Inline : sis3803_int_clear (vmeBase, source (0..3));\n");
   printf("         sis3803_setup(vmeBase, mode, display);\n");
   printf("calls  : SIS3803_setup( base_adr, mode)\n");
   printf("calls  : SIS3803_CSR_read( base_adr)\n");
   printf("calls  : SIS3803_all_read( base_adr) 'sis3803_counter_read()'\n");
   printf("calls  : SIS3803_all_read_clear( base_adr) 'sis3803_single_clear'\n");
   printf("calls  : SIS3803_all_bread( base_adr) 'sis3803_all_read'\n");
   printf("calls  : SIS3803_all_bcread( base_adr) 'sis3803_all_read_clear'\n");
}
void SIS3803_all_bcread (const DWORD base_adr)
Definition at line 914 of file sis3803.c.
References count, i, and sis3803_all_read_clear().
{
   DWORD count[16];
   INT i;
   sis3803_all_read_clear(base_adr, &(count[0]));
   for (i = 0; i < 16; i++) {
      printf("Counter[%i] : %u\n", i, count[i]);
   }
}
void SIS3803_all_bread (const DWORD base_adr)
Definition at line 903 of file sis3803.c.
References count, i, and sis3803_all_read().
{
   DWORD count[16];
   INT i;
   sis3803_all_read(base_adr, &(count[0]));
   for (i = 0; i < 16; i++) {
      printf("Counter[%i] : %u 0x%x\n", i, count[i], count[i]);
   }
}
INLINE void sis3803_all_clear (const DWORD base_adr)
Definition at line 251 of file sis3803.c.
References A32D24, and ALL_CLEAR.
        : Clear all module + overflow bits
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + ALL_CLEAR);
   *spec_adr = 0x0;
}
INLINE void sis3803_all_disable (const DWORD base_adr)
Definition at line 323 of file sis3803.c.
References A32D24, and DISABLE_GBL_COUNT.
        : Disable global counting
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + DISABLE_GBL_COUNT);
   *spec_adr = 0x0;
}
INLINE void sis3803_all_enable (const DWORD base_adr)
Definition at line 305 of file sis3803.c.
References A32D24, and ENABLE_GBL_COUNT.
Referenced by sis3803_setup().
        : Enable global counting
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + ENABLE_GBL_COUNT);
   *spec_adr = 0x0;
}
void SIS3803_all_read (const DWORD base_adr)
Definition at line 880 of file sis3803.c.
References count, i, and sis3803_counter_read().
{
   DWORD count;
   INT i;
   for (i = 0; i < 16; i++) {
      sis3803_counter_read(base_adr, i, &count);
      printf("Counter[%i] : %u\n", i, count);
   }
}
INLINE void sis3803_all_read (const DWORD base_adr, DWORD * pvalue)
Definition at line 439 of file sis3803.c.
References A32D24, COUNTER_READ, and i.
Referenced by SIS3803_all_bread().
        : Reads all 16 channels scaler
 Input:
  DWORD base_addr     : base address of the SIS3803
  DWORD *pvalue       : destination pointer
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   INT i;
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + COUNTER_READ);
   for (i = 0; i < 16; i++) {
      *pvalue++ = *spec_adr++;
   }
}
void SIS3803_all_read_clear (const DWORD base_adr)
Definition at line 891 of file sis3803.c.
References count, i, sis3803_counter_read(), and sis3803_single_clear().
{
   DWORD count;
   INT i;
   for (i = 0; i < 16; i++) {
      sis3803_counter_read(base_adr, i, &count);
      sis3803_single_clear(base_adr, i);
      printf("Counter[%i] : %u\n", i, count);
   }
}
INLINE void sis3803_all_read_clear (const DWORD base_adr, DWORD * pvalue)
Definition at line 505 of file sis3803.c.
References A32D24, COUNTER_READ_CLEAR, and i.
Referenced by SIS3803_all_bcread().
        : Reads & clear all 16 channels scaler
 Input:
  DWORD base_addr     : base address of the SIS3803
  DWORD *pvalue       : destination pointer
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   INT i;
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + COUNTER_READ_CLEAR);
   for (i = 0; i < 16; i++) {
      *pvalue++ = *spec_adr++;
   }
}
INLINE void sis3803_channel_disable (const DWORD base_adr, DWORD pat)
Definition at line 188 of file sis3803.c.
References A32D24, and SELECT_COUNT_DIS_REG.
        : Disable pat channel for acquistion.
          blind command! 0x0..0xffff
 Input:
  DWORD base_addr     : base address of the SIS3803
  DWORD pat           : channel pattern
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + SELECT_COUNT_DIS_REG);
   *spec_adr = pat & 0xffff;
}
INLINE void sis3803_channel_enable (const DWORD base_adr, DWORD pat)
Definition at line 167 of file sis3803.c.
References A32D24, and SELECT_COUNT_DIS_REG.
Referenced by sis3803_setup().
        : Enable pat channel for acquistion.
          blind command! 0x0..0xffff
 Input:
  DWORD base_addr     : base address of the SIS3803
  DWORD pat           : channel pattern
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + SELECT_COUNT_DIS_REG);
   *spec_adr = (~pat & 0xffff);
}
INLINE void sis3803_counter_read (const DWORD base_adr, INT ch, DWORD * pvalue)
Definition at line 417 of file sis3803.c.
References A32D24, and COUNTER_READ.
Referenced by SIS3803_all_read(), and SIS3803_all_read_clear().
        : Reads one individual scaler
 Input:
  DWORD base_addr     : base address of the SIS3803
  INT   ch            : Channel to be read
  DWORD *pvalue       : destination pointer
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   if (ch < 16) {
      spec_adr = (DWORD *) (A32D24 + base_adr + COUNTER_READ + (ch << 2));
      *pvalue = *spec_adr;
   }
}
void SIS3803_CSR_read (const DWORD base_adr)
Definition at line 857 of file sis3803.c.
References csr(), CSR_FULL, IS_GBL_ENABLE, IS_GBL_OVFL, IS_IRQ_BS0, IS_IRQ_BS1, IS_IRQ_BS2, IS_IRQ_EN_BS0, IS_IRQ_EN_BS1, IS_IRQ_EN_BS2, IS_LED, IS_REF1, sis3803_CSR_read(), sis3803_input_mode(), and sis3803_module_ID().
Referenced by sis3803_setup().
{
   DWORD csr;
   csr = sis3803_CSR_read(base_adr, CSR_FULL);
   printf("Module Version   : %d\t", ((sis3803_module_ID(base_adr) & 0xf000) >> 12));
   printf("Module ID        : %4.4x\n", (sis3803_module_ID(base_adr) >> 16));
   printf("LED              : %s \t", (csr & IS_LED) ? "Y" : "N");
   printf("Input mode       : %d \n", sis3803_input_mode(base_adr, 1));
   printf("Reference pulse 1: %s \t", (csr & IS_REF1) ? "Y" : "N");
   printf("Global Enable    : %s \t", (csr & IS_GBL_ENABLE) ? "Y" : "N");
   printf("Global OVFL bit  : %s \n", (csr & IS_GBL_OVFL) ? "Y" : "N");
   printf("IRQ enable BS0   : %s \t", (csr & IS_IRQ_EN_BS0) ? "Y" : "N");
   printf("IRQ enable BS1   : %s \t", (csr & IS_IRQ_EN_BS1) ? "Y" : "N");
   printf("IRQ enable BS2   : %s \n", (csr & IS_IRQ_EN_BS2) ? "Y" : "N");
   printf("IRQ Bit Source 0 : %s \t", (csr & IS_IRQ_BS0) ? "Y" : "N");
   printf("IRQ Bit Source 1 : %s \t", (csr & IS_IRQ_BS1) ? "Y" : "N");
   printf("IRQ Bit Source 2 : %s \n", (csr & IS_IRQ_BS2) ? "Y" : "N");
   printf("internal VME IRQ : %s \t", (csr & 0x4000000) ? "Y" : "N");
   printf("VME IRQ          : %s \n", (csr & 0x8000000) ? "Y" : "N");
}
INLINE DWORD sis3803_CSR_read (const DWORD base_adr, const DWORD what)
Definition at line 208 of file sis3803.c.
References A32D24, CSR_FULL, and CSR_READ.
Referenced by SIS3803_CSR_read(), and sis3803_CSR_write().
        : Read the CSR and return 1/0 based on what.
          except for what == CSR_FULL where it returns current CSR
 Input:
  DWORD base_addr     : base address of the SIS3803
  DWORD what          : bitwise field (see sis3803.h)
 Output:
    none
 Function value:
 DWORD             : CSR 32bit current content
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + CSR_READ);
   if (what == CSR_FULL)
      return *spec_adr;
   else
      return ((*spec_adr & what) ? 1 : 0);
}
INLINE DWORD sis3803_CSR_write (const DWORD base_adr, const DWORD what)
Definition at line 231 of file sis3803.c.
References A32D24, CSR_FULL, CSR_WRITE, and sis3803_CSR_read().
        : Write to the CSR and return CSR_FULL.
 Input:
  DWORD base_addr     : base address of the SIS3803
  DWORD what          : bitwise field
 Output:
    none
 Function value:
 DWORD             : CSR 32bit current content
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + CSR_WRITE);
   *spec_adr = what;
   return sis3803_CSR_read(base_adr, CSR_FULL);
}
INLINE void sis3803_grp1_clear (const DWORD base_adr)
Definition at line 341 of file sis3803.c.
References A32D24, and COUNTER_GRP1_CLEAR.
        : Clear group 1 (1-8) channels + overflow bits
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + COUNTER_GRP1_CLEAR);
   *spec_adr = 0x0;
}
INLINE void sis3803_grp1_read (const DWORD base_adr, DWORD * pvalue)
Definition at line 461 of file sis3803.c.
References A32D24, COUNTER_READ, and i.
        : Reads group 1 (1..8) channels scaler
 Input:
  DWORD base_addr     : base address of the SIS3803
  DWORD *pvalue       : destination pointer
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   INT i;
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + COUNTER_READ);
   for (i = 0; i < 8; i++) {
      *pvalue++ = *spec_adr++;
   }
}
INLINE void sis3803_grp2_clear (const DWORD base_adr)
Definition at line 359 of file sis3803.c.
References A32D24, and COUNTER_GRP2_CLEAR.
        : Clear group 2 (9-16) channels + overflow bits
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + COUNTER_GRP2_CLEAR);
   *spec_adr = 0x0;
}
INLINE void sis3803_grp2_read (const DWORD base_adr, DWORD * pvalue)
Definition at line 483 of file sis3803.c.
References A32D24, COUNTER_GRP2_READ, and i.
        : Reads group 1 (1..8) channels scaler
 Input:
  DWORD base_addr     : base address of the SIS3803
  DWORD *pvalue       : destination pointer
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   INT i;
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + COUNTER_GRP2_READ);
   for (i = 0; i < 8; i++) {
      *pvalue++ = *spec_adr++;
   }
}
INLINE DWORD sis3803_input_mode (const DWORD base_adr, DWORD mode)
Definition at line 117 of file sis3803.c.
References A32D24, CSR_READ, CSR_WRITE, and GET_MODE.
Referenced by SIS3803_CSR_read(), and sis3803_setup().
        : Set input configuration mode (only mode 1 available)
 Input:
  DWORD base_addr     : base address of the SIS3803
  DWORD mode          : Mode 0-3
 Output:
    none
 Function value:
    DWORD             : current mode
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + CSR_WRITE);
   if (mode < 4)
      mode <<= 2;
   *spec_adr = mode;
   spec_adr = (DWORD *) (A32D24 + base_adr + CSR_READ);
   return ((*spec_adr & GET_MODE) >> 2);
}
INLINE void sis3803_int_attach (const DWORD base_adr, DWORD base_vect, int level, void(*)(void) isr)
Definition at line 658 of file sis3803.c.
References A32D24, IRQ_REG, isr, and VME_IRQ_ENABLE.
        : Book an ISR for a bitwise set of interrupt input (0xff).
          The interrupt vector is then the VECTOR_BASE+intnum
 Input:
  DWORD * base_addr      : base address of the sis3803
  DWORD base_vect        : base vector of the module
  int   level            : IRQ level (1..7)
  DWORD isr_routine      : interrupt routine pointer
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   /* disable all IRQ sources */
/*  Should be done but not in attach
  sis3803_int_source(base_adr
                             , DISABLE_IRQ_DI_BS0
                             | DISABLE_IRQ_DI_BS1
                             | DISABLE_IRQ_DI_BS2);
*/
#ifdef OS_VXWORKS
   if ((level < 8) && (level > 0) && (base_vect < 0x100)) {
      spec_adr = (DWORD *) (A32D24 + base_adr + IRQ_REG);
      *spec_adr = (level << 8) | VME_IRQ_ENABLE | base_vect;
      sysIntEnable(level);      /* interrupt level */
   }
   intConnect(INUM_TO_IVEC(base_vect), (VOIDFUNCPTR) isr, 0);
#else
   printf("Not implemented for this OS\n");
#endif
}
INLINE void sis3803_int_clear (const DWORD base_adr, const int intnum)
Definition at line 732 of file sis3803.c.
References A32D24, CSR_WRITE, DISABLE_IRQ_DI_BS0, DISABLE_IRQ_DI_BS1, DISABLE_IRQ_DI_BS2, ENABLE_IRQ_EN_BS0, ENABLE_IRQ_EN_BS1, and ENABLE_IRQ_EN_BS2.
        : Disable the interrupt for the bitwise input intnum (0xff).
          The interrupt vector is then the VECTOR_BASE+intnum
 Input:
  DWORD * base_addr       : base address of the sis3803
  int   * intnum          : interrupt number (input 0..3)
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   DWORD int_source;
   spec_adr = (DWORD *) (A32D24 + base_adr + CSR_WRITE);
   switch (intnum) {
   case 0:
      int_source = DISABLE_IRQ_DI_BS0;
      *spec_adr = int_source;
      int_source = ENABLE_IRQ_EN_BS0;
      *spec_adr = int_source;
      break;
   case 1:
      int_source = DISABLE_IRQ_DI_BS1;
      *spec_adr = int_source;
      int_source = ENABLE_IRQ_EN_BS1;
      *spec_adr = int_source;
      break;
   case 2:
      int_source = DISABLE_IRQ_DI_BS2;
      *spec_adr = int_source;
      int_source = ENABLE_IRQ_EN_BS2;
      *spec_adr = int_source;
      break;
   default:
      logMsg("Unknown interrupt source (%d)\n", int_source, 0, 0, 0, 0, 0);
   }
}
INLINE void sis3803_int_detach (const DWORD base_adr, DWORD base_vect, int level)
Definition at line 697 of file sis3803.c.
References myStub_sis3803().
        : Unbook an ISR for a bitwise set of interrupt input (0xff).
          The interrupt vector is then the VECTOR_BASE+intnum
 Input:
  DWORD * base_addr       : base address of the sis3803
  DWORD base_vect        : base vector of the module
  int   level            : IRQ level (1..7)
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   /* disable all IRQ sources */
/*  Should be done but not in detach
  sis3803_int_source(base_adr   , DISABLE_IRQ_DI_BS0
                    | DISABLE_IRQ_DI_BS1
                    | DISABLE_IRQ_DI_BS2);
*/
#ifdef OS_VXWORKS
/* Suppose to save the default isr before attach but would
 * required isr table in case of multiple IRQ
 * for now restore with myStub()
 */
   intConnect(INUM_TO_IVEC(base_vect), (VOIDFUNCPTR) myStub_sis3803, 0);
   sysIntDisable(level);        /* interrupt level */
#else
   printf("vector : 0x%x\n", base_vect + intnum);
#endif
}
INLINE void sis3803_int_source (const DWORD base_adr, DWORD int_source)
Definition at line 634 of file sis3803.c.
References A32D24, CSR_WRITE, DISABLE_IRQ_DI_BS0, DISABLE_IRQ_DI_BS1, DISABLE_IRQ_DI_BS2, ENABLE_IRQ_EN_BS0, ENABLE_IRQ_EN_BS1, and ENABLE_IRQ_EN_BS2.
        : Enable the one of the 4 interrupt using the
          predefined parameters (see sis3803.h)
 Input:
  DWORD * base_addr       : base address of the sis3803
  DWORD * intnum          : interrupt number (input 0..3)
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + CSR_WRITE);
   int_source &= (ENABLE_IRQ_EN_BS0 | ENABLE_IRQ_EN_BS1
                  | ENABLE_IRQ_EN_BS2
                  | DISABLE_IRQ_DI_BS0 | DISABLE_IRQ_DI_BS1 | DISABLE_IRQ_DI_BS2);
   *spec_adr = int_source;
}
INLINE void sis3803_int_source_disable (const DWORD base_adr, const int intnum)
Definition at line 599 of file sis3803.c.
References A32D24, CSR_WRITE, DISABLE_IRQ_DI_BS0, DISABLE_IRQ_DI_BS1, and DISABLE_IRQ_DI_BS2.
Referenced by myStub_sis3803().
        : Disable the interrupt for the bitwise input intnum (0xff).
          The interrupt vector is then the VECTOR_BASE+intnum
 Input:
  DWORD * base_addr       : base address of the sis3803
  int     level           : IRQ level (1..7)
  int   * intnum          : interrupt number (input 0..3)
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   DWORD int_source;
   spec_adr = (DWORD *) (A32D24 + base_adr + CSR_WRITE);
   switch (intnum) {
   case 0:
      int_source = DISABLE_IRQ_DI_BS0;
      break;
   case 1:
      int_source = DISABLE_IRQ_DI_BS1;
      break;
   case 2:
      int_source = DISABLE_IRQ_DI_BS2;
      break;
   default:
      logMsg("Unknown interrupt source (%d)\n", int_source, 0, 0, 0, 0, 0);
   }
   *spec_adr = int_source;
}
INLINE void sis3803_int_source_enable (const DWORD base_adr, const int intnum)
Definition at line 565 of file sis3803.c.
References A32D24, CSR_WRITE, ENABLE_IRQ_EN_BS0, ENABLE_IRQ_EN_BS1, and ENABLE_IRQ_EN_BS2.
Referenced by myStub_sis3803().
        : Enable the interrupt for the bitwise input intnum (0xff).
          The interrupt vector is then the VECTOR_BASE
 Input:
  DWORD * base_addr       : base address of the sis3803
  DWORD * intnum          : interrupt number (input 0:7)
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   DWORD int_source;
   spec_adr = (DWORD *) (A32D24 + base_adr + CSR_WRITE);
   switch (intnum) {
   case 0:
      int_source = ENABLE_IRQ_EN_BS0;
      break;
   case 1:
      int_source = ENABLE_IRQ_EN_BS1;
      break;
   case 2:
      int_source = ENABLE_IRQ_EN_BS2;
      break;
   default:
      logMsg("Unknown interrupt source (%d)\n", int_source, 0, 0, 0, 0, 0);
   }
   *spec_adr = int_source;
}
INLINE DWORD sis3803_IRQ_REG_read (const DWORD base_adr)
Definition at line 78 of file sis3803.c.
References A32D24, and IRQ_REG.
        : return the lower 12 bits corresponding to
          VME IRQ enable, levels, vector(lower 8bits)
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 DWORD                : 0xE(1)L(3)V(8)
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + IRQ_REG);
   return (*spec_adr & 0xFFF);
}
INLINE DWORD sis3803_IRQ_REG_write (const DWORD base_adr, DWORD irq)
Definition at line 97 of file sis3803.c.
References A32D24, and IRQ_REG.
        : write irq (ELV) to the register and read back
 Input:
  DWORD base_addr     : base address of the SIS3803
  DWORD irq           : reg
 Output:
    none
 Function value:
 DWORD                : 0xE(1)L(3)V(8)
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + IRQ_REG);
   *spec_adr = irq;
   return (*spec_adr & 0xFFF);
}
INLINE DWORD sis3803_module_ID (const DWORD base_adr)
Definition at line 41 of file sis3803.c.
References A32D24, and MODULE_ID.
Referenced by SIS3803_CSR_read().
        : return the Module ID number (I) version (V)
          IRQ level (L) IRQ vector# (BB)
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 DWORD                : 0xIIIIVLBB
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + MODULE_ID);
   return *spec_adr;
}
INLINE void sis3803_module_reset (const DWORD base_adr)
Definition at line 60 of file sis3803.c.
References A32D24, and MODULE_RESET.
Referenced by sis3803_setup().
        : General Module reset
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + MODULE_RESET);
   *spec_adr = 0x0;
}
INLINE void sis3803_OVFL_grp1_read (const DWORD base_adr, DWORD * reg)
Definition at line 527 of file sis3803.c.
References A32D24, and OVERFLOW_REG1_8.
        : Read Overflow reg for group 1 (1-8)
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    reg               : pointer to overflow reg
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + OVERFLOW_REG1_8);
   *reg = *spec_adr;
   *reg >>= 24;
}
INLINE void sis3803_OVFL_grp2_read (const DWORD base_adr, DWORD * reg)
Definition at line 546 of file sis3803.c.
References A32D24, and OVERFLOW_REG9_16.
        : Read Overflow reg for group 2 (9-16)
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    reg               : pointer to overflow reg
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + OVERFLOW_REG9_16);
   *reg = *spec_adr;
   *reg >>= 24;
}
INLINE DWORD sis3803_ref1 (const DWORD base_adr, DWORD endis)
Definition at line 140 of file sis3803.c.
References A32D24, CSR_READ, DISABLE_REF_CH1, ENABLE_REF_CH1, and IS_REF1.
        : Enable/Disable Reference on Channel 1
 Input:
  DWORD base_addr     : base address of the SIS3803
  DWORD endis         : action either ENABLE_REF_CH1
                                      DISABLE_REF_CH1
 Output:
    none
 Function value:
               : status of the ref1 1=enable, 0=disable
\**************************************************************/
{
   volatile DWORD *spec_adr;
   if ((endis == ENABLE_REF_CH1) || (endis == DISABLE_REF_CH1)) {
      spec_adr = (DWORD *) (A32D24 + base_adr + endis);
      *spec_adr = 0x0;
   } else
      printf("sis3803_ref1: unknown command %d\n", endis);
   /* read back the status */
   spec_adr = (DWORD *) (A32D24 + base_adr + CSR_READ);
   return ((*spec_adr & IS_REF1) ? 1 : 0);
}
void SIS3803_setup (const DWORD base_adr, int mode)
Definition at line 852 of file sis3803.c.
References sis3803_setup().
{
   sis3803_setup(base_adr, mode, 1);
}
void sis3803_setup (const DWORD base_adr, int mode, int dsp)
Definition at line 774 of file sis3803.c.
References sis3803_all_enable(), sis3803_channel_enable(), SIS3803_CSR_read(), sis3803_input_mode(), and sis3803_module_reset().
Referenced by SIS3803_setup().
{
   switch (mode) {
   case 1:
      /* */
      if (dsp) {
         printf("Setting          : %d \t", mode);
         printf("Info             : PAA/June 2000\n");
      }
      sis3803_module_reset(base_adr);
      sis3803_input_mode(base_adr, 1);  /* mode 1 ONLY */
      sis3803_all_enable(base_adr);
      sis3803_channel_enable(base_adr, 0xf);    /* 4 channels */
      if (dsp)
         SIS3803_CSR_read(base_adr);
      if (dsp)
         printf("# of active ch.  : 4\n");
      break;
   default:
      printf("Undefined mode %d (known mode :1, 2, 3, 4, 5)\n", mode);
      break;
   }
}
INLINE void sis3803_single_clear (const DWORD base_adr, const INT ch)
Definition at line 377 of file sis3803.c.
References A32D24, and COUNTER_CLEAR.
Referenced by SIS3803_all_read_clear().
        : Clear single scaler channels + overflow bits
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   if (ch < 16) {
      spec_adr = (DWORD *) (A32D24 + base_adr + COUNTER_CLEAR + (ch << 2));
      *spec_adr = 0x0;
   }
}
INLINE void sis3803_single_OVFL_clear (const DWORD base_adr, INT ch)
Definition at line 397 of file sis3803.c.
References A32D24, and OVERFLOW_CLEAR.
        : Clear single scaler channels + overflow bits
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   if (ch < 16) {
      spec_adr = (DWORD *) (A32D24 + base_adr + OVERFLOW_CLEAR + (ch << 2));
      *spec_adr = 0x0;
   }
}
INLINE void sis3803_test_disable (const DWORD base_adr)
Definition at line 287 of file sis3803.c.
References A32D24, CSR_WRITE, and DISABLE_TEST_PULSE.
        : Disable test pulse and input test
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + CSR_WRITE);
   *spec_adr = DISABLE_TEST_PULSE;
}
INLINE void sis3803_test_enable (const DWORD base_adr)
Definition at line 269 of file sis3803.c.
References A32D24, CSR_WRITE, and ENABLE_TEST_PULSE.
        : Enable test pulse and input test
 Input:
  DWORD base_addr     : base address of the SIS3803
 Output:
    none
 Function value:
 none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr + CSR_WRITE);
   *spec_adr = ENABLE_TEST_PULSE;
}
void test (DWORD mem)
Definition at line 927 of file sis3803.c.
{
   PART_ID part_id;
   if (p != NULL)
      free(p);
   (char *) p = malloc(mem);
}
Variable Documentation
DWORD* p = NULL
Definition at line 925 of file sis3803.c.
Referenced by cm_msg_retrieve(), cmd_loop(), cnafsub(), command_loop(), condition_test(), create_password(), decode(), decode_get(), decode_line(), decode_post(), display_kumac(), eeprom_erase(), eeprom_read(), eeprom_write(), el_retrieve(), el_submit(), enumcfg(), epics_ca_init(), fb_read_data_memory(), FillCoincidenceTimeHistogram(), format(), format1(), gdImageBrushApply(), gdImageFill(), gdImageSetPixel(), gdImageTileApply(), generate_hist_graph(), getcfg(), interprete(), LoadCorrectionTables(), lrs1445a_get(), lrs1454_get(), lrs1454_get_all(), lrs1454_get_current(), lrs1454_get_current_all(), main(), mchart_get_names(), mcstd_func(), new_fadc_read(), parport_poll_live(), print_key_info(), MakeTemplate::ProcessEntry(), rpc_client_accept(), rpc_convert_data(), rpc_get_option(), rsputs2(), search_callback(), sendmail(), server_loop(), setup(), sgets(), show_create_page(), show_custom_page(), show_elog_new(), show_odb_page(), show_rawfile(), show_set_page(), ss_gets(), ss_shm_open(), submit_elog(), urlEncode(), vme_read_d16(), vme_read_d32(), vme_read_d8(), vme_write_d16(), vme_write_d32(), vme_write_d8(), and xml_encode().