AlcapDAQ: TRANS_TABLE Struct Reference
TRANS_TABLE Struct Reference
[The midas.h & midas.c]
Data Fields
INT transition
INT sequence_number
INT(* func)(INT, char *)
Detailed Description
Definition at line 840 of file midas.c.
Field Documentation
INT(* TRANS_TABLE::func)(INT, char *)
Referenced by cm_register_deferred_transition(), cm_register_transition(), cm_transition(), and rpc_transition_dispatch().
INT TRANS_TABLE::sequence_number
Definition at line 842 of file midas.c.
Referenced by cm_register_transition(), and rpc_transition_dispatch().
INT TRANS_TABLE::transition
Definition at line 841 of file midas.c.
Referenced by cm_check_deferred_transition(), cm_register_deferred_transition(), cm_register_transition(), and cm_transition().
The documentation for this struct was generated from the following file:
midas/src/midas.c