AlcapDAQ: readout_module Struct Reference
readout_module Struct Reference
#include <crate.h>
Data Fields
INT(* init)()
void(* exit)()
INT(* pre_bor)()
INT(* bor)()
INT(* eor)()
INT(* poll_live)()
INT(* poll_dead)()
INT(* start_cycle)()
INT(* stop_cycle)()
INT(* read)(char *pevent)
Detailed Description
Definition at line 13 of file crate.h.
Field Documentation
INT(* readout_module::bor)()
Definition at line 25 of file crate.h.
Referenced by begin_of_run().
INT(* readout_module::eor)()
Definition at line 28 of file crate.h.
Referenced by end_of_run().
void(* readout_module::exit)()
Definition at line 19 of file crate.h.
Referenced by frontend_exit().
INT(* readout_module::init)()
Definition at line 16 of file crate.h.
Referenced by frontend_init().
INT(* readout_module::poll_dead)()
Definition at line 34 of file crate.h.
INT(* readout_module::poll_live)()
Definition at line 31 of file crate.h.
INT(* readout_module::pre_bor)()
Definition at line 22 of file crate.h.
Referenced by pre_begin_of_run().
INT(* readout_module::read)(char *pevent)
Definition at line 43 of file crate.h.
INT(* readout_module::start_cycle)()
Definition at line 37 of file crate.h.
INT(* readout_module::stop_cycle)()
Definition at line 40 of file crate.h.
The documentation for this struct was generated from the following files:
crate3/crate.h
crate4_CAEN_V1724/crate.h
crate5_CAEN_DT5720/crate.h
crate6_CAEN_TDC/crate.h
crate9/crate.h