AlcapDAQ: REQUEST_LIST Struct Reference
REQUEST_LIST Struct Reference
[System Structure Declaration]
#include <msystem.h>
Data Fields
INT buffer_handle
short int event_id
short int trigger_mask
void(* dispatcher)(HNDLE, HNDLE, EVENT_HEADER *, void *)
Detailed Description
Definition at line 549 of file msystem.h.
Field Documentation
INT REQUEST_LIST::buffer_handle
Definition at line 550 of file msystem.h.
Referenced by bm_request_event().
void(* REQUEST_LIST::dispatcher)(HNDLE, HNDLE, EVENT_HEADER *, void *)
Referenced by bm_poll_event(), bm_push_event(), and bm_request_event().
short int REQUEST_LIST::event_id
Definition at line 551 of file msystem.h.
Referenced by bm_request_event().
short int REQUEST_LIST::trigger_mask
Definition at line 552 of file msystem.h.
Referenced by bm_request_event().
The documentation for this struct was generated from the following file:
midas/include/msystem.h