AlcapDAQ: Algorithm::Pedestal_iterator< InputIterator > Struct Template Reference
Algorithm::Pedestal_iterator< InputIterator > Struct Template Reference
#include <Convolver.h>
Public Types
typedef std::pair
< TH1_c_iterator,
TH1_c_iterator > HistIter
typedef std::vector< HistIter > HistList
Public Member Functions
Pedestal_iterator (const InputIterator &it, double ped)
Pedestal_iterator (const InputIterator &it)
double operator* () const
double GetPedestal () const
void operator++ ()
void AddHistogram (TH1 *hist, double scale, int shift)
Private Attributes
double fPedestal
HistList fHistograms
Detailed Description
template<typename InputIterator>
struct Algorithm::Pedestal_iterator< InputIterator >
Definition at line 88 of file Convolver.h.
Member Typedef Documentation
template<typename InputIterator > typedef std::pair<TH1_c_iterator, TH1_c_iterator> Algorithm::Pedestal_iterator< InputIterator >::HistIter
Definition at line 89 of file Convolver.h.
template<typename InputIterator > typedef std::vector<HistIter> Algorithm::Pedestal_iterator< InputIterator >::HistList
Definition at line 90 of file Convolver.h.
Constructor & Destructor Documentation
template<typename InputIterator > Algorithm::Pedestal_iterator< InputIterator >::Pedestal_iterator (const InputIterator & it, double ped) [inline]
Definition at line 91 of file Convolver.h.
:InputIterator(it),fPedestal(ped){}
template<typename InputIterator > Algorithm::Pedestal_iterator< InputIterator >::Pedestal_iterator (const InputIterator & it) [inline]
Definition at line 92 of file Convolver.h.
:InputIterator(it),fPedestal(0){}
Member Function Documentation
template<typename InputIterator > void Algorithm::Pedestal_iterator< InputIterator >::AddHistogram (TH1 * hist, double scale, int shift) [inline]
Definition at line 114 of file Convolver.h.
References Algorithm::TH1_wrapper::begin(), Algorithm::TH1_wrapper::end(), and Algorithm::Pedestal_iterator< InputIterator >::fHistograms.
{
       TH1_wrapper wrap(hist, scale);
       fHistograms.push_back(std::make_pair(wrap.begin(shift), wrap.end()));
     }
template<typename InputIterator > double Algorithm::Pedestal_iterator< InputIterator >::GetPedestal () const [inline]
Definition at line 96 of file Convolver.h.
References Algorithm::Pedestal_iterator< InputIterator >::fPedestal.
Referenced by TemplateConvolver::FindAllPeaks(), TemplateConvolver::FindBestPeak(), and Algorithm::Pedestal_iterator< InputIterator >::operator*().
{
        double val=fPedestal;
        //for(HistList::const_iterator i_hist=fHistograms.begin(); i_hist!=fHistograms.end(); ++i_hist){
        //   val+=*(i_hist->first);
        //}
       return val;
     }
template<typename InputIterator > double Algorithm::Pedestal_iterator< InputIterator >::operator* () const [inline]
Definition at line 93 of file Convolver.h.
References Algorithm::Pedestal_iterator< InputIterator >::GetPedestal().
{
        return InputIterator::operator*() - GetPedestal();
     }
template<typename InputIterator > void Algorithm::Pedestal_iterator< InputIterator >::operator++ () [inline]
Definition at line 103 of file Convolver.h.
References Algorithm::Pedestal_iterator< InputIterator >::fHistograms.
                      {
        InputIterator::operator++();
        for(HistList::iterator i_hist=fHistograms.begin(); i_hist!=fHistograms.end(); ){
           ++(i_hist->first);
           if( i_hist->first == i_hist->second ){
             fHistograms.erase(i_hist);
             continue;
           }
           ++i_hist;
        }
     }
Member Data Documentation
template<typename InputIterator > HistList Algorithm::Pedestal_iterator< InputIterator >::fHistograms [private]
Definition at line 121 of file Convolver.h.
Referenced by Algorithm::Pedestal_iterator< InputIterator >::AddHistogram(), and Algorithm::Pedestal_iterator< InputIterator >::operator++().
template<typename InputIterator > double Algorithm::Pedestal_iterator< InputIterator >::fPedestal [private]
Definition at line 120 of file Convolver.h.
Referenced by Algorithm::Pedestal_iterator< InputIterator >::GetPedestal().
The documentation for this struct was generated from the following file:
rootana/src/TAP_generators/template_fitting/Convolver.h