AlcapDAQ: Algorithm::MaxBinAmplitude Struct Reference
Algorithm::MaxBinAmplitude Struct Reference
#include <TAPAlgorithms.h>
Public Member Functions
MaxBinAmplitude (double ped, int trig_pol)
double operator() (const TPulseIsland *tpi) const
double GetTime () const
double GetAmplitude () const
Public Attributes
const int trigger_polarity
const double pedestal
Private Attributes
double time
double amplitude
Detailed Description
Definition at line 17 of file TAPAlgorithms.h.
Constructor & Destructor Documentation
Algorithm::MaxBinAmplitude::MaxBinAmplitude (double ped, int trig_pol) [inline]
Definition at line 19 of file TAPAlgorithms.h.
      :trigger_polarity(trig_pol), pedestal(ped){}
Member Function Documentation
double Algorithm::MaxBinAmplitude::GetAmplitude () const [inline]
Definition at line 23 of file TAPAlgorithms.h.
References amplitude.
Referenced by IntegralRatioAPGenerator::ProcessPulses().
{return amplitude;}
double Algorithm::MaxBinAmplitude::GetTime () const [inline]
Definition at line 22 of file TAPAlgorithms.h.
References time.
Referenced by TemplateFitAPGenerator::ProcessPulses(), and IntegralRatioAPGenerator::ProcessPulses().
{return time;}
double Algorithm::MaxBinAmplitude::operator() (const TPulseIsland * tpi) const
Definition at line 12 of file TAPAlgorithms.cpp.
References amplitude, TPulseIsland::GetSamples(), pedestal, time, and trigger_polarity.
{
  // Get the samples and get an iterator ready to find the peak sample
  const std::vector<int>& pulseSamples = tpi->GetSamples();
  std::vector<int>::const_iterator peak_sample_pos;
  // Find the position of the peak samples
  if (trigger_polarity == 1)
    peak_sample_pos = std::max_element(pulseSamples.begin(), pulseSamples.end());
  else if (trigger_polarity == -1)
    peak_sample_pos = std::min_element(pulseSamples.begin(), pulseSamples.end());
  // Now calculate the amplitude
  amplitude = trigger_polarity*(*peak_sample_pos - pedestal);
  time = peak_sample_pos- pulseSamples.begin();
  return amplitude;
}
Member Data Documentation
double Algorithm::MaxBinAmplitude::amplitude [mutable, private]
Definition at line 29 of file TAPAlgorithms.h.
Referenced by GetAmplitude(), and operator()().
const double Algorithm::MaxBinAmplitude::pedestal
Definition at line 26 of file TAPAlgorithms.h.
Referenced by operator()().
double Algorithm::MaxBinAmplitude::time [mutable, private]
Definition at line 28 of file TAPAlgorithms.h.
Referenced by GetTime(), and operator()().
const int Algorithm::MaxBinAmplitude::trigger_polarity
Definition at line 25 of file TAPAlgorithms.h.
Referenced by operator()().
The documentation for this struct was generated from the following files:
rootana/src/TAP_generators/utils/TAPAlgorithms.h
rootana/src/TAP_generators/utils/TAPAlgorithms.cpp