AlcapDAQ: Algorithm::IntegralRatio Struct Reference
Algorithm::IntegralRatio Struct Reference
#include <TAPAlgorithms.h>
Public Member Functions
IntegralRatio (int begin, int tail, int end, int trig_pol, double ped=0.)
double operator() (const TPulseIsland *tpi)
double GetRatio () const
double GetTotal () const
double GetTail () const
void SetTailStart (int v)
void SetPedestal (double v)
void SetPedestalToMinimum (const TPulseIsland *tpi)
Private Attributes
Algorithm::SimpleIntegral fTailIntegrator
Algorithm::SimpleIntegral fHeadIntegrator
double fTail
double fHead
Detailed Description
Definition at line 86 of file TAPAlgorithms.h.
Constructor & Destructor Documentation
Algorithm::IntegralRatio::IntegralRatio (int begin, int tail, int end, int trig_pol, double ped = 0.) [inline]
Definition at line 87 of file TAPAlgorithms.h.
    :fTailIntegrator(ped,trig_pol,tail,end)
     ,fHeadIntegrator(ped,trig_pol,begin,tail){
     }
Member Function Documentation
double Algorithm::IntegralRatio::GetRatio () const [inline]
Definition at line 93 of file TAPAlgorithms.h.
References fHead, and fTail.
Referenced by operator()(), TemplateFitAPGenerator::PassesIntegralRatio(), TemplateConvolveAPGenerator::PassesIntegralRatio(), and IntegralRatioAPGenerator::ProcessPulses().
{return fTail/(fHead+fTail);}
double Algorithm::IntegralRatio::GetTail () const [inline]
Definition at line 95 of file TAPAlgorithms.h.
References fTail.
Referenced by IntegralRatioAPGenerator::ProcessPulses().
{return fTail;}
double Algorithm::IntegralRatio::GetTotal () const [inline]
Definition at line 94 of file TAPAlgorithms.h.
References fHead, and fTail.
Referenced by TemplateFitAPGenerator::PassesIntegralRatio(), TemplateConvolveAPGenerator::PassesIntegralRatio(), and IntegralRatioAPGenerator::ProcessPulses().
{return fHead+fTail;}
double Algorithm::IntegralRatio::operator() (const TPulseIsland * tpi)
Definition at line 90 of file TAPAlgorithms.cpp.
References fHead, fHeadIntegrator, fTail, fTailIntegrator, and GetRatio().
{
     fHead=fHeadIntegrator(tpi);
     fTail=fTailIntegrator(tpi);
     return GetRatio();
  }
void Algorithm::IntegralRatio::SetPedestal (double v) [inline]
Definition at line 98 of file TAPAlgorithms.h.
References fHeadIntegrator, fTailIntegrator, and Algorithm::SimpleIntegral::SetPedestal().
Referenced by SetPedestalToMinimum().
{ fTailIntegrator.SetPedestal(v); fHeadIntegrator.SetPedestal(v);}
void Algorithm::IntegralRatio::SetPedestalToMinimum (const TPulseIsland * tpi)
Definition at line 86 of file TAPAlgorithms.cpp.
References TPulseIsland::GetSamples(), and SetPedestal().
Referenced by TemplateFitAPGenerator::PassesIntegralRatio(), TemplateConvolveAPGenerator::PassesIntegralRatio(), and IntegralRatioAPGenerator::ProcessPulses().
{
     SetPedestal(*std::min_element(tpi->GetSamples().begin(), tpi->GetSamples().end()));
}
void Algorithm::IntegralRatio::SetTailStart (int v) [inline]
Definition at line 97 of file TAPAlgorithms.h.
References fHeadIntegrator, fTailIntegrator, Algorithm::SimpleIntegral::SetStart(), and Algorithm::SimpleIntegral::SetStop().
Referenced by IntegralRatioAPGenerator::ProcessPulses().
{ fTailIntegrator.SetStart(v); fHeadIntegrator.SetStop(v);}
Member Data Documentation
double Algorithm::IntegralRatio::fHead [private]
Definition at line 105 of file TAPAlgorithms.h.
Referenced by GetRatio(), GetTotal(), and operator()().
Algorithm::SimpleIntegral Algorithm::IntegralRatio::fHeadIntegrator [private]
Definition at line 103 of file TAPAlgorithms.h.
Referenced by operator()(), SetPedestal(), and SetTailStart().
double Algorithm::IntegralRatio::fTail [private]
Definition at line 104 of file TAPAlgorithms.h.
Referenced by GetRatio(), GetTail(), GetTotal(), and operator()().
Algorithm::SimpleIntegral Algorithm::IntegralRatio::fTailIntegrator [private]
Definition at line 102 of file TAPAlgorithms.h.
Referenced by operator()(), SetPedestal(), and SetTailStart().
The documentation for this struct was generated from the following files:
rootana/src/TAP_generators/utils/TAPAlgorithms.h
rootana/src/TAP_generators/utils/TAPAlgorithms.cpp