AlcapDAQ: midas/drivers/bus/tcpip.c File Reference
midas/drivers/bus/tcpip.c File Reference
#include "midas.h"
#include "msystem.h"
Data Structures
struct TCPIP_SETTINGS
struct TCPIP_INFO
Defines
#define TCPIP_SETTINGS_STR "\Host = STRING : [256] myhost.my.domain\n\Port = INT : 23\n\Debug = INT : 0\n\"
Functions
void tcpip_debug (TCPIP_INFO *info, char *dbg_str)
int tcpip_open (char *host, int port)
int tcpip_exit (TCPIP_INFO *info)
int tcpip_write (TCPIP_INFO *info, char *data, int size)
int tcpip_read (TCPIP_INFO *info, char *data, int size, int millisec)
int tcpip_puts (TCPIP_INFO *info, char *str)
int tcpip_gets (TCPIP_INFO *info, char *str, int size, char *pattern, int millisec)
int tcpip_init (HNDLE hkey, void **pinfo)
INT tcpip (INT cmd,...)
Variables
static int debug_last = 0
static int debug_first = TRUE
Define Documentation
#define TCPIP_SETTINGS_STR "\Host = STRING : [256] myhost.my.domain\n\Port = INT : 23\n\Debug = INT : 0\n\"
Definition at line 44 of file tcpip.c.
Referenced by tcpip_init().
Function Documentation
INT tcpip (INT cmd, ...)
Definition at line 366 of file tcpip.c.
References CMD_DEBUG, CMD_EXIT, CMD_GETS, CMD_INIT, CMD_NAME, CMD_PUTS, CMD_READ, CMD_WRITE, FE_SUCCESS, size, status, tcpip_exit(), tcpip_gets(), tcpip_init(), tcpip_puts(), tcpip_read(), tcpip_write(), and timeout.
{
   va_list argptr;
   HNDLE hkey;
   INT status, size, timeout;
   void *info;
   char *str, *pattern;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hkey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      status = tcpip_init(hkey, info);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = tcpip_exit(info);
      break;
   case CMD_NAME:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      strcpy(str, "tcpip");
      break;
   case CMD_WRITE:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, int);
      status = tcpip_write(info, str, size);
      break;
   case CMD_READ:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, INT);
      timeout = va_arg(argptr, INT);
      status = tcpip_read(info, str, size, timeout);
      break;
   case CMD_PUTS:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      status = tcpip_puts(info, str);
      break;
   case CMD_GETS:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, INT);
      pattern = va_arg(argptr, char *);
      timeout = va_arg(argptr, INT);
      status = tcpip_gets(info, str, size, pattern, timeout);
      break;
   case CMD_DEBUG:
      info = va_arg(argptr, void *);
      status = va_arg(argptr, INT);
      ((TCPIP_INFO *) info)->settings.debug = status;
      break;
   }
   va_end(argptr);
   return status;
}
void tcpip_debug (TCPIP_INFO * info, char * dbg_str)
Definition at line 57 of file tcpip.c.
References TCPIP_SETTINGS::debug, debug_first, debug_last, FALSE, TCPIP_INFO::settings, and ss_millitime().
Referenced by tcpip_gets(), tcpip_puts(), tcpip_read(), and tcpip_write().
{
   FILE *f;
   int delta;
   if (debug_last == 0)
      delta = 0;
   else
      delta = ss_millitime() - debug_last;
   debug_last = ss_millitime();
   f = fopen("tcpip.log", "a");
   if (debug_first)
      fprintf(f, "\n==== new session =============\n\n");
   debug_first = FALSE;
   fprintf(f, "{%d} %s\n", delta, dbg_str);
   if (info->settings.debug > 1)
      printf("{%d} %s\n", delta, dbg_str);
   fclose(f);
}
int tcpip_exit (TCPIP_INFO * info)
Definition at line 160 of file tcpip.c.
References closesocket, TCPIP_INFO::fd, and SUCCESS.
Referenced by tcpip().
{
   closesocket(info->fd);
   return SUCCESS;
}
int tcpip_gets (TCPIP_INFO * info, char * str, int size, char * pattern, int millisec)
Definition at line 271 of file tcpip.c.
References TCPIP_SETTINGS::debug, TCPIP_INFO::fd, FD_SETSIZE, i, n, TCPIP_INFO::settings, status, tcpip_debug(), and WATCHDOG_INTERVAL.
Referenced by tcpip().
{
   fd_set readfds;
   struct timeval timeout;
   int i, status, n;
   n = 0;
   memset(str, 0, size);
   do {
      if (millisec > 0) {
         FD_ZERO(&readfds);
         FD_SET(info->fd, &readfds);
         timeout.tv_sec = millisec / 1000;
         timeout.tv_usec = (millisec % 1000) * 1000;
         do {
            status = select(FD_SETSIZE, (void *) &readfds, NULL, NULL, (void *) &timeout);
            /* if an alarm signal was cought, restart select with reduced timeout */
            if (status == -1 && timeout.tv_sec >= WATCHDOG_INTERVAL / 1000)
               timeout.tv_sec -= WATCHDOG_INTERVAL / 1000;
         } while (status == -1);        /* dont return if an alarm signal was cought */
         if (!FD_ISSET(info->fd, &readfds))
            break;
      }
      i = recv(info->fd, str + n, 1, 0);
      if (i <= 0)
         break;
      n += i;
      if (pattern && pattern[0])
         if (strstr(str, pattern) != NULL)
            break;
      if (n >= size)
         break;
   } while (1);                 /* while (buffer[n-1] && buffer[n-1] != 10); */
   if (info->settings.debug) {
      char dbg_str[256];
      sprintf(dbg_str, "gets [%s]: ", pattern);
      if (str[0] == 0)
         sprintf(dbg_str + strlen(dbg_str), "<TIMEOUT>");
      else
         sprintf(dbg_str + strlen(dbg_str), "%s", str);
      tcpip_debug(info, dbg_str);
   }
   return n;
}
int tcpip_init (HNDLE hkey, void ** pinfo)
Definition at line 335 of file tcpip.c.
References cm_get_experiment_database(), db_create_record(), db_find_key(), db_get_record(), DB_SUCCESS, TCPIP_INFO::fd, FE_ERR_HW, FE_ERR_ODB, hDB, TCPIP_SETTINGS::host, TCPIP_SETTINGS::port, TCPIP_INFO::settings, size, status, SUCCESS, tcpip_open(), and TCPIP_SETTINGS_STR.
Referenced by tcpip().
{
   HNDLE hDB, hkeybd;
   INT size, status;
   TCPIP_INFO *info;
   /* allocate info structure */
   info = calloc(1, sizeof(TCPIP_INFO));
   *pinfo = info;
   cm_get_experiment_database(&hDB, NULL);
   /* create TCPIP settings record */
   status = db_create_record(hDB, hkey, "BD", TCPIP_SETTINGS_STR);
   if (status != DB_SUCCESS)
      return FE_ERR_ODB;
   db_find_key(hDB, hkey, "BD", &hkeybd);
   size = sizeof(info->settings);
   db_get_record(hDB, hkeybd, &info->settings, &size, 0);
   /* open port */
   info->fd = tcpip_open(info->settings.host, info->settings.port);
   if (info->fd < 0)
      return FE_ERR_HW;
   return SUCCESS;
}
int tcpip_open (char * host, int port)
Definition at line 83 of file tcpip.c.
References RPC_NET_ERROR, and status.
Referenced by tcpip_init().
{
   struct sockaddr_in bind_addr;
   struct hostent *phe;
   int status, fd;
#ifdef OS_WINNT
   {
      WSADATA WSAData;
      /* Start windows sockets */
      if (WSAStartup(MAKEWORD(1, 1), &WSAData) != 0)
         return RPC_NET_ERROR;
   }
#endif
   /* create a new socket for connecting to remote server */
   fd = socket(AF_INET, SOCK_STREAM, 0);
   if (fd == -1) {
      perror("tcpip_open: socket");
      return fd;
   }
   /* let OS choose any port number */
   memset(&bind_addr, 0, sizeof(bind_addr));
   bind_addr.sin_family = AF_INET;
   bind_addr.sin_addr.s_addr = 0;
   bind_addr.sin_port = 0;
   status = bind(fd, (void *) &bind_addr, sizeof(bind_addr));
   if (status < 0) {
      perror("tcpip_open:bind");
      return fd;
   }
   /* connect to remote node */
   memset(&bind_addr, 0, sizeof(bind_addr));
   bind_addr.sin_family = AF_INET;
   bind_addr.sin_addr.s_addr = 0;
   bind_addr.sin_port = htons((short) port);
#ifdef OS_VXWORKS
   {
      INT host_addr;
      host_addr = hostGetByName(host);
      memcpy((char *) &(bind_addr.sin_addr), &host_addr, 4);
   }
#else
   phe = gethostbyname(host);
   if (phe == NULL) {
      printf("\ntcpip_open: unknown host name %s\n", host);
      return fd;
   }
   memcpy((char *) &(bind_addr.sin_addr), phe->h_addr, phe->h_length);
#endif
#ifdef OS_UNIX
   do {
      status = connect(fd, (void *) &bind_addr, sizeof(bind_addr));
      /* don't return if an alarm signal was cought */
   } while (status == -1 && errno == EINTR);
#else
   status = connect(fd, (void *) &bind_addr, sizeof(bind_addr));
#endif
   if (status != 0) {
      perror("tcpip_open:connect");
      return -1;
   }
   return fd;
}
int tcpip_puts (TCPIP_INFO * info, char * str)
Definition at line 251 of file tcpip.c.
References TCPIP_SETTINGS::debug, TCPIP_INFO::fd, i, send(), TCPIP_INFO::settings, and tcpip_debug().
Referenced by tcpip().
{
   int i;
   if (info->settings.debug) {
      char dbg_str[256];
      sprintf(dbg_str, "puts: %s", str);
      tcpip_debug(info, dbg_str);
   }
   i = send(info->fd, str, strlen(str), 0);
   if (i < 0)
      perror("tcpip_puts");
   return i;
}
int tcpip_read (TCPIP_INFO * info, char * data, int size, int millisec)
Definition at line 190 of file tcpip.c.
References TCPIP_SETTINGS::debug, TCPIP_INFO::fd, FD_SETSIZE, i, n, TCPIP_INFO::settings, status, tcpip_debug(), and WATCHDOG_INTERVAL.
Referenced by tcpip().
{
   fd_set readfds;
   struct timeval timeout;
   int i, status, n;
   n = 0;
   memset(data, 0, size);
   do {
      if (millisec > 0) {
         FD_ZERO(&readfds);
         FD_SET(info->fd, &readfds);
         timeout.tv_sec = millisec / 1000;
         timeout.tv_usec = (millisec % 1000) * 1000;
         do {
            status = select(FD_SETSIZE, (void *) &readfds, NULL, NULL, (void *) &timeout);
            /* if an alarm signal was cought, restart select with reduced timeout */
            if (status == -1 && timeout.tv_sec >= WATCHDOG_INTERVAL / 1000)
               timeout.tv_sec -= WATCHDOG_INTERVAL / 1000;
         } while (status == -1);        /* dont return if an alarm signal was cought */
         if (!FD_ISSET(info->fd, &readfds))
            break;
      }
      i = recv(info->fd, data + n, 1, 0);
      if (i <= 0)
         break;
      n++;
      if (n >= size)
         break;
   } while (1);                 /* while (buffer[n-1] && buffer[n-1] != 10); */
   if (info->settings.debug) {
      char dbg_str[256];
      sprintf(dbg_str, "read: ");
      if (n == 0)
         sprintf(dbg_str + strlen(dbg_str), "<TIMEOUT>");
      else
         for (i = 0; i < n; i++)
            sprintf(dbg_str + strlen(dbg_str), "%X ", data[i]);
      tcpip_debug(info, dbg_str);
   }
   return n;
}
int tcpip_write (TCPIP_INFO * info, char * data, int size)
Definition at line 169 of file tcpip.c.
References TCPIP_SETTINGS::debug, TCPIP_INFO::fd, i, send(), TCPIP_INFO::settings, and tcpip_debug().
Referenced by tcpip().
{
   int i;
   if (info->settings.debug) {
      char dbg_str[256];
      sprintf(dbg_str, "write: ");
      for (i = 0; (int) i < size; i++)
         sprintf(dbg_str + strlen(dbg_str), "%X ", data[i]);
      tcpip_debug(info, dbg_str);
   }
   i = send(info->fd, data, size, 0);
   return i;
}
Variable Documentation
int debug_first = TRUE [static]
Definition at line 36 of file tcpip.c.
Referenced by tcpip_debug().
int debug_last = 0 [static]
Definition at line 36 of file tcpip.c.
Referenced by tcpip_debug().