AlcapDAQ: slowcontrol/temperature_probe/frontend.c File Reference
frontend.c File Reference
#include <stdio.h>
#include "midas.h"
Functions
INT read_temperature_probe (char *pevent, INT off)
INT pre_begin_of_run ()
INT frontend_early_init ()
INT poll_event (INT source[], INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source[], PTYPE adr)
INT frontend_init ()
INT frontend_exit ()
INT frontend_loop ()
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
Variables
INT crate_number =0
HNDLE hDB
HNDLE hKey
int size
int sepDemand
char Alarm [128] = "/Equipment/TemperatureMonitor/Variables/Alarm_Triggered"
char * frontend_name = "TemperatureMonitor"
char * frontend_file_name = __FILE__
BOOL frontend_call_loop = TRUE
INT display_period = 1000
INT max_event_size = 10000
INT max_event_size_frag = 5 * 1024 * 1024
INT event_buffer_size = 10 * 10000
BANK_LIST temperature_bank_list []
EQUIPMENT equipment []
Function Documentation
INT begin_of_run (INT run_number, char * error)
Definition at line 191 of file frontend.c.
 {
    return CM_SUCCESS;
 }
INT end_of_run (INT run_number, char * error)
Definition at line 198 of file frontend.c.
 {
    return CM_SUCCESS;
 }
INT frontend_early_init (void)
Definition at line 145 of file crate.cpp.
References crate_number, equipment, FALSE, frontend_index, frontend_name, i, printf(), sprintf(), and SUCCESS.
 {
   // Determine our crate ID by comparing against a list of hostnames
   printf("Entering frontend_early_init ... \n");
   //char *hostnames[] = {"fe1", "fe2", "fe3", "turtle", "fe5", "fe6"};
   //char *hostnames[] = {"fe1", "fe2", "daq2.MuSIC", "fe4", "fe5", "fe6", "fe7"};
   //int crate_numbers[] = {1, 2, 3, 4, 5, 6, 9};
   //char *hostnames[] = {"daq2.MuSIC"};
   //int crate_numbers[] = {3};
   //BOOL crate_has_periodic[] = {FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE};
   //int num_hostnames = sizeof(hostnames)/sizeof(char *);
   //char my_hostname[256];
   //gethostname(my_hostname, sizeof(my_hostname));
 #if 0
   BOOL has_periodic = FALSE;
   for(int i = 0; i < num_hostnames; i++) {
     if(!strcmp(my_hostname, hostnames[i])) {
       crate_number = crate_numbers[i];
       has_periodic = crate_has_periodic[i];
     }
   }
 #endif
   crate_number = 3;
   BOOL has_periodic = FALSE;
   printf("Hostname and crate cumber defined, crate number = %d  ... \n",crate_number);
   if(crate_number > 0) {
     frontend_name = new char[32];
     strcpy(frontend_name, "Crate ");
 #if 0
     sprintf(equipment[0].name, "Crate %d", crate_number);
     sprintf(equipment[0].info.buffer, "BUF%d", crate_number);
     equipment[0].info.event_id = 1000 + crate_number;
 #endif
     frontend_index = crate_number;
     printf("Crate number = %d\n",crate_number);
     if(has_periodic) {
       sprintf(equipment[1].name, "Periodic %d", crate_number);
       equipment[1].info.event_id = 2000 + crate_number;
     } else {
       sprintf(equipment[1].name, "");
     }
   }
   printf("Frontend early init returns success \n");
   return SUCCESS;
 }
INT frontend_exit (void)
Definition at line 176 of file frontend.c.
 {
   return CM_SUCCESS;
 }
INT frontend_init (void)
Definition at line 161 of file frontend.c.
References Alarm, hDB, hKey, and SUCCESS.
 {
   // get the LabView filename
   cm_get_experiment_database(&hDB, NULL);
   if(db_find_key(hDB, 0, Alarm, &hKey) != SUCCESS){
     db_create_key(hDB,0,Alarm,TID_INT);
   }
   return CM_SUCCESS;
 }
INT frontend_loop (void)
Definition at line 183 of file frontend.c.
 {
    ss_sleep(100);
    return CM_SUCCESS;
 }
INT interrupt_configure (INT cmd, INT source[], PTYPE adr)
Definition at line 154 of file frontend.c.
 {
    return 1;
 };
INT pause_run (INT run_number, char * error)
Definition at line 205 of file frontend.c.
 {
    return CM_SUCCESS;
 }
INT poll_event (INT source[], INT count, BOOL test)
Definition at line 150 of file frontend.c.
 {
    return 1;
 };
INT pre_begin_of_run ()
INT read_temperature_probe (char * pevent, INT off)
Definition at line 219 of file frontend.c.
References count, and printf().
{
 //
 //  static char oldtimestamp[80];
 //  char timestamp[80];
 //  char timestring[80];
 //  FILE *infile=NULL;
   float *pdata;
 //  static float lastHVs[4] = {-1., -1., -1., -1.};
 //  static int initDone = 0;
 //  int i;
 //
 //  size = sizeof(sepDemand);
 //  db_get_value(hDB,0, "/Experiment/Edit on start/Temperature HV",
 //             &sepDemand, &size, TID_INT, 1);
 //
 //  timestamp[0]='\0';
 //
 //  infile=fopen("/tmp/temperature.txt","r");
 //  if (infile==NULL){
 //    cm_msg(MERROR,frontend_name,
 //         "Could not open tempfile. temperature_daemon.pl not running?");
 //    temperature_data.hv =-1;
 //    temperature_data.vac =-1;
 //    temperature_data.sep_stat =-1;
 //  }
 //  else{
 //    fscanf(infile,"%s\n%f\n%f\n%f\n%f",timestamp,&temperature_data.hv,
 //         &temperature_data.current,&temperature_data.vac,
 //         &temperature_data.sep_stat);
 //    fclose(infile);
 //
 //    if(!strcmp(oldtimestamp, timestamp)){
 //      temperature_data.hv=-1;
 //      temperature_data.vac=-1;
 //      temperature_data.sep_stat=-1;
 //    }
 //  }
 //
 //  if(initDone == 0){
 //    for(i=0; i<4; i++) lastHVs[i] = temperature_data.hv;
 //    initDone = 1;
 //  }
 //  else{
 //    for(i=0; i<3; i++) lastHVs[i] = lastHVs[i+1];
 //    lastHVs[3] = temperature_data.hv;
 //  }
 //
 //  //for(i=0; i<4; i++) printf("HV[%d]=%d\n",i,(int)lastHVs[i]);
 //  //printf("Demand = %d\n", sepDemand);
 //
   //Send to midas:
   bk_init(pevent);
 //bk_create(pevent,"SEPA",TID_FLOAT,&pdata);
 //pdata[0] = 1;
 //  pdata[1] = temperature_data.current;
 //  pdata[2] = temperature_data.vac;
 //  pdata[3] = temperature_data.sep_stat;
 //bk_close(pevent,pdata+0);
 //
 //  int sepError = 1;
 //
 //  for(i=0; i<4; i++){
 //    if((int)lastHVs[i] == sepDemand) sepError = 0;
 //  }
 //
 //  if(sepError==1){
 //    if(strcmp(oldtimestamp, timestamp)){
 //      cm_msg(MERROR,frontend_name,"Temperature high voltage not same as demand!");
 //      printf("Demand = %d", sepDemand);
 //    }
 //    else{
 //      cm_msg(MERROR,frontend_name,"Old and new timestamps identical."
 //           " Refresh too high or temperature_daemon.pl not running.");
 //    }
 //    int on = 1;
 //    db_set_value(hDB, 0, Alarm, &on, sizeof(on), 1, TID_INT);
 //  }
 //  else{
 //    int off = 0;
 //    db_set_value(hDB, 0, Alarm, &off, sizeof(off), 1, TID_INT);
 //  }
 //
 //  strcpy(oldtimestamp,timestamp);
 //
 //  return bk_size(pevent);
 //
   static int count=0;
   printf("hello from temperature probe %d\n", count++);
   return 1;
 }
INT resume_run (INT run_number, char * error)
Definition at line 212 of file frontend.c.
 {
    return CM_SUCCESS;
 }
Variable Documentation
char Alarm[128] = "/Equipment/TemperatureMonitor/Variables/Alarm_Triggered"
Definition at line 74 of file frontend.c.
INT crate_number =0
Definition at line 68 of file frontend.c.
INT display_period = 1000
Definition at line 91 of file frontend.c.
EQUIPMENT equipment[]
Initial value:
= {
   {"TemperatureMonitor",
     { 23, 0,
       "SYSTEM",
       EQ_PERIODIC,
       0,
       "MIDAS",
       TRUE,
       RO_ALWAYS|RO_ODB,
       10000,
       0,
       0,
       0,
       "", "", "", },
    read_temperature_probe,
    NULL, NULL,
    temperature_bank_list,
   },
   {""}
}
Definition at line 111 of file frontend.c.
INT event_buffer_size = 10 * 10000
Definition at line 100 of file frontend.c.
BOOL frontend_call_loop = TRUE
Definition at line 88 of file frontend.c.
char* frontend_file_name = __FILE__
Definition at line 85 of file frontend.c.
char* frontend_name = "TemperatureMonitor"
Definition at line 83 of file frontend.c.
HNDLE hDB
Definition at line 70 of file frontend.c.
HNDLE hKey
Definition at line 71 of file frontend.c.
INT max_event_size = 10000
Definition at line 94 of file frontend.c.
INT max_event_size_frag = 5 * 1024 * 1024
Definition at line 97 of file frontend.c.
int sepDemand
Definition at line 73 of file frontend.c.
int size
Definition at line 72 of file frontend.c.
BANK_LIST temperature_bank_list[]
Initial value:
= {
  { "TMP1", TID_FLOAT,  1, NULL },
  { "" },
}
Definition at line 104 of file frontend.c.