AlcapDAQ: analyzer/rootana/scripts/test.cc File Reference
test.cc File Reference
Typedefs
typedef map< string, vector
< TAnalysedPulse * > > chn2AnalysedPulseMap
Functions
gROOT ProcessLine ("#include <map>")
gROOT ProcessLine ("#include <pair>")
gROOT ProcessLine ("#include <vector>")
gROOT ProcessLine (".L ~/work/AlcapDAQ/analyzer/rootana/libAnalysis.so")
tree Print ()
tree SetMakeClass (1)
tree SetBranchAddress ("fChn2PulseMap",&currentMap)
for (int i=0;i< 1;++i)
Variables
TFile * file
TTree * tree = (TTree*)file->Get("AnalysedPulseTree")
TAnalysedPulseMapWrapper * mapWrapper
chn2AnalysedPulseMap currentMap
int nentries = tree->GetEntriesFast()
Typedef Documentation
typedef map<string, vector<TAnalysedPulse*> > chn2AnalysedPulseMap
Definition at line 14 of file test.cc.
Function Documentation
for ()
Definition at line 23 of file test.cc.
References i, and printf().
Referenced by epics_ca_callback(), and V1742UnpackEventGroup().
         {
                 std::cout<<"Event "<<i<<", ";
                 std::cout<<"byte read: "<<tree->GetEntry(i);
                 std::cout<<", size: "<<currentMap.size()<<std::endl;
                 //mapWrapper->ShowInfo();
                 for (chn2AnalysedPulseMap::iterator mapIter = currentMap.begin();
                                 mapIter != currentMap.end(); ++mapIter)
                 {
                         string detname = mapIter->first;
                         vector<TAnalysedPulse *> pulseVector = mapIter->second;
                         std::cout<<detname<<": "<< pulseVector.size()<<" pulses\n";
                         vector<TAnalysedPulse *>::iterator pulseIter;
                         for (pulseIter = pulseVector.begin();
                                         pulseIter != pulseVector.end(); ++pulseIter)
{
                                 printf("height: %.2f", (*pulseIter)->GetAmplitude());
                                 printf("time: %.2f\n", (*pulseIter)->GetTime());
                         }
                 }
         }
tree Print ()
gROOT ProcessLine ("#include <map>")
gROOT ProcessLine ("#include <pair>")
gROOT ProcessLine ("#include <vector>")
gROOT ProcessLine (".L ~/work/AlcapDAQ/analyzer/rootana/libAnalysis.so")
tree SetBranchAddress ("fChn2PulseMap" , & currentMap)
tree SetMakeClass (1)
Variable Documentation
chn2AnalysedPulseMap currentMap
Definition at line 15 of file test.cc.
TFile* file
Initial value:
=
                TFile::Open("~/work/RunPSI2013/data/root/analysedtree/anatree03474.root")
Definition at line 7 of file test.cc.
Referenced by MDFile().
TAnalysedPulseMapWrapper* mapWrapper
Definition at line 13 of file test.cc.
int nentries = tree->GetEntriesFast()
Definition at line 21 of file test.cc.
Referenced by Main_event_loop().
TTree* tree = (TTree*)file->Get("AnalysedPulseTree")
Definition at line 10 of file test.cc.
Referenced by h1analysis::Init().