AlcapDAQ: midas/examples/basic/tinyfe.c File Reference
midas/examples/basic/tinyfe.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "midas.h"
#include "msystem.h"
#include "mcstd.h"
Defines
#define NWORDS 3
Functions
INT frontend_init ()
INT frontend_exit ()
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
INT frontend_loop ()
INT read_tiny_event (char *pevent, INT off)
INT poll_event (INT source, INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Variables
char * frontend_name = "tinyfe"
char * frontend_file_name = __FILE__
BOOL frontend_call_loop = TRUE
INT display_period = 0000
INT max_event_size = 10000
INT max_event_size_frag = 5 * 1024 * 1024
INT event_buffer_size = 10 * 10000
HNDLE hDB
HNDLE hKey
EQUIPMENT equipment []
Define Documentation
#define NWORDS 3
Definition at line 264 of file tinyfe.c.
Referenced by read_tiny_event().
Function Documentation
INT begin_of_run (INT run_number, char * error)
Definition at line 182 of file tinyfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT end_of_run (INT run_number, char * error)
Definition at line 189 of file tinyfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_exit (void)
Definition at line 175 of file tinyfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_init (void)
Definition at line 168 of file tinyfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_loop (void)
Definition at line 209 of file tinyfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Definition at line 247 of file tinyfe.c.
References CMD_INTERRUPT_ATTACH, CMD_INTERRUPT_DETACH, CMD_INTERRUPT_DISABLE, CMD_INTERRUPT_ENABLE, and SUCCESS.
{
   switch (cmd) {
   case CMD_INTERRUPT_ENABLE:
      break;
   case CMD_INTERRUPT_DISABLE:
      break;
   case CMD_INTERRUPT_ATTACH:
      break;
   case CMD_INTERRUPT_DETACH:
      break;
   }
   return SUCCESS;
}
INT pause_run (INT run_number, char * error)
Definition at line 196 of file tinyfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT poll_event (INT source, INT count, BOOL test)
Definition at line 224 of file tinyfe.c.
References cam_lam_read(), i, LAM_SOURCE_CRATE, and LAM_SOURCE_STATION.
{
   int i;
   DWORD lam;
   for (i = 0; i < count; i++) {
      cam_lam_read(LAM_SOURCE_CRATE(source), &lam);
//  To force a LAM independently of the driver.
      lam = 1;
      if (lam & LAM_SOURCE_STATION(source))
         if (!test)
            return lam;
   }
   return 0;
}
INT read_tiny_event (char * pevent, INT off)
Definition at line 266 of file tinyfe.c.
References bk_close(), bk_create(), bk_init(), bk_size(), NWORDS, and TID_WORD.
{
   static WORD *pdata = NULL;
   static WORD sub_counter = 0;
   // Super event structure
   if (offset == 0) {           // FIRST event of the Super event
      bk_init(pevent);
      bk_create(pevent, "SUPR", TID_WORD, &pdata);
      sub_counter = 1;
   } else if (offset == -1) {   // CLOSE Super event
      bk_close(pevent, pdata);
      return bk_size(pevent);
   }
   // READ event
   *pdata++ = 0xB0E;
   *pdata++ = sub_counter++;
   *pdata++ = 0xE0E;
   if (offset == 0) {
      // Compute the proper event length on the FIRST event in the Super Event
      // NWORDS correspond to the !! NWORDS WORD above !!
      // sizeof(BANK_HEADER) + sizeof(BANK) will make the 16 bytes header
      // sizeof(WORD) is defined by the TID_WORD in bk_create()
      return NWORDS * sizeof(WORD) + sizeof(BANK_HEADER) + sizeof(BANK);
   } else {
      // Return the data section size only
      // sizeof(WORD) is defined by the TID_WORD in bk_create()
      return NWORDS * sizeof(WORD);
   }
}
INT resume_run (INT run_number, char * error)
Definition at line 203 of file tinyfe.c.
References SUCCESS.
{
   return SUCCESS;
}
Variable Documentation
INT display_period = 0000
Definition at line 88 of file tinyfe.c.
EQUIPMENT equipment[]
Initial value:
 {
      {"Tiny",
       3, 0,
       "SYSTEM",
       EQ_POLLED,
       1,
       "MIDAS",
       TRUE,
       RO_RUNNING,
       500,
       0,
       10,
       0,
       "", "", "",
       read_tiny_event,
       NULL, NULL,
       NULL,
       },
      {""}
   }
Definition at line 117 of file tinyfe.c.
INT event_buffer_size = 10 * 10000
Definition at line 97 of file tinyfe.c.
BOOL frontend_call_loop = TRUE
Definition at line 85 of file tinyfe.c.
char* frontend_file_name = __FILE__
Definition at line 82 of file tinyfe.c.
char* frontend_name = "tinyfe"
Definition at line 79 of file tinyfe.c.
HNDLE hDB
Definition at line 101 of file tinyfe.c.
HNDLE hKey
Definition at line 101 of file tinyfe.c.
INT max_event_size = 10000
Definition at line 91 of file tinyfe.c.
INT max_event_size_frag = 5 * 1024 * 1024
Definition at line 94 of file tinyfe.c.