AlcapDAQ: midas/NT/directio/tstio.c File Reference
midas/NT/directio/tstio.c File Reference
#include <stdio.h>
#include <windows.h>
#include <math.h>
#include <conio.h>
Data Structures
struct NOTE
Functions
void setfreq (int hz)
void playnote (NOTE note)
INT ss_directio_init ()
INT ss_directio_exit ()
INT ss_directio_give_port (INT start, INT end)
INT ss_directio_lock_port (INT start, INT end)
int main ()
Variables
NOTE notes [] = {{14, 500}, {16, 500}, {12, 500}, {0, 500}, {7, 1000}}
static HANDLE _hdio = 0
Function Documentation
int main (void)
Definition at line 107 of file tstio.c.
References i, playnote(), ss_directio_exit(), ss_directio_give_port(), ss_directio_init(), and ss_directio_lock_port().
{
int i;
  ss_directio_init();
  ss_directio_lock_port(0, 0xFFFF);
  ss_directio_give_port(0x42, 0x43);
  ss_directio_give_port(0x61, 0x61);
  ss_directio_exit();
        for(i=0; i < sizeof(notes)/sizeof(int); ++i)
                playnote(notes[i]);
        return 0;
}
void playnote (NOTE note)
Definition at line 47 of file tstio.c.
References NOTE::duration, NOTE::pitch, and setfreq().
Referenced by main().
{
        _outp(0x61, _inp(0x61) | 0x03);                 // start speaker going
        setfreq((int)(400 * pow(2, note.pitch / 12.0)));
        Sleep(note.duration);
        _outp(0x61, _inp(0x61) & ~0x03);                // stop that racket!
}
void setfreq (int hz)
Definition at line 33 of file tstio.c.
Referenced by playnote().
{
        hz = 1193180 / hz;                                              // clocked at 1.19MHz
        _outp(0x43, 0xb6);                                              // timer 2, square wave
        _outp(0x42, hz);
        _outp(0x42, hz >> 8);
}
INT ss_directio_exit ()
Definition at line 68 of file tstio.c.
References _hdio.
{
  return CloseHandle(_hdio);
}
INT ss_directio_init ()
Definition at line 61 of file tstio.c.
References _hdio.
{
  _hdio = CreateFile("\\\\.\\directio", GENERIC_READ, FILE_SHARE_READ, NULL,
                                       OPEN_EXISTING, 0, NULL);
  return (INT) _hdio;
}
Variable Documentation
HANDLE _hdio = 0 [static]
Definition at line 59 of file tstio.c.
Referenced by ss_directio_exit(), ss_directio_give_port(), ss_directio_init(), and ss_directio_lock_port().
NOTE notes[] = {{14, 500}, {16, 500}, {12, 500}, {0, 500}, {7, 1000}}
Definition at line 27 of file tstio.c.