AlcapDAQ: crate4_CAEN_V1724/v1724_module.c File Reference
v1724_module.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/io.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>
#include "midas.h"
#include "crate.h"
#include "diag.h"
#include "CAENDigitizer.h"
Data Structures
struct s_v1724_odb
Macros
#define NBOARDS 1 /* Number of connected boards */
#define S_V1724_ODB_STR "\[.]\n\VME base = DWORD : 0x32100000\n\enabled = BOOL : y\n\waveform length = DWORD : 32\n\acquisition mode = BYTE : 1\n\software trigger mode = BYTE : 0\n\hardware trigger mode = BYTE : 0\n\trigger edge (0-ris 1-fal) = BYTE : 1\n\down sampling factor = INT : 1\n\ROC firmware = STRING : [128] -\n\AMC firmware = STRING : [128] -\n\\n\[Ch0]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 0\n\trigger threshhold = DWORD : 0\n\\n\[Ch1]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch2]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch3]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch4]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch5]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch6]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch7]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\"
Typedefs
typedef struct timespec timer_start
typedef struct s_v1724_odb S_V1724_ODB_DEF
Functions
static INT v1724_init ()
static void v1724_exit ()
static INT v1724_pre_bor ()
static INT v1724_eor ()
static INT v1724_poll_live ()
static INT v1724_read (char *pevent)
static void v1724_readout ()
Variables
static int handle [NBOARDS]
static char * caen_data_buffer [NBOARDS]
static uint32_t caen_data_buffer_size [NBOARDS]
static char * data_buffer [NBOARDS]
static uint32_t data_buffer_size [NBOARDS]
static uint32_t data_size [NBOARDS]
HNDLE hDB
bool block_sig
struct readout_module v1724_module
static S_V1724_ODB_DEF S_V1724_ODB [NBOARDS]
Macro Definition Documentation
#define NBOARDS 1 /* Number of connected boards */
Definition at line 20 of file v1724_module.c.
Referenced by v1724_eor(), v1724_exit(), v1724_init(), v1724_pre_bor(), v1724_read(), and v1724_readout().
#define S_V1724_ODB_STR "\[.]\n\VME base = DWORD : 0x32100000\n\enabled = BOOL : y\n\waveform length = DWORD : 32\n\acquisition mode = BYTE : 1\n\software trigger mode = BYTE : 0\n\hardware trigger mode = BYTE : 0\n\trigger edge (0-ris 1-fal) = BYTE : 1\n\down sampling factor = INT : 1\n\ROC firmware = STRING : [128] -\n\AMC firmware = STRING : [128] -\n\\n\[Ch0]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 0\n\trigger threshhold = DWORD : 0\n\\n\[Ch1]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch2]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch3]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch4]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch5]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch6]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\\n\[Ch7]\n\enabled = BOOL : y\n\DC offset = DWORD : 0\n\self-trigger mode = BYTE : 1\n\trigger threshhold = DWORD : 0\n\"
Definition at line 83 of file v1724_module.c.
Referenced by v1724_init().
Typedef Documentation
typedef struct s_v1724_odb S_V1724_ODB_DEF
typedef struct timespec timer_start
Definition at line 40 of file v1724_module.c.
Function Documentation
INT v1724_eor () static
Definition at line 641 of file v1724_module.c.
References CAEN_DGTZ_Success, CAEN_DGTZ_SWStopAcquisition(), enabled, handle, NBOARDS, and SUCCESS.
 {
   CAEN_DGTZ_ErrorCode ret;
   for (int iboard=0; iboard<NBOARDS; iboard++)
     {
       if ( !S_V1724_ODB[iboard].enabled ) continue;
       // =====================================================================================
       // Disable acquisition
       // =====================================================================================
       ret =  CAEN_DGTZ_SWStopAcquisition(handle[iboard]);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot CAEN_DGTZ_SWStopAcquisition. Error 0x%08x\n",ret);
         }
     }
   return SUCCESS;
 }
void v1724_exit () static
Definition at line 320 of file v1724_module.c.
References caen_data_buffer, CAEN_DGTZ_CloseDigitizer(), CAEN_DGTZ_FreeReadoutBuffer(), CAEN_DGTZ_Success, data_buffer, enabled, handle, and NBOARDS.
 {
   CAEN_DGTZ_ErrorCode ret;
   for (int iboard=0; iboard<NBOARDS; iboard++)
     {
       if ( !S_V1724_ODB[iboard].enabled ) continue;
       // =====================================================================================
       // Free memory allocated for data buffer
       // =====================================================================================
       ret = CAEN_DGTZ_FreeReadoutBuffer(&(caen_data_buffer[iboard]));
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_exit","Cannot FreeReadoutBuffer. Error 0x%08x\n",ret);
         }
       // =====================================================================================
       // Close digitizer
       // =====================================================================================
       ret = CAEN_DGTZ_CloseDigitizer(handle[iboard]);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_exit","Cannot CloseDigitizer. Error 0x%08x\n",ret);
         }
       // =====================================================================================
       // Free memory buffers
       // =====================================================================================
       free( data_buffer[iboard] );
     }
 }
INT v1724_init () static
Definition at line 145 of file v1724_module.c.
References caen_data_buffer, caen_data_buffer_size, CAEN_DGTZ_DOWNSAMPLE_FACT_ADD, CAEN_DGTZ_GetInfo(), CAEN_DGTZ_MallocReadoutBuffer(), CAEN_DGTZ_OpenDigitizer(), CAEN_DGTZ_PCIE_OpticalLink, CAEN_DGTZ_ReadRegister(), CAEN_DGTZ_Reset(), CAEN_DGTZ_SetMaxNumEventsBLT(), CAEN_DGTZ_Success, CAEN_DGTZ_USB, CAEN_DGTZ_WriteRegister(), crate_number, data_buffer, data_buffer_size, enabled, FALSE, handle, hDB, hKey, NBOARDS, printf(), S_V1724_ODB_STR, sprintf(), status, and SUCCESS.
 {
   /* ODB */
   char str[1024];
   HNDLE hKey;
   for (int iboard=0; iboard<NBOARDS; iboard++)
     {
       sprintf(str,"/Equipment/Crate %i/Settings/CAEN%i",crate_number,iboard);
       int status = db_check_record(hDB,0,str,S_V1724_ODB_STR,FALSE);
       if(status==DB_NO_KEY || status==DB_STRUCT_MISMATCH)
         {
           status = db_create_record(hDB,0,str,S_V1724_ODB_STR);
           printf("Creating key with status: %d \n",status);
         }
       else if (status==DB_INVALID_HANDLE)
         {
           printf("Error: Cannot connect to database to setup CAEN V1724");
           return FE_ERR_HW;
         }
       status = db_find_key(hDB,0,str,&hKey);
       status = db_open_record(hDB, hKey, &(S_V1724_ODB[iboard]), sizeof(S_V1724_ODB[0]), MODE_READ, NULL, NULL);
     }
   printf("Opening CAEN VME interface ...");
   fflush(stdout);
   CAEN_DGTZ_ErrorCode ret;
   CAEN_DGTZ_BoardInfo_t BoardInfo[NBOARDS];
   uint32_t data;
   for (int iboard=0; iboard<NBOARDS; iboard++)
     {
       if ( !S_V1724_ODB[iboard].enabled ) continue;
 #if 0
       ret = CAEN_DGTZ_OpenDigitizer(CAEN_DGTZ_USB,0,0,S_V1724_ODB[iboard].vme_base,&handle[iboard]);
 #else
       ret = CAEN_DGTZ_OpenDigitizer(CAEN_DGTZ_PCIE_OpticalLink,0,0,S_V1724_ODB[iboard].vme_base,&handle[iboard]);
 #endif
       if(ret != CAEN_DGTZ_Success)
         {
           cm_msg(MERROR,"v1724_init","Can't open digitizer at address 0x%08x\n",S_V1724_ODB[iboard].vme_base);
           return FE_ERR_HW;
         }
       ret = CAEN_DGTZ_GetInfo(handle[iboard], &(BoardInfo[iboard]));
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot get board info. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       printf("\nConnected to CAEN Digitizer Model %s, recognized as board %d\n", BoardInfo[iboard].ModelName, iboard);
       printf("\tROC FPGA Release is %s\n", BoardInfo[iboard].ROC_FirmwareRel);
       printf("\tAMC FPGA Release is %s\n", BoardInfo[iboard].AMC_FirmwareRel);
       ret = CAEN_DGTZ_Reset(handle[iboard]);                                               /* Reset Digitizer */
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot reset the board. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       ret = CAEN_DGTZ_GetInfo(handle[iboard], &(BoardInfo[iboard]));
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot get board info. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // =====================================================================================
       // Setup 1024 data buffers (max.)
       // =====================================================================================
       ret = CAEN_DGTZ_WriteRegister(handle[iboard], 0x800C, 0xA);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot configure data buffers. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // =====================================================================================
       // Configure max. number of buffers for BLT readout
       // =====================================================================================
       ret = CAEN_DGTZ_SetMaxNumEventsBLT(handle[iboard],1024);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot configure data buffers for BLT readout. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // =====================================================================================
       // Allocate memory buffer to hold data received from digitizer
       // =====================================================================================
       caen_data_buffer[iboard] = NULL;
       ret = CAEN_DGTZ_MallocReadoutBuffer(handle[iboard], &(caen_data_buffer[iboard]), &(caen_data_buffer_size[iboard]));
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot MallocReadoutBuffer. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       printf("Readout buffer size: %i\n",caen_data_buffer_size[iboard]);
       // =====================================================================================
       // Allocate memory buffer to hold all data from digitizer
       // =====================================================================================
       data_buffer_size[iboard] = 0x2000000; // 32 MB
       data_buffer[iboard] = (char*)malloc(data_buffer_size[iboard]);
       if ( !data_buffer[iboard] )
         {
           cm_msg(MERROR,"v1724_init","Cannot allocate memory for data buffers.\n");
           return FE_ERR_HW;
         }
 #if 0
       // PW
       uint32_t mydata;
       ret = CAEN_DGTZ_ReadRegister(handle[iboard], 0x8100, &mydata);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot read register 0x8100. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       printf("Acquisition control register is: %d\n", mydata);
       mydata |= (1<<4);
       ret = CAEN_DGTZ_WriteRegister(handle[iboard], 0x8100, mydata);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot write register 0x8100. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       ret = CAEN_DGTZ_ReadRegister(handle[iboard], 0x8100, &mydata);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot read register 0x8100. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       printf("2nd time Acquisition control register is: %d\n", mydata);
       ret = CAEN_DGTZ_ReadRegister(handle[iboard], CAEN_DGTZ_DOWNSAMPLE_FACT_ADD, &mydata);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot read register 0x%04x. Error 0x%08x\n",CAEN_DGTZ_DOWNSAMPLE_FACT_ADD, ret);
           return FE_ERR_HW;
         }
       printf("The down sampling factor currently is: 0x%08x\n", mydata);
       mydata = 10;
       ret = CAEN_DGTZ_WriteRegister(handle[iboard], CAEN_DGTZ_DOWNSAMPLE_FACT_ADD, mydata);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot write register 0x8128. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       ret = CAEN_DGTZ_ReadRegister(handle[iboard], CAEN_DGTZ_DOWNSAMPLE_FACT_ADD, &mydata);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","2: Cannot read register 0x%04x. Error 0x%08x\n", CAEN_DGTZ_DOWNSAMPLE_FACT_ADD,ret);
           return FE_ERR_HW;
         }
       printf("The down sampling factor currently is: 0x%08x\n", mydata);
       // end PW
 #endif
     }
   printf("  [done]\n");
   return SUCCESS;
 }
INT v1724_poll_live () static
Definition at line 749 of file v1724_module.c.
References SUCCESS, and v1724_readout().
 {
   v1724_readout();
   return SUCCESS;
 }
INT v1724_pre_bor () static
Definition at line 354 of file v1724_module.c.
References CAEN_DGTZ_BROAD_CH_CTRL_ADD, CAEN_DGTZ_ClearData(), CAEN_DGTZ_ReadRegister(), CAEN_DGTZ_Reset(), CAEN_DGTZ_SetAcquisitionMode(), CAEN_DGTZ_SetChannelDCOffset(), CAEN_DGTZ_SetChannelEnableMask(), CAEN_DGTZ_SetChannelPulsePolarity(), CAEN_DGTZ_SetChannelSelfTrigger(), CAEN_DGTZ_SetChannelTriggerThreshold(), CAEN_DGTZ_SetChannelZSParams(), CAEN_DGTZ_SetPostTriggerSize(), CAEN_DGTZ_SetRecordLength(), CAEN_DGTZ_SetTriggerPolarity(), CAEN_DGTZ_SetZeroSuppressionMode(), CAEN_DGTZ_Success, CAEN_DGTZ_SWStartAcquisition(), CAEN_DGTZ_TRGMODE_ACQ_AND_EXTOUT, CAEN_DGTZ_TRGMODE_ACQ_ONLY, CAEN_DGTZ_TRGMODE_DISABLED, CAEN_DGTZ_TRGMODE_EXTOUT_ONLY, CAEN_DGTZ_TriggerOnFallingEdge, CAEN_DGTZ_TriggerOnRisingEdge, CAEN_DGTZ_WriteRegister(), CAEN_DGTZ_ZS_FINE, CAEN_DGTZ_ZS_ZLE, data_size, enabled, handle, NBOARDS, printf(), SUCCESS, and s_v1724_odb::trigger_edge.
 {
   CAEN_DGTZ_ErrorCode ret;
   for (int iboard=0; iboard<NBOARDS; iboard++)
     {
       if ( !S_V1724_ODB[iboard].enabled ) continue;
       // ==========================================================================================
       // Reset digitizer
       // ==========================================================================================
       ret = CAEN_DGTZ_Reset(handle[iboard]);                                               /* Reset Digitizer */
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot reset the board. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // =====================================================================================
       // Enable channels
       // =====================================================================================
       uint32_t channel_mask = 0x0; // disable all channels
       for (uint32_t ichan=0; ichan<8; ichan++)
         {
           if ( S_V1724_ODB[iboard].ch[ichan].enabled )
             channel_mask |= (1 << ichan); // enable channel ichannel
         }
       printf("channel enable mask: 0x%08x\n",channel_mask);
       ret = CAEN_DGTZ_SetChannelEnableMask(handle[iboard],channel_mask);  // enable all channels
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot Enable channels. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // =====================================================================================
       // Acquisition control
       // =====================================================================================
       //ret = CAEN_DGTZ_SetAcquisitionMode(handle[iboard],CAEN_DGTZ_S_IN_CONTROLLED);
       ret = CAEN_DGTZ_SetAcquisitionMode(handle[iboard], (CAEN_DGTZ_AcqMode_t)S_V1724_ODB[iboard].acquisition_mode);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot configure Acquisition Control. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // =====================================================================================
       // Record length
       // =====================================================================================
       ret = CAEN_DGTZ_SetRecordLength(handle[iboard], S_V1724_ODB[iboard].wf_length);
       //ret = CAEN_DGTZ_SetRecordLength(handle[iboard], 4096);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot SetRecordLength. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // =====================================================================================
       // Self-trigger mode
       // =====================================================================================
       // CAEN_DGTZ_TRGMODE_DISABLED
       uint32_t self_trigger_mask = 0x0; // disable all channels
       for (uint32_t ichan=0; ichan<8; ichan++)
         {
           if ( S_V1724_ODB[iboard].ch[ichan].self_trigger_mode == CAEN_DGTZ_TRGMODE_DISABLED )
             self_trigger_mask |= (1 << ichan); // enable channel ichannel
         }
       printf("self-trigger DISABLED mask: 0x%08x\n",channel_mask);
       ret = CAEN_DGTZ_SetChannelSelfTrigger(handle[iboard], CAEN_DGTZ_TRGMODE_ACQ_ONLY, self_trigger_mask);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot SetCahnngelSelfTrigger. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // CAEN_DGTZ_TRGMODE_ACQ_ONLY
       self_trigger_mask = 0x0; // disable all channels
       for (uint32_t ichan=0; ichan<8; ichan++)
         {
           if ( S_V1724_ODB[iboard].ch[ichan].self_trigger_mode == CAEN_DGTZ_TRGMODE_ACQ_ONLY )
             self_trigger_mask |= (1 << ichan); // enable channel ichannel
         }
       printf("self-trigger ACQ_ONLY mask: 0x%08x\n",channel_mask);
       ret = CAEN_DGTZ_SetChannelSelfTrigger(handle[iboard], CAEN_DGTZ_TRGMODE_ACQ_ONLY, self_trigger_mask);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot SetCahnngelSelfTrigger. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // CAEN_DGTZ_TRGMODE_EXTOUT_ONLY
       self_trigger_mask = 0x0; // disable all channels
       for (uint32_t ichan=0; ichan<8; ichan++)
         {
           if ( S_V1724_ODB[iboard].ch[ichan].self_trigger_mode == CAEN_DGTZ_TRGMODE_EXTOUT_ONLY )
             self_trigger_mask |= (1 << ichan); // enable channel ichannel
         }
       printf("self-trigger EXTOUT_ONLY mask: 0x%08x\n",channel_mask);
       ret = CAEN_DGTZ_SetChannelSelfTrigger(handle[iboard], CAEN_DGTZ_TRGMODE_EXTOUT_ONLY, self_trigger_mask);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot SetCahnngelSelfTrigger. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // CAEN_DGTZ_TRGMODE_ACQ_AND_EXTOUT
       self_trigger_mask = 0x0; // disable all channels
       for (uint32_t ichan=0; ichan<8; ichan++)
         {
           if ( S_V1724_ODB[iboard].ch[ichan].self_trigger_mode == CAEN_DGTZ_TRGMODE_ACQ_AND_EXTOUT )
             self_trigger_mask |= (1 << ichan); // enable channel ichannel
         }
       printf("self-trigger ACQ_AND_EXTOUT mask: 0x%08x\n",channel_mask);
       ret = CAEN_DGTZ_SetChannelSelfTrigger(handle[iboard], CAEN_DGTZ_TRGMODE_ACQ_AND_EXTOUT, self_trigger_mask);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot SetCahnngelSelfTrigger. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // =====================================================================================
       // Trigger polarity
       // =====================================================================================
       int trigger_edge = S_V1724_ODB[iboard].trigger_edge;
       if ( trigger_edge == 0 )
         ret = CAEN_DGTZ_SetTriggerPolarity (handle[iboard], 0, CAEN_DGTZ_TriggerOnRisingEdge);
       else
         ret = CAEN_DGTZ_SetTriggerPolarity (handle[iboard], 0, CAEN_DGTZ_TriggerOnFallingEdge);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot SetTriggerPolarity. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // =====================================================================================
       // Trigger threshold
       // =====================================================================================
       for (uint32_t ichan=0; ichan<8; ichan++)
         {
           ret = CAEN_DGTZ_SetChannelTriggerThreshold(handle[iboard], ichan, S_V1724_ODB[iboard].ch[ichan].trigger_threshold);
           if ( ret != CAEN_DGTZ_Success )
             {
               cm_msg(MERROR,"v1724_init","Cannot SetChannelTriggerThreshold. Error 0x%08x\n",ret);
               return FE_ERR_HW;
             }
         }
 #if 0
       // =====================================================================================
       // Number of samples over threshold for trigger generation
       // =====================================================================================
       for (uint32_t ichan=0; ichan<8; ichan++)
         {
           uint32_t addr = V1724_BASE[iboard]+0x1084 + 0x100*ichan;
           CAEN_DGTZ_WriteRegister(handle[iboard], addr, 1);
           if ( ret != CAEN_DGTZ_Success )
             {
               cm_msg(MERROR,"v1724_init","Cannot Set the number of samples over threshold for trigger. Error 0x%08x\n",ret);
               return FE_ERR_HW;
             }
         }
 #endif
 #if 1
       // =====================================================================================
       // Set post-trigger size
       // =====================================================================================
       ret = CAEN_DGTZ_SetPostTriggerSize(handle[iboard],80);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot SetPostTriggerSize. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
 #endif
       // =====================================================================================
       // DC offset
       // =====================================================================================
       for (uint32_t ichan=0; ichan<8; ichan++)
         {
           ret = CAEN_DGTZ_SetChannelDCOffset(handle[iboard], ichan, S_V1724_ODB[iboard].ch[ichan].offset);
           if ( ret != CAEN_DGTZ_Success )
             {
               cm_msg(MERROR,"v1724_init","Cannot SetChannelDCOffset. Error 0x%08x\n",ret);
               return FE_ERR_HW;
             }
         }
 #if 0
       // =====================================================================================
       // Pulse polarity
       // =====================================================================================
       for (uint32_t ichan=0; ichan<8; ichan++)
         {
           //ret = CAEN_DGTZ_SetChannelPulsePolarity(handle[iboard], ichan, CAEN_DGTZ_PulsePolarityPositive);
           //ret = CAEN_DGTZ_SetChannelPulsePolarity(handle[iboard], ichan, CAEN_DGTZ_PulsePolarityNegative);
           ret = CAEN_DGTZ_SetChannelPulsePolarity(handle[iboard], ichan, (CAEN_DGTZ_PulsePolarity_t)S_V1724_ODB[iboard].ch[ichan].polarity);
           if ( ret != CAEN_DGTZ_Success )
             {
               cm_msg(MERROR,"v1724_init","Cannot SetChannelPulsePolarity. Error 0x%08x\n",ret);
               return FE_ERR_HW;
             }
         }
 #endif
 #if 0
       // =====================================================================================
       // Set Zero suppresion parameters
       // =====================================================================================
       for (uint32_t ichan=0; ichan<8; ichan++)
         {
           ret = CAEN_DGTZ_SetChannelZSParams(handle[iboard], ichan, CAEN_DGTZ_ZS_FINE, 20, 4);
           if ( ret != CAEN_DGTZ_Success )
             {
               cm_msg(MERROR,"v1724_init","Cannot SetChannelZSParams. Error 0x%08x\n",ret);
               return FE_ERR_HW;
             }
         }
       // =====================================================================================
       // Zero suppresion mode
       // =====================================================================================
       ret = CAEN_DGTZ_SetZeroSuppressionMode(handle[iboard], CAEN_DGTZ_ZS_ZLE);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot SetZeroSuppressionMode. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
 #endif
       // =====================================================================================
       // Clear digitizer data buffers
       // =====================================================================================
       ret = CAEN_DGTZ_ClearData( handle[iboard] );
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot clear CAEN data buffers. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // =====================================================================================
       // Enable acquisition
       // =====================================================================================
       ret = CAEN_DGTZ_SWStartAcquisition(handle[iboard]);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot CAEN_DGTZ_SWStartAcquisition. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       data_size[iboard] = 0;
       // ======================================================================================
       // Channel configuration through register 0x8000=CAEN_DGTZ_BROAD_CH_CTRL_ADD
       // ======================================================================================
       uint32_t data;
       ret = CAEN_DGTZ_ReadRegister(handle[iboard], CAEN_DGTZ_BROAD_CH_CTRL_ADD, &data);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot read from register 0x8000. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
       // enable trigger overlap
       data |= (1<<1);
       printf("channel configuration register 0x8000: %0x08x\n",data);
       ret = CAEN_DGTZ_WriteRegister(handle[iboard], CAEN_DGTZ_BROAD_CH_CTRL_ADD, data);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_init","Cannot write to register 0x8000. Error 0x%08x\n",ret);
           return FE_ERR_HW;
         }
     }
   return SUCCESS;
 }
INT v1724_read (char * pevent) static
Definition at line 663 of file v1724_module.c.
References data_buffer, data_size, enabled, NBOARDS, printf(), sprintf(), SUCCESS, and v1724_readout().
 {
   printf("Read out data from digitizer(s)\n");
   // =====================================================================================
   // Read out remaining data from the digitizer
   // =====================================================================================
   v1724_readout();
   // =====================================================================================
   // Fill MIDAS event
   // =====================================================================================
   bk_init32(pevent);
   char bk_name[80];
   char *pdata;
   for (int iboard=0; iboard<NBOARDS; iboard++)
     {
       if ( !S_V1724_ODB[iboard].enabled ) continue;
       sprintf(bk_name, "CDG%i", iboard);
       bk_create(pevent, bk_name, TID_BYTE, &pdata);
       if ( data_size[iboard] > MAX_EVENT_SIZE/2 )
         {
           cm_msg(MERROR,"v1724_read","Event size is too large. Truncating data...\n");
           data_size[iboard] = MAX_EVENT_SIZE/2;
         }
       memcpy(pdata, data_buffer[iboard], data_size[iboard]);
       pdata += data_size[iboard];
       bk_close(pevent, pdata);
       //printf("board %i data size: %i\n",iboard,data_size[iboard]);
       // reset data couner for the next event
       data_size[iboard] = 0;
     }
   return SUCCESS;
 }
void v1724_readout () static
Definition at line 701 of file v1724_module.c.
References caen_data_buffer, CAEN_DGTZ_GetNumEvents(), CAEN_DGTZ_ReadData(), CAEN_DGTZ_ReadRegister(), CAEN_DGTZ_SLAVE_TERMINATED_READOUT_MBLT, CAEN_DGTZ_Success, data_buffer, data_buffer_size, data_size, enabled, handle, NBOARDS, and printf().
Referenced by v1724_poll_live(), and v1724_read().
 {
   CAEN_DGTZ_ErrorCode ret;
   for (int iboard=0; iboard<NBOARDS; iboard++)
     {
       if ( !S_V1724_ODB[iboard].enabled ) continue;
       uint32_t rdata;
       ret = CAEN_DGTZ_ReadRegister(handle[iboard], 0x812C, &rdata);
       //printf("Event Stored: 0x%08x ret = %i\n",rdata, ret);
       if ( ret != CAEN_DGTZ_Success )
         {
           cm_msg(MERROR,"v1724_readout","Cannot read register 0x812C. Error 0x%08x\n",ret);
         }
       //ret = CAEN_DGTZ_ReadRegister(handle[iboard], 0x814C, &rdata);
       //printf("Event size: 0x%08x ret = %i\n",rdata, ret);
       if ( rdata > 0 )
         {
           // =====================================================================================
           // Read data
           // =====================================================================================
           uint32_t caen_data_size;
           ret = CAEN_DGTZ_ReadData(handle[iboard], CAEN_DGTZ_SLAVE_TERMINATED_READOUT_MBLT, caen_data_buffer[iboard], &caen_data_size);
           if ( ret != CAEN_DGTZ_Success )
             {
               cm_msg(MERROR,"v1724_readout","Cannot DGTZ_ReadData. Error 0x%08x\n",ret);
             }
           //printf("data size: %i\n", caen_data_size);
 #if 0
           uint32_t numEvents;
           CAEN_DGTZ_GetNumEvents(handle[iboard],caen_data_buffer[iboard],caen_data_size,&numEvents);
           printf("numEvents: %i\n", numEvents);
 #endif
           if ( data_size[iboard] + caen_data_size < data_buffer_size[iboard] )
             {
               memcpy( (data_buffer[iboard] + data_size[iboard]), caen_data_buffer[iboard], caen_data_size);
               data_size[iboard] += caen_data_size;
             }
         }
     }
 }
Variable Documentation
bool block_sig
Definition at line 39 of file v1724_module.c.
char* caen_data_buffer[NBOARDS] static
Definition at line 23 of file v1724_module.c.
Referenced by v1724_exit(), v1724_init(), and v1724_readout().
uint32_t caen_data_buffer_size[NBOARDS] static
Definition at line 24 of file v1724_module.c.
Referenced by v1724_init().
char* data_buffer[NBOARDS] static
Definition at line 25 of file v1724_module.c.
Referenced by v1724_exit(), v1724_init(), v1724_read(), and v1724_readout().
uint32_t data_buffer_size[NBOARDS] static
Definition at line 26 of file v1724_module.c.
Referenced by v1724_init(), and v1724_readout().
uint32_t data_size[NBOARDS] static
Definition at line 27 of file v1724_module.c.
Referenced by decompress(), read_midas_event(), v1724_pre_bor(), v1724_read(), and v1724_readout().
int handle[NBOARDS] static
Definition at line 21 of file v1724_module.c.
Referenced by caenV767_bor1(), main(), sis3600_bor1(), v1724_eor(), v1724_exit(), v1724_init(), v1724_pre_bor(), v1724_readout(), and vme_open().
HNDLE hDB
Definition at line 11 of file mucap_compress.cpp.
S_V1724_ODB_DEF S_V1724_ODB[NBOARDS] static
Definition at line 81 of file v1724_module.c.
struct readout_module v1724_module
Initial value:
= {
  v1724_init,
  v1724_exit,
  v1724_pre_bor,
  NULL,
  v1724_eor,
  v1724_poll_live,
  NULL,
  NULL,
  NULL,
  v1724_read
}
Definition at line 42 of file v1724_module.c.