AlcapDAQ: midas/drivers/device/bb_psi.h File Reference
midas/drivers/device/bb_psi.h File Reference
Functions
INT bb_psi (INT cmd,...)
Function Documentation
INT bb_psi (INT cmd, ...)
Definition at line 330 of file bb_psi.c.
References bb_psi_exit(), bb_psi_get(), bb_psi_get_demand(), bb_psi_init(), bb_psi_set(), channel, CMD_EXIT, CMD_GET, CMD_GET_DEFAULT_NAME, CMD_GET_DEFAULT_THRESHOLD, CMD_GET_DEMAND, CMD_INIT, CMD_SET, FE_SUCCESS, hKey, name, status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   float value, *pvalue;
   void *info;
   char *name;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      status = bb_psi_init(hKey, info, channel);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = bb_psi_exit(info);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = bb_psi_set(info, channel, value);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = bb_psi_get(info, channel, pvalue);
      break;
   case CMD_GET_DEMAND:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = bb_psi_get_demand(info, channel, pvalue);
      break;
   case CMD_GET_DEFAULT_NAME:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      name = va_arg(argptr, char *);
      strcpy(name, "BBlocker");
      status = FE_SUCCESS;
      break;
   case CMD_GET_DEFAULT_THRESHOLD:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      *pvalue = 0.1f;
      status = FE_SUCCESS;
      break;
   default:
      break;
   }
   va_end(argptr);
   return status;
}