AlcapDAQ: bit3_mvme/bt617.c File Reference
bit3_mvme/bt617.c File Reference
Defines
#define DEV_FILE "/dev/vmedrv"
Functions
int mvme_open (MVME_INTERFACE **vme, int idx)
int mvme_close (MVME_INTERFACE *vme)
void show_mvme (MVME_INTERFACE *vme)
vmedrv_access_mode_t bt617_GetAccessMode (MVME_INTERFACE *vme)
void bt617_SetAccessMode (MVME_INTERFACE *vme)
int mvme_set_am (MVME_INTERFACE *vme, int am)
int mvme_get_am (MVME_INTERFACE *vme, int *am)
int mvme_set_dmode (MVME_INTERFACE *vme, int dm)
int mvme_set_blt (MVME_INTERFACE *vme, int mode)
int mvme_get_blt (MVME_INTERFACE *vme, int *mode)
int mvme_get_dmode (MVME_INTERFACE *vme, int *dm)
int mvme_read (MVME_INTERFACE *vme, void *dst, mvme_addr_t vme_addr, mvme_size_t n_bytes)
int mvme_write (MVME_INTERFACE *vme, mvme_addr_t vme_addr, void *src, mvme_size_t n_bytes)
unsigned int mvme_read_value (MVME_INTERFACE *vme, mvme_addr_t vme_addr)
int mvme_write_value (MVME_INTERFACE *vme, mvme_addr_t vme_addr, unsigned int value)
void showbits (uint32_t data)
void bt617_SetBLT (MVME_INTERFACE *vme, bool blt)
Define Documentation
#define DEV_FILE "/dev/vmedrv"
Definition at line 17 of file bt617.c.
Referenced by mvme_open().
Function Documentation
vmedrv_access_mode_t bt617_GetAccessMode (MVME_INTERFACE * vme)
Definition at line 61 of file bt617.c.
References MVME_INTERFACE::am, MVME_INTERFACE::dmode, MVME_AM_A16_ND, MVME_AM_A24_ND, MVME_AM_A32_ND, MVME_DMODE_D16, MVME_DMODE_D32, VMEDRV_A16D16, VMEDRV_A16D32, VMEDRV_A24D16, VMEDRV_A24D32, VMEDRV_A32D16, and VMEDRV_A32D32.
Referenced by bt617_SetAccessMode().
{
        int dmode = vme->dmode;
        int am = vme->am;
        int enum_am, enum_dm;
        switch (am)
        {
                case MVME_AM_A32_ND:
                        enum_am = 0;
                        break;
                case MVME_AM_A24_ND:
                        enum_am = 1;
                        break;
                case MVME_AM_A16_ND:
                        enum_am = 2;
                        break;
                default:
                        enum_am = 0;
                        break;
        }
        switch (dmode)
        {
                case MVME_DMODE_D32:
                        enum_dm = 0;
                        break;
                case MVME_DMODE_D16:
                        enum_dm = 1;
                        break;
                default:
                        enum_dm = 0;
                        break;
        }
        static vmedrv_access_mode_t access_mode_tab[3][2] = {
                {VMEDRV_A32D32,VMEDRV_A32D16},
                {VMEDRV_A24D32,VMEDRV_A24D16},
                {VMEDRV_A16D32,VMEDRV_A16D16}
        };
        return access_mode_tab[enum_am][enum_dm];
}
void bt617_SetAccessMode (MVME_INTERFACE * vme)
Definition at line 103 of file bt617.c.
References bt617_GetAccessMode(), MVME_INTERFACE::handle, and VMEDRV_IOC_SET_ACCESS_MODE.
Referenced by mvme_open(), mvme_set_am(), and mvme_set_dmode().
{
        vmedrv_access_mode_t amode = bt617_GetAccessMode(vme);
        ioctl(vme->handle,VMEDRV_IOC_SET_ACCESS_MODE,&amode);
}
void bt617_SetBLT (MVME_INTERFACE * vme, bool blt)
Definition at line 274 of file bt617.c.
References MVME_INTERFACE::handle, VMEDRV_DMA, VMEDRV_IOC_SET_TRANSFER_METHOD, and VMEDRV_PIO.
Referenced by mvme_set_blt().
{
        if (blt)
        {
                int transfer_method = VMEDRV_DMA;
                ioctl(vme->handle, VMEDRV_IOC_SET_TRANSFER_METHOD, &transfer_method);
        }
        else
        {
                int transfer_method = VMEDRV_PIO;
                ioctl(vme->handle, VMEDRV_IOC_SET_TRANSFER_METHOD, &transfer_method);
        }
}
void show_mvme (MVME_INTERFACE * vme)
Definition at line 51 of file bt617.c.
References MVME_INTERFACE::am, MVME_INTERFACE::dmode, MVME_INTERFACE::handle, MVME_INTERFACE::index, and MVME_INTERFACE::initialized.
{
        printf("mvme properties:\n");
        printf("init: %d\n",vme->initialized);
        printf("handl: %d\n",vme->handle);
        printf("index: %d\n",vme->index);
        printf("am: %X\n",vme->am);
        printf("dw: %d\n",vme->dmode);
}
void showbits (uint32_t data)
Definition at line 238 of file bt617.c.
References putchar().
Referenced by v1290_FWRev(), and v1290_ReadEventFIFO().
{
 int ii;
    for (ii=31;ii>=28;ii--)
        (data&(1<<ii))?putchar('1'):putchar('0');
    putchar(' ');
    for (ii=27;ii>=24;ii--)
        (data&(1<<ii))?putchar('1'):putchar('0');
    putchar(' ');
    for (ii=23;ii>=20;ii--)
        (data&(1<<ii))?putchar('1'):putchar('0');
    putchar(' ');
    for (ii=19;ii>=16;ii--)
        (data&(1<<ii))?putchar('1'):putchar('0');
    putchar(' ');
    for (ii=15;ii>=12;ii--)
        (data&(1<<ii))?putchar('1'):putchar('0');
    putchar(' ');
    for (ii=11;ii>=8;ii--)
        (data&(1<<ii))?putchar('1'):putchar('0');
    putchar(' ');
    for (ii=7;ii>=4;ii--)
        (data&(1<<ii))?putchar('1'):putchar('0');
    putchar(' ');
    for (ii=3;ii>=0;ii--)
        (data&(1<<ii))?putchar('1'):putchar('0');
    putchar('\n');
}