AlcapDAQ: midas/drivers/divers/caenv488.c File Reference
midas/drivers/divers/caenv488.c File Reference
Defines
#define A24D16_V488 0xf0000000
#define INLINE
#define EXTERNAL extern
#define VER_SER 0xFE
#define MAN_MOD 0xFC
#define FIXED_CODE 0xFA
#define HF_REG 0x1E
#define RESET_REG 0x1C
#define CTL_REG 0x1A
#define OUTB_REG 0x18
#define FF_REG 0x16
#define RR_REG 0x14
#define THRH_REG 0x12
#define THRL_REG 0x10
#define INT_REG 0x00
#define V488_CSTART 0x8000
#define V488_IE1 0x1
#define V488_IE2 0x2
#define V488_IE3 0x4
#define V488_IE4 0x8
#define V488_IE5 0x10
#define V488_IE6 0x20
#define V488_IE7 0x40
#define V488_IE8 0x80
#define V488_IE14 0xf
#define V488_IE58 0xf0
#define V488_IE18 0xff
Typedefs
typedef unsigned short int WORD
typedef unsigned long int DWORD
Functions
INLINE caenv488_HF_set (const DWORD base, const WORD mode)
INLINE caenv488_HF_get (const DWORD base, WORD *mode)
INLINE caenv488_reset (const DWORD base)
INLINE caenv488_CTL_write (const DWORD base, const WORD mode)
INLINE caenv488_CTL_read (const DWORD base, WORD *mode)
INLINE caenv488_RR_write (const DWORD base, const WORD mode)
INLINE caenv488_THRH_write (const DWORD base, const WORD mode)
INLINE caenv488_THRL_write (const DWORD base, const WORD mode)
INLINE caenv488_FF_set (const DWORD base)
INLINE caenv488_read (const DWORD base, WORD **data)
void caenv488 (void)
INLINE void caenv488_MIW (DWORD base)
INLINE void caenv488_status (DWORD base)
INLINE void caenv488_cstop_set (DWORD base)
INLINE void caenv488_cstart_set (DWORD base)
INLINE void caenv488_all_enable (DWORD base)
INLINE void caenv488_all_disable (DWORD base)
INLINE void caenv488_std_init (DWORD base)
void caenv488_outb_read (DWORD base)
Define Documentation
#define A24D16_V488 0xf0000000
Definition at line 24 of file caenv488.c.
Referenced by caenv488_CTL_read(), caenv488_CTL_write(), caenv488_FF_set(), caenv488_HF_get(), caenv488_HF_set(), caenv488_MIW(), caenv488_outb_read(), caenv488_read(), caenv488_reset(), caenv488_RR_write(), caenv488_status(), caenv488_THRH_write(), and caenv488_THRL_write().
#define CTL_REG 0x1A
Definition at line 54 of file caenv488.c.
Referenced by caenv488_CTL_read(), caenv488_CTL_write(), caenv488_MIW(), and caenv488_status().
#define EXTERNAL extern
Definition at line 34 of file caenv488.c.
#define FF_REG 0x16
Definition at line 56 of file caenv488.c.
Referenced by caenv488_FF_set().
#define FIXED_CODE 0xFA
Definition at line 51 of file caenv488.c.
Referenced by caenv488_MIW().
#define HF_REG 0x1E
Definition at line 52 of file caenv488.c.
Referenced by caenv488_HF_get(), and caenv488_HF_set().
#define INLINE
Definition at line 31 of file caenv488.c.
#define INT_REG 0x00
Definition at line 60 of file caenv488.c.
#define MAN_MOD 0xFC
Definition at line 50 of file caenv488.c.
Referenced by caenv488_MIW().
#define OUTB_REG 0x18
Definition at line 55 of file caenv488.c.
Referenced by caenv488_outb_read(), and caenv488_read().
#define RESET_REG 0x1C
Definition at line 53 of file caenv488.c.
Referenced by caenv488_reset().
#define RR_REG 0x14
Definition at line 57 of file caenv488.c.
Referenced by caenv488_MIW(), caenv488_RR_write(), and caenv488_status().
#define THRH_REG 0x12
Definition at line 58 of file caenv488.c.
Referenced by caenv488_THRH_write().
#define THRL_REG 0x10
Definition at line 59 of file caenv488.c.
Referenced by caenv488_THRL_write().
#define V488_CSTART 0x8000
Definition at line 61 of file caenv488.c.
Referenced by caenv488_cstart_set().
#define V488_IE1 0x1
Definition at line 62 of file caenv488.c.
#define V488_IE14 0xf
Definition at line 70 of file caenv488.c.
#define V488_IE18 0xff
Definition at line 72 of file caenv488.c.
Referenced by caenv488_all_enable().
#define V488_IE2 0x2
Definition at line 63 of file caenv488.c.
#define V488_IE3 0x4
Definition at line 64 of file caenv488.c.
#define V488_IE4 0x8
Definition at line 65 of file caenv488.c.
#define V488_IE5 0x10
Definition at line 66 of file caenv488.c.
#define V488_IE58 0xf0
Definition at line 71 of file caenv488.c.
#define V488_IE6 0x20
Definition at line 67 of file caenv488.c.
#define V488_IE7 0x40
Definition at line 68 of file caenv488.c.
#define V488_IE8 0x80
Definition at line 69 of file caenv488.c.
#define VER_SER 0xFE
Definition at line 49 of file caenv488.c.
Referenced by caenv488_MIW().
Typedef Documentation
typedef unsigned long int DWORD
Definition at line 44 of file caenv488.c.
typedef unsigned short int WORD
Definition at line 39 of file caenv488.c.
Function Documentation
void caenv488 (void)
Definition at line 175 of file caenv488.c.
{
   printf("\n CAEN V488 8ch. TDC Tool Box\n");
   printf("Inline : caenv488_HF_set(DWORD vmeBase);\n");
   printf("Inline : caenv488_HF_get(DWORD vmeBase, INT * mode);\n");
   printf("Inline : caenv488_reset(DWORD vmeBase);\n");
   printf("Inline : caenv488_CTL_write(DWORD vmeBase, WORD mode);\n");
   printf("Inline : caenv488_CTL_read(DWORD vmeBase, WORD * mode);\n");
   printf("Inline : caenv488_RR_write(DWORD vmeBase, WORD mode);\n");
   printf("Inline : caenv488_THRH_write(DWORD vmeBase, WORD value);\n");
   printf("Inline : caenv488_FF_set(DWORD vmeBase, WORD value);\n");
   printf("Inline : caenv488_read(DWORD vmeBase, WORD ** data);\n");
   printf("Test   : caenv488_MIW(DWORDS base)\n");
   printf("Test   : caenv488_status(DWORD base)\n");
   printf("Test   : caenv488_cstop_set(DWORDS base)\n");
   printf("Test   : caenv488_cstart_set(DWORDS base)\n");
   printf("Test   : caenv488_all_enable(DWORDS base)\n");
   printf("Test   : caenv488_all_disable(DWORDS base)\n");
   printf("Test   : caenv488_std_init(DWORDS base)\n");
   printf("Test   : caenv488_outb_read(DWORDS base)\n");
}
INLINE void caenv488_all_disable (DWORD base)
Definition at line 287 of file caenv488.c.
References caenv488_CTL_write().
{
   caenv488_CTL_write(base, 0x0);
}
INLINE void caenv488_all_enable (DWORD base)
Definition at line 282 of file caenv488.c.
References caenv488_CTL_write(), and V488_IE18.
Referenced by caenv488_std_init().
{
   caenv488_CTL_write(base, V488_IE18);
}
INLINE void caenv488_cstart_set (DWORD base)
Definition at line 277 of file caenv488.c.
References caenv488_CTL_write(), and V488_CSTART.
{
   caenv488_CTL_write(base, V488_CSTART);
}
INLINE void caenv488_cstop_set (DWORD base)
Definition at line 268 of file caenv488.c.
References caenv488_CTL_read(), and caenv488_CTL_write().
{
   WORD ctl;
   caenv488_CTL_read(base, &ctl);
   ctl &= 0x70ff;
   caenv488_CTL_write(base, ctl);
}
INLINE caenv488_CTL_read (const DWORD base, WORD * mode)
Definition at line 113 of file caenv488.c.
References A24D16_V488, and CTL_REG.
Referenced by caenv488_cstop_set().
{
   volatile WORD *spec_adr;
   spec_adr = (WORD *) (A24D16_V488 | base | CTL_REG);
   *mode = *spec_adr;
}
INLINE caenv488_CTL_write (const DWORD base, const WORD mode)
Definition at line 102 of file caenv488.c.
References A24D16_V488, and CTL_REG.
Referenced by caenv488_all_disable(), caenv488_all_enable(), caenv488_cstart_set(), and caenv488_cstop_set().
{
   volatile WORD *spec_adr;
   volatile WORD ctl;
   spec_adr = (WORD *) (A24D16_V488 | base | CTL_REG);
   ctl = *spec_adr;
   ctl |= mode & 0x80ff;
   *spec_adr = ctl & 0x80ff;
}
INLINE caenv488_FF_set (const DWORD base)
Definition at line 145 of file caenv488.c.
References A24D16_V488, and FF_REG.
{
   volatile WORD *spec_adr;
   spec_adr = (WORD *) (A24D16_V488 | base | FF_REG);
   *spec_adr = 0x0;
}
INLINE caenv488_HF_get (const DWORD base, WORD * mode)
Definition at line 85 of file caenv488.c.
References A24D16_V488, and HF_REG.
{
   volatile WORD *spec_adr;
   spec_adr = (WORD *) (A24D16_V488 | base | HF_REG);
   *mode = *spec_adr;
   *mode = (*mode >> 12) & 0x1;
}
INLINE caenv488_HF_set (const DWORD base, const WORD mode)
Definition at line 74 of file caenv488.c.
References A24D16_V488, and HF_REG.
{
   volatile WORD *spec_adr;
   spec_adr = (WORD *) (A24D16_V488 | base | HF_REG);
   if (mode)
      *spec_adr = 0x1 << 12;
   else
      *spec_adr = 0x0;
}
INLINE void caenv488_MIW (DWORD base)
Definition at line 197 of file caenv488.c.
References A24D16_V488, CTL_REG, data, FIXED_CODE, MAN_MOD, RR_REG, and VER_SER.
{
   volatile WORD *spec_adr;
   volatile WORD data;
   /* module */
   spec_adr = (WORD *) (A24D16_V488 | base | VER_SER);
   data = *spec_adr;
   printf("Version  : 0x%x - Serial#   : 0x%x\n", (data >> 12) & 0xf, data & 0xfff);
   spec_adr = (WORD *) (A24D16_V488 | base | MAN_MOD);
   data = *spec_adr;
   printf("Manuf.#  : 0x%x - Mod. type#: 0x%x\n", (data >> 10) & 0x3f, data & 0x3ff);
   spec_adr = (WORD *) (A24D16_V488 | base | FIXED_CODE);
   data = *spec_adr;
   printf("FA code  : 0x%x - F5 code  : 0x%x\n", (data >> 8) & 0xff, data & 0xff);
   /* RR */
   spec_adr = (WORD *) (A24D16_V488 | base | RR_REG);
   data = *spec_adr;
   if (data & 0x1000)
      printf("Mode FIFO full      - ");
   else
      printf("Mode FIFO half full - ");
   /* CTL */
   spec_adr = (WORD *) (A24D16_V488 | base | CTL_REG);
   data = *spec_adr;
   printf("Ch.enable: 0x%x \n", data & 0xff);
   if (data & 0x8000)
      printf("Common Start  - ");
   else
      printf("Common Stop   - ");
   if (data & 0x4000)
      printf("FIFO empty\n");
   else if (data & 0x2000)
      printf("FIFO Full\n");
   else if (data & 0x1000)
      printf("FIFO half full\n");
}
void caenv488_outb_read (DWORD base)
Definition at line 301 of file caenv488.c.
References A24D16_V488, data, and OUTB_REG.
{
   volatile WORD *spec_adr;
   volatile WORD data, header = 0;
   /* CTL */
   spec_adr = (WORD *) (A24D16_V488 | base | OUTB_REG);
   data = *spec_adr;
   for (;;) {
      if (data & 0x8000) {
         header = 1;
         printf("OutB header: 0x%x - ", data);
         printf("OutB multi : %d - event# : %d\n", ((data >> 12) & 0x7) + 1,
                data & 0xfff);
         if (((data >> 12) & 0x7) == 0)
            break;
      } else {
         if (header) {
            header = 0;
            printf("OutB data  : 0x%x - ", data);
            printf("OutB chan. : %d - data# : %d\n", (data >> 12) & 0x7, data & 0xfff);
            if (((data >> 12) & 0x7) == 0)
               break;
         } else {
            printf("OutB data  : 0x%x - No header\n", data);
            break;
         }
      }
   }
}
INLINE caenv488_read (const DWORD base, WORD ** data)
Definition at line 153 of file caenv488.c.
References A24D16_V488, and OUTB_REG.
{
   volatile WORD *spec_adr;
   int header, mult;
   spec_adr = (WORD *) (A24D16_V488 | base | OUTB_REG);
   header = *spec_adr;
   if (header & 0x8000) {
      if ((header & 0xfff) != 1)
         logMsg("Event counter in V488 base:0x%x = %d", base, (header & 0xfff), 0, 0, 0,
                0);
      else {
         mult = (header >> 12) & 0x7;
         while (mult > 0) {
            *((*data)++) = *spec_adr;
         }
      }
   } else
      logMsg("Event out of sequence in V488 base 0x%x", base, 0, 0, 0, 0, 0);
}
INLINE caenv488_reset (const DWORD base)
Definition at line 94 of file caenv488.c.
References A24D16_V488, and RESET_REG.
Referenced by caenv488_std_init().
{
   volatile WORD *spec_adr;
   spec_adr = (WORD *) (A24D16_V488 | base | RESET_REG);
   *spec_adr = 0x0;
}
INLINE caenv488_RR_write (const DWORD base, const WORD mode)
Definition at line 121 of file caenv488.c.
References A24D16_V488, and RR_REG.
Referenced by caenv488_std_init().
{
   volatile WORD *spec_adr;
   spec_adr = (WORD *) (A24D16_V488 | base | RR_REG);
   *spec_adr = mode & 0x11ff;
}
INLINE void caenv488_status (DWORD base)
Definition at line 238 of file caenv488.c.
References A24D16_V488, CTL_REG, data, and RR_REG.
{
   volatile WORD *spec_adr;
   volatile WORD data;
   /* CTL */
   spec_adr = (WORD *) (A24D16_V488 | base | CTL_REG);
   data = *spec_adr;
   printf("CTL status: 0x%x - Ch.enable: 0x%x \n", data, data & 0xff);
   if (data & 0x8000)
      printf("Common Start       - ");
   else
      printf("Common Stop        - ");
   if (!(data & 0x4000))
      printf("FIFO empty\n");
   else if (!(data & 0x2000))
      printf("FIFO Full\n");
   else if (!(data & 0x1000))
      printf("FIFO half full\n");
   /* RR */
   spec_adr = (WORD *) (A24D16_V488 | base | RR_REG);
   data = *spec_adr;
   if (data & 0x1000)
      printf("Mode FIFO full     \n");
   else
      printf("Mode FIFO half full\n");
}
INLINE void caenv488_std_init (DWORD base)
Definition at line 292 of file caenv488.c.
References caenv488_all_enable(), caenv488_reset(), caenv488_RR_write(), caenv488_THRH_write(), and caenv488_THRL_write().
{
   caenv488_reset(base);
   caenv488_THRH_write(base, 0xc7);
   caenv488_THRL_write(base, 0x00);
   caenv488_RR_write(base, 0xe0);
   caenv488_all_enable(base);
}
INLINE caenv488_THRH_write (const DWORD base, const WORD mode)
Definition at line 129 of file caenv488.c.
References A24D16_V488, and THRH_REG.
Referenced by caenv488_std_init().
{
   volatile WORD *spec_adr;
   spec_adr = (WORD *) (A24D16_V488 | base | THRH_REG);
   *spec_adr = mode & 0xff;
}
INLINE caenv488_THRL_write (const DWORD base, const WORD mode)
Definition at line 137 of file caenv488.c.
References A24D16_V488, and THRL_REG.
Referenced by caenv488_std_init().
{
   volatile WORD *spec_adr;
   spec_adr = (WORD *) (A24D16_V488 | base | THRL_REG);
   *spec_adr = mode & 0xff;
}