AlcapDAQ: midas/drivers/bus/ces8210.h File Reference
midas/drivers/bus/ces8210.h File Reference
Defines
#define BASE 0x00800000
#define A32D24 0xf0000000
#define A32D16 0xf0000002
#define CSR_OFFSET 0x0000e800
#define CAR_OFFSET 0x0000e820
#define BTB_OFFSET 0x0000e824
#define INT_OFFSET 0x0000e810
#define GL 0x0000e828
#define GLR BASE | GL | A32D24
#define CSR BASE | CSR_OFFSET | A32D16
#define CAR BASE | CAR_OFFSET | A32D16
#define BTB BASE | BTB_OFFSET | A32D16
#define IFR BASE | INT_OFFSET | A32D16
#define IT4 0x0001
#define IT2 0x0002
#define MIT4 0x0004
#define MIT2 0x0008
#define CAM_BC(_ext, _b, _c)
#define CAM_N(_ext, _n) { *_ext |= _n<<11;}
#define CAM_A(_ext, _a) { *_ext |= _a<<7;}
#define CAM_F(_ext, _f) { *_ext |= _f<<2;}
#define CAM_Ncl(_ext, _n) { *_ext = ((*_ext & ~(0x1f << 11)) | (_n << 11));}
#define CAM_Acl(_ext, _a) { *_ext = ((*_ext & ~(0xf << 7)) | (_a << 7));}
#define CAM_Fcl(_ext, _f) { *_ext = ((*_ext & ~(0x1f << 2)) | (_f << 2));}
#define CAM_CSRCHK(_w)
#define CAM_CARCHK(_w)
#define CAM_BTBCHK(_w)
#define CAM_GLCHK(_w)
#define CAM_QXCHK(_q, _x)
#define CAM16_I(_ext, _n, _a, _f, _d)
#define CAM16_IQX(_ext, _n, _a, _f, _d, _q, _x)
#define CAM16_IR(_ext, _n, _a, _f, _d, _r)
#define CAM16_IRQ(_ext, _n, _a, _f, _d, _r)
#define CAM16_IAS(_ext, _n, _a, _f, _d, _r)
#define CAM16_IASQ(_ext, _n, _a, _f, _d, _r)
#define CAM24_I(_ext, _n, _a, _f, _d)
#define CAM24_IQX(_ext, _n, _a, _f, _d, _q, _x)
#define CAM24_IR(_ext, _n, _a, _f, _d, _r)
#define CAM24_IRQ(_ext, _n, _a, _f, _d, _r)
#define CAM24_IAS(_ext, _n, _a, _f, _d, _r)
#define CAM24_INS(_ext, _n, _a, _f, _d, _r)
#define CAM16_O(_ext, _n, _a, _f, _d)
#define CAM16_OQX(_ext, _n, _a, _f, _d, _q, _x)
#define CAM24_O(_ext, _n, _a, _f, _d)
#define CAM24_OQX(_ext, _n, _a, _f, _d, _q, _x)
#define CAM_COM(_b, _c, _n, _a, _f)
#define CAM_CMD(_ext, _n, _a, _f)
#define CAM_CMDAS(_ext, _n, _a, _f, _r)
#define CAM_CMDNS(_ext, _n, _a, _f, _r)
Functions
void cdreg (int *ext, int b, int c, int n, int a)
void cfsa (int f, int ext, int *data, int *q)
void cssa (int f, int ext, short *data, int *q)
void ctstat (int *istat)
Define Documentation
#define A32D16 0xf0000002
Definition at line 73 of file ces8210.h.
#define A32D24 0xf0000000
Definition at line 72 of file ces8210.h.
Referenced by sis3803_all_clear(), sis3803_all_disable(), sis3803_all_enable(), sis3803_all_read(), sis3803_all_read_clear(), sis3803_channel_disable(), sis3803_channel_enable(), sis3803_counter_read(), sis3803_CSR_read(), sis3803_CSR_write(), sis3803_grp1_clear(), sis3803_grp1_read(), sis3803_grp2_clear(), sis3803_grp2_read(), sis3803_input_mode(), sis3803_int_attach(), sis3803_int_clear(), sis3803_int_source(), sis3803_int_source_disable(), sis3803_int_source_enable(), sis3803_IRQ_REG_read(), sis3803_IRQ_REG_write(), sis3803_module_ID(), sis3803_module_reset(), sis3803_OVFL_grp1_read(), sis3803_OVFL_grp2_read(), sis3803_ref1(), sis3803_single_clear(), sis3803_single_OVFL_clear(), sis3803_test_disable(), sis3803_test_enable(), vmeio_async_read(), vmeio_clear(), vmeio_int_clear(), vmeio_int_disable(), vmeio_int_enable(), vmeio_intsync_set(), vmeio_latch_write(), vmeio_pulse_set(), vmeio_pulse_write(), vmeio_status_read(), and vmeio_sync_read().
#define BASE 0x00800000
Definition at line 71 of file ces8210.h.
#define BTB BASE | BTB_OFFSET | A32D16
Definition at line 83 of file ces8210.h.
#define BTB_OFFSET 0x0000e824
Definition at line 76 of file ces8210.h.
#define CAM16_I (_ext, _n, _a, _f, _d)
Value:
{\
                                    *_ext &= 0xffff0000;\
                                    CAM_N(_ext,_n);\
                                    CAM_A(_ext,_a);\
                                    CAM_F(_ext,_f);\
                                    *(WORD *) _d = *(WORD *) (*_ext | 0x2);}
Definition at line 140 of file ces8210.h.
#define CAM16_IAS (_ext, _n, _a, _f, _d, _r)
Value:
{\
                                         *_ext &= 0xffff0000;\
                                         CAM_N(_ext,_n);\
                                         CAM_F(_ext,_f);\
                                         {\
                                            DWORD rr, aa, cbd_csr;\
                                            WORD csr;\
                                            aa=_a;\
                                            rr=_r;\
                                            do\
                                            {\
                                               CAM_Acl(_ext,aa);\
                                               *(WORD *) _d = *(WORD *) (*_ext | 0x2);\
                                               ((WORD *) _d)++;\
                                               rr--;\
                                               aa++;\
                                           } while (rr > 0);}\
                                     }
Definition at line 187 of file ces8210.h.
#define CAM16_IASQ (_ext, _n, _a, _f, _d, _r)
Value:
{\
                                          *_ext &= 0xffff0000;\
                                          CAM_N(_ext,_n);\
                                          CAM_F(_ext,_f);\
                                          {\
                                             DWORD rr = _r;\
                                             DWORD aa;\
                                             WORD csr;\
                                             DWORD cbd_csr = CSR;\
                                             aa=_a;\
                                             rr=_r;\
                                             do\
                                             {\
                                                CAM_Acl(_ext,aa);\
                                                *(WORD *) _d = *(WORD *) (*_ext | 0x2);\
                                                csr = *(WORD *) cbd_csr;\
                                                if ((csr & 0x8000) == 0) {\
                                                                            rr=0;\
                                                                        }\
                                                else {\
                                                        rr--;\
                                                        aa++;\
                                                        ((WORD *) _d)++;}\
                                            } while (rr > 0);}\
                                      }
Definition at line 206 of file ces8210.h.
#define CAM16_IQX (_ext, _n, _a, _f, _d, _q, _x)
Value:
{\
                                            CAM16_I(_ext,_n,_a,_f,_d);\
                                            CAM_QXCHK(_q,_x);}
Definition at line 147 of file ces8210.h.
#define CAM16_IR (_ext, _n, _a, _f, _d, _r)
Value:
{\
                                        *_ext &= 0xffff0000;\
                                        CAM_N(_ext,_n);\
                                        CAM_F(_ext,_f);\
                                        CAM_A(_ext,_a);\
                                        {\
                                           DWORD rr;\
                                           rr=_r;\
                                           do {\
                                                 *(WORD *) _d = *(WORD *) (*_ext | 0x2);\
                                                 ((WORD *) _d)++;\
                                                 rr--;} while (rr > 0);\
                                       }\
                                    }
Definition at line 151 of file ces8210.h.
#define CAM16_IRQ (_ext, _n, _a, _f, _d, _r)
Value:
{\
                                         *_ext &= 0xffff0000;\
                                         CAM_N(_ext,_n);\
                                         CAM_A(_ext,_a);\
                                         CAM_F(_ext,_f);\
                                         {\
                                            DWORD rr = _r;\
                                            WORD csr;\
                                            DWORD cbd_csr = CSR;\
                                            do {\
                                                  *(WORD *) _d = *(WORD *) (*_ext | 0x2);\
                                                  csr = *(WORD *) cbd_csr;\
                                                  if ((csr & 0x8000) == 0) {\
                                                                              rr=0;\
                                                                          }\
                                                  else {\
                                                          rr--;\
                                                          ((WORD *) _d)++; }\
                                              } while (rr > 0);}\
                                     }
Definition at line 166 of file ces8210.h.
#define CAM16_O (_ext, _n, _a, _f, _d)
Value:
{\
                                    *_ext &= 0xffff0000;\
                                    CAM_N(_ext,_n);\
                                    CAM_A(_ext,_a);\
                                    CAM_F(_ext,_f);\
                                    *(WORD *) (*_ext | 0x2) =  (WORD) _d;}
Definition at line 312 of file ces8210.h.
#define CAM16_OQX (_ext, _n, _a, _f, _d, _q, _x)
Value:
{\
                                            CAM16_O(_ext,_n,_a,_f,_d);\
                                            CAM_QXCHK(_q,_x);}
Definition at line 319 of file ces8210.h.
#define CAM24_I (_ext, _n, _a, _f, _d)
Value:
{\
                                    *_ext &= 0xffff0000;\
                                    CAM_N(_ext,_n);\
                                    CAM_A(_ext,_a);\
                                    CAM_F(_ext,_f);\
                 *(DWORD *) _d = *(DWORD *) *_ext;}
Definition at line 232 of file ces8210.h.
#define CAM24_IAS (_ext, _n, _a, _f, _d, _r)
Value:
{\
                                         *_ext &= 0xffff0000;\
                                         CAM_N(_ext,_n);\
                                         CAM_F(_ext,_f);\
                                         {\
                                            DWORD rr,aa;\
                                            WORD csr;\
                                            aa=_a;\
                                            rr=_r;\
                                            do {\
                                                  CAM_Acl(_ext,aa);\
                                                  *(DWORD *) _d++ = *(DWORD *) *_ext;\
                                                  rr--;\
                                                  aa++;\
                                        } while (rr > 0); }\
                                     }
Definition at line 278 of file ces8210.h.
#define CAM24_INS (_ext, _n, _a, _f, _d, _r)
Value:
{\
                                         *_ext &= 0xffff0000;\
                                         CAM_A(_ext,_a);\
                                         CAM_F(_ext,_f);\
                                         {\
                                            DWORD rr, nn;\
                                            WORD csr;\
                                            nn=_n;\
                                            rr=_r;\
                                            do {\
                                                  CAM_Ncl(_ext,nn);\
                                                  *(DWORD *) _d++ = *(DWORD *) *_ext;\
                                                  rr--;\
                                                  nn++;\
                                        } while (rr > 0); }\
                                     }
Definition at line 295 of file ces8210.h.
#define CAM24_IQX (_ext, _n, _a, _f, _d, _q, _x)
Value:
{\
                                            CAM24_I(_ext,_n,_a,_f,_d);\
                                            CAM_QXCHK(_q,_x);}
Definition at line 239 of file ces8210.h.
#define CAM24_IR (_ext, _n, _a, _f, _d, _r)
Value:
{\
                                        *_ext &= 0xffff0000;\
                                        CAM_N(_ext,_n);\
                                        CAM_A(_ext,_a);\
                                        CAM_F(_ext,_f);\
                                        {\
                                           DWORD rr;\
                                           rr=_r;\
                                           do {\
                                                 *((DWORD *)_d)++ = *(DWORD *) *_ext;\
                                                 rr--;}\
                                           while (rr > 0);}\
                                    }
Definition at line 243 of file ces8210.h.
#define CAM24_IRQ (_ext, _n, _a, _f, _d, _r)
Value:
{\
                                         *_ext &= 0xffff0000;\
                                         CAM_N(_ext,_n);\
                                         CAM_A(_ext,_a);\
                                         CAM_F(_ext,_f);\
                                         {\
                                            WORD csr;\
                                            DWORD cbd_csr = CSR;\
                                            DWORD rr=_r;\
                                            do {\
                                                  *((DWORD *)_d) = *(DWORD *) *_ext;\
                                                  csr = *(WORD *) cbd_csr;\
                                                  if ((csr & 0x8000) == 0) {\
                                                                              rr=0;\
                                                                          }\
                                                  else {\
                                                          rr--;\
                                                          (DWORD *) _d++; }\
                                              } while (rr > 0); }\
                                     }
Definition at line 257 of file ces8210.h.
#define CAM24_O (_ext, _n, _a, _f, _d)
Value:
{\
                                    *_ext &= 0xffff0000;\
                                    CAM_N(_ext,_n);\
                                    CAM_A(_ext,_a);\
                                    CAM_F(_ext,_f);\
                                    *(DWORD *) (*_ext) = (DWORD) _d;}
Definition at line 323 of file ces8210.h.
#define CAM24_OQX (_ext, _n, _a, _f, _d, _q, _x)
Value:
{\
                                            CAM24_O(_ext,_n,_a,_f,_d);\
                                            CAM_QXCHK(_q,_x);}
Definition at line 330 of file ces8210.h.
#define CAM_A (_ext, _a) { *_ext |= _a<<7;}
Definition at line 109 of file ces8210.h.
#define CAM_Acl (_ext, _a) { *_ext = ((*_ext & ~(0xf << 7)) | (_a << 7));}
Definition at line 114 of file ces8210.h.
#define CAM_BC (_ext, _b, _c)
Value:
{\
                             DWORD cbd_base = 0xf0000000 | BASE;\
                             {\
                                DWORD __w;\
                                CAM_BTBCHK (&__w);\
                                if ( ((__w >> _c) & 0x1) != 1)\
                                {\
                                   printf("crate %i not existant\n",_c);\
                                   *_ext = 0;\
                               }\
                                else\
                                *_ext = cbd_base|_b<<19|_c<<16;}\
                         }
Definition at line 93 of file ces8210.h.
#define CAM_BTBCHK (_w)
Value:
{\
                         DWORD cbd_btb = BTB;\
                         *_w = *(WORD *) cbd_btb;}
Definition at line 126 of file ces8210.h.
#define CAM_CARCHK (_w)
Value:
{\
                         DWORD cbd_car = CAR;\
                         *_w = *(WORD *) cbd_car;}
Definition at line 122 of file ces8210.h.
#define CAM_CMD (_ext, _n, _a, _f)
Value:
{\
                               *_ext &= 0xffff0000;\
                               {\
                                  static DWORD __d;\
                                  CAM_N(_ext,_n);\
                                  CAM_A(_ext,_a);\
                                  CAM_F(_ext,_f);\
                                  __d = *(DWORD *) *_ext;}\
                           }
Definition at line 344 of file ces8210.h.
#define CAM_CMDAS (_ext, _n, _a, _f, _r)
Value:
{\
                                      *_ext &= 0xffff0000;\
                                      {\
                                         static DWORD aa, rr, __d;\
                                         CAM_N(_ext,_n);\
                                         CAM_F(_ext,_f);\
                                         rr = _r;\
                                         aa = _a;\
                                         do {\
                                               CAM_Acl(_ext,aa);\
                                               __d = *(DWORD *) *_ext;\
                                               rr--;\
                                               aa++;} while (rr > 0);\
                                     }\
                                  }
Definition at line 354 of file ces8210.h.
#define CAM_CMDNS (_ext, _n, _a, _f, _r)
Value:
{\
                                      *_ext &= 0xffff0000;\
                                      {\
                                         static DWORD nn, rr, __d;\
                                         CAM_A(_ext,_a);\
                                         CAM_F(_ext,_f);\
                                         rr = _r;\
                                         nn = _n;\
                                         do {\
                                               CAM_Ncl(_ext,nn);\
                                               __d = *(DWORD *) *_ext;\
                                               rr--;\
                                               nn++;} while (rr > 0);\
                                     }\
                                  }
Definition at line 370 of file ces8210.h.
#define CAM_COM (_b, _c, _n, _a, _f)
Value:
{\
                                  {\
                                     static DWORD __ext, __d;\
                                     CAM_BC(&__ext,_b,_c);\
                                     CAM_N(&__ext,_n);\
                                     CAM_A(&__ext,_a);\
                                     CAM_F(&__ext,_f);\
                                     __d = *(DWORD *) __ext;\
                                 }\
                              }
Definition at line 333 of file ces8210.h.
#define CAM_CSRCHK (_w)
Value:
{\
                         DWORD cbd_csr = CSR;\
                         *_w = *(WORD *) cbd_csr;}
Definition at line 118 of file ces8210.h.
#define CAM_F (_ext, _f) { *_ext |= _f<<2;}
Definition at line 110 of file ces8210.h.
#define CAM_Fcl (_ext, _f) { *_ext = ((*_ext & ~(0x1f << 2)) | (_f << 2));}
Definition at line 115 of file ces8210.h.
#define CAM_GLCHK (_w)
Value:
{\
                         DWORD cbd_gl = GLR;\
                         *_w = *(DWORD *) cbd_gl;}
Definition at line 130 of file ces8210.h.
#define CAM_N (_ext, _n) { *_ext |= _n<<11;}
Definition at line 108 of file ces8210.h.
#define CAM_Ncl (_ext, _n) { *_ext = ((*_ext & ~(0x1f << 11)) | (_n << 11));}
Definition at line 113 of file ces8210.h.
#define CAM_QXCHK (_q, _x)
Value:
{\
                           DWORD cbd_csr = CSR;\
                           WORD csr = *(WORD *) cbd_csr;\
                           *_q = ((csr & 0x8000)>>15);\
                           *_x = ((csr & 0x4000)>>14);}
Definition at line 134 of file ces8210.h.
#define CAR BASE | CAR_OFFSET | A32D16
Definition at line 82 of file ces8210.h.
#define CAR_OFFSET 0x0000e820
Definition at line 75 of file ces8210.h.
#define CSR BASE | CSR_OFFSET | A32D16
Definition at line 81 of file ces8210.h.
#define CSR_OFFSET 0x0000e800
Definition at line 74 of file ces8210.h.
#define GL 0x0000e828
Definition at line 78 of file ces8210.h.
#define GLR BASE | GL | A32D24
Definition at line 80 of file ces8210.h.
#define IFR BASE | INT_OFFSET | A32D16
Definition at line 84 of file ces8210.h.
#define INT_OFFSET 0x0000e810
Definition at line 77 of file ces8210.h.
#define IT2 0x0002
Definition at line 87 of file ces8210.h.
#define IT4 0x0001
Definition at line 86 of file ces8210.h.
#define MIT2 0x0008
Definition at line 89 of file ces8210.h.
#define MIT4 0x0004
Definition at line 88 of file ces8210.h.
Function Documentation
void cdreg (int * ext, const int b, const int c, const int n, const int a)
Control Declaration REGister.
Compose an external address from BCNA for later use. Accessing CAMAC through ext could be faster if the external address is memory mapped to the processor (hardware dependent). Some CAMAC controller do not have this option see AppendixB.
Parameters:
ext external address
b branch number (0..7)
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
Returns:
void
cdreg Control Declaration REGister.
Compose an external address from BCNA for later use. Accessing CAMAC through ext could be faster if the external address is memory mapped to the processor (hardware dependent). Some CAMAC controller do not have this option see {appendix D: Supported hardware}. In this case External Address register.
Parameters:
ext external address
b branch number (0..7)
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
Returns:
void
Definition at line 122 of file esone.c.
Referenced by begin_of_run(), caen170a_init(), cdlam(), isr(), lrs4032_init(), and main().
{
   came_cn(ext, b, c, n, a);
}
void cfsa (int f, int ext, int * data, int * q)
Referenced by begin_of_run(), caen170a_get(), caen170a_init(), caen170a_set(), cfga(), cfubc(), cfubr(), lrs4032_get(), lrs4032_init(), lrs4032_set(), and main().
void cssa (int f, int ext, short * data, int * q)
Referenced by csga(), csubc(), csubr(), isr(), and main().
void ctstat (int * istat)