AlcapDAQ: midas/drivers/bus/ces8210.c File Reference
midas/drivers/bus/ces8210.c File Reference
#include <stdio.h>
#include <string.h>
#include "mcstd.h"
#include "mvmestd.h"
Data Structures
struct CBD_DESC_T
Defines
#define CBD8210_BASE 0x800000
#define CBDWL_D16 0x000002
#define CBDWL_D24 0x000000
#define CSR_OFFSET 0x0000e800
#define CAR_OFFSET 0x0000e820
#define BTB_OFFSET 0x0000e824
#define CSR CBD8210_BASE | CSR_OFFSET | CBDWL_D16
#define CAR CBD8210_BASE | CAR_OFFSET | CBDWL_D16
#define BTB CBD8210_BASE | BTB_OFFSET | CBDWL_D16
#define CAM_CSRCHK(_w)
#define CAM_CARCHK(_w)
#define CAM_BTBCHK(_w)
#define CAM_QXCHK(_q, _x)
#define CAM_QCHK(_q)
#define CAM_XCHK(_x)
Functions
INLINE void cam16i (const int c, const int n, const int a, const int f, WORD *d)
INLINE void cam24i (const int c, const int n, const int a, const int f, DWORD *d)
INLINE void cam16i_q (const int c, const int n, const int a, const int f, WORD *d, int *x, int *q)
INLINE void cam24i_q (const int c, const int n, const int a, const int f, DWORD *d, int *x, int *q)
INLINE void cam16i_r (const int c, const int n, const int a, const int f, WORD **d, const int r)
INLINE void cam24i_r (const int c, const int n, const int a, const int f, DWORD **d, const int r)
INLINE void cam16i_rq (const int c, const int n, const int a, const int f, WORD **d, const int r)
INLINE void cam24i_rq (const int c, const int n, const int a, const int f, DWORD **d, const int r)
INLINE void cam16i_sa (const int c, const int n, const int a, const int f, WORD **d, const int r)
INLINE void cam24i_sa (const int c, const int n, const int a, const int f, unsigned long **d, const int r)
INLINE void cam16i_sn (const int c, const int n, const int a, const int f, WORD **d, const int r)
INLINE void cam24i_sn (const int c, const int n, const int a, const int f, DWORD **d, const int r)
INLINE void cami (const int c, const int n, const int a, const int f, WORD *d)
INLINE void cam16o (const int c, const int n, const int a, const int f, WORD d)
INLINE void cam24o (const int c, const int n, const int a, const int f, DWORD d)
INLINE void cam16o_q (const int c, const int n, const int a, const int f, WORD d, int *x, int *q)
INLINE void cam24o_q (const int c, const int n, const int a, const int f, DWORD d, int *x, int *q)
INLINE void camo (const int c, const int n, const int a, const int f, WORD d)
INLINE int camc_chk (const int c)
INLINE void camc (const int c, const int n, const int a, const int f)
INLINE void camc_q (const int c, const int n, const int a, const int f, int *q)
INLINE void camc_sa (const int c, const int n, const int a, const int f, const int r)
INLINE void camc_sn (const int c, const int n, const int a, const int f, const int r)
INLINE int cam_init (void)
INLINE void cam_exit (void)
INLINE void cam_inhibit_set (const int c)
INLINE int cam_inhibit_test (const int c)
INLINE void cam_inhibit_clear (const int c)
INLINE void cam_crate_clear (const int c)
INLINE void cam_crate_zinit (const int c)
INLINE void cam_lam_enable (const int c, const int n)
INLINE void cam_lam_disable (const int c, const int n)
INLINE void cam_lam_read (const int c, DWORD *lam)
INLINE void cam_lam_clear (const int c, const int n)
INLINE void cam_interrupt_enable (const int c)
INLINE void cam_interrupt_disable (const int c)
INLINE int cam_interrupt_test (const int c)
INLINE void cam_interrupt_attach (const int c, const int n, void(*isr)(void))
INLINE void cam_interrupt_detach (const int c, const int n)
INLINE void cam_glint_enable (void)
INLINE void cam_glint_disable (void)
INLINE void cam_glint_attach (int lam, void(*isr)(void))
void csr (void)
void car (void)
void btb (void)
void camop (void)
Variables
CBD_DESC_T cbd [8]
int vh
Define Documentation
#define BTB CBD8210_BASE | BTB_OFFSET | CBDWL_D16
Definition at line 86 of file ces8210.c.
#define BTB_OFFSET 0x0000e824
Definition at line 83 of file ces8210.c.
#define CAM_BTBCHK (_w)
Value:
{\
       DWORD cbd_btb = cbd[0].baseCrate | BTB;\
                         *_w = *(WORD *) cbd_btb;}
Definition at line 96 of file ces8210.c.
Referenced by btb(), and camc_chk().
#define CAM_CARCHK (_w)
Value:
{\
       DWORD cbd_car = cbd[0].baseCrate | CAR;\
       *_w = *(WORD *) cbd_car;}
Definition at line 92 of file ces8210.c.
Referenced by car().
#define CAM_CSRCHK (_w)
Value:
{\
       DWORD cbd_csr = cbd[0].baseCrate | CSR;\
       *_w = *(WORD *) cbd_csr;}
Definition at line 88 of file ces8210.c.
Referenced by csr().
#define CAM_QCHK (_q)
Value:
{\
       DWORD cbd_csr = cbd[0].baseCrate | CSR;\
       WORD csr = *((WORD *) cbd_csr);\
       *_q = ((csr & 0x8000)>>15);}
Definition at line 106 of file ces8210.c.
#define CAM_QXCHK (_q, _x)
Value:
{\
       DWORD cbd_csr = cbd[0].baseCrate | CSR;\
       WORD csr = *((WORD *) cbd_csr);\
       *_q = ((csr & 0x8000)>>15);\
       *_x = ((csr & 0x4000)>>14);}
Definition at line 100 of file ces8210.c.
#define CAM_XCHK (_x)
Value:
{\
       DWORD cbd_csr = cbd[0].baseCrate | CSR;\
       WORD csr = *((WORD *) cbd_csr);\
       *_x = ((csr & 0x4000)>>14);}
Definition at line 110 of file ces8210.c.
#define CAR CBD8210_BASE | CAR_OFFSET | CBDWL_D16
Definition at line 85 of file ces8210.c.
Referenced by lrs2373_set().
#define CAR_OFFSET 0x0000e820
Definition at line 82 of file ces8210.c.
#define CBD8210_BASE 0x800000
Definition at line 78 of file ces8210.c.
Referenced by cam_init().
#define CBDWL_D16 0x000002
Definition at line 79 of file ces8210.c.
Referenced by cam16i(), and cam16o().
#define CBDWL_D24 0x000000
Definition at line 80 of file ces8210.c.
Referenced by cam24i(), and cam24o().
#define CSR CBD8210_BASE | CSR_OFFSET | CBDWL_D16
Definition at line 84 of file ces8210.c.
Referenced by cam16i_q(), cam16i_r(), cam16i_sa(), cam16o_q(), cam16o_r(), cam24i(), cam24i_q(), cam24i_r(), cam24i_sa(), cam24o(), cam24o_q(), cam24o_r(), camc(), camc_chk(), camc_q(), cami(), camo(), interprete(), and setup().
#define CSR_OFFSET 0x0000e800
Definition at line 81 of file ces8210.c.
Function Documentation
void btb (void)
Definition at line 597 of file ces8210.c.
References CAM_BTBCHK, and online.
Referenced by camop().
{
   WORD online;
   CAM_BTBCHK(&online);
   printf("BTB Online status 0x%4.4x\n", online);
}
INLINE void cam24i_sa (const int c, const int n, const int a, const int f, unsigned long ** d, const int r)
Definition at line 247 of file ces8210.c.
References cam24i().
{
   int aa;
   for (aa = a; aa < a + r; aa++)
      cam24i(c, n, aa, f, (*d)++);
}
INLINE void cam_glint_attach (int lam, void(*)(void) isr)
Definition at line 576 of file ces8210.c.
{
   printf("cam_glint_attach - Not yet implemented\n");
}
INLINE void cam_glint_disable (void)
Definition at line 569 of file ces8210.c.
{
   printf("cam_glint_disable - Not yet implemented\n");
}
INLINE void cam_glint_enable (void)
Definition at line 562 of file ces8210.c.
{
   printf("cam_glint_enable - Not yet implemented\n");
}
void camop (void)
Definition at line 605 of file ces8210.c.
References btb(), car(), and csr().
{
   csr();
   car();
   btb();
}
void car (void)
Definition at line 589 of file ces8210.c.
References CAM_CARCHK, and online.
Referenced by camop().
{
   WORD online;
   CAM_CARCHK(&online);
   printf("CAR Online status 0x%4.4x\n", online);
}
void csr (void)
Definition at line 581 of file ces8210.c.
References CAM_CSRCHK, and online.
Referenced by cam16i_q(), cam16i_rq(), cam16o_q(), cam24i_q(), cam24i_rq(), cam24o_q(), cam_lam_read(), camc_q(), camop(), sis3600_bor1(), sis3600_fifo_read(), and SIS3803_CSR_read().
{
   WORD online;
   CAM_CSRCHK(&online);
   printf("CSR Camac  status 0x%4.4x\n", online);
}
Variable Documentation
CBD_DESC_T cbd[8]
Definition at line 75 of file ces8210.c.
int vh
Definition at line 116 of file ces8210.c.
Referenced by cam_exit(), and cam_init().