AlcapDAQ: midas/examples/eventbuilder/ebuser.c File Reference
midas/examples/eventbuilder/ebuser.c File Reference
#include <stdio.h>
#include "midas.h"
#include "mevb.h"
#include "ybos.h"
Functions
INT ebuilder_init ()
INT ebuilder_exit ()
INT eb_begin_of_run (INT, char *, char *)
INT eb_end_of_run (INT, char *)
INT ebuilder_loop ()
INT ebuser (INT, BOOL mismatch, EBUILDER_CHANNEL *, EVENT_HEADER *, void *, INT *)
INT read_scaler_event (char *pevent, INT off)
INT eb_user (INT nfrag, BOOL mismatch, EBUILDER_CHANNEL *ebch, EVENT_HEADER *pheader, void *pevent, INT *dest_size)
Variables
char * frontend_name = "Ebuilder"
char * frontend_file_name = __FILE__
BOOL ebuilder_call_loop = FALSE
INT display_period = 3000
INT max_event_size = 10000
INT max_event_size_frag = 5 * 1024 * 1024
INT event_buffer_size = 10 * 10000
INT lModulo = 100
Global var for testing.
EQUIPMENT equipment []
Detailed Description
The Event builder user file
Definition in file ebuser.c.
Function Documentation
INT eb_begin_of_run (INT rn, char * UserField, char * error)
Hook to the event builder task at PreStart transition.
Parameters:
rn run number
UserField argument from /Ebuilder/Settings
error error string to be passed back to the system.
Returns:
EB_SUCCESS
Definition at line 139 of file ebuser.c.
References cm_msg, compress_load_all(), db_get_value(), EB_SUCCESS, ebch, ebset, enabled, FALSE, hDB, lModulo, mask, MAX_CHANNELS, MINFO, n, NUMCRATES, size, TID_BOOL, EBUILDER_SETTINGS::trigger_mask, and EBUILDER_CHANNEL::trigger_mask.
{
  printf("In eb_begin_of_run for run:%d User_field:%s \n", rn, UserField);
   lModulo = atoi(UserField);
   return EB_SUCCESS;
}
INT eb_end_of_run (INT rn, char * error)
Hook to the event builder task at completion of event collection after receiving the Stop transition.
Parameters:
rn run number
error error string to be passed back to the system.
Returns:
EB_SUCCESS
Definition at line 154 of file ebuser.c.
References EB_SUCCESS.
{
   printf("In eb_end_of_run\n");
   return EB_SUCCESS;
}
INT eb_user (INT nfrag, BOOL mismatch, EBUILDER_CHANNEL * ebch, EVENT_HEADER * pheader, void * pevent, INT * dest_size)
Hook to the event builder task after the reception of all fragments of the same serial number. The destination event has already the final EVENT_HEADER setup with the data size set to 0. It is than possible to add private data at this point using the proper bank calls.
The ebch[] array structure points to nfragment channel structure with the following content:
typedef struct {
    char  name[32];         // Fragment name (Buffer name).
    DWORD serial;           // Serial fragment number.
    char *pfragment;        // Pointer to fragment (EVENT_HEADER *)
    ...
} EBUILDER_CHANNEL;
The correct code for including your own MIDAS bank is shown below where TID_xxx is one of the valid Bank type starting with TID_ for midas format or xxx_BKTYPE for Ybos data format. bank_name is a 4 character descriptor. pdata has to be declared accordingly with the bank type. Refers to the ebuser.c source code for further description.
It is not possible to mix within the same destination event different event format!
  // Event is empty, fill it with BANK_HEADER
  // If you need to add your own bank at this stage
  bk_init(pevent);
  bk_create(pevent, bank_name, TID_xxxx, &pdata);
  *pdata++ = ...;
  *dest_size = bk_close(pevent, pdata);
  pheader->data_size = *dest_size + sizeof(EVENT_HEADER);
For YBOS format, use the following example.
  ybk_init(pevent);
  ybk_create(pevent, "EBBK", I4_BKTYPE, &pdata);
  *pdata++ = 0x12345678;
  *pdata++ = 0x87654321;
  *dest_size = ybk_close(pevent, pdata);
  *dest_size *= 4;
  pheader->data_size = *dest_size + sizeof(YBOS_BANK_HEADER);
Parameters:
nfrag Number of fragment.
mismatch Midas Serial number mismatch flag.
ebch Structure to all the fragments.
pheader Destination pointer to the header.
pevent Destination pointer to the bank header.
dest_size Destination event size in bytes.
Returns:
EB_SUCCESS
Definition at line 221 of file ebuser.c.
References bk_init32(), bk_size(), compress_event(), EVENT_HEADER::data_size, EB_SUCCESS, EB_USER_ERROR, i, EBUILDER_CHANNEL::pfragment, serial, and EVENT_HEADER::serial_number.
{
  INT i, dest_serial, frag_size, serial;
  DWORD *psrcData;
  if (mismatch){
    printf("Serial number do not match across fragments\n");
    for (i = 0; i < nfrag; i++) {
      serial = ((EVENT_HEADER *) ebch[i].pfragment)->serial_number;
      printf("Ser[%i]:%d ", i + 1, serial);
    }
    printf("\n");
    return EB_USER_ERROR;
  }
  // Destination access
  dest_serial = pheader->serial_number;
  printf("DSer#:%d ", dest_serial);
  // if (dest_serial == 505) return EB_USER_ERROR;
  // Loop over fragments.
  for (i = 0; i < nfrag; i++) {
    frag_size = ((EVENT_HEADER *) ebch[i].pfragment)->data_size;
    serial = ((EVENT_HEADER *) ebch[i].pfragment)->serial_number;
    printf("Frg#:%d Dsz:%d Ser:%d ", i + 1, frag_size, serial);
    // For Data fragment Access.
    psrcData = (DWORD *) (((EVENT_HEADER *) ebch[i].pfragment) + 1);
  }
  printf("\n");
  return EB_SUCCESS;
}
INT ebuilder_exit (void)
Definition at line 120 of file ebuser.c.
References EB_SUCCESS.
{
  return EB_SUCCESS;
}
INT ebuilder_init (void)
Definition at line 114 of file ebuser.c.
References EB_SUCCESS.
{
  return EB_SUCCESS;
}
INT ebuilder_loop (void)
Definition at line 126 of file ebuser.c.
References EB_SUCCESS.
{
  return EB_SUCCESS;
}
INT ebuser (INT , BOOL mismatch, EBUILDER_CHANNEL * , EVENT_HEADER * , void * , INT *)
INT read_scaler_event (char * pevent, INT off)
Definition at line 336 of file ebfe.c.
References bk_close(), bk_create(), bk_init(), bk_size(), cam24i(), CRATE, i, I4_BKTYPE, N_SCLR, Sclx, SLOT_SCLR, TID_DWORD, ybk_close(), ybk_create(), ybk_init(), and ybk_size().
{
   DWORD *pdata, a;
   /* init bank structure */
   bk_init(pevent);
   /* create SCLR bank */
   bk_create(pevent, Sclx, TID_DWORD, &pdata);
   /* read scaler bank */
   for (a = 0; a < N_SCLR; a++)
      cam24i(CRATE, SLOT_SCLR, a, 0, pdata++);
   bk_close(pevent, pdata);
   return bk_size(pevent);
}
Variable Documentation
INT display_period = 3000
Definition at line 68 of file ebuser.c.
BOOL ebuilder_call_loop = FALSE
Definition at line 65 of file ebuser.c.
EQUIPMENT equipment[]
Initial value:
 {
   {"EB",
    {1, 0,
     "SYSTEM",
     0,
     0,
     "MIDAS",
     TRUE,
     },
    },
  {""}
}
Definition at line 93 of file ebuser.c.
INT event_buffer_size = 10 * 10000
Definition at line 77 of file ebuser.c.
char* frontend_file_name = __FILE__
Definition at line 62 of file ebuser.c.
char* frontend_name = "Ebuilder"
Definition at line 59 of file ebuser.c.
INT lModulo = 100
Global var for testing.
Globals
Definition at line 81 of file ebuser.c.
INT max_event_size = 10000
Definition at line 71 of file ebuser.c.
INT max_event_size_frag = 5 * 1024 * 1024
Definition at line 74 of file ebuser.c.