AlcapDAQ: midas/include/esone.h File Reference
midas/include/esone.h File Reference
Defines
#define EXTERNAL extern
#define EXPRT
Functions
EXTERNAL INLINE void ccinit (void)
EXTERNAL INLINE void cdreg (int *ext, const int b, const int c, const int n, const int a)
EXTERNAL INLINE void cssa (const int f, int ext, unsigned short *d, int *q)
EXTERNAL INLINE void cfsa (const int f, const int ext, unsigned long *d, int *q)
EXTERNAL INLINE void cccc (const int ext)
EXTERNAL INLINE void cccz (const int ext)
EXTERNAL INLINE void ccci (const int ext, int l)
EXTERNAL INLINE void ctci (const int ext, int *l)
EXTERNAL INLINE void cccd (const int ext, int l)
EXTERNAL INLINE void ctcd (const int ext, int *l)
EXTERNAL INLINE void cdlam (int *lam, const int b, const int c, const int n, const int a, const int inta[2])
EXTERNAL INLINE void ctgl (const int lam, int *l)
EXTERNAL INLINE void cclm (const int lam, int l)
EXTERNAL INLINE void cclc (const int lam)
EXTERNAL INLINE void ctlm (const int lam, int *l)
EXTERNAL INLINE void cfga (int f[], int exta[], int intc[], int qa[], int cb[])
EXTERNAL INLINE void csga (int f[], int exta[], int intc[], int qa[], int cb[])
EXTERNAL INLINE void cfmad (int f, int extb[], int intc[], int cb[])
EXTERNAL INLINE void csmad (int f, int extb[], int intc[], int cb[])
EXTERNAL INLINE void cfubc (const int f, int ext, int intc[], int cb[])
EXTERNAL INLINE void csubc (const int f, int ext, int intc[], int cb[])
EXTERNAL INLINE void cfubr (const int f, int ext, int intc[], int cb[])
EXTERNAL INLINE void csubr (const int f, int ext, int intc[], int cb[])
Define Documentation
#define EXPRT
Definition at line 37 of file esone.h.
#define EXTERNAL extern
Definition at line 31 of file esone.h.
Function Documentation
EXTERNAL INLINE void cccc (const int ext)
Control Crate Clear.
Generate Crate Clear function. Execute cam_crate_clear()
Parameters:
ext external address
Returns:
void
cccc Control Crate Clear.
Generate Crate Clear function. Execute cam()
Crate Clear.
Parameters:
ext external address
Returns:
void
Definition at line 206 of file esone.c.
References c, cam_crate_clear(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   cam_crate_clear(c);
}
EXTERNAL INLINE void cccd (const int ext, int l)
Control Crate D.
Enable or Disable Crate Demand.
Parameters:
ext external address
l action l=0 -> Clear D, l=1 -> Set D
Returns:
void
cccd Control Crate D.
Enable or Disable Crate Demand.
Crate D.
Parameters:
ext external address
l action l=0 -> Clear D, l=1 -> Set D
Returns:
void
Definition at line 280 of file esone.c.
References c, cam_interrupt_disable(), cam_interrupt_enable(), came_ext(), and n.
Referenced by main().
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   if (l)
      cam_interrupt_enable(c);
   else
      cam_interrupt_disable(c);
}
EXTERNAL INLINE void ccci (const int ext, int l)
Control Crate I.
Set or Clear Dataway Inhibit, Execute cam_inhinit_set() /clear()
Parameters:
ext external address
l action l=0 -> Clear I, l=1 -> Set I
Returns:
void
ccci Control Crate I.
Set or Clear Dataway Inhibit, Execute cam() /clear()
Crate I.
Parameters:
ext external address
l action l=0 -> Clear I, l=1 -> Set I
Returns:
void
Definition at line 241 of file esone.c.
References c, cam_inhibit_clear(), cam_inhibit_set(), came_ext(), and n.
Referenced by main().
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   if (l)
      cam_inhibit_set(c);
   else
      cam_inhibit_clear(c);
}
EXTERNAL INLINE void cccz (const int ext)
Control Crate Z.
Generate Dataway Initialize. Execute cam_crate_zinit()
Parameters:
ext external address
Returns:
void
cccz Control Crate Z.
Generate Dataway Initialize. Execute cam()
Crate Z.
Parameters:
ext external address
Returns:
void
Definition at line 223 of file esone.c.
References c, cam_crate_zinit(), came_ext(), and n.
Referenced by main().
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   cam_crate_zinit(c);
}
EXTERNAL INLINE void ccinit (void)
dox CAMAC initialization
CAMAC initialization must be called before any other ESONE subroutine call.
Returns:
void
ccinit CAMAC initialization
CAMAC initialization must be called before any other ESONE subroutine call
CAMAC initialization.
Returns:
void
Definition at line 85 of file esone.c.
References cam_init().
{
   cam_init();
}
EXTERNAL INLINE void cclc (const int lam)
Control Clear LAM.
Clear the LAM of the station pointer by the lam address.
Parameters:
lam external address
Returns:
void
cclc Control Clear LAM. Clear the LAM of the staion pointer by the lam address.
Clear LAM.
Parameters:
lam external address
Returns:
void
Definition at line 441 of file esone.c.
References c, camc(), came_ext(), and n.
Referenced by isr(), and main().
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   camc(c, n, 0, 10);
}
EXTERNAL INLINE void cclm (const int lam, int l)
Control Crate LAM.
Enable or Disable LAM. Execute F24 for disable, F26 for enable.
Parameters:
lam external address
l action l=0 -> disable LAM , l=1 -> enable LAM
Returns:
void
cclm Control Crate LAM.
Enable or Disable LAM. Execute F24 for disable, F26 for enable.
dis/enable LAM.
Parameters:
lam external address
l action l=0 -> disable LAM , l=1 -> enable LAM
Returns:
void
Definition at line 361 of file esone.c.
References c, camc(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   if (l)
      camc(c, n, 0, 26);
   else
      camc(c, n, 0, 24);
}
EXTERNAL INLINE void cdlam (int * lam, const int b, const int c, const int n, const int a, const int inta[2])
Control Declare LAM.
Declare LAM, Identical to cdreg.
Parameters:
lam external LAM address
b branch number (0..7)
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
inta implementation dependent
Returns:
void
cdlam Control Declare LAM.
Declare LAM, Identical to cdreg.
Declare LAM.
Parameters:
lam external LAM address
b branch number (0..7)
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
inta[2] implementation dependent
Returns:
void
Definition at line 324 of file esone.c.
References cdreg().
Referenced by isr(), and main().
{
   /* inta[2] ignored */
   cdreg(lam, b, c, n, a);
}
EXTERNAL INLINE void cdreg (int * ext, const int b, const int c, const int n, const int a)
Control Declaration REGister.
Compose an external address from BCNA for later use. Accessing CAMAC through ext could be faster if the external address is memory mapped to the processor (hardware dependent). Some CAMAC controller do not have this option see AppendixB.
Parameters:
ext external address
b branch number (0..7)
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
Returns:
void
cdreg Control Declaration REGister.
Compose an external address from BCNA for later use. Accessing CAMAC through ext could be faster if the external address is memory mapped to the processor (hardware dependent). Some CAMAC controller do not have this option see {appendix D: Supported hardware}. In this case External Address register.
Parameters:
ext external address
b branch number (0..7)
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
Returns:
void
Definition at line 122 of file esone.c.
References came_cn().
{
   came_cn(ext, b, c, n, a);
}
EXTERNAL INLINE void cfga (int f[], int exta[], int intc[], int qa[], int cb[])
Control Full (24bit) word General Action.
Parameters:
f function code
exta[] external address array
intc[] data array
qa[] Q response array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
cfga Control Full (24bit) word General Action.
General external address scan function.
Parameters:
f function code
exta[] external address array
intc[] data array
qa[] Q response array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 480 of file esone.c.
References cfsa(), and i.
{
   int i;
   for (i = 0; i < cb[0]; i++)
      cfsa(f[i], exta[i], (unsigned long *) (&(intc[i])), &(qa[i]));
   cb[1] = cb[0];
}
EXTERNAL INLINE void cfmad (int f, int extb[], int intc[], int cb[])
Control Full (24bit) Address Q scan.
Scan all sub-address while Q=1 from a0..a15 max from address extb[0] and store corresponding data in intc[]. If Q=0 while A<15 or A=15 then cross station boundary is applied (n-> n+1) and sub-address is reset (a=0). Perform action until either cb[0] action are performed or current external address exceeds extb[1].
implementation of cb[2] for LAM recognition is not implemented.
Parameters:
f function code
extb[] external address array
extb[0] : first valid external address
extb[1] : last valid external address
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
cfmad Control Full (24bit) Address Q scan.
Scan all sub-address while Q=1 from a0..a15 max from address extb[0] and store corresponding data in intc[]. If Q=0 while A<15 or A=15 then cross station boundary is applied (n-> n+1) and sub-address is reset (a=0). Perform action until either cb[0] action are performed or current external address exceeds extb[1].
{ implementation of cb[2] for LAM recognition is not implemented.}
Address scan function.
Parameters:
f function code
extb[] external address array \ extb[0] : first valid external address \ extb[1] : last valid external address
intc[] data array
qa[] Q response array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 534 of file esone.c.
References c, cam24i_q(), came_cn(), came_ext(), count, j, and n.
{
   int j, count;
   int x, q, b, c, n, a;
   unsigned long exts, extc, exte;
   exts = extb[0];
   exte = extb[1];
   count = cb[0];
   j = 0;
   came_ext(exts, &b, &c, &n, &a);
   do {
      cam24i_q(c, n, a, f, (unsigned long *) &intc[j], &x, &q);
      if (q == 0) {
         a = 0;                 /* set subaddress to zero */
         n++;                   /* select next slot */
         j++;
      } else {
         a++;                   /* increment address */
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
      came_cn((int *) &extc, b, c, n, a);
      if (extc > exte)
         count = 0;             /* force exit */
   } while (count);
}
EXTERNAL INLINE void cfsa (const int f, const int ext, unsigned long * d, int * q)
Control Full Operation.
24 bit operation on a given external CAMAC address.
The range of the f is hardware dependent. The number indicated below are for standard ANSI/IEEE Std (758-1979) Execute cam24i for f<8, cam24o for f>15, camc_q for (f>7 or f>23)
Parameters:
f function code (0..31)
ext external address
d data long word
q Q response
Returns:
void
cfsa Control Full Operation.
24 bit operation on a given external CAMAC address.
The range of the f is hardware dependent. The number indicated below are for standard ANSI/IEEE Std (758-1979) \ Execute cam24i for f<8, cam24o for f>15, camc for (f>7 or f>23)
24 bit function.
Parameters:
f function code (0..31)
ext external address
d data long word
q Q response
Returns:
void
Definition at line 178 of file esone.c.
References c, cam24i_q(), cam24o_q(), camc_q(), came_ext(), and n.
{
   int b, c, n, a, x;
   if (f < 8) {
      /* read */
      came_ext(ext, &b, &c, &n, &a);
      cam24i_q(c, n, a, f, d, &x, q);
   } else if (f > 15) {
      /* write */
      came_ext(ext, &b, &c, &n, &a);
      cam24o_q(c, n, a, f, *d, &x, q);
   } else if ((f > 7) || (f > 23)) {
      /* command */
      came_ext(ext, &b, &c, &n, &a);
      camc_q(c, n, a, f, q);
   }
}
EXTERNAL INLINE void cfubc (const int f, int ext, int intc[], int cb[])
Control Full (24bit) Block Repeat with Q-stop.
Execute function f on address ext with data intc[] while Q.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
cfubc Control Full (24bit) Block Repeat with Q-stop.
Execute function f on address ext with data intc[] while Q.
Repeat function Q-stop.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 631 of file esone.c.
References cfsa(), and count.
{
   int count, q;
   count = cb[0];
   do {
      cfsa(f, ext, (unsigned long *) intc, &q);
      if (q == 0)
         count = 0;             /* stop on no q */
      else {
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
   } while (count);
}
EXTERNAL INLINE void cfubr (const int f, int ext, int intc[], int cb[])
Repeat Mode Block Transfer (24bit).
Execute function f on address ext with data intc[] if Q. If noQ keep current intc[] data. Repeat cb[0] times.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
cfubr Repeat Mode Block Transfer (24bit).
Execute function f on address ext with data intc[] if Q. If noQ keep current intc[] data. Repeat cb[0] times.
Repeat function.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 694 of file esone.c.
References cfsa(), and count.
{
   int q, count;
   count = cb[0];
   do {
      do {
         cfsa(f, ext, (unsigned long *) intc, &q);
      } while (q == 0);
      ++cb[1];                  /* increment tally count */
      ++intc;                   /* next data array */
      --count;
   } while (count);
}
EXTERNAL INLINE void csga (int f[], int exta[], int intc[], int qa[], int cb[])
Control (16bit) word General Action.
Parameters:
f function code
exta[] external address array
intc[] data array
qa[] Q response array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
csga Control (16bit) word General Action.
General external address scan function.
Parameters:
f function code
exta[] external address array
intc[] data array
qa[] Q response array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 503 of file esone.c.
References cssa(), and i.
{
   int i;
   for (i = 0; i < cb[0]; i++)
      cssa(f[i], exta[i], (unsigned short *) (&(intc[i])), &(qa[i]));
   cb[1] = cb[0];
}
EXTERNAL INLINE void csmad (int f, int extb[], int intc[], int cb[])
Control (16bit) Address Q scan.
Scan all sub-address while Q=1 from a0..a15 max from address extb[0] and store corresponding data in intc[]. If Q=0 while A<15 or A=15 then cross station boundary is applied (n-> n+1) and sub-address is reset (a=0). Perform action until either cb[0] action are performed or current external address exceeds extb[1].
implementation of cb[2] for LAM recognition is not implemented.
Parameters:
f function code
extb[] external address array
extb[0] : first valid external address
extb[1] : last valid external address
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
csmad Control (16bit) Address Q scan.
Scan all sub-address while Q=1 from a0..a15 max from address extb[0] and store corresponding data in intc[]. If Q=0 while A<15 or A=15 then cross station boundary is applied (n-> n+1) and sub-address is reset (a=0). Perform action until either cb[0] action are performed or current external address exceeds extb[1].
{ implementation of cb[2] for LAM recognition is not implemented.}
Address scan function.
Parameters:
f function code
extb[] external address array \ extb[0] : first valid external address \ extb[1] : last valid external address
intc[] data array
qa[] Q response array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 586 of file esone.c.
References c, cam16i_q(), came_cn(), came_ext(), count, j, and n.
{
   int j, count;
   int x, q, b, c, n, a;
   unsigned long exts, extc, exte;
   exts = extb[0];
   exte = extb[1];
   count = cb[0];
   j = 0;
   came_ext(exts, &b, &c, &n, &a);
   do {
      cam16i_q(c, n, a, f, (unsigned short *) &intc[j], &x, &q);
      if (q == 0) {
         a = 0;                 /* set subaddress to zero */
         n++;                   /* select next slot */
         j++;
      } else {
         a++;                   /* increment address */
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
      came_cn((int *) &extc, b, c, n, a);
      if (extc > exte)
         count = 0;             /* force exit */
   } while (count);
}
EXTERNAL INLINE void cssa (const int f, int ext, unsigned short * d, int * q)
Control Short Operation.
16 bit operation on a given external CAMAC address.
The range of the f is hardware dependent. The number indicated below are for standard ANSI/IEEE Std (758-1979) Execute cam16i for f<8, cam16o for f>15, camc_q for (f>7 or f>23)
Parameters:
f function code (0..31)
ext external address
d data word
q Q response
Returns:
void
cssa Control Short Operation.
16 bit operation on a given external CAMAC address.
The range of the f is hardware dependent. The number indicated below are for standard ANSI/IEEE Std (758-1979) \ Execute cam16i for f<8, cam16o for f>15, camc for (f>7 or f>23)
16 bit function.
Parameters:
f function code (0..31)
ext external address
d data word
q Q response
Returns:
void
Definition at line 143 of file esone.c.
References c, cam16i_q(), cam16o_q(), camc_q(), came_ext(), and n.
{
   int b, c, n, a, x;
   if (f < 8) {
      /* read */
      came_ext(ext, &b, &c, &n, &a);
      cam16i_q(c, n, a, f, d, &x, q);
   } else if (f > 15) {
      /* write */
      came_ext(ext, &b, &c, &n, &a);
      cam16o_q(c, n, a, f, *d, &x, q);
   } else if ((f > 7) || (f > 23)) {
      /* command */
      came_ext(ext, &b, &c, &n, &a);
      camc_q(c, n, a, f, q);
   }
}
EXTERNAL INLINE void csubc (const int f, int ext, int intc[], int cb[])
Control (16bit) Block Repeat with Q-stop.
Execute function f on address ext with data intc[] while Q.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
csubc Control (16bit) Block Repeat with Q-stop.
Execute function f on address ext with data intc[] while Q.
Repeat function Q-stop.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 662 of file esone.c.
References count, and cssa().
{
   int count, q;
   count = cb[0];
   do {
      cssa(f, ext, (unsigned short *) intc, &q);
      if (q == 0)
         count = 0;             /* stop on no q */
      else {
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
   } while (count);
}
EXTERNAL INLINE void csubr (const int f, int ext, int intc[], int cb[])
Repeat Mode Block Transfer (16bit).
Execute function f on address ext with data intc[] if Q. If noQ keep current intc[] data. Repeat cb[0] times.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
csubr Repeat Mode Block Transfer (16bit).
Execute function f on address ext with data intc[] if Q. If noQ keep current intc[] data. Repeat cb[0] times.
Repeat function.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 725 of file esone.c.
References count, and cssa().
{
   int q, count;
   count = cb[0];
   do {
      do {
         cssa(f, ext, (unsigned short *) intc, &q);
      } while (q == 0);
      ++cb[1];                  /* increment tally count */
      ++intc;                   /* next data array */
      --count;
   } while (count);
}
EXTERNAL INLINE void ctcd (const int ext, int * l)
Control Test Crate D.
Test Crate Demand.
Parameters:
ext external address
l D cleared -> l=0, D set -> l=1
Returns:
void
ctcd Control Test Crate D.
Test Crate Demand.
Test Crate D.
Parameters:
ext external address
l D cleared -> l=0, D set -> l=1
Returns:
void
Definition at line 302 of file esone.c.
References c, cam_interrupt_test(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   *l = cam_interrupt_test(c);
}
EXTERNAL INLINE void ctci (const int ext, int * l)
Test Crate I.
Test Crate Inhibit, Execute cam_inhibit_test()
Parameters:
ext external address
l action l=0 -> Clear I, l=1 -> Set I
Returns:
void
ctci Test Crate I.
Test Crate Inhibit, Execute cam()
Crate I.
Parameters:
ext external address
l action l=0 -> Clear I, l=1 -> Set I
Returns:
void
Definition at line 262 of file esone.c.
References c, cam_inhibit_test(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   *l = cam_inhibit_test(c);
}
EXTERNAL INLINE void ctgl (const int ext, int * l)
Control Test Demand Present.
Test the LAM register.
Parameters:
ext external LAM register address
l l !=0 if any LAM is set.
Returns:
void
ctgl Control Test Demand Present.
Test the LAM register.
Test GL.
Parameters:
lam external LAM register address
l l !=0 if any LAM is set.
Returns:
void
Definition at line 341 of file esone.c.
References c, cam_lam_read(), came_ext(), and n.
{
   int b, c, n, a;
   unsigned long lam;
   came_ext(ext, &b, &c, &n, &a);
   cam_lam_read(c, &lam);
   *l = (lam > 0);
}
EXTERNAL INLINE void ctlm (const int lam, int * l)
Test LAM.
Test the LAM of the station pointed by lam. Performs an F8
Parameters:
lam external address
l No LAM-> l=0, LAM present-> l=1
Returns:
void
ctlm Test LAM.
Test the LAM of the station pointed by lam. Performs an F8
Test LAM.
Parameters:
lam external address
l No LAM-> l=0, LAM present-> l=1
Returns:
void
Definition at line 459 of file esone.c.
References c, camc_q(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   camc_q(c, n, a, 8, l);
}