AlcapDAQ: midas/examples/experiment/adcsum.c File Reference
midas/examples/experiment/adcsum.c File Reference
#include <stdio.h>
#include <math.h>
#include "midas.h"
#include "experim.h"
#include "analyzer.h"
#include <TH1F.h>
Defines
#define DEFINE_TESTS
#define PI 3.14159265359
Functions
DEF_TEST (low_sum)
DEF_TEST (high_sum)
INT adc_summing (EVENT_HEADER *, void *)
INT adc_summing_init (void)
INT adc_summing_bor (INT run_number)
ADC_SUMMING_PARAM_STR (adc_summing_param_str)
Variables
ADC_SUMMING_PARAM adc_summing_param
ANA_MODULE adc_summing_module
static TH1F * hAdcSum
static TH1F * hAdcAvg
Define Documentation
#define DEFINE_TESTS
Definition at line 61 of file adcsum.c.
#define PI 3.14159265359
Definition at line 72 of file adcsum.c.
Function Documentation
INT adc_summing (EVENT_HEADER * pheader, void * pevent)
Definition at line 126 of file adcsum.c.
References ASUM_BANK::average, bk_close(), bk_create(), bk_locate(), i, j, SET_TEST, SUCCESS, ASUM_BANK::sum, and TID_STRUCT.
{
   INT i, j, n_adc;
   float *cadc;
   ASUM_BANK *asum;
   /* look for CADC bank, return if not present */
   n_adc = bk_locate(pevent, "CADC", &cadc);
   if (n_adc == 0)
      return 1;
   /* create ADC sum bank */
   bk_create(pevent, "ASUM", TID_STRUCT, &asum);
   /* sum all channels above threashold */
   asum->sum = 0.f;
   for (i = j = 0; i < n_adc; i++)
      if (cadc[i] > adc_summing_param.adc_threshold) {
         asum->sum += cadc[i];
         j++;
      }
   /* calculate ADC average */
   asum->average = j > 0 ? asum->sum / j : 0;
   /* evaluate tests */
   SET_TEST(low_sum, asum->sum < 1000);
   SET_TEST(high_sum, asum->sum > 1000);
   /* fill sum histo */
   hAdcSum->Fill(asum->sum, 1);
   /* fill average histo */
   hAdcAvg->Fill(asum->average);
   /* close calculated bank */
   bk_close(pevent, asum + 1);
   return SUCCESS;
}
INT adc_summing_bor (INT run_number)
INT adc_summing_init (void)
Definition at line 111 of file adcsum.c.
References close_subfolder(), open_subfolder(), and SUCCESS.
{
   /* book ADC sum histo */
   hAdcSum = H1_BOOK("ADCSUM", "ADC sum", 500, 0, 10000);
   /* book ADC average in separate subfolder */
   open_subfolder("Average");
   hAdcAvg = H1_BOOK("ADCAVG", "ADC average", 500, 0, 10000);
   close_subfolder();
   return SUCCESS;
}
ADC_SUMMING_PARAM_STR (adc_summing_param_str)
DEF_TEST (high_sum)
DEF_TEST (low_sum)
Variable Documentation
ANA_MODULE adc_summing_module
Initial value:
 {
   "ADC summing",
   "Stefan Ritt",
   adc_summing,
   NULL,
   NULL,
   adc_summing_init,
   NULL,
   &adc_summing_param,
   sizeof(adc_summing_param),
   adc_summing_param_str,
}
Definition at line 92 of file adcsum.c.
ADC_SUMMING_PARAM adc_summing_param
Definition at line 77 of file adcsum.c.
TH1F * hAdcAvg [static]
Definition at line 107 of file adcsum.c.
TH1F* hAdcSum [static]
Definition at line 107 of file adcsum.c.