AlcapDAQ: midas/examples/experiment/adccalib.c File Reference
midas/examples/experiment/adccalib.c File Reference
#include <stdio.h>
#include <time.h>
#include "midas.h"
#include "experim.h"
#include "analyzer.h"
#include <TH1F.h>
#include <TTree.h>
Defines
#define ADC_N_BINS 500
#define ADC_X_LOW 0
#define ADC_X_HIGH 4000
Functions
INT adc_calib (EVENT_HEADER *, void *)
INT adc_calib_init (void)
INT adc_calib_bor (INT run_number)
INT adc_calib_eor (INT run_number)
ADC_CALIBRATION_PARAM_STR (adc_calibration_param_str)
Variables
ADC_CALIBRATION_PARAM adccalib_param
EXP_PARAM exp_param
RUNINFO runinfo
ANA_MODULE adc_calib_module
static TH1F * hAdcHists [N_ADC]
Define Documentation
#define ADC_N_BINS 500
Definition at line 100 of file adccalib.c.
Referenced by adc_calib_init(), and analyzer_init().
#define ADC_X_HIGH 4000
Definition at line 102 of file adccalib.c.
Referenced by adc_calib_init(), and analyzer_init().
#define ADC_X_LOW 0
Definition at line 101 of file adccalib.c.
Referenced by adc_calib_init(), and analyzer_init().
Function Documentation
INT adc_calib (EVENT_HEADER * pheader, void * pevent)
Definition at line 139 of file adccalib.c.
References bk_close(), bk_create(), bk_locate(), for(), i, N_ADC, SUCCESS, and TID_FLOAT.
{
   INT i;
   WORD *pdata;
   float *cadc;
   /* look for ADC0 bank, return if not present */
   if (!bk_locate(pevent, "ADC0", &pdata))
      return 1;
   /* create calibrated ADC bank */
   bk_create(pevent, "CADC", TID_FLOAT, &cadc);
   /* zero cadc bank */
   for (i = 0; i < N_ADC; i++)
      cadc[i] = 0.f;
   /* subtract pedestal */
   for (i = 0; i < N_ADC; i++)
      cadc[i] = (float) ((double) pdata[i] - adccalib_param.pedestal[i] + 0.5);
   /* apply software gain calibration */
   for (i = 0; i < N_ADC; i++)
      cadc[i] *= adccalib_param.software_gain[i];
   /* fill ADC histos if above threshold */
   for (i = 0; i < N_ADC; i++)
      if (cadc[i] > (float) adccalib_param.histo_threshold)
         hAdcHists[i]->Fill(cadc[i], 1);
   /* close calculated bank */
   bk_close(pevent, cadc + N_ADC);
   return SUCCESS;
}
INT adc_calib_bor (INT run_number)
Definition at line 125 of file adccalib.c.
References SUCCESS.
{
   return SUCCESS;
}
INT adc_calib_eor (INT run_number)
Definition at line 132 of file adccalib.c.
References SUCCESS.
{
   return SUCCESS;
}
INT adc_calib_init (void)
Definition at line 104 of file adccalib.c.
References ADC_N_BINS, ADC_X_HIGH, ADC_X_LOW, i, N_ADC, name, SUCCESS, and title.
{
   char name[256];
   int i;
   /* book CADC histos */
   for (i = 0; i < N_ADC; i++) {
      char title[256];
      sprintf(name, "CADC%02d", i);
      sprintf(title, "ADC %d", i);
      hAdcHists[i] = H1_BOOK(name, title, ADC_N_BINS, ADC_X_LOW, ADC_X_HIGH);
   }
   return SUCCESS;
}
ADC_CALIBRATION_PARAM_STR (adc_calibration_param_str)
Variable Documentation
ANA_MODULE adc_calib_module
Initial value:
 {
   "ADC calibration",
   "Stefan Ritt",
   adc_calib,
   adc_calib_bor,
   adc_calib_eor,
   adc_calib_init,
   NULL,
   &adccalib_param,
   sizeof(adccalib_param),
   adc_calibration_param_str,
}
Definition at line 81 of file adccalib.c.
ADC_CALIBRATION_PARAM adccalib_param
Definition at line 68 of file adccalib.c.
EXP_PARAM exp_param
Definition at line 103 of file analyzer.c.
TH1F* hAdcHists[N_ADC] [static]
Definition at line 96 of file adccalib.c.
RUNINFO runinfo
Definition at line 101 of file analyzer.c.
Referenced by show_status_page().