AlcapDAQ: midas/drivers/class/generic.h File Reference
midas/drivers/class/generic.h File Reference
Functions
INT cd_gen (INT cmd, PEQUIPMENT pequipment)
INT cd_gen_read (char *pevent, int)
Function Documentation
INT cd_gen (INT cmd, PEQUIPMENT pequipment)
INT cd_gen_read (char * pevent, int)
Definition at line 438 of file generic.c.
References bk_close(), bk_create(), bk_init(), bk_size(), eqpmnt::cd_info, GEN_INFO::demand, EVENT_ID, F4_BKTYPE, GEN_INFO::format, FORMAT_FIXED, FORMAT_MIDAS, FORMAT_YBOS, I4_BKTYPE, if, GEN_INFO::measured, GEN_INFO::num_channels, SERIAL_NUMBER, TID_FLOAT, TIME_STAMP, ybk_close(), ybk_create(), ybk_init(), and ybk_size().
{
   float *pdata;
   DWORD *pdw;
   GEN_INFO *gen_info;
   EQUIPMENT *pequipment;
   pequipment = *((EQUIPMENT **) pevent);
   gen_info = (GEN_INFO *) pequipment->cd_info;
   if (gen_info->format == FORMAT_FIXED) {
      memcpy(pevent, gen_info->demand, sizeof(float) * gen_info->num_channels);
      pevent += sizeof(float) * gen_info->num_channels;
      memcpy(pevent, gen_info->measured, sizeof(float) * gen_info->num_channels);
      pevent += sizeof(float) * gen_info->num_channels;
      return 2 * sizeof(float) * gen_info->num_channels;
   } else if (gen_info->format == FORMAT_MIDAS) {
      bk_init(pevent);
      /* create DMND bank */
      bk_create(pevent, "DMND", TID_FLOAT, &pdata);
      memcpy(pdata, gen_info->demand, sizeof(float) * gen_info->num_channels);
      pdata += gen_info->num_channels;
      bk_close(pevent, pdata);
      /* create MSRD bank */
      bk_create(pevent, "MSRD", TID_FLOAT, &pdata);
      memcpy(pdata, gen_info->measured, sizeof(float) * gen_info->num_channels);
      pdata += gen_info->num_channels;
      bk_close(pevent, pdata);
      return bk_size(pevent);
   } else if (gen_info->format == FORMAT_YBOS) {
      ybk_init((DWORD *) pevent);
      /* create EVID bank */
      ybk_create((DWORD *) pevent, "EVID", I4_BKTYPE, (DWORD *) (&pdw));
      *(pdw)++ = EVENT_ID(pevent);      /* Event_ID + Mask */
      *(pdw)++ = SERIAL_NUMBER(pevent); /* Serial number */
      *(pdw)++ = TIME_STAMP(pevent);    /* Time Stamp */
      ybk_close((DWORD *) pevent, pdw);
      /* create DMND bank */
      ybk_create((DWORD *) pevent, "DMND", F4_BKTYPE, (DWORD *) & pdata);
      memcpy(pdata, gen_info->demand, sizeof(float) * gen_info->num_channels);
      pdata += gen_info->num_channels;
      ybk_close((DWORD *) pevent, pdata);
      /* create MSRD bank */
      ybk_create((DWORD *) pevent, "MSRD", F4_BKTYPE, (DWORD *) & pdata);
      memcpy(pdata, gen_info->measured, sizeof(float) * gen_info->num_channels);
      pdata += gen_info->num_channels;
      ybk_close((DWORD *) pevent, pdata);
      return ybk_size((DWORD *) pevent);
   } else
      return 0;
}