AlcapDAQ: midas/NT/directio/giveio.c File Reference
midas/NT/directio/giveio.c File Reference
#include <stdio.h>
#include <windows.h>
#include <math.h>
#include <conio.h>
Functions
INT ss_directio_init ()
INT ss_directio_exit ()
INT ss_directio_give_port (INT start, INT end)
INT ss_directio_lock_port (INT start, INT end)
int main (int argc, char *argv[])
Variables
static HANDLE _hdio = 0
Function Documentation
int main (int argc, char * argv[])
Definition at line 69 of file giveio.c.
References i, p1, p2, ss_directio_exit(), ss_directio_give_port(), and ss_directio_init().
{
int i, p1, p2;
  if (argc != 3)
    {
    printf("usage: giveio <port1> <port2>\n");
    printf("  to open port1 to port2 (inclusive).\n");
    printf("  Ports are specified hexadecimally.\n");
    return 0;
    }
  sscanf(argv[1], "%x", &p1);
  sscanf(argv[2], "%x", &p2);
  if (p1 == 0 || p2 == 0)
    {
    printf("Ports may not be zero\n");
    return 0;
    }
  if (p1 == 0 || p2 == 0 || p1 > p2)
    {
    printf("Second port must be larger or equal to first port\n");
    return 0;
    }
  if (ss_directio_init() == 0)
    {
    printf("DirectIO driver not installed or started\n");
    return 0;
    }
  ss_directio_give_port(p1, p2);
  ss_directio_exit();
  printf("Ports 0x%x to 0x%x enabled sucessfully.\n", p1, p2);
        return 0;
}
INT ss_directio_exit ()
Definition at line 30 of file giveio.c.
References _hdio.
Referenced by main().
{
  return CloseHandle(_hdio);
}
INT ss_directio_init ()
Definition at line 23 of file giveio.c.
References _hdio.
Referenced by main().
{
  _hdio = CreateFile("\\\\.\\directio", GENERIC_READ, FILE_SHARE_READ, NULL,
                                       OPEN_EXISTING, 0, NULL);
  return (INT) _hdio;
}
Variable Documentation
HANDLE _hdio = 0 [static]
Definition at line 21 of file giveio.c.
Referenced by cam_exit(), cam_init(), fb_exit(), fb_init(), ss_directio_exit(), ss_directio_give_port(), ss_directio_init(), and ss_directio_lock_port().