AlcapDAQ: The msystem.h & system.c
The msystem.h & system.c
Data Structures
struct NET_COMMAND_HEADER
struct NET_COMMAND
struct UDP_HEADER
struct callback_addr
struct RPC_CLIENT_CONNECTION
struct RPC_SERVER_CONNECTION
struct RPC_SERVER_ACCEPTION
struct CHN_SETTINGS
struct CHN_STATISTICS
struct LOG_CHN
struct VX_TASK_SPAWN
Modules
System Define
System Macros
System Structure Declaration
System Functions (ss_xxx)
Defines
#define MESSAGE_BUFFER_SIZE 100000
#define MESSAGE_BUFFER_NAME "SYSMSG"
#define MAX_RPC_CONNECTION 64
#define MAX_STRING_LENGTH 256
#define NET_BUFFER_SIZE
#define LOCAL_ROUTINES
#define YBOS_SUPPORT
#define FD_SETSIZE 32
#define O_BINARY 0
#define O_TEXT 0
#define ABS(a) (((a) < 0) ? -(a) : (a))
#define TELL(fh) lseek(fh, 0, SEEK_CUR)
#define UDP_FIRST 0x80000000l
#define TCP_FAST 0x80000000l
#define MSG_BM 1
#define MSG_ODB 2
#define MSG_CLIENT 3
#define MSG_SERVER 4
#define MSG_LISTEN 5
#define MSG_WATCHDOG 6
#define CHN_SETTINGS_STR(_name)
#define LOG_TYPE_DISK 1
#define LOG_TYPE_TAPE 2
#define LOG_TYPE_FTP 3
#define CH_IPC 1
#define CH_CLIENT 2
#define CH_SERVER 3
#define CH_LISTEN 4
Functions
INT EXPRT cm_set_path (char *path)
INT EXPRT cm_get_path (char *path)
INT cm_dispatch_ipc (char *message, int socket)
INT EXPRT cm_msg_log (INT message_type, const char *message)
INT EXPRT cm_msg_log1 (INT message_type, const char *message, const char *facility)
void EXPRT name2c (char *str)
INT bm_lock_buffer (INT buffer_handle)
INT bm_unlock_buffer (INT buffer_handle)
INT bm_notify_client (char *buffer_name, int socket)
INT EXPRT bm_mark_read_waiting (BOOL flag)
INT bm_push_event (char *buffer_name)
INT bm_check_buffers (void)
INT EXPRT bm_remove_event_request (INT buffer_handle, INT request_id)
void EXPRT bm_defragment_event (HNDLE buffer_handle, HNDLE request_id, EVENT_HEADER *pevent, void *pdata, void(*dispatcher)(HNDLE, HNDLE, EVENT_HEADER *, void *))
INT EXPRT db_lock_database (HNDLE database_handle)
INT EXPRT db_unlock_database (HNDLE database_handle)
INT db_update_record (INT hDB, INT hKey, int socket)
INT db_close_all_records (void)
INT EXPRT db_flush_database (HNDLE hDB)
INT EXPRT db_notify_clients (HNDLE hDB, HNDLE hKey, BOOL bWalk)
INT EXPRT db_set_client_name (HNDLE hDB, char *client_name)
INT db_delete_key1 (HNDLE hDB, HNDLE hKey, INT level, BOOL follow_links)
INT EXPRT db_show_mem (HNDLE hDB, char *result, INT buf_size, BOOL verbose)
RPC_LIST EXPRT * rpc_get_internal_list (INT flag)
INT rpc_server_receive (INT index, int sock, BOOL check)
INT rpc_server_callback (struct callback_addr *callback)
INT EXPRT rpc_server_accept (int sock)
INT rpc_client_accept (int sock)
INT rpc_get_server_acception (void)
INT rpc_set_server_acception (INT index)
INT EXPRT rpc_set_server_option (INT item, PTYPE value)
PTYPE EXPRT rpc_get_server_option (INT item)
INT recv_tcp_check (int sock)
INT recv_event_check (int sock)
INT rpc_deregister_functions (void)
INT rpc_check_channels (void)
void EXPRT rpc_client_check ()
INT rpc_server_disconnect (void)
int EXPRT rpc_get_send_sock (void)
int EXPRT rpc_get_event_sock (void)
INT EXPRT rpc_set_opt_tcp_size (INT tcp_size)
INT EXPRT rpc_get_opt_tcp_size (void)
INT ss_shm_open (char *name, INT size, void **adr, HNDLE *handle)
INT ss_shm_close (char *name, void *adr, HNDLE handle, INT destroy_flag)
INT ss_shm_flush (char *name, void *adr, INT size)
INT ss_shm_protect (HNDLE handle, void *adr)
INT ss_shm_unprotect (HNDLE handle, void **adr)
INT ss_spawnv (INT mode, char *cmdname, char *argv[])
INT ss_shell (int sock)
INT EXPRT ss_daemon_init (BOOL keep_stdout)
INT EXPRT ss_system (char *command)
INT EXPRT ss_exec (char *cmd, INT *child_pid)
BOOL EXPRT ss_existpid (INT pid)
INT EXPRT ss_getpid (void)
INT EXPRT ss_gettid (void)
INT ss_getthandle (void)
INT ss_set_async_flag (INT flag)
INT EXPRT ss_mutex_create (char *mutex_name, HNDLE *mutex_handle)
INT EXPRT ss_mutex_wait_for (HNDLE mutex_handle, INT timeout)
INT EXPRT ss_mutex_release (HNDLE mutex_handle)
INT EXPRT ss_mutex_delete (HNDLE mutex_handle, INT destroy_flag)
INT ss_wake (INT pid, INT tid, INT thandle)
INT ss_alarm (INT millitime, void(*func)(int))
INT ss_suspend_get_port (INT *port)
INT ss_suspend_set_dispatch (INT channel, void *connection, INT(*dispatch)())
INT ss_resume (INT port, char *message)
INT ss_suspend_exit (void)
INT ss_exception_handler (void(*func)())
void EXPRT ss_force_single_thread ()
INT EXPRT ss_suspend (INT millisec, INT msg)
midas_thread_t EXPRT ss_thread_create (INT(*func)(void *), void *param)
INT EXPRT ss_thread_kill (midas_thread_t thread_id)
INT EXPRT ss_get_struct_align (void)
INT EXPRT ss_timezone (void)
INT EXPRT send_tcp (int sock, char *buffer, DWORD buffer_size, INT flags)
INT EXPRT recv_tcp (int sock, char *buffer, DWORD buffer_size, INT flags)
INT send_udp (int sock, char *buffer, DWORD buffer_size, INT flags)
INT recv_udp (int sock, char *buffer, DWORD buffer_size, INT flags)
INT EXPRT recv_string (int sock, char *buffer, DWORD buffer_size, INT flags)
INT EXPRT ss_syslog (const char *message)
INT EXPRT eb_create_buffer (INT size)
INT EXPRT eb_free_buffer (void)
BOOL EXPRT eb_buffer_full (void)
BOOL EXPRT eb_buffer_empty (void)
EVENT_HEADER EXPRT * eb_get_pointer (void)
INT EXPRT eb_increment_pointer (INT buffer_handle, INT event_size)
INT EXPRT eb_send_events (BOOL send_all)
INT EXPRT dm_buffer_create (INT size, INT usize)
INT EXPRT dm_buffer_release (void)
BOOL EXPRT dm_area_full (void)
EVENT_HEADER EXPRT * dm_pointer_get (void)
INT EXPRT dm_pointer_increment (INT buffer_handle, INT event_size)
INT EXPRT dm_area_send (void)
INT EXPRT dm_area_flush (void)
INT EXPRT dm_task (void *pointer)
DWORD EXPRT dm_buffer_time_get (void)
INT EXPRT dm_async_area_send (void *pointer)
Detailed Description
dox
Define Documentation
#define ABS (a) (((a) < 0) ? -(a) : (a))
Definition at line 365 of file msystem.h.
#define CH_CLIENT 2
Definition at line 650 of file msystem.h.
Referenced by rpc_server_connect(), and ss_suspend_set_dispatch().
#define CH_IPC 1
Definition at line 649 of file msystem.h.
Referenced by bm_open_buffer(), db_open_database(), and ss_suspend_set_dispatch().
#define CH_LISTEN 4
Definition at line 652 of file msystem.h.
Referenced by rpc_register_server(), and ss_suspend_set_dispatch().
#define CH_SERVER 3
Definition at line 651 of file msystem.h.
Referenced by rpc_client_accept(), rpc_server_callback(), and ss_suspend_set_dispatch().
#define CHN_SETTINGS_STR (_name)
Value:
char *_name[] = {\
"[Settings]",\
"Active = BOOL : 1",\
"Type = STRING : [8] Disk",\
"Filename = STRING : [256] run%05d.mid",\
"Format = STRING : [8] MIDAS",\
"Compression = INT : 0",\
"ODB dump = BOOL : 1",\
"Log messages = DWORD : 0",\
"Buffer = STRING : [32] SYSTEM",\
"Event ID = INT : -1",\
"Trigger mask = INT : -1",\
"Event limit = DWORD : 0",\
"Byte limit = DOUBLE : 0",\
"Tape capacity = DOUBLE : 0",\
"Subdir format = STRING : [32]",\
"Current filename = STRING : [256]",\
"",\
"[Statistics]",\
"Events written = DOUBLE : 0",\
"Bytes written = DOUBLE : 0",\
"Bytes written total = DOUBLE : 0",\
"Files written = INT : 0",\
"",\
NULL}
dox dox
Definition at line 565 of file msystem.h.
#define FD_SETSIZE 32
Definition at line 336 of file msystem.h.
Referenced by cam_lam_wait(), frontend_init(), mrpc_call(), mrpc_server_loop(), read_paw(), recv_string(), recv_udp(), rpc_call(), rpc_check_channels(), rpc_client_call(), rpc_client_check(), rpc_client_dispatch(), scope_send(), server_loop(), ss_shell(), ss_sleep(), ss_suspend(), tcpip_gets(), tcpip_read(), and vacuum_gauge_read().
#define LOCAL_ROUTINES
Definition at line 266 of file msystem.h.
#define LOG_TYPE_DISK 1
Definition at line 633 of file msystem.h.
Referenced by lazy_main(), log_write(), tr_start(), tr_start1(), yb_any_dev_os_read(), yb_any_dev_os_write(), yb_any_file_rclose(), yb_any_file_ropen(), yb_any_file_wclose(), yb_any_file_wopen(), yb_any_log_write(), ybos_logfile_close(), and ybos_logfile_open().
#define LOG_TYPE_FTP 3
Definition at line 635 of file msystem.h.
Referenced by ascii_log_close(), ascii_log_open(), ascii_write(), dump_log_close(), dump_log_open(), dump_write(), lazy_main(), midas_flush_buffer(), midas_log_close(), midas_log_open(), tr_start(), tr_start1(), yb_any_dev_os_write(), yb_any_file_wclose(), and yb_any_file_wopen().
#define LOG_TYPE_TAPE 2
Definition at line 634 of file msystem.h.
Referenced by ascii_log_close(), ascii_log_open(), ascii_write(), dump_log_close(), dump_log_open(), dump_write(), lazy_copy(), lazy_main(), log_write(), midas_flush_buffer(), midas_log_close(), midas_log_open(), tr_poststop(), tr_start(), tr_start1(), tr_stop(), yb_any_dev_os_read(), yb_any_dev_os_write(), yb_any_file_rclose(), yb_any_file_ropen(), yb_any_file_wclose(), yb_any_file_wopen(), ybos_buffer_flush(), ybos_logfile_close(), ybos_logfile_open(), and ybos_write().
#define MAX_RPC_CONNECTION 64
server/client connections
Definition at line 255 of file msystem.h.
Referenced by command_loop(), recv_event_check(), recv_tcp_check(), rpc_check_channels(), rpc_client_accept(), rpc_client_check(), rpc_client_connect(), rpc_client_disconnect(), rpc_get_server_option(), rpc_server_accept(), rpc_server_shutdown(), rpc_set_server_option(), and ss_suspend().
#define MAX_STRING_LENGTH 256
max string length for odb
Definition at line 256 of file msystem.h.
Referenced by build_log_list(), cm_scan_experiments(), db_check_record(), db_copy(), db_create_key(), db_find_key(), db_find_key1(), db_find_link(), db_find_link1(), db_paste(), db_save_tree_struct(), db_save_xml_key(), db_sprintf(), and ss_file_find().
#define MESSAGE_BUFFER_NAME "SYSMSG"
buffer name for messages
Definition at line 254 of file msystem.h.
Referenced by cm_msg(), cm_msg1(), cm_msg_register(), main(), tr_start(), and tr_start1().
#define MESSAGE_BUFFER_SIZE 100000
dox dox Definition of implementation specific constants buffer used for messages
Definition at line 253 of file msystem.h.
Referenced by cm_msg(), cm_msg1(), cm_msg_register(), main(), tr_start(), and tr_start1().
#define MSG_BM 1
Definition at line 399 of file msystem.h.
Referenced by bm_flush_cache(), bm_notify_client(), bm_receive_event(), bm_send_event(), rpc_client_dispatch(), and ss_suspend().
#define MSG_CLIENT 3
Definition at line 401 of file msystem.h.
#define MSG_LISTEN 5
Definition at line 403 of file msystem.h.
#define MSG_ODB 2
Definition at line 400 of file msystem.h.
Referenced by db_update_record(), rpc_client_dispatch(), and ss_suspend().
#define MSG_SERVER 4
Definition at line 402 of file msystem.h.
#define MSG_WATCHDOG 6
Definition at line 404 of file msystem.h.
Referenced by rpc_check_channels(), and rpc_client_dispatch().
#define NET_BUFFER_SIZE
Value:
(ALIGN8(MAX_EVENT_SIZE)+sizeof(EVENT_HEADER)+\
4*8 + sizeof(NET_COMMAND_HEADER))
Definition at line 257 of file msystem.h.
Referenced by bm_receive_event(), mrpc_call(), mrpc_execute(), mrpc_server_loop(), recv_event_server(), recv_tcp_server(), rpc_call(), rpc_client_call(), rpc_execute(), and rpc_server_receive().
#define O_BINARY 0
Definition at line 351 of file msystem.h.
Referenced by cmd_loop(), el_delete_message(), el_search_message(), el_submit(), ftp_get(), ftp_put(), getcfg(), hs_fdump(), hs_open_file(), interprete(), main(), midas_log_open(), open_log_midstat(), show_elog_page(), ss_shm_open(), submit_elog(), tape_backup(), tape_restore(), yb_any_file_ropen(), yb_any_file_wopen(), yb_file_fragment(), yb_ymfile_open(), and ybos_logfile_open().
#define O_TEXT 0
Definition at line 352 of file msystem.h.
Referenced by command_loop(), db_load(), db_save(), and db_save_xml().
#define TCP_FAST 0x80000000l
Definition at line 397 of file msystem.h.
Referenced by rpc_call(), rpc_client_call(), rpc_execute(), and rpc_send_event().
#define TELL (fh) lseek(fh, 0, SEEK_CUR)
Definition at line 369 of file msystem.h.
Referenced by el_delete_message(), el_retrieve(), el_search_message(), el_submit(), hs_count_events(), hs_count_vars(), hs_define_event(), hs_dump(), hs_enum_vars(), hs_gen_index(), hs_get_var(), hs_read(), hs_write_event(), and show_elog_page().
#define UDP_FIRST 0x80000000l
Definition at line 396 of file msystem.h.
Referenced by recv_udp(), and send_udp().
#define YBOS_SUPPORT
Definition at line 271 of file msystem.h.
Function Documentation
INT bm_check_buffers (void)
Check if any requested event is waiting in a buffer
Returns:
TRUE More events are waiting
FALSE No more events are waiting
Definition at line 7429 of file midas.c.
References _buffer_entries, BM_MORE_EVENTS, bm_push_event(), FALSE, index, rpc_get_server_acception(), rpc_get_server_option(), RPC_OSERVER_TYPE, ss_gettid(), ss_millitime(), ST_MTHREAD, ST_SINGLE, ST_SUBPROCESS, start_time, status, and TRUE.
Referenced by cm_yield().
{
#ifdef LOCAL_ROUTINES
   {
      INT index, status = 0;
      INT server_type, server_conn, tid;
      BOOL bMore;
      DWORD start_time;
      server_type = rpc_get_server_option(RPC_OSERVER_TYPE);
      server_conn = rpc_get_server_acception();
      tid = ss_gettid();
      /* if running as a server, buffer checking is done by client
         via ASYNC bm_receive_event */
      if (server_type == ST_SUBPROCESS || server_type == ST_MTHREAD)
         return FALSE;
      bMore = FALSE;
      start_time = ss_millitime();
      /* go through all buffers */
      for (index = 0; index < _buffer_entries; index++) {
         if (server_type == ST_SINGLE && _buffer[index].index != server_conn)
            continue;
         if (server_type != ST_SINGLE && _buffer[index].index != tid)
            continue;
         if (!_buffer[index].attached)
            continue;
         do {
            /* one bm_push_event could cause a run stop and a buffer close, which
               would crash the next call to bm_push_event(). So check for valid
               buffer on each call */
            if (index < _buffer_entries && _buffer[index].buffer_header->name != NULL)
               status = bm_push_event(_buffer[index].buffer_header->name);
            if (status != BM_MORE_EVENTS)
               break;
            /* stop after one second */
            if (ss_millitime() - start_time > 1000) {
               bMore = TRUE;
               break;
            }
         } while (TRUE);
      }
      return bMore;
   }
#else                           /* LOCAL_ROUTINES */
   return FALSE;
#endif
}
void EXPRT bm_defragment_event (HNDLE buffer_handle, HNDLE request_id, EVENT_HEADER * pevent, void * pdata, void(*)(HNDLE, HNDLE, EVENT_HEADER *, void *) dispatcher)
Definition at line 7810 of file midas.c.
References cm_msg, data_size, EVENT_DEFRAG_BUFFER::data_size, EVENT_HEADER::data_size, EVENT_DEFRAG_BUFFER::event_id, EVENT_HEADER::event_id, EVENTID_FRAG1, i, MAX_DEFRAG_EVENTS, MERROR, EVENT_DEFRAG_BUFFER::pevent, and EVENT_DEFRAG_BUFFER::received.
Referenced by bm_poll_event(), and bm_push_event().
         : bm_defragment_event
  Purpose: Called internally from the event receiving routines
           bm_push_event and bm_poll_event to recombine event
           fragments and call the user callback routine upon
           completion.
  Input:
    HNDLE buffer_handle  Handle for the buffer containing event
    HNDLE request_id     Handle for event request
    EVENT_HEADER *pevent Pointer to event header
    void *pata           Pointer to event data
    dispatcher()         User callback routine
  Output:
    <calls dispatcher() after successfull recombination of event>
  Function value:
    void
\********************************************************************/
{
   INT i;
   if ((pevent->event_id & 0xF000) == EVENTID_FRAG1) {
    /*---- start new event ----*/
      /* check if fragments already stored */
      for (i = 0; i < MAX_DEFRAG_EVENTS; i++)
         if (defrag_buffer[i].event_id == (pevent->event_id & 0x0FFF))
            break;
      if (i < MAX_DEFRAG_EVENTS) {
         free(defrag_buffer[i].pevent);
         memset(&defrag_buffer[i].event_id, 0, sizeof(EVENT_DEFRAG_BUFFER));
         cm_msg(MERROR, "bm_defragement_event",
                "Received new event with ID %d while old fragments were not completed",
                (pevent->event_id & 0x0FFF));
      }
      /* search new slot */
      for (i = 0; i < MAX_DEFRAG_EVENTS; i++)
         if (defrag_buffer[i].event_id == 0)
            break;
      if (i == MAX_DEFRAG_EVENTS) {
         cm_msg(MERROR, "bm_defragment_evnet",
                "Not eough defragment buffers, please increase MAX_DEFRAG_EVENTS and recompile");
         return;
      }
      /* check event size */
      if (pevent->data_size != sizeof(DWORD)) {
         cm_msg(MERROR, "bm_defragment_evnet",
                "Received first event fragment with %s bytes instead of %d bytes, event ignored",
                pevent->data_size, sizeof(DWORD));
         return;
      }
      /* setup defragment buffer */
      defrag_buffer[i].event_id = (pevent->event_id & 0x0FFF);
      defrag_buffer[i].data_size = *(DWORD *) pdata;
      defrag_buffer[i].received = 0;
      defrag_buffer[i].pevent =
          (EVENT_HEADER *) malloc(sizeof(EVENT_HEADER) + defrag_buffer[i].data_size);
      if (defrag_buffer[i].pevent == NULL) {
         memset(&defrag_buffer[i].event_id, 0, sizeof(EVENT_DEFRAG_BUFFER));
         cm_msg(MERROR, "bm_defragement_event",
                "Not enough memory to allocate event defragment buffer");
         return;
      }
      memcpy(defrag_buffer[i].pevent, pevent, sizeof(EVENT_HEADER));
      defrag_buffer[i].pevent->event_id = defrag_buffer[i].event_id;
      defrag_buffer[i].pevent->data_size = defrag_buffer[i].data_size;
      return;
   }
   /* search buffer for that event */
   for (i = 0; i < MAX_DEFRAG_EVENTS; i++)
      if (defrag_buffer[i].event_id == (pevent->event_id & 0xFFF))
         break;
   if (i == MAX_DEFRAG_EVENTS) {
      /* no buffer available -> no first fragment received */
      free(defrag_buffer[i].pevent);
      memset(&defrag_buffer[i].event_id, 0, sizeof(EVENT_DEFRAG_BUFFER));
      cm_msg(MERROR, "bm_defragement_event",
             "Received fragment with no first fragment (ID %d)",
             pevent->event_id & 0x0FFF);
      return;
   }
   /* add fragment to buffer */
   if (pevent->data_size + defrag_buffer[i].received > defrag_buffer[i].data_size) {
      free(defrag_buffer[i].pevent);
      memset(&defrag_buffer[i].event_id, 0, sizeof(EVENT_DEFRAG_BUFFER));
      cm_msg(MERROR, "bm_defragement_event",
             "Received fragments with more data (%d) than event size (%d)",
             pevent->data_size + defrag_buffer[i].received, defrag_buffer[i].data_size);
      return;
   }
   memcpy(((char *) defrag_buffer[i].pevent) + sizeof(EVENT_HEADER) +
          defrag_buffer[i].received, pdata, pevent->data_size);
   defrag_buffer[i].received += pevent->data_size;
   if (defrag_buffer[i].received == defrag_buffer[i].data_size) {
      /* event complete */
      dispatcher(buffer_handle, request_id, defrag_buffer[i].pevent,
                 defrag_buffer[i].pevent + 1);
      free(defrag_buffer[i].pevent);
      memset(&defrag_buffer[i].event_id, 0, sizeof(EVENT_DEFRAG_BUFFER));
   }
}
INT bm_lock_buffer (INT buffer_handle)
Definition at line 5451 of file midas.c.
References _buffer_entries, BM_INVALID_HANDLE, BM_SUCCESS, cm_msg, MERROR, and ss_mutex_wait_for().
Referenced by bm_add_event_request(), bm_close_buffer(), bm_empty_buffers(), bm_flush_cache(), bm_get_buffer_info(), bm_get_buffer_level(), bm_open_buffer(), bm_push_event(), bm_receive_event(), bm_remove_event_request(), bm_send_event(), bm_skip_event(), cm_cleanup(), and cm_watchdog().
         : bm_lock_buffer
  Purpose: Lock a buffer for exclusive access via system mutex calls.
  Input:
    INT    bufer_handle     Handle to the buffer to lock
  Output:
    none
  Function value:
    BM_SUCCESS              Successful completion
    BM_INVALID_HANDLE       Buffer handle is invalid
\********************************************************************/
{
   if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
      cm_msg(MERROR, "bm_lock_buffer", "invalid buffer handle %d", buffer_handle);
      return BM_INVALID_HANDLE;
   }
   ss_mutex_wait_for(_buffer[buffer_handle - 1].mutex, 0);
   return BM_SUCCESS;
}
INT EXPRT bm_mark_read_waiting (BOOL flag)
dox
Definition at line 7495 of file midas.c.
References _buffer_entries, BM_SUCCESS, BUFFER::buffer_header, BUFFER_HEADER::client, BUFFER::client_index, i, index, BUFFER_CLIENT::read_wait, RPC_BM_MARK_READ_WAITING, rpc_call(), rpc_get_server_acception(), rpc_get_server_option(), rpc_is_remote(), RPC_OSERVER_TYPE, ss_gettid(), and ST_SINGLE.
Referenced by bm_open_buffer(), bm_poll_event(), cm_yield(), and rpc_server_dispatch().
         : bm_mark_read_waiting
  Purpose: Mark all open buffers ready for receiving events.
           Called internally by ss_suspend
  Input:
    BOOL flag               TRUE for waiting, FALSE for not waiting
  Output:
    none
  Function value:
    BM_SUCCESS              Successful completion
\********************************************************************/
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_MARK_READ_WAITING, flag);
#ifdef LOCAL_ROUTINES
   {
      INT i;
      BUFFER_HEADER *pheader;
      BUFFER_CLIENT *pclient;
      /* Mark all buffer for read waiting */
      for (i = 0; i < _buffer_entries; i++) {
         if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_SINGLE &&
             _buffer[i].index != rpc_get_server_acception())
            continue;
         if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_SINGLE &&
             _buffer[i].index != ss_gettid())
            continue;
         if (!_buffer[i].attached)
            continue;
         pheader = _buffer[i].buffer_header;
         pclient = pheader->client + _buffer[i].client_index;
         pclient->read_wait = flag;
      }
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_notify_client (char * buffer_name, int socket)
Definition at line 7548 of file midas.c.
References _buffer_entries, BM_INVALID_HANDLE, BM_SUCCESS, buffer, callback, CF_ASCII, DB_SUCCESS, NET_COMMAND::header, i, last_time, MSG_BM, NET_COMMAND_HEADER::param_size, NET_COMMAND_HEADER::routine_id, RPC_CONVERT_FLAGS, rpc_convert_single(), rpc_get_server_option(), RPC_OUTGOING, send_tcp(), ss_millitime(), and TID_DWORD.
Referenced by cm_dispatch_ipc().
         : bm_notify_client
  Purpose: Called by cm_dispatch_ipc. Send an event notification to
           the connected client
  Input:
    char  *buffer_name      Name of buffer
    int   socket            Network socket to client
  Output:
    none
  Function value:
    BM_SUCCESS              Successful completion
\********************************************************************/
{
   char buffer[32];
   NET_COMMAND *nc;
   INT i, convert_flags;
   static DWORD last_time = 0;
   for (i = 0; i < _buffer_entries; i++)
      if (strcmp(buffer_name, _buffer[i].buffer_header->name) == 0)
         break;
   if (i == _buffer_entries)
      return BM_INVALID_HANDLE;
   /* don't send notification if client has no callback defined
      to receive events -> client calls bm_receive_event manually */
   if (!_buffer[i].callback)
      return DB_SUCCESS;
   convert_flags = rpc_get_server_option(RPC_CONVERT_FLAGS);
   /* only send notification once each 500ms */
   if (ss_millitime() - last_time < 500 && !(convert_flags & CF_ASCII))
      return DB_SUCCESS;
   last_time = ss_millitime();
   if (convert_flags & CF_ASCII) {
      sprintf(buffer, "MSG_BM&%s", buffer_name);
      send_tcp(socket, buffer, strlen(buffer) + 1, 0);
   } else {
      nc = (NET_COMMAND *) buffer;
      nc->header.routine_id = MSG_BM;
      nc->header.param_size = 0;
      if (convert_flags) {
         rpc_convert_single(&nc->header.routine_id, TID_DWORD,
                            RPC_OUTGOING, convert_flags);
         rpc_convert_single(&nc->header.param_size, TID_DWORD,
                            RPC_OUTGOING, convert_flags);
      }
      /* send the update notification to the client */
      send_tcp(socket, (char *) buffer, sizeof(NET_COMMAND_HEADER), 0);
   }
   return BM_SUCCESS;
}
INT bm_push_event (char * buffer_name)
Check a buffer if an event is available and call the dispatch function if found.
Parameters:
buffer_name Name of buffer
Returns:
BM_SUCCESS, BM_INVALID_HANDLE, BM_TRUNCATED, BM_ASYNC_RETURN, RPC_NET_ERROR
Definition at line 7157 of file midas.c.
References _buffer_entries, _event_buffer_size, _request_list_entries, ALIGN8, BUFFER::attached, bm_defragment_event(), BM_INVALID_HANDLE, bm_lock_buffer(), bm_match_event(), BM_MORE_EVENTS, BM_NO_MEMORY, BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER::callback, BUFFER_HEADER::client, BUFFER::client_index, cm_msg, EVENT_HEADER::data_size, REQUEST_LIST::dispatcher, EVENT_REQUEST::event_id, EVENT_HEADER::event_id, BUFFER_CLIENT::event_request, EVENTID_FRAG, EVENTID_FRAG1, FALSE, found, i, if, LOOP, M_MALLOC, BUFFER_HEADER::max_client_index, BUFFER_CLIENT::max_request_index, MDEBUG, MERROR, BUFFER_HEADER::num_out_events, BUFFER_CLIENT::pid, BUFFER_CLIENT::port, BUFFER::read_cache, BUFFER::read_cache_rp, BUFFER::read_cache_size, BUFFER::read_cache_wp, BUFFER_HEADER::read_pointer, BUFFER_CLIENT::read_pointer, BUFFER_HEADER::size, size, ss_getpid(), ss_gettid(), ss_resume(), BUFFER_CLIENT::tid, EVENT_REQUEST::trigger_mask, TRUE, EVENT_REQUEST::valid, BUFFER_HEADER::write_pointer, and BUFFER_CLIENT::write_wait.
Referenced by bm_check_buffers(), and cm_dispatch_ipc().
{
#ifdef LOCAL_ROUTINES
   {
      BUFFER *pbuf;
      BUFFER_HEADER *pheader;
      BUFFER_CLIENT *pclient, *pc, *pctmp;
      EVENT_REQUEST *prequest;
      EVENT_HEADER *pevent;
      char *pdata;
      INT i, min_wp, size, total_size, buffer_handle;
      INT my_client_index;
      BOOL found;
      INT old_read_pointer, new_read_pointer;
      for (i = 0; i < _buffer_entries; i++)
         if (strcmp(buffer_name, _buffer[i].buffer_header->name) == 0)
            break;
      if (i == _buffer_entries)
         return BM_INVALID_HANDLE;
      buffer_handle = i + 1;
      pbuf = &_buffer[buffer_handle - 1];
      if (!pbuf->attached)
         return BM_INVALID_HANDLE;
      /* return immediately if no callback routine is defined */
      if (!pbuf->callback)
         return BM_SUCCESS;
      if (_event_buffer_size == 0) {
         _event_buffer = (EVENT_HEADER *) M_MALLOC(1000);
         if (_event_buffer == NULL) {
            cm_msg(MERROR, "bm_push_event", "not enough memory to allocate cache buffer");
            return BM_NO_MEMORY;
         }
         _event_buffer_size = 1000;
      }
    CACHE_READ:
      /* look if there is anything in the cache */
      if (pbuf->read_cache_wp > pbuf->read_cache_rp) {
         pevent = (EVENT_HEADER *) (pbuf->read_cache + pbuf->read_cache_rp);
         size = pevent->data_size + sizeof(EVENT_HEADER);
         /* correct size for DWORD boundary */
         size = ALIGN8(size);
         /* increment read pointer */
         pbuf->read_cache_rp += size;
         if (pbuf->read_cache_rp == pbuf->read_cache_wp)
            pbuf->read_cache_rp = pbuf->read_cache_wp = 0;
         /* call dispatcher */
         for (i = 0; i < _request_list_entries; i++)
            if (_request_list[i].buffer_handle == buffer_handle &&
                bm_match_event(_request_list[i].event_id,
                               _request_list[i].trigger_mask, pevent)) {
               /* if event is fragmented, call defragmenter */
               if ((pevent->event_id & 0xF000) == EVENTID_FRAG1 ||
                   (pevent->event_id & 0xF000) == EVENTID_FRAG)
                  bm_defragment_event(buffer_handle, i, pevent, (void *) (pevent + 1),
                                      _request_list[i].dispatcher);
               else
                  _request_list[i].dispatcher(buffer_handle, i, pevent,
                                              (void *) (pevent + 1));
            }
         return BM_MORE_EVENTS;
      }
      /* calculate some shorthands */
      pheader = pbuf->buffer_header;
      pdata = (char *) (pheader + 1);
      my_client_index = pbuf->client_index;
      pclient = pheader->client;
      pc = pheader->client + my_client_index;
      /* first do a quick check without locking the buffer */
      if (pheader->write_pointer == pc->read_pointer)
         return BM_SUCCESS;
      /* lock the buffer */
      bm_lock_buffer(buffer_handle);
    LOOP:
      if (pheader->write_pointer == pc->read_pointer) {
         bm_unlock_buffer(buffer_handle);
         /* return if no event available */
         return BM_SUCCESS;
      }
      /* check if event at current read pointer matches a request */
      found = FALSE;
      do {
         pevent = (EVENT_HEADER *) (pdata + pc->read_pointer);
         total_size = pevent->data_size + sizeof(EVENT_HEADER);
         total_size = ALIGN8(total_size);
         prequest = pc->event_request;
         for (i = 0; i < pc->max_request_index; i++, prequest++)
            if (prequest->valid &&
                bm_match_event(prequest->event_id, prequest->trigger_mask, pevent)) {
               /* we found one, so copy it */
               if (pbuf->read_cache_size > 0 &&
                   !(total_size > pbuf->read_cache_size && pbuf->read_cache_wp == 0)) {
                  /* copy dispatch function and event to cache */
                  if (pbuf->read_cache_size - pbuf->read_cache_wp <
                      total_size + (INT) sizeof(void *) + (INT) sizeof(INT))
                     goto CACHE_FULL;
                  if (pc->read_pointer + total_size <= pheader->size) {
                     /* copy event to cache */
                     memcpy(pbuf->read_cache + pbuf->read_cache_wp, pevent, total_size);
                  } else {
                     /* event is splitted */
                     size = pheader->size - pc->read_pointer;
                     memcpy(pbuf->read_cache + pbuf->read_cache_wp, pevent, size);
                     memcpy((char *) pbuf->read_cache + pbuf->read_cache_wp + size,
                            pdata, total_size - size);
                  }
                  pbuf->read_cache_wp += total_size;
               } else {
                  /* copy event to copy buffer, save dispatcher */
                  if (total_size > _event_buffer_size) {
                     _event_buffer = (EVENT_HEADER *) realloc(_event_buffer, total_size);
                     _event_buffer_size = total_size;
                  }
                  if (pc->read_pointer + total_size <= pheader->size) {
                     memcpy(_event_buffer, pevent, total_size);
                  } else {
                     /* event is splitted */
                     size = pheader->size - pc->read_pointer;
                     memcpy(_event_buffer, pevent, size);
                     memcpy((char *) _event_buffer + size, pdata, total_size - size);
                  }
               }
               /* update statistics */
               found = TRUE;
               pheader->num_out_events++;
               break;
            }
         old_read_pointer = pc->read_pointer;
         /* shift read pointer */
         new_read_pointer = (pc->read_pointer + total_size) % pheader->size;
         if (new_read_pointer > pheader->size - (int) sizeof(EVENT_HEADER))
            new_read_pointer = 0;
#ifdef DEBUG_MSG
         cm_msg(MDEBUG, "bm_receive_event -> wp=%d, rp %d -> %d (found=%d,size=%d)",
                pheader->write_pointer, pc->read_pointer, new_read_pointer, found,
                total_size);
#endif
         pc->read_pointer = new_read_pointer;
         /*
            Repeat until a requested event is found or no more events
            are available or large event received.
          */
         if (pbuf->read_cache_size == 0 && found)
            break;
         /* break if event has bypassed read cache */
         if (pbuf->read_cache_size > 0 &&
             total_size > pbuf->read_cache_size && pbuf->read_cache_wp == 0)
            break;
      } while (pheader->write_pointer != pc->read_pointer);
    CACHE_FULL:
      /* calculate global read pointer as "minimum" of client read pointers */
      min_wp = pheader->write_pointer;
      for (i = 0, pctmp = pclient; i < pheader->max_client_index; i++, pctmp++)
         if (pctmp->pid) {
            if (pctmp->read_pointer < min_wp)
               min_wp = pctmp->read_pointer;
            if (pctmp->read_pointer > pheader->write_pointer &&
                pctmp->read_pointer - pheader->size < min_wp)
               min_wp = pctmp->read_pointer - pheader->size;
         }
      if (min_wp < 0)
         min_wp += pheader->size;
      pheader->read_pointer = min_wp;
      /*
         If read pointer has been changed, it may have freed up some space
         for waiting producers. So check if free space is now more than 50%
         of the buffer size and wake waiting producers.
       */
      size = pc->read_pointer - pheader->write_pointer;
      if (size <= 0)
         size += pheader->size;
      if (size >= pheader->size * 0.5)
         for (i = 0, pctmp = pclient; i < pheader->max_client_index; i++, pctmp++)
            if (pctmp->pid && (pctmp->write_wait < size) && (pctmp->pid != ss_getpid() ||       /* check if not own thread */
                                                             (pctmp->pid == ss_getpid()
                                                              && pctmp->tid !=
                                                              ss_gettid()))) {
#ifdef DEBUG_MSG
               cm_msg(MDEBUG, "Receive wake: rp=%d, wp=%d, level=%1.1lf",
                      pheader->read_pointer,
                      pheader->write_pointer, 100 - 100.0 * size / pheader->size);
#endif
               ss_resume(pctmp->port, "B  ");
            }
      /* if no matching event found, start again */
      if (!found)
         goto LOOP;
      bm_unlock_buffer(buffer_handle);
      if (pbuf->read_cache_size > 0 &&
          !(total_size > pbuf->read_cache_size && pbuf->read_cache_wp == 0))
         goto CACHE_READ;
      /* call dispatcher */
      for (i = 0; i < _request_list_entries; i++)
         if (_request_list[i].buffer_handle == buffer_handle &&
             bm_match_event(_request_list[i].event_id,
                            _request_list[i].trigger_mask, _event_buffer)) {
            if ((_event_buffer->event_id & 0xF000) == EVENTID_FRAG1 ||
                (_event_buffer->event_id & 0xF000) == EVENTID_FRAG)
               bm_defragment_event(buffer_handle, i, _event_buffer,
                                   (void *) (((EVENT_HEADER *) _event_buffer) + 1),
                                   _request_list[i].dispatcher);
            else
               _request_list[i].dispatcher(buffer_handle, i, _event_buffer,
                                           (void *) (((EVENT_HEADER *) _event_buffer) +
                                                     1));
         }
      return BM_MORE_EVENTS;
   }
#else                           /* LOCAL_ROUTINES */
   return BM_SUCCESS;
#endif
}
INT EXPRT bm_remove_event_request (INT buffer_handle, INT request_id)
Delete a previously placed request for a specific event type in the client structure of the buffer refereced by buffer_handle.
Parameters:
buffer_handle Handle to the buffer where the re- quest should be placed in
request_id Request id returned by bm_request_event
Returns:
BM_SUCCESS, BM_INVALID_HANDLE, BM_NOT_FOUND, RPC_NET_ERROR
Definition at line 5920 of file midas.c.
References _buffer_entries, BUFFER_CLIENT::all_flag, BM_INVALID_HANDLE, bm_lock_buffer(), BM_NOT_FOUND, BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER::client_index, cm_msg, BUFFER_CLIENT::event_request, FALSE, GET_ALL, i, EVENT_REQUEST::id, MAX_EVENT_REQUESTS, BUFFER_CLIENT::max_request_index, MERROR, RPC_BM_REMOVE_EVENT_REQUEST, rpc_call(), rpc_is_remote(), EVENT_REQUEST::sampling_type, TRUE, and EVENT_REQUEST::valid.
Referenced by bm_delete_request(), and rpc_server_dispatch().
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_REMOVE_EVENT_REQUEST, buffer_handle, request_id);
#ifdef LOCAL_ROUTINES
   {
      INT i, deleted;
      BUFFER_CLIENT *pclient;
      if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
         cm_msg(MERROR, "bm_remove_event_request", "invalid buffer handle %d",
                buffer_handle);
         return BM_INVALID_HANDLE;
      }
      if (!_buffer[buffer_handle - 1].attached) {
         cm_msg(MERROR, "bm_remove_event_request", "invalid buffer handle %d",
                buffer_handle);
         return BM_INVALID_HANDLE;
      }
      /* get a pointer to the proper client structure */
      pclient = &(_buffer[buffer_handle - 1].buffer_header->
                  client[_buffer[buffer_handle - 1].client_index]);
      /* lock buffer */
      bm_lock_buffer(buffer_handle);
      /* check all requests and set to zero if matching */
      for (i = 0, deleted = 0; i < pclient->max_request_index; i++)
         if (pclient->event_request[i].valid &&
             pclient->event_request[i].id == request_id) {
            memset(&pclient->event_request[i], 0, sizeof(EVENT_REQUEST));
            deleted++;
         }
      /* calculate new max_request_index entry */
      for (i = MAX_EVENT_REQUESTS - 1; i >= 0; i--)
         if (pclient->event_request[i].valid)
            break;
      pclient->max_request_index = i + 1;
      /* caluclate new all_flag */
      pclient->all_flag = FALSE;
      for (i = 0; i < pclient->max_request_index; i++)
         if (pclient->event_request[i].valid &&
             (pclient->event_request[i].sampling_type & GET_ALL)) {
            pclient->all_flag = TRUE;
            break;
         }
      bm_unlock_buffer(buffer_handle);
      if (!deleted)
         return BM_NOT_FOUND;
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_unlock_buffer (INT buffer_handle)
Definition at line 5479 of file midas.c.
References _buffer_entries, BM_INVALID_HANDLE, BM_SUCCESS, cm_msg, MERROR, and ss_mutex_release().
Referenced by bm_add_event_request(), bm_close_buffer(), bm_empty_buffers(), bm_flush_cache(), bm_get_buffer_info(), bm_get_buffer_level(), bm_open_buffer(), bm_push_event(), bm_receive_event(), bm_remove_event_request(), bm_send_event(), bm_skip_event(), cm_cleanup(), and cm_watchdog().
         : bm_unlock_buffer
  Purpose: Unlock a buffer via system mutex calls.
  Input:
    INT    bufer_handle     Handle to the buffer to lock
  Output:
    none
  Function value:
    BM_SUCCESS              Successful completion
    BM_INVALID_HANDLE       Buffer handle is invalid
\********************************************************************/
{
   if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
      cm_msg(MERROR, "bm_unlock_buffer", "invalid buffer handle %d", buffer_handle);
      return BM_INVALID_HANDLE;
   }
   ss_mutex_release(_buffer[buffer_handle - 1].mutex);
   return BM_SUCCESS;
}
INT cm_dispatch_ipc (char * message, int socket)
dox
Definition at line 4080 of file midas.c.
References bm_notify_client(), bm_push_event(), CM_SUCCESS, db_update_record(), hDB, and hKey.
Referenced by bm_open_buffer(), and db_open_database().
         : cm_dispatch_ipc
  Purpose: Called from ss_suspend if an IPC message arrives
  Input:
    INT   msg               IPC message we got, MSG_ODB/MSG_BM
    INT   p1, p2            Optional parameters
    int   socket            Optional server socket
  Output:
    none
  Function value:
    CM_SUCCESS              Successful completion
\********************************************************************/
{
   if (message[0] == 'O') {
      HNDLE hDB, hKey;
      sscanf(message + 2, "%d %d", &hDB, &hKey);
      return db_update_record(hDB, hKey, socket);
   }
   /* message == "B  " means "resume event sender" */
   if (message[0] == 'B' && message[2] != ' ') {
      char str[80];
      strcpy(str, message + 2);
      if (strchr(str, ' '))
         *strchr(str, ' ') = 0;
      if (socket)
         return bm_notify_client(str, socket);
      else
         return bm_push_event(str);
   }
   return CM_SUCCESS;
}
INT EXPRT cm_get_path (char * path)
Return the path name previously set with cm_set_path.
Parameters:
path Pathname
Returns:
CM_SUCCESS
Definition at line 1735 of file midas.c.
References CM_SUCCESS.
Referenced by cm_connect_experiment1(), cm_msg_log(), cm_msg_log1(), cm_msg_retrieve(), command_loop(), logger_init(), ss_mutex_create(), ss_shm_close(), ss_shm_flush(), and ss_shm_open().
{
   strcpy(path, _path_name);
   return CM_SUCCESS;
}
INT EXPRT cm_msg_log (INT message_type, const char * message)
Write message to logging file. Called by cm_msg.
Attention:
May burn your fingers
Parameters:
message_type Message type
message Message string
Returns:
CM_SUCCESS
Definition at line 1049 of file midas.c.
References cm_get_experiment_database(), cm_get_path(), CM_SUCCESS, db_find_key(), db_get_value(), DB_SUCCESS, DIR_SEPARATOR, DIR_SEPARATOR_STR, filename, hDB, hKey, MT_DEBUG, rpc_call(), RPC_CM_MSG_LOG, rpc_is_remote(), size, ss_asctime(), status, TID_STRING, and TRUE.
Referenced by cm_msg(), and rpc_server_dispatch().
{
   char dir[256];
   char filename[256];
   char path[256];
   char str[256];
   FILE *f;
   INT status, size;
   HNDLE hDB, hKey;
   if (rpc_is_remote())
      return rpc_call(RPC_CM_MSG_LOG, message_type, message);
   if (message_type != MT_DEBUG) {
      cm_get_experiment_database(&hDB, NULL);
      if (hDB) {
         status = db_find_key(hDB, 0, "/Logger/Data dir", &hKey);
         if (status == DB_SUCCESS) {
            size = sizeof(dir);
            memset(dir, 0, size);
            db_get_value(hDB, 0, "/Logger/Data dir", dir, &size, TID_STRING, TRUE);
            if (dir[0] != 0)
               if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
                  strcat(dir, DIR_SEPARATOR_STR);
            strcpy(filename, "midas.log");
            size = sizeof(filename);
            db_get_value(hDB, 0, "/Logger/Message file", filename, &size, TID_STRING,
                         TRUE);
            strcpy(path, dir);
            strcat(path, filename);
         } else {
            cm_get_path(dir);
            if (dir[0] != 0)
               if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
                  strcat(dir, DIR_SEPARATOR_STR);
            strcpy(path, dir);
            strcat(path, "midas.log");
         }
      } else
         strcpy(path, "midas.log");
      f = fopen(path, "a");
      if (f == NULL) {
         printf("Cannot open message log file %s\n", path);
      } else {
         strcpy(str, ss_asctime());
         fprintf(f, str);
         fprintf(f, " %s\n", message);
         fclose(f);
      }
   }
   return CM_SUCCESS;
}
INT EXPRT cm_msg_log1 (INT message_type, const char * message, const char * facility)
Write message to logging file. Called by cm_msg().
Definition at line 1118 of file midas.c.
References cm_get_experiment_database(), cm_get_path(), CM_SUCCESS, db_find_key(), db_get_value(), DB_SUCCESS, DIR_SEPARATOR, DIR_SEPARATOR_STR, filename, hDB, hKey, MT_DEBUG, rpc_call(), RPC_CM_MSG_LOG1, rpc_is_remote(), size, ss_asctime(), status, TID_STRING, and TRUE.
Referenced by cm_msg1(), and rpc_server_dispatch().
         : cm_msg_log1
  Purpose: Write message to logging file. Called by cm_msg.
           Internal use only
  Input:
    INT    message_type      Message type
    char   *message          Message string
    char   *
  Output:
    none
  Function value:
    CM_SUCCESS
\********************************************************************/
{
   char dir[256];
   char filename[256];
   char path[256];
   char str[256];
   FILE *f;
   INT status, size;
   HNDLE hDB, hKey;
   if (rpc_is_remote())
      return rpc_call(RPC_CM_MSG_LOG1, message_type, message, facility);
   if (message_type != MT_DEBUG) {
      cm_get_experiment_database(&hDB, NULL);
      if (hDB) {
         status = db_find_key(hDB, 0, "/Logger/Data dir", &hKey);
         if (status == DB_SUCCESS) {
            size = sizeof(dir);
            memset(dir, 0, size);
            db_get_value(hDB, 0, "/Logger/Data dir", dir, &size, TID_STRING, TRUE);
            if (dir[0] != 0)
               if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
                  strcat(dir, DIR_SEPARATOR_STR);
            if (facility[0]) {
               strcpy(filename, facility);
               strcat(filename, ".log");
            } else {
               strcpy(filename, "midas.log");
               size = sizeof(filename);
               db_get_value(hDB, 0, "/Logger/Message file", filename, &size, TID_STRING,
                            TRUE);
            }
            strcpy(path, dir);
            strcat(path, filename);
         } else {
            cm_get_path(dir);
            if (dir[0] != 0)
               if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
                  strcat(dir, DIR_SEPARATOR_STR);
            strcpy(path, dir);
            if (facility[0]) {
               strcat(path, facility);
               strcat(path, ".log");
            } else
               strcat(path, "midas.log");
         }
      } else {
         if (facility[0]) {
            strcpy(path, facility);
            strcat(path, ".log");
         } else
            strcpy(path, "midas.log");
      }
      f = fopen(path, "a");
      if (f == NULL) {
         printf("Cannot open message log file %s\n", path);
      } else {
         strcpy(str, ss_asctime());
         fprintf(f, str);
         fprintf(f, " %s\n", message);
         fclose(f);
      }
   }
   return CM_SUCCESS;
}
INT EXPRT cm_set_path (char * path)
Set path to actual experiment. This function gets called by cm_connect_experiment if the connection is established to a local experiment (not through the TCP/IP server). The path is then used for all shared memory routines.
Parameters:
path Pathname
Returns:
CM_SUCCESS
Definition at line 1718 of file midas.c.
References CM_SUCCESS, DIR_SEPARATOR, and DIR_SEPARATOR_STR.
Referenced by cm_connect_experiment1().
{
   strcpy(_path_name, path);
   /* check for trailing directory seperator */
   if (strlen(_path_name) > 0 && _path_name[strlen(_path_name) - 1] != DIR_SEPARATOR)
      strcat(_path_name, DIR_SEPARATOR_STR);
   return CM_SUCCESS;
}
INT db_close_all_records (void)
Release local memory for open records. This routines is called by db_close_all_databases() and cm_disconnect_experiment()
Returns:
DB_SUCCESS, DB_INVALID_HANDLE
Definition at line 7912 of file odb.c.
References _record_list_entries, data, DB_SUCCESS, handle, i, MODE_ALLOC, and MODE_WRITE.
Referenced by cm_disconnect_experiment(), and db_close_all_databases().
{
   INT i;
   for (i = 0; i < _record_list_entries; i++) {
      if (_record_list[i].handle) {
         if (_record_list[i].access_mode & MODE_WRITE)
            free(_record_list[i].copy);
         if (_record_list[i].access_mode & MODE_ALLOC)
            free(_record_list[i].data);
         memset(&_record_list[i], 0, sizeof(RECORD_LIST));
      }
   }
   if (_record_list_entries > 0) {
      _record_list_entries = 0;
      free(_record_list);
   }
   return DB_SUCCESS;
}
INT db_delete_key1 (HNDLE hDB, HNDLE hKey, INT level, BOOL follow_links)
Delete a subtree, using level information (only called internally by db_delete_key())
Definition at line 1990 of file odb.c.
References _database_entries, KEY::access_mode, cm_msg, KEY::data, DATABASE::database_header, db_delete_key1(), db_find_key(), DB_INVALID_HANDLE, db_lock_database(), DB_NO_ACCESS, DB_OPEN_RECORD, DB_SUCCESS, db_unlock_database(), db_validate_hkey(), FALSE, KEYLIST::first_key, free_data(), free_key(), MERROR, MODE_DELETE, KEY::next_key, KEY::notify_count, KEYLIST::num_keys, KEYLIST::parent, KEY::parent_keylist, PTYPE, DATABASE_HEADER::root_key, status, TID_KEY, TID_LINK, KEY::total_size, TRUE, and KEY::type.
Referenced by cm_delete_client_info(), db_delete_key(), and db_delete_key1().
{
#ifdef LOCAL_ROUTINES
   {
      DATABASE_HEADER *pheader;
      KEYLIST *pkeylist;
      KEY *pkey, *pnext_key, *pkey_tmp;
      HNDLE hKeyLink;
      BOOL deny_delete;
      INT status;
      if (hDB > _database_entries || hDB <= 0) {
         cm_msg(MERROR, "db_delete_key1", "invalid database handle");
         return DB_INVALID_HANDLE;
      }
      if (!_database[hDB - 1].attached) {
         cm_msg(MERROR, "db_delete_key1", "invalid database handle");
         return DB_INVALID_HANDLE;
      }
      if (hKey < sizeof(DATABASE_HEADER)) {
         cm_msg(MERROR, "db_delete_key1", "invalid key handle");
         return DB_INVALID_HANDLE;
      }
      /* lock database at the top level */
      if (level == 0)
         db_lock_database(hDB);
      pheader = _database[hDB - 1].database_header;
      pkey = (KEY *) ((char *) pheader + hKey);
      /* check if hKey argument is correct */
      if (!db_validate_hkey(pheader, hKey)) {
         db_unlock_database(hDB);
         return DB_INVALID_HANDLE;
      }
      /* check if someone has opened key or parent */
      if (level == 0)
         do {
            if (pkey->notify_count) {
               db_unlock_database(hDB);
               return DB_OPEN_RECORD;
            }
            if (pkey->parent_keylist == 0)
               break;
            pkeylist = (KEYLIST *) ((char *) pheader + pkey->parent_keylist);
            pkey = (KEY *) ((char *) pheader + pkeylist->parent);
         } while (TRUE);
      pkey = (KEY *) ((char *) pheader + hKey);
      pkeylist = (KEYLIST *) ((char *) pheader + pkey->data);
      deny_delete = FALSE;
      /* first recures subtree for keys */
      if (pkey->type == TID_KEY && pkeylist->first_key) {
         pkey = (KEY *) ((char *) pheader + pkeylist->first_key);
         do {
            pnext_key = (KEY *) (PTYPE) pkey->next_key;
            status = db_delete_key1(hDB, (PTYPE) pkey - (PTYPE) pheader,
                                    level + 1, follow_links);
            if (status == DB_NO_ACCESS)
               deny_delete = TRUE;
            if (pnext_key)
               pkey = (KEY *) ((char *) pheader + (PTYPE) pnext_key);
         } while (pnext_key);
      }
      /* follow links if requested */
      if (pkey->type == TID_LINK && follow_links) {
         status = db_find_key(hDB, 0, (char *) pheader + pkey->data, &hKeyLink);
         if (status == DB_SUCCESS && follow_links < 100)
            db_delete_key1(hDB, hKeyLink, level + 1, follow_links + 1);
         if (follow_links == 100)
            cm_msg(MERROR, "db_delete_key1", "try to delete cyclic link");
      }
      pkey = (KEY *) ((char *) pheader + hKey);
      /* return if key was already deleted by cyclic link */
      if (pkey->parent_keylist == 0) {
         if (level == 0)
            db_unlock_database(hDB);
         return DB_SUCCESS;
      }
      /* now delete key */
      if (hKey != pheader->root_key) {
         if (!(pkey->access_mode & MODE_DELETE) || deny_delete) {
            if (level == 0)
               db_unlock_database(hDB);
            return DB_NO_ACCESS;
         }
         if (pkey->notify_count) {
            if (level == 0)
               db_unlock_database(hDB);
            return DB_OPEN_RECORD;
         }
         /* delete key data */
         if (pkey->type == TID_KEY)
            free_key(pheader, (char *) pheader + pkey->data, pkey->total_size);
         else
            free_data(pheader, (char *) pheader + pkey->data, pkey->total_size);
         /* unlink key from list */
         pnext_key = (KEY *) (PTYPE) pkey->next_key;
         pkeylist = (KEYLIST *) ((char *) pheader + pkey->parent_keylist);
         if ((KEY *) ((char *) pheader + pkeylist->first_key) == pkey) {
            /* key is first in list */
            pkeylist->first_key = (PTYPE) pnext_key;
         } else {
            /* find predecessor */
            pkey_tmp = (KEY *) ((char *) pheader + pkeylist->first_key);
            while ((KEY *) ((char *) pheader + pkey_tmp->next_key) != pkey)
               pkey_tmp = (KEY *) ((char *) pheader + pkey_tmp->next_key);
            pkey_tmp->next_key = (PTYPE) pnext_key;
         }
         /* delete key */
         free_key(pheader, pkey, sizeof(KEY));
         pkeylist->num_keys--;
      }
      if (level == 0)
         db_unlock_database(hDB);
   }
#endif                          /* LOCAL_ROUTINES */
   return DB_SUCCESS;
}
INT EXPRT db_flush_database (HNDLE hDB)
dox
Definition at line 1422 of file odb.c.
References _database_entries, DATABASE_HEADER::client, DATABASE::client_index, cm_msg, DATABASE_HEADER::data_size, DATABASE::database_header, DB_INVALID_HANDLE, db_lock_database(), DB_SUCCESS, db_unlock_database(), index, MERROR, DATABASE_HEADER::name, rpc_call(), RPC_DB_FLUSH_DATABASE, rpc_get_server_acception(), rpc_get_server_option(), rpc_is_remote(), RPC_OSERVER_TYPE, ss_gettid(), ss_shm_flush(), and ST_SINGLE.
Referenced by cm_transition(), and rpc_server_dispatch().
         : db_flush_database
  Purpose: Flushes the shared memory of a database to its disk file.
  Input:
    HNDLE  hDB              Handle to the database, which is used as
                            an index to the _database array.
  Output:
    none
  Function value:
    DB_SUCCESS              Successful completion
    DB_INVALID_HANDLE       Database handle is invalid
    RPC_NET_ERROR           Network error
\********************************************************************/
{
   if (rpc_is_remote())
      return rpc_call(RPC_DB_FLUSH_DATABASE, hDB);
#ifdef LOCAL_ROUTINES
   else {
      DATABASE_HEADER *pheader;
      DATABASE_CLIENT *pclient;
      INT index;
      if (hDB > _database_entries || hDB <= 0) {
         cm_msg(MERROR, "db_close_database", "invalid database handle");
         return DB_INVALID_HANDLE;
      }
      /*
         Check if database was opened by current thread. This is necessary
         in the server process where one thread may not close the database
         of other threads.
       */
      db_lock_database(hDB);
      index = _database[hDB - 1].client_index;
      pheader = _database[hDB - 1].database_header;
      pclient = &pheader->client[index];
      if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_SINGLE &&
          _database[hDB - 1].index != rpc_get_server_acception()) {
         db_unlock_database(hDB);
         return DB_INVALID_HANDLE;
      }
      if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_SINGLE &&
          _database[hDB - 1].index != ss_gettid()) {
         db_unlock_database(hDB);
         return DB_INVALID_HANDLE;
      }
      if (!_database[hDB - 1].attached) {
         cm_msg(MERROR, "db_close_database", "invalid database handle");
         db_unlock_database(hDB);
         return DB_INVALID_HANDLE;
      }
      /* flush shared memory to disk */
      ss_shm_flush(pheader->name, pheader,
                   sizeof(DATABASE_HEADER) + 2 * pheader->data_size);
      db_unlock_database(hDB);
   }
#endif                          /* LOCAL_ROUTINES */
   return DB_SUCCESS;
}
INT EXPRT db_lock_database (HNDLE hDB)
dox Lock a database for exclusive access via system mutex calls.
Parameters:
hDB Handle to the database to lock
Returns:
DB_SUCCESS, DB_INVALID_HANDLE, DB_TIMEOUT
Definition at line 1585 of file odb.c.
References _database_entries, cm_msg, DB_INVALID_HANDLE, DB_NO_MUTEX, DB_SUCCESS, DB_TIMEOUT, DATABASE::lock_cnt, MERROR, protect, ss_mutex_wait_for(), ss_shm_unprotect(), SS_SUCCESS, SS_TIMEOUT, and status.
Referenced by cm_check_client(), cm_cleanup(), cm_delete_client_info(), cm_get_watchdog_info(), cm_set_client_info(), cm_set_watchdog_params(), cm_watchdog(), db_add_open_record(), db_close_database(), db_create_key(), db_create_record(), db_delete_key1(), db_enum_key(), db_enum_link(), db_find_key(), db_find_link(), db_find_open_records(), db_fix_open_records(), db_flush_database(), db_get_data(), db_get_data1(), db_get_data_index(), db_get_key(), db_get_key_info(), db_get_key_time(), db_get_next_link(), db_get_path(), db_get_record(), db_get_record_size(), db_get_value(), db_open_database(), db_remove_open_record(), db_rename_key(), db_reorder_key(), db_set_data(), db_set_data_index(), db_set_data_index2(), db_set_mode(), db_set_num_values(), db_set_record(), db_set_value(), db_show_mem(), and log_system_history().
{
#ifdef LOCAL_ROUTINES
   int status;
   if (hDB > _database_entries || hDB <= 0) {
      cm_msg(MERROR, "db_lock_database", "invalid database handle, aborting...");
      abort();
      return DB_INVALID_HANDLE;
   }
   if (_database[hDB - 1].protect && _database[hDB - 1].database_header != NULL) {
      cm_msg(MERROR, "db_lock_database", "internal error: DB already locked, aborting...");
      abort();
      return DB_NO_MUTEX;
   }
   if (_database[hDB - 1].lock_cnt == 0) {
      /* wait max. 5 minutes for mutex (required if locking process is being debugged) */
      status = ss_mutex_wait_for(_database[hDB - 1].mutex, 5*60*1000);
      if (status == SS_TIMEOUT) {
         cm_msg(MERROR, "db_lock_database", "timeout obtaining lock for database, exiting...");
         exit(1);
         return DB_TIMEOUT;
      }
      if (status != SS_SUCCESS) {
         cm_msg(MERROR, "db_lock_database", "cannot lock database, ss_mutex_wait_for() status %d, aborting...",status);
         abort();
         return DB_NO_MUTEX;
      }
   }
   _database[hDB - 1].lock_cnt++;
   if (_database[hDB - 1].protect) {
      if (_database[hDB - 1].database_header == NULL)
         ss_shm_unprotect(_database[hDB - 1].shm_handle,
                          (void **) &_database[hDB - 1].database_header);
   }
#endif                          /* LOCAL_ROUTINES */
   return DB_SUCCESS;
}
INT EXPRT db_notify_clients (HNDLE hDB, HNDLE hKey, BOOL bWalk)
Definition at line 7099 of file odb.c.
References _database_entries, DATABASE_HEADER::client, cm_msg, DATABASE::database_header, DB_INVALID_HANDLE, DB_SUCCESS, OPEN_RECORD::handle, i, j, DATABASE_HEADER::max_client_index, DATABASE_CLIENT::max_index, MERROR, KEY::notify_count, DATABASE_CLIENT::open_record, KEYLIST::parent, KEY::parent_keylist, DATABASE_CLIENT::port, PTYPE, ss_resume(), and TRUE.
Referenced by db_recurse_record_tree(), db_set_data(), db_set_data_index(), db_set_data_index2(), db_set_num_values(), db_set_record(), db_set_value(), and log_system_history().
         : db_notify_clients
  Purpose: Gets called by db_set_xxx functions. Internal use only.
\********************************************************************/
{
   DATABASE_HEADER *pheader;
   DATABASE_CLIENT *pclient;
   KEY *pkey;
   KEYLIST *pkeylist;
   INT i, j;
   char str[80];
   if (hDB > _database_entries || hDB <= 0) {
      cm_msg(MERROR, "db_notify_clients", "invalid database handle");
      return DB_INVALID_HANDLE;
   }
   pheader = _database[hDB - 1].database_header;
   /* check if key or parent has notify_flag set */
   pkey = (KEY *) ((char *) pheader + hKey);
   do {
      /* check which client has record open */
      if (pkey->notify_count)
         for (i = 0; i < pheader->max_client_index; i++) {
            pclient = &pheader->client[i];
            for (j = 0; j < pclient->max_index; j++)
               if (pclient->open_record[j].handle == hKey) {
                  /* send notification to remote process */
                  sprintf(str, "O %d %d", hDB, hKey);
                  ss_resume(pclient->port, str);
               }
         }
      if (pkey->parent_keylist == 0 || !bWalk)
         return DB_SUCCESS;
      pkeylist = (KEYLIST *) ((char *) pheader + pkey->parent_keylist);
      pkey = (KEY *) ((char *) pheader + pkeylist->parent);
      hKey = (PTYPE) pkey - (PTYPE) pheader;
   } while (TRUE);
}
INT EXPRT db_set_client_name (HNDLE hDB, char * client_name)
Definition at line 1536 of file odb.c.
References DATABASE_HEADER::client, DATABASE::client_index, DATABASE::database_header, DB_SUCCESS, index, DATABASE_CLIENT::name, rpc_call(), RPC_DB_SET_CLIENT_NAME, and rpc_is_remote().
Referenced by cm_set_client_info(), and rpc_server_dispatch().
         : db_set_client_name
  Purpose: Set client name for a database. Used by cm_connect_experiment
           if a client name is duplicate and changed.
  Input:
    INT  hDB                Handle to database
    char *client_name       Name of this application
  Output:
  Function value:
    DB_SUCCESS              Successful completion
    RPC_NET_ERROR           Network error
\********************************************************************/
{
   if (rpc_is_remote())
      return rpc_call(RPC_DB_SET_CLIENT_NAME, hDB, client_name);
#ifdef LOCAL_ROUTINES
   {
      DATABASE_HEADER *pheader;
      DATABASE_CLIENT *pclient;
      INT index;
      index = _database[hDB - 1].client_index;
      pheader = _database[hDB - 1].database_header;
      pclient = &pheader->client[index];
      strcpy(pclient->name, client_name);
   }
#endif                          /* LOCAL_ROUTINES */
   return DB_SUCCESS;
}
INT EXPRT db_show_mem (HNDLE hDB, char * result, INT buf_size, BOOL verbose)
Definition at line 676 of file odb.c.
References DATABASE_HEADER::data_size, DATABASE::database_header, db_lock_database(), db_scan_tree(), DB_SUCCESS, db_unlock_database(), DATABASE_HEADER::first_free_data, DATABASE_HEADER::first_free_key, DATABASE_HEADER::key_size, FREE_DESCRIP::next_free, print_key_info(), PTYPE, DATABASE_HEADER::root_key, and FREE_DESCRIP::size.
Referenced by command_loop().
{
   DATABASE_HEADER *pheader;
   INT total_size_key, total_size_data;
   FREE_DESCRIP *pfree;
   db_lock_database(hDB);
   pheader = _database[hDB - 1].database_header;
   sprintf(result,
           "Database header size is 0x%04X, all following values are offset by this!\nKey area  0x00000000 - 0x%08X\nData area 0x%08X - 0x%08X\n\n",
           (int)sizeof(DATABASE_HEADER), pheader->key_size - 1,
           pheader->key_size, pheader->key_size + pheader->data_size);
   strcat(result, "Keylist:\n");
   strcat(result, "--------\n");
   total_size_key = 0;
   pfree = (FREE_DESCRIP *) ((char *) pheader + pheader->first_free_key);
   while ((PTYPE) pfree != (PTYPE) pheader) {
      total_size_key += pfree->size;
      sprintf(result + strlen(result),
              "Free block at 0x%08X, size 0x%08X, next 0x%08X\n",
              (int)((PTYPE) pfree - (PTYPE) pheader - sizeof(DATABASE_HEADER)),
              pfree->size,
              pfree->next_free ? (int)(pfree->next_free - sizeof(DATABASE_HEADER)) : 0);
      pfree = (FREE_DESCRIP *) ((char *) pheader + pfree->next_free);
   }
   strcat(result, "\nData:\n");
   strcat(result, "-----\n");
   total_size_data = 0;
   pfree = (FREE_DESCRIP *) ((char *) pheader + pheader->first_free_data);
   while ((PTYPE) pfree != (PTYPE) pheader) {
      total_size_data += pfree->size;
      sprintf(result + strlen(result),
              "Free block at 0x%08X, size 0x%08X, next 0x%08X\n",
              (int)((PTYPE) pfree - (PTYPE) pheader - sizeof(DATABASE_HEADER)),
              pfree->size,
              pfree->next_free ? (int)(pfree->next_free - sizeof(DATABASE_HEADER)) : 0);
      pfree = (FREE_DESCRIP *) ((char *) pheader + pfree->next_free);
   }
   sprintf(result + strlen(result),
           "\nTotal size: %1d (0x%08X) keylist, %1d (0x%08X) data\n",
           total_size_key, total_size_key, total_size_data, total_size_data);
   sprintf(result + strlen(result),
           "\nFree: %1d (%1.1lf%%) keylist, %1d (%1.1lf%%) data\n",
           total_size_key,
           100 * (double) total_size_key / pheader->key_size,
           total_size_data, 100 * (double) total_size_data / pheader->data_size);
   if (verbose) {
      sprintf(result + strlen(result), "\n\n");
      sprintf(result + strlen(result), "Key       Data      Size\n");
      sprintf(result + strlen(result), "------------------------\n");
      db_scan_tree(hDB, pheader->root_key, 0, print_key_info, result);
   }
   db_unlock_database(hDB);
   return DB_SUCCESS;
}
INT EXPRT db_unlock_database (HNDLE hDB)
Unlock a database via system mutex calls.
Parameters:
hDB Handle to the database to unlock
Returns:
DB_SUCCESS, DB_INVALID_HANDLE
Definition at line 1635 of file odb.c.
References _database_entries, cm_msg, DATABASE::database_header, DB_INVALID_HANDLE, DB_SUCCESS, DATABASE::lock_cnt, MERROR, protect, ss_mutex_release(), and ss_shm_protect().
Referenced by cm_check_client(), cm_cleanup(), cm_delete_client_info(), cm_get_watchdog_info(), cm_set_client_info(), cm_set_watchdog_params(), cm_watchdog(), db_add_open_record(), db_close_database(), db_create_key(), db_create_record(), db_delete_key1(), db_enum_key(), db_enum_link(), db_find_key(), db_find_key1(), db_find_link(), db_find_link1(), db_find_open_records(), db_fix_open_records(), db_flush_database(), db_get_data(), db_get_data1(), db_get_data_index(), db_get_key(), db_get_key_info(), db_get_key_time(), db_get_next_link(), db_get_path(), db_get_record(), db_get_record_size(), db_get_value(), db_open_database(), db_remove_open_record(), db_rename_key(), db_reorder_key(), db_set_data(), db_set_data_index(), db_set_data_index2(), db_set_mode(), db_set_num_values(), db_set_record(), db_set_value(), db_show_mem(), and log_system_history().
{
#ifdef LOCAL_ROUTINES
   if (hDB > _database_entries || hDB <= 0) {
      cm_msg(MERROR, "db_unlock_database", "invalid database handle");
      return DB_INVALID_HANDLE;
   }
   if (_database[hDB - 1].lock_cnt == 1)
      ss_mutex_release(_database[hDB - 1].mutex);
   if (_database[hDB - 1].lock_cnt > 0)
      _database[hDB - 1].lock_cnt--;
   if (_database[hDB - 1].protect) {
      ss_shm_protect(_database[hDB - 1].shm_handle, _database[hDB - 1].database_header);
      _database[hDB - 1].database_header = NULL;
   }
#endif                          /* LOCAL_ROUTINES */
   return DB_SUCCESS;
}
INT db_update_record (INT hDB, INT hKey, int socket)
If called locally, update a record (hDB/hKey) and copy its new contents to the local copy of it.
If called from a server, send a network notification to the client.
Parameters:
hDB ODB handle obtained via cm_get_experiment_database().
hKey Handle for key where search starts, zero for root.
socket optional server socket
Returns:
DB_SUCCESS, DB_INVALID_HANDLE
Definition at line 7947 of file odb.c.
References _record_list_entries, RECORD_LIST::buf_size, buffer, CF_ASCII, data, db_get_record(), DB_INVALID_HANDLE, DB_SUCCESS, RECORD_LIST::dispatcher, handle, NET_COMMAND::header, i, MODE_WRITE, MSG_ODB, NET_COMMAND::param, NET_COMMAND_HEADER::param_size, NET_COMMAND_HEADER::routine_id, RPC_CONVERT_FLAGS, rpc_convert_single(), rpc_get_server_option(), RPC_OUTGOING, send_tcp(), size, status, and TID_DWORD.
Referenced by cm_dispatch_ipc(), and rpc_client_dispatch().
{
   INT i, size, convert_flags, status;
   char buffer[32];
   NET_COMMAND *nc;
   /* check if we are the server */
   if (socket) {
      convert_flags = rpc_get_server_option(RPC_CONVERT_FLAGS);
      if (convert_flags & CF_ASCII) {
         sprintf(buffer, "MSG_ODB&%d&%d", hDB, hKey);
         send_tcp(socket, buffer, strlen(buffer) + 1, 0);
      } else {
         nc = (NET_COMMAND *) buffer;
         nc->header.routine_id = MSG_ODB;
         nc->header.param_size = 2 * sizeof(INT);
         *((INT *) nc->param) = hDB;
         *((INT *) nc->param + 1) = hKey;
         if (convert_flags) {
            rpc_convert_single(&nc->header.routine_id, TID_DWORD,
                               RPC_OUTGOING, convert_flags);
            rpc_convert_single(&nc->header.param_size, TID_DWORD,
                               RPC_OUTGOING, convert_flags);
            rpc_convert_single(&nc->param[0], TID_DWORD, RPC_OUTGOING, convert_flags);
            rpc_convert_single(&nc->param[4], TID_DWORD, RPC_OUTGOING, convert_flags);
         }
         /* send the update notification to the client */
         send_tcp(socket, buffer, sizeof(NET_COMMAND_HEADER) + 2 * sizeof(INT), 0);
      }
      return DB_SUCCESS;
   }
   status = DB_INVALID_HANDLE;
   /* check all entries for matching key */
   for (i = 0; i < _record_list_entries; i++)
      if (_record_list[i].handle == hKey) {
         status = DB_SUCCESS;
         /* get updated data if record not opened in write mode */
         if ((_record_list[i].access_mode & MODE_WRITE) == 0) {
            size = _record_list[i].buf_size;
            if (_record_list[i].data != NULL)
               db_get_record(hDB, hKey, _record_list[i].data, &size, 0);
            /* call dispatcher if requested */
            if (_record_list[i].dispatcher)
               _record_list[i].dispatcher(hDB, hKey, _record_list[i].info);
         }
      }
   return DB_SUCCESS;
}
INT EXPRT dm_area_flush (void)
Definition at line 17649 of file midas.c.
References DMEM_BUFFER::action, DMEM_BUFFER::area1, DMEM_BUFFER::area2, CM_SUCCESS, dm_buffer_send(), DM_FLUSH, DMEM_BUFFER::last_active, DMEM_BUFFER::sem_flush, DMEM_BUFFER::sem_send, DMEM_AREA::serial, ss_millitime(), ss_mutex_release(), ss_mutex_wait_for(), and status.
Referenced by frontend_loop(), scheduler(), and send_event().
17651          : dm_area_flush
17652
17653   Purpose: Flush all the events in the areas.
17654            Used in mfe for BOR events, periodic events and
17655            if rate to low in main loop once a second. The standard
17656            data transfer should be done/triggered by dm_area_send (sync/async)
17657            in dm_pointer_get().
17658   Input:
17659     none
17660   Output:
17661     none
17662   Function value:
17663     CM_SUCCESS       Successful completion
17664     RPC_NET_ERROR    send error
17665 \********************************************************************/
17666 {
17667    INT status;
17668 #ifdef DM_DUAL_THREAD
17669    /* request FULL flush */
17670    dm.action = DM_FLUSH;
17671    ss_mutex_release(dm.sem_send);
17672 #ifdef OS_WINNT
17673    /* necessary for true MUTEX (NT) get semaphore back */
17674    ss_mutex_wait_for(dm.sem_send, 0);
17675 #endif
17676
17677    /* important to wait for completion before continue with timeout
17678       timeout specified milliseconds */
17679    status = ss_mutex_wait_for(dm.sem_flush, 10000);
17680 #ifdef DM_DEBUG
17681    printf("dm_area_flush after waiting %i\n", status);
17682 #endif
17683 #ifdef OS_WINNT
17684    ss_mutex_release(dm.sem_flush);      /* give it back now */
17685 #endif
17686
17687    return status;
17688 #else
17689    /* full flush done here */
17690    /* select in order both area independently of being full or not */
17691    if (dm.area1.serial <= dm.area2.serial) {
17692       status = dm_buffer_send(&dm.area1);
17693       if (status != CM_SUCCESS)
17694          return status;
17695       status = dm_buffer_send(&dm.area2);
17696       if (status != CM_SUCCESS)
17697          return status;
17698    } else {
17699       status = dm_buffer_send(&dm.area2);
17700       if (status != CM_SUCCESS)
17701          return status;
17702       status = dm_buffer_send(&dm.area1);
17703       if (status != CM_SUCCESS)
17704          return status;
17705    }
17706    /* reset serial counter */
17707    dm.area1.serial = dm.area2.serial = 0;
17708    dm.last_active = ss_millitime();
17709    return CM_SUCCESS;
17710 #endif
17711 }
BOOL EXPRT dm_area_full (void)
Definition at line 17249 of file midas.c.
References DMEM_BUFFER::area1, DMEM_BUFFER::area2, FALSE, DMEM_AREA::full, DMEM_BUFFER::pa, and TRUE.
Referenced by dm_task().
17251          : dm_area_full
17252
17253   Purpose: Test if both area are full in order to block interrupt
17254   Input:
17255     none
17256   Output:
17257     none
17258   Function value:
17259     BOOL         TRUE if not enough space for another event
17260 \********************************************************************/
17261 {
17262    if (dm.pa == NULL || (dm.area1.full && dm.area2.full))
17263       return TRUE;
17264    return FALSE;
17265 }
INT EXPRT dm_area_send (void)
Definition at line 17465 of file midas.c.
References DMEM_BUFFER::action, DMEM_BUFFER::area1, DMEM_BUFFER::area2, CM_SUCCESS, dm_buffer_send(), DM_SEND, DMEM_AREA::full, DMEM_BUFFER::pa, RPC_NET_ERROR, DMEM_BUFFER::sem_send, DMEM_AREA::serial, ss_mutex_release(), ss_mutex_wait_for(), SS_NO_MUTEX, and status.
Referenced by dm_pointer_get().
17467          : dm_area_send
17468
17469   Purpose: Empty the FULL area only in proper event order
17470            Meant to be use either in mfe.c scheduler on every event
17471
17472   Dual memory scheme:
17473    DM_DUAL_THREAD : Trigger sem_send
17474    !DM_DUAL_THREAD: empty full buffer in order, return active to area1
17475                     if dm.pa is NULL (were both full) and now both are empty
17476
17477   Input:
17478     none
17479   Output:
17480     none
17481   Function value:
17482     CM_SUCCESS                Successful completion
17483     RPC_NET_ERROR             send error
17484 \********************************************************************/
17485 {
17486 #ifdef DM_DUAL_THREAD
17487    INT status;
17488
17489    /* force a DM_SEND if possible. Don't wait for completion */
17490    dm.action = DM_SEND;
17491    ss_mutex_release(dm.sem_send);
17492 #ifdef OS_WINNT
17493    /* necessary for true MUTEX (NT) */
17494    status = ss_mutex_wait_for(dm.sem_send, 1);
17495    if (status == SS_NO_MUTEX) {
17496       printf(" timeout while waiting for sem_send\n");
17497       return RPC_NET_ERROR;
17498    }
17499 #endif
17500
17501    return CM_SUCCESS;
17502 #else
17503    /* ---------- NOT IN DUAL THREAD ----------- */
17504    INT status = 0;
17505
17506    /* if no DUAL thread everything is local then */
17507    /* select the full area */
17508    if (dm.area1.full && dm.area2.full)
17509       if (dm.area1.serial <= dm.area2.serial)
17510          status = dm_buffer_send(&dm.area1);
17511       else
17512          status = dm_buffer_send(&dm.area2);
17513    else if (dm.area1.full)
17514       status = dm_buffer_send(&dm.area1);
17515    else if (dm.area2.full)
17516       status = dm_buffer_send(&dm.area2);
17517    if (status != CM_SUCCESS)
17518       return status;            /* catch transfer error too */
17519
17520    if (dm.pa == NULL) {
17521       printf(" sync send dm.pa:%p full 1%li 2%li\n", dm.pa, dm.area1.full, dm.area2.full);
17522       dm.pa = &dm.area1;
17523    }
17524    return CM_SUCCESS;
17525 #endif
17526 }
INT EXPRT dm_async_area_send (void * pointer)
INT EXPRT dm_buffer_create (INT size, INT user_max_event_size)
dox Setup a dual memory buffer. Has to be called initially before any other dm_xxx function
Parameters:
size Size in bytes
user_max_event_size max event size
Returns:
CM_SUCCESS, BM_NO_MEMORY, BM_MEMSIZE_MISMATCH
Definition at line 17079 of file midas.c.
References _send_sock, DMEM_BUFFER::area1, DMEM_BUFFER::area2, BM_MEMSIZE_MISMATCH, BM_NO_MEMORY, cm_msg, CM_SUCCESS, dm_task(), FALSE, DMEM_AREA::full, DMEM_BUFFER::last_active, M_MALLOC, MAX_EVENT_SIZE, MERROR, VX_TASK_SPAWN::name, DMEM_BUFFER::pa, DMEM_AREA::pb, DMEM_AREA::pe, VX_TASK_SPAWN::priority, DMEM_AREA::pt, DMEM_AREA::pw, rpc_get_event_sock(), DMEM_BUFFER::sem_flush, DMEM_BUFFER::sem_send, DMEM_BUFFER::serial, DMEM_AREA::serial, SS_CREATED, ss_millitime(), ss_mutex_create(), ss_mutex_wait_for(), SS_SUCCESS, ss_thread_create(), VX_TASK_SPAWN::stackSize, and status.
Referenced by main().
17080 {
17081
17082    dm.area1.pt = (char *) M_MALLOC(size);
17083    if (dm.area1.pt == NULL)
17084       return (BM_NO_MEMORY);
17085    dm.area2.pt = (char *) M_MALLOC(size);
17086    if (dm.area2.pt == NULL)
17087       return (BM_NO_MEMORY);
17088
17089    /* check user event size against the system MAX_EVENT_SIZE */
17090    if (user_max_event_size > MAX_EVENT_SIZE) {
17091       cm_msg(MERROR, "dm_buffer_create", "user max event size too large");
17092       return BM_MEMSIZE_MISMATCH;
17093    }
17094    dm_user_max_event_size = user_max_event_size;
17095
17096    memset(dm.area1.pt, 0, size);
17097    memset(dm.area2.pt, 0, size);
17098
17099    /* initialize pointers */
17100    dm.area1.pb = dm.area1.pt + size - 1024;
17101    dm.area1.pw = dm.area1.pe = dm.area1.pt;
17102    dm.area2.pb = dm.area2.pt + size - 1024;
17103    dm.area2.pw = dm.area2.pe = dm.area2.pt;
17104
17105   /*-PAA-*/
17106 #ifdef DM_DEBUG
17107    printf(" in dm_buffer_create ---------------------------------\n");
17108    printf(" %i %p %p %p %p\n", size, dm.area1.pt, dm.area1.pw, dm.area1.pe, dm.area1.pb);
17109    printf(" %i %p %p %p %p\n", size, dm.area2.pt, dm.area2.pw, dm.area2.pe, dm.area2.pb);
17110 #endif
17111
17112    /* activate first area */
17113    dm.pa = &dm.area1;
17114
17115    /* Default not full */
17116    dm.area1.full = dm.area2.full = FALSE;
17117
17118    /* Reset serial buffer number with proper starting sequence */
17119    dm.area1.serial = dm.area2.serial = 0;
17120    /* ensure proper serial on next increment */
17121    dm.serial = 1;
17122
17123    /* set active buffer time stamp */
17124    dm.last_active = ss_millitime();
17125
17126    /* get socket for event sending */
17127    _send_sock = rpc_get_event_sock();
17128
17129 #ifdef DM_DUAL_THREAD
17130    {
17131       INT status;
17132       VX_TASK_SPAWN starg;
17133
17134       /* create semaphore */
17135       status = ss_mutex_create("send", &dm.sem_send);
17136       if (status != SS_CREATED && status != SS_SUCCESS) {
17137          cm_msg(MERROR, "dm_buffer_create", "error in ss_mutex_create send");
17138          return status;
17139       }
17140       status = ss_mutex_create("flush", &dm.sem_flush);
17141       if (status != SS_CREATED && status != SS_SUCCESS) {
17142          cm_msg(MERROR, "dm_buffer_create", "error in ss_mutex_create flush");
17143          return status;
17144       }
17145       /* spawn dm_task */
17146       memset(&starg, 0, sizeof(VX_TASK_SPAWN));
17147
17148 #ifdef OS_VXWORKS
17149       /* Fill up the necessary arguments */
17150       strcpy(starg.name, "areaSend");
17151       starg.priority = 120;
17152       starg.stackSize = 20000;
17153 #endif
17154
17155       if ((status = ss_thread_create(dm_task, (void *) &starg))
17156           != SS_SUCCESS) {
17157          cm_msg(MERROR, "dm_buffer_create", "error in ss_thread_create");
17158          return status;
17159       }
17160 #ifdef OS_WINNT
17161       /* necessary for true MUTEX (NT) */
17162       ss_mutex_wait_for(dm.sem_send, 0);
17163 #endif
17164    }
17165 #endif                          /* DM_DUAL_THREAD */
17166
17167    return CM_SUCCESS;
17168 }
INT EXPRT dm_buffer_release (void)
dox
Definition at line 17174 of file midas.c.
References DMEM_BUFFER::action, DMEM_BUFFER::area1, DMEM_BUFFER::area2, CM_SUCCESS, DM_KILL, DMEM_AREA::full, DMEM_AREA::pt, DMEM_BUFFER::sem_flush, DMEM_BUFFER::sem_send, DMEM_AREA::serial, DMEM_BUFFER::serial, ss_mutex_delete(), ss_mutex_release(), and TRUE.
Referenced by main().
17176          : dm_buffer_release
17177
17178   Purpose: Release dual memory buffers
17179   Input:
17180     none
17181   Output:
17182     none
17183   Function value:
17184     CM_SUCCESS              Successful completion
17185 \********************************************************************/
17186 {
17187    if (dm.area1.pt) {
17188       free(dm.area1.pt);
17189       dm.area1.pt = NULL;
17190    }
17191    if (dm.area2.pt) {
17192       free(dm.area2.pt);
17193       dm.area2.pt = NULL;
17194    }
17195    dm.serial = 0;
17196    dm.area1.full = dm.area2.full = TRUE;
17197    dm.area1.serial = dm.area2.serial = 0;
17198
17199 #ifdef DM_DUAL_THREAD
17200    /* kill spawned dm_task */
17201    dm.action = DM_KILL;
17202    ss_mutex_release(dm.sem_send);
17203    ss_mutex_release(dm.sem_flush);
17204
17205    /* release semaphore */
17206    ss_mutex_delete(dm.sem_send, 0);
17207    ss_mutex_delete(dm.sem_flush, 0);
17208 #endif
17209
17210    return CM_SUCCESS;
17211 }
DWORD EXPRT dm_buffer_time_get (void)
Definition at line 17294 of file midas.c.
References DMEM_BUFFER::last_active.
17296          : dm_buffer_time_get
17297
17298   Purpose: return the time from the last buffer switch.
17299
17300   Input:
17301     none
17302   Output:
17303     none
17304   Function value:
17305     DWORD        time stamp
17306
17307 \********************************************************************/
17308 {
17309    return (dm.last_active);
17310 }
EVENT_HEADER EXPRT* dm_pointer_get (void)
Definition at line 17314 of file midas.c.
References DMEM_BUFFER::area1, DMEM_BUFFER::area2, cm_msg, dm_active_full(), dm_area_send(), dm_area_switch(), DMEM_AREA::full, DMEM_BUFFER::last_active, MERROR, DMEM_BUFFER::pa, DMEM_AREA::pw, RPC_NET_ERROR, DMEM_BUFFER::serial, DMEM_AREA::serial, ss_millitime(), ss_sleep(), status, timeout, and TRUE.
Referenced by interrupt_routine(), scheduler(), send_event(), and yb_file_fragment().
17316          : dm_pointer_get
17317
17318   Purpose: Get pointer to next free location in event buffer.
17319            after 10sec tries, it times out return NULL indicating a
17320            serious problem, i.e. abort.
17321   REMARK : Cannot be called twice in a raw due to +sizeof(INT)
17322   Input:
17323     none
17324   Output:
17325     DM_BUFFER * dm    local valid dm to work on
17326   Function value:
17327     EVENT_HEADER *    Pointer to free location
17328     NULL              cannot after several attempt get free space => abort
17329 \********************************************************************/
17330 {
17331    int timeout, status;
17332
17333    /* Is there still space in the active area ? */
17334    if (!dm_active_full())
17335       return (EVENT_HEADER *) (dm.pa->pw + sizeof(INT));
17336
17337    /* no more space => switch area */
17338
17339    /* Tag current area with global dm.serial for order consistency */
17340    dm.pa->serial = dm.serial++;
17341
17342    /* set active buffer time stamp */
17343    dm.last_active = ss_millitime();
17344
17345    /* mark current area full */
17346    dm.pa->full = TRUE;
17347
17348    /* Trigger/do data transfer (Now/don't wait) */
17349    if ((status = dm_area_send()) == RPC_NET_ERROR) {
17350       cm_msg(MERROR, "dm_pointer_get()", "Net error or timeout %i", status);
17351       return NULL;
17352    }
17353
17354    /* wait switch completion (max 10 sec) */
17355    timeout = ss_millitime();    /* with timeout */
17356    while ((ss_millitime() - timeout) < 10000) {
17357       dm.pa = dm_area_switch();
17358       if (dm.pa != NULL)
17359          return (EVENT_HEADER *) (dm.pa->pw + sizeof(INT));
17360       ss_sleep(200);
17361 #ifdef DM_DEBUG
17362       printf(" waiting for space ... %i  dm_buffer  %i %i %i %i %i \n",
17363              ss_millitime() - timeout, dm.area1.full, dm.area2.full, dm.area1.serial,
17364              dm.area2.serial, dm.serial);
17365 #endif
17366    }
17367
17368    /* Time running out abort */
17369    cm_msg(MERROR, "dm_pointer_get", "Timeout due to buffer full");
17370    return NULL;
17371 }
INT EXPRT dm_pointer_increment (INT buffer_handle, INT event_size)
Definition at line 17375 of file midas.c.
References _send_sock, ALIGN8, bm_send_event(), CM_SUCCESS, DMEM_BUFFER::pa, DMEM_AREA::pe, DMEM_AREA::pw, and SYNC.
Referenced by interrupt_routine(), scheduler(), send_event(), and yb_file_fragment().
17377          : dm_pointer_increment
17378
17379   Purpose: Increment write pointer of event buffer after an event
17380            has been copied into the buffer (at an address previously
17381            obtained via dm_pointer_get)
17382   Input:
17383     INT buffer_handle         Buffer handle event should be sent to
17384     INT event_size            Event size in bytes including header
17385   Output:
17386     none
17387   Function value:
17388     CM_SUCCESS                Successful completion
17389     status                    from bm_send_event for local connection
17390 \********************************************************************/
17391 {
17392    INT aligned_event_size;
17393
17394    /* if not connected remotely, use bm_send_event */
17395    if (_send_sock == 0) {
17396       *((INT *) dm.pa->pw) = buffer_handle;
17397       return bm_send_event(buffer_handle, dm.pa->pw + sizeof(INT), event_size, SYNC);
17398    }
17399    aligned_event_size = ALIGN8(event_size);
17400
17401    *((INT *) dm.pa->pw) = buffer_handle;
17402
17403    /* adjust write pointer */
17404    dm.pa->pw += sizeof(INT) + aligned_event_size;
17405
17406    /* adjust end pointer */
17407    dm.pa->pe = dm.pa->pw;
17408
17409    return CM_SUCCESS;
17410 }
INT EXPRT dm_task (void * pointer)
Definition at line 17529 of file midas.c.
References DMEM_BUFFER::action, DMEM_BUFFER::area1, DMEM_BUFFER::area2, cm_msg, CM_SUCCESS, dm_area_full(), dm_buffer_send(), DM_FLUSH, DM_KILL, DM_SEND, DMEM_AREA::full, MERROR, DMEM_BUFFER::pa, DMEM_BUFFER::sem_flush, DMEM_BUFFER::sem_send, DMEM_BUFFER::serial, DMEM_AREA::serial, ss_millitime(), ss_mutex_release(), ss_mutex_wait_for(), ss_sleep(), status, and timeout.
Referenced by dm_buffer_create().
17531          : dm_task
17532
17533   Purpose: async send events doing a double purpose:
17534   a) send full buffer if found (DM_SEND) set by dm_active_full
17535   b) flush full areas (DM_FLUSH) set by dm_area_flush
17536   Input:
17537   none
17538   Output:
17539   none
17540   Function value:
17541   none
17542   \********************************************************************/
17543 {
17544 #ifdef DM_DUAL_THREAD
17545    INT status, timeout;
17546
17547    printf("Semaphores initialization ... in areaSend ");
17548    /* Check or Wait for semaphore to be setup */
17549    timeout = ss_millitime();
17550    while ((ss_millitime() - timeout < 3000) && (dm.sem_send == 0))
17551       ss_sleep(200);
17552    if (dm.sem_send == 0)
17553       goto kill;
17554
17555 #ifdef OS_WINNT
17556    /* necessary for true MUTEX (NT) get semaphore */
17557    ss_mutex_wait_for(dm.sem_flush, 0);
17558 #endif
17559
17560    /* Main FOREVER LOOP */
17561    printf("task areaSend ready...\n");
17562    while (1) {
17563       if (!dm_area_full()) {
17564          /* wait semaphore here ........ 0 == forever */
17565          ss_mutex_wait_for(dm.sem_send, 0);
17566 #ifdef OS_WINNT
17567          /* necessary for true MUTEX (NT) give semaphore */
17568          ss_mutex_release(dm.sem_send);
17569 #endif
17570       }
17571       if (dm.action == DM_SEND) {
17572 #ifdef DM_DEBUG
17573          printf("Send %i %i ", dm.area1.full, dm.area2.full);
17574 #endif
17575          /* DM_SEND : Empty the oldest buffer only. */
17576          if (dm.area1.full && dm.area2.full) {
17577             if (dm.area1.serial <= dm.area2.serial)
17578                status = dm_buffer_send(&dm.area1);
17579             else
17580                status = dm_buffer_send(&dm.area2);
17581          } else if (dm.area1.full)
17582             status = dm_buffer_send(&dm.area1);
17583          else if (dm.area2.full)
17584             status = dm_buffer_send(&dm.area2);
17585
17586          if (status != CM_SUCCESS) {
17587             cm_msg(MERROR, "dm_task", "network error %i", status);
17588             goto kill;
17589          }
17590       } /* if DM_SEND */
17591       else if (dm.action == DM_FLUSH) {
17592          /* DM_FLUSH: User is waiting for completion (i.e. No more incomming
17593             events) Empty both area in order independently of being full or not */
17594          if (dm.area1.serial <= dm.area2.serial) {
17595             status = dm_buffer_send(&dm.area1);
17596             if (status != CM_SUCCESS)
17597                goto error;
17598             status = dm_buffer_send(&dm.area2);
17599             if (status != CM_SUCCESS)
17600                goto error;
17601          } else {
17602             status = dm_buffer_send(&dm.area2);
17603             if (status != CM_SUCCESS)
17604                goto error;
17605             status = dm_buffer_send(&dm.area1);
17606             if (status != CM_SUCCESS)
17607                goto error;
17608          }
17609          /* reset counter */
17610          dm.area1.serial = 0;
17611          dm.area2.serial = dm.serial = 1;
17612 #ifdef DM_DEBUG
17613          printf("dm.action: Flushing ...\n");
17614 #endif
17615          /* reset area to #1 */
17616          dm.pa = &dm.area1;
17617
17618          /* release user */
17619          ss_mutex_release(dm.sem_flush);
17620 #ifdef OS_WINNT
17621          /* necessary for true MUTEX (NT) get semaphore back */
17622          ss_mutex_wait_for(dm.sem_flush, 0);
17623 #endif
17624       }
17625       /* if FLUSH */
17626       if (dm.action == DM_KILL)
17627          goto kill;
17628
17629    }                            /* FOREVER (go back wainting for semaphore) */
17630
17631    /* kill spawn now */
17632  error:
17633    cm_msg(MERROR, "dm_area_flush", "aSync Net error");
17634  kill:
17635    ss_mutex_release(dm.sem_flush);
17636 #ifdef OS_WINNT
17637    ss_mutex_wait_for(dm.sem_flush, 1);
17638 #endif
17639    cm_msg(MERROR, "areaSend", "task areaSend exiting now");
17640    exit;
17641    return 1;
17642 #else
17643    printf("DM_DUAL_THREAD not defined\n");
17644    return 0;
17645 #endif
17646 }
BOOL EXPRT eb_buffer_empty (void)
BOOL EXPRT eb_buffer_full (void)
Definition at line 16781 of file midas.c.
References eb_free_space(), and MAX_EVENT_SIZE.
Referenced by eb_get_pointer().
16784          : eb_buffer_full
16785
16786   Purpose: Test if there is sufficient space in the event buffer
16787     for another event
16788
16789   Input:
16790     none
16791
16792   Output:
16793     none
16794
16795   Function value:
16796     BOOL  Is there enough space for another event in the event buffer
16797
16798 \********************************************************************/
16799 {
16800    INT free;
16801
16802    free = eb_free_space();
16803
16804    /* if max. event won't fit, return zero */
16805    return (free < MAX_EVENT_SIZE + sizeof(EVENT_HEADER) + sizeof(INT));
16806 }
INT EXPRT eb_create_buffer (INT size)
Definition at line 16648 of file midas.c.
References _send_sock, BM_NO_MEMORY, CM_SUCCESS, M_MALLOC, and rpc_get_event_sock().
16651          : eb_create_buffer
16652
16653   Purpose: Create an event buffer. Has to be called initially before
16654            any other eb_xxx function
16655
16656   Input:
16657     INT    size             Size in bytes
16658
16659   Output:
16660     none
16661
16662   Function value:
16663     CM_SUCCESS              Successful completion
16664     BM_NO_MEMEORY           Out of memory
16665
16666 \********************************************************************/
16667 {
16668    _event_ring_buffer = (char *) M_MALLOC(size);
16669    if (_event_ring_buffer == NULL)
16670       return BM_NO_MEMORY;
16671
16672    memset(_event_ring_buffer, 0, size);
16673    _eb_size = size;
16674
16675    _eb_write_pointer = _eb_read_pointer = _eb_end_pointer = _event_ring_buffer;
16676
16677    _send_sock = rpc_get_event_sock();
16678
16679    return CM_SUCCESS;
16680 }
INT EXPRT eb_free_buffer (void)
Definition at line 16683 of file midas.c.
References CM_SUCCESS, and M_FREE.
16686          : eb_free_buffer
16687
16688   Purpose: Free memory allocated voa eb_create_buffer
16689
16690   Input:
16691     none
16692
16693   Output:
16694     none
16695
16696   Function value:
16697     CM_SUCCESS              Successful completion
16698
16699 \********************************************************************/
16700 {
16701    if (_event_ring_buffer)
16702       M_FREE(_event_ring_buffer);
16703
16704    _eb_size = 0;
16705    return CM_SUCCESS;
16706 }
EVENT_HEADER EXPRT* eb_get_pointer (void)
Definition at line 16810 of file midas.c.
References eb_buffer_full().
16813          : eb_get_pointer
16814
16815   Purpose: Get pointer to next free location in event buffer
16816
16817   Input:
16818     none
16819
16820   Output:
16821     none
16822
16823   Function value:
16824     EVENT_HEADER *            Pointer to free location
16825
16826 \********************************************************************/
16827 {
16828    /* if max. event won't fit, return zero */
16829    if (eb_buffer_full()) {
16830 #ifdef OS_VXWORKS
16831       logMsg("eb_get_pointer(): Event won't fit: read=%d, write=%d, end=%d\n",
16832              _eb_read_pointer - _event_ring_buffer,
16833              _eb_write_pointer - _event_ring_buffer,
16834              _eb_end_pointer - _event_ring_buffer, 0, 0, 0);
16835 #endif
16836       return NULL;
16837    }
16838
16839    /* leave space for buffer handle */
16840    return (EVENT_HEADER *) (_eb_write_pointer + sizeof(INT));
16841 }
INT EXPRT eb_increment_pointer (INT buffer_handle, INT event_size)
Definition at line 16845 of file midas.c.
References _send_sock, ALIGN8, bm_send_event(), cm_msg, CM_SUCCESS, MAX_EVENT_SIZE, MERROR, PTYPE, and SYNC.
16848          : eb_increment_pointer
16849
16850   Purpose: Increment write pointer of event buffer after an event
16851            has been copied into the buffer (at an address previously
16852            obtained via eb_get_pointer)
16853
16854   Input:
16855     INT buffer_handle         Buffer handle event should be sent to
16856     INT event_size            Event size in bytes including header
16857
16858   Output:
16859     none
16860
16861   Function value:
16862     CM_SUCCESS                Successful completion
16863
16864 \********************************************************************/
16865 {
16866    INT aligned_event_size;
16867
16868    /* if not connected remotely, use bm_send_event */
16869    if (_send_sock == 0)
16870       return bm_send_event(buffer_handle,
16871                            _eb_write_pointer + sizeof(INT), event_size, SYNC);
16872
16873    aligned_event_size = ALIGN8(event_size);
16874
16875    /* copy buffer handle */
16876    *((INT *) _eb_write_pointer) = buffer_handle;
16877    _eb_write_pointer += sizeof(INT) + aligned_event_size;
16878
16879    if (_eb_write_pointer > _eb_end_pointer)
16880       _eb_end_pointer = _eb_write_pointer;
16881
16882    if (_eb_write_pointer > _event_ring_buffer + _eb_size)
16883       cm_msg(MERROR, "eb_increment_pointer",
16884              "event size (%d) exeeds maximum event size (%d)", event_size,
16885              MAX_EVENT_SIZE);
16886
16887    if (_eb_size - ((PTYPE) _eb_write_pointer - (PTYPE) _event_ring_buffer) <
16888        MAX_EVENT_SIZE + sizeof(EVENT_HEADER) + sizeof(INT)) {
16889       _eb_write_pointer = _event_ring_buffer;
16890
16891       /* avoid rp==wp */
16892       if (_eb_read_pointer == _event_ring_buffer)
16893          _eb_write_pointer--;
16894    }
16895
16896    return CM_SUCCESS;
16897 }
INT EXPRT eb_send_events (BOOL send_all)
Definition at line 16901 of file midas.c.
References _send_sock, BM_MORE_EVENTS, cm_msg, CM_SUCCESS, i, MERROR, PTYPE, RPC_NET_ERROR, send_tcp(), and size.
16904          : eb_send_events
16905
16906   Purpose: Send events from the event buffer to the server
16907
16908   Input:
16909     BOOL send_all             If FALSE, only send events if buffer
16910                               contains more than _opt_tcp_size bytes
16911
16912   Output:
16913     none
16914
16915   Function value:
16916     CM_SUCCESS                Successful completion
16917
16918 \********************************************************************/
16919 {
16920    char *eb_wp, *eb_ep;
16921    INT size, i;
16922
16923    /* write pointers are volatile, so make copy */
16924    eb_ep = _eb_end_pointer;
16925    eb_wp = _eb_write_pointer;
16926
16927    if (eb_wp == _eb_read_pointer)
16928       return CM_SUCCESS;
16929    if (eb_wp > _eb_read_pointer) {
16930       size = (PTYPE) eb_wp - (PTYPE) _eb_read_pointer;
16931
16932       /* don't send if less than optimal TCP buffer size available */
16933       if (size < (INT) _opt_tcp_size && !send_all)
16934          return CM_SUCCESS;
16935    } else {
16936       /* send last piece of event buffer */
16937       size = (PTYPE) eb_ep - (PTYPE) _eb_read_pointer;
16938    }
16939
16940    while (size > _opt_tcp_size) {
16941       /* send buffer */
16942       i = send_tcp(_send_sock, _eb_read_pointer, _opt_tcp_size, 0);
16943       if (i < 0) {
16944          printf("send_tcp() returned %d\n", i);
16945          cm_msg(MERROR, "eb_send_events", "send_tcp() failed");
16946          return RPC_NET_ERROR;
16947       }
16948
16949       _eb_read_pointer += _opt_tcp_size;
16950       if (_eb_read_pointer == eb_ep && eb_wp < eb_ep)
16951          _eb_read_pointer = _eb_end_pointer = _event_ring_buffer;
16952
16953       size -= _opt_tcp_size;
16954    }
16955
16956    if (send_all || eb_wp < _eb_read_pointer) {
16957       /* send buffer */
16958       i = send_tcp(_send_sock, _eb_read_pointer, size, 0);
16959       if (i < 0) {
16960          printf("send_tcp() returned %d\n", i);
16961          cm_msg(MERROR, "eb_send_events", "send_tcp() failed");
16962          return RPC_NET_ERROR;
16963       }
16964
16965       _eb_read_pointer += size;
16966       if (_eb_read_pointer == eb_ep && eb_wp < eb_ep)
16967          _eb_read_pointer = _eb_end_pointer = _event_ring_buffer;
16968    }
16969
16970    /* Check for case where eb_wp = eb_ring_buffer - 1 */
16971    if (eb_wp < _event_ring_buffer && _eb_end_pointer == _event_ring_buffer) {
16972       return CM_SUCCESS;
16973    }
16974
16975    if (eb_wp != _eb_read_pointer)
16976       return BM_MORE_EVENTS;
16977
16978    return CM_SUCCESS;
16979 }
void EXPRT name2c (char * str)
dox
Definition at line 5750 of file odb.c.
Referenced by create_experim_h(), db_save_string(), db_save_struct(), and db_save_tree_struct().
         : name2c
  Purpose: Convert key name to C name. Internal use only.
\********************************************************************/
{
   if (*str >= '0' && *str <= '9')
      *str = '_';
   while (*str) {
      if (!(*str >= 'a' && *str <= 'z') &&
          !(*str >= 'A' && *str <= 'Z') && !(*str >= '0' && *str <= '9'))
         *str = '_';
      *str = (char) tolower(*str);
      str++;
   }
}
INT recv_event_check (int sock)
Definition at line 10835 of file midas.c.
References RPC_SERVER_ACCEPTION::ev_read_ptr, RPC_SERVER_ACCEPTION::ev_write_ptr, index, and MAX_RPC_CONNECTION.
Referenced by ss_suspend().
10838          : recv_event_check
10839
10840   Purpose: Check if in TCP event receive buffer associated with sock
10841            is some data. Called by ss_suspend.
10842
10843   Input:
10844     INT   sock               TCP receive socket
10845
10846   Output:
10847     none
10848
10849   Function value:
10850     INT   count              Number of bytes remaining in TCP buffer
10851
10852 \********************************************************************/
10853 {
10854    INT index;
10855
10856    /* figure out to which connection socket belongs */
10857    for (index = 0; index < MAX_RPC_CONNECTION; index++)
10858       if (_server_acception[index].event_sock == sock)
10859          break;
10860
10861    return _server_acception[index].ev_write_ptr - _server_acception[index].ev_read_ptr;
10862 }
INT EXPRT recv_string (int sock, char * buffer, DWORD buffer_size, INT flags)
Definition at line 3660 of file system.c.
References FD_SETSIZE, n, status, and WATCHDOG_INTERVAL.
Referenced by bb_psi_get(), bb_psi_set(), bl_psi_init(), bl_psi_rall(), bl_psi_set(), cm_list_experiments(), rpc_client_accept(), rpc_client_connect(), rpc_server_accept(), rpc_server_callback(), rpc_server_connect(), rpc_server_receive(), and sendmail().
         : recv_string
  Purpose: Receive network data over TCP port. Since sockets are
     operated in stream mode, a single transmission via send
     may not transfer the full data. Therefore, one has to check
     at the receiver side if the full data is received. If not,
     one has to issue several recv() commands.
     The length of the data is determined by a trailing zero.
  Input:
    INT   sock               Socket which was previosly opened.
    DWORD buffer_size        Size of the buffer in bytes.
    INT   millisec           Timeout in ms
  Output:
    char  *buffer            Network receive buffer.
  Function value:
    INT                      String length
\********************************************************************/
{
   INT i, status;
   DWORD n;
   fd_set readfds;
   struct timeval timeout;
   n = 0;
   memset(buffer, 0, buffer_size);
   do {
      if (millisec > 0) {
         FD_ZERO(&readfds);
         FD_SET(sock, &readfds);
         timeout.tv_sec = millisec / 1000;
         timeout.tv_usec = (millisec % 1000) * 1000;
         do {
            status = select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
            /* if an alarm signal was cought, restart select with reduced timeout */
            if (status == -1 && timeout.tv_sec >= WATCHDOG_INTERVAL / 1000)
               timeout.tv_sec -= WATCHDOG_INTERVAL / 1000;
         } while (status == -1);        /* dont return if an alarm signal was cought */
         if (!FD_ISSET(sock, &readfds))
            break;
      }
      i = recv(sock, buffer + n, 1, 0);
      if (i <= 0)
         break;
      n++;
      if (n >= buffer_size)
         break;
   } while (buffer[n - 1] && buffer[n - 1] != 10);
   return n - 1;
}
INT EXPRT recv_tcp (int sock, char * buffer, DWORD buffer_size, INT flags)
Definition at line 3731 of file system.c.
References cm_msg, NET_COMMAND::header, MERROR, n, and NET_COMMAND_HEADER::param_size.
Referenced by rpc_call(), rpc_check_channels(), rpc_client_call(), rpc_client_dispatch(), and ss_suspend().
         : recv_tcp
  Purpose: Receive network data over TCP port. Since sockets are
     operated in stream mode, a single transmission via send
     may not transfer the full data. Therefore, one has to check
     at the receiver side if the full data is received. If not,
     one has to issue several recv() commands.
     The length of the data is determined by the data header,
     which consists of two DWORDs. The first is the command code
     (or function id), the second is the size of the following
     parameters in bytes. From that size recv_tcp() determines
     how much data to receive.
  Input:
    INT   sock               Socket which was previosly opened.
    char  *net_buffer        Buffer to store data to
    DWORD buffer_size        Size of the buffer in bytes.
    INT   flags              Flags passed to recv()
  Output:
    char  *buffer            Network receive buffer.
  Function value:
    INT                      Same as recv()
\********************************************************************/
{
   INT param_size, n_received, n;
   NET_COMMAND *nc;
   if (buffer_size < sizeof(NET_COMMAND_HEADER)) {
      cm_msg(MERROR, "recv_tcp", "parameters too large for network buffer");
      return -1;
   }
   /* first receive header */
   n_received = 0;
   do {
#ifdef OS_UNIX
      do {
         n = recv(sock, net_buffer + n_received, sizeof(NET_COMMAND_HEADER), flags);
         /* don't return if an alarm signal was cought */
      } while (n == -1 && errno == EINTR);
#else
      n = recv(sock, net_buffer + n_received, sizeof(NET_COMMAND_HEADER), flags);
#endif
      if (n <= 0) {
         cm_msg(MERROR, "recv_tcp",
                "header: recv returned %d, n_received = %d, errno: %d (%s)",
                n, n_received, errno, strerror(errno));
         return n;
      }
      n_received += n;
   } while (n_received < sizeof(NET_COMMAND_HEADER));
   /* now receive parameters */
   nc = (NET_COMMAND *) net_buffer;
   param_size = nc->header.param_size;
   n_received = 0;
   if (param_size == 0)
      return sizeof(NET_COMMAND_HEADER);
   do {
#ifdef OS_UNIX
      do {
         n = recv(sock,
                  net_buffer + sizeof(NET_COMMAND_HEADER) + n_received,
                  param_size - n_received, flags);
         /* don't return if an alarm signal was cought */
      } while (n == -1 && errno == EINTR);
#else
      n = recv(sock, net_buffer + sizeof(NET_COMMAND_HEADER) + n_received,
               param_size - n_received, flags);
#endif
      if (n <= 0) {
         cm_msg(MERROR, "recv_tcp",
                "param: recv returned %d, n_received = %d, errno: %d (%s)",
                n, n_received, errno, strerror(errno));
         return n;
      }
      n_received += n;
   } while (n_received < param_size);
   return sizeof(NET_COMMAND_HEADER) + param_size;
}
INT recv_tcp_check (int sock)
Definition at line 10624 of file midas.c.
References index, MAX_RPC_CONNECTION, RPC_SERVER_ACCEPTION::read_ptr, and RPC_SERVER_ACCEPTION::write_ptr.
Referenced by ss_suspend().
10627          : recv_tcp_check
10628
10629   Purpose: Check if in TCP receive buffer associated with sock is
10630            some data. Called by ss_suspend.
10631
10632   Input:
10633     INT   sock               TCP receive socket
10634
10635   Output:
10636     none
10637
10638   Function value:
10639     INT   count              Number of bytes remaining in TCP buffer
10640
10641 \********************************************************************/
10642 {
10643    INT index;
10644
10645    /* figure out to which connection socket belongs */
10646    for (index = 0; index < MAX_RPC_CONNECTION; index++)
10647       if (_server_acception[index].recv_sock == sock)
10648          break;
10649
10650    return _server_acception[index].write_ptr - _server_acception[index].read_ptr;
10651 }
INT recv_udp (int sock, char * buffer, DWORD buffer_size, INT flags)
Definition at line 3958 of file system.c.
References data_size, FD_SETSIZE, NET_UDP_SIZE, serial_number, status, and UDP_FIRST.
         : recv_udp
  Purpose: Receive network data over UDP port. If received event
     is splitted into several buffers, recombine them checking
     the serial number. If one buffer is missing in a splitted
     event, throw away the whole event.
  Input:
    INT   sock               Socket which was previosly opened.
    DWORD buffer_size        Size of the buffer in bytes.
    INT   flags              Flags passed to recv()
  Output:
    char  *buffer            Network receive buffer.
  Function value:
    INT                     Same as recv()
\********************************************************************/
{
   INT i, status;
   UDP_HEADER *udp_header;
   char udp_buffer[NET_UDP_SIZE];
   DWORD serial_number, sequence_number, total_buffer_size;
   DWORD data_size, n_received;
   fd_set readfds;
   struct timeval timeout;
   udp_header = (UDP_HEADER *) udp_buffer;
   data_size = NET_UDP_SIZE - sizeof(UDP_HEADER);
   /* Receive the first buffer */
#ifdef OS_UNIX
   do {
      i = recv(sock, udp_buffer, NET_UDP_SIZE, flags);
      /* dont return if an alarm signal was cought */
   } while (i == -1 && errno == EINTR);
#else
   i = recv(sock, udp_buffer, NET_UDP_SIZE, flags);
#endif
 start:
   /* Receive buffers until we get a sequence start */
   while (!(udp_header->serial_number & UDP_FIRST)) {
      /* wait for data with timeout */
      FD_ZERO(&readfds);
      FD_SET(sock, &readfds);
      timeout.tv_sec = 0;
      timeout.tv_usec = 100000; /* 0.1 s */
      do {
         status = select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
      } while (status == -1);
      /*
         If we got nothing, return zero so that calling program can do
         other things like checking TCP port for example.
       */
      if (!FD_ISSET(sock, &readfds))
         return 0;
#ifdef OS_UNIX
      do {
         i = recv(sock, udp_buffer, NET_UDP_SIZE, flags);
         /* dont return if an alarm signal was caught */
      } while (i == -1 && errno == EINTR);
#else
      i = recv(sock, udp_buffer, NET_UDP_SIZE, flags);
#endif
   }
   /* if no others are following, return */
   total_buffer_size = udp_header->serial_number & ~UDP_FIRST;
   serial_number = udp_header->sequence_number;
   sequence_number = 0;
   if (total_buffer_size <= data_size) {
      if (buffer_size < total_buffer_size) {
         memcpy(buffer, udp_header + 1, buffer_size);
         return buffer_size;
      } else {
         memcpy(buffer, udp_header + 1, total_buffer_size);
         return total_buffer_size;
      }
   }
   /* if others are following, collect them */
   n_received = data_size;
   if (buffer_size < data_size) {
      memcpy(buffer, udp_header + 1, buffer_size);
      return buffer_size;
   }
   memcpy(buffer, udp_header + 1, data_size);
   do {
      /* wait for new data with timeout */
      FD_ZERO(&readfds);
      FD_SET(sock, &readfds);
      timeout.tv_sec = 0;
      timeout.tv_usec = 100000; /* 0.1 s */
      do {
         status = select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
      } while (status == -1);
      /*
         If we got nothing, return zero so that calling program can do
         other things like checking TCP port for example.
       */
      if (!FD_ISSET(sock, &readfds))
         return 0;
#ifdef OS_UNIX
      do {
         i = recv(sock, udp_buffer, NET_UDP_SIZE, flags);
         /* dont return if an alarm signal was caught */
      } while (i == -1 && errno == EINTR);
#else
      i = recv(sock, udp_buffer, NET_UDP_SIZE, flags);
#endif
      sequence_number++;
      /* check sequence and serial numbers */
      if (udp_header->serial_number != serial_number ||
          udp_header->sequence_number != sequence_number)
         /* lost one, so start again */
         goto start;
      /* copy what we got */
      memcpy(buffer + n_received, udp_header + 1, i - sizeof(UDP_HEADER));
      n_received += (i - sizeof(UDP_HEADER));
   } while (n_received < total_buffer_size);
   return n_received;
}
INT rpc_check_channels (void)
Definition at line 12486 of file midas.c.
References closesocket, cm_disconnect_experiment(), cm_msg, FD_SETSIZE, NET_COMMAND::header, i, index, M_FREE, MAX_RPC_CONNECTION, MINFO, MSG_WATCHDOG, RPC_SERVER_ACCEPTION::net_buffer, net_buffer, NET_COMMAND_HEADER::param_size, recv_tcp(), NET_COMMAND_HEADER::routine_id, RPC_CONVERT_FLAGS, rpc_convert_single(), rpc_get_server_option(), RPC_NET_ERROR, RPC_OSERVER_TYPE, RPC_OUTGOING, RPC_SUCCESS, send_tcp(), ss_gettid(), ss_millitime(), ST_REMOTE, status, TID_DWORD, WATCHDOG_INTERVAL, and RPC_SERVER_ACCEPTION::watchdog_timeout.
Referenced by rpc_server_thread().
12489          : rpc_check_channels
12490
12491   Purpose: Check open rpc channels by sending watchdog messages
12492
12493   Input:
12494     none
12495
12496   Output:
12497     none
12498
12499   Function value:
12500     RPC_SUCCESS             Channel is still alive
12501     RPC_NET_ERROR           Connection is broken
12502
12503 \********************************************************************/
12504 {
12505    INT status, index, i, convert_flags;
12506    NET_COMMAND nc;
12507    fd_set readfds;
12508    struct timeval timeout;
12509
12510    for (index = 0; index < MAX_RPC_CONNECTION; index++) {
12511       if (_server_acception[index].recv_sock &&
12512           _server_acception[index].tid == ss_gettid() &&
12513           _server_acception[index].watchdog_timeout &&
12514           (ss_millitime() - _server_acception[index].last_activity >
12515            (DWORD) _server_acception[index].watchdog_timeout)) {
12516 /* printf("Send watchdog message to %s on %s\n",
12517                 _server_acception[index].prog_name,
12518                 _server_acception[index].host_name); */
12519
12520          /* send a watchdog message */
12521          nc.header.routine_id = MSG_WATCHDOG;
12522          nc.header.param_size = 0;
12523
12524          convert_flags = rpc_get_server_option(RPC_CONVERT_FLAGS);
12525          if (convert_flags) {
12526             rpc_convert_single(&nc.header.routine_id, TID_DWORD, RPC_OUTGOING,
12527                                convert_flags);
12528             rpc_convert_single(&nc.header.param_size, TID_DWORD, RPC_OUTGOING,
12529                                convert_flags);
12530          }
12531
12532          /* send the header to the client */
12533          i = send_tcp(_server_acception[index].send_sock,
12534                       (char *) &nc, sizeof(NET_COMMAND_HEADER), 0);
12535
12536          if (i < 0)
12537             goto exit;
12538
12539          /* make some timeout checking */
12540          FD_ZERO(&readfds);
12541          FD_SET(_server_acception[index].send_sock, &readfds);
12542          FD_SET(_server_acception[index].recv_sock, &readfds);
12543
12544          timeout.tv_sec = _server_acception[index].watchdog_timeout / 1000;
12545          timeout.tv_usec = (_server_acception[index].watchdog_timeout % 1000) * 1000;
12546
12547          do {
12548             status = select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
12549
12550             /* if an alarm signal was cought, restart select with reduced timeout */
12551             if (status == -1 && timeout.tv_sec >= WATCHDOG_INTERVAL / 1000)
12552                timeout.tv_sec -= WATCHDOG_INTERVAL / 1000;
12553
12554          } while (status == -1);        /* dont return if an alarm signal was cought */
12555
12556          if (!FD_ISSET(_server_acception[index].send_sock, &readfds) &&
12557              !FD_ISSET(_server_acception[index].recv_sock, &readfds))
12558             goto exit;
12559
12560          /* receive result on send socket */
12561          if (FD_ISSET(_server_acception[index].send_sock, &readfds)) {
12562             i = recv_tcp(_server_acception[index].send_sock, (char *) &nc, sizeof(nc), 0);
12563             if (i <= 0)
12564                goto exit;
12565          }
12566       }
12567    }
12568
12569    return RPC_SUCCESS;
12570
12571  exit:
12572
12573    cm_msg(MINFO, "rpc_check_channels", "client [%s]%s failed watchdog test after %d sec",
12574           _server_acception[index].host_name,
12575           _server_acception[index].prog_name,
12576           _server_acception[index].watchdog_timeout / 1000);
12577
12578    /* disconnect from experiment */
12579    if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE)
12580       cm_disconnect_experiment();
12581
12582    /* close server connection */
12583    if (_server_acception[index].recv_sock)
12584       closesocket(_server_acception[index].recv_sock);
12585    if (_server_acception[index].send_sock)
12586       closesocket(_server_acception[index].send_sock);
12587    if (_server_acception[index].event_sock)
12588       closesocket(_server_acception[index].event_sock);
12589
12590    /* free TCP cache */
12591    M_FREE(_server_acception[index].net_buffer);
12592    _server_acception[index].net_buffer = NULL;
12593
12594    /* mark this entry as invalid */
12595    memset(&_server_acception[index], 0, sizeof(RPC_SERVER_ACCEPTION));
12596
12597    return RPC_NET_ERROR;
12598 }
INT rpc_client_accept (int sock)
Definition at line 11860 of file midas.c.
References CH_SERVER, closesocket, cm_get_version(), RPC_SERVER_ACCEPTION::event_sock, HOST_NAME_LENGTH, i, index, RPC_SERVER_ACCEPTION::last_activity, MAX_RPC_CONNECTION, NAME_LENGTH, net_buffer, p, RPC_SERVER_ACCEPTION::recv_sock, recv_string(), RPC_SERVER_ACCEPTION::remote_hw_type, rpc_calc_convert_flags(), RPC_CONVERT_FLAGS, rpc_get_option(), RPC_NET_ERROR, RPC_OHW_TYPE, rpc_server_receive(), rpc_set_server_acception(), rpc_set_server_option(), RPC_SUCCESS, send(), RPC_SERVER_ACCEPTION::send_sock, size, ss_gettid(), ss_millitime(), ss_suspend_set_dispatch(), status, RPC_SERVER_ACCEPTION::tid, and RPC_SERVER_ACCEPTION::watchdog_timeout.
Referenced by rpc_register_server().
11863          : rpc_client_accept
11864
11865   Purpose: Accept new incoming connections as a client
11866
11867   Input:
11868     INT    lsock            Listen socket
11869
11870   Output:
11871     none
11872
11873   Function value:
11874     RPC_SUCCESS             Successful completion
11875     RPC_NET_ERROR           Error in socket call
11876     RPC_CONNCLOSED          Connection was closed
11877     RPC_SHUTDOWN            Listener shutdown
11878     RPC_EXCEED_BUFFER       Not enough memory for network buffer
11879
11880 \********************************************************************/
11881 {
11882    INT index, i, version, status;
11883    int size, sock;
11884    struct sockaddr_in acc_addr;
11885    INT client_hw_type = 0, hw_type;
11886    char str[100], client_program[NAME_LENGTH];
11887    char host_name[HOST_NAME_LENGTH];
11888    INT convert_flags;
11889    char net_buffer[256], *p;
11890
11891    size = sizeof(acc_addr);
11892    sock = accept(lsock, (struct sockaddr *) &acc_addr, (int *) &size);
11893
11894    if (sock == -1)
11895       return RPC_NET_ERROR;
11896
11897    /* get the name of the calling host */
11898 /* outcommented for speed reasons SR 7.10.98
11899 #ifdef OS_VXWORKS
11900   {
11901   status = hostGetByAddr(acc_addr.sin_addr.s_addr, host_name);
11902   if (status != 0)
11903     strcpy(host_name, "unknown");
11904   }
11905 #else
11906   phe = gethostbyaddr((char *) &acc_addr.sin_addr, 4, PF_INET);
11907   if (phe == NULL)
11908     strcpy(host_name, "unknown");
11909   strcpy(host_name, phe->h_name);
11910 #endif
11911 */
11912    strcpy(host_name, "");
11913
11914    /* look for next free entry */
11915    for (index = 0; index < MAX_RPC_CONNECTION; index++)
11916       if (_server_acception[index].recv_sock == 0)
11917          break;
11918    if (index == MAX_RPC_CONNECTION) {
11919       closesocket(sock);
11920       return RPC_NET_ERROR;
11921    }
11922
11923    /* receive string with timeout */
11924    i = recv_string(sock, net_buffer, sizeof(net_buffer), 10000);
11925    if (i <= 0) {
11926       closesocket(sock);
11927       return RPC_NET_ERROR;
11928    }
11929
11930    /* get remote computer info */
11931    p = strtok(net_buffer, " ");
11932    if (p != NULL) {
11933       client_hw_type = atoi(p);
11934       p = strtok(NULL, " ");
11935    }
11936    if (p != NULL) {
11937       version = atoi(p);
11938       p = strtok(NULL, " ");
11939    }
11940    if (p != NULL) {
11941       strcpy(client_program, p);
11942       p = strtok(NULL, " ");
11943    }
11944    if (p != NULL) {
11945       strcpy(host_name, p);
11946       p = strtok(NULL, " ");
11947    }
11948
11949    /* save information in _server_acception structure */
11950    _server_acception[index].recv_sock = sock;
11951    _server_acception[index].send_sock = 0;
11952    _server_acception[index].event_sock = 0;
11953    _server_acception[index].remote_hw_type = client_hw_type;
11954    strcpy(_server_acception[index].host_name, host_name);
11955    strcpy(_server_acception[index].prog_name, client_program);
11956    _server_acception[index].tid = ss_gettid();
11957    _server_acception[index].last_activity = ss_millitime();
11958    _server_acception[index].watchdog_timeout = 0;
11959
11960    /* send my own computer id */
11961    hw_type = rpc_get_option(0, RPC_OHW_TYPE);
11962    sprintf(str, "%d %s", hw_type, cm_get_version());
11963    status = send(sock, str, strlen(str) + 1, 0);
11964    if (status != (INT) strlen(str) + 1)
11965       return RPC_NET_ERROR;
11966
11967    rpc_set_server_acception(index + 1);
11968    rpc_calc_convert_flags(hw_type, client_hw_type, &convert_flags);
11969    rpc_set_server_option(RPC_CONVERT_FLAGS, convert_flags);
11970
11971    /* set callback function for ss_suspend */
11972    ss_suspend_set_dispatch(CH_SERVER, _server_acception,
11973                            (int (*)(void)) rpc_server_receive);
11974
11975    return RPC_SUCCESS;
11976 }
void EXPRT rpc_client_check ()
Definition at line 8597 of file midas.c.
References buffer, closesocket, cm_msg, equal_ustring(), FD_SETSIZE, i, MAX_RPC_CONNECTION, MERROR, RPC_CLIENT_CONNECTION::send_sock, and status.
Referenced by cmd_idle(), and rpc_client_connect().
         : rpc_client_check
  Purpose: Check all client connections if remote client closed link
  Function value:
    RPC_SUCCESS              Successful completion
    RPC_NET_ERROR            Error in socket call
    RPC_NO_CONNECTION        Maximum number of connections reached
    RPC_NOT_REGISTERED       cm_connect_experiment was not called properly
\********************************************************************/
{
   INT i, status;
   /* check for broken connections */
   for (i = 0; i < MAX_RPC_CONNECTION; i++)
      if (_client_connection[i].send_sock != 0) {
         int sock;
         fd_set readfds;
         struct timeval timeout;
         char buffer[64];
         sock = _client_connection[i].send_sock;
         FD_ZERO(&readfds);
         FD_SET(sock, &readfds);
         timeout.tv_sec = 0;
         timeout.tv_usec = 0;
         do {
            status = select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
         } while (status == -1);        /* dont return if an alarm signal was cought */
         if (FD_ISSET(sock, &readfds)) {
            status = recv(sock, (char *) buffer, sizeof(buffer), 0);
            if (equal_ustring(buffer, "EXIT")) {
               /* normal exit */
               closesocket(sock);
               memset(&_client_connection[i], 0, sizeof(RPC_CLIENT_CONNECTION));
            }
            if (status <= 0) {
               cm_msg(MERROR, "rpc_client_check",
                      "Connection broken to \"%s\" on host %s",
                      _client_connection[i].client_name, _client_connection[i].host_name);
               /* connection broken -> reset */
               closesocket(sock);
               memset(&_client_connection[i], 0, sizeof(RPC_CLIENT_CONNECTION));
            }
         }
      }
}
INT rpc_deregister_functions (void)
dox
Definition at line 8273 of file midas.c.
References M_FREE, and RPC_SUCCESS.
Referenced by cm_disconnect_experiment(), and rpc_server_receive().
         : rpc_deregister_functions
  Purpose: Free memory of previously registered functions
  Input:
    none
  Output:
    none
  Function value:
    RPC_SUCCESS              Successful completion
\********************************************************************/
{
   if (rpc_list)
      M_FREE(rpc_list);
   rpc_list = NULL;
   return RPC_SUCCESS;
}
int EXPRT rpc_get_event_sock (void)
Definition at line 10272 of file midas.c.
References RPC_SERVER_CONNECTION::event_sock.
Referenced by dm_buffer_create(), and eb_create_buffer().
10275          : rpc_get_event_sock
10276
10277   Purpose: Return event send socket to MIDAS server. Used by MFE.C for
10278            optimized event sending.
10279
10280   Input:
10281     none
10282
10283   Output:
10284     none
10285
10286   Function value:
10287     int    socket
10288
10289 \********************************************************************/
10290 {
10291    return _server_connection.event_sock;
10292 }
RPC_LIST EXPRT* rpc_get_internal_list (INT flag)
Definition at line 1289 of file mrpc.c.
Referenced by cam_init_rpc(), cm_connect_experiment1(), cm_register_server(), main(), rpc_register_client(), rpc_register_functions(), rpc_register_server(), and rpc_server_connect().
{
   if (flag)
      return rpc_list_library;
   else
      return rpc_list_system;
}
INT EXPRT rpc_get_opt_tcp_size (void)
Definition at line 10096 of file midas.c.
10097 {
10098    return _opt_tcp_size;
10099 }
int EXPRT rpc_get_send_sock (void)
dox
Definition at line 10248 of file midas.c.
References RPC_SERVER_CONNECTION::send_sock.
Referenced by yb_file_fragment().
10251          : rpc_get_send_sock
10252
10253   Purpose: Return send socket to MIDAS server. Used by MFE.C for
10254            optimized event sending.
10255
10256   Input:
10257     none
10258
10259   Output:
10260     none
10261
10262   Function value:
10263     int    socket
10264
10265 \********************************************************************/
10266 {
10267    return _server_connection.send_sock;
10268 }
INT rpc_get_server_acception (void)
Definition at line 9045 of file midas.c.
Referenced by bm_check_buffers(), bm_close_buffer(), bm_empty_buffers(), bm_mark_read_waiting(), bm_open_buffer(), cm_set_watchdog_params(), db_close_database(), db_flush_database(), and db_open_database().
         : rpc_get_server_acception
  Purpose: Return actual RPC server connection index
  Input:
   none
  Output:
    none
  Function value:
    INT    RPC server connection index
\********************************************************************/
{
   return _server_acception_index;
}
PTYPE EXPRT rpc_get_server_option (INT item)
dox
Definition at line 9250 of file midas.c.
References RPC_SERVER_ACCEPTION::client_handle, RPC_SERVER_ACCEPTION::convert_flags, i, MAX, MAX_RPC_CONNECTION, RPC_SERVER_ACCEPTION::odb_handle, PTYPE, RPC_CLIENT_HANDLE, RPC_CONVERT_FLAGS, RPC_ODB_HANDLE, RPC_OSERVER_NAME, RPC_OSERVER_TYPE, RPC_SEND_SOCK, RPC_WATCHDOG_TIMEOUT, RPC_SERVER_ACCEPTION::send_sock, ss_gettid(), ST_MTHREAD, ST_NONE, ST_REMOTE, ST_SINGLE, and RPC_SERVER_ACCEPTION::watchdog_timeout.
Referenced by bm_check_buffers(), bm_close_buffer(), bm_empty_buffers(), bm_mark_read_waiting(), bm_notify_client(), bm_open_buffer(), bm_receive_event(), cm_disconnect_experiment(), cm_get_experiment_database(), cm_set_watchdog_params(), db_close_database(), db_flush_database(), db_get_record(), db_open_database(), db_set_record(), db_update_record(), recv_event_server(), recv_tcp_server(), rpc_check_channels(), rpc_server_accept(), rpc_server_callback(), rpc_server_dispatch(), rpc_server_receive(), and ss_suspend().
         : rpc_get_server_option
  Purpose: Get actual RPC option for server connection
  Input:
    INT  item               One of RPC_Oxxx
  Output:
    none
  Function value:
    INT                     Actual option
\********************************************************************/
{
   INT i;
   if (item == RPC_OSERVER_TYPE)
      return _server_type;
   if (item == RPC_OSERVER_NAME)
      return (PTYPE) _server_name;
   /* return 0 for local calls */
   if (_server_type == ST_NONE)
      return 0;
   /* check which connections belongs to caller */
   if (_server_type == ST_MTHREAD) {
      for (i = 0; i < MAX_RPC_CONNECTION; i++)
         if (_server_acception[i].tid == ss_gettid())
            break;
   } else if (_server_type == ST_SINGLE || _server_type == ST_REMOTE)
      i = MAX(0, _server_acception_index - 1);
   else
      i = 0;
   switch (item) {
   case RPC_CONVERT_FLAGS:
      return _server_acception[i].convert_flags;
   case RPC_ODB_HANDLE:
      return _server_acception[i].odb_handle;
   case RPC_CLIENT_HANDLE:
      return _server_acception[i].client_handle;
   case RPC_SEND_SOCK:
      return _server_acception[i].send_sock;
   case RPC_WATCHDOG_TIMEOUT:
      return _server_acception[i].watchdog_timeout;
   }
   return 0;
}
INT EXPRT rpc_server_accept (int sock)
Definition at line 11616 of file midas.c.
References _debug_mode, closesocket, cm_get_version(), cm_msg, cm_scan_experiments(), callback_addr::debug, experiment_table::directory, callback_addr::directory, equal_ustring(), callback_addr::experiment, callback_addr::host_name, callback_addr::host_port1, callback_addr::host_port2, callback_addr::host_port3, i, callback_addr::index, index, MAX_EXPERIMENT, MAX_RPC_CONNECTION, MERROR, experiment_table::name, net_buffer, recv_string(), rpc_debug_printf(), rpc_get_server_option(), RPC_NET_ERROR, RPC_OSERVER_NAME, RPC_OSERVER_TYPE, rpc_server_callback(), rpc_server_thread(), RPC_SHUTDOWN, RPC_SUCCESS, send(), size, ss_shell(), ss_spawnv(), SS_SUCCESS, ss_thread_create(), ST_MPROCESS, ST_MTHREAD, ST_REMOTE, ST_SINGLE, status, experiment_table::user, and callback_addr::user.
Referenced by main(), and rpc_register_server().
11619          : rpc_server_accept
11620
11621   Purpose: Accept new incoming connections
11622
11623   Input:
11624     INT    lscok            Listen socket
11625
11626   Output:
11627     none
11628
11629   Function value:
11630     RPC_SUCCESS             Successful completion
11631     RPC_NET_ERROR           Error in socket call
11632     RPC_CONNCLOSED          Connection was closed
11633     RPC_SHUTDOWN            Listener shutdown
11634     RPC_EXCEED_BUFFER       Not enough memory for network buffer
11635
11636 \********************************************************************/
11637 {
11638    INT index, i;
11639    int size, status;
11640    char command, version[32], v1[32];
11641    INT sock, port1, port2, port3;
11642    struct sockaddr_in acc_addr;
11643    struct hostent *phe;
11644    char str[100];
11645    char host_port1_str[30], host_port2_str[30], host_port3_str[30];
11646    char debug_str[30];
11647    char *argv[10];
11648    char net_buffer[256];
11649    struct linger ling;
11650
11651    static struct callback_addr callback;
11652
11653    if (lsock > 0) {
11654       size = sizeof(acc_addr);
11655       sock = accept(lsock, (struct sockaddr *) &acc_addr, (int *) &size);
11656
11657       if (sock == -1)
11658          return RPC_NET_ERROR;
11659    } else {
11660       /* lsock is stdin -> already connected from inetd */
11661
11662       size = sizeof(acc_addr);
11663       sock = lsock;
11664       getpeername(sock, (struct sockaddr *) &acc_addr, (int *) &size);
11665    }
11666
11667    /* receive string with timeout */
11668    i = recv_string(sock, net_buffer, 256, 10000);
11669    rpc_debug_printf("Received command: %s", net_buffer);
11670
11671    if (i > 0) {
11672       command = (char) toupper(net_buffer[0]);
11673
11674       switch (command) {
11675       case 'S':
11676
11677          /*----------- shutdown listener ----------------------*/
11678          closesocket(sock);
11679          return RPC_SHUTDOWN;
11680
11681       case 7:
11682          ss_shell(sock);
11683          closesocket(sock);
11684          break;
11685
11686       case 'I':
11687
11688          /*----------- return available experiments -----------*/
11689          cm_scan_experiments();
11690          for (i = 0; i < MAX_EXPERIMENT && exptab[i].name[0]; i++) {
11691             sprintf(str, "%s", exptab[i].name);
11692             send(sock, str, strlen(str) + 1, 0);
11693          }
11694          send(sock, "", 1, 0);
11695          closesocket(sock);
11696          break;
11697
11698       case 'C':
11699
11700          /*----------- connect to experiment -----------*/
11701
11702          /* get callback information */
11703          callback.experiment[0] = 0;
11704          port1 = port2 = version[0] = 0;
11705          sscanf(net_buffer + 2, "%d %d %d %s", &port1, &port2, &port3, version);
11706          strcpy(callback.experiment,
11707                 strchr(strchr(strchr(strchr(net_buffer + 2, ' ') + 1, ' ') + 1, ' ') + 1,
11708                        ' ') + 1);
11709
11710          /* print warning if version patch level doesn't agree */
11711          strcpy(v1, version);
11712          if (strchr(v1, '.'))
11713             if (strchr(strchr(v1, '.') + 1, '.'))
11714                *strchr(strchr(v1, '.') + 1, '.') = 0;
11715
11716          strcpy(str, cm_get_version());
11717          if (strchr(str, '.'))
11718             if (strchr(strchr(str, '.') + 1, '.'))
11719                *strchr(strchr(str, '.') + 1, '.') = 0;
11720
11721          if (strcmp(v1, str) != 0) {
11722             sprintf(str, "client MIDAS version %s differs from local version %s",
11723                     version, cm_get_version());
11724             cm_msg(MERROR, "rpc_server_accept", str);
11725
11726             sprintf(str, "received string: %s", net_buffer + 2);
11727             cm_msg(MERROR, "rpc_server_accept", str);
11728          }
11729
11730          callback.host_port1 = (short) port1;
11731          callback.host_port2 = (short) port2;
11732          callback.host_port3 = (short) port3;
11733          callback.debug = _debug_mode;
11734
11735          /* get the name of the remote host */
11736 #ifdef OS_VXWORKS
11737          {
11738             INT status;
11739             status = hostGetByAddr(acc_addr.sin_addr.s_addr, callback.host_name);
11740             if (status != 0) {
11741                cm_msg(MERROR, "rpc_server_accept", "cannot get host name");
11742                break;
11743             }
11744          }
11745 #else
11746          phe = gethostbyaddr((char *) &acc_addr.sin_addr, 4, PF_INET);
11747          if (phe == NULL) {
11748             /* use IP number instead */
11749             strcpy(callback.host_name, (char *) inet_ntoa(acc_addr.sin_addr));
11750          } else
11751             strcpy(callback.host_name, phe->h_name);
11752 #endif
11753
11754          if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_MPROCESS) {
11755             /* update experiment definition */
11756             cm_scan_experiments();
11757
11758             /* lookup experiment */
11759             if (equal_ustring(callback.experiment, "Default"))
11760                index = 0;
11761             else
11762                for (index = 0; index < MAX_EXPERIMENT && exptab[index].name[0]; index++)
11763                   if (equal_ustring(callback.experiment, exptab[index].name))
11764                      break;
11765
11766             if (index == MAX_EXPERIMENT || exptab[index].name[0] == 0) {
11767                sprintf(str, "experiment %s not defined in exptab\r", callback.experiment);
11768                cm_msg(MERROR, "rpc_server_accept", str);
11769
11770                send(sock, "2", 2, 0);   /* 2 means exp. not found */
11771                closesocket(sock);
11772                break;
11773             }
11774
11775             strcpy(callback.directory, exptab[index].directory);
11776             strcpy(callback.user, exptab[index].user);
11777
11778             /* create a new process */
11779             sprintf(host_port1_str, "%d", callback.host_port1);
11780             sprintf(host_port2_str, "%d", callback.host_port2);
11781             sprintf(host_port3_str, "%d", callback.host_port3);
11782             sprintf(debug_str, "%d", callback.debug);
11783
11784             argv[0] = (char *) rpc_get_server_option(RPC_OSERVER_NAME);
11785             argv[1] = callback.host_name;
11786             argv[2] = host_port1_str;
11787             argv[3] = host_port2_str;
11788             argv[4] = host_port3_str;
11789             argv[5] = debug_str;
11790             argv[6] = callback.experiment;
11791             argv[7] = callback.directory;
11792             argv[8] = callback.user;
11793             argv[9] = NULL;
11794
11795             rpc_debug_printf("Spawn: %s %s %s %s %s %s %s %s %s %s",
11796                argv[0], argv[1], argv[2], argv[3], argv[4],
11797                argv[5], argv[6], argv[7], argv[8], argv[9]);
11798
11799             status = ss_spawnv(P_NOWAIT,
11800                           (char *) rpc_get_server_option(RPC_OSERVER_NAME),
11801                           argv);
11802
11803             if (status != SS_SUCCESS) {
11804                rpc_debug_printf("Cannot spawn subprocess: %s\n", strerror(errno));
11805
11806                sprintf(str, "3");       /* 3 means cannot spawn subprocess */
11807                send(sock, str, strlen(str) + 1, 0);
11808                closesocket(sock);
11809                break;
11810             }
11811
11812             sprintf(str, "1 %s", cm_get_version());     /* 1 means ok */
11813             send(sock, str, strlen(str) + 1, 0);
11814             closesocket(sock);
11815          } else {
11816             sprintf(str, "1 %s", cm_get_version());     /* 1 means ok */
11817             send(sock, str, strlen(str) + 1, 0);
11818             closesocket(sock);
11819          }
11820
11821          /* look for next free entry */
11822          for (index = 0; index < MAX_RPC_CONNECTION; index++)
11823             if (_server_acception[index].recv_sock == 0)
11824                break;
11825          if (index == MAX_RPC_CONNECTION)
11826             return RPC_NET_ERROR;
11827          callback.index = index;
11828
11829         /*----- multi thread server ------------------------*/
11830          if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_MTHREAD)
11831             ss_thread_create(rpc_server_thread, (void *) (&callback));
11832
11833         /*----- single thread server -----------------------*/
11834          if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_SINGLE ||
11835              rpc_get_server_option(RPC_OSERVER_TYPE) == ST_REMOTE)
11836             rpc_server_callback(&callback);
11837
11838          break;
11839
11840       default:
11841          cm_msg(MERROR, "rpc_server_accept", "received unknown command '%c'", command);
11842          closesocket(sock);
11843          break;
11844
11845       }
11846    } else {                     /* if i>0 */
11847
11848       /* lingering needed for PCTCP */
11849       ling.l_onoff = 1;
11850       ling.l_linger = 0;
11851       setsockopt(sock, SOL_SOCKET, SO_LINGER, (char *) &ling, sizeof(ling));
11852       closesocket(sock);
11853    }
11854
11855    return RPC_SUCCESS;
11856 }
INT rpc_server_callback (struct callback_addr * callback)
Definition at line 11980 of file midas.c.
References CH_SERVER, closesocket, cm_msg, RPC_SERVER_ACCEPTION::event_sock, flag, callback_addr::host_name, HOST_NAME_LENGTH, callback_addr::host_port1, callback_addr::host_port2, callback_addr::host_port3, callback_addr::index, index, RPC_SERVER_ACCEPTION::last_activity, MERROR, NAME_LENGTH, net_buffer, NET_TCP_SIZE, RPC_SERVER_ACCEPTION::recv_sock, recv_string(), RPC_SERVER_ACCEPTION::remote_hw_type, rpc_calc_convert_flags(), RPC_CONVERT_FLAGS, rpc_debug_printf(), rpc_get_option(), rpc_get_server_option(), RPC_NET_ERROR, RPC_OHW_TYPE, RPC_OSERVER_TYPE, rpc_server_receive(), rpc_set_server_acception(), rpc_set_server_option(), RPC_SUCCESS, send(), RPC_SERVER_ACCEPTION::send_sock, ss_gettid(), ss_millitime(), ss_suspend_set_dispatch(), ST_REMOTE, status, RPC_SERVER_ACCEPTION::tid, and RPC_SERVER_ACCEPTION::watchdog_timeout.
Referenced by rpc_server_accept(), and rpc_server_thread().
11983          : rpc_server_callback
11984
11985   Purpose: Callback a remote client. Setup _server_acception entry
11986            with optional conversion flags and establish two-way
11987            TCP connection.
11988
11989   Input:
11990     callback_addr pcallback Pointer to a callback structure
11991
11992   Output:
11993     none
11994
11995   Function value:
11996     RPC_SUCCESS             Successful completion
11997
11998 \********************************************************************/
11999 {
12000    INT index, status;
12001    int recv_sock, send_sock, event_sock;
12002    struct sockaddr_in bind_addr;
12003    struct hostent *phe;
12004    char str[100], client_program[NAME_LENGTH];
12005    char host_name[HOST_NAME_LENGTH];
12006    INT client_hw_type, hw_type;
12007    INT convert_flags;
12008    char net_buffer[256];
12009    struct callback_addr callback;
12010    int flag;
12011
12012    /* copy callback information */
12013    memcpy(&callback, pcallback, sizeof(callback));
12014    index = callback.index;
12015
12016    /* create new sockets for TCP */
12017    recv_sock = socket(AF_INET, SOCK_STREAM, 0);
12018    send_sock = socket(AF_INET, SOCK_STREAM, 0);
12019    event_sock = socket(AF_INET, SOCK_STREAM, 0);
12020    if (event_sock == -1)
12021       return RPC_NET_ERROR;
12022
12023    /* callback to remote node */
12024    memset(&bind_addr, 0, sizeof(bind_addr));
12025    bind_addr.sin_family = AF_INET;
12026    bind_addr.sin_port = htons(callback.host_port1);
12027
12028 #ifdef OS_VXWORKS
12029    {
12030       INT host_addr;
12031
12032       host_addr = hostGetByName(callback.host_name);
12033       memcpy((char *) &(bind_addr.sin_addr), &host_addr, 4);
12034    }
12035 #else
12036    phe = gethostbyname(callback.host_name);
12037    if (phe == NULL) {
12038       cm_msg(MERROR, "rpc_server_callback", "cannot get host name");
12039       return RPC_NET_ERROR;
12040    }
12041    memcpy((char *) &(bind_addr.sin_addr), phe->h_addr, phe->h_length);
12042 #endif
12043
12044    /* connect receive socket */
12045 #ifdef OS_UNIX
12046    do {
12047       status = connect(recv_sock, (void *) &bind_addr, sizeof(bind_addr));
12048
12049       /* don't return if an alarm signal was cought */
12050    } while (status == -1 && errno == EINTR);
12051 #else
12052    status = connect(recv_sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
12053 #endif
12054
12055    if (status != 0) {
12056       cm_msg(MERROR, "rpc_server_callback", "cannot connect receive socket");
12057       goto error;
12058    }
12059
12060    bind_addr.sin_port = htons(callback.host_port2);
12061
12062    /* connect send socket */
12063 #ifdef OS_UNIX
12064    do {
12065       status = connect(send_sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
12066
12067       /* don't return if an alarm signal was cought */
12068    } while (status == -1 && errno == EINTR);
12069 #else
12070    status = connect(send_sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
12071 #endif
12072
12073    if (status != 0) {
12074       cm_msg(MERROR, "rpc_server_callback", "cannot connect send socket");
12075       goto error;
12076    }
12077
12078    bind_addr.sin_port = htons(callback.host_port3);
12079
12080    /* connect event socket */
12081 #ifdef OS_UNIX
12082    do {
12083       status = connect(event_sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
12084
12085       /* don't return if an alarm signal was cought */
12086    } while (status == -1 && errno == EINTR);
12087 #else
12088    status = connect(event_sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
12089 #endif
12090
12091    if (status != 0) {
12092       cm_msg(MERROR, "rpc_server_callback", "cannot connect event socket");
12093       goto error;
12094    }
12095
12096    /* increase receive buffer size to 64k */
12097 #ifndef OS_ULTRIX               /* crashes ULTRIX... */
12098    flag = NET_TCP_SIZE + 1;
12099    setsockopt(event_sock, SOL_SOCKET, SO_RCVBUF, (char *) &flag, sizeof(INT));
12100 #endif
12101
12102    if (recv_string(recv_sock, net_buffer, 256, 10000) <= 0) {
12103       cm_msg(MERROR, "rpc_server_callback", "timeout on receive remote computer info");
12104       goto error;
12105    }
12106
12107    /* get remote computer info */
12108    sscanf(net_buffer, "%d", &client_hw_type);
12109
12110    strcpy(client_program, strchr(net_buffer, ' ') + 1);
12111
12112    /* get the name of the remote host */
12113 #ifdef OS_VXWORKS
12114    status = hostGetByAddr(bind_addr.sin_addr.s_addr, host_name);
12115    if (status != 0)
12116       strcpy(host_name, "unknown");
12117 #else
12118    phe = gethostbyaddr((char *) &bind_addr.sin_addr, 4, PF_INET);
12119    if (phe == NULL)
12120       strcpy(host_name, "unknown");
12121    else
12122       strcpy(host_name, phe->h_name);
12123 #endif
12124
12125    /* save information in _server_acception structure */
12126    _server_acception[index].recv_sock = recv_sock;
12127    _server_acception[index].send_sock = send_sock;
12128    _server_acception[index].event_sock = event_sock;
12129    _server_acception[index].remote_hw_type = client_hw_type;
12130    strcpy(_server_acception[index].host_name, host_name);
12131    strcpy(_server_acception[index].prog_name, client_program);
12132    _server_acception[index].tid = ss_gettid();
12133    _server_acception[index].last_activity = ss_millitime();
12134    _server_acception[index].watchdog_timeout = 0;
12135
12136    /* send my own computer id */
12137    hw_type = rpc_get_option(0, RPC_OHW_TYPE);
12138    sprintf(str, "%d", hw_type);
12139    send(recv_sock, str, strlen(str) + 1, 0);
12140
12141    rpc_set_server_acception(index + 1);
12142    rpc_calc_convert_flags(hw_type, client_hw_type, &convert_flags);
12143    rpc_set_server_option(RPC_CONVERT_FLAGS, convert_flags);
12144
12145    /* set callback function for ss_suspend */
12146    ss_suspend_set_dispatch(CH_SERVER, _server_acception,
12147                            (int (*)(void)) rpc_server_receive);
12148
12149    if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE)
12150       rpc_debug_printf("Connection to %s:%s established\n",
12151              _server_acception[index].host_name, _server_acception[index].prog_name);
12152
12153    return RPC_SUCCESS;
12154
12155  error:
12156
12157    closesocket(recv_sock);
12158    closesocket(send_sock);
12159    closesocket(event_sock);
12160
12161    return RPC_NET_ERROR;
12162 }
INT rpc_server_disconnect (void)
Definition at line 8975 of file midas.c.
References closesocket, RPC_SERVER_CONNECTION::event_sock, RPC_SERVER_CONNECTION::recv_sock, rpc_call(), rpc_flush_event(), RPC_ID_EXIT, RPC_SUCCESS, and RPC_SERVER_CONNECTION::send_sock.
Referenced by cm_connect_experiment1(), cm_disconnect_experiment(), and rpc_call().
         : rpc_server_disconnect
  Purpose: Close a rpc connection to a MIDAS server and close all
           server connections from other clients
  Input:
    none
  Output:
    none
  Function value:
   RPC_SUCCESS             Successful completion
   RPC_NET_ERROR           Error in socket call
   RPC_NO_CONNECTION       Maximum number of connections reached
\********************************************************************/
{
   static int rpc_server_disconnect_recursion_level = 0;
   if (rpc_server_disconnect_recursion_level)
      return RPC_SUCCESS;
   rpc_server_disconnect_recursion_level = 1;
   /* flush remaining events */
   rpc_flush_event();
   /* notify server about exit */
   rpc_call(RPC_ID_EXIT);
   /* close sockets */
   closesocket(_server_connection.send_sock);
   closesocket(_server_connection.recv_sock);
   closesocket(_server_connection.event_sock);
   memset(&_server_connection, 0, sizeof(RPC_SERVER_CONNECTION));
   rpc_server_disconnect_recursion_level = 0;
   return RPC_SUCCESS;
}
INT rpc_server_receive (INT index, int sock, BOOL check)
Definition at line 12223 of file midas.c.
References _msg_buffer, _net_recv_buffer, _net_recv_buffer_size, bm_close_all_buffers(), bm_send_event(), BM_SUCCESS, closesocket, cm_delete_client_info(), cm_get_experiment_database(), cm_msg, cm_set_experiment_database(), cm_watchdog(), EVENT_HEADER::data_size, db_close_all_databases(), DR_ASCII, hDB, hKey, M_FREE, M_MALLOC, MERROR, MTALK, RPC_SERVER_ACCEPTION::net_buffer, net_buffer, NET_BUFFER_SIZE, recv_event_server(), recv_string(), recv_tcp_server(), rpc_debug_printf(), rpc_deregister_functions(), RPC_EXCEED_BUFFER, rpc_execute(), rpc_execute_ascii(), rpc_get_server_option(), RPC_OSERVER_TYPE, rpc_set_server_acception(), RPC_SHUTDOWN, RPC_SUCCESS, SS_ABORT, ss_alarm(), SS_EXIT, ss_millitime(), SS_SUCCESS, ST_REMOTE, start_time, status, and SYNC.
Referenced by rpc_client_accept(), and rpc_server_callback().
12226          : rpc_server_receive
12227
12228   Purpose: Receive rpc commands and execute them. Close the connection
12229            if client has broken TCP pipe.
12230
12231   Input:
12232     INT    index            Index to _server_acception structure in-
12233                             dicating which connection got data.
12234     int    sock             Socket which got data
12235     BOOL   check            If TRUE, only check if connection is
12236                             broken. This may be called via
12237                             bm_receive_event/ss_suspend(..,MSG_BM)
12238
12239   Output:
12240     none
12241
12242   Function value:
12243     RPC_SUCCESS             Successful completion
12244     RPC_EXCEED_BUFFER       Not enough memeory to allocate buffer
12245     SS_EXIT                 Server connection was closed
12246     SS_ABORT                Server connection was broken
12247
12248 \********************************************************************/
12249 {
12250    INT status, n_received;
12251    INT remaining, *pbh, start_time;
12252    char test_buffer[256], str[80];
12253    EVENT_HEADER *pevent;
12254
12255    /* init network buffer */
12256    if (_net_recv_buffer_size == 0) {
12257       _net_recv_buffer = (char *) M_MALLOC(NET_BUFFER_SIZE);
12258       if (_net_recv_buffer == NULL) {
12259          cm_msg(MERROR, "rpc_server_receive",
12260                 "not enough memory to allocate network buffer");
12261          return RPC_EXCEED_BUFFER;
12262       }
12263       _net_recv_buffer_size = NET_BUFFER_SIZE;
12264    }
12265
12266    /* only check if TCP connection is broken */
12267    if (check) {
12268       n_received = recv(sock, test_buffer, sizeof(test_buffer), MSG_PEEK);
12269
12270       if (n_received == -1)
12271          cm_msg(MERROR, "rpc_server_receive",
12272                 "recv(%d,MSG_PEEK) returned %d, errno: %d (%s)", sizeof(test_buffer),
12273                 n_received, errno, strerror(errno));
12274
12275       if (n_received <= 0)
12276          return SS_ABORT;
12277
12278       return SS_SUCCESS;
12279    }
12280
12281    remaining = 0;
12282
12283    /* receive command */
12284    if (sock == _server_acception[index].recv_sock) {
12285       do {
12286          if (_server_acception[index].remote_hw_type == DR_ASCII)
12287             n_received = recv_string(_server_acception[index].recv_sock, _net_recv_buffer,
12288                                      NET_BUFFER_SIZE, 10000);
12289          else
12290             n_received =
12291                 recv_tcp_server(index, _net_recv_buffer, NET_BUFFER_SIZE, 0, &remaining);
12292
12293          if (n_received <= 0) {
12294             status = SS_ABORT;
12295             cm_msg(MERROR, "rpc_server_receive", "recv_tcp_server() returned %d, abort",
12296                    n_received);
12297             goto error;
12298          }
12299
12300          rpc_set_server_acception(index + 1);
12301
12302          if (_server_acception[index].remote_hw_type == DR_ASCII)
12303             status = rpc_execute_ascii(_server_acception[index].recv_sock,
12304                                        _net_recv_buffer);
12305          else
12306             status = rpc_execute(_server_acception[index].recv_sock,
12307                                  _net_recv_buffer,
12308                                  _server_acception[index].convert_flags);
12309
12310          if (status == SS_ABORT) {
12311             cm_msg(MERROR, "rpc_server_receive", "rpc_execute() returned %d, abort",
12312                    status);
12313             goto error;
12314          }
12315
12316          if (status == SS_EXIT || status == RPC_SHUTDOWN) {
12317             if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE)
12318                rpc_debug_printf("Connection to %s:%s closed\n",
12319                       _server_acception[index].host_name,
12320                       _server_acception[index].prog_name);
12321             goto exit;
12322          }
12323
12324       } while (remaining);
12325    } else {
12326       /* receive event */
12327       if (sock == _server_acception[index].event_sock) {
12328          start_time = ss_millitime();
12329
12330          do {
12331             n_received =
12332                 recv_event_server(index, _net_recv_buffer, NET_BUFFER_SIZE, 0,
12333                                   &remaining);
12334
12335             if (n_received <= 0) {
12336                status = SS_ABORT;
12337                cm_msg(MERROR, "rpc_server_receive",
12338                       "recv_event_server() returned %d, abort", n_received);
12339                goto error;
12340             }
12341
12342             /* send event to buffer */
12343             pbh = (INT *) _net_recv_buffer;
12344             pevent = (EVENT_HEADER *) (pbh + 1);
12345
12346             status =
12347                 bm_send_event(*pbh, pevent, pevent->data_size + sizeof(EVENT_HEADER),
12348                               SYNC);
12349             if (status != BM_SUCCESS)
12350                cm_msg(MERROR, "rpc_server_receive", "bm_send_event() returned %d",
12351                       status);
12352
12353             /* repeat for maximum 0.5 sec */
12354          } while (ss_millitime() - start_time < 500 && remaining);
12355       }
12356    }
12357
12358    return RPC_SUCCESS;
12359
12360  error:
12361
12362    strcpy(str, _server_acception[index].host_name);
12363    if (strchr(str, '.'))
12364       *strchr(str, '.') = 0;
12365    cm_msg(MTALK, "rpc_server_receive", "Program %s on host %s aborted",
12366           _server_acception[index].prog_name, str);
12367
12368  exit:
12369
12370    /* disconnect from experiment as MIDAS server */
12371    if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE) {
12372       HNDLE hDB, hKey;
12373
12374       cm_get_experiment_database(&hDB, &hKey);
12375
12376       /* only disconnect from experiment if previously connected.
12377          Necessary for pure RPC servers (RPC_SRVR) */
12378       if (hDB) {
12379 #ifdef LOCAL_ROUTINES
12380          ss_alarm(0, cm_watchdog);
12381 #endif
12382
12383          cm_delete_client_info(hDB, 0);
12384
12385          bm_close_all_buffers();
12386          db_close_all_databases();
12387
12388          rpc_deregister_functions();
12389
12390          cm_set_experiment_database(0, 0);
12391
12392          _msg_buffer = 0;
12393       }
12394    }
12395
12396    /* close server connection */
12397    if (_server_acception[index].recv_sock)
12398       closesocket(_server_acception[index].recv_sock);
12399    if (_server_acception[index].send_sock)
12400       closesocket(_server_acception[index].send_sock);
12401    if (_server_acception[index].event_sock)
12402       closesocket(_server_acception[index].event_sock);
12403
12404    /* free TCP cache */
12405    M_FREE(_server_acception[index].net_buffer);
12406    _server_acception[index].net_buffer = NULL;
12407
12408    /* mark this entry as invalid */
12409    memset(&_server_acception[index], 0, sizeof(RPC_SERVER_ACCEPTION));
12410
12411    /* signal caller a shutdonw */
12412    if (status == RPC_SHUTDOWN)
12413       return status;
12414
12415    /* don't abort if other than main connection is broken */
12416    if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_REMOTE)
12417       return SS_SUCCESS;
12418
12419    return status;
12420 }
INT EXPRT rpc_set_opt_tcp_size (INT tcp_size)
Definition at line 10087 of file midas.c.
Referenced by scheduler().
10088 {
10089    INT old;
10090
10091    old = _opt_tcp_size;
10092    _opt_tcp_size = tcp_size;
10093    return old;
10094 }
INT rpc_set_server_acception (INT index)
Definition at line 9068 of file midas.c.
References RPC_SUCCESS.
Referenced by rpc_client_accept(), rpc_server_callback(), and rpc_server_receive().
         : rpc_set_server_acception
  Purpose: Set actual RPC server connection index
  Input:
    INT  index              Server index
  Output:
    none
  Function value:
    RPC_SUCCESS             Successful completion
\********************************************************************/
{
   _server_acception_index = index;
   return RPC_SUCCESS;
}
INT EXPRT rpc_set_server_option (INT item, PTYPE value)
Definition at line 9308 of file midas.c.
References RPC_SERVER_ACCEPTION::client_handle, RPC_SERVER_ACCEPTION::convert_flags, i, MAX, MAX_RPC_CONNECTION, RPC_SERVER_ACCEPTION::odb_handle, RPC_CLIENT_HANDLE, RPC_CONVERT_FLAGS, RPC_ODB_HANDLE, RPC_OSERVER_NAME, RPC_OSERVER_TYPE, RPC_SUCCESS, RPC_WATCHDOG_TIMEOUT, ss_gettid(), ST_MTHREAD, ST_REMOTE, ST_SINGLE, and RPC_SERVER_ACCEPTION::watchdog_timeout.
Referenced by cm_set_client_info(), cm_set_watchdog_params(), main(), rpc_client_accept(), rpc_register_server(), and rpc_server_callback().
         : rpc_set_server_option
  Purpose: Set RPC option for server connection
  Input:
   INT  item               One of RPC_Oxxx
   INT  value              Value to set
  Output:
    none
  Function value:
    RPC_SUCCESS             Successful completion
\********************************************************************/
{
   INT i;
   if (item == RPC_OSERVER_TYPE) {
      _server_type = value;
      return RPC_SUCCESS;
   }
   if (item == RPC_OSERVER_NAME) {
      strcpy(_server_name, (char *) value);
      return RPC_SUCCESS;
   }
   /* check which connections belongs to caller */
   if (_server_type == ST_MTHREAD) {
      for (i = 0; i < MAX_RPC_CONNECTION; i++)
         if (_server_acception[i].tid == ss_gettid())
            break;
   } else if (_server_type == ST_SINGLE || _server_type == ST_REMOTE)
      i = MAX(0, _server_acception_index - 1);
   else
      i = 0;
   switch (item) {
   case RPC_CONVERT_FLAGS:
      _server_acception[i].convert_flags = value;
      break;
   case RPC_ODB_HANDLE:
      _server_acception[i].odb_handle = value;
      break;
   case RPC_CLIENT_HANDLE:
      _server_acception[i].client_handle = value;
      break;
   case RPC_WATCHDOG_TIMEOUT:
      _server_acception[i].watchdog_timeout = value;
      break;
   }
   return RPC_SUCCESS;
}
INT EXPRT send_tcp (int sock, char * buffer, DWORD buffer_size, INT flags)
Definition at line 3606 of file system.c.
References cm_msg, count, MERROR, NET_TCP_SIZE, send(), and status.
Referenced by bm_notify_client(), db_update_record(), dm_buffer_send(), eb_send_events(), redirect2(), rpc_call(), rpc_check_channels(), rpc_client_call(), rpc_client_dispatch(), rpc_execute(), rpc_execute_ascii(), rpc_flush_event(), rpc_send_event(), and server_loop().
         : send_tcp
  Purpose: Send network data over TCP port. Break buffer in smaller
           parts if larger than maximum TCP buffer size (usually 64k).
  Input:
    INT   sock               Socket which was previosly opened.
    DWORD buffer_size        Size of the buffer in bytes.
    INT   flags              Flags passed to send()
  Output:
    char  *buffer            Network receive buffer.
  Function value:
    INT                     Same as send()
\********************************************************************/
{
   DWORD count;
   INT status;
   /* transfer fragments until complete buffer is transferred */
   for (count = 0; (INT) count < (INT) buffer_size - NET_TCP_SIZE;) {
      status = send(sock, buffer + count, NET_TCP_SIZE, flags);
      if (status != -1)
         count += status;
      else {
         cm_msg(MERROR, "send_tcp",
                "send(socket=%d,size=%d) returned %d, errno: %d (%s)",
                sock, NET_TCP_SIZE, status, errno, strerror(errno));
         return status;
      }
   }
   while (count < buffer_size) {
      status = send(sock, buffer + count, buffer_size - count, flags);
      if (status != -1)
         count += status;
      else {
         cm_msg(MERROR, "send_tcp",
                "send(socket=%d,size=%d) returned %d, errno: %d (%s)",
                sock, (int) (buffer_size - count), status, errno, strerror(errno));
         return status;
      }
   }
   return count;
}
INT send_udp (int sock, char * buffer, DWORD buffer_size, INT flags)
Definition at line 3831 of file system.c.
References data_size, NET_UDP_SIZE, send(), UDP_HEADER::sequence_number, UDP_HEADER::serial_number, serial_number, status, and UDP_FIRST.
         : send_udp
  Purpose: Send network data over UDP port. If buffer_size is small,
     collect several events and send them together. If
     buffer_size is larger than largest datagram size
     NET_UDP_SIZE, split event in several udp buffers and
     send them separately with serial number protection.
  Input:
    INT   sock               Socket which was previosly opened.
    DWORD buffer_size        Size of the buffer in bytes.
    INT   flags              Flags passed to send()
  Output:
    char  *buffer            Network receive buffer.
  Function value:
    INT                     Same as send()
\********************************************************************/
{
   INT status;
   UDP_HEADER *udp_header;
   static char udp_buffer[NET_UDP_SIZE];
   static INT serial_number = 0, n_received = 0;
   DWORD i, data_size;
   udp_header = (UDP_HEADER *) udp_buffer;
   data_size = NET_UDP_SIZE - sizeof(UDP_HEADER);
   /*
      If buffer size is between half the UPD size and full UDP size,
      send immediately a single packet.
    */
   if (buffer_size >= NET_UDP_SIZE / 2 && buffer_size <= data_size) {
      /*
         If there is any data already in the buffer, send it first.
       */
      if (n_received) {
         udp_header->serial_number = UDP_FIRST | n_received;
         udp_header->sequence_number = ++serial_number;
         send(sock, udp_buffer, n_received + sizeof(UDP_HEADER), flags);
         n_received = 0;
      }
      udp_header->serial_number = UDP_FIRST | buffer_size;
      udp_header->sequence_number = ++serial_number;
      memcpy(udp_header + 1, buffer, buffer_size);
      status = send(sock, udp_buffer, buffer_size + sizeof(UDP_HEADER), flags);
      if (status == (INT) buffer_size + (int) sizeof(UDP_HEADER))
         status -= sizeof(UDP_HEADER);
      return status;
   }
   /*
      If buffer size is smaller than half the UDP size, collect events
      until UDP buffer is optimal filled.
    */
   if (buffer_size <= data_size) {
      /* If udp_buffer has space, just copy it there */
      if (buffer_size + n_received < data_size) {
         memcpy(udp_buffer + sizeof(UDP_HEADER) + n_received, buffer, buffer_size);
         n_received += buffer_size;
         return buffer_size;
      }
      /* If udp_buffer has not enough space, send it */
      udp_header->serial_number = UDP_FIRST | n_received;
      udp_header->sequence_number = ++serial_number;
      status = send(sock, udp_buffer, n_received + sizeof(UDP_HEADER), flags);
      n_received = 0;
      memcpy(udp_header + 1, buffer, buffer_size);
      n_received = buffer_size;
      return buffer_size;
   }
   /*
      If buffer size is larger than UDP size, split event in several
      buffers.
    */
   /* If there is any data already in the buffer, send it first */
   if (n_received) {
      udp_header->serial_number = UDP_FIRST | n_received;
      udp_header->sequence_number = ++serial_number;
      send(sock, udp_buffer, n_received + sizeof(UDP_HEADER), flags);
      n_received = 0;
   }
   for (i = 0; i < ((buffer_size - 1) / data_size); i++) {
      if (i == 0) {
         udp_header->serial_number = UDP_FIRST | buffer_size;
         udp_header->sequence_number = ++serial_number;
      } else {
         udp_header->serial_number = serial_number;
         udp_header->sequence_number = i;
      }
      memcpy(udp_header + 1, buffer + i * data_size, data_size);
      send(sock, udp_buffer, NET_UDP_SIZE, flags);
   }
   /* Send remaining bytes */
   udp_header->serial_number = serial_number;
   udp_header->sequence_number = i;
   memcpy(udp_header + 1, buffer + i * data_size, buffer_size - i * data_size);
   status =
       send(sock, udp_buffer, sizeof(UDP_HEADER) + buffer_size - i * data_size, flags);
   if ((DWORD) status == sizeof(UDP_HEADER) + buffer_size - i * data_size)
      return buffer_size;
   return status;
}
INT ss_alarm (INT millitime, void(*)(int) func)
Definition at line 2703 of file system.c.
References _timeCallback(), SS_SUCCESS, and UserCallback.
Referenced by cm_disconnect_experiment(), cm_set_client_info(), cm_set_watchdog_params(), cm_watchdog(), and rpc_server_receive().
         : ss_alarm
  Purpose: Schedules an alarm. Call function referenced by *func
     after the specified seconds.
  Input:
    INT    millitime        Time in milliseconds
    void   (*func)()        Function to be called after the spe-
          cified time.
  Output:
    none
  Function value:
    SS_SUCCESS              Successful completion
\********************************************************************/
{
#ifdef OS_WINNT
   UserCallback = func;
   if (millitime > 0)
      _timer_id =
          timeSetEvent(millitime, 100, (LPTIMECALLBACK) _timeCallback, 0, TIME_ONESHOT);
   else {
      if (_timer_id)
         timeKillEvent(_timer_id);
      _timer_id = 0;
   }
   return SS_SUCCESS;
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   signal(SIGALRM, func);
   alarm(millitime / 1000);
   return SS_SUCCESS;
#endif                          /* OS_VMS */
#ifdef OS_UNIX
   signal(SIGALRM, func);
   alarm(millitime / 1000);
   return SS_SUCCESS;
#endif                          /* OS_UNIX */
}
INT EXPRT ss_daemon_init (BOOL keep_stdout)
Definition at line 1466 of file system.c.
References _daemon_flag, cm_msg, i, MERROR, SS_ABORT, SS_SUCCESS, and TRUE.
Referenced by main(), and server_loop().
         : ss_daemon_init
  Purpose: Become a daemon
  Input:
    none
  Output:
    none
  Function value:
    SS_SUCCESS       Successful completeion
    SS_ABORT         fork() was not successful, or other problem
\********************************************************************/
{
#ifdef OS_UNIX
   /* only implemented for UNIX */
   int i, fd, pid;
   if ((pid = fork()) < 0)
      return SS_ABORT;
   else if (pid != 0)
      exit(0);                  /* parent finished */
   /* child continues here */
   _daemon_flag = TRUE;
   /* try and use up stdin, stdout and stderr, so other
      routines writing to stdout etc won't cause havoc. Copied from smbd */
   for (i = 0; i < 3; i++) {
      if (keep_stdout && ((i == 1) || (i == 2)))
         continue;
      close(i);
      fd = open("/dev/null", O_RDWR, 0);
      if (fd < 0)
         fd = open("/dev/null", O_WRONLY, 0);
      if (fd < 0) {
         cm_msg(MERROR, "ss_system", "Can't open /dev/null");
         return SS_ABORT;
      }
      if (fd != i) {
         cm_msg(MERROR, "ss_system", "Did not get file descriptor");
         return SS_ABORT;
      }
   }
   setsid();                    /* become session leader */
   chdir("/");                  /* change working direcotry (not on NFS!) */
   umask(0);                    /* clear our file mode createion mask */
#endif
   return SS_SUCCESS;
}
INT ss_exception_handler (void(*)() func)
Definition at line 2811 of file system.c.
References MidasExceptionFilter(), MidasExceptionHandler, MidasExceptionSignal(), and SS_SUCCESS.
         : ss_exception_handler
  Purpose: Establish new exception handler which is called before
     the program is aborted due to a Ctrl-Break or an access
     violation. This handler may clean up things which may
     otherwise left in an undefined state.
  Input:
    void  (*func)()     Address of handler function
  Output:
    none
  Function value:
    BM_SUCCESS          Successful completion
\********************************************************************/
{
#ifdef OS_WINNT
   MidasExceptionHandler = func;
/*  SetUnhandledExceptionFilter(
    (LPTOP_LEVEL_EXCEPTION_FILTER) MidasExceptionFilter);
  signal(SIGINT, MidasExceptionSignal);
  signal(SIGILL, MidasExceptionSignal);
  signal(SIGFPE, MidasExceptionSignal);
  signal(SIGSEGV, MidasExceptionSignal);
  signal(SIGTERM, MidasExceptionSignal);
  signal(SIGBREAK, MidasExceptionSignal);
  signal(SIGABRT, MidasExceptionSignal); */
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   MidasExceptionHandler = func;
   lib$establish(MidasExceptionFilter);
   signal(SIGINT, MidasExceptionSignal);
   signal(SIGILL, MidasExceptionSignal);
   signal(SIGQUIT, MidasExceptionSignal);
   signal(SIGFPE, MidasExceptionSignal);
   signal(SIGSEGV, MidasExceptionSignal);
   signal(SIGTERM, MidasExceptionSignal);
#endif                          /* OS_WINNT */
   return SS_SUCCESS;
}
INT EXPRT ss_exec (char * cmd, INT * child_pid)
Referenced by main().
BOOL EXPRT ss_existpid (INT pid)
Definition at line 1529 of file system.c.
References cm_msg, FALSE, MINFO, and TRUE.
Referenced by main().
         : ss_existpid
  Purpose: Execute a Kill sig=0 which return success if pid found.
  Input:
    pid  : pid to check
  Output:
    none
  Function value:
    TRUE      PID found
    FALSE     PID not found
\********************************************************************/
{
#ifdef OS_UNIX
   /* only implemented for UNIX */
   return (kill(pid, 0) == 0 ? TRUE : FALSE);
#else
   cm_msg(MINFO, "ss_existpid", "implemented for UNIX only");
   return FALSE;
#endif
}
void EXPRT ss_force_single_thread ()
Definition at line 1045 of file system.c.
References _single_thread, and TRUE.
Referenced by main().
{
   _single_thread = TRUE;
}
INT EXPRT ss_get_struct_align (void)
Definition at line 969 of file system.c.
References PTYPE, and test_align.
Referenced by ascii_write(), db_get_record(), db_get_record_size(), db_set_record(), dump_write(), update_odb(), write_event_ascii(), write_event_hbook(), and write_event_odb().
         : ss_get_struct_align
  Purpose: Returns compiler alignment of structures. In C, structures
     can be byte aligned, word or even quadword aligned. This
     can usually be set with compiler switches. This routine
     tests this alignment during runtime and returns 1 for
     byte alignment, 2 for word alignment, 4 for dword alignment
     and 8 for quadword alignment.
  Input:
    <none>
  Output:
    <none>
  Function value:
    INT    Structure alignment
\********************************************************************/
{
   return (PTYPE) (&test_align.d) - (PTYPE) & test_align.c;
}
INT EXPRT ss_getpid (void)
Definition at line 996 of file system.c.
Referenced by bm_open_buffer(), bm_push_event(), bm_receive_event(), cm_execute(), db_open_database(), debug_print(), ss_getthandle(), and ss_gettid().
         : ss_getpid
  Purpose: Return process ID of current process
  Input:
    none
  Output:
    none
  Function value:
    INT              Process ID
\********************************************************************/
{
#ifdef OS_WINNT
   return (int) GetCurrentProcessId();
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   return getpid();
#endif                          /* OS_VMS */
#ifdef OS_UNIX
   return getpid();
#endif                          /* OS_UNIX */
#ifdef OS_VXWORKS
   return 0;
#endif                          /* OS_VXWORKS */
#ifdef OS_MSDOS
   return 0;
#endif                          /* OS_MSDOS */
}
INT ss_getthandle (void)
Definition at line 913 of file system.c.
References ss_getpid(), and TRUE.
Referenced by bm_open_buffer(), and db_open_database().
         : ss_getthandle
  Purpose: Return thread handle of current thread
  Input:
    none
  Output:
    none
  Function value:
    INT thread handle
\********************************************************************/
{
#ifdef OS_WINNT
   HANDLE hThread;
   /*
      Under Windows NT, it's a little bit tricky to get a thread handle
      which can be passed to other processes. First the calling process
      has to duplicate the GetCurrentThread() handle, then the process
      which gets this handle also has to use DuplicateHandle with the
      target process as its own. Then this duplicated handle can be used
      to the SupendThread() and ResumeThread() functions.
    */
   DuplicateHandle(GetCurrentProcess(), GetCurrentThread(),
                   GetCurrentProcess(), &hThread, THREAD_ALL_ACCESS, TRUE, 0);
   return (INT)hThread;
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   return 0;
#endif                          /* OS_VMS */
#ifdef OS_UNIX
   return ss_getpid();
#endif                          /* OS_VMS */
}
INT EXPRT ss_gettid (void)
Definition at line 1050 of file system.c.
References _single_thread, and ss_getpid().
Referenced by bm_check_buffers(), bm_close_buffer(), bm_empty_buffers(), bm_mark_read_waiting(), bm_open_buffer(), bm_push_event(), bm_receive_event(), cm_delete_client_info(), cm_set_client_info(), cm_set_watchdog_params(), db_close_database(), db_create_record(), db_flush_database(), db_open_database(), rpc_check_channels(), rpc_client_accept(), rpc_get_server_option(), rpc_server_callback(), rpc_set_server_option(), ss_suspend(), and ss_suspend_get_index().
         : ss_ggettid
  Purpose: Return thread ID of current thread
  Input:
    none
  Output:
    none
  Function value:
    INT              thread ID
\********************************************************************/
{
   /* if forced to single thread mode, simply return fake TID */
   if (_single_thread)
      return 1;
#ifdef OS_MSDOS
   return 0;
#endif                          /* OS_MSDOS */
#ifdef OS_WINNT
   return (int) GetCurrentThreadId();
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   return ss_getpid();
#endif                          /* OS_VMS */
#ifdef OS_UNIX
   return ss_getpid();
#endif                          /* OS_UNIX */
#ifdef OS_VXWORKS
   return ss_getpid();
#endif                          /* OS_VXWORKS */
}
INT EXPRT ss_mutex_create (char * mutex_name, HNDLE * mutex_handle)
Definition at line 1818 of file system.c.
References cm_get_path(), cm_msg, FALSE, file_name, key, MERROR, SS_CREATED, SS_NO_MUTEX, SS_SUCCESS, status, and ushort.
Referenced by bm_open_buffer(), cm_connect_experiment1(), db_open_database(), dm_buffer_create(), main(), and rpc_server_thread().
         : ss_mutex_create
  Purpose: Create a mutex with a specific name
    Remark: Under VxWorks the specific semaphore handling is
            different than other OS. But VxWorks provides
            the POSIX-compatible semaphore interface.
            Under POSIX, no timeout is supported.
            So for the time being, we keep the pure VxWorks
            The semaphore type is a Binary instead of mutex
            as the binary is an optimized mutex.
  Input:
    char   *name            Name of the mutex to create
  Output:
    HNDLE  *mutex_handle    Handle of the created mutex
  Function value:
    SS_CREATED              Mutex was created
    SS_SUCCESS              Mutex existed already and was attached
    SS_NO_MUTEX             Cannot create mutex
\********************************************************************/
{
   char mutex_name[256], path[256], file_name[256];
   /* Add a leading SM_ to the mutex name */
   sprintf(mutex_name, "MX_%s", name);
#ifdef OS_VXWORKS
   /* semBCreate is a Binary semaphore which is under VxWorks a optimized mutex
      refering to the programmer's Guide 5.3.1 */
   if ((*((SEM_ID *) mutex_handle) = semBCreate(SEM_Q_FIFO, SEM_EMPTY)) == NULL)
      return SS_NO_MUTEX;
   return SS_CREATED;
#endif                          /* OS_VXWORKS */
   /* Build the filename out of the path and the name of the mutex */
   cm_get_path(path);
   if (path[0] == 0) {
      getcwd(path, 256);
#if defined(OS_VMS)
#elif defined(OS_UNIX)
      strcat(path, "/");
#elif defined(OS_WINNT)
      strcat(path, "\\");
#endif
   }
   strcpy(file_name, path);
#if defined (OS_UNIX)
   strcat(file_name, ".");      /* dot file under UNIX */
#endif
   strcat(file_name, name);
   strcat(file_name, ".SHM");
#ifdef OS_WINNT
   *mutex_handle = (HNDLE) CreateMutex(NULL, FALSE, mutex_name);
   if (*mutex_handle == 0)
      return SS_NO_MUTEX;
   return SS_CREATED;
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   /* VMS has to use lock manager... */
   {
      INT status;
      $DESCRIPTOR(mutexname_dsc, "dummy");
      mutexname_dsc.dsc$w_length = strlen(mutex_name);
      mutexname_dsc.dsc$a_pointer = mutex_name;
      *mutex_handle = (HNDLE) malloc(8);
      status = sys$enqw(0, LCK$K_NLMODE, *mutex_handle, 0, &mutexname_dsc,
                        0, 0, 0, 0, 0, 0);
      if (status != SS$_NORMAL) {
         free((void *) *mutex_handle);
         *mutex_handle = 0;
      }
      if (*mutex_handle == 0)
         return SS_NO_MUTEX;
      return SS_CREATED;
   }
#endif                          /* OS_VMS */
#ifdef OS_UNIX
   {
      INT key, status, fh;
      struct semid_ds buf;
#if (defined(OS_LINUX) && !defined(_SEM_SEMUN_UNDEFINED)) || defined(OS_FREEBSD)
      union semun arg;
#else
      union semun {
         INT val;
         struct semid_ds *buf;
         ushort *array;
      } arg;
#endif
      status = SS_SUCCESS;
      /* create a unique key from the file name */
      key = ftok(file_name, 'M');
      if (key < 0) {
         fh = open(file_name, O_CREAT, 0644);
         close(fh);
         key = ftok(file_name, 'M');
         status = SS_CREATED;
      }
      /* create or get semaphore */
      *mutex_handle = (HNDLE) semget(key, 1, 0);
      if (*mutex_handle < 0) {
         *mutex_handle = (HNDLE) semget(key, 1, IPC_CREAT);
         status = SS_CREATED;
      }
      if (*mutex_handle < 0) {
         cm_msg(MERROR, "ss_mutex_mutex", "semget() failed, errno = %d", errno);
         return SS_NO_MUTEX;
      }
      buf.sem_perm.uid = getuid();
      buf.sem_perm.gid = getgid();
      buf.sem_perm.mode = 0666;
      arg.buf = &buf;
      semctl(*mutex_handle, 0, IPC_SET, arg);
      /* if semaphore was created, set value to one */
      if (status == SS_CREATED) {
         arg.val = 1;
         if (semctl(*mutex_handle, 0, SETVAL, arg) < 0)
            return SS_NO_MUTEX;
      }
      return SS_SUCCESS;
   }
#endif                          /* OS_UNIX */
#ifdef OS_MSDOS
   return SS_NO_MUTEX;
#endif
}
INT EXPRT ss_mutex_delete (HNDLE mutex_handle, INT destroy_flag)
Definition at line 2177 of file system.c.
References buf, FALSE, SS_NO_MUTEX, SS_SUCCESS, and ushort.
Referenced by bm_close_buffer(), db_close_database(), and dm_buffer_release().
         : ss_mutex_delete
  Purpose: Delete a mutex
  Input:
    HNDLE  *mutex_handle    Handle of the created mutex
  Output:
    none
  Function value:
    SS_SUCCESS              Successful completion
    SS_NO_MUTEX             Invalid mutex handle
\********************************************************************/
{
#ifdef OS_WINNT
   if (CloseHandle((HANDLE) mutex_handle) == FALSE)
      return SS_NO_MUTEX;
   return SS_SUCCESS;
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   free((void *) mutex_handle);
   return SS_SUCCESS;
#endif                          /* OS_VMS */
#ifdef OS_VXWORKS
   /* no code for VxWorks destroy yet */
   if (semDelete((SEM_ID) mutex_handle) == ERROR)
      return SS_NO_MUTEX;
   return SS_SUCCESS;
#endif                          /* OS_VXWORKS */
#ifdef OS_UNIX
#if (defined(OS_LINUX) && !defined(_SEM_SEMUN_UNDEFINED)) || defined(OS_FREEBSD)
   union semun arg;
#else
   union semun {
      INT val;
      struct semid_ds *buf;
      ushort *array;
   } arg;
#endif
   memset(&arg, 0, sizeof(arg));
   if (destroy_flag)
      if (semctl(mutex_handle, 0, IPC_RMID, arg) < 0)
         return SS_NO_MUTEX;
   return SS_SUCCESS;
#endif                          /* OS_UNIX */
#ifdef OS_MSDOS
   return SS_NO_MUTEX;
#endif
}
INT EXPRT ss_mutex_release (HNDLE mutex_handle)
Definition at line 2091 of file system.c.
References FALSE, SS_NO_MUTEX, SS_SUCCESS, and status.
Referenced by al_check(), bm_unlock_buffer(), db_unlock_database(), dm_area_flush(), dm_area_send(), dm_buffer_release(), dm_task(), el_delete_message(), el_submit(), and lazy_main().
         : ss_release_mutex
  Purpose: Release ownership of a mutex
  Input:
    HNDLE  *mutex_handle    Handle of the created mutex
  Output:
    none
  Function value:
    SS_SUCCESS              Successful completion
    SS_NO_MUTEX             Invalid mutex handle
\********************************************************************/
{
   INT status;
#ifdef OS_WINNT
   status = ReleaseMutex((HANDLE) mutex_handle);
   if (status == FALSE)
      return SS_NO_MUTEX;
   return SS_SUCCESS;
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   status = sys$enqw(0, LCK$K_NLMODE, mutex_handle, LCK$M_CONVERT, 0, 0, 0, 0, 0, 0, 0);
   if (status != SS$_NORMAL)
      return SS_NO_MUTEX;
   return SS_SUCCESS;
#endif                          /* OS_VMS */
#ifdef OS_VXWORKS
   if (semGive((SEM_ID) mutex_handle) == ERROR)
      return SS_NO_MUTEX;
   return SS_SUCCESS;
#endif                          /* OS_VXWORKS */
#ifdef OS_UNIX
   {
      struct sembuf sb;
      sb.sem_num = 0;
      sb.sem_op = 1;            /* increment semaphore */
      sb.sem_flg = SEM_UNDO;
      if (mutex_handle == skip_mutex_handle) {
         skip_mutex_handle = -1;
         return SS_SUCCESS;
      }
      do {
         status = semop(mutex_handle, &sb, 1);
         /* return on success */
         if (status == 0)
            break;
         /* retry if interrupted by a ss_wake signal */
         if (errno == EINTR)
            continue;
         return SS_NO_MUTEX;
      } while (1);
      return SS_SUCCESS;
   }
#endif                          /* OS_UNIX */
#ifdef OS_MSDOS
   return SS_NO_MUTEX;
#endif
}
INT EXPRT ss_mutex_wait_for (HNDLE mutex_handle, INT timeout)
Definition at line 1980 of file system.c.
References buf, ss_in_async_routine_flag, ss_millitime(), SS_NO_MUTEX, SS_SUCCESS, SS_TIMEOUT, start_time, status, and ushort.
Referenced by al_check(), bm_lock_buffer(), db_lock_database(), dm_area_flush(), dm_area_send(), dm_buffer_create(), dm_task(), el_delete_message(), el_submit(), and lazy_main().
         : ss_mutex_wait_for
  Purpose: Wait for a mutex to get owned
  Input:
    HNDLE  *mutex_handle    Handle of the created mutex
    INT    timeout          Timeout in ms, zero for no timeout
  Output:
    none
  Function value:
    SS_SUCCESS              Successful completion
    SS_NO_MUTEX             Invalid mutex handle
    SS_TIMEOUT              Timeout
\********************************************************************/
{
   INT status;
#ifdef OS_WINNT
   status = WaitForSingleObject((HANDLE) mutex_handle, timeout == 0 ? INFINITE : timeout);
   if (status == WAIT_FAILED)
      return SS_NO_MUTEX;
   if (status == WAIT_TIMEOUT)
      return SS_TIMEOUT;
   return SS_SUCCESS;
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   status = sys$enqw(0, LCK$K_EXMODE, mutex_handle, LCK$M_CONVERT, 0, 0, 0, 0, 0, 0, 0);
   if (status != SS$_NORMAL)
      return SS_NO_MUTEX;
   return SS_SUCCESS;
#endif                          /* OS_VMS */
#ifdef OS_VXWORKS
   /* convert timeout in ticks (1/60) = 1000/60 ~ 1/16 = >>4 */
   status = semTake((SEM_ID) mutex_handle, timeout == 0 ? WAIT_FOREVER : timeout >> 4);
   if (status == ERROR)
      return SS_NO_MUTEX;
   return SS_SUCCESS;
#endif                          /* OS_VXWORKS */
#ifdef OS_UNIX
   {
      DWORD start_time;
      struct sembuf sb;
#if (defined(OS_LINUX) && !defined(_SEM_SEMUN_UNDEFINED)) || defined(OS_FREEBSD)
      union semun arg;
#else
      union semun {
         INT val;
         struct semid_ds *buf;
         ushort *array;
      } arg;
#endif
      sb.sem_num = 0;
      sb.sem_op = -1;           /* decrement semaphore */
      sb.sem_flg = SEM_UNDO;
      memset(&arg, 0, sizeof(arg));
      /* don't request the mutex when in asynchronous state
         and mutex was locked already by foreground process */
      if (ss_in_async_routine_flag)
         if (semctl(mutex_handle, 0, GETPID, arg) == getpid())
            if (semctl(mutex_handle, 0, GETVAL, arg) == 0) {
               skip_mutex_handle = mutex_handle;
               return SS_SUCCESS;
            }
      skip_mutex_handle = -1;
      start_time = ss_millitime();
      do {
         status = semop(mutex_handle, &sb, 1);
         /* return on success */
         if (status == 0)
            break;
         /* retry if interrupted by a ss_wake signal */
         if (errno == EINTR) {
            /* return if timeout expired */
            if (timeout > 0 && ss_millitime() - start_time > timeout)
               return SS_TIMEOUT;
            continue;
         }
         return SS_NO_MUTEX;
      } while (1);
      return SS_SUCCESS;
   }
#endif                          /* OS_UNIX */
#ifdef OS_MSDOS
   return SS_NO_MUTEX;
#endif
}
INT ss_resume (INT port, char * message)
Definition at line 3549 of file system.c.
References SUSPEND_STRUCT::bind_addr, index, ss_in_async_routine_flag, SS_SOCKET_ERROR, SS_SUCCESS, ss_suspend_get_index(), and status.
Referenced by bm_close_buffer(), bm_flush_cache(), bm_push_event(), bm_receive_event(), bm_send_event(), cm_cleanup(), cm_watchdog(), and db_notify_clients().
         : ss_resume
  Purpose: Resume another thread or process which called ss_suspend.
     The port has to be transfered (shared memory or so) from
     the thread or process which should be resumed. In that
     process it can be obtained via ss_suspend_get_port.
  Input:
    INT    port             UDP port number
    INT    msg              Mesage id & parameter transferred to
    INT    param              target process
  Output:
    none
  Function value:
    SS_SUCCESS              Successful completion
    SS_SOCKET_ERROR         Socket error
\********************************************************************/
{
   INT status, index;
   if (ss_in_async_routine_flag) {
      /* if called from watchdog, tid is different under NT! */
      index = 0;
   } else {
      status = ss_suspend_get_index(&index);
      if (status != SS_SUCCESS)
         return status;
   }
   _suspend_struct[index].bind_addr.sin_port = htons((short) port);
   status = sendto(_suspend_struct[index].ipc_send_socket, message,
                   strlen(message) + 1, 0,
                   (struct sockaddr *) &_suspend_struct[index].bind_addr,
                   sizeof(struct sockaddr_in));
   if (status != (INT) strlen(message) + 1)
      return SS_SOCKET_ERROR;
   return SS_SUCCESS;
}
INT ss_set_async_flag (INT flag)
Definition at line 351 of file system.c.
References ss_in_async_routine_flag.
Referenced by cm_watchdog().
         : ss_set_async_flag
  Purpose: Sets the ss_in_async_routine_flag according to the flag
     value. This is necessary when semaphore operations under
     UNIX are called inside an asynchrounous routine (via alarm)
     because they then behave different.
  Input:
    INT  flag               May be 1 or 0
  Output:
    none
  Function value:
    INT                     Previous value of the flag
\********************************************************************/
{
   INT old_flag;
   old_flag = ss_in_async_routine_flag;
   ss_in_async_routine_flag = flag;
   return old_flag;
}
INT ss_shell (int sock)
Definition at line 1232 of file system.c.
References buffer, cmd, FALSE, FD_SETSIZE, i, read, send(), SS_SUCCESS, strlcpy(), TRUE, and write.
Referenced by rpc_server_accept().
         : ss_shell
  Purpose: Execute shell via socket (like telnetd)
  Input:
    int  sock        Socket
  Output:
    none
  Function value:
    SS_SUCCESS       Successful completeion
\********************************************************************/
{
#ifdef OS_WINNT
   HANDLE hChildStdinRd, hChildStdinWr, hChildStdinWrDup,
       hChildStdoutRd, hChildStdoutWr,
       hChildStderrRd, hChildStderrWr, hSaveStdin, hSaveStdout, hSaveStderr;
   SECURITY_ATTRIBUTES saAttr;
   PROCESS_INFORMATION piProcInfo;
   STARTUPINFO siStartInfo;
   char buffer[256], cmd[256];
   DWORD dwRead, dwWritten, dwAvail, i, i_cmd;
   fd_set readfds;
   struct timeval timeout;
   /* Set the bInheritHandle flag so pipe handles are inherited. */
   saAttr.nLength = sizeof(SECURITY_ATTRIBUTES);
   saAttr.bInheritHandle = TRUE;
   saAttr.lpSecurityDescriptor = NULL;
   /* Save the handle to the current STDOUT. */
   hSaveStdout = GetStdHandle(STD_OUTPUT_HANDLE);
   /* Create a pipe for the child's STDOUT. */
   if (!CreatePipe(&hChildStdoutRd, &hChildStdoutWr, &saAttr, 0))
      return 0;
   /* Set a write handle to the pipe to be STDOUT. */
   if (!SetStdHandle(STD_OUTPUT_HANDLE, hChildStdoutWr))
      return 0;
   /* Save the handle to the current STDERR. */
   hSaveStderr = GetStdHandle(STD_ERROR_HANDLE);
   /* Create a pipe for the child's STDERR. */
   if (!CreatePipe(&hChildStderrRd, &hChildStderrWr, &saAttr, 0))
      return 0;
   /* Set a read handle to the pipe to be STDERR. */
   if (!SetStdHandle(STD_ERROR_HANDLE, hChildStderrWr))
      return 0;
   /* Save the handle to the current STDIN. */
   hSaveStdin = GetStdHandle(STD_INPUT_HANDLE);
   /* Create a pipe for the child's STDIN. */
   if (!CreatePipe(&hChildStdinRd, &hChildStdinWr, &saAttr, 0))
      return 0;
   /* Set a read handle to the pipe to be STDIN. */
   if (!SetStdHandle(STD_INPUT_HANDLE, hChildStdinRd))
      return 0;
   /* Duplicate the write handle to the pipe so it is not inherited. */
   if (!DuplicateHandle(GetCurrentProcess(), hChildStdinWr, GetCurrentProcess(), &hChildStdinWrDup, 0, FALSE,   /* not inherited */
                        DUPLICATE_SAME_ACCESS))
      return 0;
   CloseHandle(hChildStdinWr);
   /* Now create the child process. */
   memset(&siStartInfo, 0, sizeof(siStartInfo));
   siStartInfo.cb = sizeof(STARTUPINFO);
   siStartInfo.lpReserved = NULL;
   siStartInfo.lpReserved2 = NULL;
   siStartInfo.cbReserved2 = 0;
   siStartInfo.lpDesktop = NULL;
   siStartInfo.dwFlags = 0;
   if (!CreateProcess(NULL, "cmd /Q",   /* command line */
                      NULL,     /* process security attributes */
                      NULL,     /* primary thread security attributes */
                      TRUE,     /* handles are inherited */
                      0,        /* creation flags */
                      NULL,     /* use parent's environment */
                      NULL,     /* use parent's current directory */
                      &siStartInfo,     /* STARTUPINFO pointer */
                      &piProcInfo))     /* receives PROCESS_INFORMATION */
      return 0;
   /* After process creation, restore the saved STDIN and STDOUT. */
   SetStdHandle(STD_INPUT_HANDLE, hSaveStdin);
   SetStdHandle(STD_OUTPUT_HANDLE, hSaveStdout);
   SetStdHandle(STD_ERROR_HANDLE, hSaveStderr);
   i_cmd = 0;
   do {
      /* query stderr */
      do {
         if (!PeekNamedPipe(hChildStderrRd, buffer, 256, &dwRead, &dwAvail, NULL))
            break;
         if (dwRead > 0) {
            ReadFile(hChildStderrRd, buffer, 256, &dwRead, NULL);
            send(sock, buffer, dwRead, 0);
         }
      } while (dwAvail > 0);
      /* query stdout */
      do {
         if (!PeekNamedPipe(hChildStdoutRd, buffer, 256, &dwRead, &dwAvail, NULL))
            break;
         if (dwRead > 0) {
            ReadFile(hChildStdoutRd, buffer, 256, &dwRead, NULL);
            send(sock, buffer, dwRead, 0);
         }
      } while (dwAvail > 0);
      /* check if subprocess still alive */
      if (!GetExitCodeProcess(piProcInfo.hProcess, &i))
         break;
      if (i != STILL_ACTIVE)
         break;
      /* query network socket */
      FD_ZERO(&readfds);
      FD_SET(sock, &readfds);
      timeout.tv_sec = 0;
      timeout.tv_usec = 100;
      select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
      if (FD_ISSET(sock, &readfds)) {
         i = recv(sock, cmd + i_cmd, 1, 0);
         if (i <= 0)
            break;
         /* backspace */
         if (cmd[i_cmd] == 8) {
            if (i_cmd > 0) {
               send(sock, "\b \b", 3, 0);
               i_cmd -= 1;
            }
         } else if (cmd[i_cmd] >= ' ' || cmd[i_cmd] == 13 || cmd[i_cmd] == 10) {
            send(sock, cmd + i_cmd, 1, 0);
            i_cmd += i;
         }
      }
      /* linefeed triggers new command */
      if (cmd[i_cmd - 1] == 10) {
         WriteFile(hChildStdinWrDup, cmd, i_cmd, &dwWritten, NULL);
         i_cmd = 0;
      }
   } while (TRUE);
   CloseHandle(hChildStdinWrDup);
   CloseHandle(hChildStdinRd);
   CloseHandle(hChildStderrRd);
   CloseHandle(hChildStdoutRd);
   return SS_SUCCESS;
#endif                          /* OS_WINNT */
#ifdef OS_UNIX
#ifndef NO_PTY
   pid_t pid;
   int i, pipe;
   char line[32], buffer[1024], shell[32];
   fd_set readfds;
   if ((pid = forkpty(&pipe, line, NULL, NULL)) < 0)
      return 0;
   else if (pid > 0) {
      /* parent process */
      do {
         FD_ZERO(&readfds);
         FD_SET(sock, &readfds);
         FD_SET(pipe, &readfds);
         select(FD_SETSIZE, (void *) &readfds, NULL, NULL, NULL);
         if (FD_ISSET(sock, &readfds)) {
            memset(buffer, 0, sizeof(buffer));
            i = recv(sock, buffer, sizeof(buffer), 0);
            if (i <= 0)
               break;
            if (write(pipe, buffer, i) != i)
               break;
         }
         if (FD_ISSET(pipe, &readfds)) {
            memset(buffer, 0, sizeof(buffer));
            i = read(pipe, buffer, sizeof(buffer));
            if (i <= 0)
               break;
            send(sock, buffer, i, 0);
         }
      } while (1);
   } else {
      /* child process */
      if (getenv("SHELL"))
         strlcpy(shell, getenv("SHELL"), sizeof(shell));
      else
         strcpy(shell, "/bin/sh");
      execl(shell, shell, 0);
   }
#else
   send(sock, "not implemented\n", 17, 0);
#endif                          /* NO_PTY */
   return SS_SUCCESS;
#endif                          /* OS_UNIX */
}
INT ss_shm_close (char * name, void * adr, HNDLE handle, INT destroy_flag)
Definition at line 609 of file system.c.
References cm_get_path(), cm_msg, disable_shm_write, file_name, MERROR, SS_INVALID_ADDRESS, SS_INVALID_HANDLE, and SS_SUCCESS.
Referenced by bm_close_buffer(), bm_open_buffer(), and db_close_database().
         : ss_shm_close
  Purpose: Close a shared memory region.
  Input:
    char *name              Name of the shared memory
    void *adr               Base address of shared memory
    HNDLE handle            Handle of shared memeory
    BOOL destroy            Shared memory has to be destroyd and
          flushed to the mapping file.
  Output:
    none
  Function value:
    SS_SUCCESS              Successful completion
    SS_INVALID_ADDRESS      Invalid base address
    SS_FILE_ERROR           Cannot write shared memory file
    SS_INVALID_HANDLE       Invalid shared memory handle
\********************************************************************/
{
   char mem_name[256], file_name[256], path[256];
   /*
      append a leading SM_ to the memory name to resolve name conflicts
      with mutex or semaphore names
    */
   sprintf(mem_name, "SM_%s", name);
   /* append .SHM and preceed the path for the shared memory file name */
   cm_get_path(path);
   if (path[0] == 0) {
      getcwd(path, 256);
#if defined(OS_VMS)
#elif defined(OS_UNIX)
      strcat(path, "/");
#elif defined(OS_WINNT)
      strcat(path, "\\");
#endif
   }
   strcpy(file_name, path);
#if defined (OS_UNIX)
   strcat(file_name, ".");      /* dot file under UNIX */
#endif
   strcat(file_name, name);
   strcat(file_name, ".SHM");
#ifdef OS_WINNT
   if (!UnmapViewOfFile(adr))
      return SS_INVALID_ADDRESS;
   CloseHandle((HANDLE) handle);
   return SS_SUCCESS;
#endif                          /* OS_WINNT */
#ifdef OS_VMS
/* outcommented because ppl$delete... makes privilege violation
  {
  int addr[2], flags, status;
  char mem_name[100];
  $DESCRIPTOR(memname_dsc, mem_name);
  strcpy(mem_name, "SM_");
  strcat(mem_name, name);
  memname_dsc.dsc$w_length = strlen(mem_name);
  flags = PPL$M_FLUSH | PPL$M_NOUNI;
  addr[0] = 0;
  addr[1] = adr;
  status = ppl$delete_shared_memory( &memname_dsc, addr, &flags);
  if (status == PPL$_NORMAL)
    return SS_SUCCESS;
  return SS_INVALID_ADDRESS;
  }
*/
   return SS_INVALID_ADDRESS;
#endif                          /* OS_VMS */
#ifdef OS_UNIX
   {
      struct shmid_ds buf;
      FILE *fh;
      /* get info about shared memory */
      if (shmctl(handle, IPC_STAT, &buf) < 0) {
         cm_msg(MERROR, "ss_shm_close", "shmctl(shmid=%d,IPC_STAT) failed, errno %d (%s)",handle,errno,strerror(errno));
         return SS_INVALID_HANDLE;
      }
      /* copy to file and destroy if we are the last one */
      if (buf.shm_nattch == 1) {
         if (!disable_shm_write) {
            fh = fopen(file_name, "w");
            if (fh == NULL) {
               cm_msg(MERROR, "ss_shm_close",
                      "Cannot write to file %s, please check protection", file_name);
            } else {
               /* write shared memory to file */
               fwrite(adr, 1, buf.shm_segsz, fh);
               fclose(fh);
            }
         }
         if (shmdt(adr) < 0) {
            cm_msg(MERROR, "ss_shm_close", "shmdt(shmid=%d) failed, errno %d (%s)",handle,errno,strerror(errno));
            return SS_INVALID_ADDRESS;
         }
         if (shmctl(handle, IPC_RMID, &buf) < 0) {
            cm_msg(MERROR, "ss_shm_close", "shmctl(shmid=%d,IPC_RMID) failed, errno %d (%s)",handle,errno,strerror(errno));
            return SS_INVALID_ADDRESS;
         }
      } else
         /* only detach if we are not the last */
      if (shmdt(adr) < 0) {
         cm_msg(MERROR, "ss_shm_close", "shmdt(shmid=%d) failed, errno %d (%s)",handle,errno,strerror(errno));
         return SS_INVALID_ADDRESS;
      }
      return SS_SUCCESS;
   }
#endif                          /* OS_UNIX */
}
INT ss_shm_flush (char * name, void * adr, INT size)
Definition at line 830 of file system.c.
References cm_get_path(), cm_msg, disable_shm_write, file_name, MERROR, SS_INVALID_ADDRESS, and SS_SUCCESS.
Referenced by db_close_database(), and db_flush_database().
         : ss_shm_flush
  Purpose: Flush a shared memory region to its disk file.
  Input:
    char *name              Name of the shared memory
    void *adr               Base address of shared memory
    INT  size               Size of shared memeory
  Output:
    none
  Function value:
    SS_SUCCESS              Successful completion
    SS_INVALID_ADDRESS      Invalid base address
\********************************************************************/
{
   char mem_name[256], file_name[256], path[256];
   /*
      append a leading SM_ to the memory name to resolve name conflicts
      with mutex or semaphore names
    */
   sprintf(mem_name, "SM_%s", name);
   /* append .SHM and preceed the path for the shared memory file name */
   cm_get_path(path);
   if (path[0] == 0) {
      getcwd(path, 256);
#if defined(OS_VMS)
#elif defined(OS_UNIX)
      strcat(path, "/");
#elif defined(OS_WINNT)
      strcat(path, "\\");
#endif
   }
   strcpy(file_name, path);
#if defined (OS_UNIX)
   strcat(file_name, ".");      /* dot file under UNIX */
#endif
   strcat(file_name, name);
   strcat(file_name, ".SHM");
#ifdef OS_WINNT
   if (!FlushViewOfFile(adr, size))
      return SS_INVALID_ADDRESS;
   return SS_SUCCESS;
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   return SS_SUCCESS;
#endif                          /* OS_VMS */
#ifdef OS_UNIX
   if (!disable_shm_write) {
      FILE *fh;
      fh = fopen(file_name, "w");
      if (fh == NULL) {
         cm_msg(MERROR, "ss_shm_flush",
                "Cannot write to file %s, please check protection", file_name);
      } else {
         /* write shared memory to file */
         fwrite(adr, 1, size, fh);
         fclose(fh);
      }
   }
   return SS_SUCCESS;
#endif                          /* OS_UNIX */
}
INT ss_shm_open (char * name, INT size, void ** adr, HNDLE * handle)
Definition at line 380 of file system.c.
References addr, cm_get_path(), cm_msg, FALSE, file_name, key, MERROR, O_BINARY, p, read, SS_CREATED, SS_FILE_ERROR, ss_file_size(), SS_NO_MEMORY, SS_SUCCESS, and status.
Referenced by bm_open_buffer(), and db_open_database().
         : ss_shm_open
  Purpose: Create a shared memory region which can be seen by several
     processes which know the name.
  Input:
    char *name              Name of the shared memory
    INT  size               Initial size of the shared memory in bytes
                            if .SHM file doesn't exist
  Output:
    void  *adr              Address of opened shared memory
    HNDLE handle            Handle or key to the shared memory
  Function value:
    SS_SUCCESS              Successful completion
    SS_CREATED              Shared memory was created
    SS_FILE_ERROR           Paging file cannot be created
    SS_NO_MEMORY            Not enough memory
\********************************************************************/
{
   INT status;
   char mem_name[256], file_name[256], path[256];
   /* Add a leading SM_ to the memory name */
   sprintf(mem_name, "SM_%s", name);
   /* Build the filename out of the path, and the name of the shared memory. */
   cm_get_path(path);
   if (path[0] == 0) {
      getcwd(path, 256);
#if defined(OS_VMS)
#elif defined(OS_UNIX)
      strcat(path, "/");
#elif defined(OS_WINNT)
      strcat(path, "\\");
#endif
   }
   strcpy(file_name, path);
#if defined (OS_UNIX)
   strcat(file_name, ".");      /* dot file under UNIX */
#endif
   strcat(file_name, name);
   strcat(file_name, ".SHM");
#ifdef OS_WINNT
   status = SS_SUCCESS;
   {
      HANDLE hFile, hMap;
      char str[256], *p;
      DWORD file_size;
      /* make the memory name unique using the pathname. This is necessary
         because NT doesn't use ftok. So if different experiments are
         running in different directories, they should not see the same
         shared memory */
      strcpy(str, path);
      /* replace special chars by '*' */
      while (strpbrk(str, "\\: "))
         *strpbrk(str, "\\: ") = '*';
      strcat(str, mem_name);
      /* convert to uppercase */
      p = str;
      while (*p)
         *p++ = (char) toupper(*p);
      hMap = OpenFileMapping(FILE_MAP_ALL_ACCESS, FALSE, str);
      if (hMap == 0) {
         hFile = CreateFile(file_name, GENERIC_READ | GENERIC_WRITE,
                            FILE_SHARE_READ | FILE_SHARE_WRITE, NULL,
                            OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, 0);
         if (!hFile) {
            cm_msg(MERROR, "ss_shm_open", "CreateFile() failed");
            return SS_FILE_ERROR;
         }
         file_size = GetFileSize(hFile, NULL);
         if (file_size != 0xFFFFFFFF && file_size > 0)
            size = file_size;
         hMap = CreateFileMapping(hFile, NULL, PAGE_READWRITE, 0, size, str);
         if (!hMap) {
            status = GetLastError();
            cm_msg(MERROR, "ss_shm_open", "CreateFileMapping() failed, error %d", status);
            return SS_FILE_ERROR;
         }
         CloseHandle(hFile);
         status = SS_CREATED;
      }
      *adr = MapViewOfFile(hMap, FILE_MAP_ALL_ACCESS, 0, 0, 0);
      *handle = (HNDLE) hMap;
      if (adr == NULL) {
         cm_msg(MERROR, "ss_shm_open", "MapViewOfFile() failed");
         return SS_NO_MEMORY;
      }
      return status;
   }
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   status = SS_SUCCESS;
   {
      int addr[2];
      $DESCRIPTOR(memname_dsc, "dummy");
      $DESCRIPTOR(filename_dsc, "dummy");
      memname_dsc.dsc$w_length = strlen(mem_name);
      memname_dsc.dsc$a_pointer = mem_name;
      filename_dsc.dsc$w_length = strlen(file_name);
      filename_dsc.dsc$a_pointer = file_name;
      addr[0] = size;
      addr[1] = 0;
      status = ppl$create_shared_memory(&memname_dsc, addr, &PPL$M_NOUNI, &filename_dsc);
      if (status == PPL$_CREATED)
         status = SS_CREATED;
      else if (status != PPL$_NORMAL)
         status = SS_FILE_ERROR;
      *adr = (void *) addr[1];
      *handle = 0;              /* not used under VMS */
      if (adr == NULL)
         return SS_NO_MEMORY;
      return status;
   }
#endif                          /* OS_VMS */
#ifdef OS_UNIX
   status = SS_SUCCESS;
   {
      int key, shmid, fh, file_size;
      struct shmid_ds buf;
      /* create a unique key from the file name */
      key = ftok(file_name, 'M');
      /* if file doesn't exist, create it */
      if (key == -1) {
         fh = open(file_name, O_CREAT | O_TRUNC | O_BINARY, 0644);
         close(fh);
         key = ftok(file_name, 'M');
         if (key == -1) {
            cm_msg(MERROR, "ss_shm_open", "ftok() failed");
            return SS_FILE_ERROR;
         }
         status = SS_CREATED;
         /* delete any previously created memory */
         shmid = shmget(key, 0, 0);
         shmctl(shmid, IPC_RMID, &buf);
      } else {
         /* if file exists, retrieve its size */
         file_size = (INT) ss_file_size(file_name);
         if (file_size > 0)
            size = file_size;
      }
      /* get the shared memory, create if not existing */
      shmid = shmget(key, size, 0);
      if (shmid == -1) {
         //cm_msg(MINFO, "ss_shm_open", "Creating shared memory segment, key: 0x%x, size: %d",key,size);
         shmid = shmget(key, size, IPC_CREAT|IPC_EXCL);
         if (shmid == -1 && errno == EEXIST)
           {
             cm_msg(MERROR, "ss_shm_open", "Shared memory segment with key 0x%x already exists, please remove it manually: ipcrm -M 0x%x",key,key);
             return SS_NO_MEMORY;
           }
         status = SS_CREATED;
      }
      if (shmid == -1) {
         cm_msg(MERROR, "ss_shm_open", "shmget(key=0x%x,size=%d) failed, errno %d (%s)", key, size, errno, strerror(errno));
         return SS_NO_MEMORY;
      }
      buf.shm_perm.uid = getuid();
      buf.shm_perm.gid = getgid();
      buf.shm_perm.mode = 0666;
      shmctl(shmid, IPC_SET, &buf);
      *adr = shmat(shmid, 0, 0);
      *handle = (HNDLE) shmid;
      if ((*adr) == (void *) (-1)) {
         cm_msg(MERROR, "ss_shm_open","shmat(shmid=%d) failed, errno %d (%s)", shmid, errno, strerror(errno));
         return SS_NO_MEMORY;
      }
      /* if shared memory was created, try to load it from file */
      if (status == SS_CREATED) {
         fh = open(file_name, O_RDONLY, 0644);
         if (fh == -1)
            fh = open(file_name, O_CREAT | O_RDWR, 0644);
         else
            read(fh, *adr, size);
         close(fh);
      }
      return status;
   }
#endif                          /* OS_UNIX */
}
INT ss_shm_protect (HNDLE handle, void * adr)
Definition at line 748 of file system.c.
References cm_msg, MERROR, SS_INVALID_ADDRESS, and SS_SUCCESS.
Referenced by db_protect_database(), and db_unlock_database().
         : ss_shm_protect
  Purpose: Protect a shared memory region, disallow read and write
           access to it by this process
  Input:
    HNDLE handle            Handle of shared memeory
    void  *adr              Address of shared memory
  Output:
    none
  Function value:
    SS_SUCCESS              Successful completion
    SS_INVALID_ADDRESS      Invalid base address
\********************************************************************/
{
#ifdef OS_WINNT
   if (!UnmapViewOfFile(adr))
      return SS_INVALID_ADDRESS;
#endif                          /* OS_WINNT */
#ifdef OS_UNIX
   if (shmdt(adr) < 0) {
      cm_msg(MERROR, "ss_shm_protect", "shmdt() failed");
      return SS_INVALID_ADDRESS;
   }
#endif                          /* OS_UNIX */
   return SS_SUCCESS;
}
INT ss_shm_unprotect (HNDLE handle, void ** adr)
Definition at line 786 of file system.c.
References cm_msg, MERROR, SS_NO_MEMORY, and SS_SUCCESS.
Referenced by db_lock_database().
         : ss_shm_unprotect
  Purpose: Unprotect a shared memory region so that it can be accessed
           by this process
  Input:
    HNDLE handle            Handle or key to the shared memory, must
                            be obtained with ss_shm_open
  Output:
    void  *adr              Address of opened shared memory
  Function value:
    SS_SUCCESS              Successful completion
    SS_NO_MEMORY            Memory mapping failed
\********************************************************************/
{
#ifdef OS_WINNT
   *adr = MapViewOfFile((HANDLE) handle, FILE_MAP_ALL_ACCESS, 0, 0, 0);
   if (*adr == NULL) {
      cm_msg(MERROR, "ss_shm_unprotect", "MapViewOfFile() failed");
      return SS_NO_MEMORY;
   }
#endif                          /* OS_WINNT */
#ifdef OS_UNIX
   *adr = shmat(handle, 0, 0);
   if ((*adr) == (void *) (-1)) {
      cm_msg(MERROR, "ss_shm_unprotect", "shmat() failed, errno = %d", errno);
      return SS_NO_MEMORY;
   }
#endif                          /* OS_UNIX */
   return SS_SUCCESS;
}
INT ss_spawnv (INT mode, char * cmdname, char * argv[])
Definition at line 1111 of file system.c.
References BM_SUCCESS, i, SS_INVALID_NAME, SS_SUCCESS, status, and wait.
Referenced by rpc_server_accept().
         : ss_spawnv
  Purpose: Spawn a subprocess or detached process
  Input:
    INT mode         One of the following modes:
           P_WAIT     Wait for the subprocess to compl.
           P_NOWAIT   Don't wait for subprocess to compl.
           P_DETACH   Create detached process.
    char cmdname     Program name to execute
    char *argv[]     Optional program arguments
  Output:
    none
  Function value:
    SS_SUCCESS       Successful completeion
    SS_INVALID_NAME  Command could not be executed;
\********************************************************************/
{
#ifdef OS_WINNT
   if (spawnvp(mode, cmdname, argv) < 0)
      return SS_INVALID_NAME;
   return SS_SUCCESS;
#endif                          /* OS_WINNT */
#ifdef OS_MSDOS
   spawnvp((int) mode, cmdname, argv);
   return SS_SUCCESS;
#endif                          /* OS_MSDOS */
#ifdef OS_VMS
   {
      char cmdstring[500], *pc;
      INT i, flags, status;
      va_list argptr;
      $DESCRIPTOR(cmdstring_dsc, "dummy");
      if (mode & P_DETACH) {
         cmdstring_dsc.dsc$w_length = strlen(cmdstring);
         cmdstring_dsc.dsc$a_pointer = cmdstring;
         status = sys$creprc(0, &cmdstring_dsc,
                             0, 0, 0, 0, 0, NULL, 4, 0, 0, PRC$M_DETACH);
      } else {
         flags = (mode & P_NOWAIT) ? 1 : 0;
         for (pc = argv[0] + strlen(argv[0]); *pc != ']' && pc != argv[0]; pc--);
         if (*pc == ']')
            pc++;
         strcpy(cmdstring, pc);
         if (strchr(cmdstring, ';'))
            *strchr(cmdstring, ';') = 0;
         strcat(cmdstring, " ");
         for (i = 1; argv[i] != NULL; i++) {
            strcat(cmdstring, argv[i]);
            strcat(cmdstring, " ");
         }
         cmdstring_dsc.dsc$w_length = strlen(cmdstring);
         cmdstring_dsc.dsc$a_pointer = cmdstring;
         status = lib$spawn(&cmdstring_dsc, 0, 0, &flags, NULL, 0, 0, 0, 0, 0, 0, 0, 0);
      }
      return BM_SUCCESS;
   }
#endif                          /* OS_VMS */
#ifdef OS_UNIX
   pid_t child_pid;
#ifdef OS_ULTRIX
   union wait *status;
#else
   int status;
#endif
   if ((child_pid = fork()) < 0)
      return (-1);
   if (child_pid == 0) {
      /* now we are in the child process ... */
      child_pid = execvp(cmdname, argv);
      return SS_SUCCESS;
   } else {
      /* still in parent process */
      if (mode == P_WAIT)
#ifdef OS_ULTRIX
         waitpid(child_pid, status, WNOHANG);
#else
         waitpid(child_pid, &status, WNOHANG);
#endif
      else
         /* catch SIGCHLD signal to avoid <defunc> processes */
         signal(SIGCHLD, catch_sigchld);
   }
   return SS_SUCCESS;
#endif                          /* OS_UNIX */
}
INT EXPRT ss_suspend (INT millisec, INT msg)
Definition at line 3283 of file system.c.
References buffer, SUSPEND_STRUCT::client_dispatch, closesocket, cm_msg, RPC_SERVER_ACCEPTION::event_sock, FD_SETSIZE, index, SUSPEND_STRUCT::ipc_dispatch, SUSPEND_STRUCT::listen_dispatch, SUSPEND_STRUCT::listen_socket, MAX_RPC_CONNECTION, MINFO, MSG_BM, MSG_ODB, recv_event_check(), RPC_SERVER_CONNECTION::recv_sock, RPC_SERVER_ACCEPTION::recv_sock, recv_tcp(), recv_tcp_check(), rpc_get_server_option(), RPC_OSERVER_TYPE, RPC_SHUTDOWN, RPC_SERVER_ACCEPTION::send_sock, SUSPEND_STRUCT::server_acception, SUSPEND_STRUCT::server_connection, SUSPEND_STRUCT::server_dispatch, size, SS_ABORT, SS_CLIENT_RECV, SS_EXIT, ss_gettid(), ss_millitime(), SS_SERVER_RECV, SS_SUCCESS, ss_suspend_get_index(), SS_TIMEOUT, ST_REMOTE, status, and WATCHDOG_INTERVAL.
Referenced by bm_flush_cache(), bm_receive_event(), bm_send_event(), cm_yield(), main(), and rpc_server_thread().
         : ss_suspend
  Purpose: Suspend the calling thread for a speficic time. If
     timeout (in millisec.) is negative, the thead is suspended
     indefinitely. It can only be resumed from another thread
     or process which calls ss_resume or by some data which
     arrives on the client or server sockets.
     If msg equals to one of MSG_BM, MSG_ODB, the function
     return whenever such a message is received.
  Input:
    INT    millisec         Timeout in milliseconds
    INT    msg              Return from ss_suspend when msg
          (MSG_BM, MSG_ODB) is received.
  Output:
    none
  Function value:
    SS_SUCCESS              Requested message was received
    SS_TIMEOUT              Timeout expired
    SS_SERVER_RECV          Server channel got data
    SS_CLIENT_RECV          Client channel got data
    SS_ABORT (RPC_ABORT)    Connection lost
    SS_EXIT                 Connection closed
\********************************************************************/
{
   fd_set readfds;
   struct timeval timeout;
   INT sock, server_socket;
   INT index, status, i, return_status;
   int size;
   struct sockaddr from_addr;
   char str[100], buffer[80], buffer_tmp[80];
   /* get index to _suspend_struct for this thread */
   status = ss_suspend_get_index(&index);
   if (status != SS_SUCCESS)
      return status;
   return_status = SS_TIMEOUT;
   do {
      FD_ZERO(&readfds);
      /* check listen socket */
      if (_suspend_struct[index].listen_socket)
         FD_SET(_suspend_struct[index].listen_socket, &readfds);
      /* check server channels */
      if (_suspend_struct[index].server_acception)
         for (i = 0; i < MAX_RPC_CONNECTION; i++) {
            /* RPC channel */
            sock = _suspend_struct[index].server_acception[i].recv_sock;
            /* only watch the event tcp connection belonging to this thread */
            if (!sock || _suspend_struct[index].server_acception[i].tid != ss_gettid())
               continue;
            /* watch server socket if no data in cache */
            if (recv_tcp_check(sock) == 0)
               FD_SET(sock, &readfds);
            /* set timeout to zero if data in cache (-> just quick check IPC)
               and not called from inside bm_send_event (-> wait for IPC) */
            else if (msg == 0)
               millisec = 0;
            /* event channel */
            sock = _suspend_struct[index].server_acception[i].event_sock;
            if (!sock)
               continue;
            /* watch server socket if no data in cache */
            if (recv_event_check(sock) == 0)
               FD_SET(sock, &readfds);
            /* set timeout to zero if data in cache (-> just quick check IPC)
               and not called from inside bm_send_event (-> wait for IPC) */
            else if (msg == 0)
               millisec = 0;
         }
      /* watch client recv connections */
      if (_suspend_struct[index].server_connection) {
         sock = _suspend_struct[index].server_connection->recv_sock;
         if (sock)
            FD_SET(sock, &readfds);
      }
      /* check IPC socket */
      if (_suspend_struct[index].ipc_recv_socket)
         FD_SET(_suspend_struct[index].ipc_recv_socket, &readfds);
      timeout.tv_sec = millisec / 1000;
      timeout.tv_usec = (millisec % 1000) * 1000;
      do {
         if (millisec < 0)
            status = select(FD_SETSIZE, &readfds, NULL, NULL, NULL);    /* blocking */
         else
            status = select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
         /* if an alarm signal was cought, restart select with reduced timeout */
         if (status == -1 && timeout.tv_sec >= WATCHDOG_INTERVAL / 1000)
            timeout.tv_sec -= WATCHDOG_INTERVAL / 1000;
      } while (status == -1);   /* dont return if an alarm signal was cought */
      /* if listen socket got data, call dispatcher with socket */
      if (_suspend_struct[index].listen_socket &&
          FD_ISSET(_suspend_struct[index].listen_socket, &readfds)) {
         sock = _suspend_struct[index].listen_socket;
         if (_suspend_struct[index].listen_dispatch) {
            status = _suspend_struct[index].listen_dispatch(sock);
            if (status == RPC_SHUTDOWN)
               return status;
         }
      }
      /* check server channels */
      if (_suspend_struct[index].server_acception)
         for (i = 0; i < MAX_RPC_CONNECTION; i++) {
            /* rpc channel */
            sock = _suspend_struct[index].server_acception[i].recv_sock;
            /* only watch the event tcp connection belonging to this thread */
            if (!sock || _suspend_struct[index].server_acception[i].tid != ss_gettid())
               continue;
            if (recv_tcp_check(sock) || FD_ISSET(sock, &readfds)) {
               if (_suspend_struct[index].server_dispatch) {
                  status = _suspend_struct[index].server_dispatch(i, sock, msg != 0);
                  _suspend_struct[index].server_acception[i].
                      last_activity = ss_millitime();
                  if (status == SS_ABORT || status == SS_EXIT || status == RPC_SHUTDOWN)
                     return status;
                  return_status = SS_SERVER_RECV;
               }
            }
            /* event channel */
            sock = _suspend_struct[index].server_acception[i].event_sock;
            if (!sock)
               continue;
            if (recv_event_check(sock) || FD_ISSET(sock, &readfds)) {
               if (_suspend_struct[index].server_dispatch) {
                  status = _suspend_struct[index].server_dispatch(i, sock, msg != 0);
                  _suspend_struct[index].server_acception[i].
                      last_activity = ss_millitime();
                  if (status == SS_ABORT || status == SS_EXIT || status == RPC_SHUTDOWN)
                     return status;
                  return_status = SS_SERVER_RECV;
               }
            }
         }
      /* check server message channels */
      if (_suspend_struct[index].server_connection) {
         sock = _suspend_struct[index].server_connection->recv_sock;
         if (sock && FD_ISSET(sock, &readfds)) {
            if (_suspend_struct[index].client_dispatch)
               status = _suspend_struct[index].client_dispatch(sock);
            else {
               status = SS_SUCCESS;
               size = recv_tcp(sock, buffer, sizeof(buffer), 0);
               if (size <= 0)
                  status = SS_ABORT;
            }
            if (status == SS_ABORT) {
               sprintf(str, "Server connection broken to %s",
                       _suspend_struct[index].server_connection->host_name);
               cm_msg(MINFO, "ss_suspend", str);
               /* close client connection if link broken */
               closesocket(_suspend_struct[index].server_connection->send_sock);
               closesocket(_suspend_struct[index].server_connection->recv_sock);
               closesocket(_suspend_struct[index].server_connection->event_sock);
               memset(_suspend_struct[index].server_connection,
                      0, sizeof(RPC_CLIENT_CONNECTION));
               /* exit program after broken connection to MIDAS server */
               return SS_ABORT;
            }
            return_status = SS_CLIENT_RECV;
         }
      }
      /* check IPC socket */
      if (_suspend_struct[index].ipc_recv_socket &&
          FD_ISSET(_suspend_struct[index].ipc_recv_socket, &readfds)) {
         /* receive IPC message */
         size = sizeof(struct sockaddr);
         size = recvfrom(_suspend_struct[index].ipc_recv_socket,
                         buffer, sizeof(buffer), 0, &from_addr, (int *) &size);
         /* find out if this thread is connected as a server */
         server_socket = 0;
         if (_suspend_struct[index].server_acception &&
             rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE)
            for (i = 0; i < MAX_RPC_CONNECTION; i++) {
               sock = _suspend_struct[index].server_acception[i].send_sock;
               if (sock && _suspend_struct[index].server_acception[i].tid == ss_gettid())
                  server_socket = sock;
            }
         /* receive further messages to empty UDP queue */
         do {
            FD_ZERO(&readfds);
            FD_SET(_suspend_struct[index].ipc_recv_socket, &readfds);
            timeout.tv_sec = 0;
            timeout.tv_usec = 0;
            status = select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
            if (status != -1
                && FD_ISSET(_suspend_struct[index].ipc_recv_socket, &readfds)) {
               size = sizeof(struct sockaddr);
               size =
                   recvfrom(_suspend_struct[index].ipc_recv_socket,
                            buffer_tmp, sizeof(buffer_tmp), 0, &from_addr, &size);
               /* don't forward same MSG_BM as above */
               if (buffer_tmp[0] != 'B' || strcmp(buffer_tmp, buffer) != 0)
                  if (_suspend_struct[index].ipc_dispatch)
                     _suspend_struct[index].ipc_dispatch(buffer_tmp, server_socket);
            }
         } while (FD_ISSET(_suspend_struct[index].ipc_recv_socket, &readfds));
         /* return if received requested message */
         if (msg == MSG_BM && buffer[0] == 'B')
            return SS_SUCCESS;
         if (msg == MSG_ODB && buffer[0] == 'O')
            return SS_SUCCESS;
         /* call dispatcher */
         if (_suspend_struct[index].ipc_dispatch)
            _suspend_struct[index].ipc_dispatch(buffer, server_socket);
         return_status = SS_SUCCESS;
      }
   } while (millisec < 0);
   return return_status;
}
INT ss_suspend_exit (void)
Definition at line 3133 of file system.c.
References closesocket, SS_SUCCESS, ss_suspend_get_index(), and status.
Referenced by rpc_server_shutdown(), and rpc_server_thread().
         : ss_suspend_exit
  Purpose: Closes the sockets used in the suspend/resume mechanism.
     Should be called before a thread exits.
  Input:
    none
  Output:
    none
  Function value:
    SS_SUCCESS              Successful completion
\********************************************************************/
{
   INT i, status;
   status = ss_suspend_get_index(&i);
   if (status != SS_SUCCESS)
      return status;
   if (_suspend_struct[i].ipc_recv_socket) {
      closesocket(_suspend_struct[i].ipc_recv_socket);
      closesocket(_suspend_struct[i].ipc_send_socket);
   }
   memset(&_suspend_struct[i], 0, sizeof(SUSPEND_STRUCT));
   /* calculate new _suspend_entries value */
   for (i = _suspend_entries - 1; i >= 0; i--)
      if (_suspend_struct[i].in_use)
         break;
   _suspend_entries = i + 1;
   if (_suspend_entries == 0) {
      free(_suspend_struct);
      _suspend_struct = NULL;
   }
   return SS_SUCCESS;
}
INT ss_suspend_get_port (INT * port)
Definition at line 3245 of file system.c.
References index, SUSPEND_STRUCT::ipc_port, SS_SUCCESS, ss_suspend_get_index(), ss_suspend_init_ipc(), and status.
Referenced by bm_open_buffer(), and db_open_database().
         : ss_suspend_get_port
  Purpose: Return the UDP port number which can be used to resume
     the calling thread inside a ss_suspend function. The port
     number can then be used by another process as a para-
     meter to the ss_resume function to resume the thread
     which called ss_suspend.
  Input:
    none
  Output:
    INT    *port            UDP port number
  Function value:
    SS_SUCCESS              Successful completion
\********************************************************************/
{
   INT index, status;
   status = ss_suspend_get_index(&index);
   if (status != SS_SUCCESS)
      return status;
   if (!_suspend_struct[index].ipc_port)
      ss_suspend_init_ipc(index);
   *port = _suspend_struct[index].ipc_port;
   return SS_SUCCESS;
}
INT ss_suspend_set_dispatch (INT channel, void * connection, INT(*)() dispatch)
Definition at line 3182 of file system.c.
References CH_CLIENT, CH_IPC, CH_LISTEN, CH_SERVER, SUSPEND_STRUCT::client_dispatch, SUSPEND_STRUCT::ipc_dispatch, SUSPEND_STRUCT::listen_dispatch, SUSPEND_STRUCT::listen_socket, SUSPEND_STRUCT::server_acception, SUSPEND_STRUCT::server_connection, SUSPEND_STRUCT::server_dispatch, SS_SUCCESS, ss_suspend_get_index(), ss_suspend_init_ipc(), and status.
Referenced by bm_open_buffer(), db_open_database(), rpc_client_accept(), rpc_register_server(), rpc_server_callback(), and rpc_server_connect().
         : ss_suspend_set_dispatch
  Purpose: Set dispatch functions which get called whenever new data
     on various sockets arrive inside the ss_suspend function.
     Beside the Inter Process Communication socket several other
     sockets can simultanously watched: A "listen" socket for
     a server main thread, server sockets which receive new
     RPC requests from remote clients (given by the
     server_acception array) and client sockets which may
     get notification data from remote servers (such as
     database updates).
  Input:
    INT    channel               One of CH_IPC, CH_CLIENT,
         CH_SERVER, CH_MSERVER
    INT    (*dispatch())         Function being called
  Output:
    none
  Function value:
    SS_SUCCESS              Successful completion
\********************************************************************/
{
   INT i, status;
   status = ss_suspend_get_index(&i);
   if (status != SS_SUCCESS)
      return status;
   if (channel == CH_IPC) {
      _suspend_struct[i].ipc_dispatch = (INT(*)(char *, INT)) dispatch;
      if (!_suspend_struct[i].ipc_recv_socket)
         ss_suspend_init_ipc(i);
   }
   if (channel == CH_LISTEN) {
      _suspend_struct[i].listen_socket = *((INT *) connection);
      _suspend_struct[i].listen_dispatch = (INT(*)(INT)) dispatch;
   }
   if (channel == CH_CLIENT) {
      _suspend_struct[i].server_connection = (RPC_SERVER_CONNECTION *) connection;
      _suspend_struct[i].client_dispatch = (INT(*)(INT)) dispatch;
   }
   if (channel == CH_SERVER) {
      _suspend_struct[i].server_acception = (RPC_SERVER_ACCEPTION *) connection;
      _suspend_struct[i].server_dispatch = (INT(*)(INT, int, BOOL)) dispatch;
   }
   return SS_SUCCESS;
}
INT EXPRT ss_syslog (const char * message)
Definition at line 5836 of file system.c.
References FALSE, SS_SUCCESS, and TRUE.
Referenced by msg_print().
         : ss_syslog
  Purpose: Write a message to the system logging facility
  Input:
    char   format  Same as for printf
  Output:
    <none>
  Function value:
    SS_SUCCESS     Successful completion
\********************************************************************/
{
#ifdef OS_UNIX
   static BOOL init = FALSE;
   if (!init) {
#ifdef OS_ULTRIX
      openlog("MIDAS", LOG_PID);
#else
      openlog("MIDAS", LOG_PID, LOG_USER);
#endif
      init = TRUE;
   }
   syslog(LOG_DEBUG, message);
   return SS_SUCCESS;
#elif defined(OS_WINNT)         /* OS_UNIX */
/*
HANDLE hlog = 0;
const char *pstr[2];
  if (!hlog)
    {
    HKEY  hk;
    DWORD d;
    char  str[80];
    RegCreateKey(HKEY_LOCAL_MACHINE,
      "SYSTEM\\CurrentControlSet\\Services\\EventLog\\Application\\Midas", &hk);
    strcpy(str, (char *) rpc_get_server_option(RPC_OSERVER_NAME));
    RegSetValueEx(hk, "EventMessageFile", 0, REG_EXPAND_SZ, (LPBYTE) str, strlen(str) + 1);
    d = EVENTLOG_ERROR_TYPE | EVENTLOG_WARNING_TYPE |
        EVENTLOG_INFORMATION_TYPE;
    RegSetValueEx(hk, "TypesSupported", 0, REG_DWORD, (LPBYTE) &d, sizeof(DWORD));
    RegCloseKey(hk);
    hlog = RegisterEventSource(NULL, "Midas");
    }
  pstr[0] = message;
  pstr[1] = NULL;
  if (hlog)
    ReportEvent(hlog, EVENTLOG_INFORMATION_TYPE, 0, 0, NULL, 1, 0, pstr, NULL);
*/
   return SS_SUCCESS;
#else                           /* OS_WINNT */
   return SS_SUCCESS;
#endif
}
INT EXPRT ss_system (char * command)
Referenced by al_check(), al_trigger_class(), cm_transition(), exec_script(), lazy_copy(), lazy_log_update(), lazy_main(), receive_message(), and show_programs_page().
midas_thread_t EXPRT ss_thread_create (INT(*)(void *) thread_func, void * param)
dox Execute command in a separate process, close all open file descriptors invoke ss_exec() and ignore pid.
{ ...
  char cmd[256];
  sprintf(cmd,"%s %s %i %s/%s %1.3lf %d",lazy.commandAfter,
     lazy.backlabel, lazyst.nfiles, lazy.path, lazyst.backfile,
     lazyst.file_size/1024.0/1024.0, blockn);
  cm_msg(MINFO,"Lazy","Exec post file write script:%s",cmd);
  ss_system(cmd);
}
...
\encode
@param command Command to execute.
@return SS_SUCCESS or ss_exec() return code
*/
INT ss_system(char *command)
{
#ifdef OS_UNIX
   INT childpid;
   return ss_exec(command, &childpid);
#else
   system(command);
   return SS_SUCCESS;
#endif
}
#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*------------------------------------------------------------------*/
INT ss_exec(char *command, INT * pid)
/********************************************************************\
  Routine: ss_exec
  Purpose: Execute command in a separate process, close all open
           file descriptors, return the pid of the child process.
  Input:
    char * command    Command to execute
    INT  * pid        Returned PID of the spawned process.
  Output:
    none
  Function value:
    SS_SUCCESS       Successful completion
    SS_ABORT         fork() was not successful, or other problem
\********************************************************************/
{
#ifdef OS_UNIX
   /* only implemented for UNIX */
   int i, fd;
   if ((*pid = fork()) < 0)
      return SS_ABORT;
   else if (*pid != 0) {
      /* avoid <defunc> parent processes */
      signal(SIGCHLD, catch_sigchld);
      return SS_SUCCESS;        /* parent returns */
   }
   /* child continues here... */
   /* close all open file descriptors */
   for (i = 0; i < 256; i++)
      close(i);
   /* try and use up stdin, stdout and stderr, so other
      routines writing to stdout etc won't cause havoc */
   for (i = 0; i < 3; i++) {
      fd = open("/dev/null", O_RDWR, 0);
      if (fd < 0)
         fd = open("/dev/null", O_WRONLY, 0);
      if (fd < 0) {
         cm_msg(MERROR, "ss_exec", "Can't open /dev/null");
         return SS_ABORT;
      }
      if (fd != i) {
         cm_msg(MERROR, "ss_exec", "Did not get file descriptor");
         return SS_ABORT;
      }
   }
   setsid();                    /* become session leader */
   /* chdir("/"); *//* change working directory (not on NFS!) */
   umask(0);                    /* clear our file mode createion mask */
   /* execute command */
   execl("/bin/sh", "sh", "-c", command, NULL);
#else
   system(command);
#endif
   return SS_SUCCESS;
}
#endif                          /* DOXYGEN_SHOULD_SKIP_THIS */
/********************************************************************/
Example for Linux
...
midas_thread_t thread_id = ss_thread_create((void *) taskWatch, pDevice);
if (thread_id == 0) {
  printf("cannot spawn taskWatch\n");
}
...
Parameters:
(*thread_func) Thread function to create.
param a pointer to a VX_TASK_SPAWN structure for vxWorks and a void pointer for Unix and Windows
Returns:
the new thread id or zero on error
Definition at line 1705 of file system.c.
References VX_TASK_SPAWN::arg1, VX_TASK_SPAWN::arg10, VX_TASK_SPAWN::arg2, VX_TASK_SPAWN::arg3, VX_TASK_SPAWN::arg4, VX_TASK_SPAWN::arg5, VX_TASK_SPAWN::arg6, VX_TASK_SPAWN::arg7, VX_TASK_SPAWN::arg8, VX_TASK_SPAWN::arg9, VX_TASK_SPAWN::name, VX_TASK_SPAWN::options, VX_TASK_SPAWN::priority, VX_TASK_SPAWN::stackSize, and status.
Referenced by dm_buffer_create(), main(), and rpc_server_accept().
{
#if defined(OS_WINNT)
   HANDLE status;
   DWORD thread_id;
   if (thread_func == NULL) {
      return 0;
   }
   status = CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE) thread_func,
                         (LPVOID) param, 0, &thread_id);
   return status == NULL ?  0 : (midas_thread_t)thread_id;
#elif defined(OS_MSDOS)
   return 0;
#elif defined(OS_VMS)
   return 0;
#elif defined(OS_VXWORKS)
/* taskSpawn which could be considered as a thread under VxWorks
   requires several argument beside the thread args
   taskSpawn (taskname, priority, option, stacksize, entry_point
              , arg1, arg2, ... , arg9, arg10)
   all the arg will have to be retrieved from the param list.
   through a structure to be simpler  */
   INT status;
   VX_TASK_SPAWN *ts;
   ts = (VX_TASK_SPAWN *) param;
   status =
       taskSpawn(ts->name, ts->priority, ts->options, ts->stackSize,
                 (FUNCPTR) thread_func, ts->arg1, ts->arg2, ts->arg3,
                 ts->arg4, ts->arg5, ts->arg6, ts->arg7, ts->arg8, ts->arg9, ts->arg10);
   return status == ERROR ? 0 : status;
#elif defined(OS_UNIX)
   INT status;
   pthread_t thread_id;
   status = pthread_create(&thread_id, NULL, (void *) thread_func, param);
   return status != 0 ? 0 : thread_id;
#endif
}
INT EXPRT ss_thread_kill (midas_thread_t thread_id)
Destroys the thread identified by the passed thread id. The thread id is returned by ss_thread_create() on creation.
...
midas_thread_t thread_id = ss_thread_create((void *) taskWatch, pDevice);
if (thread_id == 0) {
  printf("cannot spawn taskWatch\n");
}
...
ss_thread_kill(thread_id);
...
Parameters:
thread_id the thread id of the thread to be killed.
Returns:
SS_SUCCESS if no error, else SS_NO_THREAD
Definition at line 1779 of file system.c.
References SS_NO_THREAD, SS_SUCCESS, and status.
{
#if defined(OS_WINNT)
   DWORD status;
   status = TerminateThread(thread_id, 0);
   return status != 0 ? SS_SUCCESS : SS_NO_THREAD;
#elif defined(OS_MSDOS)
   return 0;
#elif defined(OS_VMS)
   return 0;
#elif defined(OS_VXWORKS)
   INT status;
   status = taskDelete(thread_id);
   return status == OK ? 0 : ERROR;
#elif defined(OS_UNIX)
   INT status;
   status = pthread_kill(thread_id, SIGKILL);
   return status == 0 ? SS_SUCCESS : SS_NO_THREAD;
#endif
}
INT EXPRT ss_timezone (void)
Definition at line 2440 of file system.c.
Referenced by taxis().
         : ss_timezone
  Purpose: Returns difference in seconds between coordinated universal
           time and local time.
  Input:
    none
  Output:
    none
  Function value:
    INT    Time difference in seconds
\********************************************************************/
{
#if defined(OS_DARWIN) || defined(OS_VXWORKS)
  return 0;
#else
  return timezone; /* on Linux, comes from "#include <time.h>". */
#endif
}
INT ss_wake (INT pid, INT tid, INT thandle)
Definition at line 2603 of file system.c.
References SS_NO_PROCESS, SS_SUCCESS, and TRUE.
         : ss_wake
  Purpose: Wake a process with a specific ID and optional with a
     specific thread ID (on OS with support threads).
  Input:
    INT    pid              Process ID
    INT    tid              Thread ID
    INT    thandle          Thread handle (used under Windows NT)
  Output:
    none
  Function value:
    SS_SUCCESS              Successful completion
    SS_NO_PROCESS           Nonexisting process
\********************************************************************/
{
#ifdef OS_WINNT
   HANDLE process_handle;
   HANDLE dup_thread_handle;
   /*
      Under Windows NT, it's a little bit tricky to get a thread handle
      which can be passed to other processes. First the calling process
      has to duplicate the GetCurrentThread() handle, then the process
      which gets this handle also has to use DuplicateHandle with the
      target process as its own. Then this duplicated handle can be used
      to the SupendThread() and ResumeThread() functions.
    */
   process_handle = OpenProcess(PROCESS_ALL_ACCESS, TRUE, pid);
   if (process_handle == 0)
      return SS_NO_PROCESS;
   DuplicateHandle(process_handle, (HANDLE) thandle, GetCurrentProcess(),
                   &dup_thread_handle, THREAD_ALL_ACCESS, TRUE, 0);
   /* close handles not to waste resources */
   CloseHandle(process_handle);
   if (dup_thread_handle == 0)
      return SS_NO_PROCESS;
   ResumeThread(dup_thread_handle);
   /* close handles not to waste resources */
   CloseHandle(dup_thread_handle);
   return SS_SUCCESS;
#endif                          /* OS_WINNT */
#ifdef OS_VMS
   if (sys$wake(&pid, 0) == SS$_NONEXPR)
      return SS_NO_PROCESS;
   return SS_SUCCESS;
#endif                          /* OS_VMS */
#ifdef OS_UNIX
   if (kill(pid, SIGCONT) < 0)
      return SS_NO_PROCESS;
   return SS_SUCCESS;
   /*
      Bryan: kill has to get the target process out of pause(). Some
      UNIX documentation say that pause() terminates by receiving any
      signal which would be ok because the buffer manager is designed
      in a way where an additional wake doesn't hurt. If this is not
      true, one has to setup a signal(SIGCONT, dummy) in the ss_sleep
      routine or so. Please check this.
    */
#endif                          /* OS_UNIX */
}