AlcapDAQ: midas/examples/hbookexpt/analyzer.c File Reference
midas/examples/hbookexpt/analyzer.c File Reference
#include <stdio.h>
#include <string.h>
#include <time.h>
#include "midas.h"
#include "experim.h"
#include "analyzer.h"
#include <cfortran.h>
#include <hbook.h>
Functions
PAWC_DEFINE (1000000)
ASUM_BANK_STR (asum_bank_str)
ADC0_BANK_STR (ana_adc0_bank_str)
INT analyzer_init ()
INT analyzer_exit ()
INT ana_begin_of_run (INT run_number, char *error)
INT ana_end_of_run (INT run_number, char *error)
INT ana_pause_run (INT run_number, char *error)
INT ana_resume_run (INT run_number, char *error)
INT analyzer_loop ()
Variables
char * analyzer_name = "Analyzer"
INT analyzer_loop_period = 0
INT odb_size = DEFAULT_ODB_SIZE
RUNINFO runinfo
GLOBAL_PARAM global_param
EXP_PARAM exp_param
TRIGGER_SETTINGS trigger_settings
ANA_MODULE scaler_accum_module
ANA_MODULE adc_calib_module
ANA_MODULE adc_summing_module
ANA_MODULE * scaler_module []
ANA_MODULE * trigger_module []
BANK_LIST ana_trigger_bank_list []
BANK_LIST ana_scaler_bank_list []
ANALYZE_REQUEST analyze_request []
Function Documentation
ADC0_BANK_STR (ana_adc0_bank_str)
INT ana_begin_of_run (INT run_number, char * error)
Definition at line 218 of file analyzer.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
INT ana_end_of_run (INT run_number, char * error)
Definition at line 225 of file analyzer.c.
References cm_get_experiment_database(), CM_SUCCESS, EXP_PARAM::comment, db_get_value(), DIR_SEPARATOR, DIR_SEPARATOR_STR, flag, hDB, n, RUNINFO::online_mode, RUNINFO::run_number, size, RUNINFO::start_time, TID_BOOL, TID_DOUBLE, TID_STRING, time, and TRUE.
{
   FILE *f;
   time_t now;
   char str[256];
   int size;
   double n;
   HNDLE hDB;
   BOOL flag;
   cm_get_experiment_database(&hDB, NULL);
   /* update run log if run was written and running online */
   size = sizeof(flag);
   db_get_value(hDB, 0, "/Logger/Write data", &flag, &size, TID_BOOL, TRUE);
   if (flag && runinfo.online_mode == 1) {
      /* update run log */
      size = sizeof(str);
      str[0] = 0;
      db_get_value(hDB, 0, "/Logger/Data Dir", str, &size, TID_STRING, TRUE);
      if (str[0] != 0)
         if (str[strlen(str) - 1] != DIR_SEPARATOR)
            strcat(str, DIR_SEPARATOR_STR);
      strcat(str, "runlog.txt");
      f = fopen(str, "a");
      time(&now);
      strcpy(str, ctime(&now));
      str[10] = 0;
      fprintf(f, "%s\t%3d\t", str, runinfo.run_number);
      strcpy(str, runinfo.start_time);
      str[19] = 0;
      fprintf(f, "%s\t", str + 11);
      strcpy(str, ctime(&now));
      str[19] = 0;
      fprintf(f, "%s\t", str + 11);
      size = sizeof(n);
      db_get_value(hDB, 0, "/Equipment/Trigger/Statistics/Events sent", &n, &size,
                   TID_DOUBLE, TRUE);
      fprintf(f, "%5.1lfk\t", n / 1000);
      fprintf(f, "%s\n", exp_param.comment);
      fclose(f);
   }
   return CM_SUCCESS;
}
INT ana_pause_run (INT run_number, char * error)
Definition at line 282 of file analyzer.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
INT ana_resume_run (INT run_number, char * error)
Definition at line 289 of file analyzer.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
INT analyzer_exit (void)
Definition at line 211 of file analyzer.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
INT analyzer_init (void)
Definition at line 156 of file analyzer.c.
References analyzer_name, cm_get_experiment_database(), cm_msg, db_create_record(), db_find_key(), db_open_record(), DB_SUCCESS, EXP_PARAM_STR, GLOBAL_PARAM_STR, hDB, hKey, MERROR, MODE_READ, RUNINFO_STR, strcomb(), SUCCESS, and TRIGGER_SETTINGS_STR.
{
   HNDLE hDB, hKey;
   char str[80];
   RUNINFO_STR(runinfo_str);
   EXP_PARAM_STR(exp_param_str);
   GLOBAL_PARAM_STR(global_param_str);
   TRIGGER_SETTINGS_STR(trigger_settings_str);
   /* open ODB structures */
   cm_get_experiment_database(&hDB, NULL);
   db_create_record(hDB, 0, "/Runinfo", strcomb(runinfo_str));
   db_find_key(hDB, 0, "/Runinfo", &hKey);
   if (db_open_record(hDB, hKey, &runinfo, sizeof(runinfo), MODE_READ, NULL, NULL) !=
       DB_SUCCESS) {
      cm_msg(MERROR, "analyzer_init", "Cannot open \"/Runinfo\" tree in ODB");
      return 0;
   }
   db_create_record(hDB, 0, "/Experiment/Run Parameters", strcomb(exp_param_str));
   db_find_key(hDB, 0, "/Experiment/Run Parameters", &hKey);
   if (db_open_record(hDB, hKey, &exp_param, sizeof(exp_param), MODE_READ, NULL, NULL) !=
       DB_SUCCESS) {
      cm_msg(MERROR, "analyzer_init",
             "Cannot open \"/Experiment/Run Parameters\" tree in ODB");
      return 0;
   }
   sprintf(str, "/%s/Parameters/Global", analyzer_name);
   db_create_record(hDB, 0, str, strcomb(global_param_str));
   db_find_key(hDB, 0, str, &hKey);
   if (db_open_record
       (hDB, hKey, &global_param, sizeof(global_param), MODE_READ, NULL,
        NULL) != DB_SUCCESS) {
      cm_msg(MERROR, "analyzer_init", "Cannot open \"%s\" tree in ODB", str);
      return 0;
   }
   db_create_record(hDB, 0, "/Equipment/Trigger/Settings", strcomb(trigger_settings_str));
   db_find_key(hDB, 0, "/Equipment/Trigger/Settings", &hKey);
   if (db_open_record
       (hDB, hKey, &trigger_settings, sizeof(trigger_settings), MODE_READ, NULL,
        NULL) != DB_SUCCESS) {
      cm_msg(MERROR, "analyzer_init",
             "Cannot open \"/Equipment/Trigger/Settings\" tree in ODB");
      return 0;
   }
   return SUCCESS;
}
INT analyzer_loop (void)
Definition at line 296 of file analyzer.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
ASUM_BANK_STR (asum_bank_str)
PAWC_DEFINE (1000000)
Variable Documentation
ANA_MODULE adc_calib_module
Definition at line 81 of file adccalib.c.
ANA_MODULE adc_summing_module
Definition at line 92 of file adcsum.c.
BANK_LIST ana_scaler_bank_list[]
Initial value:
 {
   {"SCLR", TID_DWORD, N_ADC, NULL}
   ,
   {"ACUM", TID_DOUBLE, N_ADC, NULL}
   ,
   {""}
   ,
}
Definition at line 106 of file analyzer.c.
BANK_LIST ana_trigger_bank_list[]
Initial value:
 {
   {"ADC0", TID_STRUCT, sizeof(ADC0_BANK), ana_adc0_bank_str}
   ,
   {"TDC0", TID_WORD, N_TDC, NULL}
   ,
   {"CADC", TID_FLOAT, N_ADC, NULL}
   ,
   {"ASUM", TID_STRUCT, sizeof(ASUM_BANK), asum_bank_str}
   ,
   {""}
   ,
}
Definition at line 88 of file analyzer.c.
ANALYZE_REQUEST analyze_request[]
Definition at line 120 of file analyzer.c.
INT analyzer_loop_period = 0
Definition at line 54 of file analyzer.c.
char* analyzer_name = "Analyzer"
Definition at line 51 of file analyzer.c.
EXP_PARAM exp_param
Definition at line 62 of file analyzer.c.
GLOBAL_PARAM global_param
Definition at line 61 of file analyzer.c.
INT odb_size = DEFAULT_ODB_SIZE
Definition at line 57 of file analyzer.c.
RUNINFO runinfo
Definition at line 60 of file analyzer.c.
ANA_MODULE scaler_accum_module
Definition at line 48 of file scaler.c.
ANA_MODULE* scaler_module[]
Initial value:
 {
   &scaler_accum_module,
   NULL
}
Definition at line 71 of file analyzer.c.
ANA_MODULE* trigger_module[]
Initial value:
 {
   &adc_calib_module,
   &adc_summing_module,
   NULL
}
Definition at line 76 of file analyzer.c.
TRIGGER_SETTINGS trigger_settings
Definition at line 63 of file analyzer.c.