AlcapDAQ: midas/src/lazylogger.c File Reference
midas/src/lazylogger.c File Reference
#include "midas.h"
#include "msystem.h"
#include "ybos.h"
#include <assert.h>
Data Structures
struct DIRLOG
struct LAZY_SETTING
struct LAZY_STATISTICS
struct LAZY_INFO
Defines
#define NOTHING_TODO 0
#define FORCE_EXIT 1
#define NEW_FILE 1
#define REMOVE_FILE 2
#define REMOVE_ENTRY 3
#define MAX_LAZY_CHANNEL 4
#define TRACE
#define LAZY_SETTINGS_STRING "\Maintain free space(%) = INT : 0\n\Stay behind = INT : -3\n\Alarm Class = STRING : [32]\n\Running condition = STRING : [128] ALWAYS\n\Data dir = STRING : [256] \n\Data format = STRING : [8] MIDAS\n\Filename format = STRING : [128] run%05d.mid\n\Backup type = STRING : [8] Tape\n\Execute after rewind = STRING : [64]\n\Path = STRING : [128] \n\Capacity (Bytes) = FLOAT : 5e9\n\List label= STRING : [128] \n\Execute before writing file = STRING : [64]\n\Execute after writing file = STRING : [64]\n\Modulo.Position = STRING : [8]\n\Tape Data Append = BOOL : y\n\"
#define LAZY_STATISTICS_STRING "\Backup file = STRING : [128] none \n\File size [Bytes] = FLOAT : 0.0\n\KBytes copied = FLOAT : 0.0\n\Total Bytes copied = FLOAT : 0.0\n\Copy progress [%] = FLOAT : 0\n\Copy Rate [bytes per s] = FLOAT : 0\n\Backup status [%] = FLOAT : 0\n\Number of Files = INT : 0\n\Current Lazy run = INT : 0\n\"
#define WATCHDOG_TIMEOUT 60000
Functions
INT moduloCheck (INT lModulo, INT lPosition, INT lrun)
BOOL lazy_file_exists (char *dir, char *file)
INT lazy_main (INT, LAZY_INFO *)
INT lazy_copy (char *dev, char *file)
INT lazy_file_compose (char *fmt, char *dir, INT num, char *ffile, char *file)
INT lazy_update_list (LAZY_INFO *, DWORD cp)
INT lazy_select_purge (HNDLE, INT ch, LAZY_INFO *, char *fmt, char *dir, char *pufile, INT *run)
INT lazy_load_params (HNDLE hDB, HNDLE hKey)
INT build_log_list (char *fmt, char *dir, DIRLOG **plog)
INT build_done_list (HNDLE, INT **)
INT cmp_log2donelist (DIRLOG *plog, INT *pdo)
INT lazy_log_update (INT action, INT run, char *label, char *file, DWORD rm)
int lazy_remove_entry (INT ch, LAZY_INFO *, int run)
void lazy_settings_hotlink (HNDLE hDB, HNDLE hKey, void *info)
void lazy_maintain_check (HNDLE hKey, LAZY_INFO *pLall)
INT ss_run_extract (char *name)
INT lazy_file_remove (char *pufile)
void lazy_statistics_update (INT cploop_time)
BOOL condition_test (char *string)
BOOL lazy_condition_check (void)
int main (int argc, char **argv)
Variables
LAZY_SETTING lazy
LAZY_STATISTICS lazyst
LAZY_INFO lazyinfo [MAX_LAZY_CHANNEL]
INT channel = -1
INT lazy_mutex
HNDLE hDB
HNDLE hKey
HNDLE pcurrent_hKey
float lastsz
HNDLE hKeyst
INT run_state
INT tot_do_size
INT tot_dirlog_size
INT hDev
BOOL zap_flag
BOOL msg_flag
BOOL copy_continue = TRUE
INT data_fmt
INT dev_type
char lazylog [MAX_STRING_LENGTH]
BOOL full_bck_flag = FALSE
BOOL maintain_touched = FALSE
INT blockn = 0
Define Documentation
#define FORCE_EXIT 1
Definition at line 204 of file lazylogger.c.
Referenced by lazy_copy(), lazy_main(), and main().
#define LAZY_SETTINGS_STRING "\Maintain free space(%) = INT : 0\n\Stay behind = INT : -3\n\Alarm Class = STRING : [32]\n\Running condition = STRING : [128] ALWAYS\n\Data dir = STRING : [256] \n\Data format = STRING : [8] MIDAS\n\Filename format = STRING : [128] run%05d.mid\n\Backup type = STRING : [8] Tape\n\Execute after rewind = STRING : [64]\n\Path = STRING : [128] \n\Capacity (Bytes) = FLOAT : 5e9\n\List label= STRING : [128] \n\Execute before writing file = STRING : [64]\n\Execute after writing file = STRING : [64]\n\Modulo.Position = STRING : [8]\n\Tape Data Append = BOOL : y\n\"
Definition at line 216 of file lazylogger.c.
Referenced by main().
#define LAZY_STATISTICS_STRING "\Backup file = STRING : [128] none \n\File size [Bytes] = FLOAT : 0.0\n\KBytes copied = FLOAT : 0.0\n\Total Bytes copied = FLOAT : 0.0\n\Copy progress [%] = FLOAT : 0\n\Copy Rate [bytes per s] = FLOAT : 0\n\Backup status [%] = FLOAT : 0\n\Number of Files = INT : 0\n\Current Lazy run = INT : 0\n\"
Definition at line 234 of file lazylogger.c.
Referenced by main().
#define MAX_LAZY_CHANNEL 4
Definition at line 208 of file lazylogger.c.
Referenced by lazy_maintain_check(), lazy_remove_entry(), lazy_select_purge(), and main().
#define NEW_FILE 1
Definition at line 205 of file lazylogger.c.
Referenced by lazy_log_update(), and lazy_update_list().
#define NOTHING_TODO 0
Definition at line 203 of file lazylogger.c.
Referenced by lazy_main().
#define REMOVE_ENTRY 3
Definition at line 207 of file lazylogger.c.
Referenced by lazy_log_update(), and lazy_remove_entry().
#define REMOVE_FILE 2
Definition at line 206 of file lazylogger.c.
Referenced by lazy_log_update(), and lazy_main().
#define TRACE
Definition at line 209 of file lazylogger.c.
#define WATCHDOG_TIMEOUT 60000
Definition at line 306 of file lazylogger.c.
Referenced by main().
Function Documentation
INT build_done_list (HNDLE hLch, INT ** pdo)
Definition at line 545 of file lazylogger.c.
References db_enum_key(), db_find_key(), db_get_data(), db_get_key(), DB_SUCCESS, hDB, hKey, hSubkey, i, j, key, KEY::num_values, size, temp, TID_INT, and tot_do_size.
Referenced by lazy_main(), and lazy_select_purge().
       : build_done_list
Purpose: build a sorted internal /lazy/list list (pdo) tree.
Input:
HNDLE             Key of the Lazy channel
**pdo     /lazy_xxx/list run listing
Output:
**pdo     /lazy_xxx/list run listing
Function value:      number of elements
\********************************************************************/
{
   HNDLE hKey, hSubkey;
   KEY key;
   INT i, j, size, tot_nelement, nelement, temp;
   if (db_find_key(hDB, hLch, "List", &hKey) != DB_SUCCESS) {
      *pdo[0] = 0;
      return 0;
   }
   tot_nelement = tot_do_size = 0;
   for (i = 0;; i++) {
      db_enum_key(hDB, hKey, i, &hSubkey);
      if (!hSubkey)
         break;
      db_get_key(hDB, hSubkey, &key);
      nelement = key.num_values;
      tot_do_size += nelement * sizeof(INT);
      *pdo = realloc(*pdo, tot_do_size);
      size = nelement * sizeof(INT);
      db_get_data(hDB, hSubkey, (char *) (*pdo + tot_nelement), &size, TID_INT);
      tot_nelement += nelement;
   }
   for (j = 0; j < tot_nelement - 1; j++) {
      for (i = j + 1; i < tot_nelement; i++) {
         if (*(*pdo + j) > *(*pdo + i)) {
            memcpy(&temp, (*pdo + i), sizeof(INT));
            memcpy((*pdo + i), (*pdo + j), sizeof(INT));
            memcpy((*pdo + j), &temp, sizeof(INT));
         }
      }
   }
   return tot_nelement;
}
INT build_log_list (char * fmt, char * dir, DIRLOG ** plog)
Definition at line 452 of file lazylogger.c.
References DIR_SEPARATOR, DIR_SEPARATOR_STR, i, j, lModulo, MAX_FILE_PATH, MAX_STRING_LENGTH, LAZY_SETTING::modulo, moduloCheck(), run, size, ss_file_find(), ss_file_size(), ss_run_extract(), temp, and tot_dirlog_size.
Referenced by lazy_main(), and lazy_select_purge().
       : build_log_list
Purpose: build an internal directory file list from the disk directory
Input:
* fmt     format of the file to search for (ie:run%05d.ybs)
* dir     path to the directory for the search
Output:
**plog     internal file list struct
Function value:
number of elements
\********************************************************************/
{
   INT nfile, i, j, l;
   char *list = NULL;
   char str[MAX_FILE_PATH];
   DIRLOG temp;
   char *dot;
   int lModulo = 0, lPosition = 0;
   /* substitue %xx by * */
   strcpy(str, fmt);
   if (strchr(str, '%')) {
      *strchr(str, '%') = '*';
      if (strchr(str, '.'))
         strcpy((strchr(str, '*') + 1), strchr(str, '.'));
   }
   /* create dir listing with given criteria */
   if (dir[0] != 0)
      if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
         strcat(dir, DIR_SEPARATOR_STR);
   nfile = ss_file_find(dir, str, &list);
   /* check */
   /*
      for (j=0;j<nfile;j++)
      printf ("list[%i]:%s\n",j, list+j*MAX_STRING_LENGTH);
    */
   /* allocate memory */
   tot_dirlog_size = (nfile * sizeof(DIRLOG));
   *plog = realloc(*plog, tot_dirlog_size);
   memset(*plog, 0, tot_dirlog_size);
   /* Check Modulo option */
   if (lazy.modulo[0]) {
      /* Modulo enabled, extract modulo and position */
      dot = strchr(lazy.modulo, '.');
      if (dot) {
         *dot = '\0';
         lModulo = atoi(lazy.modulo);
         lPosition = atoi(dot + 1);
         *dot = '.';
      }
   }
   /* fill structure */
   for (j = 0, l = 0; j < nfile; j++) {
      INT strl, lrun;
      /* extract run number */
      lrun = ss_run_extract(list + j * MAX_STRING_LENGTH);
      /* apply the modulo if enabled */
      lrun = moduloCheck(lModulo, lPosition, lrun);
      /* if modulo enable skip */
      if (lrun == 0)
         continue;
      (*plog + l)->run = lrun;
      strcpy(str, dir);
      strl = strlen(list + j * MAX_STRING_LENGTH);
      strncat(str, list + j * MAX_STRING_LENGTH, strl);
      (*plog + l)->size = ss_file_size(str);
      l++;
   }
   /* correct number of file after the modulo */
   nfile = l;
   free(list);
   /* Sort list */
   for (j = 0; j < nfile; j++) {
      for (i = j; i < nfile; i++) {
         if ((*plog + j)->run > (*plog + i)->run) {
            memcpy(&temp, (*plog + i), sizeof(DIRLOG));
            memcpy((*plog + i), (*plog + j), sizeof(DIRLOG));
            memcpy((*plog + j), &temp, sizeof(DIRLOG));
         }
      }
   }
   return nfile;
}
INT cmp_log2donelist (DIRLOG * plog, INT * pdo)
Definition at line 593 of file lazylogger.c.
References i, j, tot_dirlog_size, and tot_do_size.
Referenced by lazy_main().
       : cmp_log2donelist
Purpose: return the run number to be backed up comparing the
plog struct to the pdo struct
the condition being : run# in (plog AND !pdo)
marks the run present in both list by tagging them with *= -1
Input:
*plog :   disk file listing
*pdo  :   /lazy/list run listing
Output:
Function value:
Run number
-1       : run not found
\********************************************************************/
{
   INT j, i, ndo, nlog;
   ndo = tot_do_size / sizeof(INT);
   nlog = tot_dirlog_size / sizeof(DIRLOG);
   for (j = 0; j < nlog; j++) {
      for (i = 0; i < ndo; i++) {
         if ((plog + j)->run == pdo[i])
            (plog + j)->run *= -1;
      }
   }
   for (j = 0; j < nlog; j++) {
      if ((plog + j)->run > 0)
         return (plog + j)->run;
   }
   return -1;
}
BOOL condition_test (char * string)
Definition at line 1071 of file lazylogger.c.
References cm_msg, db_find_key(), db_get_data_index(), db_get_key(), db_sprintf(), DB_SUCCESS, FALSE, hDB, hKey, index, KEY::item_size, key, MINFO, p, size, status, TID_DOUBLE, TRUE, KEY::type, and value.
Referenced by lazy_condition_check().
       : condition_check
Purpose: return TRUE or FALSE depending if condition is satisfied
I expect a statement of the following form:
<key> <operator> <value>
with <key> : either link or key[index] or key(index)
<operator> : either: = < >
<value> : [+/-][digits]
Input: char * string to decode and test
Output:
Function value:
TRUE           condition TRUE  (carry on the copy)
FALSE          condition FALSE (hold the copy)
\********************************************************************/
{
   KEY key;
   float value;
   double lcond_value;
   INT size, index, status;
   char str[128], left[64], right[64];
   char *p = NULL, *pp, *ppl, *pc, *lp;
   index = 0;
   p = string;
   if (p) {
      while (isspace(*p))
         p++;
      pc = strpbrk(p, "<=>");
      if (pc) {
         strncpy(left, p, pc - p);
         lp = left + (pc - p - 1);
         while (isspace(*lp))
            lp--;
         *(lp + 1) = '\0';
         strncpy(right, pc + 1, (strlen(p) - strlen(left)));
         right[strlen(p) - strlen(left) - 1] = '\0';
      }
      if ((pp = strpbrk(left, "[(")) != NULL) {
         if ((ppl = strpbrk(left, "])")) != NULL) {
            *pp = '\0';
            *ppl = '\0';
            index = atoi(pp + 1);
         }
         *pp = '\0';
      }
      /* convert value */
      value = (float) (atoi(right));
      status = db_find_key(hDB, 0, left, &hKey);
      if (status != DB_SUCCESS) {
         cm_msg(MINFO, "condition_check", "Key %s not found", left);
         return FALSE;
      }
      status = db_get_key(hDB, hKey, &key);
      if ((status == DB_SUCCESS) && (key.type <= TID_DOUBLE)) {
         /* get value of the condition */
         size = sizeof(lcond_value);
         db_get_data_index(hDB, hKey, &lcond_value, &size, index, key.type);
         db_sprintf(str, &lcond_value, key.item_size, 0, key.type);
         lcond_value = atof(str);
      }
      /*  printf("string:%s\n condition: %s %f %c %f \n"
         , string, left, lcond_value, *pc, value);
       */
      /*
         if (pv == NULL)
         return TRUE;
       */
      /* perform condition check */
      if (((*pc == '>') && ((float) lcond_value > value)) ||
          ((*pc == '=') && ((float) lcond_value == value)) ||
          ((*pc == '<') && ((float) lcond_value < value)))
         return TRUE;
      else
         return FALSE;
   }
   /* catch wrong argument in the condition as TRUE */
   return TRUE;
}
BOOL lazy_condition_check (void)
Definition at line 1157 of file lazylogger.c.
References LAZY_SETTING::condition, condition_test(), equal_ustring(), FALSE, run_state, STATE_RUNNING, and TRUE.
Referenced by lazy_copy().
       : lazy_condition_check
Purpose: Check if the copy should continue.
The condition can have the following setting:
ALWAYS, NEVER, WHILE_NO_ACQ_RUNNING, key<=>value
Input:
Output:
Function value:
BOOL :  new copy condition
\********************************************************************/
{
   /* Get condition */
   if (equal_ustring(lazy.condition, "ALWAYS"))
      return TRUE;
   else if (equal_ustring(lazy.condition, "NEVER"))
      return FALSE;
   else if (equal_ustring(lazy.condition, "WHILE_ACQ_NOT_RUNNING")) {
      if (run_state == STATE_RUNNING)
         return FALSE;
      else
         return TRUE;
   } else
      return (condition_test(lazy.condition));
}
INT lazy_copy (char * dev, char * file)
Definition at line 1184 of file lazylogger.c.
References LAZY_STATISTICS::backfile, LAZY_SETTING::backlabel, blockn, cm_get_watchdog_params(), cm_msg, cm_msg1(), cm_set_watchdog_params(), cm_yield(), cmd, LAZY_SETTING::commandBefore, copy_continue, LAZY_STATISTICS::cur_dev_size, LAZY_STATISTICS::cur_size, data_fmt, dev_type, equal_ustring(), FORCE_EXIT, hDev, last_time, lazy_condition_check(), lazy_statistics_update(), LOG_TYPE_TAPE, MAX_FILE_PATH, MERROR, MINFO, msg_flag, MTALK, LAZY_STATISTICS::nfiles, LAZY_STATISTICS::progress, RPC_SHUTDOWN, SS_ABORT, ss_millitime(), SS_NO_SPACE, SS_SUCCESS, ss_system(), ss_tape_close(), ss_tape_get_blockn(), ss_tape_spool(), ss_time(), status, LAZY_SETTING::tapeAppend, LAZY_SETTING::type, yb_any_file_rclose(), yb_any_file_ropen(), yb_any_file_wclose(), yb_any_file_wopen(), yb_any_log_write(), yb_any_physrec_get(), and YB_SUCCESS.
Referenced by lazy_main().
       : lazy_copy
Purpose: backup file to backup device
every 2 second will update the statistics and yield
if condition requires no copy, every 5 second will yield
Input:
char * outfile   backup destination file
char * infile    source file to be backed up
Output:
Function value:
0           success
\********************************************************************/
{
   void *plazy = NULL;
   DWORD szlazy;
   INT status, no_cpy_last_time = 0;
   INT last_time, cpy_loop_time;
   DWORD watchdog_timeout;
   static INT last_error = 0;
   char *pext;
   BOOL watchdog_flag;
   pext = malloc(strlen(infile));
   strcpy(pext, infile);
   /* find out what format it is from the extension. */
   if (strncmp(pext + strlen(pext) - 3, ".gz", 3) == 0) {
      /* extension .gz terminator on . */
      *(pext + strlen(pext) - 3) = '\0';
   }
   /* init copy variables */
   lazyst.cur_size = 0.0f;
   last_time = 0;
   /* open any logging file (output) */
   if ((status = yb_any_file_wopen(dev_type, data_fmt, outfile, &hDev)) != 1) {
      if ((ss_time() - last_error) > 60) {
         last_error = ss_time();
         cm_msg(MTALK, "Lazy_copy", "cannot open %s, error %d", outfile, status);
      }
      return (FORCE_EXIT);
   }
   /* New lazy copy if TAPE & append required force a mv to EOD */
   if ((dev_type == LOG_TYPE_TAPE) && lazy.tapeAppend) {
      /* Position Tape to end of Data */
      cm_msg(MINFO, "Lazy", "Positioning Tape to EOD");
      cm_get_watchdog_params(&watchdog_flag, &watchdog_timeout);
      cm_set_watchdog_params(watchdog_flag, 300000);    /* 5 min for tape rewind */
      status = ss_tape_spool(hDev);
      cm_set_watchdog_params(watchdog_flag, watchdog_timeout);
      if (status != SS_SUCCESS) {
         cm_msg(MINFO, "Lazy", "Error while Positioning Tape to EOD (%d)", status);
         ss_tape_close(hDev);
         return (FORCE_EXIT);
      }
   }
   /* reset error message */
   last_error = 0;
   /* open input data file */
   if (yb_any_file_ropen(infile, data_fmt) != YB_SUCCESS)
      return (FORCE_EXIT);
   /* run shell command if available */
   if (equal_ustring(lazy.type, "Tape")) {
      /* get the block number. If -1 it probably means that the tape
         is not ready. Wait for a while  */
      blockn = -1;
      while (blockn < 0) {
         blockn = ss_tape_get_blockn(hDev);
         if (blockn >= 0)
            break;
         cm_msg(MINFO, "Lazy", "Tape is not ready");
         cm_yield(3000);
      }
      if (lazy.commandBefore[0]) {
         char cmd[256];
         sprintf(cmd, "%s %s %s %d %s %i", lazy.commandBefore,
                 infile, outfile, blockn, lazy.backlabel, lazyst.nfiles);
         cm_msg(MINFO, "Lazy", "Exec pre file write script:%s", cmd);
         ss_system(cmd);
      }
   }
   /* force a statistics update on the first loop */
   cpy_loop_time = -2000;
   {
      char str[MAX_FILE_PATH];
      sprintf(str, "Starting lazy job on %s at block %d", lazyst.backfile, blockn);
      if (msg_flag)
         cm_msg(MTALK, "Lazy", str);
      cm_msg(MINFO, "Lazy", str);
      cm_msg1(MINFO, "lazy_log_update", "lazy", str);
   }
   /* infinite loop while copying */
   while (1) {
      if (copy_continue) {
         if (yb_any_physrec_get(data_fmt, &plazy, &szlazy) == YB_SUCCESS) {
            status = yb_any_log_write(hDev, data_fmt, dev_type, plazy, szlazy);
            if (status != SS_SUCCESS) {
               /* close source file */
               yb_any_file_rclose(dev_type);
               /* close output data file */
               yb_any_file_wclose(hDev, dev_type, data_fmt);
               /* szlazy is the requested block size. Why is it copied to cm_msg?
                  cm_msg(MERROR,"lazy_copy","Write error %i",szlazy); */
               cm_msg(MERROR, "lazy_copy", "Write error ");
               if (status == SS_NO_SPACE)
                  return status;
               return (FORCE_EXIT);
            }
            lazyst.cur_size += (float) szlazy;
            lazyst.cur_dev_size += (float) szlazy;
            if ((ss_millitime() - cpy_loop_time) > 2000) {
               /* update statistics */
               lazy_statistics_update(cpy_loop_time);
               /* check conditions */
               copy_continue = lazy_condition_check();
               /* update check loop */
               cpy_loop_time = ss_millitime();
               /* yield quickly */
               status = cm_yield(1);
               if (status == RPC_SHUTDOWN || status == SS_ABORT)
                  cm_msg(MINFO, "Lazy", "Abort postponed until end of copy %1.0lf[%%]",
                         (double) lazyst.progress);
            }
         } /* get physrec */
         else
            break;
      } /* copy_continue */
      else {                    /* !copy_continue */
         status = cm_yield(1000);
         if (status == RPC_SHUTDOWN || status == SS_ABORT)
            return (FORCE_EXIT);
         if ((ss_millitime() - no_cpy_last_time) > 5000) {
            copy_continue = lazy_condition_check();
            no_cpy_last_time = ss_millitime();
         }
      }                         /* !copy_continue */
   }                            /* while forever */
   /* update for last the statistics */
   lazy_statistics_update(cpy_loop_time);
   /* close input log device */
   yb_any_file_rclose(dev_type);
   /* close output data file */
   if (equal_ustring(lazy.type, "Tape")) {
      blockn = ss_tape_get_blockn(hDev);
   }
   status = yb_any_file_wclose(hDev, dev_type, data_fmt);
   if (status != SS_SUCCESS) {
      if (status == SS_NO_SPACE)
         return status;
      return (FORCE_EXIT);
   }
   /* request exit */
   return 0;
}
INT lazy_file_compose (char * fmt, char * dir, INT num, char * ffile, char * file)
Definition at line 994 of file lazylogger.c.
References DIR_SEPARATOR, DIR_SEPARATOR_STR, MAX_FILE_PATH, and size.
Referenced by lazy_main(), and lazy_select_purge().
       : lazy_file_compose
Purpose: compose "file" with the args
Input:
char * fmt       file format
char * dir       data directory
INT num          run number
Output:
char * ffile     composed full file name (include path)
char * file      composed file name (translated with fmt only)
Function value:
0           success
\********************************************************************/
{
   char str[MAX_FILE_PATH];
   INT size;
   size = sizeof(dir);
   if (dir[0] != 0)
      if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
         strcat(dir, DIR_SEPARATOR_STR);
   strcpy(str, dir);
   strcat(str, fmt);
   /* substitue "%d" by current run number [Full file name] */
   if (strchr(str, '%'))
      sprintf(ffile, str, num);
   else
      strcpy(ffile, str);
   /* substitue "%d" by current run number */
   strcpy(str, fmt);
   if (strchr(str, '%'))
      sprintf(file, str, num);
   else
      strcpy(file, str);
   return 0;
}
BOOL lazy_file_exists (char * dir, char * file)
Definition at line 1355 of file lazylogger.c.
References FALSE, LAZY_STATISTICS::file_size, MAX_FILE_PATH, ss_file_find(), ss_file_size(), and TRUE.
Referenced by lazy_main().
       : lazy_file_exists
Purpose: check if file exists in dir by extracting its size
Input:
char * dir       data directory
char * file      file to be checked
Output:
Function value:
TRUE           file found
FALSE          file not found
\********************************************************************/
{
   char *list;
   char fullfile[MAX_FILE_PATH] = { '\0' };
   double file_size = 0;
   INT ret = ss_file_find(dir, file, &list);
   //printf("calling ss_file_find: dir = [%s] file = [%s] ret=[%i]\n",dir,file,ret);
   if ( ret == 1) {
      strcat(fullfile, dir);
      strcat(fullfile, file);
      file_size = ss_file_size(fullfile);
      //printf("file [%s] size = [%f] \n",fullfile, file_size);
      if ((lazyst.file_size = file_size) > 0) {
        free(list);
        return TRUE;
      }
   }
   free(list);
   return FALSE;
}
INT lazy_file_remove (char * pufile)
Definition at line 361 of file lazylogger.c.
References SS_FILE_ERROR, ss_file_remove(), SS_INVALID_NAME, SS_SUCCESS, and status.
Referenced by lazy_main().
{
   INT fHandle, status;
   /* open device */
   fHandle = open(pufile, O_RDONLY, 0644);
   if (fHandle == -1)
      return SS_INVALID_NAME;
   close(fHandle);
   status = ss_file_remove(pufile);
   if (status != 0)
      return SS_FILE_ERROR;
   return SS_SUCCESS;
}
INT lazy_load_params (HNDLE hDB, HNDLE hKey)
INT lazy_log_update (INT action, INT run, char * label, char * file, DWORD rm)
Definition at line 379 of file lazylogger.c.
References LAZY_STATISTICS::backfile, LAZY_SETTING::backlabel, blockn, cm_msg, cm_msg1(), cmd, LAZY_SETTING::commandAfter, LAZY_STATISTICS::cur_dev_size, DIR_SEPARATOR, DIR_SEPARATOR_STR, equal_ustring(), LAZY_STATISTICS::file_size, MAX_FILE_PATH, MINFO, NEW_FILE, LAZY_STATISTICS::nfiles, LAZY_SETTING::path, REMOVE_ENTRY, REMOVE_FILE, ss_system(), and LAZY_SETTING::type.
Referenced by lazy_main(), lazy_remove_entry(), and lazy_update_list().
{
   char str[MAX_FILE_PATH];
   INT blocks;
   /* log Lazy logger to midas.log only */
   if (action == NEW_FILE) {
      /* keep track of number of file on that channel */
      lazyst.nfiles++;
      if (equal_ustring(lazy.type, "FTP"))
         sprintf(str, "%s: (cp:%.1fs) %s %1.3lfMB file COPIED",
                 label, (float) perf_time / 1000., lazyst.backfile,
                 lazyst.file_size / 1024.0 / 1024.0);
      else if (equal_ustring(lazy.type, "Disk")) {
         if (lazy.path[0] != 0)
            if (lazy.path[strlen(lazy.path) - 1] != DIR_SEPARATOR)
               strcat(lazy.path, DIR_SEPARATOR_STR);
         sprintf(str, "%s[%i] (cp:%.1fs) %s%s %1.3lfMB  file NEW",
                 label, lazyst.nfiles, (float) perf_time / 1000.,
                 lazy.path, lazyst.backfile, lazyst.file_size / 1024.0 / 1024.0);
      } else if (equal_ustring(lazy.type, "Tape")) {
         blocks = (int) (lazyst.cur_dev_size / 32.0 / 1024.0) + lazyst.nfiles;
         /* June 2002, use variable blockn from the real tape position */
         sprintf(str, "%s[%i] (cp:%.1fs) %s/%s %1.3lfMB  file NEW (position at block %d)",
                 label, lazyst.nfiles, (float) perf_time / 1000.,
                 lazy.path, lazyst.backfile, lazyst.file_size / 1024.0 / 1024.0, blockn);
         if (lazy.commandAfter[0]) {
            char cmd[256];
            sprintf(cmd, "%s %s %i %s/%s %1.3lf %d", lazy.commandAfter,
                    lazy.backlabel, lazyst.nfiles, lazy.path, lazyst.backfile,
                    lazyst.file_size / 1024.0 / 1024.0, blockn);
            cm_msg(MINFO, "Lazy", "Exec post file write script:%s", cmd);
            ss_system(cmd);
         }
      }
   } else if (action == REMOVE_FILE)
      sprintf(str, "%i (rm:%ldms) %s file REMOVED", run, perf_time, file);
   else if (action == REMOVE_ENTRY)
      sprintf(str, "%s run#%i entry REMOVED", label, run);
   cm_msg(MINFO, "lazy_log_update", str);
   /* Now add this info also to a special log file */
   cm_msg1(MINFO, "lazy_log_update", "lazy", str);
   return 0;
}
INT lazy_main (INT channel, LAZY_INFO * pLall)
Definition at line 1389 of file lazylogger.c.
References abs, al_reset_alarm(), al_trigger_alarm(), LAZY_SETTING::alarm, AT_INTERNAL, LAZY_STATISTICS::backfile, LAZY_SETTING::backfmt, LAZY_SETTING::backlabel, build_done_list(), build_log_list(), LAZY_SETTING::capacity, cm_get_watchdog_params(), cm_msg, cm_set_watchdog_params(), cmd, cmp_log2donelist(), LAZY_SETTING::command, LAZY_STATISTICS::cur_dev_size, LAZY_STATISTICS::cur_run, data_fmt, db_find_key(), db_get_value(), DB_NO_ACCESS, db_save(), db_set_record(), db_set_value(), DB_SUCCESS, dev_type, LAZY_SETTING::dir, DIR_SEPARATOR, DIR_SEPARATOR_STR, equal_ustring(), FALSE, LAZY_STATISTICS::file_size, FORCE_EXIT, LAZY_SETTING::format, FORMAT_MIDAS, FORMAT_YBOS, full_bck_flag, hDB, LAZY_INFO::hKey, hKeyst, lazy_copy(), lazy_file_compose(), lazy_file_exists(), lazy_file_remove(), lazy_log_update(), lazy_maintain_check(), lazy_mutex, lazy_remove_entry(), lazy_select_purge(), lazy_update_list(), LOG_TYPE_DISK, LOG_TYPE_FTP, LOG_TYPE_TAPE, MAX_FILE_PATH, MERROR, MINFO, LAZY_INFO::name, LAZY_STATISTICS::nfiles, NOTHING_TODO, LAZY_SETTING::path, LAZY_SETTING::pupercent, REMOVE_FILE, size, ss_disk_free(), ss_disk_size(), SS_FILE_ERROR, ss_millitime(), ss_mutex_release(), ss_mutex_wait_for(), SS_NO_SPACE, SS_SUCCESS, ss_system(), ss_tape_close(), ss_tape_open(), ss_tape_unmount(), status, LAZY_SETTING::staybehind, SUCCESS, LAZY_SETTING::tapeAppend, TID_INT, TID_STRING, TRUE, and LAZY_SETTING::type.
Referenced by main().
       : lazy_main
Purpose: check if backup is necessary...
Input:
channel: Current channel number
*pLall :   Pointer to all channels
Output:
Function value:
\********************************************************************/
{
   DWORD cp_time;
   DIRLOG *pdirlog = NULL;
   INT *pdonelist = NULL;
   INT size, cur_acq_run, status, tobe_backup, purun;
   double freepercent, svfree;
   char str[MAX_FILE_PATH], pufile[MAX_FILE_PATH], inffile[MAX_FILE_PATH],
       outffile[MAX_FILE_PATH];
   BOOL donepurge, watchdog_flag;
   DWORD watchdog_timeout;
   LAZY_INFO *pLch;
   static BOOL eot_reached = FALSE;
   /* current channel */
   pLch = &pLall[channel];
   /* extract Data format from the struct */
   if (equal_ustring(lazy.format, "YBOS"))
      data_fmt = FORMAT_YBOS;
   else if (equal_ustring(lazy.format, "MIDAS"))
      data_fmt = FORMAT_MIDAS;
   else {
      cm_msg(MERROR, "Lazy", "Unknown data format %s (MIDAS, YBOS)", lazy.format);
      return DB_NO_ACCESS;
   }
   /* extract Device type from the struct */
   if (equal_ustring(lazy.type, "DISK"))
      dev_type = LOG_TYPE_DISK;
   else if (equal_ustring(lazy.type, "TAPE"))
      dev_type = LOG_TYPE_TAPE;
   else if (equal_ustring(lazy.type, "FTP"))
      dev_type = LOG_TYPE_FTP;
   else {
      cm_msg(MERROR, "Lazy", "Unknown device type %s (Disk, Tape, FTP)", lazy.type);
      return DB_NO_ACCESS;
   }
   /* make sure that we don't operate on the current DAQ file if so set to oldest */
   if (lazy.staybehind == 0) {
      cm_msg(MERROR, "Lazy", "Stay behind cannot be 0");
      return NOTHING_TODO;
   }
   /* Check if Tape is OK */
   /* ... */
   /* check if space on device (not empty tape label) */
   if (lazy.backlabel[0] == '\0') {
      full_bck_flag = TRUE;
      return NOTHING_TODO;
   } else {
      if (full_bck_flag) {
         full_bck_flag = FALSE;
         size = sizeof(lazyst);
         memset(&lazyst, 0, size);
         if (db_find_key(hDB, pLch->hKey, "Statistics", &hKeyst) == DB_SUCCESS) {
            status = db_set_record(hDB, hKeyst, &lazyst, size, 0);
            /* New session of lazy, apply append in case of Tape */
            /* DISK for debugging */
            if ((dev_type == LOG_TYPE_DISK) && lazy.tapeAppend) {
               /* Position Tape to end of Data */
               cm_msg(MINFO, "Lazy", "Positioning Tape to EOD");
            }
         } else
            cm_msg(MERROR, "lazy_main",
                   "did not find /Lazy/Lazy_%s/Statistics for zapping", pLch->name);
         // INT al_reset_alarm(char *alarm_name)
         if (dev_type == LOG_TYPE_TAPE)
            al_reset_alarm("Tape");
      }
   }
   /* check if data dir is none empty */
   if (lazy.dir[0] == '\0') {
      cm_msg(MINFO, "Lazy", "Please setup Data dir for input source path!");
      return NOTHING_TODO;
   }
   /* check if device path is set */
   if (lazy.path[0] == '\0') {
      cm_msg(MINFO, "Lazy", "Please setup backup device path too!");
      return NOTHING_TODO;
   }
   /* build logger dir listing */
   if (pdirlog == NULL)
      pdirlog = malloc(sizeof(DIRLOG));
   build_log_list(lazy.backfmt, lazy.dir, &pdirlog);
   /* build donelist comparing pdirlog and /Lazy/List */
   if (pdonelist == NULL)
      pdonelist = malloc(sizeof(INT));
   build_done_list(pLch->hKey, &pdonelist);
   /* compare list : run NOT in donelist AND run in dirlog */
   tobe_backup = cmp_log2donelist(pdirlog, pdonelist);
   /* cleanup memory */
   if (pdirlog)
      free(pdirlog);
   pdirlog = NULL;
   if (pdonelist)
      free(pdonelist);
   pdonelist = NULL;
   if (tobe_backup < 0)
      return NOTHING_TODO;
   /* ckeck if mode is on oldest (staybehind = -x)
      else take current run - keep file */
   if (lazy.staybehind < 0)
      lazyst.cur_run = tobe_backup;
   else
      lazyst.cur_run -= lazy.staybehind;
   /* Get current run number */
   size = sizeof(cur_acq_run);
   status =
       db_get_value(hDB, 0, "Runinfo/Run number", &cur_acq_run, &size, TID_INT, TRUE);
   assert(status == SUCCESS);
   /* update "maintain free space" */
   lazy_maintain_check(pLch->hKey, pLall);
  /***** Lock other clients out of this following code as
  it may access the other client info tree   *****/
   status = ss_mutex_wait_for(lazy_mutex, 5000);
   if (status != SS_SUCCESS) {
      /* exit for now and come back later */
      if (pdirlog != NULL)
         free(pdirlog);
      pdirlog = NULL;
      if (pdonelist != NULL)
         free(pdonelist);
      pdonelist = NULL;
      return NOTHING_TODO;
   }
   /* check SPACE and purge if necessary = % (1:99) */
   if (lazy.pupercent > 0) {
      if (pdirlog == NULL)
         pdirlog = malloc(sizeof(DIRLOG));
      /* cleanup memory */
      donepurge = FALSE;
      svfree = freepercent = 100. * ss_disk_free(lazy.dir) / ss_disk_size(lazy.dir);
      /* check purging action */
      while (freepercent <= (double) lazy.pupercent) {
         /* search file to purge : run in donelist AND run in dirlog */
         /* synchronize donelist to dir log in case user has purged
            some file by hand. Basically remove the run in the list if the
            file is not anymore in the source dir. */
         if (lazy_select_purge
             (pLch->hKey, channel, pLall, lazy.backfmt, lazy.dir, pufile, &purun) == 0) {
            /* check if beyond keep file + 1 */
            if (purun < (cur_acq_run - abs(lazy.staybehind) - 1)) {
               DWORD rm_time;
               /* remove file */
               rm_time = ss_millitime();
               status = lazy_file_remove(pufile);
               rm_time = ss_millitime() - rm_time;
               if (status == SS_FILE_ERROR)
                  cm_msg(MERROR, "Lazy", "lazy_file_remove failed on file %s", pufile);
               else {
                  status = lazy_log_update(REMOVE_FILE, purun, NULL, pufile, rm_time);
                  donepurge = TRUE;
                  /* update donelist (remove run entry as the file has been deleted */
                  if ((status = lazy_remove_entry(channel, pLall, purun)) != 0)
                     cm_msg(MERROR, "Lazy", "remove_entry not performed %d", status);
               }
            }
            freepercent = 100. * ss_disk_free(lazy.dir) / ss_disk_size(lazy.dir);
            if ((INT) svfree == (INT) freepercent)
               break;
         } else {
            if (donepurge)
               cm_msg(MINFO, "Lazy", "Can't purge more for now!");
            break;
         }
      }
   }
   /* end of if pupercent > 0 */
   /* cleanup memory */
   if (pdirlog != NULL)
      free(pdirlog);
   pdirlog = NULL;
   if (pdonelist != NULL)
      free(pdonelist);
   pdonelist = NULL;
  /***** Release the mutex  *****/
   status = ss_mutex_release(lazy_mutex);
   /* check if backup run is beyond keep */
   if (lazyst.cur_run >= (cur_acq_run - abs(lazy.staybehind)))
      return NOTHING_TODO;
   /* Compose the proper file name */
   status =
       lazy_file_compose(lazy.backfmt, lazy.dir, lazyst.cur_run, inffile,
                         lazyst.backfile);
   if (status != 0) {
      cm_msg(MERROR, "Lazy", "composition of file failed -%s-%s-%d-", lazy.backfmt,
             lazy.dir, lazyst.cur_run);
      return status;
   }
   /* Check again if the backup file is present in the logger dir */
   if (lazy_file_exists(lazy.dir, lazyst.backfile)) {
      /* compose the destination file name */
      if (dev_type == LOG_TYPE_DISK) {
         if (lazy.path[0] != 0)
            if (lazy.path[strlen(lazy.path) - 1] != DIR_SEPARATOR)
               strcat(lazy.path, DIR_SEPARATOR_STR);
         strcpy(outffile, lazy.path);
         strcat(outffile, lazyst.backfile);
      } else if (dev_type == LOG_TYPE_TAPE)
         strcpy(outffile, lazy.path);
      else if (dev_type == LOG_TYPE_FTP) {
         /* Format for FTP
            lazy.path=host,port,user,password,directory,filename[,umask]
            expect filename in format such as "bck%08d.mid" */
         /*
            if (lazy.path[0] != 0)
            if (lazy.path[strlen(lazy.path)-1] != DIR_SEPARATOR)
            strcat(lazy.path, DIR_SEPARATOR_STR);
          */
         strcpy(str, lazy.path);
         /* substitue "%d" for current run number */
         if (strchr(str, '%'))
            sprintf(outffile, str, lazyst.cur_run);
         else
            strcpy(outffile, str);
         //if (lazy.path[0] != 0)
         //  if (lazy.path[strlen(lazy.path)-1] != '/')
         //    strcat(lazy.path, "/");
         //  strcpy(outffile, lazy.path);
         //  strcat(outffile, ",");
         //  strcat(outffile, lazyst.backfile);
      }
      /* check if space on backup device */
      if ((lazy.capacity < (lazyst.cur_dev_size + lazyst.file_size)) || eot_reached) {
         char pre_label[32];
         /* save the last label for shell script */
         strcpy(pre_label, lazy.backlabel);
         /* Reset EOT reached */
         eot_reached = FALSE;
         /* not enough space => reset list label */
         lazy.backlabel[0] = '\0';
         size = sizeof(lazy.backlabel);
         db_set_value(hDB, pLch->hKey, "Settings/List label", lazy.backlabel, size, 1,
                      TID_STRING);
         full_bck_flag = TRUE;
         cm_msg(MINFO, "Lazy", "Not enough space for next copy on backup device!");
         /* rewind device if TAPE type */
         if (dev_type == LOG_TYPE_TAPE) {
            INT status, channel;
            char str[128];
            sprintf(str, "Tape %s is full with %d files", pre_label, lazyst.nfiles);
            cm_msg(MINFO, "Lazy", str);
            /* Setup alarm */
            lazy.alarm[0] = 0;
            size = sizeof(lazy.alarm);
            db_get_value(hDB, pLch->hKey, "Settings/Alarm Class", lazy.alarm, &size,
                         TID_STRING, TRUE);
            /* trigger alarm if defined */
            if (lazy.alarm[0])
               al_trigger_alarm("Tape",
                                "Tape full, Please remove current tape and load new one!",
                                lazy.alarm, "Tape full", AT_INTERNAL);
            /* run shell command if available */
            if (lazy.command[0]) {
               char cmd[256];
               sprintf(cmd, "%s %s %s %s", lazy.command, lazy.path, pLch->name,
                       pre_label);
               cm_msg(MINFO, "Lazy", "Exec post-rewind script:%s", cmd);
               ss_system(cmd);
            }
            cm_msg(MINFO, "Lazy", "backup device rewinding...");
            cm_get_watchdog_params(&watchdog_flag, &watchdog_timeout);
            cm_set_watchdog_params(watchdog_flag, 300000);      /* 5 min for tape rewind */
            status = ss_tape_open(outffile, O_RDONLY, &channel);
            if (channel < 0) {
               cm_msg(MERROR, "Lazy", "Cannot rewind tape %s - %d - %d", outffile,
                      channel, status);
               return NOTHING_TODO;
            }
            //else
            //    cm_msg(MINFO,"Lazy", "After call ss_tape_open used to rewind tape %s - %d - %d", outffile, channel, status);
            cm_msg(MINFO, "Lazy", "Calling ss_tape_unmount");
            ss_tape_unmount(channel);
            ss_tape_close(channel);
            cm_set_watchdog_params(watchdog_flag, watchdog_timeout);
            return NOTHING_TODO;
         }
      }
      /* Finally do the copy */
      cp_time = ss_millitime();
      if ((status = lazy_copy(outffile, inffile)) != 0) {
         if (status == SS_NO_SPACE) {
            /* Consider this case as EOT reached */
            eot_reached = TRUE;
            return status;
         } else if (status == FORCE_EXIT)
            return status;
         cm_msg(MERROR, "Lazy", "copy failed -%s-%s-%i", lazy.path, lazyst.backfile,
                status);
         return FORCE_EXIT;
      }
   } /* file exists */
   else {
      cm_msg(MERROR, "Lazy", "lazy_file_exists file %s doesn't exists", lazyst.backfile);
      return NOTHING_TODO;
   }
   /* Update the list */
   cp_time = ss_millitime() - cp_time;
   if ((status = lazy_update_list(pLch, cp_time)) != DB_SUCCESS) {
      cm_msg(MERROR, "Lazy", "lazy_update failed");
      return NOTHING_TODO;
   }
   /* generate/update a <channel>_recover.odb file when everything is Ok
      after each file copy */
   {
      char str[128];
      /* leave "list label" as it is, as long as the _recover.odb is loaded before
         the lazylogger is started with NO -z things should be fine */
      /* save the recover with "List Label" empty */
      if (lazy.dir[strlen(lazy.dir) - 1] != DIR_SEPARATOR)
         sprintf(str, "%s%c%s_recover.odb", lazy.dir, DIR_SEPARATOR, pLch->name);
      else
         sprintf(str, "%s%s_recover.odb", lazy.dir, pLch->name);
      db_save(hDB, pLch->hKey, str, TRUE);
   }
   return NOTHING_TODO;
}
void lazy_maintain_check (HNDLE hKey, LAZY_INFO * pLall)
Definition at line 782 of file lazylogger.c.
References cm_msg, db_get_value(), db_set_value(), FALSE, hDB, i, maintain_touched, MAX_LAZY_CHANNEL, MINFO, name, size, TID_INT, TID_STRING, and TRUE.
Referenced by lazy_main().
       : lazy_maintain_check
Purpose: Check if the "maintain free space" of any of the other matching
channels is != 0. matching correspond to the condition:
"data dir" && "filename format"
if found != 0 then set to 0 and inform
Input:
hKey   :   Current lazy channel key
*pLall :   Pointer to all channels
\********************************************************************/
{
   INT size;
   INT i, maintain;
   char dir[256], ff[128];
   char cdir[256], cff[128];
   char cmodulostr[8], modulostr[8];
   /* do test only if maintain has been touched */
   if (!maintain_touched)
      return;
   maintain_touched = FALSE;
   /* check is Maintain free is enabled */
   size = sizeof(maintain);
   db_get_value(hDB, hKey, "Settings/Maintain free space(%)", &maintain, &size, TID_INT,
                TRUE);
   if (maintain != 0) {
      /* scan other channels */
      /* get current specification */
      size = sizeof(cdir);
      db_get_value(hDB, hKey, "Settings/Data dir", cdir, &size, TID_STRING, TRUE);
      size = sizeof(cff);
      db_get_value(hDB, hKey, "Settings/filename format", cff, &size, TID_STRING, TRUE);
      size = sizeof(modulostr);
      db_get_value(hDB, hKey, "Settings/Modulo.Position", cmodulostr, &size, TID_STRING,
                   TRUE);
      /* build matching dir and ff */
      for (i = 0; i < MAX_LAZY_CHANNEL; i++) {
         if (((pLall + i)->hKey) && (hKey != (pLall + i)->hKey)) {      /* valid channel */
            size = sizeof(dir);
            db_get_value(hDB, (pLall + i)->hKey, "Settings/Data dir", dir, &size,
                         TID_STRING, TRUE);
            size = sizeof(ff);
            db_get_value(hDB, (pLall + i)->hKey, "Settings/filename format", ff, &size,
                         TID_STRING, TRUE);
            size = sizeof(modulostr);
            db_get_value(hDB, (pLall + i)->hKey, "Settings/Modulo.Position", modulostr,
                         &size, TID_STRING, TRUE);
            if ((strcmp(dir, cdir) == 0) && (strcmp(ff, cff) == 0) && !cmodulostr[0]
                && !modulostr[0]) {
               /* check "maintain free space" */
               size = sizeof(maintain);
               db_get_value(hDB, (pLall + i)->hKey, "Settings/Maintain free space(%)",
                            &maintain, &size, TID_INT, TRUE);
               if (maintain) {
                  /* disable and inform */
                  size = sizeof(maintain);
                  maintain = 0;
                  db_set_value(hDB, (pLall + i)->hKey, "Settings/Maintain free space(%)",
                               &maintain, size, 1, TID_INT);
                  cm_msg(MINFO, "lazy_maintain_check",
                         "Maintain free space on channel %s has been disable",
                         (pLall + i)->name);
               }
            }
         }
      }
   }
}
int lazy_remove_entry (INT ch, LAZY_INFO * pLall, int run)
Definition at line 858 of file lazylogger.c.
References cm_msg, db_delete_key(), db_enum_key(), db_find_key(), db_get_key(), db_get_record(), db_set_data(), DB_SUCCESS, FALSE, found, hDB, hKey, hSubkey, i, j, k, key, lazy_log_update(), match(), MAX_LAZY_CHANNEL, MERROR, name, KEY::num_values, REMOVE_ENTRY, size, TID_INT, KEY::total_size, and TRUE.
Referenced by lazy_main(), and lazy_select_purge().
       : lazy_remove_entry
Purpose: remove run entry in all the /Lazy_.../list being marked by
         lazy_select_purge
Input:
channel : Current Channel
*pLall  : Pointer to all channels
run     : run number to be removed
Output:
Function value:
0             success
-1            run not found
\********************************************************************/
{
   INT size, i, j, k;
   INT *potherlist = NULL, nother;
   BOOL found = FALSE;
   HNDLE hSubkey;
   KEY key;
   /* mark current channel for removing entry too */
   (pLall + channel)->match = TRUE;
   if (potherlist == NULL)
      potherlist = malloc(sizeof(INT));
   /* scan matching run number */
   for (k = 0; k < MAX_LAZY_CHANNEL; k++) {     /* skip if no dir and no ff match */
      if ((pLall + k)->match) {
         /* search for the proper array to remove the entry */
         for (i = 0;; i++) {
            found = FALSE;
            if (db_find_key(hDB, (pLall + k)->hKey, "List", &hKey) != DB_SUCCESS) {
               cm_msg(MERROR, "lazy_entry_remove", "Did not found %s/list",
                      (pLall + k)->name);
               return -1;
            }
            db_enum_key(hDB, hKey, i, &hSubkey);
            if (!hSubkey)
               break;
            db_get_key(hDB, hSubkey, &key);
            size = key.total_size;
            nother = key.num_values;
            potherlist = (INT *) realloc(potherlist, size);
            db_get_record(hDB, hSubkey, (char *) potherlist, &size, 0);
            /* match run number */
            for (j = 0; j < nother; j++) {
               if (*(potherlist + j) == run)
                  found = TRUE;
               if (found)
                  if (j + 1 < nother)
                     *(potherlist + j) = *(potherlist + j + 1);
            }
            /* delete label[] or update label[] */
            if (found) {
               nother--;
               if (nother > 0)
                  db_set_data(hDB, hSubkey, potherlist, nother * sizeof(INT), nother,
                              TID_INT);
               else
                  db_delete_key(hDB, hSubkey, FALSE);
               lazy_log_update(REMOVE_ENTRY, run, (pLall + k)->name, NULL, 0);
            }
         }
      }
   }
   if (potherlist)
      free(potherlist);
   potherlist = NULL;
   return 0;
}
INT lazy_select_purge (HNDLE hKey, INT ch, LAZY_INFO * pLall, char * fmt, char * dir, char * pufile, INT * run)
Definition at line 628 of file lazylogger.c.
References LAZY_SETTING::backfmt, build_done_list(), build_log_list(), db_get_value(), LAZY_SETTING::dir, FALSE, hDB, i, j, k, lazy_file_compose(), lazy_remove_entry(), match(), MAX_FILE_PATH, MAX_LAZY_CHANNEL, size, status, TID_STRING, and TRUE.
Referenced by lazy_main().
       : lazy_select_purge
Purpose: Search oldest run number which can be purged
condition : oldest run# in (pdo AND present in plog)
AND scan all the other channels based on the following
conditions:
"data dir" && "filename format" are the same &&
the /list/run_number exists in all the above condition.
Input:
hKey      : Current channel key
channel   : Current channel number
*pLall    : Pointer to all channels
fmt       : Format string
dir       : Directory string
Output:
fpufile   : file to purge
run       : corresponding run# to be purged
Function value:
0          success
-1         run not found
\********************************************************************/
{
   DIRLOG *pdirlog = NULL;
   INT *pdonelist = NULL, *potherlist = NULL, size;
   INT i, j, k, status, ndone, nother, nfile;
   BOOL mark;
   char pufile[MAX_FILE_PATH];
   char ddir[256], ff[128], strmodulo[8];
   char cdir[256], cff[128];
   /* Scan donelist from first element (oldest)
      check if run exists in dirlog
      if yes return file and run number */
   /* get current specification */
   size = sizeof(cdir);
   db_get_value(hDB, hKey, "Settings/Data dir", cdir, &size, TID_STRING, TRUE);
   size = sizeof(cff);
   db_get_value(hDB, hKey, "Settings/filename format", cff, &size, TID_STRING, TRUE);
   while (1) {
      /* try to find the oldest matching run present in the list AND on disk */
      /* build current done list */
      if (pdonelist == NULL)
         pdonelist = malloc(sizeof(INT));
      if (potherlist == NULL)
         potherlist = malloc(sizeof(INT));
      /* Build current done list (run list already backed up) */
      ndone = build_done_list(hKey, &pdonelist);
      /* build matching dir and file format (ff) */
      for (i = 0; i < MAX_LAZY_CHANNEL; i++) {
         (pLall + i)->match = FALSE;
         /* Check if key present && key different than currrent
            and if modulo is off */
         if (((pLall + i)->hKey) && (hKey != (pLall + i)->hKey)) {
            /* extract dir and ff */
            size = sizeof(strmodulo);
            db_get_value(hDB, (pLall + i)->hKey, "Settings/Modulo.Position", strmodulo,
                         &size, TID_STRING, TRUE);
            if (strmodulo[0]) {
               /* Modulo enabled, skip this channel */
               continue;
            }
            size = sizeof(ddir);
            db_get_value(hDB, (pLall + i)->hKey, "Settings/Data dir", ddir, &size,
                         TID_STRING, TRUE);
            size = sizeof(ff);
            db_get_value(hDB, (pLall + i)->hKey, "Settings/filename format", ff, &size,
                         TID_STRING, TRUE);
            /* if same dir && same ff => mark lazy channel */
            if ((strcmp(ddir, cdir) == 0) && (strcmp(ff, cff) == 0))
               (pLall + i)->match = TRUE;
         }
      }
      /* scan matching run number */
      for (i = 0; i < MAX_LAZY_CHANNEL; i++) {
         /* For all matches channels, build done list */
         if ((pLall + i)->match) {
            /* build done list for that channel */
            nother = build_done_list((pLall + i)->hKey, &potherlist);
            /* search for run match */
            for (k = 0; k < ndone; k++) {
               mark = FALSE;
               for (j = 0; j < nother; j++) {
                  if ((potherlist[j] == pdonelist[k]) && (pdonelist[k] != 0))
                     mark = TRUE;
               }
               if (!mark)
                  pdonelist[k] = 0;
            }
         }
      }
      /* Take the first run from pdonelist (already sorted) to purge */
      for (i = 0; i < ndone; i++) {
         if (pdonelist[i] != 0)
            break;
      }
      /* return -1 if no run found */
      if (i == ndone)
         return -1;
      /* pdonelist[i] is the oldest run common to all the valid channels */
      *run = pdonelist[i];
      if (pdonelist)
         free(pdonelist);
      pdonelist = NULL;
      if (potherlist)
         free(potherlist);
      potherlist = NULL;
      /* check if file is in the dir log (exists) */
      if (pdirlog == NULL)
         pdirlog = malloc(sizeof(DIRLOG));
      nfile = build_log_list(fmt, dir, &pdirlog);
      for (i = 0; i < nfile; i++) {
         if (pdirlog[i].run == *run) {
            status = lazy_file_compose(lazy.backfmt, lazy.dir, *run, fpufile, pufile);
            if (pdirlog)
               free(pdirlog);
            pdirlog = NULL;
            return 0;           /* found can be selected */
         }
      }
      if (pdirlog)
         free(pdirlog);
      pdirlog = NULL;
      /* file not found synchronize listings and try again */
      status = lazy_remove_entry(channel, pLall, *run);
   }
}
void lazy_settings_hotlink (HNDLE hDB, HNDLE hKey, void * info)
Definition at line 768 of file lazylogger.c.
References db_get_value(), FALSE, maintain_touched, size, TID_INT, and TRUE.
Referenced by main().
{
   INT size, maintain;
   /* check if Maintain has been touched */
   size = sizeof(maintain);
   db_get_value(hDB, hKey, "Maintain free space(%)", &maintain, &size, TID_INT, TRUE);
   if (maintain != 0)
      maintain_touched = TRUE;
   else
      maintain_touched = FALSE;
}
void lazy_statistics_update (INT cploop_time)
Definition at line 1035 of file lazylogger.c.
References LAZY_STATISTICS::bckfill, LAZY_SETTING::capacity, LAZY_STATISTICS::copy_rate, LAZY_STATISTICS::cur_dev_size, LAZY_STATISTICS::cur_size, db_send_changed_records(), LAZY_STATISTICS::file_size, lastsz, LAZY_STATISTICS::progress, and ss_millitime().
Referenced by lazy_copy().
       : lazy_statistics_update
Purpose: update the /lazy/statistics
Input:
INT cploop_time : time of the last call
Output:
Function value:
0           success
\********************************************************************/
{
   /* update rate [kb/s] statistics */
   if ((ss_millitime() - cploop_time) > 100)
      lazyst.copy_rate =
          1000.f * (lazyst.cur_size - lastsz) / (ss_millitime() - cploop_time);
   if (lazyst.copy_rate < 0.0)
      lazyst.copy_rate = 0.0;
   /* update % statistics */
   if (lazyst.file_size != 0.0f)
      lazyst.progress = (100.0f * (lazyst.cur_size / lazyst.file_size));
   else
      lazyst.progress = 0.0f;
   /* update backup % statistics */
   if (lazy.capacity > 0.0f)
      lazyst.bckfill = 100.0f * (lazyst.cur_dev_size / lazy.capacity);
   else
      lazyst.bckfill = 0.0f;
   lastsz = lazyst.cur_size;
   /* udate ODB statistics */
   db_send_changed_records();
}
INT lazy_update_list (LAZY_INFO * pLinfo, DWORD cp)
Definition at line 932 of file lazylogger.c.
References LAZY_STATISTICS::backfile, LAZY_SETTING::backlabel, cm_msg, LAZY_STATISTICS::cur_run, db_find_key(), db_get_data(), db_get_key(), db_send_changed_records(), db_set_data(), db_set_value(), DB_SUCCESS, hDB, hKey, LAZY_INFO::hKey, lazy_log_update(), MAX_FILE_PATH, msg_flag, MTALK, NEW_FILE, KEY::num_values, size, TID_INT, and KEY::total_size.
Referenced by lazy_main().
       : lazy_update_list
Purpose: update the /lazy/list tree with the info from lazy{}
Input:
*lLinfo: Current channel structure
cp     : Copy time in seconds
Output:
Function value:
DB_SUCCESS   : update ok
\********************************************************************/
{
   INT size, ifiles;
   char *ptape = NULL, str[MAX_FILE_PATH];
   KEY Keylabel;
   INT mone = -1;
   HNDLE hKeylabel;
   /* check if dir exists */
   if (db_find_key(hDB, pLinfo->hKey, "List", &hKey) != DB_SUCCESS) {   /* list doesn't exists */
      sprintf(str, "List/%s", lazy.backlabel);
      db_set_value(hDB, pLinfo->hKey, str, &mone, sizeof(INT), 1, TID_INT);
      db_find_key(hDB, pLinfo->hKey, "List", &hKey);
   }
   /*  record the saved run */
   if (db_find_key(hDB, hKey, lazy.backlabel, &hKeylabel) == DB_SUCCESS) {      /* run array already present ==> append run */
      db_get_key(hDB, hKeylabel, &Keylabel);
      ifiles = Keylabel.num_values;
      ptape = malloc(Keylabel.total_size);
      size = Keylabel.total_size;
      db_get_data(hDB, hKeylabel, ptape, &size, TID_INT);
      if ((size == sizeof(INT)) && (*ptape == -1)) {
         ifiles = 1;
         size = sizeof(INT);
         memcpy((char *) ptape, (char *) &lazyst.cur_run, sizeof(INT));
      } else {
         ptape = realloc((char *) ptape, size + sizeof(INT));
         memcpy((char *) ptape + size, (char *) &lazyst.cur_run, sizeof(INT));
         ifiles += 1;
         size += sizeof(INT);
      }
      db_set_data(hDB, hKeylabel, (char *) ptape, size, ifiles, TID_INT);
   } else {                     /* new run array ==> */
      size = sizeof(lazyst.cur_run);
      db_set_value(hDB, hKey, lazy.backlabel, &lazyst.cur_run, size, 1, TID_INT);
   }
   lazy_log_update(NEW_FILE, lazyst.cur_run, lazy.backlabel, lazyst.backfile, cp);
   if (msg_flag)
      cm_msg(MTALK, "Lazy", "         lazy job %s done!", lazyst.backfile);
   if (ptape)
      free(ptape);
   db_send_changed_records();
   return DB_SUCCESS;
}
int main (int argc, char ** argv)
Definition at line 1756 of file lazylogger.c.
References LAZY_INFO::active, channel, cm_connect_experiment1(), cm_disconnect_experiment(), cm_exist(), cm_get_environment(), cm_get_experiment_database(), cm_msg, cm_set_watchdog_params(), CM_SUCCESS, cm_yield(), daemon, db_create_record(), db_delete_key(), db_enum_key(), db_find_key(), db_get_data(), db_get_key(), db_get_record(), db_open_record(), db_set_record(), db_set_value(), DB_SUCCESS, debug, DEFAULT_ODB_SIZE, LAZY_SETTING::dir, equal_ustring(), expt_name, FALSE, FORCE_EXIT, hDB, LAZY_INFO::hKey, hKey, hKeyst, host_name, HOST_NAME_LENGTH, hSubkey, i, j, key, lazy_main(), lazy_mutex, lazy_settings_hotlink(), LAZY_SETTINGS_STRING, LAZY_STATISTICS_STRING, MAX_LAZY_CHANNEL, MERROR, MINFO, MODE_READ, MODE_WRITE, msg_flag, name, KEY::name, pcurrent_hKey, RPC_SHUTDOWN, run_state, size, SS_ABORT, ss_daemon_init(), ss_getchar(), ss_gets(), ss_kbhit(), ss_millitime(), ss_mutex_create(), status, TID_INT, TID_KEY, TID_STRING, TRUE, KEY::type, usage(), WATCHDOG_TIMEOUT, and zap_flag.
{
   char channel_name[32];
   char host_name[HOST_NAME_LENGTH];
   char expt_name[HOST_NAME_LENGTH];
   BOOL debug, daemon;
   INT i, msg, ch, size, status, mainlast_time;
   /* set default */
   host_name[0] = 0;
   expt_name[0] = 0;
   channel_name[0] = 0;
   zap_flag = FALSE;
   msg_flag = FALSE;
   debug = daemon = FALSE;
   /* set default */
   cm_get_environment(host_name, sizeof(host_name), expt_name, sizeof(expt_name));
   /* get parameters */
   for (i = 1; i < argc; i++) {
      if (argv[i][0] == '-' && argv[i][1] == 'd')
         debug = TRUE;
      else if (argv[i][0] == '-' && argv[i][1] == 'D')
         daemon = TRUE;
      else if (strncmp(argv[i], "-z", 2) == 0)
         zap_flag = TRUE;
      else if (strncmp(argv[i], "-t", 2) == 0)
         msg_flag = TRUE;
      else if (argv[i][0] == '-') {
         if (i + 1 >= argc || argv[i + 1][0] == '-')
            goto usage;
         if (strncmp(argv[i], "-e", 2) == 0)
            strcpy(expt_name, argv[++i]);
         else if (strncmp(argv[i], "-h", 2) == 0)
            strcpy(host_name, argv[++i]);
         else if (strncmp(argv[i], "-c", 2) == 0)
            strcpy(channel_name, argv[++i]);
      } else {
       usage:
         printf("Lazylogger: Multi channel background data copier\n");
         printf("usage: lazylogger [-h <Hostname>] [-e <Experiment>]\n");
         printf("                  [-z zap statistics] [-t (talk msg)\n");
         printf("                  [-c channel name (Disk) -D to start as a daemon\n\n");
         printf("Quick man :\n");
         printf("The Lazy/Settings tree is composed of the following parameters:\n");
         printf
             ("Maintain free space [%%](0): purge source device to maintain free space on the source directory\n");
         printf("                      (0) : no purge      \n");
         printf
             ("Stay behind  (-3)         : If negative number : lazylog runs starting from the OLDEST\n");
         printf
             ("                             run file sitting in the 'Dir data' to the current acquisition\n");
         printf("                             run minus the 'Stay behind number'\n");
         printf
             ("                            If positive number : lazylog starts from the current\n");
         printf
             ("                             acquisition run minus 'Stay behind number' \n");
         printf
             ("Alarm Class               : Specify the Class to be used in case of Tape Full condition\n");
         printf
             ("Running condition         : active/deactive lazylogger under given condition i.e:\n");
         printf
             ("                           'ALWAYS' (default)     : Independent of the ACQ state ...\n");
         printf("                           'NEVER'                : ...\n");
         printf("                           'WHILE_ACQ_NOT_RUNNING': ...\n");
         printf
             ("                           '/alias/max_rate < 200'    (max_rate is a link)\n");
         printf
             ("                           '/equipment/scaler/variables/scal[4] < 23.45'\n");
         printf
             ("                           '/equipment/trigger/statistics/events per sec. < 400'\n");
         printf("Data dir                  : Directory of the run to be lazylogged \n");
         printf("Data format               : Data format (YBOS/MIDAS)\n");
         printf("Filename format           : Run format i.e. run%%05d.mid \n");
         printf("List label                : Label of destination save_set.\n");
         printf("                            Prevent lazylogger to run if not given.\n");
         printf
             ("                            Will be reset if maximum capacity reached.\n");
         printf
             ("Execute after rewind      : Execute the command <cmd> after rewind complete\n");
         printf
             ("                          : args passed are: 'device path' 'channel name' 'list label'\n");
         printf
             ("                          : The actual command will look like: <cmd> /dev/nst0 Tape Data_2000\n");
         printf
             ("Backup type               : Destination device type (Disk, Tape, FTP)\n");
         printf
             ("Path                      : Destination path (file.ext, /dev/nst0, ftp...)\n");
         printf
             ("                            in case of FTP type, the 'Path' entry should be:\n");
         printf
             ("                            host, port, user, password, directory, run%%05d.mid\n");
         printf
             ("Capacity (Bytes)          : Maximum capacity of the destination device.\n");
         printf
             ("modulo                    : Enable multiple lazy on same source. Ex: 3ch : 3.0, 3.1, 3.2\n");
         printf
             ("tapeAppend                : Enable positioning of the TAPE to EOD before each lazy copy\n");
         return 0;
      }
   }
   /* Handle SIGPIPE signals generated from errors on the pipe */
#ifdef SIGPIPE
   signal(SIGPIPE, SIG_IGN);
#endif
   if (daemon) {
      printf("Becoming a daemon...\n");
      ss_daemon_init(FALSE);
   }
   /* connect to experiment */
   status =
       cm_connect_experiment1(host_name, expt_name, "Lazy", 0, DEFAULT_ODB_SIZE,
                              WATCHDOG_TIMEOUT);
   if (status != CM_SUCCESS)
      return 1;
   /* create a common mutex for the independent lazylogger */
   status = ss_mutex_create("LAZY", &lazy_mutex);
   /* check lazy status for multiple channels */
   cm_get_experiment_database(&hDB, &hKey);
   if (db_find_key(hDB, 0, "/Lazy", &hKey) == DB_SUCCESS) {
      HNDLE hSubkey;
      KEY key;
      char strclient[32];
      INT j = 0;
      for (i = 0;; i++) {
         db_enum_key(hDB, hKey, i, &hSubkey);
         if (!hSubkey)
            break;
         db_get_key(hDB, hSubkey, &key);
         if (key.type == TID_KEY) {
            /* compose client name */
            sprintf(strclient, "Lazy_%s", key.name);
            if (cm_exist(strclient, TRUE) == CM_SUCCESS)
               lazyinfo[j].active = TRUE;
            else
               lazyinfo[j].active = FALSE;
            strcpy(lazyinfo[j].name, key.name);
            lazyinfo[j].hKey = hSubkey;
            j++;
         }
      }
   } else {
      /* create settings tree */
      char str[32];
      channel = 0;
      if (channel_name[0] != 0)
         sprintf(lazyinfo[channel].name, channel_name);
      sprintf(str, "/Lazy/%s/Settings", lazyinfo[channel].name);
      db_create_record(hDB, 0, str, LAZY_SETTINGS_STRING);
   }
   {                            /* Selection of client */
      INT i, j;
      char str[32];
      if (lazyinfo[0].hKey) {
         if (channel_name[0] == 0) {
            /* command prompt */
            printf(" Available Lazy channels to connect to:\n");
            i = 0;
            j = 1;
            while (lazyinfo[i].hKey) {
               if (!lazyinfo[i].active)
                  printf("%d) Lazy %s \n", j, lazyinfo[i].name);
               else
                  printf(".) Lazy %s already active\n", lazyinfo[i].name);
               j++;
               i++;
            }
            printf("Enter client number or new lazy client name: ");
            i = atoi(ss_gets(str, 32));
            if ((i == 0) && ((strlen(str) == 0) || (strncmp(str, " ", 1) == 0))) {
               cm_msg(MERROR, "Lazy", "Please specify a valid channel name (%s)", str);
               goto error;
            }
         } else {
            /* Skip the command prompt for serving the -c option */
            /*
               scan if channel_name already exists
               Yes : check if client is running
               Yes : get out (goto error)
               No  : connect (extract index)
               No  : new channel (i=0)
             */
            i = 0;
            j = -1;
            while (lazyinfo[i].hKey) {
               if (equal_ustring(channel_name, lazyinfo[i].name)) {
                  /* correct name => check active  */
                  if (lazyinfo[i].active) {
                     cm_msg(MERROR, "Lazy", "Lazy channel " "%s" " already running!",
                            lazyinfo[i].name);
                     goto error;
                  }
                  j = i;
               }
               i++;
            }
            if (j == -1) {
               /* new entry */
               i = 0;
               sprintf(str, "%s", channel_name);
            } else {
               /* connect to */
               i = j + 1;
            }
         }
         if (i == 0) {          /* new entry */
            char strclient[32];
            for (j = 0; j < MAX_LAZY_CHANNEL; j++) {
               if (lazyinfo[j].hKey == 0) {
                  /* compose client name */
                  sprintf(strclient, "Lazy_%s", str);
                  if (cm_exist(strclient, TRUE) == CM_SUCCESS)
                     lazyinfo[j].active = TRUE;
                  else
                     lazyinfo[j].active = FALSE;
                  strcpy(lazyinfo[j].name, str);
                  lazyinfo[j].hKey = 0;
                  channel = j;
                  break;
               }
            }
         } else if (!lazyinfo[i - 1].active)
            channel = i - 1;
         else
            channel = -1;
      }
      if ((channel < 0) && (lazyinfo[channel].hKey != 0))
         goto error;
      if (channel < 0)
         channel = 0;
      {                         /* creation of the lazy channel */
         char str[128];
         if (lazyinfo[channel].hKey == 0)
            printf(" Creating Lazy channel %s\n", lazyinfo[channel].name);
         /* create/update settings */
         sprintf(str, "/Lazy/%s/Settings", lazyinfo[channel].name);
         db_create_record(hDB, 0, str, LAZY_SETTINGS_STRING);
         /* create/update statistics */
         sprintf(str, "/Lazy/%s/Statistics", lazyinfo[channel].name);
         db_create_record(hDB, 0, str, LAZY_STATISTICS_STRING);
         sprintf(str, "/Lazy/%s", lazyinfo[channel].name);
         db_find_key(hDB, 0, str, &lazyinfo[channel].hKey);
      }
   }
   /* disconnect  from expriment */
   cm_disconnect_experiment();
   {                            /* reconnect to experiment with proper name */
      char str[32];
      sprintf(str, "Lazy_%s", lazyinfo[channel].name);
      status =
          cm_connect_experiment1(host_name, expt_name, str, 0, DEFAULT_ODB_SIZE,
                                 WATCHDOG_TIMEOUT);
   }
   if (status != CM_SUCCESS)
      goto error;
   cm_get_experiment_database(&hDB, &hKey);
   /* Remove temporary Lazy entry */
   {
      HNDLE hPkey;
      status = db_find_key(hDB, 0, "Programs/Lazy", &hPkey);
      if (status == DB_SUCCESS) {
         status = db_delete_key(hDB, hPkey, FALSE);
         if (status != DB_SUCCESS) {
            cm_msg(MERROR, "Lazy", "Cannot delete /Programs/Lazy");
         }
      }
   }
   /* turn on keepalive messages with increased timeout */
   if (debug)
      cm_set_watchdog_params(TRUE, 0);
   printf("Lazy_%s starting... " "!" " to exit \n", lazyinfo[channel].name);
   if (zap_flag) {
      /* reset the statistics */
      cm_msg(MINFO, "Lazy", "zapping %s/statistics content", lazyinfo[channel].name);
      size = sizeof(lazyst);
      memset(&lazyst, 0, size);
      if (db_find_key(hDB, lazyinfo[channel].hKey, "Statistics", &hKeyst) == DB_SUCCESS)
         status = db_set_record(hDB, hKeyst, &lazyst, size, 0);
      else
         cm_msg(MERROR, "Lazy", "did not find %s/Statistics for zapping",
                lazyinfo[channel].name);
   }
   /* get value once & hot links the run state */
   db_find_key(hDB, 0, "/runinfo/state", &hKey);
   size = sizeof(run_state);
   db_get_data(hDB, hKey, &run_state, &size, TID_INT);
   status =
       db_open_record(hDB, hKey, &run_state, sizeof(run_state), MODE_READ, NULL, NULL);
   if (status != DB_SUCCESS) {
      cm_msg(MERROR, "Lazy", "cannot open /runinfo/state record");
   }
   /* hot link for statistics in write mode */
   size = sizeof(lazyst);
   if (db_find_key(hDB, lazyinfo[channel].hKey, "Statistics", &hKey) == DB_SUCCESS)
      db_get_record(hDB, hKey, &lazyst, &size, 0);
   status = db_open_record(hDB, hKey, &lazyst, sizeof(lazyst), MODE_WRITE, NULL, NULL);
   if (status != DB_SUCCESS) {
      cm_msg(MERROR, "Lazy", "cannot open %s/Statistics record", lazyinfo[channel].name);
   }
   /* get /settings once & hot link settings in read mode */
   db_find_key(hDB, lazyinfo[channel].hKey, "Settings", &hKey);
   size = sizeof(lazy);
   status = db_open_record(hDB, hKey, &lazy, sizeof(lazy)
                           , MODE_READ, lazy_settings_hotlink, NULL);
   if (status != DB_SUCCESS) {
      cm_msg(MERROR, "Lazy", "cannot open %s/Settings record", lazyinfo[channel].name);
   }
   /* set global key for that channel */
   pcurrent_hKey = lazyinfo[channel].hKey;
   /* set Data dir from /logger if local is empty & /logger exists */
   if ((lazy.dir[0] == '\0') &&
       (db_find_key(hDB, 0, "/Logger/Data dir", &hKey) == DB_SUCCESS)) {
      size = sizeof(lazy.dir);
      db_get_data(hDB, hKey, lazy.dir, &size, TID_STRING);
      db_set_value(hDB, lazyinfo[channel].hKey, "Settings/Data dir", lazy.dir, size, 1,
                   TID_STRING);
   }
   mainlast_time = 0;
   /* initialize ss_getchar() */
   ss_getchar(0);
   do {
      msg = cm_yield(2000);
      if ((ss_millitime() - mainlast_time) > 10000) {
         status = lazy_main(channel, &lazyinfo[0]);
         if (status == FORCE_EXIT) {
            cm_msg(MERROR, "lazy", "Previous error forces task exit");
            break;
         }
         mainlast_time = ss_millitime();
      }
      ch = 0;
      while (ss_kbhit()) {
         ch = ss_getchar(0);
         if (ch == -1)
            ch = getchar();
         if ((char) ch == '!')
            break;
      }
   } while (msg != RPC_SHUTDOWN && msg != SS_ABORT && ch != '!');
 error:
   cm_disconnect_experiment();
   return 1;
}
INT moduloCheck (INT lModulo, INT lPosition, INT lrun)
Definition at line 429 of file lazylogger.c.
Referenced by build_log_list().
       : moduleCheck
Purpose: return valid run number in case of Modulo function enabled
         or zero if not.
Input:
lModulo   : number of lazy channel
lPosition : Position of the current channel
lrun      : current run to test
Function value:
valid run number (0=skip run)
\********************************************************************/
{
   if (lModulo) {
      if ((lrun % lModulo) == lPosition)
         return lrun;
      else
         return 0;
   } else
      return lrun;
}
INT ss_run_extract (char * name)
Definition at line 327 of file lazylogger.c.
References found, and j.
Referenced by build_log_list().
       : ss_run_extract
Purpose: extract the contigious digit from the string to make up a
run number.
Input:
char * name    string to search
Output:
Function value:
INT        run number
0 if no extraction
\********************************************************************/
{
   char run_str[32], *pb, *pe;
   int j = 0, found = 0;
   pb = pe = NULL;
   memset(run_str, 0, sizeof(run_str));
   for (j = 0; j < (int) strlen(name); j++) {
      if (!found) {
         if (isdigit(name[j])) {
            found = 1;
            pb = name + j;
         }
      } else if (isdigit(name[j]) == 0) {
         pe = name + j;
         break;
      }
   }
   strncpy(run_str, pb, pe - pb);
   return (atoi(run_str));
}
Variable Documentation
INT blockn = 0
Definition at line 304 of file lazylogger.c.
Referenced by lazy_copy(), lazy_log_update(), and tape_dir().
INT channel = -1
Definition at line 291 of file lazylogger.c.
BOOL copy_continue = TRUE
Definition at line 300 of file lazylogger.c.
Referenced by lazy_copy().
INT data_fmt
Definition at line 301 of file lazylogger.c.
Referenced by data_format_check(), lazy_copy(), lazy_main(), and main().
INT dev_type
Definition at line 301 of file lazylogger.c.
Referenced by lazy_copy(), and lazy_main().
BOOL full_bck_flag = FALSE
Definition at line 303 of file lazylogger.c.
Referenced by lazy_main().
HNDLE hDB
Definition at line 295 of file lazylogger.c.
INT hDev
Definition at line 298 of file lazylogger.c.
Referenced by lazy_copy().
HNDLE hKey
Definition at line 295 of file lazylogger.c.
HNDLE hKeyst
Definition at line 297 of file lazylogger.c.
Referenced by lazy_main(), and main().
float lastsz
Definition at line 296 of file lazylogger.c.
Referenced by lazy_statistics_update().
LAZY_SETTING lazy
Definition at line 265 of file lazylogger.c.
INT lazy_mutex
Definition at line 294 of file lazylogger.c.
Referenced by lazy_main(), and main().
LAZY_INFO lazyinfo[MAX_LAZY_CHANNEL]
Initial value:
 { {0, FALSE, FALSE, "Tape"}, {0, FALSE, FALSE, ""}
, {0, FALSE, FALSE, ""}, {0, FALSE, FALSE, ""}
}
Definition at line 288 of file lazylogger.c.
char lazylog[MAX_STRING_LENGTH]
Definition at line 302 of file lazylogger.c.
LAZY_STATISTICS lazyst
Definition at line 278 of file lazylogger.c.
BOOL maintain_touched = FALSE
Definition at line 303 of file lazylogger.c.
Referenced by lazy_maintain_check(), and lazy_settings_hotlink().
BOOL msg_flag
Definition at line 299 of file lazylogger.c.
Referenced by lazy_copy(), lazy_update_list(), and main().
HNDLE pcurrent_hKey
Definition at line 295 of file lazylogger.c.
Referenced by main().
INT run_state
PROGRAM: crate.cpp DESCRIPTION: Control and readout of CAEN V1724 digitizers. author: V.Tishchenko date: 12-Aug-2012
Modifications:
Definition at line 298 of file lazylogger.c.
INT tot_dirlog_size
Definition at line 298 of file lazylogger.c.
Referenced by build_log_list(), and cmp_log2donelist().
INT tot_do_size
Definition at line 298 of file lazylogger.c.
Referenced by build_done_list(), and cmp_log2donelist().
BOOL zap_flag
Definition at line 299 of file lazylogger.c.
Referenced by main().