AlcapDAQ: midas/mscb/embedded/lcd_menu.c File Reference
midas/mscb/embedded/lcd_menu.c File Reference
#include <stdio.h>
#include <string.h>
#include "mscb.h"
Data Structures
struct NAME_TABLE
Functions
unsigned char application_display (bit init)
void user_write (unsigned char index) reentrant
void display_value (MSCB_INFO_VAR *pvar, void *pd)
void var_inc (MSCB_INFO_VAR *pvar, char sign)
void display_name (unsigned char index, MSCB_INFO_VAR *pvar)
void lcd_menu ()
Variables
MSCB_INFO_VAR code variables []
SYS_INFO sys_info
bit flash_param
bit reboot
bit b0
bit b1
bit b2
bit b3
unsigned char idata n_variables
bit startup = 1
bit in_menu = 0
bit system_menu = 0
bit enter_mode = 0
unsigned char var_index = 0
idata float f_var
NAME_TABLE code prefix_table []
NAME_TABLE code unit_table []
unsigned char n_sysvar = 4
MSCB_INFO_VAR code sysvar []
Function Documentation
unsigned char application_display (bit init)
Definition at line 352 of file scs_1000.c.
References b0, b1, b2, b3, lcd_clear(), lcd_goto(), moving_x, moving_y, RELAIS0, RELAIS1, RELAIS2, RELAIS3, user_data, and user_write().
Referenced by lcd_menu().
{
static bit b0_old = 0, b1_old = 0, b2_old = 0, b3_old = 0;
   if (init)
      lcd_clear();
   /* display first two ADCs */
   lcd_goto(0, 0);
   printf("0:%6.3fV", user_data.adc[0]);
   lcd_goto(10, 0);
   printf("1:%6.3fV", user_data.adc[1]);
   /* show state of relais 0&1 */
   lcd_goto(0, 1);
   printf("Rel0: %s", user_data.relais[0] ? "ON " : "OFF");
   lcd_goto(10, 1);
   printf("Rel1: %s", user_data.relais[1] ? "ON " : "OFF");
   /* toggle relais 0 with button 1 */
   if (b1 && !b1_old) {
      user_data.relais[0] = !user_data.relais[0];
      user_write(0);
   }
   /* toggle relais 1 with button 3 */
   if (b3 && !b3_old) {
      user_data.relais[1] = !user_data.relais[1];
      user_write(1);
   }
   /* enter menu on button 0 or 2 */
   if (!init)
      if ((b0 && !b0_old) || (b2 && !b2_old))
         return 1;
   b0_old = b0;
   b1_old = b1;
   b2_old = b2;
   b3_old = b3;
   return 0;
}
void display_name (unsigned char index, MSCB_INFO_VAR * pvar)
Definition at line 262 of file lcd_menu.c.
References lcd_goto(), and MSCB_INFO_VAR::name.
Referenced by interprete(), lcd_menu(), and show_hist_config_page().
{
   char idata str[10];
   /* display variable name */
   lcd_goto(0, 0);
   memcpy(str, pvar->name, 8);
   str[8] = 0;
   printf("%2bd:%s", index, str);
   puts("        ");
}
void display_value (MSCB_INFO_VAR * pvar, void * pd)
Definition at line 114 of file lcd_menu.c.
References MSCB_INFO_VAR::flags, i, NAME_TABLE::id, lcd_goto(), MSCBF_FLOAT, MSCBF_SIGNED, name, MSCB_INFO_VAR::prefix, prefix_table, MSCB_INFO_VAR::unit, UNIT_STRING, unit_table, and MSCB_INFO_VAR::width.
Referenced by lcd_menu().
{
   unsigned char i, unit_len;
   char idata str[10];
   lcd_goto(10, 0);
   if (pvar->unit == UNIT_STRING) {
      strncpy(str, (char *)pd, 8);
      puts(str);
   } else {
      str[0] = 0;
      /* evaluate prefix */
      if (pvar->prefix) {
         for (i = 0; prefix_table[i].id; i++)
            if (prefix_table[i].id == pvar->prefix)
               break;
         if (prefix_table[i].id)
            strcat(str, prefix_table[i].name);
      }
      /* evaluate unit */
      if (pvar->unit) {
         for (i = 0; unit_table[i].id; i++)
            if (unit_table[i].id == pvar->unit)
               break;
         if (unit_table[i].id)
            strcat(str, unit_table[i].name);
      }
      unit_len = strlen(str);
      switch (pvar->width) {
      case 0:
         puts("          ");
         break;
      case 1:
         if (pvar->flags & MSCBF_SIGNED)
            printf("%b*bd", 10-unit_len, *((char *) pd));
         else
            printf("%b*bu", 10-unit_len, *((unsigned char *) pd));
         break;
      case 2:
         if (pvar->flags & MSCBF_SIGNED)
            printf("%b*d", 10-unit_len, *((short *) pd));
         else
            printf("%b*u", 10-unit_len, *((unsigned short *) pd));
         break;
      case 4:
         if (pvar->flags & MSCBF_FLOAT)
            printf("%b*.3f", 10-unit_len, *((float *) pd));
         else {
            if (pvar->flags & MSCBF_SIGNED)
               printf("%b*ld", 10-unit_len, *((long *) pd));
            else
               printf("%b*lu", 10-unit_len, *((unsigned long *) pd));
         }
         break;
      }
      puts(str);
   }
}
void lcd_menu (void)
Definition at line 276 of file lcd_menu.c.
References application_display(), b0, b1, b2, b3, delay_ms(), display_name(), display_value(), enter_mode, f_var, MSCB_INFO_VAR::flags, flash_param, i, in_menu, lcd_clear(), lcd_goto(), MSCBF_DATALESS, MSCBF_REMOUT, n_sysvar, n_variables, reboot, send_remote_var(), startup, system_menu, sysvar, time, MSCB_INFO_VAR::ud, user_write(), var_inc(), var_index, variables, and MSCB_INFO_VAR::width.
Referenced by user_loop().
{
   static idata unsigned long last_disp = 0, last_b2 = 0, last_b3 = 0;
   static bit b0_old = 0, b1_old = 0, b2_old = 0, b3_old = 0;
   MSCB_INFO_VAR *pvar;
   unsigned char i;
   /* clear startup screen after 3 sec. */
   if (startup) {
      if(time() > 300) {
         startup = 0;
         lcd_clear();
      } else
        return;
   }
   /* do menu business only every 100ms */
   if (time() > last_disp+10) {
      last_disp = time();
      if (system_menu)
         pvar = &sysvar[var_index];
      else
         pvar = &variables[var_index];
      if (!in_menu) {
         /* if not in menu, call application display */
         if (application_display(0))
            in_menu = 1;
      } else {
         if (enter_mode) {
            /* display variables */
            display_value(pvar, &f_var);
            lcd_goto(0, 1);
            puts("ESC ENTER   -    + ");
            /* evaluate ESC button */
            if (b0 && !b0_old)
               enter_mode = 0;
            /* evaluate ENTER button */
            if (b1 && !b1_old) {
               enter_mode = 0;
               memcpy(pvar->ud, &f_var, pvar->width);
               if (system_menu) {
                  /* flash new address */
                  if (var_index == 0 || var_index == 1)
                     flash_param = 1;
               } else {
                  user_write(var_index);
#ifdef SCS_1000
                  if (variables[var_index].flags & MSCBF_REMOUT)
                     send_remote_var(var_index);
#endif
               }
            }
            /* evaluate "-" button */
            if (b2 && !b2_old) {
               var_inc(pvar, -1);
               last_b2 = time();
            }
            if (b2 && time() > last_b2 + 70)
               var_inc(pvar, -1);
            if (!b2)
               last_b2 = 0;
            /* evaluate "+" button */
            if (b3 && !b3_old) {
               var_inc(pvar, 1);
               last_b3 = time();
            }
            if (b3 && time() > last_b3 + 70)
               var_inc(pvar, 1);
            if (!b3)
               last_b3 = 0;
         } else {
            /* display variables */
            display_name(var_index, pvar);
            display_value(pvar, pvar->ud);
            lcd_goto(0, 1);
            if (pvar->delta > 0 || (pvar->flags & MSCBF_DATALESS))
               puts("ESC ENTER  PREV NEXT");
            else
               puts("ESC        PREV NEXT");
            /* evaluate ESC button */
            if (b0 && !b0_old) {
               if (system_menu) {
                  system_menu = 0;
                  var_index = 0;
               } else {
                  in_menu = 0;
                  application_display(1);
               }
            }
            /* evaluate ENTER button */
            if (b1 && !b1_old) {
               if (pvar->width <= 4 && pvar->width > 0) {
                  enter_mode = 1;
                  memcpy(&f_var, pvar->ud, pvar->width);
               }
               /* check for flash command */
               if (system_menu && var_index == 2) {
                  flash_param = 1;
                  lcd_clear();
                  lcd_goto(0, 0);
                  puts("Parameters written");
                  lcd_goto(0, 1);
                  puts("to flash memory.");
                  delay_ms(3000);
               }
               /* check for reboot command */
               if (system_menu && var_index == 3)
                  reboot = 1;
            }
            /* evaluate prev button */
            if (b2 && !b2_old) {
               if (var_index == 0)
                 var_index = n_variables-1;
               else
                 var_index--;
               last_b2 = time();
            }
            if (b2 && time() > last_b2 + 70) {
               if (var_index == 0)
                 var_index = n_variables-1;
               else
                 var_index--;
            }
            if (!b2)
               last_b2 = 0;
            if (system_menu)
               i = n_sysvar;
            else
               i = n_variables;
            /* evaluate next button */
            if (b3 && !b3_old) {
               var_index = (var_index + 1) % i;
               last_b3 = time();
            }
            if (b3 && time() > last_b3 + 70)
               var_index = (var_index + 1) % i;
            if (!b3)
               last_b3 = 0;
            /* check for system menu */
            if (b2 && b3 && !system_menu) {
               var_index = 0;
               system_menu = 1;
            }
         }
      }
      b0_old = b0;
      b1_old = b1;
      b2_old = b2;
      b3_old = b3;
   }
}
void user_write (unsigned char index)
Definition at line 251 of file hvr_200.c.
{
   if (index == 0 || index == 1 || index == 4) {
      /* reset trip */
      user_data[cur_sub_addr()].status &= ~STATUS_ILIMIT;
      /* indicate new demand voltage */
      chn_bits[cur_sub_addr()] |= DEMAND_CHANGED;
   }
   /* re-check voltage limit */
   if (index == 8) {
      chn_bits[cur_sub_addr()] |= DEMAND_CHANGED;
   }
}
void var_inc (MSCB_INFO_VAR * pvar, char sign)
Definition at line 185 of file lcd_menu.c.
References f_var, MSCB_INFO_VAR::flags, MSCBF_FLOAT, MSCBF_SIGNED, MSCB_INFO_VAR::unit, UNIT_STRING, and MSCB_INFO_VAR::width.
Referenced by lcd_menu().
{
   if (pvar->unit == UNIT_STRING)
      return;
   switch (pvar->width) {
   case 0:
      return;
      break;
   case 1:
      if (pvar->flags & MSCBF_SIGNED) {
         *((char *) &f_var) += pvar->delta * sign;
         if (*((char *) &f_var) < pvar->min)
            *((char *) &f_var) = pvar->min;
         if (*((char *) &f_var) > pvar->max)
            *((char *) &f_var) = pvar->max;
      } else {
         if (sign == -1 && *((unsigned char *) &f_var) == pvar->min)
            break;
         *((unsigned char *) &f_var) += pvar->delta * sign;
         if (*((unsigned char *) &f_var) < pvar->min)
            *((unsigned char *) &f_var) = pvar->min;
         if (*((unsigned char *) &f_var) > pvar->max)
            *((unsigned char *) &f_var) = pvar->max;
      }
      break;
   case 2:
      if (pvar->flags & MSCBF_SIGNED) {
         *((short *) &f_var) += pvar->delta * sign;
         if (*((short *) &f_var) < pvar->min)
            *((short *) &f_var) = pvar->min;
         if (*((short *) &f_var) > pvar->max)
            *((short *) &f_var) = pvar->max;
      } else {
         if (sign == -1 && *((unsigned short *) &f_var) == pvar->min)
            break;
         *((unsigned short *) &f_var) += pvar->delta * sign;
         if (*((unsigned short *) &f_var) < pvar->min)
            *((unsigned short *) &f_var) = pvar->min;
         if (*((unsigned short *) &f_var) > pvar->max)
            *((unsigned short *) &f_var) = pvar->max;
      }
      break;
   case 4:
      if (pvar->flags & MSCBF_FLOAT) {
         f_var += pvar->delta * sign;
         if (f_var < pvar->min)
            f_var = pvar->min;
         if (f_var > pvar->max)
            f_var = pvar->max;
      } else {
         if (pvar->flags & MSCBF_SIGNED) {
            *((long *) &f_var) += pvar->delta * sign;
            if (*((long *) &f_var) < pvar->min)
               *((long *) &f_var) = pvar->min;
            if (*((long *) &f_var) > pvar->max)
               *((long *) &f_var) = pvar->max;
         } else {
            if (sign == -1 && *((unsigned long *) &f_var) == pvar->min)
               break;
            *((unsigned long *) &f_var) += pvar->delta * sign;
            if (*((unsigned long *) &f_var) < pvar->min)
               *((unsigned long *) &f_var) = pvar->min;
            if (*((unsigned long *) &f_var) > pvar->max)
               *((unsigned long *) &f_var) = pvar->max;
         }
      }
      break;
   }
}
Variable Documentation
bit b0
Definition at line 320 of file scs_1000.c.
Referenced by application_display(), lcd_menu(), and sr_read().
bit b1
Definition at line 320 of file scs_1000.c.
Referenced by application_display(), decode_bits(), lcd_menu(), SimpleHistograms::ProcessEntry(), MyModule::ProcessEntry(), and sr_read().
bit b2
Definition at line 320 of file scs_1000.c.
Referenced by application_display(), decode_bits(), lcd_menu(), SimpleHistograms::ProcessEntry(), and sr_read().
bit b3
Definition at line 320 of file scs_1000.c.
Referenced by application_display(), lcd_menu(), and sr_read().
bit enter_mode = 0
Definition at line 43 of file lcd_menu.c.
Referenced by lcd_menu().
idata float f_var
Definition at line 46 of file lcd_menu.c.
Referenced by lcd_menu(), and var_inc().
bit flash_param
Definition at line 254 of file mscbmain.c.
Referenced by interprete(), lcd_menu(), setup(), and yield().
bit in_menu = 0
Definition at line 41 of file lcd_menu.c.
Referenced by lcd_menu().
unsigned char n_sysvar = 4
Definition at line 100 of file lcd_menu.c.
Referenced by lcd_menu().
unsigned char idata n_variables
Definition at line 231 of file mscbmain.c.
Referenced by interprete(), lcd_menu(), and setup().
NAME_TABLE code prefix_table[]
Initial value:
 {
   {PRFX_PICO, "p",},
   {PRFX_NANO, "n",},
   {PRFX_MICRO, "\344",},
   {PRFX_MILLI, "m",},
   {PRFX_NONE, "",},
   {PRFX_KILO, "k",},
   {PRFX_MEGA, "M",},
   {PRFX_GIGA, "G",},
   {PRFX_TERA, "T",},
   {0}
}
Definition at line 55 of file lcd_menu.c.
Referenced by display_value().
bit reboot
Definition at line 256 of file mscbmain.c.
Referenced by interprete(), lcd_menu(), setup(), and yield().
bit startup = 1
Definition at line 40 of file lcd_menu.c.
Referenced by lcd_menu().
SYS_INFO sys_info
Definition at line 239 of file mscbmain.c.
bit system_menu = 0
Definition at line 42 of file lcd_menu.c.
Referenced by lcd_menu().
MSCB_INFO_VAR code sysvar[]
Initial value:
 {
   { 2, UNIT_WORD, 0, 0, 0, "Node Adr", &sys_info.node_addr, 1, 0xFFFE, 1 },
   { 2, UNIT_WORD, 0, 0, 0, "Grp Adr",  &sys_info.group_addr, 1, 0xFFFE, 1 },
   { 0, UNIT_BOOLEAN, 0, 0, MSCBF_DATALESS, "Flash" },
   { 0, UNIT_BOOLEAN, 0, 0, MSCBF_DATALESS, "Reboot" },
}
Definition at line 102 of file lcd_menu.c.
Referenced by lcd_menu().
NAME_TABLE code unit_table[]
Initial value:
 {
   {UNIT_METER, "m",},
   {UNIT_GRAM, "g",},
   {UNIT_SECOND, "s",},
   {UNIT_MINUTE, "m",},
   {UNIT_HOUR, "h",},
   {UNIT_AMPERE, "A",},
   {UNIT_KELVIN, "K",},
   {UNIT_CELSIUS, "\337C",},
   {UNIT_FARENHEIT, "\337F",},
   {UNIT_HERTZ, "Hz",},
   {UNIT_PASCAL, "Pa",},
   {UNIT_BAR, "ba",},
   {UNIT_WATT, "W",},
   {UNIT_VOLT, "V",},
   {UNIT_OHM, "\364",},
   {UNIT_TESLA, "T",},
   {UNIT_LITERPERSEC, "l/s",},
   {UNIT_RPM, "RPM",},
   {UNIT_FARAD, "F",},
   {UNIT_PERCENT, "%%",},
   {UNIT_PPM, "RPM",},
   {UNIT_COUNT, "cnt",},
   {UNIT_FACTOR, "x",},
   {0}
}
Definition at line 68 of file lcd_menu.c.
Referenced by display_value().
unsigned char var_index = 0
Definition at line 44 of file lcd_menu.c.
Referenced by generate_hist_graph(), lcd_menu(), and query_params().
MSCB_INFO_VAR code variables[]
Definition at line 149 of file hvr_200.c.