AlcapDAQ: midas/drivers/divers/lrs1190.c File Reference
midas/drivers/divers/lrs1190.c File Reference
#include <stdio.h>
Defines
#define INLINE
#define EXTERNAL extern
#define A32D24_1190 0xf0000000
#define LRS1190_ENABLE(_vmebase)
#define LRS1190_DISABLE(_vmebase)
#define LRS1190_RESET(_vmebase)
#define LRS1190_COUNT(_vmebase, _d)
#define LRS1190_READI4(_vmebase, _d, _r)
#define LRS1190_READL2(_vmebase, _d, _r)
#define LRS1190_READH2(_vmebase, _d, _r)
#define LRS_1190_READL2_TONY(_vmebase, _d, _r)
Typedefs
typedef short int INT
typedef unsigned short int WORD
typedef unsigned long int DWORD
Functions
INLINE void lrs1190_enable (DWORD vmeBase)
INLINE void lrs1190_disable (DWORD vmeBase)
INLINE void lrs1190_reset (DWORD vmeBase)
INLINE void lrs1190_count (DWORD vmeBase, INT *count)
INLINE void lrs1190_readi4 (DWORD vmeBase, DWORD **d, INT r)
INLINE void lrs1190_readl2 (DWORD vmeBase, WORD **d, INT r)
INLINE void lrs1190_readh2 (DWORD vmeBase, WORD **d, INT r)
INLINE void lrs1190_readl2z (DWORD vmeBase, WORD **d, INT r)
void lrs1190 (void)
void ena1190 (DWORD vmeBase)
void dis1190 (DWORD vmeBase)
void res1190 (DWORD vmeBase)
void cn1190 (DWORD vmeBase)
void rd1190l (DWORD vmeBase, DWORD r)
void rd1190h (DWORD vmeBase, DWORD r)
void rd1190 (DWORD vmeBase, DWORD r)
Define Documentation
#define A32D24_1190 0xf0000000
Definition at line 70 of file lrs1190.c.
Referenced by lrs1190_count(), lrs1190_disable(), lrs1190_enable(), lrs1190_readh2(), lrs1190_readi4(), lrs1190_readl2(), lrs1190_readl2z(), and lrs1190_reset().
#define EXTERNAL extern
Definition at line 51 of file lrs1190.c.
#define INLINE
Definition at line 48 of file lrs1190.c.
#define LRS1190_COUNT (_vmebase, _d)
Value:
{\
                                        {\
                                         volatile DWORD _ll, *_pcount;\
                                         _ll = _vmebase;\
                                         _pcount = (DWORD *) (((_ll) | 0x8000) | A32D24_1190);\
                                         *((WORD *) _d) = *(WORD *) _pcount;\
                                       }\
                                    }
Definition at line 105 of file lrs1190.c.
Referenced by cn1190().
#define LRS1190_DISABLE (_vmebase)
Value:
{\
                                    {\
                                       volatile DWORD _ll, _local;\
                                      _ll = _vmebase;\
                                       _local = ((_ll) | 0x8002) | A32D24_1190;\
                                       *(WORD *)_local = 0x0;\
                                   }\
                                }
Definition at line 85 of file lrs1190.c.
#define LRS1190_ENABLE (_vmebase)
Value:
{\
                                    {\
                                       volatile DWORD _ll, _local;\
                                       _ll = _vmebase;\
                                       _local = ((_ll) | 0x8002) | A32D24_1190;\
                                       *(WORD *)_local = 0x1;\
                                   }\
                                }
Definition at line 75 of file lrs1190.c.
#define LRS1190_READH2 (_vmebase, _d, _r)
Value:
{\
                                        {\
                                         volatile DWORD _ll, *_pcount, *_local, _count, __r;\
                                         __r = _r;\
                                         _ll = _vmebase;\
                                         _pcount = (DWORD *) (((_ll) | 0x8000) | A32D24_1190);\
                                         _count = *(WORD *) _pcount;\
                                         if (_count <= __r)\
                                           __r = _count;\
                                         _local = (DWORD *)((_ll)  | A32D24_1190);\
                                         while (__r > 0) {\
                                                *(WORD *) _d = *(++((WORD *)_local));\
                                                ((WORD *)_d)++;\
                                                ((WORD *)_local)++;\
                                                __r--;}\
                                         }\
                                      }
Definition at line 153 of file lrs1190.c.
#define LRS1190_READI4 (_vmebase, _d, _r)
Value:
{\
                                        {\
                                         volatile DWORD _ll, *_local, __r, _count;\
                                         DWORD *_pcount;\
                                         __r = _r;\
                                         _ll = _vmebase;\
                                         _pcount = (DWORD *) (((_ll) | 0x8000) | A32D24_1190);\
                                         _count = *(WORD *) _pcount;\
                                         if (_count <= __r)\
                                           __r = _count;\
                                         _local = (DWORD *)((_ll)  | A32D24_1190);\
                                         while (__r > 0) {\
                                                *_d++ = *_local++;\
                                                __r--;}\
                                         }\
                                      }
Definition at line 116 of file lrs1190.c.
#define LRS1190_READL2 (_vmebase, _d, _r)
Value:
{\
                                        {\
                                         volatile DWORD _ll, *_pcount, *_local, __r, _count;\
                                         __r = _r;\
                                         _ll = _vmebase;\
                                         _pcount = (DWORD *) (((_ll) | 0x8000) | A32D24_1190);\
                                         _count = *(WORD *) _pcount;\
                                         if (_count <= __r)\
                                           __r = _count;\
                                         _local = (DWORD *)((_ll)  | A32D24_1190);\
                                         while (__r > 0) {\
                                                *(WORD *) _d = *(WORD *)_local;\
                                                ((WORD *)_d)++;\
                                                (_local)++;\
                                                __r--;}\
                                         }\
                                      }
Definition at line 134 of file lrs1190.c.
#define LRS1190_RESET (_vmebase)
Value:
{\
                                   {\
                                      volatile DWORD _ll, _dummy, _local;\
                                      _ll = _vmebase;\
                                      _local = (_ll) | A32D24_1190;\
                                      _dummy = *(WORD *) _local;\
                                  }\
                               }
Definition at line 95 of file lrs1190.c.
#define LRS_1190_READL2_TONY (_vmebase, _d, _r)
Value:
{\
                                        {\
                                         volatile DWORD _ll, *_pcount, *_local, __r, _count;\
                                         __r = _r;\
                                         _ll = _vmebase;\
                                         _pcount = (DWORD *) (((_ll) | 0x8000) | A32D24_1190);\
                                         _count = *(WORD *) _pcount;\
                                         if (_count <= __r)\
                                           __r = _count;\
                                         _local = (DWORD *)((_ll)  | A32D24_1190);\
                                         *(WORD *) _d = __r;\
                                         ((WORD *)_d)++;\
                                         while (__r > 0) {\
                                                *(WORD *) _d = *(WORD *)_local;\
                                                ((WORD *)_d)++;\
                                                (_local)++;\
                                                __r--;}\
                                         }\
                                      }
Definition at line 172 of file lrs1190.c.
Typedef Documentation
typedef unsigned long int DWORD
Definition at line 62 of file lrs1190.c.
typedef short int INT
Definition at line 56 of file lrs1190.c.
typedef unsigned short int WORD
Definition at line 57 of file lrs1190.c.
Function Documentation
void cn1190 (DWORD vmeBase)
Definition at line 343 of file lrs1190.c.
References count, LRS1190_COUNT, and lrs1190_count().
{
   INT count;
   lrs1190_count(vmeBase, &count);
   printf("Inline counter %i\n", count);
   LRS1190_COUNT(vmeBase, &count);
   printf("Macro  counter %i\n", count);
}
void dis1190 (DWORD vmeBase)
Definition at line 333 of file lrs1190.c.
References lrs1190_disable().
{
   lrs1190_disable(vmeBase);
}
void ena1190 (DWORD vmeBase)
Definition at line 328 of file lrs1190.c.
References lrs1190_enable().
{
   lrs1190_enable(vmeBase);
}
void lrs1190 (void)
Definition at line 300 of file lrs1190.c.
{
   printf("\n---> LRS 1190 Dual port memory buffer (lrs1190.c) <---\n");
   printf("Macro  : LRS1190_ENABLE (DWORD vmeBase);\n");
   printf("Macro  : LRS1190_DISABLE (DWORD vmeBase);\n");
   printf("Macro  : LRS1190_CLEAR (DWORD vmeBase);\n");
   printf("Macro  : LRS1190_COUNT (DWORD vmeBase, int * count);\n");
   printf("Macro  : LRS1190_READI4 (DWORD vmeBase, DWORD *d , int repeat);\n");
   printf("Macro  : LRS1190_READL2 (DWORD vmeBase, WORD *d , int repeat);\n");
   printf("Macro  : LRS1190_READH2 (DWORD vmeBase, WORD *d , int repeat);\n");
   printf("Macro  : LRS1190_READL2_TONY (DWORD vmeBase, DWORD *d , int repeat);\n");
   printf("Inline : lrs1190_enable (DWORD vmeBase);\n");
   printf("Inline : lrs1190_disable (DWORD vmeBase);\n");
   printf("Inline : lrs1190_clear (DWORD vmeBase);\n");
   printf("Inline : lrs1190_count (DWORD vmeBase, int * count);\n");
   printf("Inline : lrs1190_readi4 (DWORD vmeBase, DWORD *d , int repeat);\n");
   printf("Inline : lrs1190_readl2 (DWORD vmeBase, DWORD *d , int repeat);\n");
   printf("Inline : lrs1190_readh2 (DWORD vmeBase, DWORD *d , int repeat);\n");
   printf("Inline : lrs1190_readl2_tony (DWORD vmeBase, DWORD *d , int repeat);\n");
   printf("Test : ena1190  (0x7f0000)         <--- enable  VME buffer\n");
   printf("Test : dis1190  (0x7f0000)         <--- disable VME buffer\n");
   printf("Test : res1190  (0x7f0000)         <--- reset   VME buffer\n");
   printf("Test : cn1190   (0x7f0000)         <--- read    WORD count register\n");
   printf("Test : rd1190   (0x7f0000)         <--- read             VME buffer\n");
   printf("Test : rd1190l  (0x7f0000)         <--- read low  WORD   VME buffer\n");
   printf("Test : rd1190h  (0x7f0000)         <--- read high WORD   VME buffer\n");
}
INLINE void lrs1190_count (DWORD vmeBase, INT * count)
Definition at line 221 of file lrs1190.c.
References A32D24_1190.
Referenced by cn1190(), rd1190(), rd1190h(), and rd1190l().
{
   volatile DWORD local;
   local = (vmeBase | 0x8000 | A32D24_1190);
   *count = *(WORD *) local;
}
INLINE void lrs1190_disable (DWORD vmeBase)
Definition at line 203 of file lrs1190.c.
References A32D24_1190.
Referenced by dis1190(), rd1190(), rd1190h(), and rd1190l().
{
   volatile DWORD local;
   local = ((vmeBase) | 0x8002) | A32D24_1190;
   *(WORD *) local = 0x0;
}
INLINE void lrs1190_enable (DWORD vmeBase)
Definition at line 194 of file lrs1190.c.
References A32D24_1190.
Referenced by ena1190(), rd1190(), rd1190h(), and rd1190l().
{
   volatile DWORD local;
   local = ((vmeBase) | 0x8002) | A32D24_1190;
   *(WORD *) local = 0x1;
}
INLINE void lrs1190_readh2 (DWORD vmeBase, WORD ** d, INT r)
Definition at line 264 of file lrs1190.c.
References A32D24_1190, and count.
Referenced by rd1190h().
{
   volatile DWORD local, count;
   local = (vmeBase | 0x8000 | A32D24_1190);
   count = *(WORD *) local;
   if ((int) count <= r)
      r = count;
   local = vmeBase | A32D24_1190;
   while (r > 0) {
      *((*d)++) = *(++((WORD *) local));
      ((WORD *) local)++;
      r--;
   }
}
INLINE void lrs1190_readi4 (DWORD vmeBase, DWORD ** d, INT r)
Definition at line 230 of file lrs1190.c.
References A32D24_1190, and count.
Referenced by rd1190().
{
   volatile DWORD local, count;
   local = (vmeBase | 0x8000 | A32D24_1190);
   count = *(WORD *) local;
   if ((int) count <= r)
      r = count;
   local = vmeBase | A32D24_1190;
   while (r > 0) {
      *((*d)++) = *((DWORD *) local);
      ((DWORD *) local)++;
      r--;
   }
}
INLINE void lrs1190_readl2 (DWORD vmeBase, WORD ** d, INT r)
Definition at line 247 of file lrs1190.c.
References A32D24_1190, and count.
Referenced by rd1190l().
{
   volatile DWORD local, count;
   local = (vmeBase | 0x8000 | A32D24_1190);
   count = *(WORD *) local;
   if ((int) count <= r)
      r = count;
   local = vmeBase | A32D24_1190;
   while (r > 0) {
      *((*d)++) = *((WORD *) local);
      ((DWORD *) local)++;
      r--;
   }
}
INLINE void lrs1190_readl2z (DWORD vmeBase, WORD ** d, INT r)
Definition at line 281 of file lrs1190.c.
References A32D24_1190, and count.
{
   volatile DWORD *local, count;
   local = (DWORD *) (vmeBase | 0x8000 | A32D24_1190);
   count = *(WORD *) local;
   if ((int) count <= r)
      r = count;
   local = (DWORD *) (vmeBase | A32D24_1190);
   *((*d)++) = r;
   while (r > 0) {
      *((*d)++) = *((WORD *) local);
      (local)++;
      r--;
   }
}
INLINE void lrs1190_reset (DWORD vmeBase)
Definition at line 212 of file lrs1190.c.
References A32D24_1190.
Referenced by res1190().
{
   volatile DWORD local, dummy;
   local = vmeBase | A32D24_1190;
   dummy = *(WORD *) local;
}
void rd1190 (DWORD vmeBase, DWORD r)
Definition at line 386 of file lrs1190.c.
References i, lrs1190_count(), lrs1190_disable(), lrs1190_enable(), and lrs1190_readi4().
{
   DWORD dd[1024], *pdd;
   INT i, buf_counter;
   for (i = 0; i < 1024; i++)
      dd[i] = 0;
   pdd = &dd[0];
   lrs1190_disable(vmeBase);
   lrs1190_count(vmeBase, &buf_counter);
   printf("counter %i\n", buf_counter);
   lrs1190_readi4(vmeBase, &pdd, r);
   lrs1190_enable(vmeBase);
   for (i = 0; i < buf_counter; i++)
      printf("%i-> %8.8x\n", i, dd[i]);
}
void rd1190h (DWORD vmeBase, DWORD r)
Definition at line 369 of file lrs1190.c.
References i, lrs1190_count(), lrs1190_disable(), lrs1190_enable(), and lrs1190_readh2().
{
   DWORD dd[1024], *pdd;
   INT i, buf_counter;
   for (i = 0; i < 1024; i++)
      dd[i] = 0;
   pdd = &dd[0];
   lrs1190_disable(vmeBase);
   lrs1190_count(vmeBase, &buf_counter);
   printf("counter %i\n", buf_counter);
   lrs1190_readh2(vmeBase, (WORD **) & pdd, r);
   lrs1190_enable(vmeBase);
   for (i = 0; i < buf_counter; i++)
      printf("%i-> %8.8x\n", i, dd[i]);
}
void rd1190l (DWORD vmeBase, DWORD r)
Definition at line 352 of file lrs1190.c.
References i, lrs1190_count(), lrs1190_disable(), lrs1190_enable(), and lrs1190_readl2().
{
   DWORD dd[1024], *pdd;
   INT i, buf_counter;
   for (i = 0; i < 1024; i++)
      dd[i] = 0;
   pdd = &dd[0];
   lrs1190_disable(vmeBase);
   lrs1190_count(vmeBase, &buf_counter);
   printf("counter %i\n", buf_counter);
   lrs1190_readl2(vmeBase, (WORD **) & pdd, r);
   lrs1190_enable(vmeBase);
   for (i = 0; i < buf_counter; i++)
      printf("%i-> %8.8x\n", i, dd[i]);
}
void res1190 (DWORD vmeBase)
Definition at line 338 of file lrs1190.c.
References lrs1190_reset().
{
   lrs1190_reset(vmeBase);
}