AlcapDAQ: midas/src/mana.cpp File Reference
midas/src/mana.cpp File Reference
#include <assert.h>
#include "midas.h"
#include "msystem.h"
#include "hardware.h"
#include "zlib.h"
#include "ybos.h"
#include <stdio.h>
Data Structures
struct EVENT_DEF
struct MA_FILE
Defines
#define PVM_BUFFER_SIZE (1024*1024)
#define HBOOK_LREC 8190
#define EXT_EVENT_SIZE (5*(MAX_EVENT_SIZE+sizeof(EVENT_HEADER)))
#define ANALYZER_REQUEST_STR "\Event ID = INT : 0\n\Trigger mask = INT : -1\n\Sampling type = INT : 1\n\Buffer = STRING : [32] SYSTEM\n\Enabled = BOOL : 1\n\Client name = STRING : [32] \n\Host = STRING : [32] \n\"
#define ANALYZER_STATS_STR "\Events received = DOUBLE : 0\n\Events per sec. = DOUBLE : 0\n\Events written = DOUBLE : 0\n\"
#define OUT_INFO_STR "\Filename = STRING : [256] run%05d.asc\n\RWNT = BOOL : 0\n\Histo Dump = BOOL : 0\n\Histo Dump Filename = STRING : [256] his%05d.rz\n\Clear histos = BOOL : 1\n\Last Histo Filename = STRING : [256] last.rz\n\Events to ODB = BOOL : 1\n\Global Memory Name = STRING : [8] ONLN\n\"
#define EVENT_DEF_CACHE_SIZE 30
#define STR_INC(p, base)
#define MA_DEVICE_DISK 1
#define MA_DEVICE_TAPE 2
#define MA_DEVICE_FTP 3
#define MA_DEVICE_PVM 4
#define MA_FORMAT_MIDAS (1<<0)
#define MA_FORMAT_YBOS (1<<2)
#define MA_FORMAT_GZIP (1<<3)
Functions
INT analyzer_init (void)
INT analyzer_exit (void)
INT analyzer_loop (void)
INT ana_begin_of_run (INT run_number, char *error)
INT ana_end_of_run (INT run_number, char *error)
INT ana_pause_run (INT run_number, char *error)
INT ana_resume_run (INT run_number, char *error)
void update_stats ()
void odb_load (EVENT_HEADER *pevent)
INT getparam (int argc, char **argv)
void add_data_dir (char *result, char *file)
EVENT_DEF * db_get_event_definition (short int event_id)
void test_register (ANA_TEST *t)
void test_clear ()
void test_increment ()
void test_write ()
INT load_parameters (INT run_number)
INT book_ntuples (void)
INT book_ttree (void)
void banks_changed (INT hDB, INT hKey, void *info)
INT mana_init ()
INT mana_exit ()
INT bor (INT run_number, char *error)
INT eor (INT run_number, char *error)
INT tr_prestart (INT rn, char *error)
INT tr_stop (INT rn, char *error)
INT tr_pause (INT rn, char *error)
INT tr_resume (INT rn, char *error)
INT write_event_ascii (FILE *file, EVENT_HEADER *pevent, ANALYZE_REQUEST *par)
INT write_event_midas (FILE *file, EVENT_HEADER *pevent, ANALYZE_REQUEST *par)
INT write_event_odb (EVENT_HEADER *pevent)
void correct_num_events (INT i)
INT process_event (ANALYZE_REQUEST *par, EVENT_HEADER *pevent)
void receive_event (HNDLE buffer_handle, HNDLE request_id, EVENT_HEADER *pheader, void *pevent)
void update_request (HNDLE hDB, HNDLE hKey, void *info)
void register_requests (void)
void lock_histo (INT id)
void load_last_histos ()
void save_last_histos ()
INT loop_online ()
INT init_module_parameters (BOOL bclose)
INT bevid_2_mheader (EVENT_HEADER *pevent, DWORD *pybos)
MA_FILE * ma_open (char *file_name)
int ma_close (MA_FILE *file)
int ma_read_event (MA_FILE *file, EVENT_HEADER *pevent, int size)
INT analyze_run (INT run_number, char *input_file_name, char *output_file_name)
INT loop_runs_offline ()
int main (int argc, char *argv[])
Variables
BOOL pvm_master = FALSE
BOOL pvm_slave = FALSE
char * bstr = " "
char * analyzer_name
INT analyzer_loop_period
INT odb_size
HNDLE hDB
DWORD current_run_number
ANALYZE_REQUEST analyze_request []
BOOL ntuple_flag
INT lock_list [10000]
BOOL now_stopping = FALSE
int QUEST [100]
INT pawc_size
struct {
INT online
char host_name [HOST_NAME_LENGTH]
char exp_name [NAME_LENGTH]
char input_file_name [10][256]
char output_file_name [256]
char secondary_output_file_name [256]
char mias_tree_output_file_name [256]
INT run_number [2]
DWORD n [4]
BOOL filter
BOOL graphics
char config_file_name [10][256]
char param [10][256]
char protect [10][256]
BOOL rwnt
INT lrec
BOOL debug
BOOL verbose
BOOL quiet
BOOL no_load
BOOL daemon
INT n_task
INT pvm_buf_size
INT root_port
} clp
struct {
char flag_char
char description [1000]
void * data
INT type
INT n
INT index
} clp_descrip []
struct {
char filename [256]
BOOL rwnt
BOOL histo_dump
char histo_dump_filename [256]
BOOL clear_histos
char last_histo_filename [256]
BOOL events_to_odb
char global_memory_name [8]
} out_info
FILE * out_file
BOOL out_gzip
INT out_format
BOOL out_append
ANA_TEST ** tl
int n_test = 0
char hbook_types [][8]
struct {
short int event_id
DWORD last_time
} last_time_event [50]
ANALYZE_REQUEST * _current_par
Define Documentation
#define ANALYZER_REQUEST_STR "\Event ID = INT : 0\n\Trigger mask = INT : -1\n\Sampling type = INT : 1\n\Buffer = STRING : [32] SYSTEM\n\Enabled = BOOL : 1\n\Client name = STRING : [32] \n\Host = STRING : [32] \n\"
Definition at line 771 of file mana.cpp.
#define ANALYZER_STATS_STR "\Events received = DOUBLE : 0\n\Events per sec. = DOUBLE : 0\n\Events written = DOUBLE : 0\n\"
Definition at line 781 of file mana.cpp.
#define EVENT_DEF_CACHE_SIZE 30
#define EXT_EVENT_SIZE (5*(MAX_EVENT_SIZE+sizeof(EVENT_HEADER)))
Definition at line 640 of file mana.cpp.
Referenced by analyze_run(), process_event(), receive_event(), and write_event_midas().
#define HBOOK_LREC 8190
Definition at line 636 of file mana.cpp.
Referenced by bor(), and main().
#define MA_DEVICE_DISK 1
Definition at line 4318 of file mana.cpp.
Referenced by ma_open(), and ma_read_event().
#define MA_DEVICE_FTP 3
Definition at line 4320 of file mana.cpp.
#define MA_DEVICE_PVM 4
Definition at line 4321 of file mana.cpp.
Referenced by ma_open(), and ma_read_event().
#define MA_DEVICE_TAPE 2
Definition at line 4319 of file mana.cpp.
#define MA_FORMAT_GZIP (1<<3)
Definition at line 4325 of file mana.cpp.
#define MA_FORMAT_MIDAS (1<<0)
Definition at line 4323 of file mana.cpp.
Referenced by ma_open(), and ma_read_event().
#define MA_FORMAT_YBOS (1<<2)
Definition at line 4324 of file mana.cpp.
Referenced by ma_close(), ma_open(), and ma_read_event().
#define OUT_INFO_STR "\Filename = STRING : [256] run%05d.asc\n\RWNT = BOOL : 0\n\Histo Dump = BOOL : 0\n\Histo Dump Filename = STRING : [256] his%05d.rz\n\Clear histos = BOOL : 1\n\Last Histo Filename = STRING : [256] last.rz\n\Events to ODB = BOOL : 1\n\Global Memory Name = STRING : [8] ONLN\n\"
Definition at line 787 of file mana.cpp.
#define PVM_BUFFER_SIZE (1024*1024)
Definition at line 554 of file mana.cpp.
Referenced by ma_open(), and main().
#define STR_INC (p, base)
Value:
{ p+=strlen(p); \
                          if (p > base+sizeof(base)) \
                            cm_msg(MERROR, "STR_INC", "ASCII buffer too small"); }
Definition at line 2521 of file mana.cpp.
Function Documentation
INT ana_begin_of_run (INT run_number, char * error)
Definition at line 206 of file analyzer.cpp.
{
        printf("Analyzer saw beginning of run %d\n", run_number);
        return CM_SUCCESS;
}
INT ana_end_of_run (INT run_number, char * error)
Definition at line 214 of file analyzer.cpp.
{
        printf("Analyzer saw end of run %d\n", run_number);
        return CM_SUCCESS;
}
INT ana_pause_run (INT run_number, char * error)
Definition at line 222 of file analyzer.cpp.
{
        return CM_SUCCESS;
}
INT ana_resume_run (INT run_number, char * error)
Definition at line 229 of file analyzer.cpp.
{
        return CM_SUCCESS;
}
INT analyze_run (INT run_number, char * input_file_name, char * output_file_name)
Definition at line 4544 of file mana.cpp.
References ALIGN8, ANALYZE_REQUEST::ar_info, bor(), clp, cm_msg, cm_yield(), EVENT_HEADER::data_size, db_set_value(), AR_INFO::enabled, eor(), AR_INFO::event_id, EVENT_HEADER::event_id, ANALYZE_REQUEST::event_name, EVENTID_ALL, EVENTID_BOR, EXT_EVENT_SIZE, FALSE, FORMAT_MIDAS, ma_close(), ma_open(), ma_read_event(), MERROR, MINFO, out_info, process_event(), PTYPE, PvmDataInPlace, RPC_SHUTDOWN, SS_FILE_ERROR, ss_millitime(), start_time, SUCCESS, TID_BOOL, TID_INT, TID_STRING, TRIGGER_ALL, EVENT_HEADER::trigger_mask, AR_INFO::trigger_mask, TRUE, and update_stats().
Referenced by loop_runs_offline().
{
   EVENT_HEADER *pevent, *pevent_unaligned;
   ANALYZE_REQUEST *par;
   INT i, n, size;
   DWORD num_events_in, num_events_out;
   char error[256], str[256];
   INT status = SUCCESS;
   MA_FILE *file;
   BOOL skip;
   DWORD start_time;
   /* set output file name and flags in ODB */
   sprintf(str, "/%s/Output/Filename", analyzer_name);
   db_set_value(hDB, 0, str, output_file_name, 256, 1, TID_STRING);
#ifdef HAVE_HBOOK
   sprintf(str, "/%s/Output/RWNT", analyzer_name);
   db_set_value(hDB, 0, str, &clp.rwnt, sizeof(BOOL), 1, TID_BOOL);
#endif
   cm_msg(MINFO, "analyze_run", "Set run number %d in ODB", run_number);
   //assert(run_number > 0);
   /* set run number in ODB */
   status =
       db_set_value(hDB, 0, "/Runinfo/Run number", &run_number, sizeof(run_number), 1,
                    TID_INT);
   assert(status == SUCCESS);
   /* set file name in out_info */
   strcpy(out_info.filename, output_file_name);
   /* let changes propagate to modules */
   cm_yield(0);
   /* open input file, will be changed to ma_open_file later... */
   file = ma_open(input_file_name);
   if (file == NULL) {
      printf("Cannot open input file \"%s\"\n", input_file_name);
      return -1;
   }
   pevent_unaligned = (EVENT_HEADER *) malloc(EXT_EVENT_SIZE);
   if (pevent_unaligned == NULL) {
      printf("Not enough memeory\n");
      return -1;
   }
   pevent = (EVENT_HEADER *) ALIGN8((PTYPE) pevent_unaligned);
   /* call analyzer bor routines */
   bor(run_number, error);
   num_events_in = num_events_out = 0;
   start_time = ss_millitime();
   /* event loop */
   do {
      /* read next event */
      memset(pevent_unaligned, 0, EXT_EVENT_SIZE);
      n = ma_read_event(file, pevent, EXT_EVENT_SIZE);
      if (n <= 0)
         break;
      num_events_in++;
      /* copy system events (BOR, EOR, MESSAGE) to output file */
      if (pevent->event_id < 0) {
         status = process_event(NULL, pevent);
         if (status < 0 || status == RPC_SHUTDOWN)      /* disk full/stop analyzer */
            break;
         if (out_file && out_format == FORMAT_MIDAS) {
            size = pevent->data_size + sizeof(EVENT_HEADER);
            if (out_gzip)
               status = gzwrite(out_file, pevent, size) == size ? SUCCESS : SS_FILE_ERROR;
            else
               status =
                   fwrite(pevent, 1, size,
                          out_file) == (size_t) size ? SUCCESS : SS_FILE_ERROR;
            if (status != SUCCESS) {
               cm_msg(MERROR, "analyze_run", "Error writing to file (Disk full?)");
               return -1;
            }
            num_events_out++;
         }
         /* reinit start time after BOR event */
         if (pevent->event_id == EVENTID_BOR)
            start_time = ss_millitime();
      }
      /* check if event is in event limit */
      skip = FALSE;
      if (!pvm_slave) {
         if (clp.n[0] > 0 || clp.n[1] > 0) {
            if (clp.n[1] == 0) {
               /* treat n[0] as upper limit */
               if (num_events_in > clp.n[0]) {
                  num_events_in--;
                  status = SUCCESS;
                  break;
               }
            } else {
               if (num_events_in > clp.n[1]) {
                  status = SUCCESS;
                  break;
               }
               if (num_events_in < clp.n[0])
                  skip = TRUE;
               else if (clp.n[2] > 0 && num_events_in % clp.n[2] != 0)
                  skip = TRUE;
            }
         }
      }
      if (!skip) {
         /* find request belonging to this event */
         par = analyze_request;
         status = SUCCESS;
         for (i = 0; par->event_name[0]; par++)
            if ((par->ar_info.event_id == EVENTID_ALL ||
                 par->ar_info.event_id == pevent->event_id) &&
                (par->ar_info.trigger_mask == TRIGGER_ALL ||
                 (par->ar_info.trigger_mask & pevent->trigger_mask)) &&
                par->ar_info.enabled) {
               /* analyze this event */
               status = process_event(par, pevent);
               if (status == SUCCESS)
                  num_events_out++;
               if (status < 0 || status == RPC_SHUTDOWN)        /* disk full/stop analyzer */
                  break;
               /* check for Ctrl-C */
               status = cm_yield(0);
            }
         if (status < 0 || status == RPC_SHUTDOWN)
            break;
      }
      /* update ODB statistics once every 100 events */
      if (num_events_in % 100 == 0) {
         update_stats();
         if (!clp.quiet) {
            if (out_file)
               printf("%s:%d  %s:%d  events\r", input_file_name, (int) num_events_in,
                      out_info.filename, (int) num_events_out);
            else
               printf("%s:%d  events\r", input_file_name, (int) num_events_in);
#ifndef OS_WINNT
            fflush(stdout);
#endif
         }
      }
   } while (1);
#ifdef HAVE_PVM
   PVM_DEBUG("analyze_run: event loop finished, status = %d", status);
#endif
   /* signal EOR to slaves */
#ifdef HAVE_PVM
   if (pvm_master) {
      if (status == RPC_SHUTDOWN)
         printf("\nShutting down distributed analyzers, please wait...\n");
      pvm_eor(status == RPC_SHUTDOWN ? TAG_EXIT : TAG_EOR);
      /* merge slave output files */
      if (out_info.filename[0] && !out_append)
         status = pvm_merge();
      start_time = ss_millitime() - start_time;
      update_stats();
      if (!clp.quiet) {
         if (out_file)
            printf("%s:%d  %s:%d  events, %1.2lfs\n", input_file_name, num_events_in,
                   out_info.filename, num_events_out, start_time / 1000.0);
         else
            printf("%s:%d  events, %1.2lfs\n", input_file_name, num_events_in,
                   start_time / 1000.0);
      }
   } else if (pvm_slave) {
      start_time = ss_millitime() - start_time;
      update_stats();
      if (!clp.quiet) {
         if (out_file)
            printf("%s:%d  %s:%d  events, %1.2lfs\n", input_file_name, num_events_in,
                   out_info.filename, num_events_out, start_time / 1000.0);
         else
            printf("%s:%d  events, %1.2lfs\n", input_file_name, num_events_in,
                   start_time / 1000.0);
      }
      eor(current_run_number, error);
      /* send back tests */
      pvm_initsend(PvmDataInPlace);
      for (i = 0; i < n_test; i++)
         pvm_pkbyte((char *) tl[i], sizeof(ANA_TEST), 1);
      PVM_DEBUG("analyze_run: send %d tests back to master", n_test);
      status = pvm_send(pvm_myparent, TAG_EOR);
      if (status < 0) {
         pvm_perror("pvm_send");
         return RPC_SHUTDOWN;
      }
   } else {
      start_time = ss_millitime() - start_time;
      update_stats();
      if (!clp.quiet) {
         if (out_file)
            printf("%s:%d  %s:%d  events, %1.2lfs\n", input_file_name, num_events_in,
                   out_info.filename, num_events_out, start_time / 1000.0);
         else
            printf("%s:%d  events, %1.2lfs\n", input_file_name, num_events_in,
                   start_time / 1000.0);
      }
      /* call analyzer eor routines */
      eor(current_run_number, error);
   }
#else
   start_time = ss_millitime() - start_time;
   update_stats();
   if (!clp.quiet) {
      if (out_file)
         printf("%s:%d  %s:%d  events, %1.2lfs\n", input_file_name, (int) num_events_in,
                out_info.filename, (int) num_events_out, start_time / 1000.0);
      else
         printf("%s:%d  events, %1.2lfs\n", input_file_name, (int) num_events_in,
                start_time / 1000.0);
   }
   /* call analyzer eor routines */
   eor(current_run_number, error);
#endif
   ma_close(file);
   free(pevent_unaligned);
   return status;
}
INT analyzer_exit (void)
Definition at line 184 of file analyzer.cpp.
{
        if(gData) {
                delete gData;
                gData = NULL;
        }
        if(gSetup) {
                delete gSetup;
                gSetup = NULL;
        }
        if(gVacuum) {
                delete gVacuum;
                gVacuum = NULL;
        }
        return CM_SUCCESS;
}
INT analyzer_init (void)
Definition at line 150 of file analyzer.cpp.
{
        bool ret;
        // Initialize gData
        gData = new TGlobalData();
        // Initialize gSetup
        gSetup = new TSetupData();
        ret = UpdateDetectorBankNameMap(gSetup);
        if (!ret) {
                printf("THERE WAS AN ERROR!\n");
                return 0;
        }
        // Override ROOT's handling of signals
        signal(SIGHUP , catastrophe);
        signal(SIGINT , catastrophe);
        signal(SIGQUIT , catastrophe);
        signal(SIGILL , catastrophe);
        signal(SIGABRT , catastrophe);
        signal(SIGFPE , catastrophe);
        signal(SIGKILL , catastrophe);
        signal(SIGSEGV , catastrophe);
        signal(SIGPIPE , catastrophe);
        signal(SIGTERM , catastrophe);
        // Initialize gVacuum
        gVacuum = new TVacuumData();
        return SUCCESS;
}
INT analyzer_loop (void)
Definition at line 236 of file analyzer.cpp.
{
        return CM_SUCCESS;
}
void banks_changed (INT hDB, INT hKey, void * info)
Definition at line 1157 of file mana.cpp.
References book_ntuples(), book_ttree(), db_close_record(), and db_find_key().
{
   char str[80];
   HNDLE hkey;
   /* close previously opened hot link */
   sprintf(str, "/%s/Bank switches", analyzer_name);
   db_find_key(hDB, 0, str, &hkey);
   db_close_record(hDB, hkey);
#ifdef HAVE_HBOOK
   book_ntuples();
   printf("N-tuples rebooked\n");
#endif
#ifdef HAVE_ROOT
   book_ttree();
   printf("ROOT TTree rebooked\n");
#endif
}
INT bevid_2_mheader (EVENT_HEADER * pevent, DWORD * pybos)
Definition at line 4206 of file mana.cpp.
References clp, EVENT_HEADER::data_size, EVENT_HEADER::event_id, EVENT_HEADER::serial_number, SS_SUCCESS, EVENT_HEADER::time_stamp, EVENT_HEADER::trigger_mask, YB_SUCCESS, ybk_find(), YBOS_EVID_EVENT_ID, YBOS_EVID_EVENT_NB, YBOS_EVID_RUN_NUMBER, YBOS_EVID_SERIAL, YBOS_EVID_TIME, and YBOS_EVID_TRIGGER_MASK.
Referenced by ma_read_event().
{
   INT status;
   DWORD bklen, bktyp, *pdata;
   YBOS_BANK_HEADER *pybk;
   /* check if EVID is present if so display its content */
   if ((status = ybk_find(pybos, "EVID", &bklen, &bktyp, (void **) &pybk)) == YB_SUCCESS) {
      pdata = (DWORD *) ((YBOS_BANK_HEADER *) pybk + 1);
      if (clp.verbose) {
         printf("--------- EVID --------- Event# %i ------Run#:%i--------\n",
                (int) (YBOS_EVID_EVENT_NB(pdata)), (int) (YBOS_EVID_RUN_NUMBER(pdata)));
         printf("Evid:%4.4x- Mask:%4.4x- Serial:%i- Time:0x%x- Dsize:%i/0x%x",
                (int) YBOS_EVID_EVENT_ID(pdata), (int) YBOS_EVID_TRIGGER_MASK(pdata)
                , (int) YBOS_EVID_SERIAL(pdata), (int) YBOS_EVID_TIME(pdata)
                , (int) pybk->length, (int) pybk->length);
      }
      pevent->event_id = YBOS_EVID_EVENT_ID(pdata);
      pevent->trigger_mask = YBOS_EVID_TRIGGER_MASK(pdata);
      pevent->serial_number = YBOS_EVID_SERIAL(pdata);
      pevent->time_stamp = YBOS_EVID_TIME(pdata);
      pevent->data_size = pybk->length;
   }
   return SS_SUCCESS;
}
INT book_ntuples (void)
Definition at line 2926 of file fal.c.
{
   INT index, i, j, status, n_tag, size, id;
   HNDLE hkey;
   KEY key;
   char rw_tag[512][8];
   char str[80], key_name[NAME_LENGTH], block_name[NAME_LENGTH];
   BANK_LIST *bank_list;
   EVENT_DEF *event_def;
   /* copy output flag from ODB to bank_list */
   for (i = 0; analyze_request[i].event_name[0]; i++) {
      bank_list = analyze_request[i].bank_list;
      if (bank_list != NULL)
         for (; bank_list->name[0]; bank_list++) {
            sprintf(str, "/%s/Bank switches/%s", analyzer_name, bank_list->name);
            bank_list->output_flag = FALSE;
            size = sizeof(DWORD);
            db_get_value(hDB, 0, str, &bank_list->output_flag, &size, TID_DWORD, TRUE);
         }
   }
   /* hot link bank switches to N-tuple re-booking */
   sprintf(str, "/%s/Bank switches", analyzer_name);
   db_find_key(hDB, 0, str, &hkey);
   db_open_record(hDB, hkey, NULL, 0, MODE_READ, banks_changed, NULL);
   /* book RW N-tuples */
   /* go through all analyzer requests (events) */
   for (index = 0; analyze_request[index].event_name[0]; index++) {
      /* don't book N-tuples if buffer size is zero */
      if (analyze_request[index].rwnt_buffer_size == 0)
         continue;
      n_tag = 0;
      strcpy(rw_tag[n_tag++], "Run");
      strcpy(rw_tag[n_tag++], "Number");
      strcpy(rw_tag[n_tag++], "Time");
      bank_list = analyze_request[index].bank_list;
      if (bank_list == NULL) {
         /* book fixed event */
         event_def =
             db_get_event_definition((short int) analyze_request[index].ar_info.event_id);
         for (i = 0;; i++) {
            status = db_enum_key(hDB, event_def->hDefKey, i, &hkey);
            if (status == DB_NO_MORE_SUBKEYS)
               break;
            db_get_key(hDB, hkey, &key);
            /* convert blanks etc to '_' */
            strcpy(key_name, key.name);
            for (j = 0; key_name[j]; j++) {
               if (!(key_name[j] >= 'a' && key_name[j] <= 'z') &&
                   !(key_name[j] >= 'A' && key_name[j] <= 'Z') &&
                   !(key_name[j] >= '0' && key_name[j] <= '9'))
                  key_name[j] = '_';
            }
            if (key.num_values > 1)
               for (j = 0; j < key.num_values; j++) {
                  sprintf(str, "%s%d", key_name, j);
                  strncpy(rw_tag[n_tag++], str, 8);
                  if (n_tag >= 512) {
                     cm_msg(MERROR, "book_ntuples",
                            "Too much tags for RW N-tupeles (512 maximum)");
                     return 0;
                  }
            } else
               strncpy(rw_tag[n_tag++], key_name, 8);
            if (n_tag >= 512) {
               cm_msg(MERROR, "book_ntuples",
                      "Too much tags for RW N-tupeles (512 maximum)");
               return 0;
            }
         }
      } else {
         /* go through all banks in bank_list */
         for (; bank_list->name[0]; bank_list++) {
            /* remember tag offset in n_data variable */
            bank_list->n_data = n_tag;
            if (bank_list->output_flag == 0)
               continue;
            if (bank_list->type != TID_STRUCT) {
               for (i = 0; i < (INT) bank_list->size; i++) {
                  sprintf(str, "%s%d", bank_list->name, i);
                  strncpy(rw_tag[n_tag++], str, 8);
               }
            } else {
               /* define structured bank */
               for (i = 0;; i++) {
                  status = db_enum_key(hDB, bank_list->def_key, i, &hkey);
                  if (status == DB_NO_MORE_SUBKEYS)
                     break;
                  db_get_key(hDB, hkey, &key);
                  /* convert blanks etc to '_' */
                  strcpy(key_name, key.name);
                  for (j = 0; key_name[j]; j++) {
                     if (!(key_name[j] >= 'a' && key_name[j] <= 'z') &&
                         !(key_name[j] >= 'A' && key_name[j] <= 'Z') &&
                         !(key_name[j] >= '0' && key_name[j] <= '9'))
                        key_name[j] = '_';
                  }
                  if (key.num_values > 1)
                     for (j = 0; j < key.num_values; j++) {
                        sprintf(str, "%s%d", key_name, j);
                        strncpy(rw_tag[n_tag++], str, 8);
                        if (n_tag >= 512) {
                           cm_msg(MERROR, "book_ntuples",
                                  "Too much tags for RW N-tupeles (512 maximum)");
                           return 0;
                        }
                  } else
                     strncpy(rw_tag[n_tag++], key_name, 8);
                  if (n_tag >= 512) {
                     cm_msg(MERROR, "book_ntuples",
                            "Too much tags for RW N-tupeles (512 maximum)");
                     return 0;
                  }
               }
            }
         }
      }
      /* book N-tuple with evend ID */
      strcpy(block_name, analyze_request[index].event_name);
      block_name[8] = 0;
#ifndef MANA_LITE
      id = analyze_request[index].ar_info.event_id;
      if (HEXIST(id))
         HDELET(id);
      HBOOKN(id, block_name, n_tag, bstr,
             n_tag * analyze_request[index].rwnt_buffer_size, rw_tag);
      if (!HEXIST(id)) {
         printf("\n");
         cm_msg(MINFO, "book_ntuples",
                "Cannot book N-tuple #%d. Increase PAWC size via the -s flag or switch off banks",
                id);
      }
#endif
   }
   return SUCCESS;
}
INT book_ttree (void)
Referenced by banks_changed(), bor(), and mana_init().
INT bor (INT run_number, char * error)
Definition at line 2079 of file mana.cpp.
References ana_begin_of_run(), ANALYZE_REQUEST::ana_module, ANALYZE_REQUEST::bank_list, book_ntuples(), book_ttree(), ANA_MODULE::bor, clp, cm_msg, db_get_value(), enabled, ANA_MODULE::enabled, equal_ustring(), ANALYZE_REQUEST::event_name, FALSE, file_name, FORMAT_ASCII, FORMAT_HBOOK, FORMAT_MIDAS, FORMAT_ROOT, gManaHistsDir, gManaOutputFile, HBOOK_LREC, HBSET, HEXIST, HIDALL, HRESET, HROPEN, load_parameters(), lrec, MERROR, module, n, name, BANK_LIST::name, out_info, BANK_LIST::output_flag, SUCCESS, test_clear(), TID_BOOL, TID_DWORD, and TRUE.
Referenced by analyze_run(), begin_of_run(), bor(), tr_prestart(), tr_start(), and tr_start2().
{
   ANA_MODULE **module;
   INT i, j, size;
   char str[256], file_name[256], *ext_str;
   BANK_LIST *bank_list;
   /* load parameters */
   load_parameters(run_number);
   for (i = 0; analyze_request[i].event_name[0]; i++) {
      /* copy output flag from ODB to bank_list */
      bank_list = analyze_request[i].bank_list;
      if (bank_list != NULL)
         for (; bank_list->name[0]; bank_list++) {
            sprintf(str, "/%s/Bank switches/%s", analyzer_name, bank_list->name);
            bank_list->output_flag = FALSE;
            size = sizeof(DWORD);
            db_get_value(hDB, 0, str, &bank_list->output_flag, &size, TID_DWORD, TRUE);
         }
      /* copy module enabled flag to ana_module */
      module = analyze_request[i].ana_module;
      for (j = 0; module != NULL && module[j] != NULL; j++) {
         sprintf(str, "/%s/Module switches/%s", analyzer_name, module[j]->name);
         module[j]->enabled = TRUE;
         size = sizeof(BOOL);
         db_get_value(hDB, 0, str, &module[j]->enabled, &size, TID_BOOL, TRUE);
      }
   }
   /* clear histos, N-tuples and tests */
   if (clp.online && out_info.clear_histos) {
#ifdef HAVE_HBOOK
      int hid[10000];
      int n;
      for (i = 0; analyze_request[i].event_name[0]; i++)
         if (analyze_request[i].bank_list != NULL)
            if (HEXIST(analyze_request[i].ar_info.event_id))
               HRESET(analyze_request[i].ar_info.event_id, bstr);
      /* get list of all histos */
      HIDALL(hid, n);
      for (i = 0; i < n; i++) {
         for (j = 0; j < 10000; j++)
            if (lock_list[j] == 0 || lock_list[j] == hid[i])
               break;
         /* clear histo if not locked */
         if (lock_list[j] != hid[i])
            HRESET(hid[i], bstr);
      }
#endif                          /* HAVE_HBOOK */
#ifdef HAVE_ROOT
      /* clear histos */
      if (clp.online && out_info.clear_histos)
         ClearRootHistograms(gManaHistsDir);
#endif                          /* HAVE_ROOT */
      /* clear tests */
      test_clear();
   }
   /* open output file if not already open (append mode) and in offline mode */
   if (!clp.online && out_file == NULL && !pvm_master
       && !equal_ustring(clp.output_file_name, "OFLN")) {
      if (out_info.filename[0]) {
         strcpy(str, out_info.filename);
         if (strchr(str, '%') != NULL)
            sprintf(file_name, str, run_number);
         else
            strcpy(file_name, str);
         /* check output file extension */
         out_gzip = FALSE;
         if (strchr(file_name, '.')) {
            ext_str = file_name + strlen(file_name) - 1;
            while (*ext_str != '.')
               ext_str--;
            if (strncmp(ext_str, ".gz", 3) == 0) {
               out_gzip = TRUE;
               ext_str--;
               while (*ext_str != '.' && ext_str > file_name)
                  ext_str--;
            }
            if (strncmp(ext_str, ".asc", 4) == 0)
               out_format = FORMAT_ASCII;
            else if (strncmp(ext_str, ".mid", 4) == 0)
               out_format = FORMAT_MIDAS;
            else if (strncmp(ext_str, ".rz", 3) == 0)
               out_format = FORMAT_HBOOK;
            else if (strncmp(ext_str, ".root", 5) == 0)
               out_format = FORMAT_ROOT;
            else {
               strcpy(error,
                      "Unknown output data format. Please use file extension .asc, .mid, .rz or .root.\n");
               cm_msg(MERROR, "bor", error);
               return 0;
            }
         } else
            out_format = FORMAT_ASCII;
#ifdef HAVE_PVM
         /* use node name as filename if PVM slave */
         if (pvm_slave) {
            /* extract extension */
            if (strchr(file_name, '.')) {
               strcpy(str, strchr(file_name, '.') + 1);
               sprintf(file_name, "n%d", pvm_client_index);
               strcat(file_name, ".");
               strcat(file_name, str);
            } else {
               sprintf(file_name, "n%d", pvm_client_index);
            }
            PVM_DEBUG("BOR: file_name = %s", file_name);
         }
#endif
         /* open output file */
         if (out_format == FORMAT_HBOOK) {
#ifdef HAVE_HBOOK
            int status, lrec;
            char str2[80];
            lrec = clp.lrec;
#ifdef extname
            quest_[9] = 65000;
#else
            QUEST[9] = 65000;
#endif
            strcpy(str, "BSIZE");
            HBSET(str, HBOOK_LREC, status);
            strcpy(str, "OFFLINE");
            strcpy(str2, "NQP");
            HROPEN(1, str, file_name, str2, lrec, status);
            if (status != 0) {
               sprintf(error, "Cannot open output file %s", out_info.filename);
               cm_msg(MERROR, "bor", error);
               out_file = NULL;
               return 0;
            } else
               out_file = (FILE *) 1;
#else
            cm_msg(MERROR, "bor", "HBOOK support is not compiled in");
#endif                          /* HAVE_HBOOK */
         }
         else if (out_format == FORMAT_ROOT) {
#ifdef HAVE_ROOT
            // ensure the output file is closed
            assert(gManaOutputFile == NULL);
            gManaOutputFile =
                new TFile(file_name, "RECREATE", "Midas Analyzer output file");
            if (gManaOutputFile == NULL) {
               sprintf(error, "Cannot open output file %s", out_info.filename);
               cm_msg(MERROR, "bor", error);
               out_file = NULL;
               return 0;
            }
            // make all ROOT objects created by user module bor() functions
            // go into the output file
            gManaOutputFile->cd();
            out_file = (FILE *) 1;
#else
            cm_msg(MERROR, "bor", "ROOT support is not compiled in");
#endif                          /* HAVE_ROOT */
         }
         else {
            if (out_gzip)
               out_file = (FILE *) gzopen(file_name, "wb");
            else if (out_format == FORMAT_ASCII)
               out_file = fopen(file_name, "wt");
            else
               out_file = fopen(file_name, "wb");
            if (out_file == NULL) {
               sprintf(error, "Cannot open output file %s", file_name);
               cm_msg(MERROR, "bor", error);
               return 0;
            }
         }
      } else
         out_file = NULL;
#ifdef HAVE_HBOOK
      /* book N-tuples */
      if (out_format == FORMAT_HBOOK) {
         int status = book_ntuples();
         if (status != SUCCESS)
            return status;
      }
#endif                          /* HAVE_HBOOK */
#ifdef HAVE_ROOT
      /* book ROOT TTree */
      if (out_format == FORMAT_ROOT) {
         int status = book_ttree();
         if (status != SUCCESS)
            return status;
      }
#endif                          /* HAVE_ROOT */
   }
#ifdef HAVE_ROOT
   /* open secondary output file if applicable. */
   if (out_format != FORMAT_ROOT && clp.secondary_output_file_name[0] != '\0') {
    // ensure the output file is closed
    assert(gManaOutputFile == NULL);
    gManaOutputFile =
        new TFile(clp.secondary_output_file_name, "RECREATE",
                        "Midas Analyzer output file");
    if (gManaOutputFile == NULL) {
       sprintf(error, "Cannot open secondary output file %s",
                       clp.secondary_output_file_name);
       cm_msg(MERROR, "bor", error);
       return 0;
    }
    // make all ROOT objects created by user module bor() functions
    // go into the output file
    gManaOutputFile->cd();
   }
#endif                          /* HAVE_ROOT */
   /* if (out_file == NULL) */
   /* save run number */
   current_run_number = run_number;
   /* call bor for modules */
   for (i = 0; analyze_request[i].event_name[0]; i++) {
      module = analyze_request[i].ana_module;
      for (j = 0; module != NULL && module[j] != NULL; j++)
         if (module[j]->bor != NULL && module[j]->enabled)
            module[j]->bor(run_number);
   }
   /* call main analyzer BOR routine */
   return ana_begin_of_run(run_number, error);
}
void correct_num_events (INT i)
Definition at line 3590 of file mana.cpp.
References ANALYZE_REQUEST::events_received.
{
   if (_current_par)
      _current_par->events_received += i - 1;
}
EVENT_DEF* db_get_event_definition (short int event_id)
Definition at line 893 of file mana.cpp.
References cm_msg, db_enum_key(), db_find_key(), db_get_value(), DB_NO_MORE_SUBKEYS, DB_SUCCESS, EVENT_DEF::disabled, equal_ustring(), EVENT_DEF_CACHE_SIZE, EVENT_DEF::event_id, FALSE, EVENT_DEF::format, FORMAT_ASCII, FORMAT_DUMP, FORMAT_FIXED, FORMAT_MIDAS, FORMAT_YBOS, EVENT_DEF::hDefKey, hKey, i, index, MERROR, size, status, TID_INT, TID_STRING, TID_WORD, TRUE, EVENT_DEF::type, and type.
{
   INT i, index, status, size, type;
   char str[80];
   HNDLE hKey, hKeyRoot;
   WORD id;
#define EVENT_DEF_CACHE_SIZE 30
   static EVENT_DEF *event_def = NULL;
   /* allocate memory for cache */
   if (event_def == NULL)
      event_def = (EVENT_DEF *) calloc(EVENT_DEF_CACHE_SIZE, sizeof(EVENT_DEF));
   /* lookup if event definition in cache */
   for (i = 0; event_def[i].event_id; i++)
      if (event_def[i].event_id == event_id)
         return &event_def[i];
   /* search free cache entry */
   for (index = 0; index < EVENT_DEF_CACHE_SIZE; index++)
      if (event_def[index].event_id == 0)
         break;
   if (index == EVENT_DEF_CACHE_SIZE) {
      cm_msg(MERROR, "db_get_event_definition", "too many event definitions");
      return NULL;
   }
   /* check for system events */
   if (event_id < 0) {
      event_def[index].event_id = event_id;
      event_def[index].format = FORMAT_ASCII;
      event_def[index].hDefKey = 0;
      event_def[index].disabled = FALSE;
      return &event_def[index];
   }
   status = db_find_key(hDB, 0, "/equipment", &hKeyRoot);
   if (status != DB_SUCCESS) {
      cm_msg(MERROR, "db_get_event_definition", "cannot find /equipment entry in ODB");
      return NULL;
   }
   for (i = 0;; i++) {
      /* search for equipment with specific name */
      status = db_enum_key(hDB, hKeyRoot, i, &hKey);
      if (status == DB_NO_MORE_SUBKEYS) {
         sprintf(str, "Cannot find event id %d under /equipment", event_id);
         cm_msg(MERROR, "db_get_event_definition", str);
         return NULL;
      }
      size = sizeof(id);
      status = db_get_value(hDB, hKey, "Common/Event ID", &id, &size, TID_WORD, TRUE);
      if (status != DB_SUCCESS)
         continue;
      size = sizeof(type);
      status = db_get_value(hDB, hKey, "Common/Type", &type, &size, TID_INT, TRUE);
      if (status != DB_SUCCESS)
         continue;
      if (id == event_id) {
         /* set cache entry */
         event_def[index].event_id = id;
         event_def[index].type = type;
         size = sizeof(str);
         str[0] = 0;
         db_get_value(hDB, hKey, "Common/Format", str, &size, TID_STRING, TRUE);
         if (equal_ustring(str, "Fixed"))
            event_def[index].format = FORMAT_FIXED;
         else if (equal_ustring(str, "ASCII"))
            event_def[index].format = FORMAT_ASCII;
         else if (equal_ustring(str, "MIDAS"))
            event_def[index].format = FORMAT_MIDAS;
         else if (equal_ustring(str, "YBOS"))
            event_def[index].format = FORMAT_YBOS;
         else if (equal_ustring(str, "DUMP"))
            event_def[index].format = FORMAT_DUMP;
         else {
            cm_msg(MERROR, "db_get_event_definition", "unknown data format");
            event_def[index].event_id = 0;
            return NULL;
         }
         db_find_key(hDB, hKey, "Variables", &event_def[index].hDefKey);
         return &event_def[index];
      }
   }
}
INT eor (INT run_number, char * error)
Definition at line 2332 of file mana.cpp.
References add_data_dir(), BANK_LIST::addr, ANALYZE_REQUEST::addr, addr, ana_end_of_run(), ANALYZE_REQUEST::ana_module, ANALYZE_REQUEST::bank_list, clp, cm_msg, enabled, ANA_MODULE::eor, ANALYZE_REQUEST::event_name, file_name, FORMAT_HBOOK, FORMAT_ROOT, gManaHistsDir, HREND, HROUT, HRPUT, MERROR, module, BANK_LIST::name, and out_info.
Referenced by analyze_run(), end_of_run(), eor(), and tr_stop().
{
   ANA_MODULE **module;
   BANK_LIST *bank_list;
   INT i, j, status;
   char str[256], file_name[256];
   /* call EOR routines modules */
   for (i = 0; analyze_request[i].event_name[0]; i++) {
      module = analyze_request[i].ana_module;
      for (j = 0; module != NULL && module[j] != NULL; j++)
         if (module[j]->eor != NULL && module[j]->enabled)
            module[j]->eor(run_number);
   }
   /* call main analyzer BOR routine */
   status = ana_end_of_run(run_number, error);
   /* save histos if requested */
   if (out_info.histo_dump && clp.online) {
      strcpy(str, out_info.histo_dump_filename);
      if (strchr(str, '%') != NULL)
         sprintf(file_name, str, run_number);
      else
         strcpy(file_name, str);
      add_data_dir(str, file_name);
#ifdef HAVE_HBOOK
      for (i = 0; i < (int) strlen(str); i++)
         if (isupper(str[i]))
            break;
      if (i < (int) strlen(str)) {
         printf
             ("Error: Due to a limitation in HBOOK, directoy names may not contain uppercase\n");
         printf("       characters. Histogram saving to %s will not work.\n", str);
      } else {
         char str2[256];
         strcpy(str2, "NT");
         HRPUT(0, str, str2);
      }
#endif                          /* HAVE_HBOOK */
#ifdef HAVE_ROOT
      SaveRootHistograms(gManaHistsDir, str);
#endif                          /* HAVE_ROOT */
   }
   /* close output file */
   if (out_file && !out_append) {
      if (out_format == FORMAT_HBOOK) {
#ifdef HAVE_HBOOK
         HROUT(0, i, bstr);
         strcpy(str, "OFFLINE");
         HREND(str);
#else
         cm_msg(MERROR, "eor", "HBOOK support is not compiled in");
#endif                          /* HAVE_HBOOK */
      } else if (out_format == FORMAT_ROOT) {
#ifdef HAVE_ROOT
         CloseRootOutputFile();
#else
         cm_msg(MERROR, "eor", "ROOT support is not compiled in");
#endif                          /* HAVE_ROOT */
      } else {
         if (out_gzip)
            gzclose(out_file);
         else
            fclose(out_file);
      }
      out_file = NULL;
      /* free CWNT buffer */
      for (i = 0; analyze_request[i].event_name[0]; i++) {
         bank_list = analyze_request[i].bank_list;
         if (bank_list == NULL) {
            if (analyze_request[i].addr) {
               free(analyze_request[i].addr);
               analyze_request[i].addr = NULL;
            }
         } else {
            for (; bank_list->name[0]; bank_list++)
               if (bank_list->addr) {
                  free(bank_list->addr);
                  bank_list->addr = NULL;
               }
         }
      }
   }
#ifdef HAVE_ROOT
   /* close secondary output file */
   if(clp.secondary_output_file_name[0] != '\0') {
     CloseRootOutputFile();
   }
#endif
   return status;
}
INT getparam (int argc, char ** argv)
Definition at line 800 of file mana.cpp.
References clp_descrip, data, db_sscanf(), description, flag_char, i, index, j, n, size, SUCCESS, TID_BOOL, TID_STRING, TRUE, type, and usage().
Referenced by interprete(), main(), show_cnaf_page(), show_custom_page(), show_elog_delete(), show_elog_page(), show_elog_submit_query(), show_form_query(), show_hist_config_page(), show_hist_page(), show_programs_page(), show_query_page(), show_rawfile(), show_sc_page(), show_set_page(), submit_elog(), and submit_form().
{
   INT index, i, j, size;
   /* parse command line parameters */
   for (index = 1; index < argc;) {
      /* search flag in parameter description */
      if (argv[index][0] == '-') {
         for (j = 0; clp_descrip[j].flag_char; j++)
            if (argv[index][1] == clp_descrip[j].flag_char)
               break;
         if (!clp_descrip[j].flag_char)
            goto usage;
         if (clp_descrip[j].n > 0 && index >= argc - 1)
            goto usage;
         index++;
         if (clp_descrip[j].type == TID_BOOL) {
            *((BOOL *) clp_descrip[j].data) = TRUE;
            continue;
         }
         do {
            if (clp_descrip[j].type == TID_STRING)
               strcpy((char *) clp_descrip[j].data + clp_descrip[j].index * 256,
                      argv[index]);
            else
               db_sscanf(argv[index], clp_descrip[j].data,
                         &size, clp_descrip[j].index, clp_descrip[j].type);
            if (clp_descrip[j].n > 1)
               clp_descrip[j].index++;
            if (clp_descrip[j].index > clp_descrip[j].n) {
               printf("Note more than %d options possible for flag -%c\n",
                      clp_descrip[j].n, clp_descrip[j].flag_char);
               return 0;
            }
            index++;
         } while (index < argc && argv[index][0] != '-');
      } else
         goto usage;
   }
   return SUCCESS;
 usage:
   printf("usage: analyzer [options]\n\n");
   printf("valid options are:\n");
   for (i = 0; clp_descrip[i].flag_char; i++)
      printf("  -%c %s\n", clp_descrip[i].flag_char, clp_descrip[i].description);
   return 0;
}
INT init_module_parameters (BOOL bclose)
Definition at line 4155 of file mana.cpp.
References ANALYZE_REQUEST::ana_module, cm_msg, db_check_record(), db_close_record(), db_find_key(), db_get_record_size(), db_open_record(), DB_SUCCESS, ANALYZE_REQUEST::event_name, MERROR, MODE_READ, module, name, strcomb(), SUCCESS, and TRUE.
{
   INT i, j, status, size;
   ANA_MODULE **module;
   char str[80];
   HNDLE hkey;
   for (i = 0; analyze_request[i].event_name[0]; i++) {
      module = analyze_request[i].ana_module;
      for (j = 0; module != NULL && module[j] != NULL; j++) {
         if (module[j]->parameters != NULL) {
            sprintf(str, "/%s/Parameters/%s", analyzer_name, module[j]->name);
            if (bclose) {
               db_find_key(hDB, 0, str, &hkey);
               db_close_record(hDB, hkey);
            } else {
               status = db_find_key(hDB, 0, str, &hkey);
               if (status == DB_SUCCESS) {
                  db_get_record_size(hDB, hkey, 0, &size);
                  if (size != module[j]->param_size)
                     status = 0;
               }
               if (status != DB_SUCCESS && module[j]->init_str) {
                  if (db_check_record(hDB, 0, str, strcomb(module[j]->init_str), TRUE) !=
                      DB_SUCCESS) {
                     cm_msg(MERROR, "init_module_parameters",
                            "Cannot create/check \"%s\" parameters in ODB", str);
                     return 0;
                  }
               }
               db_find_key(hDB, 0, str, &hkey);
               assert(hkey);
               if (db_open_record(hDB, hkey, module[j]->parameters, module[j]->param_size,
                                  MODE_READ, NULL, NULL) != DB_SUCCESS) {
                  cm_msg(MERROR, "init_module_parameters",
                         "Cannot open \"%s\" parameters in ODB", str);
                  return 0;
               }
            }
         }
      }
   }
   return SUCCESS;
}
void load_last_histos ()
Definition at line 4009 of file mana.cpp.
References add_data_dir(), clp, DIR_SEPARATOR, gManaHistsDir, HDELET, HEXIST, HRGET, and out_info.
Referenced by main().
{
   char str[256];
   /* load previous online histos */
   if (!clp.no_load) {
      strcpy(str, out_info.last_histo_filename);
      if (strchr(str, DIR_SEPARATOR) == NULL)
         add_data_dir(str, out_info.last_histo_filename);
#ifdef HAVE_HBOOK
      {
         FILE *f;
         char str2[256];
         int i;
         for (i = 0; i < (int) strlen(str); i++)
            if (isupper(str[i]))
               break;
         if (i < (int) strlen(str)) {
            printf
                ("Error: Due to a limitation in HBOOK, directoy names may not contain uppercase\n");
            printf("       characters. Histogram loading from %s will not work.\n", str);
         } else {
            f = fopen(str, "r");
            if (f != NULL) {
               fclose(f);
               printf("Loading previous online histos from %s\n", str);
               strcpy(str2, "A");
               HRGET(0, str, str2);
               /* fix wrongly booked N-tuples at ID 100000 */
               if (HEXIST(100000))
                  HDELET(100000);
            }
         }
      }
#endif                          /* HAVE_HBOOK */
#ifdef HAVE_ROOT
      printf("Loading previous online histos from %s\n", str);
      LoadRootHistograms(gManaHistsDir, str);
#endif
   }
}
INT load_parameters (INT run_number)
Definition at line 1069 of file mana.cpp.
References clp, cm_yield(), data, db_find_key(), db_get_key(), db_load(), db_set_data_index(), db_sscanf(), DB_SUCCESS, FALSE, file_name, i, index, key, size, status, SUCCESS, and KEY::type.
Referenced by bor(), and odb_load().
{
   INT i, size, index, status;
   HNDLE hkey;
   char file_name[256], str[80], value_string[80], param_string[80];
   char data[32];
   KEY key;
   /* loop over configutation file names */
   for (i = 0; clp.config_file_name[i][0] && i < 10; i++) {
      if (strchr(clp.config_file_name[i], '%') != NULL)
         sprintf(file_name, clp.config_file_name[i], run_number);
      else
         strcpy(file_name, clp.config_file_name[i]);
      /* load file under "/" */
      if (db_load(hDB, 0, file_name, FALSE) == DB_SUCCESS)
         printf("Configuration file \"%s\" loaded\n", file_name);
   }
   /* loop over parameters */
   for (i = 0; clp.param[i][0] && i < 10; i++) {
      if (strchr(clp.param[i], '=') == NULL) {
         printf("Error: parameter %s contains no value\n", clp.param[i]);
      } else {
         strcpy(value_string, strchr(clp.param[i], '=') + 1);
         strcpy(param_string, clp.param[i]);
         *strchr(param_string, '=') = 0;
         index = 0;
         if (strchr(param_string, '[') != NULL) {
            index = atoi(strchr(param_string, '[') + 1);
            *strchr(param_string, '[') = 0;
         }
         if (param_string[0] == '/')
            strcpy(str, param_string);
         else
            sprintf(str, "/%s/Parameters/%s", analyzer_name, param_string);
         db_find_key(hDB, 0, str, &hkey);
         if (hkey == 0) {
            printf("Error: cannot find parameter %s in ODB\n", str);
         } else {
            db_get_key(hDB, hkey, &key);
            db_sscanf(value_string, data, &size, 0, key.type);
            status = db_set_data_index(hDB, hkey, data, size, index, key.type);
            if (status == DB_SUCCESS)
               printf("Parameter %s changed to %s\n", str, value_string);
            else
               printf("Cannot change parameter %s\n", str);
         }
      }
   }
   /* let parameter changes propagate to modules */
   cm_yield(0);
   return SUCCESS;
}
INT loop_online ()
Definition at line 4098 of file mana.cpp.
References actual_time, analyzer_loop(), cm_yield(), RPC_SHUTDOWN, SS_ABORT, ss_getchar(), ss_kbhit(), ss_millitime(), SUCCESS, and update_stats().
Referenced by main().
{
   INT status = SUCCESS;
   DWORD last_time_loop, last_time_update, actual_time;
   int ch;
   printf("Running analyzer online. Stop with \"!\"\n");
   /* main loop */
   last_time_update = 0;
   last_time_loop = 0;
   do {
      /* calculate events per second */
      actual_time = ss_millitime();
      if (actual_time - last_time_update > 1000) {
         /* update statistics */
         update_stats();
         last_time_update = actual_time;
         /* check keyboard */
         ch = 0;
         while (ss_kbhit()) {
            ch = ss_getchar(0);
            if (ch == -1)
               ch = getchar();
            if ((char) ch == '!')
               break;
         }
         if ((char) ch == '!')
            break;
      }
      if (analyzer_loop_period == 0)
         status = cm_yield(1000);
      else {
         if (actual_time - last_time_loop > (DWORD) analyzer_loop_period) {
            last_time_loop = actual_time;
            analyzer_loop();
         }
         status = cm_yield(analyzer_loop_period);
      }
   } while (status != RPC_SHUTDOWN && status != SS_ABORT);
   /* update statistics */
   update_stats();
   return status;
}
INT loop_runs_offline ()
Definition at line 4802 of file mana.cpp.
References BANK_LIST::addr, analyze_run(), ANALYZE_REQUEST::bank_list, clp, cm_msg, CM_SUCCESS, DIR_SEPARATOR, ANALYZE_REQUEST::event_name, FORMAT_HBOOK, FORMAT_ROOT, HREND, HROUT, input_file_name, MERROR, BANK_LIST::name, out_info, output_file_name, RPC_SHUTDOWN, and run_number.
Referenced by main().
{
   INT i, status, run_number;
   char input_file_name[256], output_file_name[256], *prn;
   BANK_LIST *bank_list;
   if (!clp.quiet)
      printf("Running analyzer offline. Stop with \"!\"\n");
   run_number = 0;
   out_append = ((strchr(clp.input_file_name[0], '%') != NULL) &&
                 (strchr(clp.output_file_name, '%') == NULL)) ||
       clp.input_file_name[1][0];
   /* loop over range of files */
   if (clp.run_number[0] > 0) {
      if (strchr(clp.input_file_name[0], '%') == NULL) {
         printf
             ("Input file name must contain a wildcard like \"%%05d\" when using a range.\n");
         return 0;
      }
      if (clp.run_number[0] == 0) {
         printf("End of range not specified.\n");
         return 0;
      }
      for (run_number = clp.run_number[0]; run_number <= clp.run_number[1]; run_number++) {
         sprintf(input_file_name, clp.input_file_name[0], run_number);
         if (strchr(clp.output_file_name, '%') != NULL)
            sprintf(output_file_name, clp.output_file_name, run_number);
         else
            strcpy(output_file_name, clp.output_file_name);
         status = analyze_run(run_number, input_file_name, output_file_name);
         if (status == RPC_SHUTDOWN)
            break;
      }
   } else {
      /* loop over input file names */
      for (i = 0; clp.input_file_name[i][0] && i < 10; i++) {
         strcpy(input_file_name, clp.input_file_name[i]);
         /* get run number from input file */
         prn = input_file_name;
         while (strchr(prn, DIR_SEPARATOR) != NULL)
            prn = strchr(prn, DIR_SEPARATOR) + 1;
         if (strpbrk(prn, "0123456789"))
            run_number = atoi(strpbrk(prn, "0123456789"));
         if (strchr(clp.output_file_name, '%') != NULL) {
            if (run_number == 0) {
               printf("Cannot extract run number from input file name.\n");
               return 0;
            }
            sprintf(output_file_name, clp.output_file_name, run_number);
         } else
            strcpy(output_file_name, clp.output_file_name);
         status = analyze_run(run_number, input_file_name, output_file_name);
         if (status == RPC_SHUTDOWN)
            break;
      }
   }
   /* close output file in append mode */
   if (out_file && out_append) {
      if (out_format == FORMAT_HBOOK) {
#ifdef HAVE_HBOOK
         char str[80];
         HROUT(0, i, bstr);
         strcpy(str, "OFFLINE");
         HREND(str);
#else
         cm_msg(MERROR, "loop_runs_offline", "HBOOK support is not compiled in");
#endif
      } else if (out_format == FORMAT_ROOT) {
#ifdef HAVE_ROOT
         CloseRootOutputFile();
#else
         cm_msg(MERROR, "loop_runs_offline", "ROOT support is not compiled in");
#endif                          /* HAVE_ROOT */
      } else {
         if (out_gzip)
            gzclose(out_file);
         else
            fclose(out_file);
      }
      /* free bank buffer */
      for (i = 0; analyze_request[i].event_name[0]; i++) {
         bank_list = analyze_request[i].bank_list;
         if (bank_list == NULL)
            continue;
         for (; bank_list->name[0]; bank_list++)
            if (bank_list->addr) {
               free(bank_list->addr);
               bank_list->addr = NULL;
            }
      }
   }
#ifdef HAVE_PVM
   /* merge slave output files */
   if (pvm_master && out_info.filename[0] && out_append)
      pvm_merge();
#endif
   return CM_SUCCESS;
}
int ma_close (MA_FILE * file)
Definition at line 4412 of file mana.cpp.
References MA_FILE::format, FORMAT_YBOS, MA_FILE::gzfile, MA_FORMAT_YBOS, SUCCESS, and yb_any_file_rclose().
Referenced by analyze_run().
{
   if (file->format == MA_FORMAT_YBOS)
      yb_any_file_rclose(FORMAT_YBOS);
   else
      gzclose(file->gzfile);
   free(file);
   return SUCCESS;
}
MA_FILE* ma_open (char * file_name)
Definition at line 4340 of file mana.cpp.
References MA_FILE::buffer, cm_msg, MA_FILE::device, MA_FILE::file_name, MA_FILE::format, FORMAT_YBOS, MA_FILE::gzfile, MA_DEVICE_DISK, MA_DEVICE_PVM, MA_FORMAT_MIDAS, MA_FORMAT_YBOS, MERROR, PVM_BUFFER_SIZE, MA_FILE::rp, SS_SUCCESS, MA_FILE::wp, yb_any_file_ropen(), yb_any_physrec_skip(), and YB_SUCCESS.
Referenced by analyze_run().
{
   char *ext_str;
   int status;
   MA_FILE *file;
   /* allocate MA_FILE structure */
   file = (MA_FILE *) calloc(sizeof(MA_FILE), 1);
   if (file == NULL) {
      cm_msg(MERROR, "open_input_file", "Cannot allocate MA file structure");
      return NULL;
   }
   /* save file name */
   strcpy(file->file_name, file_name);
   /* for now, just read from disk */
   file->device = MA_DEVICE_DISK;
   /* or from PVM */
   if (pvm_slave) {
      file->device = MA_DEVICE_PVM;
      file->buffer = (char *) malloc(PVM_BUFFER_SIZE);
      file->wp = file->rp = 0;
   }
   /* check input file extension */
   if (strchr(file_name, '.')) {
      ext_str = file_name + strlen(file_name) - 1;
      while (*ext_str != '.')
         ext_str--;
   } else
      ext_str = "";
   if (strncmp(ext_str, ".gz", 3) == 0) {
      ext_str--;
      while (*ext_str != '.' && ext_str > file_name)
         ext_str--;
   }
   if (strncmp(file_name, "/dev/", 4) == 0)     /* assume MIDAS tape */
      file->format = MA_FORMAT_MIDAS;
   else if (strncmp(ext_str, ".mid", 4) == 0)
      file->format = MA_FORMAT_MIDAS;
   else if (strncmp(ext_str, ".ybs", 4) == 0)
      file->format = MA_FORMAT_YBOS;
   else {
      printf
          ("Unknown input data format \"%s\". Please use file extension .mid or mid.gz.\n",
           ext_str);
      return NULL;
   }
   if (file->device == MA_DEVICE_DISK) {
      if (file->format == MA_FORMAT_YBOS) {
         status = yb_any_file_ropen(file_name, FORMAT_YBOS);
         if (status != SS_SUCCESS)
            return NULL;
         if (yb_any_physrec_skip(FORMAT_YBOS, -1) != YB_SUCCESS)
            return (NULL);
      } else {
         file->gzfile = gzopen(file_name, "rb");
         if (file->gzfile == NULL)
            return NULL;
      }
   }
   return file;
}
int ma_read_event (MA_FILE * file, EVENT_HEADER * pevent, int size)
Definition at line 4425 of file mana.cpp.
References bevid_2_mheader(), MA_FILE::buffer, cm_msg, EVENT_HEADER::data_size, MA_FILE::device, DWORD_SWAP, EVENT_HEADER::event_id, MA_FILE::file_name, MA_FILE::format, FORMAT_YBOS, MA_FILE::gzfile, MA_DEVICE_DISK, MA_DEVICE_PVM, MA_FORMAT_MIDAS, MA_FORMAT_YBOS, MERROR, PvmDataInPlace, MA_FILE::rp, EVENT_HEADER::serial_number, ss_sleep(), SS_SUCCESS, tag, EVENT_HEADER::time_stamp, EVENT_HEADER::trigger_mask, WORD_SWAP, MA_FILE::wp, yb_any_event_swap(), and ybos_event_get().
Referenced by analyze_run(), and ma_read_event().
{
   int status, n;
   if (file->device == MA_DEVICE_DISK) {
      if (file->format == MA_FORMAT_MIDAS) {
         if (size < (int) sizeof(EVENT_HEADER)) {
            cm_msg(MERROR, "ma_read_event", "Buffer size too small");
            return -1;
         }
         /* read event header */
         n = gzread(file->gzfile, pevent, sizeof(EVENT_HEADER));
         if (n < (int) sizeof(EVENT_HEADER)) {
            if (n > 0)
               printf("Unexpected end of file %s, last event skipped\n", file->file_name);
            return -1;
         }
         /* swap event header if in wrong format */
         if (pevent->serial_number > 0x1000000) {
            WORD_SWAP(&pevent->event_id);
            WORD_SWAP(&pevent->trigger_mask);
            DWORD_SWAP(&pevent->serial_number);
            DWORD_SWAP(&pevent->time_stamp);
            DWORD_SWAP(&pevent->data_size);
         }
         /* read event */
         n = 0;
         if (pevent->data_size > 0) {
            if (size < (int) pevent->data_size + (int) sizeof(EVENT_HEADER)) {
               cm_msg(MERROR, "ma_read_event", "Buffer size too small");
               return -1;
            }
            n = gzread(file->gzfile, pevent + 1, pevent->data_size);
            if (n != (INT) pevent->data_size) {
               printf("Unexpected end of file %s, last event skipped\n", file->file_name);
               return -1;
            }
         }
         return n + sizeof(EVENT_HEADER);
      } else if (file->format == MA_FORMAT_YBOS) {
         DWORD *pybos, readn;
         if (ybos_event_get(&pybos, &readn) != SS_SUCCESS)
            return -1;
         status = yb_any_event_swap(FORMAT_YBOS, pybos);
         memcpy((char *) (pevent + 1), (char *) pybos, readn);
         status = bevid_2_mheader(pevent, pybos);
         return readn;
      }
   } else if (file->device == MA_DEVICE_PVM) {
#ifdef HAVE_PVM
      int bufid, len, tag, tid;
      EVENT_HEADER *pe;
      struct timeval timeout;
      /* check if anything in buffer */
      if (file->wp > file->rp) {
         pe = (EVENT_HEADER *) (file->buffer + file->rp);
         size = sizeof(EVENT_HEADER) + pe->data_size;
         memcpy(pevent, pe, size);
         file->rp += size;
         return size;
      }
      /* send data request */
      pvm_initsend(PvmDataInPlace);
      pvm_send(pvm_myparent, TAG_DATA);
      /* receive data */
      timeout.tv_sec = 60;
      timeout.tv_usec = 0;
      bufid = pvm_trecv(-1, -1, &timeout);
      if (bufid < 0) {
         pvm_perror("pvm_recv");
         return -1;
      }
      if (bufid == 0) {
         PVM_DEBUG("ma_read_event: timeout receiving data, aborting analyzer.\n");
         return -1;
      }
      status = pvm_bufinfo(bufid, &len, &tag, &tid);
      if (status < 0) {
         pvm_perror("pvm_bufinfo");
         return -1;
      }
      PVM_DEBUG("ma_read_event: receive tag %d, buflen %d", tag, len);
      if (tag == TAG_EOR || tag == TAG_EXIT)
         return -1;
      file->wp = len;
      file->rp = 0;
      status = pvm_upkbyte((char *) file->buffer, len, 1);
      if (status < 0) {
         pvm_perror("pvm_upkbyte");
         return -1;
      }
      /* no new data available, sleep some time to reduce network traffic */
      if (len == 0)
         ss_sleep(200);
      /* re-call this function */
      return ma_read_event(file, pevent, size);
#endif
   }
   return 0;
}
int main (int argc, char * argv[])
Definition at line 5702 of file mana.cpp.
References ana_callback(), clp, cm_cleanup(), cm_connect_experiment1(), cm_disconnect_experiment(), cm_exist(), cm_get_environment(), cm_get_error(), cm_get_experiment_database(), cm_register_function(), cm_register_transition(), cm_set_watchdog_params(), CM_SHUTDOWN, cm_shutdown(), CM_SUCCESS, CM_UNDEF_EXP, db_check_record(), db_find_key(), db_get_record(), db_set_record(), db_set_value(), DEFAULT_RPC_TIMEOUT, DEFAULT_WATCHDOG_TIMEOUT, disable_shm_write, equal_ustring(), FALSE, getparam(), gManaHistsDir, HBOOK_LREC, HLIMAP, HLIMIT, init_module_parameters(), load_last_histos(), loop_online(), loop_runs_offline(), mana_exit(), mana_init(), manaApp, out_info, OUT_INFO_STR, PVM_BUFFER_SIZE, register_requests(), RPC_ANA_CLEAR_HISTOS, save_last_histos(), ss_daemon_init(), ss_force_single_thread(), ss_getchar(), TID_INT, tr_pause(), TR_PAUSE, tr_prestart, tr_resume(), TR_RESUME, TR_START, tr_stop, TR_STOP, and TRUE.
{
   INT status, size;
   char str[256];
   HNDLE hkey;
   /* read in command line parameters into clp structure */
   status = getparam(argc, argv);
   if (status != CM_SUCCESS)
      return 1;
   /* Determine the run number from the input file - Kiburg 1/24/2008 */
   int myrunnumber=0;
   int mystrlen=0;
   char mystr[256];
   strcpy(mystr,clp.input_file_name[0]);
   mystrlen = strlen(mystr);
   if (mystrlen>8){
     char tmpstr[]={mystr[mystrlen-9],
                    mystr[mystrlen-8],
                    mystr[mystrlen-7],
                    mystr[mystrlen-6],
                    mystr[mystrlen-5]};
     myrunnumber=atoi(tmpstr);
     printf("This file indicates the run number is %d\n",myrunnumber);
   }
   /* myrunnumber now contains the current run number, or 0 if it was not poss */
#ifdef HAVE_PVM
   int i;
   str[0] = 0;
   for (i = 0; i < argc; i++) {
      strcat(str, argv[i]);
      strcat(str, " ");
   }
   PVM_DEBUG("Analyzer started: %s", str);
#endif
#ifdef HAVE_ROOT
   char **rargv;
   int rargc;
   /* copy first argument */
   rargc = 0;
   rargv = (char **) malloc(sizeof(char *) * 2);
   rargv[rargc] = (char *) malloc(strlen(argv[rargc]) + 1);
   strcpy(rargv[rargc], argv[rargc]);
   rargc++;
   /* append argument "-b" for batch mode without graphics, unless graphics */
   /* mode has been requested. */
   if(!clp.graphics) {
     rargv[rargc] = (char *) malloc(3);
     rargv[rargc++] = "-b";
   }
   manaApp = new TApplication("ranalyzer", &rargc, rargv);
   /* free argument memory */
   free(rargv[0]);
   if(rargc == 2) {
     free(rargv[1]);
   }
   free(rargv);
   /* default server port */
   clp.root_port = 9090;
#endif
   /* get default from environment */
   cm_get_environment(clp.host_name, sizeof(clp.host_name), clp.exp_name,
                      sizeof(clp.exp_name));
#ifdef HAVE_HBOOK
   /* set default lrec size */
   clp.lrec = HBOOK_LREC;
#endif                          /* HAVE_HBOOK */
   /* become a daemon */
   if (clp.daemon) {
      printf("Becoming a daemon...\n");
      clp.quiet = TRUE;
      ss_daemon_init(FALSE);
   }
   /* set default buffer size */
   if (clp.pvm_buf_size == 0)
      clp.pvm_buf_size = 512 * 1024;
   else
      clp.pvm_buf_size *= 1024;
   if (clp.pvm_buf_size > PVM_BUFFER_SIZE) {
      printf("Buffer size cannot be larger than %dkB\n", PVM_BUFFER_SIZE / 1024);
      return 1;
   }
   /* set online mode if no input filename is given */
   clp.online = (clp.input_file_name[0][0] == 0);
  /* Don't run offline if MIDAS_DIR is not defined */
   if ( ! clp.online )
     {
       if ( !getenv("MIDAS_DIR") )
         {
           printf("For offline running the directory MIDAS_DIR must be defined\n");
           return 1;
         }
     }
#ifdef HAVE_HBOOK
   /* set Ntuple format to RWNT if online */
   if (clp.online || equal_ustring(clp.output_file_name, "OFLN"))
      clp.rwnt = TRUE;
#endif                          /* HAVE_HBOOK */
#ifdef HAVE_PVM
   status = pvm_main(argv);
   if (status != CM_SUCCESS)
      return 1;
#endif
#ifdef HAVE_ROOT
   /* workaround for multi-threading with midas system calls */
   ss_force_single_thread();
#endif
   /* now connect to server */
   if (clp.online) {
      if (clp.host_name[0])
         printf("Connect to experiment %s on host %s...", clp.exp_name, clp.host_name);
      else
         printf("Connect to experiment %s...", clp.exp_name);
   }
   status =
       cm_connect_experiment1(clp.host_name, clp.exp_name, analyzer_name, NULL, odb_size,
                              DEFAULT_WATCHDOG_TIMEOUT);
   if (status == CM_UNDEF_EXP) {
      printf("\nError: Experiment \"%s\" not defined.\n", clp.exp_name);
      if (getenv("MIDAS_DIR")) {
         printf
             ("Note that \"MIDAS_DIR\" is defined, which results in a single experiment\n");
         printf
             ("called \"Default\". If you want to use the \"exptab\" file, undefine \"MIDAS_DIR\".\n");
      }
      return 1;
   } else if (status != CM_SUCCESS) {
      cm_get_error(status, str);
      printf("\nError: %s\n", str);
      return 1;
   }
   if (clp.online)
      printf("OK\n");
   /* set online/offline mode */
   cm_get_experiment_database(&hDB, NULL);
   db_set_value(hDB, 0, "/Runinfo/Online Mode", &clp.online, sizeof(clp.online), 1,
                TID_INT);
   /* set run number in the database -- Brendan Kiburg 1/24/2008 */
   /* commented out by VT on 11/25/2013 */
   //db_set_value(hDB, 0, "/Runinfo/Run number", &myrunnumber, sizeof(int), 1, TID_INT);
   if (clp.online) {
      /* check for duplicate name */
      status = cm_exist(analyzer_name, FALSE);
      if (status == CM_SUCCESS) {
         cm_disconnect_experiment();
         printf("An analyzer named \"%s\" is already running in this experiment.\n",
                analyzer_name);
         printf
             ("Please select another analyzer name in analyzer.c or stop other analyzer.\n");
         return 1;
      }
      /* register transitions if started online */
      if (cm_register_transition(TR_START, tr_prestart, 500) != CM_SUCCESS ||
          cm_register_transition(TR_STOP, tr_stop, 500) != CM_SUCCESS ||
          cm_register_transition(TR_PAUSE, tr_pause, 500) != CM_SUCCESS ||
          cm_register_transition(TR_RESUME, tr_resume, 500) != CM_SUCCESS) {
         printf("Failed to start local RPC server");
         return 1;
      }
   } else {
      if (!pvm_slave) {         /* slave could run on same machine... */
         status = cm_exist(analyzer_name, FALSE);
         if (status == CM_SUCCESS) {
            /* kill hanging previous analyzer */
            cm_cleanup(analyzer_name, FALSE);
            status = cm_exist(analyzer_name, FALSE);
            if (status == CM_SUCCESS) {
               /* analyzer may only run once if offline */
               status = cm_shutdown(analyzer_name, FALSE);
               if (status == CM_SHUTDOWN)
                  printf("Previous analyzer stopped\n");
            }
         }
      }
   }
#ifdef HAVE_HBOOK
   /* register callback for clearing histos */
   cm_register_function(RPC_ANA_CLEAR_HISTOS, ana_callback);
#endif
   /* turn on keepalive messages */
   cm_set_watchdog_params(TRUE, DEFAULT_RPC_TIMEOUT);
   /* decrease watchdog timeout in offline mode */
   if (!clp.online)
      cm_set_watchdog_params(TRUE, 2000);
   /* turn off watchdog if in debug mode */
   if (clp.debug)
      cm_set_watchdog_params(0, 0);
   /* initialize module parameters */
   if (init_module_parameters(FALSE) != CM_SUCCESS) {
      cm_disconnect_experiment();
      return 1;
   }
   /* create ODB structure for output */
   sprintf(str, "/%s/Output", analyzer_name);
   db_check_record(hDB, 0, str, OUT_INFO_STR, TRUE);
   db_find_key(hDB, 0, str, &hkey);
   assert(hkey);
   size = sizeof(out_info);
   db_get_record(hDB, hkey, &out_info, &size, 0);
#ifdef HAVE_ROOT
   /* create the directory for analyzer histograms */
   gManaHistsDir = new TDirectory("MidasHists", "MIDAS Analyzer Histograms", "");
   assert(gManaHistsDir != NULL);
   /* make all ROOT objects created in user module init() functions to into gManaHistsDir */
   gManaHistsDir->cd();
   /* convert .rz names to .root names */
   if (strstr(out_info.last_histo_filename, ".rz"))
      strcpy(out_info.last_histo_filename, "last.root");
   if (strstr(out_info.histo_dump_filename, ".rz"))
      strcpy(out_info.histo_dump_filename, "his%05d.root");
   db_set_record(hDB, hkey, &out_info, sizeof(out_info), 0);
#ifdef OS_LINUX
   /* start socket server */
   if (clp.online && clp.root_port) {
      TThread *th1 = new TThread("root_server_loop", root_server_loop, NULL);
      th1->Run();
   }
#endif
#endif                          /* HAVE_ROOT */
#ifdef HAVE_HBOOK
   /* convert .root names to .rz names */
   if (strstr(out_info.last_histo_filename, ".root"))
      strcpy(out_info.last_histo_filename, "last.rz");
   if (strstr(out_info.histo_dump_filename, ".root"))
      strcpy(out_info.histo_dump_filename, "his%05d.rz");
   db_set_record(hDB, hkey, &out_info, sizeof(out_info), 0);
#endif
#ifdef HAVE_HBOOK
   /* create global memory */
   if (clp.online) {
      HLIMAP(pawc_size / 4, out_info.global_memory_name);
      printf("\nGLOBAL MEMORY NAME = %s\n", out_info.global_memory_name);
   } else {
      if (equal_ustring(clp.output_file_name, "OFLN")) {
         strcpy(str, "OFLN");
         HLIMAP(pawc_size / 4, str);
         printf("\nGLOBAL MEMORY NAME = %s\n", "OFLN");
      } else
         HLIMIT(pawc_size / 4);
   }
#endif                          /* HAVE_HBOOK */
#ifdef HAVE_ROOT
   /* load histos from last.xxx */
   if (clp.online)
      load_last_histos();
#endif
   /* analyzer init function */
   if (mana_init() != CM_SUCCESS) {
      cm_disconnect_experiment();
      return 1;
   }
#ifdef HAVE_HBOOK
   /* load histos from last.xxx */
   if (clp.online)
      load_last_histos();
#endif
   /* reqister event requests */
   register_requests();
   /* initialize ss_getchar */
   if (!clp.quiet && !pvm_slave)
      ss_getchar(0);
  /*---- start main loop ----*/
/* multi-threaded root server only under Linux */
//#if defined(HAVE_ROOT) && defined(OS_LINUX)
#if 0
   /* start event thread */
   TThread *th2 = new TThread("root_event_loop", root_event_loop, NULL);
   th2->Run();
   manaApp->Run();
#else
#ifdef HAVE_ROOT
   if(clp.graphics){
     /* start event thread */
     TThread *th2 = new TThread("root_event_loop", root_event_loop, NULL);
     th2->Run();
     manaApp->Run();
   }
#endif // HAVE_ROOT
   else if (clp.online)
      loop_online();
   else
      loop_runs_offline();
#endif
   /* reset terminal */
   if (!clp.quiet && !pvm_slave)
      ss_getchar(TRUE);
   /* call exit function */
   mana_exit();
   /* save histos to last.xxx */
   if (clp.online)
      save_last_histos();
#ifdef HAVE_PVM
   PVM_DEBUG("Analyzer stopped");
   /* exit PVM */
   pvm_exit();
   /* if PVM slave, don't write *SHM file back */
   if (pvm_slave)
      disable_shm_write = TRUE;
#endif
   /* disconnect from experiment */
   cm_disconnect_experiment();
   return 0;
}
INT mana_exit ()
Definition at line 2060 of file mana.cpp.
References ANALYZE_REQUEST::ana_module, analyzer_exit(), enabled, ANALYZE_REQUEST::event_name, ANA_MODULE::exit, and module.
{
   ANA_MODULE **module;
   INT i, j;
   /* call exit routines from modules */
   for (i = 0; analyze_request[i].event_name[0]; i++) {
      module = analyze_request[i].ana_module;
      for (j = 0; module != NULL && module[j] != NULL; j++)
         if (module[j]->exit != NULL && module[j]->enabled)
            module[j]->exit();
   }
   /* call main analyzer exit routine */
   return analyzer_exit();
}
INT mana_init ()
Definition at line 1935 of file mana.cpp.
References ANALYZE_REQUEST::ana_module, analyzer_init(), ANALYZE_REQUEST::bank_list, book_ntuples(), book_ttree(), clp, cm_msg, db_check_record(), db_delete_key(), db_find_key(), db_get_value(), db_open_record(), db_set_value(), DB_SUCCESS, BANK_LIST::def_key, enabled, ANA_MODULE::enabled, equal_ustring(), ANALYZE_REQUEST::event_name, FALSE, gMiasTreeOutputFileName, ANA_MODULE::init, BANK_LIST::init_str, MERROR, MODE_READ, module, name, BANK_LIST::name, out_info, rpc_tid_size(), strcomb(), SUCCESS, TID_BOOL, TID_STRUCT, TRUE, and BANK_LIST::type.
{
   ANA_MODULE **module;
   INT i, j, status, size;
   HNDLE hkey;
   char str[256], block_name[32];
   BANK_LIST *bank_list;
   double dummy;
   sprintf(str, "/%s/Output", analyzer_name);
   db_find_key(hDB, 0, str, &hkey);
   if (clp.online) {
      status =
          db_open_record(hDB, hkey, &out_info, sizeof(out_info), MODE_READ, NULL, NULL);
      if (status != DB_SUCCESS) {
         cm_msg(MERROR, "bor", "Cannot read output info record");
         return 0;
      }
   }
#if HAVE_ROOT
   /* MIAS Tree output file opened in src/uiuc/EventTree/TEventTreeAnalysis.cpp. */
   gMiasTreeOutputFileName = clp.mias_tree_output_file_name;
   if(gMiasTreeOutputFileName) {
     printf("gMiasTreeOutputFileName = %s\n", gMiasTreeOutputFileName);
   } else {
     printf("gMiasTreeOutputFileName == NULL\n");
   }
#endif
   /* create ODB structures for banks */
   for (i = 0; analyze_request[i].event_name[0]; i++) {
      bank_list = analyze_request[i].bank_list;
      if (bank_list == NULL)
         continue;
      for (; bank_list->name[0]; bank_list++) {
         strncpy(block_name, bank_list->name, 4);
         block_name[4] = 0;
         if (bank_list->type == TID_STRUCT) {
            sprintf(str, "/Equipment/%s/Variables/%s", analyze_request[i].event_name,
                    block_name);
            db_check_record(hDB, 0, str, strcomb(bank_list->init_str), TRUE);
            db_find_key(hDB, 0, str, &hkey);
            bank_list->def_key = hkey;
         } else {
            sprintf(str, "/Equipment/%s/Variables/%s", analyze_request[i].event_name,
                    block_name);
            dummy = 0;
            db_set_value(hDB, 0, str, &dummy, rpc_tid_size(bank_list->type), 1,
                         bank_list->type);
            db_find_key(hDB, 0, str, &hkey);
            bank_list->def_key = hkey;
         }
      }
   }
   /* create ODB structures for fixed events */
   for (i = 0; analyze_request[i].event_name[0]; i++) {
      if (analyze_request[i].init_string) {
         sprintf(str, "/Equipment/%s/Variables", analyze_request[i].event_name);
         db_check_record(hDB, 0, str, strcomb(analyze_request[i].init_string), TRUE);
      }
   }
   /* delete tests in ODB */
   sprintf(str, "/%s/Tests", analyzer_name);
   db_find_key(hDB, 0, str, &hkey);
   if (hkey)
      db_delete_key(hDB, hkey, FALSE);
#ifdef HAVE_HBOOK
   /* create global memory */
   if (clp.online) {
      /* book online N-tuples only once when online */
      status = book_ntuples();
      if (status != SUCCESS)
         return status;
   } else {
      if (equal_ustring(clp.output_file_name, "OFLN")) {
         /* book online N-tuples only once when online */
         status = book_ntuples();
         if (status != SUCCESS)
            return status;
      }
   }
#endif                          /* HAVE_HBOOK */
#ifdef HAVE_ROOT
   if (clp.online) {
      /* book online N-tuples only once when online */
      status = book_ttree();
      if (status != SUCCESS)
         return status;
   }
#endif
   /* call main analyzer init routine */
   status = analyzer_init();
   if (status != SUCCESS)
      return status;
   /* initialize modules */
   for (i = 0; analyze_request[i].event_name[0]; i++) {
      module = analyze_request[i].ana_module;
      for (j = 0; module != NULL && module[j] != NULL; j++) {
         /* copy module enabled flag to ana_module */
         sprintf(str, "/%s/Module switches/%s", analyzer_name, module[j]->name);
         module[j]->enabled = TRUE;
         size = sizeof(BOOL);
         db_get_value(hDB, 0, str, &module[j]->enabled, &size, TID_BOOL, TRUE);
         if (module[j]->init != NULL && module[j]->enabled)
            module[j]->init();
      }
   }
   return SUCCESS;
}
void odb_load (EVENT_HEADER * pevent)
Definition at line 4234 of file mana.cpp.
References analyzer_init(), clp, db_enum_key(), db_find_key(), db_get_value(), DB_NO_MORE_SUBKEYS, db_paste(), db_set_mode(), FALSE, flag, hKey, init_module_parameters(), load_parameters(), MODE_DELETE, MODE_READ, MODE_WRITE, TID_BOOL, and TRUE.
Referenced by process_event().
{
   BOOL flag;
   int size, i, status;
   char str[256];
   HNDLE hKey, hKeyRoot, hKeyEq;
   flag = TRUE;
   size = sizeof(flag);
   sprintf(str, "/%s/ODB Load", analyzer_name);
   db_get_value(hDB, 0, str, &flag, &size, TID_BOOL, TRUE);
   if (flag) {
      for (i = 0; i < 10; i++)
         if (clp.protect[i][0] && !clp.quiet)
            printf("Protect ODB tree \"%s\"\n", clp.protect[i]);
      if (!clp.quiet)
         printf("Load ODB from run %d...", (int) current_run_number);
      if (flag == 1) {
         /* lock all ODB values except run parameters */
         db_set_mode(hDB, 0, MODE_READ, TRUE);
         db_find_key(hDB, 0, "/Experiment/Run Parameters", &hKey);
         if (hKey)
            db_set_mode(hDB, hKey, MODE_READ | MODE_WRITE | MODE_DELETE, TRUE);
         /* and analyzer parameters */
         sprintf(str, "/%s/Parameters", analyzer_name);
         db_find_key(hDB, 0, str, &hKey);
         if (hKey)
            db_set_mode(hDB, hKey, MODE_READ | MODE_WRITE | MODE_DELETE, TRUE);
         /* and equipment (except /variables) */
         db_find_key(hDB, 0, "/Equipment", &hKeyRoot);
         if (hKeyRoot) {
            db_set_mode(hDB, hKeyRoot, MODE_READ | MODE_WRITE | MODE_DELETE, FALSE);
            for (i = 0;; i++) {
               status = db_enum_key(hDB, hKeyRoot, i, &hKeyEq);
               if (status == DB_NO_MORE_SUBKEYS)
                  break;
               db_set_mode(hDB, hKeyEq, MODE_READ | MODE_WRITE | MODE_DELETE, TRUE);
               db_find_key(hDB, hKeyEq, "Variables", &hKey);
               if (hKey)
                  db_set_mode(hDB, hKey, MODE_READ, TRUE);
            }
         }
         /* lock protected trees */
         for (i = 0; i < 10; i++)
            if (clp.protect[i][0]) {
               db_find_key(hDB, 0, clp.protect[i], &hKey);
               if (hKey)
                  db_set_mode(hDB, hKey, MODE_READ, TRUE);
            }
      }
      /* close open records to parameters */
      init_module_parameters(TRUE);
      db_paste(hDB, 0, (char *) (pevent + 1));
      if (flag == 1)
         db_set_mode(hDB, 0, MODE_READ | MODE_WRITE | MODE_DELETE, TRUE);
      /* reinit structured opened by user analyzer */
      analyzer_init();
      /* reload parameter files after BOR event */
      if (!clp.quiet)
         printf("OK\n");
      load_parameters(current_run_number);
      /* open module parameters again */
      init_module_parameters(FALSE);
   }
}
INT process_event (ANALYZE_REQUEST * par, EVENT_HEADER * pevent)
Definition at line 3596 of file mana.cpp.
References actual_time, ANALYZE_REQUEST::ana_module, ANA_SKIP, ANA_MODULE::analyzer, ANALYZE_REQUEST::analyzer, bk_size(), bk_swap(), clp, cm_msg, EVENT_HEADER::data_size, db_get_event_definition(), db_set_value(), enabled, EQ_PERIODIC, EQ_SLOW, equal_ustring(), event_id, EVENT_HEADER::event_id, EVENTID_BOR, ANALYZE_REQUEST::events_received, ANALYZE_REQUEST::events_written, EXT_EVENT_SIZE, FALSE, EVENT_DEF::format, FORMAT_ASCII, FORMAT_HBOOK, FORMAT_MIDAS, FORMAT_ROOT, FORMAT_YBOS, last_time_event, MAX_EVENT_SIZE, MERROR, MINFO, module, odb_load(), out_info, RPC_SHUTDOWN, ANALYZE_REQUEST::rwnt_buffer_size, EVENT_HEADER::serial_number, ss_getchar(), ss_kbhit(), ss_millitime(), SUCCESS, test_increment(), TID_INT, EVENT_DEF::type, ANALYZE_REQUEST::use_tests, write_event_ascii(), write_event_hbook(), write_event_midas(), write_event_odb(), and ybk_size().
{
   INT i, status = SUCCESS, ch;
   ANA_MODULE **module;
   DWORD actual_time;
   EVENT_DEF *event_def;
   static DWORD last_time_kb = 0;
   static char *orig_event = NULL;
   /* verbose output */
   if (clp.verbose)
      printf("event %d, number %d, total size %d\n",
             (int) pevent->event_id,
             (int) pevent->serial_number,
             (int) (pevent->data_size + sizeof(EVENT_HEADER)));
   /* save analyze_request for event number correction */
   _current_par = par;
   /* check keyboard once every second */
   actual_time = ss_millitime();
   if (!clp.online && actual_time - last_time_kb > 1000 && !clp.quiet && !pvm_slave) {
      last_time_kb = actual_time;
      while (ss_kbhit()) {
         ch = ss_getchar(0);
         if (ch == -1)
            ch = getchar();
         if ((char) ch == '!')
            return RPC_SHUTDOWN;
      }
   }
   if (par == NULL) {
      /* load ODB with BOR event */
      if (pevent->event_id == EVENTID_BOR) {
         /* get run number from BOR event */
         current_run_number = pevent->serial_number;
         cm_msg(MINFO, "process_event", "Set run number %d in ODB", current_run_number);
         assert(current_run_number > 0);
         /* set run number in ODB */
         status = db_set_value(hDB, 0, "/Runinfo/Run number", &current_run_number,
                               sizeof(current_run_number), 1, TID_INT);
         assert(status == SUCCESS);
         /* load ODB from event */
         odb_load(pevent);
#ifdef HAVE_PVM
         PVM_DEBUG("process_event: ODB load");
#endif
      }
   } else
      /* increment event counter */
      par->events_received++;
#ifdef HAVE_PVM
   /* if master, distribute events to clients */
   if (pvm_master) {
      status = pvm_distribute(par, pevent);
      return status;
   }
#endif
   /* don't analyze special (BOR,MESSAGE,...) events */
   if (par == NULL)
      return SUCCESS;
   /* swap event if necessary */
   event_def = db_get_event_definition(pevent->event_id);
   if (event_def == NULL)
      return 0;
   if (event_def->format == FORMAT_MIDAS)
      bk_swap((BANK_HEADER *) (pevent + 1), FALSE);
   /* keep copy of original event */
   if (clp.filter) {
      if (orig_event == NULL)
         orig_event = (char *) malloc(MAX_EVENT_SIZE + sizeof(EVENT_HEADER));
      memcpy(orig_event, pevent, pevent->data_size + sizeof(EVENT_HEADER));
   }
  /* skip events after end of run when online */
  if(clp.online && now_stopping) {
    return 0;
  }
  /*---- analyze event ----*/
   /* call non-modular analyzer if defined */
   if (par->analyzer) {
      status = par->analyzer(pevent, (void *) (pevent + 1));
      /* don't continue if event was rejected */
      if (status == ANA_SKIP)
         return 0;
   }
   /* loop over analyzer modules */
   module = par->ana_module;
   for (i = 0; module != NULL && module[i] != NULL; i++) {
      if (module[i]->enabled) {
        //printf("%s\n", module[i]->name);
         status = module[i]->analyzer(pevent, (void *) (pevent + 1));
         /* don't continue if event was rejected */
         if (status == ANA_SKIP)
            return 0;
      }
   }
   if (event_def->format == FORMAT_MIDAS) {
      /* check if event got too large */
      i = bk_size(pevent + 1);
//      if (i > MAX_EVENT_SIZE)
      if (i >= 8*EXT_EVENT_SIZE/10)
         cm_msg(MERROR, "process_event", "Event got too large (%d Bytes) in analyzer", i);
      /* correct for increased event size */
      pevent->data_size = i;
   }
   if (event_def->format == FORMAT_YBOS) {
      /* check if event got too large */
      i = ybk_size((DWORD *) (pevent + 1));
      if (i > MAX_EVENT_SIZE)
         cm_msg(MERROR, "process_event", "Event got too large (%d Bytes) in analyzer", i);
      /* correct for increased event size */
      pevent->data_size = i;
   }
   /* increment tests */
   if (par->use_tests)
      test_increment();
   /* in filter mode, use original event */
   if (clp.filter)
      pevent = (EVENT_HEADER *) orig_event;
   /* write resulting event */
   if (out_file) {
#ifdef HAVE_HBOOK
      if (out_format == FORMAT_HBOOK)
         status = write_event_hbook(out_file, pevent, par);
#endif                          /* HAVE_HBOOK */
#ifdef HAVE_ROOT
      if (out_format == FORMAT_ROOT)
         status = write_event_ttree(out_file, pevent, par);
#endif                          /* HAVE_ROOT */
      if (out_format == FORMAT_ASCII)
         status = write_event_ascii(out_file, pevent, par);
      if (out_format == FORMAT_MIDAS)
         status = write_event_midas(out_file, pevent, par);
      if (status != SUCCESS) {
         cm_msg(MERROR, "process_event", "Error writing to file (Disk full?)");
         return -1;
      }
      par->events_written++;
   }
#ifdef HAVE_HBOOK
   /* fill shared memory */
   if ((clp.online || equal_ustring(clp.output_file_name, "OFLN"))
       && par->rwnt_buffer_size > 0)
      write_event_hbook(NULL, pevent, par);
#endif                          /* HAVE_HBOOK */
   /* put event in ODB once every second */
   if (out_info.events_to_odb)
      for (i = 0; i < 50; i++) {
         if (last_time_event[i].event_id == pevent->event_id) {
            if (event_def->type == EQ_PERIODIC ||
                event_def->type == EQ_SLOW ||
                actual_time - last_time_event[i].last_time > 1000) {
               last_time_event[i].last_time = actual_time;
               write_event_odb(pevent);
            }
            break;
         }
         if (last_time_event[i].event_id == 0) {
            last_time_event[i].event_id = pevent->event_id;
            last_time_event[i].last_time = actual_time;
            write_event_odb(pevent);
            break;
         }
      }
   return SUCCESS;
}
void receive_event (HNDLE buffer_handle, HNDLE request_id, EVENT_HEADER * pheader, void * pevent)
Definition at line 3795 of file mana.cpp.
References ALIGN8, buffer, ANALYZE_REQUEST::buffer_handle, buffer_size, cm_msg, EVENT_HEADER::data_size, ANALYZE_REQUEST::event_name, EXT_EVENT_SIZE, MERROR, process_event(), PTYPE, and ANALYZE_REQUEST::request_id.
{
   INT i;
   ANALYZE_REQUEST *par;
   static DWORD buffer_size = 0;
   static char *buffer = NULL;
   char *pb;
   if (buffer == NULL) {
      buffer = (char *) malloc(EXT_EVENT_SIZE);
      if (buffer == NULL) {
         cm_msg(MERROR, "receive_event", "Not enough memory to buffer event of size %d",
                buffer_size);
         return;
      }
   }
   /* align buffer */
   pb = (char *) ALIGN8((PTYPE) buffer);
   /* copy event to local buffer */
   memcpy(pb, pheader, pheader->data_size + sizeof(EVENT_HEADER));
   par = analyze_request;
   for (i = 0; par->event_name[0]; par++)
      if (par->buffer_handle == buffer_handle && par->request_id == request_id) {
         process_event(par, (EVENT_HEADER *) pb);
      }
}
void register_requests (void)
Definition at line 3861 of file mana.cpp.
References ANALYZER_REQUEST_STR, ANALYZER_STATS_STR, ANALYZE_REQUEST::ar_info, ANALYZE_REQUEST::ar_stats, bm_open_buffer(), bm_request_event(), bm_set_cache_size(), AR_INFO::buffer, ANALYZE_REQUEST::buffer_handle, AR_INFO::client_name, clp, db_check_record(), db_find_key(), db_open_record(), db_set_record(), DB_SUCCESS, AR_INFO::enabled, EVENT_BUFFER_SIZE, AR_INFO::event_id, ANALYZE_REQUEST::event_name, AR_STATS::events_per_sec, AR_STATS::events_received, AR_STATS::events_written, hKey, ANALYZE_REQUEST::hkey_common, AR_INFO::host, MODE_READ, MODE_WRITE, receive_event(), ANALYZE_REQUEST::request_id, AR_INFO::sampling_type, AR_INFO::trigger_mask, TRUE, and update_request().
{
   INT index, status;
   char str[256];
   AR_INFO *ar_info;
   AR_STATS *ar_stats;
   HNDLE hKey;
   /* scan ANALYZE_REQUEST table from ANALYZE.C */
   for (index = 0; analyze_request[index].event_name[0]; index++) {
      ar_info = &analyze_request[index].ar_info;
      ar_stats = &analyze_request[index].ar_stats;
      /* create common subtree from analyze_request table in analyze.c */
      sprintf(str, "/%s/%s/Common", analyzer_name, analyze_request[index].event_name);
      db_check_record(hDB, 0, str, ANALYZER_REQUEST_STR, TRUE);
      db_find_key(hDB, 0, str, &hKey);
      analyze_request[index].hkey_common = hKey;
      strcpy(ar_info->client_name, analyzer_name);
      gethostname(ar_info->host, sizeof(ar_info->host));
      db_set_record(hDB, hKey, ar_info, sizeof(AR_INFO), 0);
      /* open hot link to analyzer request info */
      db_open_record(hDB, hKey, ar_info, sizeof(AR_INFO), MODE_READ, update_request,
                     NULL);
      /* create statistics tree */
      sprintf(str, "/%s/%s/Statistics", analyzer_name, analyze_request[index].event_name);
      db_check_record(hDB, 0, str, ANALYZER_STATS_STR, TRUE);
      db_find_key(hDB, 0, str, &hKey);
      assert(hKey);
      ar_stats->events_received = 0;
      ar_stats->events_per_sec = 0;
      ar_stats->events_written = 0;
      /* open hot link to statistics tree */
      status =
          db_open_record(hDB, hKey, ar_stats, sizeof(AR_STATS), MODE_WRITE, NULL, NULL);
      if (status != DB_SUCCESS)
         printf("Cannot open statistics record, probably other analyzer is using it\n");
      if (clp.online) {
      /*---- open event buffer ---------------------------------------*/
         bm_open_buffer(ar_info->buffer, EVENT_BUFFER_SIZE,
                        &analyze_request[index].buffer_handle);
//         /* set the default buffer cache size */
//         bm_set_cache_size(analyze_request[index].buffer_handle, 100000, 0);
         /* turn off buffer cache */
         bm_set_cache_size(analyze_request[index].buffer_handle, 0, 0);
      /*---- request event -------------------------------------------*/
         if (ar_info->enabled)
            bm_request_event(analyze_request[index].buffer_handle,
                             (short) ar_info->event_id, (short) ar_info->trigger_mask,
                             ar_info->sampling_type, &analyze_request[index].request_id,
                             receive_event);
         else
            analyze_request[index].request_id = -1;
      }
   }
}
void save_last_histos ()
Definition at line 4059 of file mana.cpp.
References add_data_dir(), DIR_SEPARATOR, gManaHistsDir, HRPUT, and out_info.
Referenced by main().
{
   char str[256];
   /* save online histos */
   strcpy(str, out_info.last_histo_filename);
   if (strchr(str, DIR_SEPARATOR) == NULL)
      add_data_dir(str, out_info.last_histo_filename);
   printf("Saving current online histos to %s\n", str);
#ifdef HAVE_HBOOK
   {
      int i;
      char str2[256];
      for (i = 0; i < (int) strlen(str); i++)
         if (isupper(str[i]))
            break;
      if (i < (int) strlen(str)) {
         printf
             ("Error: Due to a limitation in HBOOK, directoy names may not contain uppercase\n");
         printf("       characters. Histogram saving to %s will not work.\n", str);
      } else {
         strcpy(str2, "NT");
         HRPUT(0, str, str2);
      }
   }
#endif
#ifdef HAVE_ROOT
   SaveRootHistograms(gManaHistsDir, str);
#endif
}
void test_clear ()
Definition at line 1027 of file mana.cpp.
References ANA_TEST::count, FALSE, i, TRUE, and ANA_TEST::value.
{
   int i;
   /* clear all tests in interal list */
   for (i = 0; i < n_test; i++) {
      tl[i]->count = 0;
      tl[i]->value = FALSE;
   }
   /* set "always true" test */
   if (n_test > 0)
      tl[0]->value = TRUE;
}
void test_increment ()
Definition at line 1042 of file mana.cpp.
References ANA_TEST::count, FALSE, i, ANA_TEST::value, and value.
{
   int i;
   /* increment test counters based on their value and reset them */
   for (i = 0; i < n_test; i++) {
      if (tl[i]->value)
         tl[i]->count++;
      if (i > 0)
         tl[i]->value = FALSE;
   }
}
void test_write ()
Definition at line 1055 of file mana.cpp.
References count, db_set_value(), i, name, and TID_DWORD.
{
   int i;
   char str[256];
   /* write all test counts to /analyzer/tests/<name> */
   for (i = 0; i < n_test; i++) {
      sprintf(str, "/%s/Tests/%s", analyzer_name, tl[i]->name);
      db_set_value(hDB, 0, str, &tl[i]->count, sizeof(DWORD), 1, TID_DWORD);
   }
}
INT tr_pause (INT rn, char * error)
Definition at line 2495 of file mana.cpp.
References ana_pause_run(), and CM_SUCCESS.
{
   INT status;
   status = ana_pause_run(rn, error);
   if (status != CM_SUCCESS)
      return status;
   return CM_SUCCESS;
}
INT tr_prestart (INT rn, char * error)
Definition at line 2438 of file mana.cpp.
References ANALYZE_REQUEST::ar_stats, bor(), ANALYZE_REQUEST::event_name, AR_STATS::events_per_sec, ANALYZE_REQUEST::events_received, AR_STATS::events_received, ANALYZE_REQUEST::events_written, AR_STATS::events_written, FALSE, and SUCCESS.
{
   INT status, i;
   now_stopping = FALSE;
   /* reset counters */
   for (i = 0; analyze_request[i].event_name[0]; i++) {
      analyze_request[i].ar_stats.events_received = 0;
      analyze_request[i].ar_stats.events_per_sec = 0;
      analyze_request[i].ar_stats.events_written = 0;
      analyze_request[i].events_received = 0;
      analyze_request[i].events_written = 0;
   }
   status = bor(rn, error);
   if (status != SUCCESS)
      return status;
   return SUCCESS;
}
INT tr_resume (INT rn, char * error)
Definition at line 2508 of file mana.cpp.
References ana_resume_run(), and CM_SUCCESS.
{
   INT status;
   status = ana_resume_run(rn, error);
   if (status != CM_SUCCESS)
      return status;
   return CM_SUCCESS;
}
INT tr_stop (INT rn, char * error)
Definition at line 2462 of file mana.cpp.
References bm_get_buffer_level(), bm_poll_event(), CM_SUCCESS, cm_yield(), eor(), ANALYZE_REQUEST::event_name, rpc_is_remote(), SUCCESS, TRUE, and update_stats().
{
   INT i, status, n_bytes;
   /* wait until all events in buffers are analyzed */
  now_stopping = TRUE;
  printf("*** Received stop request ***\n");
   if (rpc_is_remote())
      while (bm_poll_event(TRUE));
   else
      for (i = 0; analyze_request[i].event_name[0]; i++) {
         do {
            bm_get_buffer_level(analyze_request[i].buffer_handle, &n_bytes);
            if (n_bytes > 0)
               cm_yield(100);
         } while (n_bytes > 0);
      }
   /* update statistics */
   update_stats();
   status = eor(rn, error);
   if (status != SUCCESS)
      return status;
   return CM_SUCCESS;
}
void update_request (HNDLE hDB, HNDLE hKey, void * info)
Definition at line 3831 of file mana.cpp.
References ANALYZE_REQUEST::ar_info, bm_delete_request(), bm_request_event(), clp, AR_INFO::enabled, AR_INFO::event_id, ANALYZE_REQUEST::event_name, receive_event(), ANALYZE_REQUEST::request_id, AR_INFO::sampling_type, and AR_INFO::trigger_mask.
Referenced by register_requests().
{
   AR_INFO *ar_info;
   INT i;
   if (!clp.online)
      return;
   /* check which request's key has changed */
   for (i = 0; analyze_request[i].event_name[0]; i++)
      if (analyze_request[i].hkey_common == hKey) {
         ar_info = &analyze_request[i].ar_info;
         /* remove previous request */
         if (analyze_request[i].request_id != -1)
            bm_delete_request(analyze_request[i].request_id);
         /* if enabled, add new request */
         if (ar_info->enabled)
            bm_request_event(analyze_request[i].buffer_handle, (short) ar_info->event_id,
                             (short) ar_info->trigger_mask, ar_info->sampling_type,
                             &analyze_request[i].request_id, receive_event);
         else
            analyze_request[i].request_id = -1;
      }
}
void update_stats ()
Definition at line 3928 of file mana.cpp.
References actual_time, ANALYZE_REQUEST::ar_stats, db_send_changed_records(), ANALYZE_REQUEST::event_name, AR_STATS::events_per_sec, ANALYZE_REQUEST::events_received, AR_STATS::events_received, ANALYZE_REQUEST::events_written, AR_STATS::events_written, last_time, ss_millitime(), and test_write().
{
   int i;
   AR_STATS *ar_stats;
   static DWORD last_time = 0;
   DWORD actual_time;
   actual_time = ss_millitime();
   if (last_time == 0)
      last_time = actual_time;
   if (actual_time - last_time == 0)
      return;
   for (i = 0; analyze_request[i].event_name[0]; i++) {
      ar_stats = &analyze_request[i].ar_stats;
      ar_stats->events_received += analyze_request[i].events_received;
      ar_stats->events_written += analyze_request[i].events_written;
      ar_stats->events_per_sec =
          (analyze_request[i].events_received / ((actual_time - last_time) / 1000.0));
      analyze_request[i].events_received = 0;
      analyze_request[i].events_written = 0;
   }
   /* propagate new statistics to ODB */
   db_send_changed_records();
   /* save tests in ODB */
   test_write();
   last_time = actual_time;
}
INT write_event_ascii (FILE * file, EVENT_HEADER * pevent, ANALYZE_REQUEST * par)
Definition at line 2526 of file mana.cpp.
References ANALYZE_REQUEST::bank_list, bk_is32(), bk_iterate(), bk_iterate32(), LRS1877_HEADER::buffer, buffer, channel, cm_msg, LRS1877_HEADER::count, count, data, db_enum_key(), db_get_event_definition(), db_get_key(), DB_NO_MORE_SUBKEYS, db_sprintf(), BANK_LIST::def_key, EVENT_HEADER::event_id, EVENTID_BOR, EVENTID_EOR, FALSE, EVENT_DEF::format, FORMAT_FIXED, FORMAT_MIDAS, LRS1877_HEADER::geo_addr, EVENT_DEF::hDefKey, hKey, KEY::item_size, MERROR, MIN, KEY::name, BANK_LIST::name, BANK::name, BANK32::name, name, KEY::num_values, BANK_LIST::output_flag, rpc_tid_name(), rpc_tid_size(), EVENT_HEADER::serial_number, SS_FILE_ERROR, ss_get_struct_align(), SS_SUCCESS, STR_INC, TID_LRS1877, TID_LRS1882, TID_PCOS3, TID_STRUCT, EVENT_HEADER::trigger_mask, KEY::type, BANK::type, BANK32::type, type_name, and VALIGN.
Referenced by process_event().
{
   INT status, size, i, j, count;
   BOOL exclude;
   BANK_HEADER *pbh;
   BANK_LIST *pbl;
   EVENT_DEF *event_def;
   BANK *pbk;
   BANK32 *pbk32;
   void *pdata;
   char *pbuf, name[5], type_name[10];
   LRS1882_DATA *lrs1882;
   LRS1877_DATA *lrs1877;
   LRS1877_HEADER *lrs1877_header;
   HNDLE hKey;
   KEY key;
   char buffer[100000];
   DWORD bkname;
   WORD bktype;
   event_def = db_get_event_definition(pevent->event_id);
   if (event_def == NULL)
      return SS_SUCCESS;
   /* write event header */
   pbuf = buffer;
   name[4] = 0;
   if (pevent->event_id == EVENTID_BOR)
      sprintf(pbuf, "%%ID BOR NR %d\n", (int) pevent->serial_number);
   else if (pevent->event_id == EVENTID_EOR)
      sprintf(pbuf, "%%ID EOR NR %d\n", (int) pevent->serial_number);
   else
      sprintf(pbuf, "%%ID %d TR %d NR %d\n", pevent->event_id, pevent->trigger_mask,
              (int) pevent->serial_number);
   STR_INC(pbuf, buffer);
  /*---- MIDAS format ----------------------------------------------*/
   if (event_def->format == FORMAT_MIDAS) {
      pbh = (BANK_HEADER *) (pevent + 1);
      pbk = NULL;
      pbk32 = NULL;
      do {
         /* scan all banks */
         if (bk_is32(pbh)) {
            size = bk_iterate32(pbh, &pbk32, &pdata);
            if (pbk32 == NULL)
               break;
            bkname = *((DWORD *) pbk32->name);
            bktype = (WORD) pbk32->type;
         } else {
            size = bk_iterate(pbh, &pbk, &pdata);
            if (pbk == NULL)
               break;
            bkname = *((DWORD *) pbk->name);
            bktype = (WORD) pbk->type;
         }
         /* look if bank is in exclude list */
         exclude = FALSE;
         pbl = NULL;
         if (par->bank_list != NULL)
            for (i = 0; par->bank_list[i].name[0]; i++)
               if (*((DWORD *) par->bank_list[i].name) == bkname) {
                  pbl = &par->bank_list[i];
                  exclude = (pbl->output_flag == 0);
                  break;
               }
         if (!exclude) {
            if (rpc_tid_size(bktype & 0xFF))
               size /= rpc_tid_size(bktype & 0xFF);
            lrs1882 = (LRS1882_DATA *) pdata;
            lrs1877 = (LRS1877_DATA *) pdata;
            /* write bank header */
            *((DWORD *) name) = bkname;
            if ((bktype & 0xFF00) == 0)
               strcpy(type_name, rpc_tid_name(bktype & 0xFF));
            else if ((bktype & 0xFF00) == TID_LRS1882)
               strcpy(type_name, "LRS1882");
            else if ((bktype & 0xFF00) == TID_LRS1877)
               strcpy(type_name, "LRS1877");
            else if ((bktype & 0xFF00) == TID_PCOS3)
               strcpy(type_name, "PCOS3");
            else
               strcpy(type_name, "unknown");
            sprintf(pbuf, "BK %s TP %s SZ %d\n", name, type_name, size);
            STR_INC(pbuf, buffer);
            if (bktype == TID_STRUCT) {
               if (pbl == NULL)
                  cm_msg(MERROR, "write_event_ascii", "received unknown bank %s", name);
               else
                  /* write structured bank */
                  for (i = 0;; i++) {
                     status = db_enum_key(hDB, pbl->def_key, i, &hKey);
                     if (status == DB_NO_MORE_SUBKEYS)
                        break;
                     db_get_key(hDB, hKey, &key);
                     sprintf(pbuf, "%s:\n", key.name);
                     STR_INC(pbuf, buffer);
                     /* adjust for alignment */
                     pdata =
                         (void *) VALIGN(pdata,
                                         MIN(ss_get_struct_align(), key.item_size));
                     for (j = 0; j < key.num_values; j++) {
                        db_sprintf(pbuf, pdata, key.item_size, j, key.type);
                        strcat(pbuf, "\n");
                        STR_INC(pbuf, buffer);
                     }
                     /* shift data pointer to next item */
                     pdata = (char *) pdata + key.item_size * key.num_values;
                  }
            } else {
               /* write variable length bank  */
               if ((bktype & 0xFF00) == TID_LRS1877) {
                  for (i = 0; i < size;) {
                     lrs1877_header = (LRS1877_HEADER *) & lrs1877[i];
                     /* print header */
                     sprintf(pbuf, "GA %d BF %d CN %d",
                             lrs1877_header->geo_addr, lrs1877_header->buffer,
                             lrs1877_header->count);
                     strcat(pbuf, "\n");
                     STR_INC(pbuf, buffer);
                     count = lrs1877_header->count;
                     if (count == 0)
                        break;
                     for (j = 1; j < count; j++) {
                        /* print data */
                        sprintf(pbuf, "GA %d CH %02d ED %d DA %1.1lf",
                                lrs1877[i].geo_addr, lrs1877[i + j].channel,
                                lrs1877[i + j].edge, lrs1877[i + j].data * 0.5);
                        strcat(pbuf, "\n");
                        STR_INC(pbuf, buffer);
                     }
                     i += count;
                  }
               } else
                  for (i = 0; i < size; i++) {
                     if ((bktype & 0xFF00) == 0)
                        db_sprintf(pbuf, pdata, size, i, bktype & 0xFF);
                     else if ((bktype & 0xFF00) == TID_LRS1882)
                        sprintf(pbuf, "GA %d CH %02d DA %d",
                                lrs1882[i].geo_addr, lrs1882[i].channel, lrs1882[i].data);
                     else if ((bktype & 0xFF00) == TID_PCOS3)
                        sprintf(pbuf, "TBD");
                     else
                        db_sprintf(pbuf, pdata, size, i, bktype & 0xFF);
                     strcat(pbuf, "\n");
                     STR_INC(pbuf, buffer);
                  }
            }
         }
      } while (1);
   }
  /*---- FIXED format ----------------------------------------------*/
   if (event_def->format == FORMAT_FIXED) {
      if (event_def->hDefKey == 0)
         cm_msg(MERROR, "write_event_ascii", "cannot find event definition");
      else {
         pdata = (char *) (pevent + 1);
         for (i = 0;; i++) {
            status = db_enum_key(hDB, event_def->hDefKey, i, &hKey);
            if (status == DB_NO_MORE_SUBKEYS)
               break;
            db_get_key(hDB, hKey, &key);
            sprintf(pbuf, "%s\n", key.name);
            STR_INC(pbuf, buffer);
            /* adjust for alignment */
            pdata = (void *) VALIGN(pdata, MIN(ss_get_struct_align(), key.item_size));
            for (j = 0; j < key.num_values; j++) {
               db_sprintf(pbuf, pdata, key.item_size, j, key.type);
               strcat(pbuf, "\n");
               STR_INC(pbuf, buffer);
            }
            /* shift data pointer to next item */
            pdata = (char *) pdata + key.item_size * key.num_values;
         }
      }
   }
   /* insert empty line after each event */
   strcat(pbuf, "\n");
   size = strlen(buffer);
   /* write record to device */
   if (out_gzip)
      status = gzwrite(file, buffer, size) == size ? SS_SUCCESS : SS_FILE_ERROR;
   else
      status =
          fwrite(buffer, 1, size, file) == (size_t) size ? SS_SUCCESS : SS_FILE_ERROR;
   return status;
}
INT write_event_midas (FILE * file, EVENT_HEADER * pevent, ANALYZE_REQUEST * par)
Definition at line 2743 of file mana.cpp.
References ALIGN8, ANALYZE_REQUEST::bank_list, bk_close(), bk_create(), bk_init(), bk_init32(), bk_is32(), bk_iterate(), bk_iterate32(), bk_size(), buffer, clp, BANK::data_size, BANK32::data_size, EVENT_HEADER::data_size, db_get_event_definition(), EVENT_HEADER::event_id, EXT_EVENT_SIZE, FALSE, EVENT_DEF::format, FORMAT_FIXED, FORMAT_MIDAS, BANK_LIST::name, BANK::name, BANK32::name, BANK_LIST::output_flag, PTYPE, SS_FILE_ERROR, SUCCESS, BANK::type, and BANK32::type.
Referenced by process_event().
{
   INT status, size = 0, i;
   BOOL exclude;
   BANK_HEADER *pbh;
   BANK_LIST *pbl;
   EVENT_DEF *event_def;
   BANK *pbk;
   BANK32 *pbk32;
   char *pdata, *pdata_copy;
   char *pbuf;
   EVENT_HEADER *pevent_copy;
   DWORD bkname, bksize;
   WORD bktype;
   static char *buffer = NULL;
   if (buffer == NULL)
      buffer = (char *) malloc(EXT_EVENT_SIZE);
   pevent_copy = (EVENT_HEADER *) ALIGN8((PTYPE) buffer);
   if (clp.filter) {
      /* use original event */
      size = pevent->data_size + sizeof(EVENT_HEADER);
      memcpy(pevent_copy, pevent, size);
   } else {
      /* copy only banks which are turned on via /analyzer/bank switches */
    /*---- MIDAS format ----------------------------------------------*/
      event_def = db_get_event_definition(pevent->event_id);
      if (event_def == NULL)
         return SUCCESS;
      if (event_def->format == FORMAT_MIDAS) {
         /* copy event header */
         pbuf = (char *) pevent_copy;
         memcpy(pbuf, pevent, sizeof(EVENT_HEADER));
         pbuf += sizeof(EVENT_HEADER);
         pbh = (BANK_HEADER *) (pevent + 1);
         if (bk_is32(pbh))
            bk_init32(pbuf);
         else
            bk_init(pbuf);
         pbk = NULL;
         pbk32 = NULL;
         pdata_copy = pbuf;
         do {
            /* scan all banks */
            if (bk_is32(pbh)) {
               size = bk_iterate32(pbh, &pbk32, &pdata);
               if (pbk32 == NULL)
                  break;
               bkname = *((DWORD *) pbk32->name);
               bktype = (WORD) pbk32->type;
               bksize = pbk32->data_size;
            } else {
               size = bk_iterate(pbh, &pbk, &pdata);
               if (pbk == NULL)
                  break;
               bkname = *((DWORD *) pbk->name);
               bktype = (WORD) pbk->type;
               bksize = pbk->data_size;
            }
            /* look if bank is in exclude list */
            exclude = FALSE;
            pbl = NULL;
            if (par->bank_list != NULL)
               for (i = 0; par->bank_list[i].name[0]; i++)
                  if (*((DWORD *) par->bank_list[i].name) == bkname) {
                     pbl = &par->bank_list[i];
                     exclude = (pbl->output_flag == 0);
                     break;
                  }
            if (!exclude) {
               /* copy bank */
               bk_create(pbuf, (char *) (&bkname), bktype, &pdata_copy);
               memcpy(pdata_copy, pdata, bksize);
               pdata_copy += bksize;
               bk_close(pbuf, pdata_copy);
            }
         } while (1);
         /* set event size in header */
         size = bk_size(pbuf);
         pevent_copy->data_size = size;
         size += sizeof(EVENT_HEADER);
      }
    /*---- FIXED format ----------------------------------------------*/
      if (event_def->format == FORMAT_FIXED) {
         size = pevent->data_size + sizeof(EVENT_HEADER);
         memcpy(pevent_copy, pevent, size);
      }
      if (pevent_copy->data_size == 0)
         return SUCCESS;
   }
   /* write record to device */
   if (out_gzip)
      status = gzwrite(file, pevent_copy, size) == size ? SUCCESS : SS_FILE_ERROR;
   else
      status =
          fwrite(pevent_copy, 1, size, file) == (size_t) size ? SUCCESS : SS_FILE_ERROR;
   return status;
}
INT write_event_odb (EVENT_HEADER * pevent)
Definition at line 3479 of file mana.cpp.
References bk_is32(), bk_iterate(), bk_iterate32(), clp, cm_msg, EVENT_HEADER::data_size, db_enum_key(), db_find_key(), db_get_event_definition(), db_get_key(), DB_NO_MORE_SUBKEYS, db_set_data(), db_set_record(), DB_SUCCESS, EVENT_HEADER::event_id, EVENT_DEF::format, FORMAT_FIXED, FORMAT_MIDAS, EVENT_DEF::hDefKey, hKey, KEY::item_size, MERROR, MIN, BANK::name, BANK32::name, name, KEY::num_values, rpc_tid_size(), ss_get_struct_align(), SS_SUCCESS, SUCCESS, TID_LINK, TID_STRING, TID_STRUCT, KEY::type, BANK::type, BANK32::type, and VALIGN.
{
   INT status, size, n_data, i;
   BANK_HEADER *pbh;
   EVENT_DEF *event_def;
   BANK *pbk;
   BANK32 *pbk32;
   void *pdata;
   char name[5];
   HNDLE hKeyRoot, hKey;
   KEY key;
   DWORD bkname;
   WORD bktype;
   event_def = db_get_event_definition(pevent->event_id);
   if (event_def == NULL)
      return SS_SUCCESS;
  /*---- MIDAS format ----------------------------------------------*/
   if (event_def->format == FORMAT_MIDAS) {
      pbh = (BANK_HEADER *) (pevent + 1);
      pbk = NULL;
      pbk32 = NULL;
      do {
         /* scan all banks */
         if (bk_is32(pbh)) {
            size = bk_iterate32(pbh, &pbk32, &pdata);
            if (pbk32 == NULL)
               break;
            bkname = *((DWORD *) pbk32->name);
            bktype = (WORD) pbk32->type;
         } else {
            size = bk_iterate(pbh, &pbk, &pdata);
            if (pbk == NULL)
               break;
            bkname = *((DWORD *) pbk->name);
            bktype = (WORD) pbk->type;
         }
         n_data = size;
         if (rpc_tid_size(bktype & 0xFF))
            n_data /= rpc_tid_size(bktype & 0xFF);
         /* get bank key */
         *((DWORD *) name) = bkname;
         name[4] = 0;
         status = db_find_key(hDB, event_def->hDefKey, name, &hKeyRoot);
         if (status != DB_SUCCESS) {
            cm_msg(MERROR, "write_event_odb", "received unknown bank %s", name);
            continue;
         }
         if (bktype == TID_STRUCT) {
            /* write structured bank */
            for (i = 0;; i++) {
               status = db_enum_key(hDB, hKeyRoot, i, &hKey);
               if (status == DB_NO_MORE_SUBKEYS)
                  break;
               db_get_key(hDB, hKey, &key);
               /* adjust for alignment */
               if (key.type != TID_STRING && key.type != TID_LINK)
                  pdata =
                      (void *) VALIGN(pdata, MIN(ss_get_struct_align(), key.item_size));
               status = db_set_data(hDB, hKey, pdata, key.item_size * key.num_values,
                                    key.num_values, key.type);
               if (status != DB_SUCCESS) {
                  cm_msg(MERROR, "write_event_odb", "cannot write %s to ODB", name);
                  continue;
               }
               /* shift data pointer to next item */
               pdata = (char *) pdata + key.item_size * key.num_values;
            }
         } else {
            db_get_key(hDB, hKeyRoot, &key);
            /* write variable length bank  */
            if (n_data > 0) {
               status = db_set_data(hDB, hKeyRoot, pdata, size, n_data, key.type);
               if (status != DB_SUCCESS) {
                  cm_msg(MERROR, "write_event_odb", "cannot write %s to ODB", name);
                  continue;
               }
            }
         }
      } while (1);
   }
  /*---- FIXED format ----------------------------------------------*/
   if (event_def->format == FORMAT_FIXED && !clp.online) {
      if (db_set_record(hDB, event_def->hDefKey, (char *) (pevent + 1),
                        pevent->data_size, 0) != DB_SUCCESS)
         cm_msg(MERROR, "write_event_odb", "event #%d size mismatch", pevent->event_id);
   }
   return SUCCESS;
}
Variable Documentation
ANALYZE_REQUEST* _current_par
Definition at line 3588 of file mana.cpp.
ANALYZE_REQUEST analyze_request[]
Definition at line 92 of file analyzer.cpp.
INT analyzer_loop_period
Definition at line 46 of file analyzer.cpp.
char* analyzer_name
Definition at line 43 of file analyzer.cpp.
char* bstr = " "
Definition at line 591 of file mana.cpp.
BOOL clear_histos
Definition at line 755 of file mana.cpp.
struct { ... } clp
Referenced by analyze_run(), bevid_2_mheader(), bor(), eor(), load_last_histos(), load_parameters(), loop_runs_offline(), main(), mana_init(), odb_load(), process_event(), register_requests(), update_request(), write_event_midas(), and write_event_odb().
struct { ... } clp_descrip[]
Referenced by getparam().
char config_file_name[10][256]
Definition at line 656 of file mana.cpp.
DWORD current_run_number
Definition at line 613 of file mana.cpp.
BOOL daemon
Definition at line 665 of file mana.cpp.
Referenced by main().
void* data
Definition at line 674 of file mana.cpp.
BOOL debug
Definition at line 661 of file mana.cpp.
char description[1000]
Definition at line 673 of file mana.cpp.
Referenced by getparam().
short int event_id
Definition at line 3584 of file mana.cpp.
BOOL events_to_odb
Definition at line 757 of file mana.cpp.
char exp_name[NAME_LENGTH]
Definition at line 647 of file mana.cpp.
char filename[256]
Definition at line 751 of file mana.cpp.
BOOL filter
Definition at line 654 of file mana.cpp.
char flag_char
Definition at line 672 of file mana.cpp.
Referenced by getparam().
char global_memory_name[8]
Definition at line 758 of file mana.cpp.
BOOL graphics
Definition at line 655 of file mana.cpp.
char hbook_types[][8]
Initial value:
 {
   "",
   ":U:8",
   ":I:8",
   ":I:8",
   ":U:16",
   ":I:16",
   ":U*4",
   ":I*4",
   ":I*4",
   ":R*4",
   ":R*8",
   ":U:8",
   ":C:32",
   "",
   "",
   "",
   "",
   "",
}
Definition at line 1132 of file mana.cpp.
HNDLE hDB
Definition at line 610 of file mana.cpp.
BOOL histo_dump
Definition at line 753 of file mana.cpp.
char histo_dump_filename[256]
Definition at line 754 of file mana.cpp.
char host_name[HOST_NAME_LENGTH]
Definition at line 646 of file mana.cpp.
INT index
Definition at line 677 of file mana.cpp.
Referenced by al_evaluate_condition(), bm_check_buffers(), bm_close_buffer(), bm_empty_buffers(), bm_mark_read_waiting(), bm_open_buffer(), bm_request_event(), book_ntuples(), caen170a(), cm_set_client_info(), cm_set_watchdog_params(), cm_transition(), condition_test(), crc8(), crc8_add(), create_experim_h(), db_close_database(), db_flush_database(), db_get_event_definition(), db_open_database(), db_open_record(), db_remove_open_record(), db_save_tree_struct(), db_save_xml_key(), db_set_client_name(), el_submit(), feodb_file_dump(), gdImageSetBrush(), gen_init(), getparam(), hs_define_event(), hs_read(), hs_write_event(), hv_init(), interprete(), load_parameters(), log_system_history(), lrs2415(), lrs4032(), main(), MCaenCompProcessRaw(), MD5Final(), MD5Update(), mrpc_call(), mrpc_execute(), multi_init(), odb_hist(), open_history(), print_TPCstack_interval(), process_event(), recv_event_check(), recv_tcp_check(), register_equipment(), register_requests(), rpc_call(), rpc_check_channels(), rpc_client_accept(), rpc_client_call(), rpc_client_connect(), rpc_execute(), rpc_execute_ascii(), rpc_server_accept(), rpc_server_callback(), scheduler(), scope_open(), show_alarm_page(), show_custom_page(), show_elog_page(), show_elog_submit_query(), show_hist_config_page(), show_hist_page(), ss_resume(), ss_suspend(), ss_suspend_get_index(), ss_suspend_get_port(), submit_elog(), tape_dir(), tape_restore(), tr_start1(), user_write(), and write_dac().
char input_file_name[10][256]
Definition at line 648 of file mana.cpp.
Referenced by loop_runs_offline().
char last_histo_filename[256]
Definition at line 756 of file mana.cpp.
DWORD last_time
Definition at line 3585 of file mana.cpp.
struct { ... } last_time_event[50]
INT lock_list[10000]
Definition at line 622 of file mana.cpp.
INT lrec
Definition at line 660 of file mana.cpp.
Referenced by bor().
char mias_tree_output_file_name[256]
Definition at line 651 of file mana.cpp.
INT n
Definition at line 653 of file mana.cpp.
INT n_task
Definition at line 666 of file mana.cpp.
int n_test = 0
Definition at line 990 of file mana.cpp.
BOOL no_load
Definition at line 664 of file mana.cpp.
BOOL now_stopping = FALSE
Definition at line 625 of file mana.cpp.
BOOL ntuple_flag
Definition at line 619 of file mana.cpp.
INT odb_size
Definition at line 49 of file analyzer.cpp.
INT online
Definition at line 645 of file mana.cpp.
Referenced by btb(), car(), and csr().
BOOL out_append
Definition at line 764 of file mana.cpp.
FILE* out_file
Definition at line 761 of file mana.cpp.
INT out_format
Definition at line 763 of file mana.cpp.
BOOL out_gzip
Definition at line 762 of file mana.cpp.
struct { ... } out_info
char output_file_name[256]
Definition at line 649 of file mana.cpp.
Referenced by loop_runs_offline().
char param[10][256]
Definition at line 657 of file mana.cpp.
Referenced by cmd_loop(), command_loop(), mrpc_call(), mrpc_execute(), rpc_call(), rpc_client_call(), rpc_execute(), and rpc_execute_ascii().
INT pawc_size
char protect[10][256]
Definition at line 658 of file mana.cpp.
Referenced by db_lock_database(), and db_unlock_database().
INT pvm_buf_size
Definition at line 667 of file mana.cpp.
BOOL pvm_master = FALSE
Definition at line 589 of file mana.cpp.
BOOL pvm_slave = FALSE
Definition at line 589 of file mana.cpp.
int QUEST[100]
BOOL quiet
Definition at line 663 of file mana.cpp.
Referenced by load_pars_from_file(), and main().
INT root_port
Definition at line 668 of file mana.cpp.
INT run_number[2]
Definition at line 652 of file mana.cpp.
BOOL rwnt
Definition at line 659 of file mana.cpp.
char secondary_output_file_name[256]
Definition at line 650 of file mana.cpp.
ANA_TEST** tl
Definition at line 989 of file mana.cpp.
INT type
Definition at line 675 of file mana.cpp.
Referenced by modules::reader::AddModule(), bk_swap(), db_get_event_definition(), display_range_hist(), display_single_hist(), epics_ca_event_handler(), epics_ca_init(), epics_ca_set(), generate_hist_graph(), getparam(), hs_dump(), load_fragment(), midas_bank_display(), midas_bank_display32(), mscb_addr(), mscb_echo(), mscb_exit(), mscb_flash(), mscb_get_device(), mscb_in(), mscb_info(), mscb_info_variable(), mscb_init(), mscb_lock(), mscb_out(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_release(), mscb_reset(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), mscb_write_group(), rpc_server_dispatch(), show_alarm_page(), show_elog_new(), show_elog_page(), show_elog_submit_query(), show_status_page(), sjy_getdev(), tr_poststop(), tr_start(), tr_start1(), tr_stop(), and ybos_event_swap().
BOOL verbose
Definition at line 662 of file mana.cpp.