AlcapDAQ: midas/examples/basic/mantrigfe.c File Reference
midas/examples/basic/mantrigfe.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "midas.h"
#include "mcstd.h"
#include "experim.h"
Defines
#define N_ADC 4
#define N_TDC 8
#define N_SCLR 4
#define CRATE 0
#define SLOT_IO 23
#define SLOT_ADC 1
#define SLOT_TDC 2
#define SLOT_SCLR 3
Functions
INT frontend_init ()
INT frontend_exit ()
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
INT frontend_loop ()
INT read_mantrig_event (char *pevent, INT off)
ADC0_BANK_STR (adc0_bank_str)
INT poll_event (INT source, INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Variables
char * frontend_name = "mantrigfe"
char * frontend_file_name = __FILE__
BOOL frontend_call_loop = FALSE
INT display_period = 3000
INT max_event_size = 10000
INT max_event_size_frag = 5 * 1024 * 1024
INT event_buffer_size = 10 * 10000
BANK_LIST trigger_bank_list []
BANK_LIST scaler_bank_list []
EQUIPMENT equipment []
Define Documentation
#define CRATE 0
Definition at line 106 of file mantrigfe.c.
#define N_ADC 4
Definition at line 101 of file mantrigfe.c.
#define N_SCLR 4
Definition at line 103 of file mantrigfe.c.
#define N_TDC 8
Definition at line 102 of file mantrigfe.c.
#define SLOT_ADC 1
Definition at line 108 of file mantrigfe.c.
#define SLOT_IO 23
Definition at line 107 of file mantrigfe.c.
#define SLOT_SCLR 3
Definition at line 110 of file mantrigfe.c.
#define SLOT_TDC 2
Definition at line 109 of file mantrigfe.c.
Function Documentation
ADC0_BANK_STR (adc0_bank_str)
INT begin_of_run (INT run_number, char * error)
Definition at line 231 of file mantrigfe.c.
References SUCCESS.
{
   /* put here clear scalers etc. */
   return SUCCESS;
}
INT end_of_run (INT run_number, char * error)
Definition at line 240 of file mantrigfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_exit (void)
Definition at line 224 of file mantrigfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_init (void)
Definition at line 201 of file mantrigfe.c.
References cam_crate_clear(), cam_crate_zinit(), cam_init(), cam_lam_enable(), camc(), camo(), CRATE, SLOT_IO, and SUCCESS.
{
   /* hardware initialization */
   cam_init();
   cam_crate_clear(CRATE);
   cam_crate_zinit(CRATE);
   /* enable LAM in IO unit */
   camc(CRATE, SLOT_IO, 0, 26);
   /* enable LAM in crate controller */
   cam_lam_enable(CRATE, SLOT_IO);
   /* reset external LAM Flip-Flop */
   camo(CRATE, SLOT_IO, 1, 16, 0xFF);
   camo(CRATE, SLOT_IO, 1, 16, 0);
   return SUCCESS;
}
INT frontend_loop (void)
Definition at line 261 of file mantrigfe.c.
References SUCCESS.
{
   /* if frontend_call_loop is true, this routine gets called when
      the frontend is idle or once between every event */
   return SUCCESS;
}
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Definition at line 299 of file mantrigfe.c.
References CMD_INTERRUPT_ATTACH, CMD_INTERRUPT_DETACH, CMD_INTERRUPT_DISABLE, CMD_INTERRUPT_ENABLE, and SUCCESS.
{
   switch (cmd) {
   case CMD_INTERRUPT_ENABLE:
      break;
   case CMD_INTERRUPT_DISABLE:
      break;
   case CMD_INTERRUPT_ATTACH:
      break;
   case CMD_INTERRUPT_DETACH:
      break;
   }
   return SUCCESS;
}
INT pause_run (INT run_number, char * error)
Definition at line 247 of file mantrigfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT poll_event (INT source, INT count, BOOL test)
Definition at line 278 of file mantrigfe.c.
References cam_lam_read(), i, LAM_SOURCE_CRATE, and LAM_SOURCE_STATION.
{
   int i;
   DWORD lam;
   for (i = 0; i < count; i++) {
      cam_lam_read(LAM_SOURCE_CRATE(source), &lam);
      if (lam & LAM_SOURCE_STATION(source))
         if (!test)
            return lam;
   }
   return 0;
}
INT read_mantrig_event (char * pevent, INT off)
Definition at line 317 of file mantrigfe.c.
References bk_close(), bk_create(), bk_init(), bk_size(), cam24i(), CRATE, N_SCLR, SLOT_SCLR, and TID_DWORD.
{
   DWORD *pdata, a;
   /* init bank structure */
   bk_init(pevent);
   /* create SCLR bank */
   bk_create(pevent, "SCLR", TID_DWORD, &pdata);
   /* read scaler bank */
   for (a = 0; a < N_SCLR; a++)
      cam24i(CRATE, SLOT_SCLR, a, 0, pdata++);
   bk_close(pevent, pdata);
   return bk_size(pevent);
}
INT resume_run (INT run_number, char * error)
Definition at line 254 of file mantrigfe.c.
References SUCCESS.
{
   return SUCCESS;
}
Variable Documentation
INT display_period = 3000
Definition at line 89 of file mantrigfe.c.
EQUIPMENT equipment[]
Initial value:
 {
      {"mantrig",
       2, 0,
       "SYSTEM",
       EQ_PERIODIC | EQ_MANUAL_TRIG,
       0,
       "MIDAS",
       TRUE,
       RO_RUNNING | RO_TRANSITIONS |
       RO_ODB,
       30000,
       0,
       0,
       0,
       "", "", "",
       read_mantrig_event,
       NULL, NULL,
       scaler_bank_list,
       }
      ,
      {""}
   }
Definition at line 149 of file mantrigfe.c.
INT event_buffer_size = 10 * 10000
Definition at line 98 of file mantrigfe.c.
BOOL frontend_call_loop = FALSE
Definition at line 86 of file mantrigfe.c.
char* frontend_file_name = __FILE__
Definition at line 83 of file mantrigfe.c.
char* frontend_name = "mantrigfe"
Definition at line 81 of file mantrigfe.c.
INT max_event_size = 10000
Definition at line 92 of file mantrigfe.c.
INT max_event_size_frag = 5 * 1024 * 1024
Definition at line 95 of file mantrigfe.c.
BANK_LIST scaler_bank_list[]
Initial value:
 {
      {"SCLR", TID_DWORD, N_ADC, NULL}
      ,
      {""}
      ,
   }
Definition at line 138 of file mantrigfe.c.
BANK_LIST trigger_bank_list[]
Initial value:
 {
      {"ADC0", TID_STRUCT, sizeof(ADC0_BANK), adc0_bank_str}
      ,
      {"TDC0", TID_WORD, N_TDC, NULL}
      ,
      {""}
      ,
   }
Definition at line 128 of file mantrigfe.c.