AlcapDAQ: analyzer/src/data_quality/MDQ_RunTime.cpp File Reference
analyzer/src/data_quality/MDQ_RunTime.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <map>
#include <utility>
#include <sstream>
#include <cmath>
#include "midas.h"
#include <TH1.h>
#include <TDirectory.h>
#include "TGlobalData.h"
#include "TSetupData.h"
#include "TPulseIsland.h"
Functions
INT MDQ_RunTime_init (void)
INT MDQ_RunTime (EVENT_HEADER *, void *)
INT MDQ_RunTime_eor (INT)
Variables
HNDLE hDB
TGlobalData * gData
TSetupData * gSetup
TH1F * hDQ_RunTime
ANA_MODULE MDQ_RunTime_module
Function Documentation
INT MDQ_RunTime (EVENT_HEADER * pheader, void * pevent)
This method fills the histograms
Definition at line 142 of file MDQ_RunTime.cpp.
References EVENT_HEADER::serial_number, and SUCCESS.
{
        // Get the event number
        int midas_event_number = pheader->serial_number;
        // Some typedefs
        typedef map<string, vector<TPulseIsland*> > TStringPulseIslandMap;
        typedef pair<string, vector<TPulseIsland*> > TStringPulseIslandPair;
        typedef map<string, vector<TPulseIsland*> >::iterator map_iterator;
        // Don't need anything here
        return SUCCESS;
}
INT MDQ_RunTime_eor (INT run_number)
This method does any last minute things to the histograms at the end of the run
Definition at line 88 of file MDQ_RunTime.cpp.
References cm_get_experiment_database(), CM_SUCCESS, db_find_key(), db_get_key(), db_get_value(), DB_SUCCESS, hDB, hDQ_RunTime, hKey, KEY::num_values, size, SUCCESS, and TID_DWORD.
{
  // Get the run duration to scale the histogram
  HNDLE hDB, hKey;
  char keyName[200];
  if(cm_get_experiment_database(&hDB, NULL) != CM_SUCCESS){
    printf("Warning: Could not connect to ODB database!\n");
    return false;
  }
  sprintf(keyName, "/Runinfo/Start time binary");
  if(db_find_key(hDB,0,keyName, &hKey) != SUCCESS){
    printf("Warning: Could not find key %s\n", keyName);
    return false;
  }
  KEY start_time_key;
  if(db_get_key(hDB, hKey, &start_time_key) != DB_SUCCESS){
    printf("Warning: Could not find key %s\n", keyName);
    return false;
  }
  DWORD StartTimes[start_time_key.num_values];
  int size = sizeof(StartTimes);
  if(db_get_value(hDB, 0, keyName, StartTimes, &size, TID_DWORD, 0) != DB_SUCCESS){
    printf("Warning: Could not retrieve values for key %s\n", keyName);
    return false;
  }
  sprintf(keyName, "/Runinfo/Stop time binary");
  if(db_find_key(hDB,0,keyName, &hKey) != SUCCESS){
    printf("Warning: Could not find key %s\n", keyName);
    return false;
  }
  KEY stop_time_key;
  if(db_get_key(hDB, hKey, &stop_time_key) != DB_SUCCESS){
    printf("Warning: Could not find key %s\n", keyName);
    return false;
  }
  DWORD StopTimes[stop_time_key.num_values];
  size = sizeof(StopTimes);
  if(db_get_value(hDB, 0, keyName, StopTimes, &size, TID_DWORD, 0) != DB_SUCCESS){
    printf("Warning: Could not retrieve values for key %s\n", keyName);
    return false;
  }
  int duration = StopTimes[0] - StartTimes[0]; // length of run in seconds (checked against run #2600)
  hDQ_RunTime->Fill(1,duration);
  return SUCCESS;
}
INT MDQ_RunTime_init ()
This method initializes histograms.
Definition at line 64 of file MDQ_RunTime.cpp.
References hDQ_RunTime, string, and SUCCESS.
{
    // See if the DataQuality_LowLevel/ directory already exists
  if (!gDirectory->Cd("DataQuality_LowLevel")) {
    std::string dir_name("DataQuality_LowLevel/");
    gDirectory->mkdir(dir_name.c_str());
    gDirectory->Cd(dir_name.c_str());
  }
  // hDQ_RunTime
  std::string histname = "hDQ_RunTime";
  std::string histtitle = "The duration of the run";
  hDQ_RunTime = new TH1F(histname.c_str(), histtitle.c_str(), 3,0,3);
  hDQ_RunTime->GetXaxis()->SetTitle("");
  hDQ_RunTime->GetYaxis()->SetTitle("Run Time [s]");
  gDirectory->Cd("/MidasHists/");
  return SUCCESS;
}
Variable Documentation
TGlobalData* gData
Definition at line 54 of file analyzer.cpp.
TSetupData* gSetup
Definition at line 55 of file analyzer.cpp.
HNDLE hDB
Definition at line 11 of file mucap_compress.cpp.
TH1F* hDQ_RunTime
Definition at line 46 of file MDQ_RunTime.cpp.
Referenced by MDQ_RunTime_eor(), and MDQ_RunTime_init().
ANA_MODULE MDQ_RunTime_module
Initial value:
{
        "MDQ_RunTime",
        "Andrew Edmonds",
        MDQ_RunTime,
        NULL,
        MDQ_RunTime_eor,
        MDQ_RunTime_init,
        NULL,
        NULL,
        0,
        NULL,
}
Definition at line 48 of file MDQ_RunTime.cpp.