AlcapDAQ: midas/include/mfbstd.h File Reference
midas/include/mfbstd.h File Reference
Defines
#define SUCCESS 1
#define EXPRT
Typedefs
typedef unsigned short int WORD
typedef unsigned long int DWORD
Functions
int EXPRT fb_init ()
void EXPRT fb_exit ()
int EXPRT fb_reset (void)
int EXPRT fb_frd (int paddr, int saddr, DWORD *data)
int EXPRT fb_frc (int paddr, int saddr, DWORD *data)
int EXPRT fb_fwd (int paddr, int saddr, DWORD data)
int EXPRT fb_fwc (int paddr, int saddr, DWORD data)
int EXPRT fb_fwdm (int paddr, int saddr, DWORD data)
int EXPRT fb_fwcm (int b_case, int paddr, int saddr, DWORD data)
int EXPRT fb_frcm (int b_case, DWORD *data)
int EXPRT fb_frdb (int paddr, int saddr, DWORD *data, int *count)
int EXPRT fb_out (DWORD data)
int EXPRT fb_in (void)
void EXPRT fb_frdba (int paddr, int saddr, int count)
int EXPRT fb_load_begin (int addr)
int EXPRT fb_load_end (void)
int EXPRT fb_execute (int addr, void *buffer, int *count)
Define Documentation
#define EXPRT
Definition at line 53 of file mfbstd.h.
#define SUCCESS 1
Definition at line 45 of file mfbstd.h.
Typedef Documentation
typedef unsigned long int DWORD
Definition at line 42 of file mfbstd.h.
typedef unsigned short int WORD
Definition at line 37 of file mfbstd.h.
Function Documentation
int EXPRT fb_execute (int addr, void * buffer, int * count)
Definition at line 532 of file sis4100.c.
References ENABLE_RAM_SEQUENCER, fb_fifo_read(), remote_ram_buffer, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, status, and SUCCESS.
{
int ap, status;
  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + ENABLE_RAM_SEQUENCER + (addr & 0xFF00), 0);
  if (data == NULL)
    return SUCCESS;
  status = fb_fifo_read(&ap);
  if (status & 0x10000)
    return status & 0xFFFF;
  ap &= 0xFFFFFF;
  if (ap < *count)
    *count = ap;
  /* move data from kernel memory to user buffer */
  memcpy(data, remote_ram_buffer, *count);
  return SUCCESS;
}
void EXPRT fb_exit ()
Definition at line 175 of file lrs1821.c.
References _hdio, _sfi, BASE_1691, bt_close(), bt_unmmap(), btd, btd_lm, buffer, fb_exec(), fd_vme, fd_vme_lm, FPREL, remote_ram_buffer, REMOTE_RAM_SIZE, SFI_SIZE, size, vme_close(), and vme_unmap().
{
   // release mastership
   fb_exec(FPREL);
#ifdef _MSC_VER
   {
      DWORD buffer[] = { 6, BASE_1691, BASE_1691 + 18, 0 };
      DWORD size;
      if (_hdio <= 0)
         return;
      DeviceIoControl(_hdio, (DWORD) 0x9c406000, &buffer, sizeof(buffer),
                      NULL, 0, &size, NULL);
   }
#endif
}
int EXPRT fb_frc (int paddr, int saddr, DWORD * data)
Definition at line 322 of file lrs1821.c.
References _RESET, cm_msg, DMARL, DMB_PED_TO_HOST, FALSE, fb_exec(), fb_fifo_read(), fb_load32(), FPAC, FPR, FPWNTA, GO, INPW, MERROR, MWENB, OUTWR, PRIM_CSR, REG1, REG2, REG3, REG4, REG5, REG6, REG7, RNDM_R_DIS, SECAD_W, SFI_IN, SFI_OUT, SFI_SEQUENCER_STATUS_REGISTER, SFI_WRITE_VME2SEQ_FIFO_BASE, status, and TRUE.
{
   // primary address cycle to control space
   OUTWR(REG2, paddr);
   OUTWR(REG1, FPAC * 8);
   OUTWR(REG7, GO);
   // Seconadry address write cycle
   fb_load32(saddr);
   fb_exec(FPWNTA);
   // no pedestal subtraction, reg. 4 & 5 dest of ped.subr.subsyst. output
   OUTWR(REG3, _RESET | MWENB | DMB_PED_TO_HOST);
   // no auto advance due to read
   OUTWR(REG6, 0);
   // data memory addr load from reg. 6
   OUTWR(REG7, DMARL);
   if (!fb_exec(FPR))
      return FALSE;
   ((WORD *) data)[0] = INPW(REG4);
   ((WORD *) data)[1] = INPW(REG5);
   return TRUE;
}
int EXPRT fb_frcm (int b_case, DWORD * data)
Definition at line 391 of file sis4100.c.
References fb_fifo_read(), PRIM_HM_CSRM, RNDM_R_DIS, SFI_OUT, and SFI_WRITE_VME2SEQ_FIFO_BASE.
{
  if (b_case == 3)
    /* case 3 broadcast (sparse data scan) */
    SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_HM_CSRM, 0x09);
  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_R_DIS, 0);
  return fb_fifo_read(data);
}
int EXPRT fb_frd (int paddr, int saddr, DWORD * data)
Definition at line 290 of file lrs1821.c.
References _RESET, DMARL, DMB_PED_TO_HOST, FALSE, fb_exec(), fb_fifo_read(), fb_load32(), FPAD, FPR, FPWNTA, GO, INPW, MWENB, OUTWR, PRIM_DSR, REG1, REG2, REG3, REG4, REG5, REG6, REG7, RNDM_R_DIS, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
{
   // primary address cycle to data space
   OUTWR(REG2, paddr);
   OUTWR(REG1, FPAD * 8);
   OUTWR(REG7, GO);
   // Seconadry address write cycle
   fb_load32(saddr);
   fb_exec(FPWNTA);
   // no pedestal subtraction, reg. 4 & 5 dest of ped.subr.subsyst. output
   OUTWR(REG3, _RESET | MWENB | DMB_PED_TO_HOST);
   // no auto advance due to read
   OUTWR(REG6, 0);
   // data memory addr load from reg. 6
   OUTWR(REG7, DMARL);
   if (!fb_exec(FPR))
      return FALSE;
   ((WORD *) data)[0] = INPW(REG4);
   ((WORD *) data)[1] = INPW(REG5);
   return SUCCESS;
}
int EXPRT fb_frdb (int paddr, int saddr, DWORD * data, int * count)
Definition at line 402 of file lrs1821.c.
References _RESET, ACTIVE, DISCON, DMARL, DMB_PED_TO_DMEM, DMB_PED_TO_HOST, EAUTO, FALSE, fb_exec(), fb_fifo_read(), fb_load32(), fb_read_data_memory(), FPAD, FPRBL, FPWNTA, GO, i, INPW, IWARDY, LOAD_DMA_ADDRESS_POINTER, MWENB, OUTWR, PA_HOST_TO_SEQ, PD_HOST_TO_SEQ, PD_SEQ_TO_HOST, PRIM_DSR, REG0, REG1, REG2, REG3, REG6, REG7, remote_ram_buffer, SECAD_W, SFI_OUT, SFI_SEQUENCER_DISABLE, SFI_SEQUENCER_ENABLE, SFI_WRITE_VME2SEQ_FIFO_BASE, START_FRDB_WITH_CLEAR_WORD_COUNTER, status, STORE_FRDB_WC, SUCCESS, TRUE, and UP.
{
   int i;
   // primary address cycle to data space
   OUTWR(REG2, paddr);
   OUTWR(REG1, FPAD * 8);
   OUTWR(REG7, GO);
   // Seconadry address write cycle
   fb_load32(saddr);
   fb_exec(FPWNTA);
   // no pedestal subtraction, reg. 4 & 5 dest of ped.subr.subsyst. output
   OUTWR(REG3, _RESET | MWENB | DMB_PED_TO_HOST);
   // Configure 1821
   OUTWR(REG3, _RESET | MWENB | DMB_PED_TO_DMEM);       // no pedestal subtraction
//  OUTWR(REG3, _RESET | MWENB | DMB_PED_TO_DMEM | PDMSUB | SUPRNEG | SUPRZERO);
   OUTWR(REG6, EAUTO | UP + 0); // start at zero
   OUTWR(REG7, DMARL);
//  OUTWR(REG1, USER);
//  OUTWR(REG1, HDRBL);
   OUTWR(REG1, FPRBL * 8);      // FPRBL for non-LeCroy modules (slower)
   OUTWR(REG7, GO);
   // wait for 1821 to complete, ~200 us timeout
   for (i = 200; (INPW(REG7) & (IWARDY | ACTIVE)) && i > 0; i--);
   if (i == 0) {
      fprintf(stderr, "fb_fprbl: block transfer timeout.\n");
      return (FALSE);
   }
   // read status
   OUTWR(REG0, PA_HOST_TO_SEQ | PD_SEQ_TO_HOST);
   if (INPW(REG2) != 0x200) {
      fprintf(stderr, "fb_fprbl: bad block transfer status.\n");
      return (FALSE);
   }
   OUTWR(REG0, PA_HOST_TO_SEQ | PD_HOST_TO_SEQ);
   // read dword count
   i = (INPW(REG6) & 0xFFF) * sizeof(DWORD);
   if (i > *count)
      i = *count;
   *count = i;
   fb_read_data_memory(data, *count);
   return (TRUE);
}
void EXPRT fb_frdba (int paddr, int saddr, int count)
Definition at line 452 of file sis4100.c.
References DISCON, PRIM_DSR, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and START_FRDB_WITH_CLEAR_WORD_COUNTER.
{
  /* address module */
  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_DSR, paddr);
  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + SECAD_W, saddr);
  /* VME block mode DMA */
  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + START_FRDB_WITH_CLEAR_WORD_COUNTER,
          (0x0A<<24) | (count/sizeof(DWORD)));
  /* disonnect from module */
  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + DISCON, 0);
}
int EXPRT fb_fwc (int paddr, int saddr, DWORD data)
Definition at line 371 of file lrs1821.c.
References fb_exec(), fb_load32(), FPAC, FPW, FPWNTA, GO, OUTWR, PRIM_CSR, REG1, REG2, REG7, RNDM_W_DIS, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
{
   // primary address cycle to control space
   OUTWR(REG2, paddr);
   OUTWR(REG1, FPAC * 8);
   OUTWR(REG7, GO);
   // Seconadry address write cycle
   fb_load32(saddr);
   fb_exec(FPWNTA);
   fb_load32(data);
   return (fb_exec(FPW));
}
int EXPRT fb_fwcm (int b_case, int paddr, int saddr, DWORD data)
Definition at line 359 of file sis4100.c.
References PRIM_HM_CSRM, RNDM_W, RNDM_W_DIS, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
                             : (1<<slot1) | (1<,slot2) | ...
*/
{
  if (b_case == 2)
    {
    /* case 2 broadcast (class select) */
    SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_HM_CSRM, 0x05);
    SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_W, paddr);
    }
  if (b_case == 3)
    {
    /* case 3 broadcast (pattern select) */
    SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_HM_CSRM, 0x09);
    SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_W, paddr);
    }
  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + SECAD_W, saddr);
  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_W_DIS, data);
  return SUCCESS;
}
int EXPRT fb_fwd (int paddr, int saddr, DWORD data)
Definition at line 354 of file lrs1821.c.
References fb_exec(), fb_load32(), FPAC, FPW, FPWNTA, GO, OUTWR, PRIM_DSR, REG1, REG2, REG7, RNDM_W_DIS, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
{
   // primary address cycle to data space
   OUTWR(REG2, paddr);
   OUTWR(REG1, FPAC * 8);
   OUTWR(REG7, GO);
   // Seconadry address write cycle
   fb_load32(saddr);
   fb_exec(FPWNTA);
   fb_load32(data);
   return (fb_exec(FPW));
}
int EXPRT fb_fwdm (int paddr, int saddr, DWORD data)
Definition at line 388 of file lrs1821.c.
References PRIM_DSRM, RNDM_W_DIS, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
{
   return SUCCESS;
}
int EXPRT fb_in (void)
Definition at line 513 of file lrs1821.c.
References fb_exec(), IN1TST, INPW, OUTWR, PA_HOST_TO_SEQ, PD_HOST_TO_SEQ, PD_SEQ_TO_HOST, REG0, REG2, SFI_IN, and SFI_SEQUENCER_FIFO_FLAG_AND_ECL_NIM_INPUT_REGISTER.
{
   DWORD s;
   fb_exec(IN1TST);
   // read status
   OUTWR(REG0, PA_HOST_TO_SEQ | PD_SEQ_TO_HOST);
   s = INPW(REG2);
   OUTWR(REG0, PA_HOST_TO_SEQ | PD_HOST_TO_SEQ);
   return s;
}
int EXPRT fb_init ()
Definition at line 57 of file lrs1821.c.
References _hdio, _RESET, _sfi, ACTIVE, addr, ARB_LEVEL, BASE_1691, BT_AMOD_A24_SD, bt_close(), bt_clrerr(), bt_gen_name(), bt_get_info(), bt_init(), BT_MAX_DEV_NAME, bt_mmap(), bt_open(), BT_RDWR, bt_set_info(), BT_SUCCESS, BT_SWAP_DEFAULT, btd, btd_lm, buffer, BYPASS, cm_msg, data, FALSE, fb_exec(), FBARB, fd_vme, fd_vme_lm, flag, FPCLBS, FPRBUS, FPREQ, i, IDLE, INPW, MERROR, OUTP, OUTWR, PA_HOST_TO_SEQ, PA_MENU_TO_SEQ, patch_table, PD_HOST_TO_SEQ, PD_MENU_TO_HOST, PD_PMAR_TO_SEQ, PLOAD, PMADL, PMADZ, PWR_1, PWR_2, RCL, REG0, REG1, REG2, REG3, REG4, REG5, REG6, REG7, remote_ram_buffer, REMOTE_RAM_SIZE, ROM_NO, ROM_UPD, ROM_VER, SFI_ADDRESS, SFI_CLEAR_BOTH_LCA1_TEST_REGISTER, SFI_FASTBUS_ARBITRATION_LEVEL_REGISTER, SFI_FASTBUS_TIMEOUT_REGISTER, SFI_OUT, SFI_RESET_REGISTER_GROUP_LCA2, SFI_SEQUENCER_ENABLE, SFI_SEQUENCER_RESET, SFI_SIZE, size, SQWRT, status, SUCCESS, vme_close(), VME_DEVICE, vme_mmap(), and vme_open().
{
   WORD status, version, update, i, data, addr;
   char *pc, str[4];
#ifdef _MSC_VER
   OSVERSIONINFO vi;
   DWORD buffer[] = { 6, BASE_1691, BASE_1691 + 18, 0 };
   DWORD size;
   vi.dwOSVersionInfoSize = sizeof(OSVERSIONINFO);
   GetVersionEx(&vi);
   /* use DirectIO driver under NT to gain port access */
   if (vi.dwPlatformId == VER_PLATFORM_WIN32_NT) {
      _hdio = CreateFile("\\\\.\\directio", GENERIC_READ, FILE_SHARE_READ, NULL,
                         OPEN_EXISTING, 0, NULL);
      if (_hdio == INVALID_HANDLE_VALUE)
         return -1;
   }
   if (!DeviceIoControl(_hdio, (DWORD) 0x9c406000, &buffer, sizeof(buffer),
                        NULL, 0, &size, NULL))
      return -1;
#endif                          /* _MSC_VER */
   // set 1821 front panel address
   OUTP(RCL, BYPASS + 0);
   // clear registers
   OUTWR(REG0, 0);
   OUTWR(REG1, 0);
   OUTWR(REG2, 0);
   OUTWR(REG3, 0);
   OUTWR(REG4, 0);
   OUTWR(REG5, 0);
   OUTWR(REG6, 0);
   OUTWR(REG7, 0);
   // Check communication
   OUTWR(REG3, _RESET);
   status = INPW(REG3);
   if (status != _RESET) {
      cm_msg(MERROR, "fb_init", "Cannot access 1821. Check power and cabling.");
      return FALSE;
   }
   // Check Fastbus power
   status = INPW(REG7);
   if (!(status & PWR_1) || !(status & PWR_2)) {
      cm_msg(MERROR, "fb_init", "Fastbus power test failed. Check power and cabling.");
      return FALSE;
   }
   // Load ROM to sequencer
   OUTWR(REG0, PD_PMAR_TO_SEQ | PA_MENU_TO_SEQ | PLOAD + ROM_NO);
   OUTWR(REG7, PMADZ | PMADL);
   Sleep(10);
   while (INPW(REG7) & ACTIVE);
   // check version of PROM
   OUTWR(REG0, PA_HOST_TO_SEQ | PD_MENU_TO_HOST + ROM_NO);
   OUTWR(REG1, ROM_VER);        // Address of version #
   version = INPW(REG2) & 0xFF;
   OUTWR(REG1, ROM_UPD);        // Address of update #
   update = INPW(REG2) & 0xFF;
   if (version != 6 && version != 7)
      fprintf(stderr, "fb_init: Unkown PROM version %d.%d.\n", version, update);
   // load patch table
   OUTWR(REG0, PA_HOST_TO_SEQ | PD_HOST_TO_SEQ | PLOAD);
   for (i = 0; patch_table[i].addr > 0; i++) {
      pc = patch_table[i].data;
      addr = patch_table[i].addr * 8;
      do {
         if (isxdigit(*pc) && isxdigit(*(pc + 1))) {
            str[0] = *pc;
            str[1] = *(pc + 1);
            str[2] = 0;
            sscanf(str, "%X", &data);
            OUTWR(REG1, addr);
            OUTWR(REG2, data);
            OUTWR(REG7, SQWRT);
         }
         pc += 2;
         addr++;
      } while (*pc);
   }
   // ignite the sequencer
   OUTWR(REG0, PA_HOST_TO_SEQ | PD_HOST_TO_SEQ | PLOAD);
   OUTWR(REG1, IDLE);
   OUTWR(REG0, PA_HOST_TO_SEQ | PD_HOST_TO_SEQ);
   // clear all fastbus lines
   fb_exec(FPCLBS);
   // set arbitration level
   OUTWR(REG2, ARB_LEVEL);
   fb_exec(FBARB);
   // reset bus
   fb_exec(FPRBUS);
   // request mastership
   fb_exec(FPREQ);
   return SUCCESS;
}
int EXPRT fb_load_begin (int addr)
Definition at line 498 of file sis4100.c.
References LOAD_DMA_ADDRESS_POINTER, SFI_NEXT_SEQUENCER_RAM_ADDRESS_REGISTER, SFI_OUT, SFI_SEQUENCER_RAM_LOAD_ENABLE, SFI_SEQUENCER_RESET, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
{
  SFI_OUT(SFI_SEQUENCER_RESET, 0);
  SFI_OUT(SFI_NEXT_SEQUENCER_RAM_ADDRESS_REGISTER, addr);
  SFI_OUT(SFI_SEQUENCER_RAM_LOAD_ENABLE, 0);
  /* initialize DMA address */
  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + LOAD_DMA_ADDRESS_POINTER, 0);
  return SUCCESS;
}
int EXPRT fb_load_end (void)
Definition at line 513 of file sis4100.c.
References DISABLE_RAM_MODE, SFI_OUT, SFI_SEQUENCER_ENABLE, SFI_SEQUENCER_RAM_LOAD_DISABLE, SFI_WRITE_VME2SEQ_FIFO_BASE, SFI_WRITE_VME_OUT_SIGNAL_REGISTER, STORE_FRDB_AP, and SUCCESS.
{
  /* last command: store address pointer */
  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + STORE_FRDB_AP, 0);
  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + DISABLE_RAM_MODE, 0);
  /* 2us delay */
  SFI_OUT(SFI_WRITE_VME_OUT_SIGNAL_REGISTER, 0);
  SFI_OUT(SFI_SEQUENCER_RAM_LOAD_DISABLE, 0);
  SFI_OUT(SFI_SEQUENCER_ENABLE, 0);
  return SUCCESS;
}
int EXPRT fb_out (DWORD data)
Definition at line 532 of file lrs1821.c.
References SEQ_WRITE_OUT_REG, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
{
   // TDB
   return SUCCESS;
}
int EXPRT fb_reset (void)
Definition at line 196 of file lrs1821.c.
References fb_exec(), FPRBUS, SFI_OUT, SFI_SEQUENCER_ENABLE, SFI_SEQUENCER_RESET, and SUCCESS.
{
   // reset bus
   return fb_exec(FPRBUS);
}