AlcapDAQ: midas/utils/mlxspeaker.c File Reference
midas/utils/mlxspeaker.c File Reference
#include <stdio.h>
#include <string.h>
#include <signal.h>
#include "midas.h"
#include "msystem.h"
Defines
#define SPEECH_PROGRAM "festival --tts -"
Functions
void sigpipehandler (int sig)
void siginthandler (int sig)
void receive_message (HNDLE hBuf, HNDLE id, EVENT_HEADER *header, void *message)
int main (int argc, char *argv[])
Variables
static FILE * fp = NULL
BOOL debug = FALSE
char mtUserStr [128]
char mtTalkStr [128]
DWORD shutupTime = 10
Define Documentation
#define SPEECH_PROGRAM "festival --tts -"
Definition at line 59 of file mlxspeaker.c.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 143 of file mlxspeaker.c.
References cm_connect_experiment(), cm_disconnect_experiment(), cm_get_environment(), cm_msg, cm_msg_register(), CM_SUCCESS, cm_yield(), daemon, debug, exp_name, FALSE, fp, host_name, HOST_NAME_LENGTH, i, MERROR, mtTalkStr, mtUserStr, NAME_LENGTH, receive_message(), RPC_SHUTDOWN, shutupTime, siginthandler(), sigpipehandler(), SPEECH_PROGRAM, SS_ABORT, ss_daemon_init(), status, TRUE, and usage().
{
   BOOL daemon = FALSE;
   INT status, i;
   char host_name[HOST_NAME_LENGTH];
   char exp_name[NAME_LENGTH];
   char *speech_program = SPEECH_PROGRAM;
   /* get default from environment */
   cm_get_environment(host_name, sizeof(host_name), exp_name, sizeof(exp_name));
   /* parse command line parameters */
   for (i = 1; i < argc; i++) {
      if (argv[i][0] == '-' && argv[i][1] == 'd')
         debug = TRUE;
      else if (argv[i][0] == '-' && argv[i][1] == 'D')
         daemon = TRUE;
      else if (argv[i][0] == '-') {
         if (i + 1 >= argc || argv[i + 1][0] == '-')
            goto usage;
         if (argv[i][1] == 'e')
            strcpy(exp_name, argv[++i]);
         else if (argv[i][1] == 'h')
            strcpy(host_name, argv[++i]);
         else if (argv[i][1] == 'c')
            speech_program = argv[++i];
         else if (argv[i][1] == 't')
            strcpy(mtTalkStr, argv[++i]);
         else if (argv[i][1] == 'u')
            strcpy(mtUserStr, argv[++i]);
         else if (argv[i][1] == 's')
            shutupTime = atoi(argv[++i]);
         else {
          usage:
            printf
                ("usage: mlxspeaker [-h Hostname] [-e Experiment] [-c command] [-D] daemon\n");
            printf("                  [-t mt_talk] Specify the mt_talk alert command\n");
            printf("                  [-u mt_user] Specify the mt_user alert command\n");
            printf
                ("                  [-s shut up time] Specify the min time interval between alert [s]\n");
            printf
                ("                  The -t & -u switch require a command equivalent to:\n");
            printf("                  '-t play --volume=0.3 file.wav'\n");
            printf
                ("                  [-c command] Used to start the speech synthesizer,\n");
            printf
                ("                              which should read text from it's standard input.\n");
            printf
                ("                              eg: mlxspeaker -c 'festival --tts -'\n\n");
            return 0;
         }
      }
   }
   if (daemon) {
      printf("Becoming a daemon...\n");
      ss_daemon_init(FALSE);
   }
   /* now connect to server */
   status = cm_connect_experiment(host_name, exp_name, "Speaker", NULL);
   if (status != CM_SUCCESS)
      return 1;
   cm_msg_register(receive_message);
   /* Handle SIGPIPE signals generated from errors on the pipe */
   signal(SIGPIPE, sigpipehandler);
   signal(SIGINT, siginthandler);
   if (NULL == (fp = popen(speech_program, "w"))) {
      cm_msg(MERROR, "Speaker", "Unable to start \"%s\": %s\n",
             speech_program, strerror(errno));
      cm_disconnect_experiment();
      exit(2);
   }
   printf("Midas Message Speaker connected to %s.\n",
          host_name[0] ? host_name : "local host");
   do {
      status = cm_yield(1000);
   } while (status != RPC_SHUTDOWN && status != SS_ABORT);
   pclose(fp);
   cm_disconnect_experiment();
   return 1;
}
void receive_message (HNDLE hBuf, HNDLE id, EVENT_HEADER * header, void * message)
Definition at line 85 of file mlxspeaker.c.
References cm_disconnect_experiment(), EVENT_HEADER::data_size, debug, EVENT_HEADER::event_id, fp, MT_TALK, MT_USER, mtTalkStr, mtUserStr, EVENT_HEADER::serial_number, shutupTime, ss_sleep(), ss_system(), ss_time(), and EVENT_HEADER::trigger_mask.
{
   char str[256], *pc, *sp;
   static DWORD last_beep = 0;
   /* print message */
   printf("%s\n", (char *) (message));
   if (fp == NULL) {
      fputs("Speech synthesizer not enabled - terminating\n", stderr);
      cm_disconnect_experiment();
      exit(2);
   }
   if (debug) {
      printf("evID:%hx Mask:%hx Serial:%li Size:%ld\n", header->event_id,
             header->trigger_mask, header->serial_number, header->data_size);
      pc = strchr((char *) (message), ']') + 2;
   }
   /* skip none talking message */
   if (header->trigger_mask == MT_TALK || header->trigger_mask == MT_USER) {
      pc = strchr((char *) (message), ']') + 2;
      sp = pc + strlen(pc) - 1;
      while (*sp == ' ' || *sp == '\t')
         sp--;
      *(++sp) = '\0';
      if (debug) {
         printf("<%s>", pc);
         printf(" sending msg to festival\n");
      }
      /* Send beep first */
      // "play --volume=0.3 /etc/mt_talk.wav"
      if ((ss_time() - last_beep) > shutupTime) {
         switch (header->trigger_mask) {
         case MT_TALK:
            if (mtTalkStr[0])
               sprintf(str, mtTalkStr);
            break;
         case MT_USER:
            if (mtUserStr[0])
               sprintf(str, mtUserStr);
            break;
         }
         ss_system(str);
         last_beep = ss_time();
         ss_sleep(200);
      }
      fprintf(fp, "%s.\n.\n", pc);
      fflush(fp);
   }
   return;
}
void siginthandler (int sig)
Definition at line 75 of file mlxspeaker.c.
References cm_disconnect_experiment(), cm_msg, fp, and MINFO.
Referenced by main().
{
   cm_msg(MINFO, "Speaker", "Speaker interrupted");
   cm_disconnect_experiment();
   pclose(fp);
   exit(0);
}
void sigpipehandler (int sig)
Definition at line 67 of file mlxspeaker.c.
References cm_disconnect_experiment(), cm_msg, fp, and MERROR.
Referenced by main().
{
   cm_msg(MERROR, "Speaker", "No speech synthesizer attached");
   cm_disconnect_experiment();
   pclose(fp);
   exit(2);
}
Variable Documentation
BOOL debug = FALSE
Definition at line 62 of file mlxspeaker.c.
FILE* fp = NULL [static]
Definition at line 61 of file mlxspeaker.c.
Referenced by epics_ca_connection_handler(), epics_ca_event_handler(), epics_ca_exception_handler(), epics_ca_exit(), epics_ca_get(), epics_ca_get_demand(), epics_ca_init(), epics_ca_set(), main(), receive_message(), siginthandler(), and sigpipehandler().
char mtTalkStr[128]
Definition at line 63 of file mlxspeaker.c.
Referenced by main(), and receive_message().
char mtUserStr[128]
Definition at line 63 of file mlxspeaker.c.
Referenced by main(), and receive_message().
DWORD shutupTime = 10
Definition at line 64 of file mlxspeaker.c.
Referenced by main(), and receive_message().