AlcapDAQ: midas/mscb/embedded/mscbutil.c File Reference
midas/mscb/embedded/mscbutil.c File Reference
#include "mscb.h"
#include <intrins.h>
#include <string.h>
Functions
unsigned char crc8 (unsigned char *buffer, int len) reentrant
unsigned char crc8_add (unsigned char crc, unsigned int c)
void rs232_output (void)
void uart_init (unsigned char port, unsigned char baud)
void sysclock_init (void)
void led_int ()
void timer0_int (void)
void led_mode (unsigned char led, unsigned char flag) reentrant
void led_blink (unsigned char led, unsigned char n, int interval) reentrant
void led_set (unsigned char led, unsigned char flag) reentrant using 2
unsigned long time (void)
void watchdog_refresh (void)
void delay_ms (unsigned int ms)
void delay_us (unsigned int us)
void eeprom_read (void *dst, unsigned char len, unsigned short *offset)
void eeprom_write (void *src, unsigned char len, unsigned short *offset)
void eeprom_erase (void)
void eeprom_flash (void)
unsigned char eeprom_retrieve (void)
lcd_out (unsigned char d, bit df)
void lcd_setup ()
void lcd_clear ()
void lcd_goto (char x, char y)
char putchar (char c)
void lcd_puts (char *str)
Variables
SYS_INFO sys_info
MSCB_INFO_VAR code variables []
unsigned char idata _n_sub_addr
unsigned char idata _var_size
unsigned char idata _flkey
unsigned char code crc8_data []
static unsigned long _systime
struct {
unsigned char mode
unsigned char timer
unsigned char interval
unsigned char n
} leds [N_LED]
bit lcd_present
sbit LCD_RS = LCD ^ 3
sbit LCD_R_W = LCD ^ 2
sbit LCD_E = LCD ^ 1
sbit LCD_DB4 = LCD ^ 4
sbit LCD_DB5 = LCD ^ 5
sbit LCD_DB6 = LCD ^ 6
sbit LCD_DB7 = LCD ^ 7
sbit LCD_CLK = LCD ^ 7
sbit LCD_P_W = LCD ^ 6
sbit LCD_SD = LCD ^ 0
Function Documentation
unsigned char crc8 (unsigned char * buffer, int len)
Definition at line 187 of file mscbutil.c.
References buffer, crc8_data, i, and index.
         : crc8
  Purpose: Calculate 8-bit cyclic redundancy checksum for a full
           buffer
  Input:
    unsigned char *data     data buffer
    int len                 data length in bytes
  Function value:
    unsighend char          CRC-8 code
\********************************************************************/
{
   int i;
   unsigned char crc8_code, index;
   crc8_code = 0;
   for (i = 0; i < len; i++) {
      index = buffer[i] ^ crc8_code;
      crc8_code = crc8_data[index];
   }
   return crc8_code;
}
unsigned char crc8_add (unsigned char crc, unsigned int c)
Definition at line 217 of file mscbutil.c.
References crc8_data, and index.
Referenced by send_byte().
         : crc8_add
  Purpose: Single calculation for 8-bit cyclic redundancy checksum
  Input:
    unsigned char crc       running crc
    unsigned char c         new character
  Function value:
    unsighend char          CRC-8 code
\********************************************************************/
{
   unsigned char index;
   index = c ^ crc;
   return crc8_data[index];
}
void delay_ms (unsigned int ms)
Definition at line 902 of file mscbutil.c.
References delay_us(), and yield().
Referenced by adc_read(), lcd_menu(), lcd_setup(), rs485_receive(), user_init(), and user_loop().
{
   unsigned int i;
   for (i = 0; i < ms; i++) {
      delay_us(1000);
      yield();
   }
}
void delay_us (unsigned int us)
Definition at line 937 of file mscbutil.c.
References delay_us(), and j.
Referenced by cap_read(), delay_ms(), delay_us(), lcd_out(), lcd_setup(), read_adc24(), read_adc8(), rs485_receive(), send_byte(), ser_clock(), setup(), sr_read(), write_adc(), write_dac(), and write_gain().
{
#ifdef CPU_C8051F120
   unsigned char j;
#endif
   unsigned char i;
   unsigned int remaining_us;
   if (us <= 250) {
      for (i = (unsigned char) us; i > 0; i--) {
#ifdef CPU_C8051F120
         for (j=22 ; j>0 ; j--)
            _nop_();
#else
         _nop_();
#endif
      }
   } else {
      remaining_us = us;
      while (remaining_us > 250) {
         delay_us(250);
         remaining_us -= 250;
      }
      if (us > 0)
         delay_us(remaining_us);
   }
}
void eeprom_erase (void)
Definition at line 1154 of file mscbutil.c.
References _flkey, DISABLE_INTERRUPTS, EEPROM_OFFSET, ENABLE_INTERRUPTS, FLKEY, FLSCL, LEGACY_PAGE, p, PSCTL, and SFRPAGE.
Referenced by eeprom_flash().
         : eeprom_erase
  Purpose: Erase parameter EEPROM page
\********************************************************************/
{
#ifdef CPU_ADUC812
   ECON = 0x06;
#endif
#ifdef CPU_CYGNAL
   unsigned char xdata *p;
   if (_flkey != 0xF1)
      return;
   DISABLE_INTERRUPTS;
#ifdef CPU_C8051F120
   SFRPAGE = LEGACY_PAGE;
#endif
#if defined(CPU_C8051F000)
   FLSCL = (FLSCL & 0xF0) | 0x08;       // set timer for 11.052 MHz clock
#elif defined(CPU_C8051F020) || defined(CPU_C8051F120)
   FLSCL = FLSCL | 1;                   // enable flash writes
#endif
   PSCTL = 0x03;                        // allow write and erase
#if defined(CPU_C8051F310) || defined(CPU_C8051F320)
   p = EEPROM_OFFSET;                   // erase first page
   FLKEY = 0xA5;                        // write flash key code
   FLKEY = _flkey;
   *p = 0;
// Following code crashed the uC !
//   p = EEPROM_OFFSET+512;               // erase second page
//   FLKEY = 0xA5;                        // write flash key code
//   FLKEY = 0xF1;
//   *p = 0;
#else
   p = EEPROM_OFFSET;                   // erase page
   *p = 0;
#endif
   PSCTL = 0x00;                        // don't allow write
   FLSCL = FLSCL & 0xF0;
#endif
  ENABLE_INTERRUPTS;
}
void eeprom_flash (void)
Definition at line 1212 of file mscbutil.c.
References _flkey, _n_sub_addr, _var_size, eeprom_erase(), eeprom_write(), led_blink(), offset, variables, width, and MSCB_INFO_VAR::width.
Referenced by yield().
         : eeprom_flash
  Purpose: Write system and user parameters to EEPROM
\********************************************************************/
{
   unsigned char i, adr;
   unsigned short magic, offset;
   led_blink(3, 3, 50);
   eeprom_erase();
   offset = 0;
   // system info (node address etc...)
   eeprom_write(&sys_info, sizeof(SYS_INFO), &offset);
   // user channel variables
   for (adr = 0 ; adr < _n_sub_addr ; adr++)
      for (i = 0; variables[i].width; i++)
         eeprom_write((char *)variables[i].ud + _var_size*adr,
                      variables[i].width, &offset);
   // magic
   magic = 0x1234;
   eeprom_write(&magic, 2, &offset);
   _flkey = 0;
}
void eeprom_read (void * dst, unsigned char len, unsigned short * offset)
Definition at line 972 of file mscbutil.c.
References d, EEPROM_OFFSET, ofs, p, and watchdog_refresh().
Referenced by eeprom_retrieve().
         : eeprom_read
  Purpose: Read from internal EEPROM
  Input:
    unsigned char idata *dst    Destination in IDATA memory
    unsigned char len           Number of bytes to copy
    unsigend char *offset       Offset in EEPROM in bytes, gets
                                adjusted after read
\********************************************************************/
{
#ifdef CPU_ADUC812
   unsigned char i, ofs;
   unsigned char *d;
   watchdog_refresh();
   d = dst;
   ofs = *offset;
   EADRL = ofs / 4;
   ECON = 0x01;                 // read page
   for (i = 0; i < len; i++, d++) {
      switch (ofs % 4) {
      case 0:
         *d = EDATA1;
         break;
      case 1:
         *d = EDATA2;
         break;
      case 2:
         *d = EDATA3;
         break;
      case 3:
         *d = EDATA4;
         break;
      }
      ofs++;
      if (ofs % 4 == 0) {
         EADRL = ofs / 4;
         ECON = 0x01;           // read next page
      }
   }
   *offset = ofs;
#endif
#ifdef CPU_CYGNAL
   unsigned char i;
   unsigned char code *p;
   unsigned char *d;
   watchdog_refresh();
   p = EEPROM_OFFSET + *offset;        // read from 128-byte EEPROM page
   d = dst;
   for (i = 0; i < len; i++)
      d[i] = p[i];
   *offset += len;
#endif
}
unsigned char eeprom_retrieve (void)
Definition at line 1248 of file mscbutil.c.
References _n_sub_addr, _var_size, eeprom_read(), offset, variables, width, and MSCB_INFO_VAR::width.
Referenced by setup().
         : eeprom_retrieve
  Purpose: Retrieve system and user parameters from EEPROM
\********************************************************************/
{
   unsigned char i, adr;
   unsigned short magic, offset;
   offset = 0;
   // system info (node address etc...)
   eeprom_read(&sys_info, sizeof(SYS_INFO), &offset);
   // user channel variables
   for (adr = 0 ; adr < _n_sub_addr ; adr++)
      for (i = 0; variables[i].width; i++)
         eeprom_read((char *)variables[i].ud + _var_size*adr,
                     variables[i].width, &offset);
   // check for magic
   eeprom_read(&magic, 2, &offset);
   return (magic == 0x1234);
}
void eeprom_write (void * src, unsigned char len, unsigned short * offset)
Definition at line 1048 of file mscbutil.c.
References _flkey, d, DISABLE_INTERRUPTS, EEPROM_OFFSET, ENABLE_INTERRUPTS, FLKEY, FLSCL, LEGACY_PAGE, ofs, p, PSCTL, SFRPAGE, and watchdog_refresh().
Referenced by eeprom_flash().
         : eeprom_write
  Purpose: Read from internal EEPROM
  Input:
    unsigned char idata *src    Source in IDATA memory
    unsigned char len           Number of bytes to copy
    unsigend char offset        Offset in EEPROM in bytes, gets
                                adjusted after write
\********************************************************************/
{
#ifdef CPU_ADUC812
   unsigned char i, ofs;
   unsigned char *d;
   d = src;
   ofs = *offset;
   EADRL = ofs / 4;
   ECON = 0x01;                 // read page
   for (i = 0; i < len; i++, d++) {
      switch (ofs % 4) {
      case 0:
         EDATA1 = *d;
         break;
      case 1:
         EDATA2 = *d;
         break;
      case 2:
         EDATA3 = *d;
         break;
      case 3:
         EDATA4 = *d;
         ECON = 0x02;           // write page
         break;
      }
      ofs++;
      if (ofs % 4 == 0) {
         EADRL = ofs / 4;
         ECON = 0x01;           // read next page
      }
   }
   if (ofs % 4 != 0)
      ECON = 0x02;              // write last page
   *offset = ofs;
#endif
#ifdef CPU_CYGNAL
   unsigned char xdata *p;      // xdata pointer causes MOVX command
   unsigned char i, b;
   unsigned char *s;
   if (_flkey != 0xF1)
      return;
   DISABLE_INTERRUPTS;
#ifdef CPU_C8051F120
   SFRPAGE = LEGACY_PAGE;
#endif
#if defined(CPU_C8051F000)
   FLSCL = (FLSCL & 0xF0) | 0x08;  // set timer for 11.052 MHz clock
#elif defined(CPU_C8051F020) || defined(CPU_C8051F120)
   FLSCL = FLSCL | 1;           // enable flash writes
#endif
   PSCTL = 0x01;                // allow write
   p = EEPROM_OFFSET + *offset;
   s = src;
   for (i = 0; i < len; i++) {  // write data
      b = *s++;
#if defined(CPU_C8051F310) || defined(CPU_C8051F320)
      FLKEY = 0xA5;             // write flash key code
      FLKEY = _flkey;
#endif
      *p++ = b;
   }
   PSCTL = 0x00;                // don't allow write
   FLSCL = FLSCL & 0xF0;
   *offset += len;
   ENABLE_INTERRUPTS;
   watchdog_refresh();
#endif
}
void lcd_clear ()
Definition at line 1418 of file mscbutil.c.
References lcd_goto(), and lcd_out().
Referenced by application_display(), debug_output(), lcd_menu(), user_loop(), and yield().
{
   lcd_out(0x01, 0);
   lcd_goto(0, 0);
}
void lcd_goto (char x, char y)
Definition at line 1426 of file mscbutil.c.
References lcd_out().
Referenced by application_display(), debug_output(), display_name(), display_value(), lcd_clear(), lcd_menu(), user_init(), and user_loop().
{
   /* goto position x(0..19), y(0..1) */
   lcd_out((x & 0x0F) | (0x80) | ((y & 0x01) << 6), 0);
}
lcd_out (unsigned char d, bit df)
Definition at line 1319 of file mscbutil.c.
References CONFIG_PAGE, delay_us(), P2MDOUT, and SFRPAGE.
Referenced by lcd_clear(), lcd_goto(), lcd_puts(), lcd_setup(), and putchar().
{
   if (!lcd_present)
      return;
   LCD = LCD | 0xF0;            // data input
   SFRPAGE = CONFIG_PAGE;
   P2MDOUT = 0x0F;
   LCD_RS = 0;                  // select BF
   LCD_R_W = 1;
   delay_us(1);
   LCD_E = 1;
   delay_us(10);                // let signals settle
   while (LCD_DB7);             // loop if busy
   LCD_E = 0;
   delay_us(1);
   LCD_R_W = 0;
   P2MDOUT = 0xFF;              // data output
   delay_us(1);
   /* high nibble, preserve P0.0 */
   LCD = (LCD & 0x01) | (d & 0xF0);
   LCD_RS = df;
   delay_us(1);
   LCD_E = 1;
   delay_us(1);
   LCD_E = 0;
   delay_us(1);
   /* now nibble */
   LCD = (LCD & 0x01) | ((d << 4) & 0xF0);
   LCD_RS = df;
   delay_us(1);
   LCD_E = 1;
   delay_us(1);
   LCD_E = 0;
   delay_us(1);
}
void lcd_puts (char * str)
Definition at line 1444 of file mscbutil.c.
References lcd_out().
{
   while (*str)
      lcd_out(*str++, 1);
}
void lcd_setup ()
Definition at line 1364 of file mscbutil.c.
References CONFIG_PAGE, delay_ms(), delay_us(), lcd_out(), P2MDOUT, and SFRPAGE.
Referenced by setup().
{
   unsigned i=0;
   SFRPAGE = CONFIG_PAGE;
   P2MDOUT = 0xFF;
   LCD &= ~(0xFE);
   delay_ms(15);
   LCD |= 0x30;
   LCD_E = 1;
   delay_us(1);
   LCD_E = 0;
   delay_ms(5);
   LCD_E = 1;
   delay_us(1);
   LCD_E = 0;
   delay_ms(1);
   LCD_E = 1;
   delay_us(1);
   LCD_E = 0;
   LCD = 0x20;                  // set 4-bit interface
   LCD_E = 1;
   delay_us(1);
   LCD_E = 0;
   /* test if LCD present */
   LCD = LCD | 0xF0;            // data input
   P2MDOUT = 0x0F;
   LCD_RS = 0;                  // select BF
   LCD_R_W = 1;
   delay_us(1);
   LCD_E = 1;
   delay_us(100);               // let signal settle
   if (LCD_DB7) {
      lcd_present = 0;
      return;
   }
   lcd_present = 1;
   lcd_out(0x2C, 0);            // select 2 lines, big font
   lcd_out(0x0C, 0);            // display on
   lcd_out(0x01, 0);            // clear display
   lcd_out(0x06, 0);            // entry mode
}
void led_blink (unsigned char led, unsigned char n, int interval)
Definition at line 788 of file mscbutil.c.
References interval, n, N_LED, and timer.
Referenced by adc_calib(), BulkOrInterruptIn(), check_current(), check_lpt(), check_rs485(), eeprom_flash(), enter(), execute(), interprete(), main(), rs485_receive(), setup(), user_loop(), and yield().
         : blink led
  Purpose: Blink primary or secondary LED for a couple of times
  Input:
    int led               0 for primary, 1 for secondary, ...
    int interval          Blink interval in ms
    int n                 Number of blinks
\********************************************************************/
{
   if (led < N_LED) {
      if (leds[led].n == 0 && leds[led].timer == 0) {
         leds[led].n = n*2+1;
         leds[led].interval = interval / 10;
         leds[led].timer = 0;
      }
   }
}
void led_int ()
Definition at line 719 of file mscbutil.c.
References LED_OFF, led_set(), n, N_LED, and timer.
Referenced by timer0_int().
{
   unsigned char i;
   /* manage blinking LEDs */
   for (i=0 ; i<N_LED ; i++) {
      if (leds[i].n > 0 && leds[i].timer == 0) {
         if ((leds[i].n & 1) && leds[i].n > 1)
            led_set(i, LED_ON);
         else
            led_set(i, LED_OFF);
         leds[i].n--;
         if (leds[i].n)
            leds[i].timer = leds[i].interval;
      }
      if (leds[i].timer)
         leds[i].timer--;
      if (leds[i].n == 0)
         led_set(i, LED_OFF);
   }
}
void led_mode (unsigned char led, unsigned char flag)
Definition at line 769 of file mscbutil.c.
References flag, and N_LED.
Referenced by set_hv(), setup(), setupRegs(), and user_init().
         : led_mode
  Purpose: Set LED mode
  Input:
    int led               0 for primary, 1 for secondary
    int flag              Noninverted (0) / Inverted (1)
\********************************************************************/
{
   if (led < N_LED)
      leds[led].mode = flag;
}
void led_set (unsigned char led, unsigned char flag)
Definition at line 813 of file mscbutil.c.
References flag, mode, and N_LED.
Referenced by led_int().
{
   /* invert on/of if mode = 1 */
   if (led < N_LED && leds[led].mode)
      flag = !flag;
#ifdef LED_0
   if (led == 0)
      led_0 = flag;
#endif
#ifdef LED_1
   if (led == 1)
      led_1 = flag;
#endif
#ifdef LED_2
   if (led == 2)
      led_2 = flag;
#endif
#ifdef LED_3
   if (led == 3)
      led_3 = flag;
#endif
#ifdef LED_4
   if (led == 4)
      led_4 = flag;
#endif
}
char putchar (char c)
Definition at line 1435 of file mscbutil.c.
References lcd_out().
Referenced by cmd_loop(), showbits(), user_loop(), and user_write().
{
   if (c >= ' ')
      lcd_out(c, 1);
   return c;
}
void rs232_output (void)
Definition at line 509 of file mscbutil.c.
Referenced by yield().
{
}
void sysclock_init (void)
Definition at line 676 of file mscbutil.c.
References CKCON, EA, ET0, N_LED, PT1, SFRPAGE, TH0, TIMER01_PAGE, TL0, TMOD, and TR0.
Referenced by setup().
         : sysclock_init
  Purpose: Initial sytem clock via timer 0
*********************************************************************/
{
   unsigned char i;
   EA = 1;                      // general interrupt enable
   ET0 = 1;                     // Enable Timer 1 interrupt
   PT1 = 1;                     // Interrupt priority high
#ifdef CPU_C8051F120
   SFRPAGE = TIMER01_PAGE;
#endif
   TMOD = (TMOD & 0x0F) | 0x01; // 16-bit counter
#ifdef CPU_C8051F120
   CKCON = 0x02;                // use SYSCLK/48
   TH0 = 0xAF;                  // load initial value
#else
   CKCON = 0x00;                // use SYSCLK/12
   TH0 = 0xDB;                  // load initial value
#endif
   TL0 = 0x00;
   TR0 = 1;                     // start timer 1
   _systime = 0;
   for (i=0 ; i<N_LED ; i++) {
     leds[i].mode = 0;
     leds[i].timer = 0;
     leds[i].interval = 0;
     leds[i].n = 0;
   }
}
unsigned long time (void)
Definition at line 843 of file mscbutil.c.
References DISABLE_INTERRUPTS, and ENABLE_INTERRUPTS.
         : time
  Purpose: Return system time in units of 10ms
\********************************************************************/
{
   unsigned long t;
   DISABLE_INTERRUPTS;
   t = _systime;
   ENABLE_INTERRUPTS;
   return t;
}
void timer0_int (void)
Definition at line 746 of file mscbutil.c.
References led_int(), and TH0.
         : timer0_int
  Purpose: Timer 0 interrupt routine for 100Hz system clock
           Reload value = 0x10000 - 0.01 / (11059200/12)
\********************************************************************/
{
#ifdef CPU_C8051F120
   TH0 = 0xAF;                  // for 98 MHz clock
#else
   TH0 = 0xDC;                  // reload timer values, let LSB freely run
#endif
   _systime++;                  // increment system time
   led_int();
}
void uart_init (unsigned char port, unsigned char baud)
Definition at line 517 of file mscbutil.c.
References CKCON, EA, EIE2, EIP2, ES0, PS0, RCAP2H, RCAP2L, RCAP4H, RCAP4L, SCON0, SCON1, SFRPAGE, SSTA0, T2CON, T4CON, TH1, TIMER01_PAGE, TMOD, TMR2_PAGE, TMR2CF, TMR2CN, TR1, UART0_PAGE, and UART1_PAGE.
Referenced by setup(), user_init(), user_write(), and user_write_conf().
         : uart_init
  Purpose: Initialize serial interface, user Timer 1 for UART0 and
           (optionally) Timer 2 (4 for F020) for UART1
  Input:
    unsigned char baud      1:9600,2:19200,3:28800,4:57600,
                            5:115200,6:172800,7:345600 Baud
\********************************************************************/
{
#if defined (CPU_C8051F310)
   unsigned char code baud_table[] =
     {0x100 - 0,    //  N/A
      0x100 - 0,    //  N/A
      0x100 - 192,  //  28800
      0x100 - 96,   //  57600
      0x100 - 48,   // 115200
      0x100 - 32,   // 172800
      0x100 - 16 }; // 345600
#elif defined(CPU_C8051F320)       // 12 MHz
   unsigned char code baud_table[] =
     {0x100 - 0,    //  N/A
      0x100 - 0,    //  N/A
      0x100 - 208,  //  28800
      0x100 - 104,  //  57600
      0x100 - 52,   // 115200
      0x100 - 35,   // 172800  2% error
      0x100 - 17 }; // 345600  2% error
#elif defined(CPU_C8051F120)       // 98 MHz
   unsigned char code baud_table[] =  // UART0 via timer 2
     {0x100 - 0,    //  N/A
      0x100 - 0,    //  N/A
      0x100 - 208,  //  28800  2% error
      0x100 - 104,  //  57600  2% error
      0x100 - 53,   // 115200  2% error
      0x100 - 35,   // 172800  2% error
      0x100 - 18 }; // 345600  2% error
#else                              // 11.0592 MHz
   unsigned char code baud_table[] =
     {0x100 - 36,   //   9600
      0x100 - 18,   //  14400
      0x100 - 12,   //  28800
      0x100 - 6,    //  57600
      0x100 - 3,    // 115200
      0x100 - 2,    // 172800
      0x100 - 1 };  // 345600
#endif
   if (port == 0) { /*---- UART0 ----*/
#ifdef CPU_C8051F120
      SFRPAGE = UART0_PAGE;
#endif
      SCON0 = 0xD0;                // Mode 3, 9 bit, receive enable
#ifdef CPU_C8051F120
      SFRPAGE = UART0_PAGE;
      SSTA0 = 0x15;                // User Timer 2 for baud rate, div2 disabled
      SFRPAGE = TMR2_PAGE;
      TMR2CF = 0x08;               // use system clock for timer 2
      RCAP2H = 0xFF;
      RCAP2L = baud_table[baud - 1];  // load initial values
      TMR2CN = 0x04;               // start timer 2
      SFRPAGE = UART0_PAGE;
#else // CPU_C8051F120
      TMOD  = (TMOD & 0x0F)| 0x20; // Timer 1 8-bit counter with auto reload
#if defined(CPU_C8051F310) || defined(CPU_C8051F320)
      CKCON |= 0x08;               // use system clock
#else
      T2CON &= ~30;                // User Timer 1 for baud rate
      CKCON |= 0x10;               // use system clock
#endif
      TH1 = baud_table[baud - 1];  // load initial values
      TR1 = 1;                     // start timer 1
#endif // CPU_C8051F120
      ES0 = 1;                     // enable serial interrupt
      PS0 = 0;                     // serial interrupt low priority
   } else { /*---- UART1 ----*/
#if defined(CPU_C8051F020)
      SCON1 = 0x50;                // Mode 1, 8 bit, receive enable
      T4CON = 0x34;                // timer 4 RX+TX mode
      RCAP4H = 0xFF;
      RCAP4L = baud_table[baud - 1];
      EIE2 |= 0x40;                // enable serial interrupt
      EIP2 &= ~0x40;               // serial interrupt low priority
#ifdef SCS_210
      uart1_init_buffer();
#endif
#elif defined(CPU_C8051F120)       // 98 MHz
      SFRPAGE = UART1_PAGE;
      SCON1 = 0xD0;                // Mode 3, 9 bit, receive enable
      SFRPAGE = TIMER01_PAGE;
      TMOD  = (TMOD & 0x0F)| 0x20; // Timer 1 8-bit counter with auto reload
      CKCON = 0x02;                // use SYSCLK/48 (needed by timer 0)
      TH1 = 0xF7;                  // gives 113452 baud, neglegt "baud" parameter
      TR1 = 1;                     // start timer 1
      EIE2 |= 0x40;                // enable serial interrupt
      EIP2 &= ~0x40;               // serial interrupt low priority
      uart1_init_buffer();
#endif
   }
   EA = 1;                         // general interrupt enable
}
void watchdog_refresh (void)
Definition at line 862 of file mscbutil.c.
References PCA0CPH4, and WDTCN.
Referenced by adc_read(), check_lpt(), check_rs485(), eeprom_read(), eeprom_write(), main(), setup(), and yield().
         : watchdog_refresh
  Purpose: Refresh watchdog, has to be called regularly, otherwise
           the watchdog issues a reset
\********************************************************************/
{
#ifdef USE_WATCHDOG
#ifdef CPU_ADUC812
   WDR1 = 1;
   WDR2 = 1;
#endif
#ifdef CPU_CYGNAL
#if defined(CPU_C8051F310) || defined(CPU_C8051F320)
   PCA0CPH4 = 0x00;
#else
   WDTCN = 0xA5;
#endif
#endif
#endif
}
Variable Documentation
unsigned char idata _flkey
Definition at line 231 of file mscbmain.c.
Referenced by eeprom_erase(), eeprom_flash(), eeprom_write(), setup(), and yield().
unsigned char idata _n_sub_addr
Definition at line 52 of file hvr_200.c.
Referenced by addr_node16(), addr_node8(), eeprom_flash(), eeprom_retrieve(), and setup().
unsigned long _systime [static]
Definition at line 647 of file mscbutil.c.
unsigned char idata _var_size
Definition at line 233 of file mscbmain.c.
Referenced by eeprom_flash(), eeprom_retrieve(), interprete(), and setup().
unsigned char code crc8_data[]
Definition at line 152 of file mscbutil.c.
Referenced by crc8(), and crc8_add().
unsigned char interval
Definition at line 654 of file mscbutil.c.
Referenced by cm_cleanup(), cm_watchdog(), led_blink(), main(), and show_alarm_page().
sbit LCD_CLK = LCD ^ 7
Definition at line 1313 of file mscbutil.c.
sbit LCD_DB4 = LCD ^ 4
Definition at line 1308 of file mscbutil.c.
sbit LCD_DB5 = LCD ^ 5
Definition at line 1309 of file mscbutil.c.
sbit LCD_DB6 = LCD ^ 6
Definition at line 1310 of file mscbutil.c.
sbit LCD_DB7 = LCD ^ 7
Definition at line 1311 of file mscbutil.c.
sbit LCD_E = LCD ^ 1
Definition at line 1301 of file mscbutil.c.
sbit LCD_P_W = LCD ^ 6
Definition at line 1314 of file mscbutil.c.
bit lcd_present
Definition at line 1283 of file mscbutil.c.
Referenced by setup().
sbit LCD_R_W = LCD ^ 2
Definition at line 1300 of file mscbutil.c.
sbit LCD_RS = LCD ^ 3
Definition at line 1299 of file mscbutil.c.
sbit LCD_SD = LCD ^ 0
Definition at line 1315 of file mscbutil.c.
struct { ... } leds[N_LED]
unsigned char mode
Definition at line 652 of file mscbutil.c.
Referenced by command_loop(), dl401_finished(), dl403_runBit(), dl403_running(), led_set(), lrs2373_set(), and vmedrv_open().
unsigned char n
Definition at line 655 of file mscbutil.c.
SYS_INFO sys_info
Definition at line 239 of file mscbmain.c.
unsigned char timer
Definition at line 653 of file mscbutil.c.
Referenced by led_blink(), and led_int().
MSCB_INFO_VAR code variables[]
Definition at line 149 of file hvr_200.c.
Referenced by eeprom_flash(), eeprom_retrieve(), interprete(), lcd_menu(), and setup().