AlcapDAQ: midas/mscb/mscb.c File Reference
midas/mscb/mscb.c File Reference
#include <stdio.h>
#include "mscb.h"
#include "rpc.h"
Data Structures
struct CACHE_ENTRY
Defines
#define MSCB_LIBRARY_VERSION "1.7.5"
#define MSCB_PROTOCOL_VERSION "1.7"
#define LPT_STROBE 1
#define LPT_ACK 2
#define LPT_RESET 3
#define LPT_BIT9 4
#define LPT_READMODE 5
#define LPT_BUSY 6
#define LPT_DATAREADY 7
#define TIMEOUT_OUT 1000
#define RS485_FLAG_BIT9 (1<<0)
#define RS485_FLAG_NO_ACK (1<<1)
#define RS485_FLAG_SHORT_TO (1<<2)
#define RS485_FLAG_LONG_TO (1<<3)
#define RS485_FLAG_CMD (1<<4)
#define CACHE_PERIOD 500
Functions
void debug_log (char *format,...)
int musb_init (int index, int *hr, int *hw)
void musb_close (int fdr, int fdw)
size_t strlcpy (char *dst, const char *src, size_t size)
size_t strlcat (char *dst, const char *src, size_t size)
unsigned char crc8 (unsigned char *data, int len)
int strieq (const char *str1, const char *str2)
int mscb_lock (int fd)
int mscb_release (int fd)
void pp_wcontrol (int fd, int signal, int flag)
int pp_rstatus (int fd, int signal)
void pp_setdir (int fd, unsigned int r)
void pp_wdata (int fd, unsigned int data)
unsigned char pp_rdata (int fd)
int msend_usb (int fd, void *buf, int size)
int mrecv_usb (int fd, void *buf, int size)
int mscb_out (int index, unsigned char *buffer, int len, int flags)
int mscb_in1 (int fd, unsigned char *c, int timeout)
int mscb_in (int index, char *buffer, int size, int timeout)
int lpt_init (char *device, int index)
int lpt_close (int fd)
void mscb_get_version (char *lib_version, char *prot_version)
int mrpc_connected (int fd)
int mscb_init (char *device, int bufsize, int debug)
int mscb_exit (int fd)
void mscb_cleanup (int sock)
void mscb_get_device (int fd, char *device, int bufsize)
void mscb_check (char *device, int size)
int mscb_addr (int fd, int cmd, int adr, int retry, int lock)
int mscb_reboot (int fd, int adr)
int mscb_reset (int fd)
int mscb_ping (int fd, int adr)
int mscb_info (int fd, int adr, MSCB_INFO *info)
int mscb_info_variable (int fd, int adr, int index, MSCB_INFO_VAR *info)
int mscb_set_addr (int fd, int adr, int node, int group)
int mscb_set_name (int fd, int adr, char *name)
int mscb_write_group (int fd, int adr, unsigned char index, void *data, int size)
int mscb_write (int fd, int adr, unsigned char index, void *data, int size)
int mscb_write_block (int fd, int adr, unsigned char index, void *data, int size)
int mscb_flash (int fd, int adr)
int mscb_upload (int fd, int adr, char *buffer, int size, int debug)
int mscb_read (int fd, int adr, unsigned char index, void *data, int *size)
int mscb_read_range (int fd, int adr, unsigned char index1, unsigned char index2, void *data, int *size)
int mscb_user (int fd, int adr, void *param, int size, void *result, int *rsize)
int mscb_echo (int fd, int adr, unsigned char d1, unsigned char *d2)
unsigned long millitime ()
int mscb_link (int fd, int adr, unsigned char index, void *data, int size)
int mscb_select_device (char *device, int size, int select)
Variables
MSCB_FD mscb_fd [MSCB_MAX_FD]
int _debug_flag
CACHE_ENTRY * cache
int n_cache
unsigned char crc8_data []
Define Documentation
#define CACHE_PERIOD 500
Definition at line 387 of file mscb.c.
Referenced by mscb_link().
#define LPT_ACK 2
Definition at line 320 of file mscb.c.
Referenced by mscb_check(), mscb_in1(), pp_wcontrol(), putchar(), and user_init().
#define LPT_BIT9 4
Definition at line 322 of file mscb.c.
Referenced by check_lpt(), mscb_check(), mscb_out(), pp_wcontrol(), and setup().
#define LPT_BUSY 6
Definition at line 325 of file mscb.c.
Referenced by check_lpt(), getchar_nowait(), lpt_init(), main(), mscb_check(), mscb_out(), pp_rstatus(), setup(), and user_init().
#define LPT_DATAREADY 7
Definition at line 326 of file mscb.c.
Referenced by mscb_check(), mscb_in1(), and pp_rstatus().
#define LPT_READMODE 5
Definition at line 323 of file mscb.c.
Referenced by pp_setdir(), and pp_wcontrol().
#define LPT_RESET 3
Definition at line 321 of file mscb.c.
Referenced by lpt_init(), mscb_check(), mscb_reset(), and pp_wcontrol().
#define LPT_STROBE 1
Definition at line 319 of file mscb.c.
Referenced by lpt_init(), mscb_check(), mscb_out(), pp_wcontrol(), putchar(), and user_init().
#define MSCB_LIBRARY_VERSION "1.7.5"
Definition at line 236 of file mscb.c.
Referenced by mscb_get_version().
#define MSCB_PROTOCOL_VERSION "1.7"
Definition at line 237 of file mscb.c.
Referenced by mscb_get_version().
#define RS485_FLAG_BIT9 (1<<0)
Definition at line 359 of file mscb.c.
#define RS485_FLAG_CMD (1<<4)
Definition at line 363 of file mscb.c.
#define RS485_FLAG_LONG_TO (1<<3)
Definition at line 362 of file mscb.c.
#define RS485_FLAG_NO_ACK (1<<1)
Definition at line 360 of file mscb.c.
#define RS485_FLAG_SHORT_TO (1<<2)
Definition at line 361 of file mscb.c.
#define TIMEOUT_OUT 1000
Definition at line 353 of file mscb.c.
Referenced by mscb_out().
Function Documentation
unsigned char crc8 (unsigned char * data, int len)
Definition at line 511 of file mscb.c.
References crc8_data, i, and index.
Referenced by interprete(), mscb_addr(), mscb_echo(), mscb_flash(), mscb_info(), mscb_info_variable(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_group(), and serial_int().
         : crc8
  Purpose: Calculate 8-bit cyclic redundancy checksum
  Input:
    unsigned char *data     data buffer
    int len                 data length in bytes
  Function value:
    unsighend char          CRC-8 code
\********************************************************************/
{
   int i;
   unsigned char crc8_code, index;
   crc8_code = 0;
   for (i = 0; i < len; i++) {
      index = data[i] ^ crc8_code;
      crc8_code = crc8_data[index];
   }
   return crc8_code;
}
void debug_log (char * format, ...)
Definition at line 298 of file rpc.c.
References _debug_flag, and write.
Referenced by mrpc_call(), mscb_init(), and mscb_link().
{
   int fh;
   char str[256];
   va_list argptr;
   if (!_debug_flag)
      return;
   va_start(argptr, format);
   vsprintf(str, (char *) format, argptr);
   va_end(argptr);
   /* if debug flag equals 2, write to stdout */
   if (_debug_flag == 2)
      write(fileno(stdout), str, strlen(str));
   else {
      /* else write to file */
      fh = open("mscb_debug.log", O_CREAT | O_WRONLY | O_APPEND, 0644);
      if (fh < 0)
         return;
      write(fh, str, strlen(str));
      close(fh);
   }
}
int lpt_close (int fd)
Definition at line 1247 of file mscb.c.
References buffer, MSCB_SUCCESS, and size.
Referenced by mscb_select_device().
         : lpt_close
  Purpose: Close handle to MSCB submaster
  Input:
    int  index              Index to mscb_fd[] array
  Function value:
    MSCB_SUCCES             Successful completion
\********************************************************************/
{
#ifdef _MSC_VER
   /* under NT, user directio driver */
   OSVERSIONINFO vi;
   DWORD buffer[4];
   DWORD size;
   HANDLE hdio;
   buffer[0] = 7;               /* lock port */
   buffer[1] = fd;
   buffer[2] = buffer[1] + 4;
   buffer[3] = 0;
   vi.dwOSVersionInfoSize = sizeof(OSVERSIONINFO);
   GetVersionEx(&vi);
   /* use DirectIO driver under NT to gain port access */
   if (vi.dwPlatformId == VER_PLATFORM_WIN32_NT) {
      hdio = CreateFile("\\\\.\\directio", GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, 0, NULL);
      if (hdio == INVALID_HANDLE_VALUE) {
#ifndef _USRDLL
         printf("mscb.c: Cannot access parallel port (No DirectIO driver installed)\n");
#endif
         return -1;
      }
      if (!DeviceIoControl(hdio, (DWORD) 0x9c406000, &buffer, sizeof(buffer), NULL, 0, &size, NULL))
         return -1;
   }
#elif defined(OS_LINUX)
   close(fd);
#endif
   return MSCB_SUCCESS;
}
int lpt_init (char * device, int index)
Definition at line 1112 of file mscb.c.
References buffer, c, MSCB_FD::fd, i, LPT_BUSY, LPT_RESET, LPT_STROBE, mscb_in1(), mscb_lock(), mscb_release(), MSCB_SUCCESS, pp_rstatus(), pp_setdir(), pp_wcontrol(), size, and status.
Referenced by mscb_init(), and mscb_select_device().
         : lpt_init
  Purpose: Initialize MSCB submaster on parallel port
  Input:
    char *device            Device name "lptx"/"/dev/parportx"
    int  index              Index to mscb_fd[] array
  Output:
    int  mscb_fd[index].fd  File descriptor for device or
                            DirectIO address
  Function value:
    0                       Successful completion
    -1                      Invalid parameter or other error
    -2                      Submaster does not respond
    -3                      No DirectIO driver
    -4                      MSCB system locked by other user
\********************************************************************/
{
   int status;
   char c;
#ifdef _MSC_VER
   /* under NT, user directio driver */
   OSVERSIONINFO vi;
   DWORD buffer[4];
   DWORD size;
   HANDLE hdio;
   /* derive base address from device name */
   if (atoi(device + 3) == 1)
      mscb_fd[index].fd = 0x378;
   else if (atoi(device + 3) == 2)
      mscb_fd[index].fd = 0x278;
   else
      return -1;
   buffer[0] = 6;               /* give IO */
   buffer[1] = mscb_fd[index].fd;
   buffer[2] = buffer[1] + 4;
   buffer[3] = 0;
   vi.dwOSVersionInfoSize = sizeof(OSVERSIONINFO);
   GetVersionEx(&vi);
   /* use DirectIO driver under NT to gain port access */
   if (vi.dwPlatformId == VER_PLATFORM_WIN32_NT) {
      hdio = CreateFile("\\\\.\\directio", GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, 0, NULL);
      if (hdio == INVALID_HANDLE_VALUE) {
         //printf("mscb.c: Cannot access parallel port (No DirectIO driver installed)\n");
         return -3;
      }
      if (!DeviceIoControl(hdio, (DWORD) 0x9c406000, &buffer, sizeof(buffer), NULL, 0, &size, NULL))
         return -1;
   }
#elif defined(OS_LINUX)
   int i;
   mscb_fd[index].fd = open(device, O_RDWR);
   if (mscb_fd[index].fd < 0) {
#ifndef _USRDLL
      perror("open");
      printf("Please make sure that device \"%s\" is world readable/writable\n", device);
#endif
      return -1;
   }
   if (ioctl(mscb_fd[index].fd, PPCLAIM)) {
#ifndef _USRDLL
      perror("PPCLAIM");
      printf("Please load driver via \"modprobe parport_pc\" as root\n");
#endif
      return -1;
   }
   if (ioctl(mscb_fd[index].fd, PPRELEASE)) {
#ifndef _USRDLL
      perror("PPRELEASE");
#endif
      return -1;
   }
   i = IEEE1284_MODE_BYTE;
   if (ioctl(mscb_fd[index].fd, PPSETMODE, &i)) {
#ifndef _USRDLL
      perror("PPSETMODE");
#endif
      return -1;
   }
#endif
   status = mscb_lock(index + 1);
   if (status != MSCB_SUCCESS)
      return -4;
   /* set initial state of handshake lines */
   pp_wcontrol(index + 1, LPT_RESET, 0);
   pp_wcontrol(index + 1, LPT_STROBE, 0);
   /* switch to output mode */
   pp_setdir(index + 1, 0);
   /* wait for submaster irritated by a stuck LPT_STROBE */
   Sleep(100);
   /* check if SM alive */
   if (pp_rstatus(index + 1, LPT_BUSY)) {
      //printf("mscb.c: No SM present on parallel port\n");
      mscb_release(index + 1);
      return -2;
   }
   /* empty RBuffer of SM */
   do {
      status = mscb_in1(index + 1, &c, 1000);
      if (status == MSCB_SUCCESS)
         printf("%02X ", c);
   } while (status == MSCB_SUCCESS);
   mscb_release(index + 1);
   return 0;
}
unsigned long millitime ()
Definition at line 3317 of file mscb.c.
Referenced by mscb_link().
{
#ifdef _MSC_VER
   return (int) GetTickCount();
#else
   {
      struct timeval tv;
      gettimeofday(&tv, NULL);
      return tv.tv_sec * 1000 + tv.tv_usec / 1000;
   }
#endif
}
int mrecv_usb (int fd, void * buf, int size)
Definition at line 747 of file mscb.c.
References dev, FALSE, i, and status.
Referenced by mscb_in().
{
   int n_read;
#if defined(_MSC_VER)
   OVERLAPPED overlapped;
   int status;
   memset(&overlapped, 0, sizeof(overlapped));
   overlapped.hEvent = CreateEvent(NULL, FALSE, FALSE, NULL);
   n_read = 0;
   status = ReadFile((HANDLE) fd, buf, size, &n_read, &overlapped);
   if (!status) {
      status = GetLastError();
      if (status != ERROR_IO_PENDING)
         return 0;
      /* wait for completion, 1s timeout */
      status = WaitForSingleObject(overlapped.hEvent, 1000);
      if (status == WAIT_TIMEOUT)
         CancelIo((HANDLE) fd);
      else
         GetOverlappedResult((HANDLE) fd, &overlapped, &n_read, FALSE);
   }
   CloseHandle(overlapped.hEvent);
#elif defined(HAVE_LIBUSB)
   usb_dev_handle *dev;
   int i;
   dev = (usb_dev_handle *) fd;
   for (i = 0; i < 10; i++) {
      n_read = usb_bulk_read(dev, 1, buf, size, 1000);
      //printf("##mrecv_usb(%X): %d\n", dev, n_read);
      if (n_read < 0)
         usleep(10000);
      else
         break;
   }
#elif defined(OS_DARWIN)
   IOReturn status;
   IOUSBInterfaceInterface** device = (IOUSBInterfaceInterface**)fd;
   n_read = size;
   status = (*device)->ReadPipe(device,1,buf,&n_read);
   if (status != kIOReturnSuccess) {
      printf("mrecv_usb: size %d, read %d, ReadPipe() status %d 0x%x\n",size,n_read,status,status);
      return -1;
   }
#endif
   return n_read;
}
int mrpc_connected (int fd)
Definition at line 1586 of file mscb.c.
References MSCB_TYPE_RPC, and MSCB_FD::type.
Referenced by mscb_addr(), mscb_echo(), mscb_exit(), mscb_flash(), mscb_get_device(), mscb_info(), mscb_info_variable(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_reset(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), and mscb_write_group().
{
   return mscb_fd[fd - 1].type == MSCB_TYPE_RPC;
}
int mscb_addr (int fd, int cmd, int adr, int retry, int lock)
Definition at line 1909 of file mscb.c.
References buf, crc8(), i, MCMD_ACK, MCMD_ADDR_GRP16, MCMD_ADDR_GRP8, MCMD_ADDR_NODE16, MCMD_ADDR_NODE8, MCMD_PING16, MCMD_PING8, mrpc_call(), mrpc_connected(), mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUBM_ERROR, MSCB_SUCCESS, MSCB_TIMEOUT, n, RPC_MSCB_ADDR, RS485_FLAG_BIT9, RS485_FLAG_NO_ACK, RS485_FLAG_SHORT_TO, and type.
Referenced by cmd_loop(), mscb_echo(), mscb_flash(), mscb_info(), mscb_info_variable(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), mscb_write_group(), and server_execute().
         : mscb_addr
  Purpose: Address node or nodes, only used internall from read and
           write routines. A MSCB lock has to be obtained outside
           of this routine!
  Input:
    int fd                  File descriptor for connection
    int cmd                 Addressing mode, one of
                              MCMD_ADDR_BC
                              MCMD_ADDR_NODE8
                              MCMD_ADDR_GRP8
                              MCMD_PING8
                              MCMD_ADDR_NODE16
                              MCMD_ADDR_GRP16
                              MCMD_PING16
    int adr                 Node or group address
    int retry               Number of retries
    int lock                Lock MSCB if TRUE
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving ping acknowledge
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   unsigned char buf[10];
   int i, n, status;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_ADDR, mscb_fd[fd - 1].remote_fd, cmd, adr, retry, lock);
   if (lock) {
      if (mscb_lock(fd) != MSCB_SUCCESS)
         return MSCB_MUTEX;
   }
   for (n = 0; n < retry; n++) {
      buf[0] = cmd;
      if (cmd == MCMD_ADDR_NODE8 || cmd == MCMD_ADDR_GRP8) {
         buf[1] = (unsigned char) adr;
         buf[2] = crc8(buf, 2);
         status = mscb_out(fd, buf, 3, RS485_FLAG_BIT9 | RS485_FLAG_SHORT_TO | RS485_FLAG_NO_ACK);
      } else if (cmd == MCMD_PING8) {
         buf[1] = (unsigned char) adr;
         buf[2] = crc8(buf, 2);
         status = mscb_out(fd, buf, 3, RS485_FLAG_BIT9 | RS485_FLAG_SHORT_TO);
      } else if (cmd == MCMD_ADDR_NODE16 || cmd == MCMD_ADDR_GRP16) {
         buf[1] = (unsigned char) (adr >> 8);
         buf[2] = (unsigned char) (adr & 0xFF);
         buf[3] = crc8(buf, 3);
         status = mscb_out(fd, buf, 4, RS485_FLAG_BIT9 | RS485_FLAG_SHORT_TO | RS485_FLAG_NO_ACK);
      } else if (cmd == MCMD_PING16) {
         buf[1] = (unsigned char) (adr >> 8);
         buf[2] = (unsigned char) (adr & 0xFF);
         buf[3] = crc8(buf, 3);
         status = mscb_out(fd, buf, 4, RS485_FLAG_BIT9 | RS485_FLAG_SHORT_TO);
      } else {
         buf[1] = crc8(buf, 1);
         status = mscb_out(fd, buf, 2, RS485_FLAG_BIT9 | RS485_FLAG_SHORT_TO | RS485_FLAG_NO_ACK);
      }
      if (status != MSCB_SUCCESS) {
         if (lock)
            mscb_release(fd);
         return MSCB_SUBM_ERROR;
      }
      if (cmd == MCMD_PING8 || cmd == MCMD_PING16) {
         /* read back ping reply, 4ms timeout (for USB!) */
         i = mscb_in(fd, buf, 1, 4000);
         if (i == MSCB_SUCCESS && buf[0] == MCMD_ACK) {
            if (lock)
               mscb_release(fd);
            return MSCB_SUCCESS;
         }
         if (retry > 1) {
            /* send 0's to overflow partially filled node receive buffer */
            memset(buf, 0, sizeof(buf));
            mscb_out(fd, buf, 10, RS485_FLAG_BIT9 | RS485_FLAG_NO_ACK);
            /* wait some time */
            Sleep(10);
         }
         /* try again.... */
      } else {
         if (lock)
            mscb_release(fd);
         return MSCB_SUCCESS;
      }
   }
   if (lock)
      mscb_release(fd);
   return MSCB_TIMEOUT;
}
void mscb_check (char * device, int size)
Definition at line 1833 of file mscb.c.
References d, i, LPT_ACK, LPT_BIT9, LPT_BUSY, LPT_DATAREADY, LPT_RESET, LPT_STROBE, mscb_init(), mscb_lock(), mscb_release(), pp_rdata(), pp_rstatus(), pp_wcontrol(), and pp_wdata().
Referenced by main().
         : mscb_check
  Purpose: Check IO pins of port
  Input:
    char *device            Under NT: lpt1 or lpt2
                            Under Linux: /dev/parport0 or /dev/parport1
  Function value:
    int fd                  device descriptor for connection, -1 if
                            error
\********************************************************************/
{
   int i, fd, d;
   mscb_init(device, size, 0);
   fd = 1;
   mscb_lock(fd);
   printf("Toggling %s output pins, hit ENTER to stop.\n", device);
   printf("GND = 19-25, toggling 2-9, 1, 14, 16 and 17\n\n");
   do {
      printf("\r11111111 1111");
      fflush(stdout);
      pp_wdata(fd, 0xFF);
      pp_wcontrol(fd, LPT_STROBE, 1);
      pp_wcontrol(fd, LPT_ACK, 1);
      pp_wcontrol(fd, LPT_RESET, 1);
      pp_wcontrol(fd, LPT_BIT9, 1);
      Sleep(1000);
      printf("\r00000000 0000");
      fflush(stdout);
      pp_wdata(fd, 0);
      pp_wcontrol(fd, LPT_STROBE, 0);
      pp_wcontrol(fd, LPT_ACK, 0);
      pp_wcontrol(fd, LPT_RESET, 0);
      pp_wcontrol(fd, LPT_BIT9, 0);
      Sleep(1000);
   } while (!kbhit());
   while (kbhit())
      getch();
   printf("\n\n\nInput display, hit ENTER to stop.\n");
   printf("Pins 2-9, 10 and 11\n\n");
   do {
      d = pp_rdata(fd);
      for (i = 0; i < 8; i++) {
         printf("%d", (d & 1) > 0);
         d >>= 1;
      }
      printf(" %d%d\r", !pp_rstatus(fd, LPT_DATAREADY), pp_rstatus(fd, LPT_BUSY));
      fflush(stdout);
      Sleep(100);
   } while (!kbhit());
   while (kbhit())
      getch();
   mscb_release(fd);
}
void mscb_cleanup (int sock)
Definition at line 1788 of file mscb.c.
References i, and MSCB_MAX_FD.
Referenced by mrpc_server_loop().
{
   int i;
   for (i = 0; i < MSCB_MAX_FD; i++)
      if (mscb_fd[i].fd && mscb_fd[i].remote_fd == sock)
         memset(&mscb_fd[i], 0, sizeof(MSCB_FD));
}
int mscb_echo (int fd, int adr, unsigned char d1, unsigned char * d2)
Definition at line 3243 of file mscb.c.
References buf, crc8(), MCMD_ECHO, MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, n, RPC_MSCB_ECHO, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_echo
  Purpose: Send byte and receive echo, useful for testing
  Input:
    int  fd                 File descriptor for connection
    int  adr                Node address
    unsigned char d1        Byte to send
  Output:
    unsigned char *d2       Received byte
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_CRC_ERROR          CRC error
    MSCB_MUTEX              Cannot obtain mutex for mscb
    MSCB_FORMAT_ERROR       "size" parameter too large
\********************************************************************/
{
   int n, status;
   unsigned char buf[80];
   *d2 = 0xFF;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_ECHO, mscb_fd[fd - 1].remote_fd, adr, d1, d2);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   if (adr) {
      status = mscb_addr(fd, MCMD_PING16, adr, 1, 0);
      if (status != MSCB_SUCCESS) {
         mscb_release(fd);
         return status;
      }
   }
   buf[0] = MCMD_ECHO;
   buf[1] = d1;
   /* add CRC code and send data */
   buf[2] = crc8(buf, 2);
   status = mscb_out(fd, buf, 3, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   /* read result */
   n = mscb_in(fd, buf, sizeof(buf), 10000);
   mscb_release(fd);
   if (n < 0)
      return MSCB_TIMEOUT;
   *d2 = buf[1];
   if (buf[n - 1] != crc8(buf, n - 1))
      return MSCB_CRC_ERROR;
   return MSCB_SUCCESS;
}
int mscb_exit (int fd)
Definition at line 1750 of file mscb.c.
References mrpc_call(), mrpc_connected(), mrpc_disconnect(), MSCB_INVAL_PARAM, MSCB_MAX_FD, MSCB_SUCCESS, MSCB_TYPE_USB, musb_close(), RPC_MSCB_EXIT, and type.
Referenced by main(), mscbdev_exit(), and server_execute().
         : mscb_exit
  Purpose: Close a MSCB interface
  Input:
    int  fd                 file descriptor for connection
  Function value:
    MSCB_SUCCESS            Successful completion
\********************************************************************/
{
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd)) {
      mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_EXIT, mscb_fd[fd - 1].remote_fd);
      mrpc_disconnect(mscb_fd[fd - 1].fd);
   }
   if (mscb_fd[fd - 1].type == MSCB_TYPE_USB)
      musb_close(mscb_fd[fd - 1].hr, mscb_fd[fd - 1].hw);
   /* outcommented, other client (like Labview) could still use LPT ...
   if (mscb_fd[fd - 1].type == MSCB_TYPE_LPT)
      lpt_close(mscb_fd[fd - 1].fd);
   */
   memset(&mscb_fd[fd - 1], 0, sizeof(MSCB_FD));
   return MSCB_SUCCESS;
}
int mscb_flash (int fd, int adr)
Definition at line 2626 of file mscb.c.
References buf, crc8(), i, MCMD_ACK, MCMD_FLASH, MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, RPC_MSCB_FLASH, RS485_FLAG_LONG_TO, and type.
Referenced by cmd_loop(), main(), and server_execute().
         : mscb_flash
  Purpose: Flash node variables to EEPROM
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
                            and dword
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, status;
   unsigned char buf[10], crc, ack[2];
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_FLASH, mscb_fd[fd - 1].remote_fd, adr);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_FLASH;
   crc = crc8(buf, 1);
   buf[1] = crc;
   mscb_out(fd, buf, 2, RS485_FLAG_LONG_TO);
   /* read acknowledge, 100ms timeout */
   i = mscb_in(fd, ack, 2, 100000);
   mscb_release(fd);
   if (i < 2)
      return MSCB_TIMEOUT;
   if (ack[0] != MCMD_ACK || ack[1] != crc)
      return MSCB_CRC_ERROR;
   return MSCB_SUCCESS;
}
void mscb_get_device (int fd, char * device, int bufsize)
Definition at line 1800 of file mscb.c.
References mrpc_call(), mrpc_connected(), MSCB_MAX_FD, RPC_MSCB_GET_DEVICE, and type.
         : mscb_get_device
  Purpose: Return device name for fd
  Input:
    int fd                  File descriptor obtained wiv mscb_init()
    int bufsize             Size of device string
    char *device            device name, "" if invalid fd
\********************************************************************/
{
   char str[256];
   if (!device)
      return;
   *device = 0;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return;
   if (mrpc_connected(fd)) {
      mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_GET_DEVICE,
                mscb_fd[fd - 1].remote_fd, str, sizeof(str));
   }
   strcpy(device, mscb_fd[fd-1].device);
}
void mscb_get_version (char * lib_version, char * prot_version)
Definition at line 1578 of file mscb.c.
References MSCB_LIBRARY_VERSION, and MSCB_PROTOCOL_VERSION.
Referenced by cmd_loop().
{
   strcpy(lib_version, MSCB_LIBRARY_VERSION);
   strcpy(prot_version, MSCB_PROTOCOL_VERSION);
}
int mscb_in (int index, char * buffer, int size, int timeout)
Definition at line 1027 of file mscb.c.
References i, MCMD_ACK, mrecv_usb(), mscb_in1(), MSCB_INVAL_PARAM, MSCB_MAX_FD, MSCB_SUCCESS, MSCB_TYPE_USB, n, status, and type.
Referenced by mscb_addr(), mscb_echo(), mscb_flash(), mscb_info(), mscb_info_variable(), mscb_init(), mscb_read(), mscb_read_range(), mscb_upload(), mscb_user(), and mscb_write().
         : mscb_in
  Purpose: Read number of bytes from SM via parallel port
  Input:
    int  index              index to file descriptor table
    int  size               size of data buffer
    int  timeout            timeout in microseconds
  Output:
    char *buffer            data buffer
  Function value:
    int                     number of received bytes, -1 for timeout
\********************************************************************/
{
   int i, n, len, status;
   n = 0;
   len = -1;
   if (index > MSCB_MAX_FD || index < 1 || !mscb_fd[index - 1].type)
      return MSCB_INVAL_PARAM;
   /*---- USB code ----*/
   if (mscb_fd[index - 1].type == MSCB_TYPE_USB) {
      /* receive result on IN pipe */
      n = mrecv_usb(mscb_fd[index - 1].hr, buffer, size);
   } else {
   /*---- LPT code ----*/
      /* wait for MCMD_ACK command */
      do {
         status = mscb_in1(index, buffer, timeout);
         /* only read single byte */
         if (size == 1)
            return status;
         /* return in case of timeout */
         if (status != MSCB_SUCCESS)
            return -1;
         /* check for Acknowledge */
         if ((buffer[0] & 0xF8) == MCMD_ACK) {
            len = buffer[n++] & 0x7;
            /* check for variable length data block */
            if (len == 7) {
               status = mscb_in1(index, buffer + n, timeout);
               /* return in case of timeout */
               if (status != MSCB_SUCCESS)
                  return -1;
               len = buffer[n++];
            }
         }
      } while (len == -1);
      /* receive remaining bytes and CRC code */
      for (i = 0; i < len + 1; i++) {
         status = mscb_in1(index, buffer + n + i, timeout);
         /* return in case of timeout */
         if (status != MSCB_SUCCESS)
            return -1;
      }
      n += i;
   }
   return n;
}
int mscb_in1 (int fd, unsigned char * c, int timeout)
Definition at line 945 of file mscb.c.
References i, LPT_ACK, LPT_DATAREADY, MSCB_SUCCESS, MSCB_TIMEOUT, pp_rdata(), pp_rstatus(), pp_setdir(), and pp_wcontrol().
Referenced by lpt_init(), and mscb_in().
         : mscb_in1
  Purpose: Read one byte from SM via parallel port
  Input:
    int  fd                 file descriptor for connection
    int  timeout            timeout in microseconds
  Output:
    char *c                 data bytes
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout
\********************************************************************/
{
   int i;
   /* wait for DATAREADY, each port access takes roughly 1us */
   timeout = (int) (timeout / 1.3);
   for (i = 0; i < timeout; i++) {
      if (pp_rstatus(fd, LPT_DATAREADY))
         break;
   }
   if (i == timeout)
      return MSCB_TIMEOUT;
   /* switch to input mode */
   pp_setdir(fd, 1);
   /* signal switch to input */
   pp_wcontrol(fd, LPT_ACK, 1);
   /* wait for data ready */
   for (i = 0; i < 1000; i++) {
      if (!pp_rstatus(fd, LPT_DATAREADY))
         break;
   }
   /* read data */
   *c = pp_rdata(fd);
   /* signal data read */
   pp_wcontrol(fd, LPT_ACK, 0);
   /* wait for mode switch */
   for (i = 0; i < 1000; i++) {
      if (pp_rstatus(fd, LPT_DATAREADY))
         break;
   }
   /* switch to output mode */
   pp_setdir(fd, 0);
   /* indicate mode switch */
   pp_wcontrol(fd, LPT_ACK, 1);
   /* wait for end of cycle */
   for (i = 0; i < 1000; i++) {
      if (!pp_rstatus(fd, LPT_DATAREADY))
         break;
   }
   /* remove acknowlege */
   pp_wcontrol(fd, LPT_ACK, 0);
   if (i == 1000)
      return MSCB_TIMEOUT;
   for (i = 0; i < 50; i++)
      pp_rdata(fd);
   return MSCB_SUCCESS;
}
int mscb_info (int fd, int adr, MSCB_INFO * info)
Definition at line 2156 of file mscb.c.
References buf, crc8(), MSCB_INFO::group_address, i, MCMD_GET_INFO, MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, MSCB_INFO::node_address, RPC_MSCB_INFO, RS485_FLAG_LONG_TO, type, MSCB_INFO::watchdog_resets, and WORD_SWAP.
Referenced by cmd_loop(), and server_execute().
         : mscb_info
  Purpose: Retrieve info on addressd node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
  Output:
    MSCB_INFO *info         Info structure defined in mscb.h
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_CRC_ERROR          CRC error
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, status;
   unsigned char buf[256];
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_INFO, mscb_fd[fd - 1].remote_fd, adr, info);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_GET_INFO;
   buf[1] = crc8(buf, 1);
   mscb_out(fd, buf, 2, RS485_FLAG_LONG_TO);
   i = mscb_in(fd, buf, sizeof(buf), 10000);
   mscb_release(fd);
   if (i < (int) sizeof(MSCB_INFO) + 2)
      return MSCB_TIMEOUT;
   memcpy(info, buf + 2, sizeof(MSCB_INFO));
   /* do CRC check */
   if (crc8(buf, sizeof(MSCB_INFO) + 2) != buf[sizeof(MSCB_INFO) + 2])
      return MSCB_CRC_ERROR;
   WORD_SWAP(&info->node_address);
   WORD_SWAP(&info->group_address);
   WORD_SWAP(&info->watchdog_resets);
   return MSCB_SUCCESS;
}
int mscb_info_variable (int fd, int adr, int index, MSCB_INFO_VAR * info)
Definition at line 2221 of file mscb.c.
References buf, crc8(), i, MCMD_GET_INFO, MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, RPC_MSCB_INFO_VARIABLE, RS485_FLAG_LONG_TO, and type.
Referenced by addr_changed(), cmd_loop(), main(), mscb_link(), mscbdev_get_default_name(), and server_execute().
         : mscb_info_variable
  Purpose: Retrieve info on a specific node variable
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    int index               Variable index 0..255
  Output:
    MSCB_INFO_VAR *info     Info structure defined in mscb.h
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_CRC_ERROR          CRC error
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, status;
   unsigned char buf[80];
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_INFO_VARIABLE,
                       mscb_fd[fd - 1].remote_fd, adr, index, info);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_GET_INFO + 1;
   buf[1] = index;
   buf[2] = crc8(buf, 2);
   mscb_out(fd, buf, 3, RS485_FLAG_LONG_TO);
   i = mscb_in(fd, buf, sizeof(buf), 10000);
   mscb_release(fd);
   if (i < (int) sizeof(MSCB_INFO_VAR) + 3)
      return MSCB_TIMEOUT;
   memcpy(info, buf + 2, sizeof(MSCB_INFO_VAR));
   /* do CRC check */
   if (crc8(buf, sizeof(MSCB_INFO_VAR) + 2) != buf[sizeof(MSCB_INFO_VAR) + 2])
      return MSCB_CRC_ERROR;
   return MSCB_SUCCESS;
}
int mscb_init (char * device, int bufsize, int debug)
Definition at line 1593 of file mscb.c.
References _debug_flag, buf, data, debug_log(), MSCB_FD::fd, i, lpt_init(), MCMD_ACK, MCMD_ECHO, mrpc_call(), mrpc_connect(), mrpc_disconnect(), mscb_in(), mscb_lock(), MSCB_MAX_FD, mscb_out(), mscb_release(), mscb_select_device(), MSCB_TYPE_LPT, MSCB_TYPE_RPC, MSCB_TYPE_USB, musb_init(), n, n_cache, MSCB_FD::remote_fd, RPC_MSCB_INIT, RS485_FLAG_CMD, strieq(), strlcpy(), type, and MSCB_FD::type.
Referenced by main(), mscb_check(), mscbdev_init(), and server_execute().
         : mscb_init
  Purpose: Initialize and open MSCB
  Input:
    char *device            Under NT: lpt1 or lpt2
                            Under Linux: /dev/parport0 or /dev/parport1
                            "<host>:device" for RPC connection
                            usbx for USB connection
                            If device equals "", the function
                            mscb_select_device is called which selects
                            the first available device or asks the user
                            which one to use.
    int bufsize             Size of "device" string, in case no device
                            is specified from the caller and this function
                            returns the chosen device
    int debug               Debug flag. If "1" debugging information is
                            written to "mscb_debug.log" in the current
                            directory. If "-1", do not ask for device
                            (useb by LabView DLL)
  Function value:
    int fd                  device descriptor for connection, -1 if
                            error
\********************************************************************/
{
   int index, i, n;
   int status;
   char host[256], port[256], dev3[256], buf[10], remote_device[256];
   /* search for new file descriptor */
   for (index = 0; index < MSCB_MAX_FD; index++)
      if (mscb_fd[index].fd == 0)
         break;
   if (index == MSCB_MAX_FD)
      return -1;
   /* set global debug flag */
   _debug_flag = (debug == 1);
   debug_log("mscb_init( %s %d %d * %d)\n", device, bufsize, debug);
   /* clear cache */
   for (i = 0; i < n_cache; i++)
      free(cache[i].data);
   free(cache);
   n_cache = 0;
   if (!device[0]) {
      if (debug == -1)
         mscb_select_device(device, bufsize, 0); /* for LabView */
      else
         mscb_select_device(device, bufsize, 1); /* interactively ask for device */
   }
   /* check for RPC connection */
   if (strchr(device, ':')) {
      strlcpy(mscb_fd[index].device, device, sizeof(mscb_fd[index].device));
      mscb_fd[index].type = MSCB_TYPE_RPC;
      strcpy(remote_device, strchr(device, ':') + 1);
      strcpy(host, device);
      *strchr(host, ':') = 0;
      mscb_fd[index].fd = mrpc_connect(host);
      if (mscb_fd[index].fd < 0) {
         mscb_fd[index].fd = 0;
         return -1;
      }
      mscb_fd[index].remote_fd = mrpc_call(mscb_fd[index].fd, RPC_MSCB_INIT, remote_device, bufsize, debug);
      if (mscb_fd[index].remote_fd < 0) {
         mrpc_disconnect(mscb_fd[index].fd);
         mscb_fd[index].fd = 0;
         return -1;
      }
      sprintf(device, "%s:%s", host, remote_device);
      return index + 1;
   }
   /* check which device type */
   strcpy(dev3, device);
   dev3[3] = 0;
   strcpy(mscb_fd[index].device, device);
   mscb_fd[index].type = 0;
   /* LPT port with direct address */
   if (device[1] == 'x') {
      mscb_fd[index].type = MSCB_TYPE_LPT;
      sscanf(port + 2, "%x", &mscb_fd[index].fd);
   }
   /* LPTx */
   if (strieq(dev3, "LPT")) {
      mscb_fd[index].type = MSCB_TYPE_LPT;
   }
   /* /dev/parportx */
   if (strstr(device, "parport")) {
      mscb_fd[index].type = MSCB_TYPE_LPT;
   }
   /* USBx */
   if (strieq(dev3, "usb"))
      mscb_fd[index].type = MSCB_TYPE_USB;
   if (mscb_fd[index].type == 0)
      return -1;
   /*---- initialize submaster ----*/
   if (mscb_fd[index].type == MSCB_TYPE_LPT) {
      status = lpt_init(device, index);
      if (status < 0)
         return status;
   }
   if (mscb_fd[index].type == MSCB_TYPE_USB) {
      status = musb_init(atoi(device + 3), &mscb_fd[index].hr, &mscb_fd[index].hw);
      if (status < 0)
         return status;
      /* linux needs some time to start-up ...??? */
      for (i = 0; i < 10; i++) {
         mscb_lock(index + 1);
         /* check if submaster alive */
         buf[0] = MCMD_ECHO;
         mscb_out(index + 1, buf, 1, RS485_FLAG_CMD);
         n = mscb_in(index + 1, buf, 2, 10000);
         mscb_release(index + 1);
         if (n == 2 && buf[0] == MCMD_ACK)
            break;
      }
      if (n != 2 || buf[0] != MCMD_ACK)
         return -4;
   }
   return index + 1;
}
int mscb_link (int fd, int adr, unsigned char index, void * data, int size)
Definition at line 3334 of file mscb.c.
References CACHE_ENTRY::adr, CACHE_PERIOD, CACHE_ENTRY::data, debug_log(), CACHE_ENTRY::fd, i, CACHE_ENTRY::index, CACHE_ENTRY::last, last, millitime(), mscb_info_variable(), MSCB_NO_MEM, mscb_read(), MSCB_SUCCESS, mscb_write(), n_cache, CACHE_ENTRY::size, and MSCB_INFO_VAR::width.
Referenced by cmd_loop().
         : mscb_link
  Purpose: Used by LabView to link controls to MSCB variables
  Input:
    int  fd                 File descriptor for connection
    int  adr                Node address
    unsigned char index     Variable index
    void *data              Pointer to data
    int size                Size of data
  Output:
    void *data              Readback data
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_CRC_ERROR          CRC error
    MSCB_MUTEX              Cannot obtain mutex for mscb
    MSCB_FORMAT_ERROR       "size" parameter too large
    MSCB_NO_MEM             Out of memory
\********************************************************************/
{
   int i, s, status;
   MSCB_INFO_VAR info;
   debug_log("mscb_link( %d %d %d * %d)\n", fd, adr, index, size);
   /* check if variable in cache */
   for (i = 0; i < n_cache; i++)
      if (cache[i].fd == fd && cache[i].adr == adr && cache[i].index == index)
         break;
   if (i < n_cache) {
      if (memcmp(data, cache[i].data, cache[i].size) != 0) {
         /* data has changed, send update */
         memcpy(cache[i].data, data, cache[i].size);
         mscb_write(fd, adr, index, data, cache[i].size);
      } else {
         /* retrieve data from node */
         if (millitime() > cache[i].last + CACHE_PERIOD) {
            cache[i].last = millitime();
            s = cache[i].size;
            status = mscb_read(fd, adr, index, cache[i].data, &s);
            if (status != MSCB_SUCCESS)
               return status;
            memcpy(data, cache[i].data, size);
         }
      }
   } else {
      /* add new entry in cache */
      if (n_cache == 0)
         cache = (CACHE_ENTRY *) malloc(sizeof(CACHE_ENTRY));
      else
         cache = (CACHE_ENTRY *) realloc(cache, sizeof(CACHE_ENTRY) * (n_cache + 1));
      if (cache == NULL)
         return MSCB_NO_MEM;
      /* get variable size from node */
      status = mscb_info_variable(fd, adr, index, &info);
      if (status != MSCB_SUCCESS)
         return status;
      /* setup cache entry */
      i = n_cache;
      n_cache++;
      cache[i].fd = fd;
      cache[i].adr = adr;
      cache[i].index = index;
      cache[i].last = 0;
      cache[i].size = info.width;
      /* allocate at least 4 bytes */
      s = info.width;
      if (s < 4)
         s = 4;
      cache[i].data = malloc(s);
      if (cache[i].data == NULL)
         return MSCB_NO_MEM;
      memset(cache[i].data, 0, s);
      /* read initial value */
      s = cache[i].size;
      status = mscb_read(fd, adr, index, cache[i].data, &s);
      if (status != MSCB_SUCCESS)
         return status;
      memcpy(data, cache[i].data, size);
   }
   return MSCB_SUCCESS;
}
int mscb_lock (int fd)
Definition at line 567 of file mscb.c.
References FALSE, MSCB_SUCCESS, MSCB_TYPE_LPT, MSCB_TYPE_USB, status, and type.
Referenced by lpt_init(), mscb_addr(), mscb_check(), mscb_echo(), mscb_flash(), mscb_info(), mscb_info_variable(), mscb_init(), mscb_out(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_reset(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), and mscb_write_group().
{
#ifdef _MSC_VER
   int status;
   if (mutex_handle == 0)
      mutex_handle = CreateMutex(NULL, FALSE, "mscb");
   if (mutex_handle == 0)
      return 0;
   status = WaitForSingleObject(mutex_handle, 1000);
   if (status == WAIT_FAILED)
      return 0;
   if (status == WAIT_TIMEOUT)
      return 0;
#elif defined(OS_LINUX)
   if (mscb_fd[fd - 1].type == MSCB_TYPE_LPT) {
      if (ioctl(mscb_fd[fd - 1].fd, PPCLAIM))
         return 0;
   } else if (mscb_fd[fd - 1].type == MSCB_TYPE_USB) {
      if (usb_claim_interface((usb_dev_handle *) mscb_fd[fd - 1].hr, 0) < 0)
         return 0;
   }
#endif
   return MSCB_SUCCESS;
}
int mscb_out (int index, unsigned char * buffer, int len, int flags)
Definition at line 805 of file mscb.c.
References i, LPT_BIT9, LPT_BUSY, LPT_STROBE, MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, mscb_release(), mscb_reset(), MSCB_SUCCESS, MSCB_TIMEOUT, MSCB_TYPE_USB, msend_usb(), musb_close(), musb_init(), pp_rstatus(), pp_wcontrol(), pp_wdata(), RS485_FLAG_BIT9, timeout, TIMEOUT_OUT, and type.
Referenced by mscb_addr(), mscb_echo(), mscb_flash(), mscb_info(), mscb_info_variable(), mscb_init(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_reset(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), and mscb_write_group().
         : mscb_out
  Purpose: Write number of bytes to SM via parallel port or USB
  Input:
    int  index              index to file descriptor table
    char *buffer            data buffer
    int  len                number of bytes in buffer
    int  bit9               set bit9 in communication, used for
                            node addressing
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout
\********************************************************************/
{
   int i, timeout;
   unsigned char usb_buf[65];
   if (index > MSCB_MAX_FD || index < 1 || !mscb_fd[index - 1].type)
      return MSCB_INVAL_PARAM;
   /*---- USB code ----*/
   if (mscb_fd[index - 1].type == MSCB_TYPE_USB) {
      if (len >= 64 || len < 1)
         return MSCB_INVAL_PARAM;
      /* add flags in first byte of USB buffer */
      usb_buf[0] = flags;
      memcpy(usb_buf + 1, buffer, len);
      /* send on OUT pipe */
      i = msend_usb(mscb_fd[index - 1].hw, usb_buf, len + 1);
      if (i == 0) {
         /* USB submaster might have been dis- and reconnected, so reinit */
         musb_close(mscb_fd[index - 1].hr, mscb_fd[index - 1].hw);
         i = musb_init(atoi(mscb_fd[index - 1].device+3), &mscb_fd[index - 1].hr, &mscb_fd[index - 1].hw);
         if (i < 0)
            return MSCB_TIMEOUT;
         i = msend_usb(mscb_fd[index - 1].hw, usb_buf, len + 1);
      }
      if (i != len + 1) {
         return MSCB_TIMEOUT;
      }
   } else {
   /*---- LPT code ----*/
      /* remove accidental strobe */
      pp_wcontrol(index, LPT_STROBE, 0);
      for (i = 0; i < len; i++) {
         /* wait for SM ready */
         for (timeout = 0; timeout < TIMEOUT_OUT; timeout++) {
            if (!pp_rstatus(index, LPT_BUSY))
               break;
         }
         if (timeout == TIMEOUT_OUT) {
#ifndef _USRDLL
            printf("Automatic submaster reset.\n");
#endif
            mscb_release(index);
            mscb_reset(index);
            mscb_lock(index);
            Sleep(100);
            /* wait for SM ready */
            for (timeout = 0; timeout < TIMEOUT_OUT; timeout++) {
               if (!pp_rstatus(index, LPT_BUSY))
                  break;
            }
            if (timeout == TIMEOUT_OUT)
               return MSCB_TIMEOUT;
         }
         /* output data byte */
         pp_wdata(index, buffer[i]);
         /* set bit 9 */
         if (flags & RS485_FLAG_BIT9)
            pp_wcontrol(index, LPT_BIT9, 1);
         else
            pp_wcontrol(index, LPT_BIT9, 0);
         /* set strobe */
         pp_wcontrol(index, LPT_STROBE, 1);
         /* wait for busy to become active */
         for (timeout = 0; timeout < TIMEOUT_OUT; timeout++) {
            if (pp_rstatus(index, LPT_BUSY))
               break;
         }
         if (timeout == TIMEOUT_OUT) {
#ifndef _USRDLL
            printf("Automatic submaster reset.\n");
#endif
            mscb_release(index);
            mscb_reset(index);
            mscb_lock(index);
            Sleep(100);
            /* try again */
            return mscb_out(index, buffer, len, flags);
         }
         if (timeout == TIMEOUT_OUT) {
            pp_wdata(index, 0xFF);
            pp_wcontrol(index, LPT_STROBE, 0);
            return MSCB_TIMEOUT;
         }
         /* remove data, make port available for input */
         pp_wdata(index, 0xFF);
         /* remove strobe */
         pp_wcontrol(index, LPT_STROBE, 0);
      }
   }
   return MSCB_SUCCESS;
}
int mscb_ping (int fd, int adr)
Definition at line 2116 of file mscb.c.
References MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_release(), MSCB_SUCCESS, RPC_MSCB_PING, and type.
Referenced by cmd_loop(), main(), and server_execute().
         : mscb_ping
  Purpose: Ping node to see if it's alive
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
  Output:
    none
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int status;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_PING, mscb_fd[fd - 1].remote_fd, adr);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 1, 0);
   mscb_release(fd);
   return status;
}
int mscb_read (int fd, int adr, unsigned char index, void * data, int * size)
Definition at line 2939 of file mscb.c.
References buf, crc8(), DWORD_SWAP, i, MCMD_ACK, MCMD_PING16, MCMD_READ, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, MSCB_NO_MEM, mscb_out(), mscb_release(), mscb_reset(), MSCB_SUCCESS, MSCB_TIMEOUT, n, RPC_MSCB_READ, type, and WORD_SWAP.
Referenced by cmd_loop(), main(), mscb_link(), mscbdev_get(), and server_execute().
         : mscb_read
  Purpose: Read data from variable on node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    unsigned char index     Variable index 0..255
    int size                Buffer size for data
  Output:
    void *data              Received data
    int  *size              Number of received bytes
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, n, status;
   unsigned char buf[256], crc;
   memset(data, 0, *size);
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_READ, mscb_fd[fd - 1].remote_fd, adr, index, data, size);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   /* try ten times */
   for (n = 0; n < 10; n++) {
      /* after five times, reset submaster */
      if (n == 5) {
#ifndef _USRDLL
         printf("Automatic submaster reset.\n");
#endif
         mscb_reset(fd);
         Sleep(100);
      }
      buf[0] = MCMD_READ + 1;
      buf[1] = index;
      buf[2] = crc8(buf, 2);
      mscb_out(fd, buf, 3, 0);
      /* read data */
      i = mscb_in(fd, buf, sizeof(buf), 10000);
      if (i == 1 && buf[0] == 0xFF) {
#ifndef _USRDLL
         printf("Timeout from RS485 bus.\n");
#endif
         return MSCB_TIMEOUT;
      }
      if (i < 2)
         continue;
      crc = crc8(buf, i - 1);
      if ((buf[0] != MCMD_ACK + i - 2 && buf[0] != MCMD_ACK + 7)
          || buf[i - 1] != crc)
         continue;
      if (buf[0] == MCMD_ACK + 7) {
         if (i - 3 > *size) {
            mscb_release(fd);
            *size = 0;
            return MSCB_NO_MEM;
         }
         memcpy(data, buf + 2, i - 3);  // variable length
         *size = i - 3;
      } else {
         if (i - 2 > *size) {
            mscb_release(fd);
            *size = 0;
            return MSCB_NO_MEM;
         }
         memcpy(data, buf + 1, i - 2);
         *size = i - 2;
      }
      if (i - 2 == 2)
         WORD_SWAP(data);
      if (i - 2 == 4)
         DWORD_SWAP(data);
      mscb_release(fd);
      return MSCB_SUCCESS;
   }
   mscb_release(fd);
   if (i < 2)
      return MSCB_TIMEOUT;
   return MSCB_CRC_ERROR;
}
int mscb_read_range (int fd, int adr, unsigned char index1, unsigned char index2, void * data, int * size)
Definition at line 3060 of file mscb.c.
References buf, crc8(), i, MCMD_ACK, MCMD_PING16, MCMD_READ, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), mscb_reset(), MSCB_SUCCESS, MSCB_TIMEOUT, n, RPC_MSCB_READ_RANGE, and type.
Referenced by server_execute().
         : mscb_read
  Purpose: Read data from channel on node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    unsigned char index1    First index to read
    unsigned char index2    Last index to read
    int size                Buffer size for data
  Output:
    void *data              Received data
    int  *size              Number of received bytes
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, n, status;
   unsigned char buf[256], crc;
   memset(data, 0, *size);
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_READ_RANGE,
                       mscb_fd[fd - 1].remote_fd, adr, index1, index2, data, size);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   /* try ten times */
   for (n = 0; n < 10; n++) {
      /* after five times, reset submaster */
      if (n == 5) {
#ifndef _USRDLL
         printf("Automatic submaster reset.\n");
#endif
         mscb_reset(fd);
         Sleep(100);
      }
      buf[0] = MCMD_READ + 2;
      buf[1] = index1;
      buf[2] = index2;
      buf[3] = crc8(buf, 3);
      mscb_out(fd, buf, 4, 0);
      /* read data */
      i = mscb_in(fd, buf, 256, 10000);
      if (i < 2)
         continue;
      crc = crc8(buf, i - 1);
      if (buf[0] != MCMD_ACK + 7 || buf[i - 1] != crc)
         continue;
      memcpy(data, buf + 2, i - 3);
      *size = i - 3;
      mscb_release(fd);
      return MSCB_SUCCESS;
   }
   mscb_release(fd);
   if (i < 2)
      return MSCB_TIMEOUT;
   return MSCB_CRC_ERROR;
}
int mscb_reboot (int fd, int adr)
Definition at line 2021 of file mscb.c.
References buf, crc8(), MCMD_INIT, MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, RPC_MSCB_REBOOT, RS485_FLAG_NO_ACK, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_reboot
  Purpose: Reboot node by sending MCMD_INIT
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_MUTEX              Cannot obtain mutex for mscb
    MSCB_TIMEOUT            Timeout receiving ping acknowledge
\********************************************************************/
{
   unsigned char buf[10];
   int status;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_REBOOT, mscb_fd[fd - 1].remote_fd, adr);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_INIT;
   buf[1] = crc8(buf, 1);
   mscb_out(fd, buf, 2, RS485_FLAG_NO_ACK);
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int mscb_release (int fd)
Definition at line 597 of file mscb.c.
References FALSE, MSCB_SUCCESS, MSCB_TYPE_LPT, MSCB_TYPE_USB, status, and type.
Referenced by lpt_init(), mscb_addr(), mscb_check(), mscb_echo(), mscb_flash(), mscb_info(), mscb_info_variable(), mscb_init(), mscb_out(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_reset(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), and mscb_write_group().
{
#ifdef _MSC_VER
   int status;
   status = ReleaseMutex(mutex_handle);
   if (status == FALSE)
      return 0;
#elif defined(OS_LINUX)
   if (mscb_fd[fd - 1].type == MSCB_TYPE_LPT) {
      if (ioctl(mscb_fd[fd - 1].fd, PPRELEASE))
         return 0;
   } else if (mscb_fd[fd - 1].type == MSCB_TYPE_USB) {
      if (usb_release_interface((usb_dev_handle *) mscb_fd[fd - 1].hr, 0) < 0)
         return 0;
   }
#endif
   return MSCB_SUCCESS;
}
int mscb_reset (int fd)
Definition at line 2068 of file mscb.c.
References buf, LPT_RESET, MCMD_INIT, mrpc_call(), mrpc_connected(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TYPE_LPT, MSCB_TYPE_USB, musb_close(), musb_init(), pp_wcontrol(), RPC_MSCB_RESET, RS485_FLAG_CMD, and type.
Referenced by cmd_loop(), mscb_out(), mscb_read(), mscb_read_range(), and server_execute().
         : mscb_reset
  Purpose: Reset submaster via hardware reset
  Input:
    int fd                  File descriptor for connection
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_RESET, mscb_fd[fd - 1].remote_fd);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   if (mscb_fd[fd - 1].type == MSCB_TYPE_LPT) {
      /* toggle reset */
      pp_wcontrol(fd, LPT_RESET, 1);
      Sleep(100);               // for elko
      pp_wcontrol(fd, LPT_RESET, 0);
   } else if (mscb_fd[fd - 1].type == MSCB_TYPE_USB) {
      char buf[10];
      buf[0] = MCMD_INIT;
      mscb_out(fd, buf, 1, RS485_FLAG_CMD);
      musb_close(mscb_fd[fd - 1].hr, mscb_fd[fd - 1].hw);
      Sleep(1000);
      musb_init(atoi(mscb_fd[fd - 1].device + 3), &mscb_fd[fd - 1].hr, &mscb_fd[fd - 1].hw);
   }
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int mscb_select_device (char * device, int size, int select)
Definition at line 3438 of file mscb.c.
References i, lpt_close(), lpt_init(), MSCB_MAX_FD, MSCB_SUCCESS, MSCB_TYPE_LPT, musb_init(), n, strlcpy(), and MSCB_FD::type.
Referenced by mscb_init().
         : mscb_select_device
  Purpose: Select MSCB submaster device. Show dialog if sevral
           possibilities
  Input:
    none
  Output:
    char *device            Device name
    int  size               Size of device string buffer in bytes
    int  select             If 1, ask user which device to select,
                            if zero, use first device (for Labview)
  Function value:
    MSCB_SUCCESS            Successful completion
    0                       No submaster found
\********************************************************************/
{
   char list[10][256], str[256];
   int status, i, n, index, error_code;
   n = 0;
   *device = 0;
   error_code = 0;
   /* search for temporary file descriptor */
   for (index = 0; index < MSCB_MAX_FD; index++)
      if (mscb_fd[index].fd == 0)
         break;
   if (index == MSCB_MAX_FD)
      return -1;
   /* check USB devices */
   for (i = 0; i < 127; i++) {
      status = musb_init(i, NULL, NULL);
      if (status != -1)
         sprintf(list[n++], "usb%d", i);
      else
         break;
   }
   /* check LPT devices */
   for (i = 0; i < 1; i++) {
#ifdef _MSC_VER
      sprintf(str, "lpt%d", i + 1);
#else
      sprintf(str, "/dev/parport%d", i);
#endif
      mscb_fd[index].type = MSCB_TYPE_LPT;
      status = lpt_init(str, index);
      if (status < 0)
         error_code = status;
      else
         lpt_close(mscb_fd[index].fd);
      memset(&mscb_fd[index], 0, sizeof(MSCB_FD));
      if (status == 0)
         sprintf(list[n++], str);
      else
         break;
   }
   if (n == 0) {
      if (error_code == -3)
         printf("mscb.c: Cannot access parallel port (No DirectIO driver installed)\n");
      if (error_code == -4)
         printf("mscb.c: Cannot access parallel port, locked by other application\n");
      return 0;
   }
   /* if only one device, return it */
   if (n == 1 || select == 0) {
      strlcpy(device, list[0], size);
      return MSCB_SUCCESS;
   }
   do {
      printf("Found several submasters, please select one:\n\n");
      for (i = 0; i < n; i++)
         printf("%d: %s\n", i + 1, list[i]);
      printf("\n");
      fgets(str, sizeof(str), stdin);
      i = atoi(str);
      if (i > 0 && i <= n) {
         strlcpy(device, list[i - 1], size);
         return MSCB_SUCCESS;
      }
      printf("Invalid selection, please enter again\n");
   } while (1);
   return MSCB_SUCCESS;
}
int mscb_set_addr (int fd, int adr, int node, int group)
Definition at line 2286 of file mscb.c.
References buf, crc8(), MCMD_PING16, MCMD_SET_ADDR, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_ADDR_EXISTS, MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, RPC_MSCB_SET_ADDR, RS485_FLAG_NO_ACK, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_set_addr
  Purpose: Set node and group address of an node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    int node                16-bit node address
    int group               16-bit group address
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   unsigned char buf[8];
   int status;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_SET_ADDR, mscb_fd[fd - 1].remote_fd, adr, node, group);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   /* check if destination address is alive */
   status = mscb_addr(fd, MCMD_PING16, node, 10, 0);
   if (status == MSCB_SUCCESS) {
      mscb_release(fd);
      return MSCB_ADDR_EXISTS;
   }
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_SET_ADDR;
   buf[1] = (unsigned char) (node >> 8);
   buf[2] = (unsigned char) (node & 0xFF);
   buf[3] = (unsigned char) (group >> 8);
   buf[4] = (unsigned char) (group & 0xFF);
   buf[5] = crc8(buf, 5);
   mscb_out(fd, buf, 6, RS485_FLAG_NO_ACK);
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int mscb_set_name (int fd, int adr, char * name)
Definition at line 2345 of file mscb.c.
References buf, crc8(), i, MCMD_PING16, MCMD_SET_ADDR, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, RPC_MSCB_SET_NAME, RS485_FLAG_NO_ACK, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_set_name
  Purpose: Set node name
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    char *name              New node name, up to 16 characters
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   unsigned char buf[256];
   int status, i;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_SET_NAME, mscb_fd[fd - 1].remote_fd, adr, name);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_SET_ADDR | 0x07;
   for (i = 0; i < 16 && name[i]; i++)
      buf[2 + i] = name[i];
   if (i < 16)
      buf[2 + (i++)] = 0;
   buf[1] = i;                  /* varibale buffer length */
   buf[2 + i] = crc8(buf, 2 + i);
   mscb_out(fd, buf, 3 + i, RS485_FLAG_NO_ACK);
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int mscb_upload (int fd, int adr, char * buffer, int size, int debug)
Definition at line 2686 of file mscb.c.
References buf, crc8(), d, i, MCMD_ACK, MCMD_PING16, MCMD_UPGRADE, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_FORMAT_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, ofs, RPC_MSCB_UPLOAD, RS485_FLAG_LONG_TO, RS485_FLAG_NO_ACK, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_upload
  Purpose: Upload new firmware to node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    char *filename          File name for Intel HEX file
    int debug               If true, produce detailed debugging output
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
    MSCB_FORMAT_ERROR       Error in HEX file format
\********************************************************************/
{
   unsigned char buf[512], crc, ack[2], image[0x10000], *line;
   unsigned int len, ofh, ofl, type, d;
   int i, status, page, flash_size, n_page, last_page, retry;
   unsigned short ofs;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_UPLOAD, mscb_fd[fd - 1].remote_fd, adr, buffer, size);
   /* interprete HEX file */
   memset(image, 0xFF, sizeof(image));
   line = buffer;
   flash_size = 0;
   do {
      if (line[0] == ':') {
         sscanf(line + 1, "%02x%02x%02x%02x", &len, &ofh, &ofl, &type);
         ofs = (ofh << 8) | ofl;
         for (i = 0; i < (int) len; i++) {
            sscanf(line + 9 + i * 2, "%02x", &d);
            image[ofs + i] = d;
         }
         flash_size += len;
         line = strchr(line, '\r') + 1;
         if (line && *line == '\n')
            line++;
      } else
         return MSCB_FORMAT_ERROR;
   } while (*line);
   if (debug) {
      /* count pages and byes */
      n_page = 0;
      last_page = -1;
      for (page = 0; page < 128; page++) {
         /* check if page contains data */
         for (i = 0; i < 512; i++) {
            if (image[page * 512 + i] != 0xFF) {
               if (page != last_page) {
                  last_page = page;
                  n_page++;
               }
            }
         }
      }
      printf("Found %d valid pages (%d bytes) in HEX file\n", n_page, flash_size);
   }
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   /* send upgrade command */
   buf[0] = MCMD_UPGRADE;
   crc = crc8(buf, 1);
   buf[1] = crc;
   mscb_out(fd, buf, 2, RS485_FLAG_LONG_TO);
   /* wait for ready, 1 sec timeout */
   if (mscb_in(fd, ack, 2, 1000000) != 2) {
      printf("Error: timeout receiving upgrade acknowledge from remote node\n");
      /* send exit upgrade command, in case node gets to upgrade routine later */
      buf[0] = 6;
      mscb_out(fd, buf, 1, RS485_FLAG_LONG_TO);
      mscb_release(fd);
      return MSCB_TIMEOUT;
   }
   if (debug)
      printf("Received acknowledge for upgrade command\n");
   /* program pages up to 64k */
   for (page = 0; page < 128; page++) {
      /* check if page contains data */
      for (i = 0; i < 512; i++)
         if (image[page * 512 + i] != 0xFF)
            break;
      retry = 0;
      if (i < 512) {
         do {
            if (debug)
               printf("Erase page   0x%04X - ", page * 512);
            else
               printf("E");
            fflush(stdout);
            /* erase page */
            buf[0] = 2;
            buf[1] = page;
            mscb_out(fd, buf, 2, RS485_FLAG_LONG_TO);
            if (mscb_in(fd, ack, 2, 100000) != 2) {
               printf("\nError: timeout from remote node for erase page 0x%04X\n", page * 512);
               goto prog_error;
            }
            if (ack[1] == 0xFF) {
               /* protected page, so finish */
               if (debug)
                  printf("found protected page, exit\n");
               else
                  printf("\bX");
               fflush(stdout);
               goto prog_error;
            }
            if (ack[0] != MCMD_ACK) {
               printf("\nError: received wrong acknowledge for erase page 0x%04X\n", page * 512);
               goto prog_error;
            }
            if (debug)
               printf("ok\n");
            if (debug)
               printf("Program page 0x%04X - ", page * 512);
            else
               printf("\bP");
            fflush(stdout);
            /* program page */
            buf[0] = 3;
            buf[1] = page;
            mscb_out(fd, buf, 2, RS485_FLAG_NO_ACK);
            for (i = crc = 0; i < 512; i++) {
               buf[i] = image[page * 512 + i];
               crc += buf[i];
            }
            /* chop down page in 60 byte segments (->USB) */
            for (i = 0; i < 8; i++) {
               mscb_out(fd, buf + i * 60, 60, RS485_FLAG_LONG_TO);
               /* read acknowledge */
               if (mscb_in(fd, ack, 2, 100000) != 2) {
                  printf("\nError: timeout from remote node for program page 0x%04X\n", page * 512);
                  goto prog_error;
               }
            }
            /* send remaining 32 bytes */
            mscb_out(fd, buf + i * 60, 32, RS485_FLAG_LONG_TO);
            /* read acknowledge */
            if (mscb_in(fd, ack, 2, 100000) != 2) {
               printf("\nError: timeout from remote node for program page 0x%04X\n", page * 512);
               goto prog_error;
            }
            if (ack[0] != MCMD_ACK) {
               printf("\nError: received wrong acknowledge for program page 0x%04X\n", page * 512);
               goto prog_error;
            }
            if (debug)
               printf("ok\n");
            /* verify page */
            if (debug)
               printf("Verify page  0x%04X - ", page * 512);
            else
               printf("\bV");
            fflush(stdout);
            /* verify page */
            buf[0] = 4;
            buf[1] = page;
            mscb_out(fd, buf, 2, RS485_FLAG_LONG_TO);
            if (mscb_in(fd, ack, 2, 100000) != 2) {
               printf("\nError: timeout from remote node for verify page 0x%04X\n", page * 512);
               goto prog_error;
            }
            /* compare CRCs */
            if (ack[1] == crc) {
               if (debug)
                  printf("ok (CRC = 0x%02X)\n", crc);
               break;
            }
            if (debug)
               printf("CRC error (0x%02X != 0x%02X)\n", crc, ack[1]);
            /* reprogram page until verified */
            retry++;
            if (retry == 10) {
               printf("\nToo many retries, aborting\n");
               goto prog_error;
               break;
            }
         } while (1);
         if (!debug)
            printf("\b=");
         fflush(stdout);
      }
   }
 prog_error:
   printf("\n");
   /* reboot node */
   buf[0] = 5;
   mscb_out(fd, buf, 1, RS485_FLAG_NO_ACK);
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int mscb_user (int fd, int adr, void * param, int size, void * result, int * rsize)
Definition at line 3154 of file mscb.c.
References buf, crc8(), i, MCMD_PING16, MCMD_USER, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, MSCB_FORMAT_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, n, RPC_MSCB_USER, and type.
Referenced by server_execute().
         : mscb_user
  Purpose: Call user function on node
  Input:
    int  fd                 File descriptor for connection
    int adr                 Node address
    char *param             Parameters passed to user function, no CRC code
    int  size               Size of parameters in bytes
    int  *rsize             Size of result buffer
  Output:
    char *result            Optional return parameters
    int  *rsize             Number of returned size
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_CRC_ERROR          CRC error
    MSCB_MUTEX              Cannot obtain mutex for mscb
    MSCB_FORMAT_ERROR       "size" parameter too large
\********************************************************************/
{
   int i, n, status;
   unsigned char buf[80];
   memset(result, 0, *rsize);
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_USER,
                       mscb_fd[fd - 1].remote_fd, adr, param, size, result, rsize);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   if (size > 4 || size < 0)
      return MSCB_FORMAT_ERROR;
   buf[0] = MCMD_USER + size;
   for (i = 0; i < size; i++)
      buf[1 + i] = ((char *) param)[i];
   /* add CRC code and send data */
   buf[1 + i] = crc8(buf, 1 + i);
   status = mscb_out(fd, buf, 2 + i, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   if (result == NULL) {
      mscb_release(fd);
      return MSCB_SUCCESS;
   }
   /* read result */
   n = mscb_in(fd, buf, sizeof(buf), 10000);
   mscb_release(fd);
   if (n < 0)
      return MSCB_TIMEOUT;
   if (rsize)
      *rsize = n - 2;
   for (i = 0; i < n - 2; i++)
      ((char *) result)[i] = buf[1 + i];
   if (buf[n - 1] != crc8(buf, n - 1))
      return MSCB_CRC_ERROR;
   return MSCB_SUCCESS;
}
int mscb_write (int fd, int adr, unsigned char index, void * data, int size)
Definition at line 2461 of file mscb.c.
References buf, crc8(), d, i, MCMD_ACK, MCMD_PING16, MCMD_WRITE_ACK, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, RPC_MSCB_WRITE, and type.
Referenced by cmd_loop(), main(), mscb_link(), mscbdev_set(), and server_execute().
         : mscb_write
  Purpose: Write data to variable on single node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    unsigned char index     Variable index 0..255
    void *data              Data to send
    int size                Data size in bytes 1..4 for byte, word,
                            and dword
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, status;
   unsigned char buf[256], crc, ack[2];
   unsigned char *d;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_WRITE, mscb_fd[fd - 1].remote_fd, adr, index, data, size);
   if (size < 1)
      return MSCB_INVAL_PARAM;
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   if (size < 6) {
      buf[0] = MCMD_WRITE_ACK + size + 1;
      buf[1] = index;
      /* reverse order for WORD & DWORD */
      if (size < 5)
         for (i = 0, d = data; i < size; i++)
            buf[2 + size - 1 - i] = *d++;
      else
         for (i = 0, d = data; i < size; i++)
            buf[2 + i] = *d++;
      crc = crc8(buf, 2 + i);
      buf[2 + i] = crc;
      mscb_out(fd, buf, 3 + i, 0);
   } else {
      buf[0] = MCMD_WRITE_ACK + 7;
      buf[1] = size + 1;
      buf[2] = index;
      for (i = 0, d = data; i < size; i++)
         buf[3 + i] = *d++;
      crc = crc8(buf, 3 + i);
      buf[3 + i] = crc;
      mscb_out(fd, buf, 4 + i, 0);
   }
   /* read acknowledge */
   i = mscb_in(fd, ack, 2, 10000);
   mscb_release(fd);
   if (i < 2)
      return MSCB_TIMEOUT;
   if (ack[0] != MCMD_ACK || ack[1] != crc)
      return MSCB_CRC_ERROR;
   return MSCB_SUCCESS;
}
int mscb_write_block (int fd, int adr, unsigned char index, void * data, int size)
Definition at line 2549 of file mscb.c.
References buf, i, MCMD_PING16, MCMD_WRITE_BLOCK, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, n, RPC_MSCB_WRITE, RS485_FLAG_CMD, and type.
Referenced by cmd_loop().
         : mscb_write_block
  Purpose: Write block of data to single node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    unsigned char index     Variable index 0..255
    void *data              Data to send
    int size                Data size in bytes
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, n, status;
   unsigned char buf[1024];
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_WRITE, mscb_fd[fd - 1].remote_fd, adr, index, data, size);
   if (size < 1)
      return MSCB_INVAL_PARAM;
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   /*
   Bulk test gave 128kb/sec, 10.3.04, SR
   for (i=0 ; i<1024 ; i++)
      buf[i] = RS485_FLAG_CMD;
   i = msend_usb(mscb_fd[fd - 1].hw, buf, 1024);
   mscb_release(fd);
   return MSCB_SUCCESS;
   */
   /* slice data in 60 byte blocks */
   for (i=0 ; i<=size/60 ; i++) {
      buf[0] = MCMD_WRITE_BLOCK;
      n = 60;
      if (size < (i+1)*60)
         n = size - i*60;
      if (n == 0)
         break;
      memcpy(buf+1, (char *)data+i*60, n);
      mscb_out(fd, buf, n+1, RS485_FLAG_CMD);
   }
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int mscb_write_group (int fd, int adr, unsigned char index, void * data, int size)
Definition at line 2401 of file mscb.c.
References buf, crc8(), d, i, MCMD_ADDR_GRP16, MCMD_WRITE_NA, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, RPC_MSCB_WRITE_GROUP, RS485_FLAG_NO_ACK, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_write_na
  Purpose: Write data to channels on group of nodes
  Input:
    int fd                  File descriptor for connection
    int adr                 Group address
    unsigned char index     Variable index 0..255
    unsigned int  data      Data to send
    int size                Data size in bytes 1..4 for byte, word,
                            and dword
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, status;
   unsigned char *d;
   unsigned char buf[256];
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_WRITE_GROUP,
                       mscb_fd[fd - 1].remote_fd, adr, index, data, size);
   if (size > 4 || size < 1)
      return MSCB_INVAL_PARAM;
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_ADDR_GRP16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_WRITE_NA + size + 1;
   buf[1] = index;
   for (i = 0, d = data; i < size; i++)
      buf[2 + size - 1 - i] = *d++;
   buf[2 + i] = crc8(buf, 2 + i);
   mscb_out(fd, buf, 3 + i, RS485_FLAG_NO_ACK);
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int msend_usb (int fd, void * buf, int size)
Definition at line 726 of file mscb.c.
References status.
Referenced by mscb_out().
{
   int n_written;
#if defined(_MSC_VER)
   WriteFile((HANDLE) fd, buf, size, &n_written, NULL);
#elif defined(OS_LINUX)
   n_written = usb_bulk_write((usb_dev_handle *) fd, 2, buf, size, 100);
   usleep(0); // needed for linux not to crash !!!!
#elif defined(OS_DARWIN)
   IOReturn status;
   IOUSBInterfaceInterface** device = (IOUSBInterfaceInterface**)fd;
   status = (*device)->WritePipe(device,2,buf,size);
   if (status != 0) printf("msend_usb: WritePipe() status %d 0x%x\n",status,status);
   n_written = size;
#endif
   return n_written;
}
void musb_close (int fdr, int fdw)
Definition at line 1564 of file mscb.c.
Referenced by mscb_exit(), mscb_out(), and mscb_reset().
{
#if defined(_MSC_VER)
   CloseHandle((HANDLE) fdr);
   CloseHandle((HANDLE) fdw);
#elif defined(HAVE_LIBUSB)
   usb_close((usb_dev_handle *) fdr);
#else
   /* FIXME */
#endif
}
int musb_init (int index, int * hr, int * hw)
Referenced by mscb_init(), mscb_out(), mscb_reset(), and mscb_select_device().
unsigned char pp_rdata (int fd)
Definition at line 709 of file mscb.c.
References data.
Referenced by mscb_check(), and mscb_in1().
{
#if defined(_MSC_VER)
   return _inp((unsigned short) mscb_fd[fd - 1].fd);
#elif defined(OS_LINUX)
   unsigned char data;
   if (ioctl(mscb_fd[fd - 1].fd, PPRDATA, &data))
      perror("PPRDATA");
   return data;
#else
   /* no-op unsupported operation */
#endif
}
int pp_rstatus (int fd, int signal)
Definition at line 655 of file mscb.c.
References LPT_BUSY, LPT_DATAREADY, and mask.
Referenced by lpt_init(), mscb_check(), mscb_in1(), and mscb_out().
{
/* read status signal */
   unsigned int mask = 0;
#if defined(_MSC_VER)
   mask = _inp((unsigned short) (mscb_fd[fd - 1].fd + 1));
#elif defined(OS_LINUX)
   ioctl(mscb_fd[fd - 1].fd, PPRSTATUS, &mask);
#else
   /* no-op unsupported operation */
#endif
   switch (signal) {
   case LPT_BUSY:
      return (mask & (1 << 7)) == 0;
   case LPT_DATAREADY:
      return (mask & (1 << 6)) == 0;
   }
   return 0;
}
void pp_setdir (int fd, unsigned int r)
Definition at line 680 of file mscb.c.
References LPT_READMODE, and pp_wcontrol().
Referenced by lpt_init(), and mscb_in1().
{
/* set port direction: r==0:write mode;  r==1:read mode */
#if defined(_MSC_VER)
   pp_wcontrol(fd, LPT_READMODE, r);
#elif defined(OS_LINUX)
   if (ioctl(mscb_fd[fd - 1].fd, PPDATADIR, &r))
      perror("PPDATADIR");
#else
   /* no-op unsupported operation */
#endif
}
void pp_wcontrol (int fd, int signal, int flag)
Definition at line 621 of file mscb.c.
References LPT_ACK, LPT_BIT9, LPT_READMODE, LPT_RESET, LPT_STROBE, and mask.
Referenced by lpt_init(), mscb_check(), mscb_in1(), mscb_out(), mscb_reset(), and pp_setdir().
{
   static unsigned int mask = 0;
   switch (signal) {
   case LPT_STROBE:            // negative port, negative MSCB usage
      mask = flag ? mask | (1 << 0) : mask & ~(1 << 0);
      break;
   case LPT_RESET:             // negative port, negative MSCB usage
      mask = flag ? mask | (1 << 1) : mask & ~(1 << 1);
      break;
   case LPT_BIT9:              // positive
      mask = flag ? mask | (1 << 2) : mask & ~(1 << 2);
      break;
   case LPT_ACK:               // negative port, negative MSCB usage
      mask = flag ? mask | (1 << 3) : mask & ~(1 << 3);
      break;
   case LPT_READMODE:          // positive
      mask = flag ? mask | (1 << 5) : mask & ~(1 << 5);
      break;
   }
#if defined(_MSC_VER)
   _outp((unsigned short) (mscb_fd[fd - 1].fd + 2), mask);
#elif defined(OS_LINUX)
   ioctl(mscb_fd[fd - 1].fd, PPWCONTROL, &mask);
#else
   /* no-op unsupported operation */
#endif
}
void pp_wdata (int fd, unsigned int data)
Definition at line 695 of file mscb.c.
Referenced by mscb_check(), and mscb_out().
{
#if defined(_MSC_VER)
   _outp((unsigned short) mscb_fd[fd - 1].fd, data);
#elif defined(OS_LINUX)
   ioctl(mscb_fd[fd - 1].fd, PPWDATA, &data);
#else
   /* no-op unsupported operation */
#endif
}
int strieq (const char * str1, const char * str2)
Definition at line 542 of file mscb.c.
Referenced by mscb_init().
{
   if (str1 == NULL && str2 != NULL)
      return 0;
   if (str1 != NULL && str2 == NULL)
      return 0;
   if (str1 == NULL && str2 == NULL)
      return 1;
   while (*str1)
      if (toupper(*str1++) != toupper(*str2++))
         return 0;
   if (*str2)
      return 0;
   return 1;
}
size_t strlcat (char * dst, const char * src, size_t size)
Definition at line 445 of file mscb.c.
Referenced by db_save_xml_key(), debug_print(), receive_message(), sendmail(), submit_elog(), and xml_encode().
{
   char *d = dst;
   const char *s = src;
   size_t n = size;
   size_t dlen;
   /* Find the end of dst and adjust bytes left but don't go past end */
   while (n-- != 0 && *d != '\0')
      d++;
   dlen = d - dst;
   n = size - dlen;
   if (n == 0)
      return (dlen + strlen(s));
   while (*s != '\0') {
      if (n != 1) {
         *d++ = *s;
         n--;
      }
      s++;
   }
   *d = '\0';
   return (dlen + (s - src));   /* count does not include NUL */
}
size_t strlcpy (char * dst, const char * src, size_t size)
Definition at line 414 of file mscb.c.
Referenced by cm_get_environment(), cm_scan_experiments(), db_create_record(), db_sprintf(), decode_post(), interprete(), mscb_init(), mscb_select_device(), sendmail(), setparam(), ss_shell(), and xml_encode().
{
   char *d = dst;
   const char *s = src;
   size_t n = size;
   /* Copy as many bytes as will fit */
   if (n != 0 && --n != 0) {
      do {
         if ((*d++ = *s++) == 0)
            break;
      } while (--n != 0);
   }
   /* Not enough room in dst, add NUL and traverse rest of src */
   if (n == 0) {
      if (size != 0)
         *d = '\0';             /* NUL-terminate dst */
      while (*s++);
   }
   return (s - src - 1);        /* count does not include NUL */
}
Variable Documentation
int _debug_flag
Definition at line 118 of file rpc.c.
Referenced by debug_log(), and mscb_init().
CACHE_ENTRY* cache
Definition at line 384 of file mscb.c.
Referenced by hs_read().
unsigned char crc8_data[]
Definition at line 476 of file mscb.c.
MSCB_FD mscb_fd[MSCB_MAX_FD]
Definition at line 286 of file mscb.c.
int n_cache
Definition at line 385 of file mscb.c.
Referenced by db_get_event_definition(), mscb_init(), and mscb_link().