AlcapDAQ: midas/drivers/class/multi.h File Reference
midas/drivers/class/multi.h File Reference
Functions
INT cd_multi (INT cmd, PEQUIPMENT pequipment)
INT cd_multi_read (char *pevent, int)
Function Documentation
INT cd_multi (INT cmd, PEQUIPMENT pequipment)
INT cd_multi_read (char * pevent, int)
Definition at line 629 of file multi.c.
References bk_close(), bk_create(), bk_init(), bk_size(), eqpmnt::cd_info, EVENT_ID, F4_BKTYPE, MULTI_INFO::format, FORMAT_FIXED, FORMAT_MIDAS, FORMAT_YBOS, I4_BKTYPE, if, MULTI_INFO::num_channels_input, MULTI_INFO::num_channels_output, SERIAL_NUMBER, TID_FLOAT, TIME_STAMP, MULTI_INFO::var_input, MULTI_INFO::var_output, ybk_close(), ybk_create(), ybk_init(), and ybk_size().
{
   float *pdata;
   DWORD *pdw;
   MULTI_INFO *m_info;
   EQUIPMENT *pequipment;
   pequipment = *((EQUIPMENT **) pevent);
   m_info = (MULTI_INFO *) pequipment->cd_info;
   if (m_info->format == FORMAT_FIXED) {
      memcpy(pevent, m_info->var_input, sizeof(float) * m_info->num_channels_input);
      pevent += sizeof(float) * m_info->num_channels_input;
      memcpy(pevent, m_info->var_output, sizeof(float) * m_info->num_channels_output);
      pevent += sizeof(float) * m_info->num_channels_output;
      return sizeof(float) * (m_info->num_channels_input + m_info->num_channels_output);
   } else if (m_info->format == FORMAT_MIDAS) {
      bk_init(pevent);
      /* create INPT bank */
      bk_create(pevent, "INPT", TID_FLOAT, &pdata);
      memcpy(pdata, m_info->var_input, sizeof(float) * m_info->num_channels_input);
      pdata += m_info->num_channels_input;
      bk_close(pevent, pdata);
      /* create OUTP bank */
      bk_create(pevent, "OUTP", TID_FLOAT, &pdata);
      memcpy(pdata, m_info->var_output, sizeof(float) * m_info->num_channels_output);
      pdata += m_info->num_channels_output;
      bk_close(pevent, pdata);
      return bk_size(pevent);
   } else if (m_info->format == FORMAT_YBOS) {
      ybk_init((DWORD *) pevent);
      /* create EVID bank */
      ybk_create((DWORD *) pevent, "EVID", I4_BKTYPE, (DWORD *) (&pdw));
      *(pdw)++ = EVENT_ID(pevent);      /* Event_ID + Mask */
      *(pdw)++ = SERIAL_NUMBER(pevent); /* Serial number */
      *(pdw)++ = TIME_STAMP(pevent);    /* Time Stamp */
      ybk_close((DWORD *) pevent, pdw);
      /* create INPT bank */
      ybk_create((DWORD *) pevent, "INPT", F4_BKTYPE, (DWORD *) & pdata);
      memcpy(pdata, m_info->var_input, sizeof(float) * m_info->num_channels_input);
      pdata += m_info->num_channels_input;
      ybk_close((DWORD *) pevent, pdata);
      /* create OUTP bank */
      ybk_create((DWORD *) pevent, "OUTP", F4_BKTYPE, (DWORD *) & pdata);
      memcpy(pdata, m_info->var_output, sizeof(float) * m_info->num_channels_output);
      pdata += m_info->num_channels_output;
      ybk_close((DWORD *) pevent, pdata);
      return ybk_size((DWORD *) pevent);
   }
   return 0;
}