AlcapDAQ: midas/drivers/device/nulldev.c File Reference
midas/drivers/device/nulldev.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include "midas.h"
Data Structures
struct NULLDEV_SETTINGS
struct NULLDEV_INFO
Defines
#define DEFAULT_TIMEOUT 10000
#define NULLDEV_SETTINGS_STR "\Address = INT : 1\n\"
Functions
INT nulldev_init (HNDLE hkey, void **pinfo, INT channels, INT(*bd)(INT cmd,...))
INT nulldev_exit (NULLDEV_INFO *info)
INT nulldev_set (NULLDEV_INFO *info, INT channel, float value)
INT nulldev_set_all (NULLDEV_INFO *info, INT channels, float *value)
INT nulldev_get (NULLDEV_INFO *info, INT channel, float *pvalue)
INT nulldev_get_all (NULLDEV_INFO *info, INT channels, float *pvalue)
INT nulldev (INT cmd,...)
Define Documentation
#define DEFAULT_TIMEOUT 10000
Definition at line 42 of file nulldev.c.
#define NULLDEV_SETTINGS_STR "\Address = INT : 1\n\"
Definition at line 53 of file nulldev.c.
Referenced by nulldev_init().
Function Documentation
INT nulldev (INT cmd, ...)
Definition at line 224 of file nulldev.c.
References channel, CMD_EXIT, CMD_GET, CMD_GET_ALL, CMD_INIT, CMD_SET, CMD_SET_ALL, FE_SUCCESS, hKey, nulldev_exit(), nulldev_get(), nulldev_get_all(), nulldev_init(), nulldev_set(), nulldev_set_all(), status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   DWORD flags;
   float value, *pvalue;
   void *info, *bd;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      flags = va_arg(argptr, DWORD);
      bd = va_arg(argptr, void *);
      status = nulldev_init(hKey, info, channel, bd);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = nulldev_exit(info);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);   // floats are passed as double
      status = nulldev_set(info, channel, value);
      break;
   case CMD_SET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = (float *) va_arg(argptr, float *);
      status = nulldev_set_all(info, channel, pvalue);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = nulldev_get(info, channel, pvalue);
      break;
   case CMD_GET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = nulldev_get_all(info, channel, pvalue);
      break;
   default:
      break;
   }
   va_end(argptr);
   return status;
}
INT nulldev_exit (NULLDEV_INFO * info)
Definition at line 121 of file nulldev.c.
References NULLDEV_INFO::array, NULLDEV_INFO::bd, NULLDEV_INFO::bd_info, CMD_EXIT, and FE_SUCCESS.
Referenced by nulldev().
{
   /* call EXIT function of bus driver, usually closes device */
   info->bd(CMD_EXIT, info->bd_info);
   /* free local variables */
   if (info->array)
      free(info->array);
   free(info);
   return FE_SUCCESS;
}
INT nulldev_get (NULLDEV_INFO * info, INT channel, float * pvalue)
Definition at line 177 of file nulldev.c.
References NULLDEV_INFO::array, BD_GETS, BD_PUTS, DEFAULT_TIMEOUT, FE_SUCCESS, and status.
Referenced by nulldev().
{
   int status;
   char str[80];
   /* read value from channel, something like ... */
   sprintf(str, "GET %d", channel);
   BD_PUTS(str);
   status = BD_GETS(str, sizeof(str), ">", DEFAULT_TIMEOUT);
   *pvalue = (float) atof(str);
   /* simulate reading by copying set data from local array */
   if (channel < info->num_channels)
      *pvalue = info->array[channel];
   else
      *pvalue = 0.f;
   return FE_SUCCESS;
}
INT nulldev_get_all (NULLDEV_INFO * info, INT channels, float * pvalue)
Definition at line 200 of file nulldev.c.
References NULLDEV_INFO::array, FE_SUCCESS, i, MIN, and NULLDEV_INFO::num_channels.
Referenced by nulldev().
{
   int i;
   /* put here some optimized form of reading all channels. If the deviced
      does not support such a function, one can call nulldev_get() in a loop
      strcpy(str, "GETALL");
      BD_PUTS(str);
      BD_GETS(str, sizeof(str), ">", DEFAULT_TIMEOUT);
      for (i=0 ; i<MIN(info->num_channels, channels) ; i++)
      pvalue[i] = atof(str+i*5); // extract individual values from reply
    */
   /* simulate reading by copying set data from local array */
   for (i = 0; i < MIN(info->num_channels, channels); i++)
      pvalue[i] = info->array[i];
   return FE_SUCCESS;
}
INT nulldev_init (HNDLE hkey, void ** pinfo, INT channels, INT(*)(INT cmd,...) bd)
Definition at line 77 of file nulldev.c.
References NULLDEV_INFO::array, NULLDEV_INFO::bd, NULLDEV_INFO::bd_info, BD_PUTS, cm_get_experiment_database(), CMD_INIT, db_create_record(), db_find_key(), db_get_record(), DB_SUCCESS, FE_ERR_ODB, FE_SUCCESS, hDB, NULLDEV_INFO::hkey, NULLDEV_INFO::nulldev_settings, NULLDEV_SETTINGS_STR, NULLDEV_INFO::num_channels, size, status, and SUCCESS.
Referenced by nulldev().
{
   int status, size;
   HNDLE hDB, hkeydd;
   NULLDEV_INFO *info;
   /* allocate info structure */
   info = calloc(1, sizeof(NULLDEV_INFO));
   *pinfo = info;
   cm_get_experiment_database(&hDB, NULL);
   /* create NULLDEV settings record */
   status = db_create_record(hDB, hkey, "DD", NULLDEV_SETTINGS_STR);
   if (status != DB_SUCCESS)
      return FE_ERR_ODB;
   db_find_key(hDB, hkey, "DD", &hkeydd);
   size = sizeof(info->nulldev_settings);
   db_get_record(hDB, hkeydd, &info->nulldev_settings, &size, 0);
   /* initialize driver */
   info->num_channels = channels;
   info->array = calloc(channels, sizeof(float));
   info->bd = bd;
   info->hkey = hkey;
   if (!bd)
      return FE_ERR_ODB;
   /* initialize bus driver */
   status = info->bd(CMD_INIT, info->hkey, &info->bd_info);
   if (status != SUCCESS)
      return status;
   /* initialization of device, something like ... */
   BD_PUTS("init");
   return FE_SUCCESS;
}
INT nulldev_set (NULLDEV_INFO * info, INT channel, float value)
Definition at line 137 of file nulldev.c.
References NULLDEV_INFO::array, BD_GETS, BD_PUTS, DEFAULT_TIMEOUT, and FE_SUCCESS.
Referenced by nulldev().
{
   char str[80];
   /* set channel to a specific value, something like ... */
   sprintf(str, "SET %d %lf", channel, value);
   BD_PUTS(str);
   BD_GETS(str, sizeof(str), ">", DEFAULT_TIMEOUT);
   /* simulate writing by storing value in local array, has to be removed
      in a real driver */
   if (channel < info->num_channels)
      info->array[channel] = value;
   return FE_SUCCESS;
}
INT nulldev_set_all (NULLDEV_INFO * info, INT channels, float * value)
Definition at line 156 of file nulldev.c.
References NULLDEV_INFO::array, BD_GETS, BD_PUTS, DEFAULT_TIMEOUT, FE_SUCCESS, i, MIN, and NULLDEV_INFO::num_channels.
Referenced by nulldev().
{
   int i;
   char str[100000];
   /* put here some optimized form of setting all channels simultaneously like ... */
   strcpy(str, "SETALL ");
   for (i = 0; i < MIN(info->num_channels, channels); i++)
      sprintf(str + strlen(str), "%lf ", value[i]);
   BD_PUTS(str);
   BD_GETS(str, sizeof(str), ">", DEFAULT_TIMEOUT);
   /* simulate writing by storing values in local array */
   for (i = 0; i < MIN(info->num_channels, channels); i++)
      info->array[i] = value[i];
   return FE_SUCCESS;
}