AlcapDAQ: evb/old_ebuser.cpp File Reference
evb/old_ebuser.cpp File Reference
#include <stdio.h>
#include "midas.h"
#include "mevb.h"
#include "ybos.h"
#include "mucap_compress.h"
Defines
#define NUMCRATES 5
Functions
INT eb_begin_of_run (INT, char *, char *)
INT eb_end_of_run (INT, char *)
INT ebuser (INT, EBUILDER_CHANNEL *, EVENT_HEADER *, void *, INT *)
eb_user()
Hook to the event builder task after the reception of all fragments of the same serial number. The destination event has already the final EVENT_HEADER setup with the data size set to 0. It is than possible to add private data at this point using the proper bank calls.
The ebch[] array structure points to nfragment channel structure with the following content: {verbatim} typedef struct { char name[32]; // Fragment name (Buffer name). DWORD serial; // Serial fragment number. char *pfragment; // Pointer to fragment (EVENT_HEADER *) ... } EBUILDER_CHANNEL; {verbatim}
The correct code for including your own MIDAS bank is shown below where { TID_xxx} is one of the valid Bank type starting with { TID_} for midas format or { xxx_BKTYPE} for Ybos data format. { bank_name} is a 4 character descriptor. { pdata} has to be declared accordingly with the bank type. Refers to the ebuser.c source code for further description.
{ It is not possible to mix within the same destination event different event format!}
{verbatim} Event is empty, fill it with BANK_HEADER If you need to add your own bank at this stage
bk_init(pevent); bk_create(pevent, bank_name, TID_xxxx, &pdata); pdata++ = ...; dest_size = bk_close(pevent, pdata); pheader->data_size = *dest_size + sizeof(EVENT_HEADER); {verbatim}
For YBOS format, use the following example.
{verbatim} ybk_init(pevent); ybk_create(pevent, "EBBK", I4_BKTYPE, &pdata); pdata++ = 0x12345678; pdata++ = 0x87654321; dest_size = ybk_close(pevent, pdata); dest_size *= 4; pheader->data_size = *dest_size + sizeof(YBOS_BANK_HEADER); {verbatim}
Parameters:
nfrag Number of fragment.
ebch Structure to all the fragments.
pheader Destination pointer to the header.
pevent Destination pointer to the bank header.
dest_size Destination event size in bytes. event builder user code for private data filtering.
Returns:
EB_SUCCESS
INT eb_user (INT nfrag, EBUILDER_CHANNEL *ebch, EVENT_HEADER *pheader, void *pevent, INT *dest_size)
Variables
INT lModulo = 100
Define Documentation
#define NUMCRATES 5
Definition at line 52 of file old_ebuser.cpp.
Function Documentation
INT eb_begin_of_run (INT rn, char * UserField, char * error)
eb_begin_of_run() Hook to the event builder task at PreStart transition. {verbatim} {verbatim}
Parameters:
rn run number
UserField argument from /Ebuilder/Settings
error error string to be passed back to the system.
Returns:
EB_SUCCESS
Definition at line 72 of file old_ebuser.cpp.
References cm_msg, compress_load_all(), db_get_value(), EB_SUCCESS, ebch, ebset, enabled, FALSE, hDB, mask, MAX_CHANNELS, MINFO, n, NUMCRATES, size, TID_BOOL, EBUILDER_SETTINGS::trigger_mask, and EBUILDER_CHANNEL::trigger_mask.
{
  extern EBUILDER_SETTINGS ebset;
  extern EBUILDER_CHANNEL  ebch[MAX_CHANNELS];
  extern HNDLE hDB;
  int n;
  int mask = 0;
  char keyName[256];
  BOOL enabled;
  int size;
  /*
   * Determine which crates are enabled and set up the mask
   * accordingly.
   */
  for(n = 1; n <= NUMCRATES; n++) {
    sprintf(keyName, "/Equipment/Crate %d/Settings/Enabled", n);
    size = sizeof(enabled);
    db_get_value(hDB, 0, keyName, &enabled, &size, TID_BOOL, FALSE);
    if(size == sizeof(enabled) && enabled) {
       ebch[n-1].trigger_mask = (1 << (n-1));
       mask |= ebch[n-1].trigger_mask;
    } else {
       ebch[n-1].trigger_mask = 0;
    }
  }
  cm_msg(MINFO, "eb_begin_of_run", "Setting event mask to 0x%x", mask);
  ebset.trigger_mask = mask;
  // Initialize online compression
  compress_load_all();
  return EB_SUCCESS;
}
INT eb_end_of_run (INT rn, char * error)
eb_end_of_run() Hook to the event builder task at completion of event collection after receiving the Stop transition. {verbatim} {verbatim}
Parameters:
rn run number
error error string to be passed back to the system.
Returns:
EB_SUCCESS
Definition at line 121 of file old_ebuser.cpp.
References EB_SUCCESS.
{
  return EB_SUCCESS;
}
INT eb_user (INT nfrag, EBUILDER_CHANNEL * ebch, EVENT_HEADER * pheader, void * pevent, INT * dest_size)
Definition at line 187 of file old_ebuser.cpp.
References bk_init32(), bk_size(), compress_event(), EVENT_HEADER::data_size, EB_SUCCESS, i, EBUILDER_CHANNEL::pfragment, and EVENT_HEADER::serial_number.
{
  // Initialize output event
  bk_init32(pevent);
  // Loop over the event fragments, performing compression into the output event
  for(int i = 0; i < nfrag; i++) {
    void *fragment =  ebch[i].pfragment;
    if(fragment != NULL) {
      compress_event(((EVENT_HEADER *) fragment) + 1, pevent);
      pheader->serial_number =
        ((EVENT_HEADER *) ebch[i].pfragment)->serial_number;
    }
  }
  // Set the size of the output event properly
  pheader->data_size = *dest_size = bk_size(pevent);
  printf("Returning size %d\n", pheader->data_size);
  return EB_SUCCESS;
}
INT ebuser (INT , EBUILDER_CHANNEL * , EVENT_HEADER * , void * , INT *)
Variable Documentation
INT lModulo = 100
Definition at line 59 of file old_ebuser.cpp.