AlcapDAQ: midas/mscb/rpc.h File Reference
midas/mscb/rpc.h File Reference
Data Structures
struct RPC_PARAM
struct RPC_LIST
struct NET_COMMAND_HEADER
struct NET_COMMAND
Defines
#define TID_BYTE 1
#define TID_SBYTE 2
#define TID_CHAR 3
#define TID_WORD 4
#define TID_SHORT 5
#define TID_DWORD 6
#define TID_INT 7
#define TID_BOOL 8
#define TID_FLOAT 9
#define TID_DOUBLE 10
#define TID_BITFIELD 11
#define TID_STRING 12
#define TID_ARRAY 13
#define TID_STRUCT 14
#define TID_KEY 15
#define TID_LINK 16
#define TID_LAST 17
#define CBYTE(_i) (* ((unsigned char *) prpc_param[_i]))
#define CPBYTE(_i) (((unsigned char *) prpc_param[_i]))
#define CSHORT(_i) (* ((short *) prpc_param[_i]))
#define CPSHORT(_i) (((short *) prpc_param[_i]))
#define CINT(_i) (* ((int *) prpc_param[_i]))
#define CPINT(_i) (((int *) prpc_param[_i]))
#define CWORD(_i) (* ((unsigned short *) prpc_param[_i]))
#define CPWORD(_i) (((unsigned short *) prpc_param[_i]))
#define CLONG(_i) (* ((long *) prpc_param[_i]))
#define CPLONG(_i) (((long *) prpc_param[_i]))
#define CDWORD(_i) (* ((unsigned int *) prpc_param[_i]))
#define CPDWORD(_i) (((unsigned int *) prpc_param[_i]))
#define CBOOL(_i) (* ((int *) prpc_param[_i]))
#define CPBOOL(_i) (((int *) prpc_param[_i]))
#define CFLOAT(_i) (* ((float *) prpc_param[_i]))
#define CPFLOAT(_i) (((float *) prpc_param[_i]))
#define CDOUBLE(_i) (* ((double *) prpc_param[_i]))
#define CPDOUBLE(_i) (((double *) prpc_param[_i]))
#define CSTRING(_i) (((char *) prpc_param[_i]))
#define CARRAY(_i) (((void *) prpc_param[_i]))
#define RPC_IN (1 << 0)
#define RPC_OUT (1 << 1)
#define RPC_POINTER (1 << 2)
#define RPC_FIXARRAY (1 << 3)
#define RPC_VARARRAY (1 << 4)
#define RPC_OUTGOING (1 << 5)
#define RPC_MSCB_INIT 1
#define RPC_MSCB_EXIT 2
#define RPC_MSCB_RESET 3
#define RPC_MSCB_REBOOT 4
#define RPC_MSCB_PING 5
#define RPC_MSCB_INFO 6
#define RPC_MSCB_INFO_VARIABLE 7
#define RPC_MSCB_SET_ADDR 8
#define RPC_MSCB_WRITE 9
#define RPC_MSCB_WRITE_GROUP 10
#define RPC_MSCB_FLASH 11
#define RPC_MSCB_UPLOAD 12
#define RPC_MSCB_READ 13
#define RPC_MSCB_READ_RANGE 14
#define RPC_MSCB_USER 15
#define RPC_MSCB_ECHO 16
#define RPC_MSCB_SET_NAME 17
#define RPC_MSCB_ADDR 18
#define RPC_MSCB_WRITE_BLOCK 19
#define RPC_MSCB_GET_DEVICE 20
#define MSCB_RPC_PORT 1176
#define RPC_TIMEOUT 10000
#define RPC_SUCCESS 1
#define RPC_NET_ERROR 2
#define RPC_INVALID_ID 3
#define RPC_EXCEED_BUFFER 4
#define RPC_ERR_TIMEOUT 5
#define ALIGN8(x) (((x)+7) & ~7)
#define NET_TCP_SIZE 65535
Functions
void mrpc_server_loop (void)
int mrpc_connect (char *host_name)
int mrpc_connected (int fd)
int mrpc_disconnect (int sock)
int mrpc_call (int fdi, const int routine_id,...)
Define Documentation
#define ALIGN8 (x) (((x)+7) & ~7)
Definition at line 192 of file rpc.h.
#define CARRAY (_i) (((void *) prpc_param[_i]))
Definition at line 116 of file rpc.h.
#define CBOOL (_i) (* ((int *) prpc_param[_i]))
Definition at line 106 of file rpc.h.
#define CBYTE (_i) (* ((unsigned char *) prpc_param[_i]))
Definition at line 88 of file rpc.h.
#define CDOUBLE (_i) (* ((double *) prpc_param[_i]))
Definition at line 112 of file rpc.h.
#define CDWORD (_i) (* ((unsigned int *) prpc_param[_i]))
Definition at line 103 of file rpc.h.
#define CFLOAT (_i) (* ((float *) prpc_param[_i]))
Definition at line 109 of file rpc.h.
#define CINT (_i) (* ((int *) prpc_param[_i]))
Definition at line 94 of file rpc.h.
#define CLONG (_i) (* ((long *) prpc_param[_i]))
Definition at line 100 of file rpc.h.
#define CPBOOL (_i) (((int *) prpc_param[_i]))
Definition at line 107 of file rpc.h.
#define CPBYTE (_i) (((unsigned char *) prpc_param[_i]))
Definition at line 89 of file rpc.h.
#define CPDOUBLE (_i) (((double *) prpc_param[_i]))
Definition at line 113 of file rpc.h.
#define CPDWORD (_i) (((unsigned int *) prpc_param[_i]))
Definition at line 104 of file rpc.h.
#define CPFLOAT (_i) (((float *) prpc_param[_i]))
Definition at line 110 of file rpc.h.
#define CPINT (_i) (((int *) prpc_param[_i]))
Definition at line 95 of file rpc.h.
#define CPLONG (_i) (((long *) prpc_param[_i]))
Definition at line 101 of file rpc.h.
#define CPSHORT (_i) (((short *) prpc_param[_i]))
Definition at line 92 of file rpc.h.
#define CPWORD (_i) (((unsigned short *) prpc_param[_i]))
Definition at line 98 of file rpc.h.
#define CSHORT (_i) (* ((short *) prpc_param[_i]))
Definition at line 91 of file rpc.h.
#define CSTRING (_i) (((char *) prpc_param[_i]))
Definition at line 115 of file rpc.h.
#define CWORD (_i) (* ((unsigned short *) prpc_param[_i]))
Definition at line 97 of file rpc.h.
#define MSCB_RPC_PORT 1176
Definition at line 179 of file rpc.h.
Referenced by mrpc_connect(), and mrpc_server_loop().
#define NET_TCP_SIZE 65535
Definition at line 195 of file rpc.h.
#define RPC_ERR_TIMEOUT 5
Definition at line 189 of file rpc.h.
Referenced by mrpc_call().
#define RPC_EXCEED_BUFFER 4
Definition at line 188 of file rpc.h.
#define RPC_FIXARRAY (1 << 3)
Definition at line 122 of file rpc.h.
#define RPC_IN (1 << 0)
Definition at line 119 of file rpc.h.
#define RPC_INVALID_ID 3
Definition at line 187 of file rpc.h.
#define RPC_MSCB_ADDR 18
Definition at line 160 of file rpc.h.
Referenced by mscb_addr(), and server_execute().
#define RPC_MSCB_ECHO 16
Definition at line 158 of file rpc.h.
Referenced by mscb_echo(), and server_execute().
#define RPC_MSCB_EXIT 2
Definition at line 144 of file rpc.h.
Referenced by mscb_exit(), and server_execute().
#define RPC_MSCB_FLASH 11
Definition at line 153 of file rpc.h.
Referenced by mscb_flash(), and server_execute().
#define RPC_MSCB_GET_DEVICE 20
Definition at line 162 of file rpc.h.
Referenced by mscb_get_device().
#define RPC_MSCB_INFO 6
Definition at line 148 of file rpc.h.
Referenced by mscb_info(), and server_execute().
#define RPC_MSCB_INFO_VARIABLE 7
Definition at line 149 of file rpc.h.
Referenced by mscb_info_variable(), and server_execute().
#define RPC_MSCB_INIT 1
Definition at line 143 of file rpc.h.
Referenced by mscb_init(), and server_execute().
#define RPC_MSCB_PING 5
Definition at line 147 of file rpc.h.
Referenced by mscb_ping(), and server_execute().
#define RPC_MSCB_READ 13
Definition at line 155 of file rpc.h.
Referenced by mscb_read(), and server_execute().
#define RPC_MSCB_READ_RANGE 14
Definition at line 156 of file rpc.h.
Referenced by mscb_read_range(), and server_execute().
#define RPC_MSCB_REBOOT 4
Definition at line 146 of file rpc.h.
Referenced by mscb_reboot(), and server_execute().
#define RPC_MSCB_RESET 3
Definition at line 145 of file rpc.h.
Referenced by mscb_reset(), and server_execute().
#define RPC_MSCB_SET_ADDR 8
Definition at line 150 of file rpc.h.
Referenced by mscb_set_addr(), and server_execute().
#define RPC_MSCB_SET_NAME 17
Definition at line 159 of file rpc.h.
Referenced by mscb_set_name(), and server_execute().
#define RPC_MSCB_UPLOAD 12
Definition at line 154 of file rpc.h.
Referenced by mscb_upload(), and server_execute().
#define RPC_MSCB_USER 15
Definition at line 157 of file rpc.h.
Referenced by mscb_user(), and server_execute().
#define RPC_MSCB_WRITE 9
Definition at line 151 of file rpc.h.
Referenced by mscb_write(), mscb_write_block(), and server_execute().
#define RPC_MSCB_WRITE_BLOCK 19
Definition at line 161 of file rpc.h.
#define RPC_MSCB_WRITE_GROUP 10
Definition at line 152 of file rpc.h.
Referenced by mscb_write_group(), and server_execute().
#define RPC_NET_ERROR 2
Definition at line 186 of file rpc.h.
#define RPC_OUT (1 << 1)
Definition at line 120 of file rpc.h.
#define RPC_OUTGOING (1 << 5)
Definition at line 124 of file rpc.h.
#define RPC_POINTER (1 << 2)
Definition at line 121 of file rpc.h.
#define RPC_SUCCESS 1
Definition at line 185 of file rpc.h.
#define RPC_TIMEOUT 10000
Definition at line 182 of file rpc.h.
#define RPC_VARARRAY (1 << 4)
Definition at line 123 of file rpc.h.
#define TID_ARRAY 13
Definition at line 82 of file rpc.h.
#define TID_BITFIELD 11
Definition at line 80 of file rpc.h.
#define TID_BOOL 8
Definition at line 77 of file rpc.h.
#define TID_BYTE 1
Definition at line 70 of file rpc.h.
#define TID_CHAR 3
Definition at line 72 of file rpc.h.
#define TID_DOUBLE 10
Definition at line 79 of file rpc.h.
#define TID_DWORD 6
Definition at line 75 of file rpc.h.
#define TID_FLOAT 9
Definition at line 78 of file rpc.h.
#define TID_INT 7
Definition at line 76 of file rpc.h.
#define TID_KEY 15
Definition at line 84 of file rpc.h.
#define TID_LAST 17
Definition at line 86 of file rpc.h.
#define TID_LINK 16
Definition at line 85 of file rpc.h.
#define TID_SBYTE 2
Definition at line 71 of file rpc.h.
#define TID_SHORT 5
Definition at line 74 of file rpc.h.
#define TID_STRING 12
Definition at line 81 of file rpc.h.
#define TID_STRUCT 14
Definition at line 83 of file rpc.h.
#define TID_WORD 4
Definition at line 73 of file rpc.h.
Function Documentation
int mrpc_call (int fdi, const int routine_id, ...)
Definition at line 756 of file rpc.c.
References ALIGN8, closesocket, debug_log(), FD_SETSIZE, RPC_PARAM::flags, NET_COMMAND::header, i, index, mrecv_tcp(), mrpc_va_arg(), msend_tcp(), RPC_PARAM::n, name, NET_BUFFER_SIZE, param, RPC_LIST::param, NET_COMMAND::param, NET_COMMAND_HEADER::param_size, NET_COMMAND_HEADER::routine_id, RPC_ERR_TIMEOUT, RPC_EXCEED_BUFFER, RPC_FIXARRAY, RPC_IN, RPC_INVALID_ID, RPC_NET_ERROR, RPC_OUT, RPC_POINTER, RPC_TIMEOUT, RPC_VARARRAY, status, RPC_PARAM::tid, TID_ARRAY, TID_BOOL, TID_BYTE, TID_CHAR, TID_DOUBLE, TID_DWORD, TID_FLOAT, TID_INT, TID_LINK, TID_SBYTE, TID_SHORT, TID_STRING, TID_STRUCT, TID_WORD, and time.
Referenced by mscb_addr(), mscb_echo(), mscb_exit(), mscb_flash(), mscb_get_device(), mscb_info(), mscb_info_variable(), mscb_init(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_reset(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), and mscb_write_group().
{
   va_list ap, aptmp;
   char str[256], arg[8], arg_tmp[8];
   INT arg_type;
   INT i, index, status;
   INT param_size, arg_size, send_size;
   INT tid, flags;
   fd_set readfds;
   struct timeval timeout;
   char *param_ptr;
   int bpointer;
   NET_COMMAND *nc;
   time_t now;
   nc = (NET_COMMAND *) net_buffer;
   nc->header.routine_id = routine_id;
   for (i = 0;; i++)
      if (rpc_list[i].id == routine_id || rpc_list[i].id == 0)
         break;
   index = i;
   if (rpc_list[i].id == 0) {
      printf("mrpc_call: invalid rpc ID (%d)\n", routine_id);
      return RPC_INVALID_ID;
   }
   time(&now);
   strcpy(str, ctime(&now));
   str[19] = 0;
   debug_log("%s %s (", str + 4, rpc_list[i].name);
   /* examine variable argument list and convert it to parameter array */
   va_start(ap, routine_id);
   for (i = 0, param_ptr = nc->param; rpc_list[index].param[i].tid != 0; i++) {
      tid = rpc_list[index].param[i].tid;
      flags = rpc_list[index].param[i].flags;
      bpointer = (flags & RPC_POINTER) || (flags & RPC_OUT) ||
          (flags & RPC_FIXARRAY) || (flags & RPC_VARARRAY) ||
          tid == TID_STRING || tid == TID_ARRAY || tid == TID_STRUCT || tid == TID_LINK;
      if (bpointer)
         arg_type = TID_ARRAY;
      else
         arg_type = tid;
      /* floats are passed as doubles, at least under NT */
      if (tid == TID_FLOAT && !bpointer)
         arg_type = TID_DOUBLE;
      /* get pointer to argument */
      mrpc_va_arg(&ap, arg_type, arg);
      if (flags & RPC_IN) {
         if (bpointer)
            arg_size = mtid_size[tid];
         else
            arg_size = mtid_size[arg_type];
         /* for strings, the argument size depends on the string length */
         if (tid == TID_STRING || tid == TID_LINK)
            arg_size = 1 + strlen((char *) *((char **) arg));
         /* for varibale length arrays, the size is given by
            the next parameter on the stack */
         if (flags & RPC_VARARRAY) {
            memcpy(&aptmp, &ap, sizeof(ap));
            mrpc_va_arg(&aptmp, TID_ARRAY, arg_tmp);
            if (flags & RPC_OUT)
               arg_size = *((INT *) * ((void **) arg_tmp));
            else
               arg_size = *((INT *) arg_tmp);
            *((INT *) param_ptr) = ALIGN8(arg_size);
            param_ptr += ALIGN8(sizeof(INT));
         }
         if (tid == TID_STRUCT || (flags & RPC_FIXARRAY))
            arg_size = rpc_list[index].param[i].n;
         /* always align parameter size */
         param_size = ALIGN8(arg_size);
         if ((int) param_ptr - (int) nc + param_size > NET_BUFFER_SIZE) {
            printf
                ("mrpc_call: parameters (%d) too large for network buffer (%d)\n",
                 (int) param_ptr - (int) nc + param_size, NET_BUFFER_SIZE);
            return RPC_EXCEED_BUFFER;
         }
         if (bpointer)
            memcpy(param_ptr, (void *) *((void **) arg), arg_size);
         else {
            /* floats are passed as doubles on most systems */
            if (tid != TID_FLOAT)
               memcpy(param_ptr, arg, arg_size);
            else
               *((float *) param_ptr) = (float) *((double *) arg);
         }
         switch (tid) {
         case TID_BYTE:
            debug_log(" %d", *((unsigned char *) param_ptr));
            break;
         case TID_SBYTE:
            debug_log(" %d", *((char *) param_ptr));
            break;
         case TID_CHAR:
            debug_log(" %c", *((char *) param_ptr));
            break;
         case TID_WORD:
            debug_log(" %d", *((unsigned short *) param_ptr));
            break;
         case TID_SHORT:
            debug_log(" %d", *((short *) param_ptr));
            break;
         case TID_DWORD:
            debug_log(" %d", *((unsigned int *) param_ptr));
            break;
         case TID_INT:
            debug_log(" %d", *((int *) param_ptr));
            break;
         case TID_BOOL:
            debug_log(" %d", *((int *) param_ptr));
            break;
         case TID_FLOAT:
            debug_log(" %f", *((float *) param_ptr));
            break;
         case TID_DOUBLE:
            debug_log(" %lf", *((double *) param_ptr));
            break;
         case TID_STRING:
            debug_log(" %s", (char *) param_ptr);
            break;
         default:
            debug_log(" *");
            break;
         }
         param_ptr += param_size;
      }
   }
   debug_log(" ) : (");
   va_end(ap);
   nc->header.param_size = (int) param_ptr - (int) nc->param;
   send_size = nc->header.param_size + sizeof(NET_COMMAND_HEADER);
   /* send and wait for reply on send socket */
   i = msend_tcp(sock, (char *) nc, send_size);
   if (i != send_size) {
      printf("mrpc_call: msend_tcp() failed\n");
      return RPC_NET_ERROR;
   }
   /* make some timeout checking */
   FD_ZERO(&readfds);
   FD_SET(sock, &readfds);
   timeout.tv_sec = RPC_TIMEOUT / 1000;
   timeout.tv_usec = (RPC_TIMEOUT % 1000) * 1000;
   select(FD_SETSIZE, (void *) &readfds, NULL, NULL, (void *) &timeout);
   if (!FD_ISSET(sock, &readfds)) {
      printf("mrpc_call: rpc timeout, routine = \"%s\"\n", rpc_list[index].name);
      /* disconnect to avoid that the reply to this mrpc_call comes at
         the next mrpc_call */
      closesocket(sock);
      return RPC_ERR_TIMEOUT;
   }
   /* receive result on send socket */
   i = mrecv_tcp(sock, net_buffer, NET_BUFFER_SIZE);
   if (i <= 0) {
      printf("mrpc_call: mrecv_tcp() failed, routine = \"%s\"\n", rpc_list[index].name);
      return RPC_NET_ERROR;
   }
   /* extract result variables and place it to argument list */
   status = nc->header.routine_id;
   va_start(ap, routine_id);
   for (i = 0, param_ptr = nc->param; rpc_list[index].param[i].tid != 0; i++) {
      tid = rpc_list[index].param[i].tid;
      flags = rpc_list[index].param[i].flags;
      bpointer = (flags & RPC_POINTER) || (flags & RPC_OUT) ||
          (flags & RPC_FIXARRAY) || (flags & RPC_VARARRAY) ||
          tid == TID_STRING || tid == TID_ARRAY || tid == TID_STRUCT || tid == TID_LINK;
      if (bpointer)
         arg_type = TID_ARRAY;
      else
         arg_type = rpc_list[index].param[i].tid;
      if (tid == TID_FLOAT && !bpointer)
         arg_type = TID_DOUBLE;
      mrpc_va_arg(&ap, arg_type, arg);
      if (rpc_list[index].param[i].flags & RPC_OUT) {
         tid = rpc_list[index].param[i].tid;
         arg_size = mtid_size[tid];
         if (tid == TID_STRING || tid == TID_LINK)
            arg_size = strlen((char *) (param_ptr)) + 1;
         if (flags & RPC_VARARRAY) {
            arg_size = *((INT *) param_ptr);
            param_ptr += ALIGN8(sizeof(INT));
         }
         if (tid == TID_STRUCT || (flags & RPC_FIXARRAY))
            arg_size = rpc_list[index].param[i].n;
         /* return parameters are always pointers */
         if (*((char **) arg))
            memcpy((void *) *((char **) arg), param_ptr, arg_size);
         /* parameter size is always aligned */
         param_size = ALIGN8(arg_size);
         switch (tid) {
         case TID_BYTE:
            debug_log(" %d", *((unsigned char *) param_ptr));
            break;
         case TID_SBYTE:
            debug_log(" %d", *((char *) param_ptr));
            break;
         case TID_CHAR:
            debug_log(" %c", *((char *) param_ptr));
            break;
         case TID_WORD:
            debug_log(" %d", *((unsigned short *) param_ptr));
            break;
         case TID_SHORT:
            debug_log(" %d", *((short *) param_ptr));
            break;
         case TID_DWORD:
            debug_log(" %d", *((unsigned int *) param_ptr));
            break;
         case TID_INT:
            debug_log(" %d", *((int *) param_ptr));
            break;
         case TID_BOOL:
            debug_log(" %d", *((int *) param_ptr));
            break;
         case TID_FLOAT:
            debug_log(" %f", *((float *) param_ptr));
            break;
         case TID_DOUBLE:
            debug_log(" %lf", *((double *) param_ptr));
            break;
         case TID_STRING:
            debug_log(" %s", (char *) param_ptr);
            break;
         default:
            debug_log(" *");
            break;
         }
         param_ptr += param_size;
      }
   }
   debug_log(" ) : %d\n", status);
   va_end(ap);
   return status;
}
int mrpc_connect (char * host_name)
Definition at line 649 of file rpc.c.
References MSCB_RPC_PORT, and status.
Referenced by mscb_init().
{
   INT status, sock;
   struct sockaddr_in bind_addr;
   struct hostent *phe;
#ifdef _MSC_VER
   {
      WSADATA WSAData;
      /* Start windows sockets */
      if (WSAStartup(MAKEWORD(1, 1), &WSAData) != 0)
         return -1;
   }
#endif
   /* create a new socket for connecting to remote server */
   sock = socket(AF_INET, SOCK_STREAM, 0);
   if (sock == -1) {
      perror("mrpc_connect");
      return -1;
   }
   /* let OS choose any port number */
   memset(&bind_addr, 0, sizeof(bind_addr));
   bind_addr.sin_family = AF_INET;
   bind_addr.sin_addr.s_addr = 0;
   bind_addr.sin_port = 0;
   status = bind(sock, (void *) &bind_addr, sizeof(bind_addr));
   if (status < 0) {
      perror("mrpc_connect");
      return -1;
   }
   /* connect to remote node */
   memset(&bind_addr, 0, sizeof(bind_addr));
   bind_addr.sin_family = AF_INET;
   bind_addr.sin_addr.s_addr = 0;
   bind_addr.sin_port = htons((short) MSCB_RPC_PORT);
   phe = gethostbyname(host_name);
   if (phe == NULL) {
      perror("mrpc_connect");
      return -1;
   }
   memcpy((char *) &(bind_addr.sin_addr), phe->h_addr, phe->h_length);
   status = connect(sock, (void *) &bind_addr, sizeof(bind_addr));
   if (status != 0) {
      perror("mrpc_connect");
      return -1;
   }
   return sock;
}
int mrpc_connected (int fd)
Definition at line 1586 of file mscb.c.
References MSCB_TYPE_RPC, and MSCB_FD::type.
Referenced by mscb_addr(), mscb_echo(), mscb_exit(), mscb_flash(), mscb_get_device(), mscb_info(), mscb_info_variable(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_reset(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), and mscb_write_group().
{
   return mscb_fd[fd - 1].type == MSCB_TYPE_RPC;
}
int mrpc_disconnect (int sock)
Definition at line 708 of file rpc.c.
References closesocket, and RPC_SUCCESS.
Referenced by mscb_exit(), and mscb_init().
{
   closesocket(sock);
   return RPC_SUCCESS;
}
void mrpc_server_loop (void)
Definition at line 1047 of file rpc.c.
References closesocket, FD_SETSIZE, flag, i, mrecv_tcp(), mrpc_execute(), mscb_cleanup(), MSCB_RPC_PORT, N_MAX_CONNECTION, NET_BUFFER_SIZE, and status.
Referenced by main().
{
   int i, status, sock, lsock, len, flag;
   struct sockaddr_in serv_addr, acc_addr;
   char str[256];
   struct hostent *phe;
   fd_set readfds;
   struct timeval timeout;
#ifdef _MSC_VER
   {
      WSADATA WSAData;
      /* Start windows sockets */
      if (WSAStartup(MAKEWORD(1, 1), &WSAData) != 0)
         return;
   }
#endif
   /* create a new socket */
   lsock = socket(AF_INET, SOCK_STREAM, 0);
   if (lsock == -1) {
      perror("mrpc_server_loop");
      return;
   }
   /* bind local node name and port to socket */
   memset(&serv_addr, 0, sizeof(serv_addr));
   serv_addr.sin_family = AF_INET;
   serv_addr.sin_addr.s_addr = htonl(INADDR_ANY);
   serv_addr.sin_port = htons((short) MSCB_RPC_PORT);
   /* try reusing address */
   flag = 1;
   setsockopt(lsock, SOL_SOCKET, SO_REUSEADDR, (char *) &flag, sizeof(INT));
   status = bind(lsock, (struct sockaddr *) &serv_addr, sizeof(serv_addr));
   if (status < 0) {
      perror("mrpc_server_loop");
      return;
   }
   /* listen for connection */
   status = listen(lsock, SOMAXCONN);
   if (status < 0) {
      perror("mrpc_server_loop");
      return;
   }
   printf("Server listening...\n");
   do {
      FD_ZERO(&readfds);
      FD_SET(lsock, &readfds);
      for (i = 0; i < N_MAX_CONNECTION; i++)
         if (rpc_sock[i] > 0)
            FD_SET(rpc_sock[i], &readfds);
      timeout.tv_sec = 0;
      timeout.tv_usec = 100000;
      status = select(FD_SETSIZE, (void *) &readfds, NULL, NULL, (void *) &timeout);
      if (FD_ISSET(lsock, &readfds)) {
         len = sizeof(acc_addr);
         sock = accept(lsock, (struct sockaddr *) &acc_addr, &len);
         /* find new entry in socket table */
         for (i = 0; i < N_MAX_CONNECTION; i++)
            if (rpc_sock[i] == 0)
               break;
         if (i == N_MAX_CONNECTION) {
            printf("Maximum number of connections exceeded\n");
            closesocket(sock);
         } else {
            rpc_sock[i] = sock;
            phe = gethostbyaddr((char *) &acc_addr.sin_addr, 4, AF_INET);
            if (phe != NULL)
               strcpy(str, phe->h_name);
            else
               strcpy(str, (char *) inet_ntoa(acc_addr.sin_addr));
            printf("Open new connection from %s\n", str);
         }
      } else {
         /* check if open connection received data */
         for (i = 0; i < N_MAX_CONNECTION; i++)
            if (rpc_sock[i] > 0 && FD_ISSET(rpc_sock[i], &readfds)) {
               len = mrecv_tcp(rpc_sock[i], net_buffer, NET_BUFFER_SIZE);
               if (len < 0) {
                  /* remove stale fd */
                  mscb_cleanup(rpc_sock[i]);
                  /* close broken connection */
                  printf("Close connection\n");
                  closesocket(rpc_sock[i]);
                  rpc_sock[i] = 0;
               } else {
                  _server_sock = rpc_sock[i];
                  mrpc_execute(rpc_sock[i], net_buffer);
               }
            }
      }
   } while (1);
   printf("Server aborted.\n");
}