AlcapDAQ: midas/mscb/embedded/scs_210_tpg262.c File Reference
midas/mscb/embedded/scs_210_tpg262.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mscb.h"
Functions
void user_write (unsigned char index) reentrant
void write_gain (void)
void user_init (unsigned char init)
unsigned char user_read (unsigned char index)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
void user_loop (void)
Variables
bit FREEZE_MODE
bit DEBUG_MODE
char code node_name [] = "TPG262"
unsigned char idata _n_sub_addr = 1
bit terminal_mode
struct {
float p1
float p2
unsigned char baud
} user_data
MSCB_INFO_VAR code variables []
unsigned char xdata in_buf [300]
unsigned char xdata out_buf [300]
Function Documentation
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 155 of file scs_210_tpg262.c.
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void user_init (unsigned char init)
Definition at line 100 of file scs_210_tpg262.c.
References uart_init(), and user_data.
{
   /* initialize UART1 */
   if (init)
      user_data.baud = 1;       // 9600 by default
   uart_init(1, user_data.baud);
}
void user_loop (void)
Definition at line 166 of file scs_210_tpg262.c.
References i, terminal_mode, and user_data.
{
   char idata str[32];
   unsigned char i;
   if (!terminal_mode) {
      /*
      i = gets_wait(str, sizeof(str), 200);
      if (i == 0) {
         // start continuous mode, 1s update
         printf("COM,1\r\n");
         flush();
      } else if (i == 27) {
         user_data.p1 = atof(str + 2);
         user_data.p2 = atof(str + 16);
      }
      */
      user_data.p1 += 1;
      if (user_data.p1 > 100)
         user_data.p1 = 0;
   }
}
unsigned char user_read (unsigned char index)
Definition at line 138 of file scs_210_tpg262.c.
References c, getchar_nowait(), and out_buf.
{
   char c;
   if (index == 0) {
      c = getchar_nowait();
      if (c != -1) {
         out_buf[1] = c;
         return 1;
      }
   }
   return 0;
}
void user_write (unsigned char index)
Definition at line 116 of file scs_210_tpg262.c.
References i, in_buf, index, n, putchar(), terminal_mode, uart_init(), and user_data.
{
   unsigned char i, n;
   if (index == 0) {
      if (in_buf[2] == 27)
         terminal_mode = 0;
      else if (in_buf[2] == 0)
         terminal_mode = 1;
      else {
         n = (in_buf[0] & 0x07) - 1;
         for (i = 0; i < n; i++)
            putchar(in_buf[i + 2]);
      }
   }
   if (index == 3)
      uart_init(1, user_data.baud);
}
void write_gain (void)
Definition at line 219 of file scs_500.c.
References d, delay_us(), SR_CLOCK, SR_DATA, SR_DATAIN, SR_STROBE, and user_data.
{
   unsigned char i;
   SR_STROBE = 0;
   SR_CLOCK = 0;
   for (i = 0; i < 4; i++) {
      SR_DATA = ((user_data.gain[3 - i] & 0x02) > 0);   // first bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
      SR_DATA = ((user_data.gain[3 - i] & 0x01) > 0);   // second bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
   }
   for (i = 0; i < 4; i++) {
      SR_DATA = ((user_data.gain[7 - i] & 0x02) > 0);   // first bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
      SR_DATA = ((user_data.gain[7 - i] & 0x01) > 0);   // second bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
   }
   SR_DATA = 0;
   SR_STROBE = 1;
   SR_STROBE = 0;
}
Variable Documentation
unsigned char idata _n_sub_addr = 1
Definition at line 65 of file scs_210_tpg262.c.
unsigned char baud
Definition at line 76 of file scs_210_tpg262.c.
bit DEBUG_MODE
Definition at line 247 of file mscbmain.c.
bit FREEZE_MODE
Definition at line 249 of file mscbmain.c.
unsigned char xdata in_buf[300]
Definition at line 227 of file mscbmain.c.
char code node_name[] = "TPG262"
Definition at line 62 of file scs_210_tpg262.c.
unsigned char xdata out_buf[300]
Definition at line 227 of file mscbmain.c.
float p1
Definition at line 74 of file scs_210_tpg262.c.
float p2
Definition at line 75 of file scs_210_tpg262.c.
Referenced by main().
bit terminal_mode
Definition at line 67 of file scs_210_tpg262.c.
struct { ... } user_data
MSCB_INFO_VAR code variables[]
Initial value:
 {
   1, UNIT_ASCII,  0, 0, MSCBF_DATALESS, "RS232",               0,
   4, UNIT_PASCAL, 0, 0,    MSCBF_FLOAT, "P1",      &user_data.p1,
   4, UNIT_PASCAL, 0, 0,    MSCBF_FLOAT, "P2",      &user_data.p2,
   1, UNIT_BAUD,   0, 0,              0, "Baud",  &user_data.baud,
   0
}
Definition at line 80 of file scs_210_tpg262.c.