AlcapDAQ: midas/mscb/embedded/scs_700.c File Reference
midas/mscb/embedded/scs_700.c File Reference
#include <stdio.h>
#include "mscb.h"
Defines
#define GAIN 0
#define N_CHANNEL 8
Functions
void user_write (unsigned char index) reentrant
void user_init (unsigned char init)
unsigned char user_read (unsigned char index)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
void adc_read ()
void set_power (void)
void user_loop (void)
Variables
bit FREEZE_MODE
bit DEBUG_MODE
char code node_name [] = "SCS-700"
unsigned char idata _n_sub_addr = 1
struct {
char power [N_CHANNEL]
float temp [N_CHANNEL]
short ofs [N_CHANNEL]
} user_data
MSCB_INFO_VAR code variables []
unsigned char cycle
unsigned char ca [N_CHANNEL]
Define Documentation
#define GAIN 0
Definition at line 56 of file scs_700.c.
#define N_CHANNEL 8
Definition at line 100 of file scs_700.c.
Function Documentation
void adc_read ()
Definition at line 208 of file scs_700.c.
References ADBUSY, ADC0CF, ADC0H, ADC0L, ADCINT, AMX0SL, channel, DISABLE_INTERRUPTS, ENABLE_INTERRUPTS, GAIN, i, N_CHANNEL, user_data, value, and yield().
{
   static unsigned char channel = 0;
   static unsigned long value;
   static unsigned char cnt = 0;
   unsigned char i;
   float t;
   if (cnt == 0) {
      /* switch to new channel */
      channel = (channel + 1) % N_CHANNEL;
      AMX0SL = channel & 0x0F;
      ADC0CF = 0xE0 | (GAIN & 0x07);    // 16 system clocks and gain
      value = 0;
   }
   /* integrate 16 times */
   for (i = 0; i < 16; i++) {
      DISABLE_INTERRUPTS;
      ADCINT = 0;
      ADBUSY = 1;
      while (!ADCINT);          // wait until conversion ready, does NOT work with ADBUSY!
      ENABLE_INTERRUPTS;
      value += (ADC0L | (ADC0H << 8));
      yield();
   }
   cnt++;
   if (cnt == 0) {              /* average 16*256 = 4096 times */
      value /= 256;
      /* convert to volts, op-amp gain of 10 */
      t = value / 65536.0 * 2.5 / 10;
      /* convert to Ohms (1mA excitation) */
      t = t / 0.001;
      /* convert to Kelvin, coefficients obtained from table fit (www.lakeshore.com) */
      t = 5.232935E-7 * t * t * t + 0.0009 * t * t + 2.357 * t + 28.288;
      /* convert to Celsius */
      t -= 273.15;
      /* correct offset */
      t += user_data.ofs[channel] / 100.0;
      DISABLE_INTERRUPTS;
      user_data.temp[channel] = t;
      ENABLE_INTERRUPTS;
   }
}
void set_power (void)
Definition at line 270 of file scs_700.c.
References ca, cycle, i, last_time, N_CHANNEL, P1, time, and user_data.
{
   static unsigned long on_time, last_time;
   unsigned char i;
   float frac;
   unsigned long expired;
   /* only process each 10ms */
   if (time() == last_time)
      return;
   last_time = time();
   /* turn output off after on-time expired */
   for (i = 0; i < N_CHANNEL; i++)
      if (user_data.power[i] < 100) {
         expired = time() - on_time;
         if (expired >= (unsigned long) (user_data.power[i])) {
            frac = user_data.power[i] - (unsigned long) (user_data.power[i]);
            if (frac == 0 || expired >= (unsigned long) (user_data.power[i]) + 1) {
               P1 &= ~(1 << i);
            } else if (cycle > 0) {
               if ((float) ca[i] / cycle > frac) {
                  P1 &= ~(1 << i);
               } else {
                  ca[i]++;
               }
            } else {
               ca[i]++;
            }
         }
      }
   /* turn all outputs on every second */
   if (time() - on_time >= 100) {
      last_time = on_time = time();
      for (i = 0; i < N_CHANNEL; i++)
         if (user_data.power[i] > 0)
            P1 |= (1 << i);
      cycle = (cycle + 1) % 10;
      if (cycle == 0)
         for (i = 0; i < N_CHANNEL; i++)
            ca[i] = 0;
   }
}
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 198 of file scs_700.c.
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void user_init (unsigned char init)
Definition at line 148 of file scs_700.c.
References ADC0CF, ADC0CN, AMX0CF, DAC0CN, DAC1CN, for(), i, N_CHANNEL, PRT1CF, REF0CN, and user_data.
{
   unsigned char i;
   AMX0CF = 0x00;               // select single ended analog inputs
   ADC0CF = 0xE0;               // 16 system clocks, gain 1
   ADC0CN = 0x80;               // enable ADC
   REF0CN = 0x03;               // enable internal reference
   DAC0CN = 0x80;               // enable DAC0
   DAC1CN = 0x80;               // enable DAC1
   PRT1CF = 0xFF;               // P1 on push-pull
   if (init) {
      for (i = 0; i < N_CHANNEL; i++)
         user_data.power[i] = 0;
#ifdef PID_CONTROL
      for (i = 0; i < N_CHANNEL; i++) {
         user_data.demand[i] = 0;
         user_data.c_prop[i] = 1;
         user_data.c_int[i] = 0.1;
         user_data.p_int[i] = 0;
         user_data.period = 60;
      }
#endif
   }
}
void user_loop (void)
Definition at line 364 of file scs_700.c.
References adc_read(), and set_power().
{
   /* read temperature */
   adc_read();
#ifdef PID_CONTROL
   /* do regulation */
   do_control();
#endif
   /* set output according to power */
   set_power();
}
unsigned char user_read (unsigned char index)
Definition at line 189 of file scs_700.c.
{
   if (index);
   return 0;
}
void user_write (unsigned char index)
Definition at line 182 of file scs_700.c.
References index.
{
   if (index);
}
Variable Documentation
unsigned char idata _n_sub_addr = 1
Definition at line 54 of file scs_700.c.
unsigned char ca[N_CHANNEL]
Definition at line 268 of file scs_700.c.
unsigned char cycle
Definition at line 267 of file scs_700.c.
bit DEBUG_MODE
Definition at line 247 of file mscbmain.c.
bit FREEZE_MODE
Definition at line 249 of file mscbmain.c.
char code node_name[] = "SCS-700"
Definition at line 51 of file scs_700.c.
short ofs[N_CHANNEL]
Definition at line 105 of file scs_700.c.
char power[N_CHANNEL]
Definition at line 103 of file scs_700.c.
float temp[N_CHANNEL]
Definition at line 104 of file scs_700.c.
struct { ... } user_data
MSCB_INFO_VAR code variables[]
Initial value:
 {
   1, UNIT_PERCENT, 0, 0, 0, "Power0", &user_data.power[0],
   1, UNIT_PERCENT, 0, 0, 0, "Power1", &user_data.power[1],
   1, UNIT_PERCENT, 0, 0, 0, "Power2", &user_data.power[2],
   1, UNIT_PERCENT, 0, 0, 0, "Power3", &user_data.power[3],
   1, UNIT_PERCENT, 0, 0, 0, "Power4", &user_data.power[4],
   1, UNIT_PERCENT, 0, 0, 0, "Power5", &user_data.power[5],
   1, UNIT_PERCENT, 0, 0, 0, "Power6", &user_data.power[6],
   1, UNIT_PERCENT, 0, 0, 0, "Power7", &user_data.power[7],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp0", &user_data.temp[0],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp1", &user_data.temp[1],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp2", &user_data.temp[2],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp3", &user_data.temp[3],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp4", &user_data.temp[4],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp5", &user_data.temp[5],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp6", &user_data.temp[6],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp7", &user_data.temp[7],
   2, UNIT_CELSIUS, 0, 0, MSCBF_SIGNED, "Ofs0", &user_data.ofs[0],
   2, UNIT_CELSIUS, 0, 0, MSCBF_SIGNED, "Ofs1", &user_data.ofs[1],
   2, UNIT_CELSIUS, 0, 0, MSCBF_SIGNED, "Ofs2", &user_data.ofs[2],
   2, UNIT_CELSIUS, 0, 0, MSCBF_SIGNED, "Ofs3", &user_data.ofs[3],
   2, UNIT_CELSIUS, 0, 0, MSCBF_SIGNED, "Ofs4", &user_data.ofs[4],
   2, UNIT_CELSIUS, 0, 0, MSCBF_SIGNED, "Ofs5", &user_data.ofs[5],
   2, UNIT_CELSIUS, 0, 0, MSCBF_SIGNED, "Ofs6", &user_data.ofs[6],
   2, UNIT_CELSIUS, 0, 0, MSCBF_SIGNED, "Ofs7", &user_data.ofs[7],
   0
}
Definition at line 108 of file scs_700.c.