AlcapDAQ: midas/mscb/embedded/subm_300.c File Reference
midas/mscb/embedded/subm_300.c File Reference
#include <stdio.h>
#include <string.h>
#include "mscb.h"
Defines
#define LPT_DATA P1
Functions
void watchdog_refresh (void)
void setup (void)
void serial_int (void)
void check_lpt ()
void check_rs485 ()
void yield ()
void main (void)
Variables
sbit LPT_NSTROBE = P2 ^ 3
sbit LPT_BUSY = P2 ^ 7
sbit LPT_NDATAREADY = P2 ^ 6
sbit LPT_NACK = P2 ^ 5
sbit LPT_BIT9 = P2 ^ 4
unsigned char xdata *data rbuf_rp
unsigned char xdata *data rbuf_wp
bit ti_shadow
MSCB_INFO_VAR code variables []
SYS_INFO sys_info
Define Documentation
#define LPT_DATA P1
Definition at line 65 of file subm_300.c.
Function Documentation
void check_lpt ()
Definition at line 181 of file subm_300.c.
References led_blink(), LPT_BIT9, LPT_BUSY, LPT_DATA, LPT_NSTROBE, SBUF0, TB80, ti_shadow, time, and watchdog_refresh().
Referenced by main().
{
   unsigned char byte;
   bit bit9;
   unsigned long t;
   if (LPT_NSTROBE == 1)
      return;
   led_blink(0, 1, 50);
   /* receive new data */
   byte = LPT_DATA;
   bit9 = LPT_BIT9;
   /* signal busy to PC */
   LPT_BUSY = 1;
   /* send byte to serial port, flash LED */
   RS485_ENABLE = 1;
   TB80 = bit9;
   SBUF0 = byte;
   while (!ti_shadow);          /* wait until interrupt routine acknowledged send */
   RS485_ENABLE = 0;
   ti_shadow = 0;
   t = time();
   while (LPT_NSTROBE == 0) {   /* wait for strobe to be removed */
      watchdog_refresh();       /* can take very long (if PC gets context switch) */
      if (time() - t > 100)
         break;
   }
   /* remove busy */
   LPT_BUSY = 0;
}
void check_rs485 ()
Definition at line 224 of file subm_300.c.
References led_blink(), LPT_DATA, LPT_NACK, LPT_NDATAREADY, LPT_NSTROBE, P1MDOUT, rbuf_rp, rbuf_wp, time, and watchdog_refresh().
Referenced by main().
{
   unsigned char byte;
   unsigned long t;
   /* return if no data in buffer */
   if (rbuf_wp == rbuf_rp)
      return;
   /* abort if PC strobe is active to avoid data collision */
   if (LPT_NSTROBE == 0)
      return;
   led_blink(1, 1, 50);
   /* get received byte */
   byte = *rbuf_rp;
   /* increment read pointer with wrap around at 1024 bytes */
   rbuf_rp = rbuf_rp + 1;
   if (rbuf_rp == 0x400)
      rbuf_rp = 0;
   /* signal new data to PC */
   LPT_NDATAREADY = 0;
   /* wait for PC switched to input with 1s timeout */
   t = time();
   while (LPT_NACK == 1) {
      watchdog_refresh();
      if (time() - t > 100)
         break;
   }
   /* switch port to push-pull */
   P1MDOUT = 0xFF;
   /* output data to PC */
   LPT_DATA = byte;
   /* remove data ready */
   LPT_NDATAREADY = 1;
   /* wait until PC has data read with 1s timeout */
   t = time();
   while (LPT_NACK == 0) {
      watchdog_refresh();
      if (time() - t > 100)
         break;
   }
   /* switch port to open-drain */
   P1MDOUT = 0x00;
   /* prepare port for input */
   LPT_DATA = 0xFF;
   /* cause PC switch port to output */
   LPT_NDATAREADY = 0;
   /* wait for PC switched to output */
   while (LPT_NACK == 1)
      watchdog_refresh();
   /* reset data ready */
   LPT_NDATAREADY = 1;
   /* wait for end of cycle with 1s timeout */
   t = time();
   while (LPT_NACK == 0) {
      watchdog_refresh();
      if (time() - t > 100)
         break;
   }
}
void main (void)
Definition at line 313 of file subm_300.c.
References check_lpt(), check_rs485(), LPT_BUSY, setup(), TI0, ti_shadow, and watchdog_refresh().
{
   setup();
   TI0 = 0;
   ti_shadow = 0;
   RS485_ENABLE = 0;
   LPT_BUSY = 0;                /* indicate ready to receive LPT data */
   do {
      watchdog_refresh();
      /* check if data from PC */
      check_lpt();
      /* check if data frm RS485 */
      check_rs485();
   } while (1);                 /* repeat forever */
}
void serial_int (void)
Definition at line 153 of file subm_300.c.
References rbuf_rp, rbuf_wp, RI0, SBUF0, TI0, and ti_shadow.
{
   if (TI0) {
      /* signal transmitted character */
      ti_shadow = 1;
      TI0 = 0;
   }
   if (RI0) {
      /* check for buffer overflow */
      if (rbuf_wp + 1 == rbuf_rp) {
         RI0 = 0;
         return;
      }
      /* store character in read buffer */
      *rbuf_wp = SBUF0;
      /* increment write pointer with wrap around at 1024 bytes */
      rbuf_wp++;
      if (rbuf_wp == 0x400)
         rbuf_wp = 0;
      RI0 = 0;
   }
}
void setup (void)
Definition at line 93 of file subm_300.c.
References BD_115200, led_blink(), led_mode(), LPT_BIT9, LPT_BUSY, LPT_DATA, LPT_NACK, LPT_NDATAREADY, LPT_NSTROBE, OSCICN, OSCXCN, P0MDOUT, P1MDOUT, P2MDOUT, P3MDOUT, rbuf_rp, rbuf_wp, RSTSRC, sysclock_init(), uart_init(), WDTCN, XBR0, XBR1, and XBR2.
{
   XBR0 = 0x04;                 // Enable RX/TX
   XBR1 = 0x00;
   P2MDOUT = 0x00;              // P2: LPT
   P2MDOUT = 0x00;              // P2: LPT
   P2MDOUT = 0x00;              // P2: LPT
   P2MDOUT = 0x00;              // P2: LPT
   XBR2 = 0x40;                 // Enable crossbar
   /* Port configuration (1 = Push Pull Output) */
   P0MDOUT = 0x01;              // P0.1: TX = Push Pull
   P1MDOUT = 0x00;              // P1: LPT
   P2MDOUT = 0x00;              // P2: LPT
   P3MDOUT = 0xE0;              // P3.5,6,7: Optocouplers
   /* Select external quartz oscillator */
   OSCXCN = 0x66;               // Crystal mode, Power Factor 22E6
   OSCICN = 0x08;               // CLKSL=1 (external)
   /* enable watchdog */
   WDTCN = 0x07;                // 95 msec
   WDTCN = 0xA5;                // start watchdog
   /* enable missing clock reset */
   OSCICN |= 0x80;              // MSCLKE = 1
   /* enable reset pin and watchdog reset */
   RSTSRC = 0x09;
   /* start system clock */
   sysclock_init();
   /* initialize UART0 */
   uart_init(0, BD_115200);
   /* clear all dynamic memory */
   rbuf_wp = 0;
   rbuf_rp = 0;
   /* set input ports to one */
   LPT_DATA = 0xFF;
   LPT_NSTROBE = 1;
   LPT_BUSY = 1;
   LPT_NACK = 1;
   LPT_NDATAREADY = 1;
   LPT_BIT9 = 1;
   /* Blink LEDs */
   led_blink(0, 2, 150);
   led_blink(1, 2, 150);
   /* invert second LED */
   led_mode(2, 1);
}
void watchdog_refresh (void)
Definition at line 862 of file mscbutil.c.
References PCA0CPH4, and WDTCN.
         : watchdog_refresh
  Purpose: Refresh watchdog, has to be called regularly, otherwise
           the watchdog issues a reset
\********************************************************************/
{
#ifdef USE_WATCHDOG
#ifdef CPU_ADUC812
   WDR1 = 1;
   WDR2 = 1;
#endif
#ifdef CPU_CYGNAL
#if defined(CPU_C8051F310) || defined(CPU_C8051F320)
   PCA0CPH4 = 0x00;
#else
   WDTCN = 0xA5;
#endif
#endif
#endif
}
void yield (void)
Definition at line 302 of file subm_300.c.
References watchdog_refresh().
Referenced by adc_read(), cap_read(), delay_ms(), enter(), gets_wait(), main(), read_current(), read_hv(), read_temperature(), send_byte(), and user_loop().
{
   watchdog_refresh();
}
Variable Documentation
sbit LPT_BIT9 = P2 ^ 4
Definition at line 71 of file subm_300.c.
sbit LPT_BUSY = P2 ^ 7
Definition at line 68 of file subm_300.c.
sbit LPT_NACK = P2 ^ 5
Definition at line 70 of file subm_300.c.
Referenced by check_rs485(), and setup().
sbit LPT_NDATAREADY = P2 ^ 6
Definition at line 69 of file subm_300.c.
Referenced by check_rs485(), and setup().
sbit LPT_NSTROBE = P2 ^ 3
Definition at line 67 of file subm_300.c.
Referenced by check_lpt(), check_rs485(), and setup().
unsigned char xdata* data rbuf_rp
Definition at line 78 of file subm_300.c.
Referenced by check_rs485(), serial_int(), and setup().
unsigned char xdata* data rbuf_wp
Definition at line 79 of file subm_300.c.
Referenced by check_rs485(), serial_int(), and setup().
SYS_INFO sys_info
Definition at line 89 of file subm_300.c.
bit ti_shadow
Definition at line 81 of file subm_300.c.
Referenced by check_lpt(), main(), and serial_int().
MSCB_INFO_VAR code variables[]
Initial value:
 {
   0
}
Definition at line 85 of file subm_300.c.