AlcapDAQ: midas/drivers/bus/tcpip.h File Reference
midas/drivers/bus/tcpip.h File Reference
Functions
INT tcpip (INT cmd,...)
Function Documentation
INT tcpip (INT cmd, ...)
Definition at line 366 of file tcpip.c.
References CMD_DEBUG, CMD_EXIT, CMD_GETS, CMD_INIT, CMD_NAME, CMD_PUTS, CMD_READ, CMD_WRITE, FE_SUCCESS, size, status, tcpip_exit(), tcpip_gets(), tcpip_init(), tcpip_puts(), tcpip_read(), tcpip_write(), and timeout.
{
   va_list argptr;
   HNDLE hkey;
   INT status, size, timeout;
   void *info;
   char *str, *pattern;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hkey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      status = tcpip_init(hkey, info);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = tcpip_exit(info);
      break;
   case CMD_NAME:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      strcpy(str, "tcpip");
      break;
   case CMD_WRITE:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, int);
      status = tcpip_write(info, str, size);
      break;
   case CMD_READ:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, INT);
      timeout = va_arg(argptr, INT);
      status = tcpip_read(info, str, size, timeout);
      break;
   case CMD_PUTS:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      status = tcpip_puts(info, str);
      break;
   case CMD_GETS:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, INT);
      pattern = va_arg(argptr, char *);
      timeout = va_arg(argptr, INT);
      status = tcpip_gets(info, str, size, pattern, timeout);
      break;
   case CMD_DEBUG:
      info = va_arg(argptr, void *);
      status = va_arg(argptr, INT);
      ((TCPIP_INFO *) info)->settings.debug = status;
      break;
   }
   va_end(argptr);
   return status;
}