AlcapDAQ: midas/drivers/divers/vmeio.h File Reference
midas/drivers/divers/vmeio.h File Reference
#include "stdio.h"
#include "string.h"
Defines
#define INLINE
#define EXTERNAL extern
#define A32D24 0xf0000000
#define ENABLE_INT 0x00
#define SET_INT_SYNC 0x01
#define SET_PULSE 0x02
#define WRITE_PULSE 0x03
#define WRITE_LATCH 0x04
#define READ_SYNC 0x05
#define READ_ASYNC 0x06
#define READ_STATUS 0x07
#define CLEAR_VMEIO 0x07
#define VMEIO_VECT_BASE 0x7f
Typedefs
typedef unsigned short int WORD
typedef unsigned long int DWORD
Functions
void myStub (void)
void vmeio (void)
void vmeio_intsync_set (DWORD base_adr, DWORD pattern)
void vmeio_pulse_set (const DWORD base_adr, DWORD pattern)
void vmeio_sync_read (const DWORD base_adr, DWORD *data)
void vmeio_async_read (const DWORD base_adr, DWORD *data)
void vmeio_pulse_write (const DWORD base_adr, DWORD data)
void vmeio_latch_write (const DWORD base_adr, DWORD data)
void vmeio_clear (const DWORD base_adr)
void vmeio_status_read (const DWORD base_adr, DWORD *data)
void vmeio_int_clear (const DWORD base_adr)
void vmeio_int_enable (const DWORD base_adr, int intnum)
void vmeio_int_disable (const DWORD base_adr, int intnum)
void vmeio_int_attach (const DWORD base_adr, DWORD base_vect, int intnum, void(*isr)(void))
void vmeio_int_detach (const DWORD base_adr, DWORD base_vect, int intnum)
Define Documentation
#define A32D24 0xf0000000
Definition at line 72 of file vmeio.h.
#define CLEAR_VMEIO 0x07
Definition at line 83 of file vmeio.h.
Referenced by vmeio_clear(), and vmeio_int_clear().
#define ENABLE_INT 0x00
Definition at line 75 of file vmeio.h.
Referenced by vmeio_int_disable(), and vmeio_int_enable().
#define EXTERNAL extern
Definition at line 54 of file vmeio.h.
#define INLINE
Definition at line 51 of file vmeio.h.
#define READ_ASYNC 0x06
Definition at line 81 of file vmeio.h.
Referenced by vmeio_async_read().
#define READ_STATUS 0x07
Definition at line 82 of file vmeio.h.
Referenced by vmeio_status_read(), and vmeio_sync_read().
#define READ_SYNC 0x05
Definition at line 80 of file vmeio.h.
Referenced by vmeio_sync_read().
#define SET_INT_SYNC 0x01
Definition at line 76 of file vmeio.h.
Referenced by vmeio_intsync_set().
#define SET_PULSE 0x02
Definition at line 77 of file vmeio.h.
Referenced by vmeio_pulse_set().
#define VMEIO_VECT_BASE 0x7f
Definition at line 85 of file vmeio.h.
#define WRITE_LATCH 0x04
Definition at line 79 of file vmeio.h.
Referenced by vmeio_latch_write().
#define WRITE_PULSE 0x03
Definition at line 78 of file vmeio.h.
Referenced by vmeio_pulse_write().
Typedef Documentation
typedef unsigned long int DWORD
Definition at line 64 of file vmeio.h.
typedef unsigned short int WORD
Definition at line 59 of file vmeio.h.
Function Documentation
void myStub (void)
Definition at line 43 of file vmeio.c.
Referenced by vmeio_int_detach().
{
#ifdef OS_VXWORKS
   logMsg("myStub\n", 0, 0, 0, 0, 0, 0);
#endif
}
void vmeio (void)
Definition at line 327 of file vmeio.c.
{
   printf("\n---> vmeIO Triumf board 24bit in/out latch/pulse + 8 interrupts <---\n");
   printf("Inline: vmeio_intsync_set (base, pattern)  : set interrupt source\n");
   printf("Inline: vmeio_pulse_set   (base, pattern)  : set output pulse\n");
   printf("Inline: vmeio_sync_read   (base, *data)    : read sync input\n");
   printf("Inline: vmeio_async_read  (base, *data)    : read Async input\n");
   printf("Inline: vmeio_pulse_write (base, data)     : write pulse output\n");
   printf("Inline: vmeio_latch_write (base, data)     : write latch output\n");
   printf("Inline: vmeio_clear       (base)           : clear strobe\n");
   printf("Inline: vmeio_status_read (base, *status)  : read status register\n");
   printf("Inline: vmeio_int_clear   (base)           : clear interrupts\n");
   printf("Inline: vmeio_int_enable  (base, int#)     : enable interrupt (0:7)\n");
   printf("Inline: vmeio_int_disable (base, int#)     : disable interrupt (0:7)\n");
   printf("Inline: vmeio_int_enable  (base, int#)     : enable interrupt (0:7)\n");
   printf("Inline: vmeio_int_attach  (base, vec, int#, isr) : interrupt (0:7)\n");
   printf("Inline: vmeio_int_detach  (base, vect, int#) : interrupt (0:7)\n");
   printf("Test  : vmeio_Status_read (0x780000)       : display status\n");
   printf("Test  : vmeio_Async_read  (0x780000)       : read Async\n");
   printf("Test  : vmeio_Sync_read   (0x780000)       : read sync\n");
   printf("Test  : vmeio_Pulse_write (0x780000,       : write pulse\n");
   printf("Test  : vmeio_Latch_write (0x780000,       : write latch\n");
   printf("Test  : vmeio_Clear       (0x780000)       : clear VMEIO\n");
   printf("Test  : Interrupt : VMEIO_BASE: 0x780000, VMEIO_VECT_BASE: 0x7F\n");
   printf("Test  : The interrupt test is based on the following configuration:\n");
   printf("        Output 0 -> strobe\n");
   printf("        Output 1 -> Input 0\n");
   printf("        Output 2 -> Input 1\n");
   printf("        Output 3 -> Input 2\n");
   printf("        vmeio_attach_async_interrupt(1)  will enable I1\n");
   printf("        vmeio_gen_async(1)               will generate int in I1\n");
   printf("  or    vmeio_attach_sync_interrupt(1)   will enable I1\n");
   printf("        vmeio_gen_sync(1)                will generate int in I1\n");
   printf("Test  : vmeio_attach_async_interrupt( x...): attach, enable Int#\n");
   printf("Test  : vmeio_attach_sync_interrupt( x...) : attach, enable Int#\n");
   printf("Test  : vmeio_detach_interrupt( x...)      : detach, enable Int#\n");
   printf("Test  : vmeio_gen_async( x)                : generate a Async int\n");
   printf("Test  : vmeio_gen_sync( x)                 : generate a sync int\n");
}
void vmeio_async_read (const DWORD base_adr, DWORD * data)
Definition at line 120 of file vmeio.c.
References A32D24, and READ_ASYNC.
Referenced by vmeio_Async_read().
        : read VMEIO async input data
 Input:
  DWORD * base_addr       : base address of the VMEIO
  DWORD * data            : data to be read
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr) + (READ_ASYNC);
   *data = (*spec_adr & 0xffffff);
}
void vmeio_clear (const DWORD base_adr)
Definition at line 183 of file vmeio.c.
References A32D24, and CLEAR_VMEIO.
Referenced by vmeio_Clear(), and vmeio_gen_sync().
        : clear the status reg (strobe)
 Input:
  DWORD * base_addr       : base address of the VMEIO
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   /* status : Check first if trigger has been received */
   spec_adr = (DWORD *) (A32D24 + base_adr) + (CLEAR_VMEIO);
   *spec_adr = 0x0;
}
void vmeio_int_attach (const DWORD base_adr, DWORD base_vect, int intnum, void(*)(void) isr)
Definition at line 275 of file vmeio.c.
References isr, vmeio_int_clear(), vmeio_int_disable(), and vmeio_int_enable().
Referenced by vmeio_attach_async_interrupt(), and vmeio_attach_sync_interrupt().
        : Book an ISR for a bitwise set of interrupt input (0xff).
          The interrupt vector is then the VECTOR_BASE+intnum
 Input:
  DWORD * base_addr      : base address of the VMEIO
  DWORD base_vect        : base vector of the module
  DWORD intnum           : interrupt number (0:7)
  DWORD isr_routine      : interrupt routine pointer
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   vmeio_int_clear(base_adr);   /* clear any pending front panel interrupts */
   vmeio_int_disable(base_adr, intnum); /* bitwise input */
#ifdef OS_VXWORKS
   if (intnum < 8)
      intConnect(INUM_TO_IVEC(base_vect + intnum), (VOIDFUNCPTR) isr, intnum);
#else
   printf("vector : 0x%x\n", base_vect + intnum);
#endif
   vmeio_int_enable(base_adr, intnum);  /* bitwise input */
}
void vmeio_int_clear (const DWORD base_adr)
Definition at line 222 of file vmeio.c.
References A32D24, and CLEAR_VMEIO.
Referenced by vmeio_int_attach(), and vmeio_int_detach().
{
   volatile DWORD *spec_adr;
   /* status : Check first if trigger has been received */
   spec_adr = (DWORD *) (A32D24 + base_adr) + (CLEAR_VMEIO);
   *spec_adr = 0x0;
}
void vmeio_int_detach (const DWORD base_adr, DWORD base_vect, int intnum)
Definition at line 302 of file vmeio.c.
References myStub(), vmeio_int_clear(), and vmeio_int_disable().
Referenced by vmeio_detach_interrupt().
        : Unbook an ISR for a bitwise set of interrupt input (0xff).
          The interrupt vector is then the VECTOR_BASE+intnum
 Input:
  DWORD * base_addr       : base address of the VMEIO
  DWORD base_vect        : base vector of the module
  DWORD intnum           : interrupt number (0:7)
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   vmeio_int_clear(base_adr);   /* clear any pending front panel interrupts */
   vmeio_int_disable(base_adr, intnum); /* mask off external interrupt x */
#ifdef OS_VXWORKS
   if (intnum < 8)
      intConnect(INUM_TO_IVEC(base_vect + intnum), (VOIDFUNCPTR) myStub, intnum);
#else
   printf("vector : 0x%x\n", base_vect + intnum);
#endif
}
void vmeio_int_disable (const DWORD base_adr, int intnum)
Definition at line 253 of file vmeio.c.
References A32D24, and ENABLE_INT.
Referenced by vmeio_attach_async_interrupt(), vmeio_attach_sync_interrupt(), vmeio_detach_interrupt(), vmeio_int_attach(), and vmeio_int_detach().
        : Disable the interrupt for the bitwise input intnum (0xff).
          The interrupt vector is then the VECTOR_BASE+intnum
 Input:
  DWORD * base_addr       : base address of the VMEIO
  DWORD * intnum          : interrupt number (input 0:7)
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
#ifdef OS_VXWORKS
   sysIntDisable(7);            /* interrupt level 7 */
#endif
   spec_adr = (DWORD *) (A32D24 + base_adr) + (ENABLE_INT);
   *spec_adr = ~(intnum & 0xff);
}
void vmeio_int_enable (const DWORD base_adr, int intnum)
Definition at line 231 of file vmeio.c.
References A32D24, and ENABLE_INT.
Referenced by vmeio_attach_async_interrupt(), vmeio_attach_sync_interrupt(), and vmeio_int_attach().
        : Enable the interrupt for the bitwise input intnum (0xff).
          The interrupt vector is then the VECTOR_BASE+intnum
 Input:
  DWORD * base_addr       : base address of the VMEIO
  DWORD * intnum          : interrupt number (input 0:7)
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr) + (ENABLE_INT);
   *spec_adr = (intnum & 0xff);
#ifdef OS_VXWORKS
   sysIntEnable(7);             /* interrupt level 7 */
#endif
}
void vmeio_intsync_set (DWORD base_adr, DWORD pattern)
Definition at line 51 of file vmeio.c.
References A32D24, and SET_INT_SYNC.
Referenced by vmeio_attach_async_interrupt(), vmeio_attach_sync_interrupt(), and vmeio_gen_async().
        : Set VMEIO interrupt source to be sync mode.
          Each bit refers to an input (0:7)
          If not set the interrupt source is Async
 Input:
  DWORD * base_addr     : base address of the VMEIO
  DWORD pattern         : data to be applied to board
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr) + (SET_INT_SYNC);
   *spec_adr = (pattern & 0xf);
}
void vmeio_latch_write (const DWORD base_adr, DWORD data)
Definition at line 161 of file vmeio.c.
References A32D24, and WRITE_LATCH.
Referenced by vmeio_Latch_write().
        : write to VMEIO latch output.
          only the latch enable channels will be affected
          Each bit correspond to a output (0:23)
 Input:
  DWORD * base_addr       : base address of the VMEIO
  DWORD data              : data to write
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   /* status : Check first if trigger has been received */
   spec_adr = (DWORD *) (A32D24 + base_adr) + (WRITE_LATCH);
   *spec_adr = (data & 0xffffff);
}
void vmeio_pulse_set (const DWORD base_adr, DWORD pattern)
Definition at line 72 of file vmeio.c.
References A32D24, and SET_PULSE.
Referenced by vmeio_attach_async_interrupt(), and vmeio_attach_sync_interrupt().
        : Set VMEIO output channel pattern to be pulse mode
          Each bit refers to an output (0:23)
          If not set the output is latch mode
 Input:
  DWORD * base_addr     : base address of the VMEIO
  DWORD pattern         : data to be applied to board
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr) + (SET_PULSE);
   *spec_adr = (pattern & 0xffffff);
}
void vmeio_pulse_write (const DWORD base_adr, DWORD data)
Definition at line 139 of file vmeio.c.
References A32D24, and WRITE_PULSE.
Referenced by vmeio_Pulse_write().
        : write to VMEIO pulse output.
          only the pulse enable channels will be affected
          Each bit correspond to a output (0:23)
 Input:
  DWORD * base_addr       : base address of the VMEIO
  DWORD data              : data to write
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   DWORD *spec_adr;
   /* status : Check first if trigger has been received */
   spec_adr = (DWORD *) (A32D24 | base_adr) + (WRITE_PULSE);
   *spec_adr = (data & 0xffffff);
}
void vmeio_status_read (const DWORD base_adr, DWORD * data)
Definition at line 202 of file vmeio.c.
References A32D24, and READ_STATUS.
Referenced by vmeio_Status_read().
        : read the status register.
          contains the strobe bit (0x1), the interrupt level (0x70)
 Input:
  DWORD * base_addr       : base address of the VMEIO
  DWORD * data            : status
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   spec_adr = (DWORD *) (A32D24 + base_adr) + (READ_STATUS);
   *data = (*spec_adr & 0xff);
}
void vmeio_sync_read (const DWORD base_adr, DWORD * data)
Definition at line 93 of file vmeio.c.
References A32D24, READ_STATUS, READ_SYNC, and status.
Referenced by vmeio_Sync_read().
        : read VMEIO sync input data if gate received
 Input:
  DWORD * base_addr       : base address of the VMEIO
  DWORD * data            : data to be read
 Output:
    none
 Function value:
    none
\**************************************************************/
{
   volatile DWORD *spec_adr;
   DWORD status;
   /* status : Check first if trigger has been received */
   spec_adr = (DWORD *) (A32D24 + base_adr) + (READ_STATUS);
   status = *spec_adr;
   status &= 0xf;
   if (status != 0) {
      spec_adr = (DWORD *) (A32D24 + base_adr) + (READ_SYNC);
      *data = (*spec_adr & 0xffffff);
   } else
      *data = 0x80000000;
}