AlcapDAQ:Rootana: analyzer/rootana/src/deprecated/AnalysePulseIsland.h File Reference
analyzer/rootana/src/deprecated/AnalysePulseIsland.h File Reference
#include "FillHistBase.h"
#include "TGlobalData.h"
#include "TSetupData.h"
#include "TAnalysedPulse.h"
Data Structures
class AnalysePulseIsland
Functions
bool IsTimeOrdered (TAnalysedPulse *a, TAnalysedPulse *b)
Function Documentation
bool IsTimeOrdered (TAnalysedPulse * a, TAnalysedPulse * b)
Definition at line 117 of file AnalysePulseIsland.cpp.
References TAnalysedPulse::GetTime().
Referenced by AnalysePulseIsland::ProcessEntry(), and MaxBinAPGenerator::ProcessPulses().
{
  // Want a to be before b
  return ( a->GetTime() < b->GetTime() );
}