AlcapDAQ:Rootana: midas/drivers/device/bl_psi.h File Reference
midas/drivers/device/bl_psi.h File Reference
Functions
INT bl_psi (INT cmd,...)
Function Documentation
INT bl_psi (INT cmd, ...)
Definition at line 370 of file bl_psi.c.
References bl_psi_exit(), bl_psi_get(), bl_psi_get_default_name(), bl_psi_get_default_threshold(), bl_psi_get_demand(), bl_psi_init(), bl_psi_set(), channel, CMD_EXIT, CMD_GET, CMD_GET_DEFAULT_NAME, CMD_GET_DEFAULT_THRESHOLD, CMD_GET_DEMAND, CMD_INIT, CMD_SET, FE_SUCCESS, hKey, name, status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   float value, *pvalue;
   void *info;
   char *name;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      status = bl_psi_init(hKey, info, channel);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = bl_psi_exit(info);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = bl_psi_set(info, channel, value);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = bl_psi_get(info, channel, pvalue);
      break;
   case CMD_GET_DEMAND:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = bl_psi_get_demand(info, channel, pvalue);
      break;
   case CMD_GET_DEFAULT_NAME:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      name = va_arg(argptr, char *);
      status = bl_psi_get_default_name(info, channel, name);
      break;
   case CMD_GET_DEFAULT_THRESHOLD:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = bl_psi_get_default_threshold(info, channel, pvalue);
      break;
   default:
      break;
   }
   va_end(argptr);
   return status;
}