AlcapDAQ:Rootana: midas/drivers/bus/esone.c File Reference
midas/drivers/bus/esone.c File Reference
#include <stdio.h>
#include "mcstd.h"
#include "esone.h"
Functions
INLINE void came_cn (int *ext, const int b, const int c, const int n, const int a)
INLINE void came_ext (const int ext, int *b, int *c, int *n, int *a)
INLINE void ccinit (void)
INLINE int fccinit (void)
INLINE void cdreg (int *ext, const int b, const int c, const int n, const int a)
INLINE void cssa (const int f, int ext, unsigned short *d, int *q)
INLINE void cfsa (const int f, const int ext, unsigned long *d, int *q)
INLINE void cccc (const int ext)
INLINE void cccz (const int ext)
INLINE void ccci (const int ext, int l)
INLINE void ctci (const int ext, int *l)
INLINE void cccd (const int ext, int l)
INLINE void ctcd (const int ext, int *l)
INLINE void cdlam (int *lam, const int b, const int c, const int n, const int a, const int inta[2])
INLINE void ctgl (const int ext, int *l)
INLINE void cclm (const int lam, int l)
INLINE void cclnk (const int lam, void(*isr)(void))
INLINE void cculk (const int lam)
INLINE void ccrgl (const int lam)
INLINE void cclc (const int lam)
INLINE void ctlm (const int lam, int *l)
INLINE void cfga (int f[], int exta[], int intc[], int qa[], int cb[])
INLINE void csga (int f[], int exta[], int intc[], int qa[], int cb[])
INLINE void cfmad (int f, int extb[], int intc[], int cb[])
INLINE void csmad (int f, int extb[], int intc[], int cb[])
INLINE void cfubc (const int f, int ext, int intc[], int cb[])
INLINE void csubc (const int f, int ext, int intc[], int cb[])
INLINE void cfubr (const int f, int ext, int intc[], int cb[])
INLINE void csubr (const int f, int ext, int intc[], int cb[])
Function Documentation
INLINE void came_cn (int * ext, const int b, const int c, const int n, const int a)
dox
Definition at line 55 of file esone.c.
Referenced by cdreg(), cfmad(), and csmad().
{
   *ext = (b << 24 | (c << 16) | (n << 8) | a);
}
INLINE void came_ext (const int ext, int * b, int * c, int * n, int * a)
Definition at line 61 of file esone.c.
Referenced by cccc(), cccd(), ccci(), cccz(), cclc(), cclm(), cclnk(), ccrgl(), cculk(), cfmad(), cfsa(), csmad(), cssa(), ctcd(), ctci(), ctgl(), and ctlm().
{
   *b = (ext >> 24) & 0x7;
   *c = (ext >> 16) & 0x7;
   *n = (ext >> 8) & 0x1f;
   *a = (ext >> 0) & 0xf;
}
INLINE void cccc (const int ext)
Control Crate Clear.
Generate Crate Clear function. Execute cam_crate_clear()
Parameters:
ext external address
Returns:
void
Definition at line 206 of file esone.c.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   cam_crate_clear(c);
}
INLINE void cccd (const int ext, int l)
Control Crate D.
Enable or Disable Crate Demand.
Parameters:
ext external address
l action l=0 -> Clear D, l=1 -> Set D
Returns:
void
Definition at line 280 of file esone.c.
Referenced by main().
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   if (l)
      cam_interrupt_enable(c);
   else
      cam_interrupt_disable(c);
}
INLINE void ccci (const int ext, int l)
Control Crate I.
Set or Clear Dataway Inhibit, Execute cam_inhinit_set() /clear()
Parameters:
ext external address
l action l=0 -> Clear I, l=1 -> Set I
Returns:
void
Definition at line 241 of file esone.c.
Referenced by main().
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   if (l)
      cam_inhibit_set(c);
   else
      cam_inhibit_clear(c);
}
INLINE void cccz (const int ext)
Control Crate Z.
Generate Dataway Initialize. Execute cam_crate_zinit()
Parameters:
ext external address
Returns:
void
Definition at line 223 of file esone.c.
Referenced by main().
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   cam_crate_zinit(c);
}
INLINE void ccinit (void)
dox CAMAC initialization
CAMAC initialization must be called before any other ESONE subroutine call.
Returns:
void
Definition at line 85 of file esone.c.
{
   cam_init();
}
INLINE void cclc (const int lam)
Control Clear LAM.
Clear the LAM of the station pointer by the lam address.
Parameters:
lam external address
Returns:
void
Definition at line 441 of file esone.c.
Referenced by isr(), and main().
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   camc(c, n, 0, 10);
}
INLINE void cclm (const int lam, int l)
Control Crate LAM.
Enable or Disable LAM. Execute F24 for disable, F26 for enable.
Parameters:
lam external address
l action l=0 -> disable LAM , l=1 -> enable LAM
Returns:
void
Definition at line 361 of file esone.c.
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   if (l)
      camc(c, n, 0, 26);
   else
      camc(c, n, 0, 24);
}
INLINE void cclnk (const int lam, void(*)(void) isr)
Link LAM to service procedure
Link a specific service routine to a LAM. Since this routine is executed asynchronously, care must be taken on re-entrancy.
Parameters:
lam external address
isr name of service procedure
Returns:
void
Definition at line 384 of file esone.c.
References c, cam_interrupt_attach(), cam_lam_clear(), cam_lam_enable(), came_ext(), isr, and n.
Referenced by main().
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   cam_interrupt_attach(c, n, isr);
   cam_lam_enable(c, n);
   cam_lam_clear(c, n);
}
INLINE void ccrgl (const int lam)
Relink LAM
Re-enable LAM in the controller
Parameters:
lam external address
Returns:
void
Definition at line 421 of file esone.c.
References c, cam_interrupt_enable(), cam_lam_clear(), cam_lam_enable(), came_ext(), and n.
Referenced by isr().
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   cam_lam_enable(c, n);
   cam_lam_clear(c, n);
   cam_interrupt_enable(c);
}
INLINE void cculk (const int lam)
Unlink LAM from service procedure
Performs complementary operation to cclnk.
Parameters:
lam external address
Returns:
void
Definition at line 404 of file esone.c.
References c, cam_interrupt_detach(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   cam_interrupt_detach(c, n);
}
INLINE void cdlam (int * lam, const int b, const int c, const int n, const int a, const int inta[2])
Control Declare LAM.
Declare LAM, Identical to cdreg.
Parameters:
lam external LAM address
b branch number (0..7)
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
inta implementation dependent
Returns:
void
Definition at line 324 of file esone.c.
Referenced by isr(), and main().
{
   /* inta[2] ignored */
   cdreg(lam, b, c, n, a);
}
INLINE void cdreg (int * ext, const int b, const int c, const int n, const int a)
Control Declaration REGister.
Compose an external address from BCNA for later use. Accessing CAMAC through ext could be faster if the external address is memory mapped to the processor (hardware dependent). Some CAMAC controller do not have this option see AppendixB.
Parameters:
ext external address
b branch number (0..7)
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
Returns:
void
Definition at line 122 of file esone.c.
{
   came_cn(ext, b, c, n, a);
}
INLINE void cfga (int f[], int exta[], int intc[], int qa[], int cb[])
Control Full (24bit) word General Action.
Parameters:
f function code
exta[] external address array
intc[] data array
qa[] Q response array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
Definition at line 480 of file esone.c.
{
   int i;
   for (i = 0; i < cb[0]; i++)
      cfsa(f[i], exta[i], (unsigned long *) (&(intc[i])), &(qa[i]));
   cb[1] = cb[0];
}
INLINE void cfmad (int f, int extb[], int intc[], int cb[])
Control Full (24bit) Address Q scan.
Scan all sub-address while Q=1 from a0..a15 max from address extb[0] and store corresponding data in intc[]. If Q=0 while A<15 or A=15 then cross station boundary is applied (n-> n+1) and sub-address is reset (a=0). Perform action until either cb[0] action are performed or current external address exceeds extb[1].
implementation of cb[2] for LAM recognition is not implemented.
Parameters:
f function code
extb[] external address array
extb[0] : first valid external address
extb[1] : last valid external address
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
Definition at line 534 of file esone.c.
{
   int j, count;
   int x, q, b, c, n, a;
   unsigned long exts, extc, exte;
   exts = extb[0];
   exte = extb[1];
   count = cb[0];
   j = 0;
   came_ext(exts, &b, &c, &n, &a);
   do {
      cam24i_q(c, n, a, f, (unsigned long *) &intc[j], &x, &q);
      if (q == 0) {
         a = 0;                 /* set subaddress to zero */
         n++;                   /* select next slot */
         j++;
      } else {
         a++;                   /* increment address */
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
      came_cn((int *) &extc, b, c, n, a);
      if (extc > exte)
         count = 0;             /* force exit */
   } while (count);
}
INLINE void cfsa (const int f, const int ext, unsigned long * d, int * q)
Control Full Operation.
24 bit operation on a given external CAMAC address.
The range of the f is hardware dependent. The number indicated below are for standard ANSI/IEEE Std (758-1979) Execute cam24i for f<8, cam24o for f>15, camc_q for (f>7 or f>23)
Parameters:
f function code (0..31)
ext external address
d data long word
q Q response
Returns:
void
Definition at line 178 of file esone.c.
{
   int b, c, n, a, x;
   if (f < 8) {
      /* read */
      came_ext(ext, &b, &c, &n, &a);
      cam24i_q(c, n, a, f, d, &x, q);
   } else if (f > 15) {
      /* write */
      came_ext(ext, &b, &c, &n, &a);
      cam24o_q(c, n, a, f, *d, &x, q);
   } else if ((f > 7) || (f > 23)) {
      /* command */
      came_ext(ext, &b, &c, &n, &a);
      camc_q(c, n, a, f, q);
   }
}
INLINE void cfubc (const int f, int ext, int intc[], int cb[])
Control Full (24bit) Block Repeat with Q-stop.
Execute function f on address ext with data intc[] while Q.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
Definition at line 631 of file esone.c.
{
   int count, q;
   count = cb[0];
   do {
      cfsa(f, ext, (unsigned long *) intc, &q);
      if (q == 0)
         count = 0;             /* stop on no q */
      else {
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
   } while (count);
}
INLINE void cfubr (const int f, int ext, int intc[], int cb[])
Repeat Mode Block Transfer (24bit).
Execute function f on address ext with data intc[] if Q. If noQ keep current intc[] data. Repeat cb[0] times.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
Definition at line 694 of file esone.c.
{
   int q, count;
   count = cb[0];
   do {
      do {
         cfsa(f, ext, (unsigned long *) intc, &q);
      } while (q == 0);
      ++cb[1];                  /* increment tally count */
      ++intc;                   /* next data array */
      --count;
   } while (count);
}
INLINE void csga (int f[], int exta[], int intc[], int qa[], int cb[])
Control (16bit) word General Action.
Parameters:
f function code
exta[] external address array
intc[] data array
qa[] Q response array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
Definition at line 503 of file esone.c.
{
   int i;
   for (i = 0; i < cb[0]; i++)
      cssa(f[i], exta[i], (unsigned short *) (&(intc[i])), &(qa[i]));
   cb[1] = cb[0];
}
INLINE void csmad (int f, int extb[], int intc[], int cb[])
Control (16bit) Address Q scan.
Scan all sub-address while Q=1 from a0..a15 max from address extb[0] and store corresponding data in intc[]. If Q=0 while A<15 or A=15 then cross station boundary is applied (n-> n+1) and sub-address is reset (a=0). Perform action until either cb[0] action are performed or current external address exceeds extb[1].
implementation of cb[2] for LAM recognition is not implemented.
Parameters:
f function code
extb[] external address array
extb[0] : first valid external address
extb[1] : last valid external address
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
Definition at line 586 of file esone.c.
{
   int j, count;
   int x, q, b, c, n, a;
   unsigned long exts, extc, exte;
   exts = extb[0];
   exte = extb[1];
   count = cb[0];
   j = 0;
   came_ext(exts, &b, &c, &n, &a);
   do {
      cam16i_q(c, n, a, f, (unsigned short *) &intc[j], &x, &q);
      if (q == 0) {
         a = 0;                 /* set subaddress to zero */
         n++;                   /* select next slot */
         j++;
      } else {
         a++;                   /* increment address */
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
      came_cn((int *) &extc, b, c, n, a);
      if (extc > exte)
         count = 0;             /* force exit */
   } while (count);
}
INLINE void cssa (const int f, int ext, unsigned short * d, int * q)
Control Short Operation.
16 bit operation on a given external CAMAC address.
The range of the f is hardware dependent. The number indicated below are for standard ANSI/IEEE Std (758-1979) Execute cam16i for f<8, cam16o for f>15, camc_q for (f>7 or f>23)
Parameters:
f function code (0..31)
ext external address
d data word
q Q response
Returns:
void
Definition at line 143 of file esone.c.
{
   int b, c, n, a, x;
   if (f < 8) {
      /* read */
      came_ext(ext, &b, &c, &n, &a);
      cam16i_q(c, n, a, f, d, &x, q);
   } else if (f > 15) {
      /* write */
      came_ext(ext, &b, &c, &n, &a);
      cam16o_q(c, n, a, f, *d, &x, q);
   } else if ((f > 7) || (f > 23)) {
      /* command */
      came_ext(ext, &b, &c, &n, &a);
      camc_q(c, n, a, f, q);
   }
}
INLINE void csubc (const int f, int ext, int intc[], int cb[])
Control (16bit) Block Repeat with Q-stop.
Execute function f on address ext with data intc[] while Q.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
Definition at line 662 of file esone.c.
{
   int count, q;
   count = cb[0];
   do {
      cssa(f, ext, (unsigned short *) intc, &q);
      if (q == 0)
         count = 0;             /* stop on no q */
      else {
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
   } while (count);
}
INLINE void csubr (const int f, int ext, int intc[], int cb[])
Repeat Mode Block Transfer (16bit).
Execute function f on address ext with data intc[] if Q. If noQ keep current intc[] data. Repeat cb[0] times.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array
cb[0] : number of function to perform
cb[1] : returned number of function performed
Returns:
void
Definition at line 725 of file esone.c.
{
   int q, count;
   count = cb[0];
   do {
      do {
         cssa(f, ext, (unsigned short *) intc, &q);
      } while (q == 0);
      ++cb[1];                  /* increment tally count */
      ++intc;                   /* next data array */
      --count;
   } while (count);
}
INLINE void ctcd (const int ext, int * l)
Control Test Crate D.
Test Crate Demand.
Parameters:
ext external address
l D cleared -> l=0, D set -> l=1
Returns:
void
Definition at line 302 of file esone.c.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   *l = cam_interrupt_test(c);
}
INLINE void ctci (const int ext, int * l)
Test Crate I.
Test Crate Inhibit, Execute cam_inhibit_test()
Parameters:
ext external address
l action l=0 -> Clear I, l=1 -> Set I
Returns:
void
Definition at line 262 of file esone.c.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   *l = cam_inhibit_test(c);
}
INLINE void ctgl (const int ext, int * l)
Control Test Demand Present.
Test the LAM register.
Parameters:
ext external LAM register address
l l !=0 if any LAM is set.
Returns:
void
Definition at line 341 of file esone.c.
{
   int b, c, n, a;
   unsigned long lam;
   came_ext(ext, &b, &c, &n, &a);
   cam_lam_read(c, &lam);
   *l = (lam > 0);
}
INLINE void ctlm (const int lam, int * l)
Test LAM.
Test the LAM of the station pointed by lam. Performs an F8
Parameters:
lam external address
l No LAM-> l=0, LAM present-> l=1
Returns:
void
Definition at line 459 of file esone.c.
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   camc_q(c, n, a, 8, l);
}
INLINE int fccinit (void)
CAMAC initialization with return status
fccinit can be called instead of ccinit to determine if the initialization was successful
Returns:
1 for success, 0 for failure
Definition at line 99 of file esone.c.
References cam_init(), and SUCCESS.
Referenced by main().
{
   if (cam_init() == SUCCESS)
      return 1;
   return 0;
}