AlcapDAQ:Rootana: midas/examples/epics/caerr.h File Reference
midas/examples/epics/caerr.h File Reference
#include "shareLib.h"
#include "epicsTypes.h"
Defines
#define CA_K_INFO 3
#define CA_K_ERROR 2
#define CA_K_SUCCESS 1
#define CA_K_WARNING 0
#define CA_K_SEVERE 4
#define CA_K_FATAL CA_K_ERROR | CA_K_SEVERE
#define CA_M_MSG_NO 0x0000FFF8
#define CA_M_SEVERITY 0x00000007
#define CA_M_LEVEL 0x00000003
#define CA_M_SUCCESS 0x00000001
#define CA_M_ERROR 0x00000002
#define CA_M_SEVERE 0x00000004
#define CA_S_MSG_NO 0x0D
#define CA_S_SEVERITY 0x03
#define CA_V_MSG_NO 0x03
#define CA_V_SEVERITY 0x00
#define CA_V_SUCCESS 0x00
#define CA_EXTRACT_MSG_NO(code) (((code) & CA_M_MSG_NO) >> CA_V_MSG_NO)
#define CA_EXTRACT_SEVERITY(code) (((code) & CA_M_SEVERITY) >> CA_V_SEVERITY)
#define CA_EXTRACT_SUCCESS(code) (((code) & CA_M_SUCCESS) >> CA_V_SUCCESS)
#define CA_INSERT_MSG_NO(code) (((code)<< CA_V_MSG_NO) & CA_M_MSG_NO)
#define CA_INSERT_SEVERITY(code) (((code)<< CA_V_SEVERITY)& CA_M_SEVERITY)
#define CA_INSERT_SUCCESS(code) (((code)<< CA_V_SUCCESS) & CA_M_SUCCESS)
#define DEFMSG(SEVERITY, NUMBER) (CA_INSERT_MSG_NO(NUMBER) | CA_INSERT_SEVERITY(SEVERITY))
#define ECA_NORMAL DEFMSG(CA_K_SUCCESS, 0)
#define ECA_MAXIOC DEFMSG(CA_K_ERROR, 1)
#define ECA_UKNHOST DEFMSG(CA_K_ERROR, 2)
#define ECA_UKNSERV DEFMSG(CA_K_ERROR, 3)
#define ECA_SOCK DEFMSG(CA_K_ERROR, 4)
#define ECA_CONN DEFMSG(CA_K_WARNING, 5)
#define ECA_ALLOCMEM DEFMSG(CA_K_WARNING, 6)
#define ECA_UKNCHAN DEFMSG(CA_K_WARNING, 7)
#define ECA_UKNFIELD DEFMSG(CA_K_WARNING, 8)
#define ECA_TOLARGE DEFMSG(CA_K_ERROR, 9)
#define ECA_TIMEOUT DEFMSG(CA_K_WARNING, 10)
#define ECA_NOSUPPORT DEFMSG(CA_K_WARNING, 11)
#define ECA_STRTOBIG DEFMSG(CA_K_WARNING, 12)
#define ECA_DISCONNCHID DEFMSG(CA_K_ERROR, 13)
#define ECA_BADTYPE DEFMSG(CA_K_ERROR, 14)
#define ECA_CHIDNOTFND DEFMSG(CA_K_INFO, 15)
#define ECA_CHIDRETRY DEFMSG(CA_K_INFO, 16)
#define ECA_INTERNAL DEFMSG(CA_K_FATAL, 17)
#define ECA_DBLCLFAIL DEFMSG(CA_K_WARNING, 18)
#define ECA_GETFAIL DEFMSG(CA_K_WARNING, 19)
#define ECA_PUTFAIL DEFMSG(CA_K_WARNING, 20)
#define ECA_ADDFAIL DEFMSG(CA_K_WARNING, 21)
#define ECA_BADCOUNT DEFMSG(CA_K_WARNING, 22)
#define ECA_BADSTR DEFMSG(CA_K_ERROR, 23)
#define ECA_DISCONN DEFMSG(CA_K_WARNING, 24)
#define ECA_DBLCHNL DEFMSG(CA_K_WARNING, 25)
#define ECA_EVDISALLOW DEFMSG(CA_K_ERROR, 26)
#define ECA_BUILDGET DEFMSG(CA_K_WARNING, 27)
#define ECA_NEEDSFP DEFMSG(CA_K_WARNING, 28)
#define ECA_OVEVFAIL DEFMSG(CA_K_WARNING, 29)
#define ECA_BADMONID DEFMSG(CA_K_ERROR, 30)
#define ECA_NEWADDR DEFMSG(CA_K_WARNING, 31)
#define ECA_NEWCONN DEFMSG(CA_K_INFO, 32)
#define ECA_NOCACTX DEFMSG(CA_K_WARNING, 33)
#define ECA_DEFUNCT DEFMSG(CA_K_FATAL, 34)
#define ECA_EMPTYSTR DEFMSG(CA_K_WARNING, 35)
#define ECA_NOREPEATER DEFMSG(CA_K_WARNING, 36)
#define ECA_NOCHANMSG DEFMSG(CA_K_WARNNING, 37)
#define ECA_DLCKREST DEFMSG(CA_K_WARNING, 38)
#define ECA_SERVBEHIND DEFMSG(CA_K_WARNING, 39)
#define ECA_NOCAST DEFMSG(CA_K_WARNING, 40)
#define ECA_BADMASK DEFMSG(CA_K_ERROR, 41)
#define ECA_IODONE DEFMSG(CA_K_INFO, 42)
#define ECA_IOINPROGRESS DEFMSG(CA_K_INFO, 43)
#define ECA_BADSYNCGRP DEFMSG(CA_K_ERROR, 44)
#define ECA_PUTCBINPROG DEFMSG(CA_K_ERROR, 45)
#define ECA_NORDACCESS DEFMSG(CA_K_WARNING, 46)
#define ECA_NOWTACCESS DEFMSG(CA_K_WARNING, 47)
#define ECA_ANACHRONISM DEFMSG(CA_K_ERROR, 48)
#define ECA_NOSEARCHADDR DEFMSG(CA_K_WARNING, 49)
#define ECA_NOCONVERT DEFMSG(CA_K_WARNING, 50)
#define ECA_BADCHID DEFMSG(CA_K_ERROR, 51)
#define ECA_BADFUNCPTR DEFMSG(CA_K_ERROR, 52)
Functions
READONLY char * ca_message ()
Variables
epicsShareExtern READONLY char * ca_message_text []
Define Documentation
#define CA_EXTRACT_MSG_NO (code) (((code) & CA_M_MSG_NO) >> CA_V_MSG_NO)
Definition at line 77 of file caerr.h.
#define CA_EXTRACT_SEVERITY (code) (((code) & CA_M_SEVERITY) >> CA_V_SEVERITY)
Definition at line 79 of file caerr.h.
#define CA_EXTRACT_SUCCESS (code) (((code) & CA_M_SUCCESS) >> CA_V_SUCCESS)
Definition at line 81 of file caerr.h.
#define CA_INSERT_MSG_NO (code) (((code)<< CA_V_MSG_NO) & CA_M_MSG_NO)
Definition at line 83 of file caerr.h.
#define CA_INSERT_SEVERITY (code) (((code)<< CA_V_SEVERITY)& CA_M_SEVERITY)
Definition at line 85 of file caerr.h.
#define CA_INSERT_SUCCESS (code) (((code)<< CA_V_SUCCESS) & CA_M_SUCCESS)
Definition at line 87 of file caerr.h.
#define CA_K_ERROR 2
Definition at line 60 of file caerr.h.
#define CA_K_FATAL CA_K_ERROR | CA_K_SEVERE
Definition at line 64 of file caerr.h.
#define CA_K_INFO 3
Definition at line 59 of file caerr.h.
#define CA_K_SEVERE 4
Definition at line 63 of file caerr.h.
#define CA_K_SUCCESS 1
Definition at line 61 of file caerr.h.
#define CA_K_WARNING 0
Definition at line 62 of file caerr.h.
#define CA_M_ERROR 0x00000002
Definition at line 69 of file caerr.h.
#define CA_M_LEVEL 0x00000003
Definition at line 67 of file caerr.h.
#define CA_M_MSG_NO 0x0000FFF8
Definition at line 65 of file caerr.h.
#define CA_M_SEVERE 0x00000004
Definition at line 70 of file caerr.h.
#define CA_M_SEVERITY 0x00000007
Definition at line 66 of file caerr.h.
#define CA_M_SUCCESS 0x00000001
Definition at line 68 of file caerr.h.
Referenced by epics_ca_init().
#define CA_S_MSG_NO 0x0D
Definition at line 71 of file caerr.h.
#define CA_S_SEVERITY 0x03
Definition at line 72 of file caerr.h.
#define CA_V_MSG_NO 0x03
Definition at line 73 of file caerr.h.
#define CA_V_SEVERITY 0x00
Definition at line 74 of file caerr.h.
#define CA_V_SUCCESS 0x00
Definition at line 75 of file caerr.h.
#define DEFMSG (SEVERITY, NUMBER) (CA_INSERT_MSG_NO(NUMBER) | CA_INSERT_SEVERITY(SEVERITY))
Definition at line 89 of file caerr.h.
#define ECA_ADDFAIL DEFMSG(CA_K_WARNING, 21)
Definition at line 112 of file caerr.h.
#define ECA_ALLOCMEM DEFMSG(CA_K_WARNING, 6)
Definition at line 97 of file caerr.h.
#define ECA_ANACHRONISM DEFMSG(CA_K_ERROR, 48)
Definition at line 139 of file caerr.h.
#define ECA_BADCHID DEFMSG(CA_K_ERROR, 51)
Definition at line 142 of file caerr.h.
#define ECA_BADCOUNT DEFMSG(CA_K_WARNING, 22)
Definition at line 113 of file caerr.h.
#define ECA_BADFUNCPTR DEFMSG(CA_K_ERROR, 52)
Definition at line 143 of file caerr.h.
#define ECA_BADMASK DEFMSG(CA_K_ERROR, 41)
Definition at line 132 of file caerr.h.
#define ECA_BADMONID DEFMSG(CA_K_ERROR, 30)
Definition at line 121 of file caerr.h.
#define ECA_BADSTR DEFMSG(CA_K_ERROR, 23)
Definition at line 114 of file caerr.h.
#define ECA_BADSYNCGRP DEFMSG(CA_K_ERROR, 44)
Definition at line 135 of file caerr.h.
#define ECA_BADTYPE DEFMSG(CA_K_ERROR, 14)
Definition at line 105 of file caerr.h.
#define ECA_BUILDGET DEFMSG(CA_K_WARNING, 27)
Definition at line 118 of file caerr.h.
#define ECA_CHIDNOTFND DEFMSG(CA_K_INFO, 15)
Definition at line 106 of file caerr.h.
#define ECA_CHIDRETRY DEFMSG(CA_K_INFO, 16)
Definition at line 107 of file caerr.h.
#define ECA_CONN DEFMSG(CA_K_WARNING, 5)
Definition at line 96 of file caerr.h.
#define ECA_DBLCHNL DEFMSG(CA_K_WARNING, 25)
Definition at line 116 of file caerr.h.
#define ECA_DBLCLFAIL DEFMSG(CA_K_WARNING, 18)
Definition at line 109 of file caerr.h.
#define ECA_DEFUNCT DEFMSG(CA_K_FATAL, 34)
Definition at line 125 of file caerr.h.
#define ECA_DISCONN DEFMSG(CA_K_WARNING, 24)
Definition at line 115 of file caerr.h.
#define ECA_DISCONNCHID DEFMSG(CA_K_ERROR, 13)
Definition at line 104 of file caerr.h.
#define ECA_DLCKREST DEFMSG(CA_K_WARNING, 38)
Definition at line 129 of file caerr.h.
#define ECA_EMPTYSTR DEFMSG(CA_K_WARNING, 35)
Definition at line 126 of file caerr.h.
#define ECA_EVDISALLOW DEFMSG(CA_K_ERROR, 26)
Definition at line 117 of file caerr.h.
#define ECA_GETFAIL DEFMSG(CA_K_WARNING, 19)
Definition at line 110 of file caerr.h.
#define ECA_INTERNAL DEFMSG(CA_K_FATAL, 17)
Definition at line 108 of file caerr.h.
#define ECA_IODONE DEFMSG(CA_K_INFO, 42)
Definition at line 133 of file caerr.h.
#define ECA_IOINPROGRESS DEFMSG(CA_K_INFO, 43)
Definition at line 134 of file caerr.h.
#define ECA_MAXIOC DEFMSG(CA_K_ERROR, 1)
Definition at line 92 of file caerr.h.
#define ECA_NEEDSFP DEFMSG(CA_K_WARNING, 28)
Definition at line 119 of file caerr.h.
#define ECA_NEWADDR DEFMSG(CA_K_WARNING, 31)
Definition at line 122 of file caerr.h.
#define ECA_NEWCONN DEFMSG(CA_K_INFO, 32)
Definition at line 123 of file caerr.h.
#define ECA_NOCACTX DEFMSG(CA_K_WARNING, 33)
Definition at line 124 of file caerr.h.
#define ECA_NOCAST DEFMSG(CA_K_WARNING, 40)
Definition at line 131 of file caerr.h.
#define ECA_NOCHANMSG DEFMSG(CA_K_WARNNING, 37)
Definition at line 128 of file caerr.h.
#define ECA_NOCONVERT DEFMSG(CA_K_WARNING, 50)
Definition at line 141 of file caerr.h.
#define ECA_NORDACCESS DEFMSG(CA_K_WARNING, 46)
Definition at line 137 of file caerr.h.
#define ECA_NOREPEATER DEFMSG(CA_K_WARNING, 36)
Definition at line 127 of file caerr.h.
#define ECA_NORMAL DEFMSG(CA_K_SUCCESS, 0)
Definition at line 91 of file caerr.h.
Referenced by epics_ca_connection_handler(), epics_ca_event_handler(), epics_ca_exit(), epics_ca_init(), and epics_ca_set_label().
#define ECA_NOSEARCHADDR DEFMSG(CA_K_WARNING, 49)
Definition at line 140 of file caerr.h.
#define ECA_NOSUPPORT DEFMSG(CA_K_WARNING, 11)
Definition at line 102 of file caerr.h.
#define ECA_NOWTACCESS DEFMSG(CA_K_WARNING, 47)
Definition at line 138 of file caerr.h.
#define ECA_OVEVFAIL DEFMSG(CA_K_WARNING, 29)
Definition at line 120 of file caerr.h.
#define ECA_PUTCBINPROG DEFMSG(CA_K_ERROR, 45)
Definition at line 136 of file caerr.h.
#define ECA_PUTFAIL DEFMSG(CA_K_WARNING, 20)
Definition at line 111 of file caerr.h.
#define ECA_SERVBEHIND DEFMSG(CA_K_WARNING, 39)
Definition at line 130 of file caerr.h.
#define ECA_SOCK DEFMSG(CA_K_ERROR, 4)
Definition at line 95 of file caerr.h.
#define ECA_STRTOBIG DEFMSG(CA_K_WARNING, 12)
Definition at line 103 of file caerr.h.
#define ECA_TIMEOUT DEFMSG(CA_K_WARNING, 10)
Definition at line 101 of file caerr.h.
Referenced by epics_ca_init().
#define ECA_TOLARGE DEFMSG(CA_K_ERROR, 9)
Definition at line 100 of file caerr.h.
#define ECA_UKNCHAN DEFMSG(CA_K_WARNING, 7)
Definition at line 98 of file caerr.h.
#define ECA_UKNFIELD DEFMSG(CA_K_WARNING, 8)
Definition at line 99 of file caerr.h.
#define ECA_UKNHOST DEFMSG(CA_K_ERROR, 2)
Definition at line 93 of file caerr.h.
#define ECA_UKNSERV DEFMSG(CA_K_ERROR, 3)
Definition at line 94 of file caerr.h.
Function Documentation
READONLY char* ca_message ()
Referenced by epics_ca_connection_handler(), epics_ca_event_handler(), epics_ca_exit(), epics_ca_get(), epics_ca_init(), epics_ca_set(), epics_ca_set_all(), and epics_ca_set_label().
Variable Documentation
epicsShareExtern READONLY char* ca_message_text[]
Definition at line 145 of file caerr.h.