AlcapDAQ:Rootana: midas/drivers/kernel/khyt1331/camactest.c File Reference
midas/drivers/kernel/khyt1331/camactest.c File Reference
#include <stdio.h>
#include "mcstd.h"
Functions
void isr (void)
main ()
Function Documentation
void isr (void)
Definition at line 4 of file camactest.c.
References cam16o(), cam_interrupt_enable(), cam_lam_clear(), and camc().
{
   /* toggle output so one can measure interrupt response time */
   cam16o(0, 1, 0, 16, 0xFF);
   cam16o(0, 1, 0, 16, 0);
   /* clear lam in unit and controller */
   camc(0, 1, 0, 10);
   cam_lam_clear(0, 1);
   /* re-enable crate demand */
   cam_interrupt_enable(0);
   printf("ISR\n");
}
main (void)
Definition at line 20 of file camactest.c.
References cam24i(), cam24o(), cam_crate_zinit(), cam_inhibit_clear(), cam_init(), cam_interrupt_attach(), cam_interrupt_enable(), cam_lam_clear(), cam_lam_enable(), camc(), d, and isr.
{
   unsigned long d;
   /* initialize CAMAC */
   if (cam_init() < 0)
      return;
   /* crate zero and remove inhibit */
   cam_crate_zinit(0);
   cam_inhibit_clear(0);
   /* write data and read back */
   cam24o(0, 1, 0, 16, 0x123456);
   cam24i(0, 1, 0, 0, &d);
   printf("Read back %X, should be 123456\n", d);
   /* enable and clear LAM in unit */
   camc(0, 1, 0, 26);
   camc(0, 1, 0, 10);
   /* register service routine */
   cam_lam_enable(0, 1);
   cam_lam_clear(0, 1);
   cam_interrupt_attach(0, 1, isr);
   /* enable crate demand */
   cam_interrupt_enable(0);
   /* go into endless loop */
   while (1);
}