AlcapDAQ:Rootana: midas/drivers/bus/cc7700pci.c File Reference
midas/drivers/bus/cc7700pci.c File Reference
#include <stdio.h>
#include "mcstd.h"
Defines
#define INLINE
#define CONTROL_KEPT_BIT_MASK (0x04 | 0x08 | 0x80)
#define STATUS_BIT_MASK 0x00ff
Enumerations
enum cc7700_regs {
regCONTROL = 0x00, regSTATUS = 0x00, regCOMMAND = 0x04, regLAM = 0x04,
regDATA = 0x08, regGO = 0x0C
}
enum cc7700_ctrlbits {
ctrlCLEAR = 0x01, ctrlINITIALIZE = 0x02, ctrlINHIBIT = 0x04, ctrlENABLEINTERRUPT = 0x08,
ctrlRESET = 0x40, ctrlLAMINTERNAL = 0x80
}
enum cc7700_statbits {
statNOQ = 0x01, statNOX = 0x02, statINHIBIT = 0x04, statENABLEINTERRUPT = 0x08,
statDONE = 0x10, statONLINE = 0x20, statLAMSUM = 0x40, statLAMINTERNAL = 0x80
}
Functions
int wait_done ()
INLINE void cam8i (const int c, const int n, const int a, const int f, unsigned char *d)
INLINE void cami (const int c, const int n, const int a, const int f, unsigned short *d)
INLINE void cam16i (const int c, const int n, const int a, const int f, unsigned short *d)
INLINE void cam24i (const int c, const int n, const int a, const int f, DWORD *d)
INLINE void cam8i_q (const int c, const int n, const int a, const int f, unsigned char *d, int *x, int *q)
INLINE void cam16i_q (const int c, const int n, const int a, const int f, unsigned short *d, int *x, int *q)
INLINE void cam24i_q (const int c, const int n, const int a, const int f, DWORD *d, int *x, int *q)
INLINE void cam16i_r (const int c, const int n, const int a, const int f, unsigned short **d, const int r)
INLINE void cam24i_r (const int c, const int n, const int a, const int f, DWORD **d, const int r)
INLINE void cam16i_rq (const int c, const int n, const int a, const int f, unsigned short **d, const int r)
INLINE void cam24i_rq (const int c, const int n, const int a, const int f, DWORD **d, const int r)
INLINE void cam16i_sa (const int c, const int n, const int a, const int f, unsigned short **d, const int r)
INLINE void cam24i_sa (const int c, const int n, const int a, const int f, DWORD **d, const int r)
INLINE void cam16i_sn (const int c, const int n, const int a, const int f, unsigned short **d, const int r)
INLINE void cam24i_sn (const int c, const int n, const int a, const int f, DWORD **d, const int r)
INLINE void cam8o (const int c, const int n, const int a, const int f, unsigned char d)
INLINE void camo (const int c, const int n, const int a, const int f, unsigned short d)
INLINE void cam16o (const int c, const int n, const int a, const int f, unsigned short d)
INLINE void cam24o (const int c, const int n, const int a, const int f, DWORD d)
INLINE void cam16o_q (const int c, const int n, const int a, const int f, unsigned short d, int *x, int *q)
INLINE void cam24o_q (const int c, const int n, const int a, const int f, DWORD d, int *x, int *q)
INLINE void cam8o_r (const int c, const int n, const int a, const int f, BYTE *d, const int r)
INLINE void cam16o_r (const int c, const int n, const int a, const int f, unsigned short *d, const int r)
INLINE void cam24o_r (const int c, const int n, const int a, const int f, DWORD *d, const int r)
INLINE int camc_chk (const int c)
INLINE void camc (const int c, const int n, const int a, const int f)
INLINE void camc_q (const int c, const int n, const int a, const int f, int *q)
INLINE void camc_sa (const int c, const int n, const int a, const int f, const int r)
INLINE void camc_sn (const int c, const int n, const int a, const int f, const int r)
INLINE int cam_init (void)
INLINE void cam_exit (void)
INLINE void cam_inhibit_set (const int c)
INLINE void cam_inhibit_clear (const int c)
INLINE void cam_crate_clear (const int c)
INLINE void cam_crate_zinit (const int c)
INLINE void cam_lam_enable (const int c, const int n)
INLINE void cam_lam_disable (const int c, const int n)
INLINE void cam_lam_read (const int c, DWORD *lam)
INLINE void cam_lam_clear (const int c, const int n)
INLINE void cam_interrupt_enable (const int c)
INLINE void cam_interrupt_disable (const int c)
INLINE void cam_interrupt_attach (const int c, const int n, void(*isr)(void))
INLINE void cam_interrupt_detach (const int c, const int n)
INLINE int cam_init_rpc (char *host_name, char *exp_name, char *fe_name, char *client_name, char *rpc_server)
Variables
static unsigned int iobase
static void(* old_handler)(void) = (void *) 0
Define Documentation
#define CONTROL_KEPT_BIT_MASK (0x04 | 0x08 | 0x80)
Definition at line 115 of file cc7700pci.c.
Referenced by cam_crate_clear(), cam_crate_zinit(), cam_inhibit_clear(), cam_inhibit_set(), cam_lam_disable(), and cam_lam_enable().
#define INLINE
Definition at line 77 of file cc7700pci.c.
#define STATUS_BIT_MASK 0x00ff
Definition at line 116 of file cc7700pci.c.
Enumeration Type Documentation
enum cc7700_ctrlbits
Enumerator:
ctrlCLEAR
ctrlINITIALIZE
ctrlINHIBIT
ctrlENABLEINTERRUPT
ctrlRESET
ctrlLAMINTERNAL
Definition at line 95 of file cc7700pci.c.
                     {
   ctrlCLEAR = 0x01,
   ctrlINITIALIZE = 0x02,
   ctrlINHIBIT = 0x04,
   ctrlENABLEINTERRUPT = 0x08,
   ctrlRESET = 0x40,
   ctrlLAMINTERNAL = 0x80
};
enum cc7700_regs
Enumerator:
regCONTROL
regSTATUS
regCOMMAND
regLAM
regDATA
regGO
Definition at line 86 of file cc7700pci.c.
                 {
   regCONTROL = 0x00,
   regSTATUS = 0x00,
   regCOMMAND = 0x04,
   regLAM = 0x04,
   regDATA = 0x08,
   regGO = 0x0C
};
enum cc7700_statbits
Enumerator:
statNOQ
statNOX
statINHIBIT
statENABLEINTERRUPT
statDONE
statONLINE
statLAMSUM
statLAMINTERNAL
Definition at line 104 of file cc7700pci.c.
                     {
   statNOQ = 0x01,
   statNOX = 0x02,
   statINHIBIT = 0x04,
   statENABLEINTERRUPT = 0x08,
   statDONE = 0x10,
   statONLINE = 0x20,
   statLAMSUM = 0x40,
   statLAMINTERNAL = 0x80
};
Function Documentation
INLINE void cam16i (const int c, const int n, const int a, const int f, unsigned short * d)
Definition at line 161 of file cc7700pci.c.
References cami().
{
   cami(c, n, a, f, d);
}
INLINE void cam16i_q (const int c, const int n, const int a, const int f, unsigned short * d, int * x, int * q)
Definition at line 200 of file cc7700pci.c.
References INPW, iobase, OUTPW, regCOMMAND, regDATA, regGO, status, and wait_done().
{
   WORD status;
   OUTPL(iobase + regCOMMAND, ((c & 0x7) << 16) |
         (((n - 1) & 0x1F) << 9) | ((a & 0xF) << 5) | (f & 0x1F));
   OUTPW(iobase + regGO, 0);
   status = wait_done();
   *d = INPW(iobase + regDATA);
   *q = ((status & 1) == 0);
   *x = ((status & 2) == 0);
}
INLINE void cam16i_r (const int c, const int n, const int a, const int f, unsigned short ** d, const int r)
Definition at line 237 of file cc7700pci.c.
References cam16i(), and i.
{
   unsigned short i;
   for (i = 0; i < r; i++)
      cam16i(c, n, a, f, (*d)++);
}
INLINE void cam16i_rq (const int c, const int n, const int a, const int f, unsigned short ** d, const int r)
Definition at line 258 of file cc7700pci.c.
References cam16i_q(), and i.
{
   unsigned short i;
   int q, x;
   for (i = 0; i < r; i++) {
      cam16i_q(c, n, a, f, (*d)++, &x, &q);
      if (!q)
         break;
   }
}
INLINE void cam16i_sa (const int c, const int n, const int a, const int f, unsigned short ** d, const int r)
Definition at line 288 of file cc7700pci.c.
References cami(), and i.
{
   unsigned short i;
   for (i = 0; i < r; i++)
      cami(c, n, a + i, f, (*d)++);
}
INLINE void cam16i_sn (const int c, const int n, const int a, const int f, unsigned short ** d, const int r)
Definition at line 310 of file cc7700pci.c.
References cam16i(), and i.
{
   int i;
   for (i = 0; i < r; i++)
      cam16i(c, n + i, a, f, (*d)++);
}
INLINE void cam16o (const int c, const int n, const int a, const int f, unsigned short d)
Definition at line 358 of file cc7700pci.c.
References camo().
{
   camo(c, n, a, f, d);
}
INLINE void cam16o_q (const int c, const int n, const int a, const int f, unsigned short d, int * x, int * q)
Definition at line 378 of file cc7700pci.c.
References iobase, OUTPW, regCOMMAND, regDATA, regGO, status, and wait_done().
{
   int status;
   OUTPL(iobase + regCOMMAND, ((c & 0x7) << 16) |
         (((n - 1) & 0x1F) << 9) | ((a & 0xF) << 5) | (f & 0x1F));
   OUTPL(iobase + regDATA, d);
   OUTPW(iobase + regGO, 0);
   status = wait_done();
   *q = ((status & 1) == 0);
   *x = ((status & 2) == 0);
}
INLINE void cam16o_r (const int c, const int n, const int a, const int f, unsigned short * d, const int r)
Definition at line 427 of file cc7700pci.c.
References cam16o(), and i.
{
   unsigned short i;
   for (i = 0; i < r; i++)
      cam16o(c, n, a, f, *(d++));
}
INLINE void cami (const int c, const int n, const int a, const int f, unsigned short * d)
Definition at line 148 of file cc7700pci.c.
References INPW, iobase, OUTPW, regCOMMAND, regDATA, regGO, and wait_done().
{
   OUTPL(iobase + regCOMMAND, ((c & 0x7) << 16) |
         (((n - 1) & 0x1F) << 9) | ((a & 0xF) << 5) | (f & 0x1F));
   OUTPW(iobase + regGO, 0);
   wait_done();
   *d = INPW(iobase + regDATA);
}
INLINE void camo (const int c, const int n, const int a, const int f, unsigned short d)
Definition at line 345 of file cc7700pci.c.
References iobase, OUTPW, regCOMMAND, regDATA, regGO, and wait_done().
{
   OUTPL(iobase + regCOMMAND, ((c & 0x7) << 16) |
         (((n - 1) & 0x1F) << 9) | ((a & 0xF) << 5) | (f & 0x1F));
   OUTPW(iobase + regDATA, d);
   OUTPW(iobase + regGO, 0);
   wait_done();
}
int wait_done ()
Definition at line 120 of file cc7700pci.c.
References i, INP, iobase, regSTATUS, statDONE, and status.
Referenced by cam16i_q(), cam16o_q(), cam24i(), cam24i_q(), cam24o(), cam24o_q(), cam8i(), cam8i_q(), cam8o(), camc(), camc_q(), cami(), and camo().
{
   int i, status;
   for (i = 0; i < 100; i++) {
      status = INP(iobase + regSTATUS);
      if (status & statDONE)
         break;
   }
   return status;
}
Variable Documentation
unsigned int iobase [static]
Definition at line 82 of file cc7700pci.c.
Referenced by cam16i_q(), cam16o_q(), cam24i(), cam24i_q(), cam24o(), cam24o_q(), cam8i(), cam8i_q(), cam8o(), cam_crate_clear(), cam_crate_zinit(), cam_exit(), cam_inhibit_clear(), cam_inhibit_set(), cam_init(), cam_lam_disable(), cam_lam_enable(), cam_lam_read(), camc(), camc_chk(), camc_q(), cami(), camo(), and wait_done().
void(* old_handler)(void) = (void *) 0 [static]
Referenced by cam_interrupt_attach(), and cam_interrupt_detach().