AlcapDAQ:Rootana: HelpWindow Class Reference
HelpWindow Class Reference
#include <helpwindow.h>
Public Member Functions
HelpWindow (const QString &home_, const QString &path, QWidget *parent=0, const char *name=0)
~HelpWindow ()
Private Slots
void setBackwardAvailable (bool)
void setForwardAvailable (bool)
void textChanged ()
void about ()
void aboutQt ()
void openFile ()
void newWindow ()
void print ()
void pathSelected (const QString &)
void histChosen (int)
void bookmChosen (int)
void addBookmark ()
Private Member Functions
void readHistory ()
void readBookmarks ()
Private Attributes
QTextBrowser * browser
QComboBox * pathCombo
int backwardId
int forwardId
QString selectedURL
QStringList history
QStringList bookmarks
QMap< int, QString > mHistory
QMap< int, QString > mBookmarks
QPopupMenu * hist
QPopupMenu * bookm
Detailed Description
Definition at line 23 of file helpwindow.h.
Constructor & Destructor Documentation
HelpWindow::HelpWindow (const QString & home_, const QString & path, QWidget * parent = 0, const char * name = 0)
Definition at line 39 of file helpwindow.cpp.
References about(), aboutQt(), addBookmark(), backwardId, bookm, bookmarks, bookmChosen(), browser, FALSE, forwardId, hist, histChosen(), history, mBookmarks, message, mHistory, newWindow(), openFile(), pathCombo, pathSelected(), print(), readBookmarks(), readHistory(), setBackwardAvailable(), setForwardAvailable(), textChanged(), and TRUE.
Referenced by newWindow().
    : QMainWindow( parent, name, WDestructiveClose ),
      pathCombo( 0 ), selectedURL()
{
    readHistory();
    readBookmarks();
    browser = new QTextBrowser( this );
    browser->mimeSourceFactory()->setFilePath( _path );
    browser->setFrameStyle( QFrame::Panel | QFrame::Sunken );
    connect( browser, SIGNAL( textChanged() ),
             this, SLOT( textChanged() ) );
    setCentralWidget( browser );
    if ( !home_.isEmpty() )
        browser->setSource( home_ );
    connect( browser, SIGNAL( highlighted( const QString&) ),
             statusBar(), SLOT( message( const QString&)) );
    resize( 640,700 );
    QPopupMenu* file = new QPopupMenu( this );
    file->insertItem( tr("&New Window"), this, SLOT( newWindow() ), CTRL+Key_N );
    file->insertItem( tr("&Open File"), this, SLOT( openFile() ), CTRL+Key_O );
    file->insertItem( tr("&Print"), this, SLOT( print() ), CTRL+Key_P );
    file->insertSeparator();
    file->insertItem( tr("&Close"), this, SLOT( close() ), CTRL+Key_Q );
//as    file->insertItem(tr("E&xit"), qApp, SLOT(closeAllWindows()), CTRL+Key_X);
    // The same three icons are used twice each.
    QIconSet icon_back( QPixmap("help/back.xpm") );
    QIconSet icon_forward( QPixmap("help/forward.xpm") );
    QIconSet icon_home( QPixmap("help/home.xpm") );
    QPopupMenu* go = new QPopupMenu( this );
    backwardId = go->insertItem( icon_back,
                                 tr("&Backward"), browser, SLOT( backward() ),
                                 CTRL+Key_Left );
    forwardId = go->insertItem( icon_forward,
                                tr("&Forward"), browser, SLOT( forward() ),
                                CTRL+Key_Right );
    go->insertItem( icon_home, tr("&Home"), browser, SLOT( home() ) );
    QPopupMenu* help = new QPopupMenu( this );
    help->insertItem( tr("&About ..."), this, SLOT( about() ) );
    help->insertItem( tr("About &Qt ..."), this, SLOT( aboutQt() ) );
    hist = new QPopupMenu( this );
    QStringList::Iterator it = history.begin();
    for ( ; it != history.end(); ++it )
        mHistory[ hist->insertItem( *it ) ] = *it;
    connect( hist, SIGNAL( activated( int ) ),
             this, SLOT( histChosen( int ) ) );
    bookm = new QPopupMenu( this );
    bookm->insertItem( tr( "Add Bookmark" ), this, SLOT( addBookmark() ) );
    bookm->insertSeparator();
    QStringList::Iterator it2 = bookmarks.begin();
    for ( ; it2 != bookmarks.end(); ++it2 )
        mBookmarks[ bookm->insertItem( *it2 ) ] = *it2;
    connect( bookm, SIGNAL( activated( int ) ),
             this, SLOT( bookmChosen( int ) ) );
    menuBar()->insertItem( tr("&File"), file );
    menuBar()->insertItem( tr("&Go"), go );
    menuBar()->insertItem( tr( "History" ), hist );
    menuBar()->insertItem( tr( "Bookmarks" ), bookm );
    menuBar()->insertSeparator();
    menuBar()->insertItem( tr("&Help"), help );
    menuBar()->setItemEnabled( forwardId, FALSE);
    menuBar()->setItemEnabled( backwardId, FALSE);
    connect( browser, SIGNAL( backwardAvailable( bool ) ),
             this, SLOT( setBackwardAvailable( bool ) ) );
    connect( browser, SIGNAL( forwardAvailable( bool ) ),
             this, SLOT( setForwardAvailable( bool ) ) );
    QToolBar* toolbar = new QToolBar( this );
    addToolBar( toolbar, "Toolbar");
    QToolButton* button;
    button = new QToolButton( icon_back, tr("Backward"), "", browser, SLOT(backward()), toolbar );
    connect( browser, SIGNAL( backwardAvailable(bool) ), button, SLOT( setEnabled(bool) ) );
    button->setEnabled( FALSE );
    button = new QToolButton( icon_forward, tr("Forward"), "", browser, SLOT(forward()), toolbar );
    connect( browser, SIGNAL( forwardAvailable(bool) ), button, SLOT( setEnabled(bool) ) );
    button->setEnabled( FALSE );
    button = new QToolButton( icon_home, tr("Home"), "", browser, SLOT(home()), toolbar );
    toolbar->addSeparator();
    pathCombo = new QComboBox( TRUE, toolbar );
    connect( pathCombo, SIGNAL( activated( const QString & ) ),
             this, SLOT( pathSelected( const QString & ) ) );
    toolbar->setStretchableWidget( pathCombo );
    setRightJustification( TRUE );
    setDockEnabled( DockLeft, FALSE );
    setDockEnabled( DockRight, FALSE );
    pathCombo->insertItem( home_ );
    browser->setFocus();
}
HelpWindow::~HelpWindow ()
Definition at line 189 of file helpwindow.cpp.
References bookmarks, history, mBookmarks, and mHistory.
{
    history.clear();
    QMap<int, QString>::Iterator it = mHistory.begin();
    for ( ; it != mHistory.end(); ++it )
        history.append( *it );
    QFile f( QDir::currentDirPath() + "/.history" );
    f.open( IO_WriteOnly );
    QDataStream s( &f );
    s << history;
    f.close();
    bookmarks.clear();
    QMap<int, QString>::Iterator it2 = mBookmarks.begin();
    for ( ; it2 != mBookmarks.end(); ++it2 )
        bookmarks.append( *it2 );
    QFile f2( QDir::currentDirPath() + "/.bookmarks" );
    f2.open( IO_WriteOnly );
    QDataStream s2( &f2 );
    s2 << bookmarks;
    f2.close();
}
Member Function Documentation
void HelpWindow::about () [private, slot]
Definition at line 214 of file helpwindow.cpp.
Referenced by HelpWindow().
{
    QMessageBox::about( this, "HelpViewer Example",
                        "<p>This example implements a simple HTML help viewer "
                        "using Qt's rich text capabilities</p>"
                        "<p>It's just about 100 lines of C++ code, so don't expect too much :-)</p>"
                        );
}
void HelpWindow::aboutQt () [private, slot]
Definition at line 224 of file helpwindow.cpp.
Referenced by HelpWindow().
{
    QMessageBox::aboutQt( this, "QBrowser" );
}
void HelpWindow::addBookmark () [private, slot]
Definition at line 328 of file helpwindow.cpp.
References bookm, browser, and mBookmarks.
Referenced by HelpWindow().
{
    mBookmarks[ bookm->insertItem( caption() ) ] = browser->context();
}
void HelpWindow::bookmChosen (int i) [private, slot]
Definition at line 322 of file helpwindow.cpp.
References browser, and mBookmarks.
Referenced by HelpWindow().
{
    if ( mBookmarks.contains( i ) )
        browser->setSource( mBookmarks[ i ] );
}
void HelpWindow::histChosen (int i) [private, slot]
Definition at line 316 of file helpwindow.cpp.
References browser, and mHistory.
Referenced by HelpWindow().
{
    if ( mHistory.contains( i ) )
        browser->setSource( mHistory[ i ] );
}
void HelpWindow::newWindow () [private, slot]
Definition at line 238 of file helpwindow.cpp.
References browser, and HelpWindow().
Referenced by HelpWindow().
{
    ( new HelpWindow(browser->source(), "qbrowser") )->show();
}
void HelpWindow::openFile () [private, slot]
Definition at line 229 of file helpwindow.cpp.
References browser, and null().
Referenced by HelpWindow().
{
#ifndef QT_NO_FILEDIALOG
    QString fn = QFileDialog::getOpenFileName( QString::null, QString::null, this );
    if ( !fn.isEmpty() )
        browser->setSource( fn );
#endif
}
void HelpWindow::pathSelected (const QString & _path) [private, slot]
Definition at line 277 of file helpwindow.cpp.
References browser, FALSE, hist, mHistory, and TRUE.
Referenced by HelpWindow().
{
    browser->setSource( _path );
    QMap<int, QString>::Iterator it = mHistory.begin();
    bool exists = FALSE;
    for ( ; it != mHistory.end(); ++it ) {
        if ( *it == _path ) {
            exists = TRUE;
            break;
        }
    }
    if ( !exists )
        mHistory[ hist->insertItem( _path ) ] = _path;
}
void HelpWindow::print () [private, slot]
Definition at line 243 of file helpwindow.cpp.
References browser, and TRUE.
Referenced by HelpWindow().
{
#ifndef QT_NO_PRINTER
    QPrinter printer;
    printer.setFullPage(TRUE);
    if ( printer.setup( this ) ) {
        QPainter p( &printer );
        QPaintDeviceMetrics metrics(p.device());
        int dpix = metrics.logicalDpiX();
        int dpiy = metrics.logicalDpiY();
        const int margin = 72; // pt
        QRect body(margin*dpix/72, margin*dpiy/72,
                   metrics.width()-margin*dpix/72*2,
                   metrics.height()-margin*dpiy/72*2 );
        QSimpleRichText richText( browser->text(), QFont(), browser->context(), browser->styleSheet(),
                                  browser->mimeSourceFactory(), body.height() );
        richText.setWidth( &p, body.width() );
        QRect view( body );
        int page = 1;
        do {
            richText.draw( &p, body.left(), body.top(), view, colorGroup() );
            view.moveBy( 0, body.height() );
            p.translate( 0 , -body.height() );
            p.drawText( view.right() - p.fontMetrics().width( QString::number(page) ),
                        view.bottom() + p.fontMetrics().ascent() + 5, QString::number(page) );
            if ( view.top()  >= richText.height() )
                break;
            printer.newPage();
            page++;
        } while (TRUE);
    }
#endif
}
void HelpWindow::readBookmarks () [private]
Definition at line 305 of file helpwindow.cpp.
References bookmarks.
Referenced by HelpWindow().
{
    if ( QFile::exists( QDir::currentDirPath() + "/.bookmarks" ) ) {
        QFile f( QDir::currentDirPath() + "/.bookmarks" );
        f.open( IO_ReadOnly );
        QDataStream s( &f );
        s >> bookmarks;
        f.close();
    }
}
void HelpWindow::readHistory () [private]
Definition at line 292 of file helpwindow.cpp.
References history.
Referenced by HelpWindow().
{
    if ( QFile::exists( QDir::currentDirPath() + "/.history" ) ) {
        QFile f( QDir::currentDirPath() + "/.history" );
        f.open( IO_ReadOnly );
        QDataStream s( &f );
        s >> history;
        f.close();
        while ( history.count() > 20 )
            history.remove( history.begin() );
    }
}
void HelpWindow::setBackwardAvailable (bool b) [private, slot]
Definition at line 150 of file helpwindow.cpp.
References backwardId.
Referenced by HelpWindow().
{
    menuBar()->setItemEnabled( backwardId, b);
}
void HelpWindow::setForwardAvailable (bool b) [private, slot]
Definition at line 155 of file helpwindow.cpp.
References forwardId.
Referenced by HelpWindow().
{
    menuBar()->setItemEnabled( forwardId, b);
}
void HelpWindow::textChanged () [private, slot]
Definition at line 161 of file helpwindow.cpp.
References browser, FALSE, hist, mHistory, null(), pathCombo, selectedURL, and TRUE.
Referenced by HelpWindow().
{
    if ( browser->documentTitle().isNull() )
        setCaption( "Qt Example - Helpviewer - " + browser->context() );
    else
        setCaption( "Qt Example - Helpviewer - " + browser->documentTitle() ) ;
    selectedURL = browser->context();
    if ( !selectedURL.isEmpty() && pathCombo ) {
        bool exists = FALSE;
        int i;
        for ( i = 0; i < pathCombo->count(); ++i ) {
            if ( pathCombo->text( i ) == selectedURL ) {
                exists = TRUE;
                break;
            }
        }
        if ( !exists ) {
            pathCombo->insertItem( selectedURL, 0 );
            pathCombo->setCurrentItem( 0 );
            mHistory[ hist->insertItem( selectedURL ) ] = selectedURL;
        } else
            pathCombo->setCurrentItem( i );
        selectedURL = QString::null;
    }
}
Field Documentation
int HelpWindow::backwardId [private]
Definition at line 50 of file helpwindow.h.
Referenced by HelpWindow(), and setBackwardAvailable().
QPopupMenu * HelpWindow::bookm [private]
Definition at line 54 of file helpwindow.h.
Referenced by addBookmark(), and HelpWindow().
QStringList HelpWindow::bookmarks [private]
Definition at line 52 of file helpwindow.h.
Referenced by HelpWindow(), readBookmarks(), and ~HelpWindow().
QTextBrowser* HelpWindow::browser [private]
Definition at line 48 of file helpwindow.h.
Referenced by addBookmark(), bookmChosen(), HelpWindow(), histChosen(), newWindow(), openFile(), pathSelected(), print(), and textChanged().
int HelpWindow::forwardId [private]
Definition at line 50 of file helpwindow.h.
Referenced by HelpWindow(), and setForwardAvailable().
QPopupMenu* HelpWindow::hist [private]
Definition at line 54 of file helpwindow.h.
Referenced by HelpWindow(), pathSelected(), and textChanged().
QStringList HelpWindow::history [private]
Definition at line 52 of file helpwindow.h.
Referenced by HelpWindow(), readHistory(), and ~HelpWindow().
QMap< int, QString > HelpWindow::mBookmarks [private]
Definition at line 53 of file helpwindow.h.
Referenced by addBookmark(), bookmChosen(), HelpWindow(), and ~HelpWindow().
QMap< int, QString > HelpWindow::mHistory [private]
Definition at line 53 of file helpwindow.h.
Referenced by HelpWindow(), histChosen(), pathSelected(), textChanged(), and ~HelpWindow().
QComboBox* HelpWindow::pathCombo [private]
Definition at line 49 of file helpwindow.h.
Referenced by HelpWindow(), and textChanged().
QString HelpWindow::selectedURL [private]
Definition at line 51 of file helpwindow.h.
Referenced by textChanged().
The documentation for this class was generated from the following files:
midas/gui/hvedit/qt/help/helpwindow.h
midas/gui/hvedit/qt/help/helpwindow.cpp