AlcapDAQ:Rootana: CreateDetectorPulse Class Reference
CreateDetectorPulse Class Reference
#include <CreateDetectorPulses.h>
Public Member Functions
CreateDetectorPulse (char *HistogramDirectoryName)
~CreateDetectorPulse ()
int ProcessGenericEntry (TGlobalData *gData, TSetupData *gSetup)
virtual int BeforeFirstEntry (TGlobalData *gData, TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, TSetupData *setup)
const char * GetName () const
Protected Member Functions
bool Debug () const
Protected Attributes
TDirectory * dir
TSetupData * fSetup
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData, TSetupData *gSetup)
Detailed Description
Definition at line 8 of file CreateDetectorPulses.h.
Constructor & Destructor Documentation
CreateDetectorPulse::CreateDetectorPulse (char * HistogramDirectoryName)
Definition at line 24 of file CreateDetectorPulses.cpp.
References FillHistBase::dir.
                                                                     :
  FillHistBase(HistogramDirectoryName){
  dir->cd("/");
}
CreateDetectorPulse::~CreateDetectorPulse ()
Definition at line 29 of file CreateDetectorPulses.cpp.
{
}
Member Function Documentation
virtual int FillHistBase::AfterLastEntry (TGlobalData * gData, TSetupData * setup) [inline, virtual, inherited]
Definition at line 39 of file FillHistBase.h.
{return 0;};
virtual int FillHistBase::BeforeFirstEntry (TGlobalData * gData, TSetupData * setup) [inline, virtual, inherited]
Reimplemented in ExportPulse, MakeAnalysedPulses, MakeDetectorPulses, and MakeMuonEvents.
Definition at line 38 of file FillHistBase.h.
{return 0;};
bool FillHistBase::Debug () const [inline, protected, inherited]
Definition at line 45 of file FillHistBase.h.
References FillHistBase::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), MakeMuonEvents::BeforeFirstEntry(), MakeDetectorPulses::MakeGenerator(), ExportPulse::MakePlot(), and MakeAnalysedPulses::ProcessEntry().
{return fDebug;};
const char* FillHistBase::GetName () const [inline, inherited]
Definition at line 40 of file FillHistBase.h.
References FillHistBase::dir.
Referenced by PlotTime::ProcessEntry(), PlotAmplitude::ProcessEntry(), and DeadTimeGe::ProcessEntry().
{return dir->GetName();};
int CreateDetectorPulse::ProcessEntry (TGlobalData * gData, TSetupData * gSetup) [private, virtual]
Reimplemented from FillHistBase.
Definition at line 32 of file CreateDetectorPulses.cpp.
References gAnalysedPulseMap, gDetectorPulseMap, TAnalysedPulse::GetDetName(), TDetectorPulse::GetFastPulseTime(), TDetectorPulse::GetSlowPulseTime(), TAnalysedPulse::GetTime(), GetTime(), TSetupData::IsFast(), TSetupData::IsSlow(), and PrintOut.
{
  typedef map<string, vector<TPulseIsland*> > TStringPulseIslandMap;
  typedef pair<string, vector<TPulseIsland*> > TStringPulseIslandPair;
  typedef map<string, vector<TPulseIsland*> >::iterator map_iterator;
  // Loop through and find a fast channel
  for (std::map<std::string, std::vector<TAnalysedPulse*> >::iterator findFastIter = gAnalysedPulseMap.begin(); findFastIter != gAnalysedPulseMap.end(); findFastIter++) {
    std::string fast_det_name = findFastIter->first;
    if (! TSetupData::IsFast(fast_det_name)) continue;
      std::string detname = fast_det_name.substr(0, fast_det_name.size() - 2);
      std::string slow_det_name = detname + "-S"; // take off the F and add an S
      std::map<std::string, std::vector<TAnalysedPulse*> >::iterator findSlowIter= gAnalysedPulseMap.find(slow_det_name);
      if(findSlowIter== gAnalysedPulseMap.end()) std::cout<<"Unable to find slow channel, "<<slow_det_name<<std::endl;
          std::vector<TAnalysedPulse*> fast_pulses = findFastIter->second;
          std::vector<TAnalysedPulse*> slow_pulses = findSlowIter->second;
          std::vector<TAnalysedPulse*>::iterator fastPulseIter = fast_pulses.begin();
          std::vector<TAnalysedPulse*>::iterator slowPulseIter = slow_pulses.begin();
          std::vector<TAnalysedPulse*>::iterator finalFastPulseIter = fast_pulses.end();
          std::vector<TAnalysedPulse*>::iterator finalSlowPulseIter = slow_pulses.end();
          std::vector<std::vector<TAnalysedPulse*>::iterator> pulseIters;
          pulseIters.push_back(fastPulseIter);
          pulseIters.push_back(slowPulseIter);
          std::vector<std::vector<TAnalysedPulse*>::iterator> finalIters;
          finalIters.push_back(finalFastPulseIter);
          finalIters.push_back(finalSlowPulseIter);
          std::vector<TDetectorPulse*> detectorPulses;
          // Loop through both TAnalysedPulse vectors until they are both finished
          // NB with this alogirthm this can be extended to more than 2
          double min_time = 999999; // something large
          double pulse_time;
          while (pulseIters.size() > 0) {
            // Find out which of the next fast or slow pulsees happened next
            for (int b = 0; b < pulseIters.size(); ++b) {
              pulse_time = (*pulseIters[b])->GetTime() * 1e-6; // convert to ms
              min_time = std::min(min_time, pulse_time);
            }
            // Now go through and find all the pulses that are within a certain time of this
            double time_difference = 0.1; // 0.1 ms
            TAnalysedPulse* fast_pulse = NULL;
            TAnalysedPulse* slow_pulse = NULL;
            for (int b = 0; b < pulseIters.size(); ++b) {
              TAnalysedPulse* pulse = *(pulseIters[b]);
              double pulse_time = pulse->GetTime() * 1e-6; // convert to ms
              if (std::fabs(pulse_time - min_time) < time_difference) {
                if ( TSetupData::IsFast(pulse->GetDetName())) {
                  PrintOut("Fast? " << pulse->GetDetName() << std::endl);
                  fast_pulse = pulse;
                }
                else if ( TSetupData::IsSlow(pulse->GetDetName()))  {
                  PrintOut( "Slow? " << pulse->GetDetName() << std::endl);
                  slow_pulse = pulse;
                }
                ++(pulseIters[b]); // increment the iterator because we used the pulse
              }
            }
            TDetectorPulse* det_pulse = new TDetectorPulse(fast_pulse, slow_pulse, detname); // Create the TDetectorPulse
            detectorPulses.push_back(det_pulse);
            PrintOut("Created a TDetectorPulse with:\n");
            PrintOut("Fast Pulse: " << det_pulse->GetFastPulseTime() * 1e-6 << std::endl);
            PrintOut( "Slow Pulse: " << det_pulse->GetSlowPulseTime() * 1e-6 << std::endl);
            PrintOut( std::endl);
            //Delete the iterators to finished banks. Go through in reverse to
            //avoid invalidation problems
            for (int b = pulseIters.size()-1; b >= 0; --b) {
              if (pulseIters[b] == finalIters[b]){
                pulseIters.erase(pulseIters.begin() + b);
                finalIters.erase(finalIters.begin() + b);
              }
            } // for (int b -reversed)
          } // end for
          gDetectorPulseMap[detname] = detectorPulses;
      //} // end loop to find corresponding slow channel
  } // end loop to find fast channel
  return 0;
}
int FillHistBase::ProcessGenericEntry (TGlobalData * gData, TSetupData * gSetup) [inherited]
Definition at line 24 of file FillHistBase.cpp.
References FillHistBase::dir, and FillHistBase::ProcessEntry().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(dir) dir->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
Field Documentation
TDirectory* FillHistBase::dir [protected, inherited]
Definition at line 40 of file FillHistBase.h.
Referenced by AnalysePulseIsland::AnalysePulseIsland(), CoincidenceCut::CoincidenceCut(), CreateDetectorPulse(), DeadTimeGe::DeadTimeGe(), ExportPulse::ExportPulse(), FillHistBase::FillHistBase(), FillHistBase::GetName(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmplitude::PlotAmplitude(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTime::PlotTime(), and FillHistBase::ProcessGenericEntry().
TSetupData* FillHistBase::fSetup [protected, inherited]
Reimplemented in ExportPulse.
Definition at line 44 of file FillHistBase.h.
Referenced by CheckCoincidence::CheckCoincidence().
The documentation for this class was generated from the following files:
analyzer/rootana/src/deprecated/CreateDetectorPulses.h
analyzer/rootana/src/deprecated/CreateDetectorPulses.cpp