AlcapDAQ:Rootana: TUsrSevtData1 Class Reference
TUsrSevtData1 Class Reference
#include <clonesA_Event.h>
Public Member Functions
TUsrSevtData1 ()
virtual ~TUsrSevtData1 ()
void SetEvent (Int_t ev)
Int_t GetPileup ()
void Clear (Option_t *opt="")
TUsrHitBuffer * GetHitBuffer ()
Protected Attributes
TString fSevtName
Int_t fMer
Int_t fPileup
Int_t fTimeStamp
TUsrHitBuffer fHitBuffer
Detailed Description
Definition at line 63 of file clonesA_Event.h.
Constructor & Destructor Documentation
TUsrSevtData1::TUsrSevtData1 () [inline]
Definition at line 65 of file clonesA_Event.h.
References SetEvent().
{SetEvent(0);}
virtual TUsrSevtData1::~TUsrSevtData1 () [inline, virtual]
Definition at line 67 of file clonesA_Event.h.
{}
Member Function Documentation
void TMrbSubevent_Caen::Clear (Option_t * opt = "") [inline, inherited]
Definition at line 51 of file clonesA_Event.h.
References TUsrHitBuffer::Clear(), and TMrbSubevent_Caen::fHitBuffer.
Referenced by TUsrSevtData2::SetEvent(), and SetEvent().
{fHitBuffer.Clear();};
TUsrHitBuffer* TMrbSubevent_Caen::GetHitBuffer () [inline, inherited]
Definition at line 52 of file clonesA_Event.h.
References TMrbSubevent_Caen::fHitBuffer.
{return &fHitBuffer;};
Int_t TUsrSevtData1::GetPileup () [inline]
Definition at line 69 of file clonesA_Event.h.
References fPileup.
{return fPileup; };
void TUsrSevtData1::SetEvent (Int_t ev)
Definition at line 44 of file clonesA_Event.cxx.
References TUsrHitBuffer::AddHit(), TMrbSubevent_Caen::Clear(), TMrbSubevent_Caen::fHitBuffer, fMer, fPileup, fSevtName, TMrbSubevent_Caen::fTimeStamp, and i.
Referenced by TUsrSevtData1().
{
   Clear();
   cout << "TUsrSevtData1: " << ev << endl;
   fTimeStamp = 100+ev; //in TMrbSubevent_Caen
   fSevtName  = "SubEvent_1_";
   fSevtName += ev;
   fMer       = 1100 + ev;
   fPileup    = 2100 + ev;
   for(Int_t i = 1; i <= ev+1; i++) {
      fHitBuffer.AddHit(i);
   }
}
Field Documentation
TUsrHitBuffer TMrbSubevent_Caen::fHitBuffer [protected, inherited]
Definition at line 56 of file clonesA_Event.h.
Referenced by TMrbSubevent_Caen::Clear(), TMrbSubevent_Caen::GetHitBuffer(), TUsrSevtData2::SetEvent(), and SetEvent().
Int_t TUsrSevtData1::fMer [protected]
Definition at line 73 of file clonesA_Event.h.
Referenced by SetEvent().
Int_t TUsrSevtData1::fPileup [protected]
Definition at line 74 of file clonesA_Event.h.
Referenced by GetPileup(), and SetEvent().
TString TUsrSevtData1::fSevtName [protected]
Definition at line 69 of file clonesA_Event.h.
Referenced by SetEvent().
Int_t TMrbSubevent_Caen::fTimeStamp [protected, inherited]
Definition at line 52 of file clonesA_Event.h.
Referenced by TUsrSevtData2::SetEvent(), and SetEvent().
The documentation for this class was generated from the following files:
www/html/online/trend_plots/runsummary/tutorials/clonesA_Event.h
www/html/online/trend_plots/runsummary/tutorials/clonesA_Event.cxx