AlcapDAQ:Rootana: TMrbSubevent_Caen Class Reference
TMrbSubevent_Caen Class Reference
#include <clonesA_Event.h>
Public Member Functions
TMrbSubevent_Caen ()
virtual ~TMrbSubevent_Caen ()
void Clear (Option_t *opt="")
TUsrHitBuffer * GetHitBuffer ()
Protected Attributes
Int_t fTimeStamp
TUsrHitBuffer fHitBuffer
Detailed Description
Definition at line 46 of file clonesA_Event.h.
Constructor & Destructor Documentation
TMrbSubevent_Caen::TMrbSubevent_Caen () [inline]
Definition at line 49 of file clonesA_Event.h.
{cout << "ctor  TMrbSubevent_Caen" << this << endl;}
virtual TMrbSubevent_Caen::~TMrbSubevent_Caen () [inline, virtual]
Definition at line 50 of file clonesA_Event.h.
{}
Member Function Documentation
void TMrbSubevent_Caen::Clear (Option_t * opt = "") [inline]
Definition at line 51 of file clonesA_Event.h.
References TUsrHitBuffer::Clear(), and fHitBuffer.
Referenced by TUsrSevtData2::SetEvent(), and TUsrSevtData1::SetEvent().
{fHitBuffer.Clear();};
TUsrHitBuffer* TMrbSubevent_Caen::GetHitBuffer () [inline]
Definition at line 52 of file clonesA_Event.h.
References fHitBuffer.
{return &fHitBuffer;};
Field Documentation
TUsrHitBuffer TMrbSubevent_Caen::fHitBuffer [protected]
Definition at line 56 of file clonesA_Event.h.
Referenced by Clear(), GetHitBuffer(), TUsrSevtData2::SetEvent(), and TUsrSevtData1::SetEvent().
Int_t TMrbSubevent_Caen::fTimeStamp [protected]
Definition at line 52 of file clonesA_Event.h.
Referenced by TUsrSevtData2::SetEvent(), and TUsrSevtData1::SetEvent().
The documentation for this class was generated from the following file:
www/html/online/trend_plots/runsummary/tutorials/clonesA_Event.h