AlcapDAQ:Rootana: cmExperiment Class Reference
cmExperiment Class Reference
#include <cmExperiment.h>
Public Member Functions
cmExperiment (QString strClientName, QObject *parent=0, const char *name=0)
~cmExperiment ()
void SetHostName (QString hostName)
Sets the name of the host.
void SetExperimentName (QString expName)
Sets the name of the experiment.
QString GetHostName ()
Returns the name of the host.
QString GetExperimentName ()
Returns the name of the MIDAS experiment to which one is connected.
QString GetClientName ()
Returns the name of the calling client.
HNDLE GetHdb ()
Returns the main MIDAS handle to the ODB.
BOOL IsConnected ()
Returns if already connected to an experiment.
BOOL StartTimer ()
BOOL Connect (QString host, QString experiment, QString client)
void Disconnect ()
Private Slots
void timeOutProc ()
Private Attributes
QString m_strHostName
host name on which the experiment is running
QString m_strExperimentName
name of the experiment
QString m_strClientName
name of the client calling cmExperiment, e.g. 'hvEdit'
BOOL m_bConnected
flag showing if a connection to an experiment is established
BOOL m_bTimerStarted
flag showing if the cyclic timer is already running
HNDLE m_hDB
main handle to the ODB
QTimer * timer
pointer to a timer which is used for the watchdog process
Detailed Description
Definition at line 53 of file cmExperiment.h.
Constructor & Destructor Documentation
cmExperiment::cmExperiment (QString strClientName, QObject * parent = 0, const char * name = 0)
Creates an object to a MIDAS experiment.
Parameters:
strClientName Name of the client which connects to the experiment, e.g. 'hvEdit'
parent The parent of an object may be viewed as the object's owner. Setting parent to 0 constructs an object with no parent. If the object is a widget, it will become a top-level window.
name Name of the object. The object name is some text that can be used to identify a QObject.
Definition at line 77 of file cmExperiment.cpp.
References FALSE, m_bConnected, m_strClientName, m_strExperimentName, and m_strHostName.
                                             : QObject(parent, name)
{
  // Set empty strings
  m_strHostName       = "";
  m_strExperimentName = "";
  m_strClientName     = strClientName;
  m_bConnected = FALSE;
}
cmExperiment::~cmExperiment ()
Destroys the object.
Definition at line 92 of file cmExperiment.cpp.
{
}
Member Function Documentation
BOOL cmExperiment::Connect (QString strHostName, QString strExperimentName, QString strClientName)
Establishes the connection to a MIDAS experiment, running on the host strHostName.
return:
TRUE, if connection to the experiment is established
FALSE, otherwise
Parameters:
strHostName Name of the host on which the MIDAS experiment runs.
strExperimentName Name of the MIDAS experiment to which one wants to connect
strClientName Name of the client which connects to the experiment, e.g. 'hvEdit'
Definition at line 109 of file cmExperiment.cpp.
References cm_connect_experiment1(), cm_get_error(), cm_get_experiment_database(), cm_set_msg_print(), cm_set_watchdog_params(), CM_SUCCESS, CM_WRONG_PASSWORD, DEFAULT_ODB_SIZE, FALSE, GetPassword(), m_bConnected, m_bTimerStarted, m_hDB, MidasMessage(), MT_ALL, status, and TRUE.
Referenced by Qt_hvEdit::connectToExp().
{
  int status;
  // initialize variables
  m_bConnected    = FALSE;
  m_bTimerStarted = FALSE;
  // try to connect to midas host
  do {
    status = cm_connect_experiment1((char *)strHostName.ascii(),
                                    (char *)strExperimentName.ascii(),
                                    (char *)strClientName.ascii(), GetPassword,
                                    DEFAULT_ODB_SIZE, 20000); // increased timeout for W95
    if (status == CM_WRONG_PASSWORD) {
      MidasMessage("Password is incorrect");
      return FALSE;
    }
    if (status != CM_SUCCESS) { // midas error
      char str[256];
      cm_get_error(status, str);
      MidasMessage(str);
    }
  } while (status != CM_SUCCESS);
  // disable watchdog during debugging
#ifdef _DEBUG
  cm_set_watchdog_params(TRUE, 0);
#endif
  // route all messages to MidasMessage
  cm_set_msg_print(MT_ALL, MT_ALL, MidasMessage);
  // get handle to ODB
  cm_get_experiment_database(&m_hDB, NULL);
  // set connected flag
  m_bConnected = TRUE;
  return TRUE;
}
void cmExperiment::Disconnect ()
Disconnects from an already connected MIDAS experiment.
return: void
Definition at line 161 of file cmExperiment.cpp.
References cm_disconnect_experiment(), FALSE, and m_bConnected.
Referenced by Qt_hvEdit::disconnectFromExp().
{
  cm_disconnect_experiment();
  m_bConnected = FALSE;
}
QString cmExperiment::GetClientName () [inline]
Returns the name of the calling client.
Definition at line 89 of file cmExperiment.h.
References m_strClientName.
Referenced by Qt_hvEdit::connectToExp().
{
      return m_strClientName;
   };
QString cmExperiment::GetExperimentName () [inline]
Returns the name of the MIDAS experiment to which one is connected.
Definition at line 85 of file cmExperiment.h.
References m_strExperimentName.
Referenced by Qt_hvEdit::connectToExp().
{
      return m_strExperimentName;
   };
HNDLE cmExperiment::GetHdb () [inline]
Returns the main MIDAS handle to the ODB.
Definition at line 93 of file cmExperiment.h.
References m_hDB.
Referenced by cmKey::cmKey().
                  {
      return m_hDB;
   };
QString cmExperiment::GetHostName () [inline]
Returns the name of the host.
Definition at line 81 of file cmExperiment.h.
References m_strHostName.
Referenced by Qt_hvEdit::connectToExp(), and Qt_Connect::getExpList().
{
      return m_strHostName;
   };
BOOL cmExperiment::IsConnected () [inline]
Returns if already connected to an experiment.
Definition at line 97 of file cmExperiment.h.
References m_bConnected.
Referenced by Qt_hvEdit::fileExit().
                      {
      return m_bConnected;
   };
void cmExperiment::SetExperimentName (QString expName) [inline]
Sets the name of the experiment.
Definition at line 77 of file cmExperiment.h.
References m_strExperimentName.
Referenced by Qt_hvEdit::connectToExp(), and Qt_Connect::gotExperiment().
{
      m_strExperimentName = expName;
   };
void cmExperiment::SetHostName (QString hostName) [inline]
Sets the name of the host.
Definition at line 73 of file cmExperiment.h.
References m_strHostName.
Referenced by Qt_hvEdit::connectToExp(), and Qt_Connect::getExpList().
{
      m_strHostName = hostName;
   };
BOOL cmExperiment::StartTimer ()
Since all MIDAS clients cyclically have to tell that they are still alive, such a cyclical timer is needed, which is implemented here. This cyclic timer works the following way: Once it is started, it runs in the background till timeout is reached. At timeout it calls a time out routine (timeOutProc) and the whole things starts all over again.
return:
TRUE if timer could have been started
FALSE otherwise
Definition at line 180 of file cmExperiment.cpp.
References FALSE, m_bTimerStarted, MidasMessage(), timeout, timeOutProc(), timer, and TRUE.
Referenced by cmKey::HotLink().
{
  if (m_bTimerStarted)
    return TRUE;
  // create timer
  timer = new QTimer();
  // connect timer to event handler
  connect(timer, SIGNAL(timeout()), SLOT(timeOutProc()));
  // start timer
  if (!timer->start(500)) {
    MidasMessage("Cannot set timer");
    return FALSE;
  }
  m_bTimerStarted = TRUE;
  return TRUE;
}
void cmExperiment::timeOutProc () [private, slot]
This routine is the time out routine of StartTimer and is cyclically called. It self tells MIDAS that hvEdit is still alive and checks if MIDAS itself is alive and if MIDAS (for what ever reason) kick hvEdit out.
return: void
Definition at line 211 of file cmExperiment.cpp.
References cm_yield(), MidasMessage(), RPC_SHUTDOWN, SS_ABORT, and status.
Referenced by StartTimer().
{
  int status;
  // tell MIDAS that hvEdit is still alive
  status = cm_yield(0);
  // check if MIDAS itself is still alive
  // check further if MIDAS did not through hvEdit out
  if (status == SS_ABORT || status == RPC_SHUTDOWN) {
    MidasMessage("Lost connection to the host");
  }
}
Field Documentation
BOOL cmExperiment::m_bConnected [private]
flag showing if a connection to an experiment is established
Definition at line 65 of file cmExperiment.h.
Referenced by cmExperiment(), Connect(), Disconnect(), and IsConnected().
BOOL cmExperiment::m_bTimerStarted [private]
flag showing if the cyclic timer is already running
Definition at line 66 of file cmExperiment.h.
Referenced by Connect(), and StartTimer().
HNDLE cmExperiment::m_hDB [private]
main handle to the ODB
Definition at line 67 of file cmExperiment.h.
Referenced by Connect(), and GetHdb().
QString cmExperiment::m_strClientName [private]
name of the client calling cmExperiment, e.g. 'hvEdit'
Definition at line 64 of file cmExperiment.h.
Referenced by cmExperiment(), and GetClientName().
QString cmExperiment::m_strExperimentName [private]
name of the experiment
Definition at line 63 of file cmExperiment.h.
Referenced by cmExperiment(), GetExperimentName(), and SetExperimentName().
QString cmExperiment::m_strHostName [private]
host name on which the experiment is running
Definition at line 62 of file cmExperiment.h.
Referenced by cmExperiment(), GetHostName(), and SetHostName().
QTimer* cmExperiment::timer [private]
pointer to a timer which is used for the watchdog process
Definition at line 68 of file cmExperiment.h.
Referenced by StartTimer().
The documentation for this class was generated from the following files:
midas/gui/hvedit/qt/cmExperiment.h
midas/gui/hvedit/qt/cmExperiment.cpp