AlcapDAQ:Rootana: Qt_Connect Class Reference
Qt_Connect Class Reference
#include <Qt_Connect.h>
Public Slots
void gotExperiment ()
Public Member Functions
Qt_Connect (cmExperiment *cmExp, QWidget *parent=0, const char *name=0, bool modal=FALSE, WFlags f=WDestructiveClose)
~Qt_Connect ()
Private Slots
void getExpList ()
Private Attributes
cmExperiment * cmExp
Pointer to a MIDAS experiment object.
Detailed Description
Definition at line 53 of file Qt_Connect.h.
Constructor & Destructor Documentation
Qt_Connect::Qt_Connect (cmExperiment * cmExp, QWidget * parent = 0, const char * name = 0, bool modal = FALSE, WFlags fl = WDestructiveClose)
Shows the 'connect to' dialog which is used to establish the connection to a MIDAS experiment.
Parameters:
cmExp Pointer to a MIDAS experiment object
parent Pointer to the parent widget.
name Pointer to the internal name
modal Flag telling if the widget is going to be modal or not.
fl The widget flags argument, f, is normally 0, but it can be set to customize the window frame of a top-level widget (i.e. parent must be 0). To customize the frame, set the WStyle_Customize flag OR'ed with any of the Qt::WidgetFlags.
Definition at line 66 of file Qt_Connect.cpp.
References cmExp.
                                              : Qt_Connect_Base(parent, name, modal, fl)
{
  Qt_Connect::cmExp = cmExp; // links local experiment to the global one
  host_lineEdit->setFocus(); // set the focus to the host name field
}
Qt_Connect::~Qt_Connect ()
Destroys the object.
Definition at line 77 of file Qt_Connect.cpp.
{
}
Member Function Documentation
void Qt_Connect::getExpList () [private, slot]
Gets the list of experiments from 'host' and displays them.
Return: void.
Definition at line 87 of file Qt_Connect.cpp.
References cm_list_experiments(), CM_SUCCESS, cmExp, cmExperiment::GetHostName(), MAX_EXPERIMENT, NAME_LENGTH, and cmExperiment::SetHostName().
{
  cmExp->SetHostName(host_lineEdit->text());        // gets the host name
  char exp_name_list[MAX_EXPERIMENT][NAME_LENGTH];  // list of all the available experiments
  int  i;
  // try to get list of experiments from host
  if (cm_list_experiments((char *)cmExp->GetHostName().ascii(), exp_name_list) != CM_SUCCESS) {
    QMessageBox::warning(this, "ERROR", "Could not connect to "+cmExp->GetHostName(),
                         QMessageBox::Ok, QMessageBox::Cancel);
    return;
  }
  // generate list of experiments for widget
  exp_listBox->clear(); // deletes a perhaps existing list
  i=0;
  while (strcmp(exp_name_list[i],"")) {
    exp_listBox->insertItem(exp_name_list[i],-1); // insert new item at the end of the list
    i++;
  }
  exp_listBox->setFocus();
}
void Qt_Connect::gotExperiment () [slot]
Gets the selected experiment from the list and terminates the GUI.
Return: void.
Definition at line 116 of file Qt_Connect.cpp.
References cmExp, and cmExperiment::SetExperimentName().
{
  cmExp->SetExperimentName(exp_listBox->currentText());
  Qt_Connect::done(0);
}
Field Documentation
cmExperiment* Qt_Connect::cmExp [private]
Pointer to a MIDAS experiment object.
Definition at line 64 of file Qt_Connect.h.
Referenced by getExpList(), gotExperiment(), and Qt_Connect().
The documentation for this class was generated from the following files:
midas/gui/hvedit/qt/Qt_Connect.h
midas/gui/hvedit/qt/Qt_Connect.cpp