AlcapDAQ:Rootana: CheckCoincidence Class Reference
CheckCoincidence Class Reference
#include <CheckCoincidence.h>
Public Member Functions
CheckCoincidence (char *HistogramDirectoryName, modules::options *opts, TSetupData *setup)
~CheckCoincidence ()
int ProcessGenericEntry (TGlobalData *gData, TSetupData *gSetup)
virtual int BeforeFirstEntry (TGlobalData *gData, TSetupData *setup)
virtual int AfterLastEntry (TGlobalData *gData, TSetupData *setup)
const char * GetName () const
Protected Member Functions
bool Debug () const
Protected Attributes
TDirectory * dir
TSetupData * fSetup
Private Types
typedef std::map< std::string,
bool > CoincidenceList
Private Member Functions
virtual int ProcessEntry (TGlobalData *gData)
Private Attributes
CoincidenceList fDetectors
CoincidenceList fBanks
Detailed Description
Definition at line 10 of file CheckCoincidence.h.
Member Typedef Documentation
typedef std::map<std::string, bool> CheckCoincidence::CoincidenceList [private]
Definition at line 11 of file CheckCoincidence.h.
Constructor & Destructor Documentation
CheckCoincidence::CheckCoincidence (char * HistogramDirectoryName, modules::options * opts, TSetupData * setup)
Definition at line 26 of file CheckCoincidence.cpp.
References fBanks, fDetectors, FillHistBase::fSetup, and TSetupData::GetBankName().
                                                                                                      :
  FillHistBase(HistogramDirectoryName,opts, setup){
  fDetectors["muSc"]=true;
  fDetectors["Ge-S"]=true;
  // The following are the banks we want to compare in this example
  CoincidenceList::const_iterator it;
  std::string bank_name;
  std::cout<<"Looking for: "<<std::endl;
  for(it=fDetectors.begin();it!=fDetectors.end();it++){
      bank_name=fSetup->GetBankName(it->first);
      fBanks[bank_name]=it->second;
      if(it->second) std::cout<<"Coincidence ";
      else std::cout<<"Anti-coincidence ";
      std::cout<<"in "<<it->first<<std::endl;
  }
}
CheckCoincidence::~CheckCoincidence ()
Definition at line 46 of file CheckCoincidence.cpp.
{
}
Member Function Documentation
virtual int FillHistBase::AfterLastEntry (TGlobalData * gData, TSetupData * setup) [inline, virtual, inherited]
Definition at line 39 of file FillHistBase.h.
{return 0;};
virtual int FillHistBase::BeforeFirstEntry (TGlobalData * gData, TSetupData * setup) [inline, virtual, inherited]
Reimplemented in ExportPulse, MakeAnalysedPulses, MakeDetectorPulses, and MakeMuonEvents.
Definition at line 38 of file FillHistBase.h.
{return 0;};
bool FillHistBase::Debug () const [inline, protected, inherited]
Definition at line 45 of file FillHistBase.h.
References FillHistBase::fDebug.
Referenced by MakeAnalysedPulses::AddGenerator(), MakeMuonEvents::BeforeFirstEntry(), MakeDetectorPulses::MakeGenerator(), ExportPulse::MakePlot(), and MakeAnalysedPulses::ProcessEntry().
{return fDebug;};
const char* FillHistBase::GetName () const [inline, inherited]
Definition at line 40 of file FillHistBase.h.
References FillHistBase::dir.
Referenced by PlotTime::ProcessEntry(), PlotAmplitude::ProcessEntry(), and DeadTimeGe::ProcessEntry().
{return dir->GetName();};
int CheckCoincidence::ProcessEntry (TGlobalData * gData) [private, virtual]
Definition at line 49 of file CheckCoincidence.cpp.
{
//  typedef map<string, vector<TPulseIsland*> > TStringPulseIslandMap;
//  typedef pair<string, vector<TPulseIsland*> > TStringPulseIslandPair;
//  typedef map<string, vector<TPulseIsland*> >::iterator map_iterator;
//
//  //printf(" bank size %d\n ",banks.size());
//
//  vector<TPulseIsland*> islands[banks.size()];
//
//  for(unsigned int b1 = 0; b1 < banks.size(); ++b1){
//    string bank = banks.at(b1);
//    for(map_iterator iter = gData->fPulseIslandToChannelMap.begin(); iter != gData->fPulseIslandToChannelMap.end(); iter++){
//
//      if(strcmp((iter->first).data(), bank.data()) == 0){
//          islands[b1] = iter->second;
//        //std::cout<<" match! iter->first: "<<iter->first<<std::endl;//printf(" iter->first = %s\n",iter->first);
//      }
//    }
//    //printf(" b1 %d, island size %d\n",b1,islands[b1].size());
//    //hBankSize->Fill(islands[b1].size(), b1+1);
//  }
//
//  int maxTPIsize = 10;
//
//  vector<int> samples[banks.size()][maxTPIsize];
//
//  for (int b1=0; b1<banks.size(); b1++){
//    for (int i=0; i<islands[b1].size(); i++){
//      samples[b1][i] = islands[b1][i]->GetSamples();
//    }
//  }
//
//  //for (int j=0; j<banks.size(); j++) printf("islands %d size %d, sample size %d\n",j,islands[j].size(),samples[j][0].size());
//
//  for(unsigned int b1 = 0; b1 < banks.size(); ++b1){
//
//    //std::cout<<" b1 "<<b1<<" / "<<banks.size()<<std::endl;
//
//    for(unsigned int i = 0; i < islands[b1].size(); ++i){
//      //printf(" bank %d, island %d timestamp %d clock tick %d\n",b1,i,islands[b1][i]->GetTimeStamp(),islands[b1][i]->GetClockTickInNs());
//      for (int j=0; j<samples[b1][i].size(); j++){
//        bankHists[b1]->Fill(samples[b1][i][j]);
//        if (i==0) hSamples1->Fill(samples[b1][i][j]);
//        if (i==1) hSamples2->Fill(samples[b1][i][j]);
//        if (i==2) hSamples3->Fill(samples[b1][i][j]);
//        //printf(" for channel %d, island %d, adc samples #%d = %d\n",b1,i,j,samples[i][j]);
//      }
//    }
//  }
  return 0;
}
int FillHistBase::ProcessGenericEntry (TGlobalData * gData, TSetupData * gSetup) [inherited]
Definition at line 24 of file FillHistBase.cpp.
References FillHistBase::dir, and FillHistBase::ProcessEntry().
{
  // This is called by our main routine and would allow later to split into different
  // process routines if we have more than one Tree and hence different tpyes of data input.
  if(dir) dir->cd();
  int ret = ProcessEntry(gData, gSetup);
  gDirectory->cd("/");
  return ret;
}
Field Documentation
TDirectory* FillHistBase::dir [protected, inherited]
Definition at line 40 of file FillHistBase.h.
Referenced by AnalysePulseIsland::AnalysePulseIsland(), CoincidenceCut::CoincidenceCut(), CreateDetectorPulse::CreateDetectorPulse(), DeadTimeGe::DeadTimeGe(), ExportPulse::ExportPulse(), FillHistBase::FillHistBase(), FillHistBase::GetName(), MakeAnalysedPulses::MakeAnalysedPulses(), MakeMuonEvents::MakeMuonEvents(), PlotAmplitude::PlotAmplitude(), PlotAmpVsTDiff::PlotAmpVsTDiff(), PlotTime::PlotTime(), and FillHistBase::ProcessGenericEntry().
CoincidenceList CheckCoincidence::fBanks [private]
Definition at line 20 of file CheckCoincidence.h.
Referenced by CheckCoincidence().
CoincidenceList CheckCoincidence::fDetectors [private]
Definition at line 19 of file CheckCoincidence.h.
Referenced by CheckCoincidence().
TSetupData* FillHistBase::fSetup [protected, inherited]
Reimplemented in ExportPulse.
Definition at line 44 of file FillHistBase.h.
Referenced by CheckCoincidence().
The documentation for this class was generated from the following files:
analyzer/rootana/src/deprecated/CheckCoincidence.h
analyzer/rootana/src/deprecated/CheckCoincidence.cpp