AlcapDAQ:Rootana: TUsrSevtData2 Class Reference
TUsrSevtData2 Class Reference
#include <clonesA_Event.h>
Public Member Functions
TUsrSevtData2 ()
virtual ~TUsrSevtData2 ()
void SetEvent (Int_t ev)
Int_t GetPileup ()
void Clear (Option_t *opt="")
TUsrHitBuffer * GetHitBuffer ()
Protected Attributes
TString fSevtName
Int_t fMer
Int_t fPileup
Int_t fTimeStamp
TUsrHitBuffer fHitBuffer
Detailed Description
Definition at line 80 of file clonesA_Event.h.
Constructor & Destructor Documentation
TUsrSevtData2::TUsrSevtData2 () [inline]
Definition at line 82 of file clonesA_Event.h.
References SetEvent().
{SetEvent(0);}
virtual TUsrSevtData2::~TUsrSevtData2 () [inline, virtual]
Definition at line 84 of file clonesA_Event.h.
{}
Member Function Documentation
void TMrbSubevent_Caen::Clear (Option_t * opt = "") [inline, inherited]
Definition at line 51 of file clonesA_Event.h.
References TUsrHitBuffer::Clear(), and TMrbSubevent_Caen::fHitBuffer.
Referenced by SetEvent(), and TUsrSevtData1::SetEvent().
{fHitBuffer.Clear();};
TUsrHitBuffer* TMrbSubevent_Caen::GetHitBuffer () [inline, inherited]
Definition at line 52 of file clonesA_Event.h.
References TMrbSubevent_Caen::fHitBuffer.
{return &fHitBuffer;};
Int_t TUsrSevtData2::GetPileup () [inline]
Definition at line 86 of file clonesA_Event.h.
References fPileup.
{return fPileup; };
void TUsrSevtData2::SetEvent (Int_t ev)
Definition at line 58 of file clonesA_Event.cxx.
References TUsrHitBuffer::AddHit(), TMrbSubevent_Caen::Clear(), TMrbSubevent_Caen::fHitBuffer, fMer, fPileup, fSevtName, TMrbSubevent_Caen::fTimeStamp, and i.
Referenced by TUsrSevtData2().
{
   Clear();
   cout << "TUsrSevtData2: " << ev << endl;
   fTimeStamp = 100+ev; //in TMrbSubevent_Caen
   fSevtName  = "SubEvent_2_";
   fSevtName += ev;
   fMer       = 21000 + ev;
   fPileup    = 22000 + ev;
   for(Int_t i = 1; i <= ev+1; i++) {
      fHitBuffer.AddHit(i);
   }
}
Field Documentation
TUsrHitBuffer TMrbSubevent_Caen::fHitBuffer [protected, inherited]
Definition at line 56 of file clonesA_Event.h.
Referenced by TMrbSubevent_Caen::Clear(), TMrbSubevent_Caen::GetHitBuffer(), SetEvent(), and TUsrSevtData1::SetEvent().
Int_t TUsrSevtData2::fMer [protected]
Definition at line 90 of file clonesA_Event.h.
Referenced by SetEvent().
Int_t TUsrSevtData2::fPileup [protected]
Definition at line 91 of file clonesA_Event.h.
Referenced by GetPileup(), and SetEvent().
TString TUsrSevtData2::fSevtName [protected]
Definition at line 86 of file clonesA_Event.h.
Referenced by SetEvent().
Int_t TMrbSubevent_Caen::fTimeStamp [protected, inherited]
Definition at line 52 of file clonesA_Event.h.
Referenced by SetEvent(), and TUsrSevtData1::SetEvent().
The documentation for this class was generated from the following files:
www/html/online/trend_plots/runsummary/tutorials/clonesA_Event.h
www/html/online/trend_plots/runsummary/tutorials/clonesA_Event.cxx