AlcapDAQ:Rootana: cmKey Class Reference
cmKey Class Reference
#include <cmKey.h>
Public Member Functions
cmKey (cmExperiment *pExperiment, QString *strKeyName)
cmKey (cmKey *pRootKey, QString *strKeyName)
~cmKey ()
HNDLE GetHdb ()
Returns the Main handle of the ODB.
HNDLE GetHkey ()
Returns the key.
BOOL IsValid ()
Returns if the searched key is accessible or existing.
INT GetType ()
Returns the type of the key.
INT GetItemSize ()
Returns the item size of the key.
WORD GetAccessMode ()
Returns the access mode of the key.
INT GetNumValues ()
Returns the number of elements contained in the key.
INT UpdateKey ()
INT HotLink (void *addr, WORD access, void(*dispatcher)(INT, INT, void *), void *window)
INT Unlink ()
INT GetData (void *data, INT *size, DWORD type)
INT SetData (void *data, INT num_values, DWORD type)
INT SetDataIndex (void *data, INT index, DWORD type)
DWORD GetKeyTime ()
Private Attributes
HNDLE m_hDB
Main handle to the ODB of MIDAS.
HNDLE m_hKey
Handle to a key in the ODB.
BOOL m_bValid
Validator flag, showing if the searched key is accessible or existing.
KEY m_Key
MIDAS Structure to the key. Holding informations about the content of the key.
cmExperiment * m_pExperiment
Pointer to a MIDAS experiment object.
Detailed Description
Definition at line 50 of file cmKey.h.
Constructor & Destructor Documentation
cmKey::cmKey (cmExperiment * pExperiment, QString * strKeyName)
Constructs a cmKey object, linked to a MIDAS experiment. It is used to establish the main entry key for all the other ones.
Parameters:
pExperiment Pointer to a MIDAS experiment object, i.e. the connection to this experiment is already established (see cmExperiment).
strKeyName Name of the key in the ODB, which one wants to link to.
Definition at line 56 of file cmKey.cpp.
References db_find_key(), db_get_key(), DB_SUCCESS, cmExperiment::GetHdb(), m_bValid, m_hDB, m_hKey, m_Key, and m_pExperiment.
{
  m_pExperiment = pExperiment;   // pointer to the experiment
  m_hDB = pExperiment->GetHdb(); // handle to the ODB
  m_bValid = (db_find_key(m_hDB, 0, (char *)strKeyName->ascii(), &m_hKey) == DB_SUCCESS);
  if (m_bValid) {
    db_get_key(m_hDB, m_hKey, &m_Key);
  } else {
    QMessageBox::warning(0, "MIDAS", "Cannot find " + *strKeyName + " entry in online database",
                         QMessageBox::Ok, QMessageBox::NoButton);
  }
}
cmKey::cmKey (cmKey * pRootKey, QString * strKeyName)
Constructs a cmKey object, linked to a MIDAS experiment. It is used to establish a hot-link to a specific sub-key.
Parameters:
pRootKey Pointer to the root key.
strKeyName Name of the key in the ODB, which one wants to link to.
Definition at line 76 of file cmKey.cpp.
References db_find_key(), db_get_key(), DB_SUCCESS, GetHdb(), GetHkey(), m_bValid, m_hDB, m_hKey, m_Key, and m_pExperiment.
{
  m_pExperiment = pRootKey->m_pExperiment; // pointer to the experiment
  m_hDB = pRootKey->GetHdb();              // handle to the ODB
  m_bValid = (db_find_key(m_hDB, pRootKey->GetHkey(),
                          (char *)strKeyName->ascii(), &m_hKey) == DB_SUCCESS);
  if (m_bValid) {
    db_get_key(m_hDB, m_hKey, &m_Key);
  } else {
    QMessageBox::warning(0, "MIDAS", "Cannot find " + *strKeyName + " entry in online database",
                         QMessageBox::Ok, QMessageBox::NoButton);
  }
}
cmKey::~cmKey ()
Destroys the object.
Definition at line 94 of file cmKey.cpp.
{
}
Member Function Documentation
WORD cmKey::GetAccessMode () [inline]
Returns the access mode of the key.
Definition at line 88 of file cmKey.h.
References KEY::access_mode, and m_Key.
{
      return m_Key.access_mode;
   };
INT cmKey::GetData (void * data, INT * size, DWORD type)
The function returns single values or whole arrays which are contained in an ODB key. Since the data buffer is of type void, no type checking can be performed by the compiler. Therefore the type has to be explicitly supplied, which is checked against the type stored in the ODB.
Return:
DB_SUCCESS on successful completion.
DB_INVALID_HANDLE if ODB or key is invalid.
DB_TRUNCATED if there is a size mismatch between the local structure and the ODB.
DB_TYPE_MISMATCH if there is a type discrepancy between the local structure and the ODB.
Parameters:
data Pointer to the data structure.
size Size of data buffer.
type Type of key, one of TID_xxx (see MIDAS documentation)
Definition at line 170 of file cmKey.cpp.
References db_get_data(), m_hDB, and m_hKey.
Referenced by Qt_hvEdit::updateODB_currentLimit(), and Qt_hvEdit::updateODB_demand().
{
  return db_get_data(m_hDB, m_hKey, data, size, type);
}
HNDLE cmKey::GetHdb () [inline]
Returns the Main handle of the ODB.
Definition at line 68 of file cmKey.h.
References m_hDB.
Referenced by cmKey().
                   {
      return m_hDB;
   };
HNDLE cmKey::GetHkey () [inline]
Returns the key.
Definition at line 72 of file cmKey.h.
References m_hKey.
Referenced by cmKey().
                   {
      return m_hKey;
   };
INT cmKey::GetItemSize () [inline]
Returns the item size of the key.
Definition at line 84 of file cmKey.h.
References KEY::item_size, and m_Key.
Referenced by Qt_hvEdit::updateChannelDefinitions(), and Qt_hvEdit::updateTable().
                     {
      return m_Key.item_size;
   };
DWORD cmKey::GetKeyTime ()
Returns the time in seconds, when the key was last time modified.
Return: Time when key was last time modified.
Definition at line 220 of file cmKey.cpp.
References db_get_key_time(), m_hDB, and m_hKey.
Referenced by Qt_hvEdit::updateTable().
{
  DWORD delta;
  db_get_key_time(m_hDB, m_hKey, &delta);
  return delta;
}
INT cmKey::GetNumValues () [inline]
Returns the number of elements contained in the key.
Definition at line 92 of file cmKey.h.
References m_Key, and KEY::num_values.
Referenced by Qt_hvEdit::updateChannelDefinitions().
                      {
      return m_Key.num_values;
   };
INT cmKey::GetType () [inline]
Returns the type of the key.
Definition at line 80 of file cmKey.h.
References m_Key, and KEY::type.
Referenced by Qt_hvEdit::updateChannelDefinitions().
                 {
      return m_Key.type;
   };
INT cmKey::HotLink (void * addr, WORD access, void(*)(INT, INT, void *) dispatcher, void * window)
Establishes a hot-link between a local data structure and the ODB, i.e. everytime this structure is changed in the ODB, it is automatically propageted to the structure and vice versa. Further is starts the cyclic timer needed for the MIDAS watch-dog process.
Return:
DB_SUCCESS on successful completion.
DB_INVALID_HANDLE if ODB or key is invalid.
DB_STRUCT_SIZE_MISMATCH if the structure size doesn't match the sub-tree size
DB_NO_ACCESS if there is no READ/WRITE access to the sub-tree
Parameters:
addr Address of the local structure to which a hot-link shall be established.
access Access flags for this hot-link.
dispatcher Callback function which is called, if the entries in the ODB have changed.
window Pointer to the ...
Definition at line 131 of file cmKey.cpp.
References db_open_record(), m_hDB, m_hKey, m_Key, m_pExperiment, cmExperiment::StartTimer(), and KEY::total_size.
Referenced by Qt_hvEdit::updateChannelDefinitions().
{
  m_pExperiment->StartTimer(); // start a cylcic timer event
  // establishes a hotlink
  return db_open_record(m_hDB, m_hKey, addr, m_Key.total_size, access, dispatcher, window);
}
BOOL cmKey::IsValid () [inline]
Returns if the searched key is accessible or existing.
Definition at line 76 of file cmKey.h.
References m_bValid.
Referenced by Qt_hvEdit::openKeys().
                  {
      return m_bValid;
   };
INT cmKey::SetData (void * data, INT num_values, DWORD type)
Set key data from a handle. Adjust number of values if previous data has different size.
Return:
DB_SUCCESS on successful completion.
DB_INVALID_HANDLE if ODB or key is invalid.
DB_TRUNCATED if there is a size mismatch between the local structure and the ODB.
Parameters:
data Pointer to the data structure.
num_values Number of data elements.
type Type of key, one of TID_xxx (see MIDAS documentation)
Definition at line 188 of file cmKey.cpp.
References db_set_data(), KEY::item_size, m_hDB, m_hKey, and m_Key.
Referenced by Qt_hvEdit::updateODB_currentLimit(), and Qt_hvEdit::updateODB_demand().
{
  return db_set_data(m_hDB, m_hKey, data, num_values*m_Key.item_size, num_values, type);
}
INT cmKey::SetDataIndex (void * data, INT index, DWORD type)
Set key data for a key which contains an array of values. This function sets individual values of a key containing an array. If the index is larger than the array size, the array is extended and the intermediate values are set to zero.
Return:
DB_SUCCESS on successful completion.
DB_INVALID_HANDLE if ODB or key is invalid.
DB_TRUNCATED if there is a size mismatch between the local structure and the ODB.
Parameters:
data Pointer to the data structure.
index Index of the data element.
type Type of key, one of TID_xxx (see MIDAS documentation)
Definition at line 209 of file cmKey.cpp.
References db_set_data_index(), KEY::item_size, m_hDB, m_hKey, and m_Key.
Referenced by Qt_hvEdit::updateODB_currentLimit(), and Qt_hvEdit::updateODB_demand().
{
  return db_set_data_index(m_hDB, m_hKey, data, m_Key.item_size, index, type);
}
INT cmKey::Unlink ()
Closes the hot-link, i.e. disconnects the tight link between the local structure and the ODB.
Return:
DB_SUCCESS on successful completion.
DB_INVALID_HANDLE if ODB or key is invalid.
Definition at line 148 of file cmKey.cpp.
References db_close_record(), m_hDB, and m_hKey.
Referenced by Qt_hvEdit::updateChannelDefinitions().
{
  return db_close_record(m_hDB, m_hKey);
}
INT cmKey::UpdateKey ()
Updates the key handle and the related info structure.
Return:
DB_SUCCESS on successful completion.
DB_INVALID_HANDLE if ODB or key is invalid.
Definition at line 106 of file cmKey.cpp.
References db_get_key(), m_hDB, m_hKey, and m_Key.
Referenced by Qt_hvEdit::updateChannelDefinitions().
{
  return db_get_key(m_hDB, m_hKey, &m_Key);
}
Field Documentation
BOOL cmKey::m_bValid [private]
Validator flag, showing if the searched key is accessible or existing.
Definition at line 61 of file cmKey.h.
Referenced by cmKey(), and IsValid().
HNDLE cmKey::m_hDB [private]
Main handle to the ODB of MIDAS.
Definition at line 59 of file cmKey.h.
Referenced by cmKey(), GetData(), GetHdb(), GetKeyTime(), HotLink(), SetData(), SetDataIndex(), Unlink(), and UpdateKey().
HNDLE cmKey::m_hKey [private]
Handle to a key in the ODB.
Definition at line 60 of file cmKey.h.
Referenced by cmKey(), GetData(), GetHkey(), GetKeyTime(), HotLink(), SetData(), SetDataIndex(), Unlink(), and UpdateKey().
KEY cmKey::m_Key [private]
MIDAS Structure to the key. Holding informations about the content of the key.
Definition at line 62 of file cmKey.h.
Referenced by cmKey(), GetAccessMode(), GetItemSize(), GetNumValues(), GetType(), HotLink(), SetData(), SetDataIndex(), and UpdateKey().
cmExperiment* cmKey::m_pExperiment [private]
Pointer to a MIDAS experiment object.
Definition at line 63 of file cmKey.h.
Referenced by cmKey(), and HotLink().
The documentation for this class was generated from the following files:
midas/gui/hvedit/qt/cmKey.h
midas/gui/hvedit/qt/cmKey.cpp