AlcapDAQ:Rootana: crate4_CAEN_V1724/odb_wrapper.cpp File Reference
crate4_CAEN_V1724/odb_wrapper.cpp File Reference
#include <stdio.h>
#include <stdarg.h>
#include "midas.h"
#include "odb_wrapper.h"
Functions
int odb_connect (char *format,...)
int odb_find_key (char *format,...)
int odb_get_int (char *format,...)
WORD odb_get_word (char *format,...)
DWORD odb_get_dword (char *format,...)
BOOL odb_get_bool (char *format,...)
void odb_get_boolarray (BOOL *array_out, int num_array_elements, char *format,...)
Variables
HNDLE hDB
Function Documentation
int odb_connect (char * format, ...)
Definition at line 11 of file odb_wrapper.cpp.
References cm_connect_experiment(), cm_get_experiment_database(), CM_SUCCESS, hDB, hKey, MAX_ODB_PATH, status, and SUCCESS.
{
  char s[MAX_ODB_PATH];
  int  status;
  HNDLE hKey;
  va_list argp;
  va_start(argp, format);
  vsprintf(s, format, argp);
  va_end(argp);
  /* connect to experiment */
  status = cm_connect_experiment("pc620", "muCap", s, NULL);
  if (status != CM_SUCCESS)
    return 0;
  /* get handle to online database */
  cm_get_experiment_database(&hDB, &hKey);
  return SUCCESS;
}
int odb_find_key (char * format, ...)
Definition at line 34 of file odb_wrapper.cpp.
References db_find_key(), DB_SUCCESS, hDB, hKey, MAX_ODB_PATH, status, and SUCCESS.
{
  char s[MAX_ODB_PATH];
  int  status;
  HNDLE hKey;
  va_list argp;
  va_start(argp, format);
  vsprintf(s, format, argp);
  va_end(argp);
  status = db_find_key(hDB, 0, s, &hKey);
  if (status != DB_SUCCESS)
    return 0;
  return SUCCESS;
}
BOOL odb_get_bool (char * format, ...)
Definition at line 107 of file odb_wrapper.cpp.
References db_get_value(), hDB, MAX_ODB_PATH, size, status, TID_BOOL, and TRUE.
{
  char  s[MAX_ODB_PATH];
  int   size, status;
  BOOL  retval;
  va_list argp;
  va_start(argp, format);
  vsprintf(s, format, argp);
  va_end(argp);
  size = sizeof(retval);
  status = db_get_value(hDB, 0, s, &retval, &size,
                        TID_BOOL, TRUE);
  return retval;
}
void odb_get_boolarray (BOOL * array_out, int num_array_elements, char * format, ...)
Definition at line 125 of file odb_wrapper.cpp.
References db_get_value(), hDB, MAX_ODB_PATH, size, status, TID_BOOL, and TRUE.
{
  char  s[MAX_ODB_PATH];
  int   size, status;
  BOOL  rettype;
  va_list argp;
  va_start(argp, format);
  vsprintf(s, format, argp);
  va_end(argp);
  size = sizeof(rettype) * num_array_elements;
  status = db_get_value(hDB, 0, s, array_out, &size,
                        TID_BOOL, TRUE);
}
DWORD odb_get_dword (char * format, ...)
Definition at line 89 of file odb_wrapper.cpp.
References db_get_value(), hDB, MAX_ODB_PATH, size, status, TID_DWORD, and TRUE.
{
  char  s[MAX_ODB_PATH];
  int   size, status;
  DWORD retval;
  va_list argp;
  va_start(argp, format);
  vsprintf(s, format, argp);
  va_end(argp);
  size = sizeof(retval);
  status = db_get_value(hDB, 0, s, &retval, &size,
                        TID_DWORD, TRUE);
  return retval;
}
int odb_get_int (char * format, ...)
Definition at line 54 of file odb_wrapper.cpp.
References db_get_value(), hDB, MAX_ODB_PATH, size, status, TID_INT, and TRUE.
{
  char s[MAX_ODB_PATH];
  int  retval, size, status;
  va_list argp;
  va_start(argp, format);
  vsprintf(s, format, argp);
  va_end(argp);
  size = sizeof(retval);
  status = db_get_value(hDB, 0, s, &retval, &size,
                        TID_INT, TRUE);
  return retval;
}
WORD odb_get_word (char * format, ...)
Definition at line 71 of file odb_wrapper.cpp.
References db_get_value(), hDB, MAX_ODB_PATH, size, status, TID_WORD, and TRUE.
{
  char  s[MAX_ODB_PATH];
  int   size, status;
  WORD retval;
  va_list argp;
  va_start(argp, format);
  vsprintf(s, format, argp);
  va_end(argp);
  size = sizeof(retval);
  status = db_get_value(hDB, 0, s, &retval, &size,
                        TID_WORD, TRUE);
  return retval;
}
Variable Documentation
HNDLE hDB
Definition at line 9 of file odb_wrapper.cpp.