AlcapDAQ:Rootana: crate6_CAEN_TDC/mfe_mucap.c File Reference
crate6_CAEN_TDC/mfe_mucap.c File Reference
#include <stdio.h>
#include "midas.h"
#include "msystem.h"
#include "mcstd.h"
Defines
#define USE_EVENT_CHANNEL 1
#define SERVER_CACHE_SIZE 0
#define ODB_UPDATE_TIME 1000
#define DEFAULT_FE_TIMEOUT 60000
#define EQUIPMENT_COMMON_STR "\Event ID = WORD : 0\n\Trigger mask = WORD : 0\n\Buffer = STRING : [32] SYSTEM\n\Type = INT : 0\n\Source = INT : 0\n\Format = STRING : [8] FIXED\n\Enabled = BOOL : 0\n\Read on = INT : 0\n\Period = INT : 0\n\Event limit = DOUBLE : 0\n\Num subevents = DWORD : 0\n\Log history = INT : 0\n\Frontend host = STRING : [32] \n\Frontend name = STRING : [32] \n\Frontend file name = STRING : [256] \n\"
#define EQUIPMENT_STATISTICS_STR "\Events sent = DOUBLE : 0\n\Events per sec. = DOUBLE : 0\n\kBytes per sec. = DOUBLE : 0\n\"
Functions
INT frontend_init (void)
INT frontend_early_init (void)
INT frontend_exit (void)
INT frontend_loop (void)
INT begin_of_run (INT run_number, char *error)
INT pre_begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
INT poll_event (INT source, INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
int send_event (INT index)
void send_all_periodic_events (INT transition)
void interrupt_routine (void)
void interrupt_enable (BOOL flag)
void display (BOOL bInit)
INT tr_prestart (INT rn, char *error)
INT tr_start (INT rn, char *error)
INT tr_prestop (INT rn, char *error)
INT tr_prepause (INT rn, char *error)
INT tr_resume (INT rn, char *error)
INT manual_trigger (INT index, void *prpc_param[])
INT register_equipment (void)
void update_odb (EVENT_HEADER *pevent, HNDLE hKey, INT format)
int message_print (const char *msg)
BOOL logger_root ()
INT scheduler (void)
INT cnaf_callback (INT index, void *prpc_param[])
int main (int argc, char *argv[])
Variables
char * frontend_name
char * frontend_file_name
BOOL frontend_call_loop
INT max_event_size
INT max_event_size_frag
INT event_buffer_size
INT display_period
INT run_state
INT run_number
DWORD actual_time
DWORD actual_millitime
char host_name [HOST_NAME_LENGTH]
char exp_name [NAME_LENGTH]
INT max_bytes_per_sec
INT optimize = 0
INT fe_stop = 0
BOOL debug
DWORD auto_restart = 0
HNDLE hDB
EQUIPMENT equipment []
EQUIPMENT * interrupt_eq = NULL
EVENT_HEADER * interrupt_odb_buffer
BOOL interrupt_odb_buffer_valid
BOOL interrupt_enabled
Define Documentation
#define DEFAULT_FE_TIMEOUT 60000
Definition at line 320 of file mfe_mucap.c.
Referenced by main().
#define EQUIPMENT_COMMON_STR "\Event ID = WORD : 0\n\Trigger mask = WORD : 0\n\Buffer = STRING : [32] SYSTEM\n\Type = INT : 0\n\Source = INT : 0\n\Format = STRING : [8] FIXED\n\Enabled = BOOL : 0\n\Read on = INT : 0\n\Period = INT : 0\n\Event limit = DOUBLE : 0\n\Num subevents = DWORD : 0\n\Log history = INT : 0\n\Frontend host = STRING : [32] \n\Frontend name = STRING : [32] \n\Frontend file name = STRING : [256] \n\"
Definition at line 368 of file mfe_mucap.c.
Referenced by register_equipment().
#define EQUIPMENT_STATISTICS_STR "\Events sent = DOUBLE : 0\n\Events per sec. = DOUBLE : 0\n\kBytes per sec. = DOUBLE : 0\n\"
Definition at line 386 of file mfe_mucap.c.
Referenced by register_equipment().
#define ODB_UPDATE_TIME 1000
Definition at line 318 of file mfe_mucap.c.
Referenced by gen_idle(), interrupt_routine(), and scheduler().
#define SERVER_CACHE_SIZE 0
Definition at line 316 of file mfe_mucap.c.
Referenced by register_equipment(), and scheduler().
#define USE_EVENT_CHANNEL 1
Definition at line 312 of file mfe_mucap.c.
Function Documentation
INT begin_of_run (INT run_number, char * error)
Definition at line 295 of file crate.cpp.
{
  diag_print(1, "*** Begin of run %d ***\n", run_number);
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).bor != NULL) {
      int status = (*trigger_modules[i]).bor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  for(int i = 0; i < num_periodic_modules; i++) {
    if((*periodic_modules[i]).bor != NULL) {
      int status = (*periodic_modules[i]).bor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  cycle_active = 0;
  event_avail = false;
  between_runs = false;
  return SUCCESS;
}
INT cnaf_callback (INT index, void * prpc_param[])
Definition at line 1934 of file mfe_mucap.c.
References c, cam16i_q(), cam16i_rq(), cam16o_q(), cam24i_q(), cam24i_rq(), cam24o_q(), cam_crate_clear(), cam_crate_zinit(), cam_inhibit_clear(), cam_inhibit_set(), CDWORD, cmd, CNAF, CNAF_CRATE_CLEAR, CNAF_CRATE_ZINIT, CNAF_INHIBIT_CLEAR, CNAF_INHIBIT_SET, CNAF_nQ, CNAF_TEST, count, CPDWORD, CPWORD, debug, i, n, RPC_CNAF16, RPC_CNAF24, RPC_SUCCESS, size, and temp.
Referenced by main().
{
DWORD cmd, b, c, n, a, f, *pdword, *size, *x, *q, dtemp;
WORD  *pword, *pdata, temp;
INT   i, count;
  /* Decode parameters */
  cmd    = CDWORD(0);
  b      = CDWORD(1);
  c      = CDWORD(2);
  n      = CDWORD(3);
  a      = CDWORD(4);
  f      = CDWORD(5);
  pdword = CPDWORD(6);
  pword  = CPWORD(6);
  pdata  = CPWORD(6);
  size   = CPDWORD(7);
  x      = CPDWORD(8);
  q      = CPDWORD(9);
  /* determine repeat count */
  if (index == RPC_CNAF16)
    count = *size / sizeof(WORD);  /* 16 bit */
  else
    count = *size / sizeof(DWORD); /* 24 bit */
  switch (cmd)
    {
    /*---- special commands ----*/
    case CNAF_INHIBIT_SET:
      cam_inhibit_set(c);
      break;
    case CNAF_INHIBIT_CLEAR:
      cam_inhibit_clear(c);
      break;
    case CNAF_CRATE_CLEAR:
      cam_crate_clear(c);
      break;
    case CNAF_CRATE_ZINIT:
      cam_crate_zinit(c);
      break;
    case CNAF_TEST:
      break;
    case CNAF:
      if (index == RPC_CNAF16)
        {
        for (i=0 ; i<count ; i++)
          if (f<16)
            cam16i_q(c, n, a, f, pword++, (int *) x, (int *) q);
          else if (f<24)
            cam16o_q(c, n, a, f, pword[i], (int *) x, (int *) q);
          else
            cam16i_q(c, n, a, f, &temp, (int *) x, (int *) q);
        }
      else
        {
        for (i=0 ; i<count ; i++)
          if (f<16)
            cam24i_q(c, n, a, f, pdword++, (int *) x, (int *) q);
          else if (f<24)
            cam24o_q(c, n, a, f, pdword[i], (int *) x, (int *) q);
          else
            cam24i_q(c, n, a, f, &dtemp, (int *) x, (int *) q);
        }
      break;
    case CNAF_nQ:
      if (index == RPC_CNAF16)
        {
        if (f<16)
          cam16i_rq(c, n, a, f, (WORD **) &pdword, count);
        }
      else
        {
        if (f<16)
          cam24i_rq(c, n, a, f, &pdword, count);
        }
      /* return reduced return size */
      *size = (int) pdword - (int) pdata;
      break;
    default:
      printf("cnaf: Unknown command 0x%X\n",(unsigned int)cmd);
    }
  if (debug)
    {
    if (index == RPC_CNAF16)
      printf("cmd=%d r=%d c=%d n=%d a=%d f=%d d=%X x=%d q=%d\n",
              (int)cmd, (int)count, (int)c, (int)n, (int)a, (int)f, (int)pword[0], (int)*x, (int)*q);
    else if (index == RPC_CNAF24)
      printf("cmd=%d r=%d c=%d n=%d a=%d f=%d d=%X x=%d q=%d\n",
              (int)cmd, (int)count, (int)c, (int)n, (int)a, (int)f, (int)pdword[0], (int)*x, (int)*q);
    }
  return RPC_SUCCESS;
}
void display (BOOL bInit)
Definition at line 1347 of file mfe_mucap.c.
References eqpmnt::events_sent, FE_ERR_DISABLED, FE_ERR_HW, FE_ERR_ODB, FE_SUCCESS, frontend_name, host_name, i, name, eqpmnt::name, run_number, run_state, ss_clear_screen(), ss_printf(), STATE_RUNNING, STATE_STOPPED, eqpmnt::status, status, and time.
{
INT    i, status;
time_t full_time;
char   str[30];
  if (bInit)
    {
    ss_clear_screen();
    if (host_name[0])
      strcpy(str, host_name);
    else
      strcpy(str, "<local>");
    ss_printf(0, 0, "%s connected to %s. Press \"!\" to exit", frontend_name, str);
    ss_printf(0, 1, "================================================================================");
    ss_printf(0, 2, "Run status:   %s", run_state == STATE_STOPPED ? "Stopped" :
                                        run_state == STATE_RUNNING ? "Running" :
                                        "Paused");
    ss_printf(25,2, "Run number %d   ", run_number);
    ss_printf(0, 3, "================================================================================");
    ss_printf(0, 4, "Equipment     Status     Events     Events/sec Rate[kB/s] ODB->FE    FE->ODB");
    ss_printf(0, 5, "--------------------------------------------------------------------------------");
    for (i=0 ; equipment[i].name[0] ; i++)
      ss_printf(0, i+6, "%s", equipment[i].name);
    }
  /* display time */
  time(&full_time);
  strcpy(str, ctime(&full_time)+11);
  str[8] = 0;
  ss_printf(72, 0, "%s", str);
  for (i=0 ; equipment[i].name[0] ; i++)
    {
    status = equipment[i].status;
    if ((status == 0 || status == FE_SUCCESS) &&
        equipment[i].info.enabled)
      ss_printf(14, i+6, "OK       ");
    else if (!equipment[i].info.enabled)
      ss_printf(14, i+6, "Disabled ");
    else if (status == FE_ERR_ODB)
      ss_printf(14, i+6, "ODB Error");
    else if (status == FE_ERR_HW)
      ss_printf(14, i+6, "HW Error ");
    else if (status == FE_ERR_DISABLED)
      ss_printf(14, i+6, "Disabled ");
    else
      ss_printf(14, i+6, "Unknown  ");
    if (equipment[i].stats.events_sent > 1E9)
      ss_printf(25, i+6, "%1.3lfG     ", equipment[i].stats.events_sent/1E9);
    else if (equipment[i].stats.events_sent > 1E6)
      ss_printf(25, i+6, "%1.3lfM     ", equipment[i].stats.events_sent/1E6);
    else
      ss_printf(25, i+6, "%1.0lf      ", equipment[i].stats.events_sent);
    ss_printf(36, i+6, "%1.1lf      ", equipment[i].stats.events_per_sec);
    ss_printf(47, i+6, "%1.1lf      ", equipment[i].stats.kbytes_per_sec);
    ss_printf(58, i+6, "%ld       ", equipment[i].odb_in);
    ss_printf(69, i+6, "%ld       ", equipment[i].odb_out);
    }
  /* go to next line */
  ss_printf(0, i+6, "");
}
INT end_of_run (INT run_number, char * error)
Definition at line 330 of file crate.cpp.
{
  diag_print(1, "*** End of run %d ***\n", run_number);
  between_runs = true;
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).eor != NULL) {
      int status = (*trigger_modules[i]).eor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  for(int i = 0; i < num_periodic_modules; i++) {
    if((*periodic_modules[i]).eor != NULL) {
      int status = (*periodic_modules[i]).eor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  return SUCCESS;
}
INT frontend_early_init (void)
Definition at line 145 of file crate.cpp.
{
  // Determine our crate ID by comparing against a list of hostnames
  printf("Entering frontend_early_init ... \n");
  //char *hostnames[] = {"fe1", "fe2", "fe3", "turtle", "fe5", "fe6"};
  //char *hostnames[] = {"fe1", "fe2", "daq2.MuSIC", "fe4", "fe5", "fe6", "fe7"};
  //int crate_numbers[] = {1, 2, 3, 4, 5, 6, 9};
  //char *hostnames[] = {"daq2.MuSIC"};
  //int crate_numbers[] = {3};
  //BOOL crate_has_periodic[] = {FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE};
  //int num_hostnames = sizeof(hostnames)/sizeof(char *);
  //char my_hostname[256];
  //gethostname(my_hostname, sizeof(my_hostname));
#if 0
  BOOL has_periodic = FALSE;
  for(int i = 0; i < num_hostnames; i++) {
    if(!strcmp(my_hostname, hostnames[i])) {
      crate_number = crate_numbers[i];
      has_periodic = crate_has_periodic[i];
    }
  }
#endif
  crate_number = 3;
  BOOL has_periodic = FALSE;
  printf("Hostname and crate cumber defined, crate number = %d  ... \n",crate_number);
  if(crate_number > 0) {
    frontend_name = new char[32];
    strcpy(frontend_name, "Crate ");
#if 0
    sprintf(equipment[0].name, "Crate %d", crate_number);
    sprintf(equipment[0].info.buffer, "BUF%d", crate_number);
    equipment[0].info.event_id = 1000 + crate_number;
#endif
    frontend_index = crate_number;
    printf("Crate number = %d\n",crate_number);
    if(has_periodic) {
      sprintf(equipment[1].name, "Periodic %d", crate_number);
      equipment[1].info.event_id = 2000 + crate_number;
    } else {
      sprintf(equipment[1].name, "");
    }
  }
  printf("Frontend early init returns success \n");
  return SUCCESS;
}
INT frontend_exit (void)
Definition at line 244 of file crate.cpp.
{
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).exit != NULL) {
      (*trigger_modules[i]).exit();
    }
  }
  for(int i = 0; i < num_periodic_modules; i++) {
    if((*periodic_modules[i]).exit != NULL) {
      (*periodic_modules[i]).exit();
    }
  }
  return SUCCESS;
}
INT frontend_init (void)
Definition at line 207 of file crate.cpp.
{
  printf("Entering frontend_init() ... \n");
  INT run_state = odb_get_int("/Runinfo/State");
  if (run_state != STATE_STOPPED) {
    cm_msg(MERROR, "Crate",
            "Run must be stopped before starting crate program.");
    return FE_ERR_HW;
  }
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).init != NULL) {
      int status = (*trigger_modules[i]).init();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  for(int i = 0; i < num_periodic_modules; i++) {
    if((*periodic_modules[i]).init != NULL) {
      int status = (*periodic_modules[i]).init();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  return SUCCESS;
}
INT frontend_loop (void)
Definition at line 435 of file crate.cpp.
{
  // If we're going to be pre-empted, get it over with during livetime
  // rather than deadtime.
  if (cycle_active || run_state != STATE_RUNNING || between_runs == TRUE) {
    dm_area_flush();
    sched_yield();
  }
  // Exit immediately if no run in progress
  if (run_state != STATE_RUNNING || between_runs == TRUE) {
    return SUCCESS;
  }
  // Call appropriate poll functions, depending on whether we're live or dead
  //printf("fe loop: cycle_active %i\n",cycle_active);
  if (cycle_active) {
    for(int i = 0; i < num_trigger_modules; i++) {
      if((*trigger_modules[i]).poll_live != NULL) {
        // There are conditions that can lead to changes in run state between
        // modules...
        if (run_state != STATE_RUNNING || between_runs == TRUE) {
          return SUCCESS;
        }
        int status = (*trigger_modules[i]).poll_live();
        if(status == FE_END_BLOCK) {
          cycle_active = 0;
          event_avail = true;
        } else if(status == FE_NEED_STOP) {
          stop_cycle();
        } else if(status != SUCCESS) {
          return status;
        }
      }
    }
  } else {
    consider_start();
  }
  return SUCCESS;
}
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Definition at line 505 of file crate.cpp.
{
    switch (cmd) {
    case CMD_INTERRUPT_ENABLE:
        interrupts_enabled = TRUE;
        break;
    case CMD_INTERRUPT_DISABLE:
        interrupts_enabled = FALSE;
        break;
    case CMD_INTERRUPT_ATTACH:
        interrupt_handler = (void (*)(void)) adr;
        break;
    case CMD_INTERRUPT_DETACH:
        interrupts_enabled = FALSE;
        interrupt_handler = NULL;
        break;
    }
    return SUCCESS;
}
void interrupt_enable (BOOL flag)
Definition at line 1248 of file mfe_mucap.c.
References CMD_INTERRUPT_DISABLE, CMD_INTERRUPT_ENABLE, interrupt_configure(), and interrupt_enabled.
Referenced by main(), scheduler(), tr_pause(), tr_prepause(), tr_prestop(), tr_resume(), tr_start(), and tr_stop().
{
  interrupt_enabled = flag;
  if (interrupt_eq)
  {
    if (interrupt_enabled)
      interrupt_configure(CMD_INTERRUPT_ENABLE,0,0);
    else
      interrupt_configure(CMD_INTERRUPT_DISABLE,0,0);
  }
}
void interrupt_routine (void)
Definition at line 1263 of file mfe_mucap.c.
References actual_millitime, actual_time, eqpmnt::buffer_handle, eqpmnt::bytes_sent, cm_msg, EVENT_HEADER::data_size, dm_pointer_get(), dm_pointer_increment(), EQUIPMENT_INFO::event_id, EVENT_HEADER::event_id, eqpmnt::events_sent, EQUIPMENT_INFO::history, eqpmnt::info, interrupt_odb_buffer_valid, eqpmnt::last_called, MERROR, eqpmnt::odb_out, ODB_UPDATE_TIME, EQUIPMENT_INFO::read_on, eqpmnt::readout, RO_ODB, rpc_send_event(), eqpmnt::serial_number, EVENT_HEADER::serial_number, SYNC, EVENT_HEADER::time_stamp, EQUIPMENT_INFO::trigger_mask, EVENT_HEADER::trigger_mask, and TRUE.
Referenced by register_equipment().
{
  EVENT_HEADER *pevent;
  /* get pointer for upcoming event.
  This is a blocking call if no space available */
#ifndef USE_PVIC
  if ((pevent = dm_pointer_get()) == NULL)
    cm_msg(MERROR, "interrupt_routine", "interrupt, dm_pointer_get returned NULL");
#else
  if ((pevent = pvic_pointer_get()) == NULL)
    cm_msg(MERROR, "interrupt_routine", "interrupt, pvic_pointer_get returned NULL");
#endif
  /* compose MIDAS event header */
  pevent->event_id      = interrupt_eq->info.event_id;
  pevent->trigger_mask  = interrupt_eq->info.trigger_mask;
  pevent->data_size     = 0;
  pevent->time_stamp    = actual_time;
  pevent->serial_number = interrupt_eq->serial_number++;
  /* call user readout routine */
  pevent->data_size = interrupt_eq->readout((char *) (pevent+1), 0);
  /* send event */
  if (pevent->data_size)
  {
    interrupt_eq->bytes_sent += pevent->data_size + sizeof(EVENT_HEADER);
    interrupt_eq->events_sent++;
    if (interrupt_eq->buffer_handle)
    {
#ifdef USE_EVENT_CHANNEL
      dm_pointer_increment(interrupt_eq->buffer_handle,
        pevent->data_size + sizeof(EVENT_HEADER));
#else
#ifdef USE_PVIC
      pvic_send_event(interrupt_eq->buffer_handle, pevent,
        pevent->data_size + sizeof(EVENT_HEADER), SYNC);
#else
      rpc_send_event(interrupt_eq->buffer_handle, pevent,
        pevent->data_size + sizeof(EVENT_HEADER), SYNC);
#endif
#endif
   }
    /* send event to ODB */
    if (interrupt_eq->info.read_on & RO_ODB ||
      interrupt_eq->info.history)
    {
      if (actual_millitime - interrupt_eq->last_called > ODB_UPDATE_TIME)
      {
        interrupt_eq->last_called = actual_millitime;
        memcpy(interrupt_odb_buffer, pevent, pevent->data_size + sizeof(EVENT_HEADER));
        interrupt_odb_buffer_valid = TRUE;
        interrupt_eq->odb_out++;
      }
    }
  }
  else
    interrupt_eq->serial_number--;
}
BOOL logger_root ()
Definition at line 1417 of file mfe_mucap.c.
References db_enum_key(), db_find_key(), db_get_value(), DB_NO_MORE_SUBKEYS, DB_SUCCESS, equal_ustring(), FALSE, hDB, hKey, i, size, status, TID_STRING, and TRUE.
Referenced by scheduler().
{
int   size, i, status;
char  str[80];
HNDLE hKeyRoot, hKey;
  if (db_find_key(hDB, 0, "/Logger/Channels", &hKeyRoot) == DB_SUCCESS)
    {
    for (i=0;  ; i++)
      {
      status = db_enum_key(hDB, hKeyRoot, i, &hKey);
      if (status == DB_NO_MORE_SUBKEYS)
        break;
      strcpy(str, "MIDAS");
      size = sizeof(str);
      db_get_value(hDB, hKey, "Settings/Format", str, &size, TID_STRING, TRUE);
      if (equal_ustring(str, "ROOT"))
        return TRUE;
      }
    }
  return FALSE;
}
int main (int argc, char * argv[])
Definition at line 2042 of file mfe_mucap.c.
References eqpmnt::cd, cm_cleanup(), cm_connect_experiment1(), cm_disconnect_experiment(), cm_get_environment(), cm_get_experiment_database(), cm_msg, cm_register_function(), cm_register_transition(), cm_set_msg_print(), cm_set_watchdog_params(), CM_SHUTDOWN, cm_shutdown(), CM_SUCCESS, cm_synchronize(), CMD_EXIT, CMD_INTERRUPT_DETACH, CMD_INTERRUPT_DISABLE, cnaf_callback(), daemon, debug, DEFAULT_FE_TIMEOUT, DEFAULT_ODB_SIZE, display, display_period, dm_buffer_create(), dm_buffer_release(), EQ_SLOW, event_buffer_size, exp_name, FALSE, FE_SUCCESS, frontend_early_init(), frontend_exit(), frontend_init(), frontend_name, hDB, host_name, i, eqpmnt::info, interrupt_configure(), interrupt_enable(), MAX_EVENT_SIZE, max_event_size, max_event_size_frag, MERROR, message_print(), MT_ALL, eqpmnt::name, register_equipment(), RPC_CNAF16, RPC_CNAF24, RPC_OTIMEOUT, rpc_set_option(), RPC_SHUTDOWN, run_state, scheduler(), EQUIPMENT_INFO::source, ss_clear_screen(), ss_daemon_init(), ss_getchar(), ss_printf(), ss_sleep(), STATE_RUNNING, eqpmnt::status, status, SUCCESS, tr_prepause(), tr_prestart, tr_prestop(), tr_resume(), TR_RESUME, tr_start(), TR_START, TRUE, and usage().
{
INT  status, i, dm_size;
INT  daemon;
  host_name[0] = 0;
  exp_name[0] = 0;
  debug = FALSE;
  daemon = 0;
  setbuf(stdout,0);
  setbuf(stderr,0);
#ifdef SIGPIPE
  signal(SIGPIPE,SIG_IGN);
#endif
#ifdef OS_VXWORKS
  if (ahost_name)
    strcpy(host_name, ahost_name);
  if (aexp_name)
    strcpy(exp_name, aexp_name);
  debug = adebug;
#else
  /* get default from environment */
  cm_get_environment(host_name, sizeof(host_name), exp_name, sizeof(exp_name));
  /* parse command line parameters */
  for (i=1 ; i<argc ; i++)
    {
    if (argv[i][0] == '-' && argv[i][1] == 'd')
      debug = TRUE;
    else if (argv[i][0] == '-' && argv[i][1] == 'D')
      daemon = 1;
    else if (argv[i][0] == '-' && argv[i][1] == 'O')
      daemon = 2;
    else if (argv[i][0] == '-')
      {
      if (i+1 >= argc || argv[i+1][0] == '-')
        goto usage;
      if (argv[i][1] == 'e')
        strcpy(exp_name, argv[++i]);
      else if (argv[i][1] == 'h')
        strcpy(host_name, argv[++i]);
      else
        {
usage:
        printf("usage: frontend [-h Hostname] [-e Experiment] [-d] [-D] [-O]\n");
        printf("         [-d]     Used to debug the frontend\n");
        printf("         [-D]     Become a daemon\n");
        printf("         [-O]     Become a daemon but keep stdout\n");
        return 0;
        }
      }
    }
#endif
#ifdef PART_OF_MUCAP
  frontend_early_init();
#endif
  /* check event and buffer sizes */
  if (event_buffer_size < 2*max_event_size)
    {
    printf("event_buffer_size too small for max. event size\n");
    ss_sleep(5000);
    return 1;
    }
  if (max_event_size > MAX_EVENT_SIZE)
    {
    printf("Requested max_event_size (%d) exceeds max. system event size (%d)",
            max_event_size, MAX_EVENT_SIZE);
    ss_sleep(5000);
    return 1;
    }
  dm_size = event_buffer_size;
#ifdef OS_VXWORKS
  /* override dm_size in case of VxWorks
     take remaining free memory and use 20% of it for dm_ */
  dm_size = 2*10*(max_event_size + sizeof(EVENT_HEADER) + sizeof(INT));
  if (dm_size > memFindMax())
    {
    cm_msg(MERROR,"mainFE","Not enough mem space for event size");
    return 0;
    }
  /* takes overall 20% of the available memory resource for dm_() */
  dm_size = 0.2 * memFindMax();
  /* there are two buffers */
  dm_size /= 2;
#endif
  /* reduce memory size for MS-DOS */
#ifdef OS_MSDOS
  if (dm_size > 0x4000)
    dm_size = 0x4000; /* 16k */
#endif
  /* inform user of settings */
  printf("Event buffer size      :     %d\n", event_buffer_size);
  printf("Buffer allocation      : 2 x %d\n", dm_size);
  printf("System max event size  :     %d\n", MAX_EVENT_SIZE);
  printf("User max event size    :     %d\n", max_event_size);
  if (max_event_size_frag > 0)
    printf("User max frag. size    :     %d\n", max_event_size_frag);
  printf("# of events per buffer :     %d\n\n", dm_size/max_event_size);
  if (daemon)
    {
    printf("\nBecoming a daemon...\n");
    ss_daemon_init(daemon == 2);
    }
  /* now connect to server */
  if (display_period)
    {
    if (host_name[0])
      printf("Connect to experiment %s on host %s...", exp_name, host_name);
    else
      printf("Connect to experiment %s...", exp_name);
    }
  status = cm_connect_experiment1(host_name, exp_name, frontend_name,
                                  NULL, DEFAULT_ODB_SIZE, DEFAULT_FE_TIMEOUT);
  if (status != CM_SUCCESS)
    {
    /* let user read message before window might close */
    ss_sleep(5000);
    return 1;
    }
  if (display_period)
    printf("OK\n");
  /* book buffer space */
  status = dm_buffer_create(dm_size, max_event_size);
  if (status != CM_SUCCESS)
    {
    printf("dm_buffer_create: Not enough memory or event too big\n");
    return 1;
    }
  /* remomve any dead frontend */
  cm_cleanup(frontend_name, FALSE);
  /* shutdown previous frontend */
  status = cm_shutdown(frontend_name, FALSE);
  if (status == CM_SHUTDOWN && display_period)
    {
    printf("Previous frontend stopped\n");
    ss_sleep(1000);
    }
  /* register transition callbacks */
  if (cm_register_transition(TR_START, tr_start) != CM_SUCCESS ||
      cm_register_transition(TR_PRESTART, tr_prestart) != CM_SUCCESS ||
      cm_register_transition(TR_PRESTOP, tr_prestop) != CM_SUCCESS ||
      cm_register_transition(TR_PREPAUSE, tr_prepause) != CM_SUCCESS ||
      cm_register_transition(TR_RESUME, tr_resume) != CM_SUCCESS)
    {
    printf("Failed to start local RPC server");
    cm_disconnect_experiment();
    dm_buffer_release();
    /* let user read message before window might close */
    ss_sleep(5000);
    return 1;
    }
  /* register CNAF callback */
#ifndef PART_OF_MUCAP
  cm_register_function(RPC_CNAF16, cnaf_callback);
  cm_register_function(RPC_CNAF24, cnaf_callback);
#endif
  cm_get_experiment_database(&hDB, &status);
  /* set time from server */
#ifdef OS_VXWORKS
  cm_synchronize(NULL);
#endif
  /* turn off watchdog if in debug mode */
  if (debug)
    cm_set_watchdog_params(TRUE, 0);
  /* increase RPC timeout to 2min for logger with exabyte or blocked disk */
  rpc_set_option(-1, RPC_OTIMEOUT, 120000);
  /* set own message print function */
  if (display_period)
    cm_set_msg_print(MT_ALL, MT_ALL, message_print);
  /* call user init function */
  if (display_period)
    printf("Init hardware...");
  if (frontend_init() != SUCCESS)
    {
    if (display_period)
      printf("\n");
    cm_disconnect_experiment();
    dm_buffer_release();
    /* let user read message before window might close */
    ss_sleep(5000);
    return 1;
    }
  /* reqister equipment in ODB */
  if (register_equipment() != SUCCESS)
    {
    if (display_period)
      printf("\n");
    cm_disconnect_experiment();
    dm_buffer_release();
    /* let user read message before window might close */
    ss_sleep(5000);
    return 1;
    }
  if (display_period)
    printf("OK\n");
  /* initialize screen display */
  if (display_period)
    {
    ss_sleep(1000);
    display(TRUE);
    }
  /* switch on interrupts if running */
  if (interrupt_eq && run_state == STATE_RUNNING)
    interrupt_enable(TRUE);
  /* initialize ss_getchar */
  ss_getchar(0);
  /* call main scheduler loop */
  status = scheduler();
  /* reset terminal */
  ss_getchar(TRUE);
  /* switch off interrupts */
  if (interrupt_eq)
    {
    interrupt_configure(CMD_INTERRUPT_DISABLE, 0, 0);
    interrupt_configure(CMD_INTERRUPT_DETACH, 0, 0);
    if (interrupt_odb_buffer)
      free(interrupt_odb_buffer);
    }
  /* detach interrupts */
  if (interrupt_eq != NULL)
    interrupt_configure(CMD_INTERRUPT_DETACH, interrupt_eq->info.source, 0);
  /* call user exit function */
  frontend_exit();
  /* close slow control drivers */
  for (i=0 ; equipment[i].name[0] ; i++)
    if ((equipment[i].info.eq_type & EQ_SLOW) &&
        equipment[i].status == FE_SUCCESS)
      equipment[i].cd(CMD_EXIT, &equipment[i]);
  /* close network connection to server */
  cm_disconnect_experiment();
  if (display_period)
    {
    if (status == RPC_SHUTDOWN)
      {
      ss_clear_screen();
      ss_printf(0, 0, "Frontend shut down.");
      ss_printf(0, 1, "");
      }
    }
  if (status != RPC_SHUTDOWN)
    printf("Network connection aborted.\n");
  dm_buffer_release();
  return 0;
}
INT manual_trigger (INT index, void * prpc_param[])
Definition at line 536 of file mfe_mucap.c.
References CWORD, display, display_period, event_id, FALSE, i, eqpmnt::name, send_event(), and SUCCESS.
Referenced by register_equipment().
{
WORD event_id, i;
  event_id = CWORD(0);
  for (i=0 ; equipment[i].name[0] ; i++)
    if (equipment[i].info.event_id == event_id)
      send_event(i);
  if (display_period)
    display(FALSE);
  return SUCCESS;
}
int message_print (const char * msg)
Definition at line 1329 of file mfe_mucap.c.
References ss_printf().
Referenced by main().
{
char str[160];
  memset(str, ' ', 159);
  str[159] = 0;
  if (msg[0] == '[')
    msg = strchr(msg, ']')+2;
  memcpy(str, msg, strlen(msg));
  ss_printf(0, 20, str);
  return 0;
}
INT pause_run (INT run_number, char * error)
Definition at line 362 of file crate.cpp.
{
    return SUCCESS;
}
INT poll_event (INT source, INT count, BOOL test)
Definition at line 486 of file crate.cpp.
{
    INT retval = false;
    if(!test) {
      count = 1;
    }
    for (int i = 0; i < count; i++) {
        frontend_loop();
        if(event_avail) {
          retval = true;
        }
    }
    return retval;
}
INT pre_begin_of_run (INT run_number, char * error)
Definition at line 264 of file crate.cpp.
{
  diag_print(1, "*** Before begin of run %d ***\n", run_number);
  for(int i = 0; i < num_trigger_modules; i++) {
    if((*trigger_modules[i]).pre_bor != NULL) {
      int status = (*trigger_modules[i]).pre_bor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  for(int i = 0; i < num_periodic_modules; i++) {
    if((*periodic_modules[i]).pre_bor != NULL) {
      int status = (*periodic_modules[i]).pre_bor();
      if(status != SUCCESS) {
        return status;
      }
    }
  }
  return SUCCESS;
}
INT register_equipment (void)
Definition at line 554 of file mfe_mucap.c.
References BM_CREATED, bm_open_buffer(), bm_set_cache_size(), BM_SUCCESS, EQUIPMENT_INFO::buffer, eqpmnt::buffer_handle, eqpmnt::cd, cm_msg, cm_register_function(), CMD_INIT, CMD_INTERRUPT_ATTACH, count, db_create_key(), db_create_record(), db_delete_key(), db_find_key(), db_get_value(), db_open_record(), db_set_record(), db_set_value(), DB_SUCCESS, delta_time, display_period, driver, eqpmnt::driver, EQUIPMENT_INFO::enabled, EQ_INTERRUPT, EQ_MANUAL_TRIG, EQ_POLLED, EQ_SLOW, EQUIPMENT_INFO::eq_type, equal_ustring(), EQUIPMENT_COMMON_STR, EQUIPMENT_STATISTICS_STR, EVENT_BUFFER_SIZE, EQUIPMENT_INFO::event_id, EQUIPMENT_INFO::event_limit, EQUIPMENT_STATS::events_per_sec, EQUIPMENT_STATS::events_sent, FALSE, FE_ERR_DISABLED, FE_SUCCESS, format(), eqpmnt::format, EQUIPMENT_INFO::format, FORMAT_FIXED, FORMAT_MIDAS, FORMAT_YBOS, frontend_file_name, EQUIPMENT_INFO::frontend_file_name, EQUIPMENT_INFO::frontend_host, frontend_name, EQUIPMENT_INFO::frontend_name, hDB, hKey, eqpmnt::hkey_variables, i, index, eqpmnt::info, BANK_LIST::init_str, interrupt_configure(), interrupt_routine(), j, k, EQUIPMENT_STATS::kbytes_per_sec, manual_trigger(), MAX_EVENT_SIZE, MERROR, MINFO, MODE_READ, MODE_WRITE, n, DEVICE_DRIVER::name, BANK_LIST::name, name, eqpmnt::name, EQUIPMENT_INFO::period, eqpmnt::poll_count, poll_event(), PTYPE, RPC_MANUAL_TRIG, rpc_tid_size(), run_number, run_state, SERVER_CACHE_SIZE, size, EQUIPMENT_INFO::source, ss_millitime(), ss_sleep(), start_time, STATE_STOPPED, eqpmnt::stats, eqpmnt::status, status, strcomb(), SUCCESS, TID_DOUBLE, TID_INT, TID_KEY, TID_STRUCT, TRUE, and BANK_LIST::type.
Referenced by main().
{
INT    index, count, size, status, i, j, k, n;
char   str[256];
EQUIPMENT_INFO *eq_info;
EQUIPMENT_STATS *eq_stats;
DWORD  start_time, delta_time;
HNDLE  hKey;
BOOL   manual_trig_flag = FALSE;
BANK_LIST *bank_list;
DWORD  dummy;
  /* get current ODB run state */
  size = sizeof(run_state);
  run_state = STATE_STOPPED;
  db_get_value(hDB, 0, "/Runinfo/State", &run_state, &size, TID_INT, TRUE);
  size = sizeof(run_number);
  run_number = 1;
  db_get_value(hDB, 0, "/Runinfo/Run number", &run_number, &size, TID_INT, TRUE);
  /* scan EQUIPMENT table from FRONTEND.C */
  for (index=0 ; equipment[index].name[0] ; index++)
    {
    eq_info = &equipment[index].info;
    eq_stats = &equipment[index].stats;
    if (eq_info->event_id == 0)
      {
      printf("Event ID 0 for %s not allowed\n", equipment[index].name);
      ss_sleep(5000);
      }
    /* init status */
    equipment[index].status = FE_SUCCESS;
    sprintf(str, "/Equipment/%s/Common", equipment[index].name);
    /* get last event limit from ODB */
    if (eq_info->eq_type != EQ_SLOW)
      {
      db_find_key(hDB, 0, str, &hKey);
      size = sizeof(double);
      if (hKey)
        db_get_value(hDB, hKey, "Event limit", &eq_info->event_limit, &size, TID_DOUBLE, TRUE);
      }
    /* Create common subtree */
    status = db_create_record(hDB, 0, str, EQUIPMENT_COMMON_STR);
    if (status != DB_SUCCESS)
      {
      printf("Cannot init equipment record, probably other FE is using it\n");
      ss_sleep(3000);
      }
    db_find_key(hDB, 0, str, &hKey);
    if (equal_ustring(eq_info->format, "YBOS"))
      equipment[index].format = FORMAT_YBOS;
    else if (equal_ustring(eq_info->format, "FIXED"))
      equipment[index].format = FORMAT_FIXED;
    else /* default format is MIDAS */
      equipment[index].format = FORMAT_MIDAS;
    gethostname(eq_info->frontend_host, sizeof(eq_info->frontend_host));
    strcpy(eq_info->frontend_name, frontend_name);
    strcpy(eq_info->frontend_file_name, frontend_file_name);
    /* set record from equipment[] table in frontend.c */
    db_set_record(hDB, hKey, eq_info, sizeof(EQUIPMENT_INFO), 0);
    /* open hot link to equipment info */
    db_open_record(hDB, hKey, eq_info, sizeof(EQUIPMENT_INFO), MODE_READ, NULL, NULL);
    /*---- Create variables record ---------------------------------*/
    sprintf(str, "/Equipment/%s/Variables", equipment[index].name);
    if (equipment[index].event_descrip)
      {
      if (equipment[index].format == FORMAT_FIXED)
        db_create_record(hDB, 0, str, (char *)equipment[index].event_descrip);
      else
        {
        /* create bank descriptions */
        bank_list = (BANK_LIST *)equipment[index].event_descrip;
        for (; bank_list->name[0] ; bank_list++)
          {
          /* mabye needed later...
          if (bank_list->output_flag == 0)
            continue;
          */
          if (bank_list->type == TID_STRUCT)
            {
            sprintf(str, "/Equipment/%s/Variables/%s", equipment[index].name, bank_list->name);
            db_create_record(hDB, 0, str, strcomb(bank_list->init_str));
            }
          else
            {
            sprintf(str, "/Equipment/%s/Variables/%s", equipment[index].name, bank_list->name);
            dummy = 0;
            db_set_value(hDB, 0, str, &dummy, rpc_tid_size(bank_list->type), 1, bank_list->type);
            }
          }
        }
      }
    else
      db_create_key(hDB, 0, str, TID_KEY);
    sprintf(str, "/Equipment/%s/Variables", equipment[index].name);
    db_find_key(hDB, 0, str, &hKey);
    equipment[index].hkey_variables = hKey;
    /*---- Create and initialize statistics tree -------------------*/
    sprintf(str, "/Equipment/%s/Statistics", equipment[index].name);
    /*-PAA- Needed in case Statistics exists but size = 0 */
    /*-SR- Not needed since db_create_record does a delete already */
    status = db_find_key(hDB, 0, str, &hKey);
    if (status == DB_SUCCESS)
      {
      status = db_delete_key(hDB, hKey, FALSE);
      if (status != DB_SUCCESS)
        {
          printf("Cannot delete statistics record, error %d\n",status);
          ss_sleep(3000);
        }
      }
    status = db_create_record(hDB, 0, str, EQUIPMENT_STATISTICS_STR);
    if (status != DB_SUCCESS)
      {
      printf("Cannot create statistics record, error %d\n",status);
      ss_sleep(3000);
      }
    status = db_find_key(hDB, 0, str, &hKey);
    if (status != DB_SUCCESS)
      {
      printf("Cannot find statistics record, error %d\n",status);
      ss_sleep(3000);
      }
    eq_stats->events_sent = 0;
    eq_stats->events_per_sec = 0;
    eq_stats->kbytes_per_sec = 0;
    /* open hot link to statistics tree */
    status = db_open_record(hDB, hKey, eq_stats, sizeof(EQUIPMENT_STATS), MODE_WRITE, NULL, NULL);
    if (status != DB_SUCCESS)
      {
      printf("Cannot open statistics record, error %d. Probably other FE is using it\n",status);
      ss_sleep(3000);
      }
    /*---- open event buffer ---------------------------------------*/
    if (eq_info->buffer[0])
      {
      status = bm_open_buffer(eq_info->buffer, EVENT_BUFFER_SIZE, &equipment[index].buffer_handle);
      if (status != BM_SUCCESS && status != BM_CREATED)
        {
        cm_msg(MERROR, "register_equipment",
               "Cannot open event buffer. Try to reduce EVENT_BUFFER_SIZE in midas.h \
and rebuild the system.");
        return 0;
        }
      /* set the default buffer cache size */
      bm_set_cache_size(equipment[index].buffer_handle, 0, SERVER_CACHE_SIZE);
      }
    else
      equipment[index].buffer_handle = 0;
    /*---- evaluate polling count ----------------------------------*/
    if (eq_info->eq_type & EQ_POLLED)
      {
      if (display_period)
        printf("\nCalibrating");
      count = 1;
      do
        {
        if (display_period)
          printf(".");
        start_time = ss_millitime();
        poll_event(equipment[index].info.source, count, TRUE);
        delta_time = ss_millitime() - start_time;
        if (delta_time > 0)
          count = (INT) ((double) count * 100 / delta_time);
        else
          count*=100;
        } while (delta_time > 120 || delta_time < 80);
      equipment[index].poll_count = (INT) ((double) eq_info->period / 100 * count);
      if (display_period)
        printf("OK\n");
      }
    /*---- initialize interrupt events -----------------------------*/
    if (eq_info->eq_type & EQ_INTERRUPT)
      {
      /* install interrupt for interrupt events */
      for (i=0 ; equipment[i].name[0] ; i++)
        if (equipment[i].info.eq_type & EQ_POLLED)
          {
          equipment[index].status = FE_ERR_DISABLED;
          cm_msg(MINFO, "register_equipment",
            "Interrupt readout cannot be combined with polled readout");
          }
      if (equipment[index].status != FE_ERR_DISABLED)
        {
        if (eq_info->enabled)
          {
          if (interrupt_eq)
            {
            equipment[index].status = FE_ERR_DISABLED;
            cm_msg(MINFO, "register_equipment",
              "Defined more than one equipment with interrupt readout");
            }
          else
            {
            interrupt_configure(CMD_INTERRUPT_ATTACH, eq_info->source, (PTYPE) interrupt_routine);
            interrupt_eq = &equipment[index];
            interrupt_odb_buffer = malloc(MAX_EVENT_SIZE+sizeof(EVENT_HEADER));
            }
          }
        else
          {
          equipment[index].status = FE_ERR_DISABLED;
          cm_msg(MINFO, "register_equipment", "Equipment %s disabled in file \"frontend.c\"",
                         equipment[index].name);
          }
        }
      }
    /*---- initialize slow control equipment -----------------------*/
    if (eq_info->eq_type & EQ_SLOW)
      {
      /* resolve duplicate device names */
      for (i=0 ; equipment[index].driver[i].name[0] ; i++)
        for (j=i+1 ; equipment[index].driver[j].name[0] ; j++)
          if (equal_ustring(equipment[index].driver[i].name,
                            equipment[index].driver[j].name))
            {
            strcpy(str, equipment[index].driver[i].name);
            for (k=0,n=0 ; equipment[index].driver[k].name[0] ; k++)
              if (equal_ustring(str, equipment[index].driver[k].name))
                sprintf(equipment[index].driver[k].name, "%s_%d", str, n++);
            break;
            }
      /* loop over equipment list and call class driver's init method */
      if (eq_info->enabled)
        equipment[index].status = equipment[index].cd(CMD_INIT, &equipment[index]);
      else
        {
        equipment[index].status = FE_ERR_DISABLED;
        cm_msg(MINFO, "register_equipment", "Equipment %s disabled in file \"frontend.c\"",
                       equipment[index].name);
        }
      /* let user read error messages */
      if (equipment[index].status != FE_SUCCESS)
        ss_sleep(3000);
      }
    /*---- register callback for manual triggered events -----------*/
    if (eq_info->eq_type & EQ_MANUAL_TRIG)
      {
      if (!manual_trig_flag)
        cm_register_function(RPC_MANUAL_TRIG, manual_trigger);
      manual_trig_flag = TRUE;
      }
    }
  return SUCCESS;
}
INT resume_run (INT run_number, char * error)
Definition at line 371 of file crate.cpp.
{
    return SUCCESS;
}
INT scheduler (void)
Definition at line 1446 of file mfe_mucap.c.
References actual_millitime, actual_time, ASYNC, auto_restart, bm_flush_cache(), BM_SUCCESS, eqpmnt::buffer_handle, eqpmnt::bytes_sent, eqpmnt::cd, cm_check_deferred_transition(), cm_msg, CM_SUCCESS, cm_transition(), cm_yield(), CMD_IDLE, EVENT_HEADER::data_size, db_get_value(), db_send_changed_records(), DB_SUCCESS, display, display_period, dm_area_flush(), dm_pointer_get(), dm_pointer_increment(), EQUIPMENT_INFO::enabled, eq, EQ_INTERRUPT, EQ_PERIODIC, EQ_POLLED, EQ_SLOW, EQUIPMENT_INFO::eq_type, EQUIPMENT_INFO::event_id, EVENT_HEADER::event_id, EQUIPMENT_INFO::event_limit, EQUIPMENT_STATS::events_per_sec, EQUIPMENT_STATS::events_sent, eqpmnt::events_sent, FALSE, fe_stop, FE_SUCCESS, flag, eqpmnt::format, frontend_call_loop, frontend_loop(), hDB, EQUIPMENT_INFO::history, eqpmnt::hkey_variables, i, index, eqpmnt::info, interrupt_enable(), interrupt_odb_buffer_valid, j, EQUIPMENT_STATS::kbytes_per_sec, eqpmnt::last_called, eqpmnt::last_idle, logger_root(), MAX, max_bytes_per_sec, max_event_size, MERROR, MTALK, eqpmnt::name, NET_TCP_SIZE, EQUIPMENT_INFO::num_subevents, eqpmnt::odb_out, ODB_UPDATE_TIME, optimize, EQUIPMENT_INFO::period, eqpmnt::poll_count, poll_event(), EQUIPMENT_INFO::read_on, eqpmnt::readout, RO_ODB, RO_PAUSED, RO_RUNNING, RO_STOPPED, rpc_flush_event(), RPC_FTCP, RPC_OTRANSPORT, rpc_send_event(), rpc_set_opt_tcp_size(), rpc_set_option(), RPC_SHUTDOWN, RPC_SUCCESS, RPC_TCP, run_number, run_state, send_event(), eqpmnt::serial_number, EVENT_HEADER::serial_number, SERVER_CACHE_SIZE, size, EQUIPMENT_INFO::source, SS_ABORT, ss_getchar(), ss_kbhit(), ss_millitime(), SS_NO_MEMORY, ss_printf(), ss_time(), STATE_PAUSED, STATE_RUNNING, STATE_STOPPED, eqpmnt::stats, eqpmnt::status, status, eqpmnt::subevent_number, SUCCESS, SYNC, TID_BOOL, TID_INT, EVENT_HEADER::time_stamp, TR_START, TR_STOP, EQUIPMENT_INFO::trigger_mask, EVENT_HEADER::trigger_mask, TRUE, and update_odb().
Referenced by main().
{
EQUIPMENT_INFO *eq_info;
EQUIPMENT      *eq;
EVENT_HEADER   *pevent;
DWORD          last_time_network=0, last_time_display=0,
               last_time_flush=0, readout_start;
INT            i, j, index, status, ch, source, size, state;
char           str[80];
BOOL           buffer_done, flag, force_update = FALSE;
INT opt_max=0, opt_index=0, opt_tcp_size=128, opt_cnt=0;
INT err;
#ifdef OS_VXWORKS
  rpc_set_opt_tcp_size(1024);
#ifdef PPCxxx
  rpc_set_opt_tcp_size(NET_TCP_SIZE);
#endif
#endif
  /*----------------- MAIN equipment loop ------------------------------*/
  do
    {
    actual_millitime = ss_millitime();
    actual_time = ss_time();
    /*---- loop over equipment table -------------------------------*/
    for (index=0 ; ; index++)
      {
      eq = &equipment[index];
      eq_info = &eq->info;
      /* check if end of equipment list */
      if (!eq->name[0])
        break;
      if (!eq_info->enabled)
        continue;
      if (eq->status != FE_SUCCESS)
        continue;
      /*---- call idle routine for slow control equipment ----*/
      if ((eq_info->eq_type & EQ_SLOW) &&
          eq->status == FE_SUCCESS)
        {
        if (eq_info->event_limit>0 && run_state == STATE_RUNNING)
          {
          if (actual_time - eq->last_idle >= (DWORD) eq_info->event_limit)
            {
            eq->cd(CMD_IDLE, eq);
            eq->last_idle = actual_time;
            }
          }
        else
          eq->cd(CMD_IDLE, eq);
        }
      if (run_state == STATE_STOPPED && (eq_info->read_on & RO_STOPPED) == 0)
        continue;
      if (run_state == STATE_PAUSED  && (eq_info->read_on & RO_PAUSED)  == 0)
        continue;
      if (run_state == STATE_RUNNING && (eq_info->read_on & RO_RUNNING) == 0)
        continue;
      /*---- check periodic events ----*/
      if ((eq_info->eq_type & EQ_PERIODIC) || (eq_info->eq_type & EQ_SLOW))
        {
        if (eq_info->period == 0)
          continue;
        /* check if period over */
        if (actual_millitime - eq->last_called >= (DWORD) eq_info->period)
          {
          /* disable interrupts during readout */
          interrupt_enable(FALSE);
          /* readout and send event */
          status = send_event(index);
          if (status != CM_SUCCESS)
            {
            cm_msg(MERROR, "scheduler", "send_event error %d",status);
            goto net_error;
            }
          /* re-enable the interrupt after periodic */
          interrupt_enable(TRUE);
          }
        } /* end of periodic equipments */
      /*---- check polled events ----*/
      if (eq_info->eq_type & EQ_POLLED)
        {
        readout_start = actual_millitime;
        pevent = NULL;
        while ((source = poll_event(eq_info->source, eq->poll_count, FALSE)) > 0)
          {
#ifndef USE_PVIC
          pevent = dm_pointer_get();
#else
          pevent = pvic_pointer_get();
#endif
          if (pevent == NULL)
            {
            cm_msg(MERROR, "scheduler", "polled, dm_pointer_get not returning valid pointer");
            status = SS_NO_MEMORY;
            goto net_error;
            }
          /* compose MIDAS event header */
          pevent->event_id      = eq_info->event_id;
          pevent->trigger_mask  = eq_info->trigger_mask;
          pevent->data_size     = 0;
          pevent->time_stamp    = actual_time;
          pevent->serial_number = eq->serial_number;
          /* put source at beginning of event, will be overwritten by
             user readout code, just a special feature used by some
             multi-source applications */
          *(INT *) (pevent+1) = source;
          if (eq->info.num_subevents)
            {
            eq->subevent_number = 0;
            do
              {
              *(INT *) ((char *)(pevent+1)+pevent->data_size) = source;
              /* call user readout routine for subevent indicating offset */
              size = eq->readout((char *) (pevent+1), pevent->data_size);
              pevent->data_size += size;
              if (size > 0)
                {
                if (pevent->data_size+sizeof(EVENT_HEADER) > (DWORD) max_event_size)
                  {
                  cm_msg(MERROR, "scheduler", "Event size %ld larger than maximum size %d",
                         (long)(pevent->data_size+sizeof(EVENT_HEADER)), max_event_size);
                  }
                eq->subevent_number++;
                eq->serial_number++;
                }
              /* wait for next event */
              do
                {
                source = poll_event(eq_info->source, eq->poll_count, FALSE);
                if (source == FALSE)
                  {
                  actual_millitime = ss_millitime();
                  /* repeat no more than period */
                  if (actual_millitime - readout_start > (DWORD) eq_info->period)
                    break;
                  }
                } while (source == FALSE);
              } while (eq->subevent_number < eq->info.num_subevents && source);
            /* notify readout routine about end of super-event */
            pevent->data_size = eq->readout((char *) (pevent+1), -1);
            }
          else
            {
            /* call user readout routine indicating event source */
            pevent->data_size = eq->readout((char *) (pevent+1), 0);
            /* check event size */
            if (pevent->data_size+sizeof(EVENT_HEADER) > (DWORD) max_event_size)
              {
              cm_msg(MERROR, "scheduler", "Event size %ld larger than maximum size %d",
                     (long)(pevent->data_size+sizeof(EVENT_HEADER)), max_event_size);
              }
            /* increment serial number if event read out sucessfully */
            if (pevent->data_size)
              eq->serial_number++;
            }
          /* send event */
          if (pevent->data_size)
            {
            if (eq->buffer_handle)
              {
              /* send first event to ODB if logger writes in root format */
              if (pevent->serial_number == 1)
                if (logger_root())
                  update_odb(pevent, eq->hkey_variables, eq->format);
#ifdef USE_EVENT_CHANNEL
              dm_pointer_increment(eq->buffer_handle,
                                   pevent->data_size + sizeof(EVENT_HEADER));
#else
#ifdef USE_PVIC
              status = pvic_send_event(eq->buffer_handle, pevent,
                             pevent->data_size + sizeof(EVENT_HEADER), SYNC);
#else
              status = rpc_send_event(eq->buffer_handle, pevent,
                             pevent->data_size + sizeof(EVENT_HEADER), SYNC);
#endif
              if (status != SUCCESS)
                {
                cm_msg(MERROR, "scheduler", "rpc_send_event error %d", status);
                goto net_error;
                }
#endif
              eq->bytes_sent += pevent->data_size + sizeof(EVENT_HEADER);
              if (eq->info.num_subevents)
                eq->events_sent += eq->subevent_number;
              else
                eq->events_sent++;
              }
            }
          actual_millitime = ss_millitime();
          /* repeat no more than period */
          if (actual_millitime - readout_start > (DWORD) eq_info->period)
            break;
          /* quit if event limit is reached */
          if (eq_info->event_limit > 0 &&
              eq->stats.events_sent + eq->events_sent >= eq_info->event_limit)
            break;
          }
        /* send event to ODB */
        if (pevent && (eq_info->read_on & RO_ODB || eq_info->history))
          {
          if (actual_millitime - eq->last_called > ODB_UPDATE_TIME && pevent != NULL)
            {
            eq->last_called = actual_millitime;
            update_odb(pevent, eq->hkey_variables, eq->format);
            eq->odb_out++;
            }
          }
        }
      /*---- send interrupt events ----*/
      if (eq_info->eq_type & EQ_INTERRUPT)
        {
        /* not much to do as work being done independently in interrupt_routine() */
        /* update ODB */
        if (interrupt_odb_buffer_valid)
          {
          update_odb(interrupt_odb_buffer, interrupt_eq->hkey_variables,
                     interrupt_eq->format);
          interrupt_odb_buffer_valid = FALSE;
          }
        }
      /*---- check if event limit is reached ----*/
      if (eq_info->eq_type != EQ_SLOW &&
          eq_info->event_limit > 0 &&
          eq->stats.events_sent + eq->events_sent >= eq_info->event_limit &&
          run_state == STATE_RUNNING)
        {
        /* stop run */
        if (cm_transition(TR_STOP, 0, str, sizeof(str), SYNC, FALSE) != CM_SUCCESS)
          cm_msg(MERROR, "scheduler", "cannot stop run: %s", str);
        /* check if autorestart, main loop will take care of it */
        size = sizeof(BOOL);
        flag = FALSE;
        db_get_value(hDB, 0, "/Logger/Auto restart", &flag, &size, TID_BOOL, TRUE);
        if (flag)
          auto_restart = ss_time() + 20; /* restart in 20 sec. */
        /* update event display correctly */
        force_update = TRUE;
        }
      }
    /*---- call frontend_loop periodically -------------------------*/
    if (frontend_call_loop)
      {
      status = frontend_loop();
      if (status != CM_SUCCESS)
        status = RPC_SHUTDOWN;
      }
    /*---- check for deferred transitions --------------------------*/
    cm_check_deferred_transition();
    /*---- calculate rates and update status page periodically -----*/
    if (force_update ||
        (display_period && actual_millitime - last_time_display > (DWORD) display_period) ||
        (!display_period && actual_millitime - last_time_display > 3000))
      {
      force_update = FALSE;
      /* calculate rates */
      if (actual_millitime != last_time_display)
        {
        max_bytes_per_sec = 0;
        for (i=0 ; equipment[i].name[0] ; i++)
          {
          eq = &equipment[i];
          eq->stats.events_sent += eq->events_sent;
          eq->stats.events_per_sec =
            eq->events_sent/((actual_millitime-last_time_display)/1000.0);
          eq->stats.kbytes_per_sec =
            eq->bytes_sent/1024.0/((actual_millitime-last_time_display)/1000.0);
          if ((INT) eq->bytes_sent > max_bytes_per_sec)
            max_bytes_per_sec = eq->bytes_sent;
          eq->bytes_sent = 0;
          eq->events_sent = 0;
          }
        max_bytes_per_sec = (DWORD)
          ((double)max_bytes_per_sec/((actual_millitime-last_time_display)/1000.0));
        /* tcp buffer size evaluation */
        if (optimize)
          {
          opt_max = MAX(opt_max, (INT)max_bytes_per_sec);
          ss_printf(0, opt_index, "%6d : %5.1lf %5.1lf", opt_tcp_size, opt_max/1024.0,
                    max_bytes_per_sec/1024.0);
          if (++opt_cnt == 10)
            {
            opt_cnt = 0;
            opt_max = 0;
            opt_index++;
            opt_tcp_size = 1<<(opt_index+7);
            rpc_set_opt_tcp_size(opt_tcp_size);
            if (1<<(opt_index+7) > 0x8000)
              {
              opt_index = 0;
              opt_tcp_size = 1<<7;
              rpc_set_opt_tcp_size(opt_tcp_size);
              }
            }
          }
      /* propagate changes in equipment to ODB */
      rpc_set_option(-1, RPC_OTRANSPORT, RPC_FTCP);
      db_send_changed_records();
      rpc_set_option(-1, RPC_OTRANSPORT, RPC_TCP);
        }
      if (display_period)
        {
        display(FALSE);
        /* check keyboard */
        ch = 0;
        status = 0;
        while (ss_kbhit())
          {
          ch = ss_getchar(0);
          if (ch == -1)
            ch = getchar();
          if (ch == '!')
            status = RPC_SHUTDOWN;
          }
        if (ch > 0)
          display(TRUE);
        if (status == RPC_SHUTDOWN)
          break;
        }
      last_time_display = actual_millitime;
      }
    /*---- check to flush cache ------------------------------------*/
    if (actual_millitime - last_time_flush > 1000)
      {
      last_time_flush = actual_millitime;
      /* if cache on server is not filled in one second at current
         data rate, flush it now to make events available to consumers */
      if (max_bytes_per_sec < SERVER_CACHE_SIZE)
        {
        interrupt_enable(FALSE);
#ifdef USE_EVENT_CHANNEL
        if ((status = dm_area_flush()) != CM_SUCCESS)
          cm_msg(MERROR, "scheduler", "dm_area_flush: %i", status);
#endif
        for (i=0 ; equipment[i].name[0] ; i++)
          {
          if (equipment[i].buffer_handle)
            {
            /* check if buffer already flushed */
            buffer_done = FALSE;
            for (j=0 ; j<i ; j++)
              if (equipment[i].buffer_handle == equipment[j].buffer_handle)
                {
                buffer_done = TRUE;
                break;
                }
            if (!buffer_done)
              {
              rpc_set_option(-1, RPC_OTRANSPORT, RPC_FTCP);
          rpc_flush_event();
              err = bm_flush_cache(equipment[i].buffer_handle, ASYNC);
          if (err != BM_SUCCESS)
        {
          cm_msg(MERROR,"scheduler","bm_flush_cache(ASYNC) error %d",err);
          return err;
        }
              rpc_set_option(-1, RPC_OTRANSPORT, RPC_TCP);
              }
            }
          }
        interrupt_enable(TRUE);
        }
      }
      /*---- check for auto restart --------------------------------*/
      if (auto_restart > 0 && ss_time() > auto_restart)
        {
        /* check if really stopped */
        size = sizeof(state);
        status = db_get_value(hDB, 0, "Runinfo/State", &state, &size, TID_INT, TRUE);
        if (status != DB_SUCCESS)
          cm_msg(MERROR, "scheduler", "cannot get Runinfo/State in database");
        if (state == STATE_STOPPED)
          {
          auto_restart = 0;
          size = sizeof(run_number);
          db_get_value(hDB, 0, "/Runinfo/Run number", &run_number, &size, TID_INT, TRUE);
          cm_msg(MTALK, "main", "starting new run");
          status = cm_transition(TR_START, run_number+1, NULL, 0, SYNC, FALSE);
          if (status != CM_SUCCESS)
            cm_msg(MERROR, "main", "cannot restart run");
          }
        }
    /*---- check network messages ----------------------------------*/
    if (run_state == STATE_RUNNING && interrupt_eq == NULL)
      {
//#ifndef PART_OF_MUCAP
      /* only call yield once every 500ms when running */
      if (actual_millitime - last_time_network > 500)
//#else
//      /* only call yield once every 1 ms when running */
//      if (actual_millitime - last_time_network > 0)
//        if(1)
//#endif
        {
        status = cm_yield(0);
        last_time_network = actual_millitime;
        }
      else
        status = RPC_SUCCESS;
      }
    else
      /* when run is stopped or interrupts used,
         call yield with 100ms timeout */
      status = cm_yield(100);
    /* exit for VxWorks */
    if (fe_stop)
      status = RPC_SHUTDOWN;
    } while (status != RPC_SHUTDOWN && status != SS_ABORT);
net_error:
  return status;
}
void send_all_periodic_events (INT transition)
Definition at line 1219 of file mfe_mucap.c.
References EQUIPMENT_INFO::enabled, FE_SUCCESS, i, eqpmnt::info, eqpmnt::name, EQUIPMENT_INFO::read_on, RO_BOR, RO_EOR, RO_PAUSE, RO_RESUME, send_event(), eqpmnt::status, TR_PAUSE, TR_RESUME, TR_START, and TR_STOP.
Referenced by tr_pause(), tr_prepause(), tr_prestop(), tr_resume(), tr_start(), tr_start2(), and tr_stop().
{
  EQUIPMENT_INFO *eq_info;
  INT            i;
  for (i=0 ; equipment[i].name[0] ; i++)
  {
    eq_info = &equipment[i].info;
    if (!eq_info->enabled || equipment[i].status != FE_SUCCESS)
      continue;
    if (transition == TR_START  && (eq_info->read_on & RO_BOR)    == 0)
      continue;
    if (transition == TR_STOP   && (eq_info->read_on & RO_EOR)    == 0)
      continue;
    if (transition == TR_PAUSE  && (eq_info->read_on & RO_PAUSE)  == 0)
      continue;
    if (transition == TR_RESUME && (eq_info->read_on & RO_RESUME) == 0)
      continue;
    send_event(i);
  }
}
int send_event (INT index)
Definition at line 1003 of file mfe_mucap.c.
References bm_flush_cache(), bm_send_event(), BM_SUCCESS, eqpmnt::bytes_sent, cm_msg, CM_SUCCESS, EVENT_HEADER::data_size, dm_area_flush(), dm_pointer_get(), dm_pointer_increment(), EQ_FRAGMENTED, EQ_SLOW, EQUIPMENT_INFO::eq_type, EQUIPMENT_INFO::event_id, EVENT_HEADER::event_id, EVENTID_FRAG, EVENTID_FRAG1, EQUIPMENT_STATS::events_sent, eqpmnt::events_sent, format(), EQUIPMENT_INFO::history, i, eqpmnt::info, eqpmnt::last_called, max_event_size, max_event_size_frag, MERROR, eqpmnt::name, eqpmnt::odb_out, EQUIPMENT_INFO::read_on, eqpmnt::readout, RO_ODB, rpc_flush_event(), eqpmnt::serial_number, EVENT_HEADER::serial_number, size, ss_millitime(), SS_NO_MEMORY, ss_time(), eqpmnt::stats, status, SYNC, EVENT_HEADER::time_stamp, EQUIPMENT_INFO::trigger_mask, EVENT_HEADER::trigger_mask, and update_odb().
Referenced by manual_trigger(), scheduler(), and send_all_periodic_events().
{
EQUIPMENT_INFO *eq_info;
EVENT_HEADER   *pevent, *pfragment;
char           *pdata;
unsigned char  *pd;
INT            i, status;
DWORD          sent, size;
static void    *frag_buffer = NULL;
  eq_info = &equipment[index].info;
  /* check for fragmented event */
  if (eq_info->eq_type & EQ_FRAGMENTED)
    {
    if (frag_buffer == NULL)
      frag_buffer = malloc(max_event_size_frag);
    if (frag_buffer == NULL)
      {
      cm_msg(MERROR, "send_event", "Not enough memory to allocate buffer for fragmented events");
      return SS_NO_MEMORY;
      }
    pevent = frag_buffer;
    }
  else
    {
    /* return value should be valid pointer. if NULL BIG error ==> abort  */
    pevent = dm_pointer_get();
    if (pevent == NULL)
      {
      cm_msg(MERROR, "send_event", "dm_pointer_get not returning valid pointer");
      return SS_NO_MEMORY;
      }
    }
  /* compose MIDAS event header */
  pevent->event_id      = eq_info->event_id;
  pevent->trigger_mask  = eq_info->trigger_mask;
  pevent->data_size     = 0;
  pevent->time_stamp    = ss_time();
  pevent->serial_number = equipment[index].serial_number++;
  equipment[index].last_called = ss_millitime();
  /* call user readout routine */
  *((EQUIPMENT **)(pevent+1)) = &equipment[index];
  pevent->data_size = equipment[index].readout((char *) (pevent+1), 0);
  /* send event */
  if (pevent->data_size)
    {
    if (eq_info->eq_type & EQ_FRAGMENTED)
      {
      /* fragment event */
      if (pevent->data_size+sizeof(EVENT_HEADER) > (DWORD) max_event_size_frag)
        {
        cm_msg(MERROR, "send_event", "Event size %ld larger than maximum size %d for frag. ev.",
          (long)(pevent->data_size+sizeof(EVENT_HEADER)), max_event_size_frag);
        return SS_NO_MEMORY;
        }
      /* compose fragments */
      pfragment = dm_pointer_get();
      if (pfragment == NULL)
        {
        cm_msg(MERROR, "send_event", "dm_pointer_get not returning valid pointer");
        return SS_NO_MEMORY;
        }
      /* compose MIDAS event header */
      memcpy(pfragment, pevent, sizeof(EVENT_HEADER));
      pfragment->event_id |= EVENTID_FRAG1;
      /* store total event size */
      pd = (char *)(pfragment+1);
      size = pevent->data_size;
      for (i=0 ; i<4 ; i++)
        {
        pd[i] = (unsigned char)(size & 0xFF); /* little endian, please! */
        size >>= 8;
        }
      pfragment->data_size = sizeof(DWORD);
      pdata=(char *)(pevent+1);
      for (i=0,sent=0 ; sent<pevent->data_size ; i++)
        {
        if (i>0)
          {
          pfragment = dm_pointer_get();
          /* compose MIDAS event header */
          memcpy(pfragment, pevent, sizeof(EVENT_HEADER));
          pfragment->event_id |= EVENTID_FRAG;
          /* copy portion of event */
          size = pevent->data_size - sent;
          if (size > max_event_size-sizeof(EVENT_HEADER))
            size = max_event_size-sizeof(EVENT_HEADER);
          memcpy(pfragment+1, pdata, size);
          pfragment->data_size = size;
          sent += size;
          pdata += size;
          }
        /* send event to buffer */
        if (equipment[index].buffer_handle)
          {
#ifdef USE_EVENT_CHANNEL
          dm_pointer_increment(equipment[index].buffer_handle,
            pfragment->data_size + sizeof(EVENT_HEADER));
#else
          rpc_flush_event();
          status = bm_send_event(equipment[index].buffer_handle, pfragment,
                                 pfragment->data_size + sizeof(EVENT_HEADER), SYNC);
          if (status != BM_SUCCESS)
            {
            cm_msg(MERROR, "send_event", "bm_send_event(SYNC) error %d", status);
            return status;
            }
#endif
          }
        }
      if (equipment[index].buffer_handle) {
#ifndef USE_EVENT_CHANNEL
        status = bm_flush_cache(equipment[index].buffer_handle, SYNC);
        if (status != BM_SUCCESS)
          {
          cm_msg(MERROR,"send_event","bm_flush_cache(SYNC) error %d", status);
          return status;
          }
#endif
        }
      }
    else
      {
      /* send unfragmented event */
      if (pevent->data_size+sizeof(EVENT_HEADER) > (DWORD) max_event_size)
        {
        cm_msg(MERROR, "send_event", "Event size %ld larger than maximum size %d",
          (long)(pevent->data_size+sizeof(EVENT_HEADER)), max_event_size);
        return SS_NO_MEMORY;
        }
      /* send event to buffer */
      if (equipment[index].buffer_handle)
        {
#ifdef USE_EVENT_CHANNEL
        dm_pointer_increment(equipment[index].buffer_handle,
          pevent->data_size + sizeof(EVENT_HEADER));
#else
        rpc_flush_event();
        status = bm_send_event(equipment[index].buffer_handle, pevent,
          pevent->data_size + sizeof(EVENT_HEADER), SYNC);
        if (status != BM_SUCCESS)
          {
          cm_msg(MERROR,"send_event","bm_send_event(SYNC) error %d",status);
          return status;
          }
        status = bm_flush_cache(equipment[index].buffer_handle, SYNC);
        if (status != BM_SUCCESS)
          {
          cm_msg(MERROR,"send_event","bm_flush_cache(SYNC) error %d",status);
          return status;
          }
#endif
        }
      /* send event to ODB if RO_ODB flag is set or history is on. Do not
      send SLOW events since the class driver does that */
      if ((eq_info->read_on & RO_ODB) ||
        (eq_info->history > 0 && (eq_info->eq_type & ~EQ_SLOW)))
        {
        update_odb(pevent, equipment[index].hkey_variables, equipment[index].format);
        equipment[index].odb_out++;
        }
      }
    equipment[index].bytes_sent += pevent->data_size + sizeof(EVENT_HEADER);
    equipment[index].events_sent++;
    equipment[index].stats.events_sent += equipment[index].events_sent;
    equipment[index].events_sent = 0;
   }
  else
    equipment[index].serial_number--;
  /* emtpy event buffer */
#ifdef USE_EVENT_CHANNEL
    if ((status = dm_area_flush()) != CM_SUCCESS)
      cm_msg(MERROR,"send_event","dm_area_flush: %i", status);
#endif
  for (i=0 ; equipment[i].name[0] ; i++)
    if (equipment[i].buffer_handle)
      {
      status = bm_flush_cache(equipment[i].buffer_handle, SYNC);
      if (status != BM_SUCCESS)
        {
        cm_msg(MERROR,"send_event","bm_flush_cache(SYNC) error %d", status);
        return status;
        }
      }
  return CM_SUCCESS;
}
INT tr_prepause (INT rn, char * error)
Definition at line 484 of file mfe_mucap.c.
References CM_SUCCESS, display_period, FALSE, interrupt_enable(), pause_run, run_number, run_state, send_all_periodic_events(), ss_printf(), STATE_PAUSED, status, TR_PAUSE, and TRUE.
Referenced by main().
{
INT status;
  /* disable interrupts */
  interrupt_enable(FALSE);
  status = pause_run(rn, error);
  if (status == CM_SUCCESS)
    {
    run_state = STATE_PAUSED;
    run_number = rn;
    send_all_periodic_events(TR_PAUSE);
    if (display_period)
      ss_printf(14, 2, "Paused  ");
    }
  else
    interrupt_enable(TRUE);
  return status;
}
INT tr_prestart (INT rn, char * error)
Definition at line 396 of file mfe_mucap.c.
References pre_begin_of_run(), and status.
{
  INT status;
  status = pre_begin_of_run(rn, error);
  return status;
}
INT tr_prestop (INT rn, char * error)
Definition at line 442 of file mfe_mucap.c.
References bm_flush_cache(), BM_SUCCESS, cm_msg, CM_SUCCESS, display_period, end_of_run(), FALSE, i, interrupt_enable(), MERROR, eqpmnt::name, rpc_flush_event(), run_number, run_state, send_all_periodic_events(), ss_printf(), STATE_STOPPED, status, SYNC, TR_STOP, and TRUE.
Referenced by main().
{
INT status, i;
  /* disable interrupts */
  interrupt_enable(FALSE);
  status = end_of_run(rn, error);
  if (status == CM_SUCCESS)
    {
    /* don't send events if already stopped */
    if (run_state != STATE_STOPPED)
      send_all_periodic_events(TR_STOP);
    run_state = STATE_STOPPED;
    run_number = rn;
    if (display_period)
      ss_printf(14, 2, "Stopped ");
    }
  else
    interrupt_enable(TRUE);
  /* flush remaining buffered events */
  rpc_flush_event();
  for (i=0 ; equipment[i].name[0] ; i++)
    if (equipment[i].buffer_handle)
      {
    INT err = bm_flush_cache(equipment[i].buffer_handle, SYNC);
    if (err != BM_SUCCESS)
      {
        cm_msg(MERROR,"tr_prestop","bm_flush_cache(SYNC) error %d",err);
        return err;
      }
      }
  return status;
}
INT tr_resume (INT rn, char * error)
Definition at line 511 of file mfe_mucap.c.
References CM_SUCCESS, display_period, interrupt_enable(), resume_run, run_number, run_state, send_all_periodic_events(), ss_printf(), STATE_RUNNING, status, TR_RESUME, and TRUE.
Referenced by main().
{
INT status;
  status = resume_run(rn, error);
  if (status == CM_SUCCESS)
    {
    run_state = STATE_RUNNING;
    run_number = rn;
    send_all_periodic_events(TR_RESUME);
    if (display_period)
      ss_printf(14, 2, "Running ");
    /* enable interrupts */
    interrupt_enable(TRUE);
    }
  return status;
}
INT tr_start (INT rn, char * error)
Definition at line 405 of file mfe_mucap.c.
References begin_of_run(), CM_SUCCESS, display_period, EQUIPMENT_STATS::events_sent, i, interrupt_enable(), eqpmnt::name, eqpmnt::odb_in, eqpmnt::odb_out, run_number, run_state, send_all_periodic_events(), eqpmnt::serial_number, ss_printf(), STATE_RUNNING, eqpmnt::stats, status, eqpmnt::subevent_number, TR_START, and TRUE.
Referenced by main().
{
INT i, status;
  /* reset serial numbers */
  for (i=0 ; equipment[i].name[0] ; i++)
    {
    equipment[i].serial_number = 1;
    equipment[i].subevent_number = 0;
    equipment[i].stats.events_sent = 0;
    equipment[i].odb_in = equipment[i].odb_out = 0;
    }
  status = begin_of_run(rn, error);
  if (status == CM_SUCCESS)
    {
    run_state = STATE_RUNNING;
    run_number = rn;
    send_all_periodic_events(TR_START);
    if (display_period)
      {
      ss_printf(14, 2, "Running ");
      ss_printf(36, 2, "%d", rn);
      }
    /* enable interrupts */
    interrupt_enable(TRUE);
    }
  return status;
}
void update_odb (EVENT_HEADER * pevent, HNDLE hKey, INT format)
Definition at line 842 of file mfe_mucap.c.
References A1_BKTYPE, bk_is32(), bk_iterate(), bk_iterate32(), cm_msg, D8_BKTYPE, EVENT_HEADER::data_size, db_enum_key(), db_find_key(), db_get_key(), DB_NO_MORE_SUBKEYS, db_set_data(), db_set_record(), db_set_value(), DB_SUCCESS, EVENT_HEADER::event_id, FORMAT_FIXED, FORMAT_MIDAS, FORMAT_YBOS, hDB, i, I1_BKTYPE, I2_BKTYPE, id_map, KEY::item_size, key, MERROR, MIN, YBOS_BANK_HEADER::name, BANK::name, BANK32::name, name, KEY::num_values, odb_type, RPC_OTRANSPORT, rpc_set_option(), RPC_TCP, rpc_tid_size(), size, ss_get_struct_align(), status, TID_LINK, TID_STRING, TID_STRUCT, tsize, YBOS_BANK_HEADER::type, KEY::type, BANK::type, BANK32::type, VALIGN, and ybk_iterate().
Referenced by scheduler(), and send_event().
{
INT               size, i, ni4, tsize, status, n_data;
void              *pdata;
char              name[5];
BANK_HEADER       *pbh;
BANK              *pbk;
BANK32            *pbk32;
void              *pydata;
DWORD             odb_type;
DWORD             *pyevt, bkname;
WORD              bktype;
HNDLE             hKeyRoot, hKeyl;
KEY               key;
  /* outcommented sind db_find_key does not work in FTCP mode, SR 25.4.03
  rpc_set_option(-1, RPC_OTRANSPORT, RPC_FTCP); */
  if (format == FORMAT_FIXED)
    {
    if (db_set_record(hDB, hKey, (char *) (pevent+1),
                      pevent->data_size, 0) != DB_SUCCESS)
      cm_msg(MERROR, "update_odb", "event #%d size mismatch", pevent->event_id);
    }
  else if (format == FORMAT_MIDAS)
    {
    pbh = (BANK_HEADER *) (pevent+1);
    pbk = NULL;
    pbk32 = NULL;
    do
      {
      /* scan all banks */
      if (bk_is32(pbh))
        {
        size = bk_iterate32(pbh, &pbk32, &pdata);
        if (pbk32 == NULL)
          break;
        bkname = *((DWORD *) pbk32->name);
        bktype = (WORD) pbk32->type;
        }
      else
        {
        size = bk_iterate(pbh, &pbk, &pdata);
        if (pbk == NULL)
          break;
        bkname = *((DWORD *) pbk->name);
        bktype = (WORD) pbk->type;
        }
      n_data = size;
      if (rpc_tid_size(bktype & 0xFF))
        n_data /= rpc_tid_size(bktype & 0xFF);
      /* get bank key */
      *((DWORD *) name) = bkname;
      name[4] = 0;
      if (bktype == TID_STRUCT)
        {
        status = db_find_key(hDB, hKey, name, &hKeyRoot);
        if (status != DB_SUCCESS)
          {
          cm_msg(MERROR, "update_odb", "please define bank %s in BANK_LIST in frontend.c", name);
          continue;
          }
        /* write structured bank */
        for (i=0 ;; i++)
          {
          status = db_enum_key(hDB, hKeyRoot, i, &hKeyl);
          if (status == DB_NO_MORE_SUBKEYS)
            break;
          db_get_key(hDB, hKeyl, &key);
          /* adjust for alignment */
          if (key.type != TID_STRING && key.type != TID_LINK)
            pdata = (void *) VALIGN(pdata, MIN(ss_get_struct_align(), key.item_size));
          status = db_set_data(hDB, hKeyl, pdata, key.item_size*key.num_values,
                               key.num_values, key.type);
          if (status != DB_SUCCESS)
            {
            cm_msg(MERROR, "update_odb", "cannot write %s to ODB", name);
            continue;
            }
          /* shift data pointer to next item */
          (char *) pdata += key.item_size*key.num_values;
          }
        }
      else
        {
        /* write variable length bank  */
        if (n_data > 0)
          db_set_value(hDB, hKey, name, pdata, size, n_data, bktype & 0xFF);
        }
      } while (1);
    }
  else if (format == FORMAT_YBOS)
    {
#ifdef YBOS_SUPPORT
    YBOS_BANK_HEADER *pybkh;
    /* skip the lrl (4 bytes per event) */
    pyevt = (DWORD *) (pevent+1);
    pybkh = NULL;
    do
        {
        /* scan all banks */
        ni4 = ybk_iterate(pyevt, &pybkh, &pydata);
        if (pybkh == NULL || ni4 == 0)
          break;
        /* find the corresponding odb type */
        tsize = odb_type = 0;
      for (i=0;id_map[0].ybos_type > 0; i++)
          {
        if (pybkh->type == id_map[i].ybos_type)
          {
              odb_type = id_map[i].odb_type;
              tsize = id_map[i].tsize;
              break;
          }
          }
        /* extract bank name (key name) */
        *((DWORD *)name) = pybkh->name;
        name[4] = 0;
      /* reject EVID bank */
      if (strncmp(name, "EVID", 4) == 0)
        continue;
      /* correct YBS number of entries */
      if (pybkh->type == D8_BKTYPE)
        ni4 /= 2;
      if (pybkh->type == I2_BKTYPE)
        ni4 *= 2;
      if (pybkh->type == I1_BKTYPE || pybkh->type == A1_BKTYPE)
        ni4 *= 4;
        /* write bank to ODB, ni4 always in I*4 */
        size = ni4 * tsize;
        if ((status = db_set_value(hDB, hKey, name, pydata, size, ni4, odb_type & 0xFF)) != DB_SUCCESS)
          {
          printf("status:%i odb_type:%li name:%s ni4:%i size:%i tsize:%i\n",
                    status, odb_type, name, ni4, size, tsize);
          for (i=0;i<6;i++)
              printf("data: %f\n",*((float *)(pydata))++);
          }
      } while (1);
#endif /* YBOS_SUPPORT */
    }
  rpc_set_option(-1, RPC_OTRANSPORT, RPC_TCP);
}
Variable Documentation
DWORD actual_millitime
Definition at line 325 of file mfe_mucap.c.
Referenced by interrupt_routine(), main(), scan_fragment(), and scheduler().
DWORD actual_time
Definition at line 324 of file mfe_mucap.c.
Referenced by cm_watchdog(), interrupt_routine(), log_write(), loop_online(), multi_read(), process_event(), scheduler(), and update_stats().
DWORD auto_restart = 0
Definition at line 334 of file mfe_mucap.c.
Referenced by log_write(), main(), and scheduler().
BOOL debug
Definition at line 333 of file mfe_mucap.c.
Referenced by cnaf16(), cnaf24(), cnaf_callback(), handFlush(), load_fragment(), main(), mchart_get_array(), receive_message(), scan_fragment(), TemplateFactory< BaseModule, modules::options >::SetDebug(), source_booking(), source_scan(), source_unbooking(), and usb_scs_250_debug_data().
INT display_period
Definition at line 43 of file crate.cpp.
EQUIPMENT equipment[]
Definition at line 72 of file crate.cpp.
INT event_buffer_size
Definition at line 53 of file crate.cpp.
char exp_name[NAME_LENGTH]
Definition at line 328 of file mfe_mucap.c.
Referenced by interprete(), main(), process_file(), redirect(), search_callback(), show_alarm_page(), show_cnaf_page(), show_custom_page(), show_elog_new(), show_elog_page(), show_elog_query(), show_elog_submit_query(), show_form_query(), show_header(), show_hist_page(), show_messages_page(), show_odb_page(), show_programs_page(), show_rawfile(), show_sc_page(), show_status_page(), and submit_elog().
INT fe_stop = 0
Definition at line 332 of file mfe_mucap.c.
Referenced by scheduler().
BOOL frontend_call_loop
Definition at line 39 of file crate.cpp.
char* frontend_file_name
Definition at line 36 of file crate.cpp.
char* frontend_name
Definition at line 33 of file crate.cpp.
HNDLE hDB
Definition at line 336 of file mfe_mucap.c.
char host_name[HOST_NAME_LENGTH]
Definition at line 327 of file mfe_mucap.c.
Referenced by display(), ftp_data(), ftp_open(), interprete(), main(), process_file(), sendmail(), server_loop(), and submit_elog().
BOOL interrupt_enabled
Definition at line 1246 of file mfe_mucap.c.
Referenced by interrupt_enable().
EQUIPMENT* interrupt_eq = NULL
Definition at line 356 of file mfe_mucap.c.
EVENT_HEADER* interrupt_odb_buffer
Definition at line 357 of file mfe_mucap.c.
BOOL interrupt_odb_buffer_valid
Definition at line 358 of file mfe_mucap.c.
Referenced by interrupt_routine(), and scheduler().
INT max_bytes_per_sec
Definition at line 330 of file mfe_mucap.c.
Referenced by scheduler().
INT max_event_size
Definition at line 47 of file crate.cpp.
INT max_event_size_frag
Definition at line 50 of file crate.cpp.
INT optimize = 0
Definition at line 331 of file mfe_mucap.c.
Referenced by scheduler().
INT run_number
Definition at line 323 of file mfe_mucap.c.
Referenced by close_buffers(), display(), el_submit(), generate_hist_graph(), GetRunNumber(), loop_runs_offline(), main(), MDQ_DigitizerOverflow_init(), MDQ_FADCBufferOverflow_init(), MDQ_FADCPacketLoss_init(), register_equipment(), run_number_changed(), scheduler(), show_elog_new(), show_form_query(), tr_pause(), tr_prepause(), tr_prestop(), tr_resume(), tr_start(), tr_start2(), tr_stop(), and write_event_hbook().
INT run_state
PROGRAM: crate.cpp DESCRIPTION: Control and readout of CAEN V1724 digitizers. author: V.Tishchenko date: 12-Aug-2012
Modifications:
Definition at line 322 of file mfe_mucap.c.