AlcapDAQ:Rootana: crate9/camac_wrapper.h File Reference
crate9/camac_wrapper.h File Reference
Functions
void cam_init_once ()
Function Documentation
void cam_init_once ()
Definition at line 7 of file camac_wrapper.cpp.
References cam_inhibit_clear(), cam_init(), and camac_inited.
Referenced by lrs2249_bor1().
{
  if(!camac_inited) {
    cam_init();
    cam_inhibit_clear(0);
  }
}