AlcapDAQ:Rootana: midas/drivers/device/das1600.c File Reference
midas/drivers/device/das1600.c File Reference
#include <stdio.h>
#include <conio.h>
#include <math.h>
#include "midas.h"
Data Structures
struct DAS1600_SETTINGS
Defines
#define DAS1600_SETTINGS_STR "\IO Base = WORD : 0x240\n\Gain = WORD[16] :\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\"
#define AD0 (unsigned short) (settings->io_base+0x00)
#define AD1 (unsigned short) (settings->io_base+0x01)
#define MUX (unsigned short) (settings->io_base+0x02)
#define DIO (unsigned short) (settings->io_base+0x03)
#define DA0LB (unsigned short) (settings->io_base+0x04)
#define DA0HB (unsigned short) (settings->io_base+0x05)
#define DA1LB (unsigned short) (settings->io_base+0x06)
#define DA1HB (unsigned short) (settings->io_base+0x07)
#define STATUS (unsigned short) (settings->io_base+0x08)
#define CTRL (unsigned short) (settings->io_base+0x09)
#define GAIN (unsigned short) (settings->io_base+0x0b)
Functions
INT das1600_init (HNDLE hKey, void **psettings, INT channels, DWORD type)
INT das1600_get_analog (DAS1600_SETTINGS *settings, INT channel, float *pvalue)
INT das1600_set_analog (DAS1600_SETTINGS *settings, INT channel, float voltage)
INT das1600_ai (INT cmd,...)
INT das1600_ao (INT cmd,...)
Define Documentation
#define AD0 (unsigned short) (settings->io_base+0x00)
Definition at line 103 of file das1600.c.
Referenced by das1600_get_analog().
#define AD1 (unsigned short) (settings->io_base+0x01)
Definition at line 104 of file das1600.c.
#define CTRL (unsigned short) (settings->io_base+0x09)
Definition at line 112 of file das1600.c.
Referenced by das1600_get_analog().
#define DA0HB (unsigned short) (settings->io_base+0x05)
Definition at line 108 of file das1600.c.
#define DA0LB (unsigned short) (settings->io_base+0x04)
Definition at line 107 of file das1600.c.
Referenced by das1600_set_analog().
#define DA1HB (unsigned short) (settings->io_base+0x07)
Definition at line 110 of file das1600.c.
#define DA1LB (unsigned short) (settings->io_base+0x06)
Definition at line 109 of file das1600.c.
Referenced by das1600_set_analog().
#define DAS1600_SETTINGS_STR "\IO Base = WORD : 0x240\n\Gain = WORD[16] :\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\1\n\"
Definition at line 46 of file das1600.c.
Referenced by das1600_init().
#define DIO (unsigned short) (settings->io_base+0x03)
Definition at line 106 of file das1600.c.
#define GAIN (unsigned short) (settings->io_base+0x0b)
Definition at line 113 of file das1600.c.
Referenced by adc_read(), and das1600_get_analog().
#define MUX (unsigned short) (settings->io_base+0x02)
Definition at line 105 of file das1600.c.
Referenced by das1600_get_analog().
#define STATUS (unsigned short) (settings->io_base+0x08)
Definition at line 111 of file das1600.c.
Function Documentation
INT das1600_ai (INT cmd, ...)
Definition at line 187 of file das1600.c.
References channel, CMD_GET, CMD_INIT, das1600_get_analog(), das1600_init(), DF_INPUT, FE_SUCCESS, hKey, and status.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   float *pvalue;
   void *info;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      status = das1600_init(hKey, info, channel, DF_INPUT);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = das1600_get_analog(info, channel, pvalue);
      break;
   default:
      break;
   }
   va_end(argptr);
   return status;
}
INT das1600_ao (INT cmd, ...)
Definition at line 224 of file das1600.c.
References channel, CMD_INIT, CMD_SET, das1600_init(), das1600_set_analog(), DF_OUTPUT, FE_SUCCESS, hKey, status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   float value;
   void *info;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      status = das1600_init(hKey, info, channel, DF_OUTPUT);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = das1600_set_analog(info, channel, value);
      break;
   default:
      break;
   }
   va_end(argptr);
   return status;
}
INT das1600_get_analog (DAS1600_SETTINGS * settings, INT channel, float * pvalue)
Definition at line 117 of file das1600.c.
References AD0, CTRL, data, FE_SUCCESS, DAS1600_SETTINGS::gain, GAIN, MUX, and STATUS.
Referenced by das1600_ai().
{
   unsigned short int data;
   double volts;
//###
//*pvalue = (float) (channel/10.0);
//return FE_SUCCESS;
   /* set MUX channel */
   _outp(MUX, channel | (channel << 4));
   /* diable interrupts and DMA */
   _outp(CTRL, 0);
   /* set gain */
   _outp(GAIN, settings->gain[channel] == 1 ? 0 :
         settings->gain[channel] == 10 ? 1 :
         settings->gain[channel] == 100 ? 2 : settings->gain[channel] == 500 ? 3 : 0);
   /* start conversion */
   _outp(AD0, 0);
   /* wait for conversion */
   do {
      data = _inp(STATUS);
   } while (data & 0x80);
   data = _inpw(AD0);
   /* convert to volts assuming bipolar operation */
   volts = ((data >> 4) - 2048.0) / 4096.0;
   volts = volts * (10 - (-10)) / settings->gain[channel];
   /* return volts */
   *pvalue = (float) volts;
   return FE_SUCCESS;
}
INT das1600_init (HNDLE hKey, void ** psettings, INT channels, DWORD type)
Definition at line 69 of file das1600.c.
References cm_get_experiment_database(), cm_msg, DAS1600_SETTINGS_STR, db_create_record(), db_get_record(), DB_SUCCESS, FE_ERR_HW, FE_ERR_ODB, FE_SUCCESS, hDB, DAS1600_SETTINGS::io_base, MERROR, size, ss_directio_give_port(), SS_SUCCESS, and status.
Referenced by das1600_ai(), and das1600_ao().
{
   int status, size;
   HNDLE hDB;
   DAS1600_SETTINGS *settings;
   /* allocate info structure */
   settings = calloc(1, sizeof(DAS1600_SETTINGS));
   *psettings = settings;
   cm_get_experiment_database(&hDB, NULL);
   /* create settings record */
   status = db_create_record(hDB, hKey, "", DAS1600_SETTINGS_STR);
   if (status != DB_SUCCESS)
      return FE_ERR_ODB;
   size = sizeof(DAS1600_SETTINGS);
   db_get_record(hDB, hKey, settings, &size, 0);
#ifdef OS_WINNT
   /* open IO address space */
   status = ss_directio_give_port(settings->io_base, settings->io_base + 0x0F);
   if (status != SS_SUCCESS) {
      cm_msg(MERROR, "das1600_init", "DirectIO device driver not installed");
      return FE_ERR_HW;
   }
#endif
   return FE_SUCCESS;
}
INT das1600_set_analog (DAS1600_SETTINGS * settings, INT channel, float voltage)
Definition at line 161 of file das1600.c.
References DA0LB, DA1LB, data, and FE_SUCCESS.
Referenced by das1600_ao().
{
   signed short int data;
   /* assume +-10 V bipolar range */
//  data = (unsigned short int) (voltage / 10.0 * 2048 + 2048.5);
   /* assume +10 V unipolar range */
   data = (unsigned short int) (voltage / 10.0 * 4096);
   /* check if in range */
   if (data > 4095)
      data = 4095;
   if (data < 0)
      data = 0;
   if (channel == 0)
      _outpw(DA0LB, (unsigned short) (data << 4));
   else
      _outpw(DA1LB, (unsigned short) (data << 4));
   return FE_SUCCESS;
}