AlcapDAQ:Rootana: evb/ebuser.cpp File Reference
evb/ebuser.cpp File Reference
#include <stdio.h>
#include "midas.h"
#include "mevb.h"
#include "ybos.h"
#include "mucap_compress.h"
Defines
#define NUMCRATES 5
Functions
INT ebuilder_init ()
INT ebuilder_exit ()
INT eb_begin_of_run (INT, char *, char *)
INT eb_end_of_run (INT, char *)
INT ebuilder_loop ()
INT ebuser (INT, BOOL mismatch, EBUILDER_CHANNEL *, EVENT_HEADER *, void *, INT *)
INT read_scaler_event (char *pevent, INT off)
INT eb_user (INT nfrag, BOOL mismatch, EBUILDER_CHANNEL *ebch, EVENT_HEADER *pheader, void *pevent, INT *dest_size)
Variables
char * frontend_name = "Ebuilder"
char * frontend_file_name = __FILE__
BOOL ebuilder_call_loop = FALSE
INT display_period = 3000
INT max_event_size = MAX_EVENT_SIZE
INT max_event_size_frag = MAX_EVENT_SIZE
INT event_buffer_size = EVENT_BUFFER_SIZE
INT lModulo = 100
Global var for testing.
EQUIPMENT equipment []
Define Documentation
#define NUMCRATES 5
Definition at line 63 of file ebuser.cpp.
Referenced by eb_begin_of_run().
Function Documentation
INT eb_begin_of_run (INT rn, char * UserField, char * error)
Hook to the event builder task at PreStart transition.
Parameters:
rn run number
UserField argument from /Ebuilder/Settings
error error string to be passed back to the system.
Returns:
EB_SUCCESS
eb_begin_of_run() Hook to the event builder task at PreStart transition. {verbatim} {verbatim}
Parameters:
rn run number
UserField argument from /Ebuilder/Settings
error error string to be passed back to the system.
Returns:
EB_SUCCESS
Definition at line 145 of file ebuser.cpp.
Referenced by tr_prestart(), and tr_start().
{
#if 0
  extern EBUILDER_SETTINGS ebset;
  extern EBUILDER_CHANNEL  ebch[MAX_CHANNELS];
  extern HNDLE hDB;
  int n;
  int mask = 0;
  char keyName[256];
  BOOL enabled;
  int size;
  /*
   * Determine which crates are enabled and set up the mask
   * accordingly.
   */
  for(n = 1; n <= NUMCRATES; n++) {
    sprintf(keyName, "/Equipment/Crate %d/Settings/Enabled", n);
    size = sizeof(enabled);
    db_get_value(hDB, 0, keyName, &enabled, &size, TID_BOOL, FALSE);
    if(size == sizeof(enabled) && enabled) {
       ebch[n-1].trigger_mask = (1 << (n-1));
       mask |= ebch[n-1].trigger_mask;
    } else {
       ebch[n-1].trigger_mask = 0;
    }
  }
  cm_msg(MINFO, "eb_begin_of_run", "Setting event mask to 0x%x", mask);
  ebset.trigger_mask = mask;
#endif
  // Initialize online compression
  compress_load_all();
  return EB_SUCCESS;
}
INT eb_end_of_run (INT rn, char * error)
Hook to the event builder task at completion of event collection after receiving the Stop transition.
Parameters:
rn run number
error error string to be passed back to the system.
Returns:
EB_SUCCESS
eb_end_of_run() Hook to the event builder task at completion of event collection after receiving the Stop transition. {verbatim} {verbatim}
Parameters:
rn run number
error error string to be passed back to the system.
Returns:
EB_SUCCESS
Definition at line 193 of file ebuser.cpp.
Referenced by close_buffers(), and main().
{
   return EB_SUCCESS;
}
INT eb_user (INT nfrag, BOOL mismatch, EBUILDER_CHANNEL * ebch, EVENT_HEADER * pheader, void * pevent, INT * dest_size)
Hook to the event builder task after the reception of all fragments of the same serial number. The destination event has already the final EVENT_HEADER setup with the data size set to 0. It is than possible to add private data at this point using the proper bank calls.
The ebch[] array structure points to nfragment channel structure with the following content:
typedef struct {
    char  name[32];         // Fragment name (Buffer name).
    DWORD serial;           // Serial fragment number.
    char *pfragment;        // Pointer to fragment (EVENT_HEADER *)
    ...
} EBUILDER_CHANNEL;
The correct code for including your own MIDAS bank is shown below where TID_xxx is one of the valid Bank type starting with TID_ for midas format or xxx_BKTYPE for Ybos data format. bank_name is a 4 character descriptor. pdata has to be declared accordingly with the bank type. Refers to the ebuser.c source code for further description.
It is not possible to mix within the same destination event different event format!
  // Event is empty, fill it with BANK_HEADER
  // If you need to add your own bank at this stage
  bk_init(pevent);
  bk_create(pevent, bank_name, TID_xxxx, &pdata);
  *pdata++ = ...;
  *dest_size = bk_close(pevent, pdata);
  pheader->data_size = *dest_size + sizeof(EVENT_HEADER);
For YBOS format, use the following example.
  ybk_init(pevent);
  ybk_create(pevent, "EBBK", I4_BKTYPE, &pdata);
  *pdata++ = 0x12345678;
  *pdata++ = 0x87654321;
  *dest_size = ybk_close(pevent, pdata);
  *dest_size *= 4;
  pheader->data_size = *dest_size + sizeof(YBOS_BANK_HEADER);
Parameters:
nfrag Number of fragment.
mismatch Midas Serial number mismatch flag.
ebch Structure to all the fragments.
pheader Destination pointer to the header.
pevent Destination pointer to the bank header.
dest_size Destination event size in bytes.
Returns:
EB_SUCCESS
Definition at line 259 of file ebuser.cpp.
Referenced by source_scan().
{
  if (mismatch){
    printf("Serial number do not match across fragments\n");
    for (int i = 0; i < nfrag; i++) {
      int serial = ((EVENT_HEADER *) ebch[i].pfragment)->serial_number;
      printf("Ser[%i]:%d ", i + 1, serial);
    }
    printf("\n");
    return EB_USER_ERROR;
  }
  // Initialize output event
  bk_init32(pevent);
  // Loop over the event fragments, performing compression into the output event
  for(int i = 0; i < nfrag; i++) {
    void *fragment =  ebch[i].pfragment;
    if(fragment != NULL) {
      compress_event(((EVENT_HEADER *) fragment) + 1, pevent);
      pheader->serial_number =
        ((EVENT_HEADER *) ebch[i].pfragment)->serial_number;
    }
  }
  // Set the size of the output event properly
  pheader->data_size = *dest_size = bk_size(pevent);
  // printf("Returning size %d\n", pheader->data_size);
  return EB_SUCCESS;
}
INT ebuilder_exit (void)
Definition at line 126 of file ebuser.cpp.
Referenced by main().
{
  return EB_SUCCESS;
}
INT ebuilder_init (void)
Definition at line 120 of file ebuser.cpp.
Referenced by main().
{
  return EB_SUCCESS;
}
INT ebuilder_loop (void)
Definition at line 132 of file ebuser.cpp.
{
  return EB_SUCCESS;
}
INT ebuser (INT , BOOL mismatch, EBUILDER_CHANNEL * , EVENT_HEADER * , void * , INT *)
INT read_scaler_event (char * pevent, INT off)
Definition at line 336 of file ebfe.c.
{
   DWORD *pdata, a;
   /* init bank structure */
   bk_init(pevent);
   /* create SCLR bank */
   bk_create(pevent, Sclx, TID_DWORD, &pdata);
   /* read scaler bank */
   for (a = 0; a < N_SCLR; a++)
      cam24i(CRATE, SLOT_SCLR, a, 0, pdata++);
   bk_close(pevent, pdata);
   return bk_size(pevent);
}
Variable Documentation
INT display_period = 3000
Definition at line 77 of file ebuser.cpp.
BOOL ebuilder_call_loop = FALSE
Definition at line 74 of file ebuser.cpp.
EQUIPMENT equipment[]
Initial value:
 {
   {"EB",
    {1, 0,
     "SYSTEM",
     0,
     0,
     "MIDAS",
     TRUE,
     },
    },
  {""}
}
Definition at line 102 of file ebuser.cpp.
INT event_buffer_size = EVENT_BUFFER_SIZE
Definition at line 86 of file ebuser.cpp.
char* frontend_file_name = __FILE__
Definition at line 71 of file ebuser.cpp.
char* frontend_name = "Ebuilder"
Definition at line 68 of file ebuser.cpp.
INT lModulo = 100
Global var for testing.
Globals
Definition at line 90 of file ebuser.cpp.
Referenced by build_log_list(), and eb_begin_of_run().
INT max_event_size = MAX_EVENT_SIZE
Definition at line 80 of file ebuser.cpp.
INT max_event_size_frag = MAX_EVENT_SIZE
Definition at line 83 of file ebuser.cpp.