AlcapDAQ:Rootana: midas/mscb/embedded/mscb.h File Reference
midas/mscb/embedded/mscb.h File Reference
Data Structures
struct MSCB_INFO
struct MSCB_INFO_VAR
struct SYS_INFO
Defines
#define USE_WATCHDOG
#define EEPROM_SUPPORT
#define LED_OFF !LED_ON
#define N_LED 0
#define SCON0 SCON
#define SBUF0 SBUF
#define TI0 TI
#define RI0 RI
#define RB80 RB8
#define ES0 ES
#define PS0 PS
#define EEPROM_OFFSET 0x8000
#define VERSION 0x17
#define CMD_ADDR_NODE8 0x09
#define CMD_ADDR_NODE16 0x0A
#define CMD_ADDR_BC 0x10
#define CMD_ADDR_GRP8 0x11
#define CMD_ADDR_GRP16 0x12
#define CMD_PING8 0x19
#define CMD_PING16 0x1A
#define CMD_INIT 0x20
#define CMD_GET_INFO 0x28
#define CMD_SET_ADDR 0x34
#define CMD_SET_BAUD 0x39
#define CMD_FREEZE 0x41
#define CMD_SYNC 0x49
#define CMD_UPGRADE 0x50
#define CMD_USER 0x58
#define CMD_ECHO 0x61
#define CMD_TOKEN 0x68
#define CMD_SET_FLAGS 0x69
#define CMD_ACK 0x78
#define CMD_WRITE_NA 0x80
#define CMD_WRITE_ACK 0x88
#define CMD_FLASH 0x98
#define CMD_READ 0xA0
#define CMD_WRITE_BLOCK 0xB5
#define CMD_READ_BLOCK 0xB9
#define GET_INFO_GENERAL 0
#define GET_INFO_VARIABLES 1
#define CSR_DEBUG (1<<0)
#define CSR_LCD_PRESENT (1<<1)
#define CSR_SYNC_MODE (1<<2)
#define CSR_FREEZE_MODE (1<<3)
#define CSR_WD_RESET (1<<2)
#define BD_9600 1
#define BD_19200 2
#define BD_28800 3
#define BD_57600 4
#define BD_115200 5
#define BD_172800 6
#define BD_345600 7
#define MSCBF_FLOAT (1<<0)
#define MSCBF_SIGNED (1<<1)
#define MSCBF_DATALESS (1<<2)
#define MSCBF_HIDDEN (1<<3)
#define MSCBF_REMIN (1<<4)
#define MSCBF_REMOUT (1<<5)
#define PRFX_PICO -12
#define PRFX_NANO -9
#define PRFX_MICRO -6
#define PRFX_MILLI -3
#define PRFX_NONE 0
#define PRFX_KILO 3
#define PRFX_MEGA 6
#define PRFX_GIGA 9
#define PRFX_TERA 12
#define UNIT_UNDEFINED 0
#define UNIT_METER 1
#define UNIT_GRAM 2
#define UNIT_SECOND 3
#define UNIT_MINUTE 4
#define UNIT_HOUR 5
#define UNIT_AMPERE 6
#define UNIT_KELVIN 7
#define UNIT_CELSIUS 8
#define UNIT_FARENHEIT 9
#define UNIT_HERTZ 20
#define UNIT_PASCAL 21
#define UNIT_BAR 22
#define UNIT_WATT 23
#define UNIT_VOLT 24
#define UNIT_OHM 25
#define UNIT_TESLA 26
#define UNIT_LITERPERSEC 27
#define UNIT_RPM 28
#define UNIT_FARAD 29
#define UNIT_BOOLEAN 50
#define UNIT_BYTE 52
#define UNIT_WORD 53
#define UNIT_DWORD 54
#define UNIT_ASCII 55
#define UNIT_STRING 56
#define UNIT_BAUD 57
#define UNIT_PERCENT 90
#define UNIT_PPM 91
#define UNIT_COUNT 92
#define UNIT_FACTOR 93
#define ENABLE_INTERRUPTS { EA = 1; }
#define DISABLE_INTERRUPTS { EA = 0; }
Functions
void watchdog_refresh (void)
void yield (void)
void led_set (unsigned char led, unsigned char flag) reentrant
void led_blink (unsigned char led, unsigned char n, int interval) reentrant
void led_mode (unsigned char led, unsigned char flag) reentrant
void delay_us (unsigned int us)
void delay_ms (unsigned int ms)
unsigned char crc8 (unsigned char *buffer, int len) reentrant
unsigned char crc8_add (unsigned char crc, unsigned int c)
void lcd_setup ()
void lcd_clear ()
void lcd_goto (char x, char y)
void lcd_putc (char c)
void lcd_puts (char *str)
char scs_lcd1_read ()
char getchar_nowait (void)
unsigned char gets_wait (char *str, unsigned char size, unsigned char timeout)
void flush (void)
void eeprom_flash (void)
unsigned char eeprom_retrieve (void)
void uart_init (unsigned char port, unsigned char baud)
unsigned char uart1_send (char *buffer, int size)
unsigned char uart1_receive (char *buffer, int size)
void send_remote_var (unsigned char i)
void sysclock_init (void)
unsigned long time (void)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
void set_n_sub_addr (unsigned char n)
unsigned char cur_sub_addr (void)
Define Documentation
#define BD_115200 5
Definition at line 370 of file mscb.h.
Referenced by setup().
#define BD_172800 6
Definition at line 371 of file mscb.h.
#define BD_19200 2
Definition at line 367 of file mscb.h.
#define BD_28800 3
Definition at line 368 of file mscb.h.
#define BD_345600 7
Definition at line 372 of file mscb.h.
#define BD_57600 4
Definition at line 369 of file mscb.h.
#define BD_9600 1
Definition at line 366 of file mscb.h.
#define CMD_ACK 0x78
Definition at line 341 of file mscb.h.
Referenced by interprete(), and upgrade().
#define CMD_ADDR_BC 0x10
Definition at line 321 of file mscb.h.
Referenced by interprete().
#define CMD_ADDR_GRP16 0x12
Definition at line 323 of file mscb.h.
Referenced by interprete().
#define CMD_ADDR_GRP8 0x11
Definition at line 322 of file mscb.h.
Referenced by interprete().
#define CMD_ADDR_NODE16 0x0A
Definition at line 320 of file mscb.h.
Referenced by interprete().
#define CMD_ADDR_NODE8 0x09
Definition at line 319 of file mscb.h.
Referenced by interprete().
#define CMD_ECHO 0x61
Definition at line 337 of file mscb.h.
Referenced by interprete().
#define CMD_FLASH 0x98
Definition at line 346 of file mscb.h.
Referenced by interprete().
#define CMD_FREEZE 0x41
Definition at line 332 of file mscb.h.
Referenced by interprete().
#define CMD_GET_INFO 0x28
Definition at line 328 of file mscb.h.
Referenced by interprete().
#define CMD_INIT 0x20
Definition at line 327 of file mscb.h.
#define CMD_PING16 0x1A
Definition at line 325 of file mscb.h.
Referenced by interprete().
#define CMD_PING8 0x19
Definition at line 324 of file mscb.h.
Referenced by interprete().
#define CMD_READ 0xA0
Definition at line 348 of file mscb.h.
#define CMD_READ_BLOCK 0xB9
Definition at line 351 of file mscb.h.
#define CMD_SET_ADDR 0x34
Definition at line 329 of file mscb.h.
Referenced by interprete().
#define CMD_SET_BAUD 0x39
Definition at line 330 of file mscb.h.
Referenced by interprete().
#define CMD_SET_FLAGS 0x69
Definition at line 339 of file mscb.h.
#define CMD_SYNC 0x49
Definition at line 333 of file mscb.h.
Referenced by interprete().
#define CMD_TOKEN 0x68
Definition at line 338 of file mscb.h.
#define CMD_UPGRADE 0x50
Definition at line 334 of file mscb.h.
Referenced by interprete().
#define CMD_USER 0x58
Definition at line 335 of file mscb.h.
Referenced by interprete().
#define CMD_WRITE_ACK 0x88
Definition at line 344 of file mscb.h.
Referenced by interprete().
#define CMD_WRITE_BLOCK 0xB5
Definition at line 350 of file mscb.h.
#define CMD_WRITE_NA 0x80
Definition at line 343 of file mscb.h.
Referenced by interprete().
#define CSR_DEBUG (1<<0)
Definition at line 358 of file mscb.h.
Referenced by cmd_loop().
#define CSR_FREEZE_MODE (1<<3)
Definition at line 361 of file mscb.h.
#define CSR_LCD_PRESENT (1<<1)
Definition at line 359 of file mscb.h.
#define CSR_SYNC_MODE (1<<2)
Definition at line 360 of file mscb.h.
#define CSR_WD_RESET (1<<2)
Definition at line 362 of file mscb.h.
#define DISABLE_INTERRUPTS { EA = 0; }
Definition at line 474 of file mscb.h.
Referenced by adc_read(), cap_read(), eeprom_erase(), eeprom_write(), read_current(), read_hv(), read_temperature(), time(), and user_loop().
#define EEPROM_OFFSET 0x8000
Definition at line 300 of file mscb.h.
Referenced by eeprom_erase(), eeprom_read(), and eeprom_write().
#define EEPROM_SUPPORT
Definition at line 153 of file mscb.h.
#define ENABLE_INTERRUPTS { EA = 1; }
Definition at line 473 of file mscb.h.
Referenced by adc_read(), cap_read(), eeprom_erase(), eeprom_write(), read_current(), read_hv(), read_temperature(), time(), and user_loop().
#define ES0 ES
Definition at line 289 of file mscb.h.
Referenced by interprete(), and uart_init().
#define GET_INFO_GENERAL 0
Definition at line 353 of file mscb.h.
#define GET_INFO_VARIABLES 1
Definition at line 354 of file mscb.h.
#define LED_OFF !LED_ON
Definition at line 266 of file mscb.h.
Referenced by led_int(), and upgrade().
#define MSCBF_DATALESS (1<<2)
Definition at line 404 of file mscb.h.
Referenced by interprete(), lcd_menu(), and setup().
#define MSCBF_FLOAT (1<<0)
Definition at line 402 of file mscb.h.
Referenced by addr_changed(), cmd_loop(), display_value(), print_channel_str(), and var_inc().
#define MSCBF_HIDDEN (1<<3)
Definition at line 405 of file mscb.h.
#define MSCBF_REMIN (1<<4)
Definition at line 406 of file mscb.h.
#define MSCBF_REMOUT (1<<5)
Definition at line 407 of file mscb.h.
Referenced by lcd_menu(), and setup().
#define MSCBF_SIGNED (1<<1)
Definition at line 403 of file mscb.h.
Referenced by display_value(), print_channel_str(), and var_inc().
#define N_LED 0
Definition at line 279 of file mscb.h.
Referenced by led_blink(), led_int(), led_mode(), led_set(), setup(), and sysclock_init().
#define PRFX_GIGA 9
Definition at line 418 of file mscb.h.
#define PRFX_KILO 3
Definition at line 416 of file mscb.h.
#define PRFX_MEGA 6
Definition at line 417 of file mscb.h.
#define PRFX_MICRO -6
Definition at line 413 of file mscb.h.
#define PRFX_MILLI -3
Definition at line 414 of file mscb.h.
#define PRFX_NANO -9
Definition at line 412 of file mscb.h.
#define PRFX_NONE 0
Definition at line 415 of file mscb.h.
#define PRFX_PICO -12
Definition at line 411 of file mscb.h.
#define PRFX_TERA 12
Definition at line 419 of file mscb.h.
#define PS0 PS
Definition at line 290 of file mscb.h.
Referenced by uart_init().
#define RB80 RB8
Definition at line 288 of file mscb.h.
Referenced by serial_int().
#define RI0 RI
Definition at line 287 of file mscb.h.
Referenced by serial_int(), and upgrade().
#define SBUF0 SBUF
Definition at line 285 of file mscb.h.
Referenced by check_lpt(), interprete(), rs485_send(), send_byte(), serial_int(), and upgrade().
#define SCON0 SCON
Definition at line 284 of file mscb.h.
Referenced by uart_init().
#define TI0 TI
Definition at line 286 of file mscb.h.
Referenced by main(), send_byte(), serial_int(), and upgrade().
#define UNIT_AMPERE 6
Definition at line 429 of file mscb.h.
#define UNIT_ASCII 55
Definition at line 453 of file mscb.h.
#define UNIT_BAR 22
Definition at line 438 of file mscb.h.
#define UNIT_BAUD 57
Definition at line 455 of file mscb.h.
#define UNIT_BOOLEAN 50
Definition at line 449 of file mscb.h.
#define UNIT_BYTE 52
Definition at line 450 of file mscb.h.
#define UNIT_CELSIUS 8
Definition at line 431 of file mscb.h.
#define UNIT_COUNT 92
Definition at line 461 of file mscb.h.
#define UNIT_DWORD 54
Definition at line 452 of file mscb.h.
#define UNIT_FACTOR 93
Definition at line 462 of file mscb.h.
#define UNIT_FARAD 29
Definition at line 445 of file mscb.h.
#define UNIT_FARENHEIT 9
Definition at line 432 of file mscb.h.
#define UNIT_GRAM 2
Definition at line 425 of file mscb.h.
#define UNIT_HERTZ 20
Definition at line 436 of file mscb.h.
#define UNIT_HOUR 5
Definition at line 428 of file mscb.h.
#define UNIT_KELVIN 7
Definition at line 430 of file mscb.h.
#define UNIT_LITERPERSEC 27
Definition at line 443 of file mscb.h.
#define UNIT_METER 1
Definition at line 424 of file mscb.h.
#define UNIT_MINUTE 4
Definition at line 427 of file mscb.h.
#define UNIT_OHM 25
Definition at line 441 of file mscb.h.
#define UNIT_PASCAL 21
Definition at line 437 of file mscb.h.
#define UNIT_PERCENT 90
Definition at line 459 of file mscb.h.
#define UNIT_PPM 91
Definition at line 460 of file mscb.h.
#define UNIT_RPM 28
Definition at line 444 of file mscb.h.
#define UNIT_SECOND 3
Definition at line 426 of file mscb.h.
#define UNIT_STRING 56
Definition at line 454 of file mscb.h.
Referenced by cmd_loop(), display_value(), interprete(), print_channel_str(), and var_inc().
#define UNIT_TESLA 26
Definition at line 442 of file mscb.h.
#define UNIT_UNDEFINED 0
Definition at line 421 of file mscb.h.
#define UNIT_VOLT 24
Definition at line 440 of file mscb.h.
#define UNIT_WATT 23
Definition at line 439 of file mscb.h.
#define UNIT_WORD 53
Definition at line 451 of file mscb.h.
#define USE_WATCHDOG
Definition at line 150 of file mscb.h.
#define VERSION 0x17
Definition at line 305 of file mscb.h.
Function Documentation
unsigned char crc8 (unsigned char * buffer, int len)
Definition at line 187 of file mscbutil.c.
References buffer, crc8_data, i, and index.
Referenced by interprete(), mscb_addr(), mscb_echo(), mscb_flash(), mscb_info(), mscb_info_variable(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_group(), and serial_int().
         : crc8
  Purpose: Calculate 8-bit cyclic redundancy checksum for a full
           buffer
  Input:
    unsigned char *data     data buffer
    int len                 data length in bytes
  Function value:
    unsighend char          CRC-8 code
\********************************************************************/
{
   int i;
   unsigned char crc8_code, index;
   crc8_code = 0;
   for (i = 0; i < len; i++) {
      index = buffer[i] ^ crc8_code;
      crc8_code = crc8_data[index];
   }
   return crc8_code;
}
unsigned char crc8_add (unsigned char crc, unsigned int c)
Definition at line 217 of file mscbutil.c.
References crc8_data, and index.
Referenced by send_byte().
         : crc8_add
  Purpose: Single calculation for 8-bit cyclic redundancy checksum
  Input:
    unsigned char crc       running crc
    unsigned char c         new character
  Function value:
    unsighend char          CRC-8 code
\********************************************************************/
{
   unsigned char index;
   index = c ^ crc;
   return crc8_data[index];
}
unsigned char cur_sub_addr (void)
Definition at line 532 of file mscbmain.c.
References _cur_sub_addr.
Referenced by user_write().
{
   return _cur_sub_addr;
}
void delay_ms (unsigned int ms)
Definition at line 902 of file mscbutil.c.
References delay_us(), and yield().
Referenced by adc_read(), lcd_menu(), lcd_setup(), rs485_receive(), user_init(), and user_loop().
{
   unsigned int i;
   for (i = 0; i < ms; i++) {
      delay_us(1000);
      yield();
   }
}
void delay_us (unsigned int us)
Definition at line 937 of file mscbutil.c.
References delay_us(), and j.
Referenced by cap_read(), delay_ms(), delay_us(), lcd_out(), lcd_setup(), read_adc24(), read_adc8(), rs485_receive(), send_byte(), ser_clock(), setup(), sr_read(), write_adc(), write_dac(), and write_gain().
{
#ifdef CPU_C8051F120
   unsigned char j;
#endif
   unsigned char i;
   unsigned int remaining_us;
   if (us <= 250) {
      for (i = (unsigned char) us; i > 0; i--) {
#ifdef CPU_C8051F120
         for (j=22 ; j>0 ; j--)
            _nop_();
#else
         _nop_();
#endif
      }
   } else {
      remaining_us = us;
      while (remaining_us > 250) {
         delay_us(250);
         remaining_us -= 250;
      }
      if (us > 0)
         delay_us(remaining_us);
   }
}
void eeprom_flash (void)
Definition at line 1212 of file mscbutil.c.
References _flkey, _n_sub_addr, _var_size, eeprom_erase(), eeprom_write(), led_blink(), offset, variables, width, and MSCB_INFO_VAR::width.
Referenced by yield().
         : eeprom_flash
  Purpose: Write system and user parameters to EEPROM
\********************************************************************/
{
   unsigned char i, adr;
   unsigned short magic, offset;
   led_blink(3, 3, 50);
   eeprom_erase();
   offset = 0;
   // system info (node address etc...)
   eeprom_write(&sys_info, sizeof(SYS_INFO), &offset);
   // user channel variables
   for (adr = 0 ; adr < _n_sub_addr ; adr++)
      for (i = 0; variables[i].width; i++)
         eeprom_write((char *)variables[i].ud + _var_size*adr,
                      variables[i].width, &offset);
   // magic
   magic = 0x1234;
   eeprom_write(&magic, 2, &offset);
   _flkey = 0;
}
unsigned char eeprom_retrieve (void)
Definition at line 1248 of file mscbutil.c.
References _n_sub_addr, _var_size, eeprom_read(), offset, variables, width, and MSCB_INFO_VAR::width.
Referenced by setup().
         : eeprom_retrieve
  Purpose: Retrieve system and user parameters from EEPROM
\********************************************************************/
{
   unsigned char i, adr;
   unsigned short magic, offset;
   offset = 0;
   // system info (node address etc...)
   eeprom_read(&sys_info, sizeof(SYS_INFO), &offset);
   // user channel variables
   for (adr = 0 ; adr < _n_sub_addr ; adr++)
      for (i = 0; variables[i].width; i++)
         eeprom_read((char *)variables[i].ud + _var_size*adr,
                     variables[i].width, &offset);
   // check for magic
   eeprom_read(&magic, 2, &offset);
   return (magic == 0x1234);
}
void flush (void)
Referenced by main(), tc600_read(), tc600_write(), and user_loop().
char getchar_nowait (void)
Definition at line 164 of file scs_300.c.
References c, LPT_BUSY, LPT_DATA, and LPT_SELECT.
Referenced by gets_wait(), user_loop(), and user_read().
{
   char c;
   /* if busy signal high -> no data */
   if (LPT_BUSY == 1)
      return -1;
   /* read byte */
   c = LPT_DATA;
   /* singal received data */
   LPT_SELECT = 0;
   /* wait for busy go high */
   while (LPT_BUSY == 0);
   /* remove select */
   LPT_SELECT = 1;
}
unsigned char gets_wait (char * str, unsigned char size, unsigned char timeout)
Definition at line 185 of file scs_300.c.
References c, getchar_nowait(), i, time, and yield().
Referenced by tc600_read(), tc600_write(), and user_loop().
{
   unsigned long idata start;
   unsigned char i;
   char c;
   start = time();
   i = 0;
   do {
      c = getchar_nowait();
      if (c != -1 && c != '\n') {
         if (c == '\r') {
            str[i] = 0;
            return i;
         }
         str[i++] = c;
         if (i == size)
            return i;
      }
      yield();
   } while (time() < start + timeout);
   return 0;
}
void lcd_clear ()
Definition at line 1418 of file mscbutil.c.
References lcd_goto(), and lcd_out().
Referenced by application_display(), debug_output(), lcd_menu(), user_loop(), and yield().
{
   lcd_out(0x01, 0);
   lcd_goto(0, 0);
}
void lcd_goto (char x, char y)
Definition at line 1426 of file mscbutil.c.
References lcd_out().
Referenced by application_display(), debug_output(), display_name(), display_value(), lcd_clear(), lcd_menu(), user_init(), and user_loop().
{
   /* goto position x(0..19), y(0..1) */
   lcd_out((x & 0x0F) | (0x80) | ((y & 0x01) << 6), 0);
}
void lcd_putc (char c)
void lcd_puts (char * str)
Definition at line 1444 of file mscbutil.c.
References lcd_out().
{
   while (*str)
      lcd_out(*str++, 1);
}
void lcd_setup ()
Definition at line 1364 of file mscbutil.c.
References CONFIG_PAGE, delay_ms(), delay_us(), lcd_out(), P2MDOUT, and SFRPAGE.
Referenced by setup().
{
   unsigned i=0;
   SFRPAGE = CONFIG_PAGE;
   P2MDOUT = 0xFF;
   LCD &= ~(0xFE);
   delay_ms(15);
   LCD |= 0x30;
   LCD_E = 1;
   delay_us(1);
   LCD_E = 0;
   delay_ms(5);
   LCD_E = 1;
   delay_us(1);
   LCD_E = 0;
   delay_ms(1);
   LCD_E = 1;
   delay_us(1);
   LCD_E = 0;
   LCD = 0x20;                  // set 4-bit interface
   LCD_E = 1;
   delay_us(1);
   LCD_E = 0;
   /* test if LCD present */
   LCD = LCD | 0xF0;            // data input
   P2MDOUT = 0x0F;
   LCD_RS = 0;                  // select BF
   LCD_R_W = 1;
   delay_us(1);
   LCD_E = 1;
   delay_us(100);               // let signal settle
   if (LCD_DB7) {
      lcd_present = 0;
      return;
   }
   lcd_present = 1;
   lcd_out(0x2C, 0);            // select 2 lines, big font
   lcd_out(0x0C, 0);            // display on
   lcd_out(0x01, 0);            // clear display
   lcd_out(0x06, 0);            // entry mode
}
void led_blink (unsigned char led, unsigned char n, int interval)
Definition at line 788 of file mscbutil.c.
References interval, n, N_LED, and timer.
Referenced by adc_calib(), BulkOrInterruptIn(), check_current(), check_lpt(), check_rs485(), eeprom_flash(), enter(), execute(), interprete(), main(), rs485_receive(), setup(), user_loop(), and yield().
         : blink led
  Purpose: Blink primary or secondary LED for a couple of times
  Input:
    int led               0 for primary, 1 for secondary, ...
    int interval          Blink interval in ms
    int n                 Number of blinks
\********************************************************************/
{
   if (led < N_LED) {
      if (leds[led].n == 0 && leds[led].timer == 0) {
         leds[led].n = n*2+1;
         leds[led].interval = interval / 10;
         leds[led].timer = 0;
      }
   }
}
void led_mode (unsigned char led, unsigned char flag)
Definition at line 769 of file mscbutil.c.
References flag, and N_LED.
Referenced by set_hv(), setup(), setupRegs(), and user_init().
         : led_mode
  Purpose: Set LED mode
  Input:
    int led               0 for primary, 1 for secondary
    int flag              Noninverted (0) / Inverted (1)
\********************************************************************/
{
   if (led < N_LED)
      leds[led].mode = flag;
}
void led_set (unsigned char led, unsigned char flag)
Definition at line 813 of file mscbutil.c.
References flag, mode, and N_LED.
Referenced by led_int().
{
   /* invert on/of if mode = 1 */
   if (led < N_LED && leds[led].mode)
      flag = !flag;
#ifdef LED_0
   if (led == 0)
      led_0 = flag;
#endif
#ifdef LED_1
   if (led == 1)
      led_1 = flag;
#endif
#ifdef LED_2
   if (led == 2)
      led_2 = flag;
#endif
#ifdef LED_3
   if (led == 3)
      led_3 = flag;
#endif
#ifdef LED_4
   if (led == 4)
      led_4 = flag;
#endif
}
char scs_lcd1_read ()
void send_remote_var (unsigned char i)
Referenced by lcd_menu(), setup(), and yield().
void set_n_sub_addr (unsigned char n)
void sysclock_init (void)
Definition at line 676 of file mscbutil.c.
References CKCON, EA, ET0, N_LED, PT1, SFRPAGE, TH0, TIMER01_PAGE, TL0, TMOD, and TR0.
Referenced by setup().
         : sysclock_init
  Purpose: Initial sytem clock via timer 0
*********************************************************************/
{
   unsigned char i;
   EA = 1;                      // general interrupt enable
   ET0 = 1;                     // Enable Timer 1 interrupt
   PT1 = 1;                     // Interrupt priority high
#ifdef CPU_C8051F120
   SFRPAGE = TIMER01_PAGE;
#endif
   TMOD = (TMOD & 0x0F) | 0x01; // 16-bit counter
#ifdef CPU_C8051F120
   CKCON = 0x02;                // use SYSCLK/48
   TH0 = 0xAF;                  // load initial value
#else
   CKCON = 0x00;                // use SYSCLK/12
   TH0 = 0xDB;                  // load initial value
#endif
   TL0 = 0x00;
   TR0 = 1;                     // start timer 1
   _systime = 0;
   for (i=0 ; i<N_LED ; i++) {
     leds[i].mode = 0;
     leds[i].timer = 0;
     leds[i].interval = 0;
     leds[i].n = 0;
   }
}
unsigned long time (void)
Definition at line 843 of file mscbutil.c.
References DISABLE_INTERRUPTS, and ENABLE_INTERRUPTS.
         : time
  Purpose: Return system time in units of 10ms
\********************************************************************/
{
   unsigned long t;
   DISABLE_INTERRUPTS;
   t = _systime;
   ENABLE_INTERRUPTS;
   return t;
}
unsigned char uart1_receive (char * buffer, int size)
unsigned char uart1_send (char * buffer, int size)
void uart_init (unsigned char port, unsigned char baud)
Definition at line 517 of file mscbutil.c.
References CKCON, EA, EIE2, EIP2, ES0, PS0, RCAP2H, RCAP2L, RCAP4H, RCAP4L, SCON0, SCON1, SFRPAGE, SSTA0, T2CON, T4CON, TH1, TIMER01_PAGE, TMOD, TMR2_PAGE, TMR2CF, TMR2CN, TR1, UART0_PAGE, and UART1_PAGE.
Referenced by setup(), user_init(), user_write(), and user_write_conf().
         : uart_init
  Purpose: Initialize serial interface, user Timer 1 for UART0 and
           (optionally) Timer 2 (4 for F020) for UART1
  Input:
    unsigned char baud      1:9600,2:19200,3:28800,4:57600,
                            5:115200,6:172800,7:345600 Baud
\********************************************************************/
{
#if defined (CPU_C8051F310)
   unsigned char code baud_table[] =
     {0x100 - 0,    //  N/A
      0x100 - 0,    //  N/A
      0x100 - 192,  //  28800
      0x100 - 96,   //  57600
      0x100 - 48,   // 115200
      0x100 - 32,   // 172800
      0x100 - 16 }; // 345600
#elif defined(CPU_C8051F320)       // 12 MHz
   unsigned char code baud_table[] =
     {0x100 - 0,    //  N/A
      0x100 - 0,    //  N/A
      0x100 - 208,  //  28800
      0x100 - 104,  //  57600
      0x100 - 52,   // 115200
      0x100 - 35,   // 172800  2% error
      0x100 - 17 }; // 345600  2% error
#elif defined(CPU_C8051F120)       // 98 MHz
   unsigned char code baud_table[] =  // UART0 via timer 2
     {0x100 - 0,    //  N/A
      0x100 - 0,    //  N/A
      0x100 - 208,  //  28800  2% error
      0x100 - 104,  //  57600  2% error
      0x100 - 53,   // 115200  2% error
      0x100 - 35,   // 172800  2% error
      0x100 - 18 }; // 345600  2% error
#else                              // 11.0592 MHz
   unsigned char code baud_table[] =
     {0x100 - 36,   //   9600
      0x100 - 18,   //  14400
      0x100 - 12,   //  28800
      0x100 - 6,    //  57600
      0x100 - 3,    // 115200
      0x100 - 2,    // 172800
      0x100 - 1 };  // 345600
#endif
   if (port == 0) { /*---- UART0 ----*/
#ifdef CPU_C8051F120
      SFRPAGE = UART0_PAGE;
#endif
      SCON0 = 0xD0;                // Mode 3, 9 bit, receive enable
#ifdef CPU_C8051F120
      SFRPAGE = UART0_PAGE;
      SSTA0 = 0x15;                // User Timer 2 for baud rate, div2 disabled
      SFRPAGE = TMR2_PAGE;
      TMR2CF = 0x08;               // use system clock for timer 2
      RCAP2H = 0xFF;
      RCAP2L = baud_table[baud - 1];  // load initial values
      TMR2CN = 0x04;               // start timer 2
      SFRPAGE = UART0_PAGE;
#else // CPU_C8051F120
      TMOD  = (TMOD & 0x0F)| 0x20; // Timer 1 8-bit counter with auto reload
#if defined(CPU_C8051F310) || defined(CPU_C8051F320)
      CKCON |= 0x08;               // use system clock
#else
      T2CON &= ~30;                // User Timer 1 for baud rate
      CKCON |= 0x10;               // use system clock
#endif
      TH1 = baud_table[baud - 1];  // load initial values
      TR1 = 1;                     // start timer 1
#endif // CPU_C8051F120
      ES0 = 1;                     // enable serial interrupt
      PS0 = 0;                     // serial interrupt low priority
   } else { /*---- UART1 ----*/
#if defined(CPU_C8051F020)
      SCON1 = 0x50;                // Mode 1, 8 bit, receive enable
      T4CON = 0x34;                // timer 4 RX+TX mode
      RCAP4H = 0xFF;
      RCAP4L = baud_table[baud - 1];
      EIE2 |= 0x40;                // enable serial interrupt
      EIP2 &= ~0x40;               // serial interrupt low priority
#ifdef SCS_210
      uart1_init_buffer();
#endif
#elif defined(CPU_C8051F120)       // 98 MHz
      SFRPAGE = UART1_PAGE;
      SCON1 = 0xD0;                // Mode 3, 9 bit, receive enable
      SFRPAGE = TIMER01_PAGE;
      TMOD  = (TMOD & 0x0F)| 0x20; // Timer 1 8-bit counter with auto reload
      CKCON = 0x02;                // use SYSCLK/48 (needed by timer 0)
      TH1 = 0xF7;                  // gives 113452 baud, neglegt "baud" parameter
      TR1 = 1;                     // start timer 1
      EIE2 |= 0x40;                // enable serial interrupt
      EIP2 &= ~0x40;               // serial interrupt low priority
      uart1_init_buffer();
#endif
   }
   EA = 1;                         // general interrupt enable
}
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 277 of file hvr_200.c.
Referenced by interprete().
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void watchdog_refresh (void)
Definition at line 862 of file mscbutil.c.
Referenced by adc_read(), check_lpt(), check_rs485(), eeprom_read(), eeprom_write(), main(), setup(), and yield().
         : watchdog_refresh
  Purpose: Refresh watchdog, has to be called regularly, otherwise
           the watchdog issues a reset
\********************************************************************/
{
#ifdef USE_WATCHDOG
#ifdef CPU_ADUC812
   WDR1 = 1;
   WDR2 = 1;
#endif
#ifdef CPU_CYGNAL
#if defined(CPU_C8051F310) || defined(CPU_C8051F320)
   PCA0CPH4 = 0x00;
#else
   WDTCN = 0xA5;
#endif
#endif
#endif
}
void yield (void)
Definition at line 1361 of file mscbmain.c.
References _flkey, configured, debug_output(), eeprom_flash(), flash_allowed, flash_param, flash_program, SYS_INFO::group_addr, lcd_clear(), led_blink(), LEGACY_PAGE, new_address, SYS_INFO::node_addr, reboot, rs232_output(), RSTSRC, send_remote_var(), SFRPAGE, time, upgrade(), watchdog_refresh(), SYS_INFO::wd_counter, and wrong_cpu.
Referenced by adc_read(), cap_read(), delay_ms(), enter(), gets_wait(), main(), read_current(), read_hv(), read_temperature(), send_byte(), and user_loop().
{
   watchdog_refresh();
   /* output debug info to LCD if asked by interrupt routine */
   debug_output();
   /* output RS232 data if present */
   rs232_output();
   /* manage remote variables on SCS-1000 */
#ifdef SCS_1000
   poll_remote_vars();
   if (var_to_send != 0xFF) {
      send_remote_var(var_to_send);
      var_to_send = 0xFF;
   }
#endif
   /* output new address to LCD if available */
#if !defined(CPU_ADUC812) && !defined(SCS_300) && !defined(SCS_210)     // SCS210/300 redefine printf()
#ifdef LCD_DEBUG
   if (new_address) {
      new_address = 0;
      lcd_clear();
      printf("AD:%04X GA:%04X WD:%d", sys_info.node_addr,
             sys_info.group_addr, sys_info.wd_counter);
   }
#endif
#endif
   /* blink LED if not configured */
   if (!configured)
      led_blink(0, 1, 50);
   /* blink LED if wrong CPU */
   if (wrong_cpu)
      led_blink(0, 1, 30);
   /* flash EEPROM if asked by interrupt routine, wait 5 sec
      after reboot (power might not be stable) */
   if (flash_param && flash_allowed) {
      flash_param = 0;
      /* reset watchdog counts */
      sys_info.wd_counter = 0;
      _flkey = 0xF1;
      eeprom_flash();
           configured = 1;
   }
   if (flash_program && flash_allowed) {
      flash_program = 0;
      /* go to "bootloader" program */
      upgrade();
   }
   /* allow flash 5 sec after reboot */
   if (time() > 500)
      flash_allowed = 1;
   if (reboot) {
#ifdef CPU_CYGNAL
#ifdef CPU_C8051F120
      SFRPAGE = LEGACY_PAGE;
#endif
      RSTSRC = 0x10;         // force software reset
#else
      WDCON = 0x00;          // 16 msec
      WDE = 1;
      while (1);             // should be hardware reset later...
#endif
   }
}