AlcapDAQ:Rootana: midas/gui/hvedit/qt/globals.h File Reference
midas/gui/hvedit/qt/globals.h File Reference
Functions
int MidasMessage (const char *str)
Function Documentation
int MidasMessage (const char * str)
MidasMessage translates midas error messages to Qt Dialogs.
return: 0
Parameters:
str error message.
Definition at line 49 of file globals.cpp.
References cm_get_client_info(), name, and NAME_LENGTH.
Referenced by CMExperiment::Connect(), cmExperiment::Connect(), HVChanged(), CMExperiment::StartTimer(), cmExperiment::StartTimer(), cmExperiment::timeOutProc(), Qt_hvEdit::updateChannelDefinitions(), Qt_hvEdit::updateODB_currentLimit(), and Qt_hvEdit::updateODB_demand().
{
  char name[NAME_LENGTH];
  cm_get_client_info(name);
  QMessageBox::warning(0, "MIDAS ERROR", str, QMessageBox::Ok, QMessageBox::NoButton);
  return 0;
}