AlcapDAQ:Rootana: Midas RPC Functions (rpc_xxx)
Midas RPC Functions (rpc_xxx)
[The midas.h & midas.c]
Data Structures
struct TR_FIFO
Functions
void rpc_calc_convert_flags (INT hw_type, INT remote_hw_type, INT *convert_flags)
void rpc_get_convert_flags (INT *convert_flags)
void rpc_ieee2vax_float (float *var)
void rpc_vax2ieee_float (float *var)
void rpc_vax2ieee_double (double *var)
void rpc_ieee2vax_double (double *var)
void rpc_convert_single (void *data, INT tid, INT flags, INT convert_flags)
void rpc_convert_data (void *data, INT tid, INT flags, INT total_size, INT convert_flags)
INT rpc_tid_size (INT id)
char * rpc_tid_name (INT id)
INT rpc_register_client (char *name, RPC_LIST *list)
INT rpc_register_functions (RPC_LIST *new_list, INT(*func)(INT, void **))
INT rpc_deregister_functions ()
INT rpc_register_function (INT id, INT(*func)(INT, void **))
INT rpc_client_dispatch (int sock)
INT rpc_client_connect (char *host_name, INT port, char *client_name, HNDLE *hConnection)
void rpc_client_check ()
INT rpc_server_connect (char *host_name, char *exp_name)
INT rpc_client_disconnect (HNDLE hConn, BOOL bShutdown)
INT rpc_server_disconnect ()
INT rpc_is_remote (void)
INT rpc_get_server_acception (void)
INT rpc_set_server_acception (INT index)
INT rpc_get_option (HNDLE hConn, INT item)
INT rpc_set_option (HNDLE hConn, INT item, INT value)
PTYPE rpc_get_server_option (INT item)
INT rpc_set_server_option (INT item, PTYPE value)
INT rpc_get_name (char *name)
INT rpc_set_name (char *name)
INT rpc_set_debug (void(*func)(char *), INT mode)
void rpc_debug_printf (char *format,...)
void rpc_va_arg (va_list *arg_ptr, INT arg_type, void *arg)
INT rpc_client_call (HNDLE hConn, const INT routine_id,...)
INT rpc_call (const INT routine_id,...)
INT rpc_set_opt_tcp_size (INT tcp_size)
INT rpc_get_opt_tcp_size ()
INT rpc_send_event (INT buffer_handle, void *source, INT buf_size, INT async_flag)
int rpc_get_send_sock ()
int rpc_get_event_sock ()
INT rpc_flush_event ()
int cm_query_transition (int *transition, int *run_number, int *trans_time)
INT recv_tcp_server (INT index, char *buffer, DWORD buffer_size, INT flags, INT *remaining)
INT recv_tcp_check (int sock)
INT recv_event_server (INT index, char *buffer, DWORD buffer_size, INT flags, INT *remaining)
INT recv_event_check (int sock)
INT rpc_register_server (INT server_type, char *name, INT *port, INT(*func)(INT, void **))
INT rpc_execute (INT sock, char *buffer, INT convert_flags)
INT rpc_execute_ascii (INT sock, char *buffer)
INT rpc_server_accept (int lsock)
INT rpc_client_accept (int lsock)
INT rpc_server_callback (struct callback_addr *pcallback)
INT rpc_server_thread (void *pointer)
INT rpc_server_receive (INT index, int sock, BOOL check)
INT rpc_server_shutdown (void)
INT rpc_check_channels (void)
Variables
RPC_CLIENT_CONNECTION _client_connection [MAX_RPC_CONNECTION]
RPC_SERVER_CONNECTION _server_connection
static int _lsock
RPC_SERVER_ACCEPTION _server_acception [MAX_RPC_CONNECTION]
static INT _server_acception_index = 0
static INT _server_type
static char _server_name [256]
static RPC_LIST * rpc_list = NULL
int _opt_tcp_size = OPT_TCP_SIZE
static TR_FIFO tr_fifo [10]
static int trf_wp
static int trf_rp
Detailed Description
dox dox dox
Function Documentation
int cm_query_transition (int * transition, int * run_number, int * trans_time)
Definition at line 10405 of file midas.c.
References FALSE, TR_FIFO::run_number, TR_FIFO::transition, and TRUE.
Referenced by main().
10408          : cm_query_transition
10409
10410   Purpose: Query system if transition has occured. Normally, one
10411            registers callbacks for transitions via
10412            cm_register_transition. In some environments however,
10413            callbacks are not possible. In that case one spciefies
10414            a NULL pointer as the callback routine and can query
10415            transitions "manually" by calling this functions. A small
10416            FIFO takes care that no transition is lost if this functions
10417            did not get called between some transitions.
10418
10419   Output:
10420     INT   *transition        Type of transition, one of TR_xxx
10421     INT   *run_nuber         Run number for transition
10422     time_t *trans_time       Time (in UNIX time) of transition
10423
10424   Function value:
10425     FALSE  No transition occured since last call
10426     TRUE   Transition occured
10427
10428 \********************************************************************/
10429 {
10430
10431    if (trf_wp == trf_rp)
10432       return FALSE;
10433
10434    if (transition)
10435       *transition = tr_fifo[trf_rp].transition;
10436
10437    if (run_number)
10438       *run_number = tr_fifo[trf_rp].run_number;
10439
10440    if (trans_time)
10441       *trans_time = (int)tr_fifo[trf_rp].trans_time;
10442
10443    trf_rp = (trf_rp + 1) % 10;
10444
10445    return TRUE;
10446 }
INT recv_event_check (int sock)
Definition at line 10835 of file midas.c.
References RPC_SERVER_ACCEPTION::ev_read_ptr, RPC_SERVER_ACCEPTION::ev_write_ptr, index, and MAX_RPC_CONNECTION.
Referenced by ss_suspend().
10838          : recv_event_check
10839
10840   Purpose: Check if in TCP event receive buffer associated with sock
10841            is some data. Called by ss_suspend.
10842
10843   Input:
10844     INT   sock               TCP receive socket
10845
10846   Output:
10847     none
10848
10849   Function value:
10850     INT   count              Number of bytes remaining in TCP buffer
10851
10852 \********************************************************************/
10853 {
10854    INT index;
10855
10856    /* figure out to which connection socket belongs */
10857    for (index = 0; index < MAX_RPC_CONNECTION; index++)
10858       if (_server_acception[index].event_sock == sock)
10859          break;
10860
10861    return _server_acception[index].ev_write_ptr - _server_acception[index].ev_read_ptr;
10862 }
INT recv_event_server (INT index, char * buffer, DWORD buffer_size, INT flags, INT * remaining)
Definition at line 10655 of file midas.c.
References ALIGN8, cm_msg, RPC_SERVER_ACCEPTION::convert_flags, EVENT_HEADER::data_size, RPC_SERVER_ACCEPTION::ev_misalign, RPC_SERVER_ACCEPTION::ev_net_buffer, RPC_SERVER_ACCEPTION::ev_read_ptr, RPC_SERVER_ACCEPTION::ev_write_ptr, EVENT_HEADER::event_id, RPC_SERVER_ACCEPTION::event_sock, M_MALLOC, MERROR, net_buffer, NET_BUFFER_SIZE, RPC_SERVER_ACCEPTION::net_buffer_size, NET_TCP_SIZE, rpc_convert_single(), rpc_get_server_option(), RPC_OSERVER_TYPE, EVENT_HEADER::serial_number, size, ST_REMOTE, status, TID_DWORD, TID_INT, TID_SHORT, EVENT_HEADER::time_stamp, EVENT_HEADER::trigger_mask, and TRUE.
Referenced by rpc_server_receive().
10659          : recv_event_server
10660
10661   Purpose: TCP event receive routine with local cache. To speed up
10662            network performance, a 64k buffer is read in at once and
10663            split into several RPC command on successive calls to
10664            recv_event_server. Therefore, the number of recv() calls
10665            is minimized.
10666
10667            This routine is ment to be called by the server process.
10668            Clients should call recv_tcp instead.
10669
10670   Input:
10671     INT   index              Index of server connection
10672     DWORD buffer_size        Size of the buffer in bytes.
10673     INT   flags              Flags passed to recv()
10674     INT   convert_flags      Convert flags needed for big/little
10675                              endian conversion
10676
10677   Output:
10678     char  *buffer            Network receive buffer.
10679     INT   *remaining         Remaining data in cache
10680
10681   Function value:
10682     INT                      Same as recv()
10683
10684 \********************************************************************/
10685 {
10686    INT size, event_size, aligned_event_size = 0, *pbh, header_size;
10687    EVENT_HEADER *pevent;
10688    INT write_ptr, read_ptr, misalign;
10689    char *net_buffer;
10690    INT copied, status;
10691    INT sock;
10692    RPC_SERVER_ACCEPTION *psa;
10693
10694    psa = &_server_acception[index];
10695    sock = psa->event_sock;
10696
10697    if (flags & MSG_PEEK) {
10698       status = recv(sock, buffer, buffer_size, flags);
10699       if (status == -1)
10700          cm_msg(MERROR, "recv_event_server",
10701                 "recv(%d,MSG_PEEK) returned %d, errno: %d (%s)", buffer_size, status,
10702                 errno, strerror(errno));
10703       return status;
10704    }
10705
10706    if (!psa->ev_net_buffer) {
10707       if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE)
10708          psa->net_buffer_size = NET_TCP_SIZE;
10709       else
10710          psa->net_buffer_size = NET_BUFFER_SIZE;
10711
10712       psa->ev_net_buffer = (char *) M_MALLOC(psa->net_buffer_size);
10713       psa->ev_write_ptr = 0;
10714       psa->ev_read_ptr = 0;
10715       psa->ev_misalign = 0;
10716    }
10717    if (!psa->ev_net_buffer) {
10718       cm_msg(MERROR, "recv_event_server", "not enough memory to allocate network buffer");
10719       return -1;
10720    }
10721
10722    header_size = (INT) (sizeof(EVENT_HEADER) + sizeof(INT));
10723
10724    if ((INT) buffer_size < header_size) {
10725       cm_msg(MERROR, "recv_event_server", "parameters too large for network buffer");
10726       return -1;
10727    }
10728
10729    copied = 0;
10730    event_size = -1;
10731
10732    write_ptr = psa->ev_write_ptr;
10733    read_ptr = psa->ev_read_ptr;
10734    misalign = psa->ev_misalign;
10735    net_buffer = psa->ev_net_buffer;
10736
10737    do {
10738       if (write_ptr - read_ptr >= header_size - copied) {
10739          if (event_size == -1) {
10740             if (copied > 0) {
10741                /* assemble split header */
10742                memcpy(buffer + copied, net_buffer + read_ptr, header_size - copied);
10743                pbh = (INT *) buffer;
10744             } else
10745                pbh = (INT *) (net_buffer + read_ptr);
10746
10747             pevent = (EVENT_HEADER *) (pbh + 1);
10748
10749             event_size = pevent->data_size;
10750             if (psa->convert_flags)
10751                rpc_convert_single(&event_size, TID_DWORD, 0, psa->convert_flags);
10752
10753             aligned_event_size = ALIGN8(event_size);
10754          }
10755
10756          /* check if data part fits in buffer */
10757          if ((INT) buffer_size < aligned_event_size + header_size) {
10758             cm_msg(MERROR, "recv_event_server",
10759                    "parameters too large for network buffer");
10760             psa->ev_read_ptr = psa->ev_write_ptr = 0;
10761             return -1;
10762          }
10763
10764          /* check if we have whole event in buffer */
10765          if (write_ptr - read_ptr >= aligned_event_size + header_size - copied)
10766             break;
10767       }
10768
10769       /* not enough data, so copy partially and get new */
10770       size = write_ptr - read_ptr;
10771
10772       if (size > 0) {
10773          memcpy(buffer + copied, net_buffer + read_ptr, size);
10774          copied += size;
10775          read_ptr = write_ptr;
10776       }
10777 #ifdef OS_UNIX
10778       do {
10779          write_ptr = recv(sock, net_buffer + misalign, psa->net_buffer_size - 8, flags);
10780
10781          /* don't return if an alarm signal was cought */
10782       } while (write_ptr == -1 && errno == EINTR);
10783 #else
10784       write_ptr = recv(sock, net_buffer + misalign, psa->net_buffer_size - 8, flags);
10785 #endif
10786
10787       /* abort if connection broken */
10788       if (write_ptr <= 0) {
10789          cm_msg(MERROR, "recv_event_server", "recv() returned %d, errno: %d (%s)",
10790                 write_ptr, errno, strerror(errno));
10791
10792          if (remaining)
10793             *remaining = 0;
10794
10795          return write_ptr;
10796       }
10797
10798       read_ptr = misalign;
10799       write_ptr += misalign;
10800
10801       misalign = write_ptr % 8;
10802    } while (TRUE);
10803
10804    /* copy rest of event */
10805    size = aligned_event_size + header_size - copied;
10806    if (size > 0) {
10807       memcpy(buffer + copied, net_buffer + read_ptr, size);
10808       read_ptr += size;
10809    }
10810
10811    if (remaining)
10812       *remaining = write_ptr - read_ptr;
10813
10814    psa->ev_write_ptr = write_ptr;
10815    psa->ev_read_ptr = read_ptr;
10816    psa->ev_misalign = misalign;
10817
10818    /* convert header little endian/big endian */
10819    if (psa->convert_flags) {
10820       pevent = (EVENT_HEADER *) (((INT *) buffer) + 1);
10821
10822       rpc_convert_single(buffer, TID_INT, 0, psa->convert_flags);
10823       rpc_convert_single(&pevent->event_id, TID_SHORT, 0, psa->convert_flags);
10824       rpc_convert_single(&pevent->trigger_mask, TID_SHORT, 0, psa->convert_flags);
10825       rpc_convert_single(&pevent->serial_number, TID_DWORD, 0, psa->convert_flags);
10826       rpc_convert_single(&pevent->time_stamp, TID_DWORD, 0, psa->convert_flags);
10827       rpc_convert_single(&pevent->data_size, TID_DWORD, 0, psa->convert_flags);
10828    }
10829
10830    return header_size + event_size;
10831 }
INT recv_tcp_check (int sock)
Definition at line 10624 of file midas.c.
References index, MAX_RPC_CONNECTION, RPC_SERVER_ACCEPTION::read_ptr, and RPC_SERVER_ACCEPTION::write_ptr.
Referenced by ss_suspend().
10627          : recv_tcp_check
10628
10629   Purpose: Check if in TCP receive buffer associated with sock is
10630            some data. Called by ss_suspend.
10631
10632   Input:
10633     INT   sock               TCP receive socket
10634
10635   Output:
10636     none
10637
10638   Function value:
10639     INT   count              Number of bytes remaining in TCP buffer
10640
10641 \********************************************************************/
10642 {
10643    INT index;
10644
10645    /* figure out to which connection socket belongs */
10646    for (index = 0; index < MAX_RPC_CONNECTION; index++)
10647       if (_server_acception[index].recv_sock == sock)
10648          break;
10649
10650    return _server_acception[index].write_ptr - _server_acception[index].read_ptr;
10651 }
INT recv_tcp_server (INT index, char * buffer, DWORD buffer_size, INT flags, INT * remaining)
Definition at line 10454 of file midas.c.
References cm_msg, NET_COMMAND::header, if, M_MALLOC, MERROR, RPC_SERVER_ACCEPTION::misalign, RPC_SERVER_ACCEPTION::net_buffer, net_buffer, NET_BUFFER_SIZE, RPC_SERVER_ACCEPTION::net_buffer_size, NET_TCP_SIZE, NET_COMMAND_HEADER::param_size, RPC_SERVER_ACCEPTION::read_ptr, RPC_SERVER_ACCEPTION::recv_sock, rpc_convert_single(), rpc_get_server_option(), RPC_OSERVER_TYPE, size, ST_REMOTE, status, TID_DWORD, TRUE, and RPC_SERVER_ACCEPTION::write_ptr.
Referenced by rpc_server_receive().
10458          : recv_tcp_server
10459
10460   Purpose: TCP receive routine with local cache. To speed up network
10461            performance, a 64k buffer is read in at once and split into
10462            several RPC command on successive calls to recv_tcp_server.
10463            Therefore, the number of recv() calls is minimized.
10464
10465            This routine is ment to be called by the server process.
10466            Clients should call recv_tcp instead.
10467
10468   Input:
10469     INT   index              Index of server connection
10470     DWORD buffer_size        Size of the buffer in bytes.
10471     INT   flags              Flags passed to recv()
10472     INT   convert_flags      Convert flags needed for big/little
10473                              endian conversion
10474
10475   Output:
10476     char  *buffer            Network receive buffer.
10477     INT   *remaining         Remaining data in cache
10478
10479   Function value:
10480     INT                      Same as recv()
10481
10482 \********************************************************************/
10483 {
10484    INT size, param_size;
10485    NET_COMMAND *nc;
10486    INT write_ptr, read_ptr, misalign;
10487    char *net_buffer;
10488    INT copied, status;
10489    INT sock;
10490
10491    sock = _server_acception[index].recv_sock;
10492
10493    if (flags & MSG_PEEK) {
10494       status = recv(sock, buffer, buffer_size, flags);
10495       if (status == -1)
10496          cm_msg(MERROR, "recv_tcp_server",
10497                 "recv(%d,MSG_PEEK) returned %d, errno: %d (%s)", buffer_size, status,
10498                 errno, strerror(errno));
10499       return status;
10500    }
10501
10502    if (!_server_acception[index].net_buffer) {
10503       if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE)
10504          _server_acception[index].net_buffer_size = NET_TCP_SIZE;
10505       else
10506          _server_acception[index].net_buffer_size = NET_BUFFER_SIZE;
10507
10508       _server_acception[index].net_buffer =
10509           (char *) M_MALLOC(_server_acception[index].net_buffer_size);
10510       _server_acception[index].write_ptr = 0;
10511       _server_acception[index].read_ptr = 0;
10512       _server_acception[index].misalign = 0;
10513    }
10514    if (!_server_acception[index].net_buffer) {
10515       cm_msg(MERROR, "recv_tcp_server", "not enough memory to allocate network buffer");
10516       return -1;
10517    }
10518
10519    if (buffer_size < sizeof(NET_COMMAND_HEADER)) {
10520       cm_msg(MERROR, "recv_tcp_server", "parameters too large for network buffer");
10521       return -1;
10522    }
10523
10524    copied = 0;
10525    param_size = -1;
10526
10527    write_ptr = _server_acception[index].write_ptr;
10528    read_ptr = _server_acception[index].read_ptr;
10529    misalign = _server_acception[index].misalign;
10530    net_buffer = _server_acception[index].net_buffer;
10531
10532    do {
10533       if (write_ptr - read_ptr >= (INT) sizeof(NET_COMMAND_HEADER) - copied) {
10534          if (param_size == -1) {
10535             if (copied > 0) {
10536                /* assemble split header */
10537                memcpy(buffer + copied, net_buffer + read_ptr,
10538                       (INT) sizeof(NET_COMMAND_HEADER) - copied);
10539                nc = (NET_COMMAND *) (buffer);
10540             } else
10541                nc = (NET_COMMAND *) (net_buffer + read_ptr);
10542
10543             param_size = (INT) nc->header.param_size;
10544
10545             if (_server_acception[index].convert_flags)
10546                rpc_convert_single(&param_size, TID_DWORD, 0,
10547                                   _server_acception[index].convert_flags);
10548          }
10549
10550          /* check if parameters fit in buffer */
10551          if (buffer_size < param_size + sizeof(NET_COMMAND_HEADER)) {
10552             cm_msg(MERROR, "recv_tcp_server", "parameters too large for network buffer");
10553             _server_acception[index].read_ptr = _server_acception[index].write_ptr = 0;
10554             return -1;
10555          }
10556
10557          /* check if we have all parameters in buffer */
10558          if (write_ptr - read_ptr >=
10559              param_size + (INT) sizeof(NET_COMMAND_HEADER) - copied)
10560             break;
10561       }
10562
10563       /* not enough data, so copy partially and get new */
10564       size = write_ptr - read_ptr;
10565
10566       if (size > 0) {
10567          memcpy(buffer + copied, net_buffer + read_ptr, size);
10568          copied += size;
10569          read_ptr = write_ptr;
10570       }
10571 #ifdef OS_UNIX
10572       do {
10573          write_ptr =
10574              recv(sock, net_buffer + misalign,
10575                   _server_acception[index].net_buffer_size - 8, flags);
10576
10577          /* don't return if an alarm signal was cought */
10578       } while (write_ptr == -1 && errno == EINTR);
10579 #else
10580       write_ptr =
10581           recv(sock, net_buffer + misalign, _server_acception[index].net_buffer_size - 8,
10582                flags);
10583 #endif
10584
10585       /* abort if connection broken */
10586       if (write_ptr <= 0) {
10587          cm_msg(MERROR, "recv_tcp_server", "recv() returned %d, errno: %d (%s)",
10588                 write_ptr, errno, strerror(errno));
10589
10590          if (remaining)
10591             *remaining = 0;
10592
10593          return write_ptr;
10594       }
10595
10596       read_ptr = misalign;
10597       write_ptr += misalign;
10598
10599       misalign = write_ptr % 8;
10600    } while (TRUE);
10601
10602    /* copy rest of parameters */
10603    size = param_size + sizeof(NET_COMMAND_HEADER) - copied;
10604    memcpy(buffer + copied, net_buffer + read_ptr, size);
10605    read_ptr += size;
10606
10607    if (remaining) {
10608       /* don't keep rpc_server_receive in an infinite loop */
10609       if (write_ptr - read_ptr < param_size)
10610          *remaining = 0;
10611       else
10612          *remaining = write_ptr - read_ptr;
10613    }
10614
10615    _server_acception[index].write_ptr = write_ptr;
10616    _server_acception[index].read_ptr = read_ptr;
10617    _server_acception[index].misalign = misalign;
10618
10619    return size + copied;
10620 }
void rpc_calc_convert_flags (INT hw_type, INT remote_hw_type, INT * convert_flags)
Definition at line 7974 of file midas.c.
References CF_ASCII, CF_ENDIAN, CF_IEEE2VAX, CF_VAX2IEEE, DR_ASCII, DRF_G_FLOAT, DRF_IEEE, DRI_BIG_ENDIAN, and DRI_LITTLE_ENDIAN.
Referenced by rpc_client_accept(), rpc_get_convert_flags(), and rpc_server_callback().
{
   *convert_flags = 0;
   /* big/little endian conversion */
   if (((remote_hw_type & DRI_BIG_ENDIAN) &&
        (hw_type & DRI_LITTLE_ENDIAN)) ||
       ((remote_hw_type & DRI_LITTLE_ENDIAN) && (hw_type & DRI_BIG_ENDIAN)))
      *convert_flags |= CF_ENDIAN;
   /* float conversion between IEEE and VAX G */
   if ((remote_hw_type & DRF_G_FLOAT) && (hw_type & DRF_IEEE))
      *convert_flags |= CF_VAX2IEEE;
   /* float conversion between VAX G and IEEE */
   if ((remote_hw_type & DRF_IEEE) && (hw_type & DRF_G_FLOAT))
      *convert_flags |= CF_IEEE2VAX;
   /* ASCII format */
   if (remote_hw_type & DR_ASCII)
      *convert_flags |= CF_ASCII;
}
INT rpc_call (const INT routine_id, ...)
Definition at line 9810 of file midas.c.
References _net_send_buffer, _net_send_buffer_size, ALIGN8, cm_msg, DRI_BIG_ENDIAN, FD_SETSIZE, RPC_PARAM::flags, NET_COMMAND::header, i, index, M_MALLOC, MERROR, RPC_PARAM::n, name, NET_BUFFER_SIZE, param, RPC_LIST::param, NET_COMMAND::param, NET_COMMAND_HEADER::param_size, PTYPE, recv_tcp(), NET_COMMAND_HEADER::routine_id, RPC_EXCEED_BUFFER, RPC_FIXARRAY, RPC_FTCP, rpc_get_option(), RPC_IN, RPC_INVALID_ID, RPC_NET_ERROR, RPC_OHW_TYPE, RPC_OUT, RPC_POINTER, rpc_server_disconnect(), RPC_SUCCESS, RPC_TIMEOUT, RPC_SERVER_CONNECTION::rpc_timeout, rpc_va_arg(), RPC_VARARRAY, RPC_SERVER_CONNECTION::send_sock, send_tcp(), status, TCP_FAST, RPC_PARAM::tid, TID_ARRAY, TID_BYTE, TID_CHAR, TID_DOUBLE, TID_FLOAT, TID_LINK, TID_SBYTE, TID_SHORT, tid_size, TID_STRING, TID_STRUCT, TID_WORD, RPC_SERVER_CONNECTION::transport, and WATCHDOG_INTERVAL.
Referenced by al_check(), al_trigger_alarm(), bm_add_event_request(), bm_close_all_buffers(), bm_close_buffer(), bm_empty_buffers(), bm_flush_cache(), bm_get_buffer_info(), bm_get_buffer_level(), bm_init_buffer_counters(), bm_mark_read_waiting(), bm_open_buffer(), bm_receive_event(), bm_remove_event_request(), bm_send_event(), bm_set_cache_size(), bm_skip_event(), cm_asctime(), cm_cleanup(), cm_execute(), cm_exist(), cm_get_watchdog_info(), cm_msg_log(), cm_msg_log1(), cm_msg_retrieve(), cm_set_client_info(), cm_set_watchdog_params(), cm_synchronize(), cm_time(), db_add_open_record(), db_check_record(), db_close_all_databases(), db_close_database(), db_create_key(), db_create_link(), db_create_record(), db_delete_key(), db_enum_key(), db_enum_link(), db_find_key(), db_find_key1(), db_find_link(), db_find_link1(), db_flush_database(), db_get_data(), db_get_data1(), db_get_data_index(), db_get_key(), db_get_key_info(), db_get_key_time(), db_get_next_link(), db_get_open_records(), db_get_path(), db_get_record(), db_get_record_size(), db_get_value(), db_load(), db_open_database(), db_remove_open_record(), db_rename_key(), db_reorder_key(), db_save(), db_set_client_name(), db_set_data(), db_set_data_index(), db_set_data_index2(), db_set_mode(), db_set_num_values(), db_set_record(), db_set_value(), el_submit(), hs_count_events(), hs_count_vars(), hs_enum_events(), hs_enum_vars(), hs_get_event_id(), hs_get_var(), hs_read(), hs_set_path(), main(), and rpc_server_disconnect().
         : rpc_call
  Purpose: Call a function on a MIDAS server
  Input:
    INT  routine_id         routine ID as defined in RPC.H (RPC_xxx)
    ...                     variable argument list
  Output:
    (depends on argument list)
  Function value:
    RPC_SUCCESS             Successful completion
    RPC_NET_ERROR           Error in socket call
    RPC_NO_CONNECTION       No active connection
    RPC_TIMEOUT             Timeout in RPC call
    RPC_INVALID_ID          Invalid routine_id (not in rpc_list)
    RPC_EXCEED_BUFFER       Paramters don't fit in network buffer
\********************************************************************/
{
   va_list ap, aptmp;
   char arg[8], arg_tmp[8];
   INT arg_type, transport, rpc_timeout;
   INT i, index, status;
   INT param_size, arg_size, send_size;
   INT tid, flags;
   fd_set readfds;
   struct timeval timeout;
   char *param_ptr, str[80];
   BOOL bpointer, bbig;
   NET_COMMAND *nc;
   int send_sock;
   send_sock = _server_connection.send_sock;
   transport = _server_connection.transport;
   rpc_timeout = _server_connection.rpc_timeout;
   /* init network buffer */
   if (_net_send_buffer_size == 0) {
      _net_send_buffer = (char *) M_MALLOC(NET_BUFFER_SIZE);
      if (_net_send_buffer == NULL) {
         cm_msg(MERROR, "rpc_call", "not enough memory to allocate network buffer");
         return RPC_EXCEED_BUFFER;
      }
      _net_send_buffer_size = NET_BUFFER_SIZE;
   }
   nc = (NET_COMMAND *) _net_send_buffer;
   nc->header.routine_id = routine_id;
   if (transport == RPC_FTCP)
      nc->header.routine_id |= TCP_FAST;
   for (i = 0;; i++)
      if (rpc_list[i].id == routine_id || rpc_list[i].id == 0)
         break;
   index = i;
   if (rpc_list[i].id == 0) {
      sprintf(str, "invalid rpc ID (%d)", routine_id);
      cm_msg(MERROR, "rpc_call", str);
      return RPC_INVALID_ID;
   }
   /* examine variable argument list and convert it to parameter array */
   va_start(ap, routine_id);
   /* find out if we are on a big endian system */
   bbig = ((rpc_get_option(0, RPC_OHW_TYPE) & DRI_BIG_ENDIAN) > 0);
   for (i = 0, param_ptr = nc->param; rpc_list[index].param[i].tid != 0; i++) {
      tid = rpc_list[index].param[i].tid;
      flags = rpc_list[index].param[i].flags;
      bpointer = (flags & RPC_POINTER) || (flags & RPC_OUT) ||
          (flags & RPC_FIXARRAY) || (flags & RPC_VARARRAY) ||
          tid == TID_STRING || tid == TID_ARRAY || tid == TID_STRUCT || tid == TID_LINK;
      if (bpointer)
         arg_type = TID_ARRAY;
      else
         arg_type = tid;
      /* floats are passed as doubles, at least under NT */
      if (tid == TID_FLOAT && !bpointer)
         arg_type = TID_DOUBLE;
      /* get pointer to argument */
      rpc_va_arg(&ap, arg_type, arg);
      /* shift 1- and 2-byte parameters to the LSB on big endian systems */
      if (bbig) {
         if (tid == TID_BYTE || tid == TID_CHAR || tid == TID_SBYTE) {
            arg[0] = arg[3];
         }
         if (tid == TID_WORD || tid == TID_SHORT) {
            arg[0] = arg[2];
            arg[1] = arg[3];
         }
      }
      if (flags & RPC_IN) {
         if (bpointer)
            arg_size = tid_size[tid];
         else
            arg_size = tid_size[arg_type];
         /* for strings, the argument size depends on the string length */
         if (tid == TID_STRING || tid == TID_LINK)
            arg_size = 1 + strlen((char *) *((char **) arg));
         /* for varibale length arrays, the size is given by
            the next parameter on the stack */
         if (flags & RPC_VARARRAY) {
            memcpy(&aptmp, &ap, sizeof(ap));
            rpc_va_arg(&aptmp, TID_ARRAY, arg_tmp);
            if (flags & RPC_OUT)
               arg_size = *((INT *) * ((void **) arg_tmp));
            else
               arg_size = *((INT *) arg_tmp);
            *((INT *) param_ptr) = ALIGN8(arg_size);
            param_ptr += ALIGN8(sizeof(INT));
         }
         if (tid == TID_STRUCT || (flags & RPC_FIXARRAY))
            arg_size = rpc_list[index].param[i].n;
         /* always align parameter size */
         param_size = ALIGN8(arg_size);
         if ((PTYPE) param_ptr - (PTYPE) nc + param_size > NET_BUFFER_SIZE) {
            cm_msg(MERROR, "rpc_call",
                   "parameters (%d) too large for network buffer (%d)",
                   (PTYPE) param_ptr - (PTYPE) nc + param_size, NET_BUFFER_SIZE);
            return RPC_EXCEED_BUFFER;
         }
         if (bpointer)
            memcpy(param_ptr, (void *) *((void **) arg), arg_size);
         else {
            /* floats are passed as doubles on most systems */
            if (tid != TID_FLOAT)
               memcpy(param_ptr, arg, arg_size);
            else
               *((float *) param_ptr) = (float) *((double *) arg);
         }
         param_ptr += param_size;
      }
   }
   va_end(ap);
   nc->header.param_size = (PTYPE) param_ptr - (PTYPE) nc->param;
   send_size = nc->header.param_size + sizeof(NET_COMMAND_HEADER);
   /* in FAST TCP mode, only send call and return immediately */
   if (transport == RPC_FTCP) {
      i = send_tcp(send_sock, (char *) nc, send_size, 0);
      if (i != send_size) {
         cm_msg(MERROR, "rpc_call", "send_tcp() failed");
         return RPC_NET_ERROR;
      }
      return RPC_SUCCESS;
   }
   /* in TCP mode, send and wait for reply on send socket */
   i = send_tcp(send_sock, (char *) nc, send_size, 0);
   if (i != send_size) {
      cm_msg(MERROR, "rpc_call", "send_tcp() failed");
      return RPC_NET_ERROR;
   }
   /* make some timeout checking */
   if (rpc_timeout > 0) {
      FD_ZERO(&readfds);
      FD_SET(send_sock, &readfds);
      timeout.tv_sec = rpc_timeout / 1000;
      timeout.tv_usec = (rpc_timeout % 1000) * 1000;
10000
10001       do {
10002          status = select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
10003
10004          /* if an alarm signal was cought, restart select with reduced timeout */
10005          if (status == -1 && timeout.tv_sec >= WATCHDOG_INTERVAL / 1000)
10006             timeout.tv_sec -= WATCHDOG_INTERVAL / 1000;
10007
10008       } while (status == -1);   /* dont return if an alarm signal was cought */
10009
10010       if (!FD_ISSET(send_sock, &readfds)) {
10011          cm_msg(MERROR, "rpc_call", "rpc timeout, routine = \"%s\"",
10012                 rpc_list[index].name);
10013
10014          /* disconnect to avoid that the reply to this rpc_call comes at
10015             the next rpc_call */
10016          rpc_server_disconnect();
10017
10018          return RPC_TIMEOUT;
10019       }
10020    }
10021
10022    /* receive result on send socket */
10023    i = recv_tcp(send_sock, _net_send_buffer, NET_BUFFER_SIZE, 0);
10024
10025    if (i <= 0) {
10026       cm_msg(MERROR, "rpc_call", "recv_tcp() failed, routine = \"%s\"",
10027              rpc_list[index].name);
10028       return RPC_NET_ERROR;
10029    }
10030
10031    /* extract result variables and place it to argument list */
10032    status = nc->header.routine_id;
10033
10034    va_start(ap, routine_id);
10035
10036    for (i = 0, param_ptr = nc->param; rpc_list[index].param[i].tid != 0; i++) {
10037       tid = rpc_list[index].param[i].tid;
10038       flags = rpc_list[index].param[i].flags;
10039
10040       bpointer = (flags & RPC_POINTER) || (flags & RPC_OUT) ||
10041           (flags & RPC_FIXARRAY) || (flags & RPC_VARARRAY) ||
10042           tid == TID_STRING || tid == TID_ARRAY || tid == TID_STRUCT || tid == TID_LINK;
10043
10044       if (bpointer)
10045          arg_type = TID_ARRAY;
10046       else
10047          arg_type = rpc_list[index].param[i].tid;
10048
10049       if (tid == TID_FLOAT && !bpointer)
10050          arg_type = TID_DOUBLE;
10051
10052       rpc_va_arg(&ap, arg_type, arg);
10053
10054       if (rpc_list[index].param[i].flags & RPC_OUT) {
10055          tid = rpc_list[index].param[i].tid;
10056          arg_size = tid_size[tid];
10057
10058          if (tid == TID_STRING || tid == TID_LINK)
10059             arg_size = strlen((char *) (param_ptr)) + 1;
10060
10061          if (flags & RPC_VARARRAY) {
10062             arg_size = *((INT *) param_ptr);
10063             param_ptr += ALIGN8(sizeof(INT));
10064          }
10065
10066          if (tid == TID_STRUCT || (flags & RPC_FIXARRAY))
10067             arg_size = rpc_list[index].param[i].n;
10068
10069          /* return parameters are always pointers */
10070          if (*((char **) arg))
10071             memcpy((void *) *((char **) arg), param_ptr, arg_size);
10072
10073          /* parameter size is always aligned */
10074          param_size = ALIGN8(arg_size);
10075
10076          param_ptr += param_size;
10077       }
10078    }
10079
10080    va_end(ap);
10081
10082    return status;
10083 }
INT rpc_check_channels (void)
Definition at line 12486 of file midas.c.
References closesocket, cm_disconnect_experiment(), cm_msg, FD_SETSIZE, NET_COMMAND::header, i, index, M_FREE, MAX_RPC_CONNECTION, MINFO, MSG_WATCHDOG, RPC_SERVER_ACCEPTION::net_buffer, net_buffer, NET_COMMAND_HEADER::param_size, recv_tcp(), NET_COMMAND_HEADER::routine_id, RPC_CONVERT_FLAGS, rpc_convert_single(), rpc_get_server_option(), RPC_NET_ERROR, RPC_OSERVER_TYPE, RPC_OUTGOING, RPC_SUCCESS, send_tcp(), ss_gettid(), ss_millitime(), ST_REMOTE, status, TID_DWORD, WATCHDOG_INTERVAL, and RPC_SERVER_ACCEPTION::watchdog_timeout.
Referenced by rpc_server_thread().
12489          : rpc_check_channels
12490
12491   Purpose: Check open rpc channels by sending watchdog messages
12492
12493   Input:
12494     none
12495
12496   Output:
12497     none
12498
12499   Function value:
12500     RPC_SUCCESS             Channel is still alive
12501     RPC_NET_ERROR           Connection is broken
12502
12503 \********************************************************************/
12504 {
12505    INT status, index, i, convert_flags;
12506    NET_COMMAND nc;
12507    fd_set readfds;
12508    struct timeval timeout;
12509
12510    for (index = 0; index < MAX_RPC_CONNECTION; index++) {
12511       if (_server_acception[index].recv_sock &&
12512           _server_acception[index].tid == ss_gettid() &&
12513           _server_acception[index].watchdog_timeout &&
12514           (ss_millitime() - _server_acception[index].last_activity >
12515            (DWORD) _server_acception[index].watchdog_timeout)) {
12516 /* printf("Send watchdog message to %s on %s\n",
12517                 _server_acception[index].prog_name,
12518                 _server_acception[index].host_name); */
12519
12520          /* send a watchdog message */
12521          nc.header.routine_id = MSG_WATCHDOG;
12522          nc.header.param_size = 0;
12523
12524          convert_flags = rpc_get_server_option(RPC_CONVERT_FLAGS);
12525          if (convert_flags) {
12526             rpc_convert_single(&nc.header.routine_id, TID_DWORD, RPC_OUTGOING,
12527                                convert_flags);
12528             rpc_convert_single(&nc.header.param_size, TID_DWORD, RPC_OUTGOING,
12529                                convert_flags);
12530          }
12531
12532          /* send the header to the client */
12533          i = send_tcp(_server_acception[index].send_sock,
12534                       (char *) &nc, sizeof(NET_COMMAND_HEADER), 0);
12535
12536          if (i < 0)
12537             goto exit;
12538
12539          /* make some timeout checking */
12540          FD_ZERO(&readfds);
12541          FD_SET(_server_acception[index].send_sock, &readfds);
12542          FD_SET(_server_acception[index].recv_sock, &readfds);
12543
12544          timeout.tv_sec = _server_acception[index].watchdog_timeout / 1000;
12545          timeout.tv_usec = (_server_acception[index].watchdog_timeout % 1000) * 1000;
12546
12547          do {
12548             status = select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
12549
12550             /* if an alarm signal was cought, restart select with reduced timeout */
12551             if (status == -1 && timeout.tv_sec >= WATCHDOG_INTERVAL / 1000)
12552                timeout.tv_sec -= WATCHDOG_INTERVAL / 1000;
12553
12554          } while (status == -1);        /* dont return if an alarm signal was cought */
12555
12556          if (!FD_ISSET(_server_acception[index].send_sock, &readfds) &&
12557              !FD_ISSET(_server_acception[index].recv_sock, &readfds))
12558             goto exit;
12559
12560          /* receive result on send socket */
12561          if (FD_ISSET(_server_acception[index].send_sock, &readfds)) {
12562             i = recv_tcp(_server_acception[index].send_sock, (char *) &nc, sizeof(nc), 0);
12563             if (i <= 0)
12564                goto exit;
12565          }
12566       }
12567    }
12568
12569    return RPC_SUCCESS;
12570
12571  exit:
12572
12573    cm_msg(MINFO, "rpc_check_channels", "client [%s]%s failed watchdog test after %d sec",
12574           _server_acception[index].host_name,
12575           _server_acception[index].prog_name,
12576           _server_acception[index].watchdog_timeout / 1000);
12577
12578    /* disconnect from experiment */
12579    if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE)
12580       cm_disconnect_experiment();
12581
12582    /* close server connection */
12583    if (_server_acception[index].recv_sock)
12584       closesocket(_server_acception[index].recv_sock);
12585    if (_server_acception[index].send_sock)
12586       closesocket(_server_acception[index].send_sock);
12587    if (_server_acception[index].event_sock)
12588       closesocket(_server_acception[index].event_sock);
12589
12590    /* free TCP cache */
12591    M_FREE(_server_acception[index].net_buffer);
12592    _server_acception[index].net_buffer = NULL;
12593
12594    /* mark this entry as invalid */
12595    memset(&_server_acception[index], 0, sizeof(RPC_SERVER_ACCEPTION));
12596
12597    return RPC_NET_ERROR;
12598 }
INT rpc_client_accept (int lsock)
Definition at line 11860 of file midas.c.
References CH_SERVER, closesocket, cm_get_version(), RPC_SERVER_ACCEPTION::event_sock, HOST_NAME_LENGTH, i, index, RPC_SERVER_ACCEPTION::last_activity, MAX_RPC_CONNECTION, NAME_LENGTH, net_buffer, p, RPC_SERVER_ACCEPTION::recv_sock, recv_string(), RPC_SERVER_ACCEPTION::remote_hw_type, rpc_calc_convert_flags(), RPC_CONVERT_FLAGS, rpc_get_option(), RPC_NET_ERROR, RPC_OHW_TYPE, rpc_server_receive(), rpc_set_server_acception(), rpc_set_server_option(), RPC_SUCCESS, send(), RPC_SERVER_ACCEPTION::send_sock, size, ss_gettid(), ss_millitime(), ss_suspend_set_dispatch(), status, RPC_SERVER_ACCEPTION::tid, and RPC_SERVER_ACCEPTION::watchdog_timeout.
Referenced by rpc_register_server().
11863          : rpc_client_accept
11864
11865   Purpose: Accept new incoming connections as a client
11866
11867   Input:
11868     INT    lsock            Listen socket
11869
11870   Output:
11871     none
11872
11873   Function value:
11874     RPC_SUCCESS             Successful completion
11875     RPC_NET_ERROR           Error in socket call
11876     RPC_CONNCLOSED          Connection was closed
11877     RPC_SHUTDOWN            Listener shutdown
11878     RPC_EXCEED_BUFFER       Not enough memory for network buffer
11879
11880 \********************************************************************/
11881 {
11882    INT index, i, version, status;
11883    int size, sock;
11884    struct sockaddr_in acc_addr;
11885    INT client_hw_type = 0, hw_type;
11886    char str[100], client_program[NAME_LENGTH];
11887    char host_name[HOST_NAME_LENGTH];
11888    INT convert_flags;
11889    char net_buffer[256], *p;
11890
11891    size = sizeof(acc_addr);
11892    sock = accept(lsock, (struct sockaddr *) &acc_addr, (int *) &size);
11893
11894    if (sock == -1)
11895       return RPC_NET_ERROR;
11896
11897    /* get the name of the calling host */
11898 /* outcommented for speed reasons SR 7.10.98
11899 #ifdef OS_VXWORKS
11900   {
11901   status = hostGetByAddr(acc_addr.sin_addr.s_addr, host_name);
11902   if (status != 0)
11903     strcpy(host_name, "unknown");
11904   }
11905 #else
11906   phe = gethostbyaddr((char *) &acc_addr.sin_addr, 4, PF_INET);
11907   if (phe == NULL)
11908     strcpy(host_name, "unknown");
11909   strcpy(host_name, phe->h_name);
11910 #endif
11911 */
11912    strcpy(host_name, "");
11913
11914    /* look for next free entry */
11915    for (index = 0; index < MAX_RPC_CONNECTION; index++)
11916       if (_server_acception[index].recv_sock == 0)
11917          break;
11918    if (index == MAX_RPC_CONNECTION) {
11919       closesocket(sock);
11920       return RPC_NET_ERROR;
11921    }
11922
11923    /* receive string with timeout */
11924    i = recv_string(sock, net_buffer, sizeof(net_buffer), 10000);
11925    if (i <= 0) {
11926       closesocket(sock);
11927       return RPC_NET_ERROR;
11928    }
11929
11930    /* get remote computer info */
11931    p = strtok(net_buffer, " ");
11932    if (p != NULL) {
11933       client_hw_type = atoi(p);
11934       p = strtok(NULL, " ");
11935    }
11936    if (p != NULL) {
11937       version = atoi(p);
11938       p = strtok(NULL, " ");
11939    }
11940    if (p != NULL) {
11941       strcpy(client_program, p);
11942       p = strtok(NULL, " ");
11943    }
11944    if (p != NULL) {
11945       strcpy(host_name, p);
11946       p = strtok(NULL, " ");
11947    }
11948
11949    /* save information in _server_acception structure */
11950    _server_acception[index].recv_sock = sock;
11951    _server_acception[index].send_sock = 0;
11952    _server_acception[index].event_sock = 0;
11953    _server_acception[index].remote_hw_type = client_hw_type;
11954    strcpy(_server_acception[index].host_name, host_name);
11955    strcpy(_server_acception[index].prog_name, client_program);
11956    _server_acception[index].tid = ss_gettid();
11957    _server_acception[index].last_activity = ss_millitime();
11958    _server_acception[index].watchdog_timeout = 0;
11959
11960    /* send my own computer id */
11961    hw_type = rpc_get_option(0, RPC_OHW_TYPE);
11962    sprintf(str, "%d %s", hw_type, cm_get_version());
11963    status = send(sock, str, strlen(str) + 1, 0);
11964    if (status != (INT) strlen(str) + 1)
11965       return RPC_NET_ERROR;
11966
11967    rpc_set_server_acception(index + 1);
11968    rpc_calc_convert_flags(hw_type, client_hw_type, &convert_flags);
11969    rpc_set_server_option(RPC_CONVERT_FLAGS, convert_flags);
11970
11971    /* set callback function for ss_suspend */
11972    ss_suspend_set_dispatch(CH_SERVER, _server_acception,
11973                            (int (*)(void)) rpc_server_receive);
11974
11975    return RPC_SUCCESS;
11976 }
INT rpc_client_call (HNDLE hConn, const INT routine_id, ...)
Definition at line 9519 of file midas.c.
References _net_send_buffer, _net_send_buffer_size, ALIGN8, cm_msg, DRI_BIG_ENDIAN, FALSE, FD_SETSIZE, RPC_PARAM::flags, NET_COMMAND::header, i, index, M_MALLOC, MERROR, RPC_PARAM::n, name, NET_BUFFER_SIZE, param, RPC_LIST::param, NET_COMMAND::param, NET_COMMAND_HEADER::param_size, PTYPE, recv_tcp(), NET_COMMAND_HEADER::routine_id, rpc_client_disconnect(), RPC_EXCEED_BUFFER, RPC_FIXARRAY, RPC_FTCP, rpc_get_option(), RPC_IN, RPC_INVALID_ID, RPC_NET_ERROR, RPC_NO_CONNECTION, RPC_OHW_TYPE, RPC_OUT, RPC_POINTER, RPC_SUCCESS, RPC_TIMEOUT, RPC_CLIENT_CONNECTION::rpc_timeout, rpc_va_arg(), RPC_VARARRAY, RPC_CLIENT_CONNECTION::send_sock, send_tcp(), status, TCP_FAST, RPC_PARAM::tid, TID_ARRAY, TID_BYTE, TID_CHAR, TID_DOUBLE, TID_FLOAT, TID_LINK, TID_SBYTE, TID_SHORT, tid_size, TID_STRING, TID_STRUCT, TID_WORD, RPC_CLIENT_CONNECTION::transport, and WATCHDOG_INTERVAL.
Referenced by cam16i_q(), cam16i_r(), cam16i_rq(), cam16i_sa(), cam16i_sn(), cam16o_q(), cam16o_r(), cam24i(), cam24i_q(), cam24i_r(), cam24i_rq(), cam24i_sa(), cam24i_sn(), cam24o(), cam24o_q(), cam24o_r(), cam_crate_clear(), cam_crate_zinit(), cam_inhibit_clear(), cam_inhibit_set(), cam_init_rpc(), camc(), camc_q(), cami(), camo(), cm_transition(), command_loop(), interprete(), main(), rpc_client_disconnect(), rpc_master_read(), rpc_slave_stop_block(), send_ready_for_cycle(), and show_cnaf_page().
         : rpc_client_call
  Purpose: Call a function on a MIDAS client
  Input:
    INT  hConn              Client connection
    INT  routine_id         routine ID as defined in RPC.H (RPC_xxx)
    ...                     variable argument list
  Output:
    (depends on argument list)
  Function value:
    RPC_SUCCESS             Successful completion
    RPC_NET_ERROR           Error in socket call
    RPC_NO_CONNECTION       No active connection
    RPC_TIMEOUT             Timeout in RPC call
    RPC_INVALID_ID          Invalid routine_id (not in rpc_list)
    RPC_EXCEED_BUFFER       Paramters don't fit in network buffer
\********************************************************************/
{
   va_list ap, aptmp;
   char arg[8], arg_tmp[8];
   INT arg_type, transport, rpc_timeout;
   INT i, index, status, rpc_index;
   INT param_size, arg_size, send_size;
   INT tid, flags;
   fd_set readfds;
   struct timeval timeout;
   char *param_ptr, str[80];
   BOOL bpointer, bbig;
   NET_COMMAND *nc;
   int send_sock;
   index = hConn - 1;
   if (_client_connection[index].send_sock == 0) {
      cm_msg(MERROR, "rpc_client_call", "no rpc connection");
      return RPC_NO_CONNECTION;
   }
   send_sock = _client_connection[index].send_sock;
   rpc_timeout = _client_connection[index].rpc_timeout;
   transport = _client_connection[index].transport;
   /* init network buffer */
   if (_net_send_buffer_size == 0) {
      _net_send_buffer = (char *) M_MALLOC(NET_BUFFER_SIZE);
      if (_net_send_buffer == NULL) {
         cm_msg(MERROR, "rpc_client_call",
                "not enough memory to allocate network buffer");
         return RPC_EXCEED_BUFFER;
      }
      _net_send_buffer_size = NET_BUFFER_SIZE;
   }
   nc = (NET_COMMAND *) _net_send_buffer;
   nc->header.routine_id = routine_id;
   if (transport == RPC_FTCP)
      nc->header.routine_id |= TCP_FAST;
   for (i = 0;; i++)
      if (rpc_list[i].id == routine_id || rpc_list[i].id == 0)
         break;
   rpc_index = i;
   if (rpc_list[i].id == 0) {
      sprintf(str, "invalid rpc ID (%d)", routine_id);
      cm_msg(MERROR, "rpc_client_call", str);
      return RPC_INVALID_ID;
   }
   /* examine variable argument list and convert it to parameter array */
   va_start(ap, routine_id);
   /* find out if we are on a big endian system */
   bbig = ((rpc_get_option(0, RPC_OHW_TYPE) & DRI_BIG_ENDIAN) > 0);
   for (i = 0, param_ptr = nc->param; rpc_list[rpc_index].param[i].tid != 0; i++) {
      tid = rpc_list[rpc_index].param[i].tid;
      flags = rpc_list[rpc_index].param[i].flags;
      bpointer = (flags & RPC_POINTER) || (flags & RPC_OUT) ||
          (flags & RPC_FIXARRAY) || (flags & RPC_VARARRAY) ||
          tid == TID_STRING || tid == TID_ARRAY || tid == TID_STRUCT || tid == TID_LINK;
      if (bpointer)
         arg_type = TID_ARRAY;
      else
         arg_type = tid;
      /* floats are passed as doubles, at least under NT */
      if (tid == TID_FLOAT && !bpointer)
         arg_type = TID_DOUBLE;
      /* get pointer to argument */
      rpc_va_arg(&ap, arg_type, arg);
      /* shift 1- and 2-byte parameters to the LSB on big endian systems */
      if (bbig) {
         if (tid == TID_BYTE || tid == TID_CHAR || tid == TID_SBYTE) {
            arg[0] = arg[3];
         }
         if (tid == TID_WORD || tid == TID_SHORT) {
            arg[0] = arg[2];
            arg[1] = arg[3];
         }
      }
      if (flags & RPC_IN) {
         if (bpointer)
            arg_size = tid_size[tid];
         else
            arg_size = tid_size[arg_type];
         /* for strings, the argument size depends on the string length */
         if (tid == TID_STRING || tid == TID_LINK)
            arg_size = 1 + strlen((char *) *((char **) arg));
         /* for varibale length arrays, the size is given by
            the next parameter on the stack */
         if (flags & RPC_VARARRAY) {
            memcpy(&aptmp, &ap, sizeof(ap));
            rpc_va_arg(&aptmp, TID_ARRAY, arg_tmp);
            if (flags & RPC_OUT)
               arg_size = *((INT *) * ((void **) arg_tmp));
            else
               arg_size = *((INT *) arg_tmp);
            *((INT *) param_ptr) = ALIGN8(arg_size);
            param_ptr += ALIGN8(sizeof(INT));
         }
         if (tid == TID_STRUCT || (flags & RPC_FIXARRAY))
            arg_size = rpc_list[rpc_index].param[i].n;
         /* always align parameter size */
         param_size = ALIGN8(arg_size);
         if ((PTYPE) param_ptr - (PTYPE) nc + param_size > NET_BUFFER_SIZE) {
            cm_msg(MERROR, "rpc_client_call",
                   "parameters (%d) too large for network buffer (%d)",
                   (PTYPE) param_ptr - (PTYPE) nc + param_size, NET_BUFFER_SIZE);
            return RPC_EXCEED_BUFFER;
         }
         if (bpointer)
            memcpy(param_ptr, (void *) *((void **) arg), arg_size);
         else {
            /* floats are passed as doubles on most systems */
            if (tid != TID_FLOAT)
               memcpy(param_ptr, arg, arg_size);
            else
               *((float *) param_ptr) = (float) *((double *) arg);
         }
         param_ptr += param_size;
      }
   }
   va_end(ap);
   nc->header.param_size = (PTYPE) param_ptr - (PTYPE) nc->param;
   send_size = nc->header.param_size + sizeof(NET_COMMAND_HEADER);
   /* in FAST TCP mode, only send call and return immediately */
   if (transport == RPC_FTCP) {
      i = send_tcp(send_sock, (char *) nc, send_size, 0);
      if (i != send_size) {
         cm_msg(MERROR, "rpc_client_call", "send_tcp() failed");
         return RPC_NET_ERROR;
      }
      return RPC_SUCCESS;
   }
   /* in TCP mode, send and wait for reply on send socket */
   i = send_tcp(send_sock, (char *) nc, send_size, 0);
   if (i != send_size) {
      cm_msg(MERROR, "rpc_client_call",
             "send_tcp() failed, routine = \"%s\", host = \"%s\"",
             rpc_list[rpc_index].name, _client_connection[index].host_name);
      return RPC_NET_ERROR;
   }
   /* make some timeout checking */
   if (rpc_timeout > 0) {
      FD_ZERO(&readfds);
      FD_SET(send_sock, &readfds);
      timeout.tv_sec = rpc_timeout / 1000;
      timeout.tv_usec = (rpc_timeout % 1000) * 1000;
      do {
         status = select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
         /* if an alarm signal was cought, restart select with reduced timeout */
         if (status == -1 && timeout.tv_sec >= WATCHDOG_INTERVAL / 1000)
            timeout.tv_sec -= WATCHDOG_INTERVAL / 1000;
      } while (status == -1);   /* dont return if an alarm signal was cought */
      if (!FD_ISSET(send_sock, &readfds)) {
         cm_msg(MERROR, "rpc_client_call", "rpc timeout, routine = \"%s\", host = \"%s\"",
                rpc_list[rpc_index].name, _client_connection[index].host_name);
         /* disconnect to avoid that the reply to this rpc_call comes at
            the next rpc_call */
         rpc_client_disconnect(hConn, FALSE);
         return RPC_TIMEOUT;
      }
   }
   /* receive result on send socket */
   i = recv_tcp(send_sock, _net_send_buffer, NET_BUFFER_SIZE, 0);
   if (i <= 0) {
      cm_msg(MERROR, "rpc_client_call",
             "recv_tcp() failed, routine = \"%s\", host = \"%s\"",
             rpc_list[rpc_index].name, _client_connection[index].host_name);
      return RPC_NET_ERROR;
   }
   /* extract result variables and place it to argument list */
   status = nc->header.routine_id;
   va_start(ap, routine_id);
   for (i = 0, param_ptr = nc->param; rpc_list[rpc_index].param[i].tid != 0; i++) {
      tid = rpc_list[rpc_index].param[i].tid;
      flags = rpc_list[rpc_index].param[i].flags;
      bpointer = (flags & RPC_POINTER) || (flags & RPC_OUT) ||
          (flags & RPC_FIXARRAY) || (flags & RPC_VARARRAY) ||
          tid == TID_STRING || tid == TID_ARRAY || tid == TID_STRUCT || tid == TID_LINK;
      if (bpointer)
         arg_type = TID_ARRAY;
      else
         arg_type = rpc_list[rpc_index].param[i].tid;
      if (tid == TID_FLOAT && !bpointer)
         arg_type = TID_DOUBLE;
      rpc_va_arg(&ap, arg_type, arg);
      if (rpc_list[rpc_index].param[i].flags & RPC_OUT) {
         tid = rpc_list[rpc_index].param[i].tid;
         flags = rpc_list[rpc_index].param[i].flags;
         arg_size = tid_size[tid];
         if (tid == TID_STRING || tid == TID_LINK)
            arg_size = strlen((char *) (param_ptr)) + 1;
         if (flags & RPC_VARARRAY) {
            arg_size = *((INT *) param_ptr);
            param_ptr += ALIGN8(sizeof(INT));
         }
         if (tid == TID_STRUCT || (flags & RPC_FIXARRAY))
            arg_size = rpc_list[rpc_index].param[i].n;
         /* return parameters are always pointers */
         if (*((char **) arg))
            memcpy((void *) *((char **) arg), param_ptr, arg_size);
         /* parameter size is always aligned */
         param_size = ALIGN8(arg_size);
         param_ptr += param_size;
      }
   }
   va_end(ap);
   return status;
}
void rpc_client_check ()
Definition at line 8597 of file midas.c.
References buffer, closesocket, cm_msg, equal_ustring(), FD_SETSIZE, i, MAX_RPC_CONNECTION, MERROR, RPC_CLIENT_CONNECTION::send_sock, and status.
Referenced by cmd_idle(), and rpc_client_connect().
         : rpc_client_check
  Purpose: Check all client connections if remote client closed link
  Function value:
    RPC_SUCCESS              Successful completion
    RPC_NET_ERROR            Error in socket call
    RPC_NO_CONNECTION        Maximum number of connections reached
    RPC_NOT_REGISTERED       cm_connect_experiment was not called properly
\********************************************************************/
{
   INT i, status;
   /* check for broken connections */
   for (i = 0; i < MAX_RPC_CONNECTION; i++)
      if (_client_connection[i].send_sock != 0) {
         int sock;
         fd_set readfds;
         struct timeval timeout;
         char buffer[64];
         sock = _client_connection[i].send_sock;
         FD_ZERO(&readfds);
         FD_SET(sock, &readfds);
         timeout.tv_sec = 0;
         timeout.tv_usec = 0;
         do {
            status = select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
         } while (status == -1);        /* dont return if an alarm signal was cought */
         if (FD_ISSET(sock, &readfds)) {
            status = recv(sock, (char *) buffer, sizeof(buffer), 0);
            if (equal_ustring(buffer, "EXIT")) {
               /* normal exit */
               closesocket(sock);
               memset(&_client_connection[i], 0, sizeof(RPC_CLIENT_CONNECTION));
            }
            if (status <= 0) {
               cm_msg(MERROR, "rpc_client_check",
                      "Connection broken to \"%s\" on host %s",
                      _client_connection[i].client_name, _client_connection[i].host_name);
               /* connection broken -> reset */
               closesocket(sock);
               memset(&_client_connection[i], 0, sizeof(RPC_CLIENT_CONNECTION));
            }
         }
      }
}
INT rpc_client_connect (char * host_name, INT port, char * client_name, HNDLE * hConnection)
Definition at line 8416 of file midas.c.
References cm_get_version(), cm_msg, DEFAULT_RPC_TIMEOUT, RPC_CLIENT_CONNECTION::exp_name, HOST_NAME_LENGTH, i, index, MAX_RPC_CONNECTION, MERROR, NAME_LENGTH, RPC_CLIENT_CONNECTION::port, recv_string(), RPC_CLIENT_CONNECTION::remote_hw_type, rpc_client_check(), rpc_get_name(), rpc_get_option(), RPC_NET_ERROR, RPC_NO_CONNECTION, RPC_NOT_REGISTERED, RPC_OHW_TYPE, RPC_SUCCESS, RPC_TCP, RPC_CLIENT_CONNECTION::rpc_timeout, send(), RPC_CLIENT_CONNECTION::send_sock, status, and RPC_CLIENT_CONNECTION::transport.
Referenced by cam_init_rpc(), cm_connect_client(), cm_shutdown(), cm_transition(), and main().
         : rpc_client_connect
  Purpose: Establish a network connection to a remote client
  Input:
    char *host_name          IP address of host to connect to.
    INT  port                TPC port to connect to.
    char *clinet_name        Client program name
  Output:
    HNDLE *hConnection       Handle for new connection which can be used
                             in future rpc_call(hConnection....) calls
  Function value:
    RPC_SUCCESS              Successful completion
    RPC_NET_ERROR            Error in socket call
    RPC_NO_CONNECTION        Maximum number of connections reached
    RPC_NOT_REGISTERED       cm_connect_experiment was not called properly
\********************************************************************/
{
   INT i, status, index;
   struct sockaddr_in bind_addr;
   INT sock;
   INT remote_hw_type, hw_type;
   char str[200];
   char version[32], v1[32];
   char local_prog_name[NAME_LENGTH];
   char local_host_name[HOST_NAME_LENGTH];
   struct hostent *phe;
#ifdef OS_WINNT
   {
      WSADATA WSAData;
      /* Start windows sockets */
      if (WSAStartup(MAKEWORD(1, 1), &WSAData) != 0)
         return RPC_NET_ERROR;
   }
#endif
   /* check if cm_connect_experiment was called */
   if (_client_name[0] == 0) {
      cm_msg(MERROR, "rpc_client_connect",
             "cm_connect_experiment/rpc_set_name not called");
      return RPC_NOT_REGISTERED;
   }
   /* check for broken connections */
   rpc_client_check();
   /* check if connection already exists */
   for (i = 0; i < MAX_RPC_CONNECTION; i++)
      if (_client_connection[i].send_sock != 0 &&
          strcmp(_client_connection[i].host_name, host_name) == 0 &&
          _client_connection[i].port == port) {
         *hConnection = i + 1;
         return RPC_SUCCESS;
      }
   /* search for free entry */
   for (i = 0; i < MAX_RPC_CONNECTION; i++)
      if (_client_connection[i].send_sock == 0)
         break;
   /* open new network connection */
   if (i == MAX_RPC_CONNECTION) {
      cm_msg(MERROR, "rpc_client_connect", "maximum number of connections exceeded");
      return RPC_NO_CONNECTION;
   }
   /* create a new socket for connecting to remote server */
   sock = socket(AF_INET, SOCK_STREAM, 0);
   if (sock == -1) {
      cm_msg(MERROR, "rpc_client_connect", "cannot create socket");
      return RPC_NET_ERROR;
   }
   index = i;
   strcpy(_client_connection[index].host_name, host_name);
   strcpy(_client_connection[index].client_name, client_name);
   _client_connection[index].port = port;
   _client_connection[index].exp_name[0] = 0;
   _client_connection[index].transport = RPC_TCP;
   _client_connection[index].rpc_timeout = DEFAULT_RPC_TIMEOUT;
   _client_connection[index].rpc_timeout = DEFAULT_RPC_TIMEOUT;
   /* connect to remote node */
   memset(&bind_addr, 0, sizeof(bind_addr));
   bind_addr.sin_family = AF_INET;
   bind_addr.sin_addr.s_addr = 0;
   bind_addr.sin_port = htons((short) port);
#ifdef OS_VXWORKS
   {
      INT host_addr;
      host_addr = hostGetByName(host_name);
      memcpy((char *) &(bind_addr.sin_addr), &host_addr, 4);
   }
#else
   phe = gethostbyname(host_name);
   if (phe == NULL) {
      cm_msg(MERROR, "rpc_client_connect", "cannot get host name");
      return RPC_NET_ERROR;
   }
   memcpy((char *) &(bind_addr.sin_addr), phe->h_addr, phe->h_length);
#endif
#ifdef OS_UNIX
   do {
      status = connect(sock, (void *) &bind_addr, sizeof(bind_addr));
      /* don't return if an alarm signal was cought */
   } while (status == -1 && errno == EINTR);
#else
   status = connect(sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
#endif
   if (status != 0) {
      /* cm_msg(MERROR, "rpc_client_connect", "cannot connect");
         message should be displayed by application */
      return RPC_NET_ERROR;
   }
   /* set TCP_NODELAY option for better performance */
#ifdef OS_VXWORKS
   i = 1;
   setsockopt(sock, IPPROTO_TCP, TCP_NODELAY, (char *) &i, sizeof(i));
#endif
   /* send local computer info */
   rpc_get_name(local_prog_name);
   gethostname(local_host_name, sizeof(local_host_name));
   hw_type = rpc_get_option(0, RPC_OHW_TYPE);
   sprintf(str, "%d %s %s %s", hw_type, cm_get_version(), local_prog_name,
           local_host_name);
   send(sock, str, strlen(str) + 1, 0);
   /* receive remote computer info */
   i = recv_string(sock, str, sizeof(str), 10000);
   if (i <= 0) {
      cm_msg(MERROR, "rpc_client_connect", "timeout on receive remote computer info: %s",
             str);
      return RPC_NET_ERROR;
   }
   remote_hw_type = version[0] = 0;
   sscanf(str, "%d %s", &remote_hw_type, version);
   _client_connection[index].remote_hw_type = remote_hw_type;
   _client_connection[index].send_sock = sock;
   /* print warning if version patch level doesn't agree */
   strcpy(v1, version);
   if (strchr(v1, '.'))
      if (strchr(strchr(v1, '.') + 1, '.'))
         *strchr(strchr(v1, '.') + 1, '.') = 0;
   strcpy(str, cm_get_version());
   if (strchr(str, '.'))
      if (strchr(strchr(str, '.') + 1, '.'))
         *strchr(strchr(str, '.') + 1, '.') = 0;
   if (strcmp(v1, str) != 0) {
      sprintf(str, "remote MIDAS version %s differs from local version %s",
              version, cm_get_version());
      cm_msg(MERROR, "rpc_client_connect", str);
   }
   *hConnection = index + 1;
   return RPC_SUCCESS;
}
INT rpc_client_disconnect (HNDLE hConn, BOOL bShutdown)
Definition at line 8923 of file midas.c.
References closesocket, FALSE, i, MAX_RPC_CONNECTION, rpc_client_call(), rpc_client_disconnect(), RPC_FTCP, RPC_ID_EXIT, RPC_ID_SHUTDOWN, RPC_OTRANSPORT, rpc_set_option(), RPC_SUCCESS, and send().
Referenced by cam_exit(), cm_disconnect_client(), cm_disconnect_experiment(), cm_shutdown(), main(), rpc_client_call(), and rpc_client_disconnect().
         : rpc_client_disconnect
  Purpose: Close a rpc connection to a MIDAS client
  Input:
    HNDLE  hConn           Handle of connection
    BOOL   bShutdown       Shut down remote server if TRUE
  Output:
    none
  Function value:
   RPC_SUCCESS             Successful completion
\********************************************************************/
{
   INT i;
   if (hConn == -1) {
      /* close all open connections */
      for (i = MAX_RPC_CONNECTION - 1; i >= 0; i--)
         if (_client_connection[i].send_sock != 0)
            rpc_client_disconnect(i + 1, FALSE);
      /* close server connection from other clients */
      for (i = 0; i < MAX_RPC_CONNECTION; i++)
         if (_server_acception[i].recv_sock) {
            send(_server_acception[i].recv_sock, "EXIT", 5, 0);
            closesocket(_server_acception[i].recv_sock);
         }
   } else {
      /* notify server about exit */
      /* set FTCP mode (helps for rebooted VxWorks nodes) */
      rpc_set_option(hConn, RPC_OTRANSPORT, RPC_FTCP);
      rpc_client_call(hConn, bShutdown ? RPC_ID_SHUTDOWN : RPC_ID_EXIT);
      /* close socket */
      if (_client_connection[hConn - 1].send_sock)
         closesocket(_client_connection[hConn - 1].send_sock);
      memset(&_client_connection[hConn - 1], 0, sizeof(RPC_CLIENT_CONNECTION));
   }
   return RPC_SUCCESS;
}
INT rpc_client_dispatch (int sock)
Definition at line 8336 of file midas.c.
References bm_poll_event(), db_update_record(), FALSE, FD_SETSIZE, hDB, NET_COMMAND::header, hKey, MSG_BM, MSG_ODB, MSG_WATCHDOG, n, net_buffer, NET_COMMAND::param, NET_COMMAND_HEADER::param_size, recv_tcp(), NET_COMMAND_HEADER::routine_id, RPC_SUCCESS, send_tcp(), SS_ABORT, and status.
Referenced by rpc_server_connect().
         : rpc_client_dispatch
  Purpose: Gets called whenever a client receives data from the
           server. Get set via rpc_connect. Internal use only.
\********************************************************************/
{
   INT hDB, hKey, n;
   NET_COMMAND *nc;
   INT status = 0;
   char net_buffer[256];
   nc = (NET_COMMAND *) net_buffer;
   n = recv_tcp(sock, net_buffer, sizeof(net_buffer), 0);
   if (n <= 0)
      return SS_ABORT;
   if (nc->header.routine_id == MSG_ODB) {
      /* update a changed record */
      hDB = *((INT *) nc->param);
      hKey = *((INT *) nc->param + 1);
      status = db_update_record(hDB, hKey, 0);
   }
   else if (nc->header.routine_id == MSG_WATCHDOG) {
      nc->header.routine_id = 1;
      nc->header.param_size = 0;
      send_tcp(sock, net_buffer, sizeof(NET_COMMAND_HEADER), 0);
      status = RPC_SUCCESS;
   }
   else if (nc->header.routine_id == MSG_BM) {
      fd_set readfds;
      struct timeval timeout;
      /* receive further messages to empty TCP queue */
      do {
         FD_ZERO(&readfds);
         FD_SET(sock, &readfds);
         timeout.tv_sec = 0;
         timeout.tv_usec = 0;
         select(FD_SETSIZE, &readfds, NULL, NULL, &timeout);
         if (FD_ISSET(sock, &readfds)) {
            n = recv_tcp(sock, net_buffer, sizeof(net_buffer), 0);
            if (n <= 0)
               return SS_ABORT;
            if (nc->header.routine_id == MSG_ODB) {
               /* update a changed record */
               hDB = *((INT *) nc->param);
               hKey = *((INT *) nc->param + 1);
               status = db_update_record(hDB, hKey, 0);
            }
            else if (nc->header.routine_id == MSG_WATCHDOG) {
               nc->header.routine_id = 1;
               nc->header.param_size = 0;
               send_tcp(sock, net_buffer, sizeof(NET_COMMAND_HEADER), 0);
               status = RPC_SUCCESS;
            }
         }
      } while (FD_ISSET(sock, &readfds));
      /* poll event from server */
      status = bm_poll_event(FALSE);
   }
   return status;
}
void rpc_convert_data (void * data, INT tid, INT flags, INT total_size, INT convert_flags)
Definition at line 8108 of file midas.c.
References i, n, p, rpc_convert_single(), RPC_FIXARRAY, RPC_VARARRAY, and tid_size.
Referenced by db_get_record(), db_recurse_record_tree(), db_set_record(), rpc_execute(), and rpc_server_dispatch().
         : rpc_convert_data
  Purpose: Convert data format between differenct computers
  Input:
    void   *data            Pointer to data
    INT    tid              Type ID of data, one of TID_xxx
    INT    flags            Combination of following flags:
                              RPC_IN: data is input parameter
                              RPC_OUT: data is output variable
                              RPC_FIXARRAY, RPC_VARARRAY: data is array
                                of "size" bytes (see next param.)
                              RPC_OUTGOING: data is outgoing
    INT    total_size       Size of bytes of data. Used for variable
                            length arrays.
    INT    convert_flags    Flags for data conversion
  Output:
    void   *data            Is converted according to _convert_flag
                            value
  Function value:
    RPC_SUCCESS             Successful completion
\********************************************************************/
{
   INT i, n, single_size;
   char *p;
   /* convert array */
   if (flags & (RPC_FIXARRAY | RPC_VARARRAY)) {
      single_size = tid_size[tid];
      /* don't convert TID_ARRAY & TID_STRUCT */
      if (single_size == 0)
         return;
      n = total_size / single_size;
      for (i = 0; i < n; i++) {
         p = (char *) data + (i * single_size);
         rpc_convert_single(p, tid, flags, convert_flags);
      }
   } else {
      rpc_convert_single(data, tid, flags, convert_flags);
   }
}
void rpc_convert_single (void * data, INT tid, INT flags, INT convert_flags)
Definition at line 8079 of file midas.c.
References CF_ENDIAN, CF_IEEE2VAX, CF_VAX2IEEE, DWORD_SWAP, QWORD_SWAP, rpc_ieee2vax_double(), rpc_ieee2vax_float(), RPC_OUTGOING, rpc_vax2ieee_double(), rpc_vax2ieee_float(), TID_BOOL, TID_DOUBLE, TID_DWORD, TID_FLOAT, TID_INT, TID_SHORT, TID_WORD, and WORD_SWAP.
Referenced by bm_notify_client(), bm_receive_event(), db_get_record(), db_recurse_record_tree(), db_set_record(), db_update_record(), main(), recv_event_server(), recv_tcp_server(), rpc_check_channels(), rpc_convert_data(), rpc_execute(), and rpc_server_dispatch().
{
   if (convert_flags & CF_ENDIAN) {
      if (tid == TID_WORD || tid == TID_SHORT)
         WORD_SWAP(data);
      if (tid == TID_DWORD || tid == TID_INT || tid == TID_BOOL || tid == TID_FLOAT)
         DWORD_SWAP(data);
      if (tid == TID_DOUBLE)
         QWORD_SWAP(data);
   }
   if (((convert_flags & CF_IEEE2VAX) && !(flags & RPC_OUTGOING)) ||
       ((convert_flags & CF_VAX2IEEE) && (flags & RPC_OUTGOING))) {
      if (tid == TID_FLOAT)
         rpc_ieee2vax_float((float *) data);
      if (tid == TID_DOUBLE)
         rpc_ieee2vax_double((double *) data);
   }
   if (((convert_flags & CF_IEEE2VAX) && (flags & RPC_OUTGOING)) ||
       ((convert_flags & CF_VAX2IEEE) && !(flags & RPC_OUTGOING))) {
      if (tid == TID_FLOAT)
         rpc_vax2ieee_float((float *) data);
      if (tid == TID_DOUBLE)
         rpc_vax2ieee_double((double *) data);
   }
}
void rpc_debug_printf (char * format, ...)
Definition at line 9447 of file midas.c.
References _debug_mode, and _debug_print.
Referenced by main(), rpc_execute(), rpc_execute_ascii(), rpc_server_accept(), rpc_server_callback(), and rpc_server_receive().
         : rpc_debug_print
  Purpose: Calls function set via rpc_set_debug to output a string.
  Input:
   char *str                Debug string
  Output:
    none
\********************************************************************/
{
   va_list argptr;
   char str[1000];
   if (_debug_mode) {
      va_start(argptr, format);
      vsprintf(str, (char *) format, argptr);
      va_end(argptr);
      if (_debug_print) {
         strcat(str, "\n");
         _debug_print(str);
      } else
         puts(str);
   }
}
INT rpc_deregister_functions (void)
dox
Definition at line 8273 of file midas.c.
References M_FREE, and RPC_SUCCESS.
Referenced by cm_disconnect_experiment(), and rpc_server_receive().
         : rpc_deregister_functions
  Purpose: Free memory of previously registered functions
  Input:
    none
  Output:
    none
  Function value:
    RPC_SUCCESS              Successful completion
\********************************************************************/
{
   if (rpc_list)
      M_FREE(rpc_list);
   rpc_list = NULL;
   return RPC_SUCCESS;
}
INT rpc_execute (INT sock, char * buffer, INT convert_flags)
Definition at line 10990 of file midas.c.
References _debug_print, ALIGN8, cm_msg, db_sprintf(), RPC_LIST::dispatch, RPC_PARAM::flags, NET_COMMAND::header, i, index, MERROR, n, NET_BUFFER_SIZE, param, RPC_LIST::param, NET_COMMAND::param, NET_COMMAND_HEADER::param_size, PTYPE, return_buffer, NET_COMMAND_HEADER::routine_id, rpc_convert_data(), rpc_convert_single(), rpc_debug_printf(), RPC_EXCEED_BUFFER, RPC_ID_EXIT, RPC_ID_SHUTDOWN, RPC_ID_WATCHDOG, RPC_IN, RPC_INVALID_ID, RPC_NET_ERROR, RPC_OUT, RPC_OUTGOING, RPC_SHUTDOWN, RPC_SUCCESS, RPC_VARARRAY, send_tcp(), SS_ABORT, SS_EXIT, status, TCP_FAST, RPC_PARAM::tid, TID_DWORD, TID_INT, TID_LINK, tid_size, TID_STRING, and TID_STRUCT.
Referenced by rpc_server_receive().
10993          : rpc_execute
10994
10995   Purpose: Execute a RPC command received over the network
10996
10997   Input:
10998     INT  sock               TCP socket to which the result should be
10999                             send back
11000
11001     char *buffer            Command buffer
11002     INT  convert_flags      Flags for data conversion
11003
11004   Output:
11005     none
11006
11007   Function value:
11008     RPC_SUCCESS             Successful completion
11009     RPC_INVALID_ID          Invalid routine_id received
11010     RPC_NET_ERROR           Error in socket call
11011     RPC_EXCEED_BUFFER       Not enough memory for network buffer
11012     RPC_SHUTDOWN            Shutdown requested
11013     SS_ABORT                TCP connection broken
11014     SS_EXIT                 TCP connection closed
11015
11016 \********************************************************************/
11017 {
11018    INT i, index, routine_id, status;
11019    char *in_param_ptr, *out_param_ptr, *last_param_ptr;
11020    INT tid, flags;
11021    NET_COMMAND *nc_in, *nc_out;
11022    INT param_size, max_size;
11023    void *prpc_param[20];
11024    char str[1024], debug_line[1024];
11025
11026 /* return buffer must be auto for multi-thread servers */
11027    char return_buffer[NET_BUFFER_SIZE];
11028
11029
11030    /* extract pointer array to parameters */
11031    nc_in = (NET_COMMAND *) buffer;
11032    nc_out = (NET_COMMAND *) return_buffer;
11033
11034    /* convert header format (byte swapping) */
11035    if (convert_flags) {
11036       rpc_convert_single(&nc_in->header.routine_id, TID_DWORD, 0, convert_flags);
11037       rpc_convert_single(&nc_in->header.param_size, TID_DWORD, 0, convert_flags);
11038    }
11039
11040    /* no result return in FAST TCP mode */
11041    if (nc_in->header.routine_id & TCP_FAST)
11042       sock = 0;
11043
11044    /* find entry in rpc_list */
11045    routine_id = nc_in->header.routine_id & ~TCP_FAST;
11046
11047    for (i = 0;; i++)
11048       if (rpc_list[i].id == 0 || rpc_list[i].id == routine_id)
11049          break;
11050    index = i;
11051    if (rpc_list[i].id == 0) {
11052       cm_msg(MERROR, "rpc_execute", "Invalid rpc ID (%d)", routine_id);
11053       return RPC_INVALID_ID;
11054    }
11055
11056    in_param_ptr = nc_in->param;
11057    out_param_ptr = nc_out->param;
11058
11059    sprintf(debug_line, "%s(", rpc_list[index].name);
11060
11061    for (i = 0; rpc_list[index].param[i].tid != 0; i++) {
11062       tid = rpc_list[index].param[i].tid;
11063       flags = rpc_list[index].param[i].flags;
11064
11065       if (flags & RPC_IN) {
11066          param_size = ALIGN8(tid_size[tid]);
11067
11068          if (tid == TID_STRING || tid == TID_LINK)
11069             param_size = ALIGN8(1 + strlen((char *) (in_param_ptr)));
11070
11071          if (flags & RPC_VARARRAY) {
11072             /* for arrays, the size is stored as a INT in front of the array */
11073             param_size = *((INT *) in_param_ptr);
11074             if (convert_flags)
11075                rpc_convert_single(&param_size, TID_INT, 0, convert_flags);
11076             param_size = ALIGN8(param_size);
11077
11078             in_param_ptr += ALIGN8(sizeof(INT));
11079          }
11080
11081          if (tid == TID_STRUCT)
11082             param_size = ALIGN8(rpc_list[index].param[i].n);
11083
11084          prpc_param[i] = in_param_ptr;
11085
11086          /* convert data format */
11087          if (convert_flags) {
11088             if (flags & RPC_VARARRAY)
11089                rpc_convert_data(in_param_ptr, tid, flags, param_size, convert_flags);
11090             else
11091                rpc_convert_data(in_param_ptr, tid, flags,
11092                                 rpc_list[index].param[i].n * tid_size[tid],
11093                                 convert_flags);
11094          }
11095
11096          db_sprintf(str, in_param_ptr, param_size, 0, rpc_list[index].param[i].tid);
11097          if (rpc_list[index].param[i].tid == TID_STRING) {
11098             /* check for long strings (db_create_record...) */
11099             if (strlen(debug_line) + strlen(str) + 2 < sizeof(debug_line)) {
11100                strcat(debug_line, "\"");
11101                strcat(debug_line, str);
11102                strcat(debug_line, "\"");
11103             } else
11104                strcat(debug_line, "...");
11105          } else
11106             strcat(debug_line, str);
11107
11108          in_param_ptr += param_size;
11109       }
11110
11111       if (flags & RPC_OUT) {
11112          param_size = ALIGN8(tid_size[tid]);
11113
11114          if (flags & RPC_VARARRAY || tid == TID_STRING) {
11115             /* save maximum array length */
11116             max_size = *((INT *) in_param_ptr);
11117             if (convert_flags)
11118                rpc_convert_single(&max_size, TID_INT, 0, convert_flags);
11119             max_size = ALIGN8(max_size);
11120
11121             *((INT *) out_param_ptr) = max_size;
11122
11123             /* save space for return array length */
11124             out_param_ptr += ALIGN8(sizeof(INT));
11125
11126             /* use maximum array length from input */
11127             param_size += max_size;
11128          }
11129
11130          if (rpc_list[index].param[i].tid == TID_STRUCT)
11131             param_size = ALIGN8(rpc_list[index].param[i].n);
11132
11133          if ((PTYPE) out_param_ptr - (PTYPE) nc_out + param_size > NET_BUFFER_SIZE) {
11134             cm_msg(MERROR, "rpc_execute",
11135                    "return parameters (%d) too large for network buffer (%d)",
11136                    (PTYPE) out_param_ptr - (PTYPE) nc_out + param_size, NET_BUFFER_SIZE);
11137             return RPC_EXCEED_BUFFER;
11138          }
11139
11140          /* if parameter goes both directions, copy input to output */
11141          if (rpc_list[index].param[i].flags & RPC_IN)
11142             memcpy(out_param_ptr, prpc_param[i], param_size);
11143
11144          if (_debug_print && !(flags & RPC_IN))
11145             strcat(debug_line, "-");
11146
11147          prpc_param[i] = out_param_ptr;
11148          out_param_ptr += param_size;
11149       }
11150
11151       if (rpc_list[index].param[i + 1].tid)
11152          strcat(debug_line, ", ");
11153    }
11154
11155    strcat(debug_line, ")");
11156    rpc_debug_printf(debug_line);
11157
11158    last_param_ptr = out_param_ptr;
11159
11160   /*********************************\
11161   *   call dispatch function        *
11162   \*********************************/
11163    if (rpc_list[index].dispatch)
11164       status = rpc_list[index].dispatch(routine_id, prpc_param);
11165    else
11166       status = RPC_INVALID_ID;
11167
11168    if (routine_id == RPC_ID_EXIT || routine_id == RPC_ID_SHUTDOWN ||
11169        routine_id == RPC_ID_WATCHDOG)
11170       status = RPC_SUCCESS;
11171
11172    /* return immediately for closed down client connections */
11173    if (!sock && routine_id == RPC_ID_EXIT)
11174       return SS_EXIT;
11175
11176    if (!sock && routine_id == RPC_ID_SHUTDOWN)
11177       return RPC_SHUTDOWN;
11178
11179    /* Return if TCP connection broken */
11180    if (status == SS_ABORT)
11181       return SS_ABORT;
11182
11183    /* if sock == 0, we are in FTCP mode and may not sent results */
11184    if (!sock)
11185       return RPC_SUCCESS;
11186
11187    /* compress variable length arrays */
11188    out_param_ptr = nc_out->param;
11189    for (i = 0; rpc_list[index].param[i].tid != 0; i++)
11190       if (rpc_list[index].param[i].flags & RPC_OUT) {
11191          tid = rpc_list[index].param[i].tid;
11192          flags = rpc_list[index].param[i].flags;
11193          param_size = ALIGN8(tid_size[tid]);
11194
11195          if (tid == TID_STRING) {
11196             max_size = *((INT *) out_param_ptr);
11197             param_size = strlen((char *) prpc_param[i]) + 1;
11198             param_size = ALIGN8(param_size);
11199
11200             /* move string ALIGN8(sizeof(INT)) left */
11201             memcpy(out_param_ptr, out_param_ptr + ALIGN8(sizeof(INT)), param_size);
11202
11203             /* move remaining parameters to end of string */
11204             memcpy(out_param_ptr + param_size,
11205                    out_param_ptr + max_size + ALIGN8(sizeof(INT)),
11206                    (PTYPE) last_param_ptr -
11207                    ((PTYPE) out_param_ptr + max_size + ALIGN8(sizeof(INT))));
11208          }
11209
11210          if (flags & RPC_VARARRAY) {
11211             /* store array length at current out_param_ptr */
11212             max_size = *((INT *) out_param_ptr);
11213             param_size = *((INT *) prpc_param[i + 1]);
11214             *((INT *) out_param_ptr) = param_size;
11215             if (convert_flags)
11216                rpc_convert_single(out_param_ptr, TID_INT, RPC_OUTGOING, convert_flags);
11217
11218             out_param_ptr += ALIGN8(sizeof(INT));
11219
11220             param_size = ALIGN8(param_size);
11221
11222             /* move remaining parameters to end of array */
11223             memcpy(out_param_ptr + param_size,
11224                    out_param_ptr + max_size + ALIGN8(sizeof(INT)),
11225                    (PTYPE) last_param_ptr -
11226                    ((PTYPE) out_param_ptr + max_size + ALIGN8(sizeof(INT))));
11227          }
11228
11229          if (tid == TID_STRUCT)
11230             param_size = ALIGN8(rpc_list[index].param[i].n);
11231
11232          /* convert data format */
11233          if (convert_flags) {
11234             if (flags & RPC_VARARRAY)
11235                rpc_convert_data(out_param_ptr, tid,
11236                                 rpc_list[index].param[i].flags | RPC_OUTGOING,
11237                                 param_size, convert_flags);
11238             else
11239                rpc_convert_data(out_param_ptr, tid,
11240                                 rpc_list[index].param[i].flags | RPC_OUTGOING,
11241                                 rpc_list[index].param[i].n * tid_size[tid],
11242                                 convert_flags);
11243          }
11244
11245          out_param_ptr += param_size;
11246       }
11247
11248    /* send return parameters */
11249    param_size = (PTYPE) out_param_ptr - (PTYPE) nc_out->param;
11250    nc_out->header.routine_id = status;
11251    nc_out->header.param_size = param_size;
11252
11253    /* convert header format (byte swapping) if necessary */
11254    if (convert_flags) {
11255       rpc_convert_single(&nc_out->header.routine_id, TID_DWORD,
11256                          RPC_OUTGOING, convert_flags);
11257       rpc_convert_single(&nc_out->header.param_size, TID_DWORD,
11258                          RPC_OUTGOING, convert_flags);
11259    }
11260
11261    status = send_tcp(sock, return_buffer, sizeof(NET_COMMAND_HEADER) + param_size, 0);
11262
11263    if (status < 0) {
11264       cm_msg(MERROR, "rpc_execute", "send_tcp() failed");
11265       return RPC_NET_ERROR;
11266    }
11267
11268    /* print return buffer */
11269 /*
11270   printf("Return buffer, ID %d:\n", routine_id);
11271   for (i=0; i<param_size ; i++)
11272     {
11273     status = (char) nc_out->param[i];
11274     printf("%02X ", status);
11275     if (i%8 == 7)
11276       printf("\n");
11277     }
11278 */
11279    /* return SS_EXIT if RPC_EXIT is called */
11280    if (routine_id == RPC_ID_EXIT)
11281       return SS_EXIT;
11282
11283    /* return SS_SHUTDOWN if RPC_SHUTDOWN is called */
11284    if (routine_id == RPC_ID_SHUTDOWN)
11285       return RPC_SHUTDOWN;
11286
11287    return RPC_SUCCESS;
11288 }
INT rpc_execute_ascii (INT sock, char * buffer)
Definition at line 11292 of file midas.c.
References ALIGN8, ASCII_BUFFER_SIZE, cm_msg, db_sprintf(), db_sscanf(), RPC_LIST::dispatch, RPC_PARAM::flags, i, RPC_LIST::id, index, j, MERROR, N_APARAM, NAME_LENGTH, param, RPC_LIST::param, PTYPE, return_buffer, RPC_BM_RECEIVE_EVENT, RPC_DB_GET_DATA1, RPC_DB_GET_DATA_INDEX, rpc_debug_printf(), RPC_EXCEED_BUFFER, RPC_HS_READ, RPC_ID_EXIT, RPC_ID_SHUTDOWN, RPC_ID_WATCHDOG, RPC_IN, RPC_INVALID_ID, RPC_NET_ERROR, RPC_OUT, RPC_SHUTDOWN, RPC_SUCCESS, RPC_VARARRAY, send_tcp(), SS_ABORT, SS_EXIT, status, RPC_PARAM::tid, TID_DWORD, TID_LINK, tid_size, and TID_STRING.
Referenced by rpc_server_receive().
11295          : rpc_execute_ascii
11296
11297   Purpose: Execute a RPC command received over the network in ASCII
11298            mode
11299
11300   Input:
11301     INT  sock               TCP socket to which the result should be
11302                             send back
11303
11304     char *buffer            Command buffer
11305
11306   Output:
11307     none
11308
11309   Function value:
11310     RPC_SUCCESS             Successful completion
11311     RPC_INVALID_ID          Invalid routine_id received
11312     RPC_NET_ERROR           Error in socket call
11313     RPC_EXCEED_BUFFER       Not enough memory for network buffer
11314     RPC_SHUTDOWN            Shutdown requested
11315     SS_ABORT                TCP connection broken
11316     SS_EXIT                 TCP connection closed
11317
11318 \********************************************************************/
11319 {
11320 #define ASCII_BUFFER_SIZE 64500
11321 #define N_APARAM           1024
11322
11323    INT i, j, index, status, index_in;
11324    char *in_param_ptr, *out_param_ptr, *last_param_ptr;
11325    INT routine_id, tid, flags, array_tid, n_param;
11326    INT param_size, item_size, num_values;
11327    void *prpc_param[20];
11328    char *arpc_param[N_APARAM], *pc;
11329    char str[1024], debug_line[1024];
11330    char buffer1[ASCII_BUFFER_SIZE];     /* binary in */
11331    char buffer2[ASCII_BUFFER_SIZE];     /* binary out */
11332    char return_buffer[ASCII_BUFFER_SIZE];       /* ASCII out */
11333
11334    /* parse arguments */
11335    arpc_param[0] = buffer;
11336    for (i = 1; i < N_APARAM; i++) {
11337       arpc_param[i] = strchr(arpc_param[i - 1], '&');
11338       if (arpc_param[i] == NULL)
11339          break;
11340       *arpc_param[i] = 0;
11341       arpc_param[i]++;
11342    }
11343
11344    /* decode '%' */
11345    for (i = 0; i < N_APARAM && arpc_param[i]; i++)
11346       while ((pc = strchr(arpc_param[i], '%')) != NULL) {
11347          if (isxdigit(pc[1]) && isxdigit(pc[2])) {
11348             str[0] = pc[1];
11349             str[1] = pc[2];
11350             str[2] = 0;
11351             sscanf(str, "%02X", &i);
11352
11353             *pc++ = i;
11354             while (pc[2]) {
11355                pc[0] = pc[2];
11356                pc++;
11357             }
11358          }
11359       }
11360
11361    /* find entry in rpc_list */
11362    for (i = 0;; i++)
11363       if (rpc_list[i].id == 0 || strcmp(arpc_param[0], rpc_list[i].name) == 0)
11364          break;
11365    index = i;
11366    routine_id = rpc_list[i].id;
11367    if (rpc_list[i].id == 0) {
11368       cm_msg(MERROR, "rpc_execute", "Invalid rpc name (%s)", arpc_param[0]);
11369       return RPC_INVALID_ID;
11370    }
11371
11372    in_param_ptr = buffer1;
11373    out_param_ptr = buffer2;
11374    index_in = 1;
11375
11376    sprintf(debug_line, "%s(", rpc_list[index].name);
11377
11378    for (i = 0; rpc_list[index].param[i].tid != 0; i++) {
11379       tid = rpc_list[index].param[i].tid;
11380       flags = rpc_list[index].param[i].flags;
11381
11382       if (flags & RPC_IN) {
11383          if (flags & RPC_VARARRAY) {
11384             sscanf(arpc_param[index_in++], "%d %d", &n_param, &array_tid);
11385
11386             prpc_param[i] = in_param_ptr;
11387             for (j = 0; j < n_param; j++) {
11388                db_sscanf(arpc_param[index_in++], in_param_ptr, &param_size, 0, array_tid);
11389                in_param_ptr += param_size;
11390             }
11391             in_param_ptr = (char *) ALIGN8(((PTYPE) in_param_ptr));
11392
11393             strcat(debug_line, "<array>");
11394          } else {
11395             db_sscanf(arpc_param[index_in++], in_param_ptr, &param_size, 0, tid);
11396             param_size = ALIGN8(param_size);
11397
11398             if (tid == TID_STRING || tid == TID_LINK)
11399                param_size = ALIGN8(1 + strlen((char *) (in_param_ptr)));
11400
11401             /*
11402                if (tid == TID_STRUCT)
11403                param_size = ALIGN8(rpc_list[index].param[i].n);
11404              */
11405             prpc_param[i] = in_param_ptr;
11406
11407             db_sprintf(str, in_param_ptr, param_size, 0, rpc_list[index].param[i].tid);
11408             if (rpc_list[index].param[i].tid == TID_STRING) {
11409                /* check for long strings (db_create_record...) */
11410                if (strlen(debug_line) + strlen(str) + 2 < sizeof(debug_line)) {
11411                   strcat(debug_line, "\"");
11412                   strcat(debug_line, str);
11413                   strcat(debug_line, "\"");
11414                } else
11415                   strcat(debug_line, "...");
11416             } else
11417                strcat(debug_line, str);
11418
11419             in_param_ptr += param_size;
11420          }
11421
11422          if ((PTYPE) in_param_ptr - (PTYPE) buffer1 > ASCII_BUFFER_SIZE) {
11423             cm_msg(MERROR, "rpc_ascii_execute",
11424                    "parameters (%d) too large for network buffer (%d)", param_size,
11425                    ASCII_BUFFER_SIZE);
11426             return RPC_EXCEED_BUFFER;
11427          }
11428
11429       }
11430
11431       if (flags & RPC_OUT) {
11432          param_size = ALIGN8(tid_size[tid]);
11433
11434          if (flags & RPC_VARARRAY || tid == TID_STRING) {
11435             /* reserve maximum array length */
11436             param_size = atoi(arpc_param[index_in]);
11437             param_size = ALIGN8(param_size);
11438          }
11439
11440 /*
11441       if (rpc_list[index].param[i].tid == TID_STRUCT)
11442         param_size = ALIGN8(rpc_list[index].param[i].n);
11443 */
11444          if ((PTYPE) out_param_ptr - (PTYPE) buffer2 + param_size > ASCII_BUFFER_SIZE) {
11445             cm_msg(MERROR, "rpc_execute",
11446                    "return parameters (%d) too large for network buffer (%d)",
11447                    (PTYPE) out_param_ptr - (PTYPE) buffer2 + param_size,
11448                    ASCII_BUFFER_SIZE);
11449             return RPC_EXCEED_BUFFER;
11450          }
11451
11452          /* if parameter goes both directions, copy input to output */
11453          if (rpc_list[index].param[i].flags & RPC_IN)
11454             memcpy(out_param_ptr, prpc_param[i], param_size);
11455
11456          if (!(flags & RPC_IN))
11457             strcat(debug_line, "-");
11458
11459          prpc_param[i] = out_param_ptr;
11460          out_param_ptr += param_size;
11461       }
11462
11463       if (rpc_list[index].param[i + 1].tid)
11464          strcat(debug_line, ", ");
11465    }
11466
11467    strcat(debug_line, ")");
11468    rpc_debug_printf(debug_line);
11469
11470    last_param_ptr = out_param_ptr;
11471
11472    /*********************************\
11473    *   call dispatch function        *
11474    \*********************************/
11475
11476    if (rpc_list[index].dispatch)
11477       status = rpc_list[index].dispatch(routine_id, prpc_param);
11478    else
11479       status = RPC_INVALID_ID;
11480
11481    if (routine_id == RPC_ID_EXIT || routine_id == RPC_ID_SHUTDOWN ||
11482        routine_id == RPC_ID_WATCHDOG)
11483       status = RPC_SUCCESS;
11484
11485    /* Return if TCP connection broken */
11486    if (status == SS_ABORT)
11487       return SS_ABORT;
11488
11489    /* if sock == 0, we are in FTCP mode and may not sent results */
11490    if (!sock)
11491       return RPC_SUCCESS;
11492
11493    /* send return status */
11494    out_param_ptr = return_buffer;
11495    sprintf(out_param_ptr, "%d", status);
11496    out_param_ptr += strlen(out_param_ptr);
11497
11498    /* convert return parameters */
11499    for (i = 0; rpc_list[index].param[i].tid != 0; i++)
11500       if (rpc_list[index].param[i].flags & RPC_OUT) {
11501          *out_param_ptr++ = '&';
11502
11503          tid = rpc_list[index].param[i].tid;
11504          flags = rpc_list[index].param[i].flags;
11505          param_size = ALIGN8(tid_size[tid]);
11506
11507          if (tid == TID_STRING && !(flags & RPC_VARARRAY)) {
11508             strcpy(out_param_ptr, (char *) prpc_param[i]);
11509             param_size = strlen((char *) prpc_param[i]);
11510          }
11511
11512          else if (flags & RPC_VARARRAY) {
11513             if (rpc_list[index].id == RPC_BM_RECEIVE_EVENT) {
11514                param_size = *((INT *) prpc_param[i + 1]);
11515                /* write number of bytes to output */
11516                sprintf(out_param_ptr, "%d", param_size);
11517                out_param_ptr += strlen(out_param_ptr) + 1;      /* '0' finishes param */
11518                memcpy(out_param_ptr, prpc_param[i], param_size);
11519                out_param_ptr += param_size;
11520                *out_param_ptr = 0;
11521             } else {
11522                if (rpc_list[index].id == RPC_DB_GET_DATA1) {
11523                   param_size = *((INT *) prpc_param[i + 1]);
11524                   array_tid = *((INT *) prpc_param[i + 2]);
11525                   num_values = *((INT *) prpc_param[i + 3]);
11526                } else if (rpc_list[index].id == RPC_DB_GET_DATA_INDEX) {
11527                   param_size = *((INT *) prpc_param[i + 1]);
11528                   array_tid = *((INT *) prpc_param[i + 3]);
11529                   num_values = 1;
11530                } else if (rpc_list[index].id == RPC_HS_READ) {
11531                   param_size = *((INT *) prpc_param[i + 1]);
11532                   if (i == 6) {
11533                      array_tid = TID_DWORD;
11534                      num_values = param_size / sizeof(DWORD);
11535                   } else {
11536                      array_tid = *((INT *) prpc_param[10]);
11537                      num_values = *((INT *) prpc_param[11]);
11538                   }
11539                } else {         /* variable arrays of fixed type like hs_enum_events, hs_enum_vars */
11540
11541                   param_size = *((INT *) prpc_param[i + 1]);
11542                   array_tid = tid;
11543                   if (tid == TID_STRING)
11544                      num_values = param_size / NAME_LENGTH;
11545                   else
11546                      num_values = param_size / tid_size[tid];
11547                }
11548
11549                /* derive size of individual item */
11550                if (array_tid == TID_STRING)
11551                   item_size = param_size / num_values;
11552                else
11553                   item_size = tid_size[array_tid];
11554
11555                /* write number of elements to output */
11556                sprintf(out_param_ptr, "%d", num_values);
11557                out_param_ptr += strlen(out_param_ptr);
11558
11559                /* write array of values to output */
11560                for (j = 0; j < num_values; j++) {
11561                   *out_param_ptr++ = '&';
11562                   db_sprintf(out_param_ptr, prpc_param[i], item_size, j, array_tid);
11563                   out_param_ptr += strlen(out_param_ptr);
11564                }
11565             }
11566          }
11567
11568 /*
11569       else if (tid == TID_STRUCT)
11570         param_size = ALIGN8(rpc_list[index].param[i].n);
11571 */
11572          else
11573             db_sprintf(out_param_ptr, prpc_param[i], param_size, 0, tid);
11574
11575          out_param_ptr += strlen(out_param_ptr);
11576
11577          if ((PTYPE) out_param_ptr - (PTYPE) return_buffer > ASCII_BUFFER_SIZE) {
11578             cm_msg(MERROR, "rpc_execute",
11579                    "return parameter (%d) too large for network buffer (%d)", param_size,
11580                    ASCII_BUFFER_SIZE);
11581             return RPC_EXCEED_BUFFER;
11582          }
11583       }
11584
11585    /* send return parameters */
11586    param_size = (PTYPE) out_param_ptr - (PTYPE) return_buffer + 1;
11587
11588    status = send_tcp(sock, return_buffer, param_size, 0);
11589
11590    if (status < 0) {
11591       cm_msg(MERROR, "rpc_execute", "send_tcp() failed");
11592       return RPC_NET_ERROR;
11593    }
11594
11595    /* print return buffer */
11596    if (strlen(return_buffer) > sizeof(debug_line)) {
11597       memcpy(debug_line, return_buffer, sizeof(debug_line) - 10);
11598       strcat(debug_line, "...");
11599    } else
11600       sprintf(debug_line, "-> %s", return_buffer);
11601    rpc_debug_printf(debug_line);
11602
11603    /* return SS_EXIT if RPC_EXIT is called */
11604    if (routine_id == RPC_ID_EXIT)
11605       return SS_EXIT;
11606
11607    /* return SS_SHUTDOWN if RPC_SHUTDOWN is called */
11608    if (routine_id == RPC_ID_SHUTDOWN)
11609       return RPC_SHUTDOWN;
11610
11611    return RPC_SUCCESS;
11612 }
INT rpc_flush_event (void)
dox Send event residing in the TCP cache buffer filled by rpc_send_event. This routine should be called when a run is stopped.
Returns:
RPC_SUCCESS, RPC_NET_ERROR
Definition at line 10305 of file midas.c.
References _tcp_buffer, _tcp_rp, _tcp_wp, cm_msg, i, MERROR, rpc_is_remote(), RPC_NET_ERROR, RPC_SUCCESS, RPC_SERVER_CONNECTION::send_sock, and send_tcp().
Referenced by main(), rpc_end_of_cycle(), rpc_server_disconnect(), scan_fragment(), scheduler(), send_event(), tr_prestop(), tr_stop(), and yb_file_fragment().
10306 {
10307    INT i;
10308
10309    if (!rpc_is_remote())
10310       return RPC_SUCCESS;
10311
10312    /* return if rpc_send_event was not called */
10313    if (!_tcp_buffer || _tcp_wp == 0)
10314       return RPC_SUCCESS;
10315
10316    /* empty TCP buffer */
10317    if (_tcp_wp > 0) {
10318       i = send_tcp(_server_connection.send_sock,
10319                    _tcp_buffer + _tcp_rp, _tcp_wp - _tcp_rp, 0);
10320
10321       if (i != _tcp_wp - _tcp_rp) {
10322          cm_msg(MERROR, "rpc_flush_event", "send_tcp() failed");
10323          return RPC_NET_ERROR;
10324       }
10325    }
10326
10327    _tcp_rp = _tcp_wp = 0;
10328
10329    return RPC_SUCCESS;
10330 }
void rpc_get_convert_flags (INT * convert_flags)
Definition at line 7998 of file midas.c.
References RPC_SERVER_CONNECTION::remote_hw_type, rpc_calc_convert_flags(), rpc_get_option(), and RPC_OHW_TYPE.
Referenced by main().
{
   rpc_calc_convert_flags(rpc_get_option(0, RPC_OHW_TYPE),
                          _server_connection.remote_hw_type, convert_flags);
}
int rpc_get_event_sock (void)
Definition at line 10272 of file midas.c.
References RPC_SERVER_CONNECTION::event_sock.
Referenced by dm_buffer_create(), and eb_create_buffer().
10275          : rpc_get_event_sock
10276
10277   Purpose: Return event send socket to MIDAS server. Used by MFE.C for
10278            optimized event sending.
10279
10280   Input:
10281     none
10282
10283   Output:
10284     none
10285
10286   Function value:
10287     int    socket
10288
10289 \********************************************************************/
10290 {
10291    return _server_connection.event_sock;
10292 }
INT rpc_get_name (char * name)
Definition at line 9368 of file midas.c.
References RPC_SUCCESS.
Referenced by al_check(), cm_disconnect_experiment(), cm_msg(), cm_msg1(), rpc_client_connect(), and rpc_server_connect().
         : rpc_get_name
  Purpose: Get name set by rpc_set_name
  Input:
    none
  Output:
    char*  name             The location pointed by *name receives a
                            copy of the _prog_name
  Function value:
    RPC_SUCCESS             Successful completion
\********************************************************************/
{
   strcpy(name, _client_name);
   return RPC_SUCCESS;
}
INT rpc_get_opt_tcp_size (void)
Definition at line 10096 of file midas.c.
10097 {
10098    return _opt_tcp_size;
10099 }
INT rpc_get_option (HNDLE hConn, INT item)
Definition at line 9092 of file midas.c.
References cm_msg, d, DRF_G_FLOAT, DRF_IEEE, DRI_16, DRI_32, DRI_64, DRI_BIG_ENDIAN, DRI_LITTLE_ENDIAN, MERROR, p, RPC_OHW_TYPE, RPC_OTIMEOUT, RPC_OTRANSPORT, RPC_CLIENT_CONNECTION::rpc_timeout, RPC_SERVER_CONNECTION::rpc_timeout, size, RPC_CLIENT_CONNECTION::transport, and RPC_SERVER_CONNECTION::transport.
Referenced by cm_connect_experiment1(), cm_transition(), rpc_call(), rpc_client_accept(), rpc_client_call(), rpc_client_connect(), rpc_get_convert_flags(), rpc_server_callback(), and rpc_server_connect().
         : rpc_get_option
  Purpose: Get actual RPC option
  Input:
    HNDLE hConn             RPC connection handle
    INT   item              One of RPC_Oxxx
  Output:
    none
  Function value:
    INT                     Actual option
\********************************************************************/
{
   switch (item) {
   case RPC_OTIMEOUT:
      if (hConn == -1)
         return _server_connection.rpc_timeout;
      return _client_connection[hConn - 1].rpc_timeout;
   case RPC_OTRANSPORT:
      if (hConn == -1)
         return _server_connection.transport;
      return _client_connection[hConn - 1].transport;
   case RPC_OHW_TYPE:
      {
         INT tmp_type, size;
         DWORD dummy;
         unsigned char *p;
         float f;
         double d;
         tmp_type = 0;
         /* test pointer size */
         size = sizeof(p);
         if (size == 2)
            tmp_type |= DRI_16;
         if (size == 4)
            tmp_type |= DRI_32;
         if (size == 8)
            tmp_type |= DRI_64;
         /* test if little or big endian machine */
         dummy = 0x12345678;
         p = (unsigned char *) &dummy;
         if (*p == 0x78)
            tmp_type |= DRI_LITTLE_ENDIAN;
         else if (*p == 0x12)
            tmp_type |= DRI_BIG_ENDIAN;
         else
            cm_msg(MERROR, "rpc_get_option", "unknown byte order format");
         /* floating point format */
         f = (float) 1.2345;
         dummy = 0;
         memcpy(&dummy, &f, sizeof(f));
         if ((dummy & 0xFF) == 0x19 &&
             ((dummy >> 8) & 0xFF) == 0x04 &&
             ((dummy >> 16) & 0xFF) == 0x9E && ((dummy >> 24) & 0xFF) == 0x3F)
            tmp_type |= DRF_IEEE;
         else if ((dummy & 0xFF) == 0x9E &&
                  ((dummy >> 8) & 0xFF) == 0x40 &&
                  ((dummy >> 16) & 0xFF) == 0x19 && ((dummy >> 24) & 0xFF) == 0x04)
            tmp_type |= DRF_G_FLOAT;
         else
            cm_msg(MERROR, "rpc_get_option", "unknown floating point format");
         d = (double) 1.2345;
         dummy = 0;
         memcpy(&dummy, &d, sizeof(f));
         if ((dummy & 0xFF) == 0x8D &&  /* little endian */
             ((dummy >> 8) & 0xFF) == 0x97 &&
             ((dummy >> 16) & 0xFF) == 0x6E && ((dummy >> 24) & 0xFF) == 0x12)
            tmp_type |= DRF_IEEE;
         else if ((dummy & 0xFF) == 0x83 &&     /* big endian */
                  ((dummy >> 8) & 0xFF) == 0xC0 &&
                  ((dummy >> 16) & 0xFF) == 0xF3 && ((dummy >> 24) & 0xFF) == 0x3F)
            tmp_type |= DRF_IEEE;
         else if ((dummy & 0xFF) == 0x13 &&
                  ((dummy >> 8) & 0xFF) == 0x40 &&
                  ((dummy >> 16) & 0xFF) == 0x83 && ((dummy >> 24) & 0xFF) == 0xC0)
            tmp_type |= DRF_G_FLOAT;
         else if ((dummy & 0xFF) == 0x9E &&
                  ((dummy >> 8) & 0xFF) == 0x40 &&
                  ((dummy >> 16) & 0xFF) == 0x18 && ((dummy >> 24) & 0xFF) == 0x04)
            cm_msg(MERROR, "rpc_get_option",
                   "MIDAS cannot handle VAX D FLOAT format. Please compile with the /g_float flag");
         else
            cm_msg(MERROR, "rpc_get_option", "unknown floating point format");
         return tmp_type;
      }
   default:
      cm_msg(MERROR, "rpc_get_option", "invalid argument");
      break;
   }
   return 0;
}
int rpc_get_send_sock (void)
dox
Definition at line 10248 of file midas.c.
References RPC_SERVER_CONNECTION::send_sock.
Referenced by yb_file_fragment().
10251          : rpc_get_send_sock
10252
10253   Purpose: Return send socket to MIDAS server. Used by MFE.C for
10254            optimized event sending.
10255
10256   Input:
10257     none
10258
10259   Output:
10260     none
10261
10262   Function value:
10263     int    socket
10264
10265 \********************************************************************/
10266 {
10267    return _server_connection.send_sock;
10268 }
INT rpc_get_server_acception (void)
Definition at line 9045 of file midas.c.
Referenced by bm_check_buffers(), bm_close_buffer(), bm_empty_buffers(), bm_mark_read_waiting(), bm_open_buffer(), cm_set_watchdog_params(), db_close_database(), db_flush_database(), and db_open_database().
         : rpc_get_server_acception
  Purpose: Return actual RPC server connection index
  Input:
   none
  Output:
    none
  Function value:
    INT    RPC server connection index
\********************************************************************/
{
   return _server_acception_index;
}
PTYPE rpc_get_server_option (INT item)
dox
Definition at line 9250 of file midas.c.
References RPC_SERVER_ACCEPTION::client_handle, RPC_SERVER_ACCEPTION::convert_flags, i, MAX, MAX_RPC_CONNECTION, RPC_SERVER_ACCEPTION::odb_handle, PTYPE, RPC_CLIENT_HANDLE, RPC_CONVERT_FLAGS, RPC_ODB_HANDLE, RPC_OSERVER_NAME, RPC_OSERVER_TYPE, RPC_SEND_SOCK, RPC_WATCHDOG_TIMEOUT, RPC_SERVER_ACCEPTION::send_sock, ss_gettid(), ST_MTHREAD, ST_NONE, ST_REMOTE, ST_SINGLE, and RPC_SERVER_ACCEPTION::watchdog_timeout.
Referenced by bm_check_buffers(), bm_close_buffer(), bm_empty_buffers(), bm_mark_read_waiting(), bm_notify_client(), bm_open_buffer(), bm_receive_event(), cm_disconnect_experiment(), cm_get_experiment_database(), cm_set_watchdog_params(), db_close_database(), db_flush_database(), db_get_record(), db_open_database(), db_set_record(), db_update_record(), recv_event_server(), recv_tcp_server(), rpc_check_channels(), rpc_server_accept(), rpc_server_callback(), rpc_server_dispatch(), rpc_server_receive(), and ss_suspend().
         : rpc_get_server_option
  Purpose: Get actual RPC option for server connection
  Input:
    INT  item               One of RPC_Oxxx
  Output:
    none
  Function value:
    INT                     Actual option
\********************************************************************/
{
   INT i;
   if (item == RPC_OSERVER_TYPE)
      return _server_type;
   if (item == RPC_OSERVER_NAME)
      return (PTYPE) _server_name;
   /* return 0 for local calls */
   if (_server_type == ST_NONE)
      return 0;
   /* check which connections belongs to caller */
   if (_server_type == ST_MTHREAD) {
      for (i = 0; i < MAX_RPC_CONNECTION; i++)
         if (_server_acception[i].tid == ss_gettid())
            break;
   } else if (_server_type == ST_SINGLE || _server_type == ST_REMOTE)
      i = MAX(0, _server_acception_index - 1);
   else
      i = 0;
   switch (item) {
   case RPC_CONVERT_FLAGS:
      return _server_acception[i].convert_flags;
   case RPC_ODB_HANDLE:
      return _server_acception[i].odb_handle;
   case RPC_CLIENT_HANDLE:
      return _server_acception[i].client_handle;
   case RPC_SEND_SOCK:
      return _server_acception[i].send_sock;
   case RPC_WATCHDOG_TIMEOUT:
      return _server_acception[i].watchdog_timeout;
   }
   return 0;
}
void rpc_ieee2vax_double (double * var)
Definition at line 8058 of file midas.c.
Referenced by rpc_convert_single().
{
   unsigned short int i1, i2, i3, i4;
   /* swap words */
   i1 = *((short int *) (var) + 3);
   i2 = *((short int *) (var) + 2);
   i3 = *((short int *) (var) + 1);
   i4 = *((short int *) (var));
   /* correct exponent */
   if (i1 != 0)
      i1 += 0x20;
   *((short int *) (var) + 3) = i4;
   *((short int *) (var) + 2) = i3;
   *((short int *) (var) + 1) = i2;
   *((short int *) (var)) = i1;
}
void rpc_ieee2vax_float (float * var)
Definition at line 8005 of file midas.c.
Referenced by rpc_convert_single().
{
   unsigned short int lo, hi;
   /* swap hi and lo word */
   lo = *((short int *) (var) + 1);
   hi = *((short int *) (var));
   /* correct exponent */
   if (lo != 0)
      lo += 0x100;
   *((short int *) (var) + 1) = hi;
   *((short int *) (var)) = lo;
}
INT rpc_is_remote (void)
Definition at line 9022 of file midas.c.
References RPC_SERVER_CONNECTION::send_sock.
Referenced by al_check(), al_trigger_alarm(), bm_add_event_request(), bm_close_all_buffers(), bm_close_buffer(), bm_empty_buffers(), bm_flush_cache(), bm_get_buffer_info(), bm_get_buffer_level(), bm_init_buffer_counters(), bm_mark_read_waiting(), bm_open_buffer(), bm_receive_event(), bm_remove_event_request(), bm_send_event(), bm_set_cache_size(), bm_skip_event(), cm_asctime(), cm_cleanup(), cm_connect_experiment1(), cm_delete_client_info(), cm_disconnect_experiment(), cm_execute(), cm_exist(), cm_get_watchdog_info(), cm_msg_log(), cm_msg_log1(), cm_msg_retrieve(), cm_set_client_info(), cm_set_watchdog_params(), cm_synchronize(), cm_time(), cm_yield(), command_loop(), db_add_open_record(), db_check_record(), db_close_all_databases(), db_close_database(), db_create_key(), db_create_link(), db_create_record(), db_delete_key(), db_enum_key(), db_enum_link(), db_find_key(), db_find_key1(), db_find_link(), db_find_link1(), db_flush_database(), db_get_data(), db_get_data1(), db_get_data_index(), db_get_key(), db_get_key_info(), db_get_key_time(), db_get_next_link(), db_get_open_records(), db_get_path(), db_get_record(), db_get_record_size(), db_get_value(), db_load(), db_open_database(), db_remove_open_record(), db_rename_key(), db_reorder_key(), db_save(), db_send_changed_records(), db_set_client_name(), db_set_data(), db_set_data_index(), db_set_data_index2(), db_set_mode(), db_set_num_values(), db_set_record(), db_set_value(), el_submit(), hs_count_events(), hs_count_vars(), hs_enum_events(), hs_enum_vars(), hs_get_event_id(), hs_get_var(), hs_read(), hs_set_path(), log_system_history(), rpc_flush_event(), rpc_send_event(), rpc_server_thread(), and tr_stop().
         : rpc_is_remote
  Purpose: Return true if program is connected to a remote server
  Input:
   none
  Output:
    none
  Function value:
    INT    RPC connection index
\********************************************************************/
{
   return _server_connection.send_sock != 0;
}
INT rpc_register_client (char * name, RPC_LIST * list)
dox Register RPC client for standalone mode (without standard midas server)
Parameters:
list Array of RPC_LIST structures containing function IDs and parameter definitions. The end of the list must be indicated by a function ID of zero.
name Name of this client
Returns:
RPC_SUCCESS
Definition at line 8197 of file midas.c.
References rpc_get_internal_list(), rpc_register_functions(), rpc_set_name(), and RPC_SUCCESS.
Referenced by main().
{
   rpc_set_name(name);
   rpc_register_functions(rpc_get_internal_list(0), NULL);
   rpc_register_functions(list, NULL);
   return RPC_SUCCESS;
}
INT rpc_register_function (INT id, INT(*)(INT, void **) func)
Definition at line 8300 of file midas.c.
References RPC_LIST::dispatch, i, RPC_LIST::id, RPC_INVALID_ID, and RPC_SUCCESS.
Referenced by cm_register_function(), cm_register_transition(), main(), rpc_master_init(), and rpc_slave_init().
         : rpc_register_function
  Purpose: Replace a dispatch function for a specific rpc routine
  Input:
    INT      id             RPC ID
    INT      *func          New dispatch function
  Output:
   <implicit: func gets copied to rpc_list>
  Function value:
   RPC_SUCCESS              Successful completion
   RPC_INVALID_ID           RPC ID not found
\********************************************************************/
{
   INT i;
   for (i = 0; rpc_list != NULL && rpc_list[i].id != 0; i++)
      if (rpc_list[i].id == id)
         break;
   if (rpc_list[i].id == id)
      rpc_list[i].dispatch = func;
   else
      return RPC_INVALID_ID;
   return RPC_SUCCESS;
}
INT rpc_register_functions (RPC_LIST * new_list, INT(*)(INT, void **) func)
Register a set of RPC functions (both as clients or servers)
Parameters:
new_list Array of RPC_LIST structures containing function IDs and parameter definitions. The end of the list must be indicated by a function ID of zero.
func Default dispatch function
Returns:
RPC_SUCCESS, RPC_NO_MEMORY, RPC_DOUBLE_DEFINED
Definition at line 8217 of file midas.c.
References cm_msg, RPC_LIST::dispatch, i, RPC_LIST::id, j, M_MALLOC, MERROR, RPC_DOUBLE_DEFINED, rpc_get_internal_list(), RPC_MAX_ID, RPC_MIN_ID, RPC_NO_MEMORY, and RPC_SUCCESS.
Referenced by cam_init_rpc(), cm_connect_experiment1(), cm_register_server(), main(), rpc_master_init(), rpc_register_client(), rpc_register_server(), rpc_server_connect(), and rpc_slave_init().
{
   INT i, j, iold, inew;
   /* count number of new functions */
   for (i = 0; new_list[i].id != 0; i++) {
      /* check double defined functions */
      for (j = 0; rpc_list != NULL && rpc_list[j].id != 0; j++)
         if (rpc_list[j].id == new_list[i].id)
            return RPC_DOUBLE_DEFINED;
   }
   inew = i;
   /* count number of existing functions */
   for (i = 0; rpc_list != NULL && rpc_list[i].id != 0; i++);
   iold = i;
   /* allocate new memory for rpc_list */
   if (rpc_list == NULL)
      rpc_list = (RPC_LIST *) M_MALLOC(sizeof(RPC_LIST) * (inew + 1));
   else
      rpc_list = (RPC_LIST *) realloc(rpc_list, sizeof(RPC_LIST) * (iold + inew + 1));
   if (rpc_list == NULL) {
      cm_msg(MERROR, "rpc_register_functions", "out of memory");
      return RPC_NO_MEMORY;
   }
   /* append new functions */
   for (i = iold; i < iold + inew; i++) {
      memcpy(rpc_list + i, new_list + i - iold, sizeof(RPC_LIST));
      /* set default dispatcher */
      if (rpc_list[i].dispatch == NULL)
         rpc_list[i].dispatch = func;
      /* check valid ID for user functions */
      if (new_list != rpc_get_internal_list(0) &&
          new_list != rpc_get_internal_list(1) &&
          (rpc_list[i].id < RPC_MIN_ID || rpc_list[i].id > RPC_MAX_ID))
         cm_msg(MERROR, "rpc_register_functions",
                "registered RPC function with invalid ID");
   }
   /* mark end of list */
   rpc_list[i].id = 0;
   return RPC_SUCCESS;
}
INT rpc_register_server (INT server_type, char * name, INT * port, INT(*)(INT, void **) func)
Definition at line 10866 of file midas.c.
References CH_LISTEN, cm_msg, flag, MERROR, MIDAS_TCP_PORT, PTYPE, rpc_client_accept(), rpc_get_internal_list(), RPC_NET_ERROR, RPC_OSERVER_NAME, RPC_OSERVER_TYPE, rpc_register_functions(), rpc_server_accept(), rpc_set_server_option(), RPC_SUCCESS, size, ss_suspend_set_dispatch(), ST_REMOTE, ST_SUBPROCESS, and status.
Referenced by cm_register_server(), and main().
10870          : rpc_register_server
10871
10872   Purpose: Register the calling process as a MIDAS RPC server. Note
10873            that cm_connnect_experiment must be called prior to any call of
10874            rpc_register_server.
10875
10876   Input:
10877     INT   server_type       One of the following constants:
10878                             ST_SINGLE: register a single process server
10879                             ST_MTHREAD: for each connection, start
10880                                         a new thread to serve it
10881                             ST_MPROCESS: for each connection, start
10882                                          a new process to server it
10883                             ST_SUBPROCESS: the routine was called from
10884                                            a multi process server
10885                             ST_REMOTE: register a client program server
10886                                        connected to the ODB
10887     char  *name             Name of .EXE file to start in MPROCESS mode
10888     INT   *port             TCP port for listen. NULL if listen as main
10889                             server (MIDAS_TCP_PORT is then used). If *port=0,
10890                             the OS chooses a free port and returns it. If
10891                             *port != 0, this port is used.
10892     INT   *func             Default dispatch function
10893
10894   Output:
10895     INT   *port             Port under which server is listening.
10896
10897   Function value:
10898     RPC_SUCCESS             Successful completion
10899     RPC_NET_ERROR           Error in socket call
10900     RPC_NOT_REGISTERED      cm_connect_experiment was not called
10901
10902 \********************************************************************/
10903 {
10904    struct sockaddr_in bind_addr;
10905    INT status, flag;
10906    int size;
10907
10908 #ifdef OS_WINNT
10909    {
10910       WSADATA WSAData;
10911
10912       /* Start windows sockets */
10913       if (WSAStartup(MAKEWORD(1, 1), &WSAData) != 0)
10914          return RPC_NET_ERROR;
10915    }
10916 #endif
10917
10918    rpc_set_server_option(RPC_OSERVER_TYPE, server_type);
10919
10920    /* register system functions */
10921    rpc_register_functions(rpc_get_internal_list(0), func);
10922
10923    if (name != NULL)
10924       rpc_set_server_option(RPC_OSERVER_NAME, (PTYPE) name);
10925
10926    /* in subprocess mode, don't start listener */
10927    if (server_type == ST_SUBPROCESS)
10928       return RPC_SUCCESS;
10929
10930    /* create a socket for listening */
10931    _lsock = socket(AF_INET, SOCK_STREAM, 0);
10932    if (_lsock == -1) {
10933       cm_msg(MERROR, "rpc_register_server", "socket() failed");
10934       return RPC_NET_ERROR;
10935    }
10936
10937    /* reuse address, needed if previous server stopped (30s timeout!) */
10938    flag = 1;
10939    status = setsockopt(_lsock, SOL_SOCKET, SO_REUSEADDR, (char *) &flag, sizeof(INT));
10940    if (status < 0) {
10941       cm_msg(MERROR, "rpc_register_server", "setsockopt() failed");
10942       return RPC_NET_ERROR;
10943    }
10944
10945    /* bind local node name and port to socket */
10946    memset(&bind_addr, 0, sizeof(bind_addr));
10947    bind_addr.sin_family = AF_INET;
10948    bind_addr.sin_addr.s_addr = htonl(INADDR_ANY);
10949
10950    if (!port)
10951       bind_addr.sin_port = htons(MIDAS_TCP_PORT);
10952    else
10953       bind_addr.sin_port = htons((short) (*port));
10954
10955    status = bind(_lsock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
10956    if (status < 0) {
10957       cm_msg(MERROR, "rpc_register_server", "bind() failed: %s", strerror(errno));
10958       return RPC_NET_ERROR;
10959    }
10960
10961    /* listen for connection */
10962 #ifdef OS_MSDOS
10963    status = listen(_lsock, 1);
10964 #else
10965    status = listen(_lsock, SOMAXCONN);
10966 #endif
10967    if (status < 0) {
10968       cm_msg(MERROR, "rpc_register_server", "listen() failed");
10969       return RPC_NET_ERROR;
10970    }
10971
10972    /* return port wich OS has choosen */
10973    if (port && *port == 0) {
10974       size = sizeof(bind_addr);
10975       getsockname(_lsock, (struct sockaddr *) &bind_addr, (int *) &size);
10976       *port = ntohs(bind_addr.sin_port);
10977    }
10978
10979    /* define callbacks for ss_suspend */
10980    if (server_type == ST_REMOTE)
10981       ss_suspend_set_dispatch(CH_LISTEN, &_lsock, (int (*)(void)) rpc_client_accept);
10982    else
10983       ss_suspend_set_dispatch(CH_LISTEN, &_lsock, (int (*)(void)) rpc_server_accept);
10984
10985    return RPC_SUCCESS;
10986 }
INT rpc_send_event (INT buffer_handle, void * source, INT buf_size, INT async_flag)
dox Fast send_event routine which bypasses the RPC layer and sends the event directly at the TCP level.
Parameters:
buffer_handle Handle of the buffer to send the event to. Must be obtained via bm_open_buffer.
source Address of the event to send. It must have a proper event header.
buf_size Size of event in bytes with header.
async_flag SYNC / ASYNC flag. In ASYNC mode, the function returns immediately if it cannot send the event over the network. In SYNC mode, it waits until the packet is sent (blocking).
Returns:
BM_INVALID_PARAM, BM_ASYNC_RETURN, RPC_SUCCESS, RPC_NET_ERROR, RPC_NO_CONNECTION, RPC_EXCEED_BUFFER
Definition at line 10122 of file midas.c.
References _tcp_buffer, _tcp_rp, _tcp_wp, ALIGN8, ASYNC, BM_ASYNC_RETURN, BM_INVALID_PARAM, bm_send_event(), cm_msg, data_size, flag, NET_COMMAND::header, i, M_MALLOC, MAX_EVENT_SIZE, MERROR, NET_TCP_SIZE, NET_COMMAND::param, NET_COMMAND_HEADER::param_size, NET_COMMAND_HEADER::routine_id, RPC_BM_SEND_EVENT, RPC_EXCEED_BUFFER, rpc_is_remote(), RPC_NET_ERROR, RPC_SUCCESS, RPC_SERVER_CONNECTION::send_sock, send_tcp(), and TCP_FAST.
Referenced by interrupt_routine(), main(), scheduler(), and source_scan().
10123 {
10124    INT i;
10125    NET_COMMAND *nc;
10126    unsigned long flag;
10127    BOOL would_block = 0;
10128    DWORD aligned_buf_size;
10129
10130    aligned_buf_size = ALIGN8(buf_size);
10131
10132    if (aligned_buf_size !=
10133        (INT) ALIGN8(((EVENT_HEADER *) source)->data_size + sizeof(EVENT_HEADER))) {
10134       cm_msg(MERROR, "rpc_send_event", "event size mismatch");
10135       return BM_INVALID_PARAM;
10136    }
10137    if (((EVENT_HEADER *) source)->data_size > MAX_EVENT_SIZE) {
10138       cm_msg(MERROR, "rpc_send_event",
10139              "event size (%d) larger than maximum event size (%d)",
10140              ((EVENT_HEADER *) source)->data_size, MAX_EVENT_SIZE);
10141       return RPC_EXCEED_BUFFER;
10142    }
10143
10144    if (!rpc_is_remote())
10145       return bm_send_event(buffer_handle, source, buf_size, async_flag);
10146
10147    /* init network buffer */
10148    if (!_tcp_buffer)
10149       _tcp_buffer = (char *) M_MALLOC(NET_TCP_SIZE);
10150    if (!_tcp_buffer) {
10151       cm_msg(MERROR, "rpc_send_event", "not enough memory to allocate network buffer");
10152       return RPC_EXCEED_BUFFER;
10153    }
10154
10155    /* check if not enough space in TCP buffer */
10156    if (aligned_buf_size + 4 * 8 + sizeof(NET_COMMAND_HEADER) >=
10157        (DWORD) (_opt_tcp_size - _tcp_wp) && _tcp_wp != _tcp_rp) {
10158       /* set socket to nonblocking IO */
10159       if (async_flag == ASYNC) {
10160          flag = 1;
10161 #ifdef OS_VXWORKS
10162          ioctlsocket(_server_connection.send_sock, FIONBIO, (int) &flag);
10163 #else
10164          ioctlsocket(_server_connection.send_sock, FIONBIO, &flag);
10165 #endif
10166       }
10167
10168       i = send_tcp(_server_connection.send_sock,
10169                    _tcp_buffer + _tcp_rp, _tcp_wp - _tcp_rp, 0);
10170
10171       if (i < 0)
10172 #ifdef OS_WINNT
10173          would_block = (WSAGetLastError() == WSAEWOULDBLOCK);
10174 #else
10175          would_block = (errno == EWOULDBLOCK);
10176 #endif
10177
10178       /* set socket back to blocking IO */
10179       if (async_flag == ASYNC) {
10180          flag = 0;
10181 #ifdef OS_VXWORKS
10182          ioctlsocket(_server_connection.send_sock, FIONBIO, (int) &flag);
10183 #else
10184          ioctlsocket(_server_connection.send_sock, FIONBIO, &flag);
10185 #endif
10186       }
10187
10188       /* increment read pointer */
10189       if (i > 0)
10190          _tcp_rp += i;
10191
10192       /* check if whole buffer is sent */
10193       if (_tcp_rp == _tcp_wp)
10194          _tcp_rp = _tcp_wp = 0;
10195
10196       if (i < 0 && !would_block) {
10197          printf("send_tcp() returned %d\n", i);
10198          cm_msg(MERROR, "rpc_send_event", "send_tcp() failed");
10199          return RPC_NET_ERROR;
10200       }
10201
10202       /* return if buffer is not emptied */
10203       if (_tcp_wp > 0)
10204          return BM_ASYNC_RETURN;
10205    }
10206
10207    nc = (NET_COMMAND *) (_tcp_buffer + _tcp_wp);
10208    nc->header.routine_id = RPC_BM_SEND_EVENT | TCP_FAST;
10209    nc->header.param_size = 4 * 8 + aligned_buf_size;
10210
10211    /* assemble parameters manually */
10212    *((INT *) (&nc->param[0])) = buffer_handle;
10213    *((INT *) (&nc->param[8])) = buf_size;
10214
10215    /* send events larger than optimal buffer size directly */
10216    if (aligned_buf_size + 4 * 8 + sizeof(NET_COMMAND_HEADER) >= (DWORD) _opt_tcp_size) {
10217       /* send header */
10218       send_tcp(_server_connection.send_sock,
10219                _tcp_buffer + _tcp_wp, sizeof(NET_COMMAND_HEADER) + 16, 0);
10220
10221       /* send data */
10222       send_tcp(_server_connection.send_sock, (char *) source, aligned_buf_size, 0);
10223
10224       /* send last two parameters */
10225       *((INT *) (&nc->param[0])) = buf_size;
10226       *((INT *) (&nc->param[8])) = 0;
10227       send_tcp(_server_connection.send_sock, &nc->param[0], 16, 0);
10228    } else {
10229       /* copy event */
10230       memcpy(&nc->param[16], source, buf_size);
10231
10232       /* last two parameters (buf_size and async_flag */
10233       *((INT *) (&nc->param[16 + aligned_buf_size])) = buf_size;
10234       *((INT *) (&nc->param[24 + aligned_buf_size])) = 0;
10235
10236       _tcp_wp += nc->header.param_size + sizeof(NET_COMMAND_HEADER);
10237    }
10238
10239    return RPC_SUCCESS;
10240 }
INT rpc_server_accept (int lsock)
Definition at line 11616 of file midas.c.
References _debug_mode, closesocket, cm_get_version(), cm_msg, cm_scan_experiments(), callback_addr::debug, experiment_table::directory, callback_addr::directory, equal_ustring(), callback_addr::experiment, callback_addr::host_name, callback_addr::host_port1, callback_addr::host_port2, callback_addr::host_port3, i, callback_addr::index, index, MAX_EXPERIMENT, MAX_RPC_CONNECTION, MERROR, experiment_table::name, net_buffer, recv_string(), rpc_debug_printf(), rpc_get_server_option(), RPC_NET_ERROR, RPC_OSERVER_NAME, RPC_OSERVER_TYPE, rpc_server_callback(), rpc_server_thread(), RPC_SHUTDOWN, RPC_SUCCESS, send(), size, ss_shell(), ss_spawnv(), SS_SUCCESS, ss_thread_create(), ST_MPROCESS, ST_MTHREAD, ST_REMOTE, ST_SINGLE, status, experiment_table::user, and callback_addr::user.
Referenced by main(), and rpc_register_server().
11619          : rpc_server_accept
11620
11621   Purpose: Accept new incoming connections
11622
11623   Input:
11624     INT    lscok            Listen socket
11625
11626   Output:
11627     none
11628
11629   Function value:
11630     RPC_SUCCESS             Successful completion
11631     RPC_NET_ERROR           Error in socket call
11632     RPC_CONNCLOSED          Connection was closed
11633     RPC_SHUTDOWN            Listener shutdown
11634     RPC_EXCEED_BUFFER       Not enough memory for network buffer
11635
11636 \********************************************************************/
11637 {
11638    INT index, i;
11639    int size, status;
11640    char command, version[32], v1[32];
11641    INT sock, port1, port2, port3;
11642    struct sockaddr_in acc_addr;
11643    struct hostent *phe;
11644    char str[100];
11645    char host_port1_str[30], host_port2_str[30], host_port3_str[30];
11646    char debug_str[30];
11647    char *argv[10];
11648    char net_buffer[256];
11649    struct linger ling;
11650
11651    static struct callback_addr callback;
11652
11653    if (lsock > 0) {
11654       size = sizeof(acc_addr);
11655       sock = accept(lsock, (struct sockaddr *) &acc_addr, (int *) &size);
11656
11657       if (sock == -1)
11658          return RPC_NET_ERROR;
11659    } else {
11660       /* lsock is stdin -> already connected from inetd */
11661
11662       size = sizeof(acc_addr);
11663       sock = lsock;
11664       getpeername(sock, (struct sockaddr *) &acc_addr, (int *) &size);
11665    }
11666
11667    /* receive string with timeout */
11668    i = recv_string(sock, net_buffer, 256, 10000);
11669    rpc_debug_printf("Received command: %s", net_buffer);
11670
11671    if (i > 0) {
11672       command = (char) toupper(net_buffer[0]);
11673
11674       switch (command) {
11675       case 'S':
11676
11677          /*----------- shutdown listener ----------------------*/
11678          closesocket(sock);
11679          return RPC_SHUTDOWN;
11680
11681       case 7:
11682          ss_shell(sock);
11683          closesocket(sock);
11684          break;
11685
11686       case 'I':
11687
11688          /*----------- return available experiments -----------*/
11689          cm_scan_experiments();
11690          for (i = 0; i < MAX_EXPERIMENT && exptab[i].name[0]; i++) {
11691             sprintf(str, "%s", exptab[i].name);
11692             send(sock, str, strlen(str) + 1, 0);
11693          }
11694          send(sock, "", 1, 0);
11695          closesocket(sock);
11696          break;
11697
11698       case 'C':
11699
11700          /*----------- connect to experiment -----------*/
11701
11702          /* get callback information */
11703          callback.experiment[0] = 0;
11704          port1 = port2 = version[0] = 0;
11705          sscanf(net_buffer + 2, "%d %d %d %s", &port1, &port2, &port3, version);
11706          strcpy(callback.experiment,
11707                 strchr(strchr(strchr(strchr(net_buffer + 2, ' ') + 1, ' ') + 1, ' ') + 1,
11708                        ' ') + 1);
11709
11710          /* print warning if version patch level doesn't agree */
11711          strcpy(v1, version);
11712          if (strchr(v1, '.'))
11713             if (strchr(strchr(v1, '.') + 1, '.'))
11714                *strchr(strchr(v1, '.') + 1, '.') = 0;
11715
11716          strcpy(str, cm_get_version());
11717          if (strchr(str, '.'))
11718             if (strchr(strchr(str, '.') + 1, '.'))
11719                *strchr(strchr(str, '.') + 1, '.') = 0;
11720
11721          if (strcmp(v1, str) != 0) {
11722             sprintf(str, "client MIDAS version %s differs from local version %s",
11723                     version, cm_get_version());
11724             cm_msg(MERROR, "rpc_server_accept", str);
11725
11726             sprintf(str, "received string: %s", net_buffer + 2);
11727             cm_msg(MERROR, "rpc_server_accept", str);
11728          }
11729
11730          callback.host_port1 = (short) port1;
11731          callback.host_port2 = (short) port2;
11732          callback.host_port3 = (short) port3;
11733          callback.debug = _debug_mode;
11734
11735          /* get the name of the remote host */
11736 #ifdef OS_VXWORKS
11737          {
11738             INT status;
11739             status = hostGetByAddr(acc_addr.sin_addr.s_addr, callback.host_name);
11740             if (status != 0) {
11741                cm_msg(MERROR, "rpc_server_accept", "cannot get host name");
11742                break;
11743             }
11744          }
11745 #else
11746          phe = gethostbyaddr((char *) &acc_addr.sin_addr, 4, PF_INET);
11747          if (phe == NULL) {
11748             /* use IP number instead */
11749             strcpy(callback.host_name, (char *) inet_ntoa(acc_addr.sin_addr));
11750          } else
11751             strcpy(callback.host_name, phe->h_name);
11752 #endif
11753
11754          if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_MPROCESS) {
11755             /* update experiment definition */
11756             cm_scan_experiments();
11757
11758             /* lookup experiment */
11759             if (equal_ustring(callback.experiment, "Default"))
11760                index = 0;
11761             else
11762                for (index = 0; index < MAX_EXPERIMENT && exptab[index].name[0]; index++)
11763                   if (equal_ustring(callback.experiment, exptab[index].name))
11764                      break;
11765
11766             if (index == MAX_EXPERIMENT || exptab[index].name[0] == 0) {
11767                sprintf(str, "experiment %s not defined in exptab\r", callback.experiment);
11768                cm_msg(MERROR, "rpc_server_accept", str);
11769
11770                send(sock, "2", 2, 0);   /* 2 means exp. not found */
11771                closesocket(sock);
11772                break;
11773             }
11774
11775             strcpy(callback.directory, exptab[index].directory);
11776             strcpy(callback.user, exptab[index].user);
11777
11778             /* create a new process */
11779             sprintf(host_port1_str, "%d", callback.host_port1);
11780             sprintf(host_port2_str, "%d", callback.host_port2);
11781             sprintf(host_port3_str, "%d", callback.host_port3);
11782             sprintf(debug_str, "%d", callback.debug);
11783
11784             argv[0] = (char *) rpc_get_server_option(RPC_OSERVER_NAME);
11785             argv[1] = callback.host_name;
11786             argv[2] = host_port1_str;
11787             argv[3] = host_port2_str;
11788             argv[4] = host_port3_str;
11789             argv[5] = debug_str;
11790             argv[6] = callback.experiment;
11791             argv[7] = callback.directory;
11792             argv[8] = callback.user;
11793             argv[9] = NULL;
11794
11795             rpc_debug_printf("Spawn: %s %s %s %s %s %s %s %s %s %s",
11796                argv[0], argv[1], argv[2], argv[3], argv[4],
11797                argv[5], argv[6], argv[7], argv[8], argv[9]);
11798
11799             status = ss_spawnv(P_NOWAIT,
11800                           (char *) rpc_get_server_option(RPC_OSERVER_NAME),
11801                           argv);
11802
11803             if (status != SS_SUCCESS) {
11804                rpc_debug_printf("Cannot spawn subprocess: %s\n", strerror(errno));
11805
11806                sprintf(str, "3");       /* 3 means cannot spawn subprocess */
11807                send(sock, str, strlen(str) + 1, 0);
11808                closesocket(sock);
11809                break;
11810             }
11811
11812             sprintf(str, "1 %s", cm_get_version());     /* 1 means ok */
11813             send(sock, str, strlen(str) + 1, 0);
11814             closesocket(sock);
11815          } else {
11816             sprintf(str, "1 %s", cm_get_version());     /* 1 means ok */
11817             send(sock, str, strlen(str) + 1, 0);
11818             closesocket(sock);
11819          }
11820
11821          /* look for next free entry */
11822          for (index = 0; index < MAX_RPC_CONNECTION; index++)
11823             if (_server_acception[index].recv_sock == 0)
11824                break;
11825          if (index == MAX_RPC_CONNECTION)
11826             return RPC_NET_ERROR;
11827          callback.index = index;
11828
11829         /*----- multi thread server ------------------------*/
11830          if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_MTHREAD)
11831             ss_thread_create(rpc_server_thread, (void *) (&callback));
11832
11833         /*----- single thread server -----------------------*/
11834          if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_SINGLE ||
11835              rpc_get_server_option(RPC_OSERVER_TYPE) == ST_REMOTE)
11836             rpc_server_callback(&callback);
11837
11838          break;
11839
11840       default:
11841          cm_msg(MERROR, "rpc_server_accept", "received unknown command '%c'", command);
11842          closesocket(sock);
11843          break;
11844
11845       }
11846    } else {                     /* if i>0 */
11847
11848       /* lingering needed for PCTCP */
11849       ling.l_onoff = 1;
11850       ling.l_linger = 0;
11851       setsockopt(sock, SOL_SOCKET, SO_LINGER, (char *) &ling, sizeof(ling));
11852       closesocket(sock);
11853    }
11854
11855    return RPC_SUCCESS;
11856 }
INT rpc_server_callback (struct callback_addr * pcallback)
Definition at line 11980 of file midas.c.
References CH_SERVER, closesocket, cm_msg, RPC_SERVER_ACCEPTION::event_sock, flag, callback_addr::host_name, HOST_NAME_LENGTH, callback_addr::host_port1, callback_addr::host_port2, callback_addr::host_port3, callback_addr::index, index, RPC_SERVER_ACCEPTION::last_activity, MERROR, NAME_LENGTH, net_buffer, NET_TCP_SIZE, RPC_SERVER_ACCEPTION::recv_sock, recv_string(), RPC_SERVER_ACCEPTION::remote_hw_type, rpc_calc_convert_flags(), RPC_CONVERT_FLAGS, rpc_debug_printf(), rpc_get_option(), rpc_get_server_option(), RPC_NET_ERROR, RPC_OHW_TYPE, RPC_OSERVER_TYPE, rpc_server_receive(), rpc_set_server_acception(), rpc_set_server_option(), RPC_SUCCESS, send(), RPC_SERVER_ACCEPTION::send_sock, ss_gettid(), ss_millitime(), ss_suspend_set_dispatch(), ST_REMOTE, status, RPC_SERVER_ACCEPTION::tid, and RPC_SERVER_ACCEPTION::watchdog_timeout.
Referenced by rpc_server_accept(), and rpc_server_thread().
11983          : rpc_server_callback
11984
11985   Purpose: Callback a remote client. Setup _server_acception entry
11986            with optional conversion flags and establish two-way
11987            TCP connection.
11988
11989   Input:
11990     callback_addr pcallback Pointer to a callback structure
11991
11992   Output:
11993     none
11994
11995   Function value:
11996     RPC_SUCCESS             Successful completion
11997
11998 \********************************************************************/
11999 {
12000    INT index, status;
12001    int recv_sock, send_sock, event_sock;
12002    struct sockaddr_in bind_addr;
12003    struct hostent *phe;
12004    char str[100], client_program[NAME_LENGTH];
12005    char host_name[HOST_NAME_LENGTH];
12006    INT client_hw_type, hw_type;
12007    INT convert_flags;
12008    char net_buffer[256];
12009    struct callback_addr callback;
12010    int flag;
12011
12012    /* copy callback information */
12013    memcpy(&callback, pcallback, sizeof(callback));
12014    index = callback.index;
12015
12016    /* create new sockets for TCP */
12017    recv_sock = socket(AF_INET, SOCK_STREAM, 0);
12018    send_sock = socket(AF_INET, SOCK_STREAM, 0);
12019    event_sock = socket(AF_INET, SOCK_STREAM, 0);
12020    if (event_sock == -1)
12021       return RPC_NET_ERROR;
12022
12023    /* callback to remote node */
12024    memset(&bind_addr, 0, sizeof(bind_addr));
12025    bind_addr.sin_family = AF_INET;
12026    bind_addr.sin_port = htons(callback.host_port1);
12027
12028 #ifdef OS_VXWORKS
12029    {
12030       INT host_addr;
12031
12032       host_addr = hostGetByName(callback.host_name);
12033       memcpy((char *) &(bind_addr.sin_addr), &host_addr, 4);
12034    }
12035 #else
12036    phe = gethostbyname(callback.host_name);
12037    if (phe == NULL) {
12038       cm_msg(MERROR, "rpc_server_callback", "cannot get host name");
12039       return RPC_NET_ERROR;
12040    }
12041    memcpy((char *) &(bind_addr.sin_addr), phe->h_addr, phe->h_length);
12042 #endif
12043
12044    /* connect receive socket */
12045 #ifdef OS_UNIX
12046    do {
12047       status = connect(recv_sock, (void *) &bind_addr, sizeof(bind_addr));
12048
12049       /* don't return if an alarm signal was cought */
12050    } while (status == -1 && errno == EINTR);
12051 #else
12052    status = connect(recv_sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
12053 #endif
12054
12055    if (status != 0) {
12056       cm_msg(MERROR, "rpc_server_callback", "cannot connect receive socket");
12057       goto error;
12058    }
12059
12060    bind_addr.sin_port = htons(callback.host_port2);
12061
12062    /* connect send socket */
12063 #ifdef OS_UNIX
12064    do {
12065       status = connect(send_sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
12066
12067       /* don't return if an alarm signal was cought */
12068    } while (status == -1 && errno == EINTR);
12069 #else
12070    status = connect(send_sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
12071 #endif
12072
12073    if (status != 0) {
12074       cm_msg(MERROR, "rpc_server_callback", "cannot connect send socket");
12075       goto error;
12076    }
12077
12078    bind_addr.sin_port = htons(callback.host_port3);
12079
12080    /* connect event socket */
12081 #ifdef OS_UNIX
12082    do {
12083       status = connect(event_sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
12084
12085       /* don't return if an alarm signal was cought */
12086    } while (status == -1 && errno == EINTR);
12087 #else
12088    status = connect(event_sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
12089 #endif
12090
12091    if (status != 0) {
12092       cm_msg(MERROR, "rpc_server_callback", "cannot connect event socket");
12093       goto error;
12094    }
12095
12096    /* increase receive buffer size to 64k */
12097 #ifndef OS_ULTRIX               /* crashes ULTRIX... */
12098    flag = NET_TCP_SIZE + 1;
12099    setsockopt(event_sock, SOL_SOCKET, SO_RCVBUF, (char *) &flag, sizeof(INT));
12100 #endif
12101
12102    if (recv_string(recv_sock, net_buffer, 256, 10000) <= 0) {
12103       cm_msg(MERROR, "rpc_server_callback", "timeout on receive remote computer info");
12104       goto error;
12105    }
12106
12107    /* get remote computer info */
12108    sscanf(net_buffer, "%d", &client_hw_type);
12109
12110    strcpy(client_program, strchr(net_buffer, ' ') + 1);
12111
12112    /* get the name of the remote host */
12113 #ifdef OS_VXWORKS
12114    status = hostGetByAddr(bind_addr.sin_addr.s_addr, host_name);
12115    if (status != 0)
12116       strcpy(host_name, "unknown");
12117 #else
12118    phe = gethostbyaddr((char *) &bind_addr.sin_addr, 4, PF_INET);
12119    if (phe == NULL)
12120       strcpy(host_name, "unknown");
12121    else
12122       strcpy(host_name, phe->h_name);
12123 #endif
12124
12125    /* save information in _server_acception structure */
12126    _server_acception[index].recv_sock = recv_sock;
12127    _server_acception[index].send_sock = send_sock;
12128    _server_acception[index].event_sock = event_sock;
12129    _server_acception[index].remote_hw_type = client_hw_type;
12130    strcpy(_server_acception[index].host_name, host_name);
12131    strcpy(_server_acception[index].prog_name, client_program);
12132    _server_acception[index].tid = ss_gettid();
12133    _server_acception[index].last_activity = ss_millitime();
12134    _server_acception[index].watchdog_timeout = 0;
12135
12136    /* send my own computer id */
12137    hw_type = rpc_get_option(0, RPC_OHW_TYPE);
12138    sprintf(str, "%d", hw_type);
12139    send(recv_sock, str, strlen(str) + 1, 0);
12140
12141    rpc_set_server_acception(index + 1);
12142    rpc_calc_convert_flags(hw_type, client_hw_type, &convert_flags);
12143    rpc_set_server_option(RPC_CONVERT_FLAGS, convert_flags);
12144
12145    /* set callback function for ss_suspend */
12146    ss_suspend_set_dispatch(CH_SERVER, _server_acception,
12147                            (int (*)(void)) rpc_server_receive);
12148
12149    if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE)
12150       rpc_debug_printf("Connection to %s:%s established\n",
12151              _server_acception[index].host_name, _server_acception[index].prog_name);
12152
12153    return RPC_SUCCESS;
12154
12155  error:
12156
12157    closesocket(recv_sock);
12158    closesocket(send_sock);
12159    closesocket(event_sock);
12160
12161    return RPC_NET_ERROR;
12162 }
INT rpc_server_connect (char * host_name, char * exp_name)
Definition at line 8657 of file midas.c.
References CH_CLIENT, closesocket, cm_get_version(), cm_msg, CM_UNDEF_EXP, DEFAULT_RPC_TIMEOUT, RPC_SERVER_CONNECTION::event_sock, RPC_SERVER_CONNECTION::exp_name, flag, RPC_SERVER_CONNECTION::host_name, i, MERROR, MIDAS_TCP_PORT, NAME_LENGTH, NET_TCP_SIZE, RPC_SERVER_CONNECTION::recv_sock, recv_string(), RPC_SERVER_CONNECTION::remote_hw_type, rpc_client_dispatch(), rpc_get_internal_list(), rpc_get_name(), rpc_get_option(), RPC_NET_ERROR, RPC_NOT_REGISTERED, RPC_OHW_TYPE, rpc_register_functions(), RPC_SUCCESS, RPC_TCP, RPC_SERVER_CONNECTION::rpc_timeout, send(), RPC_SERVER_CONNECTION::send_sock, size, ss_suspend_set_dispatch(), status, and RPC_SERVER_CONNECTION::transport.
Referenced by cm_connect_experiment1().
         : rpc_server_connect
  Purpose: Extablish a network connection to a remote MIDAS
           server using a callback scheme.
  Input:
    char *host_name         IP address of host to connect to.
    INT  port               TPC port to connect to.
    char *exp_name          Name of experiment to connect to. By using
                            this name, several experiments (e.g. online
                            DAQ and offline analysis) can run simultan-
                            eously on the same host.
  Output:
    none
  Function value:
    RPC_SUCCESS              Successful completion
    RPC_NET_ERROR            Error in socket call
    RPC_NOT_REGISTERED       cm_connect_experiment was not called properly
    CM_UNDEF_EXP             Undefined experiment on server
\********************************************************************/
{
   INT i, status, flag;
   struct sockaddr_in bind_addr;
   INT sock, lsock1, lsock2, lsock3;
   INT listen_port1, listen_port2, listen_port3;
   INT remote_hw_type, hw_type;
   int size;
   char str[200], version[32], v1[32];
   char local_prog_name[NAME_LENGTH];
   struct hostent *phe;
#ifdef OS_WINNT
   {
      WSADATA WSAData;
      /* Start windows sockets */
      if (WSAStartup(MAKEWORD(1, 1), &WSAData) != 0)
         return RPC_NET_ERROR;
   }
#endif
   /* check if local connection */
   if (host_name[0] == 0)
      return RPC_SUCCESS;
   /* register system functions */
   rpc_register_functions(rpc_get_internal_list(0), NULL);
   /* check if cm_connect_experiment was called */
   if (_client_name[0] == 0) {
      cm_msg(MERROR, "rpc_server_connect",
             "cm_connect_experiment/rpc_set_name not called");
      return RPC_NOT_REGISTERED;
   }
   /* check if connection already exists */
   if (_server_connection.send_sock != 0)
      return RPC_SUCCESS;
   strcpy(_server_connection.host_name, host_name);
   strcpy(_server_connection.exp_name, exp_name);
   _server_connection.transport = RPC_TCP;
   _server_connection.rpc_timeout = DEFAULT_RPC_TIMEOUT;
   /* create new TCP sockets for listening */
   lsock1 = socket(AF_INET, SOCK_STREAM, 0);
   lsock2 = socket(AF_INET, SOCK_STREAM, 0);
   lsock3 = socket(AF_INET, SOCK_STREAM, 0);
   if (lsock3 == -1) {
      cm_msg(MERROR, "rpc_server_connect", "cannot create socket");
      return RPC_NET_ERROR;
   }
   flag = 1;
   setsockopt(lsock1, SOL_SOCKET, SO_REUSEADDR, (char *) &flag, sizeof(INT));
   setsockopt(lsock2, SOL_SOCKET, SO_REUSEADDR, (char *) &flag, sizeof(INT));
   setsockopt(lsock3, SOL_SOCKET, SO_REUSEADDR, (char *) &flag, sizeof(INT));
   /* let OS choose any port number */
   memset(&bind_addr, 0, sizeof(bind_addr));
   bind_addr.sin_family = AF_INET;
   bind_addr.sin_addr.s_addr = htonl(INADDR_ANY);
   bind_addr.sin_port = 0;
   status = bind(lsock1, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
   bind_addr.sin_port = 0;
   status = bind(lsock2, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
   bind_addr.sin_port = 0;
   status = bind(lsock3, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
   if (status < 0) {
      cm_msg(MERROR, "rpc_server_connect", "cannot bind");
      return RPC_NET_ERROR;
   }
   /* listen for connection */
   status = listen(lsock1, 1);
   status = listen(lsock2, 1);
   status = listen(lsock3, 1);
   if (status < 0) {
      cm_msg(MERROR, "rpc_server_connect", "cannot listen");
      return RPC_NET_ERROR;
   }
   /* find out which port OS has chosen */
   size = sizeof(bind_addr);
   getsockname(lsock1, (struct sockaddr *) &bind_addr, (int *) &size);
   listen_port1 = ntohs(bind_addr.sin_port);
   getsockname(lsock2, (struct sockaddr *) &bind_addr, (int *) &size);
   listen_port2 = ntohs(bind_addr.sin_port);
   getsockname(lsock3, (struct sockaddr *) &bind_addr, (int *) &size);
   listen_port3 = ntohs(bind_addr.sin_port);
   /* create a new socket for connecting to remote server */
   sock = socket(AF_INET, SOCK_STREAM, 0);
   if (sock == -1) {
      cm_msg(MERROR, "rpc_server_connect", "cannot create socket");
      return RPC_NET_ERROR;
   }
   /* connect to remote node */
   memset(&bind_addr, 0, sizeof(bind_addr));
   bind_addr.sin_family = AF_INET;
   bind_addr.sin_addr.s_addr = 0;
   bind_addr.sin_port = htons((short) MIDAS_TCP_PORT);
#ifdef OS_VXWORKS
   {
      INT host_addr;
      host_addr = hostGetByName(host_name);
      memcpy((char *) &(bind_addr.sin_addr), &host_addr, 4);
   }
#else
   phe = gethostbyname(host_name);
   if (phe == NULL) {
      cm_msg(MERROR, "rpc_server_connect", "cannot get host name");
      return RPC_NET_ERROR;
   }
   memcpy((char *) &(bind_addr.sin_addr), phe->h_addr, phe->h_length);
#endif
#ifdef OS_UNIX
   do {
      status = connect(sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
      /* don't return if an alarm signal was cought */
   } while (status == -1 && errno == EINTR);
#else
   status = connect(sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
#endif
   if (status != 0) {
/*    cm_msg(MERROR, "rpc_server_connect", "cannot connect"); message should be displayed by application */
      return RPC_NET_ERROR;
   }
   /* connect to experiment */
   if (exp_name[0] == 0)
      sprintf(str, "C %d %d %d %s Default",
              listen_port1, listen_port2, listen_port3, cm_get_version());
   else
      sprintf(str, "C %d %d %d %s %s",
              listen_port1, listen_port2, listen_port3, cm_get_version(), exp_name);
   send(sock, str, strlen(str) + 1, 0);
   i = recv_string(sock, str, sizeof(str), 10000);
   closesocket(sock);
   if (i <= 0) {
      cm_msg(MERROR, "rpc_server_connect", "timeout on receive status from server");
      return RPC_NET_ERROR;
   }
   status = version[0] = 0;
   sscanf(str, "%d %s", &status, version);
   if (status == 2) {
/*  message "undefined experiment" should be displayed by application */
      return CM_UNDEF_EXP;
   }
   /* print warning if version patch level doesn't agree */
   strcpy(v1, version);
   if (strchr(v1, '.'))
      if (strchr(strchr(v1, '.') + 1, '.'))
         *strchr(strchr(v1, '.') + 1, '.') = 0;
   strcpy(str, cm_get_version());
   if (strchr(str, '.'))
      if (strchr(strchr(str, '.') + 1, '.'))
         *strchr(strchr(str, '.') + 1, '.') = 0;
   if (strcmp(v1, str) != 0) {
      sprintf(str, "remote MIDAS version %s differs from local version %s",
              version, cm_get_version());
      cm_msg(MERROR, "rpc_server_connect", str);
   }
   /* wait for callback on send and recv socket */
   size = sizeof(bind_addr);
   _server_connection.send_sock =
       accept(lsock1, (struct sockaddr *) &bind_addr, (int *) &size);
   _server_connection.recv_sock =
       accept(lsock2, (struct sockaddr *) &bind_addr, (int *) &size);
   _server_connection.event_sock =
       accept(lsock3, (struct sockaddr *) &bind_addr, (int *) &size);
   if (_server_connection.send_sock == -1 ||
       _server_connection.recv_sock == -1 || _server_connection.event_sock == -1) {
      cm_msg(MERROR, "rpc_server_connect", "accept() failed");
      return RPC_NET_ERROR;
   }
   closesocket(lsock1);
   closesocket(lsock2);
   closesocket(lsock3);
   /* set TCP_NODELAY option for better performance */
#ifdef OS_VXWORKS
   flag = 1;
   setsockopt(_server_connection.send_sock,
              IPPROTO_TCP, TCP_NODELAY, (char *) &flag, sizeof(flag));
   setsockopt(_server_connection.event_sock,
              IPPROTO_TCP, TCP_NODELAY, (char *) &flag, sizeof(flag));
#endif
   /* increase send buffer size to 64kB */
   flag = NET_TCP_SIZE + 1;
   setsockopt(_server_connection.event_sock, SOL_SOCKET, SO_SNDBUF,
              (char *) &flag, sizeof(flag));
   /* send local computer info */
   rpc_get_name(local_prog_name);
   hw_type = rpc_get_option(0, RPC_OHW_TYPE);
   sprintf(str, "%d %s", hw_type, local_prog_name);
   send(_server_connection.send_sock, str, strlen(str) + 1, 0);
   /* receive remote computer info */
   i = recv_string(_server_connection.send_sock, str, sizeof(str), 10000);
   if (i <= 0) {
      cm_msg(MERROR, "rpc_server_connect", "timeout on receive remote computer info");
      return RPC_NET_ERROR;
   }
   sscanf(str, "%d", &remote_hw_type);
   _server_connection.remote_hw_type = remote_hw_type;
   /* set dispatcher which receives database updates */
   ss_suspend_set_dispatch(CH_CLIENT, &_server_connection,
                           (int (*)(void)) rpc_client_dispatch);
   return RPC_SUCCESS;
}
INT rpc_server_disconnect (void)
Definition at line 8975 of file midas.c.
References closesocket, RPC_SERVER_CONNECTION::event_sock, RPC_SERVER_CONNECTION::recv_sock, rpc_call(), rpc_flush_event(), RPC_ID_EXIT, RPC_SUCCESS, and RPC_SERVER_CONNECTION::send_sock.
Referenced by cm_connect_experiment1(), cm_disconnect_experiment(), and rpc_call().
         : rpc_server_disconnect
  Purpose: Close a rpc connection to a MIDAS server and close all
           server connections from other clients
  Input:
    none
  Output:
    none
  Function value:
   RPC_SUCCESS             Successful completion
   RPC_NET_ERROR           Error in socket call
   RPC_NO_CONNECTION       Maximum number of connections reached
\********************************************************************/
{
   static int rpc_server_disconnect_recursion_level = 0;
   if (rpc_server_disconnect_recursion_level)
      return RPC_SUCCESS;
   rpc_server_disconnect_recursion_level = 1;
   /* flush remaining events */
   rpc_flush_event();
   /* notify server about exit */
   rpc_call(RPC_ID_EXIT);
   /* close sockets */
   closesocket(_server_connection.send_sock);
   closesocket(_server_connection.recv_sock);
   closesocket(_server_connection.event_sock);
   memset(&_server_connection, 0, sizeof(RPC_SERVER_CONNECTION));
   rpc_server_disconnect_recursion_level = 0;
   return RPC_SUCCESS;
}
INT rpc_server_receive (INT index, int sock, BOOL check)
Definition at line 12223 of file midas.c.
References _msg_buffer, _net_recv_buffer, _net_recv_buffer_size, bm_close_all_buffers(), bm_send_event(), BM_SUCCESS, closesocket, cm_delete_client_info(), cm_get_experiment_database(), cm_msg, cm_set_experiment_database(), cm_watchdog(), EVENT_HEADER::data_size, db_close_all_databases(), DR_ASCII, hDB, hKey, M_FREE, M_MALLOC, MERROR, MTALK, RPC_SERVER_ACCEPTION::net_buffer, net_buffer, NET_BUFFER_SIZE, recv_event_server(), recv_string(), recv_tcp_server(), rpc_debug_printf(), rpc_deregister_functions(), RPC_EXCEED_BUFFER, rpc_execute(), rpc_execute_ascii(), rpc_get_server_option(), RPC_OSERVER_TYPE, rpc_set_server_acception(), RPC_SHUTDOWN, RPC_SUCCESS, SS_ABORT, ss_alarm(), SS_EXIT, ss_millitime(), SS_SUCCESS, ST_REMOTE, start_time, status, and SYNC.
Referenced by rpc_client_accept(), and rpc_server_callback().
12226          : rpc_server_receive
12227
12228   Purpose: Receive rpc commands and execute them. Close the connection
12229            if client has broken TCP pipe.
12230
12231   Input:
12232     INT    index            Index to _server_acception structure in-
12233                             dicating which connection got data.
12234     int    sock             Socket which got data
12235     BOOL   check            If TRUE, only check if connection is
12236                             broken. This may be called via
12237                             bm_receive_event/ss_suspend(..,MSG_BM)
12238
12239   Output:
12240     none
12241
12242   Function value:
12243     RPC_SUCCESS             Successful completion
12244     RPC_EXCEED_BUFFER       Not enough memeory to allocate buffer
12245     SS_EXIT                 Server connection was closed
12246     SS_ABORT                Server connection was broken
12247
12248 \********************************************************************/
12249 {
12250    INT status, n_received;
12251    INT remaining, *pbh, start_time;
12252    char test_buffer[256], str[80];
12253    EVENT_HEADER *pevent;
12254
12255    /* init network buffer */
12256    if (_net_recv_buffer_size == 0) {
12257       _net_recv_buffer = (char *) M_MALLOC(NET_BUFFER_SIZE);
12258       if (_net_recv_buffer == NULL) {
12259          cm_msg(MERROR, "rpc_server_receive",
12260                 "not enough memory to allocate network buffer");
12261          return RPC_EXCEED_BUFFER;
12262       }
12263       _net_recv_buffer_size = NET_BUFFER_SIZE;
12264    }
12265
12266    /* only check if TCP connection is broken */
12267    if (check) {
12268       n_received = recv(sock, test_buffer, sizeof(test_buffer), MSG_PEEK);
12269
12270       if (n_received == -1)
12271          cm_msg(MERROR, "rpc_server_receive",
12272                 "recv(%d,MSG_PEEK) returned %d, errno: %d (%s)", sizeof(test_buffer),
12273                 n_received, errno, strerror(errno));
12274
12275       if (n_received <= 0)
12276          return SS_ABORT;
12277
12278       return SS_SUCCESS;
12279    }
12280
12281    remaining = 0;
12282
12283    /* receive command */
12284    if (sock == _server_acception[index].recv_sock) {
12285       do {
12286          if (_server_acception[index].remote_hw_type == DR_ASCII)
12287             n_received = recv_string(_server_acception[index].recv_sock, _net_recv_buffer,
12288                                      NET_BUFFER_SIZE, 10000);
12289          else
12290             n_received =
12291                 recv_tcp_server(index, _net_recv_buffer, NET_BUFFER_SIZE, 0, &remaining);
12292
12293          if (n_received <= 0) {
12294             status = SS_ABORT;
12295             cm_msg(MERROR, "rpc_server_receive", "recv_tcp_server() returned %d, abort",
12296                    n_received);
12297             goto error;
12298          }
12299
12300          rpc_set_server_acception(index + 1);
12301
12302          if (_server_acception[index].remote_hw_type == DR_ASCII)
12303             status = rpc_execute_ascii(_server_acception[index].recv_sock,
12304                                        _net_recv_buffer);
12305          else
12306             status = rpc_execute(_server_acception[index].recv_sock,
12307                                  _net_recv_buffer,
12308                                  _server_acception[index].convert_flags);
12309
12310          if (status == SS_ABORT) {
12311             cm_msg(MERROR, "rpc_server_receive", "rpc_execute() returned %d, abort",
12312                    status);
12313             goto error;
12314          }
12315
12316          if (status == SS_EXIT || status == RPC_SHUTDOWN) {
12317             if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE)
12318                rpc_debug_printf("Connection to %s:%s closed\n",
12319                       _server_acception[index].host_name,
12320                       _server_acception[index].prog_name);
12321             goto exit;
12322          }
12323
12324       } while (remaining);
12325    } else {
12326       /* receive event */
12327       if (sock == _server_acception[index].event_sock) {
12328          start_time = ss_millitime();
12329
12330          do {
12331             n_received =
12332                 recv_event_server(index, _net_recv_buffer, NET_BUFFER_SIZE, 0,
12333                                   &remaining);
12334
12335             if (n_received <= 0) {
12336                status = SS_ABORT;
12337                cm_msg(MERROR, "rpc_server_receive",
12338                       "recv_event_server() returned %d, abort", n_received);
12339                goto error;
12340             }
12341
12342             /* send event to buffer */
12343             pbh = (INT *) _net_recv_buffer;
12344             pevent = (EVENT_HEADER *) (pbh + 1);
12345
12346             status =
12347                 bm_send_event(*pbh, pevent, pevent->data_size + sizeof(EVENT_HEADER),
12348                               SYNC);
12349             if (status != BM_SUCCESS)
12350                cm_msg(MERROR, "rpc_server_receive", "bm_send_event() returned %d",
12351                       status);
12352
12353             /* repeat for maximum 0.5 sec */
12354          } while (ss_millitime() - start_time < 500 && remaining);
12355       }
12356    }
12357
12358    return RPC_SUCCESS;
12359
12360  error:
12361
12362    strcpy(str, _server_acception[index].host_name);
12363    if (strchr(str, '.'))
12364       *strchr(str, '.') = 0;
12365    cm_msg(MTALK, "rpc_server_receive", "Program %s on host %s aborted",
12366           _server_acception[index].prog_name, str);
12367
12368  exit:
12369
12370    /* disconnect from experiment as MIDAS server */
12371    if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE) {
12372       HNDLE hDB, hKey;
12373
12374       cm_get_experiment_database(&hDB, &hKey);
12375
12376       /* only disconnect from experiment if previously connected.
12377          Necessary for pure RPC servers (RPC_SRVR) */
12378       if (hDB) {
12379 #ifdef LOCAL_ROUTINES
12380          ss_alarm(0, cm_watchdog);
12381 #endif
12382
12383          cm_delete_client_info(hDB, 0);
12384
12385          bm_close_all_buffers();
12386          db_close_all_databases();
12387
12388          rpc_deregister_functions();
12389
12390          cm_set_experiment_database(0, 0);
12391
12392          _msg_buffer = 0;
12393       }
12394    }
12395
12396    /* close server connection */
12397    if (_server_acception[index].recv_sock)
12398       closesocket(_server_acception[index].recv_sock);
12399    if (_server_acception[index].send_sock)
12400       closesocket(_server_acception[index].send_sock);
12401    if (_server_acception[index].event_sock)
12402       closesocket(_server_acception[index].event_sock);
12403
12404    /* free TCP cache */
12405    M_FREE(_server_acception[index].net_buffer);
12406    _server_acception[index].net_buffer = NULL;
12407
12408    /* mark this entry as invalid */
12409    memset(&_server_acception[index], 0, sizeof(RPC_SERVER_ACCEPTION));
12410
12411    /* signal caller a shutdonw */
12412    if (status == RPC_SHUTDOWN)
12413       return status;
12414
12415    /* don't abort if other than main connection is broken */
12416    if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_REMOTE)
12417       return SS_SUCCESS;
12418
12419    return status;
12420 }
INT rpc_server_shutdown (void)
Definition at line 12424 of file midas.c.
References _server_registered, closesocket, RPC_SERVER_ACCEPTION::event_sock, FALSE, i, MAX_RPC_CONNECTION, RPC_SERVER_ACCEPTION::recv_sock, RPC_SUCCESS, RPC_SERVER_ACCEPTION::send_sock, and ss_suspend_exit().
Referenced by cm_disconnect_experiment(), and main().
12427          : rpc_server_shutdown
12428
12429   Purpose: Shutdown RPC server, abort all connections
12430
12431   Input:
12432     none
12433
12434   Output:
12435     none
12436
12437   Function value:
12438     RPC_SUCCESS             Successful completion
12439
12440 \********************************************************************/
12441 {
12442    INT i;
12443    struct linger ling;
12444
12445    /* close all open connections */
12446    for (i = 0; i < MAX_RPC_CONNECTION; i++)
12447       if (_server_acception[i].recv_sock != 0) {
12448          /* lingering needed for PCTCP */
12449          ling.l_onoff = 1;
12450          ling.l_linger = 0;
12451          setsockopt(_server_acception[i].recv_sock,
12452                     SOL_SOCKET, SO_LINGER, (char *) &ling, sizeof(ling));
12453          closesocket(_server_acception[i].recv_sock);
12454
12455          if (_server_acception[i].send_sock) {
12456             setsockopt(_server_acception[i].send_sock,
12457                        SOL_SOCKET, SO_LINGER, (char *) &ling, sizeof(ling));
12458             closesocket(_server_acception[i].send_sock);
12459          }
12460
12461          if (_server_acception[i].event_sock) {
12462             setsockopt(_server_acception[i].event_sock,
12463                        SOL_SOCKET, SO_LINGER, (char *) &ling, sizeof(ling));
12464             closesocket(_server_acception[i].event_sock);
12465          }
12466
12467          _server_acception[i].recv_sock = 0;
12468          _server_acception[i].send_sock = 0;
12469          _server_acception[i].event_sock = 0;
12470       }
12471
12472    if (_lsock) {
12473       closesocket(_lsock);
12474       _lsock = 0;
12475       _server_registered = FALSE;
12476    }
12477
12478    /* free suspend structures */
12479    ss_suspend_exit();
12480
12481    return RPC_SUCCESS;
12482 }
INT rpc_server_thread (void * pointer)
Definition at line 12166 of file midas.c.
References al_check(), cm_set_experiment_mutex(), rpc_check_channels(), rpc_is_remote(), RPC_NET_ERROR, rpc_server_callback(), RPC_SUCCESS, SS_ABORT, SS_EXIT, ss_mutex_create(), ss_suspend(), ss_suspend_exit(), ss_time(), and status.
Referenced by main(), and rpc_server_accept().
12169          : rpc_server_thread
12170
12171   Purpose: New thread for a multi-threaded server. Callback to the
12172            client and process RPC requests.
12173
12174   Input:
12175     vcoid  pointer          pointer to callback_addr structure.
12176
12177   Output:
12178     none
12179
12180   Function value:
12181     RPC_SUCCESS             Successful completion
12182
12183 \********************************************************************/
12184 {
12185    struct callback_addr callback;
12186    int status, mutex_alarm, mutex_elog;
12187    static DWORD last_checked = 0;
12188
12189    memcpy(&callback, pointer, sizeof(callback));
12190
12191    status = rpc_server_callback(&callback);
12192
12193    if (status != RPC_SUCCESS)
12194       return status;
12195
12196    /* create alarm and elog mutexes */
12197    ss_mutex_create("ALARM", &mutex_alarm);
12198    ss_mutex_create("ELOG", &mutex_elog);
12199    cm_set_experiment_mutex(mutex_alarm, mutex_elog);
12200
12201    do {
12202       status = ss_suspend(5000, 0);
12203
12204       if (rpc_check_channels() == RPC_NET_ERROR)
12205          break;
12206
12207       /* check alarms every 10 seconds */
12208       if (!rpc_is_remote() && ss_time() - last_checked > 10) {
12209          al_check();
12210          last_checked = ss_time();
12211       }
12212
12213    } while (status != SS_ABORT && status != SS_EXIT);
12214
12215    /* delete entry in suspend table for this thread */
12216    ss_suspend_exit();
12217
12218    return RPC_SUCCESS;
12219 }
INT rpc_set_debug (void(*)(char *) func, INT mode)
Definition at line 9420 of file midas.c.
References _debug_mode, _debug_print, and RPC_SUCCESS.
Referenced by main().
         : rpc_set_debug
  Purpose: Set a function which is called on every RPC call to
           display the function name and parameters of the RPC
           call.
  Input:
   void *func(char*)        Pointer to function.
   INT  mode                Debug mode
  Output:
    none
  Function value:
    RPC_SUCCESS             Successful completion
\********************************************************************/
{
   _debug_print = func;
   _debug_mode = mode;
   return RPC_SUCCESS;
}
INT rpc_set_name (char * name)
Definition at line 9394 of file midas.c.
References RPC_SUCCESS.
Referenced by cam_init_rpc(), cm_connect_experiment1(), cm_set_client_info(), and rpc_register_client().
         : rpc_set_name
  Purpose: Set name of actual program for further rpc connections
  Input:
   char *name               Program name, up to NAME_LENGTH chars,
                            no blanks
  Output:
    none
  Function value:
    RPC_SUCCESS             Successful completion
\********************************************************************/
{
   strcpy(_client_name, name);
   return RPC_SUCCESS;
}
INT rpc_set_opt_tcp_size (INT tcp_size)
Definition at line 10087 of file midas.c.
Referenced by scheduler().
10088 {
10089    INT old;
10090
10091    old = _opt_tcp_size;
10092    _opt_tcp_size = tcp_size;
10093    return old;
10094 }
INT rpc_set_option (HNDLE hConn, INT item, INT value)
dox Set RPC option
Parameters:
hConn RPC connection handle
item One of RPC_Oxxx
value Value to set
Returns:
RPC_SUCCESS
Definition at line 9211 of file midas.c.
References cm_msg, MERROR, RPC_NODELAY, RPC_OTIMEOUT, RPC_OTRANSPORT, RPC_CLIENT_CONNECTION::rpc_timeout, RPC_SERVER_CONNECTION::rpc_timeout, RPC_SERVER_CONNECTION::send_sock, RPC_CLIENT_CONNECTION::transport, and RPC_SERVER_CONNECTION::transport.
Referenced by cm_transition(), command_loop(), db_send_changed_records(), main(), rpc_client_disconnect(), rpc_master_bor(), rpc_slave_bor(), scheduler(), and update_odb().
{
   switch (item) {
   case RPC_OTIMEOUT:
      if (hConn == -1)
         _server_connection.rpc_timeout = value;
      else
         _client_connection[hConn - 1].rpc_timeout = value;
      break;
   case RPC_OTRANSPORT:
      if (hConn == -1)
         _server_connection.transport = value;
      else
         _client_connection[hConn - 1].transport = value;
      break;
   case RPC_NODELAY:
      if (hConn == -1)
         setsockopt(_server_connection.send_sock, IPPROTO_TCP,
                    TCP_NODELAY, (char *) &value, sizeof(value));
      else
         setsockopt(_client_connection[hConn - 1].send_sock, IPPROTO_TCP,
                    TCP_NODELAY, (char *) &value, sizeof(value));
      break;
   default:
      cm_msg(MERROR, "rpc_set_option", "invalid argument");
      break;
   }
   return 0;
}
INT rpc_set_server_acception (INT index)
Definition at line 9068 of file midas.c.
References RPC_SUCCESS.
Referenced by rpc_client_accept(), rpc_server_callback(), and rpc_server_receive().
         : rpc_set_server_acception
  Purpose: Set actual RPC server connection index
  Input:
    INT  index              Server index
  Output:
    none
  Function value:
    RPC_SUCCESS             Successful completion
\********************************************************************/
{
   _server_acception_index = index;
   return RPC_SUCCESS;
}
INT rpc_set_server_option (INT item, PTYPE value)
Definition at line 9308 of file midas.c.
References RPC_SERVER_ACCEPTION::client_handle, RPC_SERVER_ACCEPTION::convert_flags, i, MAX, MAX_RPC_CONNECTION, RPC_SERVER_ACCEPTION::odb_handle, RPC_CLIENT_HANDLE, RPC_CONVERT_FLAGS, RPC_ODB_HANDLE, RPC_OSERVER_NAME, RPC_OSERVER_TYPE, RPC_SUCCESS, RPC_WATCHDOG_TIMEOUT, ss_gettid(), ST_MTHREAD, ST_REMOTE, ST_SINGLE, and RPC_SERVER_ACCEPTION::watchdog_timeout.
Referenced by cm_set_client_info(), cm_set_watchdog_params(), main(), rpc_client_accept(), rpc_register_server(), and rpc_server_callback().
         : rpc_set_server_option
  Purpose: Set RPC option for server connection
  Input:
   INT  item               One of RPC_Oxxx
   INT  value              Value to set
  Output:
    none
  Function value:
    RPC_SUCCESS             Successful completion
\********************************************************************/
{
   INT i;
   if (item == RPC_OSERVER_TYPE) {
      _server_type = value;
      return RPC_SUCCESS;
   }
   if (item == RPC_OSERVER_NAME) {
      strcpy(_server_name, (char *) value);
      return RPC_SUCCESS;
   }
   /* check which connections belongs to caller */
   if (_server_type == ST_MTHREAD) {
      for (i = 0; i < MAX_RPC_CONNECTION; i++)
         if (_server_acception[i].tid == ss_gettid())
            break;
   } else if (_server_type == ST_SINGLE || _server_type == ST_REMOTE)
      i = MAX(0, _server_acception_index - 1);
   else
      i = 0;
   switch (item) {
   case RPC_CONVERT_FLAGS:
      _server_acception[i].convert_flags = value;
      break;
   case RPC_ODB_HANDLE:
      _server_acception[i].odb_handle = value;
      break;
   case RPC_CLIENT_HANDLE:
      _server_acception[i].client_handle = value;
      break;
   case RPC_WATCHDOG_TIMEOUT:
      _server_acception[i].watchdog_timeout = value;
      break;
   }
   return RPC_SUCCESS;
}
char* rpc_tid_name (INT id)
Definition at line 8170 of file midas.c.
References TID_LAST, and tid_name.
Referenced by ascii_write(), command_loop(), db_get_data(), db_get_data1(), db_get_data_index(), db_get_value(), db_save_xml_key(), db_set_data(), db_set_data_index(), db_set_data_index2(), db_set_value(), dump_write(), print_key(), scan_tree(), show_set_page(), and write_event_ascii().
{
   if (id < TID_LAST)
      return tid_name[id];
   else
      return "<unknown>";
}
INT rpc_tid_size (INT id)
Definition at line 8162 of file midas.c.
References TID_LAST, and tid_size.
Referenced by ascii_write(), db_create_key(), db_get_value(), db_paste(), db_recurse_record_tree(), db_set_value(), db_sscanf(), display_range_hist(), display_single_hist(), dump_write(), hs_dump(), hs_read(), mana_init(), register_equipment(), rpc_server_dispatch(), set_key(), show_set_page(), update_odb(), write_event_ascii(), write_event_hbook(), and write_event_odb().
{
   if (id < TID_LAST)
      return tid_size[id];
   return 0;
}
void rpc_va_arg (va_list * arg_ptr, INT arg_type, void * arg)
Definition at line 9479 of file midas.c.
References TID_ARRAY, TID_BOOL, TID_BYTE, TID_CHAR, TID_DOUBLE, TID_DWORD, TID_FLOAT, TID_INT, TID_SBYTE, TID_SHORT, and TID_WORD.
Referenced by rpc_call(), and rpc_client_call().
{
   switch (arg_type) {
      /* On the stack, the minimum parameter size is sizeof(int).
         To avoid problems on little endian systems, treat all
         smaller parameters as int's */
   case TID_BYTE:
   case TID_SBYTE:
   case TID_CHAR:
   case TID_WORD:
   case TID_SHORT:
      *((int *) arg) = va_arg(*arg_ptr, int);
      break;
   case TID_INT:
   case TID_BOOL:
      *((INT *) arg) = va_arg(*arg_ptr, INT);
      break;
   case TID_DWORD:
      *((DWORD *) arg) = va_arg(*arg_ptr, DWORD);
      break;
      /* float variables are passed as double by the compiler */
   case TID_FLOAT:
      *((float *) arg) = (float) va_arg(*arg_ptr, double);
      break;
   case TID_DOUBLE:
      *((double *) arg) = va_arg(*arg_ptr, double);
      break;
   case TID_ARRAY:
      *((char **) arg) = va_arg(*arg_ptr, char *);
      break;
   }
}
void rpc_vax2ieee_double (double * var)
Definition at line 8038 of file midas.c.
Referenced by rpc_convert_single().
{
   unsigned short int i1, i2, i3, i4;
   /* swap words */
   i1 = *((short int *) (var) + 3);
   i2 = *((short int *) (var) + 2);
   i3 = *((short int *) (var) + 1);
   i4 = *((short int *) (var));
   /* correct exponent */
   if (i4 != 0)
      i4 -= 0x20;
   *((short int *) (var) + 3) = i4;
   *((short int *) (var) + 2) = i3;
   *((short int *) (var) + 1) = i2;
   *((short int *) (var)) = i1;
}
void rpc_vax2ieee_float (float * var)
Definition at line 8021 of file midas.c.
Referenced by rpc_convert_single().
{
   unsigned short int lo, hi;
   /* swap hi and lo word */
   lo = *((short int *) (var) + 1);
   hi = *((short int *) (var));
   /* correct exponent */
   if (hi != 0)
      hi -= 0x100;
   *((short int *) (var) + 1) = hi;
   *((short int *) (var)) = lo;
}
Variable Documentation
RPC_CLIENT_CONNECTION _client_connection[MAX_RPC_CONNECTION]
dox
Definition at line 7956 of file midas.c.
int _lsock [static]
Definition at line 7959 of file midas.c.
int _opt_tcp_size = OPT_TCP_SIZE
Definition at line 7967 of file midas.c.
RPC_SERVER_ACCEPTION _server_acception[MAX_RPC_CONNECTION]
Definition at line 7960 of file midas.c.
INT _server_acception_index = 0 [static]
Definition at line 7961 of file midas.c.
RPC_SERVER_CONNECTION _server_connection
Definition at line 7957 of file midas.c.
char _server_name[256] [static]
Definition at line 7963 of file midas.c.
INT _server_type [static]
Definition at line 7962 of file midas.c.
RPC_LIST* rpc_list = NULL [static]
Definition at line 7965 of file midas.c.
TR_FIFO tr_fifo[10] [static]
Definition at line 10344 of file midas.c.
int trf_rp [static]
Definition at line 10345 of file midas.c.
int trf_wp [static]
Definition at line 10345 of file midas.c.