AlcapDAQ:Rootana: Midas Bank Functions (bk_xxx)
Midas Bank Functions (bk_xxx)
[The midas.h & midas.c]
Functions
void bk_init (void *event)
BOOL bk_is32 (void *event)
void bk_init32 (void *event)
INT bk_size (void *event)
void bk_create (void *event, const char *name, WORD type, void *pdata)
int bk_delete (void *event, const char *name)
INT bk_close (void *event, void *pdata)
INT bk_list (void *event, char *bklist)
INT bk_locate (void *event, const char *name, void *pdata)
INT bk_find (BANK_HEADER *pbkh, const char *name, DWORD *bklen, DWORD *bktype, void **pdata)
INT bk_iterate (void *event, BANK **pbk, void *pdata)
INT bk_iterate32 (void *event, BANK32 **pbk, void *pdata)
INT bk_swap (void *event, BOOL force)
Detailed Description
dox dox dox
Function Documentation
INT bk_close (void * event, void * pdata)
dox Close the Midas bank priviously created by bk_create(). The data pointer pdata must be obtained by bk_create() and used as an address to fill a bank. It is incremented with every value written to the bank and finally points to a location just after the last byte of the bank. It is then passed to bk_close() to finish the bank creation
Parameters:
event pointer to current composed event
pdata pointer to the data
Returns:
number of bytes contained in bank
Definition at line 12826 of file midas.c.
References ALIGN8, BANK_FORMAT_32BIT, BANK::data_size, BANK32::data_size, data_size, BANK::name, BANK32::name, TID_STRUCT, BANK::type, and BANK32::type.
Referenced by adc_calib(), adc_summing(), caenV767_read1(), cd_gen_read(), cd_hv_read(), cd_multi_read(), compress_bank(), compress_event(), compress_event_skim(), decompress(), dl40x_read(), dt5720_read(), expand_bank(), expand_event(), ge_ln2_read(), lrs2249_read1(), MCaenCompProcessRaw(), new_fadc_read(), read_deferred_event(), read_large_event(), read_mantrig_event(), read_scaler_event(), read_separator_event(), read_tiny_event(), read_trigger_event(), s500_read(), scaler_accum(), sis3600_read1(), MqlArray< T >::toBank(), v1724_read(), vacuum_gauge_read(), write_event_midas(), and yb_file_fragment().
12827 {
12828    if (((BANK_HEADER *) event)->flags & BANK_FORMAT_32BIT) {
12829       BANK32 *pbk32;
12830
12831       pbk32 =
12832           (BANK32 *) ((char *) (((BANK_HEADER *) event) + 1) +
12833                       ((BANK_HEADER *) event)->data_size);
12834       pbk32->data_size = (DWORD) (INT) pdata - (INT) (pbk32 + 1);
12835       if (pbk32->type == TID_STRUCT && pbk32->data_size == 0)
12836          printf("Warning: bank %c%c%c%c has zero size\n",
12837                 pbk32->name[0], pbk32->name[1], pbk32->name[2], pbk32->name[3]);
12838       ((BANK_HEADER *) event)->data_size += sizeof(BANK32) + ALIGN8(pbk32->data_size);
12839       return pbk32->data_size;
12840    } else {
12841       BANK *pbk;
12842
12843       pbk =
12844           (BANK *) ((char *) (((BANK_HEADER *) event) + 1) +
12845                     ((BANK_HEADER *) event)->data_size);
12846       pbk->data_size = (WORD) (INT) pdata - (INT) (pbk + 1);
12847       if (pbk->type == TID_STRUCT && pbk->data_size == 0)
12848          printf("Warning: bank %c%c%c%c has zero size\n",
12849                 pbk->name[0], pbk->name[1], pbk->name[2], pbk->name[3]);
12850       ((BANK_HEADER *) event)->data_size += sizeof(BANK) + ALIGN8(pbk->data_size);
12851       return pbk->data_size;
12852    }
12853 }
void bk_create (void * event, const char * name, WORD type, void * pdata)
Create a Midas bank. The data pointer pdata must be used as an address to fill a bank. It is incremented with every value written to the bank and finally points to a location just after the last byte of the bank. It is then passed to the function bk_close() to finish the bank creation.
INT *pdata;
bk_init(pevent);
bk_create(pevent, "ADC0", TID_INT, &pdata);
*pdata++ = 123
*pdata++ = 456
bk_close(pevent, pdata);
Parameters:
event pointer to the data area
name of the bank, must be exactly 4 charaters
type type of bank, one of the Midas_Data_Types values defined in midas.h
pdata pointer to the data area of the newly created bank
Returns:
void
Definition at line 12705 of file midas.c.
References BANK_FORMAT_32BIT, BANK::data_size, BANK32::data_size, data_size, BANK::name, BANK32::name, BANK::type, and BANK32::type.
Referenced by adc_calib(), adc_summing(), caenV767_read1(), cd_gen_read(), cd_hv_read(), cd_multi_read(), compress_bank(), compress_event(), compress_event_skim(), decompress(), dl40x_read(), dt5720_read(), expand_bank(), expand_event(), ge_ln2_read(), lrs2249_read1(), MCaenCompProcessRaw(), new_fadc_read(), read_deferred_event(), read_large_event(), read_mantrig_event(), read_scaler_event(), read_separator_event(), read_tiny_event(), read_trigger_event(), s500_read(), scaler_accum(), sis3600_read1(), MqlArray< T >::toBank(), v1724_read(), vacuum_gauge_read(), write_event_midas(), and yb_file_fragment().
12706 {
12707    if (((BANK_HEADER *) event)->flags & BANK_FORMAT_32BIT) {
12708       BANK32 *pbk32;
12709
12710       pbk32 =
12711           (BANK32 *) ((char *) (((BANK_HEADER *) event) + 1) +
12712                       ((BANK_HEADER *) event)->data_size);
12713       strncpy(pbk32->name, name, 4);
12714       pbk32->type = type;
12715       pbk32->data_size = 0;
12716       *((void **) pdata) = pbk32 + 1;
12717    } else {
12718       BANK *pbk;
12719
12720       pbk =
12721           (BANK *) ((char *) (((BANK_HEADER *) event) + 1) +
12722                     ((BANK_HEADER *) event)->data_size);
12723       strncpy(pbk->name, name, 4);
12724       pbk->type = type;
12725       pbk->data_size = 0;
12726       *((void **) pdata) = pbk + 1;
12727    }
12728 }
int bk_delete (void * event, const char * name)
dox
Definition at line 12736 of file midas.c.
References ALIGN8, BANK_FORMAT_32BIT, CM_SUCCESS, BANK::data_size, data_size, BANK32::data_size, BANK::name, and BANK32::name.
Referenced by decompress().
12739          : bk_delete
12740
12741   Purpose: Delete a MIDAS bank inside an event
12742
12743   Input:
12744     void   *event           pointer to the event
12745     char   *name            Name of bank (exactly four letters)
12746
12747   Function value:
12748     CM_SUCCESS              Bank has been deleted
12749     0                       Bank has not been found
12750
12751 \********************************************************************/
12752 {
12753    BANK *pbk;
12754    BANK32 *pbk32;
12755    DWORD dname;
12756    int remaining;
12757
12758    if (((BANK_HEADER *) event)->flags & BANK_FORMAT_32BIT) {
12759       /* locate bank */
12760       pbk32 = (BANK32 *) (((BANK_HEADER *) event) + 1);
12761       strncpy((char *) &dname, name, 4);
12762       do {
12763          if (*((DWORD *) pbk32->name) == dname) {
12764             /* bank found, delete it */
12765             remaining =
12766                 (int) ((char *) event + ((BANK_HEADER *) event)->data_size +
12767                        sizeof(BANK_HEADER)) - (int) ((char *) (pbk32 + 1) +
12768                                                      ALIGN8(pbk32->data_size));
12769
12770             /* reduce total event size */
12771             ((BANK_HEADER *) event)->data_size -=
12772                 sizeof(BANK32) + ALIGN8(pbk32->data_size);
12773
12774             /* copy remaining bytes */
12775             if (remaining > 0)
12776                memcpy(pbk32, (char *) (pbk32 + 1) + ALIGN8(pbk32->data_size), remaining);
12777             return CM_SUCCESS;
12778          }
12779
12780          pbk32 = (BANK32 *) ((char *) (pbk32 + 1) + ALIGN8(pbk32->data_size));
12781       } while ((DWORD) pbk32 - (DWORD) event <
12782                ((BANK_HEADER *) event)->data_size + sizeof(BANK_HEADER));
12783    } else {
12784       /* locate bank */
12785       pbk = (BANK *) (((BANK_HEADER *) event) + 1);
12786       strncpy((char *) &dname, name, 4);
12787       do {
12788          if (*((DWORD *) pbk->name) == dname) {
12789             /* bank found, delete it */
12790             remaining =
12791                 (int) ((char *) event + ((BANK_HEADER *) event)->data_size +
12792                        sizeof(BANK_HEADER)) - (int) ((char *) (pbk + 1) +
12793                                                      ALIGN8(pbk->data_size));
12794
12795             /* reduce total event size */
12796             ((BANK_HEADER *) event)->data_size -= sizeof(BANK) + ALIGN8(pbk->data_size);
12797
12798             /* copy remaining bytes */
12799             if (remaining > 0)
12800                memcpy(pbk, (char *) (pbk + 1) + ALIGN8(pbk->data_size), remaining);
12801             return CM_SUCCESS;
12802          }
12803
12804          pbk = (BANK *) ((char *) (pbk + 1) + ALIGN8(pbk->data_size));
12805       } while ((DWORD) pbk - (DWORD) event <
12806                ((BANK_HEADER *) event)->data_size + sizeof(BANK_HEADER));
12807    }
12808
12809    return 0;
12810 }
INT bk_find (BANK_HEADER * pbkh, const char * name, DWORD * bklen, DWORD * bktype, void ** pdata)
Finds a MIDAS bank of given name inside an event.
Parameters:
pbkh pointer to current composed event
name bank name to look for
bklen number of elemtents in bank
bktype bank type, one of TID_xxx
pdata pointer to data area of bank, NULL if bank not found
Returns:
1 if bank found, 0 otherwise
Definition at line 12973 of file midas.c.
References ALIGN8, bk_is32(), BANK::data_size, data_size, BANK32::data_size, BANK::name, BANK32::name, tid_size, BANK::type, and BANK32::type.
Referenced by process_event(), and replog().
12975 {
12976    BANK *pbk;
12977    BANK32 *pbk32;
12978    DWORD dname;
12979
12980    if (bk_is32(pbkh)) {
12981       pbk32 = (BANK32 *) (pbkh + 1);
12982       strncpy((char *) &dname, name, 4);
12983       do {
12984          if (*((DWORD *) pbk32->name) == dname) {
12985             *((void **) pdata) = pbk32 + 1;
12986             if (tid_size[pbk32->type & 0xFF] == 0)
12987                *bklen = pbk32->data_size;
12988             else
12989                *bklen = pbk32->data_size / tid_size[pbk32->type & 0xFF];
12990
12991             *bktype = pbk32->type;
12992             return 1;
12993          }
12994          pbk32 = (BANK32 *) ((char *) (pbk32 + 1) + ALIGN8(pbk32->data_size));
12995       } while ((DWORD) pbk32 - (DWORD) pbkh < pbkh->data_size + sizeof(BANK_HEADER));
12996    } else {
12997       pbk = (BANK *) (pbkh + 1);
12998       strncpy((char *) &dname, name, 4);
12999       do {
13000          if (*((DWORD *) pbk->name) == dname) {
13001             *((void **) pdata) = pbk + 1;
13002             if (tid_size[pbk->type & 0xFF] == 0)
13003                *bklen = pbk->data_size;
13004             else
13005                *bklen = pbk->data_size / tid_size[pbk->type & 0xFF];
13006
13007             *bktype = pbk->type;
13008             return 1;
13009          }
13010          pbk = (BANK *) ((char *) (pbk + 1) + ALIGN8(pbk->data_size));
13011       } while ((DWORD) pbk - (DWORD) pbkh < pbkh->data_size + sizeof(BANK_HEADER));
13012    }
13013
13014    /* bank not found */
13015    *((void **) pdata) = NULL;
13016    return 0;
13017 }
void bk_init (void * event)
Initializes an event for Midas banks structure. Before banks can be created in an event, bk_init() has to be called first.
Parameters:
event pointer to the area of event
Definition at line 12623 of file midas.c.
References BANK_FORMAT_VERSION.
Referenced by cd_gen_read(), cd_hv_read(), cd_multi_read(), ge_ln2_read(), read_deferred_event(), read_mantrig_event(), read_scaler_event(), read_separator_event(), read_temperature_probe(), read_tiny_event(), read_trigger_event(), vacuum_gauge_read(), write_event_midas(), and yb_file_fragment().
12624 {
12625    ((BANK_HEADER *) event)->data_size = 0;
12626    ((BANK_HEADER *) event)->flags = BANK_FORMAT_VERSION;
12627 }
void bk_init32 (void * event)
dox Initializes an event for Midas banks structure for large bank size (> 32KBytes) Before banks can be created in an event, bk_init32() has to be called first.
Parameters:
event pointer to the area of event
Returns:
void
Definition at line 12664 of file midas.c.
References BANK_FORMAT_32BIT, and BANK_FORMAT_VERSION.
Referenced by dt5720_read(), eb_user(), main(), new_fadc_read(), read_large_event(), read_periodic_event(), read_trigger_event(), rpc_end_of_cycle(), v1724_read(), and write_event_midas().
12665 {
12666    ((BANK_HEADER *) event)->data_size = 0;
12667    ((BANK_HEADER *) event)->flags = BANK_FORMAT_VERSION | BANK_FORMAT_32BIT;
12668 }
BOOL bk_is32 (void * event)
dox
Definition at line 12633 of file midas.c.
References BANK_FORMAT_32BIT.
Referenced by ascii_write(), bk_find(), bk_list(), bk_locate(), dump_write(), update_odb(), write_event_ascii(), write_event_hbook(), write_event_midas(), write_event_odb(), yb_any_bank_display(), and yb_any_bank_event_display().
12636          : bk_is32
12637
12638   Purpose: Return true if banks inside event are 32-bit banks
12639
12640   Input:
12641     void   *event           pointer to the event
12642
12643   Output:
12644     none
12645
12646   Function value:
12647     none
12648
12649 \********************************************************************/
12650 {
12651    return ((((BANK_HEADER *) event)->flags & BANK_FORMAT_32BIT) > 0);
12652 }
INT bk_iterate (void * event, BANK ** pbk, void * pdata)
Iterates through banks inside an event. The function can be used to enumerate all banks of an event. The returned pointer to the bank header has following structure:
typedef struct {
char   name[4];
WORD   type;
WORD   data_size;
} BANK;
where type is a TID_xxx value and data_size the size of the bank in bytes.
BANK *pbk;
INT  size;
void *pdata;
char name[5];
pbk = NULL;
do
{
 size = bk_iterate(event, &pbk, &pdata);
 if (pbk == NULL)
  break;
 *((DWORD *)name) = *((DWORD *)(pbk)->name);
 name[4] = 0;
 printf("bank %s found\n", name);
} while(TRUE);
Parameters:
event Pointer to data area of event.
pbk pointer to the bank header, must be NULL for the first call to this function.
pdata Pointer to the bank header, must be NULL for the first call to this function
Returns:
Size of bank in bytes
Definition at line 13055 of file midas.c.
References ALIGN8, BANK::data_size, and data_size.
Referenced by ascii_write(), bk_list(), dump_write(), update_odb(), write_event_ascii(), write_event_hbook(), write_event_midas(), write_event_odb(), and yb_any_bank_event_display().
13056 {
13057    if (*pbk == NULL)
13058       *pbk = (BANK *) (((BANK_HEADER *) event) + 1);
13059    else
13060       *pbk = (BANK *) ((char *) (*pbk + 1) + ALIGN8((*pbk)->data_size));
13061
13062    *((void **) pdata) = (*pbk) + 1;
13063
13064    if ((DWORD) * pbk - (DWORD) event >=
13065        ((BANK_HEADER *) event)->data_size + sizeof(BANK_HEADER)) {
13066       *pbk = *((BANK **) pdata) = NULL;
13067       return 0;
13068    }
13069
13070    return (*pbk)->data_size;
13071 }
INT bk_iterate32 (void * event, BANK32 ** pbk, void * pdata)
dox
Definition at line 13078 of file midas.c.
References ALIGN8, BANK32::data_size, and data_size.
Referenced by ascii_write(), bk_list(), compress_event(), compress_event_skim(), dump_write(), expand_event(), print_diag_output(), update_odb(), write_event_ascii(), write_event_hbook(), write_event_midas(), write_event_odb(), and yb_any_bank_event_display().
13081          : bk_iterate
13082
13083   Purpose: Iterate through 32 bit MIDAS banks inside an event
13084
13085   Input:
13086     void   *event           pointer to the event
13087     BANK   **pbk32          must be NULL for the first call to bk_iterate
13088
13089   Output:
13090     BANK   **pbk            pointer to the bank header
13091     void   *pdata           pointer to data area of the bank
13092
13093   Function value:
13094     INT    size of the bank in bytes
13095
13096 \********************************************************************/
13097 {
13098    if (*pbk == NULL)
13099       *pbk = (BANK32 *) (((BANK_HEADER *) event) + 1);
13100    else
13101       *pbk = (BANK32 *) ((char *) (*pbk + 1) + ALIGN8((*pbk)->data_size));
13102
13103    *((void **) pdata) = (*pbk) + 1;
13104
13105    if ((DWORD) * pbk - (DWORD) event >=
13106        ((BANK_HEADER *) event)->data_size + sizeof(BANK_HEADER)) {
13107       *pbk = *((BANK32 **) pdata) = NULL;
13108       return 0;
13109    }
13110
13111    return (*pbk)->data_size;
13112 }
INT bk_list (void * event, char * bklist)
Extract the MIDAS bank name listing of an event. The bklist should be dimensioned with STRING_BANKLIST_MAX which corresponds to a max of BANKLIST_MAX banks (midas.h: 32 banks max).
INT adc_calib(EVENT_HEADER *pheader, void *pevent)
{
  INT    n_adc, nbanks;
  WORD   *pdata;
  char   banklist[STRING_BANKLIST_MAX];
  // Display # of banks and list of banks in the event
  nbanks = bk_list(pevent, banklist);
  printf("#banks:%d List:%s\n", nbanks, banklist);
  // look for ADC0 bank, return if not present
  n_adc = bk_locate(pevent, "ADC0", &pdata);
  ...
}
Parameters:
event pointer to current composed event
bklist returned ASCII string, has to be booked with STRING_BANKLIST_MAX.
Returns:
number of bank found in this event.
Definition at line 12880 of file midas.c.
References BANKLIST_MAX, bk_is32(), bk_iterate(), bk_iterate32(), cm_msg, MINFO, BANK::name, BANK32::name, and size.
Referenced by process_event(), replog(), and yb_any_bank_event_display().
12881 {                               /* Full event */
12882    INT nbk, size;
12883    BANK *pmbk = NULL;
12884    BANK32 *pmbk32 = NULL;
12885    char *pdata;
12886
12887    /* compose bank list */
12888    bklist[0] = 0;
12889    nbk = 0;
12890    do {
12891       /* scan all banks for bank name only */
12892       if (bk_is32(event)) {
12893          size = bk_iterate32(event, &pmbk32, &pdata);
12894          if (pmbk32 == NULL)
12895             break;
12896       } else {
12897          size = bk_iterate(event, &pmbk, &pdata);
12898          if (pmbk == NULL)
12899             break;
12900       }
12901       nbk++;
12902
12903       if (nbk > BANKLIST_MAX) {
12904          cm_msg(MINFO, "bk_list", "over %i banks -> truncated", BANKLIST_MAX);
12905          return (nbk - 1);
12906       }
12907       if (bk_is32(event))
12908          strncat(bklist, (char *) pmbk32->name, 4);
12909       else
12910          strncat(bklist, (char *) pmbk->name, 4);
12911    }
12912    while (1);
12913    return (nbk);
12914 }
INT bk_locate (void * event, const char * name, void * pdata)
Locates a MIDAS bank of given name inside an event.
Parameters:
event pointer to current composed event
name bank name to look for
pdata pointer to data area of bank, NULL if bank not found
Returns:
number of values inside the bank
Definition at line 12924 of file midas.c.
References ALIGN8, bk_is32(), BANK::data_size, data_size, BANK32::data_size, BANK::name, BANK32::name, tid_size, BANK::type, and BANK32::type.
Referenced by adc_calib(), adc_summing(), analyze_trigger_event(), decompress(), MqlArray< T >::fromBank(), make_caen(), make_comp(), MDQ_FADCBufferOverflow(), MDQ_FADCPacketLoss(), MDQ_TDCCheck(), MMuPC1AnalysisC(), MMuSCAnalysisC(), MOctalFADCBufferOverflow(), MOctalFADCPacketLoss(), module_event_caen(), MVacuumHisto(), process_event(), TWFDBankReader::ProcessEvent(), TOctalFADCBankReader::ProcessEvent(), scaler_accum(), yb_file_recompose(), yb_ymfile_open(), and yb_ymfile_update().
12925 {
12926    BANK *pbk;
12927    BANK32 *pbk32;
12928    DWORD dname;
12929
12930    if (bk_is32(event)) {
12931       pbk32 = (BANK32 *) (((BANK_HEADER *) event) + 1);
12932       strncpy((char *) &dname, name, 4);
12933       do {
12934          if (*((DWORD *) pbk32->name) == dname) {
12935             *((void **) pdata) = pbk32 + 1;
12936             if (tid_size[pbk32->type & 0xFF] == 0)
12937                return pbk32->data_size;
12938             return pbk32->data_size / tid_size[pbk32->type & 0xFF];
12939          }
12940          pbk32 = (BANK32 *) ((char *) (pbk32 + 1) + ALIGN8(pbk32->data_size));
12941       } while ((DWORD) pbk32 - (DWORD) event <
12942                ((BANK_HEADER *) event)->data_size + sizeof(BANK_HEADER));
12943    } else {
12944       pbk = (BANK *) (((BANK_HEADER *) event) + 1);
12945       strncpy((char *) &dname, name, 4);
12946       do {
12947          if (*((DWORD *) pbk->name) == dname) {
12948             *((void **) pdata) = pbk + 1;
12949             if (tid_size[pbk->type & 0xFF] == 0)
12950                return pbk->data_size;
12951             return pbk->data_size / tid_size[pbk->type & 0xFF];
12952          }
12953          pbk = (BANK *) ((char *) (pbk + 1) + ALIGN8(pbk->data_size));
12954       } while ((DWORD) pbk - (DWORD) event <
12955                ((BANK_HEADER *) event)->data_size + sizeof(BANK_HEADER));
12956    }
12957
12958    /* bank not found */
12959    *((void **) pdata) = NULL;
12960    return 0;
12961 }
INT bk_size (void * event)
Returns the size of an event containing banks. The total size of an event is the value returned by bk_size() plus the size of the event header (sizeof(EVENT_HEADER)).
Parameters:
event pointer to the area of event
Returns:
number of bytes contained in data area of event
Definition at line 12678 of file midas.c.
Referenced by cd_gen_read(), cd_hv_read(), cd_multi_read(), decompress(), eb_user(), ge_ln2_read(), main(), process_event(), read_deferred_event(), read_large_event(), read_mantrig_event(), read_periodic_event(), read_scaler_event(), read_separator_event(), read_tiny_event(), read_trigger_event(), rpc_end_of_cycle(), vacuum_gauge_read(), write_event_midas(), and yb_file_fragment().
12679 {
12680    return ((BANK_HEADER *) event)->data_size + sizeof(BANK_HEADER);
12681 }
INT bk_swap (void * event, BOOL force)
dox Swaps bytes from little endian to big endian or vice versa for a whole event.
An event contains a flag which is set by bk_init() to identify the endian format of an event. If force is FALSE, this flag is evaluated and the event is only swapped if it is in the "wrong" format for this system. An event can be swapped to the "wrong" format on purpose for example by a front-end which wants to produce events in a "right" format for a back-end analyzer which has different byte ordering.
Parameters:
event pointer to data area of event
force If TRUE, the event is always swapped, if FALSE, the event is only swapped if it is in the wrong format.
Returns:
1==event has been swap, 0==event has not been swapped.
Definition at line 13132 of file midas.c.
References ALIGN8, BANK_FORMAT_32BIT, CM_SUCCESS, BANK::data_size, BANK32::data_size, BANK_HEADER::data_size, DWORD_SWAP, BANK_HEADER::flags, PTYPE, QWORD_SWAP, TID_BOOL, TID_DOUBLE, TID_DWORD, TID_FLOAT, TID_INT, TID_SHORT, TID_WORD, BANK::type, BANK32::type, type, and WORD_SWAP.
Referenced by ascii_write(), dump_write(), eb_mfragment_add(), process_event(), read_midas_event(), source_scan(), and yb_any_event_swap().
13133 {
13134    BANK_HEADER *pbh;
13135    BANK *pbk;
13136    BANK32 *pbk32;
13137    void *pdata;
13138    WORD type;
13139    BOOL b32;
13140
13141    pbh = (BANK_HEADER *) event;
13142
13143    /* only swap if flags in high 16-bit */
13144    if (pbh->flags < 0x10000 && !force)
13145       return 0;
13146
13147    /* swap bank header */
13148    DWORD_SWAP(&pbh->data_size);
13149    DWORD_SWAP(&pbh->flags);
13150
13151    /* check for 32bit banks */
13152    b32 = ((pbh->flags & BANK_FORMAT_32BIT) > 0);
13153
13154    pbk = (BANK *) (pbh + 1);
13155    pbk32 = (BANK32 *) pbk;
13156
13157    /* scan event */
13158    while ((PTYPE) pbk - (PTYPE) pbh < (INT) pbh->data_size + (INT) sizeof(BANK_HEADER)) {
13159       /* swap bank header */
13160       if (b32) {
13161          DWORD_SWAP(&pbk32->type);
13162          DWORD_SWAP(&pbk32->data_size);
13163          pdata = pbk32 + 1;
13164          type = (WORD) pbk32->type;
13165       } else {
13166          WORD_SWAP(&pbk->type);
13167          WORD_SWAP(&pbk->data_size);
13168          pdata = pbk + 1;
13169          type = pbk->type;
13170       }
13171
13172       /* pbk points to next bank */
13173       if (b32) {
13174          pbk32 = (BANK32 *) ((char *) (pbk32 + 1) + ALIGN8(pbk32->data_size));
13175          pbk = (BANK *) pbk32;
13176       } else {
13177          pbk = (BANK *) ((char *) (pbk + 1) + ALIGN8(pbk->data_size));
13178          pbk32 = (BANK32 *) pbk;
13179       }
13180
13181       switch (type) {
13182       case TID_WORD:
13183       case TID_SHORT:
13184          while ((PTYPE) pdata < (PTYPE) pbk) {
13185             WORD_SWAP(pdata);
13186             pdata = (void *) (((WORD *) pdata) + 1);
13187          }
13188          break;
13189
13190       case TID_DWORD:
13191       case TID_INT:
13192       case TID_BOOL:
13193       case TID_FLOAT:
13194          while ((PTYPE) pdata < (PTYPE) pbk) {
13195             DWORD_SWAP(pdata);
13196             pdata = (void *) (((DWORD *) pdata) + 1);
13197          }
13198          break;
13199
13200       case TID_DOUBLE:
13201          while ((PTYPE) pdata < (PTYPE) pbk) {
13202             QWORD_SWAP(pdata);
13203             pdata = (void *) (((double *) pdata) + 1);
13204          }
13205          break;
13206       }
13207    }
13208
13209    return CM_SUCCESS;
13210 }