AlcapDAQ:Rootana: Midas History Functions (hs_xxx)
Midas History Functions (hs_xxx)
[The midas.h & midas.c]
Functions
INT hs_set_path (char *path)
INT hs_open_file (DWORD ltime, char *suffix, INT mode, int *fh)
INT hs_gen_index (DWORD ltime)
INT hs_search_file (DWORD *ltime, INT direction)
INT hs_define_event (DWORD event_id, char *name, TAG *tag, DWORD size)
INT hs_write_event (DWORD event_id, void *data, DWORD size)
INT hs_enum_events (DWORD ltime, char *event_name, DWORD *name_size, INT event_id[], DWORD *id_size)
INT hs_count_events (DWORD ltime, DWORD *count)
INT hs_get_event_id (DWORD ltime, char *name, DWORD *id)
INT hs_count_vars (DWORD ltime, DWORD event_id, DWORD *count)
INT hs_enum_vars (DWORD ltime, DWORD event_id, char *var_name, DWORD *size, DWORD *var_n, DWORD *n_size)
INT hs_get_var (DWORD ltime, DWORD event_id, char *var_name, DWORD *type, INT *n_data)
INT hs_read (DWORD event_id, DWORD start_time, DWORD end_time, DWORD interval, char *tag_name, DWORD var_index, DWORD *time_buffer, DWORD *tbsize, void *data_buffer, DWORD *dbsize, DWORD *type, DWORD *n)
INT hs_dump (DWORD event_id, DWORD start_time, DWORD end_time, DWORD interval, BOOL binary_time)
INT hs_fdump (char *file_name, DWORD id, BOOL binary_time)
Variables
static HISTORY * _history
static INT _history_entries = 0
static char _hs_path_name [MAX_STRING_LENGTH]
Detailed Description
dox dox
Function Documentation
INT hs_count_events (DWORD ltime, DWORD * count)
Definition at line 13907 of file midas.c.
References cm_msg, HS_FILE_ERROR, hs_open_file(), hs_search_file(), HS_SUCCESS, i, j, M_FREE, M_MALLOC, MERROR, n, read, rpc_call(), RPC_HS_COUNT_EVENTS, rpc_is_remote(), status, TELL, and TRUE.
Referenced by display_vars(), query_params(), and rpc_server_dispatch().
13910          : hs_count_events
13911
13912   Purpose: Count number of different events for a given date
13913
13914   Input:
13915     DWORD  ltime            Date at which events should be counted
13916
13917   Output:
13918     DWORD  *count           Number of different events found
13919
13920   Function value:
13921     HS_SUCCESS              Successful completion
13922     HS_FILE_ERROR           Cannot open history file
13923
13924 \********************************************************************/
13925 {
13926    int fh, fhd;
13927    INT status, i, j, n;
13928    DWORD *id;
13929    DEF_RECORD def_rec;
13930
13931    if (rpc_is_remote())
13932       return rpc_call(RPC_HS_COUNT_EVENTS, ltime, count);
13933
13934    /* search latest history file */
13935    status = hs_search_file(&ltime, -1);
13936    if (status != HS_SUCCESS) {
13937       cm_msg(MERROR, "hs_count_events", "cannot find recent history file");
13938       return HS_FILE_ERROR;
13939    }
13940
13941    /* open history and definition files */
13942    hs_open_file(ltime, "hst", O_RDONLY, &fh);
13943    hs_open_file(ltime, "idf", O_RDONLY, &fhd);
13944    if (fh < 0 || fhd < 0) {
13945       cm_msg(MERROR, "hs_count_events", "cannot open index files");
13946       return HS_FILE_ERROR;
13947    }
13948
13949    /* allocate event id array */
13950    lseek(fhd, 0, SEEK_END);
13951    id = (DWORD *) M_MALLOC(TELL(fhd) / sizeof(def_rec) * sizeof(DWORD));
13952    lseek(fhd, 0, SEEK_SET);
13953
13954    /* loop over index file */
13955    n = 0;
13956    do {
13957       /* read definition index record */
13958       j = read(fhd, (char *) &def_rec, sizeof(def_rec));
13959       if (j < (int) sizeof(def_rec))
13960          break;
13961
13962       /* look for existing entries */
13963       for (i = 0; i < n; i++)
13964          if (id[i] == def_rec.event_id)
13965             break;
13966
13967       /* new entry found */
13968       if (i == n) {
13969          id[i] = def_rec.event_id;
13970          n++;
13971       }
13972    } while (TRUE);
13973
13974
13975    M_FREE(id);
13976    close(fh);
13977    close(fhd);
13978    *count = n;
13979
13980    return HS_SUCCESS;
13981 }
INT hs_count_vars (DWORD ltime, DWORD event_id, DWORD * count)
Definition at line 14064 of file midas.c.
References cm_msg, DEF_RECORD::def_offset, DEF_RECORD::event_id, HS_FILE_ERROR, hs_open_file(), hs_search_file(), HS_SUCCESS, i, MERROR, n, read, rpc_call(), RPC_HS_COUNT_VARS, rpc_is_remote(), status, and TELL.
Referenced by display_vars(), query_params(), and rpc_server_dispatch().
14067          : hs_count_vars
14068
14069   Purpose: Count number of variables for a given date and event id
14070
14071   Input:
14072     DWORD  ltime            Date at which tags should be counted
14073
14074   Output:
14075     DWORD  *count           Number of tags
14076
14077   Function value:
14078     HS_SUCCESS              Successful completion
14079     HS_FILE_ERROR           Cannot open history file
14080
14081 \********************************************************************/
14082 {
14083    int fh, fhd;
14084    INT i, n, status;
14085    DEF_RECORD def_rec;
14086    HIST_RECORD rec;
14087
14088    if (rpc_is_remote())
14089       return rpc_call(RPC_HS_COUNT_VARS, ltime, event_id, count);
14090
14091    /* search latest history file */
14092    status = hs_search_file(&ltime, -1);
14093    if (status != HS_SUCCESS) {
14094       cm_msg(MERROR, "hs_count_tags", "cannot find recent history file");
14095       return HS_FILE_ERROR;
14096    }
14097
14098    /* open history and definition files */
14099    hs_open_file(ltime, "hst", O_RDONLY, &fh);
14100    hs_open_file(ltime, "idf", O_RDONLY, &fhd);
14101    if (fh < 0 || fhd < 0) {
14102       cm_msg(MERROR, "hs_count_tags", "cannot open index files");
14103       return HS_FILE_ERROR;
14104    }
14105
14106    /* search last definition */
14107    lseek(fhd, 0, SEEK_END);
14108    n = TELL(fhd) / sizeof(def_rec);
14109    def_rec.event_id = 0;
14110    for (i = n - 1; i >= 0; i--) {
14111       lseek(fhd, i * sizeof(def_rec), SEEK_SET);
14112       read(fhd, (char *) &def_rec, sizeof(def_rec));
14113       if (def_rec.event_id == event_id)
14114          break;
14115    }
14116    if (def_rec.event_id != event_id) {
14117       cm_msg(MERROR, "hs_count_tags", "event %d not found in index file", event_id);
14118       return HS_FILE_ERROR;
14119    }
14120
14121    /* read definition */
14122    lseek(fh, def_rec.def_offset, SEEK_SET);
14123    read(fh, (char *) &rec, sizeof(rec));
14124    *count = rec.data_size / sizeof(TAG);
14125
14126    close(fh);
14127    close(fhd);
14128
14129    return HS_SUCCESS;
14130 }
INT hs_define_event (DWORD event_id, char * name, TAG * tag, DWORD size)
Definition at line 13463 of file midas.c.
References HISTORY::base_time, buffer, HIST_RECORD::data_size, HISTORY::def_fh, DEF_RECORD::def_offset, HISTORY::def_offset, DEF_RECORD::event_id, HISTORY::event_id, HIST_RECORD::event_id, DEF_RECORD::event_name, HISTORY::hist_fh, HS_FILE_ERROR, hs_gen_index(), HS_NO_MEMORY, hs_open_file(), HS_SUCCESS, i, index, HISTORY::index_fh, M_FREE, M_MALLOC, n, HISTORY::n_tag, NAME_LENGTH, read, HIST_RECORD::record_type, RT_DEF, HISTORY::tag, TELL, time, HIST_RECORD::time, and write.
Referenced by generate_hist(), open_history(), rpc_server_dispatch(), and write_hist_speed().
13466          : hs_define_evnet
13467
13468   Purpose: Define a new event for which a history should be recorded.
13469            This routine must be called before any call to
13470            hs_write_event. It also should be called if the definition
13471            of the event has changed.
13472
13473            The event definition is written directly to the history
13474            file. If the definition is identical to a previous
13475            definition, it is not written to the file.
13476
13477
13478   Input:
13479     DWORD  event_id         ID for this event. Must be unique.
13480     char   name             Name of this event
13481     TAG    tag              Tag list containing names and types of
13482                             variables in this event.
13483     DWORD  size             Size of tag array
13484
13485   Output:
13486     <none>
13487
13488   Function value:
13489     HS_SUCCESS              Successful completion
13490     HS_NO_MEMEORY           Out of memory
13491     HS_FILE_ERROR           Cannot open history file
13492
13493 \********************************************************************/
13494 {
13495 /* History events are only written locally (?)
13496
13497   if (rpc_is_remote())
13498     return rpc_call(RPC_HS_DEFINE_EVENT, event_id, name, tag, size);
13499 */
13500    {
13501       HIST_RECORD rec, prev_rec;
13502       DEF_RECORD def_rec;
13503       char str[256], event_name[NAME_LENGTH], *buffer;
13504       int fh, fhi, fhd;
13505       INT i, n, len, index;
13506       struct tm *tmb;
13507
13508       /* allocate new space for the new history descriptor */
13509       if (_history_entries == 0) {
13510          _history = (HISTORY *) M_MALLOC(sizeof(HISTORY));
13511          memset(_history, 0, sizeof(HISTORY));
13512          if (_history == NULL)
13513             return HS_NO_MEMORY;
13514
13515          _history_entries = 1;
13516          index = 0;
13517       } else {
13518          /* check if history already open */
13519          for (i = 0; i < _history_entries; i++)
13520             if (_history[i].event_id == event_id)
13521                break;
13522
13523          /* if not found, create new one */
13524          if (i == _history_entries) {
13525             _history =
13526                 (HISTORY *) realloc(_history, sizeof(HISTORY) * (_history_entries + 1));
13527             memset(&_history[_history_entries], 0, sizeof(HISTORY));
13528
13529             _history_entries++;
13530             if (_history == NULL) {
13531                _history_entries--;
13532                return HS_NO_MEMORY;
13533             }
13534          }
13535          index = i;
13536       }
13537
13538       /* assemble definition record header */
13539       rec.record_type = RT_DEF;
13540       rec.event_id = event_id;
13541       rec.time = time(NULL);
13542       rec.data_size = size;
13543       strncpy(event_name, name, NAME_LENGTH);
13544
13545       /* pad tag names with zeos */
13546       for (i = 0; (DWORD) i < size / sizeof(TAG); i++) {
13547          len = strlen(tag[i].name);
13548          memset(tag[i].name + len, 0, NAME_LENGTH - len);
13549       }
13550
13551       /* if history structure not set up, do so now */
13552       if (!_history[index].hist_fh) {
13553          /* open history file */
13554          hs_open_file(rec.time, "hst", O_CREAT | O_RDWR, &fh);
13555          if (fh < 0)
13556             return HS_FILE_ERROR;
13557
13558          /* open index files */
13559          hs_open_file(rec.time, "idf", O_CREAT | O_RDWR, &fhd);
13560          hs_open_file(rec.time, "idx", O_CREAT | O_RDWR, &fhi);
13561          lseek(fh, 0, SEEK_END);
13562          lseek(fhi, 0, SEEK_END);
13563          lseek(fhd, 0, SEEK_END);
13564
13565          /* regenerate index if missing */
13566          if (TELL(fh) > 0 && TELL(fhd) == 0) {
13567             close(fh);
13568             close(fhi);
13569             close(fhd);
13570             hs_gen_index(rec.time);
13571             hs_open_file(rec.time, "hst", O_RDWR, &fh);
13572             hs_open_file(rec.time, "idx", O_RDWR, &fhi);
13573             hs_open_file(rec.time, "idf", O_RDWR, &fhd);
13574             lseek(fh, 0, SEEK_END);
13575             lseek(fhi, 0, SEEK_END);
13576             lseek(fhd, 0, SEEK_END);
13577          }
13578
13579          tmb = localtime((const time_t *) &rec.time);
13580          tmb->tm_hour = tmb->tm_min = tmb->tm_sec = 0;
13581
13582          /* setup history structure */
13583          _history[index].hist_fh = fh;
13584          _history[index].index_fh = fhi;
13585          _history[index].def_fh = fhd;
13586          _history[index].def_offset = TELL(fh);
13587          _history[index].event_id = event_id;
13588          strcpy(_history[index].event_name, event_name);
13589          _history[index].base_time = mktime(tmb);
13590          _history[index].n_tag = size / sizeof(TAG);
13591          _history[index].tag = (TAG *) M_MALLOC(size);
13592          memcpy(_history[index].tag, tag, size);
13593
13594          /* search previous definition */
13595          n = TELL(fhd) / sizeof(def_rec);
13596          def_rec.event_id = 0;
13597          for (i = n - 1; i >= 0; i--) {
13598             lseek(fhd, i * sizeof(def_rec), SEEK_SET);
13599             read(fhd, (char *) &def_rec, sizeof(def_rec));
13600             if (def_rec.event_id == event_id)
13601                break;
13602          }
13603          lseek(fhd, 0, SEEK_END);
13604
13605          /* if definition found, compare it with new one */
13606          if (def_rec.event_id == event_id) {
13607             buffer = (char *) M_MALLOC(size);
13608             memset(buffer, 0, size);
13609
13610             lseek(fh, def_rec.def_offset, SEEK_SET);
13611             read(fh, (char *) &prev_rec, sizeof(prev_rec));
13612             read(fh, str, NAME_LENGTH);
13613             read(fh, buffer, size);
13614             lseek(fh, 0, SEEK_END);
13615
13616             if (prev_rec.data_size != size ||
13617                 strcmp(str, event_name) != 0 || memcmp(buffer, tag, size) != 0) {
13618                /* write definition to history file */
13619                write(fh, (char *) &rec, sizeof(rec));
13620                write(fh, event_name, NAME_LENGTH);
13621                write(fh, (char *) tag, size);
13622
13623                /* write index record */
13624                def_rec.event_id = event_id;
13625                memcpy(def_rec.event_name, event_name, sizeof(event_name));
13626                def_rec.def_offset = _history[index].def_offset;
13627                write(fhd, (char *) &def_rec, sizeof(def_rec));
13628             } else
13629                /* definition identical, just remember old offset */
13630                _history[index].def_offset = def_rec.def_offset;
13631
13632             M_FREE(buffer);
13633          } else {
13634             /* write definition to history file */
13635             write(fh, (char *) &rec, sizeof(rec));
13636             write(fh, event_name, NAME_LENGTH);
13637             write(fh, (char *) tag, size);
13638
13639             /* write definition index record */
13640             def_rec.event_id = event_id;
13641             memcpy(def_rec.event_name, event_name, sizeof(event_name));
13642             def_rec.def_offset = _history[index].def_offset;
13643             write(fhd, (char *) &def_rec, sizeof(def_rec));
13644          }
13645       } else {
13646          fh = _history[index].hist_fh;
13647          fhd = _history[index].def_fh;
13648
13649          /* compare definition with previous definition */
13650          buffer = (char *) M_MALLOC(size);
13651          memset(buffer, 0, size);
13652
13653          lseek(fh, _history[index].def_offset, SEEK_SET);
13654          read(fh, (char *) &prev_rec, sizeof(prev_rec));
13655          read(fh, str, NAME_LENGTH);
13656          read(fh, buffer, size);
13657
13658          lseek(fh, 0, SEEK_END);
13659          lseek(fhd, 0, SEEK_END);
13660
13661          if (prev_rec.data_size != size ||
13662              strcmp(str, event_name) != 0 || memcmp(buffer, tag, size) != 0) {
13663             /* save new definition offset */
13664             _history[index].def_offset = TELL(fh);
13665
13666             /* write definition to history file */
13667             write(fh, (char *) &rec, sizeof(rec));
13668             write(fh, event_name, NAME_LENGTH);
13669             write(fh, (char *) tag, size);
13670
13671             /* write index record */
13672             def_rec.event_id = event_id;
13673             memcpy(def_rec.event_name, event_name, sizeof(event_name));
13674             def_rec.def_offset = _history[index].def_offset;
13675             write(fhd, (char *) &def_rec, sizeof(def_rec));
13676          }
13677
13678          M_FREE(buffer);
13679       }
13680
13681    }
13682
13683    return HS_SUCCESS;
13684 }
INT hs_dump (DWORD event_id, DWORD start_time, DWORD end_time, DWORD interval, BOOL binary_time)
Definition at line 14695 of file midas.c.
References abs, cm_msg, data_buffer, db_sprintf(), HS_FILE_ERROR, HS_NO_MEMORY, hs_open_file(), hs_search_file(), HS_SUCCESS, i, j, M_FREE, M_MALLOC, MERROR, TAG::n_data, NAME_LENGTH, offset, read, rpc_tid_size(), status, tag, TELL, TID_STRING, INDEX_RECORD::time, time, and type.
Referenced by main(), and tmp().
14699          : hs_dump
14700
14701   Purpose: Display history for a given event at stdout. The output
14702            can be redirected to be read by Excel for example.
14703
14704   Input:
14705     DWORD  event_id         Event ID
14706     DWORD  start_time       Starting Date/Time
14707     DWORD  end_time         End Date/Time
14708     DWORD  interval         Minimum time in seconds between reported
14709                             events. Can be used to skip events
14710     BOOL   binary_time      Display DWORD time stamp
14711   Output:
14712     <screen output>
14713
14714   Function value:
14715     HS_SUCCESS              Successful completion
14716     HS_FILE_ERROR           Cannot open history file
14717
14718 \********************************************************************/
14719 {
14720    DWORD prev_time, last_irec_time;
14721    int fh, fhd, fhi;
14722    INT i, j, delta, status, n_tag = 0, old_n_tag = 0;
14723    INDEX_RECORD irec;
14724    HIST_RECORD rec, drec;
14725    INT old_def_offset, offset;
14726    TAG *tag = NULL, *old_tag = NULL;
14727    char str[NAME_LENGTH], data_buffer[10000];
14728    struct tm *tms;
14729
14730    /* if not time given, use present to one hour in past */
14731    if (start_time == 0)
14732       start_time = time(NULL) - 3600;
14733    if (end_time == 0)
14734       end_time = time(NULL);
14735
14736    /* search history file for start_time */
14737    status = hs_search_file(&start_time, 1);
14738    if (status != HS_SUCCESS) {
14739       cm_msg(MERROR, "hs_dump", "cannot find recent history file");
14740       return HS_FILE_ERROR;
14741    }
14742
14743    /* open history and definition files */
14744    hs_open_file(start_time, "hst", O_RDONLY, &fh);
14745    hs_open_file(start_time, "idf", O_RDONLY, &fhd);
14746    hs_open_file(start_time, "idx", O_RDONLY, &fhi);
14747    if (fh < 0 || fhd < 0 || fhi < 0) {
14748       cm_msg(MERROR, "hs_dump", "cannot open index files");
14749       return HS_FILE_ERROR;
14750    }
14751
14752    /* search record closest to start time */
14753    lseek(fhi, 0, SEEK_END);
14754    delta = (TELL(fhi) / sizeof(irec)) / 2;
14755    lseek(fhi, delta * sizeof(irec), SEEK_SET);
14756    do {
14757       delta = (int) (abs(delta) / 2.0 + 0.5);
14758       read(fhi, (char *) &irec, sizeof(irec));
14759       if (irec.time > start_time)
14760          delta = -delta;
14761
14762       i = lseek(fhi, (delta - 1) * sizeof(irec), SEEK_CUR);
14763    } while (abs(delta) > 1 && irec.time != start_time);
14764    read(fhi, (char *) &irec, sizeof(irec));
14765    if (irec.time > start_time)
14766       delta = -abs(delta);
14767
14768    i = TELL(fhi) + (delta - 1) * sizeof(irec);
14769    if (i <= 0)
14770       lseek(fhi, 0, SEEK_SET);
14771    else
14772       lseek(fhi, (delta - 1) * sizeof(irec), SEEK_CUR);
14773    read(fhi, (char *) &irec, sizeof(irec));
14774
14775    /* read records, skip wrong IDs */
14776    old_def_offset = -1;
14777    prev_time = 0;
14778    last_irec_time = 0;
14779    do {
14780       if (irec.time < last_irec_time) {
14781          cm_msg(MERROR, "hs_dump",
14782                 "corrupted history data: time does not increase: %d -> %d",
14783                 last_irec_time, irec.time);
14784          return HS_FILE_ERROR;
14785       }
14786       last_irec_time = irec.time;
14787       if (irec.event_id == event_id && irec.time <= end_time && irec.time >= start_time) {
14788          if (irec.time >= prev_time + interval) {
14789             prev_time = irec.time;
14790             lseek(fh, irec.offset, SEEK_SET);
14791             read(fh, (char *) &rec, sizeof(rec));
14792
14793             /* if definition changed, read new definition */
14794             if ((INT) rec.def_offset != old_def_offset) {
14795                lseek(fh, rec.def_offset, SEEK_SET);
14796                read(fh, (char *) &drec, sizeof(drec));
14797                read(fh, str, NAME_LENGTH);
14798
14799                if (tag == NULL)
14800                   tag = (TAG *) M_MALLOC(drec.data_size);
14801                else
14802                   tag = (TAG *) realloc(tag, drec.data_size);
14803                if (tag == NULL)
14804                   return HS_NO_MEMORY;
14805                read(fh, (char *) tag, drec.data_size);
14806                n_tag = drec.data_size / sizeof(TAG);
14807
14808                /* print tag names if definition has changed */
14809                if (old_tag == NULL || old_n_tag != n_tag ||
14810                    memcmp(old_tag, tag, drec.data_size) != 0) {
14811                   printf("Date\t");
14812                   for (i = 0; i < n_tag; i++) {
14813                      if (tag[i].n_data == 1 || tag[i].type == TID_STRING)
14814                         printf("%s\t", tag[i].name);
14815                      else
14816                         for (j = 0; j < (INT) tag[i].n_data; j++)
14817                            printf("%s%d\t", tag[i].name, j);
14818                   }
14819                   printf("\n");
14820
14821                   if (old_tag == NULL)
14822                      old_tag = (TAG *) M_MALLOC(drec.data_size);
14823                   else
14824                      old_tag = (TAG *) realloc(old_tag, drec.data_size);
14825                   memcpy(old_tag, tag, drec.data_size);
14826                   old_n_tag = n_tag;
14827                }
14828
14829                old_def_offset = rec.def_offset;
14830                lseek(fh, irec.offset + sizeof(rec), SEEK_SET);
14831             }
14832
14833             /* print time from header */
14834             if (binary_time)
14835                printf("%li ", irec.time);
14836             else {
14837                sprintf(str, "%s", ctime((const time_t *) &irec.time) + 4);
14838                str[20] = '\t';
14839                printf(str);
14840             }
14841
14842             /* read data */
14843             read(fh, data_buffer, rec.data_size);
14844
14845             /* interprete data from tag definition */
14846             offset = 0;
14847             for (i = 0; i < n_tag; i++) {
14848                /* strings have a length of n_data */
14849                if (tag[i].type == TID_STRING) {
14850                   printf("%s\t", data_buffer + offset);
14851                   offset += tag[i].n_data;
14852                } else if (tag[i].n_data == 1) {
14853                   /* non-array data */
14854                   db_sprintf(str, data_buffer + offset, rpc_tid_size(tag[i].type), 0,
14855                              tag[i].type);
14856                   printf("%s\t", str);
14857                   offset += rpc_tid_size(tag[i].type);
14858                } else
14859                   /* loop over array data */
14860                   for (j = 0; j < (INT) tag[i].n_data; j++) {
14861                      db_sprintf(str, data_buffer + offset, rpc_tid_size(tag[i].type), 0,
14862                                 tag[i].type);
14863                      printf("%s\t", str);
14864                      offset += rpc_tid_size(tag[i].type);
14865                   }
14866             }
14867             printf("\n");
14868          }
14869       }
14870
14871       /* read next index record */
14872       i = read(fhi, (char *) &irec, sizeof(irec));
14873
14874       /* end of file: search next history file */
14875       if (i <= 0) {
14876          close(fh);
14877          close(fhd);
14878          close(fhi);
14879
14880          /* advance one day */
14881          tms = localtime((const time_t *) &last_irec_time);
14882          tms->tm_hour = tms->tm_min = tms->tm_sec = 0;
14883          last_irec_time = mktime(tms);
14884
14885          last_irec_time += 3600 * 24;
14886          if (last_irec_time > end_time)
14887             break;
14888
14889          /* search next file */
14890          status = hs_search_file(&last_irec_time, 1);
14891          if (status != HS_SUCCESS)
14892             break;
14893
14894          /* open history and definition files */
14895          hs_open_file(last_irec_time, "hst", O_RDONLY, &fh);
14896          hs_open_file(last_irec_time, "idf", O_RDONLY, &fhd);
14897          hs_open_file(last_irec_time, "idx", O_RDONLY, &fhi);
14898          if (fh < 0 || fhd < 0 || fhi < 0) {
14899             cm_msg(MERROR, "hs_dump", "cannot open index files");
14900             break;
14901          }
14902
14903          /* read first record */
14904          i = read(fhi, (char *) &irec, sizeof(irec));
14905          if (i <= 0)
14906             break;
14907
14908          /* old definition becomes invalid */
14909          old_def_offset = -1;
14910       }
14911    } while (irec.time < end_time);
14912
14913    M_FREE(tag);
14914    M_FREE(old_tag);
14915    close(fh);
14916    close(fhd);
14917    close(fhi);
14918
14919    return HS_SUCCESS;
14920 }
INT hs_enum_events (DWORD ltime, char * event_name, DWORD * name_size, INT event_id[], DWORD * id_size)
Definition at line 13818 of file midas.c.
References cm_msg, HS_FILE_ERROR, HS_NO_MEMORY, hs_open_file(), hs_search_file(), HS_SUCCESS, i, j, MERROR, n, NAME_LENGTH, read, rpc_call(), RPC_HS_ENUM_EVENTS, rpc_is_remote(), status, and TRUE.
Referenced by display_vars(), query_params(), and rpc_server_dispatch().
13822          : hs_enum_events
13823
13824   Purpose: Enumerate events for a given date
13825
13826   Input:
13827     DWORD  ltime            Date at which events should be enumerated
13828
13829   Output:
13830     char   *event_name      Array containing event names
13831     DWORD  *name_size       Size of name array
13832     char   *event_id        Array containing event IDs
13833     DWORD  *id_size         Size of ID array
13834
13835   Function value:
13836     HS_SUCCESS              Successful completion
13837     HS_NO_MEMEORY           Out of memory
13838     HS_FILE_ERROR           Cannot open history file
13839
13840 \********************************************************************/
13841 {
13842    int fh, fhd;
13843    INT status, i, j, n;
13844    DEF_RECORD def_rec;
13845
13846    if (rpc_is_remote())
13847       return rpc_call(RPC_HS_ENUM_EVENTS, ltime, event_name, name_size, event_id,
13848                       id_size);
13849
13850    /* search latest history file */
13851    status = hs_search_file(&ltime, -1);
13852    if (status != HS_SUCCESS) {
13853       cm_msg(MERROR, "hs_enum_events", "cannot find recent history file");
13854       return HS_FILE_ERROR;
13855    }
13856
13857    /* open history and definition files */
13858    hs_open_file(ltime, "hst", O_RDONLY, &fh);
13859    hs_open_file(ltime, "idf", O_RDONLY, &fhd);
13860    if (fh < 0 || fhd < 0) {
13861       cm_msg(MERROR, "hs_enum_events", "cannot open index files");
13862       return HS_FILE_ERROR;
13863    }
13864    lseek(fhd, 0, SEEK_SET);
13865
13866    /* loop over definition index file */
13867    n = 0;
13868    do {
13869       /* read event definition */
13870       j = read(fhd, (char *) &def_rec, sizeof(def_rec));
13871       if (j < (int) sizeof(def_rec))
13872          break;
13873
13874       /* look for existing entry for this event id */
13875       for (i = 0; i < n; i++)
13876          if (event_id[i] == (INT) def_rec.event_id) {
13877             strcpy(event_name + i * NAME_LENGTH, def_rec.event_name);
13878             break;
13879          }
13880
13881       /* new entry found */
13882       if (i == n) {
13883          if (i * NAME_LENGTH > (INT) * name_size || i * sizeof(INT) > (INT) * id_size) {
13884             cm_msg(MERROR, "hs_enum_events", "index buffer too small");
13885             close(fh);
13886             close(fhd);
13887             return HS_NO_MEMORY;
13888          }
13889
13890          /* copy definition record */
13891          strcpy(event_name + i * NAME_LENGTH, def_rec.event_name);
13892          event_id[i] = def_rec.event_id;
13893          n++;
13894       }
13895    } while (TRUE);
13896
13897    close(fh);
13898    close(fhd);
13899    *name_size = n * NAME_LENGTH;
13900    *id_size = n * sizeof(INT);
13901
13902    return HS_SUCCESS;
13903 }
INT hs_enum_vars (DWORD ltime, DWORD event_id, char * var_name, DWORD * size, DWORD * var_n, DWORD * n_size)
Definition at line 14134 of file midas.c.
References cm_msg, DEF_RECORD::def_offset, DEF_RECORD::event_id, HS_FILE_ERROR, HS_NO_MEMORY, hs_open_file(), hs_search_file(), HS_SUCCESS, i, M_FREE, M_MALLOC, MERROR, n, NAME_LENGTH, read, rpc_call(), RPC_HS_ENUM_VARS, rpc_is_remote(), status, tag, and TELL.
Referenced by display_vars(), query_params(), and rpc_server_dispatch().
14138          : hs_enum_vars
14139
14140   Purpose: Enumerate variable tags for a given date and event id
14141
14142   Input:
14143     DWORD  ltime            Date at which tags should be enumerated
14144     DWORD  event_id         Event ID
14145
14146   Output:
14147     char   *var_name        Array containing variable names
14148     DWORD  *size            Size of name array
14149     DWORD  *var_n           Array size of variable
14150     DWORD  *n_size          Size of n array
14151
14152   Function value:
14153     HS_SUCCESS              Successful completion
14154     HS_NO_MEMEORY           Out of memory
14155     HS_FILE_ERROR           Cannot open history file
14156
14157 \********************************************************************/
14158 {
14159    char str[256];
14160    int fh, fhd;
14161    INT i, n, status;
14162    DEF_RECORD def_rec;
14163    HIST_RECORD rec;
14164    TAG *tag;
14165
14166    if (rpc_is_remote())
14167       return rpc_call(RPC_HS_ENUM_VARS, ltime, event_id, var_name, size);
14168
14169    /* search latest history file */
14170    status = hs_search_file(&ltime, -1);
14171    if (status != HS_SUCCESS) {
14172       cm_msg(MERROR, "hs_enum_vars", "cannot find recent history file");
14173       return HS_FILE_ERROR;
14174    }
14175
14176    /* open history and definition files */
14177    hs_open_file(ltime, "hst", O_RDONLY, &fh);
14178    hs_open_file(ltime, "idf", O_RDONLY, &fhd);
14179    if (fh < 0 || fhd < 0) {
14180       cm_msg(MERROR, "hs_enum_vars", "cannot open index files");
14181       return HS_FILE_ERROR;
14182    }
14183
14184    /* search last definition */
14185    lseek(fhd, 0, SEEK_END);
14186    n = TELL(fhd) / sizeof(def_rec);
14187    def_rec.event_id = 0;
14188    for (i = n - 1; i >= 0; i--) {
14189       lseek(fhd, i * sizeof(def_rec), SEEK_SET);
14190       read(fhd, (char *) &def_rec, sizeof(def_rec));
14191       if (def_rec.event_id == event_id)
14192          break;
14193    }
14194    if (def_rec.event_id != event_id) {
14195       cm_msg(MERROR, "hs_enum_vars", "event %d not found in index file", event_id);
14196       return HS_FILE_ERROR;
14197    }
14198
14199    /* read definition header */
14200    lseek(fh, def_rec.def_offset, SEEK_SET);
14201    read(fh, (char *) &rec, sizeof(rec));
14202    read(fh, str, NAME_LENGTH);
14203
14204    /* read event definition */
14205    n = rec.data_size / sizeof(TAG);
14206    tag = (TAG *) M_MALLOC(rec.data_size);
14207    read(fh, (char *) tag, rec.data_size);
14208
14209    if (n * NAME_LENGTH > (INT) *size || n * sizeof(DWORD) > *n_size) {
14210
14211       /* store partial definition */
14212       for (i = 0; i < (INT) *size / NAME_LENGTH; i++) {
14213          strcpy(var_name + i * NAME_LENGTH, tag[i].name);
14214          var_n[i] = tag[i].n_data;
14215       }
14216
14217       cm_msg(MERROR, "hs_enum_vars", "tag buffer too small");
14218       M_FREE(tag);
14219       close(fh);
14220       close(fhd);
14221       return HS_NO_MEMORY;
14222    }
14223
14224    /* store full definition */
14225    for (i = 0; i < n; i++) {
14226       strcpy(var_name + i * NAME_LENGTH, tag[i].name);
14227       var_n[i] = tag[i].n_data;
14228    }
14229    *size = n * NAME_LENGTH;
14230    *n_size = n * sizeof(DWORD);
14231
14232    M_FREE(tag);
14233    close(fh);
14234    close(fhd);
14235
14236    return HS_SUCCESS;
14237 }
INT hs_fdump (char * file_name, DWORD id, BOOL binary_time)
Definition at line 14924 of file midas.c.
References cm_msg, HS_FILE_ERROR, HS_SUCCESS, MERROR, n, NAME_LENGTH, O_BINARY, read, RT_DEF, and TRUE.
Referenced by main().
14927          : hs_fdump
14928
14929   Purpose: Display history for a given history file
14930
14931   Input:
14932     char   *file_name       Name of file to dump
14933     DWORD  event_id         Event ID
14934     BOOL   binary_time      Display DWORD time stamp
14935
14936   Output:
14937     <screen output>
14938
14939   Function value:
14940     HS_SUCCESS              Successful completion
14941     HS_FILE_ERROR           Cannot open history file
14942
14943 \********************************************************************/
14944 {
14945    int fh;
14946    INT n;
14947    HIST_RECORD rec;
14948    char event_name[NAME_LENGTH];
14949    char str[80];
14950
14951    /* open file, add O_BINARY flag for Windows NT */
14952    fh = open(file_name, O_RDONLY | O_BINARY, 0644);
14953    if (fh < 0) {
14954       cm_msg(MERROR, "hs_fdump", "cannot open file %s", file_name);
14955       return HS_FILE_ERROR;
14956    }
14957
14958    /* loop over file records in .hst file */
14959    do {
14960       n = read(fh, (char *) &rec, sizeof(rec));
14961       if (n < sizeof(rec))
14962          break;
14963
14964       /* check if record type is definition */
14965       if (rec.record_type == RT_DEF) {
14966          /* read name */
14967          read(fh, event_name, sizeof(event_name));
14968
14969          if (rec.event_id == id || id == 0)
14970             printf("Event definition %s, ID %ld\n", event_name, rec.event_id);
14971
14972          /* skip tags */
14973          lseek(fh, rec.data_size, SEEK_CUR);
14974       } else {
14975          /* print data record */
14976          if (binary_time)
14977             sprintf(str, "%li ", rec.time);
14978          else {
14979             strcpy(str, ctime((const time_t *) &rec.time) + 4);
14980             str[15] = 0;
14981          }
14982          if (rec.event_id == id || id == 0)
14983             printf("ID %ld, %s, size %ld\n", rec.event_id, str, rec.data_size);
14984
14985          /* skip data */
14986          lseek(fh, rec.data_size, SEEK_CUR);
14987       }
14988
14989    } while (TRUE);
14990
14991    close(fh);
14992
14993    return HS_SUCCESS;
14994 }
INT hs_gen_index (DWORD ltime)
dox
Definition at line 13299 of file midas.c.
References cm_msg, DEF_RECORD::def_offset, INDEX_RECORD::event_id, DEF_RECORD::event_id, DEF_RECORD::event_name, HS_FILE_ERROR, hs_open_file(), HS_SUCCESS, MERROR, n, NAME_LENGTH, INDEX_RECORD::offset, read, RT_DEF, TELL, INDEX_RECORD::time, time, TRUE, and write.
Referenced by hs_define_event(), and hs_search_file().
13302          : hs_gen_index
13303
13304   Purpose: Regenerate index files ("idx" and "idf" files) for a given
13305            history file ("hst"). Interal use only.
13306
13307   Input:
13308     DWORD  ltime            Date for which a history file should
13309                             be analyzed.
13310
13311   Output:
13312     none
13313
13314   Function value:
13315     HS_SUCCESS              Successful completion
13316     HS_FILE_ERROR           Index files cannot be created
13317
13318 \********************************************************************/
13319 {
13320    char event_name[NAME_LENGTH];
13321    int fh, fhd, fhi;
13322    INT n;
13323    HIST_RECORD rec;
13324    INDEX_RECORD irec;
13325    DEF_RECORD def_rec;
13326
13327    printf("Recovering index files...\n");
13328
13329    if (ltime == 0)
13330       ltime = time(NULL);
13331
13332    /* open new index file */
13333    hs_open_file(ltime, "idx", O_RDWR | O_CREAT | O_TRUNC, &fhi);
13334    hs_open_file(ltime, "idf", O_RDWR | O_CREAT | O_TRUNC, &fhd);
13335
13336    if (fhd < 0 || fhi < 0) {
13337       cm_msg(MERROR, "hs_gen_index", "cannot create index file");
13338       return HS_FILE_ERROR;
13339    }
13340
13341    /* open history file */
13342    hs_open_file(ltime, "hst", O_RDONLY, &fh);
13343    if (fh < 0)
13344       return HS_FILE_ERROR;
13345    lseek(fh, 0, SEEK_SET);
13346
13347    /* loop over file records in .hst file */
13348    do {
13349       n = read(fh, (char *) &rec, sizeof(rec));
13350       if (n < sizeof(rec))
13351          break;
13352
13353       /* check if record type is definition */
13354       if (rec.record_type == RT_DEF) {
13355          /* read name */
13356          read(fh, event_name, sizeof(event_name));
13357
13358          printf("Event definition %s, ID %ld\n", event_name, rec.event_id);
13359
13360          /* write definition index record */
13361          def_rec.event_id = rec.event_id;
13362          memcpy(def_rec.event_name, event_name, sizeof(event_name));
13363          def_rec.def_offset = TELL(fh) - sizeof(event_name) - sizeof(rec);
13364          write(fhd, (char *) &def_rec, sizeof(def_rec));
13365
13366          /* skip tags */
13367          lseek(fh, rec.data_size, SEEK_CUR);
13368       } else {
13369          /* write index record */
13370          irec.event_id = rec.event_id;
13371          irec.time = rec.time;
13372          irec.offset = TELL(fh) - sizeof(rec);
13373          write(fhi, (char *) &irec, sizeof(irec));
13374
13375          /* printf("ID %d, %s\n", rec.event_id, ctime((const time_t *)&irec.time)+4); */
13376
13377          /* skip data */
13378          lseek(fh, rec.data_size, SEEK_CUR);
13379       }
13380
13381    } while (TRUE);
13382
13383    close(fh);
13384    close(fhi);
13385    close(fhd);
13386
13387    printf("...done.\n");
13388
13389    return HS_SUCCESS;
13390 }
INT hs_get_event_id (DWORD ltime, char * name, DWORD * id)
Definition at line 13985 of file midas.c.
References cm_msg, HS_FILE_ERROR, hs_open_file(), hs_search_file(), HS_SUCCESS, HS_UNDEFINED_EVENT, i, MERROR, read, rpc_call(), RPC_HS_GET_EVENT_ID, rpc_is_remote(), status, time, and TRUE.
Referenced by generate_hist_graph(), and rpc_server_dispatch().
13988          : hs_get_event_id
13989
13990   Purpose: Return event ID for a given name. If event cannot be found
13991            in current definition file, go back in time until found
13992
13993   Input:
13994     DWORD  ltime            Date at which event ID should be looked for
13995
13996   Output:
13997     DWORD  *id              Event ID
13998
13999   Function value:
14000     HS_SUCCESS              Successful completion
14001     HS_FILE_ERROR           Cannot open history file
14002     HS_UNDEFINED_EVENT      Event "name" not found
14003
14004 \********************************************************************/
14005 {
14006    int fh, fhd;
14007    INT status, i;
14008    DWORD lt;
14009    DEF_RECORD def_rec;
14010
14011    if (rpc_is_remote())
14012       return rpc_call(RPC_HS_GET_EVENT_ID, ltime, name, id);
14013
14014    /* search latest history file */
14015    if (ltime == 0)
14016       ltime = time(NULL);
14017
14018    lt = ltime;
14019
14020    do {
14021       status = hs_search_file(&lt, -1);
14022       if (status != HS_SUCCESS) {
14023          cm_msg(MERROR, "hs_count_events", "cannot find recent history file");
14024          return HS_FILE_ERROR;
14025       }
14026
14027       /* open history and definition files */
14028       hs_open_file(lt, "hst", O_RDONLY, &fh);
14029       hs_open_file(lt, "idf", O_RDONLY, &fhd);
14030       if (fh < 0 || fhd < 0) {
14031          cm_msg(MERROR, "hs_count_events", "cannot open index files");
14032          return HS_FILE_ERROR;
14033       }
14034
14035       /* loop over index file */
14036       *id = 0;
14037       do {
14038          /* read definition index record */
14039          i = read(fhd, (char *) &def_rec, sizeof(def_rec));
14040          if (i < (int) sizeof(def_rec))
14041             break;
14042
14043          if (strcmp(name, def_rec.event_name) == 0) {
14044             *id = def_rec.event_id;
14045             close(fh);
14046             close(fhd);
14047             return HS_SUCCESS;
14048          }
14049       } while (TRUE);
14050
14051       close(fh);
14052       close(fhd);
14053
14054       /* not found -> go back one day */
14055       lt -= 3600 * 24;
14056
14057    } while (lt > ltime - 3600 * 24 * 365 * 10); /* maximum 10 years */
14058
14059    return HS_UNDEFINED_EVENT;
14060 }
INT hs_get_var (DWORD ltime, DWORD event_id, char * var_name, DWORD * type, INT * n_data)
Definition at line 14241 of file midas.c.
References cm_msg, DEF_RECORD::def_offset, DEF_RECORD::event_id, HS_FILE_ERROR, hs_open_file(), hs_search_file(), HS_SUCCESS, HS_UNDEFINED_VAR, i, M_FREE, M_MALLOC, MERROR, n, NAME_LENGTH, read, rpc_call(), RPC_HS_GET_VAR, rpc_is_remote(), status, tag, and TELL.
Referenced by query_params(), and rpc_server_dispatch().
14244          : hs_get_var
14245
14246   Purpose: Get definition for certain variable
14247
14248   Input:
14249     DWORD  ltime            Date at which variable definition should
14250                             be returned
14251     DWORD  event_id         Event ID
14252     char   *var_name        Name of variable
14253
14254   Output:
14255     INT    *type            Type of variable
14256     INT    *n_data          Number of items in variable
14257
14258   Function value:
14259     HS_SUCCESS              Successful completion
14260     HS_NO_MEMEORY           Out of memory
14261     HS_FILE_ERROR           Cannot open history file
14262
14263 \********************************************************************/
14264 {
14265    char str[256];
14266    int fh, fhd;
14267    INT i, n, status;
14268    DEF_RECORD def_rec;
14269    HIST_RECORD rec;
14270    TAG *tag;
14271
14272    if (rpc_is_remote())
14273       return rpc_call(RPC_HS_GET_VAR, ltime, event_id, var_name, type, n_data);
14274
14275    /* search latest history file */
14276    status = hs_search_file(&ltime, -1);
14277    if (status != HS_SUCCESS) {
14278       cm_msg(MERROR, "hs_get_var", "cannot find recent history file");
14279       return HS_FILE_ERROR;
14280    }
14281
14282    /* open history and definition files */
14283    hs_open_file(ltime, "hst", O_RDONLY, &fh);
14284    hs_open_file(ltime, "idf", O_RDONLY, &fhd);
14285    if (fh < 0 || fhd < 0) {
14286       cm_msg(MERROR, "hs_get_var", "cannot open index files");
14287       return HS_FILE_ERROR;
14288    }
14289
14290    /* search last definition */
14291    lseek(fhd, 0, SEEK_END);
14292    n = TELL(fhd) / sizeof(def_rec);
14293    def_rec.event_id = 0;
14294    for (i = n - 1; i >= 0; i--) {
14295       lseek(fhd, i * sizeof(def_rec), SEEK_SET);
14296       read(fhd, (char *) &def_rec, sizeof(def_rec));
14297       if (def_rec.event_id == event_id)
14298          break;
14299    }
14300    if (def_rec.event_id != event_id) {
14301       cm_msg(MERROR, "hs_get_var", "event %d not found in index file", event_id);
14302       return HS_FILE_ERROR;
14303    }
14304
14305    /* read definition header */
14306    lseek(fh, def_rec.def_offset, SEEK_SET);
14307    read(fh, (char *) &rec, sizeof(rec));
14308    read(fh, str, NAME_LENGTH);
14309
14310    /* read event definition */
14311    n = rec.data_size / sizeof(TAG);
14312    tag = (TAG *) M_MALLOC(rec.data_size);
14313    read(fh, (char *) tag, rec.data_size);
14314
14315    /* search variable */
14316    for (i = 0; i < n; i++)
14317       if (strcmp(tag[i].name, var_name) == 0)
14318          break;
14319
14320    close(fh);
14321    close(fhd);
14322
14323    if (i < n) {
14324       *type = tag[i].type;
14325       *n_data = tag[i].n_data;
14326    } else {
14327       *type = *n_data = 0;
14328       cm_msg(MERROR, "hs_get_var", "variable %s not found", var_name);
14329       M_FREE(tag);
14330       return HS_UNDEFINED_VAR;
14331    }
14332
14333    M_FREE(tag);
14334    return HS_SUCCESS;
14335 }
INT hs_open_file (DWORD ltime, char * suffix, INT mode, int * fh)
Open history file belonging to certain date. Internal use only.
Parameters:
ltime Date for which a history file should be opened.
suffix File name suffix like "hst", "idx", "idf"
mode R/W access mode
fh File handle
Returns:
HS_SUCCESS
Definition at line 13271 of file midas.c.
References file_name, HS_SUCCESS, and O_BINARY.
Referenced by hs_count_events(), hs_count_vars(), hs_define_event(), hs_dump(), hs_enum_events(), hs_enum_vars(), hs_gen_index(), hs_get_event_id(), hs_get_var(), hs_read(), hs_search_file(), and hs_write_event().
13272 {
13273    time_t tt;
13274    struct tm *tms;
13275    char file_name[256];
13276
13277    /* generate new file name YYMMDD.xxx */
13278 #if !defined(OS_VXWORKS)
13279 #if !defined(OS_VMS)
13280    tzset();
13281 #endif
13282 #endif
13283    tt = (time_t) ltime;
13284    tms = localtime(&tt);
13285
13286    sprintf(file_name, "%s%02d%02d%02d.%s", _hs_path_name,
13287            tms->tm_year % 100, tms->tm_mon + 1, tms->tm_mday, suffix);
13288
13289    /* open file, add O_BINARY flag for Windows NT */
13290    *fh = open(file_name, mode | O_BINARY, 0644);
13291
13292    return HS_SUCCESS;
13293 }
INT hs_read (DWORD event_id, DWORD start_time, DWORD end_time, DWORD interval, char * tag_name, DWORD var_index, DWORD * time_buffer, DWORD * tbsize, void * data_buffer, DWORD * dbsize, DWORD * type, DWORD * n)
Definition at line 14339 of file midas.c.
References abs, cache, cm_msg, equal_ustring(), INDEX_RECORD::event_id, HS_FILE_ERROR, HS_NO_MEMORY, hs_open_file(), hs_search_file(), HS_SUCCESS, HS_TRUNCATED, HS_WRONG_INDEX, i, index, M_FREE, M_MALLOC, MERROR, NAME_LENGTH, INDEX_RECORD::offset, read, rpc_call(), RPC_HS_READ, rpc_is_remote(), rpc_tid_size(), status, tag, TELL, TID_STRING, INDEX_RECORD::time, and time.
Referenced by display_range_hist(), display_single_hist(), generate_hist_graph(), and rpc_server_dispatch().
14345          : hs_read
14346
14347   Purpose: Read history for a variable at a certain time interval
14348
14349   Input:
14350     DWORD  event_id         Event ID
14351     DWORD  start_time       Starting Date/Time
14352     DWORD  end_time         End Date/Time
14353     DWORD  interval         Minimum time in seconds between reported
14354                             events. Can be used to skip events
14355     char   *tag_name        Variable name inside event
14356     DWORD  var_index        Index if variable is array
14357
14358   Output:
14359     DWORD  *time_buffer     Buffer containing times for each value
14360     DWORD  *tbsize          Size of time buffer
14361     void   *data_buffer     Buffer containing variable values
14362     DWORD  *dbsize          Data buffer size
14363     DWORD  *type            Type of variable (one of TID_xxx)
14364     DWORD  *n               Number of time/value pairs found
14365                             in specified interval and placed into
14366                             time_buffer and data_buffer
14367
14368
14369   Function value:
14370     HS_SUCCESS              Successful completion
14371     HS_NO_MEMEORY           Out of memory
14372     HS_FILE_ERROR           Cannot open history file
14373     HS_WRONG_INDEX          var_index exceeds array size of variable
14374     HS_UNDEFINED_VAR        Variable "tag_name" not found in event
14375     HS_TRUNCATED            Buffer too small, data has been truncated
14376
14377 \********************************************************************/
14378 {
14379    DWORD prev_time, last_irec_time;
14380    int fh, fhd, fhi, cp = 0;
14381    INT i, delta, index = 0, status, cache_size;
14382    INDEX_RECORD irec, *pirec;
14383    HIST_RECORD rec, drec;
14384    INT old_def_offset, var_size = 0, var_offset = 0;
14385    TAG *tag;
14386    char str[NAME_LENGTH];
14387    struct tm *tms;
14388    char *cache;
14389
14390    if (rpc_is_remote())
14391       return rpc_call(RPC_HS_READ, event_id, start_time, end_time, interval,
14392                       tag_name, var_index, time_buffer, tbsize, data_buffer,
14393                       dbsize, type, n);
14394
14395    /* if not time given, use present to one hour in past */
14396    if (start_time == 0)
14397       start_time = time(NULL) - 3600;
14398    if (end_time == 0)
14399       end_time = time(NULL);
14400
14401    /* search history file for start_time */
14402    status = hs_search_file(&start_time, 1);
14403    if (status != HS_SUCCESS) {
14404       cm_msg(MERROR, "hs_read", "cannot find recent history file");
14405       *tbsize = *dbsize = *n = 0;
14406       return HS_FILE_ERROR;
14407    }
14408
14409    /* open history and definition files */
14410    hs_open_file(start_time, "hst", O_RDONLY, &fh);
14411    hs_open_file(start_time, "idf", O_RDONLY, &fhd);
14412    hs_open_file(start_time, "idx", O_RDONLY, &fhi);
14413    if (fh < 0 || fhd < 0 || fhi < 0) {
14414       cm_msg(MERROR, "hs_read", "cannot open index files");
14415       *tbsize = *dbsize = *n = 0;
14416       return HS_FILE_ERROR;
14417    }
14418
14419    /* try to read index file into cache */
14420    lseek(fhi, 0, SEEK_END);
14421    cache_size = TELL(fhi);
14422
14423    if (cache_size > 0) {
14424       cache = (char *) M_MALLOC(cache_size);
14425       if (cache) {
14426          lseek(fhi, 0, SEEK_SET);
14427          i = read(fhi, cache, cache_size);
14428          if (i < cache_size) {
14429             M_FREE(cache);
14430             close(fh);
14431             close(fhd);
14432             close(fhi);
14433             return HS_FILE_ERROR;
14434          }
14435       }
14436
14437       /* search record closest to start time */
14438       if (cache == NULL) {
14439          lseek(fhi, 0, SEEK_END);
14440          delta = (TELL(fhi) / sizeof(irec)) / 2;
14441          lseek(fhi, delta * sizeof(irec), SEEK_SET);
14442          do {
14443             delta = (int) (abs(delta) / 2.0 + 0.5);
14444             read(fhi, (char *) &irec, sizeof(irec));
14445             if (irec.time > start_time)
14446                delta = -delta;
14447
14448             lseek(fhi, (delta - 1) * sizeof(irec), SEEK_CUR);
14449          } while (abs(delta) > 1 && irec.time != start_time);
14450          read(fhi, (char *) &irec, sizeof(irec));
14451          if (irec.time > start_time)
14452             delta = -abs(delta);
14453
14454          i = TELL(fhi) + (delta - 1) * sizeof(irec);
14455          if (i <= 0)
14456             lseek(fhi, 0, SEEK_SET);
14457          else
14458             lseek(fhi, (delta - 1) * sizeof(irec), SEEK_CUR);
14459          read(fhi, (char *) &irec, sizeof(irec));
14460       } else {
14461          delta = (cache_size / sizeof(irec)) / 2;
14462          cp = delta * sizeof(irec);
14463          do {
14464             delta = (int) (abs(delta) / 2.0 + 0.5);
14465             pirec = (INDEX_RECORD *) (cache + cp);
14466             if (pirec->time > start_time)
14467                delta = -delta;
14468
14469             cp = cp + delta * sizeof(irec);
14470          } while (abs(delta) > 1 && pirec->time != start_time);
14471          pirec = (INDEX_RECORD *) (cache + cp);
14472          if (pirec->time > start_time)
14473             delta = -abs(delta);
14474
14475          if (cp <= delta * (int) sizeof(irec))
14476             cp = 0;
14477          else
14478             cp = cp + delta * sizeof(irec);
14479
14480          if (cp >= cache_size)
14481             cp = cache_size - sizeof(irec);
14482          if (cp < 0)
14483             cp = 0;
14484
14485          memcpy(&irec, (INDEX_RECORD *) (cache + cp), sizeof(irec));
14486          cp += sizeof(irec);
14487       }
14488    } else {                     /* file size > 0 */
14489
14490       cache = NULL;
14491       irec.time = start_time;
14492    }
14493
14494    /* read records, skip wrong IDs */
14495    old_def_offset = -1;
14496    *n = 0;
14497    prev_time = 0;
14498    last_irec_time = 0;
14499    do {
14500       if (irec.time < last_irec_time) {
14501          cm_msg(MERROR, "hs_read",
14502                 "corrupted history data: time does not increase: %d -> %d",
14503                 last_irec_time, irec.time);
14504          *tbsize = *dbsize = *n = 0;
14505          return HS_FILE_ERROR;
14506       }
14507       last_irec_time = irec.time;
14508       if (irec.event_id == event_id && irec.time <= end_time && irec.time >= start_time) {
14509          /* check if record time more than "interval" seconds after previous time */
14510          if (irec.time >= prev_time + interval) {
14511             prev_time = irec.time;
14512             lseek(fh, irec.offset, SEEK_SET);
14513             read(fh, (char *) &rec, sizeof(rec));
14514
14515             /* if definition changed, read new definition */
14516             if ((INT) rec.def_offset != old_def_offset) {
14517                lseek(fh, rec.def_offset, SEEK_SET);
14518                read(fh, (char *) &drec, sizeof(drec));
14519                read(fh, str, NAME_LENGTH);
14520
14521                tag = (TAG *) M_MALLOC(drec.data_size);
14522                if (tag == NULL) {
14523                   *n = *tbsize = *dbsize = 0;
14524                   if (cache)
14525                      M_FREE(cache);
14526                   close(fh);
14527                   close(fhd);
14528                   close(fhi);
14529                   return HS_NO_MEMORY;
14530                }
14531                read(fh, (char *) tag, drec.data_size);
14532
14533                /* find index of tag_name in new definition */
14534                index = -1;
14535                for (i = 0; (DWORD) i < drec.data_size / sizeof(TAG); i++)
14536                   if (equal_ustring(tag[i].name, tag_name)) {
14537                      index = i;
14538                      break;
14539                   }
14540
14541                /*
14542                   if ((DWORD) i == drec.data_size/sizeof(TAG))
14543                   {
14544                   *n = *tbsize = *dbsize = 0;
14545                   if (cache)
14546                   M_FREE(cache);
14547
14548                   return HS_UNDEFINED_VAR;
14549                   }
14550                 */
14551
14552                if (index >= 0 && var_index >= tag[i].n_data) {
14553                   *n = *tbsize = *dbsize = 0;
14554                   if (cache)
14555                      M_FREE(cache);
14556                   M_FREE(tag);
14557                   close(fh);
14558                   close(fhd);
14559                   close(fhi);
14560                   return HS_WRONG_INDEX;
14561                }
14562
14563                /* calculate offset for variable */
14564                if (index >= 0) {
14565                   *type = tag[i].type;
14566
14567                   /* loop over all previous variables */
14568                   for (i = 0, var_offset = 0; i < index; i++)
14569                      var_offset += rpc_tid_size(tag[i].type) * tag[i].n_data;
14570
14571                   /* strings have size n_data */
14572                   if (tag[index].type == TID_STRING)
14573                      var_size = tag[i].n_data;
14574                   else
14575                      var_size = rpc_tid_size(tag[index].type);
14576
14577                   var_offset += var_size * var_index;
14578                }
14579
14580                M_FREE(tag);
14581                old_def_offset = rec.def_offset;
14582                lseek(fh, irec.offset + sizeof(rec), SEEK_SET);
14583             }
14584
14585             if (index >= 0) {
14586                /* check if data fits in buffers */
14587                if ((*n) * sizeof(DWORD) >= *tbsize || (*n) * var_size >= *dbsize) {
14588                   *dbsize = (*n) * var_size;
14589                   *tbsize = (*n) * sizeof(DWORD);
14590                   if (cache)
14591                      M_FREE(cache);
14592                   close(fh);
14593                   close(fhd);
14594                   close(fhi);
14595                   return HS_TRUNCATED;
14596                }
14597
14598                /* copy time from header */
14599                time_buffer[*n] = irec.time;
14600
14601                /* copy data from record */
14602                lseek(fh, var_offset, SEEK_CUR);
14603                read(fh, (char *) data_buffer + (*n) * var_size, var_size);
14604
14605                /* increment counter */
14606                (*n)++;
14607             }
14608          }
14609       }
14610
14611       /* read next index record */
14612       if (cache) {
14613          if (cp >= cache_size) {
14614             i = -1;
14615             M_FREE(cache);
14616             cache = NULL;
14617          } else
14618             i = sizeof(irec);
14619
14620          if (cp < cache_size) {
14621             memcpy(&irec, cache + cp, sizeof(irec));
14622             cp += sizeof(irec);
14623          }
14624       } else
14625          i = read(fhi, (char *) &irec, sizeof(irec));
14626
14627       /* end of file: search next history file */
14628       if (i <= 0) {
14629          close(fh);
14630          close(fhd);
14631          close(fhi);
14632
14633          /* advance one day */
14634          tms = localtime((const time_t *) &last_irec_time);
14635          tms->tm_hour = tms->tm_min = tms->tm_sec = 0;
14636          last_irec_time = mktime(tms);
14637
14638          last_irec_time += 3600 * 24;
14639
14640          if (last_irec_time > end_time)
14641             break;
14642
14643          /* search next file */
14644          status = hs_search_file(&last_irec_time, 1);
14645          if (status != HS_SUCCESS)
14646             break;
14647
14648          /* open history and definition files */
14649          hs_open_file(last_irec_time, "hst", O_RDONLY, &fh);
14650          hs_open_file(last_irec_time, "idf", O_RDONLY, &fhd);
14651          hs_open_file(last_irec_time, "idx", O_RDONLY, &fhi);
14652          if (fh < 0 || fhd < 0 || fhi < 0) {
14653             cm_msg(MERROR, "hs_read", "cannot open index files");
14654             break;
14655          }
14656
14657          /* try to read index file into cache */
14658          lseek(fhi, 0, SEEK_END);
14659          cache_size = TELL(fhi);
14660          lseek(fhi, 0, SEEK_SET);
14661          cache = (char *) M_MALLOC(cache_size);
14662          if (cache) {
14663             i = read(fhi, cache, cache_size);
14664             if (i < cache_size)
14665                break;
14666             /* read first record */
14667             cp = 0;
14668             memcpy(&irec, cache, sizeof(irec));
14669          } else {
14670             /* read first record */
14671             i = read(fhi, (char *) &irec, sizeof(irec));
14672             if (i <= 0)
14673                break;
14674          }
14675
14676          /* old definition becomes invalid */
14677          old_def_offset = -1;
14678       }
14679    } while (irec.time < end_time);
14680
14681    if (cache)
14682       M_FREE(cache);
14683    close(fh);
14684    close(fhd);
14685    close(fhi);
14686
14687    *dbsize = *n * var_size;
14688    *tbsize = *n * sizeof(DWORD);
14689
14690    return HS_SUCCESS;
14691 }
INT hs_search_file (DWORD * ltime, INT direction)
Definition at line 13394 of file midas.c.
References HS_FILE_ERROR, hs_gen_index(), hs_open_file(), HS_SUCCESS, and time.
Referenced by hs_count_events(), hs_count_vars(), hs_dump(), hs_enum_events(), hs_enum_vars(), hs_get_event_id(), hs_get_var(), and hs_read().
13397          : hs_search_file
13398
13399   Purpose: Search an history file for a given date. If not found,
13400            look for files after date (direction==1) or before date
13401            (direction==-1) up to one year.
13402
13403   Input:
13404     DWORD  *ltime           Date of history file
13405     INT    direction        Search direction
13406
13407   Output:
13408     DWORD  *ltime           Date of history file found
13409
13410   Function value:
13411     HS_SUCCESS              Successful completion
13412     HS_FILE_ERROR           No file found
13413
13414 \********************************************************************/
13415 {
13416    DWORD lt;
13417    int fh, fhd, fhi;
13418    struct tm *tms;
13419
13420    if (*ltime == 0)
13421       *ltime = time(NULL);
13422
13423    lt = *ltime;
13424    do {
13425       /* try to open history file for date "lt" */
13426       hs_open_file(lt, "hst", O_RDONLY, &fh);
13427
13428       /* if not found, look for next day */
13429       if (fh < 0)
13430          lt += direction * 3600 * 24;
13431
13432       /* stop if more than a year before starting point or in the future */
13433    } while (fh < 0 && (INT) * ltime - (INT) lt < 3600 * 24 * 365 &&
13434             lt < (DWORD) time(NULL));
13435
13436    if (fh < 0)
13437       return HS_FILE_ERROR;
13438
13439    if (lt != *ltime) {
13440       /* if switched to new day, set start_time to 0:00 */
13441       tms = localtime((const time_t *) &lt);
13442       tms->tm_hour = tms->tm_min = tms->tm_sec = 0;
13443       *ltime = mktime(tms);
13444    }
13445
13446    /* check if index files are there */
13447    hs_open_file(*ltime, "idf", O_RDONLY, &fhd);
13448    hs_open_file(*ltime, "idx", O_RDONLY, &fhi);
13449
13450    close(fh);
13451    close(fhd);
13452    close(fhi);
13453
13454    /* generate them if not */
13455    if (fhd < 0 || fhi < 0)
13456       hs_gen_index(*ltime);
13457
13458    return HS_SUCCESS;
13459 }
INT hs_set_path (char * path)
dox Sets the path for future history file accesses. Should be called before any other history function is called.
Parameters:
path Directory where history files reside
Returns:
HS_SUCCESS
Definition at line 13244 of file midas.c.
References DIR_SEPARATOR, DIR_SEPARATOR_STR, HS_SUCCESS, rpc_call(), RPC_HS_SET_PATH, and rpc_is_remote().
Referenced by generate_hist_graph(), main(), open_history(), and rpc_server_dispatch().
13245 {
13246    /* set path locally and remotely */
13247    if (rpc_is_remote())
13248       rpc_call(RPC_HS_SET_PATH, path);
13249
13250    strcpy(_hs_path_name, path);
13251
13252    /* check for trailing directory seperator */
13253    if (strlen(_hs_path_name) > 0 &&
13254        _hs_path_name[strlen(_hs_path_name) - 1] != DIR_SEPARATOR)
13255       strcat(_hs_path_name, DIR_SEPARATOR_STR);
13256
13257    return HS_SUCCESS;
13258 }
INT hs_write_event (DWORD event_id, void * data, DWORD size)
Definition at line 13688 of file midas.c.
References HISTORY::base_time, HIST_RECORD::data_size, HISTORY::def_fh, DEF_RECORD::def_offset, HISTORY::def_offset, HIST_RECORD::def_offset, DEF_RECORD::event_id, INDEX_RECORD::event_id, HISTORY::event_id, HIST_RECORD::event_id, HISTORY::event_name, DEF_RECORD::event_name, HISTORY::hist_fh, HS_FILE_ERROR, hs_open_file(), HS_SUCCESS, HS_UNDEFINED_EVENT, index, HISTORY::index_fh, HISTORY::n_tag, NAME_LENGTH, INDEX_RECORD::offset, HIST_RECORD::record_type, RT_DATA, RT_DEF, tag, TELL, INDEX_RECORD::time, time, HIST_RECORD::time, and write.
Referenced by generate_hist(), log_history(), log_system_history(), rpc_server_dispatch(), tr_pause(), tr_poststop(), tr_resume(), tr_start(), tr_start1(), tr_stop(), and write_hist_speed().
13691          : hs_write_event
13692
13693   Purpose: Write an event to a history file.
13694
13695   Input:
13696     DWORD  event_id         Event ID
13697     void   *data            Data buffer containing event
13698     DWORD  size             Data buffer size in bytes
13699
13700   Output:
13701     none
13702                             future hs_write_event
13703
13704   Function value:
13705     HS_SUCCESS              Successful completion
13706     HS_NO_MEMEORY           Out of memory
13707     HS_FILE_ERROR           Cannot write to history file
13708     HS_UNDEFINED_EVENT      Event was not defined via hs_define_event
13709
13710 \********************************************************************/
13711 {
13712 /* history events are only written locally (?)
13713
13714   if (rpc_is_remote())
13715     return rpc_call(RPC_HS_WRITE_EVENT, event_id, data, size);
13716 */
13717    HIST_RECORD rec, drec;
13718    DEF_RECORD def_rec;
13719    INDEX_RECORD irec;
13720    int fh, fhi, fhd;
13721    INT index;
13722    struct tm tmb, tmr;
13723
13724    /* find index to history structure */
13725    for (index = 0; index < _history_entries; index++)
13726       if (_history[index].event_id == event_id)
13727          break;
13728    if (index == _history_entries)
13729       return HS_UNDEFINED_EVENT;
13730
13731    /* assemble record header */
13732    rec.record_type = RT_DATA;
13733    rec.event_id = _history[index].event_id;
13734    rec.time = time(NULL);
13735    rec.def_offset = _history[index].def_offset;
13736    rec.data_size = size;
13737
13738    irec.event_id = _history[index].event_id;
13739    irec.time = rec.time;
13740
13741    /* check if new day */
13742    memcpy(&tmr, localtime((const time_t *) &rec.time), sizeof(tmr));
13743    memcpy(&tmb, localtime((const time_t *) &_history[index].base_time), sizeof(tmb));
13744
13745    if (tmr.tm_yday != tmb.tm_yday) {
13746       /* close current history file */
13747       close(_history[index].hist_fh);
13748       close(_history[index].def_fh);
13749       close(_history[index].index_fh);
13750
13751       /* open new history file */
13752       hs_open_file(rec.time, "hst", O_CREAT | O_RDWR, &fh);
13753       if (fh < 0)
13754          return HS_FILE_ERROR;
13755
13756       /* open new index file */
13757       hs_open_file(rec.time, "idx", O_CREAT | O_RDWR, &fhi);
13758       if (fhi < 0)
13759          return HS_FILE_ERROR;
13760
13761       /* open new definition index file */
13762       hs_open_file(rec.time, "idf", O_CREAT | O_RDWR, &fhd);
13763       if (fhd < 0)
13764          return HS_FILE_ERROR;
13765
13766       lseek(fh, 0, SEEK_END);
13767       lseek(fhi, 0, SEEK_END);
13768       lseek(fhd, 0, SEEK_END);
13769
13770       /* remember new file handles */
13771       _history[index].hist_fh = fh;
13772       _history[index].index_fh = fhi;
13773       _history[index].def_fh = fhd;
13774
13775       _history[index].def_offset = TELL(fh);
13776       rec.def_offset = _history[index].def_offset;
13777
13778       tmr.tm_hour = tmr.tm_min = tmr.tm_sec = 0;
13779       _history[index].base_time = mktime(&tmr);
13780
13781       /* write definition from _history structure */
13782       drec.record_type = RT_DEF;
13783       drec.event_id = _history[index].event_id;
13784       drec.time = rec.time;
13785       drec.data_size = _history[index].n_tag * sizeof(TAG);
13786
13787       write(fh, (char *) &drec, sizeof(drec));
13788       write(fh, _history[index].event_name, NAME_LENGTH);
13789       write(fh, (char *) _history[index].tag, drec.data_size);
13790
13791       /* write definition index record */
13792       def_rec.event_id = _history[index].event_id;
13793       memcpy(def_rec.event_name, _history[index].event_name, sizeof(def_rec.event_name));
13794       def_rec.def_offset = _history[index].def_offset;
13795       write(fhd, (char *) &def_rec, sizeof(def_rec));
13796    }
13797
13798    /* got to end of file */
13799    lseek(_history[index].hist_fh, 0, SEEK_END);
13800    irec.offset = TELL(_history[index].hist_fh);
13801
13802    /* write record header */
13803    write(_history[index].hist_fh, (char *) &rec, sizeof(rec));
13804
13805    /* write data */
13806    write(_history[index].hist_fh, (char *) data, size);
13807
13808    /* write index record */
13809    lseek(_history[index].index_fh, 0, SEEK_END);
13810    if (write(_history[index].index_fh, (char *) &irec, sizeof(irec)) < sizeof(irec))
13811       return HS_FILE_ERROR;
13812
13813    return HS_SUCCESS;
13814 }
Variable Documentation
HISTORY* _history [static]
dox
Definition at line 13230 of file midas.c.
INT _history_entries = 0 [static]
Definition at line 13231 of file midas.c.
char _hs_path_name[MAX_STRING_LENGTH] [static]
Definition at line 13232 of file midas.c.