AlcapDAQ:Rootana: Midas Elog Functions (el_xxx)
Midas Elog Functions (el_xxx)
[The midas.h & midas.c]
Functions
void el_decode (char *message, char *key, char *result, int size)
INT el_submit (int run, char *author, char *type, char *system, char *subject, char *text, char *reply_to, char *encoding, char *afilename1, char *buffer1, INT buffer_size1, char *afilename2, char *buffer2, INT buffer_size2, char *afilename3, char *buffer3, INT buffer_size3, char *tag, INT tag_size)
INT el_search_message (char *tag, int *fh, BOOL walk)
INT el_retrieve (char *tag, char *date, int *run, char *author, char *type, char *system, char *subject, char *text, int *textsize, char *orig_tag, char *reply_tag, char *attachment1, char *attachment2, char *attachment3, char *encoding)
INT el_search_run (int run, char *return_tag)
INT el_delete_message (char *tag)
Detailed Description
dox dox dox
Function Documentation
void el_decode (char * message, char * key, char * result, int size)
dox
Definition at line 15018 of file midas.c.
Referenced by el_retrieve(), and el_submit().
15019 {
15020    char *rstart = result;
15021    char *pc;
15022
15023    if (result == NULL)
15024       return;
15025
15026    *result = 0;
15027
15028    if (strstr(message, key)) {
15029       for (pc = strstr(message, key) + strlen(key); *pc != '\n';)
15030          *result++ = *pc++;
15031       *result = 0;
15032    }
15033
15034    assert((int)strlen(rstart) < size);
15035 }
INT el_delete_message (char * tag)
Definition at line 15854 of file midas.c.
References buffer, cm_get_experiment_database(), cm_get_experiment_mutex(), db_get_value(), DB_SUCCESS, DIR_SEPARATOR, DIR_SEPARATOR_STR, EL_FILE_ERROR, EL_SUCCESS, FALSE, file_name, hDB, M_FREE, M_MALLOC, n, O_BINARY, offset, read, size, ss_mutex_release(), ss_mutex_wait_for(), status, TELL, TID_STRING, TRUE, and write.
Referenced by show_elog_delete().
15857          : el_submit
15858
15859   Purpose: Submit an ELog entry
15860
15861   Input:
15862     char   *tag             Message tage
15863
15864   Output:
15865     <none>
15866
15867   Function value:
15868     EL_SUCCESS              Successful completion
15869
15870 \********************************************************************/
15871 {
15872 #ifdef LOCAL_ROUTINES
15873    INT n, size, fh, mutex, offset = 0, tail_size, status;
15874    char dir[256], str[256], file_name[256];
15875    HNDLE hDB;
15876    char *buffer = NULL;
15877
15878    cm_get_experiment_database(&hDB, NULL);
15879
15880    /* request semaphore */
15881    cm_get_experiment_mutex(NULL, &mutex);
15882    ss_mutex_wait_for(mutex, 0);
15883
15884    /* generate file name YYMMDD.log in data directory */
15885    cm_get_experiment_database(&hDB, NULL);
15886
15887    size = sizeof(dir);
15888    memset(dir, 0, size);
15889    status = db_get_value(hDB, 0, "/Logger/Elog dir", dir, &size, TID_STRING, FALSE);
15890    if (status != DB_SUCCESS)
15891       db_get_value(hDB, 0, "/Logger/Data dir", dir, &size, TID_STRING, TRUE);
15892
15893    if (dir[0] != 0 && dir[strlen(dir) - 1] != DIR_SEPARATOR)
15894       strcat(dir, DIR_SEPARATOR_STR);
15895
15896    strcpy(str, tag);
15897    if (strchr(str, '.')) {
15898       offset = atoi(strchr(str, '.') + 1);
15899       *strchr(str, '.') = 0;
15900    }
15901    sprintf(file_name, "%s%s.log", dir, str);
15902    fh = open(file_name, O_CREAT | O_RDWR | O_BINARY, 0644);
15903    if (fh < 0) {
15904       ss_mutex_release(mutex);
15905       return EL_FILE_ERROR;
15906    }
15907    lseek(fh, offset, SEEK_SET);
15908    read(fh, str, 16);
15909    size = atoi(str + 9);
15910
15911    /* buffer tail of logfile */
15912    lseek(fh, 0, SEEK_END);
15913    tail_size = TELL(fh) - (offset + size);
15914
15915    if (tail_size > 0) {
15916       buffer = (char *) M_MALLOC(tail_size);
15917       if (buffer == NULL) {
15918          close(fh);
15919          ss_mutex_release(mutex);
15920          return EL_FILE_ERROR;
15921       }
15922
15923       lseek(fh, offset + size, SEEK_SET);
15924       n = read(fh, buffer, tail_size);
15925    }
15926    lseek(fh, offset, SEEK_SET);
15927
15928    if (tail_size > 0) {
15929       n = write(fh, buffer, tail_size);
15930       M_FREE(buffer);
15931    }
15932
15933    /* truncate file here */
15934 #ifdef OS_WINNT
15935    chsize(fh, TELL(fh));
15936 #else
15937    ftruncate(fh, TELL(fh));
15938 #endif
15939
15940    /* if file length gets zero, delete file */
15941    tail_size = lseek(fh, 0, SEEK_END);
15942    close(fh);
15943
15944    if (tail_size == 0)
15945       remove(file_name);
15946
15947    /* release elog mutex */
15948    ss_mutex_release(mutex);
15949 #endif                          /* LOCAL_ROUTINES */
15950
15951    return EL_SUCCESS;
15952 }
INT el_retrieve (char * tag, char * date, int * run, char * author, char * type, char * system, char * subject, char * text, int * textsize, char * orig_tag, char * reply_tag, char * attachment1, char * attachment2, char * attachment3, char * encoding)
Definition at line 15633 of file midas.c.
References el_decode(), EL_LAST_MSG, el_search_message(), EL_SUCCESS, EL_TRUNCATED, message, offset, p, read, size, TELL, and TRUE.
Referenced by el_search_run(), show_elog_new(), show_elog_page(), and show_elog_submit_query().
15639          : el_retrieve
15640
15641   Purpose: Retrieve an ELog entry by its message tab
15642
15643   Input:
15644     char   *tag             tag in the form YYMMDD.offset
15645     int    *size            Size of text buffer
15646
15647   Output:
15648     char   *tag             tag of retrieved message
15649     char   *date            Date/time of message recording
15650     int    *run             Run number
15651     char   *author          Message author
15652     char   *type            Message type
15653     char   *system          Message system
15654     char   *subject         Subject
15655     char   *text            Message text
15656     char   *orig_tag        Original message if this one is a reply
15657     char   *reply_tag       Reply for current message
15658     char   *attachment1/2/3 File attachment
15659     char   *encoding        Encoding of message
15660     int    *size            Actual message text size
15661
15662   Function value:
15663     EL_SUCCESS              Successful completion
15664     EL_LAST_MSG             Last message in log
15665
15666 \********************************************************************/
15667 {
15668    int size, fh = 0, offset, search_status, rd;
15669    char str[256], *p;
15670    char message[10000], thread[256], attachment_all[256];
15671
15672    if (tag[0]) {
15673       search_status = el_search_message(tag, &fh, TRUE);
15674       if (search_status != EL_SUCCESS)
15675          return search_status;
15676    } else {
15677       /* open most recent message */
15678       strcpy(tag, "-1");
15679       search_status = el_search_message(tag, &fh, TRUE);
15680       if (search_status != EL_SUCCESS)
15681          return search_status;
15682    }
15683
15684    /* extract message size */
15685    offset = TELL(fh);
15686    rd = read(fh, str, 15);
15687    assert(rd == 15);
15688
15689    /* make sure the input string is zero-terminated before we call atoi() */
15690    str[15] = 0;
15691
15692    /* get size */
15693    size = atoi(str+9);
15694
15695    assert(strncmp(str,"$Start$:",8) == 0);
15696    assert(size > 15);
15697    assert(size < sizeof(message));
15698
15699    memset(message, 0, sizeof(message));
15700
15701    rd = read(fh, message, size);
15702    assert(rd > 0);
15703    assert((rd+15 == size)||(rd == size));
15704
15705    close(fh);
15706
15707    /* decode message */
15708    if (strstr(message, "Run: ") && run)
15709       *run = atoi(strstr(message, "Run: ") + 5);
15710
15711    el_decode(message, "Date: ",     date,     80); /* size from show_elog_submit_query() */
15712    el_decode(message, "Thread: ", thread, sizeof(thread));
15713    el_decode(message, "Author: ",   author,   80); /* size from show_elog_submit_query() */
15714    el_decode(message, "Type: ",     type,     80); /* size from show_elog_submit_query() */
15715    el_decode(message, "System: ",   system,   80); /* size from show_elog_submit_query() */
15716    el_decode(message, "Subject: ",  subject, 256); /* size from show_elog_submit_query() */
15717    el_decode(message, "Attachment: ", attachment_all, sizeof(attachment_all));
15718    el_decode(message, "Encoding: ", encoding, 80); /* size from show_elog_submit_query() */
15719
15720    /* break apart attachements */
15721    if (attachment1 && attachment2 && attachment3) {
15722       attachment1[0] = attachment2[0] = attachment3[0] = 0;
15723       p = strtok(attachment_all, ",");
15724       if (p != NULL) {
15725          strcpy(attachment1, p);
15726          p = strtok(NULL, ",");
15727          if (p != NULL) {
15728             strcpy(attachment2, p);
15729             p = strtok(NULL, ",");
15730             if (p != NULL)
15731                strcpy(attachment3, p);
15732          }
15733       }
15734
15735       assert(strlen(attachment1) < 256); /* size from show_elog_submit_query() */
15736       assert(strlen(attachment2) < 256); /* size from show_elog_submit_query() */
15737       assert(strlen(attachment3) < 256); /* size from show_elog_submit_query() */
15738    }
15739
15740    /* conver thread in reply-to and reply-from */
15741    if (orig_tag != NULL && reply_tag != NULL) {
15742       p = strtok(thread, " \r");
15743       if (p != NULL)
15744          strcpy(orig_tag, p);
15745       else
15746          strcpy(orig_tag, "");
15747       p = strtok(NULL, " \r");
15748       if (p != NULL)
15749          strcpy(reply_tag, p);
15750       else
15751          strcpy(reply_tag, "");
15752       if (atoi(orig_tag) == 0)
15753          orig_tag[0] = 0;
15754       if (atoi(reply_tag) == 0)
15755          reply_tag[0] = 0;
15756    }
15757
15758    p = strstr(message, "========================================\n");
15759
15760    if (text != NULL) {
15761       if (p != NULL) {
15762          p += 41;
15763          if ((int) strlen(p) >= *textsize) {
15764             strncpy(text, p, *textsize - 1);
15765             text[*textsize - 1] = 0;
15766             return EL_TRUNCATED;
15767          } else {
15768             strcpy(text, p);
15769
15770             /* strip end tag */
15771             if (strstr(text, "$End$"))
15772                *strstr(text, "$End$") = 0;
15773
15774             *textsize = strlen(text);
15775          }
15776       } else {
15777          text[0] = 0;
15778          *textsize = 0;
15779       }
15780    }
15781
15782    if (search_status == EL_LAST_MSG)
15783       return EL_LAST_MSG;
15784
15785    return EL_SUCCESS;
15786 }
INT el_search_message (char * tag, int * fh, BOOL walk)
dox
Definition at line 15379 of file midas.c.
References abs, cm_get_experiment_database(), db_get_value(), DB_SUCCESS, DIR_SEPARATOR, DIR_SEPARATOR_STR, EL_FILE_ERROR, EL_FIRST_MSG, EL_LAST_MSG, el_search_message(), EL_SUCCESS, FALSE, file_name, hDB, i, last, O_BINARY, offset, read, size, status, TELL, TID_STRING, time, and TRUE.
Referenced by el_retrieve(), el_search_message(), el_search_run(), el_submit(), and show_elog_page().
15380 {
15381    int i, size, offset, direction, last, status;
15382    struct tm *tms, ltms;
15383    DWORD lt, ltime, lact;
15384    char str[256], file_name[256], dir[256];
15385    HNDLE hDB;
15386
15387 #if !defined(OS_VXWORKS)
15388 #if !defined(OS_VMS)
15389    tzset();
15390 #endif
15391 #endif
15392
15393    /* open file */
15394    cm_get_experiment_database(&hDB, NULL);
15395
15396    size = sizeof(dir);
15397    memset(dir, 0, size);
15398    status = db_get_value(hDB, 0, "/Logger/Elog dir", dir, &size, TID_STRING, FALSE);
15399    if (status != DB_SUCCESS)
15400       db_get_value(hDB, 0, "/Logger/Data dir", dir, &size, TID_STRING, TRUE);
15401
15402    if (dir[0] != 0 && dir[strlen(dir) - 1] != DIR_SEPARATOR)
15403       strcat(dir, DIR_SEPARATOR_STR);
15404
15405    /* check tag for direction */
15406    direction = 0;
15407    if (strpbrk(tag, "+-")) {
15408       direction = atoi(strpbrk(tag, "+-"));
15409       *strpbrk(tag, "+-") = 0;
15410    }
15411
15412    /* if tag is given, open file directly */
15413    if (tag[0]) {
15414       /* extract time structure from tag */
15415       tms = &ltms;
15416       memset(tms, 0, sizeof(struct tm));
15417       tms->tm_year = (tag[0] - '0') * 10 + (tag[1] - '0');
15418       tms->tm_mon = (tag[2] - '0') * 10 + (tag[3] - '0') - 1;
15419       tms->tm_mday = (tag[4] - '0') * 10 + (tag[5] - '0');
15420       tms->tm_hour = 12;
15421
15422       if (tms->tm_year < 90)
15423          tms->tm_year += 100;
15424       ltime = lt = mktime(tms);
15425
15426       strcpy(str, tag);
15427       if (strchr(str, '.')) {
15428          offset = atoi(strchr(str, '.') + 1);
15429          *strchr(str, '.') = 0;
15430       } else
15431          return EL_FILE_ERROR;
15432
15433       do {
15434          tms = localtime((const time_t *) &ltime);
15435
15436          sprintf(file_name, "%s%02d%02d%02d.log", dir,
15437                  tms->tm_year % 100, tms->tm_mon + 1, tms->tm_mday);
15438          *fh = open(file_name, O_RDWR | O_BINARY, 0644);
15439
15440          if (*fh < 0) {
15441             if (!walk)
15442                return EL_FILE_ERROR;
15443
15444             if (direction == -1)
15445                ltime -= 3600 * 24;      /* one day back */
15446             else
15447                ltime += 3600 * 24;      /* go forward one day */
15448
15449             /* set new tag */
15450             tms = localtime((const time_t *) &ltime);
15451             sprintf(tag, "%02d%02d%02d.0", tms->tm_year % 100, tms->tm_mon + 1,
15452                     tms->tm_mday);
15453          }
15454
15455          /* in forward direction, stop today */
15456          if (direction != -1 && ltime > (DWORD) time(NULL) + 3600 * 24)
15457             break;
15458
15459          /* in backward direction, go back 10 years */
15460          if (direction == -1 && abs((INT) lt - (INT) ltime) > 3600 * 24 * 365 * 10)
15461             break;
15462
15463       } while (*fh < 0);
15464
15465       if (*fh < 0)
15466          return EL_FILE_ERROR;
15467
15468       lseek(*fh, offset, SEEK_SET);
15469
15470       /* check if start of message */
15471       i = read(*fh, str, 15);
15472       if (i <= 0) {
15473          close(*fh);
15474          return EL_FILE_ERROR;
15475       }
15476
15477       if (strncmp(str, "$Start$: ", 9) != 0) {
15478          close(*fh);
15479          return EL_FILE_ERROR;
15480       }
15481
15482       lseek(*fh, offset, SEEK_SET);
15483    }
15484
15485    /* open most recent file if no tag given */
15486    if (tag[0] == 0) {
15487       time((long *) &lt);
15488       ltime = lt;
15489       do {
15490          tms = localtime((const time_t *) &ltime);
15491
15492          sprintf(file_name, "%s%02d%02d%02d.log", dir,
15493                  tms->tm_year % 100, tms->tm_mon + 1, tms->tm_mday);
15494          *fh = open(file_name, O_RDWR | O_BINARY, 0644);
15495
15496          if (*fh < 0)
15497             ltime -= 3600 * 24; /* one day back */
15498
15499       } while (*fh < 0 && (INT) lt - (INT) ltime < 3600 * 24 * 365);
15500
15501       if (*fh < 0)
15502          return EL_FILE_ERROR;
15503
15504       /* remember tag */
15505       sprintf(tag, "%02d%02d%02d", tms->tm_year % 100, tms->tm_mon + 1, tms->tm_mday);
15506
15507       lseek(*fh, 0, SEEK_END);
15508
15509       sprintf(tag + strlen(tag), ".%d", (int) TELL(*fh));
15510    }
15511
15512
15513    if (direction == -1) {
15514       /* seek previous message */
15515
15516       if (TELL(*fh) == 0) {
15517          /* go back one day */
15518          close(*fh);
15519
15520          lt = ltime;
15521          do {
15522             lt -= 3600 * 24;
15523             tms = localtime((const time_t *) &lt);
15524             sprintf(str, "%02d%02d%02d.0",
15525                     tms->tm_year % 100, tms->tm_mon + 1, tms->tm_mday);
15526
15527             status = el_search_message(str, fh, FALSE);
15528
15529          } while (status != EL_SUCCESS && (INT) ltime - (INT) lt < 3600 * 24 * 365);
15530
15531          if (status != EL_SUCCESS)
15532             return EL_FIRST_MSG;
15533
15534          /* adjust tag */
15535          strcpy(tag, str);
15536
15537          /* go to end of current file */
15538          lseek(*fh, 0, SEEK_END);
15539       }
15540
15541       /* read previous message size */
15542       lseek(*fh, -17, SEEK_CUR);
15543       i = read(*fh, str, 17);
15544       if (i <= 0) {
15545          close(*fh);
15546          return EL_FILE_ERROR;
15547       }
15548
15549       if (strncmp(str, "$End$: ", 7) != 0) {
15550          close(*fh);
15551          return EL_FILE_ERROR;
15552       }
15553
15554       /* make sure the input string to atoi() is zero-terminated:
15555        * $End$:      355garbage
15556        * 01234567890123456789 */
15557       str[15] = 0;
15558
15559       size = atoi(str + 7);
15560       assert(size > 15);
15561
15562       lseek(*fh, -size, SEEK_CUR);
15563
15564       /* adjust tag */
15565       sprintf(strchr(tag, '.') + 1, "%d", (int) TELL(*fh));
15566    }
15567
15568    if (direction == 1) {
15569       /* seek next message */
15570
15571       /* read current message size */
15572       last = TELL(*fh);
15573
15574       i = read(*fh, str, 15);
15575       if (i <= 0) {
15576          close(*fh);
15577          return EL_FILE_ERROR;
15578       }
15579       lseek(*fh, -15, SEEK_CUR);
15580
15581       if (strncmp(str, "$Start$: ", 9) != 0) {
15582          close(*fh);
15583          return EL_FILE_ERROR;
15584       }
15585
15586       /* make sure the input string to atoi() is zero-terminated
15587        * $Start$:    606garbage
15588        * 01234567890123456789 */
15589       str[15] = 0;
15590
15591       size = atoi(str+9);
15592       assert(size > 15);
15593
15594       lseek(*fh, size, SEEK_CUR);
15595
15596       /* if EOF, goto next day */
15597       i = read(*fh, str, 15);
15598       if (i < 15) {
15599          close(*fh);
15600          time((long *) &lact);
15601
15602          lt = ltime;
15603          do {
15604             lt += 3600 * 24;
15605             tms = localtime((const time_t *) &lt);
15606             sprintf(str, "%02d%02d%02d.0",
15607                     tms->tm_year % 100, tms->tm_mon + 1, tms->tm_mday);
15608
15609             status = el_search_message(str, fh, FALSE);
15610
15611          } while (status != EL_SUCCESS && (INT) lt - (INT) lact < 3600 * 24);
15612
15613          if (status != EL_SUCCESS)
15614             return EL_LAST_MSG;
15615
15616          /* adjust tag */
15617          strcpy(tag, str);
15618
15619          /* go to beginning of current file */
15620          lseek(*fh, 0, SEEK_SET);
15621       } else
15622          lseek(*fh, -15, SEEK_CUR);
15623
15624       /* adjust tag */
15625       sprintf(strchr(tag, '.') + 1, "%d", (int) TELL(*fh));
15626    }
15627
15628    return EL_SUCCESS;
15629 }
INT el_search_run (int run, char * return_tag)
Definition at line 15790 of file midas.c.
References EL_FIRST_MSG, EL_LAST_MSG, el_retrieve(), el_search_message(), EL_SUCCESS, status, tag, and TRUE.
Referenced by show_elog_submit_query().
15793          : el_search_run
15794
15795   Purpose: Find first message belonging to a specific run
15796
15797   Input:
15798     int    run              Run number
15799
15800   Output:
15801     char   *tag             tag of retrieved message
15802
15803   Function value:
15804     EL_SUCCESS              Successful completion
15805     EL_LAST_MSG             Last message in log
15806
15807 \********************************************************************/
15808 {
15809    int actual_run, fh, status;
15810    char tag[256];
15811
15812    tag[0] = return_tag[0] = 0;
15813
15814    do {
15815       /* open first message in file */
15816       strcat(tag, "-1");
15817       status = el_search_message(tag, &fh, TRUE);
15818       if (status == EL_FIRST_MSG)
15819          break;
15820       if (status != EL_SUCCESS)
15821          return status;
15822       close(fh);
15823
15824       if (strchr(tag, '.') != NULL)
15825          strcpy(strchr(tag, '.'), ".0");
15826
15827       el_retrieve(tag, NULL, &actual_run, NULL, NULL,
15828                   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
15829    } while (actual_run >= run);
15830
15831    while (actual_run < run) {
15832       strcat(tag, "+1");
15833       status = el_search_message(tag, &fh, TRUE);
15834       if (status == EL_LAST_MSG)
15835          break;
15836       if (status != EL_SUCCESS)
15837          return status;
15838       close(fh);
15839
15840       el_retrieve(tag, NULL, &actual_run, NULL, NULL,
15841                   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
15842    }
15843
15844    strcpy(return_tag, tag);
15845
15846    if (status == EL_LAST_MSG || status == EL_FIRST_MSG)
15847       return status;
15848
15849    return EL_SUCCESS;
15850 }
INT el_submit (int run, char * author, char * type, char * system, char * subject, char * text, char * reply_to, char * encoding, char * afilename1, char * buffer1, INT buffer_size1, char * afilename2, char * buffer2, INT buffer_size2, char * afilename3, char * buffer3, INT buffer_size3, char * tag, INT tag_size)
dox Submit an ELog entry.
Parameters:
run Run Number.
author Message author.
type Message type.
system Message system.
subject Subject.
text Message text.
reply_to In reply to this message.
encoding Text encoding, either HTML or plain.
afilename1 File name of attachment.
buffer1 File contents.
buffer_size1 Size of buffer in bytes.
afilename2 File name of attachment.
buffer2 File contents.
buffer_size2 Size of buffer in bytes.
afilename3 File name of attachment.
buffer3 File contents.
buffer_size3 Size of buffer in bytes.
tag If given, edit existing message.
tag_size Maximum size of tag.
Returns:
EL_SUCCESS
Definition at line 15064 of file midas.c.
References buffer, buffer_size, cm_get_experiment_database(), cm_get_experiment_mutex(), cm_msg, db_get_value(), DB_SUCCESS, DIR_SEPARATOR, DIR_SEPARATOR_STR, el_decode(), EL_FILE_ERROR, el_search_message(), EL_SUCCESS, FALSE, file_name, hDB, index, last, M_FREE, M_MALLOC, MERROR, message, n, O_BINARY, offset, p, read, rpc_call(), RPC_EL_SUBMIT, rpc_is_remote(), run_number, size, ss_mutex_release(), ss_mutex_wait_for(), status, SUCCESS, TELL, TID_INT, TID_STRING, time, TRUE, and write.
Referenced by al_trigger_class(), rpc_server_dispatch(), and submit_elog().
15069 {
15070    if (rpc_is_remote())
15071       return rpc_call(RPC_EL_SUBMIT, run, author, type, system, subject,
15072                       text, reply_to, encoding,
15073                       afilename1, buffer1, buffer_size1,
15074                       afilename2, buffer2, buffer_size2,
15075                       afilename3, buffer3, buffer_size3, tag, tag_size);
15076
15077 #ifdef LOCAL_ROUTINES
15078    {
15079       INT n, size, fh, status, run_number, mutex, buffer_size = 0, index, offset =
15080           0, tail_size = 0;
15081       struct tm *tms = NULL;
15082       char afilename[256], file_name[256], afile_name[3][256], dir[256], str[256],
15083           start_str[80], end_str[80], last[80], date[80], thread[80], attachment[256];
15084       HNDLE hDB;
15085       time_t now;
15086       char message[10000], *p, *buffer = NULL;
15087       BOOL bedit;
15088
15089       cm_get_experiment_database(&hDB, NULL);
15090
15091       bedit = (tag[0] != 0);
15092
15093       /* request semaphore */
15094       cm_get_experiment_mutex(NULL, &mutex);
15095       ss_mutex_wait_for(mutex, 0);
15096
15097       /* get run number from ODB if not given */
15098       if (run > 0)
15099          run_number = run;
15100       else {
15101          /* get run number */
15102          size = sizeof(run_number);
15103          status =
15104              db_get_value(hDB, 0, "/Runinfo/Run number", &run_number, &size, TID_INT,
15105                           TRUE);
15106          assert(status == SUCCESS);
15107       }
15108
15109       if (run_number < 0) {
15110          cm_msg(MERROR, "el_submit", "aborting on attempt to use invalid run number %d",
15111                 run_number);
15112          abort();
15113       }
15114
15115       for (index = 0; index < 3; index++) {
15116          /* generate filename for attachment */
15117          afile_name[index][0] = file_name[0] = 0;
15118
15119          if (index == 0) {
15120             strcpy(afilename, afilename1);
15121             buffer = buffer1;
15122             buffer_size = buffer_size1;
15123          } else if (index == 1) {
15124             strcpy(afilename, afilename2);
15125             buffer = buffer2;
15126             buffer_size = buffer_size2;
15127          } else if (index == 2) {
15128             strcpy(afilename, afilename3);
15129             buffer = buffer3;
15130             buffer_size = buffer_size3;
15131          }
15132
15133          if (afilename[0]) {
15134             strcpy(file_name, afilename);
15135             p = file_name;
15136             while (strchr(p, ':'))
15137                p = strchr(p, ':') + 1;
15138             while (strchr(p, '\\'))
15139                p = strchr(p, '\\') + 1; /* NT */
15140             while (strchr(p, '/'))
15141                p = strchr(p, '/') + 1;  /* Unix */
15142             while (strchr(p, ']'))
15143                p = strchr(p, ']') + 1;  /* VMS */
15144
15145             /* assemble ELog filename */
15146             if (p[0]) {
15147                dir[0] = 0;
15148                if (hDB > 0) {
15149                   size = sizeof(dir);
15150                   memset(dir, 0, size);
15151                   status =
15152                       db_get_value(hDB, 0, "/Logger/Elog dir", dir, &size, TID_STRING,
15153                                    FALSE);
15154                   if (status != DB_SUCCESS)
15155                      db_get_value(hDB, 0, "/Logger/Data dir", dir, &size, TID_STRING,
15156                                   TRUE);
15157
15158                   if (dir[0] != 0 && dir[strlen(dir) - 1] != DIR_SEPARATOR)
15159                      strcat(dir, DIR_SEPARATOR_STR);
15160                }
15161 #if !defined(OS_VXWORKS)
15162 #if !defined(OS_VMS)
15163                tzset();
15164 #endif
15165 #endif
15166
15167                time((time_t *) & now);
15168                tms = localtime((const time_t *) &now);
15169
15170                strcpy(str, p);
15171                sprintf(afile_name[index], "%02d%02d%02d_%02d%02d%02d_%s",
15172                        tms->tm_year % 100, tms->tm_mon + 1, tms->tm_mday,
15173                        tms->tm_hour, tms->tm_min, tms->tm_sec, str);
15174                sprintf(file_name, "%s%02d%02d%02d_%02d%02d%02d_%s", dir,
15175                        tms->tm_year % 100, tms->tm_mon + 1, tms->tm_mday,
15176                        tms->tm_hour, tms->tm_min, tms->tm_sec, str);
15177
15178                /* save attachment */
15179                fh = open(file_name, O_CREAT | O_RDWR | O_BINARY, 0644);
15180                if (fh < 0) {
15181                   cm_msg(MERROR, "el_submit", "Cannot write attachment file \"%s\"",
15182                          file_name);
15183                } else {
15184                   write(fh, buffer, buffer_size);
15185                   close(fh);
15186                }
15187             }
15188          }
15189       }
15190
15191       /* generate new file name YYMMDD.log in data directory */
15192       cm_get_experiment_database(&hDB, NULL);
15193
15194       size = sizeof(dir);
15195       memset(dir, 0, size);
15196       status = db_get_value(hDB, 0, "/Logger/Elog dir", dir, &size, TID_STRING, FALSE);
15197       if (status != DB_SUCCESS)
15198          db_get_value(hDB, 0, "/Logger/Data dir", dir, &size, TID_STRING, TRUE);
15199
15200       if (dir[0] != 0 && dir[strlen(dir) - 1] != DIR_SEPARATOR)
15201          strcat(dir, DIR_SEPARATOR_STR);
15202
15203 #if !defined(OS_VXWORKS)
15204 #if !defined(OS_VMS)
15205       tzset();
15206 #endif
15207 #endif
15208
15209       if (bedit) {
15210          /* edit existing message */
15211          strcpy(str, tag);
15212          if (strchr(str, '.')) {
15213             offset = atoi(strchr(str, '.') + 1);
15214             *strchr(str, '.') = 0;
15215          }
15216          sprintf(file_name, "%s%s.log", dir, str);
15217          fh = open(file_name, O_CREAT | O_RDWR | O_BINARY, 0644);
15218          if (fh < 0) {
15219             ss_mutex_release(mutex);
15220             return EL_FILE_ERROR;
15221          }
15222          lseek(fh, offset, SEEK_SET);
15223          read(fh, str, 16);
15224          size = atoi(str + 9);
15225          read(fh, message, size);
15226
15227          el_decode(message, "Date: ", date, sizeof(date));
15228          el_decode(message, "Thread: ", thread, sizeof(thread));
15229          el_decode(message, "Attachment: ", attachment, sizeof(attachment));
15230
15231          /* buffer tail of logfile */
15232          lseek(fh, 0, SEEK_END);
15233          tail_size = TELL(fh) - (offset + size);
15234
15235          if (tail_size > 0) {
15236             buffer = (char *) M_MALLOC(tail_size);
15237             if (buffer == NULL) {
15238                close(fh);
15239                ss_mutex_release(mutex);
15240                return EL_FILE_ERROR;
15241             }
15242
15243             lseek(fh, offset + size, SEEK_SET);
15244             n = read(fh, buffer, tail_size);
15245          }
15246          lseek(fh, offset, SEEK_SET);
15247       } else {
15248          /* create new message */
15249          time((time_t *) & now);
15250          tms = localtime((const time_t *) &now);
15251
15252          sprintf(file_name, "%s%02d%02d%02d.log", dir,
15253                  tms->tm_year % 100, tms->tm_mon + 1, tms->tm_mday);
15254
15255          fh = open(file_name, O_CREAT | O_RDWR | O_BINARY, 0644);
15256          if (fh < 0) {
15257             ss_mutex_release(mutex);
15258             return EL_FILE_ERROR;
15259          }
15260
15261          strcpy(date, ctime(&now));
15262          date[24] = 0;
15263
15264          if (reply_to[0])
15265             sprintf(thread, "%16s %16s", reply_to, "0");
15266          else
15267             sprintf(thread, "%16s %16s", "0", "0");
15268
15269          lseek(fh, 0, SEEK_END);
15270       }
15271
15272       /* compose message */
15273
15274       sprintf(message, "Date: %s\n", date);
15275       sprintf(message + strlen(message), "Thread: %s\n", thread);
15276       sprintf(message + strlen(message), "Run: %d\n", run_number);
15277       sprintf(message + strlen(message), "Author: %s\n", author);
15278       sprintf(message + strlen(message), "Type: %s\n", type);
15279       sprintf(message + strlen(message), "System: %s\n", system);
15280       sprintf(message + strlen(message), "Subject: %s\n", subject);
15281
15282       /* keep original attachment if edit and no new attachment */
15283       if (bedit && afile_name[0][0] == 0 && afile_name[1][0] == 0 &&
15284           afile_name[2][0] == 0)
15285          sprintf(message + strlen(message), "Attachment: %s", attachment);
15286       else {
15287          sprintf(message + strlen(message), "Attachment: %s", afile_name[0]);
15288          if (afile_name[1][0])
15289             sprintf(message + strlen(message), ",%s", afile_name[1]);
15290          if (afile_name[2][0])
15291             sprintf(message + strlen(message), ",%s", afile_name[2]);
15292       }
15293       sprintf(message + strlen(message), "\n");
15294
15295       sprintf(message + strlen(message), "Encoding: %s\n", encoding);
15296       sprintf(message + strlen(message), "========================================\n");
15297       strcat(message, text);
15298
15299       assert(strlen(message) < sizeof(message)); /* bomb out on array overrun. */
15300
15301       size = 0;
15302       sprintf(start_str, "$Start$: %6d\n", size);
15303       sprintf(end_str, "$End$:   %6d\n\f", size);
15304
15305       size = strlen(message) + strlen(start_str) + strlen(end_str);
15306
15307       if (tag != NULL && !bedit)
15308          sprintf(tag, "%02d%02d%02d.%d", tms->tm_year % 100, tms->tm_mon + 1,
15309                  tms->tm_mday, (int) TELL(fh));
15310
15311       /* size has to fit in 6 digits */
15312       assert(size < 999999);
15313
15314       sprintf(start_str, "$Start$: %6d\n", size);
15315       sprintf(end_str, "$End$:   %6d\n\f", size);
15316
15317       write(fh, start_str, strlen(start_str));
15318       write(fh, message, strlen(message));
15319       write(fh, end_str, strlen(end_str));
15320
15321       if (bedit) {
15322          if (tail_size > 0) {
15323             n = write(fh, buffer, tail_size);
15324             M_FREE(buffer);
15325          }
15326
15327          /* truncate file here */
15328 #ifdef OS_WINNT
15329          chsize(fh, TELL(fh));
15330 #else
15331          ftruncate(fh, TELL(fh));
15332 #endif
15333       }
15334
15335       close(fh);
15336
15337       /* if reply, mark original message */
15338       if (reply_to[0] && !bedit) {
15339          strcpy(last, reply_to);
15340          do {
15341             status = el_search_message(last, &fh, FALSE);
15342             if (status == EL_SUCCESS) {
15343                /* position to next thread location */
15344                lseek(fh, 72, SEEK_CUR);
15345                memset(str, 0, sizeof(str));
15346                read(fh, str, 16);
15347                lseek(fh, -16, SEEK_CUR);
15348
15349                /* if no reply yet, set it */
15350                if (atoi(str) == 0) {
15351                   sprintf(str, "%16s", tag);
15352                   write(fh, str, 16);
15353                   close(fh);
15354                   break;
15355                } else {
15356                   /* if reply set, find last one in chain */
15357                   strcpy(last, strtok(str, " "));
15358                   close(fh);
15359                }
15360             } else
15361                /* stop on error */
15362                break;
15363
15364          } while (TRUE);
15365       }
15366
15367       /* release elog mutex */
15368       ss_mutex_release(mutex);
15369    }
15370 #endif                          /* LOCAL_ROUTINES */
15371
15372    return EL_SUCCESS;
15373 }