AlcapDAQ:Rootana: The ybos.h & ybos.c
The ybos.h & ybos.c
Data Structures
struct YBOS_INFO
struct YBOS_PHYSREC_HEADER
struct YBOS_BANK_HEADER
struct YM_CFILE
struct YM_PFILE
struct R_YM_FILE
Modules
YBOS Define
YBOS error code
YBOS Macros
YBOS Bank Functions (ybk_xxx)
Defines
#define MAX_FILE_PATH 128
#define MAX_FRAG_SIZE 2000
#define MAX_YM_FILE 8
#define NLINE 8
#define TRACE
#define INCLUDE_LOGGING
Functions
INT EXPRT yb_file_recompose (void *pevt, INT fmt, char *svpath, INT file_mode)
INT EXPRT feodb_file_dump (EQUIPMENT *eqp, char *eqpname, char *pevent, INT run_number, char *path)
void EXPRT yb_any_bank_display (void *pmbh, void *pbk, INT fmt, INT dsp_mode, INT dsp_fmt)
void EXPRT yb_any_event_display (void *pevt, INT data_fmt, INT dsp_mode, INT dsp_fmt)
INT EXPRT yb_any_all_info_display (INT what)
INT EXPRT yb_any_physrec_display (INT data_fmt)
INT EXPRT yb_any_physrec_skip (INT data_fmt, INT bl)
INT EXPRT yb_any_physrec_get (INT data_fmt, void **prec, DWORD *psize)
INT EXPRT yb_any_file_rclose (INT data_fmt)
INT EXPRT yb_any_file_ropen (char *infile, INT data_fmt)
INT EXPRT yb_any_file_wopen (INT type, INT data_fmt, char *filename, INT *hDev)
INT EXPRT yb_any_file_wclose (INT handle, INT type, INT data_fmt)
INT EXPRT yb_any_log_write (INT handle, INT data_fmt, INT type, void *prec, DWORD nbytes)
INT EXPRT yb_any_event_swap (INT data_fmt, void *pevent)
INT EXPRT yb_any_event_get (INT data_fmt, void **pevent, DWORD *psize)
void EXPRT ybk_init (DWORD *pevent)
void EXPRT ybk_create (DWORD *pevent, char *bkname, DWORD btype, void *pbkdat)
INT EXPRT ybk_close (DWORD *pevent, void *pbkdat)
INT EXPRT ybk_size (DWORD *pevent)
INT EXPRT ybk_list (DWORD *pevent, char *bklist)
INT EXPRT ybk_locate (DWORD *pevent, char *bkname, void *pdata)
INT EXPRT ybk_find (DWORD *pevent, char *bkname, DWORD *bklength, DWORD *bktype, void **pbkdata)
void EXPRT ybk_create_chaos (DWORD *pevent, char *bname, DWORD btype, void *pbkdat)
INT EXPRT ybk_iterate (DWORD *pevent, YBOS_BANK_HEADER **pybkh, void **pdata)
INT EXPRT ybk_close_chaos (DWORD *pevent, DWORD btype, void *pbkdat)
INT EXPRT ybos_event_get (DWORD **plrl, DWORD *size)
INT EXPRT ybos_get_tid_size (INT tid)
INT yb_any_dev_os_read (INT handle, INT type, void *prec, DWORD nbytes, DWORD *nread)
INT yb_any_dev_os_write (INT handle, INT type, void *prec, DWORD nbytes, DWORD *written)
INT yb_ymfile_update (int slot, int fmt, void *pevt)
INT yb_ymfile_open (int *slot, int fmt, void *pevt, char *svpath, INT file_mode)
INT yb_file_fragment (EQUIPMENT *eqp, EVENT_HEADER *pevent, INT run_number, char *path)
INT midas_event_skip (INT evtn)
INT ybos_physrec_skip (INT bl)
INT ybos_physrec_get (DWORD **prec, DWORD *readn)
INT midas_physrec_get (void *prec, DWORD *readn)
void yb_any_bank_event_display (void *pevent, INT data_fmt, INT dsp_fmt)
void yb_any_raw_event_display (void *pevent, INT data_fmt, INT dsp_fmt)
void yb_any_raw_bank_display (void *pbank, INT data_fmt, INT dsp_fmt)
void ybos_bank_display (YBOS_BANK_HEADER *pybk, INT dsp_fmt)
void midas_bank_display (BANK *pbk, INT dsp_fmt)
void midas_bank_display32 (BANK32 *pbk, INT dsp_fmt)
INT midas_event_get (void **pevent, DWORD *size)
INT ybos_event_swap (DWORD *pevt)
INT ybos_buffer_flush (LOG_CHN *log_chn, INT run_number)
INT ybos_logfile_open (INT type, char *path, HNDLE *handle)
INT ybos_logfile_close (INT type, HNDLE handle)
void ybos_log_dump (LOG_CHN *log_chn, short int event_id, INT run_number)
Variables
INT yb_tid_size []
DWORD * pbot
DWORD * pbktop = NULL
char * ptopmrd
DWORD magta [3] = { 0x00000004, 0x544f422a, 0x00007ff8 }
R_YM_FILE ymfile [MAX_YM_FILE]
struct stat * filestat
struct {
INT handle
char name [MAX_FILE_PATH]
char * pmp
EVENT_HEADER * pmh
EVENT_HEADER * pme
char * pmrd
char * pmagta
YBOS_PHYSREC_HEADER * pyh
DWORD * pylrl
DWORD * pyrd
DWORD evtn
DWORD serial
DWORD evtlen
DWORD size
DWORD recn
INT fmt
INT type
DWORD runn
BOOL zipfile
BOOL magtafl
} my
Detailed Description
dox
Define Documentation
#define INCLUDE_LOGGING
Definition at line 276 of file ybos.c.
#define MAX_FILE_PATH 128
YBOS FILE parameters
Definition at line 393 of file ybos.h.
Referenced by build_log_list(), feodb_file_dump(), lazy_copy(), lazy_file_compose(), lazy_file_exists(), lazy_log_update(), lazy_main(), lazy_select_purge(), and lazy_update_list().
#define MAX_FRAG_SIZE 2000
Definition at line 394 of file ybos.h.
Referenced by yb_file_fragment().
#define MAX_YM_FILE 8
Definition at line 395 of file ybos.h.
Referenced by yb_file_recompose(), and yb_ymfile_open().
#define NLINE 8
Definition at line 396 of file ybos.h.
Referenced by yb_any_physrec_display(), yb_any_raw_bank_display(), and yb_any_raw_event_display().
#define TRACE
dox
Definition at line 264 of file ybos.c.
Function Documentation
INT EXPRT feodb_file_dump (EQUIPMENT * eqp, char * eqpname, char * pevent, INT run_number, char * path)
dox
Definition at line 796 of file ybos.c.
References cm_get_experiment_database(), cm_msg, db_enum_key(), db_find_key(), db_get_path(), db_get_value(), DB_INVALID_NAME, DB_NO_MORE_SUBKEYS, DB_SUCCESS, equal_ustring(), FALSE, hDB, hKey, index, MAX_FILE_PATH, MINFO, eqpmnt::name, size, status, TID_STRING, TRUE, yb_file_fragment(), and YB_SUCCESS.
Referenced by files_dump().
       : feodb_file_dump
Purpose: Access ODB for the /Equipment/<equip_name>/Dump.
in order to scan for file name and dump the files content to the
Midas buffer channel.
Input:
EQUIPMENT * eqp           Current equipment
INT       run_number      current run_number
char      * path          full file name specification
Output:
none
Function value:
0                      Successful completion
DB_INVALID_NAME        Equipment doesn't match request
\********************************************************************/
{
   EQUIPMENT *peqp;
   INT index, size, status;
   HNDLE hDB, hKey, hKeydump;
   char strpath[MAX_FILE_PATH], Dumpfile[MAX_FILE_PATH];
   char odb_entry[MAX_FILE_PATH];
   BOOL eqpfound = FALSE;
   cm_get_experiment_database(&hDB, &hKey);
   peqp = eqp;
   /* find the equipment info for this job */
   while (*(peqp->name) != 0) {
      if (equal_ustring((peqp->name), eqpname)) {
         eqpfound = TRUE;
         break;
      }
      peqp++;
   }
   if (!eqpfound)
      return DB_INVALID_NAME;
   /* loop over all channels */
   sprintf(odb_entry, "/Equipment/%s/Dump", path);
   status = db_find_key(hDB, 0, odb_entry, &hKey);
   if (status != DB_SUCCESS) {
      cm_msg(MINFO, "ybos_odb_file_dump", "odb_access_file -I- %s not found", odb_entry);
      return YB_SUCCESS;
   }
   index = 0;
   while ((status = db_enum_key(hDB, hKey, index, &hKeydump)) != DB_NO_MORE_SUBKEYS) {
      if (status == DB_SUCCESS) {
         size = sizeof(strpath);
         db_get_path(hDB, hKeydump, strpath, size);
         db_get_value(hDB, 0, strpath, Dumpfile, &size, TID_STRING, TRUE);
         yb_file_fragment(peqp, (EVENT_HEADER *) pevent, run_number, Dumpfile);
      }
      index++;
   }
   return (YB_SUCCESS);
}
void midas_bank_display (BANK * pbk, INT dsp_fmt)
Definition at line 3139 of file ybos.c.
References bank_name, BANK::data_size, DSP_ASC, DSP_DEC, DSP_HEX, DSP_UNK, i, j, BANK::name, TID_BOOL, TID_BYTE, TID_CHAR, TID_DOUBLE, TID_DWORD, TID_FLOAT, TID_INT, TID_SBYTE, TID_SHORT, TID_STRUCT, TID_WORD, BANK::type, and type.
Referenced by yb_any_bank_display(), and yb_any_bank_event_display().
       : midas_bank_display
Purpose: display on screen the pointed MIDAS bank data using MIDAS Bank structure.
Input:
BANK *  pbk            pointer to the BANK
INT     dsp_fmt        display format (DSP_DEC/HEX)
Output:
none
Function value:
none
\********************************************************************/
{
   char bank_name[5], strbktype[32];
   char *pdata, *pendbk;
   DWORD length_type = 0, lrl;
   INT type, i, j;
   lrl = pbk->data_size;        /* in bytes */
   type = pbk->type & 0xff;
   bank_name[4] = 0;
   memcpy(bank_name, (char *) (pbk->name), 4);
   pdata = (char *) (pbk + 1);
   j = 64;                      /* elements within line */
   i = 1;                       /* data counter */
   strcpy(strbktype, "Unknown format");
   if (type == TID_DOUBLE) {
      length_type = sizeof(double);
      strcpy(strbktype, "double*8");
   }
   if (type == TID_FLOAT) {
      length_type = sizeof(float);
      strcpy(strbktype, "Real*4 (FMT machine dependent)");
   }
   if (type == TID_DWORD) {
      length_type = sizeof(DWORD);
      strcpy(strbktype, "Unsigned Integer*4");
   }
   if (type == TID_INT) {
      length_type = sizeof(INT);
      strcpy(strbktype, "Signed Integer*4");
   }
   if (type == TID_WORD) {
      length_type = sizeof(WORD);
      strcpy(strbktype, "Unsigned Integer*2");
   }
   if (type == TID_SHORT) {
      length_type = sizeof(short);
      strcpy(strbktype, "Signed Integer*2");
   }
   if (type == TID_BYTE) {
      length_type = sizeof(BYTE);
      strcpy(strbktype, "Unsigned Bytes");
   }
   if (type == TID_SBYTE) {
      length_type = sizeof(BYTE);
      strcpy(strbktype, "Signed Bytes");
   }
   if (type == TID_BOOL) {
      length_type = sizeof(DWORD);
      strcpy(strbktype, "Boolean");
   }
   if (type == TID_CHAR) {
      length_type = sizeof(char);
      strcpy(strbktype, "8 bit ASCII");
   }
   if (type == TID_STRUCT) {
      length_type = sizeof(char);
      strcpy(strbktype, "STRUCT (not supported->8 bits)");
   }
   printf("\nBank:%s Length: %li(I*1)/%li(I*4)/%li(Type) Type:%s",
          bank_name, lrl, lrl >> 2, lrl / length_type, strbktype);
   pendbk = pdata + lrl;
   while (pdata < pendbk) {
      switch (type) {
      case TID_DOUBLE:
         if (j > 3) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 4;
         }
         printf("%15.5le    ", *((double *) pdata));
         pdata = (char *) (((double *) pdata) + 1);
         j++;
         break;
      case TID_FLOAT:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if ((dsp_fmt == DSP_DEC) || (dsp_fmt == DSP_UNK))
            printf("%8.3e ", *((float *) pdata));
         if (dsp_fmt == DSP_HEX)
            printf("0x%8.8lx ", *((DWORD *) pdata));
         pdata = (char *) (((DWORD *) pdata) + 1);
         j++;
         break;
      case TID_DWORD:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if (dsp_fmt == DSP_DEC)
            printf("%8.1li ", *((DWORD *) pdata));
         if ((dsp_fmt == DSP_HEX) || (dsp_fmt == DSP_UNK))
            printf("0x%8.8lx ", *((DWORD *) pdata));
         pdata = (char *) (((DWORD *) pdata) + 1);
         j++;
         break;
      case TID_INT:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if ((dsp_fmt == DSP_DEC) || (dsp_fmt == DSP_UNK))
            printf("%8.1li ", *((DWORD *) pdata));
         if (dsp_fmt == DSP_HEX)
            printf("0x%8.8lx ", *((DWORD *) pdata));
         pdata = (char *) (((DWORD *) pdata) + 1);
         j++;
         break;
      case TID_WORD:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if (dsp_fmt == DSP_DEC)
            printf("%5.1i ", *((WORD *) pdata));
         if ((dsp_fmt == DSP_HEX) || (dsp_fmt == DSP_UNK))
            printf("0x%4.4x ", *((WORD *) pdata));
         pdata = (char *) (((WORD *) pdata) + 1);
         j++;
         break;
      case TID_SHORT:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if ((dsp_fmt == DSP_DEC) || (dsp_fmt == DSP_UNK))
            printf("%5.1i ", *((short *) pdata));
         if (dsp_fmt == DSP_HEX)
            printf("0x%4.4x ", *((short *) pdata));
         pdata = (char *) (((short *) pdata) + 1);
         j++;
         break;
      case TID_BYTE:
      case TID_STRUCT:
         if (j > 15) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 16;
         }
         if (dsp_fmt == DSP_DEC)
            printf("%4.i ", *((BYTE *) pdata));
         if ((dsp_fmt == DSP_HEX) || (dsp_fmt == DSP_UNK))
            printf("0x%2.2x ", *((BYTE *) pdata));
         pdata++;
         j++;
         break;
      case TID_SBYTE:
         if (j > 15) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 16;
         }
         if ((dsp_fmt == DSP_DEC) || (dsp_fmt == DSP_UNK))
            printf("%4.i ", *((BYTE *) pdata));
         if (dsp_fmt == DSP_HEX)
            printf("0x%2.2x ", *((BYTE *) pdata));
         pdata++;
         j++;
         break;
      case TID_BOOL:
         if (j > 15) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 16;
         }
         (*((BOOL *) pdata) != 0) ? printf("Y ") : printf("N ");
         pdata = (char *) (((DWORD *) pdata) + 1);
         j++;
         break;
      case TID_CHAR:
         if (j > 15) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 16;
         }
         if (dsp_fmt == DSP_DEC)
            printf("%3.i ", *((BYTE *) pdata));
         if ((dsp_fmt == DSP_ASC) || (dsp_fmt == DSP_UNK))
            printf("%1.1s ", (char *) pdata);
         if (dsp_fmt == DSP_HEX)
            printf("0x%2.2x ", *((BYTE *) pdata));
         pdata++;
         j++;
         break;
      default:
         printf("bank type not supported (%d)\n", type);
         return;
         break;
      }
   }                            /* end of bank */
   printf("\n");
   return;
}
void midas_bank_display32 (BANK32 * pbk, INT dsp_fmt)
Definition at line 3355 of file ybos.c.
References bank_name, BANK32::data_size, DSP_ASC, DSP_DEC, DSP_HEX, DSP_UNK, i, j, BANK32::name, TID_BOOL, TID_BYTE, TID_CHAR, TID_DOUBLE, TID_DWORD, TID_FLOAT, TID_INT, TID_SBYTE, TID_SHORT, TID_STRUCT, TID_WORD, BANK32::type, and type.
Referenced by yb_any_bank_display(), and yb_any_bank_event_display().
       : midas_bank_display32
Purpose: display on screen the pointed MIDAS bank data using MIDAS Bank structure.
for 32bit length banks
Input:
BANK32 *  pbk            pointer to the BANK
INT     dsp_fmt        display format (DSP_DEC/HEX)
Output:
none
Function value:
none
\********************************************************************/
{
   char bank_name[5], strbktype[32];
   char *pdata, *pendbk;
   DWORD length_type = 0, lrl;
   INT type, i, j;
   lrl = pbk->data_size;        /* in bytes */
   type = pbk->type & 0xff;
   bank_name[4] = 0;
   memcpy(bank_name, (char *) (pbk->name), 4);
   pdata = (char *) (pbk + 1);
   j = 64;                      /* elements within line */
   i = 1;                       /* data counter */
   strcpy(strbktype, "Unknown format");
   if (type == TID_DOUBLE) {
      length_type = sizeof(double);
      strcpy(strbktype, "double*8");
   }
   if (type == TID_FLOAT) {
      length_type = sizeof(float);
      strcpy(strbktype, "Real*4 (FMT machine dependent)");
   }
   if (type == TID_DWORD) {
      length_type = sizeof(DWORD);
      strcpy(strbktype, "Unsigned Integer*4");
   }
   if (type == TID_INT) {
      length_type = sizeof(INT);
      strcpy(strbktype, "Signed Integer*4");
   }
   if (type == TID_WORD) {
      length_type = sizeof(WORD);
      strcpy(strbktype, "Unsigned Integer*2");
   }
   if (type == TID_SHORT) {
      length_type = sizeof(short);
      strcpy(strbktype, "Signed Integer*2");
   }
   if (type == TID_BYTE) {
      length_type = sizeof(BYTE);
      strcpy(strbktype, "8 bit Bytes");
   }
   if (type == TID_SBYTE) {
      length_type = sizeof(BYTE);
      strcpy(strbktype, "Signed Bytes");
   }
   if (type == TID_BOOL) {
      length_type = sizeof(DWORD);
      strcpy(strbktype, "Boolean");
   }
   if (type == TID_CHAR) {
      length_type = sizeof(char);
      strcpy(strbktype, "8 bit ASCII");
   }
   if (type == TID_STRUCT) {
      length_type = sizeof(char);
      strcpy(strbktype, "STRUCT (not supported->8 bits)");
   }
   printf("\nBank:%s Length: %li(I*1)/%li(I*4)/%li(Type) Type:%s",
          bank_name, lrl, lrl >> 2, lrl / length_type, strbktype);
   pendbk = pdata + lrl;
   while (pdata < pendbk) {
      switch (type) {
      case TID_DOUBLE:
         if (j > 3) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 4;
         }
         printf("%15.5le    ", *((double *) pdata));
         pdata = (char *) (((double *) pdata) + 1);
         j++;
         break;
      case TID_FLOAT:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if ((dsp_fmt == DSP_DEC) || (dsp_fmt == DSP_UNK))
            printf("%8.3e ", *((float *) pdata));
         if (dsp_fmt == DSP_HEX)
            printf("0x%8.8lx ", *((DWORD *) pdata));
         pdata = (char *) (((DWORD *) pdata) + 1);
         j++;
         break;
      case TID_DWORD:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if (dsp_fmt == DSP_DEC)
            printf("%8.1li ", *((DWORD *) pdata));
         if ((dsp_fmt == DSP_HEX) || (dsp_fmt == DSP_UNK))
            printf("0x%8.8lx ", *((DWORD *) pdata));
         pdata = (char *) (((DWORD *) pdata) + 1);
         j++;
         break;
      case TID_INT:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if ((dsp_fmt == DSP_DEC) || (dsp_fmt == DSP_UNK))
            printf("%8.1li ", *((DWORD *) pdata));
         if (dsp_fmt == DSP_HEX)
            printf("0x%8.8lx ", *((DWORD *) pdata));
         pdata = (char *) (((DWORD *) pdata) + 1);
         j++;
         break;
      case TID_WORD:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if (dsp_fmt == DSP_DEC)
            printf("%5.1i ", *((WORD *) pdata));
         if ((dsp_fmt == DSP_HEX) || (dsp_fmt == DSP_UNK))
            printf("0x%4.4x ", *((WORD *) pdata));
         pdata = (char *) (((WORD *) pdata) + 1);
         j++;
         break;
      case TID_SHORT:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if ((dsp_fmt == DSP_DEC) || (dsp_fmt == DSP_UNK))
            printf("%5.1i ", *((short *) pdata));
         if (dsp_fmt == DSP_HEX)
            printf("0x%4.4x ", *((short *) pdata));
         pdata = (char *) (((short *) pdata) + 1);
         j++;
         break;
      case TID_BYTE:
      case TID_STRUCT:
         if (j > 15) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 16;
         }
         if (dsp_fmt == DSP_DEC)
            printf("%4.i ", *((BYTE *) pdata));
         if ((dsp_fmt == DSP_HEX) || (dsp_fmt == DSP_UNK))
            printf("0x%2.2x ", *((BYTE *) pdata));
         pdata++;
         j++;
         break;
      case TID_SBYTE:
         if (j > 15) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 16;
         }
         if ((dsp_fmt == DSP_DEC) || (dsp_fmt == DSP_UNK))
            printf("%4.i ", *((BYTE *) pdata));
         if (dsp_fmt == DSP_HEX)
            printf("0x%2.2x ", *((BYTE *) pdata));
         pdata++;
         j++;
         break;
      case TID_BOOL:
         if (j > 15) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 16;
         }
         (*((BOOL *) pdata) != 0) ? printf("Y ") : printf("N ");
         pdata = (char *) (((DWORD *) pdata) + 1);
         j++;
         break;
      case TID_CHAR:
         if (j > 15) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 16;
         }
         if (dsp_fmt == DSP_DEC)
            printf("%3.i ", *((BYTE *) pdata));
         if (dsp_fmt == DSP_ASC || (dsp_fmt == DSP_UNK))
            printf("%1.1s ", (char *) pdata);
         if (dsp_fmt == DSP_HEX)
            printf("0x%2.2x ", *((BYTE *) pdata));
         pdata++;
         j++;
         break;
      default:
         printf("bank type not supported (%d)\n", type);
         return;
         break;
      }
   }                            /* end of bank */
   printf("\n");
   return;
}
INT midas_event_get (void ** pevent, DWORD * size)
Definition at line 2665 of file ybos.c.
References if, midas_physrec_get(), my, size, YB_DONE, and YB_SUCCESS.
Referenced by midas_event_skip(), and yb_any_event_get().
       : midas_event_get
Purpose: read one MIDAS event.
Will detect:
The first pass in getting the record number being -1
The last pass in checking the midas_physrec_get() readn
being different then the my.size then flushing the current
buffer until pointer goes beyond last event.
Input:
void ** pevent     points to MIDAS HEADER
Output:
DWORD * readn      event size in bytes (MIDAS)
Function value:
YB_DONE           No more record to read
YB_SUCCESS        Ok
\********************************************************************/
{
   INT status, leftover;
   DWORD fpart;
   static DWORD size = 0;
   /* save pointer */
   *pevent = (char *) my.pmh;
   if (size == 0)
      size = my.size;
   /* first time in get physrec once */
   if (my.recn == -1) {
      status = midas_physrec_get((void *) my.pmp, &size);
      if (status != YB_SUCCESS)
         return (YB_DONE);
   }
  /*-PAA- Jul 12/2002
    if (((my.pmp+size) - (char *)my.pme) == 0)
        return (YB_DONE);
  */
   /* copy header only */
   if (((my.pmp + size) - (char *) my.pme) < sizeof(EVENT_HEADER)) {
      fpart = (my.pmp + my.size) - (char *) my.pme;
      memcpy(my.pmh, my.pme, fpart);
      my.pmh = (EVENT_HEADER *) (((char *) my.pmh) + fpart);
      leftover = sizeof(EVENT_HEADER) - fpart;
      status = midas_physrec_get((void *) my.pmp, &size);
      if (status != YB_SUCCESS)
         return (YB_DONE);
      memset(my.pmp + size, -1, my.size - size);
      my.pme = (EVENT_HEADER *) my.pmp;
      memcpy(my.pmh, my.pme, leftover);
      my.pme = (EVENT_HEADER *) (((char *) my.pme) + leftover);
      my.pmh = (EVENT_HEADER *) * pevent;
   } else {
      memcpy(my.pmh, my.pme, sizeof(EVENT_HEADER));
      my.pme = (EVENT_HEADER *) (((char *) my.pme) + sizeof(EVENT_HEADER));
   }
   /* leave with pmh  to destination header
      pmrd to destination event (pmh+1)
      pme  to source event
    */
   my.pmrd = (char *) (my.pmh + 1);
   /* check for end of file */
   if (my.pmh->event_id == -1)
      return YB_DONE;
   /* copy event (without header) */
   leftover = my.pmh->data_size;
   /* check for block crossing */
   while (((my.pmp + size) - (char *) my.pme) < leftover) {
      fpart = (my.pmp + my.size) - (char *) my.pme;
      memcpy(my.pmrd, my.pme, fpart);
      my.pmrd += fpart;
      leftover -= fpart;
      status = midas_physrec_get((void *) my.pmp, &size);
      if (status != YB_SUCCESS)
         return (YB_DONE);
      memset(my.pmp + size, -1, my.size - size);
      my.pme = (EVENT_HEADER *) my.pmp;
   }
   /* copy left over or full event if no Xing */
   *readn = my.evtlen = my.pmh->data_size + sizeof(EVENT_HEADER);
   memcpy(my.pmrd, my.pme, leftover);
   my.pme = (EVENT_HEADER *) (((char *) my.pme) + leftover);
   my.evtn++;
   return YB_SUCCESS;
}
INT midas_event_skip (INT evtn)
Definition at line 2290 of file ybos.c.
References MAX_EVENT_SIZE, midas_event_get(), my, size, YB_DONE, and YB_SUCCESS.
Referenced by yb_any_physrec_skip().
       : midas_event_skip
Purpose: skip event on a MIDAS file.
Input:
INT     evtn          event record number. (start at 0)
if evt = -1 : skip skiping
Output:
none
Function value:
YB_SUCCESS        Ok
\********************************************************************/
{
   void *pevent;
   DWORD size;
   size = MAX_EVENT_SIZE;
   if (evtn == -1) {
      /*    if(midas_event_get(&pevent, &size) == YB_SUCCESS) */
      return YB_SUCCESS;
   }
   while (midas_event_get(&pevent, &size) == YB_SUCCESS) {
      if ((INT) my.evtn < evtn) {
         printf("Skipping event_# ... ");
         printf("%ld \r", my.evtn);
         fflush(stdout);
      } else {
         printf("\n");
         return YB_SUCCESS;
      }
   }
   return YB_DONE;
}
INT midas_physrec_get (void * prec, DWORD * readn)
Definition at line 2147 of file ybos.c.
References my, SS_FILE_ERROR, SS_SUCCESS, yb_any_dev_os_read(), YB_DONE, and YB_SUCCESS.
Referenced by midas_event_get(), and yb_any_physrec_get().
       : midas_physrec_get
Purpose: read one physical record.from a MIDAS run
This is a "fake" physical record as Midas is
not block structured. This function is used for
reading a my.size record size. The return readn if different
then my.size, will indicate a end of run. An extra read will
indicate an eof.
Input:
void * prec        pointer to the record
Output:
DWORD *readn       retrieve number of bytes
Function value:
YB_DONE            No more record to read
YB_SUCCESS         Ok
\********************************************************************/
{
   INT status = 0;
   /* read one block of data */
   if (!my.zipfile) {
      status = yb_any_dev_os_read(my.handle, my.type, prec, my.size, readn);
   } else {
#ifdef INCLUDE_ZLIB
      *readn = gzread(filegz, (char *) prec, my.size);
      if (*readn <= 0)
         status = SS_FILE_ERROR;
      else
         status = SS_SUCCESS;
#endif
   }
   if (status != SS_SUCCESS) {
      return (YB_DONE);
   } else {
      /* count blocks */
      my.recn++;
      return (YB_SUCCESS);
   }
}
INT EXPRT yb_any_all_info_display (INT what)
Definition at line 2367 of file ybos.c.
References D_EVTLEN, D_HEADER, D_RECORD, FORMAT_MIDAS, FORMAT_YBOS, my, offset, run, YB_DONE, and YB_SUCCESS.
Referenced by replog(), and yb_any_physrec_display().
       : yb_any_all_info_display
Purpose: display on screen all the info about "what".
Input:
INT     what              type of display.
Output:
none
Function value:
INT                 YB_SUCCESS
YB_DONE
\********************************************************************/
{
   if (my.fmt == FORMAT_YBOS) {
      DWORD bz, hyl, ybn, of;
      bz = (my.pyh)->rec_size;
      hyl = (my.pyh)->header_length;
      ybn = (my.pyh)->rec_num;
      of = (my.pyh)->offset;
      switch (what) {
      case D_RECORD:
      case D_HEADER:
         printf("rec#%ld- ", my.recn);
         printf("%5ldbz %5ldhyl %5ldybn %5ldof\n", bz, hyl, ybn, of);
         break;
      case D_EVTLEN:
         printf("rec#%ld- ", my.recn);
         printf("%5ldbz %5ldhyl %5ldybn %5ldof ", bz, hyl, ybn, of);
         printf("%5ldel/x%lx %5ldev\n", my.evtlen, my.evtlen, my.evtn);
         break;
      }
   } else if (my.fmt == FORMAT_MIDAS) {
      DWORD mbn, run, ser;
      WORD id, msk;
      mbn = my.evtn;
      run = my.runn;
      id = my.pmh->event_id;
      msk = my.pmh->trigger_mask;
      ser = my.pmh->serial_number;
      switch (what) {
      case D_RECORD:
      case D_HEADER:
         printf(">>> No physical record structure for Midas format <<<\n");
         return YB_DONE;
         break;
      case D_EVTLEN:
         printf("Evt#%ld- ", my.evtn);
         printf("%lirun 0x%4.4uxid 0x%4.4uxmsk %5ldmevt#", run, id, msk, mbn);
         printf("%5ldel/x%lx %5ldserial\n", my.evtlen, my.evtlen, ser);
         break;
      }
   }
   return YB_SUCCESS;
}
void EXPRT yb_any_bank_display (void * pmbh, void * pbk, INT fmt, INT dsp_mode, INT dsp_fmt)
Definition at line 2923 of file ybos.c.
References bk_is32(), DSP_RAW, FORMAT_MIDAS, FORMAT_YBOS, midas_bank_display(), midas_bank_display32(), yb_any_raw_bank_display(), and ybos_bank_display().
Referenced by process_event().
       : external yb_any_bank_display
Purpose: display on screen the given bank.
Input:
void * pbk          pointer to the bank
INT  data_fmt       YBOS or MIDAS
INT  dsp_mode       display mode (RAW/BANK)
INT  dsp_fmt        display format (DSP_DEC/HEX)
Output:
none
Function value:
none
\********************************************************************/
{
   if (dsp_mode == DSP_RAW)
      yb_any_raw_bank_display(pbk, data_fmt, dsp_fmt);
   else {
      if (data_fmt == FORMAT_MIDAS) {
         if (bk_is32(pmbh))
            midas_bank_display32((BANK32 *) pbk, dsp_fmt);
         else
            midas_bank_display((BANK *) pbk, dsp_fmt);
      } else if (data_fmt == FORMAT_YBOS)
         ybos_bank_display((YBOS_BANK_HEADER *) pbk, dsp_fmt);
   }
   return;
}
void yb_any_bank_event_display (void * pevent, INT data_fmt, INT dsp_fmt)
Definition at line 2824 of file ybos.c.
References bk_is32(), bk_iterate(), bk_iterate32(), bk_list(), BANK_HEADER::data_size, EVENT_HEADER::data_size, EVENT_HEADER::event_id, EVENTID_BOR, EVENTID_EOR, EVENTID_MESSAGE, FORMAT_MIDAS, FORMAT_YBOS, length, midas_bank_display(), midas_bank_display32(), EVENT_HEADER::serial_number, EVENT_HEADER::time_stamp, EVENT_HEADER::trigger_mask, yb_any_raw_event_display(), YB_STRING_BANKLIST_MAX, YB_SUCCESS, ybk_find(), ybk_iterate(), ybk_list(), ybos_bank_display(), YBOS_EVID_EVENT_ID, YBOS_EVID_EVENT_NB, YBOS_EVID_RUN_NUMBER, YBOS_EVID_SERIAL, YBOS_EVID_TIME, and YBOS_EVID_TRIGGER_MASK.
Referenced by yb_any_event_display().
       : ybos_bank_event_display
Purpose: display on screen the event header, bank list and bank content
for either ybos or midas format. In case of ybos check is EVID is
present if so extract its content (see macro ybos.h)
Input:
void * pevent          points to either plrl or pheader
INT     data_fmt       uses the YBOS or MIDAS event structure
INT     dsp_fmt        display format (DSP_DEC/HEX)
Output:
none
Function value:
none
\********************************************************************/
{
   char banklist[YB_STRING_BANKLIST_MAX];
   YBOS_BANK_HEADER *pybk;
   DWORD *pdata;
   DWORD bklen, bktyp;
   BANK_HEADER *pbh;
   BANK *pmbk;
   BANK32 *pmbk32;
   EVENT_HEADER *pheader;
   INT status;
   if (data_fmt == FORMAT_YBOS) {
      /* event header --> No event header in YBOS */
      /* bank list */
      status = ybk_list((DWORD *) pevent, banklist);
      printf("#banks:%i - Bank list:-%s-\n", status, banklist);
      /* check if EVID is present if so display its content */
      if ((status =
           ybk_find((DWORD *) pevent, "EVID", &bklen, &bktyp,
                    (void **) &pybk)) == YB_SUCCESS) {
         pdata = (DWORD *) ((YBOS_BANK_HEADER *) pybk + 1);
         printf
             ("--------- EVID --------- Event# %li ------Run#:%li--------\n",
              YBOS_EVID_EVENT_NB(pdata), YBOS_EVID_RUN_NUMBER(pdata));
         printf
             ("Evid:%4.4x- Mask:%4.4x- Serial:%li- Time:0x%lx- Dsize:%li/0x%lx",
              (WORD) YBOS_EVID_EVENT_ID(pdata), (WORD) YBOS_EVID_TRIGGER_MASK(pdata)
              , YBOS_EVID_SERIAL(pdata), YBOS_EVID_TIME(pdata)
              , ((YBOS_BANK_HEADER *) pybk)->length, ((YBOS_BANK_HEADER *) pybk)->length);
      }
      /* display bank content */
      pybk = NULL;
      while ((ybk_iterate((DWORD *) pevent, &pybk, (void **) &pdata) >= 0)
             && (pybk != NULL))
         ybos_bank_display(pybk, dsp_fmt);
   } else if (data_fmt == FORMAT_MIDAS) {
      /* skip these special events (NO bank structure) */
      pheader = (EVENT_HEADER *) pevent;
      if (pheader->event_id == EVENTID_BOR ||
          pheader->event_id == EVENTID_EOR || pheader->event_id == EVENTID_MESSAGE)
         return;
      /* event header */
      printf
          ("Evid:%4.4x- Mask:%4.4x- Serial:%li- Time:0x%lx- Dsize:%li/0x%lx",
           (WORD) pheader->event_id, (WORD) pheader->trigger_mask,
           pheader->serial_number, pheader->time_stamp, pheader->data_size,
           pheader->data_size);
      /* check if format is MIDAS or FIXED */
      pbh = (BANK_HEADER *) (pheader + 1);
      if ((pbh->data_size + 8) == pheader->data_size) {
         /* bank list */
         status = bk_list((BANK_HEADER *) (pheader + 1), banklist);
         printf("\n#banks:%i - Bank list:-%s-\n", status, banklist);
         /* display bank content */
         if (bk_is32(pbh)) {
            pmbk32 = NULL;
            do {
               bk_iterate32(pbh, &pmbk32, &pdata);
               if (pmbk32 != NULL)
                  midas_bank_display32(pmbk32, dsp_fmt);
            } while (pmbk32 != NULL);
         } else {
            pmbk = NULL;
            do {
               bk_iterate(pbh, &pmbk, &pdata);
               if (pmbk != NULL)
                  midas_bank_display(pmbk, dsp_fmt);
            } while (pmbk != NULL);
         }
      } else {
         printf("\nFIXED event with Midas Header\n");
         yb_any_raw_event_display(pevent, data_fmt, dsp_fmt);
      }
   }
   return;
}
INT yb_any_dev_os_read (INT handle, INT type, void * prec, DWORD nbytes, DWORD * nread)
Definition at line 1889 of file ybos.c.
References LOG_TYPE_DISK, LOG_TYPE_TAPE, read, SS_END_OF_TAPE, SS_FILE_ERROR, and SS_SUCCESS.
Referenced by midas_physrec_get(), and ybos_physrec_get().
       : yb_any_dev_os_read
Purpose: read nbytes from the type device.
Input:
INT  handle        file handler
INT  type          Type of device (TAPE or DISK)
void * prec        pointer to the record
DWORD nbytes       # of bytes to read
Output:
DWORD *readn       # of bytes read
Function value:
YB_DONE            No more record to read
YB_SUCCESS         Ok
\********************************************************************/
{
   INT status;
   if (type == LOG_TYPE_DISK)
      /* --------- DISK ---------- */
   {
      *readn = read(handle, prec, nbytes);
      if (*readn <= 0)
         status = SS_FILE_ERROR;
      else
         status = SS_SUCCESS;
      return status;
   }
   /* --------- TAPE ---------- */
#ifdef OS_UNIX
   else if (type == LOG_TYPE_TAPE) {
      *readn = read(handle, prec, nbytes);
      if (*readn <= 0)
         status = SS_FILE_ERROR;
      else
         status = SS_SUCCESS;
      return status;
   }
#endif
#ifdef OS_WINNT
   else if (type == LOG_TYPE_TAPE) {
      if (!ReadFile((HANDLE) handle, prec, nbytes, readn, NULL))
         status = GetLastError();
      else
         status = SS_SUCCESS;
      if (status == ERROR_NO_DATA_DETECTED)
         status = SS_END_OF_TAPE;
      return status;
   }
#endif                          /* OS_WINNT */
   else
      return SS_SUCCESS;
}
INT yb_any_dev_os_write (INT handle, INT type, void * prec, DWORD nbytes, DWORD * written)
Definition at line 1945 of file ybos.c.
References cm_msg, FTP_CON::data, ftp_send(), LOG_TYPE_DISK, LOG_TYPE_FTP, LOG_TYPE_TAPE, MERROR, SS_FILE_ERROR, SS_IO_ERROR, SS_NO_SPACE, SS_SUCCESS, SS_TAPE_ERROR, and write.
Referenced by yb_any_log_write(), and ybos_logfile_open().
       : yb_any_dev_os_write
Purpose: write nbytes to the device. This function is YBOS independent
(NO magta stuff for disk)
Input:
INT  handle        file handler
INT  type          Type of device (TAPE or DISK)
void * prec        pointer to the record
DWORD   nbytes     record length to be written
Output:
DWORD *written     # of written bytes
Function value:
INT status           # of written bytes or ERROR
SS_FILE_ERROR      write error
SS_SUCCESS         Ok
\********************************************************************/
{
   INT status;
   if (type == LOG_TYPE_DISK)
#ifdef OS_WINNT
   {                            /* --------- DISK ---------- */
      WriteFile((HANDLE) handle, (char *) prec, nbytes, written, NULL);
      status = *written == nbytes ? SS_SUCCESS : SS_FILE_ERROR;
      return status;            /* return for DISK */
   }
#else
   {                            /* --------- DISK ---------- */
      status = *written =
          write(handle, (char *) prec, nbytes) == nbytes ? SS_SUCCESS : SS_FILE_ERROR;
      return status;            /* return for DISK */
   }
#endif
   else if (type == LOG_TYPE_TAPE) {    /* --------- TAPE ---------- */
#ifdef OS_UNIX
      do {
         status = write(handle, (char *) prec, nbytes);
      } while (status == -1 && errno == EINTR);
      *written = status;
      if (*written != nbytes) {
         cm_msg(MERROR, "any_dev_os_write", strerror(errno));
         if (errno == EIO)
            return SS_IO_ERROR;
         if (errno == ENOSPC)
            return SS_NO_SPACE;
         else
            return SS_TAPE_ERROR;
      }
#endif                          /* OS_UNIX */
#ifdef OS_WINNT
      WriteFile((HANDLE) handle, (char *) prec, nbytes, written, NULL);
      if (*written != nbytes) {
         status = GetLastError();
         cm_msg(MERROR, "any_dev_os_write", "error %d", status);
         return SS_IO_ERROR;
      }
      return SS_SUCCESS;        /* return for TAPE */
#endif                          /* OS_WINNT */
   } else if (type == LOG_TYPE_FTP)
#ifdef INCLUDE_FTPLIB
   {
          status =
          (INT) ftp_send(ftp_con->data, (char *) prec,
                         (int) nbytes) == (int) nbytes ? SS_SUCCESS : SS_FILE_ERROR;
          *written = (DWORD) status;
      return status;
   }
#else
   {
      cm_msg(MERROR, "ybos", "FTP support not included");
      return SS_IO_ERROR;
   }
#endif
   return SS_SUCCESS;
}
void EXPRT yb_any_event_display (void * pevt, INT data_fmt, INT dsp_mode, INT dsp_fmt)
Definition at line 2757 of file ybos.c.
References DSP_BANK, DSP_RAW, yb_any_bank_event_display(), and yb_any_raw_event_display().
Referenced by process_event(), and replog().
       : external yb_any_event_display
Purpose: display on screen the YBOS event in either RAW or YBOS mode
and in either Decimal or Hexadecimal.
Input:
void *  pevent     pointer to either plrl or pheader.
INT     data_fmt   uses the YBOS or MIDAS event structure
INT     dsp_mode   display in RAW or Bank mode
INT     dsp_fmt    display format (DSP_DEC/HEX)
Output:
none
Function value:
none
\********************************************************************/
{
   if (dsp_mode == DSP_RAW)
      yb_any_raw_event_display(pevent, data_fmt, dsp_fmt);
   else if (dsp_mode == DSP_BANK)
      yb_any_bank_event_display(pevent, data_fmt, dsp_fmt);
   else
      printf("yb_any_event_display- Unknown format:%i\n", dsp_fmt);
   return;
}
INT EXPRT yb_any_event_get (INT data_fmt, void ** pevent, DWORD * psize)
Definition at line 2544 of file ybos.c.
References FORMAT_MIDAS, FORMAT_YBOS, midas_event_get(), and ybos_event_get().
Referenced by replog().
       : external yb_any_event_get
Purpose: Retrieve an event from the given data format.
Input:
INT data_fmt :  YBOS or MIDAS
void ** pevent : either plrl or pheader
Output:
DWORD * readn : number of bytes read
Function value:
status : from lower function
\********************************************************************/
{
   INT status = 0;
   *pevent = NULL;
   if (data_fmt == FORMAT_MIDAS)
      status = midas_event_get(pevent, readn);
   else if (data_fmt == FORMAT_YBOS)
      status = ybos_event_get((DWORD **) pevent, readn);
   return (status);
}
INT EXPRT yb_any_event_swap (INT data_fmt, void * pevent)
Definition at line 2424 of file ybos.c.
References bk_swap(), CM_SUCCESS, event_id, EVENTID_BOR, EVENTID_EOR, EVENTID_MESSAGE, FALSE, FORMAT_MIDAS, FORMAT_YBOS, SS_SUCCESS, YB_EVENT_NOT_SWAPPED, YB_SUCCESS, YB_UNKNOWN_FORMAT, and ybos_event_swap().
Referenced by ma_read_event(), process_event(), and replog().
       : external yb_any_event_swap
Purpose: Swap an event from the given data format.
Input:
INT data_fmt  : YBOS or MIDAS
void * pevent : pointer to either plrl or pheader
Output:
none
Function value:
status :  from the lower function
\********************************************************************/
{
   INT status;
   BANK_HEADER *pbh;
   if (data_fmt == FORMAT_MIDAS) {
      if ((((EVENT_HEADER *) pevent)->event_id == EVENTID_BOR) ||
          (((EVENT_HEADER *) pevent)->event_id == EVENTID_EOR) ||
          (((EVENT_HEADER *) pevent)->event_id == EVENTID_MESSAGE))
         return SS_SUCCESS;
      pbh = (BANK_HEADER *) (((EVENT_HEADER *) pevent) + 1);
      status = bk_swap(pbh, FALSE);
      return status == CM_SUCCESS ? YB_EVENT_NOT_SWAPPED : YB_SUCCESS;
   } else if (data_fmt == FORMAT_YBOS) {
      status = ybos_event_swap((DWORD *) pevent);
      return status == YB_EVENT_NOT_SWAPPED ? YB_SUCCESS : status;
   }
   return YB_UNKNOWN_FORMAT;
}
INT EXPRT yb_any_file_rclose (INT data_fmt)
Definition at line 1668 of file ybos.c.
References LOG_TYPE_DISK, LOG_TYPE_TAPE, my, and YB_SUCCESS.
Referenced by lazy_copy(), ma_close(), and replog().
       : external yb_any_file_rclose
Purpose: Close a data file used for replay for the given data format
Input:
INT data_fmt :  YBOS or MIDAS
Output:
none
Function value:
status : from lower function
*******************************************************************/
{
   switch (my.type) {
   case LOG_TYPE_TAPE:
   case LOG_TYPE_DISK:
      /* close file */
      if (my.zipfile) {
#ifdef INCLUDE_ZLIB
         gzclose(filegz);
#endif
      } else {
         if (my.handle != 0)
            close(my.handle);
      }
      break;
   }
   if (my.pmagta != NULL)
      free(my.pmagta);
   if (my.pyh != NULL)
      free(my.pyh);
   if (my.pylrl != NULL)
      free(my.pylrl);
   if (my.pmrd != NULL)
      free(my.pmrd);
   if (my.pmp != NULL)
      free(my.pmp);
   my.pylrl = NULL;
   my.pyh = NULL;
   my.pmagta = NULL;
   my.pmp = NULL;
   my.pmh = NULL;
   my.pmrd = NULL;
   return (YB_SUCCESS);
}
INT EXPRT yb_any_file_ropen (char * infile, INT data_fmt)
Definition at line 1559 of file ybos.c.
References cm_msg, FALSE, FORMAT_MIDAS, FORMAT_YBOS, if, LOG_TYPE_DISK, LOG_TYPE_TAPE, MAX_EVENT_SIZE, MERROR, my, O_BINARY, O_LARGEFILE, offset, ptopmrd, SS_FILE_ERROR, SS_NO_MEMORY, ss_tape_open(), status, TAPE_BUFFER_SIZE, TRUE, YB_SUCCESS, YBOS_HEADER_LENGTH, and YBOS_PHYREC_SIZE.
Referenced by lazy_copy(), ma_open(), and replog().
       : external yb_any_file_ropen
Purpose: Open data file for replay for the given data format.
It uses the local "my" structure.
Input:
INT data_fmt :  YBOS or MIDAS
char * infile : Data file name
Output:
none
Function value:
status : from lower function
\********************************************************************/
{
   INT status;
   /* fill up record with file name */
   strcpy(my.name, infile);
   /* find out what dev it is ? : check on /dev */
   my.zipfile = FALSE;
   if ((strncmp(my.name, "/dev", 4) == 0) || (strncmp(my.name, "\\\\.\\", 4) == 0)) {
      /* tape device */
      my.type = LOG_TYPE_TAPE;
   } else {
      /* disk device */
      my.type = LOG_TYPE_DISK;
      if (strncmp(infile + strlen(infile) - 3, ".gz", 3) == 0)
         my.zipfile = TRUE;
   }
   /* open file */
   if (!my.zipfile) {
      if (my.type == LOG_TYPE_TAPE) {
         status = ss_tape_open(my.name, O_RDONLY | O_BINARY, &my.handle);
      }
      else if ((my.handle = open(my.name, O_RDONLY | O_BINARY | O_LARGEFILE, 0644)) == -1)
      {
         printf("dev name :%s Handle:%d \n", my.name, my.handle);
         return (SS_FILE_ERROR);
      }
   } else {
#ifdef INCLUDE_ZLIB
      if (my.type == LOG_TYPE_TAPE) {
         printf(" Zip on tape not yet supported \n");
         return (SS_FILE_ERROR);
      }
      filegz = gzopen(my.name, "rb");
      my.handle = 0;
      if (filegz == NULL) {
         printf("dev name :%s gzopen error:%d \n", my.name, my.handle);
         return (SS_FILE_ERROR);
      }
#else
      cm_msg(MERROR, "ybos.c", "Zlib not included ... gz file not supported");
      return (SS_FILE_ERROR);
#endif
   }
   if (data_fmt == FORMAT_YBOS) {
      my.fmt = FORMAT_YBOS;
      my.size = YBOS_PHYREC_SIZE;       /* in DWORD  */
      my.pmagta = (char *) malloc(32);
      if (my.pmagta == NULL)
         return SS_NO_MEMORY;
      my.pyh = (YBOS_PHYSREC_HEADER *) malloc(my.size * 14);
      if (my.pyh == NULL)
         return SS_NO_MEMORY;
      (my.pyh)->rec_size = my.size - 1;
      (my.pyh)->header_length = YBOS_HEADER_LENGTH;
      (my.pyh)->rec_num = 0;
      (my.pyh)->offset = 0;
      /* current ptr in the physical record */
      my.pyrd = (DWORD *) ((DWORD *) my.pyh + (my.pyh)->offset);
      /* allocate memory for one full event */
      my.pylrl = (DWORD *) malloc(MAX_EVENT_SIZE);      /* in bytes */
      if (my.pylrl == NULL)
         return SS_NO_MEMORY;
      memset((char *) my.pylrl, -1, MAX_EVENT_SIZE);
      /* reset first path */
      my.magtafl = FALSE;
   } else if (data_fmt == FORMAT_MIDAS) {
      my.fmt = FORMAT_MIDAS;
      my.size = TAPE_BUFFER_SIZE;
      my.pmp = (char *) malloc(my.size);
      if (my.pmp == NULL)
         return SS_NO_MEMORY;
      my.pme = (EVENT_HEADER *) my.pmp;
      /* allocate memory for one full event */
      if (my.pmrd != NULL)
         free(my.pmrd);
      my.pmrd = (char *) malloc(5 * MAX_EVENT_SIZE);    /* in bytes */
      ptopmrd = my.pmrd;
      if (my.pmrd == NULL)
         return SS_NO_MEMORY;
      memset((char *) my.pmrd, -1, 5 * MAX_EVENT_SIZE);
      my.pmh = (EVENT_HEADER *) my.pmrd;
   }
   /* initialize pertinent variables */
   my.recn = (DWORD) - 1;       /* physical record number */
   my.evtn = 0;
   return (YB_SUCCESS);
}
INT EXPRT yb_any_file_wclose (INT handle, INT type, INT data_fmt)
Definition at line 1847 of file ybos.c.
References ftp_bye(), ftp_close(), LOG_TYPE_DISK, LOG_TYPE_FTP, LOG_TYPE_TAPE, SS_SUCCESS, ss_tape_close(), ss_tape_write_eof(), and YB_SUCCESS.
Referenced by lazy_copy().
       : external yb_any_file_wclose
Purpose: Close a data file used for replay for the given data format
Input:
INT data_fmt :  YBOS or MIDAS
Output:
none
Function value:
status : from lower function
*******************************************************************/
{
   INT status;
   status = SS_SUCCESS;
   switch (type) {
   case LOG_TYPE_TAPE:
      /* writing EOF mark on tape Fonly */
      status = ss_tape_write_eof(handle);
      ss_tape_close(handle);
      break;
   case LOG_TYPE_DISK:
      /* close file */
      if (handle != 0)
#ifdef OS_WINNT
         CloseHandle((HANDLE) handle);
#else
         close(handle);
#endif
      break;
   case LOG_TYPE_FTP:
#ifdef INCLUDE_FTPLIB
      ftp_close(ftp_con);
      ftp_bye(ftp_con);
#endif
      break;
   }
   if (status != SS_SUCCESS)
      return status;
   return (YB_SUCCESS);
}
INT EXPRT yb_any_file_wopen (INT type, INT data_fmt, char * filename, INT * hDev)
Definition at line 1789 of file ybos.c.
References cm_msg, FORMAT_MIDAS, FORMAT_YBOS, LOG_TYPE_DISK, LOG_TYPE_FTP, LOG_TYPE_TAPE, MERROR, O_BINARY, O_LARGEFILE, SS_FILE_ERROR, SS_SUCCESS, ss_tape_open(), and ybos_logfile_open().
Referenced by lazy_copy().
       : external yb_any_file_wopen
Purpose: Open a data file for the given data format
Input:
INT type     :  Tape or Disk
INT data_fmt :  YBOS or MIDAS
char * filename : file to open
Output:
INT * hDev      : file handle
Function value:
status : from lower function
*******************************************************************/
{
   INT status = 0;
   if (type == LOG_TYPE_DISK)
      /* takes care of TapeLX/NT under ss_tape_open , DiskLX/NT here */
   {
      if (data_fmt == FORMAT_YBOS) {
         /* takes care of TapeLX/NT under ss_tape_open , DiskLX/NT there */
         status = ybos_logfile_open(type, filename, hDev);
      } else if (data_fmt == FORMAT_MIDAS) {
#ifdef OS_WINNT
         *hDev =
             (int) CreateFile(filename, GENERIC_WRITE, FILE_SHARE_READ,
                              NULL, CREATE_ALWAYS,
                              FILE_ATTRIBUTE_NORMAL |
                              FILE_FLAG_WRITE_THROUGH | FILE_FLAG_SEQUENTIAL_SCAN, 0);
#else
         *hDev = open(filename, O_WRONLY | O_CREAT | O_TRUNC | O_BINARY | O_LARGEFILE, 0644);
#endif
         status = *hDev < 0 ? SS_FILE_ERROR : SS_SUCCESS;
      }
   } else if (type == LOG_TYPE_TAPE) {
      if (data_fmt == FORMAT_YBOS) {
         /* takes care of TapeLX/NT under ss_tape_open , DiskLX/NT there */
         status = ybos_logfile_open(type, filename, hDev);
      } else if (data_fmt == FORMAT_MIDAS)
         status = ss_tape_open(filename, O_WRONLY | O_CREAT | O_TRUNC, hDev);
   } else if (type == LOG_TYPE_FTP) {
#ifdef INCLUDE_FTPLIB
      status = yb_ftp_open(filename, (FTP_CON **) & ftp_con);
      if (status != SS_SUCCESS) {
         *hDev = 0;
         return status;
      } else
         *hDev = 1;
#else
      cm_msg(MERROR, "yb_any_file_wopen", "FTP support not included");
      return SS_FILE_ERROR;
#endif
   }
   return status;
}
INT EXPRT yb_any_log_write (INT handle, INT data_fmt, INT type, void * prec, DWORD nbytes)
Definition at line 2191 of file ybos.c.
References FORMAT_YBOS, LOG_TYPE_DISK, magta, SS_SUCCESS, and yb_any_dev_os_write().
Referenced by lazy_copy(), ybos_buffer_flush(), and ybos_write().
       : external yb_any_log_write
Purpose: Write a physical record to the out device, takes care of the
magta under YBOS.
Input:
void handle   : file handle
INT data_fmt  : YBOS or MIDAS
INT type      : Tape or disk
void *prec    : record pointer
DWORD nbytes  : record length to be written
Output:
none
Function value:
status : from lower function  SS_SUCCESS, SS_FILE_ERROR
\********************************************************************/
{
   INT status;
   DWORD written;
#ifdef YBOS_VERSION_3_3
   if ((type == LOG_TYPE_DISK) && (data_fmt == FORMAT_YBOS)) {  /* add the magta record if going to disk */
      status =
          yb_any_dev_os_write(handle, type,
                              (char *) ((DWORD *) (magta + 2)), 4, &written);
      if (status != SS_SUCCESS)
         return status;
   }
#endif
   /* write record */
   status = yb_any_dev_os_write(handle, type, prec, nbytes, &written);
   return status;
}
INT EXPRT yb_any_physrec_display (INT data_fmt)
Definition at line 2325 of file ybos.c.
References D_RECORD, FORMAT_MIDAS, FORMAT_YBOS, i, j, k, my, NLINE, yb_any_all_info_display(), YB_DONE, YB_SUCCESS, and YB_UNKNOWN_FORMAT.
Referenced by replog().
       : external yb_any_physrec_display
Purpose: Display the physical record of the current record
for the given data format.
Not possible for MIDAS as no physical record structure
Input:
INT data_fmt :  YBOS or MIDAS
Output:
none
Function value:
status          Lower function
\********************************************************************/
{
   INT bz, j, i, k;
   DWORD *prec;
   if (data_fmt == FORMAT_MIDAS) {
      printf(">>> No physical record structure for Midas format <<<\n");
      return YB_DONE;
   } else if (data_fmt == FORMAT_YBOS) {
      yb_any_all_info_display(D_RECORD);
      bz = (my.pyh)->rec_size + 1;
      /* adjust local pointer to top of record to include record header */
      prec = (DWORD *) (my.pyh);
      k = (my.pyh)->rec_num;
      for (i = 0; i < bz; i += NLINE) {
         printf("R(%d)[%d] = ", k, i);
         for (j = 0; j < NLINE; j++) {
            if (i + j < bz) {
               printf("%8.8lx ", *prec);
               prec++;
            }
         }
         printf("\n");
      }
      return (YB_SUCCESS);
   } else
      return YB_UNKNOWN_FORMAT;
}
INT EXPRT yb_any_physrec_get (INT data_fmt, void ** prec, DWORD * psize)
Definition at line 2023 of file ybos.c.
References FORMAT_MIDAS, FORMAT_YBOS, midas_physrec_get(), my, YB_UNKNOWN_FORMAT, and ybos_physrec_get().
Referenced by lazy_copy(), and replog().
       : external yb_any_physrec_get
Purpose: Retrieve a physical record for the given data format
Input:
INT data_fmt :  YBOS or MIDAS
Output:
void ** precord     pointer to the record
DWORD * readn       record length in bytes
Function value:
status : from lower function
\********************************************************************/
{
   *precord = my.pmp;
   if (data_fmt == FORMAT_MIDAS)
      return midas_physrec_get(*precord, readn);
   else if (data_fmt == FORMAT_YBOS)
      return ybos_physrec_get((DWORD **) precord, readn);
   else
      return YB_UNKNOWN_FORMAT;
}
INT EXPRT yb_any_physrec_skip (INT data_fmt, INT bl)
Definition at line 2227 of file ybos.c.
References FORMAT_MIDAS, FORMAT_YBOS, midas_event_skip(), YB_SUCCESS, YB_UNKNOWN_FORMAT, and ybos_physrec_skip().
Referenced by ma_open(), and replog().
       : external yb_any_physrec_skip
Purpose: Skip physical record until block = bl for the given data
format, Under midas the skip is an event as no physical
record is present under that format,
Input:
INT data_fmt :  YBOS or MIDAS
INT bl:         block number (-1==all, 0 = first block)
in case of MIDAS the bl represent an event
Output:
none
Function value:
status : from lower function
\********************************************************************/
{
   INT status;
   if (data_fmt == FORMAT_MIDAS) {
      status = midas_event_skip(bl);
      return YB_SUCCESS;
   } else if (data_fmt == FORMAT_YBOS)
      return ybos_physrec_skip(bl);
   else
      return YB_UNKNOWN_FORMAT;
}
void yb_any_raw_bank_display (void * pbank, INT data_fmt, INT dsp_fmt)
Definition at line 2953 of file ybos.c.
References DSP_ASC, DSP_DEC, DSP_HEX, FORMAT_MIDAS, FORMAT_YBOS, i, j, and NLINE.
Referenced by yb_any_bank_display().
       : yb_any_raw_bank_display
Purpose: display on screen the RAW data of a given YBOS/MIDAS bank.
Input:
void  * pbank          pointer to the bank name
INT     data_fmt       uses the YBOS or MIDAS event structure
INT     dsp_fmt        display format (DSP_DEC/HEX)
Output:
none
Function value:
none
\********************************************************************/
{
   DWORD *pdata = NULL, lrl = 0, j, i;
   if (data_fmt == FORMAT_YBOS) {
      lrl = (((YBOS_BANK_HEADER *) pbank)->length) - 1;
      pdata = (DWORD *) (((YBOS_BANK_HEADER *) pbank) + 1);
   } else if (data_fmt == FORMAT_MIDAS) {
      lrl = ((BANK *) pbank)->data_size >> 2;   /* in DWORD */
      pdata = (DWORD *) ((BANK *) (pbank) + 1);
   }
   for (i = 0; i < lrl; i += NLINE) {
      j = 0;
      printf("\n%4li-> ", i + j + 1);
      for (j = 0; j < NLINE; j++) {
         if ((i + j) < lrl) {
            if (dsp_fmt == DSP_DEC)
               printf("%8.li ", *((DWORD *) pdata));
            if (dsp_fmt == DSP_ASC)
               printf("%8.8lx ", *((DWORD *) pdata));
            if (dsp_fmt == DSP_HEX)
               printf("%8.8lx ", *((DWORD *) pdata));
            pdata++;
         }
      }
   }
}
void yb_any_raw_event_display (void * pevent, INT data_fmt, INT dsp_fmt)
Definition at line 2783 of file ybos.c.
References DSP_DEC, FORMAT_MIDAS, FORMAT_YBOS, i, j, NLINE, and total.
Referenced by yb_any_bank_event_display(), and yb_any_event_display().
       : yb_any_raw_event_display
Purpose: display on screen the RAW data of either YBOS or MIDAS format.
Input:
DWORD *  pevent         points to either plrl or pheader
INT     data_fmt        uses the YBOS or MIDAS event structure
INT      dsp_fmt        display format (DSP_DEC/HEX)
Output:
none
Function value:
none
\********************************************************************/
{
   DWORD lrl = 0, *pevt = NULL, j, i, total = 0;
   if (data_fmt == FORMAT_YBOS) {
      lrl = *((DWORD *) (pevent)) + 1;  /* include itself */
      pevt = (DWORD *) pevent;  /* local copy starting from the plrl */
   } else if (data_fmt == FORMAT_MIDAS) {
      lrl = ((((EVENT_HEADER *) pevent)->data_size) + sizeof(EVENT_HEADER)) / sizeof(DWORD);    /* in I*4 for raw including the header */
      pevt = (DWORD *) pevent;  /* local copy starting from the pheader */
   }
   for (i = 0; i < lrl; i += NLINE) {
      printf("%6.0ld->: ", total);
      for (j = 0; j < NLINE; j++) {
         if ((i + j) < lrl) {
            if (dsp_fmt == DSP_DEC)
               printf("%8.li ", *pevt);
            else
               printf("%8.8lx ", *pevt);
            pevt++;
         }
      }
      total += NLINE;
      printf("\n");
   }
}
INT yb_file_fragment (EQUIPMENT * eqp, EVENT_HEADER * pevent, INT run_number, char * path)
Definition at line 856 of file ybos.c.
References A1_BKTYPE, bk_close(), bk_create(), bk_init(), bk_size(), bm_compose_event(), bm_send_event(), eqpmnt::buffer_handle, eqpmnt::bytes_sent, cm_msg, YM_CFILE::current_fragment, YM_CFILE::current_read_byte, EVENT_HEADER::data_size, dm_pointer_get(), dm_pointer_increment(), EQUIPMENT_INFO::event_id, eqpmnt::events_sent, YM_CFILE::file_ID, filestat, flag, eqpmnt::format, FORMAT_MIDAS, FORMAT_YBOS, YM_CFILE::fragment_size, I4_BKTYPE, eqpmnt::info, MAX_FRAG_SIZE, MERROR, MIDAS_EVID_BANK, MINFO, O_BINARY, O_LARGEFILE, eqpmnt::odb_out, YM_PFILE::path, read, rpc_flush_event(), rpc_get_send_sock(), YM_CFILE::run_number, eqpmnt::serial_number, YM_CFILE::size, YM_CFILE::spare, SS_FILE_ERROR, SYNC, TID_CHAR, TID_DWORD, time, YM_CFILE::total_fragment, EQUIPMENT_INFO::trigger_mask, YB_SUCCESS, ybk_close(), ybk_create(), ybk_init(), ybk_size(), and YBOS_EVID_BANK.
Referenced by feodb_file_dump().
       : yb_file_fragment
Purpose: Fragment file in order to send it through Midas.
Compose an event of the form of:
Midas_header[(YM_CFILE)(YM_PFILE)(YM_DFILE)]
Specific for the fe for either format YBOS/MIDAS
Input:
EQUIPMENT * eqp        Current equipment
INT   run_number       currrent run_number
char * path            full file name specification
Output:
none
Function value:
YB_SUCCESS          Successful completion
SS_FILE_ERROR       file access error
\********************************************************************/
{
   INT dmpf, remaining;
   INT nread, filesize, nfrag;
   INT allheader_size;
   DWORD *pbuf, *pcfile, *pmy;
   YM_CFILE myc_fileh;
   YM_PFILE myp_fileh;
   int send_sock, flag;
   /* check if file exists */
   /* Open for read (will fail if file does not exist) */
   if ((dmpf = open(path, O_RDONLY | O_BINARY | O_LARGEFILE, 0644)) == -1) {
      cm_msg(MINFO, "ybos_file_fragment", "File dump -Failure- on open file %s", path);
      return SS_FILE_ERROR;
   }
   /* get file size */
   filestat = (struct stat *) malloc(sizeof(struct stat));
   stat(path, filestat);
   filesize = filestat->st_size;
   free(filestat);
   cm_msg(MINFO, "ybos_file_fragment", "Accessing File %s (%i)", path, filesize);
  /*-PAA-Oct06/97 added for ring buffer option */
   send_sock = rpc_get_send_sock();
   /* compute fragmentation & initialize */
   nfrag = filesize / MAX_FRAG_SIZE;
   /* Generate a unique FILE ID */
   srand((unsigned) time(NULL));
   srand((unsigned) time(NULL));
   /* Fill file YM_CFILE header */
   myc_fileh.file_ID = rand();
   myc_fileh.size = filesize;
   myc_fileh.total_fragment = nfrag + (((filesize % MAX_FRAG_SIZE) == 0) ? 0 : 1);
   myc_fileh.current_fragment = 0;
   myc_fileh.current_read_byte = 0;
   myc_fileh.run_number = run_number;
   myc_fileh.spare = 0x1234abcd;
   /* Fill file YM_PFILE header */
   memset(myp_fileh.path, 0, sizeof(YM_PFILE));
   /* first remove path if present */
   if (strrchr(path, '/') != NULL) {
      strncpy(myp_fileh.path, strrchr(path, '/') + 1, strlen(strrchr(path, '/')));
   } else
      strcpy(myp_fileh.path, path);
   /* allocate space */
   allheader_size = sizeof(EVENT_HEADER)
       + sizeof(YBOS_BANK_HEADER)       /* EVID bank header */
       +5 * sizeof(DWORD)       /* EVID data size */
       +sizeof(YM_CFILE)
       + sizeof(YM_PFILE) + 64;
   flag = 0;
   pevent -= 1;
   /* read file */
   while (myc_fileh.current_fragment <= nfrag) {
      /* pevent passed by fe for first event only */
      if (flag)
         pevent = dm_pointer_get();
      flag = 1;
      /* bank header */
      pmy = (DWORD *) (pevent + 1);
    /*-PAA-Oct06/97 for ring buffer reset the LRL */
      if (eqp->format == FORMAT_YBOS)
         ybk_init((DWORD *) pmy);
      else if (eqp->format == FORMAT_MIDAS)
         bk_init(pmy);
    /*---- EVID bank ----*/
      if (eqp->format == FORMAT_YBOS) {
         YBOS_EVID_BANK(pmy, myc_fileh.current_fragment,
                        (eqp->info.event_id << 16) | (eqp->info.trigger_mask)
                        , eqp->serial_number, run_number);
      } else if (eqp->format == FORMAT_MIDAS) {
         MIDAS_EVID_BANK(pmy, myc_fileh.current_fragment,
                         (eqp->info.event_id << 16) | (eqp->info.trigger_mask)
                         , eqp->serial_number, run_number);
      }
      /* Create Control file bank */
      if (eqp->format == FORMAT_YBOS)
         ybk_create(pmy, "CFIL", I4_BKTYPE, (DWORD *) & pbuf);
      else if (eqp->format == FORMAT_MIDAS)
         bk_create(pmy, "CFIL", TID_DWORD, &pbuf);
      /* save pointer for later */
      pcfile = pbuf;
      pbuf = (DWORD *) (((char *) pbuf) + sizeof(YM_CFILE));
      if (eqp->format == FORMAT_YBOS)
         ybk_close(pmy, pbuf);
      else if (eqp->format == FORMAT_MIDAS)
         bk_close(pmy, pbuf);
      /* Create Path file name bank */
      if (eqp->format == FORMAT_YBOS)
         ybk_create(pmy, "PFIL", A1_BKTYPE, (DWORD *) & pbuf);
      else if (eqp->format == FORMAT_MIDAS)
         bk_create(pmy, "PFIL", TID_CHAR, &pbuf);
      memcpy((char *) pbuf, (char *) &myp_fileh, sizeof(YM_PFILE));
      pbuf = (DWORD *) (((char *) pbuf) + sizeof(YM_CFILE));
      if (eqp->format == FORMAT_YBOS)
         ybk_close(pmy, pbuf);
      else if (eqp->format == FORMAT_MIDAS)
         bk_close(pmy, pbuf);
      /* file content */
      if (eqp->format == FORMAT_YBOS)
         ybk_create(pmy, "DFIL", A1_BKTYPE, (DWORD *) & pbuf);
      else if (eqp->format == FORMAT_MIDAS)
         bk_create(pmy, "DFIL", TID_CHAR, (DWORD *) & pbuf);
      /* compute data length */
      remaining = filesize - myc_fileh.current_read_byte;
      nread =
          read(dmpf, (char *) pbuf,
               (remaining > MAX_FRAG_SIZE) ? MAX_FRAG_SIZE : remaining);
      /* adjust target pointer */
      pbuf = (DWORD *) (((char *) pbuf) + nread);
      /* keep track of statistic */
      myc_fileh.current_fragment++;
      myc_fileh.fragment_size = nread;
      myc_fileh.current_read_byte += nread;
      memcpy((char *) pcfile, (char *) &myc_fileh, sizeof(YM_CFILE));
      /* close YBOS bank */
      if (eqp->format == FORMAT_YBOS)
         ybk_close(pmy, pbuf);
      else if (eqp->format == FORMAT_MIDAS)
         bk_close(pmy, pbuf);
      /* Fill the Midas header */
      if (eqp->format == FORMAT_YBOS)
         bm_compose_event(pevent, eqp->info.event_id,
                          eqp->info.trigger_mask, ybk_size(pmy), eqp->serial_number++);
      else if (eqp->format == FORMAT_MIDAS)
         bm_compose_event(pevent, eqp->info.event_id,
                          eqp->info.trigger_mask, bk_size(pmy), eqp->serial_number++);
    /*-PAA-Oct06/97 Added the ring buffer option for FE event send */
      eqp->bytes_sent += pevent->data_size + sizeof(EVENT_HEADER);
      eqp->events_sent++;
      if (eqp->buffer_handle) {
    /*-PAA- Jun98 These events should be sent directly as they come before the run
    started. If the event channel has to be used, then care should be taken
    if interrupt are being used too. May requires buffer checks like in
      scheduler (mfe.c) */
         /* #undef USE_EVENT_CHANNEL */
#ifdef USE_EVENT_CHANNEL
         dm_pointer_increment(eqp->buffer_handle,
                              pevent->data_size + sizeof(EVENT_HEADER));
#else
         rpc_flush_event();
         bm_send_event(eqp->buffer_handle, pevent,
                       pevent->data_size + sizeof(EVENT_HEADER), SYNC);
#endif
         eqp->odb_out++;
      }
   }
   /* close file */
   if (close(dmpf)) {
      cm_msg(MERROR, "fe_file_dump", "cannot close file: %s", path);
      return SS_FILE_ERROR;
   }
   return YB_SUCCESS;
}
INT EXPRT yb_file_recompose (void * pevt, INT fmt, char * svpath, INT file_mode)
Definition at line 3576 of file ybos.c.
References bk_locate(), YM_CFILE::current_fragment, YM_CFILE::current_read_byte, event_id, EVENTID_BOR, EVENTID_EOR, EVENTID_MESSAGE, R_YM_FILE::file_ID, YM_CFILE::file_ID, FORMAT_MIDAS, FORMAT_YBOS, YM_CFILE::fragment_size, MAX_YM_FILE, YM_CFILE::run_number, YM_CFILE::size, YM_CFILE::total_fragment, YB_BANK_NOT_FOUND, YB_COMPLETE, YB_INCOMPLETE, YB_NO_RECOVER, YB_SUCCESS, yb_ymfile_open(), yb_ymfile_update(), and ybk_locate().
Referenced by process_event(), and replog().
       : external file_recompose
Purpose: Receive event which are expected to be file oriented with
YM_xFILE header.
Input:
char * pevt           pointer to a YBOS event (->LRL).
char * svpath         path where to save file
INT    file_mode      NO_RUN : save file under original name
ADD_RUN: cat run number at end of file name
Output:
none
Function value:
YB_SUCCESS         OP successfull
YB_INCOMPLETE      file compose channels still open
YB_COMPLETE        All file compose channels closed or complete
status             -x error of inner call
\********************************************************************/
{
   YM_CFILE *pmyfch;
   int slot, status;
   if (file_mode == YB_NO_RECOVER)
      return YB_SUCCESS;
   if (format == FORMAT_YBOS) {
      if ((status = ybk_locate((DWORD *) pevt, "CFIL", &pmyfch)) <= 0)
         return (status);
   } else if (format == FORMAT_MIDAS) {
      if ((((EVENT_HEADER *) pevt)->event_id == EVENTID_BOR) ||
          (((EVENT_HEADER *) pevt)->event_id == EVENTID_EOR) ||
          (((EVENT_HEADER *) pevt)->event_id == EVENTID_MESSAGE))
         return YB_BANK_NOT_FOUND;
      pevt = (EVENT_HEADER *) pevt + 1;
      if ((status = bk_locate(pevt, "CFIL", &pmyfch)) <= 0)
         return (status);
   }
   printf("%i - %i - %i - %i - %i -%i -%i \n", pmyfch->file_ID,
          pmyfch->size, pmyfch->fragment_size, pmyfch->total_fragment,
          pmyfch->current_fragment, pmyfch->current_read_byte, pmyfch->run_number);
   /* check if file is in progress */
   for (slot = 0; slot < MAX_YM_FILE; slot++) {
      if ((ymfile[slot].fHandle != 0)
          && (pmyfch->file_ID == ymfile[slot].file_ID)) {
         /* Yep file in progress for that file_ID */
         if ((status = yb_ymfile_update(slot, format, pevt)) != YB_SUCCESS) {
            printf("yb_ymfile_update() failed\n");
            return status;
         }
         goto check;
      }
      /* next slot */
   }
   /* current fragment not registered => new file */
   /* open file, get slot back */
   if ((status = yb_ymfile_open(&slot, format, pevt, svpath, file_mode)) != YB_SUCCESS) {
      printf("yb_ymfile_open() failed\n");
      return status;
   }
   /* update file */
   if ((status = yb_ymfile_update(slot, format, pevt)) != YB_SUCCESS) {
      printf("yb_ymfile_update() failed\n");
      return status;
   }
 check:
   /* for completion of recovery on ALL files */
   for (slot = 0; slot < MAX_YM_FILE; slot++) {
      if (ymfile[slot].fHandle != 0) {
         /* Yes still some file composition in progress */
         return YB_INCOMPLETE;
      }
      /* next slot */
   }
   return YB_COMPLETE;
}
INT yb_ymfile_open (int * slot, int fmt, void * pevt, char * svpath, INT file_mode)
Definition at line 3657 of file ybos.c.
References bk_locate(), R_YM_FILE::current_fragment, R_YM_FILE::current_read_byte, DIR_SEPARATOR, DIR_SEPARATOR_STR, R_YM_FILE::fHandle, YM_CFILE::file_ID, R_YM_FILE::file_ID, FORMAT_MIDAS, FORMAT_YBOS, i, MAX_YM_FILE, O_BINARY, O_LARGEFILE, R_YM_FILE::path, YM_PFILE::path, YM_CFILE::run_number, SS_FILE_ERROR, YB_ADD_RUN, YB_NOMORE_SLOT, YB_SUCCESS, and ybk_locate().
Referenced by yb_file_recompose().
       : yb_ymfile_open
Purpose: Prepare channel for receiving event of YM_FILE type.
Input:
void * pevt           pointer to the data portion of the event
char * svpath         path where to save file
INT    file_mode      NO_RUN : save file under original name
ADD_RUN: cat run number at end of file name
Output:
INT  * slot           index of the opened channel
Function value:
YB_SUCCESS          Successful completion
YB_FAIL_OPEN        cannot create output file
YB_NOMORE_SLOT      no more slot for starting dump
\********************************************************************/
{
   YM_CFILE *pmyfch;
   YM_PFILE *pmyfph;
   char *pfilename;
   char srun[16], sslot[3];
   int i, status;
   /* initialize invalid slot */
   *slot = -1;
   if (fmt == FORMAT_YBOS) {
      if ((status = ybk_locate((DWORD *) pevt, "CFIL", &pmyfch)) <= 0)
         return (status);
      if ((status = ybk_locate((DWORD *) pevt, "PFIL", &pmyfph)) <= 0)
         return (status);
   } else if (fmt == FORMAT_MIDAS) {
      if ((status = bk_locate(pevt, "CFIL", &pmyfch)) <= 0)
         return (status);
      if ((status = bk_locate(pevt, "PFIL", &pmyfph)) <= 0)
         return (status);
   } else
      return -2;
   /* find free slot */
   for (i = 0; i < MAX_YM_FILE; i++)
      if (ymfile[i].fHandle == 0)
         break;
   if (i < MAX_YM_FILE) {
      /* copy necessary file header info */
      ymfile[i].file_ID = pmyfch->file_ID;
      strcpy(ymfile[i].path, pmyfph->path);
      /* extract file name */
      pfilename = pmyfph->path;
      if (strrchr(pmyfph->path, '/') > pfilename)
         pfilename = strrchr(pmyfph->path, '/');
      if (strrchr(pmyfph->path, '\\') > pfilename)
         pfilename = strrchr(pmyfph->path, '\\');
      if (strrchr(pmyfph->path, ':') > pfilename)
         pfilename = strrchr(pmyfph->path, ':');
      if (*pfilename != pmyfph->path[0])
         pfilename++;
      /* add path name */
      if (svpath[0] != 0) {
         ymfile[i].path[0] = 0;
         strncat(ymfile[i].path, svpath, strlen(svpath));
         if (ymfile[i].path[strlen(ymfile[i].path) - 1] != DIR_SEPARATOR)
            strcat(ymfile[i].path, DIR_SEPARATOR_STR);
         /* append the file name */
         strcat(ymfile[i].path, pfilename);
      }
      if (file_mode == YB_ADD_RUN) {    /* append run number */
         strcat(ymfile[i].path, ".");
         sprintf(srun, "Run%4.4i", pmyfch->run_number);
         strncat(ymfile[i].path, srun, strlen(srun));
      }
      /* differentiate the possible file dumps
         as the path is unique */
      if (i > 0) {
         sprintf(sslot, ".%03i", i);
         strcat(ymfile[i].path, sslot);
      }
      /* open device */
      if ((ymfile[i].fHandle =
           open(ymfile[i].path, O_WRONLY | O_CREAT | O_TRUNC | O_BINARY | O_LARGEFILE, 0644)) == -1) {
         ymfile[i].fHandle = 0;
         printf("File %s cannot be created\n", ymfile[i].path);
         return (SS_FILE_ERROR);
      }
   } else {
      /* no more slot */
      printf("No more slot for file %s\n", pmyfph->path);
      return YB_NOMORE_SLOT;
   }
   ymfile[i].current_read_byte = 0;
   ymfile[i].current_fragment = 0;
   *slot = i;
   return YB_SUCCESS;
}
INT yb_ymfile_update (int slot, int fmt, void * pevt)
Definition at line 3756 of file ybos.c.
References bk_locate(), R_YM_FILE::current_fragment, YM_CFILE::current_fragment, R_YM_FILE::current_read_byte, R_YM_FILE::fHandle, FORMAT_MIDAS, FORMAT_YBOS, YM_CFILE::fragment_size, YM_CFILE::total_fragment, write, YB_SUCCESS, YB_UNKNOWN_FORMAT, and ybk_locate().
Referenced by yb_file_recompose().
       : yb_ymfile_update
Purpose: dump Midas/Ybos event to file for YBOS file oriented event type.
Input:
char * pevt           pointer to the data portion of the event.
Output:
INT  slot             valid index of the opened channel.
Function value:
YB_SUCCESS         Successful completion
-1                     error
\********************************************************************/
{
   YM_CFILE *pmyfch;
   char *pmyfd;
   int status;
   int nwrite;
   if (fmt == FORMAT_YBOS) {
      if ((status = ybk_locate((DWORD *) pevt, "CFIL", &pmyfch)) <= 0)
         return (status);
      if ((status = ybk_locate((DWORD *) pevt, "DFIL", &pmyfd)) <= 0)
         return (status);
      /* check sequence order */
      if (ymfile[slot].current_fragment + 1 != pmyfch->current_fragment) {
         printf("Out of sequence %i / %i\n", ymfile[slot].current_fragment,
                pmyfch->current_fragment);
      }
      /* dump fragment to file */
      nwrite = write(ymfile[slot].fHandle, pmyfd, pmyfch->fragment_size);
      /* update current file record */
      ymfile[slot].current_read_byte += nwrite;
      ymfile[slot].current_fragment++;
      /* check if file has to be closed */
      if (ymfile[slot].current_fragment == pmyfch->total_fragment) {
         /* file complete */
         close(ymfile[slot].fHandle);
         printf("File %s (%i) completed\n", ymfile[slot].path,
                ymfile[slot].current_read_byte);
         /* cleanup slot */
         ymfile[slot].fHandle = 0;
         return YB_SUCCESS;
      } /* close file */
      else {
         /* fragment retrieved wait next one */
         return YB_SUCCESS;
      }
   } else if (fmt == FORMAT_MIDAS) {
      if ((status = bk_locate(pevt, "CFIL", &pmyfch)) <= 0)
         return (status);
      if ((status = bk_locate(pevt, "DFIL", &pmyfd)) <= 0)
         return (status);
      /* check sequence order */
      if (ymfile[slot].current_fragment + 1 != pmyfch->current_fragment) {
         printf("Out of sequence %i / %i\n", ymfile[slot].current_fragment,
                pmyfch->current_fragment);
      }
      /* dump fragment to file */
      nwrite = write(ymfile[slot].fHandle, pmyfd, pmyfch->fragment_size);
      /* update current file record */
      ymfile[slot].current_read_byte += nwrite;
      ymfile[slot].current_fragment++;
      /* check if file has to be closed */
      if (ymfile[slot].current_fragment == pmyfch->total_fragment) {
         /* file complete */
         close(ymfile[slot].fHandle);
         printf("File %s (%i) completed\n", ymfile[slot].path,
                ymfile[slot].current_read_byte);
         /* cleanup slot */
         ymfile[slot].fHandle = 0;
         return YB_SUCCESS;
      } /* close file */
      else {
         /* fragment retrieved wait next one */
         return YB_SUCCESS;
      }
   } else
      return YB_UNKNOWN_FORMAT;
}
INT EXPRT ybk_close (DWORD * plrl, void * pbkdat)
dox Close the YBOS bank previously created by ybk_create().
The data pointer pdata must be obtained by ybk_create() and used as an address to fill a bank. It is incremented with every value written to the bank and finally points to a location just after the last byte of the bank. It is then passed to ybk_close() to finish the bank creation. YBOS is a 4 bytes bank aligned structure. Padding is performed at the closing of the bank with values of 0x0f or/and 0x0ffb. See YBOS_bank_examples.
Parameters:
plrl pointer to current composed event.
pbkdat pointer to the current data.
Returns:
number number of bytes contained in bank.
Definition at line 549 of file ybos.c.
References YBOS_BANK_HEADER::length.
Referenced by cd_gen_read(), cd_hv_read(), cd_multi_read(), read_scaler_event(), read_trigger_event(), yb_file_fragment(), ybk_close_chaos(), and ybos_write().
{
   DWORD tdlen;
   /* align pbkdat to I*4 */
   if (((DWORD) pbkdat & 0x1) != 0) {
      *((BYTE *) pbkdat) = 0x0f;
      pbkdat = (void *) (((BYTE *) pbkdat) + 1);
   }
   if (((DWORD) pbkdat & 0x2) != 0) {
      *((WORD *) pbkdat) = 0x0ffb;
      pbkdat = (void *) (((WORD *) pbkdat) + 1);
   }
   /* length in byte */
   tdlen = (DWORD) ((char *) pbkdat - (char *) __pbkh - sizeof(YBOS_BANK_HEADER));
   /* YBOS bank length in I4 */
   __pbkh->length = (tdlen + 4) / 4;    /* (+Bank Type &@#$!) YBOS bank length */
   /* adjust Logical Record Length (entry point from the system) */
   *plrl += __pbkh->length + (sizeof(YBOS_BANK_HEADER) / 4) - 1;
   return __pbkh->length;
}
INT EXPRT ybk_close_chaos (DWORD * pevent, DWORD btype, void * pbkdat)
Definition at line 491 of file ybos.c.
References __pchaosi4, A1_BKTYPE, D8_BKTYPE, F4_BKTYPE, I1_BKTYPE, I2_BKTYPE, I4_BKTYPE, SWAP_D2WORD, and ybk_close().
Referenced by read_trigger_event().
       : ybk_close_chaos
Purpose: patch the end of the event to the next 4 byte boundary,
fills up the bank header,
compute the data size in bt unit.
update the LRL (pevt)
Input:
DWORD * pevt          pointer to the top of the YBOS event (LRL).
DWORD   bt            bank type
I2_BKTYPE, I1_BKTYPE, I4_BKTYPE, F4_BKTYPE
void  * pbkdat        pointer to the user area
Output:
none
Function value: Number of bytes in the bank.
\********************************************************************/
{
   switch (bktype) {
   case D8_BKTYPE:
      *__pchaosi4 = (DWORD) ((double *) pbkdat - (double *) __pchaosi4 - 1);
      break;
   case I4_BKTYPE:
   case F4_BKTYPE:
      *__pchaosi4 = (DWORD) ((DWORD *) pbkdat - __pchaosi4 - 1);
      break;
   case I2_BKTYPE:
      *__pchaosi4 = (DWORD) ((WORD *) pbkdat - (WORD *) __pchaosi4 - 2);
      SWAP_D2WORD(__pchaosi4);
      break;
   case I1_BKTYPE:
   case A1_BKTYPE:
      *__pchaosi4 = (DWORD) ((BYTE *) pbkdat - (BYTE *) __pchaosi4 - 4);
      break;
   default:
      printf(" unknown YBOS bank type (%ld)\n", bktype);
      break;
   }
   return ybk_close(plrl, pbkdat);
}
void EXPRT ybk_create (DWORD * plrl, char * bkname, DWORD bktype, void * pbkdat)
dox Define the following memory area to be a YBOS bank with the given attribute. See YBOS_bank_examples.
Before banks can be created in an event, ybk_init(). has to be called first. YBOS does not support mixed bank type. i.e: all the data are expected to be of the same type. YBOS is a 4 bytes bank aligned structure. Padding is performed at the closing of the bank (see ybk_close) with values of 0x0f or/and 0x0ffb. See YBOS_bank_examples.
Parameters:
plrl pointer to the first DWORD of the event area.
bkname name to be assigned to the breated bank (max 4 char)
bktype YBOS_Bank_Types of the values for the entire created bank.
pbkdat return pointer to the first empty data location.
Returns:
void
Definition at line 438 of file ybos.c.
References YBOS_BANK_HEADER::index, YBOS_BANK_HEADER::length, YBOS_BANK_HEADER::name, YBOS_BANK_HEADER::number, and YBOS_BANK_HEADER::type.
Referenced by cd_gen_read(), cd_hv_read(), cd_multi_read(), read_scaler_event(), read_trigger_event(), yb_file_fragment(), and ybos_write().
{
   DWORD dname = 0;
   __pbkh = (YBOS_BANK_HEADER *) (((DWORD *) (plrl + 1)) + (*(DWORD *) plrl));
   strncpy((char *) &dname, bkname, 4);
   __pbkh->name = *((DWORD *) bkname);
   __pbkh->number = 1;
   __pbkh->index = 0;
   __pbkh->length = 0;
   __pbkh->type = bktype;
   *((DWORD **) pbkdat) = (DWORD *) (__pbkh + 1);
   return;
}
void EXPRT ybk_create_chaos (DWORD * pevent, char * bname, DWORD btype, void * pbkdat)
Definition at line 458 of file ybos.c.
References __pchaosi4, YBOS_BANK_HEADER::index, YBOS_BANK_HEADER::length, YBOS_BANK_HEADER::name, YBOS_BANK_HEADER::number, and YBOS_BANK_HEADER::type.
Referenced by read_trigger_event().
       : ybk_create
Purpose: fills up the bank header,
reserve the first 4bytes for the size of the bank in bt unit
and return the pointer to the user space.
Input:
DWORD * pevt          pointer to the top of the YBOS event (LRL)
char  * bname         Bank name should be char*4
DWORD   bktype            Bank type can by either
I2_BKTYPE, I1_BKTYPE, I4_BKTYPE, F4_BKTYPE
Output:
void    *pbkdat       pointer to first valid data of the created bank
Function value:
none
\********************************************************************/
{
   DWORD dname = 0;
   __pbkh = (YBOS_BANK_HEADER *) ((plrl + 1) + (*plrl));
   strncpy((char *) &dname, bkname, 4);
   __pbkh->name = *((DWORD *) bkname);
   __pbkh->number = 1;
   __pbkh->index = 0;
   __pbkh->length = 0;
   __pbkh->type = bktype;
   *((DWORD **) pbkdat) = (DWORD *) (__pbkh + 1);
   __pchaosi4 = (DWORD *) (*(DWORD *) pbkdat);
   *((DWORD **) pbkdat) += 1;
   return;
}
INT EXPRT ybk_find (DWORD * plrl, char * bkname, DWORD * bklen, DWORD * bktype, void ** pbk)
Find the requested bank and return the infirmation if the bank as well as the pointer to the top of the data section.
Parameters:
plrl pointer to the area of event.
bkname name of the bank to be located.
bklen returned length in 4bytes unit of the bank.
bktype returned bank type.
pbk pointer to the first data of the found bank.
Returns:
YB_SUCCESS, YB_BANK_NOT_FOUND, YB_WRONG_BANK_TYPE
Definition at line 643 of file ybos.c.
References YBOS_BANK_HEADER::length, MAX_BKTYPE, YBOS_BANK_HEADER::name, YBOS_BANK_HEADER::type, YB_BANK_NOT_FOUND, YB_SUCCESS, and YB_WRONG_BANK_TYPE.
Referenced by bevid_2_mheader(), process_event(), replog(), and yb_any_bank_event_display().
{
   YBOS_BANK_HEADER *pevt;
   DWORD *pendevt;
   pevt = (YBOS_BANK_HEADER *) (plrl + 1);
   /* end of event pointer skip LRL, point to YBOS_BANK_HEADER */
   pendevt = (DWORD *) pevt + *plrl;
   /* check if bank_type in range */
   if (pevt->type >= MAX_BKTYPE)
      return (YB_WRONG_BANK_TYPE);
   /* init returned variables */
   *bklen = 0;
   *bktype = 0;
   /* scan event */
   while ((DWORD *) pevt < pendevt) {
      /* check bank name */
      if (strncmp((char *) &(pevt->name), bkname, 4) == 0) {    /* bank name match */
         /* extract bank length */
         *bklen = pevt->length - 1;     /* exclude bank type */
         /* extract bank type */
         *bktype = pevt->type;
         /* return point to bank name */
         *pbk = &pevt->name;
         return (YB_SUCCESS);
      } else {
         /* skip to next bank */
         pevt = (YBOS_BANK_HEADER *) (((DWORD *) pevt) + pevt->length + 4);
      }
   }
   return (YB_BANK_NOT_FOUND);
}
void EXPRT ybk_init (DWORD * plrl)
Initializes an event for YBOS banks structure.
Before banks can be created in an event, ybk_init() has to be called first. See YBOS_bank_examples.
Parameters:
plrl pointer to the first DWORD of the event area of event
Returns:
void
Definition at line 408 of file ybos.c.
Referenced by cd_gen_read(), cd_hv_read(), cd_multi_read(), read_scaler_event(), read_trigger_event(), yb_file_fragment(), and ybos_write().
{
   *plrl = 0;
   return;
}
INT EXPRT ybk_iterate (DWORD * plrl, YBOS_BANK_HEADER ** pybkh, void ** pdata)
Returns the bank header pointer and data pointer of the given bank name.
Parameters:
plrl pointer to the area of event.
pybkh pointer to the YBOS bank header.
pdata pointer to the first data of the current bank.
Returns:
data length in 4 bytes unit. return -1 if no more bank found.
Definition at line 729 of file ybos.c.
References I1_BKTYPE, YBOS_BANK_HEADER::length, and YB_WRONG_BANK_TYPE.
Referenced by update_odb(), and yb_any_bank_event_display().
{
   static int len;
   static DWORD *pendevt;
   static DWORD *pybk;
   /*PAA char bname[5]; */
   /* the event may have several bank
      check if we have been already in here */
   if (*pybkh == NULL) {
      /* first time in (skip lrl) */
      *pybkh = (YBOS_BANK_HEADER *) (plrl + 1);
      if ((*pybkh)->type > I1_BKTYPE) {
         *pdata = NULL;
         *pybkh = (YBOS_BANK_HEADER *) * pdata;
         return (YB_WRONG_BANK_TYPE);
      }
      /* end of event pointer (+ lrl) */
      pendevt = plrl + *plrl;
      /* skip the EVID bank if present */
    /*-PAA- keep it in for a little while Dec 17/98
    *((DWORD *)bname) = (*pybkh)->name;
    if (strncmp (bname,"EVID",4) == 0)
    {
    len = (*pybkh)->length;
    (YBOS_BANK_HEADER *)(*pybkh)++;
    pybk = (DWORD *) *pybkh;
    pybk += len - 1;
    *pybkh = (YBOS_BANK_HEADER *) pybk;
    }
    */
   } else {
      /* already been in iterate */
      /* skip current pointed bank ( + bank_length + header) */
      len = (*pybkh)->length;
      (YBOS_BANK_HEADER *) (*pybkh)++;
      pybk = (DWORD *) * pybkh;
      pybk += len - 1;
      *pybkh = (YBOS_BANK_HEADER *) pybk;
   }
   /* check for end of event */
   if ((DWORD *) (*pybkh) < pendevt) {
      /* points to the data section */
      *pdata = (void *) (*pybkh + 1);
      /* length always in I*4 due to YBOS -1 because type included in length !@# */
      return ((*pybkh)->length - 1);
   } else {
      /* no more bank in this event */
      *pdata = NULL;
      *pybkh = (YBOS_BANK_HEADER *) * pdata;
      return (-1);
   }
}
INT EXPRT ybk_list (DWORD * plrl, char * bklist)
Returns the size in bytes of the event composed of YBOS bank(s).
The bk_list() has to be a predefined string of max size of YB_STRING_BANKLIST_MAX.
Parameters:
plrl pointer to the area of event
bklist Filled character string of the YBOS bank names found in the event.
Returns:
number of banks found in this event.
Definition at line 594 of file ybos.c.
References cm_msg, MAX_BKTYPE, MINFO, YBOS_BANK_HEADER::name, YBOS_BANK_HEADER::type, YB_BANKLIST_MAX, and YB_WRONG_BANK_TYPE.
Referenced by process_event(), replog(), and yb_any_bank_event_display().
{
   YBOS_BANK_HEADER *pbk;
   DWORD *pendevt, nbk;
   pbk = (YBOS_BANK_HEADER *) (plrl + 1);
   /* end of event pointer skip LRL, point to YBOS_BANK_HEADER */
   pendevt = (DWORD *) pbk + *plrl;
   /* check if bank_type in range */
   if (pbk->type >= MAX_BKTYPE)
      return (YB_WRONG_BANK_TYPE);
   /*init bank counter and returned string */
   nbk = 0;
   bklist[0] = 0;
   /* scan event */
   while ((DWORD *) pbk < pendevt) {
      /* update the number of bank counter */
      nbk++;
      if (nbk > YB_BANKLIST_MAX) {
         cm_msg(MINFO, "ybk_list", "over %i banks -> truncated", YB_BANKLIST_MAX);
         return (nbk);
      }
      /* append ybos bank name to list */
      strncat(bklist, (char *) &(pbk->name), 4);
      /* skip to next bank */
      pbk = (YBOS_BANK_HEADER *) (((DWORD *) pbk) + pbk->length + 4);
   }
   return (nbk);
}
INT EXPRT ybk_locate (DWORD * plrl, char * bkname, void * pdata)
Locate the requested bank and return the pointer to the top of the data section.
Parameters:
plrl pointer to the area of event
bkname name of the bank to be located.
pdata pointer to the first data of the located bank.
Returns:
Number of DWORD in bank or YB_BANK_NOT_FOUND, YB_WRONG_BANK_TYPE (<0)
Definition at line 690 of file ybos.c.
References YBOS_BANK_HEADER::length, MAX_BKTYPE, YBOS_BANK_HEADER::name, YBOS_BANK_HEADER::type, YB_BANK_NOT_FOUND, and YB_WRONG_BANK_TYPE.
Referenced by yb_file_recompose(), yb_ymfile_open(), and yb_ymfile_update().
{
   YBOS_BANK_HEADER *pybk;
   DWORD *pendevt;
   pybk = (YBOS_BANK_HEADER *) (plrl + 1);
   /* end of event pointer skip LRL, point to YBOS_BANK_HEADER */
   pendevt = (DWORD *) pybk + *plrl;
   /* check if bank_type in range */
   if (pybk->type >= MAX_BKTYPE)
      return (YB_WRONG_BANK_TYPE);
   /* scan event */
   while ((DWORD *) pybk < pendevt) {
      /* check bank name */
      if (strncmp((char *) &(pybk->name), bkname, 4) == 0) {    /* bank name match */
         /* extract bank length */
         /* return pointer to data section */
         *((void **) pdata) = pybk + 1;
         return (pybk->length - 1);
      } else {
         /* skip to next bank */
         pybk = (YBOS_BANK_HEADER *) (((DWORD *) pybk) + pybk->length + 4);
      }
   }
   return (YB_BANK_NOT_FOUND);
}
INT EXPRT ybk_size (DWORD * plrl)
Returns the size in bytes of the event composed of YBOS bank(s).
Parameters:
plrl pointer to the area of event
Returns:
number of bytes contained in data area of the event
Definition at line 579 of file ybos.c.
Referenced by cd_gen_read(), cd_hv_read(), cd_multi_read(), process_event(), read_scaler_event(), read_trigger_event(), yb_file_fragment(), and ybos_write().
{
   return (*((DWORD *) plrl) * 4 + 4);
}
void ybos_bank_display (YBOS_BANK_HEADER * pybk, INT dsp_fmt)
Definition at line 2995 of file ybos.c.
References A1_BKTYPE, bank_name, D8_BKTYPE, DSP_ASC, DSP_DEC, DSP_HEX, DSP_UNK, F4_BKTYPE, i, I1_BKTYPE, I2_BKTYPE, I4_BKTYPE, j, YBOS_BANK_HEADER::length, YBOS_BANK_HEADER::name, and YBOS_BANK_HEADER::type.
Referenced by yb_any_bank_display(), and yb_any_bank_event_display().
       : ybos_event_display
Purpose: display on screen the YBOS data in YBOS bank mode.
Input:
YBOS_BANK_HEADER * pybk     pointer to the bank header
INT     dsp_fmt             display format (DSP_DEC/HEX)
Output:
none
Function value:
none
\********************************************************************/
{
   char bank_name[5], strbktype[32];
   DWORD length_type = 0;
   DWORD *pdata, *pendbk;
   INT i, j;
   j = 8;                       /* elements within line */
   i = 1;                       /* data counter */
   pdata = (DWORD *) (pybk + 1);
   memcpy(&bank_name[0], (char *) &pybk->name, 4);
   bank_name[4] = 0;
   if (pybk->type == D8_BKTYPE) {
      length_type = ((pybk->length - 1) >> 1);
      sprintf(strbktype, "double*8 (FMT machine dependent)");
   }
   if (pybk->type == F4_BKTYPE) {
      length_type = pybk->length - 1;
      strcpy(strbktype, "Real*4 (FMT machine dependent)");
   }
   if (pybk->type == I4_BKTYPE) {
      length_type = pybk->length - 1;
      strcpy(strbktype, "Integer*4");
   }
   if (pybk->type == I2_BKTYPE) {
      length_type = ((pybk->length - 1) << 1);
      strcpy(strbktype, "Integer*2");
   }
   if (pybk->type == I1_BKTYPE) {
      length_type = ((pybk->length - 1) << 2);
      strcpy(strbktype, "8 bit Bytes");
   }
   if (pybk->type == A1_BKTYPE) {
      length_type = ((pybk->length - 1) << 2);
      strcpy(strbktype, "8 bit ASCII");
   }
   printf("\nBank:%s Length: %li(I*1)/%li(I*4)/%li(Type) Type:%s",
          bank_name, ((pybk->length - 1) << 2), pybk->length - 1, length_type, strbktype);
   j = 16;
   pendbk = pdata + pybk->length - 1;
   while ((BYTE *) pdata < (BYTE *) pendbk) {
      switch (pybk->type) {
      case D8_BKTYPE:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         printf("%15.5le  ", *((double *) pdata));
         pdata = (DWORD *) (((double *) pdata) + 1);
         j++;
         break;
      case F4_BKTYPE:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if ((dsp_fmt == DSP_DEC) || (dsp_fmt == DSP_UNK))
            printf("%8.3e ", *((float *) pdata));
         if (dsp_fmt == DSP_HEX)
            printf("0x%8.8lx ", *((DWORD *) pdata));
         pdata++;
         j++;
         break;
      case I4_BKTYPE:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if (dsp_fmt == DSP_DEC)
            printf("%8.1li ", *((DWORD *) pdata));
         if ((dsp_fmt == DSP_HEX) || (dsp_fmt == DSP_UNK))
            printf("0x%8.8lx ", *((DWORD *) pdata));
         pdata++;
         j++;
         break;
      case I2_BKTYPE:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if (dsp_fmt == DSP_DEC)
            printf("%5.1i ", *((WORD *) pdata));
         if ((dsp_fmt == DSP_HEX) || (dsp_fmt == DSP_UNK))
            printf("0x%4.4x ", *((WORD *) pdata));
         pdata = (DWORD *) (((WORD *) pdata) + 1);
         j++;
         break;
      case A1_BKTYPE:
         if (j > 15) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 16;
         }
         if ((dsp_fmt == DSP_ASC) || (dsp_fmt == DSP_UNK))
            printf("%1.1s ", (char *) pdata);
         if (dsp_fmt == DSP_DEC)
            printf("%2.i ", *((BYTE *) pdata));
         if (dsp_fmt == DSP_HEX)
            printf("0x%2.2x ", *((BYTE *) pdata));
         pdata = (DWORD *) (((BYTE *) pdata) + 1);
         j++;
         break;
      case I1_BKTYPE:
         if (j > 7) {
            printf("\n%4i-> ", i);
            j = 0;
            i += 8;
         }
         if ((dsp_fmt == DSP_DEC) || (dsp_fmt == DSP_UNK))
            printf("%4.i ", *((BYTE *) pdata));
         if (dsp_fmt == DSP_HEX)
            printf("0x%2.2x ", *((BYTE *) pdata));
         pdata = (DWORD *) (((BYTE *) pdata) + 1);
         j++;
         break;
      default:
         printf("ybos_bak_display-E- Unknown bank type %li\n", pybk->type);
         break;
      }                         /* switch */
   }                            /* while next bank */
   printf("\n");
   return;
}
INT ybos_buffer_flush (LOG_CHN * log_chn, INT run_number)
Definition at line 1359 of file ybos.c.
References CHN_STATISTICS::bytes_written, CHN_STATISTICS::bytes_written_total, EVENTID_EOR, LOG_CHN::format, LOG_CHN::format_info, LOG_CHN::handle, YBOS_PHYSREC_HEADER::header_length, if, LOG_TYPE_TAPE, CHN_SETTINGS::odb_dump, YBOS_PHYSREC_HEADER::offset, YBOS_INFO::pbuf, YBOS_INFO::pwrt, YBOS_PHYSREC_HEADER::rec_num, YBOS_PHYSREC_HEADER::rec_size, YBOS_INFO::recn, YBOS_INFO::reco, LOG_CHN::settings, LOG_CHN::statistics, status, LOG_CHN::type, yb_any_log_write(), YBOS_HEADER_LENGTH, ybos_log_dump(), and YBOS_PHYREC_SIZE.
Referenced by ybos_log_close().
       : ybos_buffer_flush
Purpose: Empty the internal buffer to logger channel for YBOS fmt
YBOS end of run marks (End of file) is -1 in the *plrl
I'm writting an extra FULL YBOS_PHYSREC_SIZE of -1
Input:
LOG_CHN * log_chn      Concern log channel
Output:
none
Function value:
error, success
\********************************************************************/
{
   INT status;
   YBOS_INFO *ybos;
   YBOS_PHYSREC_HEADER *yb_phrh;
   ybos = (YBOS_INFO *) log_chn->format_info;
   /* dump the ODB if necessary */
   if (log_chn->settings.odb_dump)
      ybos_log_dump(log_chn, EVENTID_EOR, run_number);
   /* adjust read pointer to beg of record */
   ybos->pwrt -= YBOS_HEADER_LENGTH;
   yb_phrh = (YBOS_PHYSREC_HEADER *) ybos->pwrt;
   yb_phrh->rec_size = YBOS_PHYREC_SIZE - 1;    /* exclusive */
   yb_phrh->header_length = YBOS_HEADER_LENGTH; /* inclusive */
   yb_phrh->rec_num = ybos->recn;
   yb_phrh->offset = ybos->reco;        /* exclusive from block_size */
/* YBOS known only about fix record size. The way to find out
it there is no more valid event is to look at the LRL for -1
  put some extra -1 in the current physical record */
   memset((DWORD *) ybos->pbuf, -1, YBOS_PHYREC_SIZE << 2);
   /* write record to device */
   status =
       yb_any_log_write(log_chn->handle, log_chn->format, log_chn->type,
                        ybos->pwrt, YBOS_PHYREC_SIZE << 2);
#ifdef YBOS_VERSION_3_3
   if (log_chn->type == LOG_TYPE_TAPE) {
      log_chn->statistics.bytes_written += YBOS_PHYREC_SIZE << 2;
      log_chn->statistics.bytes_written_total += YBOS_PHYREC_SIZE << 2;
   } else {
      /* write MAGTA header (4bytes)=0x7ff8 */
      log_chn->statistics.bytes_written += YBOS_PHYREC_SIZE << 2 + 4;
      log_chn->statistics.bytes_written_total += YBOS_PHYREC_SIZE << 2 + 4;
   }
#else
   log_chn->statistics.bytes_written += YBOS_PHYREC_SIZE << 2;
   log_chn->statistics.bytes_written_total += YBOS_PHYREC_SIZE << 2;
#endif
   return status;
}
INT ybos_event_get (DWORD ** plrl, DWORD * size)
Definition at line 2568 of file ybos.c.
References my, size, YB_DONE, YB_SUCCESS, YBOS_HEADER_LENGTH, YBOS_PHYREC_SIZE, and ybos_physrec_get().
Referenced by ma_read_event(), and yb_any_event_get().
       : ybos_event_get
Purpose: read one YBOS event.
detect the end of run by checking the *plrl content (-1)
Input:
Output:
DWORD ** plrl      points to LRL valid full YBOS event
DWORD * readn      event size in Bytes
Function value:
YB_DONE           No more record to read
YB_SUCCESS        Ok
\********************************************************************/
{
   DWORD size, fpart, lpart, evt_length;
   DWORD *ptmp, *prec;
   INT status;
   /* detect end of run (no more events)
      by checking the *pyrd == -1 */
   if ((INT) (*my.pyrd) == -1)
      return YB_DONE;
   /* extract event to local event area
      event may not be complete if larger then physical record size
      will be taken care below, ADD the lrl  */
   evt_length = *(my.pyrd) + 1;
   memcpy((char *) my.pylrl, (char *) my.pyrd, evt_length << 2);
   /* extract lrl in I*4 and include itself (lrl) */
   /* stop if LRL  = -1 ... I don't think it is necessary but I leave it in for now
      or forever... */
   if (evt_length - 1 == -1)
      return (YB_DONE);
   /* check if event cross physical record boundary */
   if ((my.pyrd + evt_length) >= (DWORD *) my.pyh + my.size) {
      /* upcomming event crosses block, then first copy first part of event */
      /* compute max copy for first part of event */
      fpart = (DWORD *) my.pyh + my.size - my.pyrd;
      memcpy((char *) my.pylrl, (char *) my.pyrd, fpart << 2);
      /* adjust temporary evt pointer all in I*4 */
      ptmp = my.pylrl + fpart;
      if ((evt_length - fpart) == 0) {
         /* get next physical record */
         if ((status = ybos_physrec_get(&prec, &size)) != YB_SUCCESS)
            return (status);
         my.pyrd = (DWORD *) my.pyh + my.pyh->header_length;
      } else {
         while ((evt_length - fpart) > 0) {
            lpart = evt_length - fpart;
            if (lpart > (YBOS_PHYREC_SIZE - YBOS_HEADER_LENGTH))
               lpart = (YBOS_PHYREC_SIZE - YBOS_HEADER_LENGTH);
            /* get next physical record */
            if ((status = ybos_physrec_get(&prec, &size)) != YB_SUCCESS)
               return (status);
            /* pyrd is left at the next lrl but here we comming from
               a cross boundary request so read just the pyrd to
               pyh+header_length */
            my.pyrd = (DWORD *) my.pyh + my.pyh->header_length;
            /* now copy remaining from temporary pointer */
            memcpy((char *) ptmp, (char *) my.pyrd, lpart << 2);
            /* adjust pointer to next valid data (LRL)
               should be equivalent to pyh+pyh->offset */
            my.pyrd += lpart;
            fpart += lpart;
            ptmp += lpart;
         }
      }
      if (my.pyrd != (DWORD *) my.pyh + my.pyh->offset) {
         printf(" event misalignment !! %p  %p \n",
                my.pyrd, (DWORD *) my.pyh + my.pyh->offset);
         printf("Event crossed boundary: length %ld\n", evt_length);
         my.pyrd = (DWORD *) my.pyh + my.pyh->offset;
      }
   } else {
      /* adjust pointer to next valid data (LRL) */
      my.pyrd += evt_length;
   }
   /* count event */
   my.evtn++;
  /*-PAA- Dec99 Danny adjust event size in I*4 */
   my.evtlen = evt_length;
   /* in bytes for the world */
   *readn = my.evtlen << 2;
   *plrl = (DWORD *) my.pylrl;
   return (YB_SUCCESS);
}
INT ybos_event_swap (DWORD * pevt)
Definition at line 2457 of file ybos.c.
References A1_BKTYPE, D8_BKTYPE, DWORD_SWAP, F4_BKTYPE, I1_BKTYPE, I2_BKTYPE, I4_BKTYPE, MAX_BKTYPE, QWORD_SWAP, type, WORD_SWAP, YB_EVENT_NOT_SWAPPED, YB_SUCCESS, and YB_SWAP_ERROR.
Referenced by eb_yfragment_add(), source_scan(), yb_any_event_swap(), and ybos_write().
       : ybos_event_swap
Purpose: byte swap the entire YBOS event if necessary.
chekc necessity of swapping by looking at the
bank type being < MAX_BKTYPE
Input:
DWORD * plrl           pointer to the YBOS event
Output:
none
Function value:
YB_SUCCESS             Event has been swapped
YB_EVENT_NOT_SWAPPED   Event has been not been swapped
YB_SWAP_ERROR          swapping error
\********************************************************************/
{
   DWORD *pevt, *pnextb, *pendevt;
   DWORD bank_length, bank_type;
   /* check if event has to be swapped */
   if ((((YBOS_BANK_HEADER *) (plrl + 1))->type) < MAX_BKTYPE)
      return (YB_EVENT_NOT_SWAPPED);
   /* swap LRL */
   DWORD_SWAP(plrl);
   pevt = plrl + 1;
   /* end of event pointer */
   pendevt = pevt + *plrl;
   /* scan event */
   while (pevt < pendevt) {
      /* swap YBOS bank header for sure */
      /* bank name doesn't have to be swapped as it's an ASCII coded */
      pevt++;                   /* bank name */
      DWORD_SWAP(pevt);         /* bank number */
      pevt++;
      DWORD_SWAP(pevt);         /* bank index */
      pevt++;
      DWORD_SWAP(pevt);         /* bank length */
      bank_length = *pevt++;
      DWORD_SWAP(pevt);         /* bank type */
      bank_type = *pevt++;
      /* pevt left pointing at first data in bank */
      /* pointer to next bank (-1 due to type inclided in length #$%@ */
      pnextb = pevt + bank_length - 1;
      switch (bank_type) {
      case D8_BKTYPE:
         while ((BYTE *) pevt < (BYTE *) pnextb) {
            QWORD_SWAP(pevt);
            pevt = (DWORD *) (((double *) pevt) + 1);
         }
         break;
      case I4_BKTYPE:
      case F4_BKTYPE:
         while ((BYTE *) pevt < (BYTE *) pnextb) {
            DWORD_SWAP(pevt);
            pevt++;
         }
         break;
      case I2_BKTYPE:
         while ((BYTE *) pevt < (BYTE *) pnextb) {
            WORD_SWAP(pevt);
            pevt = (DWORD *) (((WORD *) pevt) + 1);
         }
         break;
      case I1_BKTYPE:
      case A1_BKTYPE:
         pevt = pnextb;
         break;
      default:
         printf("ybos_swap_event-E- Unknown bank type %li\n", bank_type);
         return (YB_SWAP_ERROR);
         break;
      }
   }
   return (YB_SUCCESS);
}
INT EXPRT ybos_get_tid_size (INT tid)
Definition at line 1047 of file ybos.c.
References yb_tid_size.
{
   if (tid < 8)
      return yb_tid_size[tid];
   return 0;
}
void ybos_log_dump (LOG_CHN * log_chn, short int event_id, INT run_number)
Definition at line 1505 of file ybos.c.
References bm_compose_event(), buffer_size, cm_get_experiment_database(), cm_msg, EVENT_HEADER::data_size, db_copy(), DB_TRUNCATED, hDB, MERROR, MIDAS_MAGIC, size, status, and ybos_write().
Referenced by ybos_buffer_flush(), and ybos_log_open().
       : ybos_log_dump, used by mlogger, ybos_log_open
Purpose: Serves the logger flag /logger/settings/ODB dump
Extract the ODB in ASCII format and send it to the logger channel
Compose a ybos bank in A1_BKTYPE regardless of the odb size.
It uses ybos_write to compose the actual event. From here it looks
like a MIDAS event.
Input:
LOG_CHN * log_chn      Concern log channel
short in  event_id     event ID
INT   run_number       run number
Output:
none
Function value:
none
\********************************************************************/
{
   INT status, buffer_size, size;
   EVENT_HEADER *pevent;
   HNDLE hDB;
   cm_get_experiment_database(&hDB, NULL);
   /* write ODB dump */
   buffer_size = 10000;
   do {
      pevent = (EVENT_HEADER *) malloc(buffer_size);
      if (pevent == NULL) {
         cm_msg(MERROR, "ybos_odb_log_dump", "Cannot allocate ODB dump buffer");
         break;
      }
      size = buffer_size - sizeof(EVENT_HEADER);
      status = db_copy(hDB, 0, (char *) (pevent + 1), &size, "");
      if (status != DB_TRUNCATED) {
         bm_compose_event(pevent, event_id, MIDAS_MAGIC,
                          buffer_size - sizeof(EVENT_HEADER) - size + 1, run_number);
         ybos_write(log_chn, pevent, pevent->data_size + sizeof(EVENT_HEADER));
         break;
      }
      /* increase buffer size if truncated */
      free(pevent);
      buffer_size *= 2;
   } while (1);
   free(pevent);
}
INT ybos_logfile_close (INT type, HNDLE handle)
Definition at line 1418 of file ybos.c.
References LOG_TYPE_DISK, LOG_TYPE_TAPE, SS_IO_ERROR, SS_NO_SPACE, SS_SUCCESS, ss_tape_close(), ss_tape_write_eof(), status, and YB_SUCCESS.
Referenced by ybos_log_close().
       : ybos_logfile_close
Purpose: close a logging channel for either type (Disk/Tape)
For the tape I'm writting just a EOF and expect the rewind command to
write another one if necessary. This way the run restart is faster.
Input:
INT type       : Disk, Tape
HNDLE * handle ; returned handle of the open device
Output:
none
Function value:
error, success
\********************************************************************/
{
   INT status;
   /* Write EOF if Tape */
   if (type == LOG_TYPE_TAPE) {
      /* writing EOF mark on tape only */
      status = ss_tape_write_eof(handle);
#ifdef OS_UNIX
      if (status != SS_SUCCESS) {
         if (errno == EIO)
            return SS_IO_ERROR;
         if (errno == ENOSPC)
            return SS_NO_SPACE;
         else
            return status;
      }
#endif
#ifdef OS_WINNT
      if (status != SS_SUCCESS) {
         if (errno == ERROR_END_OF_MEDIA)
            return SS_NO_SPACE;
         else
            return status;
      }
#endif
      ss_tape_close(handle);
   } else if (type == LOG_TYPE_DISK) {
#ifdef OS_WINNT
      CloseHandle((HANDLE) handle);
#else
      close(handle);
#endif
   }
   return YB_SUCCESS;
}
INT ybos_logfile_open (INT type, char * path, HNDLE * handle)
Definition at line 1126 of file ybos.c.
References LOG_TYPE_DISK, LOG_TYPE_TAPE, magta, O_BINARY, O_LARGEFILE, pbot, SS_FILE_ERROR, SS_SUCCESS, ss_tape_open(), status, yb_any_dev_os_write(), and YB_SUCCESS.
Referenced by yb_any_file_wopen(), and ybos_log_open().
       : ybos_logfile_open
Purpose: Open a YBOS logging channel for either type (Disk/Tape)
The device open is taken care here. But the writting is done
through yb_any_dev_os_write for ybos magta.
Input:
INT type       : Disk, Tape
char * path    : Device name
Output:
HNDLE * handle ; returned handle of the open device
none
Function value:
error, success
\********************************************************************/
{
#ifdef YBOS_VERSION_3_3
   INT status;
   DWORD written;
#endif
   /* Create device channel */
   if (type == LOG_TYPE_TAPE) {
    /*-PAA- Should check for the TAPE_BUFFER_SIZE set in ss_tape_open() */
      return ss_tape_open(path, O_WRONLY | O_CREAT | O_TRUNC, handle);
   } else if (type == LOG_TYPE_DISK) {
#ifdef OS_WINNT
      *handle =
          (int) CreateFile(path, GENERIC_WRITE, FILE_SHARE_READ, NULL,
                           CREATE_ALWAYS,
                           FILE_ATTRIBUTE_NORMAL | FILE_FLAG_WRITE_THROUGH
                           | FILE_FLAG_SEQUENTIAL_SCAN, 0);
#else
      *handle = open(path, O_WRONLY | O_CREAT | O_TRUNC | O_BINARY | O_LARGEFILE, 0644);
#endif
      if (*handle < 0)
         return SS_FILE_ERROR;
#ifdef YBOS_VERSION_3_3
      /* specific to YBOS Disk structure */
      /* write MAGTA header in bytes 0x4, "*BOT" */
      status = yb_any_dev_os_write(*handle, type, (char *) magta, 8, &written);
      if (status != SS_SUCCESS)
         return status;
      /* allocate temporary emtpy record */
      pbot = realloc(pbot, magta[2] - 4);
      memset((char *) pbot, 0, magta[2] - 4);
      /* write BOT empty record for MAGTA */
      status = yb_any_dev_os_write(*handle, type, (char *) pbot, magta[2] - 4, &written);
      if (status != SS_SUCCESS)
         return status;
#endif
   }
   return YB_SUCCESS;
}
INT ybos_physrec_get (DWORD ** prec, DWORD * readn)
Definition at line 2046 of file ybos.c.
References my, SS_SUCCESS, TRUE, yb_any_dev_os_read(), YB_DONE, and YB_SUCCESS.
Referenced by yb_any_physrec_get(), ybos_event_get(), and ybos_physrec_skip().
       : ybos_physrec_get
Purpose: read one physical YBOS record.
The number of bytes to be read is fixed under YBOS.
It is defined by my.size, In case of Disk file the magta
stuff has to be read/rejected first.
Input:
void ** precord     pointer to the record
DWORD * readn       record length in bytes
Output:
none
Function value:
YB_DONE            No more record to read
YB_SUCCESS         Ok
\********************************************************************/
{
   INT status;
#ifdef YBOS_VERSION_3_3
   if (my.magtafl) {
      /* skip 4 bytes from MAGTA header */
      if (!my.zipfile) {
         status = yb_any_dev_os_read(my.handle, my.type, my.pmagta, 4, readn);
         if (status != SS_SUCCESS)
            return (YB_DONE);
      } else {                  /* --------- GZIP ---------- */
#ifdef INCLUDE_ZLIB
         status = gzread(filegz, (char *) my.pmagta, 4);
         if (status <= 0)
            return (YB_DONE);
#endif
      }
   }
#endif
   /* read full YBOS physical record */
   if (!my.zipfile) {
      status = yb_any_dev_os_read(my.handle, my.type, my.pyh, my.size << 2, readn);
      if (status != SS_SUCCESS)
         return (YB_DONE);
   } else {
#ifdef INCLUDE_ZLIB
      status = gzread(filegz, (char *) my.pyh, my.size << 2);
      if (status <= 0)
         return (YB_DONE);
#endif
   }
#ifdef YBOS_VERSION_3_3
   /* check if header make sense for MAGTA there is extra stuff to get rid off */
   if ((!my.magtafl) && (*((DWORD *) my.pyh) == 0x00000004)) {
      /* set MAGTA flag */
      my.magtafl = TRUE;
      /* BOT of MAGTA skip record */
      if (!my.zipfile) {
         status = yb_any_dev_os_read(my.handle, my.type, my.pmagta, 8, readn);
         if (status != SS_SUCCESS)
            return (YB_DONE);
      } else {
#ifdef INCLUDE_ZLIB
         status = gzread(filegz, (char *) my.pmagta, 8);
         if (status <= 0)
            return (YB_DONE);
#endif
      }
      /* read full YBOS physical record */
      if (!my.zipfile) {
         status = yb_any_dev_os_read(my.handle, my.type, my.pyh, my.size << 2, readn);
         if (status != SS_SUCCESS)
            return (YB_DONE);
      } else {
#ifdef INCLUDE_ZLIB
         status = gzread(filegz, (char *) my.pyh, my.size << 2);
         if (status <= 0)
            return (YB_DONE);
#endif
      }
   }
#endif
   /* move current ptr of newly phys rec to first event */
   if ((my.pyh)->offset == 0) {
      /* no new event ==> full phys rec is continuation of the previous event
         leave pointer to continuation */
      my.pyrd = (DWORD *) my.pyh + (my.pyh)->offset;
   } else {
      /* new event in physical record
         leave pointer to plrl */
      my.pyrd = (DWORD *) my.pyh + (my.pyh)->offset;
   }
   /* count blocks */
   my.recn++;
   *precord = (DWORD *) (my.pyh);
   return (YB_SUCCESS);
}
INT ybos_physrec_skip (INT bl)
Definition at line 2255 of file ybos.c.
References my, size, YB_DONE, YB_SUCCESS, and ybos_physrec_get().
Referenced by yb_any_physrec_skip().
       : ybos_physrec_skip
Purpose: skip physical record on a YBOS file.
The physical record size is fixed (see ybos.h)
Input:
INT     bl            physical record number. (start at 0)
if bl = -1 : skip skiping
Output:
none
Function value:
YB_SUCCESS        Ok
\********************************************************************/
{
   INT status;
   DWORD *prec, size;
   if (bl == -1) {
      if ((status = ybos_physrec_get(&prec, &size)) == YB_SUCCESS)
         return status;
   }
   while (ybos_physrec_get(&prec, &size) == YB_SUCCESS) {
      if ((INT) (my.pyh)->rec_num != bl) {
         printf("Skipping physical record_# ... ");
         printf("%ld \r", (my.pyh)->rec_num);
         fflush(stdout);
      } else {
         printf("\n");
         return YB_SUCCESS;
      }
   }
   return YB_DONE;
}
Variable Documentation
DWORD { ... } evtlen [inherited]
Definition at line 372 of file ybos.c.
DWORD { ... } evtn [inherited]
Definition at line 370 of file ybos.c.
struct stat* filestat
Definition at line 349 of file ybos.c.
Referenced by yb_file_fragment().
INT { ... } fmt [inherited]
Definition at line 375 of file ybos.c.
INT { ... } handle [inherited]
Definition at line 357 of file ybos.c.
DWORD magta[3] = { 0x00000004, 0x544f422a, 0x00007ff8 }
Definition at line 345 of file ybos.c.
Referenced by yb_any_log_write(), and ybos_logfile_open().
BOOL { ... } magtafl [inherited]
Definition at line 379 of file ybos.c.
struct { ... } my
Referenced by midas_event_get(), midas_event_skip(), midas_physrec_get(), yb_any_all_info_display(), yb_any_file_rclose(), yb_any_file_ropen(), yb_any_physrec_display(), yb_any_physrec_get(), ybos_event_get(), ybos_physrec_get(), and ybos_physrec_skip().
char { ... } name[MAX_FILE_PATH] [inherited]
Definition at line 358 of file ybos.c.
DWORD * pbktop = NULL
Definition at line 343 of file ybos.c.
Referenced by ybos_write().
DWORD* pbot
Definition at line 343 of file ybos.c.
Referenced by ybos_logfile_open().
char* { ... } pmagta [inherited]
Definition at line 365 of file ybos.c.
EVENT_HEADER* { ... } pme [inherited]
Definition at line 362 of file ybos.c.
EVENT_HEADER* { ... } pmh [inherited]
Definition at line 361 of file ybos.c.
char* { ... } pmp [inherited]
Definition at line 360 of file ybos.c.
char* { ... } pmrd [inherited]
Definition at line 363 of file ybos.c.
char* ptopmrd
Definition at line 344 of file ybos.c.
Referenced by yb_any_file_ropen().
YBOS_PHYSREC_HEADER* { ... } pyh [inherited]
Definition at line 366 of file ybos.c.
DWORD* { ... } pylrl [inherited]
Definition at line 367 of file ybos.c.
DWORD* { ... } pyrd [inherited]
Definition at line 368 of file ybos.c.
DWORD { ... } recn [inherited]
Definition at line 374 of file ybos.c.
DWORD { ... } runn [inherited]
Definition at line 377 of file ybos.c.
DWORD { ... } serial [inherited]
Definition at line 371 of file ybos.c.
DWORD { ... } size [inherited]
Definition at line 373 of file ybos.c.
INT { ... } type [inherited]
Definition at line 376 of file ybos.c.
INT yb_tid_size[]
Initial value:
 {
   0,
   2,
   1,
   4,
   4,
   8,
   0,
   0,
   1,
}
Definition at line 279 of file ybos.c.
Referenced by ybos_get_tid_size().
R_YM_FILE ymfile[MAX_YM_FILE]
Definition at line 348 of file ybos.c.
BOOL { ... } zipfile [inherited]
Definition at line 378 of file ybos.c.