AlcapDAQ:Rootana: Midas Buffer Manager Functions (bm_xxx)
Midas Buffer Manager Functions (bm_xxx)
[The midas.h & midas.c]
Data Structures
struct EVENT_DEFRAG_BUFFER
Defines
#define MAX_DEFRAG_EVENTS 10
Functions
INT bm_match_event (short int event_id, short int trigger_mask, EVENT_HEADER *pevent)
INT bm_open_buffer (char *buffer_name, INT buffer_size, INT *buffer_handle)
INT bm_close_buffer (INT buffer_handle)
INT bm_close_all_buffers (void)
INT bm_set_cache_size (INT buffer_handle, INT read_size, INT write_size)
INT bm_compose_event (EVENT_HEADER *event_header, short int event_id, short int trigger_mask, DWORD size, DWORD serial)
INT bm_add_event_request (INT buffer_handle, short int event_id, short int trigger_mask, INT sampling_type, void(*func)(HNDLE, HNDLE, EVENT_HEADER *, void *), INT request_id)
INT bm_request_event (HNDLE buffer_handle, short int event_id, short int trigger_mask, INT sampling_type, HNDLE *request_id, void(*func)(HNDLE, HNDLE, EVENT_HEADER *, void *))
INT bm_remove_event_request (INT buffer_handle, INT request_id)
INT bm_delete_request (INT request_id)
INT bm_send_event (INT buffer_handle, void *source, INT buf_size, INT async_flag)
INT bm_flush_cache (INT buffer_handle, INT async_flag)
INT bm_receive_event (INT buffer_handle, void *destination, INT *buf_size, INT async_flag)
INT bm_skip_event (INT buffer_handle)
INT bm_push_event (char *buffer_name)
INT bm_check_buffers ()
INT bm_mark_read_waiting (BOOL flag)
INT bm_notify_client (char *buffer_name, int socket)
INT bm_poll_event (INT flag)
INT bm_empty_buffers ()
void bm_defragment_event (HNDLE buffer_handle, HNDLE request_id, EVENT_HEADER *pevent, void *pdata, void(*dispatcher)(HNDLE, HNDLE, EVENT_HEADER *, void *))
Variables
EVENT_DEFRAG_BUFFER defrag_buffer [MAX_DEFRAG_EVENTS]
Detailed Description
dox dox dox
Define Documentation
#define MAX_DEFRAG_EVENTS 10
dox
Definition at line 7798 of file midas.c.
Referenced by bm_defragment_event().
Function Documentation
INT bm_add_event_request (INT buffer_handle, short int event_id, short int trigger_mask, INT sampling_type, void(*)(HNDLE, HNDLE, EVENT_HEADER *, void *) func, INT request_id)
dox
Definition at line 5703 of file midas.c.
References _buffer_entries, BUFFER_CLIENT::all_flag, BM_INVALID_HANDLE, BM_INVALID_MIXING, bm_lock_buffer(), BM_NO_MEMORY, BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER::callback, callback, BUFFER::client_index, cm_msg, EVENT_REQUEST::dispatch, EVENT_REQUEST::event_id, BUFFER_CLIENT::event_request, GET_ALL, i, EVENT_REQUEST::id, MAX_EVENT_REQUESTS, BUFFER_CLIENT::max_request_index, MERROR, RPC_BM_ADD_EVENT_REQUEST, rpc_call(), rpc_is_remote(), EVENT_REQUEST::sampling_type, EVENT_REQUEST::trigger_mask, TRUE, and EVENT_REQUEST::valid.
Referenced by bm_request_event(), and rpc_server_dispatch().
         :  bm_add_event_request
  Purpose:  Place a request for a specific event type in the client
            structure of the buffer refereced by buffer_handle.
  Input:
    INT          buffer_handle  Handle to the buffer where the re-
                                quest should be placed in
    short int    event_id       Event ID      \
    short int    trigger_mask   Trigger mask  / Event specification
    INT          sampling_type  One of GET_ALL, GET_SOME or GET_FARM
                 Note: to request all types of events, use
                   event_id = 0 (all others should be !=0 !)
                   trigger_mask = TRIGGER_ALL
                   sampling_typ = GET_ALL
    void         *func          Callback function
    INT          request_id     Request id (unique number assigned
                                by bm_request_event)
  Output:
    none
  Function value:
    BM_SUCCESS              Successful completion
    BM_NO_MEMORY            Too much request. MAX_EVENT_REQUESTS in
                            MIDAS.H should be increased.
    BM_INVALID_HANDLE       Buffer handle is invalid
    RPC_NET_ERROR           Network error
\********************************************************************/
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_ADD_EVENT_REQUEST, buffer_handle, event_id,
                      trigger_mask, sampling_type, (INT) func, request_id);
#ifdef LOCAL_ROUTINES
   {
      INT i;
      BUFFER_CLIENT *pclient;
      if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
         cm_msg(MERROR, "bm_add_event_request", "invalid buffer handle %d",
                buffer_handle);
         return BM_INVALID_HANDLE;
      }
      if (!_buffer[buffer_handle - 1].attached) {
         cm_msg(MERROR, "bm_add_event_request", "invalid buffer handle %d",
                buffer_handle);
         return BM_INVALID_HANDLE;
      }
      /* avoid callback/non callback requests */
      if (func == NULL && _buffer[buffer_handle - 1].callback) {
         cm_msg(MERROR, "bm_add_event_request",
                "mixing callback/non callback requests not possible");
         return BM_INVALID_MIXING;
      }
      /* get a pointer to the proper client structure */
      pclient = &(_buffer[buffer_handle - 1].buffer_header->
                  client[_buffer[buffer_handle - 1].client_index]);
      /* lock buffer */
      bm_lock_buffer(buffer_handle);
      /* look for a empty request entry */
      for (i = 0; i < MAX_EVENT_REQUESTS; i++)
         if (!pclient->event_request[i].valid)
            break;
      if (i == MAX_EVENT_REQUESTS) {
         bm_unlock_buffer(buffer_handle);
         return BM_NO_MEMORY;
      }
      /* setup event_request structure */
      pclient->event_request[i].id = request_id;
      pclient->event_request[i].valid = TRUE;
      pclient->event_request[i].event_id = event_id;
      pclient->event_request[i].trigger_mask = trigger_mask;
      pclient->event_request[i].sampling_type = sampling_type;
      pclient->event_request[i].dispatch = func;
      pclient->all_flag = pclient->all_flag || (sampling_type & GET_ALL);
      /* set callback flag in buffer structure */
      if (func != NULL)
         _buffer[buffer_handle - 1].callback = TRUE;
      /*
         Save the index of the last request in the list so that later only the
         requests 0..max_request_index-1 have to be searched through.
       */
      if (i + 1 > pclient->max_request_index)
         pclient->max_request_index = i + 1;
      bm_unlock_buffer(buffer_handle);
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_check_buffers (void)
Check if any requested event is waiting in a buffer
Returns:
TRUE More events are waiting
FALSE No more events are waiting
Definition at line 7429 of file midas.c.
References _buffer_entries, BM_MORE_EVENTS, bm_push_event(), FALSE, index, rpc_get_server_acception(), rpc_get_server_option(), RPC_OSERVER_TYPE, ss_gettid(), ss_millitime(), ST_MTHREAD, ST_SINGLE, ST_SUBPROCESS, start_time, status, and TRUE.
Referenced by cm_yield().
{
#ifdef LOCAL_ROUTINES
   {
      INT index, status = 0;
      INT server_type, server_conn, tid;
      BOOL bMore;
      DWORD start_time;
      server_type = rpc_get_server_option(RPC_OSERVER_TYPE);
      server_conn = rpc_get_server_acception();
      tid = ss_gettid();
      /* if running as a server, buffer checking is done by client
         via ASYNC bm_receive_event */
      if (server_type == ST_SUBPROCESS || server_type == ST_MTHREAD)
         return FALSE;
      bMore = FALSE;
      start_time = ss_millitime();
      /* go through all buffers */
      for (index = 0; index < _buffer_entries; index++) {
         if (server_type == ST_SINGLE && _buffer[index].index != server_conn)
            continue;
         if (server_type != ST_SINGLE && _buffer[index].index != tid)
            continue;
         if (!_buffer[index].attached)
            continue;
         do {
            /* one bm_push_event could cause a run stop and a buffer close, which
               would crash the next call to bm_push_event(). So check for valid
               buffer on each call */
            if (index < _buffer_entries && _buffer[index].buffer_header->name != NULL)
               status = bm_push_event(_buffer[index].buffer_header->name);
            if (status != BM_MORE_EVENTS)
               break;
            /* stop after one second */
            if (ss_millitime() - start_time > 1000) {
               bMore = TRUE;
               break;
            }
         } while (TRUE);
      }
      return bMore;
   }
#else                           /* LOCAL_ROUTINES */
   return FALSE;
#endif
}
INT bm_close_all_buffers (void)
Close all open buffers
Returns:
BM_SUCCESS
Definition at line 4722 of file midas.c.
References _buffer_entries, bm_close_buffer(), BM_SUCCESS, i, RPC_BM_CLOSE_ALL_BUFFERS, rpc_call(), and rpc_is_remote().
Referenced by cm_disconnect_experiment(), cm_set_client_info(), rpc_server_dispatch(), and rpc_server_receive().
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_CLOSE_ALL_BUFFERS);
#ifdef LOCAL_ROUTINES
   {
      INT i;
      for (i = _buffer_entries; i > 0; i--)
         bm_close_buffer(i);
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_close_buffer (INT buffer_handle)
Closes an event buffer previously opened with bm_open_buffer().
Parameters:
buffer_handle buffer handle
Returns:
BM_SUCCESS, BM_INVALID_HANDLE
Definition at line 4611 of file midas.c.
References _buffer_entries, _request_list_entries, BUFFER::attached, bm_delete_request(), BM_INVALID_HANDLE, bm_lock_buffer(), BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER_HEADER::client, BUFFER::client_index, cm_msg, FALSE, i, index, j, M_FREE, BUFFER_HEADER::max_client_index, MAX_CLIENTS, MERROR, BUFFER_HEADER::name, BUFFER_HEADER::num_clients, BUFFER_CLIENT::pid, BUFFER_CLIENT::port, BUFFER_CLIENT::read_wait, RPC_BM_CLOSE_BUFFER, rpc_call(), rpc_get_server_acception(), rpc_get_server_option(), rpc_is_remote(), RPC_OSERVER_TYPE, BUFFER::shm_handle, ss_gettid(), ss_mutex_delete(), ss_resume(), ss_shm_close(), ST_SINGLE, and BUFFER_CLIENT::write_wait.
Referenced by bm_close_all_buffers(), command_loop(), rpc_server_dispatch(), source_unbooking(), tr_poststop(), and tr_stop().
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_CLOSE_BUFFER, buffer_handle);
#ifdef LOCAL_ROUTINES
   {
      BUFFER_CLIENT *pclient;
      BUFFER_HEADER *pheader;
      INT i, j, index, destroy_flag;
      if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
         cm_msg(MERROR, "bm_close_buffer", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      /*
         Check if buffer was opened by current thread. This is necessary
         in the server process where one thread may not close the buffer
         of other threads.
       */
      index = _buffer[buffer_handle - 1].client_index;
      pheader = _buffer[buffer_handle - 1].buffer_header;
      if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_SINGLE &&
          _buffer[buffer_handle - 1].index != rpc_get_server_acception())
         return BM_INVALID_HANDLE;
      if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_SINGLE &&
          _buffer[buffer_handle - 1].index != ss_gettid())
         return BM_INVALID_HANDLE;
      if (!_buffer[buffer_handle - 1].attached) {
         /* don't produce error, since bm_close_all_buffers() might want to close an
            already closed buffer */
         return BM_SUCCESS;
      }
      /* delete all requests for this buffer */
      for (i = 0; i < _request_list_entries; i++)
         if (_request_list[i].buffer_handle == buffer_handle)
            bm_delete_request(i);
      /* first lock buffer */
      bm_lock_buffer(buffer_handle);
      /* mark entry in _buffer as empty */
      _buffer[buffer_handle - 1].attached = FALSE;
      /* clear entry from client structure in buffer header */
      memset(&(pheader->client[index]), 0, sizeof(BUFFER_CLIENT));
      /* calculate new max_client_index entry */
      for (i = MAX_CLIENTS - 1; i >= 0; i--)
         if (pheader->client[i].pid != 0)
            break;
      pheader->max_client_index = i + 1;
      /* count new number of clients */
      for (i = MAX_CLIENTS - 1, j = 0; i >= 0; i--)
         if (pheader->client[i].pid != 0)
            j++;
      pheader->num_clients = j;
      destroy_flag = (pheader->num_clients == 0);
      /* free cache */
      if (_buffer[buffer_handle - 1].read_cache_size > 0)
         M_FREE(_buffer[buffer_handle - 1].read_cache);
      if (_buffer[buffer_handle - 1].write_cache_size > 0)
         M_FREE(_buffer[buffer_handle - 1].write_cache);
      /* check if anyone is waiting and wake him up */
      pclient = pheader->client;
      for (i = 0; i < pheader->max_client_index; i++, pclient++)
         if (pclient->pid && (pclient->write_wait || pclient->read_wait))
            ss_resume(pclient->port, "B  ");
      /* unmap shared memory, delete it if we are the last */
      ss_shm_close(pheader->name, _buffer[buffer_handle - 1].buffer_header,
                   _buffer[buffer_handle - 1].shm_handle, destroy_flag);
      /* unlock buffer */
      bm_unlock_buffer(buffer_handle);
      /* delete mutex */
      ss_mutex_delete(_buffer[buffer_handle - 1].mutex, destroy_flag);
      /* update _buffer_entries */
      if (buffer_handle == _buffer_entries)
         _buffer_entries--;
      if (_buffer_entries > 0)
         _buffer = (BUFFER *) realloc(_buffer, sizeof(BUFFER) * (_buffer_entries));
      else {
         M_FREE(_buffer);
         _buffer = NULL;
      }
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_compose_event (EVENT_HEADER * event_header, short int event_id, short int trigger_mask, DWORD size, DWORD serial)
Compose a Midas event header. An event header can usually be set-up manually or through this routine. If the data size of the event is not known when the header is composed, it can be set later with event_header->data-size = <...> Following structure is created at the beginning of an event
typedef struct {
 short int     event_id;
 short int     trigger_mask;
 DWORD         serial_number;
 DWORD         time_stamp;
 DWORD         data_size;
} EVENT_HEADER;
char event[1000];
 bm_compose_event((EVENT_HEADER *)event, 1, 0, 100, 1);
 *(event+sizeof(EVENT_HEADER)) = <...>
Parameters:
event_header pointer to the event header
event_id event ID of the event
trigger_mask trigger mask of the event
size size if the data part of the event in bytes
serial serial number
Returns:
BM_SUCCESS
Definition at line 5686 of file midas.c.
References BM_SUCCESS, EVENT_HEADER::data_size, EVENT_HEADER::event_id, EVENT_HEADER::serial_number, ss_time(), EVENT_HEADER::time_stamp, and EVENT_HEADER::trigger_mask.
Referenced by cm_msg(), cm_msg1(), log_odb_dump(), main(), rpc_end_of_cycle(), source_scan(), yb_file_fragment(), and ybos_log_dump().
{
   event_header->event_id = event_id;
   event_header->trigger_mask = trigger_mask;
   event_header->data_size = size;
   event_header->time_stamp = ss_time();
   event_header->serial_number = serial;
   return BM_SUCCESS;
}
void bm_defragment_event (HNDLE buffer_handle, HNDLE request_id, EVENT_HEADER * pevent, void * pdata, void(*)(HNDLE, HNDLE, EVENT_HEADER *, void *) dispatcher)
Definition at line 7810 of file midas.c.
References cm_msg, data_size, EVENT_DEFRAG_BUFFER::data_size, EVENT_HEADER::data_size, EVENT_DEFRAG_BUFFER::event_id, EVENT_HEADER::event_id, EVENTID_FRAG1, i, MAX_DEFRAG_EVENTS, MERROR, EVENT_DEFRAG_BUFFER::pevent, and EVENT_DEFRAG_BUFFER::received.
Referenced by bm_poll_event(), and bm_push_event().
         : bm_defragment_event
  Purpose: Called internally from the event receiving routines
           bm_push_event and bm_poll_event to recombine event
           fragments and call the user callback routine upon
           completion.
  Input:
    HNDLE buffer_handle  Handle for the buffer containing event
    HNDLE request_id     Handle for event request
    EVENT_HEADER *pevent Pointer to event header
    void *pata           Pointer to event data
    dispatcher()         User callback routine
  Output:
    <calls dispatcher() after successfull recombination of event>
  Function value:
    void
\********************************************************************/
{
   INT i;
   if ((pevent->event_id & 0xF000) == EVENTID_FRAG1) {
    /*---- start new event ----*/
      /* check if fragments already stored */
      for (i = 0; i < MAX_DEFRAG_EVENTS; i++)
         if (defrag_buffer[i].event_id == (pevent->event_id & 0x0FFF))
            break;
      if (i < MAX_DEFRAG_EVENTS) {
         free(defrag_buffer[i].pevent);
         memset(&defrag_buffer[i].event_id, 0, sizeof(EVENT_DEFRAG_BUFFER));
         cm_msg(MERROR, "bm_defragement_event",
                "Received new event with ID %d while old fragments were not completed",
                (pevent->event_id & 0x0FFF));
      }
      /* search new slot */
      for (i = 0; i < MAX_DEFRAG_EVENTS; i++)
         if (defrag_buffer[i].event_id == 0)
            break;
      if (i == MAX_DEFRAG_EVENTS) {
         cm_msg(MERROR, "bm_defragment_evnet",
                "Not eough defragment buffers, please increase MAX_DEFRAG_EVENTS and recompile");
         return;
      }
      /* check event size */
      if (pevent->data_size != sizeof(DWORD)) {
         cm_msg(MERROR, "bm_defragment_evnet",
                "Received first event fragment with %s bytes instead of %d bytes, event ignored",
                pevent->data_size, sizeof(DWORD));
         return;
      }
      /* setup defragment buffer */
      defrag_buffer[i].event_id = (pevent->event_id & 0x0FFF);
      defrag_buffer[i].data_size = *(DWORD *) pdata;
      defrag_buffer[i].received = 0;
      defrag_buffer[i].pevent =
          (EVENT_HEADER *) malloc(sizeof(EVENT_HEADER) + defrag_buffer[i].data_size);
      if (defrag_buffer[i].pevent == NULL) {
         memset(&defrag_buffer[i].event_id, 0, sizeof(EVENT_DEFRAG_BUFFER));
         cm_msg(MERROR, "bm_defragement_event",
                "Not enough memory to allocate event defragment buffer");
         return;
      }
      memcpy(defrag_buffer[i].pevent, pevent, sizeof(EVENT_HEADER));
      defrag_buffer[i].pevent->event_id = defrag_buffer[i].event_id;
      defrag_buffer[i].pevent->data_size = defrag_buffer[i].data_size;
      return;
   }
   /* search buffer for that event */
   for (i = 0; i < MAX_DEFRAG_EVENTS; i++)
      if (defrag_buffer[i].event_id == (pevent->event_id & 0xFFF))
         break;
   if (i == MAX_DEFRAG_EVENTS) {
      /* no buffer available -> no first fragment received */
      free(defrag_buffer[i].pevent);
      memset(&defrag_buffer[i].event_id, 0, sizeof(EVENT_DEFRAG_BUFFER));
      cm_msg(MERROR, "bm_defragement_event",
             "Received fragment with no first fragment (ID %d)",
             pevent->event_id & 0x0FFF);
      return;
   }
   /* add fragment to buffer */
   if (pevent->data_size + defrag_buffer[i].received > defrag_buffer[i].data_size) {
      free(defrag_buffer[i].pevent);
      memset(&defrag_buffer[i].event_id, 0, sizeof(EVENT_DEFRAG_BUFFER));
      cm_msg(MERROR, "bm_defragement_event",
             "Received fragments with more data (%d) than event size (%d)",
             pevent->data_size + defrag_buffer[i].received, defrag_buffer[i].data_size);
      return;
   }
   memcpy(((char *) defrag_buffer[i].pevent) + sizeof(EVENT_HEADER) +
          defrag_buffer[i].received, pdata, pevent->data_size);
   defrag_buffer[i].received += pevent->data_size;
   if (defrag_buffer[i].received == defrag_buffer[i].data_size) {
      /* event complete */
      dispatcher(buffer_handle, request_id, defrag_buffer[i].pevent,
                 defrag_buffer[i].pevent + 1);
      free(defrag_buffer[i].pevent);
      memset(&defrag_buffer[i].event_id, 0, sizeof(EVENT_DEFRAG_BUFFER));
   }
}
INT bm_delete_request (INT request_id)
Deletes an event request previously done with bm_request_event(). When an event request gets deleted, events of that requested type are not received any more. When a buffer is closed via bm_close_buffer(), all event requests from that buffer are deleted automatically
Parameters:
request_id request identifier given by bm_request_event()
Returns:
BM_SUCCESS, BM_INVALID_HANDLE
Definition at line 5993 of file midas.c.
References _request_list_entries, BM_INVALID_HANDLE, bm_remove_event_request(), and BM_SUCCESS.
Referenced by bm_close_buffer(), source_unbooking(), tr_poststop(), tr_stop(), and update_request().
{
   if (request_id < 0 || request_id >= _request_list_entries)
      return BM_INVALID_HANDLE;
   /* remove request entry from buffer */
   bm_remove_event_request(_request_list[request_id].buffer_handle, request_id);
   memset(&_request_list[request_id], 0, sizeof(REQUEST_LIST));
   return BM_SUCCESS;
}
INT bm_empty_buffers (void)
dox Clears event buffer and cache. If an event buffer is large and a consumer is slow in analyzing events, events are usually received some time after they are produced. This effect is even more experienced if a read cache is used (via bm_set_cache_size()). When changes to the hardware are made in the experience, the consumer will then still analyze old events before any new event which reflects the hardware change. Users can be fooled by looking at histograms which reflect the hardware change many seconds after they have been made.
To overcome this potential problem, the analyzer can call bm_empty_buffers() just after the hardware change has been made which skips all old events contained in event buffers and read caches. Technically this is done by forwarding the read pointer of the client. No events are really deleted, they are still visible to other clients like the logger.
Note that the front-end also contains write buffers which can delay the delivery of events. The standard front-end framework mfe.c reduces this effect by flushing all buffers once every second.
Returns:
BM_SUCCESS
Definition at line 7751 of file midas.c.
References _buffer_entries, bm_lock_buffer(), BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER::client_index, index, BUFFER::read_cache_rp, BUFFER::read_cache_wp, BUFFER_CLIENT::read_pointer, RPC_BM_EMPTY_BUFFERS, rpc_call(), rpc_get_server_acception(), rpc_get_server_option(), rpc_is_remote(), RPC_OSERVER_TYPE, ss_gettid(), and ST_SINGLE.
Referenced by handFlush(), rpc_server_dispatch(), source_booking(), and source_unbooking().
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_EMPTY_BUFFERS);
#ifdef LOCAL_ROUTINES
   {
      INT index, server_type, server_conn, tid;
      BUFFER *pbuf;
      BUFFER_CLIENT *pclient;
      server_type = rpc_get_server_option(RPC_OSERVER_TYPE);
      server_conn = rpc_get_server_acception();
      tid = ss_gettid();
      /* go through all buffers */
      for (index = 0; index < _buffer_entries; index++) {
         if (server_type == ST_SINGLE && _buffer[index].index != server_conn)
            continue;
         if (server_type != ST_SINGLE && _buffer[index].index != tid)
            continue;
         if (!_buffer[index].attached)
            continue;
         pbuf = &_buffer[index];
         /* empty cache */
         pbuf->read_cache_rp = pbuf->read_cache_wp = 0;
         /* set read pointer to write pointer */
         pclient = (pbuf->buffer_header)->client + pbuf->client_index;
         bm_lock_buffer(index + 1);
         pclient->read_pointer = (pbuf->buffer_header)->write_pointer;
         bm_unlock_buffer(index + 1);
      }
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_flush_cache (INT buffer_handle, INT async_flag)
Empty write cache. This function should be used if events in the write cache should be visible to the consumers immediately. It should be called at the end of each run, otherwise events could be kept in the write buffer and will flow to the data of the next run.
Parameters:
buffer_handle Buffer handle obtained via bm_open_buffer()
async_flag Synchronous/asynchronous flag. If FALSE, the function blocks if the buffer has not enough free space to receive the full cache. If TRUE, the function returns immediately with a value of BM_ASYNC_RETURN without writing the cache.
Returns:
BM_SUCCESS, BM_INVALID_HANDLE
BM_ASYNC_RETURN Routine called with async_flag == TRUE and buffer has not enough space to receive cache
BM_NO_MEMORY Event is too large for network buffer or event buffer. One has to increase MAX_EVENT_SIZE or EVENT_BUFFER_SIZE in midas.h and recompile.
Definition at line 6412 of file midas.c.
References _buffer_entries, ALIGN8, BUFFER::attached, BM_ASYNC_RETURN, BM_INVALID_HANDLE, bm_lock_buffer(), bm_match_event(), BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER_HEADER::client, BUFFER::client_index, cm_msg, EVENT_HEADER::data_size, EVENT_REQUEST::event_id, BUFFER_CLIENT::event_request, FALSE, GET_ALL, i, EVENT_REQUEST::id, if, increment, j, BUFFER_HEADER::max_client_index, BUFFER_CLIENT::max_request_index, MDEBUG, MERROR, MSG_BM, BUFFER_HEADER::name, BUFFER_HEADER::num_in_events, BUFFER_CLIENT::pid, BUFFER_CLIENT::port, BUFFER_CLIENT::read_pointer, BUFFER_HEADER::read_pointer, BUFFER_CLIENT::read_wait, RPC_BM_FLUSH_CACHE, rpc_call(), rpc_is_remote(), EVENT_REQUEST::sampling_type, BUFFER_HEADER::size, size, SS_ABORT, ss_resume(), ss_suspend(), status, EVENT_REQUEST::trigger_mask, TRUE, EVENT_REQUEST::valid, BUFFER::write_cache, BUFFER::write_cache_rp, BUFFER::write_cache_size, BUFFER::write_cache_wp, BUFFER_HEADER::write_pointer, and BUFFER_CLIENT::write_wait.
Referenced by bm_send_event(), close_buffers(), dm_buffer_send(), main(), rpc_end_of_cycle(), rpc_server_dispatch(), scan_fragment(), scheduler(), send_event(), tr_prestop(), and tr_stop().
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_FLUSH_CACHE, buffer_handle, async_flag);
#ifdef LOCAL_ROUTINES
   {
      BUFFER *pbuf;
      BUFFER_HEADER *pheader;
      BUFFER_CLIENT *pclient, *pc;
      EVENT_REQUEST *prequest;
      EVENT_HEADER *pevent, *pevent_test;
      INT i, j, min_wp, size, total_size, status;
      INT increment;
      INT my_client_index;
      INT old_write_pointer;
      INT old_read_pointer, new_read_pointer;
      char *pdata;
      BOOL blocking;
      INT n_blocking;
      INT request_id;
      char str[80];
      pbuf = &_buffer[buffer_handle - 1];
      if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
         cm_msg(MERROR, "bm_flush_cache", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      if (!pbuf->attached) {
         cm_msg(MERROR, "bm_flush_cache", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      if (pbuf->write_cache_size == 0)
         return BM_SUCCESS;
      /* check if anything needs to be flushed */
      if (pbuf->write_cache_rp == pbuf->write_cache_wp)
         return BM_SUCCESS;
      /* calculate some shorthands */
      pheader = _buffer[buffer_handle - 1].buffer_header;
      pdata = (char *) (pheader + 1);
      my_client_index = _buffer[buffer_handle - 1].client_index;
      pclient = pheader->client;
      pevent = (EVENT_HEADER *) (pbuf->write_cache + pbuf->write_cache_rp);
      /* lock the buffer */
      bm_lock_buffer(buffer_handle);
#ifdef DEBUG_MSG
      cm_msg(MDEBUG, "bm_flush_cache initial: rp=%d, wp=%d", pheader->read_pointer,
             pheader->write_pointer);
#endif
      /* check if enough space in buffer left */
      do {
         size = pheader->read_pointer - pheader->write_pointer;
         if (size <= 0)
            size += pheader->size;
         if (size <= pbuf->write_cache_wp) {
            /* if not enough space, find out who's blocking */
            n_blocking = 0;
            for (i = 0, pc = pclient; i < pheader->max_client_index; i++, pc++)
               if (pc->pid) {
                  if (pc->read_pointer == pheader->read_pointer) {
                     /*
                        First assume that the client with the "minimum" read pointer
                        is not really blocking due to a GET_ALL request.
                      */
                     blocking = FALSE;
                     request_id = -1;
                     /* check if this request blocks. */
                     prequest = pc->event_request;
                     pevent_test = (EVENT_HEADER *) (pdata + pc->read_pointer);
                     for (j = 0; j < pc->max_request_index; j++, prequest++)
                        if (prequest->valid &&
                            bm_match_event(prequest->event_id, prequest->trigger_mask,
                                           pevent_test)) {
                           request_id = prequest->id;
                           if (prequest->sampling_type & GET_ALL) {
                              blocking = TRUE;
                              break;
                           }
                        }
                     if (!blocking) {
                        /*
                           The blocking guy has no GET_ALL request for this event
                           -> shift its read pointer.
                         */
                        old_read_pointer = pc->read_pointer;
                        increment = sizeof(EVENT_HEADER) +
                            ((EVENT_HEADER *) (pdata + pc->read_pointer))->data_size;
                        /* correct increment for DWORD boundary */
                        increment = ALIGN8(increment);
                        new_read_pointer = (pc->read_pointer + increment) % pheader->size;
                        if (new_read_pointer > pheader->size - (int) sizeof(EVENT_HEADER))
                           new_read_pointer = 0;
#ifdef DEBUG_MSG
                        cm_msg(MDEBUG, "bm_flush_cache: shift client %d rp=%d -> =%d", i,
                               pc->read_pointer, new_read_pointer);
#endif
                        pc->read_pointer = new_read_pointer;
                     } else {
                        n_blocking++;
                     }
                     /* wake that client if it has a request */
                     if (pc->read_wait && request_id != -1) {
#ifdef DEBUG_MSG
                        cm_msg(MDEBUG, "Send wake: rp=%d, wp=%d",
                               pheader->read_pointer, pheader->write_pointer);
#endif
                        sprintf(str, "B %s %d", pheader->name, request_id);
                        ss_resume(pc->port, str);
                     }
                  }             /* read_pointer blocks */
               }
            /* client loop */
            if (n_blocking > 0) {
               /* at least one client is blocking */
               bm_unlock_buffer(buffer_handle);
               /* return now in ASYNC mode */
               if (async_flag)
                  return BM_ASYNC_RETURN;
#ifdef DEBUG_MSG
               cm_msg(MDEBUG, "Send sleep: rp=%d, wp=%d, level=%1.1lf",
                      pheader->read_pointer,
                      pheader->write_pointer, 100 - 100.0 * size / pheader->size);
#endif
               /* has the read pointer moved in between ? */
               size = pheader->read_pointer - pheader->write_pointer;
               if (size <= 0)
                  size += pheader->size;
               /* suspend process */
               if (size <= pbuf->write_cache_wp) {
                  /* signal other clients wait mode */
                  pclient[my_client_index].write_wait = pbuf->write_cache_wp;
                  status = ss_suspend(1000, MSG_BM);
                  pclient[my_client_index].write_wait = 0;
                  /* return if TCP connection broken */
                  if (status == SS_ABORT)
                     return SS_ABORT;
               }
#ifdef DEBUG_MSG
               cm_msg(MDEBUG, "Send woke up: rp=%d, wp=%d, level=%1.1lf",
                      pheader->read_pointer,
                      pheader->write_pointer, 100 - 100.0 * size / pheader->size);
#endif
               bm_lock_buffer(buffer_handle);
               /* has the write pointer moved in between ? */
               size = pheader->read_pointer - pheader->write_pointer;
               if (size <= 0)
                  size += pheader->size;
            } else {
               /*
                  calculate new global read pointer as "minimum" of
                  client read pointers
                */
               min_wp = pheader->write_pointer;
               for (i = 0, pc = pclient; i < pheader->max_client_index; i++, pc++)
                  if (pc->pid) {
                     if (pc->read_pointer < min_wp)
                        min_wp = pc->read_pointer;
                     if (pc->read_pointer > pheader->write_pointer &&
                         pc->read_pointer - pheader->size < min_wp)
                        min_wp = pc->read_pointer - pheader->size;
                  }
               if (min_wp < 0)
                  min_wp += pheader->size;
               pheader->read_pointer = min_wp;
            }
         }
         /* if (size <= total_size) */
      } while (size <= pbuf->write_cache_wp);
      /* we have space, so let's copy the event */
      old_write_pointer = pheader->write_pointer;
#ifdef DEBUG_MSG
      cm_msg(MDEBUG, "bm_flush_cache: found space rp=%d, wp=%d", pheader->read_pointer,
             pheader->write_pointer);
#endif
      while (pbuf->write_cache_rp < pbuf->write_cache_wp) {
         /* loop over all events in cache */
         pevent = (EVENT_HEADER *) (pbuf->write_cache + pbuf->write_cache_rp);
         total_size = pevent->data_size + sizeof(EVENT_HEADER);
         /* correct size for DWORD boundary */
         total_size = ALIGN8(total_size);
         if (pheader->write_pointer + total_size <= pheader->size) {
            memcpy(pdata + pheader->write_pointer, pevent, total_size);
            pheader->write_pointer = (pheader->write_pointer + total_size) %
                pheader->size;
            if (pheader->write_pointer > pheader->size - (int) sizeof(EVENT_HEADER))
               pheader->write_pointer = 0;
         } else {
            /* split event */
            size = pheader->size - pheader->write_pointer;
            memcpy(pdata + pheader->write_pointer, pevent, size);
            memcpy(pdata, (char *) pevent + size, total_size - size);
            pheader->write_pointer = total_size - size;
         }
         pbuf->write_cache_rp += total_size;
      }
      pbuf->write_cache_rp = pbuf->write_cache_wp = 0;
      /* check which clients are waiting */
      for (i = 0; i < pheader->max_client_index; i++)
         if (pclient[i].pid && pclient[i].read_wait) {
#ifdef DEBUG_MSG
            cm_msg(MDEBUG, "Send wake: rp=%d, wp=%d", pheader->read_pointer,
                   pheader->write_pointer);
#endif
            sprintf(str, "B %s %d", pheader->name, -1);
            ss_resume(pclient[i].port, str);
         }
      /* shift read pointer of own client */
/* 16.4.99 SR, outcommented to receive own messages
  if (pclient[my_client_index].read_pointer == old_write_pointer)
    pclient[my_client_index].read_pointer = pheader->write_pointer;
*/
      /* calculate global read pointer as "minimum" of client read pointers */
      min_wp = pheader->write_pointer;
      for (i = 0, pc = pclient; i < pheader->max_client_index; i++, pc++)
         if (pc->pid) {
#ifdef DEBUG_MSG
            cm_msg(MDEBUG, "bm_flush_cache: client %d rp=%d", i, pc->read_pointer);
#endif
            if (pc->read_pointer < min_wp)
               min_wp = pc->read_pointer;
            if (pc->read_pointer > pheader->write_pointer &&
                pc->read_pointer - pheader->size < min_wp)
               min_wp = pc->read_pointer - pheader->size;
         }
      if (min_wp < 0)
         min_wp += pheader->size;
#ifdef DEBUG_MSG
      if (min_wp == pheader->read_pointer)
         cm_msg(MDEBUG, "bm_flush_cache -> wp=%d", pheader->write_pointer);
      else
         cm_msg(MDEBUG, "bm_flush_cache -> wp=%d, rp %d -> %d, size=%d",
                pheader->write_pointer, pheader->read_pointer, min_wp, size);
#endif
      pheader->read_pointer = min_wp;
      /* update statistics */
      pheader->num_in_events++;
      /* unlock the buffer */
      bm_unlock_buffer(buffer_handle);
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_mark_read_waiting (BOOL flag)
dox
Definition at line 7495 of file midas.c.
References _buffer_entries, BM_SUCCESS, BUFFER::buffer_header, BUFFER_HEADER::client, BUFFER::client_index, i, index, BUFFER_CLIENT::read_wait, RPC_BM_MARK_READ_WAITING, rpc_call(), rpc_get_server_acception(), rpc_get_server_option(), rpc_is_remote(), RPC_OSERVER_TYPE, ss_gettid(), and ST_SINGLE.
Referenced by bm_open_buffer(), bm_poll_event(), cm_yield(), and rpc_server_dispatch().
         : bm_mark_read_waiting
  Purpose: Mark all open buffers ready for receiving events.
           Called internally by ss_suspend
  Input:
    BOOL flag               TRUE for waiting, FALSE for not waiting
  Output:
    none
  Function value:
    BM_SUCCESS              Successful completion
\********************************************************************/
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_MARK_READ_WAITING, flag);
#ifdef LOCAL_ROUTINES
   {
      INT i;
      BUFFER_HEADER *pheader;
      BUFFER_CLIENT *pclient;
      /* Mark all buffer for read waiting */
      for (i = 0; i < _buffer_entries; i++) {
         if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_SINGLE &&
             _buffer[i].index != rpc_get_server_acception())
            continue;
         if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_SINGLE &&
             _buffer[i].index != ss_gettid())
            continue;
         if (!_buffer[i].attached)
            continue;
         pheader = _buffer[i].buffer_header;
         pclient = pheader->client + _buffer[i].client_index;
         pclient->read_wait = flag;
      }
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_match_event (short int event_id, short int trigger_mask, EVENT_HEADER * pevent)
Check if an event matches a given event request by the event id and trigger mask
Parameters:
event_id Event ID of request
trigger_mask Trigger mask of request
pevent Pointer to event to check
Returns:
TRUE if event matches request
Definition at line 4327 of file midas.c.
References EVENT_HEADER::event_id, EVENTID_ALL, EVENTID_FRAG, EVENTID_FRAG1, TRIGGER_ALL, and EVENT_HEADER::trigger_mask.
Referenced by bm_flush_cache(), bm_poll_event(), bm_push_event(), bm_receive_event(), and bm_send_event().
{
   if ((pevent->event_id & 0xF000) == EVENTID_FRAG1 ||
       (pevent->event_id & 0xF000) == EVENTID_FRAG)
      /* fragmented event */
      return ((event_id == EVENTID_ALL ||
               event_id == (pevent->event_id & 0x0FFF)) &&
              (trigger_mask == TRIGGER_ALL || (trigger_mask & pevent->trigger_mask)));
   return ((event_id == EVENTID_ALL ||
            event_id == pevent->event_id) &&
           (trigger_mask == TRIGGER_ALL || (trigger_mask & pevent->trigger_mask)));
}
INT bm_notify_client (char * buffer_name, int socket)
Definition at line 7548 of file midas.c.
References _buffer_entries, BM_INVALID_HANDLE, BM_SUCCESS, buffer, callback, CF_ASCII, DB_SUCCESS, NET_COMMAND::header, i, last_time, MSG_BM, NET_COMMAND_HEADER::param_size, NET_COMMAND_HEADER::routine_id, RPC_CONVERT_FLAGS, rpc_convert_single(), rpc_get_server_option(), RPC_OUTGOING, send_tcp(), ss_millitime(), and TID_DWORD.
Referenced by cm_dispatch_ipc().
         : bm_notify_client
  Purpose: Called by cm_dispatch_ipc. Send an event notification to
           the connected client
  Input:
    char  *buffer_name      Name of buffer
    int   socket            Network socket to client
  Output:
    none
  Function value:
    BM_SUCCESS              Successful completion
\********************************************************************/
{
   char buffer[32];
   NET_COMMAND *nc;
   INT i, convert_flags;
   static DWORD last_time = 0;
   for (i = 0; i < _buffer_entries; i++)
      if (strcmp(buffer_name, _buffer[i].buffer_header->name) == 0)
         break;
   if (i == _buffer_entries)
      return BM_INVALID_HANDLE;
   /* don't send notification if client has no callback defined
      to receive events -> client calls bm_receive_event manually */
   if (!_buffer[i].callback)
      return DB_SUCCESS;
   convert_flags = rpc_get_server_option(RPC_CONVERT_FLAGS);
   /* only send notification once each 500ms */
   if (ss_millitime() - last_time < 500 && !(convert_flags & CF_ASCII))
      return DB_SUCCESS;
   last_time = ss_millitime();
   if (convert_flags & CF_ASCII) {
      sprintf(buffer, "MSG_BM&%s", buffer_name);
      send_tcp(socket, buffer, strlen(buffer) + 1, 0);
   } else {
      nc = (NET_COMMAND *) buffer;
      nc->header.routine_id = MSG_BM;
      nc->header.param_size = 0;
      if (convert_flags) {
         rpc_convert_single(&nc->header.routine_id, TID_DWORD,
                            RPC_OUTGOING, convert_flags);
         rpc_convert_single(&nc->header.param_size, TID_DWORD,
                            RPC_OUTGOING, convert_flags);
      }
      /* send the update notification to the client */
      send_tcp(socket, (char *) buffer, sizeof(NET_COMMAND_HEADER), 0);
   }
   return BM_SUCCESS;
}
INT bm_open_buffer (char * buffer_name, INT buffer_size, INT * buffer_handle)
Open an event buffer. Two default buffers are created by the system. The "SYSTEM" buffer is used to exchange events and the "SYSMSG" buffer is used to exchange system messages. The name and size of the event buffers is defined in midas.h as EVENT_BUFFER_NAME and EVENT_BUFFER_SIZE. Following example opens the "SYSTEM" buffer, requests events with ID 1 and enters a main loop. Events are then received in process_event()
#include <stdio.h>
#include "midas.h"
void process_event(HNDLE hbuf, HNDLE request_id,
           EVENT_HEADER *pheader, void *pevent)
{
  printf("Received event #%d\r",
  pheader->serial_number);
}
main()
{
  INT status, request_id;
  HNDLE hbuf;
  status = cm_connect_experiment("pc810", "Sample", "Simple Analyzer", NULL);
  if (status != CM_SUCCESS)
  return 1;
  bm_open_buffer(EVENT_BUFFER_NAME, EVENT_BUFFER_SIZE, &hbuf);
  bm_request_event(hbuf, 1, TRIGGER_ALL, GET_ALL, request_id, process_event);
  do
  {
   status = cm_yield(1000);
  } while (status != RPC_SHUTDOWN && status != SS_ABORT);
  cm_disconnect_experiment();
  return 0;
}
Parameters:
buffer_name Name of buffer
buffer_size Size of buffer in bytes
buffer_handle Buffer handle returned by function
Returns:
BM_SUCCESS, BM_CREATED
BM_NO_SHM Shared memory cannot be created
BM_NO_MUTEX Mutex cannot be created
BM_NO_MEMORY Not enough memory to create buffer descriptor
BM_MEMSIZE_MISMATCH Buffer size conflicts with an existing buffer of different size
BM_INVALID_PARAM Invalid parameter
Definition at line 4389 of file midas.c.
References _buffer_entries, BUFFER::attached, BM_CREATED, bm_init_buffer_counters(), BM_INVALID_NAME, BM_INVALID_PARAM, bm_lock_buffer(), bm_mark_read_waiting(), BM_MEMSIZE_MISMATCH, BM_NO_MEMORY, BM_NO_MUTEX, BM_NO_SHM, BM_NO_SLOT, BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_data, BUFFER::buffer_header, BUFFER::callback, CH_IPC, BUFFER_HEADER::client, BUFFER::client_index, cm_dispatch_ipc(), cm_get_client_info(), cm_get_watchdog_params(), cm_msg, equal_ustring(), FALSE, handle, i, BUFFER::index, index, BUFFER_CLIENT::last_activity, M_MALLOC, BUFFER_HEADER::max_client_index, MAX_CLIENTS, MERROR, BUFFER_CLIENT::name, BUFFER_HEADER::name, NAME_LENGTH, BUFFER_HEADER::num_clients, BUFFER_CLIENT::pid, BUFFER_CLIENT::port, BUFFER_CLIENT::read_pointer, RPC_BM_OPEN_BUFFER, rpc_call(), rpc_get_server_acception(), rpc_get_server_option(), rpc_is_remote(), RPC_OSERVER_TYPE, BUFFER::shm_handle, BUFFER_HEADER::size, SS_CREATED, SS_FILE_ERROR, ss_getpid(), ss_getthandle(), ss_gettid(), ss_millitime(), ss_mutex_create(), SS_NO_MEMORY, ss_shm_close(), ss_shm_open(), SS_SUCCESS, ss_suspend_get_port(), ss_suspend_set_dispatch(), ST_SINGLE, status, BUFFER_CLIENT::thandle, BUFFER_CLIENT::tid, TRUE, BUFFER_CLIENT::watchdog_timeout, and BUFFER_HEADER::write_pointer.
Referenced by cm_msg(), cm_msg1(), cm_msg_register(), command_loop(), main(), register_equipment(), register_requests(), rpc_server_dispatch(), source_booking(), tr_start(), and tr_start1().
{
   INT status;
   if (rpc_is_remote()) {
      status = rpc_call(RPC_BM_OPEN_BUFFER, buffer_name, buffer_size, buffer_handle);
      bm_mark_read_waiting(TRUE);
      return status;
   }
#ifdef LOCAL_ROUTINES
   {
      INT i, handle;
      BUFFER_CLIENT *pclient;
      BOOL shm_created;
      HNDLE shm_handle;
      BUFFER_HEADER *pheader;
      if (buffer_size <= 0 || buffer_size > 32E6) {
         cm_msg(MERROR, "bm_open_buffer", "invalid buffer size");
         return BM_INVALID_PARAM;
      }
      if (!buffer_name[0]) {
         cm_msg(MERROR, "bm_open_buffer", "cannot open buffer with zero name");
         return BM_INVALID_PARAM;
      }
      /* allocate new space for the new buffer descriptor */
      if (_buffer_entries == 0) {
         _buffer = (BUFFER *) M_MALLOC(sizeof(BUFFER));
         memset(_buffer, 0, sizeof(BUFFER));
         if (_buffer == NULL) {
            *buffer_handle = 0;
            return BM_NO_MEMORY;
         }
         _buffer_entries = 1;
         i = 0;
      } else {
         /* check if buffer alreay is open */
         for (i = 0; i < _buffer_entries; i++)
            if (_buffer[i].attached &&
                equal_ustring(_buffer[i].buffer_header->name, buffer_name)) {
               if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_SINGLE &&
                   _buffer[i].index != rpc_get_server_acception())
                  continue;
               if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_SINGLE &&
                   _buffer[i].index != ss_gettid())
                  continue;
               *buffer_handle = i + 1;
               return BM_SUCCESS;
            }
         /* check for a deleted entry */
         for (i = 0; i < _buffer_entries; i++)
            if (!_buffer[i].attached)
               break;
         /* if not found, create new one */
         if (i == _buffer_entries) {
            _buffer = (BUFFER *) realloc(_buffer, sizeof(BUFFER) * (_buffer_entries + 1));
            memset(&_buffer[_buffer_entries], 0, sizeof(BUFFER));
            _buffer_entries++;
            if (_buffer == NULL) {
               _buffer_entries--;
               *buffer_handle = 0;
               return BM_NO_MEMORY;
            }
         }
      }
      handle = i;
      if (strlen(buffer_name) >= NAME_LENGTH)
         buffer_name[NAME_LENGTH] = 0;
      /* reduce buffer size is larger than maximum */
#ifdef MAX_SHM_SIZE
      if (buffer_size + sizeof(BUFFER_HEADER) > MAX_SHM_SIZE)
         buffer_size = MAX_SHM_SIZE - sizeof(BUFFER_HEADER);
#endif
      /* open shared memory region */
      status = ss_shm_open(buffer_name, sizeof(BUFFER_HEADER) + buffer_size,
                           (void **) &(_buffer[handle].buffer_header), &shm_handle);
      if (status == SS_NO_MEMORY || status == SS_FILE_ERROR) {
         *buffer_handle = 0;
         return BM_NO_SHM;
      }
      pheader = _buffer[handle].buffer_header;
      shm_created = (status == SS_CREATED);
      if (shm_created) {
         /* setup header info if buffer was created */
         memset(pheader, 0, sizeof(BUFFER_HEADER));
         strcpy(pheader->name, buffer_name);
         pheader->size = buffer_size;
      } else {
         /* check if buffer size is identical */
         if (pheader->size != buffer_size) {
            buffer_size = pheader->size;
            /* re-open shared memory with proper size */
            status = ss_shm_close(buffer_name, _buffer[handle].buffer_header,
                                  shm_handle, FALSE);
            if (status != BM_SUCCESS)
               return BM_MEMSIZE_MISMATCH;
            status = ss_shm_open(buffer_name, sizeof(BUFFER_HEADER) + buffer_size,
                                 (void **) &(_buffer[handle].buffer_header), &shm_handle);
            if (status == SS_NO_MEMORY || status == SS_FILE_ERROR) {
               *buffer_handle = 0;
               return BM_INVALID_NAME;
            }
            pheader = _buffer[handle].buffer_header;
         }
      }
      /* create mutex for the buffer */
      status = ss_mutex_create(buffer_name, &(_buffer[handle].mutex));
      if (status != SS_CREATED && status != SS_SUCCESS) {
         *buffer_handle = 0;
         return BM_NO_MUTEX;
      }
      /* first lock buffer */
      bm_lock_buffer(handle + 1);
      /*
         Now we have a BUFFER_HEADER, so let's setup a CLIENT
         structure in that buffer. The information there can also
         be seen by other processes.
       */
      for (i = 0; i < MAX_CLIENTS; i++)
         if (pheader->client[i].pid == 0)
            break;
      if (i == MAX_CLIENTS) {
         bm_unlock_buffer(handle + 1);
         *buffer_handle = 0;
         cm_msg(MERROR, "bm_open_buffer", "maximum number of clients exceeded");
         return BM_NO_SLOT;
      }
      /* store slot index in _buffer structure */
      _buffer[handle].client_index = i;
      /*
         Save the index of the last client of that buffer so that later only
         the clients 0..max_client_index-1 have to be searched through.
       */
      pheader->num_clients++;
      if (i + 1 > pheader->max_client_index)
         pheader->max_client_index = i + 1;
      /* setup buffer header and client structure */
      pclient = &pheader->client[i];
      memset(pclient, 0, sizeof(BUFFER_CLIENT));
      /* use client name previously set by bm_set_name */
      cm_get_client_info(pclient->name);
      if (pclient->name[0] == 0)
         strcpy(pclient->name, "unknown");
      pclient->pid = ss_getpid();
      pclient->tid = ss_gettid();
      pclient->thandle = ss_getthandle();
      ss_suspend_get_port(&pclient->port);
      pclient->read_pointer = pheader->write_pointer;
      pclient->last_activity = ss_millitime();
      cm_get_watchdog_params(NULL, &pclient->watchdog_timeout);
      bm_unlock_buffer(handle + 1);
      /* setup _buffer entry */
      _buffer[handle].buffer_data = _buffer[handle].buffer_header + 1;
      _buffer[handle].attached = TRUE;
      _buffer[handle].shm_handle = shm_handle;
      _buffer[handle].callback = FALSE;
      /* remember to which connection acutal buffer belongs */
      if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_SINGLE)
         _buffer[handle].index = rpc_get_server_acception();
      else
         _buffer[handle].index = ss_gettid();
      *buffer_handle = (handle + 1);
      /* initialize buffer counters */
      bm_init_buffer_counters(handle + 1);
      /* setup dispatcher for receive events */
      ss_suspend_set_dispatch(CH_IPC, 0, (int (*)(void)) cm_dispatch_ipc);
      if (shm_created)
         return BM_CREATED;
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_poll_event (INT flag)
Definition at line 7616 of file midas.c.
References _event_buffer_size, _request_list_entries, ASYNC, BM_ASYNC_RETURN, bm_defragment_event(), bm_mark_read_waiting(), bm_match_event(), bm_receive_event(), BM_SUCCESS, cm_msg, REQUEST_LIST::dispatcher, EVENT_HEADER::event_id, EVENTID_FRAG, EVENTID_FRAG1, FALSE, i, M_MALLOC, MAX_EVENT_SIZE, MERROR, RPC_NET_ERROR, size, SS_ABORT, ss_millitime(), start_time, status, and TRUE.
Referenced by cm_yield(), rpc_client_dispatch(), and tr_stop().
         : bm_poll_event
  Purpose: Poll an event from a remote server. Gets called by
           rpc_client_dispatch
  Input:
    INT flag         TRUE if called from cm_yield
  Output:
    none
  Function value:
    TRUE             More events are waiting
    FALSE            No more events are waiting
    SS_ABORT         Network connection broken
\********************************************************************/
{
   INT status, size, i, request_id;
   DWORD start_time;
   BOOL bMore;
   static BOOL bMoreLast = FALSE;
   if (_event_buffer_size == 0) {
      _event_buffer = (EVENT_HEADER *) M_MALLOC(MAX_EVENT_SIZE + sizeof(EVENT_HEADER));
      if (!_event_buffer) {
         cm_msg(MERROR, "bm_poll_event", "not enough memory to allocate event buffer");
         return SS_ABORT;
      }
      _event_buffer_size = MAX_EVENT_SIZE + sizeof(EVENT_HEADER);
   }
   start_time = ss_millitime();
   /* if we got event notification, turn off read_wait */
   if (!flag)
      bm_mark_read_waiting(FALSE);
   /* if called from yield, return if no more events */
   if (flag) {
      if (!bMoreLast)
         return FALSE;
   }
   bMore = FALSE;
   /* loop over all requests */
   for (request_id = 0; request_id < _request_list_entries; request_id++) {
      /* continue if no dispatcher set (manual bm_receive_event) */
      if (_request_list[request_id].dispatcher == NULL)
         continue;
      do {
         /* receive event */
         size = _event_buffer_size;
         status = bm_receive_event(_request_list[request_id].buffer_handle,
                                   _event_buffer, &size, ASYNC);
         /* call user function if successful */
         if (status == BM_SUCCESS)
            /* search proper request for this event */
            for (i = 0; i < _request_list_entries; i++)
               if ((_request_list[i].buffer_handle ==
                    _request_list[request_id].buffer_handle) &&
                   bm_match_event(_request_list[i].event_id,
                                  _request_list[i].trigger_mask, _event_buffer)) {
                  if ((_event_buffer->event_id & 0xF000) == EVENTID_FRAG1 ||
                      (_event_buffer->event_id & 0xF000) == EVENTID_FRAG)
                     bm_defragment_event(_request_list[i].buffer_handle, i, _event_buffer,
                                         (void *) (((EVENT_HEADER *) _event_buffer) + 1),
                                         _request_list[i].dispatcher);
                  else
                     _request_list[i].dispatcher(_request_list[i].buffer_handle, i,
                                                 _event_buffer,
                                                 (void
                                                  *) (((EVENT_HEADER *) _event_buffer) +
                                                      1));
               }
         /* break if no more events */
         if (status == BM_ASYNC_RETURN)
            break;
         /* break if server died */
         if (status == RPC_NET_ERROR)
            return SS_ABORT;
         /* stop after one second */
         if (ss_millitime() - start_time > 1000) {
            bMore = TRUE;
            break;
         }
      } while (TRUE);
   }
   if (!bMore)
      bm_mark_read_waiting(TRUE);
   bMoreLast = bMore;
   return bMore;
}
INT bm_push_event (char * buffer_name)
Check a buffer if an event is available and call the dispatch function if found.
Parameters:
buffer_name Name of buffer
Returns:
BM_SUCCESS, BM_INVALID_HANDLE, BM_TRUNCATED, BM_ASYNC_RETURN, RPC_NET_ERROR
Definition at line 7157 of file midas.c.
References _buffer_entries, _event_buffer_size, _request_list_entries, ALIGN8, BUFFER::attached, bm_defragment_event(), BM_INVALID_HANDLE, bm_lock_buffer(), bm_match_event(), BM_MORE_EVENTS, BM_NO_MEMORY, BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER::callback, BUFFER_HEADER::client, BUFFER::client_index, cm_msg, EVENT_HEADER::data_size, REQUEST_LIST::dispatcher, EVENT_REQUEST::event_id, EVENT_HEADER::event_id, BUFFER_CLIENT::event_request, EVENTID_FRAG, EVENTID_FRAG1, FALSE, found, i, if, LOOP, M_MALLOC, BUFFER_HEADER::max_client_index, BUFFER_CLIENT::max_request_index, MDEBUG, MERROR, BUFFER_HEADER::num_out_events, BUFFER_CLIENT::pid, BUFFER_CLIENT::port, BUFFER::read_cache, BUFFER::read_cache_rp, BUFFER::read_cache_size, BUFFER::read_cache_wp, BUFFER_HEADER::read_pointer, BUFFER_CLIENT::read_pointer, BUFFER_HEADER::size, size, ss_getpid(), ss_gettid(), ss_resume(), BUFFER_CLIENT::tid, EVENT_REQUEST::trigger_mask, TRUE, EVENT_REQUEST::valid, BUFFER_HEADER::write_pointer, and BUFFER_CLIENT::write_wait.
Referenced by bm_check_buffers(), and cm_dispatch_ipc().
{
#ifdef LOCAL_ROUTINES
   {
      BUFFER *pbuf;
      BUFFER_HEADER *pheader;
      BUFFER_CLIENT *pclient, *pc, *pctmp;
      EVENT_REQUEST *prequest;
      EVENT_HEADER *pevent;
      char *pdata;
      INT i, min_wp, size, total_size, buffer_handle;
      INT my_client_index;
      BOOL found;
      INT old_read_pointer, new_read_pointer;
      for (i = 0; i < _buffer_entries; i++)
         if (strcmp(buffer_name, _buffer[i].buffer_header->name) == 0)
            break;
      if (i == _buffer_entries)
         return BM_INVALID_HANDLE;
      buffer_handle = i + 1;
      pbuf = &_buffer[buffer_handle - 1];
      if (!pbuf->attached)
         return BM_INVALID_HANDLE;
      /* return immediately if no callback routine is defined */
      if (!pbuf->callback)
         return BM_SUCCESS;
      if (_event_buffer_size == 0) {
         _event_buffer = (EVENT_HEADER *) M_MALLOC(1000);
         if (_event_buffer == NULL) {
            cm_msg(MERROR, "bm_push_event", "not enough memory to allocate cache buffer");
            return BM_NO_MEMORY;
         }
         _event_buffer_size = 1000;
      }
    CACHE_READ:
      /* look if there is anything in the cache */
      if (pbuf->read_cache_wp > pbuf->read_cache_rp) {
         pevent = (EVENT_HEADER *) (pbuf->read_cache + pbuf->read_cache_rp);
         size = pevent->data_size + sizeof(EVENT_HEADER);
         /* correct size for DWORD boundary */
         size = ALIGN8(size);
         /* increment read pointer */
         pbuf->read_cache_rp += size;
         if (pbuf->read_cache_rp == pbuf->read_cache_wp)
            pbuf->read_cache_rp = pbuf->read_cache_wp = 0;
         /* call dispatcher */
         for (i = 0; i < _request_list_entries; i++)
            if (_request_list[i].buffer_handle == buffer_handle &&
                bm_match_event(_request_list[i].event_id,
                               _request_list[i].trigger_mask, pevent)) {
               /* if event is fragmented, call defragmenter */
               if ((pevent->event_id & 0xF000) == EVENTID_FRAG1 ||
                   (pevent->event_id & 0xF000) == EVENTID_FRAG)
                  bm_defragment_event(buffer_handle, i, pevent, (void *) (pevent + 1),
                                      _request_list[i].dispatcher);
               else
                  _request_list[i].dispatcher(buffer_handle, i, pevent,
                                              (void *) (pevent + 1));
            }
         return BM_MORE_EVENTS;
      }
      /* calculate some shorthands */
      pheader = pbuf->buffer_header;
      pdata = (char *) (pheader + 1);
      my_client_index = pbuf->client_index;
      pclient = pheader->client;
      pc = pheader->client + my_client_index;
      /* first do a quick check without locking the buffer */
      if (pheader->write_pointer == pc->read_pointer)
         return BM_SUCCESS;
      /* lock the buffer */
      bm_lock_buffer(buffer_handle);
    LOOP:
      if (pheader->write_pointer == pc->read_pointer) {
         bm_unlock_buffer(buffer_handle);
         /* return if no event available */
         return BM_SUCCESS;
      }
      /* check if event at current read pointer matches a request */
      found = FALSE;
      do {
         pevent = (EVENT_HEADER *) (pdata + pc->read_pointer);
         total_size = pevent->data_size + sizeof(EVENT_HEADER);
         total_size = ALIGN8(total_size);
         prequest = pc->event_request;
         for (i = 0; i < pc->max_request_index; i++, prequest++)
            if (prequest->valid &&
                bm_match_event(prequest->event_id, prequest->trigger_mask, pevent)) {
               /* we found one, so copy it */
               if (pbuf->read_cache_size > 0 &&
                   !(total_size > pbuf->read_cache_size && pbuf->read_cache_wp == 0)) {
                  /* copy dispatch function and event to cache */
                  if (pbuf->read_cache_size - pbuf->read_cache_wp <
                      total_size + (INT) sizeof(void *) + (INT) sizeof(INT))
                     goto CACHE_FULL;
                  if (pc->read_pointer + total_size <= pheader->size) {
                     /* copy event to cache */
                     memcpy(pbuf->read_cache + pbuf->read_cache_wp, pevent, total_size);
                  } else {
                     /* event is splitted */
                     size = pheader->size - pc->read_pointer;
                     memcpy(pbuf->read_cache + pbuf->read_cache_wp, pevent, size);
                     memcpy((char *) pbuf->read_cache + pbuf->read_cache_wp + size,
                            pdata, total_size - size);
                  }
                  pbuf->read_cache_wp += total_size;
               } else {
                  /* copy event to copy buffer, save dispatcher */
                  if (total_size > _event_buffer_size) {
                     _event_buffer = (EVENT_HEADER *) realloc(_event_buffer, total_size);
                     _event_buffer_size = total_size;
                  }
                  if (pc->read_pointer + total_size <= pheader->size) {
                     memcpy(_event_buffer, pevent, total_size);
                  } else {
                     /* event is splitted */
                     size = pheader->size - pc->read_pointer;
                     memcpy(_event_buffer, pevent, size);
                     memcpy((char *) _event_buffer + size, pdata, total_size - size);
                  }
               }
               /* update statistics */
               found = TRUE;
               pheader->num_out_events++;
               break;
            }
         old_read_pointer = pc->read_pointer;
         /* shift read pointer */
         new_read_pointer = (pc->read_pointer + total_size) % pheader->size;
         if (new_read_pointer > pheader->size - (int) sizeof(EVENT_HEADER))
            new_read_pointer = 0;
#ifdef DEBUG_MSG
         cm_msg(MDEBUG, "bm_receive_event -> wp=%d, rp %d -> %d (found=%d,size=%d)",
                pheader->write_pointer, pc->read_pointer, new_read_pointer, found,
                total_size);
#endif
         pc->read_pointer = new_read_pointer;
         /*
            Repeat until a requested event is found or no more events
            are available or large event received.
          */
         if (pbuf->read_cache_size == 0 && found)
            break;
         /* break if event has bypassed read cache */
         if (pbuf->read_cache_size > 0 &&
             total_size > pbuf->read_cache_size && pbuf->read_cache_wp == 0)
            break;
      } while (pheader->write_pointer != pc->read_pointer);
    CACHE_FULL:
      /* calculate global read pointer as "minimum" of client read pointers */
      min_wp = pheader->write_pointer;
      for (i = 0, pctmp = pclient; i < pheader->max_client_index; i++, pctmp++)
         if (pctmp->pid) {
            if (pctmp->read_pointer < min_wp)
               min_wp = pctmp->read_pointer;
            if (pctmp->read_pointer > pheader->write_pointer &&
                pctmp->read_pointer - pheader->size < min_wp)
               min_wp = pctmp->read_pointer - pheader->size;
         }
      if (min_wp < 0)
         min_wp += pheader->size;
      pheader->read_pointer = min_wp;
      /*
         If read pointer has been changed, it may have freed up some space
         for waiting producers. So check if free space is now more than 50%
         of the buffer size and wake waiting producers.
       */
      size = pc->read_pointer - pheader->write_pointer;
      if (size <= 0)
         size += pheader->size;
      if (size >= pheader->size * 0.5)
         for (i = 0, pctmp = pclient; i < pheader->max_client_index; i++, pctmp++)
            if (pctmp->pid && (pctmp->write_wait < size) && (pctmp->pid != ss_getpid() ||       /* check if not own thread */
                                                             (pctmp->pid == ss_getpid()
                                                              && pctmp->tid !=
                                                              ss_gettid()))) {
#ifdef DEBUG_MSG
               cm_msg(MDEBUG, "Receive wake: rp=%d, wp=%d, level=%1.1lf",
                      pheader->read_pointer,
                      pheader->write_pointer, 100 - 100.0 * size / pheader->size);
#endif
               ss_resume(pctmp->port, "B  ");
            }
      /* if no matching event found, start again */
      if (!found)
         goto LOOP;
      bm_unlock_buffer(buffer_handle);
      if (pbuf->read_cache_size > 0 &&
          !(total_size > pbuf->read_cache_size && pbuf->read_cache_wp == 0))
         goto CACHE_READ;
      /* call dispatcher */
      for (i = 0; i < _request_list_entries; i++)
         if (_request_list[i].buffer_handle == buffer_handle &&
             bm_match_event(_request_list[i].event_id,
                            _request_list[i].trigger_mask, _event_buffer)) {
            if ((_event_buffer->event_id & 0xF000) == EVENTID_FRAG1 ||
                (_event_buffer->event_id & 0xF000) == EVENTID_FRAG)
               bm_defragment_event(buffer_handle, i, _event_buffer,
                                   (void *) (((EVENT_HEADER *) _event_buffer) + 1),
                                   _request_list[i].dispatcher);
            else
               _request_list[i].dispatcher(buffer_handle, i, _event_buffer,
                                           (void *) (((EVENT_HEADER *) _event_buffer) +
                                                     1));
         }
      return BM_MORE_EVENTS;
   }
#else                           /* LOCAL_ROUTINES */
   return BM_SUCCESS;
#endif
}
INT bm_receive_event (INT buffer_handle, void * destination, INT * buf_size, INT async_flag)
Receives events directly. This function is an alternative way to receive events without a main loop.
It can be used in analysis systems which actively receive events, rather than using callbacks. A analysis package could for example contain its own command line interface. A command like "receive 1000 events" could make it necessary to call bm_receive_event() 1000 times in a row to receive these events and then return back to the command line prompt. The according bm_request_event() call contains NULL as the callback routine to indicate that bm_receive_event() is called to receive events.
#include <stdio.h>
#include "midas.h"
void process_event(EVENT_HEADER *pheader)
{
 printf("Received event #%d\r",
 pheader->serial_number);
}
main()
{
  INT status, request_id;
  HNDLE hbuf;
  char event_buffer[1000];
  status = cm_connect_experiment("", "Sample",
  "Simple Analyzer", NULL);
  if (status != CM_SUCCESS)
   return 1;
  bm_open_buffer(EVENT_BUFFER_NAME, EVENT_BUFFER_SIZE, &hbuf);
  bm_request_event(hbuf, 1, TRIGGER_ALL, GET_ALL, request_id, NULL);
  do
  {
   size = sizeof(event_buffer);
   status = bm_receive_event(hbuf, event_buffer, &size, ASYNC);
  if (status == CM_SUCCESS)
   process_event((EVENT_HEADER *) event_buffer);
   <...do something else...>
   status = cm_yield(0);
  } while (status != RPC_SHUTDOWN &&
  status != SS_ABORT);
  cm_disconnect_experiment();
  return 0;
}
Parameters:
buffer_handle buffer handle
destination destination address where event is written to
buf_size size of destination buffer on input, size of event plus header on return.
async_flag Synchronous/asynchronous flag. If FALSE, the function blocks if no event is available. If TRUE, the function returns immediately with a value of BM_ASYNC_RETURN without receiving any event.
Returns:
BM_SUCCESS, BM_INVALID_HANDLE
BM_TRUNCATED The event is larger than the destination buffer and was therefore truncated
BM_ASYNC_RETURN No event available
Definition at line 6777 of file midas.c.
References _buffer_entries, ALIGN8, ASYNC, BUFFER::attached, BM_ASYNC_RETURN, BM_INVALID_HANDLE, bm_lock_buffer(), bm_match_event(), BM_SUCCESS, BM_TRUNCATED, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER_HEADER::client, BUFFER::client_index, cm_msg, EVENT_HEADER::data_size, EVENT_REQUEST::event_id, EVENT_HEADER::event_id, BUFFER_CLIENT::event_request, FALSE, found, i, if, LOOP, BUFFER_HEADER::max_client_index, BUFFER_CLIENT::max_request_index, MDEBUG, MERROR, MSG_BM, NET_BUFFER_SIZE, BUFFER_HEADER::num_out_events, BUFFER_CLIENT::pid, BUFFER_CLIENT::port, BUFFER::read_cache, BUFFER::read_cache_rp, BUFFER::read_cache_size, BUFFER::read_cache_wp, BUFFER_HEADER::read_pointer, BUFFER_CLIENT::read_pointer, BUFFER_CLIENT::read_wait, RPC_BM_RECEIVE_EVENT, rpc_call(), RPC_CONVERT_FLAGS, rpc_convert_single(), rpc_get_server_option(), rpc_is_remote(), RPC_NET_ERROR, RPC_OSERVER_TYPE, RPC_OUTGOING, EVENT_HEADER::serial_number, BUFFER_HEADER::size, size, SS_ABORT, ss_getpid(), ss_gettid(), ss_resume(), SS_SUCCESS, ss_suspend(), ST_REMOTE, status, BUFFER_CLIENT::tid, TID_DWORD, TID_SHORT, EVENT_HEADER::time_stamp, EVENT_REQUEST::trigger_mask, EVENT_HEADER::trigger_mask, TRUE, EVENT_REQUEST::valid, BUFFER_HEADER::write_pointer, and BUFFER_CLIENT::write_wait.
Referenced by bm_poll_event(), handFlush(), main(), rpc_server_dispatch(), and source_scan().
{
   if (rpc_is_remote()) {
      if (*buf_size > NET_BUFFER_SIZE) {
         cm_msg(MERROR, "bm_receive_event",
                "max. event size larger than NET_BUFFER_SIZE");
         return RPC_NET_ERROR;
      }
      return rpc_call(RPC_BM_RECEIVE_EVENT, buffer_handle,
                      destination, buf_size, async_flag);
   }
#ifdef LOCAL_ROUTINES
   {
      BUFFER *pbuf;
      BUFFER_HEADER *pheader;
      BUFFER_CLIENT *pclient, *pc, *pctmp;
      EVENT_REQUEST *prequest;
      EVENT_HEADER *pevent;
      char *pdata;
      INT convert_flags;
      INT i, min_wp, size, max_size, total_size, status = 0;
      INT my_client_index;
      BOOL found;
      INT old_read_pointer, new_read_pointer;
      pbuf = &_buffer[buffer_handle - 1];
      if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
         cm_msg(MERROR, "bm_receive_event", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      if (!pbuf->attached) {
         cm_msg(MERROR, "bm_receive_event", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      max_size = *buf_size;
      *buf_size = 0;
      if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE)
         convert_flags = rpc_get_server_option(RPC_CONVERT_FLAGS);
      else
         convert_flags = 0;
    CACHE_READ:
      /* look if there is anything in the cache */
      if (pbuf->read_cache_wp > pbuf->read_cache_rp) {
         pevent = (EVENT_HEADER *) (pbuf->read_cache + pbuf->read_cache_rp);
         size = pevent->data_size + sizeof(EVENT_HEADER);
         if (size > max_size) {
            memcpy(destination, pbuf->read_cache + pbuf->read_cache_rp, max_size);
            cm_msg(MERROR, "bm_receive_event", "event size larger than buffer size");
            *buf_size = max_size;
            status = BM_TRUNCATED;
         } else {
            memcpy(destination, pbuf->read_cache + pbuf->read_cache_rp, size);
            *buf_size = size;
            status = BM_SUCCESS;
         }
         /* now convert event header */
         if (convert_flags) {
            pevent = (EVENT_HEADER *) destination;
            rpc_convert_single(&pevent->event_id, TID_SHORT, RPC_OUTGOING, convert_flags);
            rpc_convert_single(&pevent->trigger_mask, TID_SHORT, RPC_OUTGOING,
                               convert_flags);
            rpc_convert_single(&pevent->serial_number, TID_DWORD, RPC_OUTGOING,
                               convert_flags);
            rpc_convert_single(&pevent->time_stamp, TID_DWORD, RPC_OUTGOING,
                               convert_flags);
            rpc_convert_single(&pevent->data_size, TID_DWORD, RPC_OUTGOING,
                               convert_flags);
         }
         /* correct size for DWORD boundary */
         size = ALIGN8(size);
         pbuf->read_cache_rp += size;
         if (pbuf->read_cache_rp == pbuf->read_cache_wp)
            pbuf->read_cache_rp = pbuf->read_cache_wp = 0;
         return status;
      }
      /* calculate some shorthands */
      pheader = pbuf->buffer_header;
      pdata = (char *) (pheader + 1);
      my_client_index = pbuf->client_index;
      pclient = pheader->client;
      pc = pheader->client + my_client_index;
      /* first do a quick check without locking the buffer */
      if (async_flag == ASYNC && pheader->write_pointer == pc->read_pointer)
         return BM_ASYNC_RETURN;
      /* lock the buffer */
      bm_lock_buffer(buffer_handle);
    LOOP:
      while (pheader->write_pointer == pc->read_pointer) {
         bm_unlock_buffer(buffer_handle);
         /* return now in ASYNC mode */
         if (async_flag == ASYNC)
            return BM_ASYNC_RETURN;
         pc->read_wait = TRUE;
         /* check again pointers (may have moved in between) */
         if (pheader->write_pointer == pc->read_pointer) {
#ifdef DEBUG_MSG
            cm_msg(MDEBUG, "Receive sleep: grp=%d, rp=%d wp=%d",
                   pheader->read_pointer, pc->read_pointer, pheader->write_pointer);
#endif
            status = ss_suspend(1000, MSG_BM);
#ifdef DEBUG_MSG
            cm_msg(MDEBUG, "Receive woke up: rp=%d, wp=%d",
                   pheader->read_pointer, pheader->write_pointer);
#endif
            /* return if TCP connection broken */
            if (status == SS_ABORT)
               return SS_ABORT;
         }
         pc->read_wait = FALSE;
         bm_lock_buffer(buffer_handle);
      }
      /* check if event at current read pointer matches a request */
      found = FALSE;
      do {
         pevent = (EVENT_HEADER *) (pdata + pc->read_pointer);
         total_size = pevent->data_size + sizeof(EVENT_HEADER);
         total_size = ALIGN8(total_size);
         prequest = pc->event_request;
         for (i = 0; i < pc->max_request_index; i++, prequest++)
            if (prequest->valid &&
                bm_match_event(prequest->event_id, prequest->trigger_mask, pevent)) {
               /* we found one, so copy it */
               if (pbuf->read_cache_size > 0 &&
                   !(total_size > pbuf->read_cache_size && pbuf->read_cache_wp == 0)) {
                  if (pbuf->read_cache_size - pbuf->read_cache_wp < total_size)
                     goto CACHE_FULL;
                  if (pc->read_pointer + total_size <= pheader->size) {
                     /* copy event to cache */
                     memcpy(pbuf->read_cache + pbuf->read_cache_wp, pevent, total_size);
                  } else {
                     /* event is splitted */
                     size = pheader->size - pc->read_pointer;
                     memcpy(pbuf->read_cache + pbuf->read_cache_wp, pevent, size);
                     memcpy((char *) pbuf->read_cache + pbuf->read_cache_wp + size,
                            pdata, total_size - size);
                  }
               } else {
                  if (pc->read_pointer + total_size <= pheader->size) {
                     /* event is not splitted */
                     if (total_size > max_size)
                        memcpy(destination, pevent, max_size);
                     else
                        memcpy(destination, pevent, total_size);
                  } else {
                     /* event is splitted */
                     size = pheader->size - pc->read_pointer;
                     if (size > max_size)
                        memcpy(destination, pevent, max_size);
                     else
                        memcpy(destination, pevent, size);
                     if (total_size > max_size) {
                        if (size <= max_size)
                           memcpy((char *) destination + size, pdata, max_size - size);
                     } else
                        memcpy((char *) destination + size, pdata, total_size - size);
                  }
                  if (total_size < max_size)
                     *buf_size = total_size;
                  else
                     *buf_size = max_size;
                  /* now convert event header */
                  if (convert_flags) {
                     pevent = (EVENT_HEADER *) destination;
                     rpc_convert_single(&pevent->event_id, TID_SHORT, RPC_OUTGOING,
                                        convert_flags);
                     rpc_convert_single(&pevent->trigger_mask, TID_SHORT, RPC_OUTGOING,
                                        convert_flags);
                     rpc_convert_single(&pevent->serial_number, TID_DWORD, RPC_OUTGOING,
                                        convert_flags);
                     rpc_convert_single(&pevent->time_stamp, TID_DWORD, RPC_OUTGOING,
                                        convert_flags);
                     rpc_convert_single(&pevent->data_size, TID_DWORD, RPC_OUTGOING,
                                        convert_flags);
                  }
               }
               if (pbuf->read_cache_size > 0 &&
                   !(total_size > pbuf->read_cache_size && pbuf->read_cache_wp == 0)) {
                  pbuf->read_cache_wp += total_size;
               } else {
                  if (total_size > max_size) {
                     cm_msg(MERROR, "bm_receive_event",
                            "event size larger than buffer size");
                     status = BM_TRUNCATED;
                  } else
                     status = BM_SUCCESS;
               }
               /* update statistics */
               found = TRUE;
               pheader->num_out_events++;
               break;
            }
         old_read_pointer = pc->read_pointer;
         /* shift read pointer */
         new_read_pointer = (pc->read_pointer + total_size) % pheader->size;
         if (new_read_pointer > pheader->size - (int) sizeof(EVENT_HEADER))
            new_read_pointer = 0;
#ifdef DEBUG_MSG
         cm_msg(MDEBUG, "bm_receive_event -> wp=%d, rp %d -> %d (found=%d,size=%d)",
                pheader->write_pointer, pc->read_pointer, new_read_pointer, found,
                total_size);
#endif
         pc->read_pointer = new_read_pointer;
         /*
            Repeat until a requested event is found or no more events
            are available.
          */
         if (pbuf->read_cache_size == 0 && found)
            break;
         /* break if event has bypassed read cache */
         if (pbuf->read_cache_size > 0 &&
             total_size > pbuf->read_cache_size && pbuf->read_cache_wp == 0)
            break;
      } while (pheader->write_pointer != pc->read_pointer);
    CACHE_FULL:
      /* calculate global read pointer as "minimum" of client read pointers */
      min_wp = pheader->write_pointer;
      for (i = 0, pctmp = pclient; i < pheader->max_client_index; i++, pctmp++)
         if (pctmp->pid) {
            if (pctmp->read_pointer < min_wp)
               min_wp = pctmp->read_pointer;
            if (pctmp->read_pointer > pheader->write_pointer &&
                pctmp->read_pointer - pheader->size < min_wp)
               min_wp = pctmp->read_pointer - pheader->size;
         }
      if (min_wp < 0)
         min_wp += pheader->size;
      pheader->read_pointer = min_wp;
      /*
         If read pointer has been changed, it may have freed up some space
         for waiting producers. So check if free space is now more than 50%
         of the buffer size and wake waiting producers.
       */
      size = pc->read_pointer - pheader->write_pointer;
      if (size <= 0)
         size += pheader->size;
      if (size >= pheader->size * 0.5)
         for (i = 0, pctmp = pclient; i < pheader->max_client_index; i++, pctmp++)
            if (pctmp->pid && (pctmp->write_wait < size) && (pctmp->pid != ss_getpid() ||       /* check if not own thread */
                                                             (pctmp->pid == ss_getpid()
                                                              && pctmp->tid !=
                                                              ss_gettid()))) {
#ifdef DEBUG_MSG
               cm_msg(MDEBUG, "Receive wake: rp=%d, wp=%d, level=%1.1lf",
                      pheader->read_pointer,
                      pheader->write_pointer, 100 - 100.0 * size / pheader->size);
#endif
               ss_resume(pctmp->port, "B  ");
            }
      /* if no matching event found, start again */
      if (!found)
         goto LOOP;
      bm_unlock_buffer(buffer_handle);
      if (pbuf->read_cache_size > 0 &&
          !(total_size > pbuf->read_cache_size && pbuf->read_cache_wp == 0))
         goto CACHE_READ;
      return status;
   }
#else                           /* LOCAL_ROUTINES */
   return SS_SUCCESS;
#endif
}
INT bm_remove_event_request (INT buffer_handle, INT request_id)
Delete a previously placed request for a specific event type in the client structure of the buffer refereced by buffer_handle.
Parameters:
buffer_handle Handle to the buffer where the re- quest should be placed in
request_id Request id returned by bm_request_event
Returns:
BM_SUCCESS, BM_INVALID_HANDLE, BM_NOT_FOUND, RPC_NET_ERROR
Definition at line 5920 of file midas.c.
References _buffer_entries, BUFFER_CLIENT::all_flag, BM_INVALID_HANDLE, bm_lock_buffer(), BM_NOT_FOUND, BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER::client_index, cm_msg, BUFFER_CLIENT::event_request, FALSE, GET_ALL, i, EVENT_REQUEST::id, MAX_EVENT_REQUESTS, BUFFER_CLIENT::max_request_index, MERROR, RPC_BM_REMOVE_EVENT_REQUEST, rpc_call(), rpc_is_remote(), EVENT_REQUEST::sampling_type, TRUE, and EVENT_REQUEST::valid.
Referenced by bm_delete_request(), and rpc_server_dispatch().
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_REMOVE_EVENT_REQUEST, buffer_handle, request_id);
#ifdef LOCAL_ROUTINES
   {
      INT i, deleted;
      BUFFER_CLIENT *pclient;
      if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
         cm_msg(MERROR, "bm_remove_event_request", "invalid buffer handle %d",
                buffer_handle);
         return BM_INVALID_HANDLE;
      }
      if (!_buffer[buffer_handle - 1].attached) {
         cm_msg(MERROR, "bm_remove_event_request", "invalid buffer handle %d",
                buffer_handle);
         return BM_INVALID_HANDLE;
      }
      /* get a pointer to the proper client structure */
      pclient = &(_buffer[buffer_handle - 1].buffer_header->
                  client[_buffer[buffer_handle - 1].client_index]);
      /* lock buffer */
      bm_lock_buffer(buffer_handle);
      /* check all requests and set to zero if matching */
      for (i = 0, deleted = 0; i < pclient->max_request_index; i++)
         if (pclient->event_request[i].valid &&
             pclient->event_request[i].id == request_id) {
            memset(&pclient->event_request[i], 0, sizeof(EVENT_REQUEST));
            deleted++;
         }
      /* calculate new max_request_index entry */
      for (i = MAX_EVENT_REQUESTS - 1; i >= 0; i--)
         if (pclient->event_request[i].valid)
            break;
      pclient->max_request_index = i + 1;
      /* caluclate new all_flag */
      pclient->all_flag = FALSE;
      for (i = 0; i < pclient->max_request_index; i++)
         if (pclient->event_request[i].valid &&
             (pclient->event_request[i].sampling_type & GET_ALL)) {
            pclient->all_flag = TRUE;
            break;
         }
      bm_unlock_buffer(buffer_handle);
      if (!deleted)
         return BM_NOT_FOUND;
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_request_event (HNDLE buffer_handle, short int event_id, short int trigger_mask, INT sampling_type, HNDLE * request_id, void(*)(HNDLE, HNDLE, EVENT_HEADER *, void *) func)
dox Place an event request based on certain characteristics. Multiple event requests can be placed for each buffer, which are later identified by their request ID. They can contain different callback routines. Example see bm_open_buffer() and bm_receive_event()
Parameters:
buffer_handle buffer handle obtained via bm_open_buffer()
event_id event ID for requested events. Use EVENTID_ALL to receive events with any ID.
trigger_mask trigger mask for requested events. The requested events must have at least one bit in its trigger mask common with the requested trigger mask. Use TRIGGER_ALL to receive events with any trigger mask.
sampling_type specifies how many events to receive. A value of GET_ALL receives all events which match the specified event ID and trigger mask. If the events are consumed slower than produced, the producer is automatically slowed down. A value of GET_SOME receives as much events as possible without slowing down the producer. GET_ALL is typically used by the logger, while GET_SOME is typically used by analyzers.
request_id request ID returned by the function. This ID is passed to the callback routine and must be used in the bm_delete_request() routine.
func allback routine which gets called when an event of the specified type is received.
Returns:
BM_SUCCESS, BM_INVALID_HANDLE
BM_NO_MEMORY too many requests. The value MAX_EVENT_REQUESTS in midas.h should be increased.
Definition at line 5852 of file midas.c.
References _request_list_entries, bm_add_event_request(), BM_NO_MEMORY, BM_SUCCESS, REQUEST_LIST::buffer_handle, cm_msg, REQUEST_LIST::dispatcher, REQUEST_LIST::event_id, index, M_MALLOC, MERROR, status, and REQUEST_LIST::trigger_mask.
{
   INT index, status;
   /* allocate new space for the local request list */
   if (_request_list_entries == 0) {
      _request_list = (REQUEST_LIST *) M_MALLOC(sizeof(REQUEST_LIST));
      memset(_request_list, 0, sizeof(REQUEST_LIST));
      if (_request_list == NULL) {
         cm_msg(MERROR, "bm_request_event",
                "not enough memory to allocate request list buffer");
         return BM_NO_MEMORY;
      }
      _request_list_entries = 1;
      index = 0;
   } else {
      /* check for a deleted entry */
      for (index = 0; index < _request_list_entries; index++)
         if (!_request_list[index].buffer_handle)
            break;
      /* if not found, create new one */
      if (index == _request_list_entries) {
         _request_list = (REQUEST_LIST *) realloc(_request_list,
                                                  sizeof(REQUEST_LIST) *
                                                  (_request_list_entries + 1));
         if (_request_list == NULL) {
            cm_msg(MERROR, "bm_request_event",
                   "not enough memory to allocate request list buffer");
            return BM_NO_MEMORY;
         }
         memset(&_request_list[_request_list_entries], 0, sizeof(REQUEST_LIST));
         _request_list_entries++;
      }
   }
   /* initialize request list */
   _request_list[index].buffer_handle = buffer_handle;
   _request_list[index].event_id = event_id;
   _request_list[index].trigger_mask = trigger_mask;
   _request_list[index].dispatcher = func;
   *request_id = index;
   /* add request in buffer structure */
   status = bm_add_event_request(buffer_handle, event_id, trigger_mask,
                                 sampling_type, func, index);
   if (status != BM_SUCCESS)
      return status;
   return BM_SUCCESS;
}
INT bm_send_event (INT buffer_handle, void * source, INT buf_size, INT async_flag)
Sends an event to a buffer. This function check if the buffer has enough space for the event, then copies the event to the buffer in shared memory. If clients have requests for the event, they are notified via an UDP packet.
char event[1000];
// create event with ID 1, trigger mask 0, size 100 bytes and serial number 1
bm_compose_event((EVENT_HEADER *) event, 1, 0, 100, 1);
// set first byte of event
*(event+sizeof(EVENT_HEADER)) = <...>
#include <stdio.h>
#include "midas.h"
main()
{
 INT status, i;
 HNDLE hbuf;
 char event[1000];
 status = cm_connect_experiment("", "Sample", "Producer", NULL);
 if (status != CM_SUCCESS)
 return 1;
 bm_open_buffer(EVENT_BUFFER_NAME, EVENT_BUFFER_SIZE, &hbuf);
 // create event with ID 1, trigger mask 0, size 100 bytes and serial number 1
 bm_compose_event((EVENT_HEADER *) event, 1, 0, 100, 1);
 // set event data
 for (i=0 ; i<100 ; i++)
 *(event+sizeof(EVENT_HEADER)+i) = i;
 // send event
 bm_send_event(hbuf, event, 100+sizeof(EVENT_HEADER), SYNC);
 cm_disconnect_experiment();
 return 0;
}
Parameters:
buffer_handle Buffer handle obtained via bm_open_buffer()
source Address of event buffer
buf_size Size of event including event header in bytes
async_flag Synchronous/asynchronous flag. If FALSE, the function blocks if the buffer has not enough free space to receive the event. If TRUE, the function returns immediately with a value of BM_ASYNC_RETURN without writing the event to the buffer
Returns:
BM_SUCCESS, BM_INVALID_HANDLE, BM_INVALID_PARAM
BM_ASYNC_RETURN Routine called with async_flag == TRUE and buffer has not enough space to receive event
BM_NO_MEMORY Event is too large for network buffer or event buffer. One has to increase MAX_EVENT_SIZE or EVENT_BUFFER_SIZE in midas.h and recompile.
Definition at line 6057 of file midas.c.
References _buffer_entries, ALIGN8, BUFFER::attached, BM_ASYNC_RETURN, bm_flush_cache(), BM_INVALID_HANDLE, BM_INVALID_PARAM, bm_lock_buffer(), bm_match_event(), BM_NO_MEMORY, BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER_HEADER::client, BUFFER::client_index, cm_msg, data_size, EVENT_REQUEST::event_id, BUFFER_CLIENT::event_request, FALSE, GET_ALL, i, EVENT_REQUEST::id, if, increment, j, BUFFER_HEADER::max_client_index, MAX_EVENT_SIZE, BUFFER_CLIENT::max_request_index, MDEBUG, MERROR, MSG_BM, BUFFER_HEADER::name, BUFFER_HEADER::num_in_events, BUFFER_CLIENT::num_waiting_events, BUFFER_CLIENT::pid, BUFFER_CLIENT::port, BUFFER_CLIENT::read_pointer, BUFFER_HEADER::read_pointer, BUFFER_CLIENT::read_wait, RPC_BM_SEND_EVENT, rpc_call(), rpc_is_remote(), EVENT_REQUEST::sampling_type, BUFFER_HEADER::size, size, SS_ABORT, ss_resume(), ss_suspend(), status, EVENT_REQUEST::trigger_mask, TRUE, EVENT_REQUEST::valid, BUFFER::write_cache, BUFFER::write_cache_size, BUFFER::write_cache_wp, BUFFER_HEADER::write_pointer, and BUFFER_CLIENT::write_wait.
Referenced by cm_msg(), cm_msg1(), dm_pointer_increment(), eb_increment_pointer(), rpc_end_of_cycle(), rpc_send_event(), rpc_server_dispatch(), rpc_server_receive(), scheduler(), send_event(), and yb_file_fragment().
{
   EVENT_HEADER *pevent;
   /* check if event size defined in header matches buf_size */
   if (ALIGN8(buf_size) != (INT) ALIGN8(((EVENT_HEADER *) source)->data_size +
                                      sizeof(EVENT_HEADER))) {
      cm_msg(MERROR, "bm_send_event", "event size (%d) mismatch in header (%d)",
             ALIGN8(buf_size), (INT) ALIGN8(((EVENT_HEADER *) source)->data_size +
                                          sizeof(EVENT_HEADER)));
      return BM_INVALID_PARAM;
   }
   /* check for maximal event size */
   if (((EVENT_HEADER *) source)->data_size > MAX_EVENT_SIZE) {
      cm_msg(MERROR, "bm_send_event",
             "event size (%d) larger than maximum event size (%d)",
             ((EVENT_HEADER *) source)->data_size, MAX_EVENT_SIZE);
      return BM_NO_MEMORY;
   }
   if (rpc_is_remote())
      return rpc_call(RPC_BM_SEND_EVENT, buffer_handle, source, buf_size, async_flag);
#ifdef LOCAL_ROUTINES
   {
      BUFFER *pbuf;
      BUFFER_HEADER *pheader;
      BUFFER_CLIENT *pclient, *pc;
      EVENT_REQUEST *prequest;
      EVENT_HEADER *pevent_test;
      INT i, j, min_wp, size, total_size, status;
      INT increment;
      INT my_client_index;
      INT old_write_pointer;
      INT old_read_pointer, new_read_pointer;
      INT num_requests_client;
      char *pdata;
      BOOL blocking;
      INT n_blocking;
      INT request_id;
      char str[80];
      pbuf = &_buffer[buffer_handle - 1];
      if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
         cm_msg(MERROR, "bm_send_event", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      if (!pbuf->attached) {
         cm_msg(MERROR, "bm_send_event", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      pevent = (EVENT_HEADER *) source;
      total_size = buf_size;
      /* round up total_size to next DWORD boundary */
      total_size = ALIGN8(total_size);
      /* look if there is space in the cache */
      if (pbuf->write_cache_size) {
         status = BM_SUCCESS;
         if (pbuf->write_cache_size - pbuf->write_cache_wp < total_size)
            status = bm_flush_cache(buffer_handle, async_flag);
         if (status != BM_SUCCESS)
            return status;
         if (total_size < pbuf->write_cache_size) {
            memcpy(pbuf->write_cache + pbuf->write_cache_wp, source, total_size);
            pbuf->write_cache_wp += total_size;
            return BM_SUCCESS;
         }
      }
      /* calculate some shorthands */
      pheader = _buffer[buffer_handle - 1].buffer_header;
      pdata = (char *) (pheader + 1);
      my_client_index = _buffer[buffer_handle - 1].client_index;
      pclient = pheader->client;
      /* check if buffer is large enough */
      if (total_size >= pheader->size) {
         cm_msg(MERROR, "bm_send_event",
                "total event size (%d) larger than buffer size (%d)", total_size,
                pheader->size);
         return BM_NO_MEMORY;
      }
      /* lock the buffer */
      bm_lock_buffer(buffer_handle);
      /* check if enough space in buffer left */
      do {
         size = pheader->read_pointer - pheader->write_pointer;
         if (size <= 0)
            size += pheader->size;
         if (size <= total_size) {      /* note the '<=' to avoid 100% filling */
            /* if not enough space, find out who's blocking */
            n_blocking = 0;
            for (i = 0, pc = pclient; i < pheader->max_client_index; i++, pc++)
               if (pc->pid) {
                  if (pc->read_pointer == pheader->read_pointer) {
                     /*
                        First assume that the client with the "minimum" read pointer
                        is not really blocking due to a GET_ALL request.
                      */
                     blocking = FALSE;
                     request_id = -1;
                     /* check if this request blocks */
                     prequest = pc->event_request;
                     pevent_test = (EVENT_HEADER *) (pdata + pc->read_pointer);
                     for (j = 0; j < pc->max_request_index; j++, prequest++)
                        if (prequest->valid &&
                            bm_match_event(prequest->event_id, prequest->trigger_mask,
                                           pevent_test)) {
                           request_id = prequest->id;
                           if (prequest->sampling_type & GET_ALL) {
                              blocking = TRUE;
                              break;
                           }
                        }
                     if (!blocking) {
                        /*
                           The blocking guy has no GET_ALL request for this event
                           -> shift its read pointer.
                         */
                        old_read_pointer = pc->read_pointer;
                        increment = sizeof(EVENT_HEADER) +
                            ((EVENT_HEADER *) (pdata + pc->read_pointer))->data_size;
                        /* correct increment for DWORD boundary */
                        increment = ALIGN8(increment);
                        new_read_pointer = (pc->read_pointer + increment) % pheader->size;
                        if (new_read_pointer > pheader->size - (int) sizeof(EVENT_HEADER))
                           new_read_pointer = 0;
                        pc->read_pointer = new_read_pointer;
                     } else {
                        n_blocking++;
                     }
                     /* wake that client if it has a request */
                     if (pc->read_wait && request_id != -1) {
#ifdef DEBUG_MSG
                        cm_msg(MDEBUG, "Send wake: rp=%d, wp=%d",
                               pheader->read_pointer, pheader->write_pointer);
#endif
                        sprintf(str, "B %s %d", pheader->name, request_id);
                        ss_resume(pc->port, str);
                     }
                  }             /* read_pointer blocks */
               }
            /* client loop */
            if (n_blocking > 0) {
               /* at least one client is blocking */
               bm_unlock_buffer(buffer_handle);
               /* return now in ASYNC mode */
               if (async_flag)
                  return BM_ASYNC_RETURN;
#ifdef DEBUG_MSG
               cm_msg(MDEBUG, "Send sleep: rp=%d, wp=%d, level=%1.1lf",
                      pheader->read_pointer,
                      pheader->write_pointer, 100 - 100.0 * size / pheader->size);
#endif
               /* has the read pointer moved in between ? */
               size = pheader->read_pointer - pheader->write_pointer;
               if (size <= 0)
                  size += pheader->size;
               /* suspend process */
               if (size <= total_size) {
                  /* signal other clients wait mode */
                  pclient[my_client_index].write_wait = total_size;
                  status = ss_suspend(1000, MSG_BM);
                  pclient[my_client_index].write_wait = 0;
                  /* return if TCP connection broken */
                  if (status == SS_ABORT)
                     return SS_ABORT;
               }
#ifdef DEBUG_MSG
               cm_msg(MDEBUG, "Send woke up: rp=%d, wp=%d, level=%1.1lf",
                      pheader->read_pointer,
                      pheader->write_pointer, 100 - 100.0 * size / pheader->size);
#endif
               bm_lock_buffer(buffer_handle);
               /* has the write pointer moved in between ? */
               size = pheader->read_pointer - pheader->write_pointer;
               if (size <= 0)
                  size += pheader->size;
            } else {
               /*
                  calculate new global read pointer as "minimum" of
                  client read pointers
                */
               min_wp = pheader->write_pointer;
               for (i = 0, pc = pclient; i < pheader->max_client_index; i++, pc++)
                  if (pc->pid) {
                     if (pc->read_pointer < min_wp)
                        min_wp = pc->read_pointer;
                     if (pc->read_pointer > pheader->write_pointer &&
                         pc->read_pointer - pheader->size < min_wp)
                        min_wp = pc->read_pointer - pheader->size;
                  }
               if (min_wp < 0)
                  min_wp += pheader->size;
               pheader->read_pointer = min_wp;
            }
         }
         /* if (size <= total_size) */
      } while (size <= total_size);
      /* we have space, so let's copy the event */
      old_write_pointer = pheader->write_pointer;
      if (pheader->write_pointer + total_size <= pheader->size) {
         memcpy(pdata + pheader->write_pointer, pevent, total_size);
         pheader->write_pointer = (pheader->write_pointer + total_size) % pheader->size;
         if (pheader->write_pointer > pheader->size - (int) sizeof(EVENT_HEADER))
            pheader->write_pointer = 0;
      } else {
         /* split event */
         size = pheader->size - pheader->write_pointer;
         memcpy(pdata + pheader->write_pointer, pevent, size);
         memcpy(pdata, (char *) pevent + size, total_size - size);
         pheader->write_pointer = total_size - size;
      }
      /* check which clients have a request for this event */
      for (i = 0; i < pheader->max_client_index; i++)
         if (pclient[i].pid) {
            prequest = pclient[i].event_request;
            num_requests_client = 0;
            request_id = -1;
            for (j = 0; j < pclient[i].max_request_index; j++, prequest++)
               if (prequest->valid &&
                   bm_match_event(prequest->event_id, prequest->trigger_mask, pevent)) {
                  if (prequest->sampling_type & GET_ALL)
                     pclient[i].num_waiting_events++;
                  num_requests_client++;
                  request_id = prequest->id;
               }
            /* if that client has a request and is suspended, wake it up */
            if (num_requests_client && pclient[i].read_wait) {
#ifdef DEBUG_MSG
               cm_msg(MDEBUG, "Send wake: rp=%d, wp=%d", pheader->read_pointer,
                      pheader->write_pointer);
#endif
               sprintf(str, "B %s %d", pheader->name, request_id);
               ss_resume(pclient[i].port, str);
            }
            /* if that client has no request, shift its read pointer */
            if (num_requests_client == 0 && pclient[i].read_pointer == old_write_pointer)
               pclient[i].read_pointer = pheader->write_pointer;
         }
      /* shift read pointer of own client */
/* 16.4.99 SR, outcommented to receive own messages
  if (pclient[my_client_index].read_pointer == old_write_pointer)
    pclient[my_client_index].read_pointer = pheader->write_pointer;
*/
      /* calculate global read pointer as "minimum" of client read pointers */
      min_wp = pheader->write_pointer;
      for (i = 0, pc = pclient; i < pheader->max_client_index; i++, pc++)
         if (pc->pid) {
            if (pc->read_pointer < min_wp)
               min_wp = pc->read_pointer;
            if (pc->read_pointer > pheader->write_pointer &&
                pc->read_pointer - pheader->size < min_wp)
               min_wp = pc->read_pointer - pheader->size;
         }
      if (min_wp < 0)
         min_wp += pheader->size;
#ifdef DEBUG_MSG
      if (min_wp == pheader->read_pointer)
         cm_msg(MDEBUG, "bm_send_event -> wp=%d", pheader->write_pointer);
      else
         cm_msg(MDEBUG, "bm_send_event -> wp=%d, rp %d -> %d, size=%d",
                pheader->write_pointer, pheader->read_pointer, min_wp, size);
#endif
      pheader->read_pointer = min_wp;
      /* update statistics */
      pheader->num_in_events++;
      /* unlock the buffer */
      bm_unlock_buffer(buffer_handle);
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_set_cache_size (INT buffer_handle, INT read_size, INT write_size)
Modifies buffer cache size. Without a buffer cache, events are copied to/from the shared memory event by event.
To protect processed from accessing the shared memory simultaneously, semaphores are used. Since semaphore operations are CPU consuming (typically 50-100us) this can slow down the data transfer especially for small events. By using a cache the number of semaphore operations is reduced dramatically. Instead writing directly to the shared memory, the events are copied to a local cache buffer. When this buffer is full, it is copied to the shared memory in one operation. The same technique can be used when receiving events.
The drawback of this method is that the events have to be copied twice, once to the cache and once from the cache to the shared memory. Therefore it can happen that the usage of a cache even slows down data throughput on a given environment (computer type, OS type, event size). The cache size has therefore be optimized manually to maximize data throughput.
Parameters:
buffer_handle buffer handle obtained via bm_open_buffer()
read_size cache size for reading events in bytes, zero for no cache
write_size cache size for writing events in bytes, zero for no cache
Returns:
BM_SUCCESS, BM_INVALID_HANDLE, BM_NO_MEMORY, BM_INVALID_PARAM
Definition at line 5589 of file midas.c.
References _buffer_entries, BM_INVALID_HANDLE, BM_INVALID_PARAM, BM_NO_MEMORY, BM_SUCCESS, cm_msg, M_FREE, M_MALLOC, MERROR, BUFFER::read_cache, BUFFER::read_cache_rp, BUFFER::read_cache_size, BUFFER::read_cache_wp, RPC_BM_SET_CACHE_SIZE, rpc_call(), rpc_is_remote(), BUFFER::write_cache, BUFFER::write_cache_rp, BUFFER::write_cache_size, and BUFFER::write_cache_wp.
Referenced by main(), register_equipment(), register_requests(), rpc_server_dispatch(), tr_start(), and tr_start1().
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_SET_CACHE_SIZE, buffer_handle, read_size, write_size);
#ifdef LOCAL_ROUTINES
   {
      BUFFER *pbuf;
      if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
         cm_msg(MERROR, "bm_set_cache_size", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      if (!_buffer[buffer_handle - 1].attached) {
         cm_msg(MERROR, "bm_set_cache_size", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      if (read_size < 0 || read_size > 1E6) {
         cm_msg(MERROR, "bm_set_cache_size", "invalid read chache size");
         return BM_INVALID_PARAM;
      }
      if (write_size < 0 || write_size > 1E6) {
         cm_msg(MERROR, "bm_set_cache_size", "invalid write chache size");
         return BM_INVALID_PARAM;
      }
      /* manage read cache */
      pbuf = &_buffer[buffer_handle - 1];
      if (pbuf->read_cache_size > 0)
         M_FREE(pbuf->read_cache);
      if (read_size > 0) {
         pbuf->read_cache = (char *) M_MALLOC(read_size);
         if (pbuf->read_cache == NULL) {
            cm_msg(MERROR, "bm_set_cache_size",
                   "not enough memory to allocate cache buffer");
            return BM_NO_MEMORY;
         }
      }
      pbuf->read_cache_size = read_size;
      pbuf->read_cache_rp = pbuf->read_cache_wp = 0;
      /* manage write cache */
      if (pbuf->write_cache_size > 0)
         M_FREE(pbuf->write_cache);
      if (write_size > 0) {
         pbuf->write_cache = (char *) M_MALLOC(write_size);
         if (pbuf->write_cache == NULL) {
            cm_msg(MERROR, "bm_set_cache_size",
                   "not enough memory to allocate cache buffer");
            return BM_NO_MEMORY;
         }
      }
      pbuf->write_cache_size = write_size;
      pbuf->write_cache_rp = pbuf->write_cache_wp = 0;
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_skip_event (INT buffer_handle)
Skip all events in current buffer.
Useful for single event displays to see the newest events
Parameters:
buffer_handle Handle of the buffer. Must be obtained via bm_open_buffer.
Returns:
BM_SUCCESS, BM_INVALID_HANDLE, RPC_NET_ERROR
Definition at line 7109 of file midas.c.
References _buffer_entries, BUFFER::attached, BM_INVALID_HANDLE, bm_lock_buffer(), BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER_HEADER::client, BUFFER::client_index, cm_msg, MERROR, BUFFER::read_cache_rp, BUFFER::read_cache_wp, BUFFER_CLIENT::read_pointer, RPC_BM_SKIP_EVENT, rpc_call(), rpc_is_remote(), and BUFFER_HEADER::write_pointer.
Referenced by rpc_server_dispatch().
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_SKIP_EVENT, buffer_handle);
#ifdef LOCAL_ROUTINES
   {
      BUFFER *pbuf;
      BUFFER_HEADER *pheader;
      BUFFER_CLIENT *pclient;
      if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
         cm_msg(MERROR, "bm_skip_event", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      pbuf = &_buffer[buffer_handle - 1];
      pheader = pbuf->buffer_header;
      if (!pbuf->attached) {
         cm_msg(MERROR, "bm_skip_event", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      /* clear cache */
      if (pbuf->read_cache_wp > pbuf->read_cache_rp)
         pbuf->read_cache_rp = pbuf->read_cache_wp = 0;
      bm_lock_buffer(buffer_handle);
      /* forward read pointer to global write pointer */
      pclient = pheader->client + pbuf->client_index;
      pclient->read_pointer = pheader->write_pointer;
      bm_unlock_buffer(buffer_handle);
   }
#endif
   return BM_SUCCESS;
}
Variable Documentation
EVENT_DEFRAG_BUFFER defrag_buffer[MAX_DEFRAG_EVENTS]
Definition at line 7807 of file midas.c.