AlcapDAQ:Rootana: YBOS Bank Functions (ybk_xxx)
YBOS Bank Functions (ybk_xxx)
[The ybos.h & ybos.c]
Functions
void ybk_init (DWORD *plrl)
void ybk_create (DWORD *plrl, char *bkname, DWORD bktype, void *pbkdat)
void ybk_create_chaos (DWORD *plrl, char *bkname, DWORD bktype, void *pbkdat)
INT ybk_close_chaos (DWORD *plrl, DWORD bktype, void *pbkdat)
INT ybk_close (DWORD *plrl, void *pbkdat)
INT ybk_size (DWORD *plrl)
INT ybk_list (DWORD *plrl, char *bklist)
INT ybk_find (DWORD *plrl, char *bkname, DWORD *bklen, DWORD *bktype, void **pbk)
INT ybk_locate (DWORD *plrl, char *bkname, void *pdata)
INT ybk_iterate (DWORD *plrl, YBOS_BANK_HEADER **pybkh, void **pdata)
INT feodb_file_dump (EQUIPMENT *eqp, char *eqpname, char *pevent, INT run_number, char *path)
INT ybos_get_tid_size (INT tid)
INT ybos_log_open (LOG_CHN *log_chn, INT run_number)
INT ybos_write (LOG_CHN *log_chn, EVENT_HEADER *pevent, INT evt_size)
INT ybos_log_close (LOG_CHN *log_chn, INT run_number)
INT yb_any_file_ropen (char *infile, INT data_fmt)
INT yb_any_file_rclose (INT data_fmt)
INT yb_any_file_wopen (INT type, INT data_fmt, char *filename, INT *hDev)
INT yb_any_file_wclose (INT handle, INT type, INT data_fmt)
INT yb_any_physrec_get (INT data_fmt, void **precord, DWORD *readn)
INT yb_any_log_write (INT handle, INT data_fmt, INT type, void *prec, DWORD nbytes)
INT yb_any_physrec_skip (INT data_fmt, INT bl)
INT yb_any_physrec_display (INT data_fmt)
INT yb_any_all_info_display (INT what)
INT yb_any_event_swap (INT data_fmt, void *pevent)
INT yb_any_event_get (INT data_fmt, void **pevent, DWORD *readn)
INT ybos_event_get (DWORD **plrl, DWORD *readn)
void yb_any_event_display (void *pevent, INT data_fmt, INT dsp_mode, INT dsp_fmt)
void yb_any_bank_display (void *pmbh, void *pbk, INT data_fmt, INT dsp_mode, INT dsp_fmt)
INT yb_file_recompose (void *pevt, INT format, char *svpath, INT file_mode)
INT ybos_event_swap (DWORD *pevt)
Variables
static YBOS_BANK_HEADER * __pbkh
static DWORD * __pchaosi4
Detailed Description
dox
dox dox
Function Documentation
INT feodb_file_dump (EQUIPMENT * eqp, char * eqpname, char * pevent, INT run_number, char * path)
dox
Definition at line 796 of file ybos.c.
References cm_get_experiment_database(), cm_msg, db_enum_key(), db_find_key(), db_get_path(), db_get_value(), DB_INVALID_NAME, DB_NO_MORE_SUBKEYS, DB_SUCCESS, equal_ustring(), FALSE, hDB, hKey, index, MAX_FILE_PATH, MINFO, eqpmnt::name, size, status, TID_STRING, TRUE, yb_file_fragment(), and YB_SUCCESS.
Referenced by files_dump().
       : feodb_file_dump
Purpose: Access ODB for the /Equipment/<equip_name>/Dump.
in order to scan for file name and dump the files content to the
Midas buffer channel.
Input:
EQUIPMENT * eqp           Current equipment
INT       run_number      current run_number
char      * path          full file name specification
Output:
none
Function value:
0                      Successful completion
DB_INVALID_NAME        Equipment doesn't match request
\********************************************************************/
{
   EQUIPMENT *peqp;
   INT index, size, status;
   HNDLE hDB, hKey, hKeydump;
   char strpath[MAX_FILE_PATH], Dumpfile[MAX_FILE_PATH];
   char odb_entry[MAX_FILE_PATH];
   BOOL eqpfound = FALSE;
   cm_get_experiment_database(&hDB, &hKey);
   peqp = eqp;
   /* find the equipment info for this job */
   while (*(peqp->name) != 0) {
      if (equal_ustring((peqp->name), eqpname)) {
         eqpfound = TRUE;
         break;
      }
      peqp++;
   }
   if (!eqpfound)
      return DB_INVALID_NAME;
   /* loop over all channels */
   sprintf(odb_entry, "/Equipment/%s/Dump", path);
   status = db_find_key(hDB, 0, odb_entry, &hKey);
   if (status != DB_SUCCESS) {
      cm_msg(MINFO, "ybos_odb_file_dump", "odb_access_file -I- %s not found", odb_entry);
      return YB_SUCCESS;
   }
   index = 0;
   while ((status = db_enum_key(hDB, hKey, index, &hKeydump)) != DB_NO_MORE_SUBKEYS) {
      if (status == DB_SUCCESS) {
         size = sizeof(strpath);
         db_get_path(hDB, hKeydump, strpath, size);
         db_get_value(hDB, 0, strpath, Dumpfile, &size, TID_STRING, TRUE);
         yb_file_fragment(peqp, (EVENT_HEADER *) pevent, run_number, Dumpfile);
      }
      index++;
   }
   return (YB_SUCCESS);
}
INT yb_any_all_info_display (INT what)
Definition at line 2367 of file ybos.c.
References D_EVTLEN, D_HEADER, D_RECORD, FORMAT_MIDAS, FORMAT_YBOS, my, offset, run, YB_DONE, and YB_SUCCESS.
Referenced by replog(), and yb_any_physrec_display().
       : yb_any_all_info_display
Purpose: display on screen all the info about "what".
Input:
INT     what              type of display.
Output:
none
Function value:
INT                 YB_SUCCESS
YB_DONE
\********************************************************************/
{
   if (my.fmt == FORMAT_YBOS) {
      DWORD bz, hyl, ybn, of;
      bz = (my.pyh)->rec_size;
      hyl = (my.pyh)->header_length;
      ybn = (my.pyh)->rec_num;
      of = (my.pyh)->offset;
      switch (what) {
      case D_RECORD:
      case D_HEADER:
         printf("rec#%ld- ", my.recn);
         printf("%5ldbz %5ldhyl %5ldybn %5ldof\n", bz, hyl, ybn, of);
         break;
      case D_EVTLEN:
         printf("rec#%ld- ", my.recn);
         printf("%5ldbz %5ldhyl %5ldybn %5ldof ", bz, hyl, ybn, of);
         printf("%5ldel/x%lx %5ldev\n", my.evtlen, my.evtlen, my.evtn);
         break;
      }
   } else if (my.fmt == FORMAT_MIDAS) {
      DWORD mbn, run, ser;
      WORD id, msk;
      mbn = my.evtn;
      run = my.runn;
      id = my.pmh->event_id;
      msk = my.pmh->trigger_mask;
      ser = my.pmh->serial_number;
      switch (what) {
      case D_RECORD:
      case D_HEADER:
         printf(">>> No physical record structure for Midas format <<<\n");
         return YB_DONE;
         break;
      case D_EVTLEN:
         printf("Evt#%ld- ", my.evtn);
         printf("%lirun 0x%4.4uxid 0x%4.4uxmsk %5ldmevt#", run, id, msk, mbn);
         printf("%5ldel/x%lx %5ldserial\n", my.evtlen, my.evtlen, ser);
         break;
      }
   }
   return YB_SUCCESS;
}
void yb_any_bank_display (void * pmbh, void * pbk, INT data_fmt, INT dsp_mode, INT dsp_fmt)
Definition at line 2923 of file ybos.c.
References bk_is32(), DSP_RAW, FORMAT_MIDAS, FORMAT_YBOS, midas_bank_display(), midas_bank_display32(), yb_any_raw_bank_display(), and ybos_bank_display().
Referenced by process_event().
       : external yb_any_bank_display
Purpose: display on screen the given bank.
Input:
void * pbk          pointer to the bank
INT  data_fmt       YBOS or MIDAS
INT  dsp_mode       display mode (RAW/BANK)
INT  dsp_fmt        display format (DSP_DEC/HEX)
Output:
none
Function value:
none
\********************************************************************/
{
   if (dsp_mode == DSP_RAW)
      yb_any_raw_bank_display(pbk, data_fmt, dsp_fmt);
   else {
      if (data_fmt == FORMAT_MIDAS) {
         if (bk_is32(pmbh))
            midas_bank_display32((BANK32 *) pbk, dsp_fmt);
         else
            midas_bank_display((BANK *) pbk, dsp_fmt);
      } else if (data_fmt == FORMAT_YBOS)
         ybos_bank_display((YBOS_BANK_HEADER *) pbk, dsp_fmt);
   }
   return;
}
void yb_any_event_display (void * pevent, INT data_fmt, INT dsp_mode, INT dsp_fmt)
Definition at line 2757 of file ybos.c.
References DSP_BANK, DSP_RAW, yb_any_bank_event_display(), and yb_any_raw_event_display().
Referenced by process_event(), and replog().
       : external yb_any_event_display
Purpose: display on screen the YBOS event in either RAW or YBOS mode
and in either Decimal or Hexadecimal.
Input:
void *  pevent     pointer to either plrl or pheader.
INT     data_fmt   uses the YBOS or MIDAS event structure
INT     dsp_mode   display in RAW or Bank mode
INT     dsp_fmt    display format (DSP_DEC/HEX)
Output:
none
Function value:
none
\********************************************************************/
{
   if (dsp_mode == DSP_RAW)
      yb_any_raw_event_display(pevent, data_fmt, dsp_fmt);
   else if (dsp_mode == DSP_BANK)
      yb_any_bank_event_display(pevent, data_fmt, dsp_fmt);
   else
      printf("yb_any_event_display- Unknown format:%i\n", dsp_fmt);
   return;
}
INT yb_any_event_get (INT data_fmt, void ** pevent, DWORD * readn)
Definition at line 2544 of file ybos.c.
References FORMAT_MIDAS, FORMAT_YBOS, midas_event_get(), and ybos_event_get().
Referenced by replog().
       : external yb_any_event_get
Purpose: Retrieve an event from the given data format.
Input:
INT data_fmt :  YBOS or MIDAS
void ** pevent : either plrl or pheader
Output:
DWORD * readn : number of bytes read
Function value:
status : from lower function
\********************************************************************/
{
   INT status = 0;
   *pevent = NULL;
   if (data_fmt == FORMAT_MIDAS)
      status = midas_event_get(pevent, readn);
   else if (data_fmt == FORMAT_YBOS)
      status = ybos_event_get((DWORD **) pevent, readn);
   return (status);
}
INT yb_any_event_swap (INT data_fmt, void * pevent)
Definition at line 2424 of file ybos.c.
References bk_swap(), CM_SUCCESS, event_id, EVENTID_BOR, EVENTID_EOR, EVENTID_MESSAGE, FALSE, FORMAT_MIDAS, FORMAT_YBOS, SS_SUCCESS, YB_EVENT_NOT_SWAPPED, YB_SUCCESS, YB_UNKNOWN_FORMAT, and ybos_event_swap().
Referenced by ma_read_event(), process_event(), and replog().
       : external yb_any_event_swap
Purpose: Swap an event from the given data format.
Input:
INT data_fmt  : YBOS or MIDAS
void * pevent : pointer to either plrl or pheader
Output:
none
Function value:
status :  from the lower function
\********************************************************************/
{
   INT status;
   BANK_HEADER *pbh;
   if (data_fmt == FORMAT_MIDAS) {
      if ((((EVENT_HEADER *) pevent)->event_id == EVENTID_BOR) ||
          (((EVENT_HEADER *) pevent)->event_id == EVENTID_EOR) ||
          (((EVENT_HEADER *) pevent)->event_id == EVENTID_MESSAGE))
         return SS_SUCCESS;
      pbh = (BANK_HEADER *) (((EVENT_HEADER *) pevent) + 1);
      status = bk_swap(pbh, FALSE);
      return status == CM_SUCCESS ? YB_EVENT_NOT_SWAPPED : YB_SUCCESS;
   } else if (data_fmt == FORMAT_YBOS) {
      status = ybos_event_swap((DWORD *) pevent);
      return status == YB_EVENT_NOT_SWAPPED ? YB_SUCCESS : status;
   }
   return YB_UNKNOWN_FORMAT;
}
INT yb_any_file_rclose (INT data_fmt)
Definition at line 1668 of file ybos.c.
References LOG_TYPE_DISK, LOG_TYPE_TAPE, my, and YB_SUCCESS.
Referenced by lazy_copy(), ma_close(), and replog().
       : external yb_any_file_rclose
Purpose: Close a data file used for replay for the given data format
Input:
INT data_fmt :  YBOS or MIDAS
Output:
none
Function value:
status : from lower function
*******************************************************************/
{
   switch (my.type) {
   case LOG_TYPE_TAPE:
   case LOG_TYPE_DISK:
      /* close file */
      if (my.zipfile) {
#ifdef INCLUDE_ZLIB
         gzclose(filegz);
#endif
      } else {
         if (my.handle != 0)
            close(my.handle);
      }
      break;
   }
   if (my.pmagta != NULL)
      free(my.pmagta);
   if (my.pyh != NULL)
      free(my.pyh);
   if (my.pylrl != NULL)
      free(my.pylrl);
   if (my.pmrd != NULL)
      free(my.pmrd);
   if (my.pmp != NULL)
      free(my.pmp);
   my.pylrl = NULL;
   my.pyh = NULL;
   my.pmagta = NULL;
   my.pmp = NULL;
   my.pmh = NULL;
   my.pmrd = NULL;
   return (YB_SUCCESS);
}
INT yb_any_file_ropen (char * infile, INT data_fmt)
Definition at line 1559 of file ybos.c.
References cm_msg, FALSE, FORMAT_MIDAS, FORMAT_YBOS, if, LOG_TYPE_DISK, LOG_TYPE_TAPE, MAX_EVENT_SIZE, MERROR, my, O_BINARY, O_LARGEFILE, offset, ptopmrd, SS_FILE_ERROR, SS_NO_MEMORY, ss_tape_open(), status, TAPE_BUFFER_SIZE, TRUE, YB_SUCCESS, YBOS_HEADER_LENGTH, and YBOS_PHYREC_SIZE.
Referenced by lazy_copy(), ma_open(), and replog().
       : external yb_any_file_ropen
Purpose: Open data file for replay for the given data format.
It uses the local "my" structure.
Input:
INT data_fmt :  YBOS or MIDAS
char * infile : Data file name
Output:
none
Function value:
status : from lower function
\********************************************************************/
{
   INT status;
   /* fill up record with file name */
   strcpy(my.name, infile);
   /* find out what dev it is ? : check on /dev */
   my.zipfile = FALSE;
   if ((strncmp(my.name, "/dev", 4) == 0) || (strncmp(my.name, "\\\\.\\", 4) == 0)) {
      /* tape device */
      my.type = LOG_TYPE_TAPE;
   } else {
      /* disk device */
      my.type = LOG_TYPE_DISK;
      if (strncmp(infile + strlen(infile) - 3, ".gz", 3) == 0)
         my.zipfile = TRUE;
   }
   /* open file */
   if (!my.zipfile) {
      if (my.type == LOG_TYPE_TAPE) {
         status = ss_tape_open(my.name, O_RDONLY | O_BINARY, &my.handle);
      }
      else if ((my.handle = open(my.name, O_RDONLY | O_BINARY | O_LARGEFILE, 0644)) == -1)
      {
         printf("dev name :%s Handle:%d \n", my.name, my.handle);
         return (SS_FILE_ERROR);
      }
   } else {
#ifdef INCLUDE_ZLIB
      if (my.type == LOG_TYPE_TAPE) {
         printf(" Zip on tape not yet supported \n");
         return (SS_FILE_ERROR);
      }
      filegz = gzopen(my.name, "rb");
      my.handle = 0;
      if (filegz == NULL) {
         printf("dev name :%s gzopen error:%d \n", my.name, my.handle);
         return (SS_FILE_ERROR);
      }
#else
      cm_msg(MERROR, "ybos.c", "Zlib not included ... gz file not supported");
      return (SS_FILE_ERROR);
#endif
   }
   if (data_fmt == FORMAT_YBOS) {
      my.fmt = FORMAT_YBOS;
      my.size = YBOS_PHYREC_SIZE;       /* in DWORD  */
      my.pmagta = (char *) malloc(32);
      if (my.pmagta == NULL)
         return SS_NO_MEMORY;
      my.pyh = (YBOS_PHYSREC_HEADER *) malloc(my.size * 14);
      if (my.pyh == NULL)
         return SS_NO_MEMORY;
      (my.pyh)->rec_size = my.size - 1;
      (my.pyh)->header_length = YBOS_HEADER_LENGTH;
      (my.pyh)->rec_num = 0;
      (my.pyh)->offset = 0;
      /* current ptr in the physical record */
      my.pyrd = (DWORD *) ((DWORD *) my.pyh + (my.pyh)->offset);
      /* allocate memory for one full event */
      my.pylrl = (DWORD *) malloc(MAX_EVENT_SIZE);      /* in bytes */
      if (my.pylrl == NULL)
         return SS_NO_MEMORY;
      memset((char *) my.pylrl, -1, MAX_EVENT_SIZE);
      /* reset first path */
      my.magtafl = FALSE;
   } else if (data_fmt == FORMAT_MIDAS) {
      my.fmt = FORMAT_MIDAS;
      my.size = TAPE_BUFFER_SIZE;
      my.pmp = (char *) malloc(my.size);
      if (my.pmp == NULL)
         return SS_NO_MEMORY;
      my.pme = (EVENT_HEADER *) my.pmp;
      /* allocate memory for one full event */
      if (my.pmrd != NULL)
         free(my.pmrd);
      my.pmrd = (char *) malloc(5 * MAX_EVENT_SIZE);    /* in bytes */
      ptopmrd = my.pmrd;
      if (my.pmrd == NULL)
         return SS_NO_MEMORY;
      memset((char *) my.pmrd, -1, 5 * MAX_EVENT_SIZE);
      my.pmh = (EVENT_HEADER *) my.pmrd;
   }
   /* initialize pertinent variables */
   my.recn = (DWORD) - 1;       /* physical record number */
   my.evtn = 0;
   return (YB_SUCCESS);
}
INT yb_any_file_wclose (INT handle, INT type, INT data_fmt)
Definition at line 1847 of file ybos.c.
References ftp_bye(), ftp_close(), LOG_TYPE_DISK, LOG_TYPE_FTP, LOG_TYPE_TAPE, SS_SUCCESS, ss_tape_close(), ss_tape_write_eof(), and YB_SUCCESS.
Referenced by lazy_copy().
       : external yb_any_file_wclose
Purpose: Close a data file used for replay for the given data format
Input:
INT data_fmt :  YBOS or MIDAS
Output:
none
Function value:
status : from lower function
*******************************************************************/
{
   INT status;
   status = SS_SUCCESS;
   switch (type) {
   case LOG_TYPE_TAPE:
      /* writing EOF mark on tape Fonly */
      status = ss_tape_write_eof(handle);
      ss_tape_close(handle);
      break;
   case LOG_TYPE_DISK:
      /* close file */
      if (handle != 0)
#ifdef OS_WINNT
         CloseHandle((HANDLE) handle);
#else
         close(handle);
#endif
      break;
   case LOG_TYPE_FTP:
#ifdef INCLUDE_FTPLIB
      ftp_close(ftp_con);
      ftp_bye(ftp_con);
#endif
      break;
   }
   if (status != SS_SUCCESS)
      return status;
   return (YB_SUCCESS);
}
INT yb_any_file_wopen (INT type, INT data_fmt, char * filename, INT * hDev)
Definition at line 1789 of file ybos.c.
References cm_msg, FORMAT_MIDAS, FORMAT_YBOS, LOG_TYPE_DISK, LOG_TYPE_FTP, LOG_TYPE_TAPE, MERROR, O_BINARY, O_LARGEFILE, SS_FILE_ERROR, SS_SUCCESS, ss_tape_open(), and ybos_logfile_open().
Referenced by lazy_copy().
       : external yb_any_file_wopen
Purpose: Open a data file for the given data format
Input:
INT type     :  Tape or Disk
INT data_fmt :  YBOS or MIDAS
char * filename : file to open
Output:
INT * hDev      : file handle
Function value:
status : from lower function
*******************************************************************/
{
   INT status = 0;
   if (type == LOG_TYPE_DISK)
      /* takes care of TapeLX/NT under ss_tape_open , DiskLX/NT here */
   {
      if (data_fmt == FORMAT_YBOS) {
         /* takes care of TapeLX/NT under ss_tape_open , DiskLX/NT there */
         status = ybos_logfile_open(type, filename, hDev);
      } else if (data_fmt == FORMAT_MIDAS) {
#ifdef OS_WINNT
         *hDev =
             (int) CreateFile(filename, GENERIC_WRITE, FILE_SHARE_READ,
                              NULL, CREATE_ALWAYS,
                              FILE_ATTRIBUTE_NORMAL |
                              FILE_FLAG_WRITE_THROUGH | FILE_FLAG_SEQUENTIAL_SCAN, 0);
#else
         *hDev = open(filename, O_WRONLY | O_CREAT | O_TRUNC | O_BINARY | O_LARGEFILE, 0644);
#endif
         status = *hDev < 0 ? SS_FILE_ERROR : SS_SUCCESS;
      }
   } else if (type == LOG_TYPE_TAPE) {
      if (data_fmt == FORMAT_YBOS) {
         /* takes care of TapeLX/NT under ss_tape_open , DiskLX/NT there */
         status = ybos_logfile_open(type, filename, hDev);
      } else if (data_fmt == FORMAT_MIDAS)
         status = ss_tape_open(filename, O_WRONLY | O_CREAT | O_TRUNC, hDev);
   } else if (type == LOG_TYPE_FTP) {
#ifdef INCLUDE_FTPLIB
      status = yb_ftp_open(filename, (FTP_CON **) & ftp_con);
      if (status != SS_SUCCESS) {
         *hDev = 0;
         return status;
      } else
         *hDev = 1;
#else
      cm_msg(MERROR, "yb_any_file_wopen", "FTP support not included");
      return SS_FILE_ERROR;
#endif
   }
   return status;
}
INT yb_any_log_write (INT handle, INT data_fmt, INT type, void * prec, DWORD nbytes)
Definition at line 2191 of file ybos.c.
References FORMAT_YBOS, LOG_TYPE_DISK, magta, SS_SUCCESS, and yb_any_dev_os_write().
Referenced by lazy_copy(), ybos_buffer_flush(), and ybos_write().
       : external yb_any_log_write
Purpose: Write a physical record to the out device, takes care of the
magta under YBOS.
Input:
void handle   : file handle
INT data_fmt  : YBOS or MIDAS
INT type      : Tape or disk
void *prec    : record pointer
DWORD nbytes  : record length to be written
Output:
none
Function value:
status : from lower function  SS_SUCCESS, SS_FILE_ERROR
\********************************************************************/
{
   INT status;
   DWORD written;
#ifdef YBOS_VERSION_3_3
   if ((type == LOG_TYPE_DISK) && (data_fmt == FORMAT_YBOS)) {  /* add the magta record if going to disk */
      status =
          yb_any_dev_os_write(handle, type,
                              (char *) ((DWORD *) (magta + 2)), 4, &written);
      if (status != SS_SUCCESS)
         return status;
   }
#endif
   /* write record */
   status = yb_any_dev_os_write(handle, type, prec, nbytes, &written);
   return status;
}
INT yb_any_physrec_display (INT data_fmt)
Definition at line 2325 of file ybos.c.
References D_RECORD, FORMAT_MIDAS, FORMAT_YBOS, i, j, k, my, NLINE, yb_any_all_info_display(), YB_DONE, YB_SUCCESS, and YB_UNKNOWN_FORMAT.
Referenced by replog().
       : external yb_any_physrec_display
Purpose: Display the physical record of the current record
for the given data format.
Not possible for MIDAS as no physical record structure
Input:
INT data_fmt :  YBOS or MIDAS
Output:
none
Function value:
status          Lower function
\********************************************************************/
{
   INT bz, j, i, k;
   DWORD *prec;
   if (data_fmt == FORMAT_MIDAS) {
      printf(">>> No physical record structure for Midas format <<<\n");
      return YB_DONE;
   } else if (data_fmt == FORMAT_YBOS) {
      yb_any_all_info_display(D_RECORD);
      bz = (my.pyh)->rec_size + 1;
      /* adjust local pointer to top of record to include record header */
      prec = (DWORD *) (my.pyh);
      k = (my.pyh)->rec_num;
      for (i = 0; i < bz; i += NLINE) {
         printf("R(%d)[%d] = ", k, i);
         for (j = 0; j < NLINE; j++) {
            if (i + j < bz) {
               printf("%8.8lx ", *prec);
               prec++;
            }
         }
         printf("\n");
      }
      return (YB_SUCCESS);
   } else
      return YB_UNKNOWN_FORMAT;
}
INT yb_any_physrec_get (INT data_fmt, void ** precord, DWORD * readn)
Definition at line 2023 of file ybos.c.
References FORMAT_MIDAS, FORMAT_YBOS, midas_physrec_get(), my, YB_UNKNOWN_FORMAT, and ybos_physrec_get().
Referenced by lazy_copy(), and replog().
       : external yb_any_physrec_get
Purpose: Retrieve a physical record for the given data format
Input:
INT data_fmt :  YBOS or MIDAS
Output:
void ** precord     pointer to the record
DWORD * readn       record length in bytes
Function value:
status : from lower function
\********************************************************************/
{
   *precord = my.pmp;
   if (data_fmt == FORMAT_MIDAS)
      return midas_physrec_get(*precord, readn);
   else if (data_fmt == FORMAT_YBOS)
      return ybos_physrec_get((DWORD **) precord, readn);
   else
      return YB_UNKNOWN_FORMAT;
}
INT yb_any_physrec_skip (INT data_fmt, INT bl)
Definition at line 2227 of file ybos.c.
References FORMAT_MIDAS, FORMAT_YBOS, midas_event_skip(), YB_SUCCESS, YB_UNKNOWN_FORMAT, and ybos_physrec_skip().
Referenced by ma_open(), and replog().
       : external yb_any_physrec_skip
Purpose: Skip physical record until block = bl for the given data
format, Under midas the skip is an event as no physical
record is present under that format,
Input:
INT data_fmt :  YBOS or MIDAS
INT bl:         block number (-1==all, 0 = first block)
in case of MIDAS the bl represent an event
Output:
none
Function value:
status : from lower function
\********************************************************************/
{
   INT status;
   if (data_fmt == FORMAT_MIDAS) {
      status = midas_event_skip(bl);
      return YB_SUCCESS;
   } else if (data_fmt == FORMAT_YBOS)
      return ybos_physrec_skip(bl);
   else
      return YB_UNKNOWN_FORMAT;
}
INT yb_file_recompose (void * pevt, INT format, char * svpath, INT file_mode)
Definition at line 3576 of file ybos.c.
References bk_locate(), YM_CFILE::current_fragment, YM_CFILE::current_read_byte, event_id, EVENTID_BOR, EVENTID_EOR, EVENTID_MESSAGE, R_YM_FILE::file_ID, YM_CFILE::file_ID, FORMAT_MIDAS, FORMAT_YBOS, YM_CFILE::fragment_size, MAX_YM_FILE, YM_CFILE::run_number, YM_CFILE::size, YM_CFILE::total_fragment, YB_BANK_NOT_FOUND, YB_COMPLETE, YB_INCOMPLETE, YB_NO_RECOVER, YB_SUCCESS, yb_ymfile_open(), yb_ymfile_update(), and ybk_locate().
Referenced by process_event(), and replog().
       : external file_recompose
Purpose: Receive event which are expected to be file oriented with
YM_xFILE header.
Input:
char * pevt           pointer to a YBOS event (->LRL).
char * svpath         path where to save file
INT    file_mode      NO_RUN : save file under original name
ADD_RUN: cat run number at end of file name
Output:
none
Function value:
YB_SUCCESS         OP successfull
YB_INCOMPLETE      file compose channels still open
YB_COMPLETE        All file compose channels closed or complete
status             -x error of inner call
\********************************************************************/
{
   YM_CFILE *pmyfch;
   int slot, status;
   if (file_mode == YB_NO_RECOVER)
      return YB_SUCCESS;
   if (format == FORMAT_YBOS) {
      if ((status = ybk_locate((DWORD *) pevt, "CFIL", &pmyfch)) <= 0)
         return (status);
   } else if (format == FORMAT_MIDAS) {
      if ((((EVENT_HEADER *) pevt)->event_id == EVENTID_BOR) ||
          (((EVENT_HEADER *) pevt)->event_id == EVENTID_EOR) ||
          (((EVENT_HEADER *) pevt)->event_id == EVENTID_MESSAGE))
         return YB_BANK_NOT_FOUND;
      pevt = (EVENT_HEADER *) pevt + 1;
      if ((status = bk_locate(pevt, "CFIL", &pmyfch)) <= 0)
         return (status);
   }
   printf("%i - %i - %i - %i - %i -%i -%i \n", pmyfch->file_ID,
          pmyfch->size, pmyfch->fragment_size, pmyfch->total_fragment,
          pmyfch->current_fragment, pmyfch->current_read_byte, pmyfch->run_number);
   /* check if file is in progress */
   for (slot = 0; slot < MAX_YM_FILE; slot++) {
      if ((ymfile[slot].fHandle != 0)
          && (pmyfch->file_ID == ymfile[slot].file_ID)) {
         /* Yep file in progress for that file_ID */
         if ((status = yb_ymfile_update(slot, format, pevt)) != YB_SUCCESS) {
            printf("yb_ymfile_update() failed\n");
            return status;
         }
         goto check;
      }
      /* next slot */
   }
   /* current fragment not registered => new file */
   /* open file, get slot back */
   if ((status = yb_ymfile_open(&slot, format, pevt, svpath, file_mode)) != YB_SUCCESS) {
      printf("yb_ymfile_open() failed\n");
      return status;
   }
   /* update file */
   if ((status = yb_ymfile_update(slot, format, pevt)) != YB_SUCCESS) {
      printf("yb_ymfile_update() failed\n");
      return status;
   }
 check:
   /* for completion of recovery on ALL files */
   for (slot = 0; slot < MAX_YM_FILE; slot++) {
      if (ymfile[slot].fHandle != 0) {
         /* Yes still some file composition in progress */
         return YB_INCOMPLETE;
      }
      /* next slot */
   }
   return YB_COMPLETE;
}
INT ybk_close (DWORD * plrl, void * pbkdat)
dox Close the YBOS bank previously created by ybk_create().
The data pointer pdata must be obtained by ybk_create() and used as an address to fill a bank. It is incremented with every value written to the bank and finally points to a location just after the last byte of the bank. It is then passed to ybk_close() to finish the bank creation. YBOS is a 4 bytes bank aligned structure. Padding is performed at the closing of the bank with values of 0x0f or/and 0x0ffb. See YBOS_bank_examples.
Parameters:
plrl pointer to current composed event.
pbkdat pointer to the current data.
Returns:
number number of bytes contained in bank.
Definition at line 549 of file ybos.c.
References YBOS_BANK_HEADER::length.
Referenced by cd_gen_read(), cd_hv_read(), cd_multi_read(), read_scaler_event(), read_trigger_event(), yb_file_fragment(), ybk_close_chaos(), and ybos_write().
{
   DWORD tdlen;
   /* align pbkdat to I*4 */
   if (((DWORD) pbkdat & 0x1) != 0) {
      *((BYTE *) pbkdat) = 0x0f;
      pbkdat = (void *) (((BYTE *) pbkdat) + 1);
   }
   if (((DWORD) pbkdat & 0x2) != 0) {
      *((WORD *) pbkdat) = 0x0ffb;
      pbkdat = (void *) (((WORD *) pbkdat) + 1);
   }
   /* length in byte */
   tdlen = (DWORD) ((char *) pbkdat - (char *) __pbkh - sizeof(YBOS_BANK_HEADER));
   /* YBOS bank length in I4 */
   __pbkh->length = (tdlen + 4) / 4;    /* (+Bank Type &@#$!) YBOS bank length */
   /* adjust Logical Record Length (entry point from the system) */
   *plrl += __pbkh->length + (sizeof(YBOS_BANK_HEADER) / 4) - 1;
   return __pbkh->length;
}
INT ybk_close_chaos (DWORD * plrl, DWORD bktype, void * pbkdat)
Definition at line 491 of file ybos.c.
References __pchaosi4, A1_BKTYPE, D8_BKTYPE, F4_BKTYPE, I1_BKTYPE, I2_BKTYPE, I4_BKTYPE, SWAP_D2WORD, and ybk_close().
Referenced by read_trigger_event().
       : ybk_close_chaos
Purpose: patch the end of the event to the next 4 byte boundary,
fills up the bank header,
compute the data size in bt unit.
update the LRL (pevt)
Input:
DWORD * pevt          pointer to the top of the YBOS event (LRL).
DWORD   bt            bank type
I2_BKTYPE, I1_BKTYPE, I4_BKTYPE, F4_BKTYPE
void  * pbkdat        pointer to the user area
Output:
none
Function value: Number of bytes in the bank.
\********************************************************************/
{
   switch (bktype) {
   case D8_BKTYPE:
      *__pchaosi4 = (DWORD) ((double *) pbkdat - (double *) __pchaosi4 - 1);
      break;
   case I4_BKTYPE:
   case F4_BKTYPE:
      *__pchaosi4 = (DWORD) ((DWORD *) pbkdat - __pchaosi4 - 1);
      break;
   case I2_BKTYPE:
      *__pchaosi4 = (DWORD) ((WORD *) pbkdat - (WORD *) __pchaosi4 - 2);
      SWAP_D2WORD(__pchaosi4);
      break;
   case I1_BKTYPE:
   case A1_BKTYPE:
      *__pchaosi4 = (DWORD) ((BYTE *) pbkdat - (BYTE *) __pchaosi4 - 4);
      break;
   default:
      printf(" unknown YBOS bank type (%ld)\n", bktype);
      break;
   }
   return ybk_close(plrl, pbkdat);
}
void ybk_create (DWORD * plrl, char * bkname, DWORD bktype, void * pbkdat)
dox Define the following memory area to be a YBOS bank with the given attribute. See YBOS_bank_examples.
Before banks can be created in an event, ybk_init(). has to be called first. YBOS does not support mixed bank type. i.e: all the data are expected to be of the same type. YBOS is a 4 bytes bank aligned structure. Padding is performed at the closing of the bank (see ybk_close) with values of 0x0f or/and 0x0ffb. See YBOS_bank_examples.
Parameters:
plrl pointer to the first DWORD of the event area.
bkname name to be assigned to the breated bank (max 4 char)
bktype YBOS_Bank_Types of the values for the entire created bank.
pbkdat return pointer to the first empty data location.
Returns:
void
Definition at line 438 of file ybos.c.
References YBOS_BANK_HEADER::index, YBOS_BANK_HEADER::length, YBOS_BANK_HEADER::name, YBOS_BANK_HEADER::number, and YBOS_BANK_HEADER::type.
Referenced by cd_gen_read(), cd_hv_read(), cd_multi_read(), read_scaler_event(), read_trigger_event(), yb_file_fragment(), and ybos_write().
{
   DWORD dname = 0;
   __pbkh = (YBOS_BANK_HEADER *) (((DWORD *) (plrl + 1)) + (*(DWORD *) plrl));
   strncpy((char *) &dname, bkname, 4);
   __pbkh->name = *((DWORD *) bkname);
   __pbkh->number = 1;
   __pbkh->index = 0;
   __pbkh->length = 0;
   __pbkh->type = bktype;
   *((DWORD **) pbkdat) = (DWORD *) (__pbkh + 1);
   return;
}
void ybk_create_chaos (DWORD * plrl, char * bkname, DWORD bktype, void * pbkdat)
Definition at line 458 of file ybos.c.
References __pchaosi4, YBOS_BANK_HEADER::index, YBOS_BANK_HEADER::length, YBOS_BANK_HEADER::name, YBOS_BANK_HEADER::number, and YBOS_BANK_HEADER::type.
Referenced by read_trigger_event().
       : ybk_create
Purpose: fills up the bank header,
reserve the first 4bytes for the size of the bank in bt unit
and return the pointer to the user space.
Input:
DWORD * pevt          pointer to the top of the YBOS event (LRL)
char  * bname         Bank name should be char*4
DWORD   bktype            Bank type can by either
I2_BKTYPE, I1_BKTYPE, I4_BKTYPE, F4_BKTYPE
Output:
void    *pbkdat       pointer to first valid data of the created bank
Function value:
none
\********************************************************************/
{
   DWORD dname = 0;
   __pbkh = (YBOS_BANK_HEADER *) ((plrl + 1) + (*plrl));
   strncpy((char *) &dname, bkname, 4);
   __pbkh->name = *((DWORD *) bkname);
   __pbkh->number = 1;
   __pbkh->index = 0;
   __pbkh->length = 0;
   __pbkh->type = bktype;
   *((DWORD **) pbkdat) = (DWORD *) (__pbkh + 1);
   __pchaosi4 = (DWORD *) (*(DWORD *) pbkdat);
   *((DWORD **) pbkdat) += 1;
   return;
}
INT ybk_find (DWORD * plrl, char * bkname, DWORD * bklen, DWORD * bktype, void ** pbk)
Find the requested bank and return the infirmation if the bank as well as the pointer to the top of the data section.
Parameters:
plrl pointer to the area of event.
bkname name of the bank to be located.
bklen returned length in 4bytes unit of the bank.
bktype returned bank type.
pbk pointer to the first data of the found bank.
Returns:
YB_SUCCESS, YB_BANK_NOT_FOUND, YB_WRONG_BANK_TYPE
Definition at line 643 of file ybos.c.
References YBOS_BANK_HEADER::length, MAX_BKTYPE, YBOS_BANK_HEADER::name, YBOS_BANK_HEADER::type, YB_BANK_NOT_FOUND, YB_SUCCESS, and YB_WRONG_BANK_TYPE.
Referenced by bevid_2_mheader(), process_event(), replog(), and yb_any_bank_event_display().
{
   YBOS_BANK_HEADER *pevt;
   DWORD *pendevt;
   pevt = (YBOS_BANK_HEADER *) (plrl + 1);
   /* end of event pointer skip LRL, point to YBOS_BANK_HEADER */
   pendevt = (DWORD *) pevt + *plrl;
   /* check if bank_type in range */
   if (pevt->type >= MAX_BKTYPE)
      return (YB_WRONG_BANK_TYPE);
   /* init returned variables */
   *bklen = 0;
   *bktype = 0;
   /* scan event */
   while ((DWORD *) pevt < pendevt) {
      /* check bank name */
      if (strncmp((char *) &(pevt->name), bkname, 4) == 0) {    /* bank name match */
         /* extract bank length */
         *bklen = pevt->length - 1;     /* exclude bank type */
         /* extract bank type */
         *bktype = pevt->type;
         /* return point to bank name */
         *pbk = &pevt->name;
         return (YB_SUCCESS);
      } else {
         /* skip to next bank */
         pevt = (YBOS_BANK_HEADER *) (((DWORD *) pevt) + pevt->length + 4);
      }
   }
   return (YB_BANK_NOT_FOUND);
}
void ybk_init (DWORD * plrl)
Initializes an event for YBOS banks structure.
Before banks can be created in an event, ybk_init() has to be called first. See YBOS_bank_examples.
Parameters:
plrl pointer to the first DWORD of the event area of event
Returns:
void
Definition at line 408 of file ybos.c.
Referenced by cd_gen_read(), cd_hv_read(), cd_multi_read(), read_scaler_event(), read_trigger_event(), yb_file_fragment(), and ybos_write().
{
   *plrl = 0;
   return;
}
INT ybk_iterate (DWORD * plrl, YBOS_BANK_HEADER ** pybkh, void ** pdata)
Returns the bank header pointer and data pointer of the given bank name.
Parameters:
plrl pointer to the area of event.
pybkh pointer to the YBOS bank header.
pdata pointer to the first data of the current bank.
Returns:
data length in 4 bytes unit. return -1 if no more bank found.
Definition at line 729 of file ybos.c.
References I1_BKTYPE, YBOS_BANK_HEADER::length, and YB_WRONG_BANK_TYPE.
Referenced by update_odb(), and yb_any_bank_event_display().
{
   static int len;
   static DWORD *pendevt;
   static DWORD *pybk;
   /*PAA char bname[5]; */
   /* the event may have several bank
      check if we have been already in here */
   if (*pybkh == NULL) {
      /* first time in (skip lrl) */
      *pybkh = (YBOS_BANK_HEADER *) (plrl + 1);
      if ((*pybkh)->type > I1_BKTYPE) {
         *pdata = NULL;
         *pybkh = (YBOS_BANK_HEADER *) * pdata;
         return (YB_WRONG_BANK_TYPE);
      }
      /* end of event pointer (+ lrl) */
      pendevt = plrl + *plrl;
      /* skip the EVID bank if present */
    /*-PAA- keep it in for a little while Dec 17/98
    *((DWORD *)bname) = (*pybkh)->name;
    if (strncmp (bname,"EVID",4) == 0)
    {
    len = (*pybkh)->length;
    (YBOS_BANK_HEADER *)(*pybkh)++;
    pybk = (DWORD *) *pybkh;
    pybk += len - 1;
    *pybkh = (YBOS_BANK_HEADER *) pybk;
    }
    */
   } else {
      /* already been in iterate */
      /* skip current pointed bank ( + bank_length + header) */
      len = (*pybkh)->length;
      (YBOS_BANK_HEADER *) (*pybkh)++;
      pybk = (DWORD *) * pybkh;
      pybk += len - 1;
      *pybkh = (YBOS_BANK_HEADER *) pybk;
   }
   /* check for end of event */
   if ((DWORD *) (*pybkh) < pendevt) {
      /* points to the data section */
      *pdata = (void *) (*pybkh + 1);
      /* length always in I*4 due to YBOS -1 because type included in length !@# */
      return ((*pybkh)->length - 1);
   } else {
      /* no more bank in this event */
      *pdata = NULL;
      *pybkh = (YBOS_BANK_HEADER *) * pdata;
      return (-1);
   }
}
INT ybk_list (DWORD * plrl, char * bklist)
Returns the size in bytes of the event composed of YBOS bank(s).
The bk_list() has to be a predefined string of max size of YB_STRING_BANKLIST_MAX.
Parameters:
plrl pointer to the area of event
bklist Filled character string of the YBOS bank names found in the event.
Returns:
number of banks found in this event.
Definition at line 594 of file ybos.c.
References cm_msg, MAX_BKTYPE, MINFO, YBOS_BANK_HEADER::name, YBOS_BANK_HEADER::type, YB_BANKLIST_MAX, and YB_WRONG_BANK_TYPE.
Referenced by process_event(), replog(), and yb_any_bank_event_display().
{
   YBOS_BANK_HEADER *pbk;
   DWORD *pendevt, nbk;
   pbk = (YBOS_BANK_HEADER *) (plrl + 1);
   /* end of event pointer skip LRL, point to YBOS_BANK_HEADER */
   pendevt = (DWORD *) pbk + *plrl;
   /* check if bank_type in range */
   if (pbk->type >= MAX_BKTYPE)
      return (YB_WRONG_BANK_TYPE);
   /*init bank counter and returned string */
   nbk = 0;
   bklist[0] = 0;
   /* scan event */
   while ((DWORD *) pbk < pendevt) {
      /* update the number of bank counter */
      nbk++;
      if (nbk > YB_BANKLIST_MAX) {
         cm_msg(MINFO, "ybk_list", "over %i banks -> truncated", YB_BANKLIST_MAX);
         return (nbk);
      }
      /* append ybos bank name to list */
      strncat(bklist, (char *) &(pbk->name), 4);
      /* skip to next bank */
      pbk = (YBOS_BANK_HEADER *) (((DWORD *) pbk) + pbk->length + 4);
   }
   return (nbk);
}
INT ybk_locate (DWORD * plrl, char * bkname, void * pdata)
Locate the requested bank and return the pointer to the top of the data section.
Parameters:
plrl pointer to the area of event
bkname name of the bank to be located.
pdata pointer to the first data of the located bank.
Returns:
Number of DWORD in bank or YB_BANK_NOT_FOUND, YB_WRONG_BANK_TYPE (<0)
Definition at line 690 of file ybos.c.
References YBOS_BANK_HEADER::length, MAX_BKTYPE, YBOS_BANK_HEADER::name, YBOS_BANK_HEADER::type, YB_BANK_NOT_FOUND, and YB_WRONG_BANK_TYPE.
Referenced by yb_file_recompose(), yb_ymfile_open(), and yb_ymfile_update().
{
   YBOS_BANK_HEADER *pybk;
   DWORD *pendevt;
   pybk = (YBOS_BANK_HEADER *) (plrl + 1);
   /* end of event pointer skip LRL, point to YBOS_BANK_HEADER */
   pendevt = (DWORD *) pybk + *plrl;
   /* check if bank_type in range */
   if (pybk->type >= MAX_BKTYPE)
      return (YB_WRONG_BANK_TYPE);
   /* scan event */
   while ((DWORD *) pybk < pendevt) {
      /* check bank name */
      if (strncmp((char *) &(pybk->name), bkname, 4) == 0) {    /* bank name match */
         /* extract bank length */
         /* return pointer to data section */
         *((void **) pdata) = pybk + 1;
         return (pybk->length - 1);
      } else {
         /* skip to next bank */
         pybk = (YBOS_BANK_HEADER *) (((DWORD *) pybk) + pybk->length + 4);
      }
   }
   return (YB_BANK_NOT_FOUND);
}
INT ybk_size (DWORD * plrl)
Returns the size in bytes of the event composed of YBOS bank(s).
Parameters:
plrl pointer to the area of event
Returns:
number of bytes contained in data area of the event
Definition at line 579 of file ybos.c.
Referenced by cd_gen_read(), cd_hv_read(), cd_multi_read(), process_event(), read_scaler_event(), read_trigger_event(), yb_file_fragment(), and ybos_write().
{
   return (*((DWORD *) plrl) * 4 + 4);
}
INT ybos_event_get (DWORD ** plrl, DWORD * readn)
Definition at line 2568 of file ybos.c.
References my, size, YB_DONE, YB_SUCCESS, YBOS_HEADER_LENGTH, YBOS_PHYREC_SIZE, and ybos_physrec_get().
Referenced by ma_read_event(), and yb_any_event_get().
       : ybos_event_get
Purpose: read one YBOS event.
detect the end of run by checking the *plrl content (-1)
Input:
Output:
DWORD ** plrl      points to LRL valid full YBOS event
DWORD * readn      event size in Bytes
Function value:
YB_DONE           No more record to read
YB_SUCCESS        Ok
\********************************************************************/
{
   DWORD size, fpart, lpart, evt_length;
   DWORD *ptmp, *prec;
   INT status;
   /* detect end of run (no more events)
      by checking the *pyrd == -1 */
   if ((INT) (*my.pyrd) == -1)
      return YB_DONE;
   /* extract event to local event area
      event may not be complete if larger then physical record size
      will be taken care below, ADD the lrl  */
   evt_length = *(my.pyrd) + 1;
   memcpy((char *) my.pylrl, (char *) my.pyrd, evt_length << 2);
   /* extract lrl in I*4 and include itself (lrl) */
   /* stop if LRL  = -1 ... I don't think it is necessary but I leave it in for now
      or forever... */
   if (evt_length - 1 == -1)
      return (YB_DONE);
   /* check if event cross physical record boundary */
   if ((my.pyrd + evt_length) >= (DWORD *) my.pyh + my.size) {
      /* upcomming event crosses block, then first copy first part of event */
      /* compute max copy for first part of event */
      fpart = (DWORD *) my.pyh + my.size - my.pyrd;
      memcpy((char *) my.pylrl, (char *) my.pyrd, fpart << 2);
      /* adjust temporary evt pointer all in I*4 */
      ptmp = my.pylrl + fpart;
      if ((evt_length - fpart) == 0) {
         /* get next physical record */
         if ((status = ybos_physrec_get(&prec, &size)) != YB_SUCCESS)
            return (status);
         my.pyrd = (DWORD *) my.pyh + my.pyh->header_length;
      } else {
         while ((evt_length - fpart) > 0) {
            lpart = evt_length - fpart;
            if (lpart > (YBOS_PHYREC_SIZE - YBOS_HEADER_LENGTH))
               lpart = (YBOS_PHYREC_SIZE - YBOS_HEADER_LENGTH);
            /* get next physical record */
            if ((status = ybos_physrec_get(&prec, &size)) != YB_SUCCESS)
               return (status);
            /* pyrd is left at the next lrl but here we comming from
               a cross boundary request so read just the pyrd to
               pyh+header_length */
            my.pyrd = (DWORD *) my.pyh + my.pyh->header_length;
            /* now copy remaining from temporary pointer */
            memcpy((char *) ptmp, (char *) my.pyrd, lpart << 2);
            /* adjust pointer to next valid data (LRL)
               should be equivalent to pyh+pyh->offset */
            my.pyrd += lpart;
            fpart += lpart;
            ptmp += lpart;
         }
      }
      if (my.pyrd != (DWORD *) my.pyh + my.pyh->offset) {
         printf(" event misalignment !! %p  %p \n",
                my.pyrd, (DWORD *) my.pyh + my.pyh->offset);
         printf("Event crossed boundary: length %ld\n", evt_length);
         my.pyrd = (DWORD *) my.pyh + my.pyh->offset;
      }
   } else {
      /* adjust pointer to next valid data (LRL) */
      my.pyrd += evt_length;
   }
   /* count event */
   my.evtn++;
  /*-PAA- Dec99 Danny adjust event size in I*4 */
   my.evtlen = evt_length;
   /* in bytes for the world */
   *readn = my.evtlen << 2;
   *plrl = (DWORD *) my.pylrl;
   return (YB_SUCCESS);
}
INT ybos_event_swap (DWORD * pevt)
Definition at line 2457 of file ybos.c.
Referenced by eb_yfragment_add(), source_scan(), yb_any_event_swap(), and ybos_write().
       : ybos_event_swap
Purpose: byte swap the entire YBOS event if necessary.
chekc necessity of swapping by looking at the
bank type being < MAX_BKTYPE
Input:
DWORD * plrl           pointer to the YBOS event
Output:
none
Function value:
YB_SUCCESS             Event has been swapped
YB_EVENT_NOT_SWAPPED   Event has been not been swapped
YB_SWAP_ERROR          swapping error
\********************************************************************/
{
   DWORD *pevt, *pnextb, *pendevt;
   DWORD bank_length, bank_type;
   /* check if event has to be swapped */
   if ((((YBOS_BANK_HEADER *) (plrl + 1))->type) < MAX_BKTYPE)
      return (YB_EVENT_NOT_SWAPPED);
   /* swap LRL */
   DWORD_SWAP(plrl);
   pevt = plrl + 1;
   /* end of event pointer */
   pendevt = pevt + *plrl;
   /* scan event */
   while (pevt < pendevt) {
      /* swap YBOS bank header for sure */
      /* bank name doesn't have to be swapped as it's an ASCII coded */
      pevt++;                   /* bank name */
      DWORD_SWAP(pevt);         /* bank number */
      pevt++;
      DWORD_SWAP(pevt);         /* bank index */
      pevt++;
      DWORD_SWAP(pevt);         /* bank length */
      bank_length = *pevt++;
      DWORD_SWAP(pevt);         /* bank type */
      bank_type = *pevt++;
      /* pevt left pointing at first data in bank */
      /* pointer to next bank (-1 due to type inclided in length #$%@ */
      pnextb = pevt + bank_length - 1;
      switch (bank_type) {
      case D8_BKTYPE:
         while ((BYTE *) pevt < (BYTE *) pnextb) {
            QWORD_SWAP(pevt);
            pevt = (DWORD *) (((double *) pevt) + 1);
         }
         break;
      case I4_BKTYPE:
      case F4_BKTYPE:
         while ((BYTE *) pevt < (BYTE *) pnextb) {
            DWORD_SWAP(pevt);
            pevt++;
         }
         break;
      case I2_BKTYPE:
         while ((BYTE *) pevt < (BYTE *) pnextb) {
            WORD_SWAP(pevt);
            pevt = (DWORD *) (((WORD *) pevt) + 1);
         }
         break;
      case I1_BKTYPE:
      case A1_BKTYPE:
         pevt = pnextb;
         break;
      default:
         printf("ybos_swap_event-E- Unknown bank type %li\n", bank_type);
         return (YB_SWAP_ERROR);
         break;
      }
   }
   return (YB_SUCCESS);
}
INT ybos_get_tid_size (INT tid)
Definition at line 1047 of file ybos.c.
References yb_tid_size.
{
   if (tid < 8)
      return yb_tid_size[tid];
   return 0;
}
INT ybos_log_close (LOG_CHN * log_chn, INT run_number)
Definition at line 1471 of file ybos.c.
References LOG_CHN::format_info, LOG_CHN::handle, YBOS_INFO::ptop, SS_SUCCESS, status, LOG_CHN::type, ybos_buffer_flush(), and ybos_logfile_close().
Referenced by log_close().
       : ybos_log_close
Purpose: Close a YBOS logger channel, Should be used only by mlogger.
Input:
LOG_CHN * log_chn      Concern log channel
INT   run_number       run number
Output:
none
Function value:
error, success
\********************************************************************/
{
   INT status;
   YBOS_INFO *ybos;
   ybos = (YBOS_INFO *) log_chn->format_info;
   /* Write EOF mark and close the device */
   /* flush buffer before closing */
   status = ybos_buffer_flush(log_chn, run_number);
   if (status != SS_SUCCESS)
      return status;
   status = ybos_logfile_close(log_chn->type, log_chn->handle);
   free(ybos->ptop);
   free(ybos);
   return SS_SUCCESS;
}
INT ybos_log_open (LOG_CHN * log_chn, INT run_number)
Definition at line 1066 of file ybos.c.
References EVENTID_BOR, LOG_CHN::format_info, LOG_CHN::handle, CHN_SETTINGS::odb_dump, LOG_CHN::path, YBOS_INFO::pbot, YBOS_INFO::pbuf, YBOS_INFO::pend, YBOS_INFO::ptop, YBOS_INFO::pwrt, YBOS_INFO::recn, YBOS_INFO::reco, LOG_CHN::settings, SS_NO_MEMORY, SS_SUCCESS, status, LOG_CHN::type, YBOS_BUFFER_SIZE, YBOS_HEADER_LENGTH, ybos_log_dump(), ybos_logfile_open(), and YBOS_PHYREC_SIZE.
Referenced by log_open().
       : ybos_log_open, Should be used only by mlogger.
Purpose: Open a logger channel in YBOS fmt
Input:
LOG_CHN * log_chn      Concern log channel
INT   run_number       run number
Output:
none
Function value:
error, success
\********************************************************************/
{
   YBOS_INFO *ybos;
   INT status;
   /* allocate YBOS buffer info */
   log_chn->format_info = (void **) malloc(sizeof(YBOS_INFO));
   ybos = (YBOS_INFO *) log_chn->format_info;
   /* reset memory */
   memset(ybos, 0, sizeof(YBOS_INFO));
   if (ybos == NULL) {
      log_chn->handle = 0;
      return SS_NO_MEMORY;
   }
   /* allocate full ring buffer for that channel */
   if ((ybos->ptop = (DWORD *) malloc(YBOS_BUFFER_SIZE)) == NULL) {
      log_chn->handle = 0;
      return SS_NO_MEMORY;
   }
   memset((char *) ybos->ptop, 0, YBOS_BUFFER_SIZE);
   /* Setup YBOS pointers */
   ybos->reco = YBOS_HEADER_LENGTH;
   ybos->pbuf = ybos->ptop + YBOS_HEADER_LENGTH;
   ybos->pwrt = ybos->pbuf;
   ybos->pbot = ybos->ptop + YBOS_PHYREC_SIZE;
   ybos->pend = ybos->ptop + YBOS_BUFFER_SIZE;
   ybos->recn = 0;
   /* open logging device */
   status = ybos_logfile_open(log_chn->type, log_chn->path, &log_chn->handle);
   if (status != SS_SUCCESS) {
      free(ybos->ptop);
      free(ybos);
      log_chn->handle = 0;
      return status;
   }
   /* write ODB dump */
   if (log_chn->settings.odb_dump)
      ybos_log_dump(log_chn, EVENTID_BOR, run_number);
   return SS_SUCCESS;
}
INT ybos_write (LOG_CHN * log_chn, EVENT_HEADER * pevent, INT evt_size)
Definition at line 1185 of file ybos.c.
References A1_BKTYPE, CHN_STATISTICS::bytes_written, CHN_STATISTICS::bytes_written_total, cm_msg, EVENT_HEADER::data_size, EVENT_HEADER::event_id, EVENTID_BOR, EVENTID_MESSAGE, CHN_STATISTICS::events_written, FALSE, LOG_CHN::format, LOG_CHN::format_info, LOG_CHN::handle, YBOS_PHYSREC_HEADER::header_length, if, CHN_SETTINGS::log_messages, LOG_TYPE_TAPE, MAX_EVENT_SIZE, MERROR, MINFO, MT_USER, YBOS_PHYSREC_HEADER::offset, pbktop, YBOS_INFO::pbot, YBOS_INFO::pbuf, YBOS_INFO::ptop, YBOS_INFO::pwrt, YBOS_PHYSREC_HEADER::rec_num, YBOS_PHYSREC_HEADER::rec_size, YBOS_INFO::recn, YBOS_INFO::reco, LOG_CHN::settings, SS_NO_MEMORY, SS_SUCCESS, LOG_CHN::statistics, status, EVENT_HEADER::trigger_mask, TRUE, LOG_CHN::type, yb_any_log_write(), YB_SUCCESS, ybk_close(), ybk_create(), ybk_init(), ybk_size(), ybos_event_swap(), YBOS_HEADER_LENGTH, and YBOS_PHYREC_SIZE.
Referenced by log_write(), and ybos_log_dump().
       : ybos_write
Purpose: Write a YBOS event to the logger channel. Should be used only by
mlogger.
Takes care of the EVENT_BOR and EVENT_MESSAGE which are
shiped as YBOS bank in A1_BKTYPE bank. named respectively
MODB, MMSG
Input:
LOG_CHN *      log_chn      Concern log channel
EVENT_HEADER * pevent       event pointer to Midas header
INT            evt_size     event size in bytes seen by Midas
Output:
none
Function value:
error, success
\********************************************************************/
{
   short int evid, evmsk;
   BOOL large_evt;
   INT status, left_over_length, datasize;
   YBOS_INFO *ybos;
   DWORD *pbkdat;
   DWORD bfsize;
   YBOS_PHYSREC_HEADER *yb_phrh;
   /* Check the Event ID for :
      Midas BOR/EOR which include the ODB dump : 0x8000/0x8001
      Msg dump from MUSER flag from odb mainly : 0x8002
    */
   evid = pevent->event_id;
   evmsk = pevent->trigger_mask;
   /* shortcut to ybos struct */
   ybos = (YBOS_INFO *) log_chn->format_info;
   /* detect if event is message oriented (ASCII) */
   if ((evid >= EVENTID_BOR) && (evid <= EVENTID_MESSAGE)) {    /* skip ASCII dump if not MUSER */
      if (!(evmsk & MT_USER))
         return SS_SUCCESS;
      /* skip if MUSER  but not Log message enabled */
      if (MT_USER && !log_chn->settings.log_messages)
         return SS_SUCCESS;
      /* ASCII event has to be recasted YBOS */
      /* Inform if event too long (>32Kbytes) */
      if (pevent->data_size > MAX_EVENT_SIZE)
         cm_msg(MINFO, "ybos_write", "MMSG or MODB event too large");
      /* align to DWORD boundary in bytes */
      datasize = 4 * (pevent->data_size + 3) / 4;
      /* overall buffer size in bytes */
      bfsize = datasize + sizeof(YBOS_BANK_HEADER) + 4; /* +LRL */
      /* allocate space */
      pbktop = (DWORD *) malloc(bfsize);
      if (pbktop == NULL) {
         cm_msg(MERROR, "ybos_write", "malloc error for ASCII dump");
         return SS_NO_MEMORY;
      }
      memset(pbktop, 0, bfsize);
      ybk_init(pbktop);
      /* open bank depending on event type */
      if (evid == EVENTID_MESSAGE)
         ybk_create(pbktop, "MMSG", A1_BKTYPE, &pbkdat);
      else
         ybk_create(pbktop, "MODB", A1_BKTYPE, &pbkdat);
      memcpy((char *) pbkdat, (char *) (pevent + 1), pevent->data_size);
      pbkdat = (DWORD *) (((char *) pbkdat) + datasize);
      ybk_close(pbktop, pbkdat);
      /* event size in bytes for Midas */
      evt_size = ybk_size(pbktop);
      /* swap bytes if necessary based on the ybos.bank_type */
      ybos_event_swap((DWORD *) pbktop);
      /* Event with MIDAS header striped out */
      memcpy((char *) ybos->pbuf, (char *) pbktop, evt_size);
      if (pbktop != NULL)
         free(pbktop);
      pbktop = NULL;
      status = SS_SUCCESS;
   } else {                     /* normal event */
      /* Strip the event from the Midas EVENT_HEADER */
      /* event size include the Midas EVENT_HEADER... don't need for ybos
         I do this in order to keep the log_write from mlogger intact */
      /* correct the event length. Now it is a pure YBOS event */
      pevent++;
      /* correct the event length in bytes */
      evt_size -= sizeof(EVENT_HEADER);
      /* swap bytes if necessary based on the ybos.bank_type */
      ybos_event_swap((DWORD *) pevent);
      /* I have ALWAYS enough space for the event <MAX_EVENT_SIZE */
      memcpy((char *) ybos->pbuf, (char *) pevent, evt_size);
      status = YB_SUCCESS;
   }
   /* move write pointer to next free location (DWORD) */
   ybos->pbuf += (4 * (evt_size + 3) / 4) >> 2;
   /* default not a large event */
   large_evt = FALSE;
   /* Loop over buffer until this condition
      The event offset in the phys rec is ==0 if event larger than PHYREC_SIZE */
   while (ybos->pbuf >= ybos->pbot) {
      ybos->pwrt -= YBOS_HEADER_LENGTH;
      yb_phrh = (YBOS_PHYSREC_HEADER *) (ybos->pwrt);
      yb_phrh->rec_size = YBOS_PHYREC_SIZE - 1; /* exclusive */
      yb_phrh->header_length = YBOS_HEADER_LENGTH;
      yb_phrh->rec_num = ybos->recn;
      yb_phrh->offset = large_evt ? 0 : ybos->reco;
      /* Write physical record to device */
      status =
          yb_any_log_write(log_chn->handle, log_chn->format, log_chn->type,
                           ybos->pwrt, YBOS_PHYREC_SIZE << 2);
      if (status != SS_SUCCESS)
         return status;
      /* update statistics */
#ifdef YBOS_VERSION_3_3
      if (log_chn->type == LOG_TYPE_TAPE) {     /* statistics in bytes */
         log_chn->statistics.bytes_written += YBOS_PHYREC_SIZE << 2;
         log_chn->statistics.bytes_written_total += YBOS_PHYREC_SIZE << 2;
      } else {                  /* statistics in bytes + the extra magta */
         log_chn->statistics.bytes_written += YBOS_PHYREC_SIZE << 2 + 4;
         log_chn->statistics.bytes_written_total += YBOS_PHYREC_SIZE << 2 + 4;
      }
#else
      log_chn->statistics.bytes_written += YBOS_PHYREC_SIZE << 2;
      log_chn->statistics.bytes_written_total += YBOS_PHYREC_SIZE << 2;
#endif
      /* Update statistics */
      ybos->recn++;
      /* check if event is larger than YBOS_PHYREC_SIZE */
      if (ybos->pbuf >= ybos->pbot + (YBOS_PHYREC_SIZE - YBOS_HEADER_LENGTH)) {
         large_evt = TRUE;
         /* shift record window by one YBOS_PHYSREC - header */
         ybos->pwrt = ybos->pbot;
         ybos->pbot += (YBOS_PHYREC_SIZE - YBOS_HEADER_LENGTH);
      } else {
         large_evt = FALSE;
         /* adjust pointers */
         ybos->pwrt = ybos->ptop + YBOS_HEADER_LENGTH;
         left_over_length = ybos->pbuf - ybos->pbot;
         memcpy(ybos->pwrt, ybos->pbot, left_over_length << 2); /* in bytes */
         ybos->pbuf = ybos->pwrt + left_over_length;
         ybos->pbot = ybos->ptop + YBOS_PHYREC_SIZE;
         ybos->reco = ybos->pbuf - ybos->pwrt + 4;      /* YBOS header */
      }
   }
   /* update statistics */
   log_chn->statistics.events_written++;
   return status;
}
Variable Documentation
YBOS_BANK_HEADER* __pbkh [static]
dox
Definition at line 417 of file ybos.c.
DWORD* __pchaosi4 [static]
dox
Definition at line 455 of file ybos.c.
Referenced by ybk_close_chaos(), and ybk_create_chaos().