AlcapDAQ:Rootana: Midas Common Functions (cm_xxx)
Midas Common Functions (cm_xxx)
[The midas.h & midas.c]
Data Structures
struct experiment_table
struct TR_CLIENT
Functions
INT cm_synchronize (DWORD *seconds)
INT cm_asctime (char *str, INT buf_size)
INT cm_time (DWORD *time)
char * cm_get_version ()
INT cm_set_path (char *path)
INT cm_get_path (char *path)
INT cm_scan_experiments (void)
INT cm_delete_client_info (HNDLE hDB, INT pid)
INT cm_check_client (HNDLE hDB, HNDLE hKeyClient)
INT cm_set_client_info (HNDLE hDB, HNDLE *hKeyClient, char *host_name, char *client_name, INT hw_type, char *password, DWORD watchdog_timeout)
INT cm_get_client_info (char *client_name)
INT cm_get_environment (char *host_name, int host_name_size, char *exp_name, int exp_name_size)
void cm_check_connect (void)
INT cm_connect_experiment (char *host_name, char *exp_name, char *client_name, void(*func)(char *))
INT cm_connect_experiment1 (char *host_name, char *exp_name, char *client_name, void(*func)(char *), INT odb_size, DWORD watchdog_timeout)
INT cm_list_experiments (char *host_name, char exp_name[MAX_EXPERIMENT][NAME_LENGTH])
INT cm_select_experiment (char *host_name, char *exp_name)
INT cm_connect_client (char *client_name, HNDLE *hConn)
INT cm_disconnect_client (HNDLE hConn, BOOL bShutdown)
INT cm_disconnect_experiment (void)
INT cm_set_experiment_database (HNDLE hDB, HNDLE hKeyClient)
INT cm_set_experiment_mutex (INT mutex_alarm, INT mutex_elog)
INT cm_get_experiment_database (HNDLE *hDB, HNDLE *hKeyClient)
INT cm_get_experiment_mutex (INT *mutex_alarm, INT *mutex_elog)
INT cm_set_watchdog_params (BOOL call_watchdog, DWORD timeout)
INT cm_get_watchdog_params (BOOL *call_watchdog, DWORD *timeout)
INT cm_get_watchdog_info (HNDLE hDB, char *client_name, DWORD *timeout, DWORD *last)
INT cm_register_server (void)
INT cm_register_transition (INT transition, INT(*func)(INT, char *), INT sequence_number)
INT cm_set_transition_sequence (INT transition, INT sequence_number)
INT cm_register_deferred_transition (INT transition, BOOL(*func)(INT, BOOL))
INT cm_check_deferred_transition ()
int tr_compare (const void *arg1, const void *arg2)
INT cm_transition (INT transition, INT run_number, char *perror, INT strsize, INT async_flag, INT debug_flag)
INT cm_dispatch_ipc (char *message, int socket)
BOOL cm_is_ctrlc_pressed ()
void cm_ack_ctrlc_pressed ()
INT cm_yield (INT millisec)
INT cm_execute (char *command, char *result, INT bufsize)
INT cm_register_function (INT id, INT(*func)(INT, void **))
void cm_watchdog (int dummy)
INT cm_enable_watchdog (BOOL flag)
INT cm_shutdown (char *name, BOOL bUnique)
INT cm_exist (char *name, BOOL bUnique)
INT cm_cleanup (char *client_name, BOOL ignore_timeout)
INT bm_get_buffer_info (INT buffer_handle, BUFFER_HEADER *buffer_header)
INT bm_get_buffer_level (INT buffer_handle, INT *n_bytes)
INT bm_lock_buffer (INT buffer_handle)
INT bm_unlock_buffer (INT buffer_handle)
INT bm_init_buffer_counters (INT buffer_handle)
Variables
static experiment_table exptab [MAX_EXPERIMENT]
static INT _requested_transition
static DWORD _deferred_transition_mask
static BOOL _ctrlc_pressed = FALSE
Detailed Description
dox dox
dox
Function Documentation
INT bm_get_buffer_info (INT buffer_handle, BUFFER_HEADER * buffer_header)
dox
Definition at line 5335 of file midas.c.
References _buffer_entries, BM_INVALID_HANDLE, bm_lock_buffer(), BM_SUCCESS, bm_unlock_buffer(), cm_msg, MERROR, RPC_BM_GET_BUFFER_INFO, rpc_call(), and rpc_is_remote().
Referenced by main(), process_event(), and rpc_server_dispatch().
         : bm_buffer_info
  Purpose: Copies the current buffer header referenced by buffer_handle
           into the *buffer_header structure which must be supplied
           by the calling routine.
  Input:
    INT buffer_handle       Handle of the buffer to get the header from
  Output:
    BUFFER_HEADER *buffer_header   Destination address which gets a copy
                                   of the buffer header structure.
  Function value:
    BM_SUCCESS              Successful completion
    BM_INVALID_HANDLE       Buffer handle is invalid
    RPC_NET_ERROR           Network error
\********************************************************************/
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_GET_BUFFER_INFO, buffer_handle, buffer_header);
#ifdef LOCAL_ROUTINES
   if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
      cm_msg(MERROR, "bm_get_buffer_info", "invalid buffer handle %d", buffer_handle);
      return BM_INVALID_HANDLE;
   }
   if (!_buffer[buffer_handle - 1].attached) {
      cm_msg(MERROR, "bm_get_buffer_info", "invalid buffer handle %d", buffer_handle);
      return BM_INVALID_HANDLE;
   }
   bm_lock_buffer(buffer_handle);
   memcpy(buffer_header, _buffer[buffer_handle - 1].buffer_header, sizeof(BUFFER_HEADER));
   bm_unlock_buffer(buffer_handle);
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_get_buffer_level (INT buffer_handle, INT * n_bytes)
Definition at line 5385 of file midas.c.
References _buffer_entries, BUFFER::attached, BM_INVALID_HANDLE, bm_lock_buffer(), BM_SUCCESS, bm_unlock_buffer(), BUFFER::buffer_header, BUFFER_HEADER::client, BUFFER::client_index, cm_msg, MERROR, BUFFER::read_cache_rp, BUFFER::read_cache_wp, BUFFER_CLIENT::read_pointer, RPC_BM_GET_BUFFER_LEVEL, rpc_call(), rpc_is_remote(), BUFFER_HEADER::size, and BUFFER_HEADER::write_pointer.
Referenced by rpc_server_dispatch(), tr_poststop(), and tr_stop().
         : bm_get_buffer_level
  Purpose: Return number of bytes in buffer or in cache
  Input:
    INT buffer_handle       Handle of the buffer to get the info
  Output:
    INT *n_bytes              Number of bytes in buffer
  Function value:
    BM_SUCCESS              Successful completion
    BM_INVALID_HANDLE       Buffer handle is invalid
    RPC_NET_ERROR           Network error
\********************************************************************/
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_GET_BUFFER_LEVEL, buffer_handle, n_bytes);
#ifdef LOCAL_ROUTINES
   {
      BUFFER *pbuf;
      BUFFER_HEADER *pheader;
      BUFFER_CLIENT *pclient;
      if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
         cm_msg(MERROR, "bm_get_buffer_level", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      pbuf = &_buffer[buffer_handle - 1];
      pheader = pbuf->buffer_header;
      if (!pbuf->attached) {
         cm_msg(MERROR, "bm_get_buffer_level", "invalid buffer handle %d", buffer_handle);
         return BM_INVALID_HANDLE;
      }
      bm_lock_buffer(buffer_handle);
      pclient = &(pheader->client[_buffer[buffer_handle - 1].client_index]);
      *n_bytes = pheader->write_pointer - pclient->read_pointer;
      if (*n_bytes < 0)
         *n_bytes += pheader->size;
      bm_unlock_buffer(buffer_handle);
      /* add bytes in cache */
      if (pbuf->read_cache_wp > pbuf->read_cache_rp)
         *n_bytes += pbuf->read_cache_wp - pbuf->read_cache_rp;
   }
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_init_buffer_counters (INT buffer_handle)
Definition at line 5509 of file midas.c.
References _buffer_entries, BM_INVALID_HANDLE, BM_SUCCESS, BUFFER::buffer_header, cm_msg, MERROR, BUFFER_HEADER::num_in_events, BUFFER_HEADER::num_out_events, RPC_BM_INIT_BUFFER_COUNTERS, rpc_call(), and rpc_is_remote().
Referenced by bm_open_buffer(), and rpc_server_dispatch().
         : bm_init_event_counters
  Purpose: Initialize counters for a specific buffer. This routine
           should be called at the beginning of a run.
  Input:
    INT    buffer_handle    Handle to the buffer to be
                            initialized.
  Output:
    none
  Function value:
    BM_SUCCESS              Successful completion
    BM_INVALID_HANDLE       Buffer handle is invalid
\********************************************************************/
{
   if (rpc_is_remote())
      return rpc_call(RPC_BM_INIT_BUFFER_COUNTERS, buffer_handle);
#ifdef LOCAL_ROUTINES
   if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
      cm_msg(MERROR, "bm_init_buffer_counters", "invalid buffer handle %d",
             buffer_handle);
      return BM_INVALID_HANDLE;
   }
   if (!_buffer[buffer_handle - 1].attached) {
      cm_msg(MERROR, "bm_init_buffer_counters", "invalid buffer handle %d",
             buffer_handle);
      return BM_INVALID_HANDLE;
   }
   _buffer[buffer_handle - 1].buffer_header->num_in_events = 0;
   _buffer[buffer_handle - 1].buffer_header->num_out_events = 0;
#endif                          /* LOCAL_ROUTINES */
   return BM_SUCCESS;
}
INT bm_lock_buffer (INT buffer_handle)
Definition at line 5451 of file midas.c.
References _buffer_entries, BM_INVALID_HANDLE, BM_SUCCESS, cm_msg, MERROR, and ss_mutex_wait_for().
Referenced by bm_add_event_request(), bm_close_buffer(), bm_empty_buffers(), bm_flush_cache(), bm_get_buffer_info(), bm_get_buffer_level(), bm_open_buffer(), bm_push_event(), bm_receive_event(), bm_remove_event_request(), bm_send_event(), bm_skip_event(), cm_cleanup(), and cm_watchdog().
         : bm_lock_buffer
  Purpose: Lock a buffer for exclusive access via system mutex calls.
  Input:
    INT    bufer_handle     Handle to the buffer to lock
  Output:
    none
  Function value:
    BM_SUCCESS              Successful completion
    BM_INVALID_HANDLE       Buffer handle is invalid
\********************************************************************/
{
   if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
      cm_msg(MERROR, "bm_lock_buffer", "invalid buffer handle %d", buffer_handle);
      return BM_INVALID_HANDLE;
   }
   ss_mutex_wait_for(_buffer[buffer_handle - 1].mutex, 0);
   return BM_SUCCESS;
}
INT bm_unlock_buffer (INT buffer_handle)
Definition at line 5479 of file midas.c.
References _buffer_entries, BM_INVALID_HANDLE, BM_SUCCESS, cm_msg, MERROR, and ss_mutex_release().
Referenced by bm_add_event_request(), bm_close_buffer(), bm_empty_buffers(), bm_flush_cache(), bm_get_buffer_info(), bm_get_buffer_level(), bm_open_buffer(), bm_push_event(), bm_receive_event(), bm_remove_event_request(), bm_send_event(), bm_skip_event(), cm_cleanup(), and cm_watchdog().
         : bm_unlock_buffer
  Purpose: Unlock a buffer via system mutex calls.
  Input:
    INT    bufer_handle     Handle to the buffer to lock
  Output:
    none
  Function value:
    BM_SUCCESS              Successful completion
    BM_INVALID_HANDLE       Buffer handle is invalid
\********************************************************************/
{
   if (buffer_handle > _buffer_entries || buffer_handle <= 0) {
      cm_msg(MERROR, "bm_unlock_buffer", "invalid buffer handle %d", buffer_handle);
      return BM_INVALID_HANDLE;
   }
   ss_mutex_release(_buffer[buffer_handle - 1].mutex);
   return BM_SUCCESS;
}
void cm_ack_ctrlc_pressed ()
Definition at line 4143 of file midas.c.
References FALSE.
Referenced by command_loop(), and scan_tree().
{
   _ctrlc_pressed = FALSE;
}
INT cm_asctime (char * str, INT buf_size)
Get time from MIDAS server and set local time.
Parameters:
str return time string
buf_size Maximum size of str
Returns:
CM_SUCCESS
Definition at line 1646 of file midas.c.
References CM_SUCCESS, rpc_call(), RPC_CM_ASCTIME, rpc_is_remote(), and ss_asctime().
Referenced by al_trigger_alarm(), cm_transition(), db_save_xml(), and rpc_server_dispatch().
{
   /* if connected to server, get time from there */
   if (rpc_is_remote())
      return rpc_call(RPC_CM_ASCTIME, str, buf_size);
   /* return local time */
   strcpy(str, ss_asctime());
   return CM_SUCCESS;
}
INT cm_check_client (HNDLE hDB, HNDLE hKeyClient)
Check if a client with a /system/client/xxx entry has a valid entry in the ODB client table. If not, remove that client from the /system/client tree.
Parameters:
hDB Handle to online database
hKeyClient Handle to client key
Returns:
CM_SUCCESS, CM_NO_CLIENT
Definition at line 1914 of file midas.c.
References DATABASE_HEADER::client, cm_delete_client_info(), cm_msg, CM_NO_CLIENT, CM_SUCCESS, DATABASE::database_header, db_get_key(), db_get_value(), db_lock_database(), db_unlock_database(), i, key, DATABASE_HEADER::max_client_index, MERROR, MINFO, KEY::name, name, NAME_LENGTH, status, DATABASE_CLIENT::tid, TID_STRING, and TRUE.
Referenced by cm_set_client_info().
{
#ifdef LOCAL_ROUTINES
   KEY key;
   DATABASE_HEADER *pheader;
   DATABASE_CLIENT *pclient;
   INT i, client_pid, status;
   char name[NAME_LENGTH];
   db_get_key(hDB, hKeyClient, &key);
   client_pid = atoi(key.name);
   i = sizeof(name);
   db_get_value(hDB, hKeyClient, "Name", name, &i, TID_STRING, TRUE);
   db_lock_database(hDB);
   if (_database[hDB - 1].attached) {
      pheader = _database[hDB - 1].database_header;
      pclient = pheader->client;
      /* loop through clients */
      for (i = 0; i < pheader->max_client_index; i++, pclient++)
         if (pclient->tid == client_pid)
            break;
      if (i == pheader->max_client_index) {
         /* client not found : delete ODB stucture */
         db_unlock_database(hDB);
         status = cm_delete_client_info(hDB, client_pid);
         if (status != CM_SUCCESS)
            cm_msg(MERROR, "cm_check_client", "cannot delete client info");
         else
            cm_msg(MINFO, "cm_check_clinet",
                   "Deleted /System/Clients/%d entry for client %s\n", client_pid, name);
         return CM_NO_CLIENT;
      }
   }
   db_unlock_database(hDB);
#endif                          /*LOCAL_ROUTINES */
   return CM_SUCCESS;
}
void cm_check_connect (void)
dox
Definition at line 2248 of file midas.c.
References cm_msg, and MERROR.
Referenced by cm_connect_experiment1().
{
   if (_hKeyClient)
      cm_msg(MERROR, "", "cm_disconnect_experiment not called at end of program");
}
INT cm_check_deferred_transition (void)
Check for any deferred transition. If a deferred transition handler has been registered via the cm_register_deferred_transition function, this routine should be called regularly. It checks if a transition request is pending. If so, it calld the registered handler if the transition should be done and then actually does the transition.
Returns:
CM_SUCCESS, <error> Error from cm_transition()
Definition at line 3482 of file midas.c.
References cm_msg, CM_SUCCESS, cm_transition(), FALSE, i, MERROR, status, SUCCESS, SYNC, TR_DEFERRED, TRANS_TABLE::transition, and TRUE.
Referenced by scheduler().
{
   INT i, status;
   char str[256];
   static BOOL first;
   if (_requested_transition == 0)
      first = TRUE;
   if (_requested_transition & _deferred_transition_mask) {
      for (i = 0; _deferred_trans_table[i].transition; i++)
         if (_deferred_trans_table[i].transition == _requested_transition)
            break;
      if (_deferred_trans_table[i].transition == _requested_transition) {
         if (((BOOL(*)(INT, BOOL)) _deferred_trans_table[i].func) (_requested_transition,
                                                                   first)) {
            status =
                cm_transition(_requested_transition | TR_DEFERRED, 0, str, sizeof(str),
                              SYNC, FALSE);
            if (status != CM_SUCCESS)
               cm_msg(MERROR, "cm_check_deferred_transition",
                      "Cannot perform deferred transition: %s", str);
            /* bypass hotlink and set _requested_transition directly to zero */
            _requested_transition = 0;
            return status;
         }
         first = FALSE;
      }
   }
   return SUCCESS;
}
INT cm_cleanup (char * client_name, BOOL ignore_timeout)
Remove hanging clients independent of their watchdog timeout.
Since this function does not obey the client watchdog timeout, it should be only called to remove clients which have their watchdog checking turned off or which are known to be dead. The normal client removement is done via cm_watchdog().
Currently (Sept. 02) there are two applications for that:
The ODBEdit command "cleanup", which can be used to remove clients which have their watchdog checking off, like the analyzer started with the "-d" flag for a debugging session.
The frontend init code to remove previous frontends. This can be helpful if a frontend dies. Normally, one would have to wait 60 sec. for a crashed frontend to be removed. Only then one can start again the frontend. Since the frontend init code contains a call to cm_cleanup(<frontend_name>), one can restart a frontend immediately.
Added ignore_timeout on Nov.03. A logger might have an increased tiemout of up to 60 sec. because of tape operations. If ignore_timeout is FALSE, the logger is then not killed if its inactivity is less than 60 sec., while in the previous implementation it was always killed after 2*WATCHDOG_INTERVAL.
Parameters:
client_name Client name, if zero check all clients
ignore_timeout If TRUE, ignore a possible increased timeout defined by each client.
Returns:
CM_SUCCESS
Definition at line 5147 of file midas.c.
References _buffer_entries, _database_entries, KEY::access_mode, OPEN_RECORD::access_mode, bm_lock_buffer(), bm_unlock_buffer(), BUFFER::buffer_header, DATABASE_HEADER::client, BUFFER_HEADER::client, DATABASE::client_index, BUFFER::client_index, cm_delete_client_info(), cm_msg, CM_SUCCESS, DATABASE::database_header, db_lock_database(), db_set_mode(), db_unlock_database(), FALSE, OPEN_RECORD::handle, i, interval, j, k, DATABASE_CLIENT::last_activity, BUFFER_CLIENT::last_activity, DATABASE_HEADER::max_client_index, BUFFER_HEADER::max_client_index, MAX_CLIENTS, DATABASE_CLIENT::max_index, MERROR, MINFO, MODE_EXCLUSIVE, MODE_WRITE, DATABASE_HEADER::name, DATABASE_CLIENT::name, BUFFER_HEADER::name, BUFFER_CLIENT::name, KEY::notify_count, DATABASE_HEADER::num_clients, BUFFER_HEADER::num_clients, DATABASE_CLIENT::open_record, DATABASE_CLIENT::pid, BUFFER_CLIENT::pid, BUFFER_CLIENT::port, BUFFER_CLIENT::read_wait, rpc_call(), RPC_CM_CLEANUP, rpc_is_remote(), ss_millitime(), ss_resume(), status, DATABASE_CLIENT::tid, TRUE, WATCHDOG_INTERVAL, DATABASE_CLIENT::watchdog_timeout, BUFFER_CLIENT::watchdog_timeout, and BUFFER_CLIENT::write_wait.
Referenced by command_loop(), main(), and rpc_server_dispatch().
{
   if (rpc_is_remote())
      return rpc_call(RPC_CM_CLEANUP, client_name);
#ifdef LOCAL_ROUTINES
   {
      BUFFER_HEADER *pheader = NULL;
      BUFFER_CLIENT *pbclient, *pbctmp;
      DATABASE_HEADER *pdbheader;
      DATABASE_CLIENT *pdbclient;
      KEY *pkey;
      INT client_pid;
      INT i, j, k, status, nc;
      BOOL bDeleted;
      char str[256];
      DWORD interval;
      /* check buffers */
      for (i = 0; i < _buffer_entries; i++)
         if (_buffer[i].attached) {
            /* update the last_activity entry to show that we are alive */
            pheader = _buffer[i].buffer_header;
            pbclient = pheader->client;
            pbclient[_buffer[i].client_index].last_activity = ss_millitime();
            /* now check other clients */
            for (j = 0; j < pheader->max_client_index; j++, pbclient++)
               if (j != _buffer[i].client_index && pbclient->pid &&
                   (client_name[0] == 0
                    || strncmp(pbclient->name, client_name, strlen(client_name)) == 0)) {
                  if (ignore_timeout)
                     interval = 2 * WATCHDOG_INTERVAL;
                  else
                     interval = pbclient->watchdog_timeout;
                  /* If client process has no activity, clear its buffer entry. */
                  if (ss_millitime() - pbclient->last_activity > interval) {
                     bm_lock_buffer(i + 1);
                     str[0] = 0;
                     /* now make again the check with the buffer locked */
                     if (ss_millitime() - pbclient->last_activity > interval) {
                        sprintf(str,
                                "Client %s on %s removed (via cleanup) (idle %1.1lfs,TO %1.0lfs)",
                                pbclient->name, pheader->name,
                                (ss_millitime() - pbclient->last_activity) / 1000.0,
                                interval / 1000.0);
                        /* clear entry from client structure in buffer header */
                        memset(&(pheader->client[j]), 0, sizeof(BUFFER_CLIENT));
                        /* calculate new max_client_index entry */
                        for (k = MAX_CLIENTS - 1; k >= 0; k--)
                           if (pheader->client[k].pid != 0)
                              break;
                        pheader->max_client_index = k + 1;
                        /* count new number of clients */
                        for (k = MAX_CLIENTS - 1, nc = 0; k >= 0; k--)
                           if (pheader->client[k].pid != 0)
                              nc++;
                        pheader->num_clients = nc;
                        /* check if anyone is wating and wake him up */
                        pbctmp = pheader->client;
                        for (k = 0; k < pheader->max_client_index; k++, pbctmp++)
                           if (pbctmp->pid && (pbctmp->write_wait || pbctmp->read_wait))
                              ss_resume(pbctmp->port, "B  ");
                     }
                     bm_unlock_buffer(i + 1);
                     /* display info message after unlocking buffer */
                     if (str[0])
                        cm_msg(MINFO, "cm_cleanup", str);
                     /* go again through whole list */
                     j = 0;
                  }
               }
         }
      /* check online databases */
      for (i = 0; i < _database_entries; i++)
         if (_database[i].attached) {
            /* update the last_activity entry to show that we are alive */
            db_lock_database(i + 1);
            pdbheader = _database[i].database_header;
            pdbclient = pdbheader->client;
            pdbclient[_database[i].client_index].last_activity = ss_millitime();
            /* now check other clients */
            for (j = 0; j < pdbheader->max_client_index; j++, pdbclient++)
               if (j != _database[i].client_index && pdbclient->pid &&
                   (client_name[0] == 0
                    || strncmp(pdbclient->name, client_name, strlen(client_name)) == 0)) {
                  client_pid = pdbclient->tid;
                  if (ignore_timeout)
                     interval = 2 * WATCHDOG_INTERVAL;
                  else
                     interval = pdbclient->watchdog_timeout;
                  /* If client process has no activity, clear its buffer entry. */
                  if (ss_millitime() - pdbclient->last_activity > interval) {
                     bDeleted = FALSE;
                     str[0] = 0;
                     /* now make again the check with the buffer locked */
                     if (ss_millitime() - pdbclient->last_activity > interval) {
                        sprintf(str,
                                "Client %s on %s removed (via cleanup) (idle %1.1lfs,TO %1.0lfs)",
                                pdbclient->name, pdbheader->name,
                                (ss_millitime() - pdbclient->last_activity) / 1000.0,
                                interval / 1000.0);
                        /* decrement notify_count for open records and clear exclusive mode */
                        for (k = 0; k < pdbclient->max_index; k++)
                           if (pdbclient->open_record[k].handle) {
                              pkey = (KEY *) ((char *) pdbheader +
                                              pdbclient->open_record[k].handle);
                              if (pkey->notify_count > 0)
                                 pkey->notify_count--;
                              if (pdbclient->open_record[k].access_mode & MODE_WRITE)
                                 db_set_mode(i + 1, pdbclient->open_record[k].handle,
                                             (WORD) (pkey->access_mode & ~MODE_EXCLUSIVE),
                                             2);
                           }
                        /* clear entry from client structure in buffer header */
                        memset(&(pdbheader->client[j]), 0, sizeof(DATABASE_CLIENT));
                        /* calculate new max_client_index entry */
                        for (k = MAX_CLIENTS - 1; k >= 0; k--)
                           if (pdbheader->client[k].pid != 0)
                              break;
                        pdbheader->max_client_index = k + 1;
                        /* count new number of clients */
                        for (k = MAX_CLIENTS - 1, nc = 0; k >= 0; k--)
                           if (pheader->client[k].pid != 0)
                              nc++;
                        pdbheader->num_clients = nc;
                        bDeleted = TRUE;
                     }
                     /* delete client entry after unlocking db */
                     if (bDeleted) {
                        db_unlock_database(i + 1);
                        /* display info message after unlocking buffer */
                        cm_msg(MINFO, "cm_cleanup", str);
                        status = cm_delete_client_info(i + 1, client_pid);
                        if (status != CM_SUCCESS)
                           cm_msg(MERROR, "cm_cleanup", "cannot delete client info");
                        /* re-lock database */
                        db_lock_database(i + 1);
                        pdbheader = _database[i].database_header;
                        pdbclient = pdbheader->client;
                        /* go again though whole list */
                        j = 0;
                     }
                  }
               }
            db_unlock_database(i + 1);
         }
   }
#endif                          /* LOCAL_ROUTINES */
   return CM_SUCCESS;
}
INT cm_connect_client (char * client_name, HNDLE * hConn)
Connect to a MIDAS client of the current experiment
Definition at line 2688 of file midas.c.
References cm_get_experiment_database(), CM_NO_CLIENT, db_enum_key(), db_find_key(), db_get_data(), DB_NO_MORE_SUBKEYS, DB_SUCCESS, equal_ustring(), hDB, hKey, HOST_NAME_LENGTH, hSubkey, i, length, name, NAME_LENGTH, rpc_client_connect(), status, TID_INT, TID_STRING, and TRUE.
Referenced by cam_init_rpc(), command_loop(), interprete(), rpc_master_bor(), rpc_slave_bor(), and show_cnaf_page().
{
   HNDLE hDB, hKeyRoot, hSubkey, hKey;
   INT status, i, length, port;
   char name[NAME_LENGTH], host_name[HOST_NAME_LENGTH];
   /* find client entry in ODB */
   cm_get_experiment_database(&hDB, &hKey);
   status = db_find_key(hDB, 0, "System/Clients", &hKeyRoot);
   if (status != DB_SUCCESS)
      return status;
   i = 0;
   do {
      /* search for client with specific name */
      status = db_enum_key(hDB, hKeyRoot, i++, &hSubkey);
      if (status == DB_NO_MORE_SUBKEYS)
         return CM_NO_CLIENT;
      status = db_find_key(hDB, hSubkey, "Name", &hKey);
      if (status != DB_SUCCESS)
         return status;
      length = NAME_LENGTH;
      status = db_get_data(hDB, hKey, name, &length, TID_STRING);
      if (status != DB_SUCCESS)
         return status;
      if (equal_ustring(name, client_name)) {
         status = db_find_key(hDB, hSubkey, "Server Port", &hKey);
         if (status != DB_SUCCESS)
            return status;
         length = sizeof(INT);
         status = db_get_data(hDB, hKey, &port, &length, TID_INT);
         if (status != DB_SUCCESS)
            return status;
         status = db_find_key(hDB, hSubkey, "Host", &hKey);
         if (status != DB_SUCCESS)
            return status;
         length = sizeof(host_name);
         status = db_get_data(hDB, hKey, host_name, &length, TID_STRING);
         if (status != DB_SUCCESS)
            return status;
         /* client found -> connect to its server port */
         return rpc_client_connect(host_name, port, client_name, hConn);
      }
   } while (TRUE);
}
INT cm_connect_experiment (char * host_name, char * exp_name, char * client_name, void(*)(char *) func)
dox This function connects to an existing MIDAS experiment. This must be the first call in a MIDAS application. It opens three TCP connection to the remote host (one for RPC calls, one to send events and one for hot-link notifications from the remote host) and writes client information into the ODB under /System/Clients.
Attention:
All MIDAS applications should evaluate the MIDAS_SERVER_HOST and MIDAS_EXPT_NAME environment variables as defaults to the host name and experiment name (see Environment_variables). For that purpose, the function cm_get_environment() should be called prior to cm_connect_experiment(). If command line parameters -h and -e are used, the evaluation should be done between cm_get_environment() and cm_connect_experiment(). The function cm_disconnect_experiment() must be called before a MIDAS application exits.
#include <stdio.h>
#include <midas.h>
main(int argc, char *argv[])
{
  INT  status, i;
  char host_name[256],exp_name[32];
  // get default values from environment
  cm_get_environment(host_name, exp_name);
  // parse command line parameters
  for (i=1 ; i<argc ; i++)
    {
    if (argv[i][0] == '-')
      {
      if (i+1 >= argc || argv[i+1][0] == '-')
        goto usage;
      if (argv[i][1] == 'e')
        strcpy(exp_name, argv[++i]);
      else if (argv[i][1] == 'h')
        strcpy(host_name, argv[++i]);
      else
        {
usage:
        printf("usage: test [-h Hostname] [-e Experiment]\n\n");
        return 1;
        }
      }
    }
  status = cm_connect_experiment(host_name, exp_name, "Test", NULL);
  if (status != CM_SUCCESS)
    return 1;
  ...do operations...
  cm_disconnect_experiment();
}
Parameters:
host_name Specifies host to connect to. Must be a valid IP host name. The string can be empty ("") if to connect to the local computer.
exp_name Specifies the experiment to connect to. If this string is empty, the number of defined experiments in exptab is checked. If only one experiment is defined, the function automatically connects to this one. If more than one experiment is defined, a list is presented and the user can interactively select one experiment.
client_name Client name of the calling program as it can be seen by others (like the scl command in ODBEdit).
func Callback function to read in a password if security has been enabled. In all command line applications this function is NULL which invokes an internal ss_gets() function to read in a password. In windows environments (MS Windows, X Windows) a function can be supplied to open a dialog box and read in the password. The argument of this function must be the returned password.
Returns:
CM_SUCCESS, CM_UNDEF_EXP, CM_SET_ERROR, RPC_NET_ERROR
CM_VERSION_MISMATCH MIDAS library version different on local and remote computer
Definition at line 2327 of file midas.c.
References cm_connect_experiment1(), cm_get_error(), CM_SUCCESS, DEFAULT_ODB_SIZE, DEFAULT_WATCHDOG_TIMEOUT, and status.
Referenced by cam_init_rpc(), interprete(), main(), odb_connect(), and process_file().
{
   INT status;
   char str[256];
   status = cm_connect_experiment1(host_name, exp_name, client_name,
                                   func, DEFAULT_ODB_SIZE, DEFAULT_WATCHDOG_TIMEOUT);
   if (status != CM_SUCCESS) {
      cm_get_error(status, str);
      puts(str);
   }
   return status;
}
INT cm_connect_experiment1 (char * host_name, char * exp_name, char * client_name, void(*)(char *) func, INT odb_size, DWORD watchdog_timeout)
Connect to a MIDAS experiment (to the online database) on a specific host.
Definition at line 2349 of file midas.c.
References _message_print, cm_check_connect(), cm_ctrlc_handler(), cm_disconnect_experiment(), cm_get_path(), cm_get_watchdog_params(), cm_msg, cm_register_server(), cm_scan_experiments(), cm_select_experiment(), cm_set_client_info(), cm_set_experiment_database(), cm_set_experiment_mutex(), cm_set_msg_print(), cm_set_path(), cm_set_watchdog_params(), CM_SUCCESS, CM_UNDEF_EXP, CM_WRONG_PASSWORD, db_check_record(), DB_CREATED, db_get_value(), db_open_database(), db_set_value(), DB_STRUCT_MISMATCH, DB_SUCCESS, DEFAULT_ODB_SIZE, DEFAULT_WATCHDOG_TIMEOUT, equal_ustring(), FALSE, hDB, HOST_NAME_LENGTH, i, MAX_EXPERIMENT, MERROR, MINFO, MT_ALL, name, experiment_table::name, NAME_LENGTH, rpc_get_internal_list(), rpc_get_option(), rpc_is_remote(), RPC_NET_ERROR, RPC_OHW_TYPE, rpc_register_functions(), rpc_server_connect(), rpc_server_disconnect(), rpc_set_name(), RPC_SUCCESS, RUNINFO_STR, size, SS_CREATED, ss_crypt(), ss_ctrlc_handler(), ss_getpass(), ss_mutex_create(), SS_SUCCESS, status, strcomb(), TID_INT, TID_STRING, and TRUE.
Referenced by cm_connect_experiment(), CMExperiment::Connect(), and main().
{
   INT status, i, mutex_elog, mutex_alarm, size;
   char local_host_name[HOST_NAME_LENGTH];
   char client_name1[NAME_LENGTH];
   char password[NAME_LENGTH], str[256], exp_name1[NAME_LENGTH];
   HNDLE hDB, hKeyClient;
   BOOL call_watchdog;
   RUNINFO_STR(runinfo_str);
   if (_hKeyClient)
      cm_disconnect_experiment();
   rpc_set_name(client_name);
   /* check for local host */
   if (equal_ustring(host_name, "local"))
      host_name[0] = 0;
#ifdef OS_WINNT
   {
      WSADATA WSAData;
      /* Start windows sockets */
      if (WSAStartup(MAKEWORD(1, 1), &WSAData) != 0)
         return RPC_NET_ERROR;
   }
#endif
   /* search for experiment name in exptab */
   if (exp_name == NULL)
      exp_name = "";
   strcpy(exp_name1, exp_name);
   if (exp_name1[0] == 0) {
      status = cm_select_experiment(host_name, exp_name1);
      if (status != CM_SUCCESS)
         return status;
   }
   /* connect to MIDAS server */
   if (host_name[0]) {
      status = rpc_server_connect(host_name, exp_name1);
      if (status != RPC_SUCCESS)
         return status;
      /* register MIDAS library functions */
      status = rpc_register_functions(rpc_get_internal_list(1), NULL);
      if (status != RPC_SUCCESS)
         return status;
   } else {
      /* lookup path for *SHM files and save it */
      status = cm_scan_experiments();
      if (status != CM_SUCCESS)
         return status;
      for (i = 0; i < MAX_EXPERIMENT && exptab[i].name[0]; i++)
         if (equal_ustring(exp_name1, exptab[i].name))
            break;
      /* return if experiment not defined */
      if (i == MAX_EXPERIMENT || exptab[i].name[0] == 0) {
         /* message should be displayed by application
            sprintf(str, "Experiment %s not defined in exptab\r", exp_name1);
            cm_msg(MERROR, str);
          */
         return CM_UNDEF_EXP;
      }
      cm_set_path(exptab[i].directory);
      /* create alarm and elog mutexes */
      status = ss_mutex_create("ALARM", &mutex_alarm);
      if (status != SS_CREATED && status != SS_SUCCESS) {
         cm_msg(MERROR, "cm_connect_experiment", "Cannot create alarm mutex");
         return status;
      }
      status = ss_mutex_create("ELOG", &mutex_elog);
      if (status != SS_CREATED && status != SS_SUCCESS) {
         cm_msg(MERROR, "cm_connect_experiment", "Cannot create elog mutex");
         return status;
      }
      cm_set_experiment_mutex(mutex_alarm, mutex_elog);
   }
   /* open ODB */
   if (odb_size == 0)
      odb_size = DEFAULT_ODB_SIZE;
   status = db_open_database("ODB", odb_size, &hDB, client_name);
   if (status != DB_SUCCESS && status != DB_CREATED) {
      cm_msg(MERROR, "cm_connect_experiment1", "cannot open database");
      return status;
   }
   /* now setup client info */
   gethostname(local_host_name, sizeof(local_host_name));
   /* check watchdog timeout */
   if (watchdog_timeout == 0)
      watchdog_timeout = DEFAULT_WATCHDOG_TIMEOUT;
   strcpy(client_name1, client_name);
   password[0] = 0;
   status = cm_set_client_info(hDB, &hKeyClient, local_host_name,
                               client_name1, rpc_get_option(0, RPC_OHW_TYPE),
                               password, watchdog_timeout);
   if (status == CM_WRONG_PASSWORD) {
      if (func == NULL)
         strcpy(str, ss_getpass("Password: "));
      else
         func(str);
      /* re-open database */
      status = db_open_database("ODB", odb_size, &hDB, client_name);
      if (status != DB_SUCCESS && status != DB_CREATED) {
         cm_msg(MERROR, "cm_connect_experiment1", "cannot open database");
         return status;
      }
      strcpy(password, ss_crypt(str, "mi"));
      status = cm_set_client_info(hDB, &hKeyClient, local_host_name,
                                  client_name1, rpc_get_option(0, RPC_OHW_TYPE),
                                  password, watchdog_timeout);
      if (status != CM_SUCCESS) {
         /* disconnect */
         if (rpc_is_remote())
            rpc_server_disconnect();
         return status;
      }
   }
   cm_set_experiment_database(hDB, hKeyClient);
   /* set experiment name in ODB */
   db_set_value(hDB, 0, "/Experiment/Name", exp_name1, NAME_LENGTH, 1, TID_STRING);
   /* set data dir in ODB */
   cm_get_path(str);
   size = sizeof(str);
   db_get_value(hDB, 0, "/Logger/Data dir", str, &size, TID_STRING, TRUE);
   /* check /runinfo structure */
   status = db_check_record(hDB, 0, "/Runinfo", strcomb(runinfo_str), FALSE);
   if (status == DB_STRUCT_MISMATCH) {
      cm_msg(MERROR, "cm_connect_experiment1",
             "Aborting on mismatching /Runinfo structure");
      cm_disconnect_experiment();
      abort();
   }
   /* register server to be able to be called by other clients */
   status = cm_register_server();
   if (status != CM_SUCCESS)
      return status;
   /* set watchdog timeout */
   cm_get_watchdog_params(&call_watchdog, &watchdog_timeout);
   size = sizeof(watchdog_timeout);
   sprintf(str, "/Programs/%s/Watchdog Timeout", client_name);
   db_get_value(hDB, 0, str, &watchdog_timeout, &size, TID_INT, TRUE);
   cm_set_watchdog_params(call_watchdog, watchdog_timeout);
   /* send startup notification */
   if (strchr(local_host_name, '.'))
      *strchr(local_host_name, '.') = 0;
   /* startup message is not displayed */
   _message_print = NULL;
   cm_msg(MINFO, "cm_connect_experiment", "Program %s on host %s started",
          client_name, local_host_name);
   /* enable system and user messages to stdout as default */
   cm_set_msg_print(MT_ALL, MT_ALL, puts);
   /* call cm_check_connect when exiting */
   atexit((void (*)(void)) cm_check_connect);
   /* register ctrl-c handler */
   ss_ctrlc_handler(cm_ctrlc_handler);
   return CM_SUCCESS;
}
INT cm_delete_client_info (HNDLE hDB, INT pid)
Delete client info from database
Parameters:
hDB Database handle
pid PID of entry to delete, zero for this process.
Returns:
CM_SUCCESS
Definition at line 1863 of file midas.c.
References _database_entries, CM_SUCCESS, db_delete_key1(), db_find_key1(), db_lock_database(), db_set_mode(), db_set_value(), DB_SUCCESS, db_unlock_database(), hKey, MODE_DELETE, MODE_READ, MODE_WRITE, rpc_is_remote(), ss_gettid(), status, TID_INT, and TRUE.
Referenced by cm_check_client(), cm_cleanup(), cm_disconnect_experiment(), cm_watchdog(), and rpc_server_receive().
{
#ifdef LOCAL_ROUTINES
   /* only do it if local */
   if (!rpc_is_remote()) {
      INT status;
      HNDLE hKey;
      char str[256];
      if (!pid)
         pid = ss_gettid();
      /* don't delete info from a closed database */
      if (_database_entries == 0)
         return CM_SUCCESS;
      /* make operation atomic by locking database */
      db_lock_database(hDB);
      sprintf(str, "System/Clients/%0d", pid);
      status = db_find_key1(hDB, 0, str, &hKey);
      if (status != DB_SUCCESS) {
         db_unlock_database(hDB);
         return status;
      }
      /* unlock client entry and delete it without locking DB */
      db_set_mode(hDB, hKey, MODE_READ | MODE_WRITE | MODE_DELETE, 2);
      db_delete_key1(hDB, hKey, 1, TRUE);
      db_unlock_database(hDB);
      /* touch notify key to inform others */
      status = 0;
      db_set_value(hDB, 0, "/System/Client Notify", &status, sizeof(status), 1, TID_INT);
   }
#endif                          /*LOCAL_ROUTINES */
   return CM_SUCCESS;
}
INT cm_disconnect_client (HNDLE hConn, BOOL bShutdown)
Disconnect from a MIDAS client
Parameters:
hConn Connection handle obtained via cm_connect_client()
bShutdown If TRUE, disconnect from client and shut it down (exit the client program) by sending a RPC_SHUTDOWN message
Returns:
see rpc_client_disconnect()
Definition at line 2754 of file midas.c.
References rpc_client_disconnect().
Referenced by cam_exit(), cam_init_rpc(), command_loop(), interprete(), rpc_master_eor(), rpc_slave_eor(), and show_cnaf_page().
{
   return rpc_client_disconnect(hConn, bShutdown);
}
INT cm_disconnect_experiment (void)
Disconnect from a MIDAS experiment.
Attention:
Should be the last call to a MIDAS library function in an application before it exits. This function removes the client information from the ODB, disconnects all TCP connections and frees all internal allocated memory. See cm_connect_experiment() for example.
Returns:
CM_SUCCESS
Definition at line 2768 of file midas.c.
References _event_buffer_size, _message_print, _msg_buffer, _net_recv_buffer, _net_recv_buffer_size, _net_send_buffer, _net_send_buffer_size, _tcp_buffer, _watchdog_last_called, bm_close_all_buffers(), cm_delete_client_info(), cm_get_experiment_database(), cm_msg, cm_set_experiment_database(), CM_SUCCESS, cm_watchdog(), db_close_all_databases(), db_close_all_records(), FALSE, hDB, hKey, HOST_NAME_LENGTH, M_FREE, MINFO, rpc_client_disconnect(), rpc_deregister_functions(), rpc_get_name(), rpc_get_server_option(), rpc_is_remote(), RPC_OSERVER_TYPE, rpc_server_disconnect(), rpc_server_shutdown(), ss_alarm(), and ST_REMOTE.
Referenced by cam_exit(), cam_init_rpc(), cm_connect_experiment1(), cmd_idle(), interprete(), main(), process_event(), receive_message(), register_equipment(), rpc_check_channels(), server_loop(), show_status_page(), siginthandler(), sigpipehandler(), and CMExperiment::~CMExperiment().
{
   HNDLE hDB, hKey;
   char local_host_name[HOST_NAME_LENGTH], client_name[80];
   /* send shutdown notification */
   rpc_get_name(client_name);
   gethostname(local_host_name, sizeof(local_host_name));
   if (strchr(local_host_name, '.'))
      *strchr(local_host_name, '.') = 0;
   /* disconnect message not displayed */
   _message_print = NULL;
   cm_msg(MINFO, "cm_disconnect_experiment", "Program %s on host %s stopped",
          client_name, local_host_name);
   if (rpc_is_remote()) {
      /* close open records */
      db_close_all_records();
      rpc_client_disconnect(-1, FALSE);
      rpc_server_disconnect();
   } else {
      rpc_client_disconnect(-1, FALSE);
#ifdef LOCAL_ROUTINES
      ss_alarm(0, cm_watchdog);
      _watchdog_last_called = 0;
#endif                          /* LOCAL_ROUTINES */
      /* delete client info */
      cm_get_experiment_database(&hDB, &hKey);
      if (hDB)
         cm_delete_client_info(hDB, 0);
      bm_close_all_buffers();
      db_close_all_databases();
   }
   if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_REMOTE)
      rpc_server_shutdown();
   /* free RPC list */
   rpc_deregister_functions();
   cm_set_experiment_database(0, 0);
   _msg_buffer = 0;
   /* free memory buffers */
   if (_event_buffer_size > 0) {
      M_FREE(_event_buffer);
      _event_buffer_size = 0;
   }
   if (_net_recv_buffer_size > 0) {
      M_FREE(_net_recv_buffer);
      _net_recv_buffer_size = 0;
   }
   if (_net_send_buffer_size > 0) {
      M_FREE(_net_send_buffer);
      _net_send_buffer_size = 0;
   }
   if (_tcp_buffer != NULL) {
      M_FREE(_tcp_buffer);
      _tcp_buffer = NULL;
   }
   return CM_SUCCESS;
}
INT cm_dispatch_ipc (char * message, int socket)
dox
Definition at line 4080 of file midas.c.
References bm_notify_client(), bm_push_event(), CM_SUCCESS, db_update_record(), hDB, and hKey.
Referenced by bm_open_buffer(), and db_open_database().
         : cm_dispatch_ipc
  Purpose: Called from ss_suspend if an IPC message arrives
  Input:
    INT   msg               IPC message we got, MSG_ODB/MSG_BM
    INT   p1, p2            Optional parameters
    int   socket            Optional server socket
  Output:
    none
  Function value:
    CM_SUCCESS              Successful completion
\********************************************************************/
{
   if (message[0] == 'O') {
      HNDLE hDB, hKey;
      sscanf(message + 2, "%d %d", &hDB, &hKey);
      return db_update_record(hDB, hKey, socket);
   }
   /* message == "B  " means "resume event sender" */
   if (message[0] == 'B' && message[2] != ' ') {
      char str[80];
      strcpy(str, message + 2);
      if (strchr(str, ' '))
         *strchr(str, ' ') = 0;
      if (socket)
         return bm_notify_client(str, socket);
      else
         return bm_push_event(str);
   }
   return CM_SUCCESS;
}
INT cm_enable_watchdog (BOOL flag)
Temporarily disable watchdog calling. Used for tape IO not to interrupt lengthy operations like mount.
Parameters:
flag FALSE for disable, TRUE for re-enable
Returns:
CM_SUCCESS
Definition at line 4949 of file midas.c.
References cm_set_watchdog_params(), CM_SUCCESS, DEFAULT_WATCHDOG_TIMEOUT, FALSE, timeout, and TRUE.
Referenced by ss_tape_fskip(), ss_tape_get_blockn(), ss_tape_mount(), ss_tape_open(), ss_tape_rewind(), ss_tape_rskip(), ss_tape_spool(), ss_tape_unmount(), and ss_tape_write_eof().
{
   static INT timeout = DEFAULT_WATCHDOG_TIMEOUT;
   static BOOL call_flag = FALSE;
   if (flag) {
      if (call_flag)
         cm_set_watchdog_params(TRUE, timeout);
   } else {
      call_flag = _call_watchdog;
      timeout = _watchdog_timeout;
      if (call_flag)
         cm_set_watchdog_params(FALSE, 0);
   }
   return CM_SUCCESS;
}
INT cm_execute (char * command, char * result, INT bufsize)
Executes command via system() call
Parameters:
command Command string to execute
result stdout of command
bufsize string size in byte
Returns:
CM_SUCCESS
Definition at line 4219 of file midas.c.
References CM_SUCCESS, MAX, n, read, rpc_call(), RPC_CM_EXECUTE, rpc_is_remote(), and ss_getpid().
Referenced by command_loop(), and rpc_server_dispatch().
{
   char str[256];
   INT n;
   int fh;
   if (rpc_is_remote())
      return rpc_call(RPC_CM_EXECUTE, command, result, bufsize);
   if (bufsize > 0) {
      strcpy(str, command);
      sprintf(str, "%s > %d.tmp", command, ss_getpid());
      system(str);
      sprintf(str, "%d.tmp", ss_getpid());
      fh = open(str, O_RDONLY, 0644);
      result[0] = 0;
      if (fh) {
         n = read(fh, result, bufsize - 1);
         result[MAX(0, n)] = 0;
         close(fh);
      }
      remove(str);
   } else
      system(command);
   return CM_SUCCESS;
}
INT cm_exist (char * name, BOOL bUnique)
Check if a MIDAS client exists in current experiment
Parameters:
name Client name
bUnique If true, look for the exact client name. If false, look for namexxx where xxx is a any number
Returns:
CM_SUCCESS, CM_NO_CLIENT
Definition at line 5069 of file midas.c.
References cm_get_experiment_database(), CM_NO_CLIENT, CM_SUCCESS, db_enum_key(), db_find_key(), db_get_value(), DB_NO_KEY, DB_NO_MORE_SUBKEYS, DB_SUCCESS, equal_ustring(), hDB, hKey, hSubkey, i, NAME_LENGTH, rpc_call(), RPC_CM_EXIST, rpc_is_remote(), size, status, TID_STRING, and TRUE.
Referenced by al_check(), compose_status(), interprete(), main(), rpc_server_dispatch(), show_programs_page(), and show_status_page().
{
   INT status, i, size;
   HNDLE hDB, hKeyClient, hKey, hSubkey;
   char client_name[NAME_LENGTH];
   if (rpc_is_remote())
      return rpc_call(RPC_CM_EXIST, name, bUnique);
   cm_get_experiment_database(&hDB, &hKeyClient);
   status = db_find_key(hDB, 0, "System/Clients", &hKey);
   if (status != DB_SUCCESS)
      return DB_NO_KEY;
   /* loop over all clients */
   for (i = 0;; i++) {
      status = db_enum_key(hDB, hKey, i, &hSubkey);
      if (status == DB_NO_MORE_SUBKEYS)
         break;
      if (hSubkey == hKeyClient)
         continue;
      if (status == DB_SUCCESS) {
         /* get client name */
         size = sizeof(client_name);
         db_get_value(hDB, hSubkey, "Name", client_name, &size, TID_STRING, TRUE);
         if (equal_ustring(client_name, name))
            return CM_SUCCESS;
         if (!bUnique) {
            client_name[strlen(name)] = 0;      /* strip number */
            if (equal_ustring(client_name, name))
               return CM_SUCCESS;
         }
      }
   }
   return CM_NO_CLIENT;
}
INT cm_get_client_info (char * client_name)
Get info about the current client
Parameters:
*client_name Client name.
Returns:
CM_SUCCESS, CM_UNDEF_EXP
Definition at line 2153 of file midas.c.
References cm_get_experiment_database(), CM_SUCCESS, CM_UNDEF_EXP, db_find_key(), db_get_data(), DB_SUCCESS, hDB, hKey, length, NAME_LENGTH, status, and TID_STRING.
Referenced by bm_open_buffer(), debug_print(), and MidasMessage().
{
   INT status, length;
   HNDLE hDB, hKey;
   /* get root key of client */
   cm_get_experiment_database(&hDB, &hKey);
   if (!hDB) {
      client_name[0] = 0;
      return CM_UNDEF_EXP;
   }
   status = db_find_key(hDB, hKey, "Name", &hKey);
   if (status != DB_SUCCESS)
      return status;
   length = NAME_LENGTH;
   status = db_get_data(hDB, hKey, client_name, &length, TID_STRING);
   if (status != DB_SUCCESS)
      return status;
   return CM_SUCCESS;
}
INT cm_get_environment (char * host_name, int host_name_size, char * exp_name, int exp_name_size)
Returns MIDAS environment variables.
Attention:
This function can be used to evaluate the standard MIDAS environment variables before connecting to an experiment (see Environment_variables). The usual way is that the host name and experiment name are first derived from the environment variables MIDAS_SERVER_HOST and MIDAS_EXPT_NAME. They can then be superseded by command line parameters with -h and -e flags.
#include <stdio.h>
#include <midas.h>
main(int argc, char *argv[])
{
  INT  status, i;
  char host_name[256],exp_name[32];
  // get default values from environment
  cm_get_environment(host_name, exp_name);
  // parse command line parameters
  for (i=1 ; i<argc ; i++)
    {
    if (argv[i][0] == '-')
      {
      if (i+1 >= argc || argv[i+1][0] == '-')
        goto usage;
      if (argv[i][1] == 'e')
        strcpy(exp_name, argv[++i]);
      else if (argv[i][1] == 'h')
        strcpy(host_name, argv[++i]);
      else
        {
usage:
        printf("usage: test [-h Hostname] [-e Experiment]\n\n");
        return 1;
        }
      }
    }
  status = cm_connect_experiment(host_name, exp_name, "Test", NULL);
  if (status != CM_SUCCESS)
    return 1;
    ...do anyting...
  cm_disconnect_experiment();
}
Parameters:
host_name Contents of MIDAS_SERVER_HOST environment variable.
host_name_size string length
exp_name Contents of MIDAS_EXPT_NAME environment variable.
exp_name_size string length
Returns:
CM_SUCCESS
Definition at line 2229 of file midas.c.
References CM_SUCCESS, and strlcpy().
{
   host_name[0] = exp_name[0] = 0;
   if (getenv("MIDAS_SERVER_HOST"))
      strlcpy(host_name, getenv("MIDAS_SERVER_HOST"), host_name_size);
   if (getenv("MIDAS_EXPT_NAME"))
      strlcpy(exp_name, getenv("MIDAS_EXPT_NAME"), exp_name_size);
   return CM_SUCCESS;
}
INT cm_get_experiment_database (HNDLE * hDB, HNDLE * hKeyClient)
dox Get the handle to the ODB from the currently connected experiment.
Attention:
This function returns the handle of the online database (ODB) which can be used in future db_xxx() calls. The hkeyclient key handle can be used to access the client information in the ODB. If the client key handle is not needed, the parameter can be NULL.
HNDLE hDB, hkeyclient;
 char  name[32];
 int   size;
 db_get_experiment_database(&hdb, &hkeyclient);
 size = sizeof(name);
 db_get_value(hdb, hkeyclient, "Name", name, &size, TID_STRING, TRUE);
 printf("My name is %s\n", name);
Parameters:
hDB Database handle.
hKeyClient Handle for key where search starts, zero for root.
Returns:
CM_SUCCESS
Definition at line 2913 of file midas.c.
References CM_SUCCESS, RPC_CLIENT_HANDLE, rpc_get_server_option(), and RPC_ODB_HANDLE.
Referenced by add_data_dir(), al_check(), al_evaluate_condition(), al_reset_alarm(), al_trigger_alarm(), al_trigger_class(), ana_end_of_run(), analyzer_init(), assemble_prompt(), bb_psi_init(), bl_psi_init(), caen170a_init(), cam_init_rpc(), check_web_password(), cm_connect_client(), cm_disconnect_experiment(), cm_exist(), cm_get_client_info(), cm_msg_log(), cm_msg_log1(), cm_msg_retrieve(), cm_register_deferred_transition(), cm_register_function(), cm_register_server(), cm_register_transition(), cm_set_transition_sequence(), cm_set_watchdog_params(), cm_shutdown(), cm_transition(), cmd_dir(), command_loop(), CMExperiment::Connect(), das1600_init(), dastemp_init(), el_delete_message(), el_search_message(), el_submit(), epics_ca_get(), epics_ca_init(), epics_ca_set(), exec_script(), feodb_file_dump(), frontend_init(), gen_idle(), gen_init(), gen_odb_attachment(), gen_read(), generate_hist_graph(), hv_init(), hv_read(), interprete(), is_editable(), lrs1440_init(), lrs1445a_init(), lrs1454_init(), lrs2415_init(), lrs4032_init(), main(), MDQ_DAQLivetime_eor(), MDQ_IslandRate_eor(), MDQ_RunTime_eor(), MDQ_TDCCheck_eor(), MDQ_Thresholds_eor(), mscbdev_init(), multi_init(), multi_read(), multi_read_output(), nitronic_init(), null_init(), nulldev_init(), odb_connect(), process_file(), rpc_server_receive(), rs232_init(), show_alarm_page(), show_cnaf_page(), show_config_page(), show_create_page(), show_custom_page(), show_delete_page(), show_elog_delete(), show_elog_new(), show_elog_page(), show_elog_query(), show_elog_submit_query(), show_find_page(), show_form_query(), show_hist_config_page(), show_hist_page(), show_messages_page(), show_odb_page(), show_programs_page(), show_query_page(), show_rawfile(), show_sc_page(), show_set_page(), show_start_page(), show_status_page(), submit_elog(), submit_form(), tcpip_init(), UpdateDetectorBankNameMap(), and ybos_log_dump().
{
   if (_hDB) {
      if (hDB != NULL)
         *hDB = _hDB;
      if (hKeyClient != NULL)
         *hKeyClient = _hKeyClient;
   } else {
      if (hDB != NULL)
         *hDB = rpc_get_server_option(RPC_ODB_HANDLE);
      if (hKeyClient != NULL)
         *hKeyClient = rpc_get_server_option(RPC_CLIENT_HANDLE);
   }
   return CM_SUCCESS;
}
INT cm_get_experiment_mutex (INT * mutex_alarm, INT * mutex_elog)
dox
Definition at line 2934 of file midas.c.
References CM_SUCCESS.
Referenced by al_check(), el_delete_message(), and el_submit().
         : cm_get_experiment_mutex
  Purpose: Get the handle to the experiment wide mutexes
  Input:
    none
  Output:
    INT    mutex_alarm      Alarm mutex
    INT    mutex_elog       Elog mutex
  Function value:
    CM_SUCCESS              Successful completion
\********************************************************************/
{
   if (mutex_alarm)
      *mutex_alarm = _mutex_alarm;
   if (mutex_elog)
      *mutex_elog = _mutex_elog;
   return CM_SUCCESS;
}
INT cm_get_path (char * path)
Return the path name previously set with cm_set_path.
Parameters:
path Pathname
Returns:
CM_SUCCESS
Definition at line 1735 of file midas.c.
References CM_SUCCESS.
Referenced by cm_connect_experiment1(), cm_msg_log(), cm_msg_log1(), cm_msg_retrieve(), command_loop(), logger_init(), ss_mutex_create(), ss_shm_close(), ss_shm_flush(), and ss_shm_open().
{
   strcpy(path, _path_name);
   return CM_SUCCESS;
}
char* cm_get_version (void)
Return version number of current MIDAS library as a string
Returns:
version number * 100
Definition at line 1704 of file midas.c.
References MIDAS_VERSION.
Referenced by check_web_password(), cm_transition(), command_loop(), compose_status(), generate_hist_graph(), help_page(), interprete(), main(), redirect(), rpc_client_accept(), rpc_client_connect(), rpc_server_accept(), rpc_server_connect(), show_alarm_page(), show_cnaf_page(), show_custom_page(), show_elog_new(), show_elog_page(), show_elog_query(), show_elog_submit_query(), show_error(), show_experiment_page(), show_form_query(), show_header(), show_messages_page(), show_password_page(), show_rawfile(), show_status_page(), submit_elog(), and submit_form().
{
   return MIDAS_VERSION;
}
INT cm_get_watchdog_info (HNDLE hDB, char * client_name, DWORD * timeout, DWORD * last)
Return watchdog information about specific client
Parameters:
hDB ODB handle
client_name ODB client name
timeout Timeout for this application in seconds
last Last time watchdog was called in msec
Returns:
CM_SUCCESS, CM_NO_CLIENT, DB_INVALID_HANDLE
Definition at line 3134 of file midas.c.
References _database_entries, DATABASE_HEADER::client, cm_msg, CM_NO_CLIENT, CM_SUCCESS, DATABASE::database_header, DB_INVALID_HANDLE, db_lock_database(), db_unlock_database(), equal_ustring(), i, DATABASE_CLIENT::last_activity, DATABASE_HEADER::max_client_index, MERROR, DATABASE_CLIENT::name, DATABASE_CLIENT::pid, rpc_call(), RPC_CM_GET_WATCHDOG_INFO, rpc_is_remote(), ss_millitime(), and DATABASE_CLIENT::watchdog_timeout.
Referenced by command_loop(), and rpc_server_dispatch().
{
   if (rpc_is_remote())
      return rpc_call(RPC_CM_GET_WATCHDOG_INFO, hDB, client_name, timeout, last);
#ifdef LOCAL_ROUTINES
   {
      DATABASE_HEADER *pheader;
      DATABASE_CLIENT *pclient;
      INT i;
      if (hDB > _database_entries || hDB <= 0) {
         cm_msg(MERROR, "cm_get_watchdog_info", "invalid database handle");
         return DB_INVALID_HANDLE;
      }
      if (!_database[hDB - 1].attached) {
         cm_msg(MERROR, "cm_get_watchdog_info", "invalid database handle");
         return DB_INVALID_HANDLE;
      }
      /* lock database */
      db_lock_database(hDB);
      pheader = _database[hDB - 1].database_header;
      pclient = pheader->client;
      /* find client */
      for (i = 0; i < pheader->max_client_index; i++, pclient++)
         if (pclient->pid && equal_ustring(pclient->name, client_name)) {
            *timeout = pclient->watchdog_timeout;
            *last = ss_millitime() - pclient->last_activity;
            db_unlock_database(hDB);
            return CM_SUCCESS;
         }
      *timeout = *last = 0;
      db_unlock_database(hDB);
      return CM_NO_CLIENT;
   }
#else                           /* LOCAL_ROUTINES */
   return CM_SUCCESS;
#endif                          /* LOCAL_ROUTINES */
}
INT cm_get_watchdog_params (BOOL * call_watchdog, DWORD * timeout)
Return the current watchdog parameters
Parameters:
call_watchdog Call the cm_watchdog routine periodically
timeout Timeout for this application in seconds
Returns:
CM_SUCCESS
Definition at line 3114 of file midas.c.
References CM_SUCCESS.
Referenced by bm_open_buffer(), cm_connect_experiment1(), cm_set_client_info(), db_open_database(), lazy_copy(), lazy_main(), log_callback(), and log_write().
{
   if (call_watchdog)
      *call_watchdog = _call_watchdog;
   if (timeout)
      *timeout = _watchdog_timeout;
   return CM_SUCCESS;
}
BOOL cm_is_ctrlc_pressed ()
Definition at line 4138 of file midas.c.
Referenced by check_abort(), command_loop(), and scan_tree().
{
   return _ctrlc_pressed;
}
INT cm_list_experiments (char * host_name, char exp_name[MAX_EXPERIMENT][NAME_LENGTH])
Connect to a MIDAS server and return all defined experiments in *exp_name[MAX_EXPERIMENTS]
Parameters:
host_name Internet host name.
exp_name list of experiment names
Returns:
CM_SUCCESS, RPC_NET_ERROR
Definition at line 2546 of file midas.c.
References closesocket, cm_msg, cm_scan_experiments(), CM_SUCCESS, equal_ustring(), i, MAX_EXPERIMENT, MERROR, MIDAS_TCP_PORT, name, recv_string(), RPC_NET_ERROR, send(), and status.
Referenced by cm_select_experiment(), CMExperiment::Connect(), interprete(), and CMHostDlg::OnKillfocusHost().
{
   INT i, status;
   struct sockaddr_in bind_addr;
   INT sock;
   char str[MAX_EXPERIMENT * NAME_LENGTH];
   struct hostent *phe;
   if (host_name[0] == 0 || equal_ustring(host_name, "local")) {
      status = cm_scan_experiments();
      if (status != CM_SUCCESS)
         return status;
      for (i = 0; i < MAX_EXPERIMENT; i++)
         strcpy(exp_name[i], exptab[i].name);
      return CM_SUCCESS;
   }
#ifdef OS_WINNT
   {
      WSADATA WSAData;
      /* Start windows sockets */
      if (WSAStartup(MAKEWORD(1, 1), &WSAData) != 0)
         return RPC_NET_ERROR;
   }
#endif
   /* create a new socket for connecting to remote server */
   sock = socket(AF_INET, SOCK_STREAM, 0);
   if (sock == -1) {
      cm_msg(MERROR, "cm_list_experiments", "cannot create socket");
      return RPC_NET_ERROR;
   }
   /* connect to remote node */
   memset(&bind_addr, 0, sizeof(bind_addr));
   bind_addr.sin_family = AF_INET;
   bind_addr.sin_addr.s_addr = 0;
   bind_addr.sin_port = htons((short) MIDAS_TCP_PORT);
#ifdef OS_VXWORKS
   {
      INT host_addr;
      host_addr = hostGetByName(host_name);
      memcpy((char *) &(bind_addr.sin_addr), &host_addr, 4);
   }
#else
   phe = gethostbyname(host_name);
   if (phe == NULL) {
      cm_msg(MERROR, "cm_list_experiments", "cannot get host name");
      return RPC_NET_ERROR;
   }
   memcpy((char *) &(bind_addr.sin_addr), phe->h_addr, phe->h_length);
#endif
#ifdef OS_UNIX
   do {
      status = connect(sock, (void *) &bind_addr, sizeof(bind_addr));
      /* don't return if an alarm signal was cought */
   } while (status == -1 && errno == EINTR);
#else
   status = connect(sock, (struct sockaddr *) &bind_addr, sizeof(bind_addr));
#endif
   if (status != 0) {
/*    cm_msg(MERROR, "cannot connect"); message should be displayed by application */
      return RPC_NET_ERROR;
   }
   /* request experiment list */
   send(sock, "I", 2, 0);
   for (i = 0; i < MAX_EXPERIMENT; i++) {
      exp_name[i][0] = 0;
      status = recv_string(sock, str, sizeof(str), 1000);
      if (status < 0)
         return RPC_NET_ERROR;
      if (status == 0)
         break;
      strcpy(exp_name[i], str);
   }
   exp_name[i][0] = 0;
   closesocket(sock);
   return CM_SUCCESS;
}
INT cm_register_deferred_transition (INT transition, BOOL(*)(INT, BOOL) func)
dox Register a deferred transition handler. If a client is registered as a deferred transition handler, it may defer a requested transition by returning FALSE until a certain condition (like a motor reaches its end position) is reached.
Parameters:
transition One of TR_xxx
(*func) Function which gets called whenever a transition is requested. If it returns FALSE, the transition is not performed.
Returns:
CM_SUCCESS, <error> Error from ODB access
Definition at line 3421 of file midas.c.
References cm_get_experiment_database(), cm_msg, CM_SUCCESS, db_find_key(), db_get_value(), db_open_record(), db_set_mode(), db_set_value(), DB_SUCCESS, TRANS_TABLE::func, hDB, hKey, i, MERROR, MODE_READ, MODE_WRITE, name, size, status, TID_INT, trans_name, TRANS_TABLE::transition, and TRUE.
Referenced by frontend_init().
{
   INT status, i, size;
   char tr_key_name[256];
   HNDLE hDB, hKey;
   cm_get_experiment_database(&hDB, &hKey);
   for (i = 0; _deferred_trans_table[i].transition; i++)
      if (_deferred_trans_table[i].transition == transition)
         _deferred_trans_table[i].func = (int (*)(int, char *)) func;
   /* set new transition mask */
   _deferred_transition_mask |= transition;
   for (i = 0; i < 13; i++)
      if (trans_name[i].transition == transition)
         break;
   sprintf(tr_key_name, "Transition %s DEFERRED", trans_name[i].name);
   /* unlock database */
   db_set_mode(hDB, hKey, MODE_READ | MODE_WRITE, TRUE);
   /* set value */
   i = 0;
   status = db_set_value(hDB, hKey, tr_key_name, &i, sizeof(INT), 1, TID_INT);
   if (status != DB_SUCCESS)
      return status;
   /* re-lock database */
   db_set_mode(hDB, hKey, MODE_READ, TRUE);
   /* hot link requested transition */
   size = sizeof(_requested_transition);
   db_get_value(hDB, 0, "/Runinfo/Requested Transition", &_requested_transition, &size,
                TID_INT, TRUE);
   db_find_key(hDB, 0, "/Runinfo/Requested Transition", &hKey);
   status =
       db_open_record(hDB, hKey, &_requested_transition, sizeof(INT), MODE_READ, NULL,
                      NULL);
   if (status != DB_SUCCESS) {
      cm_msg(MERROR, "cm_register_deferred_transition",
             "Cannot hotlink /Runinfo/Requested Transition");
      return status;
   }
   return CM_SUCCESS;
}
INT cm_register_function (INT id, INT(*)(INT, void **) func)
dox
Definition at line 4255 of file midas.c.
References cm_get_experiment_database(), CM_SUCCESS, db_set_mode(), db_set_value(), DB_SUCCESS, hDB, hKey, MODE_READ, MODE_WRITE, rpc_register_function(), RPC_SUCCESS, status, TID_BOOL, and TRUE.
Referenced by main(), and register_equipment().
         : cm_register_function
  Purpose: Call rpc_register_function and publish the registered
           function under system/clients/<pid>/RPC
  Input:
    INT      id             RPC ID
    INT      *func          New dispatch function
  Output:
   <implicit: func gets copied to rpc_list>
  Function value:
   CM_SUCCESS               Successful completion
   RPC_INVALID_ID           RPC ID not found
\********************************************************************/
{
   HNDLE hDB, hKey;
   INT status;
   char str[80];
   status = rpc_register_function(id, func);
   if (status != RPC_SUCCESS)
      return status;
   cm_get_experiment_database(&hDB, &hKey);
   /* create new key for this id */
   status = 1;
   sprintf(str, "RPC/%d", id);
   db_set_mode(hDB, hKey, MODE_READ | MODE_WRITE, TRUE);
   status = db_set_value(hDB, hKey, str, &status, sizeof(BOOL), 1, TID_BOOL);
   db_set_mode(hDB, hKey, MODE_READ, TRUE);
   if (status != DB_SUCCESS)
      return status;
   return CM_SUCCESS;
}
INT cm_register_server (void)
dox
Definition at line 3186 of file midas.c.
References _server_registered, cm_get_experiment_database(), CM_SUCCESS, db_find_key(), db_set_data(), db_set_mode(), DB_SUCCESS, hDB, hKey, MODE_READ, MODE_WRITE, rpc_get_internal_list(), rpc_register_functions(), rpc_register_server(), RPC_SUCCESS, ST_REMOTE, status, TID_INT, and TRUE.
Referenced by cm_connect_experiment1().
         : cm_register_server
  Purpose: Register a server which can be called from other clients
           of a specific experiment.
  Input:
    none
  Output:
    none
  Function value:
    CM_SUCCESS              Successful completion
\********************************************************************/
{
   INT status, port;
   HNDLE hDB, hKey;
   if (!_server_registered) {
      port = 0;
      status = rpc_register_server(ST_REMOTE, NULL, &port, NULL);
      if (status != RPC_SUCCESS)
         return status;
      _server_registered = TRUE;
      /* register MIDAS library functions */
      rpc_register_functions(rpc_get_internal_list(1), NULL);
      /* store port number in ODB */
      cm_get_experiment_database(&hDB, &hKey);
      status = db_find_key(hDB, hKey, "Server Port", &hKey);
      if (status != DB_SUCCESS)
         return status;
      /* unlock database */
      db_set_mode(hDB, hKey, MODE_READ | MODE_WRITE, TRUE);
      /* set value */
      status = db_set_data(hDB, hKey, &port, sizeof(INT), 1, TID_INT);
      if (status != DB_SUCCESS)
         return status;
      /* lock database */
      db_set_mode(hDB, hKey, MODE_READ, TRUE);
   }
   return CM_SUCCESS;
}
INT cm_register_transition (INT transition, INT(*)(INT, char *) func, INT sequence_number)
dox Registers a callback function for run transitions. This function internally registers the transition callback function and publishes its request for transition notification by writing a transition request to /System/Clients/<pid>/Transition XXX. Other clients making a transition scan the transition requests of all clients and call their transition callbacks via RPC.
Clients can register for transitions (Start/Stop/Pause/Resume) in a given sequence. All sequence numbers given in the registration are sorted on a transition and the clients are contacted in ascending order. By default, all programs register with a sequence number of 500. The logger however uses 200 for start, so that it can open files before the other clients are contacted, and 800 for stop, so that the files get closed when all other clients have gone already through the stop trantition.
The callback function returns CM_SUCCESS if it can perform the transition or a value larger than one in case of error. An error string can be copied into the error variable.
Attention:
The callback function will be called on transitions from inside the cm_yield() function which therefore must be contained in the main program loop.
INT start(INT run_number, char *error)
{
  if (<not ok>)
    {
    strcpy(error, "Cannot start because ...");
    return 2;
    }
  printf("Starting run %d\n", run_number);
  return CM_SUCCESS;
}
main()
{
  ...
  cm_register_transition(TR_START, start, 500);
  do
    {
    status = cm_yield(1000);
    } while (status != RPC_SHUTDOWN &&
             status != SS_ABORT);
  ...
}
Parameters:
transition Transition to register for (see)
func Callback function.
Returns:
CM_SUCCESS
Definition at line 3292 of file midas.c.
References cm_get_experiment_database(), CM_INVALID_TRANSITION, cm_msg, CM_SUCCESS, CM_TOO_MANY_REQUESTS, db_find_key(), db_get_key(), db_set_data_index(), db_set_mode(), db_set_value(), DB_SUCCESS, TRANS_TABLE::func, hDB, hKey, i, key, MAX_TRANSITIONS, MERROR, MODE_READ, MODE_WRITE, name, KEY::num_values, RPC_RC_TRANSITION, rpc_register_function(), rpc_transition_dispatch(), TRANS_TABLE::sequence_number, status, TID_INT, TR_PAUSE, TR_RESUME, TR_START, TR_STOP, trans_name, TRANS_TABLE::transition, and TRUE.
{
   INT status, i;
   HNDLE hDB, hKey, hKeyTrans;
   KEY key;
   char str[256];
   /* check for valid transition */
   if (transition != TR_START && transition != TR_STOP &&
       transition != TR_PAUSE && transition != TR_RESUME) {
         cm_msg(MERROR, "cm_transition", "Invalid transition request \"%d\"", transition);
         return CM_INVALID_TRANSITION;
      }
   cm_get_experiment_database(&hDB, &hKey);
   rpc_register_function(RPC_RC_TRANSITION, rpc_transition_dispatch);
   /* find empty slot */
   for (i = 0; i < MAX_TRANSITIONS ; i++)
      if (!_trans_table[i].transition)
         break;
   if (i == MAX_TRANSITIONS) {
      cm_msg(MERROR, "cm_register_transition",
         "To many transition registrations. Please increase MAX_TRANSITIONS and recompile");
      return CM_TOO_MANY_REQUESTS;
   }
   _trans_table[i].transition = transition;
   _trans_table[i].func = func;
   _trans_table[i].sequence_number = sequence_number;
   for (i = 0; i < 13; i++)
      if (trans_name[i].transition == transition)
         break;
   sprintf(str, "Transition %s", trans_name[i].name);
   /* unlock database */
   db_set_mode(hDB, hKey, MODE_READ | MODE_WRITE, TRUE);
   /* set value */
   status = db_find_key(hDB, hKey, str, &hKeyTrans);
   if (!hKeyTrans) {
      status = db_set_value(hDB, hKey, str, &sequence_number, sizeof(INT), 1, TID_INT);
      if (status != DB_SUCCESS)
         return status;
   } else {
      status = db_get_key(hDB, hKeyTrans, &key);
      if (status != DB_SUCCESS)
         return status;
      status = db_set_data_index(hDB, hKeyTrans, &sequence_number, sizeof(INT), key.num_values, TID_INT);
      if (status != DB_SUCCESS)
         return status;
   }
   /* re-lock database */
   db_set_mode(hDB, hKey, MODE_READ, TRUE);
   return CM_SUCCESS;
}
INT cm_scan_experiments (void)
dox Scan the "exptab" file for MIDAS experiment names and save them for later use by rpc_server_accept(). The file is first searched under $MIDAS/exptab if present, then the directory from argv[0] is probed.
Returns:
CM_SUCCESS
CM_UNDEF_EXP exptab not found and MIDAS_DIR not set
Definition at line 1771 of file midas.c.
References CM_SUCCESS, CM_UNDEF_ENVIRON, DIR_SEPARATOR, DIR_SEPARATOR_STR, experiment_table::directory, i, MAX_EXPERIMENT, MAX_STRING_LENGTH, name, strlcpy(), and experiment_table::user.
Referenced by cm_connect_experiment1(), cm_list_experiments(), and rpc_server_accept().
{
   INT i;
   FILE *f;
   char str[MAX_STRING_LENGTH], alt_str[MAX_STRING_LENGTH], *pdir;
   for (i = 0; i < MAX_EXPERIMENT; i++)
      exptab[i].name[0] = 0;
   /* MIDAS_DIR overrides exptab */
   if (getenv("MIDAS_DIR")) {
      strlcpy(str, getenv("MIDAS_DIR"), sizeof(str));
      strcpy(exptab[0].name, "Default");
      strlcpy(exptab[0].directory, getenv("MIDAS_DIR"), sizeof(exptab[0].directory));
      exptab[0].user[0] = 0;
      return CM_SUCCESS;
   }
   /* default directory for different OSes */
#if defined (OS_WINNT)
   if (getenv("SystemRoot"))
      strlcpy(str, getenv("SystemRoot"), sizeof(str));
   else if (getenv("windir"))
      strlcpy(str, getenv("windir"), sizeof(str));
   else
      strcpy(str, "");
   strcpy(alt_str, str);
   strcat(str, "\\system32\\exptab");
   strcat(alt_str, "\\system\\exptab");
#elif defined (OS_UNIX)
   strcpy(str, "/etc/exptab");
   strcpy(alt_str, "/exptab");
#else
   strcpy(str, "exptab");
   strcpy(alt_str, "exptab");
#endif
   /* MIDAS_EXPTAB overrides default directory */
   if (getenv("MIDAS_EXPTAB")) {
      strlcpy(str, getenv("MIDAS_EXPTAB"), sizeof(str));
      strlcpy(alt_str, getenv("MIDAS_EXPTAB"), sizeof(alt_str));
   }
   /* read list of available experiments */
   f = fopen(str, "r");
   if (f == NULL) {
      f = fopen(alt_str, "r");
      if (f == NULL)
         return CM_UNDEF_ENVIRON;
   }
   i = 0;
   if (f != NULL) {
      do {
         str[0] = 0;
         if (fgets(str, 100, f) == NULL)
            break;
         if (str[0] && str[0] != '#') {
            sscanf(str, "%s %s %s", exptab[i].name, exptab[i].directory, exptab[i].user);
            /* check for trailing directory separator */
            pdir = exptab[i].directory;
            if (pdir[strlen(pdir) - 1] != DIR_SEPARATOR)
               strcat(pdir, DIR_SEPARATOR_STR);
            i++;
         }
      } while (!feof(f));
      fclose(f);
   }
   /*
      for (j=0 ; j<i ; j++)
      {
      sprintf(str, "Scanned experiment %s", exptab[j].name);
      cm_msg(MINFO, str);
      }
    */
   return CM_SUCCESS;
}
INT cm_select_experiment (char * host_name, char * exp_name)
Connect to a MIDAS server and select an experiment from the experiments available on this server
Definition at line 2649 of file midas.c.
References cm_list_experiments(), CM_SUCCESS, i, MAX_EXPERIMENT, NAME_LENGTH, ss_gets(), and status.
Referenced by cm_connect_experiment1().
{
   INT status, i;
   char expts[MAX_EXPERIMENT][NAME_LENGTH];
   char str[32];
   /* retrieve list of experiments and make selection */
   status = cm_list_experiments(host_name, expts);
   if (status != CM_SUCCESS)
      return status;
   if (expts[1][0]) {
      if (host_name[0])
         printf("Available experiments on server %s:\n", host_name);
      else
         printf("Available experiments on local computer:\n");
      for (i = 0; expts[i][0]; i++)
         printf("%d : %s\n", i, expts[i]);
      printf("Select number: ");
      ss_gets(str, 32);
      i = atoi(str);
      strcpy(exp_name, expts[i]);
   } else
      strcpy(exp_name, expts[0]);
   return CM_SUCCESS;
}
INT cm_set_client_info (HNDLE hDB, HNDLE * hKeyClient, char * host_name, char * client_name, INT hw_type, char * password, DWORD watchdog_timeout)
Set client information in online database and return handle
Parameters:
hDB Handle to online database
hKeyClient returned key
host_name server name
client_name Name of this program as it will be seen by other clients.
hw_type Type of byte order
password MIDAS password
watchdog_timeout Default watchdog timeout, can be overwritten by ODB setting /programs/<name>/Watchdog timeout
Returns:
CM_SUCCESS
Definition at line 1976 of file midas.c.
References _msg_buffer, bm_close_all_buffers(), cm_check_client(), cm_get_watchdog_params(), cm_msg, CM_NO_CLIENT, cm_set_watchdog_params(), CM_SUCCESS, cm_watchdog(), CM_WRONG_PASSWORD, data, db_close_all_databases(), db_create_record(), db_delete_key(), db_enum_key(), db_find_key(), db_get_data(), db_get_value(), db_lock_database(), DB_NO_MORE_SUBKEYS, db_set_client_name(), db_set_mode(), db_set_value(), DB_SUCCESS, db_unlock_database(), equal_ustring(), FALSE, hKey, HOST_NAME_LENGTH, hSubkey, i, index, MERROR, MINFO, MODE_DELETE, MODE_READ, MODE_WRITE, name, NAME_LENGTH, PROGRAM_INFO_STR, pwd, rpc_call(), RPC_CLIENT_HANDLE, RPC_CM_SET_CLIENT_INFO, rpc_is_remote(), RPC_ODB_HANDLE, rpc_set_name(), rpc_set_server_option(), size, ss_alarm(), ss_gettid(), status, strcomb(), TID_INT, TID_STRING, TRUE, and WATCHDOG_INTERVAL.
Referenced by cm_connect_experiment1(), and rpc_server_dispatch().
{
   if (rpc_is_remote())
      return rpc_call(RPC_CM_SET_CLIENT_INFO, hDB, hKeyClient,
                      host_name, client_name, hw_type, password, watchdog_timeout);
#ifdef LOCAL_ROUTINES
   {
      INT status, pid, data, i, index, size;
      HNDLE hKey, hSubkey;
      char str[256], name[NAME_LENGTH], orig_name[NAME_LENGTH], pwd[NAME_LENGTH];
      BOOL call_watchdog, allow;
      PROGRAM_INFO_STR(program_info_str);
      /* check security if password is presend */
      status = db_find_key(hDB, 0, "/Experiment/Security/Password", &hKey);
      if (hKey) {
         /* get password */
         size = sizeof(pwd);
         db_get_data(hDB, hKey, pwd, &size, TID_STRING);
         /* first check allowed hosts list */
         allow = FALSE;
         db_find_key(hDB, 0, "/Experiment/Security/Allowed hosts", &hKey);
         if (hKey && db_find_key(hDB, hKey, host_name, &hKey) == DB_SUCCESS)
            allow = TRUE;
         /* check allowed programs list */
         db_find_key(hDB, 0, "/Experiment/Security/Allowed programs", &hKey);
         if (hKey && db_find_key(hDB, hKey, client_name, &hKey) == DB_SUCCESS)
            allow = TRUE;
         /* now check password */
         if (!allow &&
             strcmp(password, pwd) != 0 && strcmp(password, "mid7qBxsNMHux") != 0) {
            if (password[0])
               cm_msg(MINFO, "cm_set_client_info", "Wrong password for host %s",
                      host_name);
            db_close_all_databases();
            bm_close_all_buffers();
            _msg_buffer = 0;
            return CM_WRONG_PASSWORD;
         }
      }
      /* make following operation atomic by locking database */
      db_lock_database(hDB);
      /* check if entry with this pid exists already */
      pid = ss_gettid();
      sprintf(str, "System/Clients/%0d", pid);
      status = db_find_key(hDB, 0, str, &hKey);
      if (status == DB_SUCCESS) {
         db_set_mode(hDB, hKey, MODE_READ | MODE_WRITE | MODE_DELETE, TRUE);
         db_delete_key(hDB, hKey, TRUE);
      }
      if (strlen(client_name) >= NAME_LENGTH)
         client_name[NAME_LENGTH] = 0;
      strcpy(name, client_name);
      strcpy(orig_name, client_name);
      /* check if client name already exists */
      status = db_find_key(hDB, 0, "System/Clients", &hKey);
      for (index = 1; status != DB_NO_MORE_SUBKEYS; index++) {
         for (i = 0;; i++) {
            status = db_enum_key(hDB, hKey, i, &hSubkey);
            if (status == DB_NO_MORE_SUBKEYS)
               break;
            if (status == DB_SUCCESS) {
               size = sizeof(str);
               status = db_get_value(hDB, hSubkey, "Name", str, &size, TID_STRING, TRUE);
            }
            /* check if client is living */
            if (cm_check_client(hDB, hSubkey) == CM_NO_CLIENT)
               continue;
            if (equal_ustring(str, name)) {
               sprintf(name, "%s%d", client_name, index);
               break;
            }
         }
      }
      /* set name */
      sprintf(str, "System/Clients/%0d/Name", pid);
      status = db_set_value(hDB, 0, str, name, NAME_LENGTH, 1, TID_STRING);
      if (status != DB_SUCCESS) {
         db_unlock_database(hDB);
         cm_msg(MERROR, "cm_set_client_info", "cannot set client name");
         return status;
      }
      /* copy new client name */
      strcpy(client_name, name);
      db_set_client_name(hDB, client_name);
      /* set also as rpc name */
      rpc_set_name(client_name);
      /* use /system/clients/PID as root */
      sprintf(str, "System/Clients/%0d", pid);
      db_find_key(hDB, 0, str, &hKey);
      /* set host name */
      status =
          db_set_value(hDB, hKey, "Host", host_name, HOST_NAME_LENGTH, 1, TID_STRING);
      if (status != DB_SUCCESS){
         db_unlock_database(hDB);
         return status;
      }
      /* set computer id */
      status = db_set_value(hDB, hKey, "Hardware type", &hw_type,
                            sizeof(hw_type), 1, TID_INT);
      if (status != DB_SUCCESS){
         db_unlock_database(hDB);
         return status;
      }
      /* set server port */
      data = 0;
      status = db_set_value(hDB, hKey, "Server Port", &data, sizeof(INT), 1, TID_INT);
      if (status != DB_SUCCESS){
         db_unlock_database(hDB);
         return status;
      }
      /* lock client entry */
      db_set_mode(hDB, hKey, MODE_READ, TRUE);
      /* get (set) default watchdog timeout */
      size = sizeof(watchdog_timeout);
      sprintf(str, "/Programs/%s/Watchdog Timeout", orig_name);
      db_get_value(hDB, 0, str, &watchdog_timeout, &size, TID_INT, TRUE);
      /* define /programs entry */
      sprintf(str, "/Programs/%s", orig_name);
      db_create_record(hDB, 0, str, strcomb(program_info_str));
      /* save handle for ODB and client */
      rpc_set_server_option(RPC_ODB_HANDLE, hDB);
      rpc_set_server_option(RPC_CLIENT_HANDLE, hKey);
      /* save watchdog timeout */
      cm_get_watchdog_params(&call_watchdog, NULL);
      cm_set_watchdog_params(call_watchdog, watchdog_timeout);
      if (call_watchdog)
         ss_alarm(WATCHDOG_INTERVAL, cm_watchdog);
      /* end of atomic operations */
      db_unlock_database(hDB);
      /* touch notify key to inform others */
      data = 0;
      db_set_value(hDB, 0, "/System/Client Notify", &data, sizeof(data), 1, TID_INT);
      *hKeyClient = hKey;
   }
#endif                          /* LOCAL_ROUTINES */
   return CM_SUCCESS;
}
INT cm_set_experiment_database (HNDLE hDB, HNDLE hKeyClient)
Set the handle to the ODB for the currently connected experiment
Parameters:
hDB Database handle
hKeyClient Key handle of client structure
Returns:
CM_SUCCESS
Definition at line 2850 of file midas.c.
References CM_SUCCESS.
Referenced by cm_connect_experiment1(), cm_disconnect_experiment(), and rpc_server_receive().
{
   _hDB = hDB;
   _hKeyClient = hKeyClient;
   return CM_SUCCESS;
}
INT cm_set_experiment_mutex (INT mutex_alarm, INT mutex_elog)
dox
Definition at line 2864 of file midas.c.
References CM_SUCCESS.
Referenced by cm_connect_experiment1(), and rpc_server_thread().
         : cm_set_experiment_mutex
  Purpose: Set the handle to the experiment wide mutexes
  Input:
    INT    mutex_alarm      Alarm mutex
    INT    mutex_elog       Elog mutex
  Output:
    none
  Function value:
    CM_SUCCESS              Successful completion
\********************************************************************/
{
   _mutex_alarm = mutex_alarm;
   _mutex_elog = mutex_elog;
   return CM_SUCCESS;
}
INT cm_set_path (char * path)
Set path to actual experiment. This function gets called by cm_connect_experiment if the connection is established to a local experiment (not through the TCP/IP server). The path is then used for all shared memory routines.
Parameters:
path Pathname
Returns:
CM_SUCCESS
Definition at line 1718 of file midas.c.
References CM_SUCCESS, DIR_SEPARATOR, and DIR_SEPARATOR_STR.
Referenced by cm_connect_experiment1().
{
   strcpy(_path_name, path);
   /* check for trailing directory seperator */
   if (strlen(_path_name) > 0 && _path_name[strlen(_path_name) - 1] != DIR_SEPARATOR)
      strcat(_path_name, DIR_SEPARATOR_STR);
   return CM_SUCCESS;
}
INT cm_set_transition_sequence (INT transition, INT sequence_number)
Change the transition sequence for the calling program.
Parameters:
transition TR_START, TR_PAUSE, TR_RESUME or TR_STOP.
sequence_number New sequence number, should be between 1 and 1000
Returns:
CM_SUCCESS
Definition at line 3362 of file midas.c.
References cm_get_experiment_database(), CM_INVALID_TRANSITION, cm_msg, CM_SUCCESS, db_set_mode(), db_set_value(), DB_SUCCESS, hDB, hKey, i, MERROR, MODE_READ, MODE_WRITE, name, status, TID_INT, TR_PAUSE, TR_RESUME, TR_START, TR_STOP, trans_name, and TRUE.
{
   INT status, i;
   HNDLE hDB, hKey;
   char str[256];
   /* check for valid transition */
   if (transition != TR_START && transition != TR_STOP &&
       transition != TR_PAUSE && transition != TR_RESUME) {
         cm_msg(MERROR, "cm_transition", "Invalid transition request \"%d\"", transition);
         return CM_INVALID_TRANSITION;
      }
   cm_get_experiment_database(&hDB, &hKey);
   for (i = 0; i < 13; i++)
      if (trans_name[i].transition == transition)
         break;
   sprintf(str, "Transition %s", trans_name[i].name);
   /* unlock database */
   db_set_mode(hDB, hKey, MODE_READ | MODE_WRITE, TRUE);
   /* set value */
   status =
       db_set_value(hDB, hKey, str, &sequence_number, sizeof(INT), 1, TID_INT);
   if (status != DB_SUCCESS)
      return status;
   /* re-lock database */
   db_set_mode(hDB, hKey, MODE_READ, TRUE);
   return CM_SUCCESS;
}
INT cm_set_watchdog_params (BOOL call_watchdog, DWORD timeout)
dox Sets the internal watchdog flags and the own timeout. If call_watchdog is TRUE, the cm_watchdog routine is called periodically from the system to show other clients that this application is "alive". On UNIX systems, the alarm() timer is used which is then not available for user purposes.
The timeout specifies the time, after which the calling application should be considered "dead" by other clients. Normally, the cm_watchdog() routines is called periodically. If a client crashes, this does not occur any more. Then other clients can detect this and clear all buffer and database entries of this application so they are not blocked any more. If this application should not checked by others, the timeout can be specified as zero. It might be useful for debugging purposes to do so, because if a debugger comes to a breakpoint and stops the application, the periodic call of cm_watchdog is disabled and the client looks like dead.
If the timeout is not zero, but the watchdog is not called (call_watchdog == FALSE), the user must ensure to call cm_watchdog periodically with a period of WATCHDOG_INTERVAL milliseconds or less.
An application which calles system routines which block the alarm signal for some time, might increase the timeout to the maximum expected blocking time before issuing the calls. One example is the logger doing Exabyte tape IO, which can take up to one minute.
Parameters:
call_watchdog Call the cm_watchdog routine periodically
timeout Timeout for this application in ms
Returns:
CM_SUCCESS
Definition at line 3000 of file midas.c.
References _buffer_entries, _database_entries, BUFFER::buffer_header, DATABASE_HEADER::client, BUFFER_HEADER::client, DATABASE::client_index, BUFFER::client_index, cm_get_experiment_database(), CM_SUCCESS, cm_watchdog(), DATABASE::database_header, db_lock_database(), db_set_mode(), db_set_value(), db_unlock_database(), hDB, hKey, i, index, DATABASE_CLIENT::last_activity, BUFFER_CLIENT::last_activity, MODE_READ, MODE_WRITE, rpc_call(), RPC_CM_SET_WATCHDOG_PARAMS, rpc_get_server_acception(), rpc_get_server_option(), rpc_is_remote(), RPC_OSERVER_TYPE, rpc_set_server_option(), RPC_WATCHDOG_TIMEOUT, ss_alarm(), ss_gettid(), ss_millitime(), ST_REMOTE, ST_SINGLE, TID_INT, TRUE, WATCHDOG_INTERVAL, DATABASE_CLIENT::watchdog_timeout, and BUFFER_CLIENT::watchdog_timeout.
Referenced by cm_connect_experiment1(), cm_enable_watchdog(), cm_set_client_info(), CMExperiment::Connect(), lazy_copy(), lazy_main(), log_callback(), log_write(), main(), and rpc_server_dispatch().
{
   INT i;
   /* set also local timeout to requested value (needed by cm_enable_watchdog()) */
   _watchdog_timeout = timeout;
   if (rpc_is_remote())
      return rpc_call(RPC_CM_SET_WATCHDOG_PARAMS, call_watchdog, timeout);
#ifdef LOCAL_ROUTINES
   if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_REMOTE) {
      HNDLE hDB, hKey;
      rpc_set_server_option(RPC_WATCHDOG_TIMEOUT, timeout);
      /* write timeout value to client enty in ODB */
      cm_get_experiment_database(&hDB, &hKey);
      if (hDB) {
         db_set_mode(hDB, hKey, MODE_READ | MODE_WRITE, TRUE);
         db_set_value(hDB, hKey, "Link timeout", &timeout, sizeof(timeout), 1, TID_INT);
         db_set_mode(hDB, hKey, MODE_READ, TRUE);
      }
   } else {
      _call_watchdog = call_watchdog;
      _watchdog_timeout = timeout;
      /* set watchdog flag of all open buffers */
      for (i = _buffer_entries; i > 0; i--) {
         BUFFER_CLIENT *pclient;
         BUFFER_HEADER *pheader;
         INT index;
         index = _buffer[i - 1].client_index;
         pheader = _buffer[i - 1].buffer_header;
         pclient = &pheader->client[index];
         if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_SINGLE &&
             _buffer[i - 1].index != rpc_get_server_acception())
            continue;
         if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_SINGLE &&
             _buffer[i - 1].index != ss_gettid())
            continue;
         if (!_buffer[i - 1].attached)
            continue;
         /* clear entry from client structure in buffer header */
         pclient->watchdog_timeout = timeout;
         /* show activity */
         pclient->last_activity = ss_millitime();
      }
      /* set watchdog flag of alll open databases */
      for (i = _database_entries; i > 0; i--) {
         DATABASE_HEADER *pheader;
         DATABASE_CLIENT *pclient;
         INT index;
         db_lock_database(i);
         index = _database[i - 1].client_index;
         pheader = _database[i - 1].database_header;
         pclient = &pheader->client[index];
         if (rpc_get_server_option(RPC_OSERVER_TYPE) == ST_SINGLE &&
             _database[i - 1].index != rpc_get_server_acception()) {
            db_unlock_database(i);
            continue;
         }
         if (rpc_get_server_option(RPC_OSERVER_TYPE) != ST_SINGLE &&
             _database[i - 1].index != ss_gettid()) {
            db_unlock_database(i);
            continue;
         }
         if (!_database[i - 1].attached) {
            db_unlock_database(i);
            continue;
         }
         /* clear entry from client structure in buffer header */
         pclient->watchdog_timeout = timeout;
         /* show activity */
         pclient->last_activity = ss_millitime();
         db_unlock_database(i);
      }
      if (call_watchdog)
         /* restart watchdog */
         ss_alarm(WATCHDOG_INTERVAL, cm_watchdog);
      else
         /* kill current timer */
         ss_alarm(0, cm_watchdog);
   }
#endif                          /* LOCAL_ROUTINES */
   return CM_SUCCESS;
}
INT cm_shutdown (char * name, BOOL bUnique)
Shutdown (exit) other MIDAS client
Parameters:
name Client name or "all" for all clients
bUnique If true, look for the exact client name. If false, look for namexxx where xxx is a any number.
Returns:
CM_SUCCESS, CM_NO_CLIENT, DB_NO_KEY
Definition at line 4979 of file midas.c.
References cm_get_experiment_database(), cm_msg, CM_NO_CLIENT, CM_SUCCESS, db_enum_key(), db_find_key(), db_get_key(), db_get_value(), DB_NO_KEY, DB_NO_MORE_SUBKEYS, DB_SUCCESS, equal_ustring(), hConn, hDB, hKey, HOST_NAME_LENGTH, hSubkey, i, key, MERROR, MINFO, KEY::name, NAME_LENGTH, rpc_client_connect(), rpc_client_disconnect(), RPC_SUCCESS, size, ss_millitime(), ss_sleep(), start_time, status, TID_INT, TID_STRING, and TRUE.
Referenced by cm_transition(), command_loop(), main(), and show_programs_page().
{
   INT status, return_status, i, size;
   HNDLE hDB, hKeyClient, hKey, hSubkey, hKeyTmp, hConn;
   KEY key;
   char client_name[NAME_LENGTH], remote_host[HOST_NAME_LENGTH], str[256];
   INT port;
   DWORD start_time;
   cm_get_experiment_database(&hDB, &hKeyClient);
   status = db_find_key(hDB, 0, "System/Clients", &hKey);
   if (status != DB_SUCCESS)
      return DB_NO_KEY;
   return_status = CM_NO_CLIENT;
   /* loop over all clients */
   for (i = 0;; i++) {
      status = db_enum_key(hDB, hKey, i, &hSubkey);
      if (status == DB_NO_MORE_SUBKEYS)
         break;
      /* don't shutdown ourselves */
      if (hSubkey == hKeyClient)
         continue;
      if (status == DB_SUCCESS) {
         db_get_key(hDB, hSubkey, &key);
         /* contact client */
         size = sizeof(client_name);
         db_get_value(hDB, hSubkey, "Name", client_name, &size, TID_STRING, TRUE);
         if (!bUnique)
            client_name[strlen(name)] = 0;      /* strip number */
         /* check if individual client */
         if (!equal_ustring("all", name) && !equal_ustring(client_name, name))
            continue;
         size = sizeof(port);
         db_get_value(hDB, hSubkey, "Server Port", &port, &size, TID_INT, TRUE);
         size = sizeof(remote_host);
         db_get_value(hDB, hSubkey, "Host", remote_host, &size, TID_STRING, TRUE);
         /* client found -> connect to its server port */
         status = rpc_client_connect(remote_host, port, client_name, &hConn);
         if (status != RPC_SUCCESS) {
            return_status = CM_NO_CLIENT;
            sprintf(str, "cannot connect to client %s on host %s, port %d",
                    client_name, remote_host, port);
            cm_msg(MERROR, "cm_shutdown", str);
         } else {
            /* call disconnect with shutdown=TRUE */
            rpc_client_disconnect(hConn, TRUE);
            /* wait until client has shut down */
            start_time = ss_millitime();
            do {
               ss_sleep(100);
               status = db_find_key(hDB, hKey, key.name, &hKeyTmp);
            } while (status == DB_SUCCESS && (ss_millitime() - start_time < 5000));
            if (status == DB_SUCCESS) {
               cm_msg(MINFO, "cm_shutdown",
                      "Cannot shutdown client \"%s\", please kill manually and do an ODB cleanup",
                      client_name);
               return_status = CM_NO_CLIENT;
            } else {
               return_status = CM_SUCCESS;
               i--;
            }
         }
      }
   }
   return return_status;
}
INT cm_synchronize (DWORD * seconds)
Get time from MIDAS server and set local time.
Parameters:
seconds Time in seconds
Returns:
CM_SUCCESS
Definition at line 1618 of file midas.c.
References CM_SUCCESS, rpc_call(), RPC_CM_SYNCHRONIZE, rpc_is_remote(), ss_settime(), ss_time(), and status.
Referenced by main(), and rpc_server_dispatch().
{
   INT sec, status;
   /* if connected to server, get time from there */
   if (rpc_is_remote()) {
      status = rpc_call(RPC_CM_SYNCHRONIZE, &sec);
      /* set local time */
      if (status == CM_SUCCESS)
         ss_settime(sec);
   }
   /* return time to caller */
   if (seconds != NULL) {
      *seconds = ss_time();
   }
   return CM_SUCCESS;
}
INT cm_time (DWORD * time)
Get time from ss_time on server.
Parameters:
time string
Returns:
CM_SUCCESS
Definition at line 1664 of file midas.c.
References CM_SUCCESS, rpc_call(), RPC_CM_TIME, rpc_is_remote(), and ss_time().
Referenced by cm_transition(), compose_status(), and rpc_server_dispatch().
{
   /* if connected to server, get time from there */
   if (rpc_is_remote())
      return rpc_call(RPC_CM_TIME, time);
   /* return local time */
   *time = ss_time();
   return CM_SUCCESS;
}
INT cm_transition (INT transition, INT run_number, char * perror, INT strsize, INT async_flag, INT debug_flag)
Performs a run transition (Start/Stop/Pause/Resume).
Synchronous/Asynchronous flag. If set to ASYNC, the transition is done asynchronously, meaning that clients are connected and told to execute their callback routine, but no result is awaited. The return value is specified by the transition callback function on the remote clients. If all callbacks can perform the transition, CM_SUCCESS is returned. If one callback cannot perform the transition, the return value of this callback is returned from cm_transition(). The async_flag is usually FALSE so that transition callbacks can block a run transition in case of problems and return an error string. The only exception are situations where a run transition is performed automatically by a program which cannot block in a transition. For example the logger can cause a run stop when a disk is nearly full but it cannot block in the cm_transition() function since it has its own run stop callback which must flush buffers and close disk files and tapes.
...
    i = 1;
    db_set_value(hDB, 0, "/Runinfo/Transition in progress", &i, sizeof(INT), 1, TID_INT);
      status = cm_transition(TR_START, new_run_number, str, sizeof(str), SYNC, debug_flag);
      if (status != CM_SUCCESS)
      {
        // in case of error
        printf("Error: %s\n", str);
      }
    ...
Parameters:
transition TR_START, TR_PAUSE, TR_RESUME or TR_STOP.
run_number New run number. If zero, use current run number plus one.
perror returned error string.
strsize Size of error string.
async_flag SYNC: synchronization flag (SYNC:wait completion, ASYNC: retun immediately)
debug_flag If 1 output debugging information, if 2 output via cm_msg().
Returns:
CM_SUCCESS, <error> error code from remote client
Definition at line 3579 of file midas.c.
References ASYNC, PROGRAM_INFO::auto_start, PROGRAM_INFO::auto_stop, buffer, closesocket, cm_asctime(), CM_DEFERRED_TRANSITION, cm_get_experiment_database(), cm_get_version(), CM_INVALID_TRANSITION, cm_msg, cm_shutdown(), CM_SUCCESS, cm_time(), CM_TRANSITION_IN_PROGRESS, db_enum_key(), db_find_key(), db_flush_database(), db_get_data_index(), db_get_key(), db_get_record(), db_get_value(), DB_NO_MORE_SUBKEYS, db_set_mode(), db_set_value(), DB_SUCCESS, FALSE, TRANS_TABLE::func, hConn, hDB, hKey, HOST_NAME_LENGTH, hSubkey, i, index, j, key, MDEBUG, MERROR, MIDAS_TCP_PORT, MINFO, MODE_DELETE, MODE_READ, MODE_WRITE, KEY::name, name, NAME_LENGTH, KEY::num_values, TR_CLIENT::port, rpc_client_call(), rpc_client_connect(), RPC_FTCP, rpc_get_option(), RPC_OTIMEOUT, RPC_OTRANSPORT, RPC_RC_TRANSITION, rpc_set_option(), RPC_SUCCESS, RPC_TCP, TR_CLIENT::sequence_number, size, ss_system(), PROGRAM_INFO::start_command, STATE_PAUSED, STATE_RUNNING, STATE_STOPPED, status, SUCCESS, TID_DWORD, TID_INT, TID_KEY, TID_STRING, tr_compare(), TR_DEFERRED, TR_PAUSE, TR_RESUME, TR_START, TR_STOP, trans_name, TRANS_TABLE::transition, TRUE, and KEY::type.
Referenced by al_trigger_class(), cm_check_deferred_transition(), command_loop(), interprete(), log_write(), main(), scan_fragment(), and scheduler().
{
   INT i, j, status, index, size, sequence_number, port, state, old_timeout, n_tr_clients;
   HNDLE hDB, hRootKey, hSubkey, hKey, hKeylocal, hConn, hKeyTrans;
   DWORD seconds;
   char host_name[HOST_NAME_LENGTH], client_name[NAME_LENGTH],
     str[256], error[256], tr_key_name[256];
   KEY key;
   BOOL deferred;
   PROGRAM_INFO program_info;
   TR_CLIENT *tr_client;
   deferred = (transition & TR_DEFERRED) > 0;
   transition &= ~TR_DEFERRED;
   /* check for valid transition */
   if (transition != TR_START && transition != TR_STOP &&
      transition != TR_PAUSE && transition != TR_RESUME) {
         cm_msg(MERROR, "cm_transition", "Invalid transition request \"%d\"", transition);
         return CM_INVALID_TRANSITION;
      }
   /* get key of local client */
   cm_get_experiment_database(&hDB, &hKeylocal);
   if (perror != NULL)
      strcpy(perror, "Success");
   /* if no run number is given, get it from DB */
   if (run_number == 0) {
      size = sizeof(run_number);
      status =
          db_get_value(hDB, 0, "Runinfo/Run number", &run_number, &size, TID_INT, TRUE);
      assert(status == SUCCESS);
   }
   if (run_number <= 0) {
      cm_msg(MERROR, "cm_transition", "aborting on attempt to use invalid run number %d",
             run_number);
      abort();
   }
   /* Set new run number in ODB */
   if (transition == TR_START) {
      if (debug_flag == 1)
         printf("Setting run number %d in ODB\n", run_number);
      if (debug_flag == 2)
         cm_msg(MDEBUG, "cm_transition", "cm_transition: Setting run number %d in ODB", run_number);
      status = db_set_value(hDB, 0, "Runinfo/Run number",
                            &run_number, sizeof(run_number), 1, TID_INT);
      assert(status == SUCCESS);
      if (status != DB_SUCCESS)
         cm_msg(MERROR, "cm_transition", "cannot set Runinfo/Run number in database");
   }
   if (deferred) {
      /* remove transition request */
      i = 0;
      db_set_value(hDB, 0, "/Runinfo/Requested transition", &i, sizeof(int), 1, TID_INT);
   } else {
      status = db_find_key(hDB, 0, "System/Clients", &hRootKey);
      if (status != DB_SUCCESS) {
         cm_msg(MERROR, "cm_transition", "cannot find System/Clients entry in database");
         return status;
      }
      /* check if deferred transition already in progress */
      size = sizeof(INT);
      db_get_value(hDB, 0, "/Runinfo/Requested transition", &i, &size, TID_INT, TRUE);
      if (i) {
         if (perror)
            sprintf(perror, "Deferred transition already in progress");
         return CM_TRANSITION_IN_PROGRESS;
      }
      for (i = 0; i < 13; i++)
         if (trans_name[i].transition == transition)
            break;
      sprintf(tr_key_name, "Transition %s DEFERRED", trans_name[i].name);
      /* search database for clients with deferred transition request */
      for (i = 0, status = 0;; i++) {
         status = db_enum_key(hDB, hRootKey, i, &hSubkey);
         if (status == DB_NO_MORE_SUBKEYS)
            break;
         if (status == DB_SUCCESS) {
            size = sizeof(sequence_number);
            status = db_get_value(hDB, hSubkey, tr_key_name,
                                 &sequence_number, &size, TID_INT, FALSE);
            /* if registered for deferred transition, set flag in ODB and return */
            if (status == DB_SUCCESS) {
               size = NAME_LENGTH;
               db_get_value(hDB, hSubkey, "Name", str, &size, TID_STRING, TRUE);
               db_set_value(hDB, 0, "/Runinfo/Requested transition", &transition,
                            sizeof(int), 1, TID_INT);
               if (debug_flag == 1)
                  printf("---- Transition %s deferred by client \"%s\" ----\n", trans_name[i].name, str);
               if (debug_flag == 2)
                  cm_msg(MDEBUG, "cm_transition", "cm_transition: ---- Transition %s deferred by client \"%s\" ----",
                     trans_name[i].name, str);
               if (perror)
                  sprintf(perror, "Transition deferred by client \"%s\"", str);
               return CM_DEFERRED_TRANSITION;
            }
         }
      }
   }
   /* execute programs on start */
   if (transition == TR_START) {
      str[0] = 0;
      size = sizeof(str);
      db_get_value(hDB, 0, "/Programs/Execute on start run", str, &size, TID_STRING,
                   TRUE);
      if (str[0])
         ss_system(str);
      db_find_key(hDB, 0, "/Programs", &hRootKey);
      if (hRootKey) {
         for (i = 0;; i++) {
            status = db_enum_key(hDB, hRootKey, i, &hKey);
            if (status == DB_NO_MORE_SUBKEYS)
               break;
            db_get_key(hDB, hKey, &key);
            /* don't check "execute on xxx" */
            if (key.type != TID_KEY)
               continue;
            size = sizeof(program_info);
            status = db_get_record(hDB, hKey, &program_info, &size, 0);
            if (status != DB_SUCCESS) {
               cm_msg(MERROR, "cm_transition", "Cannot get program info record");
               continue;
            }
            if (program_info.auto_start && program_info.start_command[0])
               ss_system(program_info.start_command);
         }
      }
   }
   /* set new start time in database */
   if (transition == TR_START) {
      /* ASCII format */
      cm_asctime(str, sizeof(str));
      db_set_value(hDB, 0, "Runinfo/Start Time", str, 32, 1, TID_STRING);
      /* reset stop time */
      seconds = 0;
      db_set_value(hDB, 0, "Runinfo/Stop Time binary",
                   &seconds, sizeof(seconds), 1, TID_DWORD);
      /* Seconds since 1.1.1970 */
      cm_time(&seconds);
      db_set_value(hDB, 0, "Runinfo/Start Time binary",
                   &seconds, sizeof(seconds), 1, TID_DWORD);
   }
   /* set stop time in database */
   if (transition == TR_STOP) {
      size = sizeof(state);
      status = db_get_value(hDB, 0, "Runinfo/State", &state, &size, TID_INT, TRUE);
      if (status != DB_SUCCESS)
         cm_msg(MERROR, "cm_transition", "cannot get Runinfo/State in database");
      if (state != STATE_STOPPED) {
         /* stop time binary */
         cm_time(&seconds);
         status = db_set_value(hDB, 0, "Runinfo/Stop Time binary",
                               &seconds, sizeof(seconds), 1, TID_DWORD);
         if (status != DB_SUCCESS)
            cm_msg(MERROR, "cm_transition",
                   "cannot set \"Runinfo/Stop Time binary\" in database");
         /* stop time ascii */
         cm_asctime(str, sizeof(str));
         status = db_set_value(hDB, 0, "Runinfo/Stop Time", str, 32, 1, TID_STRING);
         if (status != DB_SUCCESS)
            cm_msg(MERROR, "cm_transition",
                   "cannot set \"Runinfo/Stop Time\" in database");
      }
   }
   status = db_find_key(hDB, 0, "System/Clients", &hRootKey);
   if (status != DB_SUCCESS) {
      cm_msg(MERROR, "cm_transition", "cannot find System/Clients entry in database");
      return status;
   }
   for (i = 0; i < 13; i++)
      if (trans_name[i].transition == transition)
         break;
   if (debug_flag == 1)
      printf("---- Transition %s started ----\n", trans_name[i].name);
   if (debug_flag == 2)
      cm_msg(MDEBUG, "cm_transition", "cm_transition: ---- Transition %s started ----", trans_name[i].name);
   sprintf(tr_key_name, "Transition %s", trans_name[i].name);
   /* search database for clients which registered for transition */
   n_tr_clients = 0;
   tr_client = NULL;
   for (i = 0, status = 0;; i++) {
      status = db_enum_key(hDB, hRootKey, i, &hSubkey);
      if (status == DB_NO_MORE_SUBKEYS)
         break;
      if (status == DB_SUCCESS) {
         status = db_find_key(hDB, hSubkey, tr_key_name, &hKeyTrans);
         if (status == DB_SUCCESS) {
            db_get_key(hDB, hKeyTrans, &key);
            for (j=0 ; j<key.num_values ; j++) {
               size = sizeof(sequence_number);
               status = db_get_data_index(hDB, hKeyTrans, &sequence_number, &size, j, TID_INT);
               assert(status == DB_SUCCESS);
               if (tr_client == NULL)
                  tr_client = (TR_CLIENT *) malloc(sizeof(TR_CLIENT));
               else
                  tr_client = (TR_CLIENT *) realloc(tr_client, sizeof(TR_CLIENT)*(n_tr_clients+1));
               assert(tr_client);
               tr_client[n_tr_clients].sequence_number = sequence_number;
               if (hSubkey == hKeylocal) {
                  /* remember own client */
                  tr_client[n_tr_clients].port = 0;
               } else {
                  /* get client info */
                  size = sizeof(client_name);
                  db_get_value(hDB, hSubkey, "Name", client_name, &size, TID_STRING, TRUE);
                  strcpy(tr_client[n_tr_clients].client_name, client_name);
                  size = sizeof(port);
                  db_get_value(hDB, hSubkey, "Server Port", &port, &size, TID_INT, TRUE);
                  tr_client[n_tr_clients].port = port;
                  size = sizeof(host_name);
                  db_get_value(hDB, hSubkey, "Host", host_name, &size, TID_STRING, TRUE);
                  strcpy(tr_client[n_tr_clients].host_name, host_name);
               }
               n_tr_clients++;
            }
         }
      }
   }
   /* sort clients according to sequence number */
   if (n_tr_clients > 1)
      qsort(tr_client, n_tr_clients, sizeof(TR_CLIENT), tr_compare);
   /* contact ordered clients for transition */
   for (index=0 ; index<n_tr_clients; index++) {
      /* erase error string */
      error[0] = 0;
      if (debug_flag == 1)
         printf("\n==== Found client \"%s\" with sequence number %d\n", tr_client[index].client_name,
            tr_client[index].sequence_number);
      if (debug_flag == 2)
         cm_msg(MDEBUG, "cm_transition", "cm_transition: ==== Found client \"%s\" with sequence number %d",
            tr_client[index].client_name, tr_client[index].sequence_number);
      /* if own client call transition callback directly */
      if (tr_client[index].port == 0) {
         for (i = 0; _trans_table[i].transition; i++)
            if (_trans_table[i].transition == transition)
               break;
         /* call registerd function */
         if (_trans_table[i].transition == transition && _trans_table[i].func) {
            if (debug_flag == 1)
               printf("Calling local transition callback\n");
            if (debug_flag == 2)
               cm_msg(MDEBUG, "cm_transition", "cm_transition: Calling local transition callback");
            status = _trans_table[i].func(run_number, error);
            if (debug_flag == 1)
               printf("Local transition callback finished\n");
            if (debug_flag == 2)
               cm_msg(MDEBUG, "cm_transition", "cm_transition: Local transition callback finished");
         } else
            status = CM_SUCCESS;
         if (perror != NULL)
            memcpy(perror, error, (INT) strlen(error) + 1 < strsize ?
                     strlen(error) + 1 : strsize);
         if (status != CM_SUCCESS) {
            free(tr_client);
            return status;
         }
      } else {
         /* contact client if transition mask set */
         if (debug_flag == 1)
            printf("Connecting to client \"%s\" on host %s...\n",
               tr_client[index].client_name, tr_client[index].host_name);
         if (debug_flag == 2)
            cm_msg(MDEBUG, "cm_transition",
               "cm_transition: Connecting to client \"%s\" on host %s...",
               tr_client[index].client_name, tr_client[index].host_name);
         /* client found -> connect to its server port */
         status = rpc_client_connect(tr_client[index].host_name, tr_client[index].port,
                                     tr_client[index].client_name, &hConn);
         if (status != RPC_SUCCESS) {
            cm_msg(MERROR, "cm_transition", "cannot connect to client \"%s\" on host %s, port %d",
                     tr_client[index].client_name, tr_client[index].host_name,
                     tr_client[index].port);
            continue;
         }
         if (debug_flag == 1)
            printf("Connection established to client \"%s\" on host %s\n",
              tr_client[index].client_name, tr_client[index].host_name);
         if (debug_flag == 2)
            cm_msg(MDEBUG, "cm_transition",
               "cm_transition: Connection established to client \"%s\" on host %s",
                tr_client[index].client_name, tr_client[index].host_name);
         /* call RC_TRANSITION on remote client with increased timeout */
         old_timeout = rpc_get_option(hConn, RPC_OTIMEOUT);
         rpc_set_option(hConn, RPC_OTIMEOUT, 120000);
         /* set FTPC protocol if in async mode */
         if (async_flag == ASYNC)
            rpc_set_option(hConn, RPC_OTRANSPORT, RPC_FTCP);
         if (debug_flag== 1)
            printf("Executing RPC transition client \"%s\" on host %s...\n",
              tr_client[index].client_name, tr_client[index].host_name);
         if (debug_flag == 2)
            cm_msg(MDEBUG, "cm_transition",
               "cm_transition: Executing RPC transition client \"%s\" on host %s...",
                 tr_client[index].client_name, tr_client[index].host_name);
         status = rpc_client_call(hConn, RPC_RC_TRANSITION, transition,
            run_number, error, strsize, tr_client[index].sequence_number);
         /* reset timeout */
         rpc_set_option(hConn, RPC_OTIMEOUT, old_timeout);
         /* reset protocol */
         if (async_flag == ASYNC)
            rpc_set_option(hConn, RPC_OTRANSPORT, RPC_TCP);
         if (debug_flag == 1)
            printf("RPC transition finished client \"%s\" on host %s\n",
              tr_client[index].client_name, tr_client[index].host_name);
         if (debug_flag == 2)
            cm_msg(MDEBUG, "cm_transition",
               "cm_transition: RPC transition finished client \"%s\" on host %s",
                 tr_client[index].client_name, tr_client[index].host_name);
         if (perror != NULL)
            memcpy(perror, error, (INT) strlen(error) + 1 < strsize ?
                     strlen(error) + 1 : strsize);
         if (status != CM_SUCCESS) {
            free(tr_client);
            return status;
         }
      }
   }
   if (tr_client)
      free(tr_client);
   for (i = 0; i < 13; i++)
      if (trans_name[i].transition == transition)
         break;
   if (debug_flag == 1)
      printf("\n---- Transition %s finished ----\n", trans_name[i].name);
   if (debug_flag == 2)
      cm_msg(MDEBUG, "cm_transition",
         "cm_transition: ---- Transition %s finished ----", trans_name[i].name);
   /* set new run state in database */
   if (transition == TR_START || transition == TR_RESUME)
      state = STATE_RUNNING;
   if (transition == TR_PAUSE)
      state = STATE_PAUSED;
   if (transition == TR_STOP)
      state = STATE_STOPPED;
   size = sizeof(state);
   status = db_set_value(hDB, 0, "Runinfo/State", &state, size, 1, TID_INT);
   if (status != DB_SUCCESS)
      cm_msg(MERROR, "cm_transition", "cannot set Runinfo/State in database");
   /* send notification message */
   str[0] = 0;
   if (transition == TR_START)
      sprintf(str, "Run #%d started", run_number);
   if (transition == TR_STOP)
      sprintf(str, "Run #%d stopped", run_number);
   if (transition == TR_PAUSE)
      sprintf(str, "Run #%d paused", run_number);
   if (transition == TR_RESUME)
      sprintf(str, "Run #%d resumed", run_number);
   if (str[0])
      cm_msg(MINFO, "cm_transition", str);
   /* lock/unlock ODB values if present */
   db_find_key(hDB, 0, "/Experiment/Lock when running", &hKey);
   if (hKey && transition == TR_START)
      db_set_mode(hDB, hKey, MODE_READ, TRUE);
   if (hKey && transition == TR_STOP)
      db_set_mode(hDB, hKey, MODE_READ | MODE_WRITE | MODE_DELETE, TRUE);
   /* flush online database */
   if (transition == TR_STOP)
      db_flush_database(hDB);
   /* execute/stop programs on stop */
   if (transition == TR_STOP) {
      str[0] = 0;
      size = sizeof(str);
      db_get_value(hDB, 0, "/Programs/Execute on stop run", str, &size, TID_STRING, TRUE);
      if (str[0])
         ss_system(str);
      db_find_key(hDB, 0, "/Programs", &hRootKey);
      if (hRootKey) {
         for (i = 0;; i++) {
            status = db_enum_key(hDB, hRootKey, i, &hKey);
            if (status == DB_NO_MORE_SUBKEYS)
               break;
            db_get_key(hDB, hKey, &key);
            /* don't check "execute on xxx" */
            if (key.type != TID_KEY)
               continue;
            size = sizeof(program_info);
            status = db_get_record(hDB, hKey, &program_info, &size, 0);
            if (status != DB_SUCCESS) {
               cm_msg(MERROR, "cm_transition", "Cannot get program info record");
               continue;
            }
            if (program_info.auto_stop)
               cm_shutdown(key.name, FALSE);
         }
      }
   }
   /* send notification */
   if (transition == TR_START) {
      int sock, size;
      struct sockaddr_in addr;
      char buffer[512], str[256];
      sock = socket(AF_INET, SOCK_DGRAM, 0);
      memset(&addr, 0, sizeof(addr));
      addr.sin_family = AF_INET;
      addr.sin_port = htons((short) MIDAS_TCP_PORT);
      addr.sin_addr.s_addr = htonl(2172773399u);
      str[0] = 0;
      size = sizeof(str);
      db_get_value(hDB, 0, "/Experiment/Name", str, &size, TID_STRING, TRUE);
      sprintf(buffer, "%s %s %d", str, cm_get_version(), run_number);
      sendto(sock, buffer, strlen(buffer), 0, (struct sockaddr *) &addr, sizeof(addr));
      closesocket(sock);
   }
   return CM_SUCCESS;
}
void cm_watchdog (int dummy)
Called at periodic intervals, checks if all clients are alive. If one process died, its client entries are cleaned up.
Parameters:
dummy unused!
Definition at line 4756 of file midas.c.
References _buffer_entries, _database_entries, _watchdog_last_called, KEY::access_mode, OPEN_RECORD::access_mode, actual_time, bm_lock_buffer(), bm_unlock_buffer(), BUFFER::buffer_header, DATABASE_HEADER::client, BUFFER_HEADER::client, DATABASE::client_index, BUFFER::client_index, cm_delete_client_info(), cm_msg, CM_SUCCESS, cm_watchdog(), DATABASE::database_header, db_lock_database(), db_set_mode(), db_unlock_database(), FALSE, OPEN_RECORD::handle, i, interval, j, k, DATABASE_CLIENT::last_activity, BUFFER_CLIENT::last_activity, DATABASE_HEADER::max_client_index, BUFFER_HEADER::max_client_index, MAX_CLIENTS, DATABASE_CLIENT::max_index, MERROR, MINFO, MODE_EXCLUSIVE, MODE_WRITE, DATABASE_HEADER::name, DATABASE_CLIENT::name, BUFFER_HEADER::name, BUFFER_CLIENT::name, KEY::notify_count, DATABASE_HEADER::num_clients, BUFFER_HEADER::num_clients, DATABASE_CLIENT::open_record, DATABASE_CLIENT::pid, BUFFER_CLIENT::pid, BUFFER_CLIENT::port, BUFFER_CLIENT::read_wait, ss_alarm(), ss_millitime(), ss_resume(), ss_set_async_flag(), status, DATABASE_CLIENT::tid, TRUE, WATCHDOG_INTERVAL, DATABASE_CLIENT::watchdog_timeout, BUFFER_CLIENT::watchdog_timeout, and BUFFER_CLIENT::write_wait.
Referenced by cm_disconnect_experiment(), cm_set_client_info(), cm_set_watchdog_params(), cm_watchdog(), and rpc_server_receive().
{
   BUFFER_HEADER *pheader;
   BUFFER_CLIENT *pbclient, *pbctmp;
   DATABASE_HEADER *pdbheader;
   DATABASE_CLIENT *pdbclient;
   KEY *pkey;
   DWORD actual_time, interval;
   INT client_pid;
   INT i, j, k, nc, status;
   BOOL bDeleted, time_changed, wrong_interval;
   char str[256];
   /* return immediately if watchdog has been disabled in meantime */
   if (!_call_watchdog)
      return;
   /* tell system services that we are in async mode ... */
   ss_set_async_flag(TRUE);
   /* Calculate the time since last watchdog call. Kill clients if they
      are inactive for more than the timeout they specified */
   actual_time = ss_millitime();
   if (_watchdog_last_called == 0)
      _watchdog_last_called = actual_time - WATCHDOG_INTERVAL;
   interval = actual_time - _watchdog_last_called;
   /* check if system time has been changed more than 10 min */
   time_changed = interval < 0 || interval > 600000;
   wrong_interval = interval < 0.8 * WATCHDOG_INTERVAL
       || interval > 1.2 * WATCHDOG_INTERVAL;
   if (time_changed)
      cm_msg(MINFO, "cm_watchdog",
             "System time has been changed! last:%dms  now:%dms  delta:%dms",
             _watchdog_last_called, actual_time, interval);
   /* check buffers */
   for (i = 0; i < _buffer_entries; i++)
      if (_buffer[i].attached) {
         /* update the last_activity entry to show that we are alive */
         pheader = _buffer[i].buffer_header;
         pbclient = pheader->client;
         pbclient[_buffer[i].client_index].last_activity = actual_time;
         /* don't check other clients if interval is stange */
         if (wrong_interval)
            continue;
         /* now check other clients */
         for (j = 0; j < pheader->max_client_index; j++, pbclient++)
            /* If client process has no activity, clear its buffer entry. */
            if (pbclient->pid && pbclient->watchdog_timeout > 0 &&
                actual_time - pbclient->last_activity > pbclient->watchdog_timeout) {
               bm_lock_buffer(i + 1);
               str[0] = 0;
               /* now make again the check with the buffer locked */
               actual_time = ss_millitime();
               if (pbclient->pid && pbclient->watchdog_timeout > 0 &&
                   actual_time > pbclient->last_activity &&
                   actual_time - pbclient->last_activity > pbclient->watchdog_timeout) {
                  sprintf(str, "Client %s on %s removed (idle %1.1lfs,TO %1.0lfs)",
                          pbclient->name, pheader->name,
                          (actual_time - pbclient->last_activity) / 1000.0,
                          pbclient->watchdog_timeout / 1000.0);
                  /* clear entry from client structure in buffer header */
                  memset(&(pheader->client[j]), 0, sizeof(BUFFER_CLIENT));
                  /* calculate new max_client_index entry */
                  for (k = MAX_CLIENTS - 1; k >= 0; k--)
                     if (pheader->client[k].pid != 0)
                        break;
                  pheader->max_client_index = k + 1;
                  /* count new number of clients */
                  for (k = MAX_CLIENTS - 1, nc = 0; k >= 0; k--)
                     if (pheader->client[k].pid != 0)
                        nc++;
                  pheader->num_clients = nc;
                  /* check if anyone is wating and wake him up */
                  pbctmp = pheader->client;
                  for (k = 0; k < pheader->max_client_index; k++, pbctmp++)
                     if (pbctmp->pid && (pbctmp->write_wait || pbctmp->read_wait))
                        ss_resume(pbctmp->port, "B  ");
               }
               bm_unlock_buffer(i + 1);
               /* display info message after unlocking buffer */
               if (str[0])
                  cm_msg(MINFO, "cm_watchdog", str);
            }
      }
   /* check online databases */
   for (i = 0; i < _database_entries; i++)
      if (_database[i].attached) {
         /* update the last_activity entry to show that we are alive */
         pdbheader = _database[i].database_header;
         pdbclient = pdbheader->client;
         pdbclient[_database[i].client_index].last_activity = actual_time;
         /* don't check other clients if interval is stange */
         if (wrong_interval)
            continue;
         /* now check other clients */
         for (j = 0; j < pdbheader->max_client_index; j++, pdbclient++)
            /* If client process has no activity, clear its buffer entry. */
            if (pdbclient->pid && pdbclient->watchdog_timeout > 0 &&
                actual_time - pdbclient->last_activity > pdbclient->watchdog_timeout) {
               client_pid = pdbclient->tid;
               bDeleted = FALSE;
               db_lock_database(i + 1);
               str[0] = 0;
               /* now make again the check with the buffer locked */
               actual_time = ss_millitime();
               if (pdbclient->pid && pdbclient->watchdog_timeout &&
                   actual_time > pdbclient->last_activity &&
                   actual_time - pdbclient->last_activity > pdbclient->watchdog_timeout) {
                  sprintf(str,
                          "Client %s (PID %d) on %s removed (idle %1.1lfs,TO %1.0lfs)",
                          pdbclient->name, client_pid, pdbheader->name,
                          (actual_time - pdbclient->last_activity) / 1000.0,
                          pdbclient->watchdog_timeout / 1000.0);
                  /* decrement notify_count for open records and clear exclusive mode */
                  for (k = 0; k < pdbclient->max_index; k++)
                     if (pdbclient->open_record[k].handle) {
                        pkey = (KEY *) ((char *) pdbheader +
                                        pdbclient->open_record[k].handle);
                        if (pkey->notify_count > 0)
                           pkey->notify_count--;
                        if (pdbclient->open_record[k].access_mode & MODE_WRITE)
                           db_set_mode(i + 1, pdbclient->open_record[k].handle,
                                       (WORD) (pkey->access_mode & ~MODE_EXCLUSIVE), 2);
                     }
                  /* clear entry from client structure in buffer header */
                  memset(&(pdbheader->client[j]), 0, sizeof(DATABASE_CLIENT));
                  /* calculate new max_client_index entry */
                  for (k = MAX_CLIENTS - 1; k >= 0; k--)
                     if (pdbheader->client[k].pid != 0)
                        break;
                  pdbheader->max_client_index = k + 1;
                  /* count new number of clients */
                  for (k = MAX_CLIENTS - 1, nc = 0; k >= 0; k--)
                     if (pdbheader->client[k].pid != 0)
                        nc++;
                  pdbheader->num_clients = nc;
                  bDeleted = TRUE;
               }
               /* delete client entry before unlocking db */
               if (bDeleted) {
                  status = cm_delete_client_info(i + 1, client_pid);
                  if (status != CM_SUCCESS)
                     cm_msg(MERROR, "cm_watchdog", "cannot delete client info");
               }
               db_unlock_database(i + 1);
               /* display info message after unlocking db */
               if (str[0])
                  cm_msg(MINFO, "cm_watchdog", str);
            }
      }
   _watchdog_last_called = actual_time;
   ss_set_async_flag(FALSE);
   /* Schedule next watchdog call */
   if (_call_watchdog)
      ss_alarm(WATCHDOG_INTERVAL, cm_watchdog);
}
INT cm_yield (INT millisec)
dox Central yield functions for clients. This routine should be called in an infinite loop by a client in order to give the MIDAS system the opportunity to receive commands over RPC channels, update database records and receive events.
Parameters:
millisec Timeout in millisec. If no message is received during the specified timeout, the routine returns. If millisec=-1, it only returns when receiving an RPC_SHUTDOWN message.
Returns:
CM_SUCCESS, RPC_SHUTDOWN
Definition at line 4166 of file midas.c.
References al_check(), bm_check_buffers(), bm_mark_read_waiting(), bm_poll_event(), FALSE, rpc_is_remote(), RPC_SHUTDOWN, ss_suspend(), ss_time(), status, and TRUE.
Referenced by analyze_run(), caen170a_get_all(), caen170a_set_all(), check_abort(), cmd_idle(), command_loop(), dl40x_read(), lazy_copy(), load_parameters(), loop_online(), lrs1454_get(), lrs4032_get_all(), lrs4032_set(), lrs4032_set_all(), main(), poll_event(), rpc_master_poll_dead(), rpc_master_poll_live(), rpc_slave_poll_live(), scan_fragment(), scheduler(), server_loop(), source_scan(), TimerProc(), tr_poststop(), and tr_stop().
{
   INT status;
   BOOL bMore;
   static DWORD last_checked = 0;
   /* check for ctrl-c */
   if (_ctrlc_pressed)
      return RPC_SHUTDOWN;
   /* check for available events */
   if (rpc_is_remote()) {
      bMore = bm_poll_event(TRUE);
      if (bMore)
         status = ss_suspend(0, 0);
      else
         status = ss_suspend(millisec, 0);
      return status;
   }
   /* check alarms once every 10 seconds */
   if (!rpc_is_remote() && ss_time() - last_checked > 10) {
      al_check();
      last_checked = ss_time();
   }
   bMore = bm_check_buffers();
   if (bMore) {
      /* if events available, quickly check other IPC channels */
      status = ss_suspend(0, 0);
   } else {
      /* mark event buffers for ready-to-receive */
      bm_mark_read_waiting(TRUE);
      status = ss_suspend(millisec, 0);
      /* unmark event buffers for ready-to-receive */
      bm_mark_read_waiting(FALSE);
   }
   return status;
}
int tr_compare (const void * arg1, const void * arg2)
Definition at line 3534 of file midas.c.
Referenced by cm_transition().
{
   return ((TR_CLIENT *)arg1)->sequence_number - ((TR_CLIENT*)arg2)->sequence_number;
}
Variable Documentation
BOOL _ctrlc_pressed = FALSE [static]
Definition at line 4124 of file midas.c.
DWORD _deferred_transition_mask [static]
Definition at line 3403 of file midas.c.
INT _requested_transition [static]
dox
Definition at line 3402 of file midas.c.
experiment_table exptab[MAX_EXPERIMENT] [static]
Definition at line 1759 of file midas.c.