AlcapDAQ:Rootana: Midas Message Functions (msg_xxx)
Midas Message Functions (msg_xxx)
[The midas.h & midas.c]
Functions
INT cm_get_error (INT code, char *string)
INT cm_set_msg_print (INT system_mask, INT user_mask, int(*func)(const char *))
INT cm_msg_log (INT message_type, const char *message)
INT cm_msg_log1 (INT message_type, const char *message, const char *facility)
INT cm_msg (INT message_type, char *filename, INT line, const char *routine, const char *format,...)
INT cm_msg1 (INT message_type, char *filename, INT line, const char *facility, const char *routine, const char *format,...)
INT cm_msg_register (void(*func)(HNDLE, HNDLE, EVENT_HEADER *, void *))
INT cm_msg_retrieve (INT n_message, char *message, INT *buf_size)
Detailed Description
dox dox
Function Documentation
INT cm_get_error (INT code, char * string)
Convert error code to string. Used after cm_connect_experiment to print error string in command line programs or windows programs.
Parameters:
code Error code as defined in midas.h
string Error string
Returns:
CM_SUCCESS
Definition at line 987 of file midas.c.
References CM_SUCCESS, ERROR_TABLE::code, and i.
Referenced by cm_connect_experiment(), CMExperiment::Connect(), and main().
{
   INT i;
   for (i = 0; _error_table[i].code; i++)
      if (_error_table[i].code == code) {
         strcpy(string, _error_table[i].string);
         return CM_SUCCESS;
      }
   sprintf(string, "Unexpected error #%d", code);
   return CM_SUCCESS;
}
INT cm_msg (INT message_type, char * filename, INT line, const char * routine, const char * format, ...)
This routine can be called whenever an internal error occurs or an informative message is produced. Different message types can be enabled or disabled by setting the type bits via cm_set_msg_print().
Attention:
Do not add the "\n" escape carriage control at the end of the formated line as it is already added by the client on the receiving side.
   ...
   cm_msg(MINFO, "my program", "This is a information message only);
   cm_msg(MERROR, "my program", "This is an error message with status:%d", my_status);
   cm_msg(MTALK, "my_program", My program is Done!");
   ...
Parameters:
message_type (See midas_macro).
filename Name of source file where error occured
line Line number where error occured
routine Routine name.
format message to printout, ... Parameters like for printf()
Returns:
CM_SUCCESS
Definition at line 1233 of file midas.c.
References _message_mask_system, _message_mask_user, _message_print, _msg_buffer, bm_compose_event(), BM_CREATED, bm_open_buffer(), bm_send_event(), BM_SUCCESS, cm_msg_log(), CM_SUCCESS, EVENT_HEADER::data_size, EVENTID_MESSAGE, FALSE, MESSAGE_BUFFER_NAME, MESSAGE_BUFFER_SIZE, MT_ERROR, MT_LOG, MT_USER, rpc_get_name(), status, SYNC, and TRUE.
{
   va_list argptr;
   char event[1000], str[256], local_message[256], send_message[256], *pc;
   EVENT_HEADER *pevent;
   INT status;
   static BOOL in_routine = FALSE;
   /* avoid recursive calls */
   if (in_routine)
      return 0;
   in_routine = TRUE;
   /* strip path */
   pc = filename + strlen(filename);
   while (*pc != '\\' && *pc != '/' && pc != filename)
      pc--;
   if (pc != filename)
      pc++;
   /* print client name into string */
   if (message_type == MT_USER)
      sprintf(send_message, "[%s] ", routine);
   else {
      rpc_get_name(str);
      if (str[0])
         sprintf(send_message, "[%s] ", str);
      else
         send_message[0] = 0;
   }
   local_message[0] = 0;
   /* preceed error messages with file and line info */
   if (message_type == MT_ERROR) {
      sprintf(str, "[%s:%d:%s] ", pc, line, routine);
      strcat(send_message, str);
      strcat(local_message, str);
   }
   /* print argument list into message */
   va_start(argptr, format);
   vsprintf(str, (char *) format, argptr);
   va_end(argptr);
   strcat(send_message, str);
   strcat(local_message, str);
   /* call user function if set via cm_set_msg_print */
   if (_message_print != NULL && (message_type & _message_mask_user) != 0)
      _message_print(local_message);
   /* return if system mask is not set */
   if ((message_type & _message_mask_system) == 0) {
      in_routine = FALSE;
      return CM_SUCCESS;
   }
   /* copy message to event */
   pevent = (EVENT_HEADER *) event;
   strcpy(event + sizeof(EVENT_HEADER), send_message);
   /* send event if not of type MLOG */
   if (message_type != MT_LOG) {
      /* if no message buffer already opened, do so now */
      if (_msg_buffer == 0) {
         status = bm_open_buffer(MESSAGE_BUFFER_NAME, MESSAGE_BUFFER_SIZE, &_msg_buffer);
         if (status != BM_SUCCESS && status != BM_CREATED) {
            in_routine = FALSE;
            return status;
         }
      }
      /* setup the event header and send the message */
      bm_compose_event(pevent, EVENTID_MESSAGE, (WORD) message_type,
                       strlen(event + sizeof(EVENT_HEADER)) + 1, 0);
      bm_send_event(_msg_buffer, event, pevent->data_size + sizeof(EVENT_HEADER), SYNC);
   }
   /* log message */
   cm_msg_log(message_type, send_message);
   in_routine = FALSE;
   return CM_SUCCESS;
}
INT cm_msg1 (INT message_type, char * filename, INT line, const char * facility, const char * routine, const char * format, ...)
This routine is similar to cm_msg(). It differs from cm_msg() only by the logging destination being a file given through the argument list i.e:facility
Definition at line 1346 of file midas.c.
References _message_mask_system, _message_mask_user, _message_print, _msg_buffer, bm_compose_event(), BM_CREATED, bm_open_buffer(), bm_send_event(), BM_SUCCESS, cm_msg_log1(), CM_SUCCESS, EVENT_HEADER::data_size, EVENTID_MESSAGE, FALSE, MESSAGE_BUFFER_NAME, MESSAGE_BUFFER_SIZE, MT_ERROR, MT_LOG, MT_USER, rpc_get_name(), status, SYNC, and TRUE.
Referenced by lazy_copy(), and lazy_log_update().
{
   va_list argptr;
   char event[1000], str[256], local_message[256], send_message[256], *pc;
   EVENT_HEADER *pevent;
   INT status;
   static BOOL in_routine = FALSE;
   /* avoid recursive calles */
   if (in_routine)
      return 0;
   in_routine = TRUE;
   /* strip path */
   pc = filename + strlen(filename);
   while (*pc != '\\' && *pc != '/' && pc != filename)
      pc--;
   if (pc != filename)
      pc++;
   /* print client name into string */
   if (message_type == MT_USER)
      sprintf(send_message, "[%s] ", routine);
   else {
      rpc_get_name(str);
      if (str[0])
         sprintf(send_message, "[%s] ", str);
      else
         send_message[0] = 0;
   }
   local_message[0] = 0;
   /* preceed error messages with file and line info */
   if (message_type == MT_ERROR) {
      sprintf(str, "[%s:%d:%s] ", pc, line, routine);
      strcat(send_message, str);
      strcat(local_message, str);
   }
   /* print argument list into message */
   va_start(argptr, format);
   vsprintf(str, (char *) format, argptr);
   va_end(argptr);
   if (facility)
      sprintf(local_message + strlen(local_message), "{%s} ", facility);
   strcat(send_message, str);
   strcat(local_message, str);
   /* call user function if set via cm_set_msg_print */
   if (_message_print != NULL && (message_type & _message_mask_user) != 0)
      _message_print(local_message);
   /* return if system mask is not set */
   if ((message_type & _message_mask_system) == 0) {
      in_routine = FALSE;
      return CM_SUCCESS;
   }
   /* copy message to event */
   pevent = (EVENT_HEADER *) event;
   strcpy(event + sizeof(EVENT_HEADER), send_message);
   /* send event if not of type MLOG */
   if (message_type != MT_LOG) {
      /* if no message buffer already opened, do so now */
      if (_msg_buffer == 0) {
         status = bm_open_buffer(MESSAGE_BUFFER_NAME, MESSAGE_BUFFER_SIZE, &_msg_buffer);
         if (status != BM_SUCCESS && status != BM_CREATED) {
            in_routine = FALSE;
            return status;
         }
      }
      /* setup the event header and send the message */
      bm_compose_event(pevent, EVENTID_MESSAGE, (WORD) message_type,
                       strlen(event + sizeof(EVENT_HEADER)) + 1, 0);
      bm_send_event(_msg_buffer, event, pevent->data_size + sizeof(EVENT_HEADER), SYNC);
   }
   /* log message */
   cm_msg_log1(message_type, send_message, facility);
   in_routine = FALSE;
   return CM_SUCCESS;
}
INT cm_msg_log (INT message_type, const char * message)
Write message to logging file. Called by cm_msg.
Attention:
May burn your fingers
Parameters:
message_type Message type
message Message string
Returns:
CM_SUCCESS
Definition at line 1049 of file midas.c.
References cm_get_experiment_database(), cm_get_path(), CM_SUCCESS, db_find_key(), db_get_value(), DB_SUCCESS, DIR_SEPARATOR, DIR_SEPARATOR_STR, filename, hDB, hKey, MT_DEBUG, rpc_call(), RPC_CM_MSG_LOG, rpc_is_remote(), size, ss_asctime(), status, TID_STRING, and TRUE.
Referenced by cm_msg(), and rpc_server_dispatch().
{
   char dir[256];
   char filename[256];
   char path[256];
   char str[256];
   FILE *f;
   INT status, size;
   HNDLE hDB, hKey;
   if (rpc_is_remote())
      return rpc_call(RPC_CM_MSG_LOG, message_type, message);
   if (message_type != MT_DEBUG) {
      cm_get_experiment_database(&hDB, NULL);
      if (hDB) {
         status = db_find_key(hDB, 0, "/Logger/Data dir", &hKey);
         if (status == DB_SUCCESS) {
            size = sizeof(dir);
            memset(dir, 0, size);
            db_get_value(hDB, 0, "/Logger/Data dir", dir, &size, TID_STRING, TRUE);
            if (dir[0] != 0)
               if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
                  strcat(dir, DIR_SEPARATOR_STR);
            strcpy(filename, "midas.log");
            size = sizeof(filename);
            db_get_value(hDB, 0, "/Logger/Message file", filename, &size, TID_STRING,
                         TRUE);
            strcpy(path, dir);
            strcat(path, filename);
         } else {
            cm_get_path(dir);
            if (dir[0] != 0)
               if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
                  strcat(dir, DIR_SEPARATOR_STR);
            strcpy(path, dir);
            strcat(path, "midas.log");
         }
      } else
         strcpy(path, "midas.log");
      f = fopen(path, "a");
      if (f == NULL) {
         printf("Cannot open message log file %s\n", path);
      } else {
         strcpy(str, ss_asctime());
         fprintf(f, str);
         fprintf(f, " %s\n", message);
         fclose(f);
      }
   }
   return CM_SUCCESS;
}
INT cm_msg_log1 (INT message_type, const char * message, const char * facility)
Write message to logging file. Called by cm_msg().
Definition at line 1118 of file midas.c.
References cm_get_experiment_database(), cm_get_path(), CM_SUCCESS, db_find_key(), db_get_value(), DB_SUCCESS, DIR_SEPARATOR, DIR_SEPARATOR_STR, filename, hDB, hKey, MT_DEBUG, rpc_call(), RPC_CM_MSG_LOG1, rpc_is_remote(), size, ss_asctime(), status, TID_STRING, and TRUE.
Referenced by cm_msg1(), and rpc_server_dispatch().
         : cm_msg_log1
  Purpose: Write message to logging file. Called by cm_msg.
           Internal use only
  Input:
    INT    message_type      Message type
    char   *message          Message string
    char   *
  Output:
    none
  Function value:
    CM_SUCCESS
\********************************************************************/
{
   char dir[256];
   char filename[256];
   char path[256];
   char str[256];
   FILE *f;
   INT status, size;
   HNDLE hDB, hKey;
   if (rpc_is_remote())
      return rpc_call(RPC_CM_MSG_LOG1, message_type, message, facility);
   if (message_type != MT_DEBUG) {
      cm_get_experiment_database(&hDB, NULL);
      if (hDB) {
         status = db_find_key(hDB, 0, "/Logger/Data dir", &hKey);
         if (status == DB_SUCCESS) {
            size = sizeof(dir);
            memset(dir, 0, size);
            db_get_value(hDB, 0, "/Logger/Data dir", dir, &size, TID_STRING, TRUE);
            if (dir[0] != 0)
               if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
                  strcat(dir, DIR_SEPARATOR_STR);
            if (facility[0]) {
               strcpy(filename, facility);
               strcat(filename, ".log");
            } else {
               strcpy(filename, "midas.log");
               size = sizeof(filename);
               db_get_value(hDB, 0, "/Logger/Message file", filename, &size, TID_STRING,
                            TRUE);
            }
            strcpy(path, dir);
            strcat(path, filename);
         } else {
            cm_get_path(dir);
            if (dir[0] != 0)
               if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
                  strcat(dir, DIR_SEPARATOR_STR);
            strcpy(path, dir);
            if (facility[0]) {
               strcat(path, facility);
               strcat(path, ".log");
            } else
               strcat(path, "midas.log");
         }
      } else {
         if (facility[0]) {
            strcpy(path, facility);
            strcat(path, ".log");
         } else
            strcpy(path, "midas.log");
      }
      f = fopen(path, "a");
      if (f == NULL) {
         printf("Cannot open message log file %s\n", path);
      } else {
         strcpy(str, ss_asctime());
         fprintf(f, str);
         fprintf(f, " %s\n", message);
         fclose(f);
      }
   }
   return CM_SUCCESS;
}
INT cm_msg_register (void(*)(HNDLE, HNDLE, EVENT_HEADER *, void *) func)
Register a dispatch function for receiving system messages.
example code from mlxspeaker.c
void receive_message(HNDLE hBuf, HNDLE id, EVENT_HEADER *header, void *message)
{
  char str[256], *pc, *sp;
  // print message
  printf("%s\n", (char *)(message));
  printf("evID:%x Mask:%x Serial:%i Size:%d\n"
                 ,header->event_id
                 ,header->trigger_mask
                 ,header->serial_number
                 ,header->data_size);
  pc = strchr((char *)(message),']')+2;
  ...
  // skip none talking message
  if (header->trigger_mask == MT_TALK ||
      header->trigger_mask == MT_USER)
   ...
}
int main(int argc, char *argv[])
{
  ...
  // now connect to server
  status = cm_connect_experiment(host_name, exp_name, "Speaker", NULL);
  if (status != CM_SUCCESS)
    return 1;
  // Register callback for messages
  cm_msg_register(receive_message);
  ...
}
Parameters:
func Dispatch function.
Returns:
CM_SUCCESS or bm_open_buffer and bm_request_event return status
Definition at line 1477 of file midas.c.
References _msg_buffer, _msg_dispatch, BM_CREATED, bm_open_buffer(), bm_request_event(), BM_SUCCESS, EVENTID_ALL, GET_SOME, MESSAGE_BUFFER_NAME, MESSAGE_BUFFER_SIZE, status, and TRIGGER_ALL.
Referenced by interprete(), and main().
{
   INT status, id;
   /* if no message buffer already opened, do so now */
   if (_msg_buffer == 0) {
      status = bm_open_buffer(MESSAGE_BUFFER_NAME, MESSAGE_BUFFER_SIZE, &_msg_buffer);
      if (status != BM_SUCCESS && status != BM_CREATED)
         return status;
   }
   _msg_dispatch = func;
   status = bm_request_event(_msg_buffer, EVENTID_ALL, TRIGGER_ALL, GET_SOME, &id, func);
   return status;
}
INT cm_msg_retrieve (INT n_message, char * message, INT * buf_size)
Retrieve old messages from log file
Parameters:
n_message Number of messages to retrieve
message buf_size bytes of messages, separated by
characters. The returned number of bytes is normally smaller than the initial buf_size, since only full lines are returned.
*buf_size Size of message buffer to fill
Returns:
CM_SUCCESS
Definition at line 1507 of file midas.c.
References CM_DB_ERROR, cm_get_experiment_database(), cm_get_path(), CM_SUCCESS, db_find_key(), db_get_value(), DB_SUCCESS, DIR_SEPARATOR, DIR_SEPARATOR_STR, filename, hDB, hKey, i, offset, p, PTYPE, rpc_call(), RPC_CM_MSG_RETRIEVE, rpc_is_remote(), size, status, TID_STRING, and TRUE.
Referenced by command_loop(), interprete(), rpc_server_dispatch(), and show_messages_page().
{
   char dir[256];
   char filename[256];
   char path[256], *p;
   FILE *f;
   INT status, size, offset, i;
   HNDLE hDB, hKey;
   if (rpc_is_remote())
      return rpc_call(RPC_CM_MSG_RETRIEVE, message, buf_size);
   cm_get_experiment_database(&hDB, NULL);
   if (hDB) {
      status = db_find_key(hDB, 0, "/Logger/Data dir", &hKey);
      if (status == DB_SUCCESS) {
         size = sizeof(dir);
         memset(dir, 0, size);
         db_get_value(hDB, 0, "/Logger/Data dir", dir, &size, TID_STRING, TRUE);
         if (dir[0] != 0)
            if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
               strcat(dir, DIR_SEPARATOR_STR);
         strcpy(filename, "midas.log");
         size = sizeof(filename);
         db_get_value(hDB, 0, "/Logger/Message file", filename, &size, TID_STRING, TRUE);
         strcpy(path, dir);
         strcat(path, filename);
      } else {
         cm_get_path(dir);
         if (dir[0] != 0)
            if (dir[strlen(dir) - 1] != DIR_SEPARATOR)
               strcat(dir, DIR_SEPARATOR_STR);
         strcpy(path, dir);
         strcat(path, "midas.log");
      }
   } else
      strcpy(path, "midas.log");
   f = fopen(path, "rb");
   if (f == NULL) {
      sprintf(message, "Cannot open message log file %s\n", path);
      *buf_size = strlen(message);
      return CM_DB_ERROR;
   } else {
      /* position buf_size bytes before the EOF */
      fseek(f, -(*buf_size - 1), SEEK_END);
      offset = ftell(f);
      if (offset != 0) {
         /* go to end of line */
         fgets(message, *buf_size - 1, f);
         offset = ftell(f) - offset;
         *buf_size -= offset;
      }
      memset(message, 0, *buf_size);
      fread(message, 1, *buf_size - 1, f);
      message[*buf_size - 1] = 0;
      fclose(f);
      p = message + (*buf_size - 2);
      /* goto end of buffer */
      while (p != message && *p == 0)
         p--;
      /* strip line break */
      while (p != message && (*p == '\n' || *p == '\r'))
         *(p--) = 0;
      /* trim buffer so that last n_messages remain */
      for (i = 0; i < n_message; i++) {
         while (p != message && *p != '\n')
            p--;
         while (p != message && (*p == '\n' || *p == '\r'))
            p--;
      }
      if (p != message) {
         p++;
         while (*p == '\n' || *p == '\r')
            p++;
      }
      *buf_size = (*buf_size - 1) - ((PTYPE) p - (PTYPE) message);
      memmove(message, p, *buf_size);
      message[*buf_size] = 0;
   }
   return CM_SUCCESS;
}
INT cm_set_msg_print (INT system_mask, INT user_mask, int(*)(const char *) func)
Set message masks. When a message is generated by calling cm_msg(), it can got to two destinatinons. First a user defined callback routine and second to the "SYSMSG" buffer.
A user defined callback receives all messages which satisfy the user_mask.
int message_print(const char *msg)
{
  char str[160];
  memset(str, ' ', 159);
  str[159] = 0;
  if (msg[0] == '[')
    msg = strchr(msg, ']')+2;
  memcpy(str, msg, strlen(msg));
  ss_printf(0, 20, str);
  return 0;
}
...
  cm_set_msg_print(MT_ALL, MT_ALL, message_print);
...
Parameters:
system_mask Bit masks for MERROR, MINFO etc. to send system messages.
user_mask Bit masks for MERROR, MINFO etc. to send messages to the user callback.
func Function which receives all printout. By setting "puts", messages are just printed to the screen.
Returns:
CM_SUCCESS
Definition at line 1032 of file midas.c.
References _message_mask_system, _message_mask_user, _message_print, and BM_SUCCESS.
Referenced by cam_init_rpc(), cm_connect_experiment1(), CMExperiment::Connect(), interprete(), main(), and CMExperiment::~CMExperiment().
{
   _message_mask_system = system_mask;
   _message_mask_user = user_mask;
   _message_print = func;
   return BM_SUCCESS;
}