AlcapDAQ:Rootana: midas/examples/hbookexpt/adcsum.c File Reference
midas/examples/hbookexpt/adcsum.c File Reference
#include <stdio.h>
#include <math.h>
#include "midas.h"
#include "experim.h"
#include "analyzer.h"
#include <cfortran.h>
#include <hbook.h>
Functions
INT adc_summing (EVENT_HEADER *, void *)
INT adc_summing_init (void)
INT adc_summing_bor (INT run_number)
ADC_SUMMING_PARAM_STR (adc_summing_param_str)
Variables
ADC_SUMMING_PARAM adc_summing_param
ANA_MODULE adc_summing_module
Function Documentation
INT adc_summing (EVENT_HEADER * pheader, void * pevent)
Definition at line 104 of file adcsum.c.
References ADCSUM_ID_BASE, ASUM_BANK::average, bk_close(), bk_create(), bk_locate(), HF1, i, j, SUCCESS, ASUM_BANK::sum, and TID_STRUCT.
{
   INT i, j, n_adc;
   float *cadc;
   ASUM_BANK *asum;
   /* look for CADC bank, return if not present */
   n_adc = bk_locate(pevent, "CADC", &cadc);
   if (n_adc == 0)
      return 1;
   /* create ADC sum bank */
   bk_create(pevent, "ASUM", TID_STRUCT, &asum);
   /* sum all channels above threashold */
   asum->sum = 0.f;
   for (i = j = 0; i < n_adc; i++)
      if (cadc[i] > adc_summing_param.adc_threshold) {
         asum->sum += cadc[i];
         j++;
      }
   /* calculate ADC average */
   asum->average = j > 0 ? asum->sum / j : 0;
   /* fill sum histo */
   HF1(ADCSUM_ID_BASE, asum->sum, 1.f);
   /* close calculated bank */
   bk_close(pevent, asum + 1);
   return SUCCESS;
}
INT adc_summing_bor (INT run_number)
INT adc_summing_init (void)
Definition at line 91 of file adcsum.c.
References ADCSUM_ID_BASE, HBOOK1, name, and SUCCESS.
{
   char name[80];
   /* book sum histo */
   strcpy(name, "ADC sum");
   HBOOK1(ADCSUM_ID_BASE, name, 500, 0.f, 10000.f, 0.f);
   return SUCCESS;
}
ADC_SUMMING_PARAM_STR (adc_summing_param_str)
Variable Documentation
ANA_MODULE adc_summing_module
Initial value:
 {
   "ADC summing",
   "Stefan Ritt",
   adc_summing,
   NULL,
   NULL,
   adc_summing_init,
   NULL,
   &adc_summing_param,
   sizeof(adc_summing_param),
   adc_summing_param_str,
}
Definition at line 68 of file adcsum.c.
ADC_SUMMING_PARAM adc_summing_param
Definition at line 58 of file adcsum.c.