AlcapDAQ:Rootana: midas/examples/hbookexpt/scaler.c File Reference
midas/examples/hbookexpt/scaler.c File Reference
#include <stdio.h>
#include <string.h>
#include <time.h>
#include "midas.h"
#include "experim.h"
#include "analyzer.h"
Functions
INT scaler_accum (EVENT_HEADER *, void *)
INT scaler_clear (INT run_number)
INT scaler_eor (INT run_number)
Variables
ANA_MODULE scaler_accum_module
double scaler [32]
Function Documentation
INT scaler_accum (EVENT_HEADER * pheader, void * pevent)
Definition at line 85 of file scaler.c.
References bk_close(), bk_create(), bk_locate(), i, n, scaler, SUCCESS, and TID_DOUBLE.
{
   INT n, i;
   DWORD *psclr;
   double *pacum;
   /* look for SCLR bank */
   n = bk_locate(pevent, "SCLR", &psclr);
   if (n == 0)
      return 1;
   /* create acummulated scaler bank */
   bk_create(pevent, "ACUM", TID_DOUBLE, &pacum);
   /* accumulate scalers */
   for (i = 0; i < n; i++) {
      scaler[i] += psclr[i];
      pacum[i] = scaler[i];
   }
   /* close bank */
   bk_close(pevent, pacum + n);
   return SUCCESS;
}
INT scaler_clear (INT run_number)
Definition at line 70 of file scaler.c.
References scaler, and SUCCESS.
{
   memset(scaler, 0, sizeof(scaler));
   return SUCCESS;
}
INT scaler_eor (INT run_number)
Definition at line 78 of file scaler.c.
References SUCCESS.
{
   return SUCCESS;
}
Variable Documentation
double scaler[32]
Definition at line 66 of file scaler.c.
ANA_MODULE scaler_accum_module
Initial value:
 {
   "Scaler accumulation",
   "Stefan Ritt",
   scaler_accum,
   scaler_clear,
   scaler_eor,
   NULL,
   NULL,
   NULL,
   0,
   NULL,
}
Definition at line 51 of file scaler.c.