AlcapDAQ:Rootana: midas/drivers/bus/jorway73a.c File Reference
midas/drivers/bus/jorway73a.c File Reference
#include <stdio.h>
#include "midas.h"
#include "mcstd.h"
#include "jorway73a.h"
#include <unistd.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include "/usr/src/linux/include/scsi/sg.h"
#include <sys/types.h>
#include <sys/stat.h>
Defines
#define SJY73A
#define XDEFLG
#define NAFCMD(n, a, f) ((SJY_CAMAC_EXT((f),(n),(a),1)))
#define SCSI_OFF sizeof(struct sg_header)
#define USER_BUF_SIZE (SG_BIG_BUFF - (SCSI_OFF + 18 + 511))
#define CMD_SIZE (SCSI_OFF + 18 + USER_BUF_SIZE)
Functions
unsigned int cdchn (int branch, int channel, int route)
INLINE void cam8i (const int c, const int n, const int a, const int f, unsigned char *d)
INLINE void cami (const int c, const int n, const int a, const int f, WORD *d)
INLINE void cam16i (const int c, const int n, const int a, const int f, WORD *d)
INLINE void cam24i (const int c, const int n, const int a, const int f, DWORD *d)
INLINE void cam8i_q (const int c, const int n, const int a, const int f, unsigned char *d, int *x, int *q)
INLINE void cam16i_q (const int c, const int n, const int a, const int f, WORD *d, int *x, int *q)
INLINE void cam24i_q (const int c, const int n, const int a, const int f, DWORD *d, int *x, int *q)
INLINE void cam16i_r (const int c, const int n, const int a, const int f, WORD **d, const int r)
INLINE void cam24i_r (const int c, const int n, const int a, const int f, DWORD **d, const int r)
INLINE void cam16i_rq (const int c, const int n, const int a, const int f, WORD **d, const int r)
INLINE void cam24i_rq (const int c, const int n, const int a, const int f, DWORD **d, const int r)
INLINE void cam16i_sa (const int c, const int n, const int a, const int f, WORD **d, const int r)
INLINE void cam24i_sa (const int c, const int n, const int a, const int f, DWORD **d, const int r)
INLINE void cam16i_sn (const int c, const int n, const int a, const int f, WORD **d, const int r)
INLINE void cam24i_sn (const int c, const int n, const int a, const int f, DWORD **d, const int r)
INLINE void cam8o (const int c, const int n, const int a, const int f, unsigned char d)
INLINE void camo (const int c, const int n, const int a, const int f, WORD d)
INLINE void cam16o (const int c, const int n, const int a, const int f, WORD d)
INLINE void cam24o (const int c, const int n, const int a, const int f, DWORD d)
INLINE void cam16o_q (const int c, const int n, const int a, const int f, WORD d, int *x, int *q)
INLINE void cam24o_q (const int c, const int n, const int a, const int f, DWORD d, int *x, int *q)
INLINE void cam8o_r (const int c, const int n, const int a, const int f, BYTE *d, const int r)
INLINE void cam16o_r (const int c, const int n, const int a, const int f, WORD *d, const int r)
INLINE void cam24o_r (const int c, const int n, const int a, const int f, DWORD *d, const int r)
INLINE int camc_chk (const int c)
INLINE void camc (const int c, const int n, const int a, const int f)
INLINE void camc_q (const int c, const int n, const int a, const int f, int *q)
INLINE void camc_sa (const int c, const int n, const int a, const int f, const int r)
INLINE void camc_sn (const int c, const int n, const int a, const int f, const int r)
INLINE int cam_init (void)
INLINE void cam_exit (void)
INLINE void cam_inhibit_set (const int c)
INLINE void cam_inhibit_clear (const int c)
INLINE void cam_crate_clear (const int c)
INLINE void cam_crate_zinit (const int c)
INLINE void cam_lam_enable (const int c, const int n)
INLINE void cam_lam_disable (const int c, const int n)
INLINE void cam_lam_read (const int c, DWORD *lam)
INLINE void cam_lam_clear (const int c, const int n)
INLINE void cam_interrupt_enable (const int c)
INLINE void cam_interrupt_disable (const int c)
INLINE int cam_init_rpc (char *host_name, char *exp_name, char *fe_name, char *client_name, char *rpc_server)
int sjy_get_qx (int branch)
int handle_scsi_cmd (int branch, unsigned cmd_len, unsigned in_size, unsigned char *i_buff, int out_size, unsigned char *o_buff)
int sjy_nondata (int branch, int camCmd)
int sjy_write (int branch, int camCmd, void *dataBuffer, int xferlen)
int sjy_read (int branch, int camCmd, void *dataBuffer, int xferlen)
unsigned char * sjy_inquiry (int branch)
int sjy_tur (int branch)
unsigned char * sjy_reqSense (int branch)
int sjy_notify_camac_data (int branch, int xferlen, int status)
int sjy_notify_camac_nondata (int branch, int xferlen, int status)
int sjy_getdev (char *dev, int branch)
int readFile (FILE *g_rfp, char *filename, char charBuff[], int charBuffsize)
int ccctype (int branch, int lserial, int lparall)
int sjy_inisem ()
int sjy_getsem ()
int sjy_putsem ()
int notify_camac_nondata (int branch, int xferlen, int status)
int notify_camac_data (int branch, int xferlen, int status)
Variables
int xdummy
int qdummy
int ieee_last_Q = 0
int ieee_last_X = 0
WORD d16dummy
DWORD d24dummy
int jorway_crate_opened [8] = { 0 }
DWORD jorway_crate_LAM [8] = { 0 }
static unsigned char cmd [CMD_SIZE]
static char * devtble []
Define Documentation
#define CMD_SIZE (SCSI_OFF + 18 + USER_BUF_SIZE)
Definition at line 627 of file jorway73a.c.
Referenced by sjy_nondata(), sjy_read(), and sjy_write().
#define NAFCMD (n, a, f) ((SJY_CAMAC_EXT((f),(n),(a),1)))
Definition at line 91 of file jorway73a.c.
Referenced by cam16i(), cam16i_q(), cam16i_r(), cam16i_rq(), cam16o_q(), cam16o_r(), cam24i(), cam24i_q(), cam24i_r(), cam24i_rq(), cam24o_q(), cam24o_r(), and camc_q().
#define SCSI_OFF sizeof(struct sg_header)
Definition at line 625 of file jorway73a.c.
Referenced by handle_scsi_cmd(), sjy_inquiry(), sjy_nondata(), sjy_read(), sjy_reqSense(), sjy_tur(), and sjy_write().
#define SJY73A
Definition at line 63 of file jorway73a.c.
#define USER_BUF_SIZE (SG_BIG_BUFF - (SCSI_OFF + 18 + 511))
Definition at line 626 of file jorway73a.c.
#define XDEFLG
Definition at line 64 of file jorway73a.c.
Function Documentation
int ccctype (int branch, int lserial, int lparall)
Definition at line 1375 of file jorway73a.c.
References CAM_S_INVLD_BRANCH, CAM_S_SER_OR_PAR_ONLY, CAM_S_SUCCESS, ID, IDX, SJY_CONTROLLER::serial, SJY_BRANCH_MAX, and sjy_controller.
Referenced by cam_init().
{
   if (ID(branch) < 0 || ID(branch) > SJY_BRANCH_MAX)
      return (CAM_S_INVLD_BRANCH);
   if (lserial & lparall)
      return (CAM_S_SER_OR_PAR_ONLY);
   if (lserial)
      sjy_controller[IDX(branch)].serial = 1;
   if (lparall)
      sjy_controller[IDX(branch)].serial = 0;
   return (CAM_S_SUCCESS);
}
unsigned int cdchn (int branch, int channel, int route)
Definition at line 1192 of file jorway73a.c.
References BUS, CAM_S_DEV_OPEN_FAIL, CAM_S_GETSEM_FAIL, CAM_S_INVLD_BRANCH, CAM_S_PUTSEM_FAIL, CAM_S_SCSI_CLOSE_FAIL, CAM_S_SEM_FAIL, CAM_S_SUCCESS, dev, SJY_CONTROLLER::fd, filename, ID, IDX, SJY_CONTROLLER::scsi_bus, SJY_CONTROLLER::scsi_id, SJY_CONTROLLER::serial, SJY_BRANCH_MAX, sjy_controller, sjy_getdev(), sjy_getsem(), sjy_inisem(), sjy_putsem(), sjy_tur(), and status.
Referenced by cam_exit(), and cam_init().
{
   /* -----------------------------------------------------------------------   */
   char filename[72];
   char version[6];
   int fd;
   int status;
   struct stat buf;
   char dev[32];
   int idx = IDX(branch);
   if (ID(branch) < 0 || ID(branch) > SJY_BRANCH_MAX)
      return (CAM_S_INVLD_BRANCH);
   /* close the SCSI device file */
   if (channel == 0) {
      if (fstat(sjy_controller[idx].fd, &buf) != -1) {
         close(sjy_controller[idx].fd);
         return (CAM_S_SUCCESS);
      }
      return (CAM_S_SCSI_CLOSE_FAIL);
   }
   /* find the scsi device name based on our SCSI id and SCSI bus */
   status = sjy_getdev(filename, branch);
   if (status != CAM_S_SUCCESS) {
      fprintf(stderr, "CDCHN Error finding generic scsi device\n");
      return (status);
   }
   /* create the semaphore */
   if (sjy_inisem() == -1) {
      perror("cdchn: inisem");
      return (CAM_S_SEM_FAIL);
   }
   /* reserve the semaphore */
   if (sjy_getsem() != 0) {
      perror("cdchn: getsem");
      sjy_putsem();
      return (CAM_S_GETSEM_FAIL);
   }
   /* open the scsi device file */
   if ((fd = open(filename, O_RDWR)) == -1) {
      fprintf(stderr, "CDCHN Error opening %s\n", filename);
      perror("CDCHN");
      sjy_putsem();
      return (CAM_S_DEV_OPEN_FAIL);
   }
   /* release the semaphore */
   if (sjy_putsem() != 0) {
      perror("cdchn: putsem");
      return (CAM_S_PUTSEM_FAIL);
   }
#ifdef DEBUG
   fprintf(stderr, "cdchn: filename = %s  fd = %d\n", filename, fd);
#endif
   sjy_controller[idx].scsi_id = ID(branch);
   sjy_controller[idx].scsi_bus = BUS(branch);
   sjy_controller[idx].serial = 1;      /* assume serial */
   sjy_controller[idx].fd = fd;
   /* Send two Test Unit Ready Commands to Jorway */
   status = sjy_tur(branch);
   if (status) {                /* 0=success */
      fprintf(stderr, "CDCHN Error executing Test Unit Ready\n");
      perror("cdchn");
      return (CAM_S_DEV_OPEN_FAIL);
   }
   return (CAM_S_SUCCESS);
}
int handle_scsi_cmd (int branch, unsigned cmd_len, unsigned in_size, unsigned char * i_buff, int out_size, unsigned char * o_buff)
Definition at line 643 of file jorway73a.c.
References CAM_S_DEV_IO_ERROR, CAM_S_GETSEM_FAIL, CAM_S_INVLD_ARG, CAM_S_PUTSEM_FAIL, SJY_CONTROLLER::fd, i, IDX, read, SJY_CONTROLLER::result, SCSI_OFF, SJY_CONTROLLER::sense_buffer, SENSEKEY, sjy_controller, sjy_getsem(), sjy_putsem(), SJY_SENSE_LENGTH, status, SJY_CONTROLLER::target_status, and write.
Referenced by sjy_inquiry(), sjy_nondata(), sjy_read(), sjy_reqSense(), sjy_tur(), and sjy_write().
{
   int status = 0;
   struct sg_header *sg_hd;
   sigset_t newmask, oldmask;
   int i;
   int idx = IDX(branch);
   int fd = sjy_controller[idx].fd;
   int defecit = 0;
#ifdef GDEBUG
   fflush(stderr);
   fflush(stdin);
   fprintf(stderr,
           "handle_scsi_cmd: branch=%d, idx=%d, fd=%d, cmd_len=%d, in_size=%d, ibuff=0x%x, out_size=%d, o_buff=0x%x\n",
           branch, idx, fd, cmd_len, in_size, i_buff, out_size, o_buff);
   fprintf(stderr, "            cmd: 0x");
   for (i = 0; i < cmd_len; i++) {
      fprintf(stderr, " %02x", i_buff[SCSI_OFF + i]);
   }
   fprintf(stderr, "\n");
   fflush(stderr);
   fflush(stdin);
#endif
   /* safety checks */
   if (!cmd_len)
      return (CAM_S_INVLD_ARG); /* need a cmd_len != 0 */
   if (!i_buff)
      return (CAM_S_INVLD_ARG); /* need an input buffer != NULL */
#ifdef SG_BIG_BUFF
   if (SCSI_OFF + cmd_len + in_size > SG_BIG_BUFF)
      return -1;
   if (SCSI_OFF + out_size > SG_BIG_BUFF)
      return -1;
#else
   if (SCSI_OFF + cmd_len + in_size > 4096)
      return -1;
   if (SCSI_OFF + out_size > 4096)
      return -1;
#endif
   if (!o_buff)
      out_size = 0;
   /* generic scsi device header construction */
   sg_hd = (struct sg_header *) i_buff;
   sg_hd->reply_len = SCSI_OFF + out_size;
   sg_hd->twelve_byte = cmd_len == 12;
   sg_hd->result = 0;
#if     0
   sg_hd->pack_len = SCSI_OFF + cmd_len + in_size;      /* not necessary */
   sg_hd->pack_id;              /* not used */
   sg_hd->other_flags;          /* not used */
#endif
   /* protect the write/read from being interrupted by ^C */
   sigemptyset(&newmask);
   sigaddset(&newmask, SIGINT);
   /*  block SIGINT and save current signal mask */
   if (sigprocmask(SIG_BLOCK, &newmask, &oldmask) < 0)
      fprintf(stderr, "sjy_interface: SIG_BLOCK error");
   /* protect the write/read section for multi-user */
   if (sjy_getsem() != 0) {
      fprintf(stderr, "sjy_interface: getsem failed");
      sjy_putsem();
      return (CAM_S_GETSEM_FAIL);
   }
   /* send command */
   status = write(fd, i_buff, SCSI_OFF + cmd_len + in_size);
#ifndef DEBUG
   if (status < 0) {
      sjy_putsem();
      sigprocmask(SIG_SETMASK, &oldmask, NULL);
      return (CAM_S_DEV_IO_ERROR);
   }
#endif
#ifdef DEBUG
   if (status < 0 || status != SCSI_OFF + cmd_len + in_size || sg_hd->result) {
      /* some error happened */
      fprintf(stderr, "write(generic) result = 0x%x cmd = 0x%x\n",
              sg_hd->result, i_buff[SCSI_OFF]);
      if (status < 0)
         perror("sjy_interface");
      sjy_putsem();
      return (CAM_S_DEV_IO_ERROR);
   }
#endif
   /* Since the sg.c driver _read_ always returns the sg_header, we must
    ** provide a buffer +SCSI_OFF in size. Since i_buff was already
    ** allocated as the largest size data buffer we could use (+SCSI_OFF),
    ** we use it. We have to copy the data read back to the user's
    ** buffer, but this ultimatly saves an extra malloc call.
    */
   /* retrieve result */
   status = read(fd, i_buff, SCSI_OFF + out_size);
   /* return the semaphore */
   if (sjy_putsem() != 0) {
      fprintf(stderr, "sjy_interface: getsem failed");
      return (CAM_S_PUTSEM_FAIL);
   }
   /* reset signal mask which unblocks SIGINT */
   if (sigprocmask(SIG_SETMASK, &oldmask, NULL) < 0)
      fprintf(stderr, "sjy_interface: SIG_SETMASK error");
   /* copy data read back to the user buffer */
   /* The generic scsi driver keeps an internal buffer with the
    ** last data read, and does not clear it when a subsequent SCSI
    ** command completes with a non-zero SCSI response. sg_hd->result
    ** does not contain the SCSI response as observed from a SCSI
    ** analyzer, so it is not used. The only alternative is to test
    ** for a non-zero sense buffer sense key field returned from the
    ** Jorway. If the sense key is non-zero, the user buffer is
    ** zeroed instead of returning stale data from the internal SCSI
    ** buffer.
    */
   /* by rex hubbard (jorway): before doing the above, check if the
    ** sensekey is 9, indicating a transfer stopped by q-response. If
    ** so, get the defecit from the sense data and adjust the return
    ** value. The data in the internal buffer is valid, so copy it.
    */
   if (!(sg_hd->sense_buffer[SENSEKEY])) {
      if (o_buff) {
         memcpy(o_buff, i_buff + SCSI_OFF, out_size);
      }
   } else {
      if (sg_hd->sense_buffer[SENSEKEY] == 9) {
         defecit = sg_hd->sense_buffer[4] << 8 | sg_hd->sense_buffer[5];
         defecit = defecit << 8 | sg_hd->sense_buffer[6];
         if (o_buff) {
            memcpy(o_buff, i_buff + SCSI_OFF, out_size);
         }
      } else
         bzero(o_buff, out_size);
   }
   /* save scsi status and sense buffer */
   sjy_controller[idx].result = sg_hd->result;
   memcpy(sjy_controller[idx].sense_buffer, sg_hd->sense_buffer, SJY_SENSE_LENGTH);
   sjy_controller[idx].target_status = (sg_hd->target_status) * 2;
#ifdef GDEBUG
   fflush(stderr);
   fflush(stdin);
   fprintf(stderr, "handle_scsi_command:  target_status=0x%x\n",
           sjy_controller[idx].target_status);
#if 0
   if ((sjy_controller[idx].target_status != 0) &&
       (sjy_controller[idx].target_status != 0))
#endif
   {
      fprintf(stderr, "read(generic) sense "
              "%x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x\n",
              sg_hd->sense_buffer[0], sg_hd->sense_buffer[1],
              sg_hd->sense_buffer[2], sg_hd->sense_buffer[3],
              sg_hd->sense_buffer[4], sg_hd->sense_buffer[5],
              sg_hd->sense_buffer[6], sg_hd->sense_buffer[7],
              sg_hd->sense_buffer[8], sg_hd->sense_buffer[9],
              sg_hd->sense_buffer[10], sg_hd->sense_buffer[11],
              sg_hd->sense_buffer[12], sg_hd->sense_buffer[13],
              sg_hd->sense_buffer[14], sg_hd->sense_buffer[15]);
   }
   fflush(stderr);
   fflush(stdin);
#endif
   /* Unlike the Jorway 73A, the 411S returns SCSI status CONDITION_MET
    ** (0x04) for Q=1 on a data transfer. This is converted by the
    ** generic SCSI driver sg.c to EIO (0x05). The CAMAC completion routines
    ** ignore this status, but the following code segment does not.
    */
#ifdef DEBUG
   if (status < 0 || status != SCSI_OFF + out_size || sg_hd->result) {
      /* some error happened */
      fprintf(stderr, "read(generic) result = 0x%x cmd = 0x%x\n",
              sg_hd->result, i_buff[SCSI_OFF]);
      fprintf(stderr, "read(generic) sense "
              "%x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x\n",
              sg_hd->sense_buffer[0], sg_hd->sense_buffer[1],
              sg_hd->sense_buffer[2], sg_hd->sense_buffer[3],
              sg_hd->sense_buffer[4], sg_hd->sense_buffer[5],
              sg_hd->sense_buffer[6], sg_hd->sense_buffer[7],
              sg_hd->sense_buffer[8], sg_hd->sense_buffer[9],
              sg_hd->sense_buffer[10], sg_hd->sense_buffer[11],
              sg_hd->sense_buffer[12], sg_hd->sense_buffer[13],
              sg_hd->sense_buffer[14], sg_hd->sense_buffer[15]);
      if (status < 0)
         perror("sjy_interface");
      return (CAM_S_DEV_IO_ERROR);
   }
#endif
   return (status - SCSI_OFF - defecit);
}
int notify_camac_data (int branch, int xferlen, int status)
Definition at line 1574 of file jorway73a.c.
References ADD_SENSECODE, SJY_CONTROLLER::errn, IDX, SJY_CONTROLLER::sense_buffer, SENSEKEY, sjy_controller, SJY_NO_Q, SJY_NO_X, and SJY_CONTROLLER::target_status.
Referenced by sjy_read(), and sjy_write().
{                               /* actual transfer length */
   int idx = IDX(branch);
   int sense_key = sjy_controller[idx].sense_buffer[SENSEKEY];
   int add_sense = sjy_controller[idx].sense_buffer[ADD_SENSECODE];
   int target_status = sjy_controller[idx].target_status;
   if (target_status == 0) {    /* Good status -- no errors */
#if GDEBUG
      fprintf(stderr, "target_status=0x%02x\n", target_status);
#endif
      sjy_controller[idx].errn = 0;
      return;
   } else if (target_status != 2) {     /* Improper status */
      sjy_controller[idx].errn = EIO;
      fprintf(stderr, "Invalid SCSI status byte: 0x%02x\n", target_status);
   } else {                     /* Status = 2, check condition */
#if GDEBUG
      fprintf(stderr,
              "target_status=0x%02x,sense_key=0x%02x,add_sense=0x%02x\n",
              target_status, sense_key, add_sense);
#endif
      if (sense_key == 0) {     /* Should only have to "check condition" if !=0 */
      }
      if (add_sense == SJY_NO_Q) {      /* SCSI ok, CAMAC ok, no Q on transfer */
         sjy_controller[idx].errn = ENODEV;
      } else if (add_sense == SJY_NO_X) {       /* SCSI ok, no X on transfer */
         sjy_controller[idx].errn = EFAULT;
      } else {                  /* SCSI problem */
         sjy_controller[idx].errn = EIO;
      }
   }
}
int notify_camac_nondata (int branch, int xferlen, int status)
Definition at line 1537 of file jorway73a.c.
References ADD_SENSECODE, SJY_CONTROLLER::errn, IDX, SJY_CONTROLLER::sense_buffer, sjy_controller, SJY_NO_Q, SJY_NO_X, and SJY_CONTROLLER::target_status.
Referenced by sjy_nondata().
{
   int idx = IDX(branch);
   int addsense = sjy_controller[idx].sense_buffer[ADD_SENSECODE];
   int target_status = sjy_controller[idx].target_status;
   switch (status) {
   case 0:
      sjy_controller[idx].errn = ENODEV;
      break;                    /* X=1,Q=0; see get_qx */
   case 4:
      sjy_controller[idx].errn = 0;
      break;                    /* X=1,Q=1; see get_qx */
   case 2:
      switch (addsense) {
      case SJY_NO_Q:
         sjy_controller[idx].errn = ENODEV;
         break;                 /* X=1,Q=0 */
      case SJY_NO_X:
         sjy_controller[idx].errn = EFAULT;
         break;                 /* X=0 but SCSI ok */
      default:
         sjy_controller[idx].errn = EIO;
         break;                 /* SCSI failed, too. */
      } /* matches switch addsense */ ;
      break;                    /* case 2 */
   default:                    /* Other status means soemthing's screwed up */
      fprintf(stderr, "Invalid SCSI Status byte: 0x%02x\n", target_status);
   }
}
int readFile (FILE * g_rfp, char * filename, char charBuff[], int charBuffsize)
Definition at line 1361 of file jorway73a.c.
References status.
Referenced by sjy_getdev().
{
   int status;
   if (fgets(charBuff, charBuffsize, g_rfp) != NULL) {
      strtok(charBuff, "\n");
      status = 0;
   } else {                     /* error or end of file found and no characters read */
      status = EOF;
   }
   return (status);
}
int sjy_get_qx (int branch)
Definition at line 583 of file jorway73a.c.
References buf, SJY_CONTROLLER::errn, IDX, ieee_last_Q, ieee_last_X, sjy_controller, and sjy_reqSense().
Referenced by cam16i_q(), cam16o_q(), cam24i_q(), cam24o_q(), and camc_q().
{
   unsigned char *buf;
   int *perrno = &sjy_controller[IDX(branch)].errn;
   if (*perrno == 0) {          /* all OK */
      ieee_last_Q = 1;
      ieee_last_X = 1;
   } else if (*perrno == ENODEV) {      /* non data command, no Q */
      ieee_last_Q = 0;
      ieee_last_X = 1;
   } else if (*perrno == EPIPE) {       /* bad word count transfer on pdt */
      ieee_last_Q = 0;
      ieee_last_X = 0;
   } else if (*perrno == EIO) { /* SCSI error */
      ieee_last_Q = 0;
      ieee_last_X = 0;
   } else if (*perrno == EFAULT) {      /* CAMAC error */
      ieee_last_Q = 0;
      ieee_last_X = 0;
   } else {
      buf = sjy_reqSense(sjy_controller[IDX(branch)].fd);
      ieee_last_Q = 1 - (buf[8] & 128) / 128;
      ieee_last_X = 1 - (buf[8] & 64) / 64;
   }
   return (ieee_last_Q);
}
int sjy_getdev (char * dev, int branch)
Definition at line 1280 of file jorway73a.c.
References BUS, CAM_S_DEV_OPEN_FAIL, CAM_S_SUCCESS, devtble, filename, found, i, ID, readFile(), status, and type.
Referenced by cam_init(), and cdchn().
{
   int status = 0;
   char charBuff[120];          /* file line buffer */
   FILE *g_rfp;                 /* /proc/scsi/scsi file descriptor */
   char filename[32] = { "/proc/scsi/scsi" };   /* file describing SCSI devices attached to system */
   int bus;                     /* SCSI bus */
   int id;                      /* SCSI id */
   char vendor[10];             /* SCSI device vendor */
   char type[10];               /* SCSI device type */
   int found = 0;               /* Jorway found flag */
   int i = 0;                   /* devtble index */
   int devtblesz = 9;           /* size of devtble */
   /* open /proc/scsi/scsi */
   g_rfp = fopen(filename, "r");
   if (g_rfp == NULL) {
      fprintf(stderr, "ScanSCSIDevices:  Cannot open %s", filename);
      return (CAM_S_DEV_OPEN_FAIL);
   }
   /* read each line of filename */
   while ((status == 0) && (i < devtblesz)) {
      status = readFile(g_rfp, filename, charBuff, sizeof(charBuff));
      if (status == EOF) {      /* end of file */
         if (!found)
            status = CAM_S_DEV_OPEN_FAIL;
         break;
      } else {                  /* parse the file line */
         /* parse the Host line */
         if (strncmp(charBuff, "Host", 4) == 0) {
            sscanf(&charBuff[10], "%d", &bus);
            sscanf(&charBuff[29], "%d", &id);
         }
         /* parse the Vendor line */
         if (strncmp(&charBuff[2], "Vendor", 6) == 0) {
            sscanf(&charBuff[10], "%s", vendor);
            if (strcmp(vendor, "JORWAY") == 0) {
               if ((id == ID(branch)) && (bus == BUS(branch))) {
                  /* found our device by matching scsi id */
                  strcpy(dev, devtble[i]);
                  found = 1;
                  break;
               }
            } else {            /* SCSI device found, but not a Jorway */
               i++;
            }
         }
         /* parse the Type line */
         if (strncmp(&charBuff[2], "Type", 4) == 0) {
            sscanf(&charBuff[10], "%s", type);
#ifdef DEBUG
            if (strcmp(type, "Unknown") || (strcmp(type, "Processor"))) {
               fprintf(stderr, "Found type %s", type);
            }
#endif
         }
      }                         /* if status == 0 */
   }                            /* while */
   fclose(g_rfp);
   if (found)
      status = CAM_S_SUCCESS;
   return (status);
}
int sjy_getsem ()
Definition at line 1520 of file jorway73a.c.
Referenced by cdchn(), and handle_scsi_cmd().
{
   return (0);
}                               /* get the sjy semaphore */
int sjy_inisem ()
Definition at line 1515 of file jorway73a.c.
Referenced by cdchn().
{
   return (1);
}
unsigned char* sjy_inquiry (int branch)
Definition at line 1001 of file jorway73a.c.
References cmd, handle_scsi_cmd(), i, INQUIRY_CMD, INQUIRY_CMDLEN, INQUIRY_REPLY_LEN, and SCSI_OFF.
{
   static unsigned char Inqbuffer[SCSI_OFF + INQUIRY_REPLY_LEN];
   int i;
   char *cptr;
   unsigned char cmdblk[INQUIRY_CMDLEN] = { INQUIRY_CMD,        /* command */
      0,                        /* lun/reserved */
      0,                        /* page code */
      0,                        /* reserved */
      INQUIRY_REPLY_LEN,        /* allocation length */
      0
   };                           /* reserved/flag/link */
   memcpy(cmd + SCSI_OFF, cmdblk, sizeof(cmdblk));
   /* clear the Inquiry buffer */
   /*memset( Inqbuffer, '\0', sizeof(Inqbuffer) ); */
   handle_scsi_cmd(branch, sizeof(cmdblk), 0, cmd,
                   sizeof(Inqbuffer) - SCSI_OFF, Inqbuffer);
   /* handle_scsi_cmd removes sg_header in the copy from i_buff to o_buff,
    ** so don't add SCSI_OFF offset to Inqbuffer
    */
   /*
      fprintf(stderr,"Inquiry buffer\n");
      fprintf(stderr,"%s\n",Inqbuffer+INQUIRY_VENDOR);
    */
   return (Inqbuffer);
}
int sjy_nondata (int branch, int camCmd)
Definition at line 860 of file jorway73a.c.
References cmd, CMD_SIZE, handle_scsi_cmd(), notify_camac_nondata(), SCSI_OFF, SJY_NONDATA_CMD, and status.
Referenced by camc_q().
{
   static unsigned char scmdblk[6];
   static unsigned char lcmdblk[12];    /* required for commands 0xc0-0xff */
   static unsigned char *cmdblk;
   int cmdsize;
   int status;
   bzero(cmd, CMD_SIZE);
   /* cmdblk = scmdblk; */
   cmdblk = cmd + SCSI_OFF;
   cmdsize = 6;
   cmdblk[0] = SJY_NONDATA_CMD; /* Op code */
   cmdblk[1] = (camCmd >> 24) & 0x1F;   /* lun/function code */
   cmdblk[2] = (camCmd >> 16) & 0xFF;   /* mode/station */
   cmdblk[3] = (camCmd >> 8) & 0x0F;    /* address */
   cmdblk[4] = 0;               /* allocation length */
   cmdblk[5] = 0;               /* control byte, always 0 */
   status = handle_scsi_cmd(branch, cmdsize, 0, cmd, 0, NULL);
   /*     sjy_notify_camac_nondata(branch, 0, status); */
   notify_camac_nondata(branch, 0, status);
   return (status);
}
int sjy_notify_camac_data (int branch, int xferlen, int status)
Definition at line 1111 of file jorway73a.c.
References ADD_SENSECODE, SJY_CONTROLLER::errn, IDX, SJY_CONTROLLER::result, SJY_CONTROLLER::sense_buffer, SENSEKEY, sjy_controller, SJY_NO_Q, and SJY_NO_X.
{                               /* actual transfer length */
   int idx = IDX(branch);
   int sense_key = sjy_controller[idx].sense_buffer[SENSEKEY];
   int add_sense = sjy_controller[idx].sense_buffer[ADD_SENSECODE];
   sjy_controller[idx].errn = 0;
   if (sense_key) {
      if (add_sense == SJY_NO_Q) {
         /* SCSI ok, CAMAC ok, no Q on transfer */
         sjy_controller[idx].errn = ENODEV;
      } else if (add_sense == SJY_NO_X) {
         /* SCSI ok, no X on transfer */
         sjy_controller[idx].errn = EFAULT;
      } else {
         /* SCSI problem */
         sjy_controller[idx].errn = EIO;
      }
   } else {
      if (status == xferlen) {
         /* SCSI ok, CAMAC ok, assuming Q on transfer */
         sjy_controller[idx].errn = 0;
      }
   }
   return sjy_controller[idx].result;
}
int sjy_notify_camac_nondata (int branch, int xferlen, int status)
Definition at line 1152 of file jorway73a.c.
References ADD_SENSECODE, SJY_CONTROLLER::errn, IDX, SJY_CONTROLLER::result, SJY_CONTROLLER::sense_buffer, SENSEKEY, SJY_CHECK_CONDITION, sjy_controller, SJY_GOOD, SJY_NO_Q, and SJY_NO_X.
{                               /* actual transfer length */
   int idx = IDX(branch);
   int sense_key = sjy_controller[idx].sense_buffer[SENSEKEY];
   int add_sense = sjy_controller[idx].sense_buffer[ADD_SENSECODE];
   sjy_controller[idx].errn = 0;
   if ((sjy_controller[idx].result == SJY_GOOD) && !(sense_key)) {
      /* SCSI ok. CAMAC ok, no Q on transfer */
      sjy_controller[idx].errn = ENODEV;
   } else if ((sjy_controller[idx].result == SJY_CHECK_CONDITION)
              || (sense_key)) {
      if (add_sense == SJY_NO_Q) {
         /* SCSI ok, CAMAC ok, no Q on transfer */
         sjy_controller[idx].errn = ENODEV;
      } else if (add_sense == SJY_NO_X) {       /* SCSI ok, no X on transfer */
         sjy_controller[idx].errn = EFAULT;
      } else {                  /* SCSI problem */
         sjy_controller[idx].errn = EIO;
      }
   } else {                     /* SCSI ok, CAMAC ok, assuming Q on transfer */
      sjy_controller[idx].errn = 0;
   }
   return sjy_controller[idx].result;
}
int sjy_putsem ()
Definition at line 1525 of file jorway73a.c.
Referenced by cdchn(), and handle_scsi_cmd().
{
   return (0);
}                               /* release the sjy semaphore */
int sjy_read (int branch, int camCmd, void * dataBuffer, int xferlen)
Definition at line 949 of file jorway73a.c.
References cmd, CMD_SIZE, handle_scsi_cmd(), notify_camac_data(), SCSI_OFF, SJY_LONGXFER_DATA_CMD, SJY_SHORTXFER_DATA_CMD, and status.
Referenced by cam16i(), cam16i_q(), cam16i_r(), cam16i_rq(), cam24i(), cam24i_q(), cam24i_r(), and cam24i_rq().
{
   static unsigned char scmdblk[6];
   static unsigned char lcmdblk[10];
   static unsigned char *cmdblk;
   int cmdsize;
   int status;
   bzero(cmd, CMD_SIZE);        /* clear cmd for case of short transfers */
   if (xferlen < 256) {
      /* cmdblk = scmdblk; */
      cmdblk = cmd + SCSI_OFF;
      cmdblk[0] = SJY_SHORTXFER_DATA_CMD;       /* Op code */
      cmdblk[1] = (camCmd >> 24) & 0x1F;        /* lun/function code */
      cmdblk[2] = (camCmd >> 16) & 0xFF;        /* mode/station */
      cmdblk[3] = (camCmd >> 8) & 0x0F; /* address */
      cmdblk[4] = xferlen;      /* allocation length */
      cmdblk[5] = 0;            /* control byte, always 0 */
   } else {
      /* cmdblk = lcmdblk; */
      cmdblk = cmd + SCSI_OFF;
      cmdblk[0] = SJY_LONGXFER_DATA_CMD;        /* Op code */
      cmdblk[1] = 0;            /* lun/reserved */
      cmdblk[2] = (camCmd >> 24) & 0x1F;        /* reserved/function code */
      cmdblk[3] = (camCmd >> 16) & 0xFF;        /* mode/S/station */
      cmdblk[4] = (camCmd >> 8) & 0x0F; /* address */
      cmdblk[5] = 0;            /* reserved */
      cmdblk[6] = (xferlen >> 16) & 0xFF;       /* transfer length (MSB) */
      cmdblk[7] = (xferlen >> 8) & 0xFF;
      cmdblk[8] = xferlen & 0xFF;       /* transfer length (LSB) */
      cmdblk[9] = 0;            /* control byte, always 0 */
   }
   if (cmdblk[0] == SJY_SHORTXFER_DATA_CMD)
      cmdsize = 6;
   else
      cmdsize = 10;
   /* memcpy( cmd + SCSI_OFF, cmdblk, cmdsize ); */
   status = handle_scsi_cmd(branch, cmdsize, 0, cmd, xferlen, dataBuffer);
   notify_camac_data(branch, xferlen, status);
   return (status);
}
unsigned char* sjy_reqSense (int branch)
Definition at line 1076 of file jorway73a.c.
References cmd, handle_scsi_cmd(), IDX, SCSI_OFF, SENSE_CMD, SENSE_CMDLEN, sjy_controller, and SJY_SENSE_LENGTH.
Referenced by sjy_get_qx().
{
   int idx = IDX(branch);
   static unsigned char sensebuffer[SCSI_OFF + SJY_SENSE_LENGTH];
   unsigned char cmdblk[SENSE_CMDLEN] = { SENSE_CMD,    /* command */
      0,                        /* lun/reserved */
      0,                        /* reserved */
      0,                        /* reserved */
      SJY_SENSE_LENGTH,         /* allocation length */
      0
   };                           /* reserved/flag/link */
   memcpy(cmd + SCSI_OFF, cmdblk, sizeof(cmdblk));
   memset(sensebuffer, '\0', sizeof(sensebuffer));
   handle_scsi_cmd(sjy_controller[idx].fd, sizeof(cmdblk), 0, cmd,
                   sizeof(sensebuffer) - SCSI_OFF, sensebuffer);
   /* handle_scsi_cmd removes sg_header in the copy from i_buff to o_buff,
    ** so don't add SCSI_OFF offset to sensebuffer
    */
   return (sensebuffer);
}
int sjy_tur (int branch)
Definition at line 1039 of file jorway73a.c.
References cmd, handle_scsi_cmd(), i, SCSI_OFF, status, TESTUNITREADY_CMD, and TESTUNITREADY_CMDLEN.
Referenced by camc_chk(), and cdchn().
{
   int i;
   int status;
   /* request READY status */
   static unsigned char cmdblk[TESTUNITREADY_CMDLEN] = {
      TESTUNITREADY_CMD,        /* command */
      0,                        /* lun/reserved */
      0,                        /* reserved */
      0,                        /* reserved */
      0,                        /* reserved */
      0
   };                           /* reserved */
   memcpy(cmd + SCSI_OFF, cmdblk, sizeof(cmdblk));
   /* This must be done twice to get good status from power cycled Jorway */
   for (i = 0; i < 2; i++) {
      status = handle_scsi_cmd(branch, sizeof(cmdblk), 0, cmd, 0, NULL);
   }
   if (status)
      perror("sjy_tur");
   return (status);
}
int sjy_write (int branch, int camCmd, void * dataBuffer, int xferlen)
Definition at line 892 of file jorway73a.c.
References cmd, CMD_SIZE, handle_scsi_cmd(), notify_camac_data(), SCSI_OFF, SJY_LONGXFER_DATA_CMD, SJY_SHORTXFER_DATA_CMD, and status.
Referenced by cam16o_q(), cam16o_r(), cam24o_q(), and cam24o_r().
{
   static unsigned char scmdblk[6];
   static unsigned char lcmdblk[10];
   static unsigned char *cmdblk;
   int cmdsize;
   int status;
   bzero(cmd, CMD_SIZE);
   if (xferlen < 256) {         /* This is also the nondata command block */
      /* cmdblk = scmdblk; */
      cmdblk = cmd + SCSI_OFF;
      cmdblk[0] = SJY_SHORTXFER_DATA_CMD;       /* Op code */
      cmdblk[1] = (camCmd >> 24) & 0x1F;        /* lun/function code */
      cmdblk[2] = (camCmd >> 16) & 0xFF;        /* mode/station */
      cmdblk[3] = (camCmd >> 8) & 0x0F; /* address */
      cmdblk[4] = xferlen;      /* allocation length */
      cmdblk[5] = 0;            /* control byte, always 0 */
   } else {
      /* cmdblk = lcmdblk; */
      cmdblk = cmd + SCSI_OFF;
      cmdblk[0] = SJY_LONGXFER_DATA_CMD;        /* Op code */
      cmdblk[1] = 0;            /* lun/reserved */
      cmdblk[2] = (camCmd >> 24) & 0x1F;        /* reserved/function code */
      cmdblk[3] = (camCmd >> 16) & 0xFF;        /* mode/S/station */
      cmdblk[4] = (camCmd >> 8) & 0x0F; /* address */
      cmdblk[5] = 0;            /* reserved */
      cmdblk[6] = (xferlen >> 16) & 0xFF;       /* transfer length (MSB) */
      cmdblk[7] = (xferlen >> 8) & 0xFF;
      cmdblk[8] = xferlen & 0xFF;       /* transfer length (LSB) */
      cmdblk[9] = 0;            /* control byte, always 0 */
   }
   if (cmdblk[0] == SJY_SHORTXFER_DATA_CMD)
      cmdsize = 6;
   else
      cmdsize = 10;
   /* memcpy( cmd + SCSI_OFF, cmdblk, cmdsize ); */
   /* copy user buffer behind cmdblk */
   if (dataBuffer != NULL)
      memcpy(cmd + SCSI_OFF + cmdsize, dataBuffer, xferlen);
   status = handle_scsi_cmd(branch, cmdsize, xferlen, cmd, 0, NULL);
   /*  sjy_notify_camac_data(branch, xferlen, status); */
   notify_camac_data(branch, xferlen, status);
   return (status);
}
Variable Documentation
unsigned char cmd[CMD_SIZE] [static]
Definition at line 628 of file jorway73a.c.
Referenced by caen170a_get(), caen170a_set(), cam16i(), cam16i_q(), cam16i_r(), cam16i_rq(), cam16o_q(), cam16o_r(), cam24i(), cam24i_q(), cam24i_r(), cam24i_rq(), cam24o_q(), cam24o_r(), camc_q(), cnaf_callback(), decode_line(), ftp_port(), interprete(), lazy_copy(), lazy_log_update(), lazy_main(), lrs4032_get(), lrs4032_set(), main(), show_cnaf_page(), show_hist_config_page(), sjy_inquiry(), sjy_nondata(), sjy_read(), sjy_reqSense(), sjy_tur(), sjy_write(), ss_shell(), and upgrade().
WORD d16dummy
Definition at line 101 of file jorway73a.c.
DWORD d24dummy
Definition at line 102 of file jorway73a.c.
char* devtble[] [static]
Initial value:
 { "/dev/sga",
   "/dev/sgb",
   "/dev/sgc",
   "/dev/sgd",
   "/dev/sge",
   "/dev/sgf",
   "/dev/sgh",
   "/dev/sgg",
   "/dev/sgh"
}
Definition at line 1269 of file jorway73a.c.
Referenced by sjy_getdev().
int ieee_last_Q = 0
Definition at line 99 of file jorway73a.c.
Referenced by sjy_get_qx().
int ieee_last_X = 0
Definition at line 100 of file jorway73a.c.
Referenced by cam16i_q(), cam16o_q(), cam24i_q(), cam24o_q(), and sjy_get_qx().
DWORD jorway_crate_LAM[8] = { 0 }
Definition at line 105 of file jorway73a.c.
Referenced by cam_lam_disable(), and cam_lam_enable().
int jorway_crate_opened[8] = { 0 }
Definition at line 104 of file jorway73a.c.
Referenced by cam_exit(), and cam_init().
int qdummy
Definition at line 98 of file jorway73a.c.
Referenced by cam16o(), cam24o(), and camc().
int xdummy
Definition at line 98 of file jorway73a.c.
Referenced by cam16o(), and cam24o().