AlcapDAQ:Rootana: midas/drivers/kernel/khyt1331/esone.c File Reference
midas/drivers/kernel/khyt1331/esone.c File Reference
#include <stdio.h>
#include "mcstd.h"
#include "esone.h"
Functions
INLINE void came_cn (int *ext, const int b, const int c, const int n, const int a)
INLINE void came_ext (const int ext, int *b, int *c, int *n, int *a)
INLINE void ccinit (void)
INLINE int fccinit (void)
INLINE void cdreg (int *ext, const int b, const int c, const int n, const int a)
INLINE void cssa (const int f, int ext, unsigned short *d, int *q)
INLINE void cfsa (const int f, const int ext, unsigned long *d, int *q)
INLINE void cccc (const int ext)
INLINE void cccz (const int ext)
INLINE void ccci (const int ext, int l)
INLINE void ctci (const int ext, int *l)
INLINE void cccd (const int ext, int l)
INLINE void ctcd (const int ext, int *l)
INLINE void cdlam (int *lam, const int b, const int c, const int n, const int a, const int inta[2])
INLINE void ctgl (const int ext, int *l)
INLINE void cclm (const int lam, int l)
INLINE void cclnk (const int lam, void(*isr)(void))
INLINE void cculk (const int lam)
INLINE void ccrgl (const int lam)
INLINE void cclc (const int lam)
INLINE void ctlm (const int lam, int *l)
INLINE void cfga (int f[], int exta[], int intc[], int qa[], int cb[])
INLINE void csga (int f[], int exta[], int intc[], int qa[], int cb[])
INLINE void cfmad (int f, int extb[], int intc[], int cb[])
INLINE void csmad (int f, int extb[], int intc[], int cb[])
INLINE void cfubc (const int f, int ext, int intc[], int cb[])
INLINE void csubc (const int f, int ext, int intc[], int cb[])
INLINE void cfubr (const int f, int ext, int intc[], int cb[])
INLINE void csubr (const int f, int ext, int intc[], int cb[])
Function Documentation
INLINE void came_cn (int * ext, const int b, const int c, const int n, const int a)
Definition at line 38 of file esone.c.
{
   *ext = (b << 24 | (c << 16) | (n << 8) | a);
}
INLINE void came_ext (const int ext, int * b, int * c, int * n, int * a)
Definition at line 45 of file esone.c.
{
   *b = (ext >> 24) & 0x7;
   *c = (ext >> 16) & 0x7;
   *n = (ext >> 8) & 0x1f;
   *a = (ext >> 0) & 0xf;
}
INLINE void cccc (const int ext)
cccc Control Crate Clear.
Generate Crate Clear function. Execute cam()
Crate Clear.
Parameters:
ext external address
Returns:
void
Definition at line 199 of file esone.c.
References c, cam_crate_clear(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   cam_crate_clear(c);
}
INLINE void cccd (const int ext, int l)
cccd Control Crate D.
Enable or Disable Crate Demand.
Crate D.
Parameters:
ext external address
l action l=0 -> Clear D, l=1 -> Set D
Returns:
void
Definition at line 281 of file esone.c.
References c, cam_interrupt_disable(), cam_interrupt_enable(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   if (l)
      cam_interrupt_enable(c);
   else
      cam_interrupt_disable(c);
}
INLINE void ccci (const int ext, int l)
ccci Control Crate I.
Set or Clear Dataway Inhibit, Execute cam() /clear()
Crate I.
Parameters:
ext external address
l action l=0 -> Clear I, l=1 -> Set I
Returns:
void
Definition at line 238 of file esone.c.
References c, cam_inhibit_clear(), cam_inhibit_set(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   if (l)
      cam_inhibit_set(c);
   else
      cam_inhibit_clear(c);
}
INLINE void cccz (const int ext)
cccz Control Crate Z.
Generate Dataway Initialize. Execute cam()
Crate Z.
Parameters:
ext external address
Returns:
void
Definition at line 218 of file esone.c.
References c, cam_crate_zinit(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   cam_crate_zinit(c);
}
INLINE void ccinit (void)
ccinit CAMAC initialization
CAMAC initialization must be called before any other ESONE subroutine call
CAMAC initialization.
Returns:
void
Definition at line 68 of file esone.c.
References cam_init().
{
   cam_init();
}
INLINE void cclc (const int lam)
cclc Control Clear LAM. Clear the LAM of the staion pointer by the lam address.
Clear LAM.
Parameters:
lam external address
Returns:
void
Definition at line 457 of file esone.c.
References c, camc(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   camc(c, n, 0, 10);
}
INLINE void cclm (const int lam, int l)
cclm Control Crate LAM.
Enable or Disable LAM. Execute F24 for disable, F26 for enable.
dis/enable LAM.
Parameters:
lam external address
l action l=0 -> disable LAM , l=1 -> enable LAM
Returns:
void
Definition at line 370 of file esone.c.
References c, camc(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   if (l)
      camc(c, n, 0, 26);
   else
      camc(c, n, 0, 24);
}
INLINE void cclnk (const int lam, void(*)(void) isr)
cclnk Link LAM to service procedure
Link a specific service routine to a LAM. Since this routine is executed asynchronously, care must be taken on re-entrancy.
Link LAM to service procedure
Parameters:
lam external address
isr name of service procedure
Returns:
void
Definition at line 395 of file esone.c.
References c, cam_interrupt_attach(), cam_lam_clear(), cam_lam_enable(), came_ext(), isr, and n.
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   cam_interrupt_attach(c, n, isr);
   cam_lam_enable(c, n);
   cam_lam_clear(c, n);
}
INLINE void ccrgl (const int lam)
ccrgl Relink LAM
Re-enable LAM in the controller
Re-enable LAM
Parameters:
lam external address
Returns:
void
Definition at line 436 of file esone.c.
References c, cam_interrupt_enable(), cam_lam_clear(), cam_lam_enable(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   cam_lam_enable(c, n);
   cam_lam_clear(c, n);
   cam_interrupt_enable(c);
}
INLINE void cculk (const int lam)
cculk Unlink LAM from service procedure
Performs complementary operation to cclnk.
Detach LAM from service procedure
Parameters:
lam external address
Returns:
void
Definition at line 417 of file esone.c.
References c, cam_interrupt_detach(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   cam_interrupt_detach(c, n);
}
INLINE void cdlam (int * lam, const int b, const int c, const int n, const int a, const int inta[2])
cdlam Control Declare LAM.
Declare LAM, Identical to cdreg.
Declare LAM.
Parameters:
lam external LAM address
b branch number (0..7)
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
inta[2] implementation dependent
Returns:
void
Definition at line 329 of file esone.c.
References cdreg().
{
   /* inta[2] ignored */
   cdreg(lam, b, c, n, a);
}
INLINE void cdreg (int * ext, const int b, const int c, const int n, const int a)
cdreg Control Declaration REGister.
Compose an external address from BCNA for later use. Accessing CAMAC through ext could be faster if the external address is memory mapped to the processor (hardware dependent). Some CAMAC controller do not have this option see {appendix D: Supported hardware}. In this case External Address register.
Parameters:
ext external address
b branch number (0..7)
c crate number (0..)
n station number (0..30)
a sub-address (0..15)
Returns:
void
Definition at line 109 of file esone.c.
References came_cn().
Referenced by begin_of_run(), caen170a_init(), cdlam(), isr(), lrs4032_init(), and main().
{
   came_cn(ext, b, c, n, a);
}
INLINE void cfga (int f[], int exta[], int intc[], int qa[], int cb[])
cfga Control Full (24bit) word General Action.
General external address scan function.
Parameters:
f function code
exta[] external address array
intc[] data array
qa[] Q response array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 500 of file esone.c.
References cfsa(), and i.
{
   int i;
   for (i = 0; i < cb[0]; i++)
      cfsa(f[i], exta[i], (unsigned long *) (&(intc[i])), &(qa[i]));
   cb[1] = cb[0];
}
INLINE void cfmad (int f, int extb[], int intc[], int cb[])
cfmad Control Full (24bit) Address Q scan.
Scan all sub-address while Q=1 from a0..a15 max from address extb[0] and store corresponding data in intc[]. If Q=0 while A<15 or A=15 then cross station boundary is applied (n-> n+1) and sub-address is reset (a=0). Perform action until either cb[0] action are performed or current external address exceeds extb[1].
{ implementation of cb[2] for LAM recognition is not implemented.}
Address scan function.
Parameters:
f function code
extb[] external address array \ extb[0] : first valid external address \ extb[1] : last valid external address
intc[] data array
qa[] Q response array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 559 of file esone.c.
References c, cam24i_q(), came_cn(), came_ext(), count, j, and n.
{
   int j, count;
   int x, q, b, c, n, a;
   unsigned long exts, extc, exte;
   exts = extb[0];
   exte = extb[1];
   count = cb[0];
   j = 0;
   came_ext(exts, &b, &c, &n, &a);
   do {
      cam24i_q(c, n, a, f, (unsigned long *) &intc[j], &x, &q);
      if (q == 0) {
         a = 0;                 /* set subaddress to zero */
         n++;                   /* select next slot */
         j++;
      } else {
         a++;                   /* increment address */
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
      came_cn((int *) &extc, b, c, n, a);
      if (extc > exte)
         count = 0;             /* force exit */
   } while (count);
}
INLINE void cfsa (const int f, const int ext, unsigned long * d, int * q)
cfsa Control Full Operation.
24 bit operation on a given external CAMAC address.
The range of the f is hardware dependent. The number indicated below are for standard ANSI/IEEE Std (758-1979) \ Execute cam24i for f<8, cam24o for f>15, camc for (f>7 or f>23)
24 bit function.
Parameters:
f function code (0..31)
ext external address
d data long word
q Q response
Returns:
void
Definition at line 169 of file esone.c.
References c, cam24i_q(), cam24o_q(), camc_q(), came_ext(), and n.
{
   int b, c, n, a, x;
   if (f < 8) {
      /* read */
      came_ext(ext, &b, &c, &n, &a);
      cam24i_q(c, n, a, f, d, &x, q);
   } else if (f > 15) {
      /* write */
      came_ext(ext, &b, &c, &n, &a);
      cam24o_q(c, n, a, f, *d, &x, q);
   } else if ((f > 7) || (f > 23)) {
      /* command */
      came_ext(ext, &b, &c, &n, &a);
      camc_q(c, n, a, f, q);
   }
}
INLINE void cfubc (const int f, int ext, int intc[], int cb[])
cfubc Control Full (24bit) Block Repeat with Q-stop.
Execute function f on address ext with data intc[] while Q.
Repeat function Q-stop.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 661 of file esone.c.
References cfsa(), and count.
{
   int count, q;
   count = cb[0];
   do {
      cfsa(f, ext, (unsigned long *) intc, &q);
      if (q == 0)
         count = 0;             /* stop on no q */
      else {
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
   } while (count);
}
INLINE void cfubr (const int f, int ext, int intc[], int cb[])
cfubr Repeat Mode Block Transfer (24bit).
Execute function f on address ext with data intc[] if Q. If noQ keep current intc[] data. Repeat cb[0] times.
Repeat function.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 728 of file esone.c.
References cfsa(), and count.
{
   int q, count;
   count = cb[0];
   do {
      do {
         cfsa(f, ext, (unsigned long *) intc, &q);
      } while (q == 0);
      ++cb[1];                  /* increment tally count */
      ++intc;                   /* next data array */
      --count;
   } while (count);
}
INLINE void csga (int f[], int exta[], int intc[], int qa[], int cb[])
csga Control (16bit) word General Action.
General external address scan function.
Parameters:
f function code
exta[] external address array
intc[] data array
qa[] Q response array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 525 of file esone.c.
References cssa(), and i.
{
   int i;
   for (i = 0; i < cb[0]; i++)
      cssa(f[i], exta[i], (unsigned short *) (&(intc[i])), &(qa[i]));
   cb[1] = cb[0];
}
INLINE void csmad (int f, int extb[], int intc[], int cb[])
csmad Control (16bit) Address Q scan.
Scan all sub-address while Q=1 from a0..a15 max from address extb[0] and store corresponding data in intc[]. If Q=0 while A<15 or A=15 then cross station boundary is applied (n-> n+1) and sub-address is reset (a=0). Perform action until either cb[0] action are performed or current external address exceeds extb[1].
{ implementation of cb[2] for LAM recognition is not implemented.}
Address scan function.
Parameters:
f function code
extb[] external address array \ extb[0] : first valid external address \ extb[1] : last valid external address
intc[] data array
qa[] Q response array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 614 of file esone.c.
References c, cam16i_q(), came_cn(), came_ext(), count, j, and n.
{
   int j, count;
   int x, q, b, c, n, a;
   unsigned long exts, extc, exte;
   exts = extb[0];
   exte = extb[1];
   count = cb[0];
   j = 0;
   came_ext(exts, &b, &c, &n, &a);
   do {
      cam16i_q(c, n, a, f, (unsigned short *) &intc[j], &x, &q);
      if (q == 0) {
         a = 0;                 /* set subaddress to zero */
         n++;                   /* select next slot */
         j++;
      } else {
         a++;                   /* increment address */
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
      came_cn((int *) &extc, b, c, n, a);
      if (extc > exte)
         count = 0;             /* force exit */
   } while (count);
}
INLINE void cssa (const int f, int ext, unsigned short * d, int * q)
cssa Control Short Operation.
16 bit operation on a given external CAMAC address.
The range of the f is hardware dependent. The number indicated below are for standard ANSI/IEEE Std (758-1979) \ Execute cam16i for f<8, cam16o for f>15, camc for (f>7 or f>23)
16 bit function.
Parameters:
f function code (0..31)
ext external address
d data word
q Q response
Returns:
void
Definition at line 132 of file esone.c.
References c, cam16i_q(), cam16o_q(), camc_q(), came_ext(), and n.
{
   int b, c, n, a, x;
   if (f < 8) {
      /* read */
      came_ext(ext, &b, &c, &n, &a);
      cam16i_q(c, n, a, f, d, &x, q);
   } else if (f > 15) {
      /* write */
      came_ext(ext, &b, &c, &n, &a);
      cam16o_q(c, n, a, f, *d, &x, q);
   } else if ((f > 7) || (f > 23)) {
      /* command */
      came_ext(ext, &b, &c, &n, &a);
      camc_q(c, n, a, f, q);
   }
}
INLINE void csubc (const int f, int ext, int intc[], int cb[])
csubc Control (16bit) Block Repeat with Q-stop.
Execute function f on address ext with data intc[] while Q.
Repeat function Q-stop.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 694 of file esone.c.
References count, and cssa().
{
   int count, q;
   count = cb[0];
   do {
      cssa(f, ext, (unsigned short *) intc, &q);
      if (q == 0)
         count = 0;             /* stop on no q */
      else {
         ++cb[1];               /* increment tally count */
         ++intc;                /* next data array */
         --count;
      }
   } while (count);
}
INLINE void csubr (const int f, int ext, int intc[], int cb[])
csubr Repeat Mode Block Transfer (16bit).
Execute function f on address ext with data intc[] if Q. If noQ keep current intc[] data. Repeat cb[0] times.
Repeat function.
Parameters:
f function code
ext external address array
intc[] data array
cb[] control block array \ cb[0] : number of function to perform \ cb[1] : returned number of function performed
Returns:
void
Definition at line 761 of file esone.c.
References count, and cssa().
{
   int q, count;
   count = cb[0];
   do {
      do {
         cssa(f, ext, (unsigned short *) intc, &q);
      } while (q == 0);
      ++cb[1];                  /* increment tally count */
      ++intc;                   /* next data array */
      --count;
   } while (count);
}
INLINE void ctcd (const int ext, int * l)
ctcd Control Test Crate D.
Test Crate Demand.
Test Crate D.
Parameters:
ext external address
l D cleared -> l=0, D set -> l=1
Returns:
void
Definition at line 305 of file esone.c.
References c, cam_interrupt_test(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   *l = cam_interrupt_test(c);
}
INLINE void ctci (const int ext, int * l)
ctci Test Crate I.
Test Crate Inhibit, Execute cam()
Crate I.
Parameters:
ext external address
l action l=0 -> Clear I, l=1 -> Set I
Returns:
void
Definition at line 261 of file esone.c.
References c, cam_inhibit_test(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(ext, &b, &c, &n, &a);
   *l = cam_inhibit_test(c);
}
INLINE void ctgl (const int ext, int * l)
ctgl Control Test Demand Present.
Test the LAM register.
Test GL.
Parameters:
lam external LAM register address
l l !=0 if any LAM is set.
Returns:
void
Definition at line 348 of file esone.c.
References c, cam_lam_read(), came_ext(), and n.
{
   int b, c, n, a;
   unsigned long lam;
   came_ext(ext, &b, &c, &n, &a);
   cam_lam_read(c, &lam);
   *l = (lam > 0);
}
INLINE void ctlm (const int lam, int * l)
ctlm Test LAM.
Test the LAM of the station pointed by lam. Performs an F8
Test LAM.
Parameters:
lam external address
l No LAM-> l=0, LAM present-> l=1
Returns:
void
Definition at line 477 of file esone.c.
References c, camc_q(), came_ext(), and n.
{
   int b, c, n, a;
   came_ext(lam, &b, &c, &n, &a);
   camc_q(c, n, a, 8, l);
}
INLINE int fccinit (void)
fccinit CAMAC initialization with return status
fccinit can be called instead of ccinit to determine if the initialization was successful
CAMAC initialization.
Returns:
1 for success, 0 for failure
Definition at line 84 of file esone.c.
References cam_init(), and SUCCESS.
{
   if (cam_init() == SUCCESS)
      return 1;
   return 0;
}