AlcapDAQ:Rootana: midas/examples/basic/largefe.c File Reference
midas/examples/basic/largefe.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "midas.h"
#include "msystem.h"
#include "mcstd.h"
Functions
INT frontend_init ()
INT frontend_exit ()
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
INT frontend_loop ()
INT read_large_event (char *pevent, INT off)
INT poll_event (INT source, INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Variables
char * frontend_name = "largefe"
char * frontend_file_name = __FILE__
BOOL frontend_call_loop = TRUE
INT display_period = 0000
INT max_event_size = 10000
INT max_event_size_frag = 5 * 1024 * 1024
INT event_buffer_size = 10 * 10000
HNDLE hDB
HNDLE hKey
EQUIPMENT equipment []
Function Documentation
INT begin_of_run (INT run_number, char * error)
Definition at line 183 of file largefe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT end_of_run (INT run_number, char * error)
Definition at line 190 of file largefe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_exit (void)
Definition at line 176 of file largefe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_init (void)
Definition at line 169 of file largefe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT frontend_loop (void)
Definition at line 210 of file largefe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT interrupt_configure (INT cmd, INT source, PTYPE adr)
Definition at line 246 of file largefe.c.
References CMD_INTERRUPT_ATTACH, CMD_INTERRUPT_DETACH, CMD_INTERRUPT_DISABLE, CMD_INTERRUPT_ENABLE, and SUCCESS.
{
   switch (cmd) {
   case CMD_INTERRUPT_ENABLE:
      break;
   case CMD_INTERRUPT_DISABLE:
      break;
   case CMD_INTERRUPT_ATTACH:
      break;
   case CMD_INTERRUPT_DETACH:
      break;
   }
   return SUCCESS;
}
INT pause_run (INT run_number, char * error)
Definition at line 197 of file largefe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT poll_event (INT source, INT count, BOOL test)
Definition at line 225 of file largefe.c.
References cam_lam_read(), i, LAM_SOURCE_CRATE, and LAM_SOURCE_STATION.
{
   int i;
   DWORD lam;
   for (i = 0; i < count; i++) {
      cam_lam_read(LAM_SOURCE_CRATE(source), &lam);
      if (lam & LAM_SOURCE_STATION(source))
         if (!test)
            return lam;
   }
   return 0;
}
INT read_large_event (char * pevent, INT off)
Definition at line 263 of file largefe.c.
References bk_close(), bk_create(), bk_init32(), bk_size(), and TID_DWORD.
{
   DWORD *pddata;
   /* init bank structure */
   bk_init32(pevent);
   bk_create(pevent, "BIGG", TID_DWORD, &pddata);
   memset((char *) pddata, 0x0000, 100);
   pddata += 1000000;
   memset((char *) pddata - 100, 0xFFFF, 100);
   bk_close(pevent, pddata);
   return bk_size(pevent);
}
INT resume_run (INT run_number, char * error)
Definition at line 204 of file largefe.c.
References SUCCESS.
{
   return SUCCESS;
}
Variable Documentation
INT display_period = 0000
Definition at line 89 of file largefe.c.
EQUIPMENT equipment[]
Initial value:
 {
      {"large",
       3, 0,
       "SYSTEM",
       EQ_PERIODIC | EQ_FRAGMENTED,
       0,
       "MIDAS",
       TRUE,
       RO_ALWAYS,
       2000,
       0,
       0,
       0,
       "", "", "",
       read_large_event,
       NULL, NULL,
       NULL,
       },
      {""}
   }
Definition at line 118 of file largefe.c.
INT event_buffer_size = 10 * 10000
Definition at line 98 of file largefe.c.
BOOL frontend_call_loop = TRUE
Definition at line 86 of file largefe.c.
char* frontend_file_name = __FILE__
Definition at line 83 of file largefe.c.
char* frontend_name = "largefe"
Definition at line 80 of file largefe.c.
HNDLE hDB
Definition at line 102 of file largefe.c.
HNDLE hKey
Definition at line 102 of file largefe.c.
INT max_event_size = 10000
Definition at line 92 of file largefe.c.
INT max_event_size_frag = 5 * 1024 * 1024
Definition at line 95 of file largefe.c.