AlcapDAQ:Rootana: midas/drivers/device/lrs1454.h File Reference
midas/drivers/device/lrs1454.h File Reference
Functions
INT lrs1454 (INT cmd,...)
Function Documentation
INT lrs1454 (INT cmd, ...)
Definition at line 487 of file lrs1454.c.
References channel, cm_msg, CMD_EXIT, CMD_GET, CMD_GET_ALL, CMD_GET_CURRENT, CMD_GET_CURRENT_ALL, CMD_GET_DEFAULT_NAME, CMD_INIT, CMD_SET, CMD_SET_ALL, CMD_SET_CURRENT_LIMIT, CMD_SET_CURRENT_LIMIT_ALL, CMD_SET_LABEL, FE_ERR_DRIVER, FE_SUCCESS, hKey, lrs1454_exit(), lrs1454_get(), lrs1454_get_all(), lrs1454_get_current(), lrs1454_get_current_all(), lrs1454_init(), lrs1454_set(), lrs1454_set_all(), lrs1454_set_current_limit(), lrs1454_set_current_limit_all(), MERROR, status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   DWORD flags;
   float value, *pvalue;
   void *info, *bd;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      flags = va_arg(argptr, DWORD);
      bd = va_arg(argptr, void *);
      status = lrs1454_init(hKey, info, channel, bd);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = lrs1454_exit(info);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = lrs1454_set(info, channel, value);
      break;
   case CMD_SET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs1454_set_all(info, channel, pvalue);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs1454_get(info, channel, pvalue);
      break;
   case CMD_GET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs1454_get_all(info, channel, pvalue);
      break;
   case CMD_GET_CURRENT:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs1454_get_current(info, channel, pvalue);
      break;
   case CMD_GET_CURRENT_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs1454_get_current_all(info, channel, pvalue);
      break;
   case CMD_SET_CURRENT_LIMIT:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = lrs1454_set_current_limit(info, channel, value);
      break;
   case CMD_SET_CURRENT_LIMIT_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs1454_set_current_limit_all(info, channel, pvalue);
      break;
   case CMD_GET_DEFAULT_NAME:
   case CMD_SET_LABEL:
      break;
   default:
      cm_msg(MERROR, "lrs1454 device driver", "Received unknown command %d", cmd);
      status = FE_ERR_DRIVER;
      break;
   }
   va_end(argptr);
   return status;
}