AlcapDAQ:Rootana: midas/drivers/device/lrs1440.c File Reference
midas/drivers/device/lrs1440.c File Reference
#include <stdio.h>
#include <math.h>
#include <stdarg.h>
#include "midas.h"
Data Structures
struct LRS1440_SETTINGS
struct LRS1440_INFO
Defines
#define LRS1440_SETTINGS_STR "\Address = INT : 1\n\Polarity = INT[16] :\n\[0] -1\n\[1] -1\n\[2] -1\n\[3] -1\n\[4] -1\n\[5] -1\n\[6] -1\n\[7] -1\n\[8] -1\n\[9] -1\n\[10] -1\n\[11] -1\n\[12] -1\n\[13] -1\n\[14] -1\n\"
Functions
void lrs1440_switch (LRS1440_INFO *info)
INT lrs1440_init (HNDLE hkey, void **pinfo, INT channels, INT(*bd)(INT cmd,...))
INT lrs1440_exit (LRS1440_INFO *info)
INT lrs1440_set (LRS1440_INFO *info, INT channel, float value)
INT lrs1440_set_all (LRS1440_INFO *info, INT channels, float value)
INT lrs1440_get (LRS1440_INFO *info, INT channel, float *pvalue)
INT lrs1440_get_all (LRS1440_INFO *info, INT channels, float *array)
INT lrs1440_set_current_limit (LRS1440_INFO *info, float limit)
INT lrs1440 (INT cmd,...)
Define Documentation
#define LRS1440_SETTINGS_STR "\Address = INT : 1\n\Polarity = INT[16] :\n\[0] -1\n\[1] -1\n\[2] -1\n\[3] -1\n\[4] -1\n\[5] -1\n\[6] -1\n\[7] -1\n\[8] -1\n\[9] -1\n\[10] -1\n\[11] -1\n\[12] -1\n\[13] -1\n\[14] -1\n\"
Definition at line 58 of file lrs1440.c.
Referenced by lrs1440_init().
Function Documentation
INT lrs1440 (INT cmd, ...)
Definition at line 309 of file lrs1440.c.
References channel, cm_msg, CMD_EXIT, CMD_GET, CMD_GET_ALL, CMD_GET_CURRENT, CMD_GET_CURRENT_ALL, CMD_INIT, CMD_SET, CMD_SET_ALL, CMD_SET_CURRENT_LIMIT, FE_ERR_DRIVER, FE_SUCCESS, hKey, lrs1440_exit(), lrs1440_get(), lrs1440_get_all(), lrs1440_init(), lrs1440_set(), lrs1440_set_all(), lrs1440_set_current_limit(), MERROR, status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   float value, *pvalue;
   void *info, *bd;
   DWORD flags;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      flags = va_arg(argptr, DWORD);
      bd = va_arg(argptr, void *);
      status = lrs1440_init(hKey, info, channel, bd);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = lrs1440_exit(info);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = lrs1440_set(info, channel, value);
      break;
   case CMD_SET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = lrs1440_set_all(info, channel, value);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs1440_get(info, channel, pvalue);
      break;
   case CMD_GET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs1440_get_all(info, channel, pvalue);
      break;
      /* current measurements not supported in LRS1440 */
   case CMD_GET_CURRENT:
      break;
   case CMD_GET_CURRENT_ALL:
      break;
   case CMD_SET_CURRENT_LIMIT:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      if (channel == 0)         /* one one limit for all channels */
         status = lrs1440_set_current_limit(info, value);
      else
         status = FE_SUCCESS;
      break;
   default:
      cm_msg(MERROR, "lrs1440 device driver", "Received unknown command %d", cmd);
      status = FE_ERR_DRIVER;
      break;
   }
   va_end(argptr);
   return status;
}
INT lrs1440_exit (LRS1440_INFO * info)
Definition at line 196 of file lrs1440.c.
References LRS1440_INFO::bd, LRS1440_INFO::bd_info, CMD_EXIT, and FE_SUCCESS.
Referenced by lrs1440().
{
   info->bd(CMD_EXIT, info->bd_info);
   free(info);
   return FE_SUCCESS;
}
INT lrs1440_get (LRS1440_INFO * info, INT channel, float * pvalue)
Definition at line 242 of file lrs1440.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, lrs1440_switch(), and value.
Referenced by lrs1440().
{
   int value;
   char str[256];
   lrs1440_switch(info);
   sprintf(str, "R V C%02d\r", channel);
   BD_PUTS(str);
   BD_GETS(str, sizeof(str), "Act ", 1000);
   BD_GETS(str, sizeof(str), "\r\n\r\n", 1000);
   sscanf(str + 1, "%d", &value);
   *pvalue = (float) value;
   return FE_SUCCESS;
}
INT lrs1440_get_all (LRS1440_INFO * info, INT channels, float * array)
Definition at line 262 of file lrs1440.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, i, j, lrs1440_switch(), and value.
Referenced by lrs1440().
{
   int value, i, j;
   char str[256];
   lrs1440_switch(info);
   sprintf(str, "R V F C0 DO%d\r", channels);
   BD_PUTS(str);
   for (i = 0; i <= (channels - 1) / 8; i++) {
      BD_GETS(str, sizeof(str), "Act ", 5000);
      BD_GETS(str, sizeof(str), "\r\n", 2000);
      for (j = 0; j < 8 && i * 8 + j < channels; j++) {
         sscanf(str + 1 + j * 6, "%d", &value);
         array[i * 8 + j] = (float) value;
      }
   }
   BD_GETS(str, sizeof(str), "\r\n", 2000);
   return FE_SUCCESS;
}
INT lrs1440_init (HNDLE hkey, void ** pinfo, INT channels, INT(*)(INT cmd,...) bd)
Definition at line 112 of file lrs1440.c.
References LRS1440_SETTINGS::address, LRS1440_INFO::bd, BD_GETS, LRS1440_INFO::bd_info, BD_PUTS, cm_get_experiment_database(), cm_msg, CMD_DEBUG, CMD_INIT, db_create_record(), db_find_key(), db_get_record(), DB_SUCCESS, FALSE, FE_ERR_HW, FE_ERR_ODB, FE_SUCCESS, hDB, LRS1440_SETTINGS_STR, MERROR, LRS1440_INFO::num_channels, LRS1440_INFO::settings, size, status, and SUCCESS.
Referenced by lrs1440().
{
   int status, size;
   char str[256];
   HNDLE hDB, hkeydd;
   LRS1440_INFO *info;
   /* allocate info structure */
   info = calloc(1, sizeof(LRS1440_INFO));
   *pinfo = info;
   cm_get_experiment_database(&hDB, NULL);
   /* create LRS1440 settings record */
   status = db_create_record(hDB, hkey, "DD", LRS1440_SETTINGS_STR);
   if (status != DB_SUCCESS)
      return FE_ERR_ODB;
   db_find_key(hDB, hkey, "DD", &hkeydd);
   size = sizeof(info->settings);
   db_get_record(hDB, hkeydd, &info->settings, &size, 0);
   info->num_channels = channels;
   info->bd = bd;
   /* initialize bus driver */
   if (!bd)
      return FE_ERR_ODB;
   status = bd(CMD_INIT, hkey, &info->bd_info);
   if (status != SUCCESS)
      return status;
   bd(CMD_DEBUG, FALSE);
   /* check if module is living  */
   BD_PUTS("M16\r\n");
   status = BD_GETS(str, sizeof(str), "M16\r\n", 2000);
   if (!status) {
      cm_msg(MERROR, "lrs1440_init",
             "LRS1440 adr %d doesn't respond. Check power and RS232 connection.",
             info->settings.address);
      return FE_ERR_HW;
   }
   sprintf(str, "M%02d\r\n", info->settings.address);
   BD_PUTS(str);
   status = BD_GETS(str, sizeof(str), "responding\r\n", 3000);
   if (!status) {
      cm_msg(MERROR, "lrs1440_init",
             "LRS1440 adr %d doesn't respond. Check power and RS232 connection.",
             info->settings.address);
      return FE_ERR_HW;
   }
   /* check if HV enabled */
   BD_PUTS("ST\r");
   BD_GETS(str, sizeof(str), "abled", 3000);
   if (str[strlen(str) - 6] == 's') {
      /* read rest of status */
      BD_GETS(str, sizeof(str), "", 0);
      cm_msg(MERROR, "lrs1440_init",
             "LeCroy1440 adr %d: HV disabled by front panel button",
             info->settings.address);
//    return FE_ERR_HW;
   }
   /* read rest of status */
   BD_GETS(str, sizeof(str), "", 0);
   /* turn on HV main switch */
   BD_PUTS("ON\r");
   BD_GETS(str, sizeof(str), "Turn on\r\n", 5000);
   BD_PUTS("M16\r\n");
   return FE_SUCCESS;
}
INT lrs1440_set (LRS1440_INFO * info, INT channel, float value)
Definition at line 207 of file lrs1440.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, lrs1440_switch(), LRS1440_SETTINGS::polarity, and LRS1440_INFO::settings.
Referenced by lrs1440().
{
   char str[80];
   lrs1440_switch(info);
   sprintf(str, "W%04.0f C%02d\r", info->settings.polarity[channel / 16] * value,
           channel);
   BD_PUTS(str);
   BD_GETS(str, sizeof(str), "\r\n\r\n", 1000);
   return FE_SUCCESS;
}
INT lrs1440_set_all (LRS1440_INFO * info, INT channels, float value)
Definition at line 224 of file lrs1440.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, i, lrs1440_switch(), LRS1440_SETTINGS::polarity, and LRS1440_INFO::settings.
Referenced by lrs1440().
{
   char str[80];
   INT i;
   lrs1440_switch(info);
   for (i = 0; i < (channels - 1) / 16 + 1; i++) {
      sprintf(str, "W%04.0f C%d DO16\r", info->settings.polarity[i / 16] * value, i * 16);
      BD_PUTS(str);
      BD_GETS(str, sizeof(str), "\r\n\r\n", 3000);
   }
   return FE_SUCCESS;
}
INT lrs1440_set_current_limit (LRS1440_INFO * info, float limit)
Definition at line 287 of file lrs1440.c.
References BD_GETS, BD_PUTS, FE_SUCCESS, and lrs1440_switch().
Referenced by lrs1440().
{
   char str[256];
   lrs1440_switch(info);
   if (limit > 255)
      limit = 255.f;
   sprintf(str, "LI %1.0f\r", limit);
   BD_PUTS(str);
   BD_GETS(str, sizeof(str), "\r\n\r\n", 1000);
   sprintf(str, "LI %1.0f\r", -limit);
   BD_PUTS(str);
   BD_GETS(str, sizeof(str), "\r\n\r\n", 1000);
   return FE_SUCCESS;
}
void lrs1440_switch (LRS1440_INFO * info)
Definition at line 87 of file lrs1440.c.
References LRS1440_SETTINGS::address, BD_GETS, BD_PUTS, cm_msg, MERROR, LRS1440_INFO::settings, and status.
Referenced by lrs1440_get(), lrs1440_get_all(), lrs1440_set(), lrs1440_set_all(), and lrs1440_set_current_limit().
{
   static INT last_address = -1;
   char str[80];
   INT status;
   if (info->settings.address != last_address) {
      BD_PUTS("M16\r\n");
      BD_GETS(str, sizeof(str), "M16\r\n", 1000);
      sprintf(str, "M%02d\r\n", info->settings.address);
      BD_PUTS(str);
      status = BD_GETS(str, sizeof(str), "responding\r\n", 2000);
      if (!status) {
         cm_msg(MERROR, "lrs1440_init",
                "LRS1440 adr %d doesn't respond. Check power and RS232 connection.",
                info->settings.address);
         return;
      }
      last_address = info->settings.address;
   }
}