AlcapDAQ:Rootana: midas/drivers/device/lrs1445a.h File Reference
midas/drivers/device/lrs1445a.h File Reference
Functions
INT lrs1445a (INT cmd,...)
Function Documentation
INT lrs1445a (INT cmd, ...)
Definition at line 301 of file lrs1445a.c.
References channel, cm_msg, CMD_EXIT, CMD_GET, CMD_GET_ALL, CMD_GET_CURRENT, CMD_GET_CURRENT_ALL, CMD_GET_DEFAULT_NAME, CMD_INIT, CMD_SET, CMD_SET_ALL, CMD_SET_CURRENT_LIMIT, CMD_SET_CURRENT_LIMIT_ALL, CMD_SET_LABEL, FE_ERR_DRIVER, FE_SUCCESS, hKey, lrs1445a_exit(), lrs1445a_get(), lrs1445a_get_all(), lrs1445a_init(), lrs1445a_set(), lrs1445a_set_all(), lrs1445a_set_current_limit(), MERROR, status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   float value, *pvalue;
   void *info, *bd;
   DWORD flags;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      flags = va_arg(argptr, DWORD);
      bd = va_arg(argptr, void *);
      status = lrs1445a_init(hKey, info, channel, bd);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = lrs1445a_exit(info);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = lrs1445a_set(info, channel, value);
      break;
   case CMD_SET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs1445a_set_all(info, channel, pvalue);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs1445a_get(info, channel, pvalue);
      break;
   case CMD_GET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = lrs1445a_get_all(info, channel, pvalue);
      break;
      /* current measurements not supported in LRS1445A */
   case CMD_GET_CURRENT:
      break;
   case CMD_GET_CURRENT_ALL:
      break;
   case CMD_SET_CURRENT_LIMIT:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      if (channel == 0)         /* one one limit for all channels */
         status = lrs1445a_set_current_limit(info, value);
      else
         status = FE_SUCCESS;
      break;
   case CMD_SET_CURRENT_LIMIT_ALL:
   case CMD_GET_DEFAULT_NAME:
   case CMD_SET_LABEL:
      break;
   default:
      cm_msg(MERROR, "lrs1445a device driver", "Received unknown command %d", cmd);
      status = FE_ERR_DRIVER;
      break;
   }
   va_end(argptr);
   return status;
}