AlcapDAQ:Rootana: midas/drivers/divers/lrs1151.c File Reference
midas/drivers/divers/lrs1151.c File Reference
Defines
#define A32D24_1151 0xf0000000
#define INLINE
#define EXTERNAL extern
#define LRS1151_READ(_vmebase, _d, _r)
#define LRS115_CLEAR(_vmebase)
Typedefs
typedef unsigned short int WORD
typedef unsigned long int DWORD
Functions
INLINE void lrs1151_read (DWORD vmeBase, DWORD **d, int r)
INLINE void lrs1151_clear (DWORD vmeBase)
void lrs1151 (void)
void rd1151 (DWORD vmeBase)
void clr1151 (DWORD vmeBase)
Define Documentation
#define A32D24_1151 0xf0000000
Definition at line 45 of file lrs1151.c.
Referenced by lrs1151_clear(), and lrs1151_read().
#define EXTERNAL extern
Definition at line 56 of file lrs1151.c.
#define INLINE
Definition at line 53 of file lrs1151.c.
#define LRS1151_READ (_vmebase, _d, _r)
Value:
{\
  {\
     volatile DWORD _ll, *_local, __r;\
        _ll = _vmebase;\
        _local = (DWORD *) (((_ll << 8) | 0x80) | A32D24_1151);\
        __r =_r;\
        if (__r > 16) __r = 16;\
        while (__r > 0) {\
                   *_d++ = *_local++;\
                   __r--;}\
        }\
  }
Definition at line 72 of file lrs1151.c.
#define LRS115_CLEAR (_vmebase)
Value:
{\
  {\
     volatile DWORD _ll, _dummy, *_local, __r=16;\
        _ll = _vmebase;\
        _local =(DWORD *)( ((_ll << 8) | 0x40) | A32D24_1151);\
        while (__r > 0) {\
                   _dummy = *_local;\
                   _local++;\
                   __r--;}\
        }\
  }
Definition at line 85 of file lrs1151.c.
Typedef Documentation
typedef unsigned long int DWORD
Definition at line 66 of file lrs1151.c.
typedef unsigned short int WORD
Definition at line 61 of file lrs1151.c.
Function Documentation
void clr1151 (DWORD vmeBase)
Definition at line 145 of file lrs1151.c.
References lrs1151_clear().
{
   lrs1151_clear(vmeBase);
}
void lrs1151 (void)
Definition at line 123 of file lrs1151.c.
{
   printf("\n---> LeCroy 1151 16ch. NIM/ECL scalers <---\n");
   printf("Macro  : LRS1151_READ (DWORD base, DWORD *data, int repeat);\n");
   printf("Macro  : LRS1151_CLEAR (DWORD base);\n");
   printf("Inline : lrs1151_read  (DWORD base, DWORD *data, int repeat);\n");
   printf("Inline : lrs1151_clear (DWORD base);\n");
   printf("Test   : rd1151   (0x7a00)    <--- read    VME scaler\n");
   printf("Test   : clr1151  (0x7a00)    <--- clear   VME scaler\n");
}
INLINE void lrs1151_clear (DWORD vmeBase)
Definition at line 113 of file lrs1151.c.
References A32D24_1151.
Referenced by clr1151().
{
   volatile DWORD *local, dummy, r;
   local = (DWORD *) (((vmeBase << 8) | 0x40) | A32D24_1151);
   for (r = 0; r < 16; r++) {
      dummy = *local++;
   }
}
INLINE void lrs1151_read (DWORD vmeBase, DWORD ** d, int r)
Definition at line 98 of file lrs1151.c.
References A32D24_1151.
Referenced by rd1151().
{
   volatile DWORD *local;
   if (r > 16)
      r = 16;
   local = (DWORD *) (((vmeBase << 8) | 0x80) | A32D24_1151);
   while (r > 0) {
      *((*d)++) = *((DWORD *) local);
      local++;
      r--;
   }
}
void rd1151 (DWORD vmeBase)
Definition at line 134 of file lrs1151.c.
References i, and lrs1151_read().
{
   DWORD i, dd[16], *pdd;
   for (i = 0; i < 16; i++)
      dd[i] = 0;
   pdd = &dd[0];
   lrs1151_read(vmeBase, &pdd, 16);
   for (i = 0; i < 16; i++)
      printf("%i-> %8.8x\n", i, dd[i]);
}