AlcapDAQ:Rootana: analyzer/src/data_quality/MDQ_IslandCounter.cpp File Reference
analyzer/src/data_quality/MDQ_IslandCounter.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <map>
#include <utility>
#include <sstream>
#include <cmath>
#include "midas.h"
#include <TH1.h>
#include <TDirectory.h>
#include "TGlobalData.h"
#include "TSetupData.h"
#include "TPulseIsland.h"
Functions
INT MDQ_IslandCounter_init (void)
INT MDQ_IslandCounter (EVENT_HEADER *, void *)
INT MDQ_IslandCounter_eor (INT)
Variables
HNDLE hDB
TGlobalData * gData
TSetupData * gSetup
TH1F * hDQ_TDCCheck_muSc
map< std::string, TH1F * > DQ_IslandCounter_histograms_map
map< std::string, TH1F * > DQ_IslandCounter_histograms_normalised_map
ANA_MODULE MDQ_IslandCounter_module
Function Documentation
INT MDQ_IslandCounter (EVENT_HEADER * pheader, void * pevent)
This method fills the histograms
Definition at line 140 of file MDQ_IslandCounter.cpp.
References DQ_IslandCounter_histograms_map, DQ_IslandCounter_histograms_normalised_map, TGlobalData::fPulseIslandToChannelMap, TSetupData::GetDetectorName(), EVENT_HEADER::serial_number, string, and SUCCESS.
{
        // Get the event number
        int midas_event_number = pheader->serial_number;
        // Some typedefs
        typedef map<string, vector<TPulseIsland*> > TStringPulseIslandMap;
        typedef pair<string, vector<TPulseIsland*> > TStringPulseIslandPair;
        typedef map<string, vector<TPulseIsland*> >::iterator map_iterator;
        // Fetch a reference to the gData structure that stores a map
        // of (bank_name, vector<TPulseIsland*>) pairs
        TStringPulseIslandMap& pulse_islands_map =
                gData->fPulseIslandToChannelMap;
        // Loop over the map and get each bankname, vector pair
        for (map_iterator mapIter = pulse_islands_map.begin(); mapIter != pulse_islands_map.end(); ++mapIter)
        {
          std::string bankname = mapIter->first;
          std::string detname = gSetup->GetDetectorName(bankname);
          std::vector<TPulseIsland*> thePulses = mapIter->second;
          // Make sure the histograms exist and then fill them
          if (DQ_IslandCounter_histograms_map.find(bankname) != DQ_IslandCounter_histograms_map.end()) {
            int n_pulse_islands = thePulses.size();
            DQ_IslandCounter_histograms_map[bankname]->Fill(n_pulse_islands);
            DQ_IslandCounter_histograms_normalised_map[bankname]->Fill(n_pulse_islands);
          }
        }
        return SUCCESS;
}
INT MDQ_IslandCounter_eor (INT run_number)
This method does any last minute things to the histograms at the end of the run
Definition at line 110 of file MDQ_IslandCounter.cpp.
References DQ_IslandCounter_histograms_normalised_map, TGlobalData::fPulseIslandToChannelMap, TSetupData::GetDetectorName(), hDQ_TDCCheck_muSc, string, and SUCCESS.
{
  // Some typedefs
  typedef map<string, vector<TPulseIsland*> > TStringPulseIslandMap;
  typedef pair<string, vector<TPulseIsland*> > TStringPulseIslandPair;
  typedef map<string, vector<TPulseIsland*> >::iterator map_iterator;
  // Fetch a reference to the gData structure that stores a map
  // of (bank_name, vector<TPulseIsland*>) pairs
  TStringPulseIslandMap& pulse_islands_map =
    gData->fPulseIslandToChannelMap;
  // Loop over the map and get each bankname, vector pair
  for (map_iterator mapIter = pulse_islands_map.begin(); mapIter != pulse_islands_map.end(); ++mapIter) {
    std::string bankname = mapIter->first;
    std::string detname = gSetup->GetDetectorName(bankname);
    // Make sure the histograms exist and then fill them
    if (DQ_IslandCounter_histograms_normalised_map.find(bankname) != DQ_IslandCounter_histograms_normalised_map.end()) {
      DQ_IslandCounter_histograms_normalised_map[bankname]->Scale(1./hDQ_TDCCheck_muSc->GetEntries());
    }
  }
  return SUCCESS;
}
INT MDQ_IslandCounter_init ()
This method initializes histograms.
Definition at line 67 of file MDQ_IslandCounter.cpp.
References DQ_IslandCounter_histograms_map, DQ_IslandCounter_histograms_normalised_map, TSetupData::fBankToDetectorMap, TSetupData::GetDetectorName(), string, and SUCCESS.
{
    // See if the DataQuality_LowLevel/ directory already exists
  if (!gDirectory->Cd("DataQuality_LowLevel")) {
    std::string dir_name("DataQuality_LowLevel/");
    gDirectory->mkdir(dir_name.c_str());
    gDirectory->Cd(dir_name.c_str());
  }
  // Create a histogram for each detector
  std::map<std::string, std::string> bank_to_detector_map = gSetup->fBankToDetectorMap;
  for(std::map<std::string, std::string>::iterator mapIter = bank_to_detector_map.begin();
      mapIter != bank_to_detector_map.end(); mapIter++) {
    std::string bankname = mapIter->first;
    std::string detname = gSetup->GetDetectorName(bankname);
    // hDQ_IslandCounter_[DetName]_[BankName]
    std::string histname = "hDQ_IslandCounter_" + detname + "_" + bankname;
    std::string histtitle = "Distribution of the number of islands per event in " + detname;
    TH1F* hDQ_Histogram = new TH1F(histname.c_str(), histtitle.c_str(), 3500, 0, 3500);
    hDQ_Histogram->GetXaxis()->SetTitle("Number of TPulseIslands");
    hDQ_Histogram->GetYaxis()->SetTitle("Number of Events");
    DQ_IslandCounter_histograms_map[bankname] = hDQ_Histogram;
    // The normalised histogram
    histname += "_normalised";
    histtitle += " (normalised)";
    TH1F* hDQ_Histogram_Normalised = new TH1F(histname.c_str(), histtitle.c_str(), 3500,0,3500);
    hDQ_Histogram_Normalised->GetXaxis()->SetTitle("Number of TPulseIslands");
    std::string yaxislabel = hDQ_Histogram->GetYaxis()->GetTitle();
    yaxislabel += " per TDC muSc Hit";
    hDQ_Histogram_Normalised->GetYaxis()->SetTitle(yaxislabel.c_str());
    DQ_IslandCounter_histograms_normalised_map[bankname] = hDQ_Histogram_Normalised;
  }
  gDirectory->Cd("/MidasHists/");
  return SUCCESS;
}
Variable Documentation
map<std::string, TH1F*> DQ_IslandCounter_histograms_map
Definition at line 48 of file MDQ_IslandCounter.cpp.
Referenced by MDQ_IslandCounter(), and MDQ_IslandCounter_init().
map<std::string, TH1F*> DQ_IslandCounter_histograms_normalised_map
Definition at line 49 of file MDQ_IslandCounter.cpp.
Referenced by MDQ_IslandCounter(), MDQ_IslandCounter_eor(), and MDQ_IslandCounter_init().
TGlobalData* gData
Definition at line 54 of file analyzer.cpp.
TSetupData* gSetup
Definition at line 55 of file analyzer.cpp.
HNDLE hDB
Definition at line 11 of file mucap_compress.cpp.
TH1F* hDQ_TDCCheck_muSc
Definition at line 64 of file MDQ_TDCCheck.cpp.
ANA_MODULE MDQ_IslandCounter_module
Initial value:
{
        "MDQ_IslandCounter",
        "Andrew Edmonds",
        MDQ_IslandCounter,
        NULL,
        MDQ_IslandCounter_eor,
        MDQ_IslandCounter_init,
        NULL,
        NULL,
        0,
        NULL,
}
Definition at line 51 of file MDQ_IslandCounter.cpp.