AlcapDAQ:Rootana: midas/drivers/device/epics_ca.c File Reference
midas/drivers/device/epics_ca.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "cadef.h"
#include "midas.h"
Data Structures
struct CA_INFO
Defines
#define CHN_NAME_LENGTH 32
Functions
void epics_ca_callback (struct event_handler_args args)
INT epics_ca_init (HNDLE hKey, void **pinfo, INT channels)
INT epics_ca_exit (CA_INFO *info)
INT epics_ca_set (CA_INFO *info, INT channel, float value)
INT epics_ca_set_all (CA_INFO *info, INT channels, float value)
INT epics_ca_set_label (CA_INFO *info, INT channels, char *label)
INT epics_ca_get (CA_INFO *info, INT channel, float *pvalue)
INT epics_ca_get_all (CA_INFO *info, INT channels, float *pvalue)
INT epics_ca (INT cmd,...)
Define Documentation
#define CHN_NAME_LENGTH 32
Definition at line 69 of file epics_ca.c.
Referenced by epics_ca_connection_handler(), epics_ca_event_handler(), epics_ca_exit(), epics_ca_get(), epics_ca_get_default_name(), epics_ca_get_demand(), epics_ca_init(), epics_ca_set(), and epics_ca_set_label().
Function Documentation
INT epics_ca (INT cmd, ...)
Definition at line 264 of file epics_ca.c.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   DWORD flags;
   float value, *pvalue;
   CA_INFO *info;
   char *label;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   if (cmd == CMD_INIT) {
      void *pinfo;
      hKey = va_arg(argptr, HNDLE);
      pinfo = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      flags = va_arg(argptr, DWORD);
      status = epics_ca_init(hKey, pinfo, channel);
      info = *(CA_INFO **) pinfo;
      info->flags = flags;
   } else {
      info = va_arg(argptr, void *);
      /* only execute command if enabled */
      if (cmd & info->cmd_disabled)
         status = FE_ERR_DISABLED;
      else
         switch (cmd) {
         case CMD_INIT:
            break;
         case CMD_EXIT:
            status = epics_ca_exit(info);
            break;
         case CMD_SET:
            channel = va_arg(argptr, INT);
            value = (float) va_arg(argptr, double);
            status = epics_ca_set(info, channel, value);
            break;
         case CMD_SET_ALL:
            channel = va_arg(argptr, INT);
            value = (float) va_arg(argptr, double);
            status = epics_ca_set_all(info, channel, value);
            break;
         case CMD_SET_LABEL:
            channel = va_arg(argptr, INT);
            label = va_arg(argptr, char *);
            status = epics_ca_set_label(info, channel, label);
            break;
         case CMD_GET:
            channel = va_arg(argptr, INT);
            pvalue = va_arg(argptr, float *);
            status = epics_ca_get(info, channel, pvalue);
            break;
         case CMD_GET_ALL:
            channel = va_arg(argptr, INT);
            pvalue = va_arg(argptr, float *);
            status = epics_ca_get_all(info, channel, pvalue);
            break;
         default:
            break;
         }
   }
   va_end(argptr);
   return status;
}
void epics_ca_callback (struct event_handler_args args)
Definition at line 80 of file epics_ca.c.
References CA_INFO::array, event_handler_args::chid, event_handler_args::dbr, for(), i, CA_INFO::num_channels, CA_INFO::pv_handles, and event_handler_args::usr.
Referenced by epics_ca_init().
{
   CA_INFO *info;
   int i;
   info = (CA_INFO *) args.usr;
   /* search channel index */
   for (i = 0; i < info->num_channels; i++)
      if (info->pv_handles[i] == args.chid)
         break;
   if (i < info->num_channels)
      info->array[i] = *((float *) args.dbr);
}
INT epics_ca_exit (CA_INFO * info)
Definition at line 176 of file epics_ca.c.
Referenced by epics_ca().
{
   int i;
   ca_task_exit();
   if (info->pv_handles) {
      for (i = 0; i < info->num_channels; i++)
         info->pv_handles[i] = calloc(1, sizeof(struct channel_in_use));
      free(info->pv_handles);
   }
   if (info->array)
      free(info->array);
   if (info->channel_names)
      free(info->channel_names);
   free(info);
   return FE_SUCCESS;
}
INT epics_ca_get (CA_INFO * info, INT channel, float * pvalue)
Definition at line 242 of file epics_ca.c.
Referenced by epics_ca(), and epics_ca_get_all().
{
   ca_pend_event(0.0001);
   *pvalue = info->array[channel];
   return FE_SUCCESS;
}
INT epics_ca_get_all (CA_INFO * info, INT channels, float * pvalue)
Definition at line 252 of file epics_ca.c.
Referenced by epics_ca().
{
   int i;
   for (i = 0; i < MIN(info->num_channels, channels); i++)
      epics_ca_get(info, i, pvalue + i);
   return FE_SUCCESS;
}
INT epics_ca_init (HNDLE hKey, void ** pinfo, INT channels)
Definition at line 98 of file epics_ca.c.
Referenced by epics_ca().
{
   int status, i;
   HNDLE hDB;
   CA_INFO *info;
   /* allocate info structure */
   info = calloc(1, sizeof(CA_INFO));
   *pinfo = info;
   cm_get_experiment_database(&hDB, NULL);
   /* get channel names */
   info->channel_names = calloc(channels, CHN_NAME_LENGTH);
   for (i = 0; i < channels; i++)
      sprintf(info->channel_names + CHN_NAME_LENGTH * i, "Channel%d", i);
   db_merge_data(hDB, hKey, "Channel name",
                 info->channel_names, CHN_NAME_LENGTH * channels, channels, TID_STRING);
   /* initialize driver */
   status = ca_task_initialize();
   if (!(status & CA_M_SUCCESS)) {
      cm_msg(MERROR, "epics_ca_init", "unable to initialize");
      return FE_ERR_HW;
   }
   /* allocate arrays */
   info->array = calloc(channels, sizeof(float));
   info->pv_handles = calloc(channels, sizeof(void *));
   for (i = 0; i < channels; i++)
      info->pv_handles[i] = calloc(1, sizeof(struct channel_in_use));
   /* search channels */
   info->num_channels = channels;
   for (i = 0; i < channels; i++) {
      status = ca_search(info->channel_names + CHN_NAME_LENGTH * i, &info->pv_handles[i]);
      if (!(status & CA_M_SUCCESS))
         cm_msg(MERROR, "epics_ca_init", "cannot find tag %s",
                info->channel_names + CHN_NAME_LENGTH * i);
   }
   if (ca_pend_io(5.0) == ECA_TIMEOUT) {
      for (i = 0; i < channels; i++)
         if (info->pv_handles[i]->state != 2)
            cm_msg(MERROR, "epics_ca_init", "cannot connect to %s",
                   info->channel_names + CHN_NAME_LENGTH * i);
   }
   /* add change notifications */
   for (i = 0; i < channels; i++) {
      /* ignore unconnected channels */
      if (info->pv_handles[i]->state != 2)
         continue;
      status = ca_add_event(DBR_FLOAT, info->pv_handles[i], epics_ca_callback,
                            info, NULL);
      if (!(status & CA_M_SUCCESS))
         cm_msg(MERROR, "epics_ca_init", "cannot add event to channel %s",
                info->channel_names + CHN_NAME_LENGTH * i);
   }
   if (ca_pend_io(5.0) == ECA_TIMEOUT) {
      for (i = 0; i < channels; i++)
         if (info->pv_handles[i]->state != 2)
            cm_msg(MERROR, "epics_ca_init", "cannot add event to channel %s",
                   info->channel_names + CHN_NAME_LENGTH * i);
   }
   /* enable all commands by default */
   info->cmd_disabled = 0;
   return FE_SUCCESS;
}
INT epics_ca_set (CA_INFO * info, INT channel, float value)
Definition at line 200 of file epics_ca.c.
References ca_put, DBR_FLOAT, FE_SUCCESS, and CA_INFO::pv_handles.
Referenced by epics_ca(), epics_ca_event_handler(), epics_ca_get(), epics_ca_set(), and epics_ca_set_all().
{
   ca_put(DBR_FLOAT, info->pv_handles[channel], &value);
   return FE_SUCCESS;
}
INT epics_ca_set_all (CA_INFO * info, INT channels, float value)
Definition at line 209 of file epics_ca.c.
Referenced by epics_ca().
{
   INT i;
   for (i = 0; i < MIN(info->num_channels, channels); i++)
      ca_put(DBR_FLOAT, info->pv_handles[i], &value);
   return FE_SUCCESS;
}
INT epics_ca_set_label (CA_INFO * info, INT channels, char * label)
Definition at line 221 of file epics_ca.c.
Referenced by epics_ca().
{
   int status;
   char str[256];
   chid chan_id;
   sprintf(str, "%s.DESC", info->channel_names + CHN_NAME_LENGTH * channels);
   status = ca_search(str, &chan_id);
   status = ca_pend_io(2.0);
   if (status != ECA_NORMAL)
      printf("%s not found\n", str);
   status = ca_put(ca_field_type(chan_id), chan_id, label);
   ca_pend_event(0.01);
   return FE_SUCCESS;
}