AlcapDAQ:Rootana: midas/examples/basic/minirc.c File Reference
midas/examples/basic/minirc.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "midas.h"
Functions
main ()
Function Documentation
main (void)
Definition at line 29 of file minirc.c.
References cm_connect_experiment(), cm_disconnect_experiment(), CM_SUCCESS, cm_transition(), host_name, run_number, ss_gets(), status, SYNC, TR_START, and TR_STOP.
{
   INT run_number, status;
   char host_name[256];
   char str[256];
   printf("Host to connect: ");
   ss_gets(host_name, 256);
   /* connect to experiment */
   status = cm_connect_experiment(host_name, "", "MiniRC", NULL);
   if (status != CM_SUCCESS)
      return 1;
   printf("Enter run number: ");
   ss_gets(str, 256);
   run_number = atoi(str);
   printf("Start run\n");
   /* start run */
   if (cm_transition(TR_START, run_number, str, sizeof(str), SYNC) != CM_SUCCESS)
      printf(str);
   printf("Hit RETURN to stop run");
   getchar();
   /* stop run */
   if (cm_transition(TR_STOP, run_number, str, sizeof(str), SYNC) != CM_SUCCESS)
      printf(str);
   cm_disconnect_experiment();
   return 1;
}