AlcapDAQ:Rootana: midas/mscb/embedded/mscbuser.c File Reference
midas/mscb/embedded/mscbuser.c File Reference
#include <stdio.h>
#include "mscb.h"
Functions
void user_write (unsigned char channel)
void user_init (void)
unsigned char user_read (unsigned char channel)
void user_write_conf (unsigned char channel)
void user_read_conf (unsigned char channel)
unsigned char user_func (unsigned char idata *data_in, unsigned char idata *data_out)
void adc_read (channel, unsigned int *d)
void user_loop (void)
Variables
bit FREEZE_MODE
char code node_name [] = "GENERIC"
struct {
unsigned char p1
unsigned int dac0
unsigned int dac1
unsigned int adc [8]
} user_data
struct {
unsigned char adc_average
} user_conf
MSCB_INFO_CHN code channel []
MSCB_INFO_CHN code conf_param []
Function Documentation
void adc_read (channel , unsigned int * d)
Definition at line 189 of file mscbuser.c.
References ADBUSY, ADC0H, ADC0L, ADCINT, AMX0SL, channel, DISABLE_INTERRUPTS, ENABLE_INTERRUPTS, i, n, user_conf, value, and watchdog_refresh().
{
   unsigned long value;
   unsigned int i, n;
   AMX0SL = channel & 0x0F;
   n = 1 << (user_conf.adc_average + 4);
   value = 0;
   for (i = 0; i < n; i++) {
      DISABLE_INTERRUPTS;
      ADCINT = 0;
      ADBUSY = 1;
      while (!ADCINT);          // wait until conversion ready, does NOT work with ADBUSY!
      ENABLE_INTERRUPTS;
      value += (ADC0L | (ADC0H << 8));
      watchdog_refresh();
   }
   if (user_conf.adc_average)
      value >>= (user_conf.adc_average);
   DISABLE_INTERRUPTS;
   *d = value;
   ENABLE_INTERRUPTS;
}
unsigned char user_func (unsigned char idata * data_in, unsigned char idata * data_out)
Definition at line 179 of file mscbuser.c.
{
   /* return some dummy data */
   data_out[0] = data_in[0] + 1;
   data_out[1] = data_in[1] + 1;
   return 2;
}
void user_init (void)
Definition at line 86 of file mscbuser.c.
References ADC0CF, ADC0CN, AMX0CF, DAC0CN, DAC1CN, REF0CN, user_conf, and user_write().
{
#ifdef CPU_ADUC812
   ADCCON1 = 0x7C;              // power up ADC, 14.5us conv+acq time
   ADCCON2 = 0;                 // select channel to convert
   DACCON = 0x1f;               // power on DACs
#endif
#ifdef CPU_C8051F000
   AMX0CF = 0x00;               // select single ended analog inputs
   ADC0CF = 0xE0;               // 16 system clocks, gain 1
   ADC0CN = 0x80;               // enable ADC
   REF0CN = 0x03;               // enable internal reference
   DAC0CN = 0x80;               // enable DAC0
   DAC1CN = 0x80;               // enable DAC1
#endif
   /* correct initial EEPROM value */
   if (user_conf.adc_average == 0xFF)
      user_conf.adc_average = 0;
   /* write P1 and DACs */
   user_write(0);
   user_write(1);
   user_write(2);
}
void user_loop (void)
Definition at line 220 of file mscbuser.c.
References adc_read(), FREEZE_MODE, i, lcd_goto(), and user_data.
{
   unsigned char i;
   /* don't take data in freeze mode */
   if (!FREEZE_MODE);
   {
      for (i = 0; i < 8; i++)
         adc_read(i, &user_data.adc[i]);
      lcd_goto(0, 0);
      printf("%6.4f V", user_data.adc[0] / 65536.0 * 2.5);
   }
}
unsigned char user_read (unsigned char channel)
Definition at line 155 of file mscbuser.c.
References P1, and user_data.
{
   if (channel == 0)
      user_data.p1 = P1;
   return 0;
}
void user_read_conf (unsigned char channel)
Definition at line 172 of file mscbuser.c.
{
   if (channel);
}
void user_write (unsigned char channel)
Definition at line 118 of file mscbuser.c.
References d, DAC0H, DAC0L, DAC1H, DAC1L, data, P1, and user_data.
{
   unsigned char data *d;
   switch (channel) {
   case 0:                     // p1
      P1 = user_data.p1;
      break;
   case 1:                     // DAC0
      d = (void *) &user_data.dac0;
#ifdef CPU_ADUC812
      DAC0H = d[1];
      DAC0L = d[0];
#endif
#ifdef CPU_C8051F000
      DAC0L = d[0];
      DAC0H = d[1];
#endif
      break;
   case 2:                     // DAC1
      d = (void *) &user_data.dac1;
#ifdef CPU_ADUC812
      DAC1H = d[1];
      DAC1L = d[0];
#endif
#ifdef CPU_C8051F000
      DAC1L = d[0];
      DAC1H = d[1];
#endif
      break;
   }
}
void user_write_conf (unsigned char channel)
Definition at line 165 of file mscbuser.c.
{
   if (channel);
}
Variable Documentation
unsigned int adc[8]
Definition at line 48 of file mscbuser.c.
unsigned char adc_average
Definition at line 52 of file mscbuser.c.
MSCB_INFO_CHN code channel[]
Initial value:
 {
   1, 0, 0, 0, "P1", &user_data.p1,
   2, 0, 0, 0, "DAC0", &user_data.dac0,
   2, 0, 0, 0, "DAC1", &user_data.dac1,
   2, 0, 0, 0, "ADC0", &user_data.adc[0],
   2, 0, 0, 0, "ADC1", &user_data.adc[1],
   2, 0, 0, 0, "ADC2", &user_data.adc[2],
   2, 0, 0, 0, "ADC3", &user_data.adc[3],
   2, 0, 0, 0, "ADC4", &user_data.adc[4],
   2, 0, 0, 0, "ADC5", &user_data.adc[5],
   2, 0, 0, 0, "ADC6", &user_data.adc[6],
   2, 0, 0, 0, "ADC7", &user_data.adc[7],
   0
}
Definition at line 56 of file mscbuser.c.
MSCB_INFO_CHN code conf_param[]
Initial value:
 {
   1, 0, 0, 0, "ADCAvrg", &user_conf.adc_average,
   0
}
Definition at line 71 of file mscbuser.c.
unsigned int dac0
Definition at line 46 of file mscbuser.c.
unsigned int dac1
Definition at line 47 of file mscbuser.c.
bit FREEZE_MODE
Definition at line 249 of file mscbmain.c.
char code node_name[] = "GENERIC"
Definition at line 37 of file mscbuser.c.
unsigned char p1
Definition at line 45 of file mscbuser.c.
Referenced by main().
struct { ... } user_conf
Referenced by adc_read(), and user_init().
struct { ... } user_data