AlcapDAQ:Rootana: midas/drivers/device/mscbdev.h File Reference
midas/drivers/device/mscbdev.h File Reference
Functions
INT mscbdev (INT cmd,...)
Function Documentation
INT mscbdev (INT cmd, ...)
Definition at line 223 of file mscbdev.c.
References channel, CMD_EXIT, CMD_GET, CMD_GET_DEFAULT_NAME, CMD_INIT, CMD_SET, FE_SUCCESS, hKey, mscbdev_exit(), mscbdev_get(), mscbdev_init(), mscbdev_set(), status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   DWORD flags;
   float value, *pvalue;
   void *info, *bd;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      flags = va_arg(argptr, DWORD);
      bd = va_arg(argptr, void *);
      status = mscbdev_init(hKey, info, channel, bd);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = mscbdev_exit(info);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);   // floats are passed as double
      status = mscbdev_set(info, channel, value);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = mscbdev_get(info, channel, pvalue);
      break;
   case CMD_GET_DEFAULT_NAME:
      /*
         info = va_arg(argptr, void *);
         channel = va_arg(argptr, INT);
         name = va_arg(argptr, char *);
         status = mscbdev_get_default_name(info, channel, name);
       */
      break;
   default:
      break;
   }
   va_end(argptr);
   return status;
}