AlcapDAQ:Rootana: midas/mscb/mscb.h File Reference
midas/mscb/mscb.h File Reference
Data Structures
struct MSCB_INFO
struct MSCB_INFO_VAR
struct MSCB_FD
Defines
#define MCMD_ADDR_NODE8 0x09
#define MCMD_ADDR_NODE16 0x0A
#define MCMD_ADDR_BC 0x10
#define MCMD_ADDR_GRP8 0x11
#define MCMD_ADDR_GRP16 0x12
#define MCMD_PING8 0x19
#define MCMD_PING16 0x1A
#define MCMD_INIT 0x20
#define MCMD_GET_INFO 0x28
#define MCMD_SET_ADDR 0x34
#define MCMD_SET_BAUD 0x39
#define MCMD_FREEZE 0x41
#define MCMD_SYNC 0x49
#define MCMD_UPGRADE 0x50
#define MCMD_USER 0x58
#define MCMD_ECHO 0x61
#define MCMD_TOKEN 0x68
#define MCMD_SET_FLAGS 0x69
#define MCMD_ACK 0x78
#define MCMD_WRITE_NA 0x80
#define MCMD_WRITE_ACK 0x88
#define MCMD_FLASH 0x98
#define MCMD_READ 0xA0
#define MCMD_WRITE_BLOCK 0xB5
#define MCMD_READ_BLOCK 0xB9
#define GET_INFO_GENERAL 0
#define GET_INFO_VARIABLE 1
#define CSR_DEBUG (1<<0)
#define CSR_LCD_PRESENT (1<<1)
#define CSR_SYNC_MODE (1<<2)
#define CSR_FREEZE_MODE (1<<3)
#define CSR_WD_RESET (1<<2)
#define BD_9600 1
#define BD_19200 2
#define BD_28800 3
#define BD_57600 4
#define BD_115200 5
#define BD_172800 6
#define BD_345600 7
#define MSCBF_FLOAT (1<<0)
#define MSCBF_SIGNED (1<<1)
#define PRFX_PICO -12
#define PRFX_NANO -9
#define PRFX_MICRO -6
#define PRFX_MILLI -3
#define PRFX_NONE 0
#define PRFX_KILO 3
#define PRFX_MEGA 6
#define PRFX_GIGA 9
#define PRFX_TERA 12
#define UNIT_UNDEFINED 0
#define UNIT_METER 1
#define UNIT_GRAM 2
#define UNIT_SECOND 3
#define UNIT_MINUTE 4
#define UNIT_HOUR 5
#define UNIT_AMPERE 6
#define UNIT_KELVIN 7
#define UNIT_CELSIUS 8
#define UNIT_FARENHEIT 9
#define UNIT_HERTZ 20
#define UNIT_PASCAL 21
#define UNIT_BAR 22
#define UNIT_WATT 23
#define UNIT_VOLT 24
#define UNIT_OHM 25
#define UNIT_TESLA 26
#define UNIT_LITERPERSEC 27
#define UNIT_RPM 28
#define UNIT_FARAD 29
#define UNIT_BOOLEAN 50
#define UNIT_BYTE 52
#define UNIT_WORD 53
#define UNIT_DWORD 54
#define UNIT_ASCII 55
#define UNIT_STRING 56
#define UNIT_BAUD 57
#define UNIT_PERCENT 90
#define UNIT_PPM 91
#define UNIT_COUNT 92
#define UNIT_FACTOR 93
#define MSCB_MAX_FD 10
#define MSCB_TYPE_LPT 1
#define MSCB_TYPE_USB 2
#define MSCB_TYPE_COM 3
#define MSCB_TYPE_RPC 4
#define MSCB_SUCCESS 1
#define MSCB_CRC_ERROR 2
#define MSCB_TIMEOUT 3
#define MSCB_INVAL_PARAM 4
#define MSCB_MUTEX 5
#define MSCB_FORMAT_ERROR 6
#define MSCB_NO_MEM 7
#define MSCB_SUBM_ERROR 8
#define MSCB_ADDR_EXISTS 9
#define WORD_SWAP(x)
#define DWORD_SWAP(x)
#define EXPRT
Functions
int EXPRT mscb_init (char *device, int size, int debug)
int EXPRT mscb_select_device (char *data, int size, int select)
void EXPRT mscb_get_device (int fd, char *device, int bufsize)
void EXPRT mscb_get_version (char *lib_version, char *prot_version)
void EXPRT mscb_check (char *device, int size)
int EXPRT mscb_exit (int fd)
int EXPRT mscb_reset (int fd)
int EXPRT mscb_reboot (int fd, int adr)
int EXPRT mscb_ping (int fd, int adr)
int EXPRT mscb_echo (int fd, int addr, unsigned char d1, unsigned char *d2)
int EXPRT mscb_info (int fd, int adr, MSCB_INFO *info)
int EXPRT mscb_info_variable (int fd, int adr, int index, MSCB_INFO_VAR *info)
int EXPRT mscb_set_addr (int fd, int adr, int node, int group)
int EXPRT mscb_set_name (int fd, int adr, char *name)
int EXPRT mscb_write (int fd, int adr, unsigned char index, void *data, int size)
int EXPRT mscb_write_group (int fd, int adr, unsigned char index, void *data, int size)
int EXPRT mscb_write_block (int fd, int adr, unsigned char index, void *data, int size)
int EXPRT mscb_flash (int fd, int adr)
int EXPRT mscb_upload (int fd, int adr, char *buffer, int size, int debug)
int EXPRT mscb_read (int fd, int adr, unsigned char index, void *data, int *size)
int EXPRT mscb_read_range (int fd, int adr, unsigned char index1, unsigned char index2, void *data, int *size)
int EXPRT mscb_user (int fd, int adr, void *param, int size, void *result, int *rsize)
int EXPRT mscb_link (int fd, int adr, unsigned char index, void *data, int size)
int EXPRT mscb_addr (int fd, int cmd, int adr, int retry, int lock)
Variables
MSCB_FD mscb_fd [MSCB_MAX_FD]
Define Documentation
#define BD_115200 5
Definition at line 175 of file mscb.h.
#define BD_172800 6
Definition at line 176 of file mscb.h.
#define BD_19200 2
Definition at line 172 of file mscb.h.
#define BD_28800 3
Definition at line 173 of file mscb.h.
#define BD_345600 7
Definition at line 177 of file mscb.h.
#define BD_57600 4
Definition at line 174 of file mscb.h.
#define BD_9600 1
Definition at line 171 of file mscb.h.
#define CSR_DEBUG (1<<0)
Definition at line 163 of file mscb.h.
#define CSR_FREEZE_MODE (1<<3)
Definition at line 166 of file mscb.h.
#define CSR_LCD_PRESENT (1<<1)
Definition at line 164 of file mscb.h.
#define CSR_SYNC_MODE (1<<2)
Definition at line 165 of file mscb.h.
#define CSR_WD_RESET (1<<2)
Definition at line 167 of file mscb.h.
#define DWORD_SWAP (x)
Value:
{ unsigned char _tmp;                              \
                       _tmp= *((unsigned char *)(x));                    \
                       *((unsigned char *)(x)) = *(((unsigned char *)(x))+3);     \
                       *(((unsigned char *)(x))+3) = _tmp;               \
                       _tmp= *(((unsigned char *)(x))+1);                \
                       *(((unsigned char *)(x))+1) = *(((unsigned char *)(x))+2); \
                       *(((unsigned char *)(x))+2) = _tmp; }
Definition at line 295 of file mscb.h.
#define EXPRT
Definition at line 314 of file mscb.h.
#define GET_INFO_GENERAL 0
Definition at line 158 of file mscb.h.
#define GET_INFO_VARIABLE 1
Definition at line 159 of file mscb.h.
#define MCMD_ACK 0x78
Definition at line 146 of file mscb.h.
#define MCMD_ADDR_BC 0x10
Definition at line 126 of file mscb.h.
#define MCMD_ADDR_GRP16 0x12
Definition at line 128 of file mscb.h.
#define MCMD_ADDR_GRP8 0x11
Definition at line 127 of file mscb.h.
#define MCMD_ADDR_NODE16 0x0A
Definition at line 125 of file mscb.h.
#define MCMD_ADDR_NODE8 0x09
Definition at line 124 of file mscb.h.
#define MCMD_ECHO 0x61
Definition at line 142 of file mscb.h.
#define MCMD_FLASH 0x98
Definition at line 151 of file mscb.h.
#define MCMD_FREEZE 0x41
Definition at line 137 of file mscb.h.
#define MCMD_GET_INFO 0x28
Definition at line 133 of file mscb.h.
#define MCMD_INIT 0x20
Definition at line 132 of file mscb.h.
#define MCMD_PING16 0x1A
Definition at line 130 of file mscb.h.
#define MCMD_PING8 0x19
Definition at line 129 of file mscb.h.
#define MCMD_READ 0xA0
Definition at line 153 of file mscb.h.
#define MCMD_READ_BLOCK 0xB9
Definition at line 156 of file mscb.h.
#define MCMD_SET_ADDR 0x34
Definition at line 134 of file mscb.h.
#define MCMD_SET_BAUD 0x39
Definition at line 135 of file mscb.h.
#define MCMD_SET_FLAGS 0x69
Definition at line 144 of file mscb.h.
#define MCMD_SYNC 0x49
Definition at line 138 of file mscb.h.
#define MCMD_TOKEN 0x68
Definition at line 143 of file mscb.h.
#define MCMD_UPGRADE 0x50
Definition at line 139 of file mscb.h.
#define MCMD_USER 0x58
Definition at line 140 of file mscb.h.
#define MCMD_WRITE_ACK 0x88
Definition at line 149 of file mscb.h.
#define MCMD_WRITE_BLOCK 0xB5
Definition at line 155 of file mscb.h.
#define MCMD_WRITE_NA 0x80
Definition at line 148 of file mscb.h.
#define MSCB_ADDR_EXISTS 9
Definition at line 287 of file mscb.h.
Referenced by cmd_loop(), and mscb_set_addr().
#define MSCB_CRC_ERROR 2
Definition at line 280 of file mscb.h.
Referenced by cmd_loop(), mscb_echo(), mscb_flash(), mscb_info(), mscb_info_variable(), mscb_read(), mscb_read_range(), mscb_user(), and mscb_write().
#define MSCB_FORMAT_ERROR 6
Definition at line 284 of file mscb.h.
Referenced by cmd_loop(), mscb_upload(), and mscb_user().
#define MSCB_INVAL_PARAM 4
Definition at line 282 of file mscb.h.
Referenced by mscb_addr(), mscb_echo(), mscb_exit(), mscb_flash(), mscb_in(), mscb_info(), mscb_info_variable(), mscb_out(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_reset(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), and mscb_write_group().
#define MSCB_MAX_FD 10
Definition at line 260 of file mscb.h.
Referenced by mscb_addr(), mscb_cleanup(), mscb_echo(), mscb_exit(), mscb_flash(), mscb_get_device(), mscb_in(), mscb_info(), mscb_info_variable(), mscb_init(), mscb_out(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_reset(), mscb_select_device(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), and mscb_write_group().
#define MSCB_MUTEX 5
Definition at line 283 of file mscb.h.
Referenced by cmd_loop(), mscb_addr(), mscb_echo(), mscb_flash(), mscb_info(), mscb_info_variable(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_reset(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), and mscb_write_group().
#define MSCB_NO_MEM 7
Definition at line 285 of file mscb.h.
Referenced by mscb_link(), and mscb_read().
#define MSCB_SUBM_ERROR 8
Definition at line 286 of file mscb.h.
Referenced by cmd_loop(), and mscb_addr().
#define MSCB_SUCCESS 1
Definition at line 279 of file mscb.h.
Referenced by addr_changed(), cmd_loop(), lpt_close(), lpt_init(), main(), mscb_addr(), mscb_echo(), mscb_exit(), mscb_flash(), mscb_in(), mscb_in1(), mscb_info(), mscb_info_variable(), mscb_link(), mscb_lock(), mscb_out(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_release(), mscb_reset(), mscb_select_device(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), mscb_write_group(), and mscbdev_get_default_name().
#define MSCB_TIMEOUT 3
Definition at line 281 of file mscb.h.
Referenced by cmd_loop(), mscb_addr(), mscb_echo(), mscb_flash(), mscb_in1(), mscb_info(), mscb_info_variable(), mscb_out(), mscb_read(), mscb_read_range(), mscb_upload(), mscb_user(), and mscb_write().
#define MSCB_TYPE_COM 3
Definition at line 264 of file mscb.h.
#define MSCB_TYPE_LPT 1
Definition at line 262 of file mscb.h.
Referenced by mscb_init(), mscb_lock(), mscb_release(), mscb_reset(), and mscb_select_device().
#define MSCB_TYPE_RPC 4
Definition at line 265 of file mscb.h.
Referenced by mrpc_connected(), and mscb_init().
#define MSCB_TYPE_USB 2
Definition at line 263 of file mscb.h.
Referenced by mscb_exit(), mscb_in(), mscb_init(), mscb_lock(), mscb_out(), mscb_release(), and mscb_reset().
#define MSCBF_FLOAT (1<<0)
Definition at line 199 of file mscb.h.
#define MSCBF_SIGNED (1<<1)
Definition at line 200 of file mscb.h.
#define PRFX_GIGA 9
Definition at line 211 of file mscb.h.
#define PRFX_KILO 3
Definition at line 209 of file mscb.h.
#define PRFX_MEGA 6
Definition at line 210 of file mscb.h.
#define PRFX_MICRO -6
Definition at line 206 of file mscb.h.
#define PRFX_MILLI -3
Definition at line 207 of file mscb.h.
#define PRFX_NANO -9
Definition at line 205 of file mscb.h.
#define PRFX_NONE 0
Definition at line 208 of file mscb.h.
#define PRFX_PICO -12
Definition at line 204 of file mscb.h.
#define PRFX_TERA 12
Definition at line 212 of file mscb.h.
#define UNIT_AMPERE 6
Definition at line 222 of file mscb.h.
#define UNIT_ASCII 55
Definition at line 246 of file mscb.h.
#define UNIT_BAR 22
Definition at line 231 of file mscb.h.
#define UNIT_BAUD 57
Definition at line 248 of file mscb.h.
#define UNIT_BOOLEAN 50
Definition at line 242 of file mscb.h.
#define UNIT_BYTE 52
Definition at line 243 of file mscb.h.
#define UNIT_CELSIUS 8
Definition at line 224 of file mscb.h.
#define UNIT_COUNT 92
Definition at line 254 of file mscb.h.
#define UNIT_DWORD 54
Definition at line 245 of file mscb.h.
#define UNIT_FACTOR 93
Definition at line 255 of file mscb.h.
#define UNIT_FARAD 29
Definition at line 238 of file mscb.h.
#define UNIT_FARENHEIT 9
Definition at line 225 of file mscb.h.
#define UNIT_GRAM 2
Definition at line 218 of file mscb.h.
#define UNIT_HERTZ 20
Definition at line 229 of file mscb.h.
#define UNIT_HOUR 5
Definition at line 221 of file mscb.h.
#define UNIT_KELVIN 7
Definition at line 223 of file mscb.h.
#define UNIT_LITERPERSEC 27
Definition at line 236 of file mscb.h.
#define UNIT_METER 1
Definition at line 217 of file mscb.h.
#define UNIT_MINUTE 4
Definition at line 220 of file mscb.h.
#define UNIT_OHM 25
Definition at line 234 of file mscb.h.
#define UNIT_PASCAL 21
Definition at line 230 of file mscb.h.
#define UNIT_PERCENT 90
Definition at line 252 of file mscb.h.
#define UNIT_PPM 91
Definition at line 253 of file mscb.h.
#define UNIT_RPM 28
Definition at line 237 of file mscb.h.
#define UNIT_SECOND 3
Definition at line 219 of file mscb.h.
#define UNIT_STRING 56
Definition at line 247 of file mscb.h.
#define UNIT_TESLA 26
Definition at line 235 of file mscb.h.
#define UNIT_UNDEFINED 0
Definition at line 214 of file mscb.h.
#define UNIT_VOLT 24
Definition at line 233 of file mscb.h.
#define UNIT_WATT 23
Definition at line 232 of file mscb.h.
#define UNIT_WORD 53
Definition at line 244 of file mscb.h.
#define WORD_SWAP (x)
Value:
{ unsigned char _tmp;                               \
                       _tmp= *((unsigned char *)(x));                    \
                       *((unsigned char *)(x)) = *(((unsigned char *)(x))+1);     \
                       *(((unsigned char *)(x))+1) = _tmp; }
Definition at line 290 of file mscb.h.
Function Documentation
int EXPRT mscb_addr (int fd, int cmd, int adr, int retry, int lock)
Definition at line 1909 of file mscb.c.
References buf, crc8(), i, MCMD_ACK, MCMD_ADDR_GRP16, MCMD_ADDR_GRP8, MCMD_ADDR_NODE16, MCMD_ADDR_NODE8, MCMD_PING16, MCMD_PING8, mrpc_call(), mrpc_connected(), mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUBM_ERROR, MSCB_SUCCESS, MSCB_TIMEOUT, n, RPC_MSCB_ADDR, RS485_FLAG_BIT9, RS485_FLAG_NO_ACK, RS485_FLAG_SHORT_TO, and type.
Referenced by cmd_loop(), mscb_echo(), mscb_flash(), mscb_info(), mscb_info_variable(), mscb_ping(), mscb_read(), mscb_read_range(), mscb_reboot(), mscb_set_addr(), mscb_set_name(), mscb_upload(), mscb_user(), mscb_write(), mscb_write_block(), mscb_write_group(), and server_execute().
         : mscb_addr
  Purpose: Address node or nodes, only used internall from read and
           write routines. A MSCB lock has to be obtained outside
           of this routine!
  Input:
    int fd                  File descriptor for connection
    int cmd                 Addressing mode, one of
                              MCMD_ADDR_BC
                              MCMD_ADDR_NODE8
                              MCMD_ADDR_GRP8
                              MCMD_PING8
                              MCMD_ADDR_NODE16
                              MCMD_ADDR_GRP16
                              MCMD_PING16
    int adr                 Node or group address
    int retry               Number of retries
    int lock                Lock MSCB if TRUE
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving ping acknowledge
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   unsigned char buf[10];
   int i, n, status;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_ADDR, mscb_fd[fd - 1].remote_fd, cmd, adr, retry, lock);
   if (lock) {
      if (mscb_lock(fd) != MSCB_SUCCESS)
         return MSCB_MUTEX;
   }
   for (n = 0; n < retry; n++) {
      buf[0] = cmd;
      if (cmd == MCMD_ADDR_NODE8 || cmd == MCMD_ADDR_GRP8) {
         buf[1] = (unsigned char) adr;
         buf[2] = crc8(buf, 2);
         status = mscb_out(fd, buf, 3, RS485_FLAG_BIT9 | RS485_FLAG_SHORT_TO | RS485_FLAG_NO_ACK);
      } else if (cmd == MCMD_PING8) {
         buf[1] = (unsigned char) adr;
         buf[2] = crc8(buf, 2);
         status = mscb_out(fd, buf, 3, RS485_FLAG_BIT9 | RS485_FLAG_SHORT_TO);
      } else if (cmd == MCMD_ADDR_NODE16 || cmd == MCMD_ADDR_GRP16) {
         buf[1] = (unsigned char) (adr >> 8);
         buf[2] = (unsigned char) (adr & 0xFF);
         buf[3] = crc8(buf, 3);
         status = mscb_out(fd, buf, 4, RS485_FLAG_BIT9 | RS485_FLAG_SHORT_TO | RS485_FLAG_NO_ACK);
      } else if (cmd == MCMD_PING16) {
         buf[1] = (unsigned char) (adr >> 8);
         buf[2] = (unsigned char) (adr & 0xFF);
         buf[3] = crc8(buf, 3);
         status = mscb_out(fd, buf, 4, RS485_FLAG_BIT9 | RS485_FLAG_SHORT_TO);
      } else {
         buf[1] = crc8(buf, 1);
         status = mscb_out(fd, buf, 2, RS485_FLAG_BIT9 | RS485_FLAG_SHORT_TO | RS485_FLAG_NO_ACK);
      }
      if (status != MSCB_SUCCESS) {
         if (lock)
            mscb_release(fd);
         return MSCB_SUBM_ERROR;
      }
      if (cmd == MCMD_PING8 || cmd == MCMD_PING16) {
         /* read back ping reply, 4ms timeout (for USB!) */
         i = mscb_in(fd, buf, 1, 4000);
         if (i == MSCB_SUCCESS && buf[0] == MCMD_ACK) {
            if (lock)
               mscb_release(fd);
            return MSCB_SUCCESS;
         }
         if (retry > 1) {
            /* send 0's to overflow partially filled node receive buffer */
            memset(buf, 0, sizeof(buf));
            mscb_out(fd, buf, 10, RS485_FLAG_BIT9 | RS485_FLAG_NO_ACK);
            /* wait some time */
            Sleep(10);
         }
         /* try again.... */
      } else {
         if (lock)
            mscb_release(fd);
         return MSCB_SUCCESS;
      }
   }
   if (lock)
      mscb_release(fd);
   return MSCB_TIMEOUT;
}
void EXPRT mscb_check (char * device, int size)
Definition at line 1833 of file mscb.c.
References d, i, LPT_ACK, LPT_BIT9, LPT_BUSY, LPT_DATAREADY, LPT_RESET, LPT_STROBE, mscb_init(), mscb_lock(), mscb_release(), pp_rdata(), pp_rstatus(), pp_wcontrol(), and pp_wdata().
Referenced by main().
         : mscb_check
  Purpose: Check IO pins of port
  Input:
    char *device            Under NT: lpt1 or lpt2
                            Under Linux: /dev/parport0 or /dev/parport1
  Function value:
    int fd                  device descriptor for connection, -1 if
                            error
\********************************************************************/
{
   int i, fd, d;
   mscb_init(device, size, 0);
   fd = 1;
   mscb_lock(fd);
   printf("Toggling %s output pins, hit ENTER to stop.\n", device);
   printf("GND = 19-25, toggling 2-9, 1, 14, 16 and 17\n\n");
   do {
      printf("\r11111111 1111");
      fflush(stdout);
      pp_wdata(fd, 0xFF);
      pp_wcontrol(fd, LPT_STROBE, 1);
      pp_wcontrol(fd, LPT_ACK, 1);
      pp_wcontrol(fd, LPT_RESET, 1);
      pp_wcontrol(fd, LPT_BIT9, 1);
      Sleep(1000);
      printf("\r00000000 0000");
      fflush(stdout);
      pp_wdata(fd, 0);
      pp_wcontrol(fd, LPT_STROBE, 0);
      pp_wcontrol(fd, LPT_ACK, 0);
      pp_wcontrol(fd, LPT_RESET, 0);
      pp_wcontrol(fd, LPT_BIT9, 0);
      Sleep(1000);
   } while (!kbhit());
   while (kbhit())
      getch();
   printf("\n\n\nInput display, hit ENTER to stop.\n");
   printf("Pins 2-9, 10 and 11\n\n");
   do {
      d = pp_rdata(fd);
      for (i = 0; i < 8; i++) {
         printf("%d", (d & 1) > 0);
         d >>= 1;
      }
      printf(" %d%d\r", !pp_rstatus(fd, LPT_DATAREADY), pp_rstatus(fd, LPT_BUSY));
      fflush(stdout);
      Sleep(100);
   } while (!kbhit());
   while (kbhit())
      getch();
   mscb_release(fd);
}
int EXPRT mscb_echo (int fd, int addr, unsigned char d1, unsigned char * d2)
Definition at line 3243 of file mscb.c.
References buf, crc8(), MCMD_ECHO, MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, n, RPC_MSCB_ECHO, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_echo
  Purpose: Send byte and receive echo, useful for testing
  Input:
    int  fd                 File descriptor for connection
    int  adr                Node address
    unsigned char d1        Byte to send
  Output:
    unsigned char *d2       Received byte
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_CRC_ERROR          CRC error
    MSCB_MUTEX              Cannot obtain mutex for mscb
    MSCB_FORMAT_ERROR       "size" parameter too large
\********************************************************************/
{
   int n, status;
   unsigned char buf[80];
   *d2 = 0xFF;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_ECHO, mscb_fd[fd - 1].remote_fd, adr, d1, d2);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   if (adr) {
      status = mscb_addr(fd, MCMD_PING16, adr, 1, 0);
      if (status != MSCB_SUCCESS) {
         mscb_release(fd);
         return status;
      }
   }
   buf[0] = MCMD_ECHO;
   buf[1] = d1;
   /* add CRC code and send data */
   buf[2] = crc8(buf, 2);
   status = mscb_out(fd, buf, 3, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   /* read result */
   n = mscb_in(fd, buf, sizeof(buf), 10000);
   mscb_release(fd);
   if (n < 0)
      return MSCB_TIMEOUT;
   *d2 = buf[1];
   if (buf[n - 1] != crc8(buf, n - 1))
      return MSCB_CRC_ERROR;
   return MSCB_SUCCESS;
}
int EXPRT mscb_exit (int fd)
Definition at line 1750 of file mscb.c.
References mrpc_call(), mrpc_connected(), mrpc_disconnect(), MSCB_INVAL_PARAM, MSCB_MAX_FD, MSCB_SUCCESS, MSCB_TYPE_USB, musb_close(), RPC_MSCB_EXIT, and type.
Referenced by main(), mscbdev_exit(), and server_execute().
         : mscb_exit
  Purpose: Close a MSCB interface
  Input:
    int  fd                 file descriptor for connection
  Function value:
    MSCB_SUCCESS            Successful completion
\********************************************************************/
{
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd)) {
      mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_EXIT, mscb_fd[fd - 1].remote_fd);
      mrpc_disconnect(mscb_fd[fd - 1].fd);
   }
   if (mscb_fd[fd - 1].type == MSCB_TYPE_USB)
      musb_close(mscb_fd[fd - 1].hr, mscb_fd[fd - 1].hw);
   /* outcommented, other client (like Labview) could still use LPT ...
   if (mscb_fd[fd - 1].type == MSCB_TYPE_LPT)
      lpt_close(mscb_fd[fd - 1].fd);
   */
   memset(&mscb_fd[fd - 1], 0, sizeof(MSCB_FD));
   return MSCB_SUCCESS;
}
int EXPRT mscb_flash (int fd, int adr)
Definition at line 2626 of file mscb.c.
References buf, crc8(), i, MCMD_ACK, MCMD_FLASH, MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, RPC_MSCB_FLASH, RS485_FLAG_LONG_TO, and type.
Referenced by cmd_loop(), main(), and server_execute().
         : mscb_flash
  Purpose: Flash node variables to EEPROM
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
                            and dword
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, status;
   unsigned char buf[10], crc, ack[2];
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_FLASH, mscb_fd[fd - 1].remote_fd, adr);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_FLASH;
   crc = crc8(buf, 1);
   buf[1] = crc;
   mscb_out(fd, buf, 2, RS485_FLAG_LONG_TO);
   /* read acknowledge, 100ms timeout */
   i = mscb_in(fd, ack, 2, 100000);
   mscb_release(fd);
   if (i < 2)
      return MSCB_TIMEOUT;
   if (ack[0] != MCMD_ACK || ack[1] != crc)
      return MSCB_CRC_ERROR;
   return MSCB_SUCCESS;
}
void EXPRT mscb_get_device (int fd, char * device, int bufsize)
Definition at line 1800 of file mscb.c.
References mrpc_call(), mrpc_connected(), MSCB_MAX_FD, RPC_MSCB_GET_DEVICE, and type.
         : mscb_get_device
  Purpose: Return device name for fd
  Input:
    int fd                  File descriptor obtained wiv mscb_init()
    int bufsize             Size of device string
    char *device            device name, "" if invalid fd
\********************************************************************/
{
   char str[256];
   if (!device)
      return;
   *device = 0;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return;
   if (mrpc_connected(fd)) {
      mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_GET_DEVICE,
                mscb_fd[fd - 1].remote_fd, str, sizeof(str));
   }
   strcpy(device, mscb_fd[fd-1].device);
}
void EXPRT mscb_get_version (char * lib_version, char * prot_version)
Definition at line 1578 of file mscb.c.
References MSCB_LIBRARY_VERSION, and MSCB_PROTOCOL_VERSION.
Referenced by cmd_loop().
{
   strcpy(lib_version, MSCB_LIBRARY_VERSION);
   strcpy(prot_version, MSCB_PROTOCOL_VERSION);
}
int EXPRT mscb_info (int fd, int adr, MSCB_INFO * info)
Definition at line 2156 of file mscb.c.
References buf, crc8(), MSCB_INFO::group_address, i, MCMD_GET_INFO, MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, MSCB_INFO::node_address, RPC_MSCB_INFO, RS485_FLAG_LONG_TO, type, MSCB_INFO::watchdog_resets, and WORD_SWAP.
Referenced by cmd_loop(), and server_execute().
         : mscb_info
  Purpose: Retrieve info on addressd node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
  Output:
    MSCB_INFO *info         Info structure defined in mscb.h
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_CRC_ERROR          CRC error
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, status;
   unsigned char buf[256];
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_INFO, mscb_fd[fd - 1].remote_fd, adr, info);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_GET_INFO;
   buf[1] = crc8(buf, 1);
   mscb_out(fd, buf, 2, RS485_FLAG_LONG_TO);
   i = mscb_in(fd, buf, sizeof(buf), 10000);
   mscb_release(fd);
   if (i < (int) sizeof(MSCB_INFO) + 2)
      return MSCB_TIMEOUT;
   memcpy(info, buf + 2, sizeof(MSCB_INFO));
   /* do CRC check */
   if (crc8(buf, sizeof(MSCB_INFO) + 2) != buf[sizeof(MSCB_INFO) + 2])
      return MSCB_CRC_ERROR;
   WORD_SWAP(&info->node_address);
   WORD_SWAP(&info->group_address);
   WORD_SWAP(&info->watchdog_resets);
   return MSCB_SUCCESS;
}
int EXPRT mscb_info_variable (int fd, int adr, int index, MSCB_INFO_VAR * info)
Definition at line 2221 of file mscb.c.
References buf, crc8(), i, MCMD_GET_INFO, MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, RPC_MSCB_INFO_VARIABLE, RS485_FLAG_LONG_TO, and type.
Referenced by addr_changed(), cmd_loop(), main(), mscb_link(), mscbdev_get_default_name(), and server_execute().
         : mscb_info_variable
  Purpose: Retrieve info on a specific node variable
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    int index               Variable index 0..255
  Output:
    MSCB_INFO_VAR *info     Info structure defined in mscb.h
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_CRC_ERROR          CRC error
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, status;
   unsigned char buf[80];
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_INFO_VARIABLE,
                       mscb_fd[fd - 1].remote_fd, adr, index, info);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_GET_INFO + 1;
   buf[1] = index;
   buf[2] = crc8(buf, 2);
   mscb_out(fd, buf, 3, RS485_FLAG_LONG_TO);
   i = mscb_in(fd, buf, sizeof(buf), 10000);
   mscb_release(fd);
   if (i < (int) sizeof(MSCB_INFO_VAR) + 3)
      return MSCB_TIMEOUT;
   memcpy(info, buf + 2, sizeof(MSCB_INFO_VAR));
   /* do CRC check */
   if (crc8(buf, sizeof(MSCB_INFO_VAR) + 2) != buf[sizeof(MSCB_INFO_VAR) + 2])
      return MSCB_CRC_ERROR;
   return MSCB_SUCCESS;
}
int EXPRT mscb_init (char * device, int size, int debug)
Definition at line 1593 of file mscb.c.
References _debug_flag, buf, data, debug_log(), MSCB_FD::fd, i, lpt_init(), MCMD_ACK, MCMD_ECHO, mrpc_call(), mrpc_connect(), mrpc_disconnect(), mscb_in(), mscb_lock(), MSCB_MAX_FD, mscb_out(), mscb_release(), mscb_select_device(), MSCB_TYPE_LPT, MSCB_TYPE_RPC, MSCB_TYPE_USB, musb_init(), n, n_cache, MSCB_FD::remote_fd, RPC_MSCB_INIT, RS485_FLAG_CMD, strieq(), strlcpy(), type, and MSCB_FD::type.
Referenced by main(), mscb_check(), mscbdev_init(), and server_execute().
         : mscb_init
  Purpose: Initialize and open MSCB
  Input:
    char *device            Under NT: lpt1 or lpt2
                            Under Linux: /dev/parport0 or /dev/parport1
                            "<host>:device" for RPC connection
                            usbx for USB connection
                            If device equals "", the function
                            mscb_select_device is called which selects
                            the first available device or asks the user
                            which one to use.
    int bufsize             Size of "device" string, in case no device
                            is specified from the caller and this function
                            returns the chosen device
    int debug               Debug flag. If "1" debugging information is
                            written to "mscb_debug.log" in the current
                            directory. If "-1", do not ask for device
                            (useb by LabView DLL)
  Function value:
    int fd                  device descriptor for connection, -1 if
                            error
\********************************************************************/
{
   int index, i, n;
   int status;
   char host[256], port[256], dev3[256], buf[10], remote_device[256];
   /* search for new file descriptor */
   for (index = 0; index < MSCB_MAX_FD; index++)
      if (mscb_fd[index].fd == 0)
         break;
   if (index == MSCB_MAX_FD)
      return -1;
   /* set global debug flag */
   _debug_flag = (debug == 1);
   debug_log("mscb_init( %s %d %d * %d)\n", device, bufsize, debug);
   /* clear cache */
   for (i = 0; i < n_cache; i++)
      free(cache[i].data);
   free(cache);
   n_cache = 0;
   if (!device[0]) {
      if (debug == -1)
         mscb_select_device(device, bufsize, 0); /* for LabView */
      else
         mscb_select_device(device, bufsize, 1); /* interactively ask for device */
   }
   /* check for RPC connection */
   if (strchr(device, ':')) {
      strlcpy(mscb_fd[index].device, device, sizeof(mscb_fd[index].device));
      mscb_fd[index].type = MSCB_TYPE_RPC;
      strcpy(remote_device, strchr(device, ':') + 1);
      strcpy(host, device);
      *strchr(host, ':') = 0;
      mscb_fd[index].fd = mrpc_connect(host);
      if (mscb_fd[index].fd < 0) {
         mscb_fd[index].fd = 0;
         return -1;
      }
      mscb_fd[index].remote_fd = mrpc_call(mscb_fd[index].fd, RPC_MSCB_INIT, remote_device, bufsize, debug);
      if (mscb_fd[index].remote_fd < 0) {
         mrpc_disconnect(mscb_fd[index].fd);
         mscb_fd[index].fd = 0;
         return -1;
      }
      sprintf(device, "%s:%s", host, remote_device);
      return index + 1;
   }
   /* check which device type */
   strcpy(dev3, device);
   dev3[3] = 0;
   strcpy(mscb_fd[index].device, device);
   mscb_fd[index].type = 0;
   /* LPT port with direct address */
   if (device[1] == 'x') {
      mscb_fd[index].type = MSCB_TYPE_LPT;
      sscanf(port + 2, "%x", &mscb_fd[index].fd);
   }
   /* LPTx */
   if (strieq(dev3, "LPT")) {
      mscb_fd[index].type = MSCB_TYPE_LPT;
   }
   /* /dev/parportx */
   if (strstr(device, "parport")) {
      mscb_fd[index].type = MSCB_TYPE_LPT;
   }
   /* USBx */
   if (strieq(dev3, "usb"))
      mscb_fd[index].type = MSCB_TYPE_USB;
   if (mscb_fd[index].type == 0)
      return -1;
   /*---- initialize submaster ----*/
   if (mscb_fd[index].type == MSCB_TYPE_LPT) {
      status = lpt_init(device, index);
      if (status < 0)
         return status;
   }
   if (mscb_fd[index].type == MSCB_TYPE_USB) {
      status = musb_init(atoi(device + 3), &mscb_fd[index].hr, &mscb_fd[index].hw);
      if (status < 0)
         return status;
      /* linux needs some time to start-up ...??? */
      for (i = 0; i < 10; i++) {
         mscb_lock(index + 1);
         /* check if submaster alive */
         buf[0] = MCMD_ECHO;
         mscb_out(index + 1, buf, 1, RS485_FLAG_CMD);
         n = mscb_in(index + 1, buf, 2, 10000);
         mscb_release(index + 1);
         if (n == 2 && buf[0] == MCMD_ACK)
            break;
      }
      if (n != 2 || buf[0] != MCMD_ACK)
         return -4;
   }
   return index + 1;
}
int EXPRT mscb_link (int fd, int adr, unsigned char index, void * data, int size)
Definition at line 3334 of file mscb.c.
References CACHE_ENTRY::adr, CACHE_PERIOD, CACHE_ENTRY::data, debug_log(), CACHE_ENTRY::fd, i, CACHE_ENTRY::index, CACHE_ENTRY::last, last, millitime(), mscb_info_variable(), MSCB_NO_MEM, mscb_read(), MSCB_SUCCESS, mscb_write(), n_cache, CACHE_ENTRY::size, and MSCB_INFO_VAR::width.
Referenced by cmd_loop().
         : mscb_link
  Purpose: Used by LabView to link controls to MSCB variables
  Input:
    int  fd                 File descriptor for connection
    int  adr                Node address
    unsigned char index     Variable index
    void *data              Pointer to data
    int size                Size of data
  Output:
    void *data              Readback data
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_CRC_ERROR          CRC error
    MSCB_MUTEX              Cannot obtain mutex for mscb
    MSCB_FORMAT_ERROR       "size" parameter too large
    MSCB_NO_MEM             Out of memory
\********************************************************************/
{
   int i, s, status;
   MSCB_INFO_VAR info;
   debug_log("mscb_link( %d %d %d * %d)\n", fd, adr, index, size);
   /* check if variable in cache */
   for (i = 0; i < n_cache; i++)
      if (cache[i].fd == fd && cache[i].adr == adr && cache[i].index == index)
         break;
   if (i < n_cache) {
      if (memcmp(data, cache[i].data, cache[i].size) != 0) {
         /* data has changed, send update */
         memcpy(cache[i].data, data, cache[i].size);
         mscb_write(fd, adr, index, data, cache[i].size);
      } else {
         /* retrieve data from node */
         if (millitime() > cache[i].last + CACHE_PERIOD) {
            cache[i].last = millitime();
            s = cache[i].size;
            status = mscb_read(fd, adr, index, cache[i].data, &s);
            if (status != MSCB_SUCCESS)
               return status;
            memcpy(data, cache[i].data, size);
         }
      }
   } else {
      /* add new entry in cache */
      if (n_cache == 0)
         cache = (CACHE_ENTRY *) malloc(sizeof(CACHE_ENTRY));
      else
         cache = (CACHE_ENTRY *) realloc(cache, sizeof(CACHE_ENTRY) * (n_cache + 1));
      if (cache == NULL)
         return MSCB_NO_MEM;
      /* get variable size from node */
      status = mscb_info_variable(fd, adr, index, &info);
      if (status != MSCB_SUCCESS)
         return status;
      /* setup cache entry */
      i = n_cache;
      n_cache++;
      cache[i].fd = fd;
      cache[i].adr = adr;
      cache[i].index = index;
      cache[i].last = 0;
      cache[i].size = info.width;
      /* allocate at least 4 bytes */
      s = info.width;
      if (s < 4)
         s = 4;
      cache[i].data = malloc(s);
      if (cache[i].data == NULL)
         return MSCB_NO_MEM;
      memset(cache[i].data, 0, s);
      /* read initial value */
      s = cache[i].size;
      status = mscb_read(fd, adr, index, cache[i].data, &s);
      if (status != MSCB_SUCCESS)
         return status;
      memcpy(data, cache[i].data, size);
   }
   return MSCB_SUCCESS;
}
int EXPRT mscb_ping (int fd, int adr)
Definition at line 2116 of file mscb.c.
References MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_release(), MSCB_SUCCESS, RPC_MSCB_PING, and type.
Referenced by cmd_loop(), main(), and server_execute().
         : mscb_ping
  Purpose: Ping node to see if it's alive
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
  Output:
    none
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int status;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_PING, mscb_fd[fd - 1].remote_fd, adr);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 1, 0);
   mscb_release(fd);
   return status;
}
int EXPRT mscb_read (int fd, int adr, unsigned char index, void * data, int * size)
Definition at line 2939 of file mscb.c.
References buf, crc8(), DWORD_SWAP, i, MCMD_ACK, MCMD_PING16, MCMD_READ, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, MSCB_NO_MEM, mscb_out(), mscb_release(), mscb_reset(), MSCB_SUCCESS, MSCB_TIMEOUT, n, RPC_MSCB_READ, type, and WORD_SWAP.
Referenced by cmd_loop(), main(), mscb_link(), mscbdev_get(), and server_execute().
         : mscb_read
  Purpose: Read data from variable on node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    unsigned char index     Variable index 0..255
    int size                Buffer size for data
  Output:
    void *data              Received data
    int  *size              Number of received bytes
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, n, status;
   unsigned char buf[256], crc;
   memset(data, 0, *size);
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_READ, mscb_fd[fd - 1].remote_fd, adr, index, data, size);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   /* try ten times */
   for (n = 0; n < 10; n++) {
      /* after five times, reset submaster */
      if (n == 5) {
#ifndef _USRDLL
         printf("Automatic submaster reset.\n");
#endif
         mscb_reset(fd);
         Sleep(100);
      }
      buf[0] = MCMD_READ + 1;
      buf[1] = index;
      buf[2] = crc8(buf, 2);
      mscb_out(fd, buf, 3, 0);
      /* read data */
      i = mscb_in(fd, buf, sizeof(buf), 10000);
      if (i == 1 && buf[0] == 0xFF) {
#ifndef _USRDLL
         printf("Timeout from RS485 bus.\n");
#endif
         return MSCB_TIMEOUT;
      }
      if (i < 2)
         continue;
      crc = crc8(buf, i - 1);
      if ((buf[0] != MCMD_ACK + i - 2 && buf[0] != MCMD_ACK + 7)
          || buf[i - 1] != crc)
         continue;
      if (buf[0] == MCMD_ACK + 7) {
         if (i - 3 > *size) {
            mscb_release(fd);
            *size = 0;
            return MSCB_NO_MEM;
         }
         memcpy(data, buf + 2, i - 3);  // variable length
         *size = i - 3;
      } else {
         if (i - 2 > *size) {
            mscb_release(fd);
            *size = 0;
            return MSCB_NO_MEM;
         }
         memcpy(data, buf + 1, i - 2);
         *size = i - 2;
      }
      if (i - 2 == 2)
         WORD_SWAP(data);
      if (i - 2 == 4)
         DWORD_SWAP(data);
      mscb_release(fd);
      return MSCB_SUCCESS;
   }
   mscb_release(fd);
   if (i < 2)
      return MSCB_TIMEOUT;
   return MSCB_CRC_ERROR;
}
int EXPRT mscb_read_range (int fd, int adr, unsigned char index1, unsigned char index2, void * data, int * size)
Definition at line 3060 of file mscb.c.
References buf, crc8(), i, MCMD_ACK, MCMD_PING16, MCMD_READ, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), mscb_reset(), MSCB_SUCCESS, MSCB_TIMEOUT, n, RPC_MSCB_READ_RANGE, and type.
Referenced by server_execute().
         : mscb_read
  Purpose: Read data from channel on node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    unsigned char index1    First index to read
    unsigned char index2    Last index to read
    int size                Buffer size for data
  Output:
    void *data              Received data
    int  *size              Number of received bytes
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, n, status;
   unsigned char buf[256], crc;
   memset(data, 0, *size);
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_READ_RANGE,
                       mscb_fd[fd - 1].remote_fd, adr, index1, index2, data, size);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   /* try ten times */
   for (n = 0; n < 10; n++) {
      /* after five times, reset submaster */
      if (n == 5) {
#ifndef _USRDLL
         printf("Automatic submaster reset.\n");
#endif
         mscb_reset(fd);
         Sleep(100);
      }
      buf[0] = MCMD_READ + 2;
      buf[1] = index1;
      buf[2] = index2;
      buf[3] = crc8(buf, 3);
      mscb_out(fd, buf, 4, 0);
      /* read data */
      i = mscb_in(fd, buf, 256, 10000);
      if (i < 2)
         continue;
      crc = crc8(buf, i - 1);
      if (buf[0] != MCMD_ACK + 7 || buf[i - 1] != crc)
         continue;
      memcpy(data, buf + 2, i - 3);
      *size = i - 3;
      mscb_release(fd);
      return MSCB_SUCCESS;
   }
   mscb_release(fd);
   if (i < 2)
      return MSCB_TIMEOUT;
   return MSCB_CRC_ERROR;
}
int EXPRT mscb_reboot (int fd, int adr)
Definition at line 2021 of file mscb.c.
References buf, crc8(), MCMD_INIT, MCMD_PING16, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, RPC_MSCB_REBOOT, RS485_FLAG_NO_ACK, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_reboot
  Purpose: Reboot node by sending MCMD_INIT
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_MUTEX              Cannot obtain mutex for mscb
    MSCB_TIMEOUT            Timeout receiving ping acknowledge
\********************************************************************/
{
   unsigned char buf[10];
   int status;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_REBOOT, mscb_fd[fd - 1].remote_fd, adr);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_INIT;
   buf[1] = crc8(buf, 1);
   mscb_out(fd, buf, 2, RS485_FLAG_NO_ACK);
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int EXPRT mscb_reset (int fd)
Definition at line 2068 of file mscb.c.
References buf, LPT_RESET, MCMD_INIT, mrpc_call(), mrpc_connected(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TYPE_LPT, MSCB_TYPE_USB, musb_close(), musb_init(), pp_wcontrol(), RPC_MSCB_RESET, RS485_FLAG_CMD, and type.
Referenced by cmd_loop(), mscb_out(), mscb_read(), mscb_read_range(), and server_execute().
         : mscb_reset
  Purpose: Reset submaster via hardware reset
  Input:
    int fd                  File descriptor for connection
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_RESET, mscb_fd[fd - 1].remote_fd);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   if (mscb_fd[fd - 1].type == MSCB_TYPE_LPT) {
      /* toggle reset */
      pp_wcontrol(fd, LPT_RESET, 1);
      Sleep(100);               // for elko
      pp_wcontrol(fd, LPT_RESET, 0);
   } else if (mscb_fd[fd - 1].type == MSCB_TYPE_USB) {
      char buf[10];
      buf[0] = MCMD_INIT;
      mscb_out(fd, buf, 1, RS485_FLAG_CMD);
      musb_close(mscb_fd[fd - 1].hr, mscb_fd[fd - 1].hw);
      Sleep(1000);
      musb_init(atoi(mscb_fd[fd - 1].device + 3), &mscb_fd[fd - 1].hr, &mscb_fd[fd - 1].hw);
   }
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int EXPRT mscb_select_device (char * data, int size, int select)
Definition at line 3438 of file mscb.c.
References i, lpt_close(), lpt_init(), MSCB_MAX_FD, MSCB_SUCCESS, MSCB_TYPE_LPT, musb_init(), n, strlcpy(), and MSCB_FD::type.
Referenced by mscb_init().
         : mscb_select_device
  Purpose: Select MSCB submaster device. Show dialog if sevral
           possibilities
  Input:
    none
  Output:
    char *device            Device name
    int  size               Size of device string buffer in bytes
    int  select             If 1, ask user which device to select,
                            if zero, use first device (for Labview)
  Function value:
    MSCB_SUCCESS            Successful completion
    0                       No submaster found
\********************************************************************/
{
   char list[10][256], str[256];
   int status, i, n, index, error_code;
   n = 0;
   *device = 0;
   error_code = 0;
   /* search for temporary file descriptor */
   for (index = 0; index < MSCB_MAX_FD; index++)
      if (mscb_fd[index].fd == 0)
         break;
   if (index == MSCB_MAX_FD)
      return -1;
   /* check USB devices */
   for (i = 0; i < 127; i++) {
      status = musb_init(i, NULL, NULL);
      if (status != -1)
         sprintf(list[n++], "usb%d", i);
      else
         break;
   }
   /* check LPT devices */
   for (i = 0; i < 1; i++) {
#ifdef _MSC_VER
      sprintf(str, "lpt%d", i + 1);
#else
      sprintf(str, "/dev/parport%d", i);
#endif
      mscb_fd[index].type = MSCB_TYPE_LPT;
      status = lpt_init(str, index);
      if (status < 0)
         error_code = status;
      else
         lpt_close(mscb_fd[index].fd);
      memset(&mscb_fd[index], 0, sizeof(MSCB_FD));
      if (status == 0)
         sprintf(list[n++], str);
      else
         break;
   }
   if (n == 0) {
      if (error_code == -3)
         printf("mscb.c: Cannot access parallel port (No DirectIO driver installed)\n");
      if (error_code == -4)
         printf("mscb.c: Cannot access parallel port, locked by other application\n");
      return 0;
   }
   /* if only one device, return it */
   if (n == 1 || select == 0) {
      strlcpy(device, list[0], size);
      return MSCB_SUCCESS;
   }
   do {
      printf("Found several submasters, please select one:\n\n");
      for (i = 0; i < n; i++)
         printf("%d: %s\n", i + 1, list[i]);
      printf("\n");
      fgets(str, sizeof(str), stdin);
      i = atoi(str);
      if (i > 0 && i <= n) {
         strlcpy(device, list[i - 1], size);
         return MSCB_SUCCESS;
      }
      printf("Invalid selection, please enter again\n");
   } while (1);
   return MSCB_SUCCESS;
}
int EXPRT mscb_set_addr (int fd, int adr, int node, int group)
Definition at line 2286 of file mscb.c.
References buf, crc8(), MCMD_PING16, MCMD_SET_ADDR, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_ADDR_EXISTS, MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, RPC_MSCB_SET_ADDR, RS485_FLAG_NO_ACK, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_set_addr
  Purpose: Set node and group address of an node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    int node                16-bit node address
    int group               16-bit group address
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   unsigned char buf[8];
   int status;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_SET_ADDR, mscb_fd[fd - 1].remote_fd, adr, node, group);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   /* check if destination address is alive */
   status = mscb_addr(fd, MCMD_PING16, node, 10, 0);
   if (status == MSCB_SUCCESS) {
      mscb_release(fd);
      return MSCB_ADDR_EXISTS;
   }
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_SET_ADDR;
   buf[1] = (unsigned char) (node >> 8);
   buf[2] = (unsigned char) (node & 0xFF);
   buf[3] = (unsigned char) (group >> 8);
   buf[4] = (unsigned char) (group & 0xFF);
   buf[5] = crc8(buf, 5);
   mscb_out(fd, buf, 6, RS485_FLAG_NO_ACK);
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int EXPRT mscb_set_name (int fd, int adr, char * name)
Definition at line 2345 of file mscb.c.
References buf, crc8(), i, MCMD_PING16, MCMD_SET_ADDR, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, RPC_MSCB_SET_NAME, RS485_FLAG_NO_ACK, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_set_name
  Purpose: Set node name
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    char *name              New node name, up to 16 characters
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   unsigned char buf[256];
   int status, i;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_SET_NAME, mscb_fd[fd - 1].remote_fd, adr, name);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_SET_ADDR | 0x07;
   for (i = 0; i < 16 && name[i]; i++)
      buf[2 + i] = name[i];
   if (i < 16)
      buf[2 + (i++)] = 0;
   buf[1] = i;                  /* varibale buffer length */
   buf[2 + i] = crc8(buf, 2 + i);
   mscb_out(fd, buf, 3 + i, RS485_FLAG_NO_ACK);
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int EXPRT mscb_upload (int fd, int adr, char * buffer, int size, int debug)
Definition at line 2686 of file mscb.c.
References buf, crc8(), d, i, MCMD_ACK, MCMD_PING16, MCMD_UPGRADE, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_FORMAT_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, ofs, RPC_MSCB_UPLOAD, RS485_FLAG_LONG_TO, RS485_FLAG_NO_ACK, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_upload
  Purpose: Upload new firmware to node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    char *filename          File name for Intel HEX file
    int debug               If true, produce detailed debugging output
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
    MSCB_FORMAT_ERROR       Error in HEX file format
\********************************************************************/
{
   unsigned char buf[512], crc, ack[2], image[0x10000], *line;
   unsigned int len, ofh, ofl, type, d;
   int i, status, page, flash_size, n_page, last_page, retry;
   unsigned short ofs;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_UPLOAD, mscb_fd[fd - 1].remote_fd, adr, buffer, size);
   /* interprete HEX file */
   memset(image, 0xFF, sizeof(image));
   line = buffer;
   flash_size = 0;
   do {
      if (line[0] == ':') {
         sscanf(line + 1, "%02x%02x%02x%02x", &len, &ofh, &ofl, &type);
         ofs = (ofh << 8) | ofl;
         for (i = 0; i < (int) len; i++) {
            sscanf(line + 9 + i * 2, "%02x", &d);
            image[ofs + i] = d;
         }
         flash_size += len;
         line = strchr(line, '\r') + 1;
         if (line && *line == '\n')
            line++;
      } else
         return MSCB_FORMAT_ERROR;
   } while (*line);
   if (debug) {
      /* count pages and byes */
      n_page = 0;
      last_page = -1;
      for (page = 0; page < 128; page++) {
         /* check if page contains data */
         for (i = 0; i < 512; i++) {
            if (image[page * 512 + i] != 0xFF) {
               if (page != last_page) {
                  last_page = page;
                  n_page++;
               }
            }
         }
      }
      printf("Found %d valid pages (%d bytes) in HEX file\n", n_page, flash_size);
   }
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   /* send upgrade command */
   buf[0] = MCMD_UPGRADE;
   crc = crc8(buf, 1);
   buf[1] = crc;
   mscb_out(fd, buf, 2, RS485_FLAG_LONG_TO);
   /* wait for ready, 1 sec timeout */
   if (mscb_in(fd, ack, 2, 1000000) != 2) {
      printf("Error: timeout receiving upgrade acknowledge from remote node\n");
      /* send exit upgrade command, in case node gets to upgrade routine later */
      buf[0] = 6;
      mscb_out(fd, buf, 1, RS485_FLAG_LONG_TO);
      mscb_release(fd);
      return MSCB_TIMEOUT;
   }
   if (debug)
      printf("Received acknowledge for upgrade command\n");
   /* program pages up to 64k */
   for (page = 0; page < 128; page++) {
      /* check if page contains data */
      for (i = 0; i < 512; i++)
         if (image[page * 512 + i] != 0xFF)
            break;
      retry = 0;
      if (i < 512) {
         do {
            if (debug)
               printf("Erase page   0x%04X - ", page * 512);
            else
               printf("E");
            fflush(stdout);
            /* erase page */
            buf[0] = 2;
            buf[1] = page;
            mscb_out(fd, buf, 2, RS485_FLAG_LONG_TO);
            if (mscb_in(fd, ack, 2, 100000) != 2) {
               printf("\nError: timeout from remote node for erase page 0x%04X\n", page * 512);
               goto prog_error;
            }
            if (ack[1] == 0xFF) {
               /* protected page, so finish */
               if (debug)
                  printf("found protected page, exit\n");
               else
                  printf("\bX");
               fflush(stdout);
               goto prog_error;
            }
            if (ack[0] != MCMD_ACK) {
               printf("\nError: received wrong acknowledge for erase page 0x%04X\n", page * 512);
               goto prog_error;
            }
            if (debug)
               printf("ok\n");
            if (debug)
               printf("Program page 0x%04X - ", page * 512);
            else
               printf("\bP");
            fflush(stdout);
            /* program page */
            buf[0] = 3;
            buf[1] = page;
            mscb_out(fd, buf, 2, RS485_FLAG_NO_ACK);
            for (i = crc = 0; i < 512; i++) {
               buf[i] = image[page * 512 + i];
               crc += buf[i];
            }
            /* chop down page in 60 byte segments (->USB) */
            for (i = 0; i < 8; i++) {
               mscb_out(fd, buf + i * 60, 60, RS485_FLAG_LONG_TO);
               /* read acknowledge */
               if (mscb_in(fd, ack, 2, 100000) != 2) {
                  printf("\nError: timeout from remote node for program page 0x%04X\n", page * 512);
                  goto prog_error;
               }
            }
            /* send remaining 32 bytes */
            mscb_out(fd, buf + i * 60, 32, RS485_FLAG_LONG_TO);
            /* read acknowledge */
            if (mscb_in(fd, ack, 2, 100000) != 2) {
               printf("\nError: timeout from remote node for program page 0x%04X\n", page * 512);
               goto prog_error;
            }
            if (ack[0] != MCMD_ACK) {
               printf("\nError: received wrong acknowledge for program page 0x%04X\n", page * 512);
               goto prog_error;
            }
            if (debug)
               printf("ok\n");
            /* verify page */
            if (debug)
               printf("Verify page  0x%04X - ", page * 512);
            else
               printf("\bV");
            fflush(stdout);
            /* verify page */
            buf[0] = 4;
            buf[1] = page;
            mscb_out(fd, buf, 2, RS485_FLAG_LONG_TO);
            if (mscb_in(fd, ack, 2, 100000) != 2) {
               printf("\nError: timeout from remote node for verify page 0x%04X\n", page * 512);
               goto prog_error;
            }
            /* compare CRCs */
            if (ack[1] == crc) {
               if (debug)
                  printf("ok (CRC = 0x%02X)\n", crc);
               break;
            }
            if (debug)
               printf("CRC error (0x%02X != 0x%02X)\n", crc, ack[1]);
            /* reprogram page until verified */
            retry++;
            if (retry == 10) {
               printf("\nToo many retries, aborting\n");
               goto prog_error;
               break;
            }
         } while (1);
         if (!debug)
            printf("\b=");
         fflush(stdout);
      }
   }
 prog_error:
   printf("\n");
   /* reboot node */
   buf[0] = 5;
   mscb_out(fd, buf, 1, RS485_FLAG_NO_ACK);
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int EXPRT mscb_user (int fd, int adr, void * param, int size, void * result, int * rsize)
Definition at line 3154 of file mscb.c.
References buf, crc8(), i, MCMD_PING16, MCMD_USER, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, MSCB_FORMAT_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, n, RPC_MSCB_USER, and type.
Referenced by server_execute().
         : mscb_user
  Purpose: Call user function on node
  Input:
    int  fd                 File descriptor for connection
    int adr                 Node address
    char *param             Parameters passed to user function, no CRC code
    int  size               Size of parameters in bytes
    int  *rsize             Size of result buffer
  Output:
    char *result            Optional return parameters
    int  *rsize             Number of returned size
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving data
    MSCB_CRC_ERROR          CRC error
    MSCB_MUTEX              Cannot obtain mutex for mscb
    MSCB_FORMAT_ERROR       "size" parameter too large
\********************************************************************/
{
   int i, n, status;
   unsigned char buf[80];
   memset(result, 0, *rsize);
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_USER,
                       mscb_fd[fd - 1].remote_fd, adr, param, size, result, rsize);
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   if (size > 4 || size < 0)
      return MSCB_FORMAT_ERROR;
   buf[0] = MCMD_USER + size;
   for (i = 0; i < size; i++)
      buf[1 + i] = ((char *) param)[i];
   /* add CRC code and send data */
   buf[1 + i] = crc8(buf, 1 + i);
   status = mscb_out(fd, buf, 2 + i, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   if (result == NULL) {
      mscb_release(fd);
      return MSCB_SUCCESS;
   }
   /* read result */
   n = mscb_in(fd, buf, sizeof(buf), 10000);
   mscb_release(fd);
   if (n < 0)
      return MSCB_TIMEOUT;
   if (rsize)
      *rsize = n - 2;
   for (i = 0; i < n - 2; i++)
      ((char *) result)[i] = buf[1 + i];
   if (buf[n - 1] != crc8(buf, n - 1))
      return MSCB_CRC_ERROR;
   return MSCB_SUCCESS;
}
int EXPRT mscb_write (int fd, int adr, unsigned char index, void * data, int size)
Definition at line 2461 of file mscb.c.
References buf, crc8(), d, i, MCMD_ACK, MCMD_PING16, MCMD_WRITE_ACK, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_CRC_ERROR, mscb_in(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, MSCB_TIMEOUT, RPC_MSCB_WRITE, and type.
Referenced by cmd_loop(), main(), mscb_link(), mscbdev_set(), and server_execute().
         : mscb_write
  Purpose: Write data to variable on single node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    unsigned char index     Variable index 0..255
    void *data              Data to send
    int size                Data size in bytes 1..4 for byte, word,
                            and dword
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, status;
   unsigned char buf[256], crc, ack[2];
   unsigned char *d;
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_WRITE, mscb_fd[fd - 1].remote_fd, adr, index, data, size);
   if (size < 1)
      return MSCB_INVAL_PARAM;
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   if (size < 6) {
      buf[0] = MCMD_WRITE_ACK + size + 1;
      buf[1] = index;
      /* reverse order for WORD & DWORD */
      if (size < 5)
         for (i = 0, d = data; i < size; i++)
            buf[2 + size - 1 - i] = *d++;
      else
         for (i = 0, d = data; i < size; i++)
            buf[2 + i] = *d++;
      crc = crc8(buf, 2 + i);
      buf[2 + i] = crc;
      mscb_out(fd, buf, 3 + i, 0);
   } else {
      buf[0] = MCMD_WRITE_ACK + 7;
      buf[1] = size + 1;
      buf[2] = index;
      for (i = 0, d = data; i < size; i++)
         buf[3 + i] = *d++;
      crc = crc8(buf, 3 + i);
      buf[3 + i] = crc;
      mscb_out(fd, buf, 4 + i, 0);
   }
   /* read acknowledge */
   i = mscb_in(fd, ack, 2, 10000);
   mscb_release(fd);
   if (i < 2)
      return MSCB_TIMEOUT;
   if (ack[0] != MCMD_ACK || ack[1] != crc)
      return MSCB_CRC_ERROR;
   return MSCB_SUCCESS;
}
int EXPRT mscb_write_block (int fd, int adr, unsigned char index, void * data, int size)
Definition at line 2549 of file mscb.c.
References buf, i, MCMD_PING16, MCMD_WRITE_BLOCK, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, n, RPC_MSCB_WRITE, RS485_FLAG_CMD, and type.
Referenced by cmd_loop().
         : mscb_write_block
  Purpose: Write block of data to single node
  Input:
    int fd                  File descriptor for connection
    int adr                 Node address
    unsigned char index     Variable index 0..255
    void *data              Data to send
    int size                Data size in bytes
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_TIMEOUT            Timeout receiving acknowledge
    MSCB_CRC_ERROR          CRC error
    MSCB_INVAL_PARAM        Parameter "size" has invalid value
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, n, status;
   unsigned char buf[1024];
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_WRITE, mscb_fd[fd - 1].remote_fd, adr, index, data, size);
   if (size < 1)
      return MSCB_INVAL_PARAM;
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_PING16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   /*
   Bulk test gave 128kb/sec, 10.3.04, SR
   for (i=0 ; i<1024 ; i++)
      buf[i] = RS485_FLAG_CMD;
   i = msend_usb(mscb_fd[fd - 1].hw, buf, 1024);
   mscb_release(fd);
   return MSCB_SUCCESS;
   */
   /* slice data in 60 byte blocks */
   for (i=0 ; i<=size/60 ; i++) {
      buf[0] = MCMD_WRITE_BLOCK;
      n = 60;
      if (size < (i+1)*60)
         n = size - i*60;
      if (n == 0)
         break;
      memcpy(buf+1, (char *)data+i*60, n);
      mscb_out(fd, buf, n+1, RS485_FLAG_CMD);
   }
   mscb_release(fd);
   return MSCB_SUCCESS;
}
int EXPRT mscb_write_group (int fd, int adr, unsigned char index, void * data, int size)
Definition at line 2401 of file mscb.c.
References buf, crc8(), d, i, MCMD_ADDR_GRP16, MCMD_WRITE_NA, mrpc_call(), mrpc_connected(), mscb_addr(), MSCB_INVAL_PARAM, mscb_lock(), MSCB_MAX_FD, MSCB_MUTEX, mscb_out(), mscb_release(), MSCB_SUCCESS, RPC_MSCB_WRITE_GROUP, RS485_FLAG_NO_ACK, and type.
Referenced by cmd_loop(), and server_execute().
         : mscb_write_na
  Purpose: Write data to channels on group of nodes
  Input:
    int fd                  File descriptor for connection
    int adr                 Group address
    unsigned char index     Variable index 0..255
    unsigned int  data      Data to send
    int size                Data size in bytes 1..4 for byte, word,
                            and dword
  Function value:
    MSCB_SUCCESS            Successful completion
    MSCB_MUTEX              Cannot obtain mutex for mscb
\********************************************************************/
{
   int i, status;
   unsigned char *d;
   unsigned char buf[256];
   if (fd > MSCB_MAX_FD || fd < 1 || !mscb_fd[fd - 1].type)
      return MSCB_INVAL_PARAM;
   if (mrpc_connected(fd))
      return mrpc_call(mscb_fd[fd - 1].fd, RPC_MSCB_WRITE_GROUP,
                       mscb_fd[fd - 1].remote_fd, adr, index, data, size);
   if (size > 4 || size < 1)
      return MSCB_INVAL_PARAM;
   if (mscb_lock(fd) != MSCB_SUCCESS)
      return MSCB_MUTEX;
   status = mscb_addr(fd, MCMD_ADDR_GRP16, adr, 10, 0);
   if (status != MSCB_SUCCESS) {
      mscb_release(fd);
      return status;
   }
   buf[0] = MCMD_WRITE_NA + size + 1;
   buf[1] = index;
   for (i = 0, d = data; i < size; i++)
      buf[2 + size - 1 - i] = *d++;
   buf[2 + i] = crc8(buf, 2 + i);
   mscb_out(fd, buf, 3 + i, RS485_FLAG_NO_ACK);
   mscb_release(fd);
   return MSCB_SUCCESS;
}
Variable Documentation
MSCB_FD mscb_fd[MSCB_MAX_FD]
Definition at line 286 of file mscb.c.