AlcapDAQ:Rootana: midas/mscb/embedded/mscbmain.c File Reference
midas/mscb/embedded/mscbmain.c File Reference
#include <stdio.h>
#include <string.h>
#include "mscb.h"
Defines
#define GET_INFO_GENERAL 0
#define GET_INFO_VARIABLE 1
#define SIZE_8BIT 1
#define SIZE_16BIT 2
#define SIZE_24BIT 3
#define SIZE_32BIT 4
#define ADDR_NONE 0
#define ADDR_NODE 1
#define ADDR_GROUP 2
#define ADDR_ALL 3
Functions
void user_init (unsigned char init)
void user_write (unsigned char index) reentrant
unsigned char user_read (unsigned char index)
void user_loop (void)
void rs232_output (void)
void watchdog_refresh (void)
void flash_upgrade (void)
void send_remote_var (unsigned char i)
void setup (void)
unsigned char cur_sub_addr ()
void debug_output ()
void interprete (void)
void serial_int (void)
static void send_byte (unsigned char d, unsigned char data *crc)
void addr_node8 (unsigned char mode, unsigned char adr, unsigned char node_addr)
void addr_node16 (unsigned char mode, unsigned int adr, unsigned int node_addr)
void upgrade ()
void yield (void)
void main (void)
Variables
MSCB_INFO_VAR code variables []
unsigned char idata _n_sub_addr
char code node_name []
bit lcd_present
unsigned char idata in_buf [20]
unsigned char idata out_buf [8]
unsigned char idata i_in
unsigned char idata last_i_in
unsigned char idata final_i_in
unsigned char idata n_out
unsigned char idata i_out
unsigned char idata cmd_len
unsigned char idata crc_code
unsigned char idata addr_mode
unsigned char idata n_variables
unsigned char idata _flkey = 0
unsigned char idata _cur_sub_addr
unsigned char idata _var_size
SYS_INFO sys_info
unsigned char bdata CSR
sbit DEBUG_MODE = CSR ^ 0
sbit SYNC_MODE = CSR ^ 1
sbit FREEZE_MODE = CSR ^ 2
sbit WD_RESET = CSR ^ 3
bit addressed
bit new_address
bit debug_new_i
bit debug_new_o
bit flash_param
bit flash_program
bit reboot
bit configured
bit flash_allowed
bit wrong_cpu
Define Documentation
#define ADDR_ALL 3
Definition at line 195 of file mscbmain.c.
Referenced by interprete().
#define ADDR_GROUP 2
Definition at line 194 of file mscbmain.c.
Referenced by interprete().
#define ADDR_NODE 1
Definition at line 193 of file mscbmain.c.
Referenced by interprete().
#define ADDR_NONE 0
Definition at line 192 of file mscbmain.c.
Referenced by addr_node16(), and addr_node8().
#define GET_INFO_GENERAL 0
Definition at line 182 of file mscbmain.c.
#define GET_INFO_VARIABLE 1
Definition at line 183 of file mscbmain.c.
#define SIZE_16BIT 2
Definition at line 187 of file mscbmain.c.
#define SIZE_24BIT 3
Definition at line 188 of file mscbmain.c.
#define SIZE_32BIT 4
Definition at line 189 of file mscbmain.c.
#define SIZE_8BIT 1
Definition at line 186 of file mscbmain.c.
Function Documentation
void addr_node16 (unsigned char mode, unsigned int adr, unsigned int node_addr)
Definition at line 679 of file mscbmain.c.
References _cur_sub_addr, _n_sub_addr, addr_mode, ADDR_NONE, and addressed.
Referenced by interprete().
{
   if (node_addr == 0xFFFF) {
      if (adr == node_addr) {
         addressed = 1;
         _cur_sub_addr = 0;
         addr_mode = mode;
      } else {
         addressed = 0;
         addr_mode = ADDR_NONE;
      }
   } else {
      if (adr >= node_addr &&
          adr <  node_addr + _n_sub_addr) {
         addressed = 1;
         _cur_sub_addr = adr - node_addr;
         addr_mode = mode;
      } else {
         addressed = 0;
         addr_mode = ADDR_NONE;
      }
   }
}
void addr_node8 (unsigned char mode, unsigned char adr, unsigned char node_addr)
Definition at line 665 of file mscbmain.c.
References _cur_sub_addr, _n_sub_addr, addr_mode, ADDR_NONE, and addressed.
Referenced by interprete().
{
   if (adr >= node_addr &&
       adr <  node_addr + _n_sub_addr) {
      addressed = 1;
      _cur_sub_addr = adr - node_addr;
      addr_mode = mode;
   } else {
      addressed = 0;
      addr_mode = ADDR_NONE;
   }
}
unsigned char cur_sub_addr (void)
Definition at line 532 of file mscbmain.c.
References _cur_sub_addr.
Referenced by user_write().
{
   return _cur_sub_addr;
}
void debug_output ()
Definition at line 538 of file mscbmain.c.
References cmd_len, DEBUG_MODE, debug_new_i, debug_new_o, i, i_in, in_buf, lcd_clear(), lcd_goto(), n, n_out, and out_buf.
Referenced by yield().
{
   if (!DEBUG_MODE)
      return;
#if !defined(CPU_ADUC812) && !defined(SCS_300) && !defined(SCS_210)     // SCS210/300 redefine printf()
#ifdef LCD_DEBUG
   {
      unsigned char i, n;
      if (debug_new_i) {
         debug_new_i = 0;
         lcd_clear();
         n = i_in ? i_in : cmd_len;
         for (i = 0; i < n; i++)
            printf("%02bX ", in_buf[i]);
      }
      if (debug_new_o) {
         debug_new_o = 0;
         lcd_goto(0, 1);
         for (i = 0; i < n_out; i++)
            printf("%02bX ", out_buf[i]);
      }
   }
#endif
#endif
}
void flash_upgrade (void)
void interprete (void)
Definition at line 704 of file mscbmain.c.
References _cur_sub_addr, _var_size, ADDR_ALL, ADDR_GROUP, ADDR_NODE, addr_node16(), addr_node8(), addressed, cmd, CMD_ACK, CMD_ADDR_BC, CMD_ADDR_GRP16, CMD_ADDR_GRP8, CMD_ADDR_NODE16, CMD_ADDR_NODE8, CMD_ECHO, CMD_FLASH, CMD_FREEZE, CMD_GET_INFO, CMD_INIT, CMD_PING16, CMD_PING8, CMD_READ, CMD_SET_ADDR, CMD_SET_BAUD, CMD_SYNC, CMD_UPGRADE, CMD_USER, CMD_WRITE_ACK, CMD_WRITE_NA, crc8(), CSR, ES0, flash_param, flash_program, FREEZE_MODE, SYS_INFO::group_addr, i, i_in, in_buf, j, led_blink(), MSCBF_DATALESS, n, n_out, n_variables, new_address, SYS_INFO::node_addr, SYS_INFO::node_name, out_buf, reboot, SBUF0, send_byte(), SFRPAGE, SYNC_MODE, UART0_PAGE, UNIT_STRING, user_func(), user_read(), user_write(), variables, VERSION, SYS_INFO::wd_counter, width, and MSCB_INFO_VAR::width.
Referenced by decode(), decode_get(), decode_post(), and serial_int().
{
   unsigned char crc, cmd, i, j, n, ch;
   MSCB_INFO_VAR code *pvar;
   cmd = (in_buf[0] & 0xF8);    // strip length field
#ifdef CPU_C8051F120
   SFRPAGE = UART0_PAGE;        // needed for SBUF0
#endif
   switch (in_buf[0]) {
   case CMD_ADDR_NODE8:
      addr_node8(ADDR_NODE, in_buf[1], sys_info.node_addr & 0xFF);
      break;
   case CMD_ADDR_NODE16:
      addr_node16(ADDR_NODE, *(unsigned int *) &in_buf[1], sys_info.node_addr);
      break;
   case CMD_ADDR_BC:
      addr_node8(ADDR_ALL, 0, 0);
      break;
   case CMD_ADDR_GRP8:
      addr_node8(ADDR_GROUP, in_buf[1], sys_info.group_addr & 0xFF);
      break;
   case CMD_ADDR_GRP16:
      addr_node16(ADDR_GROUP, *(unsigned int *) &in_buf[1], sys_info.group_addr);
      break;
   case CMD_PING8:
      addr_node8(ADDR_NODE, in_buf[1], sys_info.node_addr & 0xFF);
      if (addressed) {
         out_buf[0] = CMD_ACK;
         n_out = 1;
         RS485_ENABLE = 1;
         SBUF0 = CMD_ACK;
      }
      break;
   case CMD_PING16:
      addr_node16(ADDR_NODE, *(unsigned int *) &in_buf[1], sys_info.node_addr);
      if (addressed) {
         out_buf[0] = CMD_ACK;
         n_out = 1;
         RS485_ENABLE = 1;
         SBUF0 = CMD_ACK;
      }
      break;
   case CMD_INIT:
      reboot = 1;               // reboot in next main loop
      break;
   case CMD_GET_INFO:
      /* general info */
      ES0 = 0;                  // temporarily disable serial interrupt
      crc = 0;
      RS485_ENABLE = 1;
      send_byte(CMD_ACK + 7, &crc);     // send acknowledge, variable data length
      send_byte(24, &crc);      // send data length
      send_byte(VERSION, &crc); // send protocol version
      send_byte(n_variables, &crc);     // send number of variables
      send_byte(*(((unsigned char *) &sys_info.node_addr) + 0), &crc);  // send node address
      send_byte(*(((unsigned char *) &sys_info.node_addr) + 1), &crc);
      send_byte(*(((unsigned char *) &sys_info.group_addr) + 0), &crc); // send group address
      send_byte(*(((unsigned char *) &sys_info.group_addr) + 1), &crc);
      send_byte(*(((unsigned char *) &sys_info.wd_counter) + 0), &crc); // send watchdog resets
      send_byte(*(((unsigned char *) &sys_info.wd_counter) + 1), &crc);
      for (i = 0; i < 16; i++)  // send node name
         send_byte(sys_info.node_name[i], &crc);
      send_byte(crc, NULL);     // send CRC code
      RS485_ENABLE = 0;
      ES0 = 1;                  // re-enable serial interrupts
      break;
   case CMD_GET_INFO + 1:
      /* send variable info */
      if (in_buf[1] < n_variables) {
         pvar = variables + in_buf[1];
         ES0 = 0;               // temporarily disable serial interrupt
         crc = 0;
         RS485_ENABLE = 1;
         send_byte(CMD_ACK + 7, &crc);  // send acknowledge, variable data length
         send_byte(13, &crc);   // send data length
         send_byte(pvar->width, &crc);
         send_byte(pvar->unit, &crc);
         send_byte(pvar->prefix, &crc);
         send_byte(pvar->status, &crc);
         send_byte(pvar->flags, &crc);
         for (i = 0; i < 8; i++)        // send variable name
            send_byte(pvar->name[i], &crc);
         send_byte(crc, NULL);  // send CRC code
         RS485_ENABLE = 0;
         ES0 = 1;               // re-enable serial interrupts
      }
      break;
   case CMD_SET_ADDR:
      led_blink(_cur_sub_addr, 1, 50);
      /* set address in RAM */
      sys_info.node_addr = *((unsigned int *) (in_buf + 1));
      sys_info.group_addr = *((unsigned int *) (in_buf + 3));
      /* copy address to EEPROM */
      flash_param = 1;
      /* output new address */
      new_address = 1;
      break;
   case (CMD_SET_ADDR | 0x07):
      led_blink(_cur_sub_addr, 1, 50);
      /* set node name in RAM */
      for (i = 0; i < 16 && i < in_buf[1]; i++)
         sys_info.node_name[i] = in_buf[2 + i];
      /* copy address to EEPROM */
      flash_param = 1;
      /* output new address */
      new_address = 1;
      break;
   case CMD_SET_BAUD:
      led_blink(_cur_sub_addr, 1, 50);
      //uart_init(0, in_buf[1]);
      break;
   case CMD_FREEZE:
      FREEZE_MODE = in_buf[1];
      break;
   case CMD_SYNC:
      SYNC_MODE = in_buf[1];
      break;
   case CMD_UPGRADE:
      flash_program = 1;
      /* acknowledge gets sent from upgrade() routine */
      break;
   case CMD_FLASH:
      led_blink(_cur_sub_addr, 1, 50);
      flash_param = 1;
      /* send acknowledge */
      out_buf[0] = CMD_ACK;
      out_buf[1] = in_buf[i_in - 1];
      n_out = 2;
      RS485_ENABLE = 1;
      SBUF0 = out_buf[0];
      break;
   case CMD_ECHO:
      led_blink(0, 1, 50);
      out_buf[0] = CMD_ACK + 1;
      out_buf[1] = in_buf[1];
      out_buf[2] = crc8(out_buf, 2);
      n_out = 3;
      RS485_ENABLE = 1;
      SBUF0 = out_buf[0];
      break;
   }
   if (cmd == CMD_READ) {
      if (in_buf[0] == CMD_READ + 1) {  // single variable
         if (in_buf[1] < n_variables) {
            n = variables[in_buf[1]].width;     // number of bytes to return
            if (variables[in_buf[1]].flags & MSCBF_DATALESS) {
               n = user_read(in_buf[1]);        // for dataless variables, user routine returns bytes
               out_buf[0] = CMD_ACK + n;        // and places data directly in out_buf
               out_buf[1 + n] = crc8(out_buf, 1 + n);      // generate CRC code
               /* send result */
#ifdef CPU_C8051F120
               SFRPAGE = UART0_PAGE;
#endif
               n_out = 2 + n;
               RS485_ENABLE = 1;
               SBUF0 = out_buf[0];
            } else {
               user_read(in_buf[1]);
               ES0 = 0;            // temporarily disable serial interrupt
               crc = 0;
               RS485_ENABLE = 1;
               if (n > 6) {
                  /* variable length buffer */
                  send_byte(CMD_ACK + 7, &crc);       // send acknowledge, variable data length
                  send_byte(n, &crc); // send data length
                  for (i = 0; i < n; i++)           // copy user data
                     send_byte(((char *) variables[in_buf[1]].ud)[i+_var_size*_cur_sub_addr], &crc);
                  n++;
               } else {
                  send_byte(CMD_ACK + n, &crc);       // send acknowledge
                  for (i = 0; i < n; i++)           // copy user data
                     send_byte(((char *) variables[in_buf[1]].ud)[i+_var_size*_cur_sub_addr], &crc);
               }
               send_byte(crc, NULL);       // send CRC code
               RS485_ENABLE = 0;
               ES0 = 1;            // re-enable serial interrupts
            }
         }
      } else if (in_buf[0] == CMD_READ + 2) {   // variable range
        if (in_buf[1] < n_variables && in_buf[2] < n_variables && in_buf[1] < in_buf[2]) {
            /* calculate number of bytes to return */
            for (i = in_buf[1], n = 0; i <= in_buf[2]; i++) {
               user_read(i);
               n += variables[i].width;
            }
            ES0 = 0;            // temporarily disable serial interrupt
            crc = 0;
            RS485_ENABLE = 1;
            send_byte(CMD_ACK + 7, &crc);       // send acknowledge, variable data length
            send_byte(n, &crc); // send data length
            /* loop over all variables */
            for (i = in_buf[1]; i <= in_buf[2]; i++) {
               for (j = 0; j < variables[i].width; j++)    // send user data
                  send_byte(((char *) variables[i].ud)[j+_var_size*_cur_sub_addr], &crc);
            }
            send_byte(crc, NULL);       // send CRC code
            RS485_ENABLE = 0;
            ES0 = 1;            // re-enable serial interrupts
         }
      }
   }
   if (cmd == CMD_USER) {
      led_blink(_cur_sub_addr, 1, 50);
      n = user_func(in_buf + 1, out_buf + 1);
      out_buf[0] = CMD_ACK + n;
      out_buf[n + 1] = crc8(out_buf, n + 1);
      n_out = n + 2;
#ifdef CPU_C8051F120
      SFRPAGE = UART0_PAGE;
#endif
      RS485_ENABLE = 1;
      SBUF0 = out_buf[0];
   }
   if (cmd == CMD_WRITE_NA || cmd == CMD_WRITE_ACK) {
      /* blink LED once when writing data */
      led_blink(_cur_sub_addr, 1, 50);
      n = in_buf[0] & 0x07;
      if (n == 0x07) {  // variable length
         j = 1;
         n = in_buf[1];
         ch = in_buf[2];
      } else {
         j = 0;
         ch = in_buf[1];
      }
      n--; // data size (minus channel)
      if (ch < n_variables) {
         /* don't exceed variable width */
         if (n > variables[ch].width)
            n = variables[ch].width;
         for (i = 0; i < n; i++)
            if (!(variables[ch].flags & MSCBF_DATALESS)) {
               if (variables[ch].unit == UNIT_STRING) {
                  if (n > 4)
                     /* copy bytes in normal order */
                     ((char *) variables[ch].ud)[i + _var_size*_cur_sub_addr] =
                        in_buf[2 + j + i];
                  else
                     /* copy bytes in reverse order (got swapped on host) */
                     ((char *) variables[ch].ud)[i + _var_size*_cur_sub_addr] =
                        in_buf[i_in - 2 - i];
               } else
                  /* copy LSB bytes, needed for BYTE if DWORD is sent */
                  ((char *) variables[ch].ud)[i + _var_size*_cur_sub_addr] =
                        in_buf[i_in - 1 - variables[ch].width + i + j];
            }
         user_write(ch);
#ifdef SCS_1000
         /* mark variable to be send in main loop */
         var_to_send = ch;
#endif
         if (cmd == CMD_WRITE_ACK) {
            out_buf[0] = CMD_ACK;
            out_buf[1] = in_buf[i_in - 1];
            n_out = 2;
#ifdef CPU_C8051F120
            SFRPAGE = UART0_PAGE;
#endif
            RS485_ENABLE = 1;
            SBUF0 = out_buf[0];
         }
      } else if (ch == 0xFF) {
         CSR = in_buf[2];
         if (cmd == CMD_WRITE_ACK) {
            out_buf[0] = CMD_ACK;
            out_buf[1] = in_buf[i_in - 1];
            n_out = 2;
#ifdef CPU_C8051F120
            SFRPAGE = UART0_PAGE;
#endif
            RS485_ENABLE = 1;
            SBUF0 = out_buf[0];
         }
      }
   }
}
void main (void)
Definition at line 1447 of file mscbmain.c.
References setup(), user_loop(), and yield().
{
   setup();
   do {
      yield();
      user_loop();
   } while (1);
}
void rs232_output (void)
Definition at line 509 of file mscbutil.c.
Referenced by yield().
{
}
static void send_byte (unsigned char d, unsigned char data * crc) [static]
Definition at line 652 of file mscbmain.c.
References crc8_add(), SBUF0, SFRPAGE, TI0, and UART0_PAGE.
Referenced by enter(), interprete(), send(), user_init(), and user_loop().
{
#ifdef CPU_C8051F120
   SFRPAGE = UART0_PAGE;
#endif
   if (crc)
      *crc = crc8_add(*crc, d);
   SBUF0 = d;
   while (!TI0);
   TI0 = 0;
}
void send_remote_var (unsigned char i)
void serial_int (void)
Definition at line 577 of file mscbmain.c.
References addressed, cmd_len, crc8(), debug_new_i, debug_new_o, i_in, i_out, in_buf, interprete(), n_out, out_buf, RB80, RI0, SBUF0, and TI0.
{
   if (TI0) {
      /* character has been transferred */
      TI0 = 0;                  // clear TI flag
      i_out++;                  // increment output counter
      if (i_out == n_out) {
         i_out = 0;             // send buffer empty, clear pointer
         RS485_ENABLE = 0;      // disable RS485 driver
         debug_new_o = 1;       // indicate new debug output
      } else {
         SBUF0 = out_buf[i_out];        // send character
      }
   }
   if (RI0) {
      /* character has been received */
      if (!RB80 && !addressed) {
         RI0 = 0;
         i_in = 0;
         return;                // discard data if not bit9 and not addressed
      }
      RB80 = 0;
      in_buf[i_in++] = SBUF0;
      RI0 = 0;
      if (i_in == 1) {
         /* check for padding character */
         if (in_buf[0] == 0) {
            i_in = 0;
            return;
         }
         /* initialize command length if first byte */
         cmd_len = (in_buf[0] & 0x07) + 2;      // + cmd + crc
      }
      if (i_in == 2 && cmd_len == 9) {
         /* variable length command */
         cmd_len = in_buf[1] + 3;       // + cmd + N + crc
      }
      debug_new_i = 1;          // indicate new data in input buffer
      if (i_in == sizeof(in_buf))       // check for buffer overflow
      {
         i_in = 0;
         return;                // don't interprete command
      }
      if (i_in < cmd_len)       // return if command not yet complete
         return;
      if (in_buf[i_in - 1] != crc8(in_buf, i_in - 1)) {
         i_in = 0;
         return;                // return if CRC code does not match
      }
      interprete();             // interprete command
      i_in = 0;
   }
}
void setup (void)
Definition at line 263 of file mscbmain.c.
References _cur_sub_addr, _flkey, _n_sub_addr, _var_size, addressed, BD_115200, CLKSEL, CONFIG_PAGE, configured, CSR, eeprom_retrieve(), flash_allowed, flash_param, flash_program, FLSCL, SYS_INFO::group_addr, i, i_in, i_out, in_buf, lcd_present, lcd_setup(), led_blink(), led_mode(), LEGACY_PAGE, MSCBF_DATALESS, MSCBF_REMOUT, N_LED, n_out, n_variables, SYS_INFO::node_addr, node_name, SYS_INFO::node_name, OSCICN, OSCXCN, out_buf, p, P0MDIN, P0MDOUT, P0SKIP, P1MDOUT, P2MDOUT, P3MDOUT, PCA0CPL4, PCA0MD, PLL0CN, PLL0DIV, PLL0FLT, PLL0MUL, PRT0CF, PRT1CF, PRT2CF, PRT3CF, reboot, RSTSRC, send_remote_var(), SFRPAGE, sysclock_init(), uart_init(), MSCB_INFO_VAR::ud, user_init(), variables, watchdog_refresh(), SYS_INFO::wd_counter, WD_RESET, WDTCN, width, MSCB_INFO_VAR::width, wrong_cpu, XBR0, XBR1, and XBR2.
Referenced by main().
{
   unsigned char adr;
   unsigned short i;
   unsigned char *p;
   _flkey = 0;
   /* first disable watchdog */
#ifdef CPU_CYGNAL
#if defined(CPU_C8051F310)
   PCA0MD = 0x00;
#else
   WDTCN = 0xDE;
   WDTCN = 0xAD;
#endif
#else /* CPU_CYGNAL */
#endif
#ifdef CPU_CYGNAL
   /* Port and oscillator configuration */
#if defined(CPU_C8051F120)
   SFRPAGE   = CONFIG_PAGE;
   P0MDOUT = 0xF5;              // SCS-1000 lines
   P1MDOUT = 0xBF;
   P2MDOUT = 0x00;
   P3MDOUT = 0xFF;
   XBR0 = 0x04;                 // Enable UART0 & UART1
   XBR1 = 0x00;
   XBR2 = 0x44;
   /* Select internal quartz oscillator */
   SFRPAGE   = LEGACY_PAGE;
   FLSCL     = 0xB0;            // set flash read time for 100 MHz
   SFRPAGE   = CONFIG_PAGE;
   PLL0CN    |= 0x01;
   PLL0DIV   = 0x01;
   PLL0FLT   = 0x01;
   PLL0MUL   = 0x04;
   for (i = 0; i < 15; i++);   // Wait 5us for initialization
   PLL0CN    |= 0x02;
   while ((PLL0CN & 0x10) == 0);
   OSCICN    = 0x83;
   CLKSEL    = 0x02;            // select PLL as sysclk src
#elif defined(CPU_C8051F020)
   XBR0 = 0x04;                 // Enable UART0 & UART1
   XBR1 = 0x00;
   XBR2 = 0x44;
   P0MDOUT = 0x01;              // P0.0: TX = Push Pull
   P1MDOUT = 0x00;              // P1: LPT
   P2MDOUT = 0x00;              // P2: LPT
   P3MDOUT = 0xE0;              // P3.5,6,7: Optocouplers
   /* Select external quartz oscillator */
   OSCXCN = 0x67;               // Crystal mode, Power Factor 22E6
   OSCICN = 0x08;               // CLKSL=1 (external)
#elif defined(CPU_C8051F310)
   XBR0 = 0x01;                 // Enable RX/TX
   XBR1 = 0x40;                 // Enable crossbar
   P0MDOUT = 0x90;              // P0.4: TX, P0.7: RS485 enable Push/Pull
   P0SKIP  = 0x0C;              // Skip P0.2&3 for Xtal
   P0MDIN  = 0xF3;              // P0.2&3 as analog input for Xtal
   /* Select external quartz oscillator */
   OSCXCN = 0x67;
   for (i=0 ; i<255 ; i++);
   while ((OSCXCN & 0x80) == 0);
   CLKSEL = 0x01;               // derive SYSCLK from external source
   OSCICN = 0x00;               // CLKSL=1 (external)
#else
   XBR0 = 0x04;                 // Enable RX/TX
   XBR1 = 0x00;
   XBR2 = 0x40;                 // Enable crossbar
   PRT0CF = 0x01;               // P0.0: TX = Push Pull
   PRT1CF = 0x00;               // P1
   PRT2CF = 0x00;               // P2  Open drain for 5V LCD
   PRT3CF = 0x20;               // P3.5: RS485 enable = Push Pull
   /* Select external quartz oscillator */
   OSCXCN = 0x67;               // Crystal mode, Power Factor 22E6
   OSCICN = 0x08;               // CLKSL=1 (external)
#endif
#endif
   /* enable watchdog */
#ifdef CPU_ADUC812
#ifdef USE_WATCHDOG
   WDCON = 0xE0;                // 2048 msec
   WDE = 1;
#endif
#endif
#ifdef CPU_CYGNAL
#if defined(CPU_C8051F310)
#ifdef USE_WATCHDOG
   PCA0CPL4 = 255;              // 71.1 msec
   PCA0MD = 0x40;               // enable watchdog
#endif
   /* enable reset pin and watchdog reset */
   RSTSRC = 0x09;
#else /* CPU_C8051F310 */
#ifdef USE_WATCHDOG
   WDTCN = 0x07;                // 95 msec
   WDTCN = 0xA5;                // start watchdog
#else
   WDTCN = 0xDE;                // disable watchdog
   WDTCN = 0xAD;
#endif
#if defined(CPU_C8051F120)
   SFRPAGE = LEGACY_PAGE;
   RSTSRC = 0x04;               // enable missing clock detector
#else /* F120 */
   /* enable missing clock reset */
   OSCICN |= 0x80;              // MSCLKE = 1
   /* enable watchdog reset */
   RSTSRC = 0x08;
#endif /* not F120 */
#endif /* not F310 */
#endif /* CPU_CYGNAL */
   /* start system clock */
   sysclock_init();
   /* default LED mode */
   for (i=0 ; i<N_LED ; i++)
      led_mode(i, 1);
   /* initialize all memory */
   CSR = 0;
   addressed = 0;
   flash_param = 0;
   flash_program = 0;
   reboot = 0;
   configured = 1;
   flash_allowed = 0;
   wrong_cpu = 0;
   RS485_ENABLE = 0;
   i_in = i_out = n_out = 0;
   _cur_sub_addr = 0;
   for (i=0 ; i<sizeof(in_buf) ; i++)
      in_buf[i] = 0;
   for (i=0 ; i<sizeof(out_buf) ; i++)
      out_buf[i] = 0;
   /* initialize UART(s) */
   uart_init(0, BD_115200);
#ifdef SCS_1000
   uart_init(1, BD_115200);
#endif
#ifdef LCD_SUPPORT
   lcd_setup();
#ifdef LCD_DEBUG
   if (lcd_present) {
      printf("AD:%04X GA:%04X WD:%d", sys_info.node_addr,
             sys_info.group_addr, sys_info.wd_counter);
   }
#endif
#endif
   /* count variables */
   for (n_variables = _var_size = 0;; n_variables++) {
      _var_size += variables[n_variables].width;
      if (variables[n_variables].width == 0)
         break;
   }
   /* check if variables are in xdata and xdata is present */
   if (n_variables > 0) {
      p = variables[0].ud;
      *p = 0x55;
      if (*p != 0x55)
         wrong_cpu = 1;
      *p = 0xAA;
      if (*p != 0xAA)
         wrong_cpu = 1;
   }
   /* retrieve EEPROM data */
   if (!eeprom_retrieve()) {
      configured = 0;
      /* correct initial value */
      sys_info.node_addr = 0xFFFF;
      sys_info.group_addr = 0xFFFF;
      sys_info.wd_counter = 0;
      memset(sys_info.node_name, 0, sizeof(sys_info.node_name));
      strncpy(sys_info.node_name, node_name, sizeof(sys_info.node_name));
      /* init variables */
      for (i = 0; variables[i].width; i++)
         if (!(variables[i].flags & MSCBF_DATALESS)) {
            /* do it for each sub-address */
            for (adr = 0 ; adr < _n_sub_addr ; adr++) {
               memset((char*)variables[i].ud + _var_size*adr, 0, variables[i].width);
               watchdog_refresh();
            }
#ifdef SCS_1000
            if (variables[i].flags & MSCBF_REMOUT)
               send_remote_var(i);
#endif
         }
      /* call user initialization routine with initialization */
      user_init(1);
           /* do flash programming later (>3sec after reboot) */
      //flash_param = 1;
   } else {
      /* remember configured flag */
      configured = 1;
      /* call user initialization routine without initialization */
      user_init(0);
   /* check if reset by watchdog */
#ifdef CPU_ADUC812
      if (WDS)
#endif
#ifdef CPU_CYGNAL
       if (RSTSRC & 0x08)
#endif
         {
         WD_RESET = 1;
         sys_info.wd_counter++;
           /* do flash programming later (>3sec after reboot) */
         //flash_param = 1;
      }
   }
   /* Blink LEDs */
   for (i=0 ; i<N_LED ; i++)
      led_blink(i, 3, 150);
}
void upgrade ()
Definition at line 1140 of file mscbmain.c.
References cmd, CMD_ACK, EA, FLKEY, FLSCL, j, k, LED_OFF, LEGACY_PAGE, PCA0MD, PSCTL, RI0, RSTSRC, SBUF0, SFRPAGE, TI0, UART0_PAGE, and WDTCN.
Referenced by yield().
{
#ifdef CPU_CYGNAL
   unsigned char cmd, page, crc, j, k;
   unsigned short i;
   unsigned char xdata *pw;
   unsigned char code *pr;
   /* disable all interrupts */
   EA = 0;
   /* disable watchdog */
#if defined(CPU_C8051F310)
   PCA0MD = 0x00;
#else
   WDTCN = 0xDE;
   WDTCN = 0xAD;
#endif
   cmd = page = 0;
   /* send acknowledge */
#ifdef CPU_C8051F120
   SFRPAGE = UART0_PAGE;
#endif
   RS485_ENABLE = 1;
   TI0 = 0;
   SBUF0 = CMD_ACK;
   while (TI0 == 0);
   TI0 = 0;
   SBUF0 = 0; // dummy CRC
   while (TI0 == 0);
   RS485_ENABLE = 0;
   do {
      /* receive command */
      while (!RI0);
      cmd = SBUF0;
      RI0 = 0;
      crc = 0;
      switch (cmd) {
      case 1:                      // return acknowledge
         break;
      case 2:                      // erase page
         /* receive page */
         while (!RI0);
         page = SBUF0;
         RI0 = 0;
         /* erase page if not page of upgrade() function */
         if (page * 512 < (unsigned int)upgrade) {
#ifdef CPU_C8051F120
            SFRPAGE = LEGACY_PAGE;
#endif
#if defined(CPU_C8051F000)
            FLSCL = (FLSCL & 0xF0) | 0x08; // set timer for 11.052 MHz clock
#elif defined (CPU_C8051F020) || defined(CPU_C8051F120)
            FLSCL = FLSCL | 1;     // enable flash writes
#endif
            PSCTL = 0x03;          // allow write and erase
            pw = (char xdata *) (512 * page);
#if defined(CPU_C8051F310)
            FLKEY = 0xA5;          // write flash key code
            FLKEY = 0xF1;
#endif
            *pw = 0;
            FLSCL = (FLSCL & 0xF0);
            PSCTL = 0x00;
         } else {
            crc = 0xFF;            // return 'protected' flag
         }
         break;
      case 3:                      // program page
#ifdef LED_0
         led_0 = LED_OFF;
#endif
         /* receive page */
         while (!RI0);
         page = SBUF0;
         RI0 = 0;
#ifdef CPU_C8051F120
         SFRPAGE = LEGACY_PAGE;
#endif
         /* allow write */
#if defined(CPU_C8051F000)
         FLSCL = (FLSCL & 0xF0) | 0x08; // set timer for 11.052 MHz clock
#elif defined (CPU_C8051F020) || defined(CPU_C8051F120)
         FLSCL = FLSCL | 1;        // enable flash writes
#endif
         PSCTL = 0x01;             // allow write access
         pw = (char xdata *) (512 * page);
#ifdef CPU_C8051F120
         SFRPAGE = UART0_PAGE;
#endif
         for (j=0 ; j<8 ; j++) {
            /* receive 60 bytes */
            for (k = 0; k < 60; k++) {
               /* receive byte */
               while (!RI0);
#if defined(CPU_C8051F310)
               FLKEY = 0xA5;          // write flash key code
               FLKEY = 0xF1;
#endif
               /* flash byte */
               *pw++ = SBUF0;
               RI0 = 0;
            }
            /* send ACK after each 60 bytes */
            RS485_ENABLE = 1;
            TI0 = 0;
            SBUF0 = CMD_ACK;
            while (TI0 == 0);
            TI0 = 0;
            SBUF0 = 0;
            while (TI0 == 0);
            RS485_ENABLE = 0;
         }
         /* receive remaining 32 bytes */
         for (k = 0; k < 32; k++) {
            /* receive byte */
            while (!RI0);
#if defined(CPU_C8051F310)
            FLKEY = 0xA5;          // write flash key code
            FLKEY = 0xF1;
#endif
            /* flash byte */
            *pw++ = SBUF0;
            RI0 = 0;
         }
#ifdef CPU_C8051F120
         SFRPAGE = LEGACY_PAGE;
#endif
         /* disable write */
         FLSCL = (FLSCL & 0xF0);
         PSCTL = 0x00;
         break;
      case 4:                      // verify page
#ifdef LED_0
         led_0 = LED_ON;
#endif
         /* receive page */
         while (!RI0);
         page = SBUF0;
         RI0 = 0;
         pr = 512 * page;
         /* return simplified CRC */
         for (i = crc = 0; i < 512; i++)
            crc += *pr++;
         break;
      case 5:                      // reboot
#ifdef CPU_C8051F120
         SFRPAGE = LEGACY_PAGE;
#endif
         RSTSRC = 0x10;
         break;
      case 6:                      // return
         break;
      }
#ifdef CPU_C8051F120
      SFRPAGE = UART0_PAGE;
#endif
      /* return acknowledge */
      RS485_ENABLE = 1;
      TI0 = 0;
      SBUF0 = CMD_ACK;
      while (TI0 == 0);
      TI0 = 0;
      SBUF0 = crc;
      while (TI0 == 0);
      RS485_ENABLE = 0;
   } while (cmd != 6);
   EA = 1;                      // re-enable interrupts
#endif                          // CPU_CYGNAL
}
void user_init (unsigned char init)
Definition at line 192 of file hvr_200.c.
References ADC0_PAGE, ADC0CF, ADC0CN, adc_chn, ADC_DIN, ADC_NRDY, ADC_NRES, ADC_SF_VALUE, AMX0CF, chn_bits, CONFIG_PAGE, CONTROL_REGULATION, CUR_LIMIT_CHANGED, DAC0_PAGE, DAC0CN, DAC1_PAGE, DAC1CN, DAC_CLR, delay_ms(), demand_changed, DEMAND_CHANGED, for(), GPIB_ATN, GPIB_DATA, GPIB_DAV, GPIB_EOI, GPIB_IFC, GPIB_NDAC, GPIB_NRFD, GPIB_REM, GPIB_SRQ, i, i_limit_adc, i_limit_changed, JU1, JU2, lcd_goto(), led_mode(), LEGACY_PAGE, LPT_ACK, LPT_BUSY, LPT_DATA, LPT_INIT, LPT_SELECT, LPT_STROBE, N_CHANNEL, N_HV_CHN, SYS_INFO::node_addr, SYS_INFO::node_name, output, output_flag, P0, P0MDOUT, P1, P1MDOUT, P2MDOUT, P3MDOUT, PRT0CF, PRT1CF, REF0CN, REG_CONTROL, REG_FILTER, REG_MODE, send_byte(), ser_clock(), SET_ADDR, SFRPAGE, SR_CLOCK, SR_DATAI, SR_DATAO, SR_OE, tc600_write(), terminal_mode, uart_init(), UNI_ADC, UNI_DAC, user_data, user_write(), VALVE, and write_adc().
{
   unsigned char i;
   P2MDOUT = 0xF0; // P2.4-7: enable Push/Pull for LEDs
   SET_ADDR = 1;   // use button as input
   /* initial nonzero EEPROM values */
   if (init) {
      for (i=0 ; i<N_HV_CHN ; i++) {
         user_data[i].v_demand = 0;
         user_data[i].trip_cnt = 0;
         user_data[i].ramp_up = 0;
         user_data[i].ramp_down = 0;
         user_data[i].v_limit = 3000;
         user_data[i].i_limit = 3000;
         user_data[i].trip_max = 0;
         user_data[i].adc_gain = 1;
         user_data[i].adc_offset = 0;
         user_data[i].dac_gain = 1;
         user_data[i].dac_offset = 0;
         user_data[i].cur_gain = 1;
         user_data[i].cur_offset = 0;
      }
   }
   /* default control register */
   for (i=0 ; i<N_HV_CHN ; i++) {
      user_data[i].control = CONTROL_REGULATION;
      user_data[i].status = 0;
      user_data[i].temperature = 0;
   }
   JU1 = 1;
   JU2 = 1;
   /* set-up DAC & ADC */
   DAC_CLR = 1;
   ADC_NRES = 1;
   ADC_NRDY = 1; // input
   ADC_DIN = 1;  // input
   write_adc(REG_FILTER, ADC_SF_VALUE);
   /* force update */
   for (i=0 ; i<N_HV_CHN ; i++)
      chn_bits[i] = DEMAND_CHANGED | CUR_LIMIT_CHANGED;
   /* LED normally off (non-inverted) */
   for (i=0 ; i<N_HV_CHN ; i++)
      led_mode(i, 0);
}
void user_loop (void)
Definition at line 853 of file hvr_200.c.
References adc_chn, adc_read(), c, cap_read(), channel, check_current(), control, control_flag, CONTROL_IDLE, DEBUG_MODE, delay_ms(), demand_changed, DISABLE_INTERRUPTS, ENABLE_INTERRUPTS, enter(), EWD, flush(), for(), FREEZE_MODE, gain_flag, getchar_nowait(), gets_wait(), GPIB_ATN, i, last, lcd_clear(), lcd_goto(), lcd_menu(), led_blink(), n, n_in, output_flag, putchar(), ramp_hv(), read_current(), read_hv(), read_temperature(), regulation(), send(), send_byte(), ser_clock(), set_power(), sr_read(), tbwp, tc600_read(), tc600_write(), term_buf, term_flag, terminal_mode, time, user_data, write_gain(), and yield().
Referenced by main().
{
   unsigned char channel;
   /* loop over all HV channels */
   for (channel=0 ; channel<N_HV_CHN ; channel++) {
      if ((user_data[0].control & CONTROL_IDLE) == 0) {
         /* outcommented until implemented in HW
         if (chn_bits[channel] & CUR_LIMIT_CHANGED) {
            set_current_limit(user_data[channel].i_limit);
            chn_bits[channel] &= ~CUR_LIMIT_CHANGED;
         }
         */
         /* instead, use software limit */
         check_current(channel);
         read_hv(channel);
         ramp_hv(channel);
         regulation(channel);
         read_current(channel);
      }
   }
   // read_temperature();
}
unsigned char user_read (unsigned char index)
Definition at line 269 of file hvr_200.c.
References c, getchar_nowait(), out_buf, P1, tbrp, tbwp, term_buf, term_flag, terminal_mode, and user_data.
Referenced by interprete().
{
   if (index);
   return 0;
}
void user_write (unsigned char index)
Definition at line 251 of file hvr_200.c.
References chn_bits, control_flag, CONTROL_HV_ON, cur_sub_addr(), d, DAC0_PAGE, DAC0H, DAC0L, DAC1_PAGE, DAC1H, DAC1L, dac_write(), data, demand_changed, DEMAND_CHANGED, demand_changed_time, DOUT0, DOUT1, DOUT2, DOUT3, gain_flag, i, i_limit_changed, in_buf, index, moving_x, moving_y, n, output_flag, P1, putchar(), RELAIS0, RELAIS1, RELAIS2, RELAIS3, SFRPAGE, STATUS_ILIMIT, tbrp, tbwp, term_buf, term_flag, terminal_mode, time, uart_init(), UNI_BIP, user_data, v_actual, VALVE, write_dac(), and write_gain().
Referenced by application_display(), interprete(), lcd_menu(), and user_init().
{
   if (index == 0 || index == 1 || index == 4) {
      /* reset trip */
      user_data[cur_sub_addr()].status &= ~STATUS_ILIMIT;
      /* indicate new demand voltage */
      chn_bits[cur_sub_addr()] |= DEMAND_CHANGED;
   }
   /* re-check voltage limit */
   if (index == 8) {
      chn_bits[cur_sub_addr()] |= DEMAND_CHANGED;
   }
}
void watchdog_refresh (void)
Definition at line 862 of file mscbutil.c.
         : watchdog_refresh
  Purpose: Refresh watchdog, has to be called regularly, otherwise
           the watchdog issues a reset
\********************************************************************/
{
#ifdef USE_WATCHDOG
#ifdef CPU_ADUC812
   WDR1 = 1;
   WDR2 = 1;
#endif
#ifdef CPU_CYGNAL
#if defined(CPU_C8051F310) || defined(CPU_C8051F320)
   PCA0CPH4 = 0x00;
#else
   WDTCN = 0xA5;
#endif
#endif
#endif
}
void yield (void)
Definition at line 1361 of file mscbmain.c.
References _flkey, configured, debug_output(), eeprom_flash(), flash_allowed, flash_param, flash_program, SYS_INFO::group_addr, lcd_clear(), led_blink(), LEGACY_PAGE, new_address, SYS_INFO::node_addr, reboot, rs232_output(), RSTSRC, send_remote_var(), SFRPAGE, time, upgrade(), watchdog_refresh(), SYS_INFO::wd_counter, and wrong_cpu.
{
   watchdog_refresh();
   /* output debug info to LCD if asked by interrupt routine */
   debug_output();
   /* output RS232 data if present */
   rs232_output();
   /* manage remote variables on SCS-1000 */
#ifdef SCS_1000
   poll_remote_vars();
   if (var_to_send != 0xFF) {
      send_remote_var(var_to_send);
      var_to_send = 0xFF;
   }
#endif
   /* output new address to LCD if available */
#if !defined(CPU_ADUC812) && !defined(SCS_300) && !defined(SCS_210)     // SCS210/300 redefine printf()
#ifdef LCD_DEBUG
   if (new_address) {
      new_address = 0;
      lcd_clear();
      printf("AD:%04X GA:%04X WD:%d", sys_info.node_addr,
             sys_info.group_addr, sys_info.wd_counter);
   }
#endif
#endif
   /* blink LED if not configured */
   if (!configured)
      led_blink(0, 1, 50);
   /* blink LED if wrong CPU */
   if (wrong_cpu)
      led_blink(0, 1, 30);
   /* flash EEPROM if asked by interrupt routine, wait 5 sec
      after reboot (power might not be stable) */
   if (flash_param && flash_allowed) {
      flash_param = 0;
      /* reset watchdog counts */
      sys_info.wd_counter = 0;
      _flkey = 0xF1;
      eeprom_flash();
           configured = 1;
   }
   if (flash_program && flash_allowed) {
      flash_program = 0;
      /* go to "bootloader" program */
      upgrade();
   }
   /* allow flash 5 sec after reboot */
   if (time() > 500)
      flash_allowed = 1;
   if (reboot) {
#ifdef CPU_CYGNAL
#ifdef CPU_C8051F120
      SFRPAGE = LEGACY_PAGE;
#endif
      RSTSRC = 0x10;         // force software reset
#else
      WDCON = 0x00;          // 16 msec
      WDE = 1;
      while (1);             // should be hardware reset later...
#endif
   }
}
Variable Documentation
unsigned char idata _cur_sub_addr
Definition at line 233 of file mscbmain.c.
Referenced by addr_node16(), addr_node8(), cur_sub_addr(), interprete(), and setup().
unsigned char idata _flkey = 0
Definition at line 231 of file mscbmain.c.
Referenced by eeprom_erase(), eeprom_flash(), eeprom_write(), setup(), and yield().
unsigned char idata _n_sub_addr
Definition at line 52 of file hvr_200.c.
unsigned char idata _var_size
Definition at line 233 of file mscbmain.c.
Referenced by eeprom_flash(), eeprom_retrieve(), interprete(), and setup().
unsigned char idata addr_mode
Definition at line 231 of file mscbmain.c.
Referenced by addr_node16(), and addr_node8().
bit addressed
Definition at line 252 of file mscbmain.c.
Referenced by addr_node16(), addr_node8(), interprete(), serial_int(), and setup().
unsigned char idata cmd_len
Definition at line 230 of file mscbmain.c.
Referenced by debug_output(), and serial_int().
bit configured
Definition at line 257 of file mscbmain.c.
Referenced by setup(), and yield().
unsigned char idata crc_code
Definition at line 231 of file mscbmain.c.
unsigned char bdata CSR
Definition at line 245 of file mscbmain.c.
sbit DEBUG_MODE = CSR ^ 0
Definition at line 247 of file mscbmain.c.
Referenced by debug_output(), and user_loop().
bit debug_new_i
Definition at line 253 of file mscbmain.c.
Referenced by debug_output(), and serial_int().
bit debug_new_o
Definition at line 253 of file mscbmain.c.
Referenced by debug_output(), and serial_int().
unsigned char idata final_i_in
Definition at line 230 of file mscbmain.c.
bit flash_allowed
Definition at line 258 of file mscbmain.c.
Referenced by setup(), and yield().
bit flash_param
Definition at line 254 of file mscbmain.c.
Referenced by interprete(), lcd_menu(), setup(), and yield().
bit flash_program
Definition at line 255 of file mscbmain.c.
Referenced by interprete(), setup(), and yield().
sbit FREEZE_MODE = CSR ^ 2
Definition at line 249 of file mscbmain.c.
Referenced by interprete(), and user_loop().
unsigned char idata i_in
Definition at line 230 of file mscbmain.c.
Referenced by debug_output(), interprete(), serial_int(), and setup().
unsigned char idata i_out
Definition at line 230 of file mscbmain.c.
Referenced by serial_int(), and setup().
unsigned char idata in_buf[20]
Definition at line 227 of file mscbmain.c.
Referenced by debug_output(), interprete(), serial_int(), setup(), and user_write().
unsigned char idata last_i_in
Definition at line 230 of file mscbmain.c.
bit lcd_present
Definition at line 1283 of file mscbutil.c.
Referenced by setup().
unsigned char idata n_out
Definition at line 230 of file mscbmain.c.
Referenced by debug_output(), interprete(), serial_int(), and setup().
unsigned char idata n_variables
Definition at line 231 of file mscbmain.c.
Referenced by interprete(), lcd_menu(), and setup().
bit new_address
Definition at line 253 of file mscbmain.c.
Referenced by interprete(), and yield().
char code node_name[]
Definition at line 46 of file hvr_200.c.
Referenced by setup().
unsigned char idata out_buf[8]
Definition at line 227 of file mscbmain.c.
Referenced by debug_output(), interprete(), serial_int(), setup(), and user_read().
bit reboot
Definition at line 256 of file mscbmain.c.
Referenced by interprete(), lcd_menu(), setup(), and yield().
sbit SYNC_MODE = CSR ^ 1
Definition at line 248 of file mscbmain.c.
Referenced by interprete().
SYS_INFO sys_info
Definition at line 239 of file mscbmain.c.
MSCB_INFO_VAR code variables[]
Definition at line 149 of file hvr_200.c.
sbit WD_RESET = CSR ^ 3
Definition at line 250 of file mscbmain.c.
Referenced by setup().
bit wrong_cpu
Definition at line 259 of file mscbmain.c.
Referenced by setup(), and yield().