AlcapDAQ:Rootana: util/mzdump/mzdump.c File Reference
util/mzdump/mzdump.c File Reference
#include <zlib.h>
#include <md5global.h>
#include <md5.h>
#include <midas.h>
#include <msystem.h>
#include <ybos.h>
#include <mrpc.h>
Data Structures
struct FMT_ID
Defines
#define REP_HEADER 1
#define REP_RECORD 2
#define REP_LENGTH 3
#define REP_EVENT 4
#define REP_BANKLIST 5
#define MD5_DIGEST_LEN 16
Functions
static void decompress (void *pmyevt)
DWORD data_format_check (EVENT_HEADER *pevent, INT *i)
int replog (int data_fmt, char *rep_file, int bl, int action)
void process_event (HNDLE hBuf, HNDLE request_id, EVENT_HEADER *pheader, void *pevent)
int main (int argc, char **argv)
Variables
char bank_name [4]
char sbank_name [4]
char svpath [128]
INT hBufEvent
INT save_dsp = 1
INT evt_display = 0
INT speed = 0
INT dsp_time = 0
INT dsp_fmt = 0
INT dsp_mode = 0
INT file_mode
INT bl = -1
INT consistency = 0
INT disp_bank_list = 0
BOOL via_callback
INT i
INT data_fmt
INT count
KEY key
HNDLE hSubkey
INT event_id
INT event_msk
FMT_ID eq [32]
static unsigned char * zbuf
static z_stream zstrm
Define Documentation
#define MD5_DIGEST_LEN 16
Definition at line 144 of file mzdump.c.
Referenced by decompress().
#define REP_BANKLIST 5
Definition at line 121 of file mzdump.c.
#define REP_EVENT 4
Definition at line 120 of file mzdump.c.
#define REP_HEADER 1
Definition at line 117 of file mzdump.c.
#define REP_LENGTH 3
Definition at line 119 of file mzdump.c.
#define REP_RECORD 2
Definition at line 118 of file mzdump.c.
Function Documentation
DWORD data_format_check (EVENT_HEADER * pevent, INT * i)
Definition at line 293 of file mzdump.c.
References data_fmt, EVENT_HEADER::event_id, FALSE, FMT_ID::fmt, fmt, FMT_ID::id, and TRUE.
{
   INT jj, ii;
   BOOL dupflag = FALSE;
   /* check in the active FE list for duplicate event ID */
   ii = 0;
   while (eq[ii].fmt) {
      jj = ii + 1;
      /* problem occur when duplicate ID with different data format */
      while (eq[jj].fmt) {
         if ((eq[jj].fmt != eq[ii].fmt)
             && (eq[jj].id == eq[ii].id)
             && (eq[jj].msk == eq[ii].msk)
             && eq[ii].id != 0) {
            printf("Duplicate eventID[%d] between Eq:%s & %s  ", eq[jj].id, eq[jj].Eqname,
                   eq[ii].Eqname);
            printf("Dumping event in raw format\n");
            dupflag = TRUE;
         }
         jj++;
      }
      ii++;
   }
   if (data_fmt != 0) {
      *i = 0;
      strcpy(eq[*i].Fmt, "GIVEN");
      return data_fmt;
   } else {
      *i = 0;
      if (dupflag)
         strcpy(eq[*i].Fmt, "DUPLICATE");
      else {
         do {
            if (pevent->event_id == eq[*i].id)
               return eq[*i].fmt;
            (*i)++;
         } while (eq[*i].fmt);
      }
   }
   return 0;
}
void decompress (void * pmyevt) [static]
Definition at line 149 of file mzdump.c.
References z_stream_s::avail_in, z_stream_s::avail_out, bank, bk_close(), bk_create(), bk_delete(), bk_locate(), bk_size(), BANK32::data_size, data_size, BANK_HEADER::data_size, EVENT_HEADER::data_size, EVENT_HEADER::event_id, i, MAX_EVENT_SIZE, MD5_DIGEST_LEN, MD5Final(), MD5Init(), MD5Update(), BANK32::name, z_stream_s::next_in, z_stream_s::next_out, BANK32::type, Z_DATA_ERROR, Z_MEM_ERROR, Z_NEED_DICT, Z_NO_FLUSH, and zbuf.
Referenced by process_event(), and replog().
{
  int   i;
  char  bkName[8];
  INT   bank_size;
  int   zret;
  char  md5_digest[MD5_DIGEST_LEN];
  unsigned int   size_aux;
  unsigned char *zdata;
  unsigned char *pdata;
  EVENT_HEADER  *pheader = (EVENT_HEADER*) pmyevt;
  unsigned char *pevent  = (unsigned char*)(pheader+1);
  //if ( pheader->event_id < 1 )
  if ( pheader->event_id != 1 )
    {
      printf("decompressor: skip event with id = %d\n",pheader->event_id);
      return;
    }
  printf("Event size: %d\n",pheader->data_size);
  for (i=1; i<=9; i++)
    {
      sprintf(bkName,"FE%1dZ",i);
      bank_size = bk_locate(pevent, bkName, &zdata);
      if ( !bank_size ) continue;
      inflateReset(&zstrm);
      /*** MD5 digest ***/
      memcpy(md5_digest,zdata,MD5_DIGEST_LEN);
      /*** decompress ***/
      zstrm.avail_in = bank_size-MD5_DIGEST_LEN; /*** compressed banks are of BYTE type, therefore
                                                        the number of elements == bank_size ***/
      zstrm.next_in   = zdata + MD5_DIGEST_LEN;
      zstrm.next_out  = zbuf;
      zstrm.avail_out = MAX_EVENT_SIZE;
      zstrm.avail_in  = bank_size-MD5_DIGEST_LEN;
      zret = inflate(&zstrm, Z_NO_FLUSH);
      switch (zret)
        {
        case Z_NEED_DICT:
          zret = Z_DATA_ERROR;     /* and fall through */
        case Z_DATA_ERROR:
        case Z_MEM_ERROR:
          printf("***ERROR! decompression fail!\n");
          continue;
        }
      if ( zstrm.avail_out == 0 )
        {
          printf("***ERROR! Decompressing fail!\n");
          continue;
        }
      BANK_HEADER *bank_header_aux = (BANK_HEADER*) zbuf;
      /*** calculate MD5 sum of the decompressed event ***/
      MD5_CTX mdContext;
      char  md5_digest_new[MD5_DIGEST_LEN];
      MD5Init  ( &mdContext );
      MD5Update( &mdContext, zbuf, bank_header_aux->data_size + sizeof(BANK_HEADER) );
      MD5Final ( md5_digest_new, &mdContext);
      if ( strncmp(md5_digest,md5_digest_new,MD5_DIGEST_LEN) )
        {
          printf("MD5 checksums do not match: [%s] [%s]!\n", md5_digest,md5_digest_new);
          continue;
        }
      /*** print info about bank size ***/
      int   size_decomp = MAX_EVENT_SIZE - zstrm.avail_out;
      float z = (float)(size_decomp-bank_size)/(float)(size_decomp)*100.0;
      printf("bank [%s]: size: %d bytes -> %d bytes => compression: %0.1f\%\n",bkName,bank_size,size_decomp,z);
      /*** delete compressed bank from the event as we don't need it anymore ***/
      bk_delete(pevent,bkName);
      /*** loop over decompressed event and add banks to the MIDAS event ***/
      size_aux = 0;
      while ( size_aux < bank_header_aux->data_size )
        {
          BANK32 *bank = (BANK32*)( zbuf + sizeof(BANK_HEADER) + size_aux  );
          BYTE   *bank_data = (BYTE*)(bank+1);
          //printf("uncompressed bank name: [%s], size: %d\n",bank->name,bank->data_size);
          bank_size = bk_locate(pevent, bank->name, &pdata);
          if ( bank_size == 0 )
            {
              bk_create(pevent, bank->name, bank->type, &pdata);
              memcpy(pdata, bank_data, bank->data_size);
              pdata += bank->data_size;
              bk_close(pevent,pdata);
              //printf("bank [%s] added to event\n",bank->name);
            }
          /* modified by VT on 17-Apr-2007:
             it looks bank has to be align on WORD (or DWORD???)
             this is work around to align the bank.
          */
          //int size_i = sizeof(BANK32) + bank->data_size;
          int size_i = bank->data_size;
          if (size_i%8)
            //size_i += (size_i/4+1)*4 - (size_i/4)*4 - size_i%4;
            size_i += (size_i/8+1)*8 - (size_i/8)*8 - size_i%8;
          //size_i += 4;
          size_i += sizeof(BANK32);
          //printf("size_i: %d\n", size_i);
          size_aux += size_i;
          //size_aux += sizeof(BANK32) + bank->data_size;
        }
    }
  pheader->data_size = bk_size(pevent);
  //printf("new event size: %d\n",((BANK_HEADER*)pevent)->data_size);
  return;
}
int main (int argc, char ** argv)
Definition at line 606 of file mzdump.c.
References z_stream_s::avail_in, bl, BM_CREATED, bm_get_buffer_info(), bm_open_buffer(), bm_request_event(), bm_set_cache_size(), BM_SUCCESS, cm_connect_experiment(), cm_disconnect_experiment(), cm_get_environment(), cm_get_experiment_database(), cm_get_version(), cm_msg, cm_set_watchdog_params(), CM_SUCCESS, cm_yield(), consistency, count, data_fmt, db_enum_key(), db_find_key(), db_get_key(), db_get_value(), DB_SUCCESS, debug, disp_bank_list, DSP_ASC, DSP_BANK, DSP_DEC, dsp_fmt, DSP_HEX, dsp_mode, DSP_RAW, dsp_time, DSP_UNK, equal_ustring(), EVENT_BUFFER_NAME, EVENT_BUFFER_SIZE, event_id, event_msk, EVENTID_ALL, evt_display, expt_name, FALSE, file_mode, fmt, FORMAT_MIDAS, FORMAT_YBOS, GET_ALL, GET_SOME, hBufEvent, hDB, hKey, host_name, HOST_NAME_LENGTH, hSubkey, i, inflateInit, MAX_EVENT_SIZE, MERROR, KEY::name, NAME_LENGTH, z_stream_s::next_in, z_stream_s::opaque, process_event(), BUFFER_HEADER::read_pointer, REP_BANKLIST, REP_EVENT, REP_HEADER, REP_LENGTH, REP_RECORD, replog(), RPC_SHUTDOWN, save_dsp, sbank_name, BUFFER_HEADER::size, size, speed, SS_ABORT, ss_getchar(), ss_kbhit(), ss_millitime(), start_time, status, stop_time, svpath, TID_STRING, TID_WORD, TRIGGER_ALL, TRUE, usage(), via_callback, BUFFER_HEADER::write_pointer, YB_ADD_RUN, YB_NO_RECOVER, YB_NO_RUN, Z_NULL, Z_OK, z_stream_s::zalloc, zbuf, and z_stream_s::zfree.
{
   HNDLE hDB, hKey;
   char host_name[HOST_NAME_LENGTH], expt_name[NAME_LENGTH], str[80];
   char buf_name[32] = EVENT_BUFFER_NAME, rep_file[128];
   double rate;
   unsigned int status, start_time, stop_time;
   BOOL debug = FALSE, rep_flag;
   INT ch, request_id, size, get_flag, action, i;
   BUFFER_HEADER buffer_header;
   /* set default */
   host_name[0] = 0;
   expt_name[0] = 0;
   sbank_name[0] = 0;
   svpath[0] = 0;
   rep_file[0] = 0;
   event_id = EVENTID_ALL;
   event_msk = TRIGGER_ALL;
   evt_display = 1;
   get_flag = GET_SOME;
   dsp_fmt = DSP_UNK;
   dsp_mode = DSP_BANK;
   file_mode = YB_NO_RECOVER;
   via_callback = TRUE;
   rep_flag = FALSE;
   dsp_time = 0;
   speed = 0;
   consistency = 0;
   action = REP_EVENT;
   /* Get if existing the pre-defined experiment */
   cm_get_environment(host_name, sizeof(host_name), expt_name, sizeof(expt_name));
   /* scan arg list for -x which specify the replog configuration */
   for (i = 1; i < argc; i++) {
      if (strncmp(argv[i], "-x", 2) == 0) {
         if (i + 1 == argc)
            goto repusage;
         if (strncmp(argv[++i], "online", 6) != 0) {
            rep_flag = TRUE;
            break;
         }
      }
   }
   if (rep_flag) {
      /* get Replay argument list */
      data_fmt = 0;
      for (i = 1; i < argc; i++) {
         if (argv[i][0] == '-' && argv[i][1] == 'd')
            debug = TRUE;
         else if (argv[i][0] == '-') {
            if (i + 1 >= argc || argv[i + 1][0] == '-')
               goto repusage;
            if (strncmp(argv[i], "-t", 2) == 0) {
               sprintf(str, argv[++i]);
               if (strncmp(str, "m", 1) == 0)
                  data_fmt = FORMAT_MIDAS;
               if (strncmp(str, "y", 1) == 0)
                  data_fmt = FORMAT_YBOS;
            } else if (strncmp(argv[i], "-b", 2) == 0)
               strncpy(sbank_name, argv[++i], 4);
            else if (strncmp(argv[i], "-i", 2) == 0)
               event_id = atoi(argv[++i]);
            else if (strncmp(argv[i], "-k", 2) == 0)
               event_msk = atoi(argv[++i]);
            else if (strncmp(argv[i], "-m", 2) == 0) {
               sprintf(str, argv[++i]);
               if (strncmp(str, "r", 1) == 0)
                  dsp_mode = DSP_RAW;
               if (strncmp(str, "b", 1) == 0)
                  dsp_mode = DSP_BANK;
            } else if (strncmp(argv[i], "-w", 2) == 0) {
               sprintf(str, argv[++i]);
               if (strncmp(str, "h", 1) == 0)
                  action = REP_HEADER;
               else if (strncmp(str, "r", 1) == 0)
                  action = REP_RECORD;
               else if (strncmp(str, "l", 1) == 0)
                  action = REP_LENGTH;
               else if (strncmp(str, "e", 1) == 0)
                  action = REP_EVENT;
               else if (strncmp(str, "j", 1) == 0)
                  action = REP_BANKLIST;
            } else if (strncmp(argv[i], "-p", 2) == 0)
               strcpy(svpath, argv[++i]);
            else if (strncmp(argv[i], "-c", 2) == 0) {
               strcpy(str, argv[++i]);
               if (strncmp(str, "n", 1) == 0 || strncmp(str, "N", 1) == 0)
                  file_mode = YB_NO_RUN;
               if (strncmp(str, "a", 1) == 0 || strncmp(str, "A", 1) == 0)
                  file_mode = YB_ADD_RUN;
            } else if (strncmp(argv[i], "-f", 2) == 0) {
               sprintf(str, argv[++i]);
               if (strncmp(str, "d", 1) == 0)
                  dsp_fmt = DSP_DEC;
               if (strncmp(str, "x", 1) == 0)
                  dsp_fmt = DSP_HEX;
               if (strncmp(str, "a", 1) == 0)
                  dsp_fmt = DSP_ASC;
            } else if (strncmp(argv[i], "-r", 2) == 0)
               bl = atoi(argv[++i]);
            else if (strncmp(argv[i], "-x", 2) == 0) {
               if (i + 1 == argc)
                  goto repusage;
               strcpy(rep_file, argv[++i]);
            } else {
             repusage:
               printf("mdump for replay  -x file name    : file to inspect\n");
               printf
                   ("                  -m mode         : Display mode either Bank or raw\n");
               printf
                   ("                  -b bank name    : search for bank name (case sensitive)\n");
               printf("                  -i evt_id (any) : event id from the FE\n");
               printf
                   ("                  -k mask (any)   : trigger_mask from FE setting\n");
               printf
                   (">>> -i and -k are valid for YBOS ONLY if EVID bank is present in the event\n");
               printf
                   ("                  -w what         : Header, Record, Length, Event, Jbank_list\n");
               printf
                   (">>> Header & Record are not supported for MIDAS as no physical record structure\n");
               printf
                   ("                  -f format (auto): data representation (x/d/ascii) def:bank header content\n");
               printf
                   ("                  -p path (null)  : path for file composition (see -c)\n");
               printf("                  -t type (auto)  : Bank format (Midas/Ybos)\n");
               printf(">>> if -x is a /dev/xxx, -t has to be specified\n");
               printf
                   ("                  -c compose      : retrieve file from event (Addrun#/Norun#)\n");
               printf
                   ("                  -r #            : skip record(YBOS) or event(MIDAS) to #\n");
               return 0;
            }
         }
      }
   } else {
      /* get parameters for online */
      for (i = 1; i < argc; i++) {
         if (argv[i][0] == '-' && argv[i][1] == 'd')
            debug = TRUE;
         else if (strncmp(argv[i], "-s", 2) == 0)
            speed = 1;
         else if (strncmp(argv[i], "-y", 2) == 0)
            consistency = 1;
         else if (strncmp(argv[i], "-j", 2) == 0)
            disp_bank_list = 1;
         else if (argv[i][0] == '-') {
            if (i + 1 >= argc || argv[i + 1][0] == '-')
               goto usage;
            else if (strncmp(argv[i], "-x", 2) == 0)
               strncpy(rep_file, argv[++i], 4);
            else if (strncmp(argv[i], "-b", 2) == 0)
               strncpy(sbank_name, argv[++i], 4);
            else if (strncmp(argv[i], "-l", 2) == 0)
               save_dsp = evt_display = atoi(argv[++i]);
            else if (strncmp(argv[i], "-w", 2) == 0)
               dsp_time = 1000 * (atoi(argv[++i]));
            else if (strncmp(argv[i], "-m", 2) == 0) {
               sprintf(str, argv[++i]);
               if (strncmp(str, "r", 1) == 0)
                  dsp_mode = DSP_RAW;
               if (strncmp(str, "y", 1) == 0)
                  dsp_mode = DSP_BANK;
            } else if (strncmp(argv[i], "-g", 2) == 0) {
               sprintf(str, argv[++i]);
               if (strncmp(str, "s", 1) == 0)
                  get_flag = GET_SOME;
               if (strncmp(str, "a", 1) == 0)
                  get_flag = GET_ALL;
            } else if (strncmp(argv[i], "-f", 2) == 0) {
               sprintf(str, argv[++i]);
               if (strncmp(str, "d", 1) == 0)
                  dsp_fmt = DSP_DEC;
               if (strncmp(str, "x", 1) == 0)
                  dsp_fmt = DSP_HEX;
               if (strncmp(str, "a", 1) == 0)
                  dsp_fmt = DSP_ASC;
            } else if (strncmp(argv[i], "-i", 2) == 0)
               event_id = atoi(argv[++i]);
            else if (strncmp(argv[i], "-k", 2) == 0)
               event_msk = atoi(argv[++i]);
            else if (strncmp(argv[i], "-p", 2) == 0)
               strcpy(svpath, argv[++i]);
            else if (strncmp(argv[i], "-z", 2) == 0)
               strcpy(buf_name, argv[++i]);
            else if (strncmp(argv[i], "-t", 2) == 0) {
               sprintf(str, argv[++i]);
               if (strncmp(str, "m", 1) == 0)
                  data_fmt = FORMAT_MIDAS;
               if (strncmp(str, "y", 1) == 0)
                  data_fmt = FORMAT_YBOS;
            } else if (strncmp(argv[i], "-c", 2) == 0) {
               strcpy(str, argv[++i]);
               if (strncmp(str, "n", 1) == 0 || strncmp(str, "N", 1) == 0)
                  file_mode = YB_NO_RUN;
               if (strncmp(str, "a", 1) == 0 || strncmp(str, "A", 1) == 0)
                  file_mode = YB_ADD_RUN;
            } else if (strncmp(argv[i], "-h", 2) == 0)
               strcpy(host_name, argv[++i]);
            else if (strncmp(argv[i], "-e", 2) == 0)
               strcpy(expt_name, argv[++i]);
            else {
             usage:
               printf("mdump for online  -l #            : display # events (look 1)\n");
               printf
                   ("                  -f format (auto): data representation (x/d/ascii) def:bank header content\n");
               printf
                   ("                  -p path (null)  : path for file composition (see -c)\n");
               printf("                  -t type (auto)  : Bank format (Midas/Ybos)\n");
               printf
                   ("                  -c compose      : retrieve file from event (Addrun#/Norun#)\n");
               printf
                   ("                  -w time         : insert wait in [sec] between each display\n");
               printf
                   ("                  -m mode         : Display mode either Bank or raw\n");
               printf
                   ("                  -j              : Display # of banks and bank name list only\n");
               printf
                   ("                  -b bank name    : search for bank name (case sensitive)\n");
               printf("                  -i evt_id (any) : event id from the FE\n");
               printf
                   ("                  -k mask (any)   : trigger_mask from FE setting\n");
               printf
                   (">>> -i and -k are valid for YBOS ONLY if EVID bank is present in the event\n");
               printf
                   ("                  -g type         : sampling mode either SOME or all)\n");
               printf(">>> in case of -c it is recommented to used -g all\n");
               printf
                   ("                  -s              : speed test for connection test\n");
               printf
                   ("                  -x Source       : Data source selection def:online (see -x -h)\n");
               printf
                   ("                  -y              : Serial number consistency check\n");
               printf(">>> in case of -y it is recommented to used -g all\n");
               printf("                  -z buffer name  : Midas buffer name(SYSTEM)\n");
               printf("                  [-h Hostname] [-e Experiment]\n\n");
               return 0;
            }
         }
      }
   }
   /*-- decompression initialization ----------------------------------------*/
   zstrm.zalloc   = Z_NULL;
   zstrm.zfree    = Z_NULL;
   zstrm.opaque   = Z_NULL;
   zstrm.avail_in = 0;
   zstrm.next_in  = Z_NULL;
   if ( inflateInit(&zstrm) != Z_OK)
     {
       printf("***ERROR! decompressing initialization fail!\n");
       return 1;
     }
   zbuf = (unsigned char*) malloc( MAX_EVENT_SIZE );
   if ( !zbuf )
     {
       printf("***ERROR! Can't allocate memory for aux. decompression buffer!\n");
       return 1;
     }
   if (rep_flag && data_fmt == 0) {
      char *pext;
      if ((pext = strrchr(rep_file, '.')) != 0) {
         if (equal_ustring(pext + 1, "mid"))
            data_fmt = FORMAT_MIDAS;
         else if (equal_ustring(pext + 1, "ybs"))
            data_fmt = FORMAT_YBOS;
         else if (equal_ustring(pext + 1, "gz")) {
            if ((pext = strchr(rep_file, '.')) != 0) {
               if (strstr(pext + 1, "mid"))
                  data_fmt = FORMAT_MIDAS;
               else if (strstr(pext + 1, "ybs"))
                  data_fmt = FORMAT_YBOS;
            } else {
               printf
                   ("\n>>> data type (-t) should be set by hand in -x mode for tape <<< \n\n");
               goto usage;
            }
         } else {
            printf
                ("\n>>> data type (-t) should be set by hand in -x mode for tape <<< \n\n");
            goto usage;
         }
      }
   }
   /* steer to replog function */
   if (rep_flag) {
      replog(data_fmt, rep_file, bl, action);
      return 0;
   } else
      /* check parameters */
   if (evt_display < 1 && evt_display > 1000) {
      printf("mdump-F- <-display arg> out of range (1:1000)\n");
      return -1;
   }
   if (dsp_time < 0 && dsp_time > 100) {
      printf("mdump-F- <-delay arg> out of range (1:100)\n");
      return -1;
   }
   /* connect to experiment */
   status = cm_connect_experiment(host_name, expt_name, "mdump", 0);
   if (status != CM_SUCCESS)
      return 1;
#ifdef _DEBUG
   cm_set_watchdog_params(TRUE, 0);
#endif
   /* open the "system" buffer, 1M size */
   status = bm_open_buffer(buf_name, EVENT_BUFFER_SIZE, &hBufEvent);
   if (status != BM_SUCCESS && status != BM_CREATED) {
      cm_msg(MERROR, "mdump", "bm_open_buffer, unknown buffer");
      goto error;
   }
   /* set the buffer cache size if requested */
   bm_set_cache_size(hBufEvent, 100000, 0);
   /* place a request for a specific event id */
   bm_request_event(hBufEvent, (WORD) event_id, (WORD) event_msk,
                    get_flag, &request_id, process_event);
   start_time = 0;
   if (speed == 1)
      printf("-%s -- Enter <!> to Exit ------- Midas Dump in Speed test mode ---\n",
             cm_get_version());
   else
      printf("-%s -- Enter <!> to Exit ------- Midas Dump ---\n", cm_get_version());
   /* connect to the database */
   cm_get_experiment_database(&hDB, &hKey);
   {                            /* ID block */
      INT l = 0;
      memset((char *) eq, 0, 32 * sizeof(FMT_ID));
      /* check if dir exists */
      if (db_find_key(hDB, 0, "/equipment", &hKey) == DB_SUCCESS) {
         char strtmp[256], equclient[32];
         for (i = 0;; i++) {
            db_enum_key(hDB, hKey, i, &hSubkey);
            if (!hSubkey)
               break;
            db_get_key(hDB, hSubkey, &key);
            sprintf(eq[l].Eqname, key.name);
            /* check if client running this equipment is present */
            /* extract client name from equipment */
            size = sizeof(strtmp);
            sprintf(strtmp, "/equipment/%s/common/Frontend name", key.name);
            db_get_value(hDB, 0, strtmp, equclient, &size, TID_STRING, TRUE);
            /* search client name under /system/clients/xxx/name */
            /* Outcommented 22 Dec 1997 SR because of problem when
               mdump is started before frontend
               if (status = cm_exist(equclient,FALSE) != CM_SUCCESS)
               continue;
             */
            size = sizeof(WORD);
            sprintf(strtmp, "/equipment/%s/common/event ID", key.name);
            db_get_value(hDB, 0, strtmp, &(eq[l]).id, &size, TID_WORD, TRUE);
            size = sizeof(WORD);
            sprintf(strtmp, "/equipment/%s/common/Trigger mask", key.name);
            db_get_value(hDB, 0, strtmp, &(eq[l]).msk, &size, TID_WORD, TRUE);
            size = sizeof(str);
            sprintf(strtmp, "/equipment/%s/common/Format", key.name);
            db_get_value(hDB, 0, strtmp, str, &size, TID_STRING, TRUE);
            if (equal_ustring(str, "YBOS")) {
               eq[l].fmt = FORMAT_YBOS;
               strcpy(eq[l].Fmt, "YBOS");
            } else if (equal_ustring(str, "MIDAS")) {
               eq[l].fmt = FORMAT_MIDAS;
               strcpy(eq[l].Fmt, "MIDAS");
            } else if (equal_ustring(str, "DUMP")) {
               eq[l].fmt = FORMAT_MIDAS;
               strcpy(eq[l].Fmt, "DUMP");
            } else if (equal_ustring(str, "ASCII")) {
               eq[l].fmt = FORMAT_MIDAS;
               strcpy(eq[l].Fmt, "ASCII");
            } else if (equal_ustring(str, "HBOOK")) {
               eq[l].fmt = FORMAT_MIDAS;
               strcpy(eq[l].Fmt, "HBOOK");
            } else if (equal_ustring(str, "FIXED")) {
               eq[l].fmt = FORMAT_MIDAS;
               strcpy(eq[l].Fmt, "FIXED");
            }
            l++;
         }
      }
      /* for equipment */
      /* check for EBuilder */
      if (db_find_key(hDB, 0, "/EBuilder/Settings", &hKey) == DB_SUCCESS) {
         sprintf(eq[l].Eqname, "EBuilder");
         /* check if client running this equipment is present */
         /* search client name under /system/clients/xxx/name */
         /* Outcommented 22 Dec 1997 SR because of problem when
            mdump is started before frontend
            if (status = cm_exist(equclient,FALSE) != CM_SUCCESS)
            continue;
          */
         size = sizeof(WORD);
         db_get_value(hDB, hKey, "Event ID", &(eq[l]).id, &size, TID_WORD, TRUE);
         size = sizeof(WORD);
         db_get_value(hDB, hKey, "Trigger mask", &(eq[l]).msk, &size, TID_WORD, TRUE);
         size = sizeof(str);
         db_get_value(hDB, hKey, "Format", str, &size, TID_STRING, TRUE);
         if (equal_ustring(str, "YBOS")) {
            eq[l].fmt = FORMAT_YBOS;
            strcpy(eq[l].Fmt, "YBOS");
         } else if (equal_ustring(str, "MIDAS")) {
            eq[l].fmt = FORMAT_MIDAS;
            strcpy(eq[l].Fmt, "MIDAS");
         } else {
            printf("Format unknown for Event Builder (%s)\n", str);
            goto error;
         }
         l++;
      }
      /* Debug */
      if (debug) {
         i = 0;
         printf("ID\tMask\tFormat\tEq_name\n");
         while (eq[i].fmt) {
            printf("%d\t%d\t%s\t%s\n", eq[i].id, eq[i].msk, eq[i].Fmt, eq[i].Eqname);
            i++;
         }
      }
   }                            /* ID block */
   do {
      if (via_callback)
         status = cm_yield(1000);
      if (speed == 1) {
         /* calculate rates each second */
         if (ss_millitime() - start_time > 1000) {
            stop_time = ss_millitime();
            rate = count / 1024.0 / 1024.0 / ((stop_time - start_time) / 1000.0);
            /* get information about filling level of the buffer */
            bm_get_buffer_info(hBufEvent, &buffer_header);
            size = buffer_header.read_pointer - buffer_header.write_pointer;
            if (size <= 0)
               size += buffer_header.size;
            printf("Level: %4.3f %%, ", 100 - 100.0 * size / buffer_header.size);
            printf("Rate: %1.3f MB/sec\n", rate);
            start_time = stop_time;
            count = 0;
         }
      }
      /*  speed */
      /* check keyboard */
      ch = 0;
      if (ss_kbhit()) {
         ch = ss_getchar(0);
         if (ch == -1)
            ch = getchar();
         if ((char) ch == '!')
            break;
      }
   } while (status != RPC_SHUTDOWN && status != SS_ABORT);
 error:
   cm_disconnect_experiment();
   free( zbuf );
   (void)inflateEnd(&zstrm);
   return 1;
}
void process_event (HNDLE hBuf, HNDLE request_id, EVENT_HEADER * pheader, void * pevent)
Definition at line 484 of file mzdump.c.
References bars, bk_find(), bk_list(), cm_disconnect_experiment(), consistency, count, data_format_check(), EVENT_HEADER::data_size, decompress(), disp_bank_list, dsp_fmt, dsp_mode, DSP_RAW, dsp_time, EVENT_HEADER::event_id, evt_display, file_mode, FORMAT_MIDAS, FORMAT_YBOS, i_bar, index, save_dsp, sbank_name, EVENT_HEADER::serial_number, size, speed, ss_sleep(), SS_SUCCESS, status, svpath, EVENT_HEADER::time_stamp, EVENT_HEADER::trigger_mask, yb_any_bank_display(), yb_any_event_display(), yb_any_event_swap(), yb_file_recompose(), YB_NO_RECOVER, YB_STRING_BANKLIST_MAX, YB_SUCCESS, ybk_find(), and ybk_list().
{
   static char bars[] = "|/-\\";
   static int i_bar;
   static EVENT_HEADER pevh;
   INT internal_data_fmt, status, index, size;
   DWORD *plrl, *pybk, bklen, bktyp;
   char banklist[YB_STRING_BANKLIST_MAX];
   BANK *pmbk;
   BANK_HEADER *pmbh;
   //if (pheader->serial_number > 0)
   decompress(pheader);
   if (speed == 1) {
      /* accumulate received event size */
      size = pheader->data_size + sizeof(EVENT_HEADER);
      count += size;
      return;
   }
   if (consistency == 1) {
      if (pheader->serial_number != pevh.serial_number + 1) {
         /* event header */
         printf
             ("\nLast - Evid:%4.4hx- Mask:%4.4hx- Serial:%li- Time:0x%lx- Dsize:%li/0x%lx\n",
              pevh.event_id, pevh.trigger_mask, pevh.serial_number, pevh.time_stamp,
              pevh.data_size, pevh.data_size);
         printf
             ("Now  - Evid:%4.4hx- Mask:%4.4hx- Serial:%li- Time:0x%lx- Dsize:%li/0x%lx\n",
              pheader->event_id, pheader->trigger_mask, pheader->serial_number,
              pheader->time_stamp, pheader->data_size, pheader->data_size);
      } else {
         printf("Consistency check: %c - %li\r", bars[i_bar++ % 4],
                pheader->serial_number);
         fflush(stdout);
      }
      memcpy((char *) &pevh, (char *) pheader, sizeof(EVENT_HEADER));
      return;
   }
   if (evt_display > 0) {
      evt_display--;
      internal_data_fmt = data_format_check(pheader, &index);
      /* pointer to data section */
      plrl = (DWORD *) pevent;
      pmbh = (BANK_HEADER *) pevent;
      /* display header comes ALWAYS from MIDAS header */
      printf("------------------------ Event# %i ------------------------\n",
             save_dsp - evt_display);
      /* selection based on data format */
      if ((internal_data_fmt == FORMAT_YBOS) && (yb_any_event_swap(FORMAT_YBOS, plrl) >= YB_SUCCESS)) { /* ---- YBOS FMT ---- */
         if (file_mode != YB_NO_RECOVER)
            if ((status =
                 yb_file_recompose(pevent, internal_data_fmt, svpath,
                                   file_mode)) != YB_SUCCESS)
               printf("mdump recompose error %i\n", status);
         if (sbank_name[0] != 0) {      /* bank name given through argument list */
            if ((status = ybk_find(plrl, sbank_name, &bklen, &bktyp, (void *) &pybk)) == YB_SUCCESS) {  /* given bank found in list */
               status = ybk_list(plrl, banklist);
               printf("#banks:%i Bank list:-%s-\n", status, banklist);
               printf("Bank:%s - Length (I*4):%li - Type:%li - pBk:%p\n", sbank_name,
                      bklen, bktyp, pybk);
               yb_any_bank_display(NULL, pybk, FORMAT_YBOS, dsp_mode, dsp_fmt);
            } else {
               status = ybk_list(plrl, banklist);
               printf("Bank -%s- not found (%i) in ", sbank_name, status);
               printf("#banks:%i Bank list:-%s-\n", status, banklist);
            }
         } else {               /* Full event */
            /* event header */
            printf("Evid:%4.4hx- Mask:%4.4hx- Serial:%ld- Time:0x%lx- Dsize:%ld/0x%lx\n",
                   pheader->event_id, pheader->trigger_mask, pheader->serial_number,
                   pheader->time_stamp, pheader->data_size, pheader->data_size);
            if (disp_bank_list) {
               status = ybk_list(plrl, banklist);
               printf("#banks:%i Bank list:-%s-\n", status, banklist);
            } else
               yb_any_event_display(plrl, FORMAT_YBOS, dsp_mode, dsp_fmt);
         }
      } else if ((internal_data_fmt == FORMAT_MIDAS) && (yb_any_event_swap(FORMAT_MIDAS, pheader) >= YB_SUCCESS)) {     /* ---- MIDAS FMT ---- */
         if (file_mode != YB_NO_RECOVER)
            status = yb_file_recompose(pheader, internal_data_fmt, svpath, file_mode);
         if (sbank_name[0] != 0) {
            if (bk_find(pmbh, sbank_name, &bklen, &bktyp, (void *) &pmbk) == SS_SUCCESS) {      /* bank name given through argument list */
               status = bk_list(pmbh, banklist);
               printf("#banks:%i Bank list:-%s-", status, banklist);
               yb_any_bank_display(pmbh, pmbk, FORMAT_MIDAS, dsp_mode, dsp_fmt);
            } else {
               status = bk_list(pmbh, banklist);
               printf("Bank -%s- not found (%i) in ", sbank_name, status);
               printf("#banks:%i Bank list:-%s-\n", status, banklist);
            }
         } else {               /* Full event or bank list only */
            if (disp_bank_list) {
               /* event header */
               printf
                   ("Evid:%4.4hx- Mask:%4.4hx- Serial:%ld- Time:0x%lx- Dsize:%ld/0x%lx\n",
                    pheader->event_id, pheader->trigger_mask, pheader->serial_number,
                    pheader->time_stamp, pheader->data_size, pheader->data_size);
               status = bk_list(pmbh, banklist);
               printf("#banks:%i Bank list:-%s-\n", status, banklist);
            } else
               yb_any_event_display(pheader, FORMAT_MIDAS, dsp_mode, dsp_fmt);
         }
      } else {                  /* unknown format just dump midas event */
         printf("Data format not supported: %s\n", eq[index].Fmt);
         yb_any_event_display(pheader, FORMAT_MIDAS, DSP_RAW, dsp_fmt);
      }
      if (evt_display == 0) {
         cm_disconnect_experiment();
         exit(0);
      }
      if (dsp_time != 0)
         ss_sleep(dsp_time);
   }
   return;
}
int replog (int data_fmt, char * rep_file, int bl, int action)
Definition at line 338 of file mzdump.c.
References bk_find(), bk_list(), D_EVTLEN, D_HEADER, BANK_HEADER::data_size, EVENT_HEADER::data_size, decompress(), dsp_fmt, dsp_mode, event_id, EVENT_HEADER::event_id, event_msk, EVENTID_ALL, EVENTID_BOR, EVENTID_EOR, EVENTID_MESSAGE, evtlen, FALSE, file_mode, FORMAT_MIDAS, FORMAT_YBOS, i, pme, REP_BANKLIST, REP_EVENT, REP_HEADER, REP_LENGTH, REP_RECORD, sbank_name, EVENT_HEADER::serial_number, SS_SUCCESS, status, svpath, EVENT_HEADER::time_stamp, TRIGGER_ALL, EVENT_HEADER::trigger_mask, TRUE, yb_any_all_info_display(), yb_any_event_display(), yb_any_event_get(), yb_any_event_swap(), yb_any_file_rclose(), yb_any_file_ropen(), yb_any_physrec_display(), yb_any_physrec_get(), yb_any_physrec_skip(), YB_DONE, yb_file_recompose(), YB_NO_RECOVER, YB_STRING_BANKLIST_MAX, YB_SUCCESS, ybk_find(), ybk_list(), YBOS_EVID_EVENT_ID, and YBOS_EVID_TRIGGER_MASK.
{
   char banklist[YB_STRING_BANKLIST_MAX];
   short int msk, id;
   BOOL bank_found = FALSE;
   INT status = 0, i;
   DWORD physize, evtlen;
   void *physrec;
   char *pmyevt;
   EVENT_HEADER *pme;
   BANK_HEADER *pmbkh;
   YBOS_BANK_HEADER *pybk;
   DWORD *pdata;
   DWORD bklen, bktyp;
   /* open data file */
   if (yb_any_file_ropen(rep_file, data_fmt) != SS_SUCCESS)
      return (-1);
   switch (action) {
   case REP_HEADER:
   case REP_RECORD:
      /* get only physical record header */
      if (yb_any_physrec_skip(data_fmt, bl) != YB_SUCCESS)
         return (-1);
      do {
         if (action == REP_HEADER)
            status = yb_any_all_info_display(D_HEADER);
         else if (action == REP_RECORD)
            status = yb_any_physrec_display(data_fmt);
         if ((status == YB_DONE) || (bl != -1))
            break;
      }
      while (yb_any_physrec_get(data_fmt, &physrec, &physize) == YB_SUCCESS);
      break;
   case REP_LENGTH:
   case REP_EVENT:
   case REP_BANKLIST:
      /* skip will read atleast on record */
      if (yb_any_physrec_skip(data_fmt, bl) != YB_SUCCESS)
         return (-1);
      i = 0;
      while (yb_any_event_get(data_fmt, (void **) &pmyevt, &evtlen) == YB_SUCCESS) {
         status = yb_any_event_swap(data_fmt, pmyevt);
         if (file_mode != YB_NO_RECOVER)
            if ((status =
                 yb_file_recompose(pmyevt, data_fmt, svpath, file_mode)) != YB_SUCCESS)
               printf("mdump recompose error %i\n", status);
         /*** decompress events from WFD frontends ***/
         if (data_fmt == FORMAT_MIDAS)
           {
             //if (i>0)
             decompress(pmyevt);
           }
         if (action == REP_LENGTH)
            status = yb_any_all_info_display(D_EVTLEN);
         if (action == REP_BANKLIST) {
            if (data_fmt == FORMAT_YBOS)
               status = ybk_list((DWORD *) pmyevt, banklist);
            else if (data_fmt == FORMAT_MIDAS) {
               pme = (EVENT_HEADER *) pmyevt;
               if (pme->event_id == EVENTID_BOR ||
                   pme->event_id == EVENTID_EOR || pme->event_id == EVENTID_MESSAGE)
                  continue;
               printf
                   ("Evid:%4.4hx- Mask:%4.4hx- Serial:%ld- Time:0x%lx- Dsize:%ld/0x%lx\n",
                    pme->event_id, pme->trigger_mask, pme->serial_number, pme->time_stamp,
                    pme->data_size, pme->data_size);
               pmbkh = (BANK_HEADER *) (((EVENT_HEADER *) pmyevt) + 1);
               status = bk_list(pmbkh, banklist);
            }
            printf("#banks:%i Bank list:-%s-\n", status, banklist);
         } else if ((action == REP_EVENT) && (event_id == EVENTID_ALL) && (event_msk == TRIGGER_ALL) && (sbank_name[0] == 0)) { /* a quick by-pass to prevent bank search if not necessary */
            printf
                ("------------------------ Event# %i --------------------------------\n",
                 i++);
            yb_any_event_display(pmyevt, data_fmt, dsp_mode, dsp_fmt);
         } else if (action == REP_EVENT) {
            id = EVENTID_ALL;
            msk = TRIGGER_ALL;
            if (data_fmt == FORMAT_MIDAS) {
               pme = (EVENT_HEADER *) pmyevt;
               id = pme->event_id;
               msk = pme->trigger_mask;
               /* Search bank if necessary */
               if (sbank_name[0] != 0) {        /* bank name given through argument list */
                  bank_found = FALSE;
                  pmbkh = (BANK_HEADER *) (((EVENT_HEADER *) pmyevt) + 1);
                  if ((pmbkh->data_size + 8) == ((EVENT_HEADER *) pmyevt)->data_size) {
                     if ((status = bk_find(pmbkh, sbank_name, &bklen, &bktyp, (void *) &pybk)) == SS_SUCCESS) { /* given bank found in list */
                        status = bk_list(pmbkh, banklist);
                        bank_found = TRUE;
                     }
                  }
               }
            } else if (data_fmt == FORMAT_YBOS) {
               /* check id EVID found in event for id and msk selection */
               if ((status =
                    ybk_find((DWORD *) pmyevt, "EVID", &bklen, &bktyp,
                             (void *) &pybk)) == YB_SUCCESS) {
                  pdata = (DWORD *) ((YBOS_BANK_HEADER *) pybk + 1);
                  id = (short int) (YBOS_EVID_EVENT_ID(pdata));
                  msk = (short int) (YBOS_EVID_TRIGGER_MASK(pdata));
               }
               /* Search bank if necessary */
               if (sbank_name[0] != 0) {        /* bank name given through argument list */
                  bank_found = FALSE;
                  if ((status = ybk_find((DWORD *) pmyevt, sbank_name, &bklen, &bktyp, (void *) &pybk)) == YB_SUCCESS) {        /* given bank found in list */
                     status = ybk_list((DWORD *) pmyevt, banklist);
                     bank_found = TRUE;
                  }
               }
            }
            /* check user request through switch setting (id, msk ,bank) */
            if ((event_msk != TRIGGER_ALL) || (event_id != EVENTID_ALL) || (sbank_name[0] != 0)) {      /* check request or skip event if not satisfied */
               if (((event_id != EVENTID_ALL) && (id != event_id)) ||   /* id check ==> skip */
                   ((event_msk != TRIGGER_ALL) && (msk != event_msk)) ||        /* msk check ==> skip */
                   ((sbank_name[0] != 0) && !bank_found)) {     /* bk check ==> skip *//* skip event */
                  printf("Searching for Bank -%s- Skiping event...%i\r", sbank_name, i++);
                  fflush(stdout);
               } else {         /* request match ==> display any event */
                  printf
                      ("------------------------ Event# %i --------------------------------\n",
                       i++);
                  yb_any_event_display(pmyevt, data_fmt, dsp_mode, dsp_fmt);
               }
            } else {            /* no user request ==> display any event */
               printf
                   ("------------------------ Event# %i --------------------------------\n",
                    i++);
               yb_any_event_display(pmyevt, data_fmt, dsp_mode, dsp_fmt);
            }
         }
      }
      break;
   }                            /* switch */
   /* close data file */
   yb_any_file_rclose(data_fmt);
   return 0;
}
Variable Documentation
char bank_name[4]
Definition at line 123 of file mzdump.c.
INT bl = -1
Definition at line 126 of file mzdump.c.
INT consistency = 0
Definition at line 127 of file mzdump.c.
INT count
Definition at line 129 of file mzdump.c.
INT data_fmt
Definition at line 129 of file mzdump.c.
INT disp_bank_list = 0
Definition at line 127 of file mzdump.c.
INT dsp_fmt = 0
Definition at line 126 of file mzdump.c.
INT dsp_mode = 0
Definition at line 126 of file mzdump.c.
INT dsp_time = 0
Definition at line 126 of file mzdump.c.
FMT_ID eq[32]
Definition at line 141 of file mzdump.c.
INT event_id
Definition at line 132 of file mzdump.c.
INT event_msk
Definition at line 132 of file mzdump.c.
INT evt_display = 0
Definition at line 125 of file mzdump.c.
INT file_mode
Definition at line 126 of file mzdump.c.
INT hBufEvent
Definition at line 124 of file mzdump.c.
HNDLE hSubkey
Definition at line 131 of file mzdump.c.
INT i
Definition at line 129 of file mzdump.c.
KEY key
Definition at line 130 of file mzdump.c.
INT save_dsp = 1
Definition at line 125 of file mzdump.c.
char sbank_name[4]
Definition at line 123 of file mzdump.c.
INT speed = 0
Definition at line 126 of file mzdump.c.
char svpath[128]
Definition at line 123 of file mzdump.c.
BOOL via_callback
Definition at line 128 of file mzdump.c.
unsigned char* zbuf [static]
Definition at line 145 of file mzdump.c.
Referenced by decompress(), and main().
z_stream zstrm [static]
Definition at line 146 of file mzdump.c.