AlcapDAQ:Rootana: midas/drivers/device/nitronic.h File Reference
midas/drivers/device/nitronic.h File Reference
Functions
INT nitronic (INT cmd,...)
Function Documentation
INT nitronic (INT cmd, ...)
Definition at line 285 of file nitronic.c.
References channel, cm_msg, CMD_EXIT, CMD_GET, CMD_GET_ALL, CMD_GET_CURRENT, CMD_GET_CURRENT_ALL, CMD_GET_DEFAULT_NAME, CMD_INIT, CMD_SET, CMD_SET_ALL, CMD_SET_CURRENT_LIMIT, CMD_SET_CURRENT_LIMIT_ALL, CMD_SET_LABEL, FE_ERR_DRIVER, FE_SUCCESS, hKey, MERROR, nitronic_exit(), nitronic_get(), nitronic_get_all(), nitronic_get_current(), nitronic_init(), nitronic_set(), nitronic_set_all(), nitronic_set_current_limit(), status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, flags, status;
   float value, *pvalue;
   void *info, *bd;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      flags = va_arg(argptr, INT);
      bd = va_arg(argptr, void *);
      status = nitronic_init(hKey, info, channel, bd);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = nitronic_exit(info);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      status = nitronic_set(info, channel, value);
      break;
   case CMD_SET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue   =  va_arg(argptr, float *);
      status = nitronic_set_all(info, channel, *pvalue);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue  = va_arg(argptr, float*);
      status = nitronic_get(info, channel, pvalue);
      break;
   case CMD_GET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = nitronic_get_all(info, channel, pvalue);
      break;
   case CMD_GET_CURRENT:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = nitronic_get_current(info, channel, pvalue);
      break;
   case CMD_GET_CURRENT_ALL:
      break;
   case CMD_SET_CURRENT_LIMIT:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);
      if (channel == 0)         /* one one limit for all channels */
         status = nitronic_set_current_limit(info, value);
      else
         status = FE_SUCCESS;
      break;
    case CMD_SET_LABEL:
      status = FE_SUCCESS;
      break;
    case CMD_GET_DEFAULT_NAME:
      status = FE_SUCCESS;
      break;
    case CMD_SET_CURRENT_LIMIT_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float*);
      status = nitronic_set_current_limit(info, pvalue[0]);
      break;
   default:
      cm_msg(MERROR, "nitronic device driver", "Received unknown command %d", cmd);
      status = FE_ERR_DRIVER;
      break;
   }
   va_end(argptr);
   return status;
}