AlcapDAQ:Rootana: midas/drivers/bus/null.c File Reference
midas/drivers/bus/null.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include "midas.h"
Data Structures
struct NULL_SETTINGS
struct NULL_INFO
Defines
#define NULL_SETTINGS_STR "\Device = STRING : [32] com1\n\"
Functions
int null_open (char *device)
INT null_exit (NULL_INFO *info)
int null_write (NULL_INFO *info, char *data, int size)
int null_read (NULL_INFO *info, char *data, int size, int timeout)
int null_puts (NULL_INFO *info, char *str)
int null_gets (NULL_INFO *info, char *str, int size, char *pattern, int timeout)
int null_init (HNDLE hkey, void **pinfo)
INT null (INT cmd,...)
Variables
static int debug_flag = 0
Define Documentation
#define NULL_SETTINGS_STR "\Device = STRING : [32] com1\n\"
Definition at line 36 of file null.c.
Referenced by null_init().
Function Documentation
INT null (INT cmd, ...)
Definition at line 241 of file null.c.
References CMD_DEBUG, CMD_EXIT, CMD_GETS, CMD_INIT, CMD_NAME, CMD_PUTS, CMD_READ, CMD_WRITE, debug_flag, FE_SUCCESS, null_exit(), null_gets(), null_init(), null_puts(), null_read(), null_write(), size, status, and timeout.
{
   va_list argptr;
   HNDLE hkey;
   INT status, size, timeout;
   void *info;
   char *str, *pattern;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hkey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      status = null_init(hkey, info);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = null_exit(info);
      break;
   case CMD_NAME:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      strcpy(str, "null");
      break;
   case CMD_WRITE:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, int);
      status = null_write(info, str, size);
      break;
   case CMD_READ:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, INT);
      timeout = va_arg(argptr, INT);
      status = null_read(info, str, size, timeout);
      break;
   case CMD_PUTS:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      status = null_puts(info, str);
      break;
   case CMD_GETS:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, INT);
      pattern = va_arg(argptr, char *);
      timeout = va_arg(argptr, INT);
      status = null_gets(info, str, size, pattern, timeout);
      break;
   case CMD_DEBUG:
      status = va_arg(argptr, INT);
      debug_flag = status;
      break;
   }
   va_end(argptr);
   return status;
}
INT null_exit (NULL_INFO * info)
Definition at line 67 of file null.c.
References SUCCESS.
Referenced by null().
{
   /* something like
      close(info->fd);
    */
   return SUCCESS;
}
int null_gets (NULL_INFO * info, char * str, int size, char * pattern, int timeout)
Definition at line 168 of file null.c.
References debug_flag, and ss_sleep().
Referenced by null().
{
   int l;
   /* something like
      memset(str, 0, size);
      for (l=0 ; l<size-1 ; l++)
      {
      status = read(info->fd, str+l, 1, &i);
      if (!status || i == 0)
      {
      if (pattern && pattern[0])
      return 0;
      break;
      }
      if (pattern && pattern[0])
      if (strstr(str, pattern) != NULL)
      break;
      }
    */
   /* simulate reading */
   ss_sleep(10);
   l = 0;
   str[0] = 0;
   if (debug_flag && l > 0) {
      FILE *f;
      f = fopen("null.log", "a");
      fprintf(f, "gets %s: %s\n", pattern, str);
      fclose(f);
   }
   return l;
}
int null_init (HNDLE hkey, void ** pinfo)
Definition at line 209 of file null.c.
References cm_get_experiment_database(), db_create_record(), db_find_key(), db_get_record(), DB_SUCCESS, NULL_SETTINGS::device, NULL_INFO::fd, FE_ERR_HW, FE_ERR_ODB, hDB, null_open(), NULL_SETTINGS_STR, NULL_INFO::settings, size, status, and SUCCESS.
Referenced by null().
{
   HNDLE hDB, hkeybd;
   INT size, status;
   NULL_INFO *info;
   /* allocate info structure */
   info = calloc(1, sizeof(NULL_INFO));
   *pinfo = info;
   cm_get_experiment_database(&hDB, NULL);
   /* create NULL settings record */
   status = db_create_record(hDB, hkey, "BD", NULL_SETTINGS_STR);
   if (status != DB_SUCCESS)
      return FE_ERR_ODB;
   db_find_key(hDB, hkey, "BD", &hkeybd);
   size = sizeof(info->settings);
   db_get_record(hDB, hkeybd, &info->settings, &size, 0);
   /* open port */
   info->fd = null_open(info->settings.device);
   if (info->fd < 0)
      return FE_ERR_HW;
   return SUCCESS;
}
int null_open (char * device)
Definition at line 47 of file null.c.
Referenced by null_init().
{
   int fd;
   /* open device using device name, like
      fd = open(device);
      if (fd == -1)
      return -1;
    */
   /* simulate open */
   fd = 1;
   return fd;
}
int null_puts (NULL_INFO * info, char * str)
Definition at line 143 of file null.c.
References debug_flag.
Referenced by null().
{
   DWORD written;
   if (debug_flag) {
      FILE *f;
      f = fopen("null.log", "a");
      fprintf(f, "puts: %s\n", str);
      fclose(f);
   }
   /* something like
      write(info->fd, str, strlen(str), &written);
    */
   /* simulate writing */
   written = strlen(str);
   return written;
}
int null_read (NULL_INFO * info, char * data, int size, int timeout)
Definition at line 108 of file null.c.
References debug_flag, i, and ss_sleep().
Referenced by null().
{
   int i, l;
   /* somethng like
      memset(data, 0, size);
      for (l=0 ; l<size ; l++)
      {
      status = read(info->fd, data+l, 1, &i);
      if (!status || i == 0)
      break;
      }
    */
   /* simulate reading */
   ss_sleep(10);
   l = 0;
   if (debug_flag && l > 0) {
      FILE *f;
      f = fopen("null.log", "a");
      fprintf(f, "read: ");
      for (i = 0; i < l; i++)
         fprintf(f, "%X ", data[i]);
      fprintf(f, "\n");
      fclose(f);
   }
   return l;
}
int null_write (NULL_INFO * info, char * data, int size)
Definition at line 80 of file null.c.
References debug_flag, and i.
Referenced by null().
{
   DWORD written, i;
   if (debug_flag) {
      FILE *f;
      f = fopen("null.log", "a");
      fprintf(f, "write: ");
      for (i = 0; (int) i < size; i++)
         fprintf(f, "%X ", data[i]);
      fprintf(f, "\n");
      fclose(f);
   }
   /* something like
      write(info->fd, data, size, &written);
    */
   /* simulate writing */
   written = size;
   return written;
}
Variable Documentation
int debug_flag = 0 [static]
Definition at line 30 of file null.c.
Referenced by command_loop(), null(), null_gets(), null_puts(), null_read(), and null_write().