AlcapDAQ:Rootana: midas/drivers/device/nulldev.h File Reference
midas/drivers/device/nulldev.h File Reference
Functions
INT nulldev (INT cmd,...)
Function Documentation
INT nulldev (INT cmd, ...)
Definition at line 224 of file nulldev.c.
References channel, CMD_EXIT, CMD_GET, CMD_GET_ALL, CMD_INIT, CMD_SET, CMD_SET_ALL, FE_SUCCESS, hKey, nulldev_exit(), nulldev_get(), nulldev_get_all(), nulldev_init(), nulldev_set(), nulldev_set_all(), status, and value.
{
   va_list argptr;
   HNDLE hKey;
   INT channel, status;
   DWORD flags;
   float value, *pvalue;
   void *info, *bd;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hKey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      flags = va_arg(argptr, DWORD);
      bd = va_arg(argptr, void *);
      status = nulldev_init(hKey, info, channel, bd);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = nulldev_exit(info);
      break;
   case CMD_SET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      value = (float) va_arg(argptr, double);   // floats are passed as double
      status = nulldev_set(info, channel, value);
      break;
   case CMD_SET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = (float *) va_arg(argptr, float *);
      status = nulldev_set_all(info, channel, pvalue);
      break;
   case CMD_GET:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = nulldev_get(info, channel, pvalue);
      break;
   case CMD_GET_ALL:
      info = va_arg(argptr, void *);
      channel = va_arg(argptr, INT);
      pvalue = va_arg(argptr, float *);
      status = nulldev_get_all(info, channel, pvalue);
      break;
   default:
      break;
   }
   va_end(argptr);
   return status;
}