AlcapDAQ:Rootana: midas/examples/basic/odb_test.c File Reference
midas/examples/basic/odb_test.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "midas.h"
Functions
void run_number_changed (HNDLE hDB, HNDLE hKey, void *info)
main ()
Variables
int run_number
Function Documentation
main (void)
Definition at line 36 of file odb_test.c.
References cm_connect_experiment(), cm_disconnect_experiment(), cm_get_experiment_database(), CM_SUCCESS, cm_yield(), db_close_record(), db_find_key(), db_get_value(), db_open_record(), db_set_value(), DB_SUCCESS, hDB, hKey, MODE_READ, run_number, run_number_changed(), size, ss_kbhit(), status, TID_INT, and TRUE.
{
   int status, size;
   HNDLE hDB, hKey;
   /* connect to experiment */
   status = cm_connect_experiment("", "", "ODBTest", NULL);
   if (status != CM_SUCCESS)
      return 1;
   /* get handle to online database */
   cm_get_experiment_database(&hDB, &hKey);
   /* read key "runinfo/run number" */
   size = sizeof(run_number);
   status =
       db_get_value(hDB, 0, "/runinfo/run number", &run_number, &size, TID_INT, TRUE);
   if (status != DB_SUCCESS) {
      printf("Cannot read run number");
      return 0;
   }
   printf("Current run number is %d\n", run_number);
   /* set new run number */
   run_number++;
   db_set_value(hDB, 0, "/runinfo/run number", &run_number, size, 1, TID_INT);
   /* now open run_number with automatic updates */
   db_find_key(hDB, 0, "/runinfo/run number", &hKey);
   db_open_record(hDB, hKey, &run_number, sizeof(run_number),
                  MODE_READ, run_number_changed, NULL);
   printf("Waiting for run number to change. Hit RETURN to abort\n");
   do {
      cm_yield(1000);
   } while (!ss_kbhit());
   db_close_record(hDB, hKey);
   /* disconnect from experiment */
   cm_disconnect_experiment();
   return 1;
}
void run_number_changed (HNDLE hDB, HNDLE hKey, void * info)
Definition at line 31 of file odb_test.c.
References run_number.
Referenced by main().
{
   printf("New run number: %d\n", run_number);
}
Variable Documentation
int run_number
Definition at line 29 of file odb_test.c.