AlcapDAQ:Rootana: midas/gui/hvedit/qt/Qt_hvEdit.cpp File Reference
midas/gui/hvedit/qt/Qt_hvEdit.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include <qapplication.h>
#include <qmessagebox.h>
#include <qfiledialog.h>
#include <qlineedit.h>
#include <qlistbox.h>
#include <qtable.h>
#include <qtabwidget.h>
#include <qcombobox.h>
#include <qdialog.h>
#include <qaction.h>
#include <qpushbutton.h>
#include <qdatetime.h>
#include <qprinter.h>
#include <qpainter.h>
#include <qpaintdevicemetrics.h>
#include "midas.h"
#include "Qt_fileList.h"
#include "Qt_hvEditAbout.h"
#include "Qt_Connect.h"
#include "Qt_hvEdit.h"
#include "help/helpwindow.h"
#include "globals.h"
Functions
void namesChanged (int, int, void *)
void HVChanged (HNDLE hDB, HNDLE hKey, void *info)
Function Documentation
void HVChanged (HNDLE hDB, HNDLE hKey, void * info)
This function gets linked to the open records (demand and measured) by the db_open_record calls. Whenever a record changes, cm_yield first updates the local copy of the record and then calls odb_update
Return: void
Parameters:
hDB Handle to the ODB.
hKey Handle to the corresponding key.
info Pointer to the GUI.
Definition at line 1626 of file Qt_hvEdit.cpp.
References MidasMessage(), and Qt_hvEdit::updateTable().
Referenced by Qt_hvEdit::updateChannelDefinitions().
{
  Qt_hvEdit  *dlg;
  if (hDB);  // only there to cheat the compiler warning hDB never used ...
  if (hKey); // only there to cheat the compiler warning hKey never used ...
  dlg = (Qt_hvEdit *) info;
  if (dlg == NULL) {
    MidasMessage(">> HVChanges: Couldn't get Main Window!!");
  } else {
    dlg->updateTable(-1);
  }
}
void namesChanged (int , int , void *)
A member function cannot be passed to db_open_record. Therefore, NamesChanged works as a stub to call Qt_hvEdit::updateChannelDefinition.
Return: void
Definition at line 1605 of file Qt_hvEdit.cpp.
References Qt_hvEdit::updateChannelDefinitions(), and Qt_hvEdit::updateTable().
Referenced by Qt_hvEdit::updateChannelDefinitions().
{
  Qt_hvEdit *dlg;
  dlg = (Qt_hvEdit *) qApp->activeWindow();
  dlg->updateChannelDefinitions();
  dlg->updateTable(-1);
}