AlcapDAQ:Rootana: midas/examples/lowlevel/rpc_srvr.c File Reference
midas/examples/lowlevel/rpc_srvr.c File Reference
#include "midas.h"
#include <stdio.h>
Defines
#define RPC_MYTEST RPC_MIN_ID
Functions
INT rpc_mytest (BYTE b, WORD w, INT i, float f, double d, BYTE *b1, WORD *w1, INT *i1, float *f1, double *d1)
INT rpc_dispatch (INT index, void *prpc_param[])
main ()
Variables
RPC_LIST rpc_list []
Define Documentation
#define RPC_MYTEST RPC_MIN_ID
Definition at line 31 of file rpc_srvr.c.
Function Documentation
main (void)
Definition at line 100 of file rpc_srvr.c.
References cm_yield(), rpc_dispatch(), rpc_register_functions(), rpc_register_server(), rpc_server_shutdown(), rpc_set_debug(), RPC_SHUTDOWN, RPC_SUCCESS, ST_REMOTE, and status.
{
   INT status, port;
   /* register RPC server under port 1750 */
   port = 1750;
   status = rpc_register_server(ST_REMOTE, "", &port, NULL);
   if (status != RPC_SUCCESS) {
      printf("Cannot start server");
      return 0;
   }
   /* Register function list. Calls get forwarded to rpc_dispatch */
   rpc_register_functions(rpc_list, rpc_dispatch);
   /* Print debugging messages */
   rpc_set_debug((void (*)(char *)) puts, 0);
   /* Server loop */
   while (cm_yield(1000) != RPC_SHUTDOWN);
   /* Shutdown server */
   rpc_server_shutdown();
   return 1;
}
INT rpc_dispatch (INT index, void * prpc_param[])
Definition at line 81 of file rpc_srvr.c.
References CBYTE, CDOUBLE, CFLOAT, CINT, cm_msg, CPBYTE, CPDOUBLE, CPFLOAT, CPINT, CPWORD, CWORD, MERROR, rpc_mytest(), RPC_MYTEST, and status.
{
   INT status;
   switch (index) {
   case RPC_MYTEST:
      status = rpc_mytest(CBYTE(0), CWORD(1), CINT(2), CFLOAT(3), CDOUBLE(4),
                          CPBYTE(5), CPWORD(6), CPINT(7), CPFLOAT(8), CPDOUBLE(9));
      break;
   default:
      cm_msg(MERROR, "rpc_dispatch", "received unrecognized command");
   }
   return status;
}
INT rpc_mytest (BYTE b, WORD w, INT i, float f, double d, BYTE * b1, WORD * w1, INT * i1, float * f1, double * d1)
Definition at line 68 of file rpc_srvr.c.
Referenced by rpc_dispatch().
{
   *b1 = b * 2;
   *w1 = w * 2;
   *i1 = i * 2;
   *f1 = f * 2;
   *d1 = d * 2;
   return 1;
}
Variable Documentation
RPC_LIST rpc_list[]
Definition at line 33 of file rpc_srvr.c.