AlcapDAQ:Rootana: midas/examples/lowlevel/rpc_test.c File Reference
midas/examples/lowlevel/rpc_test.c File Reference
#include "midas.h"
#include "mrpc.h"
#include <stdio.h>
Functions
main ()
Function Documentation
main (void)
Definition at line 37 of file rpc_test.c.
References cm_connect_experiment(), cm_disconnect_experiment(), CM_SUCCESS, d, host_name, i, rpc_call(), RPC_TEST, ss_gets(), and status.
{
   char host_name[256];
   INT status;
   BYTE b;
   WORD w;
   INT i;
   float f;
   double d;
#ifdef OS_VXWORKS
   strcpy(host_name, ahost_name);
#else
   printf("Remote host IP address: ");
   ss_gets(host_name, 256);
#endif
   status = cm_connect_experiment(host_name, "", "RPC_TEST", NULL);
   if (status != CM_SUCCESS)
      return 1;
   f = 3.5f;
   d = 4.5;
   /* rpc_test just doubles numbers */
   rpc_call(RPC_TEST, 1, 2, 3l, f, d, &b, &w, &i, &f, &d);
   printf("\nResult should be:  2 4 6 7.0 9.0\n");
   printf("Result is:         %d %d %ld %1.1f %1.1lf\n", b, w, i, f, d);
   printf("\nhit return...");
   b = getchar();
   cm_disconnect_experiment();
   return 1;
}