AlcapDAQ:Rootana: midas/examples/lowlevel/rpc_clnt.c File Reference
midas/examples/lowlevel/rpc_clnt.c File Reference
#include "midas.h"
#include <stdio.h>
Defines
#define RPC_MYTEST RPC_MIN_ID
Functions
main ()
Variables
RPC_LIST rpc_list []
Define Documentation
#define RPC_MYTEST RPC_MIN_ID
Definition at line 32 of file rpc_clnt.c.
Referenced by main(), and rpc_dispatch().
Function Documentation
main (void)
Definition at line 70 of file rpc_clnt.c.
References d, FALSE, hConn, host_name, i, rpc_client_call(), rpc_client_connect(), rpc_client_disconnect(), RPC_MYTEST, rpc_register_client(), RPC_SUCCESS, ss_gets(), and status.
{
   char host_name[80];
   HNDLE hConn;
   INT status;
   BYTE b;
   WORD w;
   INT i;
   float f;
   double d;
   printf("Remote host name: ");
   ss_gets(host_name, sizeof(host_name));
   /* register this as an RPC client with rpc_list */
   rpc_register_client("MYCLIENT", rpc_list);
   /* connect to RPC server */
   status = rpc_client_connect(host_name, 1750, "", &hConn);
   if (status != RPC_SUCCESS) {
      printf("Cannot connect to RPC server running on %s at port 1750.\n", host_name);
      return 0;
   }
   f = 3.5f;
   d = 4.5;
   /* rpc_mytest just doubles numbers */
   rpc_client_call(hConn, RPC_MYTEST, 1, 2, 3l, f, d, &b, &w, &i, &f, &d);
   printf("\nResult should be:  2 4 6 7.0 9.0\n");
   printf("Result is:         %d %d %ld %1.1f %1.1lf\n", b, w, i, f, d);
   printf("\nhit return...");
   b = getchar();
   /* disconnect this client from server */
   rpc_client_disconnect(hConn, FALSE);
   return 1;
}
Variable Documentation
RPC_LIST rpc_list[]
Definition at line 36 of file rpc_clnt.c.