AlcapDAQ:Rootana: midas/drivers/bus/rs232.c File Reference
midas/drivers/bus/rs232.c File Reference
#include "midas.h"
Data Structures
struct RS232_SETTINGS
struct RS232_INFO
Defines
#define RS232_SETTINGS_STR "\RS232 Port = STRING : [32] com1\n\Baud = INT : 9600\n\Parity = CHAR : N\n\Data Bit = INT : 8\n\Stop Bit = INT : 1\n\Flow control = INT : 0\n\"
Functions
int rs232_init (HNDLE hkey, void **pinfo)
INT rs232 (INT cmd,...)
Variables
static int debug_flag = 0
Define Documentation
#define RS232_SETTINGS_STR "\RS232 Port = STRING : [32] com1\n\Baud = INT : 9600\n\Parity = CHAR : N\n\Data Bit = INT : 8\n\Stop Bit = INT : 1\n\Flow control = INT : 0\n\"
Definition at line 71 of file rs232.c.
Referenced by rs232_init().
Function Documentation
INT rs232 (INT cmd, ...)
Definition at line 951 of file rs232.c.
References CMD_DEBUG, CMD_EXIT, CMD_GETS, CMD_INIT, CMD_NAME, CMD_PUTS, CMD_READ, CMD_WRITE, debug_flag, FE_SUCCESS, and rs232_init().
Referenced by main().
{
   va_list argptr;
   HNDLE hkey;
   INT status, size, timeout;
   void *info;
   char *str, *pattern;
   va_start(argptr, cmd);
   status = FE_SUCCESS;
   switch (cmd) {
   case CMD_INIT:
      hkey = va_arg(argptr, HNDLE);
      info = va_arg(argptr, void *);
      status = rs232_init(hkey, info);
      break;
   case CMD_EXIT:
      info = va_arg(argptr, void *);
      status = rs232_exit(info);
      break;
   case CMD_NAME:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      strcpy(str, "rs232");
      break;
   case CMD_WRITE:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, int);
      status = rs232_write(info, str, size);
      break;
   case CMD_READ:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, INT);
      timeout = va_arg(argptr, INT);
      status = rs232_read(info, str, size, timeout);
      break;
   case CMD_PUTS:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      status = rs232_puts(info, str);
      break;
   case CMD_GETS:
      info = va_arg(argptr, void *);
      str = va_arg(argptr, char *);
      size = va_arg(argptr, INT);
      pattern = va_arg(argptr, char *);
      timeout = va_arg(argptr, INT);
      status = rs232_gets(info, str, size, pattern, timeout);
      break;
   case CMD_DEBUG:
      status = va_arg(argptr, INT);
      debug_flag = status;
      break;
   }
   va_end(argptr);
   return status;
}
int rs232_init (HNDLE hkey, void ** pinfo)
Definition at line 916 of file rs232.c.
References RS232_SETTINGS::baud, cm_get_experiment_database(), RS232_SETTINGS::data_bit, db_create_record(), db_find_key(), db_get_record(), DB_SUCCESS, RS232_INFO::fd, FE_ERR_HW, FE_ERR_ODB, RS232_SETTINGS::flow_control, hDB, RS232_SETTINGS::parity, RS232_SETTINGS::port, RS232_SETTINGS_STR, RS232_INFO::settings, RS232_SETTINGS::stop_bit, and SUCCESS.
Referenced by rs232().
{
   HNDLE hDB, hkeybd;
   INT size, status;
   RS232_INFO *info;
   /* allocate info structure */
   info = calloc(1, sizeof(RS232_INFO));
   *pinfo = info;
   cm_get_experiment_database(&hDB, NULL);
   /* create RS232 settings record */
   status = db_create_record(hDB, hkey, "BD", RS232_SETTINGS_STR);
   if (status != DB_SUCCESS)
      return FE_ERR_ODB;
   db_find_key(hDB, hkey, "BD", &hkeybd);
   size = sizeof(info->settings);
   db_get_record(hDB, hkeybd, &info->settings, &size, 0);
   /* open port */
   info->fd = rs232_open(info->settings.port,
                         info->settings.baud, info->settings.parity,
                         info->settings.data_bit, info->settings.stop_bit,
                         info->settings.flow_control);
   if (info->fd < 0)
      return FE_ERR_HW;
   return SUCCESS;
}
Variable Documentation
int debug_flag = 0 [static]
Definition at line 60 of file rs232.c.
Referenced by rs232().