AlcapDAQ:Rootana: midas/mscb/embedded/scs_210_tc600.c File Reference
midas/mscb/embedded/scs_210_tc600.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mscb.h"
Functions
unsigned char tc600_write (unsigned short param, unsigned char len, unsigned long value)
void user_write (unsigned char index) reentrant
void write_gain (void)
void user_init (unsigned char init)
unsigned char user_read (unsigned char index)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
unsigned char tc600_read (unsigned short param, char *result)
void user_loop (void)
Variables
char code node_name [] = "TC600"
unsigned char idata _n_sub_addr = 1
bit terminal_mode
struct {
unsigned char pump_on
unsigned char vent_on
unsigned short rot_speed
float tmp_current
unsigned char baud
unsigned char address
} user_data
MSCB_INFO_VAR code variables []
unsigned char xdata in_buf [300]
unsigned char xdata out_buf [300]
Function Documentation
unsigned char tc600_read (unsigned short param, char * result)
Definition at line 176 of file scs_210_tc600.c.
References flush(), gets_wait(), i, j, and user_data.
Referenced by user_loop().
{
   char idata str[32];
   unsigned char i, j, cs, len;
   sprintf(str, "%03Bd00%03d02=?", user_data.address, param);
   for (i = cs = 0; i < 12; i++)
      cs += str[i];
   sprintf(str + 12, "%03Bd\r", cs);
   printf(str);
   flush();
   i = gets_wait(str, sizeof(str), 200);
   if (i > 2) {
      len = (str[8] - '0') * 10 + (str[9] - '0');
      for (j = 0; j < len; j++)
         result[j] = str[10 + j];
      result[j] = 0;
      return len;
   }
   return 0;
}
unsigned char tc600_write (unsigned short param, unsigned char len, unsigned long value)
Definition at line 205 of file scs_210_tc600.c.
References flush(), gets_wait(), i, and user_data.
Referenced by user_init(), and user_loop().
{
   char idata str[32];
   unsigned char i, cs;
   if (len == 6)
      sprintf(str, "%03Bd10%03d06%06ld", user_data.address, param, value);
   else if (len == 3)
      sprintf(str, "%03Bd10%03d03%03ld", user_data.address, param, value);
   for (i = cs = 0; i < 16; i++)
      cs += str[i];
   sprintf(str + 16, "%03Bd\r", cs);
   printf(str);
   flush();
   i = gets_wait(str, sizeof(str), 200);
   return i;
}
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 166 of file scs_210_tc600.c.
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void user_init (unsigned char init)
Definition at line 101 of file scs_210_tc600.c.
References delay_ms(), tc600_write(), uart_init(), and user_data.
{
   /* initialize UART1 */
   if (init) {
      user_data.baud = 1;       // 9600 by default
      user_data.address = 1;
   }
   uart_init(1, user_data.baud);
   /* turn on turbo pump motor (not pump station) */
   tc600_write(23, 6, 111111);
   /* vent mode */
   tc600_write(30, 3, 0);
   delay_ms(0);                 // linker bug otherwise!
}
void user_loop (void)
Definition at line 228 of file scs_210_tc600.c.
References last, tc600_read(), tc600_write(), terminal_mode, time, and user_data.
{
   char idata str[32];
   static unsigned long last = 0;
   static char pump_on_last = -1;
   static char vent_on_last = -1;
   if (!terminal_mode && time() > last + 100) {
      last = time();
      if (user_data.pump_on != pump_on_last) {
         tc600_write(10, 6, user_data.pump_on ? 111111 : 0);
         pump_on_last = user_data.pump_on;
      }
      if (user_data.vent_on != vent_on_last) {
         tc600_write(12, 6, user_data.vent_on ? 111111 : 0);
         vent_on_last = user_data.vent_on;
      }
      if (tc600_read(309, str))
         user_data.rot_speed = atoi(str);
      if (tc600_read(310, str))
         user_data.tmp_current = atoi(str) / 100.0;
   }
}
unsigned char user_read (unsigned char index)
Definition at line 149 of file scs_210_tc600.c.
References c, getchar_nowait(), and out_buf.
{
   char c;
   if (index == 0) {
      c = getchar_nowait();
      if (c != -1) {
         out_buf[1] = c;
         return 1;
      }
   }
   return 0;
}
void user_write (unsigned char index)
Definition at line 127 of file scs_210_tc600.c.
References i, in_buf, index, n, putchar(), terminal_mode, uart_init(), and user_data.
{
   unsigned char i, n;
   if (index == 0) {
      if (in_buf[2] == 27)
         terminal_mode = 0;
      else if (in_buf[2] == 0)
         terminal_mode = 1;
      else {
         n = (in_buf[0] & 0x07) - 1;
         for (i = 0; i < n; i++)
            putchar(in_buf[i + 2]);
      }
   }
   if (index == 5)
      uart_init(1, user_data.baud);
}
void write_gain (void)
Definition at line 219 of file scs_500.c.
{
   unsigned char i;
   SR_STROBE = 0;
   SR_CLOCK = 0;
   for (i = 0; i < 4; i++) {
      SR_DATA = ((user_data.gain[3 - i] & 0x02) > 0);   // first bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
      SR_DATA = ((user_data.gain[3 - i] & 0x01) > 0);   // second bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
   }
   for (i = 0; i < 4; i++) {
      SR_DATA = ((user_data.gain[7 - i] & 0x02) > 0);   // first bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
      SR_DATA = ((user_data.gain[7 - i] & 0x01) > 0);   // second bit ext. PGA
      SR_CLOCK = 1;
      SR_CLOCK = 0;
   }
   SR_DATA = 0;
   SR_STROBE = 1;
   SR_STROBE = 0;
}
Variable Documentation
unsigned char idata _n_sub_addr = 1
Definition at line 57 of file scs_210_tc600.c.
unsigned char address
Definition at line 74 of file scs_210_tc600.c.
Referenced by probe(), and validateModel().
unsigned char baud
Definition at line 73 of file scs_210_tc600.c.
unsigned char xdata in_buf[300]
Definition at line 227 of file mscbmain.c.
char code node_name[] = "TC600"
Definition at line 54 of file scs_210_tc600.c.
unsigned char xdata out_buf[300]
Definition at line 227 of file mscbmain.c.
unsigned char pump_on
Definition at line 68 of file scs_210_tc600.c.
unsigned short rot_speed
Definition at line 70 of file scs_210_tc600.c.
bit terminal_mode
Definition at line 59 of file scs_210_tc600.c.
float tmp_current
Definition at line 71 of file scs_210_tc600.c.
struct { ... } user_data
MSCB_INFO_VAR code variables[]
Initial value:
 {
   1, UNIT_ASCII,   0, 0, MSCBF_DATALESS, "RS232", 0,
   1, UNIT_BOOLEAN, 0, 0,              0, "Pump on", &user_data.pump_on,
   1, UNIT_BOOLEAN, 0, 0,              0, "Vent on", &user_data.vent_on,
   2, UNIT_HERTZ,   0, 0,              0, "RotSpd", &user_data.rot_speed,
   4, UNIT_AMPERE,  0, 0,    MSCBF_FLOAT, "TMPcur", &user_data.tmp_current,
   1, UNIT_BAUD,    0, 0,              0, "Baud", &user_data.baud,
   1, UNIT_BYTE,    0, 0,              0, "Address", &user_data.address,
   0
}
Definition at line 78 of file scs_210_tc600.c.
unsigned char vent_on
Definition at line 69 of file scs_210_tc600.c.