AlcapDAQ:Rootana: midas/mscb/embedded/scs_300.c File Reference
midas/mscb/embedded/scs_300.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mscb.h"
Defines
#define LPT_DATA P1
Functions
void user_write (unsigned char channel) reentrant
void user_init (unsigned char init)
unsigned char user_read (unsigned char index)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
char putchar (char c)
char getchar_nowait ()
unsigned char gets_wait (char *str, unsigned char size, unsigned char timeout)
void user_loop (void)
Variables
char code node_name [] = "SCS-300"
unsigned char idata _n_sub_addr = 1
struct {
float value [4]
} user_data
MSCB_INFO_VAR code variables []
sbit LPT_STROBE = P2 ^ 3
sbit LPT_INIT = P2 ^ 4
sbit LPT_SELECT = P2 ^ 5
sbit LPT_ACK = P2 ^ 6
sbit LPT_BUSY = P2 ^ 7
Define Documentation
#define LPT_DATA P1
Definition at line 86 of file scs_300.c.
Referenced by check_lpt(), check_rs485(), getchar_nowait(), putchar(), setup(), and user_init().
Function Documentation
char getchar_nowait (void)
Definition at line 164 of file scs_300.c.
References c, LPT_BUSY, LPT_DATA, and LPT_SELECT.
Referenced by gets_wait(), user_loop(), and user_read().
{
   char c;
   /* if busy signal high -> no data */
   if (LPT_BUSY == 1)
      return -1;
   /* read byte */
   c = LPT_DATA;
   /* singal received data */
   LPT_SELECT = 0;
   /* wait for busy go high */
   while (LPT_BUSY == 0);
   /* remove select */
   LPT_SELECT = 1;
}
unsigned char gets_wait (char * str, unsigned char size, unsigned char timeout)
Definition at line 185 of file scs_300.c.
References c, getchar_nowait(), i, time, and yield().
Referenced by tc600_read(), tc600_write(), and user_loop().
{
   unsigned long idata start;
   unsigned char i;
   char c;
   start = time();
   i = 0;
   do {
      c = getchar_nowait();
      if (c != -1 && c != '\n') {
         if (c == '\r') {
            str[i] = 0;
            return i;
         }
         str[i++] = c;
         if (i == size)
            return i;
      }
      yield();
   } while (time() < start + timeout);
   return 0;
}
char putchar (char c)
Definition at line 141 of file scs_300.c.
References LPT_ACK, LPT_DATA, and LPT_STROBE.
{
   /* wait for acknowledge to go low */
   while (LPT_ACK);
   /* output data */
   LPT_DATA = c;
   /* negative strobe */
   LPT_STROBE = 0;
   /* wati for acknowledge to go high */
   while (!LPT_ACK);
   /* remove strobe */
   LPT_STROBE = 1;
   /* clear data for next input */
   LPT_DATA = 0xFF;
   return c;
}
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 131 of file scs_300.c.
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void user_init (unsigned char init)
Definition at line 101 of file scs_300.c.
References LPT_ACK, LPT_BUSY, LPT_DATA, LPT_INIT, LPT_SELECT, and LPT_STROBE.
{
   /* set initial state of lines */
   LPT_DATA = 0xFF;
   LPT_STROBE = 1;
   LPT_INIT = 1;
   LPT_SELECT = 1;
   LPT_ACK = 1;
   LPT_BUSY = 1;
   if (init);
}
void user_loop (void)
Definition at line 214 of file scs_300.c.
References gets_wait(), i, n, and yield().
{
   char idata str[32];
   unsigned char i, n;
   return;                      // do not execute example code
   /* this could be some example code to demonstrate a 4 chn readout */
   for (i = 0; i < 4; i++) {
      /* send data request */
      printf("READ %d\r\n", i); // goes through putchar()
      /* wait for reply for 2 seconds */
      n = gets_wait(str, sizeof(str), 200);
      /* if correct response, interprete data */
 //     if (n == 10)
 //        user_data.value[i] = atof(str);
      yield();
   }
}
unsigned char user_read (unsigned char index)
Definition at line 123 of file scs_300.c.
{
   if (index);
   return 0;
}
void user_write (unsigned char channel)
Definition at line 116 of file scs_300.c.
References index.
{
   if (index);
}
Variable Documentation
unsigned char idata _n_sub_addr = 1
Definition at line 61 of file scs_300.c.
sbit LPT_ACK = P2 ^ 6
Definition at line 92 of file scs_300.c.
sbit LPT_BUSY = P2 ^ 7
Definition at line 93 of file scs_300.c.
sbit LPT_INIT = P2 ^ 4
Definition at line 90 of file scs_300.c.
Referenced by user_init().
sbit LPT_SELECT = P2 ^ 5
Definition at line 91 of file scs_300.c.
Referenced by getchar_nowait(), and user_init().
sbit LPT_STROBE = P2 ^ 3
Definition at line 89 of file scs_300.c.
char code node_name[] = "SCS-300"
Definition at line 58 of file scs_300.c.
struct { ... } user_data
float value[4]
Definition at line 68 of file scs_300.c.
MSCB_INFO_VAR code variables[]
Initial value:
 {
   4, UNIT_UNDEFINED, 0, 0, MSCBF_FLOAT, "Data0", &user_data.value[0],
   4, UNIT_UNDEFINED, 0, 0, MSCBF_FLOAT, "Data1", &user_data.value[1],
   4, UNIT_UNDEFINED, 0, 0, MSCBF_FLOAT, "Data2", &user_data.value[2],
   4, UNIT_UNDEFINED, 0, 0, MSCBF_FLOAT, "Data3", &user_data.value[3],
   0
}
Definition at line 71 of file scs_300.c.