AlcapDAQ:Rootana: midas/mscb/embedded/scs_910.c File Reference
midas/mscb/embedded/scs_910.c File Reference
#include <stdio.h>
#include <math.h>
#include "mscb.h"
Defines
#define REG_STATUS 0
#define REG_MODE 1
#define REG_CONTROL 2
#define REG_FILTER 3
#define REG_ADCDATA 4
#define REG_ADCOFFSET 5
#define REG_ADCGAIN 6
#define REG_IOCONTROL 7
Functions
void user_write (unsigned char index) reentrant
void write_adc (unsigned char n, unsigned char a, unsigned char d)
void user_init (unsigned char init)
void set_adc_ncs (unsigned char n, unsigned char d)
unsigned char get_adc_dout (unsigned char n)
unsigned char get_adc_nrdy (unsigned char n)
void read_adc24 (unsigned char n, unsigned char a, unsigned long *d)
void adc_read ()
unsigned char user_read (unsigned char index)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
void user_loop (void)
Variables
bit FREEZE_MODE
bit DEBUG_MODE
char code node_name [] = "SCS-910"
unsigned char idata _n_sub_addr = 1
sbit EXT_WATCHDOG = P0 ^ 3
sbit ADC_SCLK = P1 ^ 6
sbit ADC_DIN = P1 ^ 7
sbit AD1_NCS = P1 ^ 0
sbit AD2_NCS = P1 ^ 1
sbit AD3_NCS = P1 ^ 2
sbit AD4_NCS = P1 ^ 3
sbit AD1_DOUT = P0 ^ 4
sbit AD2_DOUT = P0 ^ 5
sbit AD3_DOUT = P0 ^ 6
sbit AD4_DOUT = P0 ^ 7
struct {
float adc [20]
} user_data
MSCB_INFO_VAR code variables []
SYS_INFO sys_info
unsigned char code adc_index [] = {12, 10, 9, 8, 11}
static unsigned char iadc
static unsigned char ichn
static unsigned long last_check
Define Documentation
#define REG_ADCDATA 4
Definition at line 64 of file scs_910.c.
#define REG_ADCGAIN 6
Definition at line 66 of file scs_910.c.
#define REG_ADCOFFSET 5
Definition at line 65 of file scs_910.c.
#define REG_CONTROL 2
Definition at line 62 of file scs_910.c.
#define REG_FILTER 3
Definition at line 63 of file scs_910.c.
#define REG_IOCONTROL 7
Definition at line 67 of file scs_910.c.
#define REG_MODE 1
Definition at line 61 of file scs_910.c.
#define REG_STATUS 0
Definition at line 60 of file scs_910.c.
Function Documentation
void adc_read ()
Definition at line 325 of file scs_910.c.
References adc_index, DISABLE_INTERRUPTS, ENABLE_INTERRUPTS, get_adc_nrdy(), i, iadc, ichn, last_check, read_adc24(), REG_ADCDATA, REG_CONTROL, time, user_data, value, and write_adc().
{
   unsigned char i, next, ivalue;
   unsigned long value;
   float gvalue;
   if (get_adc_nrdy(iadc)) {
       if (time() - last_check < 30)
          return;
      write_adc(iadc, REG_CONTROL, 0x0F); // try to restart ADC
   }
   last_check = time();
   read_adc24(iadc, REG_ADCDATA, &value);
#ifdef UNIPOLAR
   ivalue = iadc * 10 + ichn;
#else
   ivalue = iadc * 5 + ichn;
#endif
   /* convert to volts */
   gvalue = ((float)value / (1l<<24)) * 2.56;
   /* round result to 5 digits */
   gvalue = floor(gvalue*1E5+0.5)/1E5;
   DISABLE_INTERRUPTS;
   user_data.adc[ivalue] = gvalue;
   ENABLE_INTERRUPTS;
   /* start next channel on this ADC */
   next = ichn+1;
#ifdef UNIPOLAR
   if (next == 10)
#else
   if (next == 5)
#endif
     next = 0;
   i = adc_index[next];
   write_adc(iadc, REG_CONTROL, (i << 4) | 0x0F); // adc_chn, +2.56V range
   /* switch to next ADC */
   iadc++;
   if (iadc == 4) {
     iadc = 0;
     ichn++;
#ifdef UNIPOLAR
     if (ichn == 10)
#else
     if (ichn == 5)
#endif
        ichn = 0;
   }
}
unsigned char get_adc_dout (unsigned char n)
Definition at line 209 of file scs_910.c.
References AD1_DOUT, AD2_DOUT, AD3_DOUT, and AD4_DOUT.
Referenced by read_adc24().
{
   switch (n) {
      case 0: return AD1_DOUT;
      case 1: return AD2_DOUT;
      case 2: return AD3_DOUT;
      case 3: return AD4_DOUT;
   }
}
unsigned char get_adc_nrdy (unsigned char n)
Definition at line 219 of file scs_910.c.
References ADBUSY, ADC0H, ADC0L, ADCINT, AMX0SL, and value.
Referenced by adc_read().
{
   unsigned int value;
   switch (n) {
      case 0: AMX0SL = 1; break;
      case 1: AMX0SL = 0; break;
      case 2: AMX0SL = 3; break;
      case 3: AMX0SL = 2; break;
   }
   ADCINT = 0;
   ADBUSY = 1;
   while (!ADCINT);
   value = (ADC0L | (ADC0H << 8));
   return (value > 2048);
}
void read_adc24 (unsigned char n, unsigned char a, unsigned long * d)
Definition at line 277 of file scs_910.c.
References ADC_DIN, ADC_SCLK, get_adc_dout(), i, and set_adc_ncs().
{
   unsigned char i, m;
   /* write to communication register */
   set_adc_ncs(n, 0);
   /* write zero to !WEN and one to R/!W */
   for (i=0 ; i<4 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = (i == 1);
      ADC_SCLK = 1;
   }
   /* register address */
   for (i=0,m=8 ; i<4 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = (a & m) > 0;
      ADC_SCLK = 1;
      m >>= 1;
   }
   set_adc_ncs(n, 1);
   /* read from selected data register */
   set_adc_ncs(n, 0);
   for (i=0,*d=0 ; i<24 ; i++) {
      *d <<= 1;
      ADC_SCLK = 0;
      *d |= get_adc_dout(n);
      ADC_SCLK = 1;
   }
   set_adc_ncs(n, 1);
}
void set_adc_ncs (unsigned char n, unsigned char d)
Definition at line 199 of file scs_910.c.
References AD1_NCS, AD2_NCS, AD3_NCS, and AD4_NCS.
Referenced by read_adc24(), and write_adc().
{
   switch (n) {
      case 0: AD1_NCS = d; break;
      case 1: AD2_NCS = d; break;
      case 2: AD3_NCS = d; break;
      case 3: AD4_NCS = d; break;
   }
}
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 399 of file scs_910.c.
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void user_init (unsigned char init)
Definition at line 143 of file scs_910.c.
References ADC0CF, ADC0CN, AMX0CF, DAC0CN, DAC1CN, i, P0, P1, PRT0CF, PRT1CF, REF0CN, REG_CONTROL, REG_FILTER, REG_MODE, and write_adc().
{
   unsigned char i;
   AMX0CF = 0x00;               // select single ended analog inputs
   ADC0CF = 0xE0;               // 16 system clocks, gain 1
   ADC0CN = 0x80;               // enable ADC
   REF0CN = 0x03;               // enable internal reference, BIAS on
   DAC0CN = 0x00;               // disable DAC0
   DAC1CN = 0x00;               // disable DAC1
   /* push-pull:
      P0.0    TX
      P0.1
      P0.2
      P0.3
      P0.4    ADC1 in
      P0.5    ADC2 in
      P0.6    ADC3 in
      P0.7    ADC4 in
    */
   PRT0CF = 0x01;
   P0 = 0xFF;
   /* push-pull:
      P1.0    ADC1_NCS
      P1.1    ADC2_NCS
      P1.2    ADC3_NCS
      P1.3    ADC4_NCS
      P1.4
      P1.5
      P1.6    ADC_DIN
      P1.7    ADC_SCLK
    */
   PRT1CF = 0xCF;
   P1 = 0xFF;
   /* initial EEPROM value */
   if (init) {
   }
   /* set-up ADC */
   for (i=0 ; i<4 ; i++) {
      write_adc(i, REG_FILTER, 82);                   // SF value for 50Hz rejection
      write_adc(i, REG_MODE, 0x13);                   // continuous conversion, 10 channels
      write_adc(i, REG_CONTROL, 0x0F);                // start first conversion
   }
}
void user_loop (void)
Definition at line 409 of file scs_910.c.
References adc_read().
{
   adc_read();
}
unsigned char user_read (unsigned char index)
Definition at line 391 of file scs_910.c.
{
   if (index);
   return 0;
}
void user_write (unsigned char index)
Definition at line 384 of file scs_910.c.
References index.
{
   if (index);
}
void write_adc (unsigned char n, unsigned char a, unsigned char d)
Definition at line 238 of file scs_910.c.
References ADC_DIN, ADC_SCLK, i, and set_adc_ncs().
{
   unsigned char i, m;
   /* write to communication register */
   set_adc_ncs(n, 0);
   /* write zeros to !WEN and R/!W */
   for (i=0 ; i<4 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = 0;
      ADC_SCLK = 1;
   }
   /* register address */
   for (i=0,m=8 ; i<4 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = (a & m) > 0;
      ADC_SCLK = 1;
      m >>= 1;
   }
   set_adc_ncs(n, 1);
   /* write to selected data register */
   set_adc_ncs(n, 0);
   for (i=0,m=0x80 ; i<8 ; i++) {
      ADC_SCLK = 0;
      ADC_DIN  = (d & m) > 0;
      ADC_SCLK = 1;
      m >>= 1;
   }
   set_adc_ncs(n, 1);
}
Variable Documentation
unsigned char idata _n_sub_addr = 1
Definition at line 40 of file scs_910.c.
sbit AD1_DOUT = P0 ^ 4
Definition at line 53 of file scs_910.c.
Referenced by get_adc_dout().
sbit AD1_NCS = P1 ^ 0
Definition at line 48 of file scs_910.c.
Referenced by set_adc_ncs().
sbit AD2_DOUT = P0 ^ 5
Definition at line 54 of file scs_910.c.
Referenced by get_adc_dout().
sbit AD2_NCS = P1 ^ 1
Definition at line 49 of file scs_910.c.
Referenced by set_adc_ncs().
sbit AD3_DOUT = P0 ^ 6
Definition at line 55 of file scs_910.c.
Referenced by get_adc_dout().
sbit AD3_NCS = P1 ^ 2
Definition at line 50 of file scs_910.c.
Referenced by set_adc_ncs().
sbit AD4_DOUT = P0 ^ 7
Definition at line 56 of file scs_910.c.
Referenced by get_adc_dout().
sbit AD4_NCS = P1 ^ 3
Definition at line 51 of file scs_910.c.
Referenced by set_adc_ncs().
float adc[20]
Definition at line 77 of file scs_910.c.
sbit ADC_DIN = P1 ^ 7
Definition at line 46 of file scs_910.c.
unsigned char code adc_index[] = {12, 10, 9, 8, 11}
Definition at line 319 of file scs_910.c.
sbit ADC_SCLK = P1 ^ 6
Definition at line 45 of file scs_910.c.
bit DEBUG_MODE
Definition at line 247 of file mscbmain.c.
sbit EXT_WATCHDOG = P0 ^ 3
Definition at line 42 of file scs_910.c.
bit FREEZE_MODE
Definition at line 249 of file mscbmain.c.
unsigned char iadc [static]
Definition at line 322 of file scs_910.c.
Referenced by adc_read(), and TWFDBankReader::ReadIslandsLoop().
unsigned char ichn [static]
Definition at line 322 of file scs_910.c.
Referenced by adc_read().
unsigned long last_check [static]
Definition at line 323 of file scs_910.c.
Referenced by adc_read().
char code node_name[] = "SCS-910"
Definition at line 35 of file scs_910.c.
SYS_INFO sys_info
Definition at line 239 of file mscbmain.c.
struct { ... } user_data
MSCB_INFO_VAR code variables[]
Definition at line 81 of file scs_910.c.