AlcapDAQ:Rootana: midas/mscb/embedded/scs_500_pt100.c File Reference
midas/mscb/embedded/scs_500_pt100.c File Reference
#include <stdio.h>
#include "mscb.h"
Functions
void user_write (unsigned char channel)
void user_init (void)
unsigned char user_read (unsigned char channel)
void user_write_conf (unsigned char channel)
void user_read_conf (unsigned char channel)
unsigned char user_func (unsigned char idata *data_in, unsigned char idata *data_out)
void adc_read (channel, float *d)
void user_loop (void)
Variables
bit FREEZE_MODE
bit DEBUG_MODE
char code node_name [] = "SCS-500-PT100"
struct {
float temp [8]
} user_data
struct {
float gain_cal
float ofs_cal
} user_conf
float idata gain [8]
MSCB_INFO_CHN code channel []
MSCB_INFO_CHN code conf_param []
SYS_INFO sys_info
Function Documentation
void adc_read (channel , float * d)
Definition at line 164 of file scs_500_pt100.c.
References ADBUSY, ADC0CF, ADC0H, ADC0L, ADCINT, AMX0SL, channel, DISABLE_INTERRUPTS, ENABLE_INTERRUPTS, i, n, user_conf, value, and watchdog_refresh().
{
   unsigned long value;
   unsigned int i, n;
   float gvalue;
   AMX0SL = channel & 0x0F;
   ADC0CF = 0xE0;               // 16 system clocks, gain 1
   n = 1 << (8 + 4);
   value = 0;
   for (i = 0; i < n; i++) {
      DISABLE_INTERRUPTS;
      ADCINT = 0;
      ADBUSY = 1;
      while (!ADCINT);          // wait until conversion ready, does NOT work with ADBUSY!
      ENABLE_INTERRUPTS;
      value += (ADC0L | (ADC0H << 8));
      watchdog_refresh();
   }
   value >>= 8;
   /* convert to volts */
   gvalue = value / 65536.0 * 2.5;
   /* external voltage divider */
   gvalue *= 0.5 * user_conf.gain_cal;
   /* convert to Ohms (15V supply, 2kOhm resistor) */
   gvalue = (2000 * gvalue) / (15 - gvalue);
   /* convert Ohms to Celsius, valid -100.100 deg., error <0.04K */
   gvalue -= 100;
   gvalue = 0.0011 * gvalue * gvalue + 2.5558 * gvalue;
   /* correct for offset */
   gvalue += user_conf.ofs_cal;
   DISABLE_INTERRUPTS;
   *d = gvalue;
   ENABLE_INTERRUPTS;
}
unsigned char user_func (unsigned char idata * data_in, unsigned char idata * data_out)
Definition at line 154 of file scs_500_pt100.c.
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void user_init (void)
Definition at line 101 of file scs_500_pt100.c.
References ADC0CF, ADC0CN, AMX0CF, DAC0CN, DAC1CN, REF0CN, and user_conf.
Referenced by frontend_init(), and setup().
{
   AMX0CF = 0x00;               // select single ended analog inputs
   ADC0CF = 0xE0;               // 16 system clocks, gain 1
   ADC0CN = 0x80;               // enable ADC
   REF0CN = 0x03;               // enable internal reference
   DAC0CN = 0x80;               // enable DAC0
   DAC1CN = 0x80;               // enable DAC1
   /* correct initial EEPROM value */
   if (user_conf.gain_cal < 0.1 || user_conf.gain_cal > 10)
      user_conf.gain_cal = 1;
   if (user_conf.ofs_cal < -1 || user_conf.ofs_cal > 1)
      user_conf.ofs_cal = 0;
   // DEBUG_MODE = 1;
}
void user_loop (void)
Definition at line 212 of file scs_500_pt100.c.
References adc_read(), DEBUG_MODE, i, last, lcd_clear(), lcd_goto(), time, and user_data.
{
   static unsigned char i = 0;
   static unsigned long last = 300;
   static bit first = 1;
   adc_read(i, &user_data.temp[i]);
   i = (i + 1) % 8;
   if (!DEBUG_MODE && time() > last + 30) {
      if (first) {
         lcd_clear();
         first = 0;
      }
      last = time();
      lcd_goto(0, 0);
      printf("CH1: %6.1f C   ", user_data.temp[0]);
      lcd_goto(0, 1);
      printf("CH2: %6.1f C   ", user_data.temp[1]);
   }
}
unsigned char user_read (unsigned char channel)
Definition at line 132 of file scs_500_pt100.c.
{
   if (channel == 0);
   return 0;
}
void user_read_conf (unsigned char channel)
Definition at line 147 of file scs_500_pt100.c.
{
   if (channel);
}
void user_write (unsigned char channel)
Definition at line 125 of file scs_500_pt100.c.
{
   if (channel);
}
void user_write_conf (unsigned char channel)
Definition at line 140 of file scs_500_pt100.c.
{
   if (channel);
}
Variable Documentation
MSCB_INFO_CHN code channel[]
Initial value:
 {
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp0", &user_data.temp[0],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp1", &user_data.temp[1],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp2", &user_data.temp[2],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp3", &user_data.temp[3],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp4", &user_data.temp[4],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp5", &user_data.temp[5],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp6", &user_data.temp[6],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp7", &user_data.temp[7],
   0
}
Definition at line 52 of file scs_500_pt100.c.
MSCB_INFO_CHN code conf_param[]
Initial value:
 {
   4, UNIT_FACTOR, 0, 0, MSCBF_FLOAT, "GainCal", &user_conf.gain_cal,
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "OfsCal", &user_conf.ofs_cal,
   0
}
Definition at line 83 of file scs_500_pt100.c.
bit DEBUG_MODE
Definition at line 247 of file mscbmain.c.
bit FREEZE_MODE
Definition at line 249 of file mscbmain.c.
float idata gain[8]
Definition at line 50 of file scs_500_pt100.c.
float gain_cal
Definition at line 46 of file scs_500_pt100.c.
char code node_name[] = "SCS-500-PT100"
Definition at line 34 of file scs_500_pt100.c.
float ofs_cal
Definition at line 47 of file scs_500_pt100.c.
SYS_INFO sys_info
Definition at line 239 of file mscbmain.c.
float temp[8]
Definition at line 42 of file scs_500_pt100.c.
struct { ... } user_conf
struct { ... } user_data