AlcapDAQ:Rootana: midas/mscb/embedded/scs_800.c File Reference
midas/mscb/embedded/scs_800.c File Reference
#include <stdio.h>
#include "mscb.h"
Functions
void user_write (unsigned char index) reentrant
void set_range ()
unsigned char user_read (unsigned char index)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
void cap_read ()
void user_loop (void)
Variables
bit FREEZE_MODE
bit DEBUG_MODE
char code node_name [] = "SCS-800"
unsigned char idata _n_sub_addr = 1
sbit SR_CLOCK = P0 ^ 4
sbit SR_STROBE = P0 ^ 5
sbit SR_DATAO = P0 ^ 2
sbit NE555_RESET = P0 ^ 7
sbit NE555_TRIGGER = P0 ^ 6
struct {
float cap [8]
signed short ofs [8]
float gain
} user_data
unsigned char range [8]
MSCB_INFO_VAR code variables []
Function Documentation
void cap_read ()
Definition at line 189 of file scs_800.c.
References c, channel, delay_us(), DISABLE_INTERRUPTS, ENABLE_INTERRUPTS, NE555_TRIGGER, overflow, P1, TMR3CN, TMR3H, TMR3L, TMR3RLH, TMR3RLL, user_data, and yield().
Referenced by user_loop().
{
   static unsigned char channel = 0;
   unsigned char m, i;
   unsigned long v;
   float c;
   /* average 10 times */
   for (i = v = 0; i < 10; i++) {
      yield();
      m = (1 << channel);
      /* init timer 3 */
      TMR3L = 0;
      TMR3H = 0;
      TMR3RLL = 0xFF;
      TMR3RLH = 0xFF;
      TMR3CN = (1 << 2);        /* clock/12, Timer 3 enabled */
      /* trigger NE555 */
      NE555_TRIGGER = 0;
      delay_us(1);
      NE555_TRIGGER = 1;
      /* wait until NE555 output goes low again */
      while ((P1 & m) != 0 && (TMR3CN & 0x80) == 0);
      if ((TMR3CN & 0x80) != 0) {
         /* overflow */
         c = 999;
         /* stop timer 3 */
         TMR3CN = 0;
         goto overflow;
      } else {
         /* stop timer 3 */
         TMR3CN = 0;
         /* time in us */
         v += TMR3H * 256 + TMR3L;
      }
   }
   c = (float) v / i / 11.052 * 12;
   /* time in s */
   c /= 1E6;
   /* convert to nF via t = 1.1 * R * C */
   c = c / 1.1 / 5.6E6 * 1E9;
   /* apply overall gain */
   c *= user_data.gain;
   /* general offset 18pF */
   c -= 0.018;
   /* channel offset */
   c -= user_data.ofs[channel] / 1000.0;
   /* stip off unsignificant digits */
   c = ((int) (c * 1000 + 0.5)) / 1000.0;
 overflow:
   DISABLE_INTERRUPTS;
   user_data.cap[channel] = c;
   ENABLE_INTERRUPTS;
   channel = (channel + 1) % 8;
}
void set_range ()
Definition at line 148 of file scs_800.c.
References SR_CLOCK, SR_DATAO, and SR_STROBE.
{
   unsigned char i;
   SR_STROBE = 0;
   SR_CLOCK = 0;
   /* first shift register (chn 0-3) */
   for (i = 0; i < 4; i++) {
      /* first bit (5M1 Ohm) */
      SR_DATAO = 1;
      SR_CLOCK = 1;
      SR_CLOCK = 0;
      /* second bit (5k6 Ohm) */
      SR_DATAO = 1;
      SR_CLOCK = 1;
      SR_CLOCK = 0;
   }
   /* second shift register (chn 0-3) */
   for (i = 0; i < 4; i++) {
      /* first bit (5M1 Ohm) */
      SR_DATAO = 1;
      SR_CLOCK = 1;
      SR_CLOCK = 0;
      /* second bit (5k6 Ohm) */
      SR_DATAO = 1;
      SR_CLOCK = 1;
      SR_CLOCK = 0;
   }
   /* strobe output */
   SR_DATAO = 0;
   SR_STROBE = 1;
   SR_STROBE = 0;
}
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 138 of file scs_800.c.
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void user_loop (void)
Definition at line 266 of file scs_800.c.
References cap_read(), and time.
{
   static long t = 0;
   if (time() - t > 10) {
      cap_read();
      t = time();
   }
}
unsigned char user_read (unsigned char index)
Definition at line 129 of file scs_800.c.
{
   if (index);
   return 0;
}
void user_write (unsigned char index)
Definition at line 122 of file scs_800.c.
References index.
{
   if (index);
}
Variable Documentation
unsigned char idata _n_sub_addr = 1
Definition at line 40 of file scs_800.c.
float cap[8]
Definition at line 54 of file scs_800.c.
bit DEBUG_MODE
Definition at line 247 of file mscbmain.c.
bit FREEZE_MODE
Definition at line 249 of file mscbmain.c.
float gain
Definition at line 56 of file scs_800.c.
sbit NE555_RESET = P0 ^ 7
Definition at line 46 of file scs_800.c.
sbit NE555_TRIGGER = P0 ^ 6
Definition at line 47 of file scs_800.c.
Referenced by cap_read().
char code node_name[] = "SCS-800"
Definition at line 37 of file scs_800.c.
signed short ofs[8]
Definition at line 55 of file scs_800.c.
unsigned char range[8]
Definition at line 59 of file scs_800.c.
sbit SR_CLOCK = P0 ^ 4
Definition at line 42 of file scs_800.c.
sbit SR_DATAO = P0 ^ 2
Definition at line 44 of file scs_800.c.
sbit SR_STROBE = P0 ^ 5
Definition at line 43 of file scs_800.c.
struct { ... } user_data
MSCB_INFO_VAR code variables[]
Initial value:
 {
   4, UNIT_FARAD, PRFX_NANO, 0, MSCBF_FLOAT, "Cap0", &user_data.cap[0],
   4, UNIT_FARAD, PRFX_NANO, 0, MSCBF_FLOAT, "Cap1", &user_data.cap[1],
   4, UNIT_FARAD, PRFX_NANO, 0, MSCBF_FLOAT, "Cap2", &user_data.cap[2],
   4, UNIT_FARAD, PRFX_NANO, 0, MSCBF_FLOAT, "Cap3", &user_data.cap[3],
   4, UNIT_FARAD, PRFX_NANO, 0, MSCBF_FLOAT, "Cap4", &user_data.cap[4],
   4, UNIT_FARAD, PRFX_NANO, 0, MSCBF_FLOAT, "Cap5", &user_data.cap[5],
   4, UNIT_FARAD, PRFX_NANO, 0, MSCBF_FLOAT, "Cap6", &user_data.cap[6],
   4, UNIT_FARAD, PRFX_NANO, 0, MSCBF_FLOAT, "Cap7", &user_data.cap[7],
   2, UNIT_FARAD, PRFX_PICO, 0, MSCBF_SIGNED, "Ofs0", &user_data.ofs[0],
   2, UNIT_FARAD, PRFX_PICO, 0, MSCBF_SIGNED, "Ofs1", &user_data.ofs[1],
   2, UNIT_FARAD, PRFX_PICO, 0, MSCBF_SIGNED, "Ofs2", &user_data.ofs[2],
   2, UNIT_FARAD, PRFX_PICO, 0, MSCBF_SIGNED, "Ofs3", &user_data.ofs[3],
   2, UNIT_FARAD, PRFX_PICO, 0, MSCBF_SIGNED, "Ofs4", &user_data.ofs[4],
   2, UNIT_FARAD, PRFX_PICO, 0, MSCBF_SIGNED, "Ofs5", &user_data.ofs[5],
   2, UNIT_FARAD, PRFX_PICO, 0, MSCBF_SIGNED, "Ofs6", &user_data.ofs[6],
   2, UNIT_FARAD, PRFX_PICO, 0, MSCBF_SIGNED, "Ofs7", &user_data.ofs[7],
   4, UNIT_FACTOR, 0, 0, MSCBF_FLOAT, "Gain", &user_data.gain,
   0
}
Definition at line 61 of file scs_800.c.