AlcapDAQ:Rootana: midas/mscb/embedded/scs_demo.c File Reference
midas/mscb/embedded/scs_demo.c File Reference
#include <stdio.h>
#include "mscb.h"
Defines
#define GAIN 0
Functions
void user_write (unsigned char index) reentrant
void user_init (unsigned char init)
unsigned char user_read (unsigned char index)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
void adc_read ()
void user_loop (void)
Variables
bit FREEZE_MODE
bit DEBUG_MODE
char code node_name [] = "SCS-DEMO"
sbit VALVE = P0 ^ 7
struct {
float temp [2]
unsigned char sw
} user_data
MSCB_INFO_VAR code variables []
Define Documentation
#define GAIN 0
Definition at line 32 of file scs_demo.c.
Function Documentation
void adc_read ()
Definition at line 112 of file scs_demo.c.
References ADBUSY, ADC0CF, ADC0H, ADC0L, ADCINT, AMX0SL, channel, DISABLE_INTERRUPTS, ENABLE_INTERRUPTS, GAIN, i, user_data, value, and yield().
{
   static unsigned char channel = 0;
   static unsigned long value;
   static unsigned char cnt = 0;
   unsigned char i;
   float t;
   if (cnt == 0) {
      /* switch between channels 0 and 4 */
      channel = channel == 0 ? 5 : 0;
      AMX0SL = channel & 0x0F;
      ADC0CF = 0xE0 | (GAIN & 0x07);    // 16 system clocks and gain
      value = 0;
   }
   /* integrate 16 times */
   for (i = 0; i < 16; i++) {
      DISABLE_INTERRUPTS;
      ADCINT = 0;
      ADBUSY = 1;
      while (!ADCINT);          // wait until conversion ready, does NOT work with ADBUSY!
      ENABLE_INTERRUPTS;
      value += (ADC0L | (ADC0H << 8));
      yield();
   }
   cnt++;
   if (cnt == 0) {              /* average 16*256 = 4096 times */
      value /= 256;
      /* convert to volts, times 100deg/Volt */
      t = value / 65536.0 * 2.5 * 100;
      DISABLE_INTERRUPTS;
      if (channel == 0)
         user_data.temp[0] = t;
      else
         user_data.temp[1] = t;
      ENABLE_INTERRUPTS;
   }
}
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 103 of file scs_demo.c.
{
   if (data_in);
   if (data_out);
   return 0;
}
void user_init (unsigned char init)
Definition at line 62 of file scs_demo.c.
References ADC0CF, ADC0CN, ADC_DIN, ADC_NRDY, ADC_NRES, ADC_SF_VALUE, AMX0CF, chn_bits, CONTROL_REGULATION, CUR_LIMIT_CHANGED, DAC0CN, DAC1CN, DAC_CLR, DEMAND_CHANGED, i, JU1, JU2, led_mode(), N_HV_CHN, P2MDOUT, PRT0CF, REF0CN, REG_FILTER, SET_ADDR, user_data, VALVE, and write_adc().
{
   AMX0CF = 0x00;               // select single ended analog inputs
   ADC0CF = 0xE0;               // 16 system clocks, gain 1
   ADC0CN = 0x80;               // enable ADC
   REF0CN = 0x03;               // enable internal reference
   DAC0CN = 0x80;               // enable DAC0
   DAC1CN = 0x80;               // enable DAC1
   PRT0CF = 0xFF;               // P0 on push-pull
   if (init) {
      user_data.temp[0] = 0;
      user_data.temp[1] = 0;
      user_data.sw = 0;
   }
   VALVE = user_data.sw;
}
void user_loop (void)
Definition at line 165 of file scs_demo.c.
References adc_read(), channel, check_current(), control, CONTROL_IDLE, ramp_hv(), read_current(), read_hv(), regulation(), and user_data.
{
   /* read temperature */
   adc_read();
}
unsigned char user_read (unsigned char index)
Definition at line 95 of file scs_demo.c.
{
   if (index);
   return 0;
}
void user_write (unsigned char index)
Definition at line 87 of file scs_demo.c.
References chn_bits, cur_sub_addr(), DEMAND_CHANGED, index, STATUS_ILIMIT, user_data, and VALVE.
{
   if (index == 2)
      VALVE = user_data.sw;
}
Variable Documentation
bit DEBUG_MODE
Definition at line 247 of file mscbmain.c.
bit FREEZE_MODE
Definition at line 249 of file mscbmain.c.
char code node_name[] = "SCS-DEMO"
Definition at line 30 of file scs_demo.c.
unsigned char sw
Definition at line 42 of file scs_demo.c.
float temp[2]
Definition at line 41 of file scs_demo.c.
struct { ... } user_data
sbit VALVE = P0 ^ 7
Definition at line 34 of file scs_demo.c.
Referenced by user_init(), and user_write().
MSCB_INFO_VAR code variables[]
Initial value:
 {
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp0", &user_data.temp[0],
   4, UNIT_CELSIUS, 0, 0, MSCBF_FLOAT, "Temp1", &user_data.temp[1],
   1, UNIT_BOOLEAN, 0, 0, 0, "Switch", &user_data.sw,
   0
}
Definition at line 45 of file scs_demo.c.