AlcapDAQ:Rootana: midas/mscb/embedded/scs_1000_scanner.c File Reference
midas/mscb/embedded/scs_1000_scanner.c File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "mscb.h"
Defines
#define SHIFT SRCLK = 1; delay_us(1); SRCLK = 0; delay_us(1)
Functions
lcd_menu (void)
void user_write (unsigned char index) reentrant
void user_init (unsigned char init)
unsigned char user_read (unsigned char index)
unsigned char user_func (unsigned char *data_in, unsigned char *data_out)
void adc_read (channel, float *d)
void sr_read ()
unsigned char application_display (bit init)
void user_loop (void)
Variables
bit FREEZE_MODE
bit DEBUG_MODE
char code node_name [] = "Scanner"
unsigned char idata _n_sub_addr = 1
sbit RELAIS0 = P3 ^ 0
sbit RELAIS1 = P3 ^ 1
sbit RELAIS2 = P3 ^ 2
sbit RELAIS3 = P3 ^ 3
sbit DOUT0 = P3 ^ 7
sbit DOUT1 = P3 ^ 6
sbit DOUT2 = P3 ^ 5
sbit DOUT3 = P3 ^ 4
sbit SRCLK = P1 ^ 7
sbit SRIN = P1 ^ 6
sbit SRSTROBE = P1 ^ 5
struct {
float posx
float posy
float demandx
float demandy
unsigned char relais [4]
float aofs [2]
float five_v
} user_data
MSCB_INFO_VAR code variables []
bit moving_x = 0
bit moving_y = 0
SYS_INFO sys_info
bit b0
bit b1
bit b2
bit b3
unsigned char din [4]
Define Documentation
#define SHIFT SRCLK = 1; delay_us(1); SRCLK = 0; delay_us(1)
Definition at line 278 of file scs_1000_scanner.c.
Function Documentation
void adc_read (channel , float * d)
Definition at line 231 of file scs_1000_scanner.c.
References AD0BUSY, AD0INT, ADC0_PAGE, ADC0CF, ADC0H, ADC0L, AMX0SL, channel, DISABLE_INTERRUPTS, ENABLE_INTERRUPTS, i, n, SFRPAGE, user_data, value, and yield().
{
   unsigned long value;
   unsigned int i, n;
   float gvalue;
   SFRPAGE = ADC0_PAGE;
   AMX0SL = channel & 0x0F;
   ADC0CF = 0xE0;               // 16 system clocks, gain 1
   n = 1 << 10;                 // average 1024 times
   value = 0;
   for (i = 0; i < n; i++) {
      DISABLE_INTERRUPTS;
      AD0INT = 0;
      AD0BUSY = 1;
      while (!AD0INT);          // wait until conversion ready, does NOT work with ADBUSY!
      ENABLE_INTERRUPTS;
      value += (ADC0L | (ADC0H << 8));
      yield();
   }
   value >>= 6;
   if (channel < 2)
      gvalue = value / 65536.0 * 20 - 10;       // +- 10V range
   else
      gvalue = value / 65536.0 * 10;    // 0...10V range
   if (channel == 2 || channel == 3) {
      gvalue *= 100;            // 0..5V -> 0..500 mm range
      gvalue += user_data.aofs[channel - 2];
   }
   DISABLE_INTERRUPTS;
   *d = gvalue;
   ENABLE_INTERRUPTS;
}
unsigned char application_display (bit init)
Definition at line 310 of file scs_1000_scanner.c.
References b0, b1, b2, b3, lcd_clear(), lcd_goto(), moving_x, moving_y, RELAIS0, RELAIS1, RELAIS2, RELAIS3, user_data, and user_write().
Referenced by lcd_menu().
{
   static bit b0_old = 0, b1_old = 0, b2_old = 0, b3_old = 0;
   if (init)
      lcd_clear();
   /* display first two ADCs */
   lcd_goto(0, 0);
   printf("X:%5.1fmm", user_data.posx);
   lcd_goto(10, 0);
   printf("Y:%5.1fmm", user_data.posy);
   /* show state of relais 0&1 */
   if (moving_x || moving_y) {
      lcd_goto(0, 1);
      printf("       abort        ");
      if ((!b0_old && b0) || (!b1_old && b1) || (!b2_old && b2) || (!b3_old && b3)) {
         RELAIS0 = 0;
         RELAIS1 = 0;
         RELAIS2 = 0;
         RELAIS3 = 0;
         moving_x = moving_y = 0;
      }
      if (user_data.demandx >= user_data.posx && RELAIS0 == 1) {
         RELAIS0 = 0;
         moving_x = 0;
      }
      if (user_data.demandx <= user_data.posx && RELAIS1 == 1) {
         RELAIS1 = 0;
         moving_x = 0;
      }
      if (user_data.demandy >= user_data.posy && RELAIS2 == 1) {
         RELAIS2 = 0;
         moving_y = 0;
      }
      if (user_data.demandy <= user_data.posy && RELAIS3 == 1) {
         RELAIS3 = 0;
         moving_y = 0;
      }
   } else {
      lcd_goto(0, 1);
      printf("  -   +   ");
      lcd_goto(10, 1);
      printf("  -   +   ");
      /* switch relais 0 with button 0 */
      user_data.relais[0] = b0;
      user_write(4);
      /* switch relais 1 with button 1 */
      user_data.relais[1] = b1;
      user_write(5);
      /* switch relais 2 with button 2 */
      user_data.relais[2] = b2;
      user_write(6);
      /* switch relais 3 with button 3 */
      user_data.relais[3] = b3;
      user_write(7);
   }
   /* enter menu on button 0 and 1 */
   if (!init)
      if (b0 && b1) {
         RELAIS0 = 0;
         RELAIS1 = 0;
         RELAIS2 = 0;
         RELAIS3 = 0;
         moving_x = moving_y = 0;
         return 1;
      }
   b0_old = b0;
   b1_old = b1;
   b2_old = b2;
   b3_old = b3;
   return 0;
}
lcd_menu (void)
Definition at line 276 of file lcd_menu.c.
References application_display(), b0, b1, b2, b3, delay_ms(), display_name(), display_value(), enter_mode, f_var, MSCB_INFO_VAR::flags, flash_param, i, in_menu, lcd_clear(), lcd_goto(), MSCBF_DATALESS, MSCBF_REMOUT, n_sysvar, n_variables, reboot, send_remote_var(), startup, system_menu, sysvar, time, MSCB_INFO_VAR::ud, user_write(), var_inc(), var_index, variables, and MSCB_INFO_VAR::width.
Referenced by user_loop().
{
   static idata unsigned long last_disp = 0, last_b2 = 0, last_b3 = 0;
   static bit b0_old = 0, b1_old = 0, b2_old = 0, b3_old = 0;
   MSCB_INFO_VAR *pvar;
   unsigned char i;
   /* clear startup screen after 3 sec. */
   if (startup) {
      if(time() > 300) {
         startup = 0;
         lcd_clear();
      } else
        return;
   }
   /* do menu business only every 100ms */
   if (time() > last_disp+10) {
      last_disp = time();
      if (system_menu)
         pvar = &sysvar[var_index];
      else
         pvar = &variables[var_index];
      if (!in_menu) {
         /* if not in menu, call application display */
         if (application_display(0))
            in_menu = 1;
      } else {
         if (enter_mode) {
            /* display variables */
            display_value(pvar, &f_var);
            lcd_goto(0, 1);
            puts("ESC ENTER   -    + ");
            /* evaluate ESC button */
            if (b0 && !b0_old)
               enter_mode = 0;
            /* evaluate ENTER button */
            if (b1 && !b1_old) {
               enter_mode = 0;
               memcpy(pvar->ud, &f_var, pvar->width);
               if (system_menu) {
                  /* flash new address */
                  if (var_index == 0 || var_index == 1)
                     flash_param = 1;
               } else {
                  user_write(var_index);
#ifdef SCS_1000
                  if (variables[var_index].flags & MSCBF_REMOUT)
                     send_remote_var(var_index);
#endif
               }
            }
            /* evaluate "-" button */
            if (b2 && !b2_old) {
               var_inc(pvar, -1);
               last_b2 = time();
            }
            if (b2 && time() > last_b2 + 70)
               var_inc(pvar, -1);
            if (!b2)
               last_b2 = 0;
            /* evaluate "+" button */
            if (b3 && !b3_old) {
               var_inc(pvar, 1);
               last_b3 = time();
            }
            if (b3 && time() > last_b3 + 70)
               var_inc(pvar, 1);
            if (!b3)
               last_b3 = 0;
         } else {
            /* display variables */
            display_name(var_index, pvar);
            display_value(pvar, pvar->ud);
            lcd_goto(0, 1);
            if (pvar->delta > 0 || (pvar->flags & MSCBF_DATALESS))
               puts("ESC ENTER  PREV NEXT");
            else
               puts("ESC        PREV NEXT");
            /* evaluate ESC button */
            if (b0 && !b0_old) {
               if (system_menu) {
                  system_menu = 0;
                  var_index = 0;
               } else {
                  in_menu = 0;
                  application_display(1);
               }
            }
            /* evaluate ENTER button */
            if (b1 && !b1_old) {
               if (pvar->width <= 4 && pvar->width > 0) {
                  enter_mode = 1;
                  memcpy(&f_var, pvar->ud, pvar->width);
               }
               /* check for flash command */
               if (system_menu && var_index == 2) {
                  flash_param = 1;
                  lcd_clear();
                  lcd_goto(0, 0);
                  puts("Parameters written");
                  lcd_goto(0, 1);
                  puts("to flash memory.");
                  delay_ms(3000);
               }
               /* check for reboot command */
               if (system_menu && var_index == 3)
                  reboot = 1;
            }
            /* evaluate prev button */
            if (b2 && !b2_old) {
               if (var_index == 0)
                 var_index = n_variables-1;
               else
                 var_index--;
               last_b2 = time();
            }
            if (b2 && time() > last_b2 + 70) {
               if (var_index == 0)
                 var_index = n_variables-1;
               else
                 var_index--;
            }
            if (!b2)
               last_b2 = 0;
            if (system_menu)
               i = n_sysvar;
            else
               i = n_variables;
            /* evaluate next button */
            if (b3 && !b3_old) {
               var_index = (var_index + 1) % i;
               last_b3 = time();
            }
            if (b3 && time() > last_b3 + 70)
               var_index = (var_index + 1) % i;
            if (!b3)
               last_b3 = 0;
            /* check for system menu */
            if (b2 && b3 && !system_menu) {
               var_index = 0;
               system_menu = 1;
            }
         }
      }
      b0_old = b0;
      b1_old = b1;
      b2_old = b2;
      b3_old = b3;
   }
}
void sr_read ()
Definition at line 282 of file scs_1000_scanner.c.
References b0, b1, b2, b3, delay_us(), din, SHIFT, SRCLK, SRIN, and SRSTROBE.
{
   SRCLK = 0;
   SRIN = 1;
   SRSTROBE = 1;
   delay_us(1);
   SRSTROBE = 0;
   din[2] = SRIN;
   SHIFT;
   din[3] = SRIN;
   SHIFT;
   din[0] = SRIN;
   SHIFT;
   din[1] = SRIN;
   SHIFT;
   b3 = SRIN;
   SHIFT;
   b2 = SRIN;
   SHIFT;
   b1 = SRIN;
   SHIFT;
   b0 = SRIN;
}
unsigned char user_func (unsigned char * data_in, unsigned char * data_out)
Definition at line 221 of file scs_1000_scanner.c.
{
   /* echo input data */
   data_out[0] = data_in[0];
   data_out[1] = data_in[1];
   return 2;
}
void user_init (unsigned char init)
Definition at line 105 of file scs_1000_scanner.c.
References ADC0_PAGE, ADC0CF, ADC0CN, AMX0CF, CONFIG_PAGE, DAC0_PAGE, DAC0CN, DAC1_PAGE, DAC1CN, i, lcd_goto(), led_mode(), LEGACY_PAGE, SYS_INFO::node_addr, SYS_INFO::node_name, P0MDOUT, P1MDOUT, P2MDOUT, P3MDOUT, REF0CN, SFRPAGE, user_data, and user_write().
{
   unsigned char i;
   led_mode(2, 0);              // buzzer off by default
   SFRPAGE = ADC0_PAGE;
   AMX0CF = 0x00;               // select single ended analog inputs
   ADC0CF = 0xE0;               // 16 system clocks, gain 1
   ADC0CN = 0x80;               // enable ADC
   REF0CN = 0x00;               // use external voltage reference
   SFRPAGE = LEGACY_PAGE;
   REF0CN = 0x02;               // select external voltage reference
   SFRPAGE = DAC0_PAGE;
   DAC0CN = 0x80;               // enable DAC0
   SFRPAGE = DAC1_PAGE;
   DAC1CN = 0x80;               // enable DAC1
   /* open drain(*) /push-pull:
      P0.0 TX1      P1.0 TP6          P2.0 LED1         P3.0 RELAIS0
      P0.1*RX1      P1.1 BACKLIGHT    P2.1 LCD_E        P3.1 RELAIS1
      P0.2 TX2      P1.2 TP5          P2.2 LCD_RW       P3.2 RELAIS2
      P0.3*RX2      P1.3 TP7          P2.3 LCD_RS       P3.3 RELAIS3
      P0.4 EN1      P1.4 WATCHDOG     P2.4 LCD_DB4      P3.4 DOUT0
      P0.5 EN2      P1.5 SRSTROBE     P2.5 LCD_DB5      P3.5 DOUT1
      P0.6 LED2     P1.6*SRIN         P2.6 LCD_DB6      P3.6 DOUT2
      P0.7 BUZZER   P1.7 SRCLK        P2.7 LCD_DB7      P3.7 DOUT3
    */
   SFRPAGE = CONFIG_PAGE;
   P0MDOUT = 0xF5;
   P1MDOUT = 0xBF;
   P2MDOUT = 0xFF;
   P3MDOUT = 0xFF;
   /* initial EEPROM value */
   if (init) {
      for (i = 0; i < 4; i++)
         user_data.relais[i] = 0;
      user_data.demandx = 0;
      user_data.demandy = 0;
      user_data.aofs[0] = 0;
      user_data.aofs[1] = 0;
   }
   /* write relais */
   for (i = 4; i < 8; i++)
      user_write(i);
   /* display startup screen */
   lcd_goto(0, 0);
   for (i = 0; i < 7 - strlen(sys_info.node_name) / 2; i++)
      puts(" ");
   puts("** ");
   puts(sys_info.node_name);
   puts(" **");
   lcd_goto(0, 1);
   printf("   Address:  %04X ", sys_info.node_addr);
}
void user_loop (void)
Definition at line 401 of file scs_1000_scanner.c.
References adc_read(), lcd_menu(), sr_read(), and user_data.
{
   /* read scanne position */
   adc_read(2, &user_data.posx);
   adc_read(3, &user_data.posy);
   adc_read(4, &user_data.five_v);
   /* read buttons and digital input */
   sr_read();
   /* mangae menu on LCD display */
   lcd_menu();
}
unsigned char user_read (unsigned char index)
Definition at line 213 of file scs_1000_scanner.c.
{
   if (index);
   return 0;
}
void user_write (unsigned char index)
Definition at line 173 of file scs_1000_scanner.c.
References index, moving_x, moving_y, RELAIS0, RELAIS1, RELAIS2, RELAIS3, and user_data.
{
   switch (index) {
   case 2:
      if (user_data.demandx < user_data.posx)
         RELAIS0 = 1;
      else if (user_data.demandx > user_data.posx)
         RELAIS1 = 1;
      moving_x = 1;
      break;
   case 3:
      if (user_data.demandy < user_data.posy)
         RELAIS2 = 1;
      else if (user_data.demandy > user_data.posy)
         RELAIS3 = 1;
      moving_y = 1;
      break;
   case 4:
      RELAIS0 = user_data.relais[0];
      break;
   case 5:
      RELAIS1 = user_data.relais[1];
      break;
   case 6:
      RELAIS2 = user_data.relais[2];
      break;
   case 7:
      RELAIS3 = user_data.relais[3];
      break;
   case 10:
      RELAIS0 = RELAIS1 = RELAIS2 = RELAIS3 = 0;
      moving_x = moving_y = 0;
      break;
   }
}
Variable Documentation
unsigned char idata _n_sub_addr = 1
Definition at line 35 of file scs_1000_scanner.c.
float aofs[2]
Definition at line 63 of file scs_1000_scanner.c.
bit b0
Definition at line 276 of file scs_1000_scanner.c.
Referenced by application_display(), lcd_menu(), and sr_read().
bit b1
Definition at line 276 of file scs_1000_scanner.c.
Referenced by application_display(), decode_bits(), lcd_menu(), SimpleHistograms::ProcessEntry(), MyModule::ProcessEntry(), and sr_read().
bit b2
Definition at line 276 of file scs_1000_scanner.c.
Referenced by application_display(), decode_bits(), lcd_menu(), SimpleHistograms::ProcessEntry(), and sr_read().
bit b3
Definition at line 276 of file scs_1000_scanner.c.
Referenced by application_display(), lcd_menu(), and sr_read().
bit DEBUG_MODE
Definition at line 247 of file mscbmain.c.
float demandx
Definition at line 61 of file scs_1000_scanner.c.
float demandy
Definition at line 61 of file scs_1000_scanner.c.
unsigned char din[4]
Definition at line 280 of file scs_1000_scanner.c.
sbit DOUT0 = P3 ^ 7
Definition at line 46 of file scs_1000_scanner.c.
sbit DOUT1 = P3 ^ 6
Definition at line 47 of file scs_1000_scanner.c.
sbit DOUT2 = P3 ^ 5
Definition at line 48 of file scs_1000_scanner.c.
sbit DOUT3 = P3 ^ 4
Definition at line 49 of file scs_1000_scanner.c.
float five_v
Definition at line 64 of file scs_1000_scanner.c.
bit FREEZE_MODE
Definition at line 249 of file mscbmain.c.
bit moving_x = 0
Definition at line 90 of file scs_1000_scanner.c.
Referenced by application_display(), and user_write().
bit moving_y = 0
Definition at line 91 of file scs_1000_scanner.c.
Referenced by application_display(), and user_write().
char code node_name[] = "Scanner"
Definition at line 32 of file scs_1000_scanner.c.
float posx
Definition at line 60 of file scs_1000_scanner.c.
float posy
Definition at line 60 of file scs_1000_scanner.c.
unsigned char relais[4]
Definition at line 62 of file scs_1000_scanner.c.
sbit RELAIS0 = P3 ^ 0
Definition at line 41 of file scs_1000_scanner.c.
sbit RELAIS1 = P3 ^ 1
Definition at line 42 of file scs_1000_scanner.c.
sbit RELAIS2 = P3 ^ 2
Definition at line 43 of file scs_1000_scanner.c.
sbit RELAIS3 = P3 ^ 3
Definition at line 44 of file scs_1000_scanner.c.
sbit SRCLK = P1 ^ 7
Definition at line 51 of file scs_1000_scanner.c.
sbit SRIN = P1 ^ 6
Definition at line 52 of file scs_1000_scanner.c.
sbit SRSTROBE = P1 ^ 5
Definition at line 53 of file scs_1000_scanner.c.
SYS_INFO sys_info
Definition at line 239 of file mscbmain.c.
struct { ... } user_data
MSCB_INFO_VAR code variables[]
Initial value:
 {
   {4, UNIT_METER, PRFX_MILLI, 0, MSCBF_FLOAT, "PosX", &user_data.posx},
   {4, UNIT_METER, PRFX_MILLI, 0, MSCBF_FLOAT, "PosY", &user_data.posy},
   {4, UNIT_METER, PRFX_MILLI, 0, MSCBF_FLOAT, "DemandX", &user_data.demandx, -1000, 1000,
    1},
   {4, UNIT_METER, PRFX_MILLI, 0, MSCBF_FLOAT, "DemandY", &user_data.demandy, -1000, 1000,
    1},
   {1, UNIT_BOOLEAN, 0, 0, 0, "Relais0", &user_data.relais[0], 0, 1, 1},
   {1, UNIT_BOOLEAN, 0, 0, 0, "Relais1", &user_data.relais[1], 0, 1, 1},
   {1, UNIT_BOOLEAN, 0, 0, 0, "Relais2", &user_data.relais[2], 0, 1, 1},
   {1, UNIT_BOOLEAN, 0, 0, 0, "Relais3", &user_data.relais[3], 0, 1, 1},
   {4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "AOFS0", &user_data.aofs[0], -10, 10, 0.1},
   {4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "AOFS1", &user_data.aofs[1], -10, 10, 0.1},
   {4, UNIT_VOLT, 0, 0, MSCBF_FLOAT, "5V", &user_data.five_v},
   {0}
}
Definition at line 67 of file scs_1000_scanner.c.