AlcapDAQ:Rootana: midas/drivers/bus/sis3100/sis3100.c File Reference
midas/drivers/bus/sis3100/sis3100.c File Reference
#include <stdio.h>
#include <string.h>
#include "mvmestd.h"
#include "PlxApi.h"
#include "sis1100w.h"
Data Structures
struct SIS3100_DEVICE
Defines
#define MAX_SIS3100_DEVICES 4
Functions
int mvme_init ()
int mvme_exit ()
int mvme_write (mvme_addr_t vme_addr, void *src, mvme_size_t n_bytes)
int mvme_read (void *dst, mvme_addr_t vme_addr, mvme_size_t n_bytes)
int mvme_ioctl (int req, int *param)
Variables
int n_sis3100
int i_sis3100
SIS3100_DEVICE sis3100_device [MAX_SIS3100_DEVICES]
Define Documentation
#define MAX_SIS3100_DEVICES 4
Definition at line 30 of file sis3100.c.
Function Documentation
int mvme_exit ()
Definition at line 77 of file sis3100.c.
References i, MVME_SUCCESS, n_sis3100, and sis1100w_Close().
{
   int i;
   for (i=0 ; i<n_sis3100 ; i++)
      sis1100w_Close(&sis3100_device[i].sis1100_dev);
   return MVME_SUCCESS;
}
int mvme_init ()
Definition at line 45 of file sis3100.c.
References SIS3100_DEVICE::amod, SIS3100_DEVICE::dma, SIS3100_DEVICE::fifo_mode, i, i_sis3100, MVME_AMOD_A32, MVME_NO_CRATE, MVME_NO_INTERFACE, MVME_SUCCESS, n_sis3100, sis1100w_Find_No_Of_sis1100(), sis1100w_Get_Handle_And_Open(), sis1100w_Init(), and sis1100w_Init_sis3100().
{
   int i;
        sis1100w_Find_No_Of_sis1100(&n_sis3100);
   if (n_sis3100 == 0)
      return MVME_NO_INTERFACE;
   for (i=0 ; i < n_sis3100; i++) {
      if (sis1100w_Get_Handle_And_Open(i+1, &sis3100_device[i].sis1100_dev) != 0)
         return MVME_NO_INTERFACE;
      if (sis1100w_Init(&sis3100_device[i].sis1100_dev, 0) != 0)
         return MVME_NO_INTERFACE;
      if (sis1100w_Init_sis3100(&sis3100_device[i].sis1100_dev, 0) != 0)
         return MVME_NO_CRATE;
      /* default values */
      sis3100_device[i].amod      = MVME_AMOD_A32;
      sis3100_device[i].dma       = 0;
      sis3100_device[i].fifo_mode = 0;
        }
   /* use first device by default */
   i_sis3100 = 0;
   return MVME_SUCCESS;
}
int mvme_ioctl (int req, int * param)
Definition at line 144 of file sis3100.c.
References SIS3100_DEVICE::amod, SIS3100_DEVICE::fifo_mode, i_sis3100, MVME_IOCTL_AMOD_GET, MVME_IOCTL_AMOD_SET, MVME_IOCTL_CRATE_GET, MVME_IOCTL_CRATE_SET, MVME_IOCTL_DMA_GET, MVME_IOCTL_DMA_SET, MVME_IOCTL_FIFO_GET, MVME_IOCTL_FIFO_SET, MVME_NO_CRATE, MVME_SUCCESS, MVME_UNSUPPORTED, and n_sis3100.
{
   switch (req) {
      case MVME_IOCTL_CRATE_SET:
         *param = i_sis3100;
         break;
      case MVME_IOCTL_CRATE_GET:
         if (*param < n_sis3100)
            i_sis3100 = *param;
         else
            return MVME_NO_CRATE;
         break;
      case MVME_IOCTL_AMOD_SET:
         sis3100_device[i_sis3100].amod = *param;
         break;
      case MVME_IOCTL_AMOD_GET:
         *param = sis3100_device[i_sis3100].amod;
         break;
      case MVME_IOCTL_FIFO_SET:
         sis3100_device[i_sis3100].fifo_mode = *param;
         break;
      case MVME_IOCTL_FIFO_GET:
         *param = sis3100_device[i_sis3100].fifo_mode;
         break;
      case MVME_IOCTL_DMA_SET:
         return MVME_UNSUPPORTED;
      case MVME_IOCTL_DMA_GET:
         return MVME_UNSUPPORTED;
   }
   return MVME_SUCCESS;
}
int mvme_read (void * dst, mvme_addr_t vme_addr, mvme_size_t n_bytes)
Definition at line 118 of file sis3100.c.
References data, i_sis3100, n, sis1100w_Vme_Dma_Read(), and sis1100w_Vme_Single_Read().
{
   mvme_size_t n;
   DWORD data;
   data = 0;
   if (n_bytes <= 4) {
      data = 0;
      n = sis1100w_Vme_Single_Read(&sis3100_device[i_sis3100].sis1100_dev,
         vme_addr, sis3100_device[i_sis3100].amod, n_bytes, &data);
      memcpy(dst, &data, n_bytes);
   } else {
      sis1100w_Vme_Dma_Read(&sis3100_device[i_sis3100].sis1100_dev,
         (U32) vme_addr,
         (U32) sis3100_device[i_sis3100].amod,
         (U32) n_bytes,
         (U32) sis3100_device[i_sis3100].fifo_mode,
                        (U32*) dst, (U32) n_bytes/4, (U32*) &n);
   }
   return n;
}
int mvme_write (mvme_addr_t vme_addr, void * src, mvme_size_t n_bytes)
Definition at line 89 of file sis3100.c.
References data, i_sis3100, n, sis1100w_Vme_Dma_Write(), sis1100w_Vme_Single_Write(), and status.
{
   mvme_size_t n;
   DWORD status, data;
   if (n_bytes <= 4) {
      data = 0;
      memcpy(&data, src, n_bytes);
      status = sis1100w_Vme_Single_Write(&sis3100_device[i_sis3100].sis1100_dev,
         vme_addr, sis3100_device[i_sis3100].amod, n_bytes, data);
      if (status == 0)
         n = n_bytes;
      else
         n = 0;
   } else {
      status = sis1100w_Vme_Dma_Write(&sis3100_device[i_sis3100].sis1100_dev,
         (U32) vme_addr,
         (U32) sis3100_device[i_sis3100].amod,
         (U32) 4,
         (U32) sis3100_device[i_sis3100].fifo_mode,
                        (U32*) src, (U32) n_bytes/4, (U32*) &n);
   }
   return n;
}
Variable Documentation
int i_sis3100
Definition at line 32 of file sis3100.c.
Referenced by mvme_init(), mvme_ioctl(), mvme_read(), and mvme_write().
int n_sis3100
Definition at line 32 of file sis3100.c.
Referenced by mvme_exit(), mvme_init(), and mvme_ioctl().
SIS3100_DEVICE sis3100_device[MAX_SIS3100_DEVICES]
Definition at line 41 of file sis3100.c.