AlcapDAQ:Rootana: slowcontrol/separator/frontend.c File Reference
slowcontrol/separator/frontend.c File Reference
#include <stdio.h>
#include "midas.h"
Data Structures
struct SEPARATOR_DATA_Struct
Typedefs
typedef struct
SEPARATOR_DATA_Struct SEPARATOR_DATA
Functions
INT read_separator_event (char *pevent, INT off)
INT pre_begin_of_run ()
INT frontend_early_init ()
INT poll_event (INT source[], INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source[], PTYPE adr)
INT frontend_init ()
INT frontend_exit ()
INT frontend_loop ()
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
Variables
INT crate_number = 0
HNDLE hDB
HNDLE hKey
int size
int sepDemand
char Alarm [128] = "/Equipment/SeparatorMonitor/Variables/Alarm_Triggered"
char * frontend_name = "SeparatorMonitor"
char * frontend_file_name = __FILE__
BOOL frontend_call_loop = TRUE
INT display_period = 1000
INT max_event_size = 10000
INT max_event_size_frag = 5 * 1024 * 1024
INT event_buffer_size = 10 * 10000
BANK_LIST separator_bank_list []
EQUIPMENT equipment []
Typedef Documentation
typedef struct SEPARATOR_DATA_Struct SEPARATOR_DATA
Function Documentation
INT begin_of_run (INT run_number, char * error)
Definition at line 198 of file frontend.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
INT end_of_run (INT run_number, char * error)
Definition at line 205 of file frontend.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
INT frontend_early_init (void)
Definition at line 147 of file frontend.c.
References CM_SUCCESS.
{
  return CM_SUCCESS;
}
INT frontend_exit (void)
Definition at line 183 of file frontend.c.
References CM_SUCCESS.
{
  return CM_SUCCESS;
}
INT frontend_init (void)
Definition at line 168 of file frontend.c.
References Alarm, cm_get_experiment_database(), CM_SUCCESS, db_create_key(), db_find_key(), hDB, hKey, SUCCESS, and TID_INT.
{
  // get the LabView filename
  cm_get_experiment_database(&hDB, NULL);
  if(db_find_key(hDB, 0, Alarm, &hKey) != SUCCESS){
    db_create_key(hDB,0,Alarm,TID_INT);
  }
  return CM_SUCCESS;
}
INT frontend_loop (void)
Definition at line 190 of file frontend.c.
References CM_SUCCESS, and ss_sleep().
{
   ss_sleep(100);
   return CM_SUCCESS;
}
INT interrupt_configure (INT cmd, INT source[], PTYPE adr)
Definition at line 161 of file frontend.c.
{
   return 1;
};
INT pause_run (INT run_number, char * error)
Definition at line 212 of file frontend.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
INT poll_event (INT source[], INT count, BOOL test)
Definition at line 157 of file frontend.c.
{
   return 1;
};
INT pre_begin_of_run ()
Definition at line 152 of file frontend.c.
References CM_SUCCESS.
{
  return CM_SUCCESS;
}
INT read_separator_event (char * pevent, INT off)
Definition at line 226 of file frontend.c.
References Alarm, bk_close(), bk_create(), bk_init(), bk_size(), cm_msg, SEPARATOR_DATA_Struct::current, db_get_value(), db_set_value(), frontend_name, hDB, SEPARATOR_DATA_Struct::hv, i, MERROR, SEPARATOR_DATA_Struct::sep_stat, sepDemand, size, TID_FLOAT, TID_INT, and SEPARATOR_DATA_Struct::vac.
{
  static SEPARATOR_DATA separator_data;
  static char oldtimestamp[80];
  char timestamp[80];
  char timestring[80];
  FILE *infile=NULL;
  float *pdata;
  static float lastHVs[4] = {-1., -1., -1., -1.};
  static int initDone = 0;
  int i;
  size = sizeof(sepDemand);
  db_get_value(hDB,0, "/Experiment/Edit on start/Separator HV",
               &sepDemand, &size, TID_INT, 1);
  timestamp[0]='\0';
  infile=fopen("/tmp/separator.txt","r");
  if (infile==NULL){
    cm_msg(MERROR,frontend_name,
           "Could not open tempfile. separator_daemon.pl not running?");
    separator_data.hv =-1;
    separator_data.vac =-1;
    separator_data.sep_stat =-1;
  }
  else{
    fscanf(infile,"%s\n%f\n%f\n%f\n%f",timestamp,&separator_data.hv,
           &separator_data.current,&separator_data.vac,
           &separator_data.sep_stat);
    fclose(infile);
    if(!strcmp(oldtimestamp, timestamp)){
      separator_data.hv=-1;
      separator_data.vac=-1;
      separator_data.sep_stat=-1;
    }
  }
  if(initDone == 0){
    for(i=0; i<4; i++) lastHVs[i] = separator_data.hv;
    initDone = 1;
  }
  else{
    for(i=0; i<3; i++) lastHVs[i] = lastHVs[i+1];
    lastHVs[3] = separator_data.hv;
  }
  //for(i=0; i<4; i++) printf("HV[%d]=%d\n",i,(int)lastHVs[i]);
  //printf("Demand = %d\n", sepDemand);
  //Send to midas:
  bk_init(pevent);
  bk_create(pevent,"SEPA",TID_FLOAT,&pdata);
  pdata[0] = separator_data.hv;
  pdata[1] = separator_data.current;
  pdata[2] = separator_data.vac;
  pdata[3] = separator_data.sep_stat;
  bk_close(pevent,pdata+4);
  int sepError = 1;
  for(i=0; i<4; i++){
    if((int)lastHVs[i] == sepDemand) sepError = 0;
  }
  if(sepError==1){
    if(strcmp(oldtimestamp, timestamp)){
      cm_msg(MERROR,frontend_name,"Separator high voltage not same as demand!");
      printf("Demand = %d", sepDemand);
    }
    else{
      cm_msg(MERROR,frontend_name,"Old and new timestamps identical."
             " Refresh too high or separator_daemon.pl not running.");
    }
    int on = 1;
    db_set_value(hDB, 0, Alarm, &on, sizeof(on), 1, TID_INT);
  }
  else{
    int off = 0;
    db_set_value(hDB, 0, Alarm, &off, sizeof(off), 1, TID_INT);
  }
  strcpy(oldtimestamp,timestamp);
  return bk_size(pevent);
}
INT resume_run (INT run_number, char * error)
Definition at line 219 of file frontend.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
Variable Documentation
char Alarm[128] = "/Equipment/SeparatorMonitor/Variables/Alarm_Triggered"
Definition at line 74 of file frontend.c.
Referenced by frontend_init(), and read_separator_event().
INT crate_number = 0
Definition at line 68 of file frontend.c.
INT display_period = 1000
Definition at line 91 of file frontend.c.
EQUIPMENT equipment[]
Initial value:
 {
   {"SeparatorMonitor",
     { 22, 0,
       "SYSTEM",
       EQ_PERIODIC,
       0,
       "MIDAS",
       TRUE,
       RO_ALWAYS|RO_ODB,
       50000,
       0,
       0,
       0,
       "", "", "", },
    read_separator_event,
    NULL, NULL,
    separator_bank_list,
   },
   {""}
}
Definition at line 118 of file frontend.c.
INT event_buffer_size = 10 * 10000
Definition at line 100 of file frontend.c.
BOOL frontend_call_loop = TRUE
Definition at line 88 of file frontend.c.
char* frontend_file_name = __FILE__
Definition at line 85 of file frontend.c.
char* frontend_name = "SeparatorMonitor"
Definition at line 83 of file frontend.c.
HNDLE hDB
Definition at line 70 of file frontend.c.
HNDLE hKey
Definition at line 71 of file frontend.c.
INT max_event_size = 10000
Definition at line 94 of file frontend.c.
INT max_event_size_frag = 5 * 1024 * 1024
Definition at line 97 of file frontend.c.
BANK_LIST separator_bank_list[]
Initial value:
 {
  { "SEPA", TID_FLOAT,  4, NULL },
  { "" },
}
Definition at line 104 of file frontend.c.
int sepDemand
Definition at line 73 of file frontend.c.
Referenced by read_separator_event().
int size
Definition at line 72 of file frontend.c.