AlcapDAQ:Rootana: slowcontrol/ge_ln2/frontend.c File Reference
slowcontrol/ge_ln2/frontend.c File Reference
#include <stdio.h>
#include <time.h>
#include "midas.h"
Functions
INT ge_ln2_read (char *pevent, INT off)
INT frontend_early_init ()
INT pre_begin_of_run ()
INT poll_event (INT source[], INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source[], PTYPE adr)
INT frontend_init ()
INT frontend_exit ()
INT frontend_loop ()
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
Variables
INT crate_number = 11
HNDLE hDB
char * frontend_name = "Germanium"
char * frontend_file_name = __FILE__
BOOL frontend_call_loop = TRUE
INT display_period = 1000
INT max_event_size = 10000
INT max_event_size_frag = 5 * 1024 * 1024
INT event_buffer_size = 10 * 10000
static char * sLastFilled = "/Equipment/Germanium/Settings/AlarmCheck/LastFilled"
static char * sJustFilled = "/Equipment/Germanium/Settings/AlarmCheck/JustFilled"
static char * sTimeLimit = "/Equipment/Germanium/Settings/AlarmCheck/TimeLimit"
static char * sAlarmName = "Germanium"
static HNDLE kLastFilled
static HNDLE kJustFilled
static HNDLE kTimeLimit
static HNDLE kAlarm
BANK_LIST ge_ln2_bank_list []
EQUIPMENT equipment []
Function Documentation
INT begin_of_run (INT run_number, char * error)
Definition at line 202 of file frontend.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
INT end_of_run (INT run_number, char * error)
Definition at line 209 of file frontend.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
INT frontend_early_init (void)
Definition at line 88 of file frontend.c.
References CM_SUCCESS.
{
  return CM_SUCCESS;
}
INT frontend_exit (void)
Definition at line 188 of file frontend.c.
References CM_SUCCESS.
{
  return CM_SUCCESS;
}
INT frontend_init (void)
Definition at line 109 of file frontend.c.
References cm_get_experiment_database(), CM_SUCCESS, db_create_key(), db_find_key(), DB_NO_KEY, db_set_value(), DB_SUCCESS, FALSE, FE_ERR_HW, hDB, kJustFilled, kLastFilled, kTimeLimit, sJustFilled, sLastFilled, status, sTimeLimit, TID_BOOL, and TID_DWORD.
                    {
  INT   status;
  BOOL  default_justfilled = FALSE; // Assuming the worst
  DWORD default_lastfilled = 0;     // Assuming the worst
  DWORD default_timelimit  = 28000; // 8 hours between fills
  // Get handles to database keys if they exist,
  // and create otherwise with default worst-case-scenario values
  status = cm_get_experiment_database(&hDB, NULL);
  if (status != CM_SUCCESS) {
    printf("Warning: Could not connect to ODB database!\n");
    return FE_ERR_HW;
  }
  status = db_find_key(hDB, 0, sLastFilled, &kLastFilled);
  if (status == DB_NO_KEY) {
    db_create_key(hDB, 0, sLastFilled, TID_DWORD);
    db_find_key(hDB, 0, sLastFilled, &kLastFilled);
    status = db_set_value(hDB, 0, sLastFilled, &default_lastfilled, sizeof(default_lastfilled), 1, TID_DWORD);
  }
  if (status != DB_SUCCESS) {
    printf("Warning: Could not access key %s!\n", sLastFilled);
    return FE_ERR_HW;
  }
  status = db_find_key(hDB, 0, sJustFilled, &kJustFilled);
  if (status == DB_NO_KEY) {
    db_create_key(hDB, 0, sJustFilled, TID_BOOL);
    db_find_key(hDB, 0, sJustFilled, &kJustFilled);
    status = db_set_value(hDB, 0, sJustFilled, &default_justfilled, sizeof(default_justfilled), 1, TID_BOOL);
  }
  if (status != DB_SUCCESS) {
    printf("Warning: Could not access key %s!\n", sJustFilled);
    return FE_ERR_HW;
  }
  status = db_find_key(hDB, 0, sTimeLimit, &kTimeLimit);
  if (status == DB_NO_KEY) {
    db_create_key(hDB, 0, sTimeLimit, TID_DWORD);
    db_find_key(hDB, 0, sTimeLimit, &kTimeLimit);
    status = db_set_value(hDB, 0, sTimeLimit, &default_timelimit, sizeof(default_timelimit), 1, TID_DWORD);
  }
  if (status != DB_SUCCESS) {
    printf("Warning: Could not access key %s!\n", sTimeLimit);
    return FE_ERR_HW;
  }
  /*
  // Check if alarm exists and, if not,create it
  // Copied from midas.c which should take care of this, but doesn't
  char str[256];
  sprintf(str, "/Alarms/Alarms/%s", sAlarmName);
  db_find_key(hDB, 0, str, &kAlarm);
  if (!kAlarm) {
  ALARM_ODB_STR(alarm_odb_str); // The initial "run number too large" settings for a default alarm
  status = db_create_record(hDB, 0, str, strcomb(alarm_odb_str));
    db_find_key(hDB, 0, str, &kAlarm);
    if (!kAlarm) {
      cm_msg(MERROR, "ge_ln2_init", "Cannot create alarm record");
      return FE_ERR_HW;
    }
    BOOL al_active    = TRUE;                        // Alarm should be on
    INT  al_type      = AT_EVALUATED;                // Alarm type is evaluated; it looks for a certain ODB value to be too large
    char al_cond[256] = "";                          // Not a "conditional" alarm in the MIDAS sense
    char al_class[32] = "Alarm";                     // When triggered, the alarm will have black letters on red background
    char al_msg[80]   = "Germanium must be filled!"; // Message on banner
    db_set_value(hDB, kAlarm, "Active",        &al_active, sizeof(al_active), 1, TID_BOOL);
    db_set_value(hDB, kAlarm, "Type",          &al_type,   sizeof(al_type),   1, TID_INT);
    db_set_value(hDB, kAlarm, "Condition",      al_cond,   sizeof(al_cond),   1, TID_STRING);
    db_set_value(hDB, kAlarm, "Alarm Class",    al_class,  sizeof(al_class),  1, TID_STRING);
    db_set_value(hDB, kAlarm, "Alarm Message",  al_msg,    sizeof(al_msg),    1, TID_STRING);
  }
  */
  return CM_SUCCESS;
}
INT frontend_loop (void)
Definition at line 195 of file frontend.c.
References CM_SUCCESS.
{
  return CM_SUCCESS;
}
INT ge_ln2_read (char * pevent, INT off)
Definition at line 230 of file frontend.c.
References al_reset_alarm(), al_trigger_alarm(), AT_INTERNAL, bk_close(), bk_create(), bk_init(), bk_size(), cm_msg, db_get_value(), db_set_value(), DB_SUCCESS, FALSE, hDB, MERROR, sAlarmName, size, sJustFilled, sLastFilled, status, sTimeLimit, TID_BOOL, TID_DWORD, time, and TRUE.
{
  static INT    status, size;
  static DWORD  lastfilled, now, timelimit;
  static BOOL   justfilled;
  static DWORD  *timesincefill;
  bk_init(pevent);
  timesincefill = NULL;
  // Get recent values
  size = sizeof(lastfilled);
  status = db_get_value(hDB, 0, sLastFilled, &lastfilled, &size, TID_DWORD, FALSE);
  if (status != DB_SUCCESS) {
    cm_msg(MERROR, "ge_ln2_read", "Error getting last filled time");
    return 0;
  }
  size = sizeof(justfilled);
  status = db_get_value(hDB, 0, sJustFilled, &justfilled, &size, TID_BOOL, FALSE);
  if (status != DB_SUCCESS) {
    cm_msg(MERROR, "ge_ln2_read", "Error getting just filled status");
    return 0;
  }
  size = sizeof(timelimit);
  status = db_get_value(hDB, 0, sTimeLimit, &timelimit, &size, TID_DWORD, FALSE);
  if (status != DB_SUCCESS) {
    cm_msg(MERROR, "ge_ln2_read", "Error getting time limit between fills");
    return 0;
  }
  // If just filled, write time to ODB
  if (justfilled == TRUE) {
    lastfilled = (DWORD)time(NULL);
    status = db_set_value(hDB, 0, sLastFilled, &lastfilled, sizeof(lastfilled), 1, TID_DWORD);
    if (status != DB_SUCCESS) {
      cm_msg(MERROR, "gn_ln2_read", "Error setting last filled time");
      return 0;
    }
    justfilled = FALSE;
    status = db_set_value(hDB, 0, sJustFilled, &justfilled, sizeof(justfilled), 1, TID_BOOL);
    if (status != DB_SUCCESS) {
      cm_msg(MERROR, "gn_ln2_read", "Error setting just filled status");
      return 0;
    }
    al_reset_alarm(sAlarmName);
    bk_create(pevent, "LN2F", TID_DWORD, &timesincefill);
    *timesincefill = 0;
    bk_close(pevent, ++timesincefill);
    return bk_size(pevent);
  }
  // Check the status
  bk_create(pevent, "LN2F", TID_DWORD, &timesincefill);
  now = (DWORD) time(NULL);
  *timesincefill = now - lastfilled;
  if (*timesincefill > timelimit) {
    al_trigger_alarm(sAlarmName, "Germanium must be filled!", "Alarm", "", AT_INTERNAL);
    printf("Alarm!\n");
  }
  bk_close(pevent, ++timesincefill);
  return bk_size(pevent);
}
INT interrupt_configure (INT cmd, INT source[], PTYPE adr)
Definition at line 102 of file frontend.c.
{
   return 1;
};
INT pause_run (INT run_number, char * error)
Definition at line 216 of file frontend.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
INT poll_event (INT source[], INT count, BOOL test)
Definition at line 98 of file frontend.c.
{
   return 1;
};
INT pre_begin_of_run ()
Definition at line 93 of file frontend.c.
References CM_SUCCESS.
{
  return CM_SUCCESS;
}
INT resume_run (INT run_number, char * error)
Definition at line 223 of file frontend.c.
References CM_SUCCESS.
{
   return CM_SUCCESS;
}
Variable Documentation
INT crate_number = 11
Definition at line 11 of file frontend.c.
INT display_period = 1000
Definition at line 28 of file frontend.c.
EQUIPMENT equipment[]
Initial value:
 {
   {"Germanium",
     { 24, 0,
       "SYSTEM",
       EQ_PERIODIC,
       0,
       "MIDAS",
       TRUE,
       RO_ALWAYS | RO_ODB,
       1000,
       0,
       0,
       0,
       "", "", "", },
    ge_ln2_read,
    NULL, NULL,
    ge_ln2_bank_list,
   },
   {""}
}
Definition at line 58 of file frontend.c.
INT event_buffer_size = 10 * 10000
Definition at line 37 of file frontend.c.
BOOL frontend_call_loop = TRUE
Definition at line 25 of file frontend.c.
char* frontend_file_name = __FILE__
Definition at line 22 of file frontend.c.
char* frontend_name = "Germanium"
Definition at line 20 of file frontend.c.
BANK_LIST ge_ln2_bank_list[]
Initial value:
 {
  { "LN2F", TID_DWORD, 1, NULL },
  { "" },
}
Definition at line 51 of file frontend.c.
HNDLE hDB
Definition at line 13 of file frontend.c.
HNDLE kAlarm [static]
Definition at line 47 of file frontend.c.
HNDLE kJustFilled [static]
Definition at line 45 of file frontend.c.
Referenced by frontend_init().
HNDLE kLastFilled [static]
Definition at line 44 of file frontend.c.
Referenced by frontend_init().
HNDLE kTimeLimit [static]
Definition at line 46 of file frontend.c.
Referenced by frontend_init().
INT max_event_size = 10000
Definition at line 31 of file frontend.c.
INT max_event_size_frag = 5 * 1024 * 1024
Definition at line 34 of file frontend.c.
char* sAlarmName = "Germanium" [static]
Definition at line 43 of file frontend.c.
Referenced by ge_ln2_read().
char* sJustFilled = "/Equipment/Germanium/Settings/AlarmCheck/JustFilled" [static]
Definition at line 41 of file frontend.c.
Referenced by frontend_init(), and ge_ln2_read().
char* sLastFilled = "/Equipment/Germanium/Settings/AlarmCheck/LastFilled" [static]
Definition at line 40 of file frontend.c.
Referenced by frontend_init(), and ge_ln2_read().
char* sTimeLimit = "/Equipment/Germanium/Settings/AlarmCheck/TimeLimit" [static]
Definition at line 42 of file frontend.c.
Referenced by frontend_init(), and ge_ln2_read().