AlcapDAQ:Rootana: midas/drivers/bus/str340.c File Reference
midas/drivers/bus/str340.c File Reference
#include <stdio.h>
#include "btapi.h"
#include "mfbstd.h"
Defines
#define BT983
#define SFI_OUT(adr, data) {*((DWORD*) (_sfi+(adr))) = (data);}
#define SFI_IN(adr) *((DWORD*) (_sfi+(adr)))
#define SFI_ADDRESS 0xE00000
#define SFI_SIZE 0x1FFFF
#define SFI_READ_INT_FB_AD 0x1000
#define SFI_LAST_PRIMADR_REG 0x1004
#define SFI_WRITE_VME_OUT_SIGNAL_REGISTER 0x1000
#define SFI_CLEAR_BOTH_LCA1_TEST_REGISTER 0x1004
#define SFI_WRITE_INT_FB_AD_REG 0x1010
#define SFI_KEY_AUX_PULS_B40 0x1014
#define SFI_READ_VME_TEST_REGISTER 0x1004
#define SFI_READ_LOCAL_FB_AD_BUS 0x1008
#define SFI_READ_VME2SEQ_DATA_FIFO 0x100C
#define SFI_WRITE_VME_TEST_REGISTER 0x1008
#define SFI_FASTBUS_TIMEOUT_REGISTER 0x2000
#define SFI_FASTBUS_ARBITRATION_LEVEL_REGISTER 0x2004
#define SFI_FASTBUS_PROTOCOL_INLINE_REGISTER 0x2008
#define SFI_SEQUENCER_FIFO_FLAG_AND_ECL_NIM_INPUT_REGISTER 0x200C
#define SFI_NEXT_SEQUENCER_RAM_ADDRESS_REGISTER 0x2018
#define SFI_LAST_SEQUENCER_PROTOCOL_REGISTER 0x201C
#define SFI_SEQUENCER_STATUS_REGISTER 0x2220
#define SFI_FASTBUS_STATUS_REGISTER1 0x2224
#define SFI_FASTBUS_STATUS_REGISTER2 0x2228
#define SFI_VME_IRQ_LEVEL_AND_VECTOR_REGISTER 0x2010
#define SFI_VME_IRQ_MASK_REGISTER 0x2014
#define SFI_SEQUENCER_RAM_ADDRESS_REGISTER 0x2018
#define SFI_RESET_REGISTER_GROUP_LCA2 0x201C
#define SFI_SEQUENCER_ENABLE 0x2020
#define SFI_SEQUENCER_DISABLE 0x2024
#define SFI_SEQUENCER_RAM_LOAD_ENABLE 0x2028
#define SFI_SEQUENCER_RAM_LOAD_DISABLE 0x202C
#define SFI_SEQUENCER_RESET 0x2030
#define SFI_SEQUENCER_TRY_AGAIN 0x2034
#define SFI_READ_SEQ2VME_FIFO_BASE 0x4000
#define SFI_WRITE_VME2SEQ_FIFO_BASE 0x10000
#define PRIM_DSR 0x0004
#define PRIM_CSR 0x0104
#define PRIM_DSRM 0x0204
#define PRIM_CSRM 0x0304
#define PRIM_AMS4 0x0404
#define PRIM_AMS5 0x0504
#define PRIM_AMS6 0x0604
#define PRIM_AMS7 0x0704
#define PRIM_HM_DSR 0x0014
#define PRIM_HM_CSR 0x0114
#define PRIM_HM_DSRM 0x0214
#define PRIM_HM_CSRM 0x0314
#define PRIM_HM_AMS4 0x0414
#define PRIM_HM_AMS5 0x0514
#define PRIM_HM_AMS6 0x0614
#define PRIM_HM_AMS7 0x0714
#define PRIM_EG 0x1000
#define RNDM_R 0x0844
#define RNDM_W 0x0044
#define SECAD_R 0x0A44
#define SECAD_W 0x0244
#define SBLK_W 0x0144
#define SBLK_CLEAN 0x0064
#define RNDM_R_DIS 0x0854
#define RNDM_W_DIS 0x0054
#define SECAD_R_DIS 0x0A54
#define SECAD_W_DIS 0x0254
#define SBLK_CLEAN_DIS 0x0074
#define DISCON 0x0024
#define DISCON_RM 0x0034
#define START_FRDB_WITH_CLEAR_WORD_COUNTER 0x08A4
#define STORE_FRDB_WC 0x00E4
#define STORE_FRDB_AP 0x00D4
#define LOAD_DMA_ADDRESS_POINTER 0x0094
#define DISABLE_RAM_MODE 0x0038
#define ENABLE_RAM_SEQUENCER 0x0028
#define SEQ_WRITE_OUT_REG 0x0008
#define cm_msg(file, routine, msg) printf("[%s:%s] %s", file, routine, msg)
#define MERROR __FILE__
#define MINFO __FILE__
#define REMOTE_RAM_SIZE 0x10000
Functions
int fb_init ()
void fb_exit ()
int fb_reset (void)
static int fb_fifo_read (DWORD *data)
int fb_frd (int paddr, int saddr, DWORD *data)
int fb_frc (int paddr, int saddr, DWORD *data)
int fb_fwd (int paddr, int saddr, DWORD data)
int fb_fwc (int paddr, int saddr, DWORD data)
int fb_fwdm (int paddr, int saddr, DWORD data)
int fb_fwcm (int b_case, int paddr, int saddr, DWORD data)
int fb_frcm (int b_case, DWORD *data)
int fb_frdb (int paddr, int saddr, DWORD *data, int *count)
void fb_frdba (int paddr, int saddr, int count)
int fb_out (DWORD data)
int fb_in (void)
int fb_load_begin (int addr)
int fb_load_end ()
int fb_execute (int addr, void *data, int *count)
void fb_irq_enable (int source)
void fb_irq_disable (int source)
void fb_irq_read (int *source)
void fb_irq_clear (int source)
void fb_interrupt_enable (void)
void fb_interrupt_disable (void)
void application_icbr (void *param_p, bt_irq_t irq_type, bt_data32_t vector)
void fb_interrupt_attach (void(*isr)())
void fb_interrupt_detach (void)
Variables
char * _sfi
bt_desc_t btd
bt_desc_t btd_lm
char * remote_ram_buffer
void(* user_interrupt_routine)() = NULL
Define Documentation
#define BT983
Definition at line 22 of file str340.c.
#define cm_msg (file, routine, msg) printf("[%s:%s] %s", file, routine, msg)
Definition at line 132 of file str340.c.
#define DISABLE_RAM_MODE 0x0038
Definition at line 122 of file str340.c.
#define DISCON 0x0024
Definition at line 112 of file str340.c.
#define DISCON_RM 0x0034
Definition at line 113 of file str340.c.
#define ENABLE_RAM_SEQUENCER 0x0028
Definition at line 124 of file str340.c.
#define LOAD_DMA_ADDRESS_POINTER 0x0094
Definition at line 120 of file str340.c.
#define MERROR __FILE__
Definition at line 134 of file str340.c.
#define MINFO __FILE__
Definition at line 135 of file str340.c.
#define PRIM_AMS4 0x0404
Definition at line 83 of file str340.c.
#define PRIM_AMS5 0x0504
Definition at line 84 of file str340.c.
#define PRIM_AMS6 0x0604
Definition at line 85 of file str340.c.
#define PRIM_AMS7 0x0704
Definition at line 86 of file str340.c.
#define PRIM_CSR 0x0104
Definition at line 80 of file str340.c.
#define PRIM_CSRM 0x0304
Definition at line 82 of file str340.c.
#define PRIM_DSR 0x0004
Definition at line 79 of file str340.c.
#define PRIM_DSRM 0x0204
Definition at line 81 of file str340.c.
#define PRIM_EG 0x1000
Definition at line 97 of file str340.c.
#define PRIM_HM_AMS4 0x0414
Definition at line 92 of file str340.c.
#define PRIM_HM_AMS5 0x0514
Definition at line 93 of file str340.c.
#define PRIM_HM_AMS6 0x0614
Definition at line 94 of file str340.c.
#define PRIM_HM_AMS7 0x0714
Definition at line 95 of file str340.c.
#define PRIM_HM_CSR 0x0114
Definition at line 89 of file str340.c.
#define PRIM_HM_CSRM 0x0314
Definition at line 91 of file str340.c.
#define PRIM_HM_DSR 0x0014
Definition at line 88 of file str340.c.
#define PRIM_HM_DSRM 0x0214
Definition at line 90 of file str340.c.
#define REMOTE_RAM_SIZE 0x10000
Definition at line 148 of file str340.c.
#define RNDM_R 0x0844
Definition at line 99 of file str340.c.
#define RNDM_R_DIS 0x0854
Definition at line 106 of file str340.c.
#define RNDM_W 0x0044
Definition at line 100 of file str340.c.
#define RNDM_W_DIS 0x0054
Definition at line 107 of file str340.c.
#define SBLK_CLEAN 0x0064
Definition at line 104 of file str340.c.
#define SBLK_CLEAN_DIS 0x0074
Definition at line 110 of file str340.c.
#define SBLK_W 0x0144
Definition at line 103 of file str340.c.
#define SECAD_R 0x0A44
Definition at line 101 of file str340.c.
#define SECAD_R_DIS 0x0A54
Definition at line 108 of file str340.c.
#define SECAD_W 0x0244
Definition at line 102 of file str340.c.
#define SECAD_W_DIS 0x0254
Definition at line 109 of file str340.c.
#define SEQ_WRITE_OUT_REG 0x0008
Definition at line 126 of file str340.c.
#define SFI_ADDRESS 0xE00000
Definition at line 33 of file str340.c.
#define SFI_CLEAR_BOTH_LCA1_TEST_REGISTER 0x1004
Definition at line 42 of file str340.c.
#define SFI_FASTBUS_ARBITRATION_LEVEL_REGISTER 0x2004
Definition at line 52 of file str340.c.
#define SFI_FASTBUS_PROTOCOL_INLINE_REGISTER 0x2008
Definition at line 53 of file str340.c.
#define SFI_FASTBUS_STATUS_REGISTER1 0x2224
Definition at line 59 of file str340.c.
#define SFI_FASTBUS_STATUS_REGISTER2 0x2228
Definition at line 60 of file str340.c.
#define SFI_FASTBUS_TIMEOUT_REGISTER 0x2000
Definition at line 51 of file str340.c.
#define SFI_IN (adr) *((DWORD*) (_sfi+(adr)))
Definition at line 32 of file str340.c.
#define SFI_KEY_AUX_PULS_B40 0x1014
Definition at line 44 of file str340.c.
#define SFI_LAST_PRIMADR_REG 0x1004
Definition at line 39 of file str340.c.
#define SFI_LAST_SEQUENCER_PROTOCOL_REGISTER 0x201C
Definition at line 57 of file str340.c.
#define SFI_NEXT_SEQUENCER_RAM_ADDRESS_REGISTER 0x2018
Definition at line 56 of file str340.c.
#define SFI_OUT (adr, data) {*((DWORD*) (_sfi+(adr))) = (data);}
Definition at line 31 of file str340.c.
#define SFI_READ_INT_FB_AD 0x1000
Definition at line 38 of file str340.c.
#define SFI_READ_LOCAL_FB_AD_BUS 0x1008
Definition at line 47 of file str340.c.
#define SFI_READ_SEQ2VME_FIFO_BASE 0x4000
Definition at line 74 of file str340.c.
#define SFI_READ_VME2SEQ_DATA_FIFO 0x100C
Definition at line 48 of file str340.c.
#define SFI_READ_VME_TEST_REGISTER 0x1004
Definition at line 46 of file str340.c.
#define SFI_RESET_REGISTER_GROUP_LCA2 0x201C
Definition at line 65 of file str340.c.
#define SFI_SEQUENCER_DISABLE 0x2024
Definition at line 68 of file str340.c.
#define SFI_SEQUENCER_ENABLE 0x2020
Definition at line 67 of file str340.c.
#define SFI_SEQUENCER_FIFO_FLAG_AND_ECL_NIM_INPUT_REGISTER 0x200C
Definition at line 54 of file str340.c.
#define SFI_SEQUENCER_RAM_ADDRESS_REGISTER 0x2018
Definition at line 64 of file str340.c.
#define SFI_SEQUENCER_RAM_LOAD_DISABLE 0x202C
Definition at line 70 of file str340.c.
#define SFI_SEQUENCER_RAM_LOAD_ENABLE 0x2028
Definition at line 69 of file str340.c.
#define SFI_SEQUENCER_RESET 0x2030
Definition at line 71 of file str340.c.
#define SFI_SEQUENCER_STATUS_REGISTER 0x2220
Definition at line 58 of file str340.c.
#define SFI_SEQUENCER_TRY_AGAIN 0x2034
Definition at line 72 of file str340.c.
#define SFI_SIZE 0x1FFFF
Definition at line 34 of file str340.c.
#define SFI_VME_IRQ_LEVEL_AND_VECTOR_REGISTER 0x2010
Definition at line 62 of file str340.c.
#define SFI_VME_IRQ_MASK_REGISTER 0x2014
Definition at line 63 of file str340.c.
#define SFI_WRITE_INT_FB_AD_REG 0x1010
Definition at line 43 of file str340.c.
#define SFI_WRITE_VME2SEQ_FIFO_BASE 0x10000
Definition at line 75 of file str340.c.
#define SFI_WRITE_VME_OUT_SIGNAL_REGISTER 0x1000
Definition at line 41 of file str340.c.
#define SFI_WRITE_VME_TEST_REGISTER 0x1008
Definition at line 49 of file str340.c.
#define START_FRDB_WITH_CLEAR_WORD_COUNTER 0x08A4
Definition at line 115 of file str340.c.
#define STORE_FRDB_AP 0x00D4
Definition at line 118 of file str340.c.
#define STORE_FRDB_WC 0x00E4
Definition at line 117 of file str340.c.
Function Documentation
void application_icbr (void * param_p, bt_irq_t irq_type, bt_data32_t vector)
Definition at line 611 of file str340.c.
References bt_chkerr(), btd, status, and user_interrupt_routine.
Referenced by fb_interrupt_attach(), and fb_interrupt_detach().
{
   int status;
   status = bt_chkerr(btd);
   if (user_interrupt_routine != NULL)
      user_interrupt_routine();
}
int fb_execute (int addr, void * data, int * count)
Definition at line 522 of file str340.c.
References ENABLE_RAM_SEQUENCER, fb_fifo_read(), remote_ram_buffer, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, status, and SUCCESS.
{
   int ap, status;
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + ENABLE_RAM_SEQUENCER + (addr & 0xFF00), 0);
   if (data == NULL)
      return SUCCESS;
   status = fb_fifo_read(&ap);
   if (status & 0x10000)
      return status & 0xFFFF;
   ap &= 0xFFFFFF;
   if (ap < *count)
      *count = ap;
   /* move data from kernel memory to user buffer */
   memcpy(data, remote_ram_buffer, *count);
   return SUCCESS;
}
void fb_exit (void)
Definition at line 227 of file str340.c.
References _hdio, _sfi, BASE_1691, bt_close(), bt_unmmap(), btd, btd_lm, buffer, fb_exec(), FPREL, remote_ram_buffer, REMOTE_RAM_SIZE, SFI_SIZE, and size.
{
   bt_unmmap(btd, _sfi, SFI_SIZE);
   bt_close(btd);
   bt_unmmap(btd_lm, remote_ram_buffer, REMOTE_RAM_SIZE);
   bt_close(btd_lm);
}
static int fb_fifo_read (DWORD * data) [static]
Definition at line 247 of file str340.c.
References SFI_IN, SFI_READ_SEQ2VME_FIFO_BASE, SFI_SEQUENCER_FIFO_FLAG_AND_ECL_NIM_INPUT_REGISTER, SFI_SEQUENCER_STATUS_REGISTER, status, SUCCESS, and TRUE.
Referenced by fb_execute(), fb_frc(), fb_frcm(), fb_frd(), and fb_frdb().
{
   DWORD status;
   /* wait for sequencer done */
   do {
      status = SFI_IN(SFI_SEQUENCER_STATUS_REGISTER);
      if ((status & 0x8001) == 0)
         /* not initialized */
         return 0x10000 | (status & 0xFFFF);
      if ((status & 0x8001) == 0x8000)
         /* bad status */
         return 0x10000 | (status & 0xFFFF);
      if ((status & 0x8001) == 0x8001) {
         /* OK, check if EMPTY */
         status = SFI_IN(SFI_SEQUENCER_FIFO_FLAG_AND_ECL_NIM_INPUT_REGISTER);
         if (status & 0x10) {
            /* dummy read */
            status = SFI_IN(SFI_READ_SEQ2VME_FIFO_BASE);
            /* check again for EMTPY */
            status = SFI_IN(SFI_SEQUENCER_FIFO_FLAG_AND_ECL_NIM_INPUT_REGISTER);
            if (status & 0x10)
               return 0x10000 | (SFI_IN(SFI_SEQUENCER_STATUS_REGISTER) & 0xFFFF);
         }
         /* read FIFO */
         *data = SFI_IN(SFI_READ_SEQ2VME_FIFO_BASE);
         return SUCCESS;
      }
   } while (TRUE);
}
int fb_frc (int paddr, int saddr, DWORD * data)
Definition at line 296 of file str340.c.
References _RESET, cm_msg, DMARL, DMB_PED_TO_HOST, FALSE, fb_exec(), fb_fifo_read(), fb_load32(), FPAC, FPR, FPWNTA, GO, INPW, MERROR, MWENB, OUTWR, PRIM_CSR, REG1, REG2, REG3, REG4, REG5, REG6, REG7, RNDM_R_DIS, SECAD_W, SFI_IN, SFI_OUT, SFI_SEQUENCER_STATUS_REGISTER, SFI_WRITE_VME2SEQ_FIFO_BASE, status, and TRUE.
{
   int status;
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_CSR, paddr);
   status = SFI_IN(SFI_SEQUENCER_STATUS_REGISTER);
   if (status & 0x20)
      cm_msg(MERROR, "fb_frc", "Arbitration error on Primary Address Cycle");
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + SECAD_W, saddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_R_DIS, 0);
   return fb_fifo_read(data);
}
int fb_frcm (int b_case, DWORD * data)
Definition at line 381 of file str340.c.
References fb_fifo_read(), PRIM_HM_CSRM, RNDM_R_DIS, SFI_OUT, and SFI_WRITE_VME2SEQ_FIFO_BASE.
{
   if (b_case == 3)
      /* case 3 broadcast (sparse data scan) */
      SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_HM_CSRM, 0x09);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_R_DIS, 0);
   return fb_fifo_read(data);
}
int fb_frd (int paddr, int saddr, DWORD * data)
Definition at line 284 of file str340.c.
References _RESET, DMARL, DMB_PED_TO_HOST, FALSE, fb_exec(), fb_fifo_read(), fb_load32(), FPAD, FPR, FPWNTA, GO, INPW, MWENB, OUTWR, PRIM_DSR, REG1, REG2, REG3, REG4, REG5, REG6, REG7, RNDM_R_DIS, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
{
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_DSR, paddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + SECAD_W, saddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_R_DIS, 0);
   return fb_fifo_read(data);
}
int fb_frdb (int paddr, int saddr, DWORD * data, int * count)
Definition at line 399 of file str340.c.
References _RESET, ACTIVE, DISCON, DMARL, DMB_PED_TO_DMEM, DMB_PED_TO_HOST, EAUTO, FALSE, fb_exec(), fb_fifo_read(), fb_load32(), fb_read_data_memory(), FPAD, FPRBL, FPWNTA, GO, i, INPW, IWARDY, LOAD_DMA_ADDRESS_POINTER, MWENB, OUTWR, PA_HOST_TO_SEQ, PD_HOST_TO_SEQ, PD_SEQ_TO_HOST, PRIM_DSR, REG0, REG1, REG2, REG3, REG6, REG7, remote_ram_buffer, SECAD_W, SFI_OUT, SFI_SEQUENCER_DISABLE, SFI_SEQUENCER_ENABLE, SFI_WRITE_VME2SEQ_FIFO_BASE, START_FRDB_WITH_CLEAR_WORD_COUNTER, status, STORE_FRDB_WC, SUCCESS, TRUE, and UP.
{
   int status;
   SFI_OUT(SFI_SEQUENCER_DISABLE, 0);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_DSR, paddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + SECAD_W, saddr);
   /* DMA address 0 (remote ram window) */
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + LOAD_DMA_ADDRESS_POINTER, 0);
   /* VME block mode DMA */
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + START_FRDB_WITH_CLEAR_WORD_COUNTER,
           (0x0A << 24) | (*count / sizeof(DWORD)));
   /* disonnect from module */
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + DISCON, 0);
   /* store word count and adress pointer */
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + STORE_FRDB_WC, 0);
//  SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + STORE_FRDB_AP, 0);
   SFI_OUT(SFI_SEQUENCER_ENABLE, 0);
   status = fb_fifo_read(count);
   if (status & 0x10000)
      return status & 0xFFFF;
//  fb_fifo_read(&ap);
   *count &= 0xFFFFFF;
   *count *= sizeof(DWORD);
   /* move data from kernel memory to user buffer */
   memcpy(data, remote_ram_buffer, *count);
   return SUCCESS;
}
void fb_frdba (int paddr, int saddr, int count)
Definition at line 442 of file str340.c.
References DISCON, PRIM_DSR, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and START_FRDB_WITH_CLEAR_WORD_COUNTER.
{
   /* address module */
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_DSR, paddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + SECAD_W, saddr);
   /* VME block mode DMA */
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + START_FRDB_WITH_CLEAR_WORD_COUNTER,
           (0x0A << 24) | (count / sizeof(DWORD)));
   /* disonnect from module */
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + DISCON, 0);
}
int fb_fwc (int paddr, int saddr, DWORD data)
Definition at line 327 of file str340.c.
References fb_exec(), fb_load32(), FPAC, FPW, FPWNTA, GO, OUTWR, PRIM_CSR, REG1, REG2, REG7, RNDM_W_DIS, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
{
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_CSR, paddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + SECAD_W, saddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_W_DIS, data);
   return SUCCESS;
}
int fb_fwcm (int b_case, int paddr, int saddr, DWORD data)
Definition at line 351 of file str340.c.
References PRIM_HM_CSRM, RNDM_W, RNDM_W_DIS, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
                             : (1<<slot1) | (1<,slot2) | ...
*/
{
   if (b_case == 2) {
      /* case 2 broadcast (class select) */
      SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_HM_CSRM, 0x05);
      SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_W, paddr);
   }
   if (b_case == 3) {
      /* case 3 broadcast (pattern select) */
      SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_HM_CSRM, 0x09);
      SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_W, paddr);
   }
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + SECAD_W, saddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_W_DIS, data);
   return SUCCESS;
}
int fb_fwd (int paddr, int saddr, DWORD data)
Definition at line 315 of file str340.c.
References fb_exec(), fb_load32(), FPAC, FPW, FPWNTA, GO, OUTWR, PRIM_DSR, REG1, REG2, REG7, RNDM_W_DIS, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
{
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_DSR, paddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + SECAD_W, saddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_W_DIS, data);
   return SUCCESS;
}
int fb_fwdm (int paddr, int saddr, DWORD data)
Definition at line 339 of file str340.c.
References PRIM_DSRM, RNDM_W_DIS, SECAD_W, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
{
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + PRIM_DSRM, paddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + SECAD_W, saddr);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + RNDM_W_DIS, data);
   return SUCCESS;
}
int fb_in (void)
Definition at line 478 of file str340.c.
References fb_exec(), IN1TST, INPW, OUTWR, PA_HOST_TO_SEQ, PD_HOST_TO_SEQ, PD_SEQ_TO_HOST, REG0, REG2, SFI_IN, and SFI_SEQUENCER_FIFO_FLAG_AND_ECL_NIM_INPUT_REGISTER.
            : ECL input
   bit 12-15: NIM input */
{
   return (int) SFI_IN(SFI_SEQUENCER_FIFO_FLAG_AND_ECL_NIM_INPUT_REGISTER);
}
int fb_init (void)
Definition at line 153 of file str340.c.
References _hdio, _RESET, _sfi, ACTIVE, addr, ARB_LEVEL, BASE_1691, BT_AMOD_A24_SD, bt_close(), bt_clrerr(), bt_gen_name(), bt_get_info(), bt_init(), BT_MAX_DEV_NAME, bt_mmap(), bt_open(), BT_RDWR, bt_set_info(), BT_SUCCESS, BT_SWAP_DEFAULT, btd, btd_lm, buffer, BYPASS, cm_msg, data, FALSE, fb_exec(), FBARB, flag, FPCLBS, FPRBUS, FPREQ, i, IDLE, INPW, MERROR, OUTP, OUTWR, PA_HOST_TO_SEQ, PA_MENU_TO_SEQ, patch_table, PD_HOST_TO_SEQ, PD_MENU_TO_HOST, PD_PMAR_TO_SEQ, PLOAD, PMADL, PMADZ, PWR_1, PWR_2, RCL, REG0, REG1, REG2, REG3, REG4, REG5, REG6, REG7, remote_ram_buffer, REMOTE_RAM_SIZE, ROM_NO, ROM_UPD, ROM_VER, SFI_ADDRESS, SFI_CLEAR_BOTH_LCA1_TEST_REGISTER, SFI_FASTBUS_ARBITRATION_LEVEL_REGISTER, SFI_FASTBUS_TIMEOUT_REGISTER, SFI_OUT, SFI_RESET_REGISTER_GROUP_LCA2, SFI_SEQUENCER_ENABLE, SFI_SEQUENCER_RESET, SFI_SIZE, size, SQWRT, status, and SUCCESS.
{
   bt_error_t status;           /* Bit 3 library error return type */
   char devname[BT_MAX_DEV_NAME];       /* Device to open */
   bt_devdata_t flag;
   /* Open the device in A24 space */
   bt_gen_name(0, BT_DEV_A24, devname, BT_MAX_DEV_NAME);
   status = bt_open(&btd, devname, BT_RDWR);
   if (status != BT_SUCCESS) {
      cm_msg(MERROR, "fb_init", "Cannot open Bit3 device driver");
      return FALSE;
   }
   bt_init(btd);
   bt_clrerr(btd);
   /* map SFI memory */
   status = bt_mmap(btd, &_sfi, SFI_ADDRESS, SFI_SIZE, BT_RDWR, BT_SWAP_DEFAULT);
   if (status != BT_SUCCESS) {
      cm_msg(MERROR, "fb_init", "Cannot map VME memory");
      bt_close(btd);
      return FALSE;
   }
   /* Open the device in local memory */
   bt_gen_name(0, BT_DEV_LM, devname, BT_MAX_DEV_NAME);
   status = bt_open(&btd_lm, devname, BT_RDWR);
   if (status != BT_SUCCESS) {
      cm_msg(MERROR, "fb_init", "Cannot open Bit3 device for local memory");
      return FALSE;
   }
   bt_clrerr(btd_lm);
   /* map local memory */
   status =
       bt_mmap(btd_lm, &remote_ram_buffer, 0, REMOTE_RAM_SIZE, BT_RDWR, BT_SWAP_DEFAULT);
   if (status != BT_SUCCESS) {
      cm_msg(MERROR, "fb_init", "Cannot map local memory");
      bt_close(btd);
      return FALSE;
   }
   /* clear local memory */
   memset(remote_ram_buffer, 0, REMOTE_RAM_SIZE);
   /* force D32 mode */
   bt_get_info(btd, BT_INFO_MMAP_AMOD, &flag);
   flag = BT_AMOD_A24_SD;
   bt_set_info(btd, BT_INFO_MMAP_AMOD, flag);
   /* sequencer reset */
   SFI_OUT(SFI_SEQUENCER_RESET, 0);
   /* arbitration level */
//  SFI_OUT(SFI_FASTBUS_ARBITRATION_LEVEL_REGISTER, 0x15);
   SFI_OUT(SFI_FASTBUS_ARBITRATION_LEVEL_REGISTER, 0xBF);
   /* timeout */
   SFI_OUT(SFI_FASTBUS_TIMEOUT_REGISTER, 0x73);
   /* sequencer enable */
   SFI_OUT(SFI_SEQUENCER_ENABLE, 0);
   /* switch off all output */
   SFI_OUT(SFI_CLEAR_BOTH_LCA1_TEST_REGISTER, 0);
   /* clear registers */
   SFI_OUT(SFI_RESET_REGISTER_GROUP_LCA2, 0);
   return SUCCESS;
}
void fb_interrupt_attach (void(*)() isr)
Definition at line 623 of file str340.c.
References application_icbr(), bt_icbr_install(), BT_IRQ_IACK, bt_perror(), BT_SUCCESS, BT_VECTOR_ALL, btd, isr, status, and user_interrupt_routine.
{
   int status;
   user_interrupt_routine = isr;
   status = bt_icbr_install(btd, BT_IRQ_IACK, application_icbr, NULL, BT_VECTOR_ALL);
   if (status != BT_SUCCESS)
      bt_perror(btd, status, "Could not install interrupt call back routine.");
}
void fb_interrupt_detach (void)
Definition at line 635 of file str340.c.
References application_icbr(), bt_icbr_remove(), BT_IRQ_IACK, btd, and user_interrupt_routine.
{
   bt_icbr_remove(btd, BT_IRQ_IACK, application_icbr);
   user_interrupt_routine = NULL;
}
void fb_interrupt_disable (void)
Definition at line 601 of file str340.c.
References SFI_OUT, and SFI_VME_IRQ_LEVEL_AND_VECTOR_REGISTER.
{
   /* VME IRQ Level 1 */
   SFI_OUT(SFI_VME_IRQ_LEVEL_AND_VECTOR_REGISTER, 0x000);
}
void fb_interrupt_enable (void)
Definition at line 593 of file str340.c.
References SFI_OUT, and SFI_VME_IRQ_LEVEL_AND_VECTOR_REGISTER.
{
   /* VME IRQ Level 1 */
   SFI_OUT(SFI_VME_IRQ_LEVEL_AND_VECTOR_REGISTER, 0x800 | 0x100);
}
void fb_irq_clear (int source)
Definition at line 580 of file str340.c.
References SFI_OUT, and SFI_VME_IRQ_MASK_REGISTER.
         : NIM1
   bit 1 : NIM2
   bit 2 : NIM3
   bit 3 : ECL1 */
{
   SFI_OUT(SFI_VME_IRQ_MASK_REGISTER, source << 8);
   SFI_OUT(SFI_VME_IRQ_MASK_REGISTER, source);
}
void fb_irq_disable (int source)
Definition at line 560 of file str340.c.
References SFI_OUT, and SFI_VME_IRQ_MASK_REGISTER.
         : NIM1
   bit 1 : NIM2
   bit 2 : NIM3
   bit 3 : ECL1 */
{
   SFI_OUT(SFI_VME_IRQ_MASK_REGISTER, source << 8);
}
void fb_irq_enable (int source)
Definition at line 548 of file str340.c.
References SFI_OUT, and SFI_VME_IRQ_MASK_REGISTER.
         : NIM1
   bit 1 : NIM2
   bit 2 : NIM3
   bit 3 : ECL1 */
{
   SFI_OUT(SFI_VME_IRQ_MASK_REGISTER, source);
}
void fb_irq_read (int * source)
Definition at line 572 of file str340.c.
References SFI_IN, and SFI_VME_IRQ_MASK_REGISTER.
{
   *source = (SFI_IN(SFI_VME_IRQ_MASK_REGISTER) >> 8) & 0xFF;
}
int fb_load_begin (int addr)
Definition at line 488 of file str340.c.
References LOAD_DMA_ADDRESS_POINTER, SFI_NEXT_SEQUENCER_RAM_ADDRESS_REGISTER, SFI_OUT, SFI_SEQUENCER_RAM_LOAD_ENABLE, SFI_SEQUENCER_RESET, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
{
   SFI_OUT(SFI_SEQUENCER_RESET, 0);
   SFI_OUT(SFI_NEXT_SEQUENCER_RAM_ADDRESS_REGISTER, addr);
   SFI_OUT(SFI_SEQUENCER_RAM_LOAD_ENABLE, 0);
   /* initialize DMA address */
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + LOAD_DMA_ADDRESS_POINTER, 0);
   return SUCCESS;
}
int fb_load_end (void)
Definition at line 503 of file str340.c.
References DISABLE_RAM_MODE, SFI_OUT, SFI_SEQUENCER_ENABLE, SFI_SEQUENCER_RAM_LOAD_DISABLE, SFI_WRITE_VME2SEQ_FIFO_BASE, SFI_WRITE_VME_OUT_SIGNAL_REGISTER, STORE_FRDB_AP, and SUCCESS.
{
   /* last command: store address pointer */
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + STORE_FRDB_AP, 0);
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + DISABLE_RAM_MODE, 0);
   /* 2us delay */
   SFI_OUT(SFI_WRITE_VME_OUT_SIGNAL_REGISTER, 0);
   SFI_OUT(SFI_SEQUENCER_RAM_LOAD_DISABLE, 0);
   SFI_OUT(SFI_SEQUENCER_ENABLE, 0);
   return SUCCESS;
}
int fb_out (DWORD data)
Definition at line 459 of file str340.c.
References SEQ_WRITE_OUT_REG, SFI_OUT, SFI_WRITE_VME2SEQ_FIFO_BASE, and SUCCESS.
            : set LED
   bit 4-7  : set ECL
   bit 8-10 : set NIM
   bit 16-19: clear LED
   bit 20-23: clear ECL
   bit 24-26: clear NIM */
{
   /* directly access output register */
   /* SFI_OUT(SFI_WRITE_VME_OUT_SIGNAL_REGISTER, data); */
   /* ask the sequencer to write to the output */
   SFI_OUT(SFI_WRITE_VME2SEQ_FIFO_BASE + SEQ_WRITE_OUT_REG, data);
   return SUCCESS;
}
int fb_reset (void)
Definition at line 237 of file str340.c.
References fb_exec(), FPRBUS, SFI_OUT, SFI_SEQUENCER_ENABLE, SFI_SEQUENCER_RESET, and SUCCESS.
{
   SFI_OUT(SFI_SEQUENCER_RESET, 0);
   SFI_OUT(SFI_SEQUENCER_ENABLE, 0);
   return SUCCESS;
}
Variable Documentation
char* _sfi
Definition at line 142 of file str340.c.
bt_desc_t btd
Definition at line 145 of file str340.c.
Referenced by application_icbr(), fb_exit(), fb_init(), fb_interrupt_attach(), fb_interrupt_detach(), and vme_open().
bt_desc_t btd_lm
Definition at line 145 of file str340.c.
Referenced by fb_exit(), and fb_init().
char* remote_ram_buffer
Definition at line 149 of file str340.c.
void(* user_interrupt_routine)() = NULL
Referenced by application_icbr(), fb_interrupt_attach(), and fb_interrupt_detach().