AlcapDAQ:Rootana: midas/mxml/strlcpy.h File Reference
midas/mxml/strlcpy.h File Reference
Functions
size_t EXPRT strlcpy (char *dst, const char *src, size_t size)
size_t EXPRT strlcat (char *dst, const char *src, size_t size)
Function Documentation
size_t EXPRT strlcat (char * dst, const char * src, size_t size)
Definition at line 445 of file mscb.c.
References d, and n.
Referenced by db_save_xml_key(), debug_print(), receive_message(), sendmail(), submit_elog(), and xml_encode().
{
   char *d = dst;
   const char *s = src;
   size_t n = size;
   size_t dlen;
   /* Find the end of dst and adjust bytes left but don't go past end */
   while (n-- != 0 && *d != '\0')
      d++;
   dlen = d - dst;
   n = size - dlen;
   if (n == 0)
      return (dlen + strlen(s));
   while (*s != '\0') {
      if (n != 1) {
         *d++ = *s;
         n--;
      }
      s++;
   }
   *d = '\0';
   return (dlen + (s - src));   /* count does not include NUL */
}
size_t EXPRT strlcpy (char * dst, const char * src, size_t size)
Definition at line 414 of file mscb.c.
References d, and n.
Referenced by cm_get_environment(), cm_scan_experiments(), db_create_record(), db_sprintf(), decode_post(), interprete(), mscb_init(), mscb_select_device(), sendmail(), setparam(), ss_shell(), and xml_encode().
{
   char *d = dst;
   const char *s = src;
   size_t n = size;
   /* Copy as many bytes as will fit */
   if (n != 0 && --n != 0) {
      do {
         if ((*d++ = *s++) == 0)
            break;
      } while (--n != 0);
   }
   /* Not enough room in dst, add NUL and traverse rest of src */
   if (n == 0) {
      if (size != 0)
         *d = '\0';             /* NUL-terminate dst */
      while (*s++);
   }
   return (s - src - 1);        /* count does not include NUL */
}