AlcapDAQ:Rootana: SUSPEND_STRUCT Struct Reference
SUSPEND_STRUCT Struct Reference
[System Functions (ss_xxx)]
Data Fields
BOOL in_use
INT thread_id
INT ipc_port
INT ipc_recv_socket
INT ipc_send_socket
INT(* ipc_dispatch)(char *, INT)
INT listen_socket
INT(* listen_dispatch)(INT)
RPC_SERVER_CONNECTION * server_connection
INT(* client_dispatch)(INT)
RPC_SERVER_ACCEPTION * server_acception
INT(* server_dispatch)(INT, int, BOOL)
struct sockaddr_in bind_addr
Detailed Description
Definition at line 2936 of file system.c.
Field Documentation
struct sockaddr_in SUSPEND_STRUCT::bind_addr [read]
Definition at line 2949 of file system.c.
Referenced by ss_resume().
INT(* SUSPEND_STRUCT::client_dispatch)(INT)
Referenced by ss_suspend(), and ss_suspend_set_dispatch().
BOOL SUSPEND_STRUCT::in_use
Definition at line 2937 of file system.c.
Referenced by ss_suspend_get_index().
INT(* SUSPEND_STRUCT::ipc_dispatch)(char *, INT)
Referenced by ss_suspend(), and ss_suspend_set_dispatch().
INT SUSPEND_STRUCT::ipc_port
Definition at line 2939 of file system.c.
Referenced by ss_suspend_get_port(), and ss_suspend_init_ipc().
INT SUSPEND_STRUCT::ipc_recv_socket
Definition at line 2940 of file system.c.
Referenced by ss_suspend_init_ipc().
INT SUSPEND_STRUCT::ipc_send_socket
Definition at line 2941 of file system.c.
Referenced by ss_suspend_init_ipc().
INT(* SUSPEND_STRUCT::listen_dispatch)(INT)
Referenced by ss_suspend(), and ss_suspend_set_dispatch().
INT SUSPEND_STRUCT::listen_socket
Definition at line 2943 of file system.c.
Referenced by ss_suspend(), and ss_suspend_set_dispatch().
RPC_SERVER_ACCEPTION* SUSPEND_STRUCT::server_acception
Definition at line 2947 of file system.c.
Referenced by ss_suspend(), and ss_suspend_set_dispatch().
RPC_SERVER_CONNECTION* SUSPEND_STRUCT::server_connection
Definition at line 2945 of file system.c.
Referenced by ss_suspend(), and ss_suspend_set_dispatch().
INT(* SUSPEND_STRUCT::server_dispatch)(INT, int, BOOL)
Referenced by ss_suspend(), and ss_suspend_set_dispatch().
INT SUSPEND_STRUCT::thread_id
Definition at line 2938 of file system.c.
Referenced by ss_suspend_get_index().
The documentation for this struct was generated from the following file:
midas/src/system.c