AlcapDAQ:Rootana: midas/examples/ybosexpt/ybos_simfe.c File Reference
midas/examples/ybosexpt/ybos_simfe.c File Reference
#include <stdio.h>
#include "midas.h"
#include "msystem.h"
#include "ybos.h"
#include "mcstd.h"
#include "esone.h"
Defines
#define CRATE 1
#define LAM_SLOT 1
Functions
INT frontend_init ()
INT frontend_exit ()
INT begin_of_run (INT run_number, char *error)
INT end_of_run (INT run_number, char *error)
INT pause_run (INT run_number, char *error)
INT resume_run (INT run_number, char *error)
INT frontend_loop ()
INT read_trigger_event (char *pevent, INT off)
INT read_scaler_event (char *pevent, INT off)
INT files_dump (char *pevent, INT off)
INT poll_event (INT source, INT count, BOOL test)
INT interrupt_configure (INT cmd, INT source[], PTYPE adr)
Variables
INT poll_val = 10
INT tr1 = 16
INT tr2 = 200
char * frontend_name = "YbosFE"
char * frontend_file_name = __FILE__
BOOL frontend_call_loop = FALSE
INT display_period = 3000
INT max_event_size = 10000
INT event_buffer_size = 10 * 10000
INT gbl_run_number
EQUIPMENT equipment []
Define Documentation
#define CRATE 1
Definition at line 53 of file ybos_simfe.c.
#define LAM_SLOT 1
Definition at line 54 of file ybos_simfe.c.
Referenced by interrupt_configure().
Function Documentation
INT begin_of_run (INT run_number, char * error)
Definition at line 200 of file ybos_simfe.c.
References cdreg(), cfsa(), d, ext, gbl_run_number, and SUCCESS.
{
   int ext, q;
   unsigned long d;
   /* put here clear scalers etc. */
   gbl_run_number = run_number;
   cdreg(&ext, 1, 2, 3, 4);
   cfsa(16, ext, &d, &q);
   return SUCCESS;
}
INT end_of_run (INT run_number, char * error)
Definition at line 214 of file ybos_simfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT files_dump (char * pevent, INT off)
Definition at line 345 of file ybos_simfe.c.
References equipment, feodb_file_dump(), and gbl_run_number.
{
   feodb_file_dump(equipment, "File", pevent, gbl_run_number, "trigger");
   /* return 0 because I handle the "event send" by myself */
   return 0;
}
INT frontend_exit (void)
Definition at line 192 of file ybos_simfe.c.
References cam_exit(), and SUCCESS.
{
   cam_exit();
   return SUCCESS;
}
INT frontend_init (void)
Definition at line 183 of file ybos_simfe.c.
References cam_init(), and SUCCESS.
{
   /* put here hardware initialization */
   cam_init();
   return SUCCESS;
}
INT frontend_loop (void)
Definition at line 235 of file ybos_simfe.c.
References SUCCESS.
{
   /* if frontend_call_loop is true, this routine gets called when
      the frontend is idle or between every event */
   return SUCCESS;
}
INT interrupt_configure (INT cmd, INT source[], PTYPE adr)
Definition at line 269 of file ybos_simfe.c.
References cam_interrupt_attach(), cam_interrupt_detach(), cam_interrupt_disable(), cam_interrupt_enable(), CMD_INTERRUPT_ATTACH, CMD_INTERRUPT_DETACH, CMD_INTERRUPT_DISABLE, CMD_INTERRUPT_ENABLE, CRATE, LAM_SLOT, and SUCCESS.
{
   switch (cmd) {
   case CMD_INTERRUPT_ENABLE:
      cam_interrupt_enable(CRATE);
      break;
   case CMD_INTERRUPT_DISABLE:
      cam_interrupt_disable(CRATE);
      break;
   case CMD_INTERRUPT_ATTACH:
      cam_interrupt_attach(CRATE, LAM_SLOT, (void (*)(void)) adr);
      break;
   case CMD_INTERRUPT_DETACH:
      cam_interrupt_detach(CRATE, LAM_SLOT);
      break;
   }
   return SUCCESS;
}
INT pause_run (INT run_number, char * error)
Definition at line 221 of file ybos_simfe.c.
References SUCCESS.
{
   return SUCCESS;
}
INT poll_event (INT source, INT count, BOOL test)
Definition at line 252 of file ybos_simfe.c.
References FALSE, i, poll_val, and TRUE.
{
   INT i;
   for (i = 0; i < count; i++) {
      /* read the LAM register of the Crate controller to find out if
         ANY station has raised the LAM line.
       */
      if (rand() % 10000 < poll_val)    /* Ignore LAM if not LAM_STATION */
         if (!test)
            return TRUE;
   }
   return FALSE;
}
INT read_scaler_event (char * pevent, INT off)
Definition at line 327 of file ybos_simfe.c.
References bk_close(), bk_create(), bk_init(), bk_size(), cam24i(), CRATE, i, I4_BKTYPE, N_SCLR, Sclx, SLOT_SCLR, TID_DWORD, ybk_close(), ybk_create(), ybk_init(), and ybk_size().
{
   DWORD i;
   DWORD *pbkdat;
   ybk_init((DWORD *) pevent);
   /* collect user hardware data */
  /*---- USER Stuff ----*/
   ybk_create((DWORD *) pevent, "SCAL", I4_BKTYPE, (DWORD *) (&pbkdat));
   for (i = 0; i < 16; i++)
      *pbkdat++ = (DWORD) (0xff + i) & 0xFFF;
   ybk_close((DWORD *) pevent, pbkdat);
   return (ybk_size((DWORD *) pevent));
}
INT read_trigger_event (char * pevent, INT off)
Definition at line 290 of file ybos_simfe.c.
References D8_BKTYPE, i, I2_BKTYPE, I4_BKTYPE, j, tr1, tr2, ybk_close(), ybk_close_chaos(), ybk_create(), ybk_create_chaos(), ybk_init(), and ybk_size().
{
   INT i, j;
   double *pbkdat;
   ybk_init((DWORD *) pevent);
   j = rand() % 100;
   if (j < tr1)
      j = tr1;
   else if (j > tr2)
      j = tr2;
   ybk_create((DWORD *) pevent, "ADC0", I4_BKTYPE, (DWORD *) (&pbkdat));
   for (i = 0; i < j; i++)
      *((DWORD *) pbkdat)++ = i & 0xFFF;
   ybk_close((DWORD *) pevent, pbkdat);
   ybk_create((DWORD *) pevent, "TDC0", I2_BKTYPE, (DWORD *) (&pbkdat));
   for (i = 0; i < 16; i++)
      *((WORD *) pbkdat)++ = (WORD) (0x10 + i) & 0xFFFF;
   ybk_close((DWORD *) pevent, pbkdat);
   ybk_create_chaos((DWORD *) pevent, "OTHR", I2_BKTYPE, (DWORD *) (&pbkdat));
   for (i = 0; i < 16; i++)
      *((WORD *) pbkdat)++ = (WORD) (0x20 + i + 1) & 0xFFFF;
   ybk_close_chaos((DWORD *) pevent, I2_BKTYPE, pbkdat);
   ybk_create((DWORD *) pevent, "EFGH", D8_BKTYPE, (DWORD *) (&pbkdat));
   for (i = 0; i < 6; i++)
      *pbkdat++ = (double) i + 10.;
   ybk_close((DWORD *) pevent, pbkdat);
   /* END OF EVENT */
   return (ybk_size((DWORD *) pevent));
}
INT resume_run (INT run_number, char * error)
Definition at line 228 of file ybos_simfe.c.
References SUCCESS.
{
   return SUCCESS;
}
Variable Documentation
INT display_period = 3000
Definition at line 66 of file ybos_simfe.c.
EQUIPMENT equipment[]
Definition at line 91 of file ybos_simfe.c.
INT event_buffer_size = 10 * 10000
Definition at line 72 of file ybos_simfe.c.
BOOL frontend_call_loop = FALSE
Definition at line 63 of file ybos_simfe.c.
char* frontend_file_name = __FILE__
Definition at line 60 of file ybos_simfe.c.
char* frontend_name = "YbosFE"
Definition at line 58 of file ybos_simfe.c.
INT gbl_run_number
Definition at line 86 of file ybos_simfe.c.
Referenced by begin_of_run(), and files_dump().
INT max_event_size = 10000
Definition at line 69 of file ybos_simfe.c.
INT poll_val = 10
Definition at line 55 of file ybos_simfe.c.
Referenced by poll_event().
INT tr1 = 16
Definition at line 56 of file ybos_simfe.c.
Referenced by read_trigger_event().
INT tr2 = 200
Definition at line 56 of file ybos_simfe.c.
Referenced by read_trigger_event().